### ISSUE TITLE
SevenZip ERROR

### ISSUE THREAD

**Issue by DKeppi** [pyload/pyload#1000]
WARNING	ExtractArchive: Konnte SevenZip nicht aktivieren | 'NoneType' object has no attribute 'SevenZip'

There is no internal plugin SevenZip available - when you would release that plugin?
I think the ERROR comes from the missing plugin?

**Comment by vuolter** [comment]
50% ready.

**Comment by DKeppi** [comment]
THX!

**Comment by Gutz-Pilz** [comment]
looking forward!

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/8848a359a43316fb346b728d1d79d7b72d27e5a0
