### ISSUE TITLE
Rewrite Click'n'Load hook plugin

### ISSUE THREAD

**Issue by vuolter** [pyload/pyload#1001]
Issue: Infinite thread loop
See: https://github.com/pyload/pyload/issues/935
Related to: https://github.com/pyload/pyload/issues/381 https://github.com/pyload/pyload/issues/774

**Comment by JustinS-B** [comment]
While you're at it, one of the things that crops up in various forum discussions on this topic is the request for the ability to user define the clickandload port to something other than 9666. 

It would help if it was available on the "Config" page of the Webinterface, in the same way that General -> Menu -> Webinterface   lets us turn on SSL & set the IP & port for the Webinterface, or   General -> Menu -> Remote   which does the same thing for Remote.

Thanks.

**Comment by JustinS-B** [comment]
Is there any possibility of a user definable clickandload port, similar to the way that the Webinterface & Remote ports can be configured in the Config interface? It already has a Plugin Config page, so it could slot in there...

**Comment by vuolter** [comment]
No problem.

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/354ecbc78898efb4a31a7272e5ea1f5e00a53327

**Comment by JustinS-B** [comment]
Hi vuolter :-)

Unfortunately, this hasn't worked...

I get this popup when I try to load a link from flashgot:

pyLoad is not responding on http://192.168.44.1:9666/flashgot!
Please check your firewall settings and the pyLoad configuration for the 'ClickAndLoad' plugin.
Or try to restart pyLoad or the device itself (pyLoad may not be responding properly after some time).

& if I try loading http://192.168.44.1:9666/flashgot into firefox, I get "The connection was reset"

Terminal debugging gives:

04.01.2015 20:07:02 INFO      pyLoad is up and running
04.01.2015 20:08:44 ERROR     ClickAndLoad: [Errno 111] Connection refused
04.01.2015 20:08:45 WARNING   ClickAndLoad: Port 9666 already in use

& the pyload logs give exactly the same info:

1031	04.01.2015 20:07:02	INFO	pyLoad is up and running
1032	04.01.2015 20:08:44	ERROR	ClickAndLoad: [Errno 111] Connection refused
1033	04.01.2015 20:08:45	WARNING	ClickAndLoad: Port 9666 already in use 

**Also**, any changes to the port settings are lost when you restart pyload as it defaults back to 9666

**Also**, any changes don't show up using netstat -lnptu as it is still listening on port 9666

**Also**, netstat -lnptu before'n'after shows that it stops listening on port 9666 when it rejects it

Is there anything else that I can do to help on this one, apart from testing the code as it lands?

Thanks, J.

**Comment by vuolter** [comment]
@JustinS-B Please refer to https://github.com/pyload/pyload/issues/774. This issue is closed. Port changing works for me, but I know there is a really annoying bug in config framework, that prevent settings saving sometimes.
