### ISSUE TITLE
SerienJunkies.org does not work "No module named ... "

### ISSUE THREAD

**Issue by mbosner** [pyload/pyload#1002]
I tested the serienjunkies.org crypter plugin today with 8d12319 and i got this:

02.01.2015 18:21:16 ERROR Error importing SerienjunkiesOrg: No module named SerienjunkiesOrg
02.01.2015 18:21:16 CRITICAL 'NoneType' object has no attribute 'SerienjunkiesOrg'
Traceback (most recent call last):
File "/data/media/bin/pyload-versions/stable/module/ThreadManager.py", line 276, in assignJob
job.initPlugin()
File "/data/media/bin/pyload-versions/stable/module/utils.py", line 165, in new
return func(*args)
File "/data/media/bin/pyload-versions/stable/module/PyFile.py", line 102, in initPlugin
self.pluginclass = getattr(self.pluginmodule, self.m.core.pluginManager.getPluginName(self.pluginname))
AttributeError: 'NoneType' object has no attribute 'SerienjunkiesOrg'

stable/config/userplugins/crypter$ ls -l SerienjunkiesOrg.p*
-rw-rw-r-- 1 14610 Dec 31 02:50 SerienjunkiesOrg.py
-rw-rw-r-- 1 13711 Dec 31 02:50 SerienjunkiesOrg.pyc

"zip" version does work but has other issues.

I commented the same problem on https://github.com/pyload/pyload/issues/829 and did not see that it was already closed - sorry.

**Comment by vuolter** [comment]
We cannot offer support for SerienjunkiesOrg et simila. Anyway this error come out when there are syntax error in the code, maybe rusult of the recent changes in SimpleCrypter (which SerienjunkiesOrg is based). Try on the forum. There're some thread about that kind of stuff in the german section.
