### ISSUE TITLE
StreamCloud plugin error: downloadlink could not be found

### ISSUE THREAD

**Issue by Spedy123456** [pyload/pyload#1003]
If I want to download a video on streamcloud by putting the links into pyLoad i get this error:
02.01.2015 23:28:37	INFO	Download starts: itn-pretty.s01e09.xvid.avi
02.01.2015 23:28:44	ERROR	StreamcloudEu: download1
02.01.2015 23:28:44	WARNING	Download failed: itn-pretty.s01e09.xvid.avi | Download link not found
02.01.2015 23:28:44	INFO	UnSkipOnFail: Looking for skipped duplicates of: itn-pretty.s01e09.xvid.avi (pid:7)
02.01.2015 23:28:44	INFO	UnSkipOnFail: No duplicates found
02.01.2015 23:28:45	INFO	Download starts: itn-pretty.s01e10.xvid.avi
02.01.2015 23:28:51	ERROR	StreamcloudEu: download1
02.01.2015 23:28:51	WARNING	Download failed: itn-pretty.s01e10.xvid.avi | Download link not found
02.01.2015 23:28:51	INFO	UnSkipOnFail: Looking for skipped duplicates of: itn-pretty.s01e10.xvid.avi (pid:7)
02.01.2015 23:28:51	INFO	UnSkipOnFail: No duplicates found
02.01.2015 23:28:53	INFO	Download starts: itn-pretty.s01e11.xvid.avi
02.01.2015 23:28:58	ERROR	StreamcloudEu: download1
02.01.2015 23:28:58	WARNING	Download failed: itn-pretty.s01e11.xvid.avi | Download link not found
02.01.2015 23:28:58	INFO	UnSkipOnFail: Looking for skipped duplicates of: itn-pretty.s01e11.xvid.avi (pid:7)
02.01.2015 23:28:58	INFO	UnSkipOnFail: No duplicates found
02.01.2015 23:28:59	INFO	Download starts: itn-pretty.s01e12.xvid.avi
02.01.2015 23:29:05	ERROR	StreamcloudEu: download1
02.01.2015 23:29:05	WARNING	Download failed: itn-pretty.s01e12.xvid.avi | Download link not found
02.01.2015 23:29:05	INFO	UnSkipOnFail: Looking for skipped duplicates of: itn-pretty.s01e12.xvid.avi (pid:7)
02.01.2015 23:29:05	INFO	UnSkipOnFail: No duplicates found

This error I get with ANY video on streamcloud. Streamcloud must have changed their website structure or so... Please update the StreamCloud plugin, thx!

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/d811bb9a436888e5c0f50c71fb6cdafa053ceb51

**Comment by Spedy123456** [comment]
Thanks, its working!
