### ISSUE TITLE
rehost.to AND nopremium.pl not working

### ISSUE THREAD

**Issue by Fr3shF1sh** [pyload/pyload#1009]
Hi, 
both plugins are not working. 
For rehost.to the error is:
 04.01.2015 22:48:27 INFO      RehostTo: Reloading supported hoster list
 04.01.2015 22:48:27 ERROR     RehostTo: 'RehostTo' object has no attribute 'long_ses' 
04.01.2015 22:48:27 ERROR     RehostTo: No hoster loaded

**Comment by Shuralon** [comment]
I got the same issue. If you restart pyload you will also see:
ERROR	Error executing hooks: 'ses'

**Comment by vuolter** [comment]
rehost.to fixup coming, please append the full debug log for nopremium.pl
