### ISSUE TITLE
ExtractArchive doesn't use user_passwords.txt

### ISSUE THREAD

**Issue by kasperj** [pyload/pyload#1011]
I've got the right password in my user_passwords.txt, but ExtractArchive seems not to use the file in the newest version!

05.01.2015 10:03:59 WARNING ExtractArchive: NLAG7p.602.part1.rar | No files extracted
05.01.2015 10:03:59 ERROR   ExtractArchive: NLAG7p.602.part1.rar | Extract failed
05.01.2015 10:03:59 ERROR   ExtractArchive: NLAG7p.602.part1.rar | No password found    05.01.2015 10:03:59 INFO    ExtractArchive: NLAG7p.602.part1.rar | Password protected   05.01.2015 10:03:59 INFO    ExtractArchive: NLAG7p.602.part1.rar | Verifying... 05.01.2015 10:03:59 INFO    ExtractArchive: NLAG7p.602.part1.rar | Extract to: /mnt/video/download/NLAG7p.602/  05.01.2015 10:03:59 INFO    ExtractArchive: Check package: NLAG7p.602   05.01.2015 10:03:59 INFO    Package finished: NLAG7p.602

**Comment by Gutz-Pilz** [comment]
same here!

**Comment by Gutz-Pilz** [comment]
and ...i can not activate 'delete after succesfully extracted'.
so it stays on FALSE forever

**Comment by kasperj** [comment]
I can activate 'delete on succesful extract' but it's not saved, so the setting is disabled after the next restart/reload. Another thing that is broken is the extraction progress and the status, status is extracting forever eben after succesful extraction

**Comment by Pulper** [comment]
You can edit the ExtractArchive.py and set it to "True".

Please take this issue also into account:
http://forum.pyload.org/viewtopic.php?f=12&t=3884 

It seems that ExtractArchive cannot handle files with a password (see thread)

**Comment by vuolter** [comment]
Okay guys, I'm checking ExtractArchive just now. Please wait...

**Comment by Pulper** [comment]
Any news?

**Comment by vuolter** [comment]
I'll try to fix it for tomorrow.

**Comment by ananias47** [comment]
olso i have this on log:WARNING	ExtractArchive: Could not activate SevenZip | 'NoneType' object has no attribute 'SevenZip'

**Comment by vuolter** [comment]
@ananias47 See https://github.com/pyload/pyload/issues/1000

**Comment by kasperj** [comment]
Any progress on this?

**Comment by vuolter** [comment]
Nope for now, sorry.

**Comment by kasperj** [comment]
Is there any way to use an old and working version?

**Comment by Gutz-Pilz** [comment]
PLEASE fix it...its really annoying!
Makes pyload kind of ueseless

**Comment by VinceGitHub** [comment]
Maybe it's helpful for someone. I edited the “UnRAR.py” file on my local machine. I just change the following two function. I don’t know why but it works for me in 95% of the cases. BUT IT’S BUGGY!

```
def check(self, out="", err=""):
      if not out and not err:
            return

      if err.strip():
          if self.re_wrongpwd.search(err):
              raise PasswordError

          elif self.re_wrongcrc.search(err):
              raise CRCError

          else:  #: raise error if anything is on stderr
              raise ArchiveError(err.strip())

      if not out:
           return

      # output only used to check if passworded files are present
      for attr in self.re_filelist.findall(out):
          if attr[0].startswith("*"):
              raise PasswordError
```

```
def extract(self, progress=lambda x: None):
        # self.verify()

        command = "x" if self.fullpath else "e"

        p = self.call_cmd(command, self.file, self.out, password=self.password)

        renice(p.pid, self.renice)

        progress(0)

        progressstring = ""
        while True:
            c = p.stdout.read(1)
            # quit loop on eof
            if not c:
                break
            # reading a percentage sign -> set progress and restart
            if c == '%':
                progress(int(progressstring))
                progressstring = ""
            # not reading a digit -> therefore restart
            elif c not in digits:
                progressstring = ""
            # add digit to progressstring
            else:
                progressstring = progressstring + c
        progress(100)
        self.files = self.list()

        # retrieve stderr
        self.check(err=p.stderr.read())

        if p.returncode:
            raise ArchiveError("Process terminated")

```

**Comment by vuolter** [comment]
Useless not, but I know... it's a critical issue. I'm working on, please wait just a bit more.

**Comment by kasperj** [comment]
Any progress? :P
Script doesn't extract, but calls unbar_finished scripts afterwards, which deletes my downloads ...

**Comment by tseroo** [comment]
Any news on that? Would like to enable it again, cause currently it cannot be used at all :-(

**Comment by immenz** [comment]
I think the problem is in the unrar.py. If a wrong password is tried for extracting first, the check after the extraction raises an archive error, not an wrong password error. This is because the check is made for the Error Code beginning with "CRC...", not with the no Password regex


    def extract(self, progress, password=None):
    ...
        # retrieve stderr
        err = p.stderr.read()

        if "CRC failed" in err and not password and not self.passwordProtected:
            raise CRCError
        elif "CRC failed" in err:
            raise WrongPassword
        if err.strip():  #: raise error if anything is on stderr
            raise ArchiveError(err.strip())
        if p.returncode:
            raise ArchiveError("Process terminated")


should be something like this

    def extract(self, progress, password=None):
    ...
        # retrieve stderr
        err = p.stderr.read()

        if  [self.re_wrongcrcpattern.search(err)] and not password and not self.passwordProtected:
            raise CRCError
        elif  self.re_wrongpwd.search(err):
            raise WrongPassword
        if err.strip():  #: raise error if anything is on stderr
            raise ArchiveError(err.strip())
        if p.returncode:
            raise ArchiveError("Process terminated")
    ....

**Comment by vuolter** [comment]
@immenz https://github.com/pyload/pyload/commit/99ed44b0d919a33e3a559472893163b347cd1c37 Note that this is the reverted version, I'm focusing on the broken new.

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/8848a359a43316fb346b728d1d79d7b72d27e5a0

**Comment by tseroo** [comment]
I've tried several downloads and none of them worked as expected. The file is actually downloaded, but the extraction fails and finally the package is shown with 0 Bytes downloaded and status failed. Extracting it manually in Windows works without any issues:
2181	30.01.2015 21:30:27	DEBUG	Content-Disposition: cgi_zug_01x18.rar
2182	30.01.2015 21:38:38	INFO	Download finished: cgi_zug_01x18.rar
2183	30.01.2015 21:38:38	INFO	Package finished: http://download.serienjunkies.org/f-6aa2e638f918172a/so_cgi_zug_01x18-rar.html
2184	30.01.2015 21:38:38	INFO	ExtractArchive: Package http://download.serienjunkies.org/f-6aa2e638f918172a/so_cgi_zug_01x18-rar.html queued for later extracting
2185	30.01.2015 21:38:38	WARNING	Download failed: cgi_zug_01x18.rar | global name 'storage' is not defined

**Comment by mcmaxl** [comment]
it's still not working for me...extractarchive.py is the newest version. Does it have something to do with my unrar perhaps?

**Comment by mcmaxl** [comment]
it did - working after unrar update. thx!
