### ISSUE TITLE
ActiveDownloads in WebUI is always empty

### ISSUE THREAD

**Issue by DKeppi** [pyload/pyload#1012]
Today i realized that the ActiveDownloads in WebUI is always empty.
Also in my pyLoad App for iOS, so it should depend on the server himself.

Normally when a download is running it looks like here: http://www.megaleecher.net/sites/default/files/images/pyload-raspberry-pi-2.png

Since a few days (maybe due to a plugin update) there are no coloured bars or anything else to the actual download which is runnning (eg. downloaded, information, size, Progress, ...).

**Comment by vuolter** [comment]
Please post the full debug log. No changes was applied to webui in stable branch.

**Comment by DKeppi** [comment]
I don't think the debug will help :(
(I removed some lines with account or device id's)

424	05.01.2015 17:13:33	DEBUG	UploadedTo: Account Info: {'premium': True, 'validuntil': 1422695613.717272, 'trafficleft': 560988160.0}
425	05.01.2015 17:13:33	INFO	Activating Plugins...
426	05.01.2015 17:13:33	INFO	pyLoad is up and running

429	05.01.2015 17:13:40	DEBUG	RestartFailed: Restart failed downloads
430	05.01.2015 17:20:41	DEBUG	Redirected import module.plugins.hoster.BasePlugin -> userplugins.hoster.BasePlugin
431	05.01.2015 17:20:41	INFO	Added package pyload containing 1 links
432	05.01.2015 17:20:41	DEBUG	Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
433	05.01.2015 17:20:41	DEBUG	Run Info Fetching for BasePlugin
434	05.01.2015 17:20:41	DEBUG	Finished Info Fetching for BasePlugin
435	05.01.2015 17:20:41	INFO	Download starts: https://github.com/pyload/pyload/archive/stable.zip
436	05.01.2015 17:20:42	DEBUG	BasePlugin: Redirect #1 to: https://codeload.github.com/pyload/pyload/zip/stable
437	05.01.2015 17:20:43	DEBUG	Content-Disposition: pyload-stable.zip
438	05.01.2015 17:20:47	INFO	stable.zip saved as pyload-stable.zip
439	05.01.2015 17:20:47	INFO	Download finished: pyload-stable.zip
440	05.01.2015 17:20:47	INFO	Package finished: pyload

442	05.01.2015 17:20:47	DEBUG	PyControlPush: Response:
443	05.01.2015 17:20:47	INFO	ExtractArchive: Package pyload queued for later extracting
444	05.01.2015 17:20:48	DEBUG	ExtractArchive: Extensions allowed: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
445	05.01.2015 17:20:48	DEBUG	All downloads processed
446	05.01.2015 17:20:48	DEBUG	All downloads finished
447	05.01.2015 17:20:48	INFO	ExtractArchive: Check package: pyload
448	05.01.2015 17:20:48	DEBUG	ExtractArchive: Targets for UnRar: [(u'/volume1/downloads/pyload/pyload/pyload-stable.zip', 1)]
449	05.01.2015 17:20:48	INFO	ExtractArchive: pyload-stable.zip | Extract to: /volume1/downloads/pyload/pyload/
450	05.01.2015 17:20:48	INFO	ExtractArchive: pyload-stable.zip | Verifying...
451	05.01.2015 17:20:48	DEBUG	ExtractArchive: unrar l -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v /volume1/downloads/pyload/pyload/pyload-stable.zip
452	05.01.2015 17:20:48	DEBUG	ExtractArchive: unrar vb -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v /volume1/downloads/pyload/pyload/pyload-stable.zip
453	05.01.2015 17:20:48	ERROR	ExtractArchive: pyload-stable.zip | Archive Error | Empty archive
454	05.01.2015 17:20:48	ERROR	ExtractArchive: pyload-stable.zip | Extract failed
455	05.01.2015 17:20:48	WARNING	ExtractArchive: pyload-stable.zip | No files extracted
456	05.01.2015 17:20:48	DEBUG	ExtractArchive: Targets for UnZip: [(u'/volume1/downloads/pyload/pyload/pyload-stable.zip', 1)]
457	05.01.2015 17:20:48	DEBUG	ExtractArchive: pyload-stable.zip | skipped

**Comment by vuolter** [comment]
Allright, first try changing the webui server (webui -> config -> webinterface -> webserver).
If doesn't work, then try turning off the UpdateManager (webui -> config -> plugins -> UpdateManager, set "activated" to OFF), so delete the folder "userplugins" plus the file accounts.conf under your pyload config directory, finally restart pyload. If webui go right, so it's a plugin fault, otherwise you should try reinstalling pyload at all. :S

**Comment by DKeppi** [comment]
Thanks for your answer.
Try all the things but nothing helped :(

Is it also possible that config files in the config folder are corrupt or anything else!

**Comment by DKeppi** [comment]
I reinstalled pyload completely and it worked again!
Strange but solved :)
