### ISSUE TITLE
Multihoster smoozed.com

### ISSUE THREAD

**Issue by smoozed** [pyload/pyload#1014]
We are a quiet new service and are giving away free 14 days accounts in the time of our beta phase.
Please send me a private message containing your email address or send an email to github@smoozed.com. Your account will be created in a short time.

We have created the pull request #1013 containing all scripts needed to use our service with pyload.
We would appricate it when you tell us your expirience with this hoster to make it better.

**Comment by vuolter** [comment]
Okay, I'll take a look at that soon. ;)

**Comment by smoozed** [comment]
Our beta phase is stopped now, and so the 14 day action just ended. Please don't ask anymore for free premium accounts.

Thanks

**Comment by vuolter** [comment]
@smoozed Anymore?
