### ISSUE TITLE
[Account] Issue with Keep2Share premium - LifeTime

### ISSUE THREAD

**Issue by djraw** [pyload/pyload#1019]
Hi there,
first I'm glad that the account plugin has been added. Unfortunately I still can't use it.
The first issue is that the login now uses an additional captcha. This is known already if I correctly understand the comment for v0.3 in the repository.

The second issue is that I got a "Life Time" subscription. If I correctly understand the code it currently only works with dates. Below is an excerpt from the profile html of my account for parsing.

I hope this can be added. Thanks in advance!

```html
<div class="bootstrap-widget"><div class="bootstrap-widget-header"><i class="icon-home"></i><h3>Account info</h3></div><div class="bootstrap-widget-content" id="yw0">Account type: <a href="http://keep2share.cc/premium.html" style="font-weight:bold; color:green;">
Premium</a><br>
Premium expires: <b>LifeTime</b>
<br>
<div id="rebill">
Next rebill date: <strong><a href="http://keep2share.cc/premium.html">no active subscription</a></strong>
</div>
File stored total: <b>0 B</b><br>
Used traffic (today):
<b><a href="http://keep2share.cc/user/statistic.html">0 B</a></b><br>
Available traffic (today):
<b><a href="http://keep2share.cc/user/statistic.html">20.0 GB</a></b><br>
</div></div>
```

**Comment by vuolter** [comment]
No way to fulfill the captcha request on login for now.
