### ISSUE TITLE
file4safe: pattern-issue?

### ISSUE THREAD

**Issue by cryzto** [pyload/pyload#1022]
Hi there
Plugin-issue with some pattern error:

08.01.2015 10:13:22	DEBUG	All downloads processed
132	08.01.2015 10:13:22	DEBUG	ExtractArchive: Extensions allowed: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
131	08.01.2015 10:13:21	INFO	UnSkipOnFail: No duplicates found
130	08.01.2015 10:13:21	INFO	UnSkipOnFail: Looking for skipped duplicates of: http://www.file4safe.com/92ew5lmxt569 (pid:29)
129	08.01.2015 10:13:21	INFO	Debug Report written to debug_XFileSharingPro_08-01-2015_10-13-21.txt
128	08.01.2015 10:13:21	DEBUG	Error creating zip file: 'ascii' codec can't decode byte 0xaa in position 10: ordinal not in range(128)
127	08.01.2015 10:13:21	WARNING	Download failed: http://www.file4safe.com/92ew5lmxt569 | 'pattern'
126	08.01.2015 10:13:21	DEBUG	XFileSharingPro: File info (BEFORE): {}
125	08.01.2015 10:13:21	INFO	Download starts: http://www.file4safe.com/92ew5lmxt569
124	08.01.2015 10:13:21	DEBUG	Redirected import module.plugins.accounts.XFileSharingPro -> userplugins.accounts.XFileSharingPro
123	08.01.2015 10:13:21	DEBUG	Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
122	08.01.2015 10:13:21	DEBUG	Redirected import module.plugins.internal.XFSHoster -> userplugins.internal.XFSHoster
121	08.01.2015 10:13:21	DEBUG	Redirected import module.plugins.hoster.XFileSharingPro -> userplugins.hoster.XFileSharingPro

**Comment by cryzto** [comment]
Still problems: now I can't even add an file4safe.com-account => Error...
And if I add a XFileSharingPro-Account it won't download the link.
Here the Debug:
1031	12.01.2015 14:53:47	WARNING	Download failed: files_p-thbptfa192gb.rar | Parse error: TEXTAREA F1 not found | Plugin may be out of date
1030	12.01.2015 14:53:46	DEBUG	XFileSharingPro: Getting download link: #2
1029	12.01.2015 14:53:46	DEBUG	XFileSharingPro: {u'method_premium': u'Premium Download', u'usr_login': '', u'referer': '', u'fname': u'files_p-thbptfa192gb.rar', u'method_free': u'Free Download', u'id': u'5wihlyzmqww1', u'op': u'download1'}
1028	12.01.2015 14:53:46	DEBUG	XFileSharingPro: Getting download link: #1
1027	12.01.2015 14:53:46	DEBUG	XFileSharingPro: Handled as premium download
1026	12.01.2015 14:53:46	DEBUG	XFileSharingPro: File status: online | File info: {'status': 2, 'name': u'files_p-thbptfa192gb.rar', 'url': u'http://www.file4safe.com/5wihlyzmqww1', 'pattern': {'S': u'1.9', 'U': u'GB', 'N': u'files_p-thbptfa192gb.rar'}, 'size': 2040109465.5999999}
1025	12.01.2015 14:53:46	DEBUG	XFileSharingPro: File name: files_p-thbptfa192gb.rar | File size: 2040109465
1024	12.01.2015 14:53:46	DEBUG	XFileSharingPro: File info (AFTER): {'status': 2, 'name': u'files_p-thbptfa192gb.rar', 'url': u'http://www.file4safe.com/5wihlyzmqww1', 'pattern': {'S': u'1.9', 'U': u'GB', 'N': u'files_p-thbptfa192gb.rar'}, 'size': 2040109465.5999999}
1023	12.01.2015 14:53:46	DEBUG	XFileSharingPro: File info (BEFORE): {'status': 2, 'name': u'files_p-thbptfa192gb.rar', 'url': u'http://www.file4safe.com/5wihlyzmqww1', 'pattern': {'S': u'1.9', 'U': u'GB', 'N': u'files_p-thbptfa192gb.rar'}, 'size': 2040109465.5999999}
1022	12.01.2015 14:53:46	DEBUG	XFileSharingPro: File name: files_p-thbptfa192gb.rar | File size: 2040109465
1021	12.01.2015 14:53:46	DEBUG	XFileSharingPro: File info (AFTER): {'status': 2, 'name': u'files_p-thbptfa192gb.rar', 'url': u'http://www.file4safe.com/5wihlyzmqww1', 'pattern': {'S': u'1.9', 'U': u'GB', 'N': u'files_p-thbptfa192gb.rar'}, 'size': 2040109465.5999999}
1020	12.01.2015 14:53:46	DEBUG	XFileSharingPro: File info (BEFORE): {'status': 2, 'url': u'http://www.file4safe.com/5wihlyzmqww1', 'size': 2040109465.5999999, 'name': u'files_p-thbptfa192gb.rar', 'pattern': {'S': u'1.9', 'U': u'GB', 'N': u'files_p-thbptfa192gb.rar'}}
1019	12.01.2015 14:53:46	DEBUG	XFileSharingPro: Direct download link not found
1018	12.01.2015 14:53:46	DEBUG	XFileSharingPro: Looking for direct download link...
1017	12.01.2015 14:53:46	DEBUG	XFileSharingPro: File status: online | File info: {'status': 2, 'url': u'http://www.file4safe.com/5wihlyzmqww1', 'size': 2040109465.5999999, 'name': u'files_p-thbptfa192gb.rar', 'pattern': {'S': u'1.9', 'U': u'GB', 'N': u'files_p-thbptfa192gb.rar'}}
1016	12.01.2015 14:53:46	DEBUG	XFileSharingPro: File name: files_p-thbptfa192gb.rar | File size: 2040109465
1015	12.01.2015 14:53:46	DEBUG	XFileSharingPro: File info (AFTER): {'status': 2, 'url': u'http://www.file4safe.com/5wihlyzmqww1', 'size': 2040109465.5999999, 'name': u'files_p-thbptfa192gb.rar', 'pattern': {'S': u'1.9', 'U': u'GB', 'N': u'files_p-thbptfa192gb.rar'}}
1014	12.01.2015 14:53:46	DEBUG	XFileSharingPro: File info (BEFORE): {}
1013	12.01.2015 14:53:46	INFO	Download starts: files_p-thbptfa192gb.rar
1012	12.01.2015 14:53:46	DEBUG	Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
1011	12.01.2015 14:53:45	DEBUG	Redirected import module.plugins.internal.XFSHoster -> userplugins.internal.XFSHoster
1010	12.01.2015 14:53:45	DEBUG	Redirected import module.plugins.hoster.XFileSharingPro -> userplugins.hoster.XFileSharingPro

**Comment by cryzto** [comment]
error-(webgui)message:
fehlgeschlagenParse error: TEXTAREA F1 not found | Plugin may be out of date 1.20 GiBXFileSharingPro

As I told...I can't even add a real file4safe-account. It always ends with an error. That's why I try with XFileSharingPro-Plugin.
Help.

**Comment by cryzto** [comment]
@vuolter : I found it!
Please rename the file: File4safeCom.py => File4SafeCom.py (capital s)

**Comment by vuolter** [comment]
Done. Thx.
