### ISSUE TITLE
[ExtractArchive] Package not set to finished & Delete Archive option not saved

### ISSUE THREAD

**Issue by zomed** [pyload/pyload#1023]
Hi,

First the german Forum Topic:
http://forum.pyload.org/viewtopic.php?f=10&t=3885

Just to summarize in English again:
1.) Packages are not set to "finished" after unrar is completed. Package stays as "extracting". Still the package is being deleted if the option "Delete archive when successfully extracted" is set.

2.) "Delete archive when successfully extracted" can be checked and works. But after some time, the saved option is unchecked again. This must not be a restart of the Service or even machine.

Thanks for checking.

Cheers,
Seb

**Comment by slith76** [comment]
same here ;(

**Comment by Bambie42** [comment]
same here

but when setting a package password, the extracted files won't be deleted

**Comment by cryzto** [comment]
same here: here the screenshot
![package-name error 4](https://cloud.githubusercontent.com/assets/6126067/5855606/77bac2ac-a23a-11e4-9099-15ed4beea830.png)

**Comment by Bambie42** [comment]
Any progress here? this is really annoying.

btw: I think, the plugin is unable to handle the folder in the rar-files:
    
    DEBUG	ExtractArchive: New file images/ does not exists
    DEBUG	ExtractArchive: New file images/00000.jpeg does not exists

**Comment by McGeifer** [comment]
Same here...

DEBUG     ExtractArchive: unrar vb -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v /MYFILE.part1.rar

DEBUG     ExtractArchive: Would delete: /MYFILE.part3.rar, /MYFILE.part5.rar, /MYFILE.part4.rar, /MYFILE.part1.rar, /MYFILE.part2.rar

INFO      ExtractArchive: MYFILE.rar | Extracting finished
DEBUG     ExtractArchive: Extracted files: ['/MYFILE', '/MYFILE/MYFILE.mkv']

Files are not set to "finish" after extracting. Also queued files for extracting later are not getting extracted. Verry annoying error....

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/8848a359a43316fb346b728d1d79d7b72d27e5a0
Please reopen if not fixed.

**Comment by Gutz-Pilz** [comment]
seems to be fixed!
Gr8 work. thanks!

**Comment by godfuture** [comment]
Nice, works for me too.
Setting "Delete archive when successfully extracted" is preserved after restart and status is correctly set after extracting.
Happy!

**Comment by cryzto** [comment]
Thnx.
