### ISSUE TITLE
All downloads fail

### ISSUE THREAD

**Issue by tchoblond59** [pyload/pyload#1024]
Download failed with error message: WARNING	Download failed: wdmsd3fu8v28 | 'https'
I'am using real debrid with 1fichier dot com, uptobox or uploaded
I also have this: ERROR     Error executing hooks: MultiHook with a traceback
Also before this issue the filename was not correct with uptobox and uploaded

EDIT: When i launch pyload i got this error:
CRITICAL	'NoneType' object has no attribute 'BasePlugin'

**Comment by vuolter** [comment]
Retry now.

**Comment by tchoblond59** [comment]
You Rocks !!
It's working but filenames are still bad with uptobox and uploaded.

Thanks a lot for your work !

**Comment by vuolter** [comment]
I'm working on the filename issue...
