### ISSUE TITLE
addPackage filename

### ISSUE THREAD

**Issue by HPP8140** [pyload/pyload#1025]
Hi,

pyload: v0.4.9

I'm using the following code. Is there an option to specify the file name for the url input with this method?

self.core.api.addPackage("newpacktest", [url], 1)

I would like to specify the filename for the url input for download

Thanks.

**Comment by vuolter** [comment]
Nope, sorry. Current API is very outdated. :(
You have to add the package and with the returned pid get its packageData (see: getPackageData method), then expand packageData.links array, pick the pyfile with that url and, then, you can change its name attribute. I know... it's simply crazy.

**Comment by HPP8140** [comment]
Thanks for the info. 

I wanted to download an audio and video file in a plugin.

I ended up just calling self.download(url) twice instead. The progress bar is only shown for 1 file, but download both anyways. Wish I could figure out how to wait until the 1st is downloaded then make the 2nd call to download the other file.

self.download(video_url)
self.download(audio_url)
