### ISSUE TITLE
[question] 0.5 (api) documentation and 0.5 repo

### ISSUE THREAD

**Issue by Rusk85** [pyload/pyload#1030]
Hi!

I am looking for the 0.5 documentation. In particular I am interested in the web api part.

Also is there an official 0.5 repo where the source code is hosted ?

**Comment by RaNaN** [comment]
The source code is in the 1.0,0 branch. It includes slightly updated docs, but not hosted as html.

**Comment by Ghoststage** [comment]
Hi! gibt es irgend wo ein Tutorial wie ich pyload 0.5./1.0.0 auf mein Synology NAS Installiere? würde mich freuen.

Mit freundlichen gruß

Hi! is there somewhere a tutorial as I pyLoad 0.5. / 1.0.0 on my Synology NAS Install ? would be delighted.

With best greetings

**Comment by RaNaN** [comment]
Nicht wirklich, aber der letzte build lässt sich starten wie die aktuelle Version auch:
http://nightly.pyload.org/job/Nightly/433/artifact/dist/pyload-0.4.9.9-dev.tar.gz

**Comment by Ghoststage** [comment]
Ok THX!
