### ISSUE TITLE
Some issue in fileshark.pl

### ISSUE THREAD

**Issue by akfedux** [pyload/pyload#1040]
Hi,

after "New Year" Update hoster plugin fileshark don't work.

13.01.2015 14:46:39	INFO	pyLoad is up and running
13.01.2015 15:21:05	DEBUG	Redirected import module.plugins.hoster.BasePlugin -> userplugins.hoster.BasePlugin
13.01.2015 15:21:05	DEBUG	Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
13.01.2015 15:21:05	INFO	Download starts: christmas-newyear-part-3-rar
13.01.2015 15:21:06	DEBUG	Download Check triggered
13.01.2015 15:21:06	WARNING	Download failed: christmas-newyear-part-3-rar | Html file
13.01.2015 15:21:06	DEBUG	All downloads processed

Sample link:

http://fileshark.pl/pobierz/1240131/7015d/christmas-newyear-part-3-rarchristmas-newyear-part-3-rar
http://fileshark.pl/pobierz/1240131/7015d/

**Comment by akfedux** [comment]
Hi, there is new issue now: Captcha form not found

preload_line399.dump.html
http://www54.zippyshare.com/v/YJiNiFNX/file.html


14.01.2015 10:32:50	INFO	Download starts: Christmas_NewYear_part_3.rar
14.01.2015 10:32:50	DEBUG	FileSharkPl: File info (BEFORE): {}
14.01.2015 10:32:50	DEBUG	FileSharkPl: File info (AFTER): {'status': 2, 'url': u'http://fileshark.pl/pobierz/1240131/7015d/christmas-newyear-part-3-rarchristmas-newyear-part-3-rar', 'size': 118698803.2, 'name': u'Christmas_NewYear_part_3.rar', 'pattern': {'S': u'113.2', 'U': u'MB', 'N': u'Christmas_NewYear_part_3.rar'}}
14.01.2015 10:32:50	DEBUG	FileSharkPl: File name: Christmas_NewYear_part_3.rar | File size: 118698803
14.01.2015 10:32:50	DEBUG	FileSharkPl: File info (BEFORE): {'status': 2, 'url': u'http://fileshark.pl/pobierz/1240131/7015d/christmas-newyear-part-3-rarchristmas-newyear-part-3-rar', 'size': 118698803.2, 'name': u'Christmas_NewYear_part_3.rar', 'pattern': {'S': u'113.2', 'U': u'MB', 'N': u'Christmas_NewYear_part_3.rar'}}
14.01.2015 10:32:50	DEBUG	FileSharkPl: File info (AFTER): {'status': 2, 'name': u'Christmas_NewYear_part_3.rar', 'url': u'http://fileshark.pl/pobierz/1240131/7015d/christmas-newyear-part-3-rarchristmas-newyear-part-3-rar', 'pattern': {'S': u'113.2', 'U': u'MB', 'N': u'Christmas_NewYear_part_3.rar'}, 'size': 118698803.2}
14.01.2015 10:32:50	DEBUG	FileSharkPl: File name: Christmas_NewYear_part_3.rar | File size: 118698803
14.01.2015 10:32:50	DEBUG	FileSharkPl: File status: online | File info: {'status': 2, 'name': u'Christmas_NewYear_part_3.rar', 'url': u'http://fileshark.pl/pobierz/1240131/7015d/christmas-newyear-part-3-rarchristmas-newyear-part-3-rar', 'pattern': {'S': u'113.2', 'U': u'MB', 'N': u'Christmas_NewYear_part_3.rar'}, 'size': 118698803.2}
14.01.2015 10:32:50	DEBUG	FileSharkPl: File info (BEFORE): {'status': 2, 'name': u'Christmas_NewYear_part_3.rar', 'url': u'http://fileshark.pl/pobierz/1240131/7015d/christmas-newyear-part-3-rarchristmas-newyear-part-3-rar', 'pattern': {'S': u'113.2', 'U': u'MB', 'N': u'Christmas_NewYear_part_3.rar'}, 'size': 118698803.2}
14.01.2015 10:32:50	DEBUG	FileSharkPl: File info (AFTER): {'status': 2, 'name': u'Christmas_NewYear_part_3.rar', 'url': u'http://fileshark.pl/pobierz/1240131/7015d/christmas-newyear-part-3-rarchristmas-newyear-part-3-rar', 'pattern': {'S': u'113.2', 'U': u'MB', 'N': u'Christmas_NewYear_part_3.rar'}, 'size': 118698803.2}
14.01.2015 10:32:50	DEBUG	FileSharkPl: File name: Christmas_NewYear_part_3.rar | File size: 118698803
14.01.2015 10:32:50	DEBUG	FileSharkPl: File info (BEFORE): {'status': 2, 'name': u'Christmas_NewYear_part_3.rar', 'url': u'http://fileshark.pl/pobierz/1240131/7015d/christmas-newyear-part-3-rarchristmas-newyear-part-3-rar', 'pattern': {'S': u'113.2', 'U': u'MB', 'N': u'Christmas_NewYear_part_3.rar'}, 'size': 118698803.2}
14.01.2015 10:32:50	DEBUG	FileSharkPl: File info (AFTER): {'status': 2, 'name': u'Christmas_NewYear_part_3.rar', 'url': u'http://fileshark.pl/pobierz/1240131/7015d/christmas-newyear-part-3-rarchristmas-newyear-part-3-rar', 'pattern': {'S': u'113.2', 'U': u'MB', 'N': u'Christmas_NewYear_part_3.rar'}, 'size': 118698803.2}
14.01.2015 10:32:50	DEBUG	FileSharkPl: File name: Christmas_NewYear_part_3.rar | File size: 118698803
14.01.2015 10:32:50	DEBUG	FileSharkPl: File status: online | File info: {'status': 2, 'name': u'Christmas_NewYear_part_3.rar', 'url': u'http://fileshark.pl/pobierz/1240131/7015d/christmas-newyear-part-3-rarchristmas-newyear-part-3-rar', 'pattern': {'S': u'113.2', 'U': u'MB', 'N': u'Christmas_NewYear_part_3.rar'}, 'size': 118698803.2}
14.01.2015 10:32:50	DEBUG	FileSharkPl: Handled as free download
14.01.2015 10:32:50	WARNING	Download failed: Christmas_NewYear_part_3.rar | Captcha form not found
14.01.2015 10:32:50	DEBUG	All downloads processed 

<div class="col-lg-12 alert alert-warning">
            <p class="text-center lead">Aby rozpocząć pobieranie przepisz poniższy kod</p>
            <br>
            <div class="col-lg-4 col-sm-offset-4">
                <form method="post" action="">
                    

                        <div class="form-group">
                                <div class="row"><div style="margin-left: 90px;"><img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD//gA7Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2ODApLCBxdWFsaXR5ID0gMzAK/9sAQwAbEhQXFBEbFxYXHhwbIChCKyglJShROj0wQmBVZWRfVV1baniZgWpxkHNbXYW1hpCeo6utq2eAvMm6pseZqKuk/9sAQwEcHh4oIyhOKytOpG5dbqSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSk/8AAEQgAMgCCAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A5miiigAoqe1tWufM2sAUXdj1qVbKNV/0i5SJz/BjJ/GlctQk1cp0VJPEIn2iRZARkMtWLe1i+z/aLmRlTOFVRyaLiUW3Yp0VLcNCzjyEZVA/iOSTS28cUhYSzeVjp8pOaYra2IaKuf2e7cwSxTf7rYP61XmglgIEqFSemaVxuEluiOipIYJZ22xIWPtSzW8tuQJUKk9KdxWdrgIh9laZiQd4Vff1/pUVaMlpO9lbLFHu4Ltjpz0/HFU5baeEZkiZR6kcUkypRa6EVKVKhSRwwyP5f0pY0LuFGeT2okbfITjHoPQdhTJ6DaKKKBBRRRQBo6GcXjD1Q/zFUJGLOzMcknmrWmMIbpZJDtQA5J+lQSIplfa64ycUKLuaN+4kFuYQ589WZccbTjmtRntl01HEBeNW4VmxzWTs/wBtfzq+qr/YzBn4D54pSiyqctGvIp3M4ncFYkjAGAFFRAE9BmnblX7oyfU0bncgAnJ6AVVkjJttk+n25muPmyET5mPSi7ma9uiyqcfdUVYupms7ZLVG/eEZkP8ASqAlcOG3HIOaSs9TSXurl+81p7do1WEXSW8aj+9gse5NMeOH7GYWulmbeNpB5GeKhnWzupDMbkxMwyylCeabAlsLqMxM7rHl3ZhgYA7CoRo9/wDgiXk3+ksiSOix/IB6Y4qWynJhuPMZnjCZO85Ge1VoLaW5LSOdqZy0jdP/AK9OnmV1W1tVbywfTlz61V9LEJtPmZCsrhWIOOMcVFU9xDLAkayKVBG4Z9TjP9Kgp3uZNW0CiiigQUoJByOtX/7L24Mt1Cinoc9f5UhtrGInzbsyegjH/wCulzGns5dSiSScnrSVfGoR25xZwKq9zIMsT+dKdXnIw0cTD0Kn/Gi7Dlj3M+p0nf7M1sqgh2z05z7VY/tWUqFeGFwOgK006nIFZY4oYsjGUXBo1BKK2f4CJplyV3PsiXrl2xU0NvbWrrK96hI6BBuwf1rPeR5G3SOzH1Y5ptFmClFbI0JLSKdjIl9GzMcnf8tN+x20ZxPeKG7hFLfrVGiiwc63sXvPsoOYIWkcHhpDx+Qp41iYqweONsjAGOKzqKLIPaSW2ho/2ruASS1iaMdFx0pBqIVv3NrFEcfeA5/Os+lHAP5UWQKpK46WaSZt0jsx9z0plFFMzbuFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAH//Z" title="captcha" height="50" width="130"><label class="sr-only" for="form_captcha">Kod:</label><input id="form_captcha" name="form[captcha]" required="required" class="form-control" placeholder="Kod:" style="width:130px" type="text"></div></div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12 col-sm-offset-1">
                                    <div class="col-lg-4">
                                        <a class="btn btn-primary" href="#" onclick="location.reload();return false">Odśwież</a>
                                    </div>
                                    <div class="col-lg-4">
                                        <button type="submit" id="form_start" name="form[start]" class="btn btn-primary form-control">Pobierz</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    <input id="form__token" name="form[_token]" value="df2d28b87074e5ec98d1cb678c1a45efeb2a5d82" type="hidden">
                </form>
            </div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>

**Comment by valdi74** [comment]
Hi,

In file .pyload/userplugins/hoster/FileSharkPl.py between lines:

        link = urljoin("http://fileshark.pl", m.group(1))

and

        m = re.search(self.WAIT_PATTERN, self.html)

you have to add one line:

        self.html = self.load(link)

result:

        link = urljoin("http://fileshark.pl", m.group(1))
        self.html = self.load(link)
        m = re.search(self.WAIT_PATTERN, self.html)

This solves the 'Captcha form not found' problem for me.

**Comment by valdi74** [comment]
Please ignore commit 51fdabb0fd2cd120b3e827b59f759546babb6b64. It is without __version__ change. Sorry - this is my first commit in github.

**Comment by vuolter** [comment]
Okay, but the PR was opened in the wrong place. :P

**Comment by valdi74** [comment]
@vuolter 
You added line:

    self.html = self.load(link, decode=True)

instead of

    self.html = self.load(link)

I don't know why, but it's not working in my case. Captcha is OK, but after while download stops (and destination file exists with few KB). Logs:

    600	10.03.2015 07:56:08	INFO	Added package SA.fileshark containing 5 links
    601	10.03.2015 07:56:09	INFO	Download starts: http://fileshark.pl/pobierz/1845090/f9180/SA-part5-rar
    602	10.03.2015 07:57:13	INFO	Download restarted: SA.part5.rar | Captcha form not found
    603	10.03.2015 07:57:13	INFO	Download starts: SA.part5.rar
    604	10.03.2015 07:57:29	WARNING	Download failed: SA.part5.rar | 'FileSharkPl' object has no attribute 'SECONDS_PATTERN'
    605	10.03.2015 07:57:29	ERROR	Error executing hooks: u'FileSharkPl'

I had to delete "decode=True" parameter and it's working again.

**Comment by vuolter** [comment]
Thanks. :)
