### ISSUE TITLE
Question. No constant downloadSpeed [Premiumize.me]

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1046]
Hi there,
at the Start of a package i have a downloadspeed 12MiB/s.
after two files it drops to 400Kb/s - 2MB/s.

I use Premiumize.me using Debian wheezy
anyone else has this issue ?

**Comment by Kuenstler** [comment]
Yes, same issue 
Think its a general problem with premiumize (in my case uploaded.to)

**Comment by smystero** [comment]
Me to on EasyBytez

**Comment by vuolter** [comment]
Generate an http url (NOT https) on premiumize website and put it in pyload. The issue happens again?

**Comment by michiil** [comment]
I use premiumize with ssl downloads turned off since the cpu usage is way less this way but i still have inconstant speed on some hosters ie uploadet.to other hosters like filr.net work fine so i think its a preniumize issue..

**Comment by vuolter** [comment]
Please open a ticket on premiumize.
