### ISSUE TITLE
Premium account UptoBox

### ISSUE THREAD

**Issue by cmiscloni** [pyload/pyload#1047]
Uptobox premium account not detected

129	15.01.2015 20:05:45	INFO	pyLoad is up and running
128	15.01.2015 20:05:45	DEBUG	XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?P[\w.^_]+(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:user|folder)s?/\w+
127	15.01.2015 20:05:45	INFO	XFileSharingPro: Handling any crypter I can!
126	15.01.2015 20:05:45	DEBUG	XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?P[\w.^_]+(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
125	15.01.2015 20:05:45	INFO	XFileSharingPro: Handling any hoster I can!
124	15.01.2015 20:05:45	INFO	Activating Plugins...
123	15.01.2015 20:05:45	DEBUG	UptoboxCom: Account Info: {'premium': False, 'leechtraffic': None, 'validuntil': None, 'trafficleft': None}
122	15.01.2015 20:05:45	DEBUG	UptoboxCom: LEECH_TRAFFIC_PATTERN not found
121	15.01.2015 20:05:45	DEBUG	UptoboxCom: TRAFFIC_LEFT_PATTERN not found
120	15.01.2015 20:05:45	DEBUG	UptoboxCom: VALID_UNTIL_PATTERN not found
119	15.01.2015 20:05:44	DEBUG	UptoboxCom: Get Account Info for xxxxxxx
118	15.01.2015 20:05:43	INFO	Activating Accounts...
117	15.01.2015 20:05:43	INFO	Free space: 736.18 GiB
116	15.01.2015 20:05:43	INFO	Starting threaded webserver:

**Comment by vuolter** [comment]
Checking...

**Comment by cmiscloni** [comment]
Some news ?

**Comment by stickell** [comment]
If you send me the account details I can fix it.
stickell@pyload.org

**Comment by cmiscloni** [comment]
Login: cmiscloni
Password: nicolas68125

**Comment by stickell** [comment]
Received. I'm checking

**Comment by stickell** [comment]
Fixed. You can change your password

**Comment by cmiscloni** [comment]
Thx

**Comment by edika59** [comment]
hi Vuolter,
how can i have the bug fix for the uptobox premium account in pyload please?
thx

**Comment by zechrisd** [comment]
Hello I have same bug my premium account is not recognized in pyload

**Comment by GammaC0de** [comment]
@zechrisd Please open a new issue, thanks.
