### ISSUE TITLE
Zippyshare key now alphanumeric, breaks pattern regex

### ISSUE THREAD

**Issue by gaberad** [pyload/pyload#1049]
So the key in the zippyshre link is now characters and numbers e.g. http://www67.zippyshare.com/v/JyeOy2lr/file.html

This breaks the pattern regex, which is only looking for numbers, this part:

```
(?P<KEY>\d+)
```

Quickfix that I've done for my own purposes:

```
__pattern__ = r'(?P<HOST>http://www\d{0,2}\.zippyshare\.com)/v(?:/|iew\.jsp.*key=)(?P<KEY>.+)/file\.html'
```

**Comment by vuolter** [comment]
Thx.
