### ISSUE TITLE
Plugin issue : 9kw plugin not working anymore

### ISSUE THREAD

**Issue by prysme01** [pyload/pyload#1058]
Hi, 

I'm using the git version 0.4.9 and the plugin 9kw is not working anymore
Failed activating Captcha9kw

When switching the plugin on and off I'm getting this : 
19.01.2015 10:15:28 WARNING   Error calling event handler pluginConfigChanged: <bound method HookManager.manageHooks of <module.HookManager.HookManager instance at 0x1351f80>>, ('Captcha9kw', 'activated', True), 'module' object has no attribute 'Captcha9kw'

Prysme.

**Comment by Ghoststage** [comment]
Captcha9kw hat ein eigenes scripot versuche das mal geht bei mir ohne fehler.

**Comment by Ghoststage** [comment]
Sorry my englisch is very bad im use this Script
https://www.9kw.eu/plugins.html#submitdata-tab

117    19.01.2015 17:31:38    DEBUG    Redirected import
module.plugins.hooks.Captcha9kw -> userplugins.hooks.Captcha9kw
120    19.01.2015 17:31:38    INFO    Aktivierte Plugins: Captcha9kw,


2015-01-19 10:15 GMT+01:00 prysme01 <notifications@github.com>:

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/c4f167e267ba949ee20ec8a6d3c611d6dd93b325
