### ISSUE TITLE
ZippyshareCom: Can't download, throwing Exception

### ISSUE THREAD

**Issue by Istoran** [pyload/pyload#1060]
Downloads from Zippyshare with packagesize=200mb always fail, saying "'exceptions.AttributeError' object has no attribute 'strip".

Packages under 200mb work fine.

Is there perhaps some connection with Zippyshare using the "I am no robot"-Captchas I've seen lately?

**Comment by seppi91** [comment]
I think the issue is not fully resolved. I'm getting the same Exception at 200MiB Files.

ZippyShare.py Version is 0.79

**Comment by seppi91** [comment]
e.g. try it with this link,... http://filecrypt.cc/Link/I3GfwTFDM-QoK-ODiRD68N7NaTbdgRLIpsIrSGHveqSf8SA-o3yulhc5GpJmNCvp28FPMaUPkr03KQ0dSf4lSQ.html

Log says: 'exceptions.AttributeError' object has no attribute 'strip'

**Comment by sebdelsol** [comment]
captcha not detected (again).

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/issues/1484
