### ISSUE TITLE
WebUI-Issue with download-names (FilerNet-Plugin)

### ISSUE THREAD

**Issue by cryzto** [pyload/pyload#1062]
Hi there
During the download (FilerNet-Plugin) the filename ist read, downloaded and extracted perfectly by pyload but not shown properly in the UI:
![name issues](https://cloud.githubusercontent.com/assets/6126067/5856160/bb453a38-a240-11e4-9453-b371d643f93f.png)
Here the LOG to this second issue:
430 22.01.2015 14:46:01 DEBUG   ExtractArchive: Extracted files: [u'Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.sub', u'Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.idx']
429 22.01.2015 14:46:01 INFO    ExtractArchive: mortal-nussknacker-subs.rar | Extracting finished
428 22.01.2015 14:46:01 DEBUG   ExtractArchive: Would delete: Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL/Subs/mortal-nussknacker-subs.rar
427 22.01.2015 14:46:01 DEBUG   ExtractArchive: unrar vb -o+ -x_.nfo -x_.DS_Store -xindex.dat -xthumb.db -y -pwww.sdd-fanatico.org -v Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL/Subs/mortal-nussknacker-subs.rar
426 22.01.2015 14:46:00 DEBUG   ExtractArchive: unrar x -o+ -x_.nfo -x_.DS_Store -xindex.dat -xthumb.db -y -pwww.sdd-fanatico.org Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL/Subs/mortal-nussknacker-subs.rar Downloads/Parsed links from tmp_nox.txt/
425 22.01.2015 14:46:00 DEBUG   ExtractArchive: unrar vb -o+ -x_.nfo -x_.DS_Store -xindex.dat -xthumb.db -y -pwww.sdd-fanatico.org -v Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL/Subs/mortal-nussknacker-subs.rar
424 22.01.2015 14:46:00 DEBUG   ExtractArchive: unrar l -o+ -x_.nfo -x_.DS_Store -xindex.dat -xthumb.db -y -pwww.sdd-fanatico.org -v Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL/Subs/mortal-nussknacker-subs.rar
423 22.01.2015 14:46:00 DEBUG   ExtractArchive: unrar l -o+ -x_.nfo -x_.DS_Store -xindex.dat -xthumb.db -y -pwww.sdd-fanatico.org -v Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL/Subs/mortal-nussknacker-subs.rar
422 22.01.2015 14:46:00 DEBUG   ExtractArchive: Try password: www.sdd-fanatico.org
421 22.01.2015 14:46:00 DEBUG   ExtractArchive: No package password provided
420 22.01.2015 14:46:00 INFO    ExtractArchive: mortal-nussknacker-subs.rar | Password protected
419 22.01.2015 14:46:00 INFO    ExtractArchive: mortal-nussknacker-subs.rar | Extract to: Downloads/Parsed links from tmp_nox.txt/
418 22.01.2015 14:46:00 DEBUG   ExtractArchive: Targets for UnRar: [(u'Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL/Subs/mortal-nussknacker-subs.rar', 67)]
417 22.01.2015 14:46:00 DEBUG   ExtractArchive: Extracted files: [u'Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL/Subs', u'Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL/Subs/mortal-nussknacker-subs.rar', u'Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL/mortal-nussknacker.mkv', u'Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL', u'Downloads/Parsed links from tmp_nox.txt/Operation.Nussknacker.German.2014.BDRip.x264-MORTAL/Subs/mortal-nussknacker-subs.sfv']
416 22.01.2015 14:46:00 INFO    ExtractArchive: mortal-nussknacker.part1.rar | Extracting finished
415 22.01.2015 14:46:00 DEBUG   ExtractArchive: Would delete: Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.part2.rar, Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.part4.rar, Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.part1.rar, Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.part3.rar, Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.part5.rar
414 22.01.2015 14:46:00 DEBUG   ExtractArchive: unrar vb -o+ -x_.nfo -x_.DS_Store -xindex.dat -xthumb.db -y -pwww.sdd-fanatico.org -v Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.part1.rar
413 22.01.2015 14:45:19 DEBUG   ExtractArchive: unrar x -o+ -x_.nfo -x_.DS_Store -xindex.dat -xthumb.db -y -pwww.sdd-fanatico.org Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.part1.rar Downloads/Parsed links from tmp_nox.txt/
412 22.01.2015 14:45:19 DEBUG   ExtractArchive: unrar vb -o+ -x_.nfo -x_.DS_Store -xindex.dat -xthumb.db -y -pwww.sdd-fanatico.org -v Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.part1.rar
411 22.01.2015 14:45:19 DEBUG   ExtractArchive: unrar l -o+ -x_.nfo -x_.DS_Store -xindex.dat -xthumb.db -y -pwww.sdd-fanatico.org -v Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.part1.rar
410 22.01.2015 14:45:18 DEBUG   ExtractArchive: unrar l -o+ -x_.nfo -x_.DS_Store -xindex.dat -xthumb.db -y -pwww.sdd-fanatico.org -v Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.part1.rar
409 22.01.2015 14:45:18 DEBUG   ExtractArchive: Try password: www.sdd-fanatico.org
408 22.01.2015 14:45:18 DEBUG   ExtractArchive: No package password provided
407 22.01.2015 14:45:18 INFO    ExtractArchive: mortal-nussknacker.part1.rar | Password protected
406 22.01.2015 14:45:18 DEBUG   All downloads processed
405 22.01.2015 14:45:18 DEBUG   ExtractArchive: Extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
404 22.01.2015 14:45:18 INFO    ExtractArchive: mortal-nussknacker.part1.rar | Extract to: Downloads/Parsed links from tmp_nox.txt/
403 22.01.2015 14:45:18 DEBUG   ExtractArchive: Targets for UnRar: [(u'Downloads/Parsed links from tmp_nox.txt/mortal-nussknacker.part1.rar', 67)]
402 22.01.2015 14:45:18 INFO    ExtractArchive: Check package: Parsed links from tmp_nox.txt
401 22.01.2015 14:45:18 DEBUG   ExtractArchive: Extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
400 22.01.2015 14:45:18 INFO    Package finished: Parsed links from tmp_nox.txt
399 22.01.2015 14:45:18 INFO    Download finished: mortal-nussknacker.part4.rar
398 22.01.2015 14:45:18 INFO    jeqjczcvcsustlz8 saved as mortal-nussknacker.part4.rar
397 22.01.2015 14:44:42 INFO    Download finished: mortal-nussknacker.part5.rar
396 22.01.2015 14:44:42 INFO    zoxp8grptbepyvrk saved as mortal-nussknacker.part5.rar
395 22.01.2015 14:43:48 DEBUG   Content-Disposition: mortal-nussknacker.part5.rar
394 22.01.2015 14:43:47 INFO    FilerNet: Direct download link detected
393 22.01.2015 14:43:46 DEBUG   FilerNet: Redirect #2 to: http://dl14.filer.net/dl/fff4706981b13afb2a0fe088f513d81e/54c0feaf/zoxp8grptbepyvrk/mortal-nussknacker.part5.rar
392 22.01.2015 14:43:46 DEBUG   Content-Disposition: mortal-nussknacker.part4.rar
391 22.01.2015 14:43:46 DEBUG   FilerNet: Redirect #1 to: http://filer.net/dl/ddfac81f6477ddd7975ee6902dcb24fbf761cf4c/zoxp8grptbepyvrk?apikey=
390 22.01.2015 14:43:46 DEBUG   FilerNet: Redirect #0 to: http://filer.net/get/zoxp8grptbepyvrk
389 22.01.2015 14:43:46 DEBUG   FilerNet: Looking for direct download link...
388 22.01.2015 14:43:46 DEBUG   FilerNet: File status: queued | File info: {'status': 3, 'url': u'http://filer.net/get/zoxp8grptbepyvrk', 'name': u'zoxp8grptbepyvrk', 'size': 0}
387 22.01.2015 14:43:46 DEBUG   FilerNet: File name: zoxp8grptbepyvrk | File size: 120825137
386 22.01.2015 14:43:46 DEBUG   FilerNet: File info (AFTER): {'status': 3, 'url': u'http://filer.net/get/zoxp8grptbepyvrk', 'name': u'zoxp8grptbepyvrk', 'size': 0}
385 22.01.2015 14:43:45 INFO    FilerNet: Direct download link detected
384 22.01.2015 14:43:45 DEBUG   FilerNet: File info (BEFORE): {}
383 22.01.2015 14:43:45 INFO    Download starts: mortal-nussknacker.part5.rar
382 22.01.2015 14:43:44 INFO    Download finished: mortal-nussknacker.part3.rar
381 22.01.2015 14:43:44 INFO    uo0jtsizwum1kkzg saved as mortal-nussknacker.part3.rar
380 22.01.2015 14:43:44 DEBUG   FilerNet: Redirect #2 to: http://dl13.filer.net/dl/0b811143e85f2863e0f1dd9e9031df76/54c0fead/jeqjczcvcsustlz8/mortal-nussknacker.part4.rar
379 22.01.2015 14:43:44 DEBUG   FilerNet: Redirect #1 to: http://filer.net/dl/1063c49b6141a3b7e0e76a93c12fc37b6db983cf/jeqjczcvcsustlz8?apikey=
378 22.01.2015 14:43:44 DEBUG   FilerNet: Redirect #0 to: http://filer.net/get/jeqjczcvcsustlz8
377 22.01.2015 14:43:44 DEBUG   FilerNet: Looking for direct download link...
376 22.01.2015 14:43:44 DEBUG   FilerNet: File status: queued | File info: {'status': 3, 'url': u'http://filer.net/get/jeqjczcvcsustlz8', 'name': u'jeqjczcvcsustlz8', 'size': 0}
375 22.01.2015 14:43:44 DEBUG   FilerNet: File name: jeqjczcvcsustlz8 | File size: 209715200
374 22.01.2015 14:43:44 DEBUG   FilerNet: File info (AFTER): {'status': 3, 'url': u'http://filer.net/get/jeqjczcvcsustlz8', 'name': u'jeqjczcvcsustlz8', 'size': 0}
373 22.01.2015 14:43:43 DEBUG   FilerNet: File info (BEFORE): {}
372 22.01.2015 14:43:43 INFO    Download starts: mortal-nussknacker.part4.rar
371 22.01.2015 14:43:42 INFO    Download finished: mortal-nussknacker.part2.rar
370 22.01.2015 14:43:42 INFO    e3efn5lhhqlbo9z2 saved as mortal-nussknacker.part2.rar
369 22.01.2015 14:43:42 INFO    Download finished: mortal-nussknacker.part1.rar
368 22.01.2015 14:41:57 DEBUG   Content-Disposition: mortal-nussknacker.part3.rar
367 22.01.2015 14:41:56 INFO    FilerNet: Direct download link detected
366 22.01.2015 14:41:55 DEBUG   FilerNet: Redirect #2 to: http://dl13.filer.net/dl/aecfb6545198a79223e352a1917b629e/54c0fe40/uo0jtsizwum1kkzg/mortal-nussknacker.part3.rar
365 22.01.2015 14:41:55 DEBUG   Content-Disposition: mortal-nussknacker.part2.rar
364 22.01.2015 14:41:55 DEBUG   FilerNet: Redirect #1 to: http://filer.net/dl/504a985b80022526ed625f8fae1c89a3dd2130da/uo0jtsizwum1kkzg?apikey=
363 22.01.2015 14:41:55 DEBUG   FilerNet: Redirect #0 to: http://filer.net/get/uo0jtsizwum1kkzg
362 22.01.2015 14:41:55 DEBUG   FilerNet: Looking for direct download link...
361 22.01.2015 14:41:55 DEBUG   FilerNet: File status: queued | File info: {'status': 3, 'url': u'http://filer.net/get/uo0jtsizwum1kkzg', 'name': u'uo0jtsizwum1kkzg', 'size': 0}
360 22.01.2015 14:41:55 DEBUG   FilerNet: File name: uo0jtsizwum1kkzg | File size: 209715200
359 22.01.2015 14:41:55 DEBUG   FilerNet: File info (AFTER): {'status': 3, 'url': u'http://filer.net/get/uo0jtsizwum1kkzg', 'name': u'uo0jtsizwum1kkzg', 'size': 0}
358 22.01.2015 14:41:54 INFO    FilerNet: Direct download link detected
357 22.01.2015 14:41:54 DEBUG   FilerNet: File info (BEFORE): {}
356 22.01.2015 14:41:54 INFO    Download starts: mortal-nussknacker.part3.rar
355 22.01.2015 14:41:53 DEBUG   FilerNet: Redirect #2 to: http://dl13.filer.net/dl/2c79897fff5736fcc8e08fa56e72f53b/54c0fe3e/e3efn5lhhqlbo9z2/mortal-nussknacker.part2.rar
354 22.01.2015 14:41:53 DEBUG   Content-Disposition: mortal-nussknacker.part1.rar
353 22.01.2015 14:41:53 DEBUG   FilerNet: Redirect #1 to: http://filer.net/dl/4edf325e67c7a8df8baa01319628758b803bc0b9/e3efn5lhhqlbo9z2?apikey=
352 22.01.2015 14:41:53 DEBUG   FilerNet: Redirect #0 to: http://filer.net/get/e3efn5lhhqlbo9z2
351 22.01.2015 14:41:53 DEBUG   FilerNet: Looking for direct download link...
350 22.01.2015 14:41:53 DEBUG   FilerNet: File status: queued | File info: {'status': 3, 'url': u'http://filer.net/get/e3efn5lhhqlbo9z2', 'name': u'e3efn5lhhqlbo9z2', 'size': 0}
349 22.01.2015 14:41:53 DEBUG   FilerNet: File name: e3efn5lhhqlbo9z2 | File size: 209715200
348 22.01.2015 14:41:53 DEBUG   FilerNet: File info (AFTER): {'status': 3, 'url': u'http://filer.net/get/e3efn5lhhqlbo9z2', 'name': u'e3efn5lhhqlbo9z2', 'size': 0}
347 22.01.2015 14:41:52 INFO    FilerNet: Direct download link detected
346 22.01.2015 14:41:52 DEBUG   FilerNet: File info (BEFORE): {}
345 22.01.2015 14:41:52 INFO    Download starts: mortal-nussknacker.part2.rar
344 22.01.2015 14:41:51 DEBUG   FilerNet: Redirect #2 to: http://dl14.filer.net/dl/0223a725723fe7cfe399dd5a4bc11564/54c0fe3c/ybimusfylmy0n8hy/mortal-nussknacker.part1.rar
343 22.01.2015 14:41:51 DEBUG   FilerNet: Redirect #1 to: http://filer.net/dl/96a88eff6368cd418f295fa6f35f2c630059d718/ybimusfylmy0n8hy?apikey=
342 22.01.2015 14:41:50 DEBUG   FilerNet: Redirect #0 to: http://filer.net/get/ybimusfylmy0n8hy
341 22.01.2015 14:41:50 DEBUG   FilerNet: Looking for direct download link...
340 22.01.2015 14:41:50 DEBUG   FilerNet: File status: online | File info: {'status': 2, 'url': u'http://filer.net/get/ybimusfylmy0n8hy', 'size': 209715200.0, 'name': u'mortal-nussknacker.part1.rar', 'pattern': {'S': u'200.00', 'U': u'MB', 'N': u'mortal-nussknacker.part1.rar'}}
339 22.01.2015 14:41:50 DEBUG   FilerNet: File name: mortal-nussknacker.part1.rar | File size: 209715200
338 22.01.2015 14:41:50 DEBUG   FilerNet: File info (AFTER): {'status': 2, 'url': u'http://filer.net/get/ybimusfylmy0n8hy', 'size': 209715200.0, 'name': u'mortal-nussknacker.part1.rar', 'pattern': {'S': u'200.00', 'U': u'MB', 'N': u'mortal-nussknacker.part1.rar'}}
337 22.01.2015 14:41:50 DEBUG   FilerNet: File info (BEFORE): {}
336 22.01.2015 14:41:50 INFO    Download starts: http://filer.net/get/ybimusfylmy0n8hy...

**Comment by vuolter** [comment]
@cryzto If you could share your account with me, I can have a look at this. ;)

**Comment by michiil** [comment]
Its the same via premiumize i could share the account with you if you still need it (:

**Comment by vuolter** [comment]
@michiil Yes, thanks! :D

**Comment by michiil** [comment]
@vuolter i wrote you a pm on the forum (:

**Comment by vuolter** [comment]
@michiil I'll check it tonight. ;)

**Comment by cryzto** [comment]
Hi there
i could but how to send a pm? Sorry

**Comment by vuolter** [comment]
@cryzto PM me on forum or send an email to vuolter@gmail.com ;)

**Comment by cryzto** [comment]
Done via pm!
(Never did that before ;-))

**Comment by cryzto** [comment]
Howzit going?
I still see this issue :-(

**Comment by vuolter** [comment]
Checking...

**Comment by cryzto** [comment]
...any solutions?

**Comment by cryzto** [comment]
@michiil : Do you still use the Filer.net-plugin? Does it work for you?

**Comment by cavebeat** [comment]
same problem here with file names. . then i reinstalled on Debian Jessie, now its completely broken and refuse to use premiumize.

**Comment by GammaC0de** [comment]
FilerNet works properly.
