### ISSUE TITLE
WebUI-Issues with package-names (FilerNet-Plugin)

### ISSUE THREAD

**Issue by cryzto** [pyload/pyload#1063]
Hi there
When I create a Download-package it won't take my chosen name (Plugin: FilerNet). Instead it takes it from the file-name?
See here:
![package-name error 1](https://cloud.githubusercontent.com/assets/6126067/5856122/5d3a6b0c-a240-11e4-8be3-24f7faa5df59.png)
![package-name error 2](https://cloud.githubusercontent.com/assets/6126067/5856129/65357e3c-a240-11e4-99d3-67a4171f0205.png)

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/issues/1062

**Comment by cryzto** [comment]
@vuolter : is this a feature request? I mean it worked before...

**Comment by vuolter** [comment]
Worked because folder name was not parsed before, but now FilerNet do it like all the other decrypters. :S

**Comment by cryzto** [comment]
Still no success?...sorry to bother...

**Comment by vuolter** [comment]
...still no checked... :P

**Comment by DylanBryanRoss** [comment]
any updates here? sorry to bring up an old issue. :)

**Comment by Velociraptor85** [comment]
@cryzto @GammaC0de do you know if this is still valid :?

**Comment by GammaC0de** [comment]
Don't think so.
