### ISSUE TITLE
 Waiting time not correct #1065 closed unfixed

### ISSUE THREAD

**Issue by JeanMars** [pyload/pyload#1067]
Hi,
sorry but this one is not fixed; just updated pyload and log shows:
865 23.01.2015 00:04:09 INFO    Download starts: ***
864 23.01.2015 00:04:09 INFO    Reconnected, new IP:
863 23.01.2015 00:04:07 INFO    Starting reconnect
862 23.01.2015 00:04:06 INFO    Download starts: ***
[...]
804 23.01.2015 00:02:41 INFO    Reconnected, new IP: ***
803 23.01.2015 00:02:36 INFO    Starting reconnect
802 23.01.2015 00:02:34 INFO    Download starts: ***
801 23.01.2015 00:02:34 INFO    Reconnected, new IP:
800 23.01.2015 00:02:33 INFO    Starting reconnect

log does no longer show time to wait but on "home" tab, it is easy to see that waiting time fluctates within a 5 sec range.
I'm not using a prenium account.

Thanks,
Jean

**Comment by Dandf** [comment]
Try to set to off the reconnection mode in the configuration page. This will solved my problem that was identical to yours
