### ISSUE TITLE
ReCaptcha broken

### ISSUE THREAD

**Issue by zapp-brannigan** [pyload/pyload#1069]
After the latest changes to CaptchaService.py and ShareonlineBiz.py, the old recaptcha isn't working anymore:
`WARNING   Download failed: xxx.part1.rar | ReCaptcha instance has no attribute 'old'`

**Comment by Killer1337** [comment]
I am getting this too for an uploaded.net file.

**Comment by Killer1337** [comment]
Quickly solved, as always! Thank you!

**Comment by Killer1337** [comment]
Something is still not right with recaptcha I think. No captcha is ever approved for me. ReCaptcha always returns "err":"captcha" : 

    25.01.2015 07:22:42 INFO      Captcha9Kw: 317 credits left
    25.01.2015 07:22:42 DEBUG     Captcha9Kw: NewCaptchaID ticket: 37356554 | tmp/tmpCaptcha_UploadedTo_96175.jpg
    25.01.2015 07:23:04 INFO      Captcha9Kw: Captcha result for ticket 37356554: onentiot much
    25.01.2015 07:23:05 DEBUG     Received captcha result: onentiot much
    25.01.2015 07:23:05 DEBUG     UploadedTo: ReCaptcha result: onentiot much
    25.01.2015 07:23:06 DEBUG     UploadedTo: Result: {"err":"captcha"}
    25.01.2015 07:23:06 DEBUG     Captcha9Kw: Request refund: OK

This happens when 9Kw is used as well as when they are manually solved

**Comment by Killer1337** [comment]
That did it. Works fine now
