### ISSUE TITLE
Wrong waiting time in OneFichierCom when retry

### ISSUE THREAD

**Issue by Dandf** [pyload/pyload#1072]
Since the last update, the waiting time does not decrement correctly on onfichier download.
Example: 30min --> 29min57 --> 29min 55 --> 29min58 etc etc...

Here is a part of my log file
534 23.01.2015 22:47:37 INFO    Download starts: xxx
535 23.01.2015 22:47:37 DEBUG   OneFichierCom: File info (BEFORE): {}
536 23.01.2015 22:47:37 DEBUG   OneFichierCom: File info (AFTER): {'status': 2, 'url': u'http://z2z10aruc1.1fichier.com/en/en/en/en/en/en/en/en/', 'size': 367337144.32, 'name': u'xxx', 'pattern': {'HOST': u'1fichier.com', 'U': u'MB', 'ID1': u'z2z10aruc1', 'ID2': None, 'S': u'350.32', 'N': u'xxx'}}
537 23.01.2015 22:47:37 DEBUG   OneFichierCom: File name: xxx | File size: 367337144
538 23.01.2015 22:47:39 INFO    Starting reconnect
539 23.01.2015 22:47:39 DEBUG   Old IP:
540 23.01.2015 22:47:41 INFO    Reconnected, new IP: XXXXXXX
541 23.01.2015 22:47:41 INFO    Download starts: xxx
542 23.01.2015 22:47:41 DEBUG   OneFichierCom: File info (BEFORE): {}
543 23.01.2015 22:47:41 DEBUG   OneFichierCom: File info (AFTER): {'status': 2, 'url': u'http://z2z10aruc1.1fichier.com/en/en/en/en/en/en/en/en/', 'size': 367337144.32, 'name': u'xxx', 'pattern': {'HOST': u'1fichier.com', 'U': u'MB', 'ID1': u'z2z10aruc1', 'ID2': None, 'S': u'350.32', 'N': u'xxx'}}
544 23.01.2015 22:47:41 DEBUG   OneFichierCom: File name: xxx | File size: 367337144
545 23.01.2015 22:47:43 INFO    Starting reconnect
546 23.01.2015 22:47:43 DEBUG   Old IP:
547 23.01.2015 22:47:46 INFO    Reconnected, new IP: XXXXXXXX
548 23.01.2015 22:47:46 INFO    Download starts: xxx
549 23.01.2015 22:47:46 DEBUG   OneFichierCom: File info (BEFORE): {}
550 23.01.2015 22:47:46 DEBUG   OneFichierCom: File info (AFTER): {'status': 2, 'url': u'http://z2z10aruc1.1fichier.com/en/en/en/en/en/en/en/en/', 'size': 367337144.32, 'name': u'xxx', 'pattern': {'HOST': u'1fichier.com', 'U': u'MB', 'ID1': u'z2z10aruc1', 'ID2': None, 'S': u'350.32', 'N': u'xxx'}}
551 23.01.2015 22:47:46 DEBUG   OneFichierCom: File name: xxx | File size: 367337144
552 23.01.2015 22:47:48 INFO    Starting reconnect
553 23.01.2015 22:47:49 DEBUG   Old IP: XXXXXXX

Thanks

**Comment by Dandf** [comment]
After many search, it seems that the reconnection mode is the problem. After disabling this mode, the timer work fine!
I hope that this will serve others

**Comment by vuolter** [comment]
Reconnection was fixed in 0.4.10, but keep this as reminder...

**Comment by Velociraptor85** [comment]
@GammaC0de not sure if domain still works

**Comment by GammaC0de** [comment]
https://1fichier.com/

No known issues with this plugin.
