### ISSUE TITLE
Problem with DLC decrypting - ERROR

### ISSUE THREAD

**Issue by koffy84** [pyload/pyload#1075]
Always getting following messages:
25.01.2015 02:20:13 INFO      Aktiviere Accounts...
25.01.2015 02:20:13 INFO      Starting threaded webserver: 0.0.0.0:8000
25.01.2015 02:20:13 INFO      Activating Plugins...
25.01.2015 02:20:13 INFO      pyLoad is up and running
25.01.2015 02:20:17 INFO      Decrypting starts: tmp_u6k89gscke.dlc
25.01.2015 02:20:17 ERROR     Decrypting failed: tmp_u6k89gscke.dlc | 'module' object has no attribute 'dom'  

Runs on Xbmcbuntu in newest version from Git.
Tried new installation and configuration, but didn't work. Same error with different DLC-Files.

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/issues/1074
