### ISSUE TITLE
fileUrl() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by Spedy123456** [pyload/pyload#1079]
Downloading any file over normal HTTP responds with the message "fileUrl() takes at least 2 arguments (1 given)"
Had this issue with .rar files and also testet to download http://google.de index file and got the same error. 
Downloading on RaspberryPi

429	25.01.2015 23:01:54	INFO	Download starts: http://google.de
430	25.01.2015 23:01:54	WARNING	Download failed: Unknown | fileUrl() takes at least 2 arguments (1 given)
431	25.01.2015 23:01:54	INFO	UnSkipOnFail: Looking for skipped duplicates of: Unknown (pid:16)
432	25.01.2015 23:01:54	INFO	UnSkipOnFail: No duplicates found

**Comment by vuolter** [comment]
I think your BasePlugin is outdated.

**Comment by Spedy123456** [comment]
INFO	UpdateManager: No new pyLoad version available
I will try to download the newest version of BasePlugin directly...

**Comment by Spedy123456** [comment]
My BasePlugin already had been in v 0.33, but now after overwriting the same Version from Github, its working!
How could that be?

**Comment by vuolter** [comment]
Do you talking about the BasePlugin under the userplugins folder, right?

**Comment by Spedy123456** [comment]
Yes "userplugins/hosters/BasePlugin.py"

And got it on GitHub from "pyload/module/plugins/hoster/BasePlugin.py"

**Comment by vuolter** [comment]
I do not even want to know what happens... :P
