### ISSUE TITLE
ExtractArchive does not finish (extracting starts over and over again)

### ISSUE THREAD

**Issue by zlep** [pyload/pyload#1080]
ExtractArchive is still broken. It starts extracting the same package over and over again. If the file is completely extracted it (say 1,5 GB) it goes back to 0 MB and starts extracting from the beginning.

Fix this shit extracting plugin! It's annoying!

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/8848a359a43316fb346b728d1d79d7b72d27e5a0
Please reopen if not fixed.
