### ISSUE TITLE
config of renamed or deleted plugins is not deleted

### ISSUE THREAD

**Issue by Bambie42** [pyload/pyload#1081]
When renaming plugins like in c4f167e267ba949ee20ec8a6d3c611d6dd93b325 the old name in configuration will still remain. I don't know what will be the best solution for that. Maybe testing, if there is a plugin with that name and when not, delete the configuration?

**Comment by vuolter** [comment]
Working yet on a fix... please wait.

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/b6dc723bf214e8680f7be29594581d3da5033b90
