### ISSUE TITLE
API Bash

### ISSUE THREAD

**Issue by HPP8140** [pyload/pyload#1082]
Hi, Sorry if this is the wrong forum for this question.

How can I call the API from a bash script?

http://localhost:8000/api/generateAndAddPackages?links={"https://www.youtube.com/playlist?list=PLOO"}

Thanks.

**Comment by vuolter** [comment]
See: https://github.com/pyload/pyload/issues/341

**Comment by HPP8140** [comment]
Well, I just learned about the command line interface, that worked.
