### ISSUE TITLE
Can´t open DLC Files?

### ISSUE THREAD

**Issue by simonsal** [pyload/pyload#1083]
Hello,

in the last Time I can´t open any DLC Files with PyLoad! I get an Error "No Plugin matched".
He Shows me the directory from a DLC File like this "\pyload_download\tmp_TAAHMS01-4yiik8npcr5l8.dlc".
My Download Directory ist "\pyload_download\..." .´Normally he don´t save that File in this Directory but now he do.

PS.: If I want to add an DLC File, I get this in my Logfile:
698    27.01.2015 19:52:42    INFO    pyLoad is up and running
699    27.01.2015 19:52:44    INFO    UpdateManager: No new pyLoad version available
700    27.01.2015 19:52:44    INFO    UpdateManager: No plugin updates available
701    27.01.2015 19:52:46    INFO    Download starts: \pyload_download\tmp_TAAHMS01-4yiik8npcr5l8.dlc
702    27.01.2015 19:52:46    WARNING    Download failed: \pyload_download\tmp_TAAHMS01-4yiik8npcr5l8.dlc | No plugin matched
703    27.01.2015 19:52:46    INFO    UnSkipOnFail: Looking for skipped duplicates of: \pyload_download\tmp_TAAHMS01-4yiik8npcr5l8.dlc (pid:68)
704    27.01.2015 19:52:46    INFO    UnSkipOnFail: No duplicates found

**Comment by vuolter** [comment]
See: https://github.com/pyload/updatemanager/issues/18
