### ISSUE TITLE
Improve feedback of failing start

### ISSUE THREAD

**Issue by krichter722** [pyload/pyload#1085]
Invoking `python pyLoadCli.py -a 0.0.0.0 -u user -p 7227 --pw="password"` fails with nothing but 

```
Could not establish connection to 0.0.0.0:7227. 
```

It'd be great to have know why the connection couldn't be established (port occupied, connection timeout, etc.). Experienced with 7a0c370482142b113ab70fa1bb1446223a707c62.

**Comment by diman82** [comment]
I'm facing the same issue.
Any ideas how to tackle this?
