### ISSUE TITLE
ExtractArchive:  Archive Error | Empty Archive

### ISSUE THREAD

**Issue by zlep** [pyload/pyload#1088]
Here we go again. Same error on every package. Tested with about 20 different packages:

INFO	ExtractArchive: example.part2.rar | Extract to: Downloads/
ERROR	ExtractArchive: example.part2.rar | Archive Error | Empty Archive
ERROR	ExtractArchive: example.part2.rar | Extract failed

Manual extracting works fine as always. So definitely a Plugin Issue

**Comment by j4m** [comment]
same here

**Comment by vuolter** [comment]
Sample url please.

**Comment by zlep** [comment]
Sample? Doesn't matter. Any!!!
Anyway, here is just one example: http://download.serienjunkies.org/f-66216c8475c5f874/so_tvs-tbbt-ded-dl-ithd-x264-801.html

**Comment by SelmaUrban** [comment]
In "ExtractArchive.py" v1.10 search for:

    excludefiles = clearList(self.getConfig("excludefiles"))
    excludefiles = self.getConfig("excludefiles")

an delete the:

    excludefiles = self.getConfig("excludefiles")

or set it to:

    #excludefiles = self.getConfig("excludefiles")

**Comment by vuolter** [comment]
@SelmaUrban Thx!
https://github.com/pyload/pyload/commit/52acc62381d165b615ebbb4414d846c7aee462d5
