### ISSUE TITLE
Updatemanager error removing

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#1089]
Hello, i have in debugging mode many message like this "UpdateManager: Error removing: XFSPAccount.py | [Errno 2] No such file or directory: 'userplugins/internal/XFSPAccount.py'" or this "UpdateManager: Error removing: DLC_25.py | [Errno 2] No such file or directory: 'userplugins/container/DLC_25.py' "
There are also other files.
Best regards

**Comment by immenz** [comment]
Same here after a fresh install on Windows

**Comment by feuerwasser85** [comment]
same as me. there are 83 messages like yours.

**Comment by vuolter** [comment]
Okay, I will remove unnecessary logs like that.
