### ISSUE TITLE
PremiumTo with/or UploadedTo has stopped working

### ISSUE THREAD

**Issue by sasese** [pyload/pyload#1094]
PremiumTo is no longer accepting UploadedTo links. When packages (uploaded.net and/or ul.to) are **queued** via FlexGet or directly via pyLoad's webui 0 byte files are downloaded.

**Comment by sasese** [comment]
UploadedTo has been flagged at PremiumTo. The issue is likely there.

**Comment by Mister-XY** [comment]
Anything must be wrong, because, i can download from uploaded.to user via premium.to with Jdownloader2.
