### ISSUE TITLE
Turbobit.net premium account still doesn't work

### ISSUE THREAD

**Issue by geminiarek** [pyload/pyload#1095]
Is any chance to do something to get premium account start working?

**Comment by geminiarek** [comment]
some news in this case?

**Comment by vuolter** [comment]
Turbobit plugin need a complete rewrite.

**Comment by Velociraptor85** [comment]
@geminiarek Is this still the case?
If so please contact @GammaC0de with a premium account to solve the issue

**Comment by GammaC0de** [comment]
TurbobitNet is unsupported a.t.m. due to html/js obscuration.
