### ISSUE TITLE
uploaded.to: problems with checkErrors() for premium users, no downloads with premium account

### ISSUE THREAD

**Issue by oliverrahner** [pyload/pyload#1096]
Downloading with version 0.78 of the UploadedTo hoster plugin throws "File not downloadable for free users" error.
I haven't fully understood how the plugin handles premium downloads, but all cases seem to go through checkErrors(). "Current waiting period" is only there for free users, so the plugin exits with self.fail()

**Comment by oliverrahner** [comment]
There are several checks in checkErrors() that are only valid for free users, maybe this method should be split.

**Comment by oliverrahner** [comment]
Did a quick and dirty fix for the downloading issue in 7a8b6edcfba91e2ecf5652c4f8bde9c6ec925fc8

**Comment by Killer1337** [comment]
After update to 0.79 I still get the same error

**Comment by oliverrahner** [comment]
"The same error" being "File not downloadable for free users"?

**Comment by Killer1337** [comment]
yes.

**Comment by oliverrahner** [comment]
Sorry, but I couldn't find any mention whether you have an uploaded.to premium account?

**Comment by Killer1337** [comment]
No I don't

**Comment by oliverrahner** [comment]
Yes, because my problem was that I do have a premium account, and it gave me the same error message, which makes even less sense than in your case.
I'm only a "normal user" and thought I'd make the fix that helped me available to others :)
But I will take a quick look whether I can replicate your issue.
