### ISSUE TITLE
ExtractArchive: Starts extracting the same file again and again

### ISSUE THREAD

**Issue by zlep** [pyload/pyload#1098]
ExtractArchive still not working! It starts extracting the same file again and again (like I already posted as an issue a few days ago). When the file should be done extracting it starts at 0 MB again.

Are you f*** kidding us with this shit?!??!!

Edit: And now it's gone completely again:

Archive Error | Process terminated

Why the fuck could you not just leave it as it was a few weeks ago? Everything worked like a charm!!! Fucking hell this is so annoying!!

Attached my settings.
Sample: http://download.serienjunkies.org/f-66216c8475c5f874/so_tvs-tbbt-ded-dl-ithd-x264-801.html

![extract](https://cloud.githubusercontent.com/assets/10477541/5961576/0cbfabc6-a7de-11e4-8517-3e048ddc88a5.png)

**Comment by immenz** [comment]
Did you have the password in your unrar_password.txt or did you provide it in the package?

**Comment by zlep** [comment]
Tried both. Same result. I tried so many things in the last days and nothing worked. This plugin is completely fucked up.

**Comment by zlep** [comment]
Ok, just tried it again. If I put the password in the unbar_passwords.txt it does not finish extracting.

If I provide the password in the package it actually extracts the package successfully. BUT in the log I get

Archive Error | Process terminated
ERROR	ExtractArchive: tvs-tbbt-ded-dl-ithd-x264-801.part1.rar | Extract failed

and it does not delete the finished archive files.

**Comment by immenz** [comment]
You running under Windows? 

I've just testet in windows, and there unrar.exe did not return any returncall, or the p (popen) object. Therefore the check 
    if p.returncode != 0:
            raise ArchiveError("Process terminated")

allways raise error.

**Comment by stickell** [comment]
@zlep: keep calm please! This is a free software made by volunteers that spends a lot of hours working on code without any kind of payment! If you don't like it you could use JDownloader... it has a company behind!
Do you realize that @vuolter is just one single person and you are hundreds asking for features and reporting bugs?

If @vuolter has updated the code there has been a reason right? But if you enjoy the old version why don't you just force it in your installation? However if you will be patient (it's the minimum in my opinion) I'm sure he will do everything possible to fix it.

**Comment by vuolter** [comment]
I'm working on a fix.

**Comment by zlep** [comment]
No, there was no reason to change it. Everything run fantastic and he changed it without any reason. If I wouldn't have accidentally switched on the Updatemanager everything would be still alright. That's why I'm so pissed. 
Anyway I already tried to install the old version of ExtractArchive but it did not work. I guess he changed other things which do not work with the old version. BTW. I'm running pyload on a NAS.

**Comment by immenz** [comment]
What I understand was that the change should disable extracting of  several finished packages at the same time. And I think this feature is a reason, especially on a NAS....

**Comment by zlep** [comment]
Yes, sure that would have been a great feature to have but if you're doing such fundamental changes to an important plugin you should test it a few weeks with several people before messing it up and not getting working it again afterwards.

**Comment by immenz** [comment]
Yes, the Unrar.py i meant is in plugins/Internal 

I update my pyload dist on nas regularly with merged source from stable branch and my own. I think the latest commit I use is https://github.com/pyload/pyload/commit/99ed44b0d919a33e3a559472893163b347cd1c37

**Comment by stickell** [comment]
Just take a look to the commit messages to understand why he made the changes.

As @immenz has suggested you could simply checkout an old commit using git.
If you prefer manually you can find every old version here on GitHub as the repository saves all the history.

**Comment by mobo95** [comment]
same problem here.

**Comment by zlep** [comment]
Still nor working. I also tried the suggested solution by @immenz I replaced the ExtractArchive.py and the UnRar.py. It actually extracts the file completely but I get 

Extracting finished
ERROR	ExtractArchive: xxxx UnRar instance has no attribute 'file'
ERROR	ExtractArchive: xxx.part2.rar | Extract failed

and it does not delete the archive files.

**Comment by mobo95** [comment]
In this time i've disabled the plugin.
i will activate it again when will be fixed

**Comment by vuolter** [comment]
I just pushed a fix.

**Comment by mobo95** [comment]
Same problem:

31.01.2015 11:31:37	INFO	ExtractArchive: Check package: Rocky IV (1985) BluRay Rip 1080p
31.01.2015 11:31:38	INFO	ExtractArchive: rck8580.part59.rar | Extract to: Downloads/Rocky IV (1985) BluRay Rip 1080p/Rocky IV (1985) BluRay Rip 1080p

31.01.2015 11:33:21	INFO	ExtractArchive: rck8580.part59.rar | Extracting finished
31.01.2015 11:33:21	INFO	ExtractArchive: rck8580.part62.rar | Extract to: Downloads/Rocky IV (1985) BluRay Rip 1080p/Rocky IV (1985) BluRay Rip 1080p

31.01.2015 11:35:07	INFO	ExtractArchive: rck8580.part62.rar | Extracting finished
31.01.2015 11:35:07	INFO	ExtractArchive: rck8580.part61.rar | Extract to: Downloads/Rocky IV (1985) BluRay Rip 1080p/Rocky IV (1985) BluRay Rip 1080p

**Comment by zlep** [comment]
Not working

481	31.01.2015 11:40:28	DEBUG	ExtractArchive: unrar vb -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -pserienjunkies.org -v Downloads/tvs-tbbt-ded-dl-ithd-x264-801.part1.rar
482	31.01.2015 11:40:28	ERROR	ExtractArchive: tvs-tbbt-ded-dl-ithd-x264-801.part1.rar | Unknown Error | global name 'plugin' is not defined
483	31.01.2015 11:40:28	ERROR	ExtractArchive: tvs-tbbt-ded-dl-ithd-x264-801.part1.rar | Extract failed
484	31.01.2015 11:40:28	INFO	ExtractArchive: tvs-tbbt-ded-dl-ithd-x264-801.part2.rar | Extract to: Downloads/
485	31.01.2015 11:40:28	DEBUG	ExtractArchive: unrar l -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v Downloads/tvs-tbbt-ded-dl-ithd-x264-801.part2.rar
486	31.01.2015 11:40:28	INFO	ExtractArchive: tvs-tbbt-ded-dl-ithd-x264-801.part2.rar | Password protected
487	31.01.2015 11:40:28	DEBUG	ExtractArchive: Password: serienjunkies.org
488	31.01.2015 11:40:28	DEBUG	ExtractArchive: Try password: serienjunkies.org
489	31.01.2015 11:40:28	DEBUG	ExtractArchive: unrar l -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -pserienjunkies.org -v Downloads/tvs-tbbt-ded-dl-ithd-x264-801.part2.rar
490	31.01.2015 11:40:28	DEBUG	ExtractArchive: unrar x -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -pserienjunkies.org Downloads/tvs-tbbt-ded-dl-ithd-x264-801.part2.rar Downloads/

**Comment by zlep** [comment]
__version__ = "1.16"

not working. same issue... this is ridiculous...

**Comment by stickell** [comment]
@vuolter I think you should revert to an old stable version until you have a good tested plugin. Until you are sure you can share a public beta with some users willing to help you testing it.

**Comment by vuolter** [comment]
It's almost done... no revert anymore. I tried and was worse than ever. XD
