### ISSUE TITLE
Error ExtractArchive

### ISSUE THREAD

**Issue by DKeppi** [pyload/pyload#1102]
ERROR	Error importing ExtractArchive: invalid syntax (ExtractArchive.py, line 345)

Could you fix this pls? :)

**Comment by immenz** [comment]
https://github.com/pyload/pyload/commit/9f5aa7aec672ee184a640910fcda2d818e8f19fe
https://github.com/pyload/pyload/issues/1101

**Comment by stickell** [comment]
The new fixed version 1.13 is now been distributed by the update manager.
