### ISSUE TITLE
problem on downloads

### ISSUE THREAD

**Issue by ananias47** [pyload/pyload#1104]
![screenshot 2015-01-30 10 40 39](https://cloud.githubusercontent.com/assets/6560173/5973068/a72931e4-a86c-11e4-9b85-6881e9913db2.png)

**Comment by stickell** [comment]
In your downloads folder there is one or more entry with a bad character in its name.
We have improved a lot the charset support in 0.4.10 but we can't do anything in 0.4.9 directly because it's a core issue.

You could hunt for that char in your downloads folder.

**Comment by ananias47** [comment]
how can i update to 0.4.10 or it is beta for now???

thnx

**Comment by stickell** [comment]
0.4.10 is not ready for release. However if you like to try it you can checkout the master branch.
