### ISSUE TITLE
[JustPremium] descriptor 'strip' requires a 'str' object but received a 'unicode'

### ISSUE THREAD

**Issue by immenz** [pyload/pyload#1107]
30.01.2015 11:23:06 DEBUG     PremiumizeMe: Get Account Info for xxx
    30.01.2015 11:23:07 DEBUG     PremiumizeMe: {u'status': 200, u'result': {u'trafficleft_gigabytes': xxx, u'trafficleft_bytes': xxx, u'expires': xxx, u'fairuse_left': xxx, u'extuid': u'xxx', u'type': u'premium', u'account_name': u'xxx'}, u'statusmessage': u'OK'}
    30.01.2015 11:23:07 DEBUG     PremiumizeMe: Account Info: {'validuntil': xxx, 'trafficleft': xxx}
    30.01.2015 11:23:07 ERROR     Error executing hooks: descriptor 'strip' requires a 'str' object but received a 'unicode'
    Traceback (most recent call last):
    File "/volume1/@appstore/pyload/pyload/module/HookManager.py", line 88, in new return func(*args)
    File "/volume1/@appstore/pyload/pyload/module/HookManager.py", line 198, in coreReady plugin.coreReady()
    File "/volume1/@appstore/pyload/pyload/module/plugins/hooks/JustPremium.py", line 32, in  coreReady
    self.hosts    = map(str.strip, (hosts[1:] + "," + self.getConfig("nicehoster")).split(','))
    TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'

**Comment by vuolter** [comment]
Sorry, I started rewrite before read your post. :S
https://github.com/pyload/pyload/commit/a206e9103c6d791caf780be3de6ce6ceda13b793

**Comment by immenz** [comment]
No Problem, I just wanted to help you a little since you've got so much other stuff to care about^^

After a quick view over your changes, it seemes that the Multihoster thing isn't in your code yet. Should i rewrite your code or would you do it?

**Comment by vuolter** [comment]
Nope, no multihoster support here, but any improvement is welcome! :+1:
