### ISSUE TITLE
UploadedTo: File not downloadable for free users

### ISSUE THREAD

**Issue by Killer1337** [pyload/pyload#1108]
Hi there,
since UploadedTo v0.77 i get the error message
`Download failed: FileXY.rar | File not downloadable for free users`

The error remained after updating UploadedTo (v0.77 -> v0.78) and still after (v0.78 -> v0.79).

I use NO Premium account @oliverrahner already adressed and fixed this for premium users in #1096 but for free users the problem remains. Other than reported by the plugin the file is downloadable for free users manually via browser.

I'd be glad to run further tests and supply logs if requested.

**Comment by kasperj** [comment]
I'm getting this error with a premium account:
'ascii' codec can't encode character u'\u2026' in position 105: ordinal not in range(128)

**Comment by StarScream159** [comment]
I'm getting the same error as kasperj. I'm assuming it is from long file names being truncated and replaced with the Unicode 'HORIZONTAL ELLIPSIS' (U+2026).

The update today fixed the "file not downloadable for free users". Maybe we better start a new thread for the other issue.

**Comment by Killer1337** [comment]
Which update are you speaking of?
on 0.79 I am still getting "file not downloadable for free users" and updatemanager doesn't offer any newer version

**Comment by Killer1337** [comment]
I manually reverted back to 0.76 and disabled updatemanager for now.
This works fine for me without premium.

So I guess the rewriting process from 0.76 to 0.77 messed it up.

Unless other than code cleanup real issues were adressed during this rewriting, I would kindly ask you guys to revert the official stable repo to 0.76 as this works.

**Comment by oliverrahner** [comment]
I did the same (reverting back to 0.77), and I'd second Killer1337's request.

I think a rewrite was in order, but it didn't seem thoroughly planned.

I could try spending some time in reworking the rewrite coming week if that helps.

**Comment by immenz** [comment]
Did you try https://github.com/immenz/pyload/commit/8ae95c4b389c916b8f3b961be1a4eb145f0b2381 ?
