### ISSUE TITLE
uplea plugin reports a non existing issue

### ISSUE THREAD

**Issue by JeanMars** [pyload/pyload#1112]
Hi,
after an uplea download completes, module output "failedDownload link not found" for the link but the file seems correctly downloaded, just a wrong message.

**Comment by vuolter** [comment]
Please debug log.

**Comment by JeanMars** [comment]
Hi,
here is a log:
21	10.02.2015 22:05:45	INFO	UnSkipOnFail: No duplicates found
20	10.02.2015 22:05:45	INFO	UnSkipOnFail: Looking for skipped duplicates of: somefile.avi (pid:1)
19	10.02.2015 22:05:45	WARNING	Download failed: somefile.avi | Download link not found
18	10.02.2015 22:04:39	INFO	Download starts:  somefile.avi
17	10.02.2015 22:04:38	INFO	Added package tmp containing 1 links
16	09.02.2015 23:32:16	INFO	UpdateManager: No plugin updates available
15	09.02.2015 23:32:16	INFO	UpdateManager: No new pyLoad version available
14	09.02.2015 23:32:13	INFO	pyLoad is up and running
13	09.02.2015 23:32:13	INFO	XFileSharingPro: Handling any crypter I can!
12	09.02.2015 23:32:13	INFO	XFileSharingPro: Handling any hoster I can!
11	09.02.2015 23:32:13	INFO	ExtractArchive: Activated UnRar SevenZip UnZip
10	09.02.2015 23:32:13	INFO	Activating Plugins...
9	09.02.2015 23:32:10	INFO	Activating Accounts...
8	09.02.2015 23:32:10	INFO	Starting lightweight webserver (bjoern): 0.0.0.0:8000
7	09.02.2015 23:32:10	INFO	Free space: 3.09 TiB
6	09.02.2015 23:32:04	INFO	Starting ThriftBackend: 0.0.0.0:7227
5	09.02.2015 23:32:04	INFO	Downloadtime: True

As you can see, an error is reported as download link not found at the end of the download but the file is correctly downloaded.
