### ISSUE TITLE
ExctractArchive 1.14 new problem

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1116]
I got this:

31.01.2015 10:09:47	INFO	Package finished: Rocky III (1982) BluRay Rip 1080p
31.01.2015 10:09:47	INFO	ExtractArchive: Check package: Rocky III (1982) BluRay Rip 1080p
31.01.2015 10:09:47	INFO	ExtractArchive: rckIII8280.part57.rar | Extract to: Downloads/Rocky III (1982) BluRay Rip 1080p/Rocky III (1982) BluRay Rip 1080p

31.01.2015 10:11:52	INFO	ExtractArchive: rckIII8280.part57.rar | Extracting finished
31.01.2015 10:11:52	ERROR	ExtractArchive: rckIII8280.part57.rar | Unknown Error | UnRar instance has no attribute 'file'
31.01.2015 10:11:52	ERROR	ExtractArchive: rckIII8280.part57.rar | Extract failed
31.01.2015 10:11:52	INFO	ExtractArchive: rckIII8280.part56.rar | Extract to: Downloads/Rocky III (1982) BluRay Rip 1080p/Rocky III (1982) BluRay Rip 1080p

31.01.2015 10:13:51	INFO	ExtractArchive: rckIII8280.part56.rar | Extracting finished
31.01.2015 10:13:51	ERROR	ExtractArchive: rckIII8280.part56.rar | Unknown Error | UnRar instance has no attribute 'file'
31.01.2015 10:13:51	ERROR	ExtractArchive: rckIII8280.part56.rar | Extract failed
31.01.2015 10:13:51	INFO	ExtractArchive: rckIII8280.part52.rar | Extract to: Downloads/Rocky III (1982) BluRay Rip 1080p/Rocky III (1982) BluRay Rip 1080p

Was working good weeks ago

I'm using these settings:
![settings](https://cloud.githubusercontent.com/assets/10552743/5987768/ace87eb4-a93e-11e4-8930-b4957e263a93.PNG)

**Comment by VinceGitHub** [comment]
Now i get: 
542	31.01.2015 11:28:57	DEBUG	ExtractArchive: New file /xxx.mp3 does not exists 

I also think we have to change the line 383 
from 
 self.logDebug("Would delete: %s" % ", ".join(plugin.getDeleteFiles()))
To
 self.logDebug("Would delete: %s" % ", ".join(archive.getDeleteFiles()))

**Comment by mobo95** [comment]
Same as before, always loop.
The only things are that i didn't got anymore ERROR messages.
After "Extracting finished" message, it extract again

**Comment by VinceGitHub** [comment]
For the second "looping" problem. In ExtractArchive.py Line 264 What if we Change 
 
         fname = os.path.basename(filename)
         if filename in processed: 
               self.logDebug(fname, "Skipped")
         continue
         processed.append(filename) # prevent extracting same file twice

To something like

         fname = os.path.splitext(filename)[0]
         if ".part" in fname :                          
              fname = os.path.splitext(fname)[0]
                      
          if fname in processed:
              self.logDebug(filename, "Skipped")
              continue

          processed.append(fname)

**Comment by wastez** [comment]
This is the newest error on 1.16. 

31.01.2015 14:14:22 INFO      ExtractArchive: Check package: tcpa-revolution_s02e01_p_rp
31.01.2015 14:14:22 INFO      ExtractArchive: tcpa-revolution_s02e01_p_rp.part1.rar | Extract to: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/
31.01.2015 14:14:44 ERROR     ExtractArchive: tcpa-revolution_s02e01_p_rp.part1.rar | No password found
31.01.2015 14:14:44 ERROR     ExtractArchive: tcpa-revolution_s02e01_p_rp.part1.rar | Extract failed
31.01.2015 14:14:44 INFO      ExtractArchive: tcpa-revolution_s02e01_p_rp.part2.rar | Extract to: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/
31.01.2015 14:15:06 ERROR     ExtractArchive: tcpa-revolution_s02e01_p_rp.part2.rar | No password found
31.01.2015 14:15:06 ERROR     ExtractArchive: tcpa-revolution_s02e01_p_rp.part2.rar | Extract failed
31.01.2015 14:15:06 INFO      ExtractArchive: tcpa-revolution_s02e01_p_rp.part3.rar | Extract to: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/
31.01.2015 14:15:30 ERROR     ExtractArchive: tcpa-revolution_s02e01_p_rp.part3.rar | No password found
31.01.2015 14:15:30 ERROR     ExtractArchive: tcpa-revolution_s02e01_p_rp.part3.rar | Extract failed
31.01.2015 14:15:30 INFO      ExtractArchive: tcpa-revolution_s02e01_p_rp.part4.rar | Extract to: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/
31.01.2015 14:15:53 ERROR     ExtractArchive: tcpa-revolution_s02e01_p_rp.part4.rar | No password found
31.01.2015 14:15:53 ERROR     ExtractArchive: tcpa-revolution_s02e01_p_rp.part4.rar | Extract failed

**Comment by wastez** [comment]
Oh... What is also not working:
extracting status is not displayed and deleting files after extracting is not saved after restart.

**Comment by mobo95** [comment]
i think that this plugin should be deleted and then redone

**Comment by VinceGitHub** [comment]
@wastez Bist du dir sicher das du ein Password bereitstellt? egal ob im Package oder in der Passwortdatei?

**Comment by wastez** [comment]
Ganz sicher....

**Comment by wastez** [comment]
Habe deinen 2ten fix implementiert, der loop scheint weg zu sein.

Hier ein auszug aus der Debug log:
31.01.2015 15:56:18 DEBUG     ExtractArchive: Extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
31.01.2015 15:56:18 INFO      ExtractArchive: Check package: tcpa-revolution_s02e01_p_rp
31.01.2015 15:56:18 DEBUG     All downloads processed
31.01.2015 15:56:18 DEBUG     ExtractArchive: Targets for UnRar: [(u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp.part1.rar', 7635), (u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp.part2.rar', 7636), (u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp.part3.rar', 7637), (u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp.part4.rar', 7638)]
31.01.2015 15:56:18 DEBUG     ExtractArchive: Extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
31.01.2015 15:56:18 INFO      ExtractArchive: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp | Extract to: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/
31.01.2015 15:56:18 DEBUG     ExtractArchive: unrar l -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp.part1.rar
31.01.2015 15:56:18 DEBUG     ExtractArchive: unrar vb -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp.part1.rar
31.01.2015 15:56:18 DEBUG     ExtractArchive: Password: No provided
31.01.2015 15:56:18 DEBUG     ExtractArchive: unrar x -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp.part1.rar /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/
31.01.2015 15:56:41 ERROR     ExtractArchive: tcpa-revolution_s02e01_p_rp.part1.rar | No password found
31.01.2015 15:56:41 ERROR     ExtractArchive: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp | Extract failed
31.01.2015 15:56:41 DEBUG     ExtractArchive: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp.part2.rar | Skipped
31.01.2015 15:56:41 DEBUG     ExtractArchive: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp.part3.rar | Skipped
31.01.2015 15:56:41 DEBUG     ExtractArchive: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tcpa-revolution_s02e01_p_rp.part4.rar | Skipped

**Comment by VinceGitHub** [comment]
Dann lass und doch weiter probieren. Wenn ich in der Datei UnRar.py Line 92 das hier

        for attr in self.re_filelist.findall(out):
            if attr[0].startswith("*"):
                raise PasswordError

Mit dem hier ersetze,

        for attr in self.re_filelist.findall(out):        
	     attr = filter(None,attr)
	     if attr[0].startswith("*"):
                raise PasswordError

funktioniert dein Packet. Kannste das bestätigen?

**Comment by wastez** [comment]
Yeaah....
Das extrahieren funktioniert jetzt.

Jetzt wäre noch die anzeige des status interessant und das "Deleting after finish" gespeichert wird.

**Comment by SelmaUrban** [comment]
@VinceGitHub 
Works great

@vuolter 
Please integrate fixes for:
ExtractArchive.py Line 264
UnRar.py Line 92

**Comment by vuolter** [comment]
Fixed some stuff.

**Comment by wastez** [comment]
The extracting with Passwords is again Not working.

**Comment by wastez** [comment]
Also on 1.22 its Not possible to extract a password protected file.

**Comment by vuolter** [comment]
Really odd: the plugin uses password even if not required. :S

**Comment by mobo95** [comment]
If one archive is corrupted, queued package doesn't start to extract:

01.02.2015 09:47:44	INFO	Package finished: Rocky Balboa (2006) BluRay Rip 1080p
01.02.2015 09:47:44	INFO	ExtractArchive: Check package: Rocky Balboa (2006) BluRay Rip 1080p
01.02.2015 09:47:44	INFO	ExtractArchive: rckblb0280.part01.rar | Extract to: Downloads/Rocky Balboa (2006) BluRay Rip 1080p/Rocky Balboa (2006) BluRay Rip 1080p
01.02.2015 09:47:46	INFO	Package finished: Bullet
01.02.2015 09:47:46	INFO	ExtractArchive: Package Bullet queued for later extracting
01.02.2015 09:49:48	ERROR	ExtractArchive: rckblb0280.part01.rar | CRC mismatch |
?	?	Rocky Balboa.2006.1080p.BluRay.x264.SlCr3w.mkv : packed data CRC failed in volume Downloads/Rocky Balboa (2006) BluRay Rip 1080p/rckblb0280.part48.rar
?	?	Rocky Balboa.2006.1080p.BluRay.x264.SlCr3w.mkv - CRC failed
01.02.2015 09:49:48	ERROR	ExtractArchive: rckblb0280.part01.rar | Extract failed

Package Bullet now should start to extract but this doesn't happen.


Also, what about "repair broken archives"? This function is working?

**Comment by wastez** [comment]
Its again the "no password found" error if a rar File is pw protected.

**Comment by mobo95** [comment]
You're right.
Archive with password can't be extracted due to "Wrong Password" error....

01.02.2015 11:37:25	INFO	ExtractArchive: bulle.part01.rar | Extract to: Downloads/Bullet/Bullet
01.02.2015 11:37:25	INFO	ExtractArchive: bulle.part01.rar | Password protected
01.02.2015 11:37:36	ERROR	ExtractArchive: bulle.part01.rar | Wrong password
01.02.2015 11:37:36	ERROR	ExtractArchive: bulle.part01.rar | Extract failed

**Comment by vuolter** [comment]
@mobo95 Hey, no fake commands here! :smiling_imp: 
SevenZip and the built-in UnZip don't have repair feature, UnRar does.
