### ISSUE TITLE
Premium.to 0 bytes

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#1117]
Anything must be wrong, because, i can download from uploaded.to via premium.to with Jdownloader2. via uploaded.to i get only a 0 bytes file
and this is what i get in pyload with the same file

467 31.01.2015 08:45:56 INFO Download finished: x
466 31.01.2015 08:45:56 DEBUG Download Check triggered
465 31.01.2015 08:45:56 DEBUG Download Check triggered
464 31.01.2015 08:45:55 DEBUG PremiumTo: Handled as premium download
463 31.01.2015 08:45:55 INFO PremiumTo: Filesize: 0 KiB, Traffic left for user Mister XY: 2003964873 KiB
462 31.01.2015 08:45:55 DEBUG PremiumTo: Account Info: {'validuntil': -1, 'premium': True, 'trafficleft': 2003964873.0146484}
461 31.01.2015 08:45:55 DEBUG PremiumTo: Get Account Info for Mister XY
460 31.01.2015 08:45:55 DEBUG PremiumTo: File status: queued | File info: {'status': 3, 'url': u'x', 'name': u'bx', 'size': 0}
459 31.01.2015 08:45:55 DEBUG PremiumTo: File info (BEFORE): {}
458 31.01.2015 08:45:55 INFO Download starts: x
457 31.01.2015 08:45:35 DEBUG PremiumTo: Regexp: .(?Pdepfile.com|dizzcloud.com|filemonkey.in|fileparadox.in).
456 31.01.2015 08:45:35 DEBUG PremiumTo: New hosters: depfile.com, dizzcloud.com, filemonkey.in, fileparadox.in
455 31.01.2015 08:45:35 DEBUG PremiumTo: Overwritten hosters: BitshareCom, ExtabitCom, FilepostCom, FilerNet, FiredriveCom, FourSharedCom, FreakshareCom, Keep2ShareCc, LetitbitNet, NetloadIn, NitroflareCom, OboomCom, OneFichierCom, RapidgatorNet, RapidshareCom, SecureUploadEu, TurbobitNet, UploadableCh, UploadedTo, UptoboxCom
454 31.01.2015 08:45:35 INFO PremiumTo: Reloading supported hoster list
453 31.01.2015 08:45:33 INFO pyLoad is up and running

**Comment by sasese** [comment]
UploadedTo links (uploaded.net and ul.to) links are failing in pyLoad but work on PremiumTo's site. Trouble is expanding to include rapdgator, but as those links don't work on PremiumTo's site either, that may be due to changes on rapidgator giving rise to issue #1118.

**Comment by Mister-XY** [comment]
Now i get this info wenn i download a file. Pyload load an 29 bytes file. and in the file stand this.
"You entered a wrong auth code"

**Comment by audicted** [comment]
I can confirm the problem. Downloading from uploaded.to and ul.to works via premium.to but not with pyload. All files are getting downloaded, but contain only: "You entered a wrong auth code". Also their file name is something like "http:ul.to15fjbvxh".

The problem also persists with the current (stable) version from git (did a git pull today).

**Comment by stickell** [comment]
Let's see...

**Comment by stickell** [comment]
API reply with uploaded links is:
`Uploaded.net banned all of our servers. This means that we can no longer provide Uploaded.net. We apologize for any inconvenience this may cause.`

**Comment by Mister-XY** [comment]
Ok, on the premium.to site, i can download via uploaded.to.

**Comment by stickell** [comment]
A sample link please

**Comment by Mister-XY** [comment]
here is the link
http://uploaded.net/file/qywizj90
http://premium.to/getfile.php?link=uploaded.net%2Ffile%2Fqywizj90

**Comment by stickell** [comment]
I tried your link on the site and it doesn't work even there! Still get the message about the ban

**Comment by Mister-XY** [comment]
I think you can't download because, you are not locked in as Premium by premium.to

**Comment by stickell** [comment]
Of course I am. I logged in, pasted the link in the download form and redirected to a page with the message ban.

**Comment by Mister-XY** [comment]
Ok, i have no problem, i can download it from the Premium.to HP. If it possible, that i have special traffic and you not?

**Comment by stickell** [comment]
I don't think so

**Comment by Mister-XY** [comment]
Have you special traffic?

**Comment by stickell** [comment]
Yes

**Comment by Mister-XY** [comment]
ok, can you give me an link with your Downloadlink?

**Comment by stickell** [comment]
Premium.to support has told me that only a few users are allowed to download from Uploaded and that you should change your password with a simplier one. You should use only letters and numbers, no special chars.

**Comment by Mister-XY** [comment]
Ok, than, i'am an one from few users ^^

**Comment by stepanzel** [comment]
Hey guys, I'd like to have this bug reopened because it still persists. 
When downloading from UL or SO via premium.to I only get a 29-bytes file saying "You entered a wrong auth code". Downloading directly from premium.to-website works though. My password only contains letters and numbers.
Perhaps it could be a workaround to use user+password authentication for getfile instead of authcode or vice versa?

**Comment by stepanzel** [comment]
Added log to previous post.

**Comment by Mister-XY** [comment]
I have no problems. I have the new updates (do you also?)
and i have also this file http://www.file-upload.net/download-10535109/PremiumTo.py.html
from this issue https://github.com/pyload/pyload/issues/1337
in my ./userplugins/accounts directory.
i don't know if this help you.
