### ISSUE TITLE
rapidgator issue

### ISSUE THREAD

**Issue by akfedux** [pyload/pyload#1118]
Hi,

TypeError: int() argument must be a string or a number, not 'tuple'

link to forum about this http://forum.pyload.org/viewtopic.php?f=12&t=3980

**Comment by anshkathuria** [comment]
I just rolled back to 0.06 version of RapidgatorNet plugin and it worked like a charm.

Copy the code from http://pastebin.com/s22QrNi9 and paste in accounts/RapidgatorNet.py 

Also change the version from 0.06 to 0.08 to prevent this from auto upgrading and delete .pyc file.

**Comment by vuolter** [comment]
@anshkathuria Both version are pratically the same, so... why should the 0.06 work if 0.08 not?

**Comment by akfedux** [comment]
It might be that the "trafficleft" calculation issue is related to account.
I use only one premium hoster rapidgator.net.
Maybe you are right, "trafficleft" calculation issue, but in rapidgator hoster.
I can use premium downloads in rapidgator, but I can't enter to the settings page.
You got it?  :)


02.02.2015 10:32:08 INFO UpdateManager: No plugin updates available
02.02.2015 10:34:04 DEBUG Redirected import module.plugins.accounts.RapidgatorNet -> userplugins.accounts.RapidgatorNet
02.02.2015 10:34:04 DEBUG RapidgatorNet: API:LOGIN | {"response":{"session_id":"it0jmh1jn8fu0505mu8v48aqi4","expire_date":1426775926,"traffic_left":"2702871359365"},"response_status":200,"response_details":null}
02.02.2015 10:34:04 DEBUG RapidgatorNet: Scheduled Account refresh for rg7ee@xeb.net in 0 seconds.
02.02.2015 10:34:04 DEBUG RapidgatorNet: Get Account Info for rg7ee@xeb.net
02.02.2015 10:34:04 DEBUG RapidgatorNet: API:USERINFO | {"response":{"expire_date":1426775926,"traffic_left":"2702871359365"},"response_status":200,"response_details":null}
02.02.2015 10:34:04 DEBUG RapidgatorNet: Account Info: {'premium': True, 'sid': 'it0jmh1jn8fu0505mu8v48aqi4', 'validuntil': (1426775926,), 'trafficleft': (2639522811.879883,)}
