### ISSUE TITLE
ExtractArchive.py doesnt store setting and won't delete archives

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1122]
So. 
I'd like to delete after succesfull extraction. 
1.but it doesnt store this setting
2. if i set it to true manually and trigger the package to extract, it extracts but only deletes 1 file (part1.rar)

talking about this setting: Delete archive when successfully extracted

01.02.2015 09:57:16 DEBUG     ExtractArchive: Extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
01.02.2015 09:57:16 INFO      ExtractArchive: Check package: 123
01.02.2015 09:57:16 DEBUG     ExtractArchive: Targets for UnRar: [(u'Downloads/123/123.part1.rar', 1206)]
01.02.2015 09:57:16 INFO      ExtractArchive: 123.part1.rar | Extract to: Downloads/123/
01.02.2015 09:57:16 DEBUG     ExtractArchive: unrar l -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v Downloads/123/123.part1.rar
01.02.2015 09:57:16 DEBUG     All downloads processed
01.02.2015 09:57:16 DEBUG     ExtractArchive: Extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
01.02.2015 09:57:16 DEBUG     ExtractArchive: Password: No provided
01.02.2015 09:57:16 DEBUG     ExtractArchive: unrar x -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- Downloads/123/123.part1.rar Downloads/123/
01.02.2015 09:58:06 DEBUG     ExtractArchive: unrar vb -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v Downloads/123/123.part1.rar
01.02.2015 09:58:06 DEBUG     ExtractArchive: Would delete: Downloads/123/123.part1.rar
01.02.2015 09:58:06 INFO      ExtractArchive: 123.part1.rar | Extracting finished
01.02.2015 09:58:06 DEBUG     All downloads finished
01.02.2015 09:58:06 DEBUG     ExtractArchive: Extracted files: [u'Downloads/123/123', u'Downloads/123/123/Sample/123-sample.mkv', u'Downloads/123/123.mkv', u'Downloads/123/Sample']

**Comment by wastez** [comment]
Also extracting with a password protected file is not possible. 
And the extracting status is also not displayed.
