### ISSUE TITLE
Uploaded.to wrong archive naming

### ISSUE THREAD

**Issue by taker2one** [pyload/pyload#1127]
Hi,

Following problem occurs when downloading splitted archives from uploaded.to/net

If the archive names are the long they get shorten by some .... which will follow in not downloading all files ( cause they have all the same name)

Example:
Archive Name
Series.S02E02.German.D.ubbed…rar
instead of
Series.S02E02.German.D.ubbed.720.p.HDTV.x.264-ZZGtv.part1.rar

I tried to find the issue and think its caused by the INFO_PATTERN in uploadeto.py hoster script INFO_PATTERN

This will take the name of the link on the uploaded page which is not fully written if to long.
I'm not sure if this is the problem but thats all i found out so far :)

Btw im not an native english speaker so dont blame me ;)

**Comment by stickell** [comment]
@vuolter: Content-disposition needs to be enabled. In the new SimpleHoster class it is disabled, in my opinion we could create a config attribute like `DISPOSITION = True` as a pattern to put in those plugins which requires it.

**Comment by vuolter** [comment]
@stickell Disposition is broken in 0.4.9: doesn't parse "attached" and "charset" flag, but @kmarty fixed it in 0.4.10 (currently in my 0.4.10 branch). u.u

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/issues/1110
