### ISSUE TITLE
LF (Line Feed) in Filename causes Download Crash on Windows

### ISSUE THREAD

**Issue by immenz** [pyload/pyload#1134]
I think this problem is related to some uploadedTo problems here recently, where the downloaded file needed to be renamed because they causing problems else.

Don't think it's an specific UploadedTo problem, but when the file name got from some url pattern has an \n character in it, it causes download to crash on windows (because of "\n" in filename). On Linux Systems that seems to work fine.

Don't know where to change it exactly, but I think a simple check for "bad character" in filename should solve the problem.

EDIT: Just saw https://github.com/pyload/pyload/issues/1129, think it's the same problem

    02.02.2015 11:16:56 DEBUG     UploadedTo: File name: curl-7.40.0.zip
     | File size: 6127024

    02.02.2015 11:17:09 DEBUG     Error removing chunk: curl object not on this multi-stack
    02.02.2015 11:17:09 WARNING   Download failed: curl-7.40.0.zip
     | [Errno 22] invalid mode ('wb') or filename: u'd:\\downloads\\curl-7.40.0.zip\n.chunk0'
    Traceback (most recent call last):
      File "D:\Projekte\Coding\pyload\module\PluginThread.py", line 187, in run
        pyfile.plugin.preprocessing(self)
      File "D:\Projekte\Coding\pyload\module\plugins\Plugin.py", line 237, in preprocessing
        return self.process(self.pyfile)
      File "D:\Projekte\Coding\pyload\module\plugins\internal\SimpleHoster.py", line 490, in process
        self.downloadLink(self.link)
      File "D:\Projekte\Coding\pyload\module\plugins\internal\SimpleHoster.py", line 503, in downloadLink
    self.download(link, ref=False, disposition=disposition)
     File "D:\Projekte\Coding\pyload\module\plugins\Plugin.py", line 503, in download
        progressNotify=self.pyfile.setProgress, disposition=disposition)
      File "D:\Projekte\Coding\pyload\module\network\Browser.py", line 88, in httpDownload
        name = self.dl.download(chunks, resume)
      File "D:\Projekte\Coding\pyload\module\network\HTTPDownload.py", line 129, in download
        self._download(chunks, resume)
      File "D:\Projekte\Coding\pyload\module\network\HTTPDownload.py", line 160, in _download
        self.m.add_handle(init.getHandle())
      File "D:\Projekte\Coding\pyload\module\network\HTTPChunk.py", line 201, in getHandle
        self.fp = open(fs_name, "wb")
    IOError: [Errno 22] invalid mode ('wb') or filename: u'd:\\downloads\\curl-7.40.0.zip\n.chunk0'
    02.02.2015 11:17:10 INFO      Debug Report written to debug_UploadedTo_02-02-2015_11-17-10.zip

**Comment by vuolter** [comment]
Please post the content of your debug_UploadedTo_02-02-2015_11-17-10.zip. You found it in your pyload config directory.

**Comment by immenz** [comment]
debug_report.txt. Any Other file? (several *dump.html files) 

   pyLoad 0.4.9 Debug Report of UploadedTo 0.81 

    TRACEBACK:
     Traceback (most recent call last):
      File "D:\Projekte\Coding\pyload\module\PluginThread.py", line 187, in run
        pyfile.plugin.preprocessing(self)
      File "D:\Projekte\Coding\pyload\module\plugins\Plugin.py", line 237, in preprocessing
        return self.process(self.pyfile)
      File "D:\Projekte\Coding\pyload\module\plugins\internal\SimpleHoster.py", line 490, in process
        self.downloadLink(self.link)
      File "D:\Projekte\Coding\pyload\module\plugins\internal\SimpleHoster.py", line 503, in downloadLink
        self.download(link, ref=False, disposition=disposition)
      File "D:\Projekte\Coding\pyload\module\plugins\Plugin.py", line 503, in download
        progressNotify=self.pyfile.setProgress, disposition=disposition)
      File "D:\Projekte\Coding\pyload\module\network\Browser.py", line 88, in httpDownload
        name = self.dl.download(chunks, resume)
      File "D:\Projekte\Coding\pyload\module\network\HTTPDownload.py", line 129, in download
        self._download(chunks, resume)
      File "D:\Projekte\Coding\pyload\module\network\HTTPDownload.py", line 160, in _download
        self.m.add_handle(init.getHandle())
      File "D:\Projekte\Coding\pyload\module\network\HTTPChunk.py", line 201, in getHandle
        self.fp = open(fs_name, "wb")
    IOError: [Errno 22] invalid mode ('wb') or filename: u'd:\\downloads\\serien\\curl-7.40.0.zip\n.chunk0'
     

    FRAMESTACK:

    Frame preprocessing in D:\Projekte\Coding\pyload\module\plugins\Plugin.py at line 237
                        self = <module.plugins.hoster.UploadedTo.UploadedTo object at 0x04A03590>
                      thread = <DownloadThread(Thread-6, started daemon 816)>

    Frame process in D:\Projekte\Coding\pyload\module\plugins\internal\SimpleHoster.py at line 490
                      pyfile = PyFile 44: curl-7.40.0.zip
    @UploadedTo
                        self = <module.plugins.hoster.UploadedTo.UploadedTo object at 0x04A03590>

    Frame downloadLink in D:\Projekte\Coding\pyload\module\plugins\internal\SimpleHoster.py at line 503
                        self = <module.plugins.hoster.UploadedTo.UploadedTo object at 0x04A03590>
                        link = 'http://fra-7m19-stor07.uploaded.net/dl/b1de138f-9a33-4cf9-ab2e-d3fa98d824e0'
                 disposition = False

    Frame download in D:\Projekte\Coding\pyload\module\plugins\Plugin.py at line 505
                     cookies = True
                        name = u'curl-7.40.0.zip\n'
                         get = {}
             download_folder = u'd:\\downloads\\serien'
                        self = <module.plugins.hoster.UploadedTo.UploadedTo object at 0x04A03590>
                    filename = u'd:\\downloads\\serien\\curl-7.40.0.zip\n'
                         url = 'http://fra-7m19-stor07.uploaded.net/dl/b1de138f-9a33-4cf9-ab2e-d3fa98d824e0'
                    location = u'd:\\downloads\\serien\\'
                 disposition = False
                        post = {}
                         ref = False

    Frame httpDownload in D:\Projekte\Coding\pyload\module\network\Browser.py at line 88
                     cookies = True
              progressNotify = <bound method PyFile.setProgress of PyFile 44: curl-7.40.0.zip
    @UploadedTo>
                      resume = False
                         url = 'http://fra-7m19-stor07.uploaded.net/dl/b1de138f-9a33-4cf9-ab2e-d3fa98d824e0'
                        self = <module.network.Browser.Browser object at 0x049BAAB0>
                         get = {}
                    filename = u'd:\\downloads\\serien\\curl-7.40.0.zip\n'
                 disposition = False
                      chunks = 1
                        post = {}
                         ref = False

    Frame download in D:\Projekte\Coding\pyload\module\network\HTTPDownload.py at line 145
                      chunks = 1
                        self = <module.network.HTTPDownload.HTTPDownload instance at 0x04A24418>
                      resume = False

    Frame _download in D:\Projekte\Coding\pyload\module\network\HTTPDownload.py at line 160
                      chunks = 1
                        self = <module.network.HTTPDownload.HTTPDownload instance at 0x04A24418>
                        init = <HTTPChunk id=0, size=-1, arrived=0>
                      resume = False

    Frame getHandle in D:\Projekte\Coding\pyload\module\network\HTTPChunk.py at line 201
                     fs_name = u'd:\\downloads\\serien\\curl-7.40.0.zip\n.chunk0'
                        self = <HTTPChunk id=0, size=-1, arrived=0>


    PLUGIN OBJECT DUMP: 

                     API_KEY = 'lhF2IeeprweDfu9ccWlxXVVypA5nA3EL'
               CHECK_TRAFFIC = False
                     COOKIES = True
                 DIRECT_LINK = None
              DL_LIMIT_ERROR = 'You have reached the max. number of possible free downloads for this hour'
        LINK_PREMIUM_PATTERN = '<div class="tfree".*\\s*<form method="post" action="(.+?)"'
               LOGIN_ACCOUNT = False
                MULTI_HOSTER = False
           NAME_REPLACEMENTS = [('&#?\\w+;', <function fixup at 0x028580F0>)]
           SIZE_REPLACEMENTS = []
               TEXT_ENCODING = False
            URL_REPLACEMENTS = [('https?://(?:www\\.)?(uploaded\\.(to|net)|ul\\.to)(/file/|/?\\?id=|.*?&id=|/)(?P<ID>\\w+).*',
      'http://uploaded.net/file/\\g<ID>')]
                WAIT_PATTERN = 'Current waiting period: <span>(\\d+)'
                     account = None
                       cTask = <module.CaptchaManager.CaptchaTask instance at 0x0498C850>
                  chunkLimit = 1
                      config = <module.ConfigParser.ConfigParser instance at 0x029E9FD0>
                        core = <__main__.Core object at 0x029EAFB0>
                    directDL = False
                        html = "{type:'download',url:'http://fra-7m19-stor07.uploaded.net/dl/b1de138f-9a33-4cf9-ab2e-d3fa98d824e0',name:'curl-7.40.0.zip',size:'6127024'}"
                        info = {'name': u'curl-7.40.0.zip\n',
     'pattern': {'ID': u'16osnpvl'},
     'size': 6127024.0,
     'status': 2,
     'url': u'http://uploaded.net/file/16osnpvl'}
                          js = <module.common.JsEngine.JsEngine instance at 0x02BD15A8>
                   lastCheck = None
                lastDownload = ''
                     limitDL = 0
                        link = 'http://fra-7m19-stor07.uploaded.net/dl/b1de138f-9a33-4cf9-ab2e-d3fa98d824e0'
                         log = <logging.Logger object at 0x02978C30>
                     multiDL = False
                   multihost = False
                         ocr = None
                     premium = False
                      pyfile = PyFile 44: curl-7.40.0.zip
    @UploadedTo
                         req = <module.network.Browser.Browser object at 0x049BAAB0>
              resumeDownload = False
                     retries = 0
                      thread = <DownloadThread(Thread-6, started daemon 816)>
                        user = None
                   waitUntil = 0
                     waiting = False
               wantReconnect = False

    PYFILE OBJECT DUMP: 

                       _size = 0
                       abort = False
                      active = False
                       error = "[Errno 22] invalid mode ('wb') or filename: u'd:\\\\downloads\\\\serien\\\\curl-7.40.0.zip\\n.chunk0'"
                          id = 44
                        lock = <_RLock owner=None count=0>
                           m = <module.database.FileDatabase.FileHandler instance at 0x029E9FA8>
                 maxprogress = 100
                        name = u'curl-7.40.0.zip\n'
                       order = 0
                   packageid = 15
                      plugin = <module.plugins.hoster.UploadedTo.UploadedTo object at 0x04A03590>
                 pluginclass = <class 'module.plugins.hoster.UploadedTo.UploadedTo'>
                pluginmodule = <module 'module.plugins.hoster.UploadedTo' from 'D:\Projekte\Coding\pyload\module\plugins\hoster\UploadedTo.pyc'>
                  pluginname = u'UploadedTo'
                    progress = 0
                 reconnected = False
                        size = 0
                      status = 8
                  statusname = None
                         url = u'http://uploaded.net/file/16osnpvl'
                   waitUntil = 1422872215.426
