### ISSUE TITLE
[ExtractArchive] doesn't extract Zip Files

### ISSUE THREAD

**Issue by immenz** [pyload/pyload#1138]
When downloading Zip Files, unrar is used first. Because Unrar doesn't extract zip, just rar, but just give the output
    something.zip is not RAR archive
    No files to extract
no error is raised. Then the zip file is deleted

EDIT: This happens on a NAS (LINUX). On Windows it uses UnZip as expected...
EDIT2: On windows only Unzip is installed/used.

    02.02.2015 21:34:26 INFO      Download finished: curl-7.40.0.zip
    02.02.2015 21:34:26 INFO      Package finished: test
    02.02.2015 21:34:26 DEBUG     ExtractArchive: Extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
    02.02.2015 21:34:26 INFO      ExtractArchive: Check package: test
    02.02.2015 21:34:26 DEBUG     All downloads processed
    02.02.2015 21:34:26 DEBUG     ExtractArchive: Targets for UnRar: [(u'/volume1/pyload/downloads/curl-7.40.0.zip', 48)]
    02.02.2015 21:34:26 INFO      ExtractArchive: curl-7.40.0.zip | Extract to: /volume1/pyload/downloads/
    02.02.2015 21:34:26 DEBUG     ExtractArchive: Extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
    02.02.2015 21:34:26 DEBUG     All downloads finished
    02.02.2015 21:34:26 DEBUG     ExtractArchive: unrar l -o- -or -x -y -p- -v /volume1/pyload/downloads/curl-7.40.0.zip
    02.02.2015 21:34:26 DEBUG     ExtractArchive: Password: No provided
    02.02.2015 21:34:26 DEBUG     ExtractArchive: unrar e -o- -or -x -y -p- /volume1/pyload/downloads/curl-7.40.0.zip /volume1/pyload/downloads/
    02.02.2015 21:34:26 DEBUG     ExtractArchive: unrar lb -o- -or -x -y -p- -v /volume1/pyload/downloads/curl-7.40.0.zip
    02.02.2015 21:34:26 DEBUG     ExtractArchive: Would delete: /volume1/pyload/downloads/curl-7.40.0.zip
    02.02.2015 21:34:26 INFO      ExtractArchive: Deleting 1 files
    02.02.2015 21:34:26 INFO      ExtractArchive: curl-7.40.0.zip | Extracting finished
    02.02.2015 21:34:26 DEBUG     All downloads finished
    02.02.2015 21:34:26 DEBUG     ExtractArchive: Extracted files: []
    02.02.2015 21:34:26 DEBUG     ExtractArchive: Targets for SevenZip: [(u'/volume1/pyload/downloads/curl-7.40.0.zip', 48)]
    02.02.2015 21:34:26 DEBUG     ExtractArchive: curl-7.40.0.zip | Skipped
    02.02.2015 21:34:26 DEBUG     ExtractArchive: Targets for UnZip: [(u'/volume1/pyload/downloads/curl-7.40.0.zip', 48)]
    02.02.2015 21:34:26 DEBUG     ExtractArchive: curl-7.40.0.zip | Skipped

**Comment by immenz** [comment]
https://github.com/pyload/pyload/pull/1141

**Comment by stickell** [comment]
Has #1141 fully fixed this issue? If so please close

**Comment by immenz** [comment]
Not really, it's a kind of workaround. 

In @vuolter s ExtractArchive, it loops through all Extractors installed on the system. The Extractor which has defined a suitable File Format for Extraction will handle it. The Order Extractor were used is Unrar, SevenZip, Unzip I think. Problem is, that Unrar doesn't extract ZIP Files by design. . So I only changed that Unrar tries to handle zip files. If SevenZip is installed, it will cause a crash, because at least on my test system the SevenZip plugin does not work. If SevenZip is not installed, unzip will do the job correctly.

**Comment by stickell** [comment]
Looks like they still need some work. I can't help you very much because I've never used this plus and never worked on it. I think @vuolter knows it better than me

**Comment by immenz** [comment]
I'm on it, sevenzip is working. Still have some changes to make, but this specific problem is solved
