### ISSUE TITLE
Checksum update problem

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1140]
On latest update i get this on every download:
03.02.2015 15:37:25 WARNING Checksum: Unable to validate checksum for file: prtdcrbcnfndlmnd0780.part03.rev

what this plugin for?

**Comment by StarScream159** [comment]
I am getting this too. I use Uploaded.to. I also have "Use Checksum:" set to "Off" in the general settings.

**Comment by immenz** [comment]
@StarScream159 There is also a plugin "Checksum" on its own under Plugin-Settings, which can be deactivated. Did you deactivate it there too?

**Comment by StarScream159** [comment]
Oh, I didn't know that setting was there. Disabling the plugin has seemed to stop that error.

**Comment by vuolter** [comment]
Wait, I want know why happens. :D

**Comment by Kap0** [comment]
What's the status?
