### ISSUE TITLE
Use own cookies for downloading with pyload

### ISSUE THREAD

**Issue by Rokhsana** [pyload/pyload#1151]
I have exports my firefox cookies in .sqlite & .txt . Is it possible to use them for downloading in pyload ?
How can I do that ? please explain in full details , I am a beginner .
for example , I want to download a url with my exported firefox cookies.txt in pyload . 

Thank you.

**Comment by vuolter** [comment]
Nope. You have to manually enter your account credentials in webui -> config -> accounts to use them with pyload.
