### ISSUE TITLE
Error importing LinksnappyCom

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#1153]
Hey. Having problems adding linksnappy as a hoster.

"Error importing LinksnappyCom: invalid syntax (LinksnappyCom.py, line 47)"

**Comment by stickell** [comment]
There are no syntax errors in Linksnappy.

Are you just using the plugins provided by the update manager or you have manually copied something?

**Comment by snickers2k** [comment]
i'm cloning from stable :/ and did not change anything
