### ISSUE TITLE
strange errors

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1155]
Sometimes i get these error on logs:

07.02.2015 13:02:20	ERROR	pycurl error 0: ('cannot invoke setopt() - perform() is currently running',)
07.02.2015 13:02:21	INFO	UnSkipOnFail: Looking for skipped duplicates of: Nightmare.3.I.Guerrieri.Del.Sogno.VU.part10.rar (pid:44)
07.02.2015 13:02:21	INFO	UnSkipOnFail: No duplicates found
07.02.2015 13:02:25	ERROR	pycurl error 23: Failed writing body (0 != 2440)
07.02.2015 13:02:25	INFO	UnSkipOnFail: Looking for skipped duplicates of: Nightmare.3.I.Guerrieri.Del.Sogno.VU.part10.rar (pid:44)
07.02.2015 13:02:25	INFO	UnSkipOnFail: No duplicates found
07.02.2015 13:02:31	WARNING	Download failed: Nightmare.3.I.Guerrieri.Del.Sogno.VU.part08.rar | [Errno 2] No such file or directory: u'Downloads/Nightmare 3/Nightmare.3.I.Guerrieri.Del.Sogno.VU.part08.rar.chunk0'
07.02.2015 13:02:31	INFO	UnSkipOnFail: Looking for skipped duplicates of: Nightmare.3.I.Guerrieri.Del.Sogno.VU.part08.rar (pid:44)
07.02.2015 13:02:31	INFO	UnSkipOnFail: No duplicates found

What does mean?
Every time i get these error, active downloads goes lower.I have to restart pyload for restore the number of active downloads

**Comment by stickell** [comment]
Where are you running pyLoad on?
This error occur always using a specific hoster or any?

**Comment by mobo95** [comment]
I'm running pyload on a nas: QNAP TS-251
I use only easybytez

**Comment by vuolter** [comment]
Direct link was not recognized. Did you use easybytez premium, right?
Sample url, please.

**Comment by mobo95** [comment]
Easybytez premium.
I've disabled UnSkipOnFail and I don't have anymore these errors.
Was happening on some resumed downloads

**Comment by vuolter** [comment]
If happens again (please retry with UnSkipOnFail set to ON), post here the content of the related debug.txt file. Thx.
