### ISSUE TITLE
ClickAndLoad.py plugin crashes on connecting to port 9666

### ISSUE THREAD

**Issue by hardez** [pyload/pyload#1158]
I've made a SSH-Tunnel from my laptop to my pyload station so I can use Click'n'Load but since maybe two or three weeks the ClickAndLoad.py plugin crashes either on startup with

```
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/opt/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/share/pyload_config/userplugins/hooks/ClickAndLoad.py", line 108, in server
    client_socket.close()
UnboundLocalError: local variable 'client_socket' referenced before assignment
```
or on connectiing to port 9666 with

```
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/opt/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/share/pyload_config/userplugins/hooks/ClickAndLoad.py", line 109, in server
    server_socket.close()
UnboundLocalError: local variable 'server_socket' referenced before assignment
```

**Comment by Mister-XY** [comment]
I think, there must be an error in script.
The port is open but click and load get no packet.
Click and load open the port 127.0.1.1:9666

**Comment by Mister-XY** [comment]
Also i have tested with clickandload and for me i have found, that click and load listen to 0.0.0.0:9666.
if i changed to 127.0.0.1:9666 click and load get no packet.
If i use netstat -tulpen, also i can see, that python also use the adress 0.0.0.0:7272. Is it possible, that python must use the same hostadress? In this example 0.0.0.0 ?

**Comment by wastez** [comment]
7227 is used for the remote and has nothing to do with clicknload.

To your 127.0.1.1 problem.
Have a look on your host file, i´m quite sure there will be a 127.0.1.1 entry for your host.

**Comment by Mister-XY** [comment]
You are right. I have an entry with 127.0.1.1 Thomas-NAS but. id did not get any click and load packet on 127.0.1.1 only with 0.0.0.0 i get the click and load packets.

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/e98807ebce1220afdac21e7dfabe04f7ee2acdcf
