### ISSUE TITLE
LinkdecrypterCom nonetype error 

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1170]
Hello, 

Found a new bug. 
11.02.2015 16:39:56 ERROR     LinkdecrypterCom: 'NoneType' object has no attribute 'group' | Waiting 1 minute and retry

Thanks

**Comment by vuolter** [comment]
What's the url it was trying to decrypt?

**Comment by wastez** [comment]
it´s appears directly on start from pyload, there is no url at this time.

This appears 3 times until pyload can be used.

**Comment by ohaucke** [comment]
> Quote from http://www.downforeveryoneorjustme.com/linkdecrypter.com
> It's not just you! http://linkdecrypter.com looks down from here.

**Comment by wastez** [comment]
It would be great if it could disabled default if the service is down.
Because i´m not able to disable this service cause the "storing changes problem" after restart.

**Comment by vuolter** [comment]
First path: https://github.com/pyload/pyload/commit/29dec4b608c8d2df3a4b963d17e652d20381b1b0
