### ISSUE TITLE
Multiple downloads stop working. Only a single download at a time works

### ISSUE THREAD

**Issue by daniel-cohen** [pyload/pyload#1171]
When pyload starts, everything is fine and multiple downloads work fine. But after a while (I have it running on a NAS) it stops doing multiple downloads and only does one single download at a time.
I always suspected it does that after some plugin updates, but I can't prove it.
DEBUG mode is enabled, but there's nothing in the logs.

If I restart pyload, multiple uploads work again.
This happens repeatedly and it's just a matter of time till it happen again (usually a day or two).

The following thread sounds familiar to what I am experiencing:
http://forum.pyload.org/viewtopic.php?f=7&t=258

See attached image to see what the queue looks like:
![image](https://cloud.githubusercontent.com/assets/7077710/6157936/a20c92dc-b299-11e4-958d-04bc2d24fd47.png)

Sys info:

Python: 2.6.7 (r267:88850, Mar 5 2012, 09:53:17) [GCC 4.2.1 20070719 [FreeBSD]]
OS: posix freebsd7 FreeBSD freenas.local 7.3-RELEASE-p7 FreeBSD 7.3-RELEASE-p7 #0: Sun Oct 9 05:13:39 JST 2011 aoyama@fbsd7.freenas.local:/usr/obj/freenas/usr/src/sys/FREENAS-i386 i386
pyLoad version: 0.4.9

**Comment by daniel-cohen** [comment]
OK, this is not the real-debrid plugin. It happens with the baseplugin as well.

**Comment by stickell** [comment]
Can you post your `pyload.conf`?

**Comment by daniel-cohen** [comment]
version: 1 
remote - "Remote":
        bool nolocalauth : "No authentication on local connections" = True
        bool activated : "Activated" = True
        int port : "Port" = 7227
        ip listenaddr : "Adress" = 0.0.0.0

log - "Log":
        int log_size : "Size in kb" = 100
        folder log_folder : "Folder" = Logs
        bool file_log : "File Log" = True
        int log_count : "Count" = 5
        bool log_rotate : "Log Rotate" = True

permission - "Permissions":
        str group : "Groupname" = staff
        bool change_dl : "Change Group and User of Downloads" = True
        bool change_file : "Change file mode of downloads" = True
        str user : "Username" = root
        str file : "Filemode for Downloads" = 0674
        bool change_group : "Change group of running process" = False
        str folder : "Folder Permission mode" = 0775
        bool change_user : "Change user of running process" = False

general - "General":
        en;de;fr;it;es;nl;sv;ru;pl;cs;sr;pt_BR language : "Language" = en
        folder download_folder : "Download Folder" = /mnt/disk1/downloads
        bool checksum : "Use Checksum" = False
        bool folder_per_package : "Create folder for each package" = True
        bool debug_mode : "Debug Mode" = True
        int min_free_space : "Min Free Space (MB)" = 200
        int renice : "CPU Priority" = 0

ssl - "SSL":
        file cert : "SSL Certificate" = ssl.crt
        bool activated : "Activated" = False
        file key : "SSL Key" = ssl.key

webinterface - "Webinterface":
        str template : "Template" = default
        bool activated : "Activated" = True
        str prefix : "Path Prefix" = 
        builtin;threaded;fastcgi;lightweight server : "Server" = builtin
        ip host : "IP" = xxx.xxx.xxx.xxx
        bool https : "Use HTTPS" = False
        int port : "Port" = 8000

proxy - "Proxy":
        str username : "Username" = None
        bool proxy : "Use Proxy" = False
        str address : "Address" = "localhost"
        password password : "Password" = None
        http;socks4;socks5 type : "Protocol" = http
        int port : "Port" = 7070

reconnect - "Reconnect":
        time endTime : "End" = 0:00
        bool activated : "Use Reconnect" = False
        str method : "Method" = ./reconnect.sh
        time startTime : "Start" = 0:00

download - "Download":
        int max_downloads : "Max Parallel Downloads" = 6
        bool limit_speed : "Limit Download Speed" = False
        str interface : "Download interface to bind (ip or Name)" = None
        bool skip_existing : "Skip already existing files" = False
        int max_speed : "Max Download Speed in kb/s" = -1
        bool ipv6 : "Allow IPv6" = False
        int chunks : "Max connections for one download" = 5

downloadTime - "Download Time":
        time start : "Start" = 0:00
        time end : "End" = 0:00

**Comment by Burnout5151** [comment]
Cannot repdroduce with baseplugin.
Can we close this issue?

**Comment by GammaC0de** [comment]
👍 This seems to been fixed already.
