### ISSUE TITLE
ExtractArchive - some improvements should be done

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1173]
1) ExtractArchive should delete also .rev files when extraction is finished
2) Should be implemented a function that check MD5SUM on all archives before do extraction (using .rev files). This for avoid CRC error during extraction.
3) Progress bar and the status of extraction should be implemented.

**Comment by immenz** [comment]
Progress bar/ status should be there after the last update

**Comment by mobo95** [comment]
I get only status: exctracting.
Progress bar stuck at 0%. Size of the archive should also be fixed, i get only the size of one part

**Comment by immenz** [comment]
Please be more precise: 
So you get status: extracting in Active Tab. What else are you expecting?
And if Progress bar stuck at 0%, did the extraction finish at least? 

I disagree that size of archive needs to be fixed. the status bar representing the output of the extractor in means of progress of all archives together. The displayed size of one archive is only cosmetic. I did not think that cosmetic issues needs fixing...

**Comment by mobo95** [comment]
The extraction finish well, I know that it's only a cosmetic issue, it's just an improvement
I remember that in older version there was also a progress bar with the size value extracted and percent value

**Comment by wastez** [comment]
On my system with actual plugins extracting status is shown (with progressbar and percent)

**Comment by immenz** [comment]
please provide a DEBUG Log and if possible example links

**Comment by mobo95** [comment]
On my system progressbar doesn't work also on archives not damaged.
I have a QNAP TS-251 with latest firmware.

I use easybytez premium, i don't think that this is the problem.
I'm using latest version of ExtractArchive:
31	12.02.2015 15:10:45	INFO	UpdateManager: New version of plugin: [hook] ExtractArchive (v1.26 -> v1.29)
37	12.02.2015 15:10:48	INFO	UpdateManager: New version of plugin: [internal] Extractor (v0.18 -> v0.20)
38	12.02.2015 15:10:49	INFO	UpdateManager: New version of plugin: [internal] SevenZip (v0.07 -> v0.08)
39	12.02.2015 15:10:49	INFO	UpdateManager: New version of plugin: [internal] UnRar (v1.10 -> v1.13)
40	12.02.2015 15:10:50	INFO	UpdateManager: New version of plugin: [internal] UnZip (v1.08 -> v1.09)


![progressbar2](https://cloud.githubusercontent.com/assets/10552743/6175610/a260b1d2-b2f8-11e4-9eb5-a38b3a5f28ce.PNG)

That's the DEBUG:
http://pastebin.com/Nj8Zj6FG

**Comment by immenz** [comment]
So in this run the file was extracted? Or was there an undetected CRC Error?

**Comment by mobo95** [comment]
In this extraction, file is extracted correctly, no errors

**Comment by immenz** [comment]
But I'm wondering, log says extracted file was not found

**Comment by mobo95** [comment]
I don't know why, as you see in the picture, the file is extracted.

![cattura](https://cloud.githubusercontent.com/assets/10552743/6176102/54fc71ac-b2fc-11e4-9b1d-12efd0447a24.PNG)

**Comment by wastez** [comment]
This is on my System, showing status without Problems. 
Which unrar version are you using?

**Comment by mobo95** [comment]
UNRAR 3.60 freeware

**Comment by immenz** [comment]
uh...well. Let's investigate this ancient version :D

**Comment by wastez** [comment]
I'm not sure if it is supported, just v4 and v5 i think.

Correct me if i'm wrong.

**Comment by immenz** [comment]
hm, couldn't find unrar v3.60. Only 3.90 for windows...

When you said 
>I remember that in older version there was also a progress bar with the size value extracted and percent value

was this on the same System (QNAP)

**Comment by mobo95** [comment]
No, was using a raspberrypi.

With this nas, unrar 3.60 was installed by default
I'll try to install newer version and let you know

**Comment by immenz** [comment]
That's what I thought. 

Guess this unrar version didn't output progress, or in another way. So pyload (Extractor Plugin) can't read it and display it.

**Comment by mobo95** [comment]
I've installed unrar 5.0.0 using ipkg, but on pyload i see always 3.60 version:
81	12.02.2015 21:43:16	INFO	ExtractArchive: Activated UnRar 3.60|SevenZip 9.04


On ssh i see this:
[/share/CACHEDEV1_DATA/.qpkg/pyload/opt/bin] # unrar

UNRAR 5.00 freeware      Copyright (c) 1993-2013 Alexander Roshal

**Comment by wastez** [comment]
Check which version is in this path: /usr/bin/unrar

**Comment by mobo95** [comment]
I don't have unrar in this dir

**Comment by immenz** [comment]
you have to add the folder where executable (or a symbolic link) is in your path variable

**Comment by mobo95** [comment]
i've found the old unrar, it's located on /usr/local/sbin/
new unrar version is located in: /opt/bin/

**Comment by wastez** [comment]
as immenz said it has to be your path variable.
You can check your paths if you enter env

**Comment by mobo95** [comment]
PATH=/opt/bin:/opt/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin

Priority it's on /opt/bin

**Comment by immenz** [comment]
Or simply replace link (or executable) unrar in /usr/local/sbin/ with symbolic link to /opt/bin/unrar
ln -s /opt/bin/unrar /usr/local/sbin/unrar

Don't think that PATH=.... lasts after restart

**Comment by mobo95** [comment]
i've renamed /usr/local/sbin/unrar to /usr/local/sbin/unrar_old

now latest version is correctly loaded:

143	12.02.2015 22:00:57	INFO	ExtractArchive: Activated UnRar 5.00|SevenZip 9.04

**Comment by immenz** [comment]
Is progress displayed correctly now?

**Comment by immenz** [comment]
So whats about repairing and checking MD5 etc.... I don't think unrar supports this. What I read on the internet is that rar can repair archives. But afaik rar is shareware, and not installed automaticly along with unrar. 

So I think we should kick repair options...

**Comment by zlep** [comment]
Hm, I did a complete new installation of pyload but I'm still getting 

No password found
Extract failed

on the most packages when using the password file. Does this only happen to me?

**Comment by vuolter** [comment]
@immenz The unrar plugin supports the rar shareware package that comes with archive repair feature.

**Comment by immenz** [comment]
but rar is only used when unrar command isn't found, and rc switch (or option) is only used by rar (but tried for unrar in unrar.py)

**Comment by mobo95** [comment]
@zlep I have the same problem.
Every time i restart pyload, i have to set manually Delete archive when successfully extracted to on

**Comment by wastez** [comment]
The storing problem is not just on ExtractArchive it's a generell bug on almost every Plugin.

**Comment by mobo95** [comment]
@immenz 
Choosing rar as first it's a good idea, but most NAS doesn't support this package

**Comment by immenz** [comment]
I will take a look into it. 
Shouldn't be a problem. In same way Plugin figure out if unrar is installed, it can figure out if rar is and decide which one to use.

**Comment by zlep** [comment]
Like I mentioned in the other (wrong) issue, password_file still does not work for me. If I put the password into the package it works. Otherwise I'm getting:

No password found
Extract failed

**Comment by immenz** [comment]
what's the name of your pw file and what's it in the settings?

**Comment by wastez** [comment]
@zlep maybe it uses the New default file name. archive_password.txt

Because storing isn't working anybody on Plugins.

**Comment by mobo95** [comment]
on my nas RAR is not available

**Comment by immenz** [comment]
So from your questions at the beginning of this issue only
>1) ExtractArchive should delete also .rev files when extraction is finished

is still open... But for you it is not possible to use repair function?!

**Comment by zlep** [comment]
@immenz I did a complete new installation of pyload so I guess everything should be named and placed correctly. My pw file is still called "unrar_passwords.txt" and it is placed in the pyload main folder.
Do I have to rename it?

**Comment by mobo95** [comment]
@immenz I can't find rar or unrar-nonfree packages on OPKG.
Maybe in future

**Comment by immenz** [comment]
@zlep as @wastez said, probably you experiencing the bug that plugin conf is not not saving changed config, therefore i would assume the name of the password file is always be reset to it's default, which is "archive_password.txt". 
So rename your file to this new default value and it should work. Location is right.

**Comment by zlep** [comment]
Thanks guys @immenz @wastez This worked.
Now the last problem is that it does not save the settings. "Delete archive when successfully extracted" is set back to OFF after restart. No plugin issue if I get it right? But will it be fixed?

**Comment by Ghoststage** [comment]
Hi zlep you can in the ExtractArchive.py this entry set to true

Original entry
entries( "delete ", " bool " , "Delete archive When Extracted
successfully ", False )

NEW entry
( "delete ", " bool " , "Delete archive When Extracted successfully ", True )

It works
Sorry 4 my englisch



2015-02-15 17:46 GMT+01:00 zlep <notifications@github.com>:

**Comment by wastez** [comment]
@Ghoststage 
This is just a workarround because it just changes the default setting.

This bug need to be fixed as soon as possible because it´s on almost all other plugins too.

**Comment by Ghoststage** [comment]
Ah ok as a small bridge to fix this is ok I think


2015-02-15 19:22 GMT+01:00 wastez <notifications@github.com>:

**Comment by namealwaysinuse** [comment]
workaround doesnt work anymore after the update =( now the "True" is changed to "permanent" or "trash" but if is change the "False" in the ExtractArchive.py pyload doesnt start anymore :D

**Comment by wastez** [comment]
The workaround is the same, just write permanent instead of false.

**Comment by namealwaysinuse** [comment]
In the new version there is no Code like the workaround just some:" delete when done

If i change this to permanent pyload ist starting. 

Von meinem iPhone gesendet
