### ISSUE TITLE
UnZip plugin broken

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1174]
I get this on latest update:

62	12.02.2015 15:11:12	ERROR	Error importing UnZip: 'tuple' object has no attribute 'major'
63	12.02.2015 15:11:12	WARNING	ExtractArchive: Could not activate: UnZip | 'NoneType' object has no attribute 'UnZip'

**Comment by immenz** [comment]
On which python version are you? On which system?

**Comment by mobo95** [comment]
Python 2.7.5

**Comment by immenz** [comment]
https://github.com/immenz/pyload/commit/4fb1da8725038ee2894e9fb47af4d58a8834993d will fix this

**Comment by immenz** [comment]
may I ask where you looked up your Python Version?

Is it a "package" you installed on your NAS System or did you look in the Info Tab in pyload? On my nas (synology) the pyload package comes with it's on python envrionment, witch is older than the pyload package I've installed through the NAS OS...

**Comment by mobo95** [comment]
I just used SSH and typed:
python -V


I've installed pyload using "App Center" on the NAS software, i think that pyload was installed automatically or was already installed by default

**Comment by immenz** [comment]
Just curious, what Version is displayed in your pyload GUI under Info Tab (right top corner)?

**Comment by mobo95** [comment]
Python:	2.5.5 (r255:77872, May 16 2010, 10:32:26) [GCC 4.2.1]

**Comment by immenz** [comment]
I Knew It :D
