### ISSUE TITLE
[NitroflareCom] Plugin not working

### ISSUE THREAD

**Issue by immenz** [pyload/pyload#1176]
12.02.2015 22:33:26 INFO      pyLoad is up and running
    12.02.2015 22:33:32 INFO      Download starts: xxx.pdf
    12.02.2015 22:33:32 DEBUG     NitroflareCom: Update file info...
    12.02.2015 22:33:32 DEBUG     NitroflareCom: Previous file info: {}
    12.02.2015 22:33:33 DEBUG     NitroflareCom: Current file info: {'status': 2, 'url': u'https://www.nitroflare.com/view/F3A32C63C2B7BE5/xxx.pdf', 'size': 24463278.08, 'name': u'xxx.pdf', 'pattern': {'S': u'23.33', 'U': u'MB', 'ID': u'F3A32C63C2B7BE5', 'N': u'xxx.pdf'}}
    12.02.2015 22:33:33 DEBUG     NitroflareCom: File name: xxx.pdf | File size: 24463278
    12.02.2015 22:33:33 DEBUG     NitroflareCom: File status: online
    12.02.2015 22:33:33 DEBUG     NitroflareCom: Update file info...
    12.02.2015 22:33:33 DEBUG     NitroflareCom: Previous file info: {'status': 2, 'url': u'https://www.nitroflare.com/view/F3A32C63C2B7BE5/xxx.pdf', 'size': 24463278.08, 'name': u'xxx.pdf', 'pattern': {'S': u'23.33', 'U': u'MB', 'ID': u'F3A32C63C2B7BE5', 'N': u'xxx.pdf'}}
    12.02.2015 22:33:33 DEBUG     NitroflareCom: Current file info: {'status': 2, 'name': u'xxx.pdf', 'url': u'https://www.nitroflare.com/view/F3A32C63C2B7BE5/xxx.pdf', 'pattern': {'S': u'23.33', 'U': u'MB', 'ID': u'F3A32C63C2B7BE5', 'N': u'xxx.pdf'}, 'size': 24463278.08}
    12.02.2015 22:33:33 DEBUG     NitroflareCom: File name: xxx.pdf | File size: 24463278
    12.02.2015 22:33:33 DEBUG     NitroflareCom: Update file info...
    12.02.2015 22:33:33 DEBUG     NitroflareCom: Previous file info: {'status': 2, 'name': u'xxx.pdf', 'url': u'https://www.nitroflare.com/view/F3A32C63C2B7BE5/xxx.pdf', 'pattern': {'S': u'23.33', 'U': u'MB', 'ID': u'F3A32C63C2B7BE5', 'N': u'xxx.pdf'}, 'size': 24463278.08}
    12.02.2015 22:33:33 DEBUG     NitroflareCom: Current file info: {'status': 2, 'name': u'xxx.pdf', 'url': u'https://www.nitroflare.com/view/F3A32C63C2B7BE5/xxx.pdf', 'pattern': {'S': u'23.33', 'U': u'MB', 'ID': u'F3A32C63C2B7BE5', 'N': u'xxx.pdf'}, 'size': 24463278.08}
    12.02.2015 22:33:33 DEBUG     NitroflareCom: File name: xxx.pdf | File size: 24463278
    12.02.2015 22:33:33 DEBUG     NitroflareCom: File status: online
    12.02.2015 22:33:33 DEBUG     NitroflareCom: Handled as free download
    12.02.2015 22:34:37 WARNING   Download failed: xxx.pdf | ReCaptcha html not found
    12.02.2015 22:34:37 INFO      UnSkipOnFail: Looking for skipped duplicates of: xxx.pdf (pid:17)
    12.02.2015 22:34:37 INFO      UnSkipOnFail: No duplicates found
    12.02.2015 22:34:37 DEBUG     All downloads processed
    12.02.2015 22:35:48 INFO      shutting down...

Did some diggin:
First, Nitroflare problem is that it seems not to use cookies. I tried to do the requests with parameter "cookie=True", but no effect. I let pyload output the response headers, and it only shows one. In Browser Console, there are 3 setCookie items in header, but only the last one is shown in pyload. Maybe here is the problem. But don't know how to solve it.

Furthermore, in Captchaservice.py, def _challenge_v1(self, key) is called from line 89: return getattr(self, "_challenge_v%s" % version)(key, html) --> different count of arguments. Must fail.

Sample File: http://www.nitroflare.com/view/186EE2DDDF0F997

**Comment by immenz** [comment]
Any tips? so I could continue to work on it myself

**Comment by zapp-brannigan** [comment]
The failure is raised by this function in CaptchaService.py:
```
    def challenge(self, key=None, html=None, version=None):
        if not key:
            if self.detect_key(html):
                key = self.key
            else:
                errmsg = _("ReCaptcha key not found")
                self.plugin.fail(errmsg)
                raise TypeError(errmsg)

        if version in (1, 2):
            return getattr(self, "_challenge_v%s" % version)(key)

        elif not html and hasattr(self.plugin, "html") and self.plugin.html:
            version = 2 if re.search(self.KEY_V2_PATTERN, self.plugin.html) else 1
            return self.challenge(key, self.plugin.html, version)

        else:
            errmsg = _("ReCaptcha html not found")
            self.plugin.fail(errmsg)
            raise TypeError(errmsg)
```
This means the webpage has no captcha related code inside. I think the hoster plugin is out-of-date.

**Comment by immenz** [comment]
I know it is out of date, and i know there is no captcha code on the page. Because there isn't any (html) code comic from request.
What i am trying to figure out is why. It isn't a problem with cookies, i guess.

**Comment by immenz** [comment]
problem in NitroFlare Plugin:
In def **handleFree(self, pyfile):**

        self.html = self.load("http://nitroflare.com/ajax/freeDownload.php", 
                              post={'method': "startTimer", 'fileId': self.info['pattern']['ID']})

the response coming from that call should be either 1 or "Free downloading is not possible. You have to wait xxx minutes to download your next file."
In windows cmdline curl it works, I'm getting: 

    C:\Users\Immenz>curl "http://www.nitroflare.com/ajax/freeDownload.php"  --data "method=startTimer&fileId=C5D457F2954A793"
    ´╗┐Free downloading is not possible. You have to wait 111 minutes to download your next file.

or correspondingly

    C:\Users\Immenz>curl "http://www.nitroflare.com/ajax/freeDownload.php"  --data "method=startTimer&fileId=C5D457F2954A793"
    ´╗┐1

in pyload I'm getting only the first 3 characters i guess. Because I can't print 'em (decoding issues) I'm printing the lenght of the response instead, and i'm getting 3. So where is the problem?

I'm aware that the response never can be the whole html file, but to know the waiting time would be a progress. Also the html is never needed I guess.

**Comment by zapp-brannigan** [comment]
Have you tried "decode=True" in self.load?

Am 14. Februar 2015 19:56:39 MEZ, schrieb immenz <notifications@github.com>:
>problem in NitroFlare Plugin:
>In def **handleFree(self, pyfile):**
>
>  self.html = self.load("http://nitroflare.com/ajax/freeDownload.php", 
>   post={'method': "startTimer", 'fileId': self.info['pattern']['ID']})
>
>the response coming from that call should be either 1 or "Free
>downloading is not possible. You have to wait xxx minutes to download
>your next file."
>In windows cmdline curl it works, I'm getting: 
>
>C:\Users\Immenz>curl "http://www.nitroflare.com/ajax/freeDownload.php" 
>--data "method=startTimer&fileId=C5D457F2954A793"
>´╗┐Free downloading is not possible. You have to wait 111 minutes to
>download your next file.
>
>or correspondingly
>
>C:\Users\Immenz>curl "http://www.nitroflare.com/ajax/freeDownload.php" 
>--data "method=startTimer&fileId=C5D457F2954A793"
>    ´╗┐1
>
>in pyload I'm getting only the first 3 characters i guess. Because I
>can't print 'em (decoding issues) I'm printing the lenght of the
>response instead, and i'm getting 3. So where is the problem?
>
>I'm aware that the response never can be the whole html file, but to
>know the waiting time would be a progress. Also the html is never
>needed I guess.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pyload/pyload/issues/1176#issuecomment-74387349

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by immenz** [comment]
Yes. Then the len(self.html) is 0...
