### ISSUE TITLE
ClicknLoad problems

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1178]
I have problems adding packages using ClicknLoad
When i click in ClicknLoad button for add links, i see this on pyload logs:

13.02.2015 20:18:40	INFO	Added package easybytez.com containing 63 links
13.02.2015 20:18:40	DEBUG	Run Info Fetching for EasybytezCom
13.02.2015 20:21:26	DEBUG	Finished Info Fetching for EasybytezCom

But i don't see any package on QUEUE

**Comment by vuolter** [comment]
All the links are added to collector.
