### ISSUE TITLE
[Updatemanager] Plugins do not update

### ISSUE THREAD

**Issue by zlep** [pyload/pyload#1181]
Update manager seems to be broken (at least for me).
Plugins do not update. E.g. ExtractArchive.py stays on "version 0.1" after a complete new installation despite it "updated all plugins".

158	14.02.2015 18:08:49	INFO	UpdateManager: No new pyLoad version available
159	14.02.2015 18:08:49	INFO	UpdateManager: No plugin updates available

![extract](https://cloud.githubusercontent.com/assets/10477541/6200362/f13ab3c0-b474-11e4-9574-33f70fe4ef8a.png)

**Comment by stickell** [comment]
Try manually installing the last update manager. Download this:
https://raw.githubusercontent.com/pyload/pyload/stable/module/plugins/hooks/UpdateManager.py
and save it in your `userplugins/hooks` folder replacing the existing one. Than start pyLoad and should work.

**Comment by zlep** [comment]
Does not work unfortunately.
I don't understand why it does not update or why it updated to an old version. Because after I installed pyload it updated all plugins.

**Comment by stickell** [comment]
But ExtractArchive is the only outdated or all the plugins are?

**Comment by zlep** [comment]
Actually it seems like all plugins are not updated. I just checked MergeFiles.py and it is also version 0.1.

**Comment by stickell** [comment]
So your `userplugins` folder is empty except for the manually placed update manager right?

**Comment by zlep** [comment]
These are the plugins which are in the /hooks folder
(.../pyload/module/plugins/hooks)
![plugins](https://cloud.githubusercontent.com/assets/10477541/6200681/789cd6a0-b483-11e4-9da2-ca1bc471ad82.png)

Should I delete them all?

**Comment by immenz** [comment]
userplugins folder is in pyload home folder, not in install folder

**Comment by stickell** [comment]
@immenz is right. That are the plugins included in the installation but the updated ones are saved in a folder called `userplugins` inside your `.pyload` config folder.

**Comment by zlep** [comment]
Ok, sorry, I didn't know that. Thx for clarifying. Issue can be closed. Sorry.
In the userplugins folder the ExtractArchive.py seems to be updated (1.29). Then I have actually this problem https://github.com/pyload/pyload/issues/1173#issuecomment-74374304
