### ISSUE TITLE
[real-debrid.com] pycurl error 23: Failed writing body (0 != 2896)

### ISSUE THREAD

**Issue by ischlag** [pyload/pyload#1183]
pycurl error 23: Failed writing body (0 != 2896)

**Comment by vuolter** [comment]
Please pick the affected url, convert it using the real-debrid website service and post here.

**Comment by ChuckSeven** [comment]
http://uploaded.net/file/cg055uza/BrokCi1080EXQUiSiTE.part01.rar
http://uploaded.net/file/0s2fjprl/BrokCi1080EXQUiSiTE.part02.rar
http://uploaded.net/file/leos9fi3/BrokCi1080EXQUiSiTE.part03.rar
http://uploaded.net/file/o7ce7vzz/BrokCi1080EXQUiSiTE.part04.rar
http://uploaded.net/file/2ayjrz6t/BrokCi1080EXQUiSiTE.part05.rar


http://a.rdb.so/d/PMQVBE3BP4JHK/BrokCi1080EXQUiSiTE.part01.rar 
http://c.rdb.so/d/MRYTL4ILFQYDI/BrokCi1080EXQUiSiTE.part02.rar 
http://b.rdb.so/d/MDBLU5OQL77RY/BrokCi1080EXQUiSiTE.part03.rar 
http://a.rdb.so/d/ROSNMG527LK2M/BrokCi1080EXQUiSiTE.part04.rar 
http://a.rdb.so/d/4ICXG6VJPXRGU/BrokCi1080EXQUiSiTE.part05.rar
