### ISSUE TITLE
ClicknLoad 

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1186]
ClicknLoad isn´t working since a few days.

The port is open but nothing happens if a link is transfered.

**Comment by GammaC0de** [comment]
Hello,
I had the same problem here.
I've managed to fix it by myself, here is a patch with the changes I have made.

```
--- ./ClickAndLoad.py.bad       2015-02-17 00:23:54.519996129 +0200
+++ ./ClickAndLoad.py   2015-02-17 00:18:13.000000000 +0200
@@ -29,11 +29,11 @@
     else:
         host, port = address
         err = None
-        for res in getaddrinfo(host, port, 0, SOCK_STREAM):
+        for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
             af, socktype, proto, canonname, sa = res
             sock = None
             try:
-                sock = socket(af, socktype, proto)
+                sock = socket.socket(af, socktype, proto)
                 if type(timeout) != object:
                     sock.settimeout(timeout)
                 if source_address:
@@ -85,6 +85,7 @@

     @threaded
     def proxy(self, ip, webport, cnlport):
+        self.logInfo("Proxy listening on %s:%s" % (ip , cnlport))
         self.manager.startThread(self._server, ip, webport, cnlport)
         lock = Lock()
         lock.acquire()
```

**Comment by wastez** [comment]
@vuolter 
Please change that external will take 0:0:0:0 by default.
Because some nas os (omv for example) has it´s hostname in the hosts file with 127.0.1.1.

**Comment by GammaC0de** [comment]
@wastez 
Have you tried my patch?
My nas (mybooklive) also has it´s hostname in the hosts file with 127.0.1.1
I also was suspecting that ClicknLoad listens on 127.0.1.1 but after adding the self.logInfo line as in my above patch, I could see in the log that in spite the hosts file, it does listen on the correct IP (192.168.x.x) and not 127.0.1.1
In my case every time i had sent a link to ClicknLoad, it got an exception about getaddrinfo is unknown and the above patch solved it


```
        self.logInfo("Proxy listening on %s:%s" % (ip , cnlport))
```

**Comment by wastez** [comment]
Yes i tried it but it didn´t work on my system.
So i changed the ip detection to:
ip      = "0.0.0.0" if self.getConfig("extern") else "127.0.0.1"

**Comment by hardez** [comment]
I'm also on a Mybook Live and your Path worked for me

**Comment by vuolter** [comment]
@GammaC0de Thanks! :smile:

**Comment by GammaC0de** [comment]
@vuolter  :smiley:
tested [ e98807e](https://github.com/pyload/pyload/commit/e98807ebce1220afdac21e7dfabe04f7ee2acdcf) and it works fine for me.

**Comment by Mister-XY** [comment]
New click n load, new error .
Anything must bew wrong with the Version 0.38. The Log says click an d load listen to 0.0.0.0:9666 but netstat -tulpen says not. In netstat -tulpen you did not see the 9666 port.
