### ISSUE TITLE
[Question] Crypter

### ISSUE THREAD

**Issue by immenz** [pyload/pyload#1188]
Is the behavior that crypter plugins only decrypt right before downloading in Queue by Intention? I think somewhere in the past it also decrypted in collector.
In this context, no download information is shown (name and size) for such links, only after decryption. Is there a trick or isn't it possible to set info before decryption?
Are there pending changes for next releases?

**Comment by vuolter** [comment]
Scheduled for 0.4.11 .

**Comment by immenz** [comment]
Was it possible in the past or am I hallucinating?

**Comment by vuolter** [comment]
How long before?

**Comment by immenz** [comment]
couple month? Maybe years.

**Comment by vuolter** [comment]
Some times ago some 0.4.10 changes have flowed into the stable branch and reverted after a while, maybe we're talking about that, but I'm not sure. :S
