### ISSUE TITLE
HundredEightyUploadCom incorrecly reports all links as offline

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1189]
Hello since recent, every 180upload.com link i send to pyload fails with 'offline' status.
After doing some digging, I found that the plugin got tricked to think that the link is offline.
This is because 180upload.com adds the below html code (invisible "File Not Found" string) which matches to XFSHoster's OFFLINE_PATTERN.

```
<div style="color: transparent;">
File Not Found 

<br>

</div
```

An example to a link that is actually offline (expired):
http://180upload.com/tmpdxareltz6

**Comment by stickell** [comment]
Should be fixed. If not please reopen.
Thanks for reporting
