### ISSUE TITLE
ZippyShare keeps changing its checksum

### ISSUE THREAD

**Issue by sebdelsol** [pyload/pyload#1191]
Based on what @gaberad suggested, I have Zippyshare working for at least the 4 last changes. 

Body's JS scripts are evaluated with all the DOM statements turned into regular variables initialized with their fetched values in the html.
```python
# get all the scripts inside the html body
tree = lxml.html.fromstring(self.html)
scripts = tree.xpath('//body//script[@type="text/javascript"]/text()')

# meant to be populated with the initialization of all the DOM elements found in the scripts
initScripts = []

def repl(element):
    id, attr = element.group(1), element.group(4)      # attr might be None

    varName = '%s_%s' %(id, attr)

    initValues = tree.xpath('//*[@id="%s"]/@%s' %(id, attr))
    initValue = '"%s"' %initValues[-1] if initValues else 'null'

    initScripts.append('var %s = %s;' %(varName, initValue))
    return varName

# handle all getElementById
reVar = r'document.getElementById\([\'"](\w+)[\'"]\)(\.)?(getAttribute\([\'"])?(\w+)?([\'"]\))?'
scripts = [re.sub(reVar, repl, script) for script in scripts]

# get the file's url by evaluating all the scripts
return  JSE_chainEval(initScripts + scripts + ['dlbutton_href'])
```

Some JS scripts are meant to fail at some point, hence  `JSE_chainEval()` needs to catch errors and resume the evaluation of all the remaining scripts with *the same JS context*:

```python
def JSE_chainEval(scripts):
    rt = PyV8.JSContext()
    rt.enter()

    for script in scripts:
        try:
            ret = rt.eval(script.encode('utf8') if isinstance(script, unicode) else script)
        except:
            pass

    return ret
```
EDIT : I don't know how to use xpath (or beautifulSoup) in a hoster. So I just assumed that lxml.html would be available in some way...

EDIT2: ZippyShare changed again! I had to handle some DOM introspection, eg. document.getElementById('omg').getAttribute('class')

**Comment by gaberad** [comment]
Thanks for the solution @sebdelsol.

FYI:
I don't have PyV8 installed and just wanted to get something working for now, so I changed JSE_chainEval to use self.js.eval. It works for me, but obviously doesn't have the error catching that the original does. Ended with this (relevant parts):
```
...
import lxml.html

class ZippyshareCom(SimpleHoster):
...
    def handleFree(self, pyfile):
        recaptcha   = ReCaptcha(self)
        captcha_key = recaptcha.detect_key()

        if captcha_key:
            try:
                self.link = re.search(self.LINK_PREMIUM_PATTERN, self.html)
                recaptcha.challenge()

            except Exception, e:
                self.error(e)

        else:
            #self.link = '/'.join(("d", self.info['pattern']['KEY'], str(self.get_checksum()), self.pyfile.name))
            self.link = self.get_url()

    def get_url(self):
        try:
            # get all the scripts inside the html body
            tree = lxml.html.fromstring(self.html)
            scripts = tree.xpath('//body//script[@type="text/javascript"]/text()')

            # meant to be populated with the initialization of all the DOM elements found in the scripts
            initScripts = []

            def repl(element):
                id, attr = element.group(1), element.group(4)      # attr might be None
                varName = '%s_%s' %(id, attr)
                initValue = tree.xpath('//*[@id="%s"]/@%s' %(id, attr))
                initValue = '"%s"' %initValue[-1] if initValue else 'null'

                initScripts.append('var %s = %s;' %(varName, initValue))
                return varName

            # handle all getElementById
            reVar = r'document.getElementById\([\'"](\w+)[\'"]\)(\.)?(getAttribute\([\'"])?(\w+)?([\'"]\))?'
            scripts = [re.sub(reVar, repl, script) for script in scripts]

            # get the file's url by evaluating all the scripts
            result = self.JSE_chainEval(initScripts + scripts + ['dlbutton_href'])
                
        except Exception, e:
            self.error(_("Unable to get url"))

        else:
            return result
    
    def JSE_chainEval(self, scripts):
        script = '\n'.join(scripts)
        return self.js.eval(script.encode('utf8') if isinstance(script, unicode) else script)
...
```

**Comment by sebdelsol** [comment]
The current version of Zippyshare doesn't need JS script error catching. So it'll work for the moment.
Yet the version before had the checksum spread in 4 scripts, with the first one meant to fail halfway. 
I guess those kind of tricks could be used again.

**Comment by sebdelsol** [comment]
ZippyShare has changed again, no kidding. Now it seems to be done on a daily basis.
The good news is that this dynamic approach still works.

I guess the **plugin issue** label should be added though.

**Comment by sebdelsol** [comment]
Just to be on the safe side, it would be even better to get the DOM elements' init values only from html preceding the JS scripts, like that:
```python
initValue = tree.xpath('//body//script[@type="text/javascript"]//preceding::*[@id="%s"]/@%s' %(id, attr))
```
It would only work with `lxml.html` though - Python's standard `xml.etree.ElementTree` would not support that kind of funky xpath syntax.

**Comment by sebdelsol** [comment]
I've seen that beautifulSoup is present in module/lib. I would rather have lxml in the dependencies, since it's way faster and more standard. Yet that would work too:

```python
# get all the scripts inside the html body
soup = BeautifulSoup(self.html)
scripts = [s.getText() for s in soup.body.findAll('script', {'type':'text/javascript'})]

# meant to be populated with the initialization of all the DOM elements found in the scripts
initScripts = []

def repl(element):
    id, attr = element.group(1), element.group(4)      # attr might be None

    varName = '%s_%s' %(id, attr)
    initValue = (soup.find(id=id) or {}).get(attr, None)
    initValue = '"%s"' %initValue if initValue is not None else 'null'

    initScripts.append('var %s = %s;' %(varName, initValue))
    return varName

# handle all getElementById
reVar = r'document.getElementById\([\'"](\w+)[\'"]\)(\.)?(getAttribute\([\'"])?(\w+)?([\'"]\))?'
scripts = [re.sub(reVar, repl, script) for script in scripts]

# get the file's url by evaluating all the scripts
return  JSE_chainEval(initScripts + scripts + ['dlbutton_href'])
```

**Comment by stickell** [comment]
Yes that is a legacy support, we think they should be removed in future releases. Also it's an old version but if it achieve the goal at least there is no need to force users to install the dependence.

**Comment by sebdelsol** [comment]
oh yes lxml is way better ! I hope that you intend to add this dependency :)

**Comment by stickell** [comment]
No we will not, we can't add anything directly in 0.4.9 we should wait next release but we are willing to abandon this approach. Now we prefer making users install their own using PIP as they already have to do for other pyLoad core deps as pyCurl for example.

Use a `try` statement on the import to print a message on the console to inform users they have to install `lxml` if they want to use this plugin. This is not the first plugin that is using external deps and this approach should work quite well.

**Comment by sebdelsol** [comment]
This proposed version use the internal `Beatifulsoup`. When you decide to get rid of it, I think we should add a dependency to `lxml` as suggested by @stickell.

BTW, I've found a way to handle deliberate errors in the JS scripts without relying on PyV8 by adding JS `try/catch` statements around zippyshare scripts.

Sorry for the mess with the chain of pull requests.

**Comment by sebdelsol** [comment]
ZippyShare has change again, yet it's still working :)
