### ISSUE TITLE
No File/Folder names share-online/linkcrpyt

### ISSUE THREAD

**Issue by McGeifer** [pyload/pyload#1192]
I'm using a share-onilne premium account. After adding a new link with click 'n' load you can see the new folder with the name of the linkcrypt url in the collector. If you open the link on the webinterface of pyload you can see all the links with the share-online url as the file name. Even after waiting a long time or restarting/re-adding the link, pyload is not resolving the right file/folder names.

After starting the download, pyload is resolving the right filename for the files currently downloading. It's not a big problem because you can still download the files, but if some file is corrupted and you have to re-add the download link you have to download all files again. Pyload ist not recognizing the allready existing files, so it's verry annoying if you downloading big archives.

There are no errors in the log File as far as I can see. Same problem with dlc files.

18:42:21 INFO      UpdateManager: No plugin updates available
18:44:15 INFO      Added package http://linkcrypt.ws/dir/0pq79944o4hg4z4 containing 212 links
18:44:15 DEBUG     Redirected import module.plugins.hoster.ShareonlineBiz -> userplugins.hoster.ShareonlineBiz
18:44:15 DEBUG     Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
18:44:15 DEBUG     Run Info Fetching for ShareonlineBiz
18:44:56 DEBUG     Finished Info Fetching for ShareonlineBiz

If you need more logs, contact me...

**Comment by vuolter** [comment]
New day, new issue... alright. ;(

**Comment by McGeifer** [comment]
After testing around a bit everything works as is should be if I use Click'n'Load (not v2). Using the DLC file provided by the page which is also provides the Click'n'Load link will cause the cryptic file and folder names and the missing file size.

Maybe this will help a bit.
