### ISSUE TITLE
YoutubeCom converts the output file name to ascii

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1200]
Hello,
Is there any reason that YoutubeCom should convert the file name to ascii (`name = name.encode('ascii', 'replace')`?
Doing that when the file name contains non ascii characters result in file name like ___2__.mp4
If I comment that line, the file name is OK including the non ascii characters

``` python
        # Cleaning invalid characters from the file name
        name = name.encode('ascii', 'replace')
        for c in self.invalidChars:
            name = name.replace(c, '_')
```

**Comment by stickell** [comment]
Is there is. A lot of users had crashes without that.
See for example #287 #353 #656

In 0.4.10 maybe it will no longer necessary because the ability of the core to handle special chars has been improved.
