### ISSUE TITLE
Decrypting failed: xxx.rsdf | global name 'Key' is not defined

### ISSUE THREAD

**Issue by smindorf** [pyload/pyload#1204]
Hi,
I try to import a RSDF-Container and get the following error message:

```
Decrypting failed: xxx.rsdf | global name 'Key' is not defined
```

So I checked the Source and see:

```
IV  = AES.new(Key, AES.MODE_ECB).encrypt(binascii.unhexlify(self.IV))
```

I've changed **Key** to **KEY** and it work.

Please update your code.
Regards,
Soeren

**Comment by smindorf** [comment]
Sorry, it is **NOT** working. Only one file will be found.

Please check....

Regards,
Soeren

**Comment by vuolter** [comment]
Sample container url please.

**Comment by smindorf** [comment]
I've downloaded the container, and I tried to import.

Here is a Sample:

Inside the rsdf-file:

```
6f59654632532f656f793049464275437849303256557843304f6b4a674e4554.......e304638384e697832474f6864502f7a76513d3dda
```

**Comment by vuolter** [comment]
Sample rsdf-file is broken.

**Comment by smindorf** [comment]
Here is a new one which is not working:

6f59654632532f656f793049464275437849303256557843304f6b4a674e4554375276454a55745a445a62632f7071397451787052666f6b66646167365a383844644434662b684c7a632b444663705454574c3168766365676e6d745869436b7a6a76697931344c64673d3dda6c6d56385877507931364539765a2f4c616958612f344d71727a697959304b3735426f326c705a4f6a5651336f747435633879625278716d6b35573179715a4e6c4d33596a474e456e414f684b6a6b495433595957596968583063707258692f61732b74557a41386c513d3dda714e4f47354d3550594a4152322f4359513147583155517373686b50463754384463682b3245346a6e2b34697939745464496d44694b5064457a496863316e4458427053496f512f546b644b456a454f306d4943574e5733363274524c3538434a6676526f6b434766673d3dda70344b6a647a3770326d554679424855635970557754467652414d614a496c70456239397133577877566d386f7a335633626e707471576d4a4f77544549794c4f7a614c503141617976555337755a3474377148593971617950324f6738526767714f75524453476e673d3dda5358643441734c644533484d4649444a5658624b376b794f365165704635387768514632354e776758486e7a6e3457466769682f486a58352f745841795a78336c59494a6e744e4b6166754646567330456e7244795955796c5374583369593355637a515a49415657773d3dda384549656c5438787a66534d7174746f2b424d56616630453732627a7a422b4774596a724e66724754506a6152714c4f7a784c6b457a6b764b796b5757796c4e6e77747941537234467344684375646c464a736845764d6f59354852566f6f4257674671626c325744673d3dda5757596167372f4c4d455858374a53392b594d6568575a66665749365a7169444d654958774f34374875474a492b326b6a364a4f7575774f37434a674d736a572b532f472f5a414f6a50797431427572396b6b4f354a71705673776971564579716b632b4156475235513d3dda

**Comment by vuolter** [comment]
Try yourself: https://linkdecrypter.com/?ck

**Comment by vuolter** [comment]
Broken againm Try yourself: http://linkdecrypter.com/?ck
