### ISSUE TITLE
[Request] ExtractArchive - Delte Archive = True as default

### ISSUE THREAD

**Issue by zlep** [pyload/pyload#1207]
Just a request @immenz
Would it be possible to set "Delete archive when successfully extracted" on "True" as default? Right now I'm setting it as True by myself but after every update it's back on False. No big deal but it would be very helpful if it would be set on True by default. I guess most people use it that way.
Thanks

**Comment by immenz** [comment]
Yes, it would be possible. But I think this shouldn't be the default value, since it's erase data. 
The original authors of this plugin had have their reasons to set it to false, and it's not on me to decide whether it should be changed. Sorry.

**Comment by wastez** [comment]
I also think the same like immenz does.
Somebody has to look for the original issue which doesn´t allow to save changes on almost every plugin.

**Comment by nomad71** [comment]
Also it seems that it doesn't solve the problem, that this specific setting isn't set to "True" after a restart of pyLoad. As referenced here #1208. Also I tried to change it in the ExtractArchive.py myself and it didn't work for me as well.

You can try to change it, too. Just search for ExtractArchive.py in your pyload folder open it with a text-editor. Don't forget to restart pyLoad.

I agree. It shouldn't be the default. For the same Reasons @immenz already mentioned.

Btw, thank you for your work ExtractArchive, @immenz!!

**Comment by zlep** [comment]
That's the problem. It's always set to False when updated. It's annoying to get home and seeing thousand of parts not deleted. The problem is not that it's not deleted but in the past, if the parts have been deleted, it was the confirmation that everything went fine with extraction. Unfortunately today with the lot of bugs which can occur, you can't be sure that everything went ok. I always have to check all packages if everything is ok. That's a big issue.
Anyway, I will switch to jDownloader @NAS soon, so it's ok.

**Comment by wastez** [comment]
Hope the storing problem will be solved soon.
Could it be that there is a problem in Hook.py?

**Comment by nomad71** [comment]
This might be a cheesy workaround, but you could drop a script into scripts/package_finished with something like 
```Shell
#!/bin/sh

rm "$2/*.rar"
rm "$2/*.rev"
```

$2 is the path that pyLoad gives as argument and the " should make it work with whitespaces as well.
(didn't test it)

**Comment by immenz** [comment]
not package finished, that could cause only more problems (when archives deleted BEFORE extraction) Safer would be archive_extracted, package_extracted or all_archives_extracted

**Comment by nomad71** [comment]
I guess that would be the right way to do then :D

I thought packageFinished was the last to be executed ... is there a place to read more about that?

**Comment by immenz** [comment]
I don't know about a documentation of recent events, I've look them up in the code if I need that. But I think the names speak for it self.

Heres a list of events ExtractArchive is using (in order of their appearance

listening to
- packageDeleted
- packageFinished
- allDownloadsProcessed

dispatching:
- archive_extracted
- archive_extract_failed
- package_extracted
- package_extract_failed
- all_archives_extracted
- all_archives_processed

**Comment by nomad71** [comment]
Thank you for your Elaboration! That gave me some insight into pyLoad I didn't have before!

As I already said ... its a cheesy workaround and in no way replaces an actual bugfix ;)

**Comment by wastez** [comment]
Yes this is a workarround for deleting the archives but it would be great if somebody has a look on the main problem because extractarchive is not the only Plugin where it happened. 
This was the reason who i opened a own issue for the main problem.

**Comment by zlep** [comment]
As far as I know this issue can't be fixed in 0.4.9.
At least that what I read.

**Comment by wastez** [comment]
@zlep 
why do you think that can´t be fixed?

**Comment by zlep** [comment]
@vuolter said it can't be fixed in 0.4.9 AFAIK

**Comment by stickell** [comment]
@zlep is right, the update manager can update only plugins and this looks like a core bug. In this case the fix can't be distributed until 0.4.10. However users would be able to patch their 0.4.9 manually.
