### ISSUE TITLE
ExtractArchive - extraction status stuck at "finalizing"

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1210]
On latest version of ExtractArchive (1.31), after extraction finished, threads of extraction stuck at "finalizing" status

![finalizing](https://cloud.githubusercontent.com/assets/10552743/6353991/ee2e63b8-bc4c-11e4-9bef-97effedf61d5.PNG)

I can't delete these extraction threads with X button because nothing happens.

I can't also restart pyload because stuck at this status:

947	24.02.2015 17:48:00	INFO	restarting pyLoad
948	24.02.2015 17:48:00	INFO	shutting down...

**Comment by immenz** [comment]
This is not just since last update. The links are all in one package, right?

Since ExtractArchive extracts only whole packages, this is normal behavior. We could only adjust the status "finalizing" to "extracted", but they will stay in list til all links in package are extracted.

**Comment by mobo95** [comment]
"finalizing" or "extracted" status is a good idea.
But the bug is that i can't restart pyload and if I press "Delete" button nothing happens

**Comment by immenz** [comment]
You mean the 4 entries are all there are, there are no more active extractions going on?

**Comment by mobo95** [comment]
There aren't active extractions, all extractions are completed and the current status of these is "finalized".

**Comment by immenz** [comment]
Closed? 

The problem not necessarily have to do with extractarchive. I've got an custom plugin as well which sometime hangs pyload due to some network issues. 

Without any debug logs I can't tell where the error is, if it's occur again (reproducible).
