### ISSUE TITLE
Zippyshare.com

### ISSUE THREAD

**Issue by duffel90** [pyload/pyload#1211]
Download skipped: file.html due to ZippyshareCom

**Comment by sebdelsol** [comment]
weird, it works for me. Could you please give the log and a link ?

**Comment by vuolter** [comment]
@duffel90 Sample url please. For now disable SkipRev.

**Comment by sebdelsol** [comment]
mmm, it works for me. I can't find a way to reproduce it. It could be a dead link or a an outdated plugin.

**Comment by sebdelsol** [comment]
There's something quite weird happening when `js.engine` is `'js'` on Linux. 
It happens consistently on some guys' NAS.

I don't have a linux box though, so I've asked on the forum to test with a plugin where I've added some logged stuff:
> Script Found----
>
> var a = 104815;
> var b = 742589;
> dlbutton_omg = "f";
> if (dlbutton_omg != 'f') {
> a = Math.ceil(a/3);
> } else {
> a = Math.floor(a/3);
> }
> dlbutton_href = "/d/n6nlJ24Z/"+(a + 104815%b)+"/lorem.zip";
> if (fimage_None) {
> fimage_href = "/i/n6nlJ24Z/"+(a + 104815%b)+"/lorem.zip";
> }
>
> JSE is js
> HREF is /d/n6nlJ24Z/104815/lorem.zip

The js script is evaluated as if either `a` or `math.ceil(a/3)` was 0... that makes no sense...

**Comment by sebdelsol** [comment]
Zippyshare has changed again. There's not `math` function call anymore, so it seems to be working again. Yet I'm quite confident that the `js` engine is buggy.

**Comment by sebdelsol** [comment]
Zippyshare uses  a math function again in its javascript ans it breaks the plugin. 
I can't debug that since my js engine works fine. 
Please investigate quickly before zippyshare changes its script as they do it twice a week in average.

**Comment by duffel90** [comment]
file.html is fixed with Zippyshare Version 0.78
