### ISSUE TITLE
Web Server Problems

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1214]
Ok on almost every server is a issue:
BuiltIn: Is working but after 1 - 2 days it crashes totaly
Threaded: 
Everything is working fine execept downloading a file from downloads. If this happens the file speed is about 64 - 128 kbit. (on builtin this is working) CPU is on 100%.
Fastcgi: Fastcgi doesn´t bind a port.

**Comment by lhw365** [comment]
in this case use a supervisor program to supervise the pyload process.Like daemontools or supervisor or systemd.

**Comment by wastez** [comment]
In which Case? There are 3 different options.

**Comment by lhw365** [comment]
Mine is with lightweight and supervising with daemontools,serving the download directory with apache or other webserver.

**Comment by GammaC0de** [comment]
Now currently known issues with the web servers.
