### ISSUE TITLE
SkipRev should skip rev for every archive and not for every package

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1217]
When a package contains more than one archive, SkipRev is applied considering .rev file as unique archive. This should be fixed.
SkipRev should be applied for every archive and not for every package

**Comment by vuolter** [comment]
Why a pack should have more than one archive parts, we have packages just for that! (it's not true after all XD).

**Comment by mobo95** [comment]
Imagine downloading a TV series with more than one episode and so more than one archive...

**Comment by immenz** [comment]
@vuolter problem is you can split packages that are coming as is, for example click'n'load or a container file

**Comment by vuolter** [comment]
Okay.

**Comment by mobo95** [comment]
On latest version I get this:
525	06.03.2015 17:54:44	INFO	Download starts: Dexter.-Stagione 05.-Episodio 01.Colpa.Mia.1080p.Bluray.Ac3.ITA.ENG.part01.rev
526	06.03.2015 17:54:45	WARNING	Download failed: Dexter.-Stagione 05.-Episodio 01.Colpa.Mia.1080p.Bluray.Ac3.ITA.ENG.part01.rev | global name 're' is not defined
