### ISSUE TITLE
[Extractor] Broken since one of the latest commits

### ISSUE THREAD

**Issue by mbosner** [pyload/pyload#1219]
@vuolter did you break it, again? ;)

Currently i cannot extract any archives. Could that be somehow connected to 3a9c167ceca27d57dbef927626fe853a3d0e30b2 ?

I am getting:

```
02.03.2015 16:44:16 INFO      Package finished: pdownload
02.03.2015 16:44:16 INFO      ExtractArchive: Check package: pdownload
02.03.2015 16:44:17 INFO      ExtractArchive: pdownload.part01.rar | Extract to: /data/Downloads/pdownload/
02.03.2015 16:44:17 ERROR     ExtractArchive: pdownload.part01.rar | Archive error | Cannot open '/data/Downloads/pdownload/pdownload.part01.rar'
```

/data/Downloads/pdownload/pdownload.part01.rar is in place and all rights are fine.

**Comment by DKeppi** [comment]
I have the same issue since Monday! :(

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/8b432eb80715f84800febb88620d943211e28051

**Comment by mbosner** [comment]
Thank you!
