### ISSUE TITLE
Again ClicknLoad

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1220]
Clicknload v0.38 ist not working again. 
The port is bound on pyload start but crashes after adding an Link.

**Comment by GammaC0de** [comment]
Below patch solves this issue.
But now, when I send a link to ClickAndLoad, I get another error: `error: (107, 'Transport endpoint is not connected')` on line 19 (`source.shutdown(socket.SHUT_RD)`)
The download starts normally though.
Is  this the desired behavior? 

```patch
--- ./ClickAndLoad.py   2015-03-03 23:33:52.701259383 +0200
+++ ./ClickAndLoad.py.bad       2015-03-03 23:37:42.569260839 +0200
@@ -72,7 +72,7 @@

             while True:
                 client_socket, client_addr = dock_socket.accept()
-                self.logDebug("Connection from: %s" % client_addr[0])
+                self.logDebug("Connection from: %s" % client_addr)

                 server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                 server_socket.connect(("127.0.0.1", webport))
```
