### ISSUE TITLE
[uploaded.to] traffic reservation problems

### ISSUE THREAD

**Issue by nordic-style** [pyload/pyload#1222]
Problem:
i cannot use some of my "premium" traffic because uploaded tells me that it reserved that traffic for old download requests. If it is not used within 120 minutes they remove that reservation.

Example:
Lets assume i  want to download 200 GB and i have 300 GB  "premium" traffic left.

I add all the files to pyload (via DLC) and the download starts. After 100 GB i get this error message (pyload error):

```
failedParse error: Premium download link not found | Plugin may be out of date 170.00 MiBUploadedTo
```

After 120 minutes i can continue to use my traffic to download everything (200 GB traffic left, 100 GB to download. If it would be 120 GB downloads left i would run into the reservation problem once again).

Question:
Is pyload trying to dl a file for status information or something similar?

Is this a problem of uploaded.to ?

**Comment by Mister-XY** [comment]
Today, i have the same Problem, i have downloaded via pyload. and after a while, i get captchas. if i want to start the download manualy, i get this message.
i#M only downloades via pyload.
Your Download-, as well as your Hybrid-Traffic is completely exhausted, if you still want to download this file, you can purchase one of our Hybrid-Traffic products.
Information:

Overall traffic: 24,54 GB
Reserved traffic: 24,56 GB (will be released in 120 minutes)
