### ISSUE TITLE
problems with special characters

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1224]
When i try to download files that contains special characters (like 'è') i get this:

60	05.03.2015 14:04:15	INFO	Download starts: Dexter.-Stagione 02.-Episodio 09.La.Resistenza.è.Inutile.1080p.Bluray.Ac3.ITA.ENG.Sub.ITA-DDN.part02.rar
61	05.03.2015 14:04:23	WARNING	Download failed: Dexter.-Stagione 02.-Episodio 09.La.Resistenza.è.Inutile.1080p.Bluray.Ac3.ITA.ENG.Sub.ITA-DDN.part02.rar | 'ascii' codec can't encode character u'\xe8' in position 85: ordinal not in range(128)
62	05.03.2015 14:04:23	INFO	UnSkipOnFail: Looking for skipped duplicates of: Dexter.-Stagione 02.-Episodio 09.La.Resistenza.è.Inutile.1080p.Bluray.Ac3.ITA.ENG.Sub.ITA-DDN.part02.rar (pid:145)

I use easybytez

**Comment by mobo95** [comment]
Someone can do something about this?

**Comment by vuolter** [comment]
Already fixed in 0.4.10 .

**Comment by mobo95** [comment]
I'm using 0.4.9
It's not fixed

**Comment by vuolter** [comment]
__0.4.10__ ;)

**Comment by mobo95** [comment]
Any chance to get the fix in 0.4.9?

**Comment by mobo95** [comment]
pyload 0.4.10 can't be installed on NAS with proprietary OS.
So, any chance to get this problem fixed in 0.4.9?

**Comment by vuolter** [comment]
Retry now.
