### ISSUE TITLE
[Onefichier.com] Unable to connect to host

### ISSUE THREAD

**Issue by keno974** [pyload/pyload#1226]
Everytime i'm trying to dl a file on Onefichier.com it's doesn't work. Free or premuim none of them works.
I got this message everytime : 

> 848	05.03.2015 20:05:20	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
847	05.03.2015 20:04:50	INFO	Download starts: 88nnw8my5j
846	05.03.2015 20:03:50	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
845	05.03.2015 20:02:40	INFO	Download starts: https://1fichier.com/?88nnw8my5j
844	05.03.2015 20:01:40	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
843	05.03.2015 20:01:10	INFO	Download starts: https://1fichier.com/?88nnw8my5j
842	05.03.2015 20:00:10	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
841	05.03.2015 19:59:39	INFO	Download starts: https://1fichier.com/?88nnw8my5j
840	05.03.2015 19:58:39	WARNING	Info Fetching for OneFichierCom failed | (28, 'SSL connection timeout at 27393')
839	05.03.2015 19:58:39	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
838	05.03.2015 19:58:09	INFO	Download starts: https://1fichier.com/?88nnw8my5j

And sometime : 

> 923	05.03.2015 22:48:11	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
922	05.03.2015 22:48:10	WARNING	Info Fetching for OneFichierCom failed | (28, 'SSL connection timeout at 28423')
921	05.03.2015 22:47:41	INFO	Download starts: https://1fichier.com/?kzi463f8xp

I've clear my userplugins folder and restart pyload for update manager but the problem is still here.

Does that mean the plugin is out of date ???

thx

**Comment by vuolter** [comment]
Works for me. Retry disabling plugins or changing the pyload webserver to "threaded".

**Comment by djgreg13** [comment]
I have this same issue, try the trick but not resolved
