### ISSUE TITLE
[ExtractArchive] Recycle instead of Delete

### ISSUE THREAD

**Issue by vuolter** [pyload/pyload#1230]
Forum: http://forum.pyload.org/viewtopic.php?f=13&t=3943

**Comment by immenz** [comment]
Maybe that's helpful: https://github.com/hsoft/send2trash

**Comment by vicegold** [comment]
This broke extracting archives on Mac OSX. send2trash is installed but not working. Becuase of that months old bug of "pluginsettings not saved" bug in pyLoad the option get's activated after every download again. So i can't turn it off. 
```22166	13.04.2015 12:40:32	ERROR	ExtractArchive: test.part18.rar | Unknown error | global name 'send2trash' is not defined
22167	13.04.2015 12:40:32	ERROR	ExtractArchive: test.part18.rar | Extract failed```

**Comment by vuolter** [comment]
@vicegold Please open as new issue.
