### ISSUE TITLE
Unrar broken again?

### ISSUE THREAD

**Issue by DKeppi** [pyload/pyload#1234]
Since today unrar doesn't work again :(

WARNING	ExtractArchive: Could not activate: UnRar | global name 'Popen' is not defined

**Comment by immenz** [comment]
https://github.com/pyload/pyload/commit/3551cd44c7fad9cf5159d5920b6e8ec7aa3d1b9b ....

@vuolter Why is it a code cosmetic when importing whole package and not just the 2 needed attributes? 
And why only replacing a few occurences, did you automate it and missed the others?

**Comment by GammaC0de** [comment]
Now pyload will not start correctly nor successfully quit unless I disable ExtractArchive plugin

**Comment by vuolter** [comment]
Checking....

**Comment by vuolter** [comment]
@immenz Like PEP says is better to use `import` than `from` to reduce namespace pollution. No really performance loss anyway and I prefer it when there're more attributes to import.
