### ISSUE TITLE
PluginRedirect Fails

### ISSUE THREAD

**Issue by sraedler** [pyload/pyload#1235]
The Captcha module is not found anymore, maybe it is because of a redirect. The log shows many redirect and than this error:

09.03.2015 09:52:59 INFO      starte pyLoad 0.4.9
09.03.2015 09:52:59 INFO      Benutze Home-Verzeichnis: /opt/pyload/config
09.03.2015 09:52:59 DEBUG     Remote activated: False
09.03.2015 09:53:02 DEBUG     created index of plugins
09.03.2015 09:53:02 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
09.03.2015 09:53:02 DEBUG     Redirected import module.plugins.hooks.MergeFiles -> userplugins.hooks.MergeFiles
.
.
.
.
09.03.2015 09:53:11 ERROR     Error importing ShareonlineBiz: No module named captcha
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/captcha/ShareonlineBiz.py", line 20, in <module>
    from captcha import OCR
ImportError: No module named captcha

**Comment by vuolter** [comment]
Your plugin is out of date.
Please, try updating plugins or reinstalling pyload.
