### ISSUE TITLE
can't decrypt Uptobox links

### ISSUE THREAD

**Issue by waseb** [pyload/pyload#1240]
Hello, 
First thanks for your work.
Since about 3 months, i can't download uptobox links
Log is for example :
8	09.03.2015 17:29:01	INFO	Added package news containing 1 links 
9	09.03.2015 17:29:02	INFO	Decrypting starts: http://uptobox.com/xxxxxxxxxxxxx
and nothing happens exept a brief decrypting try on the main page. 
But no error, no downloading and no more message in the log ...

The links from other hosts works fine.

system nas: d-link 320
I already erase then re-install all, and plugins update are made at each rebooting. 
I wait for others users to post an issue about this but it seems i'm alone in this situation.

Thanks for help.

**Comment by vuolter** [comment]
Sample url please.

**Comment by waseb** [comment]
This one for example:
http://uptobox.com/bb94vg3yxjvl

**Comment by vuolter** [comment]
Disable LinkDecrypterCom (currently working on a fix).

**Comment by waseb** [comment]
Yes it's seems working (cause i have to wait  between downloads) link is waiting to to download.

Thanks a lot

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/f85e28e565a1e0a76e6271d0b0853d6d48b4a043

**Comment by waseb** [comment]
Works fine with these updates.
Thanks.
