### ISSUE TITLE
Netload.in

### ISSUE THREAD

**Issue by sztypa** [pyload/pyload#1249]
Plugin in version 0.4.9 doesn't work properly. No access to premium account. It's been an issue a while now. It's said to be problematic, because the plug-in is simple too old. Nedds to be rewrited then?
Cheers.

**Comment by vuolter** [comment]
Scheduled for the next week. u.u

**Comment by vuolter** [comment]
Account issue fixed by https://github.com/pyload/pyload/commit/cdf209de3858276d2f91e2fb006574ea874e669a

**Comment by sztypa** [comment]
Will check if it works on ARM based server tomorrow. Thank You.
