### ISSUE TITLE
Settings did not save

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#1251]
Hello, in some setting menues, the settings did not save. For example, i save in extractarchive, that "Test archive before extracting:" to on. After an restart of pyload, the setting is off.
If i delete *.nfo in "Don't extract the following files:", after an restart, the *.nfo is also there. In some menu i found this small bug, so that i must change is in Hook to save my settings, but after an update, this setting are also away.
or in update manager. if i change the "Automatically restart pyLoad when required:" to off, after an restart, is it on.

**Comment by stickell** [comment]
Duplicated of #1157
