### ISSUE TITLE
[Oboom.com] ReCaptcha html not found

### ISSUE THREAD

**Issue by seppi91** [pyload/pyload#1253]
Running pyload from vuolter's fork by source (master branch). When starting links hosted by oboom log is returning Download failed: 'ReCaptcha html not found'.

**Comment by vuolter** [comment]
My remote master is temporarily broken...

**Comment by Starkmann** [comment]
I also have this problem, but not only on master branch.
You marked the issue as invalid, so how to fix it?

If i use remotes/origin/stable i get incorrect filenames. I open an issue for that as well.

**Comment by Starkmann** [comment]
Ok there already was one  #1250
