### ISSUE TITLE
Ascii encoding errors with links with non ascii characters

### ISSUE THREAD

**Issue by johtso** [pyload/pyload#1256]
With a lot of downloads I'm getting failures of the type "'ascii' codec can't encode characters in position 72-73: ordinal not in range(128)"

At first I thought it was just Zippyshare, but I'm seeing it with rapidshare links too.

Let me know if there's a way to get the full traceback if that would help.

I'm running version **0.4.9**

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/issues/1233
