### ISSUE TITLE
Mega.co.nz folder decrypter plugin is down

### ISSUE THREAD

**Issue by vuolter** [pyload/pyload#1267]

**Comment by OliverLeitner** [comment]
i can confirm this:

114	17.04.2015 16:05:06	DEBUG	Redirected import module.plugins.hoster.MegaCoNz -> userplugins.hoster.MegaCoNz
115	17.04.2015 16:05:06	INFO	Download starts: somefile.avi.crypted
116	17.04.2015 16:05:06	DEBUG	UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
117	17.04.2015 16:05:06	DEBUG	MegaCoNz: ID: someid | Key: somekey | Type: public
118	17.04.2015 16:05:07	DEBUG	MegaCoNz: Api Response: [{"s":1592355821,"countrycode":"somehash","g":"https://userstorageid.userstorage.mega.co.nz/dl/somehash"}]
119	17.04.2015 16:05:07	DEBUG	MegaCoNz: Decrypted Attr: MEGA{"n":"file.avi"}
120	17.04.2015 16:05:22	DEBUG	Chunk 1 failed: (35, 'gnutls_handshake() failed: A TLS packet with unexpected length was received.')
121	17.04.2015 16:05:22	DEBUG	pycurl exception 35: gnutls_handshake() failed: A TLS packet with unexpected length was received.
122	17.04.2015 16:05:22	ERROR	pycurl error 35: gnutls_handshake() failed: A TLS packet with unexpected length was received.
123	17.04.2015 16:05:22	INFO	Debug Report written to debug_MegaCoNz_17-04-2015_16-05-22.zip
124	17.04.2015 16:05:22	INFO	UnSkipOnFail: Looking for skipped duplicates of: file.avi.crypted (pid:8)
125	17.04.2015 16:05:22	INFO	UnSkipOnFail: No duplicates found
126	17.04.2015 16:05:22	DEBUG	All downloads processed 

i tried:
compiling pycurl against openssl -> no go
setting ssl_cipher_list and ssl_verifypeer and ssl_verifyhost -> no go

sys specs:
xubuntu 64bit current.

**Comment by BasedMan** [comment]
I didn't find a replacement website, but maybe this could be useful? https://github.com/megous/megatools

**Comment by GammaC0de** [comment]
No current issues with Mega.co.nz folder plugin.
