### ISSUE TITLE
Cpu usage https links real debrid

### ISSUE THREAD

**Issue by tchoblond59** [pyload/pyload#1269]
Do you have a solution for cpu usage with real debrid.
Your fix for #1252 didn't work and pyload stop working when cpu usage is too heavy... 

If you need a premium account tell me.

Thanks.

**Comment by vuolter** [comment]
No solution for now. A premium account for some tests would really help me! :D

**Comment by Velociraptor85** [comment]
@tchoblond59 please update and check the issue, this will be closed and can be reopened if needed.
