### ISSUE TITLE
Download-Issue with Filer.net on Zyxel 310S NSA

### ISSUE THREAD

**Issue by TurgayTurk** [pyload/pyload#1270]
Ive pyLoad v0.4.9 running on a Zyxel 310S NSA (firmware V4.70(AALH.0)). Iam just able to download 1 or some times 2 files from a whole package. For the rest parts i get almost below Log messages;

677 20.03.2015 18:58:02 INFO FilerNet: Direct download link detected 
678 20.03.2015 18:58:02 WARNING FilerNet: Check result: Html file | Waiting 1 minute and retry
679 20.03.2015 18:59:02 INFO Download restarted: kwgg5ucsjzmx8nmf | Html file
680 20.03.2015 18:59:02 INFO Download starts: kwgg5ucsjzmx8nmf
681 20.03.2015 18:59:30 INFO FilerNet: Direct download link detected
682 20.03.2015 18:59:51 WARNING FilerNet: Check result: Html file | Waiting 1 minute and retry
683 20.03.2015 19:00:51 INFO Download restarted: kwgg5ucsjzmx8nmf | Html file
684 20.03.2015 19:00:51 INFO Download starts: kwgg5ucsjzmx8nmf
685 20.03.2015 19:01:31 INFO FilerNet: Direct download link detected
686 20.03.2015 19:01:32 WARNING FilerNet: Check result: Html file | Waiting 1 minute and retry

or

646 20.03.2015 18:57:26 INFO Download restarted: vesvr3jfrycwl8lv | Fallback to free download
647 20.03.2015 18:57:26 INFO Download starts: vesvr3jfrycwl8lv
648 20.03.2015 18:57:27 INFO Download restarted: vesvr3jfrycwl8lv | Fallback to free download
649 20.03.2015 18:57:27 INFO Download starts: vesvr3jfrycwl8lv
650 20.03.2015 18:57:29 INFO Download restarted: vesvr3jfrycwl8lv | Fallback to free download
651 20.03.2015 18:57:29 INFO Download starts: vesvr3jfrycwl8lv
652 20.03.2015 18:57:30 INFO Download restarted: vesvr3jfrycwl8lv | Fallback to free download
653 20.03.2015 18:57:30 INFO Download starts: vesvr3jfrycwl8lv
654 20.03.2015 18:57:33 INFO Download restarted: vesvr3jfrycwl8lv | Fallback to free download

Is there maybe any other plugin in conflict with filer.net which i should disable?

**Comment by Velociraptor85** [comment]
@GammaC0de this is probably fixed ? @TurgayTurk would you confirm?
