### ISSUE TITLE
Plugin FshareVN not work, please help me?

### ISSUE THREAD

**Issue by vinhpaint** [pyload/pyload#1273]
Plugin FshareVN not work because Web Fshare is changed, Please help me Update Plugin. account free, premium, folder added but not work.
I will send my account free and premium to build plugin.
link test: 
https://www.fshare.vn/file/TD4DQ1KJ1T
https://www.fshare.vn/folder/FLF1O32SIYXL

**Comment by bigdargon** [comment]
FshareVN & FshareVNFolder not working, plz update it!!!

**Comment by GammaC0de** [comment]
Fixed FshareVN plugin.
Password protected URL support was removed.
If you have a password protected URL, please provide one.

**Comment by bigdargon** [comment]
> ERROR	ACCOUNT FshareVn: Could not login user `myh*******` | Bad server response: 400 Bad Request
I updated to 0.30 but not login :(

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by bigdargon** [comment]
@GammaC0de I have sent a VIP account to your email. Many thanks for your updates for this plugins. This is a Fshare link with a password to check plugins
Link: https://www.fshare.vn/file/UXWHD468DW84 
Pass this link: test123

**Comment by GammaC0de** [comment]
user and password does not work on the site either: "Incorrect username or password."

**Comment by bigdargon** [comment]
@GammaC0de password working, plz try again! Plz type password not copy!

**Comment by GammaC0de** [comment]
OK, now it works.

**Comment by GammaC0de** [comment]
@bigdargon Password for https://www.fshare.vn/file/UXWHD468DW84 does not work..

**Comment by bigdargon** [comment]
@GammaC0de https://www.fshare.vn/file/UXWHD468DW84 Changed pass to 123456

**Comment by GammaC0de** [comment]
Tested and works with password protected URL.
