### ISSUE TITLE
ExternalScripts

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1275]
Hi there. 
there this known bug that some settings are not persistent.
So i wrote a little script with python to check and change lines in my plugin.conf.
It works perfectly fine so i thought i could drop it in pyload_start to check at the beginning.
but when i start pyLoad now - it gives me an error: 

```
21.03.2015 20:46:06 INFO      ExternalScripts: Installed scripts for: pyload_start | check2.py
21.03.2015 20:46:06 DEBUG     ExternalScripts: Executing: /root/.pyload/scripts/pyload_start/check2.py | Args:
21.03.2015 20:46:06 ERROR     ExternalScripts: Runtime error: /root/.pyload/scripts/pyload_start/check2.py | [Errno 8] Exec format error
```

so i added "#!/usr/bin/env python"  - error is gone but script doesnt do anything.

Som1 can help ?
(the file is executable (chmod +x *.py))

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/master/config_checker.py
^^heres the script

**Comment by vuolter** [comment]
Wrong shebang: replace with `#!/usr/bin/env python` with `#!/bin/sh`.

**Comment by vuolter** [comment]
Okay... that's absolutely not a shell script... XD
