### ISSUE TITLE
What is the correct path encoding behaviour?

### ISSUE THREAD

**Issue by johtso** [pyload/pyload#1277]
I've just spent ages wrestling with my freenas jail installation, trying to apply a sane UTF-8 locale, and still haven't managed to get it to apply to the pyload daemon. This means that I get `UnicodeEncodeError`s with any files that contain unicode characters, thrown when pyload checks to see if the file already exists. https://github.com/pyload/pyload/blob/stable/module/network/HTTPChunk.py#L81

I had a look through the source code and I see that on systems that have an `ANSI` encoding, the path is forced to UTF-8. What is the reasoning behind just doing this for those systems? https://github.com/pyload/pyload/blob/stable/module/utils.py#L49

I finally had to hack that line of code to just always encode paths to UTF-8, and was wondering if there was any change to the behaviour that might make sense here. Either always encoding to UTF-8, or maybe having an option in the config that forces encoding to UTF-8?

**Comment by Velociraptor85** [comment]
@vuolter @GammaC0de @johtso 
old please close the issue
