### ISSUE TITLE
strange duplicate in logs

### ISSUE THREAD

**Issue by akfedux** [pyload/pyload#1281]
hi,

![pyload](https://cloud.githubusercontent.com/assets/6263592/6780735/31d1a05a-d168-11e4-875e-72ac44c26b0c.PNG)

**Comment by nomad71** [comment]
Can confirm.

**Comment by akfedux** [comment]
![pyload2](https://cloud.githubusercontent.com/assets/6263592/6801748/0a0356cc-d22b-11e4-9501-68263a92e58b.png)

**Comment by Mister-XY** [comment]
Same error

**Comment by GammaC0de** [comment]
Somehow the update process gets called twice

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/b6dc723bf214e8680f7be29594581d3da5033b90
