### ISSUE TITLE
Excessive CPU usage with high speed  download

### ISSUE THREAD

**Issue by JeanMars** [pyload/pyload#1282]
Hi,
I am using pyload on a Synology NAS DS413J (not a big CPU).
However I have noted that when I download from uplea.com, I can make it at 10MB/s with a regular download using firefox to the NAS. CPU does not go above 50% (basically raid+smb processes).
When using pyload, CPU goes to 100% after some seconds and then download speed decreases to 5-6 MB/s. Python uses 90% CPU usage on file pyLoadCore.py.

Any way to improve this?
Thanks,
Jean

**Comment by vuolter** [comment]
Just testing the fix... :D

**Comment by vuolter** [comment]
Debug log please.

**Comment by JeanMars** [comment]
318	24.Hi vuolter,
so I enabled debug and restarted pyload, here is the log (test file to download about 1GB).
CPU at 100% during download, python eating 80-90% even when download speed falls to 4MB/s.

03.2015 19:16:45	INFO	restarting pyLoad
319	24.03.2015 19:16:45	INFO	shutting down...
320	24.03.2015 19:16:45	DEBUG	Deleting old pidfile /volume1/@appstore/pyload/var/run/pyload.pid
321	24.03.2015 19:16:46	INFO	Starting pyLoad 0.4.9
322	24.03.2015 19:16:46	INFO	Using home directory: /volume1/@appstore/pyload/var/config
323	24.03.2015 19:16:46	DEBUG	Remote activated: True
324	24.03.2015 19:16:49	DEBUG	created index of plugins
325	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.hooks.BypassCaptcha -> userplugins.hooks.BypassCaptcha
326	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
327	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.hooks.Checksum -> userplugins.hooks.Checksum
328	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
329	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
330	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
331	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
332	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.hooks.ImageTyperz -> userplugins.hooks.ImageTyperz
333	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
334	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
335	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
336	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.hooks.JdCaptcha -> userplugins.hooks.JdCaptcha
337	24.03.2015 19:16:50	DEBUG	Redirected import module.plugins.hooks.Captcha9Kw -> userplugins.hooks.Captcha9Kw
338	24.03.2015 19:16:50	INFO	Activated plugins: BypassCaptcha, Captcha9Kw, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, JdCaptcha, UnSkipOnFail, UpdateManager, XFileSharingPro
339	24.03.2015 19:16:50	INFO	Deactivate plugins: AlldebridCom, AndroidPhoneNotify, AntiVirus, CaptchaBrotherhood, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, ExpertDecoders, FastixRu, FreeWayMe, HotFolder, IRCInterface, JustPremium, LinkdecrypterCom, LinksnappyCom, MegaDebridEu, MergeFiles, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumTo, PremiumizeMe, PutdriveCom, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartFailed, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, SmoozedCom, UnrestrictLi, WindowsPhoneNotify, XMPPInterface, ZeveraCom
340	24.03.2015 19:16:50	INFO	Downloadtime: True
341	24.03.2015 19:16:50	INFO	Starting ThriftBackend: 0.0.0.0:7227
342	24.03.2015 19:16:50	INFO	Free space: 3.05 TiB
343	24.03.2015 19:16:51	INFO	Activating Accounts...
344	24.03.2015 19:16:52	DEBUG	Redirected import module.plugins.accounts.UptoboxCom -> userplugins.accounts.UptoboxCom
345	24.03.2015 19:16:52	DEBUG	Redirected import module.plugins.internal.XFSAccount -> userplugins.internal.XFSAccount
346	24.03.2015 19:16:52	INFO	Starting lightweight webserver (bjoern): 0.0.0.0:8000
347	24.03.2015 19:16:53	DEBUG	UptoboxCom: Get Account Info for *******
348	24.03.2015 19:16:53	DEBUG	UptoboxCom: VALID_UNTIL_PATTERN not found
349	24.03.2015 19:16:53	DEBUG	UptoboxCom: TRAFFIC_LEFT_PATTERN not found
350	24.03.2015 19:16:53	DEBUG	UptoboxCom: LEECH_TRAFFIC_PATTERN not found
351	24.03.2015 19:16:53	DEBUG	UptoboxCom: Account Info: {'premium': False, 'leechtraffic': None, 'validuntil': None, 'trafficleft': None}
352	24.03.2015 19:16:53	INFO	Activating Plugins...
353	24.03.2015 19:16:53	DEBUG	Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
354	24.03.2015 19:16:53	DEBUG	Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
355	24.03.2015 19:16:53	DEBUG	Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
356	24.03.2015 19:16:53	INFO	ExtractArchive: Activated UnRar 5.01|SevenZip 9.20|UnZip (python 2.7.2)
357	24.03.2015 19:16:54	INFO	XFileSharingPro: Handling any hoster I can!
358	24.03.2015 19:16:54	DEBUG	XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?P[\w\-.^_]{3,63}(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
359	24.03.2015 19:16:54	INFO	XFileSharingPro: Handling any crypter I can!
360	24.03.2015 19:16:54	DEBUG	XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?P[\w\-.^_]{3,63}(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:user|folder)s?/\w+
361	24.03.2015 19:16:54	INFO	pyLoad is up and running
362	24.03.2015 19:16:56	INFO	UpdateManager: No new pyLoad version available
363	24.03.2015 19:16:56	INFO	UpdateManager: No new pyLoad version available
364	24.03.2015 19:16:56	DEBUG	UpdateManager: Requested deletion of plugins: [('accounts', 'File4safeCom'), ('accounts', 'Keep2shareCc'), ('accounts', 'MegaDebrid'), ('accounts', 'MultiDebridCom'), ('accounts', 'NowVideoAt'), ('accounts', 'Premium4Me'), ('accounts', 'ShareRapidCom'), ('captcha', 'captcha'), ('container', 'DLC_25'), ('container', 'DLC_26'), ('container', 'DLC_27'), ('container', 'LinkList'), ('crypter', 'C1neonCom'), ('crypter', 'DailymotionBatch'), ('crypter', 'DownloadVimeoCom'), ('crypter', 'Go4Up'), ('crypter', 'HotfileFolderCom'), ('crypter', 'Movie2kTo'), ('crypter', 'ShareRapidComFolder'), ('crypter', 'YoutubeBatch'), ('hooks', 'Captcha9kw'), ('hooks', 'CaptchaTrader'), ('hooks', 'Ev0InFetcher'), ('hooks', 'MegaDebrid'), ('hooks', 'MultiDebridCom'), ('hooks', 'Premium4Me'), ('hooks', 'ReloadCc'), ('hooks', 'Vipleech4uCom'), ('hooks', 'WindowsPhoneToastNotify'), ('hoster', 'File4safeCom'), ('hoster', 'Keep2shareCC'), ('hoster', 'Keep2shareCc'), ('hoster', 'MegaDebrid'), ('hoster', 'MegaNz'), ('hoster', 'MultiDebridCom'), ('hoster', 'PandaPlaNet'), ('hoster', 'PandaPlanet'), ('hoster', 'Premium4Me'), ('hoster', 'PutlockerCom'), ('hoster', 'ReloadCc'), ('hoster', 'Share4webCom'), ('hoster', 'ShareRapidCom'), ('hoster', 'Vipleech4uCom'), ('internal', 'AbstractExtractor'), ('internal', 'XFSPAccount'), ('internal', 'XFSPCrypter'), ('internal', 'XFSPHoster')]
365	24.03.2015 19:16:56	DEBUG	UpdateManager: Requested deletion of plugins: [('accounts', 'File4safeCom'), ('accounts', 'Keep2shareCc'), ('accounts', 'MegaDebrid'), ('accounts', 'MultiDebridCom'), ('accounts', 'NowVideoAt'), ('accounts', 'Premium4Me'), ('accounts', 'ShareRapidCom'), ('captcha', 'captcha'), ('container', 'DLC_25'), ('container', 'DLC_26'), ('container', 'DLC_27'), ('container', 'LinkList'), ('crypter', 'C1neonCom'), ('crypter', 'DailymotionBatch'), ('crypter', 'DownloadVimeoCom'), ('crypter', 'Go4Up'), ('crypter', 'HotfileFolderCom'), ('crypter', 'Movie2kTo'), ('crypter', 'ShareRapidComFolder'), ('crypter', 'YoutubeBatch'), ('hooks', 'Captcha9kw'), ('hooks', 'CaptchaTrader'), ('hooks', 'Ev0InFetcher'), ('hooks', 'MegaDebrid'), ('hooks', 'MultiDebridCom'), ('hooks', 'Premium4Me'), ('hooks', 'ReloadCc'), ('hooks', 'Vipleech4uCom'), ('hooks', 'WindowsPhoneToastNotify'), ('hoster', 'File4safeCom'), ('hoster', 'Keep2shareCC'), ('hoster', 'Keep2shareCc'), ('hoster', 'MegaDebrid'), ('hoster', 'MegaNz'), ('hoster', 'MultiDebridCom'), ('hoster', 'PandaPlaNet'), ('hoster', 'PandaPlanet'), ('hoster', 'Premium4Me'), ('hoster', 'PutlockerCom'), ('hoster', 'ReloadCc'), ('hoster', 'Share4webCom'), ('hoster', 'ShareRapidCom'), ('hoster', 'Vipleech4uCom'), ('internal', 'AbstractExtractor'), ('internal', 'XFSPAccount'), ('internal', 'XFSPCrypter'), ('internal', 'XFSPHoster')]
366	24.03.2015 19:16:56	INFO	UpdateManager: No plugin updates available
367	24.03.2015 19:16:56	INFO	UpdateManager: No plugin updates available
368	24.03.2015 19:17:04	INFO	ClickAndLoad: Proxy listening on 127.0.0.1:9666
369	24.03.2015 19:18:53	INFO	Added package once containing 1 links
370	24.03.2015 19:18:53	DEBUG	Redirected import module.plugins.hoster.UpleaCom -> userplugins.hoster.UpleaCom
371	24.03.2015 19:18:53	DEBUG	Redirected import module.plugins.internal.XFSHoster -> userplugins.internal.XFSHoster
372	24.03.2015 19:18:53	DEBUG	Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
373	24.03.2015 19:18:53	DEBUG	Run Info Fetching for UpleaCom
374	24.03.2015 19:18:54	DEBUG	Finished Info Fetching for UpleaCom
375	24.03.2015 19:18:54	INFO	Download starts: download filename
376	24.03.2015 19:18:54	DEBUG	UpleaCom: Update file info...
377	24.03.2015 19:18:54	DEBUG	UpleaCom: Previous file info: {}
378	24.03.2015 19:18:55	DEBUG	UpleaCom: Current file info: {'status': 2, 'url': u'http://uplea.com/uplea link', 'size': 0, 'name': u'download filename', 'pattern': {'N': u'download filename'}}
379	24.03.2015 19:18:55	DEBUG	UpleaCom: File name: download filename | File size: Unknown
380	24.03.2015 19:18:55	DEBUG	UpleaCom: File status: online
381	24.03.2015 19:18:56	DEBUG	UpleaCom: Update file info...
382	24.03.2015 19:18:56	DEBUG	UpleaCom: Previous file info: {'status': 2, 'url': u'http://uplea.com/uplea link', 'size': 0, 'name': u'download filename', 'pattern': {'N': u'download filename'}}
383	24.03.2015 19:18:56	DEBUG	UpleaCom: Current file info: {'status': 2, 'name': u'download filename', 'url': u'http://uplea.com/uplea link', 'pattern': {'N': u'download filename'}, 'size': 0}
384	24.03.2015 19:18:56	DEBUG	UpleaCom: File name: download filename | File size: Unknown
385	24.03.2015 19:18:56	DEBUG	UpleaCom: Update file info...
386	24.03.2015 19:18:56	DEBUG	UpleaCom: Previous file info: {'status': 2, 'name': u'download filename', 'url': u'http://uplea.com/uplea link', 'pattern': {'N': u'download filename'}, 'size': 0}
387	24.03.2015 19:18:56	DEBUG	UpleaCom: Current file info: {'status': 2, 'name': u'download filename', 'url': u'http://uplea.com/uplea link', 'pattern': {'N': u'download filename'}, 'size': 0}
388	24.03.2015 19:18:56	DEBUG	UpleaCom: File name: download filename | File size: Unknown
389	24.03.2015 19:18:56	DEBUG	UpleaCom: File status: online
390	24.03.2015 19:18:56	DEBUG	UpleaCom: Handled as free download
391	24.03.2015 19:19:13	DEBUG	Content-Disposition: download filename
392	24.03.2015 19:22:47	INFO	Download finished: download filename
393	24.03.2015 19:22:47	DEBUG	Checksum: {'status': 2, 'url': u'http://uplea.com/uplea link', 'name': u'download filename', 'pattern': {'N': u'download filename'}}
394	24.03.2015 19:22:47	WARNING	Checksum: Unable to validate checksum for file: download filename
395	24.03.2015 19:22:47	INFO	Package finished: once
396	24.03.2015 19:22:47	DEBUG	ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
397	24.03.2015 19:22:47	DEBUG	All downloads processed
398	24.03.2015 19:22:47	DEBUG	All downloads finished
399	24.03.2015 19:22:47	INFO	ExtractArchive: Check package: once
400	24.03.2015 19:22:47	DEBUG	ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
401	24.03.2015 19:22:47	INFO	ExtractArchive: Check package: once
402	24.03.2015 19:22:47	INFO	ExtractArchive: No files found to extract
403	24.03.2015 19:22:47	INFO	ExtractArchive: No files found to extract 
395	24.03.2015 19:22:47	INFO	Package finished: once
396	24.03.2015 19:22:47	DEBUG	ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
397	24.03.2015 19:22:47	DEBUG	All downloads processed
398	24.03.2015 19:22:47	DEBUG	All downloads finished
399	24.03.2015 19:22:47	INFO	ExtractArchive: Check package: once
400	24.03.2015 19:22:47	DEBUG	ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
401	24.03.2015 19:22:47	INFO	ExtractArchive: Check package: once
402	24.03.2015 19:22:47	INFO	ExtractArchive: No files found to extract
403	24.03.2015 19:22:47	INFO	ExtractArchive: No files found to extract

**Comment by Gutz-Pilz** [comment]
u have openvpn running ?

**Comment by JeanMars** [comment]
Hi,

not on the NAS. I use one on the raspberry pi but it is not used during these tests.
BTW, top reports a 90% CPU usage on pyLoadCore.py; sure this is a plugin issue and not related to pyload itself?

**Comment by JeanMars** [comment]
Hi,

this is also the same downloading from youtube. My guess is that this is related to pyload, not uplea or other plugin.
