### ISSUE TITLE
Lots of plugins deactivated

### ISSUE THREAD

**Issue by alextime** [pyload/pyload#1283]
There are tons of plugins deactivated and requested deletion, pyload 0.4.9 on a Qnap Nas, why?

Heres the full log in debug mode

928	24.03.2015 17:10:33	ERROR	ClickAndLoad: (98, 'Address already in use')
927	24.03.2015 17:10:33	INFO	ClickAndLoad: Proxy listening on 127.0.0.1:9666
926	24.03.2015 17:10:29	INFO	UpdateManager: No plugin updates available
925	24.03.2015 17:10:29	DEBUG	UpdateManager: Requested deletion of plugins: [('accounts', 'File4safeCom'), ('accounts', 'Keep2shareCc'), ('accounts', 'MegaDebrid'), ('accounts', 'MultiDebridCom'), ('accounts', 'NowVideoAt'), ('accounts', 'Premium4Me'), ('accounts', 'ShareRapidCom'), ('captcha', 'captcha'), ('container', 'DLC_25'), ('container', 'DLC_26'), ('container', 'DLC_27'), ('container', 'LinkList'), ('crypter', 'C1neonCom'), ('crypter', 'DailymotionBatch'), ('crypter', 'DownloadVimeoCom'), ('crypter', 'Go4Up'), ('crypter', 'HotfileFolderCom'), ('crypter', 'Movie2kTo'), ('crypter', 'ShareRapidComFolder'), ('crypter', 'YoutubeBatch'), ('hooks', 'Captcha9kw'), ('hooks', 'CaptchaTrader'), ('hooks', 'Ev0InFetcher'), ('hooks', 'MegaDebrid'), ('hooks', 'MultiDebridCom'), ('hooks', 'Premium4Me'), ('hooks', 'ReloadCc'), ('hooks', 'Vipleech4uCom'), ('hooks', 'WindowsPhoneToastNotify'), ('hoster', 'File4safeCom'), ('hoster', 'Keep2shareCC'), ('hoster', 'Keep2shareCc'), ('hoster', 'MegaDebrid'), ('hoster', 'MegaNz'), ('hoster', 'MultiDebridCom'), ('hoster', 'PandaPlaNet'), ('hoster', 'PandaPlanet'), ('hoster', 'Premium4Me'), ('hoster', 'PutlockerCom'), ('hoster', 'ReloadCc'), ('hoster', 'Share4webCom'), ('hoster', 'ShareRapidCom'), ('hoster', 'Vipleech4uCom'), ('internal', 'AbstractExtractor'), ('internal', 'XFSPAccount'), ('internal', 'XFSPCrypter'), ('internal', 'XFSPHoster')]
924	24.03.2015 17:10:29	INFO	UpdateManager: No new pyLoad version available
923	24.03.2015 17:10:23	INFO	pyLoad is up and running
922	24.03.2015 17:10:23	DEBUG	XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?P[\w\-.^_]{3,63}(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:user|folder)s?/\w+
921	24.03.2015 17:10:23	INFO	XFileSharingPro: Handling any crypter I can!
920	24.03.2015 17:10:23	DEBUG	XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?P[\w\-.^_]{3,63}(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
919	24.03.2015 17:10:23	INFO	XFileSharingPro: Handling any hoster I can!
918	24.03.2015 17:10:23	DEBUG	UpdateManager: Invalid interval value, kept current
917	24.03.2015 17:10:23	INFO	ExtractArchive: Activated UnRar 3.92
916	24.03.2015 17:10:23	DEBUG	Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
915	24.03.2015 17:10:23	INFO	ExtractArchive: No SevenZip installed
914	24.03.2015 17:10:23	DEBUG	Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
913	24.03.2015 17:10:23	DEBUG	Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
912	24.03.2015 17:10:23	INFO	Activating Plugins...
911	24.03.2015 17:10:23	INFO	Activating Accounts...
910	24.03.2015 17:10:23	ERROR	Remote backend error: (98, 'Address already in use')
909	24.03.2015 17:10:23	INFO	Free space: 619.78 GiB
908	24.03.2015 17:10:23	INFO	Starting builtin webserver: 0.0.0.0:8100
907	24.03.2015 17:10:23	INFO	Starting ThriftBackend: 0.0.0.0:7227
906	24.03.2015 17:10:23	INFO	Downloadtime: True
905	24.03.2015 17:10:23	INFO	Deactivate plugins: AlldebridCom, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, ExpertDecoders, FastixRu, FreeWayMe, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterCom, LinksnappyCom, MegaDebridEu, MergeFiles, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumTo, PremiumizeMe, PutdriveCom, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartFailed, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, SmoozedCom, UnrestrictLi, WindowsPhoneNotify, XMPPInterface, ZeveraCom
904	24.03.2015 17:10:23	INFO	Activated plugins: ClickAndLoad, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, XFileSharingPro
903	24.03.2015 17:10:23	DEBUG	Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
902	24.03.2015 17:10:23	DEBUG	Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
901	24.03.2015 17:10:23	DEBUG	Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
900	24.03.2015 17:10:23	DEBUG	Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
899	24.03.2015 17:10:23	DEBUG	Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
898	24.03.2015 17:10:23	DEBUG	Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
897	24.03.2015 17:10:23	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
896	24.03.2015 17:10:23	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
895	24.03.2015 17:10:23	DEBUG	created index of plugins
894	24.03.2015 17:10:21	DEBUG	Remote activated: True
893	24.03.2015 17:10:21	INFO	Using home directory: /share/MD1_DATA/.qpkg/pyload/data
892	24.03.2015 17:10:21	INFO	Starting pyLoad 0.4.9
891	24.03.2015 17:10:05	INFO	Received Quit signal
890	24.03.2015 17:10:05	DEBUG	Deleting old pidfile pyload.pid
889	24.03.2015 17:10:05	INFO	shutting down...
888	24.03.2015 17:07:22	ERROR	ClickAndLoad: (98, 'Address already in use')
887	24.03.2015 17:03:22	ERROR	ClickAndLoad: (98, 'Address already in use')
886	24.03.2015 16:59:22	ERROR	ClickAndLoad: (98, 'Address already in use')
885	24.03.2015 16:55:22	ERROR	ClickAndLoad: (98, 'Address already in use')
884	24.03.2015 16:55:22	INFO	ClickAndLoad: Proxy listening on 127.0.0.1:9666
883	24.03.2015 16:55:16	INFO	UpdateManager: No plugin updates available
882	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [container] DLC_26
881	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [captcha] captcha
880	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [container] DLC_27
879	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [hooks] Ev0InFetcher
878	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [hooks] CaptchaTrader
877	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [container] DLC_25
876	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [container] LinkList
875	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [crypter] HotfileFolderCom
874	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [crypter] YoutubeBatch
873	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [hoster] ShareRapidCom
872	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [accounts] ShareRapidCom
871	24.03.2015 16:55:16	INFO	UpdateManager: Removed blacklisted plugin: [internal] AbstractExtractor
870	24.03.2015 16:55:16	DEBUG	UpdateManager: Requested deletion of plugins: [('accounts', 'File4safeCom'), ('accounts', 'Keep2shareCc'), ('accounts', 'MegaDebrid'), ('accounts', 'MultiDebridCom'), ('accounts', 'NowVideoAt'), ('accounts', 'Premium4Me'), ('accounts', 'ShareRapidCom'), ('captcha', 'captcha'), ('container', 'DLC_25'), ('container', 'DLC_26'), ('container', 'DLC_27'), ('container', 'LinkList'), ('crypter', 'C1neonCom'), ('crypter', 'DailymotionBatch'), ('crypter', 'DownloadVimeoCom'), ('crypter', 'Go4Up'), ('crypter', 'HotfileFolderCom'), ('crypter', 'Movie2kTo'), ('crypter', 'ShareRapidComFolder'), ('crypter', 'YoutubeBatch'), ('hooks', 'Captcha9kw'), ('hooks', 'CaptchaTrader'), ('hooks', 'Ev0InFetcher'), ('hooks', 'MegaDebrid'), ('hooks', 'MultiDebridCom'), ('hooks', 'Premium4Me'), ('hooks', 'ReloadCc'), ('hooks', 'Vipleech4uCom'), ('hooks', 'WindowsPhoneToastNotify'), ('hoster', 'File4safeCom'), ('hoster', 'Keep2shareCC'), ('hoster', 'Keep2shareCc'), ('hoster', 'MegaDebrid'), ('hoster', 'MegaNz'), ('hoster', 'MultiDebridCom'), ('hoster', 'PandaPlaNet'), ('hoster', 'PandaPlanet'), ('hoster', 'Premium4Me'), ('hoster', 'PutlockerCom'), ('hoster', 'ReloadCc'), ('hoster', 'Share4webCom'), ('hoster', 'ShareRapidCom'), ('hoster', 'Vipleech4uCom'), ('internal', 'AbstractExtractor'), ('internal', 'XFSPAccount'), ('internal', 'XFSPCrypter'), ('internal', 'XFSPHoster')]
869	24.03.2015 16:55:16	INFO	UpdateManager: No new pyLoad version available
868	24.03.2015 16:55:12	INFO	pyLoad is up and running
867	24.03.2015 16:55:12	DEBUG	XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?P[\w\-.^_]{3,63}(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:user|folder)s?/\w+
866	24.03.2015 16:55:12	INFO	XFileSharingPro: Handling any crypter I can!
865	24.03.2015 16:55:12	DEBUG	XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?P[\w\-.^_]{3,63}(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
864	24.03.2015 16:55:12	INFO	XFileSharingPro: Handling any hoster I can!
863	24.03.2015 16:55:12	DEBUG	UpdateManager: Invalid interval value, kept current
862	24.03.2015 16:55:12	INFO	ExtractArchive: Activated UnRar 3.92
861	24.03.2015 16:55:12	DEBUG	Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
860	24.03.2015 16:55:12	INFO	ExtractArchive: No SevenZip installed
859	24.03.2015 16:55:12	DEBUG	Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
858	24.03.2015 16:55:12	DEBUG	Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
857	24.03.2015 16:55:12	INFO	Activating Plugins...
856	24.03.2015 16:55:12	INFO	Activating Accounts...
855	24.03.2015 16:55:12	ERROR	Remote backend error: (98, 'Address already in use')
854	24.03.2015 16:55:12	INFO	Starting builtin webserver: 0.0.0.0:8100
853	24.03.2015 16:55:11	INFO	Free space: 619.83 GiB
852	24.03.2015 16:55:11	INFO	Starting ThriftBackend: 0.0.0.0:7227
851	24.03.2015 16:55:11	INFO	Downloadtime: True
850	24.03.2015 16:55:11	INFO	Deactivate plugins: AlldebridCom, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, FastixRu, FreeWayMe, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterCom, LinksnappyCom, MegaDebridEu, MergeFiles, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumTo, PremiumizeMe, PutdriveCom, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartFailed, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, SmoozedCom, UnrestrictLi, WindowsPhoneNotify, XMPPInterface, ZeveraCom
849	24.03.2015 16:55:11	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, XFileSharingPro
848	24.03.2015 16:55:11	DEBUG	Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
847	24.03.2015 16:55:11	DEBUG	Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
846	24.03.2015 16:55:11	DEBUG	Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
845	24.03.2015 16:55:11	DEBUG	Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
844	24.03.2015 16:55:11	DEBUG	Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
843	24.03.2015 16:55:11	DEBUG	Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
842	24.03.2015 16:55:11	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
841	24.03.2015 16:55:11	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
840	24.03.2015 16:55:11	DEBUG	created index of plugins
839	24.03.2015 16:55:09	DEBUG	Remote activated: True
838	24.03.2015 16:55:09	INFO	Using home directory: /share/MD1_DATA/.qpkg/pyload/data
837	24.03.2015 16:55:09	INFO	Starting pyLoad 0.4.9
836	24.03.2015 16:54:54	INFO	Received Quit signal
835	24.03.2015 16:54:54	DEBUG	Deleting old pidfile pyload.pid
834	24.03.2015 16:54:54	INFO	shutting down...
833	24.03.2015 16:50:50	INFO	UpdateManager: *** Plugins have been updated, please restart pyLoad ***
832	24.03.2015 16:50:50	DEBUG	Request reload of plugins: [('accounts', 'AlldebridCom'), ('accounts', 'BackinNet'), ('accounts', 'BillionuploadsCom'), ('accounts', 'BitshareCom'), ('accounts', 'CatShareNet'), ('accounts', 'CloudzillaTo'), ('accounts', 'CramitIn'), ('accounts', 'CzshareCom'), ('accounts', 'DebridItaliaCom'), ('accounts', 'DepositfilesCom'), ('accounts', 'EasybytezCom'), ('accounts', 'EuroshareEu'), ('accounts', 'ExashareCom'), ('accounts', 'FastixRu'), ('accounts', 'FastshareCz'), ('accounts', 'File4SafeCom'), ('accounts', 'FileParadoxIn'), ('accounts', 'FilecloudIo'), ('accounts', 'FilefactoryCom'), ('accounts', 'FilejungleCom'), ('accounts', 'FileomCom'), ('accounts', 'FilerNet'), ('accounts', 'FilerioCom'), ('accounts', 'FilesMailRu'), ('accounts', 'FourSharedCom'), ('accounts', 'FreakshareCom'), ('accounts', 'FreeWayMe'), ('accounts', 'FshareVn'), ('accounts', 'HellshareCz'), ('accounts', 'HugefilesNet'), ('accounts', 'HundredEightyUploadCom'), ('accounts', 'JunkyvideoCom'), ('accounts', 'JunocloudMe'), ('accounts', 'Keep2ShareCc'), ('accounts', 'LetitbitNet'), ('accounts', 'LinestorageCom'), ('accounts', 'LinksnappyCom'), ('accounts', 'MegaRapidCz'), ('accounts', 'MegasharesCom'), ('accounts', 'MovReelCom'), ('accounts', 'MultihostersCom'), ('accounts', 'MultishareCz'), ('accounts', 'MyfastfileCom'), ('accounts', 'NetloadIn'), ('accounts', 'NoPremiumPl'), ('accounts', 'NosuploadCom'), ('accounts', 'NovafileCom'), ('accounts', 'NowVideoSx'), ('accounts', 'OboomCom'), ('accounts', 'OneFichierCom'), ('accounts', 'OverLoadMe'), ('accounts', 'PremiumTo'), ('accounts', 'PremiumizeMe'), ('accounts', 'PutdriveCom'), ('accounts', 'QuickshareCz'), ('accounts', 'RPNetBiz'), ('accounts', 'RapideoPl'), ('accounts', 'RapidfileshareNet'), ('accounts', 'RapidgatorNet'), ('accounts', 'RapiduNet'), ('accounts', 'RarefileNet'), ('accounts', 'RealdebridCom'), ('accounts', 'RehostTo'), ('accounts', 'RyushareCom'), ('accounts', 'SafesharingEu'), ('accounts', 'SecureUploadEu'), ('accounts', 'SendmywayCom'), ('accounts', 'ShareonlineBiz'), ('accounts', 'SimplyPremiumCom'), ('accounts', 'SimplydebridCom'), ('accounts', 'SmoozedCom'), ('accounts', 'StahnuTo'), ('accounts', 'StreamcloudEu'), ('accounts', 'TurbobitNet'), ('accounts', 'TusfilesNet'), ('accounts', 'UlozTo'), ('accounts', 'UnrestrictLi'), ('accounts', 'UploadableCh'), ('accounts', 'UploadcCom'), ('accounts', 'UploadedTo'), ('accounts', 'UploadheroCom'), ('accounts', 'UploadingCom'), ('accounts', 'UptoboxCom'), ('accounts', 'VidPlayNet'), ('accounts', 'WebshareCz'), ('accounts', 'XFileSharingPro'), ('accounts', 'YibaishiwuCom'), ('accounts', 'ZeveraCom'), ('container', 'CCF'), ('container', 'DLC'), ('container', 'RSDF'), ('container', 'TXT'), ('crypter', 'BitshareComFolder'), ('crypter', 'C1NeonCom'), ('crypter', 'CloudzillaToFolder'), ('crypter', 'DailymotionComFolder'), ('crypter', 'DataHuFolder'), ('crypter', 'DdlstorageComFolder'), ('crypter', 'Dereferer'), ('crypter', 'DevhostStFolder'), ('crypter', 'DlProtectCom'), ('crypter', 'DontKnowMe'), ('crypter', 'DuploadOrgFolder'), ('crypter', 'EasybytezComFolder'), ('crypter', 'FilecloudIoFolder'), ('crypter', 'FilecryptCc'), ('crypter', 'FilefactoryComFolder'), ('crypter', 'FilerNetFolder'), ('crypter', 'FilesonicComFolder'), ('crypter', 'FilestubeCom'), ('crypter', 'FiletramCom'), ('crypter', 'FiredriveComFolder'), ('crypter', 'FourChanOrg'), ('crypter', 'FreakhareComFolder'), ('crypter', 'Go4UpCom'), ('crypter', 'HotfileComFolder'), ('crypter', 'ImgurComAlbum'), ('crypter', 'LinkCryptWs'), ('crypter', 'LinkSaveIn'), ('crypter', 'LinkdecrypterCom'), ('crypter', 'MegaCoNzFolder'), ('crypter', 'MegaRapidCzFolder'), ('crypter', 'MegauploadComFolder'), ('crypter', 'Movie2KTo'), ('crypter', 'MultiUpOrg'), ('crypter', 'MultiuploadCom'), ('crypter', 'NCryptIn'), ('crypter', 'NetfolderIn'), ('crypter', 'NosvideoCom'), ('crypter', 'OneKhDe'), ('crypter', 'PastebinCom'), ('crypter', 'RelinkUs'), ('crypter', 'SafelinkingNet'), ('crypter', 'SexuriaCom'), ('crypter', 'ShareLinksBiz'), ('crypter', 'SharingmatrixComFolder'), ('crypter', 'StealthTo'), ('crypter', 'TnyCz'), ('crypter', 'TurbobitNetFolder'), ('crypter', 'TusfilesNetFolder'), ('crypter', 'UploadableChFolder'), ('crypter', 'UploadedToFolder'), ('crypter', 'WuploadComFolder'), ('crypter', 'XFileSharingProFolder'), ('crypter', 'YoutubeComFolder'), ('hooks', 'AlldebridCom'), ('hooks', 'AndroidPhoneNotify'), ('hooks', 'AntiVirus'), ('hooks', 'BypassCaptcha'), ('hooks', 'Captcha9Kw'), ('hooks', 'CaptchaBrotherhood'), ('hooks', 'Checksum'), ('hooks', 'ClickAndLoad'), ('hooks', 'DeathByCaptcha'), ('hooks', 'DebridItaliaCom'), ('hooks', 'DeleteFinished'), ('hooks', 'DownloadScheduler'), ('hooks', 'EasybytezCom'), ('hooks', 'ExpertDecoders'), ('hooks', 'ExternalScripts'), ('hooks', 'ExtractArchive'), ('hooks', 'FastixRu'), ('hooks', 'FreeWayMe'), ('hooks', 'HotFolder'), ('hooks', 'IRCInterface'), ('hooks', 'ImageTyperz'), ('hooks', 'JustPremium'), ('hooks', 'LinkdecrypterCom'), ('hooks', 'LinksnappyCom'), ('hooks', 'MegaDebridEu'), ('hooks', 'MergeFiles'), ('hooks', 'MultiHome'), ('hooks', 'MultihostersCom'), ('hooks', 'MultishareCz'), ('hooks', 'MyfastfileCom'), ('hooks', 'NoPremiumPl'), ('hooks', 'OverLoadMe'), ('hooks', 'PremiumTo'), ('hooks', 'PremiumizeMe'), ('hooks', 'PutdriveCom'), ('hooks', 'RPNetBiz'), ('hooks', 'RapideoPl'), ('hooks', 'RealdebridCom'), ('hooks', 'RehostTo'), ('hooks', 'RestartFailed'), ('hooks', 'RestartSlow'), ('hooks', 'SimplyPremiumCom'), ('hooks', 'SimplydebridCom'), ('hooks', 'SkipRev'), ('hooks', 'SmoozedCom'), ('hooks', 'UnSkipOnFail'), ('hooks', 'UnrestrictLi'), ('hooks', 'UpdateManager'), ('hooks', 'WindowsPhoneNotify'), ('hooks', 'XFileSharingPro'), ('hooks', 'ZeveraCom'), ('hoster', 'AlldebridCom'), ('hoster', 'AndroidfilehostCom'), ('hoster', 'BasePlugin'), ('hoster', 'BasketbuildCom'), ('hoster', 'BayfilesCom'), ('hoster', 'BezvadataCz'), ('hoster', 'BillionuploadsCom'), ('hoster', 'BitshareCom'), ('hoster', 'CatShareNet'), ('hoster', 'CloudzillaTo'), ('hoster', 'CramitIn'), ('hoster', 'CrockoCom'), ('hoster', 'CzshareCom'), ('hoster', 'DataHu'), ('hoster', 'DataportCz'), ('hoster', 'DateiTo'), ('hoster', 'DdlstorageCom'), ('hoster', 'DebridItaliaCom'), ('hoster', 'DepositfilesCom'), ('hoster', 'DevhostSt'), ('hoster', 'DlFreeFr'), ('hoster', 'DodanePl'), ('hoster', 'DropboxCom'), ('hoster', 'DuploadOrg'), ('hoster', 'EasybytezCom'), ('hoster', 'EdiskCz'), ('hoster', 'EgoFilesCom'), ('hoster', 'EnteruploadCom'), ('hoster', 'EpicShareNet'), ('hoster', 'EuroshareEu'), ('hoster', 'ExashareCom'), ('hoster', 'ExtabitCom'), ('hoster', 'FastixRu'), ('hoster', 'FastshareCz'), ('hoster', 'FileSharkPl'), ('hoster', 'FileStoreTo'), ('hoster', 'FilecloudIo'), ('hoster', 'FilefactoryCom'), ('hoster', 'FileomCom'), ('hoster', 'FilepostCom'), ('hoster', 'FilepupNet'), ('hoster', 'FilerNet'), ('hoster', 'FilerioCom'), ('hoster', 'FilesMailRu'), ('hoster', 'FileserveCom'), ('hoster', 'FileshareInUa'), ('hoster', 'FilesonicCom'), ('hoster', 'FilezyNet'), ('hoster', 'FiredriveCom'), ('hoster', 'FourSharedCom'), ('hoster', 'FreakshareCom'), ('hoster', 'FreeWayMe'), ('hoster', 'FreevideoCz'), ('hoster', 'FshareVn'), ('hoster', 'Ftp'), ('hoster', 'GigapetaCom'), ('hoster', 'GooIm'), ('hoster', 'GoogledriveCom'), ('hoster', 'HellshareCz'), ('hoster', 'HugefilesNet'), ('hoster', 'HundredEightyUploadCom'), ('hoster', 'IFileWs'), ('hoster', 'IfileIt'), ('hoster', 'IfolderRu'), ('hoster', 'JumbofilesCom'), ('hoster', 'JunocloudMe'), ('hoster', 'Keep2ShareCc'), ('hoster', 'KickloadCom'), ('hoster', 'KingfilesNet'), ('hoster', 'LemUploadsCom'), ('hoster', 'LetitbitNet'), ('hoster', 'LinksnappyCom'), ('hoster', 'LoadTo'), ('hoster', 'LomafileCom'), ('hoster', 'LuckyShareNet'), ('hoster', 'MediafireCom'), ('hoster', 'MegaCoNz'), ('hoster', 'MegaDebridEu'), ('hoster', 'MegaFilesSe'), ('hoster', 'MegaRapidCz'), ('hoster', 'MegacrypterCom'), ('hoster', 'MegareleaseOrg'), ('hoster', 'MegasharesCom'), ('hoster', 'MegauploadCom'), ('hoster', 'MegavideoCom'), ('hoster', 'MovReelCom'), ('hoster', 'MultihostersCom'), ('hoster', 'MultishareCz'), ('hoster', 'MyfastfileCom'), ('hoster', 'MystoreTo'), ('hoster', 'NahrajCz'), ('hoster', 'NarodRu'), ('hoster', 'NetloadIn'), ('hoster', 'NitroflareCom'), ('hoster', 'NoPremiumPl'), ('hoster', 'NosuploadCom'), ('hoster', 'NovafileCom'), ('hoster', 'NowDownloadSx'), ('hoster', 'NowVideoSx'), ('hoster', 'OboomCom'), ('hoster', 'OneFichierCom'), ('hoster', 'OronCom'), ('hoster', 'OverLoadMe'), ('hoster', 'PandaplaNet'), ('hoster', 'PotloadCom'), ('hoster', 'PremiumTo'), ('hoster', 'PremiumizeMe'), ('hoster', 'PromptfileCom'), ('hoster', 'PrzeklejPl'), ('hoster', 'PutdriveCom'), ('hoster', 'QuickshareCz'), ('hoster', 'RPNetBiz'), ('hoster', 'RapideoPl'), ('hoster', 'RapidfileshareNet'), ('hoster', 'RapidgatorNet'), ('hoster', 'RapiduNet'), ('hoster', 'RarefileNet'), ('hoster', 'RealdebridCom'), ('hoster', 'RehostTo'), ('hoster', 'RemixshareCom'), ('hoster', 'RgHostNet'), ('hoster', 'SafesharingEu'), ('hoster', 'SecureUploadEu'), ('hoster', 'SendspaceCom'), ('hoster', 'Share4WebCom'), ('hoster', 'ShareonlineBiz'), ('hoster', 'ShareplaceCom'), ('hoster', 'SharingmatrixCom'), ('hoster', 'SimplyPremiumCom'), ('hoster', 'SimplydebridCom'), ('hoster', 'SmoozedCom'), ('hoster', 'SockshareCom'), ('hoster', 'SoundcloudCom'), ('hoster', 'SpeedyshareCom'), ('hoster', 'StreamCz'), ('hoster', 'StreamcloudEu'), ('hoster', 'TurbobitNet'), ('hoster', 'TusfilesNet'), ('hoster', 'TwoSharedCom'), ('hoster', 'UlozTo'), ('hoster', 'UloziskoSk'), ('hoster', 'UnibytesCom'), ('hoster', 'UnrestrictLi'), ('hoster', 'UpleaCom'), ('hoster', 'UploadableCh'), ('hoster', 'UploadboxCom'), ('hoster', 'UploadedTo'), ('hoster', 'UploadhereCom'), ('hoster', 'UploadheroCom'), ('hoster', 'UploadingCom'), ('hoster', 'UploadkingCom'), ('hoster', 'UpstoreNet'), ('hoster', 'UptoboxCom'), ('hoster', 'VeohCom'), ('hoster', 'VidPlayNet'), ('hoster', 'VimeoCom'), ('hoster', 'Vipleech4UCom'), ('hoster', 'WarserverCz'), ('hoster', 'WebshareCz'), ('hoster', 'WrzucTo'), ('hoster', 'XFileSharingPro'), ('hoster', 'XdadevelopersCom'), ('hoster', 'YibaishiwuCom'), ('hoster', 'YourfilesTo'), ('hoster', 'YoutubeCom'), ('hoster', 'ZShareNet'), ('hoster', 'ZeveraCom'), ('hoster', 'ZippyshareCom'), ('internal', 'CaptchaService'), ('internal', 'DeadCrypter'), ('internal', 'DeadHoster'), ('internal', 'Extractor'), ('internal', 'MultiHook'), ('internal', 'MultiHoster'), ('internal', 'SevenZip'), ('internal', 'SimpleCrypter'), ('internal', 'SimpleDereferer'), ('internal', 'SimpleHoster'), ('internal', 'UnRar'), ('internal', 'UnZip'), ('internal', 'XFSAccount'), ('internal', 'XFSCrypter'), ('internal', 'XFSHoster')]
Jump to time:

**Comment by vuolter** [comment]
Just an huge update.It should not happen again if you keep your plugins up to date. ;)
Line `DEBUG UpdateManager: Requested deletion of plugins` is regular.
No issue here.
