### ISSUE TITLE
ExtractArchive.py 1.36 new problem

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1286]
i did set delete to "Permanent"
this is what i get!
The version before worked perfectly !

25.03.2015 21:43:25 DEBUG     All downloads processed
25.03.2015 21:44:37 DEBUG     ExtractArchive: unrar vb -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -p- -v Downloads/Mr. Turner - Meister des Lichts (2014) IMDb 7.0/omgtv-mrturner-720.part6.rar
25.03.2015 21:44:37 DEBUG     ExtractArchive: Would delete: Downloads/Mr. Turner - Meister des Lichts (2014) IMDb 7.0/omgtv-mrturner-720.part6.rar, Downloads/Mr. Turner - Meister des Lichts (2014) IMDb 7.0/omgtv-mrturner-720.part6.rar, Downloads/Mr. Turner - Meister des Lichts (2014) IMDb 7.0/omgtv-mrturner-720.part2.rar, Downloads/Mr. Turner - Meister des Lichts (2014) IMDb 7.0/omgtv-mrturner-720.part3.rar, Downloads/Mr. Turner - Meister des Lichts (2014) IMDb 7.0/omgtv-mrturner-720.part1.rar, Downloads/Mr. Turner - Meister des Lichts (2014) IMDb 7.0/omgtv-mrturner-720.part4.rar, Downloads/Mr. Turner - Meister des Lichts (2014) IMDb 7.0/omgtv-mrturner-720.part5.rar
25.03.2015 21:44:37 ERROR     ExtractArchive: omgtv-mrturner-720.part6.rar | Send2Trash not installed, no files deleted
25.03.2015 21:44:38 ERROR     ExtractArchive: omgtv-mrturner-720.part6.rar | Unknown error | [Errno 2] No such file or directory: 'Downloads/Mr. Turner - Meister des Lichts (2014) IMDb 7.0/omgtv-mrturner-720.part6.rar'
Traceback (most recent call last):
  File "/root/.pyload/userplugins/hooks/ExtractArchive.py", line 475, in _extract
    os.remove(file)
OSError: [Errno 2] No such file or directory: 'Downloads/Mr. Turner - Meister des Lichts (2014) IMDb 7.0/omgtv-mrturner-720.part6.rar'
25.03.2015 21:44:38 DEBUG     All downloads finished
25.03.2015 21:44:38 ERROR     ExtractArchive: omgtv-mrturner-720.part6.rar | Extract failed

**Comment by Mister-XY** [comment]
Same error.
6243	25.03.2015 21:48:54	ERROR	ExtractArchive: xxx.rar | Extract failed
6242	25.03.2015 21:48:54	ERROR	ExtractArchive: xxx.rar | Unknown error | [Errno 2] No such file or directory: 'xxx/xxx.rar'
6241	25.03.2015 21:48:54	INFO	ExtractArchive: Deleting 46 files
6240	25.03.2015 21:48:54	ERROR	ExtractArchive: xxx.rar | Send2Trash not installed, no files deleted
6239	25.03.2015 21:46:12	INFO	ExtractArchive: xxx.rar | Extract to: xxx/
6238	25.03.2015 21:46:12	INFO	ExtractArchive: Check package: xxx
6237	25.03.2015 21:46:12	INFO	Package finished: xxx

**Comment by Gutz-Pilz** [comment]
https://github.com/pyload/pyload/pull/1287
^^ fixed it

**Comment by immenz** [comment]
Ok, little typo, my bad. But did it work as expected now? On windows it uses absolute paths, therefore no error occur. But in your case it seemes to use a relative path and your log says that it tries to delete a file which couldn't be found, so i assume there are no files deleted?

**Comment by Gutz-Pilz** [comment]
with added "(file)" 
it works for me
