### ISSUE TITLE
quit all threads in core.shutdown()

### ISSUE THREAD

**Issue by ardi69** [pyload/pyload#1295]
in function core.shutdown() not all threads are quited because threadManager.threads are modified by the threads and threadManager.threads are not locked. we must use a copy of it 
<pre>
-            for thread in self.threadManager.threads:
+            for thread in list(self.threadManager.threads):
</pre>

**Comment by vuolter** [comment]
https://github.com/vuolter/pyload/commit/7f70ac84f096ed1fcfe8549513fe3d29fbdb598e
