### ISSUE TITLE
Zippyshare

### ISSUE THREAD

**Issue by duffel90** [pyload/pyload#1303]
pyload starts the download and say finiisched after view secounds. i download it with the browser and get files of 150 MB

here a short log file with debug on:

30.03.2015 12:20:46	INFO	Download starts: ..................part01.rar
615	30.03.2015 12:20:49	INFO	Download starts: ...................part02.rar
616	30.03.2015 12:20:51	INFO	Download starts: ...................part03.rar
617	30.03.2015 12:21:19	INFO	Download finished: ..................part01.rar
618	30.03.2015 12:21:21	INFO	Download starts: ..................part04.rar
619	30.03.2015 12:21:26	INFO	Download finished: ..................part02.rar
620	30.03.2015 12:21:27	INFO	Download starts: ..................part05.rar
621	30.03.2015 12:21:28	INFO	Download finished: ..................part03.rar
622	30.03.2015 12:21:29	INFO	Download starts: ..................part06.rar 

and the queue
...................part01.rar
finished 0.00 BZippyshareCom

**Comment by sebdelsol** [comment]
I guess it's the same issue as [bug #1211](https://github.com/pyload/pyload/issues/1211)
It would be great to know what OS and JS engine @duffel90 is using.

**Comment by vuolter** [comment]
@duffel90 Please reply in https://github.com/pyload/pyload/issues/1211

**Comment by sebdelsol** [comment]
[Oups, Sorry vuolter, I deleted my comment...]
@duffel90, could you please tell us what OS and JS engine you're using. 
It would help us a lot to zero in the bug (see [#1211] (https://github.com/pyload/pyload/issues/1211))

**Comment by duffel90** [comment]
I use a QNAP TS220 with version4.1.3 JS JS engine?
