### ISSUE TITLE
uploaded.net plugin

### ISSUE THREAD

**Issue by Lalarian** [pyload/pyload#1306]
Hello!

I get this error:

Download failed: xxxxxxxxxxx | Parse error: No file downloaded | Plugin may be out of date 

Files are online and download working manually.

PS:
haven't seen stickell around here for some time now, I hope he's ok!

O.O

**Comment by vuolter** [comment]
Sample url, please.
Downloaded as premium or free?

**Comment by Lalarian** [comment]
Hello!

Sorry, for lackign info!

Sample: http://uploaded.net/file/66e0yyxf
(But it happens with any link!)

Free Access.

Thank you!

**Comment by elite705** [comment]
Hi, I get the same error, here is the Log with Debug:
39	11.04.2015 20:28:14	INFO	Download starts: FreeDOS-1.1-memstick-2-256M.img.bz2
40	11.04.2015 20:28:14	DEBUG	UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
41	11.04.2015 20:28:14	DEBUG	UploadedTo: Update file info...
42	11.04.2015 20:28:14	DEBUG	UploadedTo: Previous file info: {}
43	11.04.2015 20:28:14	DEBUG	UploadedTo: Current file info: {'status': 2, 'url': u'http://uploaded.net/file/66e0yyxf', 'size': 7019949.0, 'name': u'FreeDOS-1.1-memstick-2-256M.img.bz2', 'pattern': {'ID': u'66e0yyxf'}}
44	11.04.2015 20:28:14	DEBUG	UploadedTo: File name: FreeDOS-1.1-memstick-2-256M.img.bz2 | File size: 7019949 byte
45	11.04.2015 20:28:14	DEBUG	UploadedTo: File status: online
46	11.04.2015 20:28:14	WARNING	Download failed: FreeDOS-1.1-memstick-2-256M.img.bz2 | Parse error: No file downloaded | Plugin may be out of date 

and the according debug output from console:
11.04.2015 20:28:14 INFO      Download starts: FreeDOS-1.1-memstick-2-256M.img.bz2
11.04.2015 20:28:14 DEBUG     UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
11.04.2015 20:28:14 DEBUG     UploadedTo: Update file info...
11.04.2015 20:28:14 DEBUG     UploadedTo: Previous file info: {}
11.04.2015 20:28:14 DEBUG     UploadedTo: Current file info: {'status': 2, 'url': u'http://uploaded.net/file/66e0yyxf', 'size': 7019949.0, 'name': u'FreeDOS-1.1-memstick-2-256M.img.bz2', 'pattern': {'ID': u'66e0yyxf'}}
11.04.2015 20:28:14 DEBUG     UploadedTo: File name: FreeDOS-1.1-memstick-2-256M.img.bz2 | File size: 7019949 byte
11.04.2015 20:28:14 DEBUG     UploadedTo: File status: online
11.04.2015 20:28:14 WARNING   Download failed: FreeDOS-1.1-memstick-2-256M.img.bz2 | Parse error: No file downloaded | Plugin may be out of date
11.04.2015 20:28:14 INFO      UnSkipOnFail: Looking for skipped duplicates of: FreeDOS-1.1-memstick-2-256M.img.bz2 (pid:1)
11.04.2015 20:28:14 INFO      UnSkipOnFail: No duplicates found
Traceback (most recent call last):
  File "/usr/share/pyload/module/database/DatabaseBackend.py", line 96, in processJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 767, in updateLink
    self.c.execute('UPDATE links SET url=?,name=?,size=?,status=?,error=?,package=? WHERE id=?', (f.url, f.name, f.size, f.status, f.error, str(f.packageid), str(f.id)))
InterfaceError: Error binding parameter 4 - probably unsupported type.
Database Error @ updateLink (PyFile 1: FreeDOS-1.1-memstick-2-256M.img.bz2@UploadedTo,) {} Error binding parameter 4 - probably unsupported type.
11.04.2015 20:28:14 DEBUG     All downloads processed

I hope the error message helps.

**Comment by chris-19** [comment]
Hi,
after a bit of digging in, for me it looks like the changed behaviour of the SImpleHoster class leads to the problem. In the downloaded file it says parallel download is not possible, probably the new introduced disposition workaround is the problem.
overloading the downloadLink function in the UploadedTo class:
def downloadLink(self, link, disposition=False):
	super(UploadedTo, self).downloadLink(link, disposition=disposition)
downloads with uploadedTo are working again for me.

The binding error from the last comment is a general problem reported in issue #1346
Hope the investigation helps a bit.

**Comment by elite705** [comment]
Yes this helps, but I think we should just insert the line DISPOSITION = False in the class definition of UploadedTo like:

WAIT_PATTERN = r'Current waiting period: <span>(\d+)'
DL_LIMIT_ERROR = r'You have reached the max. number of possible free downloads for this hour'
DISPOSITION = False

Your overload does not work for me, because in SimpleHoster the downloadLink function is still called with disposition=true, so the default value is never used.
Should I fork the repository and change UploadedTo.py?

**Comment by Napster32** [comment]
Hello Vuolter,
I need help!
1. I buy a premium account, but pyload does not see it as a premium, why?
2. I want to download this file: http://uploaded.net/file/hz1fds7t
Pyload but says: Download is offline: hz1fds7t
But it is not possible because I can manually download files safely.
Where is the mistake?
Thanks

**Comment by vuolter** [comment]
@Napster32 Working on...

**Comment by vuolter** [comment]
@Napster32 Retry now.

**Comment by Napster32** [comment]
In my premium account in pyload, I added my account Uploaded.net (set as UploadedTo), but Pyload tells me:
Status: Valid
Premium: no (however my account has premium)
Valid until: not available
Traffic left: not available
Can you fix that too?
Thanks

**Comment by Napster32** [comment]
I find this error when I download the file:
- Download failed: AdCreClouCC2015.part26.rar | global name 'decode' is not defined
It also pointed to other mistakes that I have:
- Error executing hooks: 'XFileSharingPro' object has no attribute 'pyfile'
- Error executing hooks: 'LinkdecrypterComHook' object has no attribute 'pyfile'
- Error executing hooks: 'UnSkipOnFail' object has no attribute 'pyfile'

**Comment by Napster32** [comment]
Uploaded.net not work:
30.07.2015 10:40:59	INFO	Download starts: hz1fds7t
30.07.2015 10:40:59	INFO	HOSTER UploadedTo[116] : Updating file info...
30.07.2015 10:40:59	INFO	HOSTER UploadedTo[116] : File name: hz1fds7t
30.07.2015 10:40:59	INFO	HOSTER UploadedTo[116] : File size: Unknown
30.07.2015 10:40:59	INFO	HOSTER UploadedTo[116] : File status: offline
30.07.2015 10:40:59	WARNING	HOSTER UploadedTo[116] : Config option `fallback` not found, use default `True`
30.07.2015 10:40:59	WARNING	Download failed: hz1fds7t | offline
30.07.2015 10:40:59	INFO	HOOK UnSkipOnFail : Looking for skipped duplicates of: hz1fds7t (pid:23)
30.07.2015 10:40:59	INFO	HOOK UnSkipOnFail : No duplicates found
And my account Premium not work!
Thanks

**Comment by vuolter** [comment]
I didn't found these errors. Maybe: http://forum.pyload.org/viewtopic.php?f=7&t=4335

**Comment by Napster32** [comment]
Hi @vuolter ,
I attempted to clean you indicated, but nothing has changed.
I always get this error:
30/07/2015 15:22:56 WARNING Download failed: hz1fds7t | offline
But the file is not completely offline!

**Comment by Napster32** [comment]
Hi @vuolter ,
I am now looking closely errors,
but the download is not called: hz1fds7t
but it called: AdCreClouCC2015.part26.rar
I believe that the plugin can not find the real address of the file, right?

**Comment by vuolter** [comment]
@Napster32 Please, retry now.

**Comment by Napster32** [comment]
Hi @vuolter ,
It not work:

159	02.08.2015 11:06:53	INFO	Download starts: hz1fds7t
160	02.08.2015 11:06:53	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
161	02.08.2015 11:06:53	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
162	02.08.2015 11:06:53	DEBUG	HOSTER UploadedTo[1]: PROCESS URL http://uploaded.net/file/hz1fds7t | PLUGIN VERSION 0.96
163	02.08.2015 11:06:53	INFO	HOSTER UploadedTo[1]: Updating file info...
164	02.08.2015 11:06:53	DEBUG	HOSTER UploadedTo[1]: File info: {'status': 1, 'url': u'http://uploaded.net/file/hz1fds7t', 'size': 0, 'name': u'hz1fds7t', 'pattern': {'ID': u'hz1fds7t'}}
165	02.08.2015 11:06:53	DEBUG	HOSTER UploadedTo[1]: Previous file info: {}
166	02.08.2015 11:06:53	INFO	HOSTER UploadedTo[1]: File name: hz1fds7t
167	02.08.2015 11:06:53	INFO	HOSTER UploadedTo[1]: File size: Unknown
168	02.08.2015 11:06:53	INFO	HOSTER UploadedTo[1]: File status: offline
169	02.08.2015 11:06:53	DEBUG	HOSTER UploadedTo[1]: Config option `fallback` not found, use default `True`
170	02.08.2015 11:06:53	WARNING	Download failed: hz1fds7t | offline
171	02.08.2015 11:06:53	INFO	HOOK UnSkipOnFail: Looking for skipped duplicates of: hz1fds7t (pid:1)
172	02.08.2015 11:06:53	INFO	HOOK UnSkipOnFail: No duplicates found 

And my premium account not work!
I hid my username and password!

110	02.08.2015 11:05:11	INFO	ACCOUNT UploadedTo: Login user `********`...
111	02.08.2015 11:05:11	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/io/login | decode=True | cookies=True | get={} | req=None | _[1]=['decode=True', 'cookies=True', 'get={}', 'req=None'] | multipart=False | post={'id': '********', 'pw': '********'} | ref=True | just_header=False
112	02.08.2015 11:05:12	INFO	ACCOUNT UploadedTo: Parsing account info for user `********`...
113	02.08.2015 11:05:12	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | decode=True | cookies=True | get={} | req=None | _[1]=['decode=True', 'cookies=True', 'get={}', 'req=None'] | multipart=False | post={} | ref=True | just_header=False
114	02.08.2015 11:05:12	DEBUG	ACCOUNT UploadedTo: Account info for user `********`: {'login': {'timestamp': 1438506311.940608, 'password': '**********', 'valid': True}, 'data': {'premium': False, 'trafficleft': None, 'options': {}, 'maxtraffic': None, 'validuntil': None, 'login': '********', 'password': '**********', 'type': 'UploadedTo', 'valid': True}}

**Comment by sraedler** [comment]
This Plugin also working, please close

**Comment by thermalhack** [comment]
Hello,
I am getting the exact same issue of pyload saying that my UploadedTo account is not premium however I have a 2 year premium subscription. please help.

**Comment by GammaC0de** [comment]
@thermalhack Please open a new issue.
