### ISSUE TITLE
error event handler archive_extracted

### ISSUE THREAD

**Issue by namealwaysinuse** [pyload/pyload#1307]
hi,

after the ExtractArchive update i got the following error in log

Erorr calling event handler archive_extracted: >, (PyFile 1439: "nameofdata@hoster", ), archive_extracted() takes exactly 5 arguments (3 given)

files will be extracted but my scripts doesnt start anymore after extraction

best wishes

**Comment by vuolter** [comment]
Full debug log please.

**Comment by zappelrulez** [comment]
same issue here!

02.04.2015 18:54:47	INFO	ExtractArchive: Check package: newgirlWEBHD419
274	02.04.2015 18:54:47	DEBUG	ExtractArchive: Targets for UnRar: [('/nfs/Temp/newgirlWEBHD419.part04.rar', 1032, '/nfs/Temp/')]
275	02.04.2015 18:54:47	INFO	ExtractArchive: newgirlWEBHD419.part04.rar | Extract to: /nfs/Temp/
276	02.04.2015 18:54:47	DEBUG	ExtractArchive: Password: None provided
277	02.04.2015 18:54:47	DEBUG	ExtractArchive: unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -p- -v /nfs/Temp/newgirlWEBHD419.part04.rar
278	02.04.2015 18:54:48	INFO	ExtractArchive: newgirlWEBHD419.part04.rar | Password protected
279	02.04.2015 18:54:48	DEBUG	ExtractArchive: unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pserienjunkies.org -v /nfs/Temp/newgirlWEBHD419.part04.rar
280	02.04.2015 18:54:49	DEBUG	ExtractArchive: Extracting using password: serienjunkies.org
281	02.04.2015 18:54:49	DEBUG	ExtractArchive: unrar x -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pserienjunkies.org /nfs/Temp/newgirlWEBHD419.part04.rar /nfs/Temp/
282	02.04.2015 18:59:35	DEBUG	ExtractArchive: unrar vb -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pserienjunkies.org -v /nfs/Temp/newgirlWEBHD419.part04.rar
283	02.04.2015 18:59:36	DEBUG	ExtractArchive: Would delete: /nfs/Temp/newgirlWEBHD419.part04.rar, /nfs/Temp/newgirlWEBHD419.part04.rar, /nfs/Temp/newgirlWEBHD419.part06.rar, /nfs/Temp/newgirlWEBHD419.part03.rar, /nfs/Temp/newgirlWEBHD419.part08.rar, /nfs/Temp/newgirlWEBHD419.part10.rar, /nfs/Temp/newgirlWEBHD419.part07.rar, /nfs/Temp/newgirlWEBHD419.part05.rar, /nfs/Temp/newgirlWEBHD419.part09.rar, /nfs/Temp/newgirlWEBHD419.part01.rar, /nfs/Temp/newgirlWEBHD419.part02.rar
284	02.04.2015 18:59:36	INFO	ExtractArchive: newgirlWEBHD419.part04.rar | Extracting finished
285	02.04.2015 18:59:36	DEBUG	All downloads finished
286	02.04.2015 18:59:37	DEBUG	ExtractArchive: Extracted files: ['/nfs/Temp/New.Girl.S04E19.The.Right.Thing.1080p.WEB.DL.DD5.1.H.264.SA89.mkv']
287	02.04.2015 18:59:37	WARNING	Error calling event handler archive_extracted: >, (PyFile 1032: newgirlWEBHD419.part04.rar@UploadedTo, ), archive_extracted() takes exactly 5 arguments (3 given)

**Comment by immenz** [comment]
Working well for me, seems that your ExternalScripts plugin isn't up to date

**Comment by zappelrulez** [comment]
this is the version i have, is there a newer one?

class ExternalScripts(Hook):
    __name__    = "ExternalScripts"
    __type__    = "hook"
    __version__ = "0.38"

**Comment by zappelrulez** [comment]
Problem is still present.
Sure you fixed it? from the change log i can see only the change of the version, nothing else.

**Comment by namealwaysinuse** [comment]
Same for me....
Still present 

Von meinem iPhone gesendet

**Comment by immenz** [comment]
@vuolter bumped only the version number, to be sure that the latest changes are send to you if you use update manager.

Do you use updatemanager or what are your settings? (Which System, Running from Git, manually editing files?)

**Comment by namealwaysinuse** [comment]
Im Running Ubuntu server and Update via updatemanager.

The Problem comes with the Last Update. Before it works perfectly.

Von meinem iPhone gesendet

**Comment by immenz** [comment]
Are you using some kind of FileBot Hook?

**Comment by namealwaysinuse** [comment]
Yes i have the filebot hook 

Von meinem iPhone gesendet

**Comment by immenz** [comment]
there's the problem...

**Comment by namealwaysinuse** [comment]
Sorry i dont Unterstand what i have To do now, because before the Update it worked perfectly. 

Von meinem iPhone gesendet

**Comment by zappelrulez** [comment]
immenz is right. for me it was the EpisodeMover Hook. I had to update to the latest version.
Thanks!
