### ISSUE TITLE
[Easybytez] - Download not starting

### ISSUE THREAD

**Issue by erse80** [pyload/pyload#1308]
Hi 

i use pyload whith socks5 proxy enabled.

plugin check link, recive direct link but download not starting

i have reinstalled pyload problem persist

DEBUG:

01.04.2015 18:22:21 DEBUG     EasybytezCom: Current file info: {'status': 2, 'url': u'http://www.easybytez.com/oi3srvnuxu1w', 'size': 525336576.0, 'name': u'RUE3ZM1CFEYKBRJ1C55T9POC95.part43.rar', 'pattern': {'S': u'501.0', 'U': u'MB', 'N': u'RUE3ZM1CFEYKBRJ1C55T9POC95.part43.rar'}}
01.04.2015 18:22:21 DEBUG     EasybytezCom: File name: RUE3ZM1CFEYKBRJ1C55T9POC95.part43.rar | File size: 525336576 byte
01.04.2015 18:22:21 DEBUG     EasybytezCom: File status: online
01.04.2015 18:22:21 DEBUG     EasybytezCom: Looking for direct download link...
01.04.2015 18:22:21 DEBUG     EasybytezCom: Redirect #0 to: http://www.easybytez.com/oi3srvnuxu1w
01.04.2015 18:22:22 DEBUG     EasybytezCom: Redirect #1 to: http://str78.easybytez.to/files/0/83905zbpigtdw6/RUE3ZM1CFEYKBRJ1C55T9POC95.part43.rar
01.04.2015 18:22:22 INFO      EasybytezCom: Direct download link detected
01.04.2015 18:22:23 INFO      Download starts: RUE3ZM1CFEYKBRJ1C55T9POC95.part10.rar
01.04.2015 18:22:23 DEBUG     EasybytezCom: Update file info...
01.04.2015 18:22:23 DEBUG     EasybytezCom: Previous file info: {}
01.04.2015 18:22:23 DEBUG     EasybytezCom: Current file info: {'status': 2, 'url': u'http://www.easybytez.com/yzdbfh4kjaus', 'size': 525336576.0, 'name': u'RUE3ZM1CFEYKBRJ1C55T9POC95.part10.rar', 'pattern': {'S': u'501.0', 'U': u'MB', 'N': u'RUE3ZM1CFEYKBRJ1C55T9POC95.part10.rar'}}
01.04.2015 18:22:23 DEBUG     EasybytezCom: File name: RUE3ZM1CFEYKBRJ1C55T9POC95.part10.rar | File size: 525336576 byte
01.04.2015 18:22:23 DEBUG     EasybytezCom: File status: online
01.04.2015 18:22:23 DEBUG     EasybytezCom: Looking for direct download link...
01.04.2015 18:22:23 DEBUG     EasybytezCom: Redirect #0 to: http://www.easybytez.com/yzdbfh4kjaus
01.04.2015 18:22:24 DEBUG     EasybytezCom: Redirect #1 to: http://str64.easybytez.com/files/9/0ffn0mcggnfghh/RUE3ZM1CFEYKBRJ1C55T9POC95.part10.rar
01.04.2015 18:22:24 INFO      EasybytezCom: Direct download link detected
01.04.2015 18:22:25 INFO      Download starts: RUE3ZM1CFEYKBRJ1C55T9POC95.part48.rar
01.04.2015 18:22:25 DEBUG     EasybytezCom: Update file info...
01.04.2015 18:22:25 DEBUG     EasybytezCom: Previous file info: {}
01.04.2015 18:22:25 DEBUG     EasybytezCom: Current file info: {'status': 2, 'url': u'http://www.easybytez.com/59eib96mhja0', 'size': 525336576.0, 'name': u'RUE3ZM1CFEYKBRJ1C55T9POC95.part48.rar', 'pattern': {'S': u'501.0', 'U': u'MB', 'N': u'RUE3ZM1CFEYKBRJ1C55T9POC95.part48.rar'}}
01.04.2015 18:22:25 DEBUG     EasybytezCom: File name: RUE3ZM1CFEYKBRJ1C55T9POC95.part48.rar | File size: 525336576 byte
01.04.2015 18:22:25 DEBUG     EasybytezCom: File status: online
01.04.2015 18:22:25 DEBUG     EasybytezCom: Looking for direct download link...
01.04.2015 18:22:25 DEBUG     EasybytezCom: Redirect #0 to: http://www.easybytez.com/59eib96mhja0
01.04.2015 18:22:26 DEBUG     EasybytezCom: Redirect #1 to: http://str64.easybytez.com/files/9/2gqpajx4d8po8z/RUE3ZM1CFEYKBRJ1C55T9POC95.part48.rar
01.04.2015 18:22:26 INFO      EasybytezCom: Direct download link detected

**Comment by GammaC0de** [comment]
Hi,
if you are trying to download  EasybytezCom without a premium account, you can`t, there is a limit of 300MB per file.
```
10.04.2015 04:37:57 WARNING   EasybytezCom: You can download files up to 300 Mb only.
10.04.2015 04:37:57 WARNING   Download failed: RUE3ZM1CFEYKBRJ1C55T9POC95.part43.rar | File too large for free download
```
