### ISSUE TITLE
[ExtractArchive]unrar does not use passwordfile but 7zip does.

### ISSUE THREAD

**Issue by zappelrulez** [pyload/pyload#1312]
Hi ,
unrar seems sometimes not use the given password file for extracting. Instead it just uses none, which obviously fails. When i create the passwaordfile new then unrar is working fine, but after some extractions it just stops using the password file. 
I did not change the passwordfile, so i think its not related to the file itsself. Because in the beginnging it is working.

If the xtraction fails 7zip is trying to extract and 7zip always uses the password file. But 7zip can not handle multiple .rar part files and it extracts only the first one.

here is the log:
8.03.2015 22:48:11 DEBUG     ExtractArchive: Password: None provided
28.03.2015 22:48:11 DEBUG     ExtractArchive: unrar l -o+ -x'_.nfo' -x'_.DS_Store' -x'index.dat' -x'thumb.db' -y -p- -v /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar
28.03.2015 22:48:11 DEBUG     ExtractArchive: Password: None provided
28.03.2015 22:48:11 DEBUG     ExtractArchive: unrar l -o+ -x'_.nfo' -x'_.DS_Store' -x'index.dat' -x'thumb.db' -y -p- -v /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar
28.03.2015 22:48:12 DEBUG     ExtractArchive: Extracting using password: None
28.03.2015 22:48:12 DEBUG     ExtractArchive: unrar x -o+ -x'_.nfo' -x'_.DS_Store' -x'index.dat' -x'thumb.db' -y -p- /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar /nfs/Temp/
28.03.2015 22:48:12 DEBUG     ExtractArchive: Extracting using password: None
28.03.2015 22:48:12 DEBUG     ExtractArchive: unrar x -o+ -x'_.nfo' -x'_.DS_Store' -x'index.dat' -x'thumb.db' -y -p- /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar /nfs/Temp/
28.03.2015 23:03:51 ERROR     ExtractArchive: The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar | No password found
28.03.2015 23:03:51 ERROR     ExtractArchive: The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar | Extract failed
28.03.2015 23:03:51 ERROR     ExtractArchive: The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar | No password found
28.03.2015 23:03:51 DEBUG     ExtractArchive: Targets for SevenZip: [('/nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar', 69, '/nfs/Temp/')]
28.03.2015 23:03:51 INFO      ExtractArchive: The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar | Extract to: /nfs/Temp/
28.03.2015 23:03:51 ERROR     ExtractArchive: The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar | Extract failed
28.03.2015 23:03:51 DEBUG     ExtractArchive: Password: None provided
28.03.2015 23:03:51 DEBUG     ExtractArchive: 7z l -y -p- -slt /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar
28.03.2015 23:03:51 DEBUG     ExtractArchive: Targets for SevenZip: [('/nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar', 69, '/nfs/Temp/')]
28.03.2015 23:03:51 INFO      ExtractArchive: The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar | Extract to: /nfs/Temp/
28.03.2015 23:03:51 DEBUG     ExtractArchive: Password: None provided
28.03.2015 23:03:51 DEBUG     ExtractArchive: 7z l -y -p- -slt /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar
28.03.2015 23:03:53 INFO      ExtractArchive: The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar | Password protected
28.03.2015 23:03:53 INFO      ExtractArchive: The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar | Password protected
28.03.2015 23:03:53 DEBUG     ExtractArchive: 7z l -y -p- -slt /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar
28.03.2015 23:03:53 DEBUG     ExtractArchive: 7z l -y -p- -slt /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar
28.03.2015 23:03:53 DEBUG     ExtractArchive: 7z l -y -p- -slt /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar
28.03.2015 23:03:53 DEBUG     ExtractArchive: 7z l -y -p- -slt /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar
28.03.2015 23:03:53 DEBUG     ExtractArchive: Extracting using password: serienjunkies.org
28.03.2015 23:03:53 DEBUG     ExtractArchive: 7z x -y -pserienjunkies.org -o/nfs/Temp/ /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar
28.03.2015 23:03:53 DEBUG     ExtractArchive: Extracting using password: serienjunkies.org
28.03.2015 23:03:53 DEBUG     ExtractArchive: 7z x -y -pserienjunkies.org -o/nfs/Temp/ /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar
28.03.2015 23:04:27 DEBUG     ExtractArchive: 7z l -y -pserienjunkies.org /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar
28.03.2015 23:04:27 DEBUG     ExtractArchive: 7z l -y -pserienjunkies.org /nfs/Temp/The.Walking.Dead.S05E15.1080p.WEB-DL.DD5.1.H.264-Cyphanix.part02.rar

**Comment by j4m** [comment]
same problem here

**Comment by t-h-e** [comment]
I have fixed the problem for me.

unrar problem:
Set "Test archive before extracting" to "on" in the "ExtractArchive" plugin.
Then Extractor.verify will be called instead of Extractor.check.
In case of unrar, the method check only lists the contents of the archive and a password check might not be done (unrar is called with command 'l').

7z:
7z can handle multiple .rar part files. But to do this you have to give it the first part ("xxx.part1.rar").
So I just sort the files before they get extracted, to make sure that files with a part1.rar ending come first.

I added the following line in pyload/module/plugins/ExtractArchive.py in line 290:

    files_ids.sort(key=lambda x:x[0])

after:

    files_ids = dict((pylink['name'],((save_join(download_folder, pypack.folder, pylink['name'])), pylink['id'], out)) for pylink \
    in sorted(pypack.getChildren().itervalues(), key=lambda k: k['name'])).values()  #: remove duplicates

It works for me. Maybe it would be better to integrate the sort in the previous line or in Extractor.getTargets
