### ISSUE TITLE
Zippyshare captcha not detected

### ISSUE THREAD

**Issue by martin-au** [pyload/pyload#1313]
04.04.2015 19:39:48	WARNING	Download failed: exq-panemmockingjay1-1080p.part02.rar | 'exceptions.AttributeError' object has no attribute 'strip'
82	04.04.2015 19:39:48	INFO	UnSkipOnFail: Looking for skipped duplicates of: exq-panemmockingjay1-1080p.part02.rar (pid:7)
83	04.04.2015 19:39:48	INFO	UnSkipOnFail: No duplicates found

File: http://www50.zippyshare.com/v/LLkcBOOb/file.html

**Comment by sebdelsol** [comment]
mmm, the captcha is not detected.

**Comment by Mister-XY** [comment]
If you download this file tomorrow, is must be ok. Sometimes, i have the same error and download the file on an other day.

**Comment by vuolter** [comment]
If happens again, please post the zippyshare file starting with `debug_`, you found under your pyload config directory.

**Comment by Mister-XY** [comment]
Look here, here is a log
http://pastebin.com/UzaE5dgL

**Comment by sraedler** [comment]
I guess this could be closed, because zippy is working in the last weeks and I'm using it daily...

**Comment by GammaC0de** [comment]
Thanks :+1:
