### ISSUE TITLE
Error with Premium.to and name of the files

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#1316]
Hello again, i found an new error withe share-online or premium.to.
I i download a file via premium.to., i get an file that called like linkname insteat of the filename.
If i download as free user, i get the right filename. 
Here is the Log:
DEBUG   Content-Disposition: xxx.rar
DEBUG   PremiumTo: Handled as premium download
INFO    PremiumTo: Filesize: 0 KiB, Traffic left for user XXX: XXX KiB
DEBUG   PremiumTo: Account Info: {'validuntil': -1, 'premium': True, 'trafficleft': XXX}
DEBUG   PremiumTo: Get Account Info for XXX
DEBUG   PremiumTo: File status: queued
DEBUG   PremiumTo: Current file info: {'status': 3, 'url': u'http://share-online.biz/dl/1234', 'name': u'12345', 'size': 0}
DEBUG   PremiumTo: Previous file info: {}
DEBUG   PremiumTo: Update file info...
INFO    Download starts: http://share-online.biz/dl/12345 

After the Download, i have an file that called "http://share-online.biz/dl/12345"  insteat xxx.rar

I also found the same error also with uploadable.ch

**Comment by Mister-XY** [comment]
here as free downloader
DEBUG	Content-Disposition: xxx.rar
DEBUG	ReCaptcha: Result: jaalmos intersecting
DEBUG	Received captcha result: jaalmos intersecting
ERROR	Error importing ShareonlineBiz: No module named captcha
DEBUG	ReCaptcha: Challenge: 03AHJ_VuuzIR-XoMi73lMbJTlEJsxmsoPNZvp_4lHLcmKC1U6CiPAUSz5Tj81O_swBJF79CZj2c0_wUiIx9_7X0jDiJq0j-hDu7JPF1SLt-PiGSIUPIbB_mYkv2myVYgLUjAzuypuoXd3DZVJO7eo2cVxc46AjVpQsKtL-t_VUJ1T1oFGdTt6COcoB6O8sGjAe7FZgLt_BktM5AAzJtZRia-k11y1pMa6gww
DEBUG	ShareonlineBiz: Handled as free download
DEBUG	ShareonlineBiz: File status: online
DEBUG	ShareonlineBiz: File name: xxx.rar | File size: 1046478850 byte
DEBUG	ShareonlineBiz: Current file info: {'status': 2, 'name': u'xxx.rar', 'url': u'http://www.share-online.biz/dl/xxx, 'pattern': {'ID': u'xxx}, 'size': u'1046478850', 'md5': u'0c95d1bcb778e9dfe8d1a314254efb33', 'fileid': u'xxx}
DEBUG	ShareonlineBiz: Previous file info: {'status': 2, 'name': u'xxx.rar', 'url': u'http://www.share-online.biz/dl/xxx, 'pattern': {'ID': u'xxx}, 'size': u'1046478850', 'md5': u'0c95d1bcb778e9dfe8d1a314254efb33', 'fileid': u'xxx}
DEBUG	ShareonlineBiz: Update file info...
DEBUG	ShareonlineBiz: File name: xxx.rar | File size: 1046478850 byte
DEBUG	ShareonlineBiz: Current file info: {'status': 2, 'name': u'xxx.rar', 'url': u'http://www.share-online.biz/dl/xxx, 'pattern': {'ID': u'xxx}, 'size': u'1046478850', 'md5': u'0c95d1bcb778e9dfe8d1a314254efb33', 'fileid': u'xxx}
DEBUG	ShareonlineBiz: Previous file info: {'status': 2, 'fileid': u'xxx, 'name': u'xxx.rar', 'url': u'http://www.share-online.biz/dl/xxx, 'pattern': {'ID': u'xxx}, 'md5': u'0c95d1bcb778e9dfe8d1a314254efb33', 'size': u'1046478850'}
DEBUG	ShareonlineBiz: Update file info...
DEBUG	ShareonlineBiz: Direct download link not found
DEBUG	ShareonlineBiz: Redirect #0 to: http://www.share-online.biz/dl/xxx
DEBUG	ShareonlineBiz: Looking for direct download link...
DEBUG	ShareonlineBiz: File status: online
DEBUG	ShareonlineBiz: File name: xxx.rar | File size: 1046478850 byte
DEBUG	ShareonlineBiz: Current file info: {'status': 2, 'fileid': u'xxx, 'name': u'xxx.rar', 'url': u'http://www.share-online.biz/dl/xxx, 'pattern': {'ID': u'xxx}, 'md5': u'0c95d1bcb778e9dfe8d1a314254efb33', 'size': u'1046478850'}
DEBUG	ShareonlineBiz: Previous file info: {}
DEBUG	ShareonlineBiz: Update file info...
INFO	Download starts: http://share-online.biz/dl/xxx

**Comment by realbronto** [comment]
same here with premium.to + uploaded.to

**Comment by Mister-XY** [comment]
Is it possible, that the multihoster did not rename it to the right filename?

**Comment by MikeD23** [comment]
I think problem is the same as here: https://github.com/pyload/pyload/issues/1317

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/f403431adf0823da83072d4fa6aa58ace44fda3f
