### ISSUE TITLE
debriditalia.com wrong filename

### ISSUE THREAD

**Issue by Mave95** [pyload/pyload#1317]
Hello,

the files downloaded with debriditalia.com are renamed to something like "HASC3S~W.RAR".
ExtractArchive doesn't work with these filenames, when I have multiple parts.

**Comment by MikeD23** [comment]
Same here. For me most of the files weren't named with .rar ending. I think reloading supported hoster list doesn't work. In log download acts like normal uploaded.to download. No debriditalia links were listet in debug log.
This is log after start of pyload: http://pastebin.com/0byUmVTE

**Comment by Mister-XY** [comment]
MkieD23, there is nothing to see in your log, you always see, that you start pyload but now error with the download.

**Comment by MikeD23** [comment]
Yeah I know but I thought maybe there is something wrong in the beginning.
Here is a log of my downloads: http://pastebin.com/HuWg698t
There are the same issues like in #1316.

**Comment by Mister-XY** [comment]
Ok, it's also an problem with an multihoster and the wrong filename.

**Comment by MikeD23** [comment]
After plugin updates issue seems solved!

**Comment by Mister-XY** [comment]
i cant test, i have an error. The file is empty. i don't know, what is this for an error

**Comment by MikeD23** [comment]
Still a problem for me. Sometimes it works, other times it 'doesnt. Have to start (& fail) every download as a free user to get filenames and then enable multihoster to download. That works for me.

**Comment by Velociraptor85** [comment]
since duplicate was fixed ... see https://github.com/pyload/pyload/issues/1316#issuecomment-277420059
