### ISSUE TITLE
Hosted UploadedTo is broken

### ISSUE THREAD

**Issue by Kap0** [pyload/pyload#1319]
UploadedTo: Could not login with account | (6, "Couldn't resolve host 'uploaded.net'")

The username and password works with the jDownloader.

**Comment by Mister-XY** [comment]
Ok, i have extra update my pyload to see if this an error with a new update, but i have no problem to download via uploaded.to

**Comment by Ghoststage** [comment]
Hi I have also now and then , but only because pyLoad after a reboot of the server is immediately ready . After a restart of pylod everything is ok again . Try it once if you have not already tried it . Sorry for my English Google

**Comment by Kap0** [comment]
Now it works. I've restarted pyload (at my nas) multiple times but it didn't worked. The solution was to shutdown my nas for a couple of hours and restart the nas and pyload afterwards.
