### ISSUE TITLE
Some issue in fileshark.pl

### ISSUE THREAD

**Issue by akfedux** [pyload/pyload#1327]
Hi,

debuglog http://pastebin.com/asTdmS3W

preload_line455.dump.html http://pastebin.com/3kFDzHqt

TIA

**Comment by akfedux** [comment]
Old   LINK_FREE_PATTERN = r'<a href="(.*?)" class="btn-upload-free">'

New 
<div class="panel-footer">
                    <a  rel="nofollow" href="/pobierz/normal/2528385/ab0a1/" class="btn-upload-free">Pobierz za darmo<br><small>max 150 KB/s</small></a>
                </div>

Can you update LINK_FREE_PATTERN ?

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/686d51fb3a43cb49ee4c3f44ea48b052d36616e0
