### ISSUE TITLE
newer versions of beaker changed PBKDF2-stuff

### ISSUE THREAD

**Issue by ardi69** [pyload/pyload#1330]
in newer versions of beaker the PBKDF2-stuff has been changed
the attached patch resove this

<pre>
diff --git a/module/plugins/accounts/OboomCom.py b/module/plugins/accounts/OboomCom.py
index 0acacbb..9f46a71 100644
--- a/module/plugins/accounts/OboomCom.py
+++ b/module/plugins/accounts/OboomCom.py
@@ -2,7 +2,19 @@
 
 import time
 
-from beaker.crypto.pbkdf2 import PBKDF2
+try:
+    from beaker.crypto.pbkdf2 import PBKDF2
+except:
+    from beaker.crypto.pbkdf2 import pbkdf2
+    from binascii import b2a_hex
+    class PBKDF2(object):
+        def __init__(self, passphrase, salt, iterations=1000):
+            self.passphrase = passphrase
+            self.salt = salt
+            self.iterations = iterations
+
+        def hexread(self, octets):
+            return b2a_hex(pbkdf2(self.passphrase, self.salt, self.iterations, octets))
 
 from module.common.json_layer import json_loads
 from module.plugins.Account import Account
diff --git a/module/plugins/accounts/SmoozedCom.py b/module/plugins/accounts/SmoozedCom.py
index 87efb89..2e02bc7 100644
--- a/module/plugins/accounts/SmoozedCom.py
+++ b/module/plugins/accounts/SmoozedCom.py
@@ -3,7 +3,19 @@
 import hashlib
 import time
 
-from beaker.crypto.pbkdf2 import PBKDF2
+try:
+    from beaker.crypto.pbkdf2 import PBKDF2
+except:
+    from beaker.crypto.pbkdf2 import pbkdf2
+    from binascii import b2a_hex
+    class PBKDF2(object):
+        def __init__(self, passphrase, salt, iterations=1000):
+            self.passphrase = passphrase
+            self.salt = salt
+            self.iterations = iterations
+
+        def hexread(self, octets):
+            return b2a_hex(pbkdf2(self.passphrase, self.salt, self.iterations, octets))
 
 from module.common.json_layer import json_loads
 from module.plugins.Account import Account
</pre>

**Comment by vuolter** [comment]
Please open a new PR here https://github.com/pyload/pyload/pulls

**Comment by ardi69** [comment]
this patch is needed up to beaker v1.7.0

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/71c997e75ee6b8d7ae638dd8612d7b805e4eb523
