### ISSUE TITLE
UpdateManager

### ISSUE THREAD

**Issue by duffel90** [pyload/pyload#1332]
1103	07.04.2015 19:05:13	INFO	UpdateManager: No new pyLoad version available
1104	07.04.2015 19:05:13	INFO	UpdateManager: New version of plugin: [hoster] RemixshareCom (v0.03 -> v0.04)
1105	07.04.2015 19:05:14	INFO	UpdateManager: New plugin: [hoster] YadiSk (v0.02)
1106	07.04.2015 19:05:15	INFO	UpdateManager: New version of plugin: [internal] SimpleDereferer (v0.08 -> v0.10)
1107	07.04.2015 19:05:16	ERROR	UpdateManager: Error updating plugin: SimpleDereferer.py | Version mismatch
1108	07.04.2015 19:05:16	INFO	UpdateManager: New version of plugin: [internal] SimpleHoster (v1.33 -> v1.34)
1109	07.04.2015 19:05:16	ERROR	UpdateManager: Error updating plugin: SimpleHoster.py | Version mismatch
1110	07.04.2015 19:05:16	INFO	UpdateManager: *** Plugins updated ***

**Comment by vuolter** [comment]
Remove the userplugins folder and the accounts.conf in your config directory, then restart pyLoad.
