### ISSUE TITLE
[Question] What is purpose of getFileInfo and what it uses for

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1336]
also what is self.api_data?

**Comment by vuolter** [comment]
Old SimpleHoster based plugins use `getFileInfo` to retrieve file info. Deprecated by `getInfo`.
self.api_data should be removed, because check_data, api_data and info_data have been unified in self.info, but some hosters (and the Checksum addon) were not updated yet. :(

**Comment by GammaC0de** [comment]
Further to the question above, what is the purpose of `getInfo` and WHEN it gets called?
