### ISSUE TITLE
[ExtractArchive] Delete archive after extraction is broken

### ISSUE THREAD

**Issue by nordic-style** [pyload/pyload#1339]
Tested with 831f9d24ffa2ed11c21a78bb3fb4ec757e8d0ef9

Was working about a week ago.
I get this message:

```
...
10.04.2015 01:32:03 WARNING   ExtractArchive: Unable to move The.Package-1.part10.rar to trash
...
```

**Comment by vuolter** [comment]
Install this lib: https://pypi.python.org/pypi/Send2Trash
or set to False option "Move to trash (recycle bin) instead delete", but caution if option "Delete archive after extraction" is enabled.

**Comment by nordic-style** [comment]
thx :)

**Comment by Rafik89** [comment]
thx
