### ISSUE TITLE
[DepositfilesCom] plugin broken again

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1341]
After d984661 plugin is broken again.
`self.detectErrors()` successfully matches ` download_waiter_remain">60</span></td>` but fails to evaluate the time and so it does not wait.
Also, why have you removed the call to `self.correctCaptcha()`?

**Comment by vuolter** [comment]
correctCaptcha is called automatically when self.link is found and a captcha task is in progress.
