### ISSUE TITLE
[ExtractArchive] plugin does not save settings

### ISSUE THREAD

**Issue by pokrzys** [pyload/pyload#1347]
ExtractArchive plugin doesn't save settings. Every change is being restored to default after pyload restart.
Error occur with pyload for zyxel nsa325v2 if it makes any difference,

**Comment by Ghoststage** [comment]
Then change it in the ExtractArchive.py . So I 'm doing it and it goes without problems

**Comment by pokrzys** [comment]
Great! Now it works like a charm. 
Thank you kind Sir!
