### ISSUE TITLE
API doesn't accept arrays with multiple items

### ISSUE THREAD

**Issue by tredger** [pyload/pyload#1349]
The [api_app.py](https://github.com/pyload/pyload/blob/stable/module/web/api_app.py) routing regex doesn't allow for ',' in the query string. Its fairly minor as it will only affect parameters submitted in the query string, but means it returns a 404 when you try to supply an array/list parameter.

For API endpoints such as `deleteFiles` and `deletePackages` where the function name is pluralised, the expected behaviour is that the API should allow the deletion of multiple files in the same query. To fix this the routing regex just needs to be updated from:
```
@route("/api/:func:args#[a-zA-Z0-9\-_/\"'\[\]%{}]*#")
@route("/api/:func:args#[a-zA-Z0-9\-_/\"'\[\]%{}]*#", method="POST")
```
to
```
@route("/api/:func:args#[a-zA-Z0-9\-_/\"'\[\]%{},]*#")
@route("/api/:func:args#[a-zA-Z0-9\-_/\"'\[\]%{},]*#", method="POST")
```

**Comment by vuolter** [comment]
THX: https://github.com/vuolter/pyload/commit/57e450ef209f2a865dd579913e114534f0bb8851
