### ISSUE TITLE
send2trash not working on OSX

### ISSUE THREAD

**Issue by vicegold** [pyload/pyload#1351]
The integration of send2trash broke extracting archives on Mac OSX. 

send2trash is installed but not working. Because of that months old bug of "pluginsettings not saved" bug in pyLoad the option get's activated after every download again. So i can't turn it off. (Maybe it should be turned off by default?)

```22166 13.04.2015 12:40:32 ERROR ExtractArchive: test.part18.rar | Unknown error | global name 'send2trash' is not defined 
22167 13.04.2015 12:40:32 ERROR ExtractArchive: test.part18.rar | Extract failed```

The archives will be extracted, but not deleted and the hooks that would be called after extraction won't work because the extraction fails.

**Comment by wastez** [comment]
Yes, the same is on my system if send2trash is enabled.

**Comment by I-RiX-I** [comment]
Same here on Windows with python 2.7.9
