### ISSUE TITLE
premiumize.me hook not working - Required account not found

### ISSUE THREAD

**Issue by jbman11** [pyload/pyload#1354]
My premiumize me has stopped working.

I had an update and I have premiumizeme with and without the hook name

I have turned both on, tried one on and one off and still i am seeing that its not working

I have removed and added my account again and it says its valid

in the logs i see this

INFO	PremiumizeMeHook: Reloading supported hoster list

then when I try download something I see this

INFO	Download restarted: download.mp4 | Fallback to free download
INFO	Download starts: download.mp4
WARNING	Download failed: download.mp4 | Required account not found

As soon as I turn off the premiumizemehook plugin and try the download again, I get the capture prompt, enter the capture and the download begins

**Comment by jbman11** [comment]
I just went through and turned both premiumizeme plugs off, hook and the older one restarted, turned the hook version back on and it started it work

**Comment by vuolter** [comment]
@jbman11 What version do you use now?

**Comment by jbman11** [comment]
I haven't made any changes to versions etc. At first I wasn't aware of the new hook so I left the old plugin and the hook enabled which may have caused the issue.

After a few restarts and disabling and re-enabling the new hook version everything started to work again
