### ISSUE TITLE
serienjunkies deletes decrypted links

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#1359]
hey
serienjunkies.org plugin deletes the files after decrypting instead of readding the decrypted links to queue.
could you please take a quick look?

for example:
http://download.serienjunkies.org/f-7dcbf40d8309624c/ul_SCPG7P112.html

it's been for a few days now , i think.

thx

**Comment by vuolter** [comment]
Sorry, Serienjunkies is an un-official plugin and is not supported here, please try in the forum, where you should find its mantainer.
