### ISSUE TITLE
Real Debrid not working ?

### ISSUE THREAD

**Issue by tchoblond59** [pyload/pyload#1360]
I am using real debrid for uploaded and uptobox and pyload try to download them directly instead of passing by real debrid... 
Can anyone confirm if it's only me or not ?

If you need a real debrid account just give me your mail address
Thanks

**Comment by seegras3** [comment]
I can confirm this error, I wanted to download from uploaded.net over Real Debrid

I can also give you my real debrid account for testing purposes, just give me your mailadress

**Comment by byte4geek** [comment]
Hi, try to disable RealDebrid plugin and enable RealDebridHook plugin and try again, in this way work for me.

**Comment by seegras3** [comment]
This works for me, thanks for the Hint

**Comment by alienx2** [comment]
what's solution of this issue?

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/14d26e63c83a49fcafe8101d318f395a137b3906
