### ISSUE TITLE
EasyBytez: You have reached the download-limit: 600 Mb for last 1 days

### ISSUE THREAD

**Issue by smystero** [pyload/pyload#1368]
Hi everybody,
After an hour or two of continuously download I receive the following message in log: 
"You have reached the download-limit: 600 Mb for last 1 days".
Then download changes to "free user" mode.
After finishing the download everything stuck with "Waiting" message on queue.
To restart download (obviously at full speed), I need to stop/start pyload.
I have a EB premium account. I sent a message to EB, and they told me is not their fault.
What can be the problem? Do you need log?
Thank in advance.
S.

**Comment by erse80** [comment]
is the same problem reported in issue #1296
