### ISSUE TITLE
SimpleHoster - Known problems with Multihoster and for ex. Premium.to

### ISSUE THREAD

**Issue by acid112** [pyload/pyload#1374]
Hi, 

there is a problem with a lot of multihosters, you know.
Pyload can not read the filename.
The problem is within method (SimpleHoster.py):
   def download(self, url, get={}, post={}, ref=True, cookies=True, disposition=False):

here the line:
content = urllib2.urlopen(url).info()['Content-Disposition'].split(';')

urllib2 throws an exception (403, not allowed)
I think the problem is Cloudfare....

so pyload can not write the corrrect filename:
self.pyfile.name = (content[1].split('filename=')[1][1:-1]
                                    or urlparse.urlparse(urllib.unquote(url)).path.split('/')[-1]
                                    or self.pyfile.name)

replace urllib2 and everything is fine. :)
i did some tests with requests.url()...
there is no problem.

Please fix it.

**Comment by Mister-XY** [comment]
Oh thats look fine.

**Comment by acid112** [comment]
Ok, i did not change urllib2. I dont know how. and have no time for testing.

But i have a nice workaround for PremiumTo Users like you an me :).
Edit SimpleHoster.py in method:
 def download(self, url, get={}, post={}, ref=True, cookies=True, disposition=False):

and change this line:
 return super(SimpleHoster, self).download(url, get, post, ref, cookies, False)
to
 return super(SimpleHoster, self).download(url, get, post, ref, cookies, disposition)

Pyload refreshes then the filename while downloading the file.
So, the filename after download is correct und ExtractArchive has no problems.
I can live with this and i have downloaded a lot of packages yesterday from uploaded.to via premiumTo.
With my workaround for cookie-setting in accounts/premiumTo.py  everything works now.

**Comment by Mister-XY** [comment]
Via uploadet, is it correct, Tomorrow i will download with share-online to see how its look.

**Comment by Shuralon** [comment]
Thanks works fine also for rehost.to!

**Comment by Mister-XY** [comment]
@vuolter please add this to simplehoster.py
