### ISSUE TITLE
extractarchive issue

### ISSUE THREAD

**Issue by ananias47** [pyload/pyload#1378]
i have a problem it acts like it is disabled the plugin so nothing happens when downloaded finishes

its very strange

![screenshot 2015-04-26 20 11 37](https://cloud.githubusercontent.com/assets/6560173/7338306/acdb799e-ec50-11e4-906e-03037306d101.png)
![screenshot 2015-04-26 20 11 59](https://cloud.githubusercontent.com/assets/6560173/7338307/b41d59ac-ec50-11e4-9cb1-61f484b373ad.png)

**Comment by vuolter** [comment]
Please, provide a better explanation of the issue.

**Comment by DKeppi** [comment]
Same Problem here, download finished but no extracting is starting.
Nothing happens when download is finished!

Config is the same which ananias47 has!
There is no Error in the log!

**Comment by DKeppi** [comment]
Debug:

107	02.06.2015 12:12:54	INFO	Added package **** containing 2 links
108	02.06.2015 12:12:54	INFO	Download starts: ***.part2.rar
109	02.06.2015 12:12:54	DEBUG	UploadedTo: Update file info...
110	02.06.2015 12:12:54	DEBUG	UploadedTo: Previous file info: {}
111	02.06.2015 12:12:54	DEBUG	Finished Info Fetching for UploadedTo
112	02.06.2015 12:12:54	DEBUG	UploadedTo: Current file info: {'status': 2, 'url': u'http://uploaded.net/file/******', 'size': 601176210.0, 'name': u'******.part2.rar', 'pattern': {'ID': u'******b6'}}
113	02.06.2015 12:12:54	DEBUG	UploadedTo: File name: ******.part2.rar | File size: 601176210 byte
114	02.06.2015 12:12:54	DEBUG	UploadedTo: File status: online
115	02.06.2015 12:12:54	DEBUG	UploadedTo: Looking for direct download link...
116	02.06.2015 12:12:54	DEBUG	UploadedTo: Redirect #0 to: http://uploaded.net/file/*******
117	02.06.2015 12:12:55	DEBUG	UploadedTo: Redirect #1 to: http://am4-r1f1-stor03.uploaded.net/dl/61c4e3c1-********
118	02.06.2015 12:12:56	INFO	UploadedTo: Direct download link detected
119	02.06.2015 12:12:56	DEBUG	Content-Disposition: ******.part2.rar
120	02.06.2015 12:12:56	INFO	Download starts: *******.part1.rar
121	02.06.2015 12:12:56	DEBUG	UploadedTo: Update file info...
122	02.06.2015 12:12:56	DEBUG	UploadedTo: Previous file info: {}
123	02.06.2015 12:12:56	DEBUG	UploadedTo: Current file info: {'status': 2, 'url': u'http://uploaded.net/file/*******', 'size': 606129032.0, 'name': u'********.part1.rar', 'pattern': {'ID': u'p5j*****r'}}
124	02.06.2015 12:12:56	DEBUG	UploadedTo: File name: ******.part1.rar | File size: 606129032 byte
125	02.06.2015 12:12:56	DEBUG	UploadedTo: File status: online
126	02.06.2015 12:12:56	DEBUG	UploadedTo: Looking for direct download link...
127	02.06.2015 12:12:56	DEBUG	UploadedTo: Redirect #0 to: http://uploaded.net/file/******
128	02.06.2015 12:12:57	DEBUG	UploadedTo: Redirect #1 to: http://fra-7m22-stor10.uploaded.net/dl/902f469a-******
129	02.06.2015 12:12:57	INFO	UploadedTo: Direct download link detected
130	02.06.2015 12:12:57	DEBUG	Content-Disposition: ******.part1.rar
131	02.06.2015 12:14:49	INFO	Download finished: ******.rar
132	02.06.2015 12:14:52	INFO	Download finished: *****.part1.rar
133	02.06.2015 12:14:52	INFO	Package finished: ******
136	02.06.2015 12:14:53	DEBUG	All downloads processed
137	02.06.2015 12:14:53	DEBUG	All downloads finished



After that nothing happens - no extracting!
If i restart pyLoad, extracting starts....

**Comment by Walhalla360** [comment]
Is this issue still being worked on? It's driving me nuts! Everytime something other is not working after an update...
