### ISSUE TITLE
File name changed

### ISSUE THREAD

**Issue by SebaBoler** [pyload/pyload#1382]
When i start downloading file all its fine. After few second name file changed. First and last character disappears.

Log

  Code:
1015   18.04.2015 19:45:32   INFO   Package finished: http://catshare.net/xYBs2Bh9GqsfeGSL/Vikings.S03E09.PLSUBBED.HDTV.XviD-CAMBiO.avi
1014   18.04.2015 19:45:32   INFO   Download finished: ikings.S03E09.PLSUBBED.HDTV.XviD-CAMBiO.av
1013   18.04.2015 19:40:58   INFO   Download starts: Vikings.S03E09.PLSUBBED.HDTV.XviD-CAMBiO.avi
1012   18.04.2015 19:40:57   INFO   Added package http://catshare.net/xYBs2Bh9GqsfeGSL/Vikings.S03E09.PLSUBBED.HDTV.XviD-CAMBiO.avi containing 1 links

Before start was Vikings.S03E09.PLSUBBED.HDTV.XviD-CAMBiO.avi
after ikings.S03E09.PLSUBBED.HDTV.XviD-CAMBiO.av

**Comment by zapp-brannigan** [comment]
I've noticed that behavior in AndroidfilehostCom.py, too.
I think it is caused by SimpleHoster.py, there seems to be a issue with content-disposition.
