### ISSUE TITLE
Feature Request: [UploadedNet] Detect Maintenance Mode

### ISSUE THREAD

**Issue by I-RiX-I** [pyload/pyload#1383]
Please update the UploadedNet plugin so it detects uploaded maintenance mode.

Adding a timer to re-check indefinitely every 5 minutes or so might be necessary.

Else all links in the queue are skipped as offline and have to be restarted manually.

Here is the html code if Uploaded is in maintenance

http://paste2.org/OaBy4vZ6

EDiT: A check for the head title "uploaded.net - Maintenance - Wartungsarbeiten" should suffice, I guess..

**Comment by GammaC0de** [comment]
Hi,
Check #1385

**Comment by I-RiX-I** [comment]
Great stuff!
