### ISSUE TITLE
Click And Load not working when "Use HTTPS" for the Webinterface is activated

### ISSUE THREAD

**Issue by Michi-F** [pyload/pyload#1387]
This is a plugin issue with Click and Load:

When the option "Use HTTPS" for the Webinterface is activated (-> webserver: threaded for SSL support instead of builtin), Click and Load won't work.
Unfortunately, this setting also affects the Click and Load function, although Click and Load listens on a different Port (9666) than the webinterface (8000).

When the option is activated, Click and Load only accepts HTTPS requests. But almost all Click and Load requests connect with http://-ip-:9666/flash/, and not with https://-ip-:9666/flash/

The result is a "400 Bad Request" response from the Click and Load function to the client, Example:
Remote Address:-ip-:9666, Request URL:http://-ip-:9666/flash/addcrypted2
Status Code:400 Bad Request
Response: "The client sent a plain HTTP request, but this server only speaks HTTPS on this port."

-> "Use HTTPS" for the Webinterface should not affect Click and Load.
Click and Load should always listen to plain http requests on port 9666, regardless of whether the webinterface uses https or not.

Turning off "Use HTTPS" for the Webinterface and everything works fine, but that's not really a solution regarding security concerns.

Reproduce:
install pyload on debian (tested on Raspbian), activate SSL /  "Use HTTPS" Webinterface and try to add a link with click and load. (I can add an exact list of steps to reproduce if necessary)

**Comment by akfedux** [comment]
Can you append result this command?
dpkg -l *

**Comment by Michi-F** [comment]
I reproduced it on a new debian 8 installation, here is a complete list of all executed commands and the wget / dpkig results:

http://pastebin.com/0jpy6m2v
lines 3-136: commands & configuration to reproduce the pyload installation
lines 138 - 183: wget results
lines 186 - end: dpkg -l *

**Comment by milesbenson** [comment]
Is this fixed? I still cant get CNL to work when HTTPS is enabled.

My ssh tunnel looks like this:

ssh -L 9666:ip.of.pyload.machine:port.of.webif -l ssh-user -N ip.of.pyload.machine -p 22000 (as i dont use 22 for ssh)
