### ISSUE TITLE
Include Send2Trash for Precompiled Windows Version

### ISSUE THREAD

**Issue by I-RiX-I** [pyload/pyload#1391]
I lack the experience with python to set up Pyload without the precompiled windows package. (Read: the "real thing" with an independent pyload setup).

I do not have python installed and fail to implement send2trash in the compiled version.

Would it be possible to include the send2trash binaries in the pyload stable branch?

Or could someone help me in placing those binaries right..?

Thank you for the great effort put into this very feature.

**Comment by vuolter** [comment]
Already in 0.4.10
