### ISSUE TITLE
[Yadi.SK] import to freeaccount feature

### ISSUE THREAD

**Issue by sraedler** [pyload/pyload#1394]
If you have a yadi.sk account (even for free), you can import the downloadable file to your account.
If you did this, you can download it even faster.

If you wanna see this feature, checkout jDownloader...

**Comment by Velociraptor85** [comment]
http://yadi.sk/ redirects to https://disk.yandex.com/

**Comment by GammaC0de** [comment]
yadi is short for yandex

**Comment by Velociraptor85** [comment]
so is this covered by this https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/YadiSk.py hoster plugin?

**Comment by GammaC0de** [comment]
Yes, if not it should,
the plugin was not updated for a long time..

**Comment by Velociraptor85** [comment]
@sraedler can you test this ? and report back?
