### ISSUE TITLE
disable Linkdecrypter for serienjunkies.org ?

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#1397]
hey. i know, serienjunkies.org plugin is not supported
but one of the forum users told me that the problem with the not working serienjunkies.org plugin is, that one of the last linkdecrypter updates broke it. so he said linkdecrypter should ignore the domain serienjunkies.org .. and since Linkdecrypter.com is officially supported, i thought you maybe could take a look? would be awesome.

thank you so much!

**Comment by vuolter** [comment]
Okay, I fix it tomorrow. ;)
