### ISSUE TITLE
error while runtime

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1398]
When pyLoad runs for 3-4 hours i get this error.

`06.05.2015 15:47:34    ERROR   Error executing hooks: [Errno 5] Input/output error`

after it i cant start add or do something with pyload.
i have to restart pyload.
any glue where this comes from?

**Comment by vuolter** [comment]
Full debug log, please.

**Comment by Velociraptor85** [comment]
@Gutz-Pilz closing since the Issue is from 2015 and no logs where given
