### ISSUE TITLE
Shareonline.biz plugin issue with  "Penalty-Premium" state

### ISSUE THREAD

**Issue by chipotng** [pyload/pyload#1403]
module/plugins/accounts/ShareonlineBiz.py:

- 43  premium = api['group'] in ["Premium", "PrePaid"]
+ 43 premium = api['group'] in ["Premium", "PrePaid", "Penalty-Premium"]

+ 49             trafficleft = maxtraffic - traffic --> if this gets to/below 0 pyload switches to "Free Mode" with asking for Captchars blocking the Queue. Even if I'm still "Penalty-Premium" what just means decreased Downloadspeed.

**Comment by vuolter** [comment]
Please, retry now.
