### ISSUE TITLE
Wrong file name with onefichiercom account

### ISSUE THREAD

**Issue by nic27** [pyload/pyload#1413]
Hi all,

the file name of the downloaded file is wrong when using a premiun account of onefichiercom.

When I try to download without the premium account (account deleted from account list) the file name is correct.

I also try to delete the plugin and accound.conf but wihout effect...

Every plugins are up-to-date

Thanks for your help

**Comment by djgreg13** [comment]
![capture d ecran 2015-03-28 a 17 32 49](https://cloud.githubusercontent.com/assets/3840229/7665552/d7c8d720-fbbc-11e4-9384-2eca0df61f8c.png)
Check this box solve problem

**Comment by Velociraptor85** [comment]
@GammaC0de might close this too?

**Comment by GammaC0de** [comment]
Duplicate of #2918
