### ISSUE TITLE
[OneFichierCom] SSL Timeout

### ISSUE THREAD

**Issue by djgreg13** [pyload/pyload#1414]
I have only the first query to OneFichier with success, but all another failed with SSL timeout, restart pyload not solve problem, i must wait before can relogin to OneFichierCom

```
14.05.2015 08:35:06 WARNING   OneFichierCom: Could not login with account login@gmail.com | (28, 'SSL connection timeout at 28690')
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/Account.py", line 82, in _login
    self.login(user, data, req)
  File "/usr/share/pyload/module/plugins/accounts/OneFichierCom.py", line 55, in login
    decode=True)
  File "/usr/share/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 203, in load
    self.c.perform()
error: (28, 'SSL connection timeout at 28690')
```

Edit1 : I try to connect with another hoster, no problem, FourSharedCom login and download successful.

Only OneFichierCom crash

**Comment by djgreg13** [comment]
A verbose of curl

```
* About to connect() to 1fichier.com port 443 (#0)
*   Trying 5.39.224.140...
* connected
* Connected to 1fichier.com (5.39.224.140) port 443 (#0)
* found 159 certificates in /etc/ssl/certs/ca-certificates.crt
* SSL connection timeout at 27471
* Closing connection #0
```

**Comment by vuolter** [comment]
Reminder (for me): change curl.ssl in 0.4.10 to include all ssl and tls version + mega.co.nz cert

**Comment by djgreg13** [comment]
How do you do this ?

Gregory G

**Comment by djgreg13** [comment]
Exact, 1fichier uses SSLv3

**Comment by djgreg13** [comment]
Seems to be a performance problem with gnutls, it's very long to check root CA and timeout, i try it on bigger connection (1Gbit/s symmetric), it's works fine.

the problematic connection is a ADSL 10Mbits/1Mbits.

**Comment by jpedraza80** [comment]
Changing connection timeout show a new error:
gnutls_handshake() failed: A TLS packet with unexpected length was received

possible work around: you must recompile libcurl with OpenSSL (tested on Raspbian)
from http://stackoverflow.com/questions/9715160/python-pycurl-giving-for-soap-error-of-gnutls
 
sudo apt-get install build-essential
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install python-dev

wget http://curl.haxx.se/download/curl-7.26.0.tar.gz
wget http://pycurl.sourceforge.net/download/pycurl-7.19.0.tar.gz
tar -xzvf pycurl-7.19.0.tar.gz
tar -xzvf curl-7.26.0.tar.gz
cd curl-7.26.0/
./configure --with-ssl
make
sudo make install
cd ../pycurl-7.19.0/
sudo python setup.py install

sudo ldconfig

**Comment by djgreg13** [comment]
OK, i have make deb package of pycurl with openssl and it's work, thanks
