### ISSUE TITLE
[ExtractArchive] Move to Trash config doesn't stick

### ISSUE THREAD

**Issue by chaosmaker** [pyload/pyload#1417]
So on my synology system I don't have Send2Trash besides I don't even want to use it. So in the configuration I set "Move to trash (recycle bin) instead delete:" to false, however after a pyload restart this option goes back to True. 

And what's more annoying, if it is meant to delete, and it tries to the pyload webinterface crashes. So if I download anything as an archive - my other downloads finish but I have no access to the webinterface until I restart pyload.

**Comment by Kap0** [comment]
It also happens just not if you restart, I think it also happens if anything gets updated.

**Comment by GammaC0de** [comment]
Fixed long ago.
