### ISSUE TITLE
[Android client] Apk no longer available in Playstore

### ISSUE THREAD

**Issue by zapp-brannigan** [pyload/pyload#1422]
See forum: http://forum.pyload.org/viewtopic.php?f=9&t=342&start=50#p18009
The client is no longer available in Playstore. Maybe you can set up a mirror?

**Comment by TodsDeath** [comment]
You can get it from F-Droid:
https://f-droid.org/repository/browse/?fdid=org.pyload.android.client

**Comment by vuolter** [comment]
@TodsDeath :+1:

**Comment by timofonic** [comment]
Latest release is from 2013 in Fdroid.

What happened?

What about standalone PyLoad for Android?

**Comment by ChriZathens** [comment]
Fwiw, I am using pyload remote for many years but lately fails to connect to my server .
I assume some kind of incompatibility with nugat?
I have a nexus 5X and android 7.1.2

Anyone else with this problem or is it just me?

**Comment by GammaC0de** [comment]
I have tested this on OnePlus 3 and Android 7.1.1 with no issues.

**Comment by h4de5** [comment]
F-droid took the apks offline a while ago. I haven't found a reliable source for the compiled version since then.

**Comment by tod31** [comment]
@h4de5 https://web.archive.org/web/20161208121718/https://f-droid.org/repo/org.pyload.android.client_19.apk

**Comment by ChriZathens** [comment]
@GammaC0de: Don't know what's wrong...
I tried uninstalling and reinstalling but still the same. The app opens but I keep getting "Lost connection please try to refresh"
My settings are the same that were working for years.

**Comment by GammaC0de** [comment]
Does thi happen right after you try to connect or after a while?
Try to use tcpdump on the server and check if you can see something.
