### ISSUE TITLE
[Nitroflare] "The captcha wasn't entered correctly"

### ISSUE THREAD

**Issue by immenz** [pyload/pyload#1423]
Every download from nitroflare fails with "The captcha wasn't entered correctly"

Couldn't see any changes in the website, only that the captchas are often fotos. But in Pyload only text-captchas are shown.

Sample File http://nitroflare.com/view/186EE2DDDF0F997/sampePW.rar

**Comment by vuolter** [comment]
Do you spot that kind of issue in any other xfshoster based plugin?

**Comment by immenz** [comment]
I haven't downloaded from any other hoster than uploaded and nitroflare, so I couldn't say.
But I don't see that nitroflare is xfshoster based.

**Comment by zapp-brannigan** [comment]
I will take a look at this.
