### ISSUE TITLE
ShareonlineBiz  | list index out of range 

### ISSUE THREAD

**Issue by B0yman** [pyload/pyload#1424]
I wanted to download files by the hoster share-online.biz but the download doesnt start. 
In the logfile i saw this Error "Info Fetching for ShareonlineBiz failed | list index out of range".
What i have to do?

**Comment by GammaC0de** [comment]
@vuolter please add captcha|ShareonlineBiz.py to blacklist.txt. other than that I cannot reproduce the issue.
@B0yman can you supply the effected url please?

```
24.05.2015 16:09:11 ERROR     Error importing ShareonlineBiz: No module named captcha
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/usr/share/pyload/module/plugins/captcha/ShareonlineBiz.py", line 20, in <module>
    from captcha import OCR
ImportError: No module named captcha
```

**Comment by vuolter** [comment]
@GammaC0de Your captcha/ShareonlineBiz.py is out of date. :(

**Comment by GammaC0de** [comment]
@vuolter apparently http://updatemanager.pyload.org/?v=0.4.9 does not include `captcha|ShareonlineBiz.py` nor `captcha|*`, so I did not get these updates (in fact my userplugins/captcha is empty)

**Comment by vuolter** [comment]
@GammaC0de Please, open an issue report here: https://github.com/pyload/updatemanager/issues ;)
