### ISSUE TITLE
unrar_finished script not executed

### ISSUE THREAD

**Issue by EikeKre** [pyload/pyload#1429]
Hey guys!
First of all: thanks for this great tool!
I want to install the following script in ~/.pyloas/scripts/unrar_finished https://code.google.com/p/pyload-runscript/ but it is never executed but the archives get unzipped correctly.
I've already restarted pyload.
Even a simple testscript with echo "test"> /tmp/test does not create the testfile. The permissions should not be the problem as they are 777.

Thanks in advance

**Comment by GammaC0de** [comment]
Hi,
I think that `unrar_finished` is deprecated and you should use `archive_extracted` instead.
see http://forum.pyload.org/viewtopic.php?f=7&t=4181

**Comment by EikeKre** [comment]
Thanks, that was the problem!
