### ISSUE TITLE
YoutubeCom plugin functionality

### ISSUE THREAD

**Issue by PerDeDor** [pyload/pyload#1433]
Hello,
I would like to ask if YoutubeCom works fine at Pyload right now. Because it gives this error:

failed 'NoneType' object has no attribute 'group' 0.00 B

Thanks for answer

**Comment by GammaC0de** [comment]
@PerDeDor please send sample problematic url & logs

**Comment by PerDeDor** [comment]
I happens for me for every youtube video that I have tried. Here is an example from log.

1031	30.05.2015 21:49:16	INFO	Added package gympl containing 1 links
1032	30.05.2015 21:49:16	INFO	Download starts: https://www.youtube.com/watch?v=p5YDzxao4vE
1033	30.05.2015 21:49:17	WARNING	Download failed: https://www.youtube.com/watch?v=p5YDzxao4vE | 'NoneType' object has no attribute 'group'
1034	30.05.2015 21:49:17	INFO	Debug Report written to debug_YoutubeCom_30-05-2015_21-49-17.zip
1035	30.05.2015 21:49:17	INFO	UnSkipOnFail: look for skipped duplicates for watch?v=p5YDzxao4vE (pid:148)...
1036	30.05.2015 21:49:17	DEBUG	All downloads processed

**Comment by GammaC0de** [comment]
@PerDeDor have you enable debug mode? if not please do so and then resend the log
also, which OS are you running pyload?

**Comment by PerDeDor** [comment]
I use pyload at my NAS - Zyxel NSA310 and I have debug mode enabled. I could send you debug report in PM if you wish, because is quite long text file to post it here.

**Comment by GammaC0de** [comment]
you can compress the text file and upload it to http://tempsend.com/

**Comment by PerDeDor** [comment]
It's not that big to compress it :), link is here
http://tempsend.com/759C67C83D

**Comment by GammaC0de** [comment]
I see you are using plugin version 0.40 while 0.41 is the latest...

**Comment by GammaC0de** [comment]
which is seems to be exactly what was fixed in 0.41 (see http://forum.pyload.org/viewtopic.php?f=12&t=3974)

**Comment by PerDeDor** [comment]
Thanks much! I haven't noticed that my pyload wasn't set up to look up for updates automatically.

**Comment by GammaC0de** [comment]
:+1:
