### ISSUE TITLE
Recaptcha with Picture choice at Filecrypt.cc doesn't work

### ISSUE THREAD

**Issue by j4m** [pyload/pyload#1434]
The Recaptcha Version from Filecrypt.cc asks to choose Pictures which match to a given word.

Unfortunately Pyload only asks for an written answer (not clickable).

Example:
http://filecrypt.cc/Container/CFA7CB26FB.html

**Comment by zapp-brannigan** [comment]
@vuolter 
Try this url with JD2 and see what happens...
I think we should abandon recaptcha2 support :(

**Comment by vuolter** [comment]
No solution for now. I have to rewrite the captcha handler. u_u

**Comment by NETHeader** [comment]
Maybe it would be a solution to open the captcha page in a new tab?

Have a look at  https://support.jdownloader.org/index.php?/Knowledgebase/Article/View/42/3/JD-opens-my-browser-to-display-captchas

**Comment by GammaC0de** [comment]
See #2268
