### ISSUE TITLE
Uplea plugin doesn't work

### ISSUE THREAD

**Issue by doudz** [pyload/pyload#1435]
Trying to download a file from uplea give the following error 

Parse error: No file info retrieved | Plugin may be out of date 0.00 BUpleaCom
example for http://uplea.com/dl/91AF915F2AFE539

**Comment by GammaC0de** [comment]
Hi,

Which version of UpleaCom.py plugin are you using?
For me http://uplea.com/dl/91AF915F2AFE539 is working fine...

**Comment by vuolter** [comment]
@doudz Try setting "Load listed crypters only" to False in XFileSharingPro plugin
