### ISSUE TITLE
EasyBytez waiting for long time

### ISSUE THREAD

**Issue by gsasch** [pyload/pyload#1441]
I've premium account, but some part will go in wait for hours and hours:

xpart.part015.rar	attesa	aspetta 12:47:22	251.00 MiB	0% / 0 B

I have to cancel the download to start next 3 (or how many i configured) part correctly, one of these will be in waiting again

could you verifify what's break this out?

thanks

**Comment by vuolter** [comment]
Debug log please.

**Comment by vuolter** [comment]
No log, no fun.

**Comment by Stufo76** [comment]
I have same issue, below debug log:

15.07.2015 10:50:06 DEBUG     EasybytezCom[116]: {'op': 'upload_result', 'fn': 'INT3RST3LL4R.14.BD.DDN.part105.rar', 'st': "You've used all Leech traffic today"}

I have premium Easybytez account, with unlimited and unmetered traffic.

**Comment by Stufo76** [comment]
It seems to be similar to #849

**Comment by vuolter** [comment]
Fixed by last patch bomb. :bomb:
