### ISSUE TITLE
webshare.cz not working

### ISSUE THREAD

**Issue by xDereCx** [pyload/pyload#1446]
hi getting error message with webshare.cz plugin,
failed'NoneType' object is not callable 953.67 MiBWebshareCz
link is allright, working without a problem from browser.

thx

**Comment by xDereCx** [comment]
sry mate still getting errors, tryed to make debug log but there is nothin special, maybe this helps
02.06.2015 18:35:52 ERROR     Error importing WebshareCz: No module named passlib.hash
02.06.2015 18:35:52 CRITICAL  'NoneType' object is not callable

**Comment by vuolter** [comment]
Install passlib: https://pypi.python.org/pypi/passlib/1.6.2

**Comment by xDereCx** [comment]
sry, mabe i missed that in dependencies, installed however another error appeared
1	02.06.2015 20:29:53	DEBUG	Error creating zip file: [Errno 2] No such file or directory: 'tmp/WebshareCz'
2	02.06.2015 20:29:53	INFO	Debug Report written to debug_WebshareCz_02-06-2015_20-29-53.txt
3	02.06.2015 20:29:53	INFO	UnSkipOnFail: Looking for skipped duplicates of: http://webshare.cz/file/4o5r53sr6W/ (pid:35)
4	02.06.2015 20:29:53	INFO	UnSkipOnFail: No duplicates found 

hope debug will help
http://paste.ubuntu.com/11526766/

**Comment by vuolter** [comment]
Please, retry now.

**Comment by xDereCx** [comment]
working now, thank you mate
