### ISSUE TITLE
ERROR	PremiumizeMeHook: No hoster loaded

### ISSUE THREAD

**Issue by jbman11** [pyload/pyload#1450]
I am seeing this in my logs

INFO	PremiumizeMeHook: Reloading supported hoster list
WARNING	PremiumizeMeHook: Fallback to default reload interval due plugin parse error
ERROR	PremiumizeMeHook: No hoster loaded

This happens over and over again in my logs
In account settings my account is listed as valid

**Comment by vuolter** [comment]
Ful debug log please.

**Comment by jbman11** [comment]
INFO	PremiumizeMeHook: Reloading supported hoster list
DEBUG	PremiumizeMeHook: (35, 'gnutls_handshake() failed: A TLS fatal alert has been received.') | Waiting 1 minute and retry

**Comment by vuolter** [comment]
Checking...
