### ISSUE TITLE
account plugins without hoster plugins

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1458]
Hi,
These account plugins exists on the git repository without corresponding hoster plugins:
```
accounts/BackinNet.py
accounts/FileParadoxIn.py
accounts/JunkyvideoCom.py
accounts/LinestorageCom.py
accounts/RyushareCom.py
accounts/SendmywayCom.py
accounts/WorldbytezCom.py
```

**Comment by vuolter** [comment]
Used by: https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/XFileSharingPro.py
