### ISSUE TITLE
Easybytez IP_BLOCKED_PATTERN

### ISSUE THREAD

**Issue by ilteoood** [pyload/pyload#1465]
From the log:
WARNING	Download failed: *** | 'EasybytezCom' object has no attribute 'IP_BLOCKED_PATTERN'
No way to finish any download with this hoster

**Comment by mhoeschele** [comment]
This seems to be a general problem for lots of plugins (ShareOnlineBiz, etc) and occurs for me since 3af8bfcf685f82de097ef6b110dffa77fd529eaf

**Comment by Web-Eye** [comment]
this happens for uploaded.to too

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/a8c8ace5ee4868f58067c8af30ea5702a2434999
