### ISSUE TITLE
Error share-online Plugin

### ISSUE THREAD

**Issue by Klaaner** [pyload/pyload#1470]
After a download finished, the status of the file is an error, but the file ist downloaded correctly:

'ShareonlineBiz' object has no attribute 'IP_BLOCKED_PATTERN'

That happens since the update ShareonlineBiz (v0.51 -> v0.52)

**Comment by vuolter** [comment]
Your SimpleHoster plugin is out-of-date.

**Comment by Klaaner** [comment]
Indeed, now the update for SimpleHoster has come:

New version of plugin: [internal] SimpleHoster (v1.61 -> v1.65)
New version of plugin: [internal] SimpleCrypter (v0.51 -> v0.52)

Thank you.
