### ISSUE TITLE
External script package finished

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#1475]
Hello, is it possible that only the in external script the package_finished folder work with script?
I have also copy the script into the Folder package_extracted and to test in archive_extrackted and pyload load on start the script but if an download is extracted, the scripts did not run. Only the Script in Package_finished did run.

**Comment by nomad71** [comment]
Can confirm, neither package_extracted nor archive_extracted were executed.

**Comment by kasperj** [comment]
Same here, hope there will be a fix soon!
