### ISSUE TITLE
some events not working anymore

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1490]
Further to #1482:
Apparently, after https://github.com/pyload/pyload/commit/9f3ab57ec994deb24cd31a1dfbd338eb71bffc8c, other modules are surely effected.
Hook manager checks for `event_list` declaration on the constructor so setting it on `setup` is too late and would not set a hook.

**Comment by vuolter** [comment]
Working on...

**Comment by GammaC0de** [comment]
:+1:
