### ISSUE TITLE
global name 'decode' is not defined

### ISSUE THREAD

**Issue by georg94** [pyload/pyload#1492]
After the new update pyload isn't working properly anymore. There is an error that says `NameError: global name 'decode' is not defined`

Obviously it gets called periodically and spams into the log
```
Traceback (most recent call last):
  File "/home/pi/.pyload/userplugins/internal/MultiHook.py", line 178, in _periodical
    self.periodical()
  File "/home/pi/.pyload/userplugins/internal/MultiHook.py", line 190, in periodical
    self.loadAccount()
  File "/home/pi/.pyload/userplugins/internal/MultiHook.py", line 92, in loadAccount
    self.logWarning("Hook plugin will be deactivated due missing account reference")
  File "/home/pi/.pyload/userplugins/internal/Plugin.py", line 79, in logWarning
    return self._log("warning", args)
  File "/home/pi/.pyload/userplugins/internal/Plugin.py", line 63, in _log
    str(a)).strip() for a in args if a)
  File "/home/pi/.pyload/userplugins/internal/Plugin.py", line 63, in <genexpr>
    str(a)).strip() for a in args if a)
```

Another Problem is that some Hooks are broken but I'll open another issue for that...

**Comment by georg94** [comment]
In commit ea27af decode gets included in the `Plugin.py` file, but not anymore included in the `SimpleHoster.py`. Was that intended? (I don't see that decode is ever used in `Plugin.py`)

**Comment by obli88** [comment]
decode is used in line 63 of Plugin.py.

**Comment by georg94** [comment]
I don't see the usage of decode in line 63,
```
        log("%(plugin)s[%(id)s]: %(msg)s" % {'plugin': self.__name__,
```

**Comment by nomad71** [comment]
Get the same error on every single file (share-online.biz free)...

Get the debug files here:

http://www43.zippyshare.com/v/OGW1Hizd/file.html

**Comment by obli88** [comment]
My bad. During the updates I had a version where the import off decode was missing but there was still this line:

        msg = " | ".join((fs_encode(a) if isinstance(a, unicode) else  #@NOTE: `fs_encode` -> `encode` in 0.4.10
                          decode(a) if isinstance(a, str) else
                          str(a)).strip() for a in args if a)

That caused the error for me. After I cloned the whole repo again I just have trouble with some hooks like mentioned in another issue.

**Comment by georg94** [comment]
As a workaround I "disabled" the _log function, now the hooks are working again and there are no errors :smile: 
```
    # Log functions
    def _log(self, level, args):
        return
```

**Comment by vuolter** [comment]
I'm really sorry guys, I fixed the _log issue after the first report hours ago, but was not able to send the fix until now.

**Comment by nomad71** [comment]
Thanks anyway!
