### ISSUE TITLE
ExternalScripts fails with a warning it cannot start since Plugin plugin v0.06 and pyload doens't shut down gracefully

### ISSUE THREAD

**Issue by chaosmaker** [pyload/pyload#1494]
Hi all, 

Today SimpleHoster and Plugin plugin were updated on my pyload version. Since then ExternalScripts shows up with a warning that it cannot start:

```
14.06.2015 20:25:54 WARNING   Failed activating ExternalScripts
```

In addition when I try and shut down pyload it doesn't shut down gracefully anymore and a kill signal needs to be send. 

Thanks

**Comment by jbman11** [comment]
I am seeing the same issue
304	15.06.2015 06:59:40	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
305	15.06.2015 06:59:40	WARNING	Failed activating ExternalScripts
