### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by jbman11** [pyload/pyload#1499]
WARNING	Download failed: testfile | maximum recursion depth exceeded while calling a Python object
DEBUG	Error creating zip file: [Errno 2] No such file or directory: 'tmp/RapidgatorNet'
INFO	Debug Report written to debug_RapidgatorNet_15-06-2015_15-32-48.txt
DEBUG	All downloads processed

**Comment by jbman11** [comment]
PYFILE OBJECT DUMP: 

	               _size = 227163504
	               abort = False
	              active = False
	               error = 'maximum recursion depth exceeded while calling a Python object'
	                  id = 25
	                lock = <_RLock owner=None count=0>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x16fa9b8>
	         maxprogress = 100
	                name = u’removed’
	               order = 0
	           packageid = 24
	              plugin = <userplugins.hoster.PremiumizeMe.PremiumizeMe object at 0x1b274d0>
	         pluginclass = <class 'userplugins.hoster.PremiumizeMe.PremiumizeMe'>
	        pluginmodule = <module 'userplugins.hoster.PremiumizeMe' from '/home/pi/.pyload/userplugins/hoster/PremiumizeMe.pyc'>
	          pluginname = u'RapidgatorNet'
	            progress = 0
	         reconnected = False
	                size = 227163504
	              status = 8
	          statusname = None
	                 url = u’removed’
	           waitUntil = 0


CONFIG: 

{'desc': 'RapidgatorNet',
 'outline': 'Rapidgator.net hoster plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': True}}

**Comment by mchwalisz** [comment]
I can also confirm that:

```
15.06.2015 07:46:11 INFO      Download starts: pd.rar
15.06.2015 07:46:11 WARNING   Download failed: pd.rar | maximum recursion depth exceeded while calling a Python object
```

repeats for every file.

**Comment by Mister-XY** [comment]
same here.

**Comment by seppi91** [comment]
same on zippyshare 

650	15.06.2015 09:17:55	INFO	Download starts: xxx.part06.rar
651	15.06.2015 09:17:55	WARNING	Download failed: xxx.part06.rar | maximum recursion depth exceeded while calling a Python object
652	15.06.2015 09:17:55	INFO	UnSkipOnFail: Looking for skipped duplicates of: xxx.part06.rar (pid:1069)
653	15.06.2015 09:17:55	INFO	UnSkipOnFail: No duplicates found

**Comment by chaosmaker** [comment]
Same here with a real-debrid account/link/whatever

**Comment by Klaaner** [comment]
Same on share-online.biz

**Comment by vuolter** [comment]
Same as https://github.com/pyload/pyload/issues/1500
Please take a look at this and... sorry! ;(
