### ISSUE TITLE
pyload meltdown after updating plugin

### ISSUE THREAD

**Issue by grapemix** [pyload/pyload#1500]
My pyload instance is completely non-functional after updating plugin. At the beginning, when I browse into the log page to check what is wrong. At backtrace is shown instead of regular web page. 
The backtrace point me to: module/plugins/internal/Account.py:112

Then I clear my /etc/pyload/accounts.conf and then tried to re-added my account. This time, backtrace is gone, when I added my account. An 'error request' bubble is shown. When I go to the log page, I saw:

Error executing hooks: 'UnSkipOnFail' object has no attribute 'pyfile'

I suspect the above error is caused by:

https://github.com/pyload/pyload/commit/71d5584e82050a66aa5306ce99e43e7cbc3a62a7

around 8 hrs ago.

I am sorry I can't give the dev more detail.

**Comment by Stufo76** [comment]
Same error and same log, too!

**Comment by vuolter** [comment]
Sorry guys, pyLoad is okay now but for some hours a bad update was on the air yesterday...
Thy this please: http://forum.pyload.org/viewtopic.php?f=10&t=4335

**Comment by grapemix** [comment]
Sorry for the late reply. After following the instruction in  http://forum.pyload.org/viewtopic.php?f=10&t=4335 and restarting pyload a few times, everything is working. Thx, @vuolter

**Comment by vuolter** [comment]
I'm glad to read that all goes fine. Next big update will shake the earth! :earth_africa:
