### ISSUE TITLE
Real Debrid Account doesn't work

### ISSUE THREAD

**Issue by chaosmaker** [pyload/pyload#1501]
Hi All,

After yesterdays meltdown with the Plugin plugin, and me forcing a plugin re-download everything started working again except the real debrid account which now throws me the following error:

```
15.06.2015 10:27:56 DEBUG     RealdebridCom: Scheduled Account refresh for xxxx in 0 seconds.
15.06.2015 10:27:56 DEBUG     RealdebridCom: Get Account Info for xxxx
15.06.2015 10:27:56 DEBUG     RealdebridCom: Account Info: {'error': "local variable 'xml' referenced before assignment"}
```

Any idea whats wrong?

Thanks

**Comment by msfabxda** [comment]
I had the same problem as a temporary fix I changed these lines in "module/plugins/accounts/RealdebridCom.py"  
[CODE]xmld = xml.dom.minidom.parseString(html)
  account_info = {"validuntil": float(xmld.getElementsByTagName("expiration")[0].childNodes[0].nodeValue),
                        "trafficleft": -1, "premium": True} [/CODE]

**Comment by chaosmaker** [comment]
Great that works but now I have the maximum recursion depth error as specified in #1499
