### ISSUE TITLE
Error executing hooks: 'UnSkipOnFail' object has no attribute 'pyfile'

### ISSUE THREAD

**Issue by Misaal** [pyload/pyload#1505]

**Comment by vuolter** [comment]
http://forum.pyload.org/viewtopic.php?f=7&t=4335

**Comment by 1337sup3rh4x0r** [comment]
worked for me, thanks! 

Maybe the forum post could be edited to take users' concern by mentioning that all plugin settings, even the custom plugin ones', are kept even if the plugin is deleted and added back later.

**Comment by vuolter** [comment]
@1337sup3rh4x0r I'll do. Thanks for the tip.
