### ISSUE TITLE
Error executing hooks

### ISSUE THREAD

**Issue by Misaal** [pyload/pyload#1506]
Error executing hooks: 'XFileSharingPro' object has no attribute 'pyfile' 
Error executing hooks: 'LinkdecrypterComHook' object has no attribute 'pyfile'

**Comment by vuolter** [comment]
http://forum.pyload.org/viewtopic.php?f=7&t=4335

**Comment by Stufo76** [comment]
Error executing hooks: 'AndroidPhoneNotify' object has no attribute 'key'
Impossibile attivare ExternalScripts
Error executing hooks: 'XFileSharingPro' object has no attribute 'pyfile'
Error executing hooks: 'LinkdecrypterComHook' object has no attribute 'pyfile'

Debian GNU/Linux 7.8 (wheezy) x64
Python 2.7.3

**Comment by vuolter** [comment]
Checking...

**Comment by Stufo76** [comment]
I tried restoring plugins (http://forum.pyload.org/viewtopic.php?f=7&t=4335) and all about this issue is ok.
But now I found new issue #1507
