### ISSUE TITLE
Real-Debrid account not working

### ISSUE THREAD

**Issue by TodsDeath** [pyload/pyload#1512]
Follow up to #1501 
The provided fix is not working, plugin is up-to-date (0.47). Still getting
```DEBUG	RealdebridCom: Account Info: {'error': "local variable 'xml' referenced before assignment"}```
Renaming variable xml to anything else as suggested in https://github.com/pyload/pyload/issues/1501#issuecomment-112007615 works

**Comment by vuolter** [comment]
Fix is coming...
