### ISSUE TITLE
[ExtractArchive] doesn't keep settings

### ISSUE THREAD

**Issue by Stufo76** [pyload/pyload#1513]
I changed some ExtractArchive plugin settings, and it's successfully applied and writed into plugin.conf file.
But, when pyLoad restarted, settings reverted back to defaults (plugin.conf file overwritten with default ExtractArchive settings).

Debian GNU/Linux 7.8 (wheezy) x64
Python 2.7.3
pyLoad 0.4.9

**Comment by vuolter** [comment]
Could you post a sample setting you changed?

**Comment by Stufo76** [comment]
Settings changed:
ExtractArchive - "ExtractArchive":
        bool deltotrash : "Move to trash (recycle bin) instead delete" = False
        bool repair : "Repair broken archives (RAR required)" = True
        bool usepasswordfile : "Use password file" = True
        bool recursive : "Extract archives in archives" = True
        bool keepbroken : "Try to extract broken archives" = True
        bool subfolder : "Create subfolder for each package" = False
        folder destination : "Extract files to folder" =
        bool activated : "Activated" = True
        bool waitall : "Run after all downloads was processed" = False
        str excludefiles : "Don't extract the following files" = *.nfo,*.DS_Store,index.dat,thumb.db
        str extensions : "Extract archives ending with extension" = 7z,bz2,bzip2,gz,gzip,lha,lzh,lzma,rar,tar,taz,tbz,tbz2,tgz,xar,xz,z,zip
        int renice : "CPU priority" = 19
        bool test : "Test archive before extracting" = False
        file passwordfile : "Password file" = unrar_passwords.txt
        bool fullpath : "Extract with full paths" = True
        bool delete : "Delete archive after extraction" = True
        bool overwrite : "Overwrite files" = True

Original settings reverted back on pyLoad restart:
ExtractArchive - "ExtractArchive":
        bool deltotrash : "Move to trash (recycle bin) instead delete" = True
        bool repair : "Repair broken archives (RAR required)" = False
        bool usepasswordfile : "Use password file" = True
        bool recursive : "Extract archives in archives" = True
        bool keepbroken : "Try to extract broken archives" = False
        bool subfolder : "Create subfolder for each package" = False
        folder destination : "Extract files to folder" =
        bool activated : "Activated" = True
        bool waitall : "Run after all downloads was processed" = False
        str excludefiles : "Don't extract the following files" = *.nfo,*.DS_Store,index.dat,thumb.db
        str extensions : "Extract archives ending with extension" = 7z,bz2,bzip2,gz,gzip,lha,lzh,lzma,rar,tar,taz,tbz,tbz2,tgz,xar,xz,z,zip
        int renice : "CPU priority" = 19
        bool test : "Test archive before extracting" = False
        file passwordfile : "Password file" = unrar_passwords.txt
        bool fullpath : "Extract with full paths" = True
        bool delete : "Delete archive after extraction" = True
        bool overwrite : "Overwrite files" = True

**Comment by vuolter** [comment]
Okay, I'll have a look at these soon as possible.

**Comment by Stufo76** [comment]
Thank you @vuolter happy to help if I can

**Comment by Stufo76** [comment]
This issue seems to be related to #1157

**Comment by Eisfreak7** [comment]
I still have the same problem (for a while now, I don't know why #1157 got closed, it's not fixed for me). I had it when I was running pyload on my Ubuntu desktop and I now still have it running pyload on my ALARM Raspberry Pi. I even tried creating a hook script which modifies the plugin.conf when pyload starts, but that didn't seem to work (apparently pyload doesn't reload the config file).

**Comment by Stufo76** [comment]
@Eisfreak7 #1157 it's not fixed fo me too

**Comment by GamesGamble** [comment]
iam experiencing the same error. Editing the default values is a "temporary" fix. Pyload Folder > data > userplugins > hooks > ExtractArchive.py And iam deleting the .pyc file to (dunno if the file is updated automatically) I only know that Python not need to be compiled and automatically creates his machine code files known as .pyc in this case. The Source code is the .py file.

**Comment by Stufo76** [comment]
Same error even with just updated version

**Comment by vuolter** [comment]
@Stufo76 On Windows was fixed time ago.

**Comment by Stufo76** [comment]
@vuolter for me it's on Linux, and still not fixed

**Comment by Sporrdig** [comment]
by me is the same.

**Comment by geeuz** [comment]
Same here on Linux, after restart "Move to trash" is on.

**Comment by GamesGamble** [comment]
@vuolter for me it was Windows, still not fixed.

**Comment by GammaC0de** [comment]
Fixed long ago.
