### ISSUE TITLE
Error executing hooks : xxxxx object has no attribute 'pyfile'

### ISSUE THREAD

**Issue by SebaBoler** [pyload/pyload#1519]
Hello,

after last update i have problem with few hooks.

Error executing hooks: 'LinkdecrypterComHook' object has no attribute 'pyfile'
Error executing hooks: 'NoPremiumPlHook' object has no attribute 'pyfile'

is any possibility to fix it  manually ??

**Comment by vuolter** [comment]
Currently I'm busy to updating (and fixing) all the plugins (more than 400!), so I need some time... You can fix ithem manually of course or wait my update some hours more.

**Comment by SebaBoler** [comment]
Is there a chance that this week repair problem ??

**Comment by vuolter** [comment]
I'm not home right now. :(

**Comment by SebaBoler** [comment]
No you cant  :) , are you on vacation ??   When you except fix ?

**Comment by vuolter** [comment]
I already fixed almost all the issues reported these last days but I'm unable to push them now. :(

**Comment by SebaBoler** [comment]
Ok, thx for information. At this time could you show what and where fix in NoPremium host >?

**Comment by SebaBoler** [comment]
How there after weekend ??

**Comment by SebaBoler** [comment]
There is still a chance to patch ???   I w8 a month and cant use pyload

**Comment by vuolter** [comment]
Fixed.
