### ISSUE TITLE
ZeveraCom plugin is not working.

### ISSUE THREAD

**Issue by cndesu** [pyload/pyload#152]
Could not download from various websites using ZeveraCom website...

The log is..

04.06.2013 19:46:37	INFO	 Starting pyLoad 0.4.9
04.06.2013 19:46:37	INFO	 Using home directory: /opt/share/pyload_config
04.06.2013 19:46:37	DEBUG	 Remote activated: False
04.06.2013 19:47:01	DEBUG	 created index of plugins
04.06.2013 19:47:01	DEBUG	 Redirected import module.plugins.hooks.ImageTyperz -> userplugins.hooks.ImageTyperz
04.06.2013 19:47:01	DEBUG	 Redirected import module.plugins.hooks.LinkdecrypterCom -> userplugins.hooks.LinkdecrypterCom
04.06.2013 19:47:01	DEBUG	 Redirected import module.plugins.hooks.BypassCaptcha -> userplugins.hooks.BypassCaptcha
04.06.2013 19:47:01	DEBUG	 Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
04.06.2013 19:47:02	DEBUG	 Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
04.06.2013 19:47:02	DEBUG	 Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
04.06.2013 19:47:02	DEBUG	 Redirected import module.plugins.hooks.Checksum -> userplugins.hooks.Checksum
04.06.2013 19:47:02	INFO	 Checksum: Checksum validation is disabled in general configuration
04.06.2013 19:47:02	DEBUG	 Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
04.06.2013 19:47:02	DEBUG	 Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
04.06.2013 19:47:03	INFO	 ExtractArchive: Activated UnRar
04.06.2013 19:47:03	DEBUG	 Redirected import module.plugins.hooks.Captcha9kw -> userplugins.hooks.Captcha9kw
04.06.2013 19:47:03	DEBUG	 Redirected import module.plugins.hooks.CaptchaTrader -> userplugins.hooks.CaptchaTrader
04.06.2013 19:47:04	DEBUG	 Redirected import module.plugins.hooks.ZeveraCom -> userplugins.hooks.ZeveraCom
04.06.2013 19:47:04	DEBUG	 Redirected import module.plugins.internal.MultiHoster -> userplugins.internal.MultiHoster
04.06.2013 19:47:05	DEBUG	 Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
04.06.2013 19:47:05	INFO	 Activated plugins: BypassCaptcha, Captcha9kw, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterCom, UnSkipOnFail, UpdateManager, XFileSharingPro, ZeveraCom
04.06.2013 19:47:05	INFO	 Deactivate plugins: AlldebridCom, CaptchaBrotherhood, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, HotFolder, IRCInterface, MergeFiles, MultiDebridCom, MultiHome, MultishareCz, Premium4Me, PremiumizeMe, RealdebridCom, RehostTo, ReloadCc, RestartFailed, SkipRev, UnrestrictLi, XMPPInterface
04.06.2013 19:47:05	INFO	 Downloadtime: True
04.06.2013 19:47:12	INFO	 Free space: 2.67 TiB
04.06.2013 19:47:12	INFO	 Starting builtin webserver: 0.0.0.0:8000
04.06.2013 19:47:12	INFO	 Activating Accounts...
04.06.2013 19:47:13	DEBUG	 Redirected import module.plugins.accounts.ZeveraCom -> userplugins.accounts.ZeveraCom
04.06.2013 19:47:13	DEBUG	 ZeveraCom: DayTrafficLimit:75000,EndSubscriptionDate:2013/7/3 1:49:18,TrafficUsedToday:0,AvailableTodayTraffic:75000,OronDayTrafficLimit:0
04.06.2013 19:47:13	DEBUG	 ZeveraCom: Get Account Info for cndesu@yahoo.com
04.06.2013 19:47:14	DEBUG	 ZeveraCom: DayTrafficLimit:75000,EndSubscriptionDate:2013/7/3 1:49:18,TrafficUsedToday:0,AvailableTodayTraffic:75000,OronDayTrafficLimit:0
04.06.2013 19:47:14	DEBUG	 ZeveraCom: Account Info: {'premium': True, 'validuntil': 1372834158.0, 'trafficleft': 76800000}
04.06.2013 19:47:14	INFO	 Activating Plugins...
04.06.2013 19:47:19	DEBUG	 LinkdecrypterCom: REGEXP: https?://([^.]+\.)*?(00\.uz|0rz\.tw|0url\.in|10001mb\.com|123link\.it|123url\.org|1cl\.in|1ke\.com\.ar|1kh\.de|1short\.us|1tiny\.net|1tk\.us|1to4\.me|1tool\.biz|1url\.com|1y\.lt|1zh\.us|2\.gp|24h\.to|2joy\.de|2so\.be|2tu\.us|3\.ly|3klinks\.com|3le\.ru|4-url\.com|5\.gp|690\.jp|6nc\.net|7\.ly|7li\.in|8\.ly|9\.bb|9link\.us|9url\.us|aa5\.nl|adcou\.ch|adcrun\.ch|adf\.ly|adflav\.com|adfoc\.us|adha\.ir|adjoin\.me|adkoon\.com|adlock\.in|adref\.co|adv\.li|allanalpass\.com|alturl\.com|amy\.gs|anonypaste\.co|any\.gs|apurl\.ru|arabup\.biz|atu\.ca|aurl\.es|b23\.ru|baberepublic\.com|bai\.lu|bat5\.com|bax\.li|bc\.vc|bdb\.im|beam\.to|bigfly\.eu|bimm\.in|birurl\.com|bit\.ly|bitly\.com|bitsheare\.com|bitsy\.eu|bitw\.in|blu\.cc|bofh\.us|boo\.io|briefurl\.net|briefurl\.org|bshr\.info|c\.ly|cacheliens\.com|capourl\.com|cash4files\.com|cash4links\.co|cc\.st|cd\.vg|chilp\.it|choc\.la|ciervopaste\.siempreestrenos\.net|cl\.lk|clck\.ru|cli\.gs|clickthru\.ca|cloneurl\.com|clxu\.eu|coinurl\.com|compupaste\.com|convertircodigo\.com|copyload\.com|cort\.as|cosyupload\.com|crypt\.to|crypt2\.be|cryptlink\.ws|cryptobin\.org|ct\.tl|cur\.lv|cutt\.us|daa\.pl|dasolo\.info|ddl-warez\.in|deb\.gs|defensive-pro\.org|deurl\.me|dfl8\.me|digzip\.com|directmirror\.com|djurl\.com|dl-protect\.com|dl\.dropbox\.com|doiop\.com|drstickyfingers\.com|dwz\.cn|dyo\.gs|easyurl\.net|ecra\.se|ecut\.me|ehe\.me|encript\.in|encurtador\.com|enlacs\.com|esconderlink\.com\.ar|evg\.in|ewe1\.com|exoshare\.com|extreme-protect\.com|exzip\.com|exzip\.net|fa\.by|faja\.me|famous\.richenginner\.com|fapoff\.com|fastestpaste\.com|fdnlinks\.com|fea\.me|fff\.re|fff\.to|filedeck\.net|filemirrorupload\.com|filesonthe\.net|filetobox\.com|fileupster\.com|firsturl\.com|firsturl\.de|firsturl\.net|flameupload\.com|flq\.us|folu\.me|fon\.gs|forexurls\.net|freean\.us|freegaysitepass\.com|freetexthost\.com|fru\.me|fu\.gy|fwd4\.me|fyad\.org|g1n\.co|galleries\.bz|go4up\.com|goandgrab\.info|goblig\.com|goldpaste\.us|goneviral\.com|goshrink\.com|guardian\.noip\.es|guardlink\.org|h-url\.in|hasurl\.co\.cc|hide-url\.net|hidelinkz\.com|hidemyass\.com|hidemylink\.org|hidemylinks\.com\.ar|hidemylinks\.net|hides\.at|hideurl\.biz|ho\.io|hornywood\.tv|href\.hu|hurl\.me|hurlme\.com|i0u\.ru|id2\.tryjav\.com|iiiii\.in|ilii\.in|ilix\.in|ily\.me|ino\.me|interupload\.com|iou\.ru|is\.gd|iturl\.nl|ity\.im|ivpaste\.com|j\.gs|j\.mp|j7\.se|je\.pl|jheberg\.com|jheberg\.net|jijr\.com|just\.as|justpaste\.it|katt\.it|keeplinks\.me|kickupload\.com|klnk\.de|knoffl\.com|kodo\.ameoto\.com|korta\.nu|kro\.co|ks\.gs|kurzurl\.ch|kuslink\.com|kypaste\.com|l1nks\.org|last\.so|latwy\.pl|ld\.rtify\.com|leechmf\.com|li\.co\.ve|link-go\.info|link-protector\.com|link-safe\.net|link\.file-up\.ru|link\.tl|link2of\.net|link4jo\.com|linkanonimo\.com|linkasa\.com|linkbabes\.com|linkbank\.eu|linkbee\.com|linkblur\.com|linkbucks\.com|linkbun\.ch|linkc\.at|linkcrypt\.com|linkcrypt\.ws|linkencrypter\.com|linkhide\.com\.ar|linkhide\.in|linkoculto\.net|linkoff\.com\.br|linkok\.org|linkpop\.pro|linkprivado\.com|linkprivate\.net|linkprotect\.in|links-protect\.com|links-protect\.info|links-protect\.net|links-protection\.com|links\.tc|linksafe\.me|linksaver\.info|linkse\.info|linksecure\.info|linkseguro\.com\.ar|linkseguro\.org|linksole\.com|linksprotec\.com|linksprotegidos\.info|linkssafe\.com|linkto\.im|linkto\.net|linkweb\.dk|linkx\.in|linkzip\.net|linxcrypt\.com|listalinks\.com|listedfiles\.com|littleurl\.net|lixk\.me|lixxin\.com|lixy\.in|ljv2\.com|lkt\.es|ll11\.org|ln-s\.net|lnk\.cm|lnk\.co|lnk\.ly|lnx\.lu|longr\.us|loo\.katt\.it|looble\.net|losslessinside\.com|lovelink\.in|ly1\.fr|lzshort\.biz|m-l\.sk|m1q\.ru|madlink\.sk|maxi-upload\.com|mcaf\.ee|mediahide\.com|mediahide\.org|medianonym\.com|megaline\.co|megalinks\.es|megasfiles\.com|megaupper\.com|mehost\.info|merky\.de|mf1\.jp|mgff\.info|mhz\.me|migre\.me|min\.bz|miniurl\.com|miniurl\.es|miniurl\.org|miniurls\.co|minu\.me|mir\.cr|mirorii\.com|mirrorcreator\.com|mirrorstack\.com|mirrorupload\.net|mo\.by|mokkapps\.com|moourl\.com|mrte\.ch|multi-uploadeur\.com|multi\.la|multiup\.org|multiupload\.ch|multiupload\.nl|murl\.kz|musicalmente\.info|my-protect-link\.com|myhidelink\.com|mylinkgen\.com|myooo\.info|mypaqe\.com|mypl\.us|myrapidlinks\.com|myref\.de|myref\.to|mytext\.easyweb2009\.com|myurl\.in|myurls\.ca|nbanews\.us|nextdown\.net|niceurl\.org|nka\.nu|nopaste\.dk|notepad\.cc|nourelsaffe\.info|nov\.io|nsfw\.in|numrl\.com|nurl\.me|nutshellurl\.com|nxm\.us|nxy\.in|o-x\.fr|oculto\.elrincondecrespo\.com|okconsolas\.com|okupshare\.com|oneddl\.canhaz\.it|onelink\.ir|onmirror\.com|ou\.af|ow\.ly|ownsafelinks\.com|p\.tl|p4p\.com\.es|p6l\.org|past\.is|paste\.frubar\.net|paste\.hotfile-bb\.com|paste\.plurk\.com|paste\.to|paste\.ubuntu\.com|paste2\.org|paste21\.info|pasteb\.com|pastebay\.com|pastebin\.com|pastebin\.ubuntu\.com|pastehtml\.com|paylesssofts\.net|perseo\.in|picbucks\.com|pili\.la|poontown\.net|pqueno\.com|priva\.us|protec-link\.com|protect-ddl\.com|protect-my-links\.com|protect-url\.net|protect\.myurl\.in|protected\.socadvnet\.com|protectedlink\.net|protectlinks\.com|protectlinks\.net|protectlk\.com|protege-mes-liens\.com|protegez-vos-liens\.com|proxybooster\.org|prxt\.nl|ptiturl\.com|ptl\.li|q\.gs|qlnk\.net|qlql\.ru|qooy\.com|qqc\.co|qr\.net|qrf\.in|qurl\.co|qvvo\.com|qy\.fi|r4dm\.com|rapidfolder\.com|rapidsafe\.de|rapidsafe\.org|rapidshare\.mu|rarme\.com|readthis\.ca|realfiles\.net|redi\.re|redi\.se|redir\.cc|redir\.ec|redirects\.ca|ref\.so|relinka\.net|revivelink\.com|rexwo\.com|rgf\.me|ri\.ms|rlu\.ru|rod\.gs|rqq\.co|rsmonkey\.com|rt\.se|rurls\.ru|s2l\.biz|s5\.egyup\.com|saf\.li|safe\.mn|safelinking\.net|saferlinks\.com|safeurl\.me|sameurl\.com|savanttools\.com|save-link\.info|savelinking\.com|savelinks\.net|scriptmafia\.org|scut\.ly|sealed\.in|seclnk\.in|seomafia\.net|seriousdeals\.net|seriousfiles\.com|sexpalace\.gs|sflk\.in|sfurl\.biz|share-link\.info|share\.wf|sharebee\.com|sharetext\.org|shnk\.me|sho\.rtify\.com|short-link\.fr|short5\.com|shortlink\.ca|shortlink\.info|shorturlscript\.net|shrt\.st|shrunklink\.com|shrvl\.com|simurl\.com|sinl\.es|siripaste\.com|skroc\.pl|slexy\.org|slnks\.com|slnky\.net|smlk\.es|smsdl\.com|smsh\.me|sn\.im|snipr\.com|snipurl\.com|snurl\.com|sonofertas\.es|spedr\.com|spreadlink\.us|srtl\.eu|star-cyber\.com|stnx\.at|stu\.tc|subedlc\.com|subirfacil\.com|surl\.hu|syl\.me|szort\.pl|t\.co|t7\.hu|ta\.gd|takemyfile\.com|takemylinks\.com|taken\.to|textsave\.de|textsnip\.com|thecow\.me|theseblogs\.com|thesefiles\.com|theseforums\.com|thinfi\.com|tighturl\.com|tik\.tl|tilien\.net|tini\.cc|tiny\.cc|tiny\.lt|tiny\.ly|tinybucks\.net|tinylinks\.co|tinypaste\.com|tinypasted\.com|tinyurl\.com|tinyurlscript\.info|tmf\.myegy\.com|tnabucks\.com|tnij\.com|tnij\.org|tnpd\.info|tny\.cz|to\.ly|togoto\.us|tomys\.com\.ar|tot\.to|tr5\.in|tra\.kz|traccia\.org|trick\.ly|trll\.in|tubeviral\.com|twhub\.com|twurl\.nl|u\.to|uberpicz\.com|ubervidz\.com|ufa\.lt|ulinks\.net|ulmt\.in|ultrafiles\.net|ultry\.net|umediafire\.com|umquetenha\.org|undeadlink\.com|uploading\.to|uploadjockey\.com|uploadmirrors\.com|uploadonall\.com|upmirror\.com|upsafe\.org|ur\.ly|ur1\.ca|url-go\.com|url-site\.com|url\.az|url\.fm|url\.ie|url\.soft4all\.org|url\.zeta24\.com|url4t\.com|url4u\.org|urla\.in|urlbeat\.net|urlc\.de|urlcash\.net|urlcorta\.es|urlcrypt\.com|urlcut\.com|urlcut\.in|urldefender\.com|urlenco\.de|urlink\.at|urlizr\.de|urlm\.in|urln\.tk|urlpulse\.net|urls2\.net|urlsnub\.com|urlspy\.co\.cc|urwij|uselink\.info|uucc\.cc|uvy\.net|uwpaste\.info|uze\.in|verd\.in|vir\.al|vl\.am|voutz\.com|wa9\.la|wcrypt\.in|webtooljungle\.com|wee\.li|weepax\.com|whackyvidz\.com|wll\.in|wn\.arabseed\.com|wtc\.la|wwenews\.us|x-ls\.ru|x\.co|x\.vu|x61\.ch|x7z\.us|xa\.ly|xc\.io|xib\.me|xip\.ir|xishare\.com|xn--17g\.ws|xn--1ci\.ws|xn--3fi\.ws|xn--5gi\.ws|xn--9gi\.ws|xn--bih\.ws|xn--cwg\.ws|xn--egi\.ws|xn--fwg\.ws|xn--hgi\.ws|xn--l3h\.ws|xn--odi\.ws|xn--ogi\.ws|xn--rei\.ws|xn--vgi\.ws|xr\.com|xrl\.us|xtreemhost\.com|xurl\.cn|xurl\.es|xxs\.ru|y\.ahoo\.it|yep\.it|youfap\.me|youlink\.in|ysu\.me|ytc\.es|yuarel\.com|yvy\.me|yyv\.co|z\.gs|zero10\.net|zff\.co|zio\.in|zlinkz\.in|zo\.mu|zpag\.es|zsk\.bz|zwow\.it|zxxo\.net)/.*
04.06.2013 19:47:19	DEBUG	 XFileSharingPro: Pattern loaded - handling 79 hosters
04.06.2013 19:47:19	INFO	 ZeveraCom: Reloading supported hoster list
04.06.2013 19:47:20	DEBUG	 Redirected import module.plugins.hoster.ZeveraCom -> userplugins.hoster.ZeveraCom
04.06.2013 19:47:20	DEBUG	 ZeveraCom: Overwritten Hosters: BitshareCom, CatShareNet, CloudzerNet, CramitIn, CrockoCom, CyberlockerCh, DailymotionCom, DdlstorageCom, EasybytezCom, EgoFilesCom, ExtabitCom, FileApeCom, FilebeerInfo, FilecloudIo, FilefactoryCom, FilejungleCom, FilepostCom, FileserveCom, FilesonicCom, FourSharedCom, FreakshareCom, GigapetaCom, HellshareCz, HotfileCom, JumbofilesCom, KickloadCom, LetitbitNet, LuckyShareNet, MediafireCom, MegasharesCom, MegauploadCom, NetloadIn, OneFichierCom, PornhubCom, PutlockerCom, RapidgatorNet, RapidshareCom, RarefileNet, RedtubeCom, RyushareCom, SecureUploadEu, SendspaceCom, ShareonlineBiz, ShragleCom, TurbobitNet, TusfilesNet, TwoSharedCom, UnibytesCom, UploadStationCom, UploadedTo, UploadingCom, UptoboxCom, WuploadCom, X7To, XHamsterCom, XVideosCom, YoupornCom, YoutubeCom, ZippyshareCom
04.06.2013 19:47:20	DEBUG	 ZeveraCom: New Hosters: 180upload.com, 1st-files.com, albafile.com, allmyvideos.net, asfile.com, badongo.com, bayfiles.net, bulletupload.com, cuckshare.com, cum.com, dachix.com, datafile.com, depfile.com, deviantclip.com, dfiles.eu, empflix.com, en.vidivodo.com, epositfiles.com, fiberupload.com, filebox.com, filedefend.com, filedino.com, fileduct.net, fileflyer.com, filehost.ws, filemates.com, filemaze.ws, filemonster.net, fileparadox.in, filereactor.com, filerio.in, filerose.com, fileserving.com, filesflash.com, filesmonster.com, fileswap.com, filevelocity.com, frozenhippo.com, funny-videos.co.uk, funnyanimalvideos.com, furk.net, gigasize.com, girlfriendvideos.com, girlsandvids.com, greektube.org, henchfile.com, hipfile.com, homemoviestube.com, hotpornshow.com, i-filez.com, isavelink.com, ishare.rediff.com, keep2share.cc, keezmovies.com, livefile.org, liveleak.com, lumfile.com, madthumbs.com, mediabum.com, mega.co.nz, megaporn.com, megashare.com, metacafe.com, mixturecloud.com, mojvideo.com, movies.askjolene.com, muchshare.com, multiupload.com, nowvideo.eu, oneminuteu.com, oteupload.com, pornrabbit.com, queenshare.com, scribd.com, sextube.com, shareflare.net, sharpfile.com, shufuni.com, slingfile.com, slutload.com, sockshare.com, spankwire.com, uload.to, ultramegabit.com, uploadhero.co, uploadjet.net, userporn.com, videobam.com, vidmax.com, vimeo.com, vip-file.com, xfileshare.eu, xnxx.com, youjizz.com, yousendit.com, yunfile.com, yuvutu.com, ziporn.com, ztod.com
04.06.2013 19:47:20	DEBUG	 ZeveraCom: Regexp: http://zevera.com/.*|.*(empflix\.com|uploadhero\.co|hipfile\.com|keezmovies\.com|liveleak\.com|yuvutu\.com|filemaze\.ws|fiberupload\.com|uploadjet\.net|1st-files\.com|epositfiles\.com|allmyvideos\.net|megaporn\.com|sockshare\.com|homemoviestube\.com|userporn\.com|livefile\.org|filebox\.com|keep2share\.cc|yunfile\.com|muchshare\.com|filemonster\.net|movies\.askjolene\.com|hotpornshow\.com|fileflyer\.com|yousendit\.com|filevelocity\.com|cum\.com|sharpfile\.com|ishare\.rediff\.com|queenshare\.com|cuckshare\.com|xfileshare\.eu|filedefend\.com|filedino\.com|isavelink\.com|funny-videos\.co\.uk|fileparadox\.in|xnxx\.com|dachix\.com|shareflare\.net|girlfriendvideos\.com|vidmax\.com|multiupload\.com|filemates\.com|megashare\.com|en\.vidivodo\.com|uload\.to|filerose\.com|henchfile\.com|girlsandvids\.com|mixturecloud\.com|funnyanimalvideos\.com|shufuni\.com|filehost\.ws|sextube\.com|nowvideo\.eu|vimeo\.com|fileswap\.com|frozenhippo\.com|ziporn\.com|badongo\.com|fileduct\.net|furk\.net|mojvideo\.com|greektube\.org|oteupload\.com|bulletupload\.com|slutload\.com|madthumbs\.com|oneminuteu\.com|180upload\.com|filesmonster\.com|slingfile\.com|i-filez\.com|metacafe\.com|spankwire\.com|filesflash\.com|mega\.co\.nz|ztod\.com|youjizz\.com|lumfile\.com|scribd\.com|depfile\.com|bayfiles\.net|filerio\.in|vip-file\.com|dfiles\.eu|albafile\.com|datafile\.com|ultramegabit\.com|pornrabbit\.com|filereactor\.com|asfile\.com|deviantclip\.com|fileserving\.com|videobam\.com|gigasize\.com|mediabum\.com).*
04.06.2013 19:47:20	INFO	 pyLoad is up and running
04.06.2013 19:47:23	INFO	 No Updates for pyLoad
04.06.2013 19:47:23	INFO	 No plugin updates available
04.06.2013 20:19:18	DEBUG	 Redirected import module.plugins.hoster.BasePlugin -> userplugins.hoster.BasePlugin
04.06.2013 20:19:18	INFO	 Added package Species1 containing 1 links
04.06.2013 20:19:19	INFO	 Download starts: http://www.zevera.com/getFiles.ashx?our ... part01.rar
04.06.2013 20:19:20	DEBUG	 BasePlugin: Location: /Member/download.ashx?retry=1&ourl=http://uploaded.to/file/ffh9kp3f/SHDM0114508BDHGBD.part01.rar
04.06.2013 20:19:20	DEBUG	 pycurl exception 3: malformed
04.06.2013 20:19:20	ERROR	 pycurl error 3: malformed
04.06.2013 20:19:21	INFO	 Debug Report written to debug_BasePlugin_04-06-2013_20-19-20.zip
04.06.2013 20:19:21	INFO	 UnSkipOnFail: look for skipped duplicates for SHDM0114508BDHGBD.part01.rar (pid:3)...
04.06.2013 20:19:21	DEBUG	 All downloads processed
04.06.2013 20:37:43	DEBUG	 Redirected import module.plugins.hoster.NetloadIn -> userplugins.hoster.NetloadIn
04.06.2013 20:37:43	INFO	 Added package evil dead containing 1 links
04.06.2013 20:37:43	DEBUG	 Run Info Fetching for NetloadIn
04.06.2013 20:37:43	INFO	 Download starts: http://www.zevera.com/getFiles.ashx?our ... 45.rar.htm
04.06.2013 20:37:43	DEBUG	 ZeveraCom: zevera.com: Old URL: http://www.zevera.com/getFiles.ashx?our ... 45.rar.htm
04.06.2013 20:37:43	DEBUG	 Finished Info Fetching for NetloadIn
04.06.2013 20:37:44	DEBUG	 ZeveraCom: An Error Occured
Error: This link is not from download site, please fix it: http://www.zevera.com/getFiles.ashx?our ... 45.rar.htm
04.06.2013 20:37:44	WARNING	 Download failed: http://www.zevera.com/getFiles.ashx?our ... 45.rar.htm | Offline or not downloadable - contact Zevera support
04.06.2013 20:37:44	INFO	 UnSkipOnFail: look for skipped duplicates for EVIL_DEAD.part45.rar.htm (pid:4)...
04.06.2013 20:37:44	DEBUG	 ZeveraCom: Unload MultiHoster | NetloadIn | {'new_name': 'ZeveraCom', 'name': 'NetloadIn', 'pattern': 'https?://.*netload\\.in/(?:datei(.*?)(?:\\.htm|/)|index.php?id=10&file_id=)', 'module': , 'new_module': , 're': <_sre.SRE_Pattern object at 0x17b010>, 'user': True, 'v': 0.41999999999999998}
04.06.2013 20:37:44	DEBUG	 All downloads processed
04.06.2013 20:37:45	DEBUG	 Redirected import module.plugins.accounts.NetloadIn -> userplugins.accounts.NetloadIn
04.06.2013 20:37:45	INFO	 Download starts: http://www.zevera.com/getFiles.ashx?our ... 45.rar.htm
04.06.2013 20:37:45	DEBUG	 NetloadIn: URL: http://www.netload.in/dateixp2SrX0MDX.htm
04.06.2013 20:37:46	DEBUG	 Netload: APIDATA: xp2SrX0MDX;EVIL_DEAD.part45.rar;612569402;online;50b9885eeeab6bb5ce775b7cc3dd809f
04.06.2013 20:37:46	DEBUG	 Netload: Entering download_html
04.06.2013 20:37:46	DEBUG	 Netload: try number 0
04.06.2013 20:37:46	DEBUG	 Netload: Trying to find captcha
04.06.2013 20:37:47	DEBUG	 Netload: try number 1
04.06.2013 20:37:47	DEBUG	 Netload: Trying to find captcha
04.06.2013 20:37:47	DEBUG	 Netload: try number 2
04.06.2013 20:37:47	DEBUG	 Netload: Trying to find captcha
04.06.2013 20:37:47	DEBUG	 Netload: try number 3
04.06.2013 20:37:47	DEBUG	 Netload: Trying to find captcha
04.06.2013 20:37:48	DEBUG	 Netload: try number 4
04.06.2013 20:37:48	DEBUG	 Netload: Trying to find captcha
04.06.2013 20:37:48	DEBUG	 Netload: try number 5
04.06.2013 20:37:48	DEBUG	 Netload: Trying to find captcha
04.06.2013 20:37:48	DEBUG	 Netload: try number 6
04.06.2013 20:37:48	DEBUG	 Netload: Trying to find captcha
04.06.2013 20:37:49	DEBUG	 Netload: try number 7
04.06.2013 20:37:49	DEBUG	 Netload: Trying to find captcha
04.06.2013 20:37:49	DEBUG	 Netload: try number 8
04.06.2013 20:37:49	DEBUG	 Netload: Trying to find captcha
04.06.2013 20:37:49	DEBUG	 Netload: try number 9
04.06.2013 20:37:49	DEBUG	 Netload: Trying to find captcha
04.06.2013 20:37:49	WARNING	 Download failed: EVIL_DEAD.part45.rar | Failed
04.06.2013 20:37:49	INFO	 UnSkipOnFail: look for skipped duplicates for EVIL_DEAD.part45.rar (pid:4)...
04.06.2013 20:37:50	DEBUG	 All downloads processed

**Comment by vuolter** [comment]
@zevera Now should working. I'd really appreciate a way to retrieve by the api the list of currently working hosters only.

**Comment by snickers2k** [comment]
hey. i just bought a premium acc from zevera. But first of all, the plugin is not listed. It ends in the middle of XMPP... Maybe u can fix this? tested this on two different systems (mac and linux) with different monitors and resolutions - without success.

I think i have to activate the plugin there, like with premiumize, but i just can't reach the plugin :(

thanks

**Comment by vuolter** [comment]
@snickers2k Do you change anything on webui side? (pyload+ patch, bootstrap theme or something like that). Usually, you just have to scroll the list to find the plugin.
