### ISSUE TITLE
[ExtractArchive] not working anymore

### ISSUE THREAD

**Issue by hardy123480** [pyload/pyload#1526]
Since 2 or 3 days [ExtractArchive] is not working anymore for me. I did not change anything. Log just says "Package finished" but extracting does not start anymore like it was before.
I tried to start in Debug-Mode to provide further information but unfortunately in Debug-Mode the Download does not even start (pretty sure it worked a few months ago, I don't know what is broken).

Any help would be appreciated. Thanks.

Edit: ExtractArchive plugin is activated of course.

**Comment by GammaC0de** [comment]
@hardy123480 Please try this: http://forum.pyload.org/viewtopic.php?f=10&t=4335 to restore the pyLoad plugins then start debug mode and report back

**Comment by hardy123480** [comment]
Thanks, that worked.

**Comment by GammaC0de** [comment]
:+1:

**Comment by sti0** [comment]
Hi everyone,
got the same problem but the link doesn't work. Can anyone tell me how I can restore the plugins?
Thanks!
