### ISSUE TITLE
Mega.co.nz Not work latin

### ISSUE THREAD

**Issue by f4068199** [pyload/pyload#1527]
The Mega.co.nz plugin is not working to link with accented characters in Portuguese . Latin ã, ê, í, ô,ú, ç .. ASCII above 128 . Translate by google tradutor
Example links :
https://mega.co.nz/#!r1IhETqZ!Q8g7RTkQ2Nnocz5WdtFe5k2n7ad0uc32vjnJ_CMApco
'ascii' codec can't encode character u'\xfa' in position 50: ordinal not in range(128) 0.00 B
S03E19 - Saúde; Ciúme [480p][Dual].mkv

look http://www.theasciicode.com.ar/extended-ascii-code/minuscule-c-cedilla-lowercase-ascii-code-135.html 
![image](https://cloud.githubusercontent.com/assets/5298480/8268577/bc950e14-1760-11e5-8a1c-fd71aa3c75b9.png)

**Comment by GammaC0de** [comment]
Works fine here (ubuntu 14).
Which OS are you running pyload?
Also, please enable debug mode and post the log here.

**Comment by f4068199** [comment]
Embarked in a Router TP-Link TL- WDR4300 v1, running OpenWrt barrier breaker 14.07 / LuCI Trunk (0.12 + SVN - r10530 ) -
Attached log:
110	20.06.2015 20:20:18	INFO	Iniciando pyLoad 0.4.9
111	20.06.2015 20:20:18	INFO	Utilizando pasta home: /etc/pyload
112	20.06.2015 20:20:18	DEBUG	Remote activated: True
113	20.06.2015 20:20:29	DEBUG	created index of plugins
114	20.06.2015 20:20:29	DEBUG	Redirected import module.plugins.hooks.BypassCaptcha -> userplugins.hooks.BypassCaptcha
115	20.06.2015 20:20:29	DEBUG	Redirected import module.plugins.internal.Hook -> userplugins.internal.Hook
116	20.06.2015 20:20:29	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
117	20.06.2015 20:20:29	DEBUG	Redirected import module.plugins.hooks.Checksum -> userplugins.hooks.Checksum
118	20.06.2015 20:20:29	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
119	20.06.2015 20:20:29	DEBUG	Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
120	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
121	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
122	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
123	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
124	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.hooks.LinkdecrypterComHook -> userplugins.hooks.LinkdecrypterComHook
125	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.internal.MultiHook -> userplugins.internal.MultiHook
126	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.crypter.LinkdecrypterCom -> userplugins.crypter.LinkdecrypterCom
127	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.internal.Crypter -> userplugins.internal.Crypter
128	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.hooks.ImageTyperz -> userplugins.hooks.ImageTyperz
129	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
130	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
131	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
132	20.06.2015 20:20:30	DEBUG	Redirected import module.plugins.hooks.UserAgentSwitcher -> userplugins.hooks.UserAgentSwitcher
133	20.06.2015 20:20:30	INFO	Plug-ins ativados: BypassCaptcha, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterComHook, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
134	20.06.2015 20:20:30	INFO	Desativar plug-ins: AlldebridComHook, AndroidPhoneNotify, AntiVirus, Captcha9Kw, CaptchaBrotherhood, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMe, HotFolder, IRCInterface, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
135	20.06.2015 20:20:30	INFO	Tempo de Download: True
136	20.06.2015 20:20:30	INFO	Iniciando ThriftBackend: 0.0.0.0:7227
137	20.06.2015 20:20:30	INFO	Espaço livre: 38.08 GiB
138	20.06.2015 20:20:30	INFO	Ativando contas...
139	20.06.2015 20:20:30	INFO	Ativando plug-ins...
140	20.06.2015 20:20:33	INFO	Starting builtin webserver: 0.0.0.0:8000
141	20.06.2015 20:20:33	DEBUG	Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
142	20.06.2015 20:20:34	DEBUG	Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
143	20.06.2015 20:20:34	ERROR	Error executing hooks: 'ExtractArchive' object has no attribute 'pyfile'
144	20.06.2015 20:20:34	INFO	pyLoad is up and running
145	20.06.2015 20:20:36	ERROR	Error executing hooks: 'LinkdecrypterComHook' object has no attribute 'pyfile'
146	20.06.2015 20:20:48	INFO	Added package test containing 1 links
147	20.06.2015 20:20:48	DEBUG	Redirected import module.plugins.hoster.MegaCoNz -> userplugins.hoster.MegaCoNz
148	20.06.2015 20:20:48	INFO	Download starts: https://mega.co.nz/#!fQAmHTxa!QNgvLGDMZsn1HYw4P5Ho52XkWh0lpF95w4bnxAp3N60
149	20.06.2015 20:20:48	WARNING	Download failed: https://mega.co.nz/#!fQAmHTxa!QNgvLGDMZsn1HYw4P5Ho52XkWh0lpF95w4bnxAp3N60 | global name 'decode' is not defined
150	20.06.2015 20:20:49	DEBUG	Error creating zip file: [Errno 2] No such file or directory: 'tmp/MegaCoNz'
151	20.06.2015 20:20:49	INFO	Debug Report written to debug_MegaCoNz_20-06-2015_20-20-48.txt
152	20.06.2015 20:20:49	ERROR	Error executing hooks: 'UnSkipOnFail' object has no attribute 'pyfile'
153	20.06.2015 20:20:49	DEBUG	All downloads processed

DEBUG:

pyLoad 0.4.9 Debug Report of MegaCoNz 0.30 

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/share/python/pyload/module/PluginThread.py", line 186, in run
    self.m.core.hookManager.downloadPreparing(pyfile)
  File "/usr/share/python/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/python/pyload/module/HookManager.py", line 214, in downloadPreparing
    plugin.downloadPreparing(pyfile)
  File "/etc/pyload/userplugins/hooks/UserAgentSwitcher.py", line 42, in downloadPreparing
    self.logDebug("Use custom user-agent string: " + useragent)
  File "/etc/pyload/userplugins/internal/Plugin.py", line 71, in logDebug
    return self._log("debug", args)
  File "/etc/pyload/userplugins/internal/Plugin.py", line 63, in _log
    str(a)).strip() for a in args if a)
  File "/etc/pyload/userplugins/internal/Plugin.py", line 63, in <genexpr>
    str(a)).strip() for a in args if a)
NameError: global name 'decode' is not defined
 

FRAMESTACK:

Frame new in /usr/share/python/pyload/module/utils.py at line 167
	                args = (<module.HookManager.HookManager instance at 0x776e4580>,
 PyFile 1: https://mega.co.nz/#!fQAmHTxa!QNgvLGDMZsn1HYw4P5Ho52XkWh0lpF95w4bnxAp3N60@MegaCoNz)
	                func = <function downloadPreparing at 0x77358330>

Frame downloadPreparing in /usr/share/python/pyload/module/HookManager.py at line 214
	              pyfile = PyFile 1: https://mega.co.nz/#!fQAmHTxa!QNgvLGDMZsn1HYw4P5Ho52XkWh0lpF95w4bnxAp3N60@MegaCoNz
	                self = <module.HookManager.HookManager instance at 0x776e4580>
	              plugin = <Hook UserAgentSwitcher>

Frame downloadPreparing in /etc/pyload/userplugins/hooks/UserAgentSwitcher.py at line 42
	           maxredirs = 10
	           useragent = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0'
	                self = <Hook UserAgentSwitcher>
	      connecttimeout = 60
	              pyfile = PyFile 1: https://mega.co.nz/#!fQAmHTxa!QNgvLGDMZsn1HYw4P5Ho52XkWh0lpF95w4bnxAp3N60@MegaCoNz

Frame logDebug in /etc/pyload/userplugins/internal/Plugin.py at line 71
	                self = <Hook UserAgentSwitcher>
	                args = ('Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0',)

Frame _log in /etc/pyload/userplugins/internal/Plugin.py at line 63
	                self = <Hook UserAgentSwitcher>
	                args = ('Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0',)
	                 log = <bound method Logger.debug of <logging.Logger object at 0x777b6a70>>
	               level = 'debug'

Frame <genexpr> in /etc/pyload/userplugins/internal/Plugin.py at line 63
	                   a = 'Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0'
	                  .0 = <tupleiterator object at 0x769d9a70>


PLUGIN OBJECT DUMP: 

	             API_URL = 'https://eu.api.mega.co.nz/cs'
	         FILE_SUFFIX = '.crypted'
	             account = None
	               cTask = None
	          chunkLimit = 1
	              config = <module.ConfigParser.ConfigParser instance at 0x776ce710>
	                core = <__main__.Core object at 0x776caf90>
	                html = None
	                  js = <module.common.JsEngine.JsEngine instance at 0x7705abe8>
	           lastCheck = None
	        lastDownload = ''
	             limitDL = 0
	                 log = <logging.Logger object at 0x777b6a70>
	             multiDL = True
	                 ocr = None
	             premium = False
	              pyfile = PyFile 1: https://mega.co.nz/#!fQAmHTxa!QNgvLGDMZsn1HYw4P5Ho52XkWh0lpF95w4bnxAp3N60@MegaCoNz
	                 req = <module.network.Browser.Browser object at 0x769c4c00>
	      resumeDownload = False
	             retries = 0
	              thread = None
	                user = None
	           waitUntil = 0
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 0
	               abort = False
	              active = False
	               error = "global name 'decode' is not defined"
	                  id = 1
	                lock = <_RLock owner=None count=0>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x775c6328>
	         maxprogress = 100
	                name = u'https://mega.co.nz/#!fQAmHTxa!QNgvLGDMZsn1HYw4P5Ho52XkWh0lpF95w4bnxAp3N60'
	               order = 0
	           packageid = 1
	              plugin = <userplugins.hoster.MegaCoNz.MegaCoNz object at 0x769d9950>
	         pluginclass = <class 'userplugins.hoster.MegaCoNz.MegaCoNz'>
	        pluginmodule = <module 'userplugins.hoster.MegaCoNz' from '/etc/pyload/userplugins/hoster/MegaCoNz.pyc'>
	          pluginname = u'MegaCoNz'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'https://mega.co.nz/#!fQAmHTxa!QNgvLGDMZsn1HYw4P5Ho52XkWh0lpF95w4bnxAp3N60'
	           waitUntil = 0

**Comment by GammaC0de** [comment]
@f4068199 You should manually update `/etc/pyload/userplugins/internal/Plugin.py` from here: https://github.com/pyload/pyload/raw/stable/module/plugins/internal/Plugin.py
If that wont help, follow the instructions here: http://forum.pyload.org/viewtopic.php?f=10&t=4335

**Comment by Velociraptor85** [comment]
@GammaC0de I think this can be closed too
