### ISSUE TITLE
Real Debrid not existend anymore?

### ISSUE THREAD

**Issue by Canerunus** [pyload/pyload#1528]
My Realdebrid Account isn't working, but not the error the user before had. When I register my account ,pyload logs this: "Error importing RealdebridCom: No module named RealdebridCom"

Hope it can be fixed soon.

**Comment by chaosmaker** [comment]
The name has changed for some reason to RealDebridComHook or something like that. Check whether that is enabled.

**Comment by Canerunus** [comment]
I did test all scenarios. All on. one or another on. Still doesn't work for me

**Comment by vuolter** [comment]
Please retry now.

**Comment by Canerunus** [comment]
It works now! Thank you very much
