### ISSUE TITLE
[problem + bug] plugin config section is derived from the plugin filename cousing possible config collusion

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1538]
Hi,

form `PluginManager.py`:
```python
    def parse(self, folder, pattern=False, home={}):


        for f in listdir(pfolder):


                name = f[:-3]
                if name[-1] == ".": name = name[:-4]



                    try:
                        self.core.config.addPluginConfig(name, config, desc)
                    except:
                        self.log.error("Invalid config in %s: %s" % (name, config))
```
The problem is, if there are at least two plugins with the same name (say hook and hoster) - like there was with `HighWayMe`, one plugin overwrite the other''s setting.
This also happens in `0.4.10` too (https://github.com/vuolter/pyload/blob/0.4.10/pyload/manager/Plugin.py).
the correct desired behavior should be a merge of all settings from all plugins of the same name, then ,when all plugins parsing finished, removing all other unused setting of that section on `plugin.conf`

**Comment by GammaC0de** [comment]
edit: actually this does not happen in `0.4.10` because the section name now includes to folder name also

**Comment by nomad71** [comment]
Just curious: Might this be the reason why some settings aren't persistent?

**Comment by vuolter** [comment]
@nomad71 According my preliminary tests: yes. HighWayMe.py hook must be renamed to HighWayMeHook.py just in stable.
