### ISSUE TITLE
"Failed activating ExternalScripts" ?!

### ISSUE THREAD

**Issue by cab1** [pyload/pyload#1542]
With pyload 0.4.9, python 2.7.3 I get "WARNING Failed activating ExternalScripts" on startup in the log message. Has anybody seen the same or even solved this problem?
Thanks very much!!

**Comment by GammaC0de** [comment]
Hi,
Please enable debug mode then post full log.

**Comment by cab1** [comment]
line 216...

212	30.06.2015 21:01:43	INFO	restarting pyLoad
213	30.06.2015 21:01:43	INFO	shutting down...
214	30.06.2015 21:01:46	INFO	Starting pyLoad 0.4.9
215	30.06.2015 21:01:46	INFO	Using home directory: /home/pld/.pyload
216	30.06.2015 21:01:48	WARNING	Failed activating ExternalScripts
217	30.06.2015 21:01:48	INFO	Activated plugins: CaptchaBrotherhood, ClickAndLoad, ExtractArchive, LinkdecrypterComHook, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
218	30.06.2015 21:01:48	INFO	Deactivate plugins: AlldebridComHook, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaTrader, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, Ev0InFetcher, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMe, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCz, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridCom, RealdebridComHook, RehostTo, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
219	30.06.2015 21:01:48	INFO	Downloadtime: True
220	30.06.2015 21:01:48	INFO	Starting ThriftBackend: 0.0.0.0:7227
221	30.06.2015 21:01:48	INFO	Free space: 1.96 GiB
222	30.06.2015 21:01:49	INFO	Starting threaded webserver: 10.0.0.148:8000
223	30.06.2015 21:01:49	INFO	Activating Accounts...
224	30.06.2015 21:01:49	INFO	Activating Plugins...
225	30.06.2015 21:01:49	ERROR	Error executing hooks: 'ExtractArchive' object has no attribute 'pyfile'
226	30.06.2015 21:01:49	INFO	pyLoad is up and running
227	30.06.2015 21:01:51	ERROR	Error executing hooks: 'LinkdecrypterComHook' object has no attribute 'pyfile'
Jump to time:

**Comment by GammaC0de** [comment]
Have you enabled debug mode? (config -> general -> Debug Mode: on)

**Comment by cab1** [comment]
Upps, forgot to [submit]. Sorry! 
Again:


230	30.06.2015 22:58:44	INFO	Starting pyLoad 0.4.9
231	30.06.2015 22:58:44	INFO	Using home directory: /home/pld/.pyload
232	30.06.2015 22:58:44	DEBUG	Remote activated: True
233	30.06.2015 22:58:46	DEBUG	created index of plugins
234	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
235	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.internal.Hook -> userplugins.internal.Hook
236	30.06.2015 22:58:46	WARNING	Failed activating ExternalScripts
237	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
238	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
239	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
240	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
241	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
242	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
243	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.hooks.LinkdecrypterComHook -> userplugins.hooks.LinkdecrypterComHook
244	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.internal.MultiHook -> userplugins.internal.MultiHook
245	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.crypter.LinkdecrypterCom -> userplugins.crypter.LinkdecrypterCom
246	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.internal.Crypter -> userplugins.internal.Crypter
247	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
248	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
249	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
250	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.hooks.CaptchaBrotherhood -> userplugins.hooks.CaptchaBrotherhood
251	30.06.2015 22:58:46	DEBUG	Redirected import module.plugins.hooks.UserAgentSwitcher -> userplugins.hooks.UserAgentSwitcher
252	30.06.2015 22:58:46	INFO	Activated plugins: CaptchaBrotherhood, ClickAndLoad, ExtractArchive, LinkdecrypterComHook, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
253	30.06.2015 22:58:46	INFO	Deactivate plugins: AlldebridComHook, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaTrader, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, Ev0InFetcher, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMe, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCz, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridCom, RealdebridComHook, RehostTo, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
254	30.06.2015 22:58:46	INFO	Downloadtime: True
255	30.06.2015 22:58:46	INFO	Starting ThriftBackend: 0.0.0.0:7227
256	30.06.2015 22:58:47	INFO	Starting threaded webserver: 10.0.0.148:8000
257	30.06.2015 22:58:47	INFO	Free space: 1.96 GiB
258	30.06.2015 22:58:47	INFO	Activating Accounts...
259	30.06.2015 22:58:47	INFO	Activating Plugins...
260	30.06.2015 22:58:47	DEBUG	Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
261	30.06.2015 22:58:47	DEBUG	Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
262	30.06.2015 22:58:47	ERROR	Error executing hooks: 'ExtractArchive' object has no attribute 'pyfile'
263	30.06.2015 22:58:47	INFO	pyLoad is up and running
264	30.06.2015 22:58:49	ERROR	Error executing hooks: 'LinkdecrypterComHook' object has no attribute 'pyfile'

**Comment by GammaC0de** [comment]
what is the version of your `internal/Plugin.py` and `internal/Hook.py`?

**Comment by cab1** [comment]
I dont know. Its not written in these files. On .pyload "files.version" says "4" and I got the program from the website in June.

**Comment by GammaC0de** [comment]
open `Plugin.py` with notepad and look for `__version__ =` line.

**Comment by cab1** [comment]
ok. Thanks!
Plugin.py: 0.06
Hook.py: 0.02

**Comment by GammaC0de** [comment]
As I suspected, they are old and not current.
Does `UpdateManager` plugin enabled?

**Comment by cab1** [comment]
yes it is enabled

**Comment by GammaC0de** [comment]
OK then,
Shutdown pyload then find a directory called `userplugins`.
Rename it to `userplugins.old`.
Start pyload again.

**Comment by cab1** [comment]
:-) you got it. Warning vanished!
A script in scripts/pyload_restart/ is still not executed but this might be a further issue.
Thanks much!!!

**Comment by GammaC0de** [comment]
:+1:
@vuolter please close
