### ISSUE TITLE
OboomCom: Could not login with account xxxxxxxxxxxxx | (35, 'error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure') 

### ISSUE THREAD

**Issue by FeGitHub** [pyload/pyload#1545]
I am getting the following warning since a few days:

WARNING OboomCom: Could not login with account xxxxxxxxxxxxx | (35, 'error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure') 

pyload 0.4.9 - fresh install

**Comment by strikegun** [comment]
some for me. please look at it

**Comment by ekitm** [comment]
dito

**Comment by Sle3perX** [comment]
Fresh install, got the same error.
Even reinstalled my Synology NAS.

**Comment by socruel** [comment]
same here since a few days :-(

**Comment by giawaepa** [comment]
oboom changed owner and moved. they shut down ssl3 i think

check if wget oboom.com or wget https://oboom.com works

**Comment by Sle3perX** [comment]
Still not working.
Deinstalled "wget" and installed "wget-ssl" over IPKG to support https but i get this error from putty.

wget oboom.com
--2015-07-26 11:30:18--  http://oboom.com/
Resolving oboom.com (oboom.com)... 108.162.195.126, 108.162.194.126
Connecting to oboom.com (oboom.com)|108.162.195.126|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.oboom.com/ [following]
--2015-07-26 11:30:18--  https://www.oboom.com/
Resolving www.oboom.com (www.oboom.com)... 108.162.194.126, 108.162.195.126
Connecting to www.oboom.com (www.oboom.com)|108.162.194.126|:443... connected.
OpenSSL: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
Unable to establish SSL connection.

**Comment by giawaepa** [comment]
same here but curl -L oboom.com works

which os? i have ubuntu 12.04 LTS have to check if wget support TLS above v1

**Comment by Sle3perX** [comment]
I'm on Synology 5.2-5592 Update 1 (DS214play).
Any idea, how i can resolve the problem?

**Comment by FeGitHub** [comment]
I reverted all changes from Fix #1545 and the warning from initial post does not appear anymore.
Still got the problem with #1799
