### ISSUE TITLE
Uploaded and Zippy

### ISSUE THREAD

**Issue by R3alflash** [pyload/pyload#1547]
Since yesterday i have littlebit trouble with zippyshare and uploaded.to too. Here is the log:

449	30.06.2015 07:14:27	WARNING	Download failed: gamexxxxxxxx.part37.rar | long int too large to convert to int
450	30.06.2015 07:14:27	DEBUG	Error creating zip file: 'ascii' codec can't decode byte 0xcd in position 10: ordinal not in range(128) 

and zippy:

375	30.06.2015 07:14:15	WARNING	ReCaptcha: Key pattern not found
376	30.06.2015 07:14:16	INFO	Download skipped: gamexxxxxxxpart32.rar due to ZippyshareCom
377	30.06.2015 07:14:18	INFO	Download skipped: gamexxxxxxpart33.rar due to ZippyshareCom
378	30.06.2015 07:14:20	WARNING	Download failed: gamexxxxxxxx.part10.rar | Parse error: No file downloaded | Plugin may be out of date

**Comment by vuolter** [comment]
@R3alflash Still not working?

**Comment by R3alflash** [comment]
yes this is working again, since update in august. This issue can be close :)
