### ISSUE TITLE
CnL missing option to directly add to queue

### ISSUE THREAD

**Issue by I-RiX-I** [pyload/pyload#1549]
CnL is working thus far (also remotely), but it sends files to the link collector.

I have never used this feature and an option to send links directly to the queue would help.

Thank you!

**Comment by NETHeader** [comment]
Maybe this is a feature of the client?
I use CnL in conjunction with Flashgot & Firefox and there is an option for "Start downloads immediately", and activating it pushes new links into the queue, not into the collector.

**Comment by vuolter** [comment]
Done.
