### ISSUE TITLE
Debriditalia fails to download as premium users

### ISSUE THREAD

**Issue by Issam2204** [pyload/pyload#1551]
Hello!

Using pyLoad 0.4.9 on Ubuntu 14.04.02 LTS x64.

When trying to download a file from a supported host of DebridItalia(.com) (using a correctly recognized premium account) I can't download anything. The DebridItalia(.com) plugin doesn't "kick in" to download the file(s). Logs show nothing:

> 08.07.2015 17:35:51 INFO      Added package TEST containing 1 links
> 08.07.2015 17:35:52 INFO      Download starts: TEST.avi
> 08.07.2015 17:35:52 WARNING   Download failed: TEST.avi | File can be downloaded by premium users only
> 08.07.2015 17:35:52 INFO      UnSkipOnFail: Looking for skipped duplicates of: TEST.avi (pid:2)
> 08.07.2015 17:35:52 INFO      UnSkipOnFail: No duplicates found

Issues occur with several (all?) different hosts, while on their website (through link generation) everything works.

Thank you!

**Comment by Velociraptor85** [comment]
@GammaC0de I guess one can close this for now? or @Issam2204 do you still have a premium account there?

**Comment by Issam2204** [comment]
> @GammaC0de I guess one can close this for now? or @Issam2204 do you still have a premium account there?

No, I don't have an account anymore. Thanks anyway.
