### ISSUE TITLE
Error during checking new pyload version and plugin updates

### ISSUE THREAD

**Issue by moacmoa** [pyload/pyload#1553]
On the first pyload launch :
404 error found during checking new pyload version.
And no plugin updates...

-----------------------------------------------------------------------------------------------------------------
> 10.07.2015 23:59:58 INFO      Démarrage pyLoad 0.4.9
> 10.07.2015 23:59:58 INFO      Utilisation du dossier principal : /home/dl/.pyload
> 10.07.2015 23:59:59 INFO      ExtractArchive: No UnRar installed
> 11.07.2015 00:00:00 INFO      ExtractArchive: Activated UnZip
> 11.07.2015 00:00:00 INFO      Plugins activés: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
> 11.07.2015 00:00:00 INFO      Plugins désactivés: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
> 11.07.2015 00:00:00 INFO      Temps de téléchargement : True
> 11.07.2015 00:00:00 INFO      Démarre ThriftBackend: 0.0.0.0:7227
> 11.07.2015 00:00:01 INFO      Free space: 184.33 GiB
> 11.07.2015 00:00:01 INFO      Starting builtin webserver: 0.0.0.0:8000
> 11.07.2015 00:00:01 INFO      Activating Accounts...
> 11.07.2015 00:00:01 INFO      Activating Plugins...
> 11.07.2015 00:00:01 INFO      pyLoad is up and running
> 11.07.2015 00:00:03 INFO      ***  New pyLoad Version
> <html><head>
> <meta http-equiv="content-type" content="text/html;charset=utf-8">
> <title>404 Not Found</title>
> </head>
> <body text=#000000 bgcolor=#ffffff>
> <h1>Error: Not Found</h1>
> <h2>The requested URL <code>/check/0.4.9/</code> was not found on this server.</h2>
> <h2></h2>
> </body></html>
>  available  ***
> 11.07.2015 00:00:03 INFO      ***  Get it here: http://pyload.org/download  ***
> 11.07.2015 00:00:03 INFO      No plugin updates available
-------------------------------------------------------------------------------------------------------

**Comment by Saudumm** [comment]
same here.

**Comment by Brice187** [comment]
i think some changed the folder structure on the server :(

**Comment by moacmoa** [comment]
Apparently already fixed :-)

**Comment by RaNaN** [comment]
Our updating app is quite old and deprecated on the server structure. It will be completely unavailable after August 3, 2015.

**Comment by Saudumm** [comment]
And what happens after then?

**Comment by stickell** [comment]
Just download this:
https://raw.githubusercontent.com/pyload/pyload/stable/module/plugins/hooks/UpdateManager.py
And put it in your `userplugins/hooks` folder

**Comment by Brice187** [comment]
12.07.2015 09:21:34	INFO	starte pyLoad 0.4.9
326	12.07.2015 09:21:34	INFO	Benutze Home-Verzeichnis: /e-data/4db3ed06-0ca0-4c96-8242-cc50547be640/ffproot/ffp/opt/pyLoad
327	12.07.2015 09:21:36	ERROR	Fehler beim importieren von UpdateManager: No module named Hook
328	12.07.2015 09:21:36	ERROR	Fehler beim importieren von ExtractArchive: No module named AbstractExtractor
329	12.07.2015 09:21:36	INFO	Aktivierte Plugins: ClickAndLoad, ExternalScripts
330	12.07.2015 09:21:36	INFO	Deaktivierte Plugins: HotFolder, IRCInterface, MergeFiles, MultiHome, XMPPInterface
331	12.07.2015 09:21:36	INFO	Downloadzeit: True
332	12.07.2015 09:21:37	INFO	Free space: 1.10 TiB
333	12.07.2015 09:21:37	INFO	Starting threaded webserver: 0.0.0.0:8000
334	12.07.2015 09:21:37	INFO	Activating Accounts...
335	12.07.2015 09:21:38	INFO	Activating Plugins...
336	12.07.2015 09:21:38	INFO	pyLoad is up and running

**Comment by Brice187** [comment]
stickell, your workaround does not fix the problem :(

**Comment by ms81** [comment]
Had the same problem.

Try this:
https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py

And put it in your userplugins/hooks folder

This worked for me.

**Comment by stickell** [comment]
@ms81's solution should be fine

**Comment by Brice187** [comment]
Yes, @ms81 solution works

**Comment by iswt76** [comment]
Just made fresh install, but @ms81 doesnt work

**Comment by vuolter** [comment]
The new UpdateManager in 0.4.10 will connect to github directly. ;)

**Comment by iswt76** [comment]
Cannot find any release date for new version :-(

**Comment by stickell** [comment]
You can download the `stable` branch of this repo so you will get 0.4.9 with updated plugins:
https://github.com/pyload/pyload/archive/stable.zip

**Comment by iswt76** [comment]
@stickell : well, this version starts without errors... But is not working with download.serienjunkies.org and i cannot add ul.to premium account... After reading several forums it seems that after vuolters last patchbomb, there are a lot of things not working anymore... I think i'll have to wait for next version... Meantime i'll switch back to jdownloader :-1:

**Comment by vuolter** [comment]
@iswt76 I'm working on... Please retry now.

**Comment by iswt76** [comment]
No, cannot add ul.to premium account... When i add it manually in ./pyload/accounts.conf... Details are shown ... But downloading fails with CRITICAL error message...

**Comment by vuolter** [comment]
@iswt76 See: https://github.com/pyload/pyload/issues/1578

**Comment by gerrit507** [comment]
Please fix this issue. I'm also stuck on a fresh installation. I copied the whole userplugins folder from source into the pyload config folder, but somehow pyload does not recognize the new plugins, only those which were already installed. And even with the newest UpdateManager.py i can not connect to the update servers. Or could somebody at least tell me how to get pyload to recognize manually added plugins?

**Comment by stickell** [comment]
@gerrit507: Tried a fresh installation using this package?
https://github.com/pyload/pyload/archive/stable.zip

**Comment by gerrit507** [comment]
@stickell Yes, also deleted the config folder of course. It still shows 
15   30.07.2015 13:49:20	WARNING	Not able to connect server for updates
16	30.07.2015 13:49:20	INFO	No Updates for pyLoad
17	30.07.2015 13:49:21	WARNING	Not able to connect server for updates
18	30.07.2015 13:49:21	INFO	No plugin updates available

this project used to be good, but now even updating doesn't work anymore. Besides that installing from zip also only installs the standard plugins and I'm facing the same bug with uploaded as @iswt76 . How could it be that one of the biggest hoster isn't working any more? A few months ago the program was a good download manager, not as good as jDownloader but much better than everything else out there, and now it's totally useless.

**Comment by cavebeat** [comment]
:( i hope also this program is fixing the stable version soon. or at least releases a v0.4.10 (or 5.0)

**Comment by macianer85** [comment]
Probably a stupid question: Where can i find the userplugins/hooks folder? I have a ssh connection to my qnap ts-431. I can't even find the pyload folder... thanks

**Comment by GammaC0de** [comment]
@macianer85 You can see where is your config folder using http://ip-of-your-qnap:8000/info
the userplugins directorey resides under the config folder.
