### ISSUE TITLE
Config in WUI not working

### ISSUE THREAD

**Issue by Velociraptor85** [pyload/pyload#1555]
I pulled a fresh pyload:master and installed it tried it with lightweight and threaded but if you go to the webinterface config menu it shows up empty when you try to change something also I havent found any error or Message in the Logs

Also the error is persistent with Next and Default theme.

![empty config](https://cloud.githubusercontent.com/assets/4143960/8633364/5f31106e-27c4-11e5-987c-d076ad5a60bf.jpg)

**Comment by GammaC0de** [comment]
@Velociraptor85 The best route for installing pyload is to download 0.4.9 release from http://pyload.org/download and then let `UpdateManager` do its job.

**Comment by bkchr** [comment]
Pull request #1559 fixes this bug!
