### ISSUE TITLE
rapidgator filenames not resolved properly (via RealDebrid)

### ISSUE THREAD

**Issue by chaosmaker** [pyload/pyload#1563]
Hi All,

When I download using the RealDebrid plugin from rapidgator the filenames are the full web address. For example: 
```
http://rapidgator.net/file/XXXXXXXXXXXXXXXXX/somefile.fileextention.html
```
instead of
```
somefile.fileextention
```

Not sure why this happens, but while these filenames work on a unix system, on windows they are unrecognisable. 
Any idea on how to fix this?

Thanks

**Comment by vuolter** [comment]
Please retry now.
