### ISSUE TITLE
[Error 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird

### ISSUE THREAD

**Issue by GamesGamble** [pyload/pyload#1567]
debug: http://www.xup.in/a,19188/Pyload_Log/

[Error 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird
Pyload Error

**Comment by vuolter** [comment]
English please!

**Comment by vuolter** [comment]
English please!

**Comment by NothingTV** [comment]
Got the same issue several times now. The error message is as GamesGamble already said: [Error 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

In English: The process cannot access the file because it is being used by another process. Looks like a Windows permission conflict.

Debug: 
> pyLoad 0.4.20 Debug Report of OneFichierCom 1.18 
> 
> TRACEBACK:
>  Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\pyload\dist\.\module\PluginThread.py", line 187, in run
>   File "C:\Users\Administrator\Desktop\pyload\data\userplugins\internal\Base.py", line 291, in preprocessing
>   File "C:\Users\Administrator\Desktop\pyload\data\userplugins\internal\Hoster.py", line 118, in _process
>   File "C:\Users\Administrator\Desktop\pyload\data\userplugins\internal\SimpleHoster.py", line 287, in process
>   File "C:\Users\Administrator\Desktop\pyload\data\userplugins\internal\Hoster.py", line 308, in download
>   File "C:\Users\Administrator\Desktop\pyload\data\userplugins\internal\Hoster.py", line 237, in _download
>   File "C:\Users\Administrator\Desktop\pyload\dist\.\module\network\Browser.py", line 89, in httpDownload
>   File "C:\Users\Administrator\Desktop\pyload\dist\.\module\network\HTTPDownload.py", line 130, in download
>   File "C:\Users\Administrator\Desktop\pyload\dist\.\module\network\HTTPDownload.py", line 298, in _download
>   File "C:\Users\Administrator\Desktop\pyload\dist\.\module\network\HTTPDownload.py", line 120, in _copyChunks
>   File "shutil.pyc", line 326, in move
> WindowsError: [Error 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: u'C:\\Users\\Administrator\\Downloads\\****censored****.chunk0'
