### ISSUE TITLE
EasyBytez You've used all Leech traffic today

### ISSUE THREAD

**Issue by Stufo76** [pyload/pyload#1569]
Same issue #1441, below my debug log:

15.07.2015 10:52:20 INFO Download starts: INT3RST3LL4R.14.BD.DDN.part095.rar
15.07.2015 10:52:20 DEBUG UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
15.07.2015 10:52:20 DEBUG EasybytezCom[106]: Update file info...
15.07.2015 10:52:20 DEBUG EasybytezCom[106]: Previous file info: {}
15.07.2015 10:52:20 DEBUG EasybytezCom[106]: Current file info: {'status': 2, 'url': u'http://www.easybytez.com/wo43e6tw18st', 'size': 267386880.0, 'name': u'INT3RST3LL4R.14.BD.DDN.part095.rar', 'pattern': {'S': u'255.0', 'U': u'MB', 'N': u'INT3RST3LL4R.14.BD.DDN.part095.rar'}}
15.07.2015 10:52:20 DEBUG EasybytezCom[106]: File name: INT3RST3LL4R.14.BD.DDN.part095.rar | File size: 267386880 byte
15.07.2015 10:52:20 DEBUG EasybytezCom[106]: File status: online
15.07.2015 10:52:20 DEBUG EasybytezCom[106]: Looking for direct download link...
15.07.2015 10:52:20 DEBUG EasybytezCom[106]: Redirect #0 to: http://www.easybytez.com/wo43e6tw18st
15.07.2015 10:52:21 DEBUG EasybytezCom[106]: Direct download link not found
15.07.2015 10:52:21 DEBUG EasybytezCom[106]: Looking for leeched download link...
15.07.2015 10:52:21 DEBUG EasybytezCom[106]: http://wrk25.easybytez.com/cgi-bin/upload.cgi?upload_id=702044854618&js_on=1&utype=prem&upload_type=url | {'up1oad_type': 'url', 'link_rcpt': '', 'url_mass': u'http://www.easybytez.com/wo43e6tw18st', 'sess_id': 'rzo2ne83fud866nh', 'submit_btn': ' Upload! ', 'file_1': 'getElementById(\'my_file_element\').value;"', 'tos': '1', 'upload_type': 'file', 'link_pass': '', 'srv_tmp_url': 'http://wrk25.easybytez.com/tmp'}
15.07.2015 10:52:26 DEBUG EasybytezCom[106]: {'op': 'upload_result', 'fn': 'INT3RST3LL4R.14.BD.DDN.part095.rar', 'st': "You've used all Leech traffic today"}

**Comment by vuolter** [comment]
Fixed.
