### ISSUE TITLE
https redirect on DSM 5592 Update 1

### ISSUE THREAD

**Issue by skyphab** [pyload/pyload#1572]
Looks like there is a change in https/http-behaviour with Synology DSM 5.2-5592 Update 1:
After the update I couldn't connect anymore to my pyload-server on my NAS. I saw, that the http-connection was redirected to https which was wrong.

Waiting for the connection fail and replacing https with http in the address works. After the login this has to be done again.
I have https-connections active in my NAS-settings, but before Update 1 the pyload-server wasn't affected. Now it looks like the browser (Safari) is forced to connect with https to the pyload-webserver, too.

Is that a bug in pyload or DSM?

**Comment by vuolter** [comment]
DSM sorry.
