### ISSUE TITLE
uptobox: codec can't encode character

### ISSUE THREAD

**Issue by anthony-ra** [pyload/pyload#1573]
Hello,

I have the same issue #1110 for uptobox:

Life_-_L'aventure_de_la_vie_-_03_Les_mammifères_-_Arte_HD_1080p.avi
failed'ascii' codec can't encode character u'\xe8' in position 127: ordinal not in range(128) 1.30 GiBUptoboxCom

hope that help... a bit

**Comment by vuolter** [comment]
Please update and retry. Otherwise post a sample url. Thanks.

**Comment by anthony-ra** [comment]
I can't update. this the log:
28.07.2015 17:47:56	WARNING	Not able to connect server for updates
913	28.07.2015 17:47:56	INFO	No plugin updates available

**Comment by anthony-ra** [comment]
And this a sample url:
http://uploaded.net/file/66ffrw3h
I think that it's due to the "é" in the filename
