### ISSUE TITLE
pyLoadGui error No module named Connector

### ISSUE THREAD

**Issue by borlox** [pyload/pyload#1579]
Starting pyLoadGui results in the error message

    Traceback (most recent call last):
      File "/usr/bin/pyLoadGui", line 41, in <module>
        from module.gui.Connector import Connector
    ImportError: No module named Connector

followed by the termination of the program. The cause of this issue is, that the file of the Connector module in module/gui/ is acutually called "connector.py" with a lowercase c. On arch (and I'd guess any other) linux this prevents python from finding the file.

This can easily be fixed by changing [line 41](https://github.com/pyload/pyload/blob/stable/pyLoadGui.py#L41) to

    from module.gui.connector import Connector

or alternatively renaming "module/gui/connector.py" to "Connector.py"

Thank you.

**Comment by vuolter** [comment]
Interesting, but there will no gui in 0.4.10 . :(

**Comment by alexanderadam** [comment]
@borlox thank you for the hint!
