### ISSUE TITLE
Captcha9Kw/DeathByCaptcha - cannot import name threaded

### ISSUE THREAD

**Issue by kasperj** [pyload/pyload#1580]
28.07.2015 10:35:07	ERROR	Fehler beim importieren von Captcha9Kw: cannot import name threaded
28.07.2015 10:35:07	ERROR	Fehler beim importieren von DeathByCaptcha: cannot import name threaded

Similar to this one
https://github.com/pyload/pyload/issues/1577

**Comment by Eisfreak7** [comment]
I have the same problem.
The cause seems to be that those plugins try to import "threaded" form /opt/pyload/module/plugins/internal/hook.py but the hook.py file isn't in the internal folder but directly in the plugins folder.
Hard linking it to the internal folder changes the error message to
  cannot import name Base
Maybe there has been a change in the folder structure recently?

**Comment by vuolter** [comment]
@Eisfreak7 PLease try: http://forum.pyload.org/viewtopic.php?f=7&t=4335

**Comment by kasperj** [comment]
Fix is working, thanks for the quick fix!

**Comment by Eisfreak7** [comment]
Renaming both accounts.conf and userplugins results in 
```
28.07.2015 18:16:38	WARNING	Not able to connect server for updates
855	28.07.2015 18:16:38	INFO	No plugin updates available 
```
The machine has access to the internet however. A 'ping www.google.com' is successful.

**Comment by c0rrre** [comment]
Same here

**Comment by vuolter** [comment]
Please try: http://forum.pyload.org/viewtopic.php?f=7&t=4335
Updated built-in packages for 0.4.9 will be released soon as ready.

**Comment by Eisfreak7** [comment]
Isn't that the exact same link as before?
Like I said, that unfortunately doesn't seem to work.

**Comment by vuolter** [comment]
@Eisfreak7 Workaround: http://forum.pyload.org/viewtopic.php?f=7&t=4408#p18856

**Comment by Eisfreak7** [comment]
Replacing the /opt/module/plugins folder as well as the pyload/userplugins one (I don't really understand the difference) works, thanks!

However, now the AntiStandby plugin gives these errors:
```
WARNING	HOOK AntiStandby: Unable to change power state | [Errno 2] No such file or directory 
ERROR	HOOK AntiStandby: Error executing addon: 'ascii' codec can't decode byte 0xe4 in position 29: ordinal not in range(128) 
```
And captcha9kw still doesn't work

**Comment by vuolter** [comment]
@Eisfreak7 Please retry now. If you detect any issue please open a new ticket.
