### ISSUE TITLE
Every Script call fails with: global name '' is not defined

### ISSUE THREAD

**Issue by venious** [pyload/pyload#1582]
28.07.2015 18:46:05	ERROR	HOOK ExternalScripts : Runtime error: .sh | global name 'isinstande' is not defined

28.07.2015 19:00:10	WARNING	Download failed: .rar | global name 'task' is not defined

28.07.2015 19:00:12	WARNING	Download failed: .rar | global name 'task' is not defined

**Comment by vuolter** [comment]
Noooo... unbelievable. XD
