### ISSUE TITLE
'UploadedTo' object has no attribute 'lastDownload' and only 1 download at a time

### ISSUE THREAD

**Issue by c0rrre** [pyload/pyload#1583]
Hi, 

i tried to download a file with uploaded.to premium, but i can only download 1 file at once.
It should allow 4 parallel downloads.

and ill got

Download failed: XXXXXXXXXX.part01.rar | 'UploadedTo' object has no attribute 'lastDownload'

**Comment by vuolter** [comment]
Checking...
