### ISSUE TITLE
UploadedTo Plugin - no mutiple downloads

### ISSUE THREAD

**Issue by kasperj** [pyload/pyload#1584]
There is always just one download at the same time, no multiple downloads

1898	28.07.2015 23:43:34	INFO	Download finished: tvp-lastship-s02e07-1080p.part02.rar
1897	28.07.2015 23:43:34	INFO	HOSTER UploadedTo[63] : No errors found
1896	28.07.2015 23:43:34	DEBUG	HOSTER UploadedTo[63] : Using custom check rules...
1895	28.07.2015 23:43:34	DEBUG	HOSTER UploadedTo[63] : Using default check rules...
1894	28.07.2015 23:43:34	INFO	HOSTER UploadedTo[63] : Checking file...
1893	28.07.2015 23:43:34	INFO	HOSTER UploadedTo[63] : 8b66fb9d-9b44-4ebb-9860-1e89c94a0f07 saved as tvp-lastship-s02e07-1080p.part02.rar
1892	28.07.2015 23:43:34	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440935004.221353, 'valid': True, 'trafficleft': 545213885972.48, 'timestamp': 1438119804.071478, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1891	28.07.2015 23:43:32	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440935004.221353, 'valid': True, 'trafficleft': 545213885972.48, 'timestamp': 1438119804.071478, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1890	28.07.2015 23:43:30	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440935004.221353, 'valid': True, 'trafficleft': 545213885972.48, 'timestamp': 1438119804.071478, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1889	28.07.2015 23:43:28	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440935004.221353, 'valid': True, 'trafficleft': 545213885972.48, 'timestamp': 1438119804.071478, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1888	28.07.2015 23:43:26	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440935004.221353, 'valid': True, 'trafficleft': 545213885972.48, 'timestamp': 1438119804.071478, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1887	28.07.2015 23:43:24	DEBUG	Content-Disposition: tvp-lastship-s02e07-1080p.part02.rar
1886	28.07.2015 23:43:24	DEBUG	HOSTER UploadedTo[63] : DOWNLOAD URL http://am4-r1f2-stor09.uploaded.net/dl/8b66fb9d-9b44-4ebb-9860-1e89c94a0f07 | cookies=True | get={} | disposition=True | post={} | ref=True
1885	28.07.2015 23:43:24	INFO	HOSTER UploadedTo[63] : Downloading file...
1884	28.07.2015 23:43:24	INFO	HOSTER UploadedTo[63] : Direct download link detected
1883	28.07.2015 23:43:24	DEBUG	HOSTER UploadedTo[63] : LOAD URL http://uploaded.net/file/zrtcghxx | cookies=True | get={} | req=None | decode=True | just_header=True | post={} | ref=True
1882	28.07.2015 23:43:24	DEBUG	HOSTER UploadedTo[63] : Redirect #0 to: http://uploaded.net/file/zrtcghxx
1881	28.07.2015 23:43:24	INFO	HOSTER UploadedTo[63] : Looking for direct download link...
1880	28.07.2015 23:43:24	INFO	HOSTER UploadedTo[63] : File status: online
1879	28.07.2015 23:43:24	INFO	HOSTER UploadedTo[63] : File size: 105906176 bytes
1878	28.07.2015 23:43:24	INFO	HOSTER UploadedTo[63] : File name: tvp-lastship-s02e07-1080p.part02.rar
1877	28.07.2015 23:43:24	DEBUG	HOSTER UploadedTo[63] : Previous file info: {}
1876	28.07.2015 23:43:24	DEBUG	HOSTER UploadedTo[63] : File info: {'status': 2, 'url': u'http://uploaded.net/file/zrtcghxx', 'size': 105906176.0, 'name': 'tvp-lastship-s02e07-1080p.part02.rar', 'pattern': {'ID': u'zrtcghxx'}}
1875	28.07.2015 23:43:24	INFO	HOSTER UploadedTo[63] : Updating file info...
1874	28.07.2015 23:43:24	DEBUG	HOSTER UploadedTo[63] : PROCESS URL http://uploaded.net/file/zrtcghxx
1873	28.07.2015 23:43:24	DEBUG	HOOK UserAgentSwitcher : Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
1872	28.07.2015 23:43:24	INFO	Download starts: tvp-lastship-s02e07-1080p.part02.rar
1871	28.07.2015 23:43:24	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440935004.221353, 'valid': True, 'trafficleft': 545213885972.48, 'timestamp': 1438119804.071478, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1870	28.07.2015 23:43:24	DEBUG	ACCOUNT UploadedTo : LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | just_header=False | post={} | ref=True
1869	28.07.2015 23:43:24	INFO	ACCOUNT UploadedTo : Parsing account info for user `13153325`...
1868	28.07.2015 23:43:22	INFO	Download finished: tvp-lastship-s02e07-1080p.part01.rar
1867	28.07.2015 23:43:22	INFO	HOSTER UploadedTo[62] : No errors found
1866	28.07.2015 23:43:22	DEBUG	HOSTER UploadedTo[62] : Using custom check rules...
1865	28.07.2015 23:43:22	DEBUG	HOSTER UploadedTo[62] : Using default check rules...
1864	28.07.2015 23:43:22	INFO	HOSTER UploadedTo[62] : Checking file...
1863	28.07.2015 23:43:22	INFO	HOSTER UploadedTo[62] : 0d9e05a0-f716-4584-8400-cbe4705b81c1 saved as tvp-lastship-s02e07-1080p.part01.rar
1862	28.07.2015 23:43:22	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440934984.036255, 'valid': True, 'trafficleft': 545310522736.64, 'timestamp': 1438119783.919216, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1861	28.07.2015 23:43:20	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440934984.036255, 'valid': True, 'trafficleft': 545310522736.64, 'timestamp': 1438119783.919216, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1860	28.07.2015 23:43:18	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440934984.036255, 'valid': True, 'trafficleft': 545310522736.64, 'timestamp': 1438119783.919216, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1859	28.07.2015 23:43:16	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440934984.036255, 'valid': True, 'trafficleft': 545310522736.64, 'timestamp': 1438119783.919216, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1858	28.07.2015 23:43:14	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440934984.036255, 'valid': True, 'trafficleft': 545310522736.64, 'timestamp': 1438119783.919216, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1857	28.07.2015 23:43:12	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440934984.036255, 'valid': True, 'trafficleft': 545310522736.64, 'timestamp': 1438119783.919216, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1856	28.07.2015 23:43:10	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440934984.036255, 'valid': True, 'trafficleft': 545310522736.64, 'timestamp': 1438119783.919216, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1855	28.07.2015 23:43:08	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440934984.036255, 'valid': True, 'trafficleft': 545310522736.64, 'timestamp': 1438119783.919216, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1854	28.07.2015 23:43:06	DEBUG	ACCOUNT UploadedTo : Account info for user `13153325`: {'login': {'timestamp': 1438119738.959025, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440934984.036255, 'valid': True, 'trafficleft': 545310522736.64, 'timestamp': 1438119783.919216, 'maxtraffic': None, 'premium': True, 'login': '13153325', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
1853	28.07.2015 23:43:04	DEBUG	Content-Disposition: tvp-lastship-s02e07-1080p.part01.rar
1852	28.07.2015 23:43:04	DEBUG	HOSTER UploadedTo[62] : DOWNLOAD URL http://am4-r1f6-stor05.uploaded.net/dl/0d9e05a0-f716-4584-8400-cbe4705b81c1 | cookies=True | get={} | disposition=True | post={} | ref=True
1851	28.07.2015 23:43:04	INFO	HOSTER UploadedTo[62] : Downloading file...
1850	28.07.2015 23:43:04	INFO	HOSTER UploadedTo[62] : Direct download link detected
1849	28.07.2015 23:43:04	DEBUG	HOSTER UploadedTo[62] : LOAD URL http://uploaded.net/file/h5ia0saa | cookies=True | get={} | req=None | decode=True | just_header=True | post={} | ref=True
1848	28.07.2015 23:43:04	DEBUG	HOSTER UploadedTo[62] : Redirect #0 to: http://uploaded.net/file/h5ia0saa
1847	28.07.2015 23:43:04	INFO	HOSTER UploadedTo[62] : Looking for direct download link...
1846	28.07.2015 23:43:04	INFO	HOSTER UploadedTo[62] : File status: online
1845	28.07.2015 23:43:04	INFO	HOSTER UploadedTo[62] : File size: 105906176 bytes
1844	28.07.2015 23:43:04	INFO	HOSTER UploadedTo[62] : File name: tvp-lastship-s02e07-1080p.part01.rar
1843	28.07.2015 23:43:04	DEBUG	HOSTER UploadedTo[62] : Previous file info: {}
1842	28.07.2015 23:43:04	DEBUG	HOSTER UploadedTo[62] : File info: {'status': 2, 'url': u'http://uploaded.net/file/h5ia0saa', 'size': 105906176.0, 'name': 'tvp-lastship-s02e07-1080p.part01.rar', 'pattern': {'ID': u'h5ia0saa'}}
1841	28.07.2015 23:43:04	INFO	HOSTER UploadedTo[62] : Updating file info...
1840	28.07.2015 23:43:04	DEBUG	HOSTER UploadedTo[62] : PROCESS URL http://uploaded.net/file/h5ia0saa
1839	28.07.2015 23:43:04	DEBUG	HOOK UserAgentSwitcher : Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
1838	28.07.2015 23:43:04	INFO	Download starts: tvp-lastship-s02e07-1080p.part01.rar

**Comment by kasperj** [comment]
New github clone fixed the issue, working with newest git version!

**Comment by 1337sup3rh4x0r** [comment]
what exactly did you clone? the entire repo or just the userplugins folder into your user config folder?

**Comment by kasperj** [comment]
Cloned the full repo, which fixed some other Bugs too, for example the issue some settings aren't persistent, like the send2trash issue, config folder was left untouched
