### ISSUE TITLE
Premium Download from ShareonlineBiz not possible, TypeError: invalid arguments to setopt

### ISSUE THREAD

**Issue by wweich** [pyload/pyload#1589]
When trying to download a file from share-online.biz with premium account, I get the following errors:
```
29.07.2015 08:12:55 WARNING   ACCOUNT ShareonlineBiz : Error loading info for user `**********` | invalid arguments to setopt
Traceback (most recent call last):
  File "/opt/pyload/userplugins/internal/Account.py", line 245, in _parse_info
    extra_info = self.parse_info(user, info['login']['password'], info, self.req)
  File "/opt/pyload/userplugins/accounts/ShareonlineBiz.py", line 34, in parse_info
    for line in self.api_response(user, password, req).splitlines():
  File "/opt/pyload/userplugins/accounts/ShareonlineBiz.py", line 24, in api_response
    'password': password})
  File "/opt/pyload/userplugins/internal/Plugin.py", line 294, in load
    res = req.load(url, get, post, ref, cookies, just_header, isinstance(post, dict), decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/usr/share/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 186, in load
    self.setRequestContext(url, get, post, referer, cookies, multipart)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 180, in setRequestContext
    self.getCookies()
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 139, in getCookies
    self.c.setopt(pycurl.COOKIELIST, c)
TypeError: invalid arguments to setopt
```

```
29.07.2015 08:12:55 WARNING   Download failed: ********** | invalid arguments to setopt
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/opt/pyload/userplugins/internal/Hoster.py", line 183, in preprocessing
    return self.process(self.pyfile)
  File "/opt/pyload/userplugins/internal/SimpleHoster.py", line 274, in process
    self.handle_direct(pyfile)
  File "/opt/pyload/userplugins/internal/SimpleHoster.py", line 532, in handle_direct
    self.link = self.direct_link(pyfile.url, self.resume_download)
  File "/opt/pyload/userplugins/internal/Hoster.py", line 538, in direct_link
    res = self.load(url, just_header=True)
  File "/opt/pyload/userplugins/internal/Plugin.py", line 294, in load
    res = req.load(url, get, post, ref, cookies, just_header, isinstance(post, dict), decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/usr/share/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 186, in load
    self.setRequestContext(url, get, post, referer, cookies, multipart)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 180, in setRequestContext
    self.getCookies()
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 139, in getCookies
    self.c.setopt(pycurl.COOKIELIST, c)
TypeError: invalid arguments to setopt
```

I cleared the `tmp` dir for the odd chance, that there was broken cookie data stored.

**Comment by vuolter** [comment]
Full debug log, please.

**Comment by wweich** [comment]
The content of the debug_Report.txt is here: http://pastebin.com/jFE1BykN

**Comment by der10mrx** [comment]
Same for me

**Comment by vuolter** [comment]
Checking...

**Comment by wweich** [comment]
I tried changing that line to `self.c.setopt(pycurl.COOKIELIST, c.encode("UTF-8"))` (did see that in a ticket for UserAgentSwticher and tried it here) which prevents the error but causes my premium account to not being used, as the cookie data is probably invalid.

**Comment by vuolter** [comment]
The problem is that c is equal to this fu**ing crazy string: u'.share-online.biz\tTRUE\t/\tFALSE\t1453709986.14\ta\tAD442EF3F61343EC927623EDD8515CD7904914B292702FE8A56478DEF75E5686950211EE86491AC8CC5470E5E64075ABF80B2ACFDD662EA5901862A2BD3642A5'

**Comment by L0rz** [comment]
same problem : http://pastebin.com/iwMtXXWZ

**Comment by wweich** [comment]
I don't think share-online changed their cookies in the last few days, so pyload could handle their crazy cookies in the past ;-). What changed that?

**Comment by wastez** [comment]
Share Online changed nothing.
I tried it with my backup which is a few days old and with it it is working without problems.

**Comment by no-Legend** [comment]
I got the same problem since a few day.
The behave came after a power shutdown from my supplier.
Before the system restart there was the old version of the plugins used and there i works fine!

**Comment by dhardtke** [comment]
Same here.

**Comment by bepix** [comment]
Just stopping by to state that I've got the same problem and no clue why it doesn't work anymore.

**Comment by vuolter** [comment]
Working on...

**Comment by bepix** [comment]
Thank you very much ... I already tried to resolve it, but I'm lacking in the necessary insight especially with respect to the latest update (which was huge and seems to be the root cause for the issue).

**Comment by godfuture** [comment]
Nowadays I have issues with SO as well. I have deleted the plugin folder due to a "no object type pyfile" error occuring after downloads completed. After cleaning the plugin folder and restart, another issue appeared in log which seems to be the similar to this thread:
```
205	30.07.2015 17:35:22	INFO	ACCOUNT ShareonlineBiz: Parsing account info for user `XXXXXXXXXXX`...
206	30.07.2015 17:35:23	WARNING	ACCOUNT ShareonlineBiz: Error loading info for user `XXXXXXXXXXX` | 'a'
```

**Comment by wweich** [comment]
@godfuture The "no object type pyfile" error has been resolved (today I think).
Check your account.conf, if the password is correct or replaced with ********.
This happens to me, when the currently broken account management changes the account settings.

For the problem at hand: I restored my backup of the userplugin folder from last sunday and "disabled" the UpdateManager to keep to old plugin versions.

**Comment by L0rz** [comment]
it works again! Thx!

**Comment by no-Legend** [comment]
@L0rz 
Just wait a few minutes, during downloading some file, share online account is getting invalid.
But the setoparg error is solved

**Comment by L0rz** [comment]
Error at the Moment:
Download failed: CCRROO.part1.rar | 'super' object has no attribute 'checkFile'
Log:
https://onedrive.live.com/redir?resid=1990D5486CAC82FF!8484&authkey=!AIlty6RKRttq1XE&ithint=file%2czip

**Comment by vuolter** [comment]
@L0rz Your plugin is out of date. u.u

**Comment by L0rz** [comment]
Ok, Thx for your help.

**Comment by wastez** [comment]
I have the same problem.
It´s working at beginning but it stop working after a while.
[code] Log
 lade
   
Reversed:    Lines per page:  
707	02.08.2015 20:51:41	INFO	HOSTER ShareonlineBiz[1671]: WAIT 3 seconds
706	02.08.2015 20:51:41	INFO	HOSTER ShareonlineBiz[1671]: Processing as free download...
705	02.08.2015 20:51:41	INFO	HOSTER ShareonlineBiz[1671]: File status: online
704	02.08.2015 20:51:41	INFO	HOSTER ShareonlineBiz[1671]: File size: 105906176 bytes
703	02.08.2015 20:51:41	INFO	HOSTER ShareonlineBiz[1671]: File name: wcd.x264.S06E06.part1.rar
702	02.08.2015 20:51:41	INFO	HOSTER ShareonlineBiz[1671]: Updating file info...
701	02.08.2015 20:51:41	WARNING	ACCOUNT ShareonlineBiz: Could not login user `XXXXXXXXX` | 'password'
700	02.08.2015 20:51:41	INFO	ACCOUNT ShareonlineBiz: Relogin user `XXXXXXXXX`...
[/code]

**Comment by vuolter** [comment]
Fixed.

**Comment by wastez** [comment]
Ok thanks will Test that.
