### ISSUE TITLE
New CloudSix.me

### ISSUE THREAD

**Issue by Napster32** [pyload/pyload#1591]
Hello at all,
It was recently released a new cloud called CloudSix.me
Recently I use it a lot, you can integrate it into Pyload?
It is very similar to that lately Linestorage.com is always in maintenance.
I await your news.
Bye

**Comment by vuolter** [comment]
One minute please.

**Comment by vuolter** [comment]
Please try: https://github.com/pyload/pyload/commit/c7e2c7771fe6acd64f5ef461bf121fa77ad0c931

**Comment by Napster32** [comment]
CloudSix Work perfectly! Thanks

**Comment by Napster32** [comment]
Hi @vuolter ,
I looked better but unfortunately there are still errors:
30.07.2015 10:44:42	INFO	Download starts: Setupv4.4.2-32.zip
30.07.2015 10:44:42	WARNING	HOSTER XFileSharingPro: CloudsixMe[117] : Config option `use_premium` not found, use default `True`
30.07.2015 10:44:42	INFO	HOSTER XFileSharingPro: CloudsixMe[117] : Updating file info...
30.07.2015 10:44:43	INFO	HOSTER XFileSharingPro: CloudsixMe[117] : File name: Setupv4.4.2-32.zip
30.07.2015 10:44:43	INFO	HOSTER XFileSharingPro: CloudsixMe[117] : File size: 13316915 bytes
30.07.2015 10:44:43	INFO	HOSTER XFileSharingPro: CloudsixMe[117] : File status: online
30.07.2015 10:44:43	INFO	HOSTER XFileSharingPro: CloudsixMe[117] : Processing as free download...
30.07.2015 10:44:43	WARNING	CAPTCHA XFileSharingPro: CloudsixMe[117] : ReCaptcha | Key pattern not found
30.07.2015 10:44:43	WARNING	CAPTCHA XFileSharingPro: CloudsixMe[117] : SolveMedia | Key pattern not found
30.07.2015 10:44:43	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:44:43	INFO	HOSTER XFileSharingPro: CloudsixMe[117] : WAIT 90 seconds
30.07.2015 10:44:43	INFO	HOSTER XFileSharingPro: CloudsixMe[117] : RECONNECT disabled
30.07.2015 10:45:10	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:45:32	INFO	CAPTCHA XFileSharingPro: CloudsixMe[117] : ReCaptcha | Captcha result: must rtGeomp
30.07.2015 10:45:36	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:46:02	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:46:15	INFO	HOSTER XFileSharingPro: CloudsixMe[117] : Downloading file...
30.07.2015 10:46:28	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:46:55	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:47:21	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:47:47	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:48:14	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:48:40	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:49:06	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:49:32	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:49:59	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:50:25	ERROR	HOOK AntiStandby : Error executing addon: ('ascii', '/Office 2013 VL \xe2\x80\x93 SP1 Marzo 2015', 16, 17, 'ordinal not in range(128)')
30.07.2015 10:50:35	INFO	HOSTER XFileSharingPro: CloudsixMe[117] : Checking file...
30.07.2015 10:50:35	INFO	HOSTER XFileSharingPro: CloudsixMe[117] : File deleted
30.07.2015 10:50:35	WARNING	HOSTER XFileSharingPro: CloudsixMe[117] : Config option `fallback` not found, use default `True`
30.07.2015 10:50:35	WARNING	Download failed: Setupv4.4.2-32.zip | File size mismatch | Expected file size: 13316915.2 | Downloaded file size: 13290667
30.07.2015 10:50:35	INFO	HOOK UnSkipOnFail : Looking for skipped duplicates of: Setupv4.4.2-32.zip (pid:24)
30.07.2015 10:50:35	INFO	HOOK UnSkipOnFail : No duplicates found 

The link of files is: http://cloudsix.me/users/cazzone/8811/kms360.1

**Comment by vuolter** [comment]
http://cloudsix.me/ is down.

**Comment by Napster32** [comment]
Hi @vuolter ,
CloudSix.me is not down!
But I discharge from the file by Cloudsix.me (I see that the bar continues downloading) only at the end does not save the file, why?
Look that Error:
177	30.07.2015 15:27:39	INFO	HOSTER XFileSharingPro: CloudsixMe[115] : Downloading file...
178	30.07.2015 15:31:59	INFO	HOSTER XFileSharingPro: CloudsixMe[115] : Checking file...
179	30.07.2015 15:31:59	INFO	HOSTER XFileSharingPro: CloudsixMe[115] : File deleted
180	30.07.2015 15:31:59	WARNING	HOSTER XFileSharingPro: CloudsixMe[115] : Config option `fallback` not found, use default `True`
181	30.07.2015 15:31:59	WARNING	Download failed: Setupv4.4.2-64.zip | File size mismatch | Expected file size: 13316915.2 | Downloaded file size: 13290728
182	30.07.2015 15:31:59	INFO	HOOK UnSkipOnFail : Looking for skipped duplicates of: Setupv4.4.2-64.zip (pid:22)
183	30.07.2015 15:31:59	INFO	HOOK UnSkipOnFail : No duplicates found

WHY THIS?
179	30.07.2015 15:31:59	INFO	HOSTER XFileSharingPro: CloudsixMe[115] : File deleted
Thanks a lot!

**Comment by Napster32** [comment]
Hi @vuolter ,
I have activate the Debig Mode,
But the log is same:

205	30.07.2015 16:44:20	INFO	Download starts: Setupv4.4.2-64.zip
206	30.07.2015 16:44:20	WARNING	HOSTER XFileSharingPro: CloudsixMe[3] : Config option `use_premium` not found, use default `True`
207	30.07.2015 16:44:20	INFO	HOSTER XFileSharingPro: CloudsixMe[3] : Updating file info...
208	30.07.2015 16:44:20	INFO	HOSTER XFileSharingPro: CloudsixMe[3] : File name: Setupv4.4.2-64.zip
209	30.07.2015 16:44:20	INFO	HOSTER XFileSharingPro: CloudsixMe[3] : File size: 13316915 bytes
210	30.07.2015 16:44:20	INFO	HOSTER XFileSharingPro: CloudsixMe[3] : File status: online
211	30.07.2015 16:44:21	INFO	HOSTER XFileSharingPro: CloudsixMe[3] : Processing as free download...
212	30.07.2015 16:44:21	WARNING	CAPTCHA XFileSharingPro: CloudsixMe[3] : ReCaptcha | Key pattern not found
213	30.07.2015 16:44:21	WARNING	CAPTCHA XFileSharingPro: CloudsixMe[3] : SolveMedia | Key pattern not found
214	30.07.2015 16:44:21	INFO	HOSTER XFileSharingPro: CloudsixMe[3] : WAIT 90 seconds
215	30.07.2015 16:44:21	INFO	HOSTER XFileSharingPro: CloudsixMe[3] : RECONNECT disabled
216	30.07.2015 16:44:43	INFO	CAPTCHA XFileSharingPro: CloudsixMe[3] : ReCaptcha | Captcha result: extsafe Occasional
217	30.07.2015 16:45:54	INFO	HOSTER XFileSharingPro: CloudsixMe[3] : Downloading file...
218	30.07.2015 16:50:14	INFO	HOSTER XFileSharingPro: CloudsixMe[3] : Checking file...
219	30.07.2015 16:50:14	INFO	HOSTER XFileSharingPro: CloudsixMe[3] : File deleted
220	30.07.2015 16:50:14	WARNING	HOSTER XFileSharingPro: CloudsixMe[3] : Config option `fallback` not found, use default `True`
221	30.07.2015 16:50:14	WARNING	Download failed: Setupv4.4.2-64.zip | File size mismatch | Expected file size: 13316915.2 | Downloaded file size: 13290728
222	30.07.2015 16:50:14	INFO	HOOK UnSkipOnFail : Looking for skipped duplicates of: Setupv4.4.2-64.zip (pid:3)
223	30.07.2015 16:50:14	INFO	HOOK UnSkipOnFail : No duplicates found

**Comment by vuolter** [comment]
Retry now.

**Comment by Napster32** [comment]
Hi @vuolter ,
I have this error:
02.08.2015 11:18:11	CRITICAL	'CloudsixMe' object has no attribute 'can_use'

**Comment by davboc** [comment]
I have the same error too
