### ISSUE TITLE
cannot add premium account

### ISSUE THREAD

**Issue by raidyne** [pyload/pyload#1592]
cannot add premium account (uploaded.to): if credentials are entered and clicked on add the page jumps to config/general and no account is added.

(was working until yesterday but i got hit by the flawed update ("validuntil"), deleted my premium account and tried to reenter it)

additionally i get a lot of these in the debug log:

133	29.07.2015 10:21:07	ERROR	HOOK AntiStandby: Error executing addon: 'AntiStandby' object has no attribute 'mtime'

traceback:
29.07.2015 10:31:06 ERROR     HOOK AntiStandby: Error executing addon: 'AntiStandby' object has no attribute 'mtime'
Jul 29 10:31:06 server pyLoadCore.py: Traceback (most recent call last):
Jul 29 10:31:06 server pyLoadCore.py: File "/home/nutzer/pyload-stable/module/plugins/internal/Addon.py", line 97, in _periodical
Jul 29 10:31:06 server pyLoadCore.py: self.periodical()
Jul 29 10:31:06 server pyLoadCore.py: File "/home/nutzer/pyload-stable/module/plugins/hooks/AntiStandby.py", line 154, in periodical
Jul 29 10:31:06 server pyLoadCore.py: if (self.max_mtime(path) - self.mtime) < self.interval:
Jul 29 10:31:06 server pyLoadCore.py: AttributeError: 'AntiStandby' object has no attribute 'mtime'

**Comment by wweich** [comment]
Same here :(
The DEBUG Log does not show anything when adding an account.
But when trying to add a second ShareonlineBiz account will replace the password of the existing one with ********** inside the account.conf.

@raidyne If you don't need the AntiStandby Plugin (becouse you configured your OS accordingly) you can disable it. As I see it, that plugin will touch files on the HDD to avoid the HDD to spin down (or so) and send commands to the OS to keep it from going into stand-by while a download is running.

**Comment by vuolter** [comment]
AntiStandby should working fine right now. :S

**Comment by raidyne** [comment]
@wweich thanks, already figured that out ;-) premium account problem still persists..

**Comment by FuX-STV** [comment]
Same Problem..

**Comment by no-Legend** [comment]
same here!

**Comment by nordic-style** [comment]
just tried latest pyload with uploaded.to
was not able to add an account :/

**Comment by ccric** [comment]
I have the same problems since everything went down with this buggy "validuntil"-Update.
Now, when I try to download something it falls back to free download, even when the account manager displays the premium account without flaws.
```
225	30.07.2015 13:08:33	INFO	ACCOUNT UploadedTo: Parsing account info for user `xxxxxxx`...
226	30.07.2015 13:08:33	INFO	Download starts: http://uploaded.net/file/xxxxxxxx
227	30.07.2015 13:08:33	INFO	HOSTER UploadedTo[1256]: Updating file info...
228	30.07.2015 13:08:33	INFO	HOSTER UploadedTo[1256]: File name: xxxxxxxxx.part1.rar
229	30.07.2015 13:08:33	INFO	HOSTER UploadedTo[1256]: File size: 157286400 bytes
230	30.07.2015 13:08:33	INFO	HOSTER UploadedTo[1256]: File status: online
231	30.07.2015 13:08:33	INFO	HOSTER UploadedTo[1256]: Looking for direct download link...
232	30.07.2015 13:08:33	INFO	HOSTER UploadedTo[1256]: Direct download link not found
233	30.07.2015 13:08:33	INFO	HOSTER UploadedTo[1256]: Processing as free download... 
```

When I delete the premium account and try to reenter it through the webinterface, nothing is added to the accounts.conf file and the log says

```
 142	30.07.2015 12:42:42	ERROR	ACCOUNT UploadedTo: User `xxxxxxx` not found while retrieving account info
143	30.07.2015 12:42:44	ERROR	ACCOUNT UploadedTo: User `xxxxxxx` not found while retrieving account info
144	30.07.2015 12:42:46	ERROR	ACCOUNT UploadedTo: User `xxxxxxx` not found while retrieving account info
145	30.07.2015 12:42:48	ERROR	ACCOUNT UploadedTo: User `xxxxxxx` not found while retrieving account info 
```

After manually adding the account to accounts.conf, everything is back to the "processing as free download" behaviour.

So maybe these are two distinct bugs. One with adding the account and one with starting downloads. But probably they have a common origin.

**Comment by venious** [comment]
can not add uploaded account

**Comment by evilmon** [comment]
same here with ShareonlineBiz

**Comment by beatgen** [comment]
hello,

I had the same problem and just resolved it on my machine (here win7 though but should not mind).

First updatemanger didn't work anymore, I fixed it by #1553 (https://github.com/pyload/pyload/issues/1553)

After all updates finished and pyload closed put/replace the updated Account.py from #1593 (https://github.com/pyload/pyload/pull/1593)  in the userplugins\internal and module\plugins\internal directories. Start, activate the premium hoster plugin (if not already) and close pyload again.

The premium account can now be added manually in the accounts.conf. Add premium login and password like this (exemplary for ul.to): 

UploadedTo: login:password

Save file and start pyload. Now the premium account is listed under accounts settings and should work. You see the account gets parsed in the log.

I could not add the account over gui.

**Comment by vuolter** [comment]
Checking...

**Comment by mattionline** [comment]
Same here:

ERROR	HOOK AntiStandby: Error executing addon: 'AntiStandby' object has no attribute 'pyfile'

**Comment by godfuture** [comment]
Same here. I cannot add accounts...tried SO.

**Comment by vuolter** [comment]
Now all should work flawlessly. ;)
