### ISSUE TITLE
Errors in AntiStandby: ValueError: max() arg is an empty sequence + HOOK AntiStandby: Unable to change power state | [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wweich** [pyload/pyload#1600]
Every time the plugin is loaded or unloaded, the following Log-Line is printed:
```
29.07.2015 13:46:58 WARNING   HOOK AntiStandby: Unable to change power state | [Errno 2] No such file or directory
```

Every time the plugin tries to touch the HDD, the following error occurs:
```
Traceback (most recent call last):
  File "/opt/pyload/userplugins/internal/Addon.py", line 97, in _periodical
    self.periodical()
  File "/opt/pyload/userplugins/hooks/AntiStandby.py", line 154, in periodical
    if (self.max_mtime(path) - self.mtime) < self.interval:
  File "/opt/pyload/userplugins/hooks/AntiStandby.py", line 144, in max_mtime
    for root, dirs, files in os.walk(path, topdown=False)
ValueError: max() arg is an empty sequence
```

I am running on Ubuntu Server 12.04.
I don't need the plugin as I don't have standby enabled for OS or HDD, so I will keep it disabled.
Just wanted to let you know.

**Comment by Gummibaer** [comment]
ERROR	HOOK AntiStandby: Error executing addon: 'AntiStandby' object has no attribute 'pyfile'

**Comment by vuolter** [comment]
When you write pyfile instead pycore, then you're tired. u.u
