### ISSUE TITLE
captcha9kw.py not working

### ISSUE THREAD

**Issue by acidburn78** [pyload/pyload#1601]
The Hook is called but the captcha isn't send to 9kw.eu to solve it

29.07.2015 13:54:19	INFO	Download restarted: tvp-newgirl-s04e17-720p.part3.rar | No captcha result obtained in appropiate time
199	29.07.2015 13:54:19	INFO	Download starts: tvp-newgirl-s04e17-720p.part3.rar
200	29.07.2015 13:54:19	INFO	HOSTER ShareonlineBiz[5]: Updating file info...
201	29.07.2015 13:54:19	INFO	HOSTER ShareonlineBiz[5]: File name: tvp-newgirl-s04e17-720p.part3.rar
202	29.07.2015 13:54:19	INFO	HOSTER ShareonlineBiz[5]: File size: 105906176 bytes
203	29.07.2015 13:54:19	INFO	HOSTER ShareonlineBiz[5]: File status: online
204	29.07.2015 13:54:19	INFO	HOSTER ShareonlineBiz[5]: Processing as free download...
205	29.07.2015 13:54:19	INFO	HOSTER ShareonlineBiz[5]: WAIT 3 seconds
206	29.07.2015 13:54:24	INFO	HOOK Captcha9Kw: 43959 credits left

Thats all what i get from Captcha9Kw

**Comment by FuX-STV** [comment]
https://www.9kw.eu/grafik/plugins/Captcha9kw.zip

Captcha_9kw works fine

**Comment by vuolter** [comment]
@FuX-STV If that version works for you, then your pyLoad is broken or out of date. XD

**Comment by snickers2k** [comment]
broken here too... running latest git version

**Comment by no-Legend** [comment]
the plugin from the 9kw page is working
https://www.9kw.eu/hilfe.html#pyload-tab
