### ISSUE TITLE
ExtractArchive: problems deleting multipart archives

### ISSUE THREAD

**Issue by TodsDeath** [pyload/pyload#1603]
```
62	29.07.2015 15:13:58	INFO	Package finished: test_package
63	29.07.2015 15:13:58	DEBUG	HOOK ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
64	29.07.2015 15:13:58	INFO	HOOK ExtractArchive: Check package: test_package
65	29.07.2015 15:13:58	DEBUG	All downloads processed
66	29.07.2015 15:13:58	DEBUG	HOOK ExtractArchive: Targets for UnRar: [(u'/volume1/downloads/multipart-archive.part1.rar', 2396, u'/volume1/downloads/')]
67	29.07.2015 15:13:58	INFO	HOOK ExtractArchive: multipart-archive.part1.rar | Extract to: /volume1/downloads/
68	29.07.2015 15:13:58	DEBUG	All downloads finished
69	29.07.2015 15:13:58	DEBUG	HOOK ExtractArchive: Password: None provided
70	29.07.2015 15:13:58	DEBUG	EXTRACTOR ExtractArchive: UnRar: rar l -o- -or -x'' -y -p- -v /volume1/downloads/multipart-archive.part1.rar
71	29.07.2015 15:13:58	INFO	HOOK ExtractArchive: multipart-archive.part1.rar | Password protected
72	29.07.2015 15:13:58	DEBUG	EXTRACTOR ExtractArchive: UnRar: rar l -o- -or -x'' -y -ppassword1 -v /volume1/downloads/multipart-archive.part1.rar
73	29.07.2015 15:13:58	DEBUG	EXTRACTOR ExtractArchive: UnRar: rar l -o- -or -x'' -y -ppassword2 -v /volume1/downloads/multipart-archive.part1.rar
74	29.07.2015 15:13:58	DEBUG	EXTRACTOR ExtractArchive: UnRar: rar l -o- -or -x'' -y -ppassword3 -v /volume1/downloads/multipart-archive.part1.rar
75	29.07.2015 15:13:58	DEBUG	HOOK ExtractArchive: Extracting using password: password1
76	29.07.2015 15:13:58	DEBUG	EXTRACTOR ExtractArchive: UnRar: rar x -o- -or -x'' -y -ppassword1 /volume1/downloads/multipart-archive.part1.rar /volume1/downloads/
77	29.07.2015 15:14:36	DEBUG	Cleared Result cache
78	29.07.2015 15:15:17	DEBUG	EXTRACTOR ExtractArchive: UnRar: rar vb -o- -or -x'' -y -ppassword1 -v /volume1/downloads/multipart-archive.part1.rar
79	29.07.2015 15:15:18	DEBUG	HOOK ExtractArchive: Would delete: /volume1/downloads/multipart-archive.part1.rar
80	29.07.2015 15:15:18	INFO	HOOK ExtractArchive: Deleting 1 files
81	29.07.2015 15:15:18	INFO	HOOK ExtractArchive: multipart-archive.part1.rar | Extracting finished
82	29.07.2015 15:15:18	DEBUG	All downloads finished
83	29.07.2015 15:15:18	DEBUG	HOOK ExtractArchive: Extracted files: [u'/volume1/downloads/*****/*****.***', u'/volume1/downloads/*****/*****.***', u'/volume1/downloads/*****']
84	29.07.2015 15:15:18	DEBUG	HOOK ExtractArchive: Targets for SevenZip: [(u'/volume1/downloads/multipart-archive.part3.rar', 2398, u'/volume1/downloads/')]
85	29.07.2015 15:15:18	INFO	HOOK ExtractArchive: multipart-archive.part3.rar | Extract to: /volume1/downloads/
86	29.07.2015 15:15:18	DEBUG	HOOK ExtractArchive: Password: None provided
87	29.07.2015 15:15:18	DEBUG	EXTRACTOR ExtractArchive: SevenZip: 7z l -p- -slt /volume1/downloads/multipart-archive.part3.rar
88	29.07.2015 15:15:19	DEBUG	HOOK ExtractArchive: multipart-archive.part3.rar | Header protected
89	29.07.2015 15:15:19	INFO	HOOK ExtractArchive: multipart-archive.part3.rar | CRC Error
90	29.07.2015 15:15:19	ERROR	HOOK ExtractArchive: multipart-archive.part3.rar | CRC mismatch | Archive damaged
91	29.07.2015 15:15:19	DEBUG	All downloads finished
92	29.07.2015 15:15:19	ERROR	HOOK ExtractArchive: multipart-archive.part3.rar | Extract failed
```
This was an encrypted multipart archive with 4 parts (*.part1.rar, ..., *.part4.rar). As you can see, the package finishes and ExtractArchive gets started. After guessing the right password and successful extraction, only part1 gets deleted (lines 79/80).

7zip is then trying to extract the remaining parts, which understandably fails.

**Comment by Gutz-Pilz** [comment]
Also deep Extraction doesnt work.

**Comment by Gutz-Pilz** [comment]
can someone please fix this!
this sucks really bad!

**Comment by wastez** [comment]
i also have this problem.....

**Comment by vuolter** [comment]
No time to fix it now, sorry.

**Comment by wastez** [comment]
The files are not going to be deleted and it also trys to extract the last part with sevenzip after it´s already extracted.
<pre><code>
177	02.08.2015 22:19:20	DEBUG	HOOK ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
178	02.08.2015 22:19:20	INFO	HOOK ExtractArchive: Check package: tvs-defiance-dl-hdtv-x264-306
179	02.08.2015 22:19:20	DEBUG	HOOK ExtractArchive: Targets for UnRar: [(u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar', 1686, u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/')]
180	02.08.2015 22:19:20	INFO	HOOK ExtractArchive: tvs-defiance-dl-hdtv-x264-306.part1.rar | Extract to: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/
181	02.08.2015 22:19:20	DEBUG	HOOK ExtractArchive: Password: None provided
182	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -p- -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
183	02.08.2015 22:19:20	INFO	HOOK ExtractArchive: tvs-defiance-dl-hdtv-x264-306.part1.rar | Password protected
184	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pserienjunkies.org -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
185	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pF430 -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
186	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pboerse -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
187	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pddl-warez -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
188	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pbrubbel -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
189	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pdokujunkies.org -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
190	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pHQ-Community.com -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
191	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pBy.B-52.4all -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
192	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pplusquamperfekt! -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
193	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pminion -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
194	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pddl-music -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
195	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pddl-warez.in -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
196	02.08.2015 22:19:20	DEBUG	HOOK ExtractArchive: Extracting using password: serienjunkies.org
197	02.08.2015 22:19:20	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar x -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pserienjunkies.org /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/
198	02.08.2015 22:19:20	DEBUG	PyControlPush: Response:
199	02.08.2015 22:19:20	DEBUG	PyControlPush: Pushing notification to device ad571b1b65c4bdde957793fc77f8d104e5465ff637ecb97f0b712c70fdfcf53a
200	02.08.2015 22:19:21	DEBUG	PyControlPush: Response:
201	02.08.2015 22:19:21	DEBUG	All downloads processed
202	02.08.2015 22:19:27	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar vb -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pserienjunkies.org -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
203	02.08.2015 22:19:27	DEBUG	HOOK ExtractArchive: Would delete: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part1.rar
204	02.08.2015 22:19:27	INFO	HOOK ExtractArchive: Deleting 1 files
205	02.08.2015 22:19:27	INFO	HOOK ExtractArchive: tvs-defiance-dl-hdtv-x264-306.part1.rar | Extracting finished
206	02.08.2015 22:19:27	DEBUG	PyControlPush: Pushing notification to device 7066f49aa5ab8dd6e8f4a8d94c467f26792967e418ac28c049a27f03654214d5
207	02.08.2015 22:19:28	DEBUG	PyControlPush: Response:
208	02.08.2015 22:19:28	DEBUG	PyControlPush: Pushing notification to device ad571b1b65c4bdde957793fc77f8d104e5465ff637ecb97f0b712c70fdfcf53a
209	02.08.2015 22:19:28	DEBUG	PyControlPush: Response:
210	02.08.2015 22:19:28	DEBUG	All downloads finished
211	02.08.2015 22:19:28	DEBUG	HOOK ExtractArchive: Extracted files: [u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/Defiance.S03E06.Wohin.die.Aepfel.fallen.German.DL.HDTV.x264-TVS/tvs-defiance-dl-hdtv-x264-306.mkv', u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/Defiance.S03E06.Wohin.die.Aepfel.fallen.German.DL.HDTV.x264-TVS/tvs-defiance-dl-hdtv-x264-306.nfo', u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/Defiance.S03E06.Wohin.die.Aepfel.fallen.German.DL.HDTV.x264-TVS']
212	02.08.2015 22:19:28	DEBUG	HOOK ExtractArchive: Targets for SevenZip: [(u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar', 1689, u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/')]
213	02.08.2015 22:19:28	INFO	HOOK ExtractArchive: tvs-defiance-dl-hdtv-x264-306.part4.rar | Extract to: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/
214	02.08.2015 22:19:28	DEBUG	HOOK ExtractArchive: Password: None provided
215	02.08.2015 22:19:28	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
216	02.08.2015 22:19:28	INFO	HOOK ExtractArchive: tvs-defiance-dl-hdtv-x264-306.part4.rar | Password protected
217	02.08.2015 22:19:28	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
218	02.08.2015 22:19:28	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
219	02.08.2015 22:19:28	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
220	02.08.2015 22:19:28	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
221	02.08.2015 22:19:28	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
222	02.08.2015 22:19:29	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
223	02.08.2015 22:19:29	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
224	02.08.2015 22:19:29	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
225	02.08.2015 22:19:29	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
226	02.08.2015 22:19:29	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
227	02.08.2015 22:19:29	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
228	02.08.2015 22:19:29	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -p- -slt /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
229	02.08.2015 22:19:29	DEBUG	HOOK ExtractArchive: Extracting using password: serienjunkies.org
230	02.08.2015 22:19:29	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z x -y -pserienjunkies.org -o/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/ /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
231	02.08.2015 22:19:30	DEBUG	EXTRACTOR ExtractArchive: SevenZip | 7z l -y -pserienjunkies.org /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
232	02.08.2015 22:19:30	DEBUG	HOOK ExtractArchive: Would delete: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/tvs-defiance-dl-hdtv-x264-306.part4.rar
233	02.08.2015 22:19:30	INFO	HOOK ExtractArchive: Deleting 1 files
234	02.08.2015 22:19:30	INFO	HOOK ExtractArchive: tvs-defiance-dl-hdtv-x264-306.part4.rar | Extracting finished
235	02.08.2015 22:19:30	DEBUG	PyControlPush: Pushing notification to device 7066f49aa5ab8dd6e8f4a8d94c467f26792967e418ac28c049a27f03654214d5
236	02.08.2015 22:19:31	DEBUG	PyControlPush: Response:
237	02.08.2015 22:19:31	DEBUG	PyControlPush: Pushing notification to device ad571b1b65c4bdde957793fc77f8d104e5465ff637ecb97f0b712c70fdfcf53a
238	02.08.2015 22:19:32	DEBUG	PyControlPush: Response:
239	02.08.2015 22:19:32	DEBUG	All downloads finished
240	02.08.2015 22:19:32	DEBUG	HOOK ExtractArchive: Extracted files: [u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/Defiance.S03E06.Wohin.die.Aepfel.fallen.German.DL.HDTV.x264-TVS/tvs-defiance-dl-hdtv-x264-306.mkv', u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/Defiance.S03E06.Wohin.die.Aepfel.fallen.German.DL.HDTV.x264-TVS/tvs-defiance-dl-hdtv-x264-306.nfo', u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/Defiance.S03E06.Wohin.die.Aepfel.fallen.German.DL.HDTV.x264-TVS']
</code></pre>

**Comment by wastez** [comment]
Can somebody have a look on it?
Because extraction is one of the main plugins out there and it´s indispensable.

**Comment by wastez** [comment]
Sorry referencing was not intented.
Didn´t know that it reference it just with posting a link.

**Comment by GammaC0de** [comment]
@wastez How would you exactly supposed to handle multipart archives?
For example, if you download part1.rar from one host and part2.rar from another, how would you handle this case?

**Comment by Gutz-Pilz** [comment]
but i have the same problem downloading from one hoster.
but anyway - is extractarchive recognizing and differentiating between "downloaded from multiple hoster" or "downloaded from one hoster" ?

**Comment by wastez** [comment]
I also just downloaded from one Hoster. (ShareOnline)

**Comment by TodsDeath** [comment]
@GammaC0de Its not a problem that files would come from different hosts. All files, for example part1 to part4, get downloaded from the same host.

Problem (for me) occurs after the successful extraction with unrar. Only one part (which one is "random", probably depending on the link order in the package) is deleted. In the past all parts (in this case 1 to 4) got deleted.

Additionally 7zip kicks in and tries to extract the not deleted parts of the multipart archive, which obviously fails, because one part is missing.

**Comment by GammaC0de** [comment]
@wastez are you using `Run after all downloads was processed` config?
@TodsDeath so the only problem is that `ExtractArchive` does no delete all parts of the archive but it extract it ok?

**Comment by TodsDeath** [comment]
@GammaC0de I would say so. The extracted files were fine, but due to the incomplete deletion the package fails. If all files are deleted, the package should finish without errors.

But I am not 100% sure about this last part. Maybe there are additional bugs.

**Comment by wastez** [comment]
No it Extracts when the Package finished download. 
Again i Download from just one Hoster. 
This is not the only Problem. 
After extracting with unrar it trys to extract with 7zip. But because one part is deleted (from unrar) it will overwrite the extracted file with a defect one.

**Comment by TodsDeath** [comment]
@GammaC0de 
https://github.com/pyload/pyload/blob/950250af5af3a1cd3deb351d2678bab49418a3a8/module/plugins/internal/UnRar.py#L180
I think "is" has to be "=="

**Comment by GammaC0de** [comment]
@TodsDeath i think you are right, please change this and post the results

**Comment by TodsDeath** [comment]
seems to work, no more errors, made pr #1689

**Comment by GammaC0de** [comment]
:+1:

**Comment by GammaC0de** [comment]
so can anyone confirm we can close this issue?

**Comment by wastez** [comment]
@GammaC0de 
Could you please also have a look on the premium accounts (share-online)?
Seems vuolter has too much to do in the moment.

**Comment by Gutz-Pilz** [comment]
^^that would be great.
uploaded seems to have issues 2!

**Comment by GammaC0de** [comment]
which issue# are you referring to?

**Comment by wastez** [comment]
https://github.com/pyload/pyload/issues/1692

this one.
