### ISSUE TITLE
Decrypting failed: | Decrypt error: No link grabbed | Plugin may be out of date

### ISSUE THREAD

**Issue by FuX-STV** [pyload/pyload#1605]
cant decrypt :(

19	29.07.2015 18:54:59	INFO	shutting down...
20	29.07.2015 18:55:00	INFO	starte pyLoad 0.4.9
21	29.07.2015 18:55:00	INFO	Benutze Home-Verzeichnis: /volume1/@appstore/pyload/etc
22	29.07.2015 18:55:00	INFO	Aktivierte Plugins: BypassCaptcha, Captcha_9kw, Checksum, ClickAndLoad, DeleteFinished, ExternalScripts, ExtractArchive, HDAreaOrg, LinkdecrypterComHook, SJ, UnSkipOnFail, UpdateManager, UserAgentSwitcher
23	29.07.2015 18:55:00	INFO	Deaktivierte Plugins: AlldebridComHook, AndroidPhoneNotify, AntiStandby, AntiVirus, Captcha9Kw, CaptchaBrotherhood, DeathByCaptcha, DebridItaliaComHook, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, WindowsPhoneNotify, XFileSharingPro, XMPPInterface, ZeveraComHook
24	29.07.2015 18:55:00	INFO	Downloadzeit: True
25	29.07.2015 18:55:01	INFO	Starting threaded webserver: :::8190
26	29.07.2015 18:55:01	INFO	Free space: 1.09 TiB
27	29.07.2015 18:55:02	INFO	Activating Accounts...
28	29.07.2015 18:55:02	INFO	Activating Plugins...
29	29.07.2015 18:55:03	INFO	pyLoad is up and running
30	29.07.2015 18:55:04	INFO	HOOK UpdateManager: No new pyLoad version available
31	29.07.2015 18:55:04	INFO	HOOK UpdateManager: No plugin updates available
32	29.07.2015 18:55:05	INFO	HOOK LinkdecrypterCom: Reloading supported crypter list
33	29.07.2015 18:55:06	INFO	HOOK LinkdecrypterCom: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
34	29.07.2015 18:55:13	INFO	HOOK ClickAndLoad: Proxy listening on 127.0.0.1:9666
35	29.07.2015 18:55:36	INFO	HOOK LinkdecrypterCom: Reloading supported crypter list
36	29.07.2015 18:55:37	INFO	HOOK LinkdecrypterCom: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
37	29.07.2015 18:55:44	INFO	Decrypting starts: http://filecrypt.cc/Container/FA6B409569.html
38	29.07.2015 18:55:44	WARNING	CAPTCHA FilecryptCc: ReCaptcha[11]: Key pattern not found
39	29.07.2015 18:55:44	INFO	CRYPTER FilecryptCc[11]: No captcha found
40	29.07.2015 18:55:44	ERROR	Decrypting failed: http://filecrypt.cc/Container/FA6B409569.html | Decrypt error: No link grabbed | Plugin may be out of date
41	29.07.2015 18:56:04	INFO	Decrypting starts: http://filecrypt.cc/Container/FA6B409569.html
42	29.07.2015 18:56:04	WARNING	CAPTCHA FilecryptCc: ReCaptcha[11]: Key pattern not found
43	29.07.2015 18:56:04	INFO	CRYPTER FilecryptCc[11]: No captcha found
44	29.07.2015 18:56:04	ERROR	Decrypting failed: http://filecrypt.cc/Container/FA6B409569.html | Decrypt error: No link grabbed | Plugin may be out of date
45	29.07.2015 18:56:12	INFO	Decrypting starts: http://filecrypt.cc/Container/FA6B409569.html
46	29.07.2015 18:56:12	ERROR	Decrypting failed: http://filecrypt.cc/Container/FA6B409569.html | (23, 'Failed writing body (0 != 2067)')
47	29.07.2015 18:56:14	INFO	Decrypting starts: http://filecrypt.cc/Container/FA6B409569.html
48	29.07.2015 18:56:14	WARNING	CAPTCHA FilecryptCc: ReCaptcha[11]: Key pattern not found
49	29.07.2015 18:56:14	INFO	CRYPTER FilecryptCc[11]: No captcha found
50	29.07.2015 18:56:14	ERROR	Decrypting failed: http://filecrypt.cc/Container/FA6B409569.html | Decrypt error: No link grabbed | Plugin may be out of date
51	29.07.2015 18:56:20	INFO	Decrypting starts: http://filecrypt.cc/Container/FA6B409569.html
52	29.07.2015 18:56:20	ERROR	Decrypting failed: http://filecrypt.cc/Container/FA6B409569.html | 'NoneType' object has no attribute '__getitem__'
53	29.07.2015 18:56:22	INFO	Decrypting starts: http://filecrypt.cc/Container/FA6B409569.html
54	29.07.2015 18:56:22	ERROR	Decrypting failed: http://filecrypt.cc/Container/FA6B409569.html | 'NoneType' object has no attribute '__getitem__'
55	29.07.2015 18:56:24	INFO	Decrypting starts: http://filecrypt.cc/Container/FA6B409569.html
56	29.07.2015 18:56:25	INFO	Captcha_9kw: 75914 credits left
57	29.07.2015 18:56:25	INFO	Captcha_9kw: NewCaptchaID from upload: 51131935 : tmp/captcha_image_FilecryptCc_98532.gif
58	29.07.2015 18:56:35	INFO	Captcha_9kw: result 51131935 : grfz2m
59	29.07.2015 18:56:36	INFO	CAPTCHA FilecryptCc: Captcha[11]: Captcha result: grfz2m
60	29.07.2015 18:56:36	ERROR	CAPTCHA FilecryptCc: Captcha[11]: Invalid captcha
61	29.07.2015 18:56:36	INFO	Captcha_9kw: Request refund: OK
62	29.07.2015 18:56:36	INFO	CRYPTER FilecryptCc[11]: WAIT 1 seconds
63	29.07.2015 18:56:36	INFO	CRYPTER FilecryptCc[11]: RECONNECT disabled
64	29.07.2015 18:56:38	INFO	Retrying http://filecrypt.cc/Container/FA6B409569.html
65	29.07.2015 18:56:38	INFO	Decrypting starts: http://filecrypt.cc/Container/FA6B409569.html
66	29.07.2015 18:56:39	WARNING	CAPTCHA FilecryptCc: ReCaptcha[11]: Key pattern not found
67	29.07.2015 18:56:39	INFO	CRYPTER FilecryptCc[11]: No captcha found
68	29.07.2015 18:56:39	ERROR	Decrypting failed: http://filecrypt.cc/Container/FA6B409569.html | Decrypt error: No link grabbed | Plugin may be out of date
69	29.07.2015 19:10:01	INFO	Decrypting starts: http://filecrypt.cc/Container/80B15A4DB6.html
70	29.07.2015 19:10:01	WARNING	CAPTCHA FilecryptCc: ReCaptcha[12]: Key pattern not found
71	29.07.2015 19:10:01	INFO	CRYPTER FilecryptCc[12]: No captcha found
72	29.07.2015 19:10:01	INFO	CRYPTER FilecryptCc[12]: Found 2 mirrors
73	29.07.2015 19:10:01	ERROR	Decrypting failed: http://filecrypt.cc/Container/80B15A4DB6.html | 'ascii' codec can't encode character u'\xfc' in position 1393: ordinal not in range(128)

'NoneType' object has no attribute '__getitem__'
 'ascii' codec can't encode character u'\xfc' in position 1393: ordinal not in range(128)

**Comment by j4m** [comment]
same here

**Comment by j4m** [comment]
@zapp-brannigan could you investigate?

**Comment by zapp-brannigan** [comment]
I'm already working on it ;)

**Comment by zapp-brannigan** [comment]
There are some problems regarding captcha:
1) ReCaptchaV2 will not work via pyload, the plugin should retry or fail (easy to implement)
2) Sometimes, Solvemedia captchas appear (ease to implement)
I've edited the plugin and fixed 1) and 2). 

So we have 3 captcha-types which can be handled (Text,Circle,Solvemedia).
Solvemedia is working great. Unfortunately, text and circle captcha don't work anymore. I have no idea to fix it, you simply can not pass the first page, an other captcha is shown instead.

And now the strange thing: I'm running a pretty old and non-updated version of pyload 0.49. Text and circle captcha are working in this version :((

I'm not able to determine the difference between the old and new captcha handling. I guess it is caused by some changes in pyload core.

For now FilecryptCC.py is completely broken.

**Comment by sraedler** [comment]
Filecrypt is working...

Please close
