### ISSUE TITLE
CaptchaBrotherhood did not work anymore

### ISSUE THREAD

**Issue by kistenstampler** [pyload/pyload#1606]
The CaptchaBrotherhood-Plugin stopped working after the latest update. 

Here is the error from the console:
29.07.2015 20:18:48 INFO      HOOK CaptchaBrotherhood: 10715 credits left
Exception in thread Thread-25:
Traceback (most recent call last):
  File "threading.pyc", line 530, in __bootstrap_inner
  File "C:\Programme\pyLoad\dist\.\module\PluginThread.py", line 466, in run
  File "C:\Programme\pyLoad\data\userplugins\hooks\CaptchaBrotherhood.py", line 164, in _process_captcha
AttributeError: 'CaptchaBrotherhoodException' object has no attribute 'getCode'

**Comment by kistenstampler** [comment]
Rename "getCode" to "get_code" helps, but another error is shown after that (and every download is skipped):
29.07.2015 20:24:44 INFO      HOSTER ShareonlineBiz[13]: WAIT 3 seconds
29.07.2015 20:24:49 INFO      HOOK CaptchaBrotherhood: 10715 credits left
29.07.2015 20:24:50 WARNING   Download failed: file-which-i-want-to-download.part1.rar | global name 'task' is not defined

**Comment by vuolter** [comment]
Could you test it again, please.

**Comment by kistenstampler** [comment]
Tested it again, but it still does not work. The "new" error is:

03.08.2015 19:20:00 INFO      HOSTER UploadedTo[14]: Processing as free download...
03.08.2015 19:20:01 WARNING   Download failed: myfile.part2.rar | 'ReCaptcha' object has no attribute 'COOKIES'
03.08.2015 19:20:01 INFO      HOOK UnSkipOnFail: Looking for skipped duplicatesof: myfile.part2.rar (pid:7)

OT: pyLoad gets updates almost every day. But since several days, each update makes more errors. I temporarily switch back to JDownloader (which has only one nasty error: Usage of RAM and CPU are to high).

**Comment by kistenstampler** [comment]
Update: Since the UpdateManager is broken, I can't tell you, if the plugin works again.

My last status regarding updates is:
08.08.2015 17:18:45 WARNING   HOOK UpdateManager: Unable to retrieve server to get updates

Even a fresh install of pyLoad did not work:
08.08.2015 17:24:54 WARNING   Not able to connect server for updates
08.08.2015 17:24:54 INFO      No Updates for pyLoad
08.08.2015 17:24:54 WARNING   Not able to connect server for updates
08.08.2015 17:24:54 INFO      No plugin updates available

pyLoad is running under Windows 7, with the installer from http://get.pyload.org/get/win

**Comment by kistenstampler** [comment]
After deleting the content of the folder "userplugins" and restoring the folders "internal" and "hooks" from github, pyLoad can download updates again.
The CaptchaBrotherhood plugin works again. I was able to download one file. But pyLoad is still in a very unstable state. Soon after the first download, many other errors appeared in the console/log.
I had to use JDownloader again. 
The good news are: The plugin is fixed again and you can close the issue.
The bad are: I will not donate money to pyLoad this year, because pyLoad does not work since several weeks.
