### ISSUE TITLE
4.10 release plan

### ISSUE THREAD

**Issue by bkchr** [pyload/pyload#1607]
Hi, do you have any sort of a release plan? 
I would suggest that you maybe merge the last pull requests for 4.10 and then you could maybe start a beta?

**Comment by vuolter** [comment]
When the plugin module (recently merged in the stable branch) and the config module will be ready and tested, then I plan to release the 0.4.10 .

**Comment by bkchr** [comment]
Is there something where I could help you?

**Comment by sraedler** [comment]
This question and #1791 are opened issues, which are not important to read, maybe closeable?
