### ISSUE TITLE
QNAP TS-119P+ ARM Pyload Share-Online - list index out of range -

### ISSUE THREAD

**Issue by Moerdoc** [pyload/pyload#1617]
Hello,

i´ve got the problem, that i can´t downloading with my Share-Online (Premium Account) on Pyload. 
The Error Message is "list index out of range".

Reinstall doesn´t help.

Any ideas?

THX MdC

**Comment by vuolter** [comment]
Debug log please.

**Comment by Moerdoc** [comment]
pyLoad 0.4.9 Debug Report of ShareonlineBiz 0.21 

TRACEBACK:
 Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/share/HDA_DATA/.qpkg/pyload/module/plugins/Plugin.py", line 237, in preprocessing
    return self.process(self.pyfile)
  File "/share/HDA_DATA/.qpkg/pyload/module/plugins/hoster/ShareonlineBiz.py", line 59, in process
    self.downloadAPIData()
  File "/share/HDA_DATA/.qpkg/pyload/module/plugins/hoster/ShareonlineBiz.py", line 76, in downloadAPIData
    "status": fields[1]}
IndexError: list index out of range
 

FRAMESTACK:

Frame preprocessing in /share/HDA_DATA/.qpkg/pyload/module/plugins/Plugin.py at line 237
	                self = <module.plugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0x223f7b0>
	              thread = <DownloadThread(Thread-2, started daemon)>

Frame process in /share/HDA_DATA/.qpkg/pyload/module/plugins/hoster/ShareonlineBiz.py at line 59
	              pyfile = PyFile 2: http://www.share-online.biz/download.php?id=PTCOX1GL6XAH@ShareonlineBiz
	                self = <module.plugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0x223f7b0>

Frame downloadAPIData in /share/HDA_DATA/.qpkg/pyload/module/plugins/hoster/ShareonlineBiz.py at line 76
	              fields = ['** NO UPLOAD IDS FOUND **\n']
	                self = <module.plugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0x223f7b0>
	      api_param_file = {'links': u'PTCOX1GL6XAH'}
	        api_url_base = 'http://www.share-online.biz/linkcheck/linkcheck.php?md5=1'
	                 src = '** NO UPLOAD IDS FOUND **\n'


PLUGIN OBJECT DUMP: 

	             account = None
	               cTask = None
	          chunkLimit = 1
	              config = <module.ConfigParser.ConfigParser instance at 0x1e3b968>
	                core = <__main__.Core object at 0x1dea3f0>
	             file_id = u'PTCOX1GL6XAH'
	                html = None
	                  js = <module.common.JsEngine.JsEngine instance at 0x200e558>
	           lastCheck = None
	        lastDownload = ''
	             limitDL = 0
	                 log = <logging.Logger instance at 0x1de2828>
	             multiDL = False
	                 ocr = None
	             premium = False
	              pyfile = PyFile 2: http://www.share-online.biz/download.php?id=PTCOX1GL6XAH@ShareonlineBiz
	                 req = <module.network.Browser.Browser object at 0x2259dc0>
	      resumeDownload = False
	             retries = 0
	              thread = <DownloadThread(Thread-2, started daemon)>
	                user = None
	           waitUntil = 0
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 0
	               abort = False
	              active = False
	               error = 'list index out of range'
	                  id = 2
	                lock = <_RLock(None, 0)>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x1e47f08>
	         maxprogress = 100
	                name = u'http://www.share-online.biz/download.php?id=PTCOX1GL6XAH'
	               order = 0
	           packageid = 2
	              plugin = <module.plugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0x223f7b0>
	         pluginclass = <class 'module.plugins.hoster.ShareonlineBiz.ShareonlineBiz'>
	        pluginmodule = <module 'module.plugins.hoster.ShareonlineBiz' from '/share/HDA_DATA/.qpkg/pyload/module/plugins/hoster/ShareonlineBiz.pyc'>
	          pluginname = u'ShareonlineBiz'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'http://www.share-online.biz/dl/PTCOX1GL6XAH'
	           waitUntil = 0


THX for helping

**Comment by vuolter** [comment]
Please retry now.

**Comment by Moerdoc** [comment]
Nice Job :+1: ... ShareOnline.biz working, after restart doesn´t work.
I´ve got a new error.

"NoneType' object has no attribute 'find"

THX voulter

LATEST DEBUG LOG

pyLoad 0.4.9 Debug Report of ShareonlineBiz 0.55 

TRACEBACK:
 Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/share/HDA_DATA/.qpkg/pyload/module/plugins/internal/Hoster.py", line 184, in preprocessing
    return self.process(self.pyfile)
  File "/share/HDA_DATA/.qpkg/pyload/module/plugins/internal/SimpleHoster.py", line 296, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/share/HDA_DATA/.qpkg/pyload/module/plugins/internal/Hoster.py", line 411, in download
    finalname = urlparse.urlparse(newname).path.split('/')[-1].split(' filename*=')[0]
  File "/share/HDA_DATA/.qpkg/pyload/opt/lib/python2.5/urlparse.py", line 154, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/share/HDA_DATA/.qpkg/pyload/opt/lib/python2.5/urlparse.py", line 193, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
 

FRAMESTACK:

Frame preprocessing in /share/HDA_DATA/.qpkg/pyload/module/plugins/internal/Hoster.py at line 184
	                self = <module.plugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0x1f894b0>
	              thread = <DownloadThread(Thread-2, started daemon)>

Frame process in /share/HDA_DATA/.qpkg/pyload/module/plugins/internal/SimpleHoster.py at line 306
	              pyfile = PyFile 2: cat-bljz.rar@ShareonlineBiz
	                self = <module.plugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0x1f894b0>

Frame download in /share/HDA_DATA/.qpkg/pyload/module/plugins/internal/Hoster.py at line 411
	                 key = 'ref'
	             cookies = True
	                name = u'cat-bljz.rar'
	                 val = True
	                 get = {}
	                 url = u'http://dlw41-2.share-online.biz/dl?u=C74423E9913D2EBEF2137E8A90412CB9942222ECF446239297412BA9944669EDF2422B9A8A4954A8967C33EDC9373F9F&q=v4'
	                self = <module.plugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0x1f894b0>
	   download_location = u'Downloads/Test'
	            filename = u'Downloads/Test/cat-bljz.rar'
	             newname = None
	            location = u'Downloads/Test'
	         disposition = True
	     download_folder = u'Downloads'
	                post = {}
	                 ref = True

Frame urlparse in /share/HDA_DATA/.qpkg/pyload/opt/lib/python2.5/urlparse.py at line 154
	                 url = None
	              scheme = ''
	     allow_fragments = True

Frame urlsplit in /share/HDA_DATA/.qpkg/pyload/opt/lib/python2.5/urlparse.py at line 193
	            fragment = ''
	              netloc = ''
	     allow_fragments = True
	              cached = None
	                 url = None
	                 key = (None, '', True, <type 'NoneType'>, <type 'str'>)
	               query = ''
	              scheme = ''


PLUGIN OBJECT DUMP: 

	          CHECK_FILE = True
	       CHECK_TRAFFIC = True
	             COOKIES = True
	         DIRECT_LINK = None
	         DISPOSITION = True
	       ERROR_PATTERN = '<p class="b">Information:</p>\\s*<div>\\s*<strong>(.*?)</strong>'
	         FILE_ERRORS = [('Html error',
  '\\A(?:\\s*<.+>)?((?:[\\w\\s]*(?:[Ee]rror|ERROR)\\s*\\:?)?\\s*\\d{3})(?:\\Z|\\s+)'),
 ('Request error', '([Aa]n error occured while processing your request)'),
 ('Html file', '\\A\\s*<!DOCTYPE html')]
	        LEECH_HOSTER = False
	        LINK_PATTERN = None
	       LOGIN_ACCOUNT = False
	       LOGIN_PREMIUM = False
	   NAME_REPLACEMENTS = [('&#?\\w+;', <function fixup at 0x1c990b0>)]
	       RECAPTCHA_KEY = '6LdatrsSAAAAAHZrB70txiV5p-8Iv8BtVxlTtjKX'
	   SIZE_REPLACEMENTS = []
	       TEXT_ENCODING = True
	    URL_REPLACEMENTS = [('https?://(?:www\\.)?(share-online\\.biz|egoshare\\.com)/(download\\.php\\?id=|dl/)(?P<ID>\\w+).*',
  'http://www.share-online.biz/dl/\\g<ID>')]
	             account = <module.plugins.accounts.ShareonlineBiz.ShareonlineBiz object at 0x22504b0>
	            api_data = {u'id': u'8LVV7SPN07VF',
 u'md5': u'b1803951eba29e8957f41c4940fa95fd',
 u'name': u'cat-bljz.rar',
 u'size': u'528318009',
 u'status': u'online',
 u'url': u'http://dlw41-2.share-online.biz/dl?u=C74423E9913D2EBEF2137E8A90412CB9942222ECF446239297412BA9944669EDF2422B9A8A4954A8967C33EDC9373F9F&q=v4'}
	             captcha = <module.plugins.internal.Captcha.Captcha object at 0x225ae90>
	         chunk_limit = -1
	           direct_dl = True
	                html = u'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">\n    <head>\n        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n        <meta name="keywords" content="hosting, webhosting, webspace, backup, free download, free upload, download, mp3, movies, music, videos, software, shareware, file transfer, file sharing, file mirroring, file recovery" />\n        <meta name="description" content="Share-Online.biz is a worldwide operating fileserving project. You\'re able to serve and share any type of document like pictures, movies and music with us." />\n        <meta name="title" content="Share-Online.biz" />\n        <meta name="author" content="Share-Online.biz" />\n        <meta name="publisher" content="Share-Online.biz" />\n        <meta name="copyright" content="Share-Online.biz" />\n        <title>Share-Online - dl/8LVV7SPN07VF</title>\n        <link rel="shortcut icon" href="https://www.share-online.biz/favicon.ico" type="image/ico" />\n        <link href="http://www.share-online.biz/template/v3dark/css/main.css" rel="stylesheet" type="text/css" />\n        <link href="http://www.share-online.biz/template/v3dark/css/jquery-ui.css" rel="stylesheet" type="text/css" />\n\n        <script src="http://www.share-online.biz/template/js/jquery.js" type="text/javascript"></script>\n\n        <script src="http://www.share-online.biz/template/js/jquery-ui.js" type="text/javascript"></script>\n\n        <script src="http://www.share-online.biz/template/js/jquery-liscroll.js" type="text/javascript"></script>\n        <script src="http://www.share-online.biz/template/js/tools.js" type="text/javascript"></script>\n\n    </head>\n\n    <body>\n        <script type="text/javascript">\n            \n        </script>\n\n        <script src="http://www.share-online.biz/template/v3dark/js/body.js" type="text/javascript"></script>\n        \n        <script type="text/javascript">\n            \n        </script>\n        \n        <div id="header">\n                        \n            <div id="left">\n                <ul id="left-menu">\n                    <li><span class=\'fs11 b white\'>V3-dark</span></li>\n                    <li>|</li>\n                    <li><a href=\'http://www.share-online.biz/theme/set/v3light\'>V3-light</a></li>\n                </ul>\n                <div id="login-bar">\n                    <div class="login">\n                        <img src="http://www.share-online.biz/template/images/icons/light.png" alt="" border="0" class="vmid" /> <a href="javascript:void(0);" id="login-link">Einloggen</a>\n                        \n                    </div>\n                </div>\n                <div id="login" class="ui-corner-bottom">\n                    <div class="login">\n                        <form action="https://www.share-online.biz/user/login" method="post">\n                            <input type="text" value="" class="login ui-corner-all" name="user" id="l_user" onfocus="login_fields(\'user\', \'click\');" onblur="login_fields(\'user\', \'blur\');" /> <input type="password" value="" class="login ui-corner-all" name="pass" id="l_pass" onfocus="login_fields(\'pass\', \'click\');" onblur="login_fields(\'pass\', \'blur\');" /><div class="forget_pass"><a href="javascript:resend();">Passwort vergessen?</a></div> <div class="c"><input type="checkbox" value="1" name="l_rememberme" id="l_rememberme" title="f\xfcr n\xe4chsten Login merken" /> <label for="l_rememberme">f\xfcr n\xe4chsten Login merken</label></div><span class="login_form"><input type="submit" value="Einloggen" title="Einloggen" class="button" /></span><span class="login_ssl"><a href="http://www.share-online.biz/lang/ssl">SSL/HTTPS: auto</a> <a href=\'https://www.share-online.biz/helpdesk/knowledgebase.php?article=8\' target=\'_blank\' class=\'red\'>(?)</a></span>\n                        </form>\n                        \n                    </div>\n                </div>\n                <div id="logo">\n                    <a href="http://www.share-online.biz/"><img src="http://www.share-online.biz/template/v3dark/images/logo.gif" alt="" width="285" height="50" border="0" /></a>\n                </div>\n            </div>\n            \n            <div class="middle">\n                <ul id="topnav" class="notranslate">\n                    <li>\n                        <a href="http://www.share-online.biz/">home</a>\n                    </li>\n                    <li>\n                        <a href="http://www.share-online.biz/news/">news</a>\n                    </li>\n                    \n                    <li>\n                            \n                        <a href="https://www.share-online.biz/register/premium">Registrieren</a>\n                            \n                    </li>\n                    \n                    <li>\n                            \n                        <a href="https://www.share-online.biz/register/free">Paketvergleich</a>\n                            \n                    </li>\n                    \n                    <li>\n                        <a href="http://www.share-online.biz/faq/">faq</a>\n                    </li>\n                    <li>\n                        <a href="http://www.share-online.biz/tools/">tools</a>\n                    </li>\n                    <li>\n                        <a href="https://www.share-online.biz/helpdesk/index.php?language=Deutsch">support</a>\n                    </li>\n\n\n\n                </ul>\n                <div id="select_lang">\n                    <a href="http://www.share-online.biz/lang/set/english"><img src="http://www.share-online.biz/template/images/lang/en.gif" alt="english" border="0" /></a>\n                    <a href="http://www.share-online.biz/lang/set/german"><img src="http://www.share-online.biz/template/images/lang/de.gif" alt="german" border="0" /></a>\n                </div>\n            </div>\n\n            <div id="page_options" class="ui-corner-top">\n                <a href="http://www.share-online.biz/lang/animations/off">Men\xfcanimation deaktivieren</a> | <a href="http://www.share-online.biz/lang/news/off">News deaktivieren</a>\n            </div>\n\n        </div>\n        <ul id="newsscroller"><li><span>30.04.2015</span><a href=\'https://www.share-online.biz/news/387\'>Neue PPS Raten</a></li><li><span>01.12.2014</span><a href=\'https://www.share-online.biz/news/347\'>Weihnachts Spezial</a></li><li><span>30.11.2014</span><a href=\'https://www.share-online.biz/news/357\'>\xc4nderung Traffic Berechnung</a></li><li><span>09.11.2014</span><a href=\'https://www.share-online.biz/news/327\'>Ersatzleistung</a></li><li><span>07.11.2014</span><a href=\'https://www.share-online.biz/news/307\'>Starker DDOS Angriff</a></li></ul>\n        <noscript><div class="noscript-message"><p><img src="https://www.share-online.biz/template/images/alert.png" alt="0" width="32" height="30" /><strong>Bitte Javascript aktivieren.</strong> Die komplette Funktionalit\xe4t (Download, Upload, Verwaltung) ist andernfalls nicht verf\xfcgbar!</p></div></noscript>\n        \n        <div id="main" class="ui-corner-all">\n            <div id="inner">\n<div id="download">\n    <h1>Bitte w\xe4hlen Sie Ihr Download-Paket</h1>\n    <hr />\n    <div>\n        <script type="text/javascript">\n            \n        </script>\n    </div>\n    <div class="cb"></div>\n    <div id="choose_package">\n        <object data="http://www.share-online.biz/template/swf/choose_package.swf" type="application/x-shockwave-flash" width="700" height="230"><param value="high" name="quality"><param value="opaque" name="wmode"><param value="always" name="allowScriptAccess"></object>\n        <table id="dl_package" cellpadding="0" cellspacing="0" border="0">\n            <tr>\n                <th>kostenlos</th>\n                <th>PREMIUM</th>\n            </tr>\n            <tr>\n                <td class="dl_free details ui-corner-all"><ul><li>teils Captcha Abfragen</li><li>Wartezeiten (minimal 30s)</li><li>limitierter Speed (aktuell max. 175 kb/s)</li><li>st\xf6rende Werbung</li><li>maximal 1 Download auf einmal</li><li>begrenzte Downloadslots</li><li>Downloads nicht wiederaufnehmbar</li><li>Limit von 1024 MB pro Stunde/Datei</li></ul></td>\n                <td class="dl_premium details ui-corner-all"><ul><li>Sofort loslegen</li><li>keine Wartezeiten</li><li>maximale Geschwindigkeit</li><li>keine Werbung, Layer oder Popups</li><li>Paralleler Download von mehreren Dateien</li><li>immer Vorrang vor G\xe4sten und Sammlern</li><li>Downloads wiederaufnehmbar</li><li>kein Stundenlimit</li></ul></td>\n            </tr>\n            <tr>\n                <td><button class="dl_action">>> kostenlos weiter <<</button></td>\n                <td><button class="dl_action">>> Premium Vorteile sichern <<</button></td>\n            </tr>\n        </table>\n\n    </div>\n</div>\n<script type="text/javascript">\n    \n</script>\n\n                <div id="consumer_bottom" class="ui-corner-all">\n                    <iframe id=\'aa81823a\' name=\'aa81823a\' src=\'http://ad.propellerads.com/afr.php?zoneid=2517\' frameborder=\'0\' scrolling=\'no\' width=\'728\' height=\'90\'><a href=\'http://ad.propellerads.com/ck.php?n=a799fafc\' target=\'_blank\'><img src=\'http://ad.propellerads.com/avw.php?zoneid=2517&n=a799fafc\' border=\'0\' alt=\'\' /></a></iframe>\n                </div>\n    \n            </div>\n        </div>\n        <div id="footer">\n            <div class="footer">\n                <ul id="footer-menu">\n                    <li><a href="http://www.share-online.biz/linkcheckapi/">Linkcheck API</a></li>\n                    <li><a href="http://www.share-online.biz/uploadapi/">Upload API</a></li>\n                    <li><a href="http://www.share-online.biz/nopaste/">nopaste</a></li>\n                    <li><a href="http://www.share-online.biz/tos/">AGB</a></li>\n                    <li><a href="http://www.share-online.biz/abuse/">abuse</a></li>\n                    <li class="last"><a href="http://www.share-online.biz/imprint/">Impressum</a></li>\n                </ul>\n            </div>\n            <div id="footer-logo">\n                    <a href="http://www.share-online.biz/"><img src="http://www.share-online.biz/template/v3dark/images/footer_logo.gif" alt="" width="113" height="27" border="0" /></a>\n            </div>\n        </div>\n        <div id="dialog" title="">\n            <p></p>\n        </div>\n        <ul id="contextMenu" class="contextMenu">\n            <li><a href="#action"></a></li>\n        </ul>\n\n        \n        <script type="text/javascript">\n            var alive = "http://www.share-online.biz/alive/";\n        </script>\n    </body>\n</html>'
	                info = {'fileid': '8LVV7SPN07VF',
 'folder': 'cat-bljz.rar',
 'md5': 'b1803951eba29e8957f41c4940fa95fd',
 'name': 'cat-bljz.rar',
 'pattern': {'ID': u'8LVV7SPN07VF'},
 'size': 528318009.0,
 'status': 2,
 'url': u'http://www.share-online.biz/dl/8LVV7SPN07VF'}
	                  js = <module.common.JsEngine.JsEngine instance at 0x1faa1c0>
	          last_check = None
	       last_download = ''
	            leech_dl = False
	             limitDL = 0
	                link = u'http://dlw41-2.share-online.biz/dl?u=C74423E9913D2EBEF2137E8A90412CB9942222ECF446239297412BA9944669EDF2422B9A8A4954A8967C33EDC9373F9F&q=v4'
	             multiDL = True
	             premium = True
	              pyfile = PyFile 2: cat-bljz.rar@ShareonlineBiz
	              pyload = <__main__.Core object at 0x1d47470>
	                 req = <module.network.Browser.Browser object at 0x22d9d88>
	     resume_download = True
	             retries = {}
	          retry_free = False
	              thread = <DownloadThread(Thread-2, started daemon)>
	                user = '86341356492'
	          wait_until = 0
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 0
	               abort = False
	              active = False
	               error = "'NoneType' object has no attribute 'find'"
	                  id = 2
	                lock = <_RLock(None, 0)>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x1da69e0>
	         maxprogress = 100
	                name = u'cat-bljz.rar'
	               order = 0
	           packageid = 2
	              plugin = <module.plugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0x1f894b0>
	         pluginclass = <class 'module.plugins.hoster.ShareonlineBiz.ShareonlineBiz'>
	        pluginmodule = <module 'module.plugins.hoster.ShareonlineBiz' from '/share/HDA_DATA/.qpkg/pyload/module/plugins/hoster/ShareonlineBiz.pyc'>
	          pluginname = u'ShareonlineBiz'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'http://www.share-online.biz/dl/8LVV7SPN07VF'
	           waitUntil = 0


CONFIG: 

{'desc': 'ShareonlineBiz',
 'outline': 'Shareonline.biz hoster plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': True}}

**Comment by Moerdoc** [comment]
Note: I´ve got a Premium Account and i log in.

**Comment by vuolter** [comment]
It's closed yet. u.u
