### ISSUE TITLE
Interval doesnt work anymore

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1618]
i changed my hooks and they are working. bur are executed just once at start of pyload.
They are not being perdiocally executed anymore.
What am i doing wrong ?
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/master/SJ.py
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/master/HDAreaOrg.py

**Comment by Gutz-Pilz** [comment]
can be closed. guess i found a solution

**Comment by vuolter** [comment]
If you need info about new method, just ask. ;)
