### ISSUE TITLE
uptobox: Download Fail

### ISSUE THREAD

**Issue by anthony-ra** [pyload/pyload#1621]
I download the last stable but I can't download :(

this is the log:
295 30.07.2015 18:54:23 WARNING HOSTER UptoboxCom[1]: var rand = new Date(
296 30.07.2015 18:54:23 WARNING HOSTER UptoboxCom[1]: Config option `fallback` not found, use default `True`
297 30.07.2015 18:54:23 WARNING Download failed: Anissa Kate (Harmony Films).mp4 | var rand = new Date(

**Comment by vuolter** [comment]
No solution for now.

**Comment by bast69** [comment]
Hi,

Me, I 've another message :
<code>INFO	Download starts: myDownload.mkv
552	05.08.2015 12:01:57	INFO	HOSTER UptoboxCom[5]: Updating file info...
553	05.08.2015 12:01:57	INFO	HOSTER UptoboxCom[5]: File name: myDownload.mkv
554	05.08.2015 12:01:57	INFO	HOSTER UptoboxCom[5]: File size: 1503238553 bytes
555	05.08.2015 12:01:57	INFO	HOSTER UptoboxCom[5]: File status: online
556	05.08.2015 12:01:58	INFO	HOSTER UptoboxCom[5]: Processing as free download...
557	05.08.2015 12:01:58	WARNING	CAPTCHA UptoboxCom[5]: ReCaptcha | Key pattern not found
558	05.08.2015 12:01:58	WARNING	CAPTCHA UptoboxCom[5]: SolveMedia | Key pattern not found
559	05.08.2015 12:01:58	INFO	HOSTER UptoboxCom[5]: Downloading file...
560	05.08.2015 13:00:40	INFO	HOSTER UptoboxCom[5]: Checking file...
561	05.08.2015 13:00:40	INFO	HOSTER UptoboxCom[5]: File deleted
562	05.08.2015 13:00:40	WARNING	Download failed: myDownload.mkv | File size mismatch | Expected file size: 1503238553.6 | Downloaded file size: 1473438520</code>

Do you have any ideas ?

**Comment by joberreiter** [comment]
New plugin version with #1826.

**Comment by Velociraptor85** [comment]
@GammaC0de this might be solved too =?

**Comment by GammaC0de** [comment]
Probably and if not, irrelevant because the age of this issue, closing.
