### ISSUE TITLE
filename error with 1fichier.com

### ISSUE THREAD

**Issue by b0m0x** [pyload/pyload#1625]
After the recent plugin update the 1fichier.com downloads don't finish cleanly. The Files are downloaded but pyload reports an error because it thinks no file was saved.
In the Download Dir there is a file with the name "file.rar filename*=UTF-8file.rar".

**Comment by vuolter** [comment]
Debug log please.

**Comment by b0m0x** [comment]
Here is the log. Unfortunately without Debug on (because this prevents pyload from starting entirely)
```
HOSTER OneFichierCom[823]: Updating file info...
HOSTER OneFichierCom[823]: File name: file.rar
HOSTER OneFichierCom[823]: File size: 1073701764 bytes
HOSTER OneFichierCom[823]: File status: online
HOSTER OneFichierCom[823]: Processing as free download...
HOSTER OneFichierCom[823]: file.rar saved as file.rar
HOSTER OneFichierCom[823]: Checking file...
HOSTER OneFichierCom[823]: Config option `fallback` not found, use default `True`
WARNING Download failed: file.rar | No file downloaded 
```
It probably just gets the filename wrong, see above.

**Comment by vuolter** [comment]
Eh?! Debug freezes pyload??? O.O
