### ISSUE TITLE
Real debrid plugin

### ISSUE THREAD

**Issue by Dybala93** [pyload/pyload#1626]
Hi,
from last plugins (account and hook) update i can't use Real debrid...
log: Required premium account not found
but on account info it's all ok!
In these months too problems with pyload :(

debug log:
31.07.2015 17:04:57	INFO	pyLoad is up and running
31.07.2015 17:04:57	INFO	HOOK UpdateManager: No new pyLoad version available
31.07.2015 17:04:57	INFO	HOOK UpdateManager: No plugin updates available
31.07.2015 17:04:59	DEBUG	Redirected import module.plugins.hoster.TusfilesNet -> userplugins.hoster.TusfilesNet
31.07.2015 17:04:59	DEBUG	Redirected import module.plugins.internal.XFSHoster -> userplugins.internal.XFSHoster
31.07.2015 17:04:59	DEBUG	Redirected import module.plugins.captcha.ReCaptcha -> userplugins.captcha.ReCaptcha
31.07.2015 17:04:59	DEBUG	Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
31.07.2015 17:04:59	DEBUG	Redirected import module.plugins.captcha.SolveMedia -> userplugins.captcha.SolveMedia
31.07.2015 17:04:59	INFO	Download starts: 1.rar
31.07.2015 17:04:59	WARNING	Download failed: 1.rar | 'NoneType' object has no attribute 'http'
31.07.2015 17:04:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:04:59	ERROR	HOOK RealdebridCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:04:59	INFO	HOOK UnSkipOnFail: Looking for skipped duplicates of: 1.rar (pid:11)
31.07.2015 17:04:59	INFO	HOOK UnSkipOnFail: No duplicates found
31.07.2015 17:05:05	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:05:05	ERROR	HOOK RealdebridCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:05:06	INFO	HOOK ClickAndLoad: Proxy listening on 127.0.0.1:9666
31.07.2015 17:06:00	ERROR	HOOK RealdebridCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:06:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:06:06	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:06:06	ERROR	HOOK RealdebridCom: Error executing addon: maximum recursion depth exceeded

I don't know why closed...maybe my error, sorry!

**Comment by vuolter** [comment]
Please debug log.

**Comment by Dybala93** [comment]
31.07.2015 17:04:57	INFO	pyLoad is up and running
31.07.2015 17:04:57	INFO	HOOK UpdateManager: No new pyLoad version available
31.07.2015 17:04:57	INFO	HOOK UpdateManager: No plugin updates available
31.07.2015 17:04:59	DEBUG	Redirected import module.plugins.hoster.TusfilesNet -> userplugins.hoster.TusfilesNet
31.07.2015 17:04:59	DEBUG	Redirected import module.plugins.internal.XFSHoster -> userplugins.internal.XFSHoster
31.07.2015 17:04:59	DEBUG	Redirected import module.plugins.captcha.ReCaptcha -> userplugins.captcha.ReCaptcha
31.07.2015 17:04:59	DEBUG	Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
31.07.2015 17:04:59	DEBUG	Redirected import module.plugins.captcha.SolveMedia -> userplugins.captcha.SolveMedia
31.07.2015 17:04:59	INFO	Download starts: 1.rar
31.07.2015 17:04:59	WARNING	Download failed: 1.rar | 'NoneType' object has no attribute 'http'
31.07.2015 17:04:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:04:59	ERROR	HOOK RealdebridCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:04:59	INFO	HOOK UnSkipOnFail: Looking for skipped duplicates of: 1.rar (pid:11)
31.07.2015 17:04:59	INFO	HOOK UnSkipOnFail: No duplicates found
31.07.2015 17:05:05	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:05:05	ERROR	HOOK RealdebridCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:05:06	INFO	HOOK ClickAndLoad: Proxy listening on 127.0.0.1:9666
31.07.2015 17:06:00	ERROR	HOOK RealdebridCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:06:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:06:06	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
31.07.2015 17:06:06	ERROR	HOOK RealdebridCom: Error executing addon: maximum recursion depth exceeded

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/a9e1aacd52e53b734c1e18299141900c1c8c0c32
