### ISSUE TITLE
ReCaptcha | Invalid captcha (9kw.eu Captcha)

### ISSUE THREAD

**Issue by Sle3perX** [pyload/pyload#1627]
Hi, im getting the error above, im using 9kw.eu.
If i answer the captcha by myself it works and pyload starts downloading the file.
Sometimes there is this error too:
WARNING	HOSTER ShareonlineBiz[613]: Config option `fallback` not found, use default `True`
Really buggy since the updates 3 days ago i must say^^

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/issues/1601
