### ISSUE TITLE
Package last file Download failed: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by Stufo76** [pyload/pyload#1629]
Last file of a package always fail with following error:

```
WARNING	Download failed: 4308862_1800.mp4 | 'NoneType' object has no attribute 'find'
```

Same error with base plugin download, or with EasyBytez free and premium, or others.
same error with only one file package.

**Comment by vuolter** [comment]
No idea... maybe some extractor plugin???

**Comment by DomiStyle** [comment]
I posted a traceback for this issue [here](https://github.com/pyload/pyload/issues/1634#issuecomment-126663703).
Maybe it helps.

**Comment by vuolter** [comment]
@Stufo76 Debug log please.
@DomiStyle Not the same. Anyhow your is fixed. ;)
