### ISSUE TITLE
Captcha 9kw Bad Upload 0008 find no Captcha

### ISSUE THREAD

**Issue by acidburn78** [pyload/pyload#1630]
I'm sorry but the Captch9kw plugin didn't upload the Captche to 9kw.eu

Here is the Log:

199	31.07.2015 09:49:17	DEBUG	HOSTER ShareonlineBiz[21]: LOAD URL http://www.share-online.biz/dl/OZ3C88SN3NTE/free/ | cookies=True | get={} | req=None | decode=True | multipart=False | post={'dl_free': '1', 'choice': 'free'} | ref=True | just_header=False
200	31.07.2015 09:49:17	DEBUG	HOSTER ShareonlineBiz[21]: LOAD URL http://www.google.com/recaptcha/api/challenge | cookies=True | get={'k': '6LdatrsSAAAAAHZrB70txiV5p-8Iv8BtVxlTtjKX'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
201	31.07.2015 09:49:17	DEBUG	CAPTCHA ShareonlineBiz[21]: ReCaptcha | Challenge: 03AHJ_Vusb6hkuFrkkaZHIEPyU3Ev6CuRP_ewrT5c20RudXM-TVnOH9Hnx3mNRVdZ5Nr7EWlGCwuNHwZqK72oTr0-8E344QU77widfhj8SSRTgi0xU1hECTiXvzjA2d3vQHymz4IBo-k7uVItO1UlYuWxjitVLsgvPwPS9HjOeL8AzvVI0tbwfMh2r0U0YH0trYKaQN5n1EdRpTVnYzAKh6mKQCj2cHhXrTw
202	31.07.2015 09:49:17	DEBUG	HOSTER ShareonlineBiz[21]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
203	31.07.2015 09:49:17	DEBUG	HOSTER ShareonlineBiz[21]: LOAD URL http://www.google.com/recaptcha/api/reload | cookies=True | get={'reason': 'i', 'c': u'03AHJ_Vusb6hkuFrkkaZHIEPyU3Ev6CuRP_ewrT5c20RudXM-TVnOH9Hnx3mNRVdZ5Nr7EWlGCwuNHwZqK72oTr0-8E344QU77widfhj8SSRTgi0xU1hECTiXvzjA2d3vQHymz4IBo-k7uVItO1UlYuWxjitVLsgvPwPS9HjOeL8AzvVI0tbwfMh2r0U0YH0trYKaQN5n1EdRpTVnYzAKh6mKQCj2cHhXrTw', 'type': 'image', 'k': '6LdatrsSAAAAAHZrB70txiV5p-8Iv8BtVxlTtjKX'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
204	31.07.2015 09:49:17	DEBUG	CAPTCHA ShareonlineBiz[21]: ReCaptcha | Second challenge: 03AHJ_Vut_nyvhZt8F0WhkGPbTgg9TqrZR9Aey5UNGeh4JYJ0aRIq_PiAd2DZOITUJnQUBNn5HSdF5PxZqyPV36oCI5jTHXOnQZZcXAoT1JNBgFB_QN2mF77NsBQ1UZFLx9pmPQ9TuI7fjfrU2ixA50t7fSsurB7UMFIu-gDvZA18bIdqPDYbnkg6Vff-2wjLNQVmq581MT4pdEcDPQryQSiiC7Hj0r8JBRg
205	31.07.2015 09:49:17	DEBUG	CAPTCHA ShareonlineBiz[21]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | cookies=True | get={'c': u'03AHJ_Vut_nyvhZt8F0WhkGPbTgg9TqrZR9Aey5UNGeh4JYJ0aRIq_PiAd2DZOITUJnQUBNn5HSdF5PxZqyPV36oCI5jTHXOnQZZcXAoT1JNBgFB_QN2mF77NsBQ1UZFLx9pmPQ9TuI7fjfrU2ixA50t7fSsurB7UMFIu-gDvZA18bIdqPDYbnkg6Vff-2wjLNQVmq581MT4pdEcDPQryQSiiC7Hj0r8JBRg'} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
206	31.07.2015 09:49:17	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={'action': 'usercaptchaguthaben', 'source': 'pyload', 'apikey': u'XXXX', 'pyload': '1'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
207	31.07.2015 09:49:17	INFO	HOOK Captcha9Kw: 43959 credits left
208	31.07.2015 09:49:17	DEBUG	HOOK Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
209	31.07.2015 09:49:18	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={} | req=None | decode=True | multipart=False | post={'file-upload-01': '', 'apikey': u'XXXX', 'captchapermin': 9999, 'case-sensitive': 0, 'prio': 0, 'confirm': False, 'source': 'pyload', 'maxtimeout': 900, 'captchaperhour': 9999, 'selfsolve': False, 'max_len': 50, 'min_len': 2, 'base64': '1', 'numeric': 0, 'action': 'usercaptchaupload', 'phrase': 0, 'pyload': '1', 'mouse': 0, 'math': 0, 'oldsource': 'ShareonlineBiz'} | ref=True | just_header=False
210	31.07.2015 09:49:18	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={} | req=None | decode=True | multipart=False | post={'file-upload-01': '', 'apikey': u'XXXXX', 'captchapermin': 9999, 'case-sensitive': 0, 'prio': 0, 'confirm': False, 'source': 'pyload', 'maxtimeout': 900, 'captchaperhour': 9999, 'selfsolve': False, 'max_len': 50, 'min_len': 2, 'base64': '1', 'numeric': 0, 'action': 'usercaptchaupload', 'phrase': 0, 'pyload': '1', 'mouse': 0, 'math': 0, 'oldsource': 'ShareonlineBiz'} | ref=True | just_header=False
211	31.07.2015 09:49:18	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={} | req=None | decode=True | multipart=False | post={'file-upload-01': '', 'apikey': u'XXXXX', 'captchapermin': 9999, 'case-sensitive': 0, 'prio': 0, 'confirm': False, 'source': 'pyload', 'maxtimeout': 900, 'captchaperhour': 9999, 'selfsolve': False, 'max_len': 50, 'min_len': 2, 'base64': '1', 'numeric': 0, 'action': 'usercaptchaupload', 'phrase': 0, 'pyload': '1', 'mouse': 0, 'math': 0, 'oldsource': 'ShareonlineBiz'} | ref=True | just_header=False
212	31.07.2015 09:49:18	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={} | req=None | decode=True | multipart=False | post={'file-upload-01': '', 'apikey': u'XCXXXXX', 'captchapermin': 9999, 'case-sensitive': 0, 'prio': 0, 'confirm': False, 'source': 'pyload', 'maxtimeout': 900, 'captchaperhour': 9999, 'selfsolve': False, 'max_len': 50, 'min_len': 2, 'base64': '1', 'numeric': 0, 'action': 'usercaptchaupload', 'phrase': 0, 'pyload': '1', 'mouse': 0, 'math': 0, 'oldsource': 'ShareonlineBiz'} | ref=True | just_header=False
213	31.07.2015 09:49:19	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={} | req=None | decode=True | multipart=False | post={'file-upload-01': '', 'apikey': u'XXXXX', 'captchapermin': 9999, 'case-sensitive': 0, 'prio': 0, 'confirm': False, 'source': 'pyload', 'maxtimeout': 900, 'captchaperhour': 9999, 'selfsolve': False, 'max_len': 50, 'min_len': 2, 'base64': '1', 'numeric': 0, 'action': 'usercaptchaupload', 'phrase': 0, 'pyload': '1', 'mouse': 0, 'math': 0, 'oldsource': 'ShareonlineBiz'} | ref=True | just_header=False
214	31.07.2015 09:49:19	ERROR	HOOK Captcha9Kw: Bad upload: 0008 Kein Captcha gefunden.

**Comment by vuolter** [comment]
Do you only removed the API key from the log, right?

**Comment by acidburn78** [comment]
Yes i only remove my API key

**Comment by no-Legend** [comment]
Same here

**Comment by vuolter** [comment]
Whyyyy nothing woorks?! D:

**Comment by acidburn78** [comment]
That's a question that i will give back to you ;)

**Comment by LeoDJ** [comment]
Anything new yet?

**Comment by LeoDJ** [comment]
Okay, take a look at that:
http://forum.pyload.org/viewtopic.php?f=12&t=4443

It seems that the current captcha_image file (.pyload/tmp/captcha_image_XXXXX.jpg) doesn't get written properly and is always 0KB in size until you abort the download.

I hope this helps and there will be a fix soon ;)
