### ISSUE TITLE
ExternalScripts

### ISSUE THREAD

**Issue by DKeppi** [pyload/pyload#1635]
External scripts are not being called since last 2 updates!

Normally at the DEBUG or LOG there is an Info where a Script was found, mine is the folder all_archives_extracted, but since last update this info is gone and no script is called

**Comment by Web-Eye** [comment]
same here

**Comment by nomad71** [comment]
Ay! Can confirm!

**Comment by Gummibaer** [comment]
The External scripts dont see the Scriptfiles !! Nothing in Log

**Comment by CrEaK** [comment]
Can confirm! External scripts dont see my script at startup. No entry in the logs

**Comment by c0rrre** [comment]
Can confirm too

**Comment by dizzle667** [comment]
can confirm it. I have it with package_finished. If it helps, AndroidPhoneNotify sends a message, that one package could not be completed, although it is completed successfully. Maybe there is something wrong with the completion?
