### ISSUE TITLE
 LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by anthony-ra** [pyload/pyload#1636]
I think it is the same issue as #1633 

In debug mode:
[/share/CACHEDEV1_DATA/.qpkg] # ps aux | grep pyload
11969 admin       532 S   grep pyload 
[/share/CACHEDEV1_DATA/.qpkg] # /etc/init.d/pyload.sh debug
Stopping pyLoad
No pyLoad running.
Starting pyLoad - Debug mode
31.07.2015 13:09:12 INFO      Starting pyLoad 0.4.9
31.07.2015 13:09:12 INFO      Using home directory: /share/CACHEDEV1_DATA/.qpkg/pyload/data
31.07.2015 13:09:12 DEBUG     Remote activated: True
31.07.2015 13:09:13 DEBUG     created index of plugins
31.07.2015 13:09:13 DEBUG     Redirected import module.plugins.internal.MultiHook -> userplugins.internal.MultiHook
31.07.2015 13:09:13 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
31.07.2015 13:09:13 DEBUG     Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
31.07.2015 13:09:13 DEBUG     Redirected import module.plugins.internal.SimpleCrypter -> userplugins.internal.SimpleCrypter
31.07.2015 13:09:13 DEBUG     Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
31.07.2015 13:09:13 DEBUG     Redirected import module.plugins.internal.Captcha -> userplugins.internal.Captcha
31.07.2015 13:09:13 DEBUG     Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
31.07.2015 13:09:13 DEBUG     HOOK ExternalScripts: Deprecated method `event_list`, use `event_map` instead
31.07.2015 13:09:13 DEBUG     Redirected import module.plugins.hooks.AntiStandby -> userplugins.hooks.AntiStandby
31.07.2015 13:09:13 INFO      Activated plugins: AntiStandby, ClickAndLoad, ExternalScripts, ExtractArchive, LinkdecrypterComHook, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
31.07.2015 13:09:13 INFO      Deactivate plugins: AlldebridComHook, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
31.07.2015 13:09:13 INFO      Downloadtime: True
31.07.2015 13:09:13 INFO      Starting ThriftBackend: 0.0.0.0:7227
31.07.2015 13:09:13 INFO      Free space: 1.47 TiB
31.07.2015 13:09:13 INFO      Starting builtin webserver: 0.0.0.0:8100
31.07.2015 13:09:13 INFO      Activating Accounts...
31.07.2015 13:09:13 INFO      Activating Plugins...
31.07.2015 13:09:13 WARNING   HOOK AntiStandby: Unable to change power state | [Errno 2] No such file or directory
31.07.2015 13:09:13 INFO      HOOK XFileSharingPro: Handling any hoster I can!
31.07.2015 13:09:13 DEBUG     HOOK XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?:\w+\.)*?(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
31.07.2015 13:09:13 INFO      HOOK XFileSharingPro: Handling any crypter I can!
31.07.2015 13:09:13 DEBUG     HOOK XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?:\w+\.)*?(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:user|folder)s?/\w+
31.07.2015 13:09:13 DEBUG     HOOK ExtractArchive: Found UnRar 3.60 | Found SevenZip 9.04
31.07.2015 13:09:13 INFO      pyLoad is up and running
31.07.2015 13:09:14 DEBUG     HOOK UpdateManager: LOAD URL http://updatemanager.pyload.org | decode=True | cookies=True | get={'v': '0.4.9'} | req=None | _[1]=['decode=True', 'cookies=True', "get={'v': '0.4.9'}", 'req=None'] | multipart=False | post={} | ref=True | just_header=False
31.07.2015 13:09:14 INFO      HOOK UpdateManager: No new pyLoad version available
31.07.2015 13:09:14 DEBUG     HOOK UpdateManager: Requested deletion of plugins: [(u'accounts', u'BillionuploadsCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'ShareRapidCom'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'Movie2kTo'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'EasybytezCom'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FreeWayMe'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultishareCz'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'OverLoadMe'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PutdriveCom'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RapideoPl'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RehostTo'), (u'hooks', u'ReloadCc'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SmoozedCom'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'ZeveraCom'), (u'hoster', u'File4safeCom'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'Vipleech4uCom'), (u'internal', u'AbstractExtractor'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster')]
31.07.2015 13:09:14 INFO      HOOK UpdateManager: No plugin updates available
31.07.2015 13:09:16 ERROR     HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/internal/Addon.py", line 97, in _periodical
    self.periodical()
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/internal/MultiHook.py", line 159, in periodical
    self.load_account()
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/internal/MultiHook.py", line 87, in load_account
    self.load_account()
*********
lines repeted many times
*********
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/internal/MultiHook.py", line 87, in load_account
    self.load_account()
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/internal/MultiHook.py", line 87, in load_account
    self.load_account()
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/internal/MultiHook.py", line 85, in load_account
    self.account = self.pyload.accountManager.getAccountPlugin(self.pluginname)
RuntimeError: maximum recursion depth exceeded
^C31.07.2015 13:09:52 INFO      shutting down...
31.07.2015 13:09:52 WARNING   HOOK AntiStandby: Unable to change power state | [Errno 2] No such file or directory
31.07.2015 13:09:52 DEBUG     Deleting old pidfile pyload.pid
31.07.2015 13:09:52 INFO      killed pyLoad from Terminal

thanks

**Comment by acidburn78** [comment]
also here

**Comment by moson-mo** [comment]
Issue came with this commit:
https://github.com/pyload/pyload/commit/cc3c575a68fd4b585f0e4af586e027fddb0fe605

Previous one is working fine (8a8323f3fd86985a5ca876e8d54f1699e75b24a8)

**Comment by marviobezerra** [comment]
I have the same erro!

ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded

**Comment by koroki** [comment]
Same error here...

**Comment by d4re89** [comment]
Looks like this part in module/plugins/internal/MultiHook.py is probably the problem:
     def load_account(self):
         self.account = self.pyload.accountManager.getAccountPlugin(self.pluginname)
         self.load_account()

**Comment by sonics007** [comment]
Odoslané zo služby Samsung Mobile

**Comment by sonics007** [comment]
Odoslané zo služby Samsung Mobile

-------- Pôvodná správa --------
Od: moson-mo <notifications@github.com> 
Dátum: 31. 07. 2015  14:32  (GMT+01:00) 
Komu: pyload/pyload <pyload@noreply.github.com> 
Predmet: Re: [pyload]  LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded (#1636) 
 
Issue came with this commit:
cc3c575

Previous one is working fine (8a8323f)
