### ISSUE TITLE
ShareOnline doesn't work

### ISSUE THREAD

**Issue by middrive** [pyload/pyload#1643]
Hi

pyload doesn't work with premium account
if i use my valid account data it comes this error
107	01.08.2015 13:06:49	INFO	ACCOUNT ShareonlineBiz: Parsing account info for user `************`...
106	01.08.2015 13:06:49	WARNING	ACCOUNT ShareonlineBiz: Could not login user *********` | expected string or buffer
105	01.08.2015 13:06:47	INFO	ACCOUNT ShareonlineBiz: Login user `*********`...

if i use random account data (doesn't know its exist)
it looks it works right
116	01.08.2015 13:09:26	INFO	ACCOUNT ShareonlineBiz: Parsing account info for user `random`...
115	01.08.2015 13:09:24	WARNING	ACCOUNT ShareonlineBiz: Could not login user `random` | Invalid username/password
114	01.08.2015 13:09:24	INFO	ACCOUNT ShareonlineBiz: Login user `random`...

here my debug report
01.08.2015 12:48:21 INFO      starte pyLoad 0.4.9
01.08.2015 12:48:21 INFO      Benutze Home-Verzeichnis: /mnt/system/opt/share/pyload_config
01.08.2015 12:48:21 DEBUG     Remote activated: True
01.08.2015 12:48:23 DEBUG     created index of plugins
01.08.2015 12:48:23 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
01.08.2015 12:48:23 DEBUG     Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
01.08.2015 12:48:23 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
01.08.2015 12:48:23 DEBUG     HOOK ExternalScripts: Deprecated method `event_list`, use `event_map` instead
01.08.2015 12:48:23 DEBUG     Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
01.08.2015 12:48:23 DEBUG     Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
01.08.2015 12:48:23 INFO      Aktivierte Plugins: ClickAndLoad, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager
01.08.2015 12:48:23 INFO      Deaktivierte Plugins: AlldebridComHook, AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterComHook, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, UserAgentSwitcher, WindowsPhoneNotify, XFileSharingPro, XMPPInterface, ZeveraComHook
01.08.2015 12:48:23 INFO      Downloadzeit: True
01.08.2015 12:48:23 INFO      Starte ThriftBackend: 0.0.0.0:7227
01.08.2015 12:48:24 INFO      Free space: 3.34 TiB
01.08.2015 12:48:24 INFO      Starting builtin webserver: 0.0.0.0:8000
01.08.2015 12:48:24 INFO      Activating Accounts...
01.08.2015 12:48:24 DEBUG     Redirected import module.plugins.accounts.ShareonlineBiz -> userplugins.accounts.ShareonlineBiz
01.08.2015 12:48:24 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
01.08.2015 12:48:24 INFO      ACCOUNT ShareonlineBiz: Login user `********`...
01.08.2015 12:48:24 DEBUG     ACCOUNT ShareonlineBiz: LOAD URL http://api.share-online.biz/cgi-bin | decode=False | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': '*******', 'password': '********'} | req=None | _[1]=['decode=False', 'cookies=True', "get={'q': 'userdetails', 'aux': 'traffic', 'username': '********', 'password': '*********'}", 'req=None'] | multipart=False | post={} | ref=True | just_header=False
01.08.2015 12:48:25 DEBUG     ACCOUNT ShareonlineBiz: user=********
email=*******@********.com
group=Premium
register_date=1284467613
expire_date=1528895999
points=7478
money=15.70
a=92442E8DE6133FEC943D78EEED4F35DA9010689ED21A59EAE83328B3F2744ED2905547C38D175FEEEF3D06E4AF3B03C3857D22CAD252059D953C2AE4F6775EF3
traffic_1d=0;0.000
traffic_7d=0;0.000
01.08.2015 12:48:25 WARNING   ACCOUNT ShareonlineBiz: Could not login user `*********` | expected string or buffer
01.08.2015 12:48:25 INFO      ACCOUNT ShareonlineBiz: Parsing account info for user `********`...
01.08.2015 12:48:25 DEBUG     ACCOUNT ShareonlineBiz: Account info for user `********`: {'login': {'timestamp': 1438426104.571862, 'password': '**********', 'valid': False}, 'data': {'premium': None, 'trafficleft': None, 'options': {}, 'maxtraffic': None, 'validuntil': None, 'login': '********', 'password': ********, 'type': 'ShareonlineBiz', 'valid': False}}
01.08.2015 12:48:25 INFO      Activating Plugins...
01.08.2015 12:48:25 DEBUG     Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
01.08.2015 12:48:25 DEBUG     Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
01.08.2015 12:48:25 DEBUG     Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
01.08.2015 12:48:25 DEBUG     HOOK ExtractArchive: Found UnRar 5.00
01.08.2015 12:48:25 DEBUG     HOOK UpdateManager: LOAD URL http://updatemanager.pyload.org | decode=True | cookies=True | get={'v': '0.4.9'} | req=None | _[1]=['decode=True', 'cookies=True', "get={'v': '0.4.9'}", 'req=None'] | multipart=False | post={} | ref=True | just_header=False
01.08.2015 12:48:25 INFO      pyLoad is up and running
01.08.2015 12:48:27 INFO      HOOK UpdateManager: No new pyLoad version available
01.08.2015 12:48:27 DEBUG     HOOK UpdateManager: Requested deletion of plugins: [(u'accounts', u'BillionuploadsCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'ShareRapidCom'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'Movie2kTo'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'EasybytezCom'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FreeWayMe'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultishareCz'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'OverLoadMe'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PutdriveCom'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RapideoPl'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RehostTo'), (u'hooks', u'ReloadCc'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SmoozedCom'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'ZeveraCom'), (u'hoster', u'File4safeCom'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'Vipleech4uCom'), (u'internal', u'AbstractExtractor'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster')]
01.08.2015 12:48:27 INFO      HOOK UpdateManager: No plugin updates available
01.08.2015 12:48:35 INFO      HOOK ClickAndLoad: Proxy listening on 0.0.0.0:9666
01.08.2015 12:49:18 INFO      shutting down...
01.08.2015 12:49:18 DEBUG     Deleting old pidfile pyload.pid
01.08.2015 12:49:18 INFO      pyLoad quits

please help can't use pyload since 1 week

**Comment by J-8** [comment]
Sadly, I have the exact same problem. If any more information is needed, I'll be happy to supply.

**Comment by wastez** [comment]
Here share-online is also not working anymore..... :(

**Comment by middrive** [comment]
what i wonder is
yesterday i was by a friend
he use pyload on a synology diskstation
he get also the problems after update last week
but after uninstall and install again
it works and accept share online premium account without problems
so what he have what i not have

**Comment by wastez** [comment]
In the moment i´m using the plugins a few weeks ago.
Just download the plugins from 2 - 3 weeks ago and insert it in the folders where they belong.
Don´t forget to disable the updatemanager.

**Comment by middrive** [comment]
hi again
where i can get older plugins
if i want download src i cant get (site not possible https://get.pyload.org/get/src/) 
only latest stable zip i can download

**Comment by menaceone** [comment]
same here. share online is broken.

**Comment by wastez** [comment]
@ middrive
You can get it here.
Just pick a moment from the commits.
Here is the source 26 days ago: https://github.com/pyload/pyload/tree/b1759bc440cd6013837697eb8de540914f693ffd

**Comment by middrive** [comment]
thanks it works
i leran from this and save my working pyload as backup before i try updates

**Comment by wastez** [comment]
Yes but this is does nothing change to the actual source....
So it should stay open...

**Comment by J-8** [comment]
This issue is not solved. Status Closed is absolutely incorrect, as this is only a workaround which really cannot be the way to go. @middrive: Please reopen.

**Comment by hardy123480** [comment]
@wastez Which plugins do we have to replace? Just the ShareonlineBiz.py ? Thanks

**Comment by dannoe** [comment]
first login is working, after the timeout it will break again

Log: (i only changed my username in "myusername")

16966	02.08.2015 11:19:30	WARNING	ACCOUNT ShareonlineBiz: Could not login user `myusername` | 'password'
16965	02.08.2015 11:19:30	INFO	ACCOUNT ShareonlineBiz: Relogin user `myusername`...
16964	02.08.2015 11:19:30	DEBUG	ACCOUNT ShareonlineBiz: Reached login timeout for myusername

**Comment by no-Legend** [comment]
Same here.
