### ISSUE TITLE
HOOK AntiStandby: Error executing addon: 'ascii' codec can't decode byte 0x81 in position 41: ordinal not in range(128) 

### ISSUE THREAD

**Issue by Sporrdig** [pyload/pyload#1651]
AntiStandby Issue:

Log:
HOOK AntiStandby: Error executing addon: 'ascii' codec can't decode byte 0x81 in position 41: ordinal not in range(128) 

directory path:
xxx/pyload/data/userplugins/hooks

Debug:
    __authors__     = [("Walter Purcaro", "vuolter@gmail.com")]

**Comment by Sporrdig** [comment]
WARNING   HOOK AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
WARNING   HOOK AntiStandby: Unable to change display power state | [Errno 2] No such file or directory

**Comment by vuolter** [comment]
Please post the content of your debug file (you should find it under your pyload config directory).

**Comment by Sporrdig** [comment]
Thanks you very mutch. 
It works now.

But you Need this AntiStandby debug ? Say me please the dirdirectory path, in what Folder is this). I'm in the application Folder from Pyload. I have only more this data Folder by top Folder from pyload. In the data Folder is Folder:
Logs
scripts
temp
userplugins (this Folder looking same insite who your plugin Folder. But not with always the same plugins)

**Comment by vuolter** [comment]
No, that's okay.
