### ISSUE TITLE
Uploaded Premuim Accout Captcha after fix from 02.08.2015

### ISSUE THREAD

**Issue by Sporrdig** [pyload/pyload#1653]
After Plugin Update form 02.08.2015:
Fixed: Download failed: 'NoneType' object has no attribute 'http'

but by Premium Account Uploaded.to (Uploaded.net) it ask for Catcha, when the Download start. 
The File is downloaded and in the Folder.
The mp4 Files works.
Status of the Download is stay by start Download.

Click and Load works
9kw works, but by a premuim Account i not want use me credits.
DLC add works.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Maybe this is a multipost, see #1622 , apologize...
[Uploaded.To] fall back to free-account #1622 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

But this post is older who today, 02.08.2015.

Debug Log:
HOSTER UploadedTo[2]: PROCESS URL http://uploaded.net/file/02swc61l | PLUGIN VERSION 0.96
INFO      HOSTER UploadedTo[2]: Updating file info...
DEBUG     HOSTER UploadedTo[2]: File info: {'status': 2, 'name': '[Pure-Ani.me]_Aoharu_X_Kinkanjuu_02v2_Ger_Sub.mp4', 'url': u'http://uploaded.net/file/02swc61l', 'pattern': {'ID': u'02swc61l'}, 'folder': '[Pure-Ani.me]_Aoharu_X_Kinkanjuu_02v2_Ger_Sub.mp4', 'size': 227311806.0}
DEBUG     HOSTER UploadedTo[2]: Previous file info: {'status': 2, 'name': '[Pure-Ani.me]_Aoharu_X_Kinkanjuu_02v2_Ger_Sub.mp4', 'url': u'http://uploaded.net/file/02swc61l', 'pattern': {'ID': u'02swc61l'}, 'folder': '[Pure-Ani.me]_Aoharu_X_Kinkanjuu_02v2_Ger_Sub.mp4', 'size': 227311806.0}
INFO      HOSTER UploadedTo[2]: File name: [Pure-Ani.me]_Aoharu_X_Kinkanjuu_02v2_Ger_Sub.mp4
INFO      HOSTER UploadedTo[2]: File size: 227311806 bytes
INFO      HOSTER UploadedTo[2]: File status: online
DEBUG     HOSTER UploadedTo[2]: LOAD URL http://uploaded.net/file/02swc61l | decode=True | cookies=True | get={} | req=None | _[1]=['decode=True', 'cookies=True', 'get={}', 'req=None'] | multipart=False | post={} | ref=False | just_header=False
INFO      HOSTER UploadedTo[2]: Processing as free download...
DEBUG     HOSTER UploadedTo[2]: LOAD URL http://uploaded.net/language/en | decode=True | cookies=True | get={} | req=None | _[1]=['decode=True', 'cookies=True', 'get={}', 'req=None'] | multipart=False | post={} | ref=True | just_header=True
DEBUG     HOSTER UploadedTo[2]: LOAD URL http://uploaded.net/js/download.js | decode=True | cookies=True | get={} | req=None | _[1]=['decode=True', 'cookies=True', 'get={}', 'req=None'] | multipart=False | post={} | ref=True | just_header=False
DEBUG     CAPTCHA UploadedTo[2]: ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
DEBUG     HOSTER UploadedTo[2]: LOAD URL http://www.google.com/recaptcha/api/challenge | decode=True | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | _[1]=['decode=True', 'cookies=True', "get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'}", 'req=None'] | multipart=False | post={} | ref=True | just_header=False
DEBUG     CAPTCHA UploadedTo[2]: ReCaptcha | Challenge: 03AHJ_Vuvvp0uDL3B28FbxilJhA3cUq0apnN130t4Ttpc9x37LxnB4eatlF8-UUL1gzEVwDf0QxIhpuxpJURHVqqkMkgQXAL2nab29bjeIrTUPPD0wsv9rA9qZXWyVq1jhjT1jNvXdDKmQtSpjBbJ0Uoyo1SMQnFGfy89jWNIlHVhNsQ-QWrRAGxOxfbilMkLztiBqCQgVTO4x64wXfUWN3F4CjhApy5KZkQ
DEBUG     HOSTER UploadedTo[2]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | decode=True | cookies=True | get={} | req=None | _[1]=['decode=True', 'cookies=True', 'get={}', 'req=None'] | multipart=False | post={} | ref=True | just_header=False
DEBUG     HOSTER UploadedTo[2]: LOAD URL http://www.google.com/recaptcha/api/reload | decode=True | cookies=True | get={'reason': 'i', 'c': u'03AHJ_Vuvvp0uDL3B28FbxilJhA3cUq0apnN130t4Ttpc9x37LxnB4eatlF8-UUL1gzEVwDf0QxIhpuxpJURHVqqkMkgQXAL2nab29bjeIrTUPPD0wsv9rA9qZXWyVq1jhjT1jNvXdDKmQtSpjBbJ0Uoyo1SMQnFGfy89jWNIlHVhNsQ-QWrRAGxOxfbilMkLztiBqCQgVTO4x64wXfUWN3F4CjhApy5KZkQ', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | _[1]=['decode=True', 'cookies=True', "get={'reason': 'i', 'c': u'03AHJ_Vuvvp0uDL3B28FbxilJhA3cUq0apnN130t4Ttpc9x37LxnB4eatlF8-UUL1gzEVwDf0QxIhpuxpJURHVqqkMkgQXAL2nab29bjeIrTUPPD0wsv9rA9qZXWyVq1jhjT1jNvXdDKmQtSpjBbJ0Uoyo1SMQnFGfy89jWNIlHVhNsQ-QWrRAGxOxfbilMkLztiBqCQgVTO4x64wXfUWN3F4CjhApy5KZkQ', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'}", 'req=None'] | multipart=False | post={} | ref=True | just_header=False
DEBUG     CAPTCHA UploadedTo[2]: ReCaptcha | Second challenge: 03AHJ_VusNAciVzU9Jk6K_zXGbgRIy6Q0S4uvq4ZRUoVobygnSFSjG-k75xaqlV6Xku3incJOvP5YcpaD8LgUyiIZs_J6qnCTyE1KeMuBCtDlYsp_K0W3D7Y5_0jhxR8Dodi3OOmBreg_VIGZEWk6Kk3JY-RWflV-p88L5jRcULaBzSu0Arb9rA_j7NAeLjhlxUqfFh9NvXMNAqxbyRZ6NNfHUrks_Qet76g
DEBUG     CAPTCHA UploadedTo[2]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | decode=False | cookies=True | get={'c': u'03AHJ_VusNAciVzU9Jk6K_zXGbgRIy6Q0S4uvq4ZRUoVobygnSFSjG-k75xaqlV6Xku3incJOvP5YcpaD8LgUyiIZs_J6qnCTyE1KeMuBCtDlYsp_K0W3D7Y5_0jhxR8Dodi3OOmBreg_VIGZEWk6Kk3JY-RWflV-p88L5jRcULaBzSu0Arb9rA_j7NAeLjhlxUqfFh9NvXMNAqxbyRZ6NNfHUrks_Qet76g'} | req=None | _[1]=['decode=False', 'cookies=True', "get={'c': u'03AHJ_VusNAciVzU9Jk6K_zXGbgRIy6Q0S4uvq4ZRUoVobygnSFSjG-k75xaqlV6Xku3incJOvP5YcpaD8LgUyiIZs_J6qnCTyE1KeMuBCtDlYsp_K0W3D7Y5_0jhxR8Dodi3OOmBreg_VIGZEWk6Kk3JY-RWflV-p88L5jRcULaBzSu0Arb9rA_j7NAeLjhlxUqfFh9NvXMNAqxbyRZ6NNfHUrks_Qet76g'}", 'req=None'] | multipart=False | post={} | ref=False | just_header=False

**Comment by sraedler** [comment]
uploaded is working

please close
