### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by scrimpy** [pyload/pyload#1655]

**Comment by NETHeader** [comment]
?

**Comment by scrimpy** [comment]
one error leads to another, I really never saw someone developing a software like this. 
the only reason for releasing untested shitass code to the public is that the project is gonna die anyway and i dont have to care what im doing.
have fun, im gonna switch to jdownloader now.

**Comment by vuolter** [comment]
Bye bye.
