### ISSUE TITLE
User to add Failed with the command: python pyLoadCore.py -u

### ISSUE THREAD

**Issue by Sporrdig** [pyload/pyload#1656]
When i want try to add a user with pyLoadCore.py -u. Then come this fail alert:

Debug Log from Terminal:

Traceback (most recent call last):
  File "pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/xxx/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/xxx//pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/xxx/pyload/module/network/HTTPRequest.py", line 20, in <module>
    import pycurl
ImportError: No module named pycurl

**Comment by NETHeader** [comment]
pycurl is missing, not correctly installed or could not be found within the python path.
Read the readme at  https://github.com/pyload/pyload under 'Dependencies'.

**Comment by Sporrdig** [comment]
okey. But how install pycurl of a QNAP NAS. I doen't have more OPTWARE. 
Of cource over ssh. But how?

**Comment by Sporrdig** [comment]
so: pycurl] # python setup.py install                                             sh: curl-config: command not found
Traceback (most recent call last):
  File "setup.py", line 90, in <module>
    raise Exception, ("`%s' not found -- please install the libcurl development files" % CURL_CONFIG)
Exception: `curl-config' not found -- please install the libcurl development files

**Comment by Sporrdig** [comment]
/Python/pylibmc-1.4.3] # python setup.py install
running install
running build
running build_py
running build_ext
building '_pylibmc' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_ZLIB -I/share/CACHEDEV1_DATA/.qpkg/Python/include/python2.7 -c src/_pylibmcmodule.c -o build/temp.linux-x86_64-2.7/src/_pylibmcmodule.o -fno-strict-aliasing
unable to execute gcc: No such file or directory
error: command 'gcc' failed with exit status 1

**Comment by Sporrdig** [comment]
/Python/pycurl-7.19.0.2] # python setup.py install                             sh: curl-config: command not found
Traceback (most recent call last):
  File "setup.py", line 90, in <module>
    raise Exception("`%s' not found -- please install the libcurl development files or specify --curl-config=/path/to/curl-config" % CURL_CONFIG)
Exception: `curl-config' not found -- please install the libcurl development files or specify --curl-config=/path/to/curl-config
