### ISSUE TITLE
HOOK ExtractArchive: No files found to extract

### ISSUE THREAD

**Issue by J-Ha** [pyload/pyload#1658]
After Finishing the Download, ExractArchive does not reconize .rar Files

479	02.08.2015 11:33:34	INFO	Package finished: Download - Package
480	02.08.2015 11:33:34	DEBUG	HOOK ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
481	02.08.2015 11:33:34	INFO	HOOK ExtractArchive: Check package: Download - Package
482	02.08.2015 11:33:34	DEBUG	All downloads processed
483	02.08.2015 11:33:34	DEBUG	All downloads finished
484	02.08.2015 11:33:34	INFO	HOOK ExtractArchive: No files found to extract

**Comment by J-Ha** [comment]
Fixed Systemside, updated $PATH

**Comment by vuolter** [comment]
@J-Ha Could you explain how?!

**Comment by J-Ha** [comment]
I'm using a DLink-DNS-320L, the pyload version comes with an included python 2.7 version, there was only a symlink to the unrar application in the /bin folder missing.

**Comment by hbbernardo** [comment]
J-HA, how did you solve this? I have just installed pyload on my DNS-320L. Ive looked into the /bin folder and there isn't any unrar binary or folder in there.

Please, let me know.
