### ISSUE TITLE
Config option `fallback` not found, use default `True`

### ISSUE THREAD

**Issue by scrimpy** [pyload/pyload#1660]
02.08.2015 11:51:07	WARNING	HOSTER UploadedTo[102]: Premium download failed | No file downloaded
101	02.08.2015 11:51:07	DEBUG	HOSTER UploadedTo[102]: Config option `fallback` not found, use default `True`
100	02.08.2015 11:51:07	INFO	HOSTER UploadedTo[102]: Checking file...
99	02.08.2015 11:51:06	DEBUG	Content-Disposition: 
98	02.08.2015 11:51:06	DEBUG	HOSTER UploadedTo[102]: DOWNLOAD URL http://am4-r1f6-stor07.uploaded.net/dl/9cae578a-c546-43d4-a605-6ab3a5b60e7d | cookies=True | get={} | disposition=True | post={} | ref=True
97	02.08.2015 11:51:06	INFO	HOSTER UploadedTo[102]: Downloading file...
96	02.08.2015 11:51:06	INFO	HOSTER UploadedTo[102]: Processing as premium download...

therese no debug log output, since this seems not recognized as a bug

**Comment by vuolter** [comment]
`Config option fallback not found, use default True` is not an issue properly... it's asimple warning due not implemented feature.
