### ISSUE TITLE
Checksum Error

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1667]
Hello,

Every Download ends in:

A new issue:
621	02.08.2015 19:45:10	WARNING	Download failed: wcd.x264.S06E03.part3.rar | Incorrect file size
620	02.08.2015 19:45:10	WARNING	HOOK Checksum: File wcd.x264.S06E03.part3.rar has incorrect size: 105906176 B (105906176 expected)

**Comment by vuolter** [comment]
Quick solution: disable the Checksum plugin. Hashsum is not processed correctly by the plugin, and size comparison is now performed internally. ;)

**Comment by wastez** [comment]
Yes thats clear allready did that. 
But now i reverted the Plugins before this big Update because for ne it US not useable because share online is not working aus it should.

**Comment by vuolter** [comment]
Check latest 0.4.9... maybe this time will work. :P

**Comment by godfuture** [comment]
Hey guys,
same issue. I tried to download with SO, it seem Pyload is downloading the files, but somehow the checksum check is still incorrect. Plugins got just updated:
```
2983	05.08.2015 23:45:57	INFO	HOSTER ShareonlineBiz[14]: No errors found
2984	05.08.2015 23:45:57	INFO	Download finished: BHDTEGS72TDRE.part10.rar
2985	05.08.2015 23:45:57	WARNING	HOOK Checksum: File BHDTEGS72TDRE.part10.rar has incorrect size: 157286400 B (157286400 expected)
2986	05.08.2015 23:45:57	WARNING	Download failed: BHDTEGS72TDRE.part10.rar | Incorrect file size 
```
Deactivate checksum check or is there a fix ready?

Thx

**Comment by CodeUnit** [comment]
So I have the same problem on my system.
My solution:
In file "userplugins/hooks/Checksum.py" Line 117 I changed "if api_size is not file_size:" in "if api_size != file_size:"

Good luck
