### ISSUE TITLE
XFileSharingPro.py missmatch Version by UpdateManager

### ISSUE THREAD

**Issue by Sporrdig** [pyload/pyload#1668]
Here a Little Issue:

You have update XFileSharingPro.py. 
The Problem is that XFileSharingPro.py in the accont folder can't update over updatemanager, because the Version is missmatch. So the error. 

I have no more debug log. Because i Update Manual.

**Comment by GammaC0de** [comment]
#1690
@vuolter please close

**Comment by Sporrdig** [comment]
Sry
