### ISSUE TITLE
[plugin] UlozTo

### ISSUE THREAD

**Issue by closedhead** [pyload/pyload#1671]
147	03.08.2015 00:54:19	CRITICAL	'NoneType' object has no attribute 'UlozTo'
146	03.08.2015 00:54:19	ERROR	Error importing UlozTo: name 'convertDecimalPrefix' is not defined
145	03.08.2015 00:54:19	DEBUG	Redirected import module.plugins.hoster.UlozTo -> userplugins.hoster.UlozTo

**Comment by sraedler** [comment]
I checked, uloz.to is working
[http://uloz.to/live/xboCaZjJ/31s-cz-restart-mkv](testlink)

please close
