### ISSUE TITLE
LinkdecrypterComHook does not work

### ISSUE THREAD

**Issue by koroki** [pyload/pyload#1674]
WARNING   HOOK LinkdecrypterCom: 'LinkdecrypterComHook' object has no attribute 'COOKIES' | Waiting 1 minute and retry

Any link can be added, simply does not start to download.

**Comment by byte4geek** [comment]
same error:

03.08.2015 15:57:38	INFO	Added package fdfdfdf containing 1 links
195	03.08.2015 15:57:38	INFO	Decrypting starts: http://share-links.biz/_xbt5isn9f22jd
196	03.08.2015 15:57:38	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
197	03.08.2015 15:57:38	DEBUG	CRYPTER ShareLinksBiz[1]: PROCESS URL http://share-links.biz/_xbt5isn9f22jd | PLUGIN VERSION 1.16
198	03.08.2015 15:57:38	DEBUG	CRYPTER ShareLinksBiz[1]: LOAD URL http://www.share-links.biz/_xbt5isn9f22jd | decode=True | cookies=True | get={} | req=None | _[1]=['decode=True', 'cookies=True', 'get={}', 'req=None'] | multipart=False | post={} | ref=True | just_header=False
199	03.08.2015 15:57:38	ERROR	Decrypting failed: http://share-links.biz/_xbt5isn9f22jd | 'ShareLinksBiz' object has no attribute 'COOKIES'
200	03.08.2015 15:57:38	DEBUG	Error creating zip file: [Errno 2] No such file or directory: 'tmp/ShareLinksBiz'
201	03.08.2015 15:57:38	INFO	Debug Report written to debug_ShareLinksBiz_03-08-2015_15-57-38.txt 

|
|
|
[/share/HDA_DATA/.qpkg/pyload/data] # more debug_ShareLinksBiz_03-08-2015_15-57-38.txt
pyLoad 0.4.9 Debug Report of ShareLinksBiz 1.16

TRACEBACK:
 Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/share/HDA_DATA/.qpkg/pyload/module/plugins/internal/Hoster.py", line 184, in preprocessing
    return self.process(self.pyfile)
  File "/share/HDA_DATA/.qpkg/pyload/module/plugins/internal/Crypter.py", line 41, in process
    self.decrypt(pyfile)
  File "/share/HDA_DATA/.qpkg/pyload/module/plugins/crypter/ShareLinksBiz.py", line 38, in decrypt
    self.html = self.load(url)
  File "/share/HDA_DATA/.qpkg/pyload/module/plugins/internal/Plugin.py", line 337, in load
    if isinstance(self.COOKIES, list):
AttributeError: 'ShareLinksBiz' object has no attribute 'COOKIES'


FRAMESTACK:

Frame preprocessing in /share/HDA_DATA/.qpkg/pyload/module/plugins/internal/Hoster.py at line 184
                        self = <module.plugins.crypter.ShareLinksBiz.ShareLinksBiz object at 0x12de290>
                      thread = <DecrypterThread(Thread-14, started daemon)>

Frame process in /share/HDA_DATA/.qpkg/pyload/module/plugins/internal/Crypter.py at line 41
                      pyfile = PyFile 1: http://share-links.biz/_xbt5isn9f22jd@ShareLinksBiz
                        self = <module.plugins.crypter.ShareLinksBiz.ShareLinksBiz object at 0x12de290>

Frame decrypt in /share/HDA_DATA/.qpkg/pyload/module/plugins/crypter/ShareLinksBiz.py at line 38
                         url = u'http://www.share-links.biz/_xbt5isn9f22jd'
                      pyfile = PyFile 1: http://share-links.biz/_xbt5isn9f22jd@ShareLinksBiz
                        self = <module.plugins.crypter.ShareLinksBiz.ShareLinksBiz object at 0x12de290>

Frame load in /share/HDA_DATA/.qpkg/pyload/module/plugins/internal/Plugin.py at line 337
                      decode = True
                     cookies = True
                         val = False
                         get = {}
                         url = u'http://www.share-links.biz/_xbt5isn9f22jd'
                        self = <module.plugins.crypter.ShareLinksBiz.ShareLinksBiz object at 0x12de290>
                         req = <module.network.Browser.Browser object at 0x12b5228>
                   multipart = False
                         key = 'just_header'
                        post = {}
                         ref = True
                 just_header = False


PLUGIN OBJECT DUMP:

                     account = None
                    base_url = u'http://www.share-links.biz'
                     captcha = False
                 chunk_limit = 1
                     file_id = u'_xbt5isn9f22jd'
                        html = None
                        info = {}
                          js = <module.common.JsEngine.JsEngine instance at 0xf9eb20>
                  last_check = None
               last_download = ''
                     limitDL = 0
                     multiDL = True
                     package = <module.PyPackage.PyPackage instance at 0x12c66c0>
                    packages = []
                     premium = False
                      pyfile = PyFile 1: http://share-links.biz/_xbt5isn9f22jd@ShareLinksBiz
                      pyload = <__main__.Core object at 0xcd7690>
                         req = <module.network.Browser.Browser object at 0x12b5228>
             resume_download = False
                     retries = {}
                  retry_free = False
                      thread = <DecrypterThread(Thread-14, started daemon)>
                        urls = []
                        user = None
                  wait_until = 0
                     waiting = False
               wantReconnect = False

PYFILE OBJECT DUMP:

                       _size = 0
                       abort = False
                      active = False
                       error = "'ShareLinksBiz' object has no attribute 'COOKIES'"
                          id = 1
                        lock = <_RLock(None, 0)>
                           m = <module.database.FileDatabase.FileHandler instance at 0xd33300>
                 maxprogress = 100
                        name = u'http://share-links.biz/_xbt5isn9f22jd'
                       order = 0
                   packageid = 1
                      plugin = <module.plugins.crypter.ShareLinksBiz.ShareLinksBiz object at 0x12de290>
                 pluginclass = <class 'module.plugins.crypter.ShareLinksBiz.ShareLinksBiz'>
                pluginmodule = <module 'module.plugins.crypter.ShareLinksBiz' from '/share/HDA_DATA/.qpkg/pyload/module/plugins/crypter/ShareLinksBiz.py'>
                  pluginname = u'ShareLinksBiz'
                    progress = 0
                 reconnected = False
                        size = 0
                      status = 8
                  statusname = None
                         url = u'http://share-links.biz/_xbt5isn9f22jd'
                   waitUntil = 0


CONFIG:

{'desc': 'ShareLinksBiz',
 'outline': 'Share-Links.biz decrypter plugin',
 'subfolder_per_pack': {'desc': 'Create a subfolder for each package',
                        'type': 'bool',
                        'value': True},
 'use_subfolder': {'desc': 'Save package to subfolder',
                   'type': 'bool',
                   'value': True}}

**Comment by koroki** [comment]
Solve, thanks!

Finally I can download this, after 2 weeks of bugs
