### ISSUE TITLE
UploadedTo - Could not login user

### ISSUE THREAD

**Issue by DKeppi** [pyload/pyload#1676]
03.08.2015 05:42:38 WARNING   ACCOUNT UploadedTo: Could not login user `12345678` | 'UploadedTo' object has no attribute 'COOKIES'

**Comment by Shultz1895** [comment]
Exactly same issue here.

**Comment by c0rrre** [comment]
'ReCaptcha' object has no attribute 'COOKIES' 

Same with recaptcha

**Comment by mattionline** [comment]
'UploadedTo' object has no attribute 'COOKIES' 
HOOK LinkdecrypterCom: 'LinkdecrypterComHook' object has no attribute 'COOKIES' | Waiting 1 minute and retry 

same here

**Comment by NETHeader** [comment]
+1

**Comment by Giotrumpet** [comment]
Same here amigos.

**Comment by Stetanchi** [comment]
Same here with pyload and Uploaded.to premium account.
