### ISSUE TITLE
UpdateManager: Unable to retrieve server to get updates

### ISSUE THREAD

**Issue by zephura** [pyload/pyload#1677]
As the title explains, after last update (this morning) I cannot reach server anymore

Extract from log.txt

```
 UpdateManager: Unable to retrieve server to get updates
03.08.2015 00:00:49 INFO      HOOK UpdateManager: No new pyLoad version available
03.08.2015 00:00:49 INFO      HOOK UpdateManager: New version of plugin: [account] XFileSharingPro (v0.07 -> v0.08)
03.08.2015 00:00:49 ERROR     HOOK UpdateManager: Error updating plugin: XFileSharingPro.py | Version mismatch
03.08.2015 00:00:49 INFO      HOOK UpdateManager: No plugin updates available
03.08.2015 08:00:54 INFO      HOOK UpdateManager: No new pyLoad version available
03.08.2015 08:00:54 INFO      HOOK UpdateManager: New version of plugin: [account] FastshareCz (v0.08 -> v0.09)
03.08.2015 08:00:55 INFO      HOOK UpdateManager: New version of plugin: [account] FilecloudIo (v0.06 -> v0.07)
03.08.2015 08:00:55 INFO      HOOK UpdateManager: New version of plugin: [account] FourSharedCom (v0.06 -> v0.07)
03.08.2015 08:00:55 INFO      HOOK UpdateManager: New version of plugin: [account] Keep2ShareCc (v0.07 -> v0.08)
03.08.2015 08:00:56 INFO      HOOK UpdateManager: New version of plugin: [account] ShareonlineBiz (v0.38 -> v0.39)
03.08.2015 08:00:56 INFO      HOOK UpdateManager: New version of plugin: [account] SimplyPremiumCom (v0.07 -> v0.08)
03.08.2015 08:00:56 INFO      HOOK UpdateManager: New version of plugin: [account] TurbobitNet (v0.04 -> v0.05)
03.08.2015 08:00:57 INFO      HOOK UpdateManager: New version of plugin: [account] UploadedTo (v0.33 -> v0.34)
03.08.2015 08:00:57 INFO      HOOK UpdateManager: New version of plugin: [account] XFileSharingPro (v0.07 -> v0.08)
03.08.2015 08:00:57 ERROR     HOOK UpdateManager: Error updating plugin: XFileSharingPro.py | Version mismatch
03.08.2015 08:00:57 INFO      HOOK UpdateManager: New version of plugin: [hook] AntiStandby (v0.10 -> v0.11)
03.08.2015 08:00:58 INFO      HOOK UpdateManager: New version of plugin: [internal] Plugin (v0.27 -> v0.28)
03.08.2015 08:00:58 INFO      HOOK UpdateManager: New version of plugin: [internal] XFSAccount (v0.40 -> v0.41)
03.08.2015 08:00:58 INFO      HOOK UpdateManager: *** Plugins updated ***
03.08.2015 08:00:58 WARNING   HOOK UpdateManager: pyLoad restart required to reload the updated plugins
03.08.2015 08:01:01 WARNING   HOOK UpdateManager: Unable to retrieve server to get updates
03.08.2015 08:41:56 WARNING   HOOK UpdateManager: Unable to retrieve server to get updates
```

From my side :
- it is not a firewall issue as the server is answering (http://updatemanager.pyload.org/?v=0.4.9 is responding)
- it is not a DNS issue (my DNS server are up and answering)

```
# nslookup updatemanager.pyload.org
Server:         192.168.8.7
Address:        192.168.8.7#53

Non-authoritative answer:
updatemanager.pyload.org        canonical name = update.pyload.org.
update.pyload.org       canonical name = updatemanager-spyload.rhcloud.com.
updatemanager-spyload.rhcloud.com       canonical name = ex-std-node75.prod.rhcloud.com.
ex-std-node75.prod.rhcloud.com  canonical name = ec2-54-172-97-196.compute-1.amazonaws.com.
Name:   ec2-54-172-97-196.compute-1.amazonaws.com
Address: 54.172.97.196
```

I've try the "refresh method"
- delete userplugins directory
- delete account.conf and plugin.conf
- restart pyload
  without success (this is the last try in the log.txt)

Maybe a new update policy, maybe an overloaded server, maybe something else
Any suggestion is appreciated

**Comment by FuX-STV** [comment]
same here.. pyload cant update

**Comment by mattionline** [comment]
same here

**Comment by BigBart** [comment]
same here

**Comment by no-Legend** [comment]
same here

**Comment by stickell** [comment]
The server works like a charm, and the plugin has been updated last time 5 days ago so this must be a core issue.

**Comment by zephura** [comment]
stickel> 
I'm sure the server is pefectly working (I can reach it)
And as you said, I am sure it is not linked to the UpdateManager hook plugin
as it worked today 03.08.2015 08:00:58
and it doesn't work anymore 3 seconds later (03.08.2015 08:01:01)

That's why I precised I try to remove the "userplugins" directory in order to perform a "full update"

**Comment by mattionline** [comment]
Removing userplugins worked

**Comment by zephura** [comment]
mattionline>
- you stop pyload
- you remove userplugins directory
- you start pyload
(- you check the logs to see something)

that's all or something else?
because I already tried it twice, I must be missing something...

**Comment by mattionline** [comment]
Try to remove accounts.conf

**Comment by drmedramme** [comment]
Updates are not working for me at the moment with the current version of the UpdateManager.py hook plugin. When I replace it with this one it works:
https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py

**Comment by mattionline** [comment]
The files downloaded but now i have still the problem. Now it appeared again

**Comment by zephura** [comment]
Well...
since I modified Plugin.py around line 337... I can see the updates... well I can see that there are no new update, which is strictly right.
:warning I DON'T KNOW IF IT IS LINKED :warning

Here is what I modified : https://github.com/pyload/pyload/issues/1679#issuecomment-127265325

**Comment by GammaC0de** [comment]
Some more info:
'UpdateManager' object has no attribute 'COOKIES'
This is related to https://github.com/pyload/pyload/commit/e5ce0acf056dc96c40d5616ab6d2b82f998eefbe.


```
03.08.2015 20:18:59 WARNING   HOOK UpdateManager: Unable to retrieve server to get updates | 'UpdateManager' object has no attribute 'COOKIES'
```

**Comment by mattionline** [comment]
But when i delete the folder it updates from this source? Then it normally should work

**Comment by mattionline** [comment]
When i clone this project i still have this messages:

HOOK LinkdecrypterCom: 'LinkdecrypterComHook' object has no attribute 'COOKIES' | Waiting 1 minute and retry

**Comment by ccric** [comment]
At least it can't pull more bugs ;-P

**Comment by drmedramme** [comment]
Hehe, yes, I have deactivated the Updater now.

I got all working again with this fix:
https://github.com/pyload/pyload/pull/1685

**Comment by no-Legend** [comment]
Can anybody explain how i can fix my installation?

**Comment by mobo95** [comment]
I've fixed downloading pyload from github

**Comment by zephura** [comment]
@no-Legend 

see above : https://github.com/pyload/pyload/issues/1677#issuecomment-127336725

- stop pyload
- copy Plugin.py from here https://github.com/pyload/pyload/blob/e5ce0acf056dc96c40d5616ab6d2b82f998eefbe/module/plugins/internal/Plugin.py
into userplugins/internal directory
- remove Plugin.pyc (not mandatory)
- start pyload

If your desperate...
- stop pyload
- remove userplugins directory (or move this directory somewhere)
- backup and remove account.conf
- start pyload

it should launch Updatemanager from the install directory (instead of the conf dir) and catch the last updates.
it's like a software reset... (I think)

Perhaps I am missing something......

**Comment by Dybala93** [comment]
Fix works for update manager, and COOKIES error!
Thanks!

**Comment by I-RiX-I** [comment]
Not on my Windows Server unfortunately.

It gets even worse when trying to do a fresh install.

(also tried the plugin.py fix from the forums)

**Comment by godfuture** [comment]
I have removed the userplugins folder and now it seems to work for me.
Thx

**Comment by Sporrdig** [comment]
Yes thanks

**Comment by b0m0x** [comment]
i can confirm that  the userplugins removal fixes the issue

**Comment by fthiesse** [comment]
Same issue here, removing userplugins, account and plugin.conf *does not* fix the issue for me. What does adding "plugin issue" mean anyway? Are the plugins written by someone else?

**Comment by dansoftware** [comment]
Here is the solution: https://github.com/pyload/pyload/issues/1679#issuecomment-127265325 It solved this issue and one more: https://github.com/pyload/pyload/issues/1691 Thanks to **zephura**.

**Comment by I-RiX-I** [comment]
That's all good and well,

I do however need someone to explain to me how I can get this to work on Windows. The Prebuilt package from 2011 isnt working with those fixes. Could someone be as kind as to repack/release a working version for win?

**Comment by gregus69** [comment]
dead for me too since 3 days
