### ISSUE TITLE
Premium Account Problems

### ISSUE THREAD

**Issue by mattionline** [pyload/pyload#1687]
Hi, before the logs all worked fine with no problems but then the download stucks and it throws me out to a free user. Here are the logs: Thanks in advance for your help

281	03.08.2015 22:55:37	INFO	ACCOUNT UploadedTo: Parsing account info for user `MYUSERNAME`...
282	03.08.2015 22:55:37	INFO	HOSTER UploadedTo[206]: Filesize: 79948 KiB, Traffic left for user MYUSERNAME: 3.491257778371e+11 KiB
283	03.08.2015 22:55:37	INFO	HOSTER UploadedTo[206]: Processing as premium download...
284	03.08.2015 22:55:37	INFO	HOSTER UploadedTo[206]: Downloading file...
285	03.08.2015 22:59:39	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
286	03.08.2015 22:59:41	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
287	03.08.2015 22:59:53	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
288	03.08.2015 23:00:40	INFO	Download starts: FILENAME.rar
289	03.08.2015 23:00:40	INFO	ACCOUNT UploadedTo: Relogin user `MYUSERNAME`...
290	03.08.2015 23:00:40	WARNING	ACCOUNT UploadedTo: Could not login user `MYUSERNAME` | 'password'
291	03.08.2015 23:00:40	INFO	HOSTER UploadedTo[206]: Updating file info...
292	03.08.2015 23:00:40	INFO	HOSTER UploadedTo[206]: File name: FILENAME.rar
293	03.08.2015 23:00:40	INFO	HOSTER UploadedTo[206]: File size: 72386424 bytes
294	03.08.2015 23:00:40	INFO	HOSTER UploadedTo[206]: File status: online
295	03.08.2015 23:00:40	INFO	HOSTER UploadedTo[206]: Processing as free download...
296	03.08.2015 23:00:42	INFO	Download starts: FILENAME.rar
297	03.08.2015 23:00:42	INFO	HOSTER UploadedTo[204]: Updating file info...
298	03.08.2015 23:00:42	INFO	HOSTER UploadedTo[204]: File name: FILENAME.rar
299	03.08.2015 23:00:42	INFO	HOSTER UploadedTo[204]: File size: 17597328 bytes
300	03.08.2015 23:00:42	INFO	HOSTER UploadedTo[204]: File status: online
301	03.08.2015 23:00:42	INFO	HOSTER UploadedTo[204]: Looking for direct download link...
302	03.08.2015 23:00:42	INFO	HOSTER UploadedTo[204]: Direct download link not found
303	03.08.2015 23:00:42	INFO	ACCOUNT UploadedTo: Parsing account info for user `MYUSERNAME`...
304	03.08.2015 23:00:42	INFO	HOSTER UploadedTo[204]: Filesize: 192304 KiB, Traffic left for user MYUSERNAME: 3.491257778371e+11 KiB
305	03.08.2015 23:00:42	INFO	HOSTER UploadedTo[204]: Processing as premium download...
306	03.08.2015 23:00:42	WARNING	HOSTER UploadedTo[204]: Premium download failed | Parse error: Premium download link not found | Plugin may be out of date
307	03.08.2015 23:00:42	INFO	Download restarted: FILENAME.rar | Fallback to free download
308	03.08.2015 23:00:42	INFO	Download starts: FILENAME.rar
309	03.08.2015 23:00:42	INFO	HOSTER UploadedTo[204]: Updating file info...

**Comment by mattionline** [comment]
I dont think that the plugin is out of date. I cloned the git today and i did a restart to look if the problem appears again. And it appeared again

**Comment by vuolter** [comment]
Fixed.
