### ISSUE TITLE
HOOK LinkdecrypterCom: 'LinkdecrypterComHook' object has no attribute 'COOKIES' 

### ISSUE THREAD

**Issue by marviobezerra** [pyload/pyload#1691]
03.08.2015 20:46:43	INFO	Free space: 6.48 TiB
630	03.08.2015 20:46:43	INFO	Activating Accounts...
631	03.08.2015 20:46:43	INFO	Activating Plugins...
632	03.08.2015 20:46:43	WARNING	HOOK AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
633	03.08.2015 20:46:43	WARNING	HOOK AntiStandby: Unable to change display power state | [Errno 2] No such file or directory
634	03.08.2015 20:46:43	INFO	HOOK XFileSharingPro: Handling any hoster I can!
635	03.08.2015 20:46:43	WARNING	HOOK UpdateManager: Unable to retrieve server to get updates
636	03.08.2015 20:46:43	INFO	HOOK XFileSharingPro: Handling any crypter I can!
637	03.08.2015 20:46:43	INFO	pyLoad is up and running
638	03.08.2015 20:46:45	INFO	HOOK LinkdecrypterCom: Reloading supported crypter list
639	03.08.2015 20:46:45	WARNING	HOOK LinkdecrypterCom: 'LinkdecrypterComHook' object has no attribute 'COOKIES' | Waiting 1 minute and retry
640	03.08.2015 20:46:53	INFO	HOOK ClickAndLoad: Proxy listening on 127.0.0.1:9666
641	03.08.2015 20:46:53	INFO	HOOK LinkdecrypterCom: Reloading supported crypter list
642	03.08.2015 20:46:53	WARNING	HOOK LinkdecrypterCom: 'LinkdecrypterComHook' object has no attribute 'COOKIES' | Waiting 1 minute and retry
643	03.08.2015 20:47:45	WARNING	HOOK LinkdecrypterCom: 'LinkdecrypterComHook' object has no attribute 'COOKIES' | Waiting 1 minute and retry
644	03.08.2015 20:47:53	WARNING	HOOK LinkdecrypterCom: 'LinkdecrypterComHook' object has no attribute 'COOKIES' | Waiting 1 minute and retry

**Comment by mobo95** [comment]
same here

**Comment by FRYYYYYY** [comment]
Same too

**Comment by Gutz-Pilz** [comment]
https://github.com/pyload/pyload/pull/1696/files

**Comment by drt1** [comment]
same here, adding COOKIES=False to acc. or crypter doesn't help

**Comment by marviobezerra** [comment]
Someone could fix this?

**Comment by mobo95** [comment]
This project looks died

**Comment by Velociraptor85** [comment]
was Fixed with internal/Plugin v0.30 in https://github.com/pyload/pyload/commit/e5ce0acf056dc96c40d5616ab6d2b82f998eefbe

**Comment by dansoftware** [comment]
Here is the solution: https://github.com/pyload/pyload/issues/1679#issuecomment-127265325 It solved this issue and one more: https://github.com/pyload/pyload/issues/1677 Thanks to **zephura**.
