### ISSUE TITLE
RapidGator No JSON object could be decoded

### ISSUE THREAD

**Issue by zhaobb** [pyload/pyload#1698]
Could not login to Rapidgator since around one week ago. Tried to remove the userplugins directory but UpdateManager cannot recreate them.

INFO	ACCOUNT RapidgatorNet: Login user `XXX@gmail.com`...
DEBUG	ACCOUNT RapidgatorNet: LOAD URL http://rapidgator.net/api/login | cookies=True | get={} | req=None | decode=True | multipart=False | post={'username': 'XXX@gmail.com', 'password': 'J@s0n1812'} | ref=True | just_header=False
ERROR	ACCOUNT RapidgatorNet: No JSON object could be decoded
WARNING	ACCOUNT RapidgatorNet: Could not login user `XXX@gmail.com` | Login handshake has failed
INFO	ACCOUNT RapidgatorNet: Parsing account info for user `XXX@gmail.com`..

**Comment by covertsa** [comment]
I have had the same issue for about a week now :(

**Comment by covertsa** [comment]
Anyone ?  let me know if i can help in any way or if there is a way to revert the plugin back a version ?

**Comment by covertsa** [comment]
Seems line 78 is different 
https://github.com/pyload/pyload/blob/8f17f875f6e28f73ddb10da59c6464bd04922222/module/plugins/accounts/RapidgatorNet.py (line 78 show as        self.fail()   )  )  while in the plugin v 11 it shows as self.login_fail()  not sure if that could be a issue.

**Comment by fayf** [comment]
In ```RapidgatorNet.py```, make these changes:

line 33:
```html = self.load(urlparse.urljoin(self.API_URL, "info")```
change to:
```html = self.load(urlparse.urljoin(self.API_URL, "user/info")```

line 61:
```html = self.load(urlparse.urljoin(self.API_URL, "login"),```
change to:
```html = self.load(urlparse.urljoin(self.API_URL, "user/login"),```
