### ISSUE TITLE
ACCOUNT UploadedTo: Could not login user

### ISSUE THREAD

**Issue by scrimpy** [pyload/pyload#1699]
378	04.08.2015 19:29:09	WARNING	ACCOUNT UploadedTo: Could not login user `` | 'password'
377	04.08.2015 19:29:09	INFO	ACCOUNT UploadedTo: Relogin user ``...
376	04.08.2015 19:29:09	DEBUG	ACCOUNT UploadedTo: Reached login timeout for

**Comment by DomiStyle** [comment]
Same issue.
The first few downloads work without issue but the account will show up as not valid after they finished and switch to free account.

**Comment by scrimpy** [comment]
Did you download the newest github version, deleted userscripts directory and accounts.conf?

**Comment by scrimpy** [comment]
youre right, that isnt fixed. after stop and start the error came back.

**Comment by scrimpy** [comment]
theres no debug output.

**Comment by DomiStyle** [comment]
Yes, tried with a fresh install.
No debug output, the state just switches to not valid after the error you posted.

**Comment by scrimpy** [comment]
Yep, a restart helped me in this case.

**Comment by DomiStyle** [comment]
That's not a permanent solution though.
I can't restart every time 5 parts are finished. :)

**Comment by scrimpy** [comment]
Thats right.

**Comment by wastez** [comment]
This happens also with shareonline after 10 minutes.

**Comment by wastez** [comment]
https://github.com/pyload/pyload/issues/1692

**Comment by Stetanchi** [comment]
Can confirm this issue, do have the same behavour here, with lates git clone.

**Comment by GammaC0de** [comment]
should be fixed with #1705, please confirm

**Comment by Shultz1895** [comment]
Yes, the first batch gets downloaded, and then relogin fails  (Uploaded.to).

Just got myself a friend's backup of userplugin directory from two weeks ago, switched off UpdateManager and everything works splendid.
It's a shame there is no official download source for working userplugins (aren't we in "stable" branch?).

Will have a look here in september; hoping pyload will work by then...

**Comment by Shultz1895** [comment]
Seems to work for me; third batch is already downloading. Downloaded files are complete and usable.
Thank you for your good work!

**Comment by GammaC0de** [comment]
@vuolter / @scrimpy please close this issue.
