### ISSUE TITLE
global name 'set_cookie' is not defined

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1700]
after latest update i get this for every file:

611	04.08.2015 19:34:06	INFO	Download starts: Hawaii.Five-0.1x04.L.Evaso.iTaEng.WEBDLMux-DarkSideMux.part1.rar
612	04.08.2015 19:34:06	WARNING	Download failed: Hawaii.Five-0.1x04.L.Evaso.iTaEng.WEBDLMux-DarkSideMux.part1.rar | global name 'set_cookie' is not defined

**Comment by zephura** [comment]
mobo95 has found a fix :
https://github.com/pyload/pyload/commit/2cf928db10224b5327f918dceaa13273753620ac#commitcomment-12522848
