### ISSUE TITLE
convertDecimalPrefix error in UlozTo.py

### ISSUE THREAD

**Issue by janpal** [pyload/pyload#1703]
Hi all,

removal of camelCase apparently caused bug in the UlozTo.py file.
error from log looks like this: 
04.08.2015 20:50:47	ERROR	Error importing UlozTo: name 'convertDecimalPrefix' is not defined

convertDecimalPrefix has been changed to convert_decimal_prefix. Unfortunately, you can still find in the code reference to convertDecimalPrefix

Best,...

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/f80576bd8c809932dd9f62483402ec18532699b2

**Comment by janpal** [comment]
Thanks :-)
