### ISSUE TITLE
ShareonlineBiz takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by acidburn78** [pyload/pyload#1707]
04.08.2015 22:26:50	WARNING	Download failed: tvp-newgirl-s04e18-720p.part5.rar | fail() takes exactly 2 arguments (3 given)
637

**Comment by vuolter** [comment]
Debug log please.

**Comment by acidburn78** [comment]
pyLoad 0.4.9 Debug Report of ShareonlineBiz 0.55

TRACEBACK:
 Traceback (most recent call last):
  File "/volume2/@appstore/pyload/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/volume2/@appstore/pyload/var/config/userplugins/internal/Hoster.py", line 184, in preprocessing
    return self.process(self.pyfile)
  File "/volume2/@appstore/pyload/var/config/userplugins/internal/SimpleHoster.py", line 257, in process
    self.prepare()
  File "/volume2/@appstore/pyload/var/config/userplugins/internal/SimpleHoster.py", line 213, in prepare
    self.restart(nopremium=True)
  File "/volume2/@appstore/pyload/var/config/userplugins/internal/Hoster.py", line 335, in restart
    self.fail(reason, _("Download was already free"))
TypeError: fail() takes exactly 2 arguments (3 given)


FRAMESTACK:

Frame preprocessing in /volume2/@appstore/pyload/var/config/userplugins/internal/Hoster.py at line 184
                        self = <userplugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0xd14c90>
                      thread = <DownloadThread(Thread-2, started daemon 1103098992)>

Frame process in /volume2/@appstore/pyload/var/config/userplugins/internal/SimpleHoster.py at line 303
                      pyfile = PyFile 156: tvp-newgirl-s04e18-720p.part8.rar@ShareonlineBiz
                        self = <userplugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0xd14c90>

Frame prepare in /volume2/@appstore/pyload/var/config/userplugins/internal/SimpleHoster.py at line 213
                        self = <userplugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0xd14c90>

Frame restart in /volume2/@appstore/pyload/var/config/userplugins/internal/Hoster.py at line 335
                   nopremium = True
                      reason = u'Fallback to free download'
                        self = <userplugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0xd14c90>


PLUGIN OBJECT DUMP:

                  CHECK_FILE = True
               CHECK_TRAFFIC = True
                     COOKIES = True
                 DIRECT_LINK = None
                 DISPOSITION = True
               ERROR_PATTERN = '<p class="b">Information:</p>\\s*<div>\\s*<strong>(.*?)</strong>'
                 FILE_ERRORS = [('Html error',
  '\\A(?:\\s*<.+>)?((?:[\\w\\s]*(?:[Ee]rror|ERROR)\\s*\\:?)?\\s*\\d{3})(?:\\Z|\\s+)'),
 ('Request error', '([Aa]n error occured while processing your request)'),
 ('Html file', '\\A\\s*<!DOCTYPE html')]
                LEECH_HOSTER = False
                LINK_PATTERN = None
               LOGIN_ACCOUNT = False
               LOGIN_PREMIUM = False
           NAME_REPLACEMENTS = [('&#?\\w+;', <function fixup at 0x1655f0>)]
               RECAPTCHA_KEY = '6LdatrsSAAAAAHZrB70txiV5p-8Iv8BtVxlTtjKX'
           SIZE_REPLACEMENTS = []
               TEXT_ENCODING = True
            URL_REPLACEMENTS = [('https?://(?:www\\.)?(share-online\\.biz|egoshare\\.com)/(download\\.php\\?id=|dl/)(?P<ID>\\w+).*',
  'http://www.share-online.biz/dl/\\g<ID>')]
                     account = False
                     captcha = <userplugins.internal.Captcha.Captcha object at 0xd14c30>
                 chunk_limit = 1
                   direct_dl = False
                        html = ''
                        info = {}
                          js = <module.common.JsEngine.JsEngine instance at 0x52e530>
                  last_check = None
               last_download = ''
                    leech_dl = False
                     limitDL = 0
                        link = ''
                     multiDL = False
                     premium = False
                      pyfile = PyFile 156: tvp-newgirl-s04e18-720p.part8.rar@ShareonlineBiz
                      pyload = <__main__.Core object at 0x245c10>
                         req = <module.network.Browser.Browser object at 0x82a7d8>
             resume_download = False
                     retries = {}
                  retry_free = False
                      thread = <DownloadThread(Thread-2, started daemon 1103098992)>
                        user = None
                  wait_until = 0
                     waiting = False
               wantReconnect = False

PYFILE OBJECT DUMP:

                       _size = 58946309
                       abort = False
                      active = False
                       error = 'fail() takes exactly 2 arguments (3 given)'
                          id = 156
                        lock = <_RLock owner=None count=0>
                           m = <module.database.FileDatabase.FileHandler instance at 0x2513c8>
                 maxprogress = 100
                        name = u'tvp-newgirl-s04e18-720p.part8.rar'
                       order = 7
                   packageid = 18
                      plugin = <userplugins.hoster.ShareonlineBiz.ShareonlineBiz object at 0xd14c90>
                 pluginclass = <class 'userplugins.hoster.ShareonlineBiz.ShareonlineBiz'>
                pluginmodule = <module 'userplugins.hoster.ShareonlineBiz' from '/volume2/@appstore/pyload/var/config/userplugins/hoster/ShareonlineBiz.pyc'>
                  pluginname = u'ShareonlineBiz'
                    progress = 0
                 reconnected = False
                        size = 58946309
                      status = 8
                  statusname = None
                         url = u'http://www.share-online.biz/dl/Y4CCMKSN5O'
                   waitUntil = 0


CONFIG:

{'desc': 'ShareonlineBiz',
 'outline': 'Shareonline.biz hoster plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': False}}
