### ISSUE TITLE
LinkCryptWs doesnt work anymore

### ISSUE THREAD

**Issue by Xaviius** [pyload/pyload#1710]
Log:
700	05.08.2015 01:11:33	INFO	HOOK LinkdecrypterCom: Reloading supported crypter list
701	05.08.2015 01:11:33	INFO	HOOK LinkdecrypterCom: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
702	05.08.2015 01:11:41	INFO	HOOK ClickAndLoad: Proxy listening on 0.0.0.0:9666
703	05.08.2015 01:11:41	INFO	HOOK LinkdecrypterCom: Reloading supported crypter list
704	05.08.2015 01:11:41	INFO	HOOK LinkdecrypterCom: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
705	05.08.2015 01:12:13	INFO	Added package add_file containing 0 links
706	05.08.2015 01:13:30	INFO	Added package Linkcrypt.ws // Breaking Bad 720p S01-S05 containing 1 links
707	05.08.2015 01:13:31	INFO	Decrypting starts: http://linkcrypt.ws/container/ZHYHwr5eiT4th24sO8HyBsoNc2S4QGDiretENHpnXRSG2scHFiGuGXpATF6z81J7
708	05.08.2015 01:13:31	ERROR	CRYPTER LinkCryptWs[1]: Unable to decrypt CNL links (JS Error) try to get over links
709	05.08.2015 01:13:31	ERROR	Decrypting failed: http://linkcrypt.ws/container/ZHYHwr5eiT4th24sO8HyBsoNc2S4QGDiretENHpnXRSG2scHFiGuGXpATF6z81J7 | Decrypt error: No link grabbed | Plugin may be out of date
710	05.08.2015 01:13:51	INFO	Decrypting starts: http://linkcrypt.ws/container/ZHYHwr5eiT4th24sO8HyBsoNc2S4QGDiretENHpnXRSG2scHFiGuGXpATF6z81J7
711	05.08.2015 01:13:51	ERROR	CRYPTER LinkCryptWs[1]: Unable to decrypt CNL links (JS Error) try to get over links
712	05.08.2015 01:13:51	ERROR	Decrypting failed: http://linkcrypt.ws/container/ZHYHwr5eiT4th24sO8HyBsoNc2S4QGDiretENHpnXRSG2scHFiGuGXpATF6z81J7 | Decrypt error: No link grabbed | Plugin may be out of date

If anyone have an idea... already trying to get pyload work since 5 hours...

Thanks
Xaviius

**Comment by snickers2k** [comment]
same here

'bool' object has no attribute 'decrypt' 

pyLoad 0.4.9 Debug Report of LinkCryptWs 0.10 

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 184, in preprocessing
    return self.process(self.pyfile)
  File "/usr/share/pyload/module/plugins/internal/Crypter.py", line 41, in process
    self.decrypt(pyfile)
  File "/usr/share/pyload/module/plugins/crypter/LinkCryptWs.py", line 64, in decrypt
    self.unlock_captcha_protection()
  File "/usr/share/pyload/module/plugins/crypter/LinkCryptWs.py", line 136, in unlock_captcha_protection
    captcha_code = self.captcha.decrypt(captcha_url, input_type="gif", output_type='positional')
AttributeError: 'bool' object has no attribute 'decrypt'
 

FRAMESTACK:

Frame preprocessing in /usr/share/pyload/module/plugins/internal/Hoster.py at line 184
	                self = <module.plugins.crypter.LinkCryptWs.LinkCryptWs object at 0x7f6a400a7dd0>
	              thread = <DecrypterThread(Thread-23, started daemon 140093411014400)>

Frame process in /usr/share/pyload/module/plugins/internal/Crypter.py at line 41
	              pyfile = PyFile 693: http://linkcrypt.ws/dir/8f67e8it658rb1m@LinkCryptWs
	                self = <module.plugins.crypter.LinkCryptWs.LinkCryptWs object at 0x7f6a400a7dd0>

Frame decrypt in /usr/share/pyload/module/plugins/crypter/LinkCryptWs.py at line 64
	              pyfile = PyFile 693: http://linkcrypt.ws/dir/8f67e8it658rb1m@LinkCryptWs
	                self = <module.plugins.crypter.LinkCryptWs.LinkCryptWs object at 0x7f6a400a7dd0>

Frame unlock_captcha_protection in /usr/share/pyload/module/plugins/crypter/LinkCryptWs.py at line 136
	                self = <module.plugins.crypter.LinkCryptWs.LinkCryptWs object at 0x7f6a400a7dd0>
	         captcha_url = u'http://linkcrypt.ws/textx.html?secid=id=&id='


PLUGIN OBJECT DUMP: 

	         CRYPTED_KEY = 'crypted'
	              JK_KEY = 'jk'
	             account = None
	             captcha = True
	         chunk_limit = 1
	              fileid = u'8f67e8it658rb1m'
	                html = u'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n<html lang="de" xml:lang="de" xmlns="http://www.w3.org/1999/xhtml">\n<head>\n        <meta name="verify-v1" content="hcWYJNcFiUqdf0QG384HG8koVKLLpLcNuoHcZ1lLcJk=" />\n        <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" >\n        <meta http-equiv="Content-Language" content="de">\n        <meta name="keywords" content="Links verwalten, status check, schnell, virtuelle ordner, folder service,DLC, jdownloader, Container Files,kostenlos">\n        <meta name="description" content="">\n        <meta name="page-topic" content="Sicherheit,Ordnerservice,Dienst">\n        <meta name="audience" content="Alle">\n        <meta name="language" content="deutsch, de">\n        <meta name="robots" content="index,follow,noodp">\n        <meta name="copyright" content="LinkCrypt.ws" />\n        <meta name="title" content="Linkcrypt.ws // Kill.the.Messenger.2014.German.DTS.DL.720p.BluRay.x264-EXQUiSiTE" />\n\t\t<link rel="shortcut icon" href="http://dc.linkcrypt.ws//favicon.ico" />\n        <link href="http://dc.linkcrypt.ws/css/V4style.css" rel="stylesheet" type="text/css" />\n        <meta name="Uploadstation" content="uploadstation.com-konsotec-220c77af02f8ad8561b150d93000ddff"/>\n\t\t<link rel="alternate" href="http://twitter.com/statuses/user_timeline/47130800.rss" title="Linkcrypt News @Twitter" type="application/rss+xml" />\n\t\t<title>Linkcrypt.ws // TextX</title>\n\t\t<script type= "text/javascript">/*<![CDATA[*/\n\t\t\t\t\t\t\t\t\t\t\t   \n\t\tfunction show_more () {\n\t\t$(\'#readmore\').hide(\'slow\');\n\t\t$(\'#readmorec\').show(\'slow\');\n\t\t}\n\t\t\n\t\tvar DOMAIN = "http://linkcrypt.ws/";\n\t\t/*]]>*/</script>\n\t\t<script type="text/javascript" src="http://dc.linkcrypt.ws/js/jquery.js"></script>\n        <script type="text/javascript" src="http://linkcrypt.ws/js/jquery.innerfade.js"></script>\n</head>\n <body>\n<div id="container">\n<iframe id=\'ae22a5ba\' style=\'position: absolute; margin-left: 777px; top: 185px;text-align:left;\' name=\'ae22a5ba\' src=\'http://oxs1.selsin.net/delivery/afr.php?zoneid=8&cb=INSERT_RANDOM_NUMBER_HERE\' frameborder=\'0\' scrolling=\'no\' width=\'160\' height=\'600\'><a href=\'http://oxs1.selsin.net/delivery/ck.php?n=add61932&cb=INSERT_RANDOM_NUMBER_HERE\' target=\'_blank\'><img src=\'http://oxs1.selsin.net/delivery/avw.php?zoneid=8&cb=INSERT_RANDOM_NUMBER_HERE&n=add61932\' border=\'0\' alt=\'\' /></a></iframe> <iframe id=\'a5dbdbd8\' style=\'position: absolute; margin-left: -165px; top: 185px;text-align:left;\' name=\'a5dbdbd8\' src=\'http://oxs1.selsin.net/delivery/afr.php?zoneid=7&cb=INSERT_RANDOM_NUMBER_HERE\' frameborder=\'0\' scrolling=\'no\' width=\'160\' height=\'600\'><a href=\'http://oxs1.selsin.net/delivery/ck.php?n=a997a89d&cb=INSERT_RANDOM_NUMBER_HERE\' target=\'_blank\'><img src=\'http://oxs1.selsin.net/delivery/avw.php?zoneid=7&cb=INSERT_RANDOM_NUMBER_HERE&n=a997a89d\' border=\'0\' alt=\'\' /></a></iframe> <a href="http://linkcrypt.ws/"><img src="http://dc.linkcrypt.ws/image/logo.png" style="position:absolute; top:50px;"/></a>\n\t<div id="head">\n\t\t<div id="head_login">\n       \t\t\t\t</div>\n  \t</div>\n  <div id="menu">\n  <img src="http://dc.linkcrypt.ws/image/menu_left.png" style="float:left; width:13px;" />\n  <div id="menu_bg" style="background-image:url(http://dc.linkcrypt.ws/image/menu_bg.png); float:left; height:57px; width:747px;">\n    <ul>\n  \t  <li><a href="http://linkcrypt.ws/">Home</a></li>\n\t  <li class="Trenner">\xa0</li>\n\t  <li><a href="http://twitter.com/Linkcrypt" target="_blank">News</a></li>\n\t  <li class="Trenner">\xa0</li>\n\t  <li><a href="http://linkcrypt.ws/info.html">Info</a></li>\n      <li class="Trenner">\xa0</li>\n\t  <li><a href="http://linkcrypt.ws/add/">Create</a></li>\n\t  <li class="Trenner">\xa0</li>\n\t  <li><a href="http://linkcrypt.ws/member/home">Member</a></li>\n\t  <li class="Trenner">\xa0</li>\n\t  <li><a href="http://the-lounge.org/board156-supported-sites/linkcrypt-support/" target="_blank">Forum</a></li>\n\t  <li class="Trenner">\xa0</li>\n\t  <li><a href="http://linkcrypt.ws/linkus.html">Link Us</a></li>\n\t  <li class="Trenner">\xa0</li>\n\t  \n    </ul>\n    </div>\n    <img src="http://dc.linkcrypt.ws/image/menu_right.png" style="float:left; width:13px;" />\n  </div>\n<noscript>\n\t<style type="text/css"></style>\n\t<div style=" width:751px;border-left:1px solid #BDBCBD;border-right:1px solid #BDBCBD;background-color:#FFF;padding-left:10px;padding-right:10px;">\n\t\t<center>\n\t\t\t<br />\n\t\t\t\t<b>\n\t\t\t\t\tBitte Aktivieren Sie Javascript!<br />\n\t\t\t\t\tSonst kann Linkcrypt.ws nicht richtig Funktionieren!<br />\n\t\t\t\t</b>\n\t\t\t<br />\n\t\t</center>\n\t</div>\n</noscript>\t\n  <div style="position: absolute; top: 0px; text-align: center; width: 773px;">\n    <center>\n     <div style="width:430px;background-color:#4B90BB;border:2px solid #D4D5D5;border-top:none;height:24px;display:none;">\n          <a href="http://the-lounge.org/board156-supported-sites/board441-linkcrypt-support/linkcrypt-news-information/51036-geplante-wartung-08-03-2015/" style="font-size:17px;color:#FFF;text-decoration:none;" target="_blank">Achtung: Erneute Wartungsarbeiten</a>\n          \n      </div>\n    </center>\n  </div>\n  <div id="debug">\n  <div id="content"><center>\n\t<br />\n<div style="display:none;">\n\t<div id="content"><center>\n<img src="http://linkcrypt.ws/image/Warning.png"/>\n<h1>Folder not avialable!</h1>\n</div>\n\t<img src="image/Warning.png"/>\n\t<input type="password" value="xxxxx" name="password" id="password" tabindex="2" onfocus="this.value=\'\';" />\n</div>\n\t <center><div id="9581004" style="width:470px; height:60px; overflow:hidden; border:1px solid #000; text-align:center;"><iframe id=\'a6f4d16c\' name=\'a6f4d16c\' src=\'http://oxs1.selsin.net/delivery/afr.php?zoneid=10&cb=INSERT_RANDOM_NUMBER_HERE\' frameborder=\'0\' scrolling=\'no\' width=\'468\' height=\'60\'><a href=\'http://oxs1.selsin.net/delivery/ck.php?n=a3189881&cb=INSERT_RANDOM_NUMBER_HERE\' target=\'_blank\'><img src=\'http://oxs1.selsin.net/delivery/avw.php?zoneid=10&cb=INSERT_RANDOM_NUMBER_HERE&n=a3189881\' border=\'0\' alt=\'\' /></a></iframe></div></center>\n    <br />\n\t<br />\n\t<br />\n\t<br />\n\t<form action="" method="post" id="captcha">\n\t\t\t\t      \t<input  type="image" style="cursor:crosshair;border:1px solid #000000;"src="http://linkcrypt.ws/textx.html?secid=id=&id=" alt=""><br />\n\t\t<b>Please click on the circle with the result</b>\n\t\t\t\t\t</form>\n\t<br />\n\t\n\t<br />\n    <center><div id="3559382" style="width:300px; height:250px; overflow:hidden; border:1px solid #000; text-align:center;"><iframe id=\'abf1d5b9\' name=\'abf1d5b9\' src=\'http://oxs1.selsin.net/delivery/afr.php?refresh=15&zoneid=9&cb=INSERT_RANDOM_NUMBER_HERE\' frameborder=\'0\' scrolling=\'no\' width=\'300\' height=\'250\'><a href=\'http://oxs1.selsin.net/delivery/ck.php?n=a99caf84&cb=INSERT_RANDOM_NUMBER_HERE\' target=\'_blank\'><img src=\'http://oxs1.selsin.net/delivery/avw.php?zoneid=9&cb=INSERT_RANDOM_NUMBER_HERE&n=a99caf84\' border=\'0\' alt=\'\' /></a></iframe> </div></center>\n\t<br />\n\t<br />\n\n\t<script type="text/javascript" src="http://www.selsin.net/lc-73563.js"></script>\n\n</center>\n\n<script type="text/javascript"></script>\n\t</div>\n\t</div>\n  <div id="Footer">\n\t<center><img src="http://dc.linkcrypt.ws/image/footer_c_lc.png" style="margin-top: 36px;"/></center>\n  </div>\n</div>\n<br />\n<div style="position:absolute;top:5px; right:0;"><a href="http://linkcrypt.ws/?language=en"><img src="http://dc.linkcrypt.ws/image/eng_icon.gif" /></a> <a href="http://linkcrypt.ws/?language=de"><img src="http://dc.linkcrypt.ws/image/ger_icon.gif" /></a>\xa0\xa0</div>\n<script type="text/javascript">\nvar gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");\ndocument.write(unescape("%3Cscript src=\'" + gaJsHost + "google-analytics.com/ga.js\' type=\'text/javascript\'%3E%3C/script%3E"));\n</script>\n<script type="text/javascript">\nvar pageTracker = _gat._getTracker("UA-4382347-1");\npageTracker._trackPageview();\n</script>\n\n</body>\n</html>\n\n'
	                info = {}
	                  js = <module.common.JsEngine.JsEngine instance at 0x7f6a50505200>
	          last_check = None
	       last_download = ''
	             limitDL = 0
	               links = []
	             multiDL = True
	            packages = []
	             premium = False
	              pyfile = PyFile 693: http://linkcrypt.ws/dir/8f67e8it658rb1m@LinkCryptWs
	              pyload = <__main__.Core object at 0x7f6a52e75ad0>
	                 req = <module.network.Browser.Browser object at 0x7f6a400c0940>
	     resume_download = False
	             retries = {}
	          retry_free = False
	             sources = ['cnl', 'web', 'dlc', 'rsdf', 'ccf']
	              thread = <DecrypterThread(Thread-23, started daemon 140093411014400)>
	                urls = []
	                user = None
	          wait_until = 0
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 0
	               abort = False
	              active = False
	               error = "'bool' object has no attribute 'decrypt'"
	                  id = 693
	                lock = <_RLock owner=None count=0>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x7f6a52e96998>
	         maxprogress = 100
	                name = u'http://linkcrypt.ws/dir/8f67e8it658rb1m'
	               order = 0
	           packageid = 146
	              plugin = <module.plugins.crypter.LinkCryptWs.LinkCryptWs object at 0x7f6a400a7dd0>
	         pluginclass = <class 'module.plugins.crypter.LinkCryptWs.LinkCryptWs'>
	        pluginmodule = <module 'module.plugins.crypter.LinkCryptWs' from '/usr/share/pyload/module/plugins/crypter/LinkCryptWs.py'>
	          pluginname = u'LinkCryptWs'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'http://linkcrypt.ws/dir/8f67e8it658rb1m'
	           waitUntil = 0

**Comment by BigBart** [comment]
Same here

**Comment by Velociraptor85** [comment]
Does this fix https://github.com/pyload/pyload/pull/2307/ help?

**Comment by sraedler** [comment]
this crypter works 

please close
