### ISSUE TITLE
share-links error

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#1711]
11	05.08.2015 04:00:19	ERROR	Decrypting failed: http://share-links.biz/_mu3m2bn40lu1 | 'NoneType' object has no attribute 'group'
12	05.08.2015 04:00:19	INFO	Debug Report written to debug_ShareLinksBiz_05-08-2015_04-00-19.zip
13	05.08.2015 04:00:21	INFO	Decrypting starts: http://share-links.biz/misc/captcha/captcha.html
14	05.08.2015 04:00:21	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
15	05.08.2015 04:00:21	DEBUG	CRYPTER ShareLinksBiz[24]: PROCESS URL http://share-links.biz/misc/captcha/captcha.html | PLUGIN VERSION 1.16
16	05.08.2015 04:00:21	DEBUG	CRYPTER ShareLinksBiz[24]: LOAD URL http://www.share-links.biz/misc | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
17	05.08.2015 04:00:21	ERROR	Decrypting failed: http://share-links.biz/misc/captcha/captcha.html | Bad server response: 403 Forbidden
18	05.08.2015 04:00:21	INFO	Debug Report written to debug_ShareLinksBiz_05-08-2015_04-00-21.zip

pyLoad 0.4.9 Debug Report of ShareLinksBiz 1.16 

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 184, in preprocessing
    return self.process(self.pyfile)
  File "/usr/share/pyload/module/plugins/internal/Crypter.py", line 41, in process
    self.decrypt(pyfile)
  File "/usr/share/pyload/module/plugins/crypter/ShareLinksBiz.py", line 38, in decrypt
    self.html = self.load(url)
  File "/usr/share/pyload/module/plugins/internal/Plugin.py", line 340, in load
    res = req.load(url, get, post, ref, bool(cookies), just_header, multipart, decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/usr/share/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 208, in load
    self.code = self.verifyHeader()
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 222, in verifyHeader
    raise BadHeader(code, self.getResponse())
BadHeader: Bad server response: 403 Forbidden
 

FRAMESTACK:

Frame preprocessing in /usr/share/pyload/module/plugins/internal/Hoster.py at line 184
	                self = <module.plugins.crypter.ShareLinksBiz.ShareLinksBiz object at 0x7f67f003b810>
	              thread = <DecrypterThread(Thread-37, started daemon 140083445364480)>

Frame process in /usr/share/pyload/module/plugins/internal/Crypter.py at line 41
	              pyfile = PyFile 24: http://share-links.biz/misc/captcha/captcha.html@ShareLinksBiz
	                self = <module.plugins.crypter.ShareLinksBiz.ShareLinksBiz object at 0x7f67f003b810>

Frame decrypt in /usr/share/pyload/module/plugins/crypter/ShareLinksBiz.py at line 38
	                 url = u'http://www.share-links.biz/misc'
	              pyfile = PyFile 24: http://share-links.biz/misc/captcha/captcha.html@ShareLinksBiz
	                self = <module.plugins.crypter.ShareLinksBiz.ShareLinksBiz object at 0x7f67f003b810>

Frame load in /usr/share/pyload/module/plugins/internal/Plugin.py at line 340
	             cookies = True
	                 val = False
	                 get = {}
	                 url = u'http://www.share-links.biz/misc'
	                self = <module.plugins.crypter.ShareLinksBiz.ShareLinksBiz object at 0x7f67f003b810>
	                 req = <module.network.Browser.Browser object at 0x7f67f0103390>
	              decode = True
	           multipart = False
	                 key = 'just_header'
	                post = {}
	                 ref = True
	         just_header = False

Frame load in /usr/share/pyload/module/network/Browser.py at line 97
	                self = <module.network.Browser.Browser object at 0x7f67f0103390>
	                args = (u'http://www.share-links.biz/misc', {}, {}, True, True, False, False, True)
	              kwargs = {}

Frame load in /usr/share/pyload/module/network/HTTPRequest.py at line 208
	             cookies = True
	                 get = {}
	                 url = u'http://www.share-links.biz/misc'
	                 rep = '<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor="white">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
	              decode = True
	             referer = True
	           multipart = False
	                post = {}
	                self = <module.network.HTTPRequest.HTTPRequest instance at 0x7f67f0060680>
	         just_header = False

Frame verifyHeader in /usr/share/pyload/module/network/HTTPRequest.py at line 222
	                self = <module.network.HTTPRequest.HTTPRequest instance at 0x7f67f0060680>
	                code = 403

PLUGIN OBJECT DUMP: 

	             account = None
	            base_url = u'http://www.share-links.biz'
	             captcha = False
	         chunk_limit = 1
	             file_id = u'misc'
	                html = None
	                info = {}
	                  js = <module.common.JsEngine.JsEngine instance at 0x7f6809ab6dd0>
	          last_check = None
	       last_download = ''
	             limitDL = 0
	             multiDL = True
	             package = <module.PyPackage.PyPackage instance at 0x7f67f00606c8>
	            packages = []
	             premium = False
	              pyfile = PyFile 24: http://share-links.biz/misc/captcha/captcha.html@ShareLinksBiz
	              pyload = <__main__.Core object at 0x7f680cbadad0>
	                 req = <module.network.Browser.Browser object at 0x7f67f0103390>
	     resume_download = False
	             retries = {}
	          retry_free = False
	              thread = <DecrypterThread(Thread-37, started daemon 140083445364480)>
	                urls = []
	                user = None
	          wait_until = 0
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 0
	               abort = False
	              active = False
	               error = 'Bad server response: 403 Forbidden'
	                  id = 24
	                lock = <_RLock owner=None count=0>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x7f680cbce998>
	         maxprogress = 100
	                name = u'http://share-links.biz/misc/captcha/captcha.html'
	               order = 1
	           packageid = 7
	              plugin = <module.plugins.crypter.ShareLinksBiz.ShareLinksBiz object at 0x7f67f003b810>
	         pluginclass = <class 'module.plugins.crypter.ShareLinksBiz.ShareLinksBiz'>
	        pluginmodule = <module 'module.plugins.crypter.ShareLinksBiz' from '/usr/share/pyload/module/plugins/crypter/ShareLinksBiz.pyc'>
	          pluginname = u'ShareLinksBiz'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'http://share-links.biz/misc/captcha/captcha.html'
	           waitUntil = 0

CONFIG: 

{'desc': 'ShareLinksBiz',
 'outline': 'Share-Links.biz decrypter plugin',
 'subfolder_per_pack': {'desc': 'Create a subfolder for each package',
                        'type': 'bool',
                        'value': True},
 'use_subfolder': {'desc': 'Save package to subfolder',
                   'type': 'bool',
                   'value': True}}

**Comment by sraedler** [comment]
share-links is working

please close
