### ISSUE TITLE
ShareonlineBiz Fallback not found

### ISSUE THREAD

**Issue by acidburn78** [pyload/pyload#1715]
05.08.2015 12:33:02	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
502	05.08.2015 12:33:02	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
503	05.08.2015 12:33:02	DEBUG	HOSTER ShareonlineBiz[53]: PROCESS URL http://www.share-online.biz/dl/P6MLNESN3AZ | PLUGIN VERSION 0.55
504	05.08.2015 12:33:02	DEBUG	HOSTER ShareonlineBiz[53]: Config option `fallback` not found, use default `True`
505	05.08.2015 12:33:02	WARNING	Download failed: euhd-homeland-ded-dl-7p-bd-x264-411.part04.rar | Fallback to free download | Download was already free
506	05.08.2015 12:33:02	INFO	HOOK UnSkipOnFail: Looking for skipped duplicates of: euhd-homeland-ded-dl-7p-bd-x264-411.part04.rar (pid:11)
507	05.08.2015 12:33:02	INFO	HOOK UnSkipOnFail: No duplicates found

**Comment by 1337sup3rh4x0r** [comment]
Propably connected to #1650 and #1477

**Comment by 1337sup3rh4x0r** [comment]
Did you resolve the issue? Or why is it closed. Please share your solution!

**Comment by acidburn78** [comment]
In shareonlineBiz i has deactivated the Option "use Premium it available"
after i activated the Option tue fallback works
Am 06.08.2015 08:21 schrieb "1337sup3rh4x0r" <notifications@github.com>:

**Comment by 1337sup3rh4x0r** [comment]
I'm not sure I understand what you mean. I disabled the "use Premium if available" option now. This leads to no file beeing downloaded anymore. With the option disabled, it at least downloaded the first file...

My log with the option disabled reads as follows:

    06.08.2015 11:58:55 INFO      Download starts: http://uploaded.net/file/sdzkjtrh/File1.rar
	06.08.2015 11:58:55 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
	06.08.2015 11:58:55 DEBUG     Redirected import module.plugins.accounts.UploadedTo -> userplugins.accounts.UploadedTo
	06.08.2015 11:58:55 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
	06.08.2015 11:58:55 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
	06.08.2015 11:58:55 DEBUG     HOSTER UploadedTo[10]: PROCESS URL http://uploaded.net/file/sdzkjtrh/File1.rar | PLUGIN VERSION 0.96
	06.08.2015 11:58:55 DEBUG     HOSTER UploadedTo[10]: Config option `fallback` not found, use default `True`
	06.08.2015 11:58:55 WARNING   Download failed: http://uploaded.net/file/sdzkjtrh/File1.rar | Fallback to free download | Download was already free
	06.08.2015 11:58:55 INFO      HOOK UnSkipOnFail: Looking for skipped duplicates of: http://uploaded.net/file/sdzkjtrh/File1.rar (pid:3)
	06.08.2015 11:58:55 INFO      HOOK UnSkipOnFail: No duplicates found
