### ISSUE TITLE
Parsing account info - Login flood problem

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1717]
<b>Every time, I have to change IP address because the host block it due to excessive logins</b>

On logs, i get this flood every time:

246	05.08.2015 16:28:19	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
247	05.08.2015 16:28:49	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
248	05.08.2015 16:29:19	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
249	05.08.2015 16:29:49	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
250	05.08.2015 16:30:21	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
251	05.08.2015 16:30:51	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
252	05.08.2015 16:31:21	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
253	05.08.2015 16:31:51	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
254	05.08.2015 16:32:21	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
255	05.08.2015 16:32:54	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
256	05.08.2015 16:33:24	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
257	05.08.2015 16:33:54	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
258	05.08.2015 16:34:24	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
259	05.08.2015 16:34:54	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
260	05.08.2015 16:35:26	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
261	05.08.2015 16:35:56	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
262	05.08.2015 16:36:26	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
263	05.08.2015 16:36:56	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
264	05.08.2015 16:37:26	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
265	05.08.2015 16:37:58	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
266	05.08.2015 16:38:28	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
267	05.08.2015 16:38:58	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
268	05.08.2015 16:39:28	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
269	05.08.2015 16:39:58	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
270	05.08.2015 16:40:30	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
271	05.08.2015 16:41:00	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
272	05.08.2015 16:41:30	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
273	05.08.2015 16:42:00	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
274	05.08.2015 16:42:30	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
275	05.08.2015 16:43:02	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
276	05.08.2015 16:43:32	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
277	05.08.2015 16:44:02	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...
278	05.08.2015 16:44:32	INFO	ACCOUNT EasybytezCom: Parsing account info for user `XXXX`...

**Comment by simonhoenegger** [comment]
I have the same problem.
Running a patched version of mationic (stable)

**Comment by vuolter** [comment]
Fixed.

**Comment by simonhoenegger** [comment]
not really.
```
788	04.10.2015 02:52:58	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
789	04.10.2015 02:53:00	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
790	04.10.2015 02:53:02	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
791	04.10.2015 02:53:04	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
792	04.10.2015 02:53:05	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
793	04.10.2015 02:53:07	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
794	04.10.2015 02:53:09	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
795	04.10.2015 02:53:11	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
796	04.10.2015 02:53:13	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
797	04.10.2015 02:53:16	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
798	04.10.2015 02:53:18	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
799	04.10.2015 02:53:20	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
800	04.10.2015 02:53:22	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
801	04.10.2015 02:53:24	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
802	04.10.2015 02:53:26	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
803	04.10.2015 02:53:29	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
804	04.10.2015 02:53:31	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
805	04.10.2015 02:53:33	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
806	04.10.2015 02:53:35	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
807	04.10.2015 02:53:38	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
808	04.10.2015 02:53:40	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
809	04.10.2015 02:53:42	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
810	04.10.2015 02:53:44	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
811	04.10.2015 02:53:46	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
812	04.10.2015 02:53:49	INFO	ACCOUNT UploadedTo: Grabbing account info for user `8669126`...
```

**Comment by simonhoenegger** [comment]
not really.
````
788	04.10.2015 02:52:58	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
789	04.10.2015 02:53:00	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
790	04.10.2015 02:53:02	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
791	04.10.2015 02:53:04	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
792	04.10.2015 02:53:05	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
793	04.10.2015 02:53:07	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
794	04.10.2015 02:53:09	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
795	04.10.2015 02:53:11	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
796	04.10.2015 02:53:13	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
797	04.10.2015 02:53:16	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
798	04.10.2015 02:53:18	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
799	04.10.2015 02:53:20	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
800	04.10.2015 02:53:22	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
801	04.10.2015 02:53:24	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
802	04.10.2015 02:53:26	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
803	04.10.2015 02:53:29	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
804	04.10.2015 02:53:31	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
805	04.10.2015 02:53:33	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
806	04.10.2015 02:53:35	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
807	04.10.2015 02:53:38	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
808	04.10.2015 02:53:40	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
809	04.10.2015 02:53:42	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
810	04.10.2015 02:53:44	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
811	04.10.2015 02:53:46	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
812	04.10.2015 02:53:49	INFO	ACCOUNT UploadedTo: Grabbing account info for user `XXX`...
```
