### ISSUE TITLE
HotFolder.py not working

### ISSUE THREAD

**Issue by Pavion** [pyload/pyload#1718]
I've got an issue with HotFolder not working anymore. Init OK but no periodical search anymore. 
The solution seems to be an extra line 32 in def init(self):

        self.init_periodical()

Works for me anyway. Could you please see into this? 

Thanks for your great tool! 
WBR Pavion

**Comment by It0w** [comment]
Hi

I add

```
self.init_periodical()
```
in HotFolder.py at line 32

and Hotfolder is working again 

Thanks for the workaround

**Comment by Pavion** [comment]
Thanks for confirming! I've added an pull request.
