### ISSUE TITLE
Config option `fallback` not found, use default `True`

### ISSUE THREAD

**Issue by scrimpy** [pyload/pyload#1722]
05.08.2015 19:41:32 WARNING HOSTER UploadedTo[8]: Premium download failed | No file downloaded
33  05.08.2015 19:41:32 DEBUG   HOSTER UploadedTo[8]: Config option `fallback` not found, use default `True`
32  05.08.2015 19:41:32 INFO    HOSTER UploadedTo[8]: Checking file...

**Comment by scrimpy** [comment]
in multiconfig setup only the first copy runs without errors
/usr/share/pyload & /root/.pyload runs
/usr/share/pyload2 & /root/.pyload2 bugs

**Comment by scrimpy** [comment]
no debug output is created.

**Comment by bistory** [comment]
Same problem with a regularly auto-updated Pyload...

**Comment by scrimpy** [comment]
ok yes, just checked that link, and both setups gave that error.

**Comment by scrimpy** [comment]
ok i think im change flexget config to use jdownloader now. have fun with this broken code that maybe will run in a year or two again. bye

**Comment by 1337sup3rh4x0r** [comment]
It is pretty disrespectful towards the people who maintain pyload in their free time when you say something like this.

**Comment by bistory** [comment]
+1

**Comment by 1337sup3rh4x0r** [comment]
I noticed that the source of SimpleHoster.py mentions two config options, one of them is fallback:

    __config__  = [("use_premium", "bool", "Use premium account if available"          , True),
                   ("fallback"   , "bool", "Fallback to free download if premium fails", True)]

In the config page of pyload for the uploadedTo plugin I can however only set the first. Does this maybe have something to do with this issue?

**Comment by GammaC0de** [comment]
@1337sup3rh4x0r this happens for `chk_filesize` config too:
```
Config option `chk_filesize` not found, use default `None`
```
The reason for this is because `PluginManager` deletes the config because "internals have no config":
[PluginManager.py#L156](https://github.com/pyload/pyload/blob/37f6aa40d0eccd36fa43468307cfacb5d59a749e/module/plugins/PluginManager.py#L156):
```python
                # internals have no config
                if folder == "internal":
                    self.core.config.deleteConfig(name)
                    continue
```
 `SimpleHoster` is indeed internal plugin therefor the config for `use_premium`, `fallback` and `chk_filesize` gets deleted.

This happens in v0.4.10 too (see [Plugin.py#L146](https://github.com/vuolter/pyload/blob/0.4.10/pyload/manager/Plugin.py#L146))

@vuolter for you consideration.

**Comment by joberreiter** [comment]
I've an additional question that may related to this behaviour:

Is this the reason why the config options `use_subfolder` and `subfolder_per_package` are already defined in many plugins?

If yes, how does one enable or disable the use of subfolder creation on a global level, without setting every plugin accordingly?
E.g. if one disable subfolders globally (Config/General/General/Create folder for each package = off) and all plugins have their default value `use_subfolder = True`, what is the resulting action? Subfolders or not?

I'm aware that this can't be compared to `chk_filesize`, `fallback`, or `use_premium` as those don't have their according global settings.

**Comment by GammaC0de** [comment]
@joberreiter Yes, you are right, this is why config options use_subfolder and subfolder_per_package are already defined in many plugins:
`use_subfolder` and `subfolder_per_package`  in `Crypter.py` and `SimpleCrypter.py` gets deleted too but are re-added in every crypter

Local config option `use_subfolder` overrides the global `folder_per_package`, so if it is `False` no folder will be created for this plugin regradless of `subfolder_per_package`  and `folder_per_package`.
If you set `use_subfolder` to `True`and `subfolder_per_package` to  `False`, the global `folder_per_package` config option is used.
So if either one of them is `True' and `use_subfolder` is `True` also, a folder will be created.

`use_subfolder` is present only in crypters..
