### ISSUE TITLE
Uploaded.to: Wrong status after download attempt

### ISSUE THREAD

**Issue by Shultz1895** [pyload/pyload#1724]
Pyload log says, file status is offline.
Pyload queue says "failed" instead of "offline".

P.S.: Is it correct that Pyload tries to download offline files twice, as premium and as free download?
Offline is offline, isn't it?

1      05.08.2015 21:58:40	INFO	Download starts: abcdefgh
2	05.08.2015 21:58:40	INFO	HOSTER UploadedTo[6585]: Updating file info...
3	05.08.2015 21:58:40	INFO	HOSTER UploadedTo[6585]: File name: abcdefgh
4	05.08.2015 21:58:40	INFO	HOSTER UploadedTo[6585]: File size: Unknown
5	05.08.2015 21:58:40	INFO	HOSTER UploadedTo[6585]: File status: offline
6	05.08.2015 21:58:40	WARNING	HOSTER UploadedTo[6585]: Premium download failed | offline
7	05.08.2015 21:58:40	INFO	Download restarted: abcdefgh | Fallback to free download
8	05.08.2015 21:58:40	INFO	Download starts: abcdefgh
9	05.08.2015 21:58:40	INFO	HOSTER UploadedTo[6585]: Updating file info...
10	05.08.2015 21:58:41	INFO	HOSTER UploadedTo[6585]: File name: abcdefgh
11	05.08.2015 21:58:41	INFO	HOSTER UploadedTo[6585]: File size: Unknown
12	05.08.2015 21:58:41	INFO	HOSTER UploadedTo[6585]: File status: offline
13	05.08.2015 21:58:41	WARNING	Download failed: abcdefgh | offline
14	05.08.2015 21:58:41	INFO	HOOK UnSkipOnFail: Looking for skipped duplicates of: abcdefgh (pid:20)
15	05.08.2015 21:58:41	INFO	HOOK UnSkipOnFail: No duplicates found

**Comment by Shultz1895** [comment]
Anybody alive?

How about putting up a plugin backup from mid july for download, as long as there are still numerous issues with nobody having the time to work on them?

**Comment by covertsa** [comment]
Agreed UL, and Rapidgator up and stopped around that time any way to revert the plugin versions ?

**Comment by vuolter** [comment]
Debug log please.

**Comment by sraedler** [comment]
I guess this is also not an actual issue

please close...
