### ISSUE TITLE
Size calculation error?

### ISSUE THREAD

**Issue by janpal** [pyload/pyload#1726]
Hi all,
i am getting following error when downloading from UlozTo:
05.08.2015 21:49:15	WARNING	Download failed: Rozpravkova jazda.part1 29 casti sk.rar | File size mismatch | Expected file size: 1800000000.0 | Downloaded file size: 1835008000

original download link:  http://ulozto.sk/xF8ry6W4/rozpravkova-jazda-part1-29-casti-sk-rar

unfortunatelly, file is being deleted automatically, so i can not check whether the file was ok.
I faced the same error for last 4 downloads from this site.

Thanks,

**Comment by LePastis** [comment]
Same as #1708. Check the issue to find solution

**Comment by janpal** [comment]
Does not work for me. Seems that the difference in size is ~35 MB. Bigger than a treshold in the code.

**Comment by janpal** [comment]
will follow up in #1708
