### ISSUE TITLE
Send2Trash not working 

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1727]
This is the error Message:
<pre><code>
ExtractArchive: Unable to move T.L.S.S02E08.G.D.H.x-idTV.rar to trash | str() takes at most 1 argument (2 given)
</code></pre>

**Comment by GammaC0de** [comment]
debug log please

**Comment by wastez** [comment]
Tried in debug mode (and not as deamon) but there is nothing more.
<pre><code>
06.08.2015 12:53:06 DEBUG     EXTRACTOR ExtractArchive: UnRar | unrar vb -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pserienjunkies.org -v /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/ZNT4P104.part3.rar
06.08.2015 12:53:06 DEBUG     HOOK ExtractArchive: Would delete: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/ZNT4P104.part3.rar, /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/ZNT4P104.part3.rar, /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/ZNT4P104.part2.rar, /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/ZNT4P104.part4.rar, /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/ZNT4P104.part6.rar, /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/ZNT4P104.part5.rar, /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/ZNT4P104.part1.rar
06.08.2015 12:53:06 INFO      HOOK ExtractArchive: Deleting 7 files
06.08.2015 12:53:06 WARNING   HOOK ExtractArchive: Unable to move ZNT4P104.part3.rar to trash | str() takes at most 1 argument (2 given)
06.08.2015 12:53:06 WARNING   HOOK ExtractArchive: Unable to move ZNT4P104.part3.rar to trash | str() takes at most 1 argument (2 given)
06.08.2015 12:53:06 WARNING   HOOK ExtractArchive: Unable to move ZNT4P104.part2.rar to trash | str() takes at most 1 argument (2 given)
06.08.2015 12:53:06 WARNING   HOOK ExtractArchive: Unable to move ZNT4P104.part4.rar to trash | str() takes at most 1 argument (2 given)
06.08.2015 12:53:06 WARNING   HOOK ExtractArchive: Unable to move ZNT4P104.part6.rar to trash | str() takes at most 1 argument (2 given)
06.08.2015 12:53:06 WARNING   HOOK ExtractArchive: Unable to move ZNT4P104.part5.rar to trash | str() takes at most 1 argument (2 given)
06.08.2015 12:53:06 WARNING   HOOK ExtractArchive: Unable to move ZNT4P104.part1.rar to trash | str() takes at most 1 argument (2 given)
06.08.2015 12:53:06 INFO      HOOK ExtractArchive: ZNT4P104.part3.rar | Extracting finished
06.08.2015 12:53:06 DEBUG     PyControlPush: Pushing notification to device 7066f49aa5ab8dd6e8f4a8d94c467f26792967e418ac28c049a27f03654214d5
06.08.2015 12:53:07 DEBUG     PyControlPush: Response: 
06.08.2015 12:53:07 DEBUG     PyControlPush: Pushing notification to device ad571b1b65c4bdde957793fc77f8d104e5465ff637ecb97f0b712c70fdfcf53a
06.08.2015 12:53:07 DEBUG     PyControlPush: Response: 
06.08.2015 12:53:07 DEBUG     All downloads finished
06.08.2015 12:53:07 DEBUG     HOOK ExtractArchive: Extracted files: [u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/Z.Nation.S01E04.Der.General.German.Dubbed.BDRip.x264-ITG/itg-zn-s01e04.mkv', u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/Z.Nation.S01E04.Der.General.German.Dubbed.BDRip.x264-ITG', u'/media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/Z.Nation.S01E04.Der.General.German.Dubbed.BDRip.x264-ITG/itg-zn-s01e04.nfo']
06.08.2015 12:54:37 DEBUG     Cleared Result cache
</code></pre>

**Comment by ologr** [comment]
I have the same error with PyLoad working under Raspbian.
Try to disable Send2Trash in the ExtractArchive plugin configuration.

**Comment by GammaC0de** [comment]
@wastez works for me too, please close this issue.

**Comment by lazlev** [comment]
I have the same errors on Arch and Windows 7, so I wouldn't close it yet...

**Comment by GammaC0de** [comment]
@lazlev please send debug log

**Comment by lazlev** [comment]
I guess it's a bug in send2trash, for linux it uses the function in plat_other.py and tries to convert the path variable to a String if it isn't one already.

    def send2trash(path):
        if not isinstance(path, str):
            path = str(path, sys.getfilesystemencoding())
    [...]

**Comment by GammaC0de** [comment]
@lazlev Yes you are right, please test this patch to `plat_other.py`:
```patch
--- plat_other.py.bad   2015-04-26 21:59:16.000000000 +0300
+++ plat_other.py       2015-08-08 01:45:46.152850725 +0300
@@ -132,8 +132,11 @@
     return os.lstat(path).st_dev

 def send2trash(path):
-    if not isinstance(path, str):
-        path = str(path, sys.getfilesystemencoding())
+    if not isinstance(path, basestring):
+    if type(path) is unicode:
+        path = path.encode(sys.getfilesystemencoding(), "replace")
+    else:
+        path = str(path)
     if not op.exists(path):
         raise OSError("File not found: %s" % path)
     # ...should check whether the user has the necessary permissions to delete

```

**Comment by lazlev** [comment]
Yes, with that fix it is at least moving the files to trash. Next thing to fix is #1637 ;)

**Comment by pnancke** [comment]
I got the same error as @wastez:
```
18.08.2015 18:28:23	INFO	HOOK ExtractArchive: Deleting 2 files
18.08.2015 18:28:23	WARNING	HOOK ExtractArchive: Unable to move test.part01.rar to trash | str() takes at most 1 argument (2 given) 
18.08.2015 18:28:23	WARNING	HOOK ExtractArchive: Unable to move test.part02.rar to trash | str() takes at most 1 argument (2 given) 
18.08.2015 18:28:23	INFO	HOOK ExtractArchive: test.part02.rar | Extracting finished 
```

But I can't find any `plat_other.py` file to do what @GammaC0de said. Where should it be?

**Comment by GammaC0de** [comment]
just do execute the command: ` sudo find / -name 'plat_other.py' 2>/dev/null`

**Comment by pnancke** [comment]
@GammaC0de this won't find anything on my machine. I had to install `Send2Trash` manually because my pyload installation didn't had it. Is this maybe the reason why I don't have this file?

**Comment by GammaC0de** [comment]
@pnancke  won't or didn't?


`Send2Trash` is not installed by default, everyone who wished to use the `Send2Trash` feature has to manually install it.
Anyway, this command *should* find `plat_other.py`.

**Comment by pnancke** [comment]
@GammaC0de it didn't found it. In which folder should that file be?

**Comment by GammaC0de** [comment]
for me (ubuntu 14) its on `/usr/local/lib/python2.7/dist-packages/send2trash/plat_other.py`

**Comment by pnancke** [comment]
In this folder are just these files:
```
easy-install.pth            setuptools-18.1-py2.7.egg
Send2Trash-1.3.0-py2.7.egg  setuptools.pth
```
I use Bananian Linux btw.

**Comment by GammaC0de** [comment]
Maybe try `sudo find / -iname "plat_other.py"`
Also, which version of python do you use? (`python -V`)
