### ISSUE TITLE
Download deleted because of file size mismatch still there

### ISSUE THREAD

**Issue by janpal** [pyload/pyload#1732]
hi all,
i would like to report this again (because the original was closed) to ephasize that issue is still there. my diff is 35MB so the file is delete. i have locally changed the treshold in SimpleHoster.py to 100 MB. After my change, the file is downloaded sucesfully and it is not corrupted. this is happenig for big files.. like 2 Gb being downloaded from uloz.to.
thanks

**Comment by bast69** [comment]
Hi, I've the same error that you when I want to download with UptoBox.

**Comment by GammaC0de** [comment]
File size is not checked anymore
