### ISSUE TITLE
'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by ShadowmanCZ** [pyload/pyload#1737]
Hello my Pyload stopped download files from Uloz.to
I reinstalled Pyload again from : https://github.com/pyload/pyload/archive/stable.zip

and donwloading still not working and there is problem some 'ascii' conversion>

log:

1	08.08.2015 08:52:52	INFO	Spoustim pyLoad 0.4.9
2	08.08.2015 08:52:52	INFO	Nastaven domovsky adresar: /home/pi/.pyload
3	08.08.2015 08:53:11	INFO	Aktivovane pluginy: AntiStandby, ClickAndLoad, ExternalScripts, ExtractArchive, LinkdecrypterComHook, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
4	08.08.2015 08:53:11	INFO	Deaktivovat pluginy: AlldebridComHook, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
5	08.08.2015 08:53:11	INFO	Cas stahovani: True
6	08.08.2015 08:53:13	INFO	Starting builtin webserver: 0.0.0.0:8000
7	08.08.2015 08:53:13	INFO	Free space: 5.55 GiB
8	08.08.2015 08:53:13	INFO	Activating Accounts...
9	08.08.2015 08:53:13	INFO	Activating Plugins...
10	08.08.2015 08:53:13	WARNING	HOOK AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
11	08.08.2015 08:53:13	INFO	HOOK XFileSharingPro: Handling any hoster I can!
12	08.08.2015 08:53:13	INFO	HOOK XFileSharingPro: Handling any crypter I can!
13	08.08.2015 08:53:13	INFO	pyLoad is up and running
14	08.08.2015 08:53:13	INFO	HOOK UpdateManager: No new pyLoad version available
15	08.08.2015 08:53:13	INFO	HOOK UpdateManager: No plugin updates available
16	08.08.2015 08:53:15	INFO	HOOK LinkdecrypterCom: Reloading supported crypter list
17	08.08.2015 08:53:16	INFO	HOOK LinkdecrypterCom: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
18	08.08.2015 08:53:23	INFO	HOOK ClickAndLoad: Proxy listening on 0.0.0.0:9666
19	08.08.2015 08:53:23	INFO	HOOK LinkdecrypterCom: Reloading supported crypter list
20	08.08.2015 08:53:24	INFO	HOOK LinkdecrypterCom: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
21	08.08.2015 08:58:15	INFO	Added package trida8A containing 8 links
22	08.08.2015 08:58:15	WARNING	Info Fetching for UlozTo failed | 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
23	08.08.2015 08:58:16	INFO	Download starts: http://uloz.to/xKZQoQX2/trida-8-a-8-cast-avi
24	08.08.2015 08:58:16	INFO	HOSTER UlozTo[1]: Updating file info...
25	08.08.2015 08:58:16	WARNING	Download failed: http://uloz.to/xKZQoQX2/trida-8-a-8-cast-avi | 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
26	08.08.2015 08:58:16	INFO	HOOK UnSkipOnFail: Looking for skipped duplicates of: http://uloz.to/xKZQoQX2/trida-8-a-8-cast-avi (pid:1)
27	08.08.2015 08:58:16	INFO	HOOK UnSkipOnFail: No duplicates found
28	08.08.2015 08:58:18	INFO	Download starts: http://uloz.to/xLBRapX2/trida-8-a-1-cast-avi
29	08.08.2015 08:58:18	INFO	HOSTER UlozTo[2]: Updating file info...
30	08.08.2015 08:58:18	WARNING	Download failed: http://uloz.to/xLBRapX2/trida-8-a-1-cast-avi | 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
31	08.08.2015 08:58:18	INFO	HOOK UnSkipOnFail: Looking for skipped duplicates of: http://uloz.to/xLBRapX2/trida-8-a-1-cast-avi (pid:1)
32	08.08.2015 08:58:18	INFO	HOOK UnSkipOnFail: No duplicates found
33	08.08.2015 08:58:20	INFO	Download starts: http://uloz.to/xmgzv4Za/trida-8-a-2-cast-avi
34	08.08.2015 08:58:20	INFO	HOSTER UlozTo[3]: Updating file info...

**Comment by janpal** [comment]
same here.
Info Fetching for UlozTo failed | 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)

@vuolter Please. start using different codelines stable/unstable code. I am happy to test but i also need a stable instance of download manager. Last weeks, it looks like somebody is trying to kill this project.

**Comment by milanhlavin** [comment]
I have the same error:

WARNING	Download failed: http://www.ulozto.cz/xfNzvzXT/vzkriseni-demona-2015-cz-dabing-avi | 'ascii' codec can't encode characters in position 3-5: ordinal not in range(128)
or 
WARNING   Download failed: http://www.ulozto.cz/xDLb3PrQ/novinka-2015-gunman-muz-na-odstrel-cz-dabing-avi | 'ascii' codec can't encode character u'\u017e' in position 22: ordinal not in range(128) 

Please repair this bug, thanks.

**Comment by nomad71** [comment]
I think you can fix this by changing line 178 in SimpleHoster.py to

```
                info['name'] = replace_patterns(info['pattern']['N'],
```
and line 376 in Hoster.py to 
```
        name = self.pyfile.name
```
It's just a temporary workaround - as usual with my suggestions ^^

**Comment by ShadowmanCZ** [comment]
nomad71 : yeah it works, tahnk you

**Comment by milanhlavin** [comment]
Hi, working now, thanks a lot!

**Comment by tonyno** [comment]
Thanx for inspiration, this fix worked for me:

SimpleHoster.py
```python
           if 'N' in info['pattern']:
                name = replace_patterns(info['pattern']['N'], cls.NAME_REPLACEMENTS)
                info['name'] = replace_patterns(info['pattern']['N'], cls.NAME_REPLACEMENTS) # fix
```

In download method in Hoster.py I commented out this line:
```python
        # self.pyfile.name = parse_name(self.pyfile.name)  
```

**Comment by teofilko** [comment]
@nomad71 , @tonyno tahanks a lot!
Working now.

**Comment by janpal** [comment]
i do not believe this is a plugin issue. 
in simplehoster.py there is a parse_name function call. parse_name is trying to decode url from download name. if the name contains national characters, decode throws exception

simplehoster.py:
if 'N' in info['pattern']:
name = replace_patterns(info['pattern']['N'], cls.NAME_REPLACEMENTS)
info['name'] = parse_name(name)

Plugin.py:
def parse_name(url):
url = urllib.unquote(url)
url = url.decode('unicode-escape')
