### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by macross5** [pyload/pyload#1753]
Got this errors on http://filecrypt.cc/ and http://share-links.biz.
The Realdebrid rename error on the rar-file-names i have aswell.

> 1651	14.08.2015 02:03:22	INFO	Debug Report written to debug_FilecryptCc_14-08-2015_02-03-22.zip
1650	14.08.2015 02:03:22	ERROR	Decrypting failed: http://filecrypt.cc/Container/2A467695AE.html | 'NoneType' object has no attribute 'group'
1649	14.08.2015 02:03:21	DEBUG	CRYPTER FilecryptCc[1586]: LOAD URL https://www.google.com/recaptcha/api2/anchor | cookies=True | get={'parent': u'http:///filecrypt.cc', 'hl': u'de', 'v': u'r20150804120649', 'rpctoken': 19761449, 'k': u'6LcrmP8SAAAAAKa2tsM9xcOAuKaUKRrkBamt_c6q', 'usegapi': '1', 'jsh': u'm;/_/scs/apps-static/_/js/k=oz.gapi.de.3kbIs0gRBGM.O/m=__features__/am=AQ/rt=j/d=1/t=zcms/rs=AGLTcCOzmPkTppBx3aRymSCOM6cnNBpSGA#id=IO_1439510601875', 'pfname': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1648	14.08.2015 02:03:21	DEBUG	CAPTCHA FilecryptCc[1586]: ReCaptcha | Rpc-token: 19761449
1647	14.08.2015 02:03:21	DEBUG	CAPTCHA FilecryptCc[1586]: ReCaptcha | Time: 1439510601875
1646	14.08.2015 02:03:21	DEBUG	CRYPTER FilecryptCc[1586]: LOAD URL http://www.google.com/recaptcha/api2/demo | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1645	14.08.2015 02:03:21	DEBUG	CAPTCHA FilecryptCc[1586]: ReCaptcha | API jsh-string: m;/_/scs/apps-static/_/js/k=oz.gapi.de.3kbIs0gRBGM.O/m=__features__/am=AQ/rt=j/d=1/t=zcms/rs=AGLTcCOzmPkTppBx3aRymSCOM6cnNBpSGA
1644	14.08.2015 02:03:21	DEBUG	CRYPTER FilecryptCc[1586]: LOAD URL https://apis.google.com/js/api.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1643	14.08.2015 02:03:21	DEBUG	CAPTCHA FilecryptCc[1586]: ReCaptcha | API language: de
1642	14.08.2015 02:03:21	DEBUG	CAPTCHA FilecryptCc[1586]: ReCaptcha | API version: r20150804120649
1641	14.08.2015 02:03:21	DEBUG	CRYPTER FilecryptCc[1586]: LOAD URL http://www.google.com/recaptcha/api.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1640	14.08.2015 02:03:21	DEBUG	CAPTCHA FilecryptCc[1586]: ReCaptcha | Key: 6LcrmP8SAAAAAKa2tsM9xcOAuKaUKRrkBamt_c6q
1639	14.08.2015 02:03:21	DEBUG	CRYPTER FilecryptCc[1586]: LOAD URL http://filecrypt.cc/Container/2A467695AE.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1638	14.08.2015 02:03:21	DEBUG	CRYPTER FilecryptCc[1586]: PROCESS URL http://filecrypt.cc/Container/2A467695AE.html | PLUGIN VERSION 0.18
1637	14.08.2015 02:03:21	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
1636	14.08.2015 02:03:21	INFO	Decrypting starts: http://filecrypt.cc/Container/2A467695AE.html

**Comment by joberreiter** [comment]
This error originates from bad coding style, as `self.base_url = "http://www.%s.biz" % re.match(self.__pattern__, url).group(1)` can be `None` if the pattern is wrong or `url` simple doesn't fit into.

**Comment by macross5** [comment]
Ty for your fix.

Now i got these Error on Filecrypt:

> 1017	14.08.2015 22:24:46	ERROR	Decrypting failed: http://filecrypt.cc/Container/2DE585F8C1.html | coercing to Unicode: need string or buffer, tuple found
1016	14.08.2015 22:24:42	DEBUG	CAPTCHA FilecryptCc[1569]: Captcha | LOAD URL http://filecrypt.cc/../captcha/circle.php?c=abc | cookies=False | get={} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
1015	14.08.2015 22:24:42	DEBUG	CRYPTER FilecryptCc[1569]: Captcha-URL: ../captcha/circle.php
1014	14.08.2015 22:24:42	DEBUG	CRYPTER FilecryptCc[1569]: LOAD URL http://filecrypt.cc/Container/2DE585F8C1.html | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1013	14.08.2015 22:24:42	DEBUG	CRYPTER FilecryptCc[1569]: PROCESS URL http://filecrypt.cc/Container/2DE585F8C1.html | PLUGIN VERSION 0.19
1012	14.08.2015 22:24:42	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
1011	14.08.2015 22:24:42	INFO	Decrypting starts: http://filecrypt.cc/Container/2DE585F8C1.html


and still these on sharelinkbiz

> 
1033	14.08.2015 22:26:43	INFO	Debug Report written to debug_ShareLinksBiz_14-08-2015_22-26-43.zip
1032	14.08.2015 22:26:43	ERROR	Decrypting failed: http://share-links.biz/_ka4f2tn1wyfc/dragon720p | 'NoneType' object has no attribute 'group'
1031	14.08.2015 22:26:43	DEBUG	CRYPTER ShareLinksBiz[1588]: Captcha map with [196] positions
1030	14.08.2015 22:26:43	DEBUG	CRYPTER ShareLinksBiz[1588]: Links are captcha protected
1029	14.08.2015 22:26:43	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/right_top_bottom.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1028	14.08.2015 22:26:43	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/right_top_bottom.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1027	14.08.2015 22:26:43	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/question_dark.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1026	14.08.2015 22:26:43	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/misc/exclamationmark_orange.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1025	14.08.2015 22:26:43	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/flags/de.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1024	14.08.2015 22:26:43	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/flags/en.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1023	14.08.2015 22:26:43	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/header/blank.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1022	14.08.2015 22:26:43	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/_ka4f2tn1wyfc | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
1021	14.08.2015 22:26:43	DEBUG	CRYPTER ShareLinksBiz[1588]: PROCESS URL http://share-links.biz/_ka4f2tn1wyfc/dragon720p | PLUGIN VERSION 1.16
1020	14.08.2015 22:26:43	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
1019	14.08.2015 22:26:43	INFO	Decrypting starts: http://share-links.biz/_ka4f2tn1wyfc/dragon720p

**Comment by joberreiter** [comment]
FilecryptCc:
The underlying issue is an error in the ReCaptcha-module, I'm not sure how to fix it properly.

ShareOnlineBiz:
Download 67864826ef26c831c9fa216b154917d48b045f72 and retry.

**Comment by macross5** [comment]
Now the crypter cant decrype it,

> 16.08.2015 22:32:22	ERROR	Decrypting failed: http://share-links.biz/_ka4f2tn1wyfc/dragon720p | 'bool' object has no attribute 'decrypt'
16.08.2015 22:32:22	DEBUG	CRYPTER ShareLinksBiz[1588]: Waiting user for correct position
16.08.2015 22:32:22	DEBUG	CRYPTER ShareLinksBiz[1588]: Captcha map with [130] positions
16.08.2015 22:32:22	DEBUG	CRYPTER ShareLinksBiz[1588]: Links are captcha protected
16.08.2015 22:32:22	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/right_top_bottom.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
16.08.2015 22:32:22	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/right_top_bottom.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
3493	16.08.2015 22:32:22	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/question_dark.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
16.08.2015 22:32:22	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/misc/exclamationmark_orange.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
16.08.2015 22:32:22	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/flags/de.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
16.08.2015 22:32:22	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/flags/en.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
16.08.2015 22:32:21	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/template/images/header/blank.gif | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
16.08.2015 22:32:21	DEBUG	CRYPTER ShareLinksBiz[1588]: LOAD URL http://www.share-links.biz/_ka4f2tn1wyfc | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
16.08.2015 22:32:21	DEBUG	CRYPTER ShareLinksBiz[1588]: PROCESS URL http://share-links.biz/_ka4f2tn1wyfc/dragon720p | PLUGIN VERSION 1.17
16.08.2015 22:32:21	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
16.08.2015 22:32:21	INFO	Decrypting starts: http://share-links.biz/_ka4f2tn1wyfc/dragon720p
