### ISSUE TITLE
LinkCryptWs - 'bool' object has no attribute 'decrypt'

### ISSUE THREAD

**Issue by macross5** [pyload/pyload#1756]
Again an error with an crypter...

> 2458	14.08.2015 23:06:35	INFO	Debug Report written to debug_LinkCryptWs_14-08-2015_23-06-35.zip
2457	14.08.2015 23:06:35	ERROR	Decrypting failed: http://linkcrypt.ws/dir/u9zwn9sbm6nscp1 | 'bool' object has no attribute 'decrypt'
2456	14.08.2015 23:06:35	DEBUG	CRYPTER LinkCryptWs[1570]: Links are captcha protected
2455	14.08.2015 23:06:35	DEBUG	CRYPTER LinkCryptWs[1570]: LOAD URL http://linkcrypt.ws/dir/u9zwn9sbm6nscp1 | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
2454	14.08.2015 23:06:35	DEBUG	CRYPTER LinkCryptWs[1570]: PROCESS URL http://linkcrypt.ws/dir/u9zwn9sbm6nscp1 | PLUGIN VERSION 0.10
2453	14.08.2015 23:06:35	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
2452	14.08.2015 23:06:35	INFO	Decrypting starts: http://linkcrypt.ws/dir/u9zwn9sbm6nscp1
2451	14.08.2015 23:06:35	DEBUG	Redirected import module.plugins.crypter.LinkCryptWs -> userplugins.crypter.LinkCryptWs

**Comment by Bambie42** [comment]
This https://gist.github.com/Bambie42/989aa620a14d783d2078 fixes the bool problem, but then the plugin always says the captcha is invalid... I think that is a cookie problem?

**Comment by macross5** [comment]
I will try it soon. Thx for your help.

**Comment by macross5** [comment]
you are right. now i cant decrype the captcha as you said.

**Comment by Bambie42** [comment]
Writing a simple decrypter with python-requests solve this issue, so i think this is pyload handling the cookies wrong?

**Comment by j4m** [comment]
I also think it depends on the cookie handling and that this is the reason for #1605 to fail too.

**Comment by ddbxx** [comment]
I used tcpdump today to debug the FileCryptCC plugin and can confirm the cookie handling problem. For getting the captcha image a new requestFactory instance is opened by the Captcha object and no coockie pass-through is implemented. I attached two diff files for FilecryptCC.py and Captcha.py

btw: the ref=True option does not working.

diff_Captcha.txt

53c53
<     def decrypt(self, url, get={}, post={}, ref=False, cookies=False, decode=False,
---
>     def decrypt(self, url, get={}, post={}, ref=False, cookies=False, decode=False, req=None,
55c55
<         img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=decode)
---
>         img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=decode, req=req)


diff_FilecryptCc.txt

34c34
<     CAPTCHA_PATTERN        = r'<img id="nc" src="(.+?)"'
---
>     CAPTCHA_PATTERN        = r'<img id="nc" src="../(.+?)"'
44a45,47
>         pyfile.url = pyfile.url.replace("https", "http")
>         
>         self.pyfile.url = pyfile.url
95,96c98,99
<             captcha_code = self.captcha.decrypt(urlparse.urljoin(self.base_url, m.group(1)),
<                                                 input_type="gif")
---
>             # captcha_code = self.captcha.decrypt(urlparse.urljoin(self.base_url, m.group(1)), cookies=True, ref=True, 
>                                                 # input_type="gif")
97a101,103
>             captcha_code = self.captcha.decrypt(urlparse.urljoin(self.base_url, m.group(1)), cookies=True, ref=True, 
>                                                 input_type="gif", req=self.req)
>                                                 
99c105
<                                            post={'recaptcha_response_field': captcha_code})
---
>                                            post={'recaptcha_response_field': captcha_code}, ref=True)
