### ISSUE TITLE
Catshare links

### ISSUE THREAD

**Issue by blacksad77** [pyload/pyload#1758]
This is catshare link, tha pyload 0.4.9 does not qualify as catshare: 
http://catshare.net/DOp0fsmIOQfQN0E/Spy.2015.PL.SUBBED.HC.HDRip.XviD-KiT.avi
http://catshare.net/5n9iIVHQecPDLzA/Spy.2015.PLSUBBED.HC.HDRip.XviD-KiT.avi
I made correction in catshare.py, from:
__pattern__ = r'http://(?:www\.)?catshare\.net/\w{16}'
to:
__pattern__ = r'http://(?:www\.)?catshare\.net/\w{15,16}'

And teh are working now, Additionally, files downloaded from Catshare have filesize differing from declared, 10 MB of tolerance is not enough. I have entered 100 MB, but i think this is too much, however files are downloading correctly.

**Comment by vuolter** [comment]
Thanks.
