### ISSUE TITLE
FilecryptCc "coercing to Unicode: need string or buffer, tuple found"

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#1775]
21.08.2015 01:43:58	INFO	CAPTCHA FilecryptCc[2650]: Captcha | Captcha result: 10
672	21.08.2015 01:43:58	ERROR	CAPTCHA FilecryptCc[2650]: Captcha | Invalid captcha
673	21.08.2015 01:44:15	INFO	CRYPTER FilecryptCc[2650]: WAIT 1 seconds
674	21.08.2015 01:44:15	INFO	CRYPTER FilecryptCc[2650]: RECONNECT disabled
675	21.08.2015 01:44:17	INFO	Retrying http://filecrypt.cc/Container/XXXXXXXXX.html
676	21.08.2015 01:44:17	INFO	Decrypting starts: http://filecrypt.cc/Container/XXXXXXXXX.html
678	21.08.2015 01:44:32	ERROR	Decrypting failed: http://filecrypt.cc/Container/XXXXXXXXX.html | coercing to Unicode: need string or buffer, tuple found

the files are up.. worked in browser

**Comment by macross5** [comment]
same here. Seems like only solvemedia captchas works.

**Comment by snickers2k** [comment]
another issue with FileCryptCC

27.08.2015 02:00:45	WARNING	CAPTCHA FilecryptCc[1570]: ReCaptcha | Key pattern not found
8	27.08.2015 02:00:45	INFO	CRYPTER FilecryptCc[1570]: No captcha found
9	27.08.2015 02:00:45	ERROR	Decrypting failed: http://filecrypt.cc/Container/XXXXXXX.html | Decrypt error: No link grabbed | Plugin may be out of date

**Comment by vuolter** [comment]
Please, check if still persists.
