### ISSUE TITLE
downloadPreparing event is called twice for every URL

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1777]
One call in [Hoster.py#L177](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Hoster.py#L177)
The other is in [PluginThread.py#L186](https://github.com/pyload/pyload/blob/stable/module/PluginThread.py#L186)

Can we remove it from  `Hoster.py` or this is intent?

**Comment by vuolter** [comment]
FIxed
