### ISSUE TITLE
ExtractArchive - ü,ä,ö,ß error

### ISSUE THREAD

**Issue by macross5** [pyload/pyload#1778]
Got these errors when i extract an rar file with "umlauts"
How can i fix it on set sevenzip or pyload that it would extract on utf8 or rename the ö to oe, ..., while extraction.
Thx for any help.

> ERROR HOOK ExtractArchive: sdFeatur.rar | Archive error | Cannot create /volume1/downloads/-extracted/Sido - Features (2015)/12. L?wenzahn (feat. Olexesh).mp3

**Comment by Burnout5151** [comment]
@Velociraptor85, @GammaC0de  : Can probably be closed as duplicate of #2286
