### ISSUE TITLE
reconnect with easybytez

### ISSUE THREAD

**Issue by davboc** [pyload/pyload#1780]
There is a way to enable reconnect for easybytez host? I have a working reconnect script and reconnect option enabled but the reconnection event doesn't work.

**Comment by davboc** [comment]
no solution for that? Someone can use reconnect function with this host?

**Comment by vuolter** [comment]
Working on...

**Comment by davboc** [comment]
Thanks for the answer, I can provide any log that you need

**Comment by davboc** [comment]
So no hope to solve this problem?

**Comment by vuolter** [comment]
Reconnect still not working?! O.O

**Comment by davboc** [comment]
No, the log still report:
INFO	HOSTER EasybytezCom[14]: RECONNECT disabled 
what can I do?

**Comment by vuolter** [comment]
Update the plugin! XD

**Comment by vuolter** [comment]
I mean your plugins are not up-to-date. You can force the update with this procedure: http://forum.pyload.org/viewtopic.php?f=7&t=4335

**Comment by davboc** [comment]
class EasybytezCom(XFSHoster):
    __name__    = "EasybytezCom"
    __type__    = "hoster"
    __version__ = "0.24"
    __status__  = "testing"
version 0.24 is the same of the one present on github

**Comment by vuolter** [comment]
Do you check XFSHoster and SimpleHoster and Hoster and Base and Plugin too? :p

**Comment by davboc** [comment]
all done, but now I can't start download cause this error:

ERROR	pycurl error 6: Couldn't resolve host 'http'

**Comment by vuolter** [comment]
See: https://github.com/pyload/pyload/issues/1917

**Comment by davboc** [comment]
sorry but the example is not clear for me, under the fixurl function what lines I must replace?  Whit whom?

And after that, I must recompile file plugin.py?

**Comment by vuolter** [comment]
Please wait a bit for a solution... I'm working on.

**Comment by vuolter** [comment]
Try now.

**Comment by davboc** [comment]
I must repeat force update?

Il 02 ottobre 2015 02:39:49 CEST, Walter Purcaro <notifications@github.com> ha scritto:
>Try now.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pyload/pyload/issues/1780#issuecomment-144886296

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by vuolter** [comment]
Check if you have any UpdateManager entry in the log. If true, you not need to force the update. ;)

**Comment by davboc** [comment]
First of all thanks for your kindness. 
Now the download works, in the log doesn't appear "reconnect disabled" but in debug mode I see "reconnect not required":

52802.10.2015 10:30:23INFOADDON UpdateManager: New version of plugin: [account] HellshareCz (v0.20 -> v0.21)52702.10.2015 10:30:23INFOHOSTER EasybytezCom[31]: Waiting 48636 seconds...52602.10.2015 10:30:23DEBUGHOSTER EasybytezCom[31]: RECONNECT not required | Previous wantReconnect: True52502.10.2015 10:30:23DEBUGHOSTER EasybytezCom[31]: WAIT set to 48636 seconds | Previous waitUntil: 0.00000052402.10.2015 10:30:23WARNINGHOSTER EasybytezCom[31]: You have reached the download-limit: 600 Mb for last 1 days52302.10.2015 10:30:23DEBUGHOSTER EasybytezCom[31]: Getting download link #2

But obviously there is something wrong. How can I solve this? 

Thanks again 

Il 02 ottobre 2015 03:37:51 CEST, Walter Purcaro <notifications@github.com> ha scritto:

**Comment by davboc** [comment]
Restated all, now reconnect is required but:

 10:40:01ERRORReconnect Failed: after_reconnect() takes exactly 2 arguments (3 given)

:(


Il 02 ottobre 2015 03:37:51 CEST, Walter Purcaro <notifications@github.com> ha scritto:

**Comment by vuolter** [comment]
Checking...

**Comment by vuolter** [comment]
Retry now, please.

**Comment by davboc** [comment]
I restarted again and now download works, but I wait for next reconnect event to see if reconnect works without any restart. 

Another little problem: I activated the "restart failed" plugin but it doesn't works, why? 

Thanks again mate 

Il 02 ottobre 2015 11:01:10 CEST, Walter Purcaro <notifications@github.com> ha scritto:

**Comment by vuolter** [comment]
Please open a new ticket for RestartFailed (don't forget the debug log). ;)

**Comment by davboc** [comment]
419	02.10.2015 17:49:39	INFO	HOSTER EasybytezCom[57]: Downloading file...
418	02.10.2015 17:48:57	INFO	HOSTER EasybytezCom[57]: Waiting 40 seconds...
417	02.10.2015 17:48:57	WARNING	CAPTCHA EasybytezCom[57]: SolveMedia | Key pattern not found
416	02.10.2015 17:48:57	WARNING	CAPTCHA EasybytezCom[57]: ReCaptcha | Key pattern not found
415	02.10.2015 17:48:56	INFO	HOSTER EasybytezCom[57]: Waiting -1443800936 seconds...
414	02.10.2015 17:48:56	WARNING	CAPTCHA EasybytezCom[57]: SolveMedia | Key pattern not found
413	02.10.2015 17:48:56	WARNING	CAPTCHA EasybytezCom[57]: ReCaptcha | Key pattern not found
412	02.10.2015 17:48:56	INFO	HOSTER EasybytezCom[57]: Processing as free download...
411	02.10.2015 17:48:56	INFO	HOSTER EasybytezCom[57]: File status: avviando
410	02.10.2015 17:48:56	INFO	HOSTER EasybytezCom[57]: File size: 105906176 bytes
409	02.10.2015 17:48:56	INFO	HOSTER EasybytezCom[57]: File name: filename.part051.rar
408	02.10.2015 17:48:56	INFO	HOSTER EasybytezCom[57]: Updating file info...
407	02.10.2015 17:48:56	INFO	Download starts: http://www.easybytez.com/nxxx
406	02.10.2015 17:48:56	INFO	Download aborted: http://www.easybytez.com/xxx
405	02.10.2015 17:22:08	INFO	HOSTER EasybytezCom[57]: Waiting 23932 seconds...
404	02.10.2015 17:22:08	WARNING	CAPTCHA EasybytezCom[57]: SolveMedia | Key pattern not found
403	02.10.2015 17:22:08	WARNING	CAPTCHA EasybytezCom[57]: ReCaptcha | Key pattern not found
402	02.10.2015 17:22:08	INFO	HOSTER EasybytezCom[57]: Processing as free download...
401	02.10.2015 17:22:08	INFO	HOSTER EasybytezCom[57]: File status: avviando
400	02.10.2015 17:22:08	INFO	HOSTER EasybytezCom[57]: File size: 105906176 bytes
399	02.10.2015 17:22:08	INFO	HOSTER EasybytezCom[57]: File name: filename.part051.rar
398	02.10.2015 17:22:07	INFO	HOSTER EasybytezCom[57]: Updating file info...
397	02.10.2015 17:22:07	INFO	Download starts: filename.part051.rar
396	02.10.2015 17:22:07	INFO	Reconnected, new IP: 82.xx.xx.xx
395	02.10.2015 17:21:40	INFO	Starting reconnect
394	02.10.2015 17:21:39	INFO	HOSTER EasybytezCom[57]: Requiring reconnection...
393	02.10.2015 17:21:39	INFO	HOSTER EasybytezCom[57]: Waiting 23960 seconds...
392	02.10.2015 17:21:39	WARNING	HOSTER EasybytezCom[57]: You have reached the download-limit: 600 Mb for last 1 days
391	02.10.2015 17:21:39	INFO	HOSTER EasybytezCom[57]: Waiting -1443799299 seconds...
390	02.10.2015 17:21:39	WARNING	CAPTCHA EasybytezCom[57]: SolveMedia | Key pattern not found
389	02.10.2015 17:21:39	WARNING	CAPTCHA EasybytezCom[57]: ReCaptcha | Key pattern not found
388	02.10.2015 17:21:39	INFO	HOSTER EasybytezCom[57]: Processing as free download...
387	02.10.2015 17:21:39	INFO	HOSTER EasybytezCom[57]: File status: avviando
386	02.10.2015 17:21:39	INFO	HOSTER EasybytezCom[57]: File size: 105906176 bytes 



There is something wrong yet, reconnect works well, ip change, but the download of the file was not restarted automatically, so the ETA that start before the reconnection remain the same at the end. As you can see in the log, at 17.48 I restart manually the download of the file and download starts well. 

Thanks again for all

**Comment by davboc** [comment]
762	02.10.2015 23:30:10	INFO	HOSTER EasybytezCom[76]: Waiting 1850 seconds...
761	02.10.2015 23:30:10	WARNING	CAPTCHA EasybytezCom[76]: SolveMedia | Key pattern not found
760	02.10.2015 23:30:10	WARNING	CAPTCHA EasybytezCom[76]: ReCaptcha | Key pattern not found
759	02.10.2015 23:30:10	INFO	HOSTER EasybytezCom[76]: Processing as free download...
758	02.10.2015 23:30:10	INFO	HOSTER EasybytezCom[76]: File status: avviando
757	02.10.2015 23:30:10	INFO	HOSTER EasybytezCom[76]: File size: 105906176 bytes
756	02.10.2015 23:30:10	INFO	HOSTER EasybytezCom[76]: File name: filename.part070.rar
755	02.10.2015 23:30:09	INFO	HOSTER EasybytezCom[76]: Updating file info...
754	02.10.2015 23:30:09	INFO	Download starts: filename.part070.rar
753	02.10.2015 23:30:09	INFO	Reconnected, new IP: 79.xx.xx.xx
752	02.10.2015 23:29:43	INFO	Starting reconnect
751	02.10.2015 23:29:42	INFO	HOSTER EasybytezCom[76]: Requiring reconnection...
750	02.10.2015 23:29:42	INFO	HOSTER EasybytezCom[76]: Waiting 1877 seconds...
749	02.10.2015 23:29:42	WARNING	HOSTER EasybytezCom[76]: You have reached the download-limit: 600 Mb for last 1 days 


Same behavior, 1877 seconds before reconnect, 1850 seconds after reconnect

**Comment by vuolter** [comment]
Fixed.

**Comment by davboc** [comment]
I have updated and restarted but same behavior after reconnect 

Il 04 ottobre 2015 04:46:07 CEST, Walter Purcaro <notifications@github.com> ha scritto:

**Comment by vuolter** [comment]
Debug log please.

**Comment by davboc** [comment]
108	04.10.2015 15:45:43	DEBUG	ADDON RestartFailed: Restart failed downloads
107	04.10.2015 15:44:49	INFO	HOSTER EasybytezCom[36]: Waiting 29771 seconds...
106	04.10.2015 15:44:49	WARNING	CAPTCHA EasybytezCom[36]: SolveMedia | Key pattern not found
105	04.10.2015 15:44:49	WARNING	CAPTCHA EasybytezCom[36]: ReCaptcha | Key pattern not found
104	04.10.2015 15:44:49	DEBUG	HOSTER EasybytezCom[36]: {u'method_premium': u'Premium Download', u'usr_login': '', u'referer': '', u'fname': u'filename.part030.rar', u'method_free': u'Free Download', u'id': u'nm4pkpxxxxo', u'op': u'download1'}
103	04.10.2015 15:44:49	DEBUG	HOSTER EasybytezCom[36]: Getting download link #1
102	04.10.2015 15:44:49	INFO	HOSTER EasybytezCom[36]: Processing as free download...
101	04.10.2015 15:44:49	DEBUG	HOSTER EasybytezCom[36]: LOAD URL http://www.easybytez.com/nm4pkxxxxo | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
100	04.10.2015 15:44:49	INFO	HOSTER EasybytezCom[36]: File status: avviando
99	04.10.2015 15:44:49	INFO	HOSTER EasybytezCom[36]: File size: 105906176 bytes
98	04.10.2015 15:44:49	INFO	HOSTER EasybytezCom[36]: File name: filename.part030.rar
97	04.10.2015 15:44:49	DEBUG	HOSTER EasybytezCom[36]: Previous file info: {'status': 2, 'name': 'filename.part030.rar', 'error': u'You have reached the download-limit: 600 Mb for last 1 days', 'url': u'http://www.easybytez.com/nmxxxo', 'pattern': {'S': u'101.0', 'U': u'MB', 'N': u'filename.part030.rar'}, 'folder': 'foldername.part030.rar', 'size': 105906176.0}
96	04.10.2015 15:44:49	DEBUG	HOSTER EasybytezCom[36]: File info: {'status': 2, 'name': 'filename.part030.rar', 'url': u'http://www.easybytez.com/nmxxxo', 'pattern': {'S': u'101.0', 'U': u'MB', 'N': u'filename.part030.rar'}, 'error': u'You have reached the download-limit: 600 Mb for last 1 days', 'folder': 'foldername.part030.rar', 'size': 105906176.0}
95	04.10.2015 15:44:49	INFO	HOSTER EasybytezCom[36]: Updating file info...
94	04.10.2015 15:44:49	DEBUG	HOSTER EasybytezCom[36]: PROCESS URL http://www.easybytez.com/nmxxxo | PLUGIN VERSION 0.24
93	04.10.2015 15:44:49	DEBUG	HOSTER EasybytezCom[36]: Config option `use_premium` not found, use default `True`
92	04.10.2015 15:44:49	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
91	04.10.2015 15:44:49	INFO	Download starts: filename.part030.rar
90	04.10.2015 15:44:48	INFO	Reconnected, new IP: 79.49.xx.xx
89	04.10.2015 15:44:21	DEBUG	Old IP: 79.35.xx.xx
88	04.10.2015 15:44:14	INFO	Starting reconnect
87	04.10.2015 15:44:13	INFO	HOSTER EasybytezCom[36]: Requiring reconnection...
86	04.10.2015 15:44:13	INFO	HOSTER EasybytezCom[36]: Waiting 29806 seconds...
85	04.10.2015 15:44:13	DEBUG	HOSTER EasybytezCom[36]: RECONNECT required | Previous wantReconnect: False
84	04.10.2015 15:44:13	DEBUG	HOSTER EasybytezCom[36]: WAIT set to 29806 seconds | Previous waitUntil: 0.000000
83	04.10.2015 15:44:13	WARNING	HOSTER EasybytezCom[36]: You have reached the download-limit: 600 Mb for last 1 days
82	04.10.2015 15:44:13	DEBUG	HOSTER EasybytezCom[36]: Getting download link #2

**Comment by davboc** [comment]
pyload made some updates and now there is this error too:
22	04.10.2015 22:17:17	ERROR	Reconnect Failed: 'ip'
21	04.10.2015 22:16:53	DEBUG	Old IP: 87.xx.xx.xx

**Comment by davboc** [comment]
actually I can't download nothing from easybytez

**Comment by davboc** [comment]
It seems to download a 230bit file of an html type that contains the message "file not found", instead of the real file.... 

Il 04 ottobre 2015 11:35:33 CEST, Walter Purcaro <notifications@github.com> ha scritto:

**Comment by davboc** [comment]
I still can't download from esybytez, I updated to the last version

**Comment by vuolter** [comment]
@davboc Works for me... maybe is an outdated 3rd-party plugin?

**Comment by davboc** [comment]
works for me too, this is only a bad report in the log.

I haven't 3rd-part plugin

**Comment by davboc** [comment]
However, there is still the problem that after reconnect pyload doesn't restart actual download automatically.

**Comment by vuolter** [comment]
@davboc I need the __full__ debug log.

**Comment by davboc** [comment]
this is not the full log? https://github.com/pyload/pyload/issues/1780#issuecomment-145356718

**Comment by vuolter** [comment]
A more recent I mean. ;)

**Comment by davboc** [comment]
This is the full log, here you can find the problem that pyload doesn't restart the file after reconnect and a NEW problem, after the last update, that can't download nothing from easybytez but after reconnect it require anothe reconnect and so on.



70	19.10.2015 01:47:07	INFO	HOSTER EasybytezCom[445]: Waiting 1368 seconds...
69	19.10.2015 01:47:07	DEBUG	CAPTCHA EasybytezCom[445]: SolveMedia | Key pattern not found
68	19.10.2015 01:47:07	WARNING	CAPTCHA EasybytezCom[445]: ReCaptcha | Key pattern not found
67	19.10.2015 01:47:07	DEBUG	HOSTER EasybytezCom[445]: {u'method_premium': u'Premium Download', u'usr_login': '', u'referer': '', u'fname': u'filename.part19.rar', u'method_free': u'Free Download', u'id': u'hft8042xufxj', u'op': u'download1'}
66	19.10.2015 01:47:07	DEBUG	HOSTER EasybytezCom[445]: Getting download link #1
65	19.10.2015 01:47:07	INFO	HOSTER EasybytezCom[445]: Processing as free download...
64	19.10.2015 01:47:07	DEBUG	HOSTER EasybytezCom[445]: LOAD URL http://www.easybytez.com/xxxx/filename.part19.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
63	19.10.2015 01:47:07	INFO	HOSTER EasybytezCom[445]: Link status: online
62	19.10.2015 01:47:07	INFO	HOSTER EasybytezCom[445]: Link size: 264957952 bytes
61	19.10.2015 01:47:07	INFO	HOSTER EasybytezCom[445]: Link name: filename.part19.rar
60	19.10.2015 01:47:07	DEBUG	HOSTER EasybytezCom[445]: Previous link info: {'status': 2, 'name': u'filename.part19.rar', 'error': u'You have to wait 23 minutes, 39 seconds till next download', 'url': u'http://www.easybytez.com/xxxx/filename.part19.rar', 'pattern': {'S': u'252.7', 'U': u'MB', 'N': u'filename.part19.rar'}, 'size': 264957952}
59	19.10.2015 01:47:07	DEBUG	HOSTER EasybytezCom[445]: Link info: {'status': 2, 'name': u'filename.part19.rar', 'url': u'http://www.easybytez.com/xxxx/filename.part19.rar', 'pattern': {'S': u'252.7', 'U': u'MB', 'N': u'filename.part19.rar'}, 'error': u'You have to wait 23 minutes, 39 seconds till next download', 'size': 264957952}
58	19.10.2015 01:47:07	INFO	HOSTER EasybytezCom[445]: Grabbing link info...
57	19.10.2015 01:47:07	DEBUG	HOSTER EasybytezCom[445]: Config option `use_premium` not found, use default `True`
56	19.10.2015 01:47:07	WARNING	HOSTER EasybytezCom[445]: Plugin may be unstable
55	19.10.2015 01:47:07	DEBUG	HOSTER EasybytezCom[445]: Plugin status: testing
54	19.10.2015 01:47:07	DEBUG	HOSTER EasybytezCom[445]: Plugin version: 0.25
53	19.10.2015 01:47:07	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
52	19.10.2015 01:47:06	INFO	Download starts: filename.part19.rar
51	19.10.2015 01:47:06	ERROR	Reconnect Failed: 'ip'
50	19.10.2015 01:46:31	DEBUG	Old IP: 79.56.xx.xx
49	19.10.2015 01:46:17	INFO	Starting reconnect
48	19.10.2015 01:46:16	INFO	HOSTER EasybytezCom[445]: Requiring reconnection...
47	19.10.2015 01:46:16	INFO	HOSTER EasybytezCom[445]: Waiting 1419 seconds...
46	19.10.2015 01:46:16	DEBUG	HOSTER EasybytezCom[445]: RECONNECT required | Previous wantReconnect: False
45	19.10.2015 01:46:16	DEBUG	HOSTER EasybytezCom[445]: WAIT set to timestamp 1445213396.320979 | Previous waitUntil: 1445211974.863319
44	19.10.2015 01:46:16	DEBUG	HOSTER EasybytezCom[445]: Config option `max_wait` not found, use default `10`
43	19.10.2015 01:46:16	WARNING	HOSTER EasybytezCom[445]: You have to wait 23 minutes, 39 seconds till next download
42	19.10.2015 01:46:16	DEBUG	HOSTER EasybytezCom[445]: Getting download link #2
41	19.10.2015 01:46:15	DEBUG	HOSTER EasybytezCom[445]: LOAD URL http://www.easybytez.com/xxxx/filename.part19.rar | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'usr_login': '', u'referer': '', u'fname': u'filename.part19.rar', u'method_free': 'Free Download', u'id': u'hft8042xufxj', u'op': u'download1'} | ref=True | just_header=False
40	19.10.2015 01:46:15	INFO	HOSTER EasybytezCom[445]: Waiting -1 seconds...
39	19.10.2015 01:46:15	DEBUG	CAPTCHA EasybytezCom[445]: SolveMedia | Key pattern not found
38	19.10.2015 01:46:15	WARNING	CAPTCHA EasybytezCom[445]: ReCaptcha | Key pattern not found
37	19.10.2015 01:46:15	DEBUG	HOSTER EasybytezCom[445]: {u'method_premium': u'Premium Download', u'usr_login': '', u'referer': '', u'fname': u'filename.part19.rar', u'method_free': u'Free Download', u'id': u'hft8042xufxj', u'op': u'download1'}
36	19.10.2015 01:46:15	DEBUG	HOSTER EasybytezCom[445]: Getting download link #1
35	19.10.2015 01:46:15	INFO	HOSTER EasybytezCom[445]: Processing as free download...
34	19.10.2015 01:46:15	DEBUG	HOSTER EasybytezCom[445]: LOAD URL http://www.easybytez.com/xxxx/filename.part19.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
33	19.10.2015 01:46:15	INFO	HOSTER EasybytezCom[445]: Link status: online
32	19.10.2015 01:46:15	INFO	HOSTER EasybytezCom[445]: Link size: 264957952 bytes
31	19.10.2015 01:46:15	INFO	HOSTER EasybytezCom[445]: Link name: filename.part19.rar
30	19.10.2015 01:46:15	DEBUG	HOSTER EasybytezCom[445]: Previous link info: {'status': 2, 'pattern': {'S': u'252.7', 'U': u'MB', 'N': u'filename.part19.rar'}, 'url': u'http://www.easybytez.com/xxxx/filename.part19.rar', 'name': u'filename.part19.rar', 'size': 264957952}
29	19.10.2015 01:46:15	DEBUG	HOSTER EasybytezCom[445]: Link info: {'status': 2, 'name': u'filename.part19.rar', 'url': u'http://www.easybytez.com/xxxx/filename.part19.rar', 'pattern': {'S': u'252.7', 'U': u'MB', 'N': u'filename.part19.rar'}, 'size': 264957952}
28	19.10.2015 01:46:15	INFO	HOSTER EasybytezCom[445]: Grabbing link info...
27	19.10.2015 01:46:15	DEBUG	HOSTER EasybytezCom[445]: Config option `use_premium` not found, use default `True`
26	19.10.2015 01:46:15	WARNING	HOSTER EasybytezCom[445]: Plugin may be unstable
25	19.10.2015 01:46:15	DEBUG	HOSTER EasybytezCom[445]: Plugin status: testing
24	19.10.2015 01:46:15	DEBUG	HOSTER EasybytezCom[445]: Plugin version: 0.25
23	19.10.2015 01:46:15	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
22	19.10.2015 01:46:15	INFO	Download starts: filename.part19.rar
21	19.10.2015 01:45:14	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
20	19.10.2015 01:45:14	DEBUG	pycurl exception 28: Operation too slow. Less than 5 bytes/sec transferred the last 30 seconds
19	19.10.2015 01:44:39	DEBUG	HOSTER EasybytezCom[445]: LOAD URL http://www.easybytez.com/xxxx/filename.part19.rar | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'rand': u'4wvrkvg6vapqf3ld4fi3q5xctagwrfn7hlgjcti', u'down_script': u'1', u'referer': '', u'method_free': 'Free Download', u'id': u'hft8042xufxj', u'op': u'download2'} | ref=True | just_header=False
18	19.10.2015 01:41:37	INFO	HOSTER EasybytezCom[445]: Waiting 180 seconds...
17	19.10.2015 01:41:37	DEBUG	CAPTCHA EasybytezCom[445]: SolveMedia | Key pattern not found
16	19.10.2015 01:41:37	WARNING	CAPTCHA EasybytezCom[445]: ReCaptcha | Key pattern not found
15	19.10.2015 01:41:37	DEBUG	HOSTER EasybytezCom[445]: RECONNECT not required | Previous wantReconnect: False
14	19.10.2015 01:41:37	DEBUG	HOSTER EasybytezCom[445]: WAIT set to timestamp 1445211878.529352 | Previous waitUntil: 0.000000
13	19.10.2015 01:41:37	DEBUG	HOSTER EasybytezCom[445]: {u'rand': u'4wvrkvg6vapqf3ld4fi3q5xctagwrfn7hlgjcti', u'method_premium': '', u'down_script': u'1', u'referer': '', u'method_free': u'Free Download', u'id': u'hft8042xufxj', u'op': u'download2'}
12	19.10.2015 01:41:37	DEBUG	HOSTER EasybytezCom[445]: Getting download link #2
11	19.10.2015 01:41:37	DEBUG	HOSTER EasybytezCom[445]: LOAD URL http://www.easybytez.com/xxxx/filename.part19.rar | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'usr_login': '', u'referer': '', u'fname': u'filename.part19.rar', u'method_free': 'Free Download', u'id': u'hft8042xufxj', u'op': u'download1'} | ref=True | just_header=False
10	19.10.2015 01:41:37	INFO	HOSTER EasybytezCom[445]: Waiting -1445211697 seconds...
9	19.10.2015 01:41:37	DEBUG	CAPTCHA EasybytezCom[445]: SolveMedia | Key pattern not found
8	19.10.2015 01:41:37	WARNING	CAPTCHA EasybytezCom[445]: ReCaptcha | Key pattern not found
7	19.10.2015 01:41:37	DEBUG	HOSTER EasybytezCom[445]: {u'method_premium': u'Premium Download', u'usr_login': '', u'referer': '', u'fname': u'filename.part19.rar', u'method_free': u'Free Download', u'id': u'hft8042xufxj', u'op': u'download1'}
6	19.10.2015 01:41:37	DEBUG	HOSTER EasybytezCom[445]: Getting download link #1
5	19.10.2015 01:41:37	INFO	HOSTER EasybytezCom[445]: Processing as free download...
4	19.10.2015 01:41:36	DEBUG	HOSTER EasybytezCom[445]: LOAD URL http://www.easybytez.com/xxxx/filename.part19.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
3	19.10.2015 01:41:36	INFO	HOSTER EasybytezCom[445]: Link status: online
2	19.10.2015 01:41:36	INFO	HOSTER EasybytezCom[445]: Link size: 264957952 bytes
1	19.10.2015 01:41:36	INFO	HOSTER EasybytezCom[445]: Link name: filename.part19.rar

**Comment by davboc** [comment]
I delete again userplugins folder, and after update now seems to download properly. Waiting for reconnect to see if it is solved

**Comment by davboc** [comment]
I confirm that the problem of restart after reconnect was resolved, great work mate
