### ISSUE TITLE
UPTOBOX huge files download doesn't work

### ISSUE THREAD

**Issue by fright1980** [pyload/pyload#1783]
Hello,

When I try to download anything from hugefiles I am getting following error at the end of download and nothing happens..." INFO ACCOUNT UptoboxCom: Parsing account info for user XXXXXX" I have this error message in loop in the debug log and nothing happens.

Thanks for your help.

**Comment by boerngen-schmidt** [comment]
Seems that the API/Website of XFS based hosters has changed.

**Comment by joberreiter** [comment]
New plugin version with #1826.
