### ISSUE TITLE
PremiumTo | Premium download failed

### ISSUE THREAD

**Issue by tripfish** [pyload/pyload#1786]
Hello,

when I download some files via PremiumTo the files are downloaded correctly on the disk, but pyload marks the files as "failed".

Here is a snippet from the log...
>
26.08.2015 10:53:24 INFO      Download starts: http://ul.to/xxxxx
26.08.2015 10:53:24 INFO      HOSTER PremiumTo[47]: PremiumTo | Updating file info...
26.08.2015 10:53:25 INFO      HOSTER PremiumTo[47]: PremiumTo | File name: xxxxx
26.08.2015 10:53:25 INFO      HOSTER PremiumTo[47]: PremiumTo | File size: Unknown
26.08.2015 10:53:25 INFO      HOSTER PremiumTo[47]: PremiumTo | File status: queued
26.08.2015 10:53:25 INFO      HOSTER PremiumTo[47]: PremiumTo | File status: queued
26.08.2015 10:53:25 INFO      ACCOUNT PremiumTo: Parsing account info for user `xxxxx`...
26.08.2015 10:53:25 INFO      HOSTER PremiumTo[47]: PremiumTo | Filesize: 0 KiB, Traffic left for user xxxxx: 1364421534.05 KiB
26.08.2015 10:53:25 INFO      HOSTER PremiumTo[47]: PremiumTo | Processing as premium download...
[...]
26.08.2015 10:53:56 WARNING   HOSTER PremiumTo[47]: PremiumTo | Premium download failed
26.08.2015 10:53:56 INFO      Download restarted: xxxxx | Fallback to free download
26.08.2015 10:53:56 INFO      Download starts: xxxxx
26.08.2015 10:53:56 WARNING   Download failed: xxxxx | Required account not found
26.08.2015 10:53:56 INFO      HOOK UnSkipOnFail: Looking for skipped duplicates of: xxxxx (pid:2)
26.08.2015 10:53:56 INFO      HOOK UnSkipOnFail: No duplicates found 

Tried a fresh install (with new UpdateManager.py) but still the same.

PremiumTo.py Version 0.25
PremiumToHook.py Version 0.11

**Comment by It0w** [comment]
Same as #1745
