### ISSUE TITLE
Download section completely dead at pyload.org

### ISSUE THREAD

**Issue by drt1** [pyload/pyload#1791]
Hey folks,

I'm pretty sure this is not the right place to mention errors on the website,
but I do not have an account there and don't want to open one from mobile just to report this,
but the whole download section at pyload.org is down since several days.

No matter which link: 
win, deb, src ... all lead to 404.

greets!

**Comment by joberreiter** [comment]
Yes, this had been reported before with #1648.

v0.4.9 is unuseable due to an defective update manager.
You have to [download](https://github.com/pyload/pyload/archive/stable.zip) or clone the stable branch until a new version is released (#1607).

**Comment by drt1** [comment]
yep, I already did because pyload got stuck and stopped working.
after cloning the stable branch it works fine...would it be possible to link to the zip-file you posted or to let users know, that there is something in the bushes?

**Comment by joberreiter** [comment]
I'm sorry, I'm unable to do this.

@vuolter
@RaNaN 
@stickell
