### ISSUE TITLE
DeathbyCaptcha not working (do log in debug, no nothing)

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#1792]
DeathbyCaptcha not working (do log in debug, no nothing)
It's like the Plugin isn't working at all

btw. i have first entered captcha9kw and as a second "fallback" captcha-solving service deathbycaptcha.. hope thats not the problem. because this worked fine before the major changes. 
this is kind of a big problem, because Captcha9kw isn't really reliable anymore. Most of the time the captchas are not sovled by 9kw anymore :(

**Comment by vuolter** [comment]
Debug log please.
