### ISSUE TITLE
Problems processing youtu.be

### ISSUE THREAD

**Issue by B1gG** [pyload/pyload#1793]
Guys my pyload have problem to manage short url from YouTube, I'm using the app on Android and just sharing the url to pyload and it doesn't work. 
Do you have a fox for it?

**Comment by joberreiter** [comment]
Do you have a debug log for it?

**Comment by B1gG** [comment]
Yes, in fact I think that is a problem with the regexp used as __pattern__ and yesterday night  after a couple of hours of debug and help of pyregex.com I fix it.
Let me try to share my changes, I'm new in GitHub.

**Comment by B1gG** [comment]
657	26.08.2015 21:08:53	DEBUG	HOSTER BasePlugin[15]: Previous wantReconnect: False
656	26.08.2015 21:08:53	INFO	HOSTER BasePlugin[15]: RECONNECT disabled
655	26.08.2015 21:08:53	DEBUG	HOSTER BasePlugin[15]: Previous waitUntil: 1440639529.266300
654	26.08.2015 21:08:53	INFO	HOSTER BasePlugin[15]: WAIT 60 seconds
653	26.08.2015 21:08:53	WARNING	HOSTER BasePlugin[15]: Check result: Html file | Waiting 1 minute and retry
652	26.08.2015 21:08:51	DEBUG	HOSTER BasePlugin[15]: DOWNLOAD URL https://www.youtube.com/watch?v=550LPcmhybk&feature=youtu.be | cookies=True | get={} | disposition=True | post={} | ref=False
651	26.08.2015 21:08:50	DEBUG	HOSTER BasePlugin[15]: LOAD URL https://youtu.be/550LPcmhybk | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
650	26.08.2015 21:08:50	DEBUG	HOSTER BasePlugin[15]: Redirect #0 to: https://youtu.be/550LPcmhybk
649	26.08.2015 21:08:50	DEBUG	HOSTER BasePlugin[15]: PROCESS URL https://youtu.be/550LPcmhybk | PLUGIN VERSION 0.45
648	26.08.2015 21:08:50	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
647	26.08.2015 21:08:50	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
646	26.08.2015 21:08:50	INFO	Download starts: 550LPcmhybk
645	26.08.2015 21:08:50	DEBUG	All downloads processed
644	26.08.2015 21:08:50	DEBUG	HOOK AndroidPhoneNotify: LOAD URL http://www.notifymyandroid.com/publicapi/notify | cookies=True | get={'application': 'pyLoad', 'apikey': u'46ade0e8e16aca1dc3a3bca679ee48f01c745f2a286e7c91', 'event': u'Package failed', 'description': u'One or more packages was not completed successfully'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
643	26.08.2015 21:08:50	INFO	Download restarted: 550LPcmhybk | Html file
