### ISSUE TITLE
Threaded Server SSL delivers no Intermediate Certificate

### ISSUE THREAD

**Issue by protree** [pyload/pyload#1809]
Pyload stopped working over https for me. I have a StartCom SSL Certificate that requires an intermediate certificate to be delivered to the browser. So I included it in ssl.crt in addition to my server certificate. This setup worked for 2 years until now.

Since today Chrome and Safari give ssl-warnings because only the server certificate and not the intermediate certificate is delivered by the threaded server, so the ssl trust chain is broken. I didn't change my configuration or whatever. There are no Warnings in the Log. I tried to include the StartCom root CA certificate in ssl.crt without any luck. Connecting to Pyload by using the ip and ignoring the ssl warning works (HTST is activated). All permissions for conf files, logs, certificates etc. are set correctly.

My conf:

ssl - "SSL":
        file cert : "SSL Certificate" = /etc/myssl/ssl.crt
        bool activated : "Activated" = True
        file key : "SSL Key" = /etc/myssl/ssl.key

webinterface - "Webinterface":
        str template : "Template" = default
        bool activated : "Activated" = True
        str prefix : "Path Prefix" =
        builtin;threaded;fastcgi;lightweight server : "Server" = threaded
        ip host : "IP" = 0.0.0.0
        bool https : "Use HTTPS" = True
        int port : "Port" = 9001

ssl.crt:

-----BEGIN CERTIFICATE-----
Server Certificate
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
Intermediate Certificate
-----END CERTIFICATE-----

Log:

08.09.2015 00:01:26 INFO      starte pyLoad 0.4.9
08.09.2015 00:01:26 INFO      Benutze Home-Verzeichnis: /etc/pyload
08.09.2015 00:01:30 INFO      ADDON ExternalScripts: Registered script: [all_downloads_finished] scripts/all_downloads_finished/push_notify
08.09.2015 00:01:30 INFO      ADDON ExternalScripts: Installed scripts in folder `all_downloads_finished`: scripts/all_downloads_finished/push_notify
08.09.2015 00:01:30 INFO      Aktivierte Plugins: ClickAndLoad, ExternalScripts, ExtractArchive, LinkdecrypterComHook, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
08.09.2015 00:01:30 INFO      Deaktivierte Plugins: AlldebridComHook, AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, TransmissionRPC, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
08.09.2015 00:01:30 INFO      Downloadzeit: True
08.09.2015 00:01:30 INFO      Freier Speicher: 528.31 GiBGB
08.09.2015 00:01:30 INFO      Aktiviere Accounts...
08.09.2015 00:01:31 INFO      Starting threaded SSL webserver: 0.0.0.0:9001
08.09.2015 00:01:31 INFO      ACCOUNT ShareonlineBiz: Login user `XXX`...
08.09.2015 00:01:32 INFO      ACCOUNT ShareonlineBiz: Parsing account info for user `XXX`...
08.09.2015 00:01:32 INFO      Activating Plugins...
08.09.2015 00:01:32 INFO      HOOK XFileSharingPro: Handling any hoster I can!
08.09.2015 00:01:32 INFO      HOOK XFileSharingPro: Handling any crypter I can!
08.09.2015 00:01:32 INFO      pyLoad is up and running
08.09.2015 00:01:32 INFO      ADDON UpdateManager: No new pyLoad version available
08.09.2015 00:01:32 INFO      ADDON UpdateManager: No plugin updates available
08.09.2015 00:01:34 INFO      HOOK LinkdecrypterCom: Reloading supported crypter list
08.09.2015 00:01:34 INFO      HOOK LinkdecrypterCom: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
08.09.2015 00:01:40 INFO      HOOK LinkdecrypterCom: Reloading supported crypter list
08.09.2015 00:01:40 INFO      HOOK LinkdecrypterCom: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
08.09.2015 00:01:42 INFO      ADDON ClickAndLoad: Proxy listening on 0.0.0.0:9666

**Comment by GammaC0de** [comment]
Fixed.
