### ISSUE TITLE
uloz.to pycurl exception/error 3: malformed

### ISSUE THREAD

**Issue by xDereCx** [pyload/pyload#1811]
after a while tryed to dowload from uloz.to, find out that there is a problem with hoster, link working ok from browser

debug is here https://www.dropbox.com/s/7heauwt2b8891xm/debug_UlozTo_10-09-2015_19-12-24.zip?dl=0

**Comment by joberreiter** [comment]
Maybe Uloz.to had changed their html file sources. Two possible error sources for the malformed url:
1) A missing `http:` in front of the capcha urls
2) additional backslashes to mask the slash in captcha urls (originating from the downloaded html source): `http:\/\/xapca12.uloz.to\/6254ae72d160b583256fda1caafcf665d695af14\/image.gif`

But I'm unsure how to fix it properly.

**Comment by janpal** [comment]
just to note, other download managers are still capable of downloading from uloz.to

**Comment by PabloRadegast** [comment]
Hi, I have the same problem. I am used to use uloz.to regularly, but now I don't get the captcha and in the log I see only "ERROR	pycurl error 3: malformed". It is free account and my pyLoad version is 0.4.9.

**Comment by yedlick** [comment]
My hotfix is based on joberreiter comment - there is missing **http:**
try to edit UlozTo.py, line 75 like this:

```captcha_value = self.captcha.decrypt("http:"+str(data['image']))```

**Comment by xDereCx** [comment]
not working for me 56	24.09.2015 17:57:48	DEBUG	HOSTER UlozTo[667]: xapca = {"image":"http:\/\/xapca12.uloz.to\/c1aa104a2554811278f1cd3e2b8a1538ecb206fe\/image.gif","sound":"http:\/\/xapca12.uloz.to\/c1aa104a2554811278f1cd3e2b8a1538ecb206fe\/sound.wav","hash":"c1aa104a2554811278f1cd3e2b8a1538ecb206fe","timestamp":1443113866,"salt":3311}
57	24.09.2015 17:57:48	DEBUG	CAPTCHA UlozTo[667]: Captcha | LOAD URL http:http://xapca12.uloz.to/c1aa104a2554811278f1cd3e2b8a1538ecb206fe/image.gif | cookies=True | get={} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
58	24.09.2015 17:57:48	DEBUG	pycurl exception 6: Could not resolve host: http:http
59	24.09.2015 17:57:48	ERROR	pycurl error 6: Could not resolve host: http:http

**Comment by teofilko** [comment]
Thank @yedlick,
I added >*"http:"+*< into **UlozTo.py**, line 110
         `captcha_value = self.decryptCaptcha("http:"+str(data['image']))`
and work now.

**Comment by xDereCx** [comment]
line number? get email that it was line 110, hotfix was about line 75?

**Comment by teofilko** [comment]
I use old version UlozTo.py. I had to change line 110. In newest version I think must change line 75 how wrote yedlick.
Try to find `captcha_value = self.captcha.decrypt(str(data['image']))` or ` captcha_value = self.decryptCaptcha(str(data['image']))` and replace `(`*"http:"+*`str(data['image']))`
