### ISSUE TITLE
Uptobox (free access) hangs in the "Starting" stage

### ISSUE THREAD

**Issue by f6fvy** [pyload/pyload#1819]
When a package of several uptobox URL is submitted, the first one is downloaded, but the following ones just hang forever at the "Starting" stage.

Download starts :xxx.avi
HOSTER UptoboxCom[194]: Updating file info...
HOSTER UptoboxCom[194]: File name: xxx.avi
HOSTER UptoboxCom[194]: File size: 367421030 bytes
HOSTER UptoboxCom[194]: File status: online
HOSTER UptoboxCom[194]: Processing as free download...
HOSTER UptoboxCom[194]: WAIT 60 seconds
HOSTER UptoboxCom[194]: RECONNECT disabled

**Comment by pixou80** [comment]
same problem here except that all files added with uptobox stay "starting" : 

13.09.2015 19:38:28	INFO	HOSTER UptoboxCom[2]: Updating file info...
126	13.09.2015 19:38:29	INFO	HOSTER UptoboxCom[2]: File name: test.zip
127	13.09.2015 19:38:29	INFO	HOSTER UptoboxCom[2]: File size: 3196 bytes
128	13.09.2015 19:38:29	INFO	HOSTER UptoboxCom[2]: File status: online
129	13.09.2015 19:38:30	INFO	HOSTER UptoboxCom[2]: Processing as free download...
130	13.09.2015 19:38:30	INFO	HOSTER UptoboxCom[2]: WAIT 60 seconds
131	13.09.2015 19:38:30	INFO	HOSTER UptoboxCom[2]: RECONNECT disabled
134	13.09.2015 19:38:32	INFO	Download starts: http://uptobox.com/xxxxxx
135	13.09.2015 19:38:32	INFO	HOSTER UptoboxCom[5]: Updating file info...
136	13.09.2015 19:38:34	INFO	HOSTER UptoboxCom[5]: File name: test2.zip
137	13.09.2015 19:38:34	INFO	HOSTER UptoboxCom[5]: File size: 2773 bytes
138	13.09.2015 19:38:34	INFO	HOSTER UptoboxCom[5]: File status: online
145	13.09.2015 19:38:36	INFO	HOSTER UptoboxCom[5]: Processing as free download...
146	13.09.2015 19:38:36	INFO	HOSTER UptoboxCom[5]: WAIT 60 seconds
147	13.09.2015 19:38:36	INFO	HOSTER UptoboxCom[5]: RECONNECT disabled

**Comment by joberreiter** [comment]
New plugin version with #1826.

**Comment by f6fvy** [comment]
Still doesn't work:-(  When several DL are in the queue, only the first one is processed and the others are stuck in the "Starting" state forever. The "Restart pyload" doesn't work either at that stage. I have to restart my RasPi to get the next file...

**Comment by bast69** [comment]
I have the same problem as @f6fvy

**Comment by f6fvy** [comment]
And now, after another automatic update, all downloads fail:

22.09.2015 02:28:50	WARNING	Download failed: xxx.avi | 'UptoboxCom' object has no attribute 'user' 

It looks like Pyload will never handle Uptobox correctly ;-)
