### ISSUE TITLE
flexget error (without changed anything)

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#1828]
maybe this is related to #1782
flexget gives an error, but i did not changed anything flexget related. Just updated pyload. So maybe you could take a look at the externalscripts ? thx

**Comment by vuolter** [comment]
What error please?

**Comment by snickers2k** [comment]
2015-09-21 10:26 CRITICAL pyload        Movies_Watchlist_Stream Login failed
2015-09-21 10:26 WARNING  task          Movies_Watchlist_Stream Aborting task (plugin: pyload)

but my login is right...

**Comment by vuolter** [comment]
The fix is coming tomorrow. ;)

**Comment by snickers2k** [comment]
okay, thanks. can you confirm that the problem is pyload related ? Or is it me or flexget? 
really can't use pyload right now, because of this :(

so a fix would be highly appreciated ^^
thanks

**Comment by vuolter** [comment]
ExternalScripts should working now.
