### ISSUE TITLE
Zippyshare dosen't work 

### ISSUE THREAD

**Issue by crazy06** [pyload/pyload#1831]
Hello, since yesterday pyload get an error Message, trying to download from Zippyshare:

20.09.2015 22:54:11	DEBUG	Parsed package abc with 3 links
17	20.09.2015 22:54:11	DEBUG	Redirected import module.plugins.hoster.ZippyshareCom -> userplugins.hoster.ZippyshareCom
18	20.09.2015 22:54:11	DEBUG	Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
19	20.09.2015 22:54:11	DEBUG	Run Info Fetching for ZippyshareCom
20	20.09.2015 22:54:11	INFO	Added package abc containing 3 links
21	20.09.2015 22:54:13	DEBUG	Finished Info Fetching for ZippyshareCom
22	20.09.2015 22:54:13	INFO	Download starts: black-20150921040319.part3.rar
23	20.09.2015 22:54:13	DEBUG	UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
24	20.09.2015 22:54:13	DEBUG	ZippyshareCom: Update file info...
25	20.09.2015 22:54:13	DEBUG	ZippyshareCom: Previous file info: {}
26	20.09.2015 22:54:13	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'url': u'http://www30.zippyshare.com/v/j5pWew7D/file.html', 'size': 8524922.8800000008, 'name': u'black-20150921040319.part3.rar', 'pattern': {'S': u'8.13', 'U': u'MB', 'KEY': u'j5pWew7D', 'N': u'black-20150921040319.part3.rar'}}
27	20.09.2015 22:54:13	DEBUG	ZippyshareCom: File name: black-20150921040319.part3.rar | File size: 8524922 byte
28	20.09.2015 22:54:13	DEBUG	ZippyshareCom: File status: online
29	20.09.2015 22:54:14	DEBUG	ZippyshareCom: Update file info...
30	20.09.2015 22:54:14	DEBUG	ZippyshareCom: Previous file info: {'status': 2, 'url': u'http://www30.zippyshare.com/v/j5pWew7D/file.html', 'size': 8524922.8800000008, 'name': u'black-20150921040319.part3.rar', 'pattern': {'S': u'8.13', 'U': u'MB', 'KEY': u'j5pWew7D', 'N': u'black-20150921040319.part3.rar'}}
31	20.09.2015 22:54:14	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'name': u'black-20150921040319.part3.rar', 'url': u'http://www30.zippyshare.com/v/j5pWew7D/file.html', 'pattern': {'S': u'8.13', 'U': u'MB', 'KEY': u'j5pWew7D', 'N': u'black-20150921040319.part3.rar'}, 'size': 8524922.8800000008}
32	20.09.2015 22:54:14	DEBUG	ZippyshareCom: File name: black-20150921040319.part3.rar | File size: 8524922 byte
33	20.09.2015 22:54:14	DEBUG	ZippyshareCom: Update file info...
34	20.09.2015 22:54:14	DEBUG	ZippyshareCom: Previous file info: {'status': 2, 'name': u'black-20150921040319.part3.rar', 'url': u'http://www30.zippyshare.com/v/j5pWew7D/file.html', 'pattern': {'S': u'8.13', 'U': u'MB', 'KEY': u'j5pWew7D', 'N': u'black-20150921040319.part3.rar'}, 'size': 8524922.8800000008}
35	20.09.2015 22:54:14	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'name': u'black-20150921040319.part3.rar', 'url': u'http://www30.zippyshare.com/v/j5pWew7D/file.html', 'pattern': {'S': u'8.13', 'U': u'MB', 'KEY': u'j5pWew7D', 'N': u'black-20150921040319.part3.rar'}, 'size': 8524922.8800000008}
36	20.09.2015 22:54:14	DEBUG	ZippyshareCom: File name: black-20150921040319.part3.rar | File size: 8524922 byte
37	20.09.2015 22:54:14	DEBUG	ZippyshareCom: File status: online
38	20.09.2015 22:54:14	DEBUG	ZippyshareCom: Handled as free download
39	20.09.2015 22:54:14	DEBUG	ReCaptcha: Key not found
40	20.09.2015 22:54:16	INFO	Download skipped: black-20150921040319.part1.rar due to ZippyshareCom
41	20.09.2015 22:54:18	INFO	Download skipped: black-20150921040319.part2.rar due to ZippyshareCom
42	20.09.2015 22:54:19	DEBUG	Download Check triggered
43	20.09.2015 22:54:19	DEBUG	Download Check triggered
44	20.09.2015 22:54:19	INFO	Download finished: black-20150921040319.part3.rar
45	20.09.2015 22:54:19	INFO	Package finished: abc 

can you check this?

Sorry about my bad english :-)

**Comment by vuolter** [comment]
Try disabling SkipRev plugin...

**Comment by crazy06** [comment]
The plugin is disabled by default for me.

Here another attempt, the files and the size to be found correctly. It is also available in the Download Status, however, remains the stand at 0 kb / s and exits.


21.09.2015 22:13:52	DEBUG	Run Info Fetching for ZippyshareCom
5	21.09.2015 22:13:52	INFO	Added package x containing 2 links
6	21.09.2015 22:13:53	DEBUG	Finished Info Fetching for ZippyshareCom
7	21.09.2015 22:13:54	INFO	Download starts: x.part1.rar
8	21.09.2015 22:13:54	DEBUG	UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
9	21.09.2015 22:13:54	DEBUG	ZippyshareCom: Update file info...
10	21.09.2015 22:13:54	DEBUG	ZippyshareCom: Previous file info: {}
11	21.09.2015 22:13:54	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'url': u'http://www71.zippyshare.com/v/lBKR4B4j/file.html', 'size': 157286400.0, 'name': u'x.part1.rar', 'pattern': {'S': u'150', 'U': u'MB', 'KEY': u'lBKR4B4j', 'N': u'x.part1.rar'}}
12	21.09.2015 22:13:54	DEBUG	ZippyshareCom: File name: x.part1.rar | File size: 157286400 byte
13	21.09.2015 22:13:54	DEBUG	ZippyshareCom: File status: online
14	21.09.2015 22:13:54	DEBUG	ZippyshareCom: Update file info...
15	21.09.2015 22:13:54	DEBUG	ZippyshareCom: Previous file info: {'status': 2, 'url': u'http://www71.zippyshare.com/v/lBKR4B4j/file.html', 'size': 157286400.0, 'name': u'x.rar', 'pattern': {'S': u'150', 'U': u'MB', 'KEY': u'lBKR4B4j', 'N': u'x.part1.rar'}}
16	21.09.2015 22:13:54	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'name': u'x.part1.rar', 'url': u'http://www71.zippyshare.com/v/lBKR4B4j/file.html', 'pattern': {'S': u'150', 'U': u'MB', 'KEY': u'lBKR4B4j', 'N': u'x.part1.rar'}, 'size': 157286400.0}
17	21.09.2015 22:13:54	DEBUG	ZippyshareCom: File name: x.part1.rar | File size: 157286400 byte
18	21.09.2015 22:13:54	DEBUG	ZippyshareCom: Update file info...
19	21.09.2015 22:13:54	DEBUG	ZippyshareCom: Previous file info: {'status': 2, 'name': u'x.part1.rar', 'url': u'http://www71.zippyshare.com/v/lBKR4B4j/file.html', 'pattern': {'S': u'150', 'U': u'MB', 'KEY': u'lBKR4B4j', 'N': u'x.part1.rar'}, 'size': 157286400.0}
20	21.09.2015 22:13:54	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'name': u'x.part1.rar', 'url': u'http://www71.zippyshare.com/v/lBKR4B4j/file.html', 'pattern': {'S': u'150', 'U': u'MB', 'KEY': u'lBKR4B4j', 'N': u'x.part1.rar'}, 'size': 157286400.0}
21	21.09.2015 22:13:54	DEBUG	ZippyshareCom: File name: x.part1.rar | File size: 157286400 byte
22	21.09.2015 22:13:54	DEBUG	ZippyshareCom: File status: online
23	21.09.2015 22:13:54	DEBUG	ZippyshareCom: Handled as free download
24	21.09.2015 22:13:54	DEBUG	ReCaptcha: Key not found
25	21.09.2015 22:13:57	INFO	Download starts: x.part2.rar
26	21.09.2015 22:13:57	DEBUG	UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
27	21.09.2015 22:13:57	DEBUG	ZippyshareCom: Update file info...
28	21.09.2015 22:13:57	DEBUG	ZippyshareCom: Previous file info: {}
29	21.09.2015 22:13:57	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'url': u'http://www61.zippyshare.com/v/Ua4nefnb/file.html', 'size': 121016156.16, 'name': u'x.part2.rar', 'pattern': {'S': u'115.41', 'U': u'MB', 'KEY': u'Ua4nefnb', 'N': u'x.part2.rar'}}
30	21.09.2015 22:13:57	DEBUG	ZippyshareCom: File name: x.part2.rar | File size: 121016156 byte
31	21.09.2015 22:13:57	DEBUG	ZippyshareCom: File status: online
32	21.09.2015 22:13:58	DEBUG	ZippyshareCom: Update file info...
33	21.09.2015 22:13:58	DEBUG	ZippyshareCom: Previous file info: {'status': 2, 'url': u'http://www61.zippyshare.com/v/Ua4nefnb/file.html', 'size': 121016156.16, 'name': u'x.part2.rar', 'pattern': {'S': u'115.41', 'U': u'MB', 'KEY': u'Ua4nefnb', 'N': u'x.part2.rar'}}
34	21.09.2015 22:13:58	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'name': u'x.part2.rar', 'url': u'http://www61.zippyshare.com/v/Ua4nefnb/file.html', 'pattern': {'S': u'115.41', 'U': u'MB', 'KEY': u'Ua4nefnb', 'N': u'x.part2.rar'}, 'size': 121016156.16} 
21.09.2015 22:13:58	DEBUG	ZippyshareCom: File name: x.part2.rar | File size: 121016156 byte
36	21.09.2015 22:13:58	DEBUG	ZippyshareCom: Update file info...
37	21.09.2015 22:13:58	DEBUG	ZippyshareCom: Previous file info: {'status': 2, 'name': u'x.part2.rar', 'url': u'http://www61.zippyshare.com/v/Ua4nefnb/file.html', 'pattern': {'S': u'115.41', 'U': u'MB', 'KEY': u'Ua4nefnb', 'N': u'x.part2.rar'}, 'size': 121016156.16}
38	21.09.2015 22:13:58	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'name': u'x.part2.rar', 'url': u'http://www61.zippyshare.com/v/Ua4nefnb/file.html', 'pattern': {'S': u'115.41', 'U': u'MB', 'KEY': u'Ua4nefnb', 'N': u'x.part2.rar'}, 'size': 121016156.16}
39	21.09.2015 22:13:58	DEBUG	ZippyshareCom: File name: x.part2.rar | File size: 121016156 byte
40	21.09.2015 22:13:58	DEBUG	ZippyshareCom: File status: online
41	21.09.2015 22:13:58	DEBUG	ZippyshareCom: Handled as free download
42	21.09.2015 22:13:58	DEBUG	ReCaptcha: Key not found
43	21.09.2015 22:14:03	DEBUG	Download Check triggered
44	21.09.2015 22:14:03	DEBUG	Download Check triggered
45	21.09.2015 22:14:03	INFO	Download finished: x.part1.rar
46	21.09.2015 22:14:03	DEBUG	Download Check triggered
47	21.09.2015 22:14:03	DEBUG	Download Check triggered
48	21.09.2015 22:14:03	INFO	Download finished: x.part2.rar
49	21.09.2015 22:14:03	INFO	Package finished:

**Comment by sraedler** [comment]
i think this could be closed
