### ISSUE TITLE
object has no attribute 'user'

### ISSUE THREAD

**Issue by dev-rke** [pyload/pyload#1833]
Tried downloading from SO and from uploaded, i get always the message as free user:
object has no attribute 'user'

I am using the latest git checkout.
I tried to remove the userplugins directory in /etc/.pyload but had no luck.

**Comment by dev-rke** [comment]
Ok, switched back to fa6704b where everything works fine.
Also i disabled autoupdate, due to frequent instabilities in this "stable" branch.

**Comment by nordic-style** [comment]
same problem as a premium user.

**Comment by milanhlavin** [comment]
Debug:
pyLoad 0.4.9 Debug Report of UlozTo 1.15 

TRACEBACK:
 Traceback (most recent call last):
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Hoster.py", line 184, in preprocessing
    return self._process(*args, **kwargs)
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Hoster.py", line 168, in _process
    self.load_account()  #@TODO: Move to PluginThread in 0.4.10
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Hoster.py", line 195, in load_account
    if not self.account.user:  #@TODO: Move to `Account` in 0.4.10
AttributeError: 'UlozTo' object has no attribute 'user'
 

FRAMESTACK:

Frame preprocessing in /mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Hoster.py at line 184
	                self = <Hoster UlozTo>
	                args = (<DownloadThread(Thread-2, started daemon)>,)
	              kwargs = {}

Frame _process in /mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Hoster.py at line 168
	                self = <Hoster UlozTo>
	              thread = <DownloadThread(Thread-2, started daemon)>

Frame load_account in /mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Hoster.py at line 195
	                self = <Hoster UlozTo>


PLUGIN OBJECT DUMP: 

	       ADULT_PATTERN = '<form action="(.+?)" method="post" id="frm-askAgeForm">'
	          CHECK_FILE = True
	       CHECK_TRAFFIC = True
	             COOKIES = True
	         DIRECT_LINK = None
	         DISPOSITION = True
	         FILE_ERRORS = [('Html error',
  '\\A(?:\\s*<.+>)?((?:[\\w\\s]*(?:[Ee]rror|ERROR)\\s*\\:?)?\\s*\\d{3})(?:\\Z|\\s+)'),
 ('Request error', '([Aa]n error occured while processing your request)'),
 ('Html file', '\\A\\s*<!DOCTYPE html')]
	        LEECH_HOSTER = False
	        LINK_PATTERN = None
	       LOGIN_ACCOUNT = False
	       LOGIN_PREMIUM = False
	        NAME_PATTERN = '(<p>File <strong>|<title>)(?P<N>.+?)(<| \\|)'
	   NAME_REPLACEMENTS = []
	     OFFLINE_PATTERN = '<title>404 - Page not found</title>|<h1 class="h1">File (has been deleted|was banned)</h1>'
	      PASSWD_PATTERN = '<div class="passwordProtectedFile">'
	        SIZE_PATTERN = '<span id="fileSize">.*?(?P<S>[\\d.,]+\\s[kMG]?B)</span>'
	   SIZE_REPLACEMENTS = [('([\\d.]+)\\s([kMG])B', <function convert_decimal_prefix at 0x2c162530>)]
	       TEXT_ENCODING = True
	       TOKEN_PATTERN = '<input type="hidden" name="_token_" .*?value="(.+?)"'
	    URL_REPLACEMENTS = [('(?<=http://)([^/]+)', 'www.ulozto.net')]
	     VIPLINK_PATTERN = '<a href=".+?\\?disclaimer=1" class="linkVip">'
	             account = <Account UlozTo>
	             captcha = <Captcha Captcha>
	         chunk_limit = 1
	                html = ''
	                info = {}
	                  js = <module.common.JsEngine.JsEngine instance at 0x42a120>
	          last_check = None
	       last_download = ''
	             limitDL = 0
	             multiDL = True
	             premium = False
	              pyfile = PyFile 51: http://www.ulozto.cz/xtKu2VP6/labyrint-4-dil-avi@UlozTo
	              pyload = <__main__.Core object at 0x1af0b0>
	                 req = <module.network.Browser.Browser object at 0x7bd378>
	     resume_download = True
	             retries = {}
	          retry_free = False
	              thread = <DownloadThread(Thread-2, started daemon)>
	          wait_until = 0
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 0
	               abort = False
	              active = False
	               error = "'UlozTo' object has no attribute 'user'"
	                  id = 51
	                lock = <_RLock(None, 0)>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x2059b8>
	         maxprogress = 100
	                name = u'http://www.ulozto.cz/xtKu2VP6/labyrint-4-dil-avi'
	               order = 0
	           packageid = 46
	              plugin = <Hoster UlozTo>
	         pluginclass = <class 'userplugins.hoster.UlozTo.UlozTo'>
	        pluginmodule = <module 'userplugins.hoster.UlozTo' from '/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/hoster/UlozTo.pyc'>
	          pluginname = u'UlozTo'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'http://www.ulozto.cz/xtKu2VP6/labyrint-4-dil-avi'
	           waitUntil = 0


CONFIG: 

{'desc': 'UlozTo',
 'outline': 'Uloz.to hoster plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': True}}

**Comment by pixou80** [comment]
same problem for 1fichier.com, uptobox.com ...

**Comment by mojoAction** [comment]
same with uploadedTo

**Comment by cynt4k** [comment]
same with smoozed

**Comment by Sle3perX** [comment]
same with shareonline.biz and uploadable.Ch

**Comment by darkpella** [comment]
same with easybytez

**Comment by joberreiter** [comment]
Same with all, as this seems to be an error in internal/Hoster.py ...

**Comment by andrebower** [comment]
I remember the same issue happening a few weeks ago? an update broke the plugins.

**Comment by darkpella** [comment]
I just copied all files form the latest authoring from vuolter (commit 9a16506897) to my usr/share/pyload folder and started pyLoad.
the 'xxxxxx' object has no attribute 'user' issue seems to be gone, but a new issue surfaced, at least with Easybytez.
Now every downloads fails with the following log entries:
"INFO	Download starts: xxxxx.rar
722	23.09.2015 23:25:13	INFO	HOSTER EasybytezCom[1265]: Updating file info...
723	23.09.2015 23:25:17	INFO	HOSTER EasybytezCom[1265]: File name: xxxxx.rar
724	23.09.2015 23:25:17	INFO	HOSTER EasybytezCom[1265]: File size: 525336576 bytes
725	23.09.2015 23:25:17	INFO	HOSTER EasybytezCom[1265]: File status: online
726	23.09.2015 23:25:21	INFO	HOSTER EasybytezCom[1265]: Processing as free download...
727	23.09.2015 23:25:21	WARNING	Download failed: xxxxx.rar | first argument must be string or compiled pattern
728	23.09.2015 23:25:21	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: xxxxx.rar (pid:41)
729	23.09.2015 23:25:21	INFO	ADDON UnSkipOnFail: No duplicates found"

Please notice that I do own a valid premium Easybytez account, that I entered it into pyLoad and that the account tab under the configuration page (Web GUI) confirms my Easybytez account is a valid premium one.

(in vuolter we trust!)

**Comment by smystero** [comment]
Using Easybytez.com I receive this message (repeated for each file) in logs:
Download failed: xxxxxxxx.partyy.rar | 'EasybytezCom' object has no attribute 'user'

**Comment by pixou80** [comment]
With the last update it's ok for this error but i've a new one  : 
WARNING	Download failed: XXXXXXX | first argument must be string or compiled pattern

**Comment by smystero** [comment]
Me too sane problema Witherspoon EB premium  account
