### ISSUE TITLE
'UlozTo' object has no attribute 'user'

### ISSUE THREAD

**Issue by milanhlavin** [pyload/pyload#1834]
INFO	Download starts: http://www.ulozto.cz/xtKu2VP6/labyrint-4-dil-avi
WARNING	Download failed: http://www.ulozto.cz/xtKu2VP6/labyrint-4-dil-avi | 'UlozTo' object has no attribute 'user'
INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: http://www.ulozto.cz/xtKu2VP6/labyrint-4-dil-avi (pid:46)
INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by joberreiter** [comment]
Related to #1833.
