### ISSUE TITLE
'NoneType' object has no attribute 'UptoboxCom' with alldebrid plugin

### ISSUE THREAD

**Issue by damien599901** [pyload/pyload#1838]
dear all

i can't download anything with the alldebrid plugin
all the downloads stay in the queue

help

**Comment by janpal** [comment]
The same for UlozTo

**Comment by damien599901** [comment]
before np/now everyday.
what's happen?

2015-09-23 20:05 GMT+02:00 janpal <notifications@github.com>:

**Comment by joberreiter** [comment]
> what's happen?

How should one know this without further information what your copy of pyLoad is doing?
Log snippet, debug log?

**Comment by damien599901** [comment]
if you read my duplicate messages as you say, you will see my explanations,
a video and my logs
but nobody has answered 😀

2015-09-25 16:04 GMT+02:00 Jochen Oberreiter <notifications@github.com>:

**Comment by joberreiter** [comment]
Yes, but opening new issues only because no one has a fix ready for your error is not a solution at all.
It causes just work and / or confusion for others--without solving your issue ...

**Comment by vuolter** [comment]
@joberreiter :+1:
