### ISSUE TITLE
'UploadedTo' object has no attribute 'user'

### ISSUE THREAD

**Issue by TalmarGrosskotz** [pyload/pyload#1839]
Hi since today i get the following Error Message when i try to download a uploaded.to file

'UploadedTo' object has no attribute 'user'

Console shows:

22.09.2015 21:39:33 INFO      Download starts: nameoffile.rar
22.09.2015 21:39:33 WARNING   Download failed: nameoffile.rar | 'UploadedTo' object has no attribute 'user'

The Logfile doesn't give any additional info.

Any Ideas?

**Comment by ZuseZ3** [comment]
Hi,

have the same error after reinstall pyload.

**Comment by vuolter** [comment]
Working on...

**Comment by vuolter** [comment]
Duplicate of https://github.com/pyload/pyload/issues/1833
