### ISSUE TITLE
Strange Syntax error

### ISSUE THREAD

**Issue by idrostasi** [pyload/pyload#1842]
Hello,

after a fresh installation of pyLoad on my qnap nas, I get this error message:

23.09.2015 11:54:44	WARNING	Error calling event handler pluginConfigChanged: >, ('EasybytezComHook', 'activated', True), 'NoneType' object has no attribute 'EasybytezCom'
805	23.09.2015 11:54:44	ERROR	Error importing EasybytezCom: invalid syntax (Hoster.py, line 212)
804	23.09.2015 11:47:38	CRITICAL	'NoneType' object has no attribute 'EasybytezCom'

All plugins are updated and I can't download files.

Help please!

**Comment by nafex** [comment]
fixed with #1843
