### ISSUE TITLE
NoneType object has no attribute 'CatShareNet'

### ISSUE THREAD

**Issue by SebaBoler** [pyload/pyload#1844]
When i added new link i get 

1401	23.09.2015 14:11:05	CRITICAL	'NoneType' object has no attribute 'CatShareNet'
1400	23.09.2015 14:11:05	ERROR	Error importing CatShareNet: invalid syntax (Hoster.py, line 212)
1399	23.09.2015 14:11:04	ERROR	Error importing CatShareNet: invalid syntax (Hoster.py, line 212)

**Comment by tatu007** [comment]
Hello same error with OneFichier and UploadedTo :
> 152	23.09.2015 15:34:22	ERROR	Error importing UploadedTo: invalid syntax (Hoster.py, line 212)
> 153	23.09.2015 15:34:22	CRITICAL	'NoneType' object has no attribute 'UploadedTo' 
> 160	23.09.2015 15:34:51	ERROR	Error importing OneFichierCom: invalid syntax (Hoster.py, line 212)
> 161	23.09.2015 15:34:51	CRITICAL	'NoneType' object has no attribute 'OneFichierCom'

**Comment by muschikatz3** [comment]
Hello! 
Same error here:
----><--------><-------->snip<--------><--------><---- 
2112	23.09.2015 15:58:04	CRITICAL	'NoneType' object has no attribute 'UploadedTo'
2111	23.09.2015 15:58:04	ERROR	Error importing UploadedTo: invalid syntax (Hoster.py, line 212)
2110	23.09.2015 15:58:02	CRITICAL	'NoneType' object has no attribute 'UploadedTo'
2109	23.09.2015 15:58:02	ERROR	Error importing UploadedTo: invalid syntax (Hoster.py, line 212)
2108	23.09.2015 15:58:00	CRITICAL	'NoneType' object has no attribute 'UploadedTo'
2107	23.09.2015 15:58:00	ERROR	Error importing UploadedTo: invalid syntax (Hoster.py, line 212) 
----><--------><-------->snip<--------><--------><----

**Comment by nafex** [comment]
fixed with #1843
