### ISSUE TITLE
'NoneType' object has no attribute 'UptoboxCom'

### ISSUE THREAD

**Issue by aronze06** [pyload/pyload#1845]
Hi All;
When I try to add a new download link (Uptobox, Free, 1Fichier or another one...) I Have this message 'NoneType' object has no attribute 'UptoboxCom' and my download doesn't start.
Do you have solution to solve this problem.
Thanks to all of you !

Alexis

**Comment by zhaobb** [comment]
Same problem for RapidGatorNet

**Comment by nafex** [comment]
fixed with #1843

**Comment by aronze06** [comment]
Thanks for your answer !
I haven't pyload/module/plugins/internal/Hoster.py file and I created this file with code inside. It works fine !!!!
Thank you for your help !
