### ISSUE TITLE
Error importing UptoboxCom: invalid syntax (Hoster.py, line 212)

### ISSUE THREAD

**Issue by xilmen** [pyload/pyload#1847]
My download from uptobox don't start 

ERROR Error importing UptoboxCom: invalid syntax (Hoster.py, line 212)
CRITICAL 'NoneType' object has no attribute 'UptoboxCom'

Hoster v0.27

ty !

**Comment by tribal123** [comment]
same here....
Error importing EasybytezCom: invalid syntax (Hoster.py, line 212)

**Comment by sysms** [comment]
Same here:
ERROR	Error importing BasePlugin: invalid syntax (Hoster.py, line 212)
CRITICAL	'NoneType' object has no attribute 'BasePlugin'

**Comment by chaosblog** [comment]
Isn't this fixed with commits 625be1490bee7e8dd44af720eb64864799c06487 and 3da545b9be94d5da8d247102538e062ea83b0a56?

**Comment by xilmen** [comment]
nop, i have hoster.py v0.27 updated today.

23.09.2015 07:55:13	INFO	ADDON UpdateManager: New version of plugin: [internal] Hoster (v0.26 -> v0.27)

**Comment by Garog** [comment]
Same here
Fehler beim importieren von LinkdecrypterCom: invalid syntax (Hoster.py, line 212)
And when adding a dlc file
Error importing DLC: invalid syntax (Hoster.py, line 212)
Pyload is not working after i got an update from 0.26 to 0.27 from Hoster.py

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/948e0cc21ea369a6661a3b6154374a09c1f7251f
