### ISSUE TITLE
the "alldebrid hook" plugin makes KO the downloads

### ISSUE THREAD

**Issue by damien599901** [pyload/pyload#1851]
Hello

if the plugin in this title is activated, again my downloads can't begin

thank you for your help

**Comment by damien599901** [comment]
new error message : "first argument must be string or compiled pattern "

**Comment by damien599901** [comment]
another one "Required account not found" (e.g. with a link of "uptobox" and the alldebrid hook plugin + a premium account of alldebrid of course)

**Comment by joberreiter** [comment]
Related to #1859.

**Comment by Mave95** [comment]
same problem with debriditalia

**Comment by damien599901** [comment]
@joberreiter : sorry for the "duplicate" issues
But what's happened? Pyload has been hacked?  i ve never seen something like this and i use pyload since long years
BR
Damien

**Comment by gregus69** [comment]
Same problem here with alldebrid since 1 week T_T

**Comment by Poule-Hein** [comment]
Same problem here with alldebrid again

**Comment by joberreiter** [comment]
@gregus69
@Poule-Hein 
Please be a little more specific about your error messages (and look if another issue with the same error had been opened before), because this particular issue is very ambiguos (= the "alldebrid hook" plugin makes KO the downloads) and should be closed.

**Comment by gregus69** [comment]
Hi joberreiter

log of my pyload before and after installation

14   25.09.2015 11:13:31   INFO   Download starts: 2006OSS7790.rar
15   25.09.2015 11:13:31   DEBUG   ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
16   25.09.2015 11:13:31   DEBUG   ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
17   25.09.2015 11:13:31   DEBUG   HOSTER AlldebridCom[21]: AlldebridCom | PROCESS URL http://uptobox.com/yhvoqvsyo9vx | PLUGIN VERSION 0.48
18   25.09.2015 11:13:31   WARNING   Download failed: 2006OSS7790.rar | Required account not found
19   25.09.2015 11:13:31   INFO   ADDON UnSkipOnFail: Looking for skipped duplicates of: 2006OSS7790.rar (pid:3)
20   25.09.2015 11:13:31   INFO   ADDON UnSkipOnFail: No duplicates found
21   25.09.2015 11:13:33   INFO   Download starts: 2006OSS7790.rar
22   25.09.2015 11:13:33   DEBUG   ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
23   25.09.2015 11:13:33   DEBUG   ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
24   25.09.2015 11:13:33   DEBUG   HOSTER AlldebridCom[22]: AlldebridCom | PROCESS URL http://uptobox.com/yhvoqvsyo9vx | PLUGIN VERSION 0.48
25   25.09.2015 11:13:33   WARNING   Download failed: 2006OSS7790.rar | Required account not found
26   25.09.2015 11:13:33   INFO   ADDON UnSkipOnFail: Looking for skipped duplicates of: 2006OSS7790.rar (pid:3)
27   25.09.2015 11:13:33   INFO   ADDON UnSkipOnFail: No duplicates found
28   25.09.2015 11:13:33   DEBUG   All downloads processed

king regards

**Comment by damien599901** [comment]
@joberreiter : you re right. My title is not clear. Nothing works anymore with Pyload + alldebrid

**Comment by gregus69** [comment]
today is good for me without update of plugins or soft ?

**Comment by gregus69** [comment]
sorry :

INFO      ADDON UpdateManager: New version of plugin: [account] AlldebridCom (v0.27 -> v0.28)


very nice

**Comment by Poule-Hein** [comment]
Yess! It's good for me ! 

ADDON UpdateManager: New version of plugin: [account] AlldebridCom (v0.27 -> v0.28)

Nice Job ;)

**Comment by damien599901** [comment]
don't work anymore

**Comment by gregus69** [comment]
yes,

same problem since 3 days

WARNING	ACCOUNT AlldebridCom: Error loading info for user `XXXX` | (6, "Couldn't resolve host 'http'")
22	05.10.2015 09:29:48	INFO	ACCOUNT AlldebridCom: Updating account info for user `XXXX`...
23	05.10.2015 09:29:48	INFO	ACCOUNT AlldebridCom: Relogin user `XXXX`...

**Comment by Poule-Hein** [comment]
Yes,

Same problem for me

05.10.2015 08:38:22	WARNING	Reconnect script not found!
05.10.2015 08:38:22	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `xxx`...
05.10.2015 08:38:25	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `xxx`...

**Comment by joberreiter** [comment]
It is not an alldebrid problem, but a core issue with all hosters/plugins affected.
Latest errors are duplicates of #1962 and #1965.

@vuolter 
Close this issue, the first error has been resolved, the latter ones are just duplicates.

**Comment by vuolter** [comment]
@joberreiter :+1:
