### ISSUE TITLE
"first argument must be string or compiled pattern"

### ISSUE THREAD

**Issue by darkpella** [pyload/pyload#1852]
Following to issue #1833 

I just copied all files form the latest authoring from vuolter (commit 9a16506) to my usr/share/pyload folder and started pyLoad.
the " 'xxxxxx' object has no attribute 'user' " issue seems to be gone, but a new issue surfaced, at least with Easybytez.
Now every downloads fails with the following log entries:
"84 23.09.2015 23:31:26 INFO Download starts: XXXX.rar
85 23.09.2015 23:31:26 INFO HOSTER EasybytezCom[1285]: Updating file info...
86 23.09.2015 23:31:29 INFO HOSTER EasybytezCom[1285]: File name: XXXX.rar
87 23.09.2015 23:31:29 INFO HOSTER EasybytezCom[1285]: File size: 525336576 bytes
88 23.09.2015 23:31:29 INFO HOSTER EasybytezCom[1285]: File status: online
89 23.09.2015 23:31:33 INFO HOSTER EasybytezCom[1285]: Processing as free download...
90 23.09.2015 23:31:33 WARNING Download failed: XXXX.rar | first argument must be string or compiled pattern
91 23.09.2015 23:31:33 INFO ADDON UnSkipOnFail: Looking for skipped duplicates of: XXXX.rar (pid:43) "

Please notice that though line 89 states the dwnload will be processed as a free one,I do own a valid premium Easybytez account, I entered its credentials into pyLoad and the "Account" tab under the "Configuration" page (Webinterface) confirms my Easybytez account is a valid premium one.

(in vuolter we trust!)

**Comment by Exormeter** [comment]
Can confirm, premium access seems to be broken in this commit.
Using Share-Onlnie.biz and am not able to use my premium acc.

**Comment by smystero** [comment]
Same here

**Comment by Hadronius** [comment]
Same here with a different host (Worldbytez.com).

Any ideas on how to fix this?!

**Comment by joberreiter** [comment]
@vuolter
Seems like the Hoster (EasyBytez, WorldBytez) has no variable `RECAPTCHA_PATTERN` defined.
In `internal/XFSHoster.py` this variable is initialized with `None`, so the error is a logical result.

Has every hoster a different `RECAPTCHA_PATTERN`?

**Comment by joberreiter** [comment]
Ok, this solves the issue, but now I'm receiving a 'media error' at the webUI-dialog. Hm.

**Comment by lorenzobb** [comment]
Same issue for me.

here is my debug log with a valid premium account on easybytez.

614	25.09.2015 21:59:52	INFO	Download starts: SanAndreas1080p.part33.rar
615	25.09.2015 21:59:52	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
616	25.09.2015 21:59:52	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
617	25.09.2015 21:59:52	DEBUG	HOSTER EasybytezCom[137]: PROCESS URL http://www.easybytez.com/43vblan9irvd | PLUGIN VERSION 0.24
618	25.09.2015 21:59:52	DEBUG	HOSTER EasybytezCom[137]: Config option `use_premium` not found, use default `True`
619	25.09.2015 21:59:52	INFO	HOSTER EasybytezCom[137]: Updating file info...
620	25.09.2015 21:59:55	DEBUG	HOSTER EasybytezCom[137]: File info: {'status': 2, 'url': u'http://www.easybytez.com/43vblan9irvd', 'size': 123522252.8, 'name': u'SanAndreas1080p.part33.rar', 'pattern': {'S': u'117.8', 'U': u'MB', 'N': u'SanAndreas1080p.part33.rar'}}
621	25.09.2015 21:59:55	DEBUG	HOSTER EasybytezCom[137]: Previous file info: {}
622	25.09.2015 21:59:55	INFO	HOSTER EasybytezCom[137]: File name: SanAndreas1080p.part33.rar
623	25.09.2015 21:59:55	INFO	HOSTER EasybytezCom[137]: File size: 123522252 bytes
624	25.09.2015 21:59:55	INFO	HOSTER EasybytezCom[137]: File status: online
625	25.09.2015 21:59:55	DEBUG	HOSTER EasybytezCom[137]: LOAD URL http://www.easybytez.com/43vblan9irvd | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
626	25.09.2015 21:59:56	INFO	HOSTER EasybytezCom[137]: Processing as free download...
627	25.09.2015 21:59:56	DEBUG	HOSTER EasybytezCom[137]: Getting download link #1
628	25.09.2015 21:59:56	DEBUG	HOSTER EasybytezCom[137]: {u'method_premium': u'Premium Download', u'usr_login': '', u'referer': '', u'fname': u'SanAndreas1080p.part33.rar', u'method_free': u'Free Download', u'id': u'43vblan9irvd', u'op': u'download1'}
629	25.09.2015 21:59:56	WARNING	Download failed: SanAndreas1080p.part33.rar | first argument must be string or compiled pattern
630	25.09.2015 21:59:57	INFO	Debug Report written to debug_EasybytezCom_25-09-2015_21-59-56.zip
631	25.09.2015 21:59:57	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: SanAndreas1080p.part33.rar (pid:6)
632	25.09.2015 21:59:57	INFO	ADDON UnSkipOnFail: No duplicates found
633	25.09.2015 21:59:57	DEBUG	All downloads processed

**Comment by Hadronius** [comment]
I believe the problem is bit earlier in the code, inside the SimpleHoster.py where it goes to free download instead of premium, as it should, and prints:  "Processing as free download..."
Maybe the use_premium flag wasn't set correctly until then?
Unfortunately I'm not that familiar with the code.

**Comment by Hadronius** [comment]
I manualy made the changes in https://github.com/mationic/pyload/commit/5f9d6f992cb889379dd02fe71fe8c5a4b149fc44
 and the error is gone, I can download normally now as premium.
Try it.

**Comment by lorenzobb** [comment]
@joberreiter 
i added captha and recaptcha to the stable release, but it still did not recognize my premium account.

Here is a part of log.

thanks for you help.

26.09.2015 19:55:17 INFO      Download starts: SanAndreas1080p.part01.rar
26.09.2015 19:55:17 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
26.09.2015 19:55:17 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
26.09.2015 19:55:17 DEBUG     HOSTER EasybytezCom[99]: PROCESS URL http://www.easybytez.com/qkqn0u9e7vuj | PLUGIN VERSION 0.24
26.09.2015 19:55:17 DEBUG     HOSTER EasybytezCom[99]: Config option `use_premium` not found, use default `True`
26.09.2015 19:55:17 INFO      HOSTER EasybytezCom[99]: Updating file info...
26.09.2015 19:55:18 DEBUG     HOSTER EasybytezCom[99]: File info: {'status': 2, 'url': u'http://www.easybytez.com/qkqn0u9e7vuj', 'size': 263192576.0, 'name': u'SanAndreas1080p.part01.rar', 'pattern': {'S': u'251.0', 'U': u'MB', 'N': u'SanAndreas1080p.part01.rar'}}
26.09.2015 19:55:18 DEBUG     HOSTER EasybytezCom[99]: Previous file info: {}
26.09.2015 19:55:18 INFO      HOSTER EasybytezCom[99]: File name: SanAndreas1080p.part01.rar
26.09.2015 19:55:18 INFO      HOSTER EasybytezCom[99]: File size: 263192576 bytes
26.09.2015 19:55:18 INFO      HOSTER EasybytezCom[99]: File status: online
26.09.2015 19:55:18 DEBUG     HOSTER EasybytezCom[99]: LOAD URL http://www.easybytez.com/qkqn0u9e7vuj | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
26.09.2015 19:55:19 INFO      HOSTER EasybytezCom[99]: Processing as free download...
26.09.2015 19:55:19 DEBUG     HOSTER EasybytezCom[99]: Getting download link #1
26.09.2015 19:55:19 DEBUG     HOSTER EasybytezCom[99]: {u'method_premium': u'Premium Download', u'usr_login': '', u'referer': '', u'fname': u'SanAndreas1080p.part01.rar', u'method_free': u'Free Download', u'id': u'qkqn0u9e7vuj', u'op': u'download1'}
26.09.2015 19:55:19 WARNING   CAPTCHA EasybytezCom[99]: ReCaptcha | Key pattern not found
26.09.2015 19:55:19 WARNING   CAPTCHA EasybytezCom[99]: SolveMedia | Key pattern not found
26.09.2015 19:55:19 DEBUG     HOSTER EasybytezCom[99]: LOAD URL http://www.easybytez.com/qkqn0u9e7vuj | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'usr_login': '', u'referer': '', u'fname': u'SanAndreas1080p.part01.rar', u'method_free': 'Free Download', u'id': u'qkqn0u9e7vuj', u'op': u'download1'} | ref=True | just_header=False
26.09.2015 19:55:19 DEBUG     HOSTER EasybytezCom[99]: Getting download link #2
26.09.2015 19:55:19 WARNING   HOSTER EasybytezCom[99]: You have to wait 13 minutes, 16 seconds till next download
26.09.2015 19:55:19 INFO      HOSTER EasybytezCom[99]: Waiting 796 seconds...
26.09.2015 19:55:19 DEBUG     HOSTER EasybytezCom[99]: Previous waitUntil: 0.000000
26.09.2015 19:55:19 DEBUG     HOSTER EasybytezCom[99]: Reconnect: False
26.09.2015 19:55:19 DEBUG     HOSTER EasybytezCom[99]: Previous wantReconnect: True

**Comment by lorenzobb** [comment]
Now is working thanks. :+1:
