### ISSUE TITLE
Shareonlinebiz only load as free user

### ISSUE THREAD

**Issue by XneddyX** [pyload/pyload#1853]
I have a problem that Shareonlinebiz  is only loading as free user. my premium account is still working. I dont now where the problem is. My logs said no problems.

**Comment by DKeppi** [comment]
Same at UploadedTo

**Comment by Timmaaee** [comment]
Same problem with both hosters. Is there a workaround?

**Comment by vicegold** [comment]
Same here with UL.net

**Comment by Kazyini** [comment]
Same problem.

**Comment by Koelli91** [comment]
Same here (since Hoster.py-Update 0.27->0.28 as fix for https://github.com/pyload/pyload/issues/1847).
Debug-Log says nothing special about it (seams if pyload is just not using the Account(s) at all).
I have re-added the account and restartet pyload a few times - no change unfortunately

**Comment by Garog** [comment]
here too,

i have this problem every time someone updates the Hoster.py file... no other account is working (see other issues) do the dev test what they produce... doesn't seems so...

**Comment by jackdierippe** [comment]
Same situation here with shareonline.
After the hoster.py syntax error been fixed, now this issue.

**Comment by mationic** [comment]
https://github.com/mationic/pyload/commit/5f9d6f992cb889379dd02fe71fe8c5a4b149fc44 should fix premium accounts

**Comment by XneddyX** [comment]
when i put your hoster.py file in my pyload i have this issue:

WARNING	Download failed: XXXXXXXXXXXXX.rar | 'ShareonlineBiz' object has no attribute 'user'

**Comment by vicegold** [comment]
@mationic this works for a few sec, but then pyload crashes all the time. Again after a restart.

**Comment by mationic** [comment]
Hmm.. it works for me.. Restart pyload, try to readd premium account.

**Comment by sixteeN11** [comment]
'ShareonlineBiz' object has no attribute 'user'

**Comment by mationic** [comment]
https://github.com/mationic/pyload/commit/3b54dce909e07fbc6668c1e1cf19b9d25b61e195

This did the trick for me...

**Comment by XneddyX** [comment]
@mationic first thank you, but it is the same problem...
WARNING Download failed: XXXXXXXXXXXXX.rar | 'ShareonlineBiz' object has no attribute 'user'

**Comment by mationic** [comment]
@XneddyX https://github.com/mationic/pyload/commit/44b65e8f1ea367e00da1638e0362f9443b57e760

**Comment by XneddyX** [comment]
@mationic i have change all 3 files but:
WARNING   Download failed: soa.0605.s5s4.l2.hd1-itn.part1.rar | 'ShareonlineBiz' object has no attribute 'user'
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/usr/share/pyload-config/userplugins/internal/Hoster.py", line 184, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/share/pyload-config/userplugins/internal/Hoster.py", line 179, in _process
    return self.process(self.pyfile)
  File "/usr/share/pyload/module/plugins/internal/SimpleHoster.py", line 280, in process
    self.handle_premium(pyfile)
  File "/usr/share/pyload/module/plugins/hoster/ShareonlineBiz.py", line 125, in handle_premium
    get={'username': self.user,
AttributeError: 'ShareonlineBiz' object has no attribute 'user'

**Comment by mationic** [comment]
>File "/usr/share/pyload/module/plugins/hoster/ShareonlineBiz.py", line 125, in handle_premium
>get={'username': self.user,
is old. Should be
>get={'username': self.account.user,

**Comment by fassmus** [comment]
Perfect! All three changes together fixed it for me...

THX

**Comment by XneddyX** [comment]
@mationic sry my mistake... i have put ShareonlineBiz.py into the userplugin folder under the same versions number...

**Comment by Altranas** [comment]
@mationic i have the same issue with uploades.to - pyload only start downloads in free user mode.

**Comment by mationic** [comment]
@Altranas uploaded.to is working for me with https://github.com/pyload/pyload/pull/1863

**Comment by Altranas** [comment]
ok i give it a try - thx

**Comment by Altranas** [comment]
ok - it works again - thx mationic

**Comment by Binomico** [comment]
SO fixed with https://github.com/pyload/pyload/pull/1863

thx ;-)
