### ISSUE TITLE
Skip already existing file - not working

### ISSUE THREAD

**Issue by SebaBoler** [pyload/pyload#1857]
I got off option about Skip already existing file
<img width="494" alt="zrzut ekranu 2015-09-24 o 11 37 50" src="https://cloud.githubusercontent.com/assets/9715474/10070170/0738efc6-62b1-11e5-927b-8a1be47586d0.png">

but when i trying download this same file again i got information File exists, skip download.

**Comment by vuolter** [comment]
Fixed.
