### ISSUE TITLE
Zippyshare (Parse error: 'NoneType' object has no attribute 'group' | Plugin may be out of date)

### ISSUE THREAD

**Issue by spam8117** [pyload/pyload#1862]
There seems to be a problem with Zippyshare (and maybe some other hosters).
I downloaded the newest UpdateManager.py as well as the newest SimpleHoster.py (manually, see https://github.com/pyload/pyload/pull/1858). SimplyHoster.py fixed the Uploaded.to problems, Zippyshares seems to be another issue.

24.09.2015 16:26:55 INFO      Download starts: DLIA-CFTS30.part09.rar
24.09.2015 16:26:55 INFO      HOSTER ZippyshareCom[36]: Updating file info...
24.09.2015 16:26:55 INFO      HOSTER ZippyshareCom[36]: File name: DLIA-CFTS30.part09.rar
24.09.2015 16:26:55 INFO      HOSTER ZippyshareCom[36]: File size: 209715200 bytes
24.09.2015 16:26:55 INFO      HOSTER ZippyshareCom[36]: File status: online
24.09.2015 16:26:55 INFO      HOSTER ZippyshareCom[36]: Processing as free download...
24.09.2015 16:26:55 WARNING   Download failed: DLIA-CFTS30.part09.rar | Parse error: 'NoneType' object has no attribute 'group' | Plugin may be out of date
24.09.2015 16:26:55 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: DLIA-CFTS30.part09.rar (pid:13)
24.09.2015 16:26:55 INFO      ADDON UnSkipOnFail: No duplicates found

**Comment by spam8117** [comment]
P.S. SimplyHoster.py fixed the Uploaded.to problems (see https://github.com/pyload/pyload/pull/1858).
Zippyshares seems to be another issue.

**Comment by GammaC0de** [comment]
@spam8117 please post debug log and/or effected URL plz
also, I think zippy uses recaptcha v2 which pyload cannot deal with

**Comment by spam8117** [comment]
@GammaC0de Sorry, please see debug log below (URL is visible in the debug log).
http://www64.zippyshare.com/v/TmOvYMQj/file.html

24.09.2015 17:53:29 INFO      Download starts: DLIA-CFTS30.part07.rar
24.09.2015 17:53:29 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
24.09.2015 17:53:29 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
24.09.2015 17:53:29 DEBUG     HOSTER BasePlugin[31]: PROCESS URL DLIA-CFTS30.part07.rar | PLUGIN VERSION 0.45
24.09.2015 17:53:29 WARNING   Download failed: DLIA-CFTS30.part07.rar | No plugin matched
24.09.2015 17:53:29 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: DLIA-CFTS30.part07.rar (pid:13)
24.09.2015 17:53:29 INFO      ADDON UnSkipOnFail: No duplicates found
24.09.2015 17:53:31 INFO      Download starts: DLIA-CFTS30.part07.rar
24.09.2015 17:53:31 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
24.09.2015 17:53:31 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
24.09.2015 17:53:31 DEBUG     HOSTER ZippyshareCom[32]: PROCESS URL http://www64.zippyshare.com/v/TmOvYMQj/file.html | PLUGIN VERSION 0.82
24.09.2015 17:53:31 INFO      HOSTER ZippyshareCom[32]: Updating file info...
24.09.2015 17:53:32 DEBUG     HOSTER ZippyshareCom[32]: File info: {'status': 2, 'url': u'http://www64.zippyshare.com/v/TmOvYMQj/file.html', 'size': 209715200.0, 'name': u'DLIA-CFTS30.part07.rar', 'pattern': {'S': u'200', 'U': u'MB', 'KEY': u'TmOvYMQj', 'N': u'DLIA-CFTS30.part07.rar'}}
24.09.2015 17:53:32 DEBUG     HOSTER ZippyshareCom[32]: Previous file info: {}
24.09.2015 17:53:32 INFO      HOSTER ZippyshareCom[32]: File name: DLIA-CFTS30.part07.rar
24.09.2015 17:53:32 INFO      HOSTER ZippyshareCom[32]: File size: 209715200 bytes
24.09.2015 17:53:32 INFO      HOSTER ZippyshareCom[32]: File status: online
24.09.2015 17:53:32 DEBUG     HOSTER ZippyshareCom[32]: LOAD URL http://www64.zippyshare.com/v/TmOvYMQj/file.html | cookies=[('zippyshare.com', 'ziplocale', 'en')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
24.09.2015 17:53:32 INFO      HOSTER ZippyshareCom[32]: Processing as free download...
24.09.2015 17:53:32 DEBUG     CAPTCHA ZippyshareCom[32]: ReCaptcha | Key: 6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq
24.09.2015 17:53:32 DEBUG     CAPTCHA ZippyshareCom[32]: ReCaptcha | Key: 6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq
24.09.2015 17:53:32 DEBUG     HOSTER ZippyshareCom[32]: LOAD URL http://www.google.com/recaptcha/api.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
24.09.2015 17:53:32 DEBUG     CAPTCHA ZippyshareCom[32]: ReCaptcha | API version: r20150915103233
24.09.2015 17:53:32 DEBUG     CAPTCHA ZippyshareCom[32]: ReCaptcha | API language: fr
24.09.2015 17:53:32 DEBUG     HOSTER ZippyshareCom[32]: LOAD URL https://apis.google.com/js/api.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
24.09.2015 17:53:32 DEBUG     CAPTCHA ZippyshareCom[32]: ReCaptcha | API jsh-string: m;/_/scs/apps-static/_/js/k=oz.gapi.nl._YmkBCSndSI.O/m=__features__/am=AQ/rt=j/d=1/t=zcms/rs=AGLTcCM8V1BBMIvBqSAPoPN7G3Cn8hldxA
24.09.2015 17:53:32 DEBUG     HOSTER ZippyshareCom[32]: LOAD URL http://www.google.com/recaptcha/api2/demo | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
24.09.2015 17:53:32 DEBUG     CAPTCHA ZippyshareCom[32]: ReCaptcha | Time: 1443117212382
24.09.2015 17:53:32 DEBUG     CAPTCHA ZippyshareCom[32]: ReCaptcha | Rpc-token: 20629621
24.09.2015 17:53:32 DEBUG     HOSTER ZippyshareCom[32]: LOAD URL https://www.google.com/recaptcha/api2/anchor | cookies=True | get={'parent': u'http:///www64.zippyshare.com', 'hl': u'fr', 'v': u'r20150915103233', 'rpctoken': 20629621, 'k': u'6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq', 'usegapi': '1', 'jsh': u'm;/_/scs/apps-static/_/js/k=oz.gapi.nl._YmkBCSndSI.O/m=__features__/am=AQ/rt=j/d=1/t=zcms/rs=AGLTcCM8V1BBMIvBqSAPoPN7G3Cn8hldxA#id=IO_1443117212382', 'pfname': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
24.09.2015 17:53:32 DEBUG     HOSTER ZippyshareCom[32]: Config option `premium_fallback` not found, use default `True`
24.09.2015 17:53:32 WARNING   Download failed: DLIA-CFTS30.part07.rar | Parse error: 'NoneType' object has no attribute 'group' | Plugin may be out of date
24.09.2015 17:53:32 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: DLIA-CFTS30.part07.rar (pid:13)
24.09.2015 17:53:32 INFO      ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
I tried the URL and actually got the issue described in #1861.
After updating with pr #1867, the download worked fine..
Please try also

**Comment by spam8117** [comment]
Hi,
It seems to not work. I got the following log after replacing the ZippyshareCom.py manually in the modules/hoster directory. 
Do you have any idea why I always get the "old" version even if I delete and re-install pyload from pyload-git?

28.09.2015 20:22:13 INFO Download starts: DLIA-CFTS30.part07.rar
28.09.2015 20:22:13 DEBUG ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
28.09.2015 20:22:13 DEBUG ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
28.09.2015 20:22:13 DEBUG HOSTER ZippyshareCom[1]: PROCESS URL http://www64.zippyshare.com/v/TmOvYMQj/file.html | PLUGIN VERSION 0.83
28.09.2015 20:22:13 INFO HOSTER ZippyshareCom[1]: Updating file info...
28.09.2015 20:22:13 DEBUG HOSTER ZippyshareCom[1]: File info: {'status': 2, 'url': u'http://www64.zippyshare.com/v/TmOvYMQj/file.html', 'size': 209715200.0, 'name': u'DLIA-CFTS30.part07.rar', 'pattern': {'S': u'200', 'U': u'MB', 'KEY': u'TmOvYMQj', 'N': u'DLIA-CFTS30.part07.rar'}}
28.09.2015 20:22:13 DEBUG HOSTER ZippyshareCom[1]: Previous file info: {}
28.09.2015 20:22:13 INFO HOSTER ZippyshareCom[1]: File name: DLIA-CFTS30.part07.rar
28.09.2015 20:22:13 INFO HOSTER ZippyshareCom[1]: File size: 209715200 bytes
28.09.2015 20:22:13 INFO HOSTER ZippyshareCom[1]: File status: online
28.09.2015 20:22:13 DEBUG HOSTER ZippyshareCom[1]: LOAD URL http://www64.zippyshare.com/v/TmOvYMQj/file.html | cookies=[('zippyshare.com', 'ziplocale', 'en')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
28.09.2015 20:22:13 INFO HOSTER ZippyshareCom[1]: Processing as free download...
28.09.2015 20:22:13 DEBUG CAPTCHA ZippyshareCom[1]: ReCaptcha | Key: 6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq
28.09.2015 20:22:13 DEBUG CAPTCHA ZippyshareCom[1]: ReCaptcha | Key: 6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq
28.09.2015 20:22:13 DEBUG HOSTER ZippyshareCom[1]: LOAD URL http://www.google.com/recaptcha/api.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.09.2015 20:22:13 DEBUG CAPTCHA ZippyshareCom[1]: ReCaptcha | API version: r20150922132346
28.09.2015 20:22:13 DEBUG CAPTCHA ZippyshareCom[1]: ReCaptcha | API language: fr
28.09.2015 20:22:13 DEBUG HOSTER ZippyshareCom[1]: LOAD URL https://apis.google.com/js/api.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.09.2015 20:22:13 DEBUG CAPTCHA ZippyshareCom[1]: ReCaptcha | API jsh-string: m;//scs/apps-static//js/k=oz.gapi.nl.TD-NpswIL4E.O/m=features/am=AQ/rt=j/d=1/t=zcms/rs=AGLTcCNNo4calicrWHpHJibuMbOzdFcmjw
28.09.2015 20:22:13 DEBUG HOSTER ZippyshareCom[1]: LOAD URL http://www.google.com/recaptcha/api2/demo | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.09.2015 20:22:13 DEBUG CAPTCHA ZippyshareCom[1]: ReCaptcha | Time: 1443471733770
28.09.2015 20:22:13 DEBUG CAPTCHA ZippyshareCom[1]: ReCaptcha | Rpc-token: 51604545
28.09.2015 20:22:13 DEBUG HOSTER ZippyshareCom[1]: LOAD URL https://www.google.com/recaptcha/api2/anchor | cookies=True | get={'parent': u'http:///www64.zippyshare.com', 'hl': u'fr', 'v': u'r20150922132346', 'rpctoken': 51604545, 'k': u'6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq', 'usegapi': '1', 'jsh': u'm;//scs/apps-static//js/k=oz.gapi.nl.TD-NpswIL4E.O/m=features/am=AQ/rt=j/d=1/t=zcms/rs=AGLTcCNNo4calicrWHpHJibuMbOzdFcmjw#id=IO_1443471733770', 'pfname': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.09.2015 20:22:13 DEBUG HOSTER ZippyshareCom[1]: Config option premium_fallback not found, use default True
28.09.2015 20:22:13 WARNING Download failed: DLIA-CFTS30.part07.rar | Parse error: 'NoneType' object has no attribute 'group' | Plugin may be out of date
28.09.2015 20:22:13 INFO ADDON UnSkipOnFail: Looking for skipped duplicates of: DLIA-CFTS30.part07.rar (pid:1)
28.09.2015 20:22:13 INFO ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
you should update `userplugins/hoster` not `modules/hoster` directory

**Comment by GammaC0de** [comment]
From your log it seems that the problem is that it fails because of Recaptcha v2 which `pyLoad` does not support (see #1484).
from my experience, after some time zippy stops asking for captcha

**Comment by spam8117** [comment]
Now I tried with ImageTyperz (probably the same problem though), please see attached log.
My userplugins/hoster directory is empty (why?). Thanks for your help.

28.09.2015 20:56:51 DEBUG     Plugin loaded: ImageTyperz
28.09.2015 20:57:03 INFO      Download starts: DLIA-CFTS30.part07.rar
28.09.2015 20:57:03 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
28.09.2015 20:57:03 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
28.09.2015 20:57:03 DEBUG     HOSTER ZippyshareCom[1]: PROCESS URL http://www64.zippyshare.com/v/TmOvYMQj/file.html | PLUGIN VERSION 0.83
28.09.2015 20:57:03 INFO      HOSTER ZippyshareCom[1]: Updating file info...
28.09.2015 20:57:03 DEBUG     HOSTER ZippyshareCom[1]: File info: {'status': 2, 'url': u'http://www64.zippyshare.com/v/TmOvYMQj/file.html', 'size': 209715200.0, 'name': u'DLIA-CFTS30.part07.rar', 'pattern': {'S': u'200', 'U': u'MB', 'KEY': u'TmOvYMQj', 'N': u'DLIA-CFTS30.part07.rar'}}
28.09.2015 20:57:03 DEBUG     HOSTER ZippyshareCom[1]: Previous file info: {}
28.09.2015 20:57:03 INFO      HOSTER ZippyshareCom[1]: File name: DLIA-CFTS30.part07.rar
28.09.2015 20:57:03 INFO      HOSTER ZippyshareCom[1]: File size: 209715200 bytes
28.09.2015 20:57:03 INFO      HOSTER ZippyshareCom[1]: File status: online
28.09.2015 20:57:03 DEBUG     HOSTER ZippyshareCom[1]: LOAD URL http://www64.zippyshare.com/v/TmOvYMQj/file.html | cookies=[('zippyshare.com', 'ziplocale', 'en')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
28.09.2015 20:57:03 INFO      HOSTER ZippyshareCom[1]: Processing as free download...
28.09.2015 20:57:03 DEBUG     CAPTCHA ZippyshareCom[1]: ReCaptcha | Key: 6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq
28.09.2015 20:57:03 DEBUG     CAPTCHA ZippyshareCom[1]: ReCaptcha | Key: 6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq
28.09.2015 20:57:03 DEBUG     HOSTER ZippyshareCom[1]: LOAD URL http://www.google.com/recaptcha/api.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.09.2015 20:57:03 DEBUG     CAPTCHA ZippyshareCom[1]: ReCaptcha | API version: r20150922132346
28.09.2015 20:57:03 DEBUG     CAPTCHA ZippyshareCom[1]: ReCaptcha | API language: fr
28.09.2015 20:57:03 DEBUG     HOSTER ZippyshareCom[1]: LOAD URL https://apis.google.com/js/api.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.09.2015 20:57:03 DEBUG     CAPTCHA ZippyshareCom[1]: ReCaptcha | API jsh-string: m;/_/scs/apps-static/_/js/k=oz.gapi.nl.TD-NpswIL4E.O/m=__features__/am=AQ/rt=j/d=1/t=zcms/rs=AGLTcCNNo4calicrWHpHJibuMbOzdFcmjw
28.09.2015 20:57:03 DEBUG     HOSTER ZippyshareCom[1]: LOAD URL http://www.google.com/recaptcha/api2/demo | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.09.2015 20:57:03 DEBUG     CAPTCHA ZippyshareCom[1]: ReCaptcha | Time: 1443473823711
28.09.2015 20:57:03 DEBUG     CAPTCHA ZippyshareCom[1]: ReCaptcha | Rpc-token: 51494634
28.09.2015 20:57:03 DEBUG     HOSTER ZippyshareCom[1]: LOAD URL https://www.google.com/recaptcha/api2/anchor | cookies=True | get={'parent': u'http:///www64.zippyshare.com', 'hl': u'fr', 'v': u'r20150922132346', 'rpctoken': 51494634, 'k': u'6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq', 'usegapi': '1', 'jsh': u'm;/_/scs/apps-static/_/js/k=oz.gapi.nl.TD-NpswIL4E.O/m=__features__/am=AQ/rt=j/d=1/t=zcms/rs=AGLTcCNNo4calicrWHpHJibuMbOzdFcmjw#id=IO_1443473823711', 'pfname': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.09.2015 20:57:03 DEBUG     HOSTER ZippyshareCom[1]: Config option `premium_fallback` not found, use default `True`
28.09.2015 20:57:03 WARNING   Download failed: DLIA-CFTS30.part07.rar | Parse error: 'NoneType' object has no attribute 'group' | Plugin may be out of date
28.09.2015 20:57:03 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: DLIA-CFTS30.part07.rar (pid:1)
28.09.2015 20:57:03 INFO      ADDON UnSkipOnFail: No duplicates found
28.09.2015 20:57:03 DEBUG     All downloads processed

**Comment by GammaC0de** [comment]
`pyLoad` does not support ReCaptcha v2 with or without a captcha service.

as for "proper" installation of `pyLoad`:
* get `pyLoad` for your OS from https://github.com/pyload/pyload/releases
* replace the `modules/UpdateManager.py` file  with this one: https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py
* Start `pyLoad`
* Wait for update to finish
* Wacth the log - you may have to manually restart `pyLoad` for `UpdateManager` finish its job
