### ISSUE TITLE
EasybytezCom: 'bool' object has no attribute 'select'

### ISSUE THREAD

**Issue by darkpella** [pyload/pyload#1864]
issue #1852 seems gone now, but now I get the following:
 
697	24.09.2015 21:23:22	WARNING	HOOK EasybytezCom: 'bool' object has no attribute 'select' | Waiting 1 minute and retry
698	24.09.2015 21:23:41	INFO	Download starts: xxxxx.part14.rar
699	24.09.2015 21:23:41	INFO	HOSTER EasybytezCom[1265]: Updating file info...
700	24.09.2015 21:24:11	INFO	HOSTER EasybytezCom[1265]: File name: xxxxx.part14.rar
701	24.09.2015 21:24:11	INFO	HOSTER EasybytezCom[1265]: File size: 525336576 bytes
702	24.09.2015 21:24:11	INFO	HOSTER EasybytezCom[1265]: File status: queued
703	24.09.2015 21:24:22	WARNING	HOOK EasybytezCom: 'bool' object has no attribute 'select' | Waiting 1 minute and retry

**Comment by FabrizioA** [comment]
same for me

**Comment by vuolter** [comment]
Fixed.
