### ISSUE TITLE
HundredEightyUploadCom not downloading file

### ISSUE THREAD

**Issue by vilorious** [pyload/pyload#1865]
download creates just 162 B file. Captcha is working, it does show correct filesize and it starts downloading but it doesn´t download.

**Comment by joberreiter** [comment]
Without debug log or error message, we have to switch on our 'mighty crystal ball of fortune-telling' -- but it have to be cleaned prior to use ...
Alright? ;-)

**Comment by vilorious** [comment]
Iam so sorry. I thought your crystal ball is in better shape :P 
Can HundredEightyUploadCom detect Iam using pyload and give me fakefile?

Well I dont find anything in in debug log (but yeah Iam not the best with that stuff). Thank you very much for looking into it!!!

My debug log:

>25.09.2015 16:36:55	INFO	Added package 180upload.com containing 1 links
548	25.09.2015 16:36:55	DEBUG	Fetched 1 values from cache for HundredEightyUploadCom
549	25.09.2015 16:36:55	DEBUG	Finished Info Fetching for HundredEightyUploadCom
550	25.09.2015 16:36:57	INFO	Download starts: How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv
551	25.09.2015 16:36:57	DEBUG	HundredEightyUploadCom: Update file info...
552	25.09.2015 16:36:57	DEBUG	HundredEightyUploadCom: Previous file info: {}
553	25.09.2015 16:36:57	DEBUG	HundredEightyUploadCom: Current file info: {'status': 2, 'url': u'http://180upload.com/7rnhn24voya7', 'size': 810863820.8, 'name': u'How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv', 'pattern': {'S': u'773.3', 'U': u'MB', 'N': u'How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv'}}
554	25.09.2015 16:36:57	DEBUG	HundredEightyUploadCom: File name: How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv | File size: 810863820
555	25.09.2015 16:36:57	DEBUG	HundredEightyUploadCom: File status: online
556	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: Update file info...
557	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: Previous file info: {'status': 2, 'url': u'http://180upload.com/7rnhn24voya7', 'size': 810863820.8, 'name': u'How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv', 'pattern': {'S': u'773.3', 'U': u'MB', 'N': u'How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv'}}
558	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: Current file info: {'status': 2, 'name': u'How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv', 'url': u'http://180upload.com/7rnhn24voya7', 'pattern': {'S': u'773.3', 'U': u'MB', 'N': u'How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv'}, 'size': 810863820.8}
559	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: File name: How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv | File size: 810863820
560	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: Update file info...
561	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: Previous file info: {'status': 2, 'name': u'How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv', 'url': u'http://180upload.com/7rnhn24voya7', 'pattern': {'S': u'773.3', 'U': u'MB', 'N': u'How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv'}, 'size': 810863820.8}
562	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: Current file info: {'status': 2, 'name': u'How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv', 'url': u'http://180upload.com/7rnhn24voya7', 'pattern': {'S': u'773.3', 'U': u'MB', 'N': u'How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv'}, 'size': 810863820.8}
563	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: File name: How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv | File size: 810863820
564	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: File status: online
565	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: Handled as free download
566	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: Getting download link: #1
567	25.09.2015 16:36:58	DEBUG	HundredEightyUploadCom: {u'rand': u't5ooqc5535tbiw7jiauzb2vydtscuk2svcmje5i', u'method_premium': '', u'adcopy_response': u'manual_challenge', u'down_direct': u'1', u'referer': '', u'adcopy_challenge': u'\n ', u'method_free': '', u'id': u'7rnhn24voya7', u'op': u'download2'}
568	25.09.2015 16:36:59	DEBUG	ReCaptcha: Key not found
569	25.09.2015 16:36:59	DEBUG	SolveMedia: Key: key
570	25.09.2015 16:36:59	DEBUG	SolveMedia: Challenge: solvekey
571	25.09.2015 16:37:12	DEBUG	Received captcha result: new york city
572	25.09.2015 16:37:12	DEBUG	SolveMedia: Result: new york city
573	25.09.2015 16:37:14	DEBUG	Download Check triggered
574	25.09.2015 16:37:14	INFO	Download finished: How.to.Get.Away.with.Murder.S02E01.720p.HDTV.X264-DIMENSION.mkv
575	25.09.2015 16:37:14	INFO	Package finished: 180upload.com
576	25.09.2015 16:37:14	DEBUG	All downloads processed
577	25.09.2015 16:37:14	DEBUG	ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
578	25.09.2015 16:37:14	INFO	ExtractArchive: Check package: 180upload.com
579	25.09.2015 16:37:15	DEBUG	All downloads finished
580	25.09.2015 16:37:15	DEBUG	ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
581	25.09.2015 16:37:15	INFO	ExtractArchive: Check package: 180upload.com
582	25.09.2015 16:37:15	INFO	ExtractArchive: No files found to extract
583	25.09.2015 16:37:15	INFO	ExtractArchive: No files found to extract

**Comment by joberreiter** [comment]
Can you post the content of the 162 byte file also?

**Comment by vilorious** [comment]
of course, didn´t know it´s a textfile... have to learn a lot :p

Content of 162 byte file created when downloading file from HundredEightyUploadCom:

`<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>`

**Comment by joberreiter** [comment]
I think it is related to #1852, I have a fix for it, but this doesn't solve the whole problem. Please be patient, nedd to hear what vuolter or GammaC0de had to say about it.

**Comment by vilorious** [comment]
thx a lot, of course no rush, Iam very happy if someone is looking into it!
