### ISSUE TITLE
unable to run pyload stuck on ClickAndLoad: Proxy listening on 127.0.0.1:9666

### ISSUE THREAD

**Issue by ifro4u** [pyload/pyload#1868]
i installed properly and configure it .
but when i run pyloadcore i got stuck at this point
here is log

root@ASUS:~# pyLoadCore
24.09.2015 20:47:01 INFO      Starting pyLoad 0.4.9
24.09.2015 20:47:01 INFO      Using home directory: /opt/share/pyload_config
24.09.2015 20:47:12 INFO      Activated plugins: AntiStandby, ClickAndLoad, ExternalScripts, ExtractArchive, LinkdecrypterComHook, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
24.09.2015 20:47:12 INFO      Deactivate plugins: AlldebridComHook, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, TransmissionRPC, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
24.09.2015 20:47:12 INFO      Downloadtime: True
24.09.2015 20:47:12 INFO      Starting ThriftBackend: 0.0.0.0:7227
24.09.2015 20:47:16 INFO      Free space: 3.36 GiB
24.09.2015 20:47:16 INFO      Starting builtin webserver: 0.0.0.0:8000
24.09.2015 20:47:17 INFO      Activating Accounts...
24.09.2015 20:47:17 INFO      Activating Plugins...
24.09.2015 20:47:17 WARNING   ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
24.09.2015 20:47:17 WARNING   ADDON AntiStandby: Unable to change display power state | [Errno 2] No such file or directory
24.09.2015 20:47:17 INFO      HOOK XFileSharingPro: Handling any hoster I can!
24.09.2015 20:47:17 INFO      HOOK XFileSharingPro: Handling any crypter I can!
24.09.2015 20:47:17 INFO      pyLoad is up and running
24.09.2015 20:47:18 INFO      ADDON UpdateManager: No new pyLoad version available
24.09.2015 20:47:19 INFO      ADDON UpdateManager: No plugin updates available
24.09.2015 20:47:19 INFO      HOOK LinkdecrypterCom: Reloading supported crypter list
24.09.2015 20:47:22 INFO      HOOK LinkdecrypterCom: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
24.09.2015 20:47:23 INFO      HOOK LinkdecrypterCom: Reloading supported crypter list
24.09.2015 20:47:26 INFO      HOOK LinkdecrypterCom: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
24.09.2015 20:47:27 INFO      ADDON ClickAndLoad: Proxy listening on 127.0.0.1:9666

after some time i got bus error

**Comment by ifro4u** [comment]
i did try replacing pyload stable folder 
it messes everything nothing work then

**Comment by joberreiter** [comment]
I'm assuming your platform is Unix:
Delete/uninstall previous pyload installations, start over with a fresh install of the stable branch, e.g.
```shell
mkdir /opt/pyload && cd /opt/pyload
git clone https://github.com/pyload/pyload.git -b stable --single-branch .
```
Then go through the setup procedure and specify your existent config dir.

**Comment by ifro4u** [comment]
any help

**Comment by joberreiter** [comment]
I'm sorry, I've never tried to install it on ddwrt, so I'm unable to help with that.

But you haven't enabled debug mode, which can be of help here.
Normally you would enable it at the config page of the WebUI, but if you experience login problems try to
- stop all running pyload instances
- edit `pyload.conf` in your cnfig directory, looking for:
```
general - "General":
    ...
    bool debug_mode : "Debug Mode" = True
    ...
```
- restart pyLoad
