### ISSUE TITLE
AntiStandby: Error executing periodical task: 'ascii'

### ISSUE THREAD

**Issue by SebaBoler** [pyload/pyload#1869]
When i start downloading any file i get information 

1   25.09.2015 09:35:36 ERROR   ADDON AntiStandby: Error executing periodical task: 'ascii' codec can't decode byte 0xa9 in position 6: ordinal not in range(128)

**Comment by Bambie42** [comment]
Enable debug log and post it here please.

**Comment by aronze06** [comment]
Same issue like you ! Do you solve your pb ?
Thx !
Alexis

**Comment by SebaBoler** [comment]
i just uninstall all. Clear data and install again. Works !!

**Comment by aronze06** [comment]
Thx for your answer, I'll try that!

**Comment by aronze06** [comment]
No, my problem is not solved despite uninstall :(

**Comment by vuolter** [comment]
Please retry now.
