### ISSUE TITLE
keep2share - Captcha | Invalid captcha ---> Parse error: Free download link not found.

### ISSUE THREAD

**Issue by kveiro** [pyload/pyload#1871]
Hi, 
plugin version is .25
Probably plugin doesnt work due error with sending back of typed captcha.
I have typed captcha right - tried many times, but every time i got error in debug report,
w/o request of new captcha again. 

24.09.2015 16:43:47   DEBUG    HOSTER Keep2ShareCc[76]: File info: {'status': 2, 'url': u'http://keep2s.cc/file/8316ffe3db3e4', 'size': 367001600.0, 'name': u'Dark.Matter.S01E01.rus.LostFilm.avi', 'pattern': {'S': u'350.0 MB', 'ID': u'8316ffe3db3e4', 'N': u'Dark.Matter.S01E01.rus.LostFilm.avi'}}
2   24.09.2015 16:43:47   DEBUG    HOSTER Keep2ShareCc[76]: Previous file info: {}
3   24.09.2015 16:43:47   INFO    HOSTER Keep2ShareCc[76]: File name: Dark.Matter.S01E01.rus.LostFilm.avi
4   24.09.2015 16:43:47   INFO    HOSTER Keep2ShareCc[76]: File size: 367001600 bytes
5   24.09.2015 16:43:47   INFO    HOSTER Keep2ShareCc[76]: File status: online
6   24.09.2015 16:43:47   DEBUG    HOSTER Keep2ShareCc[76]: LOAD URL http://keep2s.cc/file/8316ffe3db3e4 | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
7   24.09.2015 16:43:48   INFO    HOSTER Keep2ShareCc[76]: Processing as free download...
8   24.09.2015 16:43:48   DEBUG    HOSTER Keep2ShareCc[76]: LOAD URL http://keep2s.cc/file/8316ffe3db3e4 | cookies=True | get={} | req=None | decode=True | multipart=False | post={'slow_id': u'88a5af4ae8627', 'yt0': ''} | ref=True | just_header=False
9   24.09.2015 16:43:48   DEBUG    HOSTER Keep2ShareCc[76]: captcha-form found <_sre.SRE_Match object at 0x031ADA60>
10   24.09.2015 16:43:48   DEBUG    HOSTER Keep2ShareCc[76]: CAPTCHA_PATTERN found <_sre.SRE_Match object at 0x031AD9A0>
11   24.09.2015 16:43:48   DEBUG    CAPTCHA Keep2ShareCc[76]: Captcha | LOAD URL http://keep2s.cc/file/captcha.html?v=56040c1ebf9e0 | cookies=True | get={} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
12   24.09.2015 16:44:01   DEBUG    HOSTER Keep2ShareCc[76]: LOAD URL http://keep2s.cc/file/8316ffe3db3e4 | cookies=True | get={} | req=None | decode=True | multipart=False | post={'CaptchaForm[code]': 'xsnnlr', 'yt0': '', 'freeDownloadRequest': 1, 'uniqueId': u'88a5af4ae8627', 'free': 1} | ref=True | just_header=False
13   24.09.2015 16:44:02   ERROR    CAPTCHA Keep2ShareCc[76]: Captcha | Invalid captcha
14   24.09.2015 16:44:02   INFO    HOSTER Keep2ShareCc[76]: Waiting 31 seconds...
15   24.09.2015 16:44:02   DEBUG    HOSTER Keep2ShareCc[76]: Previous waitUntil: 0.000000
16   24.09.2015 16:44:34   DEBUG    HOSTER Keep2ShareCc[76]: LOAD URL http://keep2s.cc/file/8316ffe3db3e4 | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
17   24.09.2015 16:44:34   DEBUG    HOSTER Keep2ShareCc[76]: Config option `premium_fallback` not found, use default `True`
18   24.09.2015 16:44:34   WARNING    Download failed: Dark.Matter.S01E01.rus.LostFilm.avi | Parse error: Free download link not found | Plugin may be out of date
19   24.09.2015 16:44:34   INFO    ADDON UnSkipOnFail: Looking for skipped duplicates of: Dark.Matter.S01E01.rus.LostFilm.avi (pid:76)
20   24.09.2015 16:44:34   INFO    ADDON UnSkipOnFail: No duplicates found
21   24.09.2015 16:44:34   DEBUG    All downloads processed

**Comment by sraedler** [comment]
keep2share is working, I checked...

please close
