### ISSUE TITLE
question about fixurl function

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1873]
@vuolter what is the purpose of the `fixurl` function? thx

**Comment by joberreiter** [comment]
My _guess_:
If one has only a relative url, e.g. `/image/xyz.gif`, then fixurl extracts scheme (`http`) and netloc (`hoster.com`) from a baseurl (`http://hoster.com/linkid`) and put it all together to get
`http://hoster.com/image/xyz.gif' ...

If this is correct, maybe it would be more decriptive if it is renamed in v0.4.10 to `get_full_qualified_url()` or similar?

**Comment by GammaC0de** [comment]
This was my guess also but I wanted to ask to be sure
because if you use `fixurl("../img/favico.jpg")` you would get `http://domain.com/../img/favico.jpg` which is of-course a bug

**Comment by joberreiter** [comment]
@vuolter
Are you able of answering this, instead of just labeling it as question?

**Comment by GammaC0de** [comment]
:+1:

**Comment by vuolter** [comment]
The **Plugin** `fixurl` function simply "decode" a given url, stripping whitespaces, unquoting it and removing any escape character.
The **Base** `fixurl` method, plus all of that, rebuild an incomplete url using the netloc of the pyfile.url.

**Comment by GammaC0de** [comment]
@vuolter I asked this question in the first place because I **did** found it in `FilecryptCc` (although for captcha, not downloading):

e.g '../captcha/captcha.php?namespace=container' in `http://filecrypt.cc/Container/3193DFCBF5.html`:
```html

<div class="content">
	<div class="box">
		<h2 class="safety">Sicherheitsabfrage</h2>
		<div class="safety">
			<form action="" onsubmit="try {} catch(e) {}" method="post">
				<div id="recaptcha_widget" >
      <div class="other" id="recaptcha_image">
      <img id="nc" src="../captcha/captcha.php?namespace=container" /></div>
      <input type="text" id="recaptcha_response_field" name="recaptcha_response_field" autocomplete="off" placeholder="Captcha eingeben" tabindex="1" value="">
      <span><a href="#" onclick="try{$('nc').writeAttribute('src', '../captcha/captcha.php?namespace=container&c='+new Date())}catch(e){}; return false;">Anderes Captcha anzeigen</a></span>
      <button type="submit">
        Bestätigen
      </button>
    </div>			</form>
		</div>
	</div>

</div>
```
