### ISSUE TITLE
After 'object has no attribute 'user'", ShareonlineBiz Premium doenst work - download start as free user

### ISSUE THREAD

**Issue by maddyxp** [pyload/pyload#1874]
It seems the problem is some testing code.
ShareonlineBiz Premium account does not work anymore.
5 Days ago it starts with the Problem "object has no attribute 'user'".
So i tried to set up my whole system, because i was sure i made a mistake.
5 Days of frustationg work... i didnt get it work.
Since today i'm back to Sha 5e15580202c44628f2fbfabad0c3f693975fb3c9
I'm happy at the moment, because i investigated so much time,
at least i know some new things about git :-)
I disabled the UpdateManager.
But i hope you get it back to work at the stable branch.
Thx for your good work guys!

**Comment by shortzzz** [comment]
Thanks for your Solution. This Revision helped me to get pyload running aggain.

Here are my steps to get pyLoad Running with this Revision:

**First Disable your Plugin Manager**
Config > Plugins > Update Manager
> Auto-restart pyLoad when required:			off
Check interval in hours: 					10000000000000
Check for updates periodically: 			off
Activated: 									off
Don't update plugins in debug mode: 		off
Monitor plugin code changes in debug mode: 	off
Check for updates on startup: 				off

**The Following has to be done in a terminal:**
pyLoadCore --quit

```
cd ~/
rm -R pyload201508/
mkdir pyload201508
cd pyload201508/

wget https://github.com/pyload/pyload/archive/5e15580202c44628f2fbfabad0c3f693975fb3c9.zip
unzip *.zip
mv pyload* pyload

sudo -s
rm -R /usr/share/pyload
mv pyload/ /usr/share/

exit

cd /usr/share/pyload/
./pyLoadCore.py --daemon
```

**Comment by joberreiter** [comment]
"object has no attribute 'user'" is fixed with #1863, but has to be merged.

**Comment by maddyxp** [comment]
Im now back one step more(13 days old version), because the downloads stopped after ~30 minutes.
If you are using pyload git version, you can  do this:
cd /pyloadfolder/
.pyLoadCore --quit
git checkout 36e54a3ee89aafeffdc7eab789502decf11ca2ac
rm module/plugins/hooks/UpdateManager.py (to be safe for Updates)
./pyLoadCore.py --daemon

**Comment by vuolter** [comment]
Fixed.
