### ISSUE TITLE
RealDebrid Plugin returning "Required account not found" warning

### ISSUE THREAD

**Issue by chaosmaker** [pyload/pyload#1875]
Hi All,

So apparently pyload is now completely broken... I have reset it but the current "stable" branch is completely useless.
When I try and download with RealDebrid I just get a "Required Account not found" warning and that's it.

```
26.09.2015 16:58:28 INFO      Download starts: x.mkv
26.09.2015 16:58:28 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
26.09.2015 16:58:28 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
26.09.2015 16:58:28 DEBUG     HOSTER RealdebridCom[44]: RealdebridCom | PROCESS URL http://x/x/x.mkv | PLUGIN VERSION 0.69
26.09.2015 16:58:28 WARNING   Download failed: x.mkv | Required account not found
26.09.2015 16:58:28 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: x.mkv (pid:11)
26.09.2015 16:58:28 INFO      ADDON UnSkipOnFail: No duplicates found
26.09.2015 16:58:28 DEBUG     All downloads processed
```

**Comment by buschdeluxe** [comment]
I get the same "Required account not found" warning with debriditalia.com

**Comment by damien599901** [comment]
I get the same ""Required account not found" warning with https://www.alldebrid.fr/

**Comment by funkyslap** [comment]
Guys, mationic@5f9d6f9 it works with RealDebrid

**Comment by damien599901** [comment]
great but could you explain to a newbie (me) how to proceed ? (the linux
commands please)

2015-09-27 18:10 GMT+02:00 funkyslap <notifications@github.com>:

**Comment by chaosmaker** [comment]
Yes mationic@5f9d6f9 seems to be working although I can only get 1 download at a time to work

**Comment by vuolter** [comment]
Retry now.

**Comment by chaosmaker** [comment]
Still a problem on my system... and I just deleted and updated all userscripts...

**Comment by chaosmaker** [comment]
Actually it just refreshes the account info like a million times...

**Comment by Velociraptor85** [comment]
@chaosmaker does this problem still exist? If not please close the issue

**Comment by Velociraptor85** [comment]
@GammaC0de I think this can be closed =?

**Comment by GammaC0de** [comment]
RealDebrid works fine.
