### ISSUE TITLE
easybytez.com Not working yet

### ISSUE THREAD

**Issue by smystero** [pyload/pyload#1879]
Hi,
Since  last update (one week ago) easybytez still Not working (lots of issue like #1833, #1860, #1852)
When do You plan to solve this?
How to go Back To A working revision? 
Thanks a Lot.

**Comment by lorenzobb** [comment]
Agree! Stable release is not stable! i tried, fix issue #1853, Fix for #1852 but even if my premium account is recognized, pyload only download first file then it stops with no error message.
thanks for your help!

**Comment by smystero** [comment]
Same for me.
I don't know what's happened but usually the problems are fixed without manually fixing code, but updating plugins. 
It seems nobody commits the changes to the "stable" repository...
Also, I would like to know why is not possible to go back to a working version like a week ago.
Thanls

**Comment by smystero** [comment]
Hi,
some one in the forum suggests to manually install a working version downloading it from this link:
https://github.com/pyload/pyload/archive/fa6704b50b8b98288f344f7b9051938ef32e0325.zip
This is the forum link with the suggested steps: 
http://forum.pyload.org/viewtopic.php?f=12&t=4545&start=20
Anyone has checked?
Thanks

**Comment by FabrizioA** [comment]
I've checked now, I can confirm that it works! 
I've removed the .pyload config folder and deactivate the Update Manager before run pyload.

**Comment by lorenzobb** [comment]
Working for me too. Thanks to all.

**Comment by damien599901** [comment]
how to proceed with ipkg ? 
could somebody help me please?
thank you
