### ISSUE TITLE
ShareonlineBiz premium not working

### ISSUE THREAD

**Issue by Floyddotnet** [pyload/pyload#1881]
PyLoad-Version: origin/stable 948e0cc21ea369a6661a3b6154374a09c1f7251f (current newest version)

Log:

    218	28.09.2015 00:43:10	INFO	ACCOUNT ShareonlineBiz: Login user XXX...
    219	28.09.2015 00:43:10	INFO	ACCOUNT ShareonlineBiz: Parsing account info for user XXX...
    224	28.09.2015 00:43:10	INFO	pyLoad is up and running
    225	28.09.2015 00:43:11	INFO	ADDON UpdateManager: No new pyLoad version available
    226	28.09.2015 00:43:11	INFO	ADDON UpdateManager: No plugin updates available
    
    242	28.09.2015 00:45:19	INFO	Download starts: cb9e402c2cf09907fb76631d4e930fb8.part05.rar
    243	28.09.2015 00:45:19	INFO	HOSTER ShareonlineBiz[6]: Updating file info...
    244	28.09.2015 00:45:19	INFO	HOSTER ShareonlineBiz[6]: File name: cb9e402c2cf09907fb76631d4e930fb8.part05.rar
    245	28.09.2015 00:45:19	INFO	HOSTER ShareonlineBiz[6]: File size: 157286400 bytes
    246	28.09.2015 00:45:19	INFO	HOSTER ShareonlineBiz[6]: File status: online
    247	28.09.2015 00:45:19	INFO	HOSTER ShareonlineBiz[6]: Processing as free download...
    248	28.09.2015 00:45:19	INFO	HOSTER ShareonlineBiz[6]: Waiting 3 seconds...

**Comment by GammaC0de** [comment]
duplicate #1866

**Comment by Floyddotnet** [comment]
https://github.com/pyload/pyload/pull/1863 is the right solution:

apply this changes solve it for me:

https://github.com/mationic/pyload/commit/5f9d6f992cb889379dd02fe71fe8c5a4b149fc44
https://github.com/mationic/pyload/commit/3b54dce909e07fbc6668c1e1cf19b9d25b61e195
https://github.com/mationic/pyload/commit/44b65e8f1ea367e00da1638e0362f9443b57e760
