### ISSUE TITLE
DebridItalia.com premium account | Required account not found

### ISSUE THREAD

**Issue by xSunshin3x** [pyload/pyload#1887]
Hey guys,

i recently (re-)installed pyload 0.4.9 on my raspberry running raspbian after i had some major problems with the UpdateManager and a non-working pyload-installation.
After the setup and configuration, i updated all plugins via UpdateManager.

When im trying to download some files, e.g. from Uploaded.net or ShareOnline.biz, i instantly get the error-message 

WARNING	Download failed: {URL} | Required account not found

even tough i succesfully added my DebridItalia-account to settings->accounts (valid and premium active) and the DebridItaliaComHook plugin is activated and running.

(userplugins/hook/)DebridItaliaComHook.py is on version 0.13 and (userplugins/hoster/)DebridItaliaCom.py is on version 0.19, meaning both should be up2date.

Do you know what's the issue here?

Regards,

Sun

**Comment by kasjak2000** [comment]
Hello all,
I have the same prob with PyLoadCore and Debriditalia:

29.09.2015 16:15:04 INFO      Download starts: http://ul.to/awvcfqvx
29.09.2015 16:15:04 WARNING   Download failed: http://ul.to/awvcfqvx | Required account not found
29.09.2015 16:15:04 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: http://ul.to/awvcfqvx (pid:27)

Thanx.

**Comment by joberreiter** [comment]
Seems to be fixed with #1863, but not yet committed.

**Comment by xSunshin3x** [comment]
thanks joberreiter.
i saw  #1863 before, but unluckily i can't find a file named Hoster.py in my pyload directories..neither in /usr/share/pyload, nor in /home/user/.pyload.

Sun
