### ISSUE TITLE
Share Online Premium not working

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1888]
Even with a premium account it loads as free user.

A fix would be really great.

**Comment by wastez** [comment]
I used this fix to get it working again: https://github.com/pyload/pyload/pull/1863

Would be great if somebody could merge it.

**Comment by joberreiter** [comment]
Is voulter the only one that can do this?
It seems that he is absent most of the time, and return for a short period only every couple of days ...

**Comment by damien599901** [comment]
who is Voulter? the boss? the creator of pyload? 
pyLoad is an incredible app. i hope see it work again. 
where can we do a donation to Voulter or for the Pyload's team 

cheers
Damien599901

**Comment by R3alflash** [comment]
i get a new issue:

Download failed: xxxxx.part12.rar | get_data() got an unexpected keyword argument 'refresh'
982	30.09.2015 06:55:02	DEBUG	Error creating zip file: 'ascii' codec can't decode byte 0xe1 in position 10: ordinal not in range(128)

Some ideas?

**Comment by crazy06** [comment]
same probleme here:

INFO	HOSTER ShareonlineBiz[5591]: Looking for direct download link...
449	30.09.2015 02:02:35	DEBUG	HOSTER ShareonlineBiz[5591]: Redirect #0 to: http://www.share-online.biz/dl/P7T79EVNMR2L
450	30.09.2015 02:02:35	DEBUG	HOSTER ShareonlineBiz[5591]: LOAD URL http://www.share-online.biz/dl/P7T79EVNMR2L | decode=True | cookies=True | get={} | req=None | multipart=False | post={} | ref=True | just_header=True
451	30.09.2015 02:02:35	INFO	HOSTER ShareonlineBiz[5591]: Direct download link not found
452	30.09.2015 02:02:35	DEBUG	HOSTER ShareonlineBiz[5591]: LOAD URL http://www.share-online.biz/dl/P7T79EVNMR2L | decode=True | cookies=True | get={} | req=None | multipart=False | post={} | ref=False | just_header=False
453	30.09.2015 02:02:35	WARNING	Download failed: black-20150928174525.part3.rar | get_data() got an unexpected keyword argument 'refresh'
454	30.09.2015 02:02:35	INFO	Debug Report written to debug_ShareonlineBiz_30-09-2015_02-02-35.zip
455	30.09.2015 02:02:35	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: black-20150928174525.part3.rar (pid:210)
456	30.09.2015 02:02:35	INFO	ADDON UnSkipOnFail: No duplicates found
457	30.09.2015 02:02:35	DEBUG	All downloads processed

**Comment by McGeifer** [comment]
Same proble like wastez, Downloading as free user with premium account.

**Comment by steuerlexi** [comment]
I´m getting this error when i try to enter my premium account

262	02.10.2015 13:44:23	WARNING	ACCOUNT ShareonlineBiz: Error loading info for user `USERNAME` | (6, 'Could not resolve host: https')
261	02.10.2015 13:44:23	INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `USERNAME`...

**Comment by sraedler** [comment]
SO is working...

please close

**Comment by damien599901** [comment]
you re lucky
alldebrid is still dead :(

2016-02-14 22:58 GMT+01:00 sraedler <notifications@github.com>:

**Comment by GammaC0de** [comment]
@vuolter What is the reason you reopened? is there a problem with the shareonline account plugin?

**Comment by vuolter** [comment]
Nono, never mind. :p
