### ISSUE TITLE
Uptobox fail download "getStatusName() takes exactly 1 argument"

### ISSUE THREAD

**Issue by xilmen** [pyload/pyload#1890]
hi all, new warning for uptobox plugin. (after update 29.09.2015)

WARNING	Download failed: mydownload.dat | getStatusName() takes exactly 1 argument (2 given) 

ty for fix :)

UptoboxCom.py v0.13

#DEBUG	

29.09.2015 23:43:55	DEBUG	HOSTER UptoboxCom[745]: PROCESS URL http://uptobox.com/XXXXXXXXXXX | PLUGIN VERSION 0.21
117	29.09.2015 23:43:55	DEBUG	HOSTER UptoboxCom[745]: Config option `use_premium` not found, use default `True`
118	29.09.2015 23:43:55	INFO	HOSTER UptoboxCom[745]: Updating file info...
119	29.09.2015 23:43:55	DEBUG	HOSTER UptoboxCom[745]: File info: {'status': 2, 'url': u'http://uptobox.com/XXXXXXXXXXX', 'size': 6335076761.6, 'name': u'MyDownload.dat', 'pattern': {'S': u'5.9', 'U': u'GB', 'N': u'MyDownload.dat'}}
120	29.09.2015 23:43:55	DEBUG	HOSTER UptoboxCom[745]: Previous file info: {}
121	29.09.2015 23:43:55	INFO	HOSTER UptoboxCom[745]: File name: MyDownload.dat
122	29.09.2015 23:43:55	INFO	HOSTER UptoboxCom[745]: File size: 6335076761 bytes
123	29.09.2015 23:43:55	WARNING	Download failed: MyDownload.dat | getStatusName() takes exactly 1 argument (2 given)

**Comment by f6fvy** [comment]
This issue now supersedes #1859 (just closed) !

**Comment by vuolter** [comment]
Checking...
