### ISSUE TITLE
ShareOnline: unsupported operand type(s) for -: 'unicode' and 'float'

### ISSUE THREAD

**Issue by Vince-IN** [pyload/pyload#1892]
30.09.2015 08:37:49 INFO      Download starts: XYZXYZXYZXY.rar
30.09.2015 08:37:49 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
30.09.2015 08:37:49 DEBUG     Redirected import module.plugins.accounts.ShareonlineBiz -> userplugins.accounts.ShareonlineBiz
30.09.2015 08:37:49 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
30.09.2015 08:37:49 DEBUG     HOSTER ShareonlineBiz[8902]: PROCESS URL http://www.share-online.biz/dl/XYZXYZXYZXY | PLUGIN VERSION 0.57
30.09.2015 08:37:49 INFO      HOSTER ShareonlineBiz[8902]: Updating file info...
30.09.2015 08:37:49 DEBUG     HOSTER ShareonlineBiz[8902]: File info: {'status': 2, 'fileid': 'XYZXYZXYZXY', 'name': 'us-isoyg-xvid.part07.rar', 'url': u'http://www.share-online.biz/dl/XYZXYZXYZXY', 'pattern': {'ID': u'XYZXYZXYZXY'}, 'md5': 'xyz7710dc85d72f52f77fbe9ebf75xyz', 'size': 209715200.0}
30.09.2015 08:37:49 DEBUG     HOSTER ShareonlineBiz[8902]: Previous file info: {}
30.09.2015 08:37:49 INFO      HOSTER ShareonlineBiz[8902]: File name: XYZXYZXYZXY.rar
30.09.2015 08:37:49 INFO      HOSTER ShareonlineBiz[8902]: File size: 209715200 bytes
30.09.2015 08:37:49 INFO      HOSTER ShareonlineBiz[8902]: File status: starte
30.09.2015 08:37:49 DEBUG     HOSTER ShareonlineBiz[8902]: LOAD URL http://www.share-online.biz/dl/XYZXYZXYZXY | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
30.09.2015 08:37:50 INFO      HOSTER ShareonlineBiz[8902]: Processing as free download...
30.09.2015 08:37:50 DEBUG     HOSTER ShareonlineBiz[8902]: WAIT set to 3 seconds | Previous waitUntil: 0.000000
30.09.2015 08:37:50 WARNING   Download failed: XYZXYZXYZXY.rar | unsupported operand type(s) for -: 'unicode' and 'float'
30.09.2015 08:37:50 INFO      Debug Report written to debug_ShareonlineBiz_30-09-2015_08-37-50.zip

**Comment by Vince-IN** [comment]
from Debug Report:

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/osmc/.pyload/userplugins/internal/Hoster.py", line 196, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/osmc/.pyload/userplugins/internal/Hoster.py", line 191, in _process
    return self.process(self.pyfile)
  File "/home/osmc/.pyload/userplugins/internal/SimpleHoster.py", line 279, in process
    self.handle_free(pyfile)
  File "/home/osmc/.pyload/userplugins/hoster/ShareonlineBiz.py", line 92, in handle_free
    self.wait(3)
  File "/home/osmc/.pyload/userplugins/internal/Hoster.py", line 263, in wait
    self.log_info(_("Waiting %d seconds...") % pyfile.waitUntil - time.time())
TypeError: unsupported operand type(s) for -: 'unicode' and 'float'

**Comment by GammaC0de** [comment]
duplicate #1891
