### ISSUE TITLE
Update Manager: 	Not able to connect server for updates

### ISSUE THREAD

**Issue by tchoblond59** [pyload/pyload#1893]
Hi there,

I had some trouble with pyload then i decided to remove the userplugins folder.
I also try to completely remove and reinstall pyload but i still got this error:

Warning:	Not able to connect server for updates

What can i do ? Thanks

**Comment by driet** [comment]
Are you running pyload at a NAS? Qnap e.g. has non-standard configs, in this case you should look in specific user forums.

**Comment by tchoblond59** [comment]
Running on a debian server...
I try to add the file UpdateManager.py in the userplugins directory and now it seems to work.
But i can't download using realdebrid plugin

**Comment by GammaC0de** [comment]
solution:
* stop `pyLoad`
* replace the `modules/UpdateManager.py` file with this one: https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py
* Start `pyLoad`
* Wait for update to finish
* Watch the log - you may have to manually restart `pyLoad` for `UpdateManager` finish its job

**Comment by tchoblond59** [comment]
In /usr/share/pyload/module/plugins/hooks or in the config directory .pyload/userplugins ??

**Comment by GammaC0de** [comment]
/usr/share/pyload/module/plugins/hooks

**Comment by tchoblond59** [comment]
Ok thanks ! Pyload is updating module !

**Comment by GammaC0de** [comment]
:+1:

**Comment by romu044** [comment]
Hello,

I have exactly the same problem.
I did the GammaC0de solution, but I still get the same message 
WARNING	Not able to connect server for updates
the server address is "http://updatemanager-spyload.rhcloud.com"
but error 503 Service Temporarily Unavailable
can you help me please

**Comment by hulyahulya** [comment]
1	23.07.2016 01:53:37	INFO	Starting pyLoad 0.4.9
2	23.07.2016 01:53:37	INFO	Using home directory: /usr/share/pyload/home/pi
3	23.07.2016 01:53:38	INFO	ExtractArchive: No UnRar installed
4	23.07.2016 01:53:38	INFO	ExtractArchive: Activated UnZip
5	23.07.2016 01:53:38	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
6	23.07.2016 01:53:38	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
7	23.07.2016 01:53:38	INFO	Downloadtime: True
8	23.07.2016 01:53:39	INFO	Starting builtin webserver: 192.168.1.46:8000
9	23.07.2016 01:53:39	INFO	Free space: 1.73 TiB
10	23.07.2016 01:53:39	INFO	Activating Accounts...
11	23.07.2016 01:53:39	INFO	Activating Plugins...
12	23.07.2016 01:53:39	INFO	pyLoad is up and running
13	23.07.2016 01:53:45	WARNING	Not able to connect server for updates
14	23.07.2016 01:53:45	INFO	No Updates for pyLoad
15	23.07.2016 01:55:46	INFO	Starting pyLoad 0.4.9
16	23.07.2016 01:55:46	INFO	Using home directory: /usr/share/pyload/home/pi
17	23.07.2016 01:55:48	INFO	ExtractArchive: No UnRar installed
18	23.07.2016 01:55:48	INFO	ExtractArchive: Activated UnZip
19	23.07.2016 01:55:48	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
20	23.07.2016 01:55:48	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
21	23.07.2016 01:55:48	INFO	Downloadtime: True
22	23.07.2016 01:55:50	INFO	Starting builtin webserver: 192.168.1.46:8000
23	23.07.2016 01:55:50	INFO	Free space: 1.73 TiB
24	23.07.2016 01:55:50	INFO	Activating Accounts...
25	23.07.2016 01:55:50	INFO	Activating Plugins...
26	23.07.2016 01:55:50	INFO	pyLoad is up and running
27	23.07.2016 01:55:52	WARNING	Not able to connect server for updates
28	23.07.2016 01:55:52	INFO	No Updates for pyLoad
29	23.07.2016 01:55:52	WARNING	Not able to connect server for updates
30	23.07.2016 01:55:52	INFO	No plugin updates available
31	23.07.2016 01:57:03	INFO	Added package 12 containing 1 links
32	23.07.2016 01:57:04	INFO	Download starts: https://docs.google.com/uc?id=0B0uPqaFewRxdVDREbmZiZU1FR1k&export=download
33	23.07.2016 01:57:08	INFO	Download finished: uc
34	23.07.2016 01:57:08	INFO	Package finished: 12
35	23.07.2016 01:57:08	INFO	ExtractArchive: Package 12 queued for later extracting
36	23.07.2016 01:57:08	INFO	ExtractArchive: Check package 12
37	23.07.2016 01:57:18	INFO	Added package wew containing 1 links
38	23.07.2016 01:57:18	INFO	Download starts: https://docs.google.com/uc?id=0B0uPqaFewRxdVDREbmZiZU1FR1k&export=download
39	23.07.2016 01:57:20	INFO	Download finished: uc
40	23.07.2016 01:57:20	INFO	Package finished: wew
41	23.07.2016 01:57:20	INFO	ExtractArchive: Package wew queued for later extracting
42	23.07.2016 01:57:20	INFO	ExtractArchive: Check package wew
43	23.07.2016 02:09:40	INFO	shutting down...
44	23.07.2016 02:09:40	INFO	Received Quit signal
45	23.07.2016 02:09:56	INFO	Starting pyLoad 0.4.9
46	23.07.2016 02:09:56	INFO	Using home directory: /usr/share/pyload/home/pi
47	23.07.2016 02:09:58	INFO	ExtractArchive: No UnRar installed
48	23.07.2016 02:09:58	INFO	ExtractArchive: Activated UnZip
49	23.07.2016 02:09:58	ERROR	Error importing UpdateManager: No module named Addon
50	23.07.2016 02:09:58	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
51	23.07.2016 02:09:58	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
52	23.07.2016 02:09:58	INFO	Downloadtime: True
53	23.07.2016 02:09:59	INFO	Starting builtin webserver: 192.168.1.46:8000
54	23.07.2016 02:09:59	INFO	Free space: 1.73 TiB
55	23.07.2016 02:09:59	INFO	Activating Accounts...
56	23.07.2016 02:09:59	INFO	Activating Plugins...
57	23.07.2016 02:09:59	INFO	pyLoad is up and running
58	23.07.2016 02:12:44	INFO	restarting pyLoad
59	23.07.2016 02:12:44	INFO	shutting down...
60	23.07.2016 02:12:45	INFO	Starting pyLoad 0.4.9
61	23.07.2016 02:12:45	INFO	Using home directory: /usr/share/pyload/home/pi
62	23.07.2016 02:12:45	INFO	ExtractArchive: No UnRar installed
63	23.07.2016 02:12:45	INFO	ExtractArchive: Activated UnZip
64	23.07.2016 02:12:45	ERROR	Error importing UpdateManager: No module named Addon
65	23.07.2016 02:12:45	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
66	23.07.2016 02:12:45	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
67	23.07.2016 02:12:45	INFO	Downloadtime: True
68	23.07.2016 02:12:46	INFO	Starting builtin webserver: 192.168.1.46:8000
69	23.07.2016 02:12:46	INFO	Free space: 1.73 TiB
70	23.07.2016 02:12:46	INFO	Activating Accounts...
71	23.07.2016 02:12:46	INFO	Activating Plugins...
72	23.07.2016 02:12:46	INFO	pyLoad is up and running
73	23.07.2016 02:13:31	INFO	Added package qqqqqqqqqq containing 1 links
74	23.07.2016 02:13:32	INFO	Download starts: https://docs.google.com/uc?id=0B0uPqaFewRxdVDREbmZiZU1FR1k&export=download
75	23.07.2016 02:13:34	INFO	Download finished: uc
76	23.07.2016 02:13:34	INFO	Package finished: qqqqqqqqqq
77	23.07.2016 02:13:34	INFO	ExtractArchive: Package qqqqqqqqqq queued for later extracting
78	23.07.2016 02:13:34	INFO	ExtractArchive: Check package qqqqqqqqqq
79	23.07.2016 02:17:34	INFO	Added package DOWNLOAD containing 1 links
80	23.07.2016 02:17:36	INFO	Download starts: https://docs.google.com/uc?id=0B0uPqaFewRxdVDREbmZiZU1FR1k&export=download
81	23.07.2016 02:17:38	INFO	Download finished: uc
82	23.07.2016 02:17:38	INFO	Package finished: DOWNLOAD
83	23.07.2016 02:17:38	INFO	ExtractArchive: Package DOWNLOAD queued for later extracting
84	23.07.2016 02:17:38	INFO	ExtractArchive: Check package DOWNLOAD
85	23.07.2016 02:36:48	INFO	shutting down...
86	23.07.2016 02:36:48	INFO	pyLoad quits
87	23.07.2016 02:38:23	INFO	Starting pyLoad 0.4.9
88	23.07.2016 02:38:23	INFO	Using home directory: /usr/share/pyload/home/pi
89	23.07.2016 02:38:25	INFO	ExtractArchive: No UnRar installed
90	23.07.2016 02:38:25	INFO	ExtractArchive: Activated UnZip
91	23.07.2016 02:38:25	ERROR	Error importing UpdateManager: No module named Addon
92	23.07.2016 02:38:25	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
93	23.07.2016 02:38:25	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
94	23.07.2016 02:38:25	INFO	Downloadtime: True
95	23.07.2016 02:38:26	INFO	Starting builtin webserver: 192.168.1.46:8000
96	23.07.2016 02:38:26	INFO	Free space: 1.73 TiB
97	23.07.2016 02:38:26	INFO	Activating Accounts...
98	23.07.2016 02:38:26	INFO	Activating Plugins...
99	23.07.2016 02:38:26	INFO	pyLoad is up and running
100	23.07.2016 02:39:18	INFO	Added package download containing 1 links
101	23.07.2016 02:39:19	INFO	Download starts: https://docs.google.com/uc?id=0B0uPqaFewRxdbnRGb1UwTXBLTzQ&export=download
102	23.07.2016 02:39:21	INFO	Download finished: uc
103	23.07.2016 02:39:21	INFO	Package finished: download
104	23.07.2016 02:39:21	INFO	ExtractArchive: Package download queued for later extracting
105	23.07.2016 02:39:21	INFO	ExtractArchive: Check package download

**Comment by GammaC0de** [comment]
Please enable debug mode and repeat the process
