### ISSUE TITLE
Share-Online premium "check_traffic" (Hoster.py) fails

### ISSUE THREAD

**Issue by BAERnado** [pyload/pyload#1898]
Adding premium downloads on pyload 0.4.9 after a fresh setup with acknowledged share-online.biz premium account fails because of "checktraffic" function in Hoster.py.
I do not have another premium account to check whether this happens with all hosters.

Sadly the debug_Report.txt can not be attached hence I add it's content directly:

pyLoad 0.4.9 Debug Report of ShareonlineBiz 0.57 

TRACEBACK:
 Traceback (most recent call last):
  File "/home/pyload/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/pyload/pyload/module/plugins/internal/Hoster.py", line 196, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/pyload/pyload/module/plugins/internal/Hoster.py", line 191, in _process
    return self.process(self.pyfile)
  File "/home/pyload/pyload/module/plugins/internal/SimpleHoster.py", line 273, in process
    if self.premium and (not self.CHECK_TRAFFIC or self.check_traffic()):
  File "/home/pyload/pyload/module/plugins/internal/Hoster.py", line 582, in check_traffic
    traffic = self.account.get_data(refresh=True)['trafficleft']
TypeError: get_data() got an unexpected keyword argument 'refresh'
 

FRAMESTACK:

Frame preprocessing in /home/pyload/pyload/module/plugins/internal/Hoster.py at line 196
	                self = <Hoster ShareonlineBiz>
	                args = (<DownloadThread(Thread-2, started daemon 139962771298048)>,)
	              kwargs = {}

Frame _process in /home/pyload/pyload/module/plugins/internal/Hoster.py at line 191
	                self = <Hoster ShareonlineBiz>
	              thread = <DownloadThread(Thread-2, started daemon 139962771298048)>

Frame process in /home/pyload/pyload/module/plugins/internal/SimpleHoster.py at line 293
	              pyfile = PyFile 7: O.U.a.T.E.w.e.S04E12.H.a.V.G.D.D.1080.B.x-TVP.part7.rar@ShareonlineBiz
	                self = <Hoster ShareonlineBiz>

Frame check_traffic in /home/pyload/pyload/module/plugins/internal/Hoster.py at line 582
	                self = <Hoster ShareonlineBiz>

PLUGIN OBJECT DUMP: 

	          CHECK_FILE = True
	       CHECK_TRAFFIC = True
	             COOKIES = True
	         DIRECT_LINK = None
	         DISPOSITION = True
	       ERROR_PATTERN = '<p class="b">Information:</p>\\s*<div>\\s*<strong>(.*?)</strong>'
	         FILE_ERRORS = [('Html error',
  '\\A(?:\\s*<.+>)?((?:[\\w\\s]*(?:[Ee]rror|ERROR)\\s*\\:?)?\\s*\\d{3})(?:\\Z|\\s+)'),
 ('Request error', '([Aa]n error occured while processing your request)'),
 ('Html file', '\\A\\s*<!DOCTYPE html')]
	        LEECH_HOSTER = False
	        LINK_PATTERN = None
	       LOGIN_ACCOUNT = False
	       LOGIN_PREMIUM = False
	   NAME_REPLACEMENTS = []
	       RECAPTCHA_KEY = '6LdatrsSAAAAAHZrB70txiV5p-8Iv8BtVxlTtjKX'
	   SIZE_REPLACEMENTS = []
	       TEXT_ENCODING = True
	    URL_REPLACEMENTS = [('https?://(?:www\\.)?(share-online\\.biz|egoshare\\.com)/(download\\.php\\?id=|dl/)(?P<ID>\\w+).*',
  'http://www.share-online.biz/dl/\\g<ID>')]
	             account = <Account ShareonlineBiz>
	             captcha = <Captcha Captcha>
	         chunk_limit = -1
	           direct_dl = True
	          force_free = False
	                html = u'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">\n    <head>\n        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n        <meta name="keywords" content="hosting, webhosting, webspace, backup, free download, free upload, download, mp3, movies, music, videos, software, shareware, file transfer, file sharing, file mirroring, file recovery" />\n        <meta name="description" content="Share-Online.biz is a worldwide operating fileserving project. You\'re able to serve and share any type of document like pictures, movies and music with us." />\n        <meta name="title" content="Share-Online.biz" />\n        <meta name="author" content="Share-Online.biz" />\n        <meta name="publisher" content="Share-Online.biz" />\n        <meta name="copyright" content="Share-Online.biz" />\n        <title>Share-Online - dl/23T9HSUNUC</title>\n        <link rel="shortcut icon" href="https://www.share-online.biz/favicon.ico" type="image/ico" />\n        <link href="http://www.share-online.biz/template/v3dark/css/main.css" rel="stylesheet" type="text/css" />\n        <link href="http://www.share-online.biz/template/v3dark/css/jquery-ui.css" rel="stylesheet" type="text/css" />\n\n        <script src="http://www.share-online.biz/template/js/jquery.js" type="text/javascript"></script>\n\n        <script src="http://www.share-online.biz/template/js/jquery-ui.js" type="text/javascript"></script>\n\n        <script src="http://www.share-online.biz/template/js/jquery-liscroll.js" type="text/javascript"></script>\n        <script src="http://www.share-online.biz/template/js/tools.js" type="text/javascript"></script>\n\n    </head>\n\n    <body>\n        <script type="text/javascript">\n            \n        </script>\n\n        <script src="http://www.share-online.biz/template/v3dark/js/body.js" type="text/javascript"></script>\n        \n        <script type="text/javascript">\n            \n        </script>\n        \n        <div id="header">\n                        \n            <div id="left">\n                <ul id="left-menu">\n                    <li><span class=\'fs11 b white\'>V3-dark</span></li>\n                    <li>|</li>\n                    <li><a href=\'http://www.share-online.biz/theme/set/v3light\'>V3-light</a></li>\n                </ul>\n                <div id="login-bar">\n                    <div class="login">\n                        <img src="http://www.share-online.biz/template/images/icons/light.png" alt="" border="0" class="vmid" /> <a href="javascript:void(0);" id="login-link">Einloggen</a>\n                        \n                    </div>\n                </div>\n                <div id="login" class="ui-corner-bottom">\n                    <div class="login">\n                        <form action="https://www.share-online.biz/user/login" method="post">\n                            <input type="text" value="" class="login ui-corner-all" name="user" id="l_user" onfocus="login_fields(\'user\', \'click\');" onblur="login_fields(\'user\', \'blur\');" /> <input type="password" value="" class="login ui-corner-all" name="pass" id="l_pass" onfocus="login_fields(\'pass\', \'click\');" onblur="login_fields(\'pass\', \'blur\');" /><div class="forget_pass"><a href="javascript:resend();">Passwort vergessen?</a></div> <div class="c"><input type="checkbox" value="1" name="l_rememberme" id="l_rememberme" title="f\xfcr n\xe4chsten Login merken" /> <label for="l_rememberme">f\xfcr n\xe4chsten Login merken</label></div><span class="login_form"><input type="submit" value="Einloggen" title="Einloggen" class="button" /></span><span class="login_ssl"><a href="http://www.share-online.biz/lang/ssl">SSL/HTTPS: auto</a> <a href=\'https://www.share-online.biz/helpdesk/knowledgebase.php?article=8\' target=\'_blank\' class=\'red\'>(?)</a></span>\n                        </form>\n                        \n                    </div>\n                </div>\n                <div id="logo">\n                    <a href="http://www.share-online.biz/"><img src="http://www.share-online.biz/template/v3dark/images/logo.gif" alt="" width="285" height="50" border="0" /></a>\n                </div>\n            </div>\n            \n            <div class="middle">\n                <ul id="topnav" class="notranslate">\n                    <li>\n                        <a href="http://www.share-online.biz/">home</a>\n                    </li>\n                    <li>\n                        <a href="http://www.share-online.biz/news/">news</a>\n                    </li>\n                    \n                    <li>\n                            \n                        <a href="https://www.share-online.biz/register/premium">Registrieren</a>\n                            \n                    </li>\n                    \n                    <li>\n                            \n                        <a href="https://www.share-online.biz/register/free">Paketvergleich</a>\n                            \n                    </li>\n                    \n                    <li>\n                        <a href="http://www.share-online.biz/faq/">faq</a>\n                    </li>\n                    <li>\n                        <a href="http://www.share-online.biz/tools/">tools</a>\n                    </li>\n                    <li>\n                        <a href="https://www.share-online.biz/helpdesk/index.php?language=Deutsch">support</a>\n                    </li>\n\n\n\n                </ul>\n                <div id="select_lang">\n                    <a href="http://www.share-online.biz/lang/set/english"><img src="http://www.share-online.biz/template/images/lang/en.gif" alt="english" border="0" /></a>\n                    <a href="http://www.share-online.biz/lang/set/german"><img src="http://www.share-online.biz/template/images/lang/de.gif" alt="german" border="0" /></a>\n                </div>\n            </div>\n\n            <div id="page_options" class="ui-corner-top">\n                <a href="http://www.share-online.biz/lang/animations/off">Men\xfcanimation deaktivieren</a> | <a href="http://www.share-online.biz/lang/news/off">News deaktivieren</a>\n            </div>\n\n        </div>\n        <ul id="newsscroller"><li><span>30.04.2015</span><a href=\'https://www.share-online.biz/news/387\'>Neue PPS Raten</a></li><li><span>01.12.2014</span><a href=\'https://www.share-online.biz/news/347\'>Weihnachts Spezial</a></li><li><span>30.11.2014</span><a href=\'https://www.share-online.biz/news/357\'>\xc4nderung Traffic Berechnung</a></li><li><span>09.11.2014</span><a href=\'https://www.share-online.biz/news/327\'>Ersatzleistung</a></li><li><span>07.11.2014</span><a href=\'https://www.share-online.biz/news/307\'>Starker DDOS Angriff</a></li></ul>\n        <noscript><div class="noscript-message"><p><img src="https://www.share-online.biz/template/images/alert.png" alt="0" width="32" height="30" /><strong>Bitte Javascript aktivieren.</strong> Die komplette Funktionalit\xe4t (Download, Upload, Verwaltung) ist andernfalls nicht verf\xfcgbar!</p></div></noscript>\n        \n        <div id="main" class="ui-corner-all">\n            <div id="inner">\n<div id="download">\n    <h1>Bitte w\xe4hlen Sie Ihr Download-Paket</h1>\n    <hr />\n    <div>\n        <script type="text/javascript">\n            \n        </script>\n    </div>\n    <div class="cb"></div>\n    <div id="choose_package">\n        <object data="http://www.share-online.biz/template/swf/choose_package.swf" type="application/x-shockwave-flash" width="700" height="230"><param value="high" name="quality"><param value="opaque" name="wmode"><param value="always" name="allowScriptAccess"></object>\n        <table id="dl_package" cellpadding="0" cellspacing="0" border="0">\n            <tr>\n                <th>kostenlos</th>\n                <th>PREMIUM</th>\n            </tr>\n            <tr>\n                <td class="dl_free details ui-corner-all"><ul><li>teils Captcha Abfragen</li><li>Wartezeiten (minimal 30s)</li><li>limitierter Speed (aktuell max. 200 kb/s)</li><li>st\xf6rende Werbung</li><li>maximal 1 Download auf einmal</li><li>begrenzte Downloadslots</li><li>Downloads nicht wiederaufnehmbar</li><li>Limit von 1024 MB pro Stunde/Datei</li></ul></td>\n                <td class="dl_premium details ui-corner-all"><ul><li>Sofort loslegen</li><li>keine Wartezeiten</li><li>maximale Geschwindigkeit</li><li>keine Werbung, Layer oder Popups</li><li>Paralleler Download von mehreren Dateien</li><li>immer Vorrang vor G\xe4sten und Sammlern</li><li>Downloads wiederaufnehmbar</li><li>kein Stundenlimit</li></ul></td>\n            </tr>\n            <tr>\n                <td><button class="dl_action">>> kostenlos weiter <<</button></td>\n                <td><button class="dl_action">>> Premium Vorteile sichern <<</button></td>\n            </tr>\n        </table>\n\n    </div>\n</div>\n<script type="text/javascript">\n    \n</script>\n\n                <div id="consumer_bottom" class="ui-corner-all">\n                    <iframe id=\'aa81823a\' name=\'aa81823a\' src=\'http://ad.propellerads.com/afr.php?zoneid=2517\' frameborder=\'0\' scrolling=\'no\' width=\'728\' height=\'90\'><a href=\'http://ad.propellerads.com/ck.php?n=a799fafc\' target=\'_blank\'><img src=\'http://ad.propellerads.com/avw.php?zoneid=2517&n=a799fafc\' border=\'0\' alt=\'\' /></a></iframe>\n                </div>\n    \n            </div>\n        </div>\n        <div id="footer">\n            <div class="footer">\n                <ul id="footer-menu">\n                    <li><a href="http://www.share-online.biz/linkcheckapi/">Linkcheck API</a></li>\n                    <li><a href="http://www.share-online.biz/uploadapi/">Upload API</a></li>\n                    <li><a href="http://www.share-online.biz/nopaste/">nopaste</a></li>\n                    <li><a href="http://www.share-online.biz/tos/">AGB</a></li>\n                    <li><a href="http://www.share-online.biz/abuse/">abuse</a></li>\n                    <li class="last"><a href="http://www.share-online.biz/imprint/">Impressum</a></li>\n                </ul>\n            </div>\n            <div id="footer-logo">\n                    <a href="http://www.share-online.biz/"><img src="http://www.share-online.biz/template/v3dark/images/footer_logo.gif" alt="" width="113" height="27" border="0" /></a>\n            </div>\n        </div>\n        <div id="dialog" title="">\n            <p></p>\n        </div>\n        <ul id="contextMenu" class="contextMenu">\n            <li><a href="#action"></a></li>\n        </ul>\n\n        \n        <script type="text/javascript">\n            var alive = "http://www.share-online.biz/alive/";\n        </script>\n    </body>\n</html>'
	                info = {'fileid': '23T9HSUNUC',
 'folder': 'O.U.a.T.E.w.e.S04E12.H.a.V.G.D.D.1080.B.x-TVP.part7.rar',
 'md5': '8d8d2671dd4dad41b07ef39403c74d5b',
 'name': 'O.U.a.T.E.w.e.S04E12.H.a.V.G.D.D.1080.B.x-TVP.part7.rar',
 'pattern': {'ID': u'23T9HSUNUC'},
 'size': 61352471.0,
 'status': 2,
 'url': u'http://www.share-online.biz/dl/23T9HSUNUC'}
	                  js = <module.common.JsEngine.JsEngine instance at 0x7f4b9d62e3f8>
	          last_check = None
	       last_download = ''
	            leech_dl = False
	             limitDL = 0
	                link = ''
	             multiDL = False
	             premium = True
	              pyfile = PyFile 7: O.U.a.T.E.w.e.S04E12.H.a.V.G.D.D.1080.B.x-TVP.part7.rar@ShareonlineBiz
	              pyload = <__main__.Core object at 0x7f4ba0046790>
	                 req = <module.network.Browser.Browser object at 0x7f4b7390c328>
	     resume_download = True
	             retries = {}
	              thread = <DownloadThread(Thread-2, started daemon 139962771298048)>
	                user = 'BAERnado'
	          wait_until = 0
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 61352471
	               abort = False
	              active = False
	               error = "get_data() got an unexpected keyword argument 'refresh'"
	                  id = 7
	                lock = <_RLock owner=None count=0>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x7f4ba0032290>
	         maxprogress = 100
	                name = 'O.U.a.T.E.w.e.S04E12.H.a.V.G.D.D.1080.B.x-TVP.part7.rar'
	               order = 6
	           packageid = 1
	              plugin = <Hoster ShareonlineBiz>
	         pluginclass = <class 'module.plugins.hoster.ShareonlineBiz.ShareonlineBiz'>
	        pluginmodule = <module 'module.plugins.hoster.ShareonlineBiz' from '/home/pyload/pyload/module/plugins/hoster/ShareonlineBiz.pyc'>
	          pluginname = u'ShareonlineBiz'
	            progress = 0
	         reconnected = False
	                size = 61352471
	              status = 8
	          statusname = None
	                 url = u'http://www.share-online.biz/dl/23T9HSUNUC'
	           waitUntil = 0

CONFIG: 

{'desc': 'ShareonlineBiz',
 'outline': 'Shareonline.biz hoster plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': True}}

**Comment by vuolter** [comment]
Now fixed.
