### ISSUE TITLE
OneFichierCom : pycurl exception 28: SSL connection timeout

### ISSUE THREAD

**Issue by f6fvy** [pyload/pyload#1905]
I always get this exception when submitting a link.

01.10.2015 01:17:29	DEBUG	HOSTER OneFichierCom[194]: LOAD URL https://1fichier.com/?6uymqlo1xu | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
01.10.2015 01:17:59	DEBUG	pycurl exception 28: SSL connection timeout at 28524
01.10.2015 01:17:59	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.

or

01.10.2015 01:11:25	DEBUG	HOSTER OneFichierCom[194]: DOWNLOAD URL https://1fichier.com/?6uymqlo1xu | cookies=True | get={} | disposition=True | post={u'dl_no_ssl': '', 'submit': 'Download', u'dlinline': ''} | ref=True
01.10.2015 01:11:56	DEBUG	Chunk 1 failed: (28, 'Operation timed out after 30426 milliseconds with 0 out of 0 bytes received')
01.10.2015 01:11:56	DEBUG	pycurl exception 28: Operation timed out after 30426 milliseconds with 0 out of 0 bytes received
01.10.2015 01:11:56	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry. 

The very same URL works like a charm with my browser.
What could be wrong ?

**Comment by vuolter** [comment]
Please, try with `http://1fichier.com/?6uymqlo1xu`

**Comment by f6fvy** [comment]
After an automatic pyload update I now get : 

02.10.2015 00:08:13	DEBUG	HOSTER OneFichierCom[194]: PROCESS URL https://1fichier.com/?6uymqlo1xu | PLUGIN VERSION 0.90
02.10.2015 00:08:13	INFO	HOSTER OneFichierCom[194]: Updating file info...
02.10.2015 00:08:17	DEBUG	HOSTER OneFichierCom[194]: File info: {'status': 3, 'url': u'https:/1fichier.com/?6uymqlo1xu', 'size': 0, 'name': '?6uymqlo1xu', 'pattern': {'HOST': u'1fichier.com', 'ID2': u'6uymqlo1xu', 'ID1': None}}
02.10.2015 00:08:17	DEBUG	HOSTER OneFichierCom[194]: Previous file info: {}
02.10.2015 00:08:17	INFO	HOSTER OneFichierCom[194]: File name: ?6uymqlo1xu
02.10.2015 00:08:17	INFO	HOSTER OneFichierCom[194]: File size: Unknown
02.10.2015 00:08:17	INFO	HOSTER OneFichierCom[194]: File status: starting
02.10.2015 00:08:17	INFO	HOSTER OneFichierCom[194]: Looking for direct download link...
02.10.2015 00:08:17	DEBUG	HOSTER OneFichierCom[194]: LOAD URL https://1fichier.com/?6uymqlo1xu | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
02.10.2015 00:08:18	DEBUG	pycurl exception 6: Couldn't resolve host 'https'
02.10.2015 00:08:18	ERROR	pycurl error 6: Couldn't resolve host 'https'
02.10.2015 00:08:18	INFO	Debug Report written to debug_OneFichierCom_02-10-2015_00-08-18.zip 

Debug log : 

pyLoad 0.4.9 Debug Report of OneFichierCom 0.90 

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/pi/.pyload/userplugins/internal/Base.py", line 201, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/pi/.pyload/userplugins/internal/Hoster.py", line 80, in _process
    self.process(self.pyfile)
  File "/home/pi/.pyload/userplugins/internal/SimpleHoster.py", line 274, in process
    self.handle_direct(pyfile)
  File "/home/pi/.pyload/userplugins/hoster/OneFichierCom.py", line 86, in handle_direct
    headers = self.load(redirect, just_header=True)
  File "/home/pi/.pyload/userplugins/internal/Base.py", line 47, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/pi/.pyload/userplugins/internal/Base.py", line 379, in load
    return super(Base, self).load(*args, **kwargs)
  File "/home/pi/.pyload/userplugins/internal/Plugin.py", line 374, in load
    html = req.load(url, get, post, ref, bool(cookies), just_header, multipart, decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/usr/share/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 195, in load
    self.c.perform()
error: (6, "Couldn't resolve host 'https'")
 
Is it still related to the pycurl lib ? I'm using pyload on a Raspberry Pi. How to update pycurl lib if this is the cause of the issue ? I did an apt-get update / apt-get upgrade but the issue remains.

**Comment by vuolter** [comment]
Try: `python pip install pycurl` (from shell)
