### ISSUE TITLE
Real Debrid not working

### ISSUE THREAD

**Issue by tchoblond59** [pyload/pyload#1906]
It seems that real debrid plugin is down...
When i try with 1fichier.com i got this: unsupported operand type(s) for -: 'unicode' and 'float' 
Then pyload Processing as free download...

With Uptobox i got:
first argument must be string or compiled pattern

With uploadedto pyload processing as free download

It seems that the RealDebrid is not handling the links...

Is there a new plugin or i am missing something ??

Edit: If you need an account just give me your mail address

**Comment by Velociraptor85** [comment]
@tchoblond59 @vuolter @GammaC0de 
old please close the issue
also seems to be a duplicate for https://github.com/pyload/pyload/issues/2286

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/14d26e63c83a49fcafe8101d318f395a137b3906
