### ISSUE TITLE
Account alldebrid not recognized

### ISSUE THREAD

**Issue by Spartanineo** [pyload/pyload#1908]
Hi,

pyload does not reknow my account alldebrid.
In the logs i have
 324    01.10.2015 12:43:50 INFO    ACCOUNT AlldebridCom: Updating account info for user `xxxxxxxxxxxxxxxx`...
323 01.10.2015 12:43:43 WARNING     ACCOUNT AlldebridCom: Error loading info for user `xxxxxxxxxxxxxx` | syntax error: line 1, column 0
322 01.10.2015 12:43:41 INFO    ACCOUNT AlldebridCom: Grabbing account info for user `xxxxxxxxxxxxxx`...
321 01.10.2015 12:42:43 INFO    ADDON ClickAndLoad: Proxy listening on xxxxxxxxxxxx
320 01.10.2015 12:42:37 WARNING ACCOUNT AlldebridCom: Error loading info for user `xxxxxxxxxxxxxx` | syntax error: line 1, column 0
319 01.10.2015 12:42:36 INFO    ACCOUNT AlldebridCom: Grabbing account info for user `xxxxxxxxxxxxxx`...
318 01.10.2015 12:42:34 INFO    ADDON UpdateManager: No plugin updates available
317 01.10.2015 12:42:34 INFO    ADDON UpdateManager: No new pyLoad version available 

What do I have to make?

Thank you

**Comment by vuolter** [comment]
Debug log please.

**Comment by Spartanineo** [comment]
50	02.10.2015 05:35:34	DEBUG	ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/register/ | cookies=True | get={'action': 'login', 'login_login': 'xxxxxxxxxxx', 'login_password': 'xxxxxxxxxxx'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
49	02.10.2015 05:35:34	INFO	ACCOUNT AlldebridCom: Relogin user `xxxxxxxxxxxxx`...
48	02.10.2015 05:35:34	DEBUG	ACCOUNT AlldebridCom: Reached login timeout for user `xxxxxxxxxx`
47	02.10.2015 05:29:40 DEBUG	ACCOUNT AlldebridCom: Account info for user `xxxxxxxxxx`: {'login': {'timestamp': 1443756256.1668179, 'password': '**********', 'valid': None}, 'data': {'validuntil': None, 'maxtraffic': None, 'premium': None, 'options': {'limitdl': ['0']}, 'trafficleft': None}}
46	02.10.2015 05:29:40	WARNING	ACCOUNT AlldebridCom: Error loading info for user `xxxxxxxxxxxxx` | syntax error: line 1, column 0
45	02.10.2015 05:29:40	DEBUG	ACCOUNT AlldebridCom: flood
44	02.10.2015 05:29:40	DEBUG	ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/api.php | cookies=True | get={'action': 'info_user', 'login': 'xxxxxxxxxxx', 'pw': xxxxxxxxxx'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
43	02.10.2015 05:29:39	DEBUG	ACCOUNT AlldebridCom: LOAD URL http://www.alldebrid.com/account/ | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
42	02.10.2015 05:29:39	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `xxxxxxxxxxx`...
41	02.10.2015 05:24:27	INFO	ADDON ClickAndLoad: Proxy listening on 127.0.0.1:9666
40	02.10.2015 05:24:17	INFO	ADDON UpdateManager: No plugin updates available
39	02.10.2015 05:24:17	DEBUG	ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BillionuploadsCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'ShareRapidCom'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'Movie2kTo'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'EasybytezCom'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FreeWayMe'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultishareCz'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'OverLoadMe'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PutdriveCom'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RapideoPl'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RehostTo'), (u'hooks', u'ReloadCc'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SmoozedCom'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'ZeveraCom'), (u'hoster', u'File4safeCom'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'Vipleech4uCom'), (u'internal', u'AbstractExtractor'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster')]
38	02.10.2015 05:24:17	INFO	ADDON UpdateManager: No new pyLoad version available
37	02.10.2015 05:24:17	INFO	pyLoad is up and running
36	02.10.2015 05:24:17	DEBUG	ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
35	02.10.2015 05:24:17	DEBUG	ADDON ExtractArchive: Found UnRar 4.20 | Found SevenZip 9.20 | Found UnZip 2.7.10
34	02.10.2015 05:24:17	DEBUG	HOOK XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?:\w+\.)*?(?P(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:user|folder)s?/\w+
33	02.10.2015 05:24:17	INFO	HOOK XFileSharingPro: Handling any crypter I can!
32	02.10.2015 05:24:17	DEBUG	HOOK XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?:\w+\.)*?(?P(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
31	02.10.2015 05:24:17	INFO	HOOK XFileSharingPro: Handling any hoster I can!
30	02.10.2015 05:24:17	WARNING	ADDON AntiStandby: Unable to change display power state | [Errno 2] No such file or directory
29	02.10.2015 05:24:17	WARNING	ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
28	02.10.2015 05:24:17	INFO	Activating Plugins...
27	02.10.2015 05:24:17	DEBUG	ACCOUNT AlldebridCom: Account info for user `xxxxxxxx`: {'login': {'timestamp': 1443756256.1668179, 'password': '**********', 'valid': None}, 'data': {'validuntil': None, 'maxtraffic': None, 'premium': None, 'options': {'limitdl': ['0']}, 'trafficleft': None}}
26	02.10.2015 05:24:17	WARNING	ACCOUNT AlldebridCom: Error loading info for user `xxxxxxxxxxx` | syntax error: line 1, column 0
25	02.10.2015 05:24:17	DEBUG	ACCOUNT AlldebridCom: flood
24	02.10.2015 05:24:17	DEBUG	ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/api.php | cookies=True | get={'action': 'info_user', 'login': 'xxxxxxxxxxxx', 'pw': 'xxxxxxxxxxxx'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
23	02.10.2015 05:24:16	DEBUG	ACCOUNT AlldebridCom: LOAD URL http://www.alldebrid.com/account/ | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
22	02.10.2015 05:24:16	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `xxxxxxxxxxxx`...
21	02.10.2015 05:24:16	DEBUG	ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/register/ | cookies=True | get={'action': 'login', 'login_login': 'xxxxxxxxxx', 'login_password': 'xxxxxxxxxxxx'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
20	02.10.2015 05:24:16	INFO	ACCOUNT AlldebridCom: Login user `xxxxxxxxxxxxx`...
19	02.10.2015 05:24:16	INFO	ACCOUNT AlldebridCom: Adding user `xxxxxxxxxxxx`...
18	02.10.2015 05:24:16	DEBUG	Redirected import module.plugins.internal.Account -> userplugins.internal.Account
17	02.10.2015 05:24:16	INFO	Activating Accounts...
16	02.10.2015 05:24:16	INFO	Starting threaded webserver: 0.0.0.0:9050
15	02.10.2015 05:24:16	INFO	Free space: 936.54 GiB
14	02.10.2015 05:24:16	WARNING	SSL certificates not found.
13	02.10.2015 05:24:15	INFO	Démarre ThriftBackend: 0.0.0.0:7227
12	02.10.2015 05:24:15	INFO	Temps de téléchargement : True
11	02.10.2015 05:24:15	INFO	Plugins désactivés: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, MergeFiles, MultiHome, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPPInterface
10	02.10.2015 05:24:15	INFO	Plugins activés: AntiStandby, ClickAndLoad, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
9	02.10.2015 05:24:15	DEBUG	ADDON ExternalScripts: Deprecated method `event_list`, use `event_map` instead
8	02.10.2015 05:24:15	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
7	02.10.2015 05:24:15	ERROR	Erreur d'importation LinkdecrypterComHook : No module named MultiHook
6	02.10.2015 05:24:15	DEBUG	created index of plugins
5	02.10.2015 05:24:15	ERROR	OpenloadIo a un format invalide.
4	02.10.2015 05:24:14	ERROR	OpenloadIo a un format invalide.
3	02.10.2015 05:24:14	DEBUG	Remote activated: True
2	02.10.2015 05:24:14	INFO	Utilisation du dossier principal : /volume1/.@plugins/AppCentral/pyload/config
1	02.10.2015 05:24:14	INFO	Démarrage pyLoad 0.4.9

**Comment by milanhlavin** [comment]
I have similar issue with account 
INFO	ACCOUNT FastshareCz: Grabbing account info for user `milan.hlavin`...
WARNING	ACCOUNT FastshareCz: Error loading info for user `milan.hlavin` | global name 're' is not defined

**Comment by vuolter** [comment]
@milanhlavin Relogin issue fixed.
@Spartanineo Alldebrid return a request flooding error. Investigating...

**Comment by Spartanineo** [comment]
Okay thank you

**Comment by milanhlavin** [comment]
Now is working for account on FastshareCz and EuroshareEu 
Thanks a lot.

**Comment by damien599901** [comment]
@vuolter Alldebrid works with the "premium account" but only with UpToBox (issues with 1fichier, uploaded, turbobit, rapidgator etc etc)

**Comment by Spartanineo** [comment]
@vuolter  I have the same thing, the account is seen valid but I can use only uptobox and a file has the time

**Comment by Spartanineo** [comment]
Maintaining my alldebrid account is recognized, but the automatic reconnexion does not work.

150	04.10.2015 09:29:16	DEBUG	HOSTER UptoboxCom[24]: WAIT set to 2699 seconds | Previous waitUntil: 0.000000
151	04.10.2015 09:29:16	DEBUG	HOSTER UptoboxCom[24]: RECONNECT required | Previous wantReconnect: False
152	04.10.2015 09:29:16	INFO	HOSTER UptoboxCom[24]: Waiting 2699 seconds...
153	04.10.2015 09:29:16	INFO	HOSTER UptoboxCom[24]: Requiring reconnection...
154	04.10.2015 09:29:17	DEBUG	HOSTER UptoboxCom[25]: Config option `use_premium` not found, use default `True`
155	04.10.2015 09:29:30	WARNING	Reconnect script not found!
156	04.10.2015 09:32:14	DEBUG	Cleared Result cache

**Comment by Spartanineo** [comment]
Again my account alldebrid is not recognized.

**Comment by gregus69** [comment]
no news or update for plugin alldebrid ?

**Comment by B1GPY** [comment]
please fix alldebrid issue

**Comment by keshav2609** [comment]
up up

**Comment by GammaC0de** [comment]
Issue seems to be solved now.

**Comment by keshav2609** [comment]
Soldes thanks

**Comment by keshav2609** [comment]
Solved thanks
