### ISSUE TITLE
Uploaded.to hoster plugin not working

### ISSUE THREAD

**Issue by realwax** [pyload/pyload#1909]
Hi,

Only free DL works as premium can't login due to float operation failing.

438	01.10.2015 14:29:48	WARNING	ACCOUNT UploadedTo: Error loading info for user `abcdefg` | invalid literal for float(): 508.77gb
![image](https://cloud.githubusercontent.com/assets/14924590/10220684/a381a966-6849-11e5-8363-c49f21ea5dd1.png)

After fixing trafficleft = self.parse_traffic(size + unit) with trafficleft = self.parse_traffic(size, unit)
the following error occurs

598	01.10.2015 15:29:40	WARNING	Download failed: userplugins.201507.working.tar.gz | get_data() got an unexpected keyword argument 'refresh'
599	01.10.2015 15:29:40	DEBUG	Error creating zip file: 'ascii' codec can't decode byte 0xb4 in position 10: ordinal not in range(128)

Thank you 

cheers
Wax

**Comment by mattionline** [comment]
Push. Same issue

**Comment by vuolter** [comment]
Your plugins are not up-to-date. You can delete the userplugins directory to force a full update (but you lose your custom plugins if you have any).
