### ISSUE TITLE
MultiHook.py and PremiumizeMeHook.py gone

### ISSUE THREAD

**Issue by realwax** [pyload/pyload#1910]
Obviously the latest commit removed internal/MultiHook.py and hooks/PremiumizeMeHook.py 
Before that PremiumizeMeHook.py was not retrieving hosters properly. Now it's deleted. Even when restoring the files it won't work.

Any fix/idea? 

Thank you very much

Cheers
Wax

**Comment by vuolter** [comment]
MultiHoster handling is currently under changing.

**Comment by psych0d0g** [comment]
is this fixed again? i still cant use premiumize.me at all
