### ISSUE TITLE
alldebrid plugin "Processing as free download". 

### ISSUE THREAD

**Issue by damien599901** [pyload/pyload#1911]
Dear all

i have this on my second device. I have 2 devices but i can only use one of my device my alldebrid account (premium account) 

Log 
107 01.10.2015 18:33:07 INFO    ACCOUNT AlldebridCom: Relogin user `damien599901`...
108 01.10.2015 18:33:07 INFO    ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
109 01.10.2015 18:33:08 WARNING ACCOUNT AlldebridCom: Error loading info for user `damien599901` | syntax error: line 1, column 0
110 01.10.2015 18:33:23 INFO    Download starts: Terminator.Genisys.2015.FRENCH.BDRip.XviD-GLUPS.zone-telechargement.com.avi
111 01.10.2015 18:33:23 INFO    HOSTER UptoboxCom[2]: Updating file info...
112 01.10.2015 18:33:23 INFO    HOSTER UptoboxCom[2]: File name: Terminator.Genisys.2015.FRENCH.BDRip.XviD-GLUPS.zone-telechargement.com.avi
113 01.10.2015 18:33:23 INFO    HOSTER UptoboxCom[2]: File size: 1503238553 bytes
114 01.10.2015 18:33:23 INFO    HOSTER UptoboxCom[2]: File status: démarrage
115 01.10.2015 18:33:24 INFO    HOSTER UptoboxCom[2]: Processing as free download...
116 01.10.2015 18:33:24 WARNING Download failed: Terminator.Genisys.2015.FRENCH.BDRip.XviD-GLUPS.zone-telechargement.com.avi | first argument must be string or compiled pattern
117 01.10.2015 18:33:24 INFO    ADDON UnSkipOnFail: Looking for skipped duplicates of: Terminator.Genisys.2015.FRENCH.BDRip.XviD-GLUPS.zone-telechargement.com.avi (pid:2)
118 01.10.2015 18:33:24 INFO    ADDON UnSkipOnFail: No duplicates found
119 01.10.2015 18:33:31 INFO    ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
120 01.10.2015 18:33:31 WARNING ACCOUNT AlldebridCom: Error loading info for user `damien599901` | syntax error: line 1, column 0

thank you by advance  to Sensei @vuolter ;) 
but how can i do a donation for the help and for pyLoad? Somebody could explain me how to?

**Comment by twoDarkMessiah** [comment]
@damien599901 
same problem (Processing as free download...) happend to me on multiple plugins including Uploaded and ShareOnline.
I'm using the current 'stable' from github.

Downloads at pyload.org are down since a while...

**Comment by damien599901** [comment]
Other log  @vuolter 
01.10.2015 19:27:59	INFO	HOOK XFileSharingPro: Handling any crypter I can!
199	01.10.2015 19:27:59	INFO	pyLoad is up and running
200	01.10.2015 19:28:00	INFO	ADDON UpdateManager: No new pyLoad version available
201	01.10.2015 19:28:00	INFO	ADDON UpdateManager: No plugin updates available
202	01.10.2015 19:28:09	INFO	ADDON ClickAndLoad: Proxy listening on 127.0.0.1:9666
203	01.10.2015 19:28:37	CRITICAL	'super' object has no attribute '_setup'
204	01.10.2015 19:28:45	CRITICAL	'super' object has no attribute '_setup'
205	01.10.2015 19:28:54	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
206	01.10.2015 19:28:55	WARNING	ACCOUNT AlldebridCom: Error loading info for user `damien599901` | syntax error: line 1, column 0
207	01.10.2015 19:29:06	INFO	ACCOUNT AlldebridCom: Updating account info for user `damien599901`...
208	01.10.2015 19:29:06	INFO	ACCOUNT AlldebridCom: Relogin user `damien599901`...
209	01.10.2015 19:29:07	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
210	01.10.2015 19:29:08	WARNING	ACCOUNT AlldebridCom: Error loading info for user `damien599901` | syntax error: line 1, column 0
211	01.10.2015 19:29:15	INFO	ACCOUNT AlldebridCom: Updating account info for user `damien599901`...
212	01.10.2015 19:29:15	INFO	ACCOUNT AlldebridCom: Relogin user `damien599901`...
213	01.10.2015 19:29:16	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
214	01.10.2015 19:29:17	WARNING	ACCOUNT AlldebridCom: Error loading info for user `damien599901` | syntax error: line 1, column 0
215	01.10.2015 19:29:17	INFO	ACCOUNT AlldebridCom: Updating account info for user `damien599901`...
216	01.10.2015 19:29:17	INFO	ACCOUNT AlldebridCom: Relogin user `damien599901`...
217	01.10.2015 19:29:23	INFO	ACCOUNT AlldebridCom: Updating account info for user `damien599901`...
218	01.10.2015 19:29:23	INFO	ACCOUNT AlldebridCom: Relogin user `damien599901`...
219	01.10.2015 19:29:24	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
220	01.10.2015 19:29:24	WARNING	ACCOUNT AlldebridCom: Error loading info for user `damien599901` | syntax error: line 1, column 0
221	01.10.2015 19:29:34	INFO	ACCOUNT AlldebridCom: Updating account info for user `damien599901`...
222	01.10.2015 19:29:34	INFO	ACCOUNT AlldebridCom: Relogin user `damien599901`...
223	01.10.2015 19:29:35	INFO	ACCOUNT AlldebridCom: Removing user `damien599901`...
224	01.10.2015 19:29:49	INFO	ACCOUNT AlldebridCom: Adding user `damien599901`...
225	01.10.2015 19:29:49	INFO	ACCOUNT AlldebridCom: Login user `damien599901`...
226	01.10.2015 19:29:49	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
227	01.10.2015 19:29:50	WARNING	ACCOUNT AlldebridCom: Error loading info for user `damien599901` | syntax error: line 1, column 0
228	01.10.2015 19:29:57	INFO	ACCOUNT AlldebridCom: Updating account info for user `damien599901`...
229	01.10.2015 19:29:57	INFO	ACCOUNT AlldebridCom: Relogin user `damien599901`...
230	01.10.2015 19:29:58	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
231	01.10.2015 19:29:59	WARNING	ACCOUNT AlldebridCom: Error loading info for user `damien599901` | syntax error: line 1, column 0

**Comment by damien599901** [comment]
desinstatlation/ reinstallation 

22	01.10.2015 22:43:00	INFO	Starting pyLoad 0.4.9
23	01.10.2015 22:43:00	INFO	Using home directory: /volume1/.@plugins/AppCentral/pyload/config
24	01.10.2015 22:43:01	ERROR	OpenloadIo has a invalid pattern.
25	01.10.2015 22:43:01	ERROR	Error importing LinkdecrypterComHook: No module named MultiHook
26	01.10.2015 22:43:01	INFO	Activated plugins: AntiStandby, ClickAndLoad, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
27	01.10.2015 22:43:01	INFO	Deactivate plugins: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, MergeFiles, MultiHome, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPPInterface
28	01.10.2015 22:43:01	INFO	Downloadtime: True
29	01.10.2015 22:43:01	INFO	Starting ThriftBackend: 0.0.0.0:7227
30	01.10.2015 22:43:02	INFO	Starting threaded webserver: 0.0.0.0:9050
31	01.10.2015 22:43:02	INFO	Free space: 634.73 GiB
32	01.10.2015 22:43:02	INFO	Activating Accounts...
33	01.10.2015 22:43:02	INFO	Activating Plugins...
34	01.10.2015 22:43:02	WARNING	ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
35	01.10.2015 22:43:02	WARNING	ADDON AntiStandby: Unable to change display power state | [Errno 2] No such file or directory
36	01.10.2015 22:43:02	INFO	HOOK XFileSharingPro: Handling any hoster I can!
37	01.10.2015 22:43:02	INFO	HOOK XFileSharingPro: Handling any crypter I can!
38	01.10.2015 22:43:02	INFO	pyLoad is up and running
39	01.10.2015 22:43:03	INFO	ADDON UpdateManager: No new pyLoad version available
40	01.10.2015 22:43:03	INFO	ADDON UpdateManager: No plugin updates available
41	01.10.2015 22:43:12	INFO	ADDON ClickAndLoad: Proxy listening on 127.0.0.1:9666
42	01.10.2015 22:44:00	INFO	ACCOUNT AlldebridCom: Adding user `damien599901`...
43	01.10.2015 22:44:00	INFO	ACCOUNT AlldebridCom: Login user `damien599901`...
44	01.10.2015 22:44:01	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
45	01.10.2015 22:44:01	WARNING	ACCOUNT AlldebridCom: Error loading info for user `damien599901` | syntax error: line 1, column 0
46	01.10.2015 22:44:10	INFO	ACCOUNT AlldebridCom: Updating account info for user `damien599901`...
47	01.10.2015 22:44:10	INFO	ACCOUNT AlldebridCom: Relogin user `damien599901`...
48	01.10.2015 22:44:11	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
49	01.10.2015 22:44:11	WARNING	ACCOUNT AlldebridCom: Error loading info for user `damien599901` | syntax error: line 1, column 0

**Comment by damien599901** [comment]
Dear @vuolter, 

how to activate, with the terminal of my macbook, the debug log? 
PyLoad is installed on an ASUSTOR NAS. 
I have another device (another NAS) with PyLoad. 
if i use the alldebrid premium account on one device, the premium account is not recognized on the second one . Strange.

I will do a good donation when it will be solved ;)

**Comment by damien599901** [comment]
after the last update


230	02.10.2015 12:43:25	WARNING	ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
231	02.10.2015 12:43:25	WARNING	ADDON AntiStandby: Unable to change display power state | [Errno 2] No such file or directory
232	02.10.2015 12:43:25	INFO	HOOK XFileSharingPro: Handling any hoster I can!
233	02.10.2015 12:43:25	INFO	HOOK XFileSharingPro: Handling any crypter I can!
234	02.10.2015 12:43:25	INFO	pyLoad is up and running
235	02.10.2015 12:43:26	INFO	ADDON UpdateManager: No new pyLoad version available
236	02.10.2015 12:43:26	INFO	ADDON UpdateManager: No plugin updates available
237	02.10.2015 12:43:33	INFO	restarting pyLoad
238	02.10.2015 12:43:33	INFO	shutting down...
239	02.10.2015 12:43:33	WARNING	ADDON AntiStandby

**Comment by damien599901** [comment]
now the account is recognized on the 2 devices, but the button "reconnect" is red and i can only download as a free user

**Comment by damien599901** [comment]
155	02.10.2015 15:15:26	INFO	HOSTER UptoboxCom[3]: File size: 370986188 bytes
156	02.10.2015 15:15:26	INFO	HOSTER UptoboxCom[3]: File status: démarrage
157	02.10.2015 15:15:26	DEBUG	HOSTER UptoboxCom[3]: LOAD URL http://uptobox.com/tmxj6rus2t6y | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
158	02.10.2015 15:15:27	INFO	HOSTER UptoboxCom[3]: Processing as free download...
159	02.10.2015 15:15:27	DEBUG	HOSTER UptoboxCom[3]: Getting download link #1
160	02.10.2015 15:15:27	DEBUG	HOSTER UptoboxCom[3]: {u'rand': u'kvavvftsktyenikuzwpyngiv6ya55gcaswzlktq', u'file_size_real': u'370956714', u'method_premium': '', u'down_direct': u'1', u'referer': '', u'fname': u'Allegiance.S01E01.FRENCH.HDTV.XviD-ZT.www.Zone-Telechargement.com.avi', u'method_free': '', u'id': u'tmxj6rus2t6y', u'op': u'download2'}
161	02.10.2015 15:15:27	WARNING	CAPTCHA UptoboxCom[3]: ReCaptcha | Key pattern not found
162	02.10.2015 15:15:27	WARNING	CAPTCHA UptoboxCom[3]: SolveMedia | Key pattern not found
163	02.10.2015 15:15:27	INFO	HOSTER UptoboxCom[3]: Waiting -1443791727 seconds...
164	02.10.2015 15:15:27	DEBUG	HOSTER UptoboxCom[3]: LOAD URL http://uptobox.com/tmxj6rus2t6y | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'rand': u'kvavvftsktyenikuzwpyngiv6ya55gcaswzlktq', u'file_size_real': u'370956714', u'down_direct': u'1', u'referer': '', u'fname': u'Allegiance.S01E01.FRENCH.HDTV.XviD-ZT.www.Zone-Telechargement.com.avi', u'method_free': 'Free Download', u'id': u'tmxj6rus2t6y', u'op': u'download2'} | ref=True | just_header=False
165	02.10.2015 15:15:27	INFO	HOSTER UptoboxCom[3]: Downloading file...
166	02.10.2015 15:15:27	DEBUG	HOSTER UptoboxCom[3]: DOWNLOAD URL http://www18.uptobox.com/d/wmyuexome6r76xkqyilymazppqrbdtt354dy62s5i2nb44pxjc6bpdxk/Allegiance.S01E01.FRENCH.HDTV.XviD-ZT.www.Zone-Telechargement.com.avi | cookies=True | get={} | disposition=True | post={} | ref=True
167	02.10.2015 15:17:10	DEBUG	Run Info Fetching for UptoboxCom
168	02.10.2015 15:17:10	INFO	Added package test containing 1 links
169	02.10.2015 15:17:11	DEBUG	Finished Info Fetching for UptoboxCom
170	02.10.2015 15:17:12	DEBUG	HOSTER UptoboxCom[4]: Config option `use_premium` not found, use default `True

**Comment by damien599901** [comment]
now i have this issue with onefichier linked to my alldebrid premium account 

wait() got an unexpected keyword argument 'econnect'

**Comment by damien599901** [comment]
You re the man @vuolter !!!!!!!!!!!!!! ;) 

Alldebrid works now with Uptobox. thank you so much/ merci/ danke shon/ gracias/ gracie mille 
I will give a donation x 2 or x 3 !!!


But for 


a) https://1fichier.com/ i have this

313	02.10.2015 17:58:35	INFO	Added package Dada containing 1 links
314	02.10.2015 17:58:36	INFO	Download starts: https://1fichier.com/?yuxcune9s4
315	02.10.2015 17:58:36	INFO	HOSTER OneFichierCom[7]: Updating file info...
316	02.10.2015 17:58:38	INFO	HOSTER OneFichierCom[7]: File name: ?yuxcune9s4
317	02.10.2015 17:58:38	INFO	HOSTER OneFichierCom[7]: File size: Unknown
318	02.10.2015 17:58:38	INFO	HOSTER OneFichierCom[7]: File status: démarrage
319	02.10.2015 17:58:38	INFO	HOSTER OneFichierCom[7]: Looking for direct download link...
320	02.10.2015 17:58:39	INFO	HOSTER OneFichierCom[7]: Direct download link not found
321	02.10.2015 17:58:40	INFO	HOSTER OneFichierCom[7]: Updating file info...
322	02.10.2015 17:58:41	INFO	HOSTER OneFichierCom[7]: File name: Un.Peu.Beaucoup.Aveuglement.2015.FRENCH.DVDRIP.XVid-LYS-www.Zone-Telechargement.com.avi
323	02.10.2015 17:58:41	INFO	HOSTER OneFichierCom[7]: File size: 737987788 bytes
324	02.10.2015 17:58:41	INFO	HOSTER OneFichierCom[7]: Waiting 3000 seconds...
325	02.10.2015 17:58:41	INFO	HOSTER OneFichierCom[7]: Requiring reconnection...
326	02.10.2015 17:58:44	INFO	ACCOUNT AlldebridCom: Relogin user `damien599901`...
327	02.10.2015 17:58:45	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...



b) for turbobit 

28	02.10.2015 18:03:06	ERROR	Error importing TurbobitNet: /usr/local/AppCentral/pyload/repository/lib/python/Crypto/Cipher/_ARC4.so: undefined symbol: PyUnicodeUCS4_FromString
329	02.10.2015 18:03:06	INFO	Added package test containing 1 links
330	02.10.2015 18:03:07	ERROR	Error importing TurbobitNet: /usr/local/AppCentral/pyload/repository/lib/python/Crypto/Cipher/_ARC4.so: undefined symbol: PyUnicodeUCS4_FromString
331	02.10.2015 18:03:07	CRITICAL	'NoneType' object has no attribute 'TurbobitNet'


c) for uploaded => i ve a captcha like a "free account" 

357	02.10.2015 18:04:42	INFO	Added package test containing 1 links
358	02.10.2015 18:04:42	INFO	Download starts: http://uploaded.net/file/cp1oxu2p
359	02.10.2015 18:04:42	INFO	HOSTER UploadedTo[11]: Updating file info...
360	02.10.2015 18:04:43	INFO	HOSTER UploadedTo[11]: File name: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.avi
361	02.10.2015 18:04:43	INFO	HOSTER UploadedTo[11]: File size: 728195622 bytes
362	02.10.2015 18:04:43	INFO	HOSTER UploadedTo[11]: File status: démarrage
363	02.10.2015 18:04:43	INFO	HOSTER UploadedTo[11]: Processing as free download...
364	02.10.2015 18:04:48	INFO	ACCOUNT AlldebridCom: Relogin user `damien599901`...
365	02.10.2015 18:04:49	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...


d) and finally for Rapidgator
351	02.10.2015 18:06:25	INFO	Download restarted: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi |
352	02.10.2015 18:06:25	INFO	Download starts: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi
353	02.10.2015 18:06:25	INFO	HOSTER RapidgatorNet[9]: Updating file info...
354	02.10.2015 18:06:26	INFO	HOSTER RapidgatorNet[9]: File name: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi
355	02.10.2015 18:06:26	INFO	HOSTER RapidgatorNet[9]: File size: 1471026298 bytes
356	02.10.2015 18:06:26	INFO	HOSTER RapidgatorNet[9]: File status: démarrage
357	02.10.2015 18:06:27	INFO	HOSTER RapidgatorNet[9]: Processing as free download...
358	02.10.2015 18:06:27	INFO	HOSTER RapidgatorNet[9]: Waiting 1 seconds...
359	02.10.2015 18:06:29	INFO	Download restarted: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi |
360	02.10.2015 18:06:30	INFO	Download starts: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi
361	02.10.2015 18:06:30	INFO	HOSTER RapidgatorNet[9]: Updating file info...
362	02.10.2015 18:06:30	INFO	HOSTER RapidgatorNet[9]: File name: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi
363	02.10.2015 18:06:30	INFO	HOSTER RapidgatorNet[9]: File size: 1471026298 bytes
364	02.10.2015 18:06:30	INFO	HOSTER RapidgatorNet[9]: File status: démarrage
365	02.10.2015 18:06:31	INFO	HOSTER RapidgatorNet[9]: Processing as free download...
366	02.10.2015 18:06:31	INFO	HOSTER RapidgatorNet[9]: Waiting 1 seconds...
367	02.10.2015 18:06:33	INFO	Download restarted: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi |
368	02.10.2015 18:06:33	INFO	Download starts: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi
369	02.10.2015 18:06:33	INFO	HOSTER RapidgatorNet[9]: Updating file info...
370	02.10.2015 18:06:34	INFO	HOSTER RapidgatorNet[9]: File name: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi
371	02.10.2015 18:06:34	INFO	HOSTER RapidgatorNet[9]: File size: 1471026298 bytes
372	02.10.2015 18:06:34	INFO	HOSTER RapidgatorNet[9]: File status: démarrage
373	02.10.2015 18:06:34	INFO	HOSTER RapidgatorNet[9]: Processing as free download...
374	02.10.2015 18:06:34	INFO	HOSTER RapidgatorNet[9]: Waiting 1 seconds...
375	02.10.2015 18:06:36	INFO	Download restarted: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi |
376	02.10.2015 18:06:37	INFO	Download starts: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi
377	02.10.2015 18:06:37	INFO	HOSTER RapidgatorNet[9]: Updating file info...
378	02.10.2015 18:06:37	INFO	HOSTER RapidgatorNet[9]: File name: The.Humbling.2014.TRUEFRENCH.BDRip.XviD.AC3.avi
379	02.10.2015 18:06:37	INFO	HOSTER RapidgatorNet[9]: File size: 1471026298 bytes
380	02.10.2015 18:06:37	INFO	HOSTER RapidgatorNet[9]: File status: démarrage
381	02.10.2015 18:06:38	INFO	HOSTER RapidgatorNet[9]: Processing as free download...

**Comment by damien599901** [comment]
i ve closed by error
sorry :(

**Comment by damien599901** [comment]
new log for RapidGator @vuolter 

57	02.10.2015 22:17:21	INFO	HOSTER RapidgatorNet[14]: File name: New.Kids.Nitro.2012.VOSTFR.DVDRip.XViD-www.Zone-Telechargement.com.avi.html
558	02.10.2015 22:17:21	INFO	HOSTER RapidgatorNet[14]: File size: Unknown
559	02.10.2015 22:17:21	INFO	HOSTER RapidgatorNet[14]: File status: démarrage
560	02.10.2015 22:17:51	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.

**Comment by damien599901** [comment]
and finally @vuolter for Turbobit 
'NoneType' object has no attribute '

611	02.10.2015 22:19:12	WARNING	Download failed: New.Kids.Nitro.2012.VOSTFR.DVDRip.XViD-www.Zone-Telechargement.com.avi | Max retries reached
612	02.10.2015 22:19:12	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: New.Kids.Nitro.2012.VOSTFR.DVDRip.XViD-www.Zone-Telechargement.com.avi (pid:13)
613	02.10.2015 22:19:12	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by damien599901** [comment]
@vuolter  : new issue with Uptobox
Works only with one link. the second one is in the queue :(
Thanks by advance for your great work

Log 

483	03.10.2015 11:14:23	INFO	Free space: 630.10 GiB
484	03.10.2015 11:14:23	INFO	Activating Accounts...
485	03.10.2015 11:14:23	INFO	ACCOUNT AlldebridCom: Adding user `damien599901`...
486	03.10.2015 11:14:23	INFO	ACCOUNT AlldebridCom: Login user `damien599901`...
487	03.10.2015 11:14:24	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
488	03.10.2015 11:14:25	INFO	Activating Plugins...
489	03.10.2015 11:14:25	WARNING	ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
490	03.10.2015 11:14:25	WARNING	ADDON AntiStandby: Unable to change display power state | [Errno 2] No such file or directory
491	03.10.2015 11:14:25	INFO	HOOK XFileSharingPro: Handling any hoster I can!
492	03.10.2015 11:14:25	INFO	HOOK XFileSharingPro: Handling any crypter I can!
493	03.10.2015 11:14:25	INFO	pyLoad is up and running
494	03.10.2015 11:14:25	INFO	ADDON UpdateManager: No new pyLoad version available
495	03.10.2015 11:14:25	INFO	ADDON UpdateManager: No plugin updates available
496	03.10.2015 11:14:35	INFO	ADDON ClickAndLoad: Proxy listening on 127.0.0.1:9666
497	03.10.2015 11:30:15	INFO	Added package Livia séries containing 2 links
498	03.10.2015 11:30:16	INFO	Download starts: greys.anatomy.s12e02.fastsub.www.vostfr-vf.com.avi
499	03.10.2015 11:30:16	INFO	HOSTER UptoboxCom[12]: Updating file info...
500	03.10.2015 11:30:16	INFO	HOSTER UptoboxCom[12]: File name: greys.anatomy.s12e02.fastsub.www.vostfr-vf.com.avi
501	03.10.2015 11:30:16	INFO	HOSTER UptoboxCom[12]: File size: 361234432 bytes
502	03.10.2015 11:30:16	INFO	HOSTER UptoboxCom[12]: File status: démarrage
503	03.10.2015 11:30:16	INFO	HOSTER UptoboxCom[12]: Processing as free download...
504	03.10.2015 11:30:16	WARNING	CAPTCHA UptoboxCom[12]: ReCaptcha | Key pattern not found
505	03.10.2015 11:30:16	WARNING	CAPTCHA UptoboxCom[12]: SolveMedia | Key pattern not found
506	03.10.2015 11:30:16	INFO	HOSTER UptoboxCom[12]: Waiting -1443864616 seconds...
507	03.10.2015 11:30:17	INFO	HOSTER UptoboxCom[12]: Downloading file...
508	03.10.2015 11:30:18	INFO	Download starts: greys.anatomy.s12e01.fastsub.www.vostfr-vf.com.avi
509	03.10.2015 11:30:18	INFO	HOSTER UptoboxCom[13]: Updating file info...
510	03.10.2015 11:30:19	INFO	HOSTER UptoboxCom[13]: File name: greys.anatomy.s12e01.fastsub.www.vostfr-vf.com.avi
511	03.10.2015 11:30:19	INFO	HOSTER UptoboxCom[13]: File size: 368574464 bytes
512	03.10.2015 11:30:19	INFO	HOSTER UptoboxCom[13]: File status: démarrage
513	03.10.2015 11:30:19	INFO	HOSTER UptoboxCom[13]: Processing as free download...
514	03.10.2015 11:30:19	WARNING	HOSTER UptoboxCom[13]: 44 minutes, 58 seconds
515	03.10.2015 11:30:19	INFO	HOSTER UptoboxCom[13]: Waiting 2698 seconds...
516	03.10.2015 11:30:19	INFO	HOSTER UptoboxCom[13]: Requiring reconnection...

**Comment by damien599901** [comment]
Dear @vuolter ,

Alldebrid premium account does not work anymore :(
Please find my log below 

Good luck

370	04.10.2015 10:38:18	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
371	04.10.2015 10:38:18	DEBUG	HOSTER UptoboxCom[27]: Config option `use_premium` not found, use default `True`
372	04.10.2015 10:38:18	DEBUG	HOSTER UptoboxCom[27]: PROCESS URL http://uptobox.com/61mcsm0o6oei | PLUGIN VERSION 0.22
373	04.10.2015 10:38:18	INFO	HOSTER UptoboxCom[27]: Updating file info...
374	04.10.2015 10:38:19	DEBUG	HOSTER UptoboxCom[27]: File info: {'status': 2, 'url': u'http://uptobox.com/61mcsm0o6oei', 'size': 368574464.0, 'name': u'Scorpion.S01E01.FRENCH.LD.HDTV.XviD-ZT.zone-telechargement.com.avi', 'pattern': {'S': u'351.5', 'U': u'MB', 'N': u'Scorpion.S01E01.FRENCH.LD.HDTV.XviD-ZT.zone-telechargement.com.avi'}}
375	04.10.2015 10:38:19	DEBUG	HOSTER UptoboxCom[27]: Previous file info: {}
376	04.10.2015 10:38:19	INFO	HOSTER UptoboxCom[27]: File name: Scorpion.S01E01.FRENCH.LD.HDTV.XviD-ZT.zone-telechargement.com.avi
377	04.10.2015 10:38:19	INFO	HOSTER UptoboxCom[27]: File size: 368574464 bytes
378	04.10.2015 10:38:19	INFO	HOSTER UptoboxCom[27]: File status: démarrage
379	04.10.2015 10:38:19	DEBUG	HOSTER UptoboxCom[27]: LOAD URL http://uptobox.com/61mcsm0o6oei | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
380	04.10.2015 10:38:19	INFO	HOSTER UptoboxCom[27]: Processing as free download...
381	04.10.2015 10:38:19	DEBUG	HOSTER UptoboxCom[27]: Getting download link #1
382	04.10.2015 10:38:19	WARNING	HOSTER UptoboxCom[27]: 43 minutes, 7 seconds
383	04.10.2015 10:38:19	DEBUG	HOSTER UptoboxCom[27]: WAIT set to 2587 seconds | Previous waitUntil: 0.000000
384	04.10.2015 10:38:19	DEBUG	HOSTER UptoboxCom[27]: RECONNECT required | Previous wantReconnect: False
385	04.10.2015 10:38:19	INFO	HOSTER UptoboxCom[27]: Waiting 2587 seconds...
386	04.10.2015 10:38:19	INFO	HOSTER UptoboxCom[27]: Requiring reconnection...

**Comment by damien599901** [comment]
@vuolter : i don't see the link for give you a donation.
Where is it? 
cheers

**Comment by vuolter** [comment]
There is no link. D:

**Comment by damien599901** [comment]
@vuolter 

"Below you find an excerpt of pyLoads plugins and features. For more information and some tutorials take a look into the pyLoad Community Wiki.

If you want to support our work you can donate, vote or tell you friends here: " 

Seen here : http://pyload.org/

**Comment by damien599901** [comment]
@vuolter @GammaC0de  : nothing works anymore (uptobox, uploaded, 1fichier, rapidgator, turtobit etc)
=> all works as "free account" :( 
i m sad

**Comment by vuolter** [comment]
Multihosters will keep not working until the Multi Account plugin will be incomplete. u.u

**Comment by damien599901** [comment]
what does it mean @vuolter : "Multi Account ...incomplete"?
thank you
regards

**Comment by joberreiter** [comment]
> [...] till the Multi Account plugin will be incomplete [...]

... till the MultiAccount-Plugin will be complete--that means he is working on the MultiAccount-Plugin.

**Comment by B1GPY** [comment]
Same problem here.
All downloads processed as free, like Alldebrid account isn't used.

Any solution to this issue?

**Comment by GammaC0de** [comment]
I suppose this can be closed by now...
