### ISSUE TITLE
'super' object has no attribute '_setup'

### ISSUE THREAD

**Issue by godfuture** [pyload/pyload#1913]
**Background**
I tried to add a dlc. After adding the package nothing happened, no package visible. No errors in log. I tried to add a link from this dlc.

**Issue**
When starting a download with SO, an error occurs:
```
2076	01.10.2015 20:53:33	CRITICAL	'super' object has no attribute '_setup'
2075	01.10.2015 20:53:33	INFO	Added package test containing 1 links
2074	01.10.2015 20:53:33	WARNING	Info Fetching for ShareonlineBiz failed | global name 'parse_fileInfo' is not defined 
```

**Comment by tatu007** [comment]
Hello,

Same problem when i try to add a package :

```
78	01.10.2015 22:31:01	DEBUG	Run Info Fetching for OneFichierCom
79	01.10.2015 22:31:01	WARNING	Info Fetching for OneFichierCom failed | global name 'parse_fileInfo' is not defined
80	01.10.2015 22:31:01	CRITICAL	'super' object has no attribute '_setup' 
```

**Comment by bollstedt** [comment]
Hey,

same here with uploaded.to:
01.10.2015 23:09:05	CRITICAL	'super' object has no attribute '_setup'
76	01.10.2015 23:09:07	CRITICAL	'super' object has no attribute '_setup'
77	01.10.2015 23:09:39	INFO	ACCOUNT UploadedTo: Grabbing account info for user `10255597`...
78	01.10.2015 23:09:55	CRITICAL	'super' object has no attribute '_setup'
79	01.10.2015 23:09:57	CRITICAL	'super' object has no attribute '_setup'

**Comment by vuolter** [comment]
This issue is fixed. Next! :sob:
