### ISSUE TITLE
pycurl error 6: Couldn't resolve host 'http'

### ISSUE THREAD

**Issue by must4rd** [pyload/pyload#1917]
Getting this problem now after updates with uploaded.to
ERROR	pycurl error 6: Couldn't resolve host 'http'
anyone else and any idea?

**Comment by vuolter** [comment]
Firstly, post the debug log...

**Comment by must4rd** [comment]
02.10.2015 01:37:30	INFO	ACCOUNT UploadedTo: Adding user `11945075`...
70	02.10.2015 01:37:30	INFO	ACCOUNT UploadedTo: Login user `11945075`...
71	02.10.2015 01:37:30	INFO	ACCOUNT UploadedTo: Grabbing account info for user `11945075`...
72	02.10.2015 01:37:30	WARNING	ACCOUNT UploadedTo: Error loading info for user `11945075` | (6, "Couldn't resolve host 'http'")
73	02.10.2015 01:38:16	INFO	ACCOUNT UploadedTo: Grabbing account info for user `11945075`...
74	02.10.2015 01:38:16	WARNING	ACCOUNT UploadedTo: Error loading info for user `11945075` | (6, "Couldn't resolve host 'http'")
75	02.10.2015 01:38:16	INFO	Download starts: 81X7NnI0jJvNnXIzik93611DT.part09.rar
76	02.10.2015 01:38:16	INFO	ACCOUNT UploadedTo: Grabbing account info for user `11945075`...
77	02.10.2015 01:38:16	WARNING	ACCOUNT UploadedTo: Error loading info for user `11945075` | (6, "Couldn't resolve host 'http'")
78	02.10.2015 01:38:16	INFO	HOSTER UploadedTo[410]: Updating file info...
79	02.10.2015 01:38:16	INFO	HOSTER UploadedTo[410]: File name: 81X7NnI0jJvNnXIzik93611DT.part09.rar
80	02.10.2015 01:38:16	INFO	HOSTER UploadedTo[410]: File size: 806347862 bytes
81	02.10.2015 01:38:16	INFO	HOSTER UploadedTo[410]: File status: starte
82	02.10.2015 01:38:17	ERROR	pycurl error 6: Couldn't resolve host 'http'

**Comment by youlJunior** [comment]
It comes withe the last commit in Plugin.py (Fixpack (1)).

In fixurl function, this line has been added : 
````
newurl = re.sub(r'/{2,}', '/', newurl).strip().lstrip('.')
````
This line transform all multiple slash to unique slash, but unfortunately it does it even for the first occurence which is after protocol.

Example : 

https://1fichier.com/?mu1l5hck77
becomes
https:/1fichier.com/?mu1l5hck77

**Comment by youlJunior** [comment]
You can use something like that : 

````
import re
import urlparse

testurl = 'http://www.example.com//path?foo=bar'

parsed = list(urlparse.urlparse(testurl))
parsed[2] = re.sub("/{2,}", "/", parsed[2]) # replace two or more / with one
cleaned = urlparse.urlunparse(parsed)

print cleaned
# http://www.example.com/path?foo=bar
````

**Comment by vuolter** [comment]
@youlJunior My bad...
