### ISSUE TITLE
fixurl function still not ok

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1919]
Hi,
after 4e6234d8530c513ae37307f57d65c8c2b56efb1f `fixurl` still does not function as expected
for example `self.fixurl('../captcha/captcha.php?namespace=container')` returns `https:/captcha/captcha.php?namespace=container` instead of `https://www.filecrypt.cc//captcha/captcha.php?namespace=container`

before 4e6234d8530c513ae37307f57d65c8c2b56efb1f  it had returned ` https://www.filecrypt.cc/../captcha/captcha.php?namespace=container`

`pyfile.url` is `https://www.filecrypt.cc/Container/9C2AC73E4F.html`

**Comment by vuolter** [comment]
Just fixed.
