### ISSUE TITLE
UpdateManager

### ISSUE THREAD

**Issue by orson74** [pyload/pyload#1925]
WARNING	ADDON UpdateManager: Unable to retrieve server to get updates

**Comment by vuolter** [comment]
Replace UpdateManager plugin you found under [your config]/userplugins/hooks with this https://raw.githubusercontent.com/pyload/pyload/stable/module/plugins/hooks/UpdateManager.py

**Comment by zhaobb** [comment]
After replace UpdateManager.py file and restart, it showed the below error:

ERROR	Error executing hooks: 'UpdateManager' object has no attribute 'start_periodical'
INFO	pyLoad is up and running
DEBUG	ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
WARNING	ADDON UpdateManager: Unable to retrieve server to get updates

**Comment by vuolter** [comment]
@zhaobb Not possible. See: http://forum.pyload.org/viewtopic.php?f=7&t=4335
