### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by orson74** [pyload/pyload#1926]
CRITICAL    'NoneType' object has no attribute 'PLUGIN_DOMAIN'

**Comment by vuolter** [comment]
As always I say, No debug log, no fun.

**Comment by orson74** [comment]
Log or where i find the debug.log

**Comment by driet** [comment]
1) enable debug in general settings
2) restart the broken file
3) filesystem, navigate to pyload/data

**Comment by vuolter** [comment]
@driet plus you can see the log under the tab "Logs" by web interace.

**Comment by driet** [comment]
the debug info in /data seems to be more detailed then in /log ...

**Comment by vuolter** [comment]
But post something... XD

**Comment by orson74** [comment]
just a moment please

**Comment by vuolter** [comment]
Don't worry. ;)

**Comment by orson74** [comment]
02.10.2015 11:19:13 INFO      starte pyLoad 0.4.9
02.10.2015 11:19:13 INFO      Benutze Home-Verzeichnis: /share/MD0_DATA/.qpkg/pyload/data
02.10.2015 11:19:13 DEBUG     Remote activated: True
02.10.2015 11:19:21 ERROR     OpenloadIo hat ein ungültiges Muster.
02.10.2015 11:19:23 DEBUG     created index of plugins
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.hooks.LinkdecrypterComHook -> userplugins.hooks.LinkdecrypterComHook
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.internal.MultiHook -> userplugins.internal.MultiHook
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.internal.Hook -> userplugins.internal.Hook
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.crypter.LinkdecrypterCom -> userplugins.crypter.LinkdecrypterCom
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.internal.MultiCrypter -> userplugins.internal.MultiCrypter
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.internal.SimpleCrypter -> userplugins.internal.SimpleCrypter
02.10.2015 11:19:23 ERROR     Fehler beim importieren von LinkdecrypterCom: invalid syntax (SimpleCrypter.py, line 160)
02.10.2015 11:19:23 WARNING   Konnte LinkdecrypterComHook nicht aktivieren
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.hooks.AntiVirus -> userplugins.hooks.AntiVirus
02.10.2015 11:19:23 ERROR     Fehler beim importieren von AntiVirus: invalid syntax (AntiVirus.py, line 88)
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
02.10.2015 11:19:23 DEBUG     ADDON ExternalScripts: Deprecated method `event_list`, use `event_map` instead
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.hooks.Checksum -> userplugins.hooks.Checksum
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
02.10.2015 11:19:23 DEBUG     Redirected import module.plugins.hooks.UserAgentSwitcher -> userplugins.hooks.UserAgentSwitcher
02.10.2015 11:19:23 INFO      Aktivierte Plugins: Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager, UserAgentSwitcher
02.10.2015 11:19:23 INFO      Deaktivierte Plugins: AlldebridComHook, AndroidPhoneNotify, AntiStandby, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMe, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, TransmissionRPC, UnSkipOnFail, WindowsPhoneNotify, XFileSharingPro, XMPPInterface, ZeveraComHook
02.10.2015 11:19:23 INFO      Downloadzeit: True
02.10.2015 11:19:24 INFO      Starte ThriftBackend: 0.0.0.0:7200
02.10.2015 11:19:24 INFO      Freier Speicher: 549.63 GiBGB
02.10.2015 11:19:24 INFO      Aktiviere Accounts...
02.10.2015 11:19:27 DEBUG     Redirected import module.plugins.accounts.PremiumizeMe -> userplugins.accounts.PremiumizeMe
02.10.2015 11:19:27 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
02.10.2015 11:19:27 INFO      Starting builtin webserver: 0.0.0.0:8100
02.10.2015 11:19:27 INFO      ACCOUNT PremiumizeMe: Adding user `XXXXXXX`...
02.10.2015 11:19:27 INFO      ACCOUNT PremiumizeMe: Login user `XXXXXXX`...
02.10.2015 11:19:27 DEBUG     ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php | decode=True | cookies=True | 
get={'params[pass]': 'XXX', 'params[login]': 'XXX', 'method': 'accountstatus'} | req=None | multipart=False | post={} | ref=True | 
just_header=False
02.10.2015 11:19:27 INFO      ACCOUNT PremiumizeMe: Grabbing account info for user `XXXXXX`...
02.10.2015 11:19:27 DEBUG     ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php | decode=True | cookies=True | 
get={'params[pass]': 'XXX', 'params[login]': 'XXX', 'method': 'accountstatus'} | req=None | multipart=False | post={} | ref=True | 
just_header=False
02.10.2015 11:19:28 WARNING   ACCOUNT PremiumizeMe: Error loading info for user `XXX` | (6, "Couldn't resolve host 'http'")
02.10.2015 11:19:28 DEBUG     ACCOUNT PremiumizeMe: Account info for user `XXX`: {'login': {'timestamp': 1443777567.533185, 'password': '**********', 
'valid': None}, 'data': {'validuntil': None, 'maxtraffic': None, 'premium': None, 'options': {'limitdl': ['0']}, 'trafficleft': None}}
02.10.2015 11:19:28 INFO      Activating Plugins...
02.10.2015 11:19:28 DEBUG     Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
02.10.2015 11:19:28 DEBUG     Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
02.10.2015 11:19:28 DEBUG     Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
02.10.2015 11:19:28 DEBUG     ADDON ExtractArchive: Found UnRar 3.60 | Found SevenZip 9.04
02.10.2015 11:19:28 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | decode=True | cookies=True | get={'v': '0.4.9'} | req=None | multipart=False | post={} | ref=True | just_header=False
02.10.2015 11:19:28 INFO      pyLoad is up and running
02.10.2015 11:19:29 WARNING   ADDON UpdateManager: Unable to retrieve server to get updates
02.10.2015 11:19:38 INFO      ADDON ClickAndLoad: Proxy listening on 0.0.0.0:9666
02.10.2015 11:20:21 DEBUG     Redirected import module.plugins.hoster.RapidgatorNet -> userplugins.hoster.RapidgatorNet
02.10.2015 11:20:21 INFO      Added package Test containing 1 links
02.10.2015 11:20:21 DEBUG     Redirected import module.plugins.captcha.AdsCaptcha -> userplugins.captcha.AdsCaptcha
02.10.2015 11:20:21 DEBUG     Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
02.10.2015 11:20:21 DEBUG     Redirected import module.plugins.internal.Captcha -> userplugins.internal.Captcha
02.10.2015 11:20:21 DEBUG     Redirected import module.plugins.captcha.ReCaptcha -> userplugins.captcha.ReCaptcha
02.10.2015 11:20:21 DEBUG     Redirected import module.plugins.captcha.SolveMedia -> userplugins.captcha.SolveMedia
02.10.2015 11:20:21 DEBUG     Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
02.10.2015 11:20:21 DEBUG     Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
02.10.2015 11:20:22 DEBUG     Redirected import module.plugins.internal.Base -> userplugins.internal.Base
02.10.2015 11:20:22 DEBUG     Run Info Fetching for RapidgatorNet
02.10.2015 11:20:22 DEBUG     Finished Info Fetching for RapidgatorNet
02.10.2015 11:20:23 DEBUG     Redirected import module.plugins.accounts.RapidgatorNet -> userplugins.accounts.RapidgatorNet
02.10.2015 11:20:23 INFO      Download starts: http://rapidgator.net/file/dfef1ed9ac596840e5405979498e4fba
02.10.2015 11:20:23 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
02.10.2015 11:20:23 DEBUG     HOSTER RapidgatorNet[2543]: PROCESS URL http://rapidgator.net/file/dfef1ed9ac596840e5405979498e4fba | PLUGIN VERSION 0.36
02.10.2015 11:20:23 INFO      HOSTER RapidgatorNet[2543]: Updating file info...
02.10.2015 11:20:23 DEBUG     HOSTER RapidgatorNet[2543]: File info: {'status': 2, 'url': u'http:/rapidgator.net/file/dfef1ed9ac596840e5405979498e4fba', 'size': 12048138.24, 'name': 'b0bb2.Discover.English.Global.1.Test.Book.pdf', 'pattern': {'S': u'11.49', 'U': u'MB', 'N': u'b0bb2.Discover.English.Global.1.Test.Book.pdf'}}
02.10.2015 11:20:23 DEBUG     HOSTER RapidgatorNet[2543]: Previous file info: {}
02.10.2015 11:20:23 INFO      HOSTER RapidgatorNet[2543]: File name: b0bb2.Discover.English.Global.1.Test.Book.pdf
02.10.2015 11:20:23 INFO      HOSTER RapidgatorNet[2543]: File size: 12048138 bytes
02.10.2015 11:20:23 INFO      HOSTER RapidgatorNet[2543]: File status: starte
02.10.2015 11:20:23 DEBUG     HOSTER RapidgatorNet[2543]: LOAD URL http://rapidgator.net/file/dfef1ed9ac596840e5405979498e4fba | decode=True | cookies=[('rapidgator.net', 'lang', 'en')] | get={} | req=None | multipart=False | post={} | ref=False | just_header=False
02.10.2015 11:20:24 DEBUG     pycurl exception 6: Couldn't resolve host 'http'
02.10.2015 11:20:24 ERROR     pycurl error 6: Couldn't resolve host 'http'
02.10.2015 11:20:24 DEBUG     Error creating zip file: [Errno 2] No such file or directory: 'tmp/RapidgatorNet'
02.10.2015 11:20:24 INFO      Debug Report written to debug_RapidgatorNet_02-10-2015_11-20-24.txt
02.10.2015 11:20:24 DEBUG     All downloads processed

**Comment by orson74** [comment]
pyLoad 0.4.9 Debug Report of RapidgatorNet 0.36 

TRACEBACK:
 Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/Base.py", line 201, in preprocessing
    return self._process(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/Hoster.py", line 79, in _process
    self.process(self.pyfile)
  File "/share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/SimpleHoster.py", line 282, in process
    self.preload()
  File "/share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/SimpleHoster.py", line 257, in preload
    decode=self.TEXT_ENCODING)
  File "/share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/Base.py", line 47, in wrapper
    return fn(self, *args, **kwargs)
  File "/share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/Base.py", line 379, in load
    return super(Base, self).load(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/Plugin.py", line 374, in load
    html = req.load(url, get, post, ref, bool(cookies), just_header, multipart, decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/share/MD0_DATA/.qpkg/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/pyload/module/network/HTTPRequest.py", line 202, in load
    self.c.perform()
error: (6, "Couldn't resolve host 'http'")
 

FRAMESTACK:

Frame preprocessing in /share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/Base.py at line 201
	                self = <Hoster RapidgatorNet>
	                args = (<DownloadThread(Thread-2, started daemon)>,)
	              kwargs = {}

Frame _process in /share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/Hoster.py at line 92
	                self = <Hoster RapidgatorNet>
	              thread = <DownloadThread(Thread-2, started daemon)>

Frame process in /share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/SimpleHoster.py at line 282
	              pyfile = PyFile 2543: b0bb2.Discover.English.Global.1.Test.Book.pdf@RapidgatorNet
	                self = <Hoster RapidgatorNet>

Frame preload in /share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/SimpleHoster.py at line 257
	                self = <Hoster RapidgatorNet>

Frame wrapper in /share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/Base.py at line 47
	                self = <Hoster RapidgatorNet>
	                args = (u'http://rapidgator.net/file/dfef1ed9ac596840e5405979498e4fba',)
	                  fn = <function load at 0xe0cbf0>
	              kwargs = {'cookies': [('rapidgator.net', 'lang', 'en')], 'decode': True, 'ref': False}

Frame load in /share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/Base.py at line 379
	                self = <Hoster RapidgatorNet>
	                args = (u'http://rapidgator.net/file/dfef1ed9ac596840e5405979498e4fba',)
	              kwargs = {'cookies': [('rapidgator.net', 'lang', 'en')], 'decode': True, 'ref': False}

Frame load in /share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/Plugin.py at line 374
	              decode = True
	             cookies = [('rapidgator.net', 'lang', 'en')]
	                 val = False
	                 get = {}
	                 url = u'http:/rapidgator.net/file/dfef1ed9ac596840e5405979498e4fba'
	                self = <Hoster RapidgatorNet>
	                 req = <module.network.Browser.Browser object at 0xe0ac38>
	           multipart = False
	                 key = 'just_header'
	                post = {}
	                 ref = False
	         just_header = False

Frame load in /share/MD0_DATA/.qpkg/pyload/module/network/Browser.py at line 97
	                self = <module.network.Browser.Browser object at 0xe0ac38>
	                args = (u'http:/rapidgator.net/file/dfef1ed9ac596840e5405979498e4fba',
 {},
 {},
 False,
 True,
 False,
 False,
 True)
	              kwargs = {}

Frame load in /share/MD0_DATA/.qpkg/pyload/module/network/HTTPRequest.py at line 202
	             cookies = True
	                 get = {}
	                 url = u'http:/rapidgator.net/file/dfef1ed9ac596840e5405979498e4fba'
	                self = <module.network.HTTPRequest.HTTPRequest instance at 0xdf5cd8>
	              decode = True
	             referer = False
	           multipart = False
	                post = {}
	         just_header = False


PLUGIN OBJECT DUMP: 

	  ADSCAPTCHA_PATTERN = '(http://api\\.adscaptcha\\.com/Get\\.aspx[^"\\\']+)'
	             API_URL = 'http://rapidgator.net/api/file'
	          CHECK_FILE = True
	       CHECK_TRAFFIC = False
	             COOKIES = [('rapidgator.net', 'lang', 'en')]
	         DIRECT_LINK = None
	         DISPOSITION = True
	    DL_LIMIT_PATTERN = None
	       ERROR_PATTERN = 'You have reached your (?:daily|hourly) downloads limit'
	         FILE_ERRORS = [('Html error',
  '\\A(?:\\s*<.+>)?((?:[\\w\\s]*(?:[Ee]rror|ERROR)\\s*\\:?)?\\s*\\d{3})(?:\\Z|\\s+)'),
 ('Request error', '([Aa]n error occured while processing your request)'),
 ('Html file', '\\A\\s*<!DOCTYPE html')]
	  HAPPY_HOUR_PATTERN = None
	     HASHSUM_PATTERN = None
	        INFO_PATTERN = None
	  IP_BLOCKED_PATTERN = None
	      JSVARS_PATTERN = "\\s+var\\s*(startTimerUrl|getDownloadUrl|captchaUrl|fid|secs)\\s*=\\s*\\'?(.*?)\\'?;"
	        LEECH_HOSTER = False
	   LINK_FREE_PATTERN = "return \\'(http://\\w+.rapidgator.net/.*)\\';"
	        LINK_PATTERN = None
	LINK_PREMIUM_PATTERN = None
	       LOGIN_ACCOUNT = False
	       LOGIN_PREMIUM = False
	        NAME_PATTERN = '<title>Download file (?P<N>.*)</title>'
	   NAME_REPLACEMENTS = []
	     OFFLINE_PATTERN = '>(File not found|Error 404)'
	PREMIUM_ONLY_PATTERN = 'You can download files up to|This file can be downloaded by premium only<'
	   RECAPTCHA_PATTERN = '"http://api\\.recaptcha\\.net/challenge\\?k=(.*?)"'
	  SIZE_LIMIT_PATTERN = None
	        SIZE_PATTERN = 'File size:\\s*<strong>(?P<S>[\\d.,]+) (?P<U>[\\w^_]+)</strong>'
	   SIZE_REPLACEMENTS = []
	  SOLVEMEDIA_PATTERN = 'http://api\\.solvemedia\\.com/papi/challenge\\.script\\?k=(.*?)"'
	TEMP_OFFLINE_PATTERN = None
	       TEXT_ENCODING = True
	    URL_REPLACEMENTS = []
	        WAIT_PATTERN = '(Delay between downloads must be not less than|Try again in).+'
	             account = False
	             captcha = <Captcha Captcha>
	         chunk_limit = 1
	           direct_dl = False
	                html = ''
	                info = {'folder': 'b0bb2.Discover.English.Global.1.Test.Book.pdf',
 'name': 'b0bb2.Discover.English.Global.1.Test.Book.pdf',
 'pattern': {'N': u'b0bb2.Discover.English.Global.1.Test.Book.pdf',
             'S': u'11.49',
             'U': u'MB'},
 'size': 12048138.24,
 'status': 2,
 'url': u'http:/rapidgator.net/file/dfef1ed9ac596840e5405979498e4fba'}
	                  js = <module.common.JsEngine.JsEngine instance at 0xaa57d8>
	          last_check = None
	       last_download = None
	           last_html = None
	            leech_dl = False
	             limitDL = 0
	                link = ''
	             multiDL = False
	             premium = False
	              pyfile = PyFile 2543: b0bb2.Discover.English.Global.1.Test.Book.pdf@RapidgatorNet
	              pyload = <__main__.Core object at 0x8683d0>
	                 req = <module.network.Browser.Browser object at 0xe0ac38>
	     resume_download = False
	             retries = {}
	            rst_free = False
	                 sid = None
	              thread = <DownloadThread(Thread-2, started daemon)>
	                user = None
	          wait_until = 0
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 12048138
	               abort = False
	              active = False
	               error = ''
	                  id = 2543
	                lock = <_RLock(None, 0)>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x8c6c10>
	         maxprogress = 100
	                name = 'b0bb2.Discover.English.Global.1.Test.Book.pdf'
	               order = 0
	           packageid = 446
	              plugin = <Hoster RapidgatorNet>
	         pluginclass = <class 'userplugins.hoster.RapidgatorNet.RapidgatorNet'>
	        pluginmodule = <module 'userplugins.hoster.RapidgatorNet' from '/share/MD0_DATA/.qpkg/pyload/data/userplugins/hoster/RapidgatorNet.pyc'>
	          pluginname = u'RapidgatorNet'
	            progress = 0
	         reconnected = False
	                size = 12048138
	              status = 8
	          statusname = None
	                 url = u'http://rapidgator.net/file/dfef1ed9ac596840e5405979498e4fba'
	           waitUntil = 0


CONFIG: 

{'desc': 'RapidgatorNet',
 'outline': 'Rapidgator.net hoster plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': True}}

**Comment by orson74** [comment]
The Problem with

DEBUG	Error creating zip file: [Errno 2] No such file or directory: 'tmp/RapidgatorNet'

i solved, with creating the directory

**Comment by kb0n** [comment]
As the initial error report did not show up in the log, here's a short log by me of the same error (on latest_stable, latest commit e6f7ba06c3) :
```
02.10.2015 18:56:05 DEBUG     Run Info Fetching for XFileSharingPro
02.10.2015 18:56:05 INFO      Added package sleepy containing 2 links
02.10.2015 18:56:06 CRITICAL  'NoneType' object has no attribute 'PLUGIN_DOMAIN'
Traceback (most recent call last):
  File "/home/osmc/Downloads/pyload/module/ThreadManager.py", line 276, in assignJob
    job.initPlugin()
  File "/home/osmc/Downloads/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/home/osmc/Downloads/pyload/module/PyFile.py", line 103, in initPlugin
    self.plugin = self.pluginclass(self)
  File "/home/osmc/Downloads/pyload/module/plugins/internal/Hoster.py", line 44, in __init__
    self._setup()
  File "/home/osmc/Downloads/pyload/module/plugins/hoster/XFileSharingPro.py", line 39, in _setup
    account_name     = self.__name__ if self.account.PLUGIN_DOMAIN is None else self.PLUGIN_NAME
AttributeError: 'NoneType' object has no attribute 'PLUGIN_DOMAIN'
02.10.2015 18:56:07 DEBUG     Finished Info Fetching for XFileSharingPro
```

**Comment by Cobraeti** [comment]
Hello, I'm facing the same error when trying to use a plugin located in the `USERDIR` folder tree.
I would like to share an updated version of DlProtectCom decrypter as the domain is now dl-protect.net, so I copied `DlProtectCom.py` as `DlProtectNet.py` and started tweaking it for the new domain but I get the same stack as @kb0n when a link is assigned to it... :cry:
I'm using the following Docker image: `linuxserver/pyload-ng:0.5.0`
And I'm putting the following content in `/config/plugins/decrypters/DlProtectNet.py` (USERDIR being `/config`):
```
# -*- coding: utf-8 -*-

import re
import urllib.parse

from ..base.simple_decrypter import SimpleDecrypter


class DlProtectNet(SimpleDecrypter):
    __name__ = "DlProtectNet"
    __type__ = "decrypter"
    __version__ = "0.14"
    __status__ = "testing"

    __pattern__ = r"https?://(?:www\.)?dl-protect\.net/(?P<id>\d+)\?fn=(?P<nameBase64>[a-zA-Z0-9+/]+(?:=|\%3D){,2})\&.*"
    __config__ = [
        ("enabled", "bool", "Activated", True),
        ("use_premium", "bool", "Use premium account if available", True),
        (
            "folder_per_package",
            "Default;Yes;No",
            "Create folder for each package",
            "Default",
        ),
        ("max_wait", "int", "Reconnect if waiting time is greater than minutes", 30),
    ]

    __description__ = """Dl-protect.net decrypter plugin"""
    __license__ = "GPLv3"
    __authors__ = [
        ("Walter Purcaro", "vuolter@gmail.com"),
        ("GammaC0de", "nitzo2001[AT]yahoo[DOT]com")
    ]

    def get_links(self):
        if "Cliquez sur continuer pour voir le(s) lien" in self.data:
            self.data = self.load(self.pyfile.url, post={"submit": "Continuer"})

        if 'img src="captcha.php' in self.data:
            captcha_code = self.captcha.decrypt(
                urllib.parse.urljoin(self.pyfile.url, "/captcha.php"), input_type="jpeg"
            )
            self.data = self.load(
                self.pyfile.url, post={"captchaCode": captcha_code, "submit": ""}
            )

            if "Le code de sécurité est incorrect" in self.data:
                self.retry_captcha()

        return re.findall(r'<a href="(?P<id>[^/].+?)">(?P=id)</a>', self.data)
```
When a link gets matched I see the following logs:
Line | Timestamp | Level | Module | Message
-- | -- | -- | -- | --
21645 | 2023-01-27 07:39:24 | INFO | pyload | Added package Test DlProtectNet containing 1 links
21646 | 2023-01-27 07:39:24 | ERROR | pyload | Error importing DlProtectNet: No module named 'pyload.plugins.decrypters.DlProtectNet'
21647 | ? | ? | ? | Traceback (most recent call last):
21648 | ? | ? | ? | File "/usr/lib/python3.10/site-packages/pyload/core/managers/plugin_manager.py", line 354, in load_module
21649 | ? | ? | ? | module = __import__(
21650 | ? | ? | ? | ModuleNotFoundError: No module named 'pyload.plugins.decrypters.DlProtectNet'
21651 | 2023-01-27 07:39:24 | ERROR | pyload | Error importing DlProtectNet: No module named 'pyload.plugins.decrypters.DlProtectNet'
21652 | ? | ? | ? | Traceback (most recent call last):
21653 | ? | ? | ? | File "/usr/lib/python3.10/site-packages/pyload/core/managers/plugin_manager.py", line 354, in load_module
21654 | ? | ? | ? | module = __import__(
21655 | ? | ? | ? | ModuleNotFoundError: No module named 'pyload.plugins.decrypters.DlProtectNet'
21656 | 2023-01-27 07:39:24 | CRITICAL | pyload | 'NoneType' object has no attribute 'DlProtectNet'
21657 | ? | ? | ? | Traceback (most recent call last):
21658 | ? | ? | ? | File "/usr/lib/python3.10/site-packages/pyload/core/managers/thread_manager.py", line 317, in assign_job
21659 | ? | ? | ? | job.init_plugin()
21660 | ? | ? | ? | File "/usr/lib/python3.10/site-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
21661 | ? | ? | ? | return func(self, *args, **kwargs)
21662 | ? | ? | ? | File "/usr/lib/python3.10/site-packages/pyload/core/datatypes/pyfile.py", line 96, in init_plugin
21663 | ? | ? | ? | self.pluginclass = getattr(
21664 | ? | ? | ? | AttributeError: 'NoneType' object has no attribute 'DlProtectNet'
