### ISSUE TITLE
WARNING	Not able to connect server for updates

### ISSUE THREAD

**Issue by SebaBoler** [pyload/pyload#1927]
After installed Payload on new QNAP NAS i get warning about "WARNING	Not able to connect server for updates".  I deleted folder userplugins and accounts , i tried replace and delete UpdateManager.py.

All these not working. How i can solve this problem ??

**Comment by vuolter** [comment]
See: https://github.com/pyload/pyload/issues/1925

**Comment by SebaBoler** [comment]
I replace file UpdateManager.py from my old version. Its working :)

**Comment by vuolter** [comment]
Oookay...

**Comment by Velociraptor85** [comment]
https://github.com/pyload/pyload/issues/1893 <- Solution
