### ISSUE TITLE
setup.py and pypi support

### ISSUE THREAD

**Issue by makefu** [pyload/pyload#1929]
Hi!

I'd love to see a streamlined installation process and an upload to pypi. That would make an installation on a generic system much easier, python setup.py install and all the executables are deployed in the path
I want to write a package for nixos but the current state of the project makes this feat quite hard.

Keep up the good work!

**Comment by vuolter** [comment]
pypi will supported in 0.4.10 .

**Comment by makefu** [comment]
awesome, thanks so much!

**Comment by hensing** [comment]
I'd like to write a port for FreeBSD 10.x and would like to see the PyPI support too :)

**Comment by makefu** [comment]
any updates on this issue? What are the blocking points, maybe i can help? when is milestone 0.5.x planned?

thanks for your continued efforts!

**Comment by vuolter** [comment]
@makefu These days I can not work on the code, but the PyPI support is already complete. ;)

**Comment by makefu** [comment]
@vuolter that sounds very promising, thanks very much!

**Comment by makefu** [comment]
@vuolter any updates? when searching in pypi there are a couple of projects with a similar name but no "official" pyload.
keep up your good work :+1:

**Comment by GammaC0de** [comment]
@makefu Last commit from "master" is one year old...

@vuolter Please release a beta version......

**Comment by makefu** [comment]
@GammaC0de haha you are right, weird that this branch contains a setup.py which almost works (apart `from import os.path as path` )

**Comment by makefu** [comment]
@vuolter any updates on this? i would love to instal pyload natively instead of running it inside a docker container

**Comment by makefu** [comment]
@GammaC0de i just saw the release 0.5.0 coming with pypi installation, great work! i will build the package asap 👍

**Comment by GammaC0de** [comment]
@makefu I'm afraid I don't think the version in pypi is ready for use.
