### ISSUE TITLE
Broken download-url Base.py --> Hoster.py

### ISSUE THREAD

**Issue by driet** [pyload/pyload#1932]
debug:

Frame wrapper in xxx/pyload/data/userplugins/internal/Base.py at line 47
	                self = <Hoster RapidgatorNet>
	                args = (u'http://pr30.rapidgator.net//?r=download/index&session_id=xxx',)
	                  fn = <function download at 0x168b030>
	              kwargs = {'disposition': True}

Frame download in xxx/pyload/data/userplugins/internal/Hoster.py at line 162
	             cookies = True
	                 key = 'ref'
	                 val = True
	                 get = {}
	                 url = u'http://pr30.rapidgator.ne/?r=download/index&session_id=xxx'
	                self = <Hoster RapidgatorNet>
	   download_location = u'Downloads/xxx'
	            filename = u'Downloads/xxx'
	     download_folder = u'Downloads'
	            location = u'Downloads/xxx'
	         disposition = True
	                post = {}
	                 ref = True

**Comment by vuolter** [comment]
...I need a bit of context. u.u

**Comment by driet** [comment]
Sorry, here is more input: the download urls seem not to be parsed correctly:

The result is a broken link like in http://pr30.rapidgator.ne/?r=download/index&session_id=xxx

361	02.10.2015 10:38:05	DEBUG	HOSTER RapidgatorNet[514]: LOAD URL http://rapidgator.net/download/AjaxGetDownloadLink?sid=xxx | decode=True | cookies=True | get={} | req=None | multipart=False | post={} | ref=True | just_header=False
362	02.10.2015 10:38:05	DEBUG	HOSTER RapidgatorNet[514]: http://rapidgator.net/download/AjaxGetDownloadLink?sid=xxx | {"state":"done"}
363	02.10.2015 10:38:05	DEBUG	HOSTER RapidgatorNet[514]: LOAD URL http://rapidgator.net/download/captcha | decode=True | cookies=True | get={} | req=None | multipart=False | post={} | ref=True | just_header=False
364	02.10.2015 10:38:05	WARNING	CAPTCHA RapidgatorNet[514]: AdsCaptcha | Key or id pattern not found
365	02.10.2015 10:38:06	WARNING	CAPTCHA RapidgatorNet[514]: ReCaptcha | Key pattern not found
366	02.10.2015 10:38:06	DEBUG	CAPTCHA RapidgatorNet[514]: SolveMedia | Key: xxx
367	02.10.2015 10:38:06	DEBUG	CAPTCHA RapidgatorNet[514]: SolveMedia | Key: xxx
368	02.10.2015 10:38:06	DEBUG	HOSTER RapidgatorNet[514]: LOAD URL http://api.solvemedia.com/papi/challenge.noscript | decode=True | cookies=True | get={'k': u'xxx'} | req=None | multipart=False | post={} | ref=True | just_header=False
369	02.10.2015 10:38:06	DEBUG	CAPTCHA RapidgatorNet[514]: SolveMedia | Challenge: xxx
370	02.10.2015 10:38:06	DEBUG	CAPTCHA RapidgatorNet[514]: SolveMedia | LOAD URL http://api.solvemedia.com/papi/media | decode=False | cookies=True | get={'c': u'xxx'} | req= | multipart=False | post={} | ref=False | just_header=False
371	02.10.2015 10:38:19	DEBUG	CAPTCHA RapidgatorNet[514]: SolveMedia | Result: button fly
372	02.10.2015 10:38:19	DEBUG	HOSTER RapidgatorNet[514]: LOAD URL http://api.solvemedia.com/papi/verify.noscript | decode=True | cookies=True | get={} | req=None | multipart=False | xxx
374	02.10.2015 10:38:20	INFO	HOSTER RapidgatorNet[514]: Downloading file...
375	02.10.2015 10:38:20	DEBUG	HOSTER RapidgatorNet[514]: DOWNLOAD URL http://pr37.rapidgator.net//?r=download/index&session_id=xxx | cookies=True | get={} | disposition=True | post={} | ref=True
376	02.10.2015 10:38:20	DEBUG	Chunk 1 failed: (6, "Couldn't resolve host 'pr37.rapidgator.ne'")
377	02.10.2015 10:38:20	DEBUG	pycurl exception 6: Couldn't resolve host 'pr37.rapidgator.ne'
378	02.10.2015 10:38:20	ERROR	pycurl error 6: Couldn't resolve host 'pr37.rapidgator.ne'
379	02.10.2015 10:38:20	DEBUG	Error creating zip file: 'ascii' codec can't decode byte 0xca in position 10: ordinal not in range(128)
380	02.10.2015 10:38:20	INFO	Debug Report written to debug_RapidgatorNet_xxx.txt

**Comment by vuolter** [comment]
Understood. Working on...
