### ISSUE TITLE
Premiumize.me hoster plugin

### ISSUE THREAD

**Issue by realwax** [pyload/pyload#1934]
Hi,

I did a complete refresh from github 11:15 today.

I get:
39  02.10.2015 11:29:07 WARNING ACCOUNT PremiumizeMe: Error loading info for user `1234567` | 'NoneType' object is unsubscriptable
Beside that how will the hoster be updated for Multihoster like Premiumize me, as hook plugin is gone?

Thank you very much
Cheers
Wax

**Comment by Velociraptor85** [comment]
I would say this might be linked to https://github.com/pyload/pyload/issues/1938

**Comment by GammaC0de** [comment]
As far as I know PremiumizeMe works fine.
