### ISSUE TITLE
PremiumizeMe HOOK: No Hoster loaded.

### ISSUE THREAD

**Issue by MaxPower88** [pyload/pyload#1938]
The PremiumizeMe Hook can't load hosters anymore. Additionally I noticed that there is no PremiumizeMeHook.py file in the git repository here anymore, and no MultiHook.py either. On my server they are still there however.

The debug log doesn't show much:

16  02.10.2015 15:30:55 ERROR   HOOK PremiumizeMe: No hoster loaded
15  02.10.2015 15:30:55 DEBUG   HOOK PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php | cookies=True | get={'params[pass]': '*********_', 'params[login]': 'xxx', 'method': 'hosterlist'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
14  02.10.2015 15:30:55 DEBUG   ACCOUNT PremiumizeMe: Account info for user `xxx`: {'login': {'timestamp': 1443792642.953668, 'password': '**_******_', 'valid': True}, 'data': {'validuntil': 1445576744.0, 'trafficleft': 827660666, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
13  02.10.2015 15:30:55 DEBUG   ACCOUNT PremiumizeMe: {u'status': 200, u'result': {u'trafficleft_gigabytes': 789.31872058194, u'trafficleft_bytes': 847524522755, u'expires': 1445576744, u'fairuse_left': 0.78931872058194, u'extuid': u'xxx', u'type': u'premium', u'account_name': u'xxx'}, u'statusmessage': u'OK'}
12  02.10.2015 15:30:54 DEBUG   ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php | cookies=True | get={'params[pass]': 'xxx', 'params[login]': 'xxx', 'method': 'accountstatus'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
11  02.10.2015 15:30:54 INFO    ACCOUNT PremiumizeMe: Grabbing account info for user `xxx`...
10  02.10.2015 15:30:54 DEBUG   ACCOUNT PremiumizeMe: Account info for user `xxx`: {'login': {'timestamp': 1443792642.953668, 'password': '**_*******', 'valid': True}, 'data': {'validuntil': 1445576744.0, 'trafficleft': 827660666, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
9   02.10.2015 15:30:54 DEBUG   ACCOUNT PremiumizeMe: {u'status': 200, u'result': {u'trafficleft_gigabytes': 789.31872058194, u'trafficleft_bytes': 847524522755, u'expires': 1445576744, u'fairuse_left': 0.78931872058194, u'extuid': u'xxx', u'type': u'premium', u'account_name': u'xxx'}, u'statusmessage': u'OK'}
8   02.10.2015 15:30:54 DEBUG   ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php | cookies=True | get={'params[pass]': 'xxx', 'params[login]': 'xxx', 'method': 'accountstatus'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
7   02.10.2015 15:30:54 INFO    ACCOUNT PremiumizeMe: Grabbing account info for user `xxx`...
6   02.10.2015 15:30:54 INFO    HOOK PremiumizeMe: Reloading supported hoster list

**Comment by vuolter** [comment]
Working on... but might be need a while.

**Comment by MikeD23** [comment]
Same problem here with debriditalia. But take your time! ;-)

**Comment by snickers2k** [comment]
same here..

**Comment by psych0d0g** [comment]
any updates?

**Comment by cavebeat** [comment]
:( same here

**Comment by GammaC0de** [comment]
As far as I know PremiumizeMe works fine.
