### ISSUE TITLE
Onefichier 

### ISSUE THREAD

**Issue by lpui** [pyload/pyload#1939]
When I insert a 1fichier link the download starts and finish almost immediately, saving only a file named like the link, or start with connection reset and wait one minute eventually doing the same as above. (Not in this log, I aborted them before it could do it)

975	02.10.2015 16:31:38	INFO	UpdateManager: No Updates for pyLoad
976	02.10.2015 16:31:39	INFO	UpdateManager: New version of hook|UpdateManager : 0.56
977	02.10.2015 16:31:41	INFO	Starting builtin webserver: 0.0.0.0:12346
978	02.10.2015 16:33:02	INFO	Added package Ytddt containing 1 links
979	02.10.2015 16:33:02	INFO	Download starts: https://1fichier.com/?0vlk98plwu
980	02.10.2015 16:33:32	DEBUG	pycurl exception 28: SSL connection timeout at 28721
981	02.10.2015 16:33:32	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
982	02.10.2015 16:33:39	INFO	Download aborted: https://1fichier.com/?0vlk98plwu
983	02.10.2015 16:33:40	DEBUG	All downloads processed

**Comment by damien599901** [comment]
Same issue for me @vuolter 

535	04.10.2015 10:28:24	INFO	Utilisation du dossier principal : /volume1/.@plugins/AppCentral/pyload/config
536	04.10.2015 10:28:25	ERROR	XFileSharingProFolder a un format invalide.
537	04.10.2015 10:28:25	ERROR	XFileSharingPro a un format invalide.
538	04.10.2015 10:28:25	INFO	Plugins activés: AntiStandby, ClickAndLoad, ExternalScripts, ExtractArchive, LinkdecrypterComHook, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
539	04.10.2015 10:28:25	INFO	Plugins désactivés: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, MergeFiles, MultiHome, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPPInterface
540	04.10.2015 10:28:25	INFO	Temps de téléchargement : True
541	04.10.2015 10:28:25	INFO	Démarre ThriftBackend: 0.0.0.0:7228
542	04.10.2015 10:28:25	INFO	Espace libre : 2.80 TiB
543	04.10.2015 10:28:25	INFO	Activating Accounts...
544	04.10.2015 10:28:25	INFO	Starting threaded webserver: 0.0.0.0:9051
545	04.10.2015 10:28:25	INFO	ACCOUNT AlldebridCom: Adding user `damien599901`...
546	04.10.2015 10:28:25	INFO	ACCOUNT AlldebridCom: Login user `damien599901`...
547	04.10.2015 10:28:25	INFO	ACCOUNT AlldebridCom: Grabbing account info for user `damien599901`...
548	04.10.2015 10:28:26	INFO	Activating Plugins...
549	04.10.2015 10:28:26	WARNING	ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
550	04.10.2015 10:28:26	WARNING	ADDON AntiStandby: Unable to change display power state | [Errno 2] No such file or directory
551	04.10.2015 10:28:26	INFO	HOOK XFileSharingPro: Handling any hoster I can!
552	04.10.2015 10:28:26	ERROR	Error executing hooks: bad character range
553	04.10.2015 10:28:26	INFO	pyLoad is up and running
554	04.10.2015 10:28:27	INFO	ADDON UpdateManager: No new pyLoad version available
555	04.10.2015 10:28:27	INFO	ADDON UpdateManager: No plugin updates available
556	04.10.2015 10:28:30	INFO	Download starts: Maggie.2015.TRUEFRENCH.BDRiP.XViD-AViTECH.zone-telechargement.com.avi
557	04.10.2015 10:28:30	INFO	HOSTER OneFichierCom[3]: Updating file info...
558	04.10.2015 10:28:31	INFO	HOSTER OneFichierCom[3]: File name: ?4wlza7omwy
559	04.10.2015 10:28:31	INFO	HOSTER OneFichierCom[3]: File size: 734045143 bytes
560	04.10.2015 10:28:31	INFO	HOSTER OneFichierCom[3]: File status: démarrage
561	04.10.2015 10:28:31	INFO	HOSTER OneFichierCom[3]: Looking for direct download link...
562	04.10.2015 10:28:31	INFO	HOSTER OneFichierCom[3]: Direct download link not found
563	04.10.2015 10:28:32	INFO	HOSTER OneFichierCom[3]: Updating file info...
564	04.10.2015 10:28:32	INFO	HOSTER OneFichierCom[3]: File name: Maggie.2015.TRUEFRENCH.BDRiP.XViD-AViTECH.zone-telechargement.com.avi
565	04.10.2015 10:28:32	INFO	HOSTER OneFichierCom[3]: File size: 734045143 bytes
566	04.10.2015 10:28:32	INFO	HOSTER OneFichierCom[3]: Waiting 3600 seconds...
567	04.10.2015 10:28:32	INFO	HOSTER OneFichierCom[3]: Requiring reconnection...
568	04.10.2015 10:28:36	INFO	ADDON ClickAndLoad: Proxy listening on 127.0.0.1:9666
Jump to time:
04.10.2015 10:28:24
  ok

**Comment by vuolter** [comment]
Fixed.
