### ISSUE TITLE
Encoding issue prevents downloading

### ISSUE THREAD

**Issue by vuolter** [pyload/pyload#194]
11.07.2013 22:39:24 WARNING Download failed: Oggy_et_les_cafards_Intégrale.part001.rar | 'ascii' codec can't encode character u'\xe9' in position 58: ordinal not in range(128)

**Comment by daniel-cohen** [comment]
This issue has been a pain in the a** for me for ages! I finally fixed it thanks to your commits.
Just wanted to say thanks!
I just wish we'd be able there were update release to at least fix these sort of issues.

**Comment by stickell** [comment]
> I just wish we'd be able there were update release to at least fix these sort of issues

Yes the idea behind 0.4.10 was in fact that, to release a core fixed 0.4.9 but it is taking longer than I wished.

**Comment by daniel-cohen** [comment]
@stickell: Why not make more frequent, but smaller releases ?
You're doing a great job btw. It's just a suggestion.

**Comment by stickell** [comment]
That is exactly my same opinion! But other members of the team started making huge changes and until they will be ready the code is not stable enough

**Comment by vuolter** [comment]
Here! :p

**Comment by daniel-cohen** [comment]
@vuolter Here what ?

**Comment by vuolter** [comment]
Here I am, the bad big wolf who made the huge changes... :P

**Comment by stickell** [comment]
He really enjoy them! :smile:

**Comment by daniel-cohen** [comment]
Maybe I can help you squeeze one more "big" change ? :)
Another problem I've been having for ages and can't find anything in the logs, but tracker or forums or anywhere else is:
When pyload starts everything is fine and it does multiple downloads work fine. But after a while (I have it running on a NAS) it stops doing multiple downloads and only does one download.
I always suspected it does that after some plugin updates, but I can't prove it.
DEBUG mode is enabled BTW.

Any ideas about this issue or how to debug ??

The 2nd (or more) download just sits there ''queued". Screenshot:
http://snag.gy/aofMu.jpg

* Sorry for hijacking the thread. Will gladly open a new ticket once I have some more info.

**Comment by stickell** [comment]
I've never had this issue and I used pyLoad a lot and on multiple platforms. Are you sure multiple downloads are set?

**Comment by daniel-cohen** [comment]
yup. works fine after a restart.

**Comment by stickell** [comment]
Never experienced that. Does it happen always with Realdebrid?

**Comment by daniel-cohen** [comment]
This sounds similar to what I'm seeing:
http://forum.pyload.org/viewtopic.php?f=7&t=258

TBH, I only download through real-debrid. So I don't know. I'll have to get back to you when this happens again (just restarted my pyload).
Do you think this is the RD plugin ? 
If you point me to the class/file where the logic for "queuing"/"waiting" logic is , maybe I can add some more logging. There's nothing in the log right now.

**Comment by stickell** [comment]
> Do you think this is the RD plugin ?

Maybe. I don't think it's a core bug, it should have been reporting a long time ago in this case.

`self.multiDL` in RealDebrid should be `True` so I can't image where the issue could be

**Comment by vuolter** [comment]
@daniel-cohen Please open a new issue report. I think it's a core issue because the download dispatcher in 0.4.9 (and 0.4.10) is a mess. u_u

**Comment by daniel-cohen** [comment]
Thanks @vuolter. I've opened #1171
