### ISSUE TITLE
Upoloadedto Premium Traffic left

### ISSUE THREAD

**Issue by Prandur** [pyload/pyload#1940]
Hi. 
There is a problem with the Traffic left for uploaded. It shows the correct number but it's using the wrong value. It uses kib instead of gib.
As result downloads are started as free user because of the "missing" traffic.

03.10.2015 11:07:16	INFO	ACCOUNT UploadedTo: Grabbing account info for user `usr`...
611	03.10.2015 11:07:16	INFO	HOSTER UploadedTo[2107]: Filesize: 976562 KiB, Traffic left for user usr: 361.94 KiB
612	03.10.2015 11:07:16	INFO	HOSTER UploadedTo[2107]: Processing as free download...

My correct traffic left value is 361GB at the moment.

**Comment by Bambie42** [comment]
i can't confirm this issue. Have you tried readding your Account?

**Comment by Altranas** [comment]
I have the same issue - 540kb instead of 540gb. I'm not sure - maybe it's my fault but i have many problems with pyload for the last weeks.

**Comment by Prandur** [comment]
Yes i tried readding. Won't work.
I also deleted the account, restartet pyload and then readded the account with the same result.

**Comment by It0w** [comment]
same issue 535kb instead of 535gb
readding won´t work
``
INFO	HOSTER UploadedTo[241]: Filesize: 319049 KiB, Traffic left for user #####: 535.0 KiB
``

**Comment by nordic-style** [comment]
Should be fixed with the latest commits. does work fine for me.

**Comment by Altranas** [comment]
Which commits?

**Comment by Prandur** [comment]
For me it seems fine now. I haven't updated something manually.

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/1c7d9e55ffbfc9204c9e9246d9cc64806fa38326
