### ISSUE TITLE
ACCOUNT ShareonlineBiz: Error loading info for user | your IP is temporary banned! think about the invalid requests you've done earlier and come back later

### ISSUE THREAD

**Issue by FRYYYYYY** [pyload/pyload#1944]
Since the latest update, I am not able to download anything via pyload.
The error is:

HOSTER ShareonlineBiz[5]: Processing as premium download...
ACCOUNT ShareonlineBiz: Grabbing account info for user ``...
WARNING Download failed: dsgshdfjhd.rar | 'status'
ACCOUNT ShareonlineBiz: Error loading info for user | your IP is temporary banned! think about the invalid requests you've done earlier and come back later

When I use jDownloader for example, it is working. So the account is ok, my IP is not banned.

I changed my ip but I got the same messages.

**Comment by julianmair** [comment]
Same here:

[ ... ]
INFO      Download starts: blablabla.rar
INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `username`...
INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `username`...
INFO      HOSTER ShareonlineBiz[11]: Updating file info...
INFO      HOSTER ShareonlineBiz[11]: File name: blablabla.rar
INFO      HOSTER ShareonlineBiz[11]: File size: 629145603 bytes
INFO      HOSTER ShareonlineBiz[11]: File status: starte
INFO      HOSTER ShareonlineBiz[11]: Looking for direct download link...
INFO      HOSTER ShareonlineBiz[11]: Direct download link not found
INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `username`...
INFO      HOSTER ShareonlineBiz[11]: Filesize: 614400 KiB, Traffic left for user username: 104852160.0 KiB
INFO      HOSTER ShareonlineBiz[11]: Processing as premium download...
INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `username`...
INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `username`...
WARNING   Download failed: blablabla.rar | 'status'
INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `username`...
WARNING   ACCOUNT ShareonlineBiz: Error loading info for user `username` | your IP is temporary banned! think about the invalid requests you've done earlier and come back later
INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `username`...
WARNING   ACCOUNT ShareonlineBiz: Error loading info for user `username` | your IP is temporary banned! think about the invalid requests you've done earlier and come back later
[ ... ]

should I post the debug log? and why is pyload grabbing so often?

**Comment by jackdierippe** [comment]
Same error for me (with share-online too) - same log errors
I just stop testing to avoid banning.

**Comment by WebentwicklungUfer** [comment]
Same Problem here :(

**Comment by Exormeter** [comment]
Same here

**Comment by vuolter** [comment]
Changing login interval from 10 minutes to 30...

**Comment by julianmair** [comment]
Still the same error ... :(

**Comment by erse80** [comment]
@vuolter 

for me ban is due a loop of "Grab info":

4.10.2015 09:48:14 INFO      ACCOUNT EasybytezCom: Grabbing account info for user `xxxx`...
04.10.2015 09:48:14 INFO      ACCOUNT EasybytezCom: Grabbing account info for user `xxxx`...
04.10.2015 09:48:14 INFO      ACCOUNT EasybytezCom: Grabbing account info for user `xxxx`...
04.10.2015 09:48:14 INFO      ACCOUNT EasybytezCom: Grabbing account info for user `xxxx`...

**Comment by vuolter** [comment]
@erse80 Do you have more than one EasybytezCom account?

**Comment by erse80** [comment]
only 1

**Comment by jackdierippe** [comment]
I don't know if it's important  but i found this error at the beginn of pyload log :

INFO	Activating Accounts...
INFO	ACCOUNT ShareonlineBiz: Adding user `xxxxxxxxxxx`...
INFO	ACCOUNT ShareonlineBiz: Login user `xxxxxxxxxxx`...
INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `xxxxxxxxxxx`...
WARNING	ACCOUNT ShareonlineBiz: Error loading info for user `xxxxxxxxxxx` | dictionary update sequence element #15 has length 4; 2 is required
INFO	Activating Plugins...

and a little warning later (but i don't think has something to do with our problem) :

INFO	HOOK LinkdecrypterCom: Reloading supported crypter list
WARNING	HOOK LinkdecrypterCom: 'NoneType' object has no attribute 'group' | Waiting 1 minute and retry
INFO	HOOK LinkdecrypterCom: Reloading supported crypter list
WARNING	HOOK LinkdecrypterCom: 'NoneType' object has no attribute 'group' | Waiting 1 minute and retry

**Comment by markus76** [comment]
Anything new ?
Can i test anything?

**Comment by FRYYYYYY** [comment]
I tested it yesterday evening - still the same error.

**Comment by Garog** [comment]
looks like the "same" problem like #1953

**Comment by vuolter** [comment]
Fixed.

**Comment by Velociraptor85** [comment]
@GammaC0de I would think this is solved?
