### ISSUE TITLE
'exceptions.OSError' object has no attribute 'strip'

### ISSUE THREAD

**Issue by dandftrash** [pyload/pyload#1946]
Hello,

Here is my log from pyload 0.4.9 on Xpenology 5.2.

Idea?

Démarrage pyLoad 0.4.9
872	03.10.2015 21:34:26	INFO	Utilisation du dossier principal : /volume1/@appstore/pyload/var/config
873	03.10.2015 21:34:26	DEBUG	Remote activated: True
874	03.10.2015 21:34:26	DEBUG	created index of plugins
875	03.10.2015 21:34:26	DEBUG	ADDON ExternalScripts: Deprecated method `event_list`, use `event_map` instead
876	03.10.2015 21:34:26	INFO	Plugins activés: AntiStandby, BypassCaptcha, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterComHook, UnSkipOnFail, UserAgentSwitcher, XFileSharingPro
877	03.10.2015 21:34:26	INFO	Plugins désactivés: AndroidPhoneNotify, AntiVirus, Captcha9Kw, CaptchaBrotherhood, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, JustPremium, MergeFiles, MultiHome, RestartFailed, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XMPPInterface
878	03.10.2015 21:34:26	INFO	Temps de téléchargement : True
879	03.10.2015 21:34:26	INFO	Démarre ThriftBackend: 0.0.0.0:7227
880	03.10.2015 21:34:26	INFO	Starting lightweight webserver (bjoern): 0.0.0.0:8000
881	03.10.2015 21:34:26	INFO	Free space: 2.67 TiB
882	03.10.2015 21:34:26	INFO	Activating Accounts...
883	03.10.2015 21:34:26	INFO	Activating Plugins...
884	03.10.2015 21:34:27	WARNING	ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
885	03.10.2015 21:34:27	WARNING	ADDON AntiStandby: Unable to change display power state | [Errno 2] No such file or directory
886	03.10.2015 21:34:27	INFO	HOOK XFileSharingPro: Handling any hoster I can!
887	03.10.2015 21:34:27	DEBUG	HOOK XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?:\w+\.)*?(?P(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
888	03.10.2015 21:34:27	INFO	HOOK XFileSharingPro: Handling any crypter I can!
889	03.10.2015 21:34:27	DEBUG	HOOK XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?:\w+\.)*?(?P(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:user|folder)s?/\w+
890	03.10.2015 21:34:27	DEBUG	ADDON ExtractArchive: Found UnRar 4.00 | Found SevenZip 9.20 | Found UnZip 2.7.3
891	03.10.2015 21:34:27	INFO	pyLoad is up and running
892	03.10.2015 21:34:37	INFO	ADDON ClickAndLoad: Proxy listening on 127.0.0.1:9666
893	03.10.2015 21:35:53	INFO	Download starts: Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar
894	03.10.2015 21:35:53	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
895	03.10.2015 21:35:53	DEBUG	HOSTER OneFichierCom[14]: PROCESS URL https://1fichier.com/?zfb0wok7bo | PLUGIN VERSION 0.90
896	03.10.2015 21:35:53	INFO	HOSTER OneFichierCom[14]: Updating file info...
897	03.10.2015 21:35:54	DEBUG	HOSTER OneFichierCom[14]: File info: {'status': 3, 'url': u'https://1fichier.com/?zfb0wok7bo', 'size': 0, 'name': '?zfb0wok7bo', 'pattern': {'HOST': u'1fichier.com', 'ID2': u'zfb0wok7bo', 'ID1': None}}
898	03.10.2015 21:35:54	DEBUG	HOSTER OneFichierCom[14]: Previous file info: {}
899	03.10.2015 21:35:54	INFO	HOSTER OneFichierCom[14]: File name: ?zfb0wok7bo
900	03.10.2015 21:35:54	INFO	HOSTER OneFichierCom[14]: File size: 1048576000 bytes
901	03.10.2015 21:35:54	INFO	HOSTER OneFichierCom[14]: File status: démarrage
902	03.10.2015 21:35:54	INFO	HOSTER OneFichierCom[14]: Looking for direct download link...
903	03.10.2015 21:35:54	DEBUG	HOSTER OneFichierCom[14]: LOAD URL https://1fichier.com/?zfb0wok7bo | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
904	03.10.2015 21:35:55	INFO	HOSTER OneFichierCom[14]: Direct download link not found
905	03.10.2015 21:35:55	DEBUG	HOSTER OneFichierCom[14]: LOAD URL https://1fichier.com/?zfb0wok7bo | cookies=[('1fichier.com', 'LG', 'en')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
906	03.10.2015 21:35:55	INFO	HOSTER OneFichierCom[14]: Updating file info...
907	03.10.2015 21:35:55	DEBUG	HOSTER OneFichierCom[14]: File info: {'status': 2, 'name': u'Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar', 'url': u'https://1fichier.com/?zfb0wok7bo', 'pattern': {'HOST': u'1fichier.com', 'U': u'MB', 'ID1': None, 'ID2': u'zfb0wok7bo', 'S': u'1000', 'N': u'Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar'}, 'folder': '?zfb0wok7bo', 'size': 1048576000.0}
908	03.10.2015 21:35:55	DEBUG	HOSTER OneFichierCom[14]: Previous file info: {'status': 3, 'name': '?zfb0wok7bo', 'url': u'https://1fichier.com/?zfb0wok7bo', 'pattern': {'HOST': u'1fichier.com', 'ID2': u'zfb0wok7bo', 'ID1': None}, 'folder': '?zfb0wok7bo', 'size': 0}
909	03.10.2015 21:35:55	INFO	HOSTER OneFichierCom[14]: File name: Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar
910	03.10.2015 21:35:55	INFO	HOSTER OneFichierCom[14]: File size: 1048576000 bytes
911	03.10.2015 21:35:55	INFO	HOSTER OneFichierCom[14]: Updating file info...
912	03.10.2015 21:35:56	DEBUG	HOSTER OneFichierCom[14]: File info: {'status': 2, 'name': u'Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar', 'url': u'https://1fichier.com/?zfb0wok7bo', 'pattern': {'HOST': u'1fichier.com', 'U': u'MB', 'ID1': None, 'ID2': u'zfb0wok7bo', 'S': u'1000', 'N': u'Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar'}, 'folder': u'Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar', 'size': 1048576000.0}
913	03.10.2015 21:35:56	DEBUG	HOSTER OneFichierCom[14]: Previous file info: {'status': 2, 'name': u'Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar', 'url': u'https://1fichier.com/?zfb0wok7bo', 'pattern': {'HOST': u'1fichier.com', 'U': u'MB', 'ID1': None, 'ID2': u'zfb0wok7bo', 'S': u'1000', 'N': u'Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar'}, 'folder': u'Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar', 'size': 1048576000.0}
914	03.10.2015 21:35:56	INFO	HOSTER OneFichierCom[14]: File name: Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar
915	03.10.2015 21:35:56	INFO	HOSTER OneFichierCom[14]: File size: 1048576000 bytes
916	03.10.2015 21:35:56	INFO	HOSTER OneFichierCom[14]: File status: démarrage
917	03.10.2015 21:35:56	INFO	HOSTER OneFichierCom[14]: Processing as free download...
918	03.10.2015 21:35:56	DEBUG	HOSTER OneFichierCom[14]: DOWNLOAD URL https://1fichier.com/?zfb0wok7bo | cookies=True | get={} | disposition=True | post={u'dl_no_ssl': '', 'submit': 'Download', u'dlinline': ''} | ref=True
919	03.10.2015 21:35:56	WARNING	Download failed: Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar | 'exceptions.OSError' object has no attribute 'strip'
920	03.10.2015 21:35:56	INFO	Debug Report written to debug_OneFichierCom_03-10-2015_21-35-56.zip
921	03.10.2015 21:35:56	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Terminator.Genisys.2015.MULTi.1080p.BluRay.TRUEHD.x264-Poney.zone-telechargement.com.part01.rar (pid:3)
922	03.10.2015 21:35:56	INFO	ADDON UnSkipOnFail: No duplicates found
923	03.10.2015 21:35:56	DEBUG	All downloads processed

**Comment by vuolter** [comment]
@dandftrash Retry now.

**Comment by Stetanchi** [comment]
Still not working for me...
+++
18.10.2015 22:09:03 INFO      HOSTER UploadedTo[6]: Grabbing link info...
18.10.2015 22:09:03 WARNING   xxx.hd2-tvs.part3.rar | 'NoneType' object has no attribute 'strip'
18.10.2015 22:09:03 ERROR     Error executing hooks: global name 'script' is not defined
+++

**Comment by vuolter** [comment]
@Stetanchi Fixed `18.10.2015 22:09:03 ERROR Error executing hooks: global name 'script' is not defined`

**Comment by R3alflash** [comment]
i get still this issue:

390	19.10.2015 07:25:21	WARNING	Download failed: http://www.share-online.biz/dl/xxxxxxxx | 'NoneType' object has no attribute 'strip'
391	19.10.2015 07:25:21	DEBUG	Error creating zip file: 'ascii' codec can't decode byte 0xc9 in position 14: ordinal not in range(128) 

Log is there: http://pastebin.com/dJdqfFpX

**Comment by vuolter** [comment]
@R3alflash Please, retry now.

**Comment by R3alflash** [comment]
great it works :+1:

**Comment by Dwarfex** [comment]
Hi, i still have this error on downloads ...either "normal" plain URL DLs as also with Uploaded

07.11.2015 11:09:33	INFO	starte pyLoad 0.4.9
38	07.11.2015 11:09:33	INFO	Benutze Home-Verzeichnis: /home/pyload/.pyload
39	07.11.2015 11:09:33	DEBUG	Deleting old pidfile pyload.pid
40	07.11.2015 11:09:33	DEBUG	Remote activated: True
41	07.11.2015 11:18:42	INFO	starte pyLoad 0.4.9
42	07.11.2015 11:18:42	INFO	Benutze Home-Verzeichnis: /home/pyload/.pyload
43	07.11.2015 11:18:42	DEBUG	Deleting old pidfile pyload.pid
44	07.11.2015 11:18:42	DEBUG	Remote activated: False
45	07.11.2015 11:18:43	DEBUG	created index of plugins
46	07.11.2015 11:18:43	INFO	Aktivierte Plugins: AntiStandby, ClickNLoad, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
47	07.11.2015 11:18:43	INFO	Deaktivierte Plugins: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPPInterface
48	07.11.2015 11:18:43	INFO	Downloadzeit: True
49	07.11.2015 11:18:43	INFO	Freier Speicher: 3.43 TiBGB
50	07.11.2015 11:18:43	INFO	Aktiviere Accounts...
51	07.11.2015 11:18:43	INFO	Aktiviere Plugins...
52	07.11.2015 11:18:44	INFO	Starting builtin webserver: 0.0.0.0:8100
53	07.11.2015 11:18:44	DEBUG	ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
54	07.11.2015 11:18:44	WARNING	ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
55	07.11.2015 11:18:44	DEBUG	ADDON ExtractArchive: Found UnRar 5.21 | Found SevenZip 9.20 | Found UnZip 2.7.9
56	07.11.2015 11:18:45	INFO	ADDON XFileSharing: Handle any hoster site on the web!
57	07.11.2015 11:18:45	DEBUG	ADDON XFileSharing: Loaded hoster pattern: (?:https?://(?:www\.)?)(?!180upload\.com|cramit\.in|easybytez\.com|exashare\.com|fileom\.com|filerio\.com|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uplea\.com|uptobox\.com|vidplay\.net)(?:\w+\.)*?(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
58	07.11.2015 11:18:45	INFO	ADDON XFileSharing: Handle any crypter site on the web!
59	07.11.2015 11:18:45	DEBUG	ADDON XFileSharing: Loaded crypter pattern: (?:https?://(?:www\.)?)(?!easybytez\.com|tusfiles\.net)(?:\w+\.)*?(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:user|folder)s?/\w+
60	07.11.2015 11:18:45	INFO	pyLoad is up and running
61	07.11.2015 11:18:45	INFO	ADDON UpdateManager: pyLoad is up to date!
62	07.11.2015 11:18:45	DEBUG	ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
63	07.11.2015 11:18:45	DEBUG	ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BillionuploadsCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'Movie2kTo'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'MultiHook'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster')]
64	07.11.2015 11:18:45	INFO	ADDON UpdateManager: All plugins are up to date!
65	07.11.2015 11:18:51	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
66	07.11.2015 11:19:31	INFO	Download starts: FreePBX-64bit-10.13.66.iso
67	07.11.2015 11:19:31	DEBUG	HOSTER BasePlugin[620]: Plugin version: 0.50
68	07.11.2015 11:19:31	DEBUG	HOSTER BasePlugin[620]: Plugin status: testing
69	07.11.2015 11:19:31	WARNING	HOSTER BasePlugin[620]: Plugin may be unstable
70	07.11.2015 11:19:31	DEBUG	HOSTER BasePlugin[620]: Config option `use_premium` not found, use default `True`
71	07.11.2015 11:19:31	INFO	HOSTER BasePlugin[620]: Grabbing link info...
72	07.11.2015 11:19:31	DEBUG	HOSTER BasePlugin[620]: Link info: {'status': 3, 'pattern': {}, 'size': 0, 'url': u'http://downloads.freepbxdistro.org/ISO/FreePBX-64bit-10.13.66.iso', 'name': 'FreePBX-64bit-10.13.66.iso'}
73	07.11.2015 11:19:31	DEBUG	HOSTER BasePlugin[620]: Previous link info: {}
74	07.11.2015 11:19:31	INFO	HOSTER BasePlugin[620]: Link name: FreePBX-64bit-10.13.66.iso
75	07.11.2015 11:19:31	INFO	HOSTER BasePlugin[620]: Link size: N/D
76	07.11.2015 11:19:31	INFO	HOSTER BasePlugin[620]: Link status: eingereiht
77	07.11.2015 11:19:31	DEBUG	HOSTER BasePlugin[620]: Redirect #0 to: http://downloads.freepbxdistro.org/ISO/FreePBX-64bit-10.13.66.iso
78	07.11.2015 11:19:31	DEBUG	HOSTER BasePlugin[620]: LOAD URL http://downloads.freepbxdistro.org/ISO/FreePBX-64bit-10.13.66.iso | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
79	07.11.2015 11:19:32	DEBUG	HOSTER BasePlugin[620]: DOWNLOAD URL http://downloads.freepbxdistro.org/ISO/FreePBX-64bit-10.13.66.iso | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
80	07.11.2015 11:19:32	WARNING	Download failed: FreePBX-64bit-10.13.66.iso | 'exceptions.OSError' object has no attribute 'strip'
81	07.11.2015 11:19:32	INFO	Debug Report written to debug_BasePlugin_07-11-2015_11-19-32.zip
82	07.11.2015 11:19:32	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: FreePBX-64bit-10.13.66.iso (pid:3)
83	07.11.2015 11:19:32	INFO	ADDON UnSkipOnFail: No duplicates found
84	07.11.2015 11:19:32	DEBUG	All downloads processed

**Comment by ochristi** [comment]
@Dwarfex I think this error happens if pyload is unable to write into the dl folder. Please check for correct permissions.
