### ISSUE TITLE
Hooks not working anymore

### ISSUE THREAD

**Issue by Lalarian** [pyload/pyload#1947]
Hello!

I have big trouble with getting pyload to work again for some time now. I tried fixing my oldinstallation, I tried fresh installation of different versions, like older versions, the entware pyload version, or the current git version, and all got lots and lots of bugs and throw dozens of errors. Its's so much that I can't even remember all, but there's one overall similarity: Near all bugs seem to be relatedto hooks.

The current state of my pyload installation is like:

70	04.10.2015 10:31:54	ERROR	HOOK LinkdecrypterCom: Error executing periodical task: 'LinkdecrypterComHook' object has no attribute 'core'
71	04.10.2015 10:31:54	ERROR	HOOK PremiumizeMe: Error executing periodical task: 'PremiumizeMeHook' object has no attribute 'core'
72	04.10.2015 10:31:54	ERROR	HOOK LinkdecrypterCom: Error executing periodical task: 'LinkdecrypterComHook' object has no attribute 'core'
73	04.10.2015 10:31:54	ERROR	HOOK PremiumizeMe: Error executing periodical task: 'PremiumizeMeHook' object has no attribute 'core'
74	04.10.2015 10:32:54	ERROR	HOOK LinkdecrypterCom: Error executing periodical task: 'LinkdecrypterComHook' object has no attribute 'core'
75	04.10.2015 10:32:54	ERROR	HOOK PremiumizeMe: Error executing periodical task: 'PremiumizeMeHook' object has no attribute 'core'
76	04.10.2015 10:32:54	ERROR	HOOK LinkdecrypterCom: Error executing periodical task: 'LinkdecrypterComHook' object has no attribute 'core'
77	04.10.2015 10:32:54	ERROR	HOOK PremiumizeMe: Error executing periodical task: 'PremiumizeMeHook' object has no attribute 'core'
78	04.10.2015 10:33:54	ERROR	HOOK LinkdecrypterCom: Error executing periodical task: 'LinkdecrypterComHook' object has no attribute 'core'
79	04.10.2015 10:33:54	ERROR	HOOK PremiumizeMe: Error executing periodical task: 'PremiumizeMeHook' object has no attribute 'core'
80	04.10.2015 10:33:54	ERROR	HOOK LinkdecrypterCom: Error executing periodical task: 'LinkdecrypterComHook' object has no attribute 'core'
81	04.10.2015 10:33:54	ERROR	HOOK PremiumizeMe: Error executing periodical task: 'PremiumizeMeHook' object has no attribute 'core'
82	04.10.2015 10:34:55	ERROR	HOOK LinkdecrypterCom: Error executing periodical task: 'LinkdecrypterComHook' object has no attribute 'core'
83	04.10.2015 10:34:55	ERROR	HOOK PremiumizeMe: Error executing periodical task: 'PremiumizeMeHook' object has no attribute 'core'
84	04.10.2015 10:34:55	ERROR	HOOK LinkdecrypterCom: Error executing periodical task: 'LinkdecrypterComHook' object has no attribute 'core'
85	04.10.2015 10:34:55	ERROR	HOOK PremiumizeMe: Error executing periodical task: 'PremiumizeMeHook' object has no attribute 'core' 

These messages repeat over and over.
I hope you can find a way for making this work again.

Thank you very much.

**Comment by vuolter** [comment]
Try: http://forum.pyload.org/viewtopic.php?f=7&t=4335
