### ISSUE TITLE
Captcha9Kw Plugin not working

### ISSUE THREAD

**Issue by Lalarian** [pyload/pyload#1948]
Hello!

In addition to those hook problems I mentioned, I also got trouble with the Cpatcha9kw.py AddOn.
It simply doesn't seem to do anything.
The only message regarding Captcha9kw in the log is:

04.10.2015 10:05:43 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BillionuploadsCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'ShareRapidCom'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'Movie2kTo'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'EasybytezCom'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FreeWayMe'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultishareCz'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'OverLoadMe'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PutdriveCom'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RapideoPl'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RehostTo'), (u'hooks', u'ReloadCc'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SmoozedCom'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'ZeveraCom'), (u'hoster', u'File4safeCom'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'Vipleech4uCom'), (u'internal', u'AbstractExtractor'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster')]

This message comes up on every start of pyload, I got no clue why pyload wants to delete these plugins and why it doesn't delete them instead of telling me they had been requested for deletion.

I hope there's a solution.
Regards,

**Comment by vuolter** [comment]
Debug log please.

**Comment by joberreiter** [comment]
I also see this message at every startup, but it doesn't throw an error nor seems to bug pyLoad.
I think this deletion request is unrelated to your Captcha9Kw Plugin-Issue.

By the way, I think that the core problem is not the non-functional Captcha9Kw-Plugin, I think there is another error before that. But to check this we need a full log, not only a single line of it. If an error was thrown, pyLoad has _also_ created a detailed debug log zip file.

**Comment by kasperj** [comment]
This issue is related to the issue I posted here, CaptchaSolvers didn't work when client is connected.

https://github.com/pyload/pyload/issues/1897
