### ISSUE TITLE
Can't add any dl to the queue

### ISSUE THREAD

**Issue by f6fvy** [pyload/pyload#1950]
After getting several "issue not reproduced" following bug reports, I decided to reinitiate the plugins directory.

I followed this thread http://forum.pyload.org/viewtopic.php?f=12&t=4335 but unfortunately, the plugin directory didn't updated :-( So, I downloaded and copy the /module/plugins of the stable branch to my /userplugins directory

I now get this startup log

04.10.2015 11:14:03	INFO	Starting pyLoad 0.4.9
04.10.2015 11:14:03	INFO	Using home directory: /home/pi/.pyload
04.10.2015 11:14:03	DEBUG	Deleting old pidfile pyload.pid
04.10.2015 11:14:03	DEBUG	Remote activated: True
04.10.2015 11:14:06	ERROR	XFileSharingProFolder has a invalid pattern.
04.10.2015 11:14:24	ERROR	XFileSharingPro has a invalid pattern.
04.10.2015 11:14:27	DEBUG	created index of plugins
04.10.2015 11:14:27	DEBUG	Redirected import module.plugins.hooks.LinkdecrypterComHook -> userplugins.hooks.LinkdecrypterComHook
04.10.2015 11:14:27	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
04.10.2015 11:14:27	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.hooks.DeathByCaptcha -> userplugins.hooks.DeathByCaptcha
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.internal.Hook -> userplugins.internal.Hook
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
04.10.2015 11:14:28	DEBUG	ADDON ExternalScripts: Deprecated method `event_list`, use `event_map` instead
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.hooks.AntiStandby -> userplugins.hooks.AntiStandby
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.hooks.Captcha9Kw -> userplugins.hooks.Captcha9Kw
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.hooks.CaptchaBrotherhood -> userplugins.hooks.CaptchaBrotherhood
04.10.2015 11:14:28	DEBUG	Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
04.10.2015 11:14:28	INFO	Activated plugins: AntiStandby, Captcha9Kw, CaptchaBrotherhood, ClickAndLoad, DeathByCaptcha, ExternalScripts, ExtractArchive, LinkdecrypterComHook, UnSkipOnFail, UpdateManager, XFileSharingPro
04.10.2015 11:14:28	INFO	Deactivate plugins: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Checksum, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, MergeFiles, MultiHome, RestartFailed, SkipRev, TransmissionRPC, UserAgentSwitcher, WindowsPhoneNotify, XMPPInterface
04.10.2015 11:14:28	INFO	Downloadtime: True
04.10.2015 11:14:28	INFO	Starting ThriftBackend: 0.0.0.0:7227
04.10.2015 11:14:33	INFO	Free space: 66.74 GiB
04.10.2015 11:14:33	INFO	Starting threaded webserver: 0.0.0.0:8000
04.10.2015 11:14:34	INFO	Activating Accounts...
04.10.2015 11:14:34	INFO	Activating Plugins...
04.10.2015 11:14:34	WARNING	ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
04.10.2015 11:14:34	WARNING	ADDON AntiStandby: Unable to change display power state | [Errno 2] No such file or directory
04.10.2015 11:14:34	INFO	HOOK XFileSharingPro: Handling any hoster I can!
04.10.2015 11:14:34	ERROR	Error executing hooks: bad character range
04.10.2015 11:14:34	INFO	pyLoad is up and running
04.10.2015 11:14:44	INFO	ADDON ClickAndLoad: Proxy listening on 0.0.0.0:9666 

But, unfortunately, I can't add any DL anymore to the queue. They just don't appear in the queue list, whether they're added locally or with FlashGot. I tried several pyload restarts or RasPi restart with no joy :-(

Any help please ?

**Comment by GammaC0de** [comment]
"proper" installation of `pyLoad`:
* get `pyLoad` for your OS from https://github.com/pyload/pyload/releases
* replace the `module/plugins/UpdateManager.py` file  with this one: https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py
* Start `pyLoad`
* Wait for update to finish
* Wacth the log - you may have to manually restart `pyLoad` for `UpdateManager` finish its job

**Comment by damien599901** [comment]
same issue of one my device
the queue is empty !

**Comment by GammaC0de** [comment]
are you using `ClickAndLoad`?

**Comment by damien599901** [comment]
@GammaC0de  : yes.

**Comment by GammaC0de** [comment]
check you 'collector' tab, 
there is a new settings on `ClickAndLoad` plugin to choose between 'collector' and 'queue'

**Comment by damien599901** [comment]
sorry same issue

2015-10-04 15:27 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by bilderbuchi** [comment]
@GammaC0de there's a slight error in your "proper installation routine", the path should be `module/plugins/hooks/UpdateManager.py`. Also, it would be great to put this info somewhere much more visible, e.g. the github readme, I just spent ages getting a working pyload instance set up for troubleshooting. :-/

**Comment by Bambie42** [comment]
I got the same issue. When adding links within the webinterface, they disappear. No hints in the logs of adding something...

**Comment by damien599901** [comment]
same issue 
each download = 0 ko. 
very strange :(

**Comment by drt1** [comment]
same problem here, I deleted all pyload data and did a fresh install, in setup assistant it says: "JS engine: missing" though spidermonkey-24.2.0-r3 is installed (and was since years in previous versions).
I installed rhino and started setup again - no change.
So if pyload could not recognize the Javascript engine, maybe this is the reason why Click'n'Load isn't working.

But even if it would work...
I cannot perform ANY download, nevermind if added per DLC or URL,
possibly due to issue https://github.com/pyload/pyload/issues/1954

**Comment by damien599901** [comment]
i have now one file of 0ko in the queue and if i take a look in the folder i have a little file of 469ko 
More and more strange.
What's happened with pyload :( ? pyload is dead? it will not be maintained?

**Comment by drt1** [comment]
I also get files with 1kb size and then all downloads enter wait-loop and never leave.
yes it seems like pyload is dead, and there is no equivalent alternative...

**Comment by GammaC0de** [comment]
pyload is not dead, vuolter is working hard on building v0.4.10 and fixing bugs.
this takes much of his spare time and thats why he is not often here

**Comment by Bambie42** [comment]
i solved the problem for me, i used authbind to bind the webinterface to port 80, which broke things for me.

**Comment by joberreiter** [comment]
@f6fvy 
The error of the initial post (`Error executing hooks: bad character range`) has been resolved. If the download is still not possible please check the (new) error message and see if there is already another issue for that.
This issue can be closed.

**Comment by f6fvy** [comment]
Thank you but I give up pyload currently. Too much hassle. Since several weeks now, new bugs are popping everyday, and I spend more time trying to fix, report or update (when it works) than downloading. I will patiently wait for a *true* stable version.

**Comment by drt1** [comment]
+1

**Comment by damien599901** [comment]
+1

same thing for me
i will ask to my boss the temporarily erase of our store of apps.
Or we will have 100000 tickets of asks of support.
it's a pity
All worked during years and since july we have a lot of issues, everyday a
new one.

2015-10-10 20:10 GMT+02:00 drt1 <notifications@github.com>:
