### ISSUE TITLE
ShareOnline: Download failed: [FILENAME] | 'status'

### ISSUE THREAD

**Issue by b0wtie** [pyload/pyload#1953]
Hi guys,

I have trouble downloading from share-online.biz. Like said in the description, every download fails with this message.

I already have put my good old pyload installation aside and started a new one from scratch via "git clone". The new config was just created by "pyLoadCore.py -s"

Here is the last part of my debug logfile. 

04.10.2015 21:35:01 DEBUG     ACCOUNT ShareonlineBiz: Account info for user `[I-DELETED-THIS]`: {'login': {'timestamp': 1443987301.1398971, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1552824341.0, 'trafficleft': 104854720.0, 'maxtraffic': 104857600L, 'premium': True, 'options': {'limitdl': ['0']}}}
04.10.2015 21:35:01 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL https://api.share-online.biz/account.php | decode=True | cookies=True | get={'username': '[I-DELETED-THIS]', 'lid': 'AE801FGN9K', 'password': '**********', 'act': 'download'} | req=None | multipart=False | post={} | ref=True | just_header=False
04.10.2015 21:35:02 DEBUG     HOSTER ShareonlineBiz[1]: ** USER DATA INVALID **
04.10.2015 21:35:02 WARNING   Download failed: Araeddo198GermaACDL70BlRayx64OiEADCS.part01.rar | 'status'
Traceback (most recent call last):
  File "/volume1/@optware/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/volume1/@optware/pyload/module/plugins/internal/Base.py", line 201, in preprocessing
    return self._process(*args, **kwargs)
  File "/volume1/@optware/pyload/module/plugins/internal/Hoster.py", line 80, in _process
    self.process(self.pyfile)
  File "/volume1/@optware/pyload/module/plugins/internal/SimpleHoster.py", line 289, in process
    self.handle_premium(pyfile)
  File "/volume1/@optware/pyload/module/plugins/hoster/ShareonlineBiz.py", line 135, in handle_premium
    if dlinfo['status'] != "online":
KeyError: 'status'
04.10.2015 21:35:02 DEBUG     Error creating zip file: 'ascii' codec can't decode byte 0x9c in position 11: ordinal not in range(128)
04.10.2015 21:35:02 INFO      Debug Report written to debug_ShareonlineBiz_04-10-2015_21-35-02.txt
04.10.2015 21:35:02 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: Araeddo198GermaACDL70BlRayx64OiEADCS.part01.rar (pid:1)
04.10.2015 21:35:02 INFO      ADDON UnSkipOnFail: No duplicates found
04.10.2015 21:35:02 DEBUG     All downloads processed

I notice that it gets back: USER DATA INVALID - but my password and account data are 100% correct...

Any ideas? Thank you!

**Comment by wastez** [comment]
I´ve the same error.
It would be great if pyload would work again in near future.

**Comment by stefanheimann** [comment]
same here ;(

**Comment by kotarokun** [comment]
Here it is also reported. https://github.com/pyload/pyload/issues/1931

**Comment by crazy06** [comment]
same here

**Comment by maelue** [comment]
Still problems with that :-(

14	05.10.2015 08:50:18	INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `XXXXXX`...
915	05.10.2015 08:50:18	INFO	HOSTER ShareonlineBiz[2]: Filesize: 1022976 KiB | Traffic left for user XXXXXX: 104857600.0 KiB
916	05.10.2015 08:50:18	INFO	HOSTER ShareonlineBiz[2]: Processing as premium download...
917	05.10.2015 08:50:18	INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `XXXXXX`...
918	05.10.2015 08:50:19	WARNING	Download failed: DDWWDDpart1.rar | 'status'
919	05.10.2015 08:50:19	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of:DDWWDD.part1.rar (pid:2)
920	05.10.2015 08:50:19	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by b0wtie** [comment]
Sorry for the duplicataion of #1931. Had even seen the thread but gotten lost in THAT log file xD

Does share-online change their api that often, I wonder?

**Comment by crosien2015** [comment]
same problem here......

**Comment by joberreiter** [comment]
> Does share-online change their api that often, I wonder?

No, seems to be a general account problem in pyLoad affecting other accounts as well (UploadedTo, AllDebridCom, etc.).

**Comment by Garog** [comment]
after a fresh reinstallation of pyload, i get this error too

**Comment by Moerdoc** [comment]
same problem :(

**Comment by speedfrenzy** [comment]
i spent 5 hours to get rid of this error, but no chance at all. would be so nice, if anyone could help!

**Comment by b0wtie** [comment]
I restored an old pyload backup I had on my second NAS (about 3 months old). No problem with that version. I can download just fine. Should I provide any file of the working version?

**Comment by FuX-STV** [comment]
same problem...

can u upload this version b0wtie?

**Comment by speedfrenzy** [comment]
that would be great, b0wtie !!

**Comment by b0wtie** [comment]
I hope that is allowed (if not, u may delete this comment)

This is my version. Disconnect it from the internet and deactivate the module "UpdateManager".

https://www.oboom.com/VAZG8AT4/pyload-without-sa-bug.tgz

**Comment by maelue** [comment]
Is someone successful with the old version of pyload by b0wtie ??? I have still Problems with dlc and downloads from share-online... :-(

**Comment by b0wtie** [comment]
Hmm... Did you start it without internet and deactivated the UpdateManager?

I did not pack my .pyload folder. Might that be the cause?

**Comment by XneddyX** [comment]
same problem...

**Comment by maelue** [comment]
I use pyload on a Qnap NAS. Maybe that's the cause!?! In the ipk file, some folders and files do not exist when i compare it with the b0wtie directories...

**Comment by ruabmbua** [comment]
After reinstalling I got the same problem too.

**Comment by wastez** [comment]
Will somebody fix this? It´s weeks ago that pyload is working as it should?
What about a test channel in Update Manager to prevent that pyload isn´t working in stable release.

**Comment by maelue** [comment]
I agree with that. Maybe a rollback to the last stable release including all working plugins could be helpful.

**Comment by Garog** [comment]
I abandoned pyload. jDownloader 2.0 in headless mode with myjdownloader. MUCH better ui and usability and.. its running ;)

**Comment by sveni-lee** [comment]
sorry, but that didn't help... we need a bugfix and not an other downloader....

**Comment by Garog** [comment]
Sometimes there is the time to switch. When your car is broken and the garage doesn't fix it and you don't know if there can/will fix it, think about a new car and don't try to repair your old one for the x. th time...

**Comment by sveni-lee** [comment]
yes, but you don't need to tell it the garage cause that didn't change abything...
but this is Offtopic... So please do what you think you need to do but please not here...

**Comment by bioxz** [comment]
I'm also affected by this bug. A stable plugin branch for the stable release branch would be cool.

**Comment by vuolter** [comment]
Guys, I'm currently working to restore the MultiAccount plugin. When done, all will come back to "normal".

**Comment by TheTrueHansen** [comment]
It seems that  self.account.get_login('password') does not return the password.
file: module/plugins/hoster/ShareonlineBiz.py
line: 122

For testing I replaced 'self.account.get_login('password')' with my password and it worked again.

**Comment by Moerdoc** [comment]
Hey TheTrueHansen,

thx for sharing this information... Working for me... TOP

**Comment by m-lindemann** [comment]
Can confim that! Thanks!!!

Line 121, for me in:
pyload/userplugins/hoster/ShareonlineBiz.py

Looks like this now and ist working for me:

        html = self.load("https://api.share-online.biz/account.php",
                         get={'username': self.account.user,
                              'password': "Pass1234",
                              'act'     : "download",
                              'lid'     : self.info['fileid']})

**Comment by sveni-lee** [comment]
indeed that works....

**Comment by maelue** [comment]
UNBELIEVABLE ! That works like a charm ! THAK YOU ! ! ! :+1:

**Comment by maelue** [comment]
Correction... its nearly perfect...

32	13.10.2015 13:02:10	INFO	HOSTER ShareonlineBiz[102]: Filesize: 107520 KiB | Traffic left for user `XXXXXX`: 94084945 KiB
733	13.10.2015 13:02:10	INFO	HOSTER ShareonlineBiz[102]: Processing as premium download...
734	13.10.2015 13:02:10	**WARNING	HOSTER ShareonlineBiz[102]: Premium download failed | offline**
735	13.10.2015 13:02:10	INFO	Download restarted: part051.rar | **Fallback to free processing**
736	13.10.2015 13:02:10	INFO	Download starts: part051.rar
737	13.10.2015 13:02:10	INFO	HOSTER ShareonlineBiz[102]: Updating file info...
738	13.10.2015 13:02:11	INFO	HOSTER ShareonlineBiz[102]: File name: part051.rar
739	13.10.2015 13:02:11	INFO	HOSTER ShareonlineBiz[102]: File size: 110100480 bytes
740	13.10.2015 13:02:11	INFO	HOSTER ShareonlineBiz[102]: File status: starte
741	13.10.2015 13:02:11	INFO	HOSTER ShareonlineBiz[102]: **Processing as free download...**
742	13.10.2015 13:02:11	INFO	HOSTER ShareonlineBiz[102]: Waiting 3 seconds...
743	13.10.2015 13:02:15	ERROR	HOSTER ShareonlineBiz[102]: full | Keine freien Slots für Free User!
744	13.10.2015 13:02:15	INFO	HOSTER ShareonlineBiz[102]: Waiting 600 seconds...

This happens after about 10-15 Files... :-(

**Comment by sbiriguda** [comment]
Thank you so much TheTrueHansen! it's seems to work for me too...

**Comment by McGeifer** [comment]
It's working, for now :)

Line 121, for me in:
pyload/userplugins/hoster/ShareonlineBiz.py

Looks like this now and is working for me:

    html = self.load("https://api.share-online.biz/account.php",
                     get={'username': self.account.user,
                          'password': "Pass1234",
                          'act'     : "download",
                          'lid'     : self.info['fileid']})

**Comment by FRYYYYYY** [comment]
Works for me either! Thank you!!! Please fix it via update too...

**Comment by crosien2015** [comment]
If I understood right, the password is written manually in ShareonlineBiz.py. In my opinion this isn`t a solution for the next update. I would describe this as a workaround.
However, thanks for this solution/workaround. It works for me as well! :-)
Looking forward for a real solution in next update!

Cheers Christian

**Comment by heikobornholdt** [comment]
Same problem here. Please provide a fix for stable branch :cry:

**Comment by FRYYYYYY** [comment]
Of cause that is only a workaround :)

**Comment by CodeUnit** [comment]
Hello there,
the easiest way to fix the problem:
Uncomment the line 246 in the file modules/plugins/internal/Account.py.
Example:
# safe_info ['login'] ['password'] = "**********"

Good luck

**Comment by joberreiter** [comment]
@CodeUnit 
This fixes nothing, the purpose of that line is just to mask the password for log output.
`safe_info` is not used anywhere else, as a quick [search](https://github.com/pyload/pyload/search?utf8=%E2%9C%93&q=safe_info) over the whole repository indicates.

**Comment by CodeUnit** [comment]
Sorry joberreiter but for me it's working.

**Comment by ZuseZ3** [comment]
mhh workaround dont work on a qnap :(

**Comment by CodeUnit** [comment]
At my system all folders in userplugins/...  are more or less empty. So pyload used the Account.py file from modules/plugins/internal.
I'm only a c++ programmer not python but I think safe_info is only a pointer to self.info. When you change the value of safe_info you also change the value self.info.  
(Line 246 in file Account.py)

**Comment by joberreiter** [comment]
Investigating this, @CodeUnit is right!
Fixing this by deep copying the dict.
