### ISSUE TITLE
Database errors

### ISSUE THREAD

**Issue by ghost** [pyload/pyload#1958]
Hi,
whats wrong with you guys ? pyLoad is not really working since weeks.. every update brings other problems...
updated to the last client (some minutes ago) and got this problems now
i tried multiple dlc files, hoster is shareonline

Traceback (most recent call last):
  File "/usr/share/pyload/module/database/DatabaseBackend.py", line 96, in processJob
    self.result = self.f(_self.args, *_self.kwargs)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 767, in updateLink
    self.c.execute('UPDATE links SET url=?,name=?,size=?,status=?,error=?,package=? WHERE id=?', (f.url, f.name, f.size, f.status, f.error, str(f.packageid), str(f.id)))
InterfaceError: Error binding parameter 4 - probably unsupported type.
Database Error @ updateLink (PyFile 99: HH8G3QUNEST@BasePlugin,) {} Error binding parameter 4 - probably unsupported type.

**Comment by Gutz-Pilz** [comment]
Same here

**Comment by Gronkdalonka** [comment]
Yupp, same here , also mentioned in #1952

**Comment by DomiakaSnakez** [comment]
Yep, Same here!

**Comment by DomiakaSnakez** [comment]
Can't find a fix for this issue -.- i tried clean installation but no effect :(

**Comment by Garog** [comment]
still not fixed...
what the hell are you guys doing ? pyload is unusable since weeks, looks like you never try what you programming O.O

**Comment by vuolter** [comment]
Debug log please

**Comment by Garog** [comment]
please tell me how to make a debug log :/

**Comment by Garog** [comment]
i deleted everything from pyload and made a fresh pull from the sources
error is gone now, but now i stuck at #1953 ^^

**Comment by DomiakaSnakez** [comment]
Debug Log
>09.10.2015 07:43:31 INFO      ADDON UpdateManager: No plugin updates available
09.10.2015 07:43:42 DEBUG     Redirected import module.plugins.hoster.BasePlugin                                                                                                                                                              -> userplugins.hoster.BasePlugin
09.10.2015 07:43:42 DEBUG     Redirected import module.plugins.internal.SimpleHo                                                                                                                                                             ster -> userplugins.internal.SimpleHoster
09.10.2015 07:43:42 DEBUG     Redirected import module.plugins.internal.Hoster -                                                                                                                                                             > userplugins.internal.Hoster
09.10.2015 07:43:42 DEBUG     Redirected import module.plugins.internal.Base ->                                                                                                                                                              userplugins.internal.Base
09.10.2015 07:43:42 DEBUG     Redirected import module.plugins.internal.Captcha                                                                                                                                                              -> userplugins.internal.Captcha
09.10.2015 07:43:42 DEBUG     HOSTER BasePlugin[2]: Config option `use_premium`                                                                                                                                                              not found, use default `True`
09.10.2015 07:43:42 INFO      Download starts: black-20151005173222.part01.rar
09.10.2015 07:43:42 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent str                                                                                                                                                             ing: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
09.10.2015 07:43:42 DEBUG     HOSTER BasePlugin[2]: Config option `use_premium`                                                                                                                                                              not found, use default `True`
09.10.2015 07:43:42 DEBUG     HOSTER BasePlugin[2]: PROCESS URL ://http://upload                                                                                                                                                             ed.net/file/o02m3ct1/black-20151005173222.part01.rar | PLUGIN VERSION 0.46
09.10.2015 07:43:42 DEBUG     HOSTER BasePlugin[2]: Config option `fallback_prem                                                                                                                                                             ium` not found, use default `True`
09.10.2015 07:43:42 WARNING   Download failed: black-20151005173222.part01.rar |                                                                                                                                                              No plugin matched
09.10.2015 07:43:42 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates                                                                                                                                                              of: black-20151005173222.part01.rar (pid:2)
09.10.2015 07:43:42 INFO      ADDON UnSkipOnFail: No duplicates found
Traceback (most recent call last):
  File "/usr/share/pyload/module/database/DatabaseBackend.py", line 96, in proce                                                                                                                                                             ssJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/usr/share/pyload/module/database/FileDatabase.py", line 767, in updateL                                                                                                                                                             ink
    self.c.execute('UPDATE links SET url=?,name=?,size=?,status=?,error=?,packag                                                                                                                                                             e=? WHERE id=?', (f.url, f.name, f.size, f.status, f.error, str(f.packageid), st                                                                                                                                                             r(f.id)))
InterfaceError: Error binding parameter 4 - probably unsupported type.
Database Error @ updateLink (PyFile 2: black-20151005173222.part01.rar@BasePlugi                                                                                                                                                             n,) {} Error binding parameter 4 - probably unsupported type.
09.10.2015 07:43:44 DEBUG     HOSTER BasePlugin[3]: Config option `use_premium`                                                                                                                                                              not found, use default `True`

**Comment by KelghAr** [comment]
I am afraid, I have the same issue. Deleting everything does not work for me.

**Comment by DomiakaSnakez** [comment]
Did someone found a workaround? Thanks!
