### ISSUE TITLE
"uptobox premium account" does not work

### ISSUE THREAD

**Issue by damien599901** [pyload/pyload#1960]
Dear all 

I lelt alldebrid today for uptobox and uptobox does not work :( 

715	05.10.2015 20:44:41	DEBUG	ACCOUNT UptoboxCom: LOAD URL https://uptobox.com/ | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
716	05.10.2015 20:44:41	DEBUG	ACCOUNT UptoboxCom: VALID_UNTIL_PATTERN not found
717	05.10.2015 20:44:41	DEBUG	ACCOUNT UptoboxCom: TRAFFIC_LEFT_PATTERN not found
718	05.10.2015 20:44:41	DEBUG	ACCOUNT UptoboxCom: LEECH_TRAFFIC_PATTERN not found
719	05.10.2015 20:44:41	DEBUG	ACCOUNT UptoboxCom: Account info for user `damien599901`: {'login': {'timestamp': 1444070636.723067, 'password': '**********', 'valid': None}, 'data': {'validuntil': None, 'trafficleft': None, 'leechtraffic': None, 'maxtraffic': None, 'premium': False, 'options': {'limitdl': '0'}}}
Jump to time:
05.10.2015 20:43:31
  ok

**Comment by benbox69** [comment]
Same problem...

**Comment by damien599901** [comment]
pyLoad seems not to be maintained anymore. 
My boss will probably decide to erase the app of our list of apps (i work for a world brand).
Too bad ... i was a fan :(
