### ISSUE TITLE
Files don't download - RealDebrid

### ISSUE THREAD

**Issue by chaosmaker** [pyload/pyload#1961]
Hi So I have a weird issue. 

When I try and download anything via RealDebrid, it just gets some random html page even though the links that are returned work perfectly fine...

**Comment by zephura** [comment]
Same issue with :
 - Uplea
 - OneFichier
 - UploadedTo

**Comment by syss** [comment]
not even standard http downloads work:
The requested URL /https://downloads.raspberrypi.org/https://downloads.raspberrypi.org/raspbian/images/raspbian-2015-09-28/2015-09-24-raspbian-jessie.zip was not found on this server

**Comment by kasperj** [comment]
https://github.com/pyload/pyload/pull/1964

**Comment by driet** [comment]
the patch fixed it, thanks.

**Comment by chaosmaker** [comment]
That does seem to work! Now if someone could just fix the filenames problem and the fact that pyload seems to have the need to Grab my account info every second that would be great!
