### ISSUE TITLE
Uploaded.to infinite account grabbing

### ISSUE THREAD

**Issue by SniffingMyBoxers** [pyload/pyload#1962]
Since last month or so i cant download with my premium account from uploaded.to because pyload cant grab my account info successfull.
In Firefox i can download files normally on the uploaded site.

Activating Accounts...
05.10.2015 20:07:20 INFO      ACCOUNT UploadedTo: Adding user `MyAccount`...
05.10.2015 20:07:20 INFO      ACCOUNT UploadedTo: Login user `MyAccount`...
05.10.2015 20:07:20 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
05.10.2015 20:07:25 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/io/login | cookies=True | get={} | req=None | decode=True | multipart=False | post={'id': 'MyAccount', 'pw': 'MyPassword'} | ref=True | just_header=False
05.10.2015 20:07:26 INFO      ACCOUNT UploadedTo: Grabbing account info for user `MyAccount`...
05.10.2015 20:07:26 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
05.10.2015 20:07:26 DEBUG     ACCOUNT UploadedTo: Size: 505,00 | Unit: gb
05.10.2015 20:07:26 DEBUG     ACCOUNT UploadedTo: Account info for user `MyAccount`: {'login': {'timestamp': 1444075640.553887, 'password': '*******', 'valid': True}, 'data': {'validuntil': 1446397646.268898, 'trafficleft': 529530880.0, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
05.10.2015 20:07:26 INFO      Activating Plugins..

05.10.2015 20:07:26 ERROR     Error executing hooks: bad character range

05.10.2015 20:10:36 DEBUG     Run Info Fetching for UploadedTo
05.10.2015 20:10:36 INFO      Added package TestPackage containing 1 links
05.10.2015 20:10:36 INFO      ACCOUNT UploadedTo: Grabbing account info for user `MyAccount`...
05.10.2015 20:10:36 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
05.10.2015 20:10:41 DEBUG     Finished Info Fetching for UploadedTo
05.10.2015 20:10:42 DEBUG     ACCOUNT UploadedTo: Size: 505,00 | Unit: gb
05.10.2015 20:10:42 DEBUG     ACCOUNT UploadedTo: Account info for user `MyAccount`: {'login': {'timestamp': 1444075640.553887, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1446397842.361683, 'trafficleft': 529530880.0, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
05.10.2015 20:10:42 INFO      ACCOUNT UploadedTo: Login user `MyAccount`...
05.10.2015 20:10:42 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
05.10.2015 20:10:47 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/io/login | cookies=True | get={} | req=None | decode=True | multipart=False | post={'id': 'MyAccount', 'pw': 'mypassword'} | ref=True | just_header=False
05.10.2015 20:10:47 INFO      ACCOUNT UploadedTo: Grabbing account info for user `MyAccount`...
05.10.2015 20:10:47 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
05.10.2015 20:10:48 DEBUG     ACCOUNT UploadedTo: Size: 505,00 | Unit: gb
05.10.2015 20:10:48 DEBUG     ACCOUNT UploadedTo: Account info for user `MyAccount`: {'login': {'timestamp': 1444075842.375582, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1446397848.110775, 'trafficleft': 529530880.0, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
05.10.2015 20:10:48 INFO      Download starts: http://uploaded.net/file/SomeFileYouWantToDownload
05.10.2015 20:10:48 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
05.10.2015 20:10:48 INFO      ACCOUNT UploadedTo: Grabbing account info for user `MyAccount`...
05.10.2015 20:10:48 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
05.10.2015 20:10:48 DEBUG     ACCOUNT UploadedTo: Size: 505,00 | Unit: gb
05.10.2015 20:10:48 DEBUG     ACCOUNT UploadedTo: Account info for user `MyAccount`: {'login': {'timestamp': 1444075842.375582, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1446397848.278661, 'trafficleft': 529530880.0, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
05.10.2015 20:10:48 INFO      ACCOUNT UploadedTo: Grabbing account info for user `MyAccount`...
05.10.2015 20:10:48 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
05.10.2015 20:10:48 DEBUG     ACCOUNT UploadedTo: Size: 505,00 | Unit: gb
05.10.2015 20:10:48 DEBUG     ACCOUNT UploadedTo: Account info for user `MyAccount`: {'login': {'timestamp': 1444075842.375582, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1446397848.436577, 'trafficleft': 529530880.0, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
05.10.2015 20:10:48 DEBUG     HOSTER UploadedTo[2]: PROCESS URL http://uploaded.net/file/SomeFileYouWantToDownload | PLUGIN VERSION 0.97
05.10.2015 20:10:48 INFO      HOSTER UploadedTo[2]: Updating file info...
05.10.2015 20:10:50 INFO      ACCOUNT UploadedTo: Grabbing account info for user `MyAccount`...
05.10.2015 20:10:50 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
05.10.2015 20:10:50 DEBUG     ACCOUNT UploadedTo: Size: 505,00 | Unit: gb
05.10.2015 20:10:50 DEBUG     ACCOUNT UploadedTo: Account info for user `MyAccount`: {'login': {'timestamp': 1444075842.375582, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1446397850.319373, 'trafficleft': 529530880.0, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}

**Comment by pomm0** [comment]
+1 same here

**Comment by Gutz-Pilz** [comment]
+1 same here.
had to revert to my functioning backup pyload.

**Comment by Frozen-byte** [comment]
+1

**Comment by Poule-Hein** [comment]
+1

**Comment by chaosmaker** [comment]
Happens on RealDebrid also... I guess any account will be constantly refreshed!

**Comment by pomm0** [comment]
Working! Thanks!

**Comment by vuolter** [comment]
Ekk: 2 bug fixed, 266 to fix... :sob:
