### ISSUE TITLE
Error importing GoogledriveCom: invalid syntax (Plugin.py, line 273)

### ISSUE THREAD

**Issue by marviobezerra** [pyload/pyload#1971]
768	07.10.2015 22:26:48	CRITICAL	'NoneType' object has no attribute 'GoogledriveCom'
767	07.10.2015 22:26:48	ERROR	Error importing GoogledriveCom: invalid syntax (Plugin.py, line 273)
766	07.10.2015 22:26:34	INFO	pyLoad is up and running
765	07.10.2015 22:26:34	INFO	Activating Plugins...
764	07.10.2015 22:26:34	INFO	Activating Accounts...
763	07.10.2015 22:26:34	INFO	Starting builtin webserver: 0.0.0.0:8100
762	07.10.2015 22:26:34	INFO	Free space: 6.20 TiB
761	07.10.2015 22:26:34	INFO	Starting ThriftBackend: 0.0.0.0:7227
760	07.10.2015 22:26:34	INFO	Downloadtime: True
759	07.10.2015 22:26:34	INFO	Deactivate plugins: AlldebridComHook, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, LogMarker, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, TransmissionRPC, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
758	07.10.2015 22:26:34	INFO	Activated plugins:
757	07.10.2015 22:26:34	ERROR	Error importing UserAgentSwitcher: invalid syntax (Plugin.py, line 273)
756	07.10.2015 22:26:34	ERROR	Error importing XFileSharingPro: invalid syntax (Plugin.py, line 273)
755	07.10.2015 22:26:34	ERROR	Error importing UnSkipOnFail: invalid syntax (Plugin.py, line 273)
754	07.10.2015 22:26:34	ERROR	Error importing ClickAndLoad: invalid syntax (Plugin.py, line 273)
753	07.10.2015 22:26:34	ERROR	Error importing ClickNLoad: invalid syntax (Plugin.py, line 273)
752	07.10.2015 22:26:34	ERROR	Error importing UpdateManager: invalid syntax (Plugin.py, line 273)
751	07.10.2015 22:26:34	ERROR	Error importing ExtractArchive: invalid syntax (Plugin.py, line 273)
750	07.10.2015 22:26:34	ERROR	Error importing AntiStandby: invalid syntax (Plugin.py, line 273)
749	07.10.2015 22:26:34	ERROR	Error importing ExternalScripts: invalid syntax (Plugin.py, line 273)
748	07.10.2015 22:26:34	ERROR	Error importing LinkdecrypterComHook: invalid syntax (Plugin.py, line 273)
747	07.10.2015 22:26:33	INFO	Using home directory: /share/CACHEDEV1_DATA/.qpkg/pyload/data
746	07.10.2015 22:26:33	INFO	Starting pyLoad 0.4.9
745	07.10.2015 22:26:33	INFO	shutting down...
744	07.10.2015 22:26:33	INFO	restarting pyLoad

**Comment by vuolter** [comment]
Delete userplugins folder, then restart pyLoad.

**Comment by marviobezerra** [comment]
990	07.10.2015 23:42:34	CRITICAL	'NoneType' object has no attribute 'GoogledriveCom'
989	07.10.2015 23:42:34	ERROR	Error importing GoogledriveCom: No module named Plugin
988	07.10.2015 23:42:33	ERROR	Error importing GoogledriveCom: No module named Plugin
987	07.10.2015 23:42:33	INFO	Added package Mega Magina containing 1 links
986	07.10.2015 23:40:02	INFO	pyLoad is up and running
985	07.10.2015 23:40:02	INFO	Activating Plugins...
984	07.10.2015 23:40:02	INFO	Activating Accounts...
983	07.10.2015 23:40:02	INFO	Starting builtin webserver: 0.0.0.0:8100
982	07.10.2015 23:40:02	INFO	Free space: 6.20 TiB
981	07.10.2015 23:40:02	INFO	Starting ThriftBackend: 0.0.0.0:7227
980	07.10.2015 23:40:02	INFO	Downloadtime: True
979	07.10.2015 23:40:02	INFO	Deactivate plugins: AlldebridComHook, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, LogMarker, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, TransmissionRPC, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
978	07.10.2015 23:40:02	INFO	Activated plugins:
977	07.10.2015 23:40:02	ERROR	Error importing UserAgentSwitcher: No module named Plugin
976	07.10.2015 23:40:02	ERROR	Error importing XFileSharingPro: No module named Plugin
975	07.10.2015 23:40:02	ERROR	Error importing UnSkipOnFail: No module named Plugin
974	07.10.2015 23:40:02	ERROR	Error importing ClickAndLoad: No module named Plugin
973	07.10.2015 23:40:02	ERROR	Error importing ClickNLoad: No module named Plugin
972	07.10.2015 23:40:02	ERROR	Error importing UpdateManager: No module named Plugin
971	07.10.2015 23:40:02	ERROR	Error importing ExtractArchive: No module named Plugin
970	07.10.2015 23:40:02	ERROR	Error importing AntiStandby: No module named Plugin
969	07.10.2015 23:40:02	ERROR	Error importing ExternalScripts: No module named Plugin
968	07.10.2015 23:40:02	ERROR	Error importing LinkdecrypterComHook: No module named Plugin
967	07.10.2015 23:40:01	INFO	Using home directory: /share/CACHEDEV1_DATA/.qpkg/pyload/data
966	07.10.2015 23:40:01	INFO	Starting pyLoad 0.4.9
965	07.10.2015 23:40:01	INFO	shutting down...
964	07.10.2015 23:40:01	INFO	restarting pyLoad

**Comment by vuolter** [comment]
Try: http://forum.pyload.org/viewtopic.php?f=7&t=4335

**Comment by GammaC0de** [comment]
root@user-virtual-machine:~/.pyload-0.4.9# python
Python 2.7.6 (default, Mar 22 2014, 22:59:38)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> def log_critical(*args, trace=True):
  File "<stdin>", line 1
    def log_critical(*args, trace=True):
                                ^
SyntaxError: invalid syntax
>>>

**Comment by joberreiter** [comment]
Just pull the stable branch, this is fixed.

**Comment by vuolter** [comment]
@GammaC0de The bad commit was online just a minute (for real! XD), then was overwritten. It's not in the current code.

**Comment by GammaC0de** [comment]
:+1: OK, i see.
due to the excessive use of the log_xxx() functions, isn't wise the delete the `currentframe` ?
from https://docs.python.org/2/library/inspect.html:
```


Note

Keeping references to frame objects, as found in the first element of the frame records these functions return, can cause your program to create reference cycles. Once a reference cycle has been created, the lifespan of all objects which can be accessed from the objects which form the cycle can become much longer even if Python’s optional cycle detector is enabled. If such cycles must be created, it is important to ensure they are explicitly broken to avoid the delayed destruction of objects and increased memory consumption which occurs.

Though the cycle detector will catch these, destruction of the frames (and local variables) can be made deterministic by removing the cycle in a finally clause. This is also important if the cycle detector was disabled when Python was compiled or using gc.disable(). For example:

def handle_stackframe_without_leak():
    frame = inspect.currentframe()
    try:
        # do something with the frame
    finally:
        del frame

```

**Comment by vuolter** [comment]
In truth, if someone try to use pyload under a python with gc.disable, his pc will surely blown up! u.u
:smile:

**Comment by vuolter** [comment]
Anyway, I'm gonna change it with `traceback.print_exc`.

**Comment by GammaC0de** [comment]
no! thats not good..  `print_exc()` is not appropriate here because it prints the last exception details but the call to log_xxx() not always is a result of an exception and so, `print_exc()` will print  misleading and false exception information.

**Comment by vuolter** [comment]
@GammaC0de You right.

**Comment by joberreiter** [comment]
Sorry, the above reference is wrong, ignore it.
