### ISSUE TITLE
invalid syntax (Plugin.py, line 273)

### ISSUE THREAD

**Issue by milanhlavin** [pyload/pyload#1972]
ERROR	Chyba pri importu LinkdecrypterComHook: invalid syntax (Plugin.py, line 273)
ERROR	Chyba pri importu ImageTyperz: invalid syntax (Plugin.py, line 273)
ERROR	Chyba pri importu BypassCaptcha: invalid syntax (Plugin.py, line 273)
ERROR	Chyba pri importu ExternalScripts: invalid syntax (Plugin.py, line 273)
ERROR	Chyba pri importu AntiStandby: invalid syntax (Plugin.py, line 273)
ERROR	Chyba pri importu ClickNLoad: invalid syntax (Plugin.py, line 273)
ERROR	Chyba pri importu UnSkipOnFail: invalid syntax (Plugin.py, line 273)
ERROR	Chyba pri importu XFileSharingPro: invalid syntax (Plugin.py, line 273)
ERROR	Chyba pri importu Checksum: invalid syntax (Plugin.py, line 273)
ERROR	Chyba pri importu ExtractArchive: invalid syntax (Plugin.py, line 273)
ERROR	Chyba pri importu UpdateManager: invalid syntax (Plugin.py, line 273)
ERROR	Chyba pri importu UserAgentSwitcher: invalid syntax (Plugin.py, line 273)
ERROR	Error importing UlozTo: invalid syntax (Plugin.py, line 273)

**Comment by vuolter** [comment]
See: https://github.com/pyload/pyload/issues/1971

**Comment by GammaC0de** [comment]
@vuolter this is due [fixpack (4)](https://github.com/pyload/pyload/commit/958fce02e51f81a0eae4ee248db930811da91788):
````python
def log_error(self, *args, trace=False):
```
you can't use key-worded arguments in combination of `*args` in python 2.x, thats why i implemented it with `**wkarg` which is possible in v2.x
```bash
root@machine:~# python
Python 2.7.6 (default, Mar 22 2014, 22:59:38)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>> def log_critical(*args, trace=True):
  File "<stdin>", line 1
    def log_critical(*args, trace=True):
                                ^
SyntaxError: invalid syntax
>>>
```
