### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by R0ckweb** [pyload/pyload#1975]
Hi !

Today, with no change on my side, pyLoad use lot of CPU :-/

I think last plugins update cause that :( 

  PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND
 2366 yann     20   0  250m  21m 4044 R 116.7  0.1   0:15.66 python

Nothing in log (debug ON)

08.10.2015 10:10:23 INFO      Démarrage pyLoad 0.4.9
08.10.2015 10:10:23 INFO      Utilisation du dossier principal : /home/yann/.pyload
08.10.2015 10:10:23 DEBUG     Deleting old pidfile pyload.pid
08.10.2015 10:10:23 DEBUG     Remote activated: True
08.10.2015 10:10:23 DEBUG     created index of plugins
08.10.2015 10:10:23 INFO      Plugins activés: AntiStandby, ExternalScripts, ExtractArchive, LinkdecrypterComHook, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharingPro
08.10.2015 10:10:23 INFO      Plugins désactivés: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, ClickNLoad, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, LogMarker, MultiHome, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPPInterface
08.10.2015 10:10:23 INFO      Temps de téléchargement : True
08.10.2015 10:10:23 INFO      Démarre ThriftBackend: 127.0.0.1:7227
08.10.2015 10:10:24 INFO      Starting builtin webserver: 127.0.0.1:5162
08.10.2015 10:10:24 INFO      Free space: 75.31 GiB
08.10.2015 10:10:24 INFO      Activating Accounts...
08.10.2015 10:10:24 INFO      Activating Plugins...
08.10.2015 10:10:24 WARNING   ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
08.10.2015 10:10:24 INFO      HOOK XFileSharingPro: Handling any hoster I can!
08.10.2015 10:10:24 DEBUG     HOOK XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?:\w+\.)*?(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
08.10.2015 10:10:24 INFO      HOOK XFileSharingPro: Handling any crypter I can!
08.10.2015 10:10:24 DEBUG     HOOK XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?:\w+\.)*?(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:user|folder)s?/\w+
08.10.2015 10:10:24 DEBUG     ADDON ExtractArchive: Found UnRar 4.00 | Found UnZip 2.7.3
08.10.2015 10:10:24 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.10.2015 10:10:24 INFO      pyLoad is up and running
08.10.2015 10:10:24 INFO      ADDON UpdateManager: No new pyLoad version available
08.10.2015 10:10:24 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BillionuploadsCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'ShareRapidCom'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'Movie2kTo'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'EasybytezCom'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FreeWayMe'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultishareCz'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'OverLoadMe'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PutdriveCom'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RapideoPl'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RehostTo'), (u'hooks', u'ReloadCc'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SmoozedCom'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'ZeveraCom'), (u'hoster', u'File4safeCom'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'Vipleech4uCom'), (u'internal', u'AbstractExtractor'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster')]
08.10.2015 10:10:24 INFO      ADDON UpdateManager: No plugin updates available

**Comment by vuolter** [comment]
Working on...

**Comment by vuolter** [comment]
A tiny typo has made the new cpu-save design very hungry! D:
