### ISSUE TITLE
RestartFailed running infinite times

### ISSUE THREAD

**Issue by kasperj** [pyload/pyload#1983]
1063	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1064	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1065	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1066	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1067	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1068	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1069	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1070	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1071	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1072	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1073	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1074	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1075	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1076	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1077	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1078	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1079	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1080	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1081	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1082	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1083	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1084	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1085	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1086	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1087	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1088	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1089	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1090	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1091	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1092	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1093	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1094	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1095	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...
1096	08.10.2015 16:34:40	INFO	ADDON RestartFailed: Restarting all failed downloads...

**Comment by kasperj** [comment]
Seems like a restart fixed this, maybe not all plugins have been updated, closing for now, i will keep an eye on it

**Comment by vuolter** [comment]
This issue is fixed. I'm sure about that! :D

**Comment by kasperj** [comment]
As i said probably just an update problem, working fine now

**Comment by vuolter** [comment]
Don't worry. ;)
