### ISSUE TITLE
error in Plugin.py - line 273

### ISSUE THREAD

**Issue by jackdierippe** [pyload/pyload#1984]
Hello,
After all the errors of the past week, pyload won't even start the web interface now.

This is the content of the log file. Plugin.py version is 0.50 and seems to have been updated Oct  8 04:36

INFO      Starting pyLoad 0.4.9
INFO      Using home directory: /volume1/@appstore/pyload/var/config
ERROR     Error importing RestartFailed: invalid syntax (Plugin.py, line 273)
ERROR     Error importing BypassCaptcha: invalid syntax (Plugin.py, line 273)
ERROR     Error importing ExternalScripts: invalid syntax (Plugin.py, line 273)
ERROR     Error importing ExtractArchive: invalid syntax (Plugin.py, line 273)
ERROR     Error importing UpdateManager: invalid syntax (Plugin.py, line 273)
ERROR     Error importing LinkdecrypterComHook: invalid syntax (Plugin.py, line 273)
ERROR     Error importing ImageTyperz: invalid syntax (Plugin.py, line 273)
ERROR     Error importing ClickAndLoad: invalid syntax (Plugin.py, line 273)
ERROR     Error importing ClickNLoad: invalid syntax (Plugin.py, line 273)
ERROR     Error importing UnSkipOnFail: invalid syntax (Plugin.py, line 273)
ERROR     Error importing XFileSharingPro: invalid syntax (Plugin.py, line 273)
ERROR     Error importing UserAgentSwitcher: invalid syntax (Plugin.py, line 273)
INFO      Activated plugins:
INFO      Deactivate plugins: AlldebridComHook, AndroidPhoneNotify, AntiStandby, Ant
INFO      Downloadtime: True
INFO      Free space: 910.94 GiB
INFO      Activating Accounts...
INFO      Starting builtin webserver: 0.0.0.0:8000
ERROR     Error importing ShareonlineBiz: invalid syntax (Plugin.py, line 273)

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/issues/1972
