### ISSUE TITLE
Website 404

### ISSUE THREAD

**Issue by Garog** [pyload/pyload#1985]
https://get.pyload.org/get/ubuntu-cli/
same for 
https://get.pyload.org/get/ubuntu

Not Found

The requested URL /get/ubuntu-cli/ was not found on this server.

Apache/2.2.15 (Red Hat) Server at get.pyload.org Port 443

**Comment by joberreiter** [comment]
Yes, this is known.

By the way, pyload-cli-v0.4.9-all.deb is _NOT_ the latest version, please [download](https://github.com/pyload/pyload/archive/stable.zip) or clone the stable branch.

```bash
mkdir /opt/pyload && cd /opt/pyload
git clone -b stable --single-branch https://github.com/pyload/pyload.git .
```
