### ISSUE TITLE
WARNING   Not able to connect server for updates

### ISSUE THREAD

**Issue by Garog** [pyload/pyload#1986]
clean installation with the pyload-cli-v0.4.9-all.deb file

updater not working...

**Comment by joberreiter** [comment]
pyload-cli-v0.4.9-all.deb is NOT the latest version, please [download](https://github.com/pyload/pyload/archive/stable.zip) or clone stable branch with:

```bash
mkdir /opt/pyload && cd /opt/pyload
git clone -b stable --single-branch https://github.com/pyload/pyload.git .
```

**Comment by Garog** [comment]
so the only way to get a "working" version is to get the git version ?
maybe some info about would be good or taking down the old, not working, versions

**Comment by vuolter** [comment]
When the stable branch will come back to be stable, I'll publish an hotfix release.

**Comment by Velociraptor85** [comment]
https://github.com/pyload/pyload/issues/1893 <- Solution
