### ISSUE TITLE
Uploaded.to no Download possible!!! 'exceptions.OSError' object has no attribute 'strip'

### ISSUE THREAD

**Issue by mrxxxxxx** [pyload/pyload#1987]
Hello!
If i try to download with pyload on a Synology Diskstation with a Premium Uploaded.to Account there comes the following Error

WARNING	Download failed: xxxxxxxxxxxxx.rar | 'exceptions.OSError' object has no attribute 'strip'

Can someone help me to fix this error?

many many Thanx
mrxxxxx

**Comment by vuolter** [comment]
Debug log please.

**Comment by mrxxxxxx** [comment]
please, i hope this enough and the right

167	09.10.2015 01:21:35	INFO	starte pyLoad 0.4.9
168	09.10.2015 01:21:35	INFO	Benutze Home-Verzeichnis: /volume1/@appstore/pyload/etc
169	09.10.2015 01:21:35	DEBUG	Remote activated: False
170	09.10.2015 01:21:37	DEBUG	created index of plugins
171	09.10.2015 01:21:37	DEBUG	Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
172	09.10.2015 01:21:37	INFO	Aktivierte Plugins: BypassCaptcha, ClickAndLoad, ExternalScripts, ExtractArchive, HotFolder, ImageTyperz, LinkdecrypterComHook, RestartFailed, UnSkipOnFail, UserAgentSwitcher, XFileSharingPro
173	09.10.2015 01:21:37	INFO	Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, Captcha9Kw, CaptchaBrotherhood, Checksum, ClickNLoad, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, IRCInterface, JustPremium, LogMarker, MergeFiles, MultiHome, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XMPPInterface
174	09.10.2015 01:21:37	INFO	Downloadzeit: True
175	09.10.2015 01:21:38	INFO	Starting threaded webserver: 0.0.0.0:8190
176	09.10.2015 01:21:38	INFO	Free space: 6.58 TiB
177	09.10.2015 01:21:38	INFO	Activating Accounts...
178	09.10.2015 01:21:45	INFO	ACCOUNT UploadedTo: Adding user `343434`...
179	09.10.2015 01:21:45	DEBUG	ACCOUNT UploadedTo: Reached login timeout for user `343434`
180	09.10.2015 01:21:45	INFO	ACCOUNT UploadedTo: Login user `343434`...
181	09.10.2015 01:21:45	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/language/en | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
182	09.10.2015 01:21:45	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/io/login | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'id': '343434', 'pw': 'gicxvrv'} | ref=True | just_header=False
183	09.10.2015 01:21:45	INFO	ACCOUNT UploadedTo: Grabbing account info for user `343434`...
184	09.10.2015 01:21:45	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
185	09.10.2015 01:21:46	DEBUG	ACCOUNT UploadedTo: Size: 138,97 | Unit: gb
186	09.10.2015 01:21:46	DEBUG	ACCOUNT UploadedTo: Account info for user `343434`: {'login': {'timestamp': 1444346505.575186, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1453292505.9961619, 'trafficleft': 145720606.72, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
187	09.10.2015 01:21:46	INFO	Activating Plugins...
188	09.10.2015 01:21:46	INFO	HOOK XFileSharingPro: Handling any hoster I can!
189	09.10.2015 01:21:46	DEBUG	HOOK XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?:\w+\.)*?(?P(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
190	09.10.2015 01:21:46	INFO	HOOK XFileSharingPro: Handling any crypter I can!
191	09.10.2015 01:21:46	DEBUG	HOOK XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?:\w+\.)*?(?P(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:user|folder)s?/\w+
192	09.10.2015 01:21:46	DEBUG	ADDON ExtractArchive: Found UnRar 5.01 | Found SevenZip 9.20 | Found UnZip 2.7.10
193	09.10.2015 01:21:46	INFO	pyLoad is up and running
194	09.10.2015 01:21:56	INFO	ADDON ClickAndLoad: Proxy listening on 0.0.0.0:9666
195	09.10.2015 01:21:56	ERROR	ADDON ClickAndLoad: [Errno 98] Address already in use
196	09.10.2015 01:22:32	INFO	ACCOUNT UploadedTo: Grabbing account info for user `343434`...
197	09.10.2015 01:22:32	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
198	09.10.2015 01:22:32	DEBUG	ACCOUNT UploadedTo: Size: 138,97 | Unit: gb
199	09.10.2015 01:22:32	DEBUG	ACCOUNT UploadedTo: Account info for user `343434`: {'login': {'timestamp': 1444346505.575186, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1453292552.624135, 'trafficleft': 145720606.72, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
200	09.10.2015 01:22:32	INFO	Download starts: xyzxyzxyz.part01.rar
201	09.10.2015 01:22:32	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
202	09.10.2015 01:22:32	INFO	ACCOUNT UploadedTo: Grabbing account info for user `343434`...
203	09.10.2015 01:22:32	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
204	09.10.2015 01:22:32	DEBUG	ACCOUNT UploadedTo: Size: 138,97 | Unit: gb
205	09.10.2015 01:22:32	DEBUG	ACCOUNT UploadedTo: Account info for user `343434`: {'login': {'timestamp': 1444346505.575186, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1453292552.7226961, 'trafficleft': 145720606.72, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
206	09.10.2015 01:22:32	DEBUG	HOSTER UploadedTo[5276]: PROCESS URL http://uploaded.net/file/qmcw6cfm | PLUGIN VERSION 0.97
207	09.10.2015 01:22:32	INFO	HOSTER UploadedTo[5276]: Updating file info...
208	09.10.2015 01:22:32	DEBUG	HOSTER UploadedTo[5276]: File info: {'status': 2, 'url': u'http://uploaded.net/file/qmcw6cfm', 'size': 1049624000.0, 'name': 'xyzxyzxyz.part01.rar', 'pattern': {}}
209	09.10.2015 01:22:32	DEBUG	HOSTER UploadedTo[5276]: Previous file info: {}
210	09.10.2015 01:22:32	INFO	HOSTER UploadedTo[5276]: File name: xyzxyzxyz.part01.rar
211	09.10.2015 01:22:32	INFO	HOSTER UploadedTo[5276]: File size: 1049624000 bytes
212	09.10.2015 01:22:32	INFO	HOSTER UploadedTo[5276]: File status: starte
213	09.10.2015 01:22:32	INFO	HOSTER UploadedTo[5276]: Looking for direct download link...
214	09.10.2015 01:22:32	DEBUG	HOSTER UploadedTo[5276]: Redirect #0 to: http://uploaded.net/file/qmcw6cfm
215	09.10.2015 01:22:32	DEBUG	HOSTER UploadedTo[5276]: LOAD URL http://uploaded.net/file/qmcw6cfm | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
216	09.10.2015 01:22:33	INFO	HOSTER UploadedTo[5276]: Direct download link not found
217	09.10.2015 01:22:33	DEBUG	HOSTER UploadedTo[5276]: LOAD URL http://uploaded.net/file/qmcw6cfm | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
218	09.10.2015 01:22:33	INFO	ACCOUNT UploadedTo: Grabbing account info for user `343434`...
219	09.10.2015 01:22:33	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
220	09.10.2015 01:22:33	DEBUG	ACCOUNT UploadedTo: Size: 138,97 | Unit: gb
221	09.10.2015 01:22:33	DEBUG	ACCOUNT UploadedTo: Account info for user `343434`: {'login': {'timestamp': 1444346505.575186, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1453292553.271415, 'trafficleft': 145720606.72, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
222	09.10.2015 01:22:33	INFO	HOSTER UploadedTo[5276]: Filesize: 1025023 KiB | Traffic left for user `343434`: 145720606 KiB
223	09.10.2015 01:22:33	INFO	HOSTER UploadedTo[5276]: Processing as premium download...
224	09.10.2015 01:22:33	INFO	HOSTER UploadedTo[5276]: Downloading file...
225	09.10.2015 01:22:33	DEBUG	HOSTER UploadedTo[5276]: DOWNLOAD URL http://am4-r1f2-stor06.uploaded.net/dl/818a34bf-1339-4b76-be28-67457d6af3ff | cookies=True | get={} | disposition=True | post={} | ref=True
226	09.10.2015 01:22:33	WARNING	Download failed: xyzxyzxyz.part01.rar | 'exceptions.OSError' object has no attribute 'strip'
227	09.10.2015 01:22:33	INFO	Debug Report written to debug_UploadedTo_09-10-2015_01-22-33.zip
228	09.10.2015 01:22:33	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: xyzxyzxyz.part01.rar (pid:137)
229	09.10.2015 01:22:33	INFO	ADDON UnSkipOnFail: No duplicates found
230	09.10.2015 01:22:34	INFO	ACCOUNT UploadedTo: Grabbing account info for user `343434`...
231	09.10.2015 01:22:34	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
232	09.10.2015 01:22:34	DEBUG	ACCOUNT UploadedTo: Size: 138,97 | Unit: gb
233	09.10.2015 01:22:34	DEBUG	ACCOUNT UploadedTo: Account info for user `343434`: {'login': {'timestamp': 1444346505.575186, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1453292554.7541039, 'trafficleft': 145720606.72, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
234	09.10.2015 01:22:34	INFO	Download starts: xyzxyzxyz.part02.rar
235	09.10.2015 01:22:34	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
236	09.10.2015 01:22:34	INFO	ACCOUNT UploadedTo: Grabbing account info for user `343434`...
237	09.10.2015 01:22:34	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
238	09.10.2015 01:22:34	DEBUG	ACCOUNT UploadedTo: Size: 138,97 | Unit: gb
239	09.10.2015 01:22:34	DEBUG	ACCOUNT UploadedTo: Account info for user `343434`: {'login': {'timestamp': 1444346505.575186, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1453292554.8492, 'trafficleft': 145720606.72, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
240	09.10.2015 01:22:34	DEBUG	HOSTER UploadedTo[5278]: PROCESS URL http://uploaded.net/file/ypccrkp1 | PLUGIN VERSION 0.97
241	09.10.2015 01:22:34	INFO	HOSTER UploadedTo[5278]: Updating file info...
242	09.10.2015 01:22:34	DEBUG	HOSTER UploadedTo[5278]: File info: {'status': 2, 'url': u'http://uploaded.net/file/ypccrkp1', 'size': 1049624000.0, 'name': 'xyzxyzxyz.part02.rar', 'pattern': {}}
243	09.10.2015 01:22:34	DEBUG	HOSTER UploadedTo[5278]: Previous file info: {}
244	09.10.2015 01:22:34	INFO	HOSTER UploadedTo[5278]: File name: xyzxyzxyz.part02.rar
245	09.10.2015 01:22:34	INFO	HOSTER UploadedTo[5278]: File size: 1049624000 bytes
246	09.10.2015 01:22:34	INFO	HOSTER UploadedTo[5278]: File status: starte
247	09.10.2015 01:22:34	INFO	HOSTER UploadedTo[5278]: Looking for direct download link...
248	09.10.2015 01:22:34	DEBUG	HOSTER UploadedTo[5278]: Redirect #0 to: http://uploaded.net/file/ypccrkp1
249	09.10.2015 01:22:34	DEBUG	HOSTER UploadedTo[5278]: LOAD URL http://uploaded.net/file/ypccrkp1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
250	09.10.2015 01:22:35	INFO	HOSTER UploadedTo[5278]: Direct download link not found
251	09.10.2015 01:22:35	DEBUG	HOSTER UploadedTo[5278]: LOAD URL http://uploaded.net/file/ypccrkp1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
252	09.10.2015 01:22:35	INFO	ACCOUNT UploadedTo: Grabbing account info for user `343434`...
253	09.10.2015 01:22:35	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
254	09.10.2015 01:22:35	DEBUG	ACCOUNT UploadedTo: Size: 138,97 | Unit: gb
255	09.10.2015 01:22:35	DEBUG	ACCOUNT UploadedTo: Account info for user `343434`: {'login': {'timestamp': 1444346505.575186, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1453292555.350436, 'trafficleft': 145720606.72, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}
256	09.10.2015 01:22:35	INFO	HOSTER UploadedTo[5278]: Filesize: 1025023 KiB | Traffic left for user `343434`: 145720606 KiB
257	09.10.2015 01:22:35	INFO	HOSTER UploadedTo[5278]: Processing as premium download...
258	09.10.2015 01:22:35	INFO	HOSTER UploadedTo[5278]: Downloading file...
259	09.10.2015 01:22:35	DEBUG	HOSTER UploadedTo[5278]: DOWNLOAD URL http://am4-r1f4-stor07.uploaded.net/dl/23d832dc-62c1-4589-a029-b9dfe806393a | cookies=True | get={} | disposition=True | post={} | ref=True
260	09.10.2015 01:22:35	WARNING	Download failed: xyzxyzxyz.part02.rar | 'exceptions.OSError' object has no attribute 'strip'
261	09.10.2015 01:22:35	INFO	Debug Report written to debug_UploadedTo_09-10-2015_01-22-35.zip
262	09.10.2015 01:22:35	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: xyzxyzxyz.part02.rar (pid:137)
263	09.10.2015 01:22:35	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by joberreiter** [comment]
Same issue as #1946.

**Comment by vuolter** [comment]
@mrxxxxxx Retry now.
