### ISSUE TITLE
[uptobox | 1fichier] invalid syntax (Plugin.py, line 273),'NoneType' object has no attribute

### ISSUE THREAD

**Issue by pixou80** [pyload/pyload#1988]
new error:

ERROR	Error importing OneFichierCom: invalid syntax (Plugin.py, line 273)
CRITICAL	'NoneType' object has no attribute 'OneFichierCom'
ERROR	Error importing UptoboxCom: invalid syntax (Plugin.py, line 273)
INFO	Added package film containing 1 links
ERROR	Error importing UptoboxCom: invalid syntax (Plugin.py, line 273)
CRITICAL	'NoneType' object has no attribute 'UptoboxCom'

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/issues/1984
