### ISSUE TITLE
bug in ConfigParser.py

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1996]
Hi,
There is a bug in `ConfigParser.py` which is also present in v0.4.10:
If the description part or the value part of a line in the config file contains `=` (`:` too?)  characters (e.g. `Captcha9Kw`'s `hoster_options`), this line will not parsed correctly.
This also makes `plugin.conf` bigger on every `pyLoad` startup (see the size of `Captcha9Kw`'s `hoster_options` grows with every start)

Since its a core issue, nothing can be done in v0.4.9 beside removing `hoster_options` support from `Captcha9Kw`..

I will post a fix for v0.4.10

maybe this is the reason for the recent issues with config not saved

**Comment by vuolter** [comment]
Remote repo is not updated, I just have some unfinished commits to push, but I'm currently focus on stable branch as you can see. ;)

**Comment by GammaC0de** [comment]
yes, i can see that :+1: 
hopefully, will be updated soon :) (I have few unmerged PRs there, wink wink)

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/6c5c72b1a657e91f4ffee88629a3523cda8cacd1
