### ISSUE TITLE
How to : Fresh Install

### ISSUE THREAD

**Issue by bast69** [pyload/pyload#2000]
Hi,
Now that the site to download is down (http://get.pyload.org/get/ubuntu), I download the stable version, but how to do a fresh install on a raspberry (debian) ?
Thanks you very well

**Comment by GammaC0de** [comment]
"proper" installation of `pyLoad`:
* get `pyLoad` for your OS from https://github.com/pyload/pyload/releases
* replace the `<pyload directory>module/plugins/hooks/UpdateManager.py` file  with this one: https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py
* Start `pyLoad`
* Wait for update to finish
* Wacth the log:  you may have to manually restart `pyLoad` for `UpdateManager` finish its job

Please note that pyLoad is not stable at the moment.

**Comment by vuolter** [comment]
@GammaC0de :+1:

**Comment by tomtompy** [comment]
Hi,

- I update my syno
- can't launch Pyload… 
- do a Refresh install from pyLoad-0.4.9-4-armv5.spk at http://spk.unzureichende.info/dl/pyLoad-0.4.9-4-armv5.spk

- find why : Pyload user was disabled 
- Be sade

So I do this manual update on UpdateManager.py … but plugin are not update and I can see a notification : pyload update available…

**Comment by GammaC0de** [comment]
@tomtompy Please open a new issue, thanks
