### ISSUE TITLE
[Account] Stuck at activating accounts

### ISSUE THREAD

**Issue by mcmaxl** [pyload/pyload#2001]
516	10.10.2015 22:19:22	INFO	starte pyLoad 0.4.9
517	10.10.2015 22:19:22	INFO	Benutze Home-Verzeichnis: /opt/pyload-config
518	10.10.2015 22:19:22	DEBUG	Deleting old pidfile pyload.pid
519	10.10.2015 22:19:22	DEBUG	Remote activated: True
520	10.10.2015 22:19:23	DEBUG	created index of plugins
521	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.hooks.LinkdecrypterComHook -> userplugins.hooks.LinkdecrypterComHook
522	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
523	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
524	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.hooks.MovieMover -> userplugins.hooks.MovieMover
525	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
526	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.hooks.ImageTyperz -> userplugins.hooks.ImageTyperz
527	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.internal.Hook -> userplugins.internal.Hook
528	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.hooks.BypassCaptcha -> userplugins.hooks.BypassCaptcha
529	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
530	10.10.2015 22:19:23	WARNING	Konnte ExternalScripts nicht aktivieren
531	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
532	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.hooks.Captcha_9kw -> userplugins.hooks.Captcha_9kw
533	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.hooks.Checksum -> userplugins.hooks.Checksum
534	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
535	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
536	10.10.2015 22:19:23	DEBUG	Redirected import module.plugins.hooks.EpisodeMover -> userplugins.hooks.EpisodeMover
537	10.10.2015 22:19:24	DEBUG	Redirected import module.plugins.hooks.SJ -> userplugins.hooks.SJ
538	10.10.2015 22:19:24	DEBUG	Redirected import module.plugins.hooks.RestartFailed -> userplugins.hooks.RestartFailed
539	10.10.2015 22:19:24	DEBUG	Redirected import module.plugins.hooks.HDAreaOrg -> userplugins.hooks.HDAreaOrg
540	10.10.2015 22:19:24	DEBUG	Redirected import module.plugins.hooks.PushExtension -> userplugins.hooks.PushExtension
541	10.10.2015 22:19:24	INFO	Aktivierte Plugins: BypassCaptcha, Captcha_9kw, Checksum, ClickAndLoad, EpisodeMover, ExtractArchive, HDAreaOrg, ImageTyperz, LinkdecrypterComHook, MovieMover, PushExtension, RestartFailed, SJ, UnSkipOnFail, UpdateManager
542	10.10.2015 22:19:24	INFO	Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, Captcha9Kw, CaptchaBrotherhood, ClickNLoad, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, JustPremium, LogMarker, MergeFiles, MultiHome, RestartSlow, SkipRev, TransmissionRPC, UserAgentSwitcher, WindowsPhoneNotify, XFileSharingPro, XMPPInterface
543	10.10.2015 22:19:24	INFO	Downloadzeit: True
544	10.10.2015 22:19:24	INFO	Starte ThriftBackend: 0.0.0.0:7227
545	10.10.2015 22:19:24	INFO	Starting builtin webserver: 0.0.0.0:8000
546	10.10.2015 22:19:24	INFO	Free space: 2.59 TiB
547	10.10.2015 22:19:24	INFO	Activating Accounts...
548	10.10.2015 22:19:24	DEBUG	Redirected import module.plugins.accounts.UploadedTo -> userplugins.accounts.UploadedTo
549	10.10.2015 22:19:24	DEBUG	Redirected import module.plugins.internal.Account -> userplugins.internal.Account

**Comment by jackdierippe** [comment]
The same situation here since last update log stopped at Activating Accounts
Web interface is down 
Have this warning at beginning of log : Failed activating ExternalScripts

**Comment by vuolter** [comment]
Working on...
