### ISSUE TITLE
[ExtractArchive] no attribute '_Plugin__type'

### ISSUE THREAD

**Issue by mcmaxl** [pyload/pyload#2004]
11.10.2015 10:43:20 INFO      Free space: 2.59 TiB
11.10.2015 10:43:20 INFO      Activating Accounts...
11.10.2015 10:43:20 INFO      Activating Plugins...
11.10.2015 10:43:20 DEBUG     MovieMover: Initial search on startup activated. Proceeding...
11.10.2015 10:43:20 INFO      MovieMover: No movies in "/volume1/pyload_downloads" to process.
11.10.2015 10:43:21 DEBUG     Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
11.10.2015 10:43:21 DEBUG     Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
11.10.2015 10:43:21 DEBUG     Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
11.10.2015 10:43:21 ERROR     Error executing hooks: 'ExtractArchive' object has no attribute '_Plugin__type'
11.10.2015 10:43:21 INFO      pyLoad is up and running

**Comment by vuolter** [comment]
Renstall pyload.
