### ISSUE TITLE
RealDebridHook not loading

### ISSUE THREAD

**Issue by chaosmaker** [pyload/pyload#2008]
@vuolter Hi - so although a lot of fixes have gone through a fresh install of all userscripts still gives me the following error:

```
11.10.2015 17:37:50 WARNING   Failed activating RealdebridComHook
Traceback (most recent call last):
  File "/volume1/public/pyload/pyload/module/HookManager.py", line 130, in createIndex
    plugin = pluginClass(self.core, self)
  File "/volume1/public/pyload/pyload/module/plugins/internal/Hook.py", line 23, in __init__
    self.init_periodical(10)
AttributeError: 'RealdebridComHook' object has no attribute 'init_periodical'
```

**Comment by vuolter** [comment]
There is no Hook plugin anymore in current code. O.o

**Comment by chaosmaker** [comment]
@vuolter So no RealDebrid plugin for now? I pulled the most recent git and I can't get RealDebrid to be used at all...

**Comment by vuolter** [comment]
To simplify the code and improve plugins maintenance and reliability, multi-hoster feature is now built-in with account plugin. Thr bad news is that the MultiAccount plugin (that handles that task) is not ready...

**Comment by fzimmermann89** [comment]
Any news?
