### ISSUE TITLE
UlozTo Hoster plugin is not working with password protected items

### ISSUE THREAD

**Issue by izderadicka** [pyload/pyload#2012]
Got wrong password error , when correct password was set in package - password verified on Ulozto site.
method check_errors, which should post password is not called - adding it to beginning of handle_free hepled (just needed to fix there references to pyfile) .

**Comment by GammaC0de** [comment]
debug log & sample URL please

**Comment by izderadicka** [comment]
Hi,

cannot provide debug log due to this issue: #2003 
<https://github.com/pyload/pyload/issues/2003>
URL: |http://uloz.to/xC4yW96z/c-rar|

However this diff fixed issue for me:

***************
*** 50,60 ****


       def handle_free(self, pyfile):
           action, inputs = 
self.parse_html_form('id="frm-downloadDialog-freeDownloadForm"')
           if not action or not inputs:
               self.error(_("Free download form not found"))

!         self.log_debug("inputs.keys = %s" % inputs.keys())
           #: Get and decrypt captcha
           if all(key in inputs for key in ("captcha_value", 
"captcha_id", "captcha_key")):
               #: Old version - last seen 9.12.2013
--- 48,59 ----


       def handle_free(self, pyfile):
*+         self.check_errors()*
           action, inputs = 
self.parse_html_form('id="frm-downloadDialog-freeDownloadForm"')
           if not action or not inputs:
               self.error(_("Free download form not found"))

!         self.log_debug("inputs.keys = " + str(inputs.keys()))
           #: Get and decrypt captcha
           if all(key in inputs for key in ("captcha_value", 
"captcha_id", "captcha_key")):
               #: Old version - last seen 9.12.2013
***************
*** 99,105 ****
               if m is None:
                   self.error(_("TOKEN_PATTERN not found"))

!             self.html = self.load(pyfile.url,
                                     get={'do': "askAgeForm-submit"},
                                     post={'agree': "Confirm", 
'_token_': m.group(1)})

--- 97,103 ----
               if m is None:
                   self.error(_("TOKEN_PATTERN not found"))

!             self.html = self.load(*self.pyfile.url,*
                                     get={'do': "askAgeForm-submit"},
                                     post={'agree': "Confirm", 
'_token_': m.group(1)})

***************
*** 108,124 ****

               if password:
                   self.log_info(_("Password protected link, trying ") + 
password)
!                 self.html = self.load(pyfile.url,
                                         get={'do': 
"passwordProtectedForm-submit"},
                                         post={'password': password, 
'password_send': 'Send'})

                   if self.PASSWD_PATTERN in self.html:
!                     self.fail(_("Wrong password"))
               else:
                   self.fail(_("No password found"))

           if re.search(self.VIPLINK_PATTERN, self.html):
!             self.html = self.load(pyfile.url, get={'disclaimer': "1"})

           return super(UlozTo, self).check_errors()

--- 106,122 ----

               if password:
                   self.log_info(_("Password protected link, trying ") + 
password)
!                 self.html = self.load(*self.pyfile.url,*
                                         get={'do': 
"passwordProtectedForm-submit"},
                                         post={'password': password, 
'password_send': 'Send'})

                   if self.PASSWD_PATTERN in self.html:
!                     self.fail(_("Incorrect password"))
               else:
                   self.fail(_("No password found"))

           if re.search(self.VIPLINK_PATTERN, self.html):
!             self.html = self.load(*self.pyfile.url,* 
get={'disclaimer': "1"})

           return super(UlozTo, self).check_errors()

***************

**Comment by GammaC0de** [comment]
so issue a PR and then close this issue :+1:

**Comment by izderadicka** [comment]
I cannt - because my version contains other changes related to audio 
captcha recognition and also is already out of sync with latest version.
Should be better if maintainer fixes it.

I.

**Comment by GammaC0de** [comment]
No issues with UlozTo  anymore.
