### ISSUE TITLE
cannot VACUUM from within a transaction

### ISSUE THREAD

**Issue by rathsky** [pyload/pyload#2013]
Clean install from stable on Arch Linux, wiped ~/.pyload for good measure.

I get as far as Basic Setup, then it's always

> The following logindata is valid for CLI, GUI and webinterface.
> Exception in thread Thread-1:
> Traceback (most recent call last):
>  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>    self.run()
>  File "/opt/pyload/module/database/DatabaseBackend.py", line 140, in run
>    self._createTables()
>  File "/opt/pyload/module/database/DatabaseBackend.py", line 246, in _createTables
>    self.c.execute('VACUUM')
> OperationalError: cannot VACUUM from within a transaction

Updated both sqlite and python2.7 to git, no change. Removing the line works, though.

**Comment by hahiserw** [comment]
I have the same issue. I made it to the end of the installation without the error (by not making basic setup nor web interface), but when I try to run the server the error is shown.

**Comment by DocMAX** [comment]
any news on this?

**Comment by GammaC0de** [comment]
@DocMAX Try adding:
```python
        self.c.execute('COMMIT')

```
before line 246 in DatabaseBackend.py and report if it solves the problem.

**Comment by DocMAX** [comment]
Didn't help. Maybe you meant replacing instead adding?

**Comment by GammaC0de** [comment]
No, I meant adding, although I think the 'VACUUM' statement is not must, try removing the line, see if it helps

**Comment by GammaC0de** [comment]
@DocMAX can you try moving this line to line 144, e.g:
```python
        self.conn.commit()

        self.c.execute('VACUUM')        

        self.setuplock.set()
```

**Comment by DocMAX** [comment]
I just replaced VACUUM with COMMIT. works.

**Comment by GammaC0de** [comment]
@DocMAX Yes, but VACUUM and COMMIT do different things, can you please check the solution I proposed in https://github.com/pyload/pyload/issues/2013#issuecomment-254951430?

**Comment by DocMAX** [comment]
Doesnt work

`The following logindata is valid for CLI, GUI and webinterface.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/database/DatabaseBackend.py", line 145, in run
    self.c.execute('VACUUM')
OperationalError: cannot VACUUM from within a transaction`

**Comment by GammaC0de** [comment]
Ok, thanks.

**Comment by GammaC0de** [comment]
BTW, what OS are you running?

**Comment by DocMAX** [comment]
I'm happy with the COMMIT replace

**Comment by DocMAX** [comment]
Linux server 4.7.6-1-ARCH #1 SMP PREEMPT Fri Sep 30 19:28:42 CEST 2016 x86_64 GNU/Linux

**Comment by Velociraptor85** [comment]
@GammaC0de close?

**Comment by GammaC0de** [comment]
👍
