### ISSUE TITLE
[OneFichierCom] Premium account still in waiting

### ISSUE THREAD

**Issue by fab76** [pyload/pyload#2014]
Hi thanks for your hard work,

Since last week, I can't download anything with my premuim account, all the downloads remain in waiting.
i've tried without my premuim account, and the download worked.
Pyload is up to date, and my pycurl and curl versions too (7.19.5.1 and 7.45.0)

Have you an idea?

Thanks

464 12.10.2015 09:53:07 INFO    HOSTER OneFichierCom[3]: Updating file info...
465 12.10.2015 09:53:08 INFO    HOSTER OneFichierCom[3]: File name: ?0vlk98plwu
466 12.10.2015 09:53:08 INFO    HOSTER OneFichierCom[3]: File size: 178 bytes
467 12.10.2015 09:53:08 INFO    HOSTER OneFichierCom[3]: File status: démarrage
468 12.10.2015 09:53:08 INFO    HOSTER OneFichierCom[3]: Looking for direct download link...
469 12.10.2015 09:53:09 INFO    HOSTER OneFichierCom[3]: Direct download link not found
470 12.10.2015 09:53:10 INFO    HOSTER OneFichierCom[3]: Updating file info...
471 12.10.2015 09:53:11 INFO    HOSTER OneFichierCom[3]: File name: 432FHD.mp4
472 12.10.2015 09:53:11 INFO    HOSTER OneFichierCom[3]: File size: 442582958 bytes
473 12.10.2015 09:53:11 INFO    HOSTER OneFichierCom[3]: Updating file info...
474 12.10.2015 09:53:12 INFO    HOSTER OneFichierCom[3]: File name: 432FHD.mp4
475 12.10.2015 09:53:12 INFO    HOSTER OneFichierCom[3]: File size: 442582958 bytes
476 12.10.2015 09:53:12 INFO    HOSTER OneFichierCom[3]: File status: démarrage
477 12.10.2015 09:53:12 INFO    HOSTER OneFichierCom[3]: Processing as premium download...
478 12.10.2015 09:53:13 INFO    HOSTER OneFichierCom[3]: Checking downloaded file...
479 12.10.2015 09:53:13 WARNING HOSTER OneFichierCom[3]: Check result: Html file | Waiting 1 minute and retry
480 12.10.2015 09:53:13 INFO    HOSTER OneFichierCom[3]: Waiting 60 seconds...
481 12.10.2015 09:53:13 INFO    HOSTER OneFichierCom[3]: Requiring reconnection...
482 12.10.2015 09:53:13 WARNING HOSTER OneFichierCom[3]: Ignore reconnection due logged account

**Comment by vuolter** [comment]
Working on...

**Comment by fab76** [comment]
thanks

**Comment by youlJunior** [comment]
I have another strange behaviour.
When I add a link from OneFichier.com, it detects the wait time (15 minutes), but there's a thread that start the download in background.
In the web gui, it shows that it wait 15 minutes with the countdown, but the file is downloaded fully.

Here is the log : 

23.10.2015 01:08:01 INFO      Added package Test1 containing 1 links
23.10.2015 01:08:01 DEBUG     Redirected import module.plugins.hoster.OneFichierCom -> userplugins.hoster.OneFichierCom
23.10.2015 01:08:01 DEBUG     Run Info Fetching for OneFichierCom
23.10.2015 01:08:02 INFO      Download starts: https://1fichier.com/?utxaxnrwl6
23.10.2015 01:08:02 DEBUG     HOSTER OneFichierCom[14]: Plugin version: 0.94
23.10.2015 01:08:02 DEBUG     HOSTER OneFichierCom[14]: Plugin status: testing
23.10.2015 01:08:02 WARNING   HOSTER OneFichierCom[14]: Plugin may be unstable
23.10.2015 01:08:02 INFO      HOSTER OneFichierCom[14]: Grabbing link info...
23.10.2015 01:08:04 DEBUG     Finished Info Fetching for OneFichierCom
23.10.2015 01:08:04 INFO      Download starts: https://1fichier.com/?utxaxnrwl6
23.10.2015 01:08:04 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
23.10.2015 01:08:04 DEBUG     HOSTER OneFichierCom[14]: Plugin version: 0.94
23.10.2015 01:08:04 DEBUG     HOSTER OneFichierCom[14]: Plugin status: testing
23.10.2015 01:08:04 WARNING   HOSTER OneFichierCom[14]: Plugin may be unstable
23.10.2015 01:08:04 INFO      HOSTER OneFichierCom[14]: Grabbing link info...
23.10.2015 01:08:05 DEBUG     HOSTER OneFichierCom[14]: Link info: {'status': 3, 'pattern': {'HOST': u'1fichier.com'}, 'size': 0, 'url': u'http://1fichier.com/?utxaxnrwl6', 'na
me': '?utxaxnrwl6'}
23.10.2015 01:08:05 DEBUG     HOSTER OneFichierCom[14]: Previous link info: {}
23.10.2015 01:08:05 INFO      HOSTER OneFichierCom[14]: Link name: ?utxaxnrwl6
23.10.2015 01:08:05 INFO      HOSTER OneFichierCom[14]: Link size: N/D
23.10.2015 01:08:05 INFO      HOSTER OneFichierCom[14]: Link status: en file d'attente
23.10.2015 01:08:05 INFO      HOSTER OneFichierCom[14]: Looking for direct download link...
23.10.2015 01:08:05 DEBUG     HOSTER OneFichierCom[14]: Redirect #0 to: http://1fichier.com/?utxaxnrwl6
23.10.2015 01:08:05 DEBUG     HOSTER OneFichierCom[14]: LOAD URL http://1fichier.com/?utxaxnrwl6 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=Fa
lse | post={} | ref=True | just_header=True
23.10.2015 01:08:05 DEBUG     HOSTER OneFichierCom[14]: Redirect #1 to: https://1fichier.com/?utxaxnrwl6
23.10.2015 01:08:05 DEBUG     HOSTER OneFichierCom[14]: LOAD URL https://1fichier.com/?utxaxnrwl6 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=F
alse | post={} | ref=True | just_header=True
23.10.2015 01:08:06 INFO      HOSTER OneFichierCom[14]: Direct download link not found
23.10.2015 01:08:06 DEBUG     HOSTER OneFichierCom[14]: LOAD URL http://1fichier.com/?utxaxnrwl6 | redirect=True | cookies=[('1fichier.com', 'LG', 'en')] | get={} | req=None |
decode=True | multipart=False | post={} | ref=False | just_header=False
23.10.2015 01:08:07 INFO      HOSTER OneFichierCom[14]: Grabbing link info...
23.10.2015 01:08:08 DEBUG     HOSTER OneFichierCom[14]: Link info: {'status': 3, 'name': '?utxaxnrwl6', 'url': u'http://1fichier.com/?utxaxnrwl6', 'pattern': {'HOST': u'1fichie
r.com'}, 'size': 0}
23.10.2015 01:08:08 DEBUG     HOSTER OneFichierCom[14]: Previous link info: {}
23.10.2015 01:08:08 INFO      HOSTER OneFichierCom[14]: Link name: ?utxaxnrwl6
23.10.2015 01:08:08 INFO      HOSTER OneFichierCom[14]: Link size: N/D
23.10.2015 01:08:08 INFO      HOSTER OneFichierCom[14]: Link status: en file d'attente
23.10.2015 01:08:08 INFO      HOSTER OneFichierCom[14]: Looking for direct download link...
23.10.2015 01:08:08 DEBUG     HOSTER OneFichierCom[14]: Redirect #0 to: http://1fichier.com/?utxaxnrwl6
23.10.2015 01:08:08 DEBUG     HOSTER OneFichierCom[14]: LOAD URL http://1fichier.com/?utxaxnrwl6 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=Fa
lse | post={} | ref=True | just_header=True
23.10.2015 01:08:08 DEBUG     HOSTER OneFichierCom[14]: Redirect #1 to: https://1fichier.com/?utxaxnrwl6
23.10.2015 01:08:08 DEBUG     HOSTER OneFichierCom[14]: LOAD URL https://1fichier.com/?utxaxnrwl6 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=F
alse | post={} | ref=True | just_header=True
23.10.2015 01:08:08 DEBUG     HOSTER OneFichierCom[14]: Link info: {'status': 2, 'name': u'Fargo.S02E01.FRENCH.WEBRip.x264-LiBERTY.mp4', 'url': u'http://1fichier.com/?utxaxnrwl
6', 'pattern': {'HOST': u'1fichier.com', 'U': u'MB', 'S': u'438.94', 'N': u'Fargo.S02E01.FRENCH.WEBRip.x264-LiBERTY.mp4'}, 'size': 460238848}
23.10.2015 01:08:08 DEBUG     HOSTER OneFichierCom[14]: Previous link info: {'status': 3, 'pattern': {'HOST': u'1fichier.com'}, 'url': u'http://1fichier.com/?utxaxnrwl6', 'name
': '?utxaxnrwl6', 'size': 0}
23.10.2015 01:08:08 INFO      HOSTER OneFichierCom[14]: Link name: Fargo.S02E01.FRENCH.WEBRip.x264-LiBERTY.mp4
23.10.2015 01:08:08 INFO      HOSTER OneFichierCom[14]: Link size: 438.92 MiB (460238848 bytes)
23.10.2015 01:08:08 INFO      HOSTER OneFichierCom[14]: Link status: en ligne
23.10.2015 01:08:08 INFO      HOSTER OneFichierCom[14]: Processing as free download...
23.10.2015 01:08:08 DEBUG     HOSTER OneFichierCom[14]: DOWNLOAD URL https://1fichier.com/?utxaxnrwl6 | cookies=True | resume=None | get={} | disposition=True | chunks=None | p
ost={u'dl_no_ssl': '', 'submit': 'Download', u'dlinline': ''} | ref=True
23.10.2015 01:08:09 INFO      HOSTER OneFichierCom[14]: Direct download link not found
23.10.2015 01:08:09 DEBUG     HOSTER OneFichierCom[14]: LOAD URL http://1fichier.com/?utxaxnrwl6 | redirect=True | cookies=[('1fichier.com', 'LG', 'en')] | get={} | req=None |
decode=True | multipart=False | post={} | ref=False | just_header=False
23.10.2015 01:08:10 INFO      HOSTER OneFichierCom[14]: Processing as free download...
23.10.2015 01:08:10 DEBUG     HOSTER OneFichierCom[14]: Config option `max_wait` not found, use default `10`
23.10.2015 01:08:10 DEBUG     HOSTER OneFichierCom[14]: WAIT set to timestamp 1445556191.669442 | Previous waitUntil: 0.000000
23.10.2015 01:08:10 DEBUG     HOSTER OneFichierCom[14]: RECONNECT  required | Previous wantReconnect: False
23.10.2015 01:08:10 INFO      HOSTER OneFichierCom[14]: Waiting 15 minutes...
23.10.2015 01:08:10 INFO      HOSTER OneFichierCom[14]: Requiring reconnection...
23.10.2015 01:08:14 DEBUG     Content-Disposition: Fargo.S02E01.FRENCH.WEBRip.x264-LiBERTY.mp4 filename*=UTF-8Fargo.S02E01.FRENCH.WEBRip.x264-LiBERTY.mp4
23.10.2015 01:12:48 INFO      HOSTER OneFichierCom[14]: `Fargo.S02E01.FRENCH.WEBRip.x264-LiBERTY.mp4` saved as `Fargo.S02E01.FRENCH.WEBRip.x264-LiBERTY.mp4`
23.10.2015 01:12:48 INFO      HOSTER OneFichierCom[14]: Checking downloaded file...
23.10.2015 01:12:49 DEBUG     HOSTER OneFichierCom[14]: Config option `chk_filesize` not found, use default `None`
23.10.2015 01:12:49 INFO      HOSTER OneFichierCom[14]: File is OK
23.10.2015 01:12:49 DEBUG     HOSTER OneFichierCom[14]: Performing default check rules...
23.10.2015 01:12:49 DEBUG     HOSTER OneFichierCom[14]: Performing custom check rules...
23.10.2015 01:12:49 INFO      Download finished: Fargo.S02E01.FRENCH.WEBRip.x264-LiBERTY.mp4
23.10.2015 01:12:49 INFO      ADDON ExternalScripts: EXECUTE [/etc/pyload/scripts/download_finished] ['/etc/pyload/scripts/download_finished/script_dl_done.sh', '14', 'Fargo.S0
2E01.FRENCH.WEBRip.x264-LiBERTY.mp4', '/HDD4/Pyload/Fargo.S02E01.FRENCH.WEBRip.x264-LiBERTY.mp4', 'OneFichierCom', 'http://1fichier.com/?utxaxnrwl6']
23.10.2015 01:12:50 INFO      Package finished: Test1
23.10.2015 01:13:04 DEBUG     Cleared Result cache

**Comment by damien599901** [comment]
same issue again and again and again 

- onefichier premium dead
- uptobox premium dead 
- debriditalia premium dead
- alldebrid premium dead

My boss will probably choose Jdownloader on on all our devices for our society which is all over the world (the choice will done last week)

have a nice week end

**Comment by neomatfr** [comment]
Same issue !

if In the 1fichier console I check : "Show the download menu" the file is renamed correctly but no download (only 178B) and waiting 1 minute in loop.

If I disable the option (default 1 fichier option) "Show the download menu" download work but I have to rename file !

Thnaks

**Comment by fab76** [comment]
I've maybe a temporary solution
if we disable ssl from the 1fichier console, and if we add the 1fichier link in pyload in http:// without the s, the dowload works...

**Comment by fab76** [comment]
I've still the same issue, do you find a solution to fix it? thanks

**Comment by GammaC0de** [comment]
@fab76 You should enable direct downloads in 1fichier.com

**Comment by fab76** [comment]
Hi GammaC0de, thanks for your fast answer.

Do you mean disable the "Force download menu" , with disabling it, the download start, but the files are wrongly nammed :

244	01.12.2016 08:15:18	INFO	HOSTER OneFichierCom[6]: Grabbing link info...
245	01.12.2016 08:15:20	INFO	HOSTER OneFichierCom[6]: Link name: ?6y8ldm0k20
246	01.12.2016 08:15:20	INFO	HOSTER OneFichierCom[6]: Link size: 178.00 B (178 bytes)
247	01.12.2016 08:15:20	INFO	HOSTER OneFichierCom[6]: Link status: démarrage
248	01.12.2016 08:15:20	INFO	HOSTER OneFichierCom[6]: Processing url: http://1fichier.com/?6y8ldm0k20
249	01.12.2016 08:15:20	INFO	HOSTER OneFichierCom[6]: Looking for direct download link...
250	01.12.2016 08:15:22	INFO	HOSTER OneFichierCom[6]: Direct download link detected
251	01.12.2016 08:15:22	INFO	HOSTER OneFichierCom[6]: Downloading file...
252	01.12.2016 08:15:41	INFO	Download aborted: ?6y8ldm0k20

**Comment by GammaC0de** [comment]
@fab76 This is a know issue with OneFichierCom plugin.
I you would like me to try and fix this, I will need account login and password for testing.
Please send account information to nitzo2001 at yahoo dot com.

**Comment by fab76** [comment]
@GammaC0de , just send the email thanks

**Comment by GammaC0de** [comment]
👍

**Comment by fab76** [comment]
It's working well thanks very much :)

**Comment by GammaC0de** [comment]
👍
