### ISSUE TITLE
'utf8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#2017]
getting error 
'utf8' codec can't decode byte 0xff in position 0: invalid start byte

but don't know whether this is my bad running ubuntu or pyload :S

Debug log
http://pastebin.com/TavyKyL0

**Comment by joberreiter** [comment]
I can confirm this error, so it's not your machine or installation.

**Comment by vicegold** [comment]
Same here.

**Comment by mcmaxl** [comment]
same here

**Comment by Gutz-Pilz** [comment]
https://github.com/pyload/pyload/issues/2025

**Comment by joberreiter** [comment]
Is basically working with fix 477046e0b1bb37e294db6ceab68462c0fc797ea7 again.

**Comment by Gutz-Pilz** [comment]
@vuolter it also needs version up to be updated i guess ?

**Comment by vuolter** [comment]
@Gutz-Pilz Done! .)
