### ISSUE TITLE
'utf8' codec can't decode

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#2025]
when i try to decrypt filecrypt.cc links
it seems to be a circle captcha.

```
14.10.2015 13:15:22 INFO      Decrypting starts: https://www.filecrypt.cc/Container/3CAF813F45.html
14.10.2015 13:15:22 DEBUG     CRYPTER FilecryptCc[13]: Config option `use_premium` not found, use default `True`
14.10.2015 13:15:22 DEBUG     CRYPTER FilecryptCc[13]: PROCESS URL https://www.filecrypt.cc/Container/3CAF813F45.html | PLUGIN VERSION 0.20
14.10.2015 13:15:22 DEBUG     CRYPTER FilecryptCc[13]: LOAD URL https://www.filecrypt.cc/Container/3CAF813F45.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
14.10.2015 13:15:22 DEBUG     CRYPTER FilecryptCc[13]: Circle Captcha URL: https://www.filecrypt.cc/captcha/circle.php
14.10.2015 13:15:22 DEBUG     CAPTCHA FilecryptCc[13]: Captcha | LOAD URL https://www.filecrypt.cc/captcha/circle.php | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x17dcd18> | decode=False | multipart=False | post={} | ref=False | just_header=False
14.10.2015 13:15:22 ERROR     Decrypting failed: https://www.filecrypt.cc/Container/3CAF813F45.html | utf8
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/root/.pyload/userplugins/internal/Base.py", line 217, in preprocessing
    return self._process(*args, **kwargs)
  File "/root/.pyload/userplugins/internal/Base.py", line 212, in _process
    self.process(self.pyfile)
  File "/root/.pyload/userplugins/internal/Crypter.py", line 38, in process
    self.decrypt(pyfile)
  File "/root/.pyload/userplugins/crypter/FilecryptCc.py", line 56, in decrypt
    self.handle_captcha()
  File "/root/.pyload/userplugins/crypter/FilecryptCc.py", line 112, in handle_captcha
    input_type="png", output_type='positional')
  File "/root/.pyload/userplugins/internal/Captcha.py", line 54, in decrypt
    img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=decode, req=req or self.plugin.req)
  File "/root/.pyload/userplugins/internal/Plugin.py", line 532, in load
    f.write(encode(html))
  File "/root/.pyload/userplugins/internal/Plugin.py", line 67, in encode
    res = encode(decode(string, decoding), encoding)
  File "/root/.pyload/userplugins/internal/Plugin.py", line 44, in decode
    res = unicode(string, encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte
```
@GammaC0de 
it seems to be Plugin.py encoding/decoding issue
can u take a look at it ?
i'd really appreciate it!

**Comment by milanhlavin** [comment]
I have similar error

INFO	Download starts: nphv.rar
DEBUG	HOSTER UlozTo[3]: PROCESS URL http://www.ulozto.net/xZoznUZw/nphv-rar | PLUGIN VERSION 1.16
INFO	HOSTER UlozTo[3]: Updating file info...
DEBUG	HOSTER UlozTo[3]: File info: {'status': 2, 'pattern': {'S': u'3 MB', 'ID': 'xZoznUZw/nphv-rar', 'N': u'nphv.rar'}, 'size': 3000000.0, 'url': 'http://www.ulozto.net/xZoznUZw/nphv-rar', 'name': u'nphv.rar'}
DEBUG	HOSTER UlozTo[3]: Previous file info: {}
INFO	HOSTER UlozTo[3]: File name: nphv.rar
INFO	HOSTER UlozTo[3]: File size: 3000000 bytes
INFO	HOSTER UlozTo[3]: File status: spoustim
DEBUG	HOSTER UlozTo[3]: LOAD URL http://www.ulozto.net/xZoznUZw/nphv-rar | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={} | ref=False | multipart=False
INFO	HOSTER UlozTo[3]: Processing as free download...
DEBUG	HOSTER UlozTo[3]: inputs.keys = [u'do', u'hash', u'cid', u'timestamp', u'ts', u'freeDownload', u'sign', u'_token_', u'captcha_value', u'captcha_type', u'salt', u'sign_a', u'adi']
DEBUG	HOSTER UlozTo[3]: Using "new" version
DEBUG	HOSTER UlozTo[3]: LOAD URL http://www.ulozto.net/reloadXapca.php | redirect=True | decode=True | cookies=True | get={'rnd': '1444969213'} | req=None | just_header=False | post={} | ref=True | multipart=False
DEBUG	HOSTER UlozTo[3]: xapca = {"image":"http:\/\/xapca6.uloz.to\/1677996dd6042052312761166c70daf003d76b12\/image.gif","sound":"http:\/\/xapca6.uloz.to\/1677996dd6042052312761166c70daf003d76b12\/sound.wav","hash":"1677996dd6042052312761166c70daf003d76b12","timestamp":1444969206,"salt":1648}
DEBUG	CAPTCHA UlozTo[3]: Captcha | LOAD URL http://xapca6.uloz.to/1677996dd6042052312761166c70daf003d76b12/image.gif | redirect=True | decode=False | cookies=True | get={} | req= | just_header=False | post={} | ref=False | multipart=False
WARNING	Download failed: nphv.rar | 'utf8' codec can't decode byte 0xaf in position 6: unexpected code byte
INFO	Debug Report written to debug_UlozTo_16-10-2015_06-20-13.zip



TRACEBACK:
 Traceback (most recent call last):
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Base.py", line 217, in preprocessing
    return self._process(*args, **kwargs)
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Hoster.py", line 87, in _process
    self.process(self.pyfile)
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/SimpleHoster.py", line 286, in process
    self.handle_free(pyfile)
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/hoster/UlozTo.py", line 76, in handle_free
    captcha_value = self.captcha.decrypt(str(data['image']))
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Captcha.py", line 54, in decrypt
    img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=decode, req=req or self.plugin.req)
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Plugin.py", line 533, in load
    f.write(encode(html))
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Plugin.py", line 67, in encode
    res = encode(decode(string, decoding), encoding)
  File "/mnt/HD/HD_a2/ffp/tmp/pyload/.pyload/userplugins/internal/Plugin.py", line 44, in decode
    res = unicode(string, encoding or "utf-8")
  File "/opt/lib/python2.5/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xaf in position 6: unexpected code byte

**Comment by vuolter** [comment]
The fix is coming...

**Comment by Gutz-Pilz** [comment]
:+1:

**Comment by Gutz-Pilz** [comment]
is the fix coming in today ?
if not, i would revert to my backup :)

**Comment by mcmaxl** [comment]
Would be greatly appreciated!

**Comment by Bambie42** [comment]
For me this issue still exists :(

**Comment by Gutz-Pilz** [comment]
i  an confirm.
still persists
```
19.10.2015 08:38:40 INFO      Decrypting starts: https://www.filecrypt.cc/Container/3CAF813F45.html
19.10.2015 08:38:40 DEBUG     CRYPTER FilecryptCc[13]: Plugin version: 0.21
19.10.2015 08:38:40 DEBUG     CRYPTER FilecryptCc[13]: Plugin status: testing
19.10.2015 08:38:40 WARNING   CRYPTER FilecryptCc[13]: Plugin may be unstable
19.10.2015 08:38:40 DEBUG     CRYPTER FilecryptCc[13]: Config option `use_premium` not found, use default `True`
19.10.2015 08:38:40 INFO      CRYPTER FilecryptCc[13]: Grabbing link info...
19.10.2015 08:38:40 DEBUG     CRYPTER FilecryptCc[13]: Link info: {'status': 3, 'pattern': {}, 'size': 0, 'url': u'https://www.filecrypt.cc/Container/3CAF813F45.html', 'name': '3CAF813F45.html'}
19.10.2015 08:38:40 DEBUG     CRYPTER FilecryptCc[13]: Previous link info: {}
19.10.2015 08:38:40 INFO      CRYPTER FilecryptCc[13]: Link name: 3CAF813F45.html
19.10.2015 08:38:40 INFO      CRYPTER FilecryptCc[13]: Link size: N/D
19.10.2015 08:38:40 INFO      CRYPTER FilecryptCc[13]: Link status: eingereiht
19.10.2015 08:38:40 INFO      CRYPTER FilecryptCc[13]: Processing url: https://www.filecrypt.cc/Container/3CAF813F45.html
19.10.2015 08:38:40 DEBUG     CRYPTER FilecryptCc[13]: LOAD URL https://www.filecrypt.cc/Container/3CAF813F45.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
19.10.2015 08:38:40 DEBUG     CRYPTER FilecryptCc[13]: Circle Captcha URL: https://www.filecrypt.cc/captcha/circle.php
19.10.2015 08:38:40 DEBUG     CAPTCHA FilecryptCc[13]: Captcha | LOAD URL https://www.filecrypt.cc/captcha/circle.php | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x1f02148> | decode=False | multipart=False | post={} | ref=False | just_header=False
19.10.2015 08:38:40 ERROR     Decrypting failed: 3CAF813F45.html | utf8
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/root/.pyload/userplugins/internal/Base.py", line 288, in preprocessing
    return self._process(*args, **kwargs)
  File "/root/.pyload/userplugins/internal/Base.py", line 282, in _process
    self.process(self.pyfile)
  File "/root/.pyload/userplugins/internal/Crypter.py", line 38, in process
    self.decrypt(pyfile)
  File "/root/.pyload/userplugins/crypter/FilecryptCc.py", line 57, in decrypt
    self.handle_captcha()
  File "/root/.pyload/userplugins/crypter/FilecryptCc.py", line 113, in handle_captcha
    input_type="png", output_type='positional')
  File "/root/.pyload/userplugins/internal/Captcha.py", line 53, in decrypt
    img = self.load(url, get=get, post=post, ref=ref, cookies=cookies, decode=decode, req=req or self.plugin.req)
  File "/root/.pyload/userplugins/internal/Plugin.py", line 267, in load
    f.write(encode(html))
  File "/root/.pyload/userplugins/internal/utils.py", line 187, in encode
    res = encode(decode(value, decoding), encoding)
  File "/root/.pyload/userplugins/internal/utils.py", line 168, in decode
    res = unicode(value, encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by mcmaxl** [comment]
same here

**Comment by kasperj** [comment]
Still existing for a couple of crypters, hosters

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyload/commit/477046e0b1bb37e294db6ceab68462c0fc797ea7
^^this fixes it for me

**Comment by mcmaxl** [comment]
@Gutz-Pilz thx!!!!!!!

**Comment by joberreiter** [comment]
I would try to abandon the custom functions `decode()` and `encode()` both and switch to `unicode.encode()` and `unicode.decode()`.
Both former functions are only wrapper for the latter ones and introducing more unicode problems by unneccessary de-/encoding operations.

**Comment by mcmaxl** [comment]
and now Extract Archive doesn't do anything after package is downloaded....

**Comment by joberreiter** [comment]
@mcmaxl If there is no error in the log: Try to start PyLoad from the command line, is there any traceback shown when Extract Archive runs?

**Comment by mcmaxl** [comment]
@joberreiter 

19.10.2015 15:23:56 INFO      ADDON ExtractArchive: Check package: originalsHD302
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/opt/pyload-stable/module/PluginThread.py", line 459, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/pyload-config/userplugins/hooks/ExtractArchive.py", line 185, in extract_queued
    if self.extract(packages, thread):  #@NOTE: check only if all gone fine, no failed reporting for now
  File "/opt/pyload-config/userplugins/hooks/ExtractArchive.py", line 292, in extract
    targets = Extractor.get_targets(files_ids)
  File "/opt/pyload-config/userplugins/internal/Extractor.py", line 78, in get_targets
    pname = re.sub(cls.re_multipart, "", fname) if cls.ismultipart(fname) else os.path.splitext(fname)[0]
AttributeError: type object 'UnRar' has no attribute 'ismultipart'

**Comment by Gutz-Pilz** [comment]
same here !
but this was already before my change in utils.py

**Comment by mcmaxl** [comment]
oh, didn't want to imply that. It probably came with voulters latest changes which I updated this morning. Had been running the version from 3 or 4 days ago without that problem

**Comment by joberreiter** [comment]
See #2060 for AttributeError: type object 'UnRar' has no attribute 'ismultipart'

**Comment by Gutz-Pilz** [comment]
https://github.com/pyload/pyload/pull/2063

**Comment by mcmaxl** [comment]
thx again @Gutz-Pilz
