### ISSUE TITLE
Cloudsix host

### ISSUE THREAD

**Issue by davboc** [pyload/pyload#2027]
There is no way to add Cloudsix host in pyload?

Thanks

**Comment by davboc** [comment]
110	19.10.2015 00:41:36	WARNING	Download failed: filename.part2.rev | invalid arguments to setopt
109	19.10.2015 00:41:36	WARNING	HOSTER XFileSharingPro: CloudsixMe[392]: Plugin may be unstable

**Comment by davboc** [comment]
267	19.10.2015 12:43:15	WARNING	Download failed: filename.part3.rev | 'NoneType' object has no attribute 'HOSTER_DOMAIN'
266	19.10.2015 12:43:15	WARNING	HOSTER XFileSharingPro: CloudsixMe[394]: Plugin may be unstable

**Comment by vuolter** [comment]
@davboc XFileSharingPro was replaced by XFileSharing

**Comment by davboc** [comment]
@vuolter yes but there is the same problem for easybytez https://github.com/pyload/pyload/issues/2073#issuecomment-149471917
