### ISSUE TITLE
debriditalia not kicking in

### ISSUE THREAD

**Issue by gumsh** [pyload/pyload#2030]
debriditalia multihoster plugin does noet kick in when starting a download from ul.com / rapidgator.

**Comment by hannsen** [comment]
configure it

Hoster list (comma separated):

**Comment by gumsh** [comment]
there is no "hoster List" in the Plugin config.

**Comment by hannsen** [comment]
DebridItaliaCom - "DebridItaliaCom":
        str mh_list : "Hoster list (comma separated)" =
        all;listed;unlisted mh_mode : "Filter hosters to use" = all
        int mh_interval : "Reload interval in minutes" = 60

**Comment by chaosmaker** [comment]
As far as I understand none of the multihoster plugins are working... They are implementing a new multihoster plugin directly and it is not finished yet... I'm quite annoyed as the whole point of having a git stable version is to have a version of pyload that f***** works - this way all the testing is done on the stable version and it just doesn't work.... the only thing you can do is pull an earlier version from git where it did work and disable updates...

**Comment by gumsh** [comment]
![screenshot 2015-10-15 21 04 11](https://cloud.githubusercontent.com/assets/12197640/10524522/5dc6e00c-7380-11e5-9d1c-6919ec3efc18.png)

**Comment by gumsh** [comment]
i don't know if i have the current version i did a fresh install and then downloaded the download manager from 
https://raw.githubusercontent.com/pyload/pyload/stable/module/plugins/hooks/UpdateManager.py

**Comment by hannsen** [comment]
Try https://github.com/pyload/pyload/archive/stable.zip

I use this, but I dont have your debrid service to test. Maybe new versions dont work as chaosmaker said

**Comment by damien599901** [comment]
any news?  still KO

**Comment by ddbxx** [comment]
Here is my work around. The 3 changed spots are marked with my username

MultiAccount.py from userplugins/internal
DebridItaliaCom.py from userplugins/accounts

the 2 files you can find in my dropbox share:

https://www.dropbox.com/sh/ucpsbe01bpajpy7/AADQ0evYrQxIHIFxgCid9Sgla?dl=0

**Comment by gumsh** [comment]
i tried a full reinstall and used the two workaround files still no luck with debriditalia on different Hosters..

**Comment by VirusAlertX** [comment]
Hi, i've got the same problem. After a fresh install of stable version of pyload, Debriditalia plugin doesn't hook other hosters links, like TusFiles.net. I tried the 2 files by ddbxx but nothing changes. Thank you

**Comment by GammaC0de** [comment]
@VirusAlertX Can you check now?

**Comment by VirusAlertX** [comment]
I'm trying but nothing changed, it tells "Required account not found" but it is set and valid (green in PyLoad), or "Plugin is temporarily unavailable", or "temp. offline" but the file is online.

**Comment by GammaC0de** [comment]
Ok, account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
No response, closing (continuing in #2718)
