### ISSUE TITLE
How to change the owner of downloaded files?

### ISSUE THREAD

**Issue by pahofmann** [pyload/pyload#2031]
All the needed settings are in the config, but they would only work if I run pyload as root.
Is there a way to make pyload use sudo for the chown?
Then I could just add a NOPASSWD: chown in the sudoers file.

**Comment by runningbits** [comment]
Would you mind to explain a bit more what you are trying to achieve? If you run into permission issues usually your setup is wrong. I recommend running pyload as the user who should own the downloaded files in the end. If you need to access these files from a different account I recommend using unix groups/acls to provide access for that account.
(Please note that I don't claim any authority on how to setup pyload, this is just from my personal Linux experience.)

**Comment by pahofmann** [comment]
Pyload runs as his own user (pyload), setting permissons works fine.  
However, the settings also offer an option to change the owner/group of the downloaded files.  
But this will only work if you run pyload as root, because only root can change the owner/group of a file.  
Running pyload as root is not an option, so it would be nice if pyload would execute the user/group change with sudo. 
Simple solution, I just cant find where the `chown` is executed so I can add the `sudo`.
If I would use ACLs,  pyload could not execute scripts on the downlaoded files because they already belong to another user.

**Comment by joberreiter** [comment]
I agree with runningbits ... this is primarily a design problem of your installation.

> Simple solution, I just cant find where the chown is executed so I can add the sudo.

chown is executed via os.chown() in internal/Plugin.py, line 108ff `set_permissions()`

**Comment by pahofmann** [comment]
I agree, the sudoers entry is not the best solution, but at least privileges of the pyload user are contained to `chown`. 
The problem for me is that I do not want to run pyload as root or the user who should own the files at the end.
I'm just curious why there are parameters in the settings that allow for changing owner/group of the files, when the only way to use these is running pyload as root.
Or am I missing something and there is a way to allow the change of owner/group via permission settings? I thought only root could change the owner.

**Comment by vuolter** [comment]
![img8976](https://cloud.githubusercontent.com/assets/1221092/10594514/326aa6b8-76ce-11e5-8bc8-9d6108125310.png)

**Comment by pahofmann** [comment]
Yes these are the Settings I talk about..
But how does that answer my questions in the comment above?

**Comment by joberreiter** [comment]
> My problem is that I do not want to run pyload as root or the user who should own the files at the end.

This is ok, nothing to say against it. But why cant you give permissions to the 'other users' to access the downloaded files that the 'user pyload' owns (by setting the group permissions of the download directory correct and adding the users to the corresponding group)?
Another solution would be the use of the external scripts, I assume.
Or a cron job running as root, setting the right permissions and/or moving the files to the right places.
Or ... whatever.

> I'm just curious why there are parameters in the settings that allow for changing owner/group of the files, when the only way to use these is running pyload as root.

Perhaps just for not having the downloaded files owned by root, when running pyload as root?
I can't answer this.

> Or am I missing something and there is a way to allow the change of owner/group via permission settings? I thought only root could change the owner.

This is also my understanding of it, yes. Therefore runningbits and I showed you some alternate ways to solve it if you run pyload as non-root ...

**Comment by pahofmann** [comment]
I just wanted to make sure there is no other way to do this with pyload only.  
I'm going to use a custom script then.
