### ISSUE TITLE
[ExtractArchive] not using saved passwords from text file

### ISSUE THREAD

**Issue by mcmaxl** [pyload/pyload#2033]
this is log showing not using password file (as necessary password is definitely saved inside the file, path is also set correctly)

second issue is that Extract Archive is not saving the "move to trash" setting as false

149	15.10.2015 11:08:52	INFO	Download finished: Arrow.S04E02.720p.HDTV.x-DIMENSION.part7.rar
150	15.10.2015 11:08:52	INFO	Package finished: Arrow S04E02 720p HDTV x-DIMENSION
151	15.10.2015 11:08:52	INFO	HOOK ExtractArchive: Check package: Arrow S04E02 720p HDTV x-DIMENSION
152	15.10.2015 11:08:52	INFO	HOOK ExtractArchive: Arrow.S04E02.720p.HDTV.x-DIMENSION.part3.rar | Extract to: /volume1/pyload_downloads/Arrow S04E02 720p HDTV x-DIMENSION/
153	15.10.2015 11:10:53	INFO	HOSTER UploadedTo[290]: Checking downloaded file...
154	15.10.2015 11:10:53	INFO	HOSTER UploadedTo[290]: No errors found
155	15.10.2015 11:10:53	INFO	Download finished: NvyHD.1304.part2.rar
156	15.10.2015 11:11:06	INFO	HOSTER UploadedTo[289]: Checking downloaded file...
157	15.10.2015 11:11:06	INFO	HOSTER UploadedTo[289]: No errors found
158	15.10.2015 11:11:07	INFO	Download finished: NvyHD.1304.part1.rar
159	15.10.2015 11:11:07	INFO	Package finished: NvyHD 1304
160	15.10.2015 11:11:37	ERROR	HOOK ExtractArchive: Arrow.S04E02.720p.HDTV.x-DIMENSION.part3.rar | No password found
161	15.10.2015 11:11:37	ERROR	HOOK ExtractArchive: Arrow.S04E02.720p.HDTV.x-DIMENSION.part3.rar | Extract failed

**Comment by mcmaxl** [comment]
looks like its working with upgraded unrar in debian

**Comment by Gutz-Pilz** [comment]
please close :)
