### ISSUE TITLE
uploaded.to hoster problems (premium/baseplugin)

### ISSUE THREAD

**Issue by die2gether** [pyload/pyload#2035]
the uploaded hoster hasnt been working on my rpi2 for the at least the last 2 weeks so i tried reinstalling today, but it didnt solve the issues.
im not quite sure wether the hoster should be fixed by now or not, but i noticed that a few issues about it are in the closed section.

mind that in the log it states premium: False (even though it should be) and the plugin used is the baseplugin (should be uploadedto i assume)

_______________________________________________________________________________

LOG:

15.10.2015 19:28:49	INFO	Starting pyLoad 0.4.9
192	15.10.2015 19:28:49	INFO	Using home directory: /root/.pyload
193	15.10.2015 19:28:49	DEBUG	Remote activated: True
194	15.10.2015 19:28:50	DEBUG	created index of plugins
195	15.10.2015 19:28:50	INFO	ExtractArchive: Activated UnRar UnZip
196	15.10.2015 19:28:50	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
197	15.10.2015 19:28:50	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
198	15.10.2015 19:28:50	INFO	Downloadtime: True
199	15.10.2015 19:28:50	INFO	Starting ThriftBackend: 0.0.0.0:7227
200	15.10.2015 19:28:51	INFO	Starting threaded webserver: 192.168.0.10:8000
201	15.10.2015 19:28:51	INFO	Free space: 4.89 GiB
202	15.10.2015 19:28:51	INFO	Activating Accounts...
203	15.10.2015 19:29:07	DEBUG	UploadedTo: Get Account Info for 8918867
204	15.10.2015 19:29:13	DEBUG	UploadedTo: Account Info: {'validuntil': -1, 'premium': False}
205	15.10.2015 19:29:13	INFO	Activating Plugins...
206	15.10.2015 19:29:13	INFO	pyLoad is up and running
207	15.10.2015 19:29:15	INFO	Download starts: the100_0201.rar
208	15.10.2015 19:29:16	DEBUG	BasePlugin: Filename: the100_0201.rar
209	15.10.2015 19:29:16	INFO	Download finished: the100_0201.rar
210	15.10.2015 19:29:17	WARNING	Not able to connect server for updates
211	15.10.2015 19:29:17	INFO	No Updates for pyLoad
212	15.10.2015 19:29:17	INFO	Download starts: the100_0202.rar
213	15.10.2015 19:29:17	DEBUG	BasePlugin: Filename: the100_0202.rar
214	15.10.2015 19:29:18	WARNING	Not able to connect server for updates
215	15.10.2015 19:29:18	INFO	No plugin updates available
216	15.10.2015 19:29:19	INFO	Download starts: the100_0203.rar
217	15.10.2015 19:29:25	DEBUG	BasePlugin: Filename: the100_0203.rar
218	15.10.2015 19:29:25	INFO	Download finished: the100_0203.rar
219	15.10.2015 19:29:27	INFO	Download starts: the100_0204.rar
220	15.10.2015 19:29:27	DEBUG	BasePlugin: Filename: the100_0204.rar
221	15.10.2015 19:29:28	INFO	Download finished: the100_0202.rar
222	15.10.2015 19:29:28	INFO	Download finished: the100_0204.rar
223	15.10.2015 19:29:29	INFO	Download starts: the100_0205.rar
224	15.10.2015 19:29:29	DEBUG	BasePlugin: Filename: the100_0205.rar
225	15.10.2015 19:29:30	INFO	Download finished: the100_0205.rar
226	15.10.2015 19:29:30	INFO	Package finished: The 100 S02 SD
227	15.10.2015 19:29:30	INFO	ExtractArchive: Package The 100 S02 SD queued for later extracting
228	15.10.2015 19:29:30	DEBUG	All downloads processed
229	15.10.2015 19:29:30	INFO	ExtractArchive: Check package The 100 S02 SD
230	15.10.2015 19:29:30	DEBUG	ExtractArchive: Targets for UnRar: [('Downloads/The 100 S02 SD/the100_0201.rar', 18), ('Downloads/The 100 S02 SD/the100_0202.rar', 19), ('Downloads/The 100 S02 SD/the100_0203.rar', 20), ('Downloads/The 100 S02 SD/the100_0204.rar', 21), ('Downloads/The 100 S02 SD/the100_0205.rar', 22)]
231	15.10.2015 19:29:30	DEBUG	All downloads finished
232	15.10.2015 19:29:30	INFO	ExtractArchive: the100_0201.rar | Extract to Downloads/The 100 S02 SD/
233	15.10.2015 19:29:30	DEBUG	ExtractArchive: unrar l -o+ -y -p- -v Downloads/The 100 S02 SD/the100_0201.rar
234	15.10.2015 19:29:30	DEBUG	ExtractArchive: unrar vb -o+ -y -p- -v Downloads/The 100 S02 SD/the100_0201.rar
235	15.10.2015 19:29:30	ERROR	ExtractArchive: the100_0201.rar | Archive Error | Empty Archive
236	15.10.2015 19:29:30	DEBUG	ExtractArchive: Extracted: []
237	15.10.2015 19:29:30	INFO	ExtractArchive: the100_0202.rar | Extract to Downloads/The 100 S02 SD/
238	15.10.2015 19:29:30	DEBUG	ExtractArchive: unrar l -o+ -y -p- -v Downloads/The 100 S02 SD/the100_0202.rar
239	15.10.2015 19:29:30	DEBUG	ExtractArchive: unrar vb -o+ -y -p- -v Downloads/The 100 S02 SD/the100_0202.rar
240	15.10.2015 19:29:30	ERROR	ExtractArchive: the100_0202.rar | Archive Error | Empty Archive
241	15.10.2015 19:29:30	DEBUG	ExtractArchive: Extracted: []
242	15.10.2015 19:29:30	INFO	ExtractArchive: the100_0203.rar | Extract to Downloads/The 100 S02 SD/
243	15.10.2015 19:29:30	DEBUG	ExtractArchive: unrar l -o+ -y -p- -v Downloads/The 100 S02 SD/the100_0203.rar
244	15.10.2015 19:29:30	DEBUG	ExtractArchive: unrar vb -o+ -y -p- -v Downloads/The 100 S02 SD/the100_0203.rar
245	15.10.2015 19:29:30	ERROR	ExtractArchive: the100_0203.rar | Archive Error | Empty Archive
246	15.10.2015 19:29:30	DEBUG	ExtractArchive: Extracted: []
247	15.10.2015 19:29:30	INFO	ExtractArchive: the100_0204.rar | Extract to Downloads/The 100 S02 SD/
248	15.10.2015 19:29:30	DEBUG	ExtractArchive: unrar l -o+ -y -p- -v Downloads/The 100 S02 SD/the100_0204.rar
249	15.10.2015 19:29:30	DEBUG	ExtractArchive: unrar vb -o+ -y -p- -v Downloads/The 100 S02 SD/the100_0204.rar
250	15.10.2015 19:29:30	ERROR	ExtractArchive: the100_0204.rar | Archive Error | Empty Archive
251	15.10.2015 19:29:30	DEBUG	ExtractArchive: Extracted: []
252	15.10.2015 19:29:30	INFO	ExtractArchive: the100_0205.rar | Extract to Downloads/The 100 S02 SD/
253	15.10.2015 19:29:30	DEBUG	ExtractArchive: unrar l -o+ -y -p- -v Downloads/The 100 S02 SD/the100_0205.rar
254	15.10.2015 19:29:30	DEBUG	ExtractArchive: unrar vb -o+ -y -p- -v Downloads/The 100 S02 SD/the100_0205.rar
255	15.10.2015 19:29:30	ERROR	ExtractArchive: the100_0205.rar | Archive Error | Empty Archive
256	15.10.2015 19:29:30	DEBUG	ExtractArchive: Extracted: []
257	15.10.2015 19:29:30	DEBUG	All downloads finished

**Comment by joberreiter** [comment]
Maybe it is the result from a combination of two issues,
- wrong password submitted (fix #2041 has already be merged)
- issue #2060 ('UnRar' has no 'ismultipart')

**Comment by vuolter** [comment]
@die2gether Retry and let me know if works now. ;)

**Comment by die2gether** [comment]
sorry for the delayed feedback, but it appears to be working now
