### ISSUE TITLE
Tusfiles simultaneous download limit 

### ISSUE THREAD

**Issue by davboc** [pyload/pyload#2037]
How I can set simultaneous download limit to 2 instead of 3 for this host? I see that it can't download more than 2 files concurrently

**Comment by vuolter** [comment]
Fixing...

**Comment by davboc** [comment]
however, tusfiles doesn't work well... Sometimes it loops in an error like this:

948	16.10.2015 22:53:27	INFO	HOSTER TusfilesNet[651]: File name: mm.part21.rar
947	16.10.2015 22:53:25	INFO	HOSTER TusfilesNet[651]: Updating file info...
946	16.10.2015 22:53:23	INFO	Download starts: mmm.part21.rar
945	16.10.2015 22:53:23	INFO	Download restarted: mm.rar | Download limit exceeded
944	16.10.2015 22:53:21	INFO	HOSTER TusfilesNet[652]: Waiting 9 seconds...
943	16.10.2015 22:53:21	WARNING	HOSTER TusfilesNet[652]: You have to wait 9 seconds till next download
942	16.10.2015 22:53:21	INFO	HOSTER TusfilesNet[652]: Processing as free download...
941	16.10.2015 22:53:19	INFO	HOSTER TusfilesNet[652]: File status: avviando
940	16.10.2015 22:53:19	INFO	HOSTER TusfilesNet[652]: File size: 105906176 bytes
939	16.10.2015 22:53:19	INFO	HOSTER TusfilesNet[652]: File name: mmm.part22.rar
938	16.10.2015 22:53:17	INFO	HOSTER TusfilesNet[652]: Updating file info...
937	16.10.2015 22:53:15	INFO	Download starts: mmm.part22.rar 

And so on... 


but I don't think that this is an error server-side because if I manually stop this download, pyload starts to download another file from tusfiles correctly.

**Comment by vuolter** [comment]
@davboc Open a new ticket for the last issue.
P.S.: Reconnect is working fine now?

**Comment by davboc** [comment]
The loop issue seems solved now, I don't know how. 

Reconnect has the same problem: after reconnect doesn't restart automatically the file. Now I use a workaround by editing the reconnect.sh script, I have not had time to provide a full debug log.

Thanks for all vuolter!
