### ISSUE TITLE
Pyload doesn't start on DSM6 (64bits)

### ISSUE THREAD

**Issue by sousouille** [pyload/pyload#2042]
Hi,

I have upgraded my Synology NAS in DSM 6.0 beta. Now the app pyload doesn't start. No log are generated.
Anyone is encountering the same issue (i see one man on deutch syno's forum)?
Anyone can help me to solve the issue?

Thx in advance.

Alex

**Comment by joberreiter** [comment]
I don't know Synology, but what is the output if you start it directly from the command line?
Which python version do you run?

**Comment by sousouille** [comment]
Hi,

Python 2.7 is include in the package. Python is installed too. When I start manually, nothing...

**Comment by joberreiter** [comment]
Are there any entries in syslog, kernel log, user log?
Is Python itself functioning, can you run other python scripts?

Without any error or debug message, what should we do?

**Comment by syss** [comment]
Does pyload have enough rights to write logs?

**Comment by sousouille** [comment]
Hi,

Thx for the help. With your last msg, I realize that the pyload user was disabled. So it can't write log and can't start too.

Thx to you.
