### ISSUE TITLE
uploaded.to - Fallback to free processing

### ISSUE THREAD

**Issue by solariz** [pyload/pyload#2050]
Since several days I can't run any uploaded.to downloads anymore.

    HOSTER UploadedTo[377]: Premium download failed | Parse error: Premium download link not found | Plugin may be out of date
    INFO      Download restarted: test.img | Fallback to free processing

Log:  http://kopy.io/E6tl5#h2E2knJ8W1J0N4

Full Premium Page Download HTML:
http://kopy.io/PSwHD#A3dft9aJR8Zvdv

**Comment by maikyyy** [comment]
i think it is .../plugins/accounts/UploadedTo.py related. Account Information "Premium" is not read correctly. Read out date is always the current day.

**Comment by maikyyy** [comment]
The fault lay with me from one week to four days premium time.

now with 3 day left all is running fine with old pyload 0.4.9

**Comment by vuolter** [comment]
@maikyyy What version are you using?

**Comment by maikyyy** [comment]
now 0.4.9 but the problem was the same till yesterday with newer version. premium ends today and downloads be as free processed. today with "Duration: 3 days and 20 hours" all works fine again.

**Comment by syss** [comment]
seems to work now

**Comment by solariz** [comment]
Confirmed, working with days left > 100 too.
