### ISSUE TITLE
[HTTP] 404 will NOT raise a BadHeader exception 

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2051]
Regarding [Http.py#L45](https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/Http.py#L45):
```python
            try:
                self.download(link, ref=False, disposition=True)

            except BadHeader, e:
                if e.code in (404, 410):
                    self.offline()
```

As stated in [HTTPRequest.py#L221](https://github.com/pyload/pyload/blob/stable/module/network/HTTPRequest.py#L221), Please note that 404 will NOT raise a `BadHeader` exception

**Comment by vuolter** [comment]
Mmhnn, but `bad_headers = range(400, 404) + range(405, 418) + range(500, 506)`...

**Comment by GammaC0de** [comment]
```python
>>> range(400, 404)
[400, 401, 402, 403]
```

also in [Hoster.py#L230](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Hoster.py#L230), [SimpleCrypter.py#L106](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/SimpleCrypter.py#L106), [SimpleHoster.py#L153](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/SimpleHoster.py#L153)

**Comment by GammaC0de** [comment]
Regarding https://github.com/pyload/pyload/commit/ffd38f027ed103f7b39ec78c6af0d182774950a4 and `BadHeader`:

These codes **would** trigger a `BadHeader`:
`[400, 401, 402, 403, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 500, 501, 502, 503, 504, 505]`
but 404 **would not**.

so  https://github.com/pyload/pyload/commit/ffd38f027ed103f7b39ec78c6af0d182774950a4 is not  a proper fix

**Comment by vuolter** [comment]
Okay... I understood with an embarrassing delay. XD
