### ISSUE TITLE
Windows unrar.exe unzip

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#2060]
Hy, i test pyload now under Windows and want extract some files. But pyload says
" 19.10.2015 12:24:41	DEBUG	ADDON ExtractArchive: Found UnRar 3.91 | Found UnZip 2.7.1"
And i have the newest 7-zip and downloaded the newest unrar.exe file. Must i change something in pyload?

**Comment by Mister-XY** [comment]
Ok, i have found the error. In Pyload\dist is an very old unrar.exe file.

**Comment by joberreiter** [comment]
And it doesn't work, or what is the point here?

**Comment by Mister-XY** [comment]
Yes, it doesn't work

**Comment by Mister-XY** [comment]
Ah look, an error.
![pyload error](https://cloud.githubusercontent.com/assets/10309056/10576777/30990004-7666-11e5-9ad2-578a3fd6e375.png)

**Comment by joberreiter** [comment]
Come on, don't post screenshots, post the full log.

**Comment by Mister-XY** [comment]
There is no error in the log, Thats is the Problem, that is the reason why i post the screenshot.

**Comment by joberreiter** [comment]
For future issues: [How to copy text from a dos prompt](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/windows_dos_copy.mspx?mfr=true)

Attribute Error : type object 'UnRar' has no attribute 'ismultipart'

@Vuolter has changed Extractor.py recently, what are your version of `internal/Extractor.py` and `internal\UnRar.py`?

**Comment by Mister-XY** [comment]
Ok thanks
The extractor version is 0.37 and the unrar.py is 1.28

**Comment by joberreiter** [comment]
Ok, you have the latest versions, we have to wait what vuolter has to say about it.

**Comment by Gutz-Pilz** [comment]
https://github.com/pyload/pyload/pull/2063
this may fix also this problem :)

**Comment by joberreiter** [comment]
But in `internal/UnRar.py` is states
```
    @classmethod
    def ismultipart(cls, filename):
        return True if cls.re_multipart.search(filename) else False
```
?

**Comment by vuolter** [comment]
I prefer `ismultipart`, it looks like `isinstance` for me. XD
But if you want the underscore I have no problem to replacing it everywhere. :p

**Comment by Mister-XY** [comment]
The error is always there.

**Comment by Gutz-Pilz** [comment]
If i do it without underscore it errors.

Sincerly
your lovely NAS

**Comment by Gutz-Pilz** [comment]
I ment.
When using it with underscore it doesnt work.

**Comment by Gutz-Pilz** [comment]
@Mister-XY 
did u make the changes suggested ?

**Comment by Mister-XY** [comment]
I have change the ismultipart in unrar.py and i want to test it.

**Comment by Gutz-Pilz** [comment]
okay. 
https://github.com/Gutz-Pilz/pyload/commit/b21a54ed5049cd34dceb63bcb3dffe3d286aac24
^^ dont forget the imporet in line8

**Comment by Mister-XY** [comment]
Ok, i have tested it with your Extractor.py. the problem ist  definition from Multipart
in extractor is called cls.is_multipart
and in unrar is called ismultipart.
After i change the line to the same (ismultipart oris_multipart) is extract. But after the extraction, i get an new error.

**Comment by Gutz-Pilz** [comment]
damn windows ;)

**Comment by Mister-XY** [comment]
It's look like good.
