### ISSUE TITLE
Security issue when displaying debug logs

### ISSUE THREAD

**Issue by joberreiter** [pyload/pyload#2061]
With the latest commit b0ddd95c9697c2df7a9cf26398406fb57d2c5059, the user account passwords are now displayed unmasked in the logs.

As this is ok for local debugging purposes, it is worse in terms of security, as the log had to be edited to prevent revealing the account credentials to the world.

Is this an intended change?
Although not very beautiful at coding, there was a good reason for password masking in the past ...

**Comment by GammaC0de** [comment]
@joberreiter Just a note: this masking was not very effective since every HTTP request, including the arguments, is logged in debug mode..
[Hoster.py#L176](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Hoster.py#L176), [Plugin.py#L217](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Plugin.py#L217)
```python
    def load(self, url, get={}, post={}, ref=True, cookies=True, just_header=False, decode=True,
             multipart=False, redirect=True, req=None):
        """
        Load content at url and returns it

        :param url:
        :param get:
        :param post:
        :param ref:
        :param cookies:
        :param just_header: If True only the header will be retrieved and returned as dict
        :param decode: Wether to decode the output according to http header, should be True in most cases
        :return: Loaded content
        """
        if self.pyload.debug:
            self.log_debug("LOAD URL " + url,
                           *["%s=%s" % (key, val) for key, val in locals().items() if key not in ("self", "url", "_[1]")])

```

**Comment by vuolter** [comment]
@GammaC0de has already exposed the reason that led me to remove the password masking.
