### ISSUE TITLE
ExtractArchive // global name 'encode' is not defined

### ISSUE THREAD

**Issue by Leonderi** [pyload/pyload#2072]
For me now ExtractArchive doesnt work anymore..

137	19.10.2015 17:42:13	DEBUG	ADDON ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
138	19.10.2015 17:42:14	DEBUG	All downloads processed
139	19.10.2015 17:42:14	INFO	ADDON ExtractArchive: Check package: izombie s01e11
140	19.10.2015 17:42:14	DEBUG	All downloads finished
141	19.10.2015 17:42:14	DEBUG	ADDON ExtractArchive: Targets for UnRar: [('/mnt/media/Downloads/tmp/pyload/izombie s01e11/wishtv-izombie-s01e11-720p.part1.rar', 5151, '/mnt/media/Downloads/_Pyload_/izombie s01e11')]
142	19.10.2015 17:42:14	INFO	ADDON ExtractArchive: wishtv-izombie-s01e11-720p.part1.rar | Extract to: /mnt/media/Downloads/_Pyload_/izombie s01e11
143	19.10.2015 17:42:14	DEBUG	ADDON ExtractArchive: Password: None provided
144	19.10.2015 17:42:14	ERROR	ADDON ExtractArchive: wishtv-izombie-s01e11-720p.part1.rar | Unknown error | global name 'encode' is not defined
145	19.10.2015 17:42:14	DEBUG	All downloads finished
146	19.10.2015 17:42:14	ERROR	ADDON ExtractArchive: wishtv-izombie-s01e11-720p.part1.rar | Extract failed
147	19.10.2015 17:42:14	DEBUG	ADDON ExtractArchive: Targets for SevenZip: [('/mnt/media/Downloads/tmp/pyload/izombie s01e11/wishtv-izombie-s01e11-720p.part1.rar', 5151, '/mnt/media/Downloads/_Pyload_/izombie s01e11')]
148	19.10.2015 17:42:14	INFO	ADDON ExtractArchive: wishtv-izombie-s01e11-720p.part1.rar | Extract to: /mnt/media/Downloads/_Pyload_/izombie s01e11
149	19.10.2015 17:42:14	DEBUG	ADDON ExtractArchive: Password: None provided
150	19.10.2015 17:42:14	ERROR	ADDON ExtractArchive: wishtv-izombie-s01e11-720p.part1.rar | Unknown error | global name 'encode' is not defined
151	19.10.2015 17:42:14	DEBUG	All downloads finished
152	19.10.2015 17:42:14	ERROR	ADDON ExtractArchive: wishtv-izombie-s01e11-720p.part1.rar | Extract failed

**Comment by GammaC0de** [comment]
see #2063
