### ISSUE TITLE
Easybytez link problem after last update

### ISSUE THREAD

**Issue by davboc** [pyload/pyload#2073]
After latest update if I add a link of easybytez, pyload see not like an easybytez link but like a XFileSharing link, then it process two or three downloads at the same time and this is not allowed from easybytez

**Comment by davboc** [comment]
why it still download many files at same time from easybytez when easybytez allow max one or two download at same time? 
Another question, why now in queue list I see only "XFileSharing" instead of the name of the hoster like easybytez or cloudsix?

**Comment by davboc** [comment]
495	22.10.2015 10:19:00	WARNING	Download failed: filename.rev | Missing PLUGIN_DOMAIN
494	22.10.2015 10:19:00	WARNING	HOSTER XFileSharing[779]: EasybytezCom | Plugin may be unstable

**Comment by vuolter** [comment]
Fixed.
