### ISSUE TITLE
uptobox premium account again dead

### ISSUE THREAD

**Issue by damien599901** [pyload/pyload#2075]
Once again the premium accounts of uptobox no longer work

**Comment by vuolter** [comment]
Log please.

**Comment by damien599901** [comment]
288	20.10.2015 23:43:01	INFO	ADDON UpdateManager: pyLoad is up to date!
289	20.10.2015 23:43:02	INFO	ADDON UpdateManager: All plugins are up to date!
290	20.10.2015 23:43:07	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
291	20.10.2015 23:43:13	INFO	Added package test containing 1 links
292	20.10.2015 23:43:13	INFO	Download starts: http://uptobox.com/4u0xx5ibh538
293	20.10.2015 23:43:13	WARNING	HOSTER XFileSharing[4]: UptoboxCom | Plugin may be unstable
294	20.10.2015 23:43:28	INFO	HOSTER XFileSharing[4]: UptoboxCom | Grabbing link info...
295	20.10.2015 23:43:28	INFO	HOSTER XFileSharing[4]: UptoboxCom | Link name: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi
296	20.10.2015 23:43:28	INFO	HOSTER XFileSharing[4]: UptoboxCom | Link size: N/D
297	20.10.2015 23:43:28	INFO	HOSTER XFileSharing[4]: UptoboxCom | Link status: en ligne
298	20.10.2015 23:43:28	INFO	HOSTER XFileSharing[4]: UptoboxCom | Processing as free download...
299	20.10.2015 23:43:29	INFO	HOSTER XFileSharing[4]: UptoboxCom | Downloading file...
300	20.10.2015 23:43:29	WARNING	Download failed: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi | 'NoneType' object has no attribute 'split'
301	20.10.2015 23:43:29	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi (pid:4)
302	20.10.2015 23:43:29	INFO	ADDON UnSkipOnFail: No duplicates found
303	20.10.2015 23:44:03	INFO	ACCOUNT AlldebridCom: Removing user `damien599901`...
304	20.10.2015 23:44:10	INFO	Added package test containing 1 links
305	20.10.2015 23:44:11	INFO	Download starts: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi
306	20.10.2015 23:44:11	WARNING	HOSTER XFileSharing[5]: UptoboxCom | Plugin may be unstable
307	20.10.2015 23:44:11	INFO	HOSTER XFileSharing[5]: UptoboxCom | Grabbing link info...
308	20.10.2015 23:44:11	INFO	HOSTER XFileSharing[5]: UptoboxCom | Link name: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi
309	20.10.2015 23:44:11	INFO	HOSTER XFileSharing[5]: UptoboxCom | Link size: N/D
310	20.10.2015 23:44:11	INFO	HOSTER XFileSharing[5]: UptoboxCom | Link status: en ligne
311	20.10.2015 23:44:11	INFO	HOSTER XFileSharing[5]: UptoboxCom | Processing as free download...
312	20.10.2015 23:44:12	INFO	HOSTER XFileSharing[5]: UptoboxCom | Downloading file...
313	20.10.2015 23:44:12	WARNING	Download failed: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi | 'NoneType' object has no attribute 'split'
314	20.10.2015 23:44:12	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi (pid:5)
315	20.10.2015 23:44:12	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by damien599901** [comment]
304	20.10.2015 23:44:10	INFO	Added package test containing 1 links
305	20.10.2015 23:44:11	INFO	Download starts: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi
306	20.10.2015 23:44:11	WARNING	HOSTER XFileSharing[5]: UptoboxCom | Plugin may be unstable
307	20.10.2015 23:44:11	INFO	HOSTER XFileSharing[5]: UptoboxCom | Grabbing link info...
308	20.10.2015 23:44:11	INFO	HOSTER XFileSharing[5]: UptoboxCom | Link name: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi
309	20.10.2015 23:44:11	INFO	HOSTER XFileSharing[5]: UptoboxCom | Link size: N/D
310	20.10.2015 23:44:11	INFO	HOSTER XFileSharing[5]: UptoboxCom | Link status: en ligne
311	20.10.2015 23:44:11	INFO	HOSTER XFileSharing[5]: UptoboxCom | Processing as free download...
312	20.10.2015 23:44:12	INFO	HOSTER XFileSharing[5]: UptoboxCom | Downloading file...
313	20.10.2015 23:44:12	WARNING	Download failed: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi | 'NoneType' object has no attribute 'split'
314	20.10.2015 23:44:12	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi (pid:5)
315	20.10.2015 23:44:12	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by vuolter** [comment]
Debug log I meant.

**Comment by damien599901** [comment]
457	21.10.2015 07:21:34	INFO	ADDON XFileSharing: Handling any hoster I can!
458	21.10.2015 07:21:34	DEBUG	ADDON XFileSharing: Loaded hoster pattern: https?://(?:www\.)?(?:\w+\.)*(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
459	21.10.2015 07:21:34	INFO	ADDON XFileSharing: Handling any crypter I can!
460	21.10.2015 07:21:34	DEBUG	ADDON XFileSharing: Loaded crypter pattern: https?://(?:www\.)?(?:\w+\.)*(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:user|folder)s?/\w+
461	21.10.2015 07:21:34	INFO	pyLoad is up and running
462	21.10.2015 07:21:35	INFO	ADDON UpdateManager: pyLoad is up to date!
463	21.10.2015 07:21:35	DEBUG	ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
464	21.10.2015 07:21:35	DEBUG	ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BillionuploadsCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'ShareRapidCom'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'Movie2kTo'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'MultiHook'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster')]
465	21.10.2015 07:21:35	INFO	ADDON UpdateManager: All plugins are up to date!
466	21.10.2015 07:21:35	DEBUG	Run Info Fetching for XFileSharing
467	21.10.2015 07:21:35	INFO	Added package test containing 1 links
468	21.10.2015 07:21:36	DEBUG	Finished Info Fetching for XFileSharing
469	21.10.2015 07:21:36	INFO	Download starts: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi
470	21.10.2015 07:21:36	DEBUG	HOSTER XFileSharing[7]: UptoboxCom | Plugin version: 0.59
471	21.10.2015 07:21:36	DEBUG	HOSTER XFileSharing[7]: UptoboxCom | Plugin status: testing
472	21.10.2015 07:21:36	WARNING	HOSTER XFileSharing[7]: UptoboxCom | Plugin may be unstable
473	21.10.2015 07:21:36	DEBUG	HOSTER XFileSharing[7]: UptoboxCom | LOAD URL http://uptobox.com/4u0xx5ibh538 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
474	21.10.2015 07:21:37	INFO	HOSTER XFileSharing[7]: UptoboxCom | Grabbing link info...
475	21.10.2015 07:21:37	DEBUG	HOSTER XFileSharing[7]: UptoboxCom | Link info: {'status': 2, 'pattern': {'N': u'Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi'}, 'size': 0, 'url': u'http://uptobox.com/4u0xx5ibh538', 'name': u'Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi'}
476	21.10.2015 07:21:37	DEBUG	HOSTER XFileSharing[7]: UptoboxCom | Previous link info: {}
477	21.10.2015 07:21:37	INFO	HOSTER XFileSharing[7]: UptoboxCom | Link name: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi
478	21.10.2015 07:21:37	INFO	HOSTER XFileSharing[7]: UptoboxCom | Link size: N/D
479	21.10.2015 07:21:37	INFO	HOSTER XFileSharing[7]: UptoboxCom | Link status: en ligne
480	21.10.2015 07:21:37	INFO	HOSTER XFileSharing[7]: UptoboxCom | Processing as free download...
481	21.10.2015 07:21:37	DEBUG	HOSTER XFileSharing[7]: UptoboxCom | Getting download link #1...
482	21.10.2015 07:21:37	DEBUG	HOSTER XFileSharing[7]: UptoboxCom | {u'rand': u'ym6zbhfzgcmxu2gp4jus3x3xvudeodnx2hvkwyy', u'file_size_real': u'362086000', u'method_premium': '', u'down_direct': u'1', u'referer': '', u'fname': u'Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi', u'method_free': '', u'id': u'4u0xx5ibh538', u'op': u'download2'}
483	21.10.2015 07:21:37	DEBUG	HOSTER XFileSharing[7]: UptoboxCom | LOAD URL http://uptobox.com/4u0xx5ibh538 | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'rand': u'ym6zbhfzgcmxu2gp4jus3x3xvudeodnx2hvkwyy', u'file_size_real': u'362086000', u'down_direct': u'1', u'referer': '', u'fname': u'Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi', u'method_free': 'Free Download', u'id': u'4u0xx5ibh538', u'op': u'download2'} | ref=True | just_header=False
484	21.10.2015 07:21:37	INFO	HOSTER XFileSharing[7]: UptoboxCom | Downloading file...
485	21.10.2015 07:21:37	WARNING	Download failed: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi | cannot concatenate 'str' and 'NoneType' objects
486	21.10.2015 07:21:37	INFO	Debug Report written to debug_XFileSharing_21-10-2015_07-21-37.zip
487	21.10.2015 07:21:37	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Blue.Bloods.S06E04.FASTSUB.VOSTFR.HDTV.XviD-ZT.zone-telechargement.com.avi (pid:7)
488	21.10.2015 07:21:37	INFO	ADDON UnSkipOnFail: No duplicates found
489	21.10.2015 07:21:37	DEBUG	All downloads processed
490	21.10.2015 07:21:40	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666

**Comment by damien599901** [comment]
Again KO.

'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128) 0.00 BUptoboxCom

there's no end for those issues?

**Comment by damien599901** [comment]
dead again. There 's not end @vuolter ? 
i m really sad very sad and my family too

**Comment by damien599901** [comment]
FYI issue with.rar extension

**Comment by GammaC0de** [comment]
Is this issue still exists?

**Comment by damien599901** [comment]
yes GammaC0de :(

**Comment by GammaC0de** [comment]
Do you have a premium account for testing?
Please  send account info to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
@damien599901 Well?

**Comment by youlJunior** [comment]
FYI, I'm using premium on UpToBox, and all is working.

**Comment by GammaC0de** [comment]
@youlJunior 👍 Closing.
