### ISSUE TITLE
[OneFichier] Pycurl error

### ISSUE THREAD

**Issue by youlJunior** [pyload/pyload#2076]
I can't download any file from 1fichier.com, I have a strange error : 
pycurl error 0: ('cannot invoke setopt() - perform() is currently running',)

(log is reversed)
19.10.2015 23:59:53 DEBUG   All downloads processed
668 19.10.2015 23:59:53 WARNING Download failed: ?n5us9jaq4i | 'NoneType' object has no attribute 'id'
667 19.10.2015 23:59:52 DEBUG   All downloads processed
666 19.10.2015 23:59:52 INFO    ADDON UnSkipOnFail: No duplicates found
665 19.10.2015 23:59:52 INFO    ADDON UnSkipOnFail: Looking for skipped duplicates of: ?n5us9jaq4i (pid:2)
664 19.10.2015 23:59:52 INFO    Debug Report written to debug_OneFichierCom_19-10-2015_23-59-51.zip
663 19.10.2015 23:59:51 INFO    HOSTER OneFichierCom[3]: Grabbing link info...
662 19.10.2015 23:59:51 ERROR   pycurl error 0: ('cannot invoke setopt() - perform() is currently running',)
661 19.10.2015 23:59:51 DEBUG   pycurl exception 0: ('cannot invoke setopt() - perform() is currently running',)
660 19.10.2015 23:59:51 DEBUG   HOSTER OneFichierCom[3]: LOAD URL http://1fichier.com/?n5us9jaq4i | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
659 19.10.2015 23:59:51 DEBUG   HOSTER OneFichierCom[3]: Redirect #0 to: http://1fichier.com/?n5us9jaq4i
658 19.10.2015 23:59:51 INFO    HOSTER OneFichierCom[3]: Looking for direct download link...
657 19.10.2015 23:59:51 INFO    HOSTER OneFichierCom[3]: Link status: en file d'attente
656 19.10.2015 23:59:51 INFO    HOSTER OneFichierCom[3]: Link size: N/D
655 19.10.2015 23:59:51 INFO    HOSTER OneFichierCom[3]: Link name: ?n5us9jaq4i
654 19.10.2015 23:59:51 DEBUG   HOSTER OneFichierCom[3]: Previous link info: {}
653 19.10.2015 23:59:51 DEBUG   HOSTER OneFichierCom[3]: Link info: {'status': 3, 'name': '?n5us9jaq4i', 'url': u'http://1fichier.com/?n5us9jaq4i', 'pattern': {'HOST': u'1fichier.com'}, 'size': 0}
652 19.10.2015 23:59:50 DEBUG   HOSTER OneFichierCom[3]: LOAD URL http://1fichier.com/?n5us9jaq4i | redirect=True | cookies=[('1fichier.com', 'LG', 'en')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
651 19.10.2015 23:59:50 INFO    HOSTER OneFichierCom[3]: Direct download link not found
650 19.10.2015 23:59:49 DEBUG   HOSTER OneFichierCom[3]: LOAD URL https://1fichier.com/?n5us9jaq4i | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
649 19.10.2015 23:59:49 DEBUG   HOSTER OneFichierCom[3]: Redirect #1 to: https://1fichier.com/?n5us9jaq4i
648 19.10.2015 23:59:49 DEBUG   HOSTER OneFichierCom[3]: LOAD URL http://1fichier.com/?n5us9jaq4i | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
647 19.10.2015 23:59:49 DEBUG   HOSTER OneFichierCom[3]: Redirect #0 to: http://1fichier.com/?n5us9jaq4i
646 19.10.2015 23:59:49 INFO    HOSTER OneFichierCom[3]: Looking for direct download link...
645 19.10.2015 23:59:49 INFO    HOSTER OneFichierCom[3]: Link status: en file d'attente
644 19.10.2015 23:59:49 INFO    HOSTER OneFichierCom[3]: Link size: N/D
643 19.10.2015 23:59:49 INFO    HOSTER OneFichierCom[3]: Link name: ?n5us9jaq4i
642 19.10.2015 23:59:49 DEBUG   HOSTER OneFichierCom[3]: Previous link info: {}
641 19.10.2015 23:59:49 DEBUG   HOSTER OneFichierCom[3]: Link info: {'status': 3, 'pattern': {'HOST': u'1fichier.com'}, 'size': 0, 'url': u'http://1fichier.com/?n5us9jaq4i', 'name': '?n5us9jaq4i'}
640 19.10.2015 23:59:49 INFO    HOSTER OneFichierCom[3]: Grabbing link info...
639 19.10.2015 23:59:49 WARNING HOSTER OneFichierCom[3]: Plugin may be unstable
638 19.10.2015 23:59:49 DEBUG   HOSTER OneFichierCom[3]: Plugin status: testing
637 19.10.2015 23:59:49 DEBUG   HOSTER OneFichierCom[3]: Plugin version: 0.94
636 19.10.2015 23:59:49 DEBUG   ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
635 19.10.2015 23:59:49 INFO    Download starts: https://1fichier.com/?n5us9jaq4i
634 19.10.2015 23:59:47 INFO    HOSTER OneFichierCom[3]: Grabbing link info...
633 19.10.2015 23:59:47 WARNING HOSTER OneFichierCom[3]: Plugin may be unstable
632 19.10.2015 23:59:47 DEBUG   HOSTER OneFichierCom[3]: Plugin status: testing
631 19.10.2015 23:59:47 DEBUG   HOSTER OneFichierCom[3]: Plugin version: 0.94
630 19.10.2015 23:59:47 DEBUG   ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
629 19.10.2015 23:59:47 INFO    Download starts: https://1fichier.com/?n5us9jaq4i
628 19.10.2015 23:59:45 INFO    HOSTER OneFichierCom[3]: Grabbing link info...
627 19.10.2015 23:59:45 WARNING HOSTER OneFichierCom[3]: Plugin may be unstable
626 19.10.2015 23:59:45 DEBUG   HOSTER OneFichierCom[3]: Plugin status: testing
625 19.10.2015 23:59:45 DEBUG   HOSTER OneFichierCom[3]: Plugin version: 0.94
624 19.10.2015 23:59:45 DEBUG   ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
623 19.10.2015 23:59:45 INFO    Download starts: https://1fichier.com/?n5us9jaq4i
622 19.10.2015 23:59:43 INFO    HOSTER OneFichierCom[3]: Grabbing link info...
621 19.10.2015 23:59:43 WARNING HOSTER OneFichierCom[3]: Plugin may be unstable
620 19.10.2015 23:59:43 DEBUG   HOSTER OneFichierCom[3]: Plugin status: testing
619 19.10.2015 23:59:43 DEBUG   HOSTER OneFichierCom[3]: Plugin version: 0.94
618 19.10.2015 23:59:43 INFO    Download starts: https://1fichier.com/?n5us9jaq4i
617 19.10.2015 23:59:43 DEBUG   Run Info Fetching for OneFichierCom
616 19.10.2015 23:59:43 DEBUG   Redirected import module.plugins.internal.Captcha -> userplugins.internal.Captcha
615 19.10.2015 23:59:42 DEBUG   Redirected import module.plugins.internal.Base -> userplugins.internal.Base
614 19.10.2015 23:59:42 DEBUG   Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
613 19.10.2015 23:59:42 DEBUG   Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
612 19.10.2015 23:59:42 DEBUG   Redirected import module.plugins.hoster.OneFichierCom -> userplugins.hoster.OneFichierCom
611 19.10.2015 23:59:42 INFO    Added package test2 containing 1 links

**Comment by fab76** [comment]
hello same error for me :
WARNING	Download failed: ?32zen3ozyi | 'NoneType' object has no attribute 'id'

**Comment by youlJunior** [comment]
I have another problem now : 
When i add a link from 1fichier, the download start, but the file stay in "waiting" state, with a 15 minutes countdown.
When the download is finished, the post download script runs, but the link and the package stay in "waiting" and the coutdown still runs...

Here is the log in debug : 

26.10.2015 00:47:09 INFO      Download starts: https://1fichier.com/?70zwnlj91k
26.10.2015 00:47:09 DEBUG     HOSTER OneFichierCom[39]: Plugin version: 0.94
26.10.2015 00:47:09 DEBUG     HOSTER OneFichierCom[39]: Plugin status: testing
26.10.2015 00:47:09 WARNING   HOSTER OneFichierCom[39]: Plugin may be unstable
26.10.2015 00:47:09 INFO      HOSTER OneFichierCom[39]: Grabbing link info...
26.10.2015 00:47:11 INFO      Download starts: https://1fichier.com/?70zwnlj91k
26.10.2015 00:47:11 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
26.10.2015 00:47:11 DEBUG     HOSTER OneFichierCom[39]: Plugin version: 0.94
26.10.2015 00:47:11 DEBUG     HOSTER OneFichierCom[39]: Plugin status: testing
26.10.2015 00:47:11 WARNING   HOSTER OneFichierCom[39]: Plugin may be unstable
26.10.2015 00:47:11 INFO      HOSTER OneFichierCom[39]: Grabbing link info...
26.10.2015 00:47:11 DEBUG     HOSTER OneFichierCom[39]: Link info: {'status': 3, 'pattern': {'HOST': u'1fichier.com'}, 'size': 0, 'url': u'http://1fichier.com/?70zwnlj91k', 'na
me': '?70zwnlj91k'}
26.10.2015 00:47:11 DEBUG     HOSTER OneFichierCom[39]: Previous link info: {}
26.10.2015 00:47:11 INFO      HOSTER OneFichierCom[39]: Link name: ?70zwnlj91k
26.10.2015 00:47:11 INFO      HOSTER OneFichierCom[39]: Link size: N/D
26.10.2015 00:47:11 INFO      HOSTER OneFichierCom[39]: Link status: en file d'attente
26.10.2015 00:47:11 INFO      HOSTER OneFichierCom[39]: Looking for direct download link...
26.10.2015 00:47:11 DEBUG     HOSTER OneFichierCom[39]: Redirect #0 to: http://1fichier.com/?70zwnlj91k
26.10.2015 00:47:11 DEBUG     HOSTER OneFichierCom[39]: LOAD URL http://1fichier.com/?70zwnlj91k | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=Fa
lse | post={} | ref=True | just_header=True
26.10.2015 00:47:11 DEBUG     HOSTER OneFichierCom[39]: Redirect #1 to: https://1fichier.com/?70zwnlj91k
26.10.2015 00:47:11 DEBUG     HOSTER OneFichierCom[39]: LOAD URL https://1fichier.com/?70zwnlj91k | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=F
alse | post={} | ref=True | just_header=True
26.10.2015 00:47:11 DEBUG     HOSTER OneFichierCom[39]: Redirect #1 to: https://1fichier.com/?70zwnlj91k
26.10.2015 00:47:11 DEBUG     HOSTER OneFichierCom[39]: LOAD URL https://1fichier.com/?70zwnlj91k | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=F
alse | post={} | ref=True | just_header=True
26.10.2015 00:47:12 INFO      HOSTER OneFichierCom[39]: Direct download link not found
26.10.2015 00:47:12 DEBUG     HOSTER OneFichierCom[39]: LOAD URL http://1fichier.com/?70zwnlj91k | redirect=True | cookies=[('1fichier.com', 'LG', 'en')] | get={} | req=None |
decode=True | multipart=False | post={} | ref=False | just_header=False
26.10.2015 00:47:13 INFO      HOSTER OneFichierCom[39]: Grabbing link info...
26.10.2015 00:47:14 DEBUG     HOSTER OneFichierCom[39]: Link info: {'status': 3, 'name': '?70zwnlj91k', 'url': u'http://1fichier.com/?70zwnlj91k', 'pattern': {'HOST': u'1fichie
r.com'}, 'size': 0}
26.10.2015 00:47:14 DEBUG     HOSTER OneFichierCom[39]: Previous link info: {}
26.10.2015 00:47:14 INFO      HOSTER OneFichierCom[39]: Link name: ?70zwnlj91k
26.10.2015 00:47:14 INFO      HOSTER OneFichierCom[39]: Link size: N/D
26.10.2015 00:47:14 INFO      HOSTER OneFichierCom[39]: Link status: en file d'attente
26.10.2015 00:47:14 INFO      HOSTER OneFichierCom[39]: Looking for direct download link...
26.10.2015 00:47:14 DEBUG     HOSTER OneFichierCom[39]: Redirect #0 to: http://1fichier.com/?70zwnlj91k
26.10.2015 00:47:14 DEBUG     HOSTER OneFichierCom[39]: LOAD URL http://1fichier.com/?70zwnlj91k | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=Fa
lse | post={} | ref=True | just_header=True
26.10.2015 00:47:14 DEBUG     HOSTER OneFichierCom[39]: Redirect #1 to: https://1fichier.com/?70zwnlj91k
26.10.2015 00:47:14 DEBUG     HOSTER OneFichierCom[39]: LOAD URL https://1fichier.com/?70zwnlj91k | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=F
alse | post={} | ref=True | just_header=True
26.10.2015 00:47:15 DEBUG     HOSTER OneFichierCom[39]: Link info: {'status': 2, 'name': u'Star.Wars.Rebels.S01E12.FRENCH.DVDRip.x264-LiBERTY.mkv', 'url': u'http://1fichier.com
/?70zwnlj91k', 'pattern': {'HOST': u'1fichier.com', 'U': u'MB', 'S': u'215.40', 'N': u'Star.Wars.Rebels.S01E12.FRENCH.DVDRip.x264-LiBERTY.mkv'}, 'size': 225853440}
26.10.2015 00:47:15 DEBUG     HOSTER OneFichierCom[39]: Previous link info: {'status': 3, 'pattern': {'HOST': u'1fichier.com'}, 'url': u'http://1fichier.com/?70zwnlj91k', 'name
': '?70zwnlj91k', 'size': 0}
26.10.2015 00:47:15 INFO      HOSTER OneFichierCom[39]: Link name: Star.Wars.Rebels.S01E12.FRENCH.DVDRip.x264-LiBERTY.mkv
26.10.2015 00:47:15 INFO      HOSTER OneFichierCom[39]: Link size: 215.39 MiB (225853440 bytes)
26.10.2015 00:47:15 INFO      HOSTER OneFichierCom[39]: Link status: en ligne
26.10.2015 00:47:15 INFO      HOSTER OneFichierCom[39]: Processing as free download...
26.10.2015 00:47:15 DEBUG     HOSTER OneFichierCom[39]: DOWNLOAD URL https://1fichier.com/?70zwnlj91k | cookies=True | resume=None | get={} | disposition=True | chunks=None | p
ost={u'dl_no_ssl': '', 'submit': 'Download', u'dlinline': ''} | ref=True
26.10.2015 00:47:15 INFO      HOSTER OneFichierCom[39]: Direct download link not found
26.10.2015 00:47:15 DEBUG     HOSTER OneFichierCom[39]: LOAD URL http://1fichier.com/?70zwnlj91k | redirect=True | cookies=[('1fichier.com', 'LG', 'en')] | get={} | req=None |
decode=True | multipart=False | post={} | ref=False | just_header=False
26.10.2015 00:47:16 INFO      HOSTER OneFichierCom[39]: Processing as free download...
26.10.2015 00:47:16 DEBUG     HOSTER OneFichierCom[39]: Config option `max_wait` not found, use default `10`
26.10.2015 00:47:16 DEBUG     HOSTER OneFichierCom[39]: WAIT set to timestamp 1445817737.832038 | Previous waitUntil: 0.000000
26.10.2015 00:47:16 DEBUG     HOSTER OneFichierCom[39]: RECONNECT  required | Previous wantReconnect: False
26.10.2015 00:47:16 INFO      HOSTER OneFichierCom[39]: Waiting 15 minutes...
26.10.2015 00:47:16 INFO      HOSTER OneFichierCom[39]: Requiring reconnection...
26.10.2015 00:47:20 DEBUG     Content-Disposition: Star.Wars.Rebels.S01E12.FRENCH.DVDRip.x264-LiBERTY.mkv filename*=UTF-8Star.Wars.Rebels.S01E12.FRENCH.DVDRip.x264-LiBERTY.mkv
26.10.2015 00:52:04 DEBUG     Cleared Result cache
26.10.2015 00:53:49 INFO      HOSTER OneFichierCom[39]: `Star.Wars.Rebels.S01E12.FRENCH.DVDRip.x264-LiBERTY.mkv` saved as `Star.Wars.Rebels.S01E12.FRENCH.DVDRip.x264-LiBERTY.mk
v`
26.10.2015 00:53:49 INFO      HOSTER OneFichierCom[39]: Checking downloaded file...
26.10.2015 00:53:50 DEBUG     HOSTER OneFichierCom[39]: Config option `chk_filesize` not found, use default `None`
26.10.2015 00:53:50 INFO      HOSTER OneFichierCom[39]: File is OK
26.10.2015 00:53:50 DEBUG     HOSTER OneFichierCom[39]: Performing default check rules...
26.10.2015 00:53:50 DEBUG     HOSTER OneFichierCom[39]: Performing custom check rules...
26.10.2015 00:53:50 INFO      Download finished: Star.Wars.Rebels.S01E12.FRENCH.DVDRip.x264-LiBERTY.mkv
26.10.2015 00:53:50 INFO      ADDON ExternalScripts: EXECUTE [/etc/pyload/scripts/download_finished] ['/etc/pyload/scripts/download_finished/script_dl_done.sh', '39', 'Star.War
s.Rebels.S01E12.FRENCH.DVDRip.x264-LiBERTY.mkv', '/HDD4/Pyload/Star.Wars.Rebels.S01E12.FRENCH.DVDRip.x264-LiBERTY.mkv', 'OneFichierCom', 'http://1fichier.com/?70zwnlj91k']
26.10.2015 00:53:50 INFO      Package finished: Star Wars Rebels S01 - 2

**Comment by Velociraptor85** [comment]
worked for me in current version
