### ISSUE TITLE
Last Base.py killed everything

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#2082]
Your last Base.py update killed again everything.
Before everything seems to work.
You forgot a colon in line 12.
<pre><code>
414	20.10.2015 19:31:49	CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
413	20.10.2015 19:31:49	ERROR	Error importing ShareonlineBiz: invalid syntax (Base.py, line 13)
412	20.10.2015 19:31:47	CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
411	20.10.2015 19:31:47	ERROR	Error importing ShareonlineBiz: invalid syntax (Base.py, line 13)
410	20.10.2015 19:30:59	CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
409	20.10.2015 19:30:59	ERROR	Error importing ShareonlineBiz: invalid syntax (Base.py, line 13)
408	20.10.2015 19:30:57	CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
407	20.10.2015 19:30:57	ERROR	Error importing ShareonlineBiz: invalid syntax (Base.py, line 13)
406	20.10.2015 19:30:55	CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
405	20.10.2015 19:30:55	ERROR	Error importing ShareonlineBiz: invalid syntax (Base.py, line 13)
404	20.10.2015 19:30:53	CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
403	20.10.2015 19:30:53	ERROR	Error importing ShareonlineBiz: invalid syntax (Base.py, line 13)
402	20.10.2015 19:30:51	CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
401	20.10.2015 19:30:51	ERROR	Error importing ShareonlineBiz: invalid syntax (Base.py, line 13)
400	20.10.2015 19:30:49	CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
399	20.10.2015 19:30:49	ERROR	Error importing ShareonlineBiz: invalid syntax (Base.py, line 13)
398	20.10.2015 19:30:47	INFO	ADDON RestartFailed: Restarting all failed downloads...
</code></pre>

**Comment by vuolter** [comment]
:anguished: 
Thanks for reporting!
