### ISSUE TITLE
Easybytez and cloudsix still not working

### ISSUE THREAD

**Issue by willoz88** [pyload/pyload#2086]
After the last update easybitez and cloudsix stills unworking
the log follows
INFO	Download starts: Filename.part3.rar
WARNING  HOSTER XFileSharing[1]: CloudsixMe | Plugin may be unstable
INFO	HOSTER XFileSharing[1]: CloudsixMe | Grabbing link info...
INFO	HOSTER XFileSharing[1]: CloudsixMe | Link name: Filename.part3.rar
INFO	HOSTER XFileSharing[1]: CloudsixMe | Link size: 264241152 bytes
INFO	HOSTER XFileSharing[1]: CloudsixMe | Link status: online
INFO	HOSTER XFileSharing[1]: CloudsixMe | Processing as free download...
WARNING	  CAPTCHA XFileSharing[1]: CloudsixMe | ReCaptcha | Key pattern not found
WARNING  Download failed: Filename.part3.rar | date value out of range 
and
INFO	Download starts: Filename.part3.rar
WARNING	HOSTER XFileSharing[1]: CloudsixMe | Plugin may be unstable
INFO	HOSTER XFileSharing[1]: CloudsixMe | Grabbing link info...
INFO	HOSTER XFileSharing[1]: CloudsixMe | Link name: Filename.part3.rar
INFO	HOSTER XFileSharing[1]: CloudsixMe | Link size: 264241152 bytes
INFO	HOSTER XFileSharing[1]: CloudsixMe | Link status: online
INFO	HOSTER XFileSharing[1]: CloudsixMe | Processing as free download...
WARNING	CAPTCHA XFileSharing[1]: CloudsixMe | ReCaptcha | Key pattern not found
WARNING	Download failed: Filename.part3.rar | date value out of range

**Comment by willoz88** [comment]
also
INFO	Download starts: http://www.easybytez.com/js2zlrljwi7r
WARNING	HOSTER XFileSharing[4]: EasybytezCom | Plugin may be unstable
INFO	HOSTER XFileSharing[4]: EasybytezCom | Grabbing link info...
INFO	HOSTER XFileSharing[4]: EasybytezCom | Link name: Filename.mkv
INFO	HOSTER XFileSharing[4]: EasybytezCom | Link size: 366669824 bytes
INFO	HOSTER XFileSharing[4]: EasybytezCom | Link status: online
INFO	HOSTER XFileSharing[4]: EasybytezCom | Processing as free download...
WARNING	CAPTCHA XFileSharing[4]: EasybytezCom | ReCaptcha | Key pattern not found
WARNING	Download failed: Filename.mkv | date value out of range

**Comment by willoz88** [comment]
Why both easybytez and cloudsix packages where handled by Xfilesharing plugin?

**Comment by GammaC0de** [comment]
are you using free of premium account for easybytez?

**Comment by Hadronius** [comment]
Exactly the same happens with Worldbytez, where I'm using a premium account.
I'll try to debug it when I find some time.

**Comment by GammaC0de** [comment]
try #2088

**Comment by GammaC0de** [comment]
:+1:
