### ISSUE TITLE
[Notifier] Too restrictive

### ISSUE THREAD

**Issue by malkavi** [pyload/pyload#2092]
WindowsPhoneNotify and PushOver can't work. Both of them need a pair of keys to work (get_ket return 2 values) and Notifier doesn't allow this.
```
    @Expose
    def notify(self, event, msg="", key=None):
        key = key or self.get_key()
        if isiterable(key) and all(key) or not key:
            return
```

There is any reason for this?

**Comment by vuolter** [comment]
In these cases `key` is a tuple.
