### ISSUE TITLE
No module named HTMLParser 

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#2099]
Hello with the new update i get this error.
492	23.10.2015 07:47:30	ERROR	Fehler beim importieren von UserAgentSwitcher: No module named HTMLParser
491	23.10.2015 07:47:30	DEBUG	Redirected import module.plugins.internal.utils -> userplugins.internal.utils
490	23.10.2015 07:47:30	ERROR	Fehler beim importieren von XFileSharing: No module named HTMLParser
489	23.10.2015 07:47:30	DEBUG	Redirected import module.plugins.internal.utils -> userplugins.internal.utils
488	23.10.2015 07:47:30	DEBUG	Redirected import module.plugins.hooks.XFileSharing -> userplugins.hooks.XFileSharing
487	23.10.2015 07:47:30	ERROR	Fehler beim importieren von ExtractArchive: No module named HTMLParser
486	23.10.2015 07:47:30	DEBUG	Redirected import module.plugins.internal.utils -> userplugins.internal.utils
485	23.10.2015 07:47:30	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
484	23.10.2015 07:47:30	ERROR	Fehler beim importieren von UnSkipOnFail: No module named HTMLParser
483	23.10.2015 07:47:30	DEBUG	Redirected import module.plugins.internal.utils -> userplugins.internal.utils
482	23.10.2015 07:47:30	ERROR	Fehler beim importieren von AntiStandby: No module named HTMLParser
481	23.10.2015 07:47:30	DEBUG	Redirected import module.plugins.internal.utils -> userplugins.internal.utils
480	23.10.2015 07:47:30	ERROR	Fehler beim importieren von ExternalScripts: No module named HTMLParser
479	23.10.2015 07:47:30	DEBUG	Redirected import module.plugins.internal.utils -> userplugins.internal.utils
478	23.10.2015 07:47:30	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
477	23.10.2015 07:47:30	ERROR	Fehler beim importieren von UpdateManager: No module named HTMLParser
476	23.10.2015 07:47:30	DEBUG	Redirected import module.plugins.internal.utils -> userplugins.internal.utils

**Comment by mattionline** [comment]
595	23.10.2015 11:27:47	ERROR	Error importing PremiumTo: cannot import name fixup
596	23.10.2015 11:27:47	ERROR	Error importing OverLoadMe: cannot import name fixup
597	23.10.2015 11:27:47	ERROR	Error importing DataHu: cannot import name fixup
598	23.10.2015 11:27:47	ERROR	Error importing BasketbuildCom: cannot import name fixup
599	23.10.2015 11:27:47	ERROR	Error importing FileSharkPl: cannot import name fixup
600	23.10.2015 11:27:47	ERROR	Error importing GamefrontCom: cannot import name fixup
601	23.10.2015 11:27:47	ERROR	Error importing ExtabitCom: cannot import name fixup
602	23.10.2015 11:27:47	ERROR	Error importing FilejungleCom: cannot import name fixup
603	23.10.2015 11:27:47	ERROR	Error importing DepositfilesCom: cannot import name fixup
604	23.10.2015 11:27:47	ERROR	Error importing DlFreeFr: cannot import name fixup
605	23.10.2015 11:27:47	ERROR	Error importing GoogledriveCom: cannot import name fixup
606	23.10.2015 11:27:47	ERROR	Error importing SimplyPremiumCom: cannot import name fixup
607	23.10.2015 11:27:47	INFO	ADDON XFileSharing: Handle any hoster site on the web!
608	23.10.2015 11:27:47	INFO	ADDON XFileSharing: Handle any crypter site on the web!
609	23.10.2015 11:27:47	INFO	pyLoad is up and running
610	23.10.2015 11:27:52	INFO	ADDON UpdateManager: pyLoad is up to date!
611	23.10.2015 11:27:53	INFO	ADDON UpdateManager: All plugins are up to date!

**Comment by mattionline** [comment]
Now i cant download anymore...


693	23.10.2015 11:49:45	CRITICAL	'NoneType' object has no attribute 'UploadedTo'
692	23.10.2015 11:49:45	ERROR	Error importing UploadedTo: cannot import name fixup
691	23.10.2015 11:49:43	CRITICAL	'NoneType' object has no attribute 'UploadedTo'
690	23.10.2015 11:49:43	ERROR	Error importing UploadedTo: cannot import name fixup
689	23.10.2015 11:49:41	CRITICAL	'NoneType' object has no attribute 'UploadedTo'
688	23.10.2015 11:49:41	ERROR	Error importing UploadedTo: cannot import name fixup

620	23.10.2015 11:49:11	WARNING	CONTAINER DLC[385]: Plugin may be unstable
618	23.10.2015 11:48:53	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
617	23.10.2015 11:48:52	INFO	ADDON UpdateManager: All plugins are up to date!
616	23.10.2015 11:48:52	INFO	ADDON UpdateManager: pyLoad is up to date!
615	23.10.2015 11:48:47	INFO	pyLoad is up and running
614	23.10.2015 11:48:47	INFO	ADDON XFileSharing: Handle any crypter site on the web!
613	23.10.2015 11:48:47	INFO	ADDON XFileSharing: Handle any hoster site on the web!
612	23.10.2015 11:48:47	ERROR	Error importing SimplyPremiumCom: cannot import name fixup
611	23.10.2015 11:48:47	ERROR	Error importing GoogledriveCom: cannot import name fixup
610	23.10.2015 11:48:47	ERROR	Error importing DlFreeFr: cannot import name fixup
