### ISSUE TITLE
cannot import name fixup

### ISSUE THREAD

**Issue by acidburn78** [pyload/pyload#2100]
Since the Last Update i get multiple Errors:

23.10.2015 08:16:28 ERROR     Error importing LoadTo: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing LolabitsEs: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing ZippyshareCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing FilecloudIo: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing FlyFilesNet: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing MyfastfileCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing HundredEightyUploadCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing PremiumizeMe: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing PromptfileCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing CzshareCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing SmoozedCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing VeohCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing ZahikiNet: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing RapideoPl: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing RgHostNet: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing UlozTo: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing UploadedTo: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing XFileSharing: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing FilepupNet: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing GooIm: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing PutdriveCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing NoPremiumPl: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing UploadingCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing LetitbitNet: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing AlldebridCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing UpleaCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing NitroflareCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing ZeveraCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing NowDownloadSx: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing YibaishiwuCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing NowVideoSx: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing FastshareCz: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing RPNetBiz: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing UloziskoSk: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing GigapetaCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing NowDownloadEu: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing MegaDebridEu: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing TurbobitNet: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing UptoboxCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing RapidfileshareNet: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing FreakshareCom: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing UploadableCh: cannot import name fixup
23.10.2015 08:16:28 ERROR     Error importing MovReelCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing CloudzillaTo: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing SolidfilesCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing UserscloudCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing MultishareCz: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing RarefileNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FilefactoryCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing VidPlayNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing HighWayMe: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing HostujeNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing Share4WebCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing SoundcloudCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing MegasharesCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FiledropperCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing StahnuTo: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing MegaRapidCz: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing RemixshareCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FilepostCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FileStoreTo: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing MystoreTo: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing StreamcloudEu: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing SendmywayCom: No module named XFileSharingPro
23.10.2015 08:16:29 ERROR     Error importing SafesharingEu: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing TusfilesNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing JumbofilesCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing SendspaceCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing NovafileCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing KingfilesNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing XdadevelopersCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing NosuploadCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing MediafireCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing SpeedyshareCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing MegaRapidoNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FreeWayMe: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing RealdebridCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing LinksnappyCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing SimplydebridCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing IfolderRu: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing VkCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing HugefilesNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing ExashareCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing RehostTo: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing Keep2ShareCc: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing QuickshareCz: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FastixRu: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing MultihostersCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing YadiSk: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing CrockoCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing ShareonlineBiz: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FileomCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing AndroidfilehostCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing VimeoCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FileboomMe: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing HellshareCz: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing WebshareCz: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing DropboxCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing TwoSharedCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing SecureUploadEu: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing DateiTo: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing UpstoreNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing DevhostSt: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing OneFichierCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing EdiskCz: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing BezvadataCz: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing NarodRu: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing RapidgatorNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing JunocloudMe: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing DebridItaliaCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing UnibytesCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing OpenloadIo: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FilerioCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing UploadheroCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing SizedriveCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FilerNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing RapiduNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing BitshareCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FshareVn: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing LuckyShareNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing DataportCz: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FileuploadNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing CramitIn: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing RyushareCom: No module named XFileSharingPro
23.10.2015 08:16:29 ERROR     Error importing EuroshareEu: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FourSharedCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing EasybytezCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FileserveCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing CatShareNet: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing PremiumTo: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing OverLoadMe: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing DataHu: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing BasketbuildCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FileSharkPl: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing GamefrontCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing SimplyPremiumCom: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing WrzucTo: cannot import name fixup
23.10.2015 08:16:29 ERROR     Error importing FilejungleCom: cannot import name fixup
23.10.2015 08:16:30 ERROR     Error importing DepositfilesCom: cannot import name fixup
23.10.2015 08:16:30 ERROR     Error importing DlFreeFr: cannot import name fixup
23.10.2015 08:16:30 ERROR     Error importing GoogledriveCom: cannot import name fixup
23.10.2015 08:16:30 ERROR     Error importing ExtabitCom: cannot import name fixup

**Comment by chaosmaker** [comment]
Delete the userplugins folder and let it download again

**Comment by bollstedt** [comment]
I have the same probleme and deleting the userplugins did not work for me, still the same error message.

**Comment by CultUr** [comment]
same here. also no download via uploaded.to premium account. seems to be related on this issue:

23.10.2015 09:19:59	CRITICAL	'NoneType' object has no attribute 'UploadedTo'
926	23.10.2015 09:19:59	ERROR	Error importing UploadedTo: cannot import name fixup

**Comment by chaosmaker** [comment]
Have you tried cloning the git again?

**Comment by acidburn78** [comment]
it's all up to date

**Comment by CultUr** [comment]
getting the same issue after git clone

**Comment by acidburn78** [comment]
I found a Fixup:

The Problem is the /internal/SimpleHoster.py plugin in the git is no Version-Up after some changes in the File.

Nano SimpleHoster.py delete the Code an copy&paste the Code from the RAW

**Comment by vuolter** [comment]
:anguished:
