### ISSUE TITLE
Cannot import name fixup

### ISSUE THREAD

**Issue by Paxx23** [pyload/pyload#2101]
After manually updating updatemanager.py because of the problem with version mismatch, pyload stops working. I get several Errors:

1018	23.10.2015 12:09:52	ERROR	Error importing RarefileNet: cannot import name fixup
1019	23.10.2015 12:09:52	ERROR	Error importing ZippyshareCom: cannot import name fixup
1020	23.10.2015 12:09:52	ERROR	Error importing FilecloudIo: cannot import name fixup
1021	23.10.2015 12:09:52	ERROR	Error importing VeohCom: cannot import name fixup
1022	23.10.2015 12:09:52	ERROR	Error importing HostujeNet: cannot import name fixup
1023	23.10.2015 12:09:52	ERROR	Error importing Share4WebCom: cannot import name fixup
1024	23.10.2015 12:09:52	ERROR	Error importing SoundcloudCom: cannot import name fixup
1025	23.10.2015 12:09:52	ERROR	Error importing MegasharesCom: cannot import name fixup
1026	23.10.2015 12:09:52	ERROR	Error importing MultihostersCom: cannot import name fixup
1027	23.10.2015 12:09:52	ERROR	Error importing StahnuTo: cannot import name fixup
1028	23.10.2015 12:09:52	ERROR	Error importing MegaRapidCz: cannot import name fixup
1029	23.10.2015 12:09:52	ERROR	Error importing RemixshareCom: cannot import name fixup
1030	23.10.2015 12:09:52	ERROR	Error importing FilepostCom: cannot import name fixup
1031	23.10.2015 12:09:52	ERROR	Error importing MystoreTo: cannot import name fixup
1032	23.10.2015 12:09:52	ERROR	Error importing StreamcloudEu: cannot import name fixup
1033	23.10.2015 12:09:52	ERROR	Error importing SendmywayCom: No module named XFileSharingPro
1034	23.10.2015 12:09:52	ERROR	Error importing PromptfileCom: cannot import name fixup
1035	23.10.2015 12:09:52	ERROR	Error importing TusfilesNet: cannot import name fixup
1036	23.10.2015 12:09:52	ERROR	Error importing JumbofilesCom: cannot import name fixup
1037	23.10.2015 12:09:52	ERROR	Error importing SendspaceCom: cannot import name fixup
1038	23.10.2015 12:09:52	ERROR	Error importing NovafileCom: cannot import name fixup
1039	23.10.2015 12:09:52	ERROR	Error importing XdadevelopersCom: cannot import name fixup
1040	23.10.2015 12:09:52	ERROR	Error importing RPNetBiz: cannot import name fixup
1041	23.10.2015 12:09:52	ERROR	Error importing MediafireCom: cannot import name fixup
1042	23.10.2015 12:09:52	ERROR	Error importing SpeedyshareCom: cannot import name fixup
1043	23.10.2015 12:09:52	ERROR	Error importing MegaRapidoNet: cannot import name fixup
1044	23.10.2015 12:09:52	ERROR	Error importing FreeWayMe: cannot import name fixup
1045	23.10.2015 12:09:52	ERROR	Error importing RealdebridCom: cannot import name fixup
1046	23.10.2015 12:09:52	ERROR	Error importing SimplydebridCom: cannot import name fixup
1047	23.10.2015 12:09:52	ERROR	Error importing IfolderRu: cannot import name fixup
1048	23.10.2015 12:09:52	ERROR	Error importing VkCom: cannot import name fixup
1049	23.10.2015 12:09:52	ERROR	Error importing HugefilesNet: cannot import name fixup
1050	23.10.2015 12:09:52	ERROR	Error importing ExashareCom: cannot import name fixup
1051	23.10.2015 12:09:52	ERROR	Error importing RehostTo: cannot import name fixup
1052	23.10.2015 12:09:52	ERROR	Error importing Keep2ShareCc: cannot import name fixup
1053	23.10.2015 12:09:52	ERROR	Error importing SafesharingEu: cannot import name fixup
1054	23.10.2015 12:09:52	ERROR	Error importing QuickshareCz: cannot import name fixup
1055	23.10.2015 12:09:52	ERROR	Error importing FastixRu: cannot import name fixup
1056	23.10.2015 12:09:52	ERROR	Error importing YadiSk: cannot import name fixup
1057	23.10.2015 12:09:52	ERROR	Error importing CrockoCom: cannot import name fixup
1058	23.10.2015 12:09:52	ERROR	Error importing ShareonlineBiz: cannot import name fixup
1059	23.10.2015 12:09:52	ERROR	Error importing FileomCom: cannot import name fixup
1060	23.10.2015 12:09:52	ERROR	Error importing UpstoreNet: cannot import name fixup
1061	23.10.2015 12:09:52	ERROR	Error importing KingfilesNet: cannot import name fixup
1062	23.10.2015 12:09:52	ERROR	Error importing AndroidfilehostCom: cannot import name fixup
1063	23.10.2015 12:09:52	ERROR	Error importing VimeoCom: cannot import name fixup
1064	23.10.2015 12:09:52	ERROR	Error importing CramitIn: cannot import name fixup
1065	23.10.2015 12:09:52	ERROR	Error importing HellshareCz: cannot import name fixup
1066	23.10.2015 12:09:52	ERROR	Error importing WebshareCz: cannot import name fixup
1067	23.10.2015 12:09:52	ERROR	Error importing DropboxCom: cannot import name fixup
1068	23.10.2015 12:09:52	ERROR	Error importing TwoSharedCom: cannot import name fixup
1069	23.10.2015 12:09:52	ERROR	Error importing SecureUploadEu: cannot import name fixup
1070	23.10.2015 12:09:52	ERROR	Error importing DateiTo: cannot import name fixup
1071	23.10.2015 12:09:52	ERROR	Error importing DevhostSt: cannot import name fixup
1072	23.10.2015 12:09:52	ERROR	Error importing OneFichierCom: cannot import name fixup
1073	23.10.2015 12:09:52	ERROR	Error importing EdiskCz: cannot import name fixup
1074	23.10.2015 12:09:52	ERROR	Error importing BezvadataCz: cannot import name fixup
1075	23.10.2015 12:09:52	ERROR	Error importing NarodRu: cannot import name fixup
1076	23.10.2015 12:09:52	ERROR	Error importing RapidgatorNet: cannot import name fixup
1077	23.10.2015 12:09:52	ERROR	Error importing JunocloudMe: cannot import name fixup
1078	23.10.2015 12:09:52	ERROR	Error importing DebridItaliaCom: cannot import name fixup
1079	23.10.2015 12:09:52	ERROR	Error importing UnibytesCom: cannot import name fixup
1080	23.10.2015 12:09:52	ERROR	Error importing OpenloadIo: cannot import name fixup
1081	23.10.2015 12:09:52	ERROR	Error importing FilerioCom: cannot import name fixup
1082	23.10.2015 12:09:52	ERROR	Error importing UploadheroCom: cannot import name fixup
1083	23.10.2015 12:09:52	ERROR	Error importing SizedriveCom: cannot import name fixup
1084	23.10.2015 12:09:52	ERROR	Error importing FilerNet: cannot import name fixup
1085	23.10.2015 12:09:52	ERROR	Error importing RapiduNet: cannot import name fixup
1086	23.10.2015 12:09:52	ERROR	Error importing BitshareCom: cannot import name fixup
1087	23.10.2015 12:09:52	ERROR	Error importing LinksnappyCom: cannot import name fixup
1088	23.10.2015 12:09:52	ERROR	Error importing FshareVn: cannot import name fixup
1089	23.10.2015 12:09:52	ERROR	Error importing LuckyShareNet: cannot import name fixup
1090	23.10.2015 12:09:52	ERROR	Error importing DataportCz: cannot import name fixup
1091	23.10.2015 12:09:52	ERROR	Error importing FileuploadNet: cannot import name fixup
1092	23.10.2015 12:09:52	ERROR	Error importing FileboomMe: cannot import name fixup
1093	23.10.2015 12:09:52	ERROR	Error importing RyushareCom: No module named XFileSharingPro
1094	23.10.2015 12:09:52	ERROR	Error importing EuroshareEu: cannot import name fixup
1095	23.10.2015 12:09:52	ERROR	Error importing FourSharedCom: cannot import name fixup
1096	23.10.2015 12:09:52	ERROR	Error importing EasybytezCom: cannot import name fixup
1097	23.10.2015 12:09:52	ERROR	Error importing FileserveCom: cannot import name fixup
1098	23.10.2015 12:09:52	ERROR	Error importing CatShareNet: cannot import name fixup
1099	23.10.2015 12:09:52	ERROR	Error importing PremiumTo: cannot import name fixup
1100	23.10.2015 12:09:52	ERROR	Error importing OverLoadMe: cannot import name fixup
1101	23.10.2015 12:09:52	ERROR	Error importing DataHu: cannot import name fixup
1102	23.10.2015 12:09:52	ERROR	Error importing BasketbuildCom: cannot import name fixup
1103	23.10.2015 12:09:52	ERROR	Error importing FileSharkPl: cannot import name fixup
1104	23.10.2015 12:09:52	ERROR	Error importing GamefrontCom: cannot import name fixup
1105	23.10.2015 12:09:52	ERROR	Error importing SimplyPremiumCom: cannot import name fixup
1106	23.10.2015 12:09:52	ERROR	Error importing WrzucTo: cannot import name fixup
1107	23.10.2015 12:09:52	ERROR	Error importing FilejungleCom: cannot import name fixup
1108	23.10.2015 12:09:52	ERROR	Error importing DepositfilesCom: cannot import name fixup
1109	23.10.2015 12:09:52	ERROR	Error importing DlFreeFr: cannot import name fixup
1110	23.10.2015 12:09:52	ERROR	Error importing GoogledriveCom: cannot import name fixup
1111	23.10.2015 12:09:52	ERROR	Error importing ExtabitCom: cannot import name fixup
1112	23.10.2015 12:09:52	INFO	ADDON XFileSharing: Handle any hoster site on the web!
1113	23.10.2015 12:09:52	INFO	ADDON XFileSharing: Handle any crypter site on the web!
1114	23.10.2015 12:09:52	INFO	pyLoad is up and running
1115	23.10.2015 12:09:52	INFO	ADDON UpdateManager: pyLoad is up to date!
1116	23.10.2015 12:09:53	INFO	ADDON UpdateManager: All plugins are up to date!

**Comment by Gutz-Pilz** [comment]
Same here.

**Comment by Eisfreak7** [comment]
Same problem here (except I didn't update manually).
Deleting the userplugins fodler and reinstalling all plugins didn't help.
