### ISSUE TITLE
Oboom pycurl error 35: gnutls_handshake() failed: Handshake failed

### ISSUE THREAD

**Issue by OzzieIsaacs** [pyload/pyload#2104]
When starting a download from Oboom the above error message occours

The debug log shows the following:
pyLoad 0.4.9 Debug Report of OboomCom 0.40 

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/srv/pyload/userplugins/internal/Base.py", line 281, in preprocessing
    return self._process(*args, **kwargs)
  File "/srv/pyload/userplugins/internal/Hoster.py", line 92, in _process
    self.process(self.pyfile)
  File "/srv/pyload/userplugins/hoster/OboomCom.py", line 38, in process
    self.html = self.load(pyfile.url)
  File "/srv/pyload/userplugins/internal/Base.py", line 490, in load
    return super(Base, self).load(*args, **kwargs)
  File "/srv/pyload/userplugins/internal/Plugin.py", line 236, in load
    html = req.load(url, get, post, ref, bool(cookies), just_header, multipart, decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/usr/share/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 202, in load
    self.c.perform()
error: (35, 'gnutls_handshake() failed: Handshake failed')
 

FRAMESTACK:

Frame preprocessing in /srv/pyload/userplugins/internal/Base.py at line 281
	                self = <Hoster OboomCom>
	                args = (<DownloadThread(Thread-2, started daemon 140201933657856)>,)
	              kwargs = {}

Frame _process in /srv/pyload/userplugins/internal/Hoster.py at line 102
	                self = <Hoster OboomCom>
	              thread = <DownloadThread(Thread-2, started daemon 140201933657856)>

Frame process in /srv/pyload/userplugins/hoster/OboomCom.py at line 38
	              pyfile = PyFile 3: xxxx.yyy@OboomCom
	                self = <Hoster OboomCom>

Frame load in /srv/pyload/userplugins/internal/Base.py at line 490
	                self = <Hoster OboomCom>
	                args = (u'https://www.oboom.com/??????/xxxx.yyy',)
	              kwargs = {}

Frame load in /srv/pyload/userplugins/internal/Plugin.py at line 236
	            redirect = True
	             cookies = True
	                 val = False
	                 get = {}
	                 url = u'https://www.oboom.com/??????/xxxx.yyy'
	                self = <Hoster OboomCom>
	                 req = <module.network.Browser.Browser object at 0x7f832780a668>
	              decode = True
	           multipart = False
	                 key = 'just_header'
	                post = {}
	                 ref = True
	         just_header = False

Frame load in /usr/share/pyload/module/network/Browser.py at line 97
	                self = <module.network.Browser.Browser object at 0x7f832780a668>
	                args = (u'https://www.oboom.com/??????/xxxx.yyy',
 {},
 {},
 True,
 True,
 False,
 False,
 True)
	              kwargs = {}

Frame load in /usr/share/pyload/module/network/HTTPRequest.py at line 202
	             cookies = True
	                 get = {}
	                 url = u'https://www.oboom.com/??????/xxxx.yyy'
	                self = <module.network.HTTPRequest.HTTPRequest instance at 0x7f8327815c20>
	              decode = True
	             referer = True
	           multipart = False
	                post = {}
	         just_header = False

PLUGIN OBJECT DUMP: 

	       RECAPTCHA_KEY = '6LdqpO0SAAAAAJGHXo63HyalP7H4qlRs_vff0kJX'
	    URL_REPLACEMENTS = []
	             account = False
	             captcha = <Captcha Captcha>
	         chunk_limit = 1
	           classname = 'OboomCom'
	                html = ''
	                info = {'name': 'xxxx.yyy',
 'pattern': {'ID': u'??????'},
 'size': 0,
 'status': 3,
 'url': u'https://www.oboom.com/??????/xxxx.yyy'}
	                  js = <module.common.JsEngine.JsEngine instance at 0x7f834c699950>
	          last_check = None
	       last_download = None
	           last_html = None
	             limitDL = 0
	             multiDL = False
	             premium = False
	              pyfile = PyFile 3: xxxx.yyy@OboomCom
	              pyload = <__main__.Core object at 0x7f834f566b90>
	                 req = <module.network.Browser.Browser object at 0x7f832780a668>
	        restart_free = False
	     resume_download = False
	             retries = {}
	              thread = <DownloadThread(Thread-2, started daemon 140201933657856)>
	                user = None
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 0
	               abort = False
	              active = False
	               error = ''
	                  id = 3
	                lock = <_RLock owner=None count=0>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x7f834f582758>
	         maxprogress = 100
	                name = 'xxxx.yyy'
	               order = 0
	           packageid = 406
	              plugin = <Hoster OboomCom>
	         pluginclass = <class 'userplugins.hoster.OboomCom.OboomCom'>
	        pluginmodule = <module 'userplugins.hoster.OboomCom' from '/srv/pyload/userplugins/hoster/OboomCom.pyc'>
	          pluginname = u'OboomCom'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'https://www.oboom.com/??????/xxxx.yyy'
	           waitUntil = 0

CONFIG: 

{'activated': {'desc': 'Activated', 'type': 'bool', 'value': True},
 'desc': 'OboomCom',
 'outline': 'Oboom.com hoster plugin'}

Pyload is running on:
Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64)
pycurl==7.19.3

**Comment by GammaC0de** [comment]
known bug in pycurl, see https://github.com/xmendez/wfuzz/wiki/PyCurlSSLBug

**Comment by OzzieIsaacs** [comment]
Thank you for the help.

This hint solved the problem

**Comment by GammaC0de** [comment]
:+1:
