### ISSUE TITLE
Easybytez download error

### ISSUE THREAD

**Issue by davboc** [pyload/pyload#2105]
after latest update, this is the debug log:

```

198	24.10.2015 14:14:08	DEBUG	All downloads processed
197	24.10.2015 14:14:07	INFO	ADDON UnSkipOnFail: No duplicates found
196	24.10.2015 14:14:07	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: filename.part01.rar (pid:93)
195	24.10.2015 14:14:07	INFO	Debug Report written to debug_XFileSharing_24-10-2015_14-14-07.txt
194	24.10.2015 14:14:07	DEBUG	Error creating zip file: [Errno 2] No such file or directory: 'tmp/XFileSharing'
193	24.10.2015 14:14:07	WARNING	Download failed: filename.part01.rar | global name 'SimpleCrypter' is not defined
192	24.10.2015 14:14:07	DEBUG	HOSTER XFileSharing[845]: WwwEasybytezCom | Config option `use_premium` not found, use default `True`
191	24.10.2015 14:14:07	WARNING	HOSTER XFileSharing[845]: WwwEasybytezCom | Plugin may be unstable
190	24.10.2015 14:14:07	DEBUG	HOSTER XFileSharing[845]: WwwEasybytezCom | Plugin status: testing
189	24.10.2015 14:14:07	DEBUG	HOSTER XFileSharing[845]: WwwEasybytezCom | Plugin version: 0.61
188	24.10.2015 14:14:07	INFO	Download starts: filename.part01.rar
187	24.10.2015 14:14:07	DEBUG	Finished Info Fetching for XFileSharing
186	24.10.2015 14:14:07	INFO	Added package test containing 1 links
185	24.10.2015 14:14:07	DEBUG	Run Info Fetching for XFileSharing 

```

**Comment by GammaC0de** [comment]
@davboc please try #2107

**Comment by davboc** [comment]
Yes @GammaC0de now it works, thanks!

I can't understand two things:
1) now in queue list XFileSharing replace all hosters name, is that normal?
2) why it download more files at same time when easybytez doesn't allow more than one (sometimes two) downloads at same time?

thanks!

**Comment by GammaC0de** [comment]
> 1) now in queue list XFileSharing replace all hosters name, is that normal?

Do you mean like in #2103?
If so, this is intent and is a side effect of XFileSharing  parsing all the modules.

> why it download more files at same time when easybytez doesn't allow more than one (sometimes two) downloads at same time?

I don't quite understand what do you mean by that, please elaborate.

**Comment by davboc** [comment]
Sorry @GammaC0de, my English is bad.
If I add a package with three easybytez links, pyload starts download of all three links at same time, but free account of easybytez doesn't allow more than one download simultaneously, I can't understand this behavior...

**Comment by GammaC0de** [comment]
check #2108

**Comment by davboc** [comment]
@GammaC0de mmm no, this doesn't work, pyload still launch all downloads in the package

**Comment by GammaC0de** [comment]
Please send sample URLs

**Comment by davboc** [comment]
```
http://www.easybytez.com/zf26a2dujhx9/Jessabelle (2014) BDRip 576p.part05.rar
http://www.easybytez.com/7rh9ksw27owu/Jessabelle (2014) BDRip 576p.part05.rev
http://www.easybytez.com/cdgnxl11v836/Jessabelle (2014) BDRip 576p.part06.rar
http://www.easybytez.com/7nc9jxoaj406/Jessabelle (2014) BDRip 576p.part06.rev
```

**Comment by GammaC0de** [comment]
@vuolter adding 
```python
super(XFileSharing, self).setup()
```

to the end of [setup()](https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/XFileSharing.py#L37) function solves the problem by calling `XFSHoster`'s `setup()` function.

BUT it does not call `EasybytezCom` `setup()` function if I add one..
How to solve this?

**Comment by GammaC0de** [comment]
@vuolter can you check the issue I have mentioned above?

**Comment by vuolter** [comment]
@GammaC0de I'll take a look at that later this night.

**Comment by GammaC0de** [comment]
:+1:

**Comment by vuolter** [comment]
Sorry guys, this all week I'll be out and I can not take care of the project. :(

**Comment by sraedler** [comment]
Same like #2113 right?
