### ISSUE TITLE
ShareOnlineBiz - Config option `chk_filesize` not found, use default `None`

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#2112]
In debug Mode i got this error after downloading:
<pre><code>
25.10.2015 19:08:53 INFO      HOSTER ShareonlineBiz[3417]: Checking downloaded file...
25.10.2015 19:08:53 DEBUG     HOSTER ShareonlineBiz[3417]: Config option `chk_filesize` not found, use default `None`
25.10.2015 19:08:53 INFO      HOSTER ShareonlineBiz[3417]: File is OK
25.10.2015 19:08:53 DEBUG     HOSTER ShareonlineBiz[3417]: Performing default check rules...
25.10.2015 19:08:53 DEBUG     HOSTER ShareonlineBiz[3417]: Performing custom check rules...
25.10.2015 19:08:53 INFO      Download finished: longmire303.part4.rar
</code></pre>

**Comment by joberreiter** [comment]
Hm. I don't see an error, just info and debug lines ...
