### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by syss** [pyload/pyload#2117]
When I start from command line I get a lot of these errors lately. I am not sure if they appear random or not. Strange thing is that these do not appear in the log files, only in the CLI.

After a while the webinterface gets unresponsive

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 197, in send_preamble
    self._write('Server: %s\r\n' % self.server_software)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by joberreiter** [comment]
> Strange thing is that these do not appear in the log files, only in the CLI.

Tracebacks originate from python, not from pyload. So it is normal that python itself don't make use of the pyload log.
Some errors are catched within pyload itself (if there is a possibility to get those errors), in this case the pyload log holds the error, before the traceback is shown on the CLI _and_ pyLoad continues.

But the traceback is always shown only in CLI.

**Comment by joberreiter** [comment]
The broken pipe error occurres usually if you request is blocked or takes too long and after request-side timeout (client), it'll closes the connection. When the respond-side (server) try to write the socket, it will throw a pipe broken error.

This may indicate network performance problems or firewall problems, or ...

**Comment by syss** [comment]
thank you for the information on this error and where it comes from.

pyload runs on a single core raspberry pi which also runs other stuff.
I think the problem occours when it unpacks archives and has a load of 4+
Is there a way to increase the timeouts to avoid these problems?

**Comment by GammaC0de** [comment]
@syss try setting `self.priority` in 'call_cmd' of the unpacker .py to somting between -1 to -20.

**Comment by GammaC0de** [comment]
acctually, there is a "Process priority" config parameter in `ExtractArchive`.

**Comment by syss** [comment]
@GammaC0de thank you for the hint, i set it to -20. 

I think that this can be closed, because the error is on my side: slow hardware ;)

**Comment by GammaC0de** [comment]
:+1: 
Only you or **vulter** can close this issue, so please do.
