### ISSUE TITLE
[Easybytez] premium faild

### ISSUE THREAD

**Issue by erse80** [pyload/pyload#2126]
i have premium account in config -> account it's confirmed account is active and valid butPremium download faild

27.10.2015 22:37:25 INFO      Download starts: the.100.s01e07.La.Tempesta.BDMux.ITA.part1.rev
27.10.2015 22:37:25 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | Plugin version: 0.63
27.10.2015 22:37:25 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | Plugin status: testing
27.10.2015 22:37:25 WARNING   HOSTER XFileSharing[2754]: WwwEasybytezCom | Plugin may be unstable
27.10.2015 22:37:25 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | Config option `use_premium` not found, use default `True`
27.10.2015 22:37:25 INFO      HOSTER XFileSharing[2754]: WwwEasybytezCom | Grabbing link info...
27.10.2015 22:37:25 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | Link info: {'status': 2, 'pattern': {'S': u'105.0', 'U': u'MB', 'N': u'the.100.s01e07.La.Tempesta.BDMux.ITA.part1.rev'}, 'size': 110100480, 'url': u'http://www.easybytez.com/9b94wgz8kxih', 'name': u'the.100.s01e07.La.Tempesta.BDMux.ITA.part1.rev'}
27.10.2015 22:37:25 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | Previous link info: {}
27.10.2015 22:37:25 INFO      HOSTER XFileSharing[2754]: WwwEasybytezCom | Link name: the.100.s01e07.La.Tempesta.BDMux.ITA.part1.rev
27.10.2015 22:37:25 INFO      HOSTER XFileSharing[2754]: WwwEasybytezCom | Link size: 105.00 MiB (110100480 bytes)
27.10.2015 22:37:25 INFO      HOSTER XFileSharing[2754]: WwwEasybytezCom | Link status: online
27.10.2015 22:37:25 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | LOAD URL http://www.easybytez.com/9b94wgz8kxih | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
27.10.2015 22:37:25 INFO      HOSTER XFileSharing[2754]: WwwEasybytezCom | Processing as free download...
27.10.2015 22:37:25 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | Getting download link #1...
27.10.2015 22:37:25 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | {u'method_premium': u'Premium Download', u'usr_login': '', u'referer': '', u'fname': u'the.100.s01e07.La.Tempesta.BDMux.ITA.part1.rev', u'method_free': u'Free Download', u'id': u'9b94wgz8kxih', u'op': u'download1'}
27.10.2015 22:37:25 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | LOAD URL http://www.easybytez.com/9b94wgz8kxih | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'usr_login': '', u'referer': '', u'fname': u'the.100.s01e07.La.Tempesta.BDMux.ITA.part1.rev', u'method_free': 'Free Download', u'id': u'9b94wgz8kxih', u'op': u'download1'} | ref=True | just_header=False
27.10.2015 22:37:26 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | Getting download link #2...
27.10.2015 22:37:26 WARNING   HOSTER XFileSharing[2754]: WwwEasybytezCom | You have reached the download-limit: 512 Mb for last 1 days
27.10.2015 22:37:26 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | Config option `max_wait` not found, use default `10`
27.10.2015 22:37:26 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | WAIT set to timestamp 1445986860.118270 | Previous waitUntil: 0.000000
27.10.2015 22:37:26 DEBUG     HOSTER XFileSharing[2754]: WwwEasybytezCom | RECONNECT  required | Previous wantReconnect: False
27.10.2015 22:37:26 INFO      HOSTER XFileSharing[2754]: WwwEasybytezCom | Waiting 1 hours, 23 minutes, 33 seconds...
27.10.2015 22:37:26 INFO      HOSTER XFileSharing[2754]: WwwEasybytezCom | Requiring reconnection...

**Comment by vuolter** [comment]
Checking...

**Comment by erse80** [comment]
any solutions?

**Comment by vuolter** [comment]
Disable the XFSharing addon.
