### ISSUE TITLE
Share-online.biz dosen't work

### ISSUE THREAD

**Issue by Klaaner** [pyload/pyload#2130]
Since the Plugin-Update to "ShareonlineBiz (v0.61 -> v0.63)" and "CRYPTER ShareLinksBiz (v1.19 -> v1.20)" download won't start:

28.10.2015 11:02:41	INFO	ADDON UnSkipOnFail: No duplicates found
28.10.2015 11:02:41	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: ...part07.rar (pid:46)
28.10.2015 11:02:41	WARNING	Download failed: ...part07.rar | ReCaptcha data not found
28.10.2015 11:02:37	INFO	HOSTER ShareonlineBiz[969]: Waiting 3 seconds...
28.10.2015 11:02:37	INFO	HOSTER ShareonlineBiz[969]: Processing as free download...
28.10.2015 11:02:37	INFO	HOSTER ShareonlineBiz[969]: Direct download link not found
28.10.2015 11:02:37	INFO	HOSTER ShareonlineBiz[969]: Looking for direct download link...
28.10.2015 11:02:37	INFO	HOSTER ShareonlineBiz[969]: Link status: online
28.10.2015 11:02:37	INFO	HOSTER ShareonlineBiz[969]: Link size: 101.00 MiB (105906176 bytes)
28.10.2015 11:02:37	INFO	HOSTER ShareonlineBiz[969]: Link name: ...part07.rar
28.10.2015 11:02:37	INFO	HOSTER ShareonlineBiz[969]: Grabbing link info...
28.10.2015 11:02:37	WARNING	HOSTER ShareonlineBiz[969]: Plugin may be unstable
28.10.2015 11:02:37	INFO	Download starts: ...

**Comment by benchlor** [comment]
I had the same error and did the following to fix it (under linux):

git clone https://github.com/pyload/pyload.git
/etc/init.d/pyload stop
mv /var/lib/pyload/userplugins /var/lib/pyload/userplugins-old
cp pyload/module/plugins/ -R /varlib/pyload/userplugins
chmod 777 /var/lib/pyload/userplugins -R
/etc/init.d/pyload start

I've got no idea why this is working, but hopefully it helps other people, too?

**Comment by joberreiter** [comment]
ShareonlineBiz (v0.63) finds the recaptcha data (both first and second challenge) at my installation, so are you able to reproduce it?
Please enable debug mode, check again and post the log with debugging enabled.

@benchlor
You're just downloading the latest version of the 'stable' branch (by the way: the daemon should be stopped before cloning the git repo!). Copying the plugins with `cp pyload/module/plugins/ -R /var/lib/pyload/userplugins` does not change the way pyload works and is unneccessary.
`userplugins` is just the directory for own plugins and for new updated plugins downloaded by the automatic updater. If you clone the branch you have got the newest plugins, no need to copy it again.

**Comment by Klaaner** [comment]
176763	30.10.2015 16:59:46	INFO	ADDON UnSkipOnFail: No duplicates found
176762	30.10.2015 16:59:46	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: .part07.rar (pid:45)
176761	30.10.2015 16:59:46	WARNING	Download failed: .part07.rar | ReCaptcha data not found
176760	30.10.2015 16:59:42	INFO	HOSTER ShareonlineBiz[954]: Waiting 3 seconds...
176759	30.10.2015 16:59:42	INFO	HOSTER ShareonlineBiz[954]: Processing as free download...
176758	30.10.2015 16:59:42	INFO	HOSTER ShareonlineBiz[954]: Direct download link not found
176757	30.10.2015 16:59:42	INFO	HOSTER ShareonlineBiz[954]: Looking for direct download link...
176756	30.10.2015 16:59:42	INFO	HOSTER ShareonlineBiz[954]: Link status: online
176755	30.10.2015 16:59:42	INFO	HOSTER ShareonlineBiz[954]: Link size: 101.00 MiB (105906176 bytes)
176754	30.10.2015 16:59:42	INFO	HOSTER ShareonlineBiz[954]: Link name: .rar
176753	30.10.2015 16:59:42	INFO	HOSTER ShareonlineBiz[954]: Grabbing link info...
176752	30.10.2015 16:59:42	WARNING	HOSTER ShareonlineBiz[954]: Plugin may be unstable
176751	30.10.2015 16:59:42	INFO	Download starts: 1.part07.rar
176750	30.10.2015 16:59:40	INFO	ADDON UnSkipOnFail: No duplicates found
176749	30.10.2015 16:59:40	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: .part06.rar (pid:45)
176748	30.10.2015 16:59:40	WARNING	Download failed: .part06.rar | ReCaptcha data not found
176747	30.10.2015 16:59:36	INFO	HOSTER ShareonlineBiz[953]: Waiting 3 seconds...
176746	30.10.2015 16:59:36	INFO	HOSTER ShareonlineBiz[953]: Processing as free download...
176745	30.10.2015 16:59:36	INFO	HOSTER ShareonlineBiz[953]: Direct download link not found
176744	30.10.2015 16:59:36	INFO	HOSTER ShareonlineBiz[953]: Looking for direct download link...
176743	30.10.2015 16:59:36	INFO	HOSTER ShareonlineBiz[953]: Link status: online
176742	30.10.2015 16:59:36	INFO	HOSTER ShareonlineBiz[953]: Link size: 101.00 MiB (105906176 bytes)
176741	30.10.2015 16:59:36	INFO	HOSTER ShareonlineBiz[953]: Link name: .part06.rar
176740	30.10.2015 16:59:36	INFO	HOSTER ShareonlineBiz[953]: Grabbing link info...
176739	30.10.2015 16:59:36	WARNING	HOSTER ShareonlineBiz[953]: Plugin may be unstable
176738	30.10.2015 16:59:36	INFO	Download starts: .part06.rar
176737	30.10.2015 16:59:34	INFO	ADDON UnSkipOnFail: No duplicates found
176736	30.10.2015 16:59:34	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: .part05.rar (pid:45)
176735	30.10.2015 16:59:34	WARNING	Download failed: .part05.rar | ReCaptcha data not found
176734	30.10.2015 16:59:30	INFO	HOSTER ShareonlineBiz[952]: Waiting 3 seconds...
176733	30.10.2015 16:59:30	INFO	HOSTER ShareonlineBiz[952]: Processing as free download...
176732	30.10.2015 16:59:30	INFO	HOSTER ShareonlineBiz[952]: Direct download link not found
176731	30.10.2015 16:59:30	INFO	HOSTER ShareonlineBiz[952]: Looking for direct download link...
176730	30.10.2015 16:59:30	INFO	HOSTER ShareonlineBiz[952]: Link status: online 
176729	30.10.2015 16:59:30	INFO	HOSTER ShareonlineBiz[952]: Link size: 101.00 MiB (105906176 bytes)
176728	30.10.2015 16:59:30	INFO	HOSTER ShareonlineBiz[952]: Link name: .part05.rar
176727	30.10.2015 16:59:30	INFO	HOSTER ShareonlineBiz[952]: Grabbing link info...
176726	30.10.2015 16:59:30	WARNING	HOSTER ShareonlineBiz[952]: Plugin may be unstable
176725	30.10.2015 16:59:30	INFO	Download starts: .part05.rar 


Nothing else in the log-files. Debug Mode was enabled

**Comment by Lalarian** [comment]
From my trials I learned: copying the older versions of all plugins fixes the bug for shareonline. But not for zippyshare and uploaded.to.

**Comment by joberreiter** [comment]
@Klaaner
If debug mode were enabled, there should be debug lines in the log, e.g.
```
31.10.2015 13:21:07 DEBUG     HOSTER ShareonlineBiz[13807]: Plugin version: 0.63
31.10.2015 13:21:07 DEBUG     HOSTER ShareonlineBiz[13807]: Plugin status: testing
31.10.2015 13:21:07 WARNING   HOSTER ShareonlineBiz[13807]: Plugin may be unstable
31.10.2015 13:21:07 INFO      HOSTER ShareonlineBiz[13807]: Grabbing link info...
31.10.2015 13:21:07 DEBUG     HOSTER ShareonlineBiz[13807]: Link info: {'status': 2, 'size': 159035045, 'name': 'testfile.rar', 'url': u'http://www.share-online.biz/dl/FEPTETWNZHT1', 'pattern': {'ID': u'FEPTETWNZHT1'}, 'md5': '3906dab3d1258fc7484bf1b7b9a1ec0c', 'fileid': 'FEPTETWNZHT1'}
31.10.2015 13:21:07 DEBUG     HOSTER ShareonlineBiz[13807]: Previous link info: {}
31.10.2015 13:21:07 INFO      HOSTER ShareonlineBiz[13807]: Link name: testfile.rar
31.10.2015 13:21:07 INFO      HOSTER ShareonlineBiz[13807]: Link size: 151.67 MiB (159035045 bytes)
31.10.2015 13:21:07 INFO      HOSTER ShareonlineBiz[13807]: Link status: online
31.10.2015 13:21:07 INFO      HOSTER ShareonlineBiz[13807]: Looking for direct download link...
31.10.2015 13:21:07 DEBUG     HOSTER ShareonlineBiz[13807]: Redirect #0 to: http://www.share-online.biz/dl/FEPTETWNZHT1
31.10.2015 13:21:07 DEBUG     HOSTER ShareonlineBiz[13807]: LOAD URL http://www.share-online.biz/dl/FEPTETWNZHT1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
31.10.2015 13:21:07 INFO      HOSTER ShareonlineBiz[13807]: Direct download link not found
31.10.2015 13:21:07 DEBUG     HOSTER ShareonlineBiz[13807]: LOAD URL http://www.share-online.biz/dl/FEPTETWNZHT1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
31.10.2015 13:21:07 INFO      HOSTER ShareonlineBiz[13807]: Processing as free download...
31.10.2015 13:21:07 DEBUG     HOSTER ShareonlineBiz[13807]: WAIT set to timestamp 1446294071.821931 | Previous waitUntil: 0.000000
31.10.2015 13:21:07 INFO      HOSTER ShareonlineBiz[13807]: Waiting 3 seconds...
```
Have you restarted pyload after enabling debug mode?

**Comment by Klaaner** [comment]
Hmpf. I knew there was something else... :-(

177343	31.10.2015 13:33:48	INFO	ADDON UnSkipOnFail: No duplicates found
177342	31.10.2015 13:33:48	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of:  .part23.rar (pid:33)
177341	31.10.2015 13:33:48	WARNING	Download failed:  .part23.rar | ReCaptcha data not found
177340	31.10.2015 13:33:48	DEBUG	HOSTER ShareonlineBiz[684]: Config option `fallback` not found, use default `True`
177339	31.10.2015 13:33:48	DEBUG	HOSTER ShareonlineBiz[684]: LOAD URL http://www.share-online.biz/dl/ .../free/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'dl_free': '1', 'choice': 'free'} | ref=True | just_header=False
177338	31.10.2015 13:33:44	INFO	HOSTER ShareonlineBiz[684]: Waiting 3 seconds...
177337	31.10.2015 13:33:44	DEBUG	HOSTER ShareonlineBiz[684]: WAIT set to timestamp 1446294828.035698 | Previous waitUntil: 0.000000
177336	31.10.2015 13:33:44	INFO	HOSTER ShareonlineBiz[684]: Processing as free download...
177335	31.10.2015 13:33:43	DEBUG	HOSTER ShareonlineBiz[684]: LOAD URL http://www.share-online.biz/dl/... | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
177334	31.10.2015 13:33:43	INFO	HOSTER ShareonlineBiz[684]: Direct download link not found
177333	31.10.2015 13:33:43	DEBUG	HOSTER ShareonlineBiz[684]: LOAD URL http://www.share-online.biz/dl/... | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
177332	31.10.2015 13:33:43	DEBUG	HOSTER ShareonlineBiz[684]: Redirect #0 to: http://www.share-online.biz/dl/...
177331	31.10.2015 13:33:43	INFO	HOSTER ShareonlineBiz[684]: Looking for direct download link...
177330	31.10.2015 13:33:43	INFO	HOSTER ShareonlineBiz[684]: Link status: online
177329	31.10.2015 13:33:43	INFO	HOSTER ShareonlineBiz[684]: Link size: 101.00 MiB (105906176 bytes)
177328	31.10.2015 13:33:43	INFO	HOSTER ShareonlineBiz[684]: Link name:  .part23.rar
177327	31.10.2015 13:33:43	DEBUG	HOSTER ShareonlineBiz[684]: Previous link info: {}
177326	31.10.2015 13:33:43	DEBUG	HOSTER ShareonlineBiz[684]: Link info: {'status': 2, 'size': 105906176, 'name': ' .part23.rar', 'url': u'http://www.share-online.biz/dl/...', 'pattern': {'ID': u'...'}, 'md5': '7816a7d45d25ccb13251853b576f9d79', 'fileid': ' ...'}
177325	31.10.2015 13:33:43	INFO	HOSTER ShareonlineBiz[684]: Grabbing link info...
177324	31.10.2015 13:33:43	WARNING	HOSTER ShareonlineBiz[684]: Plugin may be unstable
177323	31.10.2015 13:33:43	DEBUG	HOSTER ShareonlineBiz[684]: Plugin status: testing
177322	31.10.2015 13:33:43	DEBUG	HOSTER ShareonlineBiz[684]: Plugin version: 0.63
177321	31.10.2015 13:33:43	INFO	Download starts:  .part23.rar
177320	31.10.2015 13:33:42	INFO	ADDON UnSkipOnFail: No duplicates found
177319	31.10.2015 13:33:42	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of:  .part22.rar (pid:33)
177318	31.10.2015 13:33:42	WARNING	Download failed:  .part22.rar | ReCaptcha data not found
177317	31.10.2015 13:33:42	DEBUG	HOSTER ShareonlineBiz[683]: Config option `fallback` not found, use default `True`
177316	31.10.2015 13:33:42	DEBUG	HOSTER ShareonlineBiz[683]: LOAD URL http://www.share-online.biz/dl/.../free/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'dl_free': '1', 'choice': 'free'} | ref=True | just_header=False
177315	31.10.2015 13:33:38	INFO	HOSTER ShareonlineBiz[683]: Waiting 3 seconds...
177314	31.10.2015 13:33:38	DEBUG	HOSTER ShareonlineBiz[683]: WAIT set to timestamp 1446294822.094761 | Previous waitUntil: 0.000000
177313	31.10.2015 13:33:38	INFO	HOSTER ShareonlineBiz[683]: Processing as free download...
177312	31.10.2015 13:33:37	DEBUG	HOSTER ShareonlineBiz[683]: LOAD URL http://www.share-online.biz/dl/... | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
177311	31.10.2015 13:33:37	INFO	HOSTER ShareonlineBiz[683]: Direct download link not found
177310	31.10.2015 13:33:37	DEBUG	HOSTER ShareonlineBiz[683]: LOAD URL http://www.share-online.biz/dl/... | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True 
177309	31.10.2015 13:33:37	DEBUG	HOSTER ShareonlineBiz[683]: Redirect #0 to: http://www.share-online.biz/dl/...
177308	31.10.2015 13:33:37	INFO	HOSTER ShareonlineBiz[683]: Looking for direct download link...
177307	31.10.2015 13:33:37	INFO	HOSTER ShareonlineBiz[683]: Link status: online
177306	31.10.2015 13:33:37	INFO	HOSTER ShareonlineBiz[683]: Link size: 101.00 MiB (105906176 bytes)
177305	31.10.2015 13:33:37	INFO	HOSTER ShareonlineBiz[683]: Link name:  .part22.rar
177304	31.10.2015 13:33:37	DEBUG	HOSTER ShareonlineBiz[683]: Previous link info: {}
177303	31.10.2015 13:33:37	DEBUG	HOSTER ShareonlineBiz[683]: Link info: {'status': 2, 'size': 105906176, 'name': '.part22.rar', 'url': u'http://www.share-online.biz/dl/...', 'pattern': {'ID': u'...'}, 'md5': '9255cfeb3b732fad862fabc6f95e1398', 'fileid': '...'}
177302	31.10.2015 13:33:37	INFO	HOSTER ShareonlineBiz[683]: Grabbing link info...
177301	31.10.2015 13:33:37	DEBUG	Redirected import module.plugins.accounts.ShareonlineBiz -> userplugins.accounts.ShareonlineBiz
177300	31.10.2015 13:33:37	WARNING	HOSTER ShareonlineBiz[683]: Plugin may be unstable
177299	31.10.2015 13:33:37	DEBUG	HOSTER ShareonlineBiz[683]: Plugin status: testing
177298	31.10.2015 13:33:37	DEBUG	HOSTER ShareonlineBiz[683]: Plugin version: 0.63
177297	31.10.2015 13:33:37	INFO	Download starts: .part22.rar

**Comment by pipsen** [comment]
I have exactly the same issue since Thursday! ShareOnline and Uploaded affected
Any help?

**Comment by Velociraptor85** [comment]
I have the same issue and a delete+redownload of the userplugin folder did not help

**Comment by Arno-Nymous** [comment]
Please raise the version number when committing new file versions! This can save up lots of hours of investigation.

There were changed a few lines in `../module/plugins/captcha/CaptchaService.py` about two weeks ago, but the version number remained `0.33`, which actually should be `0.34`. Thus, no one got this update and from that point had this nasty error occuring.
Just copy the new code from the aforementioned file from this repo into your PyLoad installation and leave the version number as is.

And to the maintainers of this repo: please, please, please have an eye on your versioning and update the version of this file as soon as possible ;)

**Comment by Lalarian** [comment]
Hello, and thank for your hint!
I've spent hours for finding this problem. Yout hint finally made mypaload working again.
You have made a little mistake, though:

CaptchaService.py isn't located at captchas foldr, butat internal folder.

https://github.com/pyload/pyload/blob/stable/module/plugins/internal/CaptchaService.py

Thanks!

**Comment by k1l** [comment]
https://github.com/pyload/pyload/issues/2130#issuecomment-153559353   
very good spot you guys.
now pyload works again

**Comment by Klaaner** [comment]
Thanks. That also worked for me...

**Comment by UserX82** [comment]
Thank you for the hint.
Worked for me too.

**Comment by joberreiter** [comment]
:+1:
