### ISSUE TITLE
Zippyshare ReCaptcha data not found

### ISSUE THREAD

**Issue by Paxx23** [pyload/pyload#2132]
After updating plugins to the newest version, i discover the following problem:

1	28.10.2015 20:01:17	INFO	HOSTER ZippyshareCom[590]: Link size: 200.00 MiB (209715200 bytes)
2	28.10.2015 20:01:17	INFO	HOSTER ZippyshareCom[590]: Link status: online
3	28.10.2015 20:01:17	INFO	HOSTER ZippyshareCom[590]: Looking for direct download link...
4	28.10.2015 20:01:17	INFO	HOSTER ZippyshareCom[590]: Direct download link not found
5	28.10.2015 20:01:18	INFO	HOSTER ZippyshareCom[590]: Processing as free download...
6	28.10.2015 20:01:18	WARNING	Download failed: ...part06.rar | ReCaptcha data not found
7	28.10.2015 20:01:18	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: ...part06.rar (pid:28)
8	28.10.2015 20:01:18	INFO	ADDON UnSkipOnFail: No duplicates found

Atm, no zippy donwloads working.

**Comment by Lalarian** [comment]
It's same for Uploaded.to.
Also I have noticed, that now there's always just one downloadcurrentlyactive, although there are multiple downloads in queue from different hosters.

**Comment by joberreiter** [comment]
Same as #2130.

**Comment by pipsen** [comment]
Any ideas how to solve this problem? I have the same issue

**Comment by k1l** [comment]
same for me. just got a new git clone and even needed to do manually:
 wget https://raw.githubusercontent.com/pyload/pyload/b72f8fb3d564feb3881d43c2956b1adc238e8b54/module/plugins/hooks/UpdateManager.py 
and put that into .pyload/userplugins/hooks/   to get pyload load the modules at all. but still now have
ReCaptcha data not found  on several hosters

**Comment by Arno-Nymous** [comment]
The issue is not the hoster plugins but a parent captcha plugin which of also the recaptcha plugin inherits from. For the solution see my comment on https://github.com/pyload/pyload/issues/2130.

**Comment by Paxx23** [comment]
Nice Work. Everything working now. Thx!

**Comment by py-nob** [comment]
Please I need your help.
After 6 Hours of searching I have enough.
1 Month bevore this solution works.
After a fresh Installation of Pyload last Weak, I get get only:

WARNING	 HOSTER ZippyshareCom[37]: Plugin may be unstable
989	19.12.2015 19:00:30	INFO	 HOSTER ZippyshareCom[37]: Grabbing link info...
990	19.12.2015 19:00:30	INFO	 HOSTER ZippyshareCom[37]: Link name: tvp-fargo-s02e09-720p.part11.rar
991	19.12.2015 19:00:30	INFO	 HOSTER ZippyshareCom[37]: Link size: 91.62 MiB (96075776 bytes)
992	19.12.2015 19:00:30	INFO	 HOSTER ZippyshareCom[37]: Link status: online
993	19.12.2015 19:00:30	INFO	 HOSTER ZippyshareCom[37]: Looking for direct download link...
994	19.12.2015 19:00:31	INFO	 HOSTER ZippyshareCom[37]: Direct download link not found
995	19.12.2015 19:00:31	INFO	 HOSTER ZippyshareCom[37]: Processing as free download...
996	19.12.2015 19:00:31	WARNING	 CAPTCHA ZippyshareCom[37]: ReCaptcha | Key pattern not found
997	19.12.2015 19:00:31	WARNING	 Download failed: xxxxxxxx.rar | No JS Engine

**Comment by GammaC0de** [comment]
@py-nob You have a totally different issue: `pyLoad` cannot find any Javascript interpreter installed on your system.
`ZippyshareCom` requires a Javascript interpreter to work
