### ISSUE TITLE
No downloads are shown in the ome tab

### ISSUE THREAD

**Issue by KleinerCacher** [pyload/pyload#2134]
I've got pyload installed on wheezy and when going to the home tab i don't see the downloads. I can see the speed they're downloaded and that are 2 active. When going to the Queue-Tab I can see a file with status downloading.

One of the download-packages can't be opend and the ui says "Failed" if I click on it.

I turned on DEBUG-Logs but can't find any Debug or Error-Logentries

**Comment by joberreiter** [comment]
Maybe a corrupt database (no name assigned to a download?).

Do you start pyload via service or CLI? If the former, try it from on the command line, as there are tracebacks of errors shown that pyload is unable to log in its own debug log.

**Comment by KleinerCacher** [comment]
The next morning it worked. Now I have some other issues. I deleted files.db and I'll look what happens. I installed the new version 0.49 but I think it's not as stable as other versions before it. 
Thanks for your fast help. If I've another issue I post it.
