### ISSUE TITLE
question about isdownload function

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2136]
What is the propose of the `resume` parameter in `Hoster.py `'s `isdownload` function?

**Comment by vuolter** [comment]
If  `resume` is  `True`,  `isdownload` loads the final link and checks its header to make sure that points to a file. Links not resumable get an expired session error if `resume` is  not `False`.

**Comment by GammaC0de** [comment]
Hi,
Looking at the code of `isdownload`, if I understand right, setting `resume` to `True` guarantees that there is actually a file behind `url` and not html/text file
There nothing there related to resuming download (i.e. no `Range:` header send/HTTP 206 received)
So I'm a bit confused..
Correct me if I'm wrong

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/fa314e0806c73a3cba9a010b3b53570f16160966
