### ISSUE TITLE
Uploaded plugin failed

### ISSUE THREAD

**Issue by jp776** [pyload/pyload#2139]
Hi,
just a problem with uploaded. Downloads are no longer possible.
I removed all personal thinks ...

<pre><code>4    31.10.2015 14:57:59 INFO    Download starts: yyy.rar
5   31.10.2015 14:57:59 DEBUG   HOSTER UploadedTo[73]: Plugin version: 0.99
6   31.10.2015 14:57:59 DEBUG   HOSTER UploadedTo[73]: Plugin status: testing
7   31.10.2015 14:57:59 WARNING HOSTER UploadedTo[73]: Plugin may be unstable
8   31.10.2015 14:57:59 INFO    ACCOUNT UploadedTo: Grabbing account info for user `yyy`...
9   31.10.2015 14:57:59 DEBUG   ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
10  31.10.2015 14:58:00 DEBUG   ACCOUNT UploadedTo: Size: 514,78 | Unit: gb
11  31.10.2015 14:58:00 DEBUG   ACCOUNT UploadedTo: Account info for user `yyy`: {'login': {'timestamp': 1446277961.572684, 'password': 'yyy', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 539766784L, 'maxtraffic': None, 'validuntil': 1493135880.294741, 'login': 'yyy', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
12  31.10.2015 14:58:00 INFO    HOSTER UploadedTo[73]: Grabbing link info...
13  31.10.2015 14:58:00 DEBUG   HOSTER UploadedTo[73]: Link info: {'status': 2, 'url': u'http://uploaded.net/file/yyy', 'size': 105906176, 'name': 'yyy.rar', 'pattern': {'ID': u'yyy'}}
14  31.10.2015 14:58:00 DEBUG   HOSTER UploadedTo[73]: Previous link info: {}
15  31.10.2015 14:58:01 INFO    HOSTER UploadedTo[73]: Link name: yyy.rar
16  31.10.2015 14:58:01 INFO    HOSTER UploadedTo[73]: Link size: 101.00 MiB (105906176 bytes)
17  31.10.2015 14:58:01 INFO    HOSTER UploadedTo[73]: Link status: online
18  31.10.2015 14:58:01 INFO    HOSTER UploadedTo[73]: Looking for direct download link...
19  31.10.2015 14:58:01 DEBUG   HOSTER UploadedTo[73]: Redirect #0 to: http://uploaded.net/file/yyy
20  31.10.2015 14:58:01 DEBUG   HOSTER UploadedTo[73]: LOAD URL http://uploaded.net/file/yyy| redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
21  31.10.2015 14:58:01 INFO    HOSTER UploadedTo[73]: Direct download link not found
22  31.10.2015 14:58:01 DEBUG   HOSTER UploadedTo[73]: LOAD URL http://uploaded.net/file/yyy| redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
23  31.10.2015 14:58:02 INFO    ACCOUNT UploadedTo: Grabbing account info for user `yyy`...
24  31.10.2015 14:58:02 DEBUG   ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
25  31.10.2015 14:58:02 DEBUG   ACCOUNT UploadedTo: Size: 514,78 | Unit: gb
26  31.10.2015 14:58:02 DEBUG   ACCOUNT UploadedTo: Account info for user `yyy`: {'login': {'timestamp': 1446277961.572684, 'password': 'yyy', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 539766784L, 'maxtraffic': None, 'validuntil': 1493135882.775374, 'login': 'yyy', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
27  31.10.2015 14:58:02 INFO    HOSTER UploadedTo[73]: Filesize: 103424 KiB | Traffic left for user `yyy`: 539766784 KiB
28  31.10.2015 14:58:02 INFO    HOSTER UploadedTo[73]: Processing as premium download...
29  31.10.2015 14:58:02 INFO    HOSTER UploadedTo[73]: Downloading file...
30  31.10.2015 14:58:02 DEBUG   HOSTER UploadedTo[73]: DOWNLOAD URL yyy | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
31  31.10.2015 14:58:02 WARNING Download failed: yyy.rar | 'getpwnam(): name not found: user'
32  31.10.2015 14:58:02 INFO    Debug Report written to debug_UploadedTo_31-10-2015_14-58-02.zip
33  31.10.2015 14:58:02 INFO    ADDON UnSkipOnFail: Looking for skipped duplicates of: yyy.rar (pid:14)
34  31.10.2015 14:58:02 INFO    ADDON UnSkipOnFail: No duplicates found
35  31.10.2015 14:58:02 DEBUG   All downloads processed 
</code></pre>

**Comment by Sync500** [comment]
me too jp. i hope somebody from the developers fix it as fast as possible ^^.

**Comment by georg90** [comment]
same!

**Comment by jp776** [comment]
You lucky. 
Does not work here.

**Comment by m4xcube** [comment]
Same issue on my side, no download will work.
Here is an example file firefox.exe: http://ul.to/8ivb0am5

Log: 
```
953	08.11.2015 14:55:10	INFO	ADDON UpdateManager: pyLoad is up to date!
954	08.11.2015 14:55:11	INFO	ADDON UpdateManager: All plugins are up to date!
955	08.11.2015 14:55:16	INFO	ADDON RestartFailed: Restarting all failed downloads...
956	08.11.2015 14:55:16	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
957	08.11.2015 14:55:18	INFO	Download starts: firefox.exe
958	08.11.2015 14:55:18	WARNING	HOSTER UploadedTo[1702]: Plugin may be unstable
959	08.11.2015 14:55:18	INFO	ACCOUNT UploadedTo: Grabbing account info for user `00000000`...
960	08.11.2015 14:55:19	INFO	ACCOUNT UploadedTo: Grabbing account info for user `00000000`...
961	08.11.2015 14:55:19	INFO	HOSTER UploadedTo[1702]: Grabbing link info...
962	08.11.2015 14:55:19	INFO	HOSTER UploadedTo[1702]: Link name: firefox.exe
963	08.11.2015 14:55:19	INFO	HOSTER UploadedTo[1702]: Link size: 368.16 KiB (377000 bytes)
964	08.11.2015 14:55:19	INFO	HOSTER UploadedTo[1702]: Link status: online
965	08.11.2015 14:55:19	INFO	HOSTER UploadedTo[1702]: Looking for direct download link...
966	08.11.2015 14:55:20	INFO	HOSTER UploadedTo[1702]: Direct download link not found
967	08.11.2015 14:55:20	INFO	ACCOUNT UploadedTo: Grabbing account info for user `00000000`...
968	08.11.2015 14:55:20	INFO	HOSTER UploadedTo[1702]: Filesize: 368 KiB | Traffic left for user `00000000`: 158376 KiB
969	08.11.2015 14:55:20	INFO	HOSTER UploadedTo[1702]: Processing as premium download...
970	08.11.2015 14:55:20	WARNING	Download failed: firefox.exe | Parse error: Premium download link not found | Plugin may be out of date

```

**Comment by Velociraptor85** [comment]
I am guessing this is already solve since the current plugin version is 1.07 https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/UploadedTo.py
