### ISSUE TITLE
OboomCom: pycurl error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by pipsen** [pyload/pyload#2142]
Hi,

when I try to download a Link from Oboom (plugin Version 0.41), I get this error:

01.11.2015 16:38:33	INFO	Download starts: 4AGOSB3P
01.11.2015 16:38:33	WARNING	HOSTER OboomCom[373]: Plugin may be unstable
01.11.2015 16:38:33	INFO	HOSTER OboomCom[373]: Grabbing link info...
01.11.2015 16:38:33	INFO	HOSTER OboomCom[373]: Link name: ABCDEFG
01.11.2015 16:38:33	INFO	HOSTER OboomCom[373]: Link size: N/D
01.11.2015 16:38:33	INFO	HOSTER OboomCom[373]: Link status: eingereiht
01.11.2015 16:38:33	ERROR	pycurl error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
01.11.2015 16:38:33	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: ABCDEFG (pid:20)
01.11.2015 16:38:33	INFO	ADDON UnSkipOnFail: No duplicates found

Any ideas how to overcome?

**Comment by GammaC0de** [comment]
duplicate #2104

see https://github.com/xmendez/wfuzz/wiki/PyCurlSSLBug

**Comment by pipsen** [comment]
Will there be pyload for QNAP update soon, that fixes this problem?

**Comment by GammaC0de** [comment]
This is not part of pyload, pyload uses this 3rd party library (`pycurl`).
Either ask for one at QNAP support site or build/compile it for yourself.
