### ISSUE TITLE
Rapidu.net problem premium download

### ISSUE THREAD

**Issue by ladigb** [pyload/pyload#2146]
Hi
its look like premium is not working is try to download by free user 
i can send premium account by pw for request.

163	01.11.2015 18:42:02	DEBUG	ACCOUNT RapiduNet: LOAD URL https://rapidu.net/ajax.php | redirect=True | cookies=True | get={'a': 'getUserLogin'} | req=None | decode=True | multipart=False | post={'_go': '', 'remember': '1', 'login': 'ladigb', 'pass': 'm123'} | ref=True | just_header=False
164	01.11.2015 18:42:02	DEBUG	ACCOUNT RapiduNet: {u'redirect': u'', u'message': u'success'}
165	01.11.2015 18:42:02	INFO	ACCOUNT RapiduNet: Grabbing account info for user `ladigb`...
166	01.11.2015 18:42:02	DEBUG	ACCOUNT RapiduNet: LOAD URL https://rapidu.net/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
167	01.11.2015 18:42:02	DEBUG	ACCOUNT RapiduNet: Size: 30.00 GB | Unit: N/D
168	01.11.2015 18:42:02	DEBUG	ACCOUNT RapiduNet: Account info for user `ladigb`: {'login': {'timestamp': 1446403322.388063, 'password': 'xxxxxx', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 0, 'maxtraffic': None, 'validuntil': 1449427322.595886, 'login': 'ladigb', 'type': 'RapiduNet', 'options': {'limitdl': ['0']}}}
169	01.11.2015 18:42:06	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
170	01.11.2015 18:42:35	DEBUG	Run Info Fetching for RapiduNet
171	01.11.2015 18:42:35	INFO	Added package test2 containing 1 links
172	01.11.2015 18:42:36	DEBUG	Finished Info Fetching for RapiduNet
173	01.11.2015 18:42:36	INFO	Download starts: Maps.to.the.Stars.2014.PL.BRRip.XviD-KiT.avi
174	01.11.2015 18:42:36	DEBUG	HOSTER RapiduNet[5]: Plugin version: 0.12
175	01.11.2015 18:42:36	DEBUG	HOSTER RapiduNet[5]: Plugin status: testing
176	01.11.2015 18:42:36	WARNING	HOSTER RapiduNet[5]: Plugin may be unstable
177	01.11.2015 18:42:36	INFO	ACCOUNT RapiduNet: Grabbing account info for user `ladigb`...
178	01.11.2015 18:42:36	DEBUG	ACCOUNT RapiduNet: LOAD URL https://rapidu.net/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
179	01.11.2015 18:42:36	DEBUG	ACCOUNT RapiduNet: Size: 30.00 GB | Unit: N/D
180	01.11.2015 18:42:36	DEBUG	ACCOUNT RapiduNet: Account info for user `ladigb`: {'login': {'timestamp': 1446403322.388063, 'password': 'xxxxxx', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 0, 'maxtraffic': None, 'validuntil': 1449427356.651747, 'login': 'ladigb', 'type': 'RapiduNet', 'options': {'limitdl': '0'}}}
181	01.11.2015 18:42:36	INFO	HOSTER RapiduNet[5]: Grabbing link info...
182	01.11.2015 18:42:36	DEBUG	HOSTER RapiduNet[5]: Link info: {'status': 2, 'pattern': {'S': u'699.99', 'U': u'MB', 'ID': u'1711515112', 'N': u'Maps.to.the.Stars.2014.PL.BRRip.XviD-KiT.avi'}, 'size': 733968384, 'url': u'https://rapidu.net/1711515112/Maps.to.the.Stars.2014.PL.BRRip.XviD-KiT.avi', 'name': u'Maps.to.the.Stars.2014.PL.BRRip.XviD-KiT.avi'}
183	01.11.2015 18:42:36	DEBUG	HOSTER RapiduNet[5]: Previous link info: {}
184	01.11.2015 18:42:36	INFO	HOSTER RapiduNet[5]: Link name: Maps.to.the.Stars.2014.PL.BRRip.XviD-KiT.avi
185	01.11.2015 18:42:36	INFO	HOSTER RapiduNet[5]: Link size: 699.97 MiB (733968384 bytes)
186	01.11.2015 18:42:36	INFO	HOSTER RapiduNet[5]: Link status: online
187	01.11.2015 18:42:36	INFO	HOSTER RapiduNet[5]: Looking for direct download link...
188	01.11.2015 18:42:36	DEBUG	HOSTER RapiduNet[5]: Redirect #0 to: https://rapidu.net/1711515112/Maps.to.t ... iD-KiT.avi
189	01.11.2015 18:42:36	DEBUG	HOSTER RapiduNet[5]: LOAD URL https://rapidu.net/1711515112/Maps.to.t ... iD-KiT.avi | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
190	01.11.2015 18:42:36	INFO	HOSTER RapiduNet[5]: Direct download link not found
191	01.11.2015 18:42:36	DEBUG	HOSTER RapiduNet[5]: LOAD URL https://rapidu.net/1711515112/Maps.to.t ... iD-KiT.avi | redirect=True | cookies=[('rapidu.net', 'rapidu_lang', 'en')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
192	01.11.2015 18:42:37	INFO	HOSTER RapiduNet[5]: Processing as free download...
193	01.11.2015 18:42:37	DEBUG	HOSTER RapiduNet[5]: LOAD URL https://rapidu.net/ajax.php | redirect=True | cookies=True | get={'a': 'getLoadTimeToDownload'} | req=None | decode=True | multipart=False | post={'_go': ''} | ref=True | just_header=False
194	01.11.2015 18:42:37	DEBUG	HOSTER RapiduNet[5]: {"timeToDownload":1446403429}
195	01.11.2015 18:42:37	DEBUG	HOSTER RapiduNet[5]: WAIT set to timestamp 1446403430.053705 | Previous waitUntil: 0.000000
196	01.11.2015 18:42:37	INFO	HOSTER RapiduNet[5]: Waiting 1 minutes, 12 seconds...

**Comment by p-26** [comment]
Hi, 

I have the same problem that the rapidu premium account is not working. It seems to fall back to the free account.
But I get other messages. E.g. the warning "Plugin may be unstable". See below.

Maybe the rapidu_session cookie is missing in the RapiduNet.py hoster? If I do this, it downloads the file without problems:
wget --no-cookies --header "Cookie: rapidu_session=h82vqiimnpnk9lgte1rh38s454" https://rapidu.net/4212403765/M4rv3ls.4g3nts.0f.S.H.1.3.L.D.S03E01.PL.720p.rar

I tried to add it, but maybe I did something wrong...didn't get it to work...

> 10.12.2015 20:23:32 INFO      Download starts: TURBO-KID-720p.part4.rar
> 10.12.2015 20:23:32 WARNING   HOSTER RapiduNet[6484]: Plugin may be unstable
> 10.12.2015 20:23:32 INFO      ACCOUNT RapiduNet: Grabbing account info for user `theclan`...
> 10.12.2015 20:23:33 INFO      HOSTER RapiduNet[6481]: Link name: TURBO-KID-720p.part1.rar
> 10.12.2015 20:23:33 INFO      HOSTER RapiduNet[6483]: Link name: TURBO-KID-720p.part3.rar
> 10.12.2015 20:23:33 INFO      HOSTER RapiduNet[6481]: Link size: 1.17 GiB (1251999744 bytes)
> 10.12.2015 20:23:33 INFO      HOSTER RapiduNet[6483]: Link size: 1.17 GiB (1251999744 bytes)
> 10.12.2015 20:23:33 INFO      HOSTER RapiduNet[6481]: Link status: online
> 10.12.2015 20:23:33 INFO      HOSTER RapiduNet[6483]: Link status: online
> 10.12.2015 20:23:34 INFO      HOSTER RapiduNet[6483]: Looking for direct download link...
> 10.12.2015 20:23:34 INFO      HOSTER RapiduNet[6481]: Looking for direct download link...
> 10.12.2015 20:23:35 INFO      HOSTER RapiduNet[6484]: Grabbing link info...
> 10.12.2015 20:23:37 INFO      HOSTER RapiduNet[6483]: Direct download link not found
> 10.12.2015 20:23:37 INFO      HOSTER RapiduNet[6481]: Direct download link not found
> 10.12.2015 20:23:38 INFO      HOSTER RapiduNet[6484]: Link name: TURBO-KID-720p.part4.rar
> 10.12.2015 20:23:39 INFO      HOSTER RapiduNet[6484]: Link size: 0.98 GiB (1055512576 bytes)
> 10.12.2015 20:23:39 INFO      HOSTER RapiduNet[6484]: Link status: online
> 10.12.2015 20:23:39 INFO      HOSTER RapiduNet[6484]: Looking for direct download link...
> 10.12.2015 20:23:41 INFO      HOSTER RapiduNet[6481]: Processing as free download...
> 10.12.2015 20:23:41 INFO      HOSTER RapiduNet[6483]: Processing as free download...

**Comment by p-26** [comment]
I can send you my premium account.
@GammaC0de can you tell me your email or should i send it to vuolter@gmail.com?

**Comment by GammaC0de** [comment]
@p-26 Please change your password to a temporary one then send the details to nitzo2001 \<at\> yahoo \<dot\> com

**Comment by GammaC0de** [comment]
:+1:

**Comment by GammaC0de** [comment]
@p-26 can you test this patch:
```patch
--- module/plugins/accounts/RapiduNet.py	(date 1449411681000)
+++ module/plugins/accounts/RapiduNet.py	(revision )
@@ -23,7 +23,7 @@
 
     VALID_UNTIL_PATTERN = r'>Account: <b>\w+ \((\d+)'
 
-    TRAFFIC_LEFT_PATTERN = r'class="tipsyS"><b>(.+?)<'
+    TRAFFIC_LEFT_PATTERN = r'class="tipsyS"><b>([\d.,]+)\s*([\w^_]*)<'
 
 
     def grab_info(self, user, password, data):
@@ -42,7 +42,7 @@
 
         m = re.search(self.TRAFFIC_LEFT_PATTERN, html)
         if m is not None:
-            trafficleft = self.parse_traffic(m.group(1))
+            trafficleft = self.parse_traffic(m.group(1), m.group(2))
 
         return {'validuntil': validuntil, 'trafficleft': trafficleft, 'premium': premium}
 
```

**Comment by p-26** [comment]
Works perfectly! Great job! Thanks a lot!! :metal:

**Comment by GammaC0de** [comment]
:+1: Gr8 news, you can now change back your password.
