### ISSUE TITLE
Direct file download failed (iso from opensuse)

### ISSUE THREAD

**Issue by malkavi** [pyload/pyload#2152]
Direct file download from http://download.opensuse.org fail.
Using wget works.

Log:
```
04.11.2015 14:22:10	INFO	Download starts: http://download.opensuse.org/distribution/leap/42.1/iso/openSUSE-Leap-42.1-NET-x86_64.iso
04.11.2015 14:22:10	WARNING	HOSTER XFileSharing[33]: DownloadOpensuseOrg | Plugin may be unstable
04.11.2015 14:22:10	INFO	HOSTER XFileSharing[33]: DownloadOpensuseOrg | Grabbing link info...
04.11.2015 14:22:12	INFO	HOSTER XFileSharing[33]: DownloadOpensuseOrg | Link name: openSUSE-Leap-42.1-NET-x86_64.iso
04.11.2015 14:22:12	INFO	HOSTER XFileSharing[33]: DownloadOpensuseOrg | Link size: N/D
04.11.2015 14:22:12	INFO	HOSTER XFileSharing[33]: DownloadOpensuseOrg | Link status: en cola
04.11.2015 14:22:13	ERROR	pycurl error 23: Failed writing body (0 != 10136) 
```

**Comment by GammaC0de** [comment]
Hi,
This URL should have been handled by `BasePlugin` and not by `XFileSharing`
Also `XFileSharing` (and actually any plugin except `BasePlugin`) cannot handle direct links properly.

I was in the middle of the process trying to fix that issue but I'm stcuk until I get an answer from @vuolter for #2136

**Comment by MikeD23** [comment]
Can we somehow force pyload to use BasePlugin? So I could add direct links from my multihoster Account to download without issues.
