### ISSUE TITLE
Pyload 0.4.10 compatibility with python2.5

### ISSUE THREAD

**Issue by Nippey** [pyload/pyload#2155]
Hi,

I tried to test pyload 0.4.10 but was stopped by an import error.

    File "./lib/Python/Lib/bitmath/__init__.py", line 53
    Syntax Error: future feature print function is not supported

Currently you claim to support python2.5, but the print statement is supported starting with 2.6
Checking the code, the affected parts are:
* PIL
* bitmath

Do you plan to remove support for python2.5 with the upcoming release?
Then I'll already start the effort to port python2.7 to my NAS, so I can continue to complain after upgrading to 0.4.10 :o)

Regards!

**Comment by boerngen-schmidt** [comment]
Python 2.5 was initially released back in 2008, thats 7 years ago. Python 2.7 should be available on most platforms as well as python 3.x.

I personally would drop support for python < 2.7 and even aim to port pyload to python 3.

**Comment by Nippey** [comment]
Thanks, I can live with that situation, even if it requires a bit more initialisation work for me ;)

It is also my opinion:
Drop support for 2.5 and start checking for 3.x support.
Most modules used by pyLoad are already available for 3.x.
