### ISSUE TITLE
'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by ladigb** [pyload/pyload#2156]
Hi some problem 'NoneType' object has no attribute 'id'

05.11.2015 14:59:08 INFO      ADDON UpdateManager: All plugins are up to date!
05.11.2015 14:59:10 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
05.11.2015 14:59:36 INFO      Download starts: Lawless.2012.PL.BRRip.XviD.BiDA-D                                                                                                                                                             W-Aztekovsky.avi
05.11.2015 14:59:36 WARNING   HOSTER RapiduNet[1]: Plugin may be unstable
05.11.2015 14:59:36 INFO      ACCOUNT RapiduNet: Grabbing account info for user                                                                                                                                                              `ladigb`...
05.11.2015 14:59:38 INFO      HOSTER RapiduNet[1]: Grabbing link info...
05.11.2015 14:59:38 INFO      Download starts: Lawless.2012.PL.BRRip.XviD.BiDA-D                                                                                                                                                             W-Aztekovsky.avi
05.11.2015 14:59:38 WARNING   HOSTER RapiduNet[1]: Plugin may be unstable
05.11.2015 14:59:38 INFO      ACCOUNT RapiduNet: Grabbing account info for user                                                                                                                                                              `ladigb`...
05.11.2015 14:59:38 INFO      HOSTER RapiduNet[1]: Grabbing link info...
05.11.2015 14:59:39 INFO      HOSTER RapiduNet[1]: Link name: Lawless.2012.PL.BR                                                                                                                                                             Rip.XviD.BiDA-DW-Aztekovsky.avi
05.11.2015 14:59:39 INFO      HOSTER RapiduNet[1]: Link size: 742.84 MiB (778924                                                                                                                                                             032 bytes)
05.11.2015 14:59:39 INFO      HOSTER RapiduNet[1]: Link status: online
05.11.2015 14:59:39 INFO      HOSTER RapiduNet[1]: Looking for direct download l                                                                                                                                                             ink...
05.11.2015 14:59:40 INFO      HOSTER RapiduNet[1]: Link name: Lawless.2012.PL.BR                                                                                                                                                             Rip.XviD.BiDA-DW-Aztekovsky.avi
05.11.2015 14:59:40 INFO      HOSTER RapiduNet[1]: Link size: 742.84 MiB (778924                                                                                                                                                             032 bytes)
05.11.2015 14:59:40 INFO      HOSTER RapiduNet[1]: Link status: online
05.11.2015 14:59:40 INFO      HOSTER RapiduNet[1]: Looking for direct download l                                                                                                                                                             ink...
05.11.2015 14:59:40 ERROR     pycurl error 0: ('cannot invoke setopt() - perform                                                                                                                                                             () is currently running',)
05.11.2015 14:59:40 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates                                                                                                                                                              of: Lawless.2012.PL.BRRip.XviD.BiDA-DW-Aztekovsky.avi (pid:1)
05.11.2015 14:59:40 INFO      ADDON UnSkipOnFail: No duplicates found
05.11.2015 14:59:40 WARNING   Download failed: Lawless.2012.PL.BRRip.XviD.BiDA-D                                                                                                                                                             W-Aztekovsky.avi | 'NoneType' object has no attribute 'id'
05.11.2015 14:59:40 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates                                                                                                                                                              of: Lawless.2012.PL.BRRip.XviD.BiDA-DW-Aztekovsky.avi (pid:1)
05.11.2015 14:59:40 INFO      ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
URL?

**Comment by ladigb** [comment]
Sorry my foult 
now i have something like that
True}, 'data': {'premium': True, 'plugin': <Account RapiduNet>, 'trafficleft': 0                                                                                                                                                             , 'maxtraffic': None, 'validuntil': 1449395842.056842, 'login': 'ladigb', 'type'                                                                                                                                                             : 'RapiduNet', 'options': {'limitdl': '0'}}}
06.11.2015 09:57:22 INFO      HOSTER RapiduNet[1]: Grabbing link info...
06.11.2015 09:57:22 DEBUG     HOSTER RapiduNet[1]: Link info: {'status': 2, 'pat                                                                                                                                                             tern': {'S': u'700.20', 'U': u'MB', 'ID': u'7611830226', 'N': u'Jurassic.World.2                                                                                                                                                             015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi'}, 'size': 734208000, 'url': u'https://r                                                                                                                                                             apidu.net/7611830226/Jurassic.World.2015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi', '                                                                                                                                                             name': u'Jurassic.World.2015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi'}
06.11.2015 09:57:22 DEBUG     HOSTER RapiduNet[1]: Previous link info: {}
06.11.2015 09:57:22 INFO      HOSTER RapiduNet[1]: Link name: Jurassic.World.201                                                                                                                                                             5.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi
06.11.2015 09:57:22 INFO      HOSTER RapiduNet[1]: Link size: 700.20 MiB (734208                                                                                                                                                             000 bytes)
06.11.2015 09:57:22 INFO      HOSTER RapiduNet[1]: Link status: online
06.11.2015 09:57:22 INFO      HOSTER RapiduNet[1]: Looking for direct download l                                                                                                                                                             ink...
06.11.2015 09:57:22 DEBUG     HOSTER RapiduNet[1]: Redirect #0 to: https://rapid                                                                                                                                                             u.net/7611830226/Jurassic.World.2015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi
06.11.2015 09:57:22 DEBUG     HOSTER RapiduNet[1]: LOAD URL https://rapidu.net/7                                                                                                                                                             611830226/Jurassic.World.2015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi | redirect=Tru                                                                                                                                                             e | cookies=True | get={} | req=None | decode=True | multipart=False | post={} |                                                                                                                                                              ref=True | just_header=True
06.11.2015 09:57:23 DEBUG     HOSTER RapiduNet[1]: Link info: {'status': 2, 'nam                                                                                                                                                             e': u'Jurassic.World.2015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi', 'url': u'https:/                                                                                                                                                             /rapidu.net/7611830226/Jurassic.World.2015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi',                                                                                                                                                              'pattern': {'S': u'700.20', 'U': u'MB', 'ID': u'7611830226', 'N': u'Jurassic.Wo                                                                                                                                                             rld.2015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi'}, 'size': 734208000}
06.11.2015 09:57:23 DEBUG     HOSTER RapiduNet[1]: Previous link info: {}
06.11.2015 09:57:23 INFO      HOSTER RapiduNet[1]: Link name: Jurassic.World.201                                                                                                                                                             5.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi
06.11.2015 09:57:23 INFO      HOSTER RapiduNet[1]: Link size: 700.20 MiB (734208                                                                                                                                                             000 bytes)
06.11.2015 09:57:23 INFO      HOSTER RapiduNet[1]: Link status: online
06.11.2015 09:57:23 INFO      HOSTER RapiduNet[1]: Looking for direct download l                                                                                                                                                             ink...
06.11.2015 09:57:23 DEBUG     HOSTER RapiduNet[1]: Redirect #0 to: https://rapid                                                                                                                                                             u.net/7611830226/Jurassic.World.2015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi
06.11.2015 09:57:23 DEBUG     HOSTER RapiduNet[1]: LOAD URL https://rapidu.net/7                                                                                                                                                             611830226/Jurassic.World.2015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi | redirect=Tru                                                                                                                                                             e | cookies=True | get={} | req=None | decode=True | multipart=False | post={} |                                                                                                                                                              ref=True | just_header=True
06.11.2015 09:57:23 DEBUG     pycurl exception 0: ('cannot invoke setopt() - per                                                                                                                                                             form() is currently running',)
06.11.2015 09:57:23 ERROR     pycurl error 0: ('cannot invoke setopt() - perform                                                                                                                                                             () is currently running',)
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/pi/.pyload/userplugins/internal/Base.py", line 280, in preprocessi                                                                                                                                                             ng
    return self._process(*args, **kwargs)
  File "/home/pi/.pyload/userplugins/internal/Hoster.py", line 93, in _process
    self.process(self.pyfile)
  File "/home/pi/.pyload/userplugins/internal/SimpleHoster.py", line 260, in pro                                                                                                                                                             cess
    self.handle_direct(pyfile)
  File "/home/pi/.pyload/userplugins/internal/SimpleHoster.py", line 425, in han                                                                                                                                                             dle_direct
    self.link = self.isdownload(pyfile.url)
  File "/home/pi/.pyload/userplugins/internal/Hoster.py", line 122, in isdownloa                                                                                                                                                             d
    header = self.load(url, just_header=True)
  File "/home/pi/.pyload/userplugins/internal/Base.py", line 489, in load
    return super(Base, self).load(*args, **kwargs)
  File "/home/pi/.pyload/userplugins/internal/Plugin.py", line 236, in load
    html = req.load(url, get, post, ref, bool(cookies), just_header, multipart,                                                                                                                                                              decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/usr/share/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 186, in load
    self.setRequestContext(url, get, post, referer, cookies, multipart)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 154, in setReques                                                                                                                                                             tContext
    self.c.setopt(pycurl.URL, url)
error: cannot invoke setopt() - perform() is currently running
06.11.2015 09:57:23 INFO      Debug Report written to debug_RapiduNet_06-11-2015                                                                                                                                                             _09-57-23.zip
06.11.2015 09:57:23 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates                                                                                                                                                              of: Jurassic.World.2015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi (pid:1)
06.11.2015 09:57:23 INFO      ADDON UnSkipOnFail: No duplicates found
06.11.2015 09:57:23 DEBUG     All downloads processed
06.11.2015 09:57:23 WARNING   Download failed: Jurassic.World.2015.PL.BDRip.XviD                                                                                                                                                             .KiT.DW.Aztekovsky.avi | 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/pi/.pyload/userplugins/internal/Base.py", line 280, in preprocessi                                                                                                                                                             ng
    return self._process(*args, **kwargs)
  File "/home/pi/.pyload/userplugins/internal/Hoster.py", line 93, in _process
    self.process(self.pyfile)
  File "/home/pi/.pyload/userplugins/internal/SimpleHoster.py", line 265, in pro                                                                                                                                                             cess
    self.log_info(_("Direct download link not found"))
  File "/home/pi/.pyload/userplugins/internal/Plugin.py", line 79, in log_info
    self._log("info", self.__type__, self.__name__, args)
  File "/home/pi/.pyload/userplugins/internal/Base.py", line 118, in _log
    'id'        : self.pyfile.id,
AttributeError: 'NoneType' object has no attribute 'id'
06.11.2015 09:57:23 DEBUG     All downloads processed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 309, in run
    self.writeDebugReport(pyfile)
  File "/usr/share/pyload/module/PluginThread.py", line 57, in writeDebugReport
    dump = self.getDebugDump(pyfile)
  File "/usr/share/pyload/module/PluginThread.py", line 92, in getDebugDump
    self.m.core.api.getServerVersion(), pyfile.pluginname, pyfile.plugin.__versi                                                                                                                                                             on__, format_exc())
AttributeError: plugin

06.11.2015 09:57:24 ERROR     Reconnect Failed: plugin
Traceback (most recent call last):
  File "/usr/share/pyload/module/ThreadManager.py", line 135, in work
    self.tryReconnect()
  File "/usr/share/pyload/module/ThreadManager.py", line 166, in tryReconnect
    active = [x.active.plugin.wantReconnect and x.active.plugin.waiting for x in                                                                                                                                                              self.threads if x.active]
AttributeError: plugin
06.11.2015 09:57:26 ERROR     Reconnect Failed: plugin
Traceback (most recent call last):
  File "/usr/share/pyload/module/ThreadManager.py", line 135, in work
    self.tryReconnect()
  File "/usr/share/pyload/module/ThreadManager.py", line 166, in tryReconnect
    active = [x.active.plugin.wantReconnect and x.active.plugin.waiting for x in                                                                                                                                                              self.threads if x.active]
AttributeError: plugin
06.11.2015 09:57:28 ERROR     Reconnect Failed: plugin
Traceback (most recent call last):
  File "/usr/share/pyload/module/ThreadManager.py", line 135, in work
    self.tryReconnect()
  File "/usr/share/pyload/module/ThreadManager.py", line 166, in tryReconnect
    active = [x.active.plugin.wantReconnect and x.active.plugin.waiting for x in                                                                                                                                                              self.threads if x.active]
AttributeError: plugin
06.11.2015 09:57:30 ERROR     Reconnect Failed: plugin
Traceback (most recent call last):
  File "/usr/share/pyload/module/ThreadManager.py", line 135, in work
    self.tryReconnect()
  File "/usr/share/pyload/module/ThreadManager.py", line 166, in tryReconnect
    active = [x.active.plugin.wantReconnect and x.active.plugin.waiting for x in self.threads if x.active]
AttributeError: plugin
06.11.2015 09:57:32 ERROR     Reconnect Failed: plugin
Traceback (most recent call last):
  File "/usr/share/pyload/module/ThreadManager.py", line 135, in work
    self.tryReconnect()
  File "/usr/share/pyload/module/ThreadManager.py", line 166, in tryReconnect
    active = [x.active.plugin.wantReconnect and x.active.plugin.waiting for x in self.threads if x.active]
AttributeError: plugin
06.11.2015 09:57:34 ERROR     Reconnect Failed: plugin
Traceback (most recent call last):
  File "/usr/share/pyload/module/ThreadManager.py", line 135, in work
    self.tryReconnect()
  File "/usr/share/pyload/module/ThreadManager.py", line 166, in tryReconnect
    active = [x.active.plugin.wantReconnect and x.active.plugin.waiting for x in self.threads if x.active]
AttributeError: plugin
06.11.2015 09:57:36 ERROR     Reconnect Failed: plugin
Traceback (most recent call last):
  File "/usr/share/pyload/module/ThreadManager.py", line 135, in work
    self.tryReconnect()
  File "/usr/share/pyload/module/ThreadManager.py", line 166, in tryReconnect
    active = [x.active.plugin.wantReconnect and x.active.plugin.waiting for x in self.threads if x.active]
AttributeError: plugin

**Comment by GammaC0de** [comment]
@ladigb after logged in with a browser , if you put https://rapidu.net/7611830226/Jurassic.World.2015.PL.BDRip.XviD.KiT.DW.Aztekovsky.avi in the browser url, are you able to direct download  the file or there is some sort of a web page first?

**Comment by ladigb** [comment]
Hi
Yes im able to direct download if im login in premium account


W dniu piątek, 6 listopada 2015 GammaC0de <notifications@github.com>
napisał(a):

**Comment by GammaC0de** [comment]
ok, so this is a known issue and related to https://github.com/pyload/pyload/issues/2152 and also #2152

I'm waiting for an answer for my question for #2136 from @vuolter

**Comment by vuolter** [comment]
@GammaC0de I hope to have a bit of spare time to spend on the project next month. :(
