### ISSUE TITLE
slow download speeds (SOLVED)

### ISSUE THREAD

**Issue by np4me2k** [pyload/pyload#2158]
please delete

**Comment by Arno-Nymous** [comment]
Would be great, if you'd provide the solution for everyone or at least not delete it if there was any.
I'd like to know if this was an issue specific to you or whether I can reproduce it on my system.

**Comment by np4me2k** [comment]
It had no connection to pyload at all. I mounted this specific harddisk with the wrong options and this lead to the bad writing-speeds.
Now that it all works fine, thanks for the effort you and the others put into this project!
