### ISSUE TITLE
HOSTER GoogledriveCom[3]: Plugin may be unstable local variable 'link' referenced before assignment

### ISSUE THREAD

**Issue by marviobezerra** [pyload/pyload#2159]
486	09.11.2015 14:11:06	INFO	ADDON UnSkipOnFail: No duplicates found
485	09.11.2015 14:11:06	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 3D.2014.1080p.N.L.d.A.HDA.DUAL-RK.by.realitykings.filewarez.tv.rar (pid:3)
484	09.11.2015 14:11:06	WARNING	Download failed: 3D.2014.1080p.N.L.d.A.HDA.DUAL-RK.by.realitykings.filewarez.tv.rar | local variable 'link' referenced before assignment
483	09.11.2015 14:11:06	INFO	HOSTER GoogledriveCom[3]: Processing as free download...
482	09.11.2015 14:11:00	INFO	HOSTER GoogledriveCom[3]: Direct download link not found
481	09.11.2015 14:11:00	INFO	HOSTER GoogledriveCom[3]: Looking for direct download link...
480	09.11.2015 14:11:00	INFO	HOSTER GoogledriveCom[3]: Link status: online
479	09.11.2015 14:11:00	INFO	HOSTER GoogledriveCom[3]: Link size: N/D
478	09.11.2015 14:11:00	INFO	HOSTER GoogledriveCom[3]: Link name: 3D.2014.1080p.N.L.d.A.HDA.DUAL-RK.by.realitykings.filewarez.tv.rar
477	09.11.2015 14:10:58	INFO	HOSTER GoogledriveCom[3]: Grabbing link info...
476	09.11.2015 14:10:58	WARNING	HOSTER GoogledriveCom[3]: Plugin may be unstable
475	09.11.2015 14:10:58	INFO	Download starts: https://drive.google.com/file/d/0ByKistT5YHK8MU8xcVBBN3VfS0k/edit?usp=sharing
474	09.11.2015 14:10:56	INFO	Added package Edge of Tomorrow containing 1 links

**Comment by marviobezerra** [comment]
Anyone have problem to do Google Drive download?

**Comment by hero78119** [comment]
got the same problem +1

**Comment by vuolter** [comment]
Retry now, please. ;)

**Comment by marviobezerra** [comment]
The same yet: 376	05.01.2016 10:27:29	WARNING	Download failed: Extraction.2015.1080p.WEB-DL.DD5.1.H264-RBG.by.realitykings.filewarez.tv.rar | local variable 'link' referenced before assignment

**Comment by vuolter** [comment]
@marviobezerra Take a look here: https://github.com/pyload/pyload/issues/2241
