### ISSUE TITLE
RG error: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by driet** [pyload/pyload#2160]
LOG:

1   09.11.2015 19:09:02 DEBUG   HOSTER RapidgatorNet[624]: http://rapidgator.net/download/AjaxStartTimer?fid=xxx | {"state":"started","sid":"xxx"}
2   09.11.2015 19:09:02 DEBUG   HOSTER RapidgatorNet[624]: WAIT set to timestamp xxx.xxx| Previous waitUntil: 0.000000
3   09.11.2015 19:09:02 DEBUG   HOSTER RapidgatorNet[624]: RECONNECT not required | Previous wantReconnect: False
4   09.11.2015 19:09:02 INFO    HOSTER RapidgatorNet[624]: Waiting 2 minutes...
5   09.11.2015 19:11:03 DEBUG   HOSTER RapidgatorNet[624]: LOAD URL http://rapidgator.net/download/AjaxGetDownloadLink?sid=xxx | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={} | ref=True | multipart=False
6   09.11.2015 19:11:04 DEBUG   HOSTER RapidgatorNet[624]: http://rapidgator.net/download/AjaxGetDownloadLink?xxx | {"state":"done"}
7   09.11.2015 19:11:04 DEBUG   HOSTER RapidgatorNet[624]: LOAD URL http://rapidgator.net/download/captcha | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={} | ref=True | multipart=False
8   09.11.2015 19:11:04 DEBUG   CAPTCHA RapidgatorNet[624]: AdsCaptcha | Key or id pattern not found
9   09.11.2015 19:11:04 WARNING CAPTCHA RapidgatorNet[624]: ReCaptcha | Key pattern not found
10  09.11.2015 19:11:04 DEBUG   CAPTCHA RapidgatorNet[624]: SolveMedia | Key: xxx
11  09.11.2015 19:11:04 DEBUG   CAPTCHA RapidgatorNet[624]: SolveMedia | Key: xxx
12  09.11.2015 19:11:04 DEBUG   HOSTER RapidgatorNet[624]: LOAD URL http://api.solvemedia.com/papi/challenge.noscript | redirect=True | decode=True | cookies=True | get={'k': u'xxx'} | req=None | just_header=False | post={} | ref=True | multipart=False
13  09.11.2015 19:11:04 DEBUG   CAPTCHA RapidgatorNet[624]: SolveMedia | Challenge: xxx
14  09.11.2015 19:11:04 DEBUG   CAPTCHA RapidgatorNet[624]: SolveMedia | LOAD URL http://api.solvemedia.com/papi/media | redirect=True | decode=False | cookies=True | get={'c': u'xxx'} | req= | just_header=False | post={} | ref=False | multipart=False
15  09.11.2015 19:11:04 DEBUG   CAPTCHA RapidgatorNet[624]: SolveMedia | This function does nothing
16  09.11.2015 19:11:19 DEBUG   CAPTCHA RapidgatorNet[624]: SolveMedia | Result: al capone
17  09.11.2015 19:11:19 DEBUG   HOSTER RapidgatorNet[624]: LOAD URL http://api.solvemedia.com/papi/verify.noscript | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={'adcopy_response': 'al capone', 'magic': u'xxx', 'k': u'xxx', 'l': 'en', 's': 'standard', 't': 'img', 'adcopy_challenge': u'xxx', 'ref': u'http://rapidgator.net/file/xxx.rar.html'} | ref=True | multipart=False
18  09.11.2015 19:11:19 DEBUG   HOSTER RapidgatorNet[624]: LOAD URL http://rapidgator.net/download/captcha | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={'adcopy_response': 'al capone', 'DownloadCaptchaForm[captcha]': '', 'adcopy_challenge': u'xxx'} | ref=True | multipart=False
19  09.11.2015 19:11:19 INFO    HOSTER RapidgatorNet[624]: Downloading file...
20  09.11.2015 19:11:19 WARNING Download failed: xxx.rar | cannot concatenate 'str' and 'NoneType' objects
21  09.11.2015 19:11:19 DEBUG   Error creating zip file: 'ascii' codec can't decode byte 0x91 in position 11: ordinal not in range(128) 

DEBUG

pyLoad 0.4.9 Debug Report of RapidgatorNet 0.38 

TRACEBACK:
 Traceback (most recent call last):
  File "/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/pyload/module/plugins/internal/Base.py", line 280, in preprocessing
    return self._process(_args, *_kwargs)
  File "/pyload/module/plugins/internal/Hoster.py", line 93, in _process
    self.process(self.pyfile)
  File "/pyload/module/plugins/internal/SimpleHoster.py", line 283, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/pyload/module/plugins/internal/Hoster.py", line 178, in download
    self.log_debug("DOWNLOAD URL " + url,
TypeError: cannot concatenate 'str' and 'NoneType' objects

FRAMESTACK:

Frame preprocessing in /pyload/module/plugins/internal/Base.py at line 280
                    self = <Hoster RapidgatorNet>
                    args = (<DownloadThread(Thread-2, started daemon)>,)
                  kwargs = {}

Frame _process in /pyload/module/plugins/internal/Hoster.py at line 103
                    self = <Hoster RapidgatorNet>
                  thread = <DownloadThread(Thread-2, started daemon)>

Frame process in /pyload/module/plugins/internal/SimpleHoster.py at line 283
                  pyfile = PyFile 624: xxx.rar@RapidgatorNet
                    self = <Hoster RapidgatorNet>

Frame download in /pyload/module/plugins/internal/Hoster.py at line 178
                 cookies = True
                  resume = None
                     url = None
                    self = <Hoster RapidgatorNet>
                     get = {}
             disposition = True
                  chunks = None
                    post = {}
                     ref = True

PLUGIN OBJECT DUMP: 

```
  ADSCAPTCHA_PATTERN = '(http://api\\.adscaptcha\\.com/Get\\.aspx[^"\\\']+)'
             API_URL = 'http://rapidgator.net/api/file'
          CHECK_FILE = True
       CHECK_TRAFFIC = False
             COOKIES = [('rapidgator.net', 'lang', 'en')]
         DIRECT_LINK = True
         DISPOSITION = True
    DL_LIMIT_PATTERN = None
       ERROR_PATTERN = 'You have reached your (?:daily|hourly) downloads limit'
         FILE_ERRORS = [('Html error',
```

  '\A(?:\s_<.+>)?((?:[\w\s]_(?:[Ee]rror|ERROR)\s_\:?)?\s_\d{3})(?:\Z|\s+)'),
 ('Request error', '([Aa]n error occured while processing your request)'),
 ('Html file', '\A\s_<!DOCTYPE html')]
      HAPPY_HOUR_PATTERN = None
         HASHSUM_PATTERN = None
            INFO_PATTERN = None
      IP_BLOCKED_PATTERN = None
          JSVARS_PATTERN = "\s+var\s_(startTimerUrl|getDownloadUrl|captchaUrl|fid|secs)\s_=\s_\'?(._?)\'?;"
            LEECH_HOSTER = False
       LINK_FREE_PATTERN = "return \'(http://\w+.rapidgator.net/._)\';"
            LINK_PATTERN = None
    LINK_PREMIUM_PATTERN = None
           LOGIN_ACCOUNT = False
           LOGIN_PREMIUM = False
            NAME_PATTERN = '<title>Download file (?P<N>._)</title>'
       NAME_REPLACEMENTS = []
         OFFLINE_PATTERN = '>(File not found|Error 404)'
    PREMIUM_ONLY_PATTERN = 'You can download files up to|This file can be downloaded by premium only<'
       RECAPTCHA_PATTERN = '"http://api\.recaptcha\.net/challenge\?k=(._?)"'
      SIZE_LIMIT_PATTERN = None
            SIZE_PATTERN = 'File size:\s_<strong>(?P<S>[\d.,]+) (?P<U>[\w^_]+)</strong>'
       SIZE_REPLACEMENTS = []
      SOLVEMEDIA_PATTERN = 'http://api\.solvemedia\.com/papi/challenge\.script\?k=(._?)"'
    TEMP_OFFLINE_PATTERN = None
           TEXT_ENCODING = True
        URL_REPLACEMENTS = []
            WAIT_PATTERN = '(Delay between downloads must be not less than|Try again in).+'
                 account = False
                 captcha = <Captcha Captcha>
             chunk_limit = 1
               classname = 'RapidgatorNet'
                    data = u''
               direct_dl = True
                    info = {'name': 'xxx.rar',
 'pattern': {'N': u'xxx.rar', 'S': u'xxx.xx', 'U': u'MB'},
 'size': xxx,
 'status': 2,
 'url': u'http://rapidgator.net/file/xxx/xxx.rar.html'}
                      js = <module.common.JsEngine.JsEngine instance at 0x19415d0>
              last_check = None
           last_download = None
               last_html = u''
                leech_dl = False
                 limitDL = 0
                    link = None
                 multiDL = False
                 premium = False
                  pyfile = PyFile 624: xxx.rar@RapidgatorNet
                  pyload = <**main**.Core object at 0x1641430>
                     req = <module.network.Browser.Browser object at 0x1ec5148>
            restart_free = False
         resume_download = False
                 retries = {}
                     sid = None
                  thread = <DownloadThread(Thread-2, started daemon)>
                    user = None
                 waiting = False
           wantReconnect = False

PYFILE OBJECT DUMP: 

```
               _size = xxx
               abort = False
              active = False
               error = "cannot concatenate 'str' and 'NoneType' objects"
                  id = 624
                lock = <_RLock(None, 0)>
                   m = <module.database.FileDatabase.FileHandler instance at 0x174c260>
         maxprogress = 100
                name = 'xxx.rar'
               order = 36
           packageid = 31
              plugin = <Hoster RapidgatorNet>
         pluginclass = <class 'module.plugins.hoster.RapidgatorNet.RapidgatorNet'>
        pluginmodule = <module 'module.plugins.hoster.RapidgatorNet' from '/pyload/module/plugins/hoster/RapidgatorNet.pyc'>
          pluginname = u'RapidgatorNet'
            progress = 0
         reconnected = False
                size = xxx
              status = 8
          statusname = None
                 url = u'http://rapidgator.net/file/xxx/xxx.rar.html'
           waitUntil = xxx.xxx
```

CONFIG: 

{'activated': {'desc': 'Activated', 'type': 'bool', 'value': True},
 'chk_filesize': {'desc': 'Check file size', 'type': 'bool', 'value': True},
 'desc': 'RapidgatorNet',
 'fallback': {'desc': 'Fallback to free download if premium fails',
              'type': 'bool',
              'value': True},
 'max_wait': {'desc': 'Reconnect if waiting time is greater than minutes',
              'type': 'int',
              'value': 10},
 'outline': 'Rapidgator.net hoster plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': True}}

**Comment by driet** [comment]
BTW, I tried a few weeks an old copy of pyload (before the last rapidgator.py changes). Rapidgator worked fine, but premium accounts were broken. Is this really the stable branch?

**Comment by programatix** [comment]
I noticed the "link" variable is "none" but I have no idea how it become so. That's the reason for the error though.
