### ISSUE TITLE
'ascii' codec decode issue with package names

### ISSUE THREAD

**Issue by moacmoa** [pyload/pyload#2163]
Have a decode issue when i use special chars (example = "é") in the package name.
Here is the log when I named my package "vidéo" :

> 14.11.2015 00:56:41 INFO      Download starts: Fargo.S02E01.FRENCH.720p.WEBRip.DD5.1.H264-LiBERTY.mkv
> 14.11.2015 00:56:41 WARNING   HOSTER UptoboxCom[168]: Plugin may be unstable
> 14.11.2015 00:56:41 INFO      HOSTER UptoboxCom[168]: Grabbing link info...
> 14.11.2015 00:56:42 INFO      HOSTER UptoboxCom[168]: Link name: Fargo.S02E01.FRENCH.720p.WEBRip.DD5.1.H264-LiBERTY.mkv
> 14.11.2015 00:56:42 INFO      HOSTER UptoboxCom[168]: Link size: 1.49 GiB (1598029824 bytes)
> 14.11.2015 00:56:42 INFO      HOSTER UptoboxCom[168]: Link status: en ligne
> 14.11.2015 00:56:42 INFO      HOSTER UptoboxCom[168]: Processing as free download...
> 14.11.2015 00:56:42 INFO      HOSTER UptoboxCom[168]: Downloading file...
> 14.11.2015 00:56:42 WARNING   Download failed: Fargo.S02E01.FRENCH.720p.WEBRip.DD5.1.H264-LiBERTY.mkv | 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)

**Comment by ajs124** [comment]
Same issue here with mega.co.nz and a "ü".

**Comment by tomcoch** [comment]
same issue with this package name (but non special char):
Download failed: The.Man.from.U.N.C.L.E.2015.MULTi.VFF.10...-KiKi.zone-telechargement.com.part01.rar | 'ascii' codec can't decode byte 0xc3 in position 39: ordinal not in range(128)

**Comment by GammaC0de** [comment]
@vuolter are you working on this too?

**Comment by sschwart** [comment]
There is a solution in post #2286 ;)
It works great for me :)
