### ISSUE TITLE
ShareonlineBiz 0.63 broken / 0.60 working

### ISSUE THREAD

**Issue by NorfolkXX** [pyload/pyload#2166]
Hello,

After several updates at my pyload yesterday, I find the ShareonlineBiz-Hoster not working anymore.

Update was from v0.60 to v0.63, so I removed 0.63 and inserted old 0.60 again. Without any other changes, the old v0.60 did work as usuall again.

I use shareonline as free user with expertdecoder for captcha-solving. 

v0.63 - Error-message as follows:
15.11.2015 17:21:59	INFO	HOSTER ShareonlineBiz[467]: Waiting 3 seconds...
15.11.2015 17:22:03	WARNING	Download failed: XXXXXXXXX.rar | ReCaptcha data not found
***
v0.60 - All ok:
15.11.2015 17:39:32	INFO	HOSTER ShareonlineBiz[452]: Waiting 3 seconds...
15.11.2015 17:39:37	INFO	ADDON ExpertDecoders: 3791 credits left
15.11.2015 17:39:46	INFO	HOSTER ShareonlineBiz[452]: Waiting 30 seconds...
15.11.2015 17:40:18	INFO	HOSTER ShareonlineBiz[452]: Downloading file... 

Here, ExpertDecoders got the ReCaptcha, solved it and the download started.

Best regards,
Norfolk

**Comment by Arno-Nymous** [comment]
This one has already been solved, see [issue #2130](https://github.com/pyload/pyload/issues/2130) and my solution on that.

**Comment by NorfolkXX** [comment]
Ah, thank you, seems like i better dl the complete stable again
