### ISSUE TITLE
Uplea.com: Invalid Link ! (Error 4207)

### ISSUE THREAD

**Issue by tomcoch** [pyload/pyload#2170]
Since 1 week, all downloads from uplea.com failed due to file size mismatch. Within the downloaded files , it is written: Invalid Link ! (Error 4207). 
(Tested with plugin version 0.10 and 0.15).

23.11.2015 19:05:24 INFO      Download starts: Pay.the.Ghost.2015.MULTi.1080p.BluRay.x264-LOST.zone-telechargement.com.part2.rar
23.11.2015 19:05:24 DEBUG     HOSTER UpleaCom[1]: Plugin version: 0.15
23.11.2015 19:05:24 DEBUG     HOSTER UpleaCom[1]: Plugin status: testing
23.11.2015 19:05:24 WARNING   HOSTER UpleaCom[1]: Plugin may be unstable
23.11.2015 19:05:24 INFO      HOSTER UpleaCom[1]: Grabbing link info...
23.11.2015 19:05:26 DEBUG     HOSTER UpleaCom[1]: Link info: {'status': 2, 'pattern': {'S': u'1000', 'U': u'Mo', 'N': u'Pay.the.Ghost.2015.MULTi.1080p.BluRay.x264-LOST.zone-telechargement.com.part2.rar'}, 'size': 1048576000, 'url': u'http://uplea.com/dl/F2A893129C17F75', 'name': u'Pay.the.Ghost.2015.MULTi.1080p.BluRay.x264-LOST.zone-telechargement.com.part2.rar'}
23.11.2015 19:05:26 DEBUG     HOSTER UpleaCom[1]: Previous link info: {}
23.11.2015 19:05:26 INFO      HOSTER UpleaCom[1]: Link name: Pay.the.Ghost.2015.MULTi.1080p.BluRay.x264-LOST.zone-telechargement.com.part2.rar
23.11.2015 19:05:26 INFO      HOSTER UpleaCom[1]: Link size: 1000.00 MiB (1048576000 bytes)
23.11.2015 19:05:26 INFO      HOSTER UpleaCom[1]: Link status: en ligne
23.11.2015 19:05:26 DEBUG     HOSTER UpleaCom[1]: LOAD URL http://uplea.com/dl/F2A893129C17F75 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
23.11.2015 19:05:28 INFO      HOSTER UpleaCom[1]: Processing as free download...
23.11.2015 19:05:28 DEBUG     HOSTER UpleaCom[1]: LOAD URL http://uplea.com/step/F2A893129C17F75/3 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
23.11.2015 19:05:30 DEBUG     HOSTER UpleaCom[1]: WAIT set to timestamp 1448301946.543761 | Previous waitUntil: 0.000000
23.11.2015 19:05:30 INFO      HOSTER UpleaCom[1]: Waiting 15 seconds...
23.11.2015 19:05:46 INFO      HOSTER UpleaCom[1]: Downloading file...
23.11.2015 19:05:46 DEBUG     HOSTER UpleaCom[1]: DOWNLOAD URL http://n273.uplea.com/anonym/b836031af023e9ed03ed1ac7afc63bc14b413bbeeb29c46e4ad30f13ae9b604151162ee376d7cb82714986528d3399664730/Pay.the.Ghost.2015.MULTi.1080p.BluRay.x264-LOST.zone-telechargement.com.part2.rar | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
23.11.2015 19:05:47 INFO      HOSTER UpleaCom[1]: Checking downloaded file...
23.11.2015 19:05:47 WARNING   Download failed: Pay.the.Ghost.2015.MULTi.1080p.BluRay.x264-LOST.zone-telechargement.com.part2.rar | File size mismatch | Expected file size: 1048576000 | Downloaded file size: 27
23.11.2015 19:05:47 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: Pay.the.Ghost.2015.MULTi.1080p.BluRay.x264-LOST.zone-telechargement.com.part2.rar (pid:1)
23.11.2015 19:05:47 INFO      ADDON UnSkipOnFail: No duplicates found
23.11.2015 19:05:47 DEBUG     All downloads processed

**Comment by GammaC0de** [comment]
@tomcoch try #2171

**Comment by tomcoch** [comment]
It works with fix #2171, thank you GammaC0de :+1:

**Comment by zephura** [comment]
Full thanks, it works very fine!

**Comment by GammaC0de** [comment]
Thank you guys :+1:
