### ISSUE TITLE
uloz.to 'ascii' codec can't encode characters in position 2-4: ordinal not in range(128)

### ISSUE THREAD

**Issue by xDereCx** [pyload/pyload#2173]
getting errors from uloz.to

Download failed: upiri-deniky-the-vampire-diaries-s02e22-720p-web-dl-cz-en-mkv | 'ascii' codec can't encode characters in position 2-4: ordinal not in range(128)

**Comment by sschwart** [comment]
There is a solution in post #2286 ;)
It works great for me :)
