### ISSUE TITLE
UploadedTo waiting time problem

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [pyload/pyload#2174]
As discussed in #1477, there is a problem with the waiting time for free downloads. Uploaded reports ``You have reached the max. number of possible free downloads for this hour`` and the method ``parse_timer`` in utils.py reads that as a waiting time of 3600 seconds while in reality the waiting time between to free downloads is 3600 for this hoster. 

This results in the download restarting and failing three times, wasting three captchas before the download actually starts.

As overriding the parse_timer in UploadedTo.py doesn't seem possible, I changed the method definition in utils.py and added another case:

    def parse_time(value):
        if re.search("da(il)?y|today", value):
            seconds = seconds_to_midnight()

        elif re.search("You have reached the max. number of possible free downloads for this hour", value):
            seconds = 10800

        else:
            regex   = re.compile(r'(\d+| (?:this|an?) )\s*(hr|hour|min|sec|)', re.I)
            seconds = sum((int(v) if v.strip() not in ("this", "a", "an") else 1) *
                          {'hr': 3600, 'hour': 3600, 'min': 60, 'sec': 1, '': 1}[u.lower()]
                          for v, u in regex.findall(value))
        return seconds

This way it works correctly. 
Do you think this could be incorporated here to prevent a waste of captchas?

**Comment by GammaC0de** [comment]
So what are you saying is that "You have reached the max. number of possible free downloads for this hour" actually means 3 hours?

**Comment by 1337sup3rh4x0r** [comment]
Yes, unfortunately uploaded tells you "You have reached the max. number of possible free downloads for this hour" but in reality the waiting period is three hours. 

So if no other hoster uses this exact phrase all should be fine, although not beautifully implemented. 

But I cannot think of another way to cope with this. Can you?

I saw that some methods are defined in UploadedTo.py that override the ones from SimpleHoster.py. Could other methods that are  not directly imported from UploadedTo.py (like this parse_time method) be overridden similarly?

**Comment by GammaC0de** [comment]
@1337sup3rh4x0r try #2181

**Comment by 1337sup3rh4x0r** [comment]
I'll try it and report back. Thank you for looking in to this!

**Comment by 1337sup3rh4x0r** [comment]
It seems to work. Thank you very much @GammaC0de
