### ISSUE TITLE
[SimpleHoster] undefinded function "was_downloaded()"

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2175]
`was_downloaded()` function is not definded anywhere:
[SimpleHoster.py#L253](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/SimpleHoster.py#L253):
```python
            if not self.link and not was_downloaded():
                self.log_info(_("Failed to leech url"))
```

**Comment by vuolter** [comment]
I know... I fixed some things before before leaving, last month, but I still have not time for testing my latest changes and pushing them on the repo. :(
