### ISSUE TITLE
Share Online doesnt work anymore

### ISSUE THREAD

**Issue by GodHunter** [pyload/pyload#2178]
Hi,

since yesterday i have a problem downloading from share online. The Download doesnt start as premium user and wants to download as an free user but became no free slot. Here is an log from start to failed download

04.12.2015 12:51:29 INFO starte pyLoad 0.4.9
04.12.2015 12:51:29 INFO Benutze Home-Verzeichnis: /root/.pyload
04.12.2015 12:51:30 INFO Aktivierte Plugins: AntiStandby, ClickNLoad, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
04.12.2015 12:51:30 INFO Deaktivierte Plugins: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPPInterface
04.12.2015 12:51:30 INFO Downloadzeit: True
04.12.2015 12:51:30 INFO Starte ThriftBackend: 0.0.0.0:7227
04.12.2015 12:51:30 INFO Starting threaded webserver: 0.0.0.0:8080
04.12.2015 12:51:30 INFO Free space: 1.29 TiB
04.12.2015 12:51:30 INFO Activating Accounts...
04.12.2015 12:51:30 INFO ACCOUNT ShareonlineBiz: Adding user `***`...
04.12.2015 12:51:30 INFO ACCOUNT ShareonlineBiz: Login user `***`...
04.12.2015 12:51:30 INFO ACCOUNT ShareonlineBiz: Grabbing account info for user `***`...
04.12.2015 12:51:30 INFO Activating Plugins...
04.12.2015 12:51:30 WARNING ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
xset: unable to open display ""
04.12.2015 12:51:30 INFO ADDON XFileSharing: Handle any hoster site on the web!
04.12.2015 12:51:30 INFO ADDON XFileSharing: Handle any crypter site on the web!
04.12.2015 12:51:30 INFO pyLoad is up and running
04.12.2015 12:51:31 INFO ADDON UpdateManager: pyLoad is up to date!
04.12.2015 12:51:31 INFO ADDON UpdateManager: All plugins are up to date!
04.12.2015 12:51:36 INFO ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
04.12.2015 12:51:58 INFO Download starts: scrubs-s09e13.part2.rar
04.12.2015 12:51:58 WARNING HOSTER ShareonlineBiz[1]: Plugin may be unstable
04.12.2015 12:51:58 INFO ACCOUNT ShareonlineBiz: Grabbing account info for user `***`...
04.12.2015 12:51:59 INFO HOSTER ShareonlineBiz[1]: Grabbing link info...
04.12.2015 12:51:59 INFO HOSTER ShareonlineBiz[1]: Link name: scrubs-s09e13.part2.rar
04.12.2015 12:51:59 INFO HOSTER ShareonlineBiz[1]: Link size: 74.47 MiB (78090718 bytes)
04.12.2015 12:51:59 INFO HOSTER ShareonlineBiz[1]: Link status: online
04.12.2015 12:51:59 INFO HOSTER ShareonlineBiz[1]: Looking for direct download link...
04.12.2015 12:51:59 INFO HOSTER ShareonlineBiz[1]: Direct download link not found
04.12.2015 12:51:59 INFO ACCOUNT ShareonlineBiz: Grabbing account info for user `***`...
04.12.2015 12:51:59 INFO HOSTER ShareonlineBiz[1]: Filesize: 76260 KiB | Traffic left for user `***`: 104336729 KiB
04.12.2015 12:51:59 INFO HOSTER ShareonlineBiz[1]: Processing as premium download...
04.12.2015 12:51:59 INFO ACCOUNT ShareonlineBiz: Grabbing account info for user `***`...
04.12.2015 12:51:59 WARNING HOSTER ShareonlineBiz[1]: Premium download failed | offline
04.12.2015 12:51:59 INFO Download restarted: scrubs-s09e13.part2.rar | Fallback to free processing
04.12.2015 12:52:00 INFO Download starts: scrubs-s09e13.part2.rar
04.12.2015 12:52:00 WARNING HOSTER ShareonlineBiz[1]: Plugin may be unstable
04.12.2015 12:52:00 INFO HOSTER ShareonlineBiz[1]: Grabbing link info...
04.12.2015 12:52:00 INFO HOSTER ShareonlineBiz[1]: Link name: scrubs-s09e13.part2.rar
04.12.2015 12:52:00 INFO HOSTER ShareonlineBiz[1]: Link size: 74.47 MiB (78090718 bytes)
04.12.2015 12:52:00 INFO HOSTER ShareonlineBiz[1]: Link status: online
04.12.2015 12:52:00 INFO HOSTER ShareonlineBiz[1]: Looking for direct download link...
04.12.2015 12:52:00 INFO HOSTER ShareonlineBiz[1]: Direct download link not found
04.12.2015 12:52:00 INFO HOSTER ShareonlineBiz[1]: Processing as free download...
04.12.2015 12:52:00 INFO HOSTER ShareonlineBiz[1]: Waiting 3 seconds...
04.12.2015 12:52:04 ERROR HOSTER ShareonlineBiz[1]: full | Keine freien Slots für Free User!
04.12.2015 12:52:04 INFO HOSTER ShareonlineBiz[1]: Waiting 10 minutes...

**Comment by GammaC0de** [comment]
@GodHunter since I don't have a valid user/pw, I cannot test it

**Comment by Schlunze** [comment]
Hi,
same here, Plugin may be unstable.
@GammaC0de do you have any idea for a change that we coud try?
tx in advance

**Comment by GammaC0de** [comment]
Seems that the account plugin needs to be updated

**Comment by GodHunter** [comment]
@GammaC0de is there a save way to give you access to my account? Didnt find anything like PM or something else.

**Comment by GammaC0de** [comment]
@GodHunter you can send it to nitzo2001 \<at\> yahoo \<dot\> com

**Comment by GodHunter** [comment]
@GammaC0de had send you an 30 Days Premium Access

**Comment by GammaC0de** [comment]
:+1:

**Comment by hardy123480** [comment]
@GodHunter Just for info: I'm running a very old Pyload build (deactivated the Update manager a few months ago) and my ShareonlineBiz.py plugin works like a charm (I'm running v0.21). I guess it's not the plugin or you can just revert to this version.

**Comment by GammaC0de** [comment]
Just tried the plugin with the account and it works fine..
I updated the plugin version, see if that helps.
```
09.12.2015 21:50:31 INFO      ACCOUNT ShareonlineBiz: Adding user `11111111111`...
09.12.2015 21:50:31 DEBUG     ACCOUNT ShareonlineBiz: Reached login timeout foruser `11111111111`
09.12.2015 21:50:31 INFO      ACCOUNT ShareonlineBiz: Login user `11111111111`...
09.12.2015 21:50:31 DEBUG     ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': '11111111111', 'password': 'p455w0rd'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
09.12.2015 21:52:51 INFO      Download starts: [TVrip][arearaw.com]y_precure5_01_24.part03.rar
09.12.2015 21:52:51 DEBUG     HOSTER ShareonlineBiz[1]: Plugin version: 0.63
09.12.2015 21:52:51 DEBUG     HOSTER ShareonlineBiz[1]: Plugin status: testing
09.12.2015 21:52:51 WARNING   HOSTER ShareonlineBiz[1]: Plugin may be unstable
09.12.2015 21:52:51 INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `11111111111`...
09.12.2015 21:52:51 DEBUG     ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': '11111111111', 'password': 'p455w0rd'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
09.12.2015 21:52:54 DEBUG     ACCOUNT ShareonlineBiz: Account info for user `11111111111`: {'login': {'timestamp': 1449690631.229, 'password': 'p455w0rd', 'valid': True}, 'data': {'premium': True, 'plugin': <Account ShareonlineBiz>, 'trafficleft': 104857600.0, 'maxtraffic': 104857600L, 'validuntil': 1452088103.0, 'login': '11111111111', 'type': 'ShareonlineBiz', 'options': {'limitdl': '0'}}}
09.12.2015 21:52:54 INFO      HOSTER ShareonlineBiz[1]: Filesize: 513024 KiB | Traffic left for user `11111111111`: 104857600 KiB
09.12.2015 21:52:54 INFO      HOSTER ShareonlineBiz[1]: Processing as premium download...
09.12.2015 21:52:54 INFO      ACCOUNT ShareonlineBiz: Grabbing account info foruser `11111111111`...
09.12.2015 21:52:54 DEBUG     ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': '11111111111', 'password': 'p455w0rd'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
09.12.2015 21:52:54 DEBUG     ACCOUNT ShareonlineBiz: Account info for user `11111111111`: {'login': {'timestamp': 1449690631.229, 'password': 'p455w0rd', 'valid': True}, 'data': {'premium': True, 'plugin': <Account ShareonlineBiz>, 'trafficleft': 104857600.0, 'maxtraffic': 104857600L, 'validuntil': 1452088103.0, 'login': '11111111111', 'type': 'ShareonlineBiz', 'options': {'limitdl': '0'}}}
09.12.2015 21:52:54 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL https://api.share-online.biz/account.php | redirect=True | cookies=True | get={'username': '11111111111', 'lid': 'MQ3LOE9MWI', 'password': 'p455w0rd', 'act': 'download'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
09.12.2015 21:52:54 DEBUG     HOSTER ShareonlineBiz[1]: STATUS: online
URL: http://dlw46-2.share-online.biz/dl?u=C54456E992202EEA97452390954954E592342DE59D132D9191414C95943836EDD81D2BD0954808DE96402CEDF57D4CB9&q=v4
ID: MQ3LOE9MWI
NAME: [TVrip][arearaw.com]y_precure5_01_24.part03.rar
SIZE: 525336576
MD5: 3685d7593bea4b39466f0d7c6c5e045a
09.12.2015 21:52:54 INFO      HOSTER ShareonlineBiz[1]: Downloading file...
09.12.2015 21:52:54 DEBUG     HOSTER ShareonlineBiz[1]: DOWNLOAD URL http://dlw46-2.share-online.biz/dl?u=C54456E992202EEA97452390954954E592342DE59D132D9191414C95943836EDD81D2BD0954808DE96402CEDF57D4CB9&q=v4 | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
09.12.2015 21:52:56 DEBUG     Content-Disposition: [TVrip][arearaw.com]y_precure5_01_24.part03.rar
09.12.2015 22:05:00 INFO      HOSTER ShareonlineBiz[1]: Checking downloaded file...
09.12.2015 22:05:00 INFO      HOSTER ShareonlineBiz[1]: Checking downloaded file with built-in rules...
09.12.2015 22:05:00 INFO      HOSTER ShareonlineBiz[1]: Checking downloaded file with custom rules...
09.12.2015 22:05:00 INFO      HOSTER ShareonlineBiz[1]: File is OK
09.12.2015 22:05:00 INFO      Download finished: [TVrip][arearaw.com]y_precure5_01_24.part03.rar
09.12.2015 22:05:00 INFO      Package finished: ShareOnlineBiz
09.12.2015 22:05:00 DEBUG     All downloads processed
```

**Comment by GodHunter** [comment]
Works fine for me now. Thanks for your fix.
Am 09.12.2015 22:22 schrieb "GammaC0de" <notifications@github.com>:

**Comment by GammaC0de** [comment]
:+1: Great.
I'm closing this now. if you have problems, please post again.
