### ISSUE TITLE
Real-Debrid API Usage

### ISSUE THREAD

**Issue by TheCrach** [pyload/pyload#2182]
Hello,

Could anybody implemant our new API inside Pyload ? The old API will be disabled soon.

API Doc: https://api.real-debrid.com/
You can use this as a base: https://github.com/Eldorados/script.module.urlresolver/blob/master/lib/urlresolver/plugins/realdebrid.py

Pyload client ID: ECQHUYL5SW3IS
Pyload client secret (should not be used in production as Pyload is opensource): efa447c564a000ab4f0efc8458e7d8776372149b
Pyload allowed methods: /user, /unrestrict, /traffic

Please ensure the User-Agent Pyload is sending is: "Pyload/X.XX" Where X.XX is the version of the client
If OAuth cannot be implemanted please tell me, we will enable the "Workflow for old apps" on Pyload's client ID (even if that's not the best thing in matter of security)

I would love to do it but Python is not my favorite language, if anybody needs an account to implemant this just tell me, it will be free of charge ;)

Thank's !

**Comment by anonymousse37** [comment]
Hi, @TheCrach 

I use Pyload for improving my use of RealDebrid but actually the plugin is not working.
Is this related to this request ? I mean, is this legit that the plugin doesnt work anymore ?

Ty.

Salut,

Je vois que tu es de Nantes ^^.
Tu taff chez RealDebrid ?
Le plugin pour Pyload ne marche plus. Est ce que c'est normal ? Etant donné que tu as l'air de faire une demande pour que le plugin soit refait...

@+

**Comment by vuolter** [comment]
@anonymousse37 See: https://github.com/pyload/pyload/issues/2191

**Comment by GammaC0de** [comment]
Closed. 👍
