### ISSUE TITLE
Issues and crashes with python 2.7.11

### ISSUE THREAD

**Issue by rathsky** [pyload/pyload#2183]
Since updating to python 2.7.11, my uploaded.to premium account is not recognized ⅘ of the time with
>error: (47, 'Maximum (5) redirects followed')

Occasionally it'll work for a few downloads, then somehow throw the error again.

Also, pyload also crashes randomly with

> KeyError: None

See the log where both happened one after the other. I tried updating pycurl 7.19.5.3 to its current git version (curl is 7.46), no change.

[pyload_log.txt](https://github.com/pyload/pyload/files/53150/pyload_log.txt) (replaced the account number)

**Comment by rathsky** [comment]
I've now downgraded to python 2.7.10, pcurl 7.19.5 and curl 7.45.0. Still getting the "Maximum (5) redirects followed".

**Comment by dmarc75** [comment]
The first error seems to be due to a change at uploaded.net, the URL pyload uses to get a cookie sends at least pyload into an eternal redirect-loop. But the fix is simple, simply change that initial URL:

    diff --git a/module/plugins/accounts/UploadedTo.py b/module/plugins/accounts/UploadedTo.py
    index c689dc1..a85af76 100644
    --- a/module/plugins/accounts/UploadedTo.py
    +++ b/module/plugins/accounts/UploadedTo.py
    @@ -59,7 +59,7 @@ class UploadedTo(Account):
     
     
         def signin(self, user, password, data):
    -        self.load("http://uploaded.net/language/en")
    +        self.load("http://uploaded.net/me")
     
             html = self.load("http://uploaded.net/io/login",
                              post={'id': user,

**Comment by rathsky** [comment]
Seems to work. Looks like it might also resolve the crash, though that KeyError probably still needs a proper error handling.

Thanks!
