### ISSUE TITLE
[Question] What happened with the SerienjunkiesOrg plugin?

### ISSUE THREAD

**Issue by frdmn** [pyload/pyload#2187]
I've heard and read a lot of people who used PyLoad in combination with serienjunkies.org. The past few days I've setup PyLoad but i'm missing any plugin related to the web site. 

Is there anything that I am missing here or did the plugin got removed?

If so, is there any third party one I can use instead?

**Comment by GammaC0de** [comment]
As pyload does not support illegal content, this is not included in pyload.See https://Gutz-Pilz/pyLoad-stuff for this

Sent from Yahoo Mail on Android 
 
  On יום ה׳, דצמ׳ 10, 2015 at 9:15, Jonas Friedmann<notifications@github.com> wrote:   
I've heard and read a lot of people who used PyLoad in combination with serienjunkies.org. The past few days I've setup PyLoad but i'm missing any plugin related to the web site. 

Is there anything that I am missing here or did the plugin got removed?

If so, is there any third party one I can use instead?

**Comment by frdmn** [comment]
I only use SJ for public domain content :grin::

https://en.wikipedia.org/wiki/List_of_TV_series_with_episodes_in_the_public_domain
