### ISSUE TITLE
get.pyload.org TLS certificate issue

### ISSUE THREAD

**Issue by frdmn** [pyload/pyload#2189]
![bildschirmfoto 2015-12-10 um 12 10 17](https://cloud.githubusercontent.com/assets/944459/11713974/fefa28e4-9f36-11e5-9421-c0b509c940cc.png)

**Comment by frdmn** [comment]
Also 404 for /get/src:

![bildschirmfoto 2015-12-10 um 12 10 53](https://cloud.githubusercontent.com/assets/944459/11713990/1a46b978-9f37-11e5-9aa3-78bc4698ca53.png)

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/releases

**Comment by frdmn** [comment]
Why did you close this? I am aware of the GitHub releases, but the issue still exists on your website.

Von meinem iPhone gesendet

**Comment by GammaC0de** [comment]
@frdmn This is a known issue since months.
Unfortunately, the current `pyLoad` collaborators does not have write access to the web site.
Only @RaNaN have this access and he has been away for a long time now

**Comment by frdmn** [comment]
Ah okay, well now that's plausible.
