### ISSUE TITLE
Real Debrid problem won't get links...

### ISSUE THREAD

**Issue by alienx2** [pyload/pyload#2191]
I did tried installed latest version from this git but problem is every link (uptobox,file factory, uploaded,etc) is always direct instead of realdebrid. realdebrid account is working valid but download is not working.

similar to issue #1360 problem.

 by the way, I'm new to use this pyload and plan to set up it on NAS router.

**Comment by anonymousse37** [comment]
Yeah got the same issue :

XXXX> cd /opt/share/pyload
XXXX> pyLoadCore
22.12.2015 01:18:23 INFO      Starting pyLoad 0.4.9
22.12.2015 01:18:23 INFO      Using home directory: /opt/share/pyload_config
22.12.2015 01:18:23 DEBUG     Remote activated: True
22.12.2015 01:18:23 DEBUG     created index of plugins
22.12.2015 01:18:23 INFO      ExtractArchive: Activated UnRar
22.12.2015 01:18:23 INFO      Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, RealdebridCom, UpdateManager
22.12.2015 01:18:23 INFO      Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RehostTo, XMPPInterface
22.12.2015 01:18:23 INFO      Downloadtime: True
22.12.2015 01:18:23 INFO      Starting ThriftBackend: 0.0.0.0:7227
22.12.2015 01:18:23 INFO      Starting builtin webserver: 192.168.1.20:8000
22.12.2015 01:18:23 INFO      Free space: 451.63 GiB
22.12.2015 01:18:23 INFO      Activating Accounts...
22.12.2015 01:18:24 DEBUG     RealdebridCom: Get Account Info for XXXXX
22.12.2015 01:18:24 DEBUG     RealdebridCom: Account Info: {'validuntil': XXXXX, 'trafficleft': -1}
22.12.2015 01:18:24 INFO      Activating Plugins...
22.12.2015 01:18:24 DEBUG     RealdebridCom: Overwritten Hosters: DlFreeFr, EasybytezCom, FilefactoryCom, LetitbitNet, LoadTo, MediafireCom, MegasharesCom, RedtubeCom, SendspaceCom, ShareonlineBiz, UlozTo, UploadedTo, UploadingCom, YoupornCom, YoutubeCom, ZippyshareCom
22.12.2015 01:18:24 DEBUG     RealdebridCom: New Hosters: 1fichier.com, 2shared.com, 4shared.com, 5xpan.com, allmyvideos.net, alterupload.com, canalplus.fr, catshare.net, cbs.com, cjoint.net, cloudtime.to, dailymotion.com, datafile.com, datafilehost.com, datei.to, depfile.com, desfichiers.com, dfichiers.com, divxstage.eu, divxstage.to, dl4free.com, exashare.com, extmatrix.com, filecloud.io, fileflyer.com, filemarkets.com, fileover.net, filerio.com, filerio.in, filesabc.com, filesflash.com, filesflash.net, filesmonster.com, gboxes.com, gigapeta.com, gigasize.com, gulfup.com, hugefiles.net, hulkshare.com, i-filez.com, k2s.cc, k2share.cc, keep2s.cc, keep2share.cc, luckyshare.net, mega.co.nz, mega.nz, megadl.fr, mesfichiers.org, movshare.net, nitroflare.com, novamov.com, nowdownload.ag, nowdownload.at, nowdownload.ch, nowdownload.ec, nowdownload.eu, nowdownload.li, nowdownload.sx, nowvideo.ag, nowvideo.at, nowvideo.ch, nowvideo.eu, nowvideo.li, nowvideo.sx, oboom.com, piecejointe.net, pjointe.com, purevid.com, radiotunes.com, rapidgator.net, rarefile.net, redbunker.net, rg.to, rockfile.eu, rutube.ru, scribd.com, secureupload.eu, shareflare.net, sky.fm, soundcloud.com, speedyshare.com, tenvoi.com, thevideo.me, turbobit.net, tusfiles.net, ul.to, ulozto.net, ulozto.sk, unibytes.com, uplea.com, uploadable.ch, uploaded.net, uploadrocket.net, upstore.net, uptobox.com, userporn.com, veevr.com, vimeo.com, vip-file.com, vipfile.in, wat.tv, wholecloud.net, youwatch.org, yunfile.com
22.12.2015 01:18:24 INFO      pyLoad is up and running
22.12.2015 01:18:27 WARNING   Not able to connect server for updates
22.12.2015 01:18:27 INFO      No Updates for pyLoad
22.12.2015 01:18:27 WARNING   Not able to connect server for updates
22.12.2015 01:18:27 INFO      No plugin updates available
22.12.2015 01:18:46 INFO      Added package acd containing 1 links
22.12.2015 01:18:46 INFO      Download starts: https://1fichier.com/?XXXXX
22.12.2015 01:18:46 DEBUG     Real-Debrid: Old URL: https://1fichier.com/?XXXXX
Traceback (most recent call last):
  File "/opt/lib/python2.5/logging/__init__.py", line 752, in emit
    self.stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 253: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/lib/python2.5/logging/__init__.py", line 752, in emit
    self.stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 253: ordinal not in range(128)
22.12.2015 01:18:47 DEBUG     Chunk 1 failed: (6, "Couldn't resolve host '%3C!DOCTYPE%20html%20PUBLIC%20%22-'")
22.12.2015 01:18:47 DEBUG     pycurl exception 6: Couldn't resolve host '%3C!DOCTYPE%20html%20PUBLIC%20%22-'
22.12.2015 01:18:47 ERROR     pycurl error 6: Couldn't resolve host '%3C!DOCTYPE%20html%20PUBLIC%20%22-'
Traceback (most recent call last):
  File "/opt/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/opt/share/pyload/module/plugins/Plugin.py", line 237, in preprocessing
    return self.process(self.pyfile)
  File "/opt/share/pyload/module/plugins/hoster/RealdebridCom.py", line 77, in process
    self.download(new_url, disposition=True)
  File "/opt/share/pyload/module/plugins/Plugin.py", line 503, in download
    progressNotify=self.pyfile.setProgress, disposition=disposition)
  File "/opt/share/pyload/module/network/Browser.py", line 88, in httpDownload
    name = self.dl.download(chunks, resume)
  File "/opt/share/pyload/module/network/HTTPDownload.py", line 129, in download
    self._download(chunks, resume)
  File "/opt/share/pyload/module/network/HTTPDownload.py", line 260, in _download
    raise ex
error: (6, "Couldn't resolve host '%3C!DOCTYPE%20html%20PUBLIC%20%22-'")
22.12.2015 01:18:47 DEBUG     Error creating zip file: 'ascii' codec can't decode byte 0xba in position 11: ordinal not in range(128)
22.12.2015 01:18:47 INFO      Debug Report written to debug_RealdebridCom_22-12-2015_01-18-47.txt
22.12.2015 01:18:47 DEBUG     All downloads processed

**Comment by vuolter** [comment]
Until I don't complete the MultiAccount plugin all the MultiHoster plugins will stay unusable. :(

**Comment by Brueggus** [comment]
@vuolter What are your plans for the Multiaccount plugin? Is there anything I can help out with?

I love pyload, but without multihoster support it's pretty much useless for me for about three months now :(

**Comment by vuolter** [comment]
@Brueggus I wanna finish this damn plugin with all my heart! :smiling_imp:

**Comment by anonymousse37** [comment]
Hi,

Any news from now on ?

XXX

**Comment by vuolter** [comment]
MultiHoster is complete but under merging in pyLoad 0.5 .

**Comment by Sparx710** [comment]
@vuolter is it included in a specific branch?
