### ISSUE TITLE
Easybytez connection time out

### ISSUE THREAD

**Issue by redeemer666** [pyload/pyload#2192]
It's a couple of days that I can't download from easybytez. On the account page it says that my premium account is "not valid", and here what happens in the log:
EasybytezCom: Could not login with account xxx | (28, 'connect() timed out!')
I can access and login fine on my browser

Some advice? Thank you

**Comment by redeemer666** [comment]
Hello, my account is "redeemer666".

I have tried to delete the userplugins folder, found in another thread and now here's what's happening:
WARNING   Not able to connect server for updates

**Comment by redeemer666** [comment]
Hello again.
I've used the update manager from this case https://github.com/pyload/pyload/issues/1893 and now it seems resolved.

**Comment by GammaC0de** [comment]
:+1:
