### ISSUE TITLE
OneFichierCom 0.95

### ISSUE THREAD

**Issue by jpedraza80** [pyload/pyload#2193]
Unable to download files from onefichier.com

Urls:
http://ixqbi6qwvf.1fichier.com/
http://6rg566nawh.1fichier.com/
http://w8476kugg0.1fichier.com/

Errors:
>87DO1700CAG.part03.rar
>fallido[Errno 22] invalid mode ('wb') or filename: '/media/SSD/downloads/SIM4GT/87DO1700CAG.part03.rar filename*=UTF-887DO1700CAG.part03.rar' 700.00 MiBOneFichierCom

>87DO1700CAG.part04.rar
>fallidoFile size mismatch | Expected file size: 734003200 | Downloaded file size: 11016 0.00 B

Debug trace

>12.12.2015 22:32:04 INFO      Download starts: 87DO1700CAG.part02.rar
>12.12.2015 22:32:04 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
>12.12.2015 22:32:04 DEBUG     HOSTER OneFichierCom[2]: Plugin version: 0.95
>12.12.2015 22:32:04 DEBUG     HOSTER OneFichierCom[2]: Plugin status: testing
>12.12.2015 22:32:04 WARNING   HOSTER OneFichierCom[2]: Plugin may be unstable
>12.12.2015 22:32:05 INFO      HOSTER OneFichierCom[2]: Grabbing link info...
>12.12.2015 22:32:07 INFO      Download starts: 87DO1700CAG.part02.rar
>12.12.2015 22:32:07 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
>12.12.2015 22:32:07 DEBUG     HOSTER OneFichierCom[2]: Plugin version: 0.95
>12.12.2015 22:32:07 DEBUG     HOSTER OneFichierCom[2]: Plugin status: testing
>12.12.2015 22:32:07 WARNING   HOSTER OneFichierCom[2]: Plugin may be unstable
>12.12.2015 22:32:07 INFO      HOSTER OneFichierCom[2]: Grabbing link info...
>12.12.2015 22:32:08 DEBUG     HOSTER OneFichierCom[2]: Link info: {'status': 2, 'pattern': {'HOST': u'1fichier.com', 'U': u'MB', 'S': u'700', 'N': u'87DO1700CAG.part02.rar'}, 'size': 734003200, 'url': u'http://6rg566nawh.1fichier.com/', 'name': u'87DO1700CAG.part02.rar'}
>12.12.2015 22:32:08 DEBUG     HOSTER OneFichierCom[2]: Previous link info: {}
>12.12.2015 22:32:08 INFO      HOSTER OneFichierCom[2]: Link name: 87DO1700CAG.part02.rar
>12.12.2015 22:32:08 INFO      HOSTER OneFichierCom[2]: Link size: 700.00 MiB (734003200 bytes)
>12.12.2015 22:32:08 INFO      HOSTER OneFichierCom[2]: Link status: en línea
>12.12.2015 22:32:08 INFO      HOSTER OneFichierCom[2]: Looking for direct download link...
>12.12.2015 22:32:08 DEBUG     HOSTER OneFichierCom[2]: Redirect #0 to: http://6rg566nawh.1fichier.com/
>12.12.2015 22:32:08 DEBUG     HOSTER OneFichierCom[2]: LOAD URL http://6rg566nawh.1fichier.com/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
>12.12.2015 22:32:09 DEBUG     HOSTER OneFichierCom[2]: Redirect #1 to: https://6rg566nawh.1fichier.com/
>12.12.2015 22:32:09 DEBUG     HOSTER OneFichierCom[2]: LOAD URL https://6rg566nawh.1fichier.com/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
>12.12.2015 22:32:10 DEBUG     HOSTER OneFichierCom[2]: Link info: {'status': 2, 'name': u'87DO1700CAG.part02.rar', 'url': u'http://6rg566nawh.1fichier.com/', 'pattern': {'HOST': u'1fichier.com', 'U': u'MB', 'S': u'700', 'N': u'87DO1700CAG.part02.rar'}, 'size': 734003200}
>12.12.2015 22:32:10 DEBUG     HOSTER OneFichierCom[2]: Previous link info: {}
>12.12.2015 22:32:10 INFO      HOSTER OneFichierCom[2]: Link name: 87DO1700CAG.part02.rar
>12.12.2015 22:32:10 INFO      HOSTER OneFichierCom[2]: Link size: 700.00 MiB (734003200 bytes)
>12.12.2015 22:32:10 INFO      HOSTER OneFichierCom[2]: Link status: en línea
>12.12.2015 22:32:10 INFO      HOSTER OneFichierCom[2]: Looking for direct download link...
>12.12.2015 22:32:10 DEBUG     HOSTER OneFichierCom[2]: Redirect #0 to: http://6rg566nawh.1fichier.com/
>12.12.2015 22:32:10 DEBUG     HOSTER OneFichierCom[2]: LOAD URL http://6rg566nawh.1fichier.com/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
>12.12.2015 22:32:11 DEBUG     pycurl exception 0: ('cannot invoke setopt() - perform() is currently running',)
>12.12.2015 22:32:11 ERROR     pycurl error 0: ('cannot invoke setopt() - perform() is currently running',)
>12.12.2015 22:32:11 INFO      HOSTER OneFichierCom[2]: Direct download link not found
>12.12.2015 22:32:11 WARNING   Download failed: 87DO1700CAG.part02.rar | fallido
>12.12.2015 22:32:11 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: 87DO1700CAG.part02.rar (pid:1)
>12.12.2015 22:32:11 INFO      ADDON UnSkipOnFail: No duplicates found
>12.12.2015 22:32:11 INFO      Debug Report written to debug_OneFichierCom_12-12-2015_22-32-11.zip
>12.12.2015 22:32:11 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: 87DO1700CAG.part02.rar (pid:1)
>12.12.2015 22:32:11 DEBUG     All downloads processed
>12.12.2015 22:32:11 INFO      ADDON UnSkipOnFail: No duplicates found
>12.12.2015 22:32:11 DEBUG     All downloads processed
>12.12.2015 22:32:12 WARNING   Download failed: 87DO1700CAG.part02.rar | 'NoneType' object has no attribute 'id'
>12.12.2015 22:32:12 DEBUG     All downloads processed

**Comment by GammaC0de** [comment]
@jpedraza80 Can you try this patch?
```patch
--- module/plugins/hoster/OneFichierCom.py	(date 1449411681000)
+++ module/plugins/hoster/OneFichierCom.py	(revision )
@@ -9,10 +9,10 @@
 class OneFichierCom(SimpleHoster):
     __name__    = "OneFichierCom"
     __type__    = "hoster"
-    __version__ = "0.95"
+    __version__ = "0.96"
     __status__  = "testing"
 
-    __pattern__ = r'https?://(?:www\.)?(?:\w+\.)?(?P<HOST>1fichier\.com|alterupload\.com|cjoint\.net|d(es)?fichiers\.com|dl4free\.com|megadl\.fr|mesfichiers\.org|piecejointe\.net|pjointe\.com|tenvoi\.com)(?:/\?\w+)?'
+    __pattern__ = r'https?://(?:www\.)?(?:\w+\.)?(?P<HOST>1fichier\.com|alterupload\.com|cjoint\.net|d(?:es)?fichiers\.com|dl4free\.com|megadl\.fr|mesfichiers\.org|piecejointe\.net|pjointe\.com|tenvoi\.com)(?:/\?\w+)?'
     __config__  = [("activated"   , "bool", "Activated"                                        , True),
                    ("use_premium" , "bool", "Use premium account if available"                 , True),
                    ("fallback"    , "bool", "Fallback to free download if premium fails"       , True),
@@ -28,7 +28,8 @@
                        ("stickell", "l.stickell@yahoo.it"),
                        ("Elrick69", "elrick69[AT]rocketmail[DOT]com"),
                        ("Walter Purcaro", "vuolter@gmail.com"),
-                       ("Ludovic Lehmann", "ludo.lehmann@gmail.com")]
+                       ("Ludovic Lehmann", "ludo.lehmann@gmail.com"),
+                       ("GammaC0de", "nitzo2001[AT]yahoo[DOT]com")]
 
 
     URL_REPLACEMENTS = [("https:", "http:")]  #@TODO: Remove in 0.4.10
@@ -41,9 +42,8 @@
 
     WAIT_PATTERN = r'>You must wait \d+ minutes'
 
-
     def setup(self):
-        self.multiDL        = self.premium
+        self.multiDL         = self.premium
         self.resume_download = True
 
 
@@ -96,11 +96,11 @@
 
         inputs['submit'] = "Download"
 
-        self.download(url, post=inputs)
+        self.download(url, post=inputs, disposition=False)  #@TODO: Remove disposition in 0.4.10
 
 
     def handle_premium(self, pyfile):
-        self.download(pyfile.url, post={'did': 0, 'dl_no_ssl': "on"})
+        self.download(pyfile.url, post={'did': 0, 'dl_no_ssl': "on"}, disposition=False)  #@TODO: Remove disposition in 0.4.10
 
 
 getInfo = create_getInfo(OneFichierCom)
```

**Comment by jpedraza80** [comment]
Great, the downloads works again, ty
