### ISSUE TITLE
UploadedTo: Premium download link not found

### ISSUE THREAD

**Issue by githubrsys** [pyload/pyload#2195]
## Summary

Premium Account is set, active and valid. Downloading fails due error shown below. Any captcha in fallback mode is recognized as invalid.

### Log
````
WARNING	UploadedTo[11]: 
Premium download failed | 
Parse error: Premium download link not found | 
Plugin may be out of date
````

### System
Python:	2.5.5 (r255:77872, May 16 2010, 10:32:26) [GCC 4.2.1]
Betriebssystem:	posix linux2 Linux NAS 3.4.6 #1 SMP Tue Aug 25 11:00:47 CST 2015 x86_64
pyLoad Version:	0.4.9

**Comment by githubrsys** [comment]
### Workaround

switching to "direct download" in ulto settings, then download works.

**Comment by GammaC0de** [comment]
duplicate #2190
