### ISSUE TITLE
No issue this time, but help/advice needed

### ISSUE THREAD

**Issue by Arno-Nymous** [pyload/pyload#2199]
Hello folks,
I'm trying to help out a bit with issue fixing and wanted to setup an environment for efficiently debugging pyLoad. Sadly all my approaches didn't realy work out. On Windows pyLoad is missing some libraries like JS and such and I'm not familiar with how to install those libs on Windows. Addiotionally I set up a Linux VM with Eclipse and PyDev and can execute pyLoad there. Now the next problem is that PyDev won't stop on breakpoints in threads spawned for the plugins. As a matter of fact I nearly can't debug any plugin that runs in a thread.

Therefore I would appreciate any hints and suggestions on how to setup a reliable dev environment, especially from you guys @vuolter and @GammaC0de, since you contribute the most to this project.

Sorry for posting this here but I could not find anything on my problem that helped and I am somewhat lost and desperate here XD Debugging pyLoad only via command line and pdb is just crap :/

Cheers!

**Comment by GammaC0de** [comment]
Hi @Arno-Nymous, welcome aboard!
 
For windows package, you should use this: https://github.com/pyload/pyload/releases/download/v0.4.9/pyload-v0.4.9-win.zip (note that you have to fix `UpdateManager.py` as described in #2000)

For debugging, `self.log_debug()` is your best friend.
Running `pyLoadCore.py -d` would give you a lot of debugging information.
Also, `traceback.print_stack()' is sometimes usefull.

Happy pyLoading! :wink:
