### ISSUE TITLE
Support hflix.in and ugoupload.net

### ISSUE THREAD

**Issue by TheRadziu** [pyload/pyload#2201]
Since there is plugin request tag, I'll post this request here as well (I hope more devs will see it here than on forums)
Can someone add support for hflix.in and ugoupload.net ? here is example link

`
http://hflix.in/oucax
`

hflix.in redirects to ugoupload.net where actual download starts. 
Cheers!

**Comment by TheRadziu** [comment]
my pyloader updated and someone added hflix support, now only ugoupload.net remains to add.

**Comment by vuolter** [comment]
@GammaC0de made the hflix plugin yesterday. u.u

**Comment by GammaC0de** [comment]
URL is offline, need another one.

**Comment by TheRadziu** [comment]
Updated first post with correct link
