### ISSUE TITLE
Failed downloads stuck in queue

### ISSUE THREAD

**Issue by Velociraptor85** [pyload/pyload#2204]
Yap exactly what happens, also they cant be deleted via web interface and the restart does not work I guess its because of this Problem.

Tried redownload of userplugins ... does not help

Haven't found any Error messages

**Comment by GammaC0de** [comment]
Try deleting/renaming `files.db`

**Comment by Velociraptor85** [comment]
OK that would help but than my users would be gone

**Comment by GammaC0de** [comment]
if by 'users' you mean accounts, those are kept in `accounts.conf`.
Anyway, be sure to backup those files before any change

**Comment by Velociraptor85** [comment]
no by users I meant those you can configure in /admin

**Comment by GammaC0de** [comment]
well, if you know the passwords, these can be reconfigured by issuing `pyLoadCore --user`

**Comment by Velociraptor85** [comment]
I fixed it, thanks!
Downloaded the fies.db and opend it with the http://sqlitebrowser.org/ than deleted the faulty package and the links saved that and started pyload.

Thanks for the fast help.
Will try those links again to check if they are broke.

**Comment by Velociraptor85** [comment]
OK seems to work now.
Thank again

**Comment by GammaC0de** [comment]
you're welcome :+1:
