### ISSUE TITLE
question about SimpleHoster

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2205]
Shouldn't `SimpleHoster`'s`handle_free()` and `handle_premium()` call `self.check_errors()`?

With the current implementation, WAIT_PATTERN is totally ignored unless you override `handle_free()` and explicitly call it.

**Comment by vuolter** [comment]
Should be called after self.preload

**Comment by GammaC0de** [comment]
If you define both LINK_PATTERN and WAIT_PATTERN, no wait is done.

Should it be part of `SimpleHoster`? are you gonna add it?

**Comment by vuolter** [comment]
Yep, I'm working on SimpleHoster and other internal plugins. :disappointed: 
I'll check that issue tomorrow.
