### ISSUE TITLE
LinkCryptWs throws 'JS Error' messages due to recent site modifications

### ISSUE THREAD

**Issue by Arno-Nymous** [pyload/pyload#2207]
The LinkCryptWs crypter plugin issues some recent JS errors. This is due to some cosmetic code changes on the Linkcrypt.ws page. Though most of the time links can be parsed correctly it could happen that there is only the Click n Load button available. In that case the plugin cannot find the Click and Load section and throws this error.

I have no debug log prepared since I watched this problem for some time now and already got it fixed in my fork. I will post a pull request here soon.

So this issue can rather be treated for reference purpose.

**Comment by vuolter** [comment]
Waiting your PR. ;)
