### ISSUE TITLE
[OneFichierCom] Too many redirects

### ISSUE THREAD

**Issue by HydrelioxGitHub** [pyload/pyload#2208]
I do not know if it's related to changes you made @GammaC0de in #2196  but after working great for a time. There is another problem : 

```

540	22.12.2015 06:54:20	INFO	ADDON UnSkipOnFail: No duplicates found
539	22.12.2015 06:54:20	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: https://1fichier.com/?xxx (pid:54)
538	22.12.2015 06:54:20	WARNING	Download failed: https://1fichier.com/?xxx| Too many redirects
537	22.12.2015 06:54:20	INFO	HOSTER OneFichierCom[183]: Link status: échoué
536	22.12.2015 06:54:20	INFO	HOSTER OneFichierCom[183]: Link size: N/D
535	22.12.2015 06:54:20	INFO	HOSTER OneFichierCom[183]: Link name: https://1fichier.com/?xxx
534	22.12.2015 06:54:19	INFO	HOSTER OneFichierCom[183]: Grabbing link info...
533	22.12.2015 06:54:19	WARNING	HOSTER OneFichierCom[183]: Plugin may be unstable
532	22.12.2015 06:54:19	INFO	Download starts: https://1fichier.com/?xxx
```

All my links are failed because too many redirects ....

**Comment by vuolter** [comment]
Debug log please.

**Comment by HydrelioxGitHub** [comment]
Sorry not famliar with signaling issues (noob)

'''
796	22.12.2015 08:55:34	INFO	ADDON UnSkipOnFail: No duplicates found
795	22.12.2015 08:55:34	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: https://1fichier.com/?xxx (pid:54)
794	22.12.2015 08:55:34	WARNING	Download failed: https://1fichier.com/?xxx | Too many redirects
793	22.12.2015 08:55:34	INFO	HOSTER OneFichierCom[175]: Link status: échoué
792	22.12.2015 08:55:34	INFO	HOSTER OneFichierCom[175]: Link size: N/D
791	22.12.2015 08:55:34	INFO	HOSTER OneFichierCom[175]: Link name: https://1fichier.com/?xxx
790	22.12.2015 08:55:34	DEBUG	HOSTER OneFichierCom[175]: Previous link info: {}
789	22.12.2015 08:55:34	DEBUG	HOSTER OneFichierCom[175]: Link info: {'status': 8, 'error': u'Too many redirects'}
788	22.12.2015 08:50:34	INFO	HOSTER OneFichierCom[175]: Grabbing link info...
787	22.12.2015 08:50:34	WARNING	HOSTER OneFichierCom[175]: Plugin may be unstable
786	22.12.2015 08:50:34	DEBUG	HOSTER OneFichierCom[175]: Plugin status: testing
785	22.12.2015 08:50:34	DEBUG	HOSTER OneFichierCom[175]: Plugin version: 0.97
784	22.12.2015 08:50:34	INFO	Download starts: https://1fichier.com/?xxx
'''

**Comment by GammaC0de** [comment]
@HydrelioxGitHub Effected URL please

**Comment by HydrelioxGitHub** [comment]
https://1fichier.com/?ar1rcablei is one example but it affects all my 1fichier url ... Does it come from my setup ?

**Comment by GammaC0de** [comment]
@HydrelioxGitHub is down at the moment (http://downforeveryoneorjustme.com/1fichier.com)
