### ISSUE TITLE
pyLoad disregards additional premium accounts for the same hoster

### ISSUE THREAD

**Issue by twwn** [pyload/pyload#2211]
Apparently pyLoad completely ignores the presence of any other premium accounts for a specific hoster (UploadedTo in my case).

Eg, you have two premium accounts for a hoster: pyLoad consistently uses only a certain one to query remaining traffic, and uses only this one for premium downloads. IOW, the second one remains completely unused.

Expected would be pyLoad querying all relevant accounts for the next download and using the one with the highest (sufficient) traffic left.

**Comment by GammaC0de** [comment]
@rathsky Currently `pyLoad` does not support more than one premium account per hoster.

**Comment by djessich** [comment]
@GammaC0de Is there any progress on this yet?

**Comment by GammaC0de** [comment]
@djessich Well?

**Comment by honk-e-tonk** [comment]
Hello @GammaC0de , i got the same Problem with more than 1 Share-Online Premium accounts.
Is there any possibility to at lease SEE when no premium ammount is left? I cannot even see any entry in the logfile in that case. There will be checks before starting to download a new link ( out_of_traffic in Hoster.py, used in SimpleHoster.py) but i wonder why it dosent create any message in logfile, when theres no premium traffic left. Is it possible to get at least some kind of warning in that case? Of course i would prefer a multi-premium-account solution.
Thanks in advance, Honk-E-Tonk

**Comment by GammaC0de** [comment]
@honk-e-tonk pyLoad calles out_of_traffic() only if  CHECK_TRAFFIC == True.
By default CHECK_TRAFFIC  is set to False.

So what you would want to do is set CHECK_TRAFFIC  to True for ShareonlineBiz  plugin (see [UploadedTo.py#L32](https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/UploadedTo.py#L32) for example).

**Comment by honk-e-tonk** [comment]
ok - i will give it a try... thx

**Comment by honk-e-tonk** [comment]
Hello @GammaC0de !
Well - i found the time to try but remarked the CHECK_TRAFFIC already set to true. i can see the ammount of traffic left to be count down, but i get no message like "no traffic left" when traffic is used up - the download simply stops or switches to free mode. 
multiple premium accounts are listed in the accounts list, so there must be a possibility to switch them when on of them runs out of traffic. is it a bug? or simply not implemented. The project ist quite large and complex and i was trying to find out dependencies of all the modules, but i guess i just dont have enough time to figure all out.
is there a possibility for you to add this feature in future? As workaround i intended to get warned when traffic is used up, shutdown pyload, change account and restart it again. but i even dont get a clear signal when to do so.

**Comment by GammaC0de** [comment]
@honk-e-tonk Sorry but I cannot test it because I do not have multiple premium accounts :(

**Comment by advorsky73** [comment]
yes.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by advorsky73** [comment]
done.

**Comment by advorsky73** [comment]
one of the 2 is out of traffic atm, which causes weird display issues in the account page as well, maybe you can take a look at that as well?

**Comment by advorsky73** [comment]
Don't get me wrong, I am not in a hurry...
But do you need something else I could provide fot this topic ?

**Comment by GammaC0de** [comment]
Sorry for keeping you waiting.
I'm working on it this moment.
I pinpointed the bug, working on a solution. 😉

**Comment by GammaC0de** [comment]
@advorsky73 Please test

**Comment by advorsky73** [comment]
@GammaC0de it starts now downloading with 2 premium accounts of the same downloader, but only if pyload is freshly started.
As soon as you move around the packages from queue to packages, stop a few downloads and start them again, move the packages back, then the accounts are both shown as valid but NO premium in accounts page again.
I took the /develop branch for testing, this is correct right ?

**Comment by GammaC0de** [comment]
> it starts now downloading with 2 premium accounts of the same downloader, but only if pyload is freshly started

Are you sure? How can you tell?


> Then the accounts are both shown as valid but NO premium in accounts page again

This is a problem with this specific hoster that asks for captha even for premium account, I'll see if I can do something with that..

**Comment by advorsky73** [comment]
the valid/NO premium occurs as well with filer.net accounts btw :( 

> Are you sure? How can you tell?
Well, i think i put that to be easy misunderstood. what i ment was, that when 2 accounts of ddownload.com are entered in the accounts page, and i add a package to download, it will start using the 2nd account in the list.
previously, this did not happen, as both accounts switched to valid/no premium immediatly when trying to start a download.

**Comment by GammaC0de** [comment]
> the valid/NO premium occurs as well with filer.net accounts btw :(

Was it happening before this update?

**Comment by advorsky73** [comment]
> > the valid/NO premium occurs as well with filer.net accounts btw :(
> 
> Was it happening before this update?

Yes. Even on 0.40

**Comment by GammaC0de** [comment]
> Yes. Even on 0.40

Are you telling this from your **past** experience or have you tested this now on a old pyload?
This is important because pyload will use the updated account plug-in even on old version...

**Comment by advorsky73** [comment]
> > Yes. Even on 0.40
> 
> Are you telling this from your **past** experience or have you tested this now on a old pyload? This is important because pyload will use the updated account plug-in even on old version...

I am running develop branch and another 0.40 in parallel. So current experience.

**Comment by GammaC0de** [comment]
Now premium DDownload forks fine after https://github.com/pyload/pyload/commit/5c67a158ca3132d8bf706f5f24e2f1a8afb4a7a9, the account remains premium.

I still have so solve the account switching.

**Comment by GammaC0de** [comment]
P.S.
If you want me to test filer.net, please send accounts.

**Comment by advorsky73** [comment]
Currently i do own only 1 filer account. as soon as i got another one, i will send it to you.

>Now premium DDownload works fine after https://github.com/pyload/pyload/commit/5c67a158ca3132d8bf706f5f24e2f1a8afb4a7a9, the account remains premium.

That's great to hear !  This already is a great achievement ;)

> I still have so solve the account switching.

Which strategy are you going to implement?
- Drain one account, then use next in order of appearance
- Balance load on both accounts (could be great if e.g. the amount of DLs is limited on an account as it would double the dl slots basically)

And could this be done as a setting so the user can choose the strategy? 
As usual... Take your time, and if I can assist with testing anything, please let me know !

**Comment by GammaC0de** [comment]
OK,
Account switching should be now fixed,
Please test.

> Which strategy are you going to implement?
>
>  *  Drain one account, then use next in order of appearance
>  *  Balance load on both accounts (could be great if e.g. the amount of DLs is limited on an account as it would double the dl slots basically)
>
>And could this be done as a setting so the user can choose the strategy?


Currently the oldest used account is chosen, so this make the account usage rotate.
To drain one account and then use the other, you would have to assign a priority to an account so the usage order can be determined.

**Comment by advorsky73** [comment]
I will start testing tonight. Getting the develop branch will be sufficient I guess?

**Comment by advorsky73** [comment]
> Currently the oldest used account is chosen, so this make the account usage rotate.
To drain one account and then use the other, you would have to assign a priority to an account so the usage order can be determined.

yes it works! Both accounts get drained almost equally during downloads. its hard to see in the logs as both accounts start with AL...., though i think it takes them alternating.
So this should be working for all account types, correct?

**Comment by GammaC0de** [comment]
> So this should be working for all account types, correct?

Yes

**Comment by advorsky73** [comment]
Seems to work fine for ddownload now. Thanks a lot !!!
Short question though: how are the max connections handled? 
I have seen that if i have e.g. 10 in both, it will in summary only open 10.
What would happen if I have e.g. 5 and 10 in the 2 account settings?

**Comment by GammaC0de** [comment]
> Short question though: how are the max connections handled?
I have seen that if i have e.g. 10 in both, it will in summary only open 10.
What would happen if I have e.g. 5 and 10 in the 2 account settings?

I have to check this
