### ISSUE TITLE
UploadedTo - 'NoneType' object has no attribute 'size'

### ISSUE THREAD

**Issue by kasperj** [pyload/pyload#2214]
Some downloads fail randomly, error log is shown below, after this error all files all downloaded separately, never 2 at the same, or even 10 like before the error occurred, need to restart payload to fix this, same download runs trough without an issue

24.12.2015 03:21:11	INFO	ADDON UnSkipOnFail: No duplicates found
24.12.2015 03:21:11	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: tvs-the-leftovers-dd51-sed-dl-18p-hdtv-x264-108.part10.rar (pid:18)
24.12.2015 03:21:11	WARNING	Download failed: tvs-the-leftovers-dd51-sed-dl-18p-hdtv-x264-108.part10.rar | 'NoneType' object has no attribute 'size'
24.12.2015 03:21:03	INFO	ADDON UnSkipOnFail: No duplicates found
24.12.2015 03:21:03	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: tvs-the-leftovers-dd51-sed-dl-18p-hdtv-x264-108.part10.rar (pid:18)
24.12.2015 03:21:03	WARNING	Download failed: tvs-the-leftovers-dd51-sed-dl-18p-hdtv-x264-108.part10.rar | dl
24.12.2015 03:20:03	INFO	HOSTER UploadedTo[186]: Downloading file...
24.12.2015 03:20:03	INFO	HOSTER UploadedTo[186]: Direct download link detected
24.12.2015 03:20:00	INFO	HOSTER UploadedTo[186]: Looking for direct download link...
24.12.2015 03:20:00	INFO	HOSTER UploadedTo[186]: Link status: online
24.12.2015 03:20:00	INFO	HOSTER UploadedTo[186]: Link size: 101.00 MiB (105906176 bytes)
24.12.2015 03:20:00	INFO	HOSTER UploadedTo[186]: Link name: tvs-the-leftovers-dd51-sed-dl-18p-hdtv-x264-108.part10.rar
24.12.2015 03:19:58	INFO	HOSTER UploadedTo[186]: Grabbing link info...
24.12.2015 03:19:58	INFO	ACCOUNT UploadedTo: Grabbing account info for user `13153325`...
24.12.2015 03:19:58	WARNING	HOSTER UploadedTo[186]: Plugin may be unstable
24.12.2015 03:19:58	INFO	Download starts: tvs-the-leftovers-dd51-sed-dl-18p-hdtv-x264-108.part10.rar

**Comment by vuolter** [comment]
Retry now.

**Comment by kasperj** [comment]
The error happens quite unpredictable and randomly, so it's hard to say, but i'll keep an eye on it and will report if the issue is coming up again or not.

**Comment by sraedler** [comment]
I had no errors since weeks, so I guess it is fixed?
