### ISSUE TITLE
UploadedTo - Free download with valid premium account

### ISSUE THREAD

**Issue by kasperj** [pyload/pyload#2215]
Some uploaded downloads fail, because there is no direct download link found and no one enters the captcha for the free download, after this fallback there is only one download at the same time, despite the setting, restart fixes the problem and download is processed as premium

24.12.2015 03:49:55	INFO	HOSTER UploadedTo[254]: Processing as free download...
24.12.2015 03:49:55	INFO	HOSTER UploadedTo[254]: Direct download link not found
24.12.2015 03:49:54	INFO	HOSTER UploadedTo[254]: Looking for direct download link...
24.12.2015 03:49:54	INFO	HOSTER UploadedTo[254]: Link status: online
24.12.2015 03:49:54	INFO	HOSTER UploadedTo[254]: Link size: 101.00 MiB (105906176 bytes)
24.12.2015 03:49:54	INFO	HOSTER UploadedTo[254]: Link name: tvs-the-leftovers-dd51-sed-dl-18p-hdtv-x264-110.part05.rar
24.12.2015 03:49:54	INFO	HOSTER UploadedTo[254]: Grabbing link info...
24.12.2015 03:49:53	INFO	ACCOUNT UploadedTo: Grabbing account info for user `13153325`...
24.12.2015 03:49:53	WARNING	HOSTER UploadedTo[254]: Plugin may be unstable
24.12.2015 03:49:53	INFO	Download starts: http://uploaded.net/file/cgovzzwq/tvs-the-leftovers-dd51-sed-dl-18p-hdtv-x264-110.part05.rar

**Comment by GammaC0de** [comment]
@kasperj did you enabled "direct download" in ulto settings?

**Comment by kasperj** [comment]
@GammaC0de DDL is enabled all time

**Comment by GammaC0de** [comment]
DEBUG log please

**Comment by kasperj** [comment]
Hard to reproduce because it happens randomly, no specific DL, trying my best to provide you with all debug log

**Comment by GammaC0de** [comment]
:+1:

**Comment by kasperj** [comment]
Having pyLoad running in debug mode for a few days now, error didn't came up again, just to let you know i'm still on it :P

**Comment by GammaC0de** [comment]
I am closing this now, if the problem still persists, please let me know.

**Comment by kasperj** [comment]
Right now its hard to tell, because Serienjunkies is not working, i'll report if the problem comes back.
