### ISSUE TITLE
[Easybytez] - Premium not working

### ISSUE THREAD

**Issue by erse80** [pyload/pyload#2217]
Hi premium options not working all download are handled as Free

In Debug mode i recive this error
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | Config option `use_premium` not found, use default `True`

Full Debug:

24.12.2015 22:00:51 INFO      Download starts: frmtmtotmbd.part1.rev
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | Plugin version: 0.63
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | Plugin status: testing
24.12.2015 22:00:51 WARNING   HOSTER XFileSharing[2]: WwwEasybytezCom | Plugin may be unstable
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | Config option `use_premium` not found, use default `True`
24.12.2015 22:00:51 INFO      HOSTER XFileSharing[2]: WwwEasybytezCom | Grabbing link info...
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | Link info: {'status': 2, 'pattern': {'S': u'252.0', 'U': u'MB', 'N': u'frmtmtotmbd.part1.rev'}, 'size': 264241152, 'url': u'http://www.easybytez.com/tv6ag5dttg5q', 'name': u'frmtmtotmbd.part1.rev'}
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | Previous link info: {}
24.12.2015 22:00:51 INFO      HOSTER XFileSharing[2]: WwwEasybytezCom | Link name: frmtmtotmbd.part1.rev
24.12.2015 22:00:51 INFO      HOSTER XFileSharing[2]: WwwEasybytezCom | Link size: 252.00 MiB (264241152 bytes)
24.12.2015 22:00:51 INFO      HOSTER XFileSharing[2]: WwwEasybytezCom | Link status: online
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | LOAD URL http://www.easybytez.com/tv6ag5dttg5q | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
24.12.2015 22:00:51 INFO      HOSTER XFileSharing[2]: WwwEasybytezCom | Processing as free download...
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | Getting download link #1...
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | {u'method_premium': u'Premium Download', u'usr_login': '', u'referer': '', u'fname': u'frmtmtotmbd.part1.rev', u'method_free': u'Free Download', u'id': u'tv6ag5dttg5q', u'op': u'download1'}
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | LOAD URL http://www.easybytez.com/tv6ag5dttg5q | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'usr_login': '', u'referer': '', u'fname': u'frmtmtotmbd.part1.rev', u'method_free': 'Free Download', u'id': u'tv6ag5dttg5q', u'op': u'download1'} | ref=True | just_header=False
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | Getting download link #2...
24.12.2015 22:00:51 WARNING   HOSTER XFileSharing[2]: WwwEasybytezCom | You have to wait 21 minutes, 27 seconds till next download
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | Config option `max_wait` not found, use default `10`
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | WAIT set to timestamp 1450992139.600496 | Previous waitUntil: 0.000000
24.12.2015 22:00:51 DEBUG     HOSTER XFileSharing[2]: WwwEasybytezCom | RECONNECT  required | Previous wantReconnect: False
24.12.2015 22:00:51 INFO      HOSTER XFileSharing[2]: WwwEasybytezCom | Waiting 21 minutes, 27 seconds...
24.12.2015 22:00:51 INFO      HOSTER XFileSharing[2]: WwwEasybytezCom | Requiring reconnection...

**Comment by GammaC0de** [comment]
duplicate #2221

**Comment by erse80** [comment]
I did not understand what issues is duplicate... and if have a solution...

**Comment by GammaC0de** [comment]
Hi,
This is the same issue as in #2221 (EasyBytez premium processed as free) and without an account I cannot proceed
