### ISSUE TITLE
EasyBytez premium processed as free by XFileSharing

### ISSUE THREAD

**Issue by kirner** [pyload/pyload#2221]
Hello, seems there is a bad formatting for request anyway this is my debug:

26.12.2015 10:33:52 INFO      ADDON UpdateManager: All plugins are up to date!
26.12.2015 10:33:52 INFO      Download starts: Mad Max Fury Road (2015).Mkv.Ultra HD 4K 4096 x 2160 DTS ITA.part002.rev
26.12.2015 10:33:52 DEBUG     HOSTER XFileSharing[209]: WwwEasybytezCom | Plugin version: 0.63
26.12.2015 10:33:52 DEBUG     HOSTER XFileSharing[209]: WwwEasybytezCom | Plugin status: testing
26.12.2015 10:33:52 WARNING   HOSTER XFileSharing[209]: WwwEasybytezCom | Plugin may be unstable
26.12.2015 10:33:52 DEBUG     HOSTER XFileSharing[209]: WwwEasybytezCom | Config option `use_premium` not found, use default `True`
26.12.2015 10:33:52 INFO      HOSTER XFileSharing[209]: WwwEasybytezCom | Grabbing link info...
26.12.2015 10:33:53 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
26.12.2015 10:33:54 DEBUG     HOSTER XFileSharing[209]: WwwEasybytezCom | Link info: {'status': 2, 'pattern': {'S': u'255.0', 'U': u'MB', 'N': u'Mad Max Fury Road (2015).Mkv.Ultra HD 4K 4                                    096 x 2160 DTS ITA.part002.rev'}, 'size': 267386880, 'url': u'http://www.easybytez.com/6l1jmk7wy2g2/Mad Max Fury Road (2015).Mkv.Ultra HD 4K 4096 x 2160 DTS ITA.part002.rev', 'name': 'Mad                                     Max Fury Road (2015).Mkv.Ultra HD 4K 4096 x 2160 DTS ITA.part002.rev'}
26.12.2015 10:33:54 DEBUG     HOSTER XFileSharing[209]: WwwEasybytezCom | Previous link info: {}
26.12.2015 10:33:54 INFO      HOSTER XFileSharing[209]: WwwEasybytezCom | Link name: Mad Max Fury Road (2015).Mkv.Ultra HD 4K 4096 x 2160 DTS ITA.part002.rev
26.12.2015 10:33:54 INFO      HOSTER XFileSharing[209]: WwwEasybytezCom | Link size: 255.00 MiB (267386880 bytes)
26.12.2015 10:33:54 INFO      HOSTER XFileSharing[209]: WwwEasybytezCom | Link status: online
26.12.2015 10:33:54 DEBUG     HOSTER XFileSharing[209]: WwwEasybytezCom | LOAD URL http://www.easybytez.com/6l1jmk7wy2g2/Mad Max Fury Road (2015).Mkv.Ultra HD 4K 4096 x 2160 DTS ITA.part0                                    02.rev | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={} | ref=False | multipart=False
26.12.2015 10:33:54 INFO      HOSTER XFileSharing[209]: WwwEasybytezCom | Processing as free download...

**Comment by GammaC0de** [comment]
duplicate #2221
