### ISSUE TITLE
After last plugin update downloads won't start (EasyBytez.com at least)

### ISSUE THREAD

**Issue by darkpella** [pyload/pyload#2222]
Hi,

 about 2 hours ago pyLoad requested me to restart due to a plugin update.

 After I restarted pyLoad, download was set to off (normally after restart it is on).
Even I push the start button and download is set to on, downloads won't start.
Also, non download-related activity is logged.
I also tried rebooting to see whether it would work back normally, to no avail.
pyLoad runs on a syno DS 115 under DebianChRoot package.

bye

darkpella

> 256  26.12.2015 18:01:32	INFO	Avvio pyLoad 0.4.9
> 257	26.12.2015 18:01:32	INFO	Uso la cartella home: /volume1/home/pyload/.pyload
> 258	26.12.2015 18:01:37	INFO	Plugins attivati: ClickNLoad, DownloadScheduler, ExternalScripts, ExtractArchive, LinkdecrypterComHook, UnSkipOnFail, UpdateManager, UserAgentSwitcher
> 259	26.12.2015 18:01:37	INFO	Plugins disattivati: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, LogMarker, MergeFiles, MultiHome, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPPInterface
> 260	26.12.2015 18:01:37	INFO	Tempo di download: True
> 261	26.12.2015 18:01:37	INFO	Avvio ThriftBackend: 0.0.0.0:7227
> 262	26.12.2015 18:01:37	INFO	Spazio libero: 2.37 TiB
> 263	26.12.2015 18:01:37	INFO	Attivo gli Account...
> 264	26.12.2015 18:01:38	INFO	Starting builtin webserver: 0.0.0.0:8000
> 265	26.12.2015 18:01:38	INFO	ACCOUNT EasybytezCom: Adding user `darkpella`...
> 266	26.12.2015 18:01:38	INFO	ACCOUNT EasybytezCom: Login user `darkpella`...
> 267	26.12.2015 18:01:42	INFO	ACCOUNT EasybytezCom: Grabbing account info for user `darkpella`...
> 268	26.12.2015 18:56:19	INFO	Avvio pyLoad 0.4.9
> 269	26.12.2015 18:56:19	INFO	Uso la cartella home: /volume1/home/pyload/.pyload
> 270	26.12.2015 18:56:23	INFO	Plugins attivati: ClickNLoad, DownloadScheduler, ExternalScripts, ExtractArchive, LinkdecrypterComHook, UnSkipOnFail, UpdateManager, UserAgentSwitcher
> 271	26.12.2015 18:56:23	INFO	Plugins disattivati: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, LogMarker, MergeFiles, MultiHome, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPPInterface
> 272	26.12.2015 18:56:23	INFO	Tempo di download: True
> 273	26.12.2015 18:56:23	INFO	Avvio ThriftBackend: 0.0.0.0:7227
> 274	26.12.2015 18:56:24	INFO	Starting builtin webserver: 0.0.0.0:8000
> 275	26.12.2015 18:56:24	INFO	Free space: 2.38 TiB
> 276	26.12.2015 18:56:24	INFO	Activating Accounts...
> 277	26.12.2015 18:56:25	INFO	ACCOUNT EasybytezCom: Adding user `darkpella`...
> 278	26.12.2015 18:56:25	INFO	ACCOUNT EasybytezCom: Login user `darkpella`...
> 279	26.12.2015 18:56:29	INFO	ACCOUNT EasybytezCom: Grabbing account info for user `darkpella`...

**Comment by GammaC0de** [comment]
@darkpella What is the version of your `Account.py`?

**Comment by darkpella** [comment]
@GammaC0de How/where do I read it? 
What I found is the following: 
1. Under /volume1/@appstore/debian-chroot/var/chroottarget/usr/share/pyload/module/plugins/internal/Account.py
> class Account(Plugin):
>    __name__    = "Account"
>    __type__    = "account"
>    __version__ = "0.17"
>    __status__  = "testing"
>
>    __description__ = """Base account plugin"""
>    __license__     = "GPLv3"
>    __authors__     = [("Walter Purcaro", "vuolter@gmail.com")]
2.  Under /volume1/home/pyload/.pyload/userplugins/internal/Account.py
>class Account(Plugin):
>    __name__    = "Account"
>    __type__    = "account"
>    __version__ = "0.66"
>    __status__  = "stable"
>
>    __description__ = """Base account plugin"""
>    __license__     = "GPLv3"
>    __authors__     = [("Walter Purcaro", "vuolter@gmail.com")]

Don't know whether the value after "__version__" is what you asked me.
In case, the two Accounts.py files contain different data.

Best regards
Gianfranco Pellacani

**Comment by GammaC0de** [comment]
Replace `/volume1/home/pyload/.pyload/userplugins/internal/Account.py` with https://github.com/pyload/pyload/raw/stable/module/plugins/internal/Account.py then report back.

**Comment by darkpella** [comment]
@GammaC0de: just tried it, after restarting pyLoad downloads start regularly now.
Thanks mate!

**Comment by GammaC0de** [comment]
:+1:
