### ISSUE TITLE
ExtractArchive not working properly

### ISSUE THREAD

**Issue by redeemer666** [pyload/pyload#2224]
I have found a couple of issue for the Addon ExtractArchive:

1) Every time you change the addon settings and restart pyload, they come back to default mode.
2) It seems that some archives made with the latest version of winrar make the addon fail extraction.
3) If you deactivate "move trash instead delete" setting and the addon fail an extraction, it will delete the files anyway, forced you to redownload them all.

Thank you, and keep up the good work!!

**Comment by GammaC0de** [comment]
1) Try renaming (backing up) `plugin.conf` to `plugin.bak` and see if that helps
2) DEBUG log Please
3) DEBUG log Please

**Comment by redeemer666** [comment]
I'm preparing the debug log, will send you one ASAP.

About the issue (1): I can't find the plugin.conf file. Can you tell me where is located? Thank you

**Comment by redeemer666** [comment]
Here you go, the DEBUG log for issue (2) and (3)
28.12.2015 16:32:36	INFO	Package finished: prova
569	28.12.2015 16:32:36	DEBUG	All downloads processed
570	28.12.2015 16:32:36	DEBUG	ADDON ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
571	28.12.2015 16:32:36	DEBUG	All downloads finished
572	28.12.2015 16:32:37	INFO	ADDON ExtractArchive: Check package: prova
573	28.12.2015 16:32:37	DEBUG	ADDON ExtractArchive: Targets for UnRar: [('/share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar', 216, '/share/MD0_DATA/Download/pyload/')]
574	28.12.2015 16:32:37	INFO	ADDON ExtractArchive: Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar | Extract to: /share/MD0_DATA/Download/pyload/
575	28.12.2015 16:32:37	DEBUG	ADDON ExtractArchive: Password: None provided
576	28.12.2015 16:32:37	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar l -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -p- -v /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar
577	28.12.2015 16:32:37	DEBUG	ADDON ExtractArchive: Extracting using password: None
578	28.12.2015 16:32:37	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar x -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -p- /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar /share/MD0_DATA/Download/pyload/
579	28.12.2015 16:32:38	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar vb -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -p- -v /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar
580	28.12.2015 16:32:38	DEBUG	ADDON ExtractArchive: Would delete: /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rev, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part08.rar, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part03.rev, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part04.rev, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part07.rar, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part02.rar, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part04.rar, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part06.rar, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part03.rar, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part01.rev, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part01.rar, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part09.rar, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part02.rev, /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part06.rev
581	28.12.2015 16:32:38	INFO	ADDON ExtractArchive: Deleting 16 files
582	28.12.2015 16:32:38	INFO	ADDON ExtractArchive: Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar | Extracting finished
583	28.12.2015 16:32:38	DEBUG	EXTRACTOR ExtractArchive: UnRar | unrar vb -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -p- -v /share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar
584	28.12.2015 16:32:38	ERROR	ADDON ExtractArchive: Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar | Archive error | Cannot open file
585	28.12.2015 16:32:38	DEBUG	All downloads finished
586	28.12.2015 16:32:38	ERROR	ADDON ExtractArchive: Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar | Extract failed
587	28.12.2015 16:32:38	DEBUG	ADDON ExtractArchive: Targets for SevenZip: [('/share/MD0_DATA/Download/pyload/Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar', 216, '/share/MD0_DATA/Download/pyload/')]
588	28.12.2015 16:32:38	DEBUG	ADDON ExtractArchive: Homeland.S05E09.The.Litvinov.Ruse.ITA.ENG.1080p.DLMux-EGX.part05.rar | File not found 

Just to let you know, if I open the archive with winrar (latest version) from my computer, it will extract the file without issue

**Comment by redeemer666** [comment]
Found the file for issue number 1 and renamed. As soon as I solve the new issue happened today will check if extractarchive works again

**Comment by redeemer666** [comment]
Just updated with the latest version (manually, of course). Even renaming the file doesn't solve the issue. Everytime I restart pyload all ExtractArchive settings came back to default state

**Comment by Velociraptor85** [comment]
@redeemer666 does this issue still exist? or can we close the ticket?

**Comment by GammaC0de** [comment]
Fixed long ago.
