### ISSUE TITLE
Something very wrong happened after the last update.

### ISSUE THREAD

**Issue by redeemer666** [pyload/pyload#2226]
Tonight, at 00:42 CET, pyload updated some plugins. After the reboot, here's what happen:
29.12.2015 09:18:18 INFO      Avvio pyLoad 0.4.9
29.12.2015 09:18:18 INFO      Uso la cartella home: /share/MD0_DATA/.qpkg/Optware/share/pyload_config
29.12.2015 09:18:25 ERROR     Errore durante l'importazione MergeFiles: invalid syntax (misc.py, line 806)
29.12.2015 09:18:25 ERROR     Errore durante l'importazione DeleteFinished: invalid syntax (misc.py, line 806)
29.12.2015 09:18:25 ERROR     Errore durante l'importazione EventMapper: invalid syntax (misc.py, line 806)
29.12.2015 09:18:25 ERROR     Errore durante l'importazione BypassCaptcha: invalid syntax (misc.py, line 806)
29.12.2015 09:18:25 ERROR     Errore durante l'importazione ExternalScripts: invalid syntax (misc.py, line 806)
29.12.2015 09:18:26 ERROR     Errore durante l'importazione Checksum: invalid syntax (misc.py, line 806)
29.12.2015 09:18:26 ERROR     Errore durante l'importazione ExtractArchive: invalid syntax (misc.py, line 806)
29.12.2015 09:18:26 ERROR     Errore durante l'importazione UnSkipOnFail: invalid syntax (misc.py, line 806)
29.12.2015 09:18:26 ERROR     Errore durante l'importazione UpdateManager: invalid syntax (misc.py, line 806)
29.12.2015 09:18:26 ERROR     Errore durante l'importazione ClickNLoad: invalid syntax (misc.py, line 806)
29.12.2015 09:18:26 ERROR     Errore durante l'importazione UserAgentSwitcher: invalid syntax (misc.py, line 806)
29.12.2015 09:18:26 ERROR     Errore durante l'importazione SkipRev: invalid syntax (misc.py, line 806)
29.12.2015 09:18:26 INFO      Plugins attivati:
29.12.2015 09:18:26 INFO      Plugins disattivati: AndroidPhoneNotify, AntiStandby, AntiVirus, Captcha9Kw, CaptchaBrotherhood, DeathByCaptcha, DownloadScheduler, ExpertDecoders, HotFolder, IRC, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP, XMPPInterface
29.12.2015 09:18:26 INFO      Tempo di download: True
29.12.2015 09:18:26 INFO      Avvio ThriftBackend: 0.0.0.0:7227
29.12.2015 09:18:28 INFO      Free space: 3.07 TiB
29.12.2015 09:18:28 INFO      Starting builtin webserver: 192.168.1.2:9090
29.12.2015 09:18:28 INFO      Activating Accounts...
29.12.2015 09:18:28 ERROR     Error importing EasybytezCom: invalid syntax (misc.py, line 806)
Traceback (most recent call last):
  File "/opt/bin/pyLoadCore", line 667, in <module>
    main()
  File "/opt/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/opt/bin/pyLoadCore", line 433, in start
    self.accountManager.getAccountInfos()
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable
29.12.2015 09:18:55 ERROR     Error importing EasybytezCom: invalid syntax (misc.py, line 806)
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/web/pyload_app.py", line 256, in config
    accs = PYLOAD.getAccounts(False)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/Api.py", line 875, in getAccounts
    accs = self.core.accountManager.getAccountInfos(False, refresh)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable
An error occured while processing the request.
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/web/pyload_app.py", line 256, in config
    accs = PYLOAD.getAccounts(False)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/Api.py", line 875, in getAccounts
    accs = self.core.accountManager.getAccountInfos(False, refresh)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

If I try to access the Configuration Page, here what it says
HTTP Response 500

Traceback (most recent call last):
File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/utils.py", line 165, in new
return func(*args)
File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/share/MD0_DATA/.qpkg/Optware/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

Can you help me?

**Comment by redeemer666** [comment]
Here the DEBUG log:
29.12.2015 10:01:05	INFO	Avvio pyLoad 0.4.9
438	29.12.2015 10:01:05	INFO	Uso la cartella home: /share/MD0_DATA/.qpkg/Optware/share/pyload_config
439	29.12.2015 10:01:05	DEBUG	Deleting old pidfile pyload.pid
440	29.12.2015 10:01:05	DEBUG	Remote activated: True
441	29.12.2015 10:01:13	DEBUG	created index of plugins
442	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.hooks.MergeFiles -> userplugins.hooks.MergeFiles
443	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
444	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
445	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
446	29.12.2015 10:01:13	ERROR	Errore durante l'importazione MergeFiles: invalid syntax (misc.py, line 806)
447	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.hooks.DeleteFinished -> userplugins.hooks.DeleteFinished
448	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
449	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
450	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
451	29.12.2015 10:01:13	ERROR	Errore durante l'importazione DeleteFinished: invalid syntax (misc.py, line 806)
452	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.hooks.EventMapper -> userplugins.hooks.EventMapper
453	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
454	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
455	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
456	29.12.2015 10:01:13	ERROR	Errore durante l'importazione EventMapper: invalid syntax (misc.py, line 806)
457	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.hooks.BypassCaptcha -> userplugins.hooks.BypassCaptcha
458	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
459	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
460	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
461	29.12.2015 10:01:13	ERROR	Errore durante l'importazione BypassCaptcha: invalid syntax (misc.py, line 806)
462	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
463	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
464	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
465	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
466	29.12.2015 10:01:13	ERROR	Errore durante l'importazione ExternalScripts: invalid syntax (misc.py, line 806)
467	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.hooks.Checksum -> userplugins.hooks.Checksum
468	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
469	29.12.2015 10:01:13	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
470	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
471	29.12.2015 10:01:14	ERROR	Errore durante l'importazione Checksum: invalid syntax (misc.py, line 806)
472	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
473	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
474	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
475	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
476	29.12.2015 10:01:14	ERROR	Errore durante l'importazione ExtractArchive: invalid syntax (misc.py, line 806)
477	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
478	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
479	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
480	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
481	29.12.2015 10:01:14	ERROR	Errore durante l'importazione UnSkipOnFail: invalid syntax (misc.py, line 806)
482	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
483	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
484	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
485	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
486	29.12.2015 10:01:14	ERROR	Errore durante l'importazione UpdateManager: invalid syntax (misc.py, line 806) 
29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
488	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
489	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
490	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
491	29.12.2015 10:01:14	ERROR	Errore durante l'importazione ClickNLoad: invalid syntax (misc.py, line 806)
492	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.hooks.UserAgentSwitcher -> userplugins.hooks.UserAgentSwitcher
493	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
494	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
495	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
496	29.12.2015 10:01:14	ERROR	Errore durante l'importazione UserAgentSwitcher: invalid syntax (misc.py, line 806)
497	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.hooks.SkipRev -> userplugins.hooks.SkipRev
498	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
499	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
500	29.12.2015 10:01:14	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
501	29.12.2015 10:01:14	ERROR	Errore durante l'importazione SkipRev: invalid syntax (misc.py, line 806)
502	29.12.2015 10:01:14	INFO	Plugins attivati:
503	29.12.2015 10:01:14	INFO	Plugins disattivati: AndroidPhoneNotify, AntiStandby, AntiVirus, Captcha9Kw, CaptchaBrotherhood, DeathByCaptcha, DownloadScheduler, ExpertDecoders, HotFolder, IRC, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP, XMPPInterface
504	29.12.2015 10:01:14	INFO	Tempo di download: True
505	29.12.2015 10:01:14	INFO	Avvio ThriftBackend: 0.0.0.0:7227
506	29.12.2015 10:01:14	INFO	Spazio libero: 3.07 TiB
507	29.12.2015 10:01:15	INFO	Attivo gli Account...
508	29.12.2015 10:01:17	DEBUG	Redirected import module.plugins.accounts.EasybytezCom -> userplugins.accounts.EasybytezCom
509	29.12.2015 10:01:17	DEBUG	Redirected import module.plugins.internal.XFSAccount -> userplugins.internal.XFSAccount
510	29.12.2015 10:01:17	INFO	Starting builtin webserver: 192.168.1.2:9090
511	29.12.2015 10:01:17	DEBUG	Redirected import module.plugins.internal.MultiAccount -> userplugins.internal.MultiAccount
512	29.12.2015 10:01:17	DEBUG	Redirected import module.plugins.internal.Account -> userplugins.internal.Account
513	29.12.2015 10:01:17	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
514	29.12.2015 10:01:17	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
515	29.12.2015 10:01:17	ERROR	Error importing EasybytezCom: invalid syntax (misc.py, line 806)
516	29.12.2015 10:01:50	DEBUG	Redirected import module.plugins.accounts.EasybytezCom -> userplugins.accounts.EasybytezCom
517	29.12.2015 10:01:50	DEBUG	Redirected import module.plugins.internal.XFSAccount -> userplugins.internal.XFSAccount
518	29.12.2015 10:01:50	DEBUG	Redirected import module.plugins.internal.MultiAccount -> userplugins.internal.MultiAccount
519	29.12.2015 10:01:50	DEBUG	Redirected import module.plugins.internal.Account -> userplugins.internal.Account
520	29.12.2015 10:01:50	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
521	29.12.2015 10:01:50	DEBUG	Redirected import module.plugins.internal.misc -> userplugins.internal.misc
522	29.12.2015 10:01:50	ERROR	Error importing EasybytezCom: invalid syntax (misc.py, line 806)

**Comment by GammaC0de** [comment]
Try refreshing your `userplugins` directory (see http://forum.pyload.org/viewtopic.php?f=12&t=4335)

**Comment by redeemer666** [comment]
I don't have a userplugins directory... Searched in all pyload's directories and can't find it...

**Comment by GammaC0de** [comment]
What OS?

**Comment by redeemer666** [comment]
ipkg on QNAP

**Comment by redeemer666** [comment]
Found the folder, followed the instructions you posted before. Now the updatemanager addon can't connect to server to download the updates. At least I have access to the configuration page again

**Comment by redeemer666** [comment]
can you tell me the address of the update server? Want to check if it is a server side issue or a personal one. Updatemanager still can't download updates...

**Comment by GammaC0de** [comment]
replace the <pyload directory>module/plugins/hooks/UpdateManager.py file with this one: https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py 
then retry

**Comment by redeemer666** [comment]
Nope
29.12.2015 12:09:09	WARNING	UpdateManager: Not able to connect server for updates

**Comment by GammaC0de** [comment]
Unfortunately, the server is down ATM http://updatemanager.pyload.org/?v=0.4.9

**Comment by redeemer666** [comment]
Will try later. Thank you for your help!!!

**Comment by GammaC0de** [comment]
:+1: 
I'm going to close this.
If this issue remains, please post again.

**Comment by vuolter** [comment]
I hate the updatemanager! u.u
