### ISSUE TITLE
UpdateManager not working

### ISSUE THREAD

**Issue by Velociraptor85** [pyload/pyload#2227]
UpdatedManager is not working cant connect to server even with deleting the userplugins folder.

**Comment by GammaC0de** [comment]
Server is currently down  
http://updatemanager.pyload.org/?v=0.4.9

**Comment by Velociraptor85** [comment]
thanks

**Comment by vuolter** [comment]
Ticket open here: https://github.com/pyload/updatemanager/issues/34
