### ISSUE TITLE
ZippyshareCom-Plugin version 0.86 not working

### ISSUE THREAD

**Issue by Bandicoot2205** [pyload/pyload#2229]
The new ZippyshareCom plugin 0.86 is not working

log says: global name 'set_cookies' is not defined

**Comment by GammaC0de** [comment]
Please post debug log

**Comment by Bandicoot2205** [comment]
11    29.12.2015 15:23:00	INFO	Download starts: Kanone11080DETAiLS.part07.rar
12	29.12.2015 15:23:01	WARNING	HOSTER ZippyshareCom[1005]: Plugin may be unstable
13	29.12.2015 15:23:01	INFO	HOSTER ZippyshareCom[1005]: Grabbing link info...
14	29.12.2015 15:23:01	INFO	HOSTER ZippyshareCom[1005]: Link name: Kanone11080DETAiLS.part07.rar
15	29.12.2015 15:23:01	INFO	HOSTER ZippyshareCom[1005]: Link size: 150.00 MiB (157286400 bytes)
16	29.12.2015 15:23:01	INFO	HOSTER ZippyshareCom[1005]: Link status: online
17	29.12.2015 15:23:01	INFO	HOSTER ZippyshareCom[1005]: Processing url: http://www58.zippyshare.com/v/1O3btQGL/file.html
18	29.12.2015 15:23:01	INFO	HOSTER ZippyshareCom[1005]: Looking for direct download link...
19	29.12.2015 15:23:02	INFO	HOSTER ZippyshareCom[1005]: Direct download link not found
20	29.12.2015 15:23:02	WARNING	Download failed: Kanone11080DETAiLS.part07.rar | global name 'set_cookies' is not defined
21	29.12.2015 15:23:02	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Kanone11080DETAiLS.part07.rar (pid:46)
22	29.12.2015 15:23:02	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
That is not debug log,
Please enable debug mode and post DEBUG log

**Comment by Bandicoot2205** [comment]
Sorry, but I did not know what you mean. Now there is the same problem with another error message: 'ReCaptcha' object has no attribute 'plugin'

[debug_Report.txt](https://github.com/pyload/pyload/files/74073/debug_Report.txt)

**Comment by vuolter** [comment]
Your plugins are out of date. u.u
