### ISSUE TITLE
JDownloader DLCs are not imported

### ISSUE THREAD

**Issue by godfuture** [pyload/pyload#2232]
Hi all,

I did not manage it to use click n load with ff and pyload. The effort is quite high in my opinion. But I tried to use Jdownloader for click n load, to later on export the fetched links as DLC and import the DLC to Pyload.

*Problem*
The DLC created by JD is not imported no matter what I do. The error message is:
> 4553	29.12.2015 20:19:02	ERROR	Decrypting failed: tmp_Test1.dlc | global name 'pyfile' is not defined

**Comment by ckaeslin** [comment]
I had the same problem.
Pull request is already merged: #2228

**Comment by GammaC0de** [comment]
you should update manually since the update server is currently offline
