### ISSUE TITLE
After last plugin update downloads won't start (EasyBytez.com at least), again

### ISSUE THREAD

**Issue by darkpella** [pyload/pyload#2237]
Hi,
Almost same as #2222 

Yesterday pyLoad requested me to restart due to a plugin update.

After I restarted pyLoad, download was set to on (was off on #2222) but no download starts.

Also, no download-related activity is logged.
I also tried rebooting and manually restarting pyLoad to see whether it would work back normally, to no avail.
pyLoad runs on a syno DS 115 under DebianChRoot package.

I notice that "__version__" has different values in /volume1/@appstore/debian-chroot/var/chroottarget/usr/share/pyload/module/plugins/internal/Account.py (__version__ = "0.17") and /volume1/home/pyload/.pyload/userplugins/internal/Account.py (__version__ = "0.68")

bye

darkpella

excerpt from  /volume1/@appstore/debian-chroot/var/chroottarget/usr/share/pyload/module/plugins/internal/Account.py:
>class Account(Plugin):
>    __name__    = "Account"
>    __type__    = "account"
>    __version__ = "0.17"
>    __status__  = "testing"
>
>    __description__ = """Base account plugin"""
>    __license__     = "GPLv3"

excerpt from /volume1/home/pyload/.pyload/userplugins/internal/Account.py:
>class Account(Plugin):
>    __name__    = "Account"
>    __type__    = "account"
>    __version__ = "0.68"
>    __status__  = "stable"
>
>    __description__ = """Base account plugin"""
>    __license__     = "GPLv3"

pyLoad  log upon restart:
>287	30.12.2015 07:49:00	INFO	restarting pyLoad
>288	30.12.2015 07:49:00	INFO	shutting down...
>289	30.12.2015 07:49:02	INFO	Avvio pyLoad 0.4.9
>290	30.12.2015 07:49:02	INFO	Uso la cartella home: /volume1/home/pyload/.pyload
>291	30.12.2015 07:49:05	WARNING	Impossibile attivare UpdateManager
>292	30.12.2015 07:49:05	WARNING	Impossibile attivare ExternalScripts
>293	30.12.2015 07:49:05	ERROR	Errore durante l'importazione ExtractArchive: cannot import name replace_patterns
>294	30.12.2015 07:49:05	INFO	Plugins attivati: ClickNLoad, DownloadScheduler, LinkdecrypterComHook, UnSkipOnFail, UserAgentSwitcher
295	30.12.2015 07:49:05	INFO	Plugins disattivati: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, LogMarker, MergeFiles, MultiHome, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPPInterface
>296	30.12.2015 07:49:05	INFO	Tempo di download: True
>297	30.12.2015 07:49:05	INFO	Avvio ThriftBackend: 0.0.0.0:7227
>298	30.12.2015 07:49:06	INFO	Starting builtin webserver: 0.0.0.0:8000
>299	30.12.2015 07:49:06	INFO	Free space: 2.34 TiB
>300	30.12.2015 07:49:06	INFO	Activating Accounts...
>301	30.12.2015 07:49:06	INFO	ACCOUNT EasybytezCom: Adding user `darkpella`...
>302	30.12.2015 07:49:06	INFO	ACCOUNT EasybytezCom: Login user `darkpella`...
>303	30.12.2015 07:49:07	INFO	ACCOUNT EasybytezCom: Checking for link errors...
>304	30.12.2015 07:49:07	INFO	ACCOUNT EasybytezCom: No errors found
>305	30.12.2015 07:49:07	INFO	ACCOUNT EasybytezCom: Grabbing account info for user `darkpella`...
>306	30.12.2015 07:49:08	INFO	Activating Plugins...
>307	30.12.2015 07:49:08	ERROR	Error executing hooks: 'ClickNLoad' object has no attribute 'get_config'
>308	30.12.2015 07:49:08	INFO	pyLoad is up and running

**Comment by darkpella** [comment]
Just noticed @vuolter marked this as as fake issue, guess this means I screwed up something, some advice wuould help.

bye 

darkpella

**Comment by darkpella** [comment]
I tried replacing /volume1/home/pyload/.pyload/userplugins/internal/Account.py through  https://github.com/pyload/pyload/raw/stable/module/plugins/internal/Account.py as @GammaC0de suggested for  #2222.
"__version__" now reads 0.70.
Also, I noticed that, prior to replacing /volume1/home/pyload/.pyload/userplugins/internal/Account.py  was owned by root|root rather than by pyload|1026 (pyload is the name of the user I run pyLoad under, which belongs to group 1026) as all other .py files within the same directory. most likely due to my previous replacing as directed by @GammaC0de 

After replacing Account.py I had ownership changed to pyload|1026 and permissions set to 755 

After restarting pyload some download-related activity is logged, but I get the following error: 'UserAgentSwitcher' object has no attribute 'get_config'.
Also, some plugins can't be started (see transcript below).
Guess I have not fixed all I've screwed up..
Please help me ......

>385	30.12.2015 13:31:54	INFO	restarting pyLoad
>386	30.12.2015 13:31:54	INFO	shutting down...
>387	30.12.2015 13:31:56	INFO	Starting pyLoad 0.4.9
>388	30.12.2015 13:31:56	INFO	Using home directory: /volume1/home/pyload/.pyload
>389	30.12.2015 13:31:58	WARNING	Failed activating UpdateManager
>390	30.12.2015 13:31:58	WARNING	Failed activating ExternalScripts
>391	30.12.2015 13:31:58	ERROR	Error importing ExtractArchive: cannot import name replace_patterns
>392	30.12.2015 13:31:58	INFO	Activated plugins: ClickNLoad, DownloadScheduler, LinkdecrypterComHook, UnSkipOnFail, UserAgentSwitcher
>393	30.12.2015 13:31:58	INFO	Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, LogMarker, MergeFiles, MultiHome, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPPInterface
>394	30.12.2015 13:31:58	INFO	Downloadtime: True
>395	30.12.2015 13:31:58	INFO	Starting ThriftBackend: 0.0.0.0:7227
>396	30.12.2015 13:31:59	INFO	Starting builtin webserver: 0.0.0.0:8000
>397	30.12.2015 13:31:59	INFO	Free space: 2.34 TiB
>398	30.12.2015 13:31:59	INFO	Activating Accounts...
>399	30.12.2015 13:31:59	INFO	ACCOUNT EasybytezCom: Adding user `darkpella`...
>400	30.12.2015 13:31:59	INFO	ACCOUNT EasybytezCom: Login user `darkpella`...
>401	30.12.2015 13:32:01	INFO	ACCOUNT EasybytezCom: Checking for link errors...
>402	30.12.2015 13:32:01	INFO	ACCOUNT EasybytezCom: No errors found
>403	30.12.2015 13:32:01	INFO	ACCOUNT EasybytezCom: Grabbing account info for user `darkpella`...
>404	30.12.2015 13:32:02	INFO	Activating Plugins...
>405	30.12.2015 13:32:02	ERROR	Error executing hooks: 'ClickNLoad' object has no attribute 'get_config'
>406	30.12.2015 13:32:02	INFO	pyLoad is up and running
>407	30.12.2015 13:32:04	INFO	Download starts: XXX.part1.rar
>408	30.12.2015 13:32:04	WARNING	Download failed: XXX.part1.rar | 'UserAgentSwitcher' object has no attribute 'get_config'
>409	30.12.2015 13:32:04	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: XXX.part1.rar (pid:190)
>410	30.12.2015 13:32:04	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
@darkpella Your `UserAgentSwitcher` is still not up to date.
Unfortunately the update server is down at the moment
