### ISSUE TITLE
Solve [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Cseb87** [pyload/pyload#2239]
Hello
Here is my problem
After updating today (by downloading the zip on github)
I have a problem with download folder

[Errno 2] No such file or directory: '/volume1/.@plugins/AppCentral/pyload/config/volume1/.@plugins/AppCentral/pyload/config/volume1/Mes Documents / Download / stable.zip.chunk0'

/volume1/.@plugins/AppCentral/pyload/config/
and the config folder

/volume1/Mes Documents/Download/
and the download folder

Or both address is added

While the address must be:
/volume1/Mes Documents/Download/stable.zip.chunk0

I try to fix by deleting lines 468 to 490 to test the misc.py (module / plugins / internal)
I can download but not in the correct folder
But the knowledges stops

This application may be an improvement in the safepath (value) in the misc.py?

I use pyLoad nas server on AS6202T ASUSTOR
I can test things if needs
Thank you

sorry for my english I am french

**Comment by Cseb87** [comment]
I found a solution but it is not valid for everyone I think
here's what I did

def safepath(value):
    """
    Remove invalid characters and truncate the path if needed
    """
    drive, filename = os.path.splitdrive(value)
    path = os.path.abspath(filename)
    return path

**Comment by youlJunior** [comment]
I confirm that just commenting the line below in misc.py works :
```python
filename = os.path.join(*map(safename, filename.split(os.sep)))
```

**Comment by youlJunior** [comment]
It appears that the line : 
```
filename = os.path.join(*map(safename, filename.split(os.sep)))
```
splits and join the path of the file, but it loose the leading os separator.

So on next line : 
```
path = os.path.abspath(drive + filename)
```
the filename is considered as relative because it doesn't start with an os separator, so the abspath function add the current directory to the file path (and the current dir is the config dir...)

I just modified the line to : 
```
filename = os.path.join(os.sep, *map(safename, filename.split(os.sep)))
```
and it works !

**Comment by Cseb87** [comment]
thank you for your participation @youlJunior 
;-)

**Comment by youlJunior** [comment]
You're welcome @Cseb87, I'm a python enthusiast fan :-)

**Comment by vuolter** [comment]
@youlJunior Thanks!!! :D
