### ISSUE TITLE
Error Messages "cannot import name create_getInfo" (No Download possible...)

### ISSUE THREAD

**Issue by mcflym** [pyload/pyload#2240]
Hi, since a few days (i think after an update) i got the following error messages after restarting pyload:

928	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated all_dls_processed scripts: None
927	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated all_dls_finished scripts: None
926	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated pyload_start scripts: None
925	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated package_deleted scripts: None
924	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated pyload_stop scripts: None
923	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated all_downloads_processed scripts: None
922	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated before_reconnect scripts: None
921	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated archive_extract_failed scripts: None
920	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated all_archives_extracted scripts: None
919	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated archive_extracted scripts: None
918	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated package_extract_failed scripts: None
917	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated download_finished scripts: None
916	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated all_downloads_finished scripts: None
915	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated unrar_finished scripts: None
914	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated package_extracted scripts: None
913	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated download_preparing scripts: None
912	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated package_finished scripts: None
911	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated after_reconnect scripts: None
910	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated all_archives_processed scripts: None
909	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated pyload_restart scripts: None
908	30.12.2015 13:37:21	INFO	ADDON ExternalScripts: Activated download_failed scripts: None
907	30.12.2015 13:37:04	WARNING	ADDON UpdateManager: Unable to connect to the server to retrieve updates
906	30.12.2015 13:36:59	CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
905	30.12.2015 13:36:59	ERROR	Error importing ShareonlineBiz: cannot import name create_getInfo
904	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated all_dls_processed scripts: None
903	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated all_dls_finished scripts: None
902	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated pyload_start scripts: None
901	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated package_deleted scripts: None
900	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated pyload_stop scripts: None
899	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated all_downloads_processed scripts: None
898	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated before_reconnect scripts: None
897	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated archive_extract_failed scripts: None
896	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated all_archives_extracted scripts: None
895	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated archive_extracted scripts: None
894	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated package_extract_failed scripts: None
893	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated download_finished scripts: None
892	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated all_downloads_finished scripts: None
891	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated unrar_finished scripts: None
890	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated package_extracted scripts: None
889	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated download_preparing scripts: None
888	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated package_finished scripts: None
887	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated after_reconnect scripts: None
886	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated all_archives_processed scripts: None
885	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated pyload_restart scripts: None
884	30.12.2015 13:36:21	INFO	ADDON ExternalScripts: Activated download_failed scripts: None
883	30.12.2015 13:36:19	INFO	pyLoad is up and running
882	30.12.2015 13:36:19	INFO	ADDON XFileSharing: Auto-discover new crypters
881	30.12.2015 13:36:19	ERROR	Error importing TusfilesNetFolder: cannot import name create_getInfo
880	30.12.2015 13:36:19	ERROR	Error importing BitshareComFolder: cannot import name create_getInfo
879	30.12.2015 13:36:19	ERROR	Error importing GooGl: cannot import name create_getInfo
878	30.12.2015 13:36:19	ERROR	Error importing ImgurComAlbum: cannot import name create_getInfo
877	30.12.2015 13:36:19	ERROR	Error importing TinyurlCom: cannot import name create_getInfo
876	30.12.2015 13:36:19	ERROR	Error importing CrockoComFolder: cannot import name create_getInfo
875	30.12.2015 13:36:19	ERROR	Error importing Go4UpCom: cannot import name create_getInfo
874	30.12.2015 13:36:19	ERROR	Error importing FreakhareComFolder: cannot import name create_getInfo
873	30.12.2015 13:36:19	ERROR	Error importing NitroflareComFolder: cannot import name create_getInfo
872	30.12.2015 13:36:19	ERROR	Error importing FilefactoryComFolder: cannot import name create_getInfo
871	30.12.2015 13:36:19	ERROR	Error importing FurLy: cannot import name create_getInfo
870	30.12.2015 13:36:19	ERROR	Error importing TurbobitNetFolder: cannot import name create_getInfo
869	30.12.2015 13:36:19	ERROR	Error importing DevhostStFolder: cannot import name create_getInfo
868	30.12.2015 13:36:19	ERROR	Error importing Dereferer: cannot import name create_getInfo
867	30.12.2015 13:36:19	ERROR	Error importing LinkdecrypterCom: cannot import name create_getInfo
866	30.12.2015 13:36:19	ERROR	Error importing DlProtectCom: cannot import name create_getInfo
865	30.12.2015 13:36:19	ERROR	Error importing FilecloudIoFolder: cannot import name create_getInfo
864	30.12.2015 13:36:19	ERROR	Error importing DataHuFolder: cannot import name create_getInfo
863	30.12.2015 13:36:19	ERROR	Error importing EasybytezComFolder: cannot import name create_getInfo
862	30.12.2015 13:36:19	ERROR	Error importing XFileSharingFolder: cannot import name create_getInfo
861	30.12.2015 13:36:19	ERROR	Error importing UploadableChFolder: cannot import name create_getInfo
860	30.12.2015 13:36:19	ERROR	Error importing PastebinCom: cannot import name create_getInfo
859	30.12.2015 13:36:19	ERROR	Error importing UploadedToFolder: cannot import name create_getInfo
858	30.12.2015 13:36:19	ERROR	Error importing MegaRapidCzFolder: cannot import name create_getInfo
857	30.12.2015 13:36:19	ERROR	Error importing FiletramCom: cannot import name create_getInfo
856	30.12.2015 13:36:19	ERROR	Error importing NosvideoCom: cannot import name create_getInfo
855	30.12.2015 13:36:19	ERROR	Error importing HflixIn: cannot import name create_getInfo
854	30.12.2015 13:36:19	ERROR	Error importing FilestubeCom: cannot import name create_getInfo
853	30.12.2015 13:36:19	ERROR	Error importing FreetexthostCom: cannot import name create_getInfo
852	30.12.2015 13:36:19	ERROR	Error importing CloudzillaToFolder: cannot import name create_getInfo
851	30.12.2015 13:36:19	ERROR	Error importing FshareVnFolder: cannot import name create_getInfo
850	30.12.2015 13:36:19	ERROR	Error importing FilerNetFolder: cannot import name create_getInfo
849	30.12.2015 13:36:19	ERROR	Error importing TnyCz: cannot import name create_getInfo
848	30.12.2015 13:36:19	ERROR	Error importing DepositfilesComFolder: cannot import name create_getInfo
847	30.12.2015 13:36:19	ERROR	Error importing MultiUpOrg: cannot import name create_getInfo
846	30.12.2015 13:36:19	ERROR	Error importing ImgurCom: cannot import name create_getInfo
845	30.12.2015 13:36:19	ERROR	Error importing GoogledriveComFolder: cannot import name create_getInfo
844	30.12.2015 13:36:19	ERROR	Error importing LinkSaveIn: cannot import name create_getInfo
843	30.12.2015 13:36:19	ERROR	Error importing TNTVillageScambioeticoOrg: cannot import name create_getInfo
842	30.12.2015 13:36:19	INFO	ADDON XFileSharing: Auto-discover new hosters
841	30.12.2015 13:36:19	ERROR	Error importing ExtabitCom: cannot import name create_getInfo
840	30.12.2015 13:36:19	ERROR	Error importing GoogledriveCom: cannot import name create_getInfo
839	30.12.2015 13:36:19	ERROR	Error importing DlFreeFr: cannot import name create_getInfo
838	30.12.2015 13:36:19	ERROR	Error importing DepositfilesCom: cannot import name create_getInfo
837	30.12.2015 13:36:19	ERROR	Error importing FilejungleCom: cannot import name create_getInfo
836	30.12.2015 13:36:19	ERROR	Error importing WrzucTo: cannot import name create_getInfo
835	30.12.2015 13:36:19	ERROR	Error importing SimplyPremiumCom: cannot import name create_getInfo
834	30.12.2015 13:36:19	ERROR	Error importing GamefrontCom: cannot import name create_getInfo
833	30.12.2015 13:36:19	ERROR	Error importing UploadStationCom: cannot import name create_getInfo
832	30.12.2015 13:36:19	ERROR	Error importing MegaFilesSe: cannot import name create_getInfo
831	30.12.2015 13:36:19	ERROR	Error importing FileSharkPl: cannot import name create_getInfo
830	30.12.2015 13:36:19	ERROR	Error importing BasketbuildCom: cannot import name create_getInfo
829	30.12.2015 13:36:19	ERROR	Error importing DataHu: cannot import name create_getInfo

Downloading isn't possible with share-online and uploaded... And I think with the rest of the providers as well.

**Comment by GammaC0de** [comment]
Your plugins are not up to date.
Unfortunately the update server is down at the moment
You can manually update all the plugins

**Comment by mcflym** [comment]
Updated pyload/userplugins/hoster/ShareonlineBiz.py to 0.65 manually (from 0.64)

Same Issue...

**Comment by GammaC0de** [comment]
you should update ALL of the plugins:
* Get the stable package from https://github.com/pyload/pyload/archive/stable.zip
* Extract \<stable.zip\>/module/plugins to your userplugins directory.

**Comment by mcflym** [comment]
I think I am waiting for the fix of the Update-Server... This is the main issue, right?

**Comment by GammaC0de** [comment]
Yes, but I'm not sure that your `Updatemanager` plugin is functional at the moment also..

**Comment by mcflym** [comment]
I am on 1.05, the latest version of Updatemanager.

**Comment by mcflym** [comment]
Well, I updated all plugins manually!

No Errors after restarting pyload, except the error about the Update-Server.

But there is still the problem that I can't download:

"WARNING	Download failed: XXXXX_FILENAME | correct() takes at least 2 arguments (1 given)"

**Comment by GammaC0de** [comment]
:+1: 
Please open new issue with log included.

**Comment by vuolter** [comment]
@mcflym Sample url please. ;)

**Comment by mcflym** [comment]
http://www.share-online.biz/dl/2V6VCFENIBX
