### ISSUE TITLE
Update server is down, everyone should manually update his userplugins before reporting an issue

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2241]
As you might know, update server is down at the moment.
So before reporting any issue, please make sure your `userplugins` are up to date:
* Get the stable package from https://github.com/pyload/pyload/archive/stable.zip
* Extract all the subfolders in `<stable.zip>/module/plugins` to your `userplugins` directory.

**Please note that this will only update your `pyLoad` to the current state.
It will not fix the `Updatemanager` problem!**

**Comment by twoDarkMessiah** [comment]
Confirmed, 
thx you helped me a lot, didn't noticed the problem with the update server before.

**Comment by LyonL-fr** [comment]
Thanks a lot

**Comment by GammaC0de** [comment]
Update server seems to be working now...


If this does not work for you please report here..
