### ISSUE TITLE
WARNING Download failed: XXXXX_FILENAME | correct() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by mcflym** [pyload/pyload#2242]
Hi there again :-)

Now I got the following issue when I am downloading from share-online:

WARNING Download failed: XXXXX_FILENAME | correct() takes at least 2 arguments (1 given)

File is up and download is working manually without issues.

Thanks for help!

**Comment by GammaC0de** [comment]
Hi,
Debug log and URL please

**Comment by mcflym** [comment]
URL: http://www.share-online.biz/dl/2V6VCFENIBX

380	30.12.2015 15:54:42	DEBUG	All downloads processed
379	30.12.2015 15:54:42	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
378	30.12.2015 15:54:42	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
377	30.12.2015 15:54:42	INFO	ADDON UnSkipOnFail: No duplicates found
376	30.12.2015 15:54:42	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 5364204796430125872349317.part01.rar (pid:225)
375	30.12.2015 15:54:42	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
374	30.12.2015 15:54:42	INFO	Debug Report written to debug_ShareonlineBiz_30-12-2015_15-54-42.zip
373	30.12.2015 15:54:42	WARNING	Download failed: 5364204796430125872349317.part01.rar | correct() takes at least 2 arguments (1 given)
372	30.12.2015 15:54:42	DEBUG	HOSTER ShareonlineBiz[11356]: DOWNLOAD URL http://dlw126-1.share-online.biz/dl?u=C64429EA92277FE49244288AC51758ED94372EBDE1172D92954152FD943332EDFC4629BCA94203EF977761ED866848AC&q=v4 | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
371	30.12.2015 15:54:42	INFO	HOSTER ShareonlineBiz[11356]: Downloading file...
370	?	?	MD5: 6f5fbb59cc6ddb0c5faba43f1824b6be
369	?	?	SIZE: 1073741824
368	?	?	NAME: 5364204796430125872349317.part01.rar
367	?	?	ID: 2V6VCFENIBX
366	?	?	URL: http://dlw126-1.share-online.biz/dl?u=C64429EA92277FE49244288AC51758ED94372EBDE1172D92954152FD943332EDFC4629BCA94203EF977761ED866848AC&q=v4
365	30.12.2015 15:54:42	DEBUG	HOSTER ShareonlineBiz[11356]: STATUS: online
364	30.12.2015 15:54:42	DEBUG	HOSTER ShareonlineBiz[11356]: LOAD URL https://api.share-online.biz/account.php | redirect=True | cookies=True | get={'username': 'XXXXXX', 'lid': '2V6VCFENIBX', 'password': '**********', 'act': 'download'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
363	30.12.2015 15:54:42	DEBUG	ACCOUNT ShareonlineBiz: Account info for user `XXXXXX`: {'login': {'timestamp': 1451487246.329745, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': XXXXXX, 'maxtraffic': XXXXXX, 'validuntil': XXXXXX, 'login': 'XXXXXX', 'type': 'ShareonlineBiz', 'options': {'limitdl': ['0']}}}
362	?	?	traffic_7d=0;0.000
361	?	?	traffic_1d=9437184;0.009
360	?	?	a=98442DC3EA4945EC905C28EFF8486DCE93170589D25101EB81792BF9FC2237C893412993D24655B69D4247E5C8253C83E8352E9DC03C6ED6955737F0D22424AB
359	?	?	money=8.00
358	?	?	points=8000
357	?	?	expire_date=XXXXXX
356	?	?	register_date=XXXXXX
355	?	?	group=Premium
354	?	?	email=shii-premiumbiz21@hotmail.de
353	30.12.2015 15:54:42	DEBUG	ACCOUNT ShareonlineBiz: user=XXXXXX
352	30.12.2015 15:54:42	DEBUG	ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': '42420231543', 'password': '**********'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
351	30.12.2015 15:54:42	INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `XXXXXX`...
350	30.12.2015 15:54:42	INFO	HOSTER ShareonlineBiz[11356]: Processing as premium download...
349	30.12.2015 15:54:42	INFO	HOSTER ShareonlineBiz[11356]: Filesize: 1048576 KiB | Traffic left for user `XXXXXX`: XXXXXX KiB
348	30.12.2015 15:54:42	DEBUG	ACCOUNT ShareonlineBiz: Account info for user `XXXXXX`: {'login': {'timestamp': 1451487246.329745, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': XXXXXX, 'maxtraffic': XXXXXX, 'validuntil': XXXXXX, 'login': 'XXXXXX', 'type': 'ShareonlineBiz', 'options': {'limitdl': ['0']}}}
347	?	?	traffic_7d=0;0.000
346	?	?	traffic_1d=9437184;0.009
345	?	?	a=98442DC3EA4945EC905C28EFF8486DCE93170589D25101EB81792BF9FC2237C893412993D24655B69D4247E5C8253C83E8352E9DC03C6ED6955737F0D22424AB
344	?	?	money=8.00
343	?	?	points=8000
342	?	?	expire_date=XXXXXX
341	?	?	register_date=XXXXXX
340	?	?	group=Premium
339	?	?	email=shii-premiumbiz21@hotmail.de
338	30.12.2015 15:54:42	DEBUG	ACCOUNT ShareonlineBiz: user=XXXXXX
337	30.12.2015 15:54:41	DEBUG	ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': 'XXXXXX', 'password': '**********'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
336	30.12.2015 15:54:41	INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `XXXXXX`...
335	30.12.2015 15:54:41	DEBUG	HOSTER ShareonlineBiz[11356]: LOAD URL http://www.share-online.biz/dl/2V6VCFENIBX | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
334	30.12.2015 15:54:41	INFO	HOSTER ShareonlineBiz[11356]: Direct download link not found
333	30.12.2015 15:54:41	DEBUG	HOSTER ShareonlineBiz[11356]: LOAD URL http://www.share-online.biz/dl/2V6VCFENIBX | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
332	30.12.2015 15:54:41	DEBUG	HOSTER ShareonlineBiz[11356]: Redirect #0 to: http://www.share-online.biz/dl/2V6VCFENIBX
331	30.12.2015 15:54:41	INFO	HOSTER ShareonlineBiz[11356]: Looking for direct download link...
330	30.12.2015 15:54:41	INFO	HOSTER ShareonlineBiz[11356]: Processing url: http://www.share-online.biz/dl/2V6VCFENIBX
329	30.12.2015 15:54:41	INFO	HOSTER ShareonlineBiz[11356]: Link status: online
328	30.12.2015 15:54:41	INFO	HOSTER ShareonlineBiz[11356]: Link size: 1.00 GiB (1073741824 bytes)
327	30.12.2015 15:54:41	INFO	HOSTER ShareonlineBiz[11356]: Link name: 5364204796430125872349317.part01.rar
326	30.12.2015 15:54:41	DEBUG	HOSTER ShareonlineBiz[11356]: Previous link info: {}
325	30.12.2015 15:54:41	DEBUG	HOSTER ShareonlineBiz[11356]: Link info: {'status': 2, 'hash': {}, 'name': '5364204796430125872349317.part01.rar', 'url': u'http://www.share-online.biz/dl/2V6VCFENIBX', 'pattern': {'ID': u'2V6VCFENIBX'}, 'size': 1073741824, 'md5': '6f5fbb59cc6ddb0c5faba43f1824b6be', 'fileid': '2V6VCFENIBX'}
324	30.12.2015 15:54:41	INFO	HOSTER ShareonlineBiz[11356]: Grabbing link info...
323	30.12.2015 15:54:41	DEBUG	ACCOUNT ShareonlineBiz: Account info for user `XXXXXX`: {'login': {'timestamp': 1451487246.329745, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': XXXXXX, 'maxtraffic': XXXXXX, 'validuntil': XXXXXX, 'login': 'XXXXXX', 'type': 'ShareonlineBiz', 'options': {'limitdl': ['0']}}}
322	?	?	traffic_7d=0;0.000
321	?	?	traffic_1d=9437184;0.009
320	?	?	a=98442DC3EA4945EC905C28EFF8486DCE93170589D25101EB81792BF9FC2237C893412993D24655B69D4247E5C8253C83E8352E9DC03C6ED6955737F0D22424AB
319	?	?	money=8.00
318	?	?	points=8000
317	?	?	expire_date=XXXXXX
316	?	?	register_date=XXXXXX
315	?	?	group=Premium
314	?	?	email=shii-premiumbiz21@hotmail.de
313	30.12.2015 15:54:41	DEBUG	ACCOUNT ShareonlineBiz: user=XXXXXX
312	30.12.2015 15:54:41	DEBUG	ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': '42420231543', 'password': '**********'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
311	30.12.2015 15:54:41	INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `XXXXXX`...
310	30.12.2015 15:54:41	WARNING	HOSTER ShareonlineBiz[11356]: Plugin may be unstable
309	30.12.2015 15:54:41	DEBUG	HOSTER ShareonlineBiz[11356]: Plugin status: testing
308	30.12.2015 15:54:41	DEBUG	HOSTER ShareonlineBiz[11356]: Plugin version: 0.65
307	30.12.2015 15:54:40	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
306	30.12.2015 15:54:40	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
305	30.12.2015 15:54:40	INFO	Download starts: 5364204796430125872349317.part01.rar
304	30.12.2015 15:54:40	DEBUG	Redirected import module.plugins.internal.OCR -> userplugins.internal.OCR
303	30.12.2015 15:54:40	DEBUG	Redirected import module.plugins.captcha.ShareonlineBiz -> userplugins.captcha.ShareonlineBiz

**Comment by vuolter** [comment]
Issue not found using latest git code. Surely your plugins are out of date.

**Comment by mcflym** [comment]
I updated ALL plugins form the latest stable-package?!?

So how can it possible that these are out of date?

**Comment by vuolter** [comment]
@mcflym I'm wrong (but... I tested the code and works for me... XD)
See: https://github.com/pyload/pyload/issues/2246
