### ISSUE TITLE
EASYBYTEZ (premium): pycurl error 23: Failed writing body (0 != 1418)

### ISSUE THREAD

**Issue by darkpella** [pyload/pyload#2243]
Hi, I'm currently getting this error on each (easybytez premium) download:
>pycurl error 23: Failed writing body (0 != 1418)

I already removed and replaced all files in my userplugins folder and subfolders as specified in  #2241.

Here below a transcript form pyLoad's log.
The download referred to works fine when run through a web browser

>747	30.12.2015 16:38:42	INFO	Download starts: WTCHUC80.part22.rar
>748	30.12.2015 16:38:43	WARNING	HOSTER EasybytezCom[6139]: Plugin may be unstable
>749	30.12.2015 16:38:43	INFO	ACCOUNT EasybytezCom: Grabbing account info for user `darkpella`...
>750	30.12.2015 16:38:44	INFO	HOSTER EasybytezCom[6139]: Grabbing link info...
>751	30.12.2015 16:38:45	INFO	HOSTER EasybytezCom[6139]: Link name: WTCHUC80.part22.rar
>752	30.12.2015 16:38:45	INFO	HOSTER EasybytezCom[6139]: Link size: 512.00 MiB (536870912 bytes)
>753	30.12.2015 16:38:45	INFO	HOSTER EasybytezCom[6139]: Link status: online
>754	30.12.2015 16:38:45	INFO	HOSTER EasybytezCom[6139]: Processing url: http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar
>755	30.12.2015 16:38:45	INFO	HOSTER EasybytezCom[6139]: Looking for direct download link...
>756	30.12.2015 16:38:48	INFO	HOSTER EasybytezCom[6139]: Direct download link not found
>757	30.12.2015 16:38:54	WARNING	ADDON UpdateManager: Unable to connect to the server to retrieve updates
>758	30.12.2015 16:38:57	ERROR	pycurl error 23: Failed writing body (0 != 1418)
>759	30.12.2015 16:38:57	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: WTCHUC80.part22.rar (pid:189)
>760	30.12.2015 16:38:57	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by vuolter** [comment]
Could you post the header of the http response you get opening http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar?

**Comment by darkpella** [comment]
@vuolter: would be glad to, if I knew how...

**Comment by GammaC0de** [comment]
@vuolter 
```
(Status-Line)	HTTP/1.1 302 Moved
Server	nginx
Date	Wed, 30 Dec 2015 20:49:27 GMT
Content-Type	text/plain
Transfer-Encoding	chunked
Connection	close
Location	http://str145.ezbytez.com/files/9/co75x7r9t4ww0v/WTCHUC80.part22.rar
X-Powered-By	PleskLin
MS-Author-Via	DAV
```
```
(Request-Line)	GET /files/9/co75x7r9t4ww0v/WTCHUC80.part22.rar HTTP/1.1
Host	str145.ezbytez.com
User-Agent	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language	he,en-US;q=0.7,en;q=0.3
Accept-Encoding	gzip, deflate
DNT	1
Connection	keep-alive
```
```
(Status-Line)	HTTP/1.1 200 OK
Date	Wed, 30 Dec 2015 20:50:58 GMT
Server	Apache/2.4.7 (Ubuntu)
Last-Modified	Sat, 28 Nov 2015 15:34:29 GMT
Etag	"20000000-5259b8b342dd8"
Accept-Ranges	bytes
Content-Length	536870912
Connection	close
Content-Type	application/rar
```

**Comment by darkpella** [comment]
@vuolter , maybe I found out myself...

this should be the headers I get browsing the address you mentioned above.
I logged into EB prior to browsing the address with FF.
Browsing that address resulted in the download starting.
Please le me know whether this the feedback you expected.

Thanks 
darkpella

http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar

>GET /9ng1lh2eqgdb/WTCHUC80.part22.rar HTTP/1.1
>Host: www.easybytez.com
>User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
>Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
>Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
>Accept-Encoding: gzip, deflate
>Cookie: _jsuid=2991038272; login=darkpella; _referrer_og=http%3A%2F%2Fncrypt.in%2Flink-212776792; xfss=xo2w68zqtvcrb3ul; ref_url=http%3A%2F%2Fwww.easybytez.com%2F9ng1lh2eqgdb%2FWTCHUC80.part22.rar; _first_pageview=1; heatmaps_g2g_100681576=yes
>Connection: keep-alive
>
>HTTP/1.1 302 Moved
>Server: nginx
>Date: Wed, 30 Dec 2015 20:53:42 GMT
>Content-Type: text/plain
>Transfer-Encoding: chunked
>Connection: close
>Set-Cookie: http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar
>Location: http://str145.ezbytez.com/files/8/smhrxf39pd9j1n/WTCHUC80.part22.rar
>X-Powered-By: PleskLin
>MS-Author-Via: DAV
>----------------------------------------------------------
>http://str145.ezbytez.com/files/8/smhrxf39pd9j1n/WTCHUC80.part22.rar
>
>GET /files/8/smhrxf39pd9j1n/WTCHUC80.part22.rar HTTP/1.1
>Host: str145.ezbytez.com
>User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
>Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
>Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
>Accept-Encoding: gzip, deflate
>Connection: keep-alive
>
>HTTP/1.1 200 OK
>Date: Wed, 30 Dec 2015 20:55:12 GMT
>Server: Apache/2.4.7 (Ubuntu)
>Last-Modified: Sat, 28 Nov 2015 15:34:29 GMT
>Etag: "20000000-5259b8b342dd8"
>Accept-Ranges: bytes
>Content-Length: 536870912
>Connection: close
>Content-Type: application/rar

**Comment by vuolter** [comment]
I can work with this, thanks. :)

**Comment by darkpella** [comment]
@vuolter @GammaC0de thanks guys!

**Comment by GammaC0de** [comment]
:+1:

**Comment by vuolter** [comment]
@darkpella Okay, I need the debug log too. :p

**Comment by darkpella** [comment]
@vuolter: never did this before, wait a minute..

**Comment by vuolter** [comment]
"webui" -> "config" -> "general" -> "debug" (I hope is correct XD).

**Comment by darkpella** [comment]
@vuolter ayay sir it is correct ;)

Where will the debug log be saved to?

**Comment by vuolter** [comment]
The debug file under the pyload config folder, anyway post here the console log directly. ;)

**Comment by GammaC0de** [comment]
```
30.12.2015 23:43:14 INFO      Download starts: http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar
30.12.2015 23:43:14 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
30.12.2015 23:43:14 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/41.0`
30.12.2015 23:43:15 DEBUG     HOSTER EasybytezCom[189]: Plugin version: 0.28
30.12.2015 23:43:15 DEBUG     HOSTER EasybytezCom[189]: Plugin status: testing
30.12.2015 23:43:15 WARNING   HOSTER EasybytezCom[189]: Plugin may be unstable
30.12.2015 23:43:15 DEBUG     HOSTER EasybytezCom[189]: Config option `use_premium` not found, use default `True`
30.12.2015 23:43:15 INFO      ACCOUNT EasybytezCom: Grabbing account info for user `kirner`...
30.12.2015 23:43:15 DEBUG     ACCOUNT EasybytezCom: LOAD URL http://www.easybytez.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
30.12.2015 23:43:15 DEBUG     ACCOUNT EasybytezCom: Expire date: 21 June 2016
30.12.2015 23:43:15 DEBUG     ACCOUNT EasybytezCom: Valid until: 1466456400.0
30.12.2015 23:43:15 DEBUG     ACCOUNT EasybytezCom: LEECH TRAFFIC PATTERN not found
30.12.2015 23:43:15 DEBUG     ACCOUNT EasybytezCom: Account info for user `kirner`: {'login': {'timestamp': 1451511736.194033, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account EasybytezCom>, 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1466456400.0, 'login': 'kirner', 'type': 'EasybytezCom', 'options': {'limitdl': ['0']}}}
30.12.2015 23:43:15 INFO      HOSTER EasybytezCom[189]: Grabbing link info...
30.12.2015 23:43:15 DEBUG     HOSTER EasybytezCom[189]: Link info: {'status': 2, 'hash': {}, 'name': u'WTCHUC80.part22.rar', 'url': u'http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar', 'pattern': {'S': u'512.0', 'U': u'MB', 'N': u'WTCHUC80.part22.rar'}, 'size': 536870912}
30.12.2015 23:43:15 DEBUG     HOSTER EasybytezCom[189]: Previous link info: {}
30.12.2015 23:43:15 INFO      HOSTER EasybytezCom[189]: Link name: WTCHUC80.part22.rar
30.12.2015 23:43:15 INFO      HOSTER EasybytezCom[189]: Link size: 512.00 MiB (536870912 bytes)
30.12.2015 23:43:15 INFO      HOSTER EasybytezCom[189]: Link status: online
30.12.2015 23:43:15 INFO      HOSTER EasybytezCom[189]: Processing url: http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar
30.12.2015 23:43:15 INFO      HOSTER EasybytezCom[189]: Looking for direct download link...
30.12.2015 23:43:15 DEBUG     HOSTER EasybytezCom[189]: Redirect #0 to: http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar
30.12.2015 23:43:15 DEBUG     HOSTER EasybytezCom[189]: LOAD URL http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
30.12.2015 23:43:16 DEBUG     HOSTER EasybytezCom[189]: Redirect #1 to: http://str145.ezbytez.com/files/9/0fyhvtgpvk4v2s/wtchuc80.part22.rar
30.12.2015 23:43:16 DEBUG     HOSTER EasybytezCom[189]: LOAD URL http://str145.ezbytez.com/files/9/0fyhvtgpvk4v2s/wtchuc80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
30.12.2015 23:43:16 INFO      HOSTER EasybytezCom[189]: Direct download link not found
30.12.2015 23:43:16 DEBUG     HOSTER EasybytezCom[189]: LOAD URL http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
Traceback (most recent call last):
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 285, in write
    raise Exception("Loaded Url exceeded limit")
Exception: Loaded Url exceeded limit
30.12.2015 23:43:18 DEBUG     pycurl exception 23: Failed writing body (0 != 16384)
30.12.2015 23:43:18 ERROR     pycurl error 23: Failed writing body (0 != 16384)
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 191, in run
    pyfile.plugin.preprocessing(self)
  File "/home/user/.pyload-0.4.9/userplugins/internal/Base.py", line 288, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/user/.pyload-0.4.9/userplugins/internal/Hoster.py", line 100, in _process
    self.process(self.pyfile)
  File "/home/user/.pyload-0.4.9/userplugins/internal/SimpleHoster.py", line 266, in process
    self.preload()
  File "/home/user/.pyload-0.4.9/userplugins/internal/SimpleHoster.py", line 244, in preload
    decode=self.TEXT_ENCODING)
  File "/home/user/.pyload-0.4.9/userplugins/internal/Base.py", line 495, in load
    return super(Base, self).load(*args, **kwargs)
  File "/home/user/.pyload-0.4.9/userplugins/internal/Plugin.py", line 202, in load
    html = req.load(url, get, post, ref, bool(cookies), just_header, multipart, decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/usr/share/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 205, in load
    self.c.perform()
error: (23, 'Failed writing body (0 != 16384)')
30.12.2015 23:43:18 INFO      Debug Report written to debug_EasybytezCom_30-12-2015_23-43-18.zip
30.12.2015 23:43:18 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
30.12.2015 23:43:18 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: WTCHUC80.part22.rar (pid:178)
30.12.2015 23:43:18 INFO      ADDON UnSkipOnFail: No duplicates found
30.12.2015 23:43:18 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
30.12.2015 23:43:18 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
30.12.2015 23:43:18 DEBUG     All downloads processed
30.12.2015 23:43:20 INFO      ADDON ExternalScripts: Activated scripts in folder `package_extracted`: s.sh
30.12.2015 23:43:20 INFO      ADDON ExternalScripts: Activated scripts in folder `package_deleted`: s.sh

```

**Comment by darkpella** [comment]
@vuolter here's the debug files.

[debug_EasybytezCom_30-12-2015_22-49-03.zip](https://github.com/pyload/pyload/files/75216/debug_EasybytezCom_30-12-2015_22-49-03.zip)
[debug_EasybytezCom_30-12-2015_22-49-15.zip](https://github.com/pyload/pyload/files/75217/debug_EasybytezCom_30-12-2015_22-49-15.zip)

**Comment by darkpella** [comment]
@vuolter here's the console log:
>171	30.12.2015 22:57:21	DEBUG	Plugin EasybytezCom not found
>172	30.12.2015 22:57:21	DEBUG	Available plugins : {'GigasizeCom': {'user': False, 'name': 'GigasizeCom', 'v': 0.16}, 'LinksaveIn': {'user': False, 'name': 'LinksaveIn', 'v': 0.16}, 'SolveMedia': {'user': False, 'name': 'SolveMedia', 'v': 0.17}, 'ReCaptcha': {'user': False, 'name': 'ReCaptcha', 'v': 0.2}, 'AdYouLike': {'user': False, 'name': 'AdYouLike', 'v': 0.09}, 'ShareonlineBiz': {'user': False, 'name': 'ShareonlineBiz', 'v': 0.16}, 'CircleCaptcha': {'user': False, 'name': 'CircleCaptcha', 'v': 1.06}, 'NetloadIn': {'user': False, 'name': 'NetloadIn', 'v': 0.16}, 'AdsCaptcha': {'user': False, 'name': 'AdsCaptcha', 'v': 0.12}}
>173	30.12.2015 22:57:21	INFO	Download starts: WTCHUC80.part22.rar
>174	30.12.2015 22:57:21	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
>175	30.12.2015 22:57:21	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
>176	30.12.2015 22:57:22	DEBUG	HOSTER EasybytezCom[6139]: Plugin version: 0.28
>177	30.12.2015 22:57:22	DEBUG	HOSTER EasybytezCom[6139]: Plugin status: testing
>178	30.12.2015 22:57:22	WARNING	HOSTER EasybytezCom[6139]: Plugin may be unstable
>179	30.12.2015 22:57:22	DEBUG	HOSTER EasybytezCom[6139]: Config option `use_premium` not found, use default `True`
>180	30.12.2015 22:57:22	INFO	ACCOUNT EasybytezCom: Grabbing account info for user `darkpella`...
>181	30.12.2015 22:57:22	DEBUG	ACCOUNT EasybytezCom: LOAD URL http://www.easybytez.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
>182	30.12.2015 22:57:23	DEBUG	ACCOUNT EasybytezCom: Expire date: 25 December 2016
>183	30.12.2015 22:57:23	DEBUG	ACCOUNT EasybytezCom: Valid until: 1482620400.0
>184	30.12.2015 22:57:23	DEBUG	ACCOUNT EasybytezCom: LEECH TRAFFIC PATTERN not found
>185	30.12.2015 22:57:23	DEBUG	ACCOUNT EasybytezCom: Account info for user `darkpella`: {'login': {'timestamp': 1451512011.523087, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1482620400.0, 'login': 'darkpella', 'type': 'EasybytezCom', 'options': {'limitdl': ['0']}}}
>186	30.12.2015 22:57:23	INFO	HOSTER EasybytezCom[6139]: Grabbing link info...
>187	30.12.2015 22:57:25	DEBUG	HOSTER EasybytezCom[6139]: Link info: {'status': 2, 'hash': {}, 'name': u'WTCHUC80.part22.rar', 'url': u'http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar', 'pattern': {'S': u'512.0', 'U': u'MB', 'N': u'WTCHUC80.part22.rar'}, 'size': 536870912}
>188	30.12.2015 22:57:25	DEBUG	HOSTER EasybytezCom[6139]: Previous link info: {}
>189	30.12.2015 22:57:25	INFO	HOSTER EasybytezCom[6139]: Link name: WTCHUC80.part22.rar
>190	30.12.2015 22:57:25	INFO	HOSTER EasybytezCom[6139]: Link size: 512.00 MiB (536870912 bytes)
>191	30.12.2015 22:57:25	INFO	HOSTER EasybytezCom[6139]: Link status: online
>192	30.12.2015 22:57:25	INFO	HOSTER EasybytezCom[6139]: Processing url: http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar
>193	30.12.2015 22:57:25	INFO	HOSTER EasybytezCom[6139]: Looking for direct download link...
>194	30.12.2015 22:57:25	DEBUG	HOSTER EasybytezCom[6139]: Redirect #0 to: http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar
>195	30.12.2015 22:57:25	DEBUG	HOSTER EasybytezCom[6139]: LOAD URL http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
>196	30.12.2015 22:57:26	DEBUG	HOSTER EasybytezCom[6139]: Redirect #1 to: http://str145.ezbytez.com/files/7/ymyt7ijajmo4nr/wtchuc80.part22.rar
>197	30.12.2015 22:57:26	DEBUG	HOSTER EasybytezCom[6139]: LOAD URL http://str145.ezbytez.com/files/7/ymyt7ijajmo4nr/wtchuc80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
>198	30.12.2015 22:57:27	INFO	HOSTER EasybytezCom[6139]: Direct download link not found
>199	30.12.2015 22:57:27	DEBUG	HOSTER EasybytezCom[6139]: LOAD URL http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
>200	30.12.2015 22:57:38	DEBUG	pycurl exception 23: Failed writing body (0 != 1418)
>201	30.12.2015 22:57:38	ERROR	pycurl error 23: Failed writing body (0 != 1418)
>202	30.12.2015 22:57:38	INFO	Debug Report written to debug_EasybytezCom_30-12-2015_22-57-38.zip
>203	30.12.2015 22:57:38	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
>204	30.12.2015 22:57:38	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: WTCHUC80.part22.rar (pid:189)
>205	30.12.2015 22:57:38	INFO	ADDON UnSkipOnFail: No duplicates found
>206	30.12.2015 22:57:38	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
>207	30.12.2015 22:57:38	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
>208	30.12.2015 22:57:38	DEBUG	All downloads processed
>209	30.12.2015 22:57:40	DEBUG	Plugin EasybytezCom not found
>210	30.12.2015 22:57:40	DEBUG	Available plugins : {'GigasizeCom': {'user': False, 'name': 'GigasizeCom', 'v': 0.16}, 'LinksaveIn': {'user': False, 'name': 'LinksaveIn', 'v': 0.16}, 'SolveMedia': {'user': False, 'name': 'SolveMedia', 'v': 0.17}, 'ReCaptcha': {'user': False, 'name': 'ReCaptcha', 'v': 0.2}, 'AdYouLike': {'user': False, 'name': 'AdYouLike', 'v': 0.09}, 'ShareonlineBiz': {'user': False, 'name': 'ShareonlineBiz', 'v': 0.16}, 'CircleCaptcha': {'user': False, 'name': 'CircleCaptcha', 'v': 1.06}, 'NetloadIn': {'user': False, 'name': 'NetloadIn', 'v': 0.16}, 'AdsCaptcha': {'user': False, 'name': 'AdsCaptcha', 'v': 0.12}}
>211	30.12.2015 22:57:40	INFO	Download starts: WTCHUC80.part22.rar
>212	30.12.2015 22:57:40	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
>213	30.12.2015 22:57:40	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
>214	30.12.2015 22:57:41	DEBUG	HOSTER EasybytezCom[6139]: Plugin version: 0.28
>215	30.12.2015 22:57:41	DEBUG	HOSTER EasybytezCom[6139]: Plugin status: testing
>216	30.12.2015 22:57:41	WARNING	HOSTER EasybytezCom[6139]: Plugin may be unstable
>217	30.12.2015 22:57:41	DEBUG	HOSTER EasybytezCom[6139]: Config option `use_premium` not found, use default `True`
>218	30.12.2015 22:57:41	INFO	ACCOUNT EasybytezCom: Grabbing account info for user `darkpella`...
>219	30.12.2015 22:57:41	DEBUG	ACCOUNT EasybytezCom: LOAD URL http://www.easybytez.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
>220	30.12.2015 22:57:42	DEBUG	ACCOUNT EasybytezCom: Expire date: 25 December 2016
>221	30.12.2015 22:57:42	DEBUG	ACCOUNT EasybytezCom: Valid until: 1482620400.0
>222	30.12.2015 22:57:42	DEBUG	ACCOUNT EasybytezCom: LEECH TRAFFIC PATTERN not found
>223	30.12.2015 22:57:42	DEBUG	ACCOUNT EasybytezCom: Account info for user `darkpella`: {'login': {'timestamp': 1451512011.523087, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1482620400.0, 'login': 'darkpella', 'type': 'EasybytezCom', 'options': {'limitdl': ['0']}}}
>224	30.12.2015 22:57:42	INFO	HOSTER EasybytezCom[6139]: Grabbing link info...
>225	30.12.2015 22:57:43	DEBUG	HOSTER EasybytezCom[6139]: Link info: {'status': 2, 'hash': {}, 'name': u'WTCHUC80.part22.rar', 'url': u'http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar', 'pattern': {'S': u'512.0', 'U': u'MB', 'N': u'WTCHUC80.part22.rar'}, 'size': 536870912}
>226	30.12.2015 22:57:43	DEBUG	HOSTER EasybytezCom[6139]: Previous link info: {}
>227	30.12.2015 22:57:43	INFO	HOSTER EasybytezCom[6139]: Link name: WTCHUC80.part22.rar
>228	30.12.2015 22:57:43	INFO	HOSTER EasybytezCom[6139]: Link size: 512.00 MiB (536870912 bytes)
>229	30.12.2015 22:57:43	INFO	HOSTER EasybytezCom[6139]: Link status: online
>230	30.12.2015 22:57:43	INFO	HOSTER EasybytezCom[6139]: Processing url: http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar
>231	30.12.2015 22:57:43	INFO	HOSTER EasybytezCom[6139]: Looking for direct download link...
>232	30.12.2015 22:57:43	DEBUG	HOSTER EasybytezCom[6139]: Redirect #0 to: http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar
>233	30.12.2015 22:57:43	DEBUG	HOSTER EasybytezCom[6139]: LOAD URL http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
>234	30.12.2015 22:57:44	DEBUG	HOSTER EasybytezCom[6139]: Redirect #1 to: http://str145.ezbytez.com/files/0/rzky0qygdg0uuq/wtchuc80.part22.rar
>235	30.12.2015 22:57:44	DEBUG	HOSTER EasybytezCom[6139]: LOAD URL http://str145.ezbytez.com/files/0/rzky0qygdg0uuq/wtchuc80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
>236	30.12.2015 22:57:45	INFO	HOSTER EasybytezCom[6139]: Direct download link not found
>237	30.12.2015 22:57:45	DEBUG	HOSTER EasybytezCom[6139]: LOAD URL http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
>238	30.12.2015 22:57:55	DEBUG	pycurl exception 23: Failed writing body (0 != 2836)
>239	30.12.2015 22:57:55	ERROR	pycurl error 23: Failed writing body (0 != 2836)

**Comment by GammaC0de** [comment]
@darkpella when posting logs, please add triple \` (\`\`\`) in the start and end of the pasted log
this makes is more readable, e.g:
```
237 30.12.2015 22:57:45 DEBUG HOSTER EasybytezCom[6139]: LOAD URL http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
238 30.12.2015 22:57:55 DEBUG pycurl exception 23: Failed writing body (0 != 2836)
239 30.12.2015 22:57:55 ERROR pycurl error 23: Failed writing body (0 != 2836) 
```

**Comment by GammaC0de** [comment]
Well obviously the problem is with `isdownload()` not correctly detecting.
It seems that `easybytez.com` responses different to `HEAD` and `GET` requests so no way to check if the the URL is direct download.

Look at the headers received:
```
31.12.2015 00:09:36 DEBUG     HOSTER EasybytezCom[190]: Redirect #0 to: http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar
31.12.2015 00:09:36 DEBUG     HOSTER EasybytezCom[190]: LOAD URL http://www.easybytez.com/9ng1lh2eqgdb/WTCHUC80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
31.12.2015 00:09:36 DEBUG     HOSTER EasybytezCom[190]: Header:{'code': 302, 'x-powered-by': 'plesklin', 'ms-author-via': 'dav', 'server': 'nginx', 'connection': 'close', 'location': 'http://str145.ezbytez.com/files/5/geqspbod6c62m4/wtchuc80.part22.rar', 'date': 'wed, 30 dec 2015 22:08:07 gmt', 'content-type': 'text/plain'}
31.12.2015 00:09:36 DEBUG     HOSTER EasybytezCom[190]: Redirect #1 to: http://str145.ezbytez.com/files/5/geqspbod6c62m4/wtchuc80.part22.rar
31.12.2015 00:09:36 DEBUG     HOSTER EasybytezCom[190]: LOAD URL http://str145.ezbytez.com/files/5/geqspbod6c62m4/wtchuc80.part22.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
31.12.2015 00:09:36 DEBUG     HOSTER EasybytezCom[190]: Header:{'date': 'wed, 30 dec 2015 22:09:38 gmt', 'connection': 'close', 'code': 404, 'content-type': 'text/html; charset=iso-8859-1', 'server': 'apache/2.4.7 (ubuntu)'}
```

**Comment by darkpella** [comment]
@GammaC0de so that's the trick...

**Comment by GammaC0de** [comment]
OK, Problem solved :smile: 

@vuolter Apparently the us of `is` causes many problems...

**Comment by darkpella** [comment]
@vuolter @GammaC0de  great job, mates!

**Comment by darkpella** [comment]
@GammaC0de @vuolter just tested commit 5b235eb now. 
Issue fixing confirmed, thanks a lot!

**Comment by vuolter** [comment]
@GammaC0de As you see I love the `is` statement, maybe too much. :D
