### ISSUE TITLE
fehlgeschlagen'utf8' codec can't decode byte 0xff in position 0: invalid start byte 

### ISSUE THREAD

**Issue by geronimoronin** [pyload/pyload#2245]
WARNING Download failed: file.rar | 'utf8' codec can't decode byte 0xff in position 0: invalid start byte 
RaspberryPI

**Comment by mcflym** [comment]
Same here with UploadedTo Files...

Seriously... what happend with the last update?

Share-Online and UploadedTo aren't working.

and again ALL plugins are up to date!

**Comment by vuolter** [comment]
@geronimoronin Debug log + sample url. Please. :)

**Comment by geronimoronin** [comment]
31.12.2015 09:30:44	INFO	starte pyLoad 0.4.9
388	31.12.2015 09:30:44	INFO	Benutze Home-Verzeichnis: /home/censored/.pyload
389	31.12.2015 09:30:48	INFO	Aktivierte Plugins: ClickNLoad, EventMapper, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
390	31.12.2015 09:30:48	INFO	Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, ExternalScripts, HotFolder, IRC, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
391	31.12.2015 09:30:48	INFO	Downloadzeit: True
392	31.12.2015 09:30:48	INFO	Starte ThriftBackend: 0.0.0.0:7227
393	31.12.2015 09:30:50	INFO	Free space: 83.41 GiB
394	31.12.2015 09:30:50	INFO	Starting threaded webserver: 0.0.0.0:8000
395	31.12.2015 09:30:50	INFO	Activating Accounts...
396	31.12.2015 09:30:50	INFO	ACCOUNT DebridItaliaCom: Adding user `censored`...
397	31.12.2015 09:30:50	INFO	ACCOUNT DebridItaliaCom: Login user `censored`...
398	31.12.2015 09:30:51	INFO	ACCOUNT DebridItaliaCom: Grabbing account info for user `censored`...
399	31.12.2015 09:30:51	INFO	Activating Plugins...
400	31.12.2015 09:30:52	WARNING	ADDON UpdateManager: Unable to connect to the server to retrieve updates
401	31.12.2015 09:30:52	INFO	ADDON XFileSharing: Auto-discover new hosters
402	31.12.2015 09:30:53	INFO	ADDON XFileSharing: Auto-discover new crypters
403	31.12.2015 09:30:53	INFO	pyLoad is up and running
404	31.12.2015 09:30:59	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
405	31.12.2015 09:31:24	INFO	Added package stone containing 1 links
406	31.12.2015 09:31:25	INFO	Download starts: http://uploaded.net/file/hpsbvqwf/love-Stone-205-SD.part1.rar
407	31.12.2015 09:31:26	WARNING	HOSTER UploadedTo[1]: Plugin may be unstable
408	31.12.2015 09:31:26	INFO	HOSTER UploadedTo[1]: Grabbing link info...
409	31.12.2015 09:31:26	INFO	HOSTER UploadedTo[1]: Link name: love-Stone-205-SD.part1.rar
410	31.12.2015 09:31:26	INFO	HOSTER UploadedTo[1]: Link size: 109.67 MiB (115000000 bytes)
411	31.12.2015 09:31:26	INFO	HOSTER UploadedTo[1]: Link status: online
412	31.12.2015 09:31:26	INFO	HOSTER UploadedTo[1]: Processing url: http://uploaded.net/file/hpsbvqwf/love-Stone-205-SD.part1.rar
413	31.12.2015 09:31:26	INFO	HOSTER UploadedTo[1]: Looking for direct download link...
414	31.12.2015 09:31:26	INFO	HOSTER UploadedTo[1]: Direct download link not found
415	31.12.2015 09:31:26	INFO	HOSTER UploadedTo[1]: Checking for link errors...
416	31.12.2015 09:31:26	INFO	HOSTER UploadedTo[1]: No errors found
417	31.12.2015 09:31:26	INFO	HOSTER UploadedTo[1]: Processing as free download...
418	31.12.2015 09:31:27	WARNING	Download failed: love-Stone-205-SD.part1.rar | 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
419	31.12.2015 09:31:27	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: love-Stone-205-SD.part1.rar (pid:1)
420	31.12.2015 09:31:27	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by mcflym** [comment]
Hi, you need to provide a DEBUG Log!

Please have a look at "Settings" --> "General" and set "Debug Log" to "On". Restart pyload, now you can post the debug log. There are many more lines in the log with the word "DEBUG" in the line.

**Comment by Ibotst** [comment]
Hi,
I log with set "Debug Log" to "on". See attached file.

[log.txt](https://github.com/pyload/pyload/files/75585/log.txt)

**Comment by Speil** [comment]
Same here - I already did https://github.com/pyload/pyload/commit/9a535d75f6f1a898f5fcc0a925f7cbb22fd449bb and https://github.com/Gutz-Pilz/pyload/commit/477046e0b1bb37e294db6ceab68462c0fc797ea7

**Comment by GammaC0de** [comment]
@vuolter Good ol' `fixurl()` not fixed. (hehe)

```
01.01.2016 00:31:31 WARNING   Download failed: 羋月傳01集.mp4 | 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 191, in run
    pyfile.plugin.preprocessing(self)
  File "/home/user/.pyload-0.4.9/userplugins/internal/Base.py", line 288, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/user/.pyload-0.4.9/userplugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/home/user/.pyload-0.4.9/userplugins/hoster/DailymotionCom.py", line 131, in process
    self.download(self.get_link(streams, quality))
  File "/home/user/.pyload-0.4.9/userplugins/internal/Hoster.py", line 272, in download
    dl_basename = parse_name(self.pyfile.name)
  File "/home/user/.pyload-0.4.9/userplugins/internal/misc.py", line 511, in parse_name
    path  = fixurl(decode(value), unquote=False)
  File "/home/user/.pyload-0.4.9/userplugins/internal/misc.py", line 451, in fixurl
    url = html_unescape(decode(url).decode('unicode-escape'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

**Comment by geronimoronin** [comment]
01.01.2016 14:57:45	INFO	starte pyLoad 0.4.9
509	01.01.2016 14:57:45	INFO	Benutze Home-Verzeichnis: /home/geronimo/.pyload
510	01.01.2016 14:57:45	DEBUG	Remote activated: True
511	01.01.2016 14:57:50	DEBUG	created index of plugins
512	01.01.2016 14:57:50	INFO	Aktivierte Plugins: ClickNLoad, EventMapper, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
513	01.01.2016 14:57:50	INFO	Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, ExternalScripts, HotFolder, IRC, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
514	01.01.2016 14:57:50	INFO	Downloadzeit: True
515	01.01.2016 14:57:50	INFO	Starte ThriftBackend: 0.0.0.0:7227
516	01.01.2016 14:57:51	INFO	Free space: 83.41 GiB
517	01.01.2016 14:57:51	INFO	Starting threaded webserver: 0.0.0.0:8000
518	01.01.2016 14:57:52	INFO	Activating Accounts...
519	01.01.2016 14:57:52	INFO	ACCOUNT DebridItaliaCom: Adding user `censored`...
520	01.01.2016 14:57:52	DEBUG	ACCOUNT DebridItaliaCom: Reached login timeout for user `censored`
521	01.01.2016 14:57:52	INFO	ACCOUNT DebridItaliaCom: Login user `censored`...
522	01.01.2016 14:57:52	DEBUG	ACCOUNT DebridItaliaCom: LOAD URL https://debriditalia.com/login.php | redirect=True | cookies=True | get={'p': '**********', 'u': 'censored'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
523	01.01.2016 14:57:53	INFO	ACCOUNT DebridItaliaCom: Grabbing account info for user `censored`...
524	01.01.2016 14:57:53	DEBUG	ACCOUNT DebridItaliaCom: LOAD URL http://debriditalia.com/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
525	01.01.2016 14:57:53	DEBUG	ACCOUNT DebridItaliaCom: Account info for user `censored`: {'login': {'timestamp': 1451656672.232943, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1465305900.0, 'login': 'geronimoronin', 'type': 'DebridItaliaCom', 'options': {'limitdl': ['0']}}}
526	01.01.2016 14:57:53	INFO	Activating Plugins...
527	01.01.2016 14:57:53	DEBUG	ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
528	01.01.2016 14:57:53	DEBUG	ADDON ExtractArchive: Found UnRar 4.10 | Found UnZip 2.7.3 | Found UnTar 2.7.3
529	01.01.2016 14:57:54	INFO	ADDON XFileSharing: Auto-discover new hosters
530	01.01.2016 14:57:54	DEBUG	ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|cramit\.in|easybytez\.com|exashare\.com|fileom\.com|filerio\.com|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uplea\.com|uptobox\.com|vidplay\.net))(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
531	01.01.2016 14:57:55	INFO	ADDON XFileSharing: Auto-discover new crypters
532	01.01.2016 14:57:55	DEBUG	ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
533	01.01.2016 14:57:55	INFO	pyLoad is up and running
534	01.01.2016 14:58:01	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
535	01.01.2016 14:58:13	DEBUG	Plugin UploadedTo not found
536	01.01.2016 14:58:13	DEBUG	Available plugins : {'GigasizeCom': {'user': False, 'name': 'GigasizeCom', 'v': 0.16}, 'LinksaveIn': {'user': False, 'name': 'LinksaveIn', 'v': 0.16}, 'ReCaptcha': {'user': False, 'name': 'ReCaptcha', 'v': 0.2}, 'AdYouLike': {'user': False, 'name': 'AdYouLike', 'v': 0.09}, 'SolveMedia': {'user': False, 'name': 'SolveMedia', 'v': 0.17}, 'CircleCaptcha': {'user': False, 'name': 'CircleCaptcha', 'v': 1.06}, 'NetloadIn': {'user': False, 'name': 'NetloadIn', 'v': 0.16}, 'AdsCaptcha': {'user': False, 'name': 'AdsCaptcha', 'v': 0.12}, 'ShareonlineBiz': {'user': False, 'name': 'ShareonlineBiz', 'v': 0.16}}
537	01.01.2016 14:58:13	INFO	Download starts: love-Stone-205-SD.part1.rar
538	01.01.2016 14:58:13	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
539	01.01.2016 14:58:14	DEBUG	HOSTER UploadedTo[1]: Plugin version: 1.01
540	01.01.2016 14:58:14	DEBUG	HOSTER UploadedTo[1]: Plugin status: testing
541	01.01.2016 14:58:14	WARNING	HOSTER UploadedTo[1]: Plugin may be unstable
542	01.01.2016 14:58:14	INFO	HOSTER UploadedTo[1]: Grabbing link info...
543	01.01.2016 14:58:14	DEBUG	HOSTER UploadedTo[1]: Link info: {'status': 2, 'hash': {}, 'name': 'love-Stone-205-SD.part1.rar', 'url': u'http://uploaded.net/file/hpsbvqwf', 'pattern': {'ID': u'hpsbvqwf'}, 'size': 115000000}
544	01.01.2016 14:58:14	DEBUG	HOSTER UploadedTo[1]: Previous link info: {}
545	01.01.2016 14:58:14	INFO	HOSTER UploadedTo[1]: Link name: love-Stone-205-SD.part1.rar
546	01.01.2016 14:58:14	INFO	HOSTER UploadedTo[1]: Link size: 109.67 MiB (115000000 bytes)
547	01.01.2016 14:58:14	INFO	HOSTER UploadedTo[1]: Link status: online
548	01.01.2016 14:58:14	INFO	HOSTER UploadedTo[1]: Processing url: http://uploaded.net/file/hpsbvqwf
549	01.01.2016 14:58:14	INFO	HOSTER UploadedTo[1]: Looking for direct download link...
550	01.01.2016 14:58:14	DEBUG	HOSTER UploadedTo[1]: Redirect #0 to: http://uploaded.net/file/hpsbvqwf
551	01.01.2016 14:58:14	DEBUG	HOSTER UploadedTo[1]: LOAD URL http://uploaded.net/file/hpsbvqwf | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
552	01.01.2016 14:58:14	INFO	HOSTER UploadedTo[1]: Direct download link not found
553	01.01.2016 14:58:15	DEBUG	HOSTER UploadedTo[1]: LOAD URL http://uploaded.net/file/hpsbvqwf | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
554	01.01.2016 14:58:15	INFO	HOSTER UploadedTo[1]: Checking for link errors...
555	01.01.2016 14:58:15	INFO	HOSTER UploadedTo[1]: No errors found
556	01.01.2016 14:58:15	INFO	HOSTER UploadedTo[1]: Processing as free download...
557	01.01.2016 14:58:15	DEBUG	HOSTER UploadedTo[1]: LOAD URL http://uploaded.net/language/en | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
558	01.01.2016 14:58:15	DEBUG	HOSTER UploadedTo[1]: LOAD URL http://uploaded.net/js/download.js | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
559	01.01.2016 14:58:15	DEBUG	CAPTCHA UploadedTo[1]: ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
560	01.01.2016 14:58:15	DEBUG	HOSTER UploadedTo[1]: LOAD URL http://www.google.com/recaptcha/api/challenge | redirect=True | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
561	01.01.2016 14:58:15	DEBUG	CAPTCHA UploadedTo[1]: ReCaptcha | Challenge: 03AHJ_VusAMArYQJefLLpCxq_GPDEPmKV5OA3qJna4SBlNW5noA5iPiuaCv2DA8BiYYs76XYr8E78YAotbYjMg_CwamQgj3C7QjjfXUkomV8QyBmZKDoJoN71H4cf3qHGJZrORpGMHnRgbqfnp_Q8Ld2XTO-H0RCKzjPSxOBVpd3hTb3T76Q1es6g2h1AHe9qk3qRM2Tu7iMuOa_J1phfHSIA_dWyWD4-ODQ
562	01.01.2016 14:58:15	DEBUG	HOSTER UploadedTo[1]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
563	01.01.2016 14:58:15	DEBUG	HOSTER UploadedTo[1]: LOAD URL http://www.google.com/recaptcha/api/reload | redirect=True | cookies=True | get={'reason': 'i', 'c': u'03AHJ_VusAMArYQJefLLpCxq_GPDEPmKV5OA3qJna4SBlNW5noA5iPiuaCv2DA8BiYYs76XYr8E78YAotbYjMg_CwamQgj3C7QjjfXUkomV8QyBmZKDoJoN71H4cf3qHGJZrORpGMHnRgbqfnp_Q8Ld2XTO-H0RCKzjPSxOBVpd3hTb3T76Q1es6g2h1AHe9qk3qRM2Tu7iMuOa_J1phfHSIA_dWyWD4-ODQ', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
564	01.01.2016 14:58:15	DEBUG	CAPTCHA UploadedTo[1]: ReCaptcha | Second challenge: 03AHJ_VuvVJVX81dQqOxUr5d2xJ3HR4GdDnZ_AB-Inw77PbHoYcznAg5VXirgIP_as41sBd4tXDW7vAksgQ_5qvy-XVe4sxTJIcke7n0FHGiA_6FPjp1zZWkdyRN0CnGSjiU29Ja6l9Ug_1YzSnKuE-4Dk3gr78dDznhxgfY1chGitziZyVcAK61Azw87U4KCLBihTFeIzePZb-shGUZZuukI9No1DI0xqcw
565	01.01.2016 14:58:15	DEBUG	CAPTCHA UploadedTo[1]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | redirect=True | cookies=True | get={'c': u'03AHJ_VuvVJVX81dQqOxUr5d2xJ3HR4GdDnZ_AB-Inw77PbHoYcznAg5VXirgIP_as41sBd4tXDW7vAksgQ_5qvy-XVe4sxTJIcke7n0FHGiA_6FPjp1zZWkdyRN0CnGSjiU29Ja6l9Ug_1YzSnKuE-4Dk3gr78dDznhxgfY1chGitziZyVcAK61Azw87U4KCLBihTFeIzePZb-shGUZZuukI9No1DI0xqcw'} | req= | decode=False | multipart=False | post={} | ref=False | just_header=False
566	01.01.2016 14:58:15	WARNING	Download failed: love-Stone-205-SD.part1.rar | 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
567	01.01.2016 14:58:16	INFO	Debug Report written to debug_UploadedTo_01-01-2016_14-58-15.zip
568	01.01.2016 14:58:16	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: love-Stone-205-SD.part1.rar (pid:1)
569	01.01.2016 14:58:16	INFO	ADDON UnSkipOnFail: No duplicates found
570	01.01.2016 14:58:17	DEBUG	All downloads processed
571	01.01.2016 14:58:23	WARNING	ADDON UpdateManager: Unable to connect to the server to retrieve updates

**Comment by nordic-style** [comment]
Do you need anything else to fix this?

**Comment by maddyxp** [comment]
Same here.
Some things before:
i use Smoozed.
my version: (after trying many(many,...) different versions with same problem)
´odroid@odroidNAS:~/pyload$ git status
On branch aa6e9a2
nothing to commit, working directory clean´

i wonder a little bit about: 04.01.2016 20:08:26 WARNING   ADDON UpdateManager: Unable to connect to the server to retrieve updates

then the download want to start as free download:
    04.01.2016 20:08:35 DEBUG     HOSTER ShareonlineBiz[1]: Plugin version: 0.65
    04.01.2016 20:08:35 DEBUG     HOSTER ShareonlineBiz[1]: Plugin status: testing
    04.01.2016 20:08:35 WARNING   HOSTER ShareonlineBiz[1]: Plugin may be unstable
    04.01.2016 20:08:35 INFO      HOSTER ShareonlineBiz[1]: Grabbing link info...
    04.01.2016 20:08:35 DEBUG     HOSTER ShareonlineBiz[1]: Link info: {'status': 2, 'hash': {}, 'name': 'BZ-03.01.16.pdf', 'url': u'http://www.share-online.biz/dl/S28T2D0OGM3', 'pattern': {'ID': u'S28T2D0OGM3'}, 'size': 27297321, 'md5': '797b084510795b76d805ec061f731f32', 'fileid': 'S28T2D0OGM3'}
04.01.2016 20:08:35 DEBUG     HOSTER ShareonlineBiz[1]: Previous link info: {}
04.01.2016 20:08:35 INFO      HOSTER ShareonlineBiz[1]: Link name: BZ-03.01.16.pdf
04.01.2016 20:08:35 INFO      HOSTER ShareonlineBiz[1]: Link size: 26.03 MiB (27297321 bytes)
04.01.2016 20:08:35 INFO      HOSTER ShareonlineBiz[1]: Link status: online
04.01.2016 20:08:35 INFO      HOSTER ShareonlineBiz[1]: Processing url: http://www.share-online.biz/dl/S28T2D0OGM3
04.01.2016 20:08:35 INFO      HOSTER ShareonlineBiz[1]: Looking for direct download link...
04.01.2016 20:08:35 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.share-online.biz/dl/S28T2D0OGM3 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
04.01.2016 20:08:35 INFO      HOSTER ShareonlineBiz[1]: Direct download link not found
04.01.2016 20:08:35 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.share-online.biz/dl/S28T2D0OGM3 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
04.01.2016 20:08:35 INFO      HOSTER ShareonlineBiz[1]: Processing as free download...
04.01.2016 20:08:35 DEBUG     HOSTER ShareonlineBiz[1]: WAIT set to timestamp 1451934519.340624 | Previous waitUntil: 0.000000
04.01.2016 20:08:35 INFO      HOSTER ShareonlineBiz[1]: Waiting 3 seconds...
 
and a little bit later: 
04.01.2016 20:08:39 WARNING   Download failed: BZ-03.01.16.pdf | 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

same with uploaded

**Comment by Speil** [comment]
Downloads working for me again - but i have nothing changed

**Comment by 1337sup3rh4x0r** [comment]
You changed nothing, but die the update manager?

**Comment by sschwart** [comment]
There is a solution in #2286 ;) 
It works great for me :)
