### ISSUE TITLE
correct() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by ViktorReinhold** [pyload/pyload#2246]
Hoster: ShareOnline.biz (Premium)

pyLoad 0.4.9 Debug Report of ShareonlineBiz 0.65

TRACEBACK:
 Traceback (most recent call last):
  File "/home/viktor/git/pyload/module/PluginThread.py", line 187, in run    pyfile.plugin.preprocessing(self)
  File "/home/viktor/git/pyload/module/plugins/internal/Base.py", line 286, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/viktor/git/pyload/module/plugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/home/viktor/git/pyload/module/plugins/internal/SimpleHoster.py", line 284, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/home/viktor/git/pyload/module/plugins/internal/Hoster.py", line 242, in download
    self.captcha.correct()
TypeError: correct() takes at least 2 arguments (1 given)

**Comment by mcflym** [comment]
voulter said this IS NOT AN ISSUE...

well...

**Comment by ViktorReinhold** [comment]
@mcflym Perhaps. I'm using the latest code from GitHub.

**Comment by GammaC0de** [comment]
@vuolter The problem is in [Base.py#L91](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Base.py#L91):
```python
        _Captcha = self.pyload.pluginManager.loadClass("captcha", self.classname) or Captcha
        self.captcha = _Captcha(pyfile)
```
pyLoad tries to load `ShareonlineBiz.py` in the "captcha" directory but actually,  `ShareonlineBiz.py` is of type `OCR`!

Also, what is the logic behind thos lines!?

**Comment by GammaC0de** [comment]
Should revert back to:
```python
        self.captcha = Captcha(pyfile)
```

IMHO..

**Comment by vuolter** [comment]
I work with the 0.4.10 in mind, and that is a mistake, because in 0.4.9 there is no OCR folder... XD
The logic was: search in `captcha` folder a namesake file (of the hoster/crypter one) and load it instead the base `Captcha`. Captcha files are for individual websites, OCRs are more general. For example a single captcha file could call more OCR processes in its recognize routine to solve a captcha image.

**Comment by GammaC0de** [comment]
:+1:
