### ISSUE TITLE
wrong download directory

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#2247]
I have a Problem with the last pyload update. After the Update (via stable Zip).
Via Zippyshare.
Pyload will create an download directory in the configuration directoy. here is a small log:
WARNING	Download failed: xxx.part1.rar | [Errno 2] No such file or directory: '/i-data/8f0844e2/.PKG/pyLoad/pyload-data/etc/pyload/i-data/8f0844e2/.PKG/pyLoad/pyload-data/etc/pyload/i-data/8f0844e2/Download/xxx.part1.rar.chunk0'
But this is not the download directory. the Download directory is
/i-data/8f0844e2/Download
whats wrong withe the new update?

**Comment by youlJunior** [comment]
Same as #2239. See how to resolve there.

**Comment by Mister-XY** [comment]
Yes, that solve one error. Now i get the next error.

**Comment by vuolter** [comment]
@Mister-XY Please, open a new ticket (with debug log print).
