### ISSUE TITLE
no Download

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#2248]
I can't download via zippyshare.
Log
http://pastebin.com/wj52R7t5

**Comment by vuolter** [comment]
Checking...

**Comment by vuolter** [comment]
Surely a permission issue. Investigating...

**Comment by vuolter** [comment]
Please check your value in "webui" -> "config" -> "permission" -> "group".

**Comment by Mister-XY** [comment]
Oh shit, you are right

**Comment by vuolter** [comment]
Okay.
