### ISSUE TITLE
New ExternalScripts plugin errors

### ISSUE THREAD

**Issue by youlJunior** [pyload/pyload#2251]
I had few problems with the new ExternalScripts Plugin : 

##### Problem 1 : Scripts never executed
In plugins/hooks/ExternalScripts.py, the function which call scripts was defined like that : 
```python
def call_script(self, folder, *args, **kwargs):
        scripts = self.scripts.get(folder)

        if not scripts:
            self.log_debug("No script found under folder `%s`" % folder)
            return

        if folder not in scripts:
            self.log_debug("Folder `%s` not found" % folder)
            return
```
The check "if folder not in scripts" is always true, because the var scripts contains the list of scripts in the folder, not the list of folders...
I rewrote the function so the two checks are good : 
```python
def call_script(self, folder, *args, **kwargs):
        
		if folder not in self.scripts:
            self.log_debug("Folder `%s` not found" % folder)
            return
		
		scripts = self.scripts.get(folder)

        if not scripts:
            self.log_debug("No script found under folder `%s`" % folder)
            return
```

##### Problem 2 : Error with args var between call_script and call_cmd
In plugins/hooks/ExternalScripts.py, in call_script : 
```python
def call_script(self, folder, *args, **kwargs):
		...
		p = self.call_cmd(file, args)
```
The call_script function receive a list of arg (*args), and it wraps it in a tuple ( ("arg1","arg2") ) 
But the call_cmd expect a list of args in input and not a tuple.
So you have to unpack the tuple (with a *) when you call that function :
```python
def call_script(self, folder, *args, **kwargs):
		...
		p = self.call_cmd(file, *args)
```

##### Problem 3 : Error with args var in call_cmd
In plugins/hooks/ExternalScripts.py, in call_cmd : 
```python
def call_cmd(self, command, *args, **kwargs):

        call = [command] + args
        self.log_debug("EXECUTE " + " ".join(call))

        call = map(encode, call)
        p = subprocess.Popen(call, bufsize=-1)  #@NOTE: output goes to pyload
```
* You cannot concat list and tuple, so you have to convert tuple to list
* The join fucntion expect encoded strings, so you have to encode (with the encode fucntion in map) before calling join in debug log
```python
def call_cmd(self, command, *args, **kwargs):

        call = [command] + list(args)
		call = map(encode, call)
		
        self.log_debug("EXECUTE " + " ".join(call))
        
        p = subprocess.Popen(call, bufsize=-1)  #@NOTE: output goes to pyload
```

##### Problem 4 : Spamming
In plugins/hooks/ExternalScripts.py, in periodical_task, it logs every 60 seconds the scripts that were found in folders
```python
self.log_info(_("Activated scripts in folder `%s`: %s")
```
I changed info to debug to avoid spamming
```python
self.log_debug(_("Activated scripts in folder `%s`: %s")
```

**Comment by youlJunior** [comment]
Thank you @GammaC0de

**Comment by GammaC0de** [comment]
:+1:
