### ISSUE TITLE
Premium.to don´t work

### ISSUE THREAD

**Issue by SchokoKlaus** [pyload/pyload#2255]
Premium.to Account don´t work.
Download ask for Captcha.

LOG

600 31.12.2015 13:34:33 INFO    starte pyLoad 0.4.9
601 31.12.2015 13:34:33 INFO    Benutze Home-Verzeichnis: /i-data/698199f5/admin/zy-pkgs/pyLoad/etc/pyload
602 31.12.2015 13:34:33 DEBUG   Remote activated: True
603 31.12.2015 13:34:36 DEBUG   created index of plugins
604 31.12.2015 13:34:36 DEBUG   HOOK ExternalScripts: Deprecated method `event_list`, use `event_map` instead
605 31.12.2015 13:34:36 INFO    Aktivierte Plugins: ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UserAgentSwitcher
606 31.12.2015 13:34:36 INFO    Deaktivierte Plugins: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterComHook, MultiHome, RestartFailed, SkipRev, UpdateManager, WindowsPhoneNotify, XMPPInterface
607 31.12.2015 13:34:36 INFO    Downloadzeit: True
608 31.12.2015 13:34:36 INFO    Starte ThriftBackend: 0.0.0.0:7227
609 31.12.2015 13:34:37 INFO    Starting threaded webserver: 0.0.0.0:7272
610 31.12.2015 13:34:37 INFO    Free space: 878.02 GiB
611 31.12.2015 13:34:37 INFO    Activating Accounts...
612 31.12.2015 13:34:37 INFO    ACCOUNT PremiumTo: Login user `XXX`...
613 31.12.2015 13:34:37 INFO    ACCOUNT PremiumTo: Parsing account info for user `XXX`...
614 31.12.2015 13:34:37 DEBUG   ACCOUNT PremiumTo: Account info for user `XXX`: {'login': {'timestamp': 1451568877.4625239, 'password': '*********_', 'valid': True}, 'data': {'premium': None, 'trafficleft': None, 'options': {}, 'maxtraffic': None, 'validuntil': None, 'login': 'XXX', 'password': '**_*******', 'type': 'PremiumTo', 'valid': True}}
615 31.12.2015 13:34:37 INFO    Activating Plugins...
616 31.12.2015 13:34:37 DEBUG   HOOK ExtractArchive: Found UnRar 4.00 | Found SevenZip 9.20 | Found UnZip 2.6.2
617 31.12.2015 13:34:37 INFO    pyLoad is up and running 
618 31.12.2015 13:37:53 INFO    Download starts: XXX.part1.rar
619 31.12.2015 13:37:53 DEBUG   HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
620 31.12.2015 13:37:53 DEBUG   HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
621 31.12.2015 13:37:53 DEBUG   HOSTER UploadedTo[2]: PROCESS URL http://uploaded.net/file/XXX | PLUGIN VERSION 0.97
622 31.12.2015 13:37:53 INFO    HOSTER UploadedTo[2]: Updating file info...
623 31.12.2015 13:37:54 DEBUG   HOSTER UploadedTo[2]: File info: {'status': 2, 'url': u'http://uploaded.net/file/XXX', 'size': 367001600.0, 'name': 'XXX.part1.rar', 'pattern': {'ID': u'x2sm3sou'}}
624 31.12.2015 13:37:54 DEBUG   HOSTER UploadedTo[2]: Previous file info: {}
625 31.12.2015 13:37:54 INFO    HOSTER UploadedTo[2]: File name: XXX.part1.rar
626 31.12.2015 13:37:54 INFO    HOSTER UploadedTo[2]: File size: 367001600 bytes
627 31.12.2015 13:37:54 INFO    HOSTER UploadedTo[2]: File status: online
628 31.12.2015 13:37:54 DEBUG   HOSTER UploadedTo[2]: LOAD URL http://uploaded.net/file/XXX | decode=True | cookies=True | get={} | req=None | _[1]=['decode=True', 'cookies=True', 'get={}', 'req=None'] | multipart=False | post={} | ref=False | just_header=False
629 31.12.2015 13:37:54 INFO    HOSTER UploadedTo[2]: Processing as free download...
630 31.12.2015 13:37:54 DEBUG   HOSTER UploadedTo[2]: LOAD URL http://uploaded.net/language/en | decode=True | cookies=True | get={} | req=None | _[1]=['decode=True', 'cookies=True', 'get={}', 'req=None'] | multipart=False | post={} | ref=True | just_header=True
631 31.12.2015 13:37:54 DEBUG   HOSTER UploadedTo[2]: LOAD URL http://uploaded.net/js/download.js | decode=True | cookies=True | get={} | req=None | _[1]=['decode=True', 'cookies=True', 'get={}', 'req=None'] | multipart=False | post={} | ref=True | just_header=False
632 31.12.2015 13:37:54 DEBUG   CAPTCHA UploadedTo[2]: ReCaptcha | Key: XXX

**Comment by chodid** [comment]
Is there any way to manually update which hosters should be tried with specific Multihoster accounts?

**Comment by GammaC0de** [comment]
@chodid , multi account status is currently broken, fix coming soon - see #2121

**Comment by chodid** [comment]
Perfect, then I shall wait patiently - seems like a solution for the problem is very near.

**Comment by GammaC0de** [comment]
@chodid :+1: 
P.S. Sorry for making you jump from one post to another.. 0_0

**Comment by chodid** [comment]
@GammaC0de 
Its aight, as long as I end up finding answers I'm happy! Thanks for your awesome help!

**Comment by m33cr0b** [comment]
For anyone who is looking for a pyload version in which the plugins PremiumTo and ExtractArchive are still working, get this older version: https://github.com/pyload/pyload/archive/9d3d47df1935641fe2bb8771c948b11656133d7c.zip
Disable update until pyload is great again ;)

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/aff856b6891fb7f9831453e32ff53a374f601fbd
