### ISSUE TITLE
updatemanager "unable to connect to server"

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#2257]
```
02.01.2016 16:53:43 WARNING   ADDON UpdateManager: Unable to connect to the server to retrieve updates
```
and yes. i replaced the whole userplugins folder with the latest

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/issues/2241

**Comment by Gutz-Pilz** [comment]
i did the stuff @GammaC0de is suggesting in this thread. still the same error!

**Comment by vuolter** [comment]
Because the updatemanager is currenlty down...
