### ISSUE TITLE
Error on checksum

### ISSUE THREAD

**Issue by Gronkdalonka** [pyload/pyload#2258]
All downloaded files throw following error:

'dict' object has no attribute 'lower' 

and in logs:

Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 190, in run
    self.m.core.hookManager.downloadFinished(pyfile)
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/HookManager.py", line 225, in downloadFinished
    plugin.downloadFinished(pyfile)
  File "/usr/share/pyload/module/plugins/internal/Addon.py", line 189, in downloadFinished
    return self.download_finished(pyfile)
  File "/usr/share/pyload/module/plugins/hooks/Checksum.py", line 137, in download_finished
    if checksum == data[key].lower():
AttributeError: 'dict' object has no attribute 'lower'

Seems like there is no checksum in the "data" dict (data['hash' is there but an empty dict)

As a workaround i changed line 134 of Checksum.py to

" if key in data and data[key]:"

which at least allows "normal" downloades, even if it skipps the whole checksum stuff

**Comment by Gronkdalonka** [comment]
Seems like a problem with Uploaded.to only, ShareOnline.biz is unaffected and generates a checksum

**Comment by vuolter** [comment]
New version coming soon ;)

**Comment by Gronkdalonka** [comment]
Nice :)

**Comment by manacker** [comment]
Any news here? Uploaded.to still doesn't work right and marks all downloaded files as failed.

**Comment by backslash69** [comment]
Any News ?

**Comment by randoom42** [comment]
FilefactoryCom is also affected by this bug.

**Comment by GammaC0de** [comment]
You can disable `checksum` plugin for meanwhile
