### ISSUE TITLE
Absolute paths dont't work for download folder

### ISSUE THREAD

**Issue by zeroflow** [pyload/pyload#2261]
The latest version of pyload seems to have a bug with absolute paths.

Download dir in settings: /mnt/NAS/Downloads/incomplete

Logging entry (only described)
"Cannot find /home/pyload/.pyload/home/pyload/.pyload/mnt/NAS/Downloads/incomplete/..."

My fix in module/plugins/internal/Hoster.py:
Line 248 replace safejoin(...) with os.path.join(...)
Line 249 do the same

From a short debugging session, it looks like there is a bug with safejoin that changes absolute paths to relative (missing / infront or so?)

Updates and/or a pull request will follow once i find more

Update
---------

Log messages comparing os.path.join and safejoin
```
03.01.2016 23:54:41	DEBUG	HOSTER UploadedTo[20]: DOWNLOAD URL http://<<URL>> | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
03.01.2016 23:54:41	DEBUG	HOSTER UploadedTo[20]: Line248-OS join:/mnt/NAS/Downloads/incomplete/<<NAME>>
03.01.2016 23:54:41	DEBUG	HOSTER UploadedTo[20]: Line248-Safejoin:/home/pyload/.pyload/mnt/NAS/Downloads/incomplete/<<NAME>>
03.01.2016 23:54:41	DEBUG	HOSTER UploadedTo[20]: Line249-OS join:/mnt/NAS/Downloads/incomplete/<<NAME>>
03.01.2016 23:54:41	DEBUG	HOSTER UploadedTo[20]: Line249-Safejoin:/home/pyload/.pyload/mnt/NAS/Downloads/incomplete/<<NAME>>
```

So it looks like safejoin(...) is the culprit here

**Comment by DomiakaSnakez** [comment]
I've got the same problem.
I fixed it:
Download the stable package from https://github.com/pyload/pyload/archive/stable.zip
Extract the .zip and Copy all the subfolders in <stable.zip>/module/plugins to your userplugins directory.

Have a nice day :)

**Comment by GammaC0de** [comment]
#2241
