### ISSUE TITLE
Mediafire problem

### ISSUE THREAD

**Issue by willoz88** [pyload/pyload#2262]
here's the log:
00:20	INFO	Download starts: http://www.mediafire.com/download/yg5hwp411bc1psg/%23E__U_70_5_6_AND%23.part1.rar
35	04.01.2016 21:00:21	WARNING	HOSTER MediafireCom[1]: Plugin may be unstable
36	04.01.2016 21:00:21	INFO	HOSTER MediafireCom[1]: Grabbing link info...
37	04.01.2016 21:00:24	INFO	HOSTER MediafireCom[1]: Link name: #E__U_70_5_6_AND#.part1.rar
38	04.01.2016 21:00:24	INFO	HOSTER MediafireCom[1]: Link size: N/D
39	04.01.2016 21:00:24	INFO	HOSTER MediafireCom[1]: Link status: online
40	04.01.2016 21:00:24	INFO	HOSTER MediafireCom[1]: Processing url: http://www.mediafire.com/download/yg5hwp411bc1psg/%23E__U_70_5_6_AND%23.part1.rar
41	04.01.2016 21:00:24	INFO	HOSTER MediafireCom[1]: Looking for direct download link...
42	04.01.2016 21:00:41	INFO	HOSTER MediafireCom[1]: Direct download link not found
43	04.01.2016 21:01:00	INFO	HOSTER MediafireCom[1]: Checking for link errors...
44	04.01.2016 21:01:00	INFO	HOSTER MediafireCom[1]: No errors found
45	04.01.2016 21:01:00	INFO	HOSTER MediafireCom[1]: Processing as free download...
46	04.01.2016 21:01:21	INFO	CAPTCHA MediafireCom[1]: SolveMedia | Using OCR to decrypt captcha...
47	04.01.2016 21:01:21	WARNING	CAPTCHA MediafireCom[1]: SolveMedia | No OCR result
48	04.01.2016 21:02:10	INFO	CAPTCHA MediafireCom[1]: SolveMedia | Captcha result: `bizarro jerry`
49	04.01.2016 21:02:10	WARNING	CAPTCHA MediafireCom[1]: SolveMedia | Error removing `/opt/share/pyload_config/tmp/captcha_image_MediafireCom_68112.gif` | global name 'remove' is not defined
50	04.01.2016 21:02:28	WARNING	Download failed: #E__U_70_5_6_AND#.part1.rar | Parse error: Free download link not found | Plugin may be out of date
51	04.01.2016 21:02:28	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: #E__U_70_5_6_AND#.part1.rar (pid:1)
52	04.01.2016 21:02:28	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
@willoz88 Try updating your `userplugins` and then retry and report here

**Comment by willoz88** [comment]
@GammaC0de Already updated my userplugins but result is the same
112	06.01.2016 16:38:40	INFO	Download starts: #E__U_70_5_6_AND#.part1.rar
113	06.01.2016 16:38:41	WARNING	HOSTER MediafireCom[2]: Plugin may be unstable
114	06.01.2016 16:38:41	INFO	HOSTER MediafireCom[2]: Grabbing link info...
115	06.01.2016 16:38:44	INFO	HOSTER MediafireCom[2]: Link name: #E__U_70_5_6_AND#.part1.rar
116	06.01.2016 16:38:44	INFO	HOSTER MediafireCom[2]: Link size: 550.00 MiB (576716800 bytes)
117	06.01.2016 16:38:44	INFO	HOSTER MediafireCom[2]: Link status: online
118	06.01.2016 16:38:44	INFO	HOSTER MediafireCom[2]: Processing url: http://www.mediafire.com/download/yg5hwp411bc1psg/%23E__U_70_5_6_AND%23.part1.rar
119	06.01.2016 16:38:44	INFO	HOSTER MediafireCom[2]: Looking for direct download link...
120	06.01.2016 16:39:00	INFO	HOSTER MediafireCom[2]: Direct download link not found
121	06.01.2016 16:39:05	INFO	HOSTER MediafireCom[2]: Checking for link errors...
122	06.01.2016 16:39:05	INFO	HOSTER MediafireCom[2]: No errors found
123	06.01.2016 16:39:05	INFO	HOSTER MediafireCom[2]: Processing as free download...
124	06.01.2016 16:39:12	INFO	CAPTCHA MediafireCom[2]: SolveMedia | Using OCR to decrypt captcha...
125	06.01.2016 16:39:12	WARNING	CAPTCHA MediafireCom[2]: SolveMedia | No OCR result
126	06.01.2016 16:39:26	INFO	CAPTCHA MediafireCom[2]: SolveMedia | Captcha result: `if it fits`
127	06.01.2016 16:39:26	INFO	CAPTCHA MediafireCom[2]: SolveMedia | Path deleted: /opt/share/pyload_config/tmp/captcha_image_MediafireCom_75208.gif
128	06.01.2016 16:39:31	WARNING	Download failed: #E__U_70_5_6_AND#.part1.rar | Parse error: Free download link not found | Plugin may be out of date
129	06.01.2016 16:39:31	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: #E__U_70_5_6_AND#.part1.rar (pid:2)
130	06.01.2016 16:39:31	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
Well this site uses ReCaptcha v2 which is not supported currently

**Comment by willoz88** [comment]
Captcha may be by-passed using free accounts, why is not possible to enter account login for Mediafire?

**Comment by GammaC0de** [comment]
I am sorry, I have created a free account but mediafire still asks for captch

**Comment by willoz88** [comment]
Yes, you're right, my mistake sorry

**Comment by GammaC0de** [comment]
Now working
