### ISSUE TITLE
[ExternalScripts] Too much double quotes when calling an external script

### ISSUE THREAD

**Issue by youlJunior** [pyload/pyload#2264]
The function call_cmd is defined as follow :

```python
def call_cmd(self, command, *args, **kwargs):
        _args = ['"' + _arg + '"' if ' ' in encode(_arg) else _arg for _arg in args]

        call = map(encode, [command] + _args)

        self.log_debug("EXECUTE " + " ".join(call))

        p = subprocess.Popen(call, bufsize=-1)  #@NOTE: output goes to pyload

        return p
```
But the first line adds unnecessary quotes.
Ex :
```
args=['arg1', 'argument two']
_args=['arg1', '"argument two"']
```
So when the shell script is called, the double quotes are in the argument string.
Ex :
```
python
Python 2.7.3 (default, Mar 23 2014, 01:44:56) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> p = subprocess.Popen(['echo', 'arg1'])
>>> arg1

>>> p = subprocess.Popen(['echo', '"arg 1"'])
>>> "arg 1"
```

**Comment by GammaC0de** [comment]
@youlJunior How would you send a parameter that contains a space in it?

**Comment by youlJunior** [comment]
There is examples in the python doc :
https://docs.python.org/2/library/subprocess.html#subprocess.Popen
The Popen command add quotes around parameters if they contain spaces, because each element in the array is a param.

Anyway, there wasn't double quotes before, and i was able to get the downloaded file name in param $2 in a shell script, even if the name was containing spaces.
Now the param contains double quotes too...

**Comment by GammaC0de** [comment]
:+1:
