### ISSUE TITLE
Serienjunkies.org changed their Captchas / Plugin (SerienjunkiesOrg.py) not working anymore (Max retries reached)

### ISSUE THREAD

**Issue by zlep** [pyload/pyload#2266]
I know there's unfortunately (and inexplicably) no support for this Plugin (SerienjunkiesOrg.py) anymore but maybe anybody could help anyway? Thanks
Link to the announcement: http://board.serienjunkies.org/index.php?page=Thread&postID=550381#post550381

**Comment by j4m** [comment]
Unfortunately I have to confirm that Serienjunkies now uses ReCaptcha :/

**Comment by Speil** [comment]
And ReCaptcha isnt possible in pyload?

**Comment by GammaC0de** [comment]
ReCaptcha v1 possible . ReCaptcha v2 not supported and doubt if it will be.

Anyway since SerienjunkiesOrg is a warez site it is not supported here.
You should open an issued at the developer repository at https://github.com/Gutz-Pilz/pyLoad-stuff/issues
