### ISSUE TITLE
1fichier issues

### ISSUE THREAD

**Issue by aronze06** [pyload/pyload#2267]
Hello everybody !

Since few days, I have an issue when I try do download a file on 1fichier. Before to post my message, I put the last pyload version stable on my NAS but it doesn't solve my problem :(

below the log of pyload:
34    06.01.2016 13:25:25	INFO	Added package Le pont des espions containing 1 links
35	06.01.2016 13:25:27	INFO	Download starts: https://1fichier.com/?c758o5cfxw
36	06.01.2016 13:25:28	WARNING	HOSTER OneFichierCom[1]: Plugin may be unstable
37	06.01.2016 13:25:28	INFO	HOSTER OneFichierCom[1]: Grabbing link info...
38	06.01.2016 13:25:29	INFO	Download starts: https://1fichier.com/?c758o5cfxw
39	06.01.2016 13:25:30	INFO	HOSTER OneFichierCom[1]: Link name: ?c758o5cfxw
40	06.01.2016 13:25:30	INFO	HOSTER OneFichierCom[1]: Link size: N/D
41	06.01.2016 13:25:30	INFO	HOSTER OneFichierCom[1]: Link status: en file d'attente
42	06.01.2016 13:25:30	INFO	HOSTER OneFichierCom[1]: Processing url: https://1fichier.com/?c758o5cfxw
43	06.01.2016 13:25:30	INFO	HOSTER OneFichierCom[1]: Looking for direct download link...
44	06.01.2016 13:25:30	WARNING	HOSTER OneFichierCom[1]: Plugin may be unstable
45	06.01.2016 13:25:30	INFO	HOSTER OneFichierCom[1]: Grabbing link info...
46	06.01.2016 13:25:30	WARNING	Download failed: ?c758o5cfxw | HTTPRequest instance has no attribute 'cj'
47	06.01.2016 13:25:30	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: ?c758o5cfxw (pid:1)
48	06.01.2016 13:25:30	INFO	ADDON UnSkipOnFail: No duplicates found
49	06.01.2016 13:25:31	ERROR	Reconnect Failed: plugin
50	06.01.2016 13:25:31	WARNING	Download failed: ?c758o5cfxw | 'NoneType' object has no attribute 'id'
51	06.01.2016 13:25:31	ERROR	Error executing hooks: plugin

---

Thanks a lot for your help !!!

Alexis

**Comment by GammaC0de** [comment]
same issue as https://github.com/pyload/pyload/issues/2265
