### ISSUE TITLE
add support for NoCaptcha ReCaptcha to pyLoad

### ISSUE THREAD

**Issue by b2un0** [pyload/pyload#2268]
feature request:

add support for NoCaptcha ReCaptcha to pyLoad (also KeyCaptcha).

**Comment by b2un0** [comment]
just a idea: has ReCaptcha v2 a fallback solution for javascript disabled or mobile browser?

**Comment by kasperj** [comment]
Maybe this helps http://www.deathbycaptcha.com/user/api/newrecaptcha

**Comment by GammaC0de** [comment]
@kasperj Redirects to: http://www.deathbycaptcha.com/user/need-subscription
```
Sorry, this page is available to customers only.
Please register, and consider ordering some captchas
```

**Comment by kasperj** [comment]
There's an API to get the coordinates of the images that need to be clicked

[DeathByCaptcha API Clients.pdf](https://github.com/pyload/pyload/files/83372/DeathByCaptcha.API.Clients.pdf)

**Comment by GammaC0de** [comment]
This is also interesting: https://github.com/neuroradiology/InsideReCaptcha

**Comment by wastez** [comment]
jdownloader has already solution also for headless user.
Does anybody has a idea how to implement it on pyload?

**Comment by GammaC0de** [comment]
@wastez are you sure?
Please provide more info

**Comment by wastez** [comment]
Yes tried it with my jdownloader an it istworking. 
In the Moment they have a bug in it that not more then 3 pictures can be jused, but they implemented it today so it will be fixed soon.

**Comment by GammaC0de** [comment]
So how exactly the captcha was solved then?

**Comment by wastez** [comment]
Thats how they solved it:
![bildschirmfoto 2016-01-13 um 00 01 07](https://cloud.githubusercontent.com/assets/2268597/12279700/02340d24-b989-11e5-8842-7fe97d35b5e9.png)

**Comment by GammaC0de** [comment]
So, it has opened the browser for it, no?

**Comment by wastez** [comment]
You don´t understand.
It´s working over their webinterface headless.

**Comment by wastez** [comment]
so the same way like pyload. (ok the webif is online)

**Comment by GammaC0de** [comment]
Ok, so its just a matter of loading https://www.google.com/recaptcha/api/fallback?k=<SITE_KEY> with "https://www.google.com/recaptcha/api2/demo" as referrer to be able to bypass the "Are you human" \*BS\*.

"fbc-imageselect-message-text" is the question text
"fbc-imageselect-payload" is probably the image URL 
See the `load` function in `RecaptchaV2Challenge.java` below

maybe now @zapp-brannigan can now step  further...

[RecaptchaV2Challenge.zip](https://github.com/pyload/pyload/files/88193/RecaptchaV2Challenge.zip)

**Comment by zapp-brannigan** [comment]
I'll take a look. Maybe we can borrow some code again ;)

Am 13. Januar 2016 01:20:26 MEZ, schrieb GammaC0de <notifications@github.com>:
>Ok, so its just a matter of loading
>https://www.google.com/recaptcha/api/fallback?k=<SITE_KEY> with
>"https://www.google.com/recaptcha/api2/demo" as referrer to be able to
>bypass the "Are you human" \*BS\*.
>
>"fbc-imageselect-message-text" is the question text
>"fbc-imageselect-payload" is probably the image URL 
>See the `load` function in `RecaptchaV2Challenge.java` below
>
>maybe now @zapp-brannigan can now step  further...
>
>[RecaptchaV2Challenge.zip](https://github.com/pyload/pyload/files/88193/RecaptchaV2Challenge.zip)
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pyload/pyload/issues/2268#issuecomment-171108373

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by kasperj** [comment]
Any progress on this?

**Comment by zapp-brannigan** [comment]
I failed :(

Am 25. Januar 2016 00:51:11 MEZ, schrieb Jan-Henrik Kasper <notifications@github.com>:
>Any progress on this?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pyload/pyload/issues/2268#issuecomment-174354185

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by justroot1337** [comment]
so no solution?
Please fix this. without this plugin pyload is useless for me. :(

**Comment by wastez** [comment]
Same to me.
This was the rejecting reason to swap to jdownloader in headless mode.
It´s a pitty, i really liked pyload.

**Comment by feuerwasser85** [comment]
even if i already using jdownloader, i wait patiently for a Recaptcha solution for pyload, after a fiew years, i dont wanna miss pyload, its the better solution for a NAS, AND it can be automated and extended, not like jdownloader.
I hope you can find a solution for implementing Recaptcha, i know this is hard, but keep trying!

**Comment by Pulper** [comment]
Looking forward to it, too

**Comment by wastez** [comment]
It would be really great if somebody will find a solution, i hope so. 
But personally i guess it wouldn't happen.

**Comment by GammaC0de** [comment]
If it works with jdownloader, it can work with pyload too, it just a matter of time and will
If someone serious can pick up the glove, it would be great.

**Comment by vuolter** [comment]
@wastez I think I can "port" the jd solution on pyload, although I'm not so happy to "copy" it. :S

**Comment by Pulper** [comment]
But it would be great, no matter of copy/paste :-P

**Comment by feuerwasser85** [comment]
you can't copy it anyway, jd is written in java, so the pyload solution can't be a copy.
Just for you're conscience :-)

**Comment by vuolter** [comment]
@feuerwasser85 I know it's java... I mean "copy" the idea (and obviously the correct http request sequence to fool the service). :p

**Comment by wastez** [comment]
@ vuolter 
It would be realy great if you could implement this solution.

**Comment by Arno-Nymous** [comment]
@vuolter You're right, if it's made by man it can be broken by man :smirk:

My general idea at first was to emulate a full JS environment in order to utilize it for generating the ReCaptcha IFrame. Basicaly, the new captchas are generated by a chain of obfuscated javascripts. If one could just let them run through a JS parser (I'm talking of a full fledged one, with all the globals like `console`, `document` and all the stuff a real browser offers you), one could build up the DOM through pyLoad and just scrape the necessary parameters. Other than that it could be pretty tricky to parse the right data. I just haven't found a way yet to tell my JS installation to behave like a real browser. As of now, as soon a

**Comment by GammaC0de** [comment]
@Arno-Nymous There is no need (currently, it might change in the future) for a JS engine: if you disable JS in your browser (`javascript.enabled` @ `about:config` in firefox), you would get a javascript-less version..

As for a full JS and DOM scapper, there are projects like `PhantomJS` but those are overkill for NAS environment and portability is questionable.

**Comment by Arno-Nymous** [comment]
Guys,

I think I made a nice progress on our "little problem" here :blush: (at least I hope that it's what the folks want)
I pasted a very quick and dirty coded draft of a [dummy crypter on Gist](https://gist.github.com/Arno-Nymous/5e7aa603cc281dbe2759). It is able to scrape the challenge image from the recaptcha container and show it to the user for solving via the web interface. Just put the file inside your crypter directory and see how far it takes you :smile: Would be great if some of you would check it with their favorite website and report back.

It's not an early version without a reason, so at the moment there are also a few caveats (though none of them obstructive):
- The plugins output only happens on standard ouput, so you would have to run pyLoad without the
`--daemon` option in order to see what it tells you (not that big of a deal for testing I think)
- As of now I don't know if it's possible to write some custom text into pyLoads captcha solving pop-up window, like "Enter the numbers of all pictures that match the challenge" (I must admit: I didn't look around in the code too much on that :sweat_smile:). So you have to watch the log when it says something like "Select all images with street signs". Then you have to enter the indizes of the matching images according to their index (see below). So, if the matching images would be in the upper left, middle and lower right you would type in `048` for solving the captcha.
- Currently the captcha challenges are presented in english, but it shouldn't be any problem to feed Google some language code to show the localized texts

||||
---|----|---
0 | 1 | 2
3 | 4 | 5
6 | 7 | 8

If this sounds like a good starting point for you out there, one could think about some further steps, like
- Nicely integrate the code into the captcha solving mechanism
- Maybe extend the pop-up window in a way so that plugins can pass it some custom text
- Apply some rudimentary overlays to the image (I'm not that deep into headless image processing tools) to show the index numbers of the image tiles for better user experience (similar to the image that the jDownloader plugin shows)
- Wrap everything up and send it to e.g. 9kw to let some nice folks solve our captchas while take our nighty-nighty from hard coding :stuck_out_tongue_winking_eye:

One more thing to mention: it seems normal behaviour for the nocaptcha recaptchas to prompt you for 2 or even 3 challenges. I guess it's just another way of Google to penetrate us some more. There's also one comment in the Java file which @GammaC0de shared above about this behaviour.
Also special thanks to @GammaC0de who pointed me into the direction to just turn of JavaScript in my browser and do my tests that way. From that point everything else actually was a no-brainer :sweat_smile:

Hope I don't sound to euphoric but at least my code worked for the website I intended it for. As I said: try out and report back :+1:

Cheers!

**Comment by b2un0** [comment]
we also need this to add `filecrypt.cc` cryper support.

**Comment by Arno-Nymous** [comment]
It shouldn't be a big deal to implement other crypters in the future that utilize nocaptchas since creating new crypter plugins should be the same job as it was with the old captchas.
When my code gets further refined in terms of better readability and code style plus maybe will be integrated into the existing ReCaptcha.py (I use the requests and BeautifulSoup libraries a lot in my projects because they're fast and pretty comfy imho, but I guess one would've to map them to pyLoad's built-in utilities), then crafting new crypter plugins should be easy peasy.

**Comment by Pa1nstar** [comment]
As i mentioned already in [Serienjunkies.org ReCaptcha #7](https://github.com/Gutz-Pilz/pyLoad-stuff/issues/77#issuecomment-185732734) if you need tester, here i am. :)

**Comment by Arno-Nymous** [comment]
I opened a pull request on this topic. Someone please review it for the sake of some of us :smiley:

**Comment by Arno-Nymous** [comment]
Forgot to mention the new captcha image will like this when presented to the user:

![captcha_image](https://cloud.githubusercontent.com/assets/15018472/13286821/1202dd6a-db04-11e5-82bf-09723c3ae495.jpg)

**Comment by GammaC0de** [comment]
Everyone see https://github.com/pyload/pyload/commit/93c0627b1d05212cc4f08d4518309f977dfdff90

Feedback wanted!

**Comment by feuerwasser85** [comment]
```INFO	Decrypting starts: so_tvs-ahs-dd51-ded-dl-18p-ithd-avc-512.html
DEBUG	CONTAINER SerienjunkiesOrg[124]: Plugin version: 0.40
DEBUG	CONTAINER SerienjunkiesOrg[124]: Plugin status: stable
DEBUG	CONTAINER SerienjunkiesOrg[124]: Config option `use_premium` not found, use default `True`
INFO	CONTAINER SerienjunkiesOrg[124]: Grabbing link info...
DEBUG	CONTAINER SerienjunkiesOrg[124]: Link info: {'status': 7, 'hash': {}, 'name': 'so_tvs-ahs-dd51-ded-dl-18p-ithd-avc-512.html', 'url': u'http://download.serienjunkies.org/f-6432a8e234c99189/so_tvs-ahs-dd51-ded-dl-18p-ithd-avc-512.html', 'pattern': {}, 'size': 0}
DEBUG	CONTAINER SerienjunkiesOrg[124]: Previous link info: {'status': 7, 'hash': {}, 'name': 'so_tvs-ahs-dd51-ded-dl-18p-ithd-avc-512.html', 'url': u'http://download.serienjunkies.org/f-6432a8e234c99189/so_tvs-ahs-dd51-ded-dl-18p-ithd-avc-512.html', 'pattern': {}, 'size': 0}
INFO	CONTAINER SerienjunkiesOrg[124]: Link name: so_tvs-ahs-dd51-ded-dl-18p-ithd-avc-512.html
INFO	CONTAINER SerienjunkiesOrg[124]: Link size: N/D
INFO	CONTAINER SerienjunkiesOrg[124]: Link status: starte
INFO	CONTAINER SerienjunkiesOrg[124]: Processing url: http://download.serienjunkies.org/f-6432a8e234c99189/so_tvs-ahs-dd51-ded-dl-18p-ithd-avc-512.html
ERROR	Decrypting failed: so_tvs-ahs-dd51-ded-dl-18p-ithd-avc-512.html | Max retries reached```

**Comment by justroot1337** [comment]
Same problem here :(

**Comment by vuolter** [comment]
@feuerwasser85 @justroot1337 SerienjunkiesOrg is not an official plugin, I'm sure is outdated and has became incompatible with latest upstream changes.

**Comment by feuerwasser85** [comment]
@vuoter sorry, my mistake. I wanted to test a site that only uses googles ReCaptchas, do you have an other site to test? I would like to help.

**Comment by mcmaxl** [comment]
But still a lot of Pyload users love serienjunkies. Maybe someone could update it, unofficial or not

**Comment by wastez** [comment]
Arno-Nymous wrote a RecaptchaV2 Solution and a new Serienjunkies crypter for it. So everything is working if it is implemented.

**Comment by GammaC0de** [comment]
@wastez https://github.com/pyload/pyload/commit/93c0627b1d05212cc4f08d4518309f977dfdff90 is based of @Arno-Nymous's work.

Maybe there is a bug in my code, maybe @Arno-Nymous has to update his Serienjunkies crypter to work with https://github.com/pyload/pyload/commit/93c0627b1d05212cc4f08d4518309f977dfdff90, I cannot tell.
Please ask him to check.

**Comment by wastez** [comment]
Tried his crypter with your code, but it isn´t working.
For his captcha code it is working.

**Comment by GammaC0de** [comment]
@wastez Try changing [ReCaptcha.py#L211](https://github.com/pyload/pyload/blob/stable/module/plugins/captcha/ReCaptcha.py#L211)
form `html = self.pyfile.plugin.load(fallback_url)`
to `html = self.pyfile.plugin.load(fallback_url, ref=self.pyfile.url)`

See if that helps

**Comment by wastez** [comment]
@GammaC0de 
This change fixed it!!!

**Comment by GammaC0de** [comment]
Great :+1: :+1:

**Comment by wastez** [comment]
Ok... The captcha appears and i´m able to solve it but then the package isn´t added.

**Comment by GammaC0de** [comment]
@wastez I think this is related to Serienjunkies..

**Comment by wastez** [comment]
But it´s working on Arno-Nymous Branch.

Here is the log:
`27.02.2016 17:32:34 INFO      Added package download.serienjunkies.org containing 1 links
27.02.2016 17:32:34 INFO      Decrypting starts: http://download.serienjunkies.org/f-425d7ac706f28d52/so_tvs-ncis-ded-dl-ithd-x264-1301.html
27.02.2016 17:32:34 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
27.02.2016 17:32:34 DEBUG     CRYPTER SerienJunkies[1]: Plugin version: 0.18
27.02.2016 17:32:34 DEBUG     CRYPTER SerienJunkies[1]: Plugin status: testing
27.02.2016 17:32:34 WARNING   CRYPTER SerienJunkies[1]: Plugin may be unstable
27.02.2016 17:32:34 DEBUG     CRYPTER SerienJunkies[1]: Config option `use_premium` not found, use default `True`
27.02.2016 17:32:34 INFO      CRYPTER SerienJunkies[1]: Grabbing link info...
27.02.2016 17:32:34 DEBUG     CRYPTER SerienJunkies[1]: Link info: {'status': 7, 'hash': {}, 'name': 'so_tvs-ncis-ded-dl-ithd-x264-1301.html', 'url': u'http://download.serienjunkies.org/f-425d7ac706f28d52/so_tvs-ncis-ded-dl-ithd-x264-1301.html', 'pattern': {'ID': u'so_tvs-ncis-ded-dl-ithd-x264-1301'}, 'size': 0}
27.02.2016 17:32:34 DEBUG     CRYPTER SerienJunkies[1]: Previous link info: {}
27.02.2016 17:32:34 INFO      CRYPTER SerienJunkies[1]: Link name: so_tvs-ncis-ded-dl-ithd-x264-1301.html
27.02.2016 17:32:34 INFO      CRYPTER SerienJunkies[1]: Link size: N/D
27.02.2016 17:32:34 INFO      CRYPTER SerienJunkies[1]: Link status: starte
27.02.2016 17:32:34 INFO      CRYPTER SerienJunkies[1]: Processing url: http://download.serienjunkies.org/f-425d7ac706f28d52/so_tvs-ncis-ded-dl-ithd-x264-1301.html
27.02.2016 17:32:35 DEBUG     CRYPTER SerienJunkies[1]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6LdmhRQTAAAAAAGfWQLCeCmT6CAVKKxu-TibpZ2h | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=http://download.serienjunkies.org/f-425d7ac706f28d52/so_tvs-ncis-ded-dl-ithd-x264-1301.html | just_header=False
27.02.2016 17:32:35 DEBUG     CRYPTER SerienJunkies[1]: LOAD URL http://www.google.com/recaptcha/api2/payload?c=03AHJ_VuuZazn4SQCzpihGfQxDiEI79So0WipEEMEYOTmKLleSZASV_vQsht-MfMHNVZE3VGLnb8Z72-aWV0SLr0BfjkZNSp5omPDdN_xHQYGUkJzV3xqzpTICM4SqgmfZDA7lzfu2Befrr_LyrG_SG3n2Aj-g5g5EZkE0LjIhoirX1pLaq4_ZWExjeWUCdgamngXOyqfakjG_oWbY7nQVATJh34PDEljkSm6YWlG-KGIBIXNFTFUbAEhzNurc0cN3B6HlnIXmY9W0zQwVgdiILLQGZaLqlVbR_4z3yVuL_9h2LrzYVNLmj6pAqfB11ORxu8cTEfhvmxHZN66MgCqw8wxfKpzo_lF7mbgjoCRLkRi73U-XQjr8eJl97wGkuhXp5mltqAgl684t&k=6LdmhRQTAAAAAAGfWQLCeCmT6CAVKKxu-TibpZ2h | redirect=True | cookies=True | get={} | req=None | decode=False | multipart=False | post={} | ref=http://www.google.com/recaptcha/api/fallback?k=6LdmhRQTAAAAAAGfWQLCeCmT6CAVKKxu-TibpZ2h | just_header=False
27.02.2016 17:32:49 INFO      CAPTCHA SerienJunkies[1]: ReCaptcha | Captcha result: `2579`
27.02.2016 17:32:49 DEBUG     CRYPTER SerienJunkies[1]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6LdmhRQTAAAAAAGfWQLCeCmT6CAVKKxu-TibpZ2h | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post=c=03AHJ_VuuZazn4SQCzpihGfQxDiEI79So0WipEEMEYOTmKLleSZASV_vQsht-MfMHNVZE3VGLnb8Z72-aWV0SLr0BfjkZNSp5omPDdN_xHQYGUkJzV3xqzpTICM4SqgmfZDA7lzfu2Befrr_LyrG_SG3n2Aj-g5g5EZkE0LjIhoirX1pLaq4_ZWExjeWUCdgamngXOyqfakjG_oWbY7nQVATJh34PDEljkSm6YWlG-KGIBIXNFTFUbAEhzNurc0cN3B6HlnIXmY9W0zQwVgdiILLQGZaLqlVbR_4z3yVuL_9h2LrzYVNLmj6pAqfB11ORxu8cTEfhvmxHZN66MgCqw8wxfKpzo_lF7mbgjoCRLkRi73U-XQjr8eJl97wGkuhXp5mltqAgl684t&response=1&response=4&response=6&response=8 | ref=http://www.google.com/recaptcha/api/fallback?k=6LdmhRQTAAAAAAGfWQLCeCmT6CAVKKxu-TibpZ2h | just_header=False
27.02.2016 17:32:50 DEBUG     CRYPTER SerienJunkies[1]: Config option `folder_per_package` not found, use default `Default`
27.02.2016 17:32:50 INFO      CRYPTER SerienJunkies[1]: Create package: download.serienjunkies.org | 0 links
27.02.2016 17:32:50 DEBUG     CRYPTER SerienJunkies[1]: LINKS for package download.serienjunkies.org
27.02.2016 17:32:50 DEBUG     ADDON AppleDeviceNotify: Sending notification...
27.02.2016 17:32:50 DEBUG     ADDON AppleDeviceNotify: event: Package added | msg: download.serienjunkies.org
27.02.2016 17:32:50 DEBUG     ADDON AppleDeviceNotify: LOAD URL http://95.85.62.143/pyControlPush/push.php | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'msg': u'Package added', 'deviceKey': u'ad571b1b65c4bdde957793fc77f8d104e5465ff637ecb97f0b712c70fdfcf53a', 'val': 'download.serienjunkies.org'} | ref=True | just_header=False
27.02.2016 17:32:50 DEBUG     ADDON AppleDeviceNotify: Response:
27.02.2016 17:32:50 DEBUG     ADDON AppleDeviceNotify: LOAD URL http://95.85.62.143/pyControlPush/push.php | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'msg': u'Package added', 'deviceKey': u'91be0fdf282e1ad2a9ebc684e40c7c164ff068cc0ba52deecec283ebb0132ab2', 'val': 'download.serienjunkies.org'} | ref=True | just_header=False
27.02.2016 17:32:50 DEBUG     ADDON AppleDeviceNotify: Response:
27.02.2016 17:32:50 DEBUG     ADDON AppleDeviceNotify: Notification sent
27.02.2016 17:32:50 INFO      Added package download.serienjunkies.org containing 0 links
27.02.2016 17:32:50 INFO      CRYPTER SerienJunkies[1]: Save package `download.serienjunkies.org` to folder:`

**Comment by GammaC0de** [comment]
@wastez Are you referring to this https://github.com/Arno-Nymous/pyload/commit/172ccb809698c0f31cb6825f61d2939c1051f370?

**Comment by wastez** [comment]
Yes exactly.

**Comment by GammaC0de** [comment]
@wastez https://github.com/Arno-Nymous/pyload/commit/172ccb809698c0f31cb6825f61d2939c1051f370 needs correction

The code below works:
```python
import re

from module.plugins.captcha.ReCaptcha import ReCaptcha
from module.plugins.internal.Crypter import Crypter


class SerienJunkies(Crypter):
    __name__    = 'SerienJunkies'
    __status__  = 'testing'
    __type__    = 'crypter'
    __pattern__ = r'http://(www\.)?download\.serienjunkies\.org/.*/(?P<ID>.+)\.html'
    __config__ = [
        ("activated", "bool", "Activated", True)
    ]
    LINK_PATTERN = r'<FORM ACTION="(http://download\.serienjunkies\.org/[^"]+)'

    def decrypt(self, pyfile):
        self.data = self.load(pyfile.url)

        url, inputs = self.parse_html_form('NAME="INPF"')

        self.captcha = ReCaptcha(pyfile)
        response, challenge = self.captcha.challenge()

        inputs['g-recaptcha-response'] = response
        self.data = self.load(pyfile.url, post=inputs)

        links = []

        for _l in re.findall(self.LINK_PATTERN, self.data):
            headers = self.load(_l, just_header=True)
            link = headers.get('location')
            if link:
                links.append(link)

        self.packages = [(pyfile.package().name, links, pyfile.package().folder)]
```

**Comment by Pulper** [comment]
A code which doesn´t need BeautifulSoup4? I want to use it :-D

**Comment by GammaC0de** [comment]
http://pastebin.com/uD0vLJXT

**Comment by Pulper** [comment]
Hadn´t received any E-Mail, yet

**Comment by GammaC0de** [comment]
Didn't you get email notification from github?

**Comment by Pulper** [comment]
Yep

**Comment by GammaC0de** [comment]
Did or didn't?

**Comment by Pulper** [comment]
Didn´t ;-)

**Comment by GammaC0de** [comment]
http://pastebin.com/uD0vLJXT

OK?

**Comment by Pulper** [comment]
Ty

**Comment by wastez** [comment]
Thanks Gammac0de it´s working perfect.

**Comment by Pulper** [comment]
@GammaC0de but ReCaptcha.py also uses BeautfilSoup :-(

**Comment by GammaC0de** [comment]
:+1:

**Comment by GammaC0de** [comment]
@Pulper No it isn't: https://github.com/pyload/pyload/blob/stable/module/plugins/captcha/ReCaptcha.py

**Comment by Pulper** [comment]
@GammaC0de I don´t have Captchaservice.py :-(

```

51	27.02.2016 23:50:38	DEBUG	Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
52	27.02.2016 23:50:38	CRITICAL	'module' object has no attribute 'SerienjunkiesOrg'

```

**Comment by GammaC0de** [comment]
@Pulper its `CaptchaService` not `Captchaservice`

**Comment by Pulper** [comment]
@GammaC0de Alright, but I haven´t it either. Could you provide the code via pastebin please?

**Comment by GammaC0de** [comment]
It's part of pyload, it should be in your userplugins/internal directory.
Anyway, I don't think this is the problem, you probably have wrong ident when toy copied the code,
Try getting is from @wastez's link

**Comment by Pulper** [comment]
Hm, you´ve right, it hadn´t changed anything, still not working ;-)

**Comment by wastez** [comment]
@Pulper
Why you are not taking it from the soucre. 
But it should be in your Pyload folder. 
https://github.com/pyload/pyload/blob/stable/module/plugins/internal/CaptchaService.py

**Comment by GammaC0de** [comment]
Try refreshing your userplugins directory:
* Get the stable package from https://github.com/pyload/pyload/archive/stable.zip
* Extract all the **subfolders** in `<stable.zip>/module/plugins` to your `userplugins` directory.

**Comment by wastez** [comment]
@Pulper 
You are reading the error Message above wrong. 
It just links the CaptchaService to the userplugin/internal folder. 
The message above is talking about the wrong (old) crypter.
