### ISSUE TITLE
sync issue with scripts after download_finished

### ISSUE THREAD

**Issue by JeanMars** [pyload/pyload#2269]
Hi,
it seems that there is some bad sync when download is finished: I have a script (sort.py) after "download_finished" event that basically moves the downloaded file to some folder, but then pyload reports download failed because file is not longer present :-(.
Log:
05.01.2016 00:33:29 INFO      Download finished: xxxx
05.01.2016 00:33:29 INFO      ADDON ExternalScripts: Executing scripts in folder `download_finished`...
05.01.2016 00:33:29 DEBUG     ADDON ExternalScripts: EXECUTE scripts/download_finished/sort.py 51 xxxx /volume1/pyload/downloads/tmp/xxxx OneFichierCom http://1fichier.com/?zzzzz
05.01.2016 00:33:30 INFO [sort.py] version 0.13
05.01.2016 00:33:30 INFO [sort.py] Moving /volume1/pyload/downloads/tmp/xxxx to: /volume1/ttttt
05.01.2016 00:33:30 DEBUG     ADDON Checksum: {'status': 2, 'hash': {}, 'name': u'xxxx', 'url': u'http://1fichier.com/?zzzzz', 'pattern': {'HOST': u'1fichier.com', 'U': u'GB', 'S': u'1.44', 'N': u'xxxx'}}
05.01.2016 00:33:30 WARNING   Download failed: xxxx | No file downloaded
05.01.2016 00:33:30 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`

Thanks,
Jean

**Comment by JeanMars** [comment]
Hi again,
to be checked, but it looks like to be the same as #2252

**Comment by youlJunior** [comment]
Yeah, same as #2252, the script is executed before Pyload checks the file and set the status to "finished".
So when Pyload try to check the file, it has been already moved by your script.

For now I don't see how you can achieve moving files after download properly...

**Comment by GammaC0de** [comment]
@JeanMars Please post full debug log please

**Comment by JeanMars** [comment]
@GammaC0de : What do you mean by full debug log? I have activated debug mode in pyload. BTW, not sure I still have all logs since pyload start.

**Comment by GammaC0de** [comment]
@JeanMars can you try the fix I purposed in #2265 is tell if it helps?

**Comment by JeanMars** [comment]
@GammaC0de : OK i'll try this, if I understand correctly, preprocessing method of Base.py should be:
    def preprocessing(self, *args, **kwargs):
        if self.pyload.threadManager.processingIds().count(self.pyfile.id) > 1:
          return
        time.sleep(1)  #@NOTE: Recheck info thread synchronization in 0.4.10
        return self._process(*args, **kwargs)

**Comment by GammaC0de** [comment]
Yes, please note that is this works its just a temporary solution until we fend a better one

**Comment by JeanMars** [comment]
Hi,
seems the issue is still there:
09.01.2016 13:44:53 INFO      HOSTER OneFichierCom[18]: Downloading file...
09.01.2016 13:44:53 DEBUG     HOSTER OneFichierCom[18]: DOWNLOAD URL http://a-13.1fichier.com/zzzzz | cookies=True | resume=None | get={} | disposition=False | chunks=None | post={} | ref=True
09.01.2016 13:44:53 DEBUG     Content-Disposition: xxxxx.mkv filename*=UTF-8xxxxx.mkv
09.01.2016 13:59:01 INFO      HOSTER OneFichierCom[18]: File saved
09.01.2016 13:59:01 INFO      HOSTER OneFichierCom[18]: Checking download...
09.01.2016 13:59:01 INFO      HOSTER OneFichierCom[18]: File is OK
09.01.2016 13:59:01 INFO      HOSTER OneFichierCom[18]: Checking file (with built-in rules)...
09.01.2016 13:59:01 INFO      HOSTER OneFichierCom[18]: Checking file (with custom rules)...
09.01.2016 13:59:01 INFO      HOSTER OneFichierCom[18]: Checking for link errors...
09.01.2016 13:59:01 INFO      HOSTER OneFichierCom[18]: No errors found
09.01.2016 13:59:01 INFO      HOSTER OneFichierCom[18]: No errors found
09.01.2016 13:59:01 INFO      Download finished: xxxxx.mkv
09.01.2016 13:59:01 INFO      ADDON ExternalScripts: Executing scripts in folder `download_finished`...
09.01.2016 13:59:01 DEBUG     ADDON ExternalScripts: EXECUTE scripts/download_finished/sort.py 18 xxxxx.mkv /volume1/pyload/downloads/wd5/xxxxx.mkv OneFichierCom http://1fichier.com/?yyyy
09.01.2016 13:59:02 INFO [sort.py] version 0.13
09.01.2016 13:59:02 INFO [sort.py] Moving /volume1/pyload/downloads/wd5/xxxxx.mkv to: /volume1/video/xxxxx.mkv
09.01.2016 13:59:02 DEBUG     ADDON Checksum: {'status': 2, 'hash': {}, 'name': u'xxxxx.mkv', 'url': u'http://1fichier.com/?yyyy', 'pattern': {'HOST': u'1fichier.com', 'U': u'GB', 'S': u'1.61', 'N': u'xxxxx.mkv'}}
09.01.2016 13:59:02 WARNING   Download failed: xxxxx.mkv | No file downloaded
09.01.2016 13:59:02 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
09.01.2016 13:59:02 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: xxxxx.mkv (pid:14)
09.01.2016 13:59:02 INFO      ADDON UnSkipOnFail: No duplicates found

(see "13:59:02 WARNING   Download failed" line after downloaded file has been moved to / volume1/video folder.

Hope that helps,
Jean

**Comment by youlJunior** [comment]
@JeanMars the issue #2252 has not been resolved, so you can't use your sort.py script

**Comment by GammaC0de** [comment]
@youlJunior this is not the same issue, the proble is that  `ExternalScripts` addon runs before the `Checksum` addon.

**Comment by JeanMars** [comment]
@GammaC0de : so what did you want me to test?

**Comment by GammaC0de** [comment]
Disable the `Checksum` plugin

**Comment by JeanMars** [comment]
With checksum plugin disabled, issue does not show anymore, thanks!

**Comment by GammaC0de** [comment]
:+1:
