### ISSUE TITLE
Uploaded: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by Lalarian** [pyload/pyload#2270]
Hello!

I've have freshly installed pyload yesterday and came to this error, when trying to download from Uploaded. An example link: http://uploaded.net/file/q56324xg

I found this patch: https://github.com/pyload/pyload/commit/477046e0b1bb37e294db6ceab68462c0fc797ea7

but my utils.py already got this patch included.

**Comment by sraedler** [comment]
same issue with share-online.biz...

**Comment by youlJunior** [comment]
Isn't it the same issue as #2245 ?

**Comment by GammaC0de** [comment]
#1949, #2245, #2010, #2119, #2025, #2194, #2173, #2179, ...
