### ISSUE TITLE
Smoozed - deleted/closed utf8 errors still exists

### ISSUE THREAD

**Issue by maddyxp** [pyload/pyload#2276]
Hello everyone,
(asking to GammaC0de)

i wonder why there was all encoding (utf8/Ascii) issues are closed, because at least for smoozed the (or one) bug still exist.
(like i commented [#2245](https://github.com/pyload/pyload/issues/2245)

UpdateManager is working again (since short time), thats great but still with updated plugins this issue exists.
tried with 9 days old "stable" Version
also with newest: HEAD detached at 09df5bc

if i'm wrong and there is a easy solution, plz refer one more time to it, please.
Thanks in advance.

08.01.2016 19:53:22 INFO      ADDON UpdateManager: All plugins are up to date!
08.01.2016 19:53:36 INFO      Download starts: BZ-03.01.16.pdf (2)
08.01.2016 19:53:36 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
08.01.2016 19:53:36 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
08.01.2016 19:53:37 DEBUG     HOSTER ShareonlineBiz[1]: Plugin version: 0.65
08.01.2016 19:53:37 DEBUG     HOSTER ShareonlineBiz[1]: Plugin status: testing
08.01.2016 19:53:37 WARNING   HOSTER ShareonlineBiz[1]: Plugin may be unstable
08.01.2016 19:53:37 INFO      HOSTER ShareonlineBiz[1]: Grabbing link info...
08.01.2016 19:53:37 DEBUG     HOSTER ShareonlineBiz[1]: Link info: {'status': 2, 'hash': {}, 'name': 'BZ-03.01.16.pdf', 'url': u'http://www.share-online.biz/dl/S28T2D0OGM3', 'pattern': {'ID': u'S28T2D0OGM3'}, 'size': 27297321, 'md5': '797b084510795b76d805ec061f731f32', 'fileid': 'S28T2D0OGM3'}
08.01.2016 19:53:37 DEBUG     HOSTER ShareonlineBiz[1]: Previous link info: {}
08.01.2016 19:53:37 INFO      HOSTER ShareonlineBiz[1]: Link name: BZ-03.01.16.pdf
08.01.2016 19:53:37 INFO      HOSTER ShareonlineBiz[1]: Link size: 26.03 MiB (27297321 bytes)
08.01.2016 19:53:37 INFO      HOSTER ShareonlineBiz[1]: Link status: online
08.01.2016 19:53:37 INFO      HOSTER ShareonlineBiz[1]: Processing url: http://www.share-online.biz/dl/S28T2D0OGM3
08.01.2016 19:53:37 INFO      HOSTER ShareonlineBiz[1]: Looking for direct download link...
08.01.2016 19:53:37 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.share-online.biz/dl/S28T2D0OGM3 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
08.01.2016 19:53:37 INFO      HOSTER ShareonlineBiz[1]: Direct download link not found
08.01.2016 19:53:37 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.share-online.biz/dl/S28T2D0OGM3 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
08.01.2016 19:53:37 INFO      HOSTER ShareonlineBiz[1]: Processing as free download...
08.01.2016 19:53:37 DEBUG     HOSTER ShareonlineBiz[1]: WAIT set to timestamp 1452279221.904803 | Previous waitUntil: 0.000000
08.01.2016 19:53:37 INFO      HOSTER ShareonlineBiz[1]: Waiting 3 seconds...
08.01.2016 19:53:41 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.share-online.biz/dl/S28T2D0OGM3/free/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'dl_free': '1', 'choice': 'free'} | ref=True | just_header=False
08.01.2016 19:53:43 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.google.com/recaptcha/api/challenge | redirect=True | cookies=True | get={'k': '6LdatrsSAAAAAHZrB70txiV5p-8Iv8BtVxlTtjKX'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.01.2016 19:53:43 DEBUG     CAPTCHA ShareonlineBiz[1]: ReCaptcha | Challenge: 03AHJ_Vuti9EY9TVdy_N1f_9ejX6Zq8gBEb1qd5r2ZgK5NUXwp_TG3_uktn6KYq40yndBF08QnlqvLTkM0fZWvvJbPPWO8cEMiEqs_p__8xs5fqK6GfyVGqr_kS0Sq18Qui4hyEcI-r_gI5hpcPAnQt4jEr9QyT4ZyiCuyn1eIOl2s5qpZnvWpWmHOqkl289Rhvx-0AUJpjEtV
08.01.2016 19:53:43 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.01.2016 19:53:43 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.google.com/recaptcha/api/reload | redirect=True | cookies=True | get={'reason': 'i', 'c': u'03AHJ_Vuti9EY9TVdy_N1f_9ejX6Zq8gBEb1qd5r2ZgK5NUXwp_TG3_uktn6KYq40yndBF08QnlqvLTkM0fZWvvJbPPWO8cEMiEqs_p__8xs5fqK6GfyVGqr_kS0Sq18Qui4hyEcI-r_gI5hpcPAnQt4jEr9QyT4ZyiCuyn1eIOl2s5qpZnvWpWmHOqkl289Rhvx-0AUJpjEtV', 'type': 'image', 'k': '6LdatrsSAAAAAHZrB70txiV5p-8Iv8BtVxlTtjKX'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.01.2016 19:53:43 DEBUG     CAPTCHA ShareonlineBiz[1]: ReCaptcha | Second challenge: 03AHJ_Vut9q5JBTs2hjnd33LFoyO529cVnqCBAAjBzHE_sf20RWZNX5TuP3IMJBKHYozXc-Q0b5zTPc36wo4eVwWMfcF-J3V1T4tC5KhOTFmPIIa8Qmuv0NJCTTjuHKAkpboczTNvgOeMw439dBrbmRF87EDamxADbxoI-Nyq7mAwJG14wlT59H81F-kJRRwc66aPDFxUZN5wcIOaySe_R5fEamAbrzbYAbQ
08.01.2016 19:53:43 DEBUG     CAPTCHA ShareonlineBiz[1]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | redirect=True | cookies=True | get={'c': u'03AHJ_Vut9q5JBTs2hjnd33LFoyO529cVnqCBAAjBzHE_sf20RWZNX5TuP3IMJBKHYozXc-Q0b5zTPc36wo4eVwWMfcF-J3V1T4tC5KhOTFmPIIa8Qmuv0NJCTTjuHKAkpboczTNvgOeMw439dBrbmRF87EDamxADbxoI-Nyq7mAwJG14wlT59H81F-kJRRwc66aPDFxUZN5wcIOaySe_R5fEamAbrzbYAbQ'} | req=<module.network.Browser.Browser object at 0xb0ac7618> | decode=False | multipart=False | post={} | ref=False | just_header=False
08.01.2016 19:53:43 WARNING   Download failed: BZ-03.01.16.pdf (2) | 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by vuolter** [comment]
I'm not @GammaC0de... :p 
but I can assure you all encoding issue can not be closed in 0.4.9 .
We have to switch the core modules to the unicode encoding, that's the way. u.u

**Comment by GammaC0de** [comment]
@vuolter Obviusly the problem relies in `fixurl` of `misc.py`.
Can you please describe what excatly it should do and what is the purpose of `unquote` parameter?

**Comment by nordic-style** [comment]
You cannot fix this in 4.9 ? But it was introduced just two weeks ago ...

Thank you for looking into it.

**Comment by Velociraptor85** [comment]
@vuolter @GammaC0de pls close is duplicate of "main" issue thread #2286
