### ISSUE TITLE
HotFolder: File not found 

### ISSUE THREAD

**Issue by VinceGitHub** [pyload/pyload#2279]
10.01.2016 11:48:00	ERROR	Decrypting failed: NameOfSomeDlcFile.dlc | File not found 

In HotFolder.py line 64 
There is a new function "move_tree(path, newpath) " to move the file. 
I think this function isn't made to move just one file. 
We should go back to use this function "shutil.move(path, newpath)". With this one there is no Error.

[DebugLog.txt.txt](https://github.com/pyload/pyload/files/85138/DebugLog.txt.txt)

**Comment by GammaC0de** [comment]
Debug log please

**Comment by VinceGitHub** [comment]
See first post
