### ISSUE TITLE
Temorary container file will not delete

### ISSUE THREAD

**Issue by Web-Eye** [pyload/pyload#2280]
If I import a container file, it will be save (temporary) in my download folder, but after importing or downloading never deleted.

Info: pyload is running with root rights, temporary container file will be created with 666 root:root privilegs
The original and the temp container file is attached!
[container.zip](https://github.com/pyload/pyload/files/84080/container.zip)
see #2275 too

Thanks,
WebEye

**Comment by Web-Eye** [comment]
seems to work, thanks

**Comment by GammaC0de** [comment]
:+1:
