### ISSUE TITLE
pyload.org is down

### ISSUE THREAD

**Issue by mrJakez** [pyload/pyload#2285]
Hi guys, 

the pyload page (and the forum) seems to be offline. Any idea when it will be available again?

Cheers
Dennis

**Comment by timkley** [comment]
Just do a git clone of everything and run `python pyLoadCore.py`. Same thing.

**Comment by vuolter** [comment]
I'm going to report it to the webmaster. I wait just a little more to see if the site back online.

**Comment by thilo-dual** [comment]
the website is offline since 2 days now

**Comment by Velociraptor85** [comment]
cant reach it either

**Comment by Brice187** [comment]
where can i get the plugin updates, when the Website is down?

**Comment by timkley** [comment]
@Brice187 from Github. `git clone https://github.com/pyload/pyload.git pyload`. If you have it already installed you may need to setup git first and add the remote manually.

**Comment by GammaC0de** [comment]
@Brice187 pyLoad get plugin updates from the update server which runs on a different server than pyload.org and so plugin updates are currently fully functional.

**Comment by mihawk90** [comment]
Wish this were true (I just downloaded since a long time ago, directly from the releases page here on github)
```
19.01.2016 05:50:04 INFO      Starting pyLoad 0.4.9
19.01.2016 05:50:04 INFO      Using home directory: C:\Users\tarulia\Downloads\pyload\data
19.01.2016 05:50:07 INFO      ExtractArchive: Activated UnRar UnZip
19.01.2016 05:50:07 INFO      Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
19.01.2016 05:50:07 INFO      Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
19.01.2016 05:50:07 INFO      Downloadtime: True
19.01.2016 05:50:07 INFO      Server set to threaded, due to known performance problems on windows.
19.01.2016 05:50:07 INFO      Free space: 16.86 GiB
19.01.2016 05:50:07 INFO      Starting threaded webserver: 0.0.0.0:8000
19.01.2016 05:50:07 INFO      Activating Accounts...
19.01.2016 05:50:07 INFO      Activating Plugins...
19.01.2016 05:50:07 INFO      pyLoad is up and running
19.01.2016 05:50:11 WARNING   Not able to connect server for updates
19.01.2016 05:50:11 INFO      No Updates for pyLoad
19.01.2016 05:50:11 WARNING   Not able to connect server for updates
19.01.2016 05:50:11 INFO      No plugin updates available
19.01.2016 05:50:53 INFO      shutting down...
19.01.2016 05:50:53 INFO      killed pyLoad from Terminal
```

**Comment by Brice187** [comment]
@mihawk90 try this git clone thing mentioned by @timkley. This tip worked for me. 
But I don't know how this works for windows.

**Comment by GammaC0de** [comment]
@mihawk90 Because of the recent DDOS, your IP is probably blacklisted.
Try changing your IP.
http://www.downforeveryoneorjustme.com/http://updatemanager.pyload.org

**Comment by mihawk90** [comment]
Ah OK, gotta wait in that case. My ISP assigns me a static IP so that won't work for me :) But thanks for the notice anyway :)

**Comment by GammaC0de** [comment]
:+1:

**Comment by vuolter** [comment]
I sent a mail to the webmaster today. I'll let you know what's happened soon as I get a reply.

**Comment by vuolter** [comment]
Working on a new forum platform, since the webmaster told me the db was corrupted/stolen/losed.
I'm still waiting more info from him. :s

**Comment by nordic-style** [comment]
Backups? ;)

**Comment by vuolter** [comment]
I have a backup of the whole website dated on last november and created with HTTrack.

**Comment by justroot1337** [comment]
any updates?

**Comment by vuolter** [comment]
The new main site is http://pyload.github.io/ (under construction)
Indeed pyload.org will redirect to it soon.
The database of the forum is definitely lost. As I wrote above, I have a backup of all the website, forum stuff included, so discussions, shared files, unofficial plugins and so on are save. I might put online a new little forum platform and publish there all again. I'm currently questioning with the owners of the project. ;)

**Comment by zion2k** [comment]
Hi,
is it possible to get a dump of the forum? I found some threads with google, but can not access them. Would be great if the knowledge isnt lost.

**Comment by vuolter** [comment]
Don't panic, there is a backup of everything.

**Comment by timofonic** [comment]
I just used the site repo to see my "discovery" :D 

https://github.com/pyload/pyload.github.io/issues/1

Any news? Will there be new releases for Windows too?

**Comment by vuolter** [comment]
@zion2k I'll definitely upload a dump of the forum soon, maybe upon mega. u_u

**Comment by vuolter** [comment]
Here it is: https://twitter.com/pyload/status/706646435538866176

**Comment by GammaC0de** [comment]
RIP pyload.org :angel:
