### ISSUE TITLE
[misc] Fix: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by sschwart** [pyload/pyload#2286]
Hello,

There is a way to remove the 'ascii' codec error. The idea is to convert (i.e. find an equivalent) as much as possible of all character to ascii one. Ex.: “éêËçàñö” etc. to “eeEcano”. Thus, all possible characters are converted to an ascii equivalent. If there is not equivalent, the character is removed. Until now, only “β” and “°” are removed for me. It is not a perfect solution (and code so far) but it work fine :)

In misc.py file:

``` python
…
import unicodedata #add
…
def fixurl(url, unquote=None):
    old = url
    url = urllib.unquote(url)

    if unquote is None:
        unquote = url is old

    url = html_unescape(unicodedata.normalize('NFKD', decode(url)).encode('ascii','ignore').decode('unicode-escape')) #modification
    url = re.sub(r'(?<!:)/{2,}', '/', url).strip().lstrip('.')

    if not unquote:
        url = urllib.quote(url)

    return url
```

**Comment by xDereCx** [comment]
briliant, worked for me #2173

**Comment by lachtan86** [comment]
many thanks, worked me too!

**Comment by bast69** [comment]
Hi,
Not works for me... The "@" symbol is replacing by what ?
For an example, this link doesn't work for me : [http://uptobox.com/m5puiv14apsh](http://uptobox.com/m5puiv14apsh)

**Comment by sschwart** [comment]
Hi,

The '@' is not replaced for me and pyload download the file. The only character replaced is "É" to "E".
So, it is strange it doesn't work for you..
What is the error ? _'ascii' codec can't encode character ..._ ? Which is the character on the error message ?

**Comment by bast69** [comment]
Thanks for your reply. The error message is `'ascii' codec can't encode character u'\xc9' in position 44: ordinal not in range(128)`

**Comment by sschwart** [comment]
This error correspond to the character 'É'. So, that's meen the modification is not took into account.. Have you done the right modification whith root access ? (sudo nano misc.py for exemple ? Or 'vi' if you prefer) Have you restart your pyload ? If you have a doubt, reboot your computer.

**Comment by bast69** [comment]
I have followed your recommandation : 

> It's strange because with the modification, even if the ascii can't encode characters, the characters are removed..
> 
> In this order:
> 
> Have you removed the link of the pyload contener?
> Have you edit your file with root privilege?
> Have you restart your pyload after modification? (to reload the modified files)
> Have you add again your link to pyload?
> If it still doesn't work, could you send me your link to try with my pyload setup?

I'm on a raspberry with debian wheezy. For the modification, i do this : `sudo vi misc.py`
however, i don't reboot my raspberry.

**Comment by bemar** [comment]
This "fix" mostly works for me but I still have sometime the " 'ascii' codec can't encode character"

Just my 2 cents, I "corrected" fixurl in misc.py like below, and it works for the moment :
(I just changed in @sschwart correction the default decode(url) by unicode(url))

```python
…
import unicodedata #add
…
def fixurl(url, unquote=None):
    old = url
    url = urllib.unquote(url)

    if unquote is None:
        unquote = url is old

    url = html_unescape(unicodedata.normalize('NFKD', unicode(url)).encode('ascii','ignore').decode('unicode-escape')) #modification
    url = re.sub(r'(?<!:)/{2,}', '/', url).strip().lstrip('.')

    if not unquote:
        url = urllib.quote(url)

    return url
```

**Comment by sodd** [comment]
may i ask what is the "official" standpoint for all this ascii encode problem? I know this issue has duplicate label but i can't find the first or original one, where can i probably read what is wrong and what need to be improved. 
thx @vuolter or @GammaC0de

**Comment by Velociraptor85** [comment]
@GammaC0de  @vuolter could we delete the dublicate label and use this as the reference bug report?

also seems like there is an fix https://github.com/pyload/pyload/pull/2346

**Comment by rdehouss** [comment]
Not working for me, neither solution in #2346
Example: http://ul.to/4dq19a9y

:s 

Any other idea?

**Comment by soif** [comment]
@sschwart . Your code also fixed the issue for me on 10 different URLs. 
Great Job :+1: 

Time to submit a PR, isn'it ?

**Comment by Burnout5151** [comment]
@soif : Have you also tried the patch in #2346 ? That one would have the benefit of keeping unicode signs.

**Comment by rdehouss** [comment]
@Burnout5151, the PR #2346 seems not enough for me, see the link in my previous comment.
