### ISSUE TITLE
UnRAR plugin issues "Extract failed"

### ISSUE THREAD

**Issue by Arno-Nymous** [pyload/pyload#2289]
The UnRAR extractor (plus, as it seems to me, the other extractor plugins, too) reports an "Extract failed" error message but gives no further information. This error message can pass unnoticed since the traceback is not printed in `--daemon` mode. One has to run pyLoad in the foreground in order to see where the traceback leads.

Further examination revealed to me that as soon as the UnRAR plugin hits [this line](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/UnRar.py#L227) it chokes on the upfollowing log commands since the value of `pyfile.plugin` can be `None`.

Unfortunatelly I don't have a log ouput at this very moment which demonstrates this behavior, but I'll do a pull request in no time, which fixes this error plus some more which went hand in hand with this one.

**Comment by GammaC0de** [comment]
see #2250
