### ISSUE TITLE
'ascii' codec can't encode character

### ISSUE THREAD

**Issue by jibedo** [pyload/pyload#2291]
Hello, when I try to download a file with a special character, I get an error message:
"'ascii' codec can't encode character"

In Debug mode : 
<quotes>
Traceback (most recent call last):
  File "/etc/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/root/.pyload/userplugins/internal/Base.py", line 290, in preprocessing
    return self._process(_args, *_kwargs)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 107, in _process
    self._setup()
  File "/root/.pyload/userplugins/internal/Base.py", line 166, in _setup
    self.grab_info()
  File "/root/.pyload/userplugins/internal/Base.py", line 227, in grab_info
    new_info = self.get_info(self.pyfile.url, self.data)
  File "/root/.pyload/userplugins/internal/SimpleHoster.py", line 179, in get_info
    info['name'] = parse_name(name)
  File "/root/.pyload/userplugins/internal/misc.py", line 519, in parse_name
    path  = fixurl(decode(value), unquote=False)
  File "/root/.pyload/userplugins/internal/misc.py", line 456, in fixurl
    url = html_unescape(decode(url).decode('unicode-escape'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 37: ordinal not in range(128) 
</quotes>

**Comment by sschwart** [comment]
There is a solution in the post #2286. The is one ligne to add in the beginning of the file and an other to modified. 
In misc.py (/usr/share/pyload/module/plugins/internal/):
Add after all python import 
```python 
import unicodedata
```
And, in `def fixurl` (line 456), modify:
```python
url = html_unescape(decode(url).decode('unicode-escape'))
```
To:
```python
url = html_unescape(unicodedata.normalize('NFKD', decode(url)).encode('ascii','ignore').decode('unicode-escape'))
```
It works great ;)

**Comment by jibedo** [comment]
Thank you !

This works perfectly

**Comment by ochbob** [comment]
This trick doesn't work for me.

Still have this error =>

'ascii' codec can't encode characters in position 59-60: ordinal not in range(128) 

Download file name =>

Lakeview.Terrace.(Harcelés).2008.MULTi.1080p.BluRay.HDLight.AC3.x264-Zone80.mkv

LOG =>

827	26.01.2016 08:23:34	INFO	HOSTER BasePlugin[27]: Grabbing link info...
828	26.01.2016 08:23:34	WARNING	Download failed: https://XXX.XXX/G6NTPU3DYNBCQ/Lakeview.Terrace.%28Harcel%C3%A9s%29.2008.MULTi.1080p.BluRay.HDLight.AC3.x264-Zone80.MaChO%40zone.mkv | 'ascii' codec can't encode characters in position 59-60: ordinal not in range(128) 

Any idea ?

**Comment by sschwart** [comment]
It's strange beauce with the modification, even if the ascii can't encode characters, the characters are removed.. 

In this order: 
- Have you removed the link of the pyload contener?
- Have you edit your file with root privilege?
- Have you restart your pyload after modification? (to reload the modified files)
- Have you add again your link to pyload?

If it still doesn't work, could you send me your link to try with my pyload setup?

**Comment by ochbob** [comment]
Hi

yes i did everything you said. But still not work =S

I use this link => https://jncm6bu8q3.1fichier.com/

Then Real-debrid to unrestrict the link 

=> Download failed: https://xxxxxx/d/Y2GYKLCQRO5S4/Pr%C3%A9sum%C3%A9%20coupable%202011%20FRENCH%20AC3%201080p%20x264-GOLDORAK.mkv | 'ascii' codec can't encode characters in position 37-38: ordinal not in range(128)

**Comment by Velociraptor85** [comment]
@vuolter @GammaC0de pls close is duplicate and already in "main" issue thread linked https://github.com/pyload/pyload/issues/2286
