### ISSUE TITLE
Extractarchive: ValueError: too many values to unpack

### ISSUE THREAD

**Issue by outkastm** [pyload/pyload#2296]
Hi,
Plugin ExtractArchive is giving one error

```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/raid/data/module/pyload/sys/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/raid0/data/module/pyload/bin/pyload/module/PluginThread.py", line 459, in run
    self.f(*self.args, **self.kwargs)
  File "/raid0/data/module/pyload/bin/pyload/module/plugins/hooks/ExtractArchive.py", line 185, in extract_queued
    if self.extract(packages, thread):  #@NOTE: check only if all gone fine, no failed reporting for now
  File "/raid0/data/module/pyload/bin/pyload/module/plugins/hooks/ExtractArchive.py", line 281, in extract
in sorted(pypack.getChildren().values(), key=lambda k: k['name'])).items()  #: Remove duplicates
  File "/raid0/data/module/pyload/bin/pyload/module/plugins/hooks/ExtractArchive.py", line 280, in <genexpr>
files_ids = dict((fdata['name'], ((fsjoin(dl_folder, pypack.folder, fdata['name'])), fid, out)) for fid, fdata \
ValueError: too many values to unpack    
```

I am running Python 2.7.11 and Pyload 0.4.9 latest stable

**Comment by GammaC0de** [comment]
This is a known issue, the current status of `ExtractArchive` is [`"broken"`](https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExtractArchive.py#L102)

@vuolter is in the middle of rewriting this plugin and hopefully will release it very soon.

**Comment by Arno-Nymous** [comment]
@outkastm see my latest pull request on that. It solves some of the problems with file extraction. Apply those changes to your pyLoad if you cannot wait for @vuolter to release a final fix.

**Comment by GammaC0de** [comment]
@Arno-Nymous Maybe your PR does fix the above issue, but it also changes fundamental parts of `pyLoad`'s core so I'm pretty sure that it will be rejected by @vuolter, never the less that it **was** working before (some changes were made to it that broke it) without the changes in the core.. :wink:

**Comment by Arno-Nymous** [comment]
Glad to hear that it worked before without changing the core, but as of now it doesn't ^^ So I somehow have to help myself (and hopefully others) out since I need to get those downloads running even if this means that I have to do some quick and dirty fix. I'm neither a fan of such changes but sometimes special situations require special measures ;)
If my changes don't make it into the project then at least I hope it helps others to bridge the time until a final fix will be released.

By the way: what are those changes that I did to fundamental parts in the code? I'm really interested in that because it seems to me that lately a lot has been changed (and broken) in places of pyLoad which I would also consider fundamental parts ^^

**Comment by GammaC0de** [comment]
:+1: 
Indeed many changes were made recently.
Everything that is not under `module/plugins` is considered part of the core and has not been changed since the first release of v0.4.9

**Comment by Arno-Nymous** [comment]
Then let me ask one question: Why don't you consider places like `module/plugins/internal` also core parts since already the name allows that assumption? But it's less the name of the folder in my opinion, it's more the functionality those modules contain. Now, history shows us

**Comment by vuolter** [comment]
@Arno-Nymous I take what you wrote for the 0.4.10, it's a good idea.

**Comment by Arno-Nymous** [comment]
glad reading we share the same opinion :grimacing:

**Comment by PhilW86** [comment]
Any updates about when we can expect a release? I heavily rely on this functionality, now it's broken for more than 2 weeks. :(
In case we can't expect a working version anytime soon, any advice for a workaround? (E.g. fetch or clone revision X and deactivate updates or something?)
Many thanks in advance

**Comment by GammaC0de** [comment]
@PhilW86 You can try your luck with this version: https://github.com/pyload/pyload/archive/5ee1a6ddf8cd550e58224817f306d4ddebd1512e.zip

**Comment by It0w** [comment]
> @PhilW86 You can try your luck with this version: https://github.com/pyload/pyload/archive/5ee1a6ddf8cd550e58224817f306d4ddebd1512e.zip

fresh install and works like a charm 
thanks

**Comment by PhilW86** [comment]
Thanks @GammaC0de, it's really working like a charm. :)

**Comment by GammaC0de** [comment]
:+1:

**Comment by godfuture** [comment]
@GammaC0de
> @PhilW86 You can try your luck with this version: https://github.com/pyload/pyload/archive/5ee1a6ddf8cd550e58224817f306d4ddebd1512e.zip

I tried this one, but still no luck. I have deleted pyload files initially installed through package, cloned from git, moved them to previous location where package was, set permissions, deleted userplugins and started. Still:
```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 459, in run
    self.f(*self.args, **self.kwargs)
  File "/etc/pyload/userplugins/hooks/ExtractArchive.py", line 185, in extract_queued
    if self.extract(packages, thread):  #@NOTE: check only if all gone fine, no failed reporting for now
  File "/etc/pyload/userplugins/hooks/ExtractArchive.py", line 281, in extract
    in sorted(pypack.getChildren().values(), key=lambda k: k['name'])).items()  #: Remove duplicates
  File "/etc/pyload/userplugins/hooks/ExtractArchive.py", line 280, in <genexpr>
    files_ids = dict((fdata['name'], ((fsjoin(dl_folder, pypack.folder, fdata['name'])), fid, out)) for fid, fdata \
ValueError: too many values to unpack

**Comment by GammaC0de** [comment]
@godfuture You should disable update manager (at least until this issue is fixed)

**Comment by godfuture** [comment]
@GammaC0de 
I have replaced the userplugins with the package you promoted. After starting pyload in cli, this error message appears for the first try to extract:
```
09.02.2016 00:37:42 INFO      ADDON ExtractArchive: yyy.rar | Extracting finished
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 459, in run
    self.f(*self.args, **self.kwargs)
  File "/usr/share/pyload/module/plugins/hooks/ExtractArchive.py", line 185, in extract_queued
    if self.extract(packages, thread):  #@NOTE: check only if all gone fine, no failed reporting for now
  File "/usr/share/pyload/module/plugins/hooks/ExtractArchive.py", line 289, in extract
    if filter(lambda ext: fname.lower().endswith(ext), extensions)]
  File "/usr/share/pyload/module/plugins/hooks/ExtractArchive.py", line 289, in <lambda>
    if filter(lambda ext: fname.lower().endswith(ext), extensions)]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 56: ordinal not in range(128)
```

**Comment by GammaC0de** [comment]
@godfuture Please try with another archive, the issue you have logged is related to non-english characters file names

**Comment by godfuture** [comment]
@GammaC0de 
You are bloody right, after removing the failed package, the extract module was able to do its job. Shall I open another ticket for the encoding issue?

**Comment by GammaC0de** [comment]
@godfuture No, the version you are using is an old version, so it might have been fixed already.
Also, don't forget to re-enable `UpdateManager` once the above issue is fixed.

**Comment by macianer85** [comment]
> @PhilW86 You can try your luck with this version: https://github.com/pyload/pyload/archive/5ee1a6ddf8cd550e58224817f306d4ddebd1512e.zip
fresh install and works like a charm 
thanks

Hi,
how do i install this version? simply ssh connect and overwrite the files in the pyload folder? im also struggling with ExtractArchive not starting.

**Comment by It0w** [comment]
I have deleted the "old" pyload Folder
Befor you install the pyload from the Archive you should disable the Update Manager

--Sorry for my creepy English

**Comment by FabrizioA** [comment]
@PhilW86 Can you confirm that your archive still works?
I've tried your archive with no success.... I had removed my pyload installation folder and his .pyload home's config dir. Then, I have downloaded your archive, execute pyLoadCore.py for the first time with related configurations steps and then shorty run and stop pyLoadCore.py to generate plugin.conf inside .pyload foder... then I've disabled UpdateManager and launched pyLoadCore.py..... the result was that my Easybytez account doesn't works...
Can you confirm that your archive still works? Can you brief the steps to copy and replace the corrects files from original/master pyLoad code?
Many thanks :)

**Comment by godfuture** [comment]
Is this ticket still an issue? Can I activate the update manager again? I have disabled it since then...

**Comment by GammaC0de** [comment]
@godfuture Currently ExtractArchive plugin is more or less working
