### ISSUE TITLE
download will wait for external script

### ISSUE THREAD

**Issue by Web-Eye** [pyload/pyload#2298]
I've got package finished script, which do some time-consuming processes, like extracting archives and so on! This works proper till last few days, at example I've got two packages in queue, the first one is finished and the external script is fired. During executing the script the files of package 2 will download!

Now, when the external script is fired, all next downloads will wait for the end of the script, and this is very time-expensive! The files are shown in the active downloads tab with status "queued"

It's very hard to take log of this issue, but If you need one, I will give it a try....

**Comment by GammaC0de** [comment]
try playing with the `unlock` config option of `ExternalScripts` plugin

**Comment by Web-Eye** [comment]
I think it's solved!
Althought there is no `unlock` option, I set the `Execute script concurrently`on, and the further download works proper without waiting!
