### ISSUE TITLE
megadebrid not working  can t see it

### ISSUE THREAD

**Issue by shyriu42** [pyload/pyload#2303]
421 19.01.2016 17:49:30 INFO    HOSTER OneFichierCom[5]: Waiting 1 minutes...
420 19.01.2016 17:49:30 INFO    HOSTER OneFichierCom[5]: Checking for link errors...
419 19.01.2016 17:49:29 INFO    HOSTER OneFichierCom[5]: Direct download link not found
418 19.01.2016 17:49:29 INFO    HOSTER OneFichierCom[5]: Looking for direct download link...
417 19.01.2016 17:49:29 INFO    HOSTER OneFichierCom[5]: Processing url: http://1fichier.com/?gestloyr95
416 19.01.2016 17:49:29 INFO    HOSTER OneFichierCom[5]: Link status: queued 

megadebrid account is on and ok

**Comment by vuolter** [comment]
Debug log please.

**Comment by GammaC0de** [comment]
Megadebrid now works, closing.
