### ISSUE TITLE
Problem with CloudSix.me

### ISSUE THREAD

**Issue by Napster32** [pyload/pyload#2305]
Hi @vuolter 
I have some problem with CloudSix.me, i am downloading this file:
http://cloudsix.me/dor0v9xs30uj/EseNodAnt90.rar
But i read in my log this errors:

`20.01.2016 08:46:52    INFO     Added package NOD32 20.01.16 containing 1 links
83  20.01.2016 08:46:54 INFO     Download starts: http://cloudsix.me/dor0v9xs30uj/EseNodAnt90.rar
84  20.01.2016 08:46:55 WARNING  HOSTER XFileSharing[3]: CloudsixMe | Plugin may be unstable
85  20.01.2016 08:46:55 INFO     ACCOUNT CloudsixMe: Grabbing account info for user`myaccount`...
86  20.01.2016 08:46:55 INFO     HOSTER XFileSharing[3]: CloudsixMe | Grabbing link info...
87  20.01.2016 08:46:56 INFO     Download starts: http://cloudsix.me/dor0v9xs30uj/EseNodAnt90.rar
88  20.01.2016 08:46:56 INFO     HOSTER XFileSharing[3]: CloudsixMe | Link name: EseNodAnt90.rar
89  20.01.2016 08:46:56 INFO     HOSTER XFileSharing[3]: CloudsixMe | Link size: 176.40 MiB (184968806 bytes)
90  20.01.2016 08:46:56 INFO     HOSTER XFileSharing[3]: CloudsixMe | Link status: online
91  20.01.2016 08:46:56 INFO     HOSTER XFileSharing[3]: CloudsixMe | Processing url: http://cloudsix.me/dor0v9xs30uj/EseNodAnt90.rar
92  20.01.2016 08:46:56 INFO     HOSTER XFileSharing[3]: CloudsixMe | Checking for link errors...
93  20.01.2016 08:46:57 INFO     HOSTER XFileSharing[3]: CloudsixMe | No errors found
94  20.01.2016 08:46:57 INFO     HOSTER XFileSharing[3]: CloudsixMe | Processing as free download...
95  20.01.2016 08:46:57 INFO     HOSTER XFileSharing[3]: CloudsixMe | Checking for link errors...
96  20.01.2016 08:46:57 INFO     HOSTER XFileSharing[3]: CloudsixMe | No errors found
97  20.01.2016 08:46:57 WARNING  HOSTER XFileSharing[3]: CloudsixMe | Plugin may be unstable
98  20.01.2016 08:46:57 INFO     ACCOUNT CloudsixMe: Grabbing account info for user`myaccount`...
99  20.01.2016 08:46:57 INFO     HOSTER XFileSharing[3]: CloudsixMe | Grabbing link info...
100 20.01.2016 08:46:58 ERROR    pycurl error 23: Failed writing body (0 != 21684)
101 20.01.2016 08:46:58 INFO     ADDON UnSkipOnFail: Looking for skipped duplicates of: EseNodAnt90.rar (pid:3)
102 20.01.2016 08:46:58 INFO     ADDON UnSkipOnFail: No duplicates found
103 20.01.2016 08:46:58 WARNING  Download failed: EseNodAnt90.rar | 'NoneType' object has no attribute 'id'`

**Comment by GammaC0de** [comment]
@Napster32 `CloudSix` uses CloudFlare's DDOS protection which cannot be supported in v0.4.9 because of a bug that prevents getting the html body in case of a `BadHeader` exception (403 in our case)

**Comment by Napster32** [comment]
So, what can I do to solve my problem?

**Comment by GammaC0de** [comment]
CloudSix tested now and works OK with a patched [HTTPRequest.py](https://github.com/GammaC0de/pyload/blob/1f8acaefb33faacbe85fc00ae961f1ab7ae6e8e8/pyload/network/HTTPRequest.py) and the new [CloudFlareDdos](https://github.com/pyload/pyload/blob/f0c49a8db0671219e6e2e225880488cb71bafa90/module/plugins/hooks/CloudFlareDdos.py) hook plugin active .

**Comment by GammaC0de** [comment]
The fixed HTTPRequest.py has been merged to the stable branch so closing.
