### ISSUE TITLE
ERROR	ACCOUNT RapidgatorNet

### ISSUE THREAD

**Issue by akfedux** [pyload/pyload#2306]
After last changes:

447 20.01.2016 07:49:02 INFO    Starting lightweight webserver (bjoern): 0.0.0.0:8000
448 20.01.2016 07:49:02 INFO    Activating Accounts...
449 20.01.2016 07:49:02 INFO    ACCOUNT RapidgatorNet: Adding user `abc@hotmail.com`...
450 20.01.2016 07:49:02 INFO    ACCOUNT RapidgatorNet: Login user `abc@hotmail.com`...
451 20.01.2016 07:49:03 INFO    ACCOUNT RapidgatorNet: Grabbing account info for user `abc@hotmail.com`...
452 20.01.2016 07:49:03 ERROR   ACCOUNT RapidgatorNet: 'RapidgatorNet' object has no attribute '_schedule_refresh'
453 20.01.2016 07:49:03 INFO    Activating Plugins...
454 20.01.2016 07:49:03 INFO    pyLoad is up and running
455 20.01.2016 07:49:03 INFO    ADDON UpdateManager: pyLoad is up to date!
456 20.01.2016 07:49:05 INFO    ADDON UpdateManager: All plugins are up to date!
457 20.01.2016 07:49:09 INFO    ADDON ClickNLoad: Proxy listening on 127.0.0.1:9666

**Comment by GammaC0de** [comment]
@akfedux I wiil need a valid account for testing

**Comment by akfedux** [comment]
What is your private e-mail?

2016-01-20 23:40 GMT+01:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
nitzo2001 [AT] yahoo [DOT] com

**Comment by GammaC0de** [comment]
@akfedux Please email me the PIN code

**Comment by vuolter** [comment]
Fix coming...

**Comment by Burnout5151** [comment]
@vuolter: Has the fix been merged? Can this be closed?

**Comment by akfedux** [comment]
yes
27 maj 2017 13:08 "Burnout5151" <notifications@github.com> napisał(a):

**Comment by GammaC0de** [comment]
👍
