### ISSUE TITLE
Alldebrid doesn't auto-translate links

### ISSUE THREAD

**Issue by redeemer666** [pyload/pyload#2312]
When I download something from a service alldebrid supports (like uploaded.to) it doesn't automatically translate the link to start the download with alldebrid. Moreover, it's a couple of days that i get this error:
 Download failed: Arrow.S04E10.1080p.HDTV.X264-DIMENSION.mkv | 'NoneType' object has no attribute 'user' 
when the download is finished

**Comment by redeemer666** [comment]
Same issue as #2278, at least for the first part

**Comment by GammaC0de** [comment]
#2278 is closed
