### ISSUE TITLE
plugin "ExternalScripts" not saving settings proper

### ISSUE THREAD

**Issue by Web-Eye** [pyload/pyload#2313]
Hello,

I set setting "Execute script concurrently" to "On".
After each pyLoad restart, it's fall back to "Off"

Thanks for Help,
WebEye

PS: I checked the plugins.conf permissions, it's all ok; if I manually edit plugins.conf, it falls back also to "Off" after pyload restart! It looks like, it takes its default settings with each pyload start.

**Comment by GammaC0de** [comment]
\- Stop `pyLoad`
\- Backup your `plugins.conf`
\- Edit, `plugins.conf`:
      find the `Captcha9Kw` section,
 edit the line with "Hoster options" to look excactly like `str hoster_options : "Hoster options" =`
\- Start `pyLoad`
\- Change the settings

See if that helped

**Comment by Web-Eye** [comment]
does not work.
My only workaround is to set the default value in "ExternalScripts.py".

**Comment by GammaC0de** [comment]
Try editing [Captcha9Kw.py#L26](https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/Captcha9Kw.py#L26)
to `("hoster_options", "str" , "Hoster options", ""),`

Then run pyload and restart it afterwards
See if that helps

**Comment by Web-Eye** [comment]
does not work, neither!
But, by the way, I do not understand, why the Captcha hook should interupt the setting saving of ExternalScripts hook?

Anyway, thanks for help...

**Comment by GammaC0de** [comment]
Because there is a bug related to plugins.conf and Captcha9kw, I thought its related

You can either backup then delete `plugins.conf` and hopefully it will help or you can manual edit the the `unlock` settings in `plugins.conf `

**Comment by Web-Eye** [comment]
Deleting `plugin.conf` does not work and, as I mentioned above, manually editing `unlock` setting does not work neither, at every restart of pyload it falls back to 'True'.

However; I changed the default value in `ExternalScripts.py` and hopefully notice the next update od this file...

**Comment by vuolter** [comment]
It's a core bug.
