### ISSUE TITLE
EasyBytez Premium: all downloads fail with error "HTTPRequest instance has no attribute 'cj'"

### ISSUE THREAD

**Issue by darkpella** [pyload/pyload#2314]
Hi, since today (or yesterday evening) all EB premium downloads fail with error "HTTPRequest instance has no attribute 'cj'"

Here below log of one such fail w/ debug mode turned on.

bye

    1	23.01.2016 16:31:08	INFO	Download starts: World.War.Z.2013.Extended.Action.Cut.iTA.ENG.Bluray.1080p.x264-SURRY.part02.rar
    2	23.01.2016 16:31:08	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
    3	23.01.2016 16:31:08	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
    4	23.01.2016 16:31:09	DEBUG	HOSTER EasybytezCom[7108]: Link info: {'status': 2, 'hash': {}, 'name': u'World.War.Z.2013.Extended.Action.Cut.iTA.ENG.Bluray.1080p.x264-SURRY.part02.rar', 'url': u'http://www.easybytez.com/o5a9vfak8ufq', 'pattern': {'S': u'501.0', 'U': u'MB', 'N': u'World.War.Z.2013.Extended.Action.Cut.iTA.ENG.Bluray.1080p.x264-SURRY.part02.rar'}, 'size': 525336576}
    5	23.01.2016 16:31:09	DEBUG	HOSTER EasybytezCom[7108]: Previous link info: {}
    6	23.01.2016 16:31:09	INFO	HOSTER EasybytezCom[7108]: Link name: World.War.Z.2013.Extended.Action.Cut.iTA.ENG.Bluray.1080p.x264-SURRY.part02.rar
    7	23.01.2016 16:31:09	INFO	HOSTER EasybytezCom[7108]: Link size: 501.00 MiB (525336576 bytes)
    8	23.01.2016 16:31:09	INFO	HOSTER EasybytezCom[7108]: Link status: online
    9	23.01.2016 16:31:09	INFO	HOSTER EasybytezCom[7108]: Processing url: http://www.easybytez.com/o5a9vfak8ufq
    10	23.01.2016 16:31:09	INFO	HOSTER EasybytezCom[7108]: Looking for direct download link...
    11	23.01.2016 16:31:09	DEBUG	HOSTER EasybytezCom[7108]: LOAD URL http://www.easybytez.com/o5a9vfak8ufq | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
    12	23.01.2016 16:31:09	DEBUG	HOSTER EasybytezCom[7108]: Plugin version: 0.28
    13	23.01.2016 16:31:09	DEBUG	HOSTER EasybytezCom[7108]: Plugin status: testing
    14	23.01.2016 16:31:09	WARNING	HOSTER EasybytezCom[7108]: Plugin may be unstable
    15	23.01.2016 16:31:09	DEBUG	HOSTER EasybytezCom[7108]: Config option `use_premium` not found, use default `True`
    16	23.01.2016 16:31:09	INFO	ACCOUNT EasybytezCom: Grabbing account info for user `darkpella`...
    17	23.01.2016 16:31:09	DEBUG	ACCOUNT EasybytezCom: LOAD URL http://www.easybytez.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
    18	23.01.2016 16:31:11	DEBUG	ACCOUNT EasybytezCom: Expire date: 25 December 2016
    19	23.01.2016 16:31:11	DEBUG	ACCOUNT EasybytezCom: Valid until: 1482620400.0
    20	23.01.2016 16:31:11	DEBUG	ACCOUNT EasybytezCom: LEECH TRAFFIC PATTERN not found
    21	23.01.2016 16:31:11	DEBUG	ACCOUNT EasybytezCom: Account info for user `darkpella`: {'login': {'timestamp': 1453562969.94247, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1482620400.0, 'login': 'darkpella', 'type': 'EasybytezCom', 'options': {'limitdl': ['0']}}}
    22	23.01.2016 16:31:11	INFO	HOSTER EasybytezCom[7108]: Grabbing link info...
    23	23.01.2016 16:31:11	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
    24	23.01.2016 16:31:11	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
    25	23.01.2016 16:31:11	WARNING	Error calling event handler package_failed: >, (,), PyPackage instance has no attribute '__trunc__'
    26	23.01.2016 16:31:12	WARNING	Download failed: World.War.Z.2013.Extended.Action.Cut.iTA.ENG.Bluray.1080p.x264-SURRY.part02.rar | HTTPRequest instance has no attribute 'cj'
    27	23.01.2016 16:31:12	INFO	Debug Report written to debug_EasybytezCom_23-01-2016_16-31-12.zip
    28	23.01.2016 16:31:12	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
    29	23.01.2016 16:31:12	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: World.War.Z.2013.Extended.Action.Cut.iTA.ENG.Bluray.1080p.x264-SURRY.part02.rar (pid:216)
    30	23.01.2016 16:31:12	INFO	ADDON UnSkipOnFail: No duplicates found
    31	23.01.2016 16:31:12	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
    32	23.01.2016 16:31:12	DEBUG	All downloads processed
    33	23.01.2016 16:31:13	WARNING	Download failed: World.War.Z.2013.Extended.Action.Cut.iTA.ENG.Bluray.1080p.x264-SURRY.part02.rar | 'NoneType' object has no attribute 'id'
    34	23.01.2016 16:31:13	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
    35	23.01.2016 16:31:13	DEBUG	All downloads processed

**Comment by GammaC0de** [comment]
Isn't it the same as https://github.com/pyload/pyload/issues/2265?

**Comment by darkpella** [comment]
@GammaC0de seems pretty much the same, but it looked like it had disappeared for a week or so, as most download would complete successfully 

Now again every download fails.... 

Let me know whether I can provide you with some more information

**Comment by GammaC0de** [comment]
Have you re-adeed https://github.com/pyload/pyload/issues/2265#issuecomment-169741240?

**Comment by darkpella** [comment]
@GammaC0de Looks like I forgot to..... xO

Every thing is working fine now.

Thanks

darkpella
