### ISSUE TITLE
global name 'pyfile' is not defined

### ISSUE THREAD

**Issue by ms235** [pyload/pyload#2315]
Hi at all sorry I'm living in Germany so my Englisch isn't the best at all.... 
Since a long time I'm using Pyload ... since aprox. two weeks I have the error message "global name 'pyfile' is not defined" after I ad a DLC file.
Is there anybody who can help me? 
I tried a restart, update but it doen't help.

**Comment by GammaC0de** [comment]
@ms235 Can you try https://github.com/pyload/pyload/issues/2265#issuecomment-169741240 and see if it helps?

**Comment by GammaC0de** [comment]
@ms235 Can you confirm if https://github.com/pyload/pyload/commit/cad33cec0ca6d19c66beaef2746f30630ff98102 resolves this issue?

**Comment by ms235** [comment]
A reconfiguration solves the issue! After That the program works Fine again!
