### ISSUE TITLE
i am searching for hook name i can´t remember  

### ISSUE THREAD

**Issue by must4rd** [pyload/pyload#2316]
Hey there, 
just because pyload.org is still offline and i am sure  i found the name of the hook in this forum half a year ago, i need you to help me out.
i am searching for a hook which automatically filtered links in order to get only the links of one defined  hoster. 
i have a huge dlc with >200 links for 4 different hoster and i would like to filter it.
Any one who can help?

**Comment by GammaC0de** [comment]
I can't help with the hook name but you can use http://dcrypt.it/ to decrypt the dlc file and then you can get the desired links.

**Comment by must4rd** [comment]
after clicking through the hole hook library i found it.... the name was "JustPremium"...
i added UploadedTO as hoster and it worked for me.
but thanks for your try ;-)
