### ISSUE TITLE
Captcha9kw stopped working

### ISSUE THREAD

**Issue by fthiesse** [pyload/pyload#2317]
It just retries (without actually trying) and then stops:

27.01.2016 20:47:46 INFO      Decrypting starts: http://example-url
27.01.2016 20:47:54 INFO      Retrying http://example-url
27.01.2016 20:47:54 INFO      Decrypting starts: http://example-url
27.01.2016 20:48:01 INFO      Retrying http://example-url
27.01.2016 20:48:01 INFO      Decrypting starts: http://example-url
27.01.2016 20:48:09 INFO      Retrying http://example-url
27.01.2016 20:48:09 INFO      Decrypting starts: http://example-url
27.01.2016 20:48:14 ERROR     Decrypting failed: http://example-url | Max retries reache

Tried three different versions, somehow pyload ships with two, 9kw site itself offers another version.

Also found this in the log:
./Logs/log.txt.5:09.01.2016 18:51:51 INFO      ADDON UpdateManager: Removed blacklisted plugin: HOOKS Captcha9kw

**Comment by GammaC0de** [comment]
@fthiesse I've tested the Captcha9Kw plugin and it works fine for me.
Try setting `Don't use if client is connected` to off.

**Comment by fthiesse** [comment]
You're right, it's not the 9kw plugin. I've used another link and there it worked. The original one was a serienjunkies.org link, could the decrypter have an issue?

**Comment by GammaC0de** [comment]
@fthiesse Currently serienjunkies.org plugin has issues since it started to use Recaptcha v2 which is not supported (yet?) in pyload.
Also since serienjunkies.org is a warez site, it is not supported by pyLoad.
