### ISSUE TITLE
ExtractArchive not working

### ISSUE THREAD

**Issue by TrippleP** [pyload/pyload#2318]
Hello,

I have a fresh install of Pyload but the ExtractArchive seems not to work.

unrar is installed:
ipkg list_installed | grep unrar
unrar - 5.0.12-1 - unrar is an application that can decompress files and archives created using the RAR compression scheme

The only message I see in the Log for AutoExtract is:

70	?	?	28.01.2016 07:54:06 INFO ADDON UpdateManager: All plugins are up to date!
69	?	?	28.01.2016 07:54:05 INFO ADDON UpdateManager: pyLoad is up to date!
68	?	?	28.01.2016 07:54:05 INFO ADDON ExtractArchive: Check package: test

and

28.01.2016 07:54:02 INFO Aktivierte Plugins: AntiStandby, ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing

When I download an archive:

LOG:

1129	?	?	26.01.2016 09:07:34 INFO Package finished: test
1128	?	?	26.01.2016 09:07:34 INFO Download finished: Fanatec_64_driver_231.zip
1127	?	?	26.01.2016 09:07:34 INFO HOSTER BasePlugin[149]: File is OK
1126	?	?	26.01.2016 09:07:34 INFO HOSTER BasePlugin[149]: Checking download...
1125	?	?	26.01.2016 09:07:33 INFO HOSTER BasePlugin[149]: File saved
1124	?	?	26.01.2016 09:07:30 INFO HOSTER BasePlugin[149]: Processing url: http://www.fanatec.com/download/Fana...driver_231.zip
1123	?	?	26.01.2016 09:07:30 INFO HOSTER BasePlugin[149]: Link status: eingereiht
1122	?	?	26.01.2016 09:07:30 INFO HOSTER BasePlugin[149]: Link size: N/D
1121	?	?	26.01.2016 09:07:30 INFO HOSTER BasePlugin[149]: Link name: Fanatec_64_driver_231.zip
1120	?	?	26.01.2016 09:07:30 INFO HOSTER BasePlugin[149]: Grabbing link info...

pyload.conf:

ExtractArchive - "ExtractArchive":
bool deltotrash : "Move to trash instead delete" = False
bool repair : "Repair broken archives (RAR required)" = False
bool usepasswordfile : "Use password file" = True
bool recursive : "Extract archives in archives" = True
bool keepbroken : "Try to extract broken archives" = False
bool subfolder : "Create subfolder for each package" = True
folder destination : "Extract files to folder" = /volume1/tmp
bool activated : "Activated" = True
int priority : "Process priority" = 0
str excludefiles : "Don't extract the following files" = *.nfo,*.DS_Store,index.dat,thumb.db
str extensions : "Extract archives ending with extension" = 7z,bz2,bzip2,gz,gzip,lha,lzh,lzma,rar,tar,
file passwordfile : "Password file" = ./unrar_passwords.txt
bool fullpath : "Extract with full paths" = True
bool waitall : "Run after all downloads was processed" = False
bool delete : "Delete archive after extraction" = True
bool overwrite : "Overwrite files" = True

I hope you can help.

Thanks
Patrick

**Comment by b2un0** [comment]
see #2289 and #2250 and so many other issues ;)

**Comment by TrippleP** [comment]
Thanks, but all of them refer to error messages when extracting but actually it seems the PlugIn does not even try to extract in my case.

I could not find a single error message

**Comment by b2un0** [comment]
read #2289, thats the same - no output message because the ``ExtractArchive`` is still broken
https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExtractArchive.py#L102

**Comment by TrippleP** [comment]
Is there an old codebase I could use or an ETA on a Fix?

**Comment by J-Ha** [comment]
https://github.com/pyload/pyload/pull/2290

**Comment by vuolter** [comment]
@TrippleP I hope to complete the new plugin within next month. The truth is I need at least 2 hours to finish it and in the last weeks I was able to dedicate to the entire project about 15 minutes... at all. O_O

**Comment by Jonn3y** [comment]
Any news yet? 

Have the same problem: pyLoad doesn't try to extract :(

**Comment by vuolter** [comment]
@Jonn3y Not yet. Plugin is still incomplete. :(

**Comment by Jonn3y** [comment]
oh no :( Does noone work on this problem? This trouble should get the highest priority! 
I don't want to use jDownloader on Linux!

**Comment by GammaC0de** [comment]
@Jonn3y @vuolter *is* working on this but he is also working on few other major bugs (like multi-account plugins), that's why it takes so long.
Hopefully @vuolter will finish it soon.

**Comment by Jonn3y** [comment]
Ah okay, thanks for information. Hope it too!
