### ISSUE TITLE
pycurl error 6: Couldn't resolve host 'uploaded.net'

### ISSUE THREAD

**Issue by mcmaxl** [pyload/pyload#2319]
Since yesterday pyload can't login to uploaded.net account:

> 523	29.01.2016 15:18:06	INFO	pyLoad is up and running
524	29.01.2016 15:18:08	INFO	Download starts: http://ul.to/rl9ec63z
525	29.01.2016 15:18:08	WARNING	HOSTER UploadedTo[37]: Plugin may be unstable
526	29.01.2016 15:18:08	INFO	ACCOUNT UploadedTo: Grabbing account info for user `7332354`...
527	29.01.2016 15:18:28	ERROR	ADDON SJ: Error executing periodical task: global name 'self' is not defined
528	29.01.2016 15:18:28	INFO	ADDON RestartFailed: Restarting all failed downloads...
529	29.01.2016 15:18:28	WARNING	ACCOUNT UploadedTo: Error loading info for user `7332354` | (6, "Couldn't resolve host 'uploaded.net'")
530	29.01.2016 15:18:28	INFO	HOSTER UploadedTo[37]: Grabbing link info...
531	29.01.2016 15:18:30	INFO	Download starts: http://ul.to/rl9ec63z
532	29.01.2016 15:18:30	WARNING	HOSTER UploadedTo[37]: Plugin may be unstable
533	29.01.2016 15:18:30	INFO	ACCOUNT UploadedTo: Grabbing account info for user `7332354`...
534	29.01.2016 15:18:48	ERROR	pycurl error 6: Couldn't resolve host 'uploaded.net'
535	29.01.2016 15:18:48	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: http://ul.to/rl9ec63z (pid:22)
536	29.01.2016 15:18:48	INFO	ADDON UnSkipOnFail: No duplicates found
537	29.01.2016 15:18:50	WARNING	ACCOUNT UploadedTo: Error loading info for user `7332354` | (6, "Couldn't resolve host 'uploaded.net'")
538	29.01.2016 15:18:50	WARNING	Download failed: http://ul.to/rl9ec63z | 'NoneType' object has no attribute 'user'
539	29.01.2016 15:18:50	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: http://ul.to/rl9ec63z (pid:22)
540	29.01.2016 15:18:50	INFO	ADDON UnSkipOnFail: No duplicates found

any ideas?

**Comment by GammaC0de** [comment]
@mcmaxl Works fine from here, please check your internet connection.
