### ISSUE TITLE
Crash on activated share-online Account

### ISSUE THREAD

**Issue by franzaut** [pyload/pyload#2320]
29.01.2016 17:16:23 INFO      Activating Accounts...
29.01.2016 17:16:23 ERROR     Error importing ShareonlineBiz: cannot import name set_cookie
---Pyload Stop---

readd Account data
29.01.2016 17:22:19 ERROR     Error importing ShareonlineBiz: cannot import name set_cookie

**Comment by GammaC0de** [comment]
DEBUG log please

**Comment by franzaut** [comment]
30.01.2016` 06:43:37 INFO      starte pyLoad 0.4.9
30.01.2016 06:43:37 INFO      Benutze Home-Verzeichnis: /franz/.pyload
30.01.2016 06:43:37 DEBUG     Remote activated: False
30.01.2016 06:43:38 DEBUG     created index of plugins
30.01.2016 06:43:38 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
30.01.2016 06:43:38 DEBUG     Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
30.01.2016 06:43:38 DEBUG     Redirected import module.plugins.internal.misc -> userplugins.internal.misc
30.01.2016 06:43:38 WARNING   Konnte ExternalScripts nicht aktivieren
30.01.2016 06:43:38 WARNING   Konnte UpdateManager nicht aktivieren
30.01.2016 06:43:38 INFO      Aktivierte Plugins: Checksum, ClickNLoad, LinkdecrypterComHook, UnSkipOnFail, UserAgentSwitcher
30.01.2016 06:43:38 INFO      Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, ImageTyperz, JustPremium, LogMarker, MergeFiles, MultiHome, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify
30.01.2016 06:43:38 INFO      Downloadzeit: True
30.01.2016 06:43:38 INFO      Freier Speicher: 798.57 GiBGB
30.01.2016 06:43:38 INFO      Aktiviere Accounts...
30.01.2016 06:43:38 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
30.01.2016 06:43:38 INFO      Starting threaded SSL webserver: 127.0.0.1:7789
30.01.2016 06:43:38 ERROR     Error importing ShareonlineBiz: cannot import name set_coo

**Comment by GammaC0de** [comment]
@franzaut What version is your `accounts/ShareonlineBiz.py`?

**Comment by franzaut** [comment]
@GammaC0de Version 0.44

**Comment by GammaC0de** [comment]
And what is the version of `internal/misc.py`?
Does your `UpdateManager` plugin activated?

**Comment by franzaut** [comment]
@GammaC0de  internal/misc.py Version 0.26
UpdateManager = activated

**Comment by GammaC0de** [comment]
@franzaut Your log miss the most important part which is the exception information...

**Comment by franzaut** [comment]
Full Log:
30.01.2016 17:43:20 INFO      Starting pyLoad 0.4.9
30.01.2016 17:43:20 INFO      Using home directory: /franz/.pyload
30.01.2016 17:43:20 DEBUG     Remote activated: False
30.01.2016 17:43:21 DEBUG     created index of plugins
30.01.2016 17:43:21 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
30.01.2016 17:43:21 DEBUG     Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
30.01.2016 17:43:21 DEBUG     Redirected import module.plugins.internal.misc -> userplugins.internal.misc
30.01.2016 17:43:21 WARNING   Failed activating ExternalScripts
30.01.2016 17:43:21 WARNING   Failed activating UpdateManager
30.01.2016 17:43:21 INFO      Activated plugins: Checksum, ClickNLoad, LinkdecrypterComHook, UnSkipOnFail, UserAgentSwitcher
30.01.2016 17:43:21 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, ImageTyperz, JustPremium, LogMarker, MergeFiles, MultiHome, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify
30.01.2016 17:43:21 INFO      Downloadtime: True
30.01.2016 17:43:21 INFO      Starting threaded SSL webserver: 127.0.0.1:7789
30.01.2016 17:43:21 INFO      Free space: 798.57 GiB
30.01.2016 17:43:21 INFO      Activating Accounts...
30.01.2016 17:43:21 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
30.01.2016 17:43:21 ERROR     Error importing ShareonlineBiz: cannot import name set_cookie

**Comment by GammaC0de** [comment]
Try updating your `userplugins` :
* Stop `pyLoad`.
* Get the stable package from https://github.com/pyload/pyload/archive/stable.zip
* Extract all the subfolders in `<stable.zip>/module/plugins` to your `userplugins` directory.
* Start `pyLoad`.

**Comment by franzaut** [comment]
nice this works @GammaC0de 
Thank you
