### ISSUE TITLE
[Question] Get variable __ type __ of plugin for web template

### ISSUE THREAD

**Issue by sodd** [pyload/pyload#2321]
Is it possible to get value of __ type __ of plugin in web template? I want to get sorted list of all plugins by their type.

**Comment by GammaC0de** [comment]
One could write a hook plugin with a function that returns this information and decleare it as `@Expose`
and then call PYLOAD.call() to call this function from the web template.

**Comment by sodd** [comment]
How can I call HOOK.funtion from template? I tried `PYLOAD.call(PYLOAD.ServiceCall("PluginNAME","FUNCTION"))`
but PYLOAD doesnt have this method

**Comment by GammaC0de** [comment]
```
    class ServiceCall(object):
        def __init__(self, plugin=None, func=None, arguments=None, parseArguments=None,):
            self.plugin = plugin
            self.func = func
            self.arguments = arguments
            self.parseArguments = parseArguments

    print PYLOAD.call(ServiceCall("UpdateManager", "update_plugins"))
````

**Comment by sodd** [comment]
Yeh problem is the PYLOAD.call return __str__ but nvm i solved it by __ast.literal_eval__
I have what I want, btw thx for tips but right now I another problem with javascript and css probably.
I would like something like in the picture:
http://www.imgshark.org/images/Menu.png
But i don't know how can i get more then one plugin-menu list.

**Comment by sodd** [comment]
Yeh problem is the PYLOAD.call return __str__ but nvm i solved it by __ast.literal_eval__
I have what I want, btw thx for tips but right now I another problem with javascript and css probably.
I would like something like in the picture:
http://www.imgshark.org/images/Menu.png
But i don't know how can i get more then one plugin-menu list.

**Comment by GammaC0de** [comment]
:+1: 

Unfortunately, html/css/javascript is not my strong side, maybe someone else can help
