### ISSUE TITLE
[Easybytez] invalid distance too far back

### ISSUE THREAD

**Issue by erse80** [pyload/pyload#2322]
Any idea?

31.01.2016 20:11:39 INFO      HOSTER EasybytezCom[6847]: Grabbing link info...
31.01.2016 20:11:39 DEBUG     HOSTER EasybytezCom[6847]: Link info: {'status': 2, 'hash': {}, 'name': u'NeTriS2.part28.rar', 'url': u'http://www.easybytez.com/uuv988uegdaj/NeTriS2.part28.rar', 'pattern': {'S': u'102.0', 'U': u'MB', 'N': u'NeTriS2.part28.rar'}, 'size': 106954752}
31.01.2016 20:11:39 DEBUG     HOSTER EasybytezCom[6847]: Previous link info: {}
31.01.2016 20:11:39 INFO      HOSTER EasybytezCom[6847]: Link name: NeTriS2.part28.rar
31.01.2016 20:11:39 INFO      HOSTER EasybytezCom[6847]: Link size: 102.00 MiB (106954752 bytes)
31.01.2016 20:11:39 INFO      HOSTER EasybytezCom[6847]: Link status: online
31.01.2016 20:11:39 INFO      HOSTER EasybytezCom[6847]: Processing url: http://www.easybytez.com/uuv988uegdaj/NeTriS2.part28.rar
31.01.2016 20:11:39 INFO      HOSTER EasybytezCom[6847]: Looking for direct download link...
31.01.2016 20:11:39 DEBUG     HOSTER EasybytezCom[6847]: LOAD URL http://www.easybytez.com/uuv988uegdaj/NeTriS2.part28.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
31.01.2016 20:11:40 INFO      HOSTER EasybytezCom[6847]: Direct download link detected
31.01.2016 20:11:40 INFO      HOSTER EasybytezCom[6847]: Downloading file...
31.01.2016 20:11:40 DEBUG     HOSTER EasybytezCom[6847]: DOWNLOAD URL http://www.easybytez.com/uuv988uegdaj/NeTriS2.part28.rar | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
31.01.2016 20:11:40 DEBUG     Resume File from 291
31.01.2016 20:11:40 DEBUG     Chunked resume with range 80-160
31.01.2016 20:11:40 DEBUG     Chunked resume with range 160-
31.01.2016 20:11:40 DEBUG     Chunk 1 failed: (33, "HTTP server doesn't seem to support byte ranges. Cannot resume.")
31.01.2016 20:11:40 DEBUG     Chunk 2 failed: (61, 'Error while processing content unencoding: invalid stored block lengths')
31.01.2016 20:11:40 DEBUG     Chunk 3 failed: (61, 'Error while processing content unencoding: invalid distance too far back')
31.01.2016 20:11:40 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
31.01.2016 20:11:40 DEBUG     pycurl exception 61: Error while processing content unencoding: invalid distance too far back
31.01.2016 20:11:40 ERROR     pycurl error 61: Error while processing content unencoding: invalid distance too far back
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/root/.pyload/userplugins/internal/Base.py", line 293, in preprocessing
    return self._process(*args, **kwargs)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/root/.pyload/userplugins/internal/SimpleHoster.py", line 287, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 302, in download
    disposition, resume, chunks)
  File "/root/.pyload/userplugins/internal/Hoster.py", line 233, in _download
    self.pyfile.setProgress, disposition)
  File "/usr/share/pyload/module/network/Browser.py", line 88, in httpDownload
    name = self.dl.download(chunks, resume)
  File "/usr/share/pyload/module/network/HTTPDownload.py", line 129, in download
    self._download(chunks, resume)
  File "/usr/share/pyload/module/network/HTTPDownload.py", line 260, in _download
    raise ex
error: (61, 'Error while processing content unencoding: invalid distance too far back')

**Comment by GammaC0de** [comment]
@erse80 Is it free or premium download?
What OS?

**Comment by erse80** [comment]
premium 
debian 8 64bit

**Comment by GammaC0de** [comment]
Does it happen on every EasybytezCom download?

I will need an account for testing

**Comment by erse80** [comment]
Your email it's nitzo2001 <at> yahoo <dot> com ?
only some links have the problem, of course with a browser the links work

**Comment by GammaC0de** [comment]
@erse80 Correct.
Does a link that does not work, will not work every time?

**Comment by GammaC0de** [comment]
@erse80 This worked fine on my machine.
It seems like a bug in pycurl..

Try updating your pycurl:
`sudo apt-get  update && sudo apt-get install python-pycurl`

**Comment by erse80** [comment]
no update avaiable
pycurl it's last version

root@vpn3:/tmp# dpkg -l | grep python-pycurl
ii  python-pycurl                        7.19.5-3
  amd64        Python bindings to libcurl
root@vpn3:/tmp#

you what version you have?

**Comment by GammaC0de** [comment]
windows:
```
>>> import pycurl
>>> pycurl.version
'PycURL/7.19.5.1 libcurl/7.37.0 WinSSL zlib/1.2.8'
```
Ubuntu 14:
```
>>> import pycurl
>>> pycurl.version
'PycURL/7.21.5 libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3'
```

Both worked

**Comment by vuolter** [comment]
Not related to pyload.

**Comment by erse80** [comment]
the solution for others with the same problem:

it's a bug of 
libcurl3
libcurl3-gnutls

it is necessary upgrade from 7.38.0-4+deb8u2 to 7.38.0-4+deb8u3 

tnx
