### ISSUE TITLE
[Easybytez] -  'ascii' codec can't encode character u'\xe8'

### ISSUE THREAD

**Issue by erse80** [pyload/pyload#2323]
encode problem

31.01.2016 21:10:16 WARNING   Download failed: http://www.easybytez.com/plnb3im4qm0i/Dallas.030.[02x01].Cos'è.successo.al.piccolo.John.1°.Parte.ITA.By.Gatto_7.avi | 'ascii' codec can't encode character u'\xe8' in position 61: ordinal not in range(128)

**Comment by sschwart** [comment]
There is a solution in the post #2286. There are one ligne to add in the beginning of the file and an other to modified. 
In misc.py (/usr/share/pyload/module/plugins/internal/):
Add after all python import 
```python 
import unicodedata
```
And, in `def fixurl` (line 456), modify:
```python
url = html_unescape(decode(url).decode('unicode-escape'))
```
To:
```python
url = html_unescape(unicodedata.normalize('NFKD', decode(url)).encode('ascii','ignore').decode('unicode-escape'))
```
After the modification, you need to restart your pyload to take into account the modification.
It works great for me ;)

**Comment by zephura** [comment]
Hello :)

This patch does not _"solve"_ the issue but it allow to _"manage"_ it .
To be clear, the file will not have the special characters, they will be replaced by their _"natural equivalent"_ "è" into "e" is a good example.

thanks :+1:

**Comment by sschwart** [comment]
Yes, you're totally right :)

This was the only way I find to deal with it. Pyload is built around basic ascii character (English language).  So, for the moment, it’s the best way. Otherwise, you need to change every encoding: ascii to utf-8 for example (so, lot of files are impacted) ^^

You're welcome :)

**Comment by Velociraptor85** [comment]
duplicate from https://github.com/pyload/pyload/issues/2286

Please close @GammaC0de @vuolter @erse80

**Comment by efferre79** [comment]
Ciao amico,

Ho  trovato  un po' di informazioni e ho pensato che potrebbe essere interessante per voi, si  prega di  leggere di più  a <http://clemente.ajlconsultingltd.com/kvd>

Stai bene, FBIO ROSSI

**Comment by efferre79** [comment]
Caro! 


Recentemente ho  incontrato  alcune persone nuove che  mi hanno mostrato qualcosa di  veramente cool, ti prego  di dare un'occhiata <http://lory.opesnetwork.com/fynb>

In fede, FBIO ROSSI

**Comment by efferre79** [comment]
Ciao! 


Ho pensato che ti avrebbe  fatto piacere vedere  questa roba che  ho trovato per caso, sembra  così eccitante  ed insolita, ti prego di dare un'occhiata  qui <http://clever.socialshoot.ca/yff/84>


Velocemente, FBIO ROSSI

**Comment by efferre79** [comment]
Ciao amico,

Volevo  solo dirti ciao e farti  vedere  qualcosa di veramente sorprendente, questa roba ha cambiato la  mia giornata! Ti  prego di dare un'occhiata <http://up.thinkhrlive.com/ojy/653>

Cari saluti, FBIO ROSSI
