### ISSUE TITLE
hooks/XFileSharing.py and hosters/XFileSharing.py interfer with each others configs

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#2324]
I was a bit disturbed that my config options for the `hooks/XFileSharing.py` plugin are not saved properly. A bit of research turned up that, when loading up pyload, `ConfigParser.addPluginConfig` is called for each plugin. This method will erase config options that are not defined by the plugin. Now, if `hosters/XFileSharing.py` is found first (which it usually is), some important config options of `hooks/XFileSharing.py` will be erased (and later reinstated with their default values when `ConfigParser.addPluginConfig` is called for the `hooks/XFileSharing.py` plugin). Thus, essentially, each time pyload starts, it overwrites `hooks/XFileSharing.py`'s config with the defaults.

**Comment by vuolter** [comment]
XFileSharing's hook stuff will be handle by BasePlugin... Updates are coming. ;)

**Comment by GammaC0de** [comment]
@vuolter :+1: I was thinking to suggest that :)
