### ISSUE TITLE
Uploaded.to or pycurl error

### ISSUE THREAD

**Issue by mcmaxl** [pyload/pyload#2326]
`
559	02.02.2016 08:17:41	INFO	HOSTER UploadedTo[5]: Link size: 1719355310 bytes
560	02.02.2016 08:17:41	INFO	HOSTER UploadedTo[5]: Link status: online
561	02.02.2016 08:17:41	INFO	HOSTER UploadedTo[5]: Looking for direct download link...
562	02.02.2016 08:17:42	INFO	HOSTER UploadedTo[6]: Link name: TBS.SC8-SHULiBAN.rar
563	02.02.2016 08:17:42	INFO	HOSTER UploadedTo[6]: Link size: 840650948 bytes
564	02.02.2016 08:17:42	INFO	HOSTER UploadedTo[6]: Link status: online
565	02.02.2016 08:17:42	INFO	HOSTER UploadedTo[6]: Looking for direct download link...
566	02.02.2016 08:17:44	INFO	HOSTER UploadedTo[5]: Link name: TMFU.B18-SHULiBAN.rar
567	02.02.2016 08:17:44	INFO	HOSTER UploadedTo[5]: Link size: 1719355310 bytes
568	02.02.2016 08:17:44	INFO	HOSTER UploadedTo[5]: Link status: online
569	02.02.2016 08:17:44	INFO	HOSTER UploadedTo[5]: Looking for direct download link...
570	02.02.2016 08:17:44	ERROR	pycurl error 0: ('cannot invoke setopt() - perform() is currently running',)
571	02.02.2016 08:17:45	INFO	Download starts: TBS.SC8-SHULiBAN.rar
572	02.02.2016 08:17:45	WARNING	HOSTER UploadedTo[6]: Plugin may be unstable
573	02.02.2016 08:17:45	INFO	ACCOUNT UploadedTo: Grabbing account info for user `7332354`...
574	02.02.2016 08:17:45	INFO	HOSTER UploadedTo[6]: Grabbing link info...
575	02.02.2016 08:17:46	WARNING	Download failed: TMFU.B18-SHULiBAN.rar | 'NoneType' object has no attribute 'id'
576	02.02.2016 08:17:47	WARNING	Download failed: TBS.SC8-SHULiBAN.rar | HTTPRequest instance has no attribute 'cj'
577	02.02.2016 08:17:50	WARNING	Download failed: TBS.SC8-SHULiBAN.rar | 'NoneType' object has no attribute 'id'
578	02.02.2016 09:00:04	INFO	shutting down...
579	02.02.2016 09:00:04	INFO	Received Quit signal
580	02.02.2016 09:00:13	INFO	starte pyLoad 0.4.9
581	02.02.2016 09:00:13	INFO	Benutze Home-Verzeichnis: /opt/pyload-config
582	02.02.2016 09:00:14	INFO	Aktivierte Plugins: BypassCaptcha, Captcha_9kw, EpisodeMover, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterComHook, MovieMover, RestartFailed, XFileSharing
583	02.02.2016 09:00:14	INFO	Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, Captcha9Kw, CaptchaBrotherhood, Checksum, ClickNLoad, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HDAreaOrg, HotFolder, IRCInterface, JustPremium, LogMarker, MergeFiles, MultiHome, PushExtension, SJ, SkipRev, TransmissionRPC, UnSkipOnFail, UpdateManager, UserAgentSwitcher, WindowsPhoneNotify, XFileSharingPro, XMPPInterface
584	02.02.2016 09:00:14	INFO	Downloadzeit: True
585	02.02.2016 09:00:14	INFO	Freier Speicher: 2.28 TiBGB
586	02.02.2016 09:00:15	INFO	Starting threaded webserver: 0.0.0.0:8000
587	02.02.2016 09:00:15	INFO	Activating Accounts...
588	02.02.2016 09:00:15	INFO	ACCOUNT UploadedTo: Adding user `7332354`...
589	02.02.2016 09:00:15	INFO	ACCOUNT UploadedTo: Login user `7332354`...
590	02.02.2016 09:00:20	INFO	ACCOUNT UploadedTo: Grabbing account info for user `7332354`...
591	02.02.2016 09:00:20	INFO	Activating Plugins...
592	02.02.2016 09:00:20	INFO	MovieMover: No movies in "/volume1/pyload_downloads" to process.
`

**Comment by mcmaxl** [comment]
Apologies for bad formatting, will do properly when at proper computer, not iPad...

**Comment by GammaC0de** [comment]
@mcmaxl 
`HTTPRequest instance has no attribute 'cj'`

This is same as #2314 and should have been fixed already.

Please try updating your `userplugins`:
* Get the stable package from https://github.com/pyload/pyload/archive/stable.zip
* Extract all the **subfolders** in `<stable.zip>/module/plugins` to your `userplugins` directory.

**Comment by sraedler** [comment]
no feedback, so done, because of an old problem?
