### ISSUE TITLE
Serienjunkies Decrypting failed Max retries reached

### ISSUE THREAD

**Issue by justroot1337** [pyload/pyload#2331]
Hello,

i got problems with my pyLoad.
Every tries to decrypt serienjunkies Links fails.
i have attached the Logfile.

[pyload.txt](https://github.com/pyload/pyload/files/116338/pyload.txt)

Hopy someone can help me.
Beste regards
just.RooT

**Comment by vuolter** [comment]
I'm sorry but this plugin is not officially supported by the team because serienjunkies is out of our plugin politicy.

**Comment by b2un0** [comment]
see #2268

**Comment by Velociraptor85** [comment]
@justroot1337 check https://github.com/Gutz-Pilz/pyLoad-stuff and close the issue please =)
