### ISSUE TITLE
[Question] [XFSHoster] captcha and then wait or wait and then captcha?

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2333]
I have a question about `XFSHoster`:
[XFSHoster.py#L207](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/XFSHoster.py#L207) 
Currently, using free download, if `XFSHoster` sees a page with both captcha and a delay, it will ask for the captcha first and then will do the wait (filejoker.net for example).

Is there any reason not to wait first and then ask for captcha? 
I think its better and will also save captcha credits

Correct me if I'm wrong

**Comment by vuolter** [comment]
In the meanwhile you're entering the captcha, the wait time elapse, so the wait func will stop the download for a lesser interval.

**Comment by GammaC0de** [comment]
:+1: a-ha thanks
