### ISSUE TITLE
pyLoad Bookmarklet - Add file to queue - Set download name

### ISSUE THREAD

**Issue by Ryan747800B** [pyload/pyload#2335]
Hi, given the script below is it possible to add a popup to choose from time to time the download name instead of using the same name (see `name="YOUR_DOWNLOAD_NAME"`) everytime?
Script is from http://peacecopathe.free.fr/peacecoFile/upload/pyload_BookMarklet_v2_min.js , so it isn't English but I'll translate it.

`javascript:function filtreAuto(){var e=[];e["aucun"]="aucun";e["uptobox"]="http://uptobox.com/";e["rapidshare"]="http://rapidshare.com/";e["depositfiles"]="http://depositfiles.com/";e["filefactory"]="http://www.filefactory.com/";e["uploaded"]="http://ul.to/";e["filetobox"]="http://filetobox.com/download.php?uid";return e}function bookmarklet(){var e=document.createElement("div");url=filterUrl();e.innerHTML='<h1>URL</h1><input type="checkbox" name="checkboxUrl" id="'+url+'" value="checkbox0"><label for="checkbox0"><a href="'+url+'">'+url+"</a></label><br />";var t=document.createElement("div");var n=document.createElement("h2");n.setAttribute("id","Filtrer les liens par mots clÃ©:");t.appendChild(n);var r=document.createElement("input");r.setAttribute("id","searchInput");r.setAttribute("name","searchInput");r.setAttribute("type","text");r.setAttribute("placeholder","Filtre personnaliser...");t.appendChild(r);t.innerHTML=t.innerHTML+" ou Filtre Auto: ";var i=document.createElement("select");i.setAttribute("id","searchAuto");i.onchange=function(){win.document.getElementById("searchInput").value=""};filtre=filtreAuto();for(var s in filtre){var o=document.createElement("option");o.value=filtre[s];o.text=s;i.appendChild(o)}t.appendChild(i);var u=document.createElement("button");u.onclick=function(){findLinks()};u.innerHTML="search";t.appendChild(u);var a=document.createElement("button");a.setAttribute("id","cocher");a.onclick=function(){linksCheck()};a.innerHTML="Tout cocher";t.appendChild(a);var f=document.createElement("button");f.setAttribute("id","pyLoad");f.onclick=function(){toPyload()};f.innerHTML="Envoi Ã  pyLoad";t.appendChild(f);var l=document.createElement("div");l.setAttribute("id","divList");win.document.body.appendChild(e);win.document.body.appendChild(t);win.document.body.appendChild(l);findLinks()}function linksCheck(){var e=win.document.getElementById("cocher");e.innerHTML=="Tout cocher"?e.innerHTML="Tout dÃ©cocher":e.innerHTML="Tout cocher";var t=win.document.getElementById("conteneur").firstChild;while(t!=null){if(t.getAttribute("type")=="checkbox"){test=e.innerHTML=="Tout cocher"?false:true;win.document.getElementsByName("checkboxUrl")[0].checked=test;win.document.getElementById(t.getAttribute("id")).checked=test}t=t.nextSibling}return false}function filterUrl(){url=winx.document.URL;if(url.lastIndexOf("youtube")!=-1){g=new RegExp("v=.{11}");idVideo=g.exec(url);urlYoutube="http://www.youtube.com/watch?"+idVideo;url=urlYoutube}return url}function findLinks(){win.document.getElementById("cocher").innerHTML="Tout cocher";var e=win.document.getElementById("searchAuto").value;var t=win.document.getElementById("searchInput").value;title="<h2>Tous les liens "+t+":</h2>";if(!t){if(e=="aucun"){t="";title="<h2>Pas de filtre:</h2>"}else{t=e;title="<h2>Filtre des liens :"+t+"</h2>"}}else{win.document.getElementById("searchAuto").value="aucun"}texte=title+'<div id="conteneur">';for(var n=0;n<list_Links.length;n++){list_Links[n].lastIndexOf(t)!=-1?texte+='<input type="checkbox" name="checkbox'+n+'" id="'+list_Links[n]+'" value="checkbox'+n+'"><label for="checkbox'+n+'"><a href="'+list_Links[n]+'">'+list_Links[n]+"</a></label><br />":""}var r=win.document.getElementById("divList");r.innerHTML=texte+"</div>"}function createListLinks(){list_Links=[];for(var e=winx.document.links.length-1,t;t=winx.document.links[e];e--){if(!t.href.match(/^(javascript:|data:)/)){lien=t.href;list_Links.push(lien)}}return list_Links}function toPyload(){list_Pyload=[];var e=win.document.getElementsByName("checkboxUrl")[0];e.checked?list_Pyload.push(e.id):"";var t=win.document.getElementById("conteneur").firstChild;while(t!=null){if(t.getAttribute("type")=="checkbox"){t.checked?list_Pyload.push(t.getAttribute("id")):""}t=t.nextSibling}if(list_Pyload==""){return false}jLinks=JSON.stringify(list_Pyload);urlx='http://YOUR_USERNAME:YOUR_PASSWORD@YOUR_IP:YOUR_PORT/api/addPackage?name="YOUR_DOWNLOAD_NAME"&links='+jLinks;winz=window.open(urlx,"","resizable=no, location=no, width=100, height=100, menubar=no, status=no, scrollbars=no, menubar=no");setTimeout("winz.close()",50);win.close()}winx=window;win=window.open("","_blank","width=800,height=600,scrollbars,resizable,menubar");list_Links=createListLinks();bookmarklet()`

**Comment by vuolter** [comment]
The script you posted is minified! It's a joke?! XD
I did not well understand the request. :S
Please, explain.

**Comment by Ryan747800B** [comment]
No, no its' not a joke; I found it searching for pyLoad bookmarklet. what I want to do is given a webpage for example this https://www.kali.org/downloads/, to add directly to payload queue by clicking the download link without copy it, login to pyLoad webserver, paste it to queue, choose the download name and the begin the download. Simply click and go. This script should (I'm not sure) works but it adds the distro to the queue with the same name (name="YOUR_DOWNLOAD_NAME").

**Comment by vuolter** [comment]
Okay, that's an interesting idea, a more simple alternative to write a whole plugin browser (so, I like it!).
Unfortunately is not a priority right now, but I will be back on. Tt's a promise. ;)

**Comment by GammaC0de** [comment]
@Ryan747800B What you are requesting resembles the `ClickNLoad` plugin functinality.
Together with the flashgot plugin for firefox, you can send, with just one/two mouse clicks, any link to  pyLoad.

**Comment by Ryan747800B** [comment]
@GammaC0de Yes it's true but the problem is FlashGot and other similar plugins are only for some desktop browser. If you don't use as your main browser Firefox, or you don't want to install any plugin, or you use a mobile device (W10 Mobile, iOS or Android) I think that a bookmarklet is the best and easiest way to do this.

**Comment by GammaC0de** [comment]
From the transmission bookmarlet:
`var testResult = testUrl.search(/(\.torrent$)/i);`

How would you distinguish between "normal" url and "pyLoad" url?

**Comment by Ryan747800B** [comment]
Well if .torrent or magnet are in url then Transmission; others go to pyLoad. If you test Transmission bookmarklet it works very well with magnet. If you test pyLoad bookmarlet you see all links in the page and then you can select which you want. The best solution is to do a filter with all common extension so that it shows only what is "probably" a download file.

**Comment by rscataran** [comment]
I am also looking for something like this and have modified the above code for my use. 

https://github.com/rscataran/SendTopyLoadBookmarklet/blob/master/bookmarklet.js

**Comment by GammaC0de** [comment]
@rscataran Nice, 
Can you please tell what modifications you have done and what they do?

**Comment by rscataran** [comment]
Changes made:

    Translated to English
    Added Package Name field
    Longer timeout to close dialog (sometimes it takes longer for the server to respond before the timeout)

**Comment by GammaC0de** [comment]
@Ryan747800B @rscataran If you don't mind, I would like to host this bookmarklet (including changes made by me) on pyLoad's repo.
Of-course credits would be given.

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload-bookmarklet
