### ISSUE TITLE
Proxy Pyload

### ISSUE THREAD

**Issue by adielp89** [pyload/pyload#2338]
Hi there,
as I can get my pyLoad out through a proxy which has authentication SSL (https).

**Comment by vuolter** [comment]
What... exactly you asking for?

**Comment by adielp89** [comment]
cuando configuro el pyload por la interfaz gráfica en mi red debo colocar un proxy pero en mi red el proxy no permite conexiones básica http. Mi proxy de la empresa solo permite conexiones ssl que sería protocolo https.

**Comment by adielp89** [comment]
when I set pyLoad the GUI on my network I place a proxy in my network but does not allow the proxy http basic connections. My company proxy allows only SSL connections that would https protocol

**Comment by vuolter** [comment]
Unfortunately the proxy support is partially broken in 0.4.10 too. As soon as I can I'll take a look at it, but surely not these days. :(

**Comment by adielp89** [comment]
oka, thank you very much, really recently started using pyLoad it did not know the truth which is great ... keep it up and hopefully soon have support for this type of proxies ...
Cheers

**Comment by DexterHovis9000** [comment]
see #1128

**Comment by stefan1983** [comment]
Any update here? Will HTTPS be supported anytime soon?

**Comment by GammaC0de** [comment]
@stefan1983 Please test.

**Comment by stefan1983** [comment]
Can someone compile a Unix (Debian) core file?

I am running a dockerized pyload (linuxserver/pyload:latest).

Thanks
