### ISSUE TITLE
Captcha challenge getting unsolvable

### ISSUE THREAD

**Issue by sraedler** [pyload/pyload#2340]
If you download as free user from a hoster like uploaded or share-online, you have to solve a Captcha challenge. If you are not connected to the Webinterface, than the Captcha download will be skipped, because of "No Client connected for captcha decrypting". 

The problem is that pyload always ask for a new Captacha because of the new downloads in the list, so the challange is getting harder, because rechaptcha is thinking a bot trys to solve the captcha. So if you connect later to pyload and restart the downloads, the captchas are not solvable for a few hours.

I guess, that we should add a setting, which does not start a new download which has a captcha inserted, while no client is connected. Another Idea is to add a waiting time between new captchas, while no clients are connected, because the user could add push messages and see the new captchas on mobile phones.

Or does anyone has a better idea?

**Comment by GammaC0de** [comment]
@sraedler Why aren't you using a captcha service like 9kw for example?

**Comment by sraedler** [comment]
@GammaC0de I tried it, but it often doesn't work for me...

**Comment by GammaC0de** [comment]
What do you mean? is there a bug?

**Comment by sraedler** [comment]
I'm not sure, but I lost about 600 points for one captcha, but the download didn't start

**Comment by vuolter** [comment]
To check if works fine I need the log of the captcha service you used.
About the waiting time when no client is connected, with the next 0.4.9 update, pyLoad will stop downloads for 30 min and make max 3 captcha attempts (instead 10 as currently).

**Comment by sraedler** [comment]
trank you @vuolter !

I`m sorry, but I do not have the logs, because of a reinstall. But I guess, the 30 min waiting will solve my Problem!
