### ISSUE TITLE
Question about isresource() function

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2342]
Why HTTP code 302 is considered as a 'resource' when it just means a redirection (https://en.wikipedia.org/wiki/HTTP_302)?

See http://demo.ovh.eu/en/76cb43dbb6c7cf390cad20dceed371ef as an example for such a redirection that `pyLoad` interprets as a direct link when it is acctually a HTML page.

**Comment by GammaC0de** [comment]
Another example of a url that `pyload` detects as "resource": https://drive.google.com/file/d/0BxJgS33zZl9bSU55ZUxHd0pxOEE

**Comment by GammaC0de** [comment]
And another "direct" link: http://www.mediafire.com/?9ux28fv4kfb2dq6

**Comment by vuolter** [comment]
Checking...

**Comment by YiFanChen99** [comment]
I met this problem today. I get a redirect url, but it is Not a resource.

**Comment by GammaC0de** [comment]
Another example: http://www.nitroflare.com/view/DB82767E5E3DEBA

**Comment by vuolter** [comment]
Fixing...

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/a10f0f4f265a2c1da3de3a28605cef6b82b44bf2 Not closing..
