### ISSUE TITLE
ReCaptcha.py not working for V2 captchas at all?

### ISSUE THREAD

**Issue by Arno-Nymous** [pyload/pyload#2345]
Hi guys,

I'm trying to write a new custom plugin, which fetches some links from one of my favorite sites. Unfortunatelly, that website covers the download links behind a nasty ReCaptcha v2. I was happy to see that pyLoad already has built in support for these new captchas.

So after a bit of reading through the code I created a new crypter plugin (seemed the right choice of plugin type for my need), hacked down a few lines o' code and was hoping that a call to
```python
self.captcha.challenge(THE_SITE_KEY)
```
would do the job. That was foolish of me to think -_-

When getting past [this line of code in ReCaptcha.py](https://github.com/pyload/pyload/blob/6394d1974236412f1156f204405ee3b9c21e6150/module/plugins/captcha/ReCaptcha.py#L139) the content of `html` is
```html
[...]

<link rel="stylesheet" type="text/css" href="https://www.gstatic.com/recaptcha/api2/r20160208154954/styles__ltr.css">
<script type="text/javascript" src="https://www.gstatic.com/recaptcha/api2/r20160208154954/recaptcha__en.js">
      
    </script></head>
<body><script type="text/javascript">
      recaptcha.anchor.ErrorMain.init("[\x22ainput\x22,,,,,,[1,1]\n,\x22Required field must not be blank\x22]\n");
    </script></body></html>
```

After hours and hours of googling, studying the code and watching tons of browser requests and responses from and to real websites I can say that the code is not representing the procedure that real websites perform when showing one of those captchas.

I try to be careful with my assumption that the current version of ReCaptcha.py is not working properly for this type of captchas, so I want to start of with some major questions to the main devs @vuolter and @GammaC0de:
- Do you have any test links with which ReCaptcha plugin was successful? (I could provide plenty but I think they don't comply with the project's policies :smirk:)
- Since there were no changes made to the major code lines in the plugin (like the way which parameters are passed to requests and in which way): can one of you reassure that the code still applies to the current version of Google's reCAPTCHA v2 mechanism?
- And finally: Can you provide any information on where to find anything about the internal details of that recaptcha mechanism?

Just to clarify: I don't want to solve those captchas automatically, I just want to get the challenge and  let the user (or another plugin like Captcha9kw) solve it. Just like every other captcha.
I fear that, since the first version of the recaptcha v2 support in pyLoad 1 year ago, Google overhauled the way how captchas are sent between the servers (besides the fact that every tiny bit of Google's code is heavily double and triple obfuscated).

So, hopefully one of you more-experienced-than-me-in-this-field-guys can help me out as I'm just starting with this captcha thing. Any information appreciated!

Ciao!

P.S.: Sorry for the catchy headline, but had to pull attention somehow :sweat_smile:

**Comment by GammaC0de** [comment]
@Arno-Nymous Your assumptions are correct, see #2268

**Comment by Arno-Nymous** [comment]
So much writing and coding, though failed at searching. I feel ashamed and will take some google classes at my grandma's :smile:

Thanks for referencing, I will keep up withe the original :smirk:

**Comment by GammaC0de** [comment]
:+1:
