### ISSUE TITLE
File limit on Easybytez plugin for registered but not premium account

### ISSUE THREAD

**Issue by Elzazo** [pyload/pyload#2347]
Hi,
thanks for your job! :)
I have a registered account with easybytez.com.
Downloading this file 
http://www.easybytez.com/ew22du9ouxwk/Friends.Stagione.1.720.part26.rar
works from browsers but not in pyload.
Logs say:
failed File too large for free download 502.00 MiBXFileSharing

Can you actually fix that? Thanks a lot!

**Comment by GammaC0de** [comment]
I will need an account for testing..

**Comment by Elzazo** [comment]
Use this
l:reymisterio
p:Zazzaz84

2016-02-19 0:43 GMT+00:00 GammaC0de <notifications@github.com>:

> I will need an account for testing..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyload/pyload/issues/2347#issuecomment-185995616>.
>



-- 
Aldo

**Comment by vuolter** [comment]
@Elzazo This board is public: credentials removed. Please send a private email to @GammaC0de .

**Comment by Elzazo** [comment]
It looked strange to me at a first glance...

2016-02-19 10:16 GMT+00:00 Walter Purcaro <notifications@github.com>:

> @Elzazo <https://github.com/Elzazo> This board is public: credentials
> removed. Please send a private email to @GammaC0de
> <https://github.com/GammaC0de> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyload/pyload/issues/2347#issuecomment-186151754>.
>



-- 
Aldo

**Comment by vuolter** [comment]
@Elzazo What do you mean?

**Comment by Elzazo** [comment]
Asking for login/password on a public ticket...

2016-02-19 10:19 GMT+00:00 Walter Purcaro <notifications@github.com>:

> @Elzazo <https://github.com/Elzazo> What do you mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyload/pyload/issues/2347#issuecomment-186154582>.
>



-- 
Aldo

**Comment by vuolter** [comment]
Anyway, I tried and doesn't work thought browser too.

**Comment by Elzazo** [comment]
I've just tried and it works.
I just don't know how to provide an account to you to try. I was asked to
send it to GammaC0de but I don't know how.
Maybe without a user you can't download more than 300MB per file from
easybytez.

2016-02-19 11:29 GMT+00:00 Walter Purcaro <notifications@github.com>:

> Anyway, I tried and doesn't work thought browser too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyload/pyload/issues/2347#issuecomment-186179092>.
>



-- 
Aldo

**Comment by vuolter** [comment]
Working on...

**Comment by GammaC0de** [comment]
@Elzazo Send it to nitzo2001[AT]yahoo[DOT]com
‫

**Comment by Elzazo** [comment]
Done, thanks!

2016-02-19 11:49 GMT+00:00 GammaC0de <notifications@github.com>:

> @Elzazo Send it to nitzo2001[AT]yahoo[DOT]com
> ‫
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyload/pyload/issues/2347#issuecomment-186184503>.
>



-- 
Aldo

**Comment by GammaC0de** [comment]
@Elzazo Is this a premium account?

**Comment by Elzazo** [comment]
No it isn't

**Comment by GammaC0de** [comment]
@Elzazo Please send DEBUG log.

**Comment by Elzazo** [comment]
I'll try tomorrow evening, it seems I've consumed my daily quota for downloads.

**Comment by GammaC0de** [comment]
Also, try disabling `XFileSharing` plugin and see if it helps

**Comment by Elzazo** [comment]
It seems I don't have this problem no more... I'm downloading a 502MB file.
Strange, it didn't till this morning.
Thanks for the support!

2016-02-20 19:36 GMT+00:00 Aldo Lezza <aldolezza@gmail.com>:

> It doesn't, first thing I tried.
> Il 20/feb/2016 19:14, "GammaC0de" <notifications@github.com> ha scritto:
>
>> Also, try disabling XFileSharing plugin and see if it helps
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pyload/pyload/issues/2347#issuecomment-186667449>.
>>
>


-- 
Aldo

**Comment by GammaC0de** [comment]
:+1: I think there is some kind of limit for free account.

**Comment by danielgolemi** [comment]
http://www.easybytez.com/vv9q9bh0vngt
hi i cant download it because of this 
You can download files up to 100 Mb only.
Upgrade your account to download bigger files.
can you help me please?

**Comment by GammaC0de** [comment]
@danielgolemi Please open a new issue, thanks.
