### ISSUE TITLE
cannot update pyload

### ISSUE THREAD

**Issue by ID3000** [pyload/pyload#2351]
Hello there,
I've recently installed pyload and it says, pyload update available.
But it won't download and installe the update.
Working on windows server 2012 R2.
This is from the log:

`0.02.2016 22:42:00	INFO	Server set to threaded, due to known performance problems on windows.
416	20.02.2016 22:42:00	INFO	Starting threaded webserver: 0.0.0.0:8000
417	20.02.2016 22:42:04	INFO	*** New pyLoad Version
418	?	?	
419	?	?	
420	?	?	
421	?	?	
Not Found
422	?	?	
The requested URL /check/0.4.9/ was not found on this server.
423	?	?	
424	?	?	
Apache/2.2.15 (Red Hat) Server at get.pyload.org Port 443
425	?	?	
426	?	?	available ***
427	20.02.2016 22:42:04	INFO	*** Get it here: http://pyload.org/download ***
428	20.02.2016 22:42:04	INFO	No plugin updates available
`
I also can't reach pyload.org.
Is there a way to get pyload up2date on my windows system?

Thanks for help.

**Comment by GammaC0de** [comment]
See #2000

**Comment by ID3000** [comment]
Thank you so much for this quick comment.
Update worked.
Sorry I did not find this myself :(
Thank you so much again!!!

**Comment by GammaC0de** [comment]
That's fine :+1:
