### ISSUE TITLE
Onefichiercom Premium Account

### ISSUE THREAD

**Issue by nirG95** [pyload/pyload#2352]
Hello I have a problem with my premium account. Premium is false :

`21.02.2016 19:00:46 INFO      ACCOUNT OneFichierCom: Adding user `myuser@gmail.com`...
21.02.2016 19:00:46 DEBUG     ACCOUNT OneFichierCom: Reached login timeout for user `myuser@gmail.com`
21.02.2016 19:00:46 INFO      ACCOUNT OneFichierCom: Login user `myuser@gmail.com`...
21.02.2016 19:00:46 DEBUG     ACCOUNT OneFichierCom: LOAD URL https://1fichier.com/login.pl?lg=en | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={'purge': 'off', 'mail': 'myuser@gmail.com', 'valider': 'Send', 'It': 'on', 'pass': '**********'} | ref=True | multipart=False
21.02.2016 19:00:46 INFO      ACCOUNT OneFichierCom: Grabbing account info for user `myuser@gmail.com`...
21.02.2016 19:00:46 DEBUG     ACCOUNT OneFichierCom: LOAD URL https://1fichier.com/console/abo.pl | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={} | ref=True | multipart=False
21.02.2016 19:00:47 DEBUG     ACCOUNT OneFichierCom: Account info for user `myuser@gmail.com`: {'login': {'timestamp': 1456077646.6204131, 'password': '**********', 'valid': True}, 'data': {'validuntil': None, 'trafficleft': -1, 'plugin': <Account OneFichierCom>, 'maxtraffic': None, 'premium': False, 'login': 'myuser@gmail.com', 'type': 'OneFichierCom', 'options': {'limitdl': ['0']}}}
`

I have the last plugin : 
class OneFichierCom(SimpleHoster):
    __name__    = "OneFichierCom"
    __type__    = "hoster"
    __version__ = "0.99"
    __status__  = "testing"

Can you help me ? :)

Thank you

**Comment by GammaC0de** [comment]
I will need an account for testing.. 
Please send it to nitzo2001[AT]yahoo[DOT]com

**Comment by nirG95** [comment]
it's done :)

Thx again

**Comment by nirG95** [comment]
Have you received my email ?

**Comment by GammaC0de** [comment]
Yes

**Comment by GammaC0de** [comment]
Fixed

**Comment by nirG95** [comment]
Thx so much

**Comment by GammaC0de** [comment]
:+1:
