### ISSUE TITLE
No download with Premium OCH UL+SO (Bytesized Hosting version)

### ISSUE THREAD

**Issue by ArneHo** [pyload/pyload#2353]
Hey,
i use [Bytesized hosting](https://bytesized-hosting.com/). It looks like they use a older version of pyLoad. The file structures looks like this:
![pyload folder structure](https://cloud.githubusercontent.com/assets/14205429/13203837/a904bc2e-d8c0-11e5-8609-02dec5da344c.PNG)
---------------------------------------------------------------------------
![pyload folder structure -userplugins](https://cloud.githubusercontent.com/assets/14205429/13203843/e1360e0e-d8c0-11e5-9d07-68500e764b86.PNG)

But every folder inside the /userplugins are empty! Even if i add a my Account data from a OCH.
The Account data is saved in the 'accounts.config'. 
I added a premium account from Share-Online and a premium account from UploadedTO (both working properly with my pc/browser).
When I try to download something from Share-Online the log says:
```
- 300	21.02.2016 17:20:19	WARNING	Not able to connect server for updates
- 301	21.02.2016 17:20:19	INFO	No plugin updates available
- 302	21.02.2016 17:41:34	INFO	shutting down...
- 303	21.02.2016 17:41:34	INFO	Received Quit signal
- 304	21.02.2016 17:41:40	INFO	Starting pyLoad 0.4.9
- 305	21.02.2016 17:41:40	INFO	Using home directory: /home/hd9/arne/.config/pyload
- 306	21.02.2016 17:41:40	INFO	ExtractArchive: Activated UnRar UnZip
- 307	21.02.2016 17:41:40	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
- 308	21.02.2016 17:41:40	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
- 309	21.02.2016 17:41:40	INFO	Downloadtime: True
- 310	21.02.2016 17:41:40	INFO	Starting threaded webserver: 0.0.0.0:52260
- 311	21.02.2016 17:41:40	INFO	Free space: 1.12 TiB
- 312	21.02.2016 17:41:40	INFO	Activating Accounts...
- 313	21.02.2016 17:41:41	INFO	Activating Plugins...
- 314	21.02.2016 17:41:41	INFO	pyLoad is up and running
- 315	21.02.2016 17:41:41	WARNING	Click'N'Load: Port 9666 already in use
- 316	21.02.2016 17:41:44	WARNING	Not able to connect server for updates
- 317	21.02.2016 17:41:44	INFO	No Updates for pyLoad
- 318	21.02.2016 17:41:44	WARNING	Not able to connect server for updates
- 319	21.02.2016 17:41:44	INFO	No plugin updates available
- 320	21.02.2016 17:43:14	INFO	Added package Share-Online containing 1 links
- 321	21.02.2016 17:43:15	INFO	Decrypting starts: /home/hd9/arne/pyload/tmp_*XXX*.dlc
- 322	21.02.2016 17:43:15	ERROR	Error importing ShareonlineBiz: No module named ReCaptcha
- 323	21.02.2016 17:43:15	INFO	Added package *XXX* containing 19 links
- 324	21.02.2016 17:43:17	ERROR	Error importing ShareonlineBiz: No module named ReCaptcha
- 325	21.02.2016 17:43:17	CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
```
(The last two lines are repeating for all 19 links...)

On the other hand when i try to download something from Uploaded i'm able to do that, but it downloads like i have a free account. In the Config/Accounts from the webinterface it says that my Account would not be Premium (even tho it is..)

So any ideas how to fix it? Thanks in advance! Arne

**Comment by GammaC0de** [comment]
@ArneHo See #2000

**Comment by ArneHo** [comment]
Thanks!

**Comment by GammaC0de** [comment]
:+1:
