### ISSUE TITLE
Update manager not working

### ISSUE THREAD

**Issue by Elzazo** [pyload/pyload#2356]
Hello,
I've installed Pyload for Windows and Update Manager has this error

88	22.02.2016 09:39:16	INFO	No plugin updates available
87	22.02.2016 09:39:16	INFO	*** Get it here: http://pyload.org/download ***
86	?	?	available ***
85	?	?	
84	?	?	
Apache/2.2.15 (Red Hat) Server at get.pyload.org Port 443
83	?	?	
82	?	?	
The requested URL /check/0.4.9/ was not found on this server.
81	?	?	
Not Found
80	?	?	
79	?	?	
78	?	?

Seems like it has a bad URL to check.

**Comment by GammaC0de** [comment]
See #2000

**Comment by Elzazo** [comment]
Yes it's updating now, thanks a lot!

2016-02-22 10:01 GMT+00:00 GammaC0de <notifications@github.com>:

> See #2000
>
> > Hello,
> > I've installed Pyload for Windows and Update Manager has this error
> >
> > 88 22.02.2016 09:39:16 INFO No plugin updates available
> > 87 22.02.2016 09:39:16 INFO *** Get it here: http://pyload.org/download
> ***
> > 86 ? ? available ***
> > 85 ? ?
> >
> > 84 ? ?
> >
> > Apache/2.2.15 (Red Hat) Server at get.pyload.org Port 443
> > 83 ? ?
> >
> > 82 ? ?
> >
> > The requested URL /check/0.4.9/ was not found on this server.
> > 81 ? ?
> >
> > Not Found
> > 80 ? ?
> >
> > 79 ? ?
> >
> > 78 ? ?
> >
> > Seems like it has a bad URL to check.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyload/pyload/issues/2356#issuecomment-187104442>.
>



-- 
Aldo

**Comment by GammaC0de** [comment]
:+1:
