### ISSUE TITLE
pycurl error - cannot invoke setopt() - perform() is currently running

### ISSUE THREAD

**Issue by YiFanChen99** [pyload/pyload#2359]
This issue is about "pycurl error 0: ('cannot invoke setopt() - perform() is currently running',)".

In commit [cad33c](https://github.com/pyload/pyload/commit/cad33cec0ca6d19c66beaef2746f30630ff98102) , you tried using setStatus("starting") to avoid the pycurl error when multiple threads handling the same task.
However, method _\_setup_ in _internal/Base.py_ calls _grab_info_. And _grab_info_ will updating the status by 3(queued) if no pattern matched in _internal/SimpleHoster#get_info_.
That makes the pycurl error issue exist.

Is the default status 3 still making sense after commit cad33c? Or maybe you will find out an better solution for this issue.
I hope this information helps. Good luck.

**Comment by GammaC0de** [comment]
@YiFanChen99 I thought about it too but decided that setting it just there is enough (i might be mistaken).
Do you actually have this issue? 
If yes, please post DEBUG log.

**Comment by YiFanChen99** [comment]
I can only reproduce this issue through the multi-hoster _RealdebridCom.py_.
The debug log is about using _RealdebridCom.py_ to download file form _UploadedTo_
And I added two logs for verifying there are multiple threads involved.
[src_diff.txt](https://github.com/pyload/pyload/files/145896/src_diff.txt)
[result_log.txt](https://github.com/pyload/pyload/files/145897/result_log.txt)

**Comment by YiFanChen99** [comment]
For your information, the frequency of this issue happened depends on the environment.
For example, environment _A_ with CPU model _Intel Atom C2538 x86_64_ happens usually. But environment _B_ with CPU model _Intel Atom CE5335 i686_ happens seldom.

**Comment by GammaC0de** [comment]
@YiFanChen99 Please retry now and then tell if it works now

**Comment by GammaC0de** [comment]
@YiFanChen99 is it solved now?

**Comment by YiFanChen99** [comment]
I believe it is. And I will retry it the day after tomorrow.

**Comment by YiFanChen99** [comment]
Unfortunately, uur Realdebrid account has been expired. I will try it several days later.

**Comment by YiFanChen99** [comment]
Download successfully after commit bb938a8.

**Comment by GammaC0de** [comment]
:+1:
