### ISSUE TITLE
v0.4.9.tar.gz from GitHub Releases is broken

### ISSUE THREAD

**Issue by cavebeat** [pyload/pyload#2361]
v0.4.9.tar.gz does not want to start/install. 

`pyload@pyload:/home/pyload/pyload-0.4.9$ ./pyLoadCore.py 
Traceback (most recent call last):
  File "./pyLoadCore.py", line 43, in <module>
    from module.plugins.AccountManager import AccountManager
  File "/home/pyload/pyload-0.4.9/module/plugins/AccountManager.py", line 25, in <module>
    from module.PullEvents import AccountUpdateEvent
  File "/home/pyload/pyload-0.4.9/module/PullEvents.py", line 21, in <module>
    from module.utils import uniqify
ImportError: No module named utils
`

cloning from git does the job

**Comment by GammaC0de** [comment]
see #2000

**Comment by cavebeat** [comment]
hmm, your comment is to get it from releases
https://github.com/pyload/pyload/issues/2000#issuecomment-147120512
my issue is about "download from releases is broken"  => use git clone instead

**Comment by GammaC0de** [comment]
rename `Utils.py` to `utils.py`

**Comment by Velociraptor85** [comment]
@cavebeat does this work? can you close the issue?

**Comment by cavebeat** [comment]
i guess we can close this one...
