### ISSUE TITLE
jinja2 version 2.8 seems too old.

### ISSUE THREAD

**Issue by cavebeat** [pyload/pyload#2362]
> Your installed jinja2 version 2.8 seems too old.
> You can safely continue but if the webinterface is not working,
> please upgrade or deinstall it, pyLoad includes a sufficient jinja2 libary.

https://github.com/mitsuhiko/jinja2/releases 
https://pypi.python.org/pypi/Jinja2

jinja2 2.8 **_ is _** the latest release available.

**Comment by googlebleh** [comment]
I was able to avoid this message by simply installing jinja instead of jinja2: `pip install jinja`

**Comment by cavebeat** [comment]
as far as i have seen, jinja is not in use anymore. 
regarding actual requirements: https://requires.io/github/pyload/pyload/requirements/?branch=master 

so i vote for close of this issue
