### ISSUE TITLE
'NoneType' object has no attribute with UL n RG

### ISSUE THREAD

**Issue by tbfvrs** [pyload/pyload#2364]
Today welcomed me with with such Issue on both Rapidgator and UploadedTo...
Didn't know if I had UpdMan activated so restarted pyload but didn't help...

When adding a link:
1080	27.02.2016 05:53:05	INFO	Added package ... containing 1 links
1081	27.02.2016 05:53:05	ERROR	Error importing RapidgatorNet/UploadedTo: No module named _imaging
1082	27.02.2016 05:53:05	ERROR	Error importing RapidgatorNet/UploadedTo: No module named _imaging
1083	27.02.2016 05:53:05	CRITICAL	'NoneType' object has no attribute 'RapidgatorNet/'UploadedTo'

Anyone else is having this issue?
Greetz

**Comment by GammaC0de** [comment]
@tbfvrs Please send DEBUG log

**Comment by jackdierippe** [comment]
I guess comparable situation for Shareonline :

ERROR	Error importing ShareonlineBiz: libjpeg.so.9: cannot open shared object file: No such file or directory
CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
