### ISSUE TITLE
pyLoad will not skip the same file on a different hoster

### ISSUE THREAD

**Issue by ID3000** [pyload/pyload#2365]
Hello again,

I've got the problem, if I load the same files from different hosters and start the DL, the file already started to download at hoster 1 will not be skipped for hoster 2. Pyload then wants to download the same file from two hosters.
On my previous install on a linux system, the file started to download at hoster 1 was automatically skipped at hoster 2.
Files which are successfully downloaded are skipped correctly.

I guess this is a config issue, but i canot find where I have to change my settings.
Please help me. Thanks in advance.

My setup is on a win2k12 server and py is started as hidden planned task with admin rights.

**Comment by GammaC0de** [comment]
@ID3000 Try setting "Skip already existing files" to True in the "Download" section of pyLoad's configuration.

**Comment by ID3000** [comment]
Hello GrammaC0de,

This setting was already True.
I disabled it and enabled it again.
Will post report later (can't try it actually) but I am not sure if it helps since I already had this enabled.
I also had a look for all plugins which might impact the download, but I could not find a relevant setting.

Do you know, if this could happen since files are started simultaneously (pyload is runnning on an ssd and is pretty fast right now), so the files.db can't be updated fast enoughj?

**Comment by GammaC0de** [comment]
@ID3000 This is not likely related to hardware

**Comment by ID3000** [comment]
Yeah I also do not think so, was just a thought.

The amazing thing is, if the files are downloaded completely, then they are skipped, but if the download is ongoing, then they are not.
It is also not important, if the links are stored in different or the same package. Behaviour is the same.

I guess I will reinstall pyload tomorrow and check it again.

**Comment by vuolter** [comment]
@GammaC0de @ID3000 Skipping feature is currently broken, but I've already fixed it in my personal branch, so will back to work after I pushed my next big big big patch. ;)

**Comment by GammaC0de** [comment]
:+1: Will be fun :smile:

**Comment by vuolter** [comment]
I pratically applied changes to each file I found in the plugin folder and with the new upfatemanager pyLoad, in theory, should has become a truly rolling release. However many stuff still need to be tested...

**Comment by zlep** [comment]
Oh dear... Big patch means even more broken stuff...
Seriously, will you ever sort out the mess you made of Pyload? What about broken stuff like Extracting which does not work since months?

**Comment by vuolter** [comment]
@zlep Yep, I'm the worse, bla, bla, bla.... But, the truth is that there are issues that can not be fixed without more radical changes. ExtractArchive as example: it works for 8 people over 10, now is broken, but reach the 10/10 is not possible due a lot of core/api/internal bugs, so, again, I have to write another workaround somewhere in the plugin code. Simply, there is no other way out! Ah, if I damn finish the 0.4.10 and release it, testing code will be pushed in the testing branch and user will stop blame me every time...

**Comment by zlep** [comment]
Some years ago, Pyload worked for 10/10 people... And no, it was not less complex back then. It had all relevant plugins and functions. Thats all I'm saying...

**Comment by vuolter** [comment]
@zlep I do not agree. Times ago pyLoad did not handle direct link sometimes and people continued to open issues about that, now SimpleHoster automatically detect this kind of link. A dirty example to say it was not 10/10.

**Comment by sraedler** [comment]
@zlep I think you have to look a step further, because now pyload is on a way, to be more stable and even more fixable, if bugs came up. So I guess vuolter does a great job and I have to say, I'm starring at pyload for a long time and the work is great!!

**Comment by ID3000** [comment]
@voulter
Thank you so much for this explanation.
I thought I was a dumb fool not even able to read configs and stuff .... But this explains a lot.
So I will handle it whit a workaround until a fix is there.
Can you please comment here as soon as a fix is available?

@zlep Can you please not use my support request to blame people?
And before blaming the people providing you with a free software, write your one one which works for 10/10 people and  then share it for free, thanks!
As long as you did not, please either open your own thread or keep calm, thanks agin.

**Comment by Burnout5151** [comment]
> Skipping feature is currently broken

Can we label this thread as "bug"?

**Comment by Burnout5151** [comment]
... and rename topic to something like "skipping _in progress_ downloads doesn't work" ?

**Comment by secrethero83** [comment]
@vuolter 
It seems, this feature is still broken in version 0.4.9 on raspberry.
Pyload still starts to download a file while the file is being downloaded from a different hoster.
Is there a way I can fix this manually? Which file would I have to replace?

Thanks and regards
secrethero83
