### ISSUE TITLE
Download not recognised as completed

### ISSUE THREAD

**Issue by janfreyberg** [pyload/pyload#2366]
Hi all,

I'm running pyload v0.4.9 on my Synology NAS (posix linux2 Linux 3.10.35 #5644 SMP Fri Jan 22 13:38:40 CST 2016 armv7l), with Python 2.7.11.

When a download is completed, pyload does not recognise the download as having succeeded, even though everything works well. This means the packages are not marked as having been completed, and as a result the ExternalScripts associated with thos triggers aren't executed. The error I get is:

`WARNING	Download failed: filename | 'unicode' object does not support item assignment
`

Would be nice if this was fixed!

Thanks

**Comment by vuolter** [comment]
Debug log please.

**Comment by artdog** [comment]
I am having the same issue:
DEBUG	Content-Disposition: 88vu term.rar
49	23.03.2016 06:21:59	INFO	HOSTER RapidgatorNet[6]: File saved
50	23.03.2016 06:21:59	INFO	HOSTER RapidgatorNet[6]: Checking download...
51	23.03.2016 06:21:59	INFO	HOSTER RapidgatorNet[6]: File is OK
52	23.03.2016 06:21:59	INFO	HOSTER RapidgatorNet[6]: Checking file (with built-in rules)...
53	23.03.2016 06:22:00	INFO	HOSTER RapidgatorNet[6]: Checking file (with custom rules)...
54	23.03.2016 06:22:00	INFO	HOSTER RapidgatorNet[6]: Checking for link errors...
55	23.03.2016 06:22:00	INFO	HOSTER RapidgatorNet[6]: No errors found
56	23.03.2016 06:22:00	INFO	HOSTER RapidgatorNet[6]: No errors found
57	23.03.2016 06:22:00	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
58	23.03.2016 06:22:00	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
59	23.03.2016 06:22:00	INFO	Download finished: 88vu term.rar
60	23.03.2016 06:22:00	DEBUG	ADDON ExternalScripts: No script found under folder `download_finished`
61	23.03.2016 06:22:00	DEBUG	ADDON Checksum: {'md5': u'e63be5bdb1d5802fe5ac75403c68d25b', u'hash': u'e63be5bdb1d5802fe5ac75403c68d25b', u'filename': u'Better.Call.Saul.S02E06.1080p.HDTV.x264-BRISK.part3.rar'}
**62	23.03.2016 06:22:00	WARNING	Download failed: 88vu term.part3.rar | 'unicode' object does not support item assignment**
63	23.03.2016 06:22:50	INFO	Debug Report written to debug_RapidgatorNet_23-03-2016_06-22-00.zip
64	23.03.2016 06:22:50	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
65	23.03.2016 06:22:50	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 88vu term.part3.rar (pid:2)
66	23.03.2016 06:22:50	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
URL?

**Comment by artdog** [comment]
Ok here is another one. URLs first. Log after:
http://rapidgator.net/file/f06dbecd69ac9d393df2f8985c8dd97c/Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part1.rar.html
http://rapidgator.net/file/22a3059f9f767f10731575da9b653839/Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part2.rar.html
http://rapidgator.net/file/55dadf964aafe00dae96e54f05f346dc/Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar.html

**Comment by GammaC0de** [comment]
@artdog Currently the status of `ExtractArchive` plugin is "broken" (see #2296) so please disable `ExtractArchive` plugin until @vuolter will release a new version soon.

**Comment by artdog** [comment]
I will disable the plug in but even without it I still get the download failed error on some files.

**Comment by GammaC0de** [comment]
Please send DEBUG log

**Comment by artdog** [comment]
343	24.03.2016 06:37:55	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
344	24.03.2016 06:37:55	DEBUG	HOSTER RapidgatorNet[11]: Plugin version: 0.41
345	24.03.2016 06:37:55	DEBUG	HOSTER RapidgatorNet[11]: Plugin status: testing
346	24.03.2016 06:37:55	WARNING	HOSTER RapidgatorNet[11]: Plugin may be unstable
347	24.03.2016 06:37:55	INFO	ACCOUNT RapidgatorNet: Grabbing account info for user `artdog@gmx.com`...
348	24.03.2016 06:37:55	DEBUG	ACCOUNT RapidgatorNet: LOAD URL http://rapidgator.net/api/user/info | redirect=True | decode=True | cookies=True | get={'sid': 'm3sj19um7eej6brregsb2ap5v1'} | req=None | just_header=False | post={} | ref=True | multipart=False
349	24.03.2016 06:37:55	DEBUG	ACCOUNT RapidgatorNet: API:USERINFO | {"response":{"expire_date":1464322607,"traffic_left":"3141849830728"},"response_status":200,"response_details":null}
350	24.03.2016 06:37:55	DEBUG	ACCOUNT RapidgatorNet: Account info for user `artdog@gmx.com`: {'login': {'timestamp': 1458800864.8556049, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 3068212725.3203125, 'maxtraffic': None, 'sid': 'm3sj19um7eej6brregsb2ap5v1', 'validuntil': 1464322607, 'login': 'artdog@gmx.com', 'type': 'RapidgatorNet', 'options': {'limitdl': '0'}}}
351	24.03.2016 06:37:55	INFO	HOSTER RapidgatorNet[11]: Grabbing link info...
352	24.03.2016 06:37:56	DEBUG	HOSTER RapidgatorNet[11]: Link info: {'status': 2, 'hash': {u'MD5': u'f262d453af734c4e555fcf346e564e15'}, 'name': 'Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar', 'url': u'http://rapidgator.net/file/55dadf964aafe00dae96e54f05f346dc/Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar.html', 'pattern': {'H': u'MD5', 'S': u'870.22', 'U': u'MB', 'D': u'f262d453af734c4e555fcf346e564e15', 'N': u'Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar'}, 'size': 912491806}
353	24.03.2016 06:37:56	DEBUG	HOSTER RapidgatorNet[11]: Previous link info: {}
354	24.03.2016 06:37:56	INFO	HOSTER RapidgatorNet[11]: Link name: Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar
355	24.03.2016 06:37:56	INFO	HOSTER RapidgatorNet[11]: Link size: 870.22 MiB (912491806 bytes)
356	24.03.2016 06:37:56	INFO	HOSTER RapidgatorNet[11]: Link status: online
357	24.03.2016 06:37:56	INFO	ACCOUNT RapidgatorNet: Grabbing account info for user `artdog@gmx.com`...
358	24.03.2016 06:37:56	DEBUG	ACCOUNT RapidgatorNet: LOAD URL http://rapidgator.net/api/user/info | redirect=True | decode=True | cookies=True | get={'sid': 'm3sj19um7eej6brregsb2ap5v1'} | req=None | just_header=False | post={} | ref=True | multipart=False
359	24.03.2016 06:37:56	DEBUG	ACCOUNT RapidgatorNet: API:USERINFO | {"response":{"expire_date":1464322607,"traffic_left":"3141849830728"},"response_status":200,"response_details":null}
360	24.03.2016 06:37:56	DEBUG	ACCOUNT RapidgatorNet: Account info for user `artdog@gmx.com`: {'login': {'timestamp': 1458800864.8556049, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 3068212725.3203125, 'maxtraffic': None, 'sid': 'm3sj19um7eej6brregsb2ap5v1', 'validuntil': 1464322607, 'login': 'artdog@gmx.com', 'type': 'RapidgatorNet', 'options': {'limitdl': '0'}}}
361	24.03.2016 06:37:56	INFO	HOSTER RapidgatorNet[11]: Processing url: http://rapidgator.net/file/55dadf964aafe00dae96e54f05f346dc/Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar.html
362	24.03.2016 06:37:56	INFO	HOSTER RapidgatorNet[11]: Looking for direct download link...
363	24.03.2016 06:37:56	DEBUG	HOSTER RapidgatorNet[11]: LOAD URL http://rapidgator.net/file/55dadf964aafe00dae96e54f05f346dc/Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar.html | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=True | post={} | ref=True | multipart=False
364	24.03.2016 06:37:57	INFO	HOSTER RapidgatorNet[11]: Direct download link not found
365	24.03.2016 06:37:57	DEBUG	HOSTER RapidgatorNet[11]: LOAD URL http://rapidgator.net/file/55dadf964aafe00dae96e54f05f346dc/Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar.html | redirect=True | decode=True | cookies=[('rapidgator.net', 'lang', 'en')] | get={} | req=None | just_header=False | post={} | ref=False | multipart=False
366	24.03.2016 06:37:57	INFO	HOSTER RapidgatorNet[11]: Checking for link errors...
367	24.03.2016 06:37:57	INFO	HOSTER RapidgatorNet[11]: No errors found
368	24.03.2016 06:37:57	INFO	HOSTER RapidgatorNet[11]: Processing as premium download...
369	24.03.2016 06:37:57	DEBUG	HOSTER RapidgatorNet[11]: LOAD URL http://rapidgator.net/api/file/info | redirect=True | decode=True | cookies=True | get={'url': u'http://rapidgator.net/file/55dadf964aafe00dae96e54f05f346dc/Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar.html', 'sid': 'm3sj19um7eej6brregsb2ap5v1'} | req=None | just_header=False | post={} | ref=True | multipart=False
370	24.03.2016 06:37:57	DEBUG	HOSTER RapidgatorNet[11]: API:info | {"response":{"filename":"Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar","size":"912486913","hash":"f262d453af734c4e555fcf346e564e15"},"response_status":200,"response_details":null} | SID: m3sj19um7eej6brregsb2ap5v1
371	24.03.2016 06:37:57	DEBUG	HOSTER RapidgatorNet[11]: LOAD URL http://rapidgator.net/api/file/download | redirect=True | decode=True | cookies=True | get={'url': u'http://rapidgator.net/file/55dadf964aafe00dae96e54f05f346dc/Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar.html', 'sid': 'm3sj19um7eej6brregsb2ap5v1'} | req=None | just_header=False | post={} | ref=True | multipart=False
372	24.03.2016 06:37:57	DEBUG	HOSTER RapidgatorNet[11]: API:download | {"response":{"url":"http:\/\/pr16.rapidgator.net\/\/?r=download\/index&session_id=SuLwcoG2i0FEVBJLhoTJpCSk2g0dKlT3"},"response_status":200,"response_details":null} | SID: m3sj19um7eej6brregsb2ap5v1
373	24.03.2016 06:37:57	INFO	HOSTER RapidgatorNet[11]: Downloading file...
374	24.03.2016 06:37:57	DEBUG	HOSTER RapidgatorNet[11]: DOWNLOAD URL http://pr16.rapidgator.net//?r=download/index&session_id=SuLwcoG2i0FEVBJLhoTJpCSk2g0dKlT3 | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
375	24.03.2016 06:37:58	DEBUG	Content-Disposition: Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar
376	24.03.2016 06:39:26	INFO	Debug Report written to debug_RapidgatorNet_24-03-2016_06-37-34.zip
377	24.03.2016 06:39:26	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
378	24.03.2016 06:39:26	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part1.rar (pid:5)
379	24.03.2016 06:39:26	INFO	ADDON UnSkipOnFail: No duplicates found
380	24.03.2016 06:39:31	INFO	Debug Report written to debug_RapidgatorNet_24-03-2016_06-37-39.zip
381	24.03.2016 06:39:31	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
382	24.03.2016 06:39:31	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part2.rar (pid:5)
383	24.03.2016 06:39:31	INFO	ADDON UnSkipOnFail: No duplicates found
384	24.03.2016 06:40:54	INFO	HOSTER RapidgatorNet[11]: File saved
385	24.03.2016 06:40:54	INFO	HOSTER RapidgatorNet[11]: Checking download...
386	24.03.2016 06:40:55	INFO	HOSTER RapidgatorNet[11]: File is OK
387	24.03.2016 06:40:55	INFO	HOSTER RapidgatorNet[11]: Checking file (with built-in rules)...
388	24.03.2016 06:40:56	INFO	HOSTER RapidgatorNet[11]: Checking file (with custom rules)...
389	24.03.2016 06:40:56	INFO	HOSTER RapidgatorNet[11]: Checking for link errors...
390	24.03.2016 06:40:56	INFO	HOSTER RapidgatorNet[11]: No errors found
391	24.03.2016 06:40:56	INFO	HOSTER RapidgatorNet[11]: No errors found
392	24.03.2016 06:40:56	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
393	24.03.2016 06:40:56	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
394	24.03.2016 06:40:56	DEBUG	ADDON ExternalScripts: No script found under folder `package_failed`
395	24.03.2016 06:40:56	INFO	Download finished: Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar
396	24.03.2016 06:40:56	DEBUG	ADDON ExternalScripts: No script found under folder `download_finished`
397	24.03.2016 06:40:56	DEBUG	ADDON Checksum: {'md5': u'f262d453af734c4e555fcf346e564e15', u'hash': u'f262d453af734c4e555fcf346e564e15', u'filename': u'Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar'}
398	24.03.2016 06:40:56	WARNING	Download failed: Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar | 'unicode' object does not support item assignment
399	24.03.2016 06:41:28	INFO	Debug Report written to debug_RapidgatorNet_24-03-2016_06-40-56.zip
400	24.03.2016 06:41:28	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
401	24.03.2016 06:41:28	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar (pid:5)
402	24.03.2016 06:41:28	INFO	ADDON UnSkipOnFail: No duplicates found
403	24.03.2016 06:41:28	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
404	24.03.2016 06:41:28	DEBUG	All downloads processed
405	24.03.2016 12:15:05	DEBUG	ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | redirect=True | decode=True | cookies=True | get={'v': '0.4.9'} | req=None | just_header=False | post={} | ref=True | multipart=False
406	24.03.2016 12:15:05	INFO	ADDON UpdateManager: pyLoad is up to date!
407	24.03.2016 12:15:05	DEBUG	ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | redirect=True | decode=True | cookies=True | get={'v': '0.4.9'} | req=None | just_header=False | post={} | ref=True | multipart=False
408	24.03.2016 12:15:06	DEBUG	ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
409	24.03.2016 12:15:06	ERROR	ADDON UpdateManager: Error updating plugin: CAPTCHA UlozTo | Bad version number on the server
410	24.03.2016 12:15:06	INFO	ADDON UpdateManager: All plugins are up to date!

**Comment by artdog** [comment]
Line 398	24.03.2016 06:40:56	WARNING	Download failed: Kung.Fu.Panda.3.2016.720p.WEB-DL.X264.AC3-EVO.part3.rar | 'unicode' object does not support item assignment

**Comment by GammaC0de** [comment]
This worked fine with free download, I need an account for testing premium download.
Please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com.

**Comment by GammaC0de** [comment]
Closing due to no response.

**Comment by artdog** [comment]
Sorry. I'm not willing to give anyone my account details.

**Comment by GammaC0de** [comment]
Ok, please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com.

**Comment by GammaC0de** [comment]
Just noticed the "not" ::

**Comment by wweich** [comment]
I get the same error.
I can work around it by disabling checksum check, either in the checksum plugin settings or by removing the line 
```
self.api_data['md5'] = self.api_data['hash']
```
inside the `handle_premium` function of RapidgatorNet.py.

Seems the free variant doesn't get a checksum to check, so doesn't get the error.

**Comment by GammaC0de** [comment]
@wweich If you want me to try and solve this,  please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.
