### ISSUE TITLE
Download failed: | sub() takes at most 4 arguments (5 given)

### ISSUE THREAD

**Issue by RickyTR** [pyload/pyload#2367]
Hi all,

just found this error using two different hosters (Easybytez and Rockfile).

This is the log:

461	29.02.2016 16:02:58	WARNING	Download failed: S1c4r1048.part6.rar | sub() takes at most 4 arguments (5 given)
460	29.02.2016 16:02:58	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
459	29.02.2016 16:02:58	INFO	HOSTER EasybytezCom[7]: No errors found
458	29.02.2016 16:02:58	INFO	HOSTER EasybytezCom[7]: Checking for link errors...
457	29.02.2016 16:02:58	DEBUG	HOSTER EasybytezCom[7]: Getting download link #1...
456	29.02.2016 16:02:58	INFO	HOSTER EasybytezCom[7]: Processing as free download...
455	29.02.2016 16:02:58	INFO	HOSTER EasybytezCom[7]: No errors found
454	29.02.2016 16:02:58	INFO	HOSTER EasybytezCom[7]: Checking for link errors...
453	29.02.2016 16:02:58	INFO	HOSTER EasybytezCom[8]: Grabbing link info...

Thanks.

**Comment by GammaC0de** [comment]
DEBUG log please
