### ISSUE TITLE
'NoneType' object has no attribute 'get_info' on Uploaded

### ISSUE THREAD

**Issue by tbfvrs** [pyload/pyload#2368]
After a quick fix last time now another error came up:

1057	01.03.2016 11:34:11	INFO	Download starts: ................
1058	01.03.2016 11:34:11	WARNING	HOSTER UploadedTo[91]: Plugin may be unstable
1059	01.03.2016 11:34:11	WARNING	Download failed: ................. | 'NoneType' object has no attribute 'get_info'
1060	01.03.2016 11:34:11	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: ................. (pid:26)
1061	01.03.2016 11:34:11	INFO	ADDON UnSkipOnFail: No duplicates found

So UL is broken again, sorry for no debug log but I really can't find him when saved...

**Comment by vuolter** [comment]
Debug log please.

**Comment by tbfvrs** [comment]
The error is mysteriously gone...
When checked the added prem acc 10min ago in the Ul.to row there were only:
Plugin    Login
None     None
etc.
I've restarted py in debug mode and wanted to try some links and for my surprise they started to DL;
Checked back again the prem acc and everythng is fine...
So I'm happy:)
