### ISSUE TITLE
Question: Start Click and Load directly by editing config/py files

### ISSUE THREAD

**Issue by Teyro** [pyload/pyload#2383]
Hi there,

i know this is not the support forum, but i dont know where to write ...Forums are down forever and there is no Facebook/Google+ etc Page for help.....And i hope someone can help me....

So i had to install pyload again because hardware upgrade.... At the Pyload Forums someone wrote a article how to start a added package directly... without useing the link collector... i remeber that i have to edit two files.... Can someone help me?

2.nd Question:

Many things going wrong with pyload (extracht archive brocken, ReCatcha Support dropped, Forum dropped...).....Whats going on?

thx for help

**Comment by GammaC0de** [comment]
@Teyro what do you mean by "start a added package directly"? please explain

Latest backup of the forums can be ffound here: https://mega.nz/#!l0ZUXZqY!BXIZdZS7wyTISE1RZo5Ozb6-TwfPYbbWzwCT7BZwPMI

As for your second question, @vuolter is working hard on a new version of extract archive, hopefully will be released soon.

A new site and a wiki for pyload is beeing built on http://pyload.github.io/

ReCatcha Support is not dropped, on the contrary, ReCatcha v2 support was added recently, how did you got to this conclusion?

**Comment by GammaC0de** [comment]
Closing because of no response.
