### ISSUE TITLE
Rapidgator plugin not loading

### ISSUE THREAD

**Issue by artdog** [pyload/pyload#2388]
The rapidgator plug in is not loading on startup. The log has the following entry:

ERROR	RapidgatorNet: unsupported operand type(s) for /: 'unicode' and 'int'

**Comment by GammaC0de** [comment]
Debug log please

**Comment by artdog** [comment]
I'm not sure if this is the debug log but..
`220	21.03.2016 21:24:57	INFO	Starting pyLoad 0.4.9
221	21.03.2016 21:24:57	INFO	Using home directory: /i-data/07b224a6/admin/zy-pkgs/pyLoad/etc/pyload
222	21.03.2016 21:24:59	INFO	ExtractArchive: Activated UnRar UnZip
223	21.03.2016 21:24:59	INFO	Checksum: Checksum validation is disabled in general configuration
224	21.03.2016 21:25:00	WARNING	Failed activating .___init__
225	21.03.2016 21:25:00	INFO	Activated plugins: BypassCaptcha, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterCom, UnSkipOnFail, UpdateManager, XFileSharingPro
226	21.03.2016 21:25:00	INFO	Deactivate plugins: ._AlldebridCom, ._BypassCaptcha, ._Captcha9kw, ._CaptchaBrotherhood, ._CaptchaTrader, ._Checksum, ._ClickAndLoad, ._DeathByCaptcha, ._DownloadScheduler, ._EasybytezCom, ._Ev0InFetcher, ._ExpertDecoders, ._ExternalScripts, ._ExtractArchive, ._HotFolder, ._IRCInterface, ._ImageTyperz, ._LinkdecrypterCom, ._MergeFiles, ._MultiHome, ._MultishareCz, ._Premium4Me, ._PremiumizeMe, ._RealdebridCom, ._RehostTo, ._UnSkipOnFail, ._UpdateManager, ._XFileSharingPro, ._XMPPInterface, ._ZeveraCom, AlldebridCom, Captcha9kw, CaptchaBrotherhood, DeathByCaptcha, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, Premium4Me, PremiumizeMe, RealdebridCom, RehostTo, XMPPInterface, ZeveraCom
227	21.03.2016 21:25:00	INFO	Downloadtime: True
228	21.03.2016 21:25:00	INFO	Starting ThriftBackend: 0.0.0.0:7227
229	21.03.2016 21:25:01	INFO	Starting threaded webserver: 0.0.0.0:1024
230	21.03.2016 21:25:00	INFO	Free space: 189.62 GiB
231	21.03.2016 21:25:02	INFO	Activating Accounts...
232	21.03.2016 21:25:02	ERROR	RapidgatorNet: unsupported operand type(s) for /: 'unicode' and 'int'
233	21.03.2016 21:25:02	INFO	Activating Plugins...
234	21.03.2016 21:25:02	ERROR	LinkdecrypterCom: Crypter list not found
235	21.03.2016 21:25:02	INFO	pyLoad is up and running`

**Comment by artdog** [comment]
INFO	Starting pyLoad 0.4.9
241	21.03.2016 21:31:17	INFO	Using home directory: /i-data/07b224a6/admin/zy-pkgs/pyLoad/etc/pyload
242	21.03.2016 21:31:17	DEBUG	Remote activated: True
243	21.03.2016 21:31:19	DEBUG	created index of plugins
244	21.03.2016 21:31:19	INFO	ExtractArchive: Activated UnRar UnZip
245	21.03.2016 21:31:19	INFO	Checksum: Checksum validation is disabled in general configuration
246	21.03.2016 21:31:19	DEBUG	UpdateManager: Monitoring file changes
247	21.03.2016 21:31:19	WARNING	Failed activating .___init__
248	21.03.2016 21:31:19	INFO	Activated plugins: BypassCaptcha, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterCom, UnSkipOnFail, UpdateManager, XFileSharingPro
249	21.03.2016 21:31:19	INFO	Deactivate plugins: ._AlldebridCom, ._BypassCaptcha, ._Captcha9kw, ._CaptchaBrotherhood, ._CaptchaTrader, ._Checksum, ._ClickAndLoad, ._DeathByCaptcha, ._DownloadScheduler, ._EasybytezCom, ._Ev0InFetcher, ._ExpertDecoders, ._ExternalScripts, ._ExtractArchive, ._HotFolder, ._IRCInterface, ._ImageTyperz, ._LinkdecrypterCom, ._MergeFiles, ._MultiHome, ._MultishareCz, ._Premium4Me, ._PremiumizeMe, ._RealdebridCom, ._RehostTo, ._UnSkipOnFail, ._UpdateManager, ._XFileSharingPro, ._XMPPInterface, ._ZeveraCom, AlldebridCom, Captcha9kw, CaptchaBrotherhood, DeathByCaptcha, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, Premium4Me, PremiumizeMe, RealdebridCom, RehostTo, XMPPInterface, ZeveraCom
250	21.03.2016 21:31:19	INFO	Downloadtime: True
251	21.03.2016 21:31:19	INFO	Starting ThriftBackend: 0.0.0.0:7227
252	21.03.2016 21:31:19	INFO	Free space: 189.62 GiB
253	21.03.2016 21:31:21	INFO	Starting threaded webserver: 0.0.0.0:1024
254	21.03.2016 21:31:21	INFO	Activating Accounts...
255	21.03.2016 21:31:21	DEBUG	RapidgatorNet: API:LOGIN | {"response":{"session_id":"d02fkbvtfgbv9pk3go3m64qqv1","expire_date":1464322607,"traffic_left":"3157002677334"},"response_status":200,"response_details":null}
256	21.03.2016 21:31:21	DEBUG	RapidgatorNet: Get Account Info for artdog@gmx.com

**Comment by GammaC0de** [comment]
@artdog You should enable debug mode in the "general" page of the configuration and then post the log again

**Comment by artdog** [comment]
240	21.03.2016 21:31:17	INFO	Starting pyLoad 0.4.9
241	21.03.2016 21:31:17	INFO	Using home directory: /i-data/07b224a6/admin/zy-pkgs/pyLoad/etc/pyload
242	21.03.2016 21:31:17	DEBUG	Remote activated: True
243	21.03.2016 21:31:19	DEBUG	created index of plugins
244	21.03.2016 21:31:19	INFO	ExtractArchive: Activated UnRar UnZip
245	21.03.2016 21:31:19	INFO	Checksum: Checksum validation is disabled in general configuration
246	21.03.2016 21:31:19	DEBUG	UpdateManager: Monitoring file changes
247	21.03.2016 21:31:19	WARNING	Failed activating .___init__
248	21.03.2016 21:31:19	INFO	Activated plugins: BypassCaptcha, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterCom, UnSkipOnFail, UpdateManager, XFileSharingPro
249	21.03.2016 21:31:19	INFO	Deactivate plugins: ._AlldebridCom, ._BypassCaptcha, ._Captcha9kw, ._CaptchaBrotherhood, ._CaptchaTrader, ._Checksum, ._ClickAndLoad, ._DeathByCaptcha, ._DownloadScheduler, ._EasybytezCom, ._Ev0InFetcher, ._ExpertDecoders, ._ExternalScripts, ._ExtractArchive, ._HotFolder, ._IRCInterface, ._ImageTyperz, ._LinkdecrypterCom, ._MergeFiles, ._MultiHome, ._MultishareCz, ._Premium4Me, ._PremiumizeMe, ._RealdebridCom, ._RehostTo, ._UnSkipOnFail, ._UpdateManager, ._XFileSharingPro, ._XMPPInterface, ._ZeveraCom, AlldebridCom, Captcha9kw, CaptchaBrotherhood, DeathByCaptcha, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, Premium4Me, PremiumizeMe, RealdebridCom, RehostTo, XMPPInterface, ZeveraCom
250	21.03.2016 21:31:19	INFO	Downloadtime: True
251	21.03.2016 21:31:19	INFO	Starting ThriftBackend: 0.0.0.0:7227
252	21.03.2016 21:31:19	INFO	Free space: 189.62 GiB
253	21.03.2016 21:31:21	INFO	Starting threaded webserver: 0.0.0.0:1024
254	21.03.2016 21:31:21	INFO	Activating Accounts...
255	21.03.2016 21:31:21	DEBUG	RapidgatorNet: API:LOGIN | {"response":{"session_id":"d02fkbvtfgbv9pk3go3m64qqv1","expire_date":1464322607,"traffic_left":"3157002677334"},"response_status":200,"response_details":null}
256	21.03.2016 21:31:21	DEBUG	RapidgatorNet: Get Account Info for artdog@gmx.com
257	21.03.2016 21:31:21	DEBUG	RapidgatorNet: API:USERINFO | {"response":{"expire_date":1464322607,"traffic_left":"3157002677334"},"response_status":200,"response_details":null}
258	21.03.2016 21:31:21	ERROR	RapidgatorNet: unsupported operand type(s) for /: 'unicode' and 'int'
259	21.03.2016 21:31:21	DEBUG	RapidgatorNet: Account Info: {'premium': False, 'validuntil': None, 'trafficleft': None}
260	21.03.2016 21:31:21	INFO	Activating Plugins...
261	21.03.2016 21:31:21	ERROR	LinkdecrypterCom: Crypter list not found
262	21.03.2016 21:31:22	DEBUG	XFileSharingPro: Pattern loaded - handling 109 hosters
263	21.03.2016 21:31:22	INFO	pyLoad is up and running
264	21.03.2016 21:31:25	INFO	*** New pyLoad Version available ***
265	21.03.2016 21:31:25	INFO	*** Get it here: http://pyload.org/download ***

**Comment by GammaC0de** [comment]
@artdog Is it premium account?

**Comment by artdog** [comment]
Yes it is.

**Comment by artdog** [comment]
Yes it is a valid account. The plugin doesn't seem to be recognising that though. It did work in the past but I was getting errors in the config panel and download was off. I followed some advice to uninstall the package on my NAS and reinstall. That worked but then I had no Rapidgator plugin. 

I downloaded the src and copied both the hoster and account plugins account and hoster directories on my NAS. That seemed to have worked but not for a premium account.

Sorry I should have supplied all the information earlier.

**Comment by artdog** [comment]
I have restarted pyload and here is the new log. There seem to be some extra entries for Rapidagor

274	22.03.2016 07:00:12	INFO	Starting pyLoad 0.4.9
275	22.03.2016 07:00:12	INFO	Using home directory: /i-data/07b224a6/admin/zy-pkgs/pyLoad/etc/pyload
276	22.03.2016 07:00:12	DEBUG	Deleting old pidfile pyload.pid
277	22.03.2016 07:00:12	DEBUG	Remote activated: True
278	22.03.2016 07:00:14	DEBUG	created index of plugins
279	22.03.2016 07:00:14	INFO	ExtractArchive: Activated UnRar UnZip
280	22.03.2016 07:00:15	INFO	Checksum: Checksum validation is disabled in general configuration
281	22.03.2016 07:00:15	DEBUG	UpdateManager: Monitoring file changes
282	22.03.2016 07:00:15	WARNING	Failed activating .___init__
283	22.03.2016 07:00:15	INFO	Activated plugins: BypassCaptcha, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterCom, UnSkipOnFail, UpdateManager, XFileSharingPro
284	22.03.2016 07:00:15	INFO	Deactivate plugins: ._AlldebridCom, ._BypassCaptcha, ._Captcha9kw, ._CaptchaBrotherhood, ._CaptchaTrader, ._Checksum, ._ClickAndLoad, ._DeathByCaptcha, ._DownloadScheduler, ._EasybytezCom, ._Ev0InFetcher, ._ExpertDecoders, ._ExternalScripts, ._ExtractArchive, ._HotFolder, ._IRCInterface, ._ImageTyperz, ._LinkdecrypterCom, ._MergeFiles, ._MultiHome, ._MultishareCz, ._Premium4Me, ._PremiumizeMe, ._RealdebridCom, ._RehostTo, ._UnSkipOnFail, ._UpdateManager, ._XFileSharingPro, ._XMPPInterface, ._ZeveraCom, AlldebridCom, Captcha9kw, CaptchaBrotherhood, DeathByCaptcha, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, Premium4Me, PremiumizeMe, RealdebridCom, RehostTo, XMPPInterface, ZeveraCom
285	22.03.2016 07:00:15	INFO	Downloadtime: True
286	22.03.2016 07:00:15	INFO	Starting ThriftBackend: 0.0.0.0:7227
287	22.03.2016 07:00:16	INFO	Starting threaded webserver: 0.0.0.0:1024
288	22.03.2016 07:00:15	INFO	Free space: 180.21 GiB
289	22.03.2016 07:00:17	INFO	Activating Accounts...
290	22.03.2016 07:00:17	DEBUG	RapidgatorNet: API:LOGIN | {"response":{"session_id":"d5ls32mje6b47j4spuot0bisj7","expire_date":1464322607,"traffic_left":"3150793210091"},"response_status":200,"response_details":null}
291	22.03.2016 07:00:17	DEBUG	RapidgatorNet: Get Account Info for *****@gmx.com
292	22.03.2016 07:00:17	DEBUG	RapidgatorNet: API:USERINFO | {"response":{"expire_date":1464322607,"traffic_left":"3150793210091"},"response_status":200,"response_details":null}
293	22.03.2016 07:00:17	ERROR	RapidgatorNet: unsupported operand type(s) for /: 'unicode' and 'int'
294	22.03.2016 07:00:17	DEBUG	RapidgatorNet: Account Info: {'premium': False, 'validuntil': None, 'trafficleft': None}
295	22.03.2016 07:00:17	INFO	Activating Plugins...
296	22.03.2016 07:00:17	ERROR	LinkdecrypterCom: Crypter list not found
297	22.03.2016 07:00:18	DEBUG	XFileSharingPro: Pattern loaded - handling 109 hosters
298	22.03.2016 07:00:18	INFO	pyLoad is up and running
299	22.03.2016 07:00:21	INFO	*** New pyLoad Version available ***
300	22.03.2016 07:00:21	INFO	*** Get it here: http://pyload.org/download ***

**Comment by GammaC0de** [comment]
@artdog Is this a fresh installation you installed just recently? If yes, please see https://github.com/pyload/pyload/issues/2377#issuecomment-197596414

**Comment by GammaC0de** [comment]
@artdog I will need an account for testing, please account info to nitzo2001 \[AT\] yahoo \[DOT\] com

**Comment by artdog** [comment]
I think this has been solved by following the threads about manually updating the plugins and update manager. I did comment on another issue of failed downloads. A log was requested and I posted one.

**Comment by GammaC0de** [comment]
Ok, Closing
