### ISSUE TITLE
"bad server response: 403 forbidden" for youtube videos

### ISSUE THREAD

**Issue by gs047** [pyload/pyload#2390]
i get this error on more than half of the videos i try to download and in between some of the videos do get downloaded easily.i have look around on the net but found not much regarding this error for pyload.

heres the log output - 

INFO	Added package coldplay containing 1 links
INFO	Download starts: https://www.youtube.com/watch?v=1G4isv_Fylg
DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1;     WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
DEBUG	HOSTER YoutubeCom[79]: Plugin version: 0.50
DEBUG	HOSTER YoutubeCom[79]: Plugin status: testing
WARNING	HOSTER YoutubeCom[79]: Plugin may be unstable
DEBUG	HOSTER YoutubeCom[79]: Config option `use_premium` not found, use default `True`
INFO	HOSTER YoutubeCom[79]: Grabbing link info...
DEBUG	HOSTER YoutubeCom[79]: Link info: {'status': 7, 'hash': {}, 'name': 'watch?v=1G4isv_Fylg', 'url': u'https://www.youtube.com/watch?v=1G4isv_Fylg', 'pattern': {}, 'size': 0}
DEBUG	HOSTER YoutubeCom[79]: Previous link info: {}
INFO	HOSTER YoutubeCom[79]: Link name: watch?v=1G4isv_Fylg
INFO	HOSTER YoutubeCom[79]: Link size: N/D
INFO	HOSTER YoutubeCom[79]: Link status: starting
INFO	HOSTER YoutubeCom[79]: Processing url: https://www.youtube.com/watch?v=1G4isv_Fylg
DEBUG	HOSTER YoutubeCom[79]: LOAD URL https://www.youtube.com/watch?v=1G4isv_Fylg | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
DEBUG	HOSTER YoutubeCom[79]: AVAILABLE STREAMS: [22, 59, 43, 78, 18, 5, 36, 17]
DEBUG	HOSTER YoutubeCom[79]: DESIRED STREAM: ITAG:22 (.mp4 1280x720 Q:8 3D:False) found, allowed
DEBUG	HOSTER YoutubeCom[79]: Chosen fmt: 22
DEBUG	HOSTER YoutubeCom[79]: URL: https://r2---sn-cnoa-a0ie.googlevideo.com/videoplayback?gcr=in&ipbits=0&mm=31&mn=sn-cnoa-a0ie&id=o-ACdabtQVr6k7aeegCH30ybtgSzFk1WaeIj4QqXcEDYy3&mime=video%2Fmp4&pl=22&mt=1458640743&mv=m&ms=au&ip=45.122.145.39&requiressl=yes&initcwndbps=52500&dur=260.086&sver=3&expire=1458662519&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&source=youtube&upn=Rj54fHnLnxQ&ratebypass=yes&fexp=9405994%2C9415030%2C9416126%2C9416985%2C9419451%2C9420452%2C9422596%2C9423496%2C9423661%2C9423662%2C9425064%2C9427902%2C9429563%2C9430020%2C9431012%2C9431363%2C9431402%2C9431452%2C9431842%2C9432417%2C9432484&key=yt6&lmt=1458199469965644&pcm2cms=yes&itag=22
DEBUG	HOSTER YoutubeCom[79]: DOWNLOAD URL https://r2---sn-cnoa-a0ie.googlevideo.com/videoplayback?gcr=in&ipbits=0&mm=31&mn=sn-cnoa-a0ie&id=o-ACdabtQVr6k7aeegCH30ybtgSzFk1WaeIj4QqXcEDYy3&mime=video%2Fmp4&pl=22&mt=1458640743&mv=m&ms=au&ip=45.122.145.39&requiressl=yes&initcwndbps=52500&dur=260.086&sver=3&expire=1458662519&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&source=youtube&upn=Rj54fHnLnxQ&ratebypass=yes&fexp=9405994%2C9415030%2C9416126%2C9416985%2C9419451%2C9420452%2C9422596%2C9423496%2C9423661%2C9423662%2C9425064%2C9427902%2C9429563%2C9430020%2C9431012%2C9431363%2C9431402%2C9431452%2C9431842%2C9432417%2C9432484&key=yt6&lmt=1458199469965644&pcm2cms=yes&itag=22 | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
DEBUG	Chunk 1 failed: Bad server response: 403 Forbidden
DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
WARNING	Download failed: Coldplay - Paradise (Official Video).mp4 | Bad server response: 403 Forbidden
INFO	Debug Report written to debug_YoutubeCom_22-03-2016_10-02-01.zip
DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Coldplay - Paradise (Official Video).mp4 (pid:79)
INFO	ADDON UnSkipOnFail: No duplicates found
DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
DEBUG	All downloads processed

**Comment by gs047** [comment]
hi there bro@GammaC0de 
i tried updated hoster by replacing the old hoster with the one you pointed to into pyload directory but now its throws out another error
"dictionary changed size during iteration"
heres the log of it..

564	14.05.2016 12:47:10	INFO	Added package Watch "Drake - One Dance feat. Kyla & Wizkid (Lyrics)" on YouTube containing 1 links
565	14.05.2016 12:47:12	INFO	Download starts: https://youtu.be/3IIspaicSnY
566	14.05.2016 12:47:12	WARNING	HOSTER YoutubeCom[2176]: Plugin may be unstable
567	14.05.2016 12:47:12	INFO	HOSTER YoutubeCom[2176]: Grabbing link info...
568	14.05.2016 12:47:12	INFO	HOSTER YoutubeCom[2176]: Link name: 3IIspaicSnY
569	14.05.2016 12:47:12	INFO	HOSTER YoutubeCom[2176]: Link size: N/D
570	14.05.2016 12:47:12	INFO	HOSTER YoutubeCom[2176]: Link status: starting
571	14.05.2016 12:47:12	INFO	HOSTER YoutubeCom[2176]: Processing url: https://youtu.be/3IIspaicSnY
572	14.05.2016 12:47:18	WARNING	Download failed: 3IIspaicSnY | dictionary changed size during iteration
573	14.05.2016 12:47:18	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 3IIspaicSnY (pid:246)
574	14.05.2016 12:47:19	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
@gs047 Works fine from here, please read https://github.com/pyload/pyload/issues/2241

If it does not work, please open a new issue, thanks.

**Comment by gs047** [comment]
thanks a ton bro @GammaC0de 
i reinstalled the pyload and its working fine.

**Comment by GammaC0de** [comment]
:+1:
