### ISSUE TITLE
"no module named utils" error on various file

### ISSUE THREAD

**Issue by domignace** [pyload/pyload#2391]
Hi,

I'm having problem with pyload installed on a qnap TS-410 with Entware (opkg install pyload).

When first installing and configuring pyload, everything is fine : e.g. I can use pyload on the web interface.

When restarting pyload, I have "no module named utils" error on the logs :
22.03.2016 20:39:23 INFO      Utilisation du dossier principal : /share/MD0_DATA/.qpkg/Entware-ng/var/pyload
22.03.2016 20:39:32 ERROR     Erreur d'importation UpdateManager : No module named utils
22.03.2016 20:39:32 ERROR     Erreur d'importation MergeFiles : No module named utils
22.03.2016 20:39:32 ERROR     Erreur d'importation ExternalScripts : No module named utils
22.03.2016 20:39:32 ERROR     Erreur d'importation AntiStandby : No module named utils
22.03.2016 20:39:33 ERROR     Erreur d'importation ClickNLoad : No module named utils
22.03.2016 20:39:33 ERROR     Erreur d'importation UnSkipOnFail : No module named utils
22.03.2016 20:39:33 ERROR     Erreur d'importation ExtractArchive : No module named utils
22.03.2016 20:39:33 ERROR     Erreur d'importation XFileSharing : No module named utils
22.03.2016 20:39:33 ERROR     Erreur d'importation UserAgentSwitcher : No module named utils
22.03.2016 20:39:33 INFO      Plugins activés: 
22.03.2016 20:39:33 INFO      Plugins désactivés: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify
22.03.2016 20:39:33 INFO      Temps de téléchargement : True
22.03.2016 20:39:33 INFO      Utilise SSL ThriftBackend
22.03.2016 20:39:33 INFO      Démarre ThriftBackend: 0.0.0.0:7227
22.03.2016 20:39:40 INFO      Free space: 2.83 TiB
22.03.2016 20:39:40 INFO      Starting threaded webserver: 192.168.1.105:8100
22.03.2016 20:39:41 INFO      Activating Accounts...
22.03.2016 20:39:41 INFO      Activating Plugins...
22.03.2016 20:39:41 INFO      pyLoad is up and running
22.03.2016 20:42:46 ERROR     Error importing UptoboxCom: No module named utils
22.03.2016 20:42:46 CRITICAL  'NoneType' object has no attribute 'UptoboxCom'
22.03.2016 20:42:49 ERROR     Error importing UptoboxCom: No module named utils
22.03.2016 20:42:49 CRITICAL  'NoneType' object has no attribute 'UptoboxCom'
22.03.2016 20:42:53 ERROR     Error importing UptoboxCom: No module named utils
22.03.2016 20:42:53 CRITICAL  'NoneType' object has no attribute 'UptoboxCom'
22.03.2016 20:44:56 INFO      Added package Series containing 3 links
22.03.2016 20:44:57 ERROR     Error importing UptoboxCom: No module named utils
22.03.2016 20:44:58 ERROR     Error importing UptoboxCom: No module named utils

I tried to change the file "/opt/share/pyload/module/plugins/hooks/UpdateManager.py" with the one provided in [#2000](https://github.com/pyload/pyload/issues/2000) but I got error about no module named Hook.

Right now, I reinstalled pyload, it is up and running, downloading files. But if I look at the file /opt/share/pyload/module/plugins/hooks/UpdateManager.py :
from module.plugins.internal.utils import encode, exists, fs_join
but there is no /opt/share/pyload/module/plugins/internal/utils.py file nor Utils.py.

the only utils.py files I have are :
/opt/bin/find /opt/share/pyload/ -iname "*utils*"
/opt/share/pyload/module/web/utils.py
/opt/share/pyload/module/lib/jinja2/utils.py
/opt/share/pyload/module/utils.py

Versions:
pyload - 0.4.9-20151216-1
pyopenssl - 0.13.1-1
python - 2.7.11-3
python-base - 2.7.11-3
python-codecs - 2.7.11-3
python-compiler - 2.7.11-3
python-crypto - 2.6.1-1a
python-ctypes - 2.7.11-3
python-curl - 7.19.5.3-1
python-db - 2.7.11-3
python-decimal - 2.7.11-3
python-distutils - 2.7.11-3
python-email - 2.7.11-3
python-gdbm - 2.7.11-3
python-imglib - 1.1.7-1
python-light - 2.7.11-3
python-logging - 2.7.11-3
python-multiprocessing - 2.7.11-3
python-ncurses - 2.7.11-3
python-openssl - 2.7.11-3
python-pydoc - 2.7.11-3
python-sqlite3 - 2.7.11-3
python-unittest - 2.7.11-3
python-xml - 2.7.11-3

Can I debug this further myself ? Do I need to post a Entware issue ?

Regards

**Comment by GammaC0de** [comment]
@domignace Try replacing "/opt/share/pyload/module/plugins/hooks/UpdateManager.py" with https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/e67c25e144991612519940a67d8417ea43069a66/UpdateManager.py instead and the report back

**Comment by domignace** [comment]
Hi GammaC0de,

I have the following errors :
22.03.2016 22:40:10 INFO      Démarrage pyLoad 0.4.9
22.03.2016 22:40:10 INFO      Utilisation du dossier principal : /share/MD0_DATA/.qpkg/Entware-ng/var/pyload
22.03.2016 22:40:17 ERROR     Erreur d'importation UpdateManager : No module named Hook
22.03.2016 22:40:17 ERROR     Erreur d'importation MergeFiles : No module named utils
22.03.2016 22:40:18 ERROR     Erreur d'importation ExternalScripts : No module named utils
22.03.2016 22:40:18 ERROR     Erreur d'importation AntiStandby : No module named utils
22.03.2016 22:40:18 ERROR     Erreur d'importation ClickNLoad : No module named utils
22.03.2016 22:40:18 ERROR     Erreur d'importation UnSkipOnFail : No module named utils
22.03.2016 22:40:18 ERROR     Erreur d'importation ExtractArchive : No module named utils
22.03.2016 22:40:18 ERROR     Erreur d'importation XFileSharing : No module named utils
22.03.2016 22:40:18 ERROR     Erreur d'importation UserAgentSwitcher : No module named utils
22.03.2016 22:40:18 INFO      Plugins activés: 
22.03.2016 22:40:18 INFO      Plugins désactivés: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify
22.03.2016 22:40:18 INFO      Temps de téléchargement : True
22.03.2016 22:40:18 INFO      Espace libre : 2.83 TiB
22.03.2016 22:40:20 INFO      Activation des comptes ...
22.03.2016 22:40:20 INFO      Activation des Extensions...
22.03.2016 22:40:20 INFO      pyLoad est opérationnel

Can I just get the git repo or the whole 4.9 zip and copy it over the existing files ?

**Comment by GammaC0de** [comment]
@domignace See #2241

**Comment by domignace** [comment]
@GammaC0de ,

here are the logs 
22.03.2016 22:59:18 INFO      Démarrage pyLoad 0.4.9
22.03.2016 22:59:18 INFO      Utilisation du dossier principal : /share/MD0_DATA/.qpkg/Entware-ng/var/pyload
22.03.2016 22:59:33 INFO      Plugins activés: AntiStandby, ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
22.03.2016 22:59:33 INFO      Plugins désactivés: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
22.03.2016 22:59:33 INFO      Temps de téléchargement : True
22.03.2016 22:59:33 INFO      Espace libre : 2.83 TiB
22.03.2016 22:59:34 INFO      Activation des comptes ...
22.03.2016 22:59:34 INFO      Activation des Extensions...
22.03.2016 22:59:40 INFO      Starting threaded webserver: 192.168.1.105:8100
22.03.2016 22:59:40 WARNING   ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
22.03.2016 22:59:40 WARNING   ADDON AntiStandby: Unable to change display power state | [Errno 2] No such file or directory
22.03.2016 22:59:41 INFO      ADDON UpdateManager: pyLoad is up to date!
22.03.2016 22:59:44 ERROR     ADDON UpdateManager: Error updating plugin: CAPTCHA UlozTo | Bad version number on the server
22.03.2016 22:59:44 INFO      ADDON UpdateManager: All plugins are up to date!
22.03.2016 22:59:48 ERROR     Error importing Xdcc: No module named utils
22.03.2016 22:59:49 INFO      ADDON XFileSharing: Auto-discover new hosters
22.03.2016 22:59:50 INFO      ADDON XFileSharing: Auto-discover new crypters
22.03.2016 22:59:50 INFO      pyLoad is up and running
22.03.2016 22:59:52 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666

Thank you GammaC0de, except the errors related to UlozTo and  Xdcc import, it seems ok. Do I need to take care about those two errors ?

**Comment by GammaC0de** [comment]
Just delete  Xdcc.py (not XDCC.py)
UlozTo bug has an open issue (https://github.com/pyload/pyload/issues/2377)
