### ISSUE TITLE
Parse error: No file downloaded | Plugin may be out of date 0.00 B BasePlugin

### ISSUE THREAD

**Issue by Piero87** [pyload/pyload#2392]
Hi, I can't download any file with the base plugin, give me this error:

     Parse error: No file downloaded | Plugin may be out of date 0.00 BBasePlugin

how i can solve this problem?

**Comment by vuolter** [comment]
Sample url please.

**Comment by Piero87** [comment]
It's a real debrid generated link, if i give and we download two different places, they block my account, how we can do?

**Comment by Piero87** [comment]
I have just installed DSM 6.0 on my NAS Synology, and i have make a fresh installation of pyload, using this mini guide: https://github.com/pyload/pyload/issues/2000 to update the manager, now when i use the same link of yesterday (and also other link) give me this error:

    Bad server response: 404 Not Found 0.00 B BasePlugin

how i can fix it? help me please :(

**Comment by GammaC0de** [comment]
@Piero87 Instruction in #2000 were updated recently, please read them again..

**Comment by Piero87** [comment]
i make an update here: [https://github.com/pyload/pyload/issues/2394](url)

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/969b99f02f7db10103eb426e0a31e569998a82ae

**Comment by Piero87** [comment]
i have tried but doesn't work, what i have to do?

**Comment by Piero87** [comment]
sorry i have update and restarted now work!! thank you very much!

**Comment by Piero87** [comment]
I have another question, when the Realdebrid plugin will be available?

**Comment by GammaC0de** [comment]
@Piero87 See #2121
