### ISSUE TITLE
Error importing BasePlugin: No module named utils

### ISSUE THREAD

**Issue by vrapp** [pyload/pyload#2393]
Pyload is installed on Asus router by entware.

Python: 	2.7.11 (default, Mar 8 2016, 08:21:40) [GCC 5.3.0]
OS: 	posix linux2 Linux HOMELAN 2.6.36.4brcmarm #2 SMP PREEMPT Sun Mar 20 16:06:18 EDT 2016 armv7l
pyLoad version: 	0.4.9

When I add a URL to download to the queue, it fails with the following in the log:

111	23.03.2016 06:52:37	INFO	Added package kr1 containing 1 links
112	23.03.2016 06:52:37	ERROR	Error importing BasePlugin: No module named utils
113	23.03.2016 06:52:38	ERROR	Error importing BasePlugin: No module named utils
114	23.03.2016 06:52:38	CRITICAL	'NoneType' object has no attribute 'BasePlugin'

**Comment by GammaC0de** [comment]
See #2000

**Comment by vrapp** [comment]
Did not help. Patched the UploadManager.py, then here's the log.

**Comment by GammaC0de** [comment]
Please delete your `userplugins` directory then retry

**Comment by vrapp** [comment]
did not help.

556	31.07.2015 19:00:45	INFO	Starting pyLoad 0.4.9
557	31.07.2015 19:00:45	INFO	Using home directory: /tmp/mnt/sda1/entware/var/pyload
558	31.07.2015 19:00:45	DEBUG	Remote activated: False
559	31.07.2015 19:00:48	DEBUG	created index of plugins
560	31.07.2015 19:00:49	ERROR	Error importing MergeFiles: No module named utils
561	31.07.2015 19:00:49	ERROR	Error importing ExternalScripts: No module named utils
562	31.07.2015 19:00:49	ERROR	Error importing AntiStandby: No module named utils
563	31.07.2015 19:00:49	ERROR	Error importing ClickNLoad: No module named utils
564	31.07.2015 19:00:49	ERROR	Error importing UnSkipOnFail: No module named utils
565	31.07.2015 19:00:50	ERROR	Error importing ExtractArchive: No module named utils
566	31.07.2015 19:00:50	ERROR	Error importing XFileSharing: No module named utils
567	31.07.2015 19:00:50	ERROR	Error importing UpdateManager: No module named Hook
568	31.07.2015 19:00:50	ERROR	Error importing UserAgentSwitcher: No module named utils
569	31.07.2015 19:00:50	INFO	Activated plugins:
570	31.07.2015 19:00:50	INFO	Deactivate plugins: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify
571	31.07.2015 19:00:50	INFO	Downloadtime: True
572	31.07.2015 19:00:54	INFO	Starting builtin webserver: 192.168.1.1:8000
573	31.07.2015 19:00:54	INFO	Free space: 1.03 TiB
574	31.07.2015 19:00:54	INFO	Activating Accounts...
575	31.07.2015 19:00:54	INFO	Activating Plugins...
576	31.07.2015 19:00:54	INFO	pyLoad is up and running
577	29.03.2016 17:20:47	ERROR	Error importing BasePlugin: No module named utils
578	29.03.2016 17:20:47	INFO	Added package kr containing 1 links
579	29.03.2016 17:20:48	ERROR	Error importing BasePlugin: No module named utils
580	29.03.2016 17:20:48	CRITICAL	'NoneType' object has no attribute 'BasePlugin'

**Comment by Velociraptor85** [comment]
@vuolter @GammaC0de could you close all duplicate Issues? Or is there an reason for them to stay open?

**Comment by vuolter** [comment]
@Velociraptor85 Some duplicates must stay open as reminders or for its debug reports or for other reasons or because I forgot to close them XD (like this case). Ah, thanks. ;)

**Comment by Velociraptor85** [comment]
@vuolter but if we reference the original issue in an duplicate than it will be linked and we can close it ?

Is it OK if I check for unclosed duplicates and announce them like this one? So we get rid of those.

**Comment by vuolter** [comment]
@Velociraptor85 There're 40 open duplicates right now: https://github.com/pyload/pyload/labels/duplicate
Anyhow, not problem for me if you want check it all, but thank you for your effort. ;)
