### ISSUE TITLE
"Error 403: Forbidden" when trying to use flashgot and ClickAndLoad plugin

### ISSUE THREAD

**Issue by domignace** [pyload/pyload#2398]
Hi everybody,

I am not able to configure the ClickAndLoad plugin and flashgot.
My configuration :
- nas where pyload is installed ip 192.168.1.105
- firefox where flashgot is installed ip 192.168.100

I configured pyload webinterface to be listening on 192.168.1.105:8100 . I am able to access the webinterface from firefox using the address http://192.168.1.105:8100.

The clickandload conf in plugin.conf is 
ClickNLoad - "ClickNLoad":
        queue;collector dest : "Add packages to" = collector
        bool activated : "Activated" = True
        bool extern : "Listen for external connections" = True
        int port : "Port" = 9666

The flashgot configuration is set to pyload on the url http://192.168.1.105:9666/flashgot

When using flashgot to save a link, a popup telling pyload is not responding and the log contains :
2016-03-26T16:27:11.723Z Preprocessing done in ms10
2016-03-26T16:27:11.724Z Starting dispatch
2016-03-26T16:27:12.081Z pyLoad response status:
403
Forbidden
2016-03-26T16:27:35.577Z Dispatch done in ms23853
Total processing time: ms23864

When accessing http://192.168.1.105:9666/flashgot with firefox :
Error 403: Forbidden
Sorry, the requested URL 'http://192.168.1.105:9666/flashgot' caused an error:
Forbidden
 

When using curl from the laptop where firefox is installed :
curl http://192.168.1.105:9666/flashgot
``
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error 403: Forbidden</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error 403: Forbidden</h1>
            <p>Sorry, the requested URL <tt>&#039;http://192.168.1.105:9666/flashgot&#039;</tt>
               caused an error:</p>
            <pre>Forbidden</pre>
        </body>
    </html>
``

When using curl on the nas with target 192.168.1.105 :
curl http://192.168.1.105:9666/flashgot

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error 403: Forbidden</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error 403: Forbidden</h1>
            <p>Sorry, the requested URL <tt>&#039;http://192.168.1.105:9666/flashgot&#039;</tt>
               caused an error:</p>
            <pre>Forbidden</pre>
        </body>
    </html>

When  using curl on the nas with target 127.0.0.1 :
curl http://127.0.0.1:9666/flashgot
I am getting lot of xml stuff 
...
``
			<label>Texte
			<span class="small">Veuillez taper le texte du captcha.</span>
			</label>
			<input id="cap_result" name="cap_result" type="text" size="20" />
``
...

The log of pyload tells :
when adding self.log_info(_("Proxy listening on %s:%s") % (self.cnl_ip, self.cnl_port)), the activate function : 
ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666

Am I missing something in the pyload or ClickAndLoad configurations to make the ClickAndLoad listen on 192.168.1.105 (i.e. not only locally) ?

Regards,

**Comment by GammaC0de** [comment]
Do you see this line in the log?
ADDON ClickNLoad: Connection from ...

**Comment by domignace** [comment]
@GammaC0de , 

no Connection from :
grep -i "connection" /share/MD0_DATA/.qpkg/Entware-ng/var/pyload/Logs/log.txt gives nothing

**Comment by GammaC0de** [comment]
I forgot, you should enable debug mode first

**Comment by domignace** [comment]
@GammaC0de ,

I have indeed this line : 
27.03.2016 01:01:02 DEBUG     ADDON ClickNLoad: Connection from 192.168.1.235:55680

**Comment by domignace** [comment]
@GammaC0de ,
I have a login and password for the webinterface, is this matter for remote connection ?

**Comment by GammaC0de** [comment]
No, ClickNLoad does not requires user and password
   
@GammaC0de ,
I have a login and password for the webinterface, is this matter for remote connection ?

**Comment by domignace** [comment]
Hi,

when I initially set up my pyload server, I put 192.168.1.105 for :
 ip host : "IP" = 192.168.1.105

Setting this back to 0.0.0.0 makes pyload/cnl working.
 ip host : "IP" = 0.0.0.0

Sorry for the false report because of a misconfiguration and thank you for your help.

Regards,

**Comment by GammaC0de** [comment]
:+1:
