### ISSUE TITLE
DSM 6, updatemanager, notification

### ISSUE THREAD

**Issue by tomtompy** [pyload/pyload#2399]
Hi,

  -  I update my syno
  - can't launch Pyload…

  -  do a fresh install from pyLoad-0.4.9-4-armv5.spk at http://spk.unzureichende.info/dl/pyLoad-0.4.9-4-armv5.spk

-    find why : Pyload user was disabled
-    Be sade

So I make a manual update on UpdateManager.py … but plugin are not update and I can see a notification : pyload update available…

What's wrong ?

**Comment by GammaC0de** [comment]
It seems that your `UpdateManager.py` still not correct..
Find where `UpdateManager.py` is located and replace it with the one on #2000.
Also, DEBUG log may help.

**Comment by tomtompy** [comment]
`/usr/syno/synoman/webman/3rdparty/pyload# ls
application.cfg  help  helptoc.conf  images  index.conf  texts`
don't find your folder, pyload is here but no modules inside.

**Comment by GammaC0de** [comment]
Ok, so search for `UpdateManager.py` everywhere

**Comment by tomtompy** [comment]
is here `'/volume1/@appstore/pyload/pyload/module/plugins` and in `hooks` maybe that the problem.

**Comment by sraedler** [comment]
I guess it ist something like

/var/package/pyload/target/pyload/modules/plugins/hooks

**Comment by tomtompy** [comment]
It's look better now :+1:  i put in the wrong folder !

**Comment by GammaC0de** [comment]
:+1:
