### ISSUE TITLE
Request for smule.com

### ISSUE THREAD

**Issue by psycholyzern** [pyload/pyload#2402]
I want to download the video on smule.com
Seems that they use javascript to decode the encoded url.

I see this guys, managed to use the same decoding method using javascript too, http://thebluebyte.com/getsmule/home/template/javascript/sutils.js

I can't understand what that script do in order to decode the link, so I'm asking if you can make this as plugin for pyload?

This is the url sample of a video https://www.smule.com/recording/eyshila-nada-pode-calar-um-adorador-eyshila/443694955_179520763

**Comment by igel-kun** [comment]
The code I committed in pull request #2562 downloads the sample file for me.

**Comment by GammaC0de** [comment]
:+1:

**Comment by psycholyzern** [comment]
Thank you so much :)
