### ISSUE TITLE
UploadedTo - Premium (No)

### ISSUE THREAD

**Issue by thermalhack** [pyload/pyload#2403]
Hello,
I have done several fresh installs of pyload onto my raspberry pi B and in each time, UploadedTo shows that my account is not premium. It says "Premium - No".

When I try to download anything, it downloads a file which is a few kbs in size.

Please help.

<img width="452" alt="screenshot 2016-03-30 20 09 41" src="https://cloud.githubusercontent.com/assets/17778605/14154269/6dece3bc-f6b3-11e5-95ba-0bb5435151ae.png">

**Comment by GammaC0de** [comment]
@thermalhack Account is needed for testing, please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com.

**Comment by thermalhack** [comment]
i wont be giving my account password.... sorry... it works fine on jdownloader. please tell me how else I can help

**Comment by GammaC0de** [comment]
You can change to a temporary password and after that change it back, else I cannot fix this issue.

**Comment by GammaC0de** [comment]
Closing due to no response.

**Comment by thermalhack** [comment]
Can I re-open this issue and provide login details? I've tried to get this working on 2 rapsberry pi's, using both Noobs debian, Jessie & Wheezy.

It was working fine before a refresh SD card wipe.

Also - I have installed the addon plugin for my DNS 320L CLoud Nas, and the account shows that it is premium, however I would prefer to run pyload off a raspberry pi.

Thanks

**Comment by GammaC0de** [comment]
Can you try this version?

```python
# -*- coding: utf-8 -*-

import re
import time

from module.plugins.internal.Account import Account
from module.plugins.internal.misc import json


class UploadedTo(Account):
    __name__    = "UploadedTo"
    __type__    = "account"
    __version__ = "0.41"
    __status__  = "testing"

    __description__ = """Uploaded.to account plugin"""
    __license__     = "GPLv3"
    __authors__     = [("Walter Purcaro", "vuolter@gmail.com"         ),
                       ("GammaC0de",      "nitzo2001[AT]yahoo[DOT]com")]


    COOKIES = False


    def grab_info(self, user, password, data):
        json_data = json.loads(self.load("http://uploaded.net/api/user"))

        premium = True if json_data['account']['alias']['name']['status'] == "premium" else False

        expiredate_str = json_data['account']['alias']['name']['expire']
        if expiredate_str == "unlimited":
            validuntil = -1
        else:
            validuntil = time.mktime(time.strptime(expiredate_str, "%Y-%m-%d %H:%M:%S"))

        trafficleft = self.parse_traffic(json_data['account']['traffic']['available'], "B")

        return {'validuntil' : validuntil,
                'trafficleft': trafficleft,
                'premium'    : premium}


    def signin(self, user, password, data):
        try:
            self.load("http://uploaded.net/me")

            html = self.load("http://uploaded.net/io/login",
                             post={'id': user,
                                   'pw': password})

            m = re.search(r'"err":"(.+?)"', html)
            if m is not None:
                self.fail_login(m.group(1))

        except Exception, e:
            self.log_error(e.message, trace=True)
            self.fail_login(e.message)
```

**Comment by thermalhack** [comment]
Hi, when replacing UploadedTo.py in /usr/shares//pyload/module/plugins/accounts, I get:

An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/usr/share/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/usr/share/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/usr/share/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/usr/share/pyload/module/utils.py", line 165, in new
return func(*args)
File "/usr/share/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/usr/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

**Comment by GammaC0de** [comment]
You should put it in `userplugins/accounts` directory.

**Comment by thermalhack** [comment]
I get the same error..

**Comment by GammaC0de** [comment]
Have you tried refreshing your `userplugins` folder (see #2241)?

**Comment by thermalhack** [comment]
Thank you so much. It is working now!

**Comment by GammaC0de** [comment]
:+1:
with the original version or the one above?
