### ISSUE TITLE
some plugins are duplicates

### ISSUE THREAD

**Issue by tomtompy** [pyload/pyload#2406]
Hi,

How to fix this, I have some duplicate plugins : ClickNLoad and ClickAndLoad…
I am not an chmod ninja and command line is not easy but I can log as root an do some command.

**Comment by GammaC0de** [comment]
Delete your `userplugins` directory and then follow the instructions in #2000

**Comment by tomtompy** [comment]
what is `userplugins` I just have `plugins` ?

**Comment by GammaC0de** [comment]
If you go to the http://\<IP_OF_PYLOAD\>:8000/info , you will see the location of the "Config Folder". 
Under this folder there should be a `userplugins` folder.

**Comment by tomtompy** [comment]
OK, found and delete, #2000 was do before this problem. Restart and restart : Always duplicate…
I have a lot of WARNINGS :
```
02.04.2016 23:34:55	WARNING	ADDON UpdateManager: Error removing `/volume1/@appstore/pyload/pyload/module/plugins/internal/AbstractExtractor.pyc` | [Errno 13] Permission denied: '/volume1/@appstore/pyload/pyload/module/plugins/internal/AbstractExtractor.pyc'
419	02.04.2016 23:34:55	WARNING	ADDON UpdateManager: Error removing `/volume1/@appstore/pyload/pyload/module/plugins/internal/AbstractExtractor.py` | [Errno 13] Permission denied: '/volume1/@appstore/pyload/pyload/module/plugins/internal/AbstractExtractor.py'
418	02.04.2016 23:34:55	WARNING	ADDON UpdateManager: Error removing `/volume1/@appstore/pyload/pyload/module/plugins/hoster/ShareRapidCom.py` | [Errno 13] Permission denied: '/volume1/@appstore/pyload/pyload/module/plugins/hoster/ShareRapidCom.py'
417	02.04.2016 23:34:55	WARNING	ADDON UpdateManager: Error removing `/volume1/@appstore/pyload/pyload/module/plugins/hoster/RapidshareCom.py` | [Errno 13] Permission denied: '/volume1/@appstore/pyload/pyload/module/plugins/hoster/RapidshareCom.py'
416	02.04.2016 23:34:55	WARNING	ADDON UpdateManager: Error removing `/volume1/@appstore/pyload/pyload/module/plugins/hooks/XMPPInterface.py` | [Errno 13] Permission denied: '/volume1/@appstore/pyload/pyload/module/plugins/hooks/XMPPInterface.py'
415	02.04.2016 23:34:55	WARNING	ADDON UpdateManager: Error removing `/volume1/@appstore/pyload/pyload/module/plugins/hooks/RehostTo.py` | [Errno 13] Permission denied: '/volume1/@appstore/pyload/pyload/module/plugins/hooks/RehostTo.py'
414	02.04.2016 23:34:55	WARNING	ADDON UpdateManager: Error removing `/volume1/@appstore/pyload/pyload/module/plugins/hooks/RealdebridCom.py` | [Errno 13] Permission denied: '/volume1/@appstore/pyload/pyload/module/plugins/hooks/RealdebridCom.py'
```

**Comment by GammaC0de** [comment]
You should grant write permissions to "/volume1/@appstore/pyload/pyload/module/plugins" folder.

**Comment by tomtompy** [comment]
I'm too bad in chmod and chown… I fail to grant, so I launch a new install !

**Comment by tomtompy** [comment]
Here is my step :
- remove Pyload from my package gui (DSM 6)
- install enkidu package
- reactivate the pyload user
- stop/start pyload 
- ssh in admin, sudo -i to be root, go to the folder, nano the file UpdateManger.py get in #2000 and remove all lines and paste the new inside…
- check the log in pylaod… refresh the log
- see the nofitcation to restart
- restart  (and wait without clicking)
:-1:  and fail, duplicate plugins again :(

**Comment by GammaC0de** [comment]
This is because those plugins are bundled with the pyload package and fails to be removed because of the permissions.

These commands should solve this:
```
chown -R pyload:pyload /volume1/@appstore/pyload/pyload/module/plugins
chmod -R 774 /volume1/@appstore/pyload/pyload/module/plugins
```

**Comment by tomtompy** [comment]
`chown: invalid group: ‘pyload:pyload’` 
I change to `pyload:users`

**Comment by GammaC0de** [comment]
Ok, does it work now?

**Comment by tomtompy** [comment]
At this time, plugins are duplicates… try a restart!

**Comment by tomtompy** [comment]
May be this is not a problem ?
` C1NeonCom 
C1neonCom 
CCF 
Captcha9Kw 
Captcha9kw 
CaptchaBrotherhood 
CaptchaTrader`

**Comment by GammaC0de** [comment]
what?

**Comment by tomtompy** [comment]
Is it normal to have  Captcha9Kw and Captcha9kw in select menu ?

**Comment by tomtompy** [comment]
in <ip>:8000/settings/ #plugins #menu

**Comment by GammaC0de** [comment]
Just edit the `plugin.conf` under the config directory and remove the duplicate sections

**Comment by tomtompy** [comment]
I delete it :) and restart, it's look better now !
AND… DONE !

**Comment by GammaC0de** [comment]
:+1:
