### ISSUE TITLE
pyload 0.4.9-2 DSM6.0 No premium accounts activation - error importing UploadedTo: No module named Account

### ISSUE THREAD

**Issue by birne999** [pyload/pyload#2409]
Hi.
I managed to install pyload 0.4.9-2 in my new Synology DS716+ DSM6.0. I was able to activate my premium accounts Uploaded.to and ShareOnline.biz once. After the first download was done I wasn´t able to get them activatet again. The webserver page gives me an ERROR after typing in my accounts data. Uninstall/Install, Reboot, no cuccess. Pyload is up and running but no premium account usable. The log message:error importing UploadedTo: No module named Account. And: error importing ShareonlineBiz: No module named Account
I got pyload from SynoCommunity directly from the Paket-Center.
What can I do to get the premium accounts back?

**Comment by GammaC0de** [comment]
Surly, your installation is not ok,
see #2399 and #2397 for DSM installation.

**Comment by vuolter** [comment]
pyLoad package from Synology Paket-Center is apparently broken.
