### ISSUE TITLE
MultiHome plugin bug: global name 'self' is not defined

### ISSUE THREAD

**Issue by OhSoGood** [pyload/pyload#2410]
Hi,

I tried to use the MultiHome plugin (defining interfaces as 'eth0;eth1' ) but, when downloading anything, I systematically get in the log: global name 'self' is not defined

I'm using pyload from git master (pulled as of 4/4/2016).

Thanks for the help (and thanks for pyload of course).

**Comment by sodd** [comment]
Hi,
current working branch is stable

**Comment by OhSoGood** [comment]
I fixed the 3 issues on the github version. Here it is.

[MultiHome_py.txt](https://github.com/pyload/pyload/files/204179/MultiHome_py.txt)

**Comment by GammaC0de** [comment]
This issue already been fixed with https://github.com/pyload/pyload/commit/55e331cda19cb4ec3d9ef134de1f389f3c914e88
