### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by nobody1407** [pyload/pyload#2412]
Hello again ;)

I have a problem with pyload and Debian 8.
I cloned the source code and after that I wait 25 minutes (screenshot) without any reaction..
```
git clone https://github.com/pyload/pyload.git
python /opt/pyload/pyLoadCore.py
```

![038](https://cloud.githubusercontent.com/assets/17329434/14306700/a29e2a88-fbc9-11e5-8361-cfde5f062eb0.PNG)

**Comment by GammaC0de** [comment]
`git clone -b stable https://github.com/pyload/pyload.git`

Have you followed #2000?

**Comment by nobody1407** [comment]
Oh damn.. I´m so sorry.. My firewall (ufw) has blocked the port for pyload GUI

**Comment by GammaC0de** [comment]
:+1:
