### ISSUE TITLE
Pyload on readynas OS6 RN102

### ISSUE THREAD

**Issue by Gigi31** [pyload/pyload#2415]
Hello
Why pyLoad is no longer installed in the aplications readynas OS6
Otherwise there there a tutorial to install it on a 102 readynas
Thank you

**Comment by GammaC0de** [comment]
>Why pyLoad is no longer installed in the aplications readynas OS6

You should ask readynas's support

Just a guess:
* Install python app
* Follow the instructions in #2000

**Comment by Gigi31** [comment]
Hello
I asked and here is their response :


 Hello Gigi31,

There was a problem with the app before and since then the developer hasn't submitted the app to the app page.

Regards,
JennC
NETGEAR Community Team

TY

**Comment by Velociraptor85** [comment]
@Gigi31 here a Doc for DSM https://github.com/pyload/pyload/issues/2397 maybe it will help you else please close the issue since #2000 is a good how-to by GammaC0de

**Comment by Velociraptor85** [comment]
@Gigi31 @GammaC0de @vuolter please close main issue https://github.com/pyload/pyload/issues/2361
