### ISSUE TITLE
Pyload crash after new Account.py

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#2416]
With the new Account.py pyload crashes with this error:
<pre>09.04.2016 17:13:27 INFO      Activating Accounts...
09.04.2016 17:13:27 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
09.04.2016 17:13:27 ERROR     Error importing ShareonlineBiz: No module named Account
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/accounts/ShareonlineBiz.py", line 5, in <module>
    from module.plugins.internal.Account import Account
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
ImportError: No module named Account
Traceback (most recent call last):
  File "pyLoadCore.py", line 667, in <module>
    main()
  File "pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable`</pre>

**Comment by GammaC0de** [comment]
From the log, it seems like you are missing `userplugins/Account.py`,  can you check please if `userplugins/Account.py` is ok?

**Comment by wastez** [comment]
Yes sure it is there. 
After deleting it so that it cant use the old version in modules folder everything is working again.

**Comment by wastez** [comment]
But as soon the updatemangager load the new version again pyload will Crash again.

**Comment by GammaC0de** [comment]
Can you edit `userplugins/internal/Account.py` and undo https://github.com/pyload/pyload/commit/8560ff226c2fbc0ee238b6a58077927a862f48a1 and see if it helps?

**Comment by wastez** [comment]
As i Said 0.72 is working.

**Comment by wastez** [comment]
Modules folder contains 0.72. 
or should the 0.72 tried in userplugins folder?

**Comment by GammaC0de** [comment]
0.72 should be in userplugins
in modules should be 0.2

**Comment by wastez** [comment]
No because i loaded the source just a few days ago, there was 0.72 in modules folder.

**Comment by GammaC0de** [comment]
That depends on how you have installed pyLoad:
if from https://github.com/pyload/pyload/releases, account.py has v0.2
if from https://github.com/pyload/pyload/archive/stable.zip, account.py  had of course 0.72 

Can you post full debug log from the console?

**Comment by wastez** [comment]
Also 0.73 is not working in userplugin/internal folder.

**Comment by GammaC0de** [comment]
Ok, can you post full debug log from the console please?

**Comment by wastez** [comment]
Here is a full log without changes from 0.73:
<pre><code>
09.04.2016 18:16:16 INFO      starte pyLoad 0.4.9
09.04.2016 18:16:16 INFO      Benutze Home-Verzeichnis: /opt/pyload/.pyload
09.04.2016 18:16:16 DEBUG     Deleting old pidfile pyload.pid
09.04.2016 18:16:16 DEBUG     Remote activated: False
09.04.2016 18:16:16 DEBUG     created index of plugins
09.04.2016 18:16:16 DEBUG     Redirected import module.plugins.internal.misc -> userplugins.internal.misc
09.04.2016 18:16:16 INFO      ADDON ExternalScripts: Activated scripts in folder `package_finished`: unrar_pwlist_remaster.sh
09.04.2016 18:16:16 INFO      Aktivierte Plugins: AppleDeviceNotify, ClickNLoad, EventMapper, ExternalScripts, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
09.04.2016 18:16:16 INFO      Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
09.04.2016 18:16:16 INFO      Downloadzeit: True
09.04.2016 18:16:17 INFO      Starting threaded webserver: 0.0.0.0:8000
09.04.2016 18:16:17 INFO      Free space: 83.79 GiB
09.04.2016 18:16:17 INFO      Activating Accounts...
09.04.2016 18:16:17 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
09.04.2016 18:16:17 ERROR     Error importing ShareonlineBiz: No module named Account
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/accounts/ShareonlineBiz.py", line 5, in <module>
    from module.plugins.internal.Account import Account
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
ImportError: No module named Account
Traceback (most recent call last):
  File "pyLoadCore.py", line 667, in <module>
    main()
  File "pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable
</code></pre>

**Comment by wastez** [comment]
If the same file is just in modules/internal everything is working.

**Comment by GammaC0de** [comment]
Working with 0.73?

**Comment by wastez** [comment]
Didnt tried the 0.73 in modules folder because i have almost no time in the moment.
But if 0.72 or 0.73 is in userplugin folder the error above appears.

**Comment by GammaC0de** [comment]
Ok, can you cange back [Account.py#L206](https://github.com/pyload/pyload/blob/8560ff226c2fbc0ee238b6a58077927a862f48a1/module/plugins/internal/Account.py#L206) line in userplugin and see if it helps (without changing the version number)?

Also, be aware that the file should be named Account.py and not account.py

**Comment by wastez** [comment]
Also tried it, it is not working in the userplugin/internal folder.

**Comment by wastez** [comment]
The below debug log was with it. 
Versionnumber unchanged, undone changes.

**Comment by GammaC0de** [comment]
Ok, When you have time:
Delete userplugins/internal/Account.py
Copy 0.73 to modules folder
Start pyload and see if it works

**Comment by wastez** [comment]
Ok....
0.73 is working in modules folder.

**Comment by GammaC0de** [comment]
Ok, so it's seems like a problem in your setup, maybe a permission issue in userplugins?

**Comment by wastez** [comment]
Debian.
But it is for sure no permission problem.
Permissions are set correctly, checked it right now.

**Comment by GammaC0de** [comment]
Tested on my setup (windows) and worked fin.

Maybe try installing from https://github.com/pyload/pyload/releases/download/v0.4.9/pyload-v0.4.9-all.deb and follow #2000

**Comment by GammaC0de** [comment]
Can we close this?

**Comment by wastez** [comment]
Yes we can close this, was a annoying Problem.
