### ISSUE TITLE
Rapidgator - Bad server response: 401 Unauthorized

### ISSUE THREAD

**Issue by tbfvrs** [pyload/pyload#2419]
Hi
Since couple of days RG prem doesn't work;
Pyload cannot login;

371	11.04.2016 02:28:38	DEBUG	ACCOUNT RapidgatorNet: Reached login timeout for user...
372	11.04.2016 02:28:38	INFO	ACCOUNT RapidgatorNet: Login user...
373	11.04.2016 02:28:38	DEBUG	ACCOUNT RapidgatorNet: LOAD URL http://rapidgator.net/api/user/login | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'username': ..., 'password': '**********'} | ref=True | just_header=False
374	11.04.2016 02:28:38	ERROR	ACCOUNT RapidgatorNet: Bad server response: 401 Unauthorized
375	11.04.2016 02:28:38	ERROR	ACCOUNT RapidgatorNet: Could not login user ... | Login handshake has failed
376	11.04.2016 02:28:38	INFO	ACCOUNT RapidgatorNet: Grabbing account info for user ...
377	11.04.2016 02:28:38	DEBUG	ACCOUNT RapidgatorNet: LOAD URL http://rapidgator.net/api/user/info | redirect=True | cookies=True | get={'sid': None} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
378	11.04.2016 02:28:38	ERROR	ACCOUNT RapidgatorNet: Bad server response: 401 Unauthorized
379	11.04.2016 02:28:38	DEBUG	ACCOUNT RapidgatorNet: Account info for user ...: {'login': {'timestamp': 1460356118.775944, 'password': '**********', 'valid': False}, 'data': {'premium': False, 'plugin': , 'trafficleft': None, 'maxtraffic': None, 'sid': None, 'validuntil': None, 'login': '...', 'type': 'RapidgatorNet', 'options': {'limitdl': ['0']}}} 

Please fix this issue;

**Comment by GammaC0de** [comment]
Account is needed for testing.
Please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com

**Comment by tbfvrs** [comment]
24hr acc will be enough?

**Comment by GammaC0de** [comment]
I hope.

**Comment by tbfvrs** [comment]
Sent on given yahoo acc

**Comment by tbfvrs** [comment]
Unfortunately after chaging the plugin and restarting pyload still:

538	12.04.2016 03:15:01	INFO	ACCOUNT RapidgatorNet: Removing user ...
539	12.04.2016 03:15:25	INFO	ACCOUNT RapidgatorNet: Adding user ...
540	12.04.2016 03:15:25	DEBUG	ACCOUNT RapidgatorNet: Reached login timeout for user...
541	12.04.2016 03:15:25	INFO	ACCOUNT RapidgatorNet: Login user ...
542	12.04.2016 03:15:25	DEBUG	ACCOUNT RapidgatorNet: LOAD URL http://rapidgator.net/api/user/login | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'username': ...., 'password': '**********'} | ref=True | just_header=False
543	12.04.2016 03:15:25	ERROR	ACCOUNT RapidgatorNet: Bad server response: 401 Unauthorized
544	12.04.2016 03:15:25	ERROR	ACCOUNT RapidgatorNet: Could not login user ... | Login handshake has failed
545	12.04.2016 03:15:25	INFO	ACCOUNT RapidgatorNet: Grabbing account info for user ...
546	12.04.2016 03:15:25	DEBUG	ACCOUNT RapidgatorNet: LOAD URL http://rapidgator.net/api/user/info | redirect=True | cookies=True | get={'sid': None} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
547	12.04.2016 03:15:25	ERROR	ACCOUNT RapidgatorNet: Bad server response: 401 Unauthorized
548	12.04.2016 03:15:25	DEBUG	ACCOUNT RapidgatorNet: Account info for user ...: {'login': {'timestamp': 1460445325.255242, 'password': '**********', 'valid': False}, 'data': {'premium': False, 'plugin': , 'trafficleft': None, 'maxtraffic': None, 'sid': None, 'validuntil': None, 'login': ..., 'type': 'RapidgatorNet', 'options': {'limitdl': ['0']}}}

But maybe i did sth wrong...

**Comment by GammaC0de** [comment]
@tbfvrs 
```
543 12.04.2016 03:15:25 ERROR ACCOUNT RapidgatorNet: Bad server response: 401 Unauthorized
544 12.04.2016 03:15:25 ERROR ACCOUNT RapidgatorNet: Could not login user ... | Login handshake has failed
```

It seems that the login fails because wrong username or password, are you sure your account is valid?

**Comment by tbfvrs** [comment]
Yeah, I;ve checked twice;
Geez I forgot the command to install pyl again, can you help me here?

**Comment by GammaC0de** [comment]
See #2000

**Comment by tbfvrs** [comment]
Thanks;
Reinstall fixed the issue:)
