### ISSUE TITLE
[Bug] UploadedTo account error in VALID_UNTIL_PATTERN

### ISSUE THREAD

**Issue by kagir** [pyload/pyload#2420]
The plugin can not detect the account expiration date because of an error in the regex VALID_UNTIL_PATTERN.

original
VALID_UNTIL_PATTERN =` r'<td>Duration:</td>\s*<th>(.+?)<'`
my solution
VALID_UNTIL_PATTERN  = `r'<td>Duration:</td>\s*<th>\s*(.+?)<'`

**Comment by GammaC0de** [comment]
Can you post an example text?

**Comment by kagir** [comment]
I have tested the regex on my account
