### ISSUE TITLE
IPKG fresh install; missing account plugins

### ISSUE THREAD

**Issue by StarScream159** [pyload/pyload#2425]
Hey guys,

After updating today (there were a lot of plugins out of date) I ran into many many errors and decided to just start over and re-setup my install.

I am installing to optware on a Asus RT-N16 router.

I downloaded the IPKG install package from _https://github.com/pyload/pyload/releases/download/v0.4.9/pyload-v0.4.9-noarch.ipk_ and installed it using "_ipkg install pyload-v0.4.9-noarch.ipk_". Afterward I went through the setup process and and then logged in. I went to add my premium hoster account but couldn't find it in the list. The list of hosts is really small, and doesn't contain a lot of the plugins from the git folder (_https://github.com/pyload/pyload/tree/stable/module/plugins/accounts_). I see the _/opt/share/pyload/module/plugins/accounts_ folder doesn't contain a lot of the items the repo does.

I'm specifically looking for Rapidgator. I see it in the list, how can I go about installing it?

Thanks.

**Comment by GammaC0de** [comment]
@StarScream159 See #2000

**Comment by StarScream159** [comment]
Thanks so much @GammaC0de for the quick reply. This worked. No more errors and I added my account back in fine.

**Comment by GammaC0de** [comment]
:+1:
