### ISSUE TITLE
Auto delete files in download or extract directory after X hours

### ISSUE THREAD

**Issue by sebaro11** [pyload/pyload#2429]
Hi,

since I got a working pyLoad version (Windows Server) with extracting archives I want to ask, if there is any plugin or script that can be set up to delete my downloaded and extracted files after X hours.
Because my disk space is limited and manuelly deleting is time consuming, I would wonder if there is any plugin for that.

Thanks for your help.
Your doing a great job with pyLoad!

**Comment by Nippey** [comment]
Hi sebaro11,

[Disclaimer: I'm just a pyLoad user, too]

back then when I had pyload running on my raspberrypi, I automatically removed *.rar files with a bash script. 

I made the assertion that I only need to clean up, when new files are added, so I created an external script to execute on `download_preparing`.
Put this file in the respective directory monitored by the addon `ExternalScripts.py` and it will be executed automatically.

    #!/bin/sh
    #Remove RAR files older than 3 days
    find /your/download/folder -iname "*.rar" -type f -mtime +3 -exec rm {} \;

For windows, there are [similar one-liners](http://stackoverflow.com/questions/51054/batch-file-to-delete-files-older-than-n-days) available.

Please tell me if you need more help. ;)

**Comment by sebaro11** [comment]
Hi Nippey,

that worked for me!
Thank you very much :D

**Comment by GammaC0de** [comment]
:+1:
