### ISSUE TITLE
How to generate a reconnect script

### ISSUE THREAD

**Issue by davboc** [pyload/pyload#2431]
Hi boys, 
there is a way to generate a reconnect script for changing ip address? In the past modem dlink I found that script, but with the new modem Telecom I can't find a solution for that.

Thanks everyone

**Comment by Nippey** [comment]
Hi davboc,

most routers out there have several possibilities to trigger a reconnect, but they are different from device to device.

In case Google could not help you and you have no documentation about additional APIs of your router, you only have the option to mimic what you do via Webinterface:

You can use any modern browser's web-debugger to record the network traffic happening while navigating a web page.
Use this feature while navigating and clicking "Reconnect" in your Routers webinterface and try to rebuild the recorded procedure with curl, wget, python or whatever you're good at.

My old netgear router requires basic http authorisation. With wget it looks like this: 

    wget --http-user=[User] --http-password=[Password] [URL]

For this device, it is sufficient, to directly call the endpoint for reconnection:

    wget --http-user=admin --http-password=admin "http://192.168.0.100/reconnect.htm"

There are devices out there which are much more complex. Good luck!

**Comment by davboc** [comment]
@Nippey first of all thanks for this useful answer! I tried with the debugger of firefox, In the tab "network" I can see a list of methods used like this:
http://i.imgur.com/tQOU9N9.png

Can I use this list with the headers of every method for generate a script?

Thanks again

**Comment by Nippey** [comment]
Hi davboc,
what you first have to do is find out, what part of the requested resources is actually needed.

For example: I would not expect that *.css files or *.js files need to be requested.

The server is like a black box for you with a state machine inside.
Depending on your router manufacturer, you have different states that you need to traverse in-order.

[Router A]
1. Authenticate with the router's webserver
2. Extract session token from authentication request
3. Request a reconnect while providing the session token

[Router B]
1. Request a reconnect while providing the http authentication credentials


In your case, I would take a look into the first http request you made after clicking "login".
You can extract information of how to supply your password and you can extract the session token.
The session token may also be supplied before login, then you already need to extract it with the very first page you load.
In most cases, it doesn't matter _how_ you get to the reconnect page.
So next step is to look into the request that toggled the reconnect.


I give you an example of how complex it can get with a FritzBox (Note: FB's even have other, easier, APIs than the Web Interface!)

- Extract the challenge provided in login.lua
- Calculate: `myresponse = challenge + "-" + md5(challenge + "-" + password)`
- POST to login.lua: `response=myresponse;page=;username=` (The last two are posted empty)
- You will be 303'ed to `home/home.lua?sid=YOURSESSIONID`
- GET `/internet/inetstat_monitor.lua?sid=YOURSEESIONID&useajax=1&action=disconnect&xhr=1`

**Comment by davboc** [comment]
Hi @Nippey!

You are very kind, thanks a lot!

I found the session token in the cookie, I know the page for reconnect, I see the POST request used for reconnect, this: http://i.imgur.com/uLz9Iny.png 

but I can't merge all to make the curl command...

Thanks again

**Comment by GammaC0de** [comment]
@davboc Session token is random string that you get from the process of logging in to your router, so first you'l have to do a 'login' wich will save the session token cookies and then do the actual post request.
For example:

```bash
username = "guest"
password = "123456"
login_url = "http://192.168.1.1/login.cgi"
login_url = "http://192.168.1.1/reconnect.cgi"
#login
wget $login_url --post-data="do=login&user=$username""&pass=$password&submit=" --save-cookies=/tmp/cookies.txt --keep-session-cookies -O - > /dev/null
#reconnect
wget $reconnect_url --post-data="reconnect=yes" --no-clobber --load-cookies=/tmp/cookies.txt --keep-session-cookies 
```

**Comment by davboc** [comment]
Thanks @GammaC0de boys you are really special!

I tried with this command:
wget http://192.168.1.1/index_auth.lp --post-data="do=login&user=admin""&pass=[password]&submit=" --save-cookies=cookies.txt --keep-session-cookies

but say that the password is incorrect! Indeed even if I try with Lynx I can't login... Via Windows/desktop I have no problem, with the same password of course. What the hell? This is sad because this script is really useful for me :(

**Comment by GammaC0de** [comment]
the string in `post-data`  is just an example, you should look in your network trace and see what is the correct format fro your router

**Comment by davboc** [comment]
@GammaC0de with firebug I can export post method in curl, this is the string:

```

curl 'http://192.168.1.1/index_auth.lp' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Connection: keep-alive' -H 'Cookie: xAuth_SESSION_ID=ub9hufXJffy3H8TvOPJyDwA=' -H 'Host: 192.168.1.1' -H 'Referer: http://192.168.1.1/index_auth.lp' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0' -H 'Content-Type: application/x-www-form-urlencoded' --data 'rn=ub9hufXJffy3H8TvOPJyDwA%3D&hidepw=[...]'


```

this is the post method at login, how can I adapt this for my use?

**Comment by GammaC0de** [comment]
@davboc Probably not, it seems that you are already logged in
- restart firefox
- clear the birebug log
- do a login only to your router
- stop birebug's logging
- look in the log for the correct url and post data

**Comment by davboc** [comment]
@GammaC0de 
I tried all, restart firefox and try in anonymous mode, this is the list of command:

http://i.imgur.com/jr2yqBp.png

Post method that I attached previously is the first after login, I don't know where I'm wrong

**Comment by GammaC0de** [comment]
@davboc I recommend using HTTPFox

**Comment by davboc** [comment]
@GammaC0de 

It's the same with HTTPFox

http://i.imgur.com/Y4FTVwY.png

and the post data is:
rn=Fapp1xjpAe3%2FLyDmiC8qtAA%3D&hidepw=41afb923f9fe[...]

:(

**Comment by GammaC0de** [comment]
look at the "POST Data" tab of HTTPFox

**Comment by davboc** [comment]
@GammaC0de 
same parameters 

http://i.imgur.com/rMfqS4s.png

**Comment by GammaC0de** [comment]
Please the hole strings, not just part of them.
Also Please post as text, (right click then copy in HTTPFox)

**Comment by davboc** [comment]
@GammaC0de 
rn=HZpR1DmWTnS2ahDXbjAihgA%3D&hidepw=594ae7a75574cb4520f7ff20f5541a89

**Comment by GammaC0de** [comment]
Does hidepw value the same every time?

**Comment by davboc** [comment]
@GammaC0de 

No, it changes

**Comment by davboc** [comment]
@GammaC0de 
Never used it, but I'll try

**Comment by GammaC0de** [comment]
https://www.youtube.com/watch?v=YId6Ohv0I8A

Do a network filter of "host 192.168.1.1 and port 80" then save tha capture and post the file

**Comment by davboc** [comment]
@GammaC0de 
[modemscript.zip](https://github.com/pyload/pyload/files/233162/modemscript.zip)

**Comment by GammaC0de** [comment]
@davboc Capture the whole session, i.e. from the first time you open the login page and after you actually do the login

**Comment by davboc** [comment]
@GammaC0de 

[modemscript2.zip](https://github.com/pyload/pyload/files/233165/modemscript2.zip)

**Comment by GammaC0de** [comment]
http://192.168.1.1/index_auth.lp :
```javascript
var nonce = "703124:89294:9bd24911fcf0a3ccfe1315fa1a32d2bf"; 
var qop = "auth";

function submitAuthentication()
{
  var user = "admin";

  var pwd  = document.getElementById("password").value;

  document.getElementById("password").disabled=true;
  var HA1 = MD5(user + ":" + realm + ":" + pwd);
  var HA2 = MD5("GET" + ":" + "/index_auth.lp");
  document.getElementById("hidepw").value = MD5(HA1 + ":" + nonce +
                          ":" + "00000001" + ":" + "xyz" + ":" + qop + ":" + HA2);

  document.getElementById("authform").submit();
} 
```

**Comment by GammaC0de** [comment]
Does the value of `nonce` changes every time or is it static?

**Comment by davboc** [comment]
@GammaC0de no it's the same, the command appears before login

**Comment by GammaC0de** [comment]
That does not makes sense, because if it is constant, the value of `hidepw` would be the same every time..

now how to calculate the value of `hidepw` and do the login post

**Comment by davboc** [comment]
@GammaC0de Sorry, I'm wrong. Nonce value change everytime

**Comment by GammaC0de** [comment]
```bash
nonce = `wget http://192.168.1.1/index_auth.lp --save-cookies=/tmp/cookies.txt --keep-session-cookies -O - | grep -oP -e 'var nonce = "(\K[^"]+)'`
echo nonce=$nonce
```

Try if it gives you the result

**Comment by davboc** [comment]
@GammaC0de 
yes! It gives me the value of nonce

**Comment by GammaC0de** [comment]
Try then:

```bash
#!/bin/sh
nonce = `wget http://192.168.1.1/ --save-cookies=/tmp/cookies.txt --keep-session-cookies -O - | grep -oP -e 'var nonce = "(\K[^"]+)'`
echo nonce=$nonce
```

**Comment by davboc** [comment]
@GammaC0de 
Yes! Now in cookies.txt there is the session token

**Comment by GammaC0de** [comment]
Try this:

```bash
#!/bin/sh
user="admin"
password="123456"

realm="Technicolor Gateway"
qop="auth"

router_url=http://192.168.1.1
login_url=$router_url/index_auth.lp
reconnect_url=$router_url/wanStatus.lp

MD5() {
    echo `echo -n $1 | md5sum | cut -d"-" -f1 -`
}

nonce = `wget $router_url --save-cookies=/tmp/cookies.txt --keep-session-cookies -O - | grep -oP -e 'var nonce = "(\K[^"]+)'`

HA1=$(MD5 $user":"$realm":"$password)
HA2=$(MD5 "GET:/index_auth.lp")
hidepw=$(MD5 $HA1":"$nonce":00000001:xyz:"$qop":"$HA2)


wget $login_url --post-data="hidepw=$hidepw" --save-cookies=/tmp/cookies.txt --load-cookies=/tmp/cookies.txt --keep-session-cookies -O - | grep -q "document\.logoutRemote\.submit"
if [ $? -eq 0 ]; then
	echo "Login success"
else
	echo "Login failed"
fi
```

**Comment by davboc** [comment]
@GammaC0de 

```
converted 'http://192.168.1.1' (ANSI_X3.4-1968) -> 'http://192.168.1.1' (UTF-8)
--2016-04-24 14:38:45--  http://192.168.1.1/
Connecting to 192.168.1.1:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://192.168.1.1/index_auth.lp [following]
converted 'http://192.168.1.1/index_auth.lp' (ANSI_X3.4-1968) -> 'http://192.168.1.1/index_auth.lp' (UTF-8)
--2016-04-24 14:38:45--  http://192.168.1.1/index_auth.lp
Reusing existing connection to 192.168.1.1:80.
HTTP request sent, awaiting response... 200 OK
Length: 7235 (7.1K) [text/html]
Saving to: 'STDOUT'

-                       100%[================================>]   7.07K  --.-KB/s   in 0.03s

2016-04-24 14:38:45 (207 KB/s) - written to stdout [7235/7235]

converted 'http://192.168.1.1/index_auth.lp' (ANSI_X3.4-1968) -> 'http://192.168.1.1/index_auth.lp' (UTF-8)
--2016-04-24 14:38:46--  http://192.168.1.1/index_auth.lp
Connecting to 192.168.1.1:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://192.168.1.1/loginMask.lp?url=index%5Fauth%2Elp [following]
converted 'http://192.168.1.1/loginMask.lp?url=index%5Fauth%2Elp' (ANSI_X3.4-1968) -> 'http://192.168.1.1/loginMask.lp?url=index_auth.lp' (UTF-8)
--2016-04-24 14:38:46--  http://192.168.1.1/loginMask.lp?url=index_auth.lp
Reusing existing connection to 192.168.1.1:80.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://192.168.1.1/index_auth.lp [following]
converted 'http://192.168.1.1/index_auth.lp' (ANSI_X3.4-1968) -> 'http://192.168.1.1/index_auth.lp' (UTF-8)
--2016-04-24 14:38:46--  http://192.168.1.1/index_auth.lp
Reusing existing connection to 192.168.1.1:80.
HTTP request sent, awaiting response... 200 OK
Length: 7235 (7.1K) [text/html]
Saving to: 'STDOUT'

-                       100%[================================>]   7.07K  --.-KB/s   in 0.04s

2016-04-24 14:38:46 (200 KB/s) - written to stdout [7235/7235]




```

**Comment by GammaC0de** [comment]
No Login success/fail?

**Comment by davboc** [comment]
Login failed, I forgot the last line

**Comment by GammaC0de** [comment]
what is the content of `/tmp/cookies.txt`?

**Comment by davboc** [comment]
@GammaC0de 
```
# HTTP cookie file.
# Generated by Wget on 2016-04-24 14:38:46.
# Edit at your own risk.

192.168.1.1     FALSE   /       FALSE   0       xAuth_SESSION_ID        OgK5HSHXHFu46WoF9ad5XQA=
```

**Comment by GammaC0de** [comment]
Try again (updated the script above)

**Comment by davboc** [comment]
@GammaC0de Login failed

**Comment by davboc** [comment]
It's strange that I can't login not even with Lynx

**Comment by GammaC0de** [comment]
Lynx doesn't support JavaScript which apparently needed.

**Comment by davboc** [comment]
Yes, you're true

**Comment by GammaC0de** [comment]
- Change the password of your router to to "123456"
- recapture the login with wireshark
- post the file

**Comment by davboc** [comment]
@GammaC0de I can't I must insert letters (both lower and upper case) and numbers 
I'll try with Pass123

**Comment by GammaC0de** [comment]
ok

**Comment by davboc** [comment]
@GammaC0de 
[testGamma.zip](https://github.com/pyload/pyload/files/233454/testGamma.zip)

**Comment by GammaC0de** [comment]
Script updated, please retry.

**Comment by davboc** [comment]
@GammaC0de Login failed :(

**Comment by GammaC0de** [comment]
Try the script with wireshark

**Comment by davboc** [comment]
@GammaC0de I don't know how to do this... I have Wireshark for Windows on the pc and launch the script on raspberry via putty....

**Comment by GammaC0de** [comment]
@davboc Use tcpdump:
`tcpdump -w output.pcapng host 192.168.1.1`

**Comment by GammaC0de** [comment]
@davboc Use tcpdump:
`tcpdump -w output.pcapng host 192.168.1.1`

**Comment by davboc** [comment]
@GammaC0de 
[gamma.zip](https://github.com/pyload/pyload/files/233565/gamma.zip)

**Comment by davboc** [comment]
Thanks to @Robertof that make this working script https://gist.github.com/Robertof/4c07fe562aebcb4be8983888aba21c2a really smart, it solved the problem
I also want to thank @GammaC0de and @Nippey that were really kind and helped me
