### ISSUE TITLE
Sensible to write hoster-plugin now?

### ISSUE THREAD

**Issue by Burnout5151** [pyload/pyload#2433]
Greetings,
I'm new to Github and looking for my first commit.
I'd like to write a hoster plugin, butread that there are big changes currently underway. Is it sensible to write a plugin now, or will it be broken with version 4.10?

**Comment by GammaC0de** [comment]
@Burnout5151 Of-course is is sensible to write a plugin now, there are always changes underway.
Software that does not evolve is doomed to be buggy and then useless.

Anyway, v4.10 is not supposed to change anything significant for plugin writers and also v4.10 seems to bee far away.
