### ISSUE TITLE
How to enable multiple downloads with easybytez?

### ISSUE THREAD

**Issue by davboc** [pyload/pyload#2434]
Hi boys,
what file I need to modify (and how) to allow the simultaneous downloading of more than one file with easybytez?

Thanks

**Comment by GammaC0de** [comment]
Adding a setup() member function to the class should be enough.
Why, easybytez supports downloading of more than one file at a time? or is it just for premium users? 

```python
    def setup(self):
        self.multiDL        = True
```

**Comment by davboc** [comment]
@GammaC0de doesn't support more than one file at time, but often they start at same time... In wich file I need to add those lines?

**Comment by GammaC0de** [comment]
Is this a new installation?

**Comment by davboc** [comment]
@GammaC0de no

**Comment by GammaC0de** [comment]
I suspect that your plugins are not up to date, please read https://github.com/pyload/pyload/issues/2241 to verify.

Anyway, this is the file: https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/EasybytezCom.py

**Comment by davboc** [comment]
plugins are updated and this edit works, thanks again @GammaC0de
