### ISSUE TITLE
Rapidgator issue with validity date of account

### ISSUE THREAD

**Issue by mpaszenda** [pyload/pyload#2440]
Plugin wrongly recognizing validity of Rapidgator account:

297	27.04.2016 19:04:59	DEBUG	HOSTER RapidgatorNet[342]: Plugin version: 0.43
298	27.04.2016 19:04:59	DEBUG	HOSTER RapidgatorNet[342]: Plugin status: testing
299	27.04.2016 19:04:59	WARNING	HOSTER RapidgatorNet[342]: Plugin may be unstable
300	27.04.2016 19:04:59	INFO	ACCOUNT RapidgatorNet: Grabbing account info for user `***@bk.ru`...
301	27.04.2016 19:04:59	DEBUG	ACCOUNT RapidgatorNet: LOAD URL http://rapidgator.net/api/user/info | redirect=True | cookies=True | get={'sid': '8jq893g7utp906p7oaa1g759b2'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
302	27.04.2016 19:04:59	DEBUG	ACCOUNT RapidgatorNet: API:USERINFO | {"response":{"expire_date":1461707373,"traffic_left":"990589588040"},"response_status":200,"response_details":null}
303	27.04.2016 19:04:59	DEBUG	ACCOUNT RapidgatorNet: Account info for user `***@bk.ru`: {'login': {'timestamp': 1461776689.0673001, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 967372644.5703125, 'maxtraffic': None, 'sid': '8jq893g7utp906p7oaa1g759b2', 'validuntil': 1461707373, 'login': '***@bk.ru', 'type': 'RapidgatorNet', 'options': {'limitdl': ['0']}}}
304	27.04.2016 19:04:59	WARNING	ACCOUNT RapidgatorNet: Not using account `***@bk.ru` because the account has expired
305	27.04.2016 19:04:59	INFO	HOSTER RapidgatorNet[342]: Grabbing link info... 

After login via browser - account has status premium and I'm able to download files.

**Comment by GammaC0de** [comment]
@mpaszenda I will need an account for testing.
Please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com.

**Comment by GammaC0de** [comment]
Somehow, the API server reports your account as expired:
http://rapidgator.net/api/user/info
```
{
    "response": {
        "expire_date": 1461707373,
        "traffic_left": "988009314537"
    },
    "response_status": 200,
    "response_details": null
}
```
Using http://www.epochconverter.com/, you can decode `expire_date` to a readable format which in this case is Tue, 26 Apr 2016 21:49:33 GMT and therefore considered as expired.

I suggest you contact the support of Rapidgator, give the the information above and ask them why `expire_date` is incorrect.
Please update when you have ans answer.

**Comment by mpaszenda** [comment]
Support answered for question. 
There was some bug in API and under some "special circumstances" returned expire_date maybe incorrect (not more than 24hours). This info is realy true because today my account is not premium anymore. They have cheked this and this bug will be removed asap.
Thanks for ultrafast response.
