### ISSUE TITLE
[Question] Am I allowed to copy old Wiki to Githubwiki? 

### ISSUE THREAD

**Issue by Jonn3y** [pyload/pyload#2441]
Heyho,

I love pyload and since pyload.org is down I want to recreate some of these stuff like the Wiki and Docs.
But is it okay just to copy the content to this wiki? (+ editing all dead links, etc...) 

Best wishes: Jonas

**Comment by jprk** [comment]
@Jonn3y: Not a bad idea at all ... For myself, I would really appreciated it, given that the documentation of pyload internals is scarce at its best.

**Comment by Jonn3y** [comment]
Hope some dev (@vuolter maybe?) says yes :) 
Recreating the whole pyload.org website including wiki + forums + docs would be awesome too, but there will be a reason why they shut it down :/

**Comment by vuolter** [comment]
@Jonn3y Green light by me. :smile:

**Comment by Jonn3y** [comment]
Work in Profress ! :facepunch:

**Comment by Jonn3y** [comment]
I think I'm done almost. 
Now someone has to update all the old stuff. I don't know that much about pyload 😞 

And maybe we have to recreate all installation-guides?? I read that the updater in zipped releases is outdated?! is this right?! 
But now the basic stuff is back :) And I linked the old docs to web.archive.org. 

Some links are down (marked as [~~Link~~ Offline](#) or just [~~Link~~](#) )

**Comment by vuolter** [comment]
@Jonn3y Thank you very much for your work! I'll have a look at it to fix some stuff soon I can. Indeed, there're some changes upcoming with the 0.5, I have to reflect in the wiki. ;)
Anyway, the bulk of the work has been done by you. :D
