### ISSUE TITLE
Looking for 0.5 Beta from Dec. 2013 

### ISSUE THREAD

**Issue by Jonn3y** [pyload/pyload#2443]
Hey guys,

I'm looking for pyload 0.5 Beta from Dec. 2013 [(Link)](http://web.archive.org/web/20150402094051/http://forum.pyload.org/viewtopic.php?f=7&t=2795)

Does anyone have a installable copy? 🙏 I want to create a local website using the template!
![pyload webui](https://cloud.githubusercontent.com/assets/11927089/14923335/e6befc08-0e3c-11e6-96a0-771bca4a1c67.png)

It would be awesome! PLEASE take a look into your backups ! I would be so grateful!

**Comment by GammaC0de** [comment]
Here you go: https://web.archive.org/web/20150803203701/http://nightly.pyload.org/job/Nightly/lastSuccessfulBuild/artifact/dist/pyload-0.4.9.9-dev.tar.gz

**Comment by Jonn3y** [comment]
@GammaC0de YOU ARE MY HERO! OH YES 👍 🏆

**Comment by vuolter** [comment]
The old 0.5 branch was renamed as 1.0.0 . ;)

**Comment by Jonn3y** [comment]
Testpage:
<img width="1483" alt="bildschirmfoto 2016-04-30 um 00 15 43" src="https://cloud.githubusercontent.com/assets/11927089/14931040/b8359a64-0e68-11e6-865b-0f62d86577d3.png">

(dirty & fragmented) static html but it looks okay to me. :D 

The buttons ontop & progressbars & the searchbar don't have a function.

**Comment by Jonn3y** [comment]
http://jonn3y.github.io/index.html take a look. Nothing special. It's only one site at the moment.
