### ISSUE TITLE
NITROFLARE - Parse error (File info)

### ISSUE THREAD

**Issue by nicobubulle** [pyload/pyload#2444]
Hi,

I have a fresh instalation of pyLoad with lastest plugins and I have a 'Parse error (File info) - plugin may be out of date' with nitroflare plugin.

I tried many links but same error again and again...

Thanks for your time ;)

**Comment by GammaC0de** [comment]
Have you followed the instructions in #2000?

**Comment by nicobubulle** [comment]
It's seems to work now... Very sorry for this.

Thanks for your very quick response by the way !

**Comment by GammaC0de** [comment]
:+1:
