### ISSUE TITLE
turbobit premium not working

### ISSUE THREAD

**Issue by xDereCx** [pyload/pyload#2445]
seems to me like premium account is not detected
30.04.2016 18:06:10 DEBUG     HOSTER XFileSharing[54]: TurbobitNet | Plugin version: 0.64
30.04.2016 18:06:10 DEBUG     HOSTER XFileSharing[54]: TurbobitNet | Plugin status: testing
30.04.2016 18:06:10 WARNING   HOSTER XFileSharing[54]: TurbobitNet | Plugin may be unstable
30.04.2016 18:06:10 DEBUG     HOSTER XFileSharing[54]: TurbobitNet | Config option `use_premium` not found, use default `True`
30.04.2016 18:06:10 INFO      HOSTER XFileSharing[54]: TurbobitNet | Grabbing link info...
30.04.2016 18:06:11 DEBUG     HOSTER XFileSharing[54]: TurbobitNet | Link info: {'status': 7, 'hash': {}, 'name': 'rgqe0f70f85e.html', 'url': u'http://turbobit.net/rgqe0f70f85e.html', 'pattern': {}, 'size': 0}
30.04.2016 18:06:11 DEBUG     HOSTER XFileSharing[54]: TurbobitNet | Previous link info: {'status': 7, 'hash': {}, 'name': 'rgqe0f70f85e.html', 'url': u'http://turbobit.net/rgqe0f70f85e.html', 'pattern': {}, 'size': 0}
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | Link name: rgqe0f70f85e.html
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | Link size: N/D
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | Link status: starting
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | Processing url: http://turbobit.net/rgqe0f70f85e.html
30.04.2016 18:06:11 DEBUG     HOSTER XFileSharing[54]: TurbobitNet | LOAD URL http://turbobit.net/rgqe0f70f85e.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | Checking for link errors...
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | No errors found
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | Grabbing link info...
30.04.2016 18:06:11 DEBUG     HOSTER XFileSharing[54]: TurbobitNet | Link info: {'status': 7, 'hash': {}, 'name': 'rgqe0f70f85e.html', 'url': u'http://turbobit.net/rgqe0f70f85e.html', 'pattern': {}, 'size': 0}
30.04.2016 18:06:11 DEBUG     HOSTER XFileSharing[54]: TurbobitNet | Previous link info: {'status': 7, 'hash': {}, 'name': 'rgqe0f70f85e.html', 'url': u'http://turbobit.net/rgqe0f70f85e.html', 'pattern': {}, 'size': 0}
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | Link name: rgqe0f70f85e.html
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | Link size: N/D
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | Link status: starting
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | Processing as free download...
30.04.2016 18:06:11 DEBUG     HOSTER XFileSharing[54]: TurbobitNet | Getting download link #1...
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | Checking for link errors...
30.04.2016 18:06:11 INFO      HOSTER XFileSharing[54]: TurbobitNet | No errors found

**Comment by GammaC0de** [comment]
Disable `XFileSharing` plugin

**Comment by xDereCx** [comment]
then i get      http://turbobit.net/rps96t1rs030.html
    abortedPlugin is temporarily unavailable 0.00 BTurbobitNet   [Delete Link]    [Restart Link]
    http://turbobit.net/m8fm4vxmrszf.html
    abortedPlugin is temporarily unavailable 0.00 BTurbobitNet   [Delete Link]    [Restart Link]
    http://turbobit.net/9o8gzbbbd8fv.html
    queuedPlugin is temporarily unavailable 0.00 BTurbobitNet   [Delete Link]    [Restart Link]

**Comment by xDereCx** [comment]
30.04.2016 18:25:34 DEBUG     HOSTER TurbobitNet[57]: Plugin version: 0.28
30.04.2016 18:25:34 DEBUG     HOSTER TurbobitNet[57]: Plugin status: broken
30.04.2016 18:25:36 DEBUG     HOSTER TurbobitNet[58]: Plugin version: 0.28
30.04.2016 18:25:36 DEBUG     HOSTER TurbobitNet[58]: Plugin status: broken
30.04.2016 18:25:38 DEBUG     HOSTER TurbobitNet[59]: Plugin version: 0.28
30.04.2016 18:25:38 DEBUG     HOSTER TurbobitNet[59]: Plugin status: broken

**Comment by GammaC0de** [comment]
Yes, the status of `TurbobitNet` plugin is `broken` (at least for free downloads)

I'm currently working on the account plugin so at least premium download could be working.

**Comment by xDereCx** [comment]
brilliant if u need premium to test got few days left for turbobit, and year for euroshare just email me xderecx@gmail.com

**Comment by GammaC0de** [comment]
:+1: Already got your email :smiley:

**Comment by xDereCx** [comment]
not sure about that one, turbobit priemium is detected, but download is broken
01.05.2016 21:20:17 INFO      Download starts: http://turbobit.net/rps96t1rs030.html
01.05.2016 21:20:17 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
01.05.2016 21:20:17 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
01.05.2016 21:20:17 DEBUG     HOSTER TurbobitNet[57]: Plugin version: 0.28
01.05.2016 21:20:17 DEBUG     HOSTER TurbobitNet[57]: Plugin status: broken
01.05.2016 21:20:17 INFO      Download aborted: http://turbobit.net/rps96t1rs030.html

**Comment by GammaC0de** [comment]
Free download is broken, that's why it is marked as broken.
You can edit 'hoster/TubobitNet.py' and change it from "broken" to "testing" so you'll be able to download as premium.
