### ISSUE TITLE
euroshare premium not working

### ISSUE THREAD

**Issue by xDereCx** [pyload/pyload#2446]
30.04.2016 18:03:26 DEBUG     HOSTER EuroshareEu[2]: Plugin version: 0.37
30.04.2016 18:03:26 DEBUG     HOSTER EuroshareEu[2]: Plugin status: testing
30.04.2016 18:03:26 WARNING   HOSTER EuroshareEu[2]: Plugin may be unstable
30.04.2016 18:03:26 INFO      ACCOUNT EuroshareEu: Grabbing account info for user `attacktm@gmail.com`...
30.04.2016 18:03:26 DEBUG     ACCOUNT EuroshareEu: LOAD URL http://euroshare.eu/customer-zone/settings/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
30.04.2016 18:03:32 INFO      HOSTER EuroshareEu[3]: Checking for link errors...
30.04.2016 18:03:32 INFO      HOSTER EuroshareEu[3]: No errors found
30.04.2016 18:03:32 INFO      HOSTER EuroshareEu[3]: Processing as free download...
30.04.2016 18:03:32 INFO      HOSTER EuroshareEu[3]: Downloading file...
30.04.2016 18:03:32 DEBUG     HOSTER EuroshareEu[3]: DOWNLOAD URL http://s5.euroshare.eu/_/free.php?fid=2z6Q7eHQ2B | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
30.04.2016 18:03:32 INFO      Debug Report written to debug_EuroshareEu_30-04-2016_18-03-32.zip
30.04.2016 18:03:34 DEBUG     ACCOUNT EuroshareEu: Account info for user `attacktm@gmail.com`: {'login': {'timestamp': 1462035693.229482, 'password': '**********', 'valid': True}, 'data': {'premium': False, 'plugin': <Account EuroshareEu>, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': -1, 'login': 'attacktm@gmail.com', 'type': 'EuroshareEu', 'options': {'limitdl': '0'}}}
30.04.2016 18:03:34 INFO      HOSTER EuroshareEu[2]: Grabbing link info...

**Comment by xDereCx** [comment]
thx works fine now

**Comment by GammaC0de** [comment]
:+1:
