### ISSUE TITLE
Question for v0.5

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2447]
Will the upcoming v0.5 will have captcha support when logging-in?
Now-days many hosters (I know of `TurbobitNet`, `NitroflareCom`, `FilejungleCom`) requires captcha support.

I managed to create a "hack" support for captcha (see these plugins), but this is a hack and has some issues like that `pyload` tries to login on startup and so a loging with captcha blocks `pyload'`s startup until a captcha is entered or timeout..

**Comment by vuolter** [comment]
For now 0.5 is just a 0.4.9 with massive code cosmetics, addon plugins (and some internals) updated and almost all the PRs and workarounds collected in years, so no native captcha support when logging-in. :(

**Comment by Ryan747800B** [comment]
An upcoming update? It will be an automatic update, or we need to reinstall everything (especially `ipkg` installations)? @vuolter Do you have any ETA? No rush, only info :wink:

**Comment by vuolter** [comment]
Reinstall. u_u

**Comment by GammaC0de** [comment]
Just an Idea: I would include in the distribution package only the core and UpdateManager.

**Comment by vuolter** [comment]
@GammaC0de I thought about that, but make a branch just for plugins could be more problematic. Anyhow, I remain open-minded... :S

**Comment by GammaC0de** [comment]
I meant when building the .ipk .deb etc. Just include in it the core, everything in 'internal' an of course UpdateManager   
@GammaC0de I thought about that, but make a branch just for plugins could be more problematic. Anyhow, I remain open-minded... :S

**Comment by vuolter** [comment]
0.5 will be availbale through pip directly. u_u

**Comment by Velociraptor85** [comment]
@vuolter but there is already an pyload on pypi, https://pypi.python.org/pypi/pyload/0.1 or am I wrong here?

**Comment by vuolter** [comment]
@Velociraptor85 I saw... I'll submit the package with a sligthy different name.

**Comment by vuolter** [comment]
@Velociraptor85 Have a look at the name-pool: https://twitter.com/pyload/status/734734074061983745

**Comment by GammaC0de** [comment]
+1 for pyload.next

**Comment by Velociraptor85** [comment]
or maybe PyLoadNG for nextgen :)?

**Comment by vuolter** [comment]
@GammaC0de Pinned. ;)
@Velociraptor85 I watched a tv serie with that kind of name once... :p

**Comment by Velociraptor85** [comment]
well I am happy to test it when it gets released =)

**Comment by vuolter** [comment]
@Velociraptor85 Just registered pyload-ng ;)
