### ISSUE TITLE
Names from site like filecrypt

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#2451]
Hello, since today or yesterday i see a small bug.
If i have load some files from filecrypt to pyload via click n load i get the folder name from filecrypt in pyload. looks like "xxx.1080p.x264-hermes -filecrpyt.cc". Now, i get only "filecrypt.cc". Where is the rest of the folder name?
I have also tested old files and have the same error.

**Comment by GammaC0de** [comment]
Sample URL & DEBUG log please

**Comment by Mister-XY** [comment]
Here is a sample url
http://filecrypt.cc/Container/BFE9C5C21F.html

and the debug log
http://pastebin.com/utYtxnqj

**Comment by GammaC0de** [comment]
Does it happen even without click n load?

**Comment by Mister-XY** [comment]
I think yes. Via DLC i have the correct foldename and also if i copy the url via Copy & paste.

**Comment by GammaC0de** [comment]
Well, I think that click n load takes the package name from the web page title (try click n loading the link you have posted here), so maybe the title format had changed..

**Comment by Mister-XY** [comment]
I don't know. But the title is "filecrypt" and not "filecrpyt.cc"

**Comment by GammaC0de** [comment]
I don't understand, please explain what you mean

**Comment by Mister-XY** [comment]
You say it take the name from webpage name. But the title from the webpage is filecrypt 
<title>Filecrypt</title>
and not filecrypt.cc and i have a new container called filecrypt.cc

**Comment by Mister-XY** [comment]
But i think you are right. i have take a old "stable" version from january and there is the same problem.

**Comment by GammaC0de** [comment]
So can we close this?

**Comment by Mister-XY** [comment]
I think. But that is angry. I have like this in pyload.

**Comment by GammaC0de** [comment]
How exactly do you use click n load via flashgot?

**Comment by Mister-XY** [comment]
no via portforward from windows netsh interface portproxy add v4tov4 listenport=9666 connectaddress=<Zieladresse> connectport=9666 listenaddress=127.0.0.1

**Comment by GammaC0de** [comment]
Closing :(

**Comment by Jonn3y** [comment]
Sampleurl from above: http://filecrypt.cc/Container/BFE9C5C21F.html
Important HTML-part:
```html
1. <button title="block this!" style="visibility:hidden;width:0px !important;overflow:hidden;padding:0;margin:0;height:0;"></button>
2. <form action="" target="hidden" onsubmit="CNLPOP('DxCTaP03L-bA2j1AKLteohy1VvipBHQGpaVfdyb0M3THNCX0xlwp21Cf2A06eFhikZbRW2TcSf_EP5bu84yOJg', '34303631323232363934383134323035', 'sGXN3qfPL9gRfArXzC41D6xuDdUs4saP4UixEzduaCmXzKQExcCg35uK1jhMVRYxkEDXwa9qgFlWUr6T9V8lrY2tS3xCyKQtWzkOZvnA8fJueJSGYGxb3xl7Gr6t3UMRvQ4JvtNyEVOHtPAq/dJBeblRPWUU+WSbtZhvIyWJJoICtLk+gWrPP+ZLu0ISXTUrTF5e6PdZoe3Dbw+CfNwDAzP8Fak455zvlrae2TNR7kEdawR/ghVeMWkSLVKDrkIC540GaWM7L8xg7ohDmroHaIcl2vdfRM52Iss+oRSWxHbYIN19vf7nsBmPvPE6YGTgJI+xeCmyu5lIlz9lxPB4nE+QpHzcXrffGCG/qTS3kMtG3031J8wvOvIC7tS0s6FqFtbcbxaM1Z6QybQsKSNEFnzOXgD2e5U4jTg+uFVE/rYpBFI3r+J1lcQnFTDsg0azbDTxweguOMxpBBzVBCLn56Qc3y4A1kFcm73faJi4iYiPRJAsVn7LF5gR5c8H0knDuko94dO/DE2+Fpr+15sdIlM6/NE45Fh85GnHq6yvQ8syky5VAXw5apsnChCbPQ2v/g60h0sPKpcYK249wofcjRzbTbKQFkznSTsKoikagS+29UKeDMG3tNznzItf/zODgGTHb5QN7w7wmkNlOuo1VkCftob/+xtSWqrYXD5KQGXtnJKZBz8VbAQHbaHphR5OVqCF5t7sRe/+iQuG9iUDF4lmW8wuy7unXbIvITrAxXQ5Z54tLZYYm+wyYUSqXQA9/SIsx3zTM81bnn0pwVZlnlrEb+cYIB07sVruEwJ55c1bA16N59qz2JgNCh6wmvC0VnRRO3in6QqJ/jhm2p9s6hkDO8wqTIBJ1NHDM4uSJKM=', 'Game.of.Thrones.S06E02.Zuhause.GERMAN.DL.720p.WebHD.x264-TVP - filecrypt.cc'); return false;" class="cnlform" method="post">
3.    <button type="submit" class="cnl" id="cnl_btn" name="submit" title="" value="Add Link to JDownloader"><i></i><span>Click'n Load</span></button>
4.    <button class="dlcdownload" type="button" title="*.dlc Download" onclick="DownloadDLC('F8VueRJoTjEWJI50-ptCWMba9p3uImBKMBtMFVPrJKd6f5ipf1K2hdhBAytTb7VUUKAB1m0brgANaHoJQ2uSCR4YqdMZK6web92B3UilGDSLCw3Jaju-gj98a9BRZDeu');"><i></i><span>dlc</span></button>
5. </form>
```

The Container should be named by the 4. parameter of the click'n'load stuff:
```
2. <form action="" target="hidden" onsubmit="CNLPOP('<p1>, '<p2>', '<p3>', '<p4 = name>'); return false;" class="cnlform" method="post">
```
JDownloader uses this parameter! 

The click'n'load-plugin seem's to use the domain.tld 

I just don't know how to edit the plugin just to use p4 😞

**Comment by Mister-XY** [comment]
Any news about this error? I have also ssen, that pyload name the new filecrypt container to filecrypt.cc and not to the realy name.

**Comment by GammaC0de** [comment]
@Mister-XY sample URL please

**Comment by Mister-XY** [comment]
Here http://filecrypt.cc/Container/BFE9C5C21F.html

**Comment by GammaC0de** [comment]
👍

**Comment by Mister-XY** [comment]
Yes, i have added this line manualy and it works. Very good.
