### ISSUE TITLE
smoozed.com plugin

### ISSUE THREAD

**Issue by t09** [pyload/pyload#2452]
Hi,

smoozed. com plugin seems outdated because of change to their api?!

thanks!
[debug_OboomCom_05-05-2016_12-33-24.txt](https://github.com/pyload/pyload/files/250266/debug_OboomCom_05-05-2016_12-33-24.txt)

**Comment by GammaC0de** [comment]
@t09It seems like the problem described in https://github.com/xmendez/wfuzz/wiki/PyCurlSSLBug

**Comment by t09** [comment]
thanks i will forward this to my hoster!

**Comment by t09** [comment]
Hi,
my hoster fixed that for me...now oboom.com sends me capture! pyLoad is not recognising I'm premium user at smoozed.....oboom is a supported hoster
Another log file was generated dont know if it helps.
[debug_Dereferer_05-05-2016_12-11-21.txt](https://github.com/pyload/pyload/files/251038/debug_Dereferer_05-05-2016_12-11-21.txt)

**Comment by GammaC0de** [comment]
@t09 Multihoster support is currently broken (see #2121)

**Comment by t09** [comment]
reaaaaaaal bad news :(

**Comment by GammaC0de** [comment]
Should be working now, closing.
