### ISSUE TITLE
pycurl error 6: Could not resolve host: %3C!DOCTYPE%20html%20PUBLIC%20%22-

### ISSUE THREAD

**Issue by anonymousse37** [pyload/pyload#2453]
Hi,

I am trying to use back Pyload after monthes since it got massive bugs 24/7 which was so boring because it works so well for a while.

I am using a premium account on RealDebrid.

Anyway this is the log file (verbose)

Here are what i suspect to be problem but i have no clue.

58	05.05.2016 14:08:52	ERROR	pycurl error 6: Could not resolve host: %3C!DOCTYPE%20html%20PUBLIC%20%22-
86	05.05.2016 14:28:32	DEBUG	RealdebridCom: Account Info: {'error': 'list index out of range'}

05.05.2016 14:04:13	INFO	Démarrage pyLoad 0.4.9
2	05.05.2016 14:04:13	INFO	Utilisation du dossier principal : /root/.pyload
3	05.05.2016 14:04:19	INFO	ExtractArchive: No UnRar installed
4	05.05.2016 14:04:19	INFO	ExtractArchive: Activated UnZip
5	05.05.2016 14:04:20	INFO	Plugins activés: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
6	05.05.2016 14:04:20	INFO	Plugins désactivés: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
7	05.05.2016 14:04:20	INFO	Temps de téléchargement : True
8	05.05.2016 14:04:20	INFO	Démarre ThriftBackend: 0.0.0.0:7227
9	05.05.2016 14:04:26	INFO	Free space: 2.60 GiB
10	05.05.2016 14:04:26	INFO	Starting builtin webserver: 192.168.1.57:8000
11	05.05.2016 14:04:26	INFO	Activating Accounts...
12	05.05.2016 14:04:26	INFO	Activating Plugins...
13	05.05.2016 14:04:26	INFO	pyLoad is up and running
14	05.05.2016 14:04:30	WARNING	Not able to connect server for updates
15	05.05.2016 14:04:30	INFO	No Updates for pyLoad
16	05.05.2016 14:04:31	WARNING	Not able to connect server for updates
17	05.05.2016 14:04:31	INFO	No plugin updates available
18	05.05.2016 14:05:19	INFO	shutting down...
19	05.05.2016 14:05:19	INFO	Received Quit signal
20	05.05.2016 14:05:34	INFO	Démarrage pyLoad 0.4.9
21	05.05.2016 14:05:34	INFO	Utilisation du dossier principal : /root/.pyload
22	05.05.2016 14:05:38	INFO	ExtractArchive: No UnRar installed
23	05.05.2016 14:05:38	INFO	ExtractArchive: Activated UnZip
24	05.05.2016 14:05:38	INFO	Plugins activés: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
25	05.05.2016 14:05:38	INFO	Plugins désactivés: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
26	05.05.2016 14:05:38	INFO	Temps de téléchargement : True
27	05.05.2016 14:05:38	INFO	Démarre ThriftBackend: 0.0.0.0:7227
28	05.05.2016 14:05:42	INFO	Free space: 2.60 GiB
29	05.05.2016 14:05:42	INFO	Starting builtin webserver: 192.168.1.57:8000
30	05.05.2016 14:05:42	INFO	Activating Accounts...
31	05.05.2016 14:05:42	INFO	Activating Plugins...
32	05.05.2016 14:05:42	INFO	pyLoad is up and running
33	05.05.2016 14:05:46	WARNING	Not able to connect server for updates
34	05.05.2016 14:05:46	INFO	No Updates for pyLoad
35	05.05.2016 14:05:47	WARNING	Not able to connect server for updates
36	05.05.2016 14:05:47	INFO	No plugin updates available
37	05.05.2016 14:07:19	INFO	shutting down...
38	05.05.2016 14:07:19	INFO	Received Quit signal
39	05.05.2016 14:07:35	INFO	Démarrage pyLoad 0.4.9
40	05.05.2016 14:07:35	INFO	Utilisation du dossier principal : /root/.pyload
41	05.05.2016 14:07:39	INFO	ExtractArchive: No UnRar installed
42	05.05.2016 14:07:39	INFO	ExtractArchive: Activated UnZip
43	05.05.2016 14:07:39	INFO	Plugins activés: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, RealdebridCom, UpdateManager
44	05.05.2016 14:07:39	INFO	Plugins désactivés: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RehostTo, XMPPInterface
45	05.05.2016 14:07:39	INFO	Temps de téléchargement : True
46	05.05.2016 14:07:39	INFO	Démarre ThriftBackend: 0.0.0.0:7227
47	05.05.2016 14:07:43	INFO	Free space: 2.60 GiB
48	05.05.2016 14:07:43	INFO	Starting builtin webserver: 192.168.1.57:8000
49	05.05.2016 14:07:43	INFO	Activating Accounts...
50	05.05.2016 14:07:44	INFO	Activating Plugins...
51	05.05.2016 14:07:45	INFO	pyLoad is up and running
52	05.05.2016 14:07:48	WARNING	Not able to connect server for updates
53	05.05.2016 14:07:48	INFO	No Updates for pyLoad
54	05.05.2016 14:07:50	WARNING	Not able to connect server for updates
55	05.05.2016 14:07:50	INFO	No plugin updates available
56	05.05.2016 14:08:49	INFO	Added package test containing 1 links
57	05.05.2016 14:08:51	INFO	Download starts: http://ul.to/XXXXX
58	05.05.2016 14:08:52	ERROR	pycurl error 6: Could not resolve host: %3C!DOCTYPE%20html%20PUBLIC%20%22-
59	05.05.2016 14:27:20	INFO	Download starts: html>
60	?	?	
61	?	?	
69	05.05.2016 14:27:21	ERROR	pycurl error 6: Could not resolve host: %3C!DOCTYPE%20html%20PUBLIC%20%22-
70	05.05.2016 14:28:07	INFO	shutting down...
71	05.05.2016 14:28:07	INFO	Received Quit signal
72	05.05.2016 14:28:22	INFO	Démarrage pyLoad 0.4.9
73	05.05.2016 14:28:22	INFO	Utilisation du dossier principal : /root/.pyload
74	05.05.2016 14:28:22	DEBUG	Remote activated: True
75	05.05.2016 14:28:26	DEBUG	created index of plugins
76	05.05.2016 14:28:27	INFO	ExtractArchive: No UnRar installed
77	05.05.2016 14:28:27	INFO	ExtractArchive: Activated UnZip
78	05.05.2016 14:28:27	INFO	Plugins activés: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, RealdebridCom, UpdateManager
79	05.05.2016 14:28:27	INFO	Plugins désactivés: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RehostTo, XMPPInterface
80	05.05.2016 14:28:27	INFO	Temps de téléchargement : True
81	05.05.2016 14:28:27	INFO	Démarre ThriftBackend: 0.0.0.0:7227
82	05.05.2016 14:28:31	INFO	Free space: 2.60 GiB
83	05.05.2016 14:28:31	INFO	Starting builtin webserver: 192.168.1.57:8000
84	05.05.2016 14:28:31	INFO	Activating Accounts...
85	05.05.2016 14:28:32	DEBUG	RealdebridCom: Get Account Info for XXXXX
86	05.05.2016 14:28:32	DEBUG	RealdebridCom: Account Info: {'error': 'list index out of range'}
87	05.05.2016 14:28:32	INFO	Activating Plugins...
88	05.05.2016 14:28:33	DEBUG	RealdebridCom: Overwritten Hosters: DlFreeFr, EasybytezCom, FilefactoryCom, LetitbitNet, LoadTo, MediafireCom, MegasharesCom, RedtubeCom, SendspaceCom, ShareonlineBiz, UlozTo, UploadedTo, UploadingCom, YoupornCom, YoutubeCom, ZippyshareCom
89	05.05.2016 14:28:33	DEBUG	RealdebridCom: New Hosters: 1fichier.com, 24uploading.com, 2shared.com, 4shared.com, 5xpan.com, alfafile.net, allmyvideos.net, alterupload.com, anafile.com, auroravid.to, bigfile.to, bitvid.sx, canalplus.fr, catshare.net, cbs.com, cjoint.net, clicknupload.com, clicknupload.link, clicknupload.me, cloudtime.to, dailymotion.com, datafile.com, datafilehost.com, datei.to, depfile.com, desfichiers.com, dfichiers.com, divxstage.eu, divxstage.to, dix3.com, dl4free.com, exashare.com, extmatrix.com, faststore.org, fileflyer.com, filemarkets.com, fileover.net, filerio.com, filerio.in, filesabc.com, filesflash.com, filesflash.net, filesmonster.com, gboxes.com, gigapeta.com, gigasize.com, gulfup.com, hugefiles.net, hulkshare.com, i-filez.com, k2s.cc, k2share.cc, keep2s.cc, keep2share.cc, kingfiles.net, luckyshare.net, mega.co.nz, mega.nz, megadl.fr, mesfichiers.org, mightyupload.com, movshare.net, nitroflare.com, novamov.com, nowdownload.ag, nowdownload.at, nowdownload.ch, nowdownload.ec, nowdownload.eu, nowdownload.li, nowdownload.sx, nowdownload.to, nowvideo.ag, nowvideo.at, nowvideo.ch, nowvideo.eu, nowvideo.li, nowvideo.sx, oboom.com, openload.co, openload.io, ozofiles.com, piecejointe.net, pjointe.com, purevid.com, radiotunes.com, rapidgator.net, rarefile.net, redbunker.net, rg.to, rockfile.eu, rutube.ru, salefiles.com, scribd.com, secureupload.eu, shareflare.net, sky.fm, soundcloud.com, speedyshare.com, tenvoi.com, thevideo.me, turbobit.net, tusfiles.net, ul.to, ulozto.net, ulozto.sk, unibytes.com, uplea.com, upload.af, uploadable.ch, uploadc.ch, uploadc.com, uploaded.net, uploadrocket.net, uploadx.org, upstore.net, uptobox.com, uptostream.com, userporn.com, userscloud.com, veevr.com, videoweed.es, vimeo.com, vip-file.com, vipfile.in, wholecloud.net, youwatch.org, yunfile.com
90	05.05.2016 14:28:33	INFO	pyLoad is up and running
91	05.05.2016 14:28:36	WARNING	Not able to connect server for updates
92	05.05.2016 14:28:36	INFO	No Updates for pyLoad
93	05.05.2016 14:28:38	WARNING	Not able to connect server for updates
94	05.05.2016 14:28:38	INFO	No plugin updates available
95	05.05.2016 14:29:40	INFO	shutting down...
96	05.05.2016 14:29:40	DEBUG	Deleting old pidfile pyload.pid
97	05.05.2016 14:29:40	INFO	Received Quit signal
98	05.05.2016 14:29:54	INFO	Starting pyLoad 0.4.9
99	05.05.2016 14:29:54	INFO	Using home directory: /root/.pyload
100	05.05.2016 14:29:54	DEBUG	Remote activated: True

Can you help me to understand and correct whats wrong here ?
Thank you for your help guys

**Comment by vuolter** [comment]
pyLoad libraries are outdated and buggy, that's all (plus MultiHoster support is currently down).
But I'm working on the next release. u_u

**Comment by anonymousse37** [comment]
Thanks vuolter for answering.
Pyload team gave up ? I think i have posted in january for the same problem.
When do you think u will finish to debug all this mess if i may ask you ?

**Comment by GammaC0de** [comment]
@anonymousse37 Get updated here #2121

**Comment by anonymousse37** [comment]
Hi GammaC0de,

You mention a stable version in the linked post.
Is it an equivalent to the version of pyload i can find here ? https://github.com/pyload/pyload/releases

What do you mean by stable ? Link do self debrid ?

Txs

**Comment by anonymousse37** [comment]
I found this Link with modified files for pyload here https://github.com/robbi/pyload/commit/765fd272fffdd928357fcd8d26239e71bdf33cb0#diff-b435ebd54003dd6b2762bef9c7f5007e
Do you know if this is up to date or not ?

Txs

**Comment by GammaC0de** [comment]
the latest version is the "[stable](https://github.com/pyload/pyload)" branch (which apparently has bugs)

**Comment by anonymousse37** [comment]
Ok txs.
Are you able to tell us what are the pyload module in fault for this error :

169	05.05.2016 23:57:38	DEBUG	Real-Debrid: Old URL: https://1fichier.com/?XXXXX
170	05.05.2016 23:57:39	DEBUG	Chunk 1 failed: (6, 'Could not resolve host: %3C!DOCTYPE%20html%20PUBLIC%20%22-')
171	05.05.2016 23:57:39	DEBUG	pycurl exception 6: Could not resolve host: %3C!DOCTYPE%20html%20PUBLIC%20%22-
172	05.05.2016 23:57:39	ERROR	pycurl error 6: Could not resolve host: %3C!DOCTYPE%20html%20PUBLIC%20%22-
173	05.05.2016 23:57:43	INFO	Debug Report written to debug_RealdebridCom_05-05-2016_23-57-39.zip

**Comment by GammaC0de** [comment]
@anonymousse37 The problem is in the multiaccount, if you use  https://1fichier.com/?XXXXX alone it works ok

**Comment by anonymousse37** [comment]
I need to debrid the link https://1fichier.com/?XXXXX on the realdebrid plateform and paste the  debrided link into pyload for this to work.
Pasting the raw 1fichier link doesnt work directly in Pyload doesnt work.

What is exactly the multiaccount ?

Sorry for all the questions, i need and i want to understand ^^

**Comment by GammaC0de** [comment]
multiaccount is the name for multihosters like debrid

**Comment by anonymousse37** [comment]
So you are updating all the plugins in /usr/share/pyload/module/plugins/hoster.
That's a bit of work U_U

**Comment by anonymousse37** [comment]
So i guess in my case the problem comes from the module
-RealdebridCom.py in
-/usr/share/pyload/module/plugins/hoster

I did open the file and according to this error

157	05.05.2016 23:53:52	DEBUG	RealdebridCom: Get Account Info for darkwall_37
158	05.05.2016 23:53:52	DEBUG	RealdebridCom: Account Info: {'error': 'list index out of range'}

It looks like it is trying to read and element in an array, at an index which is not 'allocated'.
For example, it cannot display the last day of the premium validity in pyload. Says "Not available".
 
    def grab_hosters(self, user, password, data):
        html = self.load("https://real-debrid.com/api/hosters.php")
        return [x for x in map(str.strip, html.replace("\"", "").split(",")) if x]


    def grab_info(self, user, password, data):
        if self.pin_code:
            return

        html = self.load("https://real-debrid.com/api/account.php")
        xml  = dom.parseString(html)

        validuntil = float(xml.getElementsByTagName("expiration")[0].childNodes[0].nodeValue)

        return {'validuntil' : validuntil,
                'trafficleft': -1        ,
                'premium'    : True      }

We can see it should return the value of validunil variable but it doesnt.
I guess the form of the html file that is parsed in this code did change so it doesnt do the job properly.

Sad i do not have a clue in python. I may dig in if only i had time enouph. AH time.....
