### ISSUE TITLE
VIP share-online.biz

### ISSUE THREAD

**Issue by t09** [pyload/pyload#2456]
HI,

I got VIP account at this hoster....pyload shows its not premium but it is....which line i need to change pyload recognize?

thanks

**Comment by vuolter** [comment]
First post the debug log, maybe the its account plugin is become outdated.

**Comment by t09** [comment]
Hi,
the plugin didn't generated an usefull log. I think the account plugin is good, but only knows status: free and premium but not VIP....the log file proofs it - 'data': {'premium': False,
[log.txt](https://github.com/pyload/pyload/files/253689/log.txt)
Thank you sir!

**Comment by GammaC0de** [comment]
@t09 I will need an account for testing,
please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com

**Comment by t09** [comment]
@GammaC0de account sent!

**Comment by GammaC0de** [comment]
:+1:

**Comment by GammaC0de** [comment]
Done.

**Comment by t09** [comment]
Thank you sir!

**Comment by GammaC0de** [comment]
:+1:

**Comment by t09** [comment]
No BTC adress here for tips?!

**Comment by GammaC0de** [comment]
Sorry, currently there is no way to donate. (see @vuolter's answer here: https://github.com/pyload/pyload/issues/2121#issuecomment-204220394)
