### ISSUE TITLE
[ZippyshareCOM] No JS Engine after java update with ossp-js installed

### ISSUE THREAD

**Issue by led13714** [pyload/pyload#2459]
I run pyload on a Synology DS214play.
When trying to download from Zippyshare I get the following Errors (see top line...):

> WARNING	Download failed: file.html | No JS Engine
> WARNING 	CAPTCHA ZippyshareCom[43]: ReCaptcha | Key pattern not found
> INFO	HOSTER ZippyshareCom[43]: Processing as free download...
> INFO	HOSTER ZippyshareCom[43]: No errors found
INFO	HOSTER ZippyshareCom[43]: Checking for link errors...
DEBUG	HOSTER ZippyshareCom[43]: LOAD URL http://www112.zippyshare.com/v/xxxxxxx/file.html | redirect=True | decode=True | cookies=[('zippyshare.com', 'ziplocale', 'en')] | get={} | req=None | just_header=False | post={} | ref=False | multipart=False
INFO	HOSTER ZippyshareCom[43]: Direct download link not foundDEBUG	HOSTER ZippyshareCom[43]: LOAD URL http://www112.zippyshare.com/v/xxxxxxx/file.html | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=True | post={} | ref=True | multipart=False
INFO	HOSTER ZippyshareCom[43]: Looking for direct download link...
INFO	HOSTER ZippyshareCom[43]: Processing url: http://www112.zippyshare.com/v/xxxxxxx/file.html
INFO	HOSTER ZippyshareCom[43]: Link status: online
INFO	HOSTER ZippyshareCom[43]: Link size: 100.93 MiB (105832775 bytes)
INFO	HOSTER ZippyshareCom[43]: Link name: file.html
DEBUG	HOSTER ZippyshareCom[43]: Previous link info: {}
DEBUG	HOSTER ZippyshareCom[43]: Link info: {'status': 2, 'hash': {}, 'name': 'file.html', 'url': u'http://www112.zippyshare.com/v/xxxxxxx/file.html', 'pattern': {'S': u'100.93', 'U': u'MB', 'KEY': u'xxxxxxx'}, 'size': 105832775}
INFO	HOSTER ZippyshareCom[43]: Grabbing link info...
WARNING	HOSTER ZippyshareCom[43]: Plugin may be unstable
DEBUG	HOSTER ZippyshareCom[43]: Plugin status: testing
DEBUG	HOSTER ZippyshareCom[43]: Plugin version: 0.87 
`

Maybe this is related to the fact that I updated the java version on my NAS to "Java SE 8 embedded"?

Although another js interpreter is installed:
> DS214> ipkg install ossp-js
> Package ossp-js (1.6.20070208-1) installed in root is up to date.
> Nothing to be done

Anybody got any idea how to fix this?

**Comment by GammaC0de** [comment]
`js` should be in your PATH

**Comment by led13714** [comment]
Seems to be the problem, but how can I add `js` to my PATH?

> DS214p> echo $PATH
/opt/bin:/opt/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin:/volume1/@appstore/java8/ejdk1.8.0_91/linux_i586/jre/bin:/volume1/@appstore/java8/ejdk1.8.0_91/linux_i586/jre/bin

**Comment by GammaC0de** [comment]
I don't know how it is in DS214play,
I would try these options:
* check in /etc/profile
* grep for PATH in /etc or whatever equivalent.
* modify pyLoad's init script to include `js`'s path

**Comment by led13714** [comment]
- [x] check in /etc/profile
added the /opt/bin and /opt/sbin to /etc/profile but the problem persists.

- [x] grep for PATH in /etc or whatever equivalent.
takes forever and doesn't seem to bring up any results

- [ ] modify pyLoad's init script to include js's path
Do you mean the __init__.py file within modules? 
What exactly should I modify?

**Comment by GammaC0de** [comment]
No, in a normal linux distribution, that would probably `/etc/init.d/pyload` or `/etc/init.d/pyload.sh`

**Comment by led13714** [comment]
my bad :+1: 
The only thing under /etc/init.d/ is an empty "S99pyload" file...

**Comment by GammaC0de** [comment]
Try `/etc/rc.d/pyload`

**Comment by GammaC0de** [comment]
> Edit: js can be found under /opt/bin which is in PATH?
Sometimes PATH gets updated after pyload have already been started so it won't see this.

**Comment by led13714** [comment]
`Try /etc/rc.d/pyload`
there is no "/etc/rc.d/" directory.

found another S99pyload script under "/opt/etc/init.d" but the specified PATH variable includes "/opt/bin/" and "/opt/sbin/"...

`Edit: js can be found under /opt/bin which is in PATH?`
yeah "js" along with "js-config", "jslint", "jspack" and many other files

`Sometimes PATH gets updated after pyload have already been started so it won't see this.`
Well I checked the $PATH variable with pyload running and stopped. "/opt/bin" was always there...

**Comment by GammaC0de** [comment]
If pyload was installed via Optware then it should be in `/opt/etc/init.d/`

>Well I checked the $PATH variable with pyload running and stopped. "/opt/bin" was always there...

If pyload is and started an PATH is something like `/bin;/sbin;` , pyload will see that only.
If after that PATH gets `/opt/bin` also, pyload will not see it even if current value of  PATH is now `/bin;/sbin;/opt/bin;`

**Comment by led13714** [comment]
Well if that is the case - and I'm still not sure if I fully understand this behaviour - how could I fix it?

**Comment by GammaC0de** [comment]
@led13714 This is how linux (and even windows) works: every process has its own environment variables that it got from the process that started it, it does not change after that.

Try searching for `*pyload*` file everywhere...

**Comment by led13714** [comment]
I understand that each process has its own environment. 
I meant the part that 
> If after that PATH gets /opt/bin also, ...

How and why would the Path variable change after the start of pyload?

searching for "pyload" everywhere as you mentioned results in:

>DS214p> find / -name "pyload*"
/root/.pyload/scripts/pyload_start
/root/.pyload/scripts/pyload_restart
/root/.pyload/scripts/pyload_stop
/root/.pyload/pyload.conf
/volume1/@eaDir/pyload
/volume1/pyload
/volume1/@optware/lib/ipkg/info/pyload.list
/volume1/@optware/lib/ipkg/info/pyload.control
/volume1/@optware/share/pyload
/volume1/@optware/share/pyload/pyload-stable
/volume1/@optware/share/pyload/icons/pyload-gui.ico
/volume1/@optware/share/pyload/icons/pyload.ico
/volume1/@optware/share/pyload/icons/pyload2.ico
/volume1/@optware/share/pyload/module/remote/thriftbackend/pyload.thrift
/volume1/@optware/share/pyload/module/remote/thriftbackend/thriftgen/pyload
/volume1/@optware/share/pyload/module/web/media/default/img/pyload-logo-edited3.5-new-font-small.png
/volume1/@optware/share/pyload/module/web/pyload_app.py
/volume1/@optware/share/pyload/module/web/pyload_app.pyc
/volume1/@optware/share/pyload/pyload_tip
/volume1/@optware/share/pyload_config
/volume1/@optware/share/pyload_config/pyload.conf
/volume1/@optware/pyload-v0.4.9-noarch.ipk
/volume1/@optware/pyload_tip
/volume1/@optware/pyload_tip/lib/ipkg/info/pyload.list
/volume1/@optware/pyload_tip/lib/ipkg/info/pyload.control


and


> DS214p> find / -type d -name "pyload"
/volume1/@eaDir/pyload
/volume1/pyload
/volume1/@optware/share/pyload
/volume1/@optware/share/pyload/module/remote/thriftbackend/thriftgen/

**Comment by GammaC0de** [comment]
Whats in `/root/.pyload/scripts/pyload_start`?

**Comment by led13714** [comment]
Nothing.

> DS214p> pwd
/root/.pyload/scripts/pyload_start
DS214p> ls
DS214p>

**Comment by GammaC0de** [comment]
`cat /root/.pyload/scripts/pyload_start`

**Comment by led13714** [comment]
> DS214p> cat /root/.pyload/scripts/pyload_start
cat: read error: Is a directory

**Comment by GammaC0de** [comment]
How did you installed pyload?

How do you make it start/stop/load on startup?

**Comment by led13714** [comment]
Originally installed it using the synology community package.
After some problems with the updatemanager i reinstalled using ipkg.
start & stop worked with the S99pyload script for a while. I guess it all comes down to the java upgrade (had to remove the old version before installing the never one), because at around that time pyload seems to be missing the js engine.

**Comment by GammaC0de** [comment]
Does it loads automatically on reboot now?

if it does not work with S99pyload, how do you start it now?

**Comment by led13714** [comment]
shell script:
> /opt/bin/python2.5 /volume1/@optware/share/pyload/pyLoadCore.py --daemon

**Comment by GammaC0de** [comment]
ok, so now its simple:
Try this:
```bash
#!/bin/sh

add_to_path ()
{
    if [[ "$PATH" =~ (^|:)"${1}"(:|$) ]]
    then
        return 0
    fi
    export PATH=${1}:$PATH
}

add_to_path /opt/bin
add_to_path /opt/sbin

/opt/bin/python2.5 /volume1/@optware/share/pyload/pyLoadCore.py --daemon
```

**Comment by led13714** [comment]
line 5: syntax error: unexpected "(" (expecting "then")

**Comment by GammaC0de** [comment]
OK, try now (script updated)

**Comment by led13714** [comment]
yep bash instead of sh strikes again...
script is working and so is pyload. 

Thanks for all your help and the quick replies!

**Comment by GammaC0de** [comment]
:+1: 
Now JS Engine found?

**Comment by led13714** [comment]
yes. no more issues with zippyshare downloads so far.

**Comment by GammaC0de** [comment]
:+1: 
Closing..
