### ISSUE TITLE
[question] Where I can find a fixed ExtractArchive plugin? ... also fixed in a dirty way.

### ISSUE THREAD

**Issue by FabrizioA** [pyload/pyload#2465]
Any ideas??
Time ago I found a version of pyLoad with a working ExtractArchive plugins... but I can not remember where I found it :(

**Comment by ladigb** [comment]
Hi
i think is that one:
https://github.com/pyload/pyload/archive/5ee1a6ddf8cd550e58224817f306d4ddebd1512e.zip

**Comment by FabrizioA** [comment]
Thank you @ladigb but I have tried it without success...
I have added my reply here: https://github.com/pyload/pyload/issues/2296 maybe you can help me.

**Comment by ladigb** [comment]
Hi 
strange coz i using it since two moths and extractarchive is working without any issue:
 
please try do it in step 

1-Install pyload
2-Disable update manager 
3 Delate plugins folder 
4 Copy plugins folder from the url i had pass you 
5 Restart 
should work if not i don`t know why .

Regards

**Comment by FabrizioA** [comment]
Thank you @ladigb. About pyload install, you intend last and official pyload version right?
And the, I need to replace entire plugins folder or only extract archive plugin?

**Comment by ladigb** [comment]
Hi
Yes last official version, then disable update manager, and on end  delete entire plugin folder, and copy that one from url

**Comment by FabrizioA** [comment]
Works ok! I had only set a small configuration for my hoster. Thank you.

**Comment by freezer69** [comment]
Hello! I had the same problem and error as the thread starter, and I did the same fix as suggested.
ExtractArchive is now not giving me any errors anymore and it says that extracting was successfull, but the files in the archives do not get extracted :( I tried with a zip archive, which was working correctly. But with rar files it doesn't work, the destination folder is empty. I already checked the user rights of this folder, but after that I checked that zip archived get extracted correctly.

P.S. I already tried other rar archives from other sources, same problem! Hope you can help me, thanks in advance!

Here is the output of python, which is not that much and it tells everything is fine:
`17.05.2016 18:14:53 INFO      HOSTER UploadedTo[6]: Downloading file...
17.05.2016 18:14:54 INFO      HOSTER UploadedTo[6]: Checking downloaded file...
17.05.2016 18:14:54 INFO      HOSTER UploadedTo[6]: Checking downloaded file with built-in rules...
17.05.2016 18:14:54 INFO      HOSTER UploadedTo[6]: Checking downloaded file with custom rules...
17.05.2016 18:14:54 INFO      HOSTER UploadedTo[6]: File is OK
17.05.2016 18:14:54 INFO      Download finished: abvaaaa.rar
17.05.2016 18:14:54 INFO      Package finished: abababa
17.05.2016 18:14:54 INFO      ADDON ExtractArchive: Check package: abababa
17.05.2016 18:14:54 INFO      ADDON ExtractArchive: abvaaaa.rar | Extract to: /media/hdd/Downloads/
17.05.2016 18:14:55 INFO      ADDON ExtractArchive: Deleting 1 files
17.05.2016 18:14:55 INFO      ADDON ExtractArchive: abvaaaa.rar | Extracting finished
`

**Comment by ladigb** [comment]
Hi 
did you disable plugin update manager before you have swap plugin folder ?

**Comment by freezer69** [comment]
Hi, thanks for that quick reply and of course I did everything as advised in your fix. I just found the solution, my unrar version was to old(3.4), I updated to newest for my dreambox and now everything is working fine, but wouldn't without your fix above! thank you very much for that :)

**Comment by ladigb** [comment]
#good to hear is start working :) just dont forget enable update manager, when extractarchive plugin will be fix.
and solution is made by @GammaC0de  from this ticket  #2296 

Regards

**Comment by GammaC0de** [comment]
Closing..
