### ISSUE TITLE
share-online.biz

### ISSUE THREAD

**Issue by t09** [pyload/pyload#2466]
Hi,

seems hoster changed something....debug log:
[debug_Report.txt](https://github.com/pyload/pyload/files/264479/debug_Report.txt)

thanks in advance

**Comment by GammaC0de** [comment]
@t09 This is debug report, not debug log.
Please enable debug mode and the post the log, thanks.

**Comment by t09** [comment]
@GammaC0de : this was the best i could do....seems login not working any more
[log.txt](https://github.com/pyload/pyload/files/264989/log.txt)

**Comment by GammaC0de** [comment]
@t09 I need account for testing, please send account info  to nitzo2001 \[AT\] yahoo \[DOT\] com

**Comment by t09** [comment]
@GammaC0de : done ;)

**Comment by GammaC0de** [comment]
seems to work fine here, try refreshing your userplugins (see #2241)

**Comment by t09** [comment]
thanks man! dont know whats goin on on my server...my bad - thanks for fast reply!

**Comment by GammaC0de** [comment]
:+1:
