### ISSUE TITLE
UpdateManager announce New Version

### ISSUE THREAD

**Issue by Web-Eye** [pyload/pyload#2472]
Hi,

my UpdateManager set the following lines:

`21.05.2016 23:01:33	INFO	ADDON UpdateManager: *** New pyLoad available ***`
`21.05.2016 23:01:33	INFO	ADDON UpdateManager: *** Get it here: https://github.com/pyload/pyload/releases *** `

But at this url are only the 0.4.9 packages. Is there's something wrong, or how do I handle this?
Maybe this related to #2469

Thanks,
WebEye #

**Comment by Velociraptor85** [comment]
yap seems to be that way :) Problem with the UpdateServer, I have the same message.

Maybe close this issue since the source is already Documented by you

**Comment by GammaC0de** [comment]
same as #2469

**Comment by GammaC0de** [comment]
manually update your `UpdateManager.py` with https://github.com/pyload/pyload/blob/d2498ffa4c58a2180a9d84e644ee9eeaa95fd1ba/module/plugins/hooks/UpdateManager.py  to fix this issue.
