### ISSUE TITLE
Hugefiles plugin: Too many OPs

### ISSUE THREAD

**Issue by Nico5206** [pyload/pyload#2474]
Hello,

when trying to download something on hugefiles, I get the following logs:
[logs.txt](https://github.com/pyload/pyload/files/277143/logs.txt)

and thus cannot download anything from hugefiles. Could you have a look please?

Thanks!

**Comment by GammaC0de** [comment]
Free download now works, account info is needed for testing premium download.
Please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com.

**Comment by Nico5206** [comment]
Hi thanks for the fix, free download is working fine now!

For the account information, I only have a free membership (which seems to still have an impact on download speed). I don't know if this one is taken into account or not. I have this in debug:

DEBUG     HOSTER HugefilesNet[7]: LOAD URL http://hugefiles.net/myfile | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'adcopy_response': u'no dice', u'adcopy_challenge': u'<a lot of stuff>', u'fsize1': u'4065485213', u'ctype': u'5', u'usr_login': '', u'referer': u'http://hugefiles.net/myfile', u'fname': u'myfile', u'method_free': 'Free Download', u'id': u'xaymzj9ude3g', u'op': u'download1'} | ref=True | just_header=False

which does not contain a usr_login.
