### ISSUE TITLE
[Question] Time to leave 1.0.0 and older stuff in the past. ?! 

### ISSUE THREAD

**Issue by Jonn3y** [pyload/pyload#2476]
Ola lovely Pyload-Community,

I don't know why but one of the dev's renamed the old beta 0.5 from 2013 to Version 1.0.0

I think it's time to begin a new era and it's time to leave all the old stuff in the past. 
a) The new release should be called also Beta 0.5 or something higher than 1.0. 
or:
b) The old 1.0.0 should be renamed to something like 0.4.10b or whatever :)

It would not be correct to give the next release a lower release-number than the 3 year old beta! 

Just in my opinion!. What do you say?! 
#sorryforbadenglish

**Comment by GammaC0de** [comment]
0.5 or 1.0.0 or whatever was planned to be a complete rewrite of pyLoad by @RaNaN with a lot of new features.
It was never finished and I think it can be considered abandoned now.

It was renamed to 1.0.0 to prevent conflict with the stable 0.4.x and the upcoming 0.5 - probably not so good name for it.

It is here for archival purposed, one can never know..

**Comment by vuolter** [comment]
Exactly, as @GammaC0de said the old 0.5 (now 1.0) has some advanced features I don't want to lose like a nodejs webui, new network modules and so on, features I plan to integrate in the new releases.
On the other hand, recent changes have made only few modules mergeable in new releases, I'm not sure, but I think just api, database (partially) and datatypes. It's a tough nut to crack. :s

**Comment by Jonn3y** [comment]
Okay, some understandable reasons. Thanks! 👍
