### ISSUE TITLE
[Hoster] NitroflareCom | Nitro Flare - No premium login

### ISSUE THREAD

**Issue by StarScream159** [pyload/pyload#2477]
Hello. The hoster Nitroflare use to work (premium), but it has seemed to have stopped.

The plugin can't log in my account anymore. Here's the log:
```
25.05.2016 16:48:36	INFO	ACCOUNT NitroflareCom: Adding user `************@gmail.com`...
25.05.2016 16:48:36	DEBUG	ACCOUNT NitroflareCom: Reached login timeout for user `************@gmail.com`
25.05.2016 16:48:36	INFO	ACCOUNT NitroflareCom: Login user `************@gmail.com`...
25.05.2016 16:48:36	DEBUG	ACCOUNT NitroflareCom: LOAD URL https://nitroflare.com/login | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={} | ref=True | multipart=False
25.05.2016 16:48:37	DEBUG	CAPTCHA NitroflareCom: ReCaptcha | Key: 6Lenx_USAAAAAF5L1pmTWvWcH73dipAEzNnmNLgy
25.05.2016 16:48:37	DEBUG	CAPTCHA NitroflareCom: ReCaptcha | Key: 6Lenx_USAAAAAF5L1pmTWvWcH73dipAEzNnmNLgy
25.05.2016 16:48:37	DEBUG	ACCOUNT NitroflareCom: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6Lenx_USAAAAAF5L1pmTWvWcH73dipAEzNnmNLgy | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={} | ref=https://nitroflare.com/login | multipart=False
25.05.2016 16:48:37	ERROR	ACCOUNT NitroflareCom: Could not login user `************@gmail.com` | Bad server response: 400 Bad Request
```
I checked my hoster plugin version with the repo and it is up to date.

EDIT: ~~wow I can not get this to format well.~~ There we go.

**Comment by GammaC0de** [comment]
Account info needed, please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com

**Comment by StarScream159** [comment]
Credentials sent. Thanks.

**Comment by GammaC0de** [comment]
:+1:

**Comment by GammaC0de** [comment]
Can't login with captcha turned off?

**Comment by StarScream159** [comment]
Sorry, I don't understand. Disable Captcha in pyload?

**Comment by GammaC0de** [comment]
no, disable nitfroflare asking for Captcha in https://nitroflare.com/login

**Comment by StarScream159** [comment]
I must be dense. I can't find an option to disable Captcha for logins anywhere in my account for NitroFlare or anything.

**Comment by GammaC0de** [comment]
Yes, I looked for it too, that's why I asked you. some hosters do have this option wich makes your life easier.

**Comment by StarScream159** [comment]
Sorry, I only saw options for "direct download" which I think allows you to start downloading the file automatically when you visit the page as oppose to clicking the "download" link. Probably has zero effect for pyload though.

**Comment by GammaC0de** [comment]
I'm sorry but it seems that nitroflare has disabled the option to use javascript-less Recaptcha on their login page :-1: 

currently no solution for that

Either ask them for support or choose another hoster

**Comment by StarScream159** [comment]
I've contacted them for support. I'll update this ticket when I hear back. Thanks.

**Comment by nicobubulle** [comment]
It's seems to work again.

**Comment by StarScream159** [comment]
This is the message I sent:

> I am having a problem using the download manager pyLoad. The system can't login. I've submitted an issue ticket with the developers and they've said there is nothing they can do: "I'm sorry but it seems that nitroflare has disabled the option to use javascript-less Recaptcha on their login page".

And I included a link to this issue page.

This is the response I got:

> Issues with Downloaders are out of our control
> and you need to contact the respective Downloader Support regarding them
> (Make Sure you have check marked Direct Download at User> Premium Access).
> If you are able to use our service via the web browser
> it means our service is working fine.
> 
> Thanks.

I followed up again, but so far I am not impressed with there support. Looks like I won't be renewing my account with them if this is how they deal with support issues.

**Comment by StarScream159** [comment]
nicobubulle is correct. I can confirm that it is working again. Maybe, even with their crummy support reply, they actually changed the way the login works.

I'll test over the next couple of days and if everything seems okay I'll close this ticket.

Thanks everyone.

**Comment by StarScream159** [comment]
Still working okay. I'm going to close this ticket and assume they changed something when I emailed them even though they said they didn't. Thanks for all the help.

**Comment by artdog** [comment]
Stopped working again as of this morning:
01.06.2016 07:53:25	ERROR	ACCOUNT NitroflareCom: Could not login user `artdog@gmail.com` | Bad server response: 400 Bad Request

**Comment by artdog** [comment]
Jdownloader does not have this problem.

**Comment by StarScream159** [comment]
@artdog I noticed this yesterday too. However I was able to get a successful login after removing the account and re-adding it. Does that work for you too?

**Comment by artdog** [comment]
No I tried that. No effect.

**Comment by nicobubulle** [comment]
It's a recaptcha behaviour on login page. Sometime they turn it on and sometime not... This plugin only work when it's not activated @GammaC0de Is it possible to work with cookie instead of credential ?

**Comment by GammaC0de** [comment]
> Is it possible to work with cookie instead of credential

What do you mean by that?

It did work even with captcha.
Tthe problem is that sometimes google rejects the captcha request causing the failure to login.

**Comment by nicobubulle** [comment]
> What do you mean by that?

I don't know how plugin work but once i'm logged on nitroflare i d'ont need to enter credentials again with cookies maybe if i use this cookies the plugin won't need to login.

Do you need credential to try ? At this moment it works because recaptcha is turn off on login page.

++

**Comment by GammaC0de** [comment]
Please try this update: https://github.com/pyload/pyload/commit/d143c31e0bd134b806a341b3c88041ea2a4f88ee

**Comment by nicobubulle** [comment]
update done, thanks for this. It will at least prevent against unecessary login.

**Comment by GammaC0de** [comment]
:+1: 
Please update if the captcha problem still exist

**Comment by StarScream159** [comment]
Can confirm it has fixed the issue for me too. I'll close this again for now. Thanks @GammaC0de.

**Comment by StarScream159** [comment]
Sorry, have to reopen. It worked for me once when I re-added my account but then when I attempted to download something it tried to use the default/generic hoster and not the Nitroflare one. When I attempt to add the account now I get the following errors:

```02.06.2016 10:23:26 INFO      ACCOUNT NitroflareCom: Adding user `***********@gmail.com`...
02.06.2016 10:23:26 DEBUG     ACCOUNT NitroflareCom: Reached login timeout for user `***********@gmail.com`
02.06.2016 10:23:26 INFO      ACCOUNT NitroflareCom: Login user `***********@gmail.com`...
02.06.2016 10:23:26 DEBUG     ACCOUNT NitroflareCom: LOAD URL https://nitroflare.com/login | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={} | ref=True | multipart=False
02.06.2016 10:23:27 DEBUG     CAPTCHA NitroflareCom: ReCaptcha | Key: 6Lenx_USAAAAAF5L1pmTWvWcH73dipAEzNnmNLgy
02.06.2016 10:23:27 DEBUG     CAPTCHA NitroflareCom: ReCaptcha | Key: 6Lenx_USAAAAAF5L1pmTWvWcH73dipAEzNnmNLgy
02.06.2016 10:23:27 DEBUG     ACCOUNT NitroflareCom: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6Lenx_USAAAAAF5L1pmTWvWcH73dipAEzNnmNLgy | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={} | ref=https://nitroflare.com/login | multipart=False
02.06.2016 10:23:27 ERROR     ACCOUNT NitroflareCom: Could not login user `***********@gmail.com` | Bad server response: 400 Bad Request
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 504, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/lib/wsgiserver/__init__.py", line 1271, in run
    conn.communicate()
  File "/opt/pyload/module/lib/wsgiserver/__init__.py", line 1174, in communicate
    req.respond()
  File "/opt/pyload/module/lib/wsgiserver/__init__.py", line 544, in respond
    self._respond()
  File "/opt/pyload/module/lib/wsgiserver/__init__.py", line 556, in _respond
    response = self.wsgi_app(self.environ, self.start_response)
  File "/opt/pyload/module/web/middlewares.py", line 53, in __call__
    response.gzip_start_response)
  File "/opt/pyload/module/web/middlewares.py", line 17, in __call__
    return self.app(e, h)
  File "/opt/pyload/module/lib/beaker/middleware.py", line 152, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/opt/pyload/module/lib/bottle.py", line 843, in __call__
    return self.wsgi(environ, start_response)
  File "/opt/pyload/module/lib/bottle.py", line 820, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/opt/pyload/module/web/json_app.py", line 276, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/opt/pyload/module/Api.py", line 894, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 149, in updateAccount
    updated = p.updateAccounts(user, password, options)
  File "/opt/pyload/module/plugins/internal/misc.py", line 234, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 333, in updateAccounts
    self.add(user, password, options)
  File "/opt/pyload/module/plugins/internal/misc.py", line 234, in new
  File "/opt/pyload/module/plugins/internal/Account.py", line 333, in updateAccounts
    self.add(user, password, options)
  File "/opt/pyload/module/plugins/internal/misc.py", line 234, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 309, in add
    result = u['plugin'].choose(user)
  File "/opt/pyload/module/plugins/internal/misc.py", line 234, in new
    return fn(*args, **kwargs)
  File "/opt/pyload/module/plugins/internal/Account.py", line 423, in choose
    self.relogin()
  File "/opt/pyload/module/plugins/internal/Account.py", line 177, in relogin
    return self.login()
  File "/opt/pyload/module/plugins/internal/Account.py", line 116, in login
    self.signin(self.user, self.info['login']['password'], self.info['data'])
  File "/opt/pyload/module/plugins/accounts/NitroflareCom.py", line 90, in signin
    response, challenge = self.captcha.challenge()
  File "/opt/pyload/module/plugins/captcha/ReCaptcha.py", line 67, in challenge
    version=2 if re.search(self.KEY_V2_PATTERN, data or self.retrieve_data()) else 1)
  File "/opt/pyload/module/plugins/captcha/ReCaptcha.py", line 63, in challenge
    return getattr(self, "_challenge_v%s" % version)(key)
  File "/opt/pyload/module/plugins/captcha/ReCaptcha.py", line 242, in _challenge_v2
    html = self.pyfile.plugin.load(fallback_url, ref=self.pyfile.url)
  File "/opt/pyload/module/plugins/internal/Plugin.py", line 213, in load
    html = req.load(url, get, post, bool(ref), bool(cookies), just_header, multipart, decode is True)  #@TODO: Fix network multipart in 0.4.10
  File "/opt/pyload/module/network/Browser.py", line 97, in load
    return self.http.load(*args, **kwargs)
  File "/opt/pyload/module/network/HTTPRequest.py", line 208, in load
    self.code = self.verifyHeader()
  File "/opt/pyload/module/network/HTTPRequest.py", line 222, in verifyHeader
    raise BadHeader(code, self.getResponse())
BadHeader: Bad server response: 400 Bad Request```

If you need to use my account to test again, I haven't changed the password back - so it will still be the same from the first email I sent you a week ago.

**Comment by GammaC0de** [comment]
I have tested this with JDownloader and is suffers from the same issue:

JDownloader first tries its javascript-less version of ReCaptcha (`http://www.google.com/recaptcha/api/fallback`) and fails as pyload do.
Now the difference is that JDownloader fallbacks to its browser based ReCaptcha plugin (i.e. opens a browser window for you to solve the captcha - i'm not a robot B.S.)

Since pyload operetes remotely it cannot communicate with your local browser solving the captcha (well not easily though, mabe websockets would help here)  

It seems that Nitroflare plays with you and has not decided whether is allows or disallows javascript-less recaptcha's so It has been disabling and enabling this option few times

```
recaptchav2.log
--ID:96TS:1465422027334-6/9/16 12:40:27 AM -  [org.jdownloader.captcha.v2.ChallengeResponseController(handle)] -> Handle Challenge: org.jdownloader.captcha.v2.challenge.recaptcha.v2.RecaptchaV2Challenge@3d3a3fd1
--ID:96TS:1465422027336-6/9/16 12:40:27 AM -  [org.jdownloader.captcha.v2.ChallengeResponseController(handle)] -> Solver: [RecaptchaChooseFrom3x3Solver]
--ID:96TS:1465422027337-6/9/16 12:40:27 AM -  [org.jdownloader.captcha.v2.ChallengeResponseController(handle)] -> Send to solver: RecaptchaChooseFrom3x3Solver CaptchaJob: org.jdownloader.captcha.v2.challenge.recaptcha.v2.RecaptchaV2Challenge@3d3a3fd1 Solver: [RecaptchaChooseFrom3x3Solver]
--ID:96TS:1465422027338-6/9/16 12:40:27 AM -  [org.jdownloader.captcha.v2.ChallengeResponseController(handle)] -> Fire New Job Event
--ID:96TS:1465422027339-6/9/16 12:40:27 AM -  [org.jdownloader.captcha.v2.ChallengeResponseController(handle)] -> Wait
------------------------Thread: 98:TimeTracker recaptchav2.log-----------------------
--ID:98TS:1465422027340-6/9/16 12:40:27 AM -  [org.jdownloader.captcha.v2.JobRunnable(run)] -> RecaptchaChooseFrom3x3Solver is Active.
--ID:98TS:1465422027341-6/9/16 12:40:27 AM -  [org.jdownloader.captcha.v2.JobRunnable(run)] -> Solver Start: RecaptchaChooseFrom3x3Solver
--ID:98TS:1465422027535-6/9/16 12:40:27 AM -  [] -> org.appwork.exceptions.WTFException: jd.http.Browser$BrowserException
	at org.jdownloader.captcha.v2.challenge.recaptcha.v2.Recaptcha2FallbackChallenge.load(Recaptcha2FallbackChallenge.java:93)
	at org.jdownloader.captcha.v2.challenge.recaptcha.v2.Recaptcha2FallbackChallenge.<init>(Recaptcha2FallbackChallenge.java:33)
	at org.jdownloader.captcha.v2.challenge.recaptcha.v2.RecaptchaV2Challenge.createBasicCaptchaChallenge(RecaptchaV2Challenge.java:180)
	at org.jdownloader.captcha.v2.solver.gui.RecaptchaChooseFrom3x3Solver.solve(RecaptchaChooseFrom3x3Solver.java:91)
	at org.jdownloader.captcha.v2.JobRunnable.run(JobRunnable.java:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: jd.http.Browser$BrowserException
	at jd.http.Browser.loadConnection(Browser.java:1268)
	at jd.http.Browser.getPage(Browser.java:1113)
	at jd.http.Browser.getPage(Browser.java:1109)
	at org.jdownloader.captcha.v2.challenge.recaptcha.v2.Recaptcha2FallbackChallenge.load(Recaptcha2FallbackChallenge.java:50)
	... 7 more
Caused by: java.io.IOException: 400 Bad Request
	at org.appwork.utils.net.httpconnection.HTTPConnectionImpl.getInputStream(HTTPConnectionImpl.java:1117)
	at jd.http.Request.read(Request.java:128)
	at jd.http.Request.read(Request.java:679)
	at jd.http.Browser.loadConnection(Browser.java:1257)
	... 10 more

```

**Comment by artdog** [comment]
Thanks GammaC0de. For me I can download without problems from Nitroflare using Jdownloader but pyload only occasionally. I'm glad I only signed up for a month with Nitroflare. I guess I will look for another hoster. Shame as Nitro is very fast.

**Comment by StarScream159** [comment]
Thanks for all the background information @GammaC0de. I, like @artdog, can sometimes download from pyLoad.

It seems the best way to do it is to login to the site using a browser behind the same connection that pyLoad runs on. Then it seems to allow the javascript login method to work. Maybe they track IPs or something and only disallow javascript login when it is a new connection.

**Comment by artdog** [comment]
StarScream that didn't work for me. I was able to successfully use Jdownloader this morning with my premium nitroflare account. Pyload didn't work though.

**Comment by artdog** [comment]
Had a bit of a disagreement with Nitroflare support as their response to my saying I would not renew my subscription if I can't use pyload was "So don't renew. We could care less"

Now I can't access the site. Have they cut me off somehow or are they down?

**Comment by StarScream159** [comment]
Can't answer to if they are down or not, but yes, I agree: I too was not too pleased with their reply. I already let my Premium account expire. I do not intend on renewing.

**Comment by anonymous-aardvark** [comment]
Their support people certainly are not very supportive.  Same as others - they don't want to know about problems, and say that the CAPTCHA changes are to deal with script/bot attacks.  I dug into the source for the JDownloader2 plugin and found it can use the NF API so I used it as a reference to redo the Pyload NF plugin to use the API.  Works for me so far - see pull request #2512.

**Comment by GammaC0de** [comment]
Someone please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com to test #2512

**Comment by anonymous-aardvark** [comment]
@GammaC0de account info sent.  Brand new account just for you to test with.

**Comment by GammaC0de** [comment]
@anonymous-aardvark Thanks :+1:

**Comment by artdog** [comment]
I'm not sure if I got the fix or not but nitroflare has been working flawlessly for the past 2 days.

**Comment by GammaC0de** [comment]
:+1: Plugin version 0.22 is the latest.

**Comment by GammaC0de** [comment]
Two method:
1. activate debug mode, start a download and look in the log.
2. look inside [NitroflareCom.py](https://github.com/pyload/pyload/blob/79dad368430c24a89fd2502dddb7f1b2bb012a71/module/plugins/hoster/NitroflareCom.py#L14) for `__version__`

**Comment by artdog** [comment]
Ok. I have replaced the previous version with the new one. I will post if I have any problems with it.

**Comment by GammaC0de** [comment]
@artdog you should update both account and hoster plugins.
Anyway, you should have got them updated already by updatemanager so please verify your updatemanager.py is up to date (read https://github.com/pyload/pyload/issues/2469)
