### ISSUE TITLE
Download slow and Updates available 

### ISSUE THREAD

**Issue by mauli16** [pyload/pyload#2478]
My pyload downloads are limited to around 150kb. 

I tested on the raspberry itself with speedtest.net and there should be 9Mbit available. I use a simply premium account, which has fullspeed downloads via web browser. 
   
And for some days I receive the message 
```
INFO	UpdateManager: *** New pyLoad Version available ***
INFO	UpdateManager: *** Get it here: https://github.com/pyload/pyload/releases ***
```
But I already have 0.49 and there is no newer release. Am I wrong? 

Pyload is running on a raspberry pi under raspbian with builtin webinterface. 

Many thanks in advance!

**Comment by GammaC0de** [comment]
See https://github.com/pyload/pyload/issues/2469#issuecomment-221045788 and https://github.com/pyload/pyload/issues/2241

**Comment by mauli16** [comment]
Thanks for your help GammaC0de ! 

I extracted all 'stable' plugin files in the plugin folder and emptied it before, but now the Log in the web interface shows me: 
`
ERROR	Error importing SimplyPremiumCom: No module named Hook`

Any advice?

**Comment by GammaC0de** [comment]
You should put it in the `userplugins` directory

**Comment by Velociraptor85** [comment]
@mauli16 is the issue still present? or can we close the issue?

**Comment by mauli16** [comment]
Didn't worked on it again since then, because I was foolish and deleted the wrong folder of plugins (system trunk) and had trouble to reinstall pyload after that. I used 'purge' to uninstall, but pyload didn't went well after installing. 

Maybe I will install everything again on a clean raspbian... need some time for that :-)

So, you can close this ticket. Thanks for asking and and many thanks for your help!

**Comment by GammaC0de** [comment]
:+1:

**Comment by mauli16** [comment]
Hi, 

found some time and did a full reinstall of everything. After that I droped all stable plugins in userplugins, activated the simplypremium addon and added the account information. 

My Problem now: I only can download as free user on every hoster. It seems the simply premium plugin is not activated, but there is no checkbox or anything in the pyload plugin section to let me do that...

Many thanks in advance, again!!!

`08.09.2016 20:15:16 INFO      Aktivierte Plugins: CaptchaTrader, ClickAndLoad, ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
08.09.2016 20:15:16 INFO      Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, Ev0InFetcher, ExpertDecoders, HotFolder, IRC, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, MultishareCz, PushBullet, PushOver, RealdebridCom, RehostTo, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP, XMPPInterface
08.09.2016 20:15:16 INFO      Downloadzeit: True
08.09.2016 20:15:16 INFO      Freier Speicher: 19.30 GiBGB
08.09.2016 20:15:17 INFO      Aktiviere Accounts...
08.09.2016 20:15:20 INFO      Starting builtin webserver: 192.168.178.27:8000
08.09.2016 20:15:21 INFO      ACCOUNT SimplyPremiumCom: Adding user XXX`...
08.09.2016 20:15:21 INFO      ACCOUNT SimplyPremiumCom: Login user `XXX`...
08.09.2016 20:15:22 INFO      ACCOUNT SimplyPremiumCom: Grabbing account info for user `XXX`...
08.09.2016 20:15:22 INFO      ACCOUNT SimplyPremiumCom: Grabbing account info for user `XXX`...
08.09.2016 20:15:22 INFO      Activating Plugins...
08.09.2016 20:15:24 ERROR     Error importing ShareRapidCom: cannot import name parseFileInfo
08.09.2016 20:15:26 INFO      ADDON XFileSharing: Auto-discover new hosters
08.09.2016 20:15:28 INFO      ADDON XFileSharing: Auto-discover new crypters
08.09.2016 20:15:28 INFO      pyLoad is up and running
08.09.2016 20:15:28 INFO      ADDON UpdateManager: pyLoad is up to date!
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/accounts/BitshareCom.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/accounts/BitshareCom.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/accounts/HotfileCom.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/accounts/HotfileCom.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/accounts/NetloadIn.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/accounts/NetloadIn.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/accounts/RapidshareCom.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/accounts/RapidshareCom.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/accounts/ShareRapidCom.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/accounts/ShareRapidCom.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/accounts/UploadingCom.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/accounts/UploadingCom.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/captcha/captcha.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/captcha/captcha.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/container/DLC_25.pyc` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/container/DLC_25.pyc'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/container/DLC_26.pyc` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/container/DLC_26.pyc'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/container/DLC_27.pyc` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/container/DLC_27.pyc'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/container/LinkList.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/container/LinkList.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/crypter/HotfileFolderCom.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/crypter/HotfileFolderCom.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/crypter/OneKhDe.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/crypter/OneKhDe.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/crypter/ShareRapidComFolder.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/crypter/ShareRapidComFolder.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/crypter/YoutubeBatch.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/crypter/YoutubeBatch.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/hooks/CaptchaTrader.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/hooks/CaptchaTrader.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/hooks/ClickAndLoad.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/hooks/ClickAndLoad.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/hooks/Ev0InFetcher.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/hooks/Ev0InFetcher.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/hooks/IRCInterface.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/hooks/IRCInterface.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/hooks/MultishareCz.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/hooks/MultishareCz.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/hooks/RealdebridCom.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/hooks/RealdebridCom.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/hooks/RehostTo.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/hooks/RehostTo.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/hooks/XMPPInterface.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/hooks/XMPPInterface.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/hoster/RapidshareCom.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/hoster/RapidshareCom.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/hoster/ShareRapidCom.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/hoster/ShareRapidCom.py'
08.09.2016 20:15:29 WARNING   ADDON UpdateManager: Error removing `/usr/share/pyload/module/plugins/internal/AbstractExtractor.py` | [Errno 13] Permission denied: '/usr/share/pyload/module/plugins/internal/AbstractExtractor.py'
08.09.2016 20:15:29 INFO      ADDON UpdateManager: All plugins are up to date!
08.09.2016 20:15:30 INFO      Download starts: SRG.THG.S01e01.720p.webrip.x264-skgtv.part1.rar
08.09.2016 20:15:30 WARNING   HOSTER RapidgatorNet[17]: Plugin may be unstable
08.09.2016 20:15:30 INFO      HOSTER RapidgatorNet[17]: Grabbing link info...
08.09.2016 20:15:30 INFO      HOSTER RapidgatorNet[17]: Link name: SRG.THG.S01e01.720p.webrip.x264-skgtv.part1.rar
08.09.2016 20:15:30 INFO      HOSTER RapidgatorNet[17]: Link size: 1000.00 MiB (1048576000 bytes)
08.09.2016 20:15:30 INFO      HOSTER RapidgatorNet[17]: Link status: online
08.09.2016 20:15:30 INFO      HOSTER RapidgatorNet[17]: Processing url: http://rapidgator.net/file/06d8d8c6f4d8103803e70b80000ea9c0/SRG.THG.S01e01.720p.webrip.x264-skgtv.part1.rar.html
08.09.2016 20:15:30 INFO      HOSTER RapidgatorNet[17]: Looking for direct download link...
08.09.2016 20:15:31 INFO      HOSTER RapidgatorNet[17]: Direct download link not found
08.09.2016 20:15:31 INFO      HOSTER RapidgatorNet[17]: Checking for link errors...
08.09.2016 20:15:31 INFO      HOSTER RapidgatorNet[17]: No errors found
08.09.2016 20:15:31 INFO      HOSTER RapidgatorNet[17]: Processing as free download...
08.09.2016 20:15:31 INFO      HOSTER RapidgatorNet[17]: Waiting 45 seconds...
08.09.2016 20:15:34 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
08.09.2016 20:15:34 ERROR     ADDON ClickNLoad: [Errno 98] Address already in use
08.09.2016 20:16:18 WARNING   CAPTCHA RapidgatorNet[17]: ReCaptcha | Key pattern not found
08.09.2016 20:16:18 INFO      CAPTCHA RapidgatorNet[17]: SolveMedia | Using OCR to decrypt captcha...
08.09.2016 20:16:18 WARNING   CAPTCHA RapidgatorNet[17]: SolveMedia | No OCR result
08.09.2016 20:18:19 WARNING   CAPTCHA RapidgatorNet[17]: SolveMedia | Invalid captcha
08.09.2016 20:18:19 INFO      HOSTER RapidgatorNet[17]: Waiting 1 seconds...
08.09.2016 20:18:21 INFO      Download restarted: SRG.THG.S01e01.720p.webrip.x264-skgtv.part1.rar | No captcha result obtained in appropriate timing
08.09.2016 20:18:21 INFO      Download starts: SRG.THG.S01e01.720p.webrip.x264-skgtv.part1.rar
08.09.2016 20:18:21 WARNING   HOSTER RapidgatorNet[17]: Plugin may be unstable
08.09.2016 20:18:21 INFO      HOSTER RapidgatorNet[17]: Grabbing link info...
08.09.2016 20:18:21 INFO      HOSTER RapidgatorNet[17]: Link name: SRG.THG.S01e01.720p.webrip.x264-skgtv.part1.rar
08.09.2016 20:18:21 INFO      HOSTER RapidgatorNet[17]: Link size: 1000.00 MiB (1048576000 bytes)
08.09.2016 20:18:21 INFO      HOSTER RapidgatorNet[17]: Link status: online
08.09.2016 20:18:21 INFO      HOSTER RapidgatorNet[17]: Processing url: http://rapidgator.net/file/06d8d8c6f4d8103803e70b80000ea9c0/SRG.THG.S01e01.720p.webrip.x264-skgtv.part1.rar.html
08.09.2016 20:18:21 INFO      HOSTER RapidgatorNet[17]: Looking for direct download link...
08.09.2016 20:18:21 INFO      HOSTER RapidgatorNet[17]: Direct download link not found
08.09.2016 20:18:22 INFO      HOSTER RapidgatorNet[17]: Checking for link errors...
08.09.2016 20:18:22 INFO      HOSTER RapidgatorNet[17]: No errors found
08.09.2016 20:18:22 INFO      HOSTER RapidgatorNet[17]: Processing as free download...
08.09.2016 20:18:22 INFO      HOSTER RapidgatorNet[17]: Waiting 45 seconds...
08.09.2016 20:19:08 WARNING   CAPTCHA RapidgatorNet[17]: ReCaptcha | Key pattern not found
08.09.2016 20:19:09 INFO      CAPTCHA RapidgatorNet[17]: SolveMedia | Using OCR to decrypt captcha...
08.09.2016 20:19:09 WARNING   CAPTCHA RapidgatorNet[17]: SolveMedia | No OCR result
08.09.2016 20:19:34 ERROR     ADDON ClickNLoad: [Errno 98] Address already in use
08.09.2016 20:21:09 WARNING   CAPTCHA RapidgatorNet[17]: SolveMedia | Invalid captcha
08.09.2016 20:21:09 INFO      HOSTER RapidgatorNet[17]: Waiting 1 seconds...
08.09.2016 20:21:11 INFO      Download restarted: SRG.THG.S01e01.720p.webrip.x264-skgtv.part1.rar | No captcha result obtained in appropriate timing
08.09.2016 20:21:11 INFO      Download starts: SRG.THG.S01e01.720p.webrip.x264-skgtv.part1.rar
08.09.2016 20:21:11 WARNING   HOSTER RapidgatorNet[17]: Plugin may be unstable
08.09.2016 20:21:11 INFO      HOSTER RapidgatorNet[17]: Grabbing link info...
08.09.2016 20:21:12 INFO      HOSTER RapidgatorNet[17]: Link name: SRG.THG.S01e01.720p.webrip.x264-skgtv.part1.rar
08.09.2016 20:21:12 INFO      HOSTER RapidgatorNet[17]: Link size: 1000.00 MiB (1048576000 bytes)
08.09.2016 20:21:12 INFO      HOSTER RapidgatorNet[17]: Link status: online
08.09.2016 20:21:12 INFO      HOSTER RapidgatorNet[17]: Processing url: http://rapidgator.net/file/06d8d8c6f4d8103803e70b80000ea9c0/SRG.THG.S01e01.720p.webrip.x264-skgtv.part1.rar.html
08.09.2016 20:21:12 INFO      HOSTER RapidgatorNet[17]: Looking for direct download link...
08.09.2016 20:21:12 INFO      HOSTER RapidgatorNet[17]: Direct download link not found
08.09.2016 20:21:12 INFO      HOSTER RapidgatorNet[17]: Checking for link errors...
08.09.2016 20:21:12 INFO      HOSTER RapidgatorNet[17]: No errors found
08.09.2016 20:21:12 INFO      HOSTER RapidgatorNet[17]: Processing as free download...
08.09.2016 20:21:12 INFO      HOSTER RapidgatorNet[17]: Waiting 45 seconds...
08.09.2016 20:21:59 WARNING   CAPTCHA RapidgatorNet[17]: ReCaptcha | Key pattern not found
08.09.2016 20:22:00 INFO      CAPTCHA RapidgatorNet[17]: SolveMedia | Using OCR to decrypt captcha...
08.09.2016 20:22:00 WARNING   CAPTCHA RapidgatorNet[17]: SolveMedia | No OCR result
`
