### ISSUE TITLE
QUESTION - Delete all downloaded folders older than n days except for some specific

### ISSUE THREAD

**Issue by Ryan747800B** [pyload/pyload#2482]
I use this script - connected to an `ExternalScript` and `download_preparing` - to delete all the folders older than 7 days which `pyLoad` creates when it downloads a file:

`find /MyPath/Downloads/* -type d -mtime +7 -exec rm -rf {} \;`

But I have three specific folders that I don't want to delete (`Important`, `WatchDir` and `Incomplete`).

How can I do this? is it possible?

**Comment by GammaC0de** [comment]
```bash
find /MyPath/Downloads/* -type d -mtime +7 ! -path "/MyPath/Downloads/Important/*"  ! -path "/MyPath/Downloads/WatchDir/*"  ! -path "/MyPath/Downloads/Incomplete/*" -exec rm -rf {} \;
```
