### ISSUE TITLE
Feature Request: VPN plugin

### ISSUE THREAD

**Issue by tuxflo** [pyload/pyload#2488]
For non-premium hosters a VPN plugin that uses a different IP could increase the download speed. Such a plugin could use an openVPN or vpnc Backend (installed on the pyload Host). The pyload webgui should just be able to enable the (saved) connections and handle a selection which files should be downloaded via the VPN connection. Maybe some clever algorithm should automatically download even part\*.rar files without VPN and uneven part\*.rar files with the alternate connection.

**Comment by GammaC0de** [comment]
`MultiHome`(https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/MultiHome.py) plugin?

**Comment by GammaC0de** [comment]
Closing because of no response.

**Comment by luizoti** [comment]
Hi, I do not know if I can "reopen" this thread, but how do I use this plugin?

What information do I need to put in Interfaces?

**Comment by GammaC0de** [comment]
@luizoti The plugin requires that you already have a working VPN client with virtual network interfaces assigned to it.

In the plugin configuration you have an option to choose which network interfaces pyLoad will use.
PyLoad will rotate the use of those interfaces.

**Comment by luizoti** [comment]
Thanks for the answer.

 One more doubt interface would be the ip of the device, right?

**Comment by GammaC0de** [comment]
Interface can be an interface name, an IP address or a host name.
The interface list is seperated by `;`.

**Comment by GammaC0de** [comment]
One more thing:
If you use just one VPN connection, you can set the interface to use for downloading in pyLoad settings, `Download` , `Download interface to bind (ip or Name): `

In that case `MultiHome` plugin is unnecessary.
