### ISSUE TITLE
ADDON ClickNLoad - Error

### ISSUE THREAD

**Issue by Ryan747800B** [pyload/pyload#2490]
Doing a fresh install, I now see this error:

`ERROR	ADDON ClickNLoad: (98, 'Address already in use')`

How can I solve it?

**Comment by GammaC0de** [comment]
@Ryan747800B This error should have been fixed in the latest version of ClickNLoad.

**Comment by Ryan747800B** [comment]
I fresh installed pyLoad few hours ago: the error seems not to be fixed. Take in mind that I'm using this version of UpdateManager [(here)](https://github.com/pyload/pyload/issues/2483).

**Comment by GammaC0de** [comment]
- Current version of `UpdateManager` is this: https://github.com/pyload/pyload/blob/f16590e26254b5a39ecbc36b4ac0fa1951d12389/module/plugins/hooks/UpdateManager.py
- Do you have something else listening on port 9666?

**Comment by Ryan747800B** [comment]
- I try it now
- No; that port is free

**Comment by Ryan747800B** [comment]
@GammaC0de  Using directly UpdateManager v1.14 plugins doesn't update, so I have to use v.0.16. I think that to have pyLoad fully updated, I have to use v.0.16 in installation process and then change it with the latest 1.14? is it necessary? What improvements in v1.14?

**Comment by GammaC0de** [comment]
@Ryan747800B You didn't understood my point:
with fresh installation you start with v0.16 (as in #2000) and then it automatically gets updated from the server to the current version (which is v1.14)

As for the above error `(98, 'Address already in use')`, 
This happens when some other process listens to port 9666, so:
- Do you actuially use ClickNLoad? if not, you can disable it.
- if yes, does it work corectly? if yes, you can ignore this error

**Comment by Ryan747800B** [comment]
@GammaC0de OK, now I understand; for that error, I simply disabled that plugin, since I'm not using it; I thought it was an essential pyLoad service, not a simple plugin.
The only issue is that I can not have an updated pyLoad and at the same time RealDebrid and Extract archive working but I know that there is a very long and hard work to do.

**Comment by Ryan747800B** [comment]
@GammaC0de I have only one last question about UpdateManager: as you said it auto-updates from v0.16 to 1.14; but as you remember I use a script to do a full one-time installation on my NAS, with only one reboot. The problem is that v1.14 updates after this reboot and so to have a fully updated and working installation I need to reboot another time. So I tried to do some changes in the script:

```
# pyLoad Install - UpdateManager.py v0.16
cat <<"EOM" >/opt/share/pyload/module/plugins/hooks/UpdateManager.py
...
EOM
# End of pyLoad Install - UpdateManager.py v0.16

# pyLoad Install - Update v0.16
marks=( '/' '-' '\' '|' )

/opt/etc/init.d/pyload start
i=0
tail -f /opt/etc/pyload/Logs/log.txt | while read LOGLINE
do
    printf "\rpyLoad updating, please wait ... ${marks[i++ % ${#marks[@]}]}"
    sleep 0.1
    [[ "${LOGLINE}" == *"please restart pyLoad"* ]] && (pkill -P $$ tail; printf "\rpyLoad updating, please wait ... Done.\n"; )
done
# End of pyLoad Install - Update v0.16

# pyLoad Install - UpdateManager.py v1.14
rm -rf /opt/share/pyload/module/plugins/hooks/UpdateManager.py
cat <<"EOM" >/opt/share/pyload/module/plugins/hooks/UpdateManager.py
...
EOM
# End of pyLoad Install - UpdateManager.py v1.14

# pyLoad Install - Update v1.14
marks=( '/' '-' '\' '|' )

/opt/etc/init.d/pyload stop
/opt/etc/init.d/pyload start
i=0
tail -f /opt/etc/pyload/Logs/log.txt | while read LOGLINE
do
    printf "\rpyLoad updating, please wait ... ${marks[i++ % ${#marks[@]}]}"
    sleep 0.1
    [[ "${LOGLINE}" == *"please restart pyLoad"* ]] && (pkill -P $$ tail; printf "\rpyLoad updating, please wait ... Done.\n"; )
done
# End of pyLoad Install - Update v1.14
```

I prefer to use `cat` so that it isn't necessary to download from GitHub; the problem is that if I do
```
/opt/etc/init.d/pyload stop
/opt/etc/init.d/pyload start
```
NAS shuts down and not only pyLoad. So, is there a way to update to v1.14 from 0.14 in the same installation script?

**Comment by GammaC0de** [comment]
@Ryan747800B UpdateManager v0.16 should have updated itself via the update process, no need for you to manual download it for a new installation.
Manual update was necessary for old installations few days ago because `pyload.org`  DNS expired so you had to manually update from v1.12 that was broken because of that to v1.14 which works with the old update server address.

Just verify that after running you original script , you get UpdateManager v1.14

**Comment by Ryan747800B** [comment]
Yeah now it's perfectly working. This UpdateManager was making me mad!
