### ISSUE TITLE
error if "é" in package name

### ISSUE THREAD

**Issue by codati** [pyload/pyload#2491]
hi
i have :
``
'ascii' codec can't decode byte 0xc3 in position 22: ordinal not in range(128)
``
for download link:
``
 https://1fichier.com/?407jv1hjda
``
my system information
https://jpst.it/J90W
thx for read

**Comment by codati** [comment]
i have "é" in the package name
this is the origin of my error

**Comment by codati** [comment]
the folder is created correctly

**Comment by GammaC0de** [comment]
This is a long lasing issue #2286, hopefully will be fixed when v0.5 will be released hopefully soon.

**Comment by codati** [comment]
thx
