### ISSUE TITLE
BasePlugin didnt work

### ISSUE THREAD

**Issue by eerozeteen** [pyload/pyload#2496]
I cant download files via baseplugin, here is debug (i think that bolded line is a problem):

07.06.2016 21:50:18 INFO      Download starts: EVEResources.7z
07.06.2016 21:50:18 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
07.06.2016 21:50:18 DEBUG     HOSTER BasePlugin[2]: Plugin version: 0.51
07.06.2016 21:50:18 DEBUG     HOSTER BasePlugin[2]: Plugin status: testing
07.06.2016 21:50:18 WARNING   HOSTER BasePlugin[2]: Plugin may be unstable
07.06.2016 21:50:18 DEBUG     HOSTER BasePlugin[2]: Config option `use_premium` not found, use default `True`
07.06.2016 21:50:18 INFO      HOSTER BasePlugin[2]: Grabbing link info...
07.06.2016 21:50:18 DEBUG     HOSTER BasePlugin[2]: Link info: {'status': 7, 'hash': {}, 'name': 'EVEResources.7z', 'url': u'https://binaries.eveonline.com/EVEResources.7z', 'pattern': {}, 'size': 0}
07.06.2016 21:50:18 DEBUG     HOSTER BasePlugin[2]: Previous link info: {}
07.06.2016 21:50:18 INFO      HOSTER BasePlugin[2]: Link name: EVEResources.7z
07.06.2016 21:50:18 INFO      HOSTER BasePlugin[2]: Link size: N/D
07.06.2016 21:50:18 INFO      HOSTER BasePlugin[2]: Link status: rozpoczynam
07.06.2016 21:50:18 INFO      HOSTER BasePlugin[2]: Processing url: https://binaries.eveonline.com/EVEResources.7z
07.06.2016 21:50:18 DEBUG     HOSTER BasePlugin[2]: DOWNLOAD URL https://binaries.eveonline.com/EVEResources.7z | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
**07.06.2016 21:50:18 DEBUG     HOSTER BasePlugin[2]: Config option `fallback` not found, use default `True`**
07.06.2016 21:50:18 WARNING   Download failed: EVEResources.7z | pobieranie
07.06.2016 21:50:18 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: EVEResources.7z (pid:2)
07.06.2016 21:50:18 INFO      ADDON UnSkipOnFail: No duplicates found
07.06.2016 21:50:18 DEBUG     All downloads processed
07.06.2016 21:50:20 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666

**Comment by GammaC0de** [comment]
@eerozeteen Can you run pyload from the console, retry the download and post the log here?

**Comment by eerozeteen** [comment]
This is weird. All from the first post was pasted from console. there is no any .py error. Just debug. Im using pyload on my Zyxel NAS 310 with 2.7 python.  With old version (about 1,5 years ago) all works ok. When last time i see that "There is a new version of pyload", i update it (via git) and pyload stops download any file. Today i will try download different files from different hosters and i will paste console. (after update i cant download anything...)

**Comment by GammaC0de** [comment]
@eerozeteen Python version should not be a problem, in fact, I'm running pyload with python 2.5

**Comment by eerozeteen** [comment]
i tested on my laptop with arch linux - download starts,  and there wasnt any line about with option fallback as on my nsa... 
I delete whole config and configure pyload again, and nothing helps... 

here is output from console with try after wipe config, and again reinstall pyload (bolded is line which didnt show when i start download on my laptop):

08.06.2016 21:02:39 DEBUG     HOSTER BasePlugin[1]: Plugin version: 0.51
08.06.2016 21:02:39 DEBUG     HOSTER BasePlugin[1]: Plugin status: testing
08.06.2016 21:02:39 WARNING   HOSTER BasePlugin[1]: Plugin may be unstable
08.06.2016 21:02:39 DEBUG     HOSTER BasePlugin[1]: Config option `use_premium` not found, use default `True`
08.06.2016 21:02:39 INFO      HOSTER BasePlugin[1]: Grabbing link info...
08.06.2016 21:02:39 DEBUG     HOSTER BasePlugin[1]: Link info: {'status': 7, 'hash': {}, 'name': 'ubuntu-16.04-server-s390x.iso', 'url': u'http://nl.archive.ubuntu.com/ubuntu-cdimages/16.04/release/ubuntu-16.04-server-s390x.iso', 'pattern': {}, 'size': 0}
08.06.2016 21:02:39 DEBUG     HOSTER BasePlugin[1]: Previous link info: {}
08.06.2016 21:02:39 INFO      HOSTER BasePlugin[1]: Link name: ubuntu-16.04-server-s390x.iso
08.06.2016 21:02:39 INFO      HOSTER BasePlugin[1]: Link size: N/D
08.06.2016 21:02:39 INFO      HOSTER BasePlugin[1]: Link status: rozpoczynam
08.06.2016 21:02:39 INFO      HOSTER BasePlugin[1]: Processing url: http://nl.archive.ubuntu.com/ubuntu-cdimages/16.04/release/ubuntu-16.04-server-s390x.iso
08.06.2016 21:02:39 DEBUG     HOSTER BasePlugin[1]: DOWNLOAD URL http://nl.archive.ubuntu.com/ubuntu-cdimages/16.04/release/ubuntu-16.04-server-s390x.iso | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
**08.06.2016 21:02:39 DEBUG     HOSTER BasePlugin[1]: Config option `fallback` not found, use default `True`**
08.06.2016 21:02:39 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
08.06.2016 21:02:39 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
08.06.2016 21:02:39 WARNING   Download failed: ubuntu-16.04-server-s390x.iso | pobieranie
08.06.2016 21:02:39 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
08.06.2016 21:02:39 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: ubuntu-16.04-server-s390x.iso (pid:1)
08.06.2016 21:02:39 INFO      ADDON UnSkipOnFail: No duplicates found
08.06.2016 21:02:39 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
08.06.2016 21:02:39 DEBUG     All downloads processed

**Comment by GammaC0de** [comment]
Maybe try updating your pycurl package

**Comment by eerozeteen** [comment]
I update whole system packages (python, pycurl, curl, and some others...)

unfortunately still this same...

**Comment by GammaC0de** [comment]
Are you able to download from your NAS with wget? 
Does pyload able to download from other hosters?

**Comment by eerozeteen** [comment]
wget works:

root@nsa310:~# wget http://releases.ubuntu.com/16.04/ubuntu-16.04-desktop-amd64.iso                                      
--20:47:31--  http://releases.ubuntu.com/16.04/ubuntu-16.04-desktop-amd64.iso
           => `ubuntu-16.04-desktop-amd64.iso'
Resolving releases.ubuntu.com... 91.189.92.151
Connecting to releases.ubuntu.com[91.189.92.151]:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://d3f216qdpm0le3.cloudfront.net/ubuntu-16.04-desktop-amd64.iso [following]
--20:47:31--  http://d3f216qdpm0le3.cloudfront.net/ubuntu-16.04-desktop-amd64.iso
           => `ubuntu-16.04-desktop-amd64.iso'
Resolving d3f216qdpm0le3.cloudfront.net... 54.230.228.107, 54.230.228.95, 54.230.228.111, ...
Connecting to d3f216qdpm0le3.cloudfront.net[54.230.228.107]:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1,485,881,344 [application/x-iso9660-image]

 1% [>                                                                                                                                                      ] 19,062,315     3.50M/s    ETA 06:41^Z
[1]+  Stopped(SIGTSTP)        wget http://releases.ubuntu.com/16.04/ubuntu-16.04-desktop-amd64.iso
root@nsa310:~# 

Here is console log of trying download file from 4 hosters: catshare, turbobit, rapidu, filesharkpl. noone starts :( if you think that those hosters not working 100% right, tell me which one  work is 100%  so i will try download from it.

Log: https://gist.github.com/eerozeteen/5992835798a6a271fc4baf0ca241b31c

**Comment by eerozeteen** [comment]
I found cause of the problem. I dont know why and when my system change owner and permissions of my download folder... after fix it, downloads start.

I know, that was stupid.... thanks for help Gamma!.

**Comment by GammaC0de** [comment]
:+1:
