### ISSUE TITLE
FileFactory Login doesn't work

### ISSUE THREAD

**Issue by flamescythe** [pyload/pyload#2498]
Premium login for FileFactoryCom does not seem to work.
I'm using Version 0.21 of the plugin, the current version available on git.

> INFO	ACCOUNT FilefactoryCom: Adding user `***`...
INFO	ACCOUNT FilefactoryCom: Login user `***`...
ERROR	ACCOUNT FilefactoryCom: Could not login user `***` | Login handshake has failed

**Comment by GammaC0de** [comment]
Please send account information to nitzo2001 \[AT\] yahoo \[DOT\] com
