### ISSUE TITLE
EasybytezComFolder double

### ISSUE THREAD

**Issue by erse80** [pyload/pyload#2499]
plugin EasybytezComFolder not work properly

For example test this link 

http://www.easybytez.com/users/13921/194201/

EasybytezComFolder generate 18 file to download, folder contain 10 file it's generate download link 2 times

LOG:

09.06.2016 21:24:05 INFO      Added package test containing 1 links
09.06.2016 21:24:06 INFO      Decrypting starts: http://www.easybytez.com/users/13921/194201/
09.06.2016 21:24:06 WARNING   CRYPTER EasybytezComFolder[3942]: Plugin may be unstable
09.06.2016 21:24:06 INFO      ACCOUNT EasybytezCom: Grabbing account info for user `XXXXX`...
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: Grabbing link info...
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: Link name: Acr0n1s3 B4ckup
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: Link size: N/D
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: Link status: online
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: Processing url: http://www.easybytez.com/users/13921/194201/
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: Looking for direct link...
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: Direct link not found
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: Checking for link errors...
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: No errors found
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: Decrypting as premium link...
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: Create package: jueb8r3kr | 2 links
09.06.2016 21:24:07 INFO      Added package jueb8r3kr containing 2 links
09.06.2016 21:24:07 INFO      CRYPTER EasybytezComFolder[3942]: Save package `jueb8r3kr` to folder: jueb8r3kr
09.06.2016 21:24:08 INFO      CRYPTER EasybytezComFolder[3942]: Create package: easybytez.com | 18 links
09.06.2016 21:24:08 INFO      Added package easybytez.com containing 18 links
09.06.2016 21:24:08 INFO      CRYPTER EasybytezComFolder[3942]: Save package `easybytez.com` to folder: easybytez.com
09.06.2016 21:24:09 INFO      Download starts: http://www.easybytez.com/cd8jueb8r3kr
09.06.2016 21:24:09 WARNING   HOSTER EasybytezCom[3943]: Plugin may be unstable

**Comment by GammaC0de** [comment]
Guest access not possible!
