### ISSUE TITLE
Uploaded

### ISSUE THREAD

**Issue by artdog** [pyload/pyload#2503]
Apologies if this is not the proper place to post this. I have not been able to find any forum since pyload.org went dark.

As nitroflare has turned out to be a waste I was thinking of trying uploaded. Is anyone using this service successfully with pyload?

**Comment by jedipimpmasterflex** [comment]
I'm using the latest (stable) pyload with uploaded without any problems.

**Comment by artdog** [comment]
Thanks

**Comment by GammaC0de** [comment]
@artdog As far as I know, UploadedTo works fine with premium too and it does not have captcha at the loging so its a big plus.

**Comment by artdog** [comment]
Thank you everyone.
