### ISSUE TITLE
AlldebridCom not working

### ISSUE THREAD

**Issue by xander409** [pyload/pyload#2504]
Hi,

i'm using last stable version. i have an Alldebrid premium account, but, for each download it seems that pyload doesn not care about that. RapidgatorCom/UploadedTo says "processing as free download".

anyone can help?

**Comment by GammaC0de** [comment]
Solution will be available only when v0.5 comes out.
Same issue as #2121, get updated there.

**Comment by xander409** [comment]
ok thank u
