### ISSUE TITLE
[UptoboxCom] Premium not working - TEXTAREA F1 not found

### ISSUE THREAD

**Issue by youlJunior** [pyload/pyload#2506]
Suddenly, premium stopped working with UpToBox, there was an error "TEXTAREA F1 not found", and all links downloaded as free...

I managed to see that is a change from UpToBox in link pattern.

Previously, the links were like that : 

> http://www**[N]**.uptobox.com:8080/d/**[RANDOM TEXT]**/**[FILE NAME]**

So the pattern was : 
```python
LINK_PATTERN = r'"(https?://\w+\.uptobox\.com/d/.*?)"'
```
But now the links are like that : 

> http://obwp**[N]**.uptobox.com/**[RANDOM TEXT]**/**[FILE NAME]**

So the pattern has to be changed.

I changed the pattern in UptoboxCom.py that way, and now Premium works again : 
```python
LINK_PATTERN` = r'"(https?://obwp.\.uptobox\.com/.*?)"'
```

**Comment by youlJunior** [comment]
mmmmmm, seems like uptobox reverted their links, new pattern doesn't work, old one works...

**Comment by GammaC0de** [comment]
@youlJunior so does it work, can we close this?

**Comment by youlJunior** [comment]
@GammaC0de
I have to check more, last night i launched 2 links, and one downloaded as premium, the other had the error.

I will launch few dls in same time with tve browser, at different times of the day, and I'll see which patterns I get.

**Comment by GammaC0de** [comment]
:+1:

**Comment by youlJunior** [comment]
I tried many times, and I got randomly the two patterns.
Maybe they added new download servers, and they used new urls for those new servers.

So I ended with a regex like that : 

```python
LINK_PATTERN = r'"(https?://(?:obwp.\.uptobox\.com|\w+\.uptobox\.com/d)/.*?)"'
```
