### ISSUE TITLE
Uploadable.ch renamed as bigfile.to

### ISSUE THREAD

**Issue by raidenii** [pyload/pyload#2507]
Seems nobody has raised this issue... I believe in February uploadable.ch has renamed itself to bigfile.to, and as a result, pyload cannot download the new links correctly (trying to use base plugin to download).

I haven't tried, but will simply renaming uploadable.ch in the plugins into bigfile.to work? I don't think there are many changes on the hoster side, although I didn't check in detail.

**Comment by OzzieIsaacs** [comment]
I created a pull request #2509 with a working version of the plugin
