### ISSUE TITLE
[Hoster] BitshareCom broken

### ISSUE THREAD

**Issue by jdoe0** [pyload/pyload#2510]
All BitShare links are failing with the following error:
`Download failed: file.ext | no such group`

**Comment by GammaC0de** [comment]
Sample URL please
‬

**Comment by jdoe0** [comment]
http://bitshare.com/files/m4q2z6x2/iscan-data_1.32.0-1_all.deb.html

**Comment by GammaC0de** [comment]
I think this hoster is dead:
have you succeeded downloading anything with a web browser? I did not
Tried registering, can't find how..

**Comment by jdoe0** [comment]
I can't actually download the file either. I get redirected to the homepage after clicking the download link. I thought the problem was due to my browser config, but perhaps the hoster really is dead,
