### ISSUE TITLE
ClickNLoad Links always in collector

### ISSUE THREAD

**Issue by Shuralon** [pyload/pyload#2516]
CnL Links are always added to the collector, so the settings don't take effect if you pick queue.

**Comment by GammaC0de** [comment]
Go to plugin setting, find ClickNLoad and change it.

**Comment by Shuralon** [comment]
Thats what i did and it's not working, i picked queue and new links are still added to collector and yes i saved the settings.

**Comment by GammaC0de** [comment]
Stop pyload, look inside plugin.conf file, at the ClickNLoad section the should be a line:
`queue;collector dest : "Add packages to" = collector `

**Comment by Shuralon** [comment]
> ClickNLoad - "ClickNLoad":
        queue;collector dest : "Add packages to" = queue
        bool activated : "Activated" = True
        bool extern : "Listen for external connections" = True
        int port : "Port" = 9666
Like i said it saves everything

**Comment by GammaC0de** [comment]
queue;collector dest : "Add packages to" = **collector**

**Comment by Shuralon** [comment]
Yes, but it didn't worked for me on my old system too btw.

**Comment by GammaC0de** [comment]
Please read #2000

**Comment by GammaC0de** [comment]
On Thursday, June 23, 2016 7:55 PM, Shuralon <notifications@github.com> wrote:
 

 Yes, but it didn't worked for me on my old system too btw.—

**Comment by Shuralon** [comment]
Updated my UpdateManager, but still the same.

**Comment by GammaC0de** [comment]
Debug log please

**Comment by Shuralon** [comment]
`24.06.2016 16:02:00	INFO	Activating Accounts...
298	24.06.2016 16:02:00	INFO	ACCOUNT UploadedTo: Adding user `ID`...
299	24.06.2016 16:02:00	DEBUG	ACCOUNT UploadedTo: Reached login timeout for user `ID`
300	24.06.2016 16:02:00	INFO	ACCOUNT UploadedTo: Login user `ID`...
301	24.06.2016 16:02:00	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
302	24.06.2016 16:02:00	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/io/login | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'id': 'ID', 'pw': '**********'} | ref=True | just_header=False
303	24.06.2016 16:02:00	INFO	ACCOUNT UploadedTo: Grabbing account info for user `ID`...
304	24.06.2016 16:02:00	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
305	24.06.2016 16:02:01	DEBUG	ACCOUNT UploadedTo: Size: xxx | Unit: gb
306	24.06.2016 16:02:01	DEBUG	ACCOUNT UploadedTo: Account info for user `ID`: {'login': {'timestamp':xxx, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 513361838, 'maxtraffic': None, 'validuntil': None, 'login': 'ID', 'type': 'UploadedTo', 'options': {'limitdl': ['0']}}}
307	24.06.2016 16:02:01	INFO	ACCOUNT UploadedTo: Grabbing account info for user `ID`...
308	24.06.2016 16:02:01	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
309	24.06.2016 16:02:01	DEBUG	ACCOUNT UploadedTo: Size: xxx | Unit: gb
310	24.06.2016 16:02:01	DEBUG	ACCOUNT UploadedTo: Account info for user `ID`: {'login': {'timestamp': xxx, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 513361838, 'maxtraffic': None, 'validuntil': None, 'login': 'ID', 'type': 'UploadedTo', 'options': {'limitdl': ['0']}}}
311	24.06.2016 16:02:01	INFO	Activating Plugins...
312	24.06.2016 16:02:01	DEBUG	ADDON ExternalScripts: No script found under folder `pyload_start`
313	24.06.2016 16:02:01	DEBUG	ADDON ExtractArchive: Found UnRar 5.21 | Found UnZip 2.7.9 | Found UnTar 2.7.9
314	24.06.2016 16:02:01	INFO	ADDON XFileSharing: Auto-discover new hosters
315	24.06.2016 16:02:01	DEBUG	ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|cramit\.in|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uplea\.com|uptobox\.com|vidplay\.net))(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
316	24.06.2016 16:02:01	DEBUG	Redirected import module.plugins.crypter.RelinkUs -> userplugins.crypter.RelinkUs
317	24.06.2016 16:02:01	INFO	ADDON XFileSharing: Auto-discover new crypters
318	24.06.2016 16:02:01	DEBUG	ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
319	24.06.2016 16:02:01	INFO	pyLoad is up and running
320	24.06.2016 16:02:07	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
321	24.06.2016 16:03:48	DEBUG	ADDON ClickNLoad: Connection from 192.168.178.29:49895
322	24.06.2016 16:03:50	INFO	Added package http://relink.to/view.php?id=xxx containing 22 links
323	24.06.2016 16:14:07	ERROR	Error importing UpdateManager: No module named Hook`

I don't know why i get an error with UpdateManager, worked fine yesterday.

**Comment by GammaC0de** [comment]
@Shuralon It seems that your pyload installation os broker, please use the instruction in #2241 to synchronize your plugins

**Comment by Shuralon** [comment]
Ok i fixed that, but ClickNLoad still adds Links always to collector. Log is the same just the Error line missing.

**Comment by vimtut0r** [comment]
The problem is `cnl_app.py` is not loading the config.
Here is my workaround:
In file `/module/web/cnl_app.py`
In this function `def addcrypted2():` (for example, depends on your needs)
Change this:
`PYLOAD.addPackage(package, result, 0)`
To this:
`PYLOAD.addPackage(package, result, 0)`

Now restart pyLoad.

I should mention that this is only a dirty workaround. Usually the queue destination should be read from config.

**Comment by lordfiSh** [comment]
Test Link: http://filecrypt.cc/Container/9B82B8ECA1.html

ClickNLoad works for me if you enable `"Add packages to" = collector` if you set it to `Queue` the following happens: 

```python
01.10.2016 09:58:13 INFO      ADDON UpdateManager: All plugins are up to date!
01.10.2016 09:58:18 INFO      ADDON ClickNLoad: Proxy listening on 127.0.0.1:9666
01.10.2016 09:58:24 DEBUG     ADDON ClickNLoad: Connection from 127.0.0.1:33364
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/pyload/module/plugins/hooks/ClickNLoad.py", line 79, in forward
    old_ids = set(pack.id for pack in self.pyload.api.getCollector())
  File "/opt/pyload/module/plugins/hooks/ClickNLoad.py", line 79, in <genexpr>
    old_ids = set(pack.id for pack in self.pyload.api.getCollector())
AttributeError: 'PackageData' object has no attribute 'id'

^C01.10.2016 10:00:14 INFO      shutting down...
```

Settings it back to `collector` 
```python
01.10.2016 10:00:19 INFO      ADDON UpdateManager: All plugins are up to date!
01.10.2016 10:00:24 INFO      ADDON ClickNLoad: Proxy listening on 127.0.0.1:9666
01.10.2016 10:00:37 DEBUG     ADDON ClickNLoad: Connection from 127.0.0.1:33440
01.10.2016 10:00:38 DEBUG     ADDON ClickNLoad: Connection from 127.0.0.1:33444
01.10.2016 10:00:38 DEBUG     ADDON ClickNLoad: Connection from 127.0.0.1:33448
01.10.2016 10:00:38 DEBUG     ADDON ClickNLoad: Connection from 127.0.0.1:33450
01.10.2016 10:00:38 DEBUG     ADDON ClickNLoad: Connection from 127.0.0.1:33454
01.10.2016 10:00:39 INFO      Added package filecrypt.cc containing 1 links
```
move it via webgui to `Queue` 
```python
01.10.2016 10:00:52 DEBUG     ADDON ExternalScripts: No script found under folder `package_deleted`
01.10.2016 10:00:56 INFO      Download starts: https://github.com/pyload/pyload/archive/stable.zip
01.10.2016 10:00:56 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
01.10.2016 10:00:56 DEBUG     HOSTER BasePlugin[240]: Plugin version: 0.51
01.10.2016 10:00:56 DEBUG     HOSTER BasePlugin[240]: Plugin status: testing
01.10.2016 10:00:56 WARNING   HOSTER BasePlugin[240]: Plugin may be unstable
01.10.2016 10:00:56 DEBUG     HOSTER BasePlugin[240]: Config option `use_premium` not found, use default `True`
01.10.2016 10:00:56 INFO      HOSTER BasePlugin[240]: Grabbing link info...
01.10.2016 10:00:56 DEBUG     HOSTER BasePlugin[240]: Link info: {'status': 7, 'hash': {}, 'name': 'stable.zip', 'url': u'https://github.com/pyload/pyload/archive/stable.zip', 'pattern': {}, 'size': 0}
01.10.2016 10:00:56 DEBUG     HOSTER BasePlugin[240]: Previous link info: {}
01.10.2016 10:00:56 INFO      HOSTER BasePlugin[240]: Link name: stable.zip
01.10.2016 10:00:56 INFO      HOSTER BasePlugin[240]: Link size: N/D
01.10.2016 10:00:56 INFO      HOSTER BasePlugin[240]: Link status: starting
01.10.2016 10:00:56 INFO      HOSTER BasePlugin[240]: Processing url: https://github.com/pyload/pyload/archive/stable.zip
01.10.2016 10:00:56 DEBUG     HOSTER BasePlugin[240]: DOWNLOAD URL https://github.com/pyload/pyload/archive/stable.zip | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
01.10.2016 10:00:58 DEBUG     Content-Disposition: pyload-stable.zip
```
