### ISSUE TITLE
UpdateManager: When does it update ExtractArchive.py?

### ISSUE THREAD

**Issue by Jonn3y** [pyload/pyload#2518]
Heyho, 

Pyload works now like a charme, but:
I saw the ExtractArchive.py was updatet to Version 1.58 78e1af94a999dc007f80749cf550654c8f625a23
On my server 1.57 is installed.

Why does it not update? There are no errors in the logs and everything works fine. It's just a question :)

**Comment by GammaC0de** [comment]
See #2469 and #2241

**Comment by Jonn3y** [comment]
Updated the UpdateManager to 1.14 manually weeks ago. And today it removed some stuff like:
```
/opt/pyload/module/plugins/accounts/BitshareCom.py
/opt/pyload/module/plugins/accounts/BitshareCom.pyc
/opt/pyload/module/plugins/crypter/UploadableChFolder.py
/opt/pyload/module/plugins/crypter/UploadableChFolder.pyc
/opt/pyload/module/plugins/hoster/UploadableCh.py
/opt/pyload/module/plugins/hoster/UploadableCh.pyc
``` 
So it looks like it works.. 

```
731	24.06.2016 15:25:32	INFO	pyLoad is up and running
732	24.06.2016 15:25:32	INFO	ADDON UpdateManager: pyLoad is up to date!
733	24.06.2016 15:25:33	ERROR	ADDON UpdateManager: Error updating plugin: CAPTCHA UlozTo | Bad version number on the server
734	24.06.2016 15:25:33	INFO	ADDON UpdateManager: All plugins are up to date!
```

```bash
root@microserver: [/opt/pyload/module/plugins/hooks]: Fr Jun 24 > 15:27:26 :
 >>> # ll
[...]
-rw-r--r-- 1 pyload pyload 12676 Jun  4 16:14 UpdateManager.py
-rw-r--r-- 1 pyload pyload 10645 Jun 24 07:30 UpdateManager.pyc
```

**Comment by Velociraptor85** [comment]
@Jonn3y hi :) try to stop pyload delete the UpdateMangaer.pyc and restart it again ... maybe it will help because for me it looks strange that the have different dates in your list

**Comment by Jonn3y** [comment]
I just reinstalled pyload :D now everything works perfectly.
