### ISSUE TITLE
EasybytezCom: cannot import name parseHtmlForm

### ISSUE THREAD

**Issue by underLgN** [pyload/pyload#2521]
Good evening.
After resetting pyload, lost the EasybytezCom account.
In manually put in  pyLoad \ pyload \ module \ plugins \ accounts and  pyload \ module \ plugins \ hoster but when I'm going to give the prenium  account sent error occured.

**Comment by GammaC0de** [comment]
See #2000 for how to do a fresh install

**Comment by GammaC0de** [comment]
Can this be closed?
