### ISSUE TITLE
'ascii' codec can't decode byte 0xc3 in position 41

### ISSUE THREAD

**Issue by Gravefield-l** [pyload/pyload#2525]
In order to fix the "[falsely reporting a new version of pyload](https://github.com/pyload/pyload/issues/2469)" I replace the file UpdateManager.py by this [one](https://github.com/pyload/pyload/raw/d2498ffa4c58a2180a9d84e644ee9eeaa95fd1ba/module/plugins/hooks/UpdateManager.py) . But Now I ve this encode error when I try to download something "'ascii' codec can't decode byte 0xc3 in position 41: ordinal not in range(128) ". What can I do?

**Comment by GammaC0de** [comment]
There is a bug related to unicode file names, its not related to UpdateManager
https://github.com/pyload/pyload/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%27ascii%27%20codec%20can%27t

Try downloading a file with only English name in it and see if it works

**Comment by Gravefield-l** [comment]
Ok, so you say it's a problem with unicode, so I try something, just edit the name of the "package" and remove the "è" in the title of package, then I restart it, then pyload can download without problem.

You can see here what I'm talking about : [http://i.imgur.com/PvrD2iQ.png](http://i.imgur.com/PvrD2iQ.png)

 So no accent like "é" "à" "è" or smething else or you have a problem with unicode. Good to know.

Thanks for the idea and to help me, it was really fast !

**Comment by GammaC0de** [comment]
:+1:
