### ISSUE TITLE
debriditaliaCom with uploaded not work

### ISSUE THREAD

**Issue by bye08** [pyload/pyload#2526]
Hello, the Debriditalia Plugin dont work for download at uploaded.to

can anyone help?

**Comment by GammaC0de** [comment]
Does it work at all? (#2121)

**Comment by bye08** [comment]
What do you mean?

**Comment by GammaC0de** [comment]
I mean does it work with hosters other than uploaded.to?

**Comment by bye08** [comment]
i don´t know i load everytime from uploded.
I can give my account for test the Plugin if need
Sorry for my Bad English

**Comment by GammaC0de** [comment]
There is no need because as far as I know MultiAccount plugin (as Debriditalia is) support is broken currently, it should be fixed only in the upcoming v0.5 (see #2121)
