### ISSUE TITLE
uloz.to links not downloading

### ISSUE THREAD

**Issue by mrkalo** [pyload/pyload#2527]
Hello,
I am not able to download links from uloz.to, it looks like only BasePlugin is activated and only HTML page is downloaded. It worked perfectly fine about a week ago.

How to solve this, please?

Thanks

> 602 29.06.2016 12:31:39	INFO	Added package test containing 1 links
603	29.06.2016 12:31:40	INFO	Download starts: https://uloz.to/!71pgGzPfL/test-txt
604	29.06.2016 12:31:40	WARNING	HOSTER BasePlugin[6]: Plugin may be unstable
605	29.06.2016 12:31:40	INFO	HOSTER BasePlugin[6]: Grabbing link info...
606	29.06.2016 12:31:40	INFO	HOSTER BasePlugin[6]: Link name: test-txt
607	29.06.2016 12:31:40	INFO	HOSTER BasePlugin[6]: Link size: N/D
608	29.06.2016 12:31:40	INFO	HOSTER BasePlugin[6]: Link status: starting
609	29.06.2016 12:31:40	INFO	HOSTER BasePlugin[6]: Processing url: https://uloz.to/!71pgGzPfL/test-txt
610	29.06.2016 12:31:41	INFO	HOSTER BasePlugin[6]: File saved
611	29.06.2016 12:31:41	INFO	HOSTER BasePlugin[6]: Checking download...
612	29.06.2016 12:31:41	INFO	HOSTER BasePlugin[6]: File is OK
613	29.06.2016 12:31:41	INFO	Download finished: test-txt
614	29.06.2016 12:31:41	INFO	Package finished: test
615	29.06.2016 12:31:41	ERROR	ADDON ExtractArchive: (2, 'No such file or directory')
616	29.06.2016 12:31:41	INFO	ADDON ExtractArchive: Check package: test
617	29.06.2016 12:31:41	INFO	ADDON ExtractArchive: No files found to extract

**Comment by mrkalo** [comment]
Great, Thank you :-)

**Comment by GammaC0de** [comment]
:+1:
