### ISSUE TITLE
Decrypter overwrites packagename

### ISSUE THREAD

**Issue by EikeKre** [pyload/pyload#2528]
Hello,
after adding a crypter link like https://www.filecrypt.cc/Container/test.html with a custom packagename and optionally a password the decrypter overwrites my selfdefined packagename with its own.
The same behavior with dlc packages and other crypters.

Until now my workaround is to overwrite the packagename after decryption. As I am an engineer and as such new to pyload I need a hint which module handles the renaming so that I can solve this by myself and add a pull request.

Regards

**Comment by vuolter** [comment]
@EikeKre https://github.com/pyload/pyload/blob/stable/module/plugins/crypter/FilecryptCc.py extending https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Crypter.py (already fixed in next release).

**Comment by EikeKre** [comment]
Ah okay.
Thank you for the answer.
