### ISSUE TITLE
How should one install current version?

### ISSUE THREAD

**Issue by knezi** [pyload/pyload#2529]
Hi,
I wonder how to install current version. There are in road map many versions. There's also written that since 0.5.0 pyload will update automatically. There is latest pyload 0.4.9 in releases though. If I download this, I see at the bottom of the webclient 2008-2011. I also got the message that my pyload is outdated.
Could anyone explain me whether there is a newer version (in roadmap seems all future versions incomplete) and if so, how should one install it?
Thanks,
knezi

**Comment by GammaC0de** [comment]
v0.4.9 is the current version, see #2000 for installation instructions .

Currently v0.5 is being written and will be release hopefully soon.

**Comment by knezi** [comment]
Is it possible to run some unstable version? Or are the downloaders updated anyway (I mean the changes in downloading websites)?
