### ISSUE TITLE
Can't install: Port py26-crypto not found

### ISSUE THREAD

**Issue by c9rbjn** [pyload/pyload#2530]
Hey guys,
If I want to install the dependencies with the suggested command „sudo port install py26-curl py26-crypto py26-openssl py26-pil spidermonkey py26-pyqt4 tesseract" I get:
> Port py26-crypto not found

I'm running Python on a Mac with OS EL Capitan.

What's wrong?

**Comment by EikeKre** [comment]
sudo easy_install py26-crypto

**Comment by GammaC0de** [comment]
So have you managed to run pyload? can we close this?

**Comment by c9rbjn** [comment]
When I type that pycurl line I get

`Searching for pycurl
Reading https://pypi.python.org/simple/pycurl/
Best match: pycurl 7.43.0
Downloading https://pypi.python.org/packages/12/3f/557356b60d8e59a1cce62ffc07ecc03e4f8a202c86adae34d895826281fb/pycurl-7.43.0.tar.gz#md5=c94bdba01da6004fa38325e9bd6b9760
Processing pycurl-7.43.0.tar.gz
Writing /tmp/easy_install-7Bzybe/pycurl-7.43.0/setup.cfg
Running pycurl-7.43.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7Bzybe/pycurl-7.43.0/egg-dist-tmp-I1GYj6
Using curl-config (libcurl 7.49.1)
warning: no files found matching 'src/Makefile'
In file included from src/docstrings.c:4:
In file included from src/pycurl.h:32:
In file included from /opt/local/include/curl/curl.h:35:
/opt/local/include/curl/curlrules.h:143:6: error: '__curl_rule_01__' declared as
      an array with a negative size
    [CurlchkszEQ(long, CURL_SIZEOF_LONG)];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/curl/curlrules.h:132:27: note: expanded from macro
      'CurlchkszEQ'
#define CurlchkszEQ(t, s) sizeof(t) == s ? 1 : -1
                          ^~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/curl/curlrules.h:153:6: error: '__curl_rule_02__' declared as
      an array with a negative size
    [CurlchkszEQ(curl_off_t, CURL_SIZEOF_CURL_OFF_T)];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/curl/curlrules.h:132:27: note: expanded from macro
      'CurlchkszEQ'
#define CurlchkszEQ(t, s) sizeof(t) == s ? 1 : -1
                          ^~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
error: Setup script exited with error: command 'cc' failed with exit status 1`

**Comment by GammaC0de** [comment]
http://stackoverflow.com/questions/2279014/pycurl-install-already-have-min-libcurl-version

**Comment by EikeKre** [comment]
@GammaC0de Yes I have

**Comment by GammaC0de** [comment]
What!?

**Comment by c9rbjn** [comment]
Further issues comming up when I start the pyLoad setup. It says that some dependencies would be missing. For example PyQt4 which I actually installed with that command line from @EikeKre  

> brew install PyQt --with-python3
When I type that line again I get "pyqt-4.11.4 already installed" - surprise!

![bildschirmfoto 2016-07-01 um 11 54 32](https://cloud.githubusercontent.com/assets/20223012/16518449/1fc0f3fe-3f83-11e6-8c57-cad83d2e9967.png)

I have installed "py-OpenSSL" via sudo easy_install pyopenssl and tesseract via sudo easy_install tesseract too. Why do I get that "missing error" from the pyLoad setup?

**Comment by GammaC0de** [comment]
Maybe try using py26-pip for installing python packages

**Comment by c9rbjn** [comment]
I've now installed pip ports with "sudo port install"
So I wanted to install missing packages via "sudo pip install <packagename>" but when I want to execute this I get "sudo: pip: command not found"

**Comment by GammaC0de** [comment]
Just a hunch: "sudo py26-pip install"

**Comment by c9rbjn** [comment]
Again: command not found
??

**Comment by GammaC0de** [comment]
"sudo pip-2.6 install"

**Comment by c9rbjn** [comment]
"DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python..."

hmpf...

**Comment by GammaC0de** [comment]
Try using python 2.7:
```
sudo port install python27
sudo port install py27-curl py27-crypto py27-openssl py27-pil spidermonkey py27-pyqt4 tesseract
sudo port install py27-pip install
```

**Comment by c9rbjn** [comment]
It works! At least the install...
So I'm able to start pyLoads GUI and command line interface. But when I add a container or some links to download it doesn't start downloading. Status says "failed" but why?

**Comment by GammaC0de** [comment]
With Python 2.6 or 2.7?

Please read #2000 for further installation instructions.

**Comment by c9rbjn** [comment]
With Python 2.7
Download works after I restarted Pyload.
The only thing which actually doesn't work is automatic extraction of downloaded files.

**Comment by GammaC0de** [comment]
Have you enabled the ExtractArchive plugin?

**Comment by c9rbjn** [comment]
Yes of course.
At the end of each download I get

> INFO      ExtractArchive: No files found to extract
can't send notification

**Comment by GammaC0de** [comment]
Enable debug mode, retry, look in the log.

**Comment by c9rbjn** [comment]
How do I run Pyload in debug mode? 
I guess that some package is missing because the Logfiles are allways incomplete. When I start pyLoadGui.py: "pynotify not installed, falling back to qt tray notification"

**Comment by GammaC0de** [comment]
@c9rbjn Why use pyload GUI and net WebUI in the first place? GUI will not be available in the next release..

to run Pyload in debug mode hust do `python2.7 pyLoadCore.py -d`

**Comment by c9rbjn** [comment]
Because it's easy to add containers with pyLoadGui. Frankly I don't even know how to do it with the command line tool. 

After running in debug mode it seems that only one error occurs: `02.07.2016 00:59:28 ERROR     LinkdecrypterCom: Crypter list not found`
Further: ```
02.07.2016 00:59:27 INFO      ExtractArchive: UnRar ist nicht installiert
02.07.2016 00:59:27 INFO      ExtractArchive: Aktiviert UnZip
```
It says "UnRar is not installed" and "activate UnZip"

**Comment by GammaC0de** [comment]
>It says "UnRar is not installed" and "activate UnZip"

Well, that explains why no extraction happens..

UnRar should be in your path..

**Comment by c9rbjn** [comment]
So I simply install UnRar via Mac Ports? .. sudo port install... ?
And how do I add containers with the command line tool? After debug mode I still get "ERROR     LinkdecrypterCom: Crypter list not found"

**Comment by GammaC0de** [comment]
>I still get "ERROR LinkdecrypterCom: Crypter list not found"

Its just a bug in LinkdecrypterCom plugin, you can just ignore it.

As for UnRar, you can use the official package (http://www.rarlab.com/rar/rarosx-5.4.b2.tar.gz) or the Mac Ports one (sudo port install unrar), just make sure UnRar is in your PATH.

**Comment by c9rbjn** [comment]
Extract works! 
Just tell me at least how I add whole containers with pyLoadCli.py and I'll free you ;)

**Comment by GammaC0de** [comment]
I guess you just add the URL of that container to the download queue.

**Comment by c9rbjn** [comment]
That doesn't work.
"pycurl error 6: Couldn't resolve host 'notfound.php' "

**Comment by GammaC0de** [comment]
URL?

**Comment by c9rbjn** [comment]
That comes up when I add the URL from the container.
I mean that's the reason I used the GUI in the first place. You can simply add your container and everything works.

**Comment by GammaC0de** [comment]
What is the URL of the **container**?

**Comment by c9rbjn** [comment]
It's a relink URL.

**Comment by GammaC0de** [comment]
Example please.

**Comment by c9rbjn** [comment]
http://relink.to/f/76198600acdf5384f1426dae0fcda8

**Comment by GammaC0de** [comment]
What happens when you add the Relink URL to the queue?

**Comment by c9rbjn** [comment]
"02.07.2016 02:25:50 INFO      Download starts: http://relink.to/f/76198600acdf5384f1426dae0fcda8
02.07.2016 02:25:50 ERROR     pycurl error 6: Couldn't resolve host 'container_captcha.php'
02.07.2016 02:25:50 INFO      UnSkipOnFail: look for skipped duplicates for 76198600acdf5384f1426dae0fcda8 (pid:15)..."

**Comment by GammaC0de** [comment]
Have you followed the instructions in #2000?

**Comment by c9rbjn** [comment]
Yes I have and I still get the error:
"02.07.2016 02:50:00 INFO      CAPTCHA RelinkUs[34]: Captcha | Using OCR to decrypt captcha...
02.07.2016 02:50:00 WARNING   CAPTCHA RelinkUs[34]: Captcha | No OCR result
02.07.2016 02:50:00 WARNING   CAPTCHA RelinkUs[34]: Captcha | No Client connected for captcha decrypting
02.07.2016 02:50:00 ERROR     Decrypting failed: view.php?id=4464fb43e604b7a20f55eb4b78fbb5 | No Client connected for captcha decrypting"

**Comment by GammaC0de** [comment]
The download fails because you have not solved the captcha request, open the WebUI ans solve the captcha then it should work.

**Comment by c9rbjn** [comment]
But when you once clear the captcha you can download the container (.dlc). How do you add this with the command line tool?
PS: webUI's not working. Can't connect to although it's running :S

**Comment by GammaC0de** [comment]
The way to go is to add the Relink URL and then solve the Captcha (either manually by going to the WebUI and solving or automatically with a Captcha solving plugin like 9kw) and then pyLoad will automatically handle the DLC for you.

Have you enabled WebUI in pyLoad's setup?
If not, run `python2.7 pyLoadCore.py -s` to repeat the setup process.

**Comment by GammaC0de** [comment]
Another way is to use the `HotFolder` plugin and drop the DLC file in the hot folder.

**Comment by c9rbjn** [comment]
WebUI works fine now! 
At least: How can I install these plugins? How do I setup Hotfolder? Where can I keep track of new plugins? Sorry but bing isn't that helpful in that case.

**Comment by GammaC0de** [comment]
:+1: 
Plugins are auto downloaded/updated by `UpdateManager` plugin - they are just not enabled by default.
To enable / configure plugins, you enter to the WebUI then press the "config" button, click on the "plugins" tab and select the plugin you want to enable / configure. 

![untitled](https://cloud.githubusercontent.com/assets/11036551/16547538/70812e5a-417a-11e6-8505-99ac4bd56e8a.png)

**Comment by c9rbjn** [comment]
I guess that's it. Finally! Thank you for your tireless effort to help me!

**Comment by GammaC0de** [comment]
:+1:
