### ISSUE TITLE
Add support for Debrid-link.fr

### ISSUE THREAD

**Issue by Johan46** [pyload/pyload#2533]
Is it possible to add support of the multihoster Debrid-link ? (i'm not the owner)
Maybe this link could help you : https://debrid-link.fr/api_doc/

Thanks for your work.

**Comment by GammaC0de** [comment]
Currently multihoster support of pyload is broken so there is no point to do so until it is fixed - see #2121

**Comment by Velociraptor85** [comment]
@Johan46 please update and check the issue, this will be closed and can be reopened if needed.

**Comment by Johan46** [comment]
Debrid-link still not available in Pyload

**Comment by GammaC0de** [comment]
Account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by Johan46** [comment]
I'm just a customer I will ask Debrid-link to send it.

**Comment by Johan46** [comment]
Hello thanks for having added Debridlinkfr !
My premium account is well recognized, and I see in the log that Pyload try to use Debridlink, but all of my downloads failed with the error : **Required account not found.**

I can send a log by email if you want.

**Comment by GammaC0de** [comment]
@Johan46 you can attach the log file here, just drag the file into the browser.

**Comment by GammaC0de** [comment]
@Johan46 Any update?
