### ISSUE TITLE
Pyload API problem with login and chekAuth methods

### ISSUE THREAD

**Issue by RaphPi** [pyload/pyload#2535]
Hello !

First of all, thanks a lot for your work on Payload ! 👍 

Actually, i'm playing with the Pyload API in Swift 2.2 language.
Unfortunately, i'm stuck at the beginning with the _login_ method. When i send my request, le response is systematically "_True_" without Session ID.

I understand that the Session ID is necessary in the request (with _"session" : "xxxxxxxx"_ in the JSON HttpBody) in a third party device without cookie gestion.

Here are the request and response informations 

> [Pyload : methodLogin]
> 
> URL Base -> http://IP:Port/api/login
> 
> Request -> ["password": "pass", "username": "user"]
> ---
> 
> [Request]: <NSMutableURLRequest: 0x7ff36a52e3e0> { URL: http://IP:Port/api/login }
> [Response]: <NSHTTPURLResponse: 0x7ff36a4937e0> { URL: http://IP:Port/api/login } { status code: 200, headers {
>     "Cache-Control" = "no-cache, must-revalidate";
>     "Content-Length" = 4;
>     "Content-Type" = "application/json";
>     Date = "Wed, 06 Jul 2016 15:49:29 GMT";
>     Server = "CherryPy/3.1.2 WSGI Server";
> } }
> [Data]: 4 bytes
> [Result]: SUCCESS: true
> 
> Data decode = true
> 
> Result decode = SUCCESS
> 
> JSON decode = true

When i try in a web browser (_http://IP:Port/api/login/"user"/"pass"_ or _http://IP:Port/api/login?username="user"&password="pass"_) it doesn't work until i log in the web interface (403 error : Forbidden). Then, the response is also "_True_".

When i try to use the checkAuth method, i have a 404 error.

I probably make a mistake in my request or in the Pyload configuration.

Thanks for your help.

PS : Sorry for my bad english.

**Comment by tod31** [comment]
@RaphPi try changing the server to threaded in settings > webinterface... I ran into the same problems 2.5 years ag, changing the webserver from bultin to threaded solved the problems.
