### ISSUE TITLE
File Info ShareOnlineBiz

### ISSUE THREAD

**Issue by sti0** [pyload/pyload#2537]
Hi,
I just updated my pyload plugins and everything works fine except the file info detection after adding a  ShareOnlineBiz link to the collector. Before the update I got the file name and size at the collector. Now I only got the link. 

Can you please help me? Thanks in advance.

**Comment by GammaC0de** [comment]
This is because plugins has no `getInfo()`  function anymore...

**Comment by Loader23** [comment]
Any workaround for this?
