### ISSUE TITLE
Template development

### ISSUE THREAD

**Issue by EikeKre** [pyload/pyload#2540]
Hello,

how do I quickly debug html-templates? Is there another way than restarting pyload?

greets

**Comment by GammaC0de** [comment]
I recommend starting pyload from the command line (`python pyLoadCore.py -d`), stopping it with `ctrl-c` when needed and then starting it again.

**Comment by EikeKre** [comment]
Okay. I thought there is also another way. Thanks

**Comment by vuolter** [comment]
The next release allowes web stuff debugging.
