### ISSUE TITLE
ExtractArchive only tries UnRar

### ISSUE THREAD

**Issue by Exormeter** [pyload/pyload#2541]
Hi, 
I think I found a bug in the ExtractArchive, but I'm not sure on this.
Basiclly I was downloading a .zip file and ExtractArchive was trying to extract it using Unrar.
It didn't extract anything but still logged as "Extraction finished"
Here is the log:

13.07.2016 14:40:00	DEBUG	ADDON ExternalScripts: No script found under folder `package_finished`
54	13.07.2016 14:40:00	DEBUG	ADDON ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
55	13.07.2016 14:40:00	INFO	ADDON ExtractArchive: Check package: zip
56	13.07.2016 14:40:01	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
57	13.07.2016 14:40:01	DEBUG	All downloads processed
58	13.07.2016 14:40:01	DEBUG	ADDON ExtractArchive: Targets for UnRar: [(2, '/mnt/usb/Downloads/zip/FB1_ab2016.pdf.zip', '/mnt/usb/Downloads/zip/./')]
59	13.07.2016 14:40:01	INFO	ADDON ExtractArchive: FB1_ab2016.pdf.zip | Extract to: /mnt/usb/Downloads/zip/./
60	13.07.2016 14:40:01	DEBUG	ADDON ExtractArchive: Password: None provided
61	13.07.2016 14:40:01	DEBUG	EXTRACTOR UnRar: EXECUTE unrar l -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v /mnt/usb/Downloads/zip/FB1_ab2016.pdf.zip
62	13.07.2016 14:40:01	DEBUG	ADDON ExtractArchive: Extracting using password: None
63	13.07.2016 14:40:01	DEBUG	EXTRACTOR UnRar: EXECUTE unrar x -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- /mnt/usb/Downloads/zip/FB1_ab2016.pdf.zip /mnt/usb/Downloads/zip/./
64	13.07.2016 14:40:01	DEBUG	EXTRACTOR UnRar: EXECUTE unrar vb -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v /mnt/usb/Downloads/zip/FB1_ab2016.pdf.zip
65	13.07.2016 14:40:01	DEBUG	ADDON ExtractArchive: Would delete: /mnt/usb/Downloads/zip/FB1_ab2016.pdf.zip
66	13.07.2016 14:40:01	INFO	ADDON ExtractArchive: FB1_ab2016.pdf.zip | Extracting finished
67	13.07.2016 14:40:01	DEBUG	EXTRACTOR UnRar: EXECUTE unrar vb -o+ -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v /mnt/usb/Downloads/zip/FB1_ab2016.pdf.zip
68	13.07.2016 14:40:01	DEBUG	ADDON ExtractArchive: Extracted files: []

If I change the list in which the extracting programs are listet from 
("UnRar", "SevenZip", "UnZip", "UnTar") to  ("UnZip", "SevenZip", "UnRar", "UnTar"),  
line in 145 in ExtractArchive.py, the .zip file is extracted normally and without problems. It seems like the script doesn't recognize that UnRar does not support other files than .rar. 
That is at least my conclusion.

**Comment by EikeKre** [comment]
This should fix this: #2545

**Comment by Velociraptor85** [comment]
@Exormeter Did the fix help you? If so please close this issue

**Comment by Velociraptor85** [comment]
closing since no answer and fix should work.
