### ISSUE TITLE
SevenZip as the only extractor a child of UnRar

### ISSUE THREAD

**Issue by EikeKre** [pyload/pyload#2546]
Hello,
just a question no issue:

Why is only SevenZip extended by UnRar and the others (UnTar,UnZip) by the Extractor class?

regards

**Comment by vuolter** [comment]
Depends on the code complexity of the plugin:
Extractor -> Unzip, etc.
Extractor -> UnRar -> Sevenzip
Sevenzip reuses functions declared both in Extractor and UnRar.

**Comment by Velociraptor85** [comment]
@EikeKre Is the question solved for you? May we close this issue?
