### ISSUE TITLE
RelinkUs with SolveMedia

### ISSUE THREAD

**Issue by EikeKre** [pyload/pyload#2548]
Hello folks,

the crypter RelinkUs uses SolveMedia in addition to their CircleCaptcha. I tried to fix this but when using the SolveMedia captcha plugin I get "error: domain / ckey mismatch" as html response from the url "http://api.solvemedia.com/papi/challenge.noscript".

Maybe there is also an issue in the ResolveMedia captcha plugin.

**Comment by GammaC0de** [comment]
Sample URL?

**Comment by EikeKre** [comment]
http://relink.to/view.php?id=bca9f3f179
