### ISSUE TITLE
Download from Google drive

### ISSUE THREAD

**Issue by mayur553** [pyload/pyload#2550]
Hi, 

i am not able to download from google drive. How do i add the link. Shall i add it to the que or collector. I am using web interface for WD NAS

**Comment by vuolter** [comment]
Sample url + debug log please.

**Comment by mayur553** [comment]
URL - https://doc-0o-2g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/cejum3ddh87g02qteavahejob8qq4ag9/1468656000000/12480721209694544128/*/0B-BLFUD0P1HNY1hybWlhUEdobjg?e=download

If the destination is queue i get these logs

INFO	Added package GTA containing 1 links
492	16.07.2016 20:40:45	ERROR	Error importing BasePlugin: No module named Hoster
493	16.07.2016 20:40:46	ERROR	Error importing BasePlugin: No module named Hoster
494	16.07.2016 20:40:46	CRITICAL	'NoneType' object has no attribute 'BasePlugin'

if the destination is collector i get this logs

16.07.2016 20:42:21	INFO	Added package GTA containing 1 links
496	16.07.2016 20:42:22	ERROR	Error importing BasePlugin: No module named Hoster

i have tried downloading from this link through Internet Download Manager and it downloads.

**Comment by vuolter** [comment]
I think you installation is broken. Have a look here: https://github.com/pyload/pyload/issues/2000

**Comment by mayur553** [comment]
It was a tough task to get it installed on my NAS in the first place... there are so many steps... will try again.. do you have tutorial to install for a MybookLive NAS

**Comment by mayur553** [comment]
Carried out the installation again. updated as per #2000 
still getting same error

**Comment by GammaC0de** [comment]
>URL - https://doc-0o-2g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/cejum3ddh87g02qteavahejob8qq4ag9/1468656000000/12480721209694544128/*/0B-BLFUD0P1HNY1hybWlhUEdobjg?e=download

This URL does not work even with a browser...
Also, google drive URLs usually starts with https://drive.google.com or https://docs.google.com

**Comment by mayur553** [comment]
The URL is not working any more as it has expired. 
Try this uRL it will work - https://doc-0k-b0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/sp30bhgosvc9bckcpk2fb8m5fvh7qid9/1468699200000/02400563360866178556/*/0Bw4qb0Pr7JzRd0JncnRTMHJwUjA?e=download

so there is not problem with the link.

**Comment by GammaC0de** [comment]
So far this link works fine, download still not finished though.
Its just a direct download link and so should be handled by `BasePlugin` (which it actually do) and not `GoogledriveCom` plugin.

>16.07.2016 20:40:45 ERROR Error importing BasePlugin: No module named Hoster

This indicates a problem with your installation.

**Comment by mayur553** [comment]
I will try installation again. Will install using this script provided by you in other post.

cd /root

# optware install
wget http://mybookworld.wikidot.com/local--files/optware/setup-mybooklive.sh
sh setup-mybooklive.sh
rm -f ./setup-mybooklive.sh

export PATH=$PATH:/opt/bin:/opt/sbin

grep -q "/opt/bin" /root/.bashrc || echo "export PATH=$PATH:/opt/bin:/opt/sbin" >> /root/.bashrc
grep -q "/opt/bin" /etc/profile || echo "export PATH=$PATH:/opt/bin:/opt/sbin" >> /etc/profile

grep -q "LC_ALL=en_US.UTF-8" /root/.bashrc || echo "export LC_ALL=en_US.UTF-8" >> /root/.bashrc
grep -q "LC_ALL=en_US.UTF-8" /etc/profile || echo "export LC_ALL=en_US.UTF-8" >> /etc/profile

if [ ! -f /etc/init.d/optware.sh ]; then
  wget -P /etc/init.d http://mybookworld.wikidot.com/local--files/optware/optware.sh
  chmod +x /etc/init.d/optware.sh
  mkdir -p /opt/etc/init.d
  mkdir -p /opt/var/run
  update-rc.d optware.sh defaults 90 01
fi
# End of optware install


# pyLoad install
ipkg update
ipkg install python25 py25-crypto py25-curl py25-openssl py25-pil tesseract-ocr tesseract-ocr-lang-eng ossp-js unrar

wget --no-check-certificate https://github.com/pyload/pyload/releases/download/v0.4.9/pyload-v0.4.9-noarch.ipk -O ./pyload-v0.4.9-noarch.ipk
ipkg install ./pyload-v0.4.9-noarch.ipk
rm -f ./pyload-v0.4.9-noarch.ipk
ln -s /opt/share/pyload/pyLoadCore.py /opt/bin/pyLoadCore

wget --no-check-certificate  https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/e67c25e144991612519940a67d8417ea43069a66/UpdateManager.py
mv -f ./UpdateManager.py /opt/share/pyload/module/plugins/hooks/UpdateManager.py

cat <<"EOM" >/opt/etc/init.d/pyload
#!/bin/sh

### BEGIN INIT INFO
# Provides:        pyload
# Required-Start:  $local_fs $remote_fs $network
# Required-Stop:   $local_fs $remote_fs $network
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start pyload download manager daemon
### END INIT INFO

export PATH=$PATH:/opt/bin:/opt/sbin

. /lib/lsb/init-functions

NAME=pyload
DAEMON=/opt/bin/python2.5
PIDFILE=/opt/var/run/pyload.pid
CONFIGDIR=/opt/etc/pyload

test -x $DAEMON || exit 5

case $1 in
    start)
        log_daemon_msg "Starting pyload download manager daemon" "$NAME"
        if [ "`/usr/local/sbin/getServiceStartup.sh $NAME`" == "disabled" ]; then
            log_progress_msg "disabled";
            log_end_msg 0
            exit 0
        fi  
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- /opt/bin/pyLoadCore --pidfile=$PIDFILE --configdir=$CONFIGDIR --daemon > /dev/null 2>&1
        sleep 5
        pidofproc -p $PIDFILE $DAEMON >/dev/null
        status=$?
        log_end_msg $status
        ;;
    stop)
        log_daemon_msg "Stopping pyload download manager daemon" "$NAME"
        $DAEMON /opt/bin/pyLoadCore --pidfile=$PIDFILE --quit > /dev/null 2>&1
        status=$?
        # Wait a little and remove stale PID file
        sleep 1
        if [ -f $PIDFILE ] && ! ps h `cat $PIDFILE` > /dev/null
        then
            # Stale PID file (pyload was succesfully stopped),
            # remove it (should be removed by pyload itself IMHO.)
            rm -f $PIDFILE
        fi
        log_end_msg $status
        ;;
    restart|force-reload)
        $0 stop && sleep 2 && $0 start
        ;;
    try-restart)
        if $0 status >/dev/null; then
            $0 restart
        else
            exit 0
        fi
        ;;
    status)
        pidofproc -p $PIDFILE $DAEMON >/dev/null
        status=$?
        if [ $status -eq 0 ]; then
            log_success_msg "pyload download manager daemon is running"
        else
            log_failure_msg "pyload download manager daemon is not running"
        fi
        exit $status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
        exit 2
        ;;
esac
EOM

chmod +x /opt/etc/init.d/pyload
ln -s /opt/etc/init.d/pyload /opt/etc/init.d/S90pyload

/opt/bin/python2.5 /opt/bin/pyLoadCore --configdir=/opt/etc/pyload -s

reboot


Is there anything apart from this script which is need to be done. Please Help

**Comment by mayur553** [comment]
I did a new installation from the script provided by you in #2328 still getting same error

ERROR	Error importing BasePlugin: No module named Hoster
581	17.07.2016 09:49:36	ERROR	Error importing BasePlugin: No module named Hoster
582	17.07.2016 09:49:36	CRITICAL	'NoneType' object has no attribute 'BasePlugin'

**Comment by GammaC0de** [comment]
Try deleteing your `userplugins` directory and then restart pyload

**Comment by GammaC0de** [comment]
Enter pyload's WebUI, click on the "info" button on the upper right corner.
There you will see "Config Folder" location. there should be a `userplugins` folder.
Delete this folder.

To restart pyload, click on the "Administrate" button then click "Restart pyLoad"

**Comment by mayur553** [comment]
Did what you said. deleted the folder. restarted Pyload but still getting same error.

**Comment by GammaC0de** [comment]
Are you using Optware or Optware-ng?

**Comment by mayur553** [comment]
How do i check that. I think i am using the version download from here

wget http://mybookworld.wikidot.com/local--files/optware/setup-mybooklive.sh

**Comment by GammaC0de** [comment]
start pyload from the console (`python2.5 pyLoadCore.py -d`), retry and post the log here

**Comment by mayur553** [comment]
When you say console... you me to use that command in Putty right

**Comment by GammaC0de** [comment]
Right: `/opt/bin/python2.5 /opt/share/pyload/pyLoadCore.py -d`

**Comment by mayur553** [comment]
The command says pyload already running

MyBookLive:~# /opt/bin/python2.5 /opt/share/pyload/pyLoadCore.py -d
pyLoad already running with pid 5607
MyBookLive:~#

**Comment by GammaC0de** [comment]
To stop running pyload: `/opt/bin/python2.5 /opt/share/pyload/pyLoadCore.py -q`

**Comment by mayur553** [comment]
You want me to first stop pyload from console and then start agaain... and then try loading the link??

**Comment by GammaC0de** [comment]
Yes, then post the log from putty

**Comment by mayur553** [comment]
MyBookLive:~# /opt/bin/python2.5 /opt/share/pyload/pyLoadCore.py -q
No pyLoad running.
MyBookLive:~# /opt/bin/python2.5 /opt/share/pyload/pyLoadCore.py -d
18.07.2016 23:17:37 INFO      Starting pyLoad 0.4.9
18.07.2016 23:17:37 INFO      Using home directory: /opt/share/pyload_config
18.07.2016 23:17:37 DEBUG     Remote activated: False
18.07.2016 23:17:40 DEBUG     created index of plugins
18.07.2016 23:17:40 DEBUG     Redirected import module.plugins.hooks.EventMapper -> userplugins.hooks.EventMapper
18.07.2016 23:17:40 ERROR     Error importing EventMapper: No module named Addon
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/EventMapper.py", line 3, in <module>
    from module.plugins.internal.Addon import Addon
ImportError: No module named Addon
18.07.2016 23:17:40 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
18.07.2016 23:17:40 ERROR     Error importing ExternalScripts: No module named Addon
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/ExternalScripts.py", line 6, in <module>
    from module.plugins.internal.Addon import Addon
ImportError: No module named Addon
18.07.2016 23:17:40 DEBUG     Redirected import module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
18.07.2016 23:17:40 ERROR     Error importing ClickNLoad: No module named Addon
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/ClickNLoad.py", line 12, in <module>
    from module.plugins.internal.Addon import Addon
ImportError: No module named Addon
18.07.2016 23:17:40 DEBUG     Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
18.07.2016 23:17:40 ERROR     Error importing UnSkipOnFail: No module named Addon
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/UnSkipOnFail.py", line 4, in <module>
    from module.plugins.internal.Addon import Addon
ImportError: No module named Addon
18.07.2016 23:17:40 DEBUG     Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
18.07.2016 23:17:40 ERROR     Error importing ExtractArchive: No module named Addon
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/ExtractArchive.py", line 52, in <module>
    from module.plugins.internal.Addon import Addon
ImportError: No module named Addon
18.07.2016 23:17:40 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
18.07.2016 23:17:40 ERROR     Error importing UpdateManager: No module named Addon
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/UpdateManager.py", line 11, in <module>
    from module.plugins.internal.Addon import Addon
ImportError: No module named Addon
18.07.2016 23:17:40 DEBUG     Redirected import module.plugins.hooks.UserAgentSwitcher -> userplugins.hooks.UserAgentSwitcher
18.07.2016 23:17:40 ERROR     Error importing UserAgentSwitcher: No module named Addon
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/UserAgentSwitcher.py", line 5, in <module>
    from module.plugins.internal.Addon import Addon
ImportError: No module named Addon
18.07.2016 23:17:40 INFO      Activated plugins:
18.07.2016 23:17:40 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
18.07.2016 23:17:40 INFO      Downloadtime: True
18.07.2016 23:17:41 INFO      Starting threaded webserver: 10.0.0.10:8000
18.07.2016 23:17:41 INFO      Free space: 1.08 GiB
18.07.2016 23:17:41 INFO      Activating Accounts...
18.07.2016 23:17:41 INFO      Activating Plugins...
18.07.2016 23:17:41 INFO      pyLoad is up and running


Its not going beyond this. I mean i am not getting MyBookLive:~#

**Comment by GammaC0de** [comment]
Addon.py seems to be missing, download it and retry
```
cd /opt/share/pyload_config/userplugins/internal
wget --no-check-certificate https://raw.githubusercontent.com/pyload/pyload/stable/module/plugins/internal/Addon.py -O Addon.py
```

**Comment by mayur553** [comment]
Downloaded. After starting Pyload the log is as follows

MyBookLive:~# /opt/bin/python2.5 /opt/share/pyload/pyLoadCore.py -d
18.07.2016 23:42:28 INFO      Starting pyLoad 0.4.9
18.07.2016 23:42:28 INFO      Using home directory: /opt/share/pyload_config
18.07.2016 23:42:28 DEBUG     Deleting old pidfile pyload.pid
18.07.2016 23:42:28 DEBUG     Remote activated: False
18.07.2016 23:42:31 DEBUG     created index of plugins
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.hooks.EventMapper -> userplugins.hooks.EventMapper
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
18.07.2016 23:42:31 ERROR     Error importing EventMapper: No module named Plugin
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/EventMapper.py", line 3, in <module>
    from module.plugins.internal.Addon import Addon
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/internal/Addon.py", line 5, in <module>
    from module.plugins.internal.Plugin import Plugin
ImportError: No module named Plugin
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
18.07.2016 23:42:31 ERROR     Error importing ExternalScripts: No module named Plugin
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/ExternalScripts.py", line 6, in <module>
    from module.plugins.internal.Addon import Addon
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/internal/Addon.py", line 5, in <module>
    from module.plugins.internal.Plugin import Plugin
ImportError: No module named Plugin
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
18.07.2016 23:42:31 ERROR     Error importing ClickNLoad: No module named Plugin
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/ClickNLoad.py", line 12, in <module>
    from module.plugins.internal.Addon import Addon
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/internal/Addon.py", line 5, in <module>
    from module.plugins.internal.Plugin import Plugin
ImportError: No module named Plugin
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
18.07.2016 23:42:31 ERROR     Error importing UnSkipOnFail: No module named Plugin
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/UnSkipOnFail.py", line 4, in <module>
    from module.plugins.internal.Addon import Addon
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/internal/Addon.py", line 5, in <module>
    from module.plugins.internal.Plugin import Plugin
ImportError: No module named Plugin
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
18.07.2016 23:42:31 ERROR     Error importing ExtractArchive: No module named Plugin
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/ExtractArchive.py", line 52, in <module>
    from module.plugins.internal.Addon import Addon
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/internal/Addon.py", line 5, in <module>
    from module.plugins.internal.Plugin import Plugin
ImportError: No module named Plugin
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
18.07.2016 23:42:31 ERROR     Error importing UpdateManager: No module named Plugin
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/UpdateManager.py", line 11, in <module>
    from module.plugins.internal.Addon import Addon
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/internal/Addon.py", line 5, in <module>
    from module.plugins.internal.Plugin import Plugin
ImportError: No module named Plugin
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.hooks.UserAgentSwitcher -> userplugins.hooks.UserAgentSwitcher
18.07.2016 23:42:31 DEBUG     Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
18.07.2016 23:42:31 ERROR     Error importing UserAgentSwitcher: No module named Plugin
Traceback (most recent call last):
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/hooks/UserAgentSwitcher.py", line 5, in <module>
    from module.plugins.internal.Addon import Addon
  File "/opt/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/share/pyload_config/userplugins/internal/Addon.py", line 5, in <module>
    from module.plugins.internal.Plugin import Plugin
ImportError: No module named Plugin
18.07.2016 23:42:31 INFO      Activated plugins:
18.07.2016 23:42:31 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
18.07.2016 23:42:31 INFO      Downloadtime: True
18.07.2016 23:42:31 INFO      Free space: 1.08 GiB
18.07.2016 23:42:31 INFO      Activating Accounts...
18.07.2016 23:42:31 INFO      Activating Plugins...
18.07.2016 23:42:31 INFO      pyLoad is up and running
18.07.2016 23:42:33 INFO      Starting threaded webserver: 10.0.0.10:8000

**Comment by GammaC0de** [comment]
There was a problem with the script in https://github.com/pyload/pyload/issues/2328#issuecomment-180789444.
I've corrected the script and now it should work.
uninstall pyload and then istall it using the script above.

**Comment by mayur553** [comment]
Its recognizing the link now but i am getting following error

INFO	Added package GTA containing 1 links
554	19.07.2016 10:44:42	INFO	Download starts: https://doc-0k-b0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/cesi1d4pl4mj0mdcktm63uss332rm3tm/1468900800000/02400563360866178556/*/0Bw4qb0Pr7JzRd0JncnRTMHJwUjA?e=download
555	19.07.2016 10:44:44	WARNING	Download failed: https://doc-0k-b0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/cesi1d4pl4mj0mdcktm63uss332rm3tm/1468900800000/02400563360866178556/*/0Bw4qb0Pr7JzRd0JncnRTMHJwUjA?e=download | Bad server response: 503 Service Unavailable

**Comment by GammaC0de** [comment]
Why are you trying to download from the temporary link?
You should paste the google drive URL (https://drive.google.com/...) and let pyLoad do the work for you...

**Comment by mayur553** [comment]
i restarted pyload.. and its working now :) its downloading. 

Where will it save the file.. i have give a path /Public/WWW/Pyload will it automatically create the folder??

**Comment by mayur553** [comment]
By the way thanks a lot for your help. it finally started working. really appreciate your effort.

**Comment by GammaC0de** [comment]
:+1:

**Comment by GammaC0de** [comment]
I think it would create it.
The correct path should start with /shares/Public

**Comment by mayur553** [comment]
Could you also let me know what is the difference between Queue and Collector

**Comment by GammaC0de** [comment]
Queue would start the download immediately.
As for Collector, I think it saves the download for later, I never used it.

**Comment by mayur553** [comment]
Thanks,

**Comment by EikeKre** [comment]
collector question: One difference is that if you put a container directly to the collector the links are not pulled immediately. Only when pushed over to the queue

**Comment by mayur553** [comment]
@GammaC0de Can you help me with this error. This has happened 3 or 4 time... it starts download from the beginning.

689	20.07.2016 09:47:40	INFO	Added package Ape Escape containing 1 links
690	20.07.2016 09:47:42	INFO	Download starts: https://drive.google.com/file/d/0Bw4qb0Pr7JzRd0JncnRTMHJwUjA/view
691	20.07.2016 09:47:42	WARNING	HOSTER GoogledriveCom[6]: Plugin may be unstable
692	20.07.2016 09:47:42	INFO	HOSTER GoogledriveCom[6]: Grabbing link info...
693	20.07.2016 09:47:43	INFO	HOSTER GoogledriveCom[6]: Link name: BCAS20159 [Ape Escape on the Move] (2.45 GB).part1.rar
694	20.07.2016 09:47:43	INFO	HOSTER GoogledriveCom[6]: Link size: N/D
695	20.07.2016 09:47:43	INFO	HOSTER GoogledriveCom[6]: Link status: online
696	20.07.2016 09:47:43	INFO	HOSTER GoogledriveCom[6]: Processing url: https://drive.google.com/file/d/0Bw4qb0Pr7JzRd0JncnRTMHJwUjA/view
697	20.07.2016 09:47:43	INFO	HOSTER GoogledriveCom[6]: Looking for direct download link...
698	20.07.2016 09:47:44	INFO	HOSTER GoogledriveCom[6]: Direct download link not found
699	20.07.2016 09:47:46	INFO	HOSTER GoogledriveCom[6]: Checking for link errors...
700	20.07.2016 09:47:46	INFO	HOSTER GoogledriveCom[6]: No errors found
701	20.07.2016 09:47:46	INFO	HOSTER GoogledriveCom[6]: Processing as free download...
702	20.07.2016 09:47:47	INFO	HOSTER GoogledriveCom[6]: Downloading file...
703	20.07.2016 10:53:18	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
704	20.07.2016 10:54:19	INFO	Download starts: BCAS20159 [Ape Escape on the Move] (2.45 GB).part1.rar
705	20.07.2016 10:54:19	WARNING	HOSTER GoogledriveCom[6]: Plugin may be unstable

**Comment by hulyahulya** [comment]
i have problem to about google drive . when i put link pyload . pyload only download xml link.
i get this error . ' Bad server response: 500 Internal Server Error '
other link working fine on pyload.  i tried put normal link and temporary ink nothing change.thats showing 0 kb after 1 sec later . error
[http://i.hizliresim.com/MJjmDk.jpg](url)

**Comment by GammaC0de** [comment]
@hulyahulya Please open a new issue, thanks.
