### ISSUE TITLE
euroshare premium not recognized/download not working

### ISSUE THREAD

**Issue by xDereCx** [pyload/pyload#2551]
euroshare, premium not recognized, download not working

19.07.2016 19:20:56 DEBUG     HOSTER EuroshareEu[401]: Plugin version: 0.37
19.07.2016 19:20:56 DEBUG     HOSTER EuroshareEu[401]: Plugin status: testing
19.07.2016 19:20:56 WARNING   HOSTER EuroshareEu[401]: Plugin may be unstable
19.07.2016 19:20:56 DEBUG     ACCOUNT EuroshareEu: Reached login timeout for user `xxx@gmail.com`
19.07.2016 19:20:56 INFO      ACCOUNT EuroshareEu: Relogin user `xxx@gmail.com`...
19.07.2016 19:20:56 DEBUG     ACCOUNT EuroshareEu: LOAD URL http://euroshare.eu/user/login/ | redirect=True | cookies=True | get={'lang': 'en'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
19.07.2016 19:20:57 ERROR     ACCOUNT EuroshareEu: Could not login user `xxx@gmail.com` | Login form not found
19.07.2016 19:20:57 INFO      HOSTER EuroshareEu[401]: Grabbing link info...
19.07.2016 19:20:58 DEBUG     HOSTER EuroshareEu[401]: Link info: {'status': 6, 'hash': {}, 'name': 'tciw8299.part1.rar', 'url': u'http://euroshare.eu/file/26J26tR02X/tciw8299.part1.rar', 'pattern': {}, 'size': 0}
19.07.2016 19:20:58 DEBUG     HOSTER EuroshareEu[401]: Previous link info: {}
19.07.2016 19:20:58 INFO      HOSTER EuroshareEu[401]: Link name: tciw8299.part1.rar
19.07.2016 19:20:58 INFO      HOSTER EuroshareEu[401]: Link size: N/D
19.07.2016 19:20:58 INFO      HOSTER EuroshareEu[401]: Link status: temp. offline
19.07.2016 19:20:58 INFO      HOSTER EuroshareEu[401]: Processing url: http://euroshare.eu/file/26J26tR02X/tciw8299.part1.rar
19.07.2016 19:20:58 INFO      HOSTER EuroshareEu[401]: Looking for direct download link...
19.07.2016 19:20:58 DEBUG     HOSTER EuroshareEu[401]: LOAD URL http://euroshare.eu/file/26J26tR02X/tciw8299.part1.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
19.07.2016 19:20:59 INFO      HOSTER EuroshareEu[401]: Direct download link not found
19.07.2016 19:20:59 DEBUG     HOSTER EuroshareEu[401]: LOAD URL http://euroshare.eu/file/26J26tR02X/tciw8299.part1.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
19.07.2016 19:20:59 INFO      HOSTER EuroshareEu[401]: Checking for link errors...
19.07.2016 19:20:59 INFO      HOSTER EuroshareEu[401]: No errors found
19.07.2016 19:20:59 INFO      HOSTER EuroshareEu[401]: Grabbing link info...
19.07.2016 19:20:59 DEBUG     HOSTER EuroshareEu[401]: Link info: {'status': 6, 'hash': {}, 'name': 'tciw8299.part1.rar', 'url': u'http://euroshare.eu/file/26J26tR02X/tciw8299.part1.rar', 'pattern': {}, 'size': 0}
19.07.2016 19:20:59 DEBUG     HOSTER EuroshareEu[401]: Previous link info: {'status': 6, 'hash': {}, 'name': 'tciw8299.part1.rar', 'url': u'http://euroshare.eu/file/26J26tR02X/tciw8299.part1.rar', 'pattern': {}, 'size': 0}
19.07.2016 19:20:59 INFO      HOSTER EuroshareEu[401]: Link name: tciw8299.part1.rar
19.07.2016 19:20:59 INFO      HOSTER EuroshareEu[401]: Link size: N/D
19.07.2016 19:20:59 INFO      HOSTER EuroshareEu[401]: Link status: temp. offline

**Comment by GammaC0de** [comment]
Account is needed for testing,
Please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com

**Comment by xDereCx** [comment]
thx working now

**Comment by GammaC0de** [comment]
:+1:
