### ISSUE TITLE
Pyload not downloading from google drive

### ISSUE THREAD

**Issue by hulyahulya** [pyload/pyload#2552]
i have problem about google drive . when i put link pyload . pyload only download xml link.
i get this error . ' Bad server response: 500 Internal Server Error '  , other site links working fine on pyload. only problem with googledrive. i tried put normal link and temporary link nothing change.that showing 0 kb after 1 sec later . error (google drive link working on windows i tested )
<a href="http://hizliresim.com/MJjmDk"><img src="http://i.hizliresim.com/MJjmDk.jpg"></a>

**Comment by GammaC0de** [comment]
Sample URL?

**Comment by hulyahulya** [comment]
https://drive.google.com/uc?id=0B-Z-a3teFlfCN0xKYXdkNEJZOEU

im very sure its not dead link problem.  its about google drive

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/e6cf876628bbdfacf5f6c60f3b7027d0ba0cb274

**Comment by hulyahulya** [comment]
what will i do with that . can you tell me simple way .im new on this

will i do save it GoogledriveCom.py

and copy  inside /home/pi/.pyload/userplugins

**Comment by GammaC0de** [comment]
`UpdateManager` would automatically update google drive plugin according the scedule.
If you dont want to wait, restart your pyload.

**Comment by hulyahulya** [comment]
i restarted pyload.  in log life writeing . 'WARNING	Not able to connect server for updates'
i think update manager not working

**Comment by GammaC0de** [comment]
See https://github.com/pyload/pyload/issues/2469

**Comment by hulyahulya** [comment]
i dont see updatemanager.py in userplugins folder.   i just copy Updatemanager.py what you give me.
i restart pyload and check log file. there is writeing 

WARNING	Click'N'Load: Port 9666 already in use
WARNING	Not able to connect server for updates
INFO	No Updates for pyLoad

i dont use port 9666. i dont what is it

**Comment by GammaC0de** [comment]
Port 9666 is used by Click'N'Load plugin, if you don't use it you can disable this plugin or just ignore this error message.

`UpadteManager.py` should be in `userplugins/hooks` folder.

**Comment by hulyahulya** [comment]
i checked all folders. i dont have nothing else in folders . i  have that file every folder 

__init.py__.py

i deleted pyload and install again nothing change

**Comment by hulyahulya** [comment]
i copied UpadteManager.py inside hooks. i restart  respberry .  i check inside hooks folder but its deleted automtic. only there is  --init.py--.py

**Comment by GammaC0de** [comment]
Go to http://\<IP_OF_PYLOAD\>/info and see the location of "Config Folder".
`userplugins` folder should be located in `<Config Folder>/userplugins`

**Comment by hulyahulya** [comment]
ok i replace UpadteManager.py.  i chek again info . there is  no error but still cant download on google drive . i looked plugins.  i cant see there  googledrive plugin

[url=http://hizliresim.com/PMgE4d][img]http://i.hizliresim.com/PMgE4d.jpg[/img][/url]

**Comment by GammaC0de** [comment]
- Stop pyload
- Start pyload from the console: `python pyLoadCore.py -d`
- Start the download
- post all the log here

**Comment by hulyahulya** [comment]
1	23.07.2016 01:53:37	INFO	Starting pyLoad 0.4.9
2	23.07.2016 01:53:37	INFO	Using home directory: /usr/share/pyload/home/pi
3	23.07.2016 01:53:38	INFO	ExtractArchive: No UnRar installed
4	23.07.2016 01:53:38	INFO	ExtractArchive: Activated UnZip
5	23.07.2016 01:53:38	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
6	23.07.2016 01:53:38	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
7	23.07.2016 01:53:38	INFO	Downloadtime: True
8	23.07.2016 01:53:39	INFO	Starting builtin webserver: 192.168.1.46:8000
9	23.07.2016 01:53:39	INFO	Free space: 1.73 TiB
10	23.07.2016 01:53:39	INFO	Activating Accounts...
11	23.07.2016 01:53:39	INFO	Activating Plugins...
12	23.07.2016 01:53:39	INFO	pyLoad is up and running
13	23.07.2016 01:53:45	WARNING	Not able to connect server for updates
14	23.07.2016 01:53:45	INFO	No Updates for pyLoad
15	23.07.2016 01:55:46	INFO	Starting pyLoad 0.4.9
16	23.07.2016 01:55:46	INFO	Using home directory: /usr/share/pyload/home/pi
17	23.07.2016 01:55:48	INFO	ExtractArchive: No UnRar installed
18	23.07.2016 01:55:48	INFO	ExtractArchive: Activated UnZip
19	23.07.2016 01:55:48	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
20	23.07.2016 01:55:48	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
21	23.07.2016 01:55:48	INFO	Downloadtime: True
22	23.07.2016 01:55:50	INFO	Starting builtin webserver: 192.168.1.46:8000
23	23.07.2016 01:55:50	INFO	Free space: 1.73 TiB
24	23.07.2016 01:55:50	INFO	Activating Accounts...
25	23.07.2016 01:55:50	INFO	Activating Plugins...
26	23.07.2016 01:55:50	INFO	pyLoad is up and running
27	23.07.2016 01:55:52	WARNING	Not able to connect server for updates
28	23.07.2016 01:55:52	INFO	No Updates for pyLoad
29	23.07.2016 01:55:52	WARNING	Not able to connect server for updates
30	23.07.2016 01:55:52	INFO	No plugin updates available
31	23.07.2016 01:57:03	INFO	Added package 12 containing 1 links
32	23.07.2016 01:57:04	INFO	Download starts: https://docs.google.com/uc?id=0B0uPqaFewRxdVDREbmZiZU1FR1k&export=download
33	23.07.2016 01:57:08	INFO	Download finished: uc
34	23.07.2016 01:57:08	INFO	Package finished: 12
35	23.07.2016 01:57:08	INFO	ExtractArchive: Package 12 queued for later extracting
36	23.07.2016 01:57:08	INFO	ExtractArchive: Check package 12
37	23.07.2016 01:57:18	INFO	Added package wew containing 1 links
38	23.07.2016 01:57:18	INFO	Download starts: https://docs.google.com/uc?id=0B0uPqaFewRxdVDREbmZiZU1FR1k&export=download
39	23.07.2016 01:57:20	INFO	Download finished: uc
40	23.07.2016 01:57:20	INFO	Package finished: wew
41	23.07.2016 01:57:20	INFO	ExtractArchive: Package wew queued for later extracting
42	23.07.2016 01:57:20	INFO	ExtractArchive: Check package wew
43	23.07.2016 02:09:40	INFO	shutting down...
44	23.07.2016 02:09:40	INFO	Received Quit signal
45	23.07.2016 02:09:56	INFO	Starting pyLoad 0.4.9
46	23.07.2016 02:09:56	INFO	Using home directory: /usr/share/pyload/home/pi
47	23.07.2016 02:09:58	INFO	ExtractArchive: No UnRar installed
48	23.07.2016 02:09:58	INFO	ExtractArchive: Activated UnZip
49	23.07.2016 02:09:58	ERROR	Error importing UpdateManager: No module named Addon
50	23.07.2016 02:09:58	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
51	23.07.2016 02:09:58	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
52	23.07.2016 02:09:58	INFO	Downloadtime: True
53	23.07.2016 02:09:59	INFO	Starting builtin webserver: 192.168.1.46:8000
54	23.07.2016 02:09:59	INFO	Free space: 1.73 TiB
55	23.07.2016 02:09:59	INFO	Activating Accounts...
56	23.07.2016 02:09:59	INFO	Activating Plugins...
57	23.07.2016 02:09:59	INFO	pyLoad is up and running
58	23.07.2016 02:12:44	INFO	restarting pyLoad
59	23.07.2016 02:12:44	INFO	shutting down...
60	23.07.2016 02:12:45	INFO	Starting pyLoad 0.4.9
61	23.07.2016 02:12:45	INFO	Using home directory: /usr/share/pyload/home/pi
62	23.07.2016 02:12:45	INFO	ExtractArchive: No UnRar installed
63	23.07.2016 02:12:45	INFO	ExtractArchive: Activated UnZip
64	23.07.2016 02:12:45	ERROR	Error importing UpdateManager: No module named Addon
65	23.07.2016 02:12:45	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
66	23.07.2016 02:12:45	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
67	23.07.2016 02:12:45	INFO	Downloadtime: True
68	23.07.2016 02:12:46	INFO	Starting builtin webserver: 192.168.1.46:8000
69	23.07.2016 02:12:46	INFO	Free space: 1.73 TiB
70	23.07.2016 02:12:46	INFO	Activating Accounts...
71	23.07.2016 02:12:46	INFO	Activating Plugins...
72	23.07.2016 02:12:46	INFO	pyLoad is up and running
73	23.07.2016 02:13:31	INFO	Added package qqqqqqqqqq containing 1 links
74	23.07.2016 02:13:32	INFO	Download starts: https://docs.google.com/uc?id=0B0uPqaFewRxdVDREbmZiZU1FR1k&export=download
75	23.07.2016 02:13:34	INFO	Download finished: uc
76	23.07.2016 02:13:34	INFO	Package finished: qqqqqqqqqq
77	23.07.2016 02:13:34	INFO	ExtractArchive: Package qqqqqqqqqq queued for later extracting
78	23.07.2016 02:13:34	INFO	ExtractArchive: Check package qqqqqqqqqq
79	23.07.2016 02:17:34	INFO	Added package DOWNLOAD containing 1 links
80	23.07.2016 02:17:36	INFO	Download starts: https://docs.google.com/uc?id=0B0uPqaFewRxdVDREbmZiZU1FR1k&export=download
81	23.07.2016 02:17:38	INFO	Download finished: uc
82	23.07.2016 02:17:38	INFO	Package finished: DOWNLOAD
83	23.07.2016 02:17:38	INFO	ExtractArchive: Package DOWNLOAD queued for later extracting
84	23.07.2016 02:17:38	INFO	ExtractArchive: Check package DOWNLOAD
85	23.07.2016 02:36:48	INFO	shutting down...
86	23.07.2016 02:36:48	INFO	pyLoad quits
87	23.07.2016 02:38:23	INFO	Starting pyLoad 0.4.9
88	23.07.2016 02:38:23	INFO	Using home directory: /usr/share/pyload/home/pi
89	23.07.2016 02:38:25	INFO	ExtractArchive: No UnRar installed
90	23.07.2016 02:38:25	INFO	ExtractArchive: Activated UnZip
91	23.07.2016 02:38:25	ERROR	Error importing UpdateManager: No module named Addon
92	23.07.2016 02:38:25	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
93	23.07.2016 02:38:25	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
94	23.07.2016 02:38:25	INFO	Downloadtime: True
95	23.07.2016 02:38:26	INFO	Starting builtin webserver: 192.168.1.46:8000
96	23.07.2016 02:38:26	INFO	Free space: 1.73 TiB
97	23.07.2016 02:38:26	INFO	Activating Accounts...
98	23.07.2016 02:38:26	INFO	Activating Plugins...
99	23.07.2016 02:38:26	INFO	pyLoad is up and running
100	23.07.2016 02:39:18	INFO	Added package download containing 1 links
101	23.07.2016 02:39:19	INFO	Download starts: https://docs.google.com/uc?id=0B0uPqaFewRxdbnRGb1UwTXBLTzQ&export=download
102	23.07.2016 02:39:21	INFO	Download finished: uc
103	23.07.2016 02:39:21	INFO	Package finished: download
104	23.07.2016 02:39:21	INFO	ExtractArchive: Package download queued for later extracting
105	23.07.2016 02:39:21	INFO	ExtractArchive: Check package download
Jump

**Comment by hulyahulya** [comment]
did you mean that all post ?

**Comment by GammaC0de** [comment]
Yes but.. please enable debug mode and repeat the process

**Comment by hulyahulya** [comment]
debug mode enabled

1	23.07.2016 03:22:56	INFO	Starting pyLoad 0.4.9
2	23.07.2016 03:22:56	INFO	Using home directory: /home/pi/.pyload
3	23.07.2016 03:24:32	INFO	Starting pyLoad 0.4.9
4	23.07.2016 03:24:32	INFO	Using home directory: /home/pi/.pyload
5	23.07.2016 03:24:34	INFO	ExtractArchive: No UnRar installed
6	23.07.2016 03:24:34	INFO	ExtractArchive: Activated UnZip
7	23.07.2016 03:24:34	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
8	23.07.2016 03:24:34	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
9	23.07.2016 03:24:34	INFO	Downloadtime: True
10	23.07.2016 03:24:34	INFO	Starting builtin webserver: 192.168.1.46:8000
11	23.07.2016 03:24:34	INFO	Free space: 1.73 TiB
12	23.07.2016 03:24:34	INFO	Activating Accounts...
13	23.07.2016 03:24:34	INFO	Activating Plugins...
14	23.07.2016 03:24:34	INFO	pyLoad is up and running
15	23.07.2016 03:24:34	WARNING	Click'N'Load: Port 9666 already in use
16	23.07.2016 03:24:42	WARNING	Not able to connect server for updates
17	23.07.2016 03:24:42	INFO	No Updates for pyLoad
18	23.07.2016 03:25:16	INFO	shutting down...
19	23.07.2016 03:25:16	INFO	killed pyLoad from Terminal
20	23.07.2016 03:25:38	INFO	Starting pyLoad 0.4.9
21	23.07.2016 03:25:38	INFO	Using home directory: /home/pi/.pyload
22	23.07.2016 03:25:46	INFO	ExtractArchive: No UnRar installed
23	23.07.2016 03:25:46	INFO	ExtractArchive: Activated UnZip
24	23.07.2016 03:25:46	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
25	23.07.2016 03:25:46	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
26	23.07.2016 03:25:46	INFO	Downloadtime: True
27	23.07.2016 03:25:47	INFO	Starting builtin webserver: 192.168.1.46:8000
28	23.07.2016 03:25:47	INFO	Free space: 1.73 TiB
29	23.07.2016 03:25:47	INFO	Activating Accounts...
30	23.07.2016 03:25:47	INFO	Activating Plugins...
31	23.07.2016 03:25:47	INFO	pyLoad is up and running
32	23.07.2016 03:25:51	WARNING	Not able to connect server for updates
33	23.07.2016 03:25:51	INFO	No Updates for pyLoad
34	23.07.2016 03:31:59	INFO	Starting pyLoad 0.4.9
35	23.07.2016 03:31:59	INFO	Using home directory: /home/pi/.pyload
36	23.07.2016 03:32:02	INFO	ExtractArchive: No UnRar installed
37	23.07.2016 03:32:02	INFO	ExtractArchive: Activated UnZip
38	23.07.2016 03:32:02	ERROR	Error importing UpdateManager: No module named Addon
39	23.07.2016 03:32:02	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
40	23.07.2016 03:32:02	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
41	23.07.2016 03:32:02	INFO	Downloadtime: True
42	23.07.2016 03:32:06	INFO	Starting builtin webserver: 192.168.1.46:8000
43	23.07.2016 03:32:06	INFO	Free space: 1.73 TiB
44	23.07.2016 03:32:06	INFO	Activating Accounts...
45	23.07.2016 03:32:06	INFO	Activating Plugins...
46	23.07.2016 03:32:06	INFO	pyLoad is up and running
47	23.07.2016 03:32:06	WARNING	Click'N'Load: Port 9666 already in use
48	23.07.2016 03:32:37	ERROR	Error importing UpdateManager: No module named Addon
49	23.07.2016 03:32:44	INFO	restarting pyLoad
50	23.07.2016 03:32:44	INFO	shutting down...
51	23.07.2016 03:32:45	INFO	Starting pyLoad 0.4.9
52	23.07.2016 03:32:45	INFO	Using home directory: /home/pi/.pyload
53	23.07.2016 03:32:45	INFO	ExtractArchive: No UnRar installed
54	23.07.2016 03:32:45	INFO	ExtractArchive: Activated UnZip
55	23.07.2016 03:32:45	ERROR	Error importing UpdateManager: No module named Addon
56	23.07.2016 03:32:45	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
57	23.07.2016 03:32:45	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
58	23.07.2016 03:32:45	INFO	Downloadtime: True
59	23.07.2016 03:32:45	INFO	Starting builtin webserver: 192.168.1.46:8000
60	23.07.2016 03:32:45	INFO	Free space: 1.73 TiB
61	23.07.2016 03:32:45	INFO	Activating Accounts...
62	23.07.2016 03:32:45	INFO	Activating Plugins...
63	23.07.2016 03:32:45	INFO	pyLoad is up and running
64	23.07.2016 03:32:45	WARNING	Click'N'Load: Port 9666 already in use
65	23.07.2016 03:33:09	INFO	Starting pyLoad 0.4.9
66	23.07.2016 03:33:09	INFO	Using home directory: /home/pi/.pyload
67	23.07.2016 03:33:13	INFO	ExtractArchive: No UnRar installed
68	23.07.2016 03:33:15	INFO	ExtractArchive: Activated UnZip
69	23.07.2016 03:33:15	ERROR	Error importing UpdateManager: No module named Addon
70	23.07.2016 03:33:15	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
71	23.07.2016 03:33:15	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
72	23.07.2016 03:33:15	INFO	Downloadtime: True
73	23.07.2016 03:33:15	INFO	Free space: 1.73 TiB
74	23.07.2016 03:33:15	INFO	Activating Accounts...
75	23.07.2016 03:33:15	INFO	Activating Plugins...
76	23.07.2016 03:33:15	INFO	pyLoad is up and running
77	23.07.2016 03:33:16	INFO	Starting builtin webserver: 192.168.1.46:8000
78	23.07.2016 03:35:00	INFO	Added package Download containing 1 links
79	23.07.2016 03:35:02	INFO	Download starts: https://docs.google.com/uc?id=0B0uPqaFewRxdanc5Z0pseUREQ1k&export=download
80	23.07.2016 03:35:04	INFO	Download finished: uc
81	23.07.2016 03:35:04	INFO	Package finished: Download
82	23.07.2016 03:35:04	INFO	ExtractArchive: Package Download queued for later extracting
83	23.07.2016 03:35:04	INFO	ExtractArchive: Check package Download

**Comment by GammaC0de** [comment]
> 38 23.07.2016 03:32:02 ERROR Error importing UpdateManager: No module named Addon

Your `UpdateManager` still does not work.
Delete your `userplugins` folder then follow the instructions in #2000

**Comment by hulyahulya** [comment]
New .deb install fixed my problem. thank you . you saved my life

**Comment by GammaC0de** [comment]
:+1:
