### ISSUE TITLE
uploaded.net free download only guest speed

### ISSUE THREAD

**Issue by neon100** [pyload/pyload#2554]
Hello @all
uploaded.net offers for free download a guest speed (50) and a free speed (70). 
![ulnet](https://cloud.githubusercontent.com/assets/4527169/17082765/7fb9c23c-5189-11e6-940c-3b5ef3ea2c50.JPG)
Is it possible to use the free speed with pyload ?
I added my uploaded.to account in the settings tab => accounts, but in the log is a entry no traffice available and pyload use the guest speed for the download.

**Comment by GammaC0de** [comment]
So does it work fine?

**Comment by neon100** [comment]
not at all, but it is not possible to use the Free Mode and reconnect at the same time (uploaded knows your last download)

**Comment by igel-kun** [comment]
I don't know why this is closed, but I think the culprit is:
```ACCOUNT UploadedTo: Not using account [...] because the account has no traffic left```
So maybe we could not disable accounts if there's no traffic left. However, we'd have to teach the hoster plugin to not think we're in premium mode just because we have an active account...
Anyways, I don't think this should be closed...

**Comment by CultUr** [comment]
Unfortunatelly this fix broke the premium functionallity in Uplaoded.to

Workaround is to change to version 0.42 with file UploadedTo.py

**Comment by igel-kun** [comment]
CultUr, could you be more precise what "broke" means exactly, please. The unwanted behavior and if applicable, debug messages would be appreciated :)

**Comment by GammaC0de** [comment]
@CultUr This makes no sense because the behavior was not changed at all for premium users, only for free

**Comment by TheBraveWarrior** [comment]
It have the same problem with 0.43. Maybe I can help with some informations.
The problem is that the premium account isn't recognized anymore.
![image](https://cloud.githubusercontent.com/assets/20773154/17294877/a9d66220-57f9-11e6-9923-4b2b990e3fd6.png)
___
If I downgrade to 0.42 it works.
___
Debug says:
````
01.08.2016 15:12:45 INFO      ACCOUNT UploadedTo: Adding user `$$$$$$$$`...
01.08.2016 15:12:46 DEBUG     ACCOUNT UploadedTo: Reached login timeout for user `$$$$$$$$`
01.08.2016 15:12:46 INFO      ACCOUNT UploadedTo: Login user `$$$$$$$$`...
01.08.2016 15:12:46 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
01.08.2016 15:12:46 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/io/login | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'id': '$$$$$$$$', 'pw': '****'} | ref=True | just_header=False
01.08.2016 15:12:46 INFO      ACCOUNT UploadedTo: Grabbing account info for user `$$$$$$$$`...
01.08.2016 15:12:46 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
01.08.2016 15:12:46 DEBUG     ACCOUNT UploadedTo: Size: $$,$$ | Unit: gb
01.08.2016 15:12:46 DEBUG     ACCOUNT UploadedTo: Account info for user `$$$$$$$$`: {'login': {'timestamp': 1470057166.175229, 'password': '****', 'valid': True}, 'data': {'premium': None, 'plugin': <Account UploadedTo>, 'trafficleft': $$$$$$$$, 'maxtraffic': None, 'validuntil': $$$$$$$$$$.$$$$$$, 'login': '$$$$$$$$', 'type': 'UploadedTo', 'options': {'limitdl': ['0']}}}
01.08.2016 15:12:46 INFO      ACCOUNT UploadedTo: Grabbing account info for user `$$$$$$$$`...
01.08.2016 15:12:46 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
01.08.2016 15:12:46 DEBUG     ACCOUNT UploadedTo: Size: $$,$$ | Unit: gb
01.08.2016 15:12:46 DEBUG     ACCOUNT UploadedTo: Account info for user `$$$$$$$$`: {'login': {'timestamp': 1470057166.175229, 'password': '****', 'valid': True}, 'data': {'premium': None, 'plugin': <Account UploadedTo>, 'trafficleft': $$$$$$$$, 'maxtraffic': None, 'validuntil': $$$$$$$$$$.$$$$$$, 'login': '$$$$$$$$', 'type': 'UploadedTo', 'options': {'limitdl': ['0']}}}
```
___
If you guys need other information please let me know.

**Comment by GammaC0de** [comment]
Account information is needed, please send account information to nitzo2001 \[AT\] yahoo \[DOT\] com

**Comment by igel-kun** [comment]
right, so... ```if premium: [...] premium = None``` is most likely the cause I'd wager (https://github.com/pyload/pyload/blob/stable/module/plugins/accounts/UploadedTo.py#L34)

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/issues/2554

**Comment by igel-kun** [comment]
In fact, non-premium accounts seem to be poorly supported overall. I just realized that, with a free account, Rapidgator doesn't ask for a captcha for example, which is quite an advantage... I'll prepare a patch... :)
