### ISSUE TITLE
Pyload and UploadedTo Premium Issues on QNAP NAS

### ISSUE THREAD

**Issue by IanJF** [pyload/pyload#2555]
Hi,

Apologies, I know this has been discussed quite a lot. 
But I can't get my UploadedTo Premium account to show up as being "Premium".
I am using Pyload 0.4.9 on a QNAP 871U. I've tried everything, updating UpdateManager.py adding in new account .py - nothing seems to work.

I have a QNAP 439+ also and that is working perfectly (But has been for a few years).
This too is running Pyload 0.4.9 - The only main difference I notice with this one is that there seems to be a lot more accounts available in the dropdown list in the config section of the GUI???

Can someone please assist me with getting this up and running please as I need to decommission my 439+ shortly. I am not overly familiar with UNIX either.. please help...

Best Regards,
IanJF.

**Comment by GammaC0de** [comment]
Seems to work fine here, please send **debug** log.

**Comment by IanJF** [comment]
Hi,

These are the Logs I get after I start up Payload??





165	?	?	var imprintwnd = window.open('','pcrew_imprint','width=640,height=480,left=200,top=200,menubar=no,status=yes,toolbar=no');
166	?	?	imprintwnd.document.writeln("");
167	?	?	imprintwnd.document.close();
168	?	?	}
169	?	?	
170	?	?	function showPolicy(){
171	?	?	var link = 'www.parkingcrew.net';
172	?	?	policywnd = window.open(
173	?	?	'http://' + link + '/privacy.html','pcrew_policy','width=890,height=330,left=200,top=200,menubar=no,status=yes,toolbar=no');
174	?	?	policywnd.focus();
175	?	?	}
176	?	?	
177	?	?	function showAboutUs(){
178	?	?	var link = 'http://'+document.location.host+'/aboutus.php?domain=pyload.org';
179	?	?	policywnd = window.open(link,'pcrew_policy','width=890,height=330,left=200,top=200,menubar=no,status=yes,toolbar=no');
180	?	?	policywnd.focus();
181	?	?	}
182	?	?	
183	?	?	
184	?	?	2016 Copyright. All Rights Reserved. 

185	?	?	The Sponsored Listings displayed above are served automatically by a third party. Neither the service provider nor the domain owner maintain any relationship with the advertisers. In case of trademark issues please contact the domain owner directly (contact information can be found in whois).
186	?	?	

187	?	?	Privacy Policy
188	?	?	

189	?	?	

190	?	?	



199	?	?	_gaq.push(['_setCustomVar', 5, 'domty', 'ascii', 3]);
200	?	?	_gaq.push(['_gat._anonymizeIp']);
201	?	?	_gaq.push(['_trackPageview']);
202	?	?	(function() {
203	?	?	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
204	?	?	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
205	?	?	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
206	?	?	})();
207	?	?	
208	?	?	
209	?	?	




233	?	?	'fontSizeAttribution' : 14,
234	?	?	'lineHeightTitle' : 33,
235	?	?	'noTitleUnderline': true,
236	?	?	'colorTitleLink' : '#fff',
237	?	?	'rolloverLinkColor' : '#3faad3',
238	?	?	'titleBold': true,
239	?	?	'width' : '666px',
240	?	?	'adIconUrl' : 'http://afs.googleusercontent.com/dp-teaminternet/arr_3faad3.png',
241	?	?	'adIconWidth' : 17,
242	?	?	'adIconHeight' : 12,
243	?	?	'adIconSpacingAbove' : 11,
244	?	?	'adIconSpacingAfter' : 17,
245	?	?	'verticalSpacing' : 3,
246	?	?	'webFontFamily' : 'Libre Baskerville'
247	?	?	};
248	?	?	
249	?	?	
250	?	?	
251	?	?	
262	?	?	
263	?	?	
264	?	?	available ***
265	25.07.2016 20:22:01	INFO	*** Get it here: http://pyload.org/download ***
266	25.07.2016 20:22:01	INFO	No plugin updates available

**Comment by GammaC0de** [comment]
Your `UpdateManager` plugin is out of date,
manually update your `UpdateManager.py` with this one: https://github.com/pyload/pyload/raw/stable/module/plugins/hooks/UpdateManager.py

**Comment by IanJF** [comment]
Hi Thanks for that... I updated the file and now I don't have the request to update Pyload. I got to this stage before.... However, The Account for UploadedTo still shows as non premium???

<img width="1635" alt="screen shot 2016-07-25 at 8 56 02 p m" src="https://cloud.githubusercontent.com/assets/20627243/17115221/453dcbb8-52aa-11e6-8c03-3e8f1832af4c.png">

I don't seem to be able to get this to work at all??

Thanks,
IanJF

**Comment by IanJF** [comment]
New Debugs......





180	?	?	policywnd.focus();
181	?	?	}
182	?	?	
183	?	?	
184	?	?	2016 Copyright. All Rights Reserved. 

185	?	?	The Sponsored Listings displayed above are served automatically by a third party. Neither the service provider nor the domain owner maintain any relationship with the advertisers. In case of trademark issues please contact the domain owner directly (contact information can be found in whois).
186	?	?	

187	?	?	Privacy Policy
188	?	?	

189	?	?	

190	?	?	
208	?	?	
209	?	?	


214	?	?	// Colors
215	?	?	'colorSearchButton' : '#3faad3',
216	?	?	'colorSearchButtonText' : '#fff',
217	?	?	// Font-Sizes
218	?	?	'fontSizeSearchInput' : 12,
219	?	?	'fontSizeSearchButton' : 13,
220	?	?	// Alphabetically
221	?	?	'hideSearchButtonBorder' : true,
222	?	?	'hideSearchInputBorder' : true
223	?	?	};
224	?	?	
225	?	?	var tcblock = {
226	?	?	'container' : 'tc',
227	?	?	'type' : 'relatedsearch',
228	?	?	// Optional params.
229	?	?	'number' : 10,
230	?	?	'fontSizeTitle' : 22,
231	?	?	'colorBackground' : 'transparent',
232	?	?	'colorAttribution' : '#aaa',
233	?	?	'fontSizeAttribution' : 14,
234	?	?	'lineHeightTitle' : 33,
235	?	?	'noTitleUnderline': true,
236	?	?	'colorTitleLink' : '#fff',
237	?	?	'rolloverLinkColor' : '#3faad3',
238	?	?	'titleBold': true,
239	?	?	'width' : '666px',
240	?	?	'adIconUrl' : 'http://afs.googleusercontent.com/dp-teaminternet/arr_3faad3.png',
241	?	?	'adIconWidth' : 17,
242	?	?	'adIconHeight' : 12,
243	?	?	'adIconSpacingAbove' : 11,
244	?	?	'adIconSpacingAfter' : 17,
245	?	?	'verticalSpacing' : 3,
246	?	?	'webFontFamily' : 'Libre Baskerville'
247	?	?	};


248	?	?	
249	?	?	
250	?	?	
251	?	?	
262	?	?	
263	?	?	
264	?	?	available ***
265	25.07.2016 20:22:01	INFO	*** Get it here: http://pyload.org/download ***
266	25.07.2016 20:22:01	INFO	No plugin updates available
267	25.07.2016 20:51:19	INFO	shutting down...
268	25.07.2016 20:51:19	INFO	Received Quit signal
269	25.07.2016 20:51:39	INFO	Starting pyLoad 0.4.9
270	25.07.2016 20:51:39	INFO	Using home directory: /share/CACHEDEV1_DATA/.qpkg/pyload/data
271	25.07.2016 20:51:40	INFO	ExtractArchive: Activated UnRar
272	25.07.2016 20:51:40	ERROR	Error importing UpdateManager: No module named Addon
273	25.07.2016 20:51:40	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
274	25.07.2016 20:51:40	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
275	25.07.2016 20:51:40	INFO	Downloadtime: True
276	25.07.2016 20:51:40	INFO	Starting ThriftBackend: 0.0.0.0:7227
277	25.07.2016 20:51:40	INFO	Free space: 14.55 TiB
278	25.07.2016 20:51:40	INFO	Starting builtin webserver: 0.0.0.0:8100
279	25.07.2016 20:51:40	INFO	Activating Accounts...
280	25.07.2016 20:51:41	INFO	Activating Plugins...
281	25.07.2016 20:51:41	INFO	pyLoad is up and running

**Comment by GammaC0de** [comment]
Add this line to to https://github.com/pyload/pyload/blob/stable/module/plugins/accounts/UploadedTo.py#L33
```
        self.log_debug("HTML: %s" % html)
```

Re-add the account and post the log here

**Comment by GammaC0de** [comment]
Add this line to to https://github.com/pyload/pyload/blob/stable/module/plugins/accounts/UploadedTo.py#L33
```
        self.log_debug("HTML: %s" % html)
```

Re-add the account and post the log here

**Comment by IanJF** [comment]
When I go to CONFIG.... This is what I see....

An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/utils.py", line 165, in new
return func(*args)
File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

**Comment by IanJF** [comment]
So I can't delete the account and add it back in.. it doesn't give me the option to...
Here is the logs....


276	25.07.2016 20:51:40	INFO	Starting ThriftBackend: 0.0.0.0:7227
277	25.07.2016 20:51:40	INFO	Free space: 14.55 TiB
278	25.07.2016 20:51:40	INFO	Starting builtin webserver: 0.0.0.0:8100
279	25.07.2016 20:51:40	INFO	Activating Accounts...
280	25.07.2016 20:51:41	INFO	Activating Plugins...
281	25.07.2016 20:51:41	INFO	pyLoad is up and running
282	25.07.2016 21:13:39	INFO	shutting down...
283	25.07.2016 21:13:39	INFO	Received Quit signal
284	25.07.2016 21:13:47	INFO	Starting pyLoad 0.4.9
285	25.07.2016 21:13:47	INFO	Using home directory: /share/CACHEDEV1_DATA/.qpkg/pyload/data
286	25.07.2016 21:13:47	INFO	ExtractArchive: Activated UnRar
287	25.07.2016 21:13:47	ERROR	Error importing UpdateManager: No module named Addon
288	25.07.2016 21:13:47	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
289	25.07.2016 21:13:47	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
290	25.07.2016 21:13:47	INFO	Downloadtime: True
291	25.07.2016 21:13:47	INFO	Starting ThriftBackend: 0.0.0.0:7227
292	25.07.2016 21:13:47	INFO	Free space: 14.55 TiB
293	25.07.2016 21:13:47	INFO	Starting builtin webserver: 0.0.0.0:8100
294	25.07.2016 21:13:47	INFO	Activating Accounts...
295	25.07.2016 21:13:47	ERROR	Error importing UploadedTo: invalid syntax (UploadedTo.py, line 5)
296	25.07.2016 21:14:18	ERROR	Error importing UploadedTo: invalid syntax (UploadedTo.py, line 5)
297	25.07.2016 21:18:32	INFO	Starting pyLoad 0.4.9
298	25.07.2016 21:18:32	INFO	Using home directory: /share/CACHEDEV1_DATA/.qpkg/pyload/data
299	25.07.2016 21:18:32	INFO	ExtractArchive: Activated UnRar
300	25.07.2016 21:18:32	ERROR	Error importing UpdateManager: No module named Addon
301	25.07.2016 21:18:32	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
302	25.07.2016 21:18:32	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
303	25.07.2016 21:18:32	INFO	Downloadtime: True
304	25.07.2016 21:18:32	INFO	Starting ThriftBackend: 0.0.0.0:7227
305	25.07.2016 21:18:32	INFO	Free space: 14.55 TiB
306	25.07.2016 21:18:32	INFO	Starting builtin webserver: 0.0.0.0:8100
307	25.07.2016 21:18:32	INFO	Activating Accounts...
308	25.07.2016 21:18:32	ERROR	Error importing UploadedTo: invalid syntax (UploadedTo.py, line 5)
309	25.07.2016 21:18:51	ERROR	Error importing UploadedTo: invalid syntax (UploadedTo.py, line 5)

**Comment by GammaC0de** [comment]
I suggest you reinstall pyload using the instructions in #2000

**Comment by IanJF** [comment]
Thank you for your time on this... I appreciate it...

I'm afraid I'm not too sure how to do that in 2000.... I don't know what Operating System I need for QNAP and then how to initiate a new install

**Comment by GammaC0de** [comment]
Ok, so just delete your 'userplugins` folder instead of reinstalling and then replace `UpdateManager.py` with the one in #2000

**Comment by IanJF** [comment]
Thank you SO MUCH for your brilliant help and assistance...
That worked :)
The Accounts updated and added lots of new ones, and once restarted and account added back in... It now sees it as a Premium account... Once again.. Thank you so much GammaC0de - much appreciated mate....

<img width="1680" alt="screen shot 2016-07-25 at 9 55 14 p m" src="https://cloud.githubusercontent.com/assets/20627243/17117131/bf954532-52b2-11e6-8402-6b68181f312d.png">

**Comment by GammaC0de** [comment]
:+1: :+1: :+1:
