### ISSUE TITLE
OneFichier seems "out of date"

### ISSUE THREAD

**Issue by zephura** [pyload/pyload#2556]
the plugin for onefichier looks like "out of date".

Do I need to provide the full trace, or only an extract will be enough?

**Comment by GammaC0de** [comment]
Sample URL please.

**Comment by zephura** [comment]
`https://1fichier.com/?q6rnkgiqkj`

**Comment by GammaC0de** [comment]
Works fine here.
`

**Comment by zephura** [comment]
I must have missed something somewhere...
it works fine

thank you!
