### ISSUE TITLE
Download directory

### ISSUE THREAD

**Issue by mayur553** [pyload/pyload#2558]
Hi i am using WD NAS while setting up i have given the download path as /Public/WWW

This is an existing path or folder in my NAS, however i cannot find any files of foldes in it. 

I searched my NAS and i cannot find the downloaded file.

Please help

**Comment by GammaC0de** [comment]
As far as I know, the correct path for WD should be /shares/Public/WWW

**Comment by mayur553** [comment]
there is not shares folder in my WD... the path is \\10.0.0.XX\Public\WWW

**Comment by GammaC0de** [comment]
So pyload is running on another machine and not locally on the WD NAS?

**Comment by mayur553** [comment]
Pyload is not running on any other machine it is running on NAS. (10.0.0.10 is my wd ip address)

Now if i add another link i get this error

29.07.2016 15:51:44	INFO	Starting threaded webserver: 10.0.0.10:8000
766	29.07.2016 15:55:20	INFO	Added package Barbie containing 1 links
767	29.07.2016 15:55:22	WARNING	Not enough space left on device
768	29.07.2016 15:55:28	WARNING	Not enough space left on device
769	29.07.2016 15:55:38	WARNING	Not enough space left on device
770	29.07.2016 15:55:52	WARNING	Not enough space left on device
771	29.07.2016 15:56:02	WARNING	Not enough space left on device
772	29.07.2016 15:56:39	INFO	Added package Barbie containing 1 links
773	29.07.2016 15:56:41	WARNING	Not enough space left on device
774	29.07.2016 19:58:38	WARNING	Not enough space left on device

**Comment by GammaC0de** [comment]
OK, so if it runs locally, download path should not be \\\\10.0.0.10\Public\WWW.
To view the real path of \Public do `cat /etc/samba/overall_share` (at least that's how it's on my machine)

**Comment by mayur553** [comment]
This is what i get.

MyBookLive:~# cat /etc/samba/overall_share

## BEGIN ## sharename = Public #
[Public]
  path = /DataVolume/shares/Public
  comment = Public Share
  public = yes
  browseable = yes
  writable = yes
  guest ok = yes
  map read only = no
## END ##

## BEGIN ## sharename = SmartWare #
[SmartWare]
  path = /shares/SmartWare
  comment = SmartWare
  public = yes
  browseable = yes
  writable = yes
  guest ok = yes
  map read only = no
## END ##
## BEGIN ## sharename = TimeMachineBackup #
[TimeMachineBackup]
  path = /shares/TimeMachineBackup
  comment = TimeMachineBackup
  public = yes
  browseable = yes
  writable = yes
  guest ok = yes
  map read only = no
## END ##
## BEGIN ## sharename = TimeMachine #
[TimeMachine]
  path = /shares/TimeMachine
  comment = TimeMachine
  public = yes
  browseable = yes
  writable = yes
  guest ok = yes
  map read only = no
## END ##

Also why is it showing not enough space. i have 34% of 2 tb still free

**Comment by mayur553** [comment]
Seems to have solved the issue. have changed the path to /DataVolumes/shares/public and it works.

**Comment by GammaC0de** [comment]
:+1:
