### ISSUE TITLE
Reconnect not working

### ISSUE THREAD

**Issue by mayur553** [pyload/pyload#2559]
I have been trying to download this 2 gb file. i have got the following error. pyload restarted the download 3 times can someone help.

30.07.2016 01:28:03	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
885	30.07.2016 01:29:03	INFO	Download starts: BCAS20159 [Ape Escape on the Move] (2.45 GB).part1.rar
886	30.07.2016 01:29:03	WARNING	HOSTER GoogledriveCom[14]: Plugin may be unstable
887	30.07.2016 01:29:04	INFO	HOSTER GoogledriveCom[14]: Grabbing link info...
888	30.07.2016 01:29:05	INFO	HOSTER GoogledriveCom[14]: Link name: BCAS20159 [Ape Escape on the Move] (2.45 GB).part1.rar
889	30.07.2016 01:29:05	INFO	HOSTER GoogledriveCom[14]: Link size: N/D
890	30.07.2016 01:29:05	INFO	HOSTER GoogledriveCom[14]: Link status: online
891	30.07.2016 01:29:05	INFO	HOSTER GoogledriveCom[14]: Processing url: https://drive.google.com/file/d/0Bw4qb0Pr7JzRd0JncnRTMHJwUjA/view
892	30.07.2016 01:29:05	INFO	HOSTER GoogledriveCom[14]: Looking for direct download link...
893	30.07.2016 01:29:06	INFO	HOSTER GoogledriveCom[14]: Direct download link not found
894	30.07.2016 01:29:09	INFO	HOSTER GoogledriveCom[14]: Checking for link errors...
895	30.07.2016 01:29:09	INFO	HOSTER GoogledriveCom[14]: No errors found
896	30.07.2016 01:29:09	INFO	HOSTER GoogledriveCom[14]: Processing as free download...
897	30.07.2016 01:29:11	INFO	HOSTER GoogledriveCom[14]: Downloading file...
898	30.07.2016 03:25:31	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
899	30.07.2016 03:26:31	INFO	Download starts: BCAS20159 [Ape Escape on the Move] (2.45 GB).part1.rar
900	30.07.2016 03:26:31	WARNING	HOSTER GoogledriveCom[14]: Plugin may be unstable
901	30.07.2016 03:26:31	INFO	HOSTER GoogledriveCom[14]: Grabbing link info...
902	30.07.2016 03:26:33	INFO	HOSTER GoogledriveCom[14]: Link name: BCAS20159 [Ape Escape on the Move] (2.45 GB).part1.rar
903	30.07.2016 03:26:33	INFO	HOSTER GoogledriveCom[14]: Link size: N/D
904	30.07.2016 03:26:33	INFO	HOSTER GoogledriveCom[14]: Link status: online
905	30.07.2016 03:26:33	INFO	HOSTER GoogledriveCom[14]: Processing url: https://drive.google.com/file/d/0Bw4qb0Pr7JzRd0JncnRTMHJwUjA/view
906	30.07.2016 03:26:33	INFO	HOSTER GoogledriveCom[14]: Looking for direct download link...
907	30.07.2016 03:26:35	INFO	HOSTER GoogledriveCom[14]: Direct download link not found
908	30.07.2016 03:26:39	INFO	HOSTER GoogledriveCom[14]: Checking for link errors...
909	30.07.2016 03:26:39	INFO	HOSTER GoogledriveCom[14]: No errors found
910	30.07.2016 03:26:39	INFO	HOSTER GoogledriveCom[14]: Processing as free download...
911	30.07.2016 03:26:41	INFO	HOSTER GoogledriveCom[14]: Downloading file...
912	30.07.2016 03:27:25	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
913	30.07.2016 03:28:25	INFO	Download starts: BCAS20159 [Ape Escape on the Move] (2.45 GB).part1.rar
914	30.07.2016 03:28:25	WARNING	HOSTER GoogledriveCom[14]: Plugin may be unstable
915	30.07.2016 03:28:25	INFO	HOSTER GoogledriveCom[14]: Grabbing link info...
916	30.07.2016 03:28:27	INFO	HOSTER GoogledriveCom[14]: Link name: BCAS20159 [Ape Escape on the Move] (2.45 GB).part1.rar
917	30.07.2016 03:28:27	INFO	HOSTER GoogledriveCom[14]: Link size: N/D
918	30.07.2016 03:28:27	INFO	HOSTER GoogledriveCom[14]: Link status: online
919	30.07.2016 03:28:27	INFO	HOSTER GoogledriveCom[14]: Processing url: https://drive.google.com/file/d/0Bw4qb0Pr7JzRd0JncnRTMHJwUjA/view
920	30.07.2016 03:28:27	INFO	HOSTER GoogledriveCom[14]: Looking for direct download link...
921	30.07.2016 03:28:28	INFO	HOSTER GoogledriveCom[14]: Direct download link not found
922	30.07.2016 03:28:31	INFO	HOSTER GoogledriveCom[14]: Checking for link errors...
923	30.07.2016 03:28:31	INFO	HOSTER GoogledriveCom[14]: No errors found
924	30.07.2016 03:28:31	INFO	HOSTER GoogledriveCom[14]: Processing as free download...
925	30.07.2016 03:28:32	INFO	HOSTER GoogledriveCom[14]: Downloading file...
926	30.07.2016 06:08:15	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
927	30.07.2016 06:09:15	INFO	Download starts: BCAS20159 [Ape Escape on the Move] (2.45 GB).part1.rar
928	30.07.2016 06:09:15	WARNING	HOSTER GoogledriveCom[14]: Plugin may be unstable
929	30.07.2016 06:09:15	INFO	HOSTER GoogledriveCom[14]: Grabbing link info...
930	30.07.2016 06:09:17	INFO	HOSTER GoogledriveCom[14]: Link name: BCAS20159 [Ape Escape on the Move] (2.45 GB).part1.rar
931	30.07.2016 06:09:17	INFO	HOSTER GoogledriveCom[14]: Link size: N/D
932	30.07.2016 06:09:17	INFO	HOSTER GoogledriveCom[14]: Link status: online
933	30.07.2016 06:09:17	INFO	HOSTER GoogledriveCom[14]: Processing url: https://drive.google.com/file/d/0Bw4qb0Pr7JzRd0JncnRTMHJwUjA/view
934	30.07.2016 06:09:17	INFO	HOSTER GoogledriveCom[14]: Looking for direct download link...
935	30.07.2016 06:09:19	INFO	HOSTER GoogledriveCom[14]: Direct download link not found
936	30.07.2016 06:09:23	INFO	HOSTER GoogledriveCom[14]: Checking for link errors...
937	30.07.2016 06:09:23	INFO	HOSTER GoogledriveCom[14]: No errors found
938	30.07.2016 06:09:23	INFO	HOSTER GoogledriveCom[14]: Processing as free download...
939	30.07.2016 06:09:25	INFO	HOSTER GoogledriveCom[14]: Downloading file...

**Comment by GammaC0de** [comment]
Worked fine here...

**Comment by GammaC0de** [comment]
Update?

**Comment by degs01** [comment]
yes
thx
