### ISSUE TITLE
Uploaded.net Plugin - No Premium

### ISSUE THREAD

**Issue by FragzPW** [pyload/pyload#2564]
Hello,
My problem is .. Pyload says my Uploaded Account is not  a Premium Accout but it is :) Downloads from Uploaded.net doesnt Start.

**Comment by GammaC0de** [comment]
Are you sure? this was already fixed in plugin version 0.44 (https://github.com/pyload/pyload/commit/c32f7e92e2b737ac966df4a03cfe203943e6f628)
Which plugin version do you use?

**Comment by FragzPW** [comment]
__name__    = "UploadedTo"
    __type__    = "hoster"
    __version__ = "1.01"
    __status__  = "testing"

i have downloaded the latest Release 0.49

**Comment by damien313** [comment]
had the same issue since the plugin updated to version 0.43 yesterday

INFO	ADDON UpdateManager: New version of plugin: ACCOUNT UploadedTo (v0.42 -> v0.43)

just restarted pyload to perform the update routine... 

INFO	ADDON UpdateManager: New version of plugin: ACCOUNT UploadedTo (v0.43 -> v0.44)

**Comment by FragzPW** [comment]
Thank you. it works Again!

**Comment by GammaC0de** [comment]
:+1:
