### ISSUE TITLE
pyLoadCore crashes on initial start-up

### ISSUE THREAD

**Issue by Anfauglith** [pyload/pyload#2568]
When first running pyLoadCore.py it crashes after entering a language code with 
` ... `
`RuntimeError: maximum recursion depth exceeded while calling a Python object`
on the `find` function. 

I think i traced back the issue to the module ./module/common/pylgettext.py, which redefines (or tries to redefine) the function `find` provided by python as `origfind` using
`origfind = find` in line 8 and
`translation.func_globals['find'] = find` in line 61
and then defines a new `find` using `origfind`.

If i comment out both lines and write 
`from gettext import find as origfind`
`from gettext import *`
instead of
`from gettext import *`
everything runs fine.

I have no idea how to commit a change using git, so I would be happy if someone else could recheck this and then commit it.

**Comment by GammaC0de** [comment]
What version of python are you running?

**Comment by Anfauglith** [comment]
I am running Python 2.7.12 provided by the openSUSE Leap Update repository.

**Comment by GammaC0de** [comment]
From where did you downloaded your pyLoad package? try following the instructions in #2000.

**Comment by Anfauglith** [comment]
Sorry for the delay. 

Initially I cloned the `stable` branch. Today I tested again with the `src` provided on the download page, same error, both with and without the fixed `UpdateManager.py`.

As a sidenote: If I configure pyLoad with my version of `gettext.py`, running the core again with the old file crashes immediately, which could be expected, I guess.

**Comment by GammaC0de** [comment]
For `src` you have to rename `Utils.py` to `utils.py`
Also try running `pyLoadCore.py -d` to enable debug mode and see the exception details

**Comment by Anfauglith** [comment]
Thanks for the help, I now tried all that, but to no avail. Also, debug does not give additional information. Attached is the full error message, with `...` standing for repetitions of the same message over and over again.

```
Traceback (most recent call last):
  File "pyLoadCore.py", line 667, in <module>
    main()
  File "pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "pyLoadCore.py", line 295, in start
    languages=[self.config['general']['language'],"en"],fallback=True)
  File "/usr/lib64/python2.7/gettext.py", line 474, in translation
    mofiles = find(domain, localedir, languages, all=1)
  File "/home/amon/code/pyload/module/common/pylgettext.py", line 46, in find
    res = origfind(domain, dir, languages, all)
  File "/usr/lib64/python2.7/gettext.py", line 428, in find
    bundle = find(domain, localedir=_default_bundlelocaledir, languages=languages, all=all)
  File "/home/amon/code/pyload/module/common/pylgettext.py", line 46, in find
    res = origfind(domain, dir, languages, all)

  ...
    
  File "/usr/lib64/python2.7/gettext.py", line 428, in find
    bundle = find(domain, localedir=_default_bundlelocaledir, languages=languages, all=all)
  File "/home/amon/code/pyload/module/common/pylgettext.py", line 46, in find
    res = origfind(domain, dir, languages, all)
  File "/usr/lib64/python2.7/gettext.py", line 446, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib64/python2.7/gettext.py", line 135, in _expand_lang
    locale = normalize(locale)
  File "/usr/lib64/python2.7/locale.py", line 383, in normalize
    localename = localename.encode('ascii')
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

Like I said, I can get pyLoad to work with the substitutions mentioned in my first post. So far no problems have appeared, so for me the issue is solved. It is strange though, that I am the only one getting this error.

**Comment by GammaC0de** [comment]
OK, since its a bug in pylgettext.py and not in pyLoad and also it works for you, I'm closing this.
