### ISSUE TITLE
flexget -> pyload fails with error 500

### ISSUE THREAD

**Issue by Leonderi** [pyload/pyload#2569]
Flexget allways fails with `(failure reason: 500 Server Error: Internal Server Error for url: http://10.10.10.180:8000/api/addPackage)`.

This is what the flexget log gives me: [http://pastebin.com/bsjp0wQH](url)
But there are no entries in the pyload log.

**Comment by Roburetto** [comment]
flexget pyload module was updated yesterday. See if the [new commit](https://github.com/Flexget/Flexget/pull/1391) helps.

**Comment by Velociraptor85** [comment]
@Leonderi any news on this one ?

**Comment by Velociraptor85** [comment]
closing since @Leonderi does not respond and could not comment on the new commit - may reopen again.
