### ISSUE TITLE
easybytez prenium problem 

### ISSUE THREAD

**Issue by underLgN** [pyload/pyload#2570]
Good morning.

For a few days it has stopped working the prenium account easybyte

EasybytezCom	XXXXXXXXXXX	
valid	yes	22.09.2016	unlimited

4.08.2016 01:44:00	WARNING	HOSTER EasybytezCom[18]: Premium download failed

**Comment by GammaC0de** [comment]
Why closed?

**Comment by underLgN** [comment]
After installing the account again, operates regularly until yesterday vevgai is the second time that I do, which is to be prenium but not to see that the account is prenium

**Comment by GammaC0de** [comment]
@underLgN Account info is needed for testing, please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com.

**Comment by GammaC0de** [comment]
Closing because of no response.
