### ISSUE TITLE
NitroFlare NoneType error

### ISSUE THREAD

**Issue by silvern18** [pyload/pyload#2571]
Good evening to all!
I installed PyLoad on my Raspberry and everything went fine till yesterday.
I generally add only NitroFlare links but from yesterday I get this error:

'NoneType' object has no attribute 'NitroflareCom'

This is what I get from the log:

1544	15.08.2016 21:24:53	CRITICAL	'NoneType' object has no attribute 'NitroflareCom'
1543	15.08.2016 21:24:53	ERROR	Error importing NitroflareCom: No module named ReCaptcha
1542	15.08.2016 21:24:53	DEBUG	Redirected import module.plugins.hoster.NitroflareCom -> userplugins.hoster.NitroflareCom
1541	15.08.2016 21:24:25	INFO	No Updates for pyLoad

Does anyone have any clue?
Thanks in advance to all oy you!!

**Comment by GammaC0de** [comment]
How exactly did you installed pyLoad? please read #2000

**Comment by GammaC0de** [comment]
Closing because of no answer.

**Comment by silvern18** [comment]
Sorry for the delay, I had lots of work during last week.
Anyway, I followed the procedure to replace UpdateManager.py but errors are still there and here's the log:

295	24.08.2016 19:56:25	CRITICAL	'NoneType' object has no attribute 'NitroflareCom'
294	24.08.2016 19:56:25	ERROR	Error importing NitroflareCom: No module named ReCaptcha
293	24.08.2016 19:56:25	DEBUG	Redirected import module.plugins.hoster.NitroflareCom -> userplugins.hoster.NitroflareCom
292	24.08.2016 19:54:02	INFO	No Updates for pyLoad
291	24.08.2016 19:54:02	WARNING	Not able to connect server for updates
290	24.08.2016 19:53:59	INFO	pyLoad is up and running
289	24.08.2016 19:53:59	INFO	Activating Plugins...
288	24.08.2016 19:53:59	INFO	Activating Accounts...
287	24.08.2016 19:53:59	INFO	Free space: 231.68 GiB
286	24.08.2016 19:53:58	INFO	Starting builtin webserver: 0.0.0.0:5003
285	24.08.2016 19:53:57	INFO	Avvio ThriftBackend: 0.0.0.0:7227
284	24.08.2016 19:53:57	INFO	Tempo di download: True
283	24.08.2016 19:53:57	INFO	Plugins disattivati: Ev0InFetcher, HotFolder, IRCInterface, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
282	24.08.2016 19:53:57	INFO	Plugins attivati: CaptchaTrader, ClickAndLoad, ExternalScripts, MergeFiles, UpdateManager
281	24.08.2016 19:53:57	ERROR	Errore durante l'importazione ExtractArchive: No module named Addon
280	24.08.2016 19:53:57	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
279	24.08.2016 19:53:57	DEBUG	ExternalScripts: Script folder all_dls_processed not created
278	24.08.2016 19:53:57	DEBUG	ExternalScripts: Script folder all_dls_finished not created
277	24.08.2016 19:53:57	DEBUG	ExternalScripts: Script folder unrar_finished not created
276	24.08.2016 19:53:57	DEBUG	ExternalScripts: Script folder after_reconnect not created
275	24.08.2016 19:53:57	DEBUG	ExternalScripts: Script folder before_reconnect not created
274	24.08.2016 19:53:57	DEBUG	ExternalScripts: Script folder package_finished not created
273	24.08.2016 19:53:57	DEBUG	ExternalScripts: Script folder download_finished not created
272	24.08.2016 19:53:57	DEBUG	ExternalScripts: Script folder download_preparing not created
271	24.08.2016 19:53:57	DEBUG	created index of plugins
270	24.08.2016 19:53:56	DEBUG	Remote activated: True
269	24.08.2016 19:53:56	INFO	Uso la cartella home: /home/pi/.pyload
268	24.08.2016 19:53:56	INFO	Avvio pyLoad 0.4.9

This is (reversed) all the log from the restart to the error when starting a download.

Any clue?

Thanks!!!

**Comment by GammaC0de** [comment]
Please delete your `userplugins` folder and then:
restart pyload, wait about 5 minutes and then restart pyload again

Retry.

**Comment by silvern18** [comment]
Good evening,
sorry to disturb you but still no luck....
This is the log after the second reboot.


725	26.08.2016 16:58:24	CRITICAL	None
724	26.08.2016 16:58:24	WARNING	Plugin NitroflareCom not found.
723	26.08.2016 16:57:41	INFO	No Updates for pyLoad
722	26.08.2016 16:57:41	WARNING	Not able to connect server for updates
721	26.08.2016 16:57:36	INFO	pyLoad is up and running
720	26.08.2016 16:57:36	INFO	Activating Plugins...
719	26.08.2016 16:57:36	INFO	Activating Accounts...
718	26.08.2016 16:57:36	INFO	Free space: 231.77 GiB
717	26.08.2016 16:57:36	INFO	Starting builtin webserver: 0.0.0.0:5003
716	26.08.2016 16:57:34	INFO	Avvio ThriftBackend: 0.0.0.0:7227
715	26.08.2016 16:57:34	INFO	Tempo di download: True
714	26.08.2016 16:57:34	INFO	Plugins disattivati: Ev0InFetcher, HotFolder, IRCInterface, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
713	26.08.2016 16:57:34	INFO	Plugins attivati: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, MergeFiles, UpdateManager
712	26.08.2016 16:57:34	INFO	ExtractArchive: Attivato UnRar UnZip
711	26.08.2016 16:57:33	DEBUG	ExternalScripts: Script folder all_dls_processed not created
710	26.08.2016 16:57:33	DEBUG	ExternalScripts: Script folder all_dls_finished not created
709	26.08.2016 16:57:33	DEBUG	ExternalScripts: Script folder unrar_finished not created
708	26.08.2016 16:57:33	DEBUG	ExternalScripts: Script folder after_reconnect not created
707	26.08.2016 16:57:33	DEBUG	ExternalScripts: Script folder before_reconnect not created
706	26.08.2016 16:57:33	DEBUG	ExternalScripts: Script folder package_finished not created
705	26.08.2016 16:57:33	DEBUG	ExternalScripts: Script folder download_finished not created
704	26.08.2016 16:57:33	DEBUG	ExternalScripts: Script folder download_preparing not created
703	26.08.2016 16:57:33	DEBUG	created index of plugins
702	26.08.2016 16:57:32	DEBUG	Remote activated: True
701	26.08.2016 16:57:32	INFO	Uso la cartella home: /home/pi/.pyload
700	26.08.2016 16:57:32	INFO	Avvio pyLoad 0.4.9

It seems that now no NitroFlare plugin is found (how about other plugins? Log reports Not able to connect server for updates...)!

Thanks again!

**Comment by GammaC0de** [comment]
* Stop pyLoad
* Go to `http://<ip_of_pyload>:8000/info`, see the value on "Installation Folder"
* Replace `<Installation Folder>/module/plugins/hooks/UpdateManager.py` with the one in #2000 
* Start pyLoad
* Wait about 5 minutes
* Restart pyLoad

**Comment by silvern18** [comment]
Wow, thanks a lot!
That was the trick...I simply didn't replace the right UpdateManager.
For those wondering, for Pyload on a Raspberry the standard installation folder is:

/usr/share/pyload

while the configuration folder is:

/home/pi/.pyload

Thanks again!
Best regards

**Comment by GammaC0de** [comment]
:+1:
