### ISSUE TITLE
systemCheck.py does not recognize imaging library on CentOS 7

### ISSUE THREAD

**Issue by djessich** [pyload/pyload#2572]
Imaging library has been installed using yum, with the follwoing command.
`yum install python-imaging # -> resolves to python-pillow`

When running systemCheck.py after install, it does not recognize python-imaging. While looking at the code, I recognized, that in the script only _'import Image'_ is written. We should improve that and also test import for PIL by using _'from PIL import Image'_, as this would work in this case.

If you have a look at [ReCaptcha.py](https://github.com/pyload/pyload/blob/stable/module/plugins/captcha/ReCaptcha.py#L14), you can see how the current code could be improved.

**Comment by Velociraptor85** [comment]
@djessich did you fix this? can this post help you https://github.com/pyload/pyload/issues/2612 ?
Please close if it is resolved

**Comment by djessich** [comment]
I converged a CentOS 7 node and ran systemCheck.py. I got the following output:

```
#####   System Information   #####

('Platform:', 'linux2')
('Operating System:', 'posix')
('Python:', '2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]\n')
('pycurl:', 'libcurl/7.29.0 NSS/3.19.1 Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3')
('py-crypto:', '2.6.1')
('OpenSSL:', '0.13.1')
('image libary:', 'missing')
('pyqt:', '4.10.1')


#####   System Status   #####

##  pyLoadCore  ##
The system check has detected some errors:

Please install py-imaging/pil to use Hoster, which uses captchas.

##  pyLoadGui  ##
No Problems detected, pyLoadGui should work fine.

##  Webinterface  ##
No Problems detected, Webinterface should work fine.
```
Checking the output, the imaging library is not recognised and resolved to be missing although it is installed from the `python-pillow` package. I also changed the script (just for testing purposes) to import using `from PIL import Image`. Then the library is recognised.

If a file within Pyload project will import using above statement, there won't be a problem, but if not the appropriate functionality as programmed in the source code file, may not work (on CentOS 7).
