### ISSUE TITLE
CatShareNet traffic left wouldn't work

### ISSUE THREAD

**Issue by mike321** [pyload/pyload#2576]
Hi,

Plugin version 0.12 can't get valid traffic left info and therefore it can't download any files using premium account. Suprisingly version 0.07 still works. There ate not many changes between those versions - the biggest one is that 0.07 is using parse_traffic where new one parseTraffic routine. If you need more info, let me know.

Cheers!

**Comment by GammaC0de** [comment]
Account info needed, please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com.
