### ISSUE TITLE
keep2share API

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#2580]
It seems people reverse engineered a keep2share API here: https://github.com/keep2share/api
Maybe we want to use that :)

**Comment by GammaC0de** [comment]
If you would like this to be implemented,
please send  sample URL and account info  if possible (send account info to nitzo2001 \[AT\] yahoo \[DOT\] com)

**Comment by igel-kun** [comment]
Oh, I think I can implement that, the question is whether it's worth doing. I'd rather not spend the time if the PR is then rejected because there already is a working implementation that uses the web interface. So, is using an API generally preferred to using the web interface?

**Comment by GammaC0de** [comment]
Yes, using an API generally preferred to using the web interface because it supposed to be more stable an APIs change less often the web..

Of-course your PR will be reviewed for code quality :wink:

**Comment by GammaC0de** [comment]
News?

**Comment by igel-kun** [comment]
argl, sorry, nothing usable yet.

**Comment by GammaC0de** [comment]
No progress, closing.

**Comment by igel-kun** [comment]
Well, I have a working implementation now but, disappointingly, the API requires solving a captcha to find out the wait time to download a file in free mode. As this doubles the amount of captchas required, I don't think it's worth replacing the current implementation... sorry
