### ISSUE TITLE
[RequestFactory] getRequest(): Lock is not released when requesting a 'XDCC' request

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2583]
RequestFactory's Lock is acquired ([RequestFactory.py#L44](https://github.com/pyload/pyload/blob/stable/module/network/RequestFactory.py#L44)) but not released ([RequestFactory.py#L54](https://github.com/pyload/pyload/blob/stable/module/network/RequestFactory.py#L54)) if you request a 'XDCC' request.
The function returns without releasing the lock.

Proper function should be:

``` python
    def getRequest(self, pluginName, account=None, type="HTTP"):
        self.lock.acquire()

        if type == "XDCC":
            req = XDCCRequest(proxies=self.getProxies())

        else:
            req = Browser(self.bucket, self.getOptions())

            if account:
                cj = self.getCookieJar(pluginName, account)
                req.setCookieJar(cj)
            else:
                req.setCookieJar(CookieJar(pluginName))

        self.lock.release()
        return req
```

**Comment by igel-kun** [comment]
In fact, I have a completely rewritten ```XDCCRequest``` network module here, based on jaraco's [python-irc](https://github.com/jaraco/irc) that supports nicks in use, passive DCC, percentage and speed reports, and lots of error management, but it cannot be merged into stable as it's not a plugin.
