### ISSUE TITLE
UptoboxCom plugin broken

### ISSUE THREAD

**Issue by Fullmono** [pyload/pyload#2586]
Hi, 

When trying to download a file hosted by uptobox.com, pyLoad say I need a premium account. Trying through web interface, premium is not mandatory. Probably caused by last interface change made by hoster. 

regards,

**Comment by GammaC0de** [comment]
Sample URL please

**Comment by Fullmono** [comment]
Here you are: http://uptobox.com/uc67zasuuko7

First time you download the file without any problem. When you reach download limit, you have to wait 1 or 2 hours before downloading next file. pyLoad doesn't recognize waiting time and say I need a premium account...

**Comment by Roburetto** [comment]
I can confirm I experienced the same recently.
