### ISSUE TITLE
RapidGator & request Factory vs. wget discrepancy

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#259]
RapidGator seems to respond differently to requests generated by Plugin.req.load and wget:

08.09.2013 13:05:26 DEBUG     RapidgatorNet: URL: http://rapidgator.net/file/18861949
08.09.2013 13:05:26 DEBUG     RapidgatorNet: {'status': 3, 'name': '', 'size': 0}

In the debug zip I find
% grep 404 load_line191.dump.html 
        \<h2\>Error 404\</h2\>

however,
% wget 'http://rapidgator.net/file/18861949'
% grep 404 18861949
%

Looking at both files with a browser uncovers that load_line191.dump.html indeed says "Error 404" while 18861949 says "You have reached your daily downloads limit".

To debug this, I added
```python
        self.logDebug('loading %s' % url)
        self.logDebug('get %s' % get)
        self.logDebug('post %s' % post)
        self.logDebug('ref %s' % ref)
        self.logDebug('just header %s' % just_header)
        self.logDebug('cookies %s' % cookies)
```
before
```python
        res = self.req.load(url, get, post, ref, cookies, just_header, decode=decode)
```
in Plugin.load(), but the request seems just fine:
```
08.09.2013 13:05:26 DEBUG     RapidgatorNet: loading http://rapidgator.net/file/18861949
08.09.2013 13:05:26 DEBUG     RapidgatorNet: get {}
08.09.2013 13:05:26 DEBUG     RapidgatorNet: post {}
08.09.2013 13:05:26 DEBUG     RapidgatorNet: ref True
08.09.2013 13:05:26 DEBUG     RapidgatorNet: just header False
08.09.2013 13:05:26 DEBUG     RapidgatorNet: cookies True
08.09.2013 13:05:26 DEBUG     RapidgatorNet: URL: http://rapidgator.net/file/18861949
08.09.2013 13:05:26 DEBUG     RapidgatorNet: {'status': 3, 'name': '', 'size': 0}
```
What's going on here? Why does RapidGator say 404 for pyload but not for wget? Oh by the way, my browser agrees with wget, so I think it's a problem with pyload.

**Comment by GammaC0de** [comment]
Is this issue still exists? can this issue be closed?

**Comment by igel-kun** [comment]
Yeah, I haven't observed any of this in a while and, tbh, both the pyload codebase and the server scripts probably changed quite a bit meanwhile...
