### ISSUE TITLE
MegaCoNZ links not being parsed/picked from URL

### ISSUE THREAD

**Issue by Roburetto** [pyload/pyload#2592]
I am experiencing an issue where MegaCoNZ (domain https://mega.nz/*) links somehow are not picked/identified while filtering HTML code (both using ParseUrl option from flexget plugin) and also if I paste a portion of html code directly into Pyload's interface and click the "filter url" button.

**Comment by GammaC0de** [comment]
URL and DEBUG log please.

**Comment by Roburetto** [comment]
You will find the requested info here: http://pastebin.com/X1Li4DZT

Includes a sample URL and the log with debug on.

it seems that as it does pick the MegaCoNZ link it picks other SNS links present on the page instead (where to disable these SNS plugins?)

Also, if you if past the html source code directly in Pyload and apply the "filer url" you will seed it picks lots of urls but not the MegaCoNZ  one.

**Comment by GammaC0de** [comment]
Your log does not include any trace of MegaCoNZ in it
Also this log seems to be belong to Flexget, not pyload

**Comment by Roburetto** [comment]
No. That is stuff generated by Pyload.

Flexget passes the URL of an HTML page to PyLoad and Pyload is expected to parse it and just pick the links to the defined hoster(s) (in my case MegaCoNz)*.

If the defined hoster(s) is not found (which is wrongly the case ) then it seems Pyload picks whatever it can recognized instead.

* This process happens silently. Nothing ever shows up for this step in PyLoad's log. And Flexget only "complains" in case of error.

This is working just find for other hosts. There is something either  or the HTML of the page being parsed that prevents if from working in this case.

**Comment by GammaC0de** [comment]
These log lines comes from the [Dereferer.py](https://github.com/pyload/pyload/blob/stable/module/plugins/crypter/Dereferer.py) crypter plugin that handles URLs that contains sub URLs within them (such as `http://www.tumblr.com/share/link?url=http://revistas-e-jornais.blogspot.pt/2016/09/harvard-business-review-brasil-setembro.html`)

Also as far as I know pyLoad is not able to parse HTML files and extract links from them.
Flexget should pass links to hoster URLs such as MegaCoNz not HTML files to parse
So it seems that you have problems in your flexget configuration

**Comment by Roburetto** [comment]
"as far as I know pyLoad is not able to parse HTML files and extract links from them."

I may be wrong. But that is not my understanding.

According to Flexget's pyload plugin [documentation ](http://flexget.com/Plugins/pyload):

"When parse_url is activated pyload will load the html page at the feed url and check it for additional links."

I do not find the hoster names defined anywhere in [Flexget source code](https://github.com/Flexget/Flexget/blob/79d396f5e559067d5548ff10372f1db6f0bfe076/flexget/plugins/output/pyload.py)

**Comment by Roburetto** [comment]
Well, hosters that work seem to use class Hoster(**SimpleHoster**).

While MegaCoNz uses class MegaCoNz(**Hoster**).

**Comment by GammaC0de** [comment]
Well, you should create an issue on Flexget, it you'll manually insert the URL on pyLoad's WebUI, you would see that its working fine, try it.

**Comment by Roburetto** [comment]
Yes. If I insert the link directly it does work.

I will raise the question with Flexget. Thanks

**Comment by GammaC0de** [comment]
:+1:

**Comment by Roburetto** [comment]
It seems Flexget does use PyLoad's "parseURLs" API ability.

parseURLs([html, url]) Parses html content or any arbitaty text for links and returns result of checkURLs.

So Flexget does send the URL to PyLoad for it to recognize hoster links...
