### ISSUE TITLE
Fix for MegaCoNz URLs not being recognized from API request

### ISSUE THREAD

**Issue by Roburetto** [pyload/pyload#2596]
Pertaining the [issue priorly described here](https://github.com/pyload/pyload/issues/2592), in /module/Api.py

replace this line:
`urlmatcher = re.compile(r"((https?|ftps?|xdcc|sftp):((//)|(\\\\))+[\w\d:#@%/;$()~_?\+\-=\\\.&]*)", re.IGNORECASE)`

with this line:
`urlmatcher = re.compile(r"((https?|ftps?|xdcc|sftp):((//)|(\\\\))+[\w\d:#!@%/;$()~_?\+\-=\\\.&]*)", re.IGNORECASE)`

The difference being the addition of a "!". 

It turns out, as it [can be tested](https://regex101.com/#python), that the regex expression was not matching MegaCoNz URLS where a # is followed by a ! such as in:
https://mega.nz/#!ENVCXBgLetcetcetc

Does not seem to affect the recognition of other hosters but can not guarantee it.

**Comment by GammaC0de** [comment]
Well, great find. :wink:

According http://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid/1547940#1547940 this actually should be:
`urlmatcher = re.compile(r"(?:(?:https?|ftps?|xdcc|sftp):(?://|\\\\)+[\w\-\._~:/?#\[\]@!$&'\(\)\*\+,;=]*)", re.IGNORECASE)`

Anyway, this cannot be merged to the 'stable' tree but only to the next version (v0.5)

**Comment by Velociraptor85** [comment]
@GammaC0de is this fixed?

**Comment by GammaC0de** [comment]
@Velociraptor85 This cannot be fixed in the "stable" version because it requires a change in Api.py hence the 0.5 milstone

**Comment by Roburetto** [comment]
I have since found that the code from stackoverflow suggested by GammaC0de does not work unmodified with Pyload.

With Flexget parse_urls on I get; "No suited urls in entry".

My modification works, Perhaps because the original Pyload expression matches multiple groups while the stackoverflow only one?

My Match results:
Full match	0-34	`http://mega.nz/#!ENVCXBgLetcetcetc`
Group 1.	0-34	`http://mega.nz/#!ENVCXBgLetcetcetc`
Group 2.	0-4	`http`
Group 3.	5-7	`//`
Group 4.	5-7	`//`

stackoverflow match results:
(?:(?:https?|ftps?|xdcc|sftp):(?://|\\\\)+[\w\-\._~:/?#\[\]@!$&'\(\)\*\+,;=]*)

**Comment by GammaC0de** [comment]
@Roburetto You are right.
Apparently the URL is expected to be in group 1, I was not aware of that.

I fixed my original post above to include the URL in group 1,.
Please retry and report back.

**Comment by GammaC0de** [comment]
@Roburetto Any news?
