### ISSUE TITLE
PromptFile broken

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#2601]
they made quite an effort to not get parsed, in fact, it seems that they explicitly requested to not be automatically parsed (at least by [Kodi](https://kodi.tv/)) as their html code now includes
```html
<button type="submit" class="gray_btn" onclick='$("#chash").val("bb"+$("#chash").val());//For Kodi devs: we are prepared to rotate our code every hour. So please stop including us in your addons.'>Continue to File</button>
```

**Comment by GammaC0de** [comment]
Sample URL please

**Comment by igel-kun** [comment]
There is a sample URL on the [youtube-dl bugtracker](https://github.com/rg3/youtube-dl/issues/10634); dunno what it is, but it most certainly exhibits the described symptoms.

**Comment by OndrejIT** [comment]
Fixed https://github.com/pyload/pyload/pull/2605 ;)
