### ISSUE TITLE
Why are issue and pull request trackers to massivelly filled? Where's the merging and solving?

### ISSUE THREAD

**Issue by timofonic** [pyload/pyload#2602]
Hello.

What happened to the dear PyLoad? Why are there *TONS* of opened issues and a considerable amount of not merged/resolved PRs?

Kind regards.

**Comment by GammaC0de** [comment]
In the current 'stable' branch of pyLoad, only issues with plugins can be merged.

Any Issue/Bug/Feature Request/Pull Request that involves anything other than plugins (i.e. pyLoad's core) cannot be merged and is scheduled to the next version

See https://github.com/pyload/pyload/milestone/2 and https://github.com/pyload/pyload/pulls?utf8=%E2%9C%93&q=milestone%3A0.5.x%20

@vuolter should have released v0.5 already and then those PRs should been merged.
