### ISSUE TITLE
LinkSnappy plugin

### ISSUE THREAD

**Issue by ghostpi** [pyload/pyload#2604]
Hi. Can you add a plugin for LinkSnappy Premium account? I'm using JDownloader 2 in Ubuntu Mate for Raspberry Pi 2 but java causes high cpu load. I actually installed pyload but it seems that there is no possibilty to integrate LinkSnappy Premium account.

**Comment by OndrejIT** [comment]
Hi,
LinkSnappy premium is in pyload https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/LinksnappyCom.py

**Comment by GammaC0de** [comment]
@OndrejIT Indeed it is in pyload but its a MultiAccount and currently MultiAccount support is broken in pyLoad :disappointed: 

I want to try and fix that.
@ghostpi I will need account information for testing, please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com.
Also, send sample URL for testing

**Comment by ghostpi** [comment]
Thanks for replying! 
@GammaC0de: What information do you need exactly?

**Comment by GammaC0de** [comment]
@ghostpi I need username/password (you can change to a temporary password) (send to the mail above) and a sample URL to test

**Comment by GammaC0de** [comment]
Closing because of no response.
