### ISSUE TITLE
'ascii' codec can't encode character u'\xe8'

### ISSUE THREAD

**Issue by zephura** [pyload/pyload#2606]
Issue with extended characters

the title is "22 - Le mystère de la falaise.MaCh......"

échoué'ascii' codec can't encode character u'\xe8' in position 12: ordinal not in range(128) 0.00 BUpleaCom

`992	24.09.2016 18:06:21	INFO	Download starts: http://uplea.com/dl/B752FF99E1264AC
993	24.09.2016 18:06:21	WARNING	HOSTER UpleaCom[1609]: Plugin may be unstable
994	24.09.2016 18:06:21	INFO	HOSTER UpleaCom[1609]: Grabbing link info...
995	24.09.2016 18:06:21	WARNING	Download failed: http://uplea.com/dl/B752FF99E1264AC | 'ascii' codec can't encode character u'\xe8' in position 12: ordinal not in range(128)
996	24.09.2016 18:06:21	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: http://uplea.com/dl/B752FF99E1264AC (pid:260)
997	24.09.2016 18:06:21	INFO	ADDON UnSkipOnFail: No duplicates found`

not sure if a full debug is necessary, but I can provided if requested

**Comment by GammaC0de** [comment]
Known bug
