### ISSUE TITLE
CatShareNet plugin doesn't work

### ISSUE THREAD

**Issue by mike321** [pyload/pyload#2609]
Hi,

Due to recent hoster changes, the plugin wouldn't work anymore. Shows that account is not "premium", even though it is premium.

Cheers!

**Comment by GammaC0de** [comment]
Account Information is needed for testing, please send account information to nitzo 20th [AT] yahoo [DOT]  com   
Hi,

Due to recent hoster changes, the plugin wouldn't work anymore. Shows that account is not "premium", even though it is premium.

Cheers!

**Comment by GammaC0de** [comment]
Could you explain the screenshot below?
You actually have a negative credit?

![catshare net_-_2016-10-01_00 05 10](https://cloud.githubusercontent.com/assets/11036551/19006913/cd1421a0-876a-11e6-945b-846185dbc96f.png)

**Comment by mike321** [comment]
First from the left - 0.000 Eur,   Premium valid for next 9 days (-0.43GB allowance of 20GB per day)      Logout

**Comment by mike321** [comment]
First from the left - 0.000 Eur, *** Premium valid for next 9 days (-0.43GB allowance of 20GB per day) *** Logout

**Comment by GammaC0de** [comment]
so credit is actually 20GB-0.43GB ?

**Comment by mike321** [comment]
First from the left - 0.000 Eur, *** Premium valid for next 9 days (-0.43GB allowance of 20GB per day) *** Logout

Not negative credit, but negative allowance (GB). It will be renewed on midnight every day. Daily allowance is 20GB,. It allows you to start download if your file is smaller than the allowance left, but if you start 2 or more files smaller than th allowance left, then obviously you will exceed daily allowance and it will be distracted from next day allowance.
