### ISSUE TITLE
Zippyshare plugin not working

### ISSUE THREAD

**Issue by keqas** [pyload/pyload#2610]
Zippyshare plugin stopped working.
Please find attached the corresponding log files (debug mode).
Thanks for your support!

[debug_ZippyshareCom_30-09-2016_11-34-37.zip](https://github.com/pyload/pyload/files/502594/debug_ZippyshareCom_30-09-2016_11-34-37.zip)
[log.txt](https://github.com/pyload/pyload/files/502595/log.txt)

**Comment by led13714** [comment]
probably same issue as in #2608

**Comment by GammaC0de** [comment]
duplicate #2608
