### ISSUE TITLE
ClickNLoad: Could not decrypt key, please install py-spidermonkey or ossp-js

### ISSUE THREAD

**Issue by lordfiSh** [pyload/pyload#2612]
> python systemCheck.py
('Platform:', 'linux2')
('Operating System:', 'posix')
('Python:', '2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]\n')
('pycurl:', 'PycURL/7.19.5 libcurl/7.38.0 GnuTLS/3.3.8 zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3')
('py-crypto:', '2.6.1')
('OpenSSL:', '16.0.0')
('image libary:', '1.1.7')
('pyqt:', 'missing')
pyLoadCore
No Problems detected, pyLoadCore should work fine.

>pip install python-spidermonkey
Requirement already satisfied (use --upgrade to upgrade): python-spidermonkey in /usr/local/lib/python2.7/dist-packages

Can someone help?

**Comment by GammaC0de** [comment]
Help in what?

**Comment by Velociraptor85** [comment]
@lordfiSh could you tell us what you wanted to do, what was expected and what was the error ?

**Comment by lordfiSh** [comment]
I can't use ClickNLoad
> Could not decrypt key, please install py-spidermonkey or ossp-js
but spidermonkey is installed

**Comment by GammaC0de** [comment]
OK,
Please  run `pyLoadCore.py  -s` and show the output of "system check"

**Comment by lordfiSh** [comment]
## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: OK

py-imaging: OK
tesseract: OK

PyQt4: missing

jinja2: OK
beaker: OK
JS engine: missing

System check finished, hit enter to see your status report.

## Status ##

Features available: container decrypting, ssl connection, automatic captcha decryption, Webinterface

Featues missing:

Gui not available
The Graphical User Interface.

no JavaScript engine found
You will need this for some Click'N'Load links. Install Spidermonkey, ossp-js, pyv8 or rhino
You can abort the setup now and fix some dependicies if you want.



> Ah, I systemCheck.py did check for JS engine (?)
I installed rhino via apt and now its working.

**Comment by GammaC0de** [comment]
:+1:
