### ISSUE TITLE
Hoster Simply-Premium.com: TEXTAREA F1 not found

### ISSUE THREAD

**Issue by elgreco29** [pyload/pyload#2613]
Hi,

i´m not able to download from the above hoster. Is there any reason why?

**Comment by GammaC0de** [comment]
@elgreco29 Account information is needed,
Please send user & password (you can set a temporary password if you like) to nitzo2001 \[AT\] yahoo \[DOT\] com.

Also, send sample URL.
Thanks

**Comment by GammaC0de** [comment]
Closing because of no response.
