### ISSUE TITLE
ExternalScripts - Differences between package_extracted and archive_extracted

### ISSUE THREAD

**Issue by Ryan747800B** [pyload/pyload#2617]
I need to run a script after a download is extracted. I see that there're three different connected actions: `package_extracted`, `archive_extracted` and `unrar_finished`. What's the differences between these and what's the best for my purpose?

**Comment by GammaC0de** [comment]
`unrar_finished` is deprecated, you can delete this.
`package_extracted`: all archives in a package has been extracted (because a package can contain multiple links with different archives)
`package_extracted`:called when an archive has been extracted

**Comment by Ryan747800B** [comment]
Thank you!
