### ISSUE TITLE
zippyshare  download does not start

### ISSUE THREAD

**Issue by tomtom38** [pyload/pyload#2620]
All zippyshare links does not start to download
for example
http://www22.zippyshare.com/v/hd041Gn8/file.html
there ist no error in the log file

**Comment by GammaC0de** [comment]
Works fine here...
Please read #2000

**Comment by GammaC0de** [comment]
No response, closing

**Comment by tomtom38** [comment]
I use an zyxel NAS with the included package I reinstall pyload and I replace the update manager file but it doesn t work.
´Here a part of the Log


476	20.10.2016 20:50:46	INFO	HOSTER ZippyshareCom[68]: No errors found
475	20.10.2016 20:50:46	INFO	HOSTER ZippyshareCom[68]: Checking for link errors...
474	20.10.2016 20:50:45	DEBUG	HOSTER ZippyshareCom[68]: LOAD URL http://www101.zippyshare.com/v/jCNGSBMI/file.html | redirect=True | decode=True | cookies=[('zippyshare.com', 'ziplocale', 'en')] | get={} | req=None | just_header=False | post={} | ref=False | multipart=False
473	20.10.2016 20:50:45	INFO	HOSTER ZippyshareCom[68]: Direct download link not found
472	20.10.2016 20:50:45	DEBUG	HOSTER ZippyshareCom[68]: LOAD URL http://www101.zippyshare.com/v/jCNGSBMI/file.html | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=True | post={} | ref=True | multipart=False
471	20.10.2016 20:50:45	INFO	HOSTER ZippyshareCom[68]: Looking for direct download link...
470	20.10.2016 20:50:45	INFO	HOSTER ZippyshareCom[68]: Processing url: http://www101.zippyshare.com/v/jCNGSBMI/file.html
469	20.10.2016 20:50:45	INFO	HOSTER ZippyshareCom[68]: Link status: online
468	20.10.2016 20:50:45	INFO	HOSTER ZippyshareCom[68]: Link size: 150.00 MiB (157286400 bytes)
467	20.10.2016 20:50:45	INFO	HOSTER ZippyshareCom[68]: Link name: pso-sausage.party_bd.1080p.part02.rar
466	20.10.2016 20:50:45	DEBUG	HOSTER ZippyshareCom[68]: Previous link info: {}

464	20.10.2016 20:50:44	INFO	HOSTER ZippyshareCom[68]: Grabbing link info...
463	20.10.2016 20:50:44	WARNING	HOSTER ZippyshareCom[68]: Plugin may be unstable
462	20.10.2016 20:50:44	DEBUG	HOSTER ZippyshareCom[68]: Plugin status: testing
461	20.10.2016 20:50:44	DEBUG	HOSTER ZippyshareCom[68]: Plugin version: 0.89
460	20.10.2016 20:50:44	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
459	20.10.2016 20:50:44	INFO	Download starts: http://www101.zippyshare.com/v/jCNGSBMI/file.html
458	20.10.2016 20:50:44	WARNING	CAPTCHA ZippyshareCom[67]: ReCaptcha | Key pattern not found
457	20.10.2016 20:50:44	INFO	HOSTER ZippyshareCom[67]: Processing as free download...
456	20.10.2016 20:50:44	INFO	HOSTER ZippyshareCom[67]: No errors found

**Comment by GammaC0de** [comment]
This is a partial log, post the log from the moment the processing starts until finished.

**Comment by tomtom38** [comment]
here is the log
[log pyload.txt](https://github.com/pyload/pyload/files/544824/log.pyload.txt)

**Comment by GammaC0de** [comment]
According to the log, you have successfully downloaded the file from zippy...

```
148	21.10.2016 18:17:34	DEBUG	HOSTER ZippyshareCom[99]: DOWNLOAD URL http://www78.zippyshare.com/*** glibc detected *** js: malloc(): memory corruption: 0x00036d00 *** | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
149	21.10.2016 18:17:35	INFO	HOSTER ZippyshareCom[99]: File saved
150	21.10.2016 18:17:35	INFO	HOSTER ZippyshareCom[99]: Checking download...
151	21.10.2016 18:17:35	INFO	HOSTER ZippyshareCom[99]: File is OK
152	21.10.2016 18:17:35	INFO	HOSTER ZippyshareCom[99]: Checking file (with built-in rules)...
153	21.10.2016 18:17:35	INFO	HOSTER ZippyshareCom[99]: Checking file (with custom rules)...
154	21.10.2016 18:17:35	INFO	HOSTER ZippyshareCom[99]: Checking for link errors...
155	21.10.2016 18:17:35	INFO	HOSTER ZippyshareCom[99]: No errors found
156	21.10.2016 18:17:35	INFO	HOSTER ZippyshareCom[99]: No errors found
```

**Comment by tomtom38** [comment]
Yes ok, but the files have only a size from 1.19 kb, the normal file size is 150MB
i can t extract them.
other hoster like share online works fine but this isn t a good option.
with tools such jdownloader the links works fine

**Comment by GammaC0de** [comment]
@tomtom38 Your zippyshare plugin in not up-to-date: you have v0.87, latest is v0.89.

Please delete your `userplugins` dirertory and update your `UpdateManager.py` according to #2000.

**Comment by tomtom38** [comment]
it still doesn t work.
Ich reinstall pyload and I delete the plugin folder I replace the update manager file
pyload do an update and after the restart it is still the same
in according to the log file I have the plug in version 0.89

**Comment by GammaC0de** [comment]
The 1.19 kb file, what does it contain?

**Comment by tomtom38** [comment]
no idea, you can t opend    an incomplete archive

**Comment by GammaC0de** [comment]
Attach the file here.

**Comment by tomtom38** [comment]
http://www72.zippyshare.com/v/NyCecWSM/file.html
you have to download from zippy.
The File doesn t support by github forum

**Comment by GammaC0de** [comment]
@tomtom38 This file cannot be downloaded from zippy's website too (try it), so the problem is not pyload

**Comment by tomtom38** [comment]
This is not the original File this is the downloaded file from pyload. I uploaded this from my NAS.

**Comment by GammaC0de** [comment]
@tomtom38 Can you post a log again?

**Comment by tomtom38** [comment]
sure but it can take a while

**Comment by tomtom38** [comment]
[logfile22.txt](https://github.com/pyload/pyload/files/558964/logfile22.txt)

**Comment by tomtom38** [comment]
I switch to Jdownloader it works fine

**Comment by GammaC0de** [comment]
@tomtom38 Sorry about that, (:
I looked at your log and there is no clue why the plugin is failing.

The plugin work fine for me and I believe it work also for others because no one reported this issue besides you.
I have no clue what's wrong in your setup, I have to connect to your machine to find out.

Again, I am sorry it does not work for you.
Cheers.

**Comment by tomtom38** [comment]
no problem, maybe its a zyxel problem ,
I use for zippy JDownloader.
maybe I try it again with a new installation if I have time
