### ISSUE TITLE
After last update uploadedTo problem 

### ISSUE THREAD

**Issue by szczepan79** [pyload/pyload#2624]
hello 

After update last version i have problem with downloading from premium account

INFO	HOSTER UploadedTo[885]: No errors found
393	17.10.2016 21:48:38	INFO	ACCOUNT UploadedTo: Grabbing account info for user `14223899`...
394	17.10.2016 21:48:38	INFO	HOSTER UploadedTo[885]: Filesize: 2097152 KiB | Traffic left for user `14223899`: 432422256 KiB
395	17.10.2016 21:48:38	INFO	HOSTER UploadedTo[885]: Processing as premium download...
396	17.10.2016 21:48:38	WARNING	HOSTER UploadedTo[885]: Premium download failed | Parse error: Premium download link not found | Plugin may be out of date
397	17.10.2016 21:48:38	INFO	Download restarted: BLOOD-FATHER-1080p.part1.rar | Fallback to free processing 

If you have any suggestion?

**Comment by GammaC0de** [comment]
Have you enabled direct downloads on your UploadedTo account?

**Comment by szczepan79** [comment]
Yes, 
Direct download is enable.

**Comment by GammaC0de** [comment]
Account information is needed,.
Please send account information and sample URL to nitzo2001 \[AT\] yahoo \[DOT\] com.

**Comment by szczepan79** [comment]
Account-ID:14223899 Password: akj4ky6v 


http://uploaded.net/file/m76j354y/LIGHTS-OUT-1080p.part1.rar

**Comment by szczepan79** [comment]
account sended to email

**Comment by GammaC0de** [comment]
Don't know if its related:
```
We received an error from your mail provider that the email address k******l@*.pl is not working. Please contact you mail provider for more informations and after you resolved the problem you can reactivate the email again with the link below.
```

**Comment by GammaC0de** [comment]
Also, I get this meessage when trying to download the sample URL:
`You used too many different IPs, Downloads have been blocked for today.`
Do you share your account with others?

**Comment by szczepan79** [comment]
i will check it. Maybe it is problem with account. Thanx for help

**Comment by szczepan79** [comment]
No i don't share it. I must looking whats going on with it.

**Comment by GammaC0de** [comment]
Ok, so maybe its because of me logging in

**Comment by szczepan79** [comment]
We will see tomorrow

**Comment by GammaC0de** [comment]
:+1: 
Updated UploadedTo plugin with https://github.com/pyload/pyload/commit/b09a85b5c61df501e9dfbae6c23e4009d869620b
After your check, if the problem presists, please post again.
