### ISSUE TITLE
ShareonlineBiz[7]: Plugin may be unstable 

### ISSUE THREAD

**Issue by Loader23** [pyload/pyload#2629]
Hi,

on every part iam Downloading I get this in my log:

WARNING	HOSTER ShareonlineBiz[7]: Plugin may be unstable 

Anyone knows why? Its a fresh install with everything uptodate.

**Comment by GammaC0de** [comment]
This message is shown for ***every*** plugins.
It means that the plugin ***may*** be unstable, i.e. it ***may*** not work correctly as expected.

**Comment by Loader23** [comment]
Oh ok. :-) I did an update from an very old version and there have been alot of changes since then. And this one was the most annoying one :D Thanks for clarification :+1:
