### ISSUE TITLE
Delete archive after extraction setting does not save

### ISSUE THREAD

**Issue by Loader23** [pyload/pyload#2630]
Whenever I restart pyload the above Settings got reverted to false in the ExtractArchive Plugin.

Any advice? Fresh Install and the Debug Log says nothing about it.

**Comment by GammaC0de** [comment]
Do you have write permissions to `plugin.conf`?

**Comment by Loader23** [comment]
Yes, and when i manually edit this value its reverted to False at the next start.

**Comment by GammaC0de** [comment]
@Loader23 you have to stop pyLoad before editing `plugin.conf`

Also, the default value of "Delete archive after extraction" is True, so you can try stopping pyLoad, delete (remember to backup) `plugin.conf` and the start it again.

**Comment by Loader23** [comment]
My pyload was of course stopped before i edited the plugin.conf ;-)

I did now delte the plugin.conf and started pyload and the Setting is on false right after startup. Any other ideas?

**Comment by GammaC0de** [comment]
What version of `ExtractArchive` are you using?

**Comment by Loader23** [comment]
Fresh Install, so its v1.58

**Comment by Ryan747800B** [comment]
Maybe something related to [this issue](https://github.com/pyload/pyload/issues/2623)?

**Comment by Loader23** [comment]
Well, it worked with an older 0.4.9 version. But looks like the same issue...

**Comment by wastez** [comment]
As workarround you can overwrite the Default setting in the addon. (.py file)

**Comment by godfuture** [comment]
have this issue as well. Also hope the new version to come soon :-/

**Comment by Burnout5151** [comment]
I once wrote a shellscript to do the Extracting and deleting and placed it in the package_finished hookfolder. It's a bit limited since it was supposed to be only a temporary solution.but it will work with *.part01.rar, *.part1.rar and *.rar archives. If you want it, I can clean it up and try to send it to you.

**Comment by maulbongo** [comment]
Hi, I also had this Problem and it seems, that it is always overwritte by the default settings, which you can find in ExtractArchive.py here you see this in line 112 `("deltotrash"     , "bool"  , "Move to trash instead delete"          , True                                                                     ),`

If you change this to False and save, it always works.

**Comment by SirMcTod** [comment]
Burnout5151, I would be interested in your script

**Comment by Burnout5151** [comment]
Wow, you just reminded me how long I have been working with that quick-'n'-dirty hack, never improving it because I always thought "the official next version will be here soon"...
oh well, I probably can send the file to you tomorrow

**Comment by SirMcTod** [comment]
That would be great

**Comment by Burnout5151** [comment]
Yeah, as I said: Not pretty: It only supports one password and both the password and target folder are harcoded ( just replace them with your needs)
MO: the script looks for *part01.rar, tries to extract that and deletes the original *part01.rar, *.part02.rar, ... IF SUCCESSFULL,
after that it repeats with *part1.rar and after that *.rar

This has the problem: if you have x.part1.rar, x.part3.rar but you are missing x.part2.rar, it will fail finding *part01.rar, fail, try *.part1.rar, start extracting, fail extracting and then try to unrar *.rar (each file again

If you also have x.part2.rar then extracting x.part1.rar will succeed, x.part1.rar, x.part2.rar and x.part3.rar will be deleted and unrar *.rar will not try to unrar unnecessarily again.

HopeThatHelps
[unrarRm.sh.zip](https://github.com/pyload/pyload/files/842794/unrarRm.sh.zip)

**Comment by SirMcTod** [comment]
Thanks a lot, I'll give it a try soon

**Comment by Burnout5151** [comment]
Updated my post from yesterday: added info on parameters, tidied up a bit

**Comment by GammaC0de** [comment]
Solved.
