### ISSUE TITLE
Support of apache2 for hosting webinterface

### ISSUE THREAD

**Issue by godfuture** [pyload/pyload#2634]
Hello together,
I tried to host pyload with apache2, but the start failed. Is there something missing from pyload side to be hosted on apache2? If not, did someone successfully host it on apache2?

Looking forward!

**Comment by GammaC0de** [comment]
Please explain further.

**Comment by godfuture** [comment]
I wanted to know, if it is possible to host the webinterface with apache2 and if yes, how this would work.

**Comment by GammaC0de** [comment]
I have not tested this personally but see https://github.com/pyload/pyload/issues/1128#issuecomment-224583037

**Comment by godfuture** [comment]
Well, this setup does not mean to host the interface from apache, but to redirect to pyload. I would like to host it directly from apache with fast_cgi.

**Comment by GammaC0de** [comment]
Sorry, pyload is not designed that way.
You have to use apache as a reverse proxy.
