### ISSUE TITLE
Mega.co.nz Parse error: Empty file | Plugin may be out of date 

### ISSUE THREAD

**Issue by CaTzil** [pyload/pyload#2635]
Hi, when ever i try to download any mega links, it always starts with waiting of 5 hours, and when it passes...there is that error: failed, Parse error: Empty file | Plugin may be out of date 
https://mega.nz/#F!D9lzFK6I!oSzjsiDq0EBHzoadFzdC3Q
I am using the latest plugin 0.46 version

**Comment by GammaC0de** [comment]
Unfortunately, these links are too big for free download,
If you try to download them on Mega's website, it will start download and fail at 4%.
I will try with a free account to see if it matters.
![capture2](https://cloud.githubusercontent.com/assets/11036551/19820552/8945c010-9d62-11e6-902f-91d709206969.PNG)

**Comment by CaTzil** [comment]
So it should start the download, as it starts it on the browser

**Comment by GammaC0de** [comment]
Actually, it starts the download and fails immediately, so I'm not sure it even downloaded the 4%.

What's the point if it does not finish?!

**Comment by CaTzil** [comment]
So you say that the plugin works with smaller files?

**Comment by GammaC0de** [comment]
Yes, have used it many times.

If using free account does not help, I will add a message that premium account required.

**Comment by CaTzil** [comment]
Thanx!

**Comment by GammaC0de** [comment]
Added account support, no large file download (chunked download ) yet.
