### ISSUE TITLE
Errors when downloading with SO

### ISSUE THREAD

**Issue by godfuture** [pyload/pyload#2639]
I have installed latest pyload and tried to download with SO. Unfortunately quite often there are errors.
```
417	04.11.2016 20:20:09	INFO	HOSTER ShareonlineBiz[xxx]: Downloading file...
418	04.11.2016 20:20:13	WARNING	Download failed: xxy.part41.rar | 'NoneType' object has no attribute 'package'
419	04.11.2016 20:20:13	ERROR	Error executing hooks: plugin
```

and 

```
320	04.11.2016 20:19:57	INFO	HOSTER ShareonlineBiz[xxxx]: Processing url: http://www.share-online.biz/dl/xxxcffads
321	04.11.2016 20:19:57	INFO	HOSTER ShareonlineBiz[xxxx]: Looking for direct download link...
322	04.11.2016 20:19:57	INFO	HOSTER ShareonlineBiz[xxxx]: Grabbing link info...
323	04.11.2016 20:19:57	WARNING	Download failed: yyyc.part1.rar | 'NoneType' object has no attribute 'id'
324	04.11.2016 20:19:57	ERROR	Error executing hooks: plugin
325	04.11.2016 20:19:57	WARNING	Download failed: yyyc.part42.rar | HTTPRequest instance has no attribute 'cj'
326	04.11.2016 20:19:57	WARNING	Download failed: yyyc.part42.rar | 'NoneType' object has no attribute 'id'
327	04.11.2016 20:19:57	ERROR	Error executing hooks: plugin 
```

**Comment by GammaC0de** [comment]
@godfuture Is this a new installation?

**Comment by godfuture** [comment]
The first time, I have deleted userplugins and then I have reinstalled pyload install folder from stable.

**Comment by GammaC0de** [comment]
Please read #2000

**Comment by lukastribus** [comment]
@GammaC0de this is not very straightforward, could the "proper" installation please be documented in the actual repository, like README or maybe a new file like INSTALLATION?

Documenting the "proper" installation in a closed github issue, that is only referenced after filing an new issue seems very inefficient, for the user and especially for yourself.

**Comment by GammaC0de** [comment]
@lukastribus Indeed you are right about this.
The v0.4.9 release packages are very old (14 Dec 2011) and many things has changed since then.

Next version (v0.5) should be released soon and would be installed via pip - this would easy the installation procedure.

You didn't say if pyLoad is working for you now...

**Comment by lukastribus** [comment]
Grea, thanks.

I'm not the OP here, I just saw this here a few times.

**Comment by GammaC0de** [comment]
@godfuture Does it work now?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by godfuture** [comment]
sorry, I was on business travel. I just tried what you posted and it worked. I guess it is quite okay now. Thanks a lot!

**Comment by GammaC0de** [comment]
:+1:
