### ISSUE TITLE
Problem with uploaded

### ISSUE THREAD

**Issue by szczepan79** [pyload/pyload#2642]
I have problem with some files:

http://uploaded.net/file/7faiimfc/S0ns.0f.4n4rchy.S02E01.MULTi.720p.rar
log info:

08.11.2016 08:04:58	INFO	Download starts: http://uploaded.net/file/7q66fm4x/S0ns.0f.4n4rchy.S02E02.MULTi.720p.rar
33	08.11.2016 08:04:58	WARNING	HOSTER UploadedTo[956]: Plugin may be unstable
34	08.11.2016 08:04:58	WARNING	Download failed: http://uploaded.net/file/7q66fm4x/S0ns.0f.4n4rchy.S02E02.MULTi.720p.rar | 'NoneType' object has no attribute 'get_info'
35	08.11.2016 08:04:58	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: http://uploaded.net/file/7q66fm4x/S0ns.0f.4n4rchy.S02E02.MULTi.720p.rar (pid:176)
36	08.11.2016 08:04:58	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
I checked this an I got "File can be downloaded by premium users only".
I did not get "'NoneType' object has no attribute 'get_info'" error.
Is the a new installation?

**Comment by szczepan79** [comment]
Ok! After restart Pyload everything starts working Fine.
THX for replay.
