### ISSUE TITLE
video files corrupt after downloading

### ISSUE THREAD

**Issue by mpopp** [pyload/pyload#2643]
Downloaded .mp4 files via direct link and linkcrypt.ws plugin. Also tried an mkv file.

All of these play for a few minutes, then just stop. When downloading the same files via chrome directly, everything is fine.
When downloading via the YouTube plugin, files seem to be ok as well (tested with a 30 min video and was able to playback the whole file).
I'm starting the downloads via webinterface on my raspberrypi to a shared folder (raspberry is the samba server of an ntfs hdd).
Accessing the files via WIndows and Android made the problems occur. Didn't try to playback the files on the raspberry directly.

In case of the direct downloads, no errors are shown.
In case of the linkcrypt.ws download, a CRC error is shown after the download.

Here is the log part for the direct download (changed the link names to not link to an actual existing file in this issue. The original links of course point to existing files):

09.11.2016 19:11:56	INFO	Download starts: http://dl.chinurarete-subs.org/downloads/xyz/%5bChinurarete_Subs%5dxyz_asdf_8BIT/%5bChinurarete_Subs%5dxyz_asdf_Folge_02_8BIT%20%5b7A2AD073%5d.mp4
780	09.11.2016 19:11:56	WARNING	HOSTER BasePlugin[57]: Plugin may be unstable
781	09.11.2016 19:11:56	INFO	HOSTER BasePlugin[57]: Grabbing link info...
782	09.11.2016 19:11:56	INFO	HOSTER BasePlugin[57]: Link name: [Chinurarete_Subs]xyz_asdf_Folge_02_8BIT [7A2AD073].mp4
783	09.11.2016 19:11:56	INFO	HOSTER BasePlugin[57]: Link size: N/D
784	09.11.2016 19:11:56	INFO	HOSTER BasePlugin[57]: Link status: starte
785	09.11.2016 19:11:56	INFO	HOSTER BasePlugin[57]: Processing url: http://dl.chinurarete-subs.org/downloads/xyz/%5bChinurarete_Subs%5dxyz_asdf_8BIT/%5bChinurarete_Subs%5dxyz_asdf_Folge_02_8BIT%20%5b7A2AD073%5d.mp4
786	09.11.2016 19:14:28	INFO	HOSTER BasePlugin[57]: File saved
787	09.11.2016 19:14:28	INFO	HOSTER BasePlugin[57]: Checking download...
788	09.11.2016 19:14:28	INFO	HOSTER BasePlugin[57]: File is OK
789	09.11.2016 19:14:28	INFO	Download finished: [Chinurarete_Subs]xyz_asdf_Folge_02_8BIT [7A2AD073].mp4

**Comment by GammaC0de** [comment]
I cloud not understand what the problem is.
Please describe your problem in two sentences.

**Comment by mpopp** [comment]
When I download a mp4 or mkv file via pyload it appears to be corrupted after download is complete. 
When I download the same file via Chrome, it is valid.

**Comment by GammaC0de** [comment]
OK,
URL please.

**Comment by mpopp** [comment]
http://trailers.divx.com/divx_prod/divx_plus_hd_showcase/Sintel_DivXPlus_6500kbps.mkv

It played until 6:03 and then just stopped.

**Comment by mpopp** [comment]
But this seems to happen for all mp4 and mkv files downloaded via pyload, not only for that specific link.

**Comment by GammaC0de** [comment]
I downloaded this file with Firefox and with pyLoad and the files are the same.

How did you installed your pyLoad (see #2000)?

**Comment by mpopp** [comment]
Definitely didn't follow #2000. Followed the instructions I found in a tutorial on a blog (don't remember the url). I'm going to do a fresh install following #2000 tomorrow and let you know if this resolved my issue.

**Comment by GammaC0de** [comment]
:+1:

**Comment by mpopp** [comment]
Reinstalling by following #2000 worked! seems something was broken with the way I installed (i found the tutorial again and saw that in the tutorial pyload was pulled directly from the git repo).

Thx a lot for your help :)
