### ISSUE TITLE
pyLoadCore.py doesn't recognize Python-Pillow on Entware-NG

### ISSUE THREAD

**Issue by digimon04** [pyload/pyload#2645]
Pillow has been installed with the following command:
opkg install pillow

When running pyLoadCore.py after install, it does not recognize python-imaging. The system check reports py-imaging: missing and feature missing report no Captcha Recognition available.

Since Python-imglib has been retired, Pillow is the only option available. I hope Pyload can support Pillow.

Thanks.

**Comment by GammaC0de** [comment]
Have you tried `pip install pillow` ?

**Comment by digimon04** [comment]
I tried that today with:
opkg install python-pip

and then:
pip install pillow

it reports:

The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): pillow in /tmp/mnt/sda1/entware/lib/python2.7/site-packages
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

The pyLoadCore.py still reports py-imaging: missing and feature missing report no Captcha Recognition available.

**Comment by GammaC0de** [comment]
Try:
```
sudo pip install --upgrade pip
sudo pip install pillow
```

**Comment by GammaC0de** [comment]
Will close if no response.

**Comment by Velociraptor85** [comment]
@GammaC0de I think we had something similar lately where the guy even had a small fix because pillow was not recognized corret even via the check command. Do you remember? I have not found the Issue.

**Comment by GammaC0de** [comment]
#2572

**Comment by digimon04** [comment]
I still need more time because I am having trouble installing pillow using pip. Thanks.

**Comment by digimon04** [comment]
I have installed pillow using "opkg install pillow". When I "python systemCheck.py", it shows;

> ('image libary:', 'missing')
> 
> #####   System Status   #####
> 
> ##  pyLoadCore  ##
> The system check has detected some errors:
> 
> Please install py-imaging/pil to use Hoster, which uses captchas.

With reference to #2572, I modify the systemCheck.py to add "from PIL" in front of all "import Image" entries.

When I "python systemCheck.py", it shows:

> ('image libary:', '1.1.7')
> 
> #####   System Status   #####
> 
> ##  pyLoadCore  ##
> No Problems detected, pyLoadCore should work fine.

Then, I tried "python pyLoadCore.py -s", Putty shows:

> ## System Check ##
> Python Version: OK
> pycurl: OK
> sqlite3: OK
> 
> pycrypto: OK
> py-OpenSSL: OK
> 
> py-imaging: missing
> 
> Featues missing:
> 
> no Captcha Recognition available
> Only needed for some hosters and as freeuser.

I don't know why systemCheck.py can correctly recognize Pillow while pyLoadCore.py cannot. Is Pillow working in this case ?

**Comment by GammaC0de** [comment]
Change [setup.py#L221](https://github.com/pyload/pyload/blob/stable/module/setup.py#L221) to:
```python
 pil = self.check_module("PIL")
```

**Comment by digimon04** [comment]
I have changed it as you told and now Pyload recognizes Pillow.

## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: OK

py-imaging: OK
tesseract: OK

PyQt4: missing

jinja2: OK
beaker: OK
JS engine: OK

System check finished, hit enter to see your status report.

## Status ##

Features available: container decrypting, ssl connection, automatic captcha decryption, Webinterface, extended Click'N'Load

**Comment by willoz88** [comment]
Confirmed pillow is correctly detected

**Comment by GammaC0de** [comment]
:+1:

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/45a0807e6f2d5a73a44dc548edc9df3609e9601c
