### ISSUE TITLE
NitroFlareCom plugin failed

### ISSUE THREAD

**Issue by alex9434** [pyload/pyload#2651]
Dear all,

I get the following error message with the NitroFlareCom plugin:

failed'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128) 0.00 BNitroflareCom

Any ideas?

Regards,
Alex

**Comment by GammaC0de** [comment]
@alex9434 This is a known bug when the file name contains unicode characters (see https://github.com/pyload/pyload/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20codec%20can%27t%20decode)

Unfortunately, there is no proper solution yet.

**Comment by GammaC0de** [comment]
Closing since it's a duplicate.
