### ISSUE TITLE
ReCaptcha - Key Pattern not found / Download does not start

### ISSUE THREAD

**Issue by PrimeF** [pyload/pyload#2652]
Hello,

trying to download a file from Zippyshare, but it does not work, as the downloads fails before it even starts.

Here the logs I see in the web interface:
`30.11.2016 00:23:43 INFO      Download starts: part10.rar
30.11.2016 00:23:43 WARNING   HOSTER ZippyshareCom[18]: Plugin may be unstable
30.11.2016 00:23:43 INFO      HOSTER ZippyshareCom[18]: Grabbing link info...
30.11.2016 00:23:44 INFO      HOSTER ZippyshareCom[18]: Link name: part10.rar
30.11.2016 00:23:44 INFO      HOSTER ZippyshareCom[18]: Link size: 125.77 MiB (131879403 bytes)
30.11.2016 00:23:44 INFO      HOSTER ZippyshareCom[18]: Link status: online
30.11.2016 00:23:44 INFO      HOSTER ZippyshareCom[18]: Processing url: http://www73.zippyshare.com/xxxxxx/file.html
30.11.2016 00:23:44 INFO      HOSTER ZippyshareCom[18]: Looking for direct download link...
30.11.2016 00:23:44 INFO      HOSTER ZippyshareCom[18]: Direct download link not found
30.11.2016 00:23:44 INFO      HOSTER ZippyshareCom[18]: Checking for link errors...
30.11.2016 00:23:44 INFO      HOSTER ZippyshareCom[18]: No errors found
30.11.2016 00:23:44 INFO      HOSTER ZippyshareCom[18]: Processing as free download...
30.11.2016 00:23:44 WARNING   CAPTCHA ZippyshareCom[18]: ReCaptcha | Key pattern not found
30.11.2016 00:23:45 INFO      HOSTER ZippyshareCom[18]: Downloading file...
30.11.2016 00:23:45 WARNING   Download failed: part10.rar | downloading
30.11.2016 00:23:45 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: part10.rar (pid:12)
30.11.2016 00:23:45 INFO      ADDON UnSkipOnFail: No duplicates found
`

Could someone check over this please.

**Comment by GammaC0de** [comment]
Please enable DEBUG mode, retry the download and post the log again.
Also, posting the URL would help.

**Comment by PrimeF** [comment]
`809	30.11.2016 01:09:44	DEBUG	All downloads processed
808	30.11.2016 01:09:44	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
807	30.11.2016 01:09:44	INFO	ADDON UnSkipOnFail: No duplicates found
806	30.11.2016 01:09:44	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Amigos.part08.rar (pid:9)
805	30.11.2016 01:09:44	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
804	30.11.2016 01:09:44	WARNING	Download failed: Amigos.part08.rar | downloading
803	30.11.2016 01:09:44	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
802	30.11.2016 01:09:44	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
801	30.11.2016 01:09:44	DEBUG	HOSTER ZippyshareCom[1]: DOWNLOAD URL http://www88.zippyshare.com/d/ZtWjDaEX/96624/Amigos.part08.rar | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
800	30.11.2016 01:09:44	INFO	HOSTER ZippyshareCom[1]: Downloading file...
799	30.11.2016 01:09:43	WARNING	CAPTCHA ZippyshareCom[1]: ReCaptcha | Key pattern not found
798	30.11.2016 01:09:43	INFO	HOSTER ZippyshareCom[1]: Processing as free download...
797	30.11.2016 01:09:43	INFO	HOSTER ZippyshareCom[1]: No errors found
796	30.11.2016 01:09:43	INFO	HOSTER ZippyshareCom[1]: Checking for link errors...
795	30.11.2016 01:09:43	DEBUG	HOSTER ZippyshareCom[1]: LOAD URL http://www88.zippyshare.com/v/ZtWjDaEX/file.html | redirect=True | cookies=[('zippyshare.com', 'ziplocale', 'en')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
794	30.11.2016 01:09:43	INFO	HOSTER ZippyshareCom[1]: Direct download link not found
793	30.11.2016 01:09:43	DEBUG	HOSTER ZippyshareCom[1]: LOAD URL http://www88.zippyshare.com/v/ZtWjDaEX/file.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
792	30.11.2016 01:09:43	INFO	HOSTER ZippyshareCom[1]: Looking for direct download link...
791	30.11.2016 01:09:43	INFO	HOSTER ZippyshareCom[1]: Processing url: http://www88.zippyshare.com/v/ZtWjDaEX/file.html
790	30.11.2016 01:09:43	INFO	HOSTER ZippyshareCom[1]: Link status: online
789	30.11.2016 01:09:43	INFO	HOSTER ZippyshareCom[1]: Link size: 150.00 MiB (157286400 bytes)
788	30.11.2016 01:09:43	INFO	HOSTER ZippyshareCom[1]: Link name: Amigos.part08.rar
787	30.11.2016 01:09:43	DEBUG	HOSTER ZippyshareCom[1]: Previous link info: {}
786	30.11.2016 01:09:43	DEBUG	HOSTER ZippyshareCom[1]: Link info: {'status': 2, 'hash': {}, 'name': u'Amigos.part08.rar', 'url': u'http://www88.zippyshare.com/v/ZtWjDaEX/file.html', 'pattern': {'S': u'150', 'U': u'MB', 'KEY': u'ZtWjDaEX', 'N': u'Amigos.part08.rar'}, 'size': 157286400}
785	30.11.2016 01:09:42	INFO	HOSTER ZippyshareCom[1]: Grabbing link info...
784	30.11.2016 01:09:42	WARNING	HOSTER ZippyshareCom[1]: Plugin may be unstable
783	30.11.2016 01:09:42	DEBUG	HOSTER ZippyshareCom[1]: Plugin status: testing
782	30.11.2016 01:09:42	DEBUG	HOSTER ZippyshareCom[1]: Plugin version: 0.89
781	30.11.2016 01:09:42	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
780	30.11.2016 01:09:42	INFO	Download starts: http://www88.zippyshare.com/v/ZtWjDaEX/file.html
779	30.11.2016 01:09:42	INFO	Added package test containing 1 links`

**Comment by GammaC0de** [comment]
I have tested the above URL and it works fine with ZippyshareCom plugin version: 0.89.

What plugin version are you using?

**Comment by PrimeF** [comment]
As in pyload/module/plugins/hoster/ZippyshareCom.py, I have version 0.89 too.
`DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'h
Nov 30 22:08:08 raspberrypi python[1621]: ooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (
Nov 30 22:08:08 raspberrypi python[1621]: u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
Nov 30 22:08:08 raspberrypi python[1621]: 30.11.2016 22:08:08 INFO      ADDON UpdateManager: All plugins are up to date!
`
When I launch systemctl status pyload, after pyload was started I get those output. Is this normal?

**Comment by GammaC0de** [comment]
>Requested deletion of plugins

It does this every time?

**Comment by PrimeF** [comment]
Yes tried now to do systemctl restart pyload a couple of times and every time I get those message.
Another message I get is the following, which I forgot to post before:
`Nov 30 22:41:03 raspberrypi python[15063]: 30.11.2016 22:41:03 INFO      ADDON XFileSharing: Auto-discover new crypters
Nov 30 22:41:03 raspberrypi python[15063]: 30.11.2016 22:41:03 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
Nov 30 22:41:03 raspberrypi python[15063]: 30.11.2016 22:41:03 INFO      pyLoad is up and running
Nov 30 22:41:03 raspberrypi python[15063]: 30.11.2016 22:41:03 INFO      ADDON UpdateManager: pyLoad is up to date!
Nov 30 22:41:03 raspberrypi python[15063]: 30.11.2016 22:41:03 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
`

**Comment by PrimeF** [comment]
I found the error. I created a unix user for pyload and launched the pyload.service using this user. Although it seems this created some sort of problems. For this reason I'm now using the root user and all is working well. Do you know if it is a problem running pyload using root? Because on some websites it is recommended to use another unix user for it? Are there any downsides?

**Comment by GammaC0de** [comment]
@PrimeF There shouldn't be any downside when using another Unix user.
You should take care of file access permissions to pyLoad's installation, config and downloads folders if you use another user.

**Comment by GammaC0de** [comment]
Closing.
