### ISSUE TITLE
ExternalScripts: Event all_packages_finished?

### ISSUE THREAD

**Issue by superalze** [pyload/pyload#2655]
I'd like to move all files into a folder once all packages are downloaded (and extracted for those applicable).

Is there an event called "all_packages_finished" or "queue_empty" or "pyload_idle"? Could I build it myself? Where in the code would it need to go? Thanks!

**Comment by GammaC0de** [comment]
Scripts in `all_downloads_processed` are called when pyLoad gets idle.

**Comment by GammaC0de** [comment]
Closing this.
