### ISSUE TITLE
MultiUp.org Crypter not grabbing links

### ISSUE THREAD

**Issue by youlJunior** [pyload/pyload#2656]
In MultiUpOrg.py Crypter, the pattern for detecting links to decrypt is : 

```python
__pattern__ = r'http://(?:www\.)?multiup\.org/(en|fr)/(?P<TYPE>project|download|mirror)/\w+(/\w+)?'
```

But I got links like that : 

http://www.multiup.org/download/e70b2e7879f3f314500d2b67d54a67e6/the.simpsons.s25e01.french.hdtv.x264-panzer.mp4

As it doesn't contain "en" or "fr" after "multiup.org/", the crypter doesn't decrypt links.

I had to modify the regex like that, and it works : 

```python
__pattern__ = r'http://(?:www\.)?multiup\.org/(en/|fr/)?(?P<TYPE>project|download|mirror)/\w+(/\w+)?'
```

PS : Is there a way I could filter links grabbed from multiup.org, to only launch 1 download, from my preferred hoster ?

**Comment by GammaC0de** [comment]
>PS : Is there a way I could filter links grabbed from multiup.org, to only launch 1 download, from my preferred hoster ?

Now you can:
Go to the plugin config and specify priority hosts and ignored hosts.

**Comment by youlJunior** [comment]
@GammaC0de you're the boss :+1:
