### ISSUE TITLE
web interface prroblem

### ISSUE THREAD

**Issue by mrgspeed** [pyload/pyload#2657]
i completely installed and configured pyload on my router (padavan firmware)
when i sign into web interface i can see that its not loading completely:

https://postimg.org/image/u67ulp1k1
https://postimg.org/image/51gu8a23l/

and i already tried uninstall then install and using different browser but the result is same

**Comment by mrgspeed** [comment]
by the way; sorry for bad english!

**Comment by GammaC0de** [comment]
Those images seems like a normal pyLoad webinterface...

**Comment by mrgspeed** [comment]
@GammaC0de 
so why config section is empty ?!
