### ISSUE TITLE
'ascii' codec can't decode byte 0xc3 in position 26

### ISSUE THREAD

**Issue by susnux** [pyload/pyload#2659]
This error occurs if the package name (or folder name?) contains Unicode (e.g. 'ü').
If I change that names it works like it should.
Using current stable branch.

**Comment by OndrejIT** [comment]
Try my fork, branch CS
https://github.com/OndrejIT/pyload

**Comment by BKPepe** [comment]
Bug is still present. :(

> 02.03.2017 20:40:44 WARNING   HOSTER WebshareCz[40]: Plugin may be unstable
> 02.03.2017 20:40:44 INFO      ACCOUNT WebshareCz: Grabbing account info for user `Pep*******`...
> 02.03.2017 20:40:44 INFO      HOSTER WebshareCz[40]: Grabbing link info...
> 02.03.2017 20:40:44 INFO      HOSTER WebshareCz[40]: Link name: MsiMd13.rar
> 02.03.2017 20:40:44 INFO      HOSTER WebshareCz[40]: Link size: 255.53 MiB (267943294 bytes)
> 02.03.2017 20:40:44 INFO      HOSTER WebshareCz[40]: Link status: online
> 02.03.2017 20:40:44 INFO      HOSTER WebshareCz[40]: Processing url: https://webshare.cz/file/1Cq7gx6EC5/msimd13-rar
> 02.03.2017 20:40:44 INFO      HOSTER WebshareCz[40]: Looking for direct download link...
> 02.03.2017 20:40:44 INFO      HOSTER WebshareCz[40]: Direct download link not found
> 02.03.2017 20:40:44 INFO      HOSTER WebshareCz[40]: Checking for link errors...
> 02.03.2017 20:40:44 INFO      HOSTER WebshareCz[40]: No errors found
> 02.03.2017 20:40:44 INFO      HOSTER WebshareCz[40]: Processing as premium download...
> 02.03.2017 20:40:44 INFO      ACCOUNT WebshareCz: Grabbing account info for user `Pep*******`...
> 02.03.2017 20:40:45 INFO      HOSTER WebshareCz[40]: Downloading file...
> 02.03.2017 20:40:45 WARNING   Download failed: MsiMd13.rar | 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
> 02.03.2017 20:40:45 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: MsiMd13.rar (pid:7)
> 02.03.2017 20:40:45 INFO      ADDON UnSkipOnFail: No duplicates found

**Comment by Burnout5151** [comment]
See also  #2286
