### ISSUE TITLE
Plugin Error with Premium Uploaded.to

### ISSUE THREAD

**Issue by PlanetDyna** [pyload/pyload#2663]
Hey Folks,

is just getting started with PyLoad on my Raspberry Pi. The PyLoad Webinterface works finde, but it display my Premium Account as "no".

Beste regards
PD

**Comment by GammaC0de** [comment]
@PlanetDyna Please read  https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-%28RaspberryPi%29 for Raspberry Pi specific instructions or #2000 for more general ones.

**Comment by PlanetDyna** [comment]
@GammaC0de: Thank you - PyLoad works! But I can not remove the created Dirs via FTP - Permission denied. You probably have an idea?

**Comment by GammaC0de** [comment]
I'd better use putty to do this directly with `sudo rmdir`

**Comment by PlanetDyna** [comment]
I run Open Media Vault on my Pi - maybe I have to edit the Permission on the PyLoad Webinterface?

**Comment by GammaC0de** [comment]
>But I can not remove the created Dirs via FTP - Permission denied. You probably have an idea?

Please explain the problem clearly

**Comment by GammaC0de** [comment]
No response, closing.
