### ISSUE TITLE
XMPP interface doesn't notify pending captchas

### ISSUE THREAD

**Issue by jldiaz** [pyload/pyload#2666]
After configuring XMPP plugin, I can check that it is working because I receive a message every time a package is finished. However, I don't receive a message when a captcha is pending. 

I'm not familiar with pyload plugin architecture, but I revised the code of [XMPP.py][3] and didn't found any hook for captchas. The only reference is a [configuration variable][1], which is set to `True` (this option is also set to True in plugin config). However, for the "package finished" event I can see that there is a [callback][2] in the XMPP plugin. This makes me wonder if such a callback is missing for the captcha event.

Anyway, I can recall that in previous versions of pyload this feature worked correctly, but I'm unable to find out which change did break it.

[1]: https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/XMPP.py#L26
[2]: https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/XMPP.py#L71
[3]: https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/XMPP.py

**Comment by GammaC0de** [comment]
Hi,
XMMP class inherents from [IRC](https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/IRC.py)  class.
[IRC.py](https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/IRC.py) has `captcha_task()` event handler that handles the captcha request.

`captcha_task()`  relies on www.freeimagehosting.net for storing the captcha image so maybe the problem relies here.

Please send DEBUG log.

**Comment by jldiaz** [comment]
Hi,

Thank you for the pointer. In fact, there are some problems with the code which deals with <www.freeimagehosting.net>. I visited the site with a browser, uploaded an image and inspected the html of the response. Apparently it has changed since the IRC plugin was written, because the [regexp used in the plugin][1] doesn't match. From that regexp it looks like in the past the page provided some kind of bbcode to use the image, but this is no longer the case. A possible replacement for the regexp which works in the current version of the page could be:

```
url = re.search(r"src='([^']+)'", html).group(1)
```

But there is another problem. The python code does not receive the same HTML code that can be seen through the browser. The POST is directed at `http://www.freeimagehosting.net/upload.php`, but it should be `http://www.freeimagehosting.net/upl.php`, but even after changing it, the HTML received after the post is the front page of the site, instead of the one with the uploaded image. 

In the end I changed the code to a simple text notification "Captcha is waiting", and now it works.



[1]: https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/IRC.py#L83

**Comment by jldiaz** [comment]
Ok, I figured out what the problem was. The current `captcha_task()` in IRC class is broken due to three reasons:

1) The address to POST to should be `http://www.freeimagehosting.net/upl.php` instead of `http://www.freeimagehosting.net/upload.php`
2) The name of the POST parameter should be `file` instead of `attached`
3) The regexp to retrieve the URL of the uploaded image should be `r"src='([^']+)'"` instead of `r'\[img\]([^\[]+)\[/img\]\[/url\]'
