### ISSUE TITLE
share online some links of multipart archive won't download free "server is full"

### ISSUE THREAD

**Issue by Lalarian** [pyload/pyload#2667]
Hello!

There are some links of multipart archives that pyload won't download for days and countless tries as a free user. It repeats saying "failed Server is full" over and over. But when trying to download those files through the website, the download everytime is working instantly.

Two examples of such not working in pyload links:
http://www.share-online.biz/dl/AD7A37FNDL
http://www.share-online.biz/dl/L6HT37FNVDPV

All the other links of same archive are working fine (for example http://www.share-online.biz/dl/6APU27FNJI54)

Thank you and wish you nice holidays! :)

**Comment by GammaC0de** [comment]
@Lalarian I tried those links and they worked fine for me.
Is this a new installation?

**Comment by Lalarian** [comment]
No, it's running for months. It was downloading the other files of the
archive right before and after those, that it wouldn't.

2016-12-27 23:23 GMT+01:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
@Lalarian Maybe you've exhausted your credit, please provide DEBUG log with the problem.

**Comment by Lalarian** [comment]
Hello!

I have now copied the log, and I have seen that I was wrong!
The link I have tried in the webbrowser actually isn't the same, although it's the same file and part of the same archive.

`15	28.12.2016 17:15:09	INFO	HOSTER ShareonlineBiz[372]: Grabbing link info...
16	28.12.2016 17:15:09	DEBUG	HOSTER ShareonlineBiz[372]: Link info: {'status': 2, 'hash': {}, 'name': 'Resident.Evil.Archives.Resident.Evil.Zero.part06.rar', 'url': u'http://www.share-online.biz/dl/3MKEPSTNOJ5', 'pattern': {'ID': u'3MKEPSTNOJ5'}, 'size': 202831872, 'md5': 'fac030c4c8398538413a17d6533af3db', 'fileid': '3MKEPSTNOJ5'}
17	28.12.2016 17:15:09	DEBUG	HOSTER ShareonlineBiz[372]: Previous link info: {}
18	28.12.2016 17:15:09	INFO	HOSTER ShareonlineBiz[372]: Link name: Resident.Evil.Archives.Resident.Evil.Zero.part06.rar
19	28.12.2016 17:15:09	INFO	HOSTER ShareonlineBiz[372]: Link size: 193.44 MiB (202831872 bytes)
20	28.12.2016 17:15:09	INFO	HOSTER ShareonlineBiz[372]: Link status: online
21	28.12.2016 17:15:09	INFO	HOSTER ShareonlineBiz[372]: Processing url: http://www.share-online.biz/dl/3MKEPSTNOJ5
22	28.12.2016 17:15:09	INFO	HOSTER ShareonlineBiz[372]: Looking for direct download link...
23	28.12.2016 17:15:09	DEBUG	HOSTER ShareonlineBiz[372]: LOAD URL http://www.share-online.biz/dl/3MKEPSTNOJ5 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
24	28.12.2016 17:15:09	INFO	HOSTER ShareonlineBiz[372]: Direct download link not found
25	28.12.2016 17:15:09	DEBUG	HOSTER ShareonlineBiz[372]: LOAD URL http://www.share-online.biz/dl/3MKEPSTNOJ5 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
26	28.12.2016 17:15:09	INFO	HOSTER ShareonlineBiz[372]: Processing as free download...
27	28.12.2016 17:15:09	DEBUG	HOSTER ShareonlineBiz[372]: WAIT set to timestamp 1482945313.802033 | Previous waitUntil: 0.000000
28	28.12.2016 17:15:09	INFO	HOSTER ShareonlineBiz[372]: Waiting 3 seconds...
29	28.12.2016 17:15:13	DEBUG	HOSTER ShareonlineBiz[372]: LOAD URL http://www.share-online.biz/dl/3MKEPSTNOJ5/free/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'dl_free': '1', 'choice': 'free'} | ref=True | just_header=False
30	28.12.2016 17:15:13	ERROR	HOSTER ShareonlineBiz[372]: full | Keine freien Slots für Free User! `

Sorry for the inconvinience and thank you for support!

:)

**Comment by GammaC0de** [comment]
![capture](https://cloud.githubusercontent.com/assets/11036551/21529343/6dbc681c-cd41-11e6-936c-9414473b9a04.PNG)

**Comment by Burnout5151** [comment]
Yes, it seems shareonline does this with selected files to incentivise people to buy premium. You either have to buy premium, DL from a different hoster or keep on trying (can take weeks).

So this is not a PyLoad bug and can be closed by @Velociraptor85  or @GammaC0de

**Comment by Lalarian** [comment]
I had tried these files for some days. You mean that there is a chance for them to become available to free users after some weeks? Did you experience this for yourself or is it just an estimation?
Thanks.

**Comment by GammaC0de** [comment]
@Lalarian That means that ShareOnline decided that this file will not be available for free users (I guess because they want to encourage you to buy premium) for unknown duration.

If they decide to make it available again is up to them to decide.

Again, there is nothing that pyload can do about it, so it is not considered a bug.

**Comment by Burnout5151** [comment]
@Lalarian don't take my word for it, but my experience was:
After several weeks of pushing "restart failed" twice per day, it "just worked" once. Of course I didn't try to download the file again, so I can't tell if the file was accessible from then on, or if I was lucky to hit a small timewindow.

**Comment by Lalarian** [comment]
Hello!
I understood this.
My question was meant only in regards to shareonline procedure (yes, a little off topic). But related to Burnout5151 saying that it might help waiting for some weeks. I just want to confirm if I really can be shure that shareonline would unlock such files some time later.

**Comment by Burnout5151** [comment]
@Lalarian : Glad I could help,
yes this got a little-bit off-topic but I don't think it got out of hand. So if we finish it here I guess it's okay ;-)
