### ISSUE TITLE
rockfile.eu

### ISSUE THREAD

**Issue by maxking71** [pyload/pyload#2671]
Hello
I apologize, I'm new, I do not find in the server list rockfile.eu
you can enter it?
thank you very much

**Comment by maxking71** [comment]
thanks to you
I see an added plugin
but as the drain and as I insert it in the web interface?

**Comment by GammaC0de** [comment]
I'm sorry, I cannot understand what you're trying to say.

No plugin was added yet.

**Comment by maxking71** [comment]
ah ok
plan to add short rockfile.eu?

**Comment by GammaC0de** [comment]
Will try to.

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/ab8231cc4e81fc394013f9fc34a986870de4dedf
Requires [patched HTTPRequest.py](https://github.com/pyload/pyload/files/683638/_HTTPRequest__Fix_empty_BadHeader_content.zip) and `CloudFlareDdos` plugin active.

**Comment by maxking71** [comment]
Many thanks
forgive me, I'm new, how do I install this patch?
I use openmediavault

**Comment by GammaC0de** [comment]
👍 
So you managed to make it work?

**Comment by maxking71** [comment]
works well
only thing I think is to review the file restart
when I put to download 3 files together, the second and third files remain in the queue with outcome failed and I have to manually restart the download
I left everything in scripth of deafult
10 min on on on

**Comment by GammaC0de** [comment]
Plugin updated, should work fine now.

**Comment by maxking71** [comment]
fallitoParse error: Too many OPs | Plugin may be out of date 0.00 BXFileSharing

**Comment by GammaC0de** [comment]
Disable XFileSharing plugin.    
fallitoParse error: Too many OPs | Plugin may be out of date 0.00 BXFileSharing

**Comment by maxking71** [comment]
thanks for everything
but I do not know how to disable this plugin
I'm using openmediavault 3

**Comment by GammaC0de** [comment]
In pyLoad's settings,  choose plugins then find XFileSharing plugin in the list. Change "active" to off. 
 


   
thanks for everything
but I do not know how to disable this plugin
I'm using openmediavault 3

**Comment by maxking71** [comment]
WARNING Download failed: VA-Psytrance_2017__Best_Of_Top_Ec_Dance__Acid_Techno-_-2016-PITY.rar | Parse error: Captcha not found | Plugin may be out of date

**Comment by GammaC0de** [comment]
Does it have problem with this file only?

**Comment by maxking71** [comment]
no, with other 3 files ....

**Comment by GammaC0de** [comment]
Some work and some don't?
If you retry those files, does it work? 
If so please provide URLs.

**Comment by maxking71** [comment]
This morning everything worked well ... 4 files together
Today no URL of rockfile works ....

**Comment by GammaC0de** [comment]
Open those URLs in a Web browser and see if you can download

**Comment by maxking71** [comment]
yes work...in a web browser...
https://s27.postimg.org/h7jgli7n7/rockfile.png

**Comment by GammaC0de** [comment]
Add this line before [RockfileEu.py#L62](https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/RockfileEu.py#L62):
```python
                self.log_debug(self.data)
```

Enable DEBUG mode, retry the download and then post the log.

**Comment by maxking71** [comment]
thanks gamma

LOG FILE:

474 06.01.2017 10:49:18 WARNING Download failed: Party Hits 100 Painted Day (2016).mp3 320 kbps.rar | Parse error: Captcha not found | Plugin may be out of date  
475 06.01.2017 10:49:18 INFO ADDON UnSkipOnFail: Looking for skipped duplicates of: Party Hits 100 Painted Day (2016).mp3 320 kbps.rar (pid:29)  
476 06.01.2017 10:49:18 INFO ADDON UnSkipOnFail: No duplicates found  
477 06.01.2017 10:49:18 DEBUG ADDON ExternalScripts: No script found under folder `download_failed`  
478 06.01.2017 10:49:19 DEBUG ADDON ExternalScripts: No script found under folder `all_downloads_processed`  
479 06.01.2017 10:49:19 DEBUG All downloads processed

**Comment by GammaC0de** [comment]
Did you make the changes to `RockfileEu.py` I told you?

Post the whole log, not just few lines..

**Comment by maxking71** [comment]
I'm using openmediavault, I do not know how to change it

**Comment by GammaC0de** [comment]
So how did you fixed `HTTPRequest.py`?

**Comment by maxking71** [comment]
excuse me but now I do not understand ... I'm not using openmediavault able to edit files ...
the new rockfile the server I found the list without doing anything

**Comment by GammaC0de** [comment]
OK, sow what you are saying is that you did not patched the HTTPRequest.py file?
That may explain why it does not work for you.

Do you have SSH access to your server?

**Comment by maxking71** [comment]
Yes, of course, I can not access the console via putty

**Comment by GammaC0de** [comment]
You have two options:

* Try to fix `HTTPRequest.py` yourself:
&nbsp;&nbsp;&nbsp;&nbsp;1. Stop pyLoad
&nbsp;&nbsp;&nbsp;&nbsp;2. Login to the server via ssh
&nbsp;&nbsp;&nbsp;&nbsp;3. Replace `/usr/share/pyload/module/network/HTTPRequest.py` with [this](https://github.com/pyload/pyload/files/691467/HTTPRequest.zip) one.
&nbsp;&nbsp;&nbsp;&nbsp;4. Start pyLoad
&nbsp;&nbsp;&nbsp;&nbsp;5. Retry the download.

* Give me access to your server and I will do this for you.

**Comment by maxking71** [comment]
I log into the console with putty
But you have to say with precision controls to write in console

thanks

**Comment by GammaC0de** [comment]
```bash
cd /usr/share/pyload/module/network
sudo wget --no-check-certificate https://github.com/pyload/pyload/files/691467/HTTPRequest.zip
sudo mv ./HTTPRequest.py HTTPRequest.py.bak
sudo unzip ./HTTPRequest.zip
```

**Comment by maxking71** [comment]
very thanks gamma
Yesterday I was able to replace the file and it worked good for me, this morning it does not work :(



333 08.01.2017 10:45:19 WARNING HOSTER RockfileEu[1]: Plugin may be unstable  
334 08.01.2017 10:45:19 INFO HOSTER RockfileEu[1]: Grabbing link info...  
335 08.01.2017 10:45:19 DEBUG HOSTER RockfileEu[1]: Link info: {'status': 2, 'hash': {}, 'name': 'VA-The_Ultimate_Progressive_Collection_Vol_7-(10115173)-_-2017-YOU.rar', 'url': u'http://rockfile.eu/5j47vjipyf6r.html', 'pattern': {'N': u'VA-The_Ultimate_Progressive_Collection_Vol_7-(10115173)-_-2017-YOU.rar'}, 'size': 0}  
336 08.01.2017 10:45:19 DEBUG HOSTER RockfileEu[1]: Previous link info: {}  
337 08.01.2017 10:45:19 INFO HOSTER RockfileEu[1]: Link name: VA-The_Ultimate_Progressive_Collection_Vol_7-(10115173)-_-2017-YOU.rar  
338 08.01.2017 10:45:19 INFO HOSTER RockfileEu[1]: Link size: N/D  
339 08.01.2017 10:45:19 INFO HOSTER RockfileEu[1]: Link status: online  
340 08.01.2017 10:45:19 INFO HOSTER RockfileEu[1]: Processing url: http://rockfile.eu/5j47vjipyf6r.html  
341 08.01.2017 10:45:19 INFO HOSTER RockfileEu[1]: Looking for direct download link...  
342 08.01.2017 10:45:19 DEBUG HOSTER RockfileEu[1]: LOAD URL http://rockfile.eu/5j47vjipyf6r.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True  
343 08.01.2017 10:45:20 INFO HOSTER RockfileEu[1]: Direct download link not found  
344 08.01.2017 10:45:20 DEBUG HOSTER RockfileEu[1]: LOAD URL http://rockfile.eu/5j47vjipyf6r.html | redirect=True | cookies=[('rockfile.eu', 'lang', 'english')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False  
345 08.01.2017 10:45:20 INFO HOSTER RockfileEu[1]: Checking for link errors...  
346 08.01.2017 10:45:20 INFO HOSTER RockfileEu[1]: No errors found  
347 08.01.2017 10:45:20 INFO HOSTER RockfileEu[1]: Processing as free download...  
348 08.01.2017 10:45:20 DEBUG HOSTER RockfileEu[1]: LOAD URL http://rockfile.eu/5j47vjipyf6r.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'usr_login': '', u'referer': '', u'fname': u'VA-The_Ultimate_Progressive_Collection_Vol_7-(10115173)-_-2017-YOU.rar', u'method_free': u'Regular Download', u'id': u'5j47vjipyf6r', u'op': u'download1'} | ref=True | just_header=False  
349 08.01.2017 10:45:21 INFO HOSTER RockfileEu[1]: Checking for link errors...  
350 08.01.2017 10:45:21 INFO HOSTER RockfileEu[1]: No errors found  
351 08.01.2017 10:45:21 DEBUG ADDON ExternalScripts: No script found under folder `download_processed`  
352 08.01.2017 10:45:21 DEBUG ADDON ExternalScripts: No script found under folder `package_processed`  
353 08.01.2017 10:45:21 WARNING Download failed: VA-The_Ultimate_Progressive_Collection_Vol_7-(10115173)-_-2017-YOU.rar | Parse error: Captcha not found | Plugin may be out of date  
354 08.01.2017 10:45:21 INFO ADDON UnSkipOnFail: Looking for skipped duplicates of: VA-The_Ultimate_Progressive_Collection_Vol_7-(10115173)-_-2017-YOU.rar (pid:1)  
355 08.01.2017 10:45:21 INFO ADDON UnSkipOnFail: No duplicates found  
356 08.01.2017 10:45:21 DEBUG ADDON ExternalScripts: No script found under folder `download_failed`  
357 08.01.2017 10:45:21 DEBUG ADDON ExternalScripts: No script found under folder `all_downloads_processed`  
358 08.01.2017 10:45:21 DEBUG All downloads processed  
359 08.01.2017 10:46:25 DEBUG Plugin RockfileEu not found  
360 08.01.2017 10:46:25 DEBUG Available plugins : {'LinkdecrypterComHook': {'user': False, 'name': 'LinkdecrypterComHook', 'v': 1.09}, 'XMPP': {'user': False, 'name': 'XMPP', 'v': 0.17},

**Comment by GammaC0de** [comment]
Can you stop pyLoad, login to ssh and run pyLoad via `python /usr/share/pyload/pyLoadCore.py -d`, retry the download and post the ssh output here?

**Comment by maxking71** [comment]
ok, I turned off the server and restarted
partner wild with pleasure to be shared pyload
for now it works flawlessly
with 6 in download file
VERY THANKS GAMMA

**Comment by maxking71** [comment]
this morning restarting the server is back in fine download
still afternoon captcha problems :(

51 09.01.2017 16:43:32 DEBUG ADDON ExternalScripts: No script found under folder `download_failed`  
52 09.01.2017 16:43:32 DEBUG ADDON ExternalScripts: No script found under folder `all_downloads_processed`  
53 09.01.2017 16:43:32 DEBUG All downloads processed  
54 09.01.2017 16:44:38 INFO Added package techno containing 1 links  
55 09.01.2017 16:44:40 INFO Download starts: http://rockfile.eu/pvwb9od2am99.html  
56 09.01.2017 16:44:40 DEBUG ADDON ExternalScripts: No script found under folder `download_preparing`  
57 09.01.2017 16:44:40 DEBUG HOSTER RockfileEu[9]: Plugin version: 0.02  
58 09.01.2017 16:44:40 DEBUG HOSTER RockfileEu[9]: Plugin status: testing  
59 09.01.2017 16:44:40 WARNING HOSTER RockfileEu[9]: Plugin may be unstable  
60 09.01.2017 16:44:40 INFO HOSTER RockfileEu[9]: Grabbing link info...  
61 09.01.2017 16:44:41 DEBUG HOSTER RockfileEu[9]: Link info: {'status': 2, 'hash': {}, 'name': u'VA-Techno_Club_Vol._50-2CD.rar', 'url': u'http://rockfile.eu/pvwb9od2am99.html', 'pattern': {'N': u'VA-Techno_Club_Vol._50-2CD.rar'}, 'size': 0}  
62 09.01.2017 16:44:41 DEBUG HOSTER RockfileEu[9]: Previous link info: {}  
63 09.01.2017 16:44:41 INFO HOSTER RockfileEu[9]: Link name: VA-Techno_Club_Vol._50-2CD.rar  
64 09.01.2017 16:44:41 INFO HOSTER RockfileEu[9]: Link size: N/D  
65 09.01.2017 16:44:41 INFO HOSTER RockfileEu[9]: Link status: online  
66 09.01.2017 16:44:41 INFO HOSTER RockfileEu[9]: Processing url: http://rockfile.eu/pvwb9od2am99.html  
67 09.01.2017 16:44:41 INFO HOSTER RockfileEu[9]: Looking for direct download link...  
68 09.01.2017 16:44:41 DEBUG HOSTER RockfileEu[9]: LOAD URL http://rockfile.eu/pvwb9od2am99.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True  
69 09.01.2017 16:44:41 INFO HOSTER RockfileEu[9]: Direct download link not found  
70 09.01.2017 16:44:41 DEBUG HOSTER RockfileEu[9]: LOAD URL http://rockfile.eu/pvwb9od2am99.html | redirect=True | cookies=[('rockfile.eu', 'lang', 'english')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False  
71 09.01.2017 16:44:41 INFO HOSTER RockfileEu[9]: Checking for link errors...  
72 09.01.2017 16:44:41 INFO HOSTER RockfileEu[9]: No errors found  
73 09.01.2017 16:44:41 INFO HOSTER RockfileEu[9]: Processing as free download...  
74 09.01.2017 16:44:41 DEBUG HOSTER RockfileEu[9]: LOAD URL http://rockfile.eu/pvwb9od2am99.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'usr_login': '', u'referer': '', u'fname': u'VA-Techno_Club_Vol._50-2CD.rar', u'method_free': u'Regular Download', u'id': u'pvwb9od2am99', u'op': u'download1'} | ref=True | just_header=False  
75 09.01.2017 16:44:42 INFO HOSTER RockfileEu[9]: Checking for link errors...  
76 09.01.2017 16:44:42 INFO HOSTER RockfileEu[9]: No errors found  
77 09.01.2017 16:44:42 DEBUG ADDON ExternalScripts: No script found under folder `download_processed`  
78 09.01.2017 16:44:42 DEBUG ADDON ExternalScripts: No script found under folder `package_processed`  
79 09.01.2017 16:44:42 WARNING Download failed: VA-Techno_Club_Vol._50-2CD.rar | Parse error: Captcha not found | Plugin may be out of date  
80 09.01.2017 16:44:42 INFO ADDON UnSkipOnFail: Looking for skipped duplicates of: VA-Techno_Club_Vol._50-2CD.rar (pid:9)  
81 09.01.2017 16:44:42 INFO ADDON UnSkipOnFail: No duplicates found  
82 09.01.2017 16:44:42 DEBUG ADDON ExternalScripts: No script found under folder `download_failed`  
83 09.01.2017 16:44:42 DEBUG ADDON ExternalScripts: No script found under folder `all_downloads_processed`  
84 09.01.2017 16:44:42 DEBUG All downloads processed

**Comment by GammaC0de** [comment]
Please replace `RockfileEu.py` with [this one](https://github.com/pyload/pyload/files/694425/RockfileEu.zip),  restart pyLoad and download until you get error and the post all the log (including the html)

**Comment by maxking71** [comment]
if I want I can give my address to join the server ... if you give me your email



666 ?  ?   
678 ?  ?  
679 ?  ?  
680 ?  ?   
689 ?  ?  
690 ?  ?  
691 ?  ?  
692 10.01.2017 07:39:48 DEBUG ADDON ExternalScripts: No script found under folder `download_processed`  
693 10.01.2017 07:39:48 DEBUG ADDON ExternalScripts: No script found under folder `package_processed`  
694 10.01.2017 07:39:48 WARNING Download failed: Winter Hits. Hot Dance Continues (2017).rar | Parse error: Captcha not found | Plugin may be out of date  
695 10.01.2017 07:39:48 INFO ADDON UnSkipOnFail: Looking for skipped duplicates of: Winter Hits. Hot Dance Continues (2017).rar (pid:9)  
696 10.01.2017 07:39:48 INFO ADDON UnSkipOnFail: No duplicates found  
697 10.01.2017 07:39:48 DEBUG ADDON ExternalScripts: No script found under folder `download_failed`  
698 10.01.2017 07:39:48 DEBUG ADDON ExternalScripts: No script found under folder `all_downloads_processed`  
699 10.01.2017 07:39:48 DEBUG All downloads processed

**Comment by GammaC0de** [comment]
My email is nitzo2001 at yahoo dot com.
