### ISSUE TITLE
ERROR	ADDON ClickNLoad: [Errno -9] Address family for hostname not supported

### ISSUE THREAD

**Issue by blckwhtx** [pyload/pyload#2672]
31.12.2016 18:09:56	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
970	31.12.2016 18:10:21	ERROR	ADDON ClickNLoad: [Errno -9] Address family for hostname not supported
971	31.12.2016 18:58:55	ERROR	ADDON ClickNLoad: [Errno -9] Address family for hostname not supported

serienjunkies.org or ddl-warez.to 

What is that?

**Comment by GammaC0de** [comment]
Please post DEBUG log

**Comment by intellnet** [comment]
IPv4 enabled 

DEBUG LOG 

355	01.01.2017 13:20:08	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
356	01.01.2017 13:50:02	DEBUG	ADDON ClickNLoad: Connection from 192.168.178.20:54007
357	01.01.2017 13:50:02	ERROR	ADDON ClickNLoad: [Errno -9] Address family for hostname not supported

**Comment by GammaC0de** [comment]
What is the output of `ifconfig` coomand?
Maybe you should disable IPv6.

**Comment by intellnet** [comment]
IPv6 is disabled

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\system32>ipconfig

Windows-IP-Konfiguration

Ethernet-Adapter LAN-Verbindung:

   Medienstatus. . . . . . . . . . . : Medium getrennt
   Verbindungsspezifisches DNS-Suffix:

Drahtlos-LAN-Adapter Drahtlosnetzwerkverbindung:   "WIFI"

   Verbindungsspezifisches DNS-Suffix: 208.67.222.333
   IPv4-Adresse  . . . . . . . . . . : 192.168.178.20
   Subnetzmaske  . . . . . . . . . . : 255.255.255.0
   Standardgateway . . . . . . . . . : 192.168.178.1

**Comment by Velociraptor85** [comment]
What does `hostname` tell you?
When do you get the messages? After start or always when you use Click'n'Load ?

**Comment by intellnet** [comment]
Since the last update of addons does not work, try to reinstall windows, then announce me

( Google translator )

**Comment by Velociraptor85** [comment]
@intellnet did the reinstall work ?

**Comment by Velociraptor85** [comment]
@intellnet may we close this issue ? or is this still valid?
