### ISSUE TITLE
Uploaded Account not Premium

### ISSUE THREAD

**Issue by erwtz** [pyload/pyload#2673]
pyload doesnt accept my uploaded premium account. 

![bildschirmfoto_2016-12-31_19-06-06](https://cloud.githubusercontent.com/assets/24855872/21578756/91292a04-cf8c-11e6-8cb3-2b8fe1c434b6.png)

![bildschirmfoto_2016-12-31_19-06-30](https://cloud.githubusercontent.com/assets/24855872/21578758/912c51e8-cf8c-11e6-933c-6308f860f719.png)

if i want to download something pyload does that, but just some kb. if i try the direct link on my pc it all works perfectly fine and i get the 200 mb

![bildschirmfoto vom 2016-12-31 19-07-08](https://cloud.githubusercontent.com/assets/24855872/21578757/9129f89e-cf8c-11e6-9a52-651068afcf4c.png)

i searched alot around and updated the updatemanager.py, took the latest stable realease, the router cant be the problem. i can log in to my account, i just get the wrong status.

would be glad to get some help.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by erwtz** [comment]
you got mail

**Comment by GammaC0de** [comment]
Works fine here:
![capture](https://cloud.githubusercontent.com/assets/11036551/21578868/6a27ac74-cf9a-11e6-8994-3c67c1904454.PNG)


What account plugin version are you using?
Is this a new installation?

Please post DEBUG log.

**Comment by erwtz** [comment]
the installation is new. it's the 0.4.9 with the including plugins

here is the log:`
pyLoadCore -d
31.12.2016 20:03:22 INFO      starte pyLoad 0.4.9
31.12.2016 20:03:22 INFO      Benutze Home-Verzeichnis: /home/pyload/.pyload
31.12.2016 20:03:22 DEBUG     Remote activated: True
31.12.2016 20:03:23 DEBUG     created index of plugins
31.12.2016 20:03:23 INFO      ExtractArchive: Aktiviert UnRar UnZip
31.12.2016 20:03:23 INFO      Aktivierte Plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
31.12.2016 20:03:23 INFO      Deaktivierte Plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
31.12.2016 20:03:23 INFO      Downloadzeit: True
31.12.2016 20:03:23 INFO      Starte ThriftBackend: 0.0.0.0:7227
31.12.2016 20:03:24 INFO      Starting builtin webserver: 192.168.178.62:8000
31.12.2016 20:03:24 INFO      Free space: 1.14 TiB
31.12.2016 20:03:24 INFO      Activating Accounts...
31.12.2016 20:03:24 DEBUG     UploadedTo: Get Account Info for 11319449
31.12.2016 20:03:24 DEBUG     UploadedTo: Account Info: {'validuntil': -1, 'premium': False}
31.12.2016 20:03:24 INFO      Activating Plugins...
31.12.2016 20:03:24 INFO      pyLoad is up and running
31.12.2016 20:03:27 INFO      ***  New pyLoad Version <!DOCTYPE html>
<html>
</html> available  ***
31.12.2016 20:03:27 INFO      ***  Get it here: http://pyload.org/download  ***
31.12.2016 20:03:27 INFO      No plugin updates available
`

**Comment by GammaC0de** [comment]
Ok, now its clear, your pyLoad version is  not up-to-date.
Please read #2000

**Comment by erwtz** [comment]
the solution #2000 was known before i asked. i tried it and it didn't fix the problem. 

at this point i ll delete everything and try fresh again. let you know if something changed.

**Comment by GammaC0de** [comment]
It seems that you have failed in the most important part which is replacing `UpdateManager.py` with a functional one...

So I don't think reinstalling would help.

**Comment by GammaC0de** [comment]
Go to http://\<pyload addr\>/info and see the location of `Installation Folder`.
put the`UpdateManager.py` from #2000 in \<Installation Folder\>\module\plugins\hooks

**Comment by erwtz** [comment]
done that. no change.

**Comment by GammaC0de** [comment]
Restart pyLoad, it may be needed for the plugin update process to finish.

**Comment by erwtz** [comment]
ok. it works now, but just after deleting the < Installation Folder > completely and starting pyload from the downloaded folder directly with python. i don't have any clue what went wrong before. but thanks for your help!

**Comment by GammaC0de** [comment]
👍
