### ISSUE TITLE
easybytez premium not working

### ISSUE THREAD

**Issue by fumantsu** [pyload/pyload#2674]
easybytez premium plugin doesn't work as premium. below the log file with debug
31.12.2016 19:44:49 INFO      ADDON UpdateManager: All plugins are up to date!
31.12.2016 19:44:51 INFO      Download starts: <filename>.part02.rar
31.12.2016 19:44:51 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
31.12.2016 19:44:51 DEBUG     HOSTER EasybytezCom[2]: Plugin version: 0.28
31.12.2016 19:44:51 DEBUG     HOSTER EasybytezCom[2]: Plugin status: testing
31.12.2016 19:44:51 WARNING   HOSTER EasybytezCom[2]: Plugin may be unstable
31.12.2016 19:44:51 DEBUG     HOSTER EasybytezCom[2]: Config option `use_premium` not found, use default `True`
31.12.2016 19:44:51 INFO      ACCOUNT EasybytezCom: Grabbing account info for user `<username>`...
31.12.2016 19:44:51 DEBUG     ACCOUNT EasybytezCom: LOAD URL http://www.easybytez.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
31.12.2016 19:44:51 DEBUG     ACCOUNT EasybytezCom: Expire date: 8 November 2017
31.12.2016 19:44:51 DEBUG     ACCOUNT EasybytezCom: Valid until: 1510095600.0
31.12.2016 19:44:51 DEBUG     ACCOUNT EasybytezCom: LEECH TRAFFIC PATTERN not found
31.12.2016 19:44:51 DEBUG     ACCOUNT EasybytezCom: Account info for user `<username>`: {'login': {'timestamp': 1483209887.105602, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account EasybytezCom>, 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1510095600.0, 'login': '<username>', 'type': 'EasybytezCom', 'options': {'limitdl': ['0']}}}
31.12.2016 19:44:51 INFO      HOSTER EasybytezCom[2]: Grabbing link info...
31.12.2016 19:44:51 DEBUG     HOSTER EasybytezCom[2]: Link info: {'status': 2, 'hash': {}, 'name': u'<filename>.part02.rar', 'url': u'http://www.easybytez.com/ahpxxud3iuk7/<filename>.part02.rar', 'pattern': {'S': u'101.0', 'U': u'MB', 'N': u'<filename>.part02.rar'}, 'size': 105906176}
31.12.2016 19:44:51 DEBUG     HOSTER EasybytezCom[2]: Previous link info: {}
31.12.2016 19:44:51 INFO      HOSTER EasybytezCom[2]: Link name: <filename>.part02.rar
31.12.2016 19:44:51 INFO      HOSTER EasybytezCom[2]: Link size: 101.00 MiB (105906176 bytes)
31.12.2016 19:44:51 INFO      HOSTER EasybytezCom[2]: Link status: online
31.12.2016 19:44:51 INFO      HOSTER EasybytezCom[2]: Processing url: http://www.easybytez.com/ahpxxud3iuk7/<filename>.part02.rar
31.12.2016 19:44:51 INFO      HOSTER EasybytezCom[2]: Looking for direct download link...
31.12.2016 19:44:51 DEBUG     HOSTER EasybytezCom[2]: LOAD URL http://www.easybytez.com/ahpxxud3iuk7/<filename>.part02.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
31.12.2016 19:44:51 INFO      HOSTER EasybytezCom[2]: Direct download link not found
31.12.2016 19:44:51 DEBUG     HOSTER EasybytezCom[2]: LOAD URL http://www.easybytez.com/ahpxxud3iuk7/<filename>.part02.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
31.12.2016 19:44:51 INFO      HOSTER EasybytezCom[2]: Checking for link errors...
31.12.2016 19:44:51 INFO      HOSTER EasybytezCom[2]: No errors found
31.12.2016 19:44:51 INFO      HOSTER EasybytezCom[2]: Processing as premium download...
31.12.2016 19:44:52 DEBUG     HOSTER EasybytezCom[2]: Getting download link #1...
31.12.2016 19:44:52 INFO      HOSTER EasybytezCom[2]: Checking for link errors...
31.12.2016 19:44:52 INFO      HOSTER EasybytezCom[2]: No errors found
31.12.2016 19:44:52 DEBUG     HOSTER EasybytezCom[2]: {u'rand': u'4gvyfqy72jkdjoz5synoct2te37xajmr56ehcqq', u'method_premium': u'1', u'down_direct': u'1', u'referer': '', u'method_free': '', u'id': u'ahpxxud3iuk7', u'op': u'download2'}
31.12.2016 19:44:52 DEBUG     HOSTER EasybytezCom[2]: LOAD URL http://www.easybytez.com/ahpxxud3iuk7/<filename>.part02.rar | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'rand': u'4gvyfqy72jkdjoz5synoct2te37xajmr56ehcqq', u'method_premium': 'Premium Download', u'down_direct': u'1', u'referer': '', u'id': u'ahpxxud3iuk7', u'op': u'download2'} | ref=True | just_header=False
31.12.2016 19:44:52 INFO      HOSTER EasybytezCom[2]: Downloading file...
31.12.2016 19:44:52 DEBUG     HOSTER EasybytezCom[2]: DOWNLOAD URL http://str25.easybytez.com/files/0/4x2eineyxrtiq3/<filename>.part02.rar | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
31.12.2016 19:44:52 DEBUG     HOSTER EasybytezCom[2]: Config option `fallback` not found, use default `True`
31.12.2016 19:44:52 WARNING   HOSTER EasybytezCom[2]: Premium download failed | downloading

**Comment by GammaC0de** [comment]
Did you enabled direct downloads in your easybytez.com account?

**Comment by fumantsu** [comment]
I tried with and without direct downloads

**Comment by GammaC0de** [comment]
Ok, account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
No response, closing.
