### ISSUE TITLE
html files download

### ISSUE THREAD

**Issue by Rpi42** [pyload/pyload#2675]
Hello,

I'm using pyLoad on a raspberry with OSMC.
Here is my issue: 
When I'm trying to download a file from web UI, I found a html file or light files without contents. I have the same with different server. Here is the log:
1120	03.01.2017 20:59:35	INFO	ExtractArchive: Check package test
1121	03.01.2017 21:06:09	INFO	Added package new containing 1 links
1122	03.01.2017 21:06:10	INFO	Download starts: http://uptobox.com/yvaate84b1b3
1123	03.01.2017 21:06:11	DEBUG	BasePlugin: Filename: yvaate84b1b3
1124	03.01.2017 21:06:11	INFO	Download finished: yvaate84b1b3
1125	03.01.2017 21:06:11	INFO	Package finished: new
1126	03.01.2017 21:06:11	INFO	ExtractArchive: Package new queued for later extracting
1127	03.01.2017 21:06:11	DEBUG	All downloads processed
1128	03.01.2017 21:06:11	INFO	ExtractArchive: Check package new

**Comment by GammaC0de** [comment]
Tested and works fine here.
Please read #2000

**Comment by Rpi42** [comment]
Thanks it works well!

**Comment by GammaC0de** [comment]
👍
