### ISSUE TITLE
getpwnam(): name not found

### ISSUE THREAD

**Issue by the-ab** [pyload/pyload#2678]
Hello,

Download does not start anymore

please help

[debug_ZippyshareCom_08-01-2017_11-03-59.zip](https://github.com/pyload/pyload/files/692022/debug_ZippyshareCom_08-01-2017_11-03-59.zip)
[log.txt](https://github.com/pyload/pyload/files/692023/log.txt)

**Comment by GammaC0de** [comment]
This link worked fine here.

What you have a configuration issue:
Either set "Change Group and User of Downloads" to "off" in pyLoad's configuration -> General -> Permissions or specify correct Username and Groupname.

**Comment by the-ab** [comment]
Thank you it works, you're the best :-)

**Comment by GammaC0de** [comment]
👍
