### ISSUE TITLE
ExtractArchive on DS216j won't extract

### ISSUE THREAD

**Issue by electricar** [pyload/pyload#2680]
ExtractArchive won't extract the archives on my Synology DS216j after finished download through pyload. Is there a possibilty to start an automated extraction of archives after finished downloads?

System
Python: 2.7.11 (default, Feb 5 2016, 22:50:15) [GCC 4.9.3 20150311 (prerelease)]
OS: posix linux2 Linux DS216j 3.10.77 #8451 SMP Wed Aug 17 05:12:58 CST 2016 armv7l
pyLoad version: 0.4.9

**Comment by GammaC0de** [comment]
Is this a new installation?

Post DEBUG log please.

**Comment by electricar** [comment]
I don't think so. It's installed from this source:
https://synology.cambier.org/?arch=armada38x

Do you know a newer pyload package which can be installed on the Synology DS216j?

Here is the code:
`09.01.2017 22:22:57	INFO	Starting pyLoad 0.4.9
585	09.01.2017 22:22:57	INFO	Using home directory: /volume1/@appstore/pyload/etc
586	09.01.2017 22:22:57	DEBUG	Remote activated: False
587	09.01.2017 22:23:01	DEBUG	created index of plugins
588	09.01.2017 22:23:02	INFO	Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
589	09.01.2017 22:23:02	INFO	Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
590	09.01.2017 22:23:02	INFO	Downloadtime: True
591	09.01.2017 22:23:02	INFO	Free space: 1.79 TiB
592	09.01.2017 22:23:02	INFO	Activating Accounts...
593	09.01.2017 22:23:03	INFO	Starting threaded webserver: 0.0.0.0:8001

604	09.01.2017 22:23:05	INFO	Activating Plugins...
605	09.01.2017 22:23:05	DEBUG	ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
606	09.01.2017 22:23:05	DEBUG	ADDON ExternalScripts: No script found under folder `pyload_start`
607	09.01.2017 22:23:05	DEBUG	ADDON ExtractArchive: Found UnRar 5.21 | Found SevenZip 9.20 | Found UnZip 2.7.11 | Found UnTar 2.7.11
608	09.01.2017 22:23:05	DEBUG	ADDON ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
609	09.01.2017 22:23:05	ERROR	ADDON ExtractArchive: [Errno 2] No such file or directory: 'passwords.txt'
610	09.01.2017 22:23:05	INFO	ADDON XFileSharing: Auto-discover new hosters
611	09.01.2017 22:23:05	DEBUG	ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|cramit\.in|easybytez\.com|exashare\.com|fileom\.com|filerio\.com|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uplea\.com|uptobox\.com|vidplay\.net))(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
612	09.01.2017 22:23:06	INFO	ADDON XFileSharing: Auto-discover new crypters
613	09.01.2017 22:23:06	DEBUG	ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
614	09.01.2017 22:23:06	INFO	ADDON ExtractArchive: Check package: MarkFitness2013_SO
615	09.01.2017 22:23:06	INFO	pyLoad is up and running
616	09.01.2017 22:23:06	INFO	ADDON UpdateManager: *** New pyLoad
618	09.01.2017 22:23:12	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
619	09.01.2017 22:24:32	INFO	Added package abc containing 1 links
620	09.01.2017 22:24:32	INFO	Download starts: http://www.share-online.biz/dl/...
621	09.01.2017 22:24:32	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
622	09.01.2017 22:24:32	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
623	09.01.2017 22:24:32	DEBUG	HOSTER ShareonlineBiz[33]: Plugin version: 0.65
624	09.01.2017 22:24:32	DEBUG	HOSTER ShareonlineBiz[33]: Plugin status: testing
625	09.01.2017 22:24:32	WARNING	HOSTER ShareonlineBiz[33]: Plugin may be unstable

650	?	?	URL: http://dlw19-2.share-online.biz/dl?u=...=v4
651	?	?	ID: ...
652	?	?	NAME: test10Mb.rar
653	?	?	SIZE: 10485835
654	?	?	MD5: 0a8b466d5d81d6c0f9d681a1685db5e5
655	09.01.2017 22:24:34	INFO	HOSTER ShareonlineBiz[33]: Downloading file...
656	09.01.2017 22:24:34	DEBUG	HOSTER ShareonlineBiz[33]: DOWNLOAD URL http://dlw19-2.share-online.biz/dl?u=...=v4 | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
657	09.01.2017 22:24:34	DEBUG	Content-Disposition: test10Mb.rar
658	09.01.2017 22:24:38	INFO	HOSTER ShareonlineBiz[33]: File saved
659	09.01.2017 22:24:38	INFO	HOSTER ShareonlineBiz[33]: Checking download...
660	09.01.2017 22:24:39	INFO	HOSTER ShareonlineBiz[33]: File is OK
661	09.01.2017 22:24:39	INFO	HOSTER ShareonlineBiz[33]: Checking file (with built-in rules)...
662	09.01.2017 22:24:39	INFO	HOSTER ShareonlineBiz[33]: Checking file (with custom rules)...
663	09.01.2017 22:24:39	INFO	HOSTER ShareonlineBiz[33]: No errors found
664	09.01.2017 22:24:39	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
665	09.01.2017 22:24:39	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
666	09.01.2017 22:24:39	INFO	Download finished: test10Mb.rar
667	09.01.2017 22:24:39	DEBUG	ADDON ExternalScripts: No script found under folder `download_finished`
668	09.01.2017 22:24:39	INFO	Package finished: abc
669	09.01.2017 22:24:39	DEBUG	ADDON ExternalScripts: No script found under folder `package_finished`
670	09.01.2017 22:24:39	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
671	09.01.2017 22:24:39	DEBUG	All downloads processed
672	09.01.2017 22:24:39	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_finished`
673	09.01.2017 22:24:39	DEBUG	All downloads finished`

**Comment by GammaC0de** [comment]
From the log, I see that your pyLoad is not up-to-date, please read #2000 on how to update `UpdateManager.py`

**Comment by GammaC0de** [comment]
No response, closing.
