### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by sraedler** [pyload/pyload#2682]
Would it be possible to integrate Spotify, to download playlists?

**Comment by GammaC0de** [comment]
Example please.

**Comment by sraedler** [comment]
https://open.spotify.com/user/12124065316/playlist/4EowKfG29GMlJk4R1N6NAW

**Comment by sraedler** [comment]
Any Progress ?

**Comment by GammaC0de** [comment]
I don't think this is possible because of DRM.
Do you know and software that can do this (not by recording the wave out of the soundcard)?

**Comment by sraedler** [comment]
I didn't checked it, but I found this one.

https://github.com/Ritiek/Spotify-Downloader

**Comment by GammaC0de** [comment]
Not possible, closing
