### ISSUE TITLE
How to install on a shared host?

### ISSUE THREAD

**Issue by aidinzolghadr** [pyload/pyload#2684]
Hi,

I installed pyload fine but to install it's dependencies like pycurl (or python-crypto), I don't have pip or easy_install and can't find any other way.

I tried to install python locally via linuxbrew but could not make the system choose that over the one in system directory.

Please advise.

**Comment by GammaC0de** [comment]
You don't have to make the system choose linuxbrew's python, just run it explicity:
```bash
bash#: <path_to_linuxbrew_python>/python /usr/share/python/pyLoadCore.py
```

**Comment by aidinzolghadr** [comment]
Thanks but problem is how to install it's dependencies. I've compiled Python and can use it but I can't force some libraries that want to install system wide to do it on my local python installation.

**Comment by GammaC0de** [comment]
What OS and hardware are you using?

**Comment by aidinzolghadr** [comment]
It's a shared server so I don't know the spec but:

```
$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
My best guess is to use virtualenv but having some problems doing it on the server.

**Comment by Velociraptor85** [comment]
maybe check with which where python is installed at?
`which python`

**Comment by aidinzolghadr** [comment]
My problem is solved. how can I label it as one?

**Comment by GammaC0de** [comment]
If your problem is solved, you just close the issue.
