### ISSUE TITLE
MegaCoNz Failed writing body (0 != 16384)

### ISSUE THREAD

**Issue by asturnauta** [pyload/pyload#2685]
Hi
I want to download a mega folder and it fails with this error:
failed(23, 'Failed writing body (0 != 16384)') 0.00 BMegaCoNzFolder

The mega url is: https://mega.nz/#F!KV1kHSaQ!7vOrKS2CEyaF4_sRSYvZQA!rNlREKYR

And this is the debug file created by pyload:
http://pastebin.com/Man8qUqx

I think the plugins are up to date because on boot pyload not shows any 'update plugins' message.

Thanks.

**Comment by GammaC0de** [comment]
This is insane: this folder contains hundreds of files..
Are you sure you want to download it?

**Comment by asturnauta** [comment]
No needed. I just downloaded about 20 files i needed.
But i did not know that the 'writing body' error was because a change on mega or something similar and i thinked in notify it.
If the error is only with number of files and the plugin works right with other folders is right.
I apologize for the confusion

Thanks.

**Comment by GammaC0de** [comment]
That's OK, no need to apologize.

It is good you have reported this, we do encourage people to report, without this pyLoad would not function well...
