### ISSUE TITLE
Download failed: dorieavc.part003.rar | 'ascii' codec can't encode character u'\xff' in position 26677: ordinal not in range(128)

### ISSUE THREAD

**Issue by minihoeppi** [pyload/pyload#2688]
Hi,
i´ve this Problem on my raspberrypi:
430885	13.01.2017 15:57:52	INFO	Download starts: http://www9.zippyshare.com/v/fibl5sh8/file.html
430886	13.01.2017 15:57:52	WARNING	HOSTER ZippyshareCom[4118]: Plugin may be unstable
430887	13.01.2017 15:57:52	INFO	HOSTER ZippyshareCom[4118]: Grabbing link info...
430888	13.01.2017 15:57:52	INFO	HOSTER ZippyshareCom[4118]: Link name: dorieavc.part003.rar
430889	13.01.2017 15:57:52	INFO	HOSTER ZippyshareCom[4118]: Link size: 150.00 MiB (157286400 bytes)
430890	13.01.2017 15:57:52	INFO	HOSTER ZippyshareCom[4118]: Link status: online
430891	13.01.2017 15:57:52	INFO	HOSTER ZippyshareCom[4118]: Processing url: http://www9.zippyshare.com/v/fibl5sh8/file.html
430892	13.01.2017 15:57:52	INFO	HOSTER ZippyshareCom[4118]: Looking for direct download link...
430893	13.01.2017 15:57:52	INFO	HOSTER ZippyshareCom[4118]: Direct download link not found
430894	13.01.2017 15:57:52	INFO	HOSTER ZippyshareCom[4118]: Checking for link errors...
430895	13.01.2017 15:57:52	INFO	HOSTER ZippyshareCom[4118]: No errors found
430896	13.01.2017 15:57:52	INFO	HOSTER ZippyshareCom[4118]: Processing as free download...
430897	13.01.2017 15:57:52	WARNING	CAPTCHA ZippyshareCom[4118]: ReCaptcha | Key pattern not found
430898	13.01.2017 15:58:03	WARNING	Download failed: dorieavc.part003.rar | 'ascii' codec can't encode character u'\xff' in position 26677: ordinal not in range(128)
430899	13.01.2017 15:58:03	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: dorieavc.part003.rar (pid:103)
430900	13.01.2017 15:58:03	INFO	ADDON UnSkipOnFail: No duplicates found 

Can anyone help?

**Comment by GammaC0de** [comment]
Tested and worked fine here,
is this a new installation?

**Comment by minihoeppi** [comment]
reinstalled.
