### ISSUE TITLE
No unrar with apt-get

### ISSUE THREAD

**Issue by PlanetDyna** [pyload/pyload#2690]
I used Pyload on my Raspberry Pi 1. Now with the Pi 3, I can not install unrar.

root@raspberrypi:~# sudo apt-get install unrar
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package unrar is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'unrar' has no installation candidate

--

ADDON ExtractArchive: No files found to extract

**Comment by Burnout5151** [comment]
This is not a PyLoad-problem:
Raspian doesn't seem to include the non-free unrar anymore.
either
a) Install unrar-free
b) Follow a guide to install unrar
Maybe this will help you with b)
http://raspberrypi.stackexchange.com/questions/3617/how-to-install-unrar-nonfree#3618
Apparently unrar-free can't handle multipart archives, so a) might be unfeasible.

@vuolter , @GammaC0de, @Velociraptor85 : I think this can be closed
