### ISSUE TITLE
direct link not found - share-online.biz

### ISSUE THREAD

**Issue by Exceen** [pyload/pyload#2692]
Added a container today when this happened:

> 15.01.2017 16:39:54 INFO      Downloadtime: True
> 15.01.2017 16:39:54 INFO      Starting ThriftBackend: 0.0.0.0:7227
> 15.01.2017 16:39:55 INFO      Free space: 94.71 GiB
> 15.01.2017 16:39:55 INFO      Starting builtin webserver: 0.0.0.0:8042
> 15.01.2017 16:39:55 INFO      Activating Accounts...
> 15.01.2017 16:39:55 INFO      ACCOUNT ShareonlineBiz: Adding user `*`...
> 15.01.2017 16:39:55 INFO      ACCOUNT ShareonlineBiz: Login user `*`...
> 15.01.2017 16:39:56 INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `*`...
> 15.01.2017 16:39:56 INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `*`...
> 15.01.2017 16:39:56 INFO      Activating Plugins...
> 15.01.2017 16:39:56 INFO      ADDON XFileSharing: Auto-discover new hosters
> 15.01.2017 16:39:57 INFO      ADDON XFileSharing: Auto-discover new crypters
> 15.01.2017 16:39:57 INFO      pyLoad is up and running
> 15.01.2017 16:39:57 INFO      ADDON UpdateManager: pyLoad is up to date!
> 15.01.2017 16:39:57 INFO      ADDON UpdateManager: All plugins are up to date!
> 15.01.2017 16:39:59 INFO      Download starts: http://www.share-online.biz/dl/*
> 15.01.2017 16:39:59 WARNING   HOSTER ShareonlineBiz[316]: Plugin may be unstable
> 15.01.2017 16:39:59 INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `*`...
> 15.01.2017 16:39:59 INFO      HOSTER ShareonlineBiz[316]: Grabbing link info...
> 15.01.2017 16:39:59 INFO      HOSTER ShareonlineBiz[316]: Link name: *.part01.rar
> 15.01.2017 16:39:59 INFO      HOSTER ShareonlineBiz[316]: Link size: 1023.00 MiB (1072693248 bytes)
> 15.01.2017 16:39:59 INFO      HOSTER ShareonlineBiz[316]: Link status: online
> 15.01.2017 16:39:59 INFO      HOSTER ShareonlineBiz[316]: Processing url: http://www.share-online.biz/dl/*
> 15.01.2017 16:39:59 INFO      HOSTER ShareonlineBiz[316]: Looking for direct download link...
> 15.01.2017 16:39:59 INFO      HOSTER ShareonlineBiz[316]: Direct download link not found
> 15.01.2017 16:39:59 INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `*`...
> 15.01.2017 16:40:00 INFO      HOSTER ShareonlineBiz[316]: Filesize: 1047552 KiB | Traffic left for user `*`: 92740707 KiB
> 15.01.2017 16:40:00 INFO      HOSTER ShareonlineBiz[316]: Processing as premium download...
> 15.01.2017 16:40:00 INFO      ACCOUNT ShareonlineBiz: Grabbing account info for user `*`...
> 15.01.2017 16:40:01 INFO      HOSTER ShareonlineBiz[316]: Downloading file...
> 15.01.2017 16:40:01 WARNING   HOSTER ShareonlineBiz[316]: Premium download failed | downloading
> 15.01.2017 16:40:01 INFO      Download restarted: *.part01.rar | Fallback to free processing
> 15.01.2017 16:40:01 INFO      Download starts: *.part01.rar
> 15.01.2017 16:40:01 WARNING   HOSTER ShareonlineBiz[316]: Plugin may be unstable
> 15.01.2017 16:40:01 INFO      HOSTER ShareonlineBiz[316]: Grabbing link info...
> 15.01.2017 16:40:01 INFO      HOSTER ShareonlineBiz[316]: Link name: *.part01.rar
> 15.01.2017 16:40:01 INFO      HOSTER ShareonlineBiz[316]: Link size: 1023.00 MiB (1072693248 bytes)
> 15.01.2017 16:40:01 INFO      HOSTER ShareonlineBiz[316]: Link status: online
> 15.01.2017 16:40:01 INFO      HOSTER ShareonlineBiz[316]: Processing url: http://www.share-online.biz/dl/*
> 15.01.2017 16:40:01 INFO      HOSTER ShareonlineBiz[316]: Looking for direct download link...
> 15.01.2017 16:40:01 INFO      HOSTER ShareonlineBiz[316]: Direct download link not found
> 15.01.2017 16:40:01 INFO      HOSTER ShareonlineBiz[316]: Processing as free download...
> 15.01.2017 16:40:01 INFO      HOSTER ShareonlineBiz[316]: Waiting 3 seconds...
> 15.01.2017 16:40:03 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
> 15.01.2017 16:40:06 INFO      CAPTCHA ShareonlineBiz[316]: ReCaptcha | Using OCR to decrypt captcha...
> 15.01.2017 16:40:06 WARNING   CAPTCHA ShareonlineBiz[316]: ReCaptcha | No OCR result

I'm not quite sure what causes this. This is the first time I get this error and I'm using pyLoad for about 5 years now. Downloading with JDownloader works just fine. Any solutions?

**Comment by GammaC0de** [comment]
Account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com.

Also send the problematic URL.

**Comment by Exceen** [comment]
After further trying to download it, I managed to get it running by creating a new package and adding the links instead of uploading a container. Very weird issue.

I think it has something to do with the "|" in the package name. Somehow it falls back into free download then.
