### ISSUE TITLE
Chomikuj.pl - account plugin

### ISSUE THREAD

**Issue by kazz3m** [pyload/pyload#2693]
Hi, I've created plugin as in topic.
Feel free to add it to pyLoad:
[https://github.com/kazz3m/pyload_chomikujpl/blob/master/ChomikujPl.py](https://github.com/kazz3m/pyload_chomikujpl/blob/master/ChomikujPl.py)

**Comment by GammaC0de** [comment]
What's the use of the account plugin without a hoster plugin?

**Comment by kazz3m** [comment]
Will check but It's working for me without it.

**Comment by GammaC0de** [comment]
Closing..
