### ISSUE TITLE
Is upstore supported?

### ISSUE THREAD

**Issue by adamwinn** [pyload/pyload#2694]
I'm on a shared hoster that has provided pyload for us and it doesn't have the upstore plugin.  They said they just installed the latest version for us.  Should upstore be included?

**Comment by Burnout5151** [comment]
Hi, I just tried with a version I recently updated via _git pull_
Upsto.re works for me.
Maybe check if your Updatemanager is activated.

**Comment by GammaC0de** [comment]
Plugin updated and tested just now, do you have issues?

**Comment by adamwinn** [comment]
I'm waiting to hear back from my hosting company.  I'll let you know.  Thanks!

**Comment by adamwinn** [comment]
upstore is in the plugins tab now.  How can I get it in the accounts tab?  Please see attached screenshot
<img width="1341" alt="screen shot 2017-01-17 at 10 47 24 pm" src="https://cloud.githubusercontent.com/assets/3028964/22052468/ae15c91e-dd07-11e6-8be3-ae55d80351df.png">

**Comment by GammaC0de** [comment]
Currently upstore premium is not supported.

If you would like to add premium is not support to upstore, I will account information for testing, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by adamwinn** [comment]
I've already done a work around so that's ok

**Comment by AkgunFatih** [comment]
@adamwinn whats the workarround ?

**Comment by adamwinn** [comment]
Sorry I can't remember.  That was 3 years ago

**Comment by GammaC0de** [comment]
@adamwinn 
If you would like to add premium is not support to upstore,, account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by AkgunFatih** [comment]
> @adamwinn
> If you would like to add premium is not support to upstore,, account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

i have just send an email can check and confirm pls

**Comment by AkgunFatih** [comment]
@GammaC0de Hey i have send you the credentials can you pls confirm it

**Comment by GammaC0de** [comment]
Added upstore premium support

**Comment by AkgunFatih** [comment]
@GammaC0de Sorry im new at pyload but
i cant find it on the master branch
there is no  `module` folder

**Comment by GammaC0de** [comment]
@AkgunFatih We use the [stable](https://github.com/pyload/pyload/tree/stable) branch for production
