### ISSUE TITLE
Several issues (Beginner)

### ISSUE THREAD

**Issue by aidinzolghadr** [pyload/pyload#2697]
Hi,

I have several issues with pyload on my Debian shared host server: I'm only interested in web interface. My python is 2.7 and installed pyload via unzipping the release and calling python pyloadCore.py, as pip and easy_install could not install it. they returned:
```
Could not find a version that satisfies the requirement pyload-ng (from versions: )
No matching distribution found for pyload-ng
```
1) Why the latest stable release is for 2011 on the main branch but the 1.0.0 branch has active development and not released a stable build?! Do I have to get the 0.49 version or clone that 1.0.0 branch and build perhaps?

2) I've tried to setup via "python pyloadCore.py -s" and mostly accepted default values but whatever URL I try, I can't connect to it. Setup's IP is set to 0.0.0.0 and port to 8000 and pyload is installed in a sub directory in my host. So I tried myDomain.com:8000, myDomain/pyLoadPath:8000 and none of them worked.

3) After calling python pyloadCoare.py, the server terminates after like 15 seconds. It just says "Terminated". How can I fix it?

Thanks

**Comment by GammaC0de** [comment]
:please read #2000

**Comment by aidinzolghadr** [comment]
Thanks, I've done all those but what does it mean when it says "starr pyLoad"? is it
`python pyloadCore.py`
?

**Comment by GammaC0de** [comment]
Yes

**Comment by aidinzolghadr** [comment]
But it did not update anything, just went straight to setup.

And please reply questions #2 and #3.

**Comment by GammaC0de** [comment]
1) 0.49 is still the current release and this version should be used, indeed 1.0.0 branch has active development but it is not yet operational and so is considered alpha version.

2) myDomain.com:8000 should be used.

3) show the output of `python pyloadCore.py -d`

**Comment by aidinzolghadr** [comment]
Thanks, I provided the output of pyLoadCore.py -d in this issue:

https://github.com/pyload/pyload/issues/2698
