### ISSUE TITLE
Fatal Python error: Couldn't create autoTLSkey mapping (and LinkdecrypterCom: Crypter list not found)

### ISSUE THREAD

**Issue by aidinzolghadr** [pyload/pyload#2698]
Hi,

After running pyload, I get this error:
`Fatal Python error: Couldn't create autoTLSkey mapping`

Here is the full log:

python pyLoadCore.py
17.01.2017 22:20:56 INFO      Starting pyLoad 0.4.9
17.01.2017 22:20:56 INFO      Using home directory: /home/pyload/settings
17.01.2017 22:20:56 INFO      Checksum: Checksum validation is disabled in general configuration
17.01.2017 22:20:56 INFO      ExtractArchive: No UnRar installed
17.01.2017 22:20:56 INFO      ExtractArchive: Activated UnZip
17.01.2017 22:20:56 INFO      Activated plugins: BypassCaptcha, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterCom, UnSkipOnFail, UpdateManager, XFileSharingPro
17.01.2017 22:20:56 INFO      Deactivate plugins: AlldebridCom, Captcha9kw, CaptchaBrotherhood, DeathByCaptcha, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, Premium4Me, PremiumizeMe, RealdebridCom, RehostTo, XMPPInterface, ZeveraCom
17.01.2017 22:20:56 INFO      Downloadtime: True
17.01.2017 22:20:56 INFO      Starting ThriftBackend: 0.0.0.0:7227
17.01.2017 22:20:56 INFO      Starting builtin webserver: 0.0.0.0:8000
17.01.2017 22:20:56 INFO      Free space: 783.60 GiB
17.01.2017 22:20:56 INFO      Activating Accounts...
17.01.2017 22:20:56 INFO      Activating Plugins...
17.01.2017 22:20:56 ERROR     LinkdecrypterCom: Crypter list not found
17.01.2017 22:20:57 INFO      pyLoad is up and running
Fatal Python error: Couldn't create autoTLSkey mapping
Aborted

**Comment by aidinzolghadr** [comment]
Apparently it's due to low memory but I can't find a way how to increase it. Since pyLoad is written in Django, apparently it should be done with uWSGI but I can't seem to find how.

**Comment by GammaC0de** [comment]
What hardware/OS?
show the output of `pyLoadCore.py -s` and `pyLoadCore.py -d`

**Comment by aidinzolghadr** [comment]
I don't understand "output of pyLoadCore.py", it just starts the setup process, here is the first part:
```
python pyLoadCore.py -s
Choose your Language / Wähle deine Sprache ([en], de, fr, it, es, nl, sv, ru, pl, cs, sr, pt_BR): ^X
```

And here is the output of `pyLoadCore.py -d`:

```
python pyLoadCore.py -d
18.01.2017 13:08:10 INFO      Starting pyLoad 0.4.9
18.01.2017 13:08:10 INFO      Using home directory: /home/pyload/settings
18.01.2017 13:08:10 DEBUG     Deleting old pidfile pyload.pid
18.01.2017 13:08:10 DEBUG     Remote activated: True
18.01.2017 13:08:10 DEBUG     created index of plugins
18.01.2017 13:08:10 INFO      Checksum: Checksum validation is disabled in general configuration
18.01.2017 13:08:10 INFO      ExtractArchive: No UnRar installed
18.01.2017 13:08:10 INFO      ExtractArchive: Activated UnZip
18.01.2017 13:08:10 INFO      Activated plugins: BypassCaptcha, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterCom, UnSkipOnFail, UpdateManager, XFileSharingPro
18.01.2017 13:08:10 INFO      Deactivate plugins: AlldebridCom, Captcha9kw, CaptchaBrotherhood, DeathByCaptcha, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, Premium4Me, PremiumizeMe, RealdebridCom, RehostTo, XMPPInterface, ZeveraCom
18.01.2017 13:08:10 INFO      Downloadtime: True
18.01.2017 13:08:10 INFO      Starting ThriftBackend: 0.0.0.0:7227
18.01.2017 13:08:10 INFO      Free space: 782.62 GiB
18.01.2017 13:08:10 INFO      Activating Accounts...
18.01.2017 13:08:10 INFO      Activating Plugins...
18.01.2017 13:08:11 INFO      Starting builtin webserver: 0.0.0.0:8000
Traceback (most recent call last):
  File "//home/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8251: ordinal not in range(128)
Logged from file Plugin.py, line 88
Traceback (most recent call last):
  File "//home/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8251: ordinal not in range(128)
Logged from file Plugin.py, line 88
18.01.2017 13:08:11 DEBUG     XFileSharingPro: Pattern loaded - handling 109 hosters
18.01.2017 13:08:11 INFO      pyLoad is up and running
Fatal Python error: Couldn't create autoTLSkey mapping
Aborted
```

**Comment by aidinzolghadr** [comment]
Also before the TLS error is this:
`LinkdecrypterCom: Crypter list not found`
Googling doesn't return anything new.

**Comment by GammaC0de** [comment]
One question: do you own this server? do you have root access? if so, why do you are using linuxbrew?

**Comment by aidinzolghadr** [comment]
No I don't have root, that's exactly the reason behind linuxbrew.

**Comment by GammaC0de** [comment]
What is the output of "`echo $LC_ALL`"  ?

**Comment by aidinzolghadr** [comment]
An empty line.

**Comment by GammaC0de** [comment]
Try:
```
export LC_ALL=en_US.UTF-8
python pyLoadCore.py -d
```

**Comment by aidinzolghadr** [comment]
`
18.01.2017 14:12:14 INFO      Starting pyLoad 0.4.9
18.01.2017 14:12:14 INFO      Using home directory: /home/pyload/settings
18.01.2017 14:12:14 DEBUG     Deleting old pidfile pyload.pid
18.01.2017 14:12:14 DEBUG     Remote activated: True
18.01.2017 14:12:14 DEBUG     created index of plugins
18.01.2017 14:12:14 INFO      Checksum: Checksum validation is disabled in general configuration
18.01.2017 14:12:14 INFO      ExtractArchive: No UnRar installed
18.01.2017 14:12:14 INFO      ExtractArchive: Activated UnZip
18.01.2017 14:12:14 INFO      Activated plugins: BypassCaptcha, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterCom, UnSkipOnFail, UpdateManager, XFileSharingPro
18.01.2017 14:12:14 INFO      Deactivate plugins: AlldebridCom, Captcha9kw, CaptchaBrotherhood, DeathByCaptcha, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, Premium4Me, PremiumizeMe, RealdebridCom, RehostTo, XMPPInterface, ZeveraCom
18.01.2017 14:12:14 INFO      Downloadtime: True
18.01.2017 14:12:14 INFO      Starting ThriftBackend: 0.0.0.0:7227
18.01.2017 14:12:15 INFO      Starting builtin webserver: 0.0.0.0:8000
18.01.2017 14:12:15 INFO      Free space: 782.42 GiB
18.01.2017 14:12:15 INFO      Activating Accounts...
18.01.2017 14:12:15 INFO      Activating Plugins...
Traceback (most recent call last):
  File "//home/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8251: ordinal not in range(128)
Logged from file Plugin.py, line 88
Traceback (most recent call last):
  File "//home/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8251: ordinal not in range(128)
Logged from file Plugin.py, line 88
18.01.2017 14:12:15 DEBUG     XFileSharingPro: Pattern loaded - handling 109 hosters
18.01.2017 14:12:15 INFO      pyLoad is up and running
Fatal Python error: Couldn't create autoTLSkey mapping
Aborted`

**Comment by GammaC0de** [comment]
Again, I need the dependency check of the command `python pyLoadCore.py -s`

**Comment by aidinzolghadr** [comment]
Do you mean "system check"?

```
## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: OK

py-imaging: missing
tesseract: missing

PyQt4: missing

jinja2: OK
beaker: OK
JS engine: missing
```

And here is the report for "stauts":

`## Status ##

Features available: container decrypting, ssl connection, Webinterface

Featues missing:

no Captcha Recognition available
Only needed for some hosters and as freeuser.

Gui not available
The Graphical User Interface.

no JavaScript engine found
You will need this for some Click'N'Load links. Install Spidermonkey, ossp-js, pyv8 or rhino
You can abort the setup now and fix some dependicies if you want.
`

**Comment by aidinzolghadr** [comment]
Ping

**Comment by ngerke** [comment]
I'm running pyLoad in LXC and had the same problem.
`export LANG=C.UTF-8` does the trick for me.

**Comment by GammaC0de** [comment]
>I'm running pyLoad in LXC and had the same problem.
export LANG=C.UTF-8 does the trick for me.

👍
