### ISSUE TITLE
ERROR: "Errore durante l'importazione UpdateManager: No module named Addon"

### ISSUE THREAD

**Issue by EletroLaix** [pyload/pyload#2699]
I updated with UpdateManager.py: https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/UpdateManager.py

but continues to always give me the same error: 

`259	19.01.2017 12:25:56	ERROR	Errore durante l'importazione UpdateManager: No module named Addon`

Please help me :(

**Comment by EletroLaix** [comment]
19.01.2017 13:32:23 INFO      Avvio pyLoad 0.4.9
19.01.2017 13:32:23 INFO      Uso la cartella home: /home/pi/.pyload
19.01.2017 13:32:23 DEBUG     Remote activated: True
19.01.2017 13:32:27 DEBUG     created index of plugins
19.01.2017 13:32:27 DEBUG     ExternalScripts: Script folder download_preparing not created
19.01.2017 13:32:27 DEBUG     ExternalScripts: Script folder download_finished not created
19.01.2017 13:32:27 DEBUG     ExternalScripts: Script folder package_finished not created
19.01.2017 13:32:27 DEBUG     ExternalScripts: Script folder before_reconnect not created
19.01.2017 13:32:27 DEBUG     ExternalScripts: Script folder after_reconnect not created
19.01.2017 13:32:27 DEBUG     ExternalScripts: Script folder unrar_finished not created
19.01.2017 13:32:27 DEBUG     ExternalScripts: Script folder all_dls_finished not created
19.01.2017 13:32:27 DEBUG     ExternalScripts: Script folder all_dls_processed not created
19.01.2017 13:32:27 INFO      ExtractArchive: UnRar non installato
19.01.2017 13:32:28 INFO      ExtractArchive: Attivato UnZip
19.01.2017 13:32:28 ERROR     Errore durante l'importazione UpdateManager: No module named Addon
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 11, in <module>
    from module.plugins.internal.Addon import Addon
ImportError: No module named Addon
19.01.2017 13:32:28 INFO      Plugins attivati: CaptchaTrader, ClickAndLoad, ExternalScripts, Extr
19.01.2017 13:32:28 INFO      Plugins disattivati: Ev0InFetcher, HotFolder, IRCInterface, MergeFilishareCz, RealdebridCom, RehostTo, XMPPInterface
19.01.2017 13:32:28 INFO      Tempo di download: True
19.01.2017 13:32:28 INFO      Avvio ThriftBackend: 0.0.0.0:7227
19.01.2017 13:32:32 INFO      Free space: 143.59 GiB
19.01.2017 13:32:32 INFO      Starting builtin webserver: 0.0.0.0:8000
19.01.2017 13:32:32 INFO      Activating Accounts...
19.01.2017 13:32:32 INFO      Activating Plugins...
19.01.2017 13:32:32 INFO      pyLoad is up and running

**Comment by GammaC0de** [comment]
Please read #2000

**Comment by EletroLaix** [comment]
I just solved: I just replaced the stable version that is on ghitHub with what you install via the 0.4.9 package ... Why not update the package?

**Comment by GammaC0de** [comment]
That's a long story..
