### ISSUE TITLE
new OneFichier access

### ISSUE THREAD

**Issue by zephura** [pyload/pyload#2702]
Hello all ;)

it seems that OneFichier have changed their way to access to their links including free links.

here is an example link 3r9mf5saxw.1fichier.com
it points to a what seems temporary internal link : https://a-##.1fichier.com/?#########
? is a letter
# are numbers

**Comment by GammaC0de** [comment]
Example URL please

**Comment by zephura** [comment]
I provided an link in my previous message, here is what I read in the log file (we can see an example link)
and that link was clearly functional when I wrote this message:

> 56 	24.01.2017 21:33:16	INFO	Download starts: 3r9mf5saxw.1fichier.com
57	24.01.2017 21:33:16	WARNING	HOSTER OneFichierCom[1913]: Plugin may be unstable
58	24.01.2017 21:33:16	INFO	HOSTER OneFichierCom[1913]: Grabbing link info...
59	24.01.2017 21:33:17	INFO	HOSTER OneFichierCom[1913]: Link name: 3r9mf5saxw.1fichier.com
60	24.01.2017 21:33:17	INFO	HOSTER OneFichierCom[1913]: Link size: N/D
61	24.01.2017 21:33:17	INFO	HOSTER OneFichierCom[1913]: Link status: temp. hors ligne
62	24.01.2017 21:33:17	INFO	HOSTER OneFichierCom[1913]: Processing url: https://3r9mf5saxw.1fichier.com
63	24.01.2017 21:33:17	INFO	HOSTER OneFichierCom[1913]: Looking for direct download link...
64	24.01.2017 21:33:18	INFO	HOSTER OneFichierCom[1913]: Direct download link not found
65	24.01.2017 21:33:18	INFO	HOSTER OneFichierCom[1913]: Checking for link errors...
66	24.01.2017 21:33:18	INFO	HOSTER OneFichierCom[1913]: No errors found
67	24.01.2017 21:33:18	INFO	HOSTER OneFichierCom[1913]: Grabbing link info...
68	24.01.2017 21:33:18	INFO	HOSTER OneFichierCom[1913]: Link name: 3r9mf5saxw.1fichier.com
69	24.01.2017 21:33:18	INFO	HOSTER OneFichierCom[1913]: Link size: N/D
70	24.01.2017 21:33:18	INFO	HOSTER OneFichierCom[1913]: Link status: temp. hors ligne
71	24.01.2017 21:33:18	WARNING	Download is temporary offline: 3r9mf5saxw.1fichier.com`

**Comment by zephura** [comment]
Wow, extremely quick working answer :+1:
