### ISSUE TITLE
Obtain info about current download job

### ISSUE THREAD

**Issue by Samgarr** [pyload/pyload#2703]
Hello, it is possible to obtain some details about current download job via API? Now i am using statusServer() method in periodical_task hook to log download speed info. How i can obtain e.g., URL from which i am downloading or redirects which Pyload had to follow to get this url? Thanks!

**Comment by GammaC0de** [comment]
```python
from module.PyFile import PyFile

for pyfile in [x.active for x in self.pyload.threadManager.threads if x.active and isinstance(x.active, PyFile)]:
    print pyfile.url, pyfile.name, pyfile.size, pyfile.package().name, pyfile.getSize(), pyfile.getPercent()
```

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by Samgarr** [comment]
Thanks, just one more question. pyfile.url give me url of file. But this is url which i insert in Queue, not final url from Pyload is downloading file. Is there way how to obtain this url?

**Comment by GammaC0de** [comment]
For `SimpleHoster`/`SimpleCrypter` plugins you could use `pyfile.plugin.link`, for `Hoster`/`Crypter` based plugins there is no way without patching the core.

Anyway, I don't see what's the point in getting the download URL as it is most of the time a temporary one...

**Comment by vuolter** [comment]
Assuming that this kind of task is a pretty awful in 0.4.9, something like: `pyfile.plugin.req.lastEffectiveURL` for the real uri and `pyfile.plugin.req.lastURL` for the last processed url by the internal browser.
