### ISSUE TITLE
Pyload doesnt work anymore on QNAP TS543mini NAS

### ISSUE THREAD

**Issue by donaufisch66** [pyload/pyload#2704]
Hello, I used pyload for several month without any troubles on my QNAP TS453mini NAS.
Since yesterday I cannot logon the webinterface. In WinSCP I checked the Path and found pyload at "/share/CACHEDEV1_DATA/.qpkg/pyload".
I think bevore yesterday pyload was found at "/root/.pyload"

I tried to stop and restart pyload and python service but didnt succeed. Is there anything I can do to reactivate Pyload?  Is there any way to resart the installation to reactivate pyload with my settings?
I would like to avoid a new installation, because it worked very well. 

greetings roland

**Comment by GammaC0de** [comment]
See https://github.com/pyload/pyload/issues/2696#issuecomment-274897350

**Comment by donaufisch66** [comment]
Hi,
thank  you,but  there is no QPyload folder!
 Therefore that command doesnt work. "python /opt/QPyload/pyLoadCore.py --configdir=/opt/QPyload/CONFIG -u "

My path to pyload is "/share/CACHEDEV1_DATA/.qpkg/pyload"
I have tried to adapt the command but didn´t succeed.

I have hade that problems every few month. The only way to solve that issue, is to reinstall pyload.
I install pyLoad_4.9_x86.zip manually, then I replace updatemanager.py and the userplugins folder by the plugin from pyload-stable.zip.
That works, but I am looking for a solution to fix it an the fly.

**Comment by GammaC0de** [comment]
configdir is where `files.db` resides.
I'd look somewhere under "/share/CACHEDEV1_DATA/.qpkg/pyload"..

**Comment by GammaC0de** [comment]
No response, closing.
