### ISSUE TITLE
Error importing RapiduNet: unexpected indent (RapiduNet.py, line 20)

### ISSUE THREAD

**Issue by marcinkrk** [pyload/pyload#2705]
Hello, I have problem with plugin rapidu.net:
`# -*- coding: utf-8 -*-

import re
import time

from module.plugins.internal.Account import Account
from module.plugins.internal.utils import json

class RapiduNet(Account):
    __name__    = "RapiduNet"
    __type__    = "account"
    __version__ = "0.11"
    __status__  = "testing"

    __description__ = """Rapidu.net account plugin"""
    __license__     = "GPLv3"
    __authors__     = [("prOq", None),
                       ("Walter Purcaro", "vuolter@gmail.com")]

    PREMIUM_PATTERN = r'>Account: <b>Premium'

    VALID_UNTIL_PATTERN = r'>Account: <b>\w+ \((\d+)'

    TRAFFIC_LEFT_PATTERN = r'class="tipsyS"><b>([\d.,]+)\s*([\w^_]*)<'

    def grab_info(self, user, password, data):
        validuntil  = None
        trafficleft = -1
        premium     = False

        html = self.load("https://rapidu.net/")

        if re.search(self.PREMIUM_PATTERN, html):
            premium = True

        m = re.search(self.VALID_UNTIL_PATTERN, html)
        if m is not None:
            validuntil = time.time() + (86400 * int(m.group(1)))

        m = re.search(self.TRAFFIC_LEFT_PATTERN, html)
        if m is not None:
            trafficleft = self.parse_traffic(m.group(1), m.group(2))

        return {'validuntil': validuntil, 'trafficleft': trafficleft, 'premium': premium}

    def signin(self, user, password, data):
        self.load("https://rapidu.net/ajax.php",
                  get={'a': "getChangeLang"},
                  post={'_go' : "",
                        'lang': "en"})

        jso = json.loads(self.load("https://rapidu.net/ajax.php",
                                    get={'a': "getUserLogin"},
                                    post={'_go'     : "",
                                          'login'   : user,
                                          'pass'    : password,
                                          'remember': "1"}))

        self.log_debug(jso)

        if jso['message'] != "success":
            self.fail_login()`

Log info:
Error importing RapiduNet: unexpected indent (RapiduNet.py, line 20)
pyLoad:	0.4.9
Python:	2.7.6

**Comment by GammaC0de** [comment]
Your RapiduNet plugin is out of date, current version is v0.14.

Please stop pyload, delete your `userplugins` directory, update `UpdateManager.py` according the instructions in #2000 (including the waiting and restarting pyload while is updates part).

**Comment by marcinkrk** [comment]
Great! Works. Thank You

**Comment by GammaC0de** [comment]
👍
