### ISSUE TITLE
fresh install, doesn't download using premium accounts, corrupt files

### ISSUE THREAD

**Issue by chienb** [pyload/pyload#2706]
i did a fresh install on my ubuntu 14.04 server without any issues, but pyload is not using my premium accounts to download. i've activated real-debrid plugin and added accounts for uploaded and real-debrid, both are confirmed working. but webgui displays real-debrid status is valid and premium marked yes and uploaded is valid but premium marked no.

also, web gui and log keep saying update is available even though i'm already on v0.4.9. my log looks like this when adding a new dl (completes with small corrupt file):
http://pastebin.com/a0cTkgDS

**Comment by Slevin7** [comment]
Please stop pyload, delete your userplugins directory, update UpdateManager.py according the instructions in #2000

**Comment by chienb** [comment]
updated fine, but couldn't get real-debrid premium status. followed instructions [https://github.com/pyload/pyload/issues/2480#issuecomment-251427062](url). account is now showing valid and premium, but downloads return 503 error. my log:
`
121	29.01.2017 02:26:29	INFO	Starting pyLoad 0.4.9
122	29.01.2017 02:26:29	INFO	Using home directory: /home/owner/.pyload
123	29.01.2017 02:26:29	INFO	Activated plugins: ClickAndLoad, ExternalScripts, ExtractArchive, LinkdecrypterComHook, MergeFiles, RealdebridComHook, UnSkipOnFail, UserAgentSwitcher, XFileSharingPro
124	29.01.2017 02:26:29	INFO	Deactivate plugins: AlldebridComHook, AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMeHook, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinksnappyComHook, MegaDebridEuHook, MegaRapidoNetHook, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, UpdateManager, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
125	29.01.2017 02:26:29	INFO	Downloadtime: True
126	29.01.2017 02:26:29	INFO	Starting ThriftBackend: 0.0.0.0:7227
127	29.01.2017 02:26:29	INFO	Free space: 820.57 GiB
128	29.01.2017 02:26:29	INFO	Activating Accounts...
129	29.01.2017 02:26:29	WARNING	RealdebridCom: logged in
130	29.01.2017 02:26:30	INFO	Starting builtin webserver: 0.0.0.0:8000
131	29.01.2017 02:26:30	INFO	Activating Plugins...
132	29.01.2017 02:26:30	INFO	XFileSharingPro: Handling any hoster I can!
133	29.01.2017 02:26:30	INFO	XFileSharingPro: Handling any crypter I can!
134	29.01.2017 02:26:30	INFO	pyLoad is up and running
135	29.01.2017 02:26:32	INFO	RealdebridComHook: Reloading supported hoster list
136	29.01.2017 02:26:32	INFO	LinkdecrypterComHook: Reloading supported crypter list
137	29.01.2017 02:26:32	INFO	LinkdecrypterComHook: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
138	29.01.2017 02:26:32	INFO	RealdebridComHook: Hosters not overwritten: real-debrid.com
139	29.01.2017 02:26:40	INFO	ClickAndLoad: Proxy listening on 0.0.0.0:9666
140	29.01.2017 02:26:40	INFO	LinkdecrypterComHook: Reloading supported crypter list
141	29.01.2017 02:26:40	INFO	LinkdecrypterComHook: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, onekh.de, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, share-links.biz, stealth.to, tinyurl.com, tny.cz
142	29.01.2017 02:26:40	INFO	RealdebridComHook: Reloading supported hoster list
143	29.01.2017 02:26:40	INFO	RealdebridComHook: Hosters not overwritten: real-debrid.com
144	29.01.2017 02:26:55	INFO	Added package 3 containing 1 links
145	29.01.2017 02:26:56	INFO	Download starts: DDLValley.cool_Taboo.UK.S01E04.HDTV.x264-ORGANiC.mkv
146	29.01.2017 02:26:56	WARNING	Download failed: DDLValley.cool_Taboo.UK.S01E04.HDTV.x264-ORGANiC.mkv | Bad server response: 503 Service Unavailable
147	29.01.2017 02:26:56	INFO	UnSkipOnFail: Looking for skipped duplicates of: DDLValley.cool_Taboo.UK.S01E04.HDTV.x264-ORGANiC.mkv (pid:3)
148	29.01.2017 02:26:56	INFO	UnSkipOnFail: No duplicates found
149	29.01.2017 02:28:04	INFO	Added package 1 containing 1 links
150	29.01.2017 02:28:04	INFO	Download starts: https://www.filefactory.com/file/5pa9kcobxsf9/The.Path.S02E01.720p.HDTV.x264-FLEET.mkv
151	29.01.2017 02:28:04	WARNING	Download failed: https://www.filefactory.com/file/5pa9kcobxsf9/The.Path.S02E01.720p.HDTV.x264-FLEET.mkv | Bad server response: 503 Service Unavailable
152	29.01.2017 02:28:04	INFO	UnSkipOnFail: Looking for skipped duplicates of: https://www.filefactory.com/file/5pa9kcobxsf9/The.Path.S02E01.720p.HDTV.x264-FLEET.mkv (pid:4)
153	29.01.2017 02:28:04	INFO	UnSkipOnFail: No duplicates found
`

**Comment by Slevin7** [comment]
Well the file you would like to download is offline. (Or the link in the log file isn't working)

**Comment by chienb** [comment]
the link in the log has been removed as of today, i just tried adding a valid uploaded.net file to the queue and still getting 
`WARNING	Download failed: http://uploaded.net/file/ie995x5j/DDLValley.cool_Blk.sls.S04E01.HDTV.x264-FLEET.mkv | Bad server response: 503 Service Unavailable`

**Comment by Slevin7** [comment]
it looks like the api url isnt the right one anymore.
pyload uses https://real-debrid.com/api/*
based on the api docoumentation it schould use https://api.real-debrid.com/rest/1.0/*
i think someone should change it.
i would love to test it but i havent had a realdebird acc either the skills to do it.

**Comment by GammaC0de** [comment]
@chienb If you are willing to send your account information (you can change the password to a temporary one), I can try to fix this.

If so, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by chienb** [comment]
@GammaC0de i emailed you my logins, hoping for a fix soon!

**Comment by GammaC0de** [comment]
@chienb OK, I will do my best but I don't promise I can really fix it.

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/14d26e63c83a49fcafe8101d318f395a137b3906

**Comment by chienb** [comment]
@GammaC0de did a fresh reinstall and updated with UpdateManager but changes not applying. how to apply your commits properly?

**Comment by GammaC0de** [comment]
Start pyload from the console with `python pyLoadCore.py -d`, start a download and port the result log here.

**Comment by chienb** [comment]
http://pastebin.com/Qh035VQv

**Comment by GammaC0de** [comment]
This is weird, I tested the same link and it works fine..
Did you put the API token in the password (you get this from https://real-debrid.co/apitoken)?

**Comment by chienb** [comment]
yup, I did the following:

1. uninstalled pyload, deleted home and install folders
2. reinstalled pyload-cli_0.4.9_all.deb from download page
3. deleted default UpdateManager.py and replaced with https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/e67c25e144991612519940a67d8417ea43069a66/UpdateManager.py
4. start pyload, enabled realdebrid (default on), added login details, apitoken. account and premium both showing green
5. adding a link to queue fails to download and displays 503 error

**Comment by GammaC0de** [comment]
I think you should installed pyload_0.4.9_any.ipk

**Comment by chienb** [comment]
i ended doing git clone the stable branch. real-debrid is still not working for me, but uploaded.net works (starts at line 59): http://pastebin.com/DU3s8PQn

**Comment by GammaC0de** [comment]
I think I know  what is your problem:
503 is CloudFlare's DDoS cool-down protection.

You should replace `module/network/HTTPRequest.py` with this one  and then activate  https://gist.github.com/GammaC0de/cc182933bc05c13ac69e807cb982b643/raw/515a3eef6a62e23ac807ae9f21c74b31d574524e/HTTPRequest.py and then activate CloudFlareDdos plugin.

**Comment by chienb** [comment]
still no go :(
http://pastebin.com/PpHsYa7H

**Comment by GammaC0de** [comment]
Can you change `hoster\RealdebrifCom.py`'s `api_response()` to this
```
    def api_response(self, namespace, get={}, post={}):
        from module.network.HTTPRequest import BadHeader
        try:
            json_data = self.load(self.API_URL + namespace, get=get, post=post)
        except BadHeader, e:
            self.log_debug("BadHeader: %s" % e.content)
            self.fail()

        return json.loads(json_data)
```
and post the output?

**Comment by chienb** [comment]
http://pastebin.com/KXbD7czD

ip-not-allowed on line 30, my ip is banned?

**Comment by GammaC0de** [comment]
I guess so, can you change your IP?

**Comment by chienb** [comment]
i don't think so, my server is located in NL. maybe realdebrid bans ip in those countries?

**Comment by GammaC0de** [comment]
I don't know, you should contact their support.

**Comment by GammaC0de** [comment]
Closing but please update on any progress. 👍

**Comment by GammaC0de** [comment]
Please update of any progress.

**Comment by chienb** [comment]
confirmed ip ban
