### ISSUE TITLE
QUESTION: Where is the new web-ui?

### ISSUE THREAD

**Issue by buehler** [pyload/pyload#2710]
Hey guys

I tried to build and start pyload from the source, to let it run in a docker box locally. As I'm fiddling around with the dependencies and stuff, I saw you have pictures of the new UI on pyload.net. Where is that ui actually? Is there a way to download it and compile it locally?

I don't really get your repo setup, I'm sorry :-/

Which code is the actual public one and which code is development stage?

Cheers and thanks for your effort!
Chris

**Comment by GammaC0de** [comment]
For docker , see https://github.com/obi12341/docker-pyload

As for the new UI, it is not merged to the current version yet although there is a patch to manually install it:
* Extract `templates` and `media` directories from the attached zip file  the to `<pyload_directory>\module\web` overwriting  files if needed.
* Edit `<pyload_directory>\module\web\webinterface.py` and add the below line after the line `loader = PrefixLoader({`
```
    "Next": FileSystemLoader(join(PROJECT_DIR, "templates", "Next")),
```

[Nexttheme.zip](https://github.com/pyload/pyload/files/743001/Nexttheme.zip)

**Comment by buehler** [comment]
Cool thing @GammaC0de 
Thanks for the help!

Another quick question (just for my interest)
How would I start, if I'd make my own frontend? Lets say, I code a SPA for this with angular or something. Would I be able to run it on pyload itself, or must it be proxied and use some remote UI stuff?

I could imagine that I may have time to code a new frontend, and when I'm done share it with you guys.

Cheers

**Comment by GammaC0de** [comment]
I don't understand what are you trying to achieve, please explain (what exactly is a SPA? what its got to do with pyLoad?)

**Comment by buehler** [comment]
Actually, I had an idea to write "my own" web ui for pyload. But as a SPA (SPA means single-page-application, made with react or angular or something like that). Imagine an application like gmail or something. 

As a matter of fact, I'm a web / frontend engineer, so I thought, why not.

What it would require: the pyload core should deliver the index.html, and all the assets, and expose an API for all the information needed in frontend.

Now the main question would be if it's possible to just deliver assets and index.html, or is it hard wired to the template. And the second question is: is there an API (like for the windows-gui) to manage everything for pyload, because that could be enough.

**Comment by GammaC0de** [comment]
Keep in mind that it should be lightweight because it runs on a low resource NAS.

You should understand the infrastructure in `module\web\` to be able to replace the server with your own.

As for API, you would do a `from webinterface import PYLOAD` and then you can call all the functions declared in `api.py` e.g. `PYLOAD.isCaptchaWaiting()`

**Comment by buehler** [comment]
Alright, thank you 👍 

The load on the machine should be very small since only the html / js / css is delivered. The rest of the app runs in the browser.

I'll have a look at it, thank you

**Comment by sraedler** [comment]
Please Open an pull request, when you're done with your theme :)
I would really like to use something like that, too

**Comment by sNiXx** [comment]
> 
> As for the new UI, it is not merged to the current version yet although there is a patch to manually install it:
> 
>     * Extract `templates` and `media` directories from the attached zip file  the to `<pyload_directory>\module\web` overwriting  files if needed.
> 
>     * Edit `<pyload_directory>\module\web\webinterface.py` and add the below line after the line `loader = PrefixLoader({`
> 
> 
> ```
>     "Next": FileSystemLoader(join(PROJECT_DIR, "templates", "Next")),
> ```
> 
>     * On the webui choose theme "Next".
>       [Nexttheme.zip](https://github.com/pyload/pyload/files/743001/Nexttheme.zip)

Just wanted to update the second step of this tutorial quickly, as it seems to be outdated. When editing `<pyload_directory>\module\web\webinterface.py` you want to change the following line
```
mapping = {'js': FileSystemLoader(join(PROJECT_DIR, 'media', 'js'))}
```
to
```
mapping = {
'js': FileSystemLoader(join(PROJECT_DIR, 'media', 'js')),
"Next": FileSystemLoader(join(PROJECT_DIR, "templates", "Next"))
}
```
Also, for me there was no way to "choose" the theme, I had to manually replace "classic" with "Next" in the "Template" field (Config > General > Webinterface > Template).

I really like this theme and think it should be the new standard...

**Comment by GammaC0de** [comment]
@sNiXx The info is outdated,
If you get the latest stable branch, these changes are already in.
Also, a new web-template called `pyplex` is also included and the setup wizard (`pyLoadCore.py -s`) now has an option to choose the active web-template.

**Comment by sNiXx** [comment]
@GammaC0de Thanks for the information. Are the installation instructions from issue 2000 still valid, then? As I'm using Docker containers, any suggestions which one to use?
Btw: Why go this route and not update to 0.4.10 instead?

**Comment by GammaC0de** [comment]
For docker see this https://github.com/obi12341/docker-pyload, it is up-to-date with the stable branch.
