### ISSUE TITLE
Hoster List Premium.to

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#2715]
Hello, i have a small problem with premium.to. I Think, pyload did not load the corectly hoster List.
2025	02.02.2017 17:05:48	WARNING	ACCOUNT PremiumTo: descriptor 'strip' requires a 'str' object but received a 'unicode' | Waiting 1 minute and retry
2024	02.02.2017 17:05:48	DEBUG	ACCOUNT PremiumTo: LOAD URL http://premium.to/api/hosters.php | redirect=True | cookies=True | get={'username': 'XXX', 'password': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
2023	02.02.2017 17:05:48	DEBUG	ACCOUNT PremiumTo: Hoster list for user `XXX`: []
2022	02.02.2017 17:05:48	WARNING	ACCOUNT PremiumTo: Error loading hoster list for user `XXX` | descriptor 'strip' requires a 'str' object but received a 'unicode'
2021	02.02.2017 17:05:48	ERROR	ACCOUNT PremiumTo: Error performing periodical task | 'data'
2020	02.02.2017 17:05:48	DEBUG	ACCOUNT PremiumTo: LOAD URL http://premium.to/api/hosters.php | redirect=True | cookies=True | get={'username': 'XXX', 'password': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
2019	02.02.2017 17:05:48	INFO	ACCOUNT PremiumTo: Loading hoster list for user `XXX`...

**Comment by GammaC0de** [comment]
Account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by Mister-XY** [comment]
You have a message

**Comment by GammaC0de** [comment]
Test account has no traffic left so I could not actually download...

**Comment by Mister-XY** [comment]
You have a new message with my account.

**Comment by GammaC0de** [comment]
Tested and works.  😄

**Comment by Mister-XY** [comment]
Thank you,
Only one question, what is this?
04.02.2017 07:38:54	ERROR	ACCOUNT PremiumTo: Error performing periodical task | 'data'

**Comment by GammaC0de** [comment]
@Mister-XY This is a known minor issue that I will deal with later.

**Comment by Mister-XY** [comment]
Ah ok, thats very nice to here it. You make a great job here. Have you found the error in filecrypt?

**Comment by GammaC0de** [comment]
Not yet, sorry, I have busy times since MultiAccount is back, will let you know.

**Comment by Mister-XY** [comment]
Ok, make pyload great again ^^

**Comment by GammaC0de** [comment]
>04.02.2017 07:38:54 ERROR ACCOUNT PremiumTo: Error performing periodical task | 'data'

This issue is now fixed with https://github.com/pyload/pyload/commit/f152233d5a078a970dcac9b233670a4f7b733f86
