### ISSUE TITLE
ExtractArchive fails after succesfull extraction

### ISSUE THREAD

**Issue by kasperj** [pyload/pyload#2716]
ExtractArchive fails after extraction is finished with "Cannot change attributes"

04.02.2017 11:04:18	ERROR	ADDON ExtractArchive: IGuvbKGOaq5O6jC.part1.rar | Extract failed
?	?	WARNING: Cannot change attributes of /mnt/download/FOLDER/FILE01
?	?	WARNING: Cannot change attributes of /mnt/download/FOLDER/FILE02
?	?	WARNING: Cannot change attributes of /mnt/download/FOLDER/FILE03
?	?	WARNING: Cannot change attributes of /mnt/download/FOLDER/FILE04
04.02.2017 11:04:18	ERROR	ADDON ExtractArchive: PART01 | Archive error | WARNING: Cannot change attributes of /mnt/download/Sample/FILE05
04.02.2017 11:21:56	DEBUG	EXTRACTOR UnRar: EXECUTE unrar x -o- -or -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -pscenedownloads /mnt/download/FILE01 /mnt/download/FOLDER
04.02.2017 11:21:56	DEBUG	ADDON ExtractArchive: Extracting using password: XXXXX
04.02.2017 11:03:13	INFO	ADDON ExtractArchive: IGuvbKGOaq5O6jC.part1.rar | Password protected
04.02.2017 11:03:13	INFO	ADDON ExtractArchive: IGuvbKGOaq5O6jC.part1.rar | Extract to: /mnt/download/FOLDER/
04.02.2017 11:03:13	INFO	ADDON ExtractArchive: Check package: PACKAGE01
04.02.2017 11:03:13	INFO	Package finished: PACKAGE01

**Comment by GammaC0de** [comment]
Seems like a permissions issue, check /mnt/download.

**Comment by kasperj** [comment]
got 770 on all folders and files

**Comment by GammaC0de** [comment]
Stop pyload and start it from the console with `python pyLoadCore.py -d`, retry the download and then post the log here.

**Comment by kasperj** [comment]
Probably interested in this:

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/PluginThread.py", line 459, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 185, in extract_queued
    if self.extract(packages, thread):  #@NOTE: check only if all gone fine, no failed reporting for now
  File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 331, in extract
    new_files = self._extract(pyfile, archive, pypack.password)
  File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 448, in _extract
    archive.extract(pw)
  File "/opt/pyload/module/plugins/internal/UnRar.py", line 153, in extract
    raise ArchiveError(err)

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/PluginThread.py", line 459, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 185, in extract_queued
    if self.extract(packages, thread):  #@NOTE: check only if all gone fine, no failed reporting for now
  File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 331, in extract
    new_files = self._extract(pyfile, archive, pypack.password)
  File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 509, in _extract
    raise Exception(_("Extract failed"))
Exception: Extract failed

**Comment by GammaC0de** [comment]
This error seems to come from `unrar` program itself..
Try extracting from the console and see what happens.

**Comment by kasperj** [comment]
Actually coming from unrar, but just as a warning, ExtractArchive fails, but extraction successfully finishes

UNRAR 5.30 beta 2 freeware      Copyright (c) 1993-2015 Alexander Roshal
Extracting from IGuvbKGOaq5O6jC.part1.rar
Extracting  tvp-theblacklist-s04e04-1080p-sample.mkv                  OK 
WARNING: Cannot change attributes of tvp-theblacklist-s04e04-1080p-sample.mkv
Extracting  tvp-theblacklist-s04e04-1080p.jpg                         OK 
WARNING: Cannot change attributes of tvp-theblacklist-s04e04-1080p.jpg
Extracting  tvp-theblacklist-s04e04-1080p.mkv                         56%

**Comment by GammaC0de** [comment]
Can you update your unrar?

**Comment by kasperj** [comment]
Seems to be the newest version as seen above

**Comment by GammaC0de** [comment]
check http://www.rarlab.com/rar_add.htm

**Comment by kasperj** [comment]
UNRAR 5.21 beta 2 freeware      Copyright (c) 1993-2015 Alexander Roshal
Extracting from IGuvbKGOaq5O6jC.part1.rar
Extracting  tvp-theblacklist-s04e04-1080p-sample.mkv                  OK 
WARNING: Cannot change attributes of tvp-theblacklist-s04e04-1080p-sample.mkv

**Comment by GammaC0de** [comment]
is /mnt/download/ FAT filesystem?

**Comment by kasperj** [comment]
Mounted SMB Share, that seems to be the issue, just copied the files to a local place and no warnings

**Comment by GammaC0de** [comment]
Well, that solves the mystery: no permission operations are allowed on a FAT filesystem.

I think I have a solution for you, few moments please.

**Comment by GammaC0de** [comment]
Unrar plugin update https://github.com/pyload/pyload/commit/eb8c7e2d2c4b6c61c2132291427d1ebd6254eb4a

Added a config option to ignore errors.

Unfotunatly, config options are ignored for internal plugins 😢 so you have to change the code at [UnRar.py#L155](https://github.com/pyload/pyload/blob/eb8c7e2d2c4b6c61c2132291427d1ebd6254eb4a/module/plugins/internal/UnRar.py#L155) from `False` to `True`.

**Comment by kasperj** [comment]
Thank you, working again with the update and fix

**Comment by efelon** [comment]
Is there still no other way to set this option `ignore_warnings` for the internal UnRar plugin, other than changing the file as @GammaC0de https://github.com/pyload/pyload/issues/2716#issuecomment-277437626 suggested?
