### ISSUE TITLE
relink.us wrong title name

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#2720]
Hello, i have found a little error. 
If i load via click and load from relink.us, i have a wrong title name.
The title from the new container ist not the name from title. It is "http://www.relink.us/f/a99fd62cefb20e8e5faf66627ae6d1"
instead "Charlotte Link - Die Betrogene (ungekürzt)".
Is it possible to change it to title instead header title?
09.02.2017 18:52:12	INFO	Added package http://relink.to/view.php?id=a99fd62cefb20e8e5faf66627ae6d1 containing 4 links

**Comment by GammaC0de** [comment]
this is from the page source of http://relink.to/view.php?id=a99fd62cefb20e8e5faf66627ae6d1:
```html
<form id="cnl_form-a99fd62cefb20e8e5faf66627ae6d1" class="cnl_form" action="http://127.0.0.1:9666/flash/addcrypted2" target="hidden" method="post" style="display:block; float:right;">
    <input type="hidden" name="source" value="http://relink.to/view.php?id=a99fd62cefb20e8e5faf66627ae6d1">
    <input type="hidden" name="crypted" id="cnl_links" value="s/ehKEWWm1vXVDjwXgWH7u7CLpvwhjbugl2NbmVHQnuqCnmQ7EV2k5WxD42MWJaYu16l8HHXUoajhHbvVq4nNu4rFVSiC3fkyeYg1LQU+vU3RId2YjHVgPyA4UpJuNumVwzB2uHpfAT9DikviXLOHcTFEOCxmOFHZVA5OzGbzrztZ3kbr6Ah3YV1FVlljAJI">
    <input type="hidden" name="jk" value="function f(){ var org = '33837383038323433383237363338343'; var dec = ''; var i = 0; for(i=32;i>=0;i--){ dec+=org.substring(i,i+1); } return dec; }" />
    <input type="image" src="images/jdownloader_not_running.jpg" alt="Click'n'load" id="cnl_button-a99fd62cefb20e8e5faf66627ae6d1" class="cnl_button" disabled="disabled" />
</form>
```

As you can see, there is no "package" parameter and "source" parameter contains the URL instead of the title

**Comment by Mister-XY** [comment]
http://relink.to/view.php?id=a99fd62cefb20e8e5faf66627ae6d1 and this is the name from link?

**Comment by GammaC0de** [comment]
Yes:
```
def addcrypted2():

    package = request.forms.get("source", None)
```


`<input type="hidden" name="source" value="http://relink.to/view.php?id=a99fd62cefb20e8e5faf66627ae6d1">`

**Comment by Mister-XY** [comment]
Ok,  that's not so good.
