### ISSUE TITLE
FREENAS JAIL (6TB ZFS) - IndexError: list index out of range

### ISSUE THREAD

**Issue by zml71** [pyload/pyload#2721]
Hello i have noticed problem with pyload 0,4.9 in FreeNas 9.10 Jail

it looks like can not read my 6 TB drive size, maybe you got already solution but i have not found it.

**log below**
`
root@PyLoad:/srv/pyLoad # ./pyLoadCore.py -v`
`pyLoad 0.4.9`
`root@PyLoad:/srv/pyLoad # ./pyLoadCore.py`
`10.02.2017 17:09:43 INFO      Starting pyLoad 0.4.9`
`10.02.2017 17:09:43 INFO      Using home directory: /srv/pyLoad/configs`
`10.02.2017 17:09:44 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing`
`10.02.2017 17:09:44 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP`
`10.02.2017 17:09:44 INFO      Downloadtime: True
Traceback (most recent call last):`
`10.02.2017 17:09:45 INFO      Starting threaded webserver: 192.168.1.13:8000`
 ` File "./pyLoadCore.py", line 667, in <module>`
   ` main()`
 ` File "./pyLoadCore.py", line 658, in main`
 `   pyload_core.start()`
`  File "./pyLoadCore.py", line 412, in start`
   ` self.log.info(_("Free space: %s") % formatSize(spaceLeft))`
 ` File "/srv/pyLoad/module/utils.py", line 95, in formatSize`
    `return "%.2f %s" % (size, sizes[steps])`
`IndexError: list index out of range`
`root@PyLoad:/srv/pyLoad # df`
`Filesystem         1K-blocks    Used      Avail Capacity  Mounted on`
`Main/jails/PyLoad 6377510295 3476921 6374033374     0%    /`
`root@PyLoad:/srv/pyLoad # df -h`
`Filesystem           Size    Used   Avail Capacity  Mounted on`
`Main/jails/PyLoad    5.9T    3.3G    5.9T     0%    /
`

**Comment by GammaC0de** [comment]
@zml71 Start pyLoad with `./pyLoadCore.py -d` and then post the log.

**Comment by zml71** [comment]
Hello i do not see anything special in log now 



**root@PyLoad:/srv/pyLoad # ./pyLoadCore.py -d**
11.02.2017 11:37:38 INFO      Starting pyLoad 0.4.9
11.02.2017 11:37:38 INFO      Using home directory: /srv/pyLoad/configs
11.02.2017 11:37:38 DEBUG     Deleting old pidfile pyload.pid
11.02.2017 11:37:38 DEBUG     Remote activated: False
11.02.2017 11:37:39 DEBUG     created index of plugins
11.02.2017 11:37:39 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
11.02.2017 11:37:39 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
11.02.2017 11:37:39 INFO      Downloadtime: True
Traceback (most recent call last):
11.02.2017 11:37:40 INFO      Starting threaded webserver: 192.168.1.13:8000
  File "./pyLoadCore.py", line 667, in <module>
    main()
  File "./pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "./pyLoadCore.py", line 412, in start
    self.log.info(_("Free space: %s") % formatSize(spaceLeft))
  File "/srv/pyLoad/module/utils.py", line 95, in formatSize
    return "%.2f %s" % (size, sizes[steps])
IndexError: list index out of range



**root@PyLoad:/srv/pyLoad # cat configs/Logs/log.txt**
11.02.2017 11:37:38 INFO      Starting pyLoad 0.4.9
11.02.2017 11:37:38 INFO      Using home directory: /srv/pyLoad/configs
11.02.2017 11:37:38 DEBUG     Deleting old pidfile pyload.pid
11.02.2017 11:37:38 DEBUG     Remote activated: False
11.02.2017 11:37:39 DEBUG     created index of plugins
11.02.2017 11:37:39 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
11.02.2017 11:37:39 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
11.02.2017 11:37:39 INFO      Downloadtime: True
11.02.2017 11:37:40 INFO      Starting threaded webserver: 192.168.1.13:8000
root@PyLoad:/srv/pyLoad #

**Comment by zml71** [comment]
Incidentialy closed :) sorry

**Comment by GammaC0de** [comment]
Try changing [utils.py#L91](https://github.com/pyload/pyload/blob/stable/module/utils.py#L91) to:
`    sizes = ["B", "KiB", "MiB", "GiB", "TiB", "PiB"]`

**Comment by zml71** [comment]
It has helped, thanks a lot :)

**Comment by war6000** [comment]
> Try changing [utils.py#L91](https://github.com/pyload/pyload/blob/stable/module/utils.py#L91) to:
> ` sizes = ["B", "KiB", "MiB", "GiB", "TiB", "PiB"]`

worked like a charm, thanks (freenas 11.1-u6)
