### ISSUE TITLE
DebridItaliaCom Fallback to free Although premium available

### ISSUE THREAD

**Issue by geronimoronin** [pyload/pyload#2723]
13.02.2017 14:41:14	INFO	HOSTER DebridItaliaCom[1202]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/xxxxxx
662	13.02.2017 14:41:14	DEBUG	HOSTER DebridItaliaCom[1202]: DebridItaliaCom | Config option `fallback` not found, use default `True`
663	13.02.2017 14:41:14	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
664	13.02.2017 14:41:14	DEBUG	HOSTER DebridItaliaCom[1202]: DebridItaliaCom | Config option `revert_failed` not found, use default `True`
665	13.02.2017 14:41:14	WARNING	Download failed: 82g9zb1a | Required account not found
666	13.02.2017 14:41:14	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
667	13.02.2017 14:41:15	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': '3i0iiyfb', 'url': u'http://www.uploaded.net/file/xxxxxxx', 'pattern': {}, 'size': 0}
668	13.02.2017 14:41:15	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 82g9zb1a (pid:11)
669	13.02.2017 14:41:15	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Previous link info: {}
670	13.02.2017 14:41:15	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link name: 3i0iiyfb
671	13.02.2017 14:41:15	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link size: N/D
672	13.02.2017 14:41:15	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link status: starte
673	13.02.2017 14:41:15	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/xxxxxx
674	13.02.2017 14:41:15	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | LOAD URL http://www.uploaded.net/file/xxxxxx | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
675	13.02.2017 14:41:15	INFO	ADDON UnSkipOnFail: No duplicates found
676	13.02.2017 14:41:15	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Checking for link errors...
677	13.02.2017 14:41:15	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | No errors found
678	13.02.2017 14:41:15	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Grabbing link info...
679	13.02.2017 14:41:15	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': '3i0iiyfb', 'url': u'http://www.uploaded.net/file/3i0iiyfb', 'pattern': {}, 'size': 0}
680	13.02.2017 14:41:15	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': '3i0iiyfb', 'url': u'http://www.uploaded.net/file/3i0iiyfb', 'pattern': {}, 'size': 0}
681	13.02.2017 14:41:15	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link name: 3i0iiyfb
682	13.02.2017 14:41:15	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link size: N/D
683	13.02.2017 14:41:15	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link status: starte
684	13.02.2017 14:41:15	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Processing as premium download...
685	13.02.2017 14:41:15	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'u': 'user*******', 'link': u'http://www.uploaded.net/file/xxxxx', 'generate': '', 'p': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
686	13.02.2017 14:41:16	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Config option `fallback` not found, use default `True`
687	13.02.2017 14:41:16	WARNING	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Premium download failed | offline
688	13.02.2017 14:41:16	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
689	13.02.2017 14:41:16	INFO	Download restarted: 3i0iiyfb | Fallback to free processing
690	13.02.2017 14:41:16	INFO	Download starts: 39kk1qrv
691	13.02.2017 14:41:16	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
692	13.02.2017 14:41:16	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Plugin version: 0.23
693	13.02.2017 14:41:16	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Plugin status: testing
694	13.02.2017 14:41:16	WARNING	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Plugin may be unstable
695	13.02.2017 14:41:16	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
696	13.02.2017 14:41:16	INFO	ACCOUNT DebridItaliaCom: Grabbing account info for user `ger*******`...
697	13.02.2017 14:41:16	DEBUG	ACCOUNT DebridItaliaCom: LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'p': '**********', 'u': 'user*******', 'check': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
698	13.02.2017 14:41:16	INFO	Download starts: 3i0iiyfb
699	13.02.2017 14:41:16	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
700	13.02.2017 14:41:16	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Plugin version: 0.23
701	13.02.2017 14:41:16	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Plugin status: testing
702	13.02.2017 14:41:16	WARNING	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Plugin may be unstable
703	13.02.2017 14:41:16	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
704	13.02.2017 14:41:16	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Grabbing link info...
705	13.02.2017 14:41:16	DEBUG	ACCOUNT DebridItaliaCom: Account info for user `ger*******`: {'login': {'timestamp': 1486992953.8046041, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1513171170, 'login': 'ger*******', 'type': 'DebridItaliaCom', 'options': {'limitdl': ['0']}}}
706	13.02.2017 14:41:16	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Grabbing link info...
707	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': '3i0iiyfb', 'url': u'http://www.uploaded.net/file/xxxxxxx', 'pattern': {}, 'size': 0}
708	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': '3i0iiyfb', 'url': u'http://www.uploaded.net/file/xxxxxx', 'pattern': {}, 'size': 0}
709	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link name: 3i0iiyfb
710	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link size: N/D
711	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Link status: starte
712	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/xxxxxx
713	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Config option `fallback` not found, use default `True`
714	13.02.2017 14:41:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
715	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': '39kk1qrv', 'url': u'http://www.uploaded.net/file/xxxxxxx', 'pattern': {}, 'size': 0}
716	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Previous link info: {}
717	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link name: 39kk1qrv
718	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link size: N/D
719	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link status: starte
720	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/xxxxxx
721	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | LOAD URL http://www.uploaded.net/file/xxxxxxx | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
722	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1203]: DebridItaliaCom | Config option `revert_failed` not found, use default `True`
723	13.02.2017 14:41:17	WARNING	Download failed: 3i0iiyfb | Required account not found
724	13.02.2017 14:41:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
725	13.02.2017 14:41:17	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 3i0iiyfb (pid:11)
726	13.02.2017 14:41:17	INFO	ADDON UnSkipOnFail: No duplicates found
727	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Checking for link errors...
728	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | No errors found
729	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Grabbing link info...
730	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': '39kk1qrv', 'url': u'http://www.uploaded.net/file/xxxxxx', 'pattern': {}, 'size': 0}
731	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': '39kk1qrv', 'url': u'http://www.uploaded.net/file/xxxxxxx', 'pattern': {}, 'size': 0}
732	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link name: 39kk1qrv
733	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link size: N/D
734	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link status: starte
735	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Processing as premium download...
736	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'u': 'ger*******', 'link': u'http://www.uploaded.net/file/xxxxxx', 'generate': '', 'p': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
737	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Config option `fallback` not found, use default `True`
738	13.02.2017 14:41:17	WARNING	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Premium download failed | offline
739	13.02.2017 14:41:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
740	13.02.2017 14:41:17	INFO	Download restarted: 39kk1qrv | Fallback to free processing
741	13.02.2017 14:41:17	INFO	Download starts: 39kk1qrv
742	13.02.2017 14:41:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
743	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Plugin version: 0.23
744	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Plugin status: testing
745	13.02.2017 14:41:17	WARNING	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Plugin may be unstable
746	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
747	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Grabbing link info...
748	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': '39kk1qrv', 'url': u'http://www.uploaded.net/file/xxxxxx', 'pattern': {}, 'size': 0}
749	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': '39kk1qrv', 'url': u'http://www.uploaded.net/file/xxxxxxx', 'pattern': {}, 'size': 0}
750	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link name: 39kk1qrv
751	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link size: N/D
752	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Link status: starte
753	13.02.2017 14:41:17	INFO	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/xxxxxxx
754	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Config option `fallback` not found, use default `True`
755	13.02.2017 14:41:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
756	13.02.2017 14:41:17	DEBUG	HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Config option `revert_failed` not found, use default `True`
757	13.02.2017 14:41:17	WARNING	Download failed: 39kk1qrv | Required account not found
758	13.02.2017 14:41:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
759	13.02.2017 14:41:17	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 39kk1qrv (pid:11)
760	13.02.2017 14:41:17	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
`665 13.02.2017 14:41:14 WARNING Download failed: 82g9zb1a | Required account not found`
`738 13.02.2017 14:41:17 WARNING HOSTER DebridItaliaCom[1204]: DebridItaliaCom | Premium download failed | offline`

Does this happens every time?

It seems that you have problems with your DebridItaliaCom account, no?

**Comment by geronimoronin** [comment]
The problem is since yesterday and it does not always come,With the account is everything OK I have tried with Jdownloader has worked.

**Comment by geronimoronin** [comment]
13.02.2017 15:09:55	DEBUG	ACCOUNT DebridItaliaCom: Account info for user `ger*******`: {'login': {'timestamp': 1486994992.2459159, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1513171170, 'login': 'ger*******', 'type': 'DebridItaliaCom', 'options': {'limitdl': ['0']}}}
2	13.02.2017 15:09:55	INFO	ACCOUNT DebridItaliaCom: Grabbing account info for user `ger*******`...
3	13.02.2017 15:09:55	DEBUG	ACCOUNT DebridItaliaCom: LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'p': '**********', 'u': 'ger*******', 'check': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
4	13.02.2017 15:09:55	DEBUG	ACCOUNT DebridItaliaCom: Account info for user `ger*******`: {'login': {'timestamp': 1486994992.2459159, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1513171170, 'login': 'ger*******', 'type': 'DebridItaliaCom', 'options': {'limitdl': ['0']}}}
5	13.02.2017 15:09:55	INFO	Activating Plugins...

**Comment by GammaC0de** [comment]
How many times this has happened?

**Comment by geronimoronin** [comment]
Since this morning does not work anymore 

13.02.2017 19:33:53	INFO	Download starts: xonyfyx1
2	13.02.2017 19:33:53	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
3	13.02.2017 19:33:53	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Plugin version: 0.23
4	13.02.2017 19:33:53	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Plugin status: testing
5	13.02.2017 19:33:53	WARNING	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Plugin may be unstable
6	13.02.2017 19:33:53	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
7	13.02.2017 19:33:53	INFO	ACCOUNT DebridItaliaCom: Grabbing account info for user `ger*******`...
8	13.02.2017 19:33:53	DEBUG	ACCOUNT DebridItaliaCom: LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'p': '**********', 'u': 'ger*******', 'check': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
9	13.02.2017 19:33:53	DEBUG	ACCOUNT DebridItaliaCom: Account info for user `ger*******`: {'login': {'timestamp': 1487010809.266777, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1513171170, 'login': 'ger*******', 'type': 'DebridItaliaCom', 'options': {'limitdl': '0'}}}
10	13.02.2017 19:33:53	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Grabbing link info...
11	13.02.2017 19:33:53	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': 'xonyfyx1', 'url': u'http://www.uploaded.net/file/xonyfyx1', 'pattern': {}, 'size': 0}
12	13.02.2017 19:33:53	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Previous link info: {}
13	13.02.2017 19:33:53	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link name: xonyfyx1
14	13.02.2017 19:33:53	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link size: N/D
15	13.02.2017 19:33:53	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link status: starte
16	13.02.2017 19:33:53	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/xonyfyx1
17	13.02.2017 19:33:53	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | LOAD URL http://www.uploaded.net/file/xonyfyx1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
18	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Checking for link errors...
19	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | No errors found
20	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Grabbing link info...
21	13.02.2017 19:33:54	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': 'xonyfyx1', 'url': u'http://www.uploaded.net/file/xonyfyx1', 'pattern': {}, 'size': 0}
22	13.02.2017 19:33:54	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'xonyfyx1', 'url': u'http://www.uploaded.net/file/xonyfyx1', 'pattern': {}, 'size': 0}
23	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link name: xonyfyx1
24	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link size: N/D
25	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link status: starte
26	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Processing as premium download...
27	13.02.2017 19:33:54	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'u': 'ger*******', 'link': u'http://www.uploaded.net/file/xonyfyx1', 'generate': '', 'p': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28	13.02.2017 19:33:54	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Config option `fallback` not found, use default `True`
29	13.02.2017 19:33:54	WARNING	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Premium download failed | offline
30	13.02.2017 19:33:54	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
31	13.02.2017 19:33:54	INFO	Download restarted: xonyfyx1 | Fallback to free processing
32	13.02.2017 19:33:54	INFO	Download starts: xonyfyx1
33	13.02.2017 19:33:54	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
34	13.02.2017 19:33:54	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Plugin version: 0.23
35	13.02.2017 19:33:54	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Plugin status: testing
36	13.02.2017 19:33:54	WARNING	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Plugin may be unstable
37	13.02.2017 19:33:54	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
38	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Grabbing link info...
39	13.02.2017 19:33:54	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': 'xonyfyx1', 'url': u'http://www.uploaded.net/file/xonyfyx1', 'pattern': {}, 'size': 0}
40	13.02.2017 19:33:54	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'xonyfyx1', 'url': u'http://www.uploaded.net/file/xonyfyx1', 'pattern': {}, 'size': 0}
41	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link name: xonyfyx1
42	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link size: N/D
43	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Link status: starte
44	13.02.2017 19:33:54	INFO	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/xonyfyx1
45	13.02.2017 19:33:54	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Config option `fallback` not found, use default `True`
46	13.02.2017 19:33:54	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
47	13.02.2017 19:33:54	DEBUG	HOSTER DebridItaliaCom[1212]: DebridItaliaCom | Config option `revert_failed` not found, use default `True`
48	13.02.2017 19:33:54	WARNING	Download failed: xonyfyx1 | Required account not found
49	13.02.2017 19:33:54	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
50	13.02.2017 19:33:54	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: xonyfyx1 (pid:11)
51	13.02.2017 19:33:54	INFO	ADDON UnSkipOnFail: No duplicates found
52	13.02.2017 19:33:55	INFO	Download starts: cmks6fyg
53	13.02.2017 19:33:56	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
54	13.02.2017 19:33:56	DEBUG	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | Plugin version: 0.23
55	13.02.2017 19:33:56	DEBUG	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | Plugin status: testing
56	13.02.2017 19:33:56	WARNING	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | Plugin may be unstable
57	13.02.2017 19:33:56	DEBUG	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
58	13.02.2017 19:33:56	INFO	ACCOUNT DebridItaliaCom: Grabbing account info for user `ger*******`...
59	13.02.2017 19:33:56	DEBUG	ACCOUNT DebridItaliaCom: LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'p': '**********', 'u': 'ger*******', 'check': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
60	13.02.2017 19:33:56	DEBUG	ACCOUNT DebridItaliaCom: Account info for user `ger*******`: {'login': {'timestamp': 1487010809.266777, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1513171170, 'login': 'ger*******', 'type': 'DebridItaliaCom', 'options': {'limitdl': '0'}}}
61	13.02.2017 19:33:56	INFO	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | Grabbing link info...
62	13.02.2017 19:33:56	DEBUG	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': 'cmks6fyg', 'url': u'http://www.uploaded.net/file/cmks6fyg', 'pattern': {}, 'size': 0}
63	13.02.2017 19:33:56	DEBUG	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | Previous link info: {}
64	13.02.2017 19:33:56	INFO	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | Link name: cmks6fyg
65	13.02.2017 19:33:56	INFO	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | Link size: N/D
66	13.02.2017 19:33:56	INFO	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | Link status: starte
67	13.02.2017 19:33:56	INFO	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/cmks6fyg
68	13.02.2017 19:33:56	DEBUG	HOSTER DebridItaliaCom[1213]: DebridItaliaCom | LOAD URL http://www.uploaded.net/file/cmks6fyg | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False

**Comment by geronimoronin** [comment]
I have  tried  now again directly from the page to load that has worked.
So with account everything is OK

**Comment by GammaC0de** [comment]
Account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by geronimoronin** [comment]
I send account pass  if not receive  look in the spam folder. 
Thank you.

**Comment by GammaC0de** [comment]
It seems that DebridItaliaCom has issues with uplloaded.net at the moment, I tried those links with JDownloader and they failed also.

Other hoters worked fine...

**Comment by geronimoronin** [comment]
Thank you for your work,  i will contact the support

**Comment by GammaC0de** [comment]
👍

**Comment by GammaC0de** [comment]
@geronimoronin Did you solved this with the support?

**Comment by geronimoronin** [comment]
He I have sent a email to support  but no answer.
