### ISSUE TITLE
PremiumizeMe does not work properly: Account login problems

### ISSUE THREAD

**Issue by exislow** [pyload/pyload#2725]
After you have fixed #2724 the following error appears:

```
895	15.02.2017 19:40:36	INFO	ACCOUNT PremiumizeMe: Login user `547*******`...
896	15.02.2017 19:40:36	ERROR	ACCOUNT PremiumizeMe: Could not login user `547*******` | (35, 'error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure')
897	15.02.2017 19:40:37	INFO	ACCOUNT PremiumizeMe: Loading hoster list for user `547*******`...
898	15.02.2017 19:40:37	WARNING	ACCOUNT PremiumizeMe: Error loading hoster list for user `547*******` | (35, 'error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure')
899	15.02.2017 19:40:37	ERROR	ACCOUNT PremiumizeMe: Failed to load hoster list for user `547*******`
````

Could you take a look at it, @GammaC0de ?

**Comment by GammaC0de** [comment]
@exislow What OS are you using?

**Comment by exislow** [comment]
pyLoad on a FreeNAS 9.10 jail. It is FreeBSD 9.10. 

Von meinem 3310 gesendet

**Comment by UserX404** [comment]
Hello
Reactivated my PremiumizeMe account after a long time and added as new account which says the login is ok. After restarting pyload it seems not to work properly. May you give me a hint to get it running?!

`
787 | 12.11.2019 06:08:12 | INFO | starte pyLoad 0.4.9
-- | -- | -- | --
788 | 12.11.2019 06:08:12 | INFO | Benutze Home-Verzeichnis: /share/CACHEDEV1_DATA/.qpkg/Entware/var/pyload
789 | 12.11.2019 06:08:12 | DEBUG | Remote activated: True
790 | 12.11.2019 06:08:13 | DEBUG | created index of plugins
791 | 12.11.2019 06:08:13 | INFO | Aktivierte Plugins: Captcha9Kw, ClickNLoad, EventMapper,  ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager,  UserAgentSwitcher
792 | 12.11.2019 06:08:13 | INFO | Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus,  BypassCaptcha, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished,  DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC,  ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker,  MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev,  TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
793 | 12.11.2019 06:08:13 | INFO | Downloadzeit: True
794 | 12.11.2019 06:08:13 | INFO | Nutze SSL Thrift Backend
795 | 12.11.2019 06:08:13 | INFO | Starte ThriftBackend: 0.0.0.0:57272
796 | 12.11.2019 06:08:14 | INFO | Starting threaded SSL webserver: 0.0.0.0:58001
797 | 12.11.2019 06:08:14 | INFO | Free space: 14.73 TiB
798 | 12.11.2019 06:08:14 | INFO | Activating Accounts...
799 | 12.11.2019 06:08:14 | INFO | ACCOUNT PremiumizeMe: Adding user `667*******`...
800 | 12.11.2019 06:08:14 | DEBUG | ACCOUNT PremiumizeMe: Reached login timeout for user `667*******`
801 | 12.11.2019 06:08:14 | INFO | ACCOUNT PremiumizeMe: Login user `667*******`...
802 | 12.11.2019 06:08:14 | DEBUG | ACCOUNT PremiumizeMe: LOAD URL  https://www.premiumize.me/api/account/info \| redirect=True \|  cookies=True \| get={'apikey': '**********'} \| req=None \| decode=True \|  multipart=False \| post={} \| ref=True \| just_header=False
803 | 12.11.2019 06:08:14 | INFO | ACCOUNT PremiumizeMe: Grabbing account info for user `667*******`...
804 | 12.11.2019 06:08:14 | DEBUG | ACCOUNT PremiumizeMe: LOAD URL  https://www.premiumize.me/api/account/info \| redirect=True \|  cookies=True \| get={'apikey': '**********'} \| req=None \| decode=True \|  multipart=False \| post={} \| ref=True \| just_header=False
805 | 12.11.2019 06:08:14 | DEBUG | ACCOUNT PremiumizeMe: Account info for user `667*******`: {'login':  {'timestamp': 1573535294.4056399, 'password': '**********', 'valid':  True}, 'data': {'premium': True, 'plugin': ,  'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1574663401,  'login': '667*******', 'type': 'PremiumizeMe', 'options': {'limitDL':  ['0']}}}
806 | 12.11.2019 06:08:14 | INFO | Activating Plugins...
807 | 12.11.2019 06:08:14 | DEBUG | ADDON UpdateManager: LOAD URL  https://raw.githubusercontent.com/pyload/updates/master/plugins.txt \|  redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \|  decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
808 | 12.11.2019 06:08:14 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_start`
809 | 12.11.2019 06:08:14 | DEBUG | ADDON ExtractArchive: Found HjSplit 0.01 \| Found UnRar 5.80 \| Found UnZip 2.7.16 \| Found UnTar 2.7.16
810 | 12.11.2019 06:08:14 | INFO | pyLoad is up and running
811 | 12.11.2019 06:08:14 | INFO | ADDON UpdateManager: pyLoad is up to date!
812 | 12.11.2019 06:08:14 | DEBUG | ADDON UpdateManager: LOAD URL  https://raw.githubusercontent.com/pyload/updates/master/plugins.txt \|  redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \|  decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
813 | 12.11.2019 06:08:14 | DEBUG | ADDON UpdateManager: Requested deletion of plugins: [(u'accounts',  u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts',  u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts',  u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts',  u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts',  u'FreeWayMe'), (u'accounts', u'HotfileCom'), (u'accounts',  u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts',  u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts',  u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts',  u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts',  u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts',  u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts',  u'ShareRapidCom'), (u'accounts', u'ShareonlineBiz'), (u'accounts',  u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts',  u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts',  u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts',  u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha',  u'ShareonlineBiz'), (u'captcha', u'captcha'), (u'container', u'DLC_25'),  (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container',  u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter',  u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter',  u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter',  u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter',  u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter',  u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter',  u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'),  (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'),  (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks',  u'Captcha9kw'), (u'hooks', u'CaptchaBrotherhood'), (u'hooks',  u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks',  u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks',  u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks',  u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'),  (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks',  u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks',  u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks',  u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks',  u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks',  u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks',  u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks',  u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks',  u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks',  u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks',  u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks',  u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks',  u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'),  (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks',  u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks',  u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'),  (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks',  u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks',  u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'),  (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'),  (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'),  (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks',  u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks',  u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks',  u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks',  u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster',  u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster',  u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'Libgen'),  (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster',  u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster',  u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster',  u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster',  u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster',  u'RealdebridComTorrent'), (u'hoster', u'ReloadCc'), (u'hoster',  u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster',  u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster',  u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster',  u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal',  u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'),  (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal',  u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal',  u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal',  u'XFSPHoster'), (u'internal', u'utils')]
814 | 12.11.2019 06:08:14 | INFO | ADDON UpdateManager: All plugins are up to date!
815 | 12.11.2019 06:08:16 | DEBUG | ACCOUNT PremiumizeMe: LOAD URL  https://www.premiumize.me/api/services/list \| redirect=True \|  cookies=True \| get={'apikey': '**********'} \| req=None \| decode=True \|  multipart=False \| post={} \| ref=True \| just_header=False
816 | 12.11.2019 06:08:16 | WARNING | ACCOUNT PremiumizeMe: Error loading hoster list for user `667*******` \| list indices must be integers, not unicode
817 | 12.11.2019 06:08:16 | DEBUG | ACCOUNT PremiumizeMe: Hoster list for user `667*******`: []
818 | 12.11.2019 06:08:16 | ERROR | ACCOUNT PremiumizeMe: Failed to load hoster list for user `667*******`, retry in 5 minutes
819 | 12.11.2019 06:08:20 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
`

**Comment by GammaC0de** [comment]
Fixed

**Comment by UserX404** [comment]
Wow
That was fast.
Thanks a lot!
