### ISSUE TITLE
PremiumizeMe strange behaviour: some files are downloaded some others are not (uploaded.to)

### ISSUE THREAD

**Issue by exislow** [pyload/pyload#2728]
I try to download several files from uploaded.to using PremiumizeMe plugin. Every single file is online and can be downloaded, e.g., with JDownloader. But pyLoad shows the following error on some files -- not on all.

```
failed Bad server response: 403 Forbidden 168.00 B UploadedTo
```

Debug output below.

```
17.02.2017 15:43:18 INFO      Download starts: http://uploaded.net/file/X1
17.02.2017 15:43:18 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
17.02.2017 15:43:18 DEBUG     HOSTER PremiumizeMe[128]: PremiumizeMe | Plugin version: 0.27
17.02.2017 15:43:18 DEBUG     HOSTER PremiumizeMe[128]: PremiumizeMe | Plugin status: testing
17.02.2017 15:43:18 WARNING   HOSTER PremiumizeMe[128]: PremiumizeMe | Plugin may be unstable
17.02.2017 15:43:18 DEBUG     HOSTER PremiumizeMe[128]: PremiumizeMe | Config option `use_premium` not found, use default `True`
17.02.2017 15:43:18 INFO      ACCOUNT PremiumizeMe: Grabbing account info for user `547*******`...
17.02.2017 15:43:18 DEBUG     ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php | redirect=True | cookies=True | get={'params[pass]': '**********', 'params[login]': '547*******', 'method': 'accountstatus'} | req=None | decode=True |multipart=False | post={} | ref=True | just_header=False
17.02.2017 15:43:18 DEBUG     ACCOUNT PremiumizeMe: Account info for user `547*******`: {'login': {'timestamp': 1487342580.642751, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account PremiumizeMe>, 'trafficleft': 860970317, 'maxtraffic': None, 'validuntil': 1488022645.0, 'login': '547*******', 'type': 'PremiumizeMe', 'options': {'limitdl': '0'}}}
17.02.2017 15:43:18 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Grabbing link info...
17.02.2017 15:43:18 DEBUG     HOSTER PremiumizeMe[128]: PremiumizeMe | Link info: {'status': 7, 'hash': {}, 'name': 'X1', 'url': u'http://uploaded.net/file/X1', 'pattern': {}, 'size': 0}
17.02.2017 15:43:18 DEBUG     HOSTER PremiumizeMe[128]: PremiumizeMe | Previous link info: {}
17.02.2017 15:43:18 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Link name: X1
17.02.2017 15:43:18 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Link size: 150.00 MiB (157286405 bytes)
17.02.2017 15:43:18 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Link status: starting
17.02.2017 15:43:18 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Processing url: http://uploaded.net/file/X1
17.02.2017 15:43:18 DEBUG     HOSTER PremiumizeMe[128]: PremiumizeMe | LOAD URL http://uploaded.net/file/X1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
17.02.2017 15:43:19 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Checking for link errors...
17.02.2017 15:43:19 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | No errors found
17.02.2017 15:43:19 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Grabbing link info...
17.02.2017 15:43:19 DEBUG     HOSTER PremiumizeMe[128]: PremiumizeMe | Link info: {'status': 7, 'hash': {}, 'name': 'X1', 'url': u'http://uploaded.net/file/X1', 'pattern': {}, 'size': 0}
17.02.2017 15:43:19 DEBUG     HOSTER PremiumizeMe[128]: PremiumizeMe | Previous link info: {'status': 7, 'hash': {}, 'name': 'X1', 'url': u'http://uploaded.net/file/X1', 'pattern': {}, 'size': 0}
17.02.2017 15:43:19 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Link name: X1
17.02.2017 15:43:19 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Link size: 150.00 MiB (157286405 bytes)
17.02.2017 15:43:19 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Link status: starting
17.02.2017 15:43:19 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Processing as premium download...
17.02.2017 15:43:19 DEBUG     HOSTER PremiumizeMe[128]: PremiumizeMe | LOAD URL http://api.premiumize.me/pm-api/v1.php | redirect=True | cookies=True | get={'params[link]': u'http://uploaded.net/file/X1', 'params[pass]': '**********', 'params[login]': '547*******', 'method': 'directdownloadlink'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
17.02.2017 15:43:19 INFO      HOSTER PremiumizeMe[128]: PremiumizeMe | Downloading file...
17.02.2017 15:43:19 DEBUG     HOSTER PremiumizeMe[128]: PremiumizeMe | DOWNLOAD URL https://c-2513095437.energycdn.com/cdl?key=339890fc40c9b0e7ed9417ca4772ed0a&log=eyJzaXRlIjoicHJlbWl1bWl6ZSIsInVzZXJfaWQiOiI1NDczMTg2NjUiLCJzZXJ2aWNlIjoidXBsb2FkZWQudG8ifQ&sig=GME1u%2FqnznjCG6WwQ9uWjNBgaSs%3D&f=Y.part01.rar | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
17.02.2017 15:43:19 DEBUG     Content-Disposition: Y.part01.rar
17.02.2017 15:43:20 INFO      Download starts: X2
17.02.2017 15:43:20 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
17.02.2017 15:43:20 DEBUG     HOSTER PremiumizeMe[129]: PremiumizeMe | Plugin version: 0.27
17.02.2017 15:43:20 DEBUG     HOSTER PremiumizeMe[129]: PremiumizeMe | Plugin status: testing
17.02.2017 15:43:20 WARNING   HOSTER PremiumizeMe[129]: PremiumizeMe | Plugin may be unstable
17.02.2017 15:43:20 DEBUG     HOSTER PremiumizeMe[129]: PremiumizeMe | Config option `use_premium` not found, use default `True`
17.02.2017 15:43:20 INFO      ACCOUNT PremiumizeMe: Grabbing account info for user `547*******`...
17.02.2017 15:43:20 DEBUG     ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php | redirect=True | cookies=True | get={'params[pass]': '**********', 'params[login]': '547*******', 'method': 'accountstatus'} | req=None | decode=True |multipart=False | post={} | ref=True | just_header=False
17.02.2017 15:43:20 DEBUG     ACCOUNT PremiumizeMe: Account info for user `547*******`: {'login': {'timestamp': 1487342580.642751, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account PremiumizeMe>, 'trafficleft': 860970317, 'maxtraffic': None, 'validuntil': 1488022645.0, 'login': '547*******', 'type': 'PremiumizeMe', 'options': {'limitdl': '0'}}}
17.02.2017 15:43:20 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Grabbing link info...
17.02.2017 15:43:21 DEBUG     HOSTER PremiumizeMe[129]: PremiumizeMe | Link info: {'status': 7, 'hash': {}, 'name': 'X2', 'url': u'http://ul.to/X2', 'pattern': {}, 'size': 0}
17.02.2017 15:43:21 DEBUG     HOSTER PremiumizeMe[129]: PremiumizeMe | Previous link info: {}
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Link name: X2
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Link size: N/D
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Link status: starting
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Processing url: http://ul.to/X2
17.02.2017 15:43:21 DEBUG     HOSTER PremiumizeMe[129]: PremiumizeMe | LOAD URL http://ul.to/X2 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Checking for link errors...
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | No errors found
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Grabbing link info...
17.02.2017 15:43:21 DEBUG     HOSTER PremiumizeMe[129]: PremiumizeMe | Link info: {'status': 7, 'hash': {}, 'name': 'X2', 'url': u'http://ul.to/X2', 'pattern': {}, 'size': 0}
17.02.2017 15:43:21 DEBUG     HOSTER PremiumizeMe[129]: PremiumizeMe | Previous link info: {'status': 7, 'hash': {}, 'name': 'X2', 'url': u'http://ul.to/X2', 'pattern': {}, 'size': 0}
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Link name: X2
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Link size: N/D
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Link status: starting
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Processing as premium download...
17.02.2017 15:43:21 DEBUG     HOSTER PremiumizeMe[129]: PremiumizeMe | LOAD URL http://api.premiumize.me/pm-api/v1.php | redirect=True | cookies=True | get={'params[link]': u'http://ul.to/X2', 'params[pass]': '**********', 'params[login]': '547*******', 'method': 'directdownloadlink'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
17.02.2017 15:43:21 INFO      HOSTER PremiumizeMe[129]: PremiumizeMe | Downloading file...
17.02.2017 15:43:21 DEBUG     HOSTER PremiumizeMe[129]: PremiumizeMe | DOWNLOAD URL https://c-3242592313.energycdn.com/cdl?key=ac8d8e4f97d6c9e9e11409b3cf140d14&log=eyJzaXRlIjoicHJlbWl1bWl6ZSIsInVzZXJfaWQiOiI1NDczMTg2NjUiLCJzZXJ2aWNlIjoidXBsb2FkZWQudG8ifQ&sig=yEgvXNpJETWATNa%2BYOVub0xfl88%3D&f=Y.part02.rar | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
17.02.2017 15:43:22 DEBUG     Chunk 1 failed: Bad server response: 403 Forbidden
17.02.2017 15:43:22 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
17.02.2017 15:43:22 WARNING   Download failed: Y.part02.rar | Bad server response: 403 Forbidden
17.02.2017 15:43:22 INFO      Debug Report written to debug_UploadedTo_17-02-2017_15-43-22.zip
17.02.2017 15:43:22 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
17.02.2017 15:43:22 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: Y.part02.rar (pid:7)
17.02.2017 15:43:22 INFO      ADDON UnSkipOnFail: No duplicates found
17.02.2017 15:43:22 INFO      Download starts: sbr1nito
17.02.2017 15:43:22 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
```

The debug archives can be found here: 
https://www.sendspace.com/filegroup/Ye2b6x2t1kgx7pHmSgG7Bw

**Comment by GammaC0de** [comment]
Does this happen only with uploaded.to?

**Comment by exislow** [comment]
share-online.biz also does not work.

**Comment by Mask66** [comment]
Also happens for me, manually downloading from the premiumize/uploaded url works fine.

`18.02.2017 16:31:15	INFO	Added package test containing 1 links
231	18.02.2017 16:31:15	INFO	Download starts: http://ul.to/ts4y2rsy/dertatortreinigerweb_hdsl8_s06e03.part7.rar
232	18.02.2017 16:31:15	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
233	18.02.2017 16:31:15	DEBUG	HOSTER PremiumizeMe[1164]: PremiumizeMe | Plugin version: 0.27
234	18.02.2017 16:31:15	DEBUG	HOSTER PremiumizeMe[1164]: PremiumizeMe | Plugin status: testing
235	18.02.2017 16:31:15	WARNING	HOSTER PremiumizeMe[1164]: PremiumizeMe | Plugin may be unstable
236	18.02.2017 16:31:15	DEBUG	HOSTER PremiumizeMe[1164]: PremiumizeMe | Config option `use_premium` not found, use default `True`
237	18.02.2017 16:31:15	INFO	ACCOUNT PremiumizeMe: Grabbing account info for user `796*******`...
238	18.02.2017 16:31:15	DEBUG	ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php | redirect=True | cookies=True | get={'params[pass]': '**********', 'params[login]': '796*******', 'method': 'accountstatus'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
239	18.02.2017 16:31:15	DEBUG	ACCOUNT PremiumizeMe: Account info for user `796*******`: {'login': {'timestamp': 1487431568.709064, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 863028451, 'maxtraffic': None, 'validuntil': 1493029906.0, 'login': '796*******', 'type': 'PremiumizeMe', 'options': {'limitdl': '0'}}}
240	18.02.2017 16:31:15	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Grabbing link info...
241	18.02.2017 16:31:16	DEBUG	HOSTER PremiumizeMe[1164]: PremiumizeMe | Link info: {'status': 7, 'hash': {}, 'name': 'dertatortreinigerweb_hdsl8_s06e03.part7.rar', 'url': u'http://ul.to/ts4y2rsy/dertatortreinigerweb_hdsl8_s06e03.part7.rar', 'pattern': {}, 'size': 0}
242	18.02.2017 16:31:16	DEBUG	HOSTER PremiumizeMe[1164]: PremiumizeMe | Previous link info: {}
243	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Link name: dertatortreinigerweb_hdsl8_s06e03.part7.rar
244	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Link size: N/D
245	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Link status: starting
246	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Processing url: http://ul.to/ts4y2rsy/dertatortreinigerweb_hdsl8_s06e03.part7.rar
247	18.02.2017 16:31:16	DEBUG	HOSTER PremiumizeMe[1164]: PremiumizeMe | LOAD URL http://ul.to/ts4y2rsy/dertatortreinigerweb_hdsl8_s06e03.part7.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
248	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Checking for link errors...
249	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | No errors found
250	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Grabbing link info...
251	18.02.2017 16:31:16	DEBUG	HOSTER PremiumizeMe[1164]: PremiumizeMe | Link info: {'status': 7, 'hash': {}, 'name': 'dertatortreinigerweb_hdsl8_s06e03.part7.rar', 'url': u'http://ul.to/ts4y2rsy/dertatortreinigerweb_hdsl8_s06e03.part7.rar', 'pattern': {}, 'size': 0}
252	18.02.2017 16:31:16	DEBUG	HOSTER PremiumizeMe[1164]: PremiumizeMe | Previous link info: {'status': 7, 'hash': {}, 'name': 'dertatortreinigerweb_hdsl8_s06e03.part7.rar', 'url': u'http://ul.to/ts4y2rsy/dertatortreinigerweb_hdsl8_s06e03.part7.rar', 'pattern': {}, 'size': 0}
253	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Link name: dertatortreinigerweb_hdsl8_s06e03.part7.rar
254	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Link size: N/D
255	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Link status: starting
256	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Processing as premium download...
257	18.02.2017 16:31:16	DEBUG	HOSTER PremiumizeMe[1164]: PremiumizeMe | LOAD URL http://api.premiumize.me/pm-api/v1.php | redirect=True | cookies=True | get={'params[link]': u'http://ul.to/ts4y2rsy/dertatortreinigerweb_hdsl8_s06e03.part7.rar', 'params[pass]': '**********', 'params[login]': '796*******', 'method': 'directdownloadlink'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
258	18.02.2017 16:31:16	INFO	HOSTER PremiumizeMe[1164]: PremiumizeMe | Downloading file...
259	18.02.2017 16:31:16	DEBUG	HOSTER PremiumizeMe[1164]: PremiumizeMe | DOWNLOAD URL https://c-2513095449.energycdn.com/cdl?key=897ed6b75f2eadb649db334750cca840&log=eyJzaXRlIjoicHJlbWl1bWl6ZSIsInVzZXJfaWQiOiI3OTYwMjQxMjMiLCJzZXJ2aWNlIjoidXBsb2FkZWQudG8ifQ&sig=jNc9r1JJTNt25tpcfcnkO5%2BhxS8%3D&f=dertatortreinigerweb_hdsl8_s06e03.part7.rar | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
260	18.02.2017 16:31:17	DEBUG	Chunk 1 failed: Bad server response: 403 Forbidden
261	18.02.2017 16:31:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
262	18.02.2017 16:31:17	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
263	18.02.2017 16:31:17	WARNING	Download failed: dertatortreinigerweb_hdsl8_s06e03.part7.rar | Bad server response: 403 Forbidden
264	18.02.2017 16:31:17	INFO	Debug Report written to debug_UploadedTo_18-02-2017_16-31-17.zip
265	18.02.2017 16:31:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
266	18.02.2017 16:31:17	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: dertatortreinigerweb_hdsl8_s06e03.part7.rar (pid:23)
267	18.02.2017 16:31:17	INFO	ADDON UnSkipOnFail: No duplicates found
268	18.02.2017 16:31:17	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
269	18.02.2017 16:31:17	DEBUG	All downloads processed
270	18.02.2017 16:31:23	DEBUG	ADDON ExternalScripts: No script found under folder `package_deleted``

**Comment by GammaC0de** [comment]
Does this happens every time with those URLs?

**Comment by GammaC0de** [comment]
@Mask66 I have edited your post because the log you have posted revealed your password.
You should change as it ASAP.

**Comment by Mask66** [comment]
Thanks for the diligence, changed the pw.  I could reproduce it with this file twice.

**Comment by GammaC0de** [comment]
Yes, I found the problem, working on a solution.
