### ISSUE TITLE
QUESTION - Fresh install with 0.4.9.deb - Need to use old fixed UpdateManager?

### ISSUE THREAD

**Issue by Ryan747800B** [pyload/pyload#2730]
If I do a fresh install from `0.4.9.deb` version, I have to use the old workaround [#2000](https://github.com/pyload/pyload/issues/2000) or it automatically updates to 1.0.0 version (or the newest commits) available? Or I can in some way do a manual install of the 1.0.0 branch?
I'm not updated on the latest (months!) updates/commits.

**Comment by GammaC0de** [comment]
>I'm not updated on the latest (months!) updates/commits.

Why?

>If I do a fresh install from 0.4.9.deb version, I have to use the old workaround #2000

Yes.

>Or I can in some way do a manual install of the 1.0.0 branch?

1.0.0 is not usable yet, don't bother.

**Comment by Ryan747800B** [comment]
`Why?`
I disabled month ago UpdateManager because of Real-Debrid; by a more or less week RDB plugin doesn't work anymore; seeing that there are lots of updates, I decided to start over with a new install but it needs time because of there are a lot of important files to save and the installScript to check.
Feedback within the next two days.

**Comment by GammaC0de** [comment]
OK, closing.

**Comment by Ryan747800B** [comment]
Quick test fresh installation done: it seems all OK. Testing Real-Debrid for two days to check if premium account and fallback correctly works. Only one issue with the new `ExtractArchive` [#2735](https://github.com/pyload/pyload/issues/2735) and `Send2LibTrash` (Send2Trash lib not found) even if I modified the `ExtractArchive.py` in `/opt/etc/pyload/userplugins/hooks` [#2630](https://github.com/pyload/pyload/issues/2630#issuecomment-276913472)
