### ISSUE TITLE
debriditalia.com Premium download failed | offline 

### ISSUE THREAD

**Issue by geronimoronin** [pyload/pyload#2736]
I have again problem with debriditalia I have tested with jdownload there it runs normally.
I will send you access data to nitzo2001

682	21.02.2017 17:54:17	INFO	Download starts: bonuzht1
683	21.02.2017 17:54:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
684	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1302]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
685	21.02.2017 17:54:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
686	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Plugin version: 0.24
687	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1302]: DebridItaliaCom | Grabbing link info...
688	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Plugin status: testing
689	21.02.2017 17:54:17	INFO	Download restarted: 0d6hllt2 | Fallback to free processing
690	21.02.2017 17:54:17	WARNING	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Plugin may be unstable
691	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
692	21.02.2017 17:54:17	INFO	ACCOUNT DebridItaliaCom: Grabbing account info for user `ger*******`...
693	21.02.2017 17:54:17	DEBUG	ACCOUNT DebridItaliaCom: LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'p': '**********', 'u': 'ger*******', 'check': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
694	21.02.2017 17:54:17	INFO	Download starts: 0d6hllt2
695	21.02.2017 17:54:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
696	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Plugin version: 0.24
697	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Plugin status: testing
698	21.02.2017 17:54:17	WARNING	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Plugin may be unstable
699	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
700	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Grabbing link info...
701	21.02.2017 17:54:17	DEBUG	ACCOUNT DebridItaliaCom: Account info for user `ger*******`: {'login': {'timestamp': 1487695369.909656, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1513171170, 'login': 'ger*******', 'type': 'DebridItaliaCom', 'options': {'limitdl': '0'}}}
702	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Grabbing link info...
703	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1302]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': 'qenp6q8p', 'url': u'http://www.uploaded.net/file/qenp6q8p', 'pattern': {}, 'size': 0}
704	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1302]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'qenp6q8p', 'url': u'http://www.uploaded.net/file/qenp6q8p', 'pattern': {}, 'size': 0}
705	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1302]: DebridItaliaCom | Link name: qenp6q8p
706	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1302]: DebridItaliaCom | Link size: N/D
707	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1302]: DebridItaliaCom | Link status: starte
708	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1302]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/qenp6q8p
709	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1302]: DebridItaliaCom | Config option `fallback` not found, use default `True`
710	21.02.2017 17:54:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
711	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1302]: DebridItaliaCom | Config option `revert_failed` not found, use default `True`
712	21.02.2017 17:54:17	WARNING	Download failed: qenp6q8p | Required account not found
713	21.02.2017 17:54:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
714	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': '0d6hllt2', 'url': u'http://www.uploaded.net/file/0d6hllt2', 'pattern': {}, 'size': 0}
715	21.02.2017 17:54:17	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: qenp6q8p (pid:11)
716	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': '0d6hllt2', 'url': u'http://www.uploaded.net/file/0d6hllt2', 'pattern': {}, 'size': 0}
717	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Link name: 0d6hllt2
718	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Link size: N/D
719	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Link status: starte
720	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/0d6hllt2
721	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Config option `fallback` not found, use default `True`
722	21.02.2017 17:54:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
723	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': 'bonuzht1', 'url': u'http://www.uploaded.net/file/bonuzht1', 'pattern': {}, 'size': 0}
724	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Previous link info: {}
725	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link name: bonuzht1
726	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link size: N/D
727	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link status: starte
728	21.02.2017 17:54:17	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/bonuzht1
729	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | LOAD URL http://www.uploaded.net/file/bonuzht1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
730	21.02.2017 17:54:17	DEBUG	HOSTER DebridItaliaCom[1306]: DebridItaliaCom | Config option `revert_failed` not found, use default `True`
731	21.02.2017 17:54:17	WARNING	Download failed: 0d6hllt2 | Required account not found
732	21.02.2017 17:54:17	INFO	ADDON UnSkipOnFail: No duplicates found
733	21.02.2017 17:54:17	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
734	21.02.2017 17:54:17	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 0d6hllt2 (pid:11)
735	21.02.2017 17:54:17	INFO	ADDON UnSkipOnFail: No duplicates found
736	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Checking for link errors...
737	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | No errors found
738	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Grabbing link info...
739	21.02.2017 17:54:18	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': 'bonuzht1', 'url': u'http://www.uploaded.net/file/bonuzht1', 'pattern': {}, 'size': 0}
740	21.02.2017 17:54:18	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'bonuzht1', 'url': u'http://www.uploaded.net/file/bonuzht1', 'pattern': {}, 'size': 0}
741	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link name: bonuzht1
742	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link size: N/D
743	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link status: starte
744	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Processing as premium download...
745	21.02.2017 17:54:18	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'u': 'ger*******', 'link': u'http://www.uploaded.net/file/bonuzht1', 'generate': '', 'p': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
746	21.02.2017 17:54:18	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Config option `fallback` not found, use default `True`
747	21.02.2017 17:54:18	WARNING	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Premium download failed | offline
748	21.02.2017 17:54:18	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
749	21.02.2017 17:54:18	INFO	Download restarted: bonuzht1 | Fallback to free processing
750	21.02.2017 17:54:18	INFO	Download starts: bonuzht1
751	21.02.2017 17:54:18	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
752	21.02.2017 17:54:18	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Plugin version: 0.24
753	21.02.2017 17:54:18	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Plugin status: testing
754	21.02.2017 17:54:18	WARNING	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Plugin may be unstable
755	21.02.2017 17:54:18	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
756	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Grabbing link info...
757	21.02.2017 17:54:18	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': 'bonuzht1', 'url': u'http://www.uploaded.net/file/bonuzht1', 'pattern': {}, 'size': 0}
758	21.02.2017 17:54:18	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'bonuzht1', 'url': u'http://www.uploaded.net/file/bonuzht1', 'pattern': {}, 'size': 0}
759	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link name: bonuzht1
760	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link size: N/D
761	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Link status: starte
762	21.02.2017 17:54:18	INFO	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/bonuzht1
763	21.02.2017 17:54:18	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Config option `fallback` not found, use default `True`
764	21.02.2017 17:54:18	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
765	21.02.2017 17:54:18	DEBUG	HOSTER DebridItaliaCom[1310]: DebridItaliaCom | Config option `revert_failed` not found, use default `True`
766	21.02.2017 17:54:18	WARNING	Download failed: bonuzht1 | Required account not found
767	21.02.2017 17:54:18	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
768	21.02.2017 17:54:18	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: bonuzht1 (pid:11)
769	21.02.2017 17:54:18	INFO	ADDON UnSkipOnFail: No duplicates found
770	21.02.2017 17:54:19	INFO	Download starts: pkali7z1
771	21.02.2017 17:54:19	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
772	21.02.2017 17:54:19	DEBUG	HOSTER DebridItaliaCom[1311]: DebridItaliaCom | Plugin version: 0.24
773	21.02.2017 17:54:19	DEBUG	HOSTER DebridItaliaCom[1311]: DebridItaliaCom | Plugin status: testing
774	21.02.2017 17:54:19	WARNING	HOSTER DebridItaliaCom[1311]: DebridItaliaCom | Plugin may be unstable
775	21.02.2017 17:54:19	DEBUG	HOSTER DebridItaliaCom[1311]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
776	21.02.2017 17:54:19	INFO	ACCOUNT DebridItaliaCom: Grabbing account info for user `ger*******`...
777	21.02.2017 17:54:19	DEBUG	ACCOUNT DebridItaliaCom: LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'p': '**********', 'u': 'ger*******', 'check': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
778	21.02.2017 17:54:19	DEBUG	ACCOUNT DebridItaliaCom: Account info for user `ger*******`: {'login': {'timestamp': 1487695369.909656, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1513171170, 'login': 'ger*******', 'type': 'DebridItaliaCom', 'options': {'limitdl': '0'}}}
779	21.02.2017 17:54:19	INFO	HOSTER DebridItaliaCom[1311]: DebridItaliaCom | Grabbing link info...

**Comment by GammaC0de** [comment]
```
21.02.2017 21:17:39 DEBUG     HOSTER DebridItaliaCom[1930]: DebridItaliaCom | LOAD URL https://debriditalia.com/api.php
| redirect=True | cookies=True | get={'u': 'ger*******', 'link': u'http://www.uploaded.net/file/bonuzht1', 'generate': '
', 'p': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
21.02.2017 21:17:40 DEBUG     HOSTER DebridItaliaCom[1930]: DebridItaliaCom | api_response=ERROR: not_supported
```

Response from DebridItaliaCom: `ERROR: not_supported` please contact DebridItaliaCom's support.
