### ISSUE TITLE
debriditalia.com not work

### ISSUE THREAD

**Issue by geronimoronin** [pyload/pyload#2737]
I do not know what this is but it does not work With pyload Since 12.2 it does not work anymore, I wrote today to support but no answer, With the JDownloader works.
Access data are the same as yesterday I had sent you.

22.02.2017 14:24:21	INFO	ACCOUNT DebridItaliaCom: Grabbing account info for user `ger*******`...
179	22.02.2017 14:24:21	DEBUG	ACCOUNT DebridItaliaCom: LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'p': '**********', 'u': 'ger*******', 'check': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
180	22.02.2017 14:24:21	DEBUG	ACCOUNT DebridItaliaCom: Account info for user `ger*******`: {'login': {'timestamp': 1487769413.3270669, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1513171170, 'login': 'ger*******', 'type': 'DebridItaliaCom', 'options': {'limitdl': ['0']}}}
181	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Grabbing link info...
182	22.02.2017 14:24:21	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': '3pg4jk8v', 'url': u'http://www.uploaded.net/file/3pg4jk8v', 'pattern': {}, 'size': 0}
183	22.02.2017 14:24:21	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Previous link info: {}
184	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link name: 3pg4jk8v
185	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link size: N/D
186	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link status: starte
187	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/3pg4jk8v
188	22.02.2017 14:24:21	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | LOAD URL http://www.uploaded.net/file/3pg4jk8v | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
189	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Checking for link errors...
190	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | No errors found
191	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Grabbing link info...
192	22.02.2017 14:24:21	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': '3pg4jk8v', 'url': u'http://www.uploaded.net/file/3pg4jk8v', 'pattern': {}, 'size': 0}
193	22.02.2017 14:24:21	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': '3pg4jk8v', 'url': u'http://www.uploaded.net/file/3pg4jk8v', 'pattern': {}, 'size': 0}
194	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link name: 3pg4jk8v
195	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link size: N/D
196	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link status: starte
197	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Processing as premium download...
198	22.02.2017 14:24:21	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'u': 'ger*******', 'link': u'http://www.uploaded.net/file/3pg4jk8v', 'generate': '', 'p': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
199	22.02.2017 14:24:21	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Config option `fallback` not found, use default `True`
200	22.02.2017 14:24:21	WARNING	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Premium download failed | offline
201	22.02.2017 14:24:21	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
202	22.02.2017 14:24:21	INFO	Download restarted: 3pg4jk8v | Fallback to free processing
203	22.02.2017 14:24:21	INFO	Download starts: 3pg4jk8v
204	22.02.2017 14:24:21	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
205	22.02.2017 14:24:21	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Plugin version: 0.24
206	22.02.2017 14:24:21	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Plugin status: testing
207	22.02.2017 14:24:21	WARNING	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Plugin may be unstable
208	22.02.2017 14:24:21	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
209	22.02.2017 14:24:21	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Grabbing link info...
210	22.02.2017 14:24:22	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': '3pg4jk8v', 'url': u'http://www.uploaded.net/file/3pg4jk8v', 'pattern': {}, 'size': 0}
211	22.02.2017 14:24:22	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': '3pg4jk8v', 'url': u'http://www.uploaded.net/file/3pg4jk8v', 'pattern': {}, 'size': 0}
212	22.02.2017 14:24:22	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link name: 3pg4jk8v
213	22.02.2017 14:24:22	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link size: N/D
214	22.02.2017 14:24:22	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Link status: starte
215	22.02.2017 14:24:22	INFO	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/3pg4jk8v
216	22.02.2017 14:24:22	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Config option `fallback` not found, use default `True`
217	22.02.2017 14:24:22	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
218	22.02.2017 14:24:22	DEBUG	HOSTER DebridItaliaCom[1252]: DebridItaliaCom | Config option `revert_failed` not found, use default `True`
219	22.02.2017 14:24:22	WARNING	Download failed: 3pg4jk8v | Required account not found
220	22.02.2017 14:24:22	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
221	22.02.2017 14:24:22	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 3pg4jk8v (pid:11)
222	22.02.2017 14:24:22	INFO	ADDON UnSkipOnFail: No duplicates found
223	22.02.2017 14:24:23	INFO	Download starts: ijqeyxyg
224	22.02.2017 14:24:23	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
225	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Plugin version: 0.24
226	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Plugin status: testing
227	22.02.2017 14:24:23	WARNING	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Plugin may be unstable
228	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
229	22.02.2017 14:24:23	INFO	ACCOUNT DebridItaliaCom: Grabbing account info for user `ger*******`...
230	22.02.2017 14:24:23	DEBUG	ACCOUNT DebridItaliaCom: LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'p': '**********', 'u': 'ger*******', 'check': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
231	22.02.2017 14:24:23	DEBUG	ACCOUNT DebridItaliaCom: Account info for user `ger*******`: {'login': {'timestamp': 1487769413.3270669, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1513171170, 'login': 'ger*******', 'type': 'DebridItaliaCom', 'options': {'limitdl': ['0']}}}
232	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Grabbing link info...
233	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': 'ijqeyxyg', 'url': u'http://www.uploaded.net/file/ijqeyxyg', 'pattern': {}, 'size': 0}
234	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Previous link info: {}
235	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link name: ijqeyxyg
236	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link size: N/D
237	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link status: starte
238	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/ijqeyxyg
239	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | LOAD URL http://www.uploaded.net/file/ijqeyxyg | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
240	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Checking for link errors...
241	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | No errors found
242	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Grabbing link info...
243	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': 'ijqeyxyg', 'url': u'http://www.uploaded.net/file/ijqeyxyg', 'pattern': {}, 'size': 0}
244	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'ijqeyxyg', 'url': u'http://www.uploaded.net/file/ijqeyxyg', 'pattern': {}, 'size': 0}
245	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link name: ijqeyxyg
246	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link size: N/D
247	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link status: starte
248	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Processing as premium download...
249	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'u': 'ger*******', 'link': u'http://www.uploaded.net/file/ijqeyxyg', 'generate': '', 'p': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
250	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Config option `fallback` not found, use default `True`
251	22.02.2017 14:24:23	WARNING	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Premium download failed | offline
252	22.02.2017 14:24:23	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
253	22.02.2017 14:24:23	INFO	Download restarted: ijqeyxyg | Fallback to free processing
254	22.02.2017 14:24:23	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
255	22.02.2017 14:24:23	DEBUG	All downloads processed
256	22.02.2017 14:24:23	INFO	Download starts: ijqeyxyg
257	22.02.2017 14:24:23	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
258	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Plugin version: 0.24
259	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Plugin status: testing
260	22.02.2017 14:24:23	WARNING	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Plugin may be unstable
261	22.02.2017 14:24:23	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Config option `use_premium` not found, use default `True`
262	22.02.2017 14:24:23	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Grabbing link info...
263	22.02.2017 14:24:24	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link info: {'status': 7, 'hash': {}, 'name': 'ijqeyxyg', 'url': u'http://www.uploaded.net/file/ijqeyxyg', 'pattern': {}, 'size': 0}
264	22.02.2017 14:24:24	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'ijqeyxyg', 'url': u'http://www.uploaded.net/file/ijqeyxyg', 'pattern': {}, 'size': 0}
265	22.02.2017 14:24:24	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link name: ijqeyxyg
266	22.02.2017 14:24:24	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link size: N/D
267	22.02.2017 14:24:24	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Link status: starte
268	22.02.2017 14:24:24	INFO	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Processing url: http://www.uploaded.net/file/ijqeyxyg
269	22.02.2017 14:24:24	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Config option `fallback` not found, use default `True`
270	22.02.2017 14:24:24	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
271	22.02.2017 14:24:24	DEBUG	HOSTER DebridItaliaCom[1253]: DebridItaliaCom | Config option `revert_failed` not found, use default `True`
272	22.02.2017 14:24:24	WARNING	Download failed: ijqeyxyg | Required account not found
273	22.02.2017 14:24:24	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`

**Comment by Slevin7** [comment]
may look here
https://github.com/pyload/pyload/issues/2736

**Comment by geronimoronin** [comment]
Thank you but it does not help me
I do not understand why it goes with Jdownloader and with Pyload not
are there any differences ?
both access to same API

**Comment by GammaC0de** [comment]
Wow, this is so stupid: `DebridItaliaCom` will not generate link for http://www.uploaded.net/file/3pg4jk8v but will generate link for http://uploaded.net/file/3pg4jk8v, try it.

I am shocked.  :astonished:

**Comment by geronimoronin** [comment]
Hi man you have absolutely right, this works without www 
thank you for your help

**Comment by GammaC0de** [comment]
@geronimoronin Are you going to report this to `DebridItaliaCom`?

**Comment by geronimoronin** [comment]
Yes i did,  but until now no answer Donnerstag, 23 Februar 2017, 02:46nachm. +01:00 von GammaC0de  notifications@github.com :
