### ISSUE TITLE
QUESTION - Is "package_preparing" not working?

### ISSUE THREAD

**Issue by Ryan747800B** [pyload/pyload#2738]
I noticed that if I put a script in "`package_preparing`" it doesn't work (pyLoad doesn't see it as for example `INFO ADDON ExternalScripts: Activated scripts in folder `pyload_start`: ExternalScript.sh`). Is it a bug or a deprecated function?

**Comment by GammaC0de** [comment]
There is no `package_preparing`in [ExternalScripts.py](https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExternalScripts.py), there is a `download_preparing`  though.

**Comment by Ryan747800B** [comment]
You're right, but in `/opt/etc/pyload/script`there are `package_preparing` and `package_processed`... probably some my old test; sorry for the question :confused:
