### ISSUE TITLE
Turbobit.net failure

### ISSUE THREAD

**Issue by damien599901** [pyload/pyload#2739]
Hi all

the turbobit's files don't work with "alldebrid" 
Help hahaha 

thanks to the Pyload's team (of course many thanks to Gammac0de who makes 1 incredible work for the community) 

24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Grabbing link info...
305	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link name: i4qgt7zjrk57.html
306	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link size: N/D
307	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link status: demarrage
308	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Processing url: http://turbobit.net/i4qgt7zjrk57.html
309	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Checking for link errors...
310	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | No errors found
311	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Grabbing link info...
312	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link name: i4qgt7zjrk57.html
313	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link size: N/D
314	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link status: demarrage
315	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Processing as free download...
316	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Checking for link errors...
317	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | No errors found
318	24.02.2017 15:29:36	INFO	HOSTER XFileSharing[3]: TurbobitNet | Waiting 1 seconds...
319	24.02.2017 15:29:38	INFO	Download restarted: i4qgt7zjrk57.html | TEXTAREA F1 not found
320	24.02.2017 15:29:40	INFO	Download starts: i4qgt7zjrk57.html
321	24.02.2017 15:29:40	WARNING	HOSTER XFileSharing[3]: TurbobitNet | Plugin may be unstable
322	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Grabbing link info...
323	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link name: i4qgt7zjrk57.html
324	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link size: N/D
325	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link status: demarrage
326	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Processing url: http://turbobit.net/i4qgt7zjrk57.html
327	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Checking for link errors...
328	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | No errors found
329	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Grabbing link info...
330	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link name: i4qgt7zjrk57.html
331	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link size: N/D
332	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Link status: demarrage
333	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Processing as free download...
334	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Checking for link errors...
335	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | No errors found
336	24.02.2017 15:29:40	INFO	HOSTER XFileSharing[3]: TurbobitNet | Waiting 1 seconds...
337	24.02.2017 15:29:42	INFO	Download restarted: i4qgt7zjrk57.html | TEXTAREA F1 not found
Jump to time:
24.02.2017 15:29:36
  ok

**Comment by GammaC0de** [comment]
First of all, please disable `XFileSharing` plugin.

**Comment by damien599901** [comment]
done and it works now !
thank you so much @Gammac0de

2017-02-24 15:44 GMT+01:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
👍
