### ISSUE TITLE
Nitroflare failure

### ISSUE THREAD

**Issue by damien599901** [pyload/pyload#2740]
Hi all

test done with 1 "alldebrid" account

470	24.02.2017 16:07:20	INFO	Added package test containing 1 links
471	24.02.2017 16:07:21	INFO	Download starts: http://nitroflare.com/view/14FF613A7500746/RE7.B4nnedF00tageV0l1-Zone-Telechargement.ws.rar
472	24.02.2017 16:07:21	WARNING	HOSTER NitroflareCom[8]: Plugin may be unstable
473	24.02.2017 16:07:21	INFO	HOSTER NitroflareCom[8]: Grabbing link info...
474	24.02.2017 16:07:22	INFO	HOSTER NitroflareCom[8]: Link name: RE7.B4nnedF00tageV0l1-Zone-Telechargement.ws.rar
475	24.02.2017 16:07:22	INFO	HOSTER NitroflareCom[8]: Link size: 1.08 GiB (1161332482 bytes)
476	24.02.2017 16:07:22	INFO	HOSTER NitroflareCom[8]: Link status: en ligne
477	24.02.2017 16:07:22	INFO	HOSTER NitroflareCom[8]: Processing url: http://nitroflare.com/view/14FF613A7500746/RE7.B4nnedF00tageV0l1-Zone-Telechargement.ws.rar
478	24.02.2017 16:07:22	INFO	HOSTER NitroflareCom[8]: Checking for link errors...
479	24.02.2017 16:07:22	INFO	HOSTER NitroflareCom[8]: No errors found
480	24.02.2017 16:07:22	INFO	HOSTER NitroflareCom[8]: Processing as free download...
481	24.02.2017 16:07:23	INFO	HOSTER NitroflareCom[8]: Checking for link errors...
482	24.02.2017 16:07:23	WARNING	Download failed: RE7.B4nnedF00tageV0l1-Zone-Telechargement.ws.rar | File can be downloaded by premium users only
483	24.02.2017 16:07:23	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: RE7.B4nnedF00tageV0l1-Zone-Telechargement.ws.rar (pid:8)
484	24.02.2017 16:07:23	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
As you can see, `NitroflareCom` is not handled by `AlldebridCom`.
To check if it is supposed to be handled `AlldebridCom`, I will need an account...
Please send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
https://www.alldebrid.com/api.php?action=get_host

nitroflare.com is not supported by AlldebridCom

**Comment by Velociraptor85** [comment]
@damien599901 will be closed since Hoster ist not supported from AlldebridCom
