### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by Velociraptor85** [pyload/pyload#2744]
Setting up an Gitter channel https://gitter.im for Pyload Project?
In my opinion it could help with communicating and maybe reduce Issues because the would not be posted twice if someone in the chat could give a fast answer to questions?

Any suggestions if this would be a good Idea? Or any alternative?
Lets discuss! Pro/Con, Alternatives, ...?

**Comment by vuolter** [comment]
https://gitter.im/pyload

**Comment by Velociraptor85** [comment]
Great Thanks :) lets try this :+1:
