### ISSUE TITLE
exclude files via sevenzip

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#2745]
Hello, in pyload it's possible to exclude some files. Unrar extract this right but if i extract via sevenzip, i have this exclude files in directory. Is sevenzipt not compatible with these option? 
edit: if i look in 7z, there is an option called exclude files
  -x[r[-|0]]]{@listfile|!wildcard}: eXclude filenames

**Comment by Mister-XY** [comment]
Ok, there must be an small error. With your line`args.append("-x!%s" % word.strip())` it did not exclude the files. But if it do at recursive with r `args.append("-xr!%s" % word.strip())` it's run very fine.

**Comment by Mister-XY** [comment]
But there must also a small error. If he delete the files after extractet, he said extractet failed and did not set permissions. So i can't go into the extracted folder.

**Comment by GammaC0de** [comment]
Explain..  logs..

**Comment by Mister-XY** [comment]
from my modified log or from you original log?

**Comment by GammaC0de** [comment]
>But there must also a small error. If he delete the files after extractet, he said extractet failed and did not set permissions. So i can't go into the extracted folder.

Is this another issue or it is caused by the `"-x!` switch?

**Comment by Mister-XY** [comment]
another error.

`4111	27.02.2017 09:33:59	DEBUG	ADDON ExternalScripts: No script found under folder `package_extract_failed`
4110	27.02.2017 09:33:59	ERROR	ADDON ExtractArchive: XXX.rar | Extract failed
4109	27.02.2017 09:33:59	DEBUG	All downloads finished
4108	27.02.2017 09:33:59	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_finished`
4107	27.02.2017 09:33:59	DEBUG	ADDON ExternalScripts: No script found under folder `archive_extract_failed`
4106	27.02.2017 09:33:59	ERROR	ADDON ExtractArchive: XXX.rar | Archive error | Process return code: 2
4105	27.02.2017 09:33:59	DEBUG	EXTRACTOR SevenZip: EXECUTE 7z l -xr!*.DS_Store -xr!index.dat -xr!thumb.db -xr!*XXX.URL -xr!*XXX.URL -xr!*XXX.in.URL -p- /media/6d286666-8b78-4674-b062-903076bb13b2/Download/jesus/XXX.rar
4104	27.02.2017 09:33:59	INFO	ADDON ExtractArchive: XXX.rar | Extracting finished
4103	27.02.2017 09:33:59	INFO	ADDON ExtractArchive: Deleting 1 files
4102	27.02.2017 09:33:59	DEBUG	ADDON ExtractArchive: Would delete: /media/6d286666-8b78-4674-b062-903076bb13b2/Download/jesus/XXX.rar
4101	27.02.2017 09:33:58	DEBUG	EXTRACTOR SevenZip: EXECUTE 7z x -xr!*.DS_Store -xr!index.dat -xr!thumb.db -xr!*XXX.URL -xr!*XXX.URL -xr!*XXX.in.URL -p- -o/media/6d286666-8b78-4674-b062-903076bb13b2/Download/jesus/ /media/6d286666-8b78-4674-b062-903076bb13b2/Download/jesus/XXX.rar
4100	27.02.2017 09:33:58	DEBUG	ADDON ExtractArchive: Extracting using password: None
4099	27.02.2017 09:33:58	DEBUG	EXTRACTOR SevenZip: EXECUTE 7z l -xr!*.DS_Store -xr!index.dat -xr!thumb.db -xr!*XXX.URL -xr!*XXX.URL -xr!*XXX.in.URL -p- -slt /media/6d286666-8b78-4674-b062-903076bb13b2/Download/jesus/XXX.rar
4098	27.02.2017 09:33:58	DEBUG	ADDON ExtractArchive: Password: None provided
4097	27.02.2017 09:33:58	INFO	ADDON ExtractArchive: XXX.rar | Extract to: /media/6d286666-8b78-4674-b062-903076bb13b2/Download/jesus/
4096	27.02.2017 09:33:58	DEBUG	ADDON ExtractArchive: Targets for SevenZip: [(71, '/media/6d286666-8b78-4674-b062-903076bb13b2/Download/jesus/XXX.rar', '/media/6d286666-8b78-4674-b062-903076bb13b2/Download/jesus/')]
4095	27.02.2017 09:33:58	DEBUG	All downloads processed
4094	27.02.2017 09:33:58	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
4093	27.02.2017 09:33:58	INFO	ADDON ExtractArchive: Check package: jesus
4092	27.02.2017 09:33:58	DEBUG	ADDON ExtractArchive: Use for extensions: 7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
4091	27.02.2017 09:33:58	DEBUG	ADDON ExternalScripts: No script found under folder `package_finished``
