### ISSUE TITLE
extract failed with 7zip

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#2747]
I have a new error with  7zip. After succefully extraction, 7zip get an error. But i have this eeror only, if i let delete the files after succefully extraction. If i keep this files, i have no error. The Problem is, if i let delete the old archives files i have no permission to the extracted folder. If i let old archives alive, i have permission to the extracted folder.
Here is the log.
http://pastebin.com/zQsUn8Mp
and here is the log, if i keep the old archives files
http://pastebin.com/LdrNr3Lc

**Comment by GammaC0de** [comment]
URL?

**Comment by Mister-XY** [comment]
URL? In this case, i have masked my exclude list.

**Comment by GammaC0de** [comment]
> URL? In this case, i have masked my exclude list.

What!?

**Comment by Mister-XY** [comment]
What did you mean with URL?

**Comment by GammaC0de** [comment]
Please post the URL you tried to download in the log

**Comment by Mister-XY** [comment]
it's with every download that i use.

**Comment by Mister-XY** [comment]
any news about it?

**Comment by GammaC0de** [comment]
Sorry, been quite busy.

Please provide a log with just one download in the queue, thanks.

**Comment by Mister-XY** [comment]
Ok here is it.
http://pastebin.com/XmmyKs1U

**Comment by Mister-XY** [comment]
That mean, you have a fix?

**Comment by GammaC0de** [comment]
Not yet

**Comment by Mister-XY** [comment]
ah ok.
