### ISSUE TITLE
pyload crashes raspbian

### ISSUE THREAD

**Issue by fooness** [pyload/pyload#2750]
Excuse me, for this vague report and question here, but it seems that pyload (git, stable) crashes my raspbian system since a few days. Maybe you have any ideas on this.

I can start pyload fine, I think downloading also works without problems, and I mean to have reproduced that almost every time something crashes during or after automatically unpacking the downloaded files, breaking my raspbian system so I have to reboot (files look corrupt, bash does not work anymore correctly, sometimes ssh or even commands like 'su' and 'sudo reboot' don’t work anymore). After having rebooted, everything is okay again.

pyload’s logfiles seem not to be updated since 2017-02-22, which is very strange.

Linux pi 4.4.38-v7+ #\938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux

Python 2.7.9

**Comment by GammaC0de** [comment]
This seems like a hardware problem

**Comment by fooness** [comment]
@GammaC0de
Would you have any ideas on how to dig further into this? I think it’s strange, that the system and hardware is working without problems until pyload is/was unarchiving something. Unarchiving manually with 'unrar' works without problems.

@Slevin7
You mean just cloning my SD card to a new one? I could try so, though I wonder how python/pyload is playing in this weird behavior.

PS: I never wanted to “blame” pyload, just came here for advice or help.

**Comment by GammaC0de** [comment]
I would first try @Slevin7 suggestion as this is a very common issue with SD cards.

If that does not help, I would try to disable the `ExtractAcrive` plugin and see if it make difference.

**Comment by Slevin7** [comment]
@fooness exactly just cloning the sd card.
and never download to your sd card otherwise you rech your read/write limit from the sdcard very fast.

**Comment by fooness** [comment]
So, the last 18 hours my system ran without problems from the new SD card.

@Slevin7 I’m not downloading to the SD card. But maybe it’s also not a good idea that the log files are written to the SD card? Though, other raspbian programs also write logfiles to e.g. /var/ … is that a problem we should think of?

**Comment by darky112** [comment]
@fooness I am using a RPi2 with a 8GB SD.
I am downloading large files over 36GB on a HDD without problems

**Comment by GammaC0de** [comment]
@fooness I'm happy to hear that you solved your problem.
As for the reason this might have happened, there might be few reasons for that such as cheap SD cards.
Even the best SD card will wear eventually.

Anyway, I'm closing this.
