### ISSUE TITLE
Premium Account stop working

### ISSUE THREAD

**Issue by ladigb** [pyload/pyload#2751]
Hi
my two premium account stop working look like don't recognise it like a premium

INFO	ACCOUNT CatShareNet: Adding user `lad*******`...
542	27.02.2017 19:14:27	DEBUG	ACCOUNT CatShareNet: Reached login timeout for user `lad*******`
543	27.02.2017 19:14:27	INFO	ACCOUNT CatShareNet: Relogin user `lad*******`...
544	27.02.2017 19:14:27	DEBUG	ACCOUNT CatShareNet: LOAD URL http://catshare.net/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
545	27.02.2017 19:14:27	DEBUG	ACCOUNT CatShareNet: LOAD URL http://catshare.net/login | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'user[submit]': 'Login', 'user_password': '**********', 'remindPassword': 0, 'user_email': 'lad*******'} | ref=True | just_header=False
546	27.02.2017 19:14:27	ERROR	ACCOUNT CatShareNet: Could not login user `lad*******` | (47, 'Maximum (1) redirects followed')

**Comment by GammaC0de** [comment]
Two CatShareNet accounts or two different accounts?

**Comment by ladigb** [comment]
two different accounts

19:44:15	INFO	ACCOUNT NoPremiumPl: Adding user `nam*******`...
217	27.02.2017 19:44:15	DEBUG	ACCOUNT NoPremiumPl: Reached login timeout for user `nam*******`
218	27.02.2017 19:44:15	INFO	ACCOUNT NoPremiumPl: Relogin user `nam*******`...
219	27.02.2017 19:44:15	DEBUG	ACCOUNT NoPremiumPl: LOAD URL http://crypt.nopremium.pl | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'username': 'nam*******', 'info': '1', 'loc': '1', 'site': 'nopremium', 'output': 'json', 'password': '2a698097ce0ace3b254625942a748c1b9e0daccf'} | ref=True | just_header=False
220	27.02.2017 19:44:15	ERROR	ACCOUNT NoPremiumPl: Could not login user `nam*******` | Login handshake has failed

**Comment by GammaC0de** [comment]
What python version are you running?

Start pyLoad from the console with `python pyLoadCore.py -d` and post the log here.

**Comment by ladigb** [comment]
python: can't open file 'pyLoadCore.py': [Errno 2] No such file or directory

**Comment by GammaC0de** [comment]
Let's focus on CatShare first.

Account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com (you can set to a temporary password).

**Comment by ladigb** [comment]
just sent

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/b19d17b945b7c2b52a1065b43a6f672302da872b

OK, now the other account...

**Comment by ladigb** [comment]
on email

**Comment by GammaC0de** [comment]
```
Logujesz się z innego miejsca niż zazwyczaj. Potwierdź logowanie klikając w link przesłany na adres e-mail (l*****@gmail.com).

Jeżeli nie otrzymano wiadomości, prosimy o sprawdzenie folderu spam i innych zakładek w segregatorze poczty. 
```

**Comment by ladigb** [comment]
i have just confirm it, please try again

**Comment by GammaC0de** [comment]
Same message..

**Comment by ladigb** [comment]
Hi
Please try now, i have swich off it

W dniu pon., 27.02.2017 o 22:34 GammaC0de <notifications@github.com>
napisał(a):

**Comment by GammaC0de** [comment]
OK, it's working now.

**Comment by ladigb** [comment]
OK cool
W dniu pon., 27.02.2017 o 22:38 GammaC0de <notifications@github.com>
napisał(a):

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/f6dbe586baad624c0def2558726ac3d09ab52401
Please test this,
I could not actually download because this site is veeeeeerrry slow to me...

**Comment by ladigb** [comment]
Hi
look like in nopremiumpl download not working 


28.02.2017 08:09:10	INFO	HOSTER NoPremiumPl[392]: NoPremiumPl | No errors found
727	28.02.2017 08:09:10	INFO	HOSTER NoPremiumPl[392]: NoPremiumPl | Grabbing link info...
728	28.02.2017 08:09:10	DEBUG	HOSTER NoPremiumPl[392]: NoPremiumPl | Link info: {'status': 7, 'hash': {}, 'name': 'Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv', 'url': u'http://catshare.net/3OpWtk195qfbQq9g/Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv', 'pattern': {}, 'size': 0}
729	28.02.2017 08:09:10	DEBUG	HOSTER NoPremiumPl[392]: NoPremiumPl | Previous link info: {'status': 7, 'hash': {}, 'name': 'Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv', 'url': u'http://catshare.net/3OpWtk195qfbQq9g/Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv', 'pattern': {}, 'size': 0}
730	28.02.2017 08:09:10	INFO	HOSTER NoPremiumPl[392]: NoPremiumPl | Link name: Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv
731	28.02.2017 08:09:10	INFO	HOSTER NoPremiumPl[392]: NoPremiumPl | Link size: N/D
732	28.02.2017 08:09:10	INFO	HOSTER NoPremiumPl[392]: NoPremiumPl | Link status: rozpoczynam
733	28.02.2017 08:09:10	INFO	HOSTER NoPremiumPl[392]: NoPremiumPl | Processing as premium download...
734	28.02.2017 08:09:10	DEBUG	HOSTER NoPremiumPl[392]: NoPremiumPl | Config option `fallback` not found, use default `True`
735	28.02.2017 08:09:10	WARNING	HOSTER NoPremiumPl[392]: NoPremiumPl | Premium download failed | temp. offline
736	28.02.2017 08:09:10	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
737	28.02.2017 08:09:10	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
738	28.02.2017 08:09:10	INFO	Download restarted: Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv | Fallback to free processing
739	28.02.2017 08:09:10	INFO	Download starts: Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv
740	28.02.2017 08:09:10	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
741	28.02.2017 08:09:10	DEBUG	HOSTER NoPremiumPl[392]: NoPremiumPl | Plugin version: 0.10
742	28.02.2017 08:09:10	DEBUG	HOSTER NoPremiumPl[392]: NoPremiumPl | Plugin status: testing
743	28.02.2017 08:09:10	WARNING	HOSTER NoPremiumPl[392]: NoPremiumPl | Plugin may be unstable
744	28.02.2017 08:09:10	DEBUG	HOSTER NoPremiumPl[392]: NoPremiumPl | Config option `use_premium` not found, use default `True`
745	28.02.2017 08:09:10	INFO	HOSTER NoPremiumPl[392]: NoPremiumPl | Grabbing link info...
746	28.02.2017 08:09:10	DEBUG	HOSTER NoPremiumPl[392]: NoPremiumPl | Link info: {'status': 7, 'hash': {}, 'name': 'Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv', 'url': u'http://catshare.net/3OpWtk195qfbQq9g/Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv', 'pattern': {}, 'size': 0}
747	28.02.2017 08:09:10	DEBUG	HOSTER NoPremiumPl[392]: NoPremiumPl | Previous link info: {'status': 7, 'hash': {}, 'name': 'Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv', 'url': u'http://catshare.net/3OpWtk195qfbQq9g/Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv', 'pattern': {}, 'size': 0}
748	28.02.2017 08:09:10	INFO	HOSTER NoPremiumPl[392]: NoPremiumPl | Link name: Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv
749	28.02.2017 08:09:10	INFO	HOSTER NoPremiumPl[392]: NoPremiumPl | Link size: N/D
750	28.02.2017 08:09:10	INFO	HOSTER NoPremiumPl[392]: NoPremiumPl | Link status: rozpoczynam
751	28.02.2017 08:09:10	INFO	HOSTER NoPremiumPl[392]: NoPremiumPl | Processing url: http://catshare.net/3OpWtk195qfbQq9g/Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv
752	28.02.2017 08:09:10	DEBUG	HOSTER NoPremiumPl[392]: NoPremiumPl | Config option `fallback` not found, use default `True`
753	28.02.2017 08:09:10	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
754	28.02.2017 08:09:10	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
755	28.02.2017 08:09:10	DEBUG	HOSTER NoPremiumPl[392]: NoPremiumPl | Config option `revert_failed` not found, use default `True`
756	28.02.2017 08:09:10	WARNING	Download failed: Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv | Required account not found
757	28.02.2017 08:09:10	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
758	28.02.2017 08:09:10	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Angry.Birds.2016.PLDUB.720p.BluRay.x264-KiT.mkv (pid:174)
759	28.02.2017 08:09:10	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/7116bf39e18994dc97a72705a1c30f1cc8ca40c7
Tested and works.

**Comment by ladigb** [comment]
perfect, thank you for your time and help
