### ISSUE TITLE
Error importing UploadedTo

### ISSUE THREAD

**Issue by PedroGPP** [pyload/pyload#2752]
Hello,

I have this error when i tried to add an uploaded premium account:

619	27.02.2017 23:02:43	ERROR	Error importing UploadedTo: invalid syntax (Plugin.py, line 118)

Please I appreciate all the help to solve this problem.

Regards
Pedro Guerra

**Comment by GammaC0de** [comment]
Same as https://github.com/pyload/pyload/issues/2749, please post there.

What system are you running?
