### ISSUE TITLE
QNAP Zippyshare: No JS Engine

### ISSUE THREAD

**Issue by thestulle** [pyload/pyload#2753]
Hello,

I can not download from Zippyshare. Here the Error:
`WARNING	Download failed: ifkiniuavrkyiuavrkydddvsvmqzx.part20.rar | No JS Engine`

Can everyone help?

**Comment by GammaC0de** [comment]
You have to install javascript interpreter.

**Comment by thestulle** [comment]
Which interpreter must be install?
JRE_ARM does not work!

**Comment by GammaC0de** [comment]
@thestulle Spidermonkey, ossp-js, pyv8 or rhino

**Comment by thestulle** [comment]
Can me everyone tell, how I install one of the JS Engine (Spidermonkey, ossp-js, pyv8 or rhino) under QNAP and Entware?

**Comment by GammaC0de** [comment]
Under entremont it's easy: "opkg installer js"

 

thestulle<notifications@github.com> wrote:   
Can me everyone tell, how I install one of the JS Engine (Spidermonkey, ossp-js, pyv8 or rhino) under QNAP and Entware?

**Comment by thestulle** [comment]
OK,
I don´t understand that:
`[~] # /share/HDA_DATA/.qpkg/Entware-ng/bin/opkg install js
Package js (1.6.20070208-2) installed in root is up to date.
[~] #
`
`302	03.03.2017 12:10:38	INFO	Download starts: ifkiniuavrkyiuavrkydddvsvmqzx.part01.rar
303	03.03.2017 12:10:38	WARNING	HOSTER ZippyshareCom[42]: Plugin may be unstable
304	03.03.2017 12:10:38	INFO	HOSTER ZippyshareCom[42]: Grabbing link info...
305	03.03.2017 12:10:39	INFO	HOSTER ZippyshareCom[42]: Link name: ifkiniuavrkyiuavrkydddvsvmqzx.part01.rar
306	03.03.2017 12:10:39	INFO	HOSTER ZippyshareCom[42]: Link size: 150.00 MiB (157286400 bytes)
307	03.03.2017 12:10:39	INFO	HOSTER ZippyshareCom[42]: Link status: online
308	03.03.2017 12:10:39	INFO	HOSTER ZippyshareCom[42]: Processing url: http://www19.zippyshare.com/v/nh7sRsR0/file.html
309	03.03.2017 12:10:39	INFO	HOSTER ZippyshareCom[42]: Looking for direct download link...
310	03.03.2017 12:10:39	INFO	HOSTER ZippyshareCom[42]: Direct download link not found
311	03.03.2017 12:10:39	INFO	HOSTER ZippyshareCom[42]: Checking for link errors...
312	03.03.2017 12:10:39	INFO	HOSTER ZippyshareCom[42]: No errors found
313	03.03.2017 12:10:39	INFO	HOSTER ZippyshareCom[42]: Processing as free download...
314	03.03.2017 12:10:39	WARNING	CAPTCHA ZippyshareCom[42]: ReCaptcha | Key pattern not found
315	03.03.2017 12:10:44	WARNING	Download failed: ifkiniuavrkyiuavrkydddvsvmqzx.part01.rar | No JS Engin`

Why doesn´t finf Pyload the JS-Engine?

**Comment by GammaC0de** [comment]
Make sure that `share/HDA_DATA/.qpkg/Entware-ng/bin` or wherever 'js' file is located is in your PATH

**Comment by Toerser** [comment]
> 
> 
> Make sure that `share/HDA_DATA/.qpkg/Entware-ng/bin` or wherever `js` file is located is in your PATH

Hi, I have the same problem. I know this thread is old, but I didn't want to open a new issue.

What exactly do you mean by "located in your PATH"? I have java installed (which js responds with /opt/bin/js) but pyload can't find it.

I'm running a QNAP 219P II with Pyload 0.4.9 the latest stable build from github.

Thanks

**Comment by GammaC0de** [comment]
@Toerser do you know what PATH is?

**Comment by Toerser** [comment]
@GammaC0de I don't think so. I thought you meant "file path" or something, but it seems to be a specific config file for python or something.

Im sorry, I'm a total beginner.

**Comment by GammaC0de** [comment]
https://en.wikipedia.org/wiki/PATH_(variable)

If you need more guidance, don't hesitate

**Comment by Toerser** [comment]
@GammaC0de Ok, I understand now, that I have to set the js path (like I said, it should be /opt/bin/js) or the folder above (/opt/bin) in my enviromental variable.

The problem is, I don't know how exactly and where to find it.

I found a **profile**-file with a **PATH** variable in it (in /etc)  where I added the /opt/bin path.

I did the same with the **profile** file in /share/MD0_DATA/.qpkg/Entware-ng/etc and the **S51pyload** file in /share/MD0_DATA/.qpkg/Entware-ng/etc/init.d. But nothing changed. Pyload still doesn't find my java.


This is my edited profile-file in /etc:
`# ~/.bashrc: executed by bash(1) for non-login interactive shells.

export PATH=\
/bin:\
/sbin:\
/usr/bin:\
/usr/sbin:\
/usr/bin/X11:\
/opt/bin:\
/usr/local/sbin

# If running interactively, then:
if [ "$PS1" ]; then

    if [ "$BASH" ]; then
	export PS1="[\u@\h \W]\\$ "
	alias ll='/bin/ls -laFh'
	alias ls='/bin/ls -F'
	export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.png=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:';
    else
      if [ "`id -u`" -eq 0 ]; then 
	export PS1='# '
      else
	export PS1='$ '
      fi
    fi

    export USER=`id -un`
    export LOGNAME=$USER
    export HOSTNAME=`/bin/hostname`
    export HISTSIZE=1000
    export HISTFILESIZE=1000
    export PAGER='/bin/more '
    export EDITOR='/bin/vi'
    export INPUTRC=/etc/inputrc
    export DMALLOC_OPTIONS=debug=0x34f47d83,inter=100,log=logfile
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    export LC_CTYPE=en_US.UTF-8

    ### Some aliases
    alias ps2='ps facux '
    alias ps1='ps faxo "%U %t %p %a" '
    alias af='ps af'
    alias cls='clear'
    alias df='df -h'
    alias indent='indent -bad -bap -bbo -nbc -br -brs -c33 -cd33 -ncdb -ce -ci4 -cli0 -cp33 -cs -d0 -di1 -nfc1 -nfca -hnl -i4 -ip0 -l75 -lp -npcs -npsl -nsc -nsob -nss -ts4 '
    #alias bc='bc -l'
    alias minicom='minicom -c on'
    alias calc='calc -Cd '
    alias bc='calc -Cd '
fi;
export PATH=${PATH}:/usr/local/bin
alias smb3enable='/etc/init.d/smb2_protocol.sh enable 3'
alias smb21enable='/etc/init.d/smb2_protocol.sh enable 21'
alias smb2enable='/etc/init.d/smb2_protocol.sh enable'
alias smb2disable='/etc/init.d/smb2_protocol.sh disable'
alias smb2status='/etc/init.d/smb2_protocol.sh status'
alias usb_qa_status='/etc/init.d/smb2_protocol.sh usb_qa_status'
export JAVA_HOME=/usr/local/jre
export PATH=$PATH:$JAVA_HOME/bin
`

**Comment by GammaC0de** [comment]
You might have to do a restart in order it to take effect but I suggest  you edit `/share/MD0_DATA/.qpkg/Entware-ng/etc/init.d/S51pyload` and add a line containing
```
export PATH==/opt/bin:/opt/sbin:$PATH
```

as one of the first lines on that file

**Comment by Toerser** [comment]
Like this?
```
#!/bin/sh

export PATH==/opt/bin:/opt/sbin:$PATH
prefix="/opt"
PATH=${prefix}/bin:${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/bin:/share/MD0_DATA/.qpkg/JRE_ARM/jre/bin:/share/MD0_DATA/.qpkg/JRE/jre/bin

start() {
	echo "starting pyLoad"
	pyload --daemon --configdir=/opt/var/pyload
	}

stop() {
	echo "stopping pyLoad"
	pyload --quit --configdir=/opt/var/pyload
	}

```

**Comment by Toerser** [comment]
Even after reboot pyload does not find Java, but the PATH should be alright.

If I type in
`echo $PATH`
it returns
`/opt/bin:/opt/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/bin:/share/MD0_DATA/.qpkg/JRE_ARM/jre/bin:/share/MD0_DATA/.qpkg/JRE/jre/bin
`
I added the other two Java pathes I found. And it seems to be fine.

But if I load the pyLoad init script with
`pyload --configdir=/opt/var/pyload -s
`
it returns
```

## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: missing

py-imaging: OK
tesseract: OK

PyQt4: missing

jinja2: OK
beaker: OK
JS engine: missing

```

**Comment by GammaC0de** [comment]
try uninstalling `js` and installing `rhino` instead

**Comment by GammaC0de** [comment]
Also, please read https://github.com/pyload/pyload/issues/3283

**Comment by Toerser** [comment]
> 
> 
> Also, please read #3283

I did it again, ok.

I uninstalled js with
`opkg remove js`
but
`opkg install rhino`
results in
`Unknown package 'rhino'`

**Comment by GammaC0de** [comment]
Try `opkg install duktape`

**Comment by Toerser** [comment]
installed it.
`which js`
still returns the same path

but still JS missing.

I really don't know what I am doing wrong. :/

**Comment by GammaC0de** [comment]
Have you followed the instruction in https://github.com/pyload/pyload/issues/3283?

**Comment by Toerser** [comment]
> 
> 
> Have you followed the instruction in #3283?

Yes I have. Word by word.
- delete userplugins
- owerwrite install folder with newest stable build

**Comment by GammaC0de** [comment]
Are you using python installed from entware?

**Comment by Toerser** [comment]
I guess so. I installed it by:
`opkg install python python-pip python-crypto python-curl python-openssl pillow tesseract js unrar`

**Comment by GammaC0de** [comment]
Have you restarted pyload after installing duktape?

**Comment by Toerser** [comment]
Yes, I also rebooted the complete QNAP System.

**Comment by GammaC0de** [comment]
Then  uninstall duktape and do `/opt/bin/pip2.7 install js2py` and retry.

**Comment by Toerser** [comment]
You are indeed a saint...

I downloaded a Zippyfile-link for the very first time. It took a while, because it said "No JS" again a few times, but then it downloaded it.

Strange thing is: `which js` doesn't result in any answer.

I will try a few links and get back here with the result. But for now I really appreciate the effort you took in this. Thank you very much. :)

**Comment by GammaC0de** [comment]
:+1:
