### ISSUE TITLE
Temporary connection problems after update

### ISSUE THREAD

**Issue by markusbaumer** [pyload/pyload#2757]
After the current auto-update this morning most downloads don't start directly but with a delay and log messages like:

```
02.03.2017 08:15:06	WARNING	Couldn't connect to host or connection reset, waiting 1 minute and retry.
02.03.2017 08:14:35	INFO	HOSTER UploadedTo[6]: Grabbing link info...
```

Sometimes it retries a few times sometimes the download started after the first minute. I didn't change anything with my configuration ... everything worked fine yesterday before the update.

**Comment by Velociraptor85** [comment]
maybe try the solution from https://github.com/pyload/pyload/issues/2758

**Comment by Velociraptor85** [comment]
@markusbaumer hello Markus ... would you try the solution? and report back if it worked 😄

**Comment by markusbaumer** [comment]
It didn't work instantly... but meanwhile I haven't been able to reproduce the problem again. So maybe it was some kind of side effect and can be called resolved now.

**Comment by Velociraptor85** [comment]
OK will close than 👍
