### ISSUE TITLE
Pyload broken after update

### ISSUE THREAD

**Issue by szczepan79** [pyload/pyload#2758]
Hello 

after last update pyload not works:

INFO	Aktywne wtyczki:
86	01.03.2017 10:49:42	INFO	Nieaktywne wtyczki:AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
87	01.03.2017 10:49:42	INFO	Czas pobierania: True
88	01.03.2017 10:49:43	INFO	Uruchamiam ThriftBackend: 0.0.0.0:7227
89	01.03.2017 10:49:43	INFO	Wolne miejsce: 254.07 GiB
90	01.03.2017 10:49:45	INFO	Starting threaded webserver: 0.0.0.0:7272
91	01.03.2017 10:49:43	INFO	Aktywacja kont ...
92	01.03.2017 10:49:45	ERROR	Error importing UploadedTo: No module named json
93	02.03.2017 07:18:48	ERROR	Error importing UploadedTo: No module named json
94	02.03.2017 07:18:54	ERROR	Error importing UploadedTo: No module named json
95	02.03.2017 07:22:41	INFO	Rozpoczynam pyLoad 0.4.9
96	02.03.2017 07:22:41	INFO	Używam katalogu domowego: /i-data/8f70b6b8/admin/zy-pkgs/pyLoad/etc/pyload
97	02.03.2017 07:22:54	ERROR	Błąd przy imporcie UpdateManager: No module named json
98	02.03.2017 07:22:54	ERROR	Błąd przy imporcie UnSkipOnFail: No module named json
99	02.03.2017 07:22:54	ERROR	Błąd przy imporcie EventMapper: No module named json
100	02.03.2017 07:22:54	ERROR	Błąd przy imporcie ExternalScripts: No module named json
101	02.03.2017 07:22:55	ERROR	Błąd przy imporcie AntiStandby: No module named json
102	02.03.2017 07:22:55	ERROR	Błąd przy imporcie ExtractArchive: No module named json
103	02.03.2017 07:22:55	ERROR	Błąd przy imporcie XFileSharing: No module named json
104	02.03.2017 07:22:55	ERROR	Błąd przy imporcie ClickNLoad: No module named json
105	02.03.2017 07:22:55	ERROR	Błąd przy imporcie UserAgentSwitcher: No module named json
106	02.03.2017 07:22:55	INFO	Aktywne wtyczki: 

Download is off and i couldn't turn it on.

**Comment by Bloodpack** [comment]
Same here.....

root@apophis:~# python /opt/pyload/pyLoadCore.py
02.03.2017 09:19:40 INFO      starte pyLoad 0.4.9
02.03.2017 09:19:40 INFO      Benutze Home-Verzeichnis: /root/.pyload
02.03.2017 09:19:41 ERROR     Fehler beim importieren von MergeFiles: No module named Plugin
02.03.2017 09:19:41 ERROR     Fehler beim importieren von EventMapper: No module named Plugin
02.03.2017 09:19:41 ERROR     Fehler beim importieren von ExternalScripts: No module named Plugin
02.03.2017 09:19:41 ERROR     Fehler beim importieren von ClickNLoad: No module named Plugin
02.03.2017 09:19:41 ERROR     Fehler beim importieren von UnSkipOnFail: No module named Plugin
02.03.2017 09:19:41 ERROR     Fehler beim importieren von ExtractArchive: No module named Plugin
02.03.2017 09:19:41 ERROR     Fehler beim importieren von XFileSharing: No module named Plugin
02.03.2017 09:19:41 ERROR     Fehler beim importieren von UpdateManager: No module named Plugin
02.03.2017 09:19:41 ERROR     Fehler beim importieren von UserAgentSwitcher: No module named Plugin
02.03.2017 09:19:41 INFO      Aktivierte Plugins:
02.03.2017 09:19:41 INFO      Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
02.03.2017 09:19:41 INFO      Downloadzeit: True
02.03.2017 09:19:41 INFO      Starting builtin webserver: 192.168.178.22:8000
02.03.2017 09:19:41 INFO      Free space: 5.86 TiB
02.03.2017 09:19:41 INFO      Activating Accounts...
02.03.2017 09:19:41 ERROR     Error importing UploadedTo: No module named Plugin
Traceback (most recent call last):
  File "/opt/pyload/pyLoadCore.py", line 667, in <module>
    main()
  File "/opt/pyload/pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "/opt/pyload/pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

any suggestions?

**Comment by geronimoronin** [comment]
The same here

**Comment by Bloodpack** [comment]
I just reinstalled pyLoad from Git.....

now it works fine!

**Comment by geronimoronin** [comment]
by me  running  pyload as Entware-ng in my router git clone Does not work there

**Comment by geronimoronin** [comment]
Have now solved also problem Have  everything copied manuel from github to my Router is it works.

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/0e70d89f52c18b4ffc637ee76a34ac6d1b7831a9

**Comment by Velociraptor85** [comment]
also had the problem ... one could also download `wget https://github.com/pyload/pyload/archive/stable.zip` for example

Also since I have installed it via apt my folder was in `/usr/share/pyload` ... so download here and start as usual.

**Comment by Web-Eye** [comment]
Thanks a lot, solved my issue too....
I've just cloned it!
Greets, WebEye

**Comment by diman82** [comment]
> also had the problem ... one could also download `wget https://github.com/pyload/pyload/archive/stable.zip` for example
> 
> Also since I have installed it via apt my folder was in `/usr/share/pyload` ... so download here and start as usual.
> 
> edit: I had to change 2 lines in cnl_app.py since thats not in the repo yet look at https://github.com/pyload/pyload/pull/2717/files and https://github.com/pyload/pyload/pull/1784/files

Also, this helped me:
https://github.com/pyload/pyload/issues/2344#issuecomment-186737934
