### ISSUE TITLE
Pyload no longer supports php 2.5x (read me, if you have problems since a few days)

### ISSUE THREAD

**Issue by gitpaulgit** [pyload/pyload#2762]
so if your system is using this version you need to update if possible.
otherwise many python operations will fail.

My problem is, i ve updated my Linkstation Live to PHP 2.6 and also to PHP 2.7 but if i start pyload the system seems to use PHP 2.5 by default (i also tried to setup pyload with -s again to get a new clean configuration). 

So how can i configure that the Linkstation starts up pyload with PHP 2.7?

**Comment by GammaC0de** [comment]
First of all, pyLoad uses Python, not PHP.

Secondly, Python 2.5 support was resumed, please update your pyLoad to the latest.
