### ISSUE TITLE
Webshare - download doesn't work because of "ID"

### ISSUE THREAD

**Issue by BKPepe** [pyload/pyload#2764]
> Download starts: mnslk07.part1.rar
> 02.03.2017 14:44:27 WARNING   HOSTER WebshareCz[14]: Plugin may be unstable
> 02.03.2017 14:44:27 INFO      ACCOUNT WebshareCz: Grabbing account info for user                           `Pep*******`...
> 02.03.2017 14:44:27 INFO      HOSTER WebshareCz[14]: Grabbing link info...
> 02.03.2017 14:44:27 INFO      HOSTER WebshareCz[14]: Link name: mnslk07.part1.ra                          r
> 02.03.2017 14:44:27 INFO      HOSTER WebshareCz[14]: Link size: 1.71 GiB (183500                          8000 bytes)
> 02.03.2017 14:44:27 INFO      HOSTER WebshareCz[14]: Link status: online
> 02.03.2017 14:44:27 INFO      HOSTER WebshareCz[14]: Processing url: https://web                          share.cz/file/6on2hMmEoK/mnslk07-part1-rar
> 02.03.2017 14:44:27 INFO      HOSTER WebshareCz[14]: Looking for direct download                           link...
> 02.03.2017 14:44:27 INFO      HOSTER WebshareCz[14]: Direct download link not fo                          und
> 02.03.2017 14:44:27 INFO      HOSTER WebshareCz[14]: Checking for link errors...
> 02.03.2017 14:44:27 INFO      HOSTER WebshareCz[14]: No errors found
> 02.03.2017 14:44:27 INFO      HOSTER WebshareCz[14]: Processing as premium downl                          oad...
> 02.03.2017 14:44:27 INFO      ACCOUNT WebshareCz: Grabbing account info for user                           `Pep*******`...
> 02.03.2017 14:44:27 WARNING   Download failed: mnslk07.part1.rar | 'ID'
> 02.03.2017 14:44:27 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates                           of: mnslk07.part1.rar (pid:4)
> 02.03.2017 14:44:27 INFO      ADDON UnSkipOnFail: No duplicates found
> 

I can provide acc, if you want.

**Comment by GammaC0de** [comment]
Same as #2763

**Comment by BKPepe** [comment]
Noticed that there, but I thought that you would like to separate issue for UploadedTo and Webshare.
Iˇm fine with that. Hopefully it will get fixed soon.

**Comment by GammaC0de** [comment]
👍 Trying to figure out the cause of this..

**Comment by BKPepe** [comment]
Hello,
I have this issue again.

> 27.03.2017 06:57:16	INFO	ADDON UpdateManager: pyLoad is up to date!
> 800	27.03.2017 06:57:17	INFO	ADDON UpdateManager: All plugins are up to date!
> 801	27.03.2017 07:51:10	INFO	HOSTER UlozTo[1371]: File saved
> 802	27.03.2017 07:51:10	INFO	CAPTCHA UlozTo[1371]: Captcha | Correct captcha | tNZd
> 803	27.03.2017 07:51:10	INFO	HOSTER UlozTo[1371]: Checking download...
> 804	27.03.2017 07:51:10	INFO	HOSTER UlozTo[1371]: File is OK
> 805	27.03.2017 07:51:10	INFO	HOSTER UlozTo[1371]: Checking file (with built-in rules)...
> 806	27.03.2017 07:51:10	INFO	HOSTER UlozTo[1371]: Checking file (with custom rules)...
> 807	27.03.2017 07:51:10	INFO	HOSTER UlozTo[1371]: Checking for link errors...
> 808	27.03.2017 07:51:10	INFO	HOSTER UlozTo[1371]: No errors found
> 809	27.03.2017 07:51:10	INFO	HOSTER UlozTo[1371]: No errors found
> 810	27.03.2017 07:51:10	INFO	Download finished: 04D75C5BE69207620C48D65726EC3A96D203320283230313229204D656E20696E20426C61636B2033.part3.rar
> 811	27.03.2017 09:50:53	INFO	Download starts: https://webshare.cz/file/79e6rD7971/wt3bd-part01-rar
> 812	27.03.2017 09:50:53	WARNING	HOSTER WebshareCz[1416]: Plugin may be unstable
> 813	27.03.2017 09:50:53	WARNING	Download failed: https://webshare.cz/file/79e6rD7971/wt3bd-part01-rar | 'NoneType' object has no attribute 'get_info'
> 814	27.03.2017 09:50:53	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: https://webshare.cz/file/79e6rD7971/wt3bd-part01-rar (pid:140)
> 815	27.03.2017 09:50:53	INFO	ADDON UnSkipOnFail: No duplicates found
