### ISSUE TITLE
pycurl error 23: Failed writing body - UploadedTo

### ISSUE THREAD

**Issue by bbosiljcic** [pyload/pyload#2766]
I have Issues downloading from uploaded. 

I tried updating the hoster plugin, didn't help.

This is my log output. 

```02.03.2017 17:13:41	INFO	ACCOUNT UploadedTo: Grabbing account info for user 9*********...
02.03.2017 17:13:41	INFO	HOSTER UploadedTo[3]: Grabbing link info...
02.03.2017 17:13:41	INFO	HOSTER UploadedTo[3]: Link name: somefile.tar
02.03.2017 17:13:41	INFO	HOSTER UploadedTo[3]: Link size: 1.36 GiB (1464962860 bytes)
02.03.2017 17:13:41	INFO	HOSTER UploadedTo[3]: Link status: online
02.03.2017 17:13:41	INFO	HOSTER UploadedTo[3]: Processing url: http://uploaded.net/file/some/somefile.tar
02.03.2017 17:13:41	INFO	HOSTER UploadedTo[3]: Looking for direct download link...
02.03.2017 17:13:41	INFO	HOSTER UploadedTo[3]: Direct download link not found
02.03.2017 17:13:41	ERROR	pycurl error 23: Failed writing body (0 != 1348)
02.03.2017 17:13:41	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: somefile.tar (pid:3)
02.03.2017 17:13:41	INFO	ADDON UnSkipOnFail: No duplicates found```

**Comment by topy** [comment]
same here. Issue occuring since a few days

**Comment by thera314** [comment]
same here too with Uptobox.com :(

**Comment by RickyTR** [comment]
Same with easybytez.com premium account.

**Comment by PedroGPP** [comment]
@GammaC0de Is there a solution to this problem?

**Comment by GammaC0de** [comment]
First of all, delete your `userplugins` folder and update to the latest git.

If the problem continues, please provide the below information:
* URL with the issue
* DEBUG log, preferably when run with `python pyLoadCore.py -d`
* Is this a premium download?

**Comment by thera314** [comment]
Hi GammaC0de,

Thanks in advance for your help.

I've just update to the latest git and pb still remains.

URL : http://uptobox.com/6rg96lkwm75m
Premium download : yes

Debug 👍 

03.03.2017 13:32:38	DEBUG	HOSTER UptoboxCom[2]: Plugin status: testing
321	03.03.2017 13:32:38	WARNING	HOSTER UptoboxCom[2]: Plugin may be unstable
322	03.03.2017 13:32:38	DEBUG	ACCOUNT UptoboxCom: Reached login timeout for user `the*******`
323	03.03.2017 13:32:38	INFO	ACCOUNT UptoboxCom: Relogin user `the*******`...
324	03.03.2017 13:32:38	DEBUG	ACCOUNT UptoboxCom: LOAD URL https://login.uptobox.com/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
325	03.03.2017 13:32:41	DEBUG	ACCOUNT UptoboxCom: LOAD URL https://login.uptobox.com/logarithme | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'redirect': 'http://uptobox.com/', 'login': 'the*******', 'password': '**********', 'op': 'login'} | ref=True | just_header=False
326	03.03.2017 13:32:41	INFO	ACCOUNT UptoboxCom: Grabbing account info for user `the*******`...
327	03.03.2017 13:32:41	DEBUG	ACCOUNT UptoboxCom: LOAD URL http://uptobox.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
328	03.03.2017 13:32:41	DEBUG	ACCOUNT UptoboxCom: Expire date: 15 January 2018
329	03.03.2017 13:32:41	DEBUG	ACCOUNT UptoboxCom: Valid until: 1515970800.0
330	03.03.2017 13:32:41	DEBUG	ACCOUNT UptoboxCom: TRAFFIC LEFT PATTERN not found
331	03.03.2017 13:32:41	DEBUG	ACCOUNT UptoboxCom: LEECH TRAFFIC PATTERN not found
332	03.03.2017 13:32:41	DEBUG	ACCOUNT UptoboxCom: Account info for user `the*******`: {'login': {'timestamp': 1488544358.518756, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1515970800.0, 'login': 'the*******', 'type': 'UptoboxCom', 'options': {'limitdl': ['0']}}}
333	03.03.2017 13:32:41	INFO	HOSTER UptoboxCom[2]: Grabbing link info...
334	03.03.2017 13:32:41	DEBUG	HOSTER UptoboxCom[2]: Link info: {'status': 2, 'hash': {}, 'name': 'Uniformes+et+Grandes+Manoeuvres.(1950+avec+Fernandel).DvDRip.DivX+-.rar', 'url': u'http://uptobox.com/6rg96lkwm75m', 'pattern': {'S': u'699.0', 'U': u'MB', 'N': u'Uniformes+et+Grandes+Manoeuvres.(1950+avec+Fernandel).DvDRip.DivX+-.rar'}, 'size': 732954624}
335	03.03.2017 13:32:41	DEBUG	HOSTER UptoboxCom[2]: Previous link info: {}
336	03.03.2017 13:32:41	INFO	HOSTER UptoboxCom[2]: Link name: Uniformes+et+Grandes+Manoeuvres.(1950+avec+Fernandel).DvDRip.DivX+-.rar
337	03.03.2017 13:32:41	INFO	HOSTER UptoboxCom[2]: Link size: 699.00 MiB (732954624 bytes)
338	03.03.2017 13:32:41	INFO	HOSTER UptoboxCom[2]: Link status: en ligne
339	03.03.2017 13:32:41	INFO	HOSTER UptoboxCom[2]: Processing url: http://uptobox.com/6rg96lkwm75m
340	03.03.2017 13:32:41	INFO	HOSTER UptoboxCom[2]: Looking for direct download link...
341	03.03.2017 13:32:41	DEBUG	HOSTER UptoboxCom[2]: LOAD URL http://uptobox.com/6rg96lkwm75m | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
342	03.03.2017 13:32:41	INFO	HOSTER UptoboxCom[2]: Direct download link not found
343	03.03.2017 13:32:41	DEBUG	HOSTER UptoboxCom[2]: LOAD URL http://uptobox.com/6rg96lkwm75m | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
344	03.03.2017 13:32:42	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
345	03.03.2017 13:32:42	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
346	03.03.2017 13:32:42	DEBUG	pycurl exception 23: Failed writing body (0 != 16384)
347	03.03.2017 13:32:42	ERROR	pycurl error 23: Failed writing body (0 != 16384)
348	03.03.2017 13:32:42	INFO	Debug Report written to debug_UptoboxCom_03-03-2017_13-32-42.zip
349	03.03.2017 13:32:42	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
350	03.03.2017 13:32:42	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Uniformes+et+Grandes+Manoeuvres.(1950+avec+Fernandel).DvDRip.DivX+-.rar (pid:2)
351	03.03.2017 13:32:42	INFO	ADDON UnSkipOnFail: No duplicates found
352	03.03.2017 13:32:42	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
353	03.03.2017 13:32:42	DEBUG	All downloads processed 

Kind regards,

tHeRa314

**Comment by GammaC0de** [comment]
Account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by thera314** [comment]
Login info sent. Thank you very much !

**Comment by thera314** [comment]
Thanks Gamma ! Everything is working perfectly with Uptobox !

**Comment by PedroGPP** [comment]
@GammaC0de Perfect with uploaded, thank you.

**Comment by PedroGPP** [comment]
@GammaC0de I don't know if it is relevant, but despite the success download i still have in my logs this message:
WARNING	HOSTER UploadedTo[4]: Plugin may be unstable

**Comment by topy** [comment]
@GammaC0de perfect! thx :)

**Comment by GammaC0de** [comment]
@PedroGPP .This is a normal message for every plugin with status "testing"

**Comment by bbosiljcic** [comment]
@GammaC0de Thank you for the effort working for me aswell
