### ISSUE TITLE
extractarchive log overflow

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#2770]
Hello and here are the next error after the great upgrade yesterday.
My log are full with this message: After remove it from my qeue, i must kill pyload and erase my files.db, because, pyload didn't start.
12	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc
11	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc
10	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc
9	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc
8	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc
7	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc
6	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc
5	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc
4	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc
3	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc
2	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc
1	03.03.2017 06:30:43	INFO	ADDON ExtractArchive: Check package: XXX - filecrypt.cc

**Comment by Mister-XY** [comment]
And here is the next error.
http://pastebin.com/Mbk9qyz2

**Comment by GammaC0de** [comment]
Have you managed to fix this?
Can this be closed?

**Comment by Mister-XY** [comment]
What did you mean?

**Comment by GammaC0de** [comment]
Do you still have this issue?

**Comment by Mister-XY** [comment]
after the update from today Or did you mean after the last 7zip fix? after the last 7zip fix, it run on main archive good, but it did not extract in subfolder.

**Comment by GammaC0de** [comment]
OK then, 
You already opened an issue for this (https://github.com/pyload/pyload/issues/2770),
Closing.

**Comment by Mister-XY** [comment]
This error ist closed, that extractarchive spam the log?

**Comment by GammaC0de** [comment]
I don't understand,
I asked if you still have the issue of "extractarchive spaming the log", you said no...
Why not close this?

**Comment by Mister-XY** [comment]
I dont't say no, i have ask you
"after the update from today Or did you mean after the last 7zip fix?"
