### ISSUE TITLE
Zippyshare issue: 'NoneType' object has no attribute 'ZippyshareCom' 

### ISSUE THREAD

**Issue by led13714** [pyload/pyload#2775]
- UpdateManager v0.16
- ZippyshareCom.py v0.91

Link: http://www105.zippyshare.com/v/sygx6GsJ/file.html

Log (reversed):

04.03.2017 16:19:37	CRITICAL	'NoneType' object has no attribute 'ZippyshareCom'
416	04.03.2017 16:19:37	ERROR	Error importing ZippyshareCom: invalid syntax (Plugin.py, line 118)
415	04.03.2017 16:19:37	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
414	04.03.2017 16:19:37	DEBUG	Redirected import module.plugins.captcha.ReCaptcha -> userplugins.captcha.ReCaptcha
413	04.03.2017 16:19:35	CRITICAL	'NoneType' object has no attribute 'ZippyshareCom'
412	04.03.2017 16:19:35	ERROR	Error importing ZippyshareCom: invalid syntax (Plugin.py, line 118)
411	04.03.2017 16:19:35	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
410	04.03.2017 16:19:35	DEBUG	Redirected import module.plugins.captcha.ReCaptcha -> userplugins.captcha.ReCaptcha
409	04.03.2017 16:17:45	INFO	pyLoad is up and running
408	04.03.2017 16:17:45	INFO	Activating Plugins...
407	04.03.2017 16:17:45	INFO	Activating Accounts...
406	04.03.2017 16:17:45	INFO	Starting threaded webserver: 192.168.0.16:8000
405	04.03.2017 16:17:44	INFO	Freier Speicher: 175.67 GiBGB
404	04.03.2017 16:17:44	INFO	Starte ThriftBackend: 0.0.0.0:7227
403	04.03.2017 16:17:44	INFO	Downloadzeit: True
402	04.03.2017 16:17:44	INFO	Deaktivierte Plugins: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
401	04.03.2017 16:17:44	INFO	Aktivierte Plugins:
400	04.03.2017 16:17:44	ERROR	Fehler beim importieren von UserAgentSwitcher: invalid syntax (Plugin.py, line 118)
399	04.03.2017 16:17:44	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
398	04.03.2017 16:17:44	ERROR	Fehler beim importieren von ClickNLoad: invalid syntax (Plugin.py, line 118)
397	04.03.2017 16:17:44	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
396	04.03.2017 16:17:44	DEBUG	Redirected import module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
395	04.03.2017 16:17:44	ERROR	Fehler beim importieren von XFileSharing: invalid syntax (Plugin.py, line 118)
394	04.03.2017 16:17:44	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
393	04.03.2017 16:17:44	ERROR	Fehler beim importieren von UnSkipOnFail: invalid syntax (Plugin.py, line 118)
392	04.03.2017 16:17:44	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
391	04.03.2017 16:17:44	ERROR	Fehler beim importieren von AntiStandby: invalid syntax (Plugin.py, line 118)
390	04.03.2017 16:17:44	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
389	04.03.2017 16:17:44	ERROR	Fehler beim importieren von ExternalScripts: invalid syntax (Plugin.py, line 118)
388	04.03.2017 16:17:44	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
387	04.03.2017 16:17:44	ERROR	Fehler beim importieren von EventMapper: invalid syntax (Plugin.py, line 118)
386	04.03.2017 16:17:44	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
385	04.03.2017 16:17:44	ERROR	Fehler beim importieren von MergeFiles: invalid syntax (Plugin.py, line 118)
384	04.03.2017 16:17:44	DEBUG	Redirected import module.plugins.internal.Plugin -> userplugins.internal.Plugin
383	04.03.2017 16:17:44	ERROR	Fehler beim importieren von UpdateManager: No module named Hook
382	04.03.2017 16:17:44	DEBUG	created index of plugins
381	04.03.2017 16:17:42	DEBUG	Remote activated: True
380	04.03.2017 16:17:42	INFO	Benutze Home-Verzeichnis: /root/.pyload
379	04.03.2017 16:17:42	INFO	starte pyLoad 0.4.9

Haven't noticed any pyload updates. Anyone able to help?

**Comment by GammaC0de** [comment]
Duplicate of https://github.com/pyload/pyload/issues/2749, please manually update all of your plugins.

**Comment by led13714** [comment]
So just replace my modules folder withthe contents of: https://github.com/pyload/pyload/tree/stable/module ?

**Comment by GammaC0de** [comment]
Yes

**Comment by led13714** [comment]
yes that solved my issues, thank you @GammaC0de
