### ISSUE TITLE
failed'NoneType' object has no attribute 'Keep2ShareCc' 0.00 BKeep2ShareCc

### ISSUE THREAD

**Issue by digimon04** [pyload/pyload#2778]
tested url:
http://k2s.cc/file/f4f26b0511ccc/GHKO-11.part1.rar

logs:

06.03.2017 07:01:07	INFO	Starting pyLoad 0.4.9
917	06.03.2017 07:01:07	INFO	Using home directory: /tmp/mnt/sda1/entware/var/pyload
918	06.03.2017 07:01:15	ERROR	Error importing UpdateManager: No module named Plugin
919	06.03.2017 07:01:15	ERROR	Error importing MergeFiles: No module named Plugin
920	06.03.2017 07:01:15	ERROR	Error importing EventMapper: No module named Plugin
921	06.03.2017 07:01:15	ERROR	Error importing ExternalScripts: No module named Plugin
922	06.03.2017 07:01:15	ERROR	Error importing UnSkipOnFail: No module named Plugin
923	06.03.2017 07:01:15	ERROR	Error importing ExtractArchive: No module named Plugin
924	06.03.2017 07:01:15	ERROR	Error importing XFileSharing: No module named Plugin
925	06.03.2017 07:01:15	ERROR	Error importing ClickNLoad: No module named Plugin
926	06.03.2017 07:01:15	ERROR	Error importing UserAgentSwitcher: No module named Plugin
927	06.03.2017 07:01:15	INFO	Activated plugins:
928	06.03.2017 07:01:15	INFO	Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
929	06.03.2017 07:01:15	INFO	Downloadtime: True
930	06.03.2017 07:01:15	INFO	Using SSL ThriftBackend
931	06.03.2017 07:01:15	INFO	Starting ThriftBackend: 0.0.0.0:7227
932	06.03.2017 07:01:23	INFO	Starting builtin webserver: 0.0.0.0:8000
933	06.03.2017 07:01:23	INFO	Free space: 3.33 GiB
934	06.03.2017 07:01:23	INFO	Activating Accounts...
935	06.03.2017 07:01:23	INFO	Activating Plugins...
936	06.03.2017 07:01:23	INFO	pyLoad is up and running
937  06.03.2017 07:06:12	INFO	Added package GHKO-11 containing 3 links
938	06.03.2017 07:06:12	ERROR	Error importing Keep2ShareCc: No module named Plugin
939	06.03.2017 07:06:13	ERROR	Error importing Keep2ShareCc: No module named Plugin
940	06.03.2017 07:06:13	CRITICAL	'NoneType' object has no attribute 'Keep2ShareCc'
941	06.03.2017 07:06:13	INFO	Added package GHKO-11 containing 3 links
942	06.03.2017 07:06:13	ERROR	Error importing Keep2ShareCc: No module named Plugin
943	06.03.2017 07:06:15	ERROR	Error importing Keep2ShareCc: No module named Plugin
944	06.03.2017 07:06:15	CRITICAL	'NoneType' object has no attribute 'Keep2ShareCc'
945	06.03.2017 07:06:17	ERROR	Error importing Keep2ShareCc: No module named Plugin
946	06.03.2017 07:06:17	CRITICAL	'NoneType' object has no attribute 'Keep2ShareCc'
947	06.03.2017 07:06:19	ERROR	Error importing Keep2ShareCc: No module named Plugin
948	06.03.2017 07:06:19	CRITICAL	'NoneType' object has no attribute 'Keep2ShareCc'
949	06.03.2017 07:06:21	ERROR	Error importing Keep2ShareCc: No module named Plugin
950	06.03.2017 07:06:21	CRITICAL	'NoneType' object has no attribute 'Keep2ShareCc'
951	06.03.2017 07:06:23	ERROR	Error importing Keep2ShareCc: No module named Plugin
952	06.03.2017 07:06:23	CRITICAL	'NoneType' object has no attribute 'Keep2ShareCc'

Re-installing Pyload didn't help. What could be the problem? Thanks

**Comment by geronimoronin** [comment]
Hi look here #2758

**Comment by GammaC0de** [comment]
No response, closing.
