### ISSUE TITLE
QUESTION - See/Send pyLoad event-script output to a log file

### ISSUE THREAD

**Issue by Ryan747800B** [pyload/pyload#2779]
I tried to send the output log of a script that runs from `package_finished` to a log file (and to see it remotely with `cp` command) and in someway it works but I don't see the output progress in Terminal (it works, but there isn't the spinning progress wheel `'/' '-' '\' '|'` )

```
#!/bin/bash

marks=( '/' '-' '\' '|' )

sh /opt/etc/pyload/scripts/package_finished/SCRIPTS/Script.sh >>/opt/etc/pyload/Logs/ScriptLog.txt 2>&1

i=0
tail -f /opt/etc/pyload/Logs/ScriptLog.txt | while read LOGLINE
do
    printf "\rScript is running ... ${marks[i++ % ${#marks[@]}]}"
    sleep 0.1
    [[ "${LOGLINE}" == *"Completed!"* ]] && (pkill -P $$ tail; printf "\rScript is running, please wait ... Done.\n";)
done
```

**Comment by GammaC0de** [comment]
What is the output of:
```
#!/bin/bash

sh /opt/etc/pyload/scripts/package_finished/SCRIPTS/Script.sh >>/opt/etc/pyload/Logs/ScriptLog.txt 2>&1

marks=( '/' '-' '\' '|' )
i=0
tail -f /opt/etc/pyload/Logs/ScriptLog.txt | while read LOGLINE
do
    printf "${LOGLINE}"
    printf "\rScript is running ... ${marks[i++ % ${#marks[@]}]}"
    sleep 0.1
    [[ "${LOGLINE}" == *"Completed!"* ]] && (pkill -P $$ tail; printf "\rScript is running, please wait ... Done.\n";)
done
```

**Comment by Ryan747800B** [comment]
Unfortunately the same thing; however testing this script I noticed that it doesn't works as I thought. I explain what it does:

A script called `ExternalScript.sh` runs when `package_finished`; this script calls
```
sh /opt/etc/pyload/scripts/package_finished/SCRIPTS/Script1A.sh
sh /opt/etc/pyload/scripts/package_finished/SCRIPTS/Script2.sh
```
`Script1A` is the script posted above, that runs `Script1B` and wait for complete file extraction (`All OK`) - I need to use a log to check if unrar is finished because of pyLoad doesn't wait for it I don't know why.
`Script1B` renames only files called ` .rar.avi|mp4|mkv|m4v` (the so called `fake-mp4`) and then unrars them (OpenLoad issue and whatever other future file extension issue, so I will not have future issues).
`Script2` renames then files called `avi|mp4|mkv|m4v` and moves them to two different folders depending on the tag I used.

The issue is that `Script1B` that runs before `Script2` works perfectly ONLY if there's a `fake-mp4` file because of instead pyLoad hangs not seeing `All OK` log line.
The only way to solve this issue is to invoke `Script1A` and `Script1B` only if there's a `fake-mp4` remembering that it's necessary that `Script2` runs after `Script1`.
I found workaround deleting the `Script1` idea and adding to `Script2` `Sleep 60`, so that if there's a `fake-mp4` pyLoad with for complete extraction and if there's not then it waits (but 60 plus seconds of download time is an acceptable compromise).

Do you have an idea how to solve the issue (it's not only related to `fake-mp4` files because of a script that runs only with some files could always be useful in the future).

<details>
 <summary>Script1B</summary>

```
#!/bin/bash

fromdir="/DataVolume/shares/Public/Downloads/"
todir="/DataVolume/shares/Public/Downloads/"

rename_files() {
    title="${1##*${2} - }"
    exttitle="${2}"
    iters=0
    numfiles=$(ls -l "$1/"*.* | wc -l)
    for filename in "$1/"*.*; do
      new_path="${todir}${exttitle} - ${title}/${title}.${filename##*.rar.}"
      iters=_$(( ++i ))
      # extract $path without dot + extension
      new_path_basename=${new_path%*.*};
      # Extract extension from $path
      ext=${new_path##*.};
      if [ "$numfiles" -eq 1 ]; then
          iters=""
      fi
      case "${filename##*.rar.}" in avi|mp4|mkv|m4v)
        echo "moving $filename -> ${new_path_basename}${iters}.rar"
        # Add ${iters} before extension
        mv "${filename}" "${new_path_basename}${iters}.rar"
        unrar e "${new_path_basename}${iters}.rar" "${todir}${exttitle} - ${title}"
      ;;
      esac
    done
}

rename_category() {
  for path in "${fromdir}${1}"*; do
    rename_files "$path" "$1"
  done
}

rename_category MOV
rename_category TV

sleep 60
```

</details>

An example of what it does `Script1B`

<details>
 <summary>Script1B example</summary>

Given a pyLoad package called `MOV - NAMEIUSED`

```
FileABC.part1.rar.mp4|avi|mkv|m4v
FileABC.part2.rar.mp4|avi|mkv|m4v
```

```
FileABC.part1.rar
FileABC.part2.rar
```

`FileABC.rar`

`fileextracted.mp4|avi|mkv|m4v`

And then `Script2`

```
fileextracted.mp4|avi|mkv|m4v
or
fileasdownloaded.mp4|avi|mkv|m4v
```

`NAMEIUSED.mp4|avi|mkv|m4v` to `MOV`

</details>

**Comment by GammaC0de** [comment]
>pyLoad doesn't wait for it I don't know why

"Execute script concurrently" config option?

>EDIT: do you know if is possible to test all this things with VirtualBox or similar softwares and the rootfs.img firmware backupped instead of using the NAS directly?

Just use VirtualBox with x86 linux...

**Comment by Ryan747800B** [comment]
> "Execute script concurrently" config option?

Where's located this option?

> Just use VirtualBox with x86 linux...

Yes but it's not the same distro as My Book Live; maybe something changes (I'm not sure).

**Comment by GammaC0de** [comment]
> Where's located this option?

Config -> Plugins -> ExternalScripts

> maybe something changes

There is a chance but I think a low one and also you don't have another alternative

**Comment by Ryan747800B** [comment]
It's default `False` so I think that if I switch it to `True` (I can't test it now) pyLoad runs `Script1` and `Script2` at the same time but if `Script2` runs at the same time of `Script1`- that requires a certain amount of time-, then `Script2` can't move the extracted file - because of it runs quickly-, right?

**Comment by GammaC0de** [comment]
Right

**Comment by Ryan747800B** [comment]
Uhm and so the only way to move extracted `fake-mp4` files is to execute `Script2` again with a `post-package_finished`  pyLoad event such as `package_extracted`? :confused:

**Comment by GammaC0de** [comment]
I just noticed, are you suffering from the same problem as in #2735 but with Alldebrid?

**Comment by Ryan747800B** [comment]
Well I noticed it with Real-Debrid but I think it's a MultiAccount issue and not only Real-Debrid one; however I think that it can be very useful a script that detect for all downloads from whatever source the real extension.

**Comment by GammaC0de** [comment]
But this issue is only with Openload (with AllDebrid or realDebrid), right?

**Comment by Ryan747800B** [comment]
I tested only with video files but yes it seems this is the only hoster with that issue. In fact jDownloader doesn't have issue with the same files. Maybe an useful test can be to download the same file with an OpenLoad account but I don't know anyone with a premium acc.

**Comment by GammaC0de** [comment]
If you would like, you can send me your account so I can try to fix that

**Comment by Ryan747800B** [comment]
I would but as I said this account it isn't only mine and it's highly restricted. But I know that with AllDebrid and RealDebrid there's the possibility to do a trial account (maybe using a free VPN so the IP it's not logged and recorded).
PS: I found a site that shares daily a .cfg file for jDownloader with a lot of premium acc.; maybe it's possible to use this with pyLoad. Here's the todoy link http:// urle.co /8NqQUkr and here's the website (use a translator) https:// jd0wnlader2premiums .bl0gsp0t.it (change 0 with o)

**Comment by GammaC0de** [comment]
Well, closing.
