### ISSUE TITLE
Uloz.to error

### ISSUE THREAD

**Issue by mrkalo** [pyload/pyload#2782]
Hello,

can somebody check this log? There is lots of errors  - No module named json. UlozTo not working anymore. It was OK about a week ago, I didn't make any changes in settings or anything. I have pyload version 0.4.9 on NSA325 v2.

Thank you

Martin

07.03.2017 19:18:36	INFO	restarting pyLoad
594	07.03.2017 19:18:36	INFO	shutting down...
595	07.03.2017 19:18:37	INFO	Starting pyLoad 0.4.9
596	07.03.2017 19:18:37	INFO	Using home directory: /i-data/939de5dc/admin/zy-pkgs/pyLoad/etc/pyload
597	07.03.2017 19:18:43	ERROR	Error importing ExternalScripts: No module named json
598	07.03.2017 19:18:43	ERROR	Error importing XFileSharing: No module named json
599	07.03.2017 19:18:43	ERROR	Error importing UpdateManager: No module named json
600	07.03.2017 19:18:43	ERROR	Error importing MergeFiles: No module named json
601	07.03.2017 19:18:43	ERROR	Error importing UnSkipOnFail: No module named json
602	07.03.2017 19:18:43	ERROR	Error importing LinkdecrypterCom: No module named json
603	07.03.2017 19:18:43	WARNING	Failed activating LinkdecrypterCom
604	07.03.2017 19:18:43	ERROR	Error importing EventMapper: No module named json
605	07.03.2017 19:18:43	ERROR	Error importing ClickNLoad: No module named json
606	07.03.2017 19:18:43	ERROR	Error importing ExtractArchive: No module named json
607	07.03.2017 19:18:43	ERROR	Error importing UserAgentSwitcher: No module named json
608	07.03.2017 19:18:43	INFO	Activated plugins: ClickAndLoad, XFileSharingPro
609	07.03.2017 19:18:43	INFO	Deactivate plugins: AlldebridCom, AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, ExpertDecoders, FastixRu, FreeWayMe, HotFolder, IRC, IRCInterface, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LinksnappyCom, LogMarker, MegaDebridEu, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumTo, PremiumizeMe, PushBullet, PushOver, PutdriveCom, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartFailed, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, SmoozedCom, TransmissionRPC, UnrestrictLi, WindowsPhoneNotify, XMPP, XMPPInterface, ZeveraCom
610	07.03.2017 19:18:43	INFO	Downloadtime: True
611	07.03.2017 19:18:43	INFO	Starting ThriftBackend: 0.0.0.0:7227
612	07.03.2017 19:18:44	INFO	Starting threaded webserver: 0.0.0.0:7272
613	07.03.2017 19:18:43	INFO	Free space: 3.16 TiB
614	07.03.2017 19:18:44	INFO	Activating Accounts...
615	07.03.2017 19:18:44	INFO	Activating Plugins...
616	07.03.2017 19:18:44	INFO	ClickAndLoad: Proxy listening on :9666
617	07.03.2017 19:18:44	INFO	XFileSharingPro: Handling any hoster I can!
618	07.03.2017 19:18:44	INFO	XFileSharingPro: Handling any crypter I can!
619	07.03.2017 19:18:44	INFO	pyLoad is up and running
620	07.03.2017 19:18:46	INFO	LinkdecrypterCom: Reloading supported crypter list
621	07.03.2017 19:18:47	INFO	LinkdecrypterCom: Crypters not overwritten: crypt-it.com, dl-protect.com, embedupload.com, freetexthost.com, go4up.com, goo.gl, linkcrypt.ws, linksave.in, lix.in, lof.cc, mirrorcreator.com, multiload.cz, multiup.org, multiupload.com, ncrypt.in, netfolder.in, pastebin.com, relink.us, rs-layer.com, safelinking.net, secured.in, sh.st, share-links.biz, stealth.to, tinyurl.com, tny.cz
622	07.03.2017 19:20:19	ERROR	Error importing UlozTo: No module named json
623	07.03.2017 19:20:19	CRITICAL	'NoneType' object has no attribute 'UlozTo'

**Comment by vuolter** [comment]
Same as https://github.com/pyload/pyload/issues/2774
