### ISSUE TITLE
pyload time (in debug log) always is one hour behind

### ISSUE THREAD

**Issue by Lalarian** [pyload/pyload#2783]
Hello!

This is a problem, I have noticed long time ago, already. The time in pyload's debug log always is one hour behind current time on the router that pyload is running on. It was same on multiple installations on different devices.

**Comment by Lalarian** [comment]
No one reading this? :(

**Comment by vuolter** [comment]
pyLoad just call the python [logging module](https://docs.python.org/2/library/logging.html), so the issue can not be pyLoad itself. :s

**Comment by Lalarian** [comment]
Hello!

I have tried the following python script, I have found online, on my router:
`#!/usr/bin/env python
import sys
print sys.version_info
import commands
print "System time: %s" % commands.getoutput("date --rfc-3339=seconds")

import logging
import datetime
logging.basicConfig(level=logging.DEBUG, stream=sys.stdout, 
                        format="%(asctime)s:" + logging.BASIC_FORMAT,
                         datefmt="%Y-%m-%dT%H:%M:%S%z")

logger = logging.getLogger()
logger.info("Something happened")`

And it's giving the right time:

> sys.version_info(major=2, minor=7, micro=3, releaselevel='final', serial=0)
System time: 2017-03-16 04:33:14+01:00
2017-03-16T04:33:14+0000:INFO:root:Something happened

Shoud'nt this also be affected?

**Comment by Velociraptor85** [comment]
it could have something to do with 
* https://docs.python.org/2/library/time.html#time.strftime
* https://docs.python.org/2/library/logging.html#logging.Formatter.format
* or https://docs.python.org/2/library/logging.html#logging.Formatter.formatTime
but its probably line https://github.com/pyload/pyload/blob/stable/pyLoadCore.py#L503 which needs to be corrected

**Comment by Lalarian** [comment]
I still get emails about the status being closed and reopened, but sorry: I got no machine using Pyload anymore at the moment. So I cannot give feedback on this.

**Comment by GammaC0de** [comment]
> I still get emails about the status being closed and reopened, but sorry: I got no machine using Pyload anymore at the moment.

Sorry to hear that..

> So I cannot give feedback on this.

Closing then,
Feel free fto create a new issue if you ever use pyload again,
We try to do better ;)
