### ISSUE TITLE
cannot run setup.py on alpine Linux

### ISSUE THREAD

**Issue by digrouz** [pyload/pyload#2785]
Hi,

It sounds like pyload has changed a lot during the last days.

I'm trying a new installation in an alpine Linux container. With some trial an error I was able to fix a lot of stuff but i end up in something I cannot fix.

So when I re-run setup.py install I get the following output: 
[setup.txt](https://github.com/pyload/pyload/files/828402/setup.txt)

If I go myself into /opt/pyload/pyload/webui/app/ and run npm install, I get the following output:
[npm.txt](https://github.com/pyload/pyload/files/828412/npm.txt)
Which seems fine to me (I'm not nodejs guru)

If I try to run the pyload command, I get the following error:
[pyload.txt](https://github.com/pyload/pyload/files/828417/pyload.txt)

How can I fix this ?

**Comment by Slevin7** [comment]
i have the same problem, maybe it is not ready yet

**Comment by Velociraptor85** [comment]
As far as I know this will be for the 1.0.0 setup but I might be wrong here... maybe @vuolter will tell you a bit more :)

**Comment by Velociraptor85** [comment]
as far as I know this is on the master branch which will be the new 1.0, 0.5 or whatever ... the new stable but the development is not yet finished so If you want to have a working pyload you should git clone the stable branch or zip download this should work I think GammaC0de has in some ticket written an little how to.

**Comment by GammaC0de** [comment]
master branch is not ready yet.
