### ISSUE TITLE
How to install on ubuntu (docker image)

### ISSUE THREAD

**Issue by buehler** [pyload/pyload#2786]
Hey there

I'm trying to get the newest master branch up and running and I'm kinda confused by now. I installed like a billion different dependencies, and still there are so many errors.

Could you provide an installation / setup manual for the master branch?

What I did so far (in the ubuntu docker image):

```bash
apt-get update
apt-get install -y python python-dev python-dbus gcc wget curl libcurl4-openssl-dev git libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev libev-dev build-essential pkg-config libdbus-1-dev libdbus-glib-1-dev 

wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
rm get-pip.py

git clone https://github.com/pyload/pyload.git /opt/pyload

cd /opt/pyload

chmod +x setup.py pyLoad.py

python setup.py build
python setup.py install

pip install argparse Beaker bottle daemonize future psutil pycurl requests tld validators beautifulsoup bitmath bjoern colorama colorlog goslate IPy Js2Py Pillow pycrypto pyOpenSSL rarfile Send2Trash setproctitle watchdog dbus-python configparser autoupgrade-ng
```

and right now if I start `pyload` the following error appears: 
```
Traceback (most recent call last):
  File "pyLoad.py", line 23, in <module>
    import pyload.core
  File "/usr/local/lib/python2.7/dist-packages/pyload/core/__init__.py", line 38, in <module>
    from . import api
  File "/usr/local/lib/python2.7/dist-packages/pyload/core/api/__init__.py", line 6, in <module>
    from .init import Api
  File "/usr/local/lib/python2.7/dist-packages/pyload/core/api/init.py", line 12, in <module>
    from ..datatype.init import DownloadState, DownloadStatus, Permission
  File "/usr/local/lib/python2.7/dist-packages/pyload/core/datatype/__init__.py", line 6, in <module>
    from .init import *
  File "/usr/local/lib/python2.7/dist-packages/pyload/core/datatype/init.py", line 7, in <module>
    from enum import IntFlag
ImportError: cannot import name IntFlag
```

Thanks for the help. Btw I'm currently implementing the web ui for pyload (https://github.com/pyload/pyload/issues/2710), that's why I try to run the newest master (for json api features and stuff)

**Comment by GammaC0de** [comment]
master branch is not ready yet, use stable branch or read #2000 for more details.
for docker image see https://github.com/obi12341/docker-pyload

**Comment by djessich** [comment]
You could also use thee [Pyload Chef](https://github.com/gridtec/cookbook-pyload) cookbook, which  works on Docker (I'm testing the cookbook on travis using Docker). I've appended in the FAQ section a short guide on how to install Pyload with the Cookbook without using the Chef Server. This means using the Chef Cookbook like an install script.
