### ISSUE TITLE
account add, any ideas? I'm a bit new to this.

### ISSUE THREAD

**Issue by midnightblue1122** [pyload/pyload#2787]
OS=Centos 7 

any ideas? trying to use rapidgator premium, and I get this when inputting the account information.

[root@starship-enterprize pyload-0.4.9]# python pyLoadCore.py -d                09.03.2017 20:33:26 INFO      Starting pyLoad 0.4.9
09.03.2017 20:33:26 INFO      Using home directory: /apps/data/.pyload
09.03.2017 20:33:26 DEBUG     Deleting old pidfile pyload.pid
09.03.2017 20:33:26 DEBUG     Remote activated: True
09.03.2017 20:33:27 DEBUG     created index of plugins
09.03.2017 20:33:27 INFO      ExtractArchive: Activated UnRar UnZip
09.03.2017 20:33:27 INFO      Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
09.03.2017 20:33:27 INFO      Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
09.03.2017 20:33:27 INFO      Downloadtime: True
09.03.2017 20:33:27 INFO      Starting ThriftBackend: 0.0.0.0:7227
09.03.2017 20:33:27 INFO      Starting threaded webserver: 0.0.0.0:9112
09.03.2017 20:33:27 INFO      Free space: 2.60 TiB
09.03.2017 20:33:27 INFO      Activating Accounts...
09.03.2017 20:33:27 INFO      Activating Plugins...
09.03.2017 20:33:27 INFO      pyLoad is up and running
09.03.2017 20:33:29 INFO      ***  New pyLoad Version 
<html data-adblockkey="MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKX74ixpzVyXbJprcLfbH4psP4+L2entqri0lzh6pkAaXLPIcclv6DQBeJJjGFWrBIF6QMyFwXT5CCRyjS2penECAwEAAQ==_dnaOxb5vnYWbDVKAaTh0o9Q651XNToQ5Rs0Y7jWOAl1DBKCLILzIC68mMb+zo7HtRK93l6MiTpnPLAYNjQBVZw=="><head>
                                  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
                                  <meta name="viewport" content="width=device-width"><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"><script type="text/javascript">
        
</script><script type='text/javascript'>try{document.cookie = 'fjccheck=1';}catch(exception){}</script></head><frameset rows="100%,*" frameborder="no" border="0" framespacing="0">
        <frame src="http://ww1.pyload.org/?fp=r8DhElIAteZqu%2FnuXAkxAjftxeY0VL9SSLzi571oLsNWJsf3tULuHTyYlHvZs2gAxeOaOSdX9ag0CH%2B4zzwuWQ%3D%3D&prvtof=kJxwPVniTSYpUs4JTs49eWQwXN7U%2B60IxEDofDVq5T1fVNR3F5X6tT8GNyqyMA71%2BbV2z3cZFa6%2FR8CatvVfaQ%3D%3D&poru=KF4cLLpTb3d%2Bg5rK9xhqU%2FkT20L5V%2FQGyqPgnIMiOFnr79FHZrJmPzN2fpLQIXFM&">
</frameset>
<noframes>
        <body bgcolor="#ffffff" text="#000000">
        <a href="http://ww1.pyload.org/?fp=r8DhElIAteZqu%2FnuXAkxAjftxeY0VL9SSLzi571oLsNWJsf3tULuHTyYlHvZs2gAxeOaOSdX9ag0CH%2B4zzwuWQ%3D%3D&prvtof=o8i7Q9Pr27OKgWCk1NxiEAmYq3VOicVKvbxAeXIQ7vJ8NAuvlojTkBqsfN8RQ0hs7VH3PwhGrzcl0u%2F2fwXxgA%3D%3D&poru=0vTbmfVXUy9Y7XepOpM%2FX7pbt50rGx4WX8A1uLW6i8f0SmkWm6ixv3Dd8asRruCl&">Click here to proceed</a>.
        </body>
</noframes></html> available  ***
09.03.2017 20:33:29 INFO      ***  Get it here: http://pyload.org/download  ***
09.03.2017 20:33:29 INFO      No plugin updates available
09.03.2017 20:33:58 ERROR     Error importing RapidgatorNet: No module named Account
Traceback (most recent call last):
  File "/apps/pyload-0.4.9/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/apps/pyload-0.4.9/module/plugins/accounts/RapidgatorNet.py", line 5, in <module>
    from ..internal.Account import Account
ImportError: No module named Account
Traceback (most recent call last):
  File "/apps/pyload-0.4.9/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/apps/pyload-0.4.9/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/apps/pyload-0.4.9/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/apps/pyload-0.4.9/module/web/json_app.py", line 276, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/apps/pyload-0.4.9/module/Api.py", line 894, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/apps/pyload-0.4.9/module/utils.py", line 165, in new
    return func(*args)
  File "/apps/pyload-0.4.9/module/plugins/AccountManager.py", line 148, in updateAccount
    p = self.getAccountPlugin(plugin)
  File "/apps/pyload-0.4.9/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable
An error occured while processing the request.
Traceback (most recent call last):
  File "/apps/pyload-0.4.9/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/apps/pyload-0.4.9/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/apps/pyload-0.4.9/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/apps/pyload-0.4.9/module/web/json_app.py", line 276, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/apps/pyload-0.4.9/module/Api.py", line 894, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/apps/pyload-0.4.9/module/utils.py", line 165, in new
    return func(*args)
  File "/apps/pyload-0.4.9/module/plugins/AccountManager.py", line 148, in updateAccount
    p = self.getAccountPlugin(plugin)
  File "/apps/pyload-0.4.9/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

**Comment by GammaC0de** [comment]
@midnightblue1122 Please read #2000 on how to install pyLoad

**Comment by djessich** [comment]
You may want to install Pyload using the [Pyload Chef](https://github.com/gridtec/cookbook-pyload) cookbook. I've appended in the FAQ section a short guide on how to install Pyload with the Cookbook without using the Chef Server. This means using the Chef Cookbook like an install script.

The Cookbook just checks out Pyload from the official Git Repository (stable) branch. It also places an Init System Script regarding your platform (f.e. SystemD) to automatically start Pyload during system startup.

**Comment by GammaC0de** [comment]
No response, closing.
