### ISSUE TITLE
'unicodeescape' codec can't decode bytes

### ISSUE THREAD

**Issue by St3ini** [pyload/pyload#2791]
I've installed pyLoad fresh on my NAS QNAP TS-212 (QTS 4.2.3).
After installing python (2.7.13) and all required packages I updated manually the pyLoad files with the latest on github (stable of course).

pyLoad is starting but when I add some DLC to download, I get follwing messege:
> 'unicodeescape' codec can't decode bytes in position 22-23: truncated \UXXXXXXXX escape

Whats going wrong here? I need help  ... :( 

Python: 2.7.13 (default, Feb 11 2017, 21:11:51) [GCC 6.3.0]
OS: posix linux2 Linux NAS 3.4.6 #1 Mon Feb 13 11:10:08 CST 2017 armv5tel
pyLoad version: 0.4.9 (stable)

[debug_DLC_13-03-2017_21-10-10.txt](https://github.com/pyload/pyload/files/839497/debug_DLC_13-03-2017_21-10-10.txt)
[log.txt](https://github.com/pyload/pyload/files/839500/log.txt)

**Comment by GammaC0de** [comment]
Post / attach here the DLC or the URL to the DLC or send to nitzo2001 at yahoo dot com.

**Comment by St3ini** [comment]
Of Course .. I'm sorry!
I've tried with a lot of DLC-container-files - all the same.

Here is one example: [TEST.zip](https://github.com/pyload/pyload/files/839616/TEST.zip)

**Comment by GammaC0de** [comment]
I tried the DLCs you emailed me and the work fine.
The attached DLC (TEST.zip) is not a valid dlc

**Comment by St3ini** [comment]
Yes, that happend to every DLC file...

The attached DLC was a Test-File when I creat my own DLC Container.

**Comment by GammaC0de** [comment]
Start pyLoad from the console with `python2.7 pyLoadCore.py -d`, add a DLC file (from a site, not self created) and then post the log from the console.

**Comment by St3ini** [comment]
The same result....

[debug_DLC_14-03-2017_10-31-29.zip](https://github.com/pyload/pyload/files/840780/debug_DLC_14-03-2017_10-31-29.zip)
[Console-log.txt](https://github.com/pyload/pyload/files/840781/Console-log.txt)

**Comment by GammaC0de** [comment]
How exactly do you add the DLC?
via file upload ar do you give a URL to the DLC?

**Comment by St3ini** [comment]
1) open the pyload webinterface 
2) click on "add"
3) choosing the file with fileuploader
4) pressing on "Add Package"

**Comment by St3ini** [comment]
Note:
When I install the old package (from 2011) on my QNAP, pyload decrypt the DLC but can't download because the outdated plugins (of course).

After updating the plugins (and setting the chmod rights) the same problem occure.

**Comment by GammaC0de** [comment]
Well, I found the problem. I now have to think how to solve it.

Basically, now pyload will fail if you add a file with patch that contains `\U` (e.g `C:\Users`) in it.
Other path names works.

**Comment by St3ini** [comment]
You're right!

I tested to add the DLC from a other place (X:\blabla.dlc) and it works now...
