### ISSUE TITLE
[uploaded.to] Treating premium downloads as free (asking for captcha)

### ISSUE THREAD

**Issue by rfeliciano129** [pyload/pyload#2792]
Started a few days ago. Seems that all uploaded.to links are being treated as free downloads. From the logs it looks like its not able to find the direct download link:

13.03.2017 20:40:53 INFO      HOSTER UploadedTo[1516]: Looking for direct download link...
13.03.2017 20:40:53 INFO      HOSTER UploadedTo[1516]: Direct download link not found
13.03.2017 20:40:53 INFO      HOSTER UploadedTo[1516]: Checking for link errors...
13.03.2017 20:40:53 INFO      HOSTER UploadedTo[1516]: No errors found
13.03.2017 20:40:53 INFO      HOSTER UploadedTo[1516]: Processing as free download...

**Comment by GammaC0de** [comment]
Account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by szczepan79** [comment]
i have problem with uploaded

INFO	ACCOUNT UploadedTo: Grabbing account info for user `156*******`...
396	21.03.2017 13:57:00	INFO	HOSTER UploadedTo[1313]: Filesize: 2448500 KiB | Traffic left for user `156*******`: 19702743 KiB
397	21.03.2017 13:57:00	INFO	HOSTER UploadedTo[1313]: Processing as premium download...
398	21.03.2017 13:57:00	INFO	HOSTER UploadedTo[1313]: Downloading file...
399	21.03.2017 13:57:00	WARNING	Download failed: Th3.Y0ung.P0p3.S01E09.MULTi.720p.rar | 'ascii' codec can't decode byte 0xc5 in position 35: ordinal not in range(128)

**Comment by GammaC0de** [comment]
@rfeliciano129 No response, closing.

@szczepan79 There is a bug when the file name contains non ASCII characters, hopefully will be fixed in the next pyLoad release.

**Comment by rfeliciano129** [comment]
Sorry was out of the country. Bit apprehensive about giving out account info. Would it be possible for me to run a script you create to get whatever output you need?

**Comment by GammaC0de** [comment]
@rfeliciano129 First of all, a DEBUG log will be helpful: stop pyLoad and then run it with `python pyLoadCore.py -d` then retry the download and post the log here.

Secondly, if your problem is that you get "'ascii' codec can't decode byte 0xc5 in position 35: ordinal not in range(128)" error, this is a known bug that happens when the file name contains non ASCII characters (e.g.  "&agrave;",  "&egrave;", "&ucirc;" etc.)

As for giving out account info, you can change to a temporary password before giving it.

**Comment by rfeliciano129** [comment]
Well apparently I'm just dumb. Somehow the share I use as the destination got unmounted. Didn't notice and pyload was defaulting to free when it couldn't write to the proper directory. 

Seems to be working fine now.
