### ISSUE TITLE
@vuolter Please set default branch to "stable"

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2794]
@vuolter Somehow the default branch was changed to "master" instead of "stable"

**Comment by BKPepe** [comment]
I told him it on 7th March on Gitter. :/

**Comment by vuolter** [comment]
I changed the main branch when I activated the cla assitant. For now I like to keep the master as main branch as should be in default, but if more reports like that should come I'll revert it for sure.

**Comment by GammaC0de** [comment]
👍 Just a side note: committing with comment like "fix \#1233445" will note close the issue...

**Comment by sebix** [comment]
I'd support the request to make the stable branch the default one. However I think this can wait until the next stable version is released.

**Comment by Velociraptor85** [comment]
👍 I would also go with the request that as long as the -nextgen branch does not work the main should be the working stable branch so that useres are not confused

**Comment by vuolter** [comment]
Done.
