### ISSUE TITLE
Start error on Ubuntu

### ISSUE THREAD

**Issue by thomas126** [pyload/pyload#2796]
Hi guys,
sorry i am pretty new to all of this. I would like to set up pyload to Access via webinterface. I starten by following a Guide on how to install pyload on ubuntu Server. Installed the following dependencies:
apt-get install python python-crypto python-pycurl python-imaging python-beaker python-qt4 tesseract-ocr tesseract-ocr-eng gocr unrar

Then ran the git command in /opt:
git clone https://github.com/pyload/pyload.git

Then i checked the pyload Folder. I was not able to locate the pyloadcore.py file so i ran
pyload.py and testwise also Setup.py but both gave me errors: importerror: no modules named builtins.

I already tried to install via pip as suggested. Francly this command "pip install --upgrade pyload-ng" results in an error. Package Not found.

Any Ideas what i am doing wrong. Also sorry if this is Not the right Place for questions. Havent found a forum for pyload.

**Comment by GammaC0de** [comment]
@thomas126 You should clone the "stable" branch...

**Comment by thomas126** [comment]
Im sorry my fault. You are right. I'll give it a shot as soon as I am home. Thank you.

**Comment by GammaC0de** [comment]
Closing.
