### ISSUE TITLE
1fichier 

### ISSUE THREAD

**Issue by Jluc33** [pyload/pyload#2797]
Thanks for the reactivity of the modification, you are great.

I have a new worry: 1file downloads do not start any more and the reason given is: "Parse error: No file downloaded | Plugin may be out of date"

Thank you for your service

Very cordially

**Comment by GammaC0de** [comment]
Sample URL please.

**Comment by Jluc33** [comment]
Thanks,

Example URL: https://1fichier.com/?uejp7lmuz1

**Comment by GammaC0de** [comment]
👍
