### ISSUE TITLE
Click N Load add only one Hoster

### ISSUE THREAD

**Issue by donaufisch66** [pyload/pyload#2799]
Hello,
Is there any possibility to add just one Hoster when clicking "ClickNLoad"? Sometimes these files contain for example shareOnlineBiz and Upload.com links.
I would like to filter for "ShareOnlineBiz" only! I have to delete all other files manually. Is there any way to do that automatically?

**Comment by Mister-XY** [comment]
That's a good idea.

**Comment by donaufisch66** [comment]
There is already a plugin therefore! "Linkfilter", just add the Hosters you don´t want and activate.
