### ISSUE TITLE
Unicode hyphen crashes ascii codec

### ISSUE THREAD

**Issue by JustinS-B** [pyload/pyload#2804]
There is a special kind of hyphen which just causes pyLoad to blow chunks - if the file name includes it. I think that it is the one the Microsoft word auto-replaces a "normal" minus sign with when two words are hyphenated. This is it: "–" (compare it to a "normal" minus sign "-"). I normally use Click n Load, & have done for several years. If the file name includes the malignant hyphen, it errors and crashes instantly. If you use the "add" button on the WebInterface, & paste the file name (that includes this hyphen) into the "Package Name" field, it will "add" it for download, but as soon as it starts to process the download, it crashes. I have added these debugs to the bottom of the post.

I'm sorry to say that this bug has existed for some years, it has just taken me a while to finally track down the cause to a unicode hyphen, as I didn't want to report a sporadic bug with an unknown cause that I couldn't reliably replicate. However, now that I can replicate this 100%, if you need a working example, pm me and I can provide a username, password, & link that you can test.

Here is the debug log of what happens. Note the file name in the logs "**Package \xe2\x80\x93 April 2017**" which originally was "**Package – April 2017**" on the link.

**This is the Click n Load generated error**
```
16.03.2017 21:28:17 INFO      pyLoad is up and running
16.03.2017 21:28:17 INFO      ADDON UpdateManager: All plugins are up to date!
16.03.2017 21:28:23 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
16.03.2017 21:28:52 DEBUG     ADDON ClickNLoad: Connection from 192.168.1.2:54916
Traceback (most recent call last):
  File "/opt/pyload/module/database/DatabaseBackend.py", line 96, in processJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/opt/pyload/module/database/FileDatabase.py", line 630, in addPackage
    self.c.execute('INSERT INTO packages(name, folder, queue, packageorder) VALUES(?,?,?,?)', (name, folder, queue, order))
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
Database Error @ addPackage ('Package \xe2\x80\x93 April 2017', 'Package \xe2\x80\x93 April 2017', 1) {} You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/cnl_app.py", line 22, in _view
    return function(*args, **kwargs)
  File "/opt/pyload/module/web/cnl_app.py", line 132, in flashgot
    PYLOAD.addPackage(package, urls, autostart)
  File "/opt/pyload/module/Api.py", line 326, in addPackage
    pid = self.core.files.addPackage(name, folder, dest)
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/database/FileDatabase.py", line 68, in new
    return func(*args)
  File "/opt/pyload/module/database/FileDatabase.py", line 141, in addPackage
    e = InsertEvent("pack", lastID, p.order, "collector" if not queue else "queue")
AttributeError: 'NoneType' object has no attribute 'order'
An error occured while processing the request.
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/cnl_app.py", line 22, in _view
    return function(*args, **kwargs)
  File "/opt/pyload/module/web/cnl_app.py", line 132, in flashgot
    PYLOAD.addPackage(package, urls, autostart)
  File "/opt/pyload/module/Api.py", line 326, in addPackage
    pid = self.core.files.addPackage(name, folder, dest)
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/database/FileDatabase.py", line 68, in new
    return func(*args)
  File "/opt/pyload/module/database/FileDatabase.py", line 141, in addPackage
    e = InsertEvent("pack", lastID, p.order, "collector" if not queue else "queue")
AttributeError: 'NoneType' object has no attribute 'order'
```

**This is the file being added using the "add" button - which works fine**
`16.03.2017 22:03:47 INFO      Added package Package – April 2017 containing 1 links`

**and this is the debug of the crash when it starts to process the "added" file, with the unicode hyphen**
```
17.03.2017 00:34:12 WARNING   Download failed: Package.April2017.rar | 'ascii' codec can't decode byte 0xe2 in position 18: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/justin/.pyload/userplugins/internal/Base.py", line 289, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/justin/.pyload/userplugins/internal/Hoster.py", line 112, in _process
    self.process(self.pyfile)
  File "/home/justin/.pyload/userplugins/internal/SimpleHoster.py", line 296, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/home/justin/.pyload/userplugins/internal/Hoster.py", line 299, in download
    disposition, resume, chunks)
  File "/home/justin/.pyload/userplugins/internal/Hoster.py", line 224, in _download
    self.pyfile.setProgress, disposition)
  File "/opt/pyload/module/network/Browser.py", line 87, in httpDownload
    self.cj if cookies else None, self.bucket, self.options, progressNotify, disposition)
  File "/opt/pyload/module/network/HTTPDownload.py", line 64, in __init__
    self.info = ChunkInfo(filename)
  File "/opt/pyload/module/network/HTTPChunk.py", line 35, in __init__
    self.name = unicode(name)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 18: ordinal not in range(128)
```
Apologies, as I originally posted this in the wrong place.

**Comment by GammaC0de** [comment]
What is the URL for this link?

**Comment by JustinS-B** [comment]
This is a page with an example of the hyphen which gives all of problems outlined above:
http://www.allyoulike.com/131906/mens-fitness-usa-april-2017/

**Comment by GammaC0de** [comment]
This link does not contain hyphen

**Comment by JustinS-B** [comment]
I'm sorry that I didn't make myself clear. 

The Click N Load system automatically uses the HTML page name as the name for the directory that it auto-creates in the download directory, so when you click'n'load on a download link on a page, it lifts the page name & uses it. The "Add" button on the WebInterface uses its "Name" field to likewise auto-create a folder for the package in the download area.

If you go to the page that I linked to above, the page name has the offending unicode hyphen in it. If you use Click N Load to click on the only download link available on that page, it will error, as detailed above. Yes, the download link doesn't actually contain the unicode hyphen, only the page name does - but that's enough to cause it to error. If you copy and paste the name of the download into the "Add" dialogue box "Name" field (ie "Men’s Fitness USA – April 2017" - which contains the hyphen) along with the download link (which doesn't), it will also error as detailed above.

On thinking about it, pyLoad appears to error when asked to auto-create a directory containing a unicode character, regardless of how you pass it the download link...

**Comment by JustinS-B** [comment]
To be honest, if you paste that unicode hyphen into any string in the "Name" field on the "Add" dialogue (ie "random–name"), & then paste in a download link of your choice, it will give you the same error. Once it has a unicode character in the name, all other details are inconsequential - it will just error... 

The Click N Load system is just another way of giving pyLoad the download link & package name, like the "add" button - the error comes when pyLoad then tries to process the package name that it has been given containing a unicode character.

**Comment by Cobraeti** [comment]
Hi,
I noticed the same behavior with a full-ASCII file name but using some extended-ASCII characters in the package name (I'am French, so "ç" or "é" are common ones :laughing:).

So I would say that (to avoid any hair lost, firestorms or stuff like that) the workaround for now is to use only the "classic" ASCII table.

Here is a small reminder of the available characters for those who, like me, where using UTF-8 for too long:
!["Classic ASCII table"](http://www.asciitable.com/index/asciifull.gif)

Hope this could help and avoid people giving away and move out from this amazing downloader :wink:

**Comment by h1ghju1ce** [comment]
ok thats ok for now, but it USED to work fine for years, then suddenly stopped working, thats the annoying part of it

**Comment by GammaC0de** [comment]
Everyone who has this issue have to edit `HTTPChunk.py` and change line 35 from:
```
        self.name = unicode(name)
```

to:
```
        self.name = unicode(name.decode('utf-8'))
```
