### ISSUE TITLE
python: can't open file 'pyLoadCore.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by riPlus** [pyload/pyload#2805]
Hi

I would like to install pyload on a raspberry pi. I followed the instruction on [https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi)]
When I try to start the configuration with `sudo -u pyload python pyLoadCore.py`
I get the error python: can't open file 'pyLoadCore.py': [Errno 2] No such file or directory

What am I doing wrong?

Thanks
Rico

**Comment by GammaC0de** [comment]
Use `find / -name pyLoadCore.py` to find where is pyLoadCore.py

**Comment by SvenLuebke** [comment]
I have the same issue, but I think the master repository already contains the alpha version of pyload-ng which is not working yet. Try to execute

git checkout tags/v0.4.9

in pyload directory.

**Comment by GammaC0de** [comment]
Oh, now I understand whats wrong.
I fixed the manual to use the "stable" branch.
```
cd /opt
sudo git clone -b stable https://github.com/pyload/pyload.git
cd pyload
sudo -u pyload python pyLoadCore.py
```

**Comment by riPlus** [comment]
Thank you
Now I could install it
