### ISSUE TITLE
Weird fallback to free user with uploaded.to

### ISSUE THREAD

**Issue by kvoit** [pyload/pyload#2807]
I just spend almost an hour resetting and cloning repositories and configs and copying them back and forth trying to figure out why one of my pyload instances loaded ul.to files fine, while the other fell back to free user, asked for a captcha and even then didn't work.
Turned out I accidentally messed up the permissions for the download folder so pyload couldn't write there. I really don't think this should result in a fallback to free user ...

**Comment by Slevin7** [comment]
is it possible that your forget #2000 ?

**Comment by GammaC0de** [comment]
@kvoit pyLoad will fallback to free user on every failure to download, that includes also failure to download because of file permissions.

**Comment by kvoit** [comment]
Well, given the new version coming up closing this isprobably ok. Else I would call this a bug :)
