### ISSUE TITLE
DebridlinkFr download failed

### ISSUE THREAD

**Issue by Johan46** [pyload/pyload#2810]
DebridlinkFR account is valid but all download failed with the same error (see log).
The links I tested are valid and downloads are ok with JDownloader or Debridlink website.

[log.txt](https://github.com/pyload/pyload/files/868708/log.txt)

**Comment by GammaC0de** [comment]
@Johan46 This worked fine for me:
The download started fine, I aborted and did not wait it to finish though.

Can you please stop pyLoad and the start it from the console with `python pyLoadCore.py -d`, retry the download and paste the log form the console here?

**Comment by Johan46** [comment]
The log for the 1Fichier link

[log.txt](https://github.com/pyload/pyload/files/870207/log.txt)

**Comment by GammaC0de** [comment]
@Johan46 can you edit `userplugins/hoster`DebridlinkFr.py` and add at the end the lines:
```
        else:
            self.log_debug("Download error", res)
```

e.g.:
```python
    def handle_premium(self, pyfile):
        res = self.api_request("/downloader/add", post=args(link=pyfile.url))

        if res['result'] == "OK":
            self.link = res['value']['downloadLink']
            pyfile.name = res['value'].get('filename', None) or pyfile.name
            self.resume_download = res['value'].get(
                'resume') or self.resume_download
            self.chunk_limit = res['value'].get('chunk') or self.chunk_limit
            
        else:
            self.log_debug("Download error", res)
```


and then retry with again with `python pyLoadCore.py -d` and post the log?

**Comment by Johan46** [comment]
[log.txt](https://github.com/pyload/pyload/files/870226/log.txt)

and 
```
Traceback (most recent call last):
  File "/home8/user/software/pyload/module/ThreadManager.py", line 276, in assignJob
    job.initPlugin()
  File "/home8/user/software/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/home8/user/software/pyload/module/PyFile.py", line 102, in initPlugin
    self.pluginclass = getattr(self.pluginmodule, self.m.core.pluginManager.getPluginName(self.pluginname))
AttributeError: 'NoneType' object has no attribute 'DebridlinkFr'
```

**Comment by GammaC0de** [comment]
@Johan46 You edited the file wrong: there must not be any tabs in the file, just spaces.
here the the [correct file](https://github.com/pyload/pyload/files/870347/DebridlinkFr.zip)  (zipped), please replace it with the one you have then retry again.

**Comment by GammaC0de** [comment]
Any news?

**Comment by GammaC0de** [comment]
No response, closing.
