### ISSUE TITLE
still problems with rockfile ...

### ISSUE THREAD

**Issue by maxking71** [pyload/pyload#2811]
still problems with rockfile ...

thanks

15 25.03.2017 07:21:51 DEBUG HOSTER RockfileEu[24]: LOAD URL http://rockfile.eu/nifhhdf8pose.html | redirect=True | cookies=[('rockfile.eu', 'lang', 'english')] | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False  
16 25.03.2017 07:21:52 DEBUG ADDON CloudFlareDdos: get_url(): got BadHeader exception 503  
17 25.03.2017 07:21:52 INFO ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page  
18 25.03.2017 07:21:52 DEBUG HOSTER RockfileEu[24]: WAIT set to timestamp 1490422918.029500 | Previous waitUntil: 0.000000  
19 25.03.2017 07:21:54 INFO HOSTER RockfileEu[24]: Waiting 3 seconds...  
20 25.03.2017 07:21:58 DEBUG HOSTER RockfileEu[24]: LOAD URL http://rockfile.eu/cdn-cgi/l/chk_jschl | redirect=True | cookies=True | get={'jschl_answer': '-176985', 'jschl_vc': 'f48bb947875f9c45fd8210b9744f4c1c', 'pass': '1490422915.969-Gryed5Qt8V'} | req=None | decode=True | multipart=False | post={} | ref=http://rockfile.eu/nifhhdf8pose.html | just_header=False  
21 25.03.2017 07:21:59 DEBUG HOSTER RockfileEu[24]: Link info: {'status': 2, 'hash': {}, 'name': 'Ibiza House Flight Hits.rar', 'url': u'http://rockfile.eu/nifhhdf8pose.html', 'pattern': {'N': u'Ibiza House Flight Hits.rar'}, 'size': 0}  
22 25.03.2017 07:21:59 DEBUG HOSTER RockfileEu[24]: Previous link info: {}  
23 25.03.2017 07:21:59 INFO HOSTER RockfileEu[24]: Link name: Ibiza House Flight Hits.rar  
24 25.03.2017 07:21:59 INFO HOSTER RockfileEu[24]: Link size: N/D  
25 25.03.2017 07:21:59 INFO HOSTER RockfileEu[24]: Link status: online  
26 25.03.2017 07:21:59 INFO HOSTER RockfileEu[24]: Processing url: http://rockfile.eu/nifhhdf8pose.html  
27 25.03.2017 07:21:59 INFO HOSTER RockfileEu[24]: Looking for direct download link...  
28 25.03.2017 07:21:59 DEBUG HOSTER RockfileEu[24]: LOAD URL http://rockfile.eu/nifhhdf8pose.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True  
29 25.03.2017 07:21:59 INFO HOSTER RockfileEu[24]: Direct download link not found  
30 25.03.2017 07:21:59 DEBUG ADDON CloudFlareDdos: Calling _preload() of  
31 25.03.2017 07:21:59 DEBUG HOSTER RockfileEu[24]: LOAD URL http://rockfile.eu/nifhhdf8pose.html | redirect=True | cookies=[('rockfile.eu', 'lang', 'english')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False  
32 25.03.2017 07:22:00 DEBUG ADDON CloudFlareDdos: _preload() returned successfully  
33 25.03.2017 07:22:00 INFO HOSTER RockfileEu[24]: Checking for link errors...  
34 25.03.2017 07:22:00 INFO HOSTER RockfileEu[24]: No errors found  
35 25.03.2017 07:22:00 INFO HOSTER RockfileEu[24]: Processing as free download...  
36 25.03.2017 07:22:00 DEBUG HOSTER RockfileEu[24]: LOAD URL http://rockfile.eu/nifhhdf8pose.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'usr_login': '', u'referer': u'http://rockfile.eu/nifhhdf8pose.html', u'fname': u'Ibiza House Flight Hits.rar', u'method_free': u'Regular Download', u'id': u'nifhhdf8pose', u'op': u'download1'} | ref=True | just_header=False  
37 25.03.2017 07:22:01 INFO HOSTER RockfileEu[24]: Checking for link errors...  
38 25.03.2017 07:22:01 INFO HOSTER RockfileEu[24]: No errors found  
39 25.03.2017 07:22:01 WARNING CAPTCHA RockfileEu[24]: ReCaptcha | Key pattern not found  
40 25.03.2017 07:22:01 DEBUG ADDON ExternalScripts: No script found under folder `download_processed`  
41 25.03.2017 07:22:01 DEBUG ADDON CloudFlareDdos: Unoverriding _preload() for  
42 25.03.2017 07:22:01 DEBUG ADDON ExternalScripts: No script found under folder `package_processed`  
43 25.03.2017 07:22:01 WARNING Download failed: Ibiza House Flight Hits.rar | Parse error: Captcha not found | Plugin may be out of date  
44 25.03.2017 07:22:01 INFO ADDON UnSkipOnFail: Looking for skipped duplicates of: Ibiza House Flight Hits.rar (pid:24)  
45 25.03.2017 07:22:01 INFO ADDON UnSkipOnFail: No duplicates found  
46 25.03.2017 07:22:01 DEBUG ADDON ExternalScripts: No script found under folder `download_failed`  
47 25.03.2017 07:22:01 DEBUG ADDON ExternalScripts: No script found under folder `all_downloads_processed`  
48 25.03.2017 07:22:01 DEBUG All downloads processed

**Comment by GammaC0de** [comment]
@maxking71 Rockfile.eu site was offline yesterday.
I tested the link above and it works fine.

**Comment by maxking71** [comment]
82 29.03.2017 10:27:11 DEBUG HOSTER RockfileEu[30]: LOAD URL http://rockfile.eu/1wiyqt4iobi1.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True  
83 29.03.2017 10:27:11 INFO HOSTER RockfileEu[30]: Direct download link not found  
84 29.03.2017 10:27:11 DEBUG ADDON CloudFlareDdos: Calling _preload() of  
85 29.03.2017 10:27:11 DEBUG HOSTER RockfileEu[30]: LOAD URL http://rockfile.eu/1wiyqt4iobi1.html | redirect=True | cookies=[('rockfile.eu', 'lang', 'english')] | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False  
86 29.03.2017 10:27:12 DEBUG ADDON CloudFlareDdos: _preload() returned successfully  
87 29.03.2017 10:27:12 INFO HOSTER RockfileEu[30]: Checking for link errors...  
88 29.03.2017 10:27:12 INFO HOSTER RockfileEu[30]: No errors found  
89 29.03.2017 10:27:12 INFO HOSTER RockfileEu[30]: Processing as free download...  
90 29.03.2017 10:27:12 DEBUG HOSTER RockfileEu[30]: LOAD URL http://rockfile.eu/1wiyqt4iobi1.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'usr_login': '', u'referer': u'http://rockfile.eu/1wiyqt4iobi1.html', u'fname': u'Summer_Bodies_are_made_in_Winter_Techno_Edition.rar', u'method_free': u'Regular Download', u'id': u'1wiyqt4iobi1', u'op': u'download1'} | ref=True | just_header=False  
91 29.03.2017 10:27:12 INFO HOSTER RockfileEu[30]: Checking for link errors...  
92 29.03.2017 10:27:12 DEBUG HOSTER RockfileEu[30]: WAIT set to timestamp 1490776048.519207 | Previous waitUntil: 1490776030.909840  
93 29.03.2017 10:27:12 DEBUG HOSTER RockfileEu[30]: RECONNECT not required | Previous wantReconnect: False  
94 29.03.2017 10:27:12 INFO HOSTER RockfileEu[30]: Waiting 15 seconds...  
95 29.03.2017 10:27:28 INFO HOSTER RockfileEu[30]: No errors found  
96 29.03.2017 10:27:28 DEBUG CAPTCHA RockfileEu[30]: ReCaptcha | Key: 6LdCmgATAAAAAPADIelEED1KQz1wraKFofdqJCyd  
97 29.03.2017 10:27:28 DEBUG CAPTCHA RockfileEu[30]: ReCaptcha | Detected Recaptcha v1  
98 29.03.2017 10:27:28 DEBUG HOSTER RockfileEu[30]: LOAD URL http://www.google.com/recaptcha/api/challenge | redirect=True | cookies=True | get={'k': u'6LdCmgATAAAAAPADIelEED1KQz1wraKFofdqJCyd'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False  
99 29.03.2017 10:27:28 DEBUG CAPTCHA RockfileEu[30]: ReCaptcha | Challenge: 03AOP2lf5mdPGN15tDL8UsFm2rW09ykwZQ-CAxdFmy_1OeLXT8ht13KfxwLKL0GIMquw65ucYEzrhrWiuvXicX955DP9MV6F4YximYC3-haziqu_qsifIdy5RNuHYN3jAajGcxLQHAzO76ffcoR2JOy39ie6FGulizmIdRYduTl_zguRl4UAa1LJs3knoB8-p8i3xCcEDOgOZK  
100 29.03.2017 10:27:28 DEBUG HOSTER RockfileEu[30]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False  
101 29.03.2017 10:27:28 DEBUG HOSTER RockfileEu[30]: LOAD URL http://www.google.com/recaptcha/api/reload | redirect=True | cookies=True | get={'reason': 'i', 'c': u'03AOP2lf5mdPGN15tDL8UsFm2rW09ykwZQ-CAxdFmy_1OeLXT8ht13KfxwLKL0GIMquw65ucYEzrhrWiuvXicX955DP9MV6F4YximYC3-haziqu_qsifIdy5RNuHYN3jAajGcxLQHAzO76ffcoR2JOy39ie6FGulizmIdRYduTl_zguRl4UAa1LJs3knoB8-p8i3xCcEDOgOZK', 'type': 'image', 'k': u'6LdCmgATAAAAAPADIelEED1KQz1wraKFofdqJCyd'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False  
102 29.03.2017 10:27:29 DEBUG CAPTCHA RockfileEu[30]: ReCaptcha | Second challenge: 03AOP2lf6aIkYw6tekMrD2zBjXKYTc3N7O22z5kTDRK1137jNZ_Gev7_K6APtXrAHW-eUOZ1UODagC6XBQ-0Exbr9TUhob4CJCevSy7N29h8g4s54uCNKsmhAU3Otk-EKyQ2aqZQG7Wg0rc2pS2boNNyYBIy2QFrvE9e9Ag3eJv3kID55ATiJ5CK4fHK2utl34iWcz-GGPjPFgB_eTiEwEgMpFmTmpfq3kDw  
103 29.03.2017 10:27:29 DEBUG CAPTCHA RockfileEu[30]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | redirect=True | cookies=True | get={'c': u'03AOP2lf6aIkYw6tekMrD2zBjXKYTc3N7O22z5kTDRK1137jNZ_Gev7_K6APtXrAHW-eUOZ1UODagC6XBQ-0Exbr9TUhob4CJCevSy7N29h8g4s54uCNKsmhAU3Otk-EKyQ2aqZQG7Wg0rc2pS2boNNyYBIy2QFrvE9e9Ag3eJv3kID55ATiJ5CK4fHK2utl34iWcz-GGPjPFgB_eTiEwEgMpFmTmpfq3kDw'} | req= | decode=False | multipart=False | post={} | ref=False | just_header=False  
104 29.03.2017 10:27:29 INFO CAPTCHA RockfileEu[30]: ReCaptcha | Using OCR to decrypt captcha...  
105 29.03.2017 10:27:29 WARNING CAPTCHA RockfileEu[30]: ReCaptcha | No OCR result  
106 29.03.2017 10:27:29 WARNING CAPTCHA RockfileEu[30]: ReCaptcha | No Client connected for captcha decrypting  
107 29.03.2017 10:27:29 DEBUG ADDON ExternalScripts: No script found under folder `download_processed`  
108 29.03.2017 10:27:29 DEBUG ADDON CloudFlareDdos: Unoverriding _preload() for  
109 29.03.2017 10:27:29 DEBUG ADDON ExternalScripts: No script found under folder `package_processed`  
110 29.03.2017 10:27:29 WARNING Download failed: Summer_Bodies_are_made_in_Winter_Techno_Edition.rar | No Client connected for captcha decrypting  
111 29.03.2017 10:27:29 INFO ADDON UnSkipOnFail: Looking for skipped duplicates of: Summer_Bodies_are_made_in_Winter_Techno_Edition.rar (pid:30)  
112 29.03.2017 10:27:29 INFO ADDON UnSkipOnFail: No duplicates found  
113 29.03.2017 10:27:29 DEBUG ADDON ExternalScripts: No script found under folder `download_failed`  
114 29.03.2017 10:27:29 DEBUG ADDON ExternalScripts: No script found under folder `all_downloads_processed`  
115 29.03.2017 10:27:29 DEBUG All downloads processed

**Comment by GammaC0de** [comment]
>No Client connected for captcha decrypting

This is not an issue: for the plugin to be able to download, you have to answer the captcha.
Because you were not connected to pyLoad's WebUI  and did not answered,it failed.

If you want pyLoad to solve the captcha for you, you can use captcha solving service like 9kw.eu and activate the plugin.

**Comment by maxking71** [comment]
thank you
I use openmediavault
where I find this plugin?
the list there is no

**Comment by GammaC0de** [comment]
First, go to http://9kw.eu and register an account.
Then you must solve some captchas at 9kw.eu to earn some credit.
After you have credit, get the API key for your user.

After that you go to pyLoad's configuration -> plugins  -> Captcha9Kw
Fill the API key and activate the plugin.

**Comment by maxking71** [comment]
thanks my friend

2017-03-29 10:55 GMT+02:00 GammaC0de <notifications@github.com>:
