### ISSUE TITLE
Real Debrid not working

### ISSUE THREAD

**Issue by Hetoft** [pyload/pyload#2815]
Hi there,

I am having problems logging in with Real Debrid. My account is valid and premium, but displays as not premium.

Using latest pyload (from Stable as of yesterday) on a rPi 3, installed using the guide here.

This is my log:

42	27.03.2017 07:24:47	INFO	Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
43	27.03.2017 07:24:47	INFO	Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
44	27.03.2017 07:24:47	INFO	Downloadtime: True
45	27.03.2017 07:24:47	INFO	Starting ThriftBackend: 0.0.0.0:7227
46	27.03.2017 07:24:47	INFO	Free space: 18.87 GiB
47	27.03.2017 07:24:48	INFO	Activating Accounts...
48	27.03.2017 07:24:48	INFO	Activating Plugins...
49	27.03.2017 07:24:49	INFO	Starting builtin webserver: 0.0.0.0:8000
50	27.03.2017 07:24:50	INFO	ADDON UpdateManager: pyLoad is up to date!
51	27.03.2017 07:24:50	INFO	ADDON UpdateManager: All plugins are up to date!
52	27.03.2017 07:24:52	INFO	ADDON XFileSharing: Auto-discover new hosters
53	27.03.2017 07:24:52	INFO	ADDON XFileSharing: Auto-discover new crypters
54	27.03.2017 07:24:52	INFO	pyLoad is up and running
55	27.03.2017 07:24:54	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
56	27.03.2017 13:24:50	INFO	ADDON UpdateManager: pyLoad is up to date!
57	27.03.2017 13:24:51	INFO	ADDON UpdateManager: All plugins are up to date!
58	27.03.2017 16:44:17	INFO	ACCOUNT RealdebridCom: Adding user `het*******`...
59	27.03.2017 16:44:17	INFO	ACCOUNT RealdebridCom: Login user `het*******`...
60	27.03.2017 16:44:18	ERROR	ACCOUNT RealdebridCom: Could not login user `het*******` | Login handshake has failed
61	27.03.2017 16:44:20	INFO	ACCOUNT RealdebridCom: Loading hoster list for user `het*******`...
62	27.03.2017 16:44:20	ERROR	ACCOUNT RealdebridCom: Could not load hoster list - invalid account, retry in 5 minutes
63	27.03.2017 16:49:20	INFO	ACCOUNT RealdebridCom: Loading hoster list for user `het*******`...
64	27.03.2017 16:49:20	ERROR	ACCOUNT RealdebridCom: Could not load hoster list - invalid account, retry in 5 minutes
65	27.03.2017 16:54:20	INFO	ACCOUNT RealdebridCom: Loading hoster list for user `het*******`...

Am I doing something wrong or is it just not working?

Thanks in advance.

**Comment by GammaC0de** [comment]
@Hetoft At the account configuration you should add your user and the API key retrieved from http://real-debrid.com/apitoken as password.

**Comment by Hetoft** [comment]
@GammaC0de Awesome, thank you very much. It works now! Perhaps the text can be changed to API instead of Password, so it's more visible to the user? Anyway, just glad it works for me.

**Comment by GammaC0de** [comment]
👍 I'm sorry but the text is hard-coded.
