### ISSUE TITLE
DebridItaliaAccount not getting premium status

### ISSUE THREAD

**Issue by MikeD23** [pyload/pyload#2816]
I wanted to use pyload again after some weeks but now I can't get my debriditalia premium account to work. I deleted userplugin folder and accounts.config to refresh all plugins and added my account again. It shows that my account is valid but that there would be no premium status. But in fact I got premium until end of July this year.

If you need my account info for checking, let me know.

Debug logs:
`1805	30.03.2017 21:34:08	INFO	ACCOUNT DebridItaliaCom: Relogin user Mik*******...`
`1806	30.03.2017 21:34:08	DEBUG	ACCOUNT DebridItaliaCom: LOAD URL https://debriditalia.com/api.php | redirect=True | cookies=True | get={'p': '**********', 'u': 'Mik*******', 'check': ''} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False`

**Comment by GammaC0de** [comment]
Account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by MikeD23** [comment]
Seems like it's working after autoupdating some plugins at night. After update pyload requested account info again and got then premium status. So I guess this issue could be closed.
