### ISSUE TITLE
Share-Online "Premium account needed" while using a premium account

### ISSUE THREAD

**Issue by M0V3** [pyload/pyload#2817]
On a few Share-Online.biz links I receive the error "Premium account needed" while using a premium account.
![DRK-RAT.RUN - Screenshot hosting](https://drk-rat.run/XtCjM54Bujjr1L.png)

![DRK-RAT.RUN - Screenshot hosting](https://drk-rat.run/Obpu5jGlN6Ci1o.png)

**Comment by GammaC0de** [comment]
@M0V3 Does this happen every time for the same links?

**Comment by GammaC0de** [comment]
No response, closing.
