### ISSUE TITLE
pyLoad installation unsuccessfull

### ISSUE THREAD

**Issue by andreapergola** [pyload/pyload#2821]
Hello there,
I was trying to install pyload 0.5.0 but I encountered some issues.

I am currently using Ubuntu Server 14.04.5 LTS, python 3.4, pip 9.0.1.

Firt of all, it seems like that pypi repository/page for pyload.core is broken since I was not able to use the automatic process at all. When I was trying any of the suggested method to install through pip I always receive this message:

> root@pegasus:~# pip install -U pyload.core[full]
> Collecting pyload.core[full]
>   Could not find a version that satisfies the requirement pyload.core[full] (from versions: )
> No matching distribution found for pyload.core[full]

Removing "[full]" or putting "--user" as argument didn't change anything. Searching on the internet I found a way to check if package is correctly setup through pypi and found that this link should contain the list of files to install: https://pypi.python.org/simple/pyload.core/
If you check you will see nothing, instead, for packages like pyload.utils (https://pypi.python.org/simple/pyload.utils/) and pyload.config (https://pypi.python.org/simple/pyload.config/) it correctly shows the list of links.

But I really wanted the latest shining pyload, so I tried to do some fixes&searches on the internet, so I found a way to use pip with a direct link to tar file, the problem was that the dependecies were not recognized, so I went here: https://requires.io/github/pyload/pyload/requirements/?tag=v0.5.2
and manually installed (with pip of course) all the packages in this list.

After that I run this:
> pip install -Iv https://github.com/pyload/pyload/archive/v0.5.0.tar.gz

I received this error: 
> error: package directory 'pyload/config' does not exist
> Cleaning up...
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-euuaidyo-build/

So I have tried with version 0.5.2:
> pip install -Iv https://github.com/pyload/pyload/archive/v0.5.2.tar.gz

And everything installed!

Triyng to run "pyload" showed me the following errors:
> Traceback (most recent call last):
>   File "/usr/local/bin/pyload", line 11, in <module>
>     load_entry_point('pyload.core==0.5.2', 'console_scripts', 'pyload')()
>   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
>     return ep.load()
>   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2302, in load
>     return self.resolve()
>   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
> ImportError: No module named 'pyLoad'

So I tought some module names in the code where mismatching the module name, so I change with find/sed all the string "pyLoad" in "pyload" through all the source code with this command:
> root@pegasus:/usr/local/lib/python3.4/dist-packages# find . -type f -exec sed -i 's/pyLoad/pyload/g' {} \;

So I was able to go after this error, but a new one appeared and I am stuck:
>  Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2310, in resolve
>     return functools.reduce(getattr, self.attrs, module)
> AttributeError: 'module' object has no attribute 'main'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/pyload", line 11, in <module>
>     load_entry_point('pyload.core==0.5.2', 'console_scripts', 'pyload')()
>   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
>     return ep.load()
>   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2302, in load
>     return self.resolve()
>   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2312, in resolve
>     raise ImportError(str(exc))
> ImportError: 'module' object has no attribute 'main'

Any idea on how to properly install pyload finally? :)

Ps: I saved the complete output of my terminal, just in case you need an in-depth look. I think I reported the important steps, but I may be wrong. Additionally you could enjoy all the typos/attempts I made before writing right commands since I am a very newbie bash/python user :)

**Comment by Slevin7** [comment]
pyLoad is the Free and Open Source download manager written in Pure Python and designed to be extremely lightweight, fully customizable and remotely manageable.

Notice: Master Branch is under heavy development, very unstable, often broken.
Notice: Stable Branch is production ready.

is just a copy from the code page.
pyload 0.5 is not working yet. We all still hope that its working soon and is note a duke nukem forever

**Comment by GammaC0de** [comment]
@andreapergola Please read #2000 for installation instructions.
