### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by New1997** [pyload/pyload#2822]
Hello,
I can't login from the web interface, it always says that the username and the password doesn't match
![image](https://cloud.githubusercontent.com/assets/27694657/25095141/a77159d2-239a-11e7-8f34-7e29c62285f0.png)
Thanks

**Comment by New1997** [comment]
by the way i have reset the login data a few dozen times already

**Comment by GammaC0de** [comment]
What OS are you using?

**Comment by New1997** [comment]
raspbian

**Comment by New1997** [comment]
i follow the installation in the wiki

**Comment by GammaC0de** [comment]
> i follow the installation in the wiki

Which one?

**Comment by New1997** [comment]
for raspberry pi

**Comment by GammaC0de** [comment]
URL for the instructions?

**Comment by New1997** [comment]
https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi)

**Comment by GammaC0de** [comment]
Well, do you have pyload user on your system?

If so, try issuing:
```
su pyload -s /bin/sh
/usr/bin/python /opt/pyload/pyLoadCore.py -s
```

**Comment by New1997** [comment]
I have tried t but it state another problem
(Sorry i don't have a picture here yet, it is a bit late here), i will contact as soon as i can.

**Comment by New1997** [comment]
(This is the form that i manage to get now)
pi@raspberrypi:~ $ su pyload -s /bin/sh/usr/bin/python /opt/pyload/pyLoadCore.py -s
su : l'option requiert un argument -- s
Syntaxe : su [options] [IDENTIFIANT]

Options :
  -c, --command COMMANDE        passer la commande COMMANDE à
                                l'interpréteur de commande appelé ;
  -h, --help                    afficher ce message d'aide et quitter ;
  -, -l, --login                utiliser un interpréteur de commandes
                                initial (« login shell ») ;
  -m, -p,
  --preserve-environment        ne pas réinitialiser les variables
                                d'environnement et conserver le même
                                interpréteur de commandes ;
  -s, --shell SHELL             utiliser SHELL comme interpréteur de
                                commandes à la place de celui défini
                                par défaut dans le fichier passwd.

**Comment by New1997** [comment]
Ps my computer configurations are in french

**Comment by GammaC0de** [comment]
Issue this (exactly):
```
su - -s /bin/sh pyload
/usr/bin/python /opt/pyload/pyLoadCore.py -s
```

and then post the output.

**Comment by New1997** [comment]
Same

**Comment by GammaC0de** [comment]
Output of `ls -l /home/pyload/`?

**Comment by New1997** [comment]
pi@raspberrypi:~ $ ls -l /home/pyload/
total 0
pi@raspberrypi:~ $ cd ..
pi@raspberrypi:/home $ ls
pi  pyload

**Comment by GammaC0de** [comment]
`find / -name files.db  -type f -print`

**Comment by New1997** [comment]
Sorry for the long absent, I have been very busy, but here is the ouput

pi@raspberrypi:~ $ sudo find / -name files.db -type f -print
/home/pi/.pyload/files.db
/home/pyload/.pyload/files.db
pi@raspberrypi:~ $

**Comment by GammaC0de** [comment]
Ok,
Now stop pyload and then try:
`sudo /usr/bin/python /opt/pyload/pyLoadCore.py -s --configdir=/home/pyload/.pyload`

**Comment by New1997** [comment]
It works thanks, could you please explain where was the problem please?

**Comment by GammaC0de** [comment]
Because pyLoad's service is configured to run as "pyload" user, the configuration directory is `/home/pyload/.pyload` but you were modifying the `/home/pi/.pyload` directory.

**Comment by New1997** [comment]
how can I access my downloaded file?

**Comment by GammaC0de** [comment]
It resides in the download folder, see http://192.168.1.45:8000/info for the location
