### ISSUE TITLE
change download folder

### ISSUE THREAD

**Issue by donaufisch66** [pyload/pyload#2823]
Hello,
I would like to change my download directory to a new harddisk (/share/MULTI3/Download3).
Where can I edit the download path? In the WebUI I cannot change anything. 
greetings Roland

**Comment by Slevin7** [comment]
you could change download folder in the settings under general --> general.

or did you mean, that this change nothing?

**Comment by donaufisch66** [comment]
yes, under settings-general, I can jus change within the installation folder but not "outside" or at any other share.

**Comment by donaufisch66** [comment]
I solved that issue with a clean installation. At the setup I could define a path to an download folder. In the WebUI the download folder cannot be changed anymore.

**Comment by GammaC0de** [comment]
@donaufisch66 Sound like a permissions issue.
