### ISSUE TITLE
restart pyload in idle state?

### ISSUE THREAD

**Issue by donaufisch66** [pyload/pyload#2824]
Hello,
occasionally my pyload installation likes to be restarted . Therefore I would like to restart pyload automatically in idle state.  Is there any possibility inside pyload to check if pyload is downloading/active or not?
Is there any variable, flag or file that I can read to use the value in a small Skript?
for example:
restart.sh:
if [ $idle-state= 0 ]; then  {pyload -q; sleep 10; pyload --daemon}

together with a cronjob every 30 minutes:
cru a PyRestart "*/30 * * * * /xxx/pystart.sh"

Can you tell me if there is any $idle-state variable in pyload that represents weather pyload is downloading or not, or how can I define one?

greetings 
roland

**Comment by GammaC0de** [comment]
If `python pyLoadCli.py status`  is "No downloads running." then pyload is idle.

`python pyLoadCore.py -q` to make pyload exit.

**Comment by Mister-XY** [comment]
I think you need the full path for your cronjob. 
`python pyLoadCore.py -q` 

for many days, i have wrote a daemon for pyload. This script has checked if pyload runs. 
And via ./pyload.sh it's run very well but with cronjob not, the error in that's script was the missing path.
And with the path, it's runs very well.

**Comment by donaufisch66** [comment]
@Mister-XY 
Hello,
can you send me your Skript?

**Comment by Mister-XY** [comment]
Ok, it's only a startscript, 
`#!/bin/sh
sleep 40
      if [ `ps aux | grep "pyLoadCore" | grep -v grep | wc -l` -eq 0 ]; then
         /usr/share/pyload/pyLoadCore.py --daemon
		 echo "Pyloadcore wurde gestartet" > /tmp/pyloadcorelog.log
      fi
exit
`

**Comment by donaufisch66** [comment]
thank you! I just found another solution:

`#!/bin/sh
if python pyLoadCli.py status | grep 'No downloads running.'; then
  echo idle
else
  echo busy
fi`

**Comment by donaufisch66** [comment]
@Mister-XY 
Hi,
what for are you using "grep -v"? -v inverts the result. and WC returns a number. 
why dont you just use " ps aux | grep "pyLoadCore" | wc -l "? if pyload is running, result =1, else 0.

**Comment by GammaC0de** [comment]
Another way to do it is to enable `ExternalScripts` plugin and put a script under:

 \<pyload_config_folder\>\scripts\all_downloads_processed:
```bash
#!/bin/sh
echo idle > /tmp/pyload_status
if [ -f /tmp/pyload_restart ]; then
   rm -f /tmp/pyload_restart
   service pyload restart
fi
```
 \<pyload_config_folder\>\scripts\download_preparing:
```bash
#!/bin/sh
echo busy > /tmp/pyload_status
```
 \<pyload_config_folder\>\scripts\pyload_start:
```bash
#!/bin/sh
echo idle > /tmp/pyload_status
```
 \<pyload_config_folder\>\scripts\pyload_stop:
```bash
#!/bin/sh
rm -f /tmp/pyload_status
rm -f /tmp/pyload_restart
```


and then on the cron job script you would:
```bash
if [ -f "/tmp/pyload_status" ];
then
   pyload_status = `cat /tmp/pyload_status`
   if [ $pyload_status = "idle" ]; then
       service pyload restart
   else
      touch /tmp/pyload_restart
   fi
fi
```
