### ISSUE TITLE
Pyload doesn't work on qnap 4.3.3.0154 firmware version

### ISSUE THREAD

**Issue by PedroGPP** [pyload/pyload#2827]
Hello,

I've upgraded my qnap firmware and when i tried to start pyload the web interface could not be found.
I thought that uninstalling and reinstalling the app will do the trick.
After uninstalling pyload i went to the app center and find out that pyload was removed from there.
Is there any way to reinstall a functional version of pyload on this new firmware?

Regards
Pedro Guerra

**Comment by GammaC0de** [comment]
https://www.qnap.com/de-de/app_center/con_show.php?op=showone&internalName=pyLoad&version=4.9&down_1_name=TS-NASX86&jump_win=1&qts=4.2.2&seq=46

**Comment by PedroGPP** [comment]
Thank you, i'v installed pyload again but when i try to open it i get web page inaccessible.

**Comment by PedroGPP** [comment]
@GammaC0de before the firmware upgrade my pyload was working fine, it was exactly the same version that i installed from the site you have indicate. After the firmware upgrade i can't access the web console. As i mentioned i thought that reinstalling pyload would resolve the problem, but i was wrong.
Is there any compatibility problem with the new QNAP firmware version?

Regards
Pedro Guerra

**Comment by GammaC0de** [comment]
I do not own a QNAP.

You have to replace `/share/CACHEDEV1_DATA/.qpkg/pyload/module/plugins/hooks/UpdateManager.py ` with this one: https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/78f10968869e887d802a75a9ef6b89628d0d5ff9/UpdateManager.py

and then run pyload from the console with
`python /share/CACHEDEV1_DATA/.qpkg/pyload/pyLoadCore.py --configdir=/share/CACHEDEV1_DATA/.qpkg/pyload/data -d`

then post the output from the console.

**Comment by PedroGPP** [comment]
The configdir command return an error.

=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2017.04.19 15:13:22 =~=~=~=~=~=~=~=~=~=~=~=
login as: admin
admin@192.168.1.12's password: 
c(B[0m[J[?25h[~] # 
                                                                                                                                                                                                                                            
[~] # find / -name UpdateManager.py -f
find: unknown predicate `-f'
[~] # find / -name UpdateManager.py -f
[~] # find / -name UpdateManager.py  -ft -fy -fp -fe -f
[~] # find / -name UpdateManager.py type  -f
[~] # find / -name UpdateManager.py type
[~] # find / -name UpdateManager.py type 
[~] # find / -name UpdateManager.py type  
[~] # find / -name UpdateManager.py type  -f 
[~] # find / -name UpdateManager.py typ
[~] # find / -name UpdateManager.py type
[~] # find / -name UpdateManager.py type f -type f
/share/CACHEDEV1_DATA/.qpkg/CodexPack/mnt/share/CACHEDEV1_DATA/homes/UpdateManager.py
/share/CACHEDEV1_DATA/.qpkg/CodexPack/mnt/share/CACHEDEV1_DATA/homes/pyload-stable/module/plugins/hooks/UpdateManager.py
find: ‘/share/CACHEDEV1_DATA/.qpkg/CodexPack/proc/13424’: No such file or directory
find: ‘/share/CACHEDEV1_DATA/.qpkg/CodexPack/proc/13699’: No such file or directory
find: ‘/share/CACHEDEV1_DATA/.qpkg/CodexPack/proc/13732’: No such file or directory
find: ‘/share/CACHEDEV1_DATA/.qpkg/CodexPack/proc/13735’: No such file or directory
/share/CACHEDEV1_DATA/.qpkg/pyload/module/plugins/hooks/UpdateManager.py
/share/CACHEDEV1_DATA/homes/UpdateManager.py
/share/CACHEDEV1_DATA/homes/pyload-stable/module/plugins/hooks/UpdateManager.py
find: ‘/proc/14562’: No such file or directory
find: ‘/proc/14679’: No such file or directory
find: ‘/proc/14701’: No such file or directory
[~] # cd /share/CACHEDEV1_DATA/homes
[/share/CACHEDEV1_DATA/homes] # cp UpdateManager.py /share/CACHEDEV1_DATA/homes/pyload-stable/module/plugins/hooks/                                                                 /share/CACHEDEV1_DATA/.qpkg/pyload/module/plugins/hooks/
[/share/CACHEDEV1_DATA/homes] # cd /
[/] # python /share/CACHEDEV1_DATA/.qpkg/pyload/pyLoadCore.py --
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/network/HTTPRequest.py", line 20, in <module>
    import pycurl
ImportError: No module named pycurl
[/] # configdir=/share/CACHEDEV1_DATA/.qpkg/pyload/data -d
-sh: -d: command not found
[/] # exit
logout

**Comment by GammaC0de** [comment]
Sorry for late response,

Your log is not clear, please repeat the process and dont forget to sorround the text with triple quotes (\`\`\`) so it will not be tampered.

One thing I could understand from the log is that python cannot find the required pycurl package...

**Comment by PedroGPP** [comment]
@GammaC0de As you asked here is the result log:
"[~] # python /share/CACHEDEV1_DATA/.qpkg/pyload/pyLoadCore.py --
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/network/HTTPRequest.py", line 20, in <module>
    import pycurl
ImportError: No module named pycurl
[~] # configdir=/share/CACHEDEV1_DATA/.qpkg/pyload/data -d
-sh: -d: command not found"

**Comment by GammaC0de** [comment]
@PedroGPP Still not readable - you have to surround the text with triple quotes (\`\`\`) 

e.g:
\`\`\`
 Very important text
\`\`\`

makes:
```
Very important text
```

**Comment by PedroGPP** [comment]
@GammaC0de Ok.
'''c(B[0m[J[?25h[~] # 
                                                                                                                                                                                                                                            
[~] # python /share/CACHEDEV1_DATA/.qpkg/pyload/pyLoadCore.py --
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/network/HTTPRequest.py", line 20, in <module>
    import pycurl
ImportError: No module named pycurl
[~] # configdir=/share/CACHEDEV1_DATA/.qpkg/pyload/data -d
-sh: -d: command not found
'''

**Comment by GammaC0de** [comment]
```
ImportError: No module named pycurl
```

Python module pycurl is not installed.

**Comment by PedroGPP** [comment]
@GammaC0de I understand, but i don't know how to install that module. Can you help me on that please?

**Comment by GammaC0de** [comment]
@PedroGPP What python version do you have?

**Comment by PedroGPP** [comment]
@GammaC0de I have installed Python 2.7.12, Python3 3.5.2.0 and Entware-ng 0.97.

**Comment by GammaC0de** [comment]
You can try these options:
1. Try this QPKG https://github.com/pyload/pyload/files/849853/pyload_4.9.qpkg.zip
2. Try the instructions in https://github.com/pyload/pyload/issues/2749#issuecomment-286433009
3. Try the instructions in https://github.com/pyload/pyload/issues/2749#issuecomment-283027159
