### ISSUE TITLE
QUESTION - AddPackage API example

### ISSUE THREAD

**Issue by Ryan747800B** [pyload/pyload#2828]
Is there some examples on how to use AddPackage API? It's the very first time I use the API, so I don't know how to manage this API request.
For example this is working fine after login

`IP:PORT/api/getFileData?fid=1`

but how can I use this

`addPackage(name, links[, dest])`

I tried to change name, links and dest but doesn't work

`IP:PORT/api/addPackage(TEST, http://example_URL[, queue])`

**Comment by GammaC0de** [comment]
`http://IP:PORT/api/addPackage?name=%22test%22&links=%5B%22https%3A%2F%2Fgithub.com%2Fpyload%2Fpyload%2Freleases%2Fdownload%2Fv0.4.9%2Fpyload_0.4.9_win.zip%22%5D`

**Comment by Ryan747800B** [comment]
Really thanks @GammaC0de !

**Comment by Ryan747800B** [comment]
@GammaC0de Yesterday this login method was working fine http://IP:Port/api/login?username="user"&password="password" but now it says Error 403. Am I missing something?

**Comment by GammaC0de** [comment]
Are there any spacial characters in the user / password ?

**Comment by Ryan747800B** [comment]
No only numbers/letters

**Comment by GammaC0de** [comment]
Try running pyload with `python pyLoadCore.py -d`  then try logging in and  check if you see anything special in the log..

**Comment by Ryan747800B** [comment]
Debug mode doesn't say anything relevant. But I noticed that if I'm not logged in then if I use this `http://IP:Port/api/login?username=%22username%22&password=%22password%22` then it says `Error 405 method not allowed` and if I use this `http://IP:Port/api/login/%22username%22/%22password%22` then `403 Forbidden` (with an HTML Source view); but if I manually login and use method 2 then it says `true`.
So the URL API is correct but doesn't work until a manual login.

**Comment by GammaC0de** [comment]
What tool do you use  to send the requests?

For login, you have to use POST method, e.g.:
```bash
wget "http://IP:PORT/api/login" --post-data="username=username&password=password" --save-cookies=./cookiejar.txt --keep-session-cookies -q -O -
wget "http://IP:PORT/api/addPackage?name=%22test%22&links=%5B%22https%3A%2F%2Fgithub.com%2Fpyload%2Fpyload%2Freleases%2Fdownload%2Fv0.4.9%2Fpyload_0.4.9_win.zip%22%5D" --load-cookies=./cookiejar.txt -q -O -
```
```

**Comment by Ryan747800B** [comment]
Sorry for late reply. I'm using Terminal; a NAS reboot seems to have solved the issue: now I can login and inject a package through SSH without any issue. Thank you really much!
