### ISSUE TITLE
IMPORTANT QUESTION - Is pyLoad dicoverable by search engines?

### ISSUE THREAD

**Issue by Ryan747800B** [pyload/pyload#2829]
Is pyLoad Webserver indexed by BigG or other search engine (DuckDuckGo, SHODAN, etc.)? Is there a way to protect it, I don't know, for example with a 2FA access? I know I can whitelist some IP but when I remotely access I have always different IPs.

**Comment by GammaC0de** [comment]
I'm afraid not:
https://www.google.com/search?q=intext:%22pyLoad+-+Webinterface%22&ie=utf-8&oe=utf-8

https://www.google.co.il/search?q=intitle:%22Login+-+pyLoad+Webinterface%22&ie=utf-8&oe=utf-8

**Comment by GammaC0de** [comment]
You can block search engines with `robots.txt` file:

[Add_Support_for_robots_txt.zip](https://github.com/pyload/pyload/files/949261/Add_Support_for_robots_txt.zip)

**Comment by Ryan747800B** [comment]
Thank you @GammaC0de . It's a really future must-have feature for pyLoad. If I have any issue I report it here.

**Comment by GammaC0de** [comment]
👍 Please notice there was a typo which was fixed in the PR.
