### ISSUE TITLE
userscloud broken

### ISSUE THREAD

**Issue by nik1a** [pyload/pyload#2834]
It tries few times to start the download but in the end it fails

> TEXTAREA F1 not found 0.00 B

**Comment by GammaC0de** [comment]
Disable XFileSharing plugin.

**Comment by nik1a** [comment]
That did not help unfortunately. The only difference is that now it waits 1min between retries with XfileSharing enabled it was 1sec.

Pyload version: 0.4.9 on raspbery pi3 Arch linux
Plugin version: 0.06
Log:
The link is just a big bug bunny image in an archive :)
> 25.04.2017 18:59:47	INFO	HOSTER UserscloudCom[4]: Grabbing link info...
121	25.04.2017 18:59:48	INFO	HOSTER UserscloudCom[4]: Link name: test.7z
122	25.04.2017 18:59:48	INFO	HOSTER UserscloudCom[4]: Link size: 353.00 KiB (361472 bytes)
123	25.04.2017 18:59:48	INFO	HOSTER UserscloudCom[4]: Link status: online
124	25.04.2017 18:59:48	INFO	HOSTER UserscloudCom[4]: Processing url: https://userscloud.com/5fqulwhe1khf
125	25.04.2017 18:59:48	INFO	HOSTER UserscloudCom[4]: Looking for direct download link...
126	25.04.2017 18:59:49	INFO	HOSTER UserscloudCom[4]: Direct download link not found
127	25.04.2017 18:59:49	INFO	HOSTER UserscloudCom[4]: Checking for link errors...
128	25.04.2017 18:59:49	INFO	HOSTER UserscloudCom[4]: No errors found
129	25.04.2017 18:59:49	INFO	HOSTER UserscloudCom[4]: Processing as free download...
130	25.04.2017 18:59:50	INFO	HOSTER UserscloudCom[4]: File saved
131	25.04.2017 18:59:50	INFO	HOSTER UserscloudCom[4]: Checking download...
132	25.04.2017 18:59:50	INFO	HOSTER UserscloudCom[4]: File is OK
133	25.04.2017 18:59:50	INFO	HOSTER UserscloudCom[4]: Checking file (with built-in rules)...
134	25.04.2017 18:59:50	WARNING	HOSTER UserscloudCom[4]: Check result: Html file | Waiting 1 minute and retry
135	25.04.2017 18:59:50	INFO	HOSTER UserscloudCom[4]: Waiting 1 minutes...
136	25.04.2017 18:59:50	INFO	HOSTER UserscloudCom[4]: Requiring reconnection...
Jump to time:
25.04.2017 18:58:42
  ok
