### ISSUE TITLE
UploadedTo premium broken

### ISSUE THREAD

**Issue by lukasgierth** [pyload/pyload#2835]
28.04.2017 15:21:52 INFO      HOSTER UploadedTo[237]: Processing as premium download...
28.04.2017 15:21:52 INFO      HOSTER UploadedTo[237]: Downloading file...
28.04.2017 15:21:52 ERROR     HOSTER UploadedTo[237]:
28.04.2017 15:21:52 WARNING   HOSTER UploadedTo[237]: Premium download failed | IOError 20

**Comment by Slevin7** [comment]
i cant repoduce this error.
did you do this?
https://github.com/pyload/pyload/issues/2000 ?

**Comment by lukasgierth** [comment]
Didn't help. But i did a complete reinstall (so, delete everything, also the config files in my home folder).

Different links work, seems to be a problem with the explicit links i used (which work perfectly in a browser)
