### ISSUE TITLE
Plugin kee2share: Parse error: Unique-ID pattern not found

### ISSUE THREAD

**Issue by kveiro** [pyload/pyload#2842]
Hi, plugin is updated to v .34, but still same error and no captcha request :(
In browser i can download w/o troubles.

( no changes in log )

07.05.2017 15:16:11	DEBUG	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
241	07.05.2017 15:16:11	DEBUG	ADDON UserAgentSwitcher: Setting maximum redirections to 10
242	07.05.2017 15:16:11	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0`
243	07.05.2017 15:16:11	DEBUG	HOSTER Keep2ShareCc[98]: Plugin version: 0.34
244	07.05.2017 15:16:11	DEBUG	HOSTER Keep2ShareCc[98]: Plugin status: testing
245	07.05.2017 15:16:11	WARNING	HOSTER Keep2ShareCc[98]: Plugin may be unstable
246	07.05.2017 15:16:11	DEBUG	Redirected import module.plugins.accounts.Keep2ShareCc -> userplugins.accounts.Keep2ShareCc
247	07.05.2017 15:16:11	INFO	HOSTER Keep2ShareCc[98]: Grabbing link info...
248	07.05.2017 15:16:19	DEBUG	HOSTER Keep2ShareCc[98]: Link info: {'status': 7, 'hash': {}, 'name': '6fbee53a940ad', 'url': u'https://keep2share.cc/file/6fbee53a940ad', 'pattern': {'ID': u'6fbee53a940ad'}, 'size': 0}
249	07.05.2017 15:16:19	DEBUG	HOSTER Keep2ShareCc[98]: Previous link info: {}
250	07.05.2017 15:16:19	INFO	HOSTER Keep2ShareCc[98]: Link name: 6fbee53a940ad
251	07.05.2017 15:16:19	INFO	HOSTER Keep2ShareCc[98]: Link size: N/D
252	07.05.2017 15:16:19	INFO	HOSTER Keep2ShareCc[98]: Link status: starting
253	07.05.2017 15:16:19	INFO	HOSTER Keep2ShareCc[98]: Processing url: https://keep2share.cc/file/6fbee53a940ad/
254	07.05.2017 15:16:19	INFO	HOSTER Keep2ShareCc[98]: Looking for direct download link...
255	07.05.2017 15:16:19	DEBUG	HOSTER Keep2ShareCc[98]: LOAD URL https://keep2share.cc/file/6fbee53a940ad | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
256	07.05.2017 15:16:23	DEBUG	HOSTER Keep2ShareCc[98]: Redirect #1 to: https://new.keep2share.cc/file/6fbee53a940ad
257	07.05.2017 15:16:23	DEBUG	HOSTER Keep2ShareCc[98]: LOAD URL https://new.keep2share.cc/file/6fbee53a940ad | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
258	07.05.2017 15:16:27	INFO	HOSTER Keep2ShareCc[98]: Direct download link not found
259	07.05.2017 15:16:27	DEBUG	HOSTER Keep2ShareCc[98]: LOAD URL https://keep2share.cc/file/6fbee53a940ad | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
260	07.05.2017 15:16:32	INFO	HOSTER Keep2ShareCc[98]: Grabbing link info...
261	07.05.2017 15:16:32	DEBUG	HOSTER Keep2ShareCc[98]: Link info: {'status': 7, 'hash': {}, 'name': '6fbee53a940ad', 'url': u'https://keep2share.cc/file/6fbee53a940ad', 'pattern': {'ID': u'6fbee53a940ad'}, 'size': 0}
262	07.05.2017 15:16:32	DEBUG	HOSTER Keep2ShareCc[98]: Previous link info: {'status': 7, 'hash': {}, 'name': '6fbee53a940ad', 'url': u'https://keep2share.cc/file/6fbee53a940ad', 'pattern': {'ID': u'6fbee53a940ad'}, 'size': 0}
263	07.05.2017 15:16:32	INFO	HOSTER Keep2ShareCc[98]: Link name: 6fbee53a940ad
264	07.05.2017 15:16:32	INFO	HOSTER Keep2ShareCc[98]: Link size: N/D
265	07.05.2017 15:16:32	INFO	HOSTER Keep2ShareCc[98]: Link status: starting
266	07.05.2017 15:16:32	INFO	HOSTER Keep2ShareCc[98]: Processing as free download...
267	07.05.2017 15:16:32	DEBUG	HOSTER Keep2ShareCc[98]: LOAD URL https://keep2share.cc/file/6fbee53a940ad | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'slow_id': u'2f6ebfb854114', 'yt0': ''} | ref=True | just_header=False
268	07.05.2017 15:16:35	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
269	07.05.2017 15:16:35	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
270	07.05.2017 15:16:35	WARNING	Download failed: 6fbee53a940ad | Parse error: Unique-ID pattern not found | Plugin may be out of date
271	07.05.2017 15:16:35	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
272	07.05.2017 15:16:35	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 6fbee53a940ad (pid:98)
273	07.05.2017 15:16:35	INFO	ADDON UnSkipOnFail: No duplicates found 

Thanks in Advance.

**Comment by kveiro** [comment]
Update:
I have noticed that keep2share randomly redirecting to their new design of download page. In this case link should be [b]new[/b].keep2share.cc.
But here need some work on new code.

**Comment by kveiro** [comment]
Update:
I have noticed that keep2share randomly redirecting to their new design of download page. In this case link should be **new**.keep2share.cc. 
But here need some work on new code.

**Comment by kveiro** [comment]
Update:
I have noticed that keep2share randomly redirecting to their new design of download page. In this case link look like **new**.keep2share.cc.
May be it can help, probably need change source code of plugin.

**Comment by kveiro** [comment]
Hello,
Thanks for help :)
I don't know if i need reopen this issue again, but i'll try continue here.
 
The strange problem with ***Unique-ID pattern not found*** still present. BUT now seems to be i have found how i get this damned message.
It simply - plugin keep2share.Cc has never reported : You need wait 24342bla seconds.
probably this ---> self.log_debug("Hoster told us to wait for %s" % m.group(1))
If anyone has downloaded link for this IP, and time is not yet out, in pyload you can get only message about Patttern bla bla.
Plugin keep2share v32 is still working. ( Karl! )

Please correct code for wait time from k2s server.

Thanks.

**Comment by kveiro** [comment]
Hi,
I have found another bug, that is not related to wait time after download is completed for one IP.
That link -> https://keep2share.cc/file/6fbee53a940ad (from my 1st post with log)  pyload has dowloaded file succefully. 

But from that: http://k2s.cc/file/c7c804f16c0b5 ( and many others ) - again ***Unique-ID pattern not found***

Log:

103	10.05.2017 15:52:37	INFO	Added package http://k2s.cc/file/c7c804f16c0b5 containing 1 links
104	10.05.2017 15:52:38	INFO	Download starts: http://k2s.cc/file/c7c804f16c0b5
105	10.05.2017 15:52:38	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
106	10.05.2017 15:52:38	DEBUG	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
107	10.05.2017 15:52:38	DEBUG	ADDON UserAgentSwitcher: Setting maximum redirections to 10
108	10.05.2017 15:52:38	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; rv:15.3) Gecko/20121202 Firefox/15.3.2 PaleMoon`
109	10.05.2017 15:52:38	DEBUG	HOSTER Keep2ShareCc[118]: Plugin version: 0.35
110	10.05.2017 15:52:38	DEBUG	HOSTER Keep2ShareCc[118]: Plugin status: testing
111	10.05.2017 15:52:38	WARNING	HOSTER Keep2ShareCc[118]: Plugin may be unstable
112	10.05.2017 15:52:38	INFO	HOSTER Keep2ShareCc[118]: Grabbing link info...
113	10.05.2017 15:52:40	DEBUG	HOSTER Keep2ShareCc[118]: Link info: {'status': 2, 'hash': {}, 'name': 'Latex _ Chrome #2.zip', 'url': u'https://keep2share.cc/file/c7c804f16c0b5?force_old=1', 'pattern': {'S': u'14.0 MB', 'ID': u'c7c804f16c0b5', 'N': u'Latex _ Chrome #2.zip'}, 'size': 14680064}
114	10.05.2017 15:52:40	DEBUG	HOSTER Keep2ShareCc[118]: Previous link info: {}
115	10.05.2017 15:52:40	INFO	HOSTER Keep2ShareCc[118]: Link name: Latex _ Chrome #2.zip
116	10.05.2017 15:52:40	INFO	HOSTER Keep2ShareCc[118]: Link size: 14.00 MiB (14680064 bytes)
117	10.05.2017 15:52:40	INFO	HOSTER Keep2ShareCc[118]: Link status: online
118	10.05.2017 15:52:40	INFO	HOSTER Keep2ShareCc[118]: Processing url: http://k2s.cc/file/c7c804f16c0b5
119	10.05.2017 15:52:40	INFO	HOSTER Keep2ShareCc[118]: Looking for direct download link...
120	10.05.2017 15:52:40	DEBUG	HOSTER Keep2ShareCc[118]: LOAD URL https://keep2share.cc/file/c7c804f16c0b5?force_old=1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
121	10.05.2017 15:52:44	DEBUG	HOSTER Keep2ShareCc[118]: Redirect #1 to: https://k2s.cc/file/c7c804f16c0b5?force_old=1
122	10.05.2017 15:52:44	DEBUG	HOSTER Keep2ShareCc[118]: LOAD URL https://k2s.cc/file/c7c804f16c0b5?force_old=1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
123	10.05.2017 15:52:47	INFO	HOSTER Keep2ShareCc[118]: Direct download link not found
124	10.05.2017 15:52:47	DEBUG	HOSTER Keep2ShareCc[118]: LOAD URL https://keep2share.cc/file/c7c804f16c0b5?force_old=1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
125	10.05.2017 15:52:52	INFO	HOSTER Keep2ShareCc[118]: Processing as free download...
126	10.05.2017 15:52:52	DEBUG	HOSTER Keep2ShareCc[118]: LOAD URL https://keep2share.cc/file/c7c804f16c0b5?force_old=1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'slow_id': u'14d770e4c472c', 'yt0': ''} | ref=True | just_header=False
127	10.05.2017 15:52:54	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
128	10.05.2017 15:52:54	INFO	ADDON ExternalScripts: Executing scripts in folder `package_processed`...
130	10.05.2017 15:52:54	WARNING	Download failed: Latex _ Chrome #2.zip | Parse error: Unique-ID pattern not found | Plugin may be out of date
131	10.05.2017 15:52:54	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
132	10.05.2017 15:52:54	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Latex _ Chrome #2.zip (pid:118)
133	10.05.2017 15:52:54	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by kveiro** [comment]
Тhis:
URL_REPLACEMENTS = [(__pattern__ + ".*", "***https://keep2share.cc***/file/\g<ID>")]
Does not work any more :(  
This is the reason why I could not download the second file.
I replaced //keep2share.cc/file with //k2s/file and then it already worked with the second file.
It is clear that this is not a universal solution.

If you have any ideas, please implement them in the plugin.

About the wait time after downloading the file, I was wrong, just forget :)
Sorry for bad english, thankful in advance for the support

**Comment by GammaC0de** [comment]
This actually seems to be the cause of the problem:
If you go to https://keep2share.cc/file/c7c804f16c0b5?force_old=1, it will redirect you to https://k2s.cc/file/c7c804f16c0b5?force_old=1
