### ISSUE TITLE
RealdebridCom: Hosters not overwritten

### ISSUE THREAD

**Issue by Okanami** [pyload/pyload#2843]
Hello :octopus: 

Protip : I'm a noob !

I recently builded my RPI3 with Pyload but today, my SD get corrupted and i don't have any save..
I thinks it's because my smb mounted on /pi/HDD got unmounted (idk why ) and pyload continue to download heavy files in /pi/HDD (but because the smb was unreachable, on the SD ) and after a reboot... boum, black screen, dot blinking.. :(

I've re-do everything again BUT i got the same problem as before with Real Debrid :

> 281	08.05.2017 04:26:43	INFO	Démarrage pyLoad 0.4.9
> 282	08.05.2017 04:26:43	INFO	Utilisation du dossier principal : /root/.pyload
> 283	08.05.2017 04:26:44	INFO	Plugins activés: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
> 284	08.05.2017 04:26:44	INFO	Plugins désactivés: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
> 285	08.05.2017 04:26:44	INFO	Temps de téléchargement : True
> 286	08.05.2017 04:26:45	INFO	Starting builtin webserver: xxxxxxxxxxxxxxxxx
> 287	08.05.2017 04:26:45	INFO	Free space: 10.60 GiB
> 288	08.05.2017 04:26:45	INFO	Activating Accounts...
> 289	08.05.2017 04:26:45	INFO	Activating Plugins...
> 290	08.05.2017 04:26:46	INFO	ADDON XFileSharing: Auto-discover new hosters
> 291	08.05.2017 04:26:46	INFO	ADDON XFileSharing: Auto-discover new crypters
> 292	08.05.2017 04:26:46	INFO	pyLoad is up and running
> 293	08.05.2017 04:26:46	INFO	ADDON UpdateManager: pyLoad is up to date!
> 294	08.05.2017 04:26:46	INFO	ADDON UpdateManager: All plugins are up to date!
> 295	08.05.2017 04:26:52	INFO	ADDON ClickNLoad: Proxy listening on xxxxxxxxxx
> 296	08.05.2017 04:52:10	INFO	ACCOUNT RealdebridCom: Adding user `xxxxxxxxx
> 297	08.05.2017 04:52:10	INFO	ACCOUNT RealdebridCom: Login user `xxxxxxxxxx.
> 298	08.05.2017 04:52:11	INFO	ACCOUNT RealdebridCom: Grabbing account info for user `xxxxxxxx..
> 299	08.05.2017 04:52:14	INFO	ACCOUNT RealdebridCom: Loading hoster list for user `xxxxxxxx`.
> 300	08.05.2017 04:52:14	INFO	ACCOUNT RealdebridCom: Hosters not overwritten: real-debrid.com

In my first build, i got rid of this but i can't remember how ..

What can i do to correct this problem ? 

Thanks you :)

**Comment by GammaC0de** [comment]
Do you have any issue? 
RealdebridCom cannot overwrite itself...

**Comment by Okanami** [comment]
In my last build, i got :
[RealdebridCom: Overwritten Hosters: uploaded.net, uptobox.com, dl.free.fr etc..]
This is why i was thinking i've an issue :( 

I don't know how, but, right now, i managed to made the RealDebridCom plugin to download my file as premium, instead of base plugin yesterday.

Maybe because i uninstalled pyload ( he got installed in /usr/share ) then install again ( then in /opt/pyload ) ?

**Comment by GammaC0de** [comment]
Please stop pyload and then start it with the command `python pyLoadCore.py -d` and post **ALL** the output here to insure proper installation..

**Comment by Okanami** [comment]
> python pyLoadCore.py -d
09.05.2017 02:37:31 INFO      DÃ©marrage pyLoad 0.4.9
09.05.2017 02:37:31 INFO      Utilisation du dossier principal : /home/pyload/.pyload
09.05.2017 02:37:31 DEBUG     Remote activated: False
09.05.2017 02:37:32 DEBUG     created index of plugins
09.05.2017 02:37:32 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
09.05.2017 02:37:32 DEBUG     Redirected import userplugins.internal.Addon -> module.plugins.internal.Addon
09.05.2017 02:37:32 DEBUG     Redirected import userplugins.internal.misc -> module.plugins.internal.misc
09.05.2017 02:37:32 INFO      Plugins activÃ©s: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
09.05.2017 02:37:32 INFO      Plugins dÃ©sactivÃ©s: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
09.05.2017 02:37:32 INFO      Temps de tÃ©lÃ©chargement : True
09.05.2017 02:37:33 WARNING   SSL certificates not found.
09.05.2017 02:37:33 INFO      Free space: 10.56 GiB
09.05.2017 02:37:33 INFO      Starting builtin webserver: **************
09.05.2017 02:37:33 INFO      Activating Accounts...
09.05.2017 02:37:33 INFO      ACCOUNT RealdebridCom: Adding user `**************`...
09.05.2017 02:37:33 DEBUG     ACCOUNT RealdebridCom: Reached login timeout for user `**************`
09.05.2017 02:37:33 INFO      ACCOUNT RealdebridCom: Login user `**************`...
09.05.2017 02:37:33 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/user | redirect=True | cookies=True | get={'auth_token': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
09.05.2017 02:37:34 INFO      ACCOUNT RealdebridCom: Grabbing account info for user `**************`...
09.05.2017 02:37:34 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/user | redirect=True | cookies=True | get={'auth_token': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
09.05.2017 02:37:34 DEBUG     ACCOUNT RealdebridCom: Account info for user `**************`: {'login': {'timestamp': **************, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account RealdebridCom>, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': **************, 'login': '**************', 'type': 'RealdebridCom', 'options': {'limitdl': ['0']}}}
09.05.2017 02:37:34 INFO      Activating Plugins...
09.05.2017 02:37:34 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_start`
09.05.2017 02:37:34 DEBUG     ADDON ExtractArchive: Found UnZip 2.7.9 | Found UnTar 2.7.9
09.05.2017 02:37:34 DEBUG     Redirected import module.plugins.hoster.Keep2ShareCc -> userplugins.hoster.Keep2ShareCc
09.05.2017 02:37:34 DEBUG     Redirected import userplugins.captcha.ReCaptcha -> module.plugins.captcha.ReCaptcha
09.05.2017 02:37:34 DEBUG     Redirected import userplugins.internal.SimpleHoster -> module.plugins.internal.SimpleHoster
09.05.2017 02:37:34 INFO      ADDON XFileSharing: Auto-discover new hosters
09.05.2017 02:37:34 DEBUG     ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|cramit\.in|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uploadrocket\.net|uptobox\.com|vidplay\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
09.05.2017 02:37:34 INFO      ADDON XFileSharing: Auto-discover new crypters
09.05.2017 02:37:34 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
09.05.2017 02:37:34 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
09.05.2017 02:37:34 INFO      pyLoad is up and running
09.05.2017 02:37:35 INFO      ADDON UpdateManager: pyLoad is up to date!
09.05.2017 02:37:35 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
09.05.2017 02:37:35 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
09.05.2017 02:37:35 INFO      ADDON UpdateManager: All plugins are up to date!
09.05.2017 02:37:36 INFO      ACCOUNT RealdebridCom: Loading hoster list for user `**************`...
09.05.2017 02:37:36 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/hosts/domains | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
09.05.2017 02:37:36 DEBUG     ACCOUNT RealdebridCom: Hoster list for user `**************`: [u'ajihezo.info', u'alfafile.net', u'alterupload.com', u'anafile.com', u'auroravid.to', u'ay8ou8ohth.com', u'bigfile.to', u'bitvid.sx', u'bojem3a.info', u'canalplus.fr', u'catshare.net', u'cbs.com', u'chouhaa.info', u'cjoint.net', u'clicknupload.com', u'clicknupload.link', u'clicknupload.me', u'cloudtime.to', u'dailymotion.com', u'datafile.com', u'datafilehost.com', u'datei.to', u'depfile.com', u'desfichiers.com', u'dfichiers.com', u'dfpan.com', u'divxstage.eu', u'divxstage.to', u'dix3.com', u'dl4free.com', u'easybytez.com', u'exashare.com', u'extmatrix.com', u'faststore.org', u'filefactory.com', u'fileflyer.com', u'filemarkets.com', u'fileover.net', u'filerio.com', u'filerio.in', u'filesabc.com', u'filesflash.com', u'filesflash.net', u'filesmonster.com', u'fivexpan.com', u'fourshared.com', u'free.fr', u'gboxes.com', u'gigapeta.com', u'gigasize.com', u'gulfup.com', u'hulkshare.com', u'i-filez.com', u'icerbox.com', u'k2s.cc', u'k2share.cc', u'keep2s.cc', u'keep2share.cc', u'kingfiles.net', u'load.to', u'mediafire.com', u'mega.co.nz', u'mega.nz', u'megadl.fr', u'mesfichiers.org', u'mightyupload.com', u'movshare.net', u'nitroflare.com', u'novamov.com', u'nowdownload.sx', u'nowdownload.sx', u'nowdownload.sx', u'nowdownload.sx', u'nowdownload.sx', u'nowdownload.sx', u'nowdownload.sx', u'nowdownload.sx', u'nowvideo.sx', u'nowvideo.sx', u'nowvideo.sx', u'nowvideo.sx', u'nowvideo.sx', u'nowvideo.sx', u'oboom.com', u'ohbuegh3ev.com', u'onefichier.com', u'openload.co', u'openload.io', u'ozofiles.com', u'piecejointe.net', u'pjointe.com', u'radiotunes.com', u'rapidgator.net', u'rarefile.net', u'real-debrid.com', u'redbunker.net', u'redtube.com', u'rockfile.eu', u'rutube.ru', u'salefiles.com', u'scribd.com', u'sendspace.com', u'share-online.biz', u'sikafika.info', u'sky.fm', u'solidfiles.com', u'soundcloud.com', u'streamin.to', u'tenvoi.com', u'thevideo.me', u'turbobit.net', u'tusfiles.net', u'two4uploading.com', u'twoshared.com', u'uloz.to', u'ulozto.net', u'ulozto.sk', u'unibytes.com', u'uplea.com', u'upload.af', u'upload.mn', u'uploadable.ch', u'uploadc.ch', u'uploadc.com', u'uploaded.to', u'uploaded.to', u'uploading.com', u'uploading.site', u'uploadrocket.net', u'uploadx.link', u'uploadx.org', u'upstore.net', u'uptobox.com', u'uptostream.com', u'userporn.com', u'userscloud.com', u'veevr.com', u'videoweed.es', u'vimeo.com', u'voodaith7e.com', u'wholecloud.net', u'wipfiles.net', u'worldbytez.com', u'youporn.com', u'youtube.com', u'youwatch.org', u'yunfile.com', u'zippyshare.com']
09.05.2017 02:37:36 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/hosts/domains | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
09.05.2017 02:37:36 DEBUG     ACCOUNT RealdebridCom: Overwritten hosters: BigfileTo, CatShareNet, ClicknuploadCom, DailymotionCom, DatafileCom, DateiTo, EasybytezCom, ExashareCom, FilefactoryCom, FilerioCom, FourSharedCom, GigapetaCom, Keep2ShareCc, KingfilesNet, LoadTo, MediafireCom, MegaCoNz, NitroflareCom, NowDownloadSx, NowVideoSx, OboomCom, OneFichierCom, OpenloadIo, RapidgatorNet, RarefileNet, RedtubeCom, RockfileEu, SendspaceCom, ShareonlineBiz, SolidfilesCom, SoundcloudCom, TurbobitNet, TusfilesNet, TwoSharedCom, UlozTo, UnibytesCom, UpleaCom, UploadedTo, UploadingCom, UploadrocketNet, UpstoreNet, UptoboxCom, UserscloudCom, VimeoCom, YoupornCom, YoutubeCom, ZippyshareCom
09.05.2017 02:37:36 INFO      ACCOUNT RealdebridCom: Hosters not overwritten: real-debrid.com
09.05.2017 02:37:36 DEBUG     ACCOUNT RealdebridCom: New hosters: ajihezo.info, alfafile.net, alterupload.com, anafile.com, auroravid.to, ay8ou8ohth.com, bitvid.sx, bojem3a.info, canalplus.fr, cbs.com, chouhaa.info, cjoint.net, clicknupload.link, clicknupload.me, cloudtime.to, datafilehost.com, depfile.com, desfichiers.com, dfichiers.com, dfpan.com, divxstage.eu, divxstage.to, dix3.com, dl4free.com, extmatrix.com, faststore.org, fileflyer.com, filemarkets.com, fileover.net, filerio.in, filesabc.com, filesflash.com, filesflash.net, filesmonster.com, fivexpan.com, free.fr, gboxes.com, gigasize.com, gulfup.com, hulkshare.com, i-filez.com, icerbox.com, k2s.cc, k2share.cc, keep2s.cc, mega.nz, megadl.fr, mesfichiers.org, mightyupload.com, movshare.net, novamov.com, ohbuegh3ev.com, openload.co, ozofiles.com, piecejointe.net, pjointe.com, radiotunes.com, redbunker.net, rutube.ru, salefiles.com, scribd.com, sikafika.info, sky.fm, streamin.to, tenvoi.com, thevideo.me, two4uploading.com, ulozto.net, ulozto.sk, upload.af, upload.mn, uploadable.ch, uploadc.ch, uploadc.com, uploading.site, uploadx.link, uploadx.org, uptostream.com, userporn.com, veevr.com, videoweed.es, voodaith7e.com, wholecloud.net, wipfiles.net, worldbytez.com, youwatch.org, yunfile.com
09.05.2017 02:37:36 DEBUG     ACCOUNT RealdebridCom: Pattern: https?://((?:www\.|s\d+\.)?real-debrid\.com/dl?/|[\w^_]\.rdb\.so/d/)[\w^_]+|.*(?P<DOMAIN>ajihezo\.info|alfafile\.net|alterupload\.com|anafile\.com|auroravid\.to|ay8ou8ohth\.com|bitvid\.sx|bojem3a\.info|canalplus\.fr|cbs\.com|chouhaa\.info|cjoint\.net|clicknupload\.link|clicknupload\.me|cloudtime\.to|datafilehost\.com|depfile\.com|desfichiers\.com|dfichiers\.com|dfpan\.com|divxstage\.eu|divxstage\.to|dix3\.com|dl4free\.com|extmatrix\.com|faststore\.org|fileflyer\.com|filemarkets\.com|fileover\.net|filerio\.in|filesabc\.com|filesflash\.com|filesflash\.net|filesmonster\.com|fivexpan\.com|free\.fr|gboxes\.com|gigasize\.com|gulfup\.com|hulkshare\.com|i-filez\.com|icerbox\.com|k2s\.cc|k2share\.cc|keep2s\.cc|mega\.nz|megadl\.fr|mesfichiers\.org|mightyupload\.com|movshare\.net|novamov\.com|ohbuegh3ev\.com|openload\.co|ozofiles\.com|piecejointe\.net|pjointe\.com|radiotunes\.com|redbunker\.net|rutube\.ru|salefiles\.com|scribd\.com|sikafika\.info|sky\.fm|streamin\.to|tenvoi\.com|thevideo\.me|two4uploading\.com|ulozto\.net|ulozto\.sk|upload\.af|upload\.mn|uploadable\.ch|uploadc\.ch|uploadc\.com|uploading\.site|uploadx\.link|uploadx\.org|uptostream\.com|userporn\.com|veevr\.com|videoweed\.es|voodaith7e\.com|wholecloud\.net|wipfiles\.net|worldbytez\.com|youwatch\.org|yunfile\.com).*
09.05.2017 02:37:40 INFO      ADDON ClickNLoad: Proxy listening on **************

**Comment by GammaC0de** [comment]
>DEBUG ACCOUNT RealdebridCom: BigfileTo, CatShareNet, ClicknuploadCom, ...
>INFO ACCOUNT RealdebridCom: Hosters not overwritten: real-debrid.com
>DEBUG ACCOUNT RealdebridCom: Pattern: 

Seems like normal operation

**Comment by GammaC0de** [comment]
News?

**Comment by Okanami** [comment]
Everything work, except the "'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)"

I used "é" and "à" in the folder name, i changed the name and then, no more error :p

**Comment by GammaC0de** [comment]
I this is the same issue as in https://github.com/pyload/pyload/issues/2804#issuecomment-299901244, read the solution there.

Closing...
