### ISSUE TITLE
FileHoster Support Req: uploadgig.com

### ISSUE THREAD

**Issue by h1ghju1ce** [pyload/pyload#2844]
Its cheaper than RapidGator, NitroFlare , I rushed in and bought premium THEN thought to look in the supported hoster list in pyload  :-( 

Would be grateful if this could be added to the hosters list please  :)

Hey maybe you should start a Patreon, so people that contribute could decide what features/fixes they'd like looked at?

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.
