### ISSUE TITLE
Shortening of long file names brakes the download of multi-part archives 

### ISSUE THREAD

**Issue by nik1a** [pyload/pyload#2845]
When a filename is to long pyload seems to shorten it.
As a result when downloading a multipart archives (longfilename.part1.rar, longfilename.part2.rar) it downloads only one part. renaming it to longfile...rar and skips the other.
Related to this? https://github.com/pyload/pyload/issues/623

**Comment by GammaC0de** [comment]
How long exactly?

Sample URL(s) please.

**Comment by nik1a** [comment]
After some more testing it seems to be plugin(or site) related issue.
https://userscloud.com/lcv9vfrqo5tv
https://userscloud.com/mccev3hldmj3 

They truncate the name in the title(h2) and if that is where pyload takes the name for the file...
