### ISSUE TITLE
Bigfile.To - Direct Download Link not found

### ISSUE THREAD

**Issue by klode82** [pyload/pyload#2846]
I'm again a new problem with pyload 0.4.9 (even with Linux version as with Windows version).
I've get the win.zip version, then I've downloaded the new package for plugins (plugins-stable.zip), then I've overwritten the plugins folder.

Now, I've added a set of links from BigFile.to, and I've used my account for download that files.

So, there is the log of debug_report created by pyload self.

[https://pastebin.com/cPfgDbPC](url)

thanks in advantage.

**Comment by GammaC0de** [comment]
This URL works fine here, please read #2000 for installation instructions.

**Comment by klode82** [comment]
thanks for your supply.
However, I've used the 0.4.9 version of pyload, then I've overwritten the plugins from here [https://github.com/pyload/plugins](url), but nothing.
The version of UpdateManager.py you have linked on #2000 is version 0.16, the version I've got with installation is 1.17.
the file with extension .pyc maybe must be removed?

**Comment by GammaC0de** [comment]
Start pyLoad from the console with `python pyLoadCore.py -d`, start the download and paste here the log from the console.

**Comment by klode82** [comment]
thanks for your supply
this is the pastebin link to debug: [https://pastebin.com/S9HqEqA8](url)

**Comment by GammaC0de** [comment]
There should be a `response.dump` file on your pyload's working directory. please send this file.

**Comment by klode82** [comment]
This is the response dump generated.

[pyload_response_dump.tar.gz](https://github.com/pyload/pyload/files/993436/pyload_response_dump.tar.gz)

**Comment by GammaC0de** [comment]
OK, I see that you have a premium account.

This seems to work fine with free download (please test).

I will need account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Will close if no response...

**Comment by GammaC0de** [comment]
No response, closing.
