### ISSUE TITLE
uptobox premium account not detected

### ISSUE THREAD

**Issue by zechrisd** [pyload/pyload#2847]
I subscribed a premium account on uptobox today but it's not valid on my pyload

123 14.05.2017 18:05:45 DEBUG UptoboxCom: Account Info: {'premium': False, 'leechtraffic': None, 'validuntil': None, 'trafficleft': None}

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by zechrisd** [comment]
thx, mail sent :)

**Comment by GammaC0de** [comment]
Please remove the account, restart pyload and then re-add the account.

**Comment by zechrisd** [comment]
Premium account still not recognized after delete restart and add (done twice)

**Comment by GammaC0de** [comment]
Ok,
1. Remove the account
2. Stop pyload
3. Start pyload from the console with `python pyLoadCore.py -d`.
4. Re-add the account.
5. Paste the log from the console (don't forget to add tripple \`\`\` in the start and the end so it will be diplayed correctly)

**Comment by zechrisd** [comment]
'''15.05.2017 20:25:15 INFO      pyLoad is up and running
15.05.2017 20:25:17 DEBUG     RestartFailed: Restart failed downloads
15.05.2017 20:25:56 DEBUG     Redirected import module.plugins.accounts.UptoboxCom -> userplugins.accounts.UptoboxCom
15.05.2017 20:25:56 DEBUG     Redirected import module.plugins.internal.XFSAccount -> userplugins.internal.XFSAccount
15.05.2017 20:25:59 DEBUG     UptoboxCom: Scheduled Account refresh for chris9184 in 0 seconds.
15.05.2017 20:26:03 DEBUG     UptoboxCom: Get Account Info for chris9184
15.05.2017 20:26:03 DEBUG     UptoboxCom: Scheduled Account refresh for chris9184 in 0 seconds.
15.05.2017 20:26:06 DEBUG     UptoboxCom: VALID_UNTIL_PATTERN not found
15.05.2017 20:26:06 DEBUG     UptoboxCom: TRAFFIC_LEFT_PATTERN not found
15.05.2017 20:26:06 DEBUG     UptoboxCom: LEECH_TRAFFIC_PATTERN not found
15.05.2017 20:26:06 DEBUG     UptoboxCom: Account Info: {'premium': False, 'leechtraffic': None, 'validuntil': None, 'trafficleft': None}
15.05.2017 20:26:09 DEBUG     UptoboxCom: Scheduled Account refresh for chris9184 in 0 seconds.
15.05.2017 20:26:13 DEBUG     UptoboxCom: Get Account Info for chris9184
15.05.2017 20:26:13 DEBUG     UptoboxCom: Scheduled Account refresh for chris9184 in 0 seconds.
15.05.2017 20:26:16 DEBUG     UptoboxCom: VALID_UNTIL_PATTERN not found
15.05.2017 20:26:16 DEBUG     UptoboxCom: TRAFFIC_LEFT_PATTERN not found
15.05.2017 20:26:16 DEBUG     UptoboxCom: LEECH_TRAFFIC_PATTERN not found
15.05.2017 20:26:16 DEBUG     UptoboxCom: Account Info: {'premium': False, 'leechtraffic': None, 'validuntil': None, 'trafficleft': None}
15.05.2017 20:26:19 DEBUG     UptoboxCom: Scheduled Account refresh for chris9184 in 0 seconds.
15.05.2017 20:26:23 DEBUG     UptoboxCom: Get Account Info for chris9184
15.05.2017 20:26:23 DEBUG     UptoboxCom: Scheduled Account refresh for chris9184 in 0 seconds.
15.05.2017 20:26:26 DEBUG     UptoboxCom: VALID_UNTIL_PATTERN not found
15.05.2017 20:26:26 DEBUG     UptoboxCom: TRAFFIC_LEFT_PATTERN not found
15.05.2017 20:26:26 DEBUG     UptoboxCom: LEECH_TRAFFIC_PATTERN not found
15.05.2017 20:26:26 DEBUG     UptoboxCom: Account Info: {'premium': False, 'leechtraffic': None, 'validuntil': None, 'trafficleft': None}'''

**Comment by GammaC0de** [comment]
can you edit [UptoboxCom.py#L21](https://github.com/pyload/pyload/blob/stable/module/plugins/accounts/UptoboxCom.py#L21)
from:
```
 PLUGIN_URL = "http://uptobox.com/"
```

to:
```
 PLUGIN_URL = "https://uptobox.com/"
```

And see if it helps?

**Comment by zechrisd** [comment]
in which path should be this file ? pyload/module/plugins/accounts ?
I didn't find it

**Comment by GammaC0de** [comment]
Most likely under userplugins/accounts

**Comment by zechrisd** [comment]
I found files with same name but not the same content
pi@raspberrypi ~ $ sudo find / -name UptoboxCom*
/home/pi/.pyload/userplugins/hoster/UptoboxCom.py
/home/pi/.pyload/userplugins/hoster/UptoboxCom.pyc
/home/pi/.pyload/userplugins/accounts/UptoboxCom.py
/home/pi/.pyload/userplugins/accounts/UptoboxCom.pyc
/home/pi/.pyload/tmp/UptoboxCom
/root/.pyload/userplugins/hoster/UptoboxCom.py
/root/.pyload/userplugins/accounts/UptoboxCom.py

**Comment by GammaC0de** [comment]
/home/pi/.pyload/userplugins/accounts/UptoboxCom.py

**Comment by zechrisd** [comment]
ok file modified but same result :(

**Comment by GammaC0de** [comment]
Maybe /root/.pyload/userplugins/accounts/UptoboxCom.py

**Comment by zechrisd** [comment]
this file contains 
'''# -*- coding: utf-8 -*-
from module.plugins.internal.XFSPAccount import XFSPAccount

class UptoboxCom(XFSPAccount):
    __name__ = "UptoboxCom"
    __version__ = "0.01"
    __type__ = "account"
    __description__ = """DDLStorage.com account plugin"""
    __author_name__ = ("zoidberg")
    __author_mail__ = ("zoidberg@mujmail.cz")

    MAIN_PAGE = "https://uptobox.com/"'''

**Comment by GammaC0de** [comment]
Do you know how to edit python files?

Edit [XFSAccount.py#L84](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/XFSAccount.py#L84) (it should be located in /home/pi/.pyload/userplugins/internal/XFSAccount.py)
and add these two lines after line 84 (`self.data = self.load(self.PLUGIN_URL,`):
```python
        with open("request.html", "wb") as f:
            f.write(self.data)
```

Then restart pyload (as normal service) and re-add the account.

After that there should be "request.html" file under /home/pi/.pyload/, attach it here.

**Comment by zechrisd** [comment]
Can't find your line 84 in my file XFSAccount.py
(I searched "self.data" and :84 with vi)

**Comment by GammaC0de** [comment]
Go to `http://<PYLOAD_IP>/info` and see where is `Config Folder`.
It should be located under `<Config Folder>\userplugins\internal`

**Comment by zechrisd** [comment]
Dossier de Configuration:	/home/pi/.pyload

**Comment by GammaC0de** [comment]
I must ask you, is this a new installation?

**Comment by zechrisd** [comment]
No I installed pyload 2 or 3 years ago

**Comment by GammaC0de** [comment]
OK, so what is the version of:
1. /home/pi/.pyload/userplugins/internal/XFSAccount.py
2. /home/pi/.pyload/userplugins/accounts/UptoboxCom.py

**Comment by zechrisd** [comment]
Pyload v.0.4.9
Where can I see version of these 2 files ?
How can I run UpdateManager ?

**Comment by zechrisd** [comment]
In the file plugins.conf UpdateManager seems to be activated
UpdateManager - "UpdateManager":
        bool autorestart : "Auto-restart pyLoad when required" = True
        int checkinterval : "Check interval in hours" = 6
        bool checkperiod : "Check for updates periodically" = True
        bool activated : "Activated" = True
        bool nodebugupdate : "Don't update plugins in debug mode" = False
        bool reloadplugins : "Monitor plugin code changes in debug mode" = True
        bool checkonstart : "Check for updates on startup" = True

**Comment by GammaC0de** [comment]
```bash
cat /home/pi/.pyload/userplugins/internal/XFSAccount.py | grep __version__
cat /home/pi/.pyload/userplugins/accounts/UptoboxCom.py  | grep __version__
```

UpdateManager may be active but does it function correctly?
Enable debug mode and then restart pyLoad and attach the log file to see.

**Comment by zechrisd** [comment]
pi@raspberrypi ~ $ cat /home/pi/.pyload/userplugins/internal/XFSAccount.py | grep __version__
    __version__ = "0.36"
pi@raspberrypi ~ $ cat /home/pi/.pyload/userplugins/accounts/UptoboxCom.py  | grep __version__
    __version__ = "0.08"

**Comment by GammaC0de** [comment]
Your plugins are out of date...

**Comment by zechrisd** [comment]
477	16.05.2017 20:04:42	DEBUG	RestartFailed: Restart failed downloads
476	16.05.2017 20:04:40	INFO	pyLoad is up and running
475	16.05.2017 20:04:40	DEBUG	XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?P[\w\-.^_]{3,63}(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:user|folder)s?/\w+
474	16.05.2017 20:04:40	INFO	XFileSharingPro: Handling any crypter I can!
473	16.05.2017 20:04:40	DEBUG	XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?P[\w\-.^_]{3,63}(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
472	16.05.2017 20:04:40	INFO	XFileSharingPro: Handling any hoster I can!
471	16.05.2017 20:04:40	INFO	ClickAndLoad: Proxy listening on 127.0.0.1:9666
470	16.05.2017 20:04:40	INFO	ExtractArchive: Activated UnRar 4.10|UnZip (python 2.7.3)
469	16.05.2017 20:04:40	DEBUG	Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
468	16.05.2017 20:04:40	INFO	ExtractArchive: No SevenZip installed
467	16.05.2017 20:04:40	DEBUG	Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
466	16.05.2017 20:04:39	DEBUG	Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
465	16.05.2017 20:04:39	DEBUG	RestartFailed: Invalid interval value, kept current
464	16.05.2017 20:04:39	INFO	Activating Plugins...
463	16.05.2017 20:04:39	DEBUG	UptoboxCom: Account Info: {'premium': False, 'leechtraffic': None, 'validuntil': None, 'trafficleft': None}
462	16.05.2017 20:04:39	DEBUG	UptoboxCom: LEECH_TRAFFIC_PATTERN not found
461	16.05.2017 20:04:39	DEBUG	UptoboxCom: TRAFFIC_LEFT_PATTERN not found
460	16.05.2017 20:04:39	DEBUG	UptoboxCom: VALID_UNTIL_PATTERN not found
459	16.05.2017 20:04:36	DEBUG	UptoboxCom: Get Account Info for chris9184
458	16.05.2017 20:04:32	DEBUG	Redirected import module.plugins.internal.XFSAccount -> userplugins.internal.XFSAccount
457	16.05.2017 20:04:32	DEBUG	Redirected import module.plugins.accounts.UptoboxCom -> userplugins.accounts.UptoboxCom
456	16.05.2017 20:04:32	INFO	Activating Accounts...
455	16.05.2017 20:04:32	INFO	Starting builtin webserver: 192.168.0.10:8000
454	16.05.2017 20:04:32	WARNING	Of course you need to be familiar with linux and know how to compile software
453	16.05.2017 20:04:32	WARNING	Copy the boern.so to module/lib folder or use setup.py install
452	16.05.2017 20:04:32	WARNING	You need to download and compile bjoern, https://github.com/jonashaag/bjoern
451	16.05.2017 20:04:32	ERROR	Error importing lightweight server: No module named bjoern
450	16.05.2017 20:04:32	INFO	Free space: 151.00 GiB
449	16.05.2017 20:04:32	WARNING	SSL certificates not found.
448	16.05.2017 20:04:30	INFO	Démarre ThriftBackend: 0.0.0.0:7227
447	16.05.2017 20:04:30	INFO	Temps de téléchargement : True
446	16.05.2017 20:04:30	INFO	Plugins désactivés: AlldebridCom, AndroidPhoneNotify, AntiVirus, CaptchaBrotherhood, DeathByCaptcha, DebridItaliaCom, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, FastixRu, FreeWayMe, HotFolder, IRCInterface, JustPremium, LinkdecrypterCom, LinksnappyCom, MegaDebridEu, MergeFiles, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumTo, PremiumizeMe, PutdriveCom, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, SmoozedCom, UnrestrictLi, WindowsPhoneNotify, XMPPInterface, ZeveraCom
445	16.05.2017 20:04:30	INFO	Plugins activés: BypassCaptcha, Captcha9Kw, CaptchaTrader, Checksum, ClickAndLoad, DeleteFinished, ExtractArchive, ImageTyperz, RestartFailed, UnSkipOnFail, XFileSharingPro
444	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
443	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
442	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
441	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.ImageTyperz -> userplugins.hooks.ImageTyperz
440	16.05.2017 20:04:30	ERROR	Erreur d'importation UpdateManager : No module named Addon
439	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
438	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
437	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
436	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
435	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.Checksum -> userplugins.hooks.Checksum
434	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.Captcha9Kw -> userplugins.hooks.Captcha9Kw
433	16.05.2017 20:04:30	WARNING	Impossible d'activer ExternalScripts
432	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
431	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.BypassCaptcha -> userplugins.hooks.BypassCaptcha
430	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.RestartFailed -> userplugins.hooks.RestartFailed
429	16.05.2017 20:04:30	DEBUG	Redirected import module.plugins.hooks.DeleteFinished -> userplugins.hooks.DeleteFinished
428	16.05.2017 20:04:30	DEBUG	created index of plugins
427	16.05.2017 20:04:25	DEBUG	Remote activated: True
426	16.05.2017 20:04:25	INFO	Utilisation du dossier principal : /home/pi/.pyload
425	16.05.2017 20:04:25	INFO	Démarrage pyLoad 0.4.9
424	16.05.2017 20:04:21	INFO	Received Quit signal
423	16.05.2017 20:04:21	DEBUG	Deleting old pidfile pyload.pid
422	16.05.2017 20:04:21	INFO	shutting down...

**Comment by zechrisd** [comment]
Why UpdateManager can't update my plugins ?

**Comment by GammaC0de** [comment]
From `http://<PYLOAD_IP>/info`, what is the valuse of "Installation Folder"?

**Comment by zechrisd** [comment]
Dossier d'Installation:	/usr/share/pyload

**Comment by GammaC0de** [comment]
`cat /usr/share/pyload/module/plugins/hooks/UpdateManager.py |  grep __version__`

**Comment by zechrisd** [comment]
pi@raspberrypi /usr/share/pyload $ cat /usr/share/pyload/module/plugins/hooks/UpdateManager.py | grep __version__
    __version__ = "0.11"

**Comment by GammaC0de** [comment]
1. Stop pyLoad
2. Delete `/home/pi/.pyload/userplugins` directory
3. Replace `/usr/share/pyload/module/plugins/hooks/UpdateManager.py` with https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/78f10968869e887d802a75a9ef6b89628d0d5ff9/UpdateManager.py
4. Start pyLoad.
5. Wait about 5 minutes.
6. Check UptoboxCom account status.

**Comment by zechrisd** [comment]
directory have been recreated with only file "__init__.py"
On page settings I can now see : 
An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/usr/share/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/usr/share/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/usr/share/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/usr/share/pyload/module/utils.py", line 165, in new
return func(*args)
File "/usr/share/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/usr/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

**Comment by GammaC0de** [comment]
Try deleting (or backup) `/home/pi/.pyload/accounts.conf`  and then proceed from step 4 above.

**Comment by zechrisd** [comment]
Ok, now it works better but when I want to add my uptobox premium account I have a message "error occured"

**Comment by GammaC0de** [comment]
Check the log to see if the update process has finished.

**Comment by zechrisd** [comment]
16.05.2017 21:05:49	ERROR	Error importing UptoboxCom: No module named misc

**Comment by GammaC0de** [comment]
Try this time deleting `/home/pi/.pyload/userplugins` and `/home/pi/.pyload/accounts.conf`, proceed again from step 4 and watch the log for `ADDON UpdateManager: All plugins are up to date!` message.

**Comment by zechrisd** [comment]
Great it works my account is set as premium ! Thanks a lot !!!

**Comment by GammaC0de** [comment]
👍
