### ISSUE TITLE
Rapidgator Plugin will not trigger reconnect

### ISSUE THREAD

**Issue by Franzl123** [pyload/pyload#2848]
WARNING	HOSTER RapidgatorNet[12]: You have reached your hourly downloads limit 
DEBUG		HOSTER RapidgatorNet[12]: WAIT set to timestamp 1495288270.550295 | Previous waitUntil: 0.000000 
DEBUG		HOSTER RapidgatorNet[12]: RECONNECT not required | Previous wantReconnect: False
INFO		HOSTER RapidgatorNet[12]: Waiting 1 hours...

reconnect plugin is activated, of course, waiting time in rapidgator plugin is set to 1 min (for test, default is 10 min)

edit: no other downloads!
edit²: is it possible to trigger an reconnect manually?

**Comment by GammaC0de** [comment]
> no other downloads

What do you mean by that?

**Comment by GammaC0de** [comment]
RapidgatorNet allows to download only one (this is a guess) file per day even with a normal browser.

RapidgatorNet can now detect this situation and fail the download.

**Comment by Franzl123** [comment]
> What do you mean by that?

this was the only download running in that moment (no other download prevent the reconnect)


> RapidgatorNet allows to download only one (this is a guess) file per day even with a normal browser.

no, thats not correct. if you download a file (filesize eg. 500mb), there is a waiting time of 2 hours (i have that time from jdownloader). if you do a reconnect, you can start a new download immedialy

**Comment by GammaC0de** [comment]
For me it says "You can`t download more than 1 file at a time in free mode" and I cannot download anything for one day.
After one day I tried to download again, this time with firefox.
I could download one file and then I got the same message again even though I used Firefox for thre download.

I will try to investigate some more and see what can be done (reconnect too), but I can't promise.

**Comment by GammaC0de** [comment]
Please check now and confirm that reconnect works.
