### ISSUE TITLE
katfile.com hoster 

### ISSUE THREAD

**Issue by Ulu1** [pyload/pyload#2852]
Hi, Is it possible to writekatfile.com hoster plugin? (plaese)

**Comment by GammaC0de** [comment]
Free download only.
If you have premium account, please say so.

**Comment by advorsky73** [comment]
Is there already a premium implementation available? I checked and could not enter premium account credentials into pyload as it doesnt give me katfile as a choice...

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by advorsky73** [comment]
information sent via email as requested 👍

**Comment by advorsky73** [comment]
Entering Katfile credentials does work now, however the account page shows the following:
Plugin: KatfileCom - Name: ****** (As sent to you) - Status:Valid - Premium: No - Valid Until: not available - Traffic left: not available.
Any ideas what went wrong?

**Comment by advorsky73** [comment]
Today it started working! Thanks a lot!
