### ISSUE TITLE
HTTPS authentication plugins ? 

### ISSUE THREAD

**Issue by jibedo** [pyload/pyload#2854]
Hello 
I need help for download on private server with account. (normal https connection) 

like -> https://user:password@url.com:port/link

Thanks

**Comment by GammaC0de** [comment]
Go to pyLoad's configuration -> Accounts -> Add account
* Select Http account type
* In the username type url.com:port
* In the password type user:password

![capture](https://cloud.githubusercontent.com/assets/11036551/26654847/f48c547c-4660-11e7-91e7-9ac0ef9b79f9.PNG)
