### ISSUE TITLE
UsersCloud.com not work

### ISSUE THREAD

**Issue by MrcRel** [pyload/pyload#2861]
I have try to download from this host, but download not start, and file name is show incorrect.

Url (expire in 24h):
https://userscloud.com/mwkw5e85xw8r

**Comment by Velociraptor85** [comment]
@MrcRel please explain in more detail and/or include some debug output

**Comment by MrcRel** [comment]
LOG:

>INFO	ADDON UnSkipOnFail: No duplicates found
>INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: mwkw5e85xw8r (pid:47)
>WARNING	Download failed: mwkw5e85xw8r | TEXTAREA F1 not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>WARNING	CAPTCHA XFileSharing[1068]: UserscloudCom | ReCaptcha | Key pattern not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing as free download...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing url: https://userscloud.com/mwkw5e85xw8r
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link status: online
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link size: N/D
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link name: mwkw5e85xw8r
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Grabbing link >info...
>WARNING	HOSTER XFileSharing[1068]: UserscloudCom | Plugin may be unstable
>INFO	Download starts: mwkw5e85xw8r
>INFO	Download restarted: mwkw5e85xw8r | TEXTAREA F1 not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Waiting 1 seconds...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>WARNING	CAPTCHA XFileSharing[1068]: UserscloudCom | ReCaptcha | Key pattern not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing as free download...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing url: https://userscloud.com/mwkw5e85xw8r
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link status: online
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link size: N/D
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link name: mwkw5e85xw8r
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Grabbing link >info...
>WARNING	HOSTER XFileSharing[1068]: UserscloudCom | Plugin may be unstable
>INFO	Download starts: mwkw5e85xw8r
>INFO	Download restarted: mwkw5e85xw8r | TEXTAREA F1 not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Waiting 1 seconds...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>WARNING	CAPTCHA XFileSharing[1068]: UserscloudCom | ReCaptcha | Key pattern not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing as free download...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing url: https://userscloud.com/mwkw5e85xw8r
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link status: online
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link size: N/D
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link name: mwkw5e85xw8r
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Grabbing link >info...
>WARNING	HOSTER XFileSharing[1068]: UserscloudCom | Plugin may be unstable
>INFO	Download starts: mwkw5e85xw8r
>INFO	Download restarted: mwkw5e85xw8r | TEXTAREA F1 not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Waiting 1 seconds...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>WARNING	CAPTCHA XFileSharing[1068]: UserscloudCom | ReCaptcha | Key pattern not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing as free download...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing url: https://userscloud.com/mwkw5e85xw8r
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link status: online
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link size: N/D
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link name: mwkw5e85xw8r
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Grabbing link >info...
>WARNING	HOSTER XFileSharing[1068]: UserscloudCom | Plugin may be unstable
>INFO	Download starts: mwkw5e85xw8r
>INFO	Download restarted: mwkw5e85xw8r | TEXTAREA F1 not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Waiting 1 seconds...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>WARNING	CAPTCHA XFileSharing[1068]: UserscloudCom | ReCaptcha | Key pattern not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing as free download...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing url: https://userscloud.com/mwkw5e85xw8r
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link status: online
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link size: N/D
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link name: mwkw5e85xw8r 
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Grabbing link >info...
>WARNING	HOSTER XFileSharing[1068]: UserscloudCom | Plugin may be unstable
>INFO	Download starts: mwkw5e85xw8r
>INFO	Download restarted: mwkw5e85xw8r | TEXTAREA F1 not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Waiting 1 seconds...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>WARNING	CAPTCHA XFileSharing[1068]: UserscloudCom | ReCaptcha | Key pattern not found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing as free download...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | No errors found
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Checking for link errors...
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Processing url: https://userscloud.com/mwkw5e85xw8r
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link status: online
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link size: N/D
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Link name: mwkw5e85xw8r
>INFO	HOSTER XFileSharing[1068]: UserscloudCom | Grabbing link >info...
>WARNING	HOSTER XFileSharing[1068]: UserscloudCom | Plugin may be unstable
>INFO	Download starts: https://userscloud.com/mwkw5e85xw8r 

Example Url:
https://userscloud.com/0nu5oqrn0w8e

**Comment by GammaC0de** [comment]
@MrcRel You should disable the `XFileSharing` plugin and then it should work fine.
