### ISSUE TITLE
backin.net hoster

### ISSUE THREAD

**Issue by MrcRel** [pyload/pyload#2863]
Is it possible to write backin.net hoster plugin, please?

ex. http://backin.net/zt54rou5686n

**Comment by GammaC0de** [comment]
hoster is down...

**Comment by MrcRel** [comment]
Host is online:
[Screen](https://s4.postimg.org/or8pqz3fh/image.png)

**Comment by GammaC0de** [comment]
I cannot access the site, maybe there is some geo-ip filtering?
![capture](https://user-images.githubusercontent.com/11036551/27306366-057c2748-554e-11e7-848e-2386f3c312b8.PNG)
