### ISSUE TITLE
 HOSTER Keep2ShareCc issue Parse error: Unique-ID pattern not found

### ISSUE THREAD

**Issue by akfedux** [pyload/pyload#2865]
DEBUG	Redirected import module.plugins.hoster.Keep2ShareCc -> userplugins.hoster.Keep2ShareCc
INFO	Added package test containing 1 links
INFO	Download starts: http://keep2s.cc/file/0db382c69bbab/BADOVRMYANBONASTOC.part4.rar
DEBUG	HOSTER Keep2ShareCc[2046]: Plugin version: 0.36
DEBUG	HOSTER Keep2ShareCc[2046]: Plugin status: testing
WARNING	HOSTER Keep2ShareCc[2046]: Plugin may be unstable
DEBUG	Redirected import module.plugins.accounts.Keep2ShareCc -> userplugins.accounts.Keep2ShareCc
INFO	HOSTER Keep2ShareCc[2046]: Grabbing link info...
DEBUG	HOSTER Keep2ShareCc[2046]: Link info: {'status': 2, 'hash': {}, 'name': u'BADOVRMYANBONASTOC.part4.rar', 'url': u'https://k2s.cc/file/0db382c69bbab?force_old=1', 'pattern': {'S': u'1.4 GB', 'ID': u'0db382c69bbab', 'N': u'BADOVRMYANBONASTOC.part4.rar'}, 'size': 1503238553}
DEBUG	HOSTER Keep2ShareCc[2046]: Previous link info: {}
INFO	HOSTER Keep2ShareCc[2046]: Link name: BADOVRMYANBONASTOC.part4.rar
INFO	HOSTER Keep2ShareCc[2046]: Link size: 1.40 GiB (1503238553 bytes)
INFO	HOSTER Keep2ShareCc[2046]: Link status: online
INFO	HOSTER Keep2ShareCc[2046]: Processing url: http://keep2s.cc/file/0db382c69bbab/BADOVRMYANBONASTOC.part4.rar
INFO	HOSTER Keep2ShareCc[2046]: Looking for direct download link...
DEBUG	HOSTER Keep2ShareCc[2046]: LOAD URL https://k2s.cc/file/0db382c69bbab?force_old=1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
DEBUG	HOSTER Keep2ShareCc[2046]: Redirect #1 to: https://keep2s.cc/file/0db382c69bbab?force_old=1
DEBUG	HOSTER Keep2ShareCc[2046]: LOAD URL https://keep2s.cc/file/0db382c69bbab?force_old=1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
INFO	HOSTER Keep2ShareCc[2046]: Direct download link not found
DEBUG	HOSTER Keep2ShareCc[2046]: LOAD URL https://k2s.cc/file/0db382c69bbab?force_old=1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
INFO	HOSTER Keep2ShareCc[2046]: Processing as free download...
DEBUG	HOSTER Keep2ShareCc[2046]: LOAD URL https://k2s.cc/file/0db382c69bbab?force_old=1 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'slow_id': u'5a67a9ceff3fe', 'yt0': ''} | ref=True | just_header=False
WARNING	Download failed: BADOVRMYANBONASTOC.part4.rar | Parse error: Unique-ID pattern not found | Plugin may be out of date
DEBUG	All downloads processed

**Comment by kveiro** [comment]
This happens because the link of the form: keep2s.cc/file does not work with this:
URL_REPLACEMENTS = [(__pattern__ + ". *", "https://k2s.cc/file/\g<ID>?force_old=1")].
As a workaround, you need to manually replace it with
URL_REPLACEMENTS = [(__pattern__ + ". *", "https://keep2s.cc/file/\g<ID>?force_old=1")].
Then, of course, links like: k2s.cc will stop working.

Perhaps respected authors Walter Purcaro, or GammaC0de will make a universal solution.

**Comment by digimon04** [comment]
I also experienced the same issue. I tried a "k2s.cc" url but still got the error.

I believe keep2share has implemented the new site layout and the "?force_old" didn't work anymore

**Comment by kveiro** [comment]
Yes, the old design of the page has already been deleted and everything does not work anymore.
The developers took a break.

**Comment by pyblub** [comment]
For me it's the other way around. I had to replace **keep2s** with **k2s**, because I got the error "Parse error: Unique-ID pattern not found".

Changing the `URL_REPLACEMENTS`, works for me:
`URL_REPLACEMENTS = [(__pattern__ + ".*", "https://k2s.cc/file/\g<ID>")]`

**Comment by GammaC0de** [comment]
@pyblub Tested and works fine here, plugin version 0.38
