### ISSUE TITLE
DepositfilesCom issue fake offline

### ISSUE THREAD

**Issue by akfedux** [pyload/pyload#2866]
524	07.06.2017 11:30:49	INFO	Added package test containing 1 links
525	07.06.2017 11:30:49	DEBUG	Redirected import module.plugins.hoster.DepositfilesCom -> userplugins.hoster.DepositfilesCom
526	07.06.2017 11:30:50	INFO	Download starts: https://dfiles.eu/files/76w36h8qe
527	07.06.2017 11:30:50	DEBUG	HOSTER DepositfilesCom[2047]: Plugin version: 0.62
528	07.06.2017 11:30:50	DEBUG	HOSTER DepositfilesCom[2047]: Plugin status: testing
529	07.06.2017 11:30:50	WARNING	HOSTER DepositfilesCom[2047]: Plugin may be unstable
530	07.06.2017 11:30:50	DEBUG	Redirected import module.plugins.accounts.DepositfilesCom -> userplugins.accounts.DepositfilesCom
531	07.06.2017 11:30:50	INFO	HOSTER DepositfilesCom[2047]: Grabbing link info...
532	07.06.2017 11:30:58	DEBUG	HOSTER DepositfilesCom[2047]: Link info: {'status': 6, 'hash': {}, 'name': '76w36h8qe', 'url': u'https://dfiles.eu/files/76w36h8qe', 'pattern': {'ID': u'76w36h8qe'}, 'size': 0}
533	07.06.2017 11:30:58	DEBUG	HOSTER DepositfilesCom[2047]: Previous link info: {}
534	07.06.2017 11:30:58	INFO	HOSTER DepositfilesCom[2047]: Link name: 76w36h8qe
535	07.06.2017 11:30:58	INFO	HOSTER DepositfilesCom[2047]: Link size: N/D
536	07.06.2017 11:30:58	INFO	HOSTER DepositfilesCom[2047]: Link status: temporary offline
537	07.06.2017 11:30:58	WARNING	Download is temporary offline: 76w36h8qe
538	07.06.2017 11:30:58	DEBUG	All downloads processed

**Comment by BKPepe** [comment]
Hello,
I tried it now and it's online.

Even in log you can see: `Link status: temporary offline`
There is nothing what pyLoad team can do.

**Comment by akfedux** [comment]
Each added link is mistakenly detected. Got it?
