### ISSUE TITLE
Nopremiumpl

### ISSUE THREAD

**Issue by lavazza2017** [pyload/pyload#2867]
Hello, do you had problem with this hoster (nopremiumpl)? I try to start working on NAS (qnap), pyload is working but hoster can't start can you help me ?

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by lavazza2017** [comment]
problem is with hook which I can't activate :(. I still use this nopremium account in 3-9 computers so sorry but I can't afford to change password. Just give me a hint what to do.

**Comment by lavazza2017** [comment]
I created new account with 0,2 GB free transfer.  I sent to you

**Comment by GammaC0de** [comment]
>problem is with hook which I can't activate :(. I still use this nopremium account in 3-9 computers 

Please explain the problem in detail.

**Comment by lavazza2017** [comment]
In config in layer accounts, I picked nopremium, write my login and passowrd click submit and is added "
Plugin	         Name	Password 	Status	Premium	Valid until	
NoPremiumPl	 ****	         ******                valid	yes	         unlimited		

so this is ok, then i go to plugin layer picked nopremiumpl

and no icon or switch with activate.

When i try  download something use always with captha and no premium account

**Comment by GammaC0de** [comment]
After you successfully enter the account credentials, you should ready to go.

Please enable DEBUG mode, start a download and post the log here.

**Comment by lavazza2017** [comment]
21.06.2017 09:46:00	INFO	Starting pyLoad 0.4.9
572	21.06.2017 09:46:00	INFO	Using home directory: /share/CACHEDEV1_DATA/.qpkg/QPyload/CONFIG
573	21.06.2017 09:46:01	INFO	Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
574	21.06.2017 09:46:01	INFO	Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
575	21.06.2017 09:46:01	INFO	Downloadtime: True
576	21.06.2017 09:46:01	INFO	Starting ThriftBackend: 0.0.0.0:7227
577	21.06.2017 09:46:02	INFO	Starting builtin webserver: 0.0.0.0:8001
578	21.06.2017 09:46:02	INFO	Free space: 5.27 TiB
579	21.06.2017 09:46:02	INFO	Activating Accounts...
580	21.06.2017 09:46:02	INFO	ACCOUNT NoPremiumPl: Adding user `mic*******`...
581	21.06.2017 09:46:02	INFO	ACCOUNT NoPremiumPl: Login user `mic*******`...
582	21.06.2017 09:46:02	INFO	ACCOUNT NoPremiumPl: Grabbing account info for user `mic*******`...
583	21.06.2017 09:46:03	INFO	Activating Plugins...
584	21.06.2017 09:46:03	INFO	ADDON XFileSharing: Auto-discover new hosters
585	21.06.2017 09:46:03	INFO	ADDON XFileSharing: Auto-discover new crypters
586	21.06.2017 09:46:03	INFO	pyLoad is up and running
587	21.06.2017 09:46:03	INFO	ADDON UpdateManager: pyLoad is up to date!
588	21.06.2017 09:46:04	INFO	ADDON UpdateManager: All plugins are up to date!
589	21.06.2017 09:46:05	INFO	ACCOUNT NoPremiumPl: Loading hoster list for user `mic*******`...
590	21.06.2017 09:46:09	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
591	21.06.2017 09:46:12	INFO	Added package sciagaeni containing 1 links
592	21.06.2017 09:46:13	INFO	Download starts: http://rapidgator.net/file/61a810655f1f52d0f6422da760e1e750/SuperHideIP.3.6.2.2.rar.html
593	21.06.2017 09:46:13	WARNING	HOSTER RapidgatorNet[2]: Plugin may be unstable
594	21.06.2017 09:46:13	INFO	HOSTER RapidgatorNet[2]: Grabbing link info...
595	21.06.2017 09:46:14	INFO	HOSTER RapidgatorNet[2]: Link name: SuperHideIP.3.6.2.2.rar
596	21.06.2017 09:46:14	INFO	HOSTER RapidgatorNet[2]: Link size: 2.44 MiB (2558525 bytes)
597	21.06.2017 09:46:14	INFO	HOSTER RapidgatorNet[2]: Link status: online
598	21.06.2017 09:46:14	INFO	HOSTER RapidgatorNet[2]: Processing url: http://rapidgator.net/file/61a810655f1f52d0f6422da760e1e750/SuperHideIP.3.6.2.2.rar.html
599	21.06.2017 09:46:14	INFO	HOSTER RapidgatorNet[2]: Looking for direct download link...
600	21.06.2017 09:46:14	INFO	HOSTER RapidgatorNet[2]: Direct download link not found
601	21.06.2017 09:46:14	INFO	HOSTER RapidgatorNet[2]: Checking for link errors...
602	21.06.2017 09:46:14	INFO	HOSTER RapidgatorNet[2]: No errors found
603	21.06.2017 09:46:14	INFO	HOSTER RapidgatorNet[2]: Processing as free download...
604	21.06.2017 09:46:14	INFO	HOSTER RapidgatorNet[2]: Waiting 30 seconds...

**Comment by lavazza2017** [comment]
As u see plugin is not using nopremium but hoster where i download in this case RapidgatorNet

**Comment by GammaC0de** [comment]
@lavazza2017 This is a limitation of Nopremiumpl, it does not support all the hosters when using API .
`Hosting czasowo wyłączony z powodu problemów po stronie hostingu`

**Comment by GammaC0de** [comment]
Closing since this is a hoster limitation.
