### ISSUE TITLE
Download speed slow Pyload Share Online

### ISSUE THREAD

**Issue by fila612** [pyload/pyload#2870]
Hi there,

i've an issue regarding using pyload on my sinology DS213+ with premium account share online.

on my internet connection (200MBit) i have not max download since couple of weeks.
i tested the connection from NAS with wget on an iso file (ubuntu) and there are around about 20MB/S.
in pyload with share online i have round about 3MB/s.
same download from SO in downloader in my iMac runs with 20MB/s.
all devices are connected via wire, no wireless LAN .)

i've checked the plugins and it seems they are alle up to date (SO-plugin is v 0.66).

any ideas what can be checked furthermore or what are the issue?

sorry for my bad english.

regards
Lars

**Comment by GammaC0de** [comment]
Does the problem exists with other plugins or just with SO?

**Comment by fila612** [comment]
I'm not sure, cause i have only SO premium access.

**Comment by GammaC0de** [comment]
>i tested the connection from NAS with wget on an iso file (ubuntu) and there are around about 20MB/S

The download test was from SO too?

**Comment by fila612** [comment]
The test regarding SO (dlc file) was on the Synology NAS with pyload, result  3MB/s, the same dlc on my Mac with jdownloader speeds up to 20MB/s. both devices are connected directly to my router. (1GBit/s on all interfaces).
so in my point of view the SO Servers are not the problem.
2nd test was the general speed on my NAS, to check this i tested a download from internet in th bash via "wget" an iso file from ubuntu website (http). there i got the expected 20MB/s.
So on the result of the ISO file test, a assume, that there are no technical issues regarding the LAN/internet connection of my NAS.
But i'm quite irritated why i can't reach that download speed in pyload with SO.

**Comment by fila612** [comment]
currentyl i tested to download the ubuntu iso in pyload and there i got the speed, only 18MB/s, but thats okay.
it seems that there is a problem with SO and pyload

**Comment by GammaC0de** [comment]
Is this a premium download?

**Comment by GammaC0de** [comment]
Please enable debug mode, start a download and look in the log for a line with `DOWNLOAD URL ...` .

Try to download this URL with wget and see what speed do you get..

**Comment by fila612** [comment]
thanks for this hint, but it doesn't work, cause in bash with "wget" i'm not able to download with premium credentials, isn't it?

**Comment by GammaC0de** [comment]
@fila612 The line `DOWNLOAD URL ...` in the log should tell you the premium download URL (provided that you did entered your credentials in pyload), so:
* Activate DEBUG mode
* Start a premium download.
* Stop the download
* Look in the log for  `DOWNLOAD URL ...`
* Download this URL with wget and see what speed do you get

**Comment by fila612** [comment]
Thanks for the information.
i've tried this steps above, but a got an error "...403 forbidden".
I searched regarding downloading SO premium via wget and found now working solution for me.
every URL was not working in bash. :(
settings in my SO account was also checked, direct downloads is enabled.

**Comment by fila612** [comment]
Currently i checked with UL premium.
this download reaches more than 20MB/s at the beginning and after several minutes it slows down to 10MB/s.
This is more than SO, but not fullspeed.
on my sinology (DS213+) i saw that the CPU is during the download on 98%/99% workload, process is python.
so think: at the beginning the 20MB/s were possible, but currently python slows down the CPU-capacity and this maybe affects the download speed.
in SO i checked this as well, but there i got only 60% CPU workload, and only slow 2-3MB/s

**Comment by GammaC0de** [comment]
Perhaps you have reached the possible limits of python on your hardware.

I would try to compare the download speed of the same SO URL, one using pyLoad on your DSM and the other using pyLoad on your iMac.
This way you can see if either you get better speed on your iMac (meaning the DSM hardware is not enough) or the same download speed (meaning pyLoad cannot handle the speed)

**Comment by fila612** [comment]
Thanks for your reply, but why i gat nearly full speed with uploaded and with ShareOnline not?
Same hw, same pyload,...
i think i remember (i'm not really sure) that a got full speed with SO to, for a couple of month (maybe last year).
So in the fact i love pyload and i want to use this combination (NAS & Pyload) for downloads like this, but i could be better working as it is at the moment.

**Comment by GammaC0de** [comment]
There is nothing that can be done regarding to the download speed except maybe insuring chunked download.

Can we close this?

**Comment by fila612** [comment]
Ok, if you like close this issue.
the problem for me isn't solved and i'm not sure where the issue directly can be adressed.
the details were written down in this issue, if anybody will have similar problems it should be comparable.
at the moment no solution can be provided.
thanks guys for helping.

**Comment by 3x3cut0r** [comment]
Same issue here again on my DS918+ since few weeks with pyload running in a Docker Container. 2MB/s on DS ... 5-6MB/s (50Mbit/s connection) on MacBookPro ... with all File Hosters!
