### ISSUE TITLE
Running pyload.py y No module named core.cli

### ISSUE THREAD

**Issue by Grauen** [pyload/pyload#2871]
I had pyload 0.4 installed and I tried to upgrade to the current version.
When executing python pyload.py I get this error

`
pyload/pyload-0.6.2$ python pyload.py
Traceback (most recent call last):
  File "pyload.py", line 16, in <module>
    from pyload.core.cli import main
  File "/home/pyload/programme/pyload/pyload-0.6.2/pyload.py", line 16, in <module>
    from pyload.core.cli import main
ImportError: No module named core.cli`

Is there anything I missed or anything I have to do?

**Comment by GammaC0de** [comment]
@Grauen Current version is v0.4.9 ...

**Comment by Grauen** [comment]
As I understand you cannot use the latest release to setup pyload. You have to checkout the stable branch instead.

**Comment by GammaC0de** [comment]
Or you can read the instructions in #2000
