### ISSUE TITLE
rockfile and captcha

### ISSUE THREAD

**Issue by maxking71** [pyload/pyload#2874]
I apologize, as by your advice I have earned some credits on the 9kw.eu site and I copied API into the appropriate pyload plugin
Unfortunately still the download does not start
Can you help me? This is the log

thank you

http://it.tinypic.com/r/9u5fnp/9

400 24.06.2017 16:41:26 WARNING CAPTCHA RockfileEu[37]: ReCaptcha | Key pattern not found  
401 24.06.2017 16:41:26 DEBUG HOSTER RockfileEu[37]: LOAD URL http://rockfile.eu/sri21j3cjb48.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'rand': u'7wusko2cam6h33acj3vfcisrxvd4vl7gq6sbyuq', u'code': '4095', u'method_premium': '', u'token': u'db857943fea50aeb2013fbc6592e1a98', u'down_direct': u'1', u'referer': u'http://rockfile.eu/sri21j3cjb48.html', u'method_free': '', u'id': u'sri21j3cjb48', u'op': u'download2'} | ref=True | just_header=False  
402 24.06.2017 16:41:27 DEBUG HOSTER RockfileEu[37]: WAIT set to timestamp 1498315289.187962 | Previous waitUntil: 1498315283.826503  
403 24.06.2017 16:41:27 INFO HOSTER RockfileEu[37]: Waiting 1 seconds...  
404 24.06.2017 16:41:29 DEBUG ADDON ExternalScripts: No script found under folder `download_processed`  
405 24.06.2017 16:41:29 DEBUG ADDON CloudFlareDdos: Unoverriding _preload() for  
406 24.06.2017 16:41:29 DEBUG ADDON ExternalScripts: No script found under folder `package_processed`  
407 24.06.2017 16:41:29 INFO Download restarted: sri21j3cjb48.html | Max captcha retries reached  
408 24.06.2017 16:41:29 DEBUG ADDON ExternalScripts: No script found under folder `all_downloads_processed`  
409 24.06.2017 16:41:29 DEBUG All downloads processed  
410 24.06.2017 16:41:29 INFO Download starts: sri21j3cjb48.html  
411 24.06.2017 16:41:29 DEBUG ADDON ExternalScripts: No script found under folder `download_preparing`  
412 24.06.2017 16:41:29 DEBUG ADDON CloudFlareDdos: Overriding _preload() for  
413 24.06.2017 16:41:29 DEBUG ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds  
414 24.06.2017 16:41:29 DEBUG ADDON UserAgentSwitcher: Setting maximum redirections to 10  
415 24.06.2017 16:41:29 DEBUG ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`  
416 24.06.2017 16:41:29 DEBUG HOSTER RockfileEu[37]: Plugin version: 0.06  
417 24.06.2017 16:41:29 DEBUG HOSTER RockfileEu[37]: Plugin status: testing  
418 24.06.2017 16:41:29 WARNING HOSTER RockfileEu[37]: Plugin may be unstable  
419 24.06.2017 16:41:29 INFO HOSTER RockfileEu[37]: Grabbing link info...  
420 24.06.2017 16:41:29 DEBUG ADDON CloudFlareDdos: Calling get_url() of  
421 24.06.2017 16:41:29 DEBUG HOSTER RockfileEu[37]: LOAD URL http://rockfile.eu/sri21j3cjb48.html | redirect=True | cookies=[('rockfile.eu', 'lang', 'english')] | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False  
422 24.06.2017 16:41:29 DEBUG ADDON CloudFlareDdos: get_url(): got BadHeader exception 503  
423 24.06.2017 16:41:29 INFO ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page  
424 24.06.2017 16:41:29 DEBUG HOSTER RockfileEu[37]: WAIT set to timestamp 1498315295.851512 | Previous waitUntil: 1498315289.187962  
425 24.06.2017 16:41:32 INFO HOSTER RockfileEu[37]: Waiting 2 seconds...  
426 24.06.2017 16:41:36 DEBUG HOSTER RockfileEu[37]: LOAD URL http://rockfile.eu/cdn-cgi/l/chk_jschl | redirect=True | cookies=True | get={'jschl_answer': '-14559', 'jschl_vc': '4fec41a2dd502192240e445704156716'

**Comment by GammaC0de** [comment]
Does it work correctly when you manually solve the captcha?

**Comment by maxking71** [comment]
Manually I do not know how it works

2017-06-24 17:15 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
Checking..

**Comment by GammaC0de** [comment]
They change something  on the site.
Plugin updated and should work now, please check.

**Comment by GammaC0de** [comment]
Does it work now?

**Comment by maxking71** [comment]
Sorry I just read now
To update what should i do from pyload?

2017-06-24 23:09 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
@maxking71 Restart pyload so UpdateManager will start.

**Comment by maxking71** [comment]
ok works...very very thanks

2017-06-25 21:22 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by maxking71** [comment]
87
Forgive me my friend
But I have problems with pyload
I have formatted hard disk and this is the log

thank you











27.06.2017 09:28:00
INFO Tempo di download: True
88 27.06.2017 09:28:00 INFO Avvio ThriftBackend: 0.0.0.0:7227
89 27.06.2017 09:28:01 WARNING SSL certificates not found.
90 27.06.2017 09:28:01 ERROR Error importing lightweight server: No module
named bjoern
91 27.06.2017 09:28:01 WARNING You need to download and compile bjoern,
https://github.com/jonashaag/bjoern
92 27.06.2017 09:28:01 WARNING Copy the boern.so to module/lib folder or
use setup.py install
93 27.06.2017 09:28:01 WARNING Of course you need to be familiar with linux
and know how to compile software
94 27.06.2017 09:28:01 INFO Starting builtin webserver: 0.0.0.0:8888
95 27.06.2017 07:21:15 INFO Avvio pyLoad 0.4.9
96 27.06.2017 07:21:15 INFO Uso la cartella home: /home/pyload/.pyload
97 27.06.2017 07:21:15 DEBUG Deleting old pidfile pyload.pid
98 27.06.2017 07:21:15 DEBUG Remote activated: True
99 27.06.2017 07:21:18 DEBUG created index of plugins
100 27.06.2017 07:21:18 DEBUG Redirected import
module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
101 27.06.2017 07:21:18 DEBUG Redirected import
module.plugins.hooks.MergeFiles -> userplugins.hooks.MergeFiles
102 27.06.2017 07:21:18 DEBUG Redirected import
module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
103 27.06.2017 07:21:18 DEBUG Redirected import
module.plugins.hooks.EventMapper -> userplugins.hooks.EventMapper
104 27.06.2017 07:21:18 DEBUG Redirected import
module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
105 27.06.2017 07:21:18 DEBUG Redirected import
module.plugins.hooks.Captcha9Kw -> userplugins.hooks.Captcha9Kw
106 27.06.2017 07:21:18 DEBUG Redirected import
module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
107 27.06.2017 07:21:18 DEBUG Redirected import
module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
108 27.06.2017 07:21:18 DEBUG Redirected import
module.plugins.hooks.CloudFlareDdos -> userplugins.hooks.CloudFlareDdos
109 27.06.2017 07:21:19 DEBUG Redirected import
module.plugins.hooks.UserAgentSwitcher ->
userplugins.hooks.UserAgentSwitcher
110 27.06.2017 07:21:19 INFO Plugins attivati: Captcha9Kw, ClickNLoad,
CloudFlareDdos, EventMapper, ExternalScripts, ExtractArchive, MergeFiles,
UnSkipOnFail, UpdateManager, UserAgentSwitcher
111 27.06.2017 07:21:19 INFO Plugins disattivati: AndroidPhoneNotify,
AntiStandby, AntiVirus, BypassCaptcha, CaptchaBrotherhood, Checksum,
DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders,
HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook,
LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev,
TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
112 27.06.2017 07:21:19 INFO Tempo di download: True
113 27.06.2017 07:21:19 INFO Avvio ThriftBackend: 0.0.0.0:7227
114 27.06.2017 07:21:19 WARNING SSL certificates not found.
115 27.06.2017 07:21:19 ERROR Error importing lightweight server: No module
named bjoern
116 27.06.2017 07:21:19 WARNING You need to download and compile bjoern,
https://github.com/jonashaag/bjoern
117 27.06.2017 07:21:19 WARNING Copy the boern.so to module/lib folder or
use setup.py install
118 27.06.2017 07:21:19 WARNING Of course you need to be familiar with
linux and know how to compile software
119 27.06.2017 07:21:19 INFO Starting builtin webserver: 0.0.0.0:8888
120 27.06.2017 07:28:30 DEBUG ADDON ExternalScripts: No script found under
folder `package_deleted`

2017-06-26 7:23 GMT+02:00 Max <cicchi@gmail.com>:

**Comment by GammaC0de** [comment]
You have to replace `HTTPRequest.py` with this one https://gist.github.com/GammaC0de/cc182933bc05c13ac69e807cb982b643/raw/515a3eef6a62e23ac807ae9f21c74b31d574524e/HTTPRequest.py and activate `CloudFlareDdos` plugin.

**Comment by maxking71** [comment]
Excuse me, but where do I find the file HTTPrequest and how do I overwrite
it?

2017-06-28 11:25 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
<PYLOAD_INSTALL_DIR>/module/network/HTTPrequest .py

**Comment by maxking71** [comment]
*Ok I changed the file and enabled dos**But i still have error :(*

626 28.06.2017 15:31:56 INFO HOSTER XFileSharing [2]: RockfileEu | Checking
for link errors ...
627 28.06.2017 15:31:56 INFO HOSTER XFileSharing [2]: RockfileEu | No
errors found
628 28.06.2017 15:31:56 WARNING CAPTCHA XFileSharing [2]: RockfileEu |
ReCaptcha
| Key pattern not found
629 28.06.2017 15:31:56 WARNING Download failed:> | Parse error: Too many
OPs | Plugin may be out of date
630 28.06.2017 15:31:56 INFO ADDON UnSkipOnFail: Looking for missed
duplicates of:> (pid: 2)
631 28.06.2017 15:31:56 INFO ADDON UnSkipOnFail: No duplicates found
632 28.06.2017 15:32:10 INFO Download starts: o8egtzan96ft.html
633 28.06.2017 15:32:10 WARNING HOSTER XFileSharing [1]: RockfileEu | Plugin
may be unstable
634 28.06.2017 15:32:10 INFO HOSTER XFileSharing [1]: RockfileEu | Grabbing
link info ...
635 28.06.2017 15:32:10 INFO ADDON CloudFlareDdos: Detected CloudFlare's
DDoS protection page
636 28.06.2017 15:32:17 WARNING HOSTER XFileSharing [1]: RockfileEu | Invalid
wait time interval
637 28.06.2017 15:32:18 INFO HOSTER XFileSharing [1]: RockfileEu | Link
name:>
638 28.06.2017 15:32:18 INFO HOSTER XFileSharing [1]: RockfileEu | Link
size: N / A
639 28.06.2017 15:32:18 INFO HOSTER XFileSharing [1]: RockfileEu | Link
status: online
640 28.06.2017 15:32:18 INFO HOSTER XFileSharing [1]: RockfileEu | Processing
url: http://rockfile.eu/o8egtzan96ft.html
641 28.06.2017 15:32:18 INFO HOSTER XFileSharing [1]: RockfileEu | Checking
for link errors ...
642 28.06.2017 15:32:18 INFO HOSTER XFileSharing [1]: RockfileEu | No
errors found
643 28.06.2017 15:32:18 INFO HOSTER XFileSharing [1]: RockfileEu | Processing
as free download ...
644 28.06.2017 15:32:18 INFO HOSTER XFileSharing [1]: RockfileEu | Checking
for link errors ...
645 28.06.2017 15:32:18 INFO HOSTER XFileSharing [1]: RockfileEu | No
errors found
646 28.06.2017 15:32:18 WARNING CAPTCHA XFileSharing [1]: RockfileEu |
ReCaptcha
| Key pattern not found
647 28.06.2017 15:32:19 INFO HOSTER XFileSharing [1]: RockfileEu | Checking
for link errors ...
648 28.06.2017 15:32:19 INFO HOSTER XFileSharing [1]: RockfileEu | No
errors found
649 28.06.2017 15:32:20 INFO HOSTER XFileSharing [1]: RockfileEu | Checking
for link errors ...
650 28.06.2017 15:32:20 INFO HOSTER XFileSharing [1]: RockfileEu | No
errors found
651 28.06.2017 15:32:20 WARNING CAPTCHA XFileSharing [1]: RockfileEu |
ReCaptcha
| Key pattern not found
652 28.06.2017 15:32:21 INFO HOSTER XFileSharing [1]: RockfileEu | Checking
for link errors ...
653 28.06.2017 15:32:21 INFO HOSTER XFileSharing [1]: RockfileEu | No
errors found
654 28.06.2017 15:32:22 INFO HOSTER XFileSharing [1]: RockfileEu | Checking
for link errors ...
655 28.06.2017 15:32:22 INFO HOSTER XFileSharing [1]: RockfileEu | No
errors found
656 28.06.2017 15:32:22 WARNING CAPTCHA XFileSharing [1]: RockfileEu |
ReCaptcha
| Key pattern not found
657 28.06.2017 15:32:23 WARNING Download failed:> | Parse error: Too many
OPs | Plugin may be out of date
658 28.06.2017 15:32:23 INFO ADDON UnSkipOnFail: Looking for skipped
duplicates of:> (pid: 1)
659 28.06.2017 15:32:23 INFO ADDON UnSkipOnFail: No duplicates found

2017-06-28 12:35 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
OK, you should disable `XFileSharing` plugin

**Comment by maxking71** [comment]
In the end it seems that I have solved everything
There is only one problem, why do I download the .hmtl files and not the
.rar file?

Sorry and thank you for everything

2017-06-28 16:08 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
@maxking71 If you have downloaded a  .html file, this means that something went wrong, maybe there is still a problem with the plugin.
Please post the log..

**Comment by maxking71** [comment]
THIS IS LOG
VERY THANKS MY FRIEND


172 29.06.2017 07:07:09 DEBUG Redirected import
module.plugins.hoster.RockfileEu -> userplugins.hoster.RockfileEu
173 29.06.2017 07:07:09 INFO Added package dance containing 1 links
174 29.06.2017 07:07:11 INFO Download starts:
http://rockfile.eu/yo0awcdu7dpv.html
175 29.06.2017 07:07:11 DEBUG ADDON ExternalScripts: No script found under
folder `download_preparing`
176 29.06.2017 07:07:11 DEBUG ADDON CloudFlareDdos: Overriding _preload()
for
177 29.06.2017 07:07:11 DEBUG ADDON UserAgentSwitcher: Setting connection
timeout to 60 seconds
178 29.06.2017 07:07:11 DEBUG ADDON UserAgentSwitcher: Setting maximum
redirections to 10
179 29.06.2017 07:07:11 DEBUG ADDON UserAgentSwitcher: Use custom
user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0)
Gecko/20100101 Firefox/38.0`
180 29.06.2017 07:07:11 DEBUG HOSTER RockfileEu[1]: Plugin version: 0.07
181 29.06.2017 07:07:11 DEBUG HOSTER RockfileEu[1]: Plugin status: testing
182 29.06.2017 07:07:11 WARNING HOSTER RockfileEu[1]: Plugin may be
unstable
183 29.06.2017 07:07:11 INFO HOSTER RockfileEu[1]: Grabbing link info...
184 29.06.2017 07:07:11 DEBUG ADDON CloudFlareDdos: Calling get_url() of
185 29.06.2017 07:07:11 DEBUG HOSTER RockfileEu[1]: LOAD URL
http://rockfile.eu/yo0awcdu7dpv.html | redirect=True | cookies=[('
rockfile.eu', 'lang', 'english')] | get={} | req=None | decode=True |
multipart=False | post={} | ref=True | just_header=False
186 29.06.2017 07:07:11 DEBUG ADDON CloudFlareDdos: get_url(): got
BadHeader exception 503
187 29.06.2017 07:07:11 INFO ADDON CloudFlareDdos: Detected CloudFlare's
DDoS protection page
188 29.06.2017 07:07:11 DEBUG HOSTER RockfileEu[1]: WAIT set to timestamp
1498712837.142844 | Previous waitUntil: 0.000000
189 29.06.2017 07:07:13 INFO HOSTER RockfileEu[1]: Waiting 4 seconds...
190 29.06.2017 07:07:19 DEBUG HOSTER RockfileEu[1]: LOAD URL
http://rockfile.eu/cdn-cgi/l/chk_jschl | redirect=True | cookies=True |
get={'jschl_answer': '34', 'jschl_vc': '1ca69bcd4c7b6c5608f7266955bfc005',
'pass': '1498712835.136-fk6QwgV1I0'} | req=None | decode=True |
multipart=False | post={} | ref=http://rockfile.eu/yo0awcdu7dpv.html |
just_header=False
191 29.06.2017 07:07:19 DEBUG HOSTER RockfileEu[1]: Link info: {'status':
2, 'hash': {}, 'name': 'yo0awcdu7dpv.html', 'url': u'
http://rockfile.eu/yo0awcdu7dpv.html', 'pattern': {}, 'size': 0}
192 29.06.2017 07:07:19 DEBUG HOSTER RockfileEu[1]: Previous link info: {}
193 29.06.2017 07:07:19 INFO HOSTER RockfileEu[1]: Link name:
yo0awcdu7dpv.html
194 29.06.2017 07:07:19 INFO HOSTER RockfileEu[1]: Link size: N/D
195 29.06.2017 07:07:19 INFO HOSTER RockfileEu[1]: Link status: online
196 29.06.2017 07:07:21 INFO HOSTER RockfileEu[1]: Processing url:
http://rockfile.eu/yo0awcdu7dpv.html
197 29.06.2017 07:07:21 INFO HOSTER RockfileEu[1]: Looking for direct
download link...
198 29.06.2017 07:07:21 DEBUG HOSTER RockfileEu[1]: LOAD URL
http://rockfile.eu/yo0awcdu7dpv.html | redirect=True | cookies=True |
get={} | req=None | decode=True | multipart=False | post={} | ref=True |
just_header=True
199 29.06.2017 07:07:22 INFO HOSTER RockfileEu[1]: Direct download link not
found
200 29.06.2017 07:07:22 DEBUG ADDON CloudFlareDdos: Calling _preload() of
201 29.06.2017 07:07:22 DEBUG HOSTER RockfileEu[1]: LOAD URL
http://rockfile.eu/yo0awcdu7dpv.html | redirect=True | cookies=[('
rockfile.eu', 'lang', 'english')] | get={} | req=None | decode=True |
multipart=False | post={} | ref=False | just_header=False
202 29.06.2017 07:07:22 DEBUG ADDON CloudFlareDdos: _preload() returned
successfully
203 29.06.2017 07:07:22 INFO HOSTER RockfileEu[1]: Checking for link
errors...
204 29.06.2017 07:07:22 INFO HOSTER RockfileEu[1]: No errors found
205 29.06.2017 07:07:22 INFO HOSTER RockfileEu[1]: Processing as free
download...
206 29.06.2017 07:07:22 DEBUG HOSTER RockfileEu[1]: LOAD URL
http://rockfile.eu/yo0awcdu7dpv.html | redirect=True | cookies=True |
get={} | req=None | decode=True | multipart=False | post={u'method_xfree':
u'Regular Download', u'usr_login': '', u'referer': u'
http://rockfile.eu/yo0awcdu7dpv.html', u'fname': '', u'id':
u'yo0awcdu7dpv', u'op': u'download1'} | ref=True | just_header=False
207 29.06.2017 07:07:23 INFO HOSTER RockfileEu[1]: Checking for link
errors...
208 29.06.2017 07:07:23 DEBUG HOSTER RockfileEu[1]: WAIT set to timestamp
1498712879.083498 | Previous waitUntil: 1498712837.142844
209 29.06.2017 07:07:23 INFO HOSTER RockfileEu[1]: Waiting 35 seconds...
210 29.06.2017 07:07:59 INFO HOSTER RockfileEu[1]: No errors found
211 29.06.2017 07:07:59 WARNING CAPTCHA RockfileEu[1]: ReCaptcha | Key
pattern not found
212 29.06.2017 07:07:59 DEBUG HOSTER RockfileEu[1]: LOAD URL
http://rockfile.eu/yo0awcdu7dpv.html | redirect=True | cookies=True |
get={} | req=None | decode=True | multipart=False | post={u'rand':
u'ysmzxnuiv5ezaaddhncudambs4nzrnkm3i4dyzy', u'code': '8828',
u'method_premium': '', u'token': u'db857943fea50aeb2013fbc6592e1a98',
u'down_direct': u'1', u'referer': u'http://rockfile.eu/yo0awcdu7dpv.html',
u'method_free': '', u'id': u'yo0awcdu7dpv', u'op': u'download2'} | ref=True
| just_header=False
213 29.06.2017 07:07:59 INFO HOSTER RockfileEu[1]: Downloading file...
214 29.06.2017 07:07:59 DEBUG HOSTER RockfileEu[1]: DOWNLOAD URL
http://stn030.rfservers.eu:182/d/sxp4cosxywdtklus3vrkn5duyg4nxmgxgfp45i3oxy44irslvagrf3qw/VA-Summer_Party_Dance_Hi__2017.rar
| cookies=True | resume=None | get={} | disposition=True | chunks=None |
post={} | ref=True

2017-06-29 1:43 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
Are you sure it does not work? it looks like it does...
```
214 29.06.2017 07:07:59 DEBUG HOSTER RockfileEu[1]: DOWNLOAD URL http://stn030.rfservers.eu:182/d/sxp4cosxywdtklus3vrkn5duyg4nxmgxgfp45i3oxy44irslvagrf3qw/VA-Summer_Party_Dance_Hi__2017.rar
```

**Comment by maxking71** [comment]
Thanks for fixing html problem
Unfortunately, not always, but I get the problem that does not find the
captcha
I, as your advice, I have enabled 9KW.com and I have accumulated credits
Do you know where the problem is?
sorry again



260 30.06.2017 08:37:28 DEBUG HOSTER RockfileEu[27]: LOAD URL
http://rockfile.eu/y37a624b0xod.html | redirect=True | cookies=[('
rockfile.eu', 'lang', 'english')] | get={} | req=None | decode=True |
multipart=False | post={} | ref=True | just_header=False
261 30.06.2017 08:37:28 DEBUG ADDON CloudFlareDdos: get_url(): got
BadHeader exception 503
262 30.06.2017 08:37:28 INFO ADDON CloudFlareDdos: Detected CloudFlare's
DDoS protection page
263 30.06.2017 08:37:28 DEBUG HOSTER RockfileEu[27]: WAIT set to timestamp
1498804654.944079 | Previous waitUntil: 0.000000
264 30.06.2017 08:37:30 INFO HOSTER RockfileEu[27]: Waiting 4 seconds...
265 30.06.2017 08:37:36 DEBUG HOSTER RockfileEu[27]: LOAD URL
http://rockfile.eu/cdn-cgi/l/chk_jschl | redirect=True | cookies=True |
get={'jschl_answer': '20115', 'jschl_vc':
'6537c5c131cc2294fb99c4aeaaa1e012', 'pass': '1498804652.918-z42SB420Ma'} |
req=None | decode=True | multipart=False | post={} | ref=
http://rockfile.eu/y37a624b0xod.html | just_header=False
266 30.06.2017 08:37:40 DEBUG HOSTER RockfileEu[27]: Link info: {'status':
2, 'hash': {}, 'name': 'y37a624b0xod.html', 'url': u'
http://rockfile.eu/y37a624b0xod.html', 'pattern': {'ID': u'y37a624b0xod'},
'size': 0}
267 30.06.2017 08:37:40 DEBUG HOSTER RockfileEu[27]: Previous link info:
{}
268 30.06.2017 08:37:40 INFO HOSTER RockfileEu[27]: Link name:
y37a624b0xod.html
269 30.06.2017 08:37:40 INFO HOSTER RockfileEu[27]: Link size: N/D
270 30.06.2017 08:37:40 INFO HOSTER RockfileEu[27]: Link status: online
271 30.06.2017 08:37:40 INFO HOSTER RockfileEu[27]: Processing url:
http://rockfile.eu/y37a624b0xod.html
272 30.06.2017 08:37:40 INFO HOSTER RockfileEu[27]: Looking for direct
download link...
273 30.06.2017 08:37:40 DEBUG HOSTER RockfileEu[27]: LOAD URL
http://rockfile.eu/y37a624b0xod.html | redirect=True | cookies=True |
get={} | req=None | decode=True | multipart=False | post={} | ref=True |
just_header=True
274 30.06.2017 08:37:41 INFO HOSTER RockfileEu[27]: Direct download link
not found
275 30.06.2017 08:37:41 DEBUG ADDON CloudFlareDdos: Calling _preload() of
276 30.06.2017 08:37:41 DEBUG HOSTER RockfileEu[27]: LOAD URL
http://rockfile.eu/y37a624b0xod.html | redirect=True | cookies=[('
rockfile.eu', 'lang', 'english')] | get={} | req=None | decode=True |
multipart=False | post={} | ref=False | just_header=False
277 30.06.2017 08:37:42 DEBUG ADDON CloudFlareDdos: _preload() returned
successfully
278 30.06.2017 08:37:42 INFO HOSTER RockfileEu[27]: Checking for link
errors...
279 30.06.2017 08:37:42 INFO HOSTER RockfileEu[27]: No errors found
280 30.06.2017 08:37:42 INFO HOSTER RockfileEu[27]: Processing as free
download...
281 30.06.2017 08:37:42 DEBUG HOSTER RockfileEu[27]: LOAD URL
http://rockfile.eu/y37a624b0xod.html | redirect=True | cookies=True |
get={} | req=None | decode=True | multipart=False | post={u'method_xfree':
u'Regular Download', u'usr_login': '', u'referer': u'
http://rockfile.eu/y37a624b0xod.html', u'fname': '', u'id':
u'y37a624b0xod', u'op': u'download1'} | ref=True | just_header=False
282 30.06.2017 08:37:42 INFO HOSTER RockfileEu[27]: Checking for link
errors...
283 30.06.2017 08:37:42 INFO HOSTER RockfileEu[27]: No errors found
284 30.06.2017 08:37:42 WARNING CAPTCHA RockfileEu[27]: ReCaptcha | Key
pattern not found
285 30.06.2017 08:37:42 DEBUG ADDON ExternalScripts: No script found under
folder `download_processed`
286 30.06.2017 08:37:42 DEBUG ADDON CloudFlareDdos: Unoverriding _preload()
for
287 30.06.2017 08:37:42 DEBUG ADDON ExternalScripts: No script found under
folder `package_processed`
288 30.06.2017 08:37:42 WARNING Download failed: y37a624b0xod.html | Parse
error: Captcha not found | Plugin may be out of date
289 30.06.2017 08:37:42 INFO ADDON UnSkipOnFail: Looking for skipped
duplicates of: y37a624b0xod.html (pid:27)
290 30.06.2017 08:37:42 INFO ADDON UnSkipOnFail: No duplicates found
291 30.06.2017 08:37:42 DEBUG ADDON ExternalScripts: No script found under
folder `download_failed`
292 30.06.2017 08:37:43 DEBUG ADDON ExternalScripts: No script found under
folder `all_downloads_processed`
293 30.06.2017 08:37:43 DEBUG All downloads processed

2017-06-29 14:05 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
Add this line between line 78 and 79 and wait for error to occur.
Then you will find in `<PYLOAD_CONFIG_FOLDER>tmp/RockfileEu` a html file, post this file here.
```python
        self.dump_html()
```

**Comment by GammaC0de** [comment]
Any news about this?

**Comment by maxking71** [comment]
close,
It was a problem of having exceeded 2 gb of downloads
thank you

2017-07-03 2:49 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
@maxking71 Can you tell me what message do you get when exceeding 2 GB of downloads?
Or you don't care if this happens again and you want to close this?

**Comment by maxking71** [comment]
I solved
You can close, it was my problem

2017-07-04 12:25 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
👍
