### ISSUE TITLE
I can't download anything

### ISSUE THREAD

**Issue by poste5** [pyload/pyload#2876]
Hi, I have a very basic knownledge of linux terminal. I can only follow copy/paste instructions. 
I have installed pyLoad on a seedbox using their tutorial. I installed it. But now I can't download anything. I tried some links. It's all weird, If I go to the ''downloads'' tab and click to the blue links pyLoad redirects me to the hoster page. What am I doing wrong? Thank you

1	25.06.2017 20:11:12	INFO	Starting pyLoad 0.4.9
2	25.06.2017 20:11:12	INFO	Using home directory: /media/sdr1/poiu0/.pyload
3	25.06.2017 20:11:13	INFO	ExtractArchive: Activated UnRar UnZip
4	25.06.2017 20:11:13	INFO	Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
5	25.06.2017 20:11:13	INFO	Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
6	25.06.2017 20:11:13	INFO	Downloadtime: True
7	25.06.2017 20:11:13	INFO	Starting builtin webserver: 0.0.0.0:12345
8	25.06.2017 20:11:13	INFO	Free space: 4.31 TiB
9	25.06.2017 20:11:13	INFO	Activating Accounts...
10	25.06.2017 20:11:13	INFO	Activating Plugins...
11	25.06.2017 20:11:13	INFO	pyLoad is up and running
12	25.06.2017 20:11:16	INFO	*** New pyLoad Version
16	? 	?	
17	? 	?	
18	? 	?	
49	? 	?	
50	? 	?	
51	? 	?	available ***
58	25.06.2017 20:11:16	INFO	*** Get it here: http://pyload.org/download ***
59	25.06.2017 20:11:16	INFO	No plugin updates available
60	25.06.2017 21:11:49	INFO	Added package Test1 containing 1 links
61	25.06.2017 21:11:49	INFO	Download starts: https://uptobox.com/l59iom75kirs
62	25.06.2017 21:11:49	INFO	Download finished: l59iom75kirs
63	25.06.2017 21:11:49	INFO	Package finished: Test1
64	25.06.2017 21:11:49	INFO	ExtractArchive: Package Test1 queued for later extracting
65	25.06.2017 21:11:49	INFO	ExtractArchive: Check package Test1
66	25.06.2017 21:12:17	INFO	Download starts: l59iom75kirs
67	25.06.2017 21:12:17	INFO	Download finished: l59iom75kirs
68	25.06.2017 21:12:23	INFO	Download starts: l59iom75kirs
69	25.06.2017 21:12:23	INFO	Download finished: l59iom75kirs
70	25.06.2017 21:22:18	INFO	Added package Test1 containing 1 links
71	25.06.2017 21:22:19	INFO	Download starts: http://nitroflare.com/view/7E81071E17FD44C/TwoDDL_12RS.part1.rar
72	25.06.2017 21:22:20	INFO	Download finished: TwoDDL_12RS.part1.rar
73	25.06.2017 21:22:20	INFO	Package finished: Test1
74	25.06.2017 21:22:20	INFO	ExtractArchive: Package Test1 queued for later extracting
75	25.06.2017 21:22:20	INFO	ExtractArchive: Check package Test1
76	25.06.2017 21:22:20	INFO	ExtractArchive: TwoDDL_12RS.part1.rar | Extract to /media/sdr1/poiu0/private/Downloads_Pyload/Test1/
77	25.06.2017 21:22:20	ERROR	ExtractArchive: TwoDDL_12RS.part1.rar | Archive Error | Empty Archive
78	25.06.2017 21:22:45	INFO	Download starts: TwoDDL_12RS.part1.rar
79	25.06.2017 21:22:46	INFO	Download finished: TwoDDL_12RS.part1.rar
80	25.06.2017 21:22:49	INFO	Download starts: TwoDDL_12RS.part1.rar
81	25.06.2017 21:22:50	INFO	Download aborted: http://nitroflare.com/view/7E81071E17FD44C/TwoDDL_12RS.part1.rar
82	25.06.2017 21:22:51	INFO	Download starts: http://nitroflare.com/view/7E81071E17FD44C/TwoDDL_12RS.part1.rar
83	25.06.2017 21:22:52	INFO	Download finished: TwoDDL_12RS.part1.rar
84	25.06.2017 21:28:27	INFO	Added package Test 2 containing 1 links
85	25.06.2017 21:28:27	WARNING	Info Fetching for FilefactoryCom failed | 'NoneType' object has no attribute 'group'
86	25.06.2017 21:28:28	INFO	Download starts: http://www.filefactory.com/file/4sjtcg0uzwzv
87	25.06.2017 21:28:28	WARNING	Download failed: http://www.filefactory.com/file/4sjtcg0uzwzv | 'NoneType' object has no attribute 'group'
88	25.06.2017 21:28:42	INFO	Download starts: http://www.filefactory.com/file/4sjtcg0uzwzv
89	25.06.2017 21:28:42	WARNING	Download failed: http://www.filefactory.com/file/4sjtcg0uzwzv | 'NoneType' object has no attribute 'group'
90	25.06.2017 21:31:54	INFO	Download starts: http://www.filefactory.com/file/4sjtcg0uzwzv
91	25.06.2017 21:31:54	WARNING	Download failed: http://www.filefactory.com/file/4sjtcg0uzwzv | 'NoneType' object has no attribute 'group'
92	25.06.2017 21:32:17	INFO	Added package grhhrdhrdhbdfh containing 1 links
93	25.06.2017 21:32:18	INFO	Download starts: TwoDDL_12RS.part1.rar
94	25.06.2017 21:32:18	WARNING	Download failed: TwoDDL_12RS.part1.rar | 'NoneType' object has no attribute 'group'
95	25.06.2017 21:32:40	INFO	Download starts: http://www.filefactory.com/file/4sjtcg0uzwzv
96	25.06.2017 21:32:40	WARNING	Download failed: http://www.filefactory.com/file/4sjtcg0uzwzv | 'NoneType' object has no attribute 'group'
97	25.06.2017 21:32:42	INFO	Download starts: http://www.filefactory.com/file/4sjtcg0uzwzv
98	25.06.2017 21:32:42	WARNING	Download failed: http://www.filefactory.com/file/4sjtcg0uzwzv | 'NoneType' object has no attribute 'group'
99	25.06.2017 21:32:50	INFO	Download starts: http://www.filefactory.com/file/4sjtcg0uzwzv
100	25.06.2017 21:32:50	WARNING	Download failed: http://www.filefactory.com/file/4sjtcg0uzwzv | 'NoneType' object has no attribute 'group' 
101	25.06.2017 21:33:24	INFO	Added package gkgukujglhjlk containing 1 links
102	25.06.2017 21:33:26	INFO	Download starts: http://rapidgator.net/file/4620d8b5f8af5261daa05ae234e7f77b/TwoDDL_12RS.part1.rar.html
103	25.06.2017 21:33:27	INFO	Download finished: TwoDDL_12RS.part1.rar.html
104	25.06.2017 21:33:27	INFO	Package finished: gkgukujglhjlk
105	25.06.2017 21:33:27	INFO	ExtractArchive: Package gkgukujglhjlk queued for later extracting
106	25.06.2017 21:33:27	INFO	ExtractArchive: Check package gkgukujglhjlk
107	25.06.2017 21:33:38	INFO	Download starts: TwoDDL_12RS.part1.rar.html
108	25.06.2017 21:33:39	INFO	Download finished: TwoDDL_12RS.part1.rar.html

**Comment by GammaC0de** [comment]
@poste5 Your installation is not complete, please read #2000

**Comment by poste5** [comment]
@GammaC0de I used this for the installation

wget -q https://github.com/pyload/pyload/releases/download/v0.4.9/pyload-cli_0.4.9_all.deb
dpkg -x pyload-cli_0.4.9_all.deb ~/pyLoad
rm ~/pyLoad/usr/bin/pyLoadCli ~/pyLoad/usr/share/pyload/pyLoadCli.py
cp -r ~/pyLoad/usr/* ~/
rm -rf ~/pyLoad/ ~/pyload-cli_0.4.9_all.deb

How do I replace the file? Do I have to do it manually with filezilla?

**Comment by GammaC0de** [comment]
```
wget https://github.com/pyload/pyload/releases/download/v0.4.9/pyload-cli_0.4.9_all.deb
dpkg -x pyload-cli_0.4.9_all.deb ~/pyLoad
rm ~/pyLoad/usr/bin/pyLoadCli ~/pyLoad/usr/share/pyload/pyLoadCli.py
cp -r ~/pyLoad/usr/* ~/
rm -rf ~/pyLoad/ ~/pyload-cli_0.4.9_all.deb
rm -f ~/share/pyload/module/plugins/hooks/UpdateManager.py
wget https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/78f10968869e887d802a75a9ef6b89628d0d5ff9/UpdateManager.py -O ~/share/pyload/module/plugins/hooks/UpdateManager.py
```

**Comment by poste5** [comment]
@GammaC0de thank you so much! Now it works. So the problem was the tutorial of FeralHosting that I followed, it didn't mention the updatemanager.py. Thank you!

**Comment by GammaC0de** [comment]
👍
