### ISSUE TITLE
Zippyshare - file.html ERROR

### ISSUE THREAD

**Issue by koenigmidas** [pyload/pyload#2880]
Dear all,

first of all I need to tell you that I had to re-setup my raspberry again because of a broken SD card-

so before using a new card everything worked 100%

so I have set up new OS - raspian jessie and new pyload.
Now I got the problem, that once I am loading dlc files with zippyshare urls, py load is loading file.html files.

simple shareonline.biz links are working.

error:
INFO Download skipped: file.html due to BasePlugin

system check via pyload config screen says all items - OK.

What did it wrong? previous card was running without problems - current setup got problems. it seems that something is "missing" for using pyload properly.

Unfortunately I am pretty new to raspbian and pyload. So please be patient when I am a bit "slow" or if I have missed anything to mentioned in my post.

Looking forward to every help which helps to solve the problem.

Greetings

**Comment by GammaC0de** [comment]
Please read https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi)

**Comment by GammaC0de** [comment]
Can we close this?

**Comment by koenigmidas** [comment]
yes - thank you very much for your help!

**Comment by GammaC0de** [comment]
👍
