### ISSUE TITLE
Download issue >2GB

### ISSUE THREAD

**Issue by dsxcsman** [pyload/pyload#2882]
Hi,

I installed Pyload on my Dedicated server (Quickbox plugin on Ubuntu 16.04.2 X64)  But I have an issue and I can't find any solution on my own.

So Pyload seems to work perfectly, but when i try to download a file > 2GB from my  dedicated server to my computer, in the "Download" section I have an error message :

`A server error occurred. Please contact the administrator.`

If I download a file < 2GB everything is working perfectly.

I can't find more information in Pyload logs or in error.log (apache2)

The only thing that i can see is my RAM increase more and more... until error message

Where does this error come from? Pyload ?

Thanks guys

**Comment by GammaC0de** [comment]
What hardware are we talking about?

**Comment by dsxcsman** [comment]
Hi, 
1x Intel® C2750 (Avoton)
8 Go DDR3
1x 1 To SATA 
This is not too bad :)

**Comment by GammaC0de** [comment]
Quickbox means https://quickbox.io?

**Comment by dsxcsman** [comment]
Yeah exactly, quickbox.io, pyload is one of the plugins of the quickbox project, this is an apache Server. Pyload installation really looks like the normal installation. Configuration path, download path, web interface, ssl port number etc... This 2GB limit is really annoying, and only affect pyload since rapidleech and h5ai. Pyload is very awesome I really would like to be able to fix this issue.

**Comment by dsxcsman** [comment]
Hi,
Before investigate further, since Quickbox script and Pyload worked properly for you, I will just try to install the Quickbox script on a fresh installed VM. 

Which OS did you use to do the installation? 

Thanks so much to spend time with that.

**Comment by GammaC0de** [comment]
I used Ubuntu 16.04 LTS.

**Comment by GammaC0de** [comment]
Any update?

**Comment by dsxcsman** [comment]
Hi, 

I finally did a fresh install with Ubuntu 16.04 and  Quickbox script and I still have the same issue. 

I spend like 4 days on this problem so I gave up and I used rapidleech instead. 

Regards, 

Nicolas

**Comment by GammaC0de** [comment]
Sorry for that.
