### ISSUE TITLE
Download from Rockfile doesn't start

### ISSUE THREAD

**Issue by poste5** [pyload/pyload#2886]
This is the log, downloads from Rockfile does not start:

09.07.2017 12:22:28 | INFO | Download starts: http://rockfile.eu/4t3r5xjnwure.html
260 | 09.07.2017 12:22:28 | WARNING | HOSTER XFileSharing[367]: RockfileEu | Plugin may be unstable
261 | 09.07.2017 12:22:28 | INFO | HOSTER XFileSharing[367]: RockfileEu | Grabbing link info...
262 | 09.07.2017 12:22:29 | INFO | HOSTER XFileSharing[367]: RockfileEu | Link name: >
263 | 09.07.2017 12:22:29 | INFO | HOSTER XFileSharing[367]: RockfileEu | Link size: N/D
264 | 09.07.2017 12:22:29 | INFO | HOSTER XFileSharing[367]: RockfileEu | Link status: online
265 | 09.07.2017 12:22:29 | INFO | HOSTER XFileSharing[367]: RockfileEu | Processing url: http://rockfile.eu/4t3r5xjnwure.html
266 | 09.07.2017 12:22:29 | INFO | HOSTER XFileSharing[367]: RockfileEu | Checking for link errors...
267 | 09.07.2017 12:22:29 | INFO | HOSTER XFileSharing[367]: RockfileEu | No errors found
268 | 09.07.2017 12:22:29 | INFO | HOSTER XFileSharing[367]: RockfileEu | Processing as free download...
269 | 09.07.2017 12:22:29 | INFO | HOSTER XFileSharing[367]: RockfileEu | Checking for link errors...
270 | 09.07.2017 12:22:29 | INFO | HOSTER XFileSharing[367]: RockfileEu | No errors found
271 | 09.07.2017 12:22:29 | WARNING | CAPTCHA XFileSharing[367]: RockfileEu | ReCaptcha | Key pattern not found
272 | 09.07.2017 12:22:29 | INFO | HOSTER XFileSharing[367]: RockfileEu | Checking for link errors...
273 | 09.07.2017 12:22:29 | INFO | HOSTER XFileSharing[367]: RockfileEu | No errors found
274 | 09.07.2017 12:22:31 | INFO | HOSTER XFileSharing[367]: RockfileEu | Checking for link errors...
275 | 09.07.2017 12:22:31 | INFO | HOSTER XFileSharing[367]: RockfileEu | No errors found
276 | 09.07.2017 12:22:31 | WARNING | CAPTCHA XFileSharing[367]: RockfileEu | ReCaptcha | Key pattern not found
277 | 09.07.2017 12:22:31 | INFO | HOSTER XFileSharing[367]: RockfileEu | Checking for link errors...
278 | 09.07.2017 12:22:31 | INFO | HOSTER XFileSharing[367]: RockfileEu | No errors found
279 | 09.07.2017 12:22:32 | INFO | HOSTER XFileSharing[367]: RockfileEu | Checking for link errors...
280 | 09.07.2017 12:22:32 | INFO | HOSTER XFileSharing[367]: RockfileEu | No errors found
281 | 09.07.2017 12:22:32 | WARNING | CAPTCHA XFileSharing[367]: RockfileEu | ReCaptcha | Key pattern not found
282 | 09.07.2017 12:22:33 | WARNING | Download failed: > | Parse error: Too many OPs | Plugin may be out of date
283 | 09.07.2017 12:22:33 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: > (pid:38)
284 | 09.07.2017 12:22:33 | INFO | ADDON UnSkipOnFail: No duplicates found

Is the reCaptcha the problem? What can I do?
Thank you

**Comment by GammaC0de** [comment]
You should disable `XFileSharing` plugin

**Comment by poste5** [comment]
Wow... thank you, now it works!

With openload i have this log:

> 

65 | 09.07.2017 23:14:20 | WARNING | HOSTER OpenloadIo[371]: Plugin may be unstable
66 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Grabbing link info...
67 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Link name: [OPF-Italia] Dragon Ball Super 98 FHD (sub ita).mp4
68 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Link size: 385.03 MiB (403731116 bytes)
69 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Link status: starting
70 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Processing url: 
https://openload.co/f/m7GhLSBgWu8/%5BOPF-Italia%5D_Dragon_Ball_Super_98_FHD_%28sub_ita%29.mp4
71 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Looking for direct download link...
72 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Direct download link not found
73 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Checking for link errors...
74 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: No errors found
75 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Grabbing link info...
76 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Link name: [OPF-Italia] Dragon Ball Super 98 FHD (sub ita).mp4
77 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Link size: 385.03 MiB (403731116 bytes)
78 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Link status: starting
79 | 09.07.2017 23:14:20 | INFO | HOSTER OpenloadIo[371]: Processing as free download...
80 | 09.07.2017 23:14:21 | WARNING | Download is temporary offline: [OPF-Italia] Dragon Ball Super 98 FHD (sub ita).mp4

What does ''download is temporary offline'' means? Is it a hoster problem? With the browser I can download the file.

**Comment by GammaC0de** [comment]
One more thing with `RockfileEu`:

You should enable `CloudFlareDdos` plugin and also replace ` HTTPRequest.py` with this one: https://gist.github.com/GammaC0de/cc182933bc05c13ac69e807cb982b643/raw/515a3eef6a62e23ac807ae9f21c74b31d574524e/HTTPRequest.py

**Comment by GammaC0de** [comment]
About `OpenloadIo`:
This is a limitation of the `OpenloadIo` API:
"bandwidth usage too high (peak hours). out of capacity for non-browser downloads. please use browser download"

```
10.07.2017 03:01:22 DEBUG     HOSTER OpenloadIo[9635]: bandwidth usage too high (peak hours). out of capacity for non-browser downloads. please use browser download
10.07.2017 03:01:22 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
10.07.2017 03:01:22 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
10.07.2017 03:01:22 WARNING   Download is temporary offline: [OPF-Italia] Dragon Ball Super 98 FHD (sub ita).mp4
```

**Comment by GammaC0de** [comment]
Nothing we can do, so closing.
