### ISSUE TITLE
OpenLoad plugin error

### ISSUE THREAD

**Issue by maxking71** [pyload/pyload#2891]
329 11.07.2017 19:16:41 DEBUG ADDON CloudFlareDdos: get_url() returned successfully  
330 11.07.2017 19:16:41 DEBUG HOSTER OpenloadIo[2]: Link info: {'status': 7, 'hash': {}, 'name': u'open new year vol 9 tormentony dance.rar', 'url': u'https://openload.co/f/TZ_zCNfbKIQ/open_new_year_vol_9_tormentony_dance.rar', 'pattern': {'ID': u'TZ_zCNfbKIQ'}, 'size': 80183166}  
331 11.07.2017 19:16:41 DEBUG HOSTER OpenloadIo[2]: Previous link info: {}  
332 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Link name: open new year vol 9 tormentony dance.rar  
333 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Link size: 76.47 MiB (80183166 bytes)  
334 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Link status: avviando  
335 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Processing url: https://openload.co/f/TZ_zCNfbKIQ/open_new_year_vol_9_tormentony_dance.rar  
336 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Looking for direct download link...  
337 11.07.2017 19:16:41 DEBUG HOSTER OpenloadIo[2]: LOAD URL https://openload.co/f/TZ_zCNfbKIQ/open_new_year_vol_9_tormentony_dance.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True  
338 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Direct download link not found  
339 11.07.2017 19:16:41 DEBUG ADDON CloudFlareDdos: Calling _preload() of  
340 11.07.2017 19:16:41 DEBUG HOSTER OpenloadIo[2]: LOAD URL https://openload.co/f/TZ_zCNfbKIQ/open_new_year_vol_9_tormentony_dance.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False  
341 11.07.2017 19:16:41 DEBUG ADDON CloudFlareDdos: _preload() returned successfully  
342 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Checking for link errors...  
343 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: No errors found  
344 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Grabbing link info...  
345 11.07.2017 19:16:41 DEBUG ADDON CloudFlareDdos: Calling get_url() of  
346 11.07.2017 19:16:41 DEBUG HOSTER OpenloadIo[2]: LOAD URL https://api.openload.co/1/file/info?file=TZ_zCNfbKIQ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False  
347 11.07.2017 19:16:41 DEBUG ADDON CloudFlareDdos: get_url() returned successfully  
348 11.07.2017 19:16:41 DEBUG HOSTER OpenloadIo[2]: Link info: {'status': 7, 'hash': {}, 'name': u'open new year vol 9 tormentony dance.rar', 'url': u'https://openload.co/f/TZ_zCNfbKIQ/open_new_year_vol_9_tormentony_dance.rar', 'pattern': {'ID': u'TZ_zCNfbKIQ'}, 'size': 80183166}  
349 11.07.2017 19:16:41 DEBUG HOSTER OpenloadIo[2]: Previous link info: {'status': 7, 'hash': {}, 'name': u'open new year vol 9 tormentony dance.rar', 'url': u'https://openload.co/f/TZ_zCNfbKIQ/open_new_year_vol_9_tormentony_dance.rar', 'pattern': {'ID': u'TZ_zCNfbKIQ'}, 'size': 80183166}  
350 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Link name: open new year vol 9 tormentony dance.rar  
351 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Link size: 76.47 MiB (80183166 bytes)  
352 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Link status: avviando  
353 11.07.2017 19:16:41 INFO HOSTER OpenloadIo[2]: Processing as free download...  
354 11.07.2017 19:16:41 DEBUG ADDON CloudFlareDdos: Calling get_url() of  
355 11.07.2017 19:16:41 DEBUG HOSTER OpenloadIo[2]: LOAD URL https://api.openload.co/1/file/dlticket?file=TZ_zCNfbKIQ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False  
356 11.07.2017 19:16:42 DEBUG ADDON CloudFlareDdos: get_url() returned successfully  
357 11.07.2017 19:16:42 DEBUG ADDON ExternalScripts: No script found under folder `download_processed`  
358 11.07.2017 19:16:42 DEBUG ADDON CloudFlareDdos: Unoverriding _preload() for  
359 11.07.2017 19:16:42 DEBUG ADDON ExternalScripts: No script found under folder `package_processed`  
360 11.07.2017 19:16:42 WARNING Download is temporary offline: open new year vol 9 tormentony dance.rar  
361 11.07.2017 19:16:42 DEBUG ADDON ExternalScripts: No script found under folder `all_downloads_processed`  
362 11.07.2017 19:16:42 DEBUG All downloads processed

**Comment by GammaC0de** [comment]
@maxking71 I'm afraid that OpenloadIo encrypts their web pages with complex Javascript.
You could try to decrypt the page but its hard and not worth the hassle.
So the only (normal) way to download from OpenloadIo is to use their API.
If you use the API to download, sometimes it will not allow you but if you try to download via a browser it will.
This their policy and we can do nothing about it.
