### ISSUE TITLE
[Request Plugin] tenlua.vn

### ISSUE THREAD

**Issue by bigdargon** [pyload/pyload#2895]
Tenlua.vn is Vietnam's host, tenlua.vn allows you to download by free account and paid account. When no account is still downloadable without waiting, however, file transfer speed limits are limited. Please write more plugins for this host! Thank you very much!
Sample: https://www.tenlua.vn/xemaydinhso1gmail.com/1b37e22ee5096503/khanghyvihanhphan1%5Bdvd-1%5D.iso

**Comment by bigdargon** [comment]
*Updated: tenlua.vn has changed download policy since July, there will be only 1 kind of free account. Free account can be downloaded unlimited, but how many files are downloaded simultaneously. I have not try yet.
Link to test: https://www.tenlua.vn/bigdargon/0e37e628e90a69041c32/mirrors.2008.unrated.720p.bluray.x264-septic-%5Brarbg.to%5D.torrent
- I found the download structure of the link as follows: https://www.tenlua.vn/<username>/<id>/<etc>
<Username> is the name of the upload file
<Id> is the identifier of the file set by the server
<Etc> file name or other, this item is not necessarily in the right link

*Tenlua.vn has a folder link, you can write plugins to get each link in the folder link?
Link folder test: https://www.tenlua.vn/folder/xemaydinhso1gmail.com/1b37e22de10e650e/khang-hy-vi-hanh

**Comment by GammaC0de** [comment]
👍 Done

**Comment by bigdargon** [comment]
Great! Thank you for writing so many plugins! Currently I have contact with the support of tenlua.vn, they said that they are testing the new version should not debut vip members feature and they gave me a month to try the VIP feature. With the VIP feature, you will not have to wait for a download, resume support, and download multiple files at the same time. I will post your account via mail to test the plugins.

**Comment by GammaC0de** [comment]
👍 Done
