### ISSUE TITLE
Download failed:  | 'ascii' codec can't decode byte 0xe2 in position 66: ordinal not in range(128)

### ISSUE THREAD

**Issue by digimon04** [pyload/pyload#2897]
I world be appreciated if anyone could tell me the meaning of Download failed:  | 'ascii' codec can't decode byte 0xe2 in position 66: ordinal not in range(128)

I remember I got 2 to 3 times of this kind of error in attempt to download from k2s and filejoker. I have no idea but to give up the download attempt.

**Comment by BKPepe** [comment]
Here are more details:
https://github.com/pyload/pyload/issues/2659

**Comment by GammaC0de** [comment]
@digimon04 There is a major bug when the filename contains foreign Unicode characters (e.g. 'ü') that pyLoad cannot handle.
This cannot be fixed without major rewrite pyLoad's core so it can handle Unicode characters properly.

@vuolter is working on rewriting pyLoad, hopefully soon.

You can either try and apply #2106 (which supposedly removes the foreign characters from the filename) or wait for @vuolter to finish rewriting pyLoad.
