### ISSUE TITLE
Cannot login pyload on qnap

### ISSUE THREAD

**Issue by TuXbOy06** [pyload/pyload#2898]
Hello,

I am having a problem with pyload, I just installed it on my QNAP NAS and I unable to login to the WEBUI .

I created my account and 2 different accounts none of them are working can you assist please.

Thanks

**Comment by GammaC0de** [comment]
The package from https://www.qnapclub.eu/index.php?act=detail&qpkg_id=189 should work.

**Comment by TuXbOy06** [comment]
thanks it works ;-)
