### ISSUE TITLE
Mediafire.com not working

### ISSUE THREAD

**Issue by bigdargon** [pyload/pyload#2899]
I just added the mediafire link and found the plugin does not work. Please update the mediafire and mediafirefolder plugins. This is a link to test
- Folder: https://www.mediafire.com/folder/w9u1oqh9ldlh1/Doom_2005_Unrated_Extended_Edition_BiRD
- File: http://www.mediafire.com/file/1o2ibrukwsg7xuc/FHD0419706.Unrated.EE-BiRD.CBH.part01.rar

Thank you very much!

**Comment by GammaC0de** [comment]
mediafire (not foder) plugin does seems to work...
