### ISSUE TITLE
rockfile.eu doesn't work

### ISSUE THREAD

**Issue by poste5** [pyload/pyload#2906]
rockfile.eu doesn't work again, the last you fixed it for me with:
1. Disabling  `XFileSharing`
2. Enabling `CloudFlareDdos `
3. Replacing `HTTPRequest.py` with this one: https://gist.github.com/GammaC0de/cc182933bc05c13ac69e807cb982b643/raw/515a3eef6a62e23ac807ae9f21c74b31d574524e/HTTPRequest.py

I have done that, it worked. Now I have this: 
849 | 24.07.2017 21:40:10 | INFO | Download starts: baubw2a050ad.html
850 | 24.07.2017 21:40:10 | WARNING | HOSTER RockfileEu[375]: Plugin may be unstable
851 | 24.07.2017 21:40:10 | INFO | HOSTER RockfileEu[375]: Grabbing link info...
852 | 24.07.2017 21:40:10 | INFO | ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page
853 | 24.07.2017 21:40:10 | ERROR | ADDON CloudFlareDdos: No JS Engine
854 | 24.07.2017 21:40:10 | INFO | HOSTER RockfileEu[375]: Link name: baubw2a050ad.html
855 | 24.07.2017 21:40:10 | INFO | HOSTER RockfileEu[375]: Link size: N/D
856 | 24.07.2017 21:40:10 | INFO | HOSTER RockfileEu[375]: Link status: starting
857 | 24.07.2017 21:40:10 | INFO | HOSTER RockfileEu[375]: Processing url: http://rockfile.eu/baubw2a050ad.html
858 | 24.07.2017 21:40:10 | INFO | HOSTER RockfileEu[375]: Looking for direct download link...
859 | 24.07.2017 21:40:10 | WARNING | Download failed: baubw2a050ad.html \| Bad server response: 503 Service Unavailable
860 | 24.07.2017 21:40:10 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: baubw2a050ad.html (pid:44)
861 | 24.07.2017 21:40:10 | INFO | ADDON UnSkipOnFail: No duplicates found
862 | 24.07.2017 21:40:12 | INFO | Download starts: zeh3rg7s1twd.html
863 | 24.07.2017 21:40:12 | WARNING | HOSTER RockfileEu[376]: Plugin may be unstable
864 | 24.07.2017 21:40:12 | INFO | HOSTER RockfileEu[376]: Grabbing link info...
865 | 24.07.2017 21:40:12 | INFO | ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page
866 | 24.07.2017 21:40:12 | ERROR | ADDON CloudFlareDdos: No JS Engine
867 | 24.07.2017 21:40:12 | INFO | HOSTER RockfileEu[376]: Link name: zeh3rg7s1twd.html
868 | 24.07.2017 21:40:12 | INFO | HOSTER RockfileEu[376]: Link size: N/D
869 | 24.07.2017 21:40:12 | INFO | HOSTER RockfileEu[376]: Link status: starting
870 | 24.07.2017 21:40:12 | INFO | HOSTER RockfileEu[376]: Processing url: http://rockfile.eu/zeh3rg7s1twd.html
871 | 24.07.2017 21:40:12 | INFO | HOSTER RockfileEu[376]: Looking for direct download link...
872 | 24.07.2017 21:40:12 | WARNING | Download failed: zeh3rg7s1twd.html \| Bad server response: 503 Service Unavailable
873 | 24.07.2017 21:40:12 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: zeh3rg7s1twd.html (pid:44)
874 | 24.07.2017 21:40:12 | INFO | ADDON UnSkipOnFail: No duplicates found
875 | 24.07.2017 21:40:14 | INFO | Download starts: ede6mgg5y1vv.html
876 | 24.07.2017 21:40:14 | WARNING | HOSTER RockfileEu[377]: Plugin may be unstable
877 | 24.07.2017 21:40:14 | INFO | HOSTER RockfileEu[377]: Grabbing link info...
878 | 24.07.2017 21:40:14 | INFO | ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page
879 | 24.07.2017 21:40:14 | ERROR | ADDON CloudFlareDdos: No JS Engine
880 | 24.07.2017 21:40:14 | INFO | HOSTER RockfileEu[377]: Link name: ede6mgg5y1vv.html
881 | 24.07.2017 21:40:14 | INFO | HOSTER RockfileEu[377]: Link size: N/D
882 | 24.07.2017 21:40:14 | INFO | HOSTER RockfileEu[377]: Link status: starting
883 | 24.07.2017 21:40:14 | INFO | HOSTER RockfileEu[377]: Processing url: http://rockfile.eu/ede6mgg5y1vv.html
884 | 24.07.2017 21:40:14 | INFO | HOSTER RockfileEu[377]: Looking for direct download link...
885 | 24.07.2017 21:40:14 | WARNING | Download failed: ede6mgg5y1vv.html \| Bad server response: 503 Service Unavailable
886 | 24.07.2017 21:40:14 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: ede6mgg5y1vv.html (pid:44)
887 | 24.07.2017 21:40:14 | INFO | ADDON UnSkipOnFail: No duplicates found

May you please check these links with your pyload and see where the problem is?

Thank you!

**Comment by GammaC0de** [comment]
>ADDON CloudFlareDdos: No JS Engine

You have to install a javascript engine for `CloudFlareDdos` plugin to be able to work.

What OS are you running pyload?

**Comment by poste5** [comment]
It's a seedbox, Debian GNU/Linux 8, I don't have root access. 
But some days ago rockfile.eu worked with 'CloudFlareDdos' disabled, only with  'XFileSharing' disabled. What is the explanation?

**Comment by GammaC0de** [comment]
put [this](http://www102.zippyshare.com/v/h3OZxN4D/file.html) somewhere in your PATH (don't forgert to unzip)

**Comment by poste5** [comment]
Wait... in which PATH should I put this file? Everywhere? 

Thank you

**Comment by GammaC0de** [comment]
What is the output of `cat /etc/debian_version`?

**Comment by poste5** [comment]
`[alcyoneus ~] cat /etc/debian_version
8.8
`

**Comment by GammaC0de** [comment]
Hopefully [this one](http://www114.zippyshare.com/v/pXKSxAZn/file.html) will work.

**Comment by poste5** [comment]
Is /media/sdr1/poiu0/bin the correct path?

569 | 27.07.2017 11:25:20 | INFO | Added package OPF containing 1 links
-- | -- | -- | --
570 | 27.07.2017 11:25:21 | INFO | Download starts: http://rockfile.eu/ede6mgg5y1vv.html
571 | 27.07.2017 11:25:21 | WARNING | HOSTER RockfileEu[430]: Plugin may be unstable
572 | 27.07.2017 11:25:21 | INFO | HOSTER RockfileEu[430]: Grabbing link info...
573 | 27.07.2017 11:25:21 | INFO | ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page
574 | 27.07.2017 11:25:21 | ERROR | ADDON CloudFlareDdos: No JS Engine
575 | 27.07.2017 11:25:21 | INFO | HOSTER RockfileEu[430]: Link name: ede6mgg5y1vv.html
576 | 27.07.2017 11:25:21 | INFO | HOSTER RockfileEu[430]: Link size: N/D
577 | 27.07.2017 11:25:21 | INFO | HOSTER RockfileEu[430]: Link status: starting
578 | 27.07.2017 11:25:21 | INFO | HOSTER RockfileEu[430]: Processing url: http://rockfile.eu/ede6mgg5y1vv.html
579 | 27.07.2017 11:25:21 | INFO | HOSTER RockfileEu[430]: Looking for direct download link...
580 | 27.07.2017 11:25:21 | WARNING | Download failed: ede6mgg5y1vv.html \| Bad server response: 503 Service Unavailable
581 | 27.07.2017 11:25:21 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: ede6mgg5y1vv.html (pid:62)
582 | 27.07.2017 11:25:21 | INFO | ADDON UnSkipOnFail: No duplicates found
583 | 27.07.2017 11:25:31 | INFO | Download starts: ede6mgg5y1vv.html
584 | 27.07.2017 11:25:31 | WARNING | HOSTER RockfileEu[430]: Plugin may be unstable
585 | 27.07.2017 11:25:31 | INFO | HOSTER RockfileEu[430]: Grabbing link info...
586 | 27.07.2017 11:25:31 | INFO | ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page
587 | 27.07.2017 11:25:31 | ERROR | ADDON CloudFlareDdos: No JS Engine
588 | 27.07.2017 11:25:31 | INFO | HOSTER RockfileEu[430]: Link name: ede6mgg5y1vv.html
589 | 27.07.2017 11:25:31 | INFO | HOSTER RockfileEu[430]: Link size: N/D
590 | 27.07.2017 11:25:31 | INFO | HOSTER RockfileEu[430]: Link status: starting
591 | 27.07.2017 11:25:31 | INFO | HOSTER RockfileEu[430]: Processing url: http://rockfile.eu/ede6mgg5y1vv.html
592 | 27.07.2017 11:25:31 | INFO | HOSTER RockfileEu[430]: Looking for direct download link...
593 | 27.07.2017 11:25:31 | WARNING | Download failed: ede6mgg5y1vv.html \| Bad server response: 503 Service Unavailable

**Comment by GammaC0de** [comment]
Enter
```
ls -l /media/sdr1/poiu0/bin/js
cd /media/sdr1/poiu0
js --help
```
What do you get?

**Comment by poste5** [comment]
> [alcyoneus~] ls -l /media/sdr1/poiu0/bin/js
-rw-r--r-- 1 poiu0 poiu0 5762777 Jul 27 11:18 /media/sdr1/poiu0/bin/js
[alcyoneus ~] cd /media/sdr1/poiu0
[alcyoneus ~] js --help
-bash: /media/sdr1/poiu0/bin/js: Permission denied



Permissions problem? I did this. What do you think? Do I have to enable ALL the permissions?

[alcyoneus ~/bin] chmod u+x js
[alcyoneus ~/bin] ls -l js
-rwxr--r-- 1 poiu0 poiu0 5762777 Jul 27 11:18 js
[alcyoneus ~/bin] js --help
Segmentation fault

**Comment by GammaC0de** [comment]
This  file is not good either 😞

**Comment by GammaC0de** [comment]
Does this work?
`js24 --help`

**Comment by poste5** [comment]
[alcyoneus ~] js24 --help
-bash: js24: command not found

But I have not downloaded js24.

**Comment by GammaC0de** [comment]
I know, maybe its already installed

**Comment by poste5** [comment]
Couldn't it be that the js file require permission for ALL the users?

**Comment by GammaC0de** [comment]
`apt-get list | grep libmozjs`

**Comment by poste5** [comment]
[alcyoneus ~] apt-get list | grep libmozjs
E: Invalid operation list



It seem that it doesn't have ''list'':

[alcyoneus ~] apt-get
apt 1.0.9.8.4 for amd64 compiled on Dec 11 2016 09:48:19
Usage: apt-get [options] command
       apt-get [options] install|remove pkg1 [pkg2 ...]
       apt-get [options] source pkg1 [pkg2 ...]

apt-get is a simple command line interface for downloading and
installing packages. The most frequently used commands are update
and install.

Commands:
   update - Retrieve new lists of packages
   upgrade - Perform an upgrade
   install - Install new packages (pkg is libc6 not libc6.deb)
   remove - Remove packages
   autoremove - Remove automatically all unused packages
   purge - Remove packages and config files
   source - Download source archives
   build-dep - Configure build-dependencies for source packages
   dist-upgrade - Distribution upgrade, see apt-get(8)
   dselect-upgrade - Follow dselect selections
   clean - Erase downloaded archive files
   autoclean - Erase old downloaded archive files
   check - Verify that there are no broken dependencies
   changelog - Download and display the changelog for the given package
   download - Download the binary package into the current directory

Options:
  -h  This help text.
  -q  Loggable output - no progress indicator
  -qq No output except for errors
  -d  Download only - do NOT install or unpack archives
  -s  No-act. Perform ordering simulation
  -y  Assume Yes to all queries and do not prompt
  -f  Attempt to correct a system with broken dependencies in place
  -m  Attempt to continue if archives are unlocatable
  -u  Show a list of upgraded packages as well
  -b  Build the source package after fetching it
  -V  Show verbose version numbers
  -c=? Read this configuration file
  -o=? Set an arbitrary configuration option, eg -o dir::cache=/tmp
See the apt-get(8), sources.list(5) and apt.conf(5) manual
pages for more information and options.
                       This APT has Super Cow Powers.

**Comment by GammaC0de** [comment]
Does this work?
```
apt-get download libmozjs-24-bin
```

**Comment by poste5** [comment]
[alcyoneus ~] apt-get download libmozjs-24-bin
Get:1 http://ftp.nl.debian.org/debian/ jessie/main libmozjs-24-bin amd64 24.2.0-2 [1,692 kB]
Fetched 1,692 kB in 0s (9,264 kB/s)
[alcyoneus ~]

**Comment by GammaC0de** [comment]
Now do:
```
mkdir  /media/sdr1/poiu0/temp
dpkg -x /media/sdr1/poiu0/libmozjs-24-bin_24.2.0-2_amd64.deb  /media/sdr1/poiu0/temp
```

One of the unpacked files is js24.
Rename it to js and put it on your PATH then do `js --help` to test.

**Comment by poste5** [comment]
I have this (how do you copy-paste linux terminal here? If I use ''insert code'' it won't follow the lines):

[alcyoneus ~/bin] js --help
Usage: js [options] [[script] scriptArgs*]

  The SpiderMonkey shell provides a command line interface to the
  JavaScript engine. Code and file options provided via the command
  line are run left to right. If provided, the optional script argument
  is run after all options have been processed. Just-In-Time
  compilation modes may be enabled via command line options.

Version: JavaScript-C24.2.0

Arguments:
  script      A script to execute (after all options)
  scriptArgs  String arguments to bind as |scriptArgs| in the shell's global

Options:
  -f --file=PATH                      File path to run
  -e --execute=CODE                   Inline code to run
  -i --shell                          Enter prompt after running code
  -m --jm                             No-op (still used by fuzzers)
  --no-jm                             No-op (still used by fuzzers)
  -n --ti                             Enable type inference (default)
  --no-ti                             Disable type inference
  -c --compileonly                    Only compile, don't run (syntax checking
                                      mode)
  -w --warnings                       Emit warnings
  -W --nowarnings                     Don't emit warnings
  -s --strict                         Check strictness
  -d --debugjit                       Enable runtime debug mode for method JIT
                                      code
  -a --always-mjit                    No-op (still used by fuzzers)
  -D --dump-bytecode                  Dump bytecode with exec count for all
                                      scripts
  -b --print-timing                   Print sub-ms runtime for each file that's
                                      run
  --thread-count=COUNT                Use COUNT auxiliary threads (default: #
                                      of cores - 1)
  --ion                               Enable IonMonkey (default)
  --no-ion                            Disable IonMonkey
  --no-asmjs                          Disable asm.js compilation
  --ion-gvn=[mode]                    Specify Ion global value numbering:
                                        off: disable GVN
                                        pessimistic: (default) use pessimistic
                                      GVN
                                        optimistic: use optimistic GVN
  --ion-licm=on/off                   Loop invariant code motion (default: on,
                                      off to disable)
  --ion-edgecase-analysis=on/off      Find edge cases where Ion can avoid
                                      bailouts (default: on, off to disable)
  --ion-range-analysis=on/off         Range analysis (default: off, on to
                                      enable)
  --ion-inlining=on/off               Inline methods where possible (default:
                                      on, off to disable)
  --ion-osr=on/off                    On-Stack Replacement (default: on, off to
                                      disable)
  --ion-limit-script-size=on/off      Don't compile very large scripts
                                      (default: on, off to disable)
  --ion-uses-before-compile=COUNT     Wait for COUNT calls or iterations before
                                      compiling (default: 10240)
  --ion-regalloc=[mode]               Specify Ion register allocation:
                                        lsra: Linear Scan register allocation
                                      (default)
                                        backtracking: Priority based
                                      backtracking register allocation
                                        stupid: Simple block local register
                                      allocation
  --ion-eager                         Always ion-compile methods (implies
                                      --baseline-eager)
  --ion-parallel-compile=on/off       Compile scripts off thread (default: off)
  --baseline                          Enable baseline compiler (default)
  --no-baseline                       Disable baseline compiler
  --baseline-eager                    Always baseline-compile methods
  --baseline-uses-before-compile=COUNT Wait for COUNT calls or iterations before
                                      baseline-compiling (default: 10)
  --no-fpu                            Pretend CPU does not support
                                      floating-point operations to test JIT
                                      codegen (no-op on platforms other than
                                      x86).
  --fuzzing-safe                      Don't expose functions that aren't safe
                                      for fuzzers to call


Can I delete the libmozjs-24-bin_24.2.0-2_amd64.deb file and the temp folder?

**Comment by GammaC0de** [comment]
> Can I delete the libmozjs-24-bin_24.2.0-2_amd64.deb file and the temp folder?

Yes.


Plugin updated, please test.

**Comment by poste5** [comment]
The first download worked, the second and the others no. There is a Parse error: Free download form not found. But with other providers when the free download quota is reached there is a ''waiting'' form in the download section. Is that normal?




79 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Link name: ede6mgg5y1vv.html
80 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Link size: N/D
81 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Link status: starting
82 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Processing url: http://rockfile.eu/ede6mgg5y1vv.html
83 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Looking for direct download link...
84 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Direct download link not found
85 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Checking for link errors...
86 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: No errors found
87 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Grabbing link info...
88 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Link name: ede6mgg5y1vv.html
89 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Link size: N/D
90 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Link status: starting
91 | 28.07.2017 11:38:14 | INFO | HOSTER RockfileEu[451]: Processing as free download...
92 | 28.07.2017 11:38:14 | WARNING | Download failed: ede6mgg5y1vv.html \| Parse error: Free download form not found \| Plugin may be out of date
93 | 28.07.2017 11:38:14 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: ede6mgg5y1vv.html (pid:71)
94 | 28.07.2017 11:38:14 | INFO | ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
Can you send about 10 links to test?

**Comment by poste5** [comment]
Yes, sure:

http://rockfile.eu/baubw2a050ad.html
http://rockfile.eu/zeh3rg7s1twd.html
http://rockfile.eu/ede6mgg5y1vv.html
http://rockfile.eu/baubw2a050ad.html
http://rockfile.eu/zeh3rg7s1twd.html
http://rockfile.eu/ede6mgg5y1vv.html
http://rockfile.eu/x5ml3oioore9.html
http://rockfile.eu/7742lyyz0yjf.html
http://rockfile.eu/08a53el6cd25.html
http://rockfile.eu/znto8fmnr0it.html
http://rockfile.eu/lbqmml5srgbi.html
http://rockfile.eu/4t3r5xjnwure.html

**Comment by GammaC0de** [comment]
I cannot reproduce this issue, do you know hot to edit .py files?

Add this line below [RockfileEu.py#L47](https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/RockfileEu.py#L47)
```python
            self.dump_html()
```
then wait for the error to occur.

There will be a .html file in `<PYLOAD_HOME_DIR>/tmp/RockfileEu`, post it here.

**Comment by poste5** [comment]
Yes, I've edited the file with vi.

But... it's weird now I don't have that error anymore. Sometimes rockfiles.Eu works, other times it doesn't work. I don't know how to describe, it's a ''hit and miss'' thing, I have to restart n times the links that fail.
This time the error is a Bad server response: 503 Service Unavailable. By the way if I delete and recreate the package some times when it fails i can download the files. I'll do more test in the next hours.

About the <PYLOAD_HOME_DIR>/tmp/RockfileEu I think that it does't exit because the error is different. I've checked here /media/sdr1/poiu0/.pyload/tmp (right?), for now there are only these files

[alcyoneus ~/.pyload/tmp] ls
container_file  container_file_lock  jinja_cache



1134 | 29.07.2017 00:11:19 | WARNING | Download failed: [OPF-Italia] Dragon Ball Super 99 HD (sub ita).mp4 \| Bad server response: 503 Service Unavailable
1135 | 29.07.2017 00:11:19 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: [OPF-Italia] Dragon Ball Super 99 HD (sub ita).mp4 (pid:79)
1136 | 29.07.2017 00:11:19 | INFO | ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
I got "503 Service Unavailable" on some files too.
maybe they changed something, maybe the server is overloaded.

Retrying the download works though.

**Comment by GammaC0de** [comment]
Plugin updated to auto retry on "503".

**Comment by poste5** [comment]
Updated, thank you. Better now. The error this time is: Parse error: Captcha not found | Plugin may be out of date

524	29.07.2017 10:31:29	INFO	HOSTER RockfileEu[487]: Link name: 8jymvwbhcerv.html
525	29.07.2017 10:31:29	INFO	HOSTER RockfileEu[487]: Link size: 537.00 B (537 bytes)
526	29.07.2017 10:31:29	INFO	HOSTER RockfileEu[487]: Link status: online
527	29.07.2017 10:31:29	INFO	HOSTER RockfileEu[487]: Processing url: http://rockfile.eu/8jymvwbhcerv.html
528	29.07.2017 10:31:29	INFO	HOSTER RockfileEu[487]: Looking for direct download link...
529	29.07.2017 10:31:29	INFO	HOSTER RockfileEu[487]: Direct download link not found
530	29.07.2017 10:31:29	INFO	HOSTER RockfileEu[487]: Checking for link errors...
531	29.07.2017 10:31:29	INFO	HOSTER RockfileEu[487]: No errors found
532	29.07.2017 10:31:29	INFO	HOSTER RockfileEu[487]: Processing as free download...
533	29.07.2017 10:31:30	INFO	HOSTER RockfileEu[487]: Checking for link errors...
534	29.07.2017 10:31:30	INFO	HOSTER RockfileEu[487]: No errors found
535	29.07.2017 10:31:30	WARNING	CAPTCHA RockfileEu[487]: ReCaptcha | Key pattern not found
536	29.07.2017 10:31:30	WARNING	Download failed: 8jymvwbhcerv.html | Parse error: Captcha not found | Plugin may be out of date
537	29.07.2017 10:31:30	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 8jymvwbhcerv.html (pid:84)
538	29.07.2017 10:31:30	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
OK, so put:
```python
            self.dump_html()
```
between lines 79 and 80 and then post the HTML file here when error occurs.

**Comment by poste5** [comment]
This is the file, I should have copy-pasted it, but it's too long.

https://drive.google.com/file/d/0B9w-dVyQF7twVl9VZWNZM1ZkOE0/view?usp=sharing

**Comment by GammaC0de** [comment]
Can you download any file after this happens?

Can you download with a browser?

**Comment by poste5** [comment]
I don't have a browser on that device. But I can say that the downloads that failed due to the captcha error today worked. I didn't do anything, I didn't either restarted Pyload.

**Comment by GammaC0de** [comment]
The file you have sent contains "You have reached the download limit" which none of the other HTML pages have...

Is this the cause of this issue?
If yes, does retrying the file again works or do you have to wait  some time?
If you have to wait  some time, for how long?

Though questions...

**Comment by poste5** [comment]
For what I have seen If I retry the file when I have the captcha error it gives me the captcha error again. But after 8-10 hours it worked again. Maybe is Rockfile.eu the problem, today for example for some files at rockfile.eu I have the ''Max retries reached'', where there is a sort of ''waiting loop''... it waits... it reachs 0... then it waits again.

**Comment by GammaC0de** [comment]
How much did you downloaded until this happened?

**Comment by poste5** [comment]
I am sorry if I cannot be more usefull to improve the plugin, but Barely 4 GB.

Today:


800 | 01.08.2017 14:50:28 | WARNING | HOSTER RockfileEu[557]: Plugin may be unstable
-- | -- | -- | --
801 | 01.08.2017 14:50:28 | INFO | HOSTER RockfileEu[557]: Grabbing link info...
802 | 01.08.2017 14:50:28 | INFO | ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page
803 | 01.08.2017 14:50:28 | INFO | HOSTER RockfileEu[557]: Waiting 5 seconds...
804 | 01.08.2017 14:50:30 | INFO | Download starts: lwvr723bpzeh.html
805 | 01.08.2017 14:50:30 | WARNING | HOSTER RockfileEu[558]: Plugin may be unstable
806 | 01.08.2017 14:50:30 | INFO | HOSTER RockfileEu[558]: Grabbing link info...
807 | 01.08.2017 14:50:30 | INFO | ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page
808 | 01.08.2017 14:50:30 | INFO | HOSTER RockfileEu[558]: Waiting 5 seconds...
809 | 01.08.2017 14:50:32 | INFO | HOSTER RockfileEu[556]: Link name: xbd486nbv7cv.html
810 | 01.08.2017 14:50:32 | INFO | HOSTER RockfileEu[556]: Link size: N/D
811 | 01.08.2017 14:50:32 | INFO | HOSTER RockfileEu[556]: Link status: offline
812 | 01.08.2017 14:50:32 | WARNING | Download is offline: xbd486nbv7cv.html

For these links... but they are not offline
http://rockfile.eu/xbd486nbv7cv.html
http://rockfile.eu/2clw76r71k0k.html
http://rockfile.eu/lwvr723bpzeh.html

**Comment by GammaC0de** [comment]
I will tread this situation as "temp offline" then.

I guess we are in a cat and mouse chase, they changed the site again....

Plugin updated again to deal with the "offline" issue.

**Comment by poste5** [comment]
Today 

451 | 02.08.2017 12:09:17 | WARNING | Download failed: pj7widlvjdnd.html \| Parse error: Form F1 not found \| Plugin may be out of date
 
:P

**Comment by GammaC0de** [comment]
Update (again), please check.

**Comment by poste5** [comment]
Today it worked, I'll more tests.

**Comment by GammaC0de** [comment]
Can we close this?

**Comment by poste5** [comment]
I've done some other test, now it ask for a manual captcha request. But after resolving the captcha manually the download work.

**Comment by GammaC0de** [comment]
>I've done some other test, now it ask for a manual captcha request. But after resolving the captcha manually the download work.

Do you mean that it asks you to solve captcha? if so, this is normal.

You can use one of captcha solving plugins to automatically solve the captcha (9kw.eu is recommended if you don't want to pay for a captcha solving service.)

**Comment by poste5** [comment]
Yes, I mean that. I've already connected 9kw.eu api with pyload, but probably those captcha there weren't in their archive. 

Another 3 tests today, after manually resolving the captcha they worked.

**Comment by GammaC0de** [comment]
>but probably those captcha there weren't in their archive.

What do you mean by that?

To use 9kw.eu you have to solve some captchas on 9kw.eu web site.
By  solving captchas on 9kw.eu web site, you earn captcha credits.
The captcha credits is used by pyload to solve your captchas.

**Comment by poste5** [comment]
These are my settings:
http://imgur.com/mj55VGI
http://imgur.com/4mS1vR7 (I've deleted that API now)
http://imgur.com/GGIqy5f

But I have to manually resolve Captcha. I have credit.

**Comment by GammaC0de** [comment]
"Don't use if client is connected" is on, which means that if you are connected to the WebUI you will have to solve captchas manually.

**Comment by poste5** [comment]
LOL... what a dude... now it works! Thank you ;)

**Comment by GammaC0de** [comment]
👍 Closing this.
If you have more question, please open a new issue.
