### ISSUE TITLE
[Question] how do I start the web UI on Windows10?

### ISSUE THREAD

**Issue by aendry** [pyload/pyload#2908]
I'm totally new and IDK where to start. I already setup the program, when I launched it appears a message saing that the interface is not stable yet and to try to use the UI but IDK how to do that. there is no youtube videos to help me out

**Comment by GammaC0de** [comment]
How exactly did you installed pyLoad?

**Comment by aendry** [comment]
Following the instructions. (That needs to be uploaded). Executing the setup.py of every module

**Comment by GammaC0de** [comment]
@aendry Please read #2000

**Comment by aendry** [comment]
Ok

**Comment by GammaC0de** [comment]
Well!?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by aendry** [comment]
I did it. Haven't been able to do it for matter of time. I opened the UpdateManager.py file with NotePad++ copy pasted the code, then run setup, then run core to apply the updates, when the core gets connected to the port I launched the GUI that still says that it is not working properly and instead encourages you to use the web interface... But this time worked perfectly. So it's solved. Thanks a lot. Now I just need to learn how to use it :)

**Comment by GammaC0de** [comment]
👍

**Comment by aendry** [comment]
One question. Is there a way to launch the webUI after launching the core automatically? Or make the core launches the webUI without the need of do it for separate?

**Comment by GammaC0de** [comment]
I would write a batch file that:
1. start the core
2. wait for some time
3. start the web browser with pyload's URL

**Comment by aendry** [comment]
The core can be executed on start up to run in the background? That will be a good solution. Just need to click on the launcher app and done

**Comment by GammaC0de** [comment]
I think so.
