### ISSUE TITLE
Bug plugins FshareVN 'ascii' codec can't encode

### ISSUE THREAD

**Issue by bigdargon** [pyload/pyload#2909]
Plugin error for Chinese characters, so you can not name File when downloading. Can you fix it?
Link https://www.fshare.vn/file/RUOICUY241MS
> 26.07.2017 08:16:52 WARNING   Download failed: https://www.fshare.vn/file/RUOICUY241MS | 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

And pyload has trouble decoding the directory of FshareVN, although the link in the browser is normal, but when added to the pyload offilne error.
Link https://www.fshare.vn/folder/THXANAFRST
> 25.07.2017 07:50:20 INFO      CRYPTER FshareVnFolder[192]: Link name: THXANAFRST
25.07.2017 07:50:20 INFO      CRYPTER FshareVnFolder[192]: Link size: N/D
25.07.2017 07:50:20 INFO      CRYPTER FshareVnFolder[192]: Link status: temp. offline
25.07.2017 07:50:20 ERROR     Decrypting failed: THXANAFRST | temp. offline

**Comment by GammaC0de** [comment]
pyload cannot handle Chinese characters because of a bug that cannot be fixed without a major rewrite of the code.
So this cannot be fixed until the next pyload release.

Try implementing #2106 and see if it helps (Chinese characters supposedd to be removed)

**Comment by bigdargon** [comment]
I added but pyload autoremove
> 26.07.2017 09:16:26 INFO      ADDON UpdateManager: Removed blacklisted plugin: INTERNAL utils

**Comment by GammaC0de** [comment]
@bigdargon The PR is outdated, you should edit `misc.py`, not `utils.py`.

**Comment by bigdargon** [comment]
@GammaC0de How to edit? misc.py is 0.46.

**Comment by GammaC0de** [comment]
See the changes (https://github.com/pyload/pyload/pull/2106/files), leave the version as is.

**Comment by bigdargon** [comment]
It still does not work. Anyway thank you for supporting FshareVN plugins, I downloaded about 2,000 links with Pyload. Just a few links so I will download manually. Hope the next version will fix this problem.
