### ISSUE TITLE
[Request plugin] Upfile.vn

### ISSUE THREAD

**Issue by bigdargon** [pyload/pyload#2917]
Upfile.vn is a host in Vietnam, upfile.vn allows for free download and no paid account. Just register a free account download speed can be up to 3MB/s and do not have to wait, if no account is about 1MB/s have to wait about 5s. Please write plugins for this host! Thank you very much!
Link test: ~~http://upfile.vn/ysGtukZCu~BC/47-meters-down-2016-hdrip-xvid-ac3-evo-mp4.html~~ file deleted
Link no password: http://upfile.vn/T-GmNTBmu~BC/adguard-v6-1-331-1732-rar.html
Link with password: http://upfile.vn/FVBtAkjCNQGg/itoolssetup3-3-9-6-exe.html
Password 123456

**Comment by GammaC0de** [comment]
None of the links abov are password protected..

The weird thing  is that is can download "deleted" files...

**Comment by bigdargon** [comment]
Thank you very much. Upfile.vn seems a lot of bugs. I have added a password to the file but still can not load without entering the password (?!) The file I sent above has not been deleted, but when I click on the link the error 404.
Once again thank you very much!

**Comment by GammaC0de** [comment]
@bigdargon Can you explain the issues in detail? I could not understand what you were trying to say..
