### ISSUE TITLE
[Premium.To] won't add account

### ISSUE THREAD

**Issue by N14tr0** [pyload/pyload#2926]
Hey dear pyLoad-Team,

I use pyLoad on a raspberry-Pi and it works just fine. But if I try to add my "premium.to" account it just freezes and the service has to be restarted.

Output from "sudo systemctl status pyload -l"

```
● pyload.service - Python Downloader
   Loaded: loaded (/etc/systemd/system/pyload.service; enabled)
   Active: active (running) since Fr 2017-08-11 10:31:26 UTC; 31s ago
 Main PID: 12022 (python)
   CGroup: /system.slice/pyload.service
           └─12022 /usr/bin/python /opt/pyload/pyLoadCore.py

Aug 11 10:31:29 raspberrypi python[12022]: 11.08.2017 10:31:29 INFO      Activating Plugins...
Aug 11 10:31:30 raspberrypi python[12022]: 11.08.2017 10:31:30 INFO      ADDON XFileSharing: Auto-discover new hosters
Aug 11 10:31:30 raspberrypi python[12022]: 11.08.2017 10:31:30 INFO      ADDON XFileSharing: Auto-discover new crypters
Aug 11 10:31:30 raspberrypi python[12022]: 11.08.2017 10:31:30 INFO      ADDON UpdateManager: pyLoad is up to date!
Aug 11 10:31:30 raspberrypi python[12022]: 11.08.2017 10:31:30 INFO      pyLoad is up and running
Aug 11 10:31:30 raspberrypi python[12022]: 11.08.2017 10:31:30 INFO      ADDON UpdateManager: All plugins are up to date!
Aug 11 10:31:36 raspberrypi python[12022]: 11.08.2017 10:31:36 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
Aug 11 10:31:54 raspberrypi python[12022]: 11.08.2017 10:31:54 INFO      ACCOUNT PremiumTo: Adding user dw9*******...
Aug 11 10:31:54 raspberrypi python[12022]: 11.08.2017 10:31:54 INFO      ACCOUNT PremiumTo: Login user dw9*******...
Aug 11 10:31:54 raspberrypi python[12022]: 11.08.2017 10:31:54 INFO      ACCOUNT PremiumTo: Grabbing account info for user dw9*******...
```

Note: This was right after a restart. But if I let it run for a hour it won't change anything.

The strange thing is -> First I've did it with the wrong password and the account showed up immediatly (but not avaliable - which is correct because of the PW), I removed it, entered the correct credentials and now I'm stuck at this point.

If you need any more infos, just tell it to me, I will gladly reach them out.

Greetings,
N14tr0

![2017-08-11 10_35_12-fsx nsupdate info - kitty](https://user-images.githubusercontent.com/25324740/29206152-ede9cb38-7e80-11e7-93de-a782bbb87dd8.png)
![2017-08-11 10_35_52-einstellungen - pyload weboberflache](https://user-images.githubusercontent.com/25324740/29206153-ede9ef00-7e80-11e7-972f-ebfea3d627f4.png)

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by N14tr0** [comment]
You've got an email (:

**Comment by N14tr0** [comment]
Works like a charm! 

Thanks for that fast fix!

**Comment by GammaC0de** [comment]
👍
