### ISSUE TITLE
Filer.net Not working anymore

### ISSUE THREAD

**Issue by djoliboli** [pyload/pyload#2928]
264	12.08.2017 14:41:43	WARNING	HOSTER FilerNet[214]: Plugin may be unstable
265	12.08.2017 14:41:43	INFO	ACCOUNT FilerNet: Grabbing account info for user `max*******`...
266	12.08.2017 14:41:43	ERROR	ACCOUNT FilerNet: Unable to retrieve account information
267	12.08.2017 14:41:43	INFO	HOSTER FilerNet[214]: Grabbing link info...
268	12.08.2017 14:41:43	INFO	HOSTER FilerNet[214]: Link name: sdsfsdfsfsfd20161026112934.part52.rar
269	12.08.2017 14:41:43	INFO	HOSTER FilerNet[214]: Link size: 150.00 MiB (157286400 bytes)
270	12.08.2017 14:41:43	INFO	HOSTER FilerNet[214]: Link status: online
271	12.08.2017 14:41:43	INFO	HOSTER FilerNet[214]: Processing url: https://filer.net/get/ok0ujawpjedoiqek
272	12.08.2017 14:41:43	INFO	HOSTER FilerNet[214]: Looking for direct download link...
273	12.08.2017 14:41:45	INFO	HOSTER FilerNet[214]: Direct download link not found
274	12.08.2017 14:41:45	INFO	HOSTER FilerNet[214]: Checking for link errors...
275	12.08.2017 14:41:45	INFO	HOSTER FilerNet[214]: No errors found
276	12.08.2017 14:41:45	INFO	HOSTER FilerNet[214]: Processing as free download...
277	12.08.2017 14:41:45	WARNING	Download failed: sdsfsdfsfsfd20161026112934.part52.rar | argument of type 'NoneType' is not iterable
278	12.08.2017 14:41:45	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: sdsfsdfsfsfd20161026112934.part52.rar (pid:28)
279	12.08.2017 14:41:45	INFO	ADDON UnSkipOnFail: No duplicates found
280	12.08.2017 14:41:47	INFO	Download starts: sdsfsdfsfsfd20161026112934.part53.rar
281	12.08.2017 14:41:47	WARNING	HOSTER FilerNet[215]: Plugin may be unstable
282	12.08.2017 14:41:47	INFO	ACCOUNT FilerNet: Grabbing account info for user `max*******`...
283	12.08.2017 14:41:47	ERROR	ACCOUNT FilerNet: Unable to retrieve account information
284	12.08.2017 14:41:47	INFO	HOSTER FilerNet[215]: Grabbing link info...
285	12.08.2017 14:41:47	INFO	HOSTER FilerNet[215]: Link name: sdsfsdfsfsfd20161026112934.part53.rar
286	12.08.2017 14:41:47	INFO	HOSTER FilerNet[215]: Link size: 141.00 MiB (147849216 bytes)
287	12.08.2017 14:41:47	INFO	HOSTER FilerNet[215]: Link status: online
288	12.08.2017 14:41:48	INFO	HOSTER FilerNet[215]: Processing url: https://filer.net/get/lambotdc9v8fpl9m
289	12.08.2017 14:41:48	INFO	HOSTER FilerNet[215]: Looking for direct download link...
290	12.08.2017 14:41:48	INFO	HOSTER FilerNet[215]: Direct download link not found
291	12.08.2017 14:41:48	INFO	HOSTER FilerNet[215]: Checking for link errors...
292	12.08.2017 14:41:48	INFO	HOSTER FilerNet[215]: No errors found
293	12.08.2017 14:41:48	INFO	HOSTER FilerNet[215]: Processing as free download...
294	12.08.2017 14:41:48	WARNING	Download failed: sdsfsdfsfsfd20161026112934.part53.rar | argument of type 'NoneType' is not iterable
295	12.08.2017 14:41:48	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: sdsfsdfsfsfd20161026112934.part53.rar (pid:28)
296	12.08.2017 14:41:48	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
I see that you have an account at FilerNet, is this a premium account?

**Comment by djoliboli** [comment]
Yes my Account is a Premium Account
I found the problem
Dircet download was disabled in profile settings
But pyload still says no premium and do Not start more than one download at
the same time

GammaC0de <notifications@github.com> schrieb am Sa., 12. Aug. 2017, 14:59:

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.
