### ISSUE TITLE
Filer.Net package name

### ISSUE THREAD

**Issue by djoliboli** [pyload/pyload#2929]
If I add a Package and inserting a Filer.net folder link the package is added to the queue with the right name 
After a short time the package automaticly get renamed to unknown.

**Comment by GammaC0de** [comment]
It does not happen to me (free download), can you check with free download and tell if it makes a difference?

**Comment by djoliboli** [comment]
Same Problem with free Download 
After returning to premium the last link of a folder is placed in a separate  package 

ADDON RestartFailed: Restarting all failed downloads...
518	14.08.2017 06:04:35	INFO	Added package Der Walter horz containing 1 links
519	14.08.2017 06:04:36	INFO	Decrypting starts: https://filer.net/folder/10fthzl99xseujns
520	14.08.2017 06:04:36	WARNING	CRYPTER FilerNetFolder[597]: Plugin may be unstable
521	14.08.2017 06:04:36	INFO	ACCOUNT FilerNet: Grabbing account info for user `max*******`...
522	14.08.2017 06:04:37	INFO	CRYPTER FilerNetFolder[597]: Grabbing link info...
523	14.08.2017 06:04:37	INFO	CRYPTER FilerNetFolder[597]: Link name: hjzgizfjhsdfgtsrt
524	14.08.2017 06:04:37	INFO	CRYPTER FilerNetFolder[597]: Link size: N/D
525	14.08.2017 06:04:37	INFO	CRYPTER FilerNetFolder[597]: Link status: online
526	14.08.2017 06:04:37	INFO	CRYPTER FilerNetFolder[597]: Processing url: https://filer.net/folder/10fthzl99xseujns
527	14.08.2017 06:04:37	INFO	CRYPTER FilerNetFolder[597]: Looking for direct link...
528	14.08.2017 06:04:38	INFO	CRYPTER FilerNetFolder[597]: Direct link not found
529	14.08.2017 06:04:38	INFO	CRYPTER FilerNetFolder[597]: Checking for link errors...
530	14.08.2017 06:04:38	INFO	CRYPTER FilerNetFolder[597]: No errors found
531	14.08.2017 06:04:38	INFO	CRYPTER FilerNetFolder[597]: Decrypting as premium link...
532	14.08.2017 06:04:38	INFO	CRYPTER FilerNetFolder[597]: Create package: unknown | 25 links
533	14.08.2017 06:04:38	INFO	Added package unknown containing 25 links
534	14.08.2017 06:04:38	INFO	CRYPTER FilerNetFolder[597]: Save package `unknown` to folder: unknown
535	14.08.2017 06:04:38	INFO	CRYPTER FilerNetFolder[597]: Create package: 2thkjfbumkqs8 | 1 links
536	14.08.2017 06:04:38	INFO	Added package 2thkjfbumkqs8 containing 1 links

**Comment by djoliboli** [comment]
Since today the same problem reappears

`27.08.2017 21:30:11	INFO	Added package Guardian of Galaxy 2 containing 1 links
107	27.08.2017 21:30:12	INFO	Decrypting starts: https://filer.net/folder/lbzgbooh26fuegoa
108	27.08.2017 21:30:12	WARNING	CRYPTER FilerNetFolder[204]: Plugin may be unstable
109	27.08.2017 21:30:12	INFO	ACCOUNT FilerNet: Grabbing account info for user `max*******`...
110	27.08.2017 21:30:13	INFO	CRYPTER FilerNetFolder[204]: Grabbing link info...
111	27.08.2017 21:30:14	INFO	CRYPTER FilerNetFolder[204]: Link name: gdrtzuztkjdfsrzt
112	27.08.2017 21:30:14	INFO	CRYPTER FilerNetFolder[204]: Link size: N/D
113	27.08.2017 21:30:14	INFO	CRYPTER FilerNetFolder[204]: Link status: online
114	27.08.2017 21:30:14	INFO	CRYPTER FilerNetFolder[204]: Processing url: https://filer.net/folder/lbzgbooh26fuegoa
115	27.08.2017 21:30:14	INFO	CRYPTER FilerNetFolder[204]: Looking for direct link...
116	27.08.2017 21:30:15	INFO	CRYPTER FilerNetFolder[204]: Direct link not found
117	27.08.2017 21:30:15	INFO	CRYPTER FilerNetFolder[204]: Checking for link errors...
118	27.08.2017 21:30:15	INFO	CRYPTER FilerNetFolder[204]: No errors found
119	27.08.2017 21:30:15	INFO	CRYPTER FilerNetFolder[204]: Decrypting as premium link...
120	27.08.2017 21:30:15	INFO	CRYPTER FilerNetFolder[204]: Create package: gdrtzuztkjdfsrzt | 40 links
121	27.08.2017 21:30:15	INFO	Added package gdrtzuztkjdfsrzt containing 40 links
122	27.08.2017 21:30:15	INFO	CRYPTER FilerNetFolder[204]: Save package `gdrtzuztkjdfsrzt` to folder: gdrtzuztkjdfsrzt
`

**Comment by GammaC0de** [comment]
@djoliboli Please open a new issue, thanks.
