### ISSUE TITLE
Alldebrid.com login handshake failure error

### ISSUE THREAD

**Issue by thornzz** [pyload/pyload#2933]
Hi
Im getting login handshake failure error ;

964 | 16.08.2017 08:52:19 | INFO | ACCOUNT AlldebridCom: Updating account info for user `tho*******`...
-- | -- | -- | --
965 | 16.08.2017 08:52:20 | INFO | ACCOUNT AlldebridCom: Updating account info for user `tho*******`...
966 | 16.08.2017 08:54:08 | ERROR | ADDON ClickNLoad: [Errno 98] Address already in use
967 | 16.08.2017 08:55:09 | INFO | restarting pyLoad
968 | 16.08.2017 08:55:09 | INFO | shutting down...
969 | 16.08.2017 08:55:09 | INFO | ADDON ClickNLoad: Shutting down proxy...
970 | 16.08.2017 08:55:19 | WARNING | ADDON ClickNLoad: Server was not exited gracefully, shutdown forced
971 | 16.08.2017 08:55:20 | INFO | Starting pyLoad 0.4.9
972 | 16.08.2017 08:55:20 | INFO | Using home directory: /home/hd1/thorn/.config/pyload
973 | 16.08.2017 08:55:20 | INFO | Activated plugins: BypassCaptcha, Checksum, ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, ImageTyperz, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
974 | 16.08.2017 08:55:20 | INFO | Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, Captcha9Kw, CaptchaBrotherhood, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
975 | 16.08.2017 08:55:20 | INFO | Downloadtime: True
976 | 16.08.2017 08:55:21 | INFO | Starting threaded webserver: 0.0.0.0:52069
977 | 16.08.2017 08:55:21 | INFO | Free space: 3.01 TiB
978 | 16.08.2017 08:55:21 | INFO | Activating Accounts...
979 | 16.08.2017 08:55:21 | INFO | ACCOUNT AlldebridCom: Adding user `tho*******`...
980 | 16.08.2017 08:55:21 | INFO | ACCOUNT AlldebridCom: Login user `tho*******`...
981 | 16.08.2017 08:55:21 | ERROR | ACCOUNT AlldebridCom: Could not login user `tho*******` \| Login handshake has failed
982 | 16.08.2017 08:55:21 | INFO | Activating Plugins...
983 | 16.08.2017 08:55:21 | INFO | ADDON XFileSharing: Auto-discover new hosters
984 | 16.08.2017 08:55:21 | INFO | ADDON XFileSharing: Auto-discover new crypters
985 | 16.08.2017 08:55:21 | INFO | pyLoad is up and running
986 | 16.08.2017 08:55:21 | INFO | ADDON UpdateManager: pyLoad is up to date!
987 | 16.08.2017 08:55:21 | INFO | ADDON UpdateManager: All plugins are up to date!
988 | 16.08.2017 08:55:23 | ERROR | ACCOUNT AlldebridCom: Could not load hoster list - invalid account, retry in 5 minutes
989 | 16.08.2017 08:55:27 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
990 | 16.08.2017 08:55:27 | ERROR | ADDON ClickNLoad: [Errno 98] Address already in use
991 | 16.08.2017 08:55:29 | INFO | ACCOUNT AlldebridCom: Updating account info for user `tho*******`...
992 | 16.08.2017 08:55:29 | INFO | ACCOUNT AlldebridCom: Relogin user `tho*******`...
993 | 16.08.2017 08:55:30 | ERROR | ACCOUNT AlldebridCom: Could not login user `tho*******` \| Login handshake has failed
994 | 16.08.2017 08:55:38 | INFO | ACCOUNT AlldebridCom: Updating account info for user `tho*******`...
995 | 16.08.2017 08:55:38 | INFO | ACCOUNT AlldebridCom: Relogin user `tho*******`...
996 | 16.08.2017 08:55:38 | ERROR | ACCOUNT AlldebridCom: Could not login user `tho*******` \| Login handshake has failed
997 | 16.08.2017 08:55:41 | ERROR | ACCOUNT AlldebridCom: Could not load hoster list - invalid account, retry in 5 minutes

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
No response, closing.
