### ISSUE TITLE
Downloads doesn't start

### ISSUE THREAD

**Issue by Catskan** [pyload/pyload#2935]
Hi,

I set up my Pyload install on a Synology DS716+II (DSM6) and the process start and I can access to the webui.

But, when I add a new package "vlc" with the direct link of vlc, the package stay on "Queued". I tried to restart the download and same problem.
I tried with an other link, and same problem.

Also, when I tried to click on "Information" page, I have the error : 
```
An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/volume1/@appstore/pyload/share/pyload/module/lib/bottle.py", line 734, in _handle
return route.call(**args)
File "/volume1/@appstore/pyload/share/pyload/module/lib/bottle.py", line 1449, in wrapper
rv = callback(*a, **ka)
File "/volume1/@appstore/pyload/share/pyload/module/web/pyload_app.py", line 528, in info
"freespace": formatSize(PYLOAD.freeSpace()),
File "/volume1/@appstore/pyload/share/pyload/module/Api.py", line 238, in freeSpace
return freeSpace(self.core.config["general"]["download_folder"])
File "/volume1/@appstore/pyload/share/pyload/module/utils.py", line 112, in freeSpace
s = statvfs(folder)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 19: ordinal not in range(128)
```

The debug mode is activate. 
I tried too to add `import unicodedata` in the bottle.py and doesn't works. Errors are same.

Can you help me with this please ? :)

Thanks you in advance.

Regards

**Comment by ohaucke** [comment]
Could you show us the url you are using? `\xe9` is `é` and i don't think that vlc uses such a char in its url for the download?
Could you test the following url `http://ipv4.download.thinkbroadband.com/50MB.zip`

**Comment by GammaC0de** [comment]
@Catskan Does your download folder path contains non ASCII characters like "ç" or "é" ?

**Comment by Catskan** [comment]
Oh yes. My download folder has "é" in the name.
I change the directory and it's ok ! Works great :D. 

Thanks guys :)
