### ISSUE TITLE
alldebrid issue

### ISSUE THREAD

**Issue by damien599901** [pyload/pyload#2939]
Hi 

alldebrid premium account does not work anymore
might you help me?
extract of log 

122 | 24.08.2017 21:21:30 | WARNING | HOSTER AlldebridCom[21]: AlldebridCom \| Plugin may be unstable
-- | -- | -- | --
123 | 24.08.2017 21:21:30 | INFO | ACCOUNT AlldebridCom: Grabbing account info for user `dam*******`...
124 | 24.08.2017 21:21:30 | WARNING | ACCOUNT AlldebridCom: Error loading info for user `dam*******` \| junk after document element: line 1, column 318
125 | 24.08.2017 21:21:30 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Grabbing link info...
126 | 24.08.2017 21:21:30 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link name: xxxxxxxxxxxxxxxx
127 | 24.08.2017 21:21:30 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link size: N/D
128 | 24.08.2017 21:21:30 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link status: en ligne
129 | 24.08.2017 21:21:30 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Processing url: xxxxxxxxxxxxxxxx
130 | 24.08.2017 21:21:31 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Checking for link errors...
131 | 24.08.2017 21:21:31 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| No errors found
132 | 24.08.2017 21:21:31 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Processing as free download...

**Comment by GammaC0de** [comment]
Cheking..

**Comment by GammaC0de** [comment]
What version is your AlldebridCom plugin?

Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by damien599901** [comment]
"What version is your AlldebridCom plugin?" => who to proceed?

2017-08-24 21:52 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by damien599901** [comment]
how to proceed

2017-08-24 23:06 GMT+02:00 Damien TELLE <damien599901@gmail.com>:

**Comment by GammaC0de** [comment]
Somehow, It asks me for the PIN again...

**Comment by damien599901** [comment]
the geo-localisation is disabled
please give another try

2017-08-24 23:08 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
Well, AlldebridCom did a nasty thing that breaks the API access:
They started to use CloudFlare's DDoS protection on the API URL.

That is, they are sending an HTML with JavaScript challenge instead the account information..

Please contact their support, I will try to see if I can solve it from our end but better that they will fix it.

**Comment by GammaC0de** [comment]
EDIT:
It's actually CloudFlare's email protection.

Still investigating..

**Comment by GammaC0de** [comment]
One more find:
AlldebridCom has API v2, maybe they disabled v1 that pyload uses.
