### ISSUE TITLE
I am having trouble with k2s downloads

### ISSUE THREAD

**Issue by digimon04** [pyload/pyload#2940]
I am having trouble with k2s downloads which lasts for several weeks . During the time, I have re-installed Pyload but it didn't work either. The log is below:

> Download starts: https://k2s.cc/file/a534e4815d51a/Wunder_Woman_Mask_Of_Kashnaktu_1.part3.rar
115	25.08.2017 17:28:08	WARNING	HOSTER Keep2ShareCc[15]: Plugin may be unstable
116	25.08.2017 17:28:08	INFO	HOSTER Keep2ShareCc[15]: Grabbing link info...
117	25.08.2017 17:28:09	INFO	HOSTER Keep2ShareCc[15]: Link name: Wunder Woman Ma... 1.part3.rar
118	25.08.2017 17:28:09	INFO	HOSTER Keep2ShareCc[15]: Link size: 300.50 MiB (315097088 bytes)
119	25.08.2017 17:28:09	INFO	HOSTER Keep2ShareCc[15]: Link status: online
120	25.08.2017 17:28:09	INFO	HOSTER Keep2ShareCc[15]: Processing url: https://k2s.cc/file/a534e4815d51a/Wunder_Woman_Mask_Of_Kashnaktu_1.part3.rar
121	25.08.2017 17:28:09	INFO	HOSTER Keep2ShareCc[15]: Looking for direct download link...
122	25.08.2017 17:28:12	INFO	HOSTER Keep2ShareCc[15]: Direct download link not found
123	25.08.2017 17:28:15	INFO	HOSTER Keep2ShareCc[15]: Processing as free download...
124	25.08.2017 17:28:18	WARNING	Download failed: Wunder Woman Ma... 1.part3.rar | Parse error: Unique-ID pattern not found | Plugin may be out of date
125	25.08.2017 17:28:18	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Wunder Woman Ma... 1.part3.rar (pid:10)

> 126 25.08.2017 17:28:18	INFO	ADDON UnSkipOnFail: No duplicates found

I hope the maintainer could fix it and thanks in advance.

**Comment by GammaC0de** [comment]
Fixed but you have to replace `HTTPRequest.py` with this one: https://github.com/pyload/pyload/blob/6b779646ebf3c023c65021d9caab71b62f3d6e73/module/network/HTTPRequest.py to be able to use the updated plugin.
