### ISSUE TITLE
FreeNAS ZFS freeSpace problem

### ISSUE THREAD

**Issue by tatu007** [pyload/pyload#2941]
Hello,

pyLoad (stable branch) say a completly strange freespace (more than available).

I have solved my problem with the change of one line in module/utils.py (line 113) :
`        return s.f_bsize * s.f_bavail`
to
`        return s.f_frsize * s.f_bavail`

**Comment by ohaucke** [comment]
freeSpace fix for FreeBSD #1179
> vuolter commented on 26 Mar 2015 
> Already in 0.4.10 .
