### ISSUE TITLE
Keep2ShareCc.py incorrect queue hadling with new API 

### ISSUE THREAD

**Issue by mahdi1234** [pyload/pyload#2942]
Hi,

after recent change in commit 672bd26b11d78a5d50b34d72ee2faf02c460d471 Keep2ShareCc.py processes all files at the same time, thus requests captcha for all downloads despite the fact free account can run only single download at the time. This leads to this problem - credits for captcha are withdrawn, but the files are never downloaded as parallel downloads are not allowed.

Older mechanism asked for captcha only when it was possible to make another download.

Would be great to somehow get this back as it is not really working right now.

cheers ...

**Comment by GammaC0de** [comment]
> Older mechanism asked for captcha only when it was possible to make another download.

This is not possible with API.

Plugin was not working anymore, that's why the switch to API (should be more stable).

Plugin updated, please test.

**Comment by mahdi1234** [comment]
Thanks it's much better now. Though as can be seen it asks for captcha multiple times ... since I only had time for couple downloads so far, will it be always twice or it's some arbitrary timeout and it'd be more times?

> 3 28.08.2017 16:06:44	INFO	Download finished: XYZ.zip
> 4	28.08.2017 16:06:46	INFO	Download starts: https://k2s.cc/file/something.zip
> 5	28.08.2017 16:06:46	WARNING	HOSTER Keep2ShareCc[18]: Plugin may be unstable
> 6	28.08.2017 16:06:46	INFO	HOSTER Keep2ShareCc[18]: Grabbing link info...
> 7	28.08.2017 16:06:47	INFO	HOSTER Keep2ShareCc[18]: Link name: something.zip
> 8	28.08.2017 16:06:47	INFO	HOSTER Keep2ShareCc[18]: Link size: 598.72 MiB (627803166 bytes)
> 9	28.08.2017 16:06:47	INFO	HOSTER Keep2ShareCc[18]: Link status: online
> 10	28.08.2017 16:06:47	INFO	HOSTER Keep2ShareCc[18]: Processing url: https://k2s.cc/file/something.zip
> 11	28.08.2017 16:06:47	INFO	HOSTER Keep2ShareCc[18]: Looking for direct download link...
> 12	28.08.2017 16:06:48	INFO	HOSTER Keep2ShareCc[18]: Direct download link not found
> 13	28.08.2017 16:06:48	INFO	HOSTER Keep2ShareCc[18]: Checking for link errors...
> 14	28.08.2017 16:06:48	INFO	HOSTER Keep2ShareCc[18]: No errors found
> 15	28.08.2017 16:06:48	INFO	HOSTER Keep2ShareCc[18]: Processing as free download...
> 16	28.08.2017 16:06:49	INFO	CAPTCHA Keep2ShareCc[18]: Captcha | Using OCR to decrypt captcha...
> 17	28.08.2017 16:06:49	WARNING	CAPTCHA Keep2ShareCc[18]: Captcha | No OCR result
> 18	28.08.2017 16:06:50	INFO	ADDON Captcha9Kw: 125 credits left
> 19	28.08.2017 16:10:26	INFO	ADDON Captcha9Kw: Captcha result for ticket 89940594: jodapan
> 20	28.08.2017 16:10:27	INFO	CAPTCHA Keep2ShareCc[18]: Captcha | Captcha result: `jodapan`
> 21	28.08.2017 16:10:27	INFO	CAPTCHA Keep2ShareCc[18]: Captcha | Path deleted: /pyload/.pyload/tmp/captcha_image_Keep2ShareCc_40972.jpg
> 22	28.08.2017 16:10:28	INFO	CAPTCHA Keep2ShareCc[18]: Captcha | Correct captcha | jodapan
> 23	28.08.2017 16:10:28	INFO	HOSTER Keep2ShareCc[18]: Waiting 56 minutes, 4 seconds...
> 24	28.08.2017 17:06:33	INFO	Download restarted: something.zip |
> 25	28.08.2017 17:06:34	INFO	Download starts: something.zip
> 26	28.08.2017 17:06:34	WARNING	HOSTER Keep2ShareCc[18]: Plugin may be unstable
> 27	28.08.2017 17:06:34	INFO	HOSTER Keep2ShareCc[18]: Grabbing link info...
> 28	28.08.2017 17:06:34	INFO	HOSTER Keep2ShareCc[18]: Link name: something.zip
> 29	28.08.2017 17:06:34	INFO	HOSTER Keep2ShareCc[18]: Link size: 598.72 MiB (627803166 bytes)
> 30	28.08.2017 17:06:34	INFO	HOSTER Keep2ShareCc[18]: Link status: online
> 31	28.08.2017 17:06:34	INFO	HOSTER Keep2ShareCc[18]: Processing url: https://keep2s.cc/file/9c6fc3ebf829f
> 32	28.08.2017 17:06:34	INFO	HOSTER Keep2ShareCc[18]: Looking for direct download link...
> 33	28.08.2017 17:06:35	INFO	HOSTER Keep2ShareCc[18]: Direct download link not found
> 34	28.08.2017 17:06:35	INFO	HOSTER Keep2ShareCc[18]: Checking for link errors...
> 35	28.08.2017 17:06:35	INFO	HOSTER Keep2ShareCc[18]: No errors found
> 36	28.08.2017 17:06:35	INFO	HOSTER Keep2ShareCc[18]: Processing as free download...
> 37	28.08.2017 17:06:37	INFO	CAPTCHA Keep2ShareCc[18]: Captcha | Using OCR to decrypt captcha...
> 38	28.08.2017 17:06:37	WARNING	CAPTCHA Keep2ShareCc[18]: Captcha | No OCR result
> 39	28.08.2017 17:06:37	INFO	ADDON Captcha9Kw: 115 credits left
> 40	28.08.2017 17:08:39	INFO	ADDON Captcha9Kw: Captcha result for ticket 89942673: dcqvneq
> 41	28.08.2017 17:08:40	INFO	CAPTCHA Keep2ShareCc[18]: Captcha | Captcha result: `dcqvneq`
> 42	28.08.2017 17:08:40	INFO	CAPTCHA Keep2ShareCc[18]: Captcha | Path deleted: /pyload/.pyload/tmp/captcha_image_Keep2ShareCc_99728.jpg
> 43	28.08.2017 17:08:40	INFO	CAPTCHA Keep2ShareCc[18]: Captcha | Correct captcha | dcqvneq
> 44	28.08.2017 17:08:40	INFO	HOSTER Keep2ShareCc[18]: Waiting 30 seconds...
> 45	28.08.2017 17:09:13	INFO	HOSTER Keep2ShareCc[18]: Downloading file... 

Anyway feel free to close as fixed as I assume there's no other way how to retrieve remaining wait time than issue captcha first.

**Comment by GammaC0de** [comment]
👍
