### ISSUE TITLE
Filer.net wrong package name 

### ISSUE THREAD

**Issue by djoliboli** [pyload/pyload#2943]
The package always get's namend like the filer.net Folder, and not like the Name i entered 

Let me Know if you need Some additional information 

27.08.2017 21:30:11 INFO Added package Guardian of Galaxy 2 containing 1 links 107 27.08.2017 21:30:12 INFO Decrypting starts: https://filer.net/folder/lbzgbooh26fuegoa 108 27.08.2017 21:30:12 WARNING CRYPTER FilerNetFolder[204]: Plugin may be unstable 109 27.08.2017 21:30:12 INFO ACCOUNT FilerNet: Grabbing account info for usermax*******... 110 27.08.2017 21:30:13 INFO CRYPTER FilerNetFolder[204]: Grabbing link info... 111 27.08.2017 21:30:14 INFO CRYPTER FilerNetFolder[204]: Link name: gdrtzuztkjdfsrzt 112 27.08.2017 21:30:14 INFO CRYPTER FilerNetFolder[204]: Link size: N/D 113 27.08.2017 21:30:14 INFO CRYPTER FilerNetFolder[204]: Link status: online 114 27.08.2017 21:30:14 INFO CRYPTER FilerNetFolder[204]: Processing url: https://filer.net/folder/lbzgbooh26fuegoa 115 27.08.2017 21:30:14 INFO CRYPTER FilerNetFolder[204]: Looking for direct link... 116 27.08.2017 21:30:15 INFO CRYPTER FilerNetFolder[204]: Direct link not found 117 27.08.2017 21:30:15 INFO CRYPTER FilerNetFolder[204]: Checking for link errors... 118 27.08.2017 21:30:15 INFO CRYPTER FilerNetFolder[204]: No errors found 119 27.08.2017 21:30:15 INFO CRYPTER FilerNetFolder[204]: Decrypting as premium link... 120 27.08.2017 21:30:15 INFO CRYPTER FilerNetFolder[204]: Create package: gdrtzuztkjdfsrzt | 40 links 121 27.08.2017 21:30:15 INFO Added package gdrtzuztkjdfsrzt containing 40 links 122 27.08.2017 21:30:15 INFO CRYPTER FilerNetFolder[204]: Save packagegdrtzuztkjdfsrztto folder: gdrtzuztkjdfsrzt

**Comment by GammaC0de** [comment]
Hi,

If you go to https://filer.net/folder/lbzgbooh26fuegoa, you will see that the folder name is `gdrtzuztkjdfsrzt` and that's why the package name is so..

**Comment by GammaC0de** [comment]
No response, closing.
