### ISSUE TITLE
Feature Request: Add Ironfiles file hoster

### ISSUE THREAD

**Issue by henne-** [pyload/pyload#2946]
Hey!

I'd be happy if someone would add ironfiles.net as hoster to pyload.
I think to develop this plugin you would need to have a premium account there, so i would be willing to offer one premium account for a month.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

Also please send some test URLs if you have.
