### ISSUE TITLE
Can't log into Pyload

### ISSUE THREAD

**Issue by IanJF** [pyload/pyload#2947]
Every month there seems to be a different issue with Pyload on QNAP its very annoying that QNAP keep changing things and then breaking functionality.

Now I can no longer log into Pyload, when I try it asks me to reset the users etc.
I have done that many times and it made no difference.

I saw another similar problem relating to Pyload on a Pi, but I was not able to get my issue sorted as my directories are all different etc.

Please see below a command I saw the other person run for the Payload setup. Hope this might save a bit of time. 

Regards,
Ian.

[~] # sudo find / -name files.db -type f -print
/share/CACHEDEV1_DATA/.qpkg/QPyload/CONFIG/files.db
/share/CACHEDEV1_DATA/homes/admin/.pyload/files.db
find: ‚Äò/proc/17788/task/27132‚Äô: No such file or directory

**Comment by GammaC0de** [comment]
Please try this package: https://www.qnapclub.eu/index.php?act=detail&qpkg_id=189
I have heard that it is working well.

**Comment by GammaC0de** [comment]
No response, closing.
