### ISSUE TITLE
DLC container content not being extracted or deleted after download is finished.

### ISSUE THREAD

**Issue by hbbernardo** [pyload/pyload#2948]
Hi pyload,

I have been downloading some DLC recently and have noticed that after the download is completed the multi-parted files residing in my download directory folder are not being merged/extracted into a new media file of folder. Nothing is happening. 

Is that a known issue?

**Comment by GammaC0de** [comment]
Is this a new installation?

**Comment by hbbernardo** [comment]
Yes. I have just installed the version 0.4.9 from git.

**Comment by GammaC0de** [comment]
Have you enabled `ExtractArchive` plugin?

Also, please provide DEBUG log

**Comment by hbbernardo** [comment]
[DLC.txt](https://github.com/pyload/pyload/files/1271888/DLC.txt)

Sorry for the delay. Here's the log you asked me to earlier. 

The files were already downloaded. I have just send the DLC again to pyload in order to reproduce what I mentioned.

Hope that helps.

**Comment by hbbernardo** [comment]
Sorry. Again. 

I forget to enable DEBUG mode on the log in the previous post.

here it is with debug mode enabled: : http://paste.ubuntu.com/25449203/

**Comment by GammaC0de** [comment]
OK, fixed.

**Comment by hbbernardo** [comment]
Sorry, for the delayed response. 

I can confirm that it is fixed. 

Extraction/Merging & deletion of the compressed files.

Thank you.
