### ISSUE TITLE
RG Premium account not working

### ISSUE THREAD

**Issue by tbfvrs** [pyload/pyload#2955]
Since couple of days Rapidgator premium links won't DL...
I would post some logs but when I click on the button it briefly shows the window with:

1 | 03.09.2017 06:54:41 | INFO | HOSTER BasePlugin[14233]: Waiting 1 minutes...
2 | 03.09.2017 06:54:59 | INFO | Download aborted: .....
3 | 03.09.2017 06:56:06 | INFO | ADDON UpdateManager: ***  New pyLoad

but in few seconds redirects to: http://ww1.pyload.org/

Very weird...

**Comment by GammaC0de** [comment]
@tbfvrs You have to replace the `<pyload directory>/module/plugins/hooks/UpdateManager.py` file  with this one: https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/78f10968869e887d802a75a9ef6b89628d0d5ff9/UpdateManager.py

And then restart pyload.

**Comment by tbfvrs** [comment]
Thank you v much;
BTW What about this constant: There is pyload update popup...?

**Comment by GammaC0de** [comment]
> BTW What about this constant: There is a pyload update popup...?

This is false and happens because you have not replaced UpdateManager.py

**Comment by tbfvrs** [comment]
Well I did replace yesterday and the popup wasnt gone but what is worse the RG prem started but today they aren't again...:(

**Comment by GammaC0de** [comment]
So to be clear, http:// links works but https:// links does not?

Can you try again with a new https:// link just to be sure?

**Comment by tbfvrs** [comment]
Yes;
Tried today and Im positive;
I've replaced the one in the installation folder not the one in root...

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

Also please send an example URL with the problem.

**Comment by GammaC0de** [comment]
Will close if no response...

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by tbfvrs** [comment]
Hi
Sorry I did not reply, was really busy lately;
Anyway sent you an email with all the details;

**Comment by GammaC0de** [comment]
Plugin updated, please test.

**Comment by StarScream159** [comment]
Working for me again. Premium downloads /w premium account. Thanks for adding https to the regex, I manually added that a while back. Nice to see it in the repo now.

**Comment by GammaC0de** [comment]
👍 Updated the plugin to use HTTPS for API calls too.

**Comment by GammaC0de** [comment]
@tbfvrs Can we close this?

**Comment by tbfvrs** [comment]
Please close, I have faith it does work, but had to check it tomorrow though, greetings

**Comment by GammaC0de** [comment]
👍  OK, closing then.
If the issue still persists let me know.
