### ISSUE TITLE
Turbobit Issue: TEXTAREA F1 not found

### ISSUE THREAD

**Issue by SergeGardien** [pyload/pyload#2956]
Hi all, I've just installed pyLoad and I'm trying to get it working with file hosters (novafile.com, turbobit.com, etc.) without much luck.

This is the log for a turbobit file:

_03.09.2017 17:01:38 INFO      Download restarted: rzhwkvx5ytk4.html | TEXTAREA F1 not found
03.09.2017 17:01:38 INFO      Download starts: rzhwkvx5ytk4.html
03.09.2017 17:01:38 WARNING   HOSTER XFileSharing[13]: TurbobitNet | Plugin may be unstable
03.09.2017 17:01:38 INFO      HOSTER XFileSharing[13]: TurbobitNet | Grabbing link info...
03.09.2017 17:01:39 INFO      HOSTER XFileSharing[13]: TurbobitNet | Link name: rzhwkvx5ytk4.html
03.09.2017 17:01:39 INFO      HOSTER XFileSharing[13]: TurbobitNet | Link size: N/D
03.09.2017 17:01:39 INFO      HOSTER XFileSharing[13]: TurbobitNet | Link status: starting
03.09.2017 17:01:39 INFO      HOSTER XFileSharing[13]: TurbobitNet | Processing url: http://turbobit.net/rzhwkvx5ytk4.html
03.09.2017 17:01:40 INFO      HOSTER XFileSharing[13]: TurbobitNet | Checking for link errors...
03.09.2017 17:01:40 INFO      HOSTER XFileSharing[13]: TurbobitNet | No errors found
03.09.2017 17:01:40 INFO      HOSTER XFileSharing[13]: TurbobitNet | Grabbing link info...
03.09.2017 17:01:40 INFO      HOSTER XFileSharing[13]: TurbobitNet | Link name: rzhwkvx5ytk4.html
03.09.2017 17:01:40 INFO      HOSTER XFileSharing[13]: TurbobitNet | Link size: N/D
03.09.2017 17:01:40 INFO      HOSTER XFileSharing[13]: TurbobitNet | Link status: starting
03.09.2017 17:01:40 INFO      HOSTER XFileSharing[13]: TurbobitNet | Processing as free download...
03.09.2017 17:01:40 INFO      HOSTER XFileSharing[13]: TurbobitNet | Checking for link errors...
03.09.2017 17:01:40 INFO      HOSTER XFileSharing[13]: TurbobitNet | No errors found
03.09.2017 17:01:40 WARNING   Download failed: rzhwkvx5ytk4.html | TEXTAREA F1 not found
03.09.2017 17:01:40 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: rzhwkvx5ytk4.html (pid:13)
03.09.2017 17:01:40 INFO      ADDON UnSkipOnFail: No duplicates found_

Any idea on how to solve it?

**Comment by GammaC0de** [comment]
Unfortunately, TurbobitNet support in pyLoad is broken (and it is not possible to fix because of it does not support JavaScript-less Recaptcha).
If you have issues with other file hosters please tell, otherwise will close this..

**Comment by SergeGardien** [comment]
Many thanks for the reply @GammaC0de :-)
I'll open a new issue-ticker in case I get errors from other file hosters.

**Comment by GammaC0de** [comment]
👍
