### ISSUE TITLE
Next theme not working with Jinja2.9.6

### ISSUE THREAD

**Issue by tibbors** [pyload/pyload#2957]
Hello,
I just tried to use the theme "Next" (according to [this](http://www.howto-blog.de/pyload-themes-installieren/) german blog).
When I restart pyLoad after inserting the name in to the pyload.conf the webinterface returns: 
`Critical error while processing request: `
`systemctl status pyload.service` returns: [Ghostbin](https://ghostbin.com/paste/pkp6j)

Somehow it can't find the theme although I put the folders in the template and media folder respectively.

Greetings,
Jonas

**Comment by GammaC0de** [comment]
Here is my working pyLoad setup with Next theme included and some bug fixes in the core as a bonus.

[pyLoad-Next.zip](https://github.com/pyload/pyload/files/1285113/pyLoad-Next.zip)

**Comment by tibbors** [comment]
Your version works for some reason. I will be using this version from now on.

Thank you

**Comment by GammaC0de** [comment]
👍
