### ISSUE TITLE
[WebUI] Changing the www addresses to leading to the project.

### ISSUE THREAD

**Issue by Rafik89** [pyload/pyload#2961]
Add to info:
Last tweets
Updating links
Is it possible to make these changes? #2953 
![screenshot 2017-09-09 16-30-33](https://user-images.githubusercontent.com/1193307/30241078-1252c4c6-957d-11e7-96bf-0db55e9a69f7.jpg)

**Comment by vuolter** [comment]
We do not make this kind of changes in the stable branch because can not be dispatched by the updatemanager. Stable branch is always frozen, only plugins can be updated.
