### ISSUE TITLE
FileHoster Plugin Issue: uploadgig.com

### ISSUE THREAD

**Issue by h1ghju1ce** [pyload/pyload#2963]
Hi,

I know its new and listed as "may be unstable" but I'm having an issue using this host, where if alot of files (or data) is added to the queue, it drops the downloads, and wont continue, even with a "restart package" 

The current workaround is to restart Pyload, then restart the package, which then works mostly fine (sometimes will then "trip over" again)

The error it gives in the LOGS is:
------------------------------------------------------------
WARNING   Download failed: anyfile.rar | Required premium account not found
------------------------------------------------------------

MaxParallelDownloads = 3
MaxConnections=2

Host has a limit of 50GB a day, this can happen even before 10GB of it is used

I have attached a fresh session log from a debug console output

[pyLoad Plugin 0.3 - Premium Account Fail Error.txt](https://github.com/pyload/pyload/files/1311334/pyLoad.Plugin.0.3.-.Premium.Account.Fail.Error.txt)

Hope this is enough information

(password for the account hasnt changed the plugin was 1st created BTW)

**Comment by GammaC0de** [comment]
So this is happens randomly?


Looking in the log I see many "error: [Errno 32] Broken pipe" errors which can imply connection issue or remote server issue

**Comment by h1ghju1ce** [comment]
The issue/error only occurs with UploadGIG and not with RapidGator, so I dont think its my connection, but could well be something the remote server does not like.

Re-reading the log, I noticed this line
--------------------------------------------------
Download failed: filename.ext | Downloaded content was smaller than expected. Try to reduce download connections.
--------------------------------------------------
The files with the "broken Pipe error actually download fine, so I think that might be a red herring.

I wonder if UpGig have very tight restrictions on simultaneous connections, I'll log a support ticket with them to get the official line on that

**Comment by GammaC0de** [comment]
OK, closing then.

If you have anything new, you can post again.

**Comment by h1ghju1ce** [comment]
I logged a call with the Hoster

https://uploadgig.com/ticket/show/7a52731b5c817ad0

I have tried using JDownloader on my Windows machine, and it doesn't have the "drop out" issue.

Also RapidGator and Uploaded.to don't have any drop out issues, so I think that eliminates, the hoster and my internet connection from being an issue as far as I can tell.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by h1ghju1ce** [comment]
sent

**Comment by GammaC0de** [comment]
Should be fixed now, please confirm.

**Comment by h1ghju1ce** [comment]
Awesome thanks, seems not to drop out now, and doesnt need a restart before adding to the queue like it used to, which is a huge improvement! , thanks again

**Comment by GammaC0de** [comment]
Good news, so all is OK.
Closing.
