### ISSUE TITLE
PIP Install error

### ISSUE THREAD

**Issue by stevezau** [pyload/pyload#2964]
Hi,

I don't think pypi has been setup correctly..

https://pypi.python.org/pypi/pyload.core is not found

```
Could not find a version that satisfies the requirement pyload.core[full] (from versions: )
```

**Comment by GammaC0de** [comment]
Are you really trying to install pyLoad or want to report an issue?

If you just want to install pyLoad, please read #2000.

pyLoad installation via pip is not ready yet.

**Comment by stevezau** [comment]
I'm raising it as an issue as if you read the README it suggests pip install https://github.com/pyload/pyload#pip-install

Perhaps that needs to be changed/updated?

**Comment by GammaC0de** [comment]
Pip installation is planed for the future version, currently its not functional.

@vuolter is responsible for the development of this version and the master (alpha version) tree. 

I am responsible to the stable tree.

**Comment by stevezau** [comment]
Oh, right. Stable branch. Understand now. thanks.
