### ISSUE TITLE
relink.to - filebot - folder name

### ISSUE THREAD

**Issue by hs1708** [pyload/pyload#2965]
Hi,
I don't know why this is happening, but smth broke the filebot hook. 

For instance assume this is the folder name: 
```relink.to_view.php?id=e439c283598070d9bdd4e04edebd53```
Then I get this error: 
```
Sep 22 18:05:15 NUC pyLoadCore[1687]: 22.09.2017 18:05:15 INFO      ADDON FileBot: executed
Sep 22 18:05:16 NUC pyLoadCore[1687]: "/media/mycloud/Media/Downloads/relink.to_view.php?id" is not a valid identifier
```

obviously the `=` seems to be the problem. A hot fix should be to remove them using the safepath method

**Comment by GammaC0de** [comment]
FileBot plugin is not part of pyLoad's distribution.
It is a plugin developed by third party.
I tried to download http://relink.to/f/view.php?id=e439c283598070d9bdd4e04edebd53 with pyLoad and it works fine.

I can try to help you but you need to provide DEBUG log and from where you have downloaded the FileBot plugin.

**Comment by GammaC0de** [comment]
No response, closing.
