### ISSUE TITLE
Can't fint folder to replace the UpdateManager.py

### ISSUE THREAD

**Issue by mooooonbaby** [pyload/pyload#2966]
Hi,

i've installed pyload 0.4.9 on Raspbian Jessie and want to replace the UpdateManager.py with a newer one (https://github.com/pyload/pyload/issues/2000#issuecomment-147120512). What is the "pyload directory"? The Install dir is /usr/bin, but there isn't a folder 'module'. In the home directory there is a folder '.pyload', but there also isn't a such folder. there is a folder 'userplugin' with a subfolder 'hooks'. But in that folder there is only one file, __init__.py. so were do i need to save the file in?

**Comment by GammaC0de** [comment]
So I guess you managed to find the correct location, right?

**Comment by mooooonbaby** [comment]
yes.
