### ISSUE TITLE
Update server & OpenShift

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#2967]
@vuolter @stickell Just got this email from OpenShift.

As far as I know, the update server runs on OpenShift and only @stickell has access to it.
So this is probably means that the update server will stop working unless @stickell will handle it..
Am I right??

From: Red Hat OpenShift Online <no-reply@openshift.com>
Valued OpenShift Online user,

This is a reminder that the sunset of the previous generation OpenShift Online 2 platform was announced on August 25, 2017. After September 30th, 2017, applications created in Free and Bronze accounts in Red Hat OpenShift Online 2 will be removed.

We invite you to join those who have already migrated their applications to our new OpenShift 3 based offerings, Red Hat OpenShift Online [Starter](https://blog.openshift.com/next-generation-red-hat-openshift-online/) and [Pro](https://blog.openshift.com/announce-pro-tier/). You can find step-by-step instructions in our [Migration Center](https://www.openshift.com/get-started/migrate.html) to help you easily migrate your OpenShift Online 2 platform applications to OpenShift 3.

If you are unable to migrate, please [backup your applications](https://developers.openshift.com/managing-your-applications/backing-up-applications.html) now, before they are removed. You can [sign-in here](https://openshift.redhat.com/app/login) to access your account. If you have any questions about migrating to the new OpenShift Online 3 platform, please reach out to us via our [Help Center](https://help.openshift.com)

**Comment by vuolter** [comment]
Hi @GammaC0de , thank you for this important notification, I'll try to contact @stickell , but we can open a new account in the case and easily switch to a new instance of the updatemanager, updating the current server location url in the plugin, just to avoid worries for the users.

**Comment by vuolter** [comment]
@stickell is checking the server.

**Comment by MaluNoPeleke** [comment]
Is that the reason for

```
290 | 03.10.2017 14:50:32 | DEBUG | ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com \| redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
292 | 03.10.2017 14:51:03 | WARNING | ADDON UpdateManager: Unable to connect to the server to retrieve updates
```

It doesn't matter if https://github.com/pyload/pyload/commit/792856a8081b8b27e08d789e11d35f5542ca9206 is installed or not.

**Comment by GammaC0de** [comment]
Server is down 😢

**Comment by GammaC0de** [comment]
Update Server suddenly works again.. (for how long, who knows?)

**Comment by GammaC0de** [comment]
Server is down, probably for good..

**Comment by GammaC0de** [comment]
@ vuolter Working on a solution.
unless you have a server-less (github only) solution..

@TuXbOy06 we need a stable hosting with PHP with sqlite extension, git client and approx  250 MB disk space..

**Comment by MaluNoPeleke** [comment]
Have you taken a look at uber.space already?

**Comment by GammaC0de** [comment]
@MaluNoPeleke No, what is that?
It is free (forgot to mention that)?

**Comment by MaluNoPeleke** [comment]
It costs at least 1€/month and offers a lot: https://uberspace.de

**Comment by TuXbOy06** [comment]
HEROKU seems to be a good solution though
Unfortunately I do not have any server to offer... :-(

**Comment by TuXbOy06** [comment]
@MaluNoPeleke seems like uberspace doesn't support git... But otherwise not it is not bad...

**Comment by MaluNoPeleke** [comment]
It does support it but the older documentation is only written in German: https://wiki.uberspace.de/development:git
They are working on English support

**Comment by TuXbOy06** [comment]
@vuolter could be a good backup solution then

**Comment by Velociraptor85** [comment]
so does the update server work now or not :?

**Comment by GammaC0de** [comment]
Soon.

**Comment by GammaC0de** [comment]
https://github.com/pyload/updatemanager/commit/3190d8c6c2a6684259de14f0ae7604f1a30234ad

**Comment by MaluNoPeleke** [comment]
Is it necessary to update the current/old updater of a stable Pyload to connect to the new service?

**Comment by GammaC0de** [comment]
It is not up yet because @vuolter has to do some more configuration.

You will have to manually update `UpdateManager.py` (already in `stable`).

**Comment by GammaC0de** [comment]
The server is now up and running:
- The data now resides in [pyload/updates](https://github.com/pyload/updates) repo:
Even if the server goes down in the future for some reason, `UpdateManager` will still be able to updated itself and move to another server if necessary.
- Automatic update of `blacklist.txt` upon deletion of a plugin from the `stable` repo, no chance to forget anymore! 😀 

Now, everyone should manually replace `UpdateManager.py` with https://github.com/pyload/pyload/blob/353c6692afdec4b6108555725cb5db46d02ed816/module/plugins/hooks/UpdateManager.py

Please spread the word and inform everyone you know that uses pyLoad, thanks!

**Comment by Flipez** [comment]
If you guys need someone who hosts your updates let me know, maybe we can work something out :)
