### ISSUE TITLE
Rapigator.Net not working

### ISSUE THREAD

**Issue by ID3000** [pyload/pyload#2969]
Hello,

I made a new pyload install using the stable branch.
My rapidgatoprNet Plugin seems not to work.
I get issues listed below.
I could download 1 file there successfully, but after it always this error.
Restarted pyload, restarted the machine pyload is running on (win server 2012 R2), but didn't work.

Made small research yesterday here, but didn't find solution.

These are the lines from the log (debug mode switched on before this try, but didn't restart pyload after turning it on).

Thank you in advance for your help.

`
27.09.2017 22:13:40 | WARNING | HOSTER RapidgatorNet[26]: Plugin may be unstable
-- | -- | --
862 | 27.09.2017 22:13:40 | INFO | HOSTER RapidgatorNet[26]: Grabbing link info...
863 | 27.09.2017 22:13:41 | INFO | HOSTER RapidgatorNet[26]: Link name: xxx.rar
864 | 27.09.2017 22:13:41 | INFO | HOSTER RapidgatorNet[26]: Link size: 1001.00 MiB (1049624576 bytes)
865 | 27.09.2017 22:13:41 | INFO | HOSTER RapidgatorNet[26]: Link status: online
866 | 27.09.2017 22:13:41 | INFO | HOSTER RapidgatorNet[26]: Processing url: xxx.rar.html
867 | 27.09.2017 22:13:41 | INFO | HOSTER RapidgatorNet[26]: Looking for direct download link...
868 | 27.09.2017 22:13:41 | INFO | HOSTER RapidgatorNet[26]: Direct download link not found
869 | 27.09.2017 22:13:41 | INFO | HOSTER RapidgatorNet[26]: Checking for link errors...
870 | 27.09.2017 22:13:41 | INFO | HOSTER RapidgatorNet[26]: No errors found
871 | 27.09.2017 22:13:41 | INFO | HOSTER RapidgatorNet[26]: Processing as free download...
872 | 27.09.2017 22:13:41 | INFO | HOSTER RapidgatorNet[26]: Waiting 31 seconds...
873 | 27.09.2017 22:14:14 | WARNING | CAPTCHA RapidgatorNet[26]: ReCaptcha \| Key pattern not found
874 | 27.09.2017 22:14:14 | WARNING | Download failed: xxx.rar \| Parse error: Captcha pattern not found \| Plugin may be out of date
875 | 27.09.2017 22:14:14 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: xxx.rar (pid:37)
876 | 27.09.2017 22:14:14 | INFO | ADDON UnSkipOnFail: No duplicates found

`

**Comment by GammaC0de** [comment]
URL?

**Comment by ID3000** [comment]
Processing url: http://rapidgator.net/file/bc96b6c75e6987ca941bd14e51b3b6b7/wowo20gedtdl10blx2_kg5eua8skwvi.part02.rar.html

**Comment by GammaC0de** [comment]
Works fine here.

How exactly did you install pyload?

**Comment by ID3000** [comment]
I copied the stable branch from git as zip, (monday this week), extracted that into a folder.
Installed dependencies using pip (was little complicated to find packages recognized by pyload for windows).
Strarted pyload with -s argument to re-setup pyload after all dependencies were installed (well tesseract still not recognized though).
Right after install, it worked one time.
Then always the issue above for several links, even if I restart pyload or the machine.

**Comment by GammaC0de** [comment]
Start pyload with `python pyLoadCore.py -d`, retry the download and post the log here.

**Comment by ID3000** [comment]
Did it, this is the log:

`

27.09.2017 22:50:07 | INFO | Download starts: http://rapidgator.net/file/93abb86071e7a731d89a89f3315483f2/wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar.html
-- | -- | --
108 | 27.09.2017 22:50:07 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing

136 | 27.09.2017 22:50:40 | DEBUG | HOSTER RapidgatorNet[34]: LOAD URL http://rapidgator.net/download/AjaxGetDownloadLink?sid=2bz44hvhU8cuEKizdi25U1ByiPgMMThG \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=http://rapidgator.net/file/93abb86071e7a731d89a89f3315483f2/wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar.html \| just_header=False
-- | -- | -- | --
137 | 27.09.2017 22:50:40 | DEBUG | HOSTER RapidgatorNet[34]: http://rapidgator.net/download/AjaxGetDownloadLink?sid=2bz44hvhU8cuEKizdi25U1ByiPgMMThG \| {"state":"done"}
138 | 27.09.2017 22:50:40 | DEBUG | HOSTER RapidgatorNet[34]: LOAD URL http://rapidgator.net/download/captcha \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=http://rapidgator.net/file/93abb86071e7a731d89a89f3315483f2/wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar.html \| just_header=False
139 | 27.09.2017 22:50:41 | DEBUG | CAPTCHA RapidgatorNet[34]: AdsCaptcha \| Key or id pattern not found
140 | 27.09.2017 22:50:41 | WARNING | CAPTCHA RapidgatorNet[34]: ReCaptcha \| Key pattern not found
141 | 27.09.2017 22:50:41 | DEBUG | CAPTCHA RapidgatorNet[34]: SolveMedia \| Key pattern not found
142 | 27.09.2017 22:50:41 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
143 | 27.09.2017 22:50:41 | WARNING | Download failed: wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar \| Parse error: Captcha pattern not found \| Plugin may be out of date
144 | 27.09.2017 22:50:41 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
145 | 27.09.2017 22:50:41 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar (pid:37)
146 | 27.09.2017 22:50:41 | INFO | ADDON UnSkipOnFail: No duplicates found

`
109 | 27.09.2017 22:50:07 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
110 | 27.09.2017 22:50:07 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
111 | 27.09.2017 22:50:07 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
112 | 27.09.2017 22:50:07 | DEBUG | HOSTER RapidgatorNet[34]: Plugin version: 0.48
113 | 27.09.2017 22:50:07 | DEBUG | HOSTER RapidgatorNet[34]: Plugin status: testing
114 | 27.09.2017 22:50:07 | WARNING | HOSTER RapidgatorNet[34]: Plugin may be unstable
115 | 27.09.2017 22:50:07 | INFO | HOSTER RapidgatorNet[34]: Grabbing link info...
116 | 27.09.2017 22:50:07 | DEBUG | HOSTER RapidgatorNet[34]: Link info: {'status': 2, 'hash': {u'MD5': u'3e8fe22193157cbade121026ae524650'}, 'name': u'wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar', 'url': u'http://rapidgator.net/file/93abb86071e7a731d89a89f3315483f2/wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar.html', 'pattern': {'H': u'MD5', 'S': u'1001', 'U': u'MB', 'D': u'3e8fe22193157cbade121026ae524650', 'N': u'wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar'}, 'size': 1049624576}
117 | 27.09.2017 22:50:07 | DEBUG | HOSTER RapidgatorNet[34]: Previous link info: {}
118 | 27.09.2017 22:50:07 | INFO | HOSTER RapidgatorNet[34]: Link name: wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar
119 | 27.09.2017 22:50:07 | INFO | HOSTER RapidgatorNet[34]: Link size: 1001.00 MiB (1049624576 bytes)
120 | 27.09.2017 22:50:07 | INFO | HOSTER RapidgatorNet[34]: Link status: online
121 | 27.09.2017 22:50:07 | INFO | HOSTER RapidgatorNet[34]: Processing url: http://rapidgator.net/file/93abb86071e7a731d89a89f3315483f2/wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar.html
122 | 27.09.2017 22:50:07 | INFO | HOSTER RapidgatorNet[34]: Looking for direct download link...
123 | 27.09.2017 22:50:07 | DEBUG | HOSTER RapidgatorNet[34]: LOAD URL http://rapidgator.net/file/93abb86071e7a731d89a89f3315483f2/wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar.html \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
124 | 27.09.2017 22:50:08 | DEBUG | HOSTER RapidgatorNet[34]: Redirect #1 to: https://rapidgator.net/file/93abb86071e7a731d89a89f3315483f2/wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar.html
125 | 27.09.2017 22:50:08 | DEBUG | HOSTER RapidgatorNet[34]: LOAD URL https://rapidgator.net/file/93abb86071e7a731d89a89f3315483f2/wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar.html \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
126 | 27.09.2017 22:50:08 | INFO | HOSTER RapidgatorNet[34]: Direct download link not found
127 | 27.09.2017 22:50:08 | DEBUG | HOSTER RapidgatorNet[34]: LOAD URL http://rapidgator.net/file/93abb86071e7a731d89a89f3315483f2/wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar.html \| redirect=True \| cookies=[('rapidgator.net', 'lang', 'en')] \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
128 | 27.09.2017 22:50:08 | INFO | HOSTER RapidgatorNet[34]: Checking for link errors...
129 | 27.09.2017 22:50:08 | INFO | HOSTER RapidgatorNet[34]: No errors found
130 | 27.09.2017 22:50:08 | INFO | HOSTER RapidgatorNet[34]: Processing as free download...
131 | 27.09.2017 22:50:08 | DEBUG | HOSTER RapidgatorNet[34]: {u'getDownloadUrl': u'/download/AjaxGetDownloadLink', u'secs': u'30', u'captchaUrl': u'/download/captcha', u'fid': u'364647856', u'startTimerUrl': u'/download/AjaxStartTimer'}
132 | 27.09.2017 22:50:08 | DEBUG | HOSTER RapidgatorNet[34]: LOAD URL http://rapidgator.net/download/AjaxStartTimer?fid=364647856 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=http://rapidgator.net/file/93abb86071e7a731d89a89f3315483f2/wowo20gedtdl10blx2_kg5eua8skwvi.part06.rar.html \| just_header=False
133 | 27.09.2017 22:50:08 | DEBUG | HOSTER RapidgatorNet[34]: http://rapidgator.net/download/AjaxStartTimer?fid=364647856 \| {"state":"started","sid":"2bz44hvhU8cuEKizdi25U1ByiPgMMThG"}
134 | 27.09.2017 22:50:08 | DEBUG | HOSTER RapidgatorNet[34]: WAIT set to timestamp 1506545439.543000 \| Previous waitUntil: 0.000000
135 | 27.09.2017 22:50:08 | INFO | HOSTER RapidgatorNet[34]: Waiting 31 seconds...

`

**Comment by GammaC0de** [comment]
Please surround the log text with tripple \` so the text will not get corrupted, e.g.:
 \`\`\`
line1
line2
 \`\`\`

Will result:
```
line1
line2
```

**Comment by ID3000** [comment]
sorry, didn't know that, edited.

**Comment by GammaC0de** [comment]
Edit module\plugins\hoster\RapidgatorNet.py  and change line 149 from:
```
            if not captcha:
                self.error(_("Captcha pattern not found"))
```
to:
```
            if not captcha:
                self.dump_html()
                self.error(_("Captcha pattern not found"))
```

Use spaces only, not tabs!

Now restart pyload (`python pyLoadCore.py -d`) and retry the download.
After the download will fail, there would be an HTML file inside `<pyload_work_directory>\tmp\RapidgatorNet\`, post the file here.

**Comment by StarScream159** [comment]
I'm having a problem with Rapidgator.net too. Started mid-day today:

```
27.09.2017 22:38:10 INFO      HOSTER RapidgatorNet[1586]: Processing url: <URLHERE>
27.09.2017 22:38:10 INFO      HOSTER RapidgatorNet[1586]: Looking for direct download link...
27.09.2017 22:38:11 INFO      HOSTER RapidgatorNet[1586]: Direct download link not found
27.09.2017 22:38:11 INFO      HOSTER RapidgatorNet[1586]: Checking for link errors...
27.09.2017 22:38:11 INFO      HOSTER RapidgatorNet[1586]: No errors found
27.09.2017 22:38:11 INFO      HOSTER RapidgatorNet[1586]: Processing as premium download...
27.09.2017 22:38:12 ERROR     HOSTER RapidgatorNet[1586]: API: info | Bad server response: 401 Unauthorized | SID: ugtnguc56b5su9i0lpvi8qnh92
```

However, while writing out this post I was able to successfully download something. I believe maybe there was a temporary problem with Rapidgator that was just solved.

**Comment by ID3000** [comment]
Her are the html files, there have been created two files, both at the same time.



[html files.zip](https://github.com/pyload/pyload/files/1339507/html.files.zip)

**Comment by GammaC0de** [comment]
@StarScream159 Plugin updated, should be fixed now.

@ID3000 Is this a premium download?

**Comment by ID3000** [comment]
Thank you so much, working now!!!
No this is not premium.

You have an amazing support !!!
Guess we can close it?

**Comment by GammaC0de** [comment]
👍 Closing.

**Comment by alex9434** [comment]
I have the following error for RapidgatorNet:
Parse error: Captcha pattern not found | Plugin may be out of date
Can you please re-open the ticket?

**Comment by StarScream159** [comment]
You're going to need to post more information then that. Can you post the log? Have you updated the plugin to the latest version? Do you have a valid account that you've double checked still has premium access? What OS are you on? Have you tried restarting the pyLoad service?

**Comment by GammaC0de** [comment]
@alex9434 Please open a new issue, there is no point in reviving a closed issue..
