### ISSUE TITLE
Logging in users with umlauts doesn't work

### ISSUE THREAD

**Issue by lavalampa** [pyload/pyload#2970]
Hello, 
when i'm try to logging a users with an uploaded account, that have umlauts (ü) an expection is called, and the log is replacing the "ü" with an "u"

28.09.2017 16:49:40 INFO      ACCOUNT UploadedTo: Login user `****uh***`...

> traceback (most recent call last):
>   File "/home/pyload/module/lib/bottle.py", line 733, in _handle
>     return route.call(**args)
>   File "/home/pyload/module/lib/bottle.py", line 1448, in wrapper
>     rv = callback(*a, **ka)
>   File "/home/pyload/module/web/utils.py", line 113, in _view
>     return func(*args, **kwargs)
>   File "/home/pyload/module/web/json_app.py", line 276, in add_account
>     PYLOAD.updateAccount(type, login, password)
>   File "/home/pyload/module/Api.py", line 894, in updateAccount
>     self.core.accountManager.updateAccount(plugin, account, password, options)
>   File "/home/pyload/module/utils.py", line 165, in new
>     return func(*args)
>   File "/home/pyload/module/plugins/AccountManager.py", line 149, in updateAccount
>     updated = p.updateAccounts(user, password, options)
>   File "/home/pyload/.pyload/userplugins/internal/misc.py", line 231, in new
>     return fn(*args, **kwargs)
>   File "/home/pyload/module/plugins/internal/Account.py", line 337, in updateAccounts
>     self.add(user, password, options)
>   File "/home/pyload/.pyload/userplugins/internal/misc.py", line 231, in new
>     return fn(*args, **kwargs)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
> An error occured while processing the request.
> Traceback (most recent call last):
>   File "/home/pyload/module/lib/bottle.py", line 733, in _handle
>     return route.call(**args)
>   File "/home/pyload/module/lib/bottle.py", line 1448, in wrapper
>     rv = callback(*a, **ka)
>   File "/home/pyload/module/web/utils.py", line 113, in _view
>     return func(*args, **kwargs)
>   File "/home/pyload/module/web/json_app.py", line 276, in add_account
>     PYLOAD.updateAccount(type, login, password)
>   File "/home/pyload/module/Api.py", line 894, in updateAccount
>     self.core.accountManager.updateAccount(plugin, account, password, options)
>   File "/home/pyload/module/utils.py", line 165, in new
>     return func(*args)
>   File "/home/pyload/module/plugins/AccountManager.py", line 149, in updateAccount
>     updated = p.updateAccounts(user, password, options)
>   File "/home/pyload/.pyload/userplugins/internal/misc.py", line 231, in new
>     return fn(*args, **kwargs)
>   File "/home/pyload/module/plugins/internal/Account.py", line 337, in updateAccounts
>     self.add(user, password, options)
>   File "/home/pyload/.pyload/userplugins/internal/misc.py", line 231, in new
>     return fn(*args, **kwargs)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

I'm using version 0.4.9

e: Also happens with the stable branch from github

**Comment by GammaC0de** [comment]
This is a known bug that makes countless issues all over pyload.

I cant try to fix this for you but I will need account information for testing.
Please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Will close if no response.

**Comment by GammaC0de** [comment]
No response, closing.
