### ISSUE TITLE
FshareVN get folder in folder

### ISSUE THREAD

**Issue by bigdargon** [pyload/pyload#2971]
I have a link that contains the directory in the directory, when add to pyload the error. 
`Decrypting failed: YWDW6R551DJA | Parse error: Free decrypted link not found | Plugin may be out of date`
Can you fix it?
This link: https://www.fshare.vn/folder/YWDW6R551DJA

**Comment by GammaC0de** [comment]
Done, you will have to enable "Download subfolders" in the plugin configuration.
