### ISSUE TITLE
Zippyshare Download failed: | No JS Engine 

### ISSUE THREAD

**Issue by Lalarian** [pyload/pyload#2972]
Hello!

I cannot download from Zippyshare. I just get No JS Engine.
First I had duktape installed and working (including PATH). I also tried switching to OSSP js, but this won't be accepted either.

```
root@router:~# which js
/opt/bin/js

```

```
root@router:~# cat /etc/profile 
export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/jffs/sbin:/jffs/bin:/jffs/usr/sbin:/jffs/usr/bin:/mmc/sbin:/mmc/bin:/mmc/usr/sbin:/mmc/usr/bin:/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin
export LD_LIBRARY_PATH=/lib:/usr/lib:/jffs/lib:/jffs/usr/lib:/jffs/usr/local/lib:/mmc/lib:/mmc/usr/lib:/opt/lib:/opt/usr/lib
export PS1='\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
export TZ=`cat /etc/TZ`

alias ll='ls -lahrt'

reboot() {
  for f in /opt/etc/init.d/K* ; do
    [ -x "$f" ] && "$f" stop
  done
  echo "#!/bin/sh" > /tmp/.rc_shutdown
  echo "$(nvram get rc_shutdown)" >> /tmp/.rc_shutdown
  if [ -f /tmp/.rc_shutdown ]; then
    chmod +x /tmp/.rc_shutdown
    /tmp/.rc_shutdown
  fi
  /sbin/reboot
  }

```

```
root@router:~# js
((o) Duktape 2.1.1 (v2.1.1)
duk> ^C

```

**Comment by GammaC0de** [comment]
Edit your pyload init script and add /opt/bin/ to the PATH.

**Comment by Lalarian** [comment]
This is my init script:
`
#!/bin/sh

prefix="/opt"
PATH=${prefix}/bin:${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin

start() {
        echo "starting pyLoad"
        pyload --daemon --configdir=/opt/var/pyload
        }

stop() {
        echo "stopping pyLoad"
        pyload --quit --configdir=/opt/var/pyload
        }

status() {
        pyload --status --configdir=/opt/var/pyload
        }

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 4
                start
                ;;
        status) status
                ;;
        *)
                echo "Usage: $0 (start|stop|restart|status)"
                exit 1
                ;;
esac

exit 0

`

So this should be allright.

**Comment by GammaC0de** [comment]
I think you should use:
export PATH=${prefix}/bin:${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin

**Comment by Lalarian** [comment]
Hi, Gamma!
Thank you for your always quick support :)
I think I found the problem: It's caused by entware-ng.
While the js commands are working, and the 23+19 test from JsEngine.py gives me the correct result of '42', all js interpreters I tried (node, js and duktape) also return with an error code. (segmentation fault).

I alreadz have --force-reinstall(ed) all packages, but this didn't help. Also it's strange, that there's no other problem besides all three js interpreters.

**Comment by GammaC0de** [comment]
OK, so this is probably a result of bad package build.

You can try to open an issue at https://github.com/Entware-ng/Entware-ng/issues or maybe switch to Optware-ng.

Should we close this issue?

**Comment by Lalarian** [comment]
Yes, it's ok to close. In between I have been killing my whole router setup while trying to this this, so it will need a while to make it functional again, I will swich to optware-ng and hope it's allright then :)

**Comment by Lalarian** [comment]
Just fyi:
I now have switched to optware-ng and it's working like a breeze.

**Comment by GammaC0de** [comment]
Great. 👍
