### ISSUE TITLE
How to start pyload 0.6.8

### ISSUE THREAD

**Issue by DimeOne** [pyload/pyload#2975]
Hi,

I have been trying to get a newer version than 0.4.9 running. 

For testing purposes I downloaded the 0.6.8 release into a docker python:3 container, installed the dependencies and finally ran: ```pip install pyload.utils2[full]``` which completed successfuly.

But there is no pyload.py or pyload on my system to start it. Since the documentation is fairly old and contradicting each other, I hope this request isn't that bad here.

How is pyload 0.6.8 started?

**Comment by vuolter** [comment]
v0.6.8 is broken (I recommend to just check https://github.com/pyload/pyload/releases, not https://github.com/pyload/pyload/tags - at least for now...). Anyway the latest master is working, but if you can wait a week you should be able to try the new webui too. ;)

**Comment by DimeOne** [comment]
Thanks for the fast reply, I'm not sure I understand the hint with releases vs tags, as it is showing me the same versions with the same commits.

**Comment by vuolter** [comment]
You right, my hint is completely wrong. XD
I should have to say that many latest tags are of not fully working versions (you can read more about that on the gitter chat of today).

**Comment by GammaC0de** [comment]
@DimeOne If you just want to use stable pyLoad, v0.4.9 is what you are looking for and you can read #2000  for instructions.
Otherwise, as @vuolter said, v0.5/v0.6 is not ready for use yet.

**Comment by GammaC0de** [comment]
Closing.
