### ISSUE TITLE
rockfile.eu #2

### ISSUE THREAD

**Issue by poste5** [pyload/pyload#2981]
Hi, I have:
-Disabled `XFileSharing`
-Enabled `CloudFlareDdos`

I try to download from rockfile.eu:
http://rockfile.eu/ryq2o19mx56q.html
http://rockfile.eu/329d9g5sqkqn.html
http://rockfile.eu/0onrcsnsl02s.html

I have this log (I tried both with XFileSharing activated and deactivated:

240 | 11.10.2017 19:14:04 | INFO | Starting pyLoad 0.4.9
241 | 11.10.2017 19:14:04 | INFO | Using home directory: /home29/poiu0/.pyload
242 | 11.10.2017 19:14:04 | INFO | Activated plugins: ClickNLoad, CloudFlareDdos, EventMapper,  ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail,  UpdateManager, UserAgentSwitcher
243 | 11.10.2017 19:14:04 | INFO | Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus,  BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha,  DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC,  ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker,  MultiHome, PushBullet, PushOver, RestartFailed, SkipRev,  TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
244 | 11.10.2017 19:14:04 | INFO | Downloadtime: True
245 | 11.10.2017 19:14:05 | INFO | Starting builtin webserver: 185.147.13.233:22126
246 | 11.10.2017 19:14:05 | INFO | Free space: 5.13 TiB
247 | 11.10.2017 19:14:05 | INFO | Activating Accounts...
248 | 11.10.2017 19:14:05 | INFO | Activating Plugins...
249 | 11.10.2017 19:14:05 | INFO | pyLoad is up and running
250 | 11.10.2017 19:14:11 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
251 | 11.10.2017 19:14:11 | ERROR | ADDON ClickNLoad: [Errno 98] Address already in use
252 | 11.10.2017 19:15:21 | CRITICAL | 'NoneType' object has no attribute 'group'
253 | 11.10.2017 19:15:23 | CRITICAL | 'NoneType' object has no attribute 'group'
254 | 11.10.2017 19:15:25 | CRITICAL | 'NoneType' object has no attribute 'group'
255 | 11.10.2017 19:17:07 | INFO | ADDON XFileSharing: Auto-discover new hosters
256 | 11.10.2017 19:17:07 | INFO | ADDON XFileSharing: Auto-discover new crypters
257 | 11.10.2017 19:17:29 | INFO | Download starts: ryq2o19mx56q.html
258 | 11.10.2017 19:17:29 | WARNING | HOSTER XFileSharing[10]: RockfileEu \| Plugin may be unstable
259 | 11.10.2017 19:17:29 | INFO | HOSTER XFileSharing[10]: RockfileEu \| Grabbing link info...
260 | 11.10.2017 19:17:29 | INFO | ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page
261 | 11.10.2017 19:17:29 | INFO | HOSTER XFileSharing[10]: RockfileEu \| Waiting 5 seconds...
262 | 11.10.2017 19:17:31 | INFO | Download starts: 329d9g5sqkqn.html
263 | 11.10.2017 19:17:31 | WARNING | HOSTER XFileSharing[11]: RockfileEu \| Plugin may be unstable
264 | 11.10.2017 19:17:31 | INFO | HOSTER XFileSharing[11]: RockfileEu \| Grabbing link info...
265 | 11.10.2017 19:17:31 | INFO | ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page
266 | 11.10.2017 19:17:31 | INFO | HOSTER XFileSharing[11]: RockfileEu \| Waiting 5 seconds...
267 | 11.10.2017 19:17:33 | INFO | Download starts: 0onrcsnsl02s.html
268 | 11.10.2017 19:17:33 | WARNING | HOSTER XFileSharing[12]: RockfileEu \| Plugin may be unstable
269 | 11.10.2017 19:17:33 | INFO | HOSTER XFileSharing[12]: RockfileEu \| Grabbing link info...
270 | 11.10.2017 19:17:33 | INFO | ADDON CloudFlareDdos: Detected CloudFlare's DDoS protection page
271 | 11.10.2017 19:17:33 | INFO | HOSTER XFileSharing[12]: RockfileEu \| Waiting 5 seconds...
272 | 11.10.2017 19:17:35 | INFO | HOSTER XFileSharing[10]: RockfileEu \| Link name: >
273 | 11.10.2017 19:17:35 | INFO | HOSTER XFileSharing[10]: RockfileEu \| Link size: N/D
274 | 11.10.2017 19:17:35 | INFO | HOSTER XFileSharing[10]: RockfileEu \| Link status: online
275 | 11.10.2017 19:17:35 | INFO | HOSTER XFileSharing[10]: RockfileEu \| Processing url: http://rockfile.eu/ryq2o19mx56q.html
276 | 11.10.2017 19:17:36 | INFO | HOSTER XFileSharing[10]: RockfileEu \| Checking for link errors...
277 | 11.10.2017 19:17:36 | INFO | HOSTER XFileSharing[10]: RockfileEu \| No errors found
278 | 11.10.2017 19:17:36 | INFO | HOSTER XFileSharing[10]: RockfileEu \| Processing as free download...
279 | 11.10.2017 19:17:36 | INFO | HOSTER XFileSharing[10]: RockfileEu \| Checking for link errors...
280 | 11.10.2017 19:17:36 | INFO | HOSTER XFileSharing[10]: RockfileEu \| No errors found
281 | 11.10.2017 19:17:36 | WARNING | CAPTCHA XFileSharing[10]: RockfileEu \| ReCaptcha \| Key pattern not found
282 | 11.10.2017 19:17:36 | INFO | HOSTER XFileSharing[10]: RockfileEu \| Checking for link errors...
283 | 11.10.2017 19:17:36 | INFO | HOSTER XFileSharing[10]: RockfileEu \| No errors found
284 | 11.10.2017 19:17:36 | INFO | CAPTCHA XFileSharing[10]: RockfileEu \| ReCaptcha \| Using OCR to decrypt captcha...
285 | 11.10.2017 19:17:36 | WARNING | CAPTCHA XFileSharing[10]: RockfileEu \| ReCaptcha \| No OCR result
286 | 11.10.2017 19:17:37 | INFO | HOSTER XFileSharing[11]: RockfileEu \| Link name: >
287 | 11.10.2017 19:17:37 | INFO | HOSTER XFileSharing[11]: RockfileEu \| Link size: N/D
288 | 11.10.2017 19:17:37 | INFO | HOSTER XFileSharing[11]: RockfileEu \| Link status: online
289 | 11.10.2017 19:17:37 | INFO | HOSTER XFileSharing[11]: RockfileEu \| Processing url: http://rockfile.eu/329d9g5sqkqn.html
290 | 11.10.2017 19:17:38 | INFO | HOSTER XFileSharing[11]: RockfileEu \| Checking for link errors...
291 | 11.10.2017 19:17:38 | INFO | HOSTER XFileSharing[11]: RockfileEu \| No errors found
292 | 11.10.2017 19:17:38 | INFO | HOSTER XFileSharing[11]: RockfileEu \| Processing as free download...
293 | 11.10.2017 19:17:38 | INFO | HOSTER XFileSharing[11]: RockfileEu \| Checking for link errors...
294 | 11.10.2017 19:17:38 | INFO | HOSTER XFileSharing[11]: RockfileEu \| No errors found
295 | 11.10.2017 19:17:38 | WARNING | CAPTCHA XFileSharing[11]: RockfileEu \| ReCaptcha \| Key pattern not found
296 | 11.10.2017 19:17:38 | INFO | HOSTER XFileSharing[11]: RockfileEu \| Checking for link errors...
297 | 11.10.2017 19:17:38 | INFO | HOSTER XFileSharing[11]: RockfileEu \| No errors found
298 | 11.10.2017 19:17:38 | INFO | CAPTCHA XFileSharing[11]: RockfileEu \| ReCaptcha \| Using OCR to decrypt captcha...
299 | 11.10.2017 19:17:38 | WARNING | CAPTCHA XFileSharing[11]: RockfileEu \| ReCaptcha \| No OCR result
300 | 11.10.2017 19:17:39 | INFO | HOSTER XFileSharing[12]: RockfileEu \| Link name: >
301 | 11.10.2017 19:17:39 | INFO | HOSTER XFileSharing[12]: RockfileEu \| Link size: N/D
302 | 11.10.2017 19:17:39 | INFO | HOSTER XFileSharing[12]: RockfileEu \| Link status: online
303 | 11.10.2017 19:17:39 | INFO | HOSTER XFileSharing[12]: RockfileEu \| Processing url: http://rockfile.eu/0onrcsnsl02s.html
304 | 11.10.2017 19:17:40 | INFO | HOSTER XFileSharing[12]: RockfileEu \| Checking for link errors...
305 | 11.10.2017 19:17:40 | INFO | HOSTER XFileSharing[12]: RockfileEu \| No errors found
306 | 11.10.2017 19:17:40 | INFO | HOSTER XFileSharing[12]: RockfileEu \| Processing as free download...
307 | 11.10.2017 19:17:40 | INFO | HOSTER XFileSharing[12]: RockfileEu \| Checking for link errors...
308 | 11.10.2017 19:17:40 | INFO | HOSTER XFileSharing[12]: RockfileEu \| No errors found
309 | 11.10.2017 19:17:40 | WARNING | CAPTCHA XFileSharing[12]: RockfileEu \| ReCaptcha \| Key pattern not found
310 | 11.10.2017 19:17:40 | INFO | HOSTER XFileSharing[12]: RockfileEu \| Checking for link errors...
311 | 11.10.2017 19:17:40 | INFO | HOSTER XFileSharing[12]: RockfileEu \| No errors found
312 | 11.10.2017 19:17:40 | INFO | CAPTCHA XFileSharing[12]: RockfileEu \| ReCaptcha \| Using OCR to decrypt captcha...
313 | 11.10.2017 19:17:40 | WARNING | CAPTCHA XFileSharing[12]: RockfileEu \| ReCaptcha \| No OCR result
314 | 11.10.2017 19:18:11 | ERROR | ADDON ClickNLoad: [Errno 98] Address already in use
315 | 11.10.2017 19:19:24 | INFO | Download aborted: http://rockfile.eu/ryq2o19mx56q.html
316 | 11.10.2017 19:19:25 | INFO | Download aborted: http://rockfile.eu/329d9g5sqkqn.html
317 | 11.10.2017 19:19:26 | INFO | Download aborted: http://rockfile.eu/0onrcsnsl02s.html
318 | 11.10.2017 19:19:26 | CRITICAL | 'NoneType' object has no attribute 'group'
319 | 11.10.2017 19:19:28 | CRITICAL | 'NoneType' object has no attribute 'group'
320 | 11.10.2017 19:19:30 | CRITICAL | 'NoneType' object has no attribute 'group'
321 | 11.10.2017 19:22:11 | ERROR | ADDON ClickNLoad: [Errno 98] Address already in use

Could you check please? Thank you

**Comment by GammaC0de** [comment]
According to the log, XFileSharing is still active (you should remove the package and create a new one).

**Comment by poste5** [comment]
Thank you very much. Now it works.

10/10

**Comment by GammaC0de** [comment]
👍
