### ISSUE TITLE
tried to install on debian stretch with pip

### ISSUE THREAD

**Issue by Doccos** [pyload/pyload#2985]
i tried to install width pip  but it says "failed building wheel for python-dbus"

python2.7
debian9 stretch

pastbin:[https://pastebin.com/tBicmezM](https://pastebin.com/tBicmezM)

**Comment by GammaC0de** [comment]
@Doccos pip installation is not ready yet, just clone the stable git source.

**Comment by Doccos** [comment]
okey thanks

**Comment by GammaC0de** [comment]
👍
