### ISSUE TITLE
specific network use

### ISSUE THREAD

**Issue by arshiay** [pyload/pyload#2986]
hi
i have 2 wireless network both with internet
i want to pyload use wireless1 for download and not use wireless2
wireless2 use for other stuff only
can i do that?

**Comment by GammaC0de** [comment]
Yes, go to pyLoad's configuration -> download -> Download interface to bind (ip or Name)
Then enter the name or IP of the interface  you would line to use for downloading.

**Comment by arshiay** [comment]
hi
thanks for replay
i do what you said but after set "ip" or "name of wlan0" it does not start download at all what should i do?

**Comment by GammaC0de** [comment]
Please enable debug mode, try to download and post the log here.

**Comment by arshiay** [comment]
22.10.2017 22:33:34 | WARNING | Couldn't connect to host or connection reset, waiting 1 minute and retry.
-- | -- | --
198 | 22.10.2017 22:34:35 | INFO | Download starts: Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
199 | 22.10.2017 22:34:35 | WARNING | HOSTER BasePlugin[2]: Plugin may be unstable
200 | 22.10.2017 22:34:35 | INFO | HOSTER BasePlugin[2]: Grabbing link info...
201 | 22.10.2017 22:34:35 | INFO | HOSTER BasePlugin[2]: Link name: Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
202 | 22.10.2017 22:34:35 | INFO | HOSTER BasePlugin[2]: Link size: 513.47 MiB (538411928 bytes)
203 | 22.10.2017 22:34:35 | INFO | HOSTER BasePlugin[2]: Link status: starting
204 | 22.10.2017 22:34:35 | INFO | HOSTER BasePlugin[2]: Processing url: http://mydo.us.to/Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta/Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
205 | 22.10.2017 22:35:05 | WARNING | Couldn't connect to host or connection reset, waiting 1 minute and retry.
206 | 22.10.2017 22:36:05 | INFO | Download starts: Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
207 | 22.10.2017 22:36:05 | WARNING | HOSTER BasePlugin[2]: Plugin may be unstable
208 | 22.10.2017 22:36:05 | INFO | HOSTER BasePlugin[2]: Grabbing link info...
209 | 22.10.2017 22:36:05 | INFO | HOSTER BasePlugin[2]: Link name: Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
210 | 22.10.2017 22:36:05 | INFO | HOSTER BasePlugin[2]: Link size: 513.47 MiB (538411928 bytes)
211 | 22.10.2017 22:36:05 | INFO | HOSTER BasePlugin[2]: Link status: starting
212 | 22.10.2017 22:36:05 | INFO | HOSTER BasePlugin[2]: Processing url: http://mydo.us.to/Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta/Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
213 | 22.10.2017 22:36:35 | WARNING | Couldn't connect to host or connection reset, waiting 1 minute and retry.
214 | 22.10.2017 22:36:39 | INFO | Download aborted: Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
215 | 22.10.2017 22:36:41 | INFO | Download starts: http://mydo.us.to/DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta/DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta.mkv
216 | 22.10.2017 22:36:41 | WARNING | HOSTER BasePlugin[4]: Plugin may be unstable
217 | 22.10.2017 22:36:41 | INFO | HOSTER BasePlugin[4]: Grabbing link info...
218 | 22.10.2017 22:36:41 | INFO | HOSTER BasePlugin[4]: Link name: DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta.mkv
219 | 22.10.2017 22:36:41 | INFO | HOSTER BasePlugin[4]: Link size: N/D
220 | 22.10.2017 22:36:41 | INFO | HOSTER BasePlugin[4]: Link status: starting
221 | 22.10.2017 22:36:41 | INFO | HOSTER BasePlugin[4]: Processing url: http://mydo.us.to/DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta/DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta.mkv
222 | 22.10.2017 22:37:11 | WARNING | Couldn't connect to host or connection reset, waiting 1 minute and retry.
223 | 22.10.2017 22:38:11 | INFO | Download starts: DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta.mkv
224 | 22.10.2017 22:38:11 | WARNING | HOSTER BasePlugin[4]: Plugin may be unstable
225 | 22.10.2017 22:38:11 | INFO | HOSTER BasePlugin[4]: Grabbing link info...
226 | 22.10.2017 22:38:11 | INFO | HOSTER BasePlugin[4]: Link name: DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta.mkv

**Comment by arshiay** [comment]
`

22.10.2017 22:33:34 | WARNING | Couldn't connect to host or connection reset, waiting 1 minute and retry.
-- | -- | --
198 | 22.10.2017 22:34:35 | INFO | Download starts: Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
199 | 22.10.2017 22:34:35 | WARNING | HOSTER BasePlugin[2]: Plugin may be unstable
200 | 22.10.2017 22:34:35 | INFO | HOSTER BasePlugin[2]: Grabbing link info...
201 | 22.10.2017 22:34:35 | INFO | HOSTER BasePlugin[2]: Link name: Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
202 | 22.10.2017 22:34:35 | INFO | HOSTER BasePlugin[2]: Link size: 513.47 MiB (538411928 bytes)
203 | 22.10.2017 22:34:35 | INFO | HOSTER BasePlugin[2]: Link status: starting
204 | 22.10.2017 22:34:35 | INFO | HOSTER BasePlugin[2]: Processing url: http://mydo.us.to/Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta/Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
205 | 22.10.2017 22:35:05 | WARNING | Couldn't connect to host or connection reset, waiting 1 minute and retry.
206 | 22.10.2017 22:36:05 | INFO | Download starts: Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
207 | 22.10.2017 22:36:05 | WARNING | HOSTER BasePlugin[2]: Plugin may be unstable
208 | 22.10.2017 22:36:05 | INFO | HOSTER BasePlugin[2]: Grabbing link info...
209 | 22.10.2017 22:36:05 | INFO | HOSTER BasePlugin[2]: Link name: Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
210 | 22.10.2017 22:36:05 | INFO | HOSTER BasePlugin[2]: Link size: 513.47 MiB (538411928 bytes)
211 | 22.10.2017 22:36:05 | INFO | HOSTER BasePlugin[2]: Link status: starting
212 | 22.10.2017 22:36:05 | INFO | HOSTER BasePlugin[2]: Processing url: http://mydo.us.to/Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta/Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
213 | 22.10.2017 22:36:35 | WARNING | Couldn't connect to host or connection reset, waiting 1 minute and retry.
214 | 22.10.2017 22:36:39 | INFO | Download aborted: Fear.the.Walking.Dead.S03E15-E16.PROPER.720p.HEVC.x265-MeGusta.mkv
215 | 22.10.2017 22:36:41 | INFO | Download starts: http://mydo.us.to/DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta/DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta.mkv
216 | 22.10.2017 22:36:41 | WARNING | HOSTER BasePlugin[4]: Plugin may be unstable
217 | 22.10.2017 22:36:41 | INFO | HOSTER BasePlugin[4]: Grabbing link info...
218 | 22.10.2017 22:36:41 | INFO | HOSTER BasePlugin[4]: Link name: DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta.mkv
219 | 22.10.2017 22:36:41 | INFO | HOSTER BasePlugin[4]: Link size: N/D
220 | 22.10.2017 22:36:41 | INFO | HOSTER BasePlugin[4]: Link status: starting
221 | 22.10.2017 22:36:41 | INFO | HOSTER BasePlugin[4]: Processing url: http://mydo.us.to/DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta/DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta.mkv
222 | 22.10.2017 22:37:11 | WARNING | Couldn't connect to host or connection reset, waiting 1 minute and retry.
223 | 22.10.2017 22:38:11 | INFO | Download starts: DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta.mkv
224 | 22.10.2017 22:38:11 | WARNING | HOSTER BasePlugin[4]: Plugin may be unstable
225 | 22.10.2017 22:38:11 | INFO | HOSTER BasePlugin[4]: Grabbing link info...
226 | 22.10.2017 22:38:11 | INFO | HOSTER BasePlugin[4]: Link name: DCs.Legends.of.Tomorrow.S03E02.720p.HEVC.x265-MeGusta.mkv

`

**Comment by arshiay** [comment]
[log.txt](https://github.com/pyload/pyload/files/1405249/log.txt)
here is my log

**Comment by GammaC0de** [comment]
You did not enabled debug mode..
Also, please provide the output of the "route" command.

**Comment by arshiay** [comment]
i enabled it on menu under general section but ....

**Comment by arshiay** [comment]
ok 
i find how to activate debug mode 
i enabled it on menu under general but did not work
i start pyloadCore.py with --debug its ok  

[log.txt](https://github.com/pyload/pyload/files/1407579/log.txt)

i don't know which route do we need please explain more

thanks for your help

**Comment by arshiay** [comment]
[log.txt](https://github.com/pyload/pyload/files/1407619/log.txt)
@GammaC0de

**Comment by GammaC0de** [comment]
`route` command in linux our `route print` in windows.

**Comment by arshiay** [comment]
[routing.txt](https://github.com/pyload/pyload/files/1409273/routing.txt)

hi its my route

**Comment by arshiay** [comment]
someone help me

**Comment by GammaC0de** [comment]
What the IP 172.20.10.1 is used for? does it used for local LAN only or it is used for the internet also?

**Comment by arshiay** [comment]
hi
both network used for internet

**Comment by GammaC0de** [comment]
You cannot have two default gateways on the same host..

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by arshiay** [comment]
@GammaC0de hi
so what should i do?

**Comment by GammaC0de** [comment]
Only one interface can go out to the internet unless you want to use one specific interface to go to to a specific list of (static) IPs.
