### ISSUE TITLE
Releases and pip

### ISSUE THREAD

**Issue by murphy85** [pyload/pyload#2987]
Hi,
i'm wondering why the latest release 0.4.9 have been created 4 years ago and is older than the versions 0.4.7, 0.4.6, ...
0.4.9 and 0.4.8 have been created from stable and the others from master.

Why can't I find the pyload package in the package index under https://pypi.python.org/pypi?

Which version and how should we install pyload? The tarball installation refers to the master branch which should not be used... But in the stable branch there is no setup.py file

**Comment by Slevin7** [comment]
at the moment the only usable version is 0.4.9.

**Comment by murphy85** [comment]
Thank you! Then I need to switch to JDownloader on my qnap Nas because
share-online.biz is not working anymore with pyload.

Am 21.10.2017 15:44 schrieb "Slevin7" <notifications@github.com>:

**Comment by GammaC0de** [comment]
@murphy85 If you issue with a plugin just create an issue.
JDownloader is resource hungry and as far as i know it does not have a WebUI.

**Comment by murphy85** [comment]
You can remote control JDownloader with my JDownloader web interface. There are apps und browser extensions too. Very comfortable.
Resources... Yes! Because it's written in Java... :-/

**Comment by snickers2k** [comment]
almost a year later and still no release :(
i'm not too happy with jdownloader, but at least it works. tried 4 times to install pyload in the last years, but no success. maybe a release would be a great idea to actually get some users on board.

**Comment by GammaC0de** [comment]
@snickers2k A release will be released soon :wink: 
Meanwhile, please open a issue and I'm sure I can help you with the installation .
