### ISSUE TITLE
New Pyload Theme named PyPlex

### ISSUE THREAD

**Issue by xunil75** [pyload/pyload#2989]
PyPlex
=========

[![Codacy Badge](https://api.codacy.com/project/badge/Grade/b33743975ac9430aae4da10aa107c8a7)](https://www.codacy.com/app/xunil75/PyPlex?utm_source=github.com&utm_medium=referral&utm_content=xunil75/PyPlex&utm_campaign=badger)

**PyPlex Theme for Pyload**

Introduction
----
After creating a Theme for Ombi https://github.com/tidusjar/Ombi (former Plex Requests), I've decided to create a Theme as well for Pyload. 

I've used the Pyload "Next" theme as a base and the modified "Next" theme from https://github.com/OzzieIsaacs/pyload-NextTheme for the development of the PyPlex

This Theme it's inspired by PlexPy (https://github.com/JonnyWong16/plexpy) A Python based monitoring and tracking tool for Plex Media Server. That's why I've choosen the name PyPlex for this theme.

Install
----
Stop your pyload Server

```sh
sudo service pyload stop
```

Edit
----
navigate to '/usr/share/pyload/module/web' (in my case it's /home/user/.pyload/module/web)
Open the file webinterface.py for editing

```sh
sudo nano webinterface.py
```

Search for the following line in the file:

```sh
FileSystemLoader(join(PROJECT_DIR, "templates", "default")),
```

Insert the following line of code right after:

```sh
"PyPlex": FileSystemLoader(join(PROJECT_DIR, "templates", "PyPlex")),
```

Delete the file webinterface.pyc located in the same path.

```sh
sudo rm -rf webinterface.pyc
```
 
Copy the files inside the `template` folder from this repo to:

```sh
/usr/share/pyload/module/web/templates
```

Copy the files inside the `media` folder from this repo to:

```sh
/usr/share/pyload/module/web/media
```

Restart your pyload Server

```sh
sudo service pyload start
```

Configuration
----
Login into the PyLoad webinterface, navigate to the Config page, General Tab and click on "Webinterface". Enter the name of the new theme: "PyPlex" in the template field and hit "Submit"

Finally
----
Restart your pyload server

```sh
sudo service pyload restart
```

Screenshots
----
Login Page:

![login](https://user-images.githubusercontent.com/32961904/32053313-3ae1b85e-ba5b-11e7-8b4c-707a25b97e78.jpg)

Administration Page:

![administration](https://user-images.githubusercontent.com/32961904/32053410-8ff42c46-ba5b-11e7-9710-008e99999c5b.jpg)

Add Package:

![add-package](https://user-images.githubusercontent.com/32961904/32053485-ccb5eb9c-ba5b-11e7-89cd-2dd4a48ed7a7.jpg)

More Screenshots and Theme download here:

https://github.com/xunil75/PyPlex

**Comment by bigdargon** [comment]
Themes so nice, but frame Link so small when add mutilink

![](https://user-images.githubusercontent.com/32961904/32053485-ccb5eb9c-ba5b-11e7-89cd-2dd4a48ed7a7.jpg)

**Comment by xunil75** [comment]
@bigdargon, this issue has been solved, please check the original Repo and update the theme.

**Comment by bigdargon** [comment]
@xunil75 updated, so nice! thanks you!

![screen shot 2017-11-05 at 21 46 29](https://user-images.githubusercontent.com/10969626/32415839-d11489ae-c272-11e7-9d0d-30fc52795f6c.png)

**Comment by djraw** [comment]
Great theme, running flawlessly for about a week now here! :)

**Comment by CocaineCowboy** [comment]
I don't have the line "FileSystemLoader(join(PROJECT_DIR, "templates", "default"))," in my webinterface.py
How can I install PyPlex correctly (I installed the latest stable version of pyload)?

**Comment by xunil75** [comment]
@CocaineCowboy download the Theme and put it in the correct folder structure as explained above. One you've done that, login into your Pyload web-interface and navigate to Config - Webinterface and type the name of the Theme in there. Case sensitive!

That's it.
Cheers

**Comment by CocaineCowboy** [comment]
@xunil75 Thank you! Your theme works fine now.

**Comment by diegoweb** [comment]
Can we have the clear version of this theme, like the NextTheme itself?
Since this Theme is available at the official pyload repository, it would be cool to have a pyplex-clear version, and this one renamed to pyplex-dark or something like that.

Thank you!

**Comment by GammaC0de** [comment]
@diegoweb I plan to release a "bright" theme and already have a name for it.

**Comment by diegoweb** [comment]
@GammaC0de will it be officially supported like this theme from @xunil75 ? Thanks!

**Comment by GammaC0de** [comment]
Yes
