### ISSUE TITLE
extractarchive is not deleting extracted archives.

### ISSUE THREAD

**Issue by koenigmidas** [pyload/pyload#2992]
Hi,

I have just installed pyload correctly (manual from github).

everything working fine so far.

only issue is that "extractarchive" wont delete the zips after extracting. 

downloaded files are located on a mounted usb stick (exfat) running everything on the latest "rasbian".

It seems that I cant upload anything on the usb stick by ftp as well.
I guess there is something wrong with the rights on the usbstick?

but i am just a early beginner.

looking forward to every help.

thanks in advance

**Comment by GammaC0de** [comment]
Do you have send to trash option enabled? if so please turn is off.

**Comment by koenigmidas** [comment]
Hey Gamma,

here my current settings:

https://www2.pic-upload.de/img/34188935/OhneTitel.jpg

**Comment by GammaC0de** [comment]
Move to trash instead of delete, this option is set to "aus".
S, what does "aus" means, is it yes or is it no?

**Comment by koenigmidas** [comment]
aus is off in german :)

**Comment by GammaC0de** [comment]
So this is probably permissions issue.

Stop pyload and start is from the console with `pyLoadCore.py -d`  command and retry the download.
Look in the console for hint / exception.

**Comment by koenigmidas** [comment]
Hey gamma,
is this helpful:


1156 | 29.10.2017 01:06:11 | ERROR | ADDON ExtractArchive: xxx.part1.rar \| Extract failed
-- | -- | -- | --
1155 | 29.10.2017 01:06:11 | ERROR | ADDON ExtractArchive: xxx.part1.rar \| Archive error \| WARNING: Cannot change attributes of /media/usbstick2/RLSNAME/RLSNAME/NAME.mp4

PS: file is fully extracted and mp4 file is working, but zip files are still in the dir and not deleted.

Thanks in advande

**Comment by GammaC0de** [comment]
Definitely permissions issue.

Probably because of exFAT..

Why exFAT and not ext3?

**Comment by GammaC0de** [comment]
So, did you solved the issue?

**Comment by koenigmidas** [comment]
Hey Gamma


i switched to refered ext3 format.

extract archive is now working without problems. thx for that hint


but i have now a problem in deleting the files by ftp once I have transfered them to my nas.


once typed sudo chmod a+w -R /media/usbstick2/ by shh - i can delet my files without any problem.

but some minutes later it is no longer possible for my to delet the files before i have typed the cmd again.



can you guess what my mistake is?

**Comment by GammaC0de** [comment]
Try to use `ls -l` before and after the changes and compare the owner/permissions..

**Comment by koenigmidas** [comment]
hey Gamma,

here is the result:

https://pastebin.com/YafdbkGF

would be great if you can also solve this problem as well :)

**Comment by GammaC0de** [comment]
`drwxr-xr-x 2 pi   pi     4096 Sep  7 18:12 Downloads`
Only owner has write access..

Which user account is running pyLoad?

**Comment by koenigmidas** [comment]
I have installed pyload based on you manual.

so user should be pyload - correct?

**Comment by GammaC0de** [comment]
use `ps -ef | grep -i pyLoadCore` command to see

**Comment by koenigmidas** [comment]
thx mate.

here we go:

pyload     326     1  4 Nov04 ?        00:50:44 /usr/bin/python /opt/pyload/pyLoadCore.py
pi        8676  8626  0 10:39 pts/0    00:00:00 grep --color=auto -i pyLoadCore

**Comment by GammaC0de** [comment]
OK, so the user name is `pyload `.

**Comment by koenigmidas** [comment]
well noted,

so can you please tell me how to solve it - i am new to this business :)

**Comment by Burnout5151** [comment]
Depends on what you want.
If it's okay for you to grant write-access to everyone (admins might cringe here), you could simply tell PyLoad to change the permissions of the files/folders it creates:
_Config -> General -> Permissions -> Change file mode of downloads [**On**], Filemode for Downloads[**666**], Folder Permission mode[**666**]_
I'm not sure if the switch _Change file mode of downloads_ only affects files or folders as well. If you find out, post it here.

**Comment by koenigmidas** [comment]
Hey Burnout,

thx so far - how to solve this issue by shh?

**Comment by Burnout5151** [comment]
> how to solve this issue by shh?
I guess you mean _ssh_ ?

Do you really want to solve this issue via ssh? The aforementioned solution is easily achievable via Webinterface

**Comment by Burnout5151** [comment]
There are other possible solutions of course:
1. Configure via Webinterface: _Change Group and User of Downloads_ to create files as user _pi_
2. Don't ssh as user _pi_ but as user _pyload_ : ssh pyload@YourNAS (since user _pyload_ is running the process and creating the files)
3. run PyLoad as user _pi_ instead of _pyload_ ( wouldn't recommend this, as you already setup the _pyload_ user)

As I said: Depends on what you want. I'd probably recommend "1. Change owner"

**Comment by koenigmidas** [comment]
Sorry, mixed something up. ok i did it by webinterface of pyload.

i tried the Config -> General -> Permissions -> Change file mode of downloads [On], Filemode for Downloads[0666], Folder Permission mode[0666]...


give me 20minutes. i will test and report

**Comment by koenigmidas** [comment]
so just for my understanding.

I can not delete any file by ftp.
once I have typed: sudo chmod a+w -R /media/usbstick2/ (by ssh)

i can delete everything via FTP


so Burnout you got my problem?
this issue should be solved by a simple ssh cmd which stays permanently. the one which iam currently using seems only to be temp.

**Comment by Burnout5151** [comment]
Please do a `ls -l` for the files that have been downloaded after you changed pyload's config.  The ACL should look like this:
`-rw-rw-rw-`

**Comment by Burnout5151** [comment]
Oh and please do a `ls -l` for new folders as well, maybe _Change file mode of downloads_ only works on files?

**Comment by koenigmidas** [comment]
so steps will be:

1: webinterface:
Config -> General -> Permissions -> Change file mode of downloads [On], Filemode for Downloads[0666], Folder Permission mode[0666]...

2: ls -l via ssh


correct?

**Comment by Burnout5151** [comment]
Yes, 

1. connect via ssh
1. cd to your download-dir
1. do a ls -l
1. cd into a newly downloaded folder in your download-dir
1. do a ls -l again

**Comment by Burnout5151** [comment]
I'm not sure about the leading _0_ in  _Filemode for Downloads[**0**666]_ I hope it means "interpret the remainder as octal"

**Comment by koenigmidas** [comment]
so settings are now set to:
https://abload.de/img/seyj3e.jpeg

but i can not download any longer from a sourche which was working before for me:


19 | 05.11.2017 14:58:42 | WARNING | HOSTER ZippyshareCom[1298]: Free download failed \| IOError 13
-- | -- | -- | --

**Comment by Burnout5151** [comment]
I sthere still room on the device?
The IOError indicates that there is a problem with the target device
ssh to the machine and do `df -h` you should look for your target device and check how much space is still available

**Comment by Burnout5151** [comment]
Oh, sorry, wait a sec: IOError 13 is permission denied

**Comment by Burnout5151** [comment]
Okay, I'm confused now:
Since when do you get IOError 13?
It seems that between
[This comment](https://github.com/pyload/pyload/issues/2992#issuecomment-341972092) and [this comment](https://github.com/pyload/pyload/issues/2992#issuecomment-341975150) no changes were made?

**Comment by koenigmidas** [comment]
well i only changed the permisons via webinterface.
and the dl's are no longer working - anyway which source /link

I switched back to default which should be:
https://abload.de/img/ohnetiteljyuxz.jpeg


any help?

**Comment by GammaC0de** [comment]
Try `sudo chmod -R 777 <download_dir>`

**Comment by koenigmidas** [comment]
hey gamma

this is working. but only for a while. after a while i need to retype it again via ssh in order to be able to delete any file :(

**Comment by GammaC0de** [comment]
So it seems (I guess) that the FTP daemon is changing back the permission.
Try turning off the FTP daemon ad see if the permissions stays after that.

**Comment by GammaC0de** [comment]
No response, closing.
