### ISSUE TITLE
How to install current version of pyload

### ISSUE THREAD

**Issue by smschumacher** [pyload/pyload#2993]
Hello,

I am trying to install a current version of pyload on my Debian Stretch 9.1. My first question is:
Which branch do I use? Stable is clear, so is Testing. But how are the former two related to master?
Is Stable the most sensible choice?

What do I need to do after having checked out a branch with git? I have installed the dependencies already. It's python so I guess I do not need to compile anything. But how do I install the programm and is it neven necessary or can I do anything from the directory I cloned with git?

Yours
Stefan

**Comment by GammaC0de** [comment]
Cloning the git and installing the dependencies is enough.

**Comment by smschumacher** [comment]
Thank you. Could you also explain the differences between the "master", "develop" and "stable" branch?

**Comment by GammaC0de** [comment]
"stable" is the latest production version.
"master" is alpha development version.
As for "develop" branch, I don't know, maybe for backup.
