### ISSUE TITLE
The latest version of the update manager does not work for me

### ISSUE THREAD

**Issue by Vechio** [pyload/pyload#2995]
Hello
After replace **/usr/share/pyload/module/plugins/hooks/UpdateManager.py** with [https://github.com/pyload/pyload/raw/353c6692afdec4b6108555725cb5db46d02ed816/module/plugins/hooks/UpdateManager.py](https://github.com/pyload/pyload/raw/353c6692afdec4b6108555725cb5db46d02ed816/module/plugins/hooks/UpdateManager.py) 
I get an error in the log:
`"ERROR	Error importing UpdateManager: No module named misc"`

pyLoad 0.4.9
What should I do to get it working?

**Comment by GammaC0de** [comment]
Is this a new installation?

**Comment by Vechio** [comment]
No, this is an old installation from the old image (2013) of my hard drive

**Comment by GammaC0de** [comment]
You should have replaced **<PYLOAD_HOME>/userplugins/hooks/UpdateManager.py**...

How to fix:
- Stop pyLoad
- Delete your **<PYLOAD_HOME>/userplugins** directory
- Backup and then delete **accounts.conf**
- Replace **/usr/share/pyload/module/plugins/hooks/UpdateManager.py** with https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/830cb0161b416a5328e32516067608cd2cfdd031/UpdateManager.py
- Start pyLoad and wait for about 5 minutes for the update process to finish (look at the logs).
- Stop pyLoad and restore **accounts.conf**
- Start pyLoad.

**Comment by Vechio** [comment]
After this fix everything works and it updates correctly. I appreciate your help and thank you very much.

**Comment by GammaC0de** [comment]
👍
