### ISSUE TITLE
Pyload - doesnt  recognize Rapideo premium account

### ISSUE THREAD

**Issue by Maverick237** [pyload/pyload#2996]
Hi,

I installed Pyload 170116 on my Qnap a few days ago.
After that i added Rapideo plugin to the Pyload. 
All works fine but i don't know why Pyload can't see my Rapideo premium account.
I must write captcha and of course the transfer is very slowly.

Can you help me in this issue?

Regards
Maverick

**Comment by GammaC0de** [comment]
How exactly did you installed pyload?
Have you update UpdateManager.py as instructed in https://github.com/pyload/pyload/issues/2994?

**Comment by Maverick237** [comment]
I downloaded Pyload from here http://qoolbox.fr/ and i installed it through App Center of Qnap.
I haven't updated UpdateManager.py but i will do if it can resolve this problem.

**Comment by GammaC0de** [comment]
Updating UpdateManager.py is the first thing to do, without that you will not get plugin updates and there is a chance you are using outdated plugins.

**Comment by Maverick237** [comment]
OK it works :) thanks. 
But i have a small question ... how can i change login to Pyload because now my login is "qnap".

**Comment by GammaC0de** [comment]
>I have a small question ... how can i change login to Pyload because now my login is "qnap".

First you have to find where `files.db` resides.
When you find the answer to this question, issue the command `pythonn pyLoadCore.py --configdir=<PATH_OF_FILEDB> -u`

>And the last question. My destination folder in Pyload is: http://serverip:8001/pathchooser//share/Download
Where can i find it?

You can change the download folder if you enter the WenUI and go to configuration -> General -> Download Folder

**Comment by Maverick237** [comment]
Again i can't dowload. All plugin out of date. Please help me.
Now i have these in my logs:

634 | 03.11.2017 22:07:59 | WARNING | CRYPTER XupPl[22]: Plugin may be unstable
-- | -- | -- | --
635 | 03.11.2017 22:07:59 | INFO | CRYPTER XupPl[22]: Grabbing link info...
636 | 03.11.2017 22:07:59 | INFO | CRYPTER XupPl[22]: Link name: 8571605984
637 | 03.11.2017 22:07:59 | INFO | CRYPTER XupPl[22]: Link size: N/D
638 | 03.11.2017 22:07:59 | INFO | CRYPTER XupPl[22]: Link status: rozpoczynam
639 | 03.11.2017 22:07:59 | INFO | CRYPTER XupPl[22]: Processing url: http://5510.rapidu.xup.pl/folder/8571605984
640 | 03.11.2017 22:07:59 | INFO | CRYPTER XupPl[22]: Create package: rapidu.net \| 1 links
641 | 03.11.2017 22:07:59 | INFO | Added package rapidu.net containing 1 links
642 | 03.11.2017 22:07:59 | INFO | CRYPTER XupPl[22]: Save package `rapidu.net` to folder: rapidu.net
643 | 03.11.2017 22:08:01 | INFO | Decrypting starts: http://rapidu.net/folder/8571605984
644 | 03.11.2017 22:08:01 | WARNING | CRYPTER XFileSharingFolder[23]: RapiduNet \| Plugin may be unstable
645 | 03.11.2017 22:08:01 | INFO | CRYPTER XFileSharingFolder[23]: RapiduNet \| Grabbing link info...
646 | 03.11.2017 22:08:01 | INFO | CRYPTER XFileSharingFolder[23]: RapiduNet \| Link name: 8571605984
647 | 03.11.2017 22:08:01 | INFO | CRYPTER XFileSharingFolder[23]: RapiduNet \| Link size: N/D
648 | 03.11.2017 22:08:01 | INFO | CRYPTER XFileSharingFolder[23]: RapiduNet \| Link status: rozpoczynam
649 | 03.11.2017 22:08:01 | INFO | CRYPTER XFileSharingFolder[23]: RapiduNet \| Processing url: http://rapidu.net/folder/8571605984
650 | 03.11.2017 22:08:01 | INFO | CRYPTER XFileSharingFolder[23]: RapiduNet \| Looking for direct link...
651 | 03.11.2017 22:08:02 | INFO | CRYPTER XFileSharingFolder[23]: RapiduNet \| Direct link not found
652 | 03.11.2017 22:08:02 | INFO | CRYPTER XFileSharingFolder[23]: RapiduNet \| Checking for link errors...
653 | 03.11.2017 22:08:02 | INFO | CRYPTER XFileSharingFolder[23]: RapiduNet \| No errors found
654 | 03.11.2017 22:08:02 | INFO | CRYPTER XFileSharingFolder[23]: RapiduNet \| Decrypting as free link...
655 | 03.11.2017 22:08:02 | ERROR | Decrypting failed: 8571605984 \| Parse error: Free decrypted link not found \| Plugin may be out of date

`

**Comment by GammaC0de** [comment]
You should disable XFileSharing & XFileSharingFolder plugins, delete the package and then retry again.

**Comment by Maverick237** [comment]
OK i can download again, but it is still a problem with the download folder.
I set here -  configuration -> General -> Download Folder - http://myqnap/download/pyload, however i can't see any files there that i downloaded.
All goes to a folder: http://myqnap:8001/downloads/get/ . I can't find such patch in File Station on my qnap.

**Comment by GammaC0de** [comment]
Download folder is the local folder you want to download to, it does not start with `http://`
For example `/home/user/Downloads`

**Comment by Maverick237** [comment]
Again i can't download.  i think something wrong with the plugin. I deleted XFileSharing and the problem is again with that. Maybe i have to turn off any updates?

> 

841 | 04.11.2017 23:50:36 | INFO | CRYPTER XFileSharingFolder[29]: RapiduNet \| Checking for link errors...
-- | -- | -- | --
842 | 04.11.2017 23:50:36 | INFO | CRYPTER XFileSharingFolder[29]: RapiduNet \| No errors found
843 | 04.11.2017 23:50:36 | INFO | CRYPTER XFileSharingFolder[29]: RapiduNet \| Decrypting as free link...
844 | 04.11.2017 23:50:36 | ERROR | Decrypting failed: 8571605984 \| Parse error: Free decrypted link not found \| Plugin may be out of date
845 | 04.11.2017 23:51:29 | INFO | Added package auto containing 1 links
846 | 04.11.2017 23:51:29 | INFO | Decrypting starts: http://49d7.catshare.xup.pl/folder/0gZohm7jio0P9ACE
847 | 04.11.2017 23:51:29 | WARNING | CRYPTER XupPl[30]: Plugin may be unstable
848 | 04.11.2017 23:51:29 | INFO | CRYPTER XupPl[30]: Grabbing link info...
849 | 04.11.2017 23:51:29 | INFO | CRYPTER XupPl[30]: Link name: 0gZohm7jio0P9ACE
850 | 04.11.2017 23:51:29 | INFO | CRYPTER XupPl[30]: Link size: N/D
851 | 04.11.2017 23:51:29 | INFO | CRYPTER XupPl[30]: Link status: rozpoczynam
852 | 04.11.2017 23:51:29 | INFO | CRYPTER XupPl[30]: Processing url: http://49d7.catshare.xup.pl/folder/0gZohm7jio0P9ACE
853 | 04.11.2017 23:51:29 | INFO | CRYPTER XupPl[30]: Create package: catshare.net \| 1 links
854 | 04.11.2017 23:51:29 | INFO | Added package catshare.net containing 1 links
855 | 04.11.2017 23:51:29 | INFO | CRYPTER XupPl[30]: Save package `catshare.net` to folder: catshare.net
856 | 04.11.2017 23:51:31 | INFO | Decrypting starts: http://catshare.net/folder/0gZohm7jio0P9ACE
857 | 04.11.2017 23:51:31 | WARNING | CRYPTER XFileSharingFolder[31]: CatshareNet \| Plugin may be unstable
858 | 04.11.2017 23:51:31 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Grabbing link info...
859 | 04.11.2017 23:51:31 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Link name: 0gZohm7jio0P9ACE
860 | 04.11.2017 23:51:31 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Link size: N/D
861 | 04.11.2017 23:51:31 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Link status: rozpoczynam
862 | 04.11.2017 23:51:31 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Processing url: http://catshare.net/folder/0gZohm7jio0P9ACE
863 | 04.11.2017 23:51:31 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Looking for direct link...
864 | 04.11.2017 23:51:32 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Direct link not found
865 | 04.11.2017 23:51:32 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Checking for link errors...
866 | 04.11.2017 23:51:32 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| No errors found
867 | 04.11.2017 23:51:32 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Decrypting as free link...
868 | 04.11.2017 23:51:32 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Create package: catshare.net \| 1 links
869 | 04.11.2017 23:51:32 | INFO | Added package catshare.net containing 1 links
870 | 04.11.2017 23:51:32 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Save package `catshare.net` to folder: catshare.net
871 | 04.11.2017 23:51:32 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Create package: as poradnik-11 \| 1 links
872 | 04.11.2017 23:51:32 | INFO | Added package as poradnik-11 containing 1 links
873 | 04.11.2017 23:51:32 | INFO | CRYPTER XFileSharingFolder[31]: CatshareNet \| Save package `as poradnik-11` to folder: as poradnik-11
874 | 04.11.2017 23:53:36 | INFO | Added package poradnik containing 1

**Comment by GammaC0de** [comment]
You don't delete XFileSharing , you disable it in pyload's plugin configuration...

**Comment by GammaC0de** [comment]
No response, closing.
