### ISSUE TITLE
New Theme on the way

### ISSUE THREAD

**Issue by xunil75** [pyload/pyload#2997]
Hi guys, i'm creating a new Theme for Pyload and this is the login Window for now. The complete Theme will probably be ready at the end of next week.

Password input with visibility toggle working as well!
Let me know what you think!

# Mobile View:
![pyload_iphone8plusspacegrey_portrait](https://user-images.githubusercontent.com/32961904/32324420-a935758c-bfcb-11e7-8446-b4c34cb1803e.png)

# Browser View:
![pyload-browser](https://user-images.githubusercontent.com/32961904/32325741-7a0ded7a-bfd0-11e7-835e-20be598abc74.jpg)

# Active Downloads:
**Collapse window on the right corner working!**

![active-downloads](https://user-images.githubusercontent.com/32961904/32371769-62cc6bba-c092-11e7-911b-d5470b3640dd.jpg)

# Tooltip:
![tooltip](https://user-images.githubusercontent.com/32961904/32382427-793ade68-c0b5-11e7-98a1-ae3b4d11b09d.jpg)

# Modal Window:
![modal-window](https://user-images.githubusercontent.com/32961904/32382893-c1f73b14-c0b6-11e7-813d-7cda8953ceb8.jpg)

# Config Page
![config-page](https://user-images.githubusercontent.com/32961904/32842787-4894f65a-ca1e-11e7-96d8-0a40e77f50af.jpg)

Follow the progress here:
https://github.com/xunil75/PyWhite

**Comment by GammaC0de** [comment]
Looks great! 😀

**Comment by bigdargon** [comment]
waiting 😄

**Comment by GammaC0de** [comment]
@xunil75 Are you a coder also or just a graphic designer?
I mean, can you add more features to the theme?

**Comment by xunil75** [comment]
@GammaC0de actually more graphic but css it’s also code. What do tou have in mind? Please open an issue on my repo since this is not the right place!

Cheers

**Comment by GammaC0de** [comment]
Just an idea I have for some quite a time:
Some hosters block javascript-less Recapcha, so for solving this kind of Recaptcha you'll have to open a new browser window (where javascript works) and solve it from there.

Currently, pyLoad WebUI lacks this functionality.

**Comment by xunil75** [comment]
@GammaC0de Do you have an example so that I can have a look?

**Comment by GammaC0de** [comment]
If you try to download https://uploadgig.com/file/download/4766f603ddF932dd/TMF2.6.17.part01.rar with JDownloader you will see what I mean.

**Comment by Lalarian** [comment]
It's looking really nice. Would be great uf it could also increase Pyload's functionality of course!

**Comment by GammaC0de** [comment]
Hello, any progress on this?

**Comment by C2N14** [comment]
@xunil75 Any updates? I was really looking forward to this :(

**Comment by GammaC0de** [comment]
Sorry, closing.
