### ISSUE TITLE
DLC Decrypting failed

### ISSUE THREAD

**Issue by kitzler-walli** [pyload/pyload#2998]
I constantly receive the following error on ubuntu:
Version 0.4.9 pyload

```WARNING	CONTAINER DLC[27]: Plugin may be unstable
INFO	CONTAINER DLC[27]: Grabbing link info...
INFO	CONTAINER DLC[27]: Link name: f8ec4ea2c2b756a69800485a6b9a4f.dlc
INFO	CONTAINER DLC[27]: Link size: N/D
INFO	CONTAINER DLC[27]: Link status: starting
INFO	CONTAINER DLC[27]: Processing url: http://xxx/Downloads/f8ec4ea2c2b756a69800485a6b9a4f.dlc
ERROR	Decrypting failed: tmp_f8ec4ea2c2b756a69800485a6b9a4f.dlc | (18, 'transfer closed with 19 bytes remaining to read')
```

I updated all plugins and this error still pops up.

**Comment by GammaC0de** [comment]
Post the DLC file please.
If you don't want to post here, I can give you email if you like.

**Comment by kitzler-walli** [comment]
Currently I experience this with all dlc files from relink.to - could you give me your mailaddress?

**Comment by GammaC0de** [comment]
Please send the file to nitzo2001 at yahoo dot com.

**Comment by kitzler-walli** [comment]
I've sent you a container by mail.

**Comment by GammaC0de** [comment]
This DLC is corrupted and I'm pretty sure is does not work in JDownloader too.

**Comment by kitzler-walli** [comment]
ok thank you for analysing this.
