### ISSUE TITLE
LinkFilter Plugin whitelisting

### ISSUE THREAD

**Issue by segelkma** [pyload/pyload#3000]
Hi, some time ago I made the LinkFilter Hookplugin:
https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/LinkFilter.py

I would like to add the functionality to invert the behaviour (whitelisting), so that only those links pass, that are in the list. I implemented it but unfortunately it effects all links (crypters and containers). This does not make much sense, so I would like it to work only on hoster plugins. However the Hook API only provides the links in a list and a pid for the event linksAdded:
https://github.com/pyload/pyload/wiki/module.HookManager.HookManager

How do I find out if the link belongs to a hoster plugin? I know that every hoster plugin has a pattern. This is the way that pyload determines which plugin to use for which link right?
But I have no idea on how check them.
Is it even possible within a hook plugin?

Thanks.

**Comment by GammaC0de** [comment]
Untested:
```python
        hosters_dict = self.pyload.pluginManager.hosterPlugins
        links_dict = self.pyload.api.checkURLs(links)
        if any(True for plugin_name in links_dict if plugin_name in hosters_dict):
            pass
```

**Comment by segelkma** [comment]
Thanks, first two lines are working (didn't check third yet). Now I got something to work with.
Can be closed.

**Comment by segelkma** [comment]
Or wait a second:
What would you prefer as an option for the filter list? The current version requests url's to be filtered (e.g. share-online.biz). Would it possibly make more sense to ask the user to input the pluginname into the filterlist (e.g. ShareonlineBiz)?
I can implement either option

**Comment by GammaC0de** [comment]
I think using share-online.biz is more diverse because you can limit just one host that the hoster support.
