### ISSUE TITLE
Decrypting Filecrypt.cc does not work anymore

### ISSUE THREAD

**Issue by j4m** [pyload/pyload#3001]
For every link i'm adding from Filecrypt.cc i get the folowing error:

> Bad server response: 500 Internal Server Error

**Comment by GammaC0de** [comment]
Fixed.

You have to use the updated [HTTPreuest.py](https://github.com/pyload/pyload/raw/stable/module/network/HTTPRequest.py) to use this fix.

**Comment by j4m** [comment]
Thanks but for Links without captcha it doesn't work.

Example:
http://filecrypt.cc/Container/EDA512FA64.html

**Comment by GammaC0de** [comment]
👍 Updated.

**Comment by c0rrre** [comment]
Same error here, already updated to new crypter version

**Comment by GammaC0de** [comment]
http://filecrypt.cc/Container/EDA512FA64.html works fine for me..

Please start pyload from the console with `pyLoadCore.py -d` , start a download and then provide the log from the console.

**Comment by segelkma** [comment]
Also works fine for me. Did you delete the HTTPRequest.pyc?

**Comment by c0rrre** [comment]
Oh... looks like I only deleted the Filecrypt.pyc :D

fixed, thanks guys

**Comment by j4m** [comment]
Pardon, deleting the .pyc worked. Thanks.
