### ISSUE TITLE
zippyshare downloads not working anymore

### ISSUE THREAD

**Issue by kingmidass** [pyload/pyload#3002]
Hi 

I have installed pyload like it is shown here.

it was working all the time till now.
Not working with zippy share.

I have not changed a thing and from 1 to another day it is not working :(

can any1 help me?

here is the log:
https://pastebin.com/y4BxPpTB

**Comment by GammaC0de** [comment]
Works fine for me..

How exactly did you installed pyLoad?

**Comment by kingmidass** [comment]
I used your manual. 
Strange - it worked for me for weeks. But now i got problems

**Comment by GammaC0de** [comment]
Which manual exactly?

**Comment by kingmidass** [comment]
https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi)



I am using a socks5 proxy. And once i am turning it off it works. 
I have changed to several Proxy locations but without success. 


But on the Other Hand i Can Download from shareonline sources with the proxy. 

Really Strange. Possible that zippyshare changed something???

**Comment by GammaC0de** [comment]
Maybe they have a list of proxies and the act different if one connect via proxy..

Why use proxy, privacy?

Since it works without proxy, it is not a pyLoad issue, closing.
