### ISSUE TITLE
TLS Error with XMPP

### ISSUE THREAD

**Issue by Franzl123** [pyload/pyload#3003]
Hi,

i get an TLS Error, when is try to connect to my XMPP-Account

here is the XMPP Part from the debug log

`ADDON XMPP: *** State changed: resolving srv (u'trashserver.net', 'xmpp-client') ***`
`ADDON XMPP: *** State changed: resolving 'h-pollux.650thz.de.' ***`
`ADDON XMPP: *** State changed: connecting ('2a00:f820:417::27e9:4b06', 5222) ***`
`ADDON XMPP: *** State changed: connecting ('5.1.76.122', 5222) ***`
`ADDON XMPP: *** State changed: connected ('5.1.76.122', 5222) ***`
`ADDON XMPP: *** State changed: tls connecting ***`
`ADDON XMPP: TLS Error: [Errno 1] _ssl.c:504: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version`

the login data i entered are correct (works on desktop and smartphone)

what exactly is the difference between XMPP and XMPPInterface?

**Comment by GammaC0de** [comment]
Try upgrading to the latest pyxmpp, openssl and pyOpenSSL

**Comment by GammaC0de** [comment]
No response, closing.
