### ISSUE TITLE
[API Question] where do i register a new hook?

### ISSUE THREAD

**Issue by Lerentis** [pyload/pyload#3005]
Hello There,

i wanted to write my own hook to trigger a rescan of my kodi library after another hook (FileBot) has finished, but i dont know how event_map is handled by pyload.
i looked at the [wiki](https://github.com/pyload/pyload/wiki/Hooks), but i think it is outdated here? if i want to use `module.plugins.Hook` i get the error in pyload:
```
RescanKodi: No module named Hook
```
i looked at other plugins and they all used `module.plugins.internal.Addon`, so i am using it to inherit from it as well for now. now my hook loads, but never actually runns. here is my event map

```
    event_map = {'allDownloadsFnished': "kodi_scan_triggered",
                 'package_finished': "kodi_scan_triggered",
                 'coreReady': "initialize"}
```
if i have understood it correctly the event_map of a plugin or hook should map functions to be executed if a certain event is fired by pyload, like in a observer pattern, but not even the initialize function is fired. did i misunderstand something here? 
would be happy about any hint here. my code so far can be found here: https://git.burntbunch.org/lerentis/Pyload-Stuff

**Comment by GammaC0de** [comment]
Register event listener: `self.pyload.hookManager.addEvent("my_custom_event", self.do_somthing)`

Fire an event: `self.pyload.hookManager.dispatchEvent(("my_custom_event",  arg1, arg2, argN)`
