### ISSUE TITLE
Broken setup.py installer

### ISSUE THREAD

**Issue by DominicMe** [pyload/pyload#3006]
I am trying to install pyload but it seems completely broken. Pip installer guide is just plain wrong as there isn't even a packagecalled pyload-ng as stated. pyload pip package does exist though says it version 0.1 and fails to install anyways. Tarbal installation fails with the below error:

```
sudo python setup.py install

/usr/lib/python2.7/site-packages/setuptools/dist.py:347: UserWarning: Normalizing '1.0.0-alpha' to '1.0.0a0'
  normalized_version,
running install
running bdist_egg
running build_locale
Traceback (most recent call last):
  File "setup.py", line 172, in <module>
    zip_safe=True)
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 101, in run
    self.run_command('build_locale')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 970, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 846, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 147, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 64, in __init__
    self.initialize_options()
  File "/usr/lib64/python2.7/distutils/cmd.py", line 136, in initialize_options
    "abstract method -- subclass %s must override" % self.__class__
RuntimeError: abstract method -- subclass __main__.BuildLocale must override

```

Is this project just dead or is it possible to install somehow? The errors I have seen are less that useless so far.

**Comment by Slevin7** [comment]
You should use the stable release, master is not ready at the moment

**Comment by DominicMe** [comment]
Ugh, I did use stable from the releases page (pyLoad 0.4.9). There is only 1 option from pip and it doesn't work  either.

**Comment by Velociraptor85** [comment]
try https://github.com/pyload/pyload/issues/2000

**Comment by DominicMe** [comment]
@Velociraptor85  The error in the original post is what I get when I try to install as stated. I am on fedora so there is no pre-compiled package and pip seems to be unusable either as the version is 0.1 there.

**Comment by GammaC0de** [comment]
Just get https://github.com/pyload/pyload/archive/stable.zip and unpack to /usr/share/pyload

You would need also to install the dependencies such as pycurl etc..

**Comment by floviolleau** [comment]
Hi,

Thanks for your work @GammaC0de!

We understand that master branch is unstable but I want to try pyload on master branch just for dev to better understand the project.

I saw many times "You should use the stable release, master is not ready at the moment" but we want to understand what is the problem and try to help you how to solve it.

KR.

**Comment by GammaC0de** [comment]
It's nice to see that more developers like to help in the development of the project 😀 

The status of the master branch (an almost a complete rewrite which @vuolter is responsible to) is pre-alpha and is incomplete.
At the moment there is no running version of it (as far as I know).

If you would like to help with the development, you are more than welcome and you should contact @vuolter .

**Comment by GammaC0de** [comment]
Closing, you can still post here is you have any comment 😉

**Comment by Velociraptor85** [comment]
@DominicMe @floviolleau as far as I know @pyblub and @adamantike  where also doing some progress on the next gen edition so mayber you could contact them also in the https://gitter.im/pyload/pyload chat you will find maybe some more info and regular comments :) happy to see some more devs wanting to help out with a hand or two :) 👍

**Comment by DominicMe** [comment]
I did eventually get it to work with the stable branch, thanks for the suggestion. I have to say it's the worst git repo I have ever come across. It seems actively developed yet completely neglected at the same time. I really dont get it, why is the master branch broken while stable works? Why not merge stable and master? Why is the documentation just hoplessly incorrect and none of the devs though of at least removing invalid parts to avoid unnecesary confusion? There is very little chance any new user would be able to figure this mess out. You can't even find the download link for stable anywhere withut a direct link. After all that it doesn't even seem to work, it just keeps resetting the timer after captcha is entered. I was gonna post an install guide for fedora though it doesn't seem to be usable at this point so not sure if it's worth the time.

**Comment by GammaC0de** [comment]
> Why is the documentation just hopelessly incorrect and none of the devs though of at least removing invalid parts to avoid unnecessary confusion?

The developers team consists of mainly two people: me and @vuolter.
Beeing low numbered, there is not much time left for such things.
I am busy fixing bugs in the stable branch and keeping the plugins up-to-date and @vuolter is busy rewriting pyLoad and with bug fixes that cannot be solved without a rewrite.
Put that aside, we all are first busy with real life and the time we invest here is our spare time.

If you have any comment / improvement to suggest or provide, we surly need help.. 

> why is the master branch broken while stable works? Why not merge stable and master

The stable and the master are *completely* different and incompatible.

>You can't even find the download link for stable anywhere without a direct link

https://github.com/pyload/pyload/releases and #2000 

>After all that it doesn't even seem to work, it just keeps resetting the timer after captcha is entered.

Please open an issue for that.

Cheers 😉

**Comment by DominicMe** [comment]
@GammaC0de I get that but surely a broken branch should not be master? I also understand how easy it is to concentrate on programming and neglect documentation but not much point in fixing bugs if no one can install it. At the very least the project is loosing users and maybe new devs too becasue it appears broken and neglected.
It's weird I could swear I downloaded that tar twice and it had setup.py and other files from master branch... Times like these I really miss arch, so easy to install from AUR. Will open a bug request when I test it out a bit more, thanks.

**Comment by pyblub** [comment]
@DominicMe Believe me, I fell you.

Again big thanks for @GammaC0de. He is doing an amazing job keeping the stable branch and plugins alive. The stable works fine, at least for me. I have it running for quite a while.

@floviolleau The master is broken. Many things that are in pyload-_stable_ are not available in master yet. Imagine building a car and all you got is a broken engine.

If anyone is interested, here is an example of how I start (not actually run) pyload-_master_ at the moment to:

```python
from pyload.core import Core
c = Core('/my/config/folder', '/my/temp/folder')

def start(x):
    x.run()

import threading
t = threading.Thread(target=start, args=(c,))

t.start()

name = 'package_name'
folder = 'package_folder'

c.filemanager.add_package(name, folder, '', '', '', '', None, 1)

url = 'http://url.to.file'
plugin = 'NoneAvalabileAtTheMoment'
data = [(url, plugin)]
c.filemanager.add_links(data, pkg, owner)

# to exit properly, but does it immediately
# c.exit()

# if exit is not called. this join will never happen and core will never stop
t.join()
```

I have not installed pyload, I just run it from the same directory.

I also did not have much time lately, but I was able to analyse some components and I'm close to actually download the first file from a hoster. Yes, that's the current state. You cannot download anything with pyload-_master_ at the moment.

There are many problems. So any help is highly appreciated.
The config parser is broken and overly complicated. Why not use a config parser library, there are many options available.
The database layer/access is also overly complicated and seems to reimplement a lot of stuff a database takes care on its own.
Not even the main loop works. Not sure what it is even supposed to be doing.

I may need to open issues for these things separately, so they can be discussed properly.

Fixing any of those things above, or even just cleaning the documentation would be a big help.
Also someone on twitter asked for a docker container for pyload. That should be rather easy for stable.

As soon as I have been able to download the first file, I will show the log and provide the necessary fixes.

**Comment by DominicMe** [comment]
@pyblub What exactly is the reason for running master as opposed to stable?

With stabe I am able to install but have issues. On fedora at least for some reason python-imaging dependency doesn't get satisfied by tesseract and python-pillow. I wasn't able to download either at least not from rapidgator.

**Comment by pyblub** [comment]
I use master for development only. I try to get it working.

**Comment by GammaC0de** [comment]
FYI there is a pyload docker https://github.com/obi12341/docker-pyload and RapidgatorNet plugin has been updated yesterday and it works now.
