### ISSUE TITLE
Premium download failed | IOError 13

### ISSUE THREAD

**Issue by mkjaxxo** [pyload/pyload#3007]
Hi there, 

I get this error with HOSTER SmoozedCom. IOError 13 is related to a permission issue? Is this correct? Download folder is writable for pyload.

Any hint is highly appreciated. 
Thanks, Markus

**Comment by GammaC0de** [comment]
IOError 13 is permission denied.

How exactly did you installed pyload?

**Comment by mkjaxxo** [comment]
@GammaC0de Thanks for your reply. I followed these steps 
https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi)
and Pyload was up and running perfectly. Then a deleted an outdated Account (upload.net) and everything stopped working.

**Comment by mkjaxxo** [comment]
Tested it once again and it is working now without any change from my side. Sorry for this "false alarm".
