### ISSUE TITLE
Fehler beim importieren von UpdateManager: No module named misc

### ISSUE THREAD

**Issue by Lalarian** [pyload/pyload#3008]
Hello!

After some days with that "Pyload update is available message" in the header of my pyload serve, I came here and found the UpdateManager.py patch and installed it.

Now it seems to be working ok, but on every Pyload start there's this message in thelog:
"Fehler beim importieren von UpdateManager: No module named misc".

**Comment by GammaC0de** [comment]
Please delete the userplugins directory.

**Comment by GammaC0de** [comment]
So is it working?

**Comment by Lalarian** [comment]
Sorr, the error remains:

ERROR | Fehler beim importieren von UpdateManager: No module named misc
-- | --

Also I had a look at userplugins before. There was nothing in besided thoese empty __init files.

**Comment by GammaC0de** [comment]
Delete userplugins directory (again) and replace UpdateManager.py with this one: https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/830cb0161b416a5328e32516067608cd2cfdd031/UpdateManager.py

**Comment by Lalarian** [comment]
Now it changed to:

"

ERROR | Fehler beim importieren von UpdateManager: No module named Hook
-- | --

"

**Comment by Lalarian** [comment]
OK, got everything workign now.
I manually copied pyload stable to share again.
Why does this always happen?
For some time Pyload is working, but then there are strange problems and they always result from some files being outdated on my server.

Am I doing something wrong?

**Comment by GammaC0de** [comment]
This happens because the pyload release package comes with an outdated UpdateManager.py which uses an unused old URL to get updates resulting in that pyload does not get any updates.

From you aswer I gould not understand if you fully managed to solve this issue...

**Comment by Lalarian** [comment]
Yes, it's ok. Thank you.
