### ISSUE TITLE
cannot concatenate 'str' and 'NoneType' objects 500.00 MiBFilerNet

### ISSUE THREAD

**Issue by Lalarian** [pyload/pyload#3009]
Hello!

There's a problem with downloading from filer.net, using otherwise working links:
"cannot concatenate 'str' and 'NoneType' objects 500.00 MiBFilerNet"
Example:
http://filer.net/get/vblmdb5jdq0wnbo6
http://filer.net/get/brnlisndtbxwbcea
http://filer.net/get/57a2igm6xu1mv246

I attached one of the debug reports.

Thank you! :)

[debug_FilerNet_13-11-2017_11-11-32.zip](https://github.com/pyload/pyload/files/1466366/debug_FilerNet_13-11-2017_11-11-32.zip)

**Comment by GammaC0de** [comment]
Tested fine with plugin version 0.26.
Have you solved #3008 ?

**Comment by Lalarian** [comment]
Not, yet.
So what does this error mean?
Could you have a look at the debug report please?

**Comment by Lalarian** [comment]
OK, it's working with current version.
I manually copied whole pyload from stable to share.
