### ISSUE TITLE
[ShareOnlineBiz] waiting 5 mins and downloading error html instead 

### ISSUE THREAD

**Issue by michbeck100** [pyload/pyload#3010]
I'm using the latest plugin version and the download from ShareOnline isn't working. I switched from UL and bought a premium account and the login seems to work. But every downloads starts with 5 mins waiting time and after that pyload just downloads an html page containing an error page from share online saying that an unknown error occurred.

Anyone having the same problem?

**Comment by michbeck100** [comment]
After turning on debug mode i can see that it gets the correct download url. This url is 300 seconds valid. This is exactly the time the plugin is waiting! So when the download starts, the url just got invalid.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Also please post the debug log..

**Comment by GammaC0de** [comment]
After investigating this, the problem is not in pyload, it relies in share-online's API:
If you try to download a file with download URL that share-online's API generates, you will get an error page (http://www.share-online.biz/dl/unknown/failure/precheck) instead of a file download.

Please contact their support, thanks.

**Comment by michbeck100** [comment]
Yes, by using jdownloader. Seems that they know how to handle this.

**Comment by GammaC0de** [comment]
@michbeck100 , @andrem1987 , @Mister-XY It's working now, please update `RequestFactory.py`

**Comment by locke45** [comment]
The ISSUE ist still present for me.
Fresh install from stable branch.

Bugfix [RequestFactory] Fix #3010, #3011 is applied:
[/opt/share/pyload/module/network] # cat RequestFactory.py | grep "def getRequest"
    def getRequest(self, pluginName, account=None, type="HTTP", **kwargs):

[lDebugLog.txt](https://github.com/pyload/pyload/files/1864766/log.txt)

**Comment by GammaC0de** [comment]
@locke45 
Your plugin is not up-to-date:
Current latest plugin is v0.68 while you are using v0.66...
