### ISSUE TITLE
Issues with UploadedTo Plugin

### ISSUE THREAD

**Issue by S3NS4Ti0N** [pyload/pyload#3011]
since commit https://github.com/pyload/pyload/commit/d2ad5d986ced31b96ef6553af9f776c7c7c34317 i have to enter captchas for my downloads, even though I have a premium account.

If I use the commit before this one, everything is working fine.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
It's working now, please update `RequestFactory.py`

**Comment by S3NS4Ti0N** [comment]
Can confirm that its working
