### ISSUE TITLE
FilecryptCc - Failed writing body

### ISSUE THREAD

**Issue by oltodosel** [pyload/pyload#3012]
I suspect error occurs because of the large number of files - 2380.

> 490 | 16.11.2017 00:32:25 | INFO | Decrypting starts: 846151D3EA.html
> 491 | 16.11.2017 00:32:25 | WARNING | CRYPTER FilecryptCc[7444]: Plugin may be unstable
> 492 | 16.11.2017 00:32:25 | INFO | CRYPTER FilecryptCc[7444]: Grabbing link info...
> 493 | 16.11.2017 00:32:25 | INFO | CRYPTER FilecryptCc[7444]: Link name: 846151D3EA.html
> 494 | 16.11.2017 00:32:25 | INFO | CRYPTER FilecryptCc[7444]: Link size: N/D
> 495 | 16.11.2017 00:32:25 | INFO | CRYPTER FilecryptCc[7444]: Link status: starting
> 496 | 16.11.2017 00:32:25 | INFO | CRYPTER FilecryptCc[7444]: Processing url: http://filecrypt.cc/Container/846151D3EA.html
> 497 | 16.11.2017 00:32:25 | WARNING | CAPTCHA FilecryptCc[7444]: ReCaptcha \| Secure Token pattern not found
> 498 | 16.11.2017 00:32:51 | INFO | CAPTCHA FilecryptCc[7444]: ReCaptcha \| Captcha result: `248`
> 499 | 16.11.2017 00:32:51 | INFO | CAPTCHA FilecryptCc[7444]: ReCaptcha \| Path deleted: /home/u/.pyload/tmp/captcha_image_FilecryptCc_14627.jpg
> 500 | 16.11.2017 00:32:51 | INFO | CAPTCHA FilecryptCc[7444]: ReCaptcha \| Correct captcha \| 248
> 501 | 16.11.2017 00:32:52 | ERROR | Decrypting failed: 846151D3EA.html \| (23, 'Failed writing body (0 != 1440)')

**Comment by GammaC0de** [comment]
Most probably this is the cause of this issue and is can be solve but does it worth it for just one URL?
Does other FilecryptCc URLs works for you?

**Comment by oltodosel** [comment]
Other Filecrypt urls with less links work fine. 
I would like this issue to be resolved, if it isn't too much of a hassle. I encountered this before without reporting, opting just to forgo them.

**Comment by GammaC0de** [comment]
OK, I will update is soon,
