### ISSUE TITLE
ClicknLoad CNL should merge links

### ISSUE THREAD

**Issue by MaluNoPeleke** [pyload/pyload#3017]
Currently I am using [this Chrome browser extension](https://chrome.google.com/webstore/detail/redirect-clicknload/hnjbnefgkiickkpfidpnlmcodicfgakk) to use ClicknLoad with PyLoad but the problem is that all the links will be added to separate folders/downloads.
It would be nice to have them merged together as a package which I can give a name to.

**Comment by GammaC0de** [comment]
Hi,
folders/downloads means separate package?

Can you give and example of the current behavior and the desired behavior?

**Comment by MaluNoPeleke** [comment]
If I click on a [Clicknload 2](http://jdownloader.org/knowledge/wiki/glossary/cnl2) button with multiple URLs like in [this example](https://jsfiddle.net/p5zepajk/) all the links will be added separately to the link collector of Pyload and I have to rename everyone of them to the same folder.
Expected behavior is all added links will be added to the same package.

**Comment by MaluNoPeleke** [comment]
Thanks a lot for the quick support!
