### ISSUE TITLE
Youtube download

### ISSUE THREAD

**Issue by Maverick237** [pyload/pyload#3018]
Hello,

I have never downloaded youtube video through pyload.
Can someone tell me how to configure that and what plug in i have to install?

Thank you.

**Comment by GammaC0de** [comment]
YouTube download should work as ever supported URLs by pyLoad:
You create a new package with the YouTube URL(s) in it.

Just make sure you have pyload properly installed (downloading the latest [stable](https://github.com/pyload/pyload/archive/stable.zip) git branch is prefered or either read #2000).

You also can find the plugin configuration (usually no modification is needed) if you go to config->plugins->YouTube.

**Comment by Maverick237** [comment]
Hi,

It works but each video is downloaded in 720p instead of 1080p. I set 1080p in the youtube plugin,
so why i receive files in 720p?

**Comment by GammaC0de** [comment]
@Maverick237 Currently this what it can download (because of historical reasons).
I am working now to improve it to support even 2160p.

I am leaving this issue open,
When I finish, I will update you here and you can help by testing some URLs

**Comment by Maverick237** [comment]
OK, thank you. I'm waiting for your message here.

**Comment by GammaC0de** [comment]
OK,
Finally it's done, please test and report.

Please review your plugin settings before testing.
Also, please note that you have to have `ffmpeg` installed for post processing (embedding subtitles and merging audio and video)

Waiting for your feedback.

**Comment by Maverick237** [comment]
Hi,

Now it works fine thanks.

But i have another question. When i add a new pack to download i write for example "new1" in the name of the pack field. However after i download the files, i get the files in the folder "catshare.net". By previous versions, pyload created the same name of folder for downloaded files like it had been written in the name of a new pack.  Why is that different now?

**Comment by GammaC0de** [comment]
Well this depends on the plugin that you used, can you have give an example?

**Comment by GammaC0de** [comment]
No response, closing.
