### ISSUE TITLE
ZippyshareCom not working

### ISSUE THREAD

**Issue by DpunktKpunkt** [pyload/pyload#3020]
Hello,

plugin for Zippyshare (newest version 0.94) doesn't work any more. Log says download was successful, but the dl'd file contains only some garbage data.
Example Zippy link: [http://www39.zippyshare.com/v/3EhLknWu/file.html](http://www39.zippyshare.com/v/3EhLknWu/file.html) (File contains the pyload-Plugin)

Log entries after download: 

>11	24.11.2017 07:41:32	INFO	Download starts: ZippyshareCom.py
12	24.11.2017 07:41:32	WARNING	HOSTER ZippyshareCom[10846]: Plugin may be unstable
13	24.11.2017 07:41:32	INFO	HOSTER ZippyshareCom[10846]: Grabbing link info...
14	24.11.2017 07:41:32	INFO	HOSTER ZippyshareCom[10846]: Link name: ZippyshareCom.py
15	24.11.2017 07:41:32	INFO	HOSTER ZippyshareCom[10846]: Link size: N/D
16	24.11.2017 07:41:32	INFO	HOSTER ZippyshareCom[10846]: Link status: online
17	24.11.2017 07:41:32	INFO	HOSTER ZippyshareCom[10846]: Processing url: http://www39.zippyshare.com/v/3EhLknWu/file.html
18	24.11.2017 07:41:32	INFO	HOSTER ZippyshareCom[10846]: Looking for direct download link...
19	24.11.2017 07:41:32	INFO	HOSTER ZippyshareCom[10846]: Direct download link not found
20	24.11.2017 07:41:32	INFO	HOSTER ZippyshareCom[10846]: Checking for link errors...
21	24.11.2017 07:41:32	INFO	HOSTER ZippyshareCom[10846]: No errors found
22	24.11.2017 07:41:32	INFO	HOSTER ZippyshareCom[10846]: Processing as free download...
23	24.11.2017 07:41:32	WARNING	CAPTCHA ZippyshareCom[10846]: ReCaptcha | Key pattern not found
24	24.11.2017 07:41:32	INFO	HOSTER ZippyshareCom[10846]: Downloading file...
25	24.11.2017 07:41:33	INFO	HOSTER ZippyshareCom[10846]: File saved
26	24.11.2017 07:41:33	INFO	HOSTER ZippyshareCom[10846]: Checking download...
27	24.11.2017 07:41:33	INFO	HOSTER ZippyshareCom[10846]: File is OK
28	24.11.2017 07:41:33	INFO	HOSTER ZippyshareCom[10846]: Checking file (with built-in rules)...
29	24.11.2017 07:41:33	INFO	HOSTER ZippyshareCom[10846]: Checking file (with custom rules)...
30	24.11.2017 07:41:33	INFO	HOSTER ZippyshareCom[10846]: Checking for link errors...
31	24.11.2017 07:41:33	INFO	HOSTER ZippyshareCom[10846]: No errors found
32	24.11.2017 07:41:33	INFO	HOSTER ZippyshareCom[10846]: No errors found
33	24.11.2017 07:41:33	INFO	Download finished: ZippyshareCom.py
34	24.11.2017 07:41:33	INFO	Package finished: Zippyshare Fault

 Dl'd file contains:

> HTTP Status 404 - /[eval]:1%0Aprint(eval(unescape('%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20document%20=%20%7B%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20document.getElementById%20=%20function(x)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(!this.hasOwnProperty(x))%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this[x]%20=%20%7BgetAttribute%20:%20function(x)%20%7B%20return%20this[x]%20%7D%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20this[x]%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0Adocument.getElementById(%22dlbutton%22)[%22href%22]%20=%20%22
... and so on

**Comment by Mister-XY** [comment]
No problem here with zippyshare. all downloads workw fine.

**Comment by DpunktKpunkt** [comment]
You're right - some python file got corrupted here ...
It works like a charme now again :-)
