### ISSUE TITLE
New Hoster: Linkifier.com

### ISSUE THREAD

**Issue by iicaii** [pyload/pyload#3024]
Is there a chance to support linkifier.com?
It's a multihoster so it should be feasible to use the MultiAccount base class. JDownloader support it via `plugins/hoster/LinkifierCom.java`, which should give a good base for conversion into pyload's structure.

**Comment by GammaC0de** [comment]
Can you provide account information? (answer yes or no, don't post it here)

**Comment by iicaii** [comment]
@GammaC0de I am! Gitter? Or rather email?

**Comment by GammaC0de** [comment]
Please set to a temporary password and then send account user and password to either Gitter or to  nitzo2001 at yahoo dot com.

**Comment by iicaii** [comment]
@GammaC0de It's in a Gitter private chat.

**Comment by GammaC0de** [comment]
Done.

Just one note:
LinkifierCom reports that is supports rapidgator.net but it actually fails to download from it so you may contact their support..

**Comment by iicaii** [comment]
Thanks a lot!
Noticed other hosters which are officially supported but not downloadable…
