### ISSUE TITLE
New Multi-Hoster: leech360.com

### ISSUE THREAD

**Issue by sebaro11** [pyload/pyload#3025]
Quite new I think but works really fine with good conditions and massive hoster support.
I can provide account information if needed. :)

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by sebaro11** [comment]
Send over gitter

**Comment by GammaC0de** [comment]
Done,
Congrats for a lifetime license 😀

**Comment by sebaro11** [comment]
Thank you very much for the fast implementation!

> Congrats for a lifetime license 😀
They have Blackfriday/Cybermonday sale ;)
