### ISSUE TITLE
ShareOnlineBiz is not working for Premium

### ISSUE THREAD

**Issue by Tao87-04** [pyload/pyload#3026]
| 25.11.2017 21:09:02 | INFO | HOSTER ShareonlineBiz[1880]: Processing url: http://www.share-online.biz/dl/***************
-- | -- | -- | --
588 | 25.11.2017 21:09:02 | INFO | HOSTER ShareonlineBiz[1880]: Looking for direct download link...
589 | 25.11.2017 21:09:02 | INFO | HOSTER ShareonlineBiz[1881]: Direct download link not found
590 | 25.11.2017 21:09:02 | INFO | HOSTER ShareonlineBiz[1880]: Direct download link not found
591 | 25.11.2017 21:09:02 | INFO | ACCOUNT ShareonlineBiz: Grabbing account info for user `Air*******`...
592 | 25.11.2017 21:09:02 | INFO | HOSTER ShareonlineBiz[1881]: Filesize: 298359 KiB \| Traffic left for user `Air*******`: 90921300 KiB
593 | 25.11.2017 21:09:02 | INFO | HOSTER ShareonlineBiz[1881]: Processing as premium download...
594 | 25.11.2017 21:09:02 | INFO | ACCOUNT ShareonlineBiz: Grabbing account info for user `Air*******`...
595 | 25.11.2017 21:09:02 | INFO | HOSTER ShareonlineBiz[1880]: Processing as free download...
596 | 25.11.2017 21:09:02 | INFO | HOSTER ShareonlineBiz[1880]: Waiting 3 seconds...
597 | 25.11.2017 21:09:03 | INFO | HOSTER ShareonlineBiz[1881]: Downloading file...
598 | 25.11.2017 21:09:03 | ERROR | HOSTER ShareonlineBiz[1881]:
599 | 25.11.2017 21:09:03 | WARNING | HOSTER ShareonlineBiz[1881]: Premium download failed \| IOError 13
600 | 25.11.2017 21:09:03 | INFO | Download restarted: **************** \| Fallback to free processing

**Comment by Mister-XY** [comment]
No Problem here with SO.

**Comment by GammaC0de** [comment]
IOError 13 is "Permission denied".

Check for proper permissions of the download folder.

**Comment by Tao87-04** [comment]
yeah, i have no idea why, but permission was changed.... Thanky and sry
