### ISSUE TITLE
Plugin Issue: OboomCom SSL Error

### ISSUE THREAD

**Issue by sebaro11** [pyload/pyload#3027]
I think the OboomCom plugin is broken because of a SSLv3 handshake error
Plugin Version: 0.46

```
1340 | 26.11.2017 14:21:47 | INFO | ADDON UnSkipOnFail: No duplicates found
-- | -- | -- | --
1339 | 26.11.2017 14:21:47 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: B1TQ81SQ (pid:2)
1338 | 26.11.2017 14:21:47 | ERROR | pycurl error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
1337 | 26.11.2017 14:21:47 | INFO | HOSTER OboomCom[2]: Processing url: https://oboom.com/someurl
1336 | 26.11.2017 14:21:47 | INFO | HOSTER OboomCom[2]: Link status: starte
1335 | 26.11.2017 14:21:47 | INFO | HOSTER OboomCom[2]: Link size: N/D
1334 | 26.11.2017 14:21:47 | INFO | HOSTER OboomCom[2]: Link name: B1TQ81SQ
1333 | 26.11.2017 14:21:47 | INFO | HOSTER OboomCom[2]: Grabbing link info...
1332 | 26.11.2017 14:21:47 | WARNING | HOSTER OboomCom[2]: Plugin may be unstable

```

**Comment by GammaC0de** [comment]
This is not pyload's issue, 
you should update `curl` / `libcurl-dev` / `pycurl` / `openssl` packages to the latest version.

**Comment by sebaro11** [comment]
Oh ok, I thought they get auto updated through pyload UpdateManager. Seems I have to search if these packages are available for windows.

**Comment by GammaC0de** [comment]
Tested on windows 7.

**Comment by sebaro11** [comment]
I am running pyhton 2.7.14 and have pycurl 7.19.5.3 for python 2.7 installed.
pycurl path is "C:\Python27\Lib\site-packages\pycurl-7.43.0-py2.7.egg-info" and "pycurl.pyd" is in "C:\Python27\Lib\site-packages\" folder

` Verzeichnis von C:\Python27\Lib\site-packages

27.11.2017  15:58    <DIR>          .
27.11.2017  15:58    <DIR>          ..
26.11.2017  17:27    <DIR>          asn1crypto
26.11.2017  17:27    <DIR>          asn1crypto-0.23.0.dist-info
26.11.2017  17:27    <DIR>          cffi
26.11.2017  17:27    <DIR>          cffi-1.11.2.dist-info
26.11.2017  17:27    <DIR>          cryptography
26.11.2017  17:27    <DIR>          cryptography-2.1.3.dist-info
26.11.2017  17:06    <DIR>          curl
26.11.2017  17:01               126 easy_install.py
26.11.2017  17:01               347 easy_install.pyc
26.11.2017  17:27    <DIR>          enum
26.11.2017  17:27    <DIR>          enum34-1.1.6.dist-info
26.11.2017  17:27    <DIR>          idna
26.11.2017  17:27    <DIR>          idna-2.6.dist-info
26.11.2017  17:27    <DIR>          ipaddress-1.0.18.dist-info
26.11.2017  17:27            80.156 ipaddress.py
26.11.2017  17:27            81.306 ipaddress.pyc
05.11.2015  06:56           312.320 libcurl.dll
26.11.2017  17:27    <DIR>          OpenSSL
26.11.2017  17:01    <DIR>          pip
26.11.2017  17:01    <DIR>          pip-9.0.1.dist-info
26.11.2017  17:01    <DIR>          pkg_resources
26.11.2017  17:27    <DIR>          pycparser
26.11.2017  17:27    <DIR>          pycparser-2.18-py2.7.egg-info
05.11.2015  06:57             1.032 pycurl-7.19.5.3-py2.7.egg-info
26.11.2017  17:06    <DIR>          pycurl-7.43.0-py2.7.egg-info
05.11.2015  06:57            77.824 pycurl.pyd
26.11.2017  17:27    <DIR>          pyOpenSSL-17.4.0.dist-info
13.02.2017  22:38               121 README.txt
26.11.2017  17:01    <DIR>          setuptools
26.11.2017  17:01    <DIR>          setuptools-28.8.0.dist-info
26.11.2017  17:27    <DIR>          six-1.11.0.dist-info
26.11.2017  17:27            30.888 six.py
26.11.2017  17:27            32.948 six.pyc
05.11.2015  06:56            67.072 zlib1.dll
26.11.2017  17:27           127.488 _cffi_backend.pyd
              12 Datei(en),        811.628 Bytes
              25 Verzeichnis(se), 3.356.798.828.544 Bytes frei

C:\Windows\system32>`

**Comment by GammaC0de** [comment]
What is the output of this:
```batch
C:\> python

>>> import pycurl
>>> pycurl.version
```

**Comment by sebaro11** [comment]
```
>>> import pycurl
>>> pycurl.version
'PycURL/7.19.5.3 libcurl/7.45.0 WinSSL zlib/1.2.8'
>>>
```

**Comment by GammaC0de** [comment]
What OS are you using?

**Comment by sebaro11** [comment]
Windows Server 2012 R2 Standard 64 Bit

**Comment by GammaC0de** [comment]
Try running pyload as administrator, maybe it would help.

**Comment by sebaro11** [comment]
Yes tried it right now and the error is still occurring.
Also tried to run pyload via Admin CMD.exe but it made no difference :/

**Comment by GammaC0de** [comment]
1. Try on Win7
2. Try PyCurl 7.43.0:
- https://bintray.com/pycurl/pycurl/download_file?file_path=pycurl-7.43.0.win32-py2.7.exe (for 32bits python)
- https://bintray.com/pycurl/pycurl/download_file?file_path=pycurl-7.43.0.win-amd64-py2.7.exe (for 64bits python)

**Comment by sebaro11** [comment]
Installing PyCurl 7.43.0 made no difference. 
I think that we cannot fix that problem and I have to take it as it is :(

**Comment by GammaC0de** [comment]
> I think that we cannot fix that problem and I have to take it as it is :(
Or you can switch to other OS (can you try on win7 or even Linux?)
Is server 2012 a must?

**Comment by sebaro11** [comment]
Windows 2012 is a must, because everything else I am using is already set up and running.
