### ISSUE TITLE
Warning after extraction

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#3028]
Hello, for what is this info after extraction any archive?

6051 | 26.11.2017 16:43:01 | WARNING | ADDON ExtractArchive: Not deleting pack folder /mnt/md0/Download/..., folder not empty

make this warning any sense?

**Comment by GammaC0de** [comment]
This happens when:
1. you have set the extraction directory to another directory.
2. the package you have downloaded includes also other types of files beside archives.

**Comment by Mister-XY** [comment]
1. No, i have set the directory not to another directory
2. the packages i have downloaded have only the files that i have downloaded.

**Comment by GammaC0de** [comment]
Please send me the problematic URL via Gitter.

**Comment by Mister-XY** [comment]
problematic URl? I have this with every package.

**Comment by GammaC0de** [comment]
So send one please.

**Comment by Mister-XY** [comment]
I have send you URL
