### ISSUE TITLE
The links 1fichier.com no longer work.

### ISSUE THREAD

**Issue by aldoman62** [pyload/pyload#3029]
Hello,

I have a premium account at 1fichier.com []((https://1fichier.com).)

Pyload can not download anymore. I think the plug-in is no longer good.

Thank you.

Here is the information from the newspaper:

383 | 26.11.2017 23:42:19 | INFO | Added package test 1fichier containing 1 links
-- | -- | -- | --
384 | 26.11.2017 23:42:19 | INFO | Download starts: https://1fichier.com/?m4tglsek8z
385 | 26.11.2017 23:42:19 | WARNING | HOSTER OneFichierCom[84]: Plugin may be unstable
386 | 26.11.2017 23:42:19 | INFO | ACCOUNT OneFichierCom: Relogin user `yom*******`...
387 | 26.11.2017 23:42:20 | INFO | ACCOUNT OneFichierCom: Grabbing account info for user `yom*******`...
388 | 26.11.2017 23:42:20 | INFO | HOSTER OneFichierCom[84]: Grabbing link info...
389 | 26.11.2017 23:42:21 | INFO | HOSTER OneFichierCom[84]: Link name: ?m4tglsek8z
390 | 26.11.2017 23:42:21 | INFO | HOSTER OneFichierCom[84]: Link size: N/D
391 | 26.11.2017 23:42:21 | INFO | HOSTER OneFichierCom[84]: Link status: demarrage
392 | 26.11.2017 23:42:21 | INFO | HOSTER OneFichierCom[84]: Processing url: https://1fichier.com/?m4tglsek8z
393 | 26.11.2017 23:42:21 | INFO | HOSTER OneFichierCom[84]: Looking for direct download link...
394 | 26.11.2017 23:42:22 | INFO | HOSTER OneFichierCom[84]: Direct download link not found
395 | 26.11.2017 23:42:22 | INFO | HOSTER OneFichierCom[84]: Checking for link errors...
396 | 26.11.2017 23:42:22 | INFO | HOSTER OneFichierCom[84]: No errors found
397 | 26.11.2017 23:42:22 | INFO | HOSTER OneFichierCom[84]: Grabbing link info...
398 | 26.11.2017 23:42:23 | INFO | HOSTER OneFichierCom[84]: Link name: Les.As.2.mkv.rar
399 | 26.11.2017 23:42:23 | INFO | HOSTER OneFichierCom[84]: Link size: 991.65 MiB (1039820390 bytes)
400 | 26.11.2017 23:42:23 | INFO | HOSTER OneFichierCom[84]: Link status: en ligne
401 | 26.11.2017 23:42:23 | INFO | HOSTER OneFichierCom[84]: Processing as premium download...
402 | 26.11.2017 23:42:23 | INFO | HOSTER OneFichierCom[84]: File saved
403 | 26.11.2017 23:42:23 | INFO | HOSTER OneFichierCom[84]: Checking download...
404 | 26.11.2017 23:42:23 | INFO | HOSTER OneFichierCom[84]: File is OK
405 | 26.11.2017 23:42:23 | INFO | HOSTER OneFichierCom[84]: Checking file (with built-in rules)...
406 | 26.11.2017 23:42:23 | WARNING | HOSTER OneFichierCom[84]: Check result: Html file \| Waiting 1 minute and retry
407 | 26.11.2017 23:42:23 | INFO | HOSTER OneFichierCom[84]: Waiting 1 minutes...
408 | 26.11.2017 23:42:37 | ERROR | ADDON AntiStandby: Error performing periodical task \| 'utf8' codec can't decode byte 0x82 in position 146: invalid start byte
-- | -- | -- | --
409 | 26.11.2017 23:43:04 | ERROR | ADDON AntiStandby: Error performing periodical task \| 'utf8' codec can't decode byte 0x82 in position 146: invalid start byte
410 | 26.11.2017 23:43:26 | INFO | Download restarted: Les.As.2.mkv.rar \| Html file
411 | 26.11.2017 23:43:26 | INFO | Download starts: Les.As.2.mkv.rar
412 | 26.11.2017 23:43:26 | WARNING | HOSTER OneFichierCom[84]: Plugin may be unstable
413 | 26.11.2017 23:43:26 | INFO | ACCOUNT OneFichierCom: Grabbing account info for user `yom*******`...
414 | 26.11.2017 23:43:26 | INFO | HOSTER OneFichierCom[84]: Grabbing link info...
415 | 26.11.2017 23:43:27 | INFO | HOSTER OneFichierCom[84]: Link name: ?m4tglsek8z
416 | 26.11.2017 23:43:27 | INFO | HOSTER OneFichierCom[84]: Link size: N/D
417 | 26.11.2017 23:43:27 | INFO | HOSTER OneFichierCom[84]: Link status: demarrage
418 | 26.11.2017 23:43:27 | INFO | HOSTER OneFichierCom[84]: Processing url: https://1fichier.com/?m4tglsek8z
419 | 26.11.2017 23:43:27 | INFO | HOSTER OneFichierCom[84]: Looking for direct download link...
420 | 26.11.2017 23:43:28 | INFO | HOSTER OneFichierCom[84]: Direct download link not found
421 | 26.11.2017 23:43:28 | INFO | HOSTER OneFichierCom[84]: Checking for link errors...
422 | 26.11.2017 23:43:28 | INFO | HOSTER OneFichierCom[84]: No errors found
423 | 26.11.2017 23:43:28 | INFO | HOSTER OneFichierCom[84]: Grabbing link info...
424 | 26.11.2017 23:43:29 | INFO | HOSTER OneFichierCom[84]: Link name: Les.As.2.mkv.rar
425 | 26.11.2017 23:43:29 | INFO | HOSTER OneFichierCom[84]: Link size: 991.65 MiB (1039820390 bytes)
426 | 26.11.2017 23:43:29 | INFO | HOSTER OneFichierCom[84]: Link status: en ligne
427 | 26.11.2017 23:43:29 | INFO | HOSTER OneFichierCom[84]: Processing as premium download...
-- | -- | -- | --
428 | 26.11.2017 23:43:30 | ERROR | ADDON AntiStandby: Error performing periodical task \| 'utf8' codec can't decode byte 0x82 in position 146: invalid start byte
429 | 26.11.2017 23:43:30 | INFO | HOSTER OneFichierCom[84]: File saved
430 | 26.11.2017 23:43:30 | INFO | HOSTER OneFichierCom[84]: Checking download...
431 | 26.11.2017 23:43:30 | INFO | HOSTER OneFichierCom[84]: File is OK
432 | 26.11.2017 23:43:30 | INFO | HOSTER OneFichierCom[84]: Checking file (with built-in rules)...
433 | 26.11.2017 23:43:30 | WARNING | HOSTER OneFichierCom[84]: Check result: Html file \| Waiting 1 minute and retry
434 | 26.11.2017 23:43:30 | INFO | HOSTER OneFichierCom[84]: Waiting 1 minutes...
435 | 26.11.2017 23:43:56 | ERROR | ADDON AntiStandby: Error performing periodical task \| 'utf8' codec can't decode byte 0x82 in position 146: invalid start byte
436 | 26.11.2017 23:44:22 | ERROR | ADDON AntiStandby: Error performing periodical task \| 'utf8' codec can't decode byte 0x82 in position 146: invalid start byte
437 | 26.11.2017 23:44:32 | INFO | Download restarted: Les.As.2.mkv.rar (2) \| Html file
438 | 26.11.2017 23:44:32 | INFO | Download starts: Les.As.2.mkv.rar (2)
439 | 26.11.2017 23:44:32 | WARNING | HOSTER OneFichierCom[84]: Plugin may be unstable
440 | 26.11.2017 23:44:32 | INFO | ACCOUNT OneFichierCom: Grabbing account info for user `yom*******`...
441 | 26.11.2017 23:44:33 | INFO | HOSTER OneFichierCom[84]: Grabbing link info...
442 | 26.11.2017 23:44:34 | INFO | HOSTER OneFichierCom[84]: Link name: ?m4tglsek8z
443 | 26.11.2017 23:44:34 | INFO | HOSTER OneFichierCom[84]: Link size: N/D
444 | 26.11.2017 23:44:34 | INFO | HOSTER OneFichierCom[84]: Link status: demarrage
445 | 26.11.2017 23:44:34 | INFO | HOSTER OneFichierCom[84]: Processing url: https://1fichier.com/?m4tglsek8z
446 | 26.11.2017 23:44:34 | INFO | HOSTER OneFichierCom[84]: Looking for direct download link...
447 | 26.11.2017 23:44:34 | INFO | HOSTER OneFichierCom[84]: Direct download link not found
448 | 26.11.2017 23:44:35 | INFO | HOSTER OneFichierCom[84]: Checking for link errors...
449 | 26.11.2017 23:44:35 | INFO | HOSTER OneFichierCom[84]: No errors found
450 | 26.11.2017 23:44:35 | INFO | HOSTER OneFichierCom[84]: Grabbing link info...
451 | 26.11.2017 23:44:35 | INFO | HOSTER OneFichierCom[84]: Link name: Les.As.2.mkv.rar
452 | 26.11.2017 23:44:35 | INFO | HOSTER OneFichierCom[84]: Link size: 991.65 MiB (1039820390 bytes)
453 | 26.11.2017 23:44:35 | INFO | HOSTER OneFichierCom[84]: Link status: en ligne
454 | 26.11.2017 23:44:35 | INFO | HOSTER OneFichierCom[84]: Processing as premium download...
455 | 26.11.2017 23:44:36 | INFO | HOSTER OneFichierCom[84]: File saved
456 | 26.11.2017 23:44:36 | INFO | HOSTER OneFichierCom[84]: Checking download...
457 | 26.11.2017 23:44:36 | INFO | HOSTER OneFichierCom[84]: File is OK
458 | 26.11.2017 23:44:36 | INFO | HOSTER OneFichierCom[84]: Checking file (with built-in rules)...
459 | 26.11.2017 23:44:36 | WARNING | HOSTER OneFichierCom[84]: Check result: Html file \| Waiting 1 minute and retry
460 | 26.11.2017 23:44:36 | INFO | HOSTER OneFichierCom[84]: Waiting 1 minutes...

**Comment by GammaC0de** [comment]
Free download seens to work fine (I started the download but did not wait for it to finish)

Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by aldoman62** [comment]
Mail sent.

**Comment by GammaC0de** [comment]
https://1fichier.com/?m4tglsek8z downloaded fine with premium also, 
maybe you have downloaded too much yesterday?

Can you retry this link?

**Comment by aldoman62** [comment]
Thank-you for your prompt response.
I use Pyload on an ASUSTOR nas.
I re-installed Pyload. The download works.

But I have another problem.Once download, the link file (https://1file.com/?m4tglsek8z) is named:
?m4tglsek8z

It should be named: Les.As.2.mkv.rar

I have to rename the file manually.

**Comment by GammaC0de** [comment]
How exactly did you installed pyload?

**Comment by aldoman62** [comment]
It is installed from the central app asustor.

William Lin worked on it.

**Comment by GammaC0de** [comment]
I don't know what is the status of pyload from the central app store, it's not an official package.

Please note about UpdateManager https://github.com/pyload/pyload/issues/2994

**Comment by luzik** [comment]
Free Account not working

> 04.12.2017 12:37:48	INFO	Download starts: https://1fichier.com/?x2gldt2qy9,Kingsman.The.Golden.Circle.720-Bonzai82.part8.rar,,126203272
> 61	04.12.2017 12:37:48	WARNING	HOSTER OneFichierCom[935]: Plugin may be unstable
> 62	04.12.2017 12:37:48	INFO	ACCOUNT OneFichierCom: Grabbing account info for user `luz*******`...
> 63	04.12.2017 12:37:48	INFO	HOSTER OneFichierCom[935]: Grabbing link info...
> 64	04.12.2017 12:37:49	INFO	HOSTER OneFichierCom[935]: Link name: Kingsman.The.Golden.Circle.720-Bonzai82.part8.rar
> 65	04.12.2017 12:37:49	INFO	HOSTER OneFichierCom[935]: Link size: 120.36 MiB (126206607 bytes)
> 66	04.12.2017 12:37:49	INFO	HOSTER OneFichierCom[935]: Link status: online
> 67	04.12.2017 12:37:49	INFO	HOSTER OneFichierCom[935]: Processing url: https://1fichier.com/?x2gldt2qy9,Kingsman.The.Golden.Circle.720-Bonzai82.part8.rar,,126203272
> 68	04.12.2017 12:37:49	INFO	HOSTER OneFichierCom[935]: Looking for direct download link...
> 69	04.12.2017 12:37:50	INFO	HOSTER OneFichierCom[935]: Direct download link not found
> 70	04.12.2017 12:37:50	INFO	HOSTER OneFichierCom[935]: Checking for link errors...
> 71	04.12.2017 12:37:50	INFO	HOSTER OneFichierCom[935]: No errors found
> 72	04.12.2017 12:37:50	INFO	HOSTER OneFichierCom[935]: Processing as free download...
> 73	04.12.2017 12:37:51	INFO	HOSTER OneFichierCom[935]: Checking for link errors...
> 74	04.12.2017 12:37:51	INFO	HOSTER OneFichierCom[935]: No errors found
> 75	04.12.2017 12:37:51	INFO	HOSTER OneFichierCom[935]: Checking download...
> 76	04.12.2017 12:37:51	WARNING	HOSTER OneFichierCom[935]: Free download failed | Parse error: No file downloaded | Plugin may be out of date
> 77	04.12.2017 12:37:51	WARNING	Download failed: Kingsman.The.Golden.Circle.720-Bonzai82.part8.rar | Parse error: No file downloaded | Plugin may be out of date

**Comment by GammaC0de** [comment]
Tested with free account and it works.

**Comment by luzik** [comment]
Did you checked 'Use premium account if available:' ?

I believe I am  using:

Account:
__version__ = "0.24"

Hoster:
__version__ = "1.10"

**Comment by GammaC0de** [comment]
Oh, by free account you mean with an account?
I tried without an account..

**Comment by luzik** [comment]
Yeah ..that's they call it :-) sorry for using confusing name. To be clear - registered, but not premium

**Comment by luzik** [comment]
Maybe wrong place to ask, but it is possible pyload to support this registered but no premium account on 1fitcher ..and maybe others hosters ? Downloading as registered user (without premium account) give you more speed and you can download bigger files from 1fitcher

**Comment by GammaC0de** [comment]
@luzik This is what https://github.com/pyload/pyload/commit/f8e83dd46b31be4bde832dc1254d1377ea6b5d92 was supposed to fix.
I even tested is whit a registered free account.

There is a downside of using a registered free account: you cannot change your IP (reconnect feature) to fool 1fischer.

**Comment by luzik** [comment]
Oh, I assumed that fall back to free starts a new http session. I was wrong yes ?

**Comment by GammaC0de** [comment]
It still says "free" download but it uses the account (which is indeed free)

**Comment by luzik** [comment]
Thanks for the clarification.

**Comment by luzik** [comment]
Now in that 'registered but not premium' state it starts to downloads two files at same time, and one is always fail to downloads

> 996	07.12.2017 11:26:54	INFO	HOSTER OneFichierCom[1003]: File saved
> 997	07.12.2017 11:26:54	INFO	HOSTER OneFichierCom[1003]: Checking download...
> 998	07.12.2017 11:26:54	INFO	HOSTER OneFichierCom[1003]: File is OK
> 999	07.12.2017 11:26:54	INFO	HOSTER OneFichierCom[1003]: Checking file (with built-in rules)...
> 1000	07.12.2017 11:26:54	INFO	HOSTER OneFichierCom[1003]: Checking file (with custom rules)...
> 1001	07.12.2017 11:26:54	INFO	HOSTER OneFichierCom[1003]: Checking for link errors...
> 1002	07.12.2017 11:26:54	INFO	HOSTER OneFichierCom[1003]: No errors found
> 1003	07.12.2017 11:26:54	INFO	HOSTER OneFichierCom[1003]: No errors found
> 1004	07.12.2017 11:26:54	INFO	Download finished: Brigsby.Bear.720-Bonzai82.part4.rar
> 1005	07.12.2017 11:26:56	INFO	Download starts: https://1fichier.com/?etvgvz0jge,Spider-Man.Homecoming.720-Bonzai82.part1.rar,,1047527424
> 1006	07.12.2017 11:26:56	WARNING	HOSTER OneFichierCom[1005]: Plugin may be unstable
> 1007	07.12.2017 11:26:56	INFO	ACCOUNT OneFichierCom: Relogin user `luz*******`...
> 1008	07.12.2017 11:26:56	INFO	ACCOUNT OneFichierCom: Grabbing account info for user `luz*******`...
> 1009	07.12.2017 11:26:57	INFO	HOSTER OneFichierCom[1005]: Grabbing link info...
> 1010	07.12.2017 11:26:58	INFO	Download starts: https://1fichier.com/?rbgplaxaif,Spider-Man.Homecoming.720-Bonzai82.part2.rar,,1047527424
> 1011	07.12.2017 11:26:58	WARNING	HOSTER OneFichierCom[1006]: Plugin may be unstable
> 1012	07.12.2017 11:26:58	INFO	ACCOUNT OneFichierCom: Grabbing account info for user `luz*******`...
> 1013	07.12.2017 11:26:58	INFO	HOSTER OneFichierCom[1006]: Grabbing link info...
> 1014	07.12.2017 11:26:58	INFO	HOSTER OneFichierCom[1005]: Link name: Spider-Man.Homecoming.720-Bonzai82.part1.rar
> 1015	07.12.2017 11:26:58	INFO	HOSTER OneFichierCom[1005]: Link size: 999.00 MiB (1047527424 bytes)
> 1016	07.12.2017 11:26:58	INFO	HOSTER OneFichierCom[1005]: Link status: online
> 1017	07.12.2017 11:26:58	INFO	HOSTER OneFichierCom[1005]: Processing url: https://1fichier.com/?etvgvz0jge,Spider-Man.Homecoming.720-Bonzai82.part1.rar,,1047527424
> 1018	07.12.2017 11:26:58	INFO	HOSTER OneFichierCom[1005]: Looking for direct download link...
> 1019	07.12.2017 11:26:59	INFO	HOSTER OneFichierCom[1005]: Direct download link not found
> 1020	07.12.2017 11:26:59	INFO	HOSTER OneFichierCom[1005]: Checking for link errors...
> 1021	07.12.2017 11:26:59	INFO	HOSTER OneFichierCom[1005]: Waiting 1 hours...
> 1022	07.12.2017 11:26:59	INFO	HOSTER OneFichierCom[1006]: Link name: Spider-Man.Homecoming.720-Bonzai82.part2.rar
> 1023	07.12.2017 11:26:59	INFO	HOSTER OneFichierCom[1006]: Link size: 999.00 MiB (1047527424 bytes)
> 1024	07.12.2017 11:26:59	INFO	HOSTER OneFichierCom[1006]: Link status: online
> 1025	07.12.2017 11:26:59	INFO	HOSTER OneFichierCom[1006]: Processing url: https://1fichier.com/?rbgplaxaif,Spider-Man.Homecoming.720-Bonzai82.part2.rar,,1047527424
> 1026	07.12.2017 11:26:59	INFO	HOSTER OneFichierCom[1006]: Looking for direct download link...
> 1027	07.12.2017 11:27:00	INFO	HOSTER OneFichierCom[1006]: Direct download link not found
> 1028	07.12.2017 11:27:00	INFO	HOSTER OneFichierCom[1006]: Checking for link errors...
> 1029	07.12.2017 11:27:00	INFO	HOSTER OneFichierCom[1006]: Waiting 1 hours...
