### ISSUE TITLE
[MegaCoNz] Download fails instantly

### ISSUE THREAD

**Issue by LillyWho** [pyload/pyload#3030]
I've tried to download from mega (after hitting the 6 hours limit, but I've reset my IP to get a new one and it still doesn't work)

`Nov 27 01:58:32 raspi python[11061]: 27.11.2017 01:58:32 WARNING   HOSTER MegaCoNz[12]: Plugin may be unstable

Nov 27 01:58:32 raspi python[11061]: 27.11.2017 01:58:32 INFO      HOSTER MegaCoNz[12]: Grabbing link info...

Nov 27 01:58:32 raspi python[11061]: 27.11.2017 01:58:32 INFO      HOSTER MegaCoNz[12]: Link name: #!USpzmKBQ!3Vly4QmyqPwrZ-F8saXEwpFH2IysmtQ7JWAc9cylUes

Nov 27 01:58:32 raspi python[11061]: 27.11.2017 01:58:32 INFO      HOSTER MegaCoNz[12]: Link size: 4.90 GiB (5261754368 bytes)

Nov 27 01:58:32 raspi python[11061]: 27.11.2017 01:58:32 INFO      HOSTER MegaCoNz[12]: Link status: starte
Nov 27 01:58:32 raspi python[11061]: 27.11.2017 01:58:32 INFO      HOSTER MegaCoNz[12]: Processing url: https://mega.nz/#!USpzmKBQ!3Vly4QmyqPwrZ-F8saXEwpFH2IysmtQ7JWAc9cylUes

Nov 27 01:58:33 raspi python[11061]: 27.11.2017 01:58:33 WARNING   HOSTER MegaCoNz[12]: Free download failed | downloade
Nov 27 01:58:33 raspi python[11061]: 27.11.2017 01:58:33 WARNING   Download failed: TheS4v136102.part3.rar.crypted | downloade

Nov 27 01:58:33 raspi python[11061]: 27.11.2017 01:58:33 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: TheS4v136102.part3.rar.crypted (pid:3)

Nov 27 01:58:33 raspi python[11061]: 27.11.2017 01:58:33 INFO      ADDON UnSkipOnFail: No duplicates found`

**Comment by GammaC0de** [comment]
Try download with an account and see if it helps.

**Comment by Alexandroid99** [comment]
- Nov 27 17:03:35 raspi python[15517]: 27.11.2017 17:03:35 INFO      ACCOUNT MegaCoNz: Grabbing account info for user `ale*******`...
- Nov 27 17:03:35 raspi python[15517]: 27.11.2017 17:03:35 INFO      HOSTER MegaCoNz[11]: Grabbing link info...
-Nov 27 17:03:35 raspi python[15517]: 27.11.2017 17:03:35 INFO      HOSTER MegaCoNz[11]: Link name: #!BWIBRD7T!EBTTAZQFYgqu1AVNyFnx__ulju4ceBmiFWFTdtnYmfU
-Nov 27 17:03:35 raspi python[15517]: 27.11.2017 17:03:35 INFO      HOSTER MegaCoNz[11]: Link size: 4.90 GiB (5261754368 bytes)
-Nov 27 17:03:35 raspi python[15517]: 27.11.2017 17:03:35 INFO      HOSTER MegaCoNz[11]: Link status: starte
- Nov 27 17:03:35 raspi python[15517]: 27.11.2017 17:03:35 INFO      HOSTER MegaCoNz[11]: Processing url: https://mega.nz/#!BWIBRD7T!EBTTAZQFYgqu1AVNyFnx__ulju4ceBmiFWFTdtnYmfU
- Nov 27 17:03:36 raspi python[15517]: 27.11.2017 17:03:36 WARNING   HOSTER MegaCoNz[11]: Free download failed | downloade
- Nov 27 17:03:36 raspi python[15517]: 27.11.2017 17:03:36 WARNING   Download failed: TheS4v136102.part4.rar.crypted | downloade
- Nov 27 17:03:36 raspi python[15517]: 27.11.2017 17:03:36 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: TheS4v136102.part4.rar.crypted (pid:3)
- Nov 27 17:03:36 raspi python[15517]: 27.11.2017 17:03:36 INFO      ADDON UnSkipOnFail: No duplicates found

Even if it had worked, downloading without an account should be possible without issues

**Comment by GammaC0de** [comment]
Successfully tested with an account.
Is this a new install? How exactly did you installed pyload?

>Even if it had worked, downloading without an account should be possible without issues

Mega imposes restrictions based on the file size and the amount you have already downloaded, I have no control of this.

**Comment by Alexandroid99** [comment]
It's a fresh install by the tutorial step by step on a Raspi 2

> Mega imposes restrictions based on the file size and the amount you have already downloaded, I have no control of this.
Megadownloader is able to download at least one file completely and currently even bypasses the data cap if you run your downloads simultaneously and make sure the connection isn't interrupted

**Comment by GammaC0de** [comment]
What is the homepage for Megadownloader ? Is it open source?

Download of https://mega.nz/#!BWIBRD7T!EBTTAZQFYgqu1AVNyFnx__ulju4ceBmiFWFTdtnYmfU finished successfully.

**Comment by GammaC0de** [comment]
Are you sure about the bypass?
https://www.reddit.com/r/megalinks/comments/6f0z7h/meta_megadownloader_and_megatools_are_no_longer/

**Comment by Alexandroid99** [comment]
Yea it's not written anywhere officially, but for me it always works as long as the connection follows through completely. Sometimes it does catch one or two files of the bundle, but the rest succeeds. Tried it with multiple DSL connections and it definitely works.

**Comment by GammaC0de** [comment]
Are you able to download lets say 10 gigs file without resuming the download and switching IP address?

**Comment by Alexandroid99** [comment]
4 x 4.09GB simultaneously, successfully if the connection isn't dropped or the bandwidth for a different file doesn't drop to 0kb/s

**Comment by Alexandroid99** [comment]
Seems like the login is also failing due to wrong server address:

884	29.11.2017 15:28:37	ERROR	ACCOUNT MegaCoNz: Could not login user `ale*******` | (6, 'Could not resolve host: eu.api.mega.co.nz')

**Comment by GammaC0de** [comment]
> 6, 'Could not resolve host: eu.api.mega.co.nz

This indicates DNS issues, try `ping eu.api.mega.co.nz` and see if you get a reply.

**Comment by Velociraptor85** [comment]
@Alexandroid99 any luck in testing out the dns?

**Comment by GammaC0de** [comment]
Can you ping to eu.api.mega.co.nz?

**Comment by Alexandroid99** [comment]
Well, on my PC (which has the same DNS settings, getting its DNS info from the router's server which is configured to use OpenDNS) it works, on the Raspi it refuses to resolve the name when using pyload. A normal ping is fine.

**Comment by GammaC0de** [comment]
Well, I had this kind of problem too and it turned out to be a pycurl issue (although on windows).
The solution for me was to downgrade to pycurl v7.19.5.3

**Comment by koroki** [comment]
Same here. The error appears today in the afternoon. In the morning, all was ok.  There are no update of Mega plugin. Also, no update of pycurl, that I use pycurl-7.19.5.1

**Comment by GammaC0de** [comment]
> Same here. The error appears today in the afternoon

By error you mean:
> 6, 'Could not resolve host: eu.api.mega.co.nz

??

**Comment by alesnav** [comment]
In my case it does not show a clear error message. It simply fails:

```
04.02.2018 18:57:42 INFO      ACCOUNT MegaCoNz: Adding user `*******`...
04.02.2018 18:57:42 INFO      ACCOUNT MegaCoNz: Login user `*******`...
04.02.2018 18:57:43 INFO      ACCOUNT MegaCoNz: Grabbing account info for user `*******`...
04.02.2018 18:57:58 INFO      Download starts: *****.avi.crypted
04.02.2018 18:57:58 WARNING   HOSTER MegaCoNz[1]: Plugin may be unstable
04.02.2018 18:57:58 INFO      ACCOUNT MegaCoNz: Grabbing account info for user `*******`...
04.02.2018 18:57:58 INFO      HOSTER MegaCoNz[1]: Grabbing link info...
04.02.2018 18:57:58 INFO      HOSTER MegaCoNz[1]: Link name: #!5VxA2ZyY!0dKypxzUzrdDLujGRNuR7HBfNHtmoy3PWlGRyDNsKns
04.02.2018 18:57:58 INFO      HOSTER MegaCoNz[1]: Link size: 1.37 GiB (1467953152 bytes)
04.02.2018 18:57:58 INFO      HOSTER MegaCoNz[1]: Link status: comenzando
04.02.2018 18:58:04 INFO      HOSTER MegaCoNz[1]: Processing url: https://mega.nz/#!5VxA2ZyY!0dKypxzUzrdDLujGRNuR7HBfNHtmoy3PWlGRyDNsKns
04.02.2018 18:58:08 WARNING   HOSTER MegaCoNz[1]: Free download failed | descargando
04.02.2018 18:58:08 WARNING   Download failed: *****.avi.crypted | descargando
04.02.2018 18:58:08 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: *****.avi.crypted (pid:1)
04.02.2018 18:58:08 INFO      ADDON UnSkipOnFail: No duplicates found
```

NOTE: link name is shown for testing purposes, if needed, but I masked the filename and username from logs :)
