### ISSUE TITLE
[Feature request] Offer not to download hoster plugins for porn sites during setup

### ISSUE THREAD

**Issue by Alexandroid99** [pyload/pyload#3031]
Or why not ask upfront what plugins to install when running first time setup? Would make the overlong list way shorter. The endlessly long list that makes me scroll down the page on the web gui just to select from the dropdown menu is annoying.
Should give people's SO's a little rest when glancing over their partner's shoulder.

**Comment by GammaC0de** [comment]
So to be clear, the problem is the porn sites or the length of the plugin list?

**Comment by Alexandroid99** [comment]
Both, the length of the site / lack of scrolling only the list rather than the full page was an afterthought

**Comment by GammaC0de** [comment]
About the length, there is a solution I have in mind I hope to implement.

What web theme are you using?

**Comment by Alexandroid99** [comment]
Theme? I didn't know there was a theme. I just set it up and used it for a bit.

**Comment by GammaC0de** [comment]
Look in https://github.com/OzzieIsaacs/pyload-NextTheme and https://github.com/xunil75/PyPlex, there are instruction there..

**Comment by GammaC0de** [comment]
Now pyplex web-theme is included in pyload and has a plugin search feature, use it.
