### ISSUE TITLE
Pyload 0.49 on QNAP (QTS4.2.6) reports error w/ latest UpdateManager.py (end Oct'17)

### ISSUE THREAD

**Issue by iceman64128** [pyload/pyload#3036]
Since 2 weeks I try to get pyload on my QNAP back running again. Since the standard installation via QTS applications does not work, I did intense testing of various solutions and now I got stuck.
Pyload "4.9" (= 0.49) has been installed via QTS Applications - only the UpdateManager.py file has been replaced with the most current version available here.

Log is reporting:
"ERROR | Error importing UpdateManager: No module named Addon"

And due to this reason the freshly installed Pyload does not update anything.

What is the problem, what should I change?

**Comment by GammaC0de** [comment]
>"ERROR | Error importing UpdateManager: No module named Addon"

This means that the UpdateManager file you used is incompatible with the pyload version you have installed.

I suggest you download the latest stable git from https://github.com/pyload/pyload/archive/stable.zip which already include the current UpdateManager  and install it.

**Comment by iceman64128** [comment]
Understand, but is the GitHub version compatible with QNAP?

**Comment by GammaC0de** [comment]
>is the GitHub version compatible with QNAP?

What do you mean by that? 
Is there anything different with the standard version and the QNAP version?

pyload is written in pure python, if you have python (and some dependencies like pycurl) installed it should run

**Comment by iceman64128** [comment]
I did not find any up-to-date installation guide on how to do that. so I am kinda stuck... I think, I just need to overcome, one update sequence and then all should be fine. But since the old server is offline, I am not able to migrate to the latest version... :((

**Comment by GammaC0de** [comment]
If you really want UpdateManager  that works with your version use this one: https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/830cb0161b416a5328e32516067608cd2cfdd031/UpdateManager.py but using the latest git is better because it includes some bugfixes that your version don't.

**Comment by iceman64128** [comment]
WOW - it works! And now it also updates the UpdateManager.py to V1.20. 

THANK YOU SO MUCH!!!

**Comment by GammaC0de** [comment]
👍 
Closing :)
