### ISSUE TITLE
Trubobit free not working...

### ISSUE THREAD

**Issue by tbfvrs** [pyload/pyload#3037]
Hi
Is there a chance to get turbobit free plugin work again?

**Comment by GammaC0de** [comment]
Can you provided sample URLs?

**Comment by tbfvrs** [comment]
http://turbobit.net/wmoyda4co9kp.html

943 | 04.12.2017 14:40:49 | INFO | Added package P3 containing 1 links
-- | -- | -- | --
944 | 04.12.2017 14:40:50 | CRITICAL | no such group

no such group 0.00 BXFileSharing

before I've replaced UpdateManager it showed that cannot handle captcha or sth (TEXT AREA etc.)

**Comment by GammaC0de** [comment]
First of all, please disable XFileSharing plugin.

As for the Trubobit plugin, the odds that it can be fixed are low.
That is because the captcha they are using requires javascript.

**Comment by tbfvrs** [comment]
Just as I thought when I saw that jdownloader needs to redirect one to browser with some addon just to input captcha...

**Comment by GammaC0de** [comment]
Yep :(
Did you succeed to download with jdownloader? because I could not - the captcha did not work well

**Comment by tbfvrs** [comment]
Yeah I did get it work but only the ones with road signs (others just change when you click them);
If only there was a way to copy direct DL link (with turbobit server number etc )I could at least put it in pyload and let it go on my VPS continously, it wouldn't be that bad despite the free speed they offer;

As I recall IDM had such thing that you could copy direct DL link...

**Comment by GammaC0de** [comment]
I don't know how to make Jdownloader produce a detailed debug log like pyload do :/

**Comment by tbfvrs** [comment]
Thats how idm handles them:

http://s243.turbobit.net:9001/download.php?name=Inst.rar&md5=2fac40470d3aedcb9657139a11f94ab6&fid=wmoyda4co9kp&uid=free&speed=59&till=1512558955&trycount=1&ip=xx.xxx.xxx.xxx&sid=3c1988a4c35d23f8cf0d4ec4f83fa658&browser=9ec285cc711c87e45c9244f4f89fc994&did=2047129739&sign=84f61e929cc5d80350896b873001b8f3

Unfortunately it bounds it to IP where you open the link + browser + sign... It will be tough (impossible?) to just decode this link to put it in pyload...

**Comment by GammaC0de** [comment]
Just edit `userplugins/hoster/TurbobitNet.py` and change the `__pattern__` value to `r'^unmatchable$` and restart pyload.

From now on pyload will treat turbobit URLs as standard HTTP URLs.

Closing this since there is no better solution.
