### ISSUE TITLE
[XDCC] Registered Nickname and Invite Only Channels

### ISSUE THREAD

**Issue by tupertinois** [pyload/pyload#3038]
Hi I'm new to using pyload.

I managed (somehow) to install pyload and the XDCC plugin on my raspberry PI.

It's running great (Great Job guys!!) on public irc channels

So I was wondering is there a way to make it work on "invite only channels"? It would require : 
1-to identify a registered nickname (by sending the "/msg nickserv IDENTIFY Mypassword" to the server) 
2-to connect to a certain channel 
3- to send another Command Line to a bot like ("/msg BotName enter #DesiredInviteOnlyChannel Nickname SpecificIrckey")
4- finally to Send the CLI as usually used by XDCC plugin ("xdcc://SERVER:PORT/#DesiredInviteOnlyChannel/BOT_NAME/#PACK_NUM"

Thanks in advance

**Comment by GammaC0de** [comment]
Can you provide such a channel ,bots etc.. ?

**Comment by tupertinois** [comment]
Yep.. here are the info:

server:  irc.recycled-irc.net (6667)
main channel : #INFEXIOUS
for this channel, I think your nick shall be registered using "/msg nickserv register email_address"

And that's why you have then to identify yourself using "/msg nickserv IDENTIFY Mypassword"

the desired invite only channel : #iNFEXiOUS-ANNONCE

Here are the instructions given by the team to access the second channel:
https://sirc.at/paste/?9d0a0e37055673d5#iVYbZoACmwWe6TST/sRZeVFM5FiR+KetOKjbigEd8oU=

You may have to sign up (it's free) on their webiste first : https://in.fexio.us/

**Comment by GammaC0de** [comment]
I'm soory, I cannot sign to https://in.fexio.us/user/signup, I get `Le token d'enregistrement fournis est invalide` message.

**Comment by tupertinois** [comment]
It seems that a token has to be generated on the main channel #INFEXIOUS to authorize you to signup... I'll look it up in a couple of hours

It was the first channel to use this kind of method, usually they just make sure that your nickname is registered (using the nickserv method) and that you've identified yourself as the "owner" of this nickname. But i will check it

**Comment by GammaC0de** [comment]
Add registered nickname support (https://github.com/pyload/pyload/commit/2926191948946efc2fe733412a679534e67a178a) for meanwhile.

**Comment by tupertinois** [comment]
I've checked within the main channel, it seems that signing up have been suspended.

I may have an account you can use for testing... I prefer not to publish those info in public.

Thanks for the addition of the registered nickname support, but silly question of mine, how can I update my XDCC.py plugin without using copy/paste from putty?

**Comment by GammaC0de** [comment]
Pyload should be update it automatically using UpdateManager (just restart pyload to make sure)

I actually did managed to get an account, I just need need to xdcc list/offers/bots

**Comment by tupertinois** [comment]
Ok for the updated plugin .. i didn't check my Web UI

So back to the website (i'll make the translation) : https://in.fexio.us/user/signup => click on "S'identifier" (first field for you username, second for the password) => click on "Connexion"

You'll be on the main page. At the top of the page there different links "News",  "Séries", "Bots", "Requêtes" and a gear symbol on which you shall click (it will lead you to the account parameters page)

On this page there three main sections "Mes Séries", "Paramètres" , "Changement de mot de passe"

Fill the fiels "Clé IRC" with a password (IrcKey) of your choice then click "Valider" (at the end of the section)

The field below "Clé IRC" shall now be filled with a command line that you'll need to type in the main channel (/msg PyClark enter #iNFEXiOUS-ANNONCE ListingNickname IrcKey)

You'll get the following answer on the main channel : 
( ¤ ) Invites: You were invited to #iNFEXiOUS-ANNONCE by PyClark ( ~PyClark@i.N.F.E.X.i.O.U.S )

Then you just have to join #iNFEXiOUS-ANNONCE which is the invite only channel where all the available bots are connected 

As for the xdcc list, you can get them inside the main site, just click on "Bots" at the top of the page, you'll get to the bots listing page.

You just have to select one bot to get to its package's listing page in which there is a button to copy the command line to type in the invite only channel (at the end of each line)

**Comment by GammaC0de** [comment]
The thing is I don't have access to the web site, only to the IRC channel.

**Comment by tupertinois** [comment]
You have access to IRC channel (with your registered Nickname) but you cannot log on the website because of the error you encountered when signing on the website : 

> Le token d'enregistrement fournis est invalide message

Does that sum up the situation ?

**Comment by GammaC0de** [comment]
Yes.

**Comment by tupertinois** [comment]
Ok, I misunderstood, when you said you did get an account, I thought it was for the website

Normally in the IRC channel topic there should be a link to generate an Registering Token (yep, the "token d'enregistrement") in order to allow you to sign up on the website.

But in place of the link there is this sentence "Les inscriptions sont fermées" which means that the team does no longer allow external users to sign up on their website and to go to the  invite only channel , etc ..

I have a secondary account on the website which is also attached to a specific nickname which I created for someone who doesn't use IRC anymore.

Just let me find where I put all the necessary passwords and I shall lend them to you.

**Comment by GammaC0de** [comment]
You can send to nitzo2001 at yahoo dot com or with gitter.

**Comment by tupertinois** [comment]
Ok, just tested .. in fact a registered nickname is not compulsory to connect  the main channel.

Sending you details for connection just follow the detailled instruction posted before

**Comment by GammaC0de** [comment]
Tested and works :)

**Comment by tupertinois** [comment]
Awesome ! Thanks a lot

**Comment by RBilly** [comment]
Hi I'm new to pyload and this feature is exactly what I was looking for ! 👍 
Unfortunately I can't seem to make it work
How did you successfuly retrieved a package ?

I configured the XDCC plugin like following:
Registered nickname password (optional) : 
Ident: Username
Realname: Username
Invite bots options: irc.recycled-irc.net/#iNFEXiOUS-ANNONCE/PyClark/Password
Nickname: Username
Request XDCC resume: on

and I added a package with:
xdcc://irc.recycled-irc.net/#iNFEXiOUS-ANNONCE/Channel/#PACKAGE_NUMBER

With that I get:
Processing url: xdcc://irc.recycled-irc.net/#iNFEXiOUS-ANNONCE/Channel/#PACKAGE_NUMBER
Connecting to: irc.recycled-irc.net:6667
Joining channel #iNFEXiOUS-ANNONCE
Cannot join channel #iNFEXiOUS-ANNONCE (error 473: 'Cannot join channel (+i)')
Diconnecting from irc.recycled-irc.net:6667

Did I missed something ? 
Thanks a lot for your work and your time !

**Comment by RBilly** [comment]
Hi, 
Thanks for your answer. 
Yes I do have an account (I have been using Hexchat until now)
What should I put in Registered nickname password field ?
For exemple if I asked manually for invite with command:
/msg PyClark enter #iNFEXiOUS-ANNONCE Username Password 
Should I just pu Username in the field ?

As for the URL , I put Channel by mistake, of course it's botname

**Comment by GammaC0de** [comment]
@RBilly I think the problem is that invite bots options sould be:
irc.recycled-irc.net/iNFEXiOUS-ANNONCE/PyClark/Password (without # in the channel).

Please confirm and I will update the plugin if so.

**Comment by RBilly** [comment]
Hi @GammaC0de, thanks that was it !
By removing # from the channel name in the config and the url request (not sure if it was needed) it worked ! 👍 
thanks a lot

**Comment by RBilly** [comment]
@GammaC0de 
It's not really the right place for it but I have a few questions that you can maybe answer for me because I will soon install pyload on a raspberry and want to do things right. 
I wanted to know which branch I should use, the current stable one right ?
I tried to fiddle with it on my pc first and maybe I didn't install all of the required things but the web interface doesn't seem to display the download progress and for XDCC download the size stay 0.00 B / 0.00 B even when it's finished (didn't tried many kind of download).
Aside from that I came across a discussion about a new version of pyload with a new interface etc... where can I get information about that ?

have a great day and thanks again !

**Comment by tupertinois** [comment]
@RBilly 
I used the following guide [https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi)](url) and it worked perfectly.
And Yes you should use the stable branch

**Comment by GammaC0de** [comment]
Plugin updated to handle this issue.
