### ISSUE TITLE
SyntaxErrors - Missing parentheses and others

### ISSUE THREAD

**Issue by MannvonStand** [pyload/pyload#3041]
Good day,

I installed pyLoad via package manager and when running `python pyLoadCore.py` I am getting the following errors:

> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "")? (line 99, 139, etc.)

So, I opened pyLoadCore in an editor and found that after every print command there are brackets instead of parentheses. Hence I went ahead and changed some of them until I encountered the next SyntaxError.

> TabError: inconsistent use of tabs and spaces in indentation (line 142)

I went ahead and corrected that as well only to discover:

> SyntaxError: invalid syntax (line 151)

changed it and yet again another invalid Syntax one line below.

I was wondering if you wrote it this way and I am doing something wrong or if someone messed up the code? Also I am new to python and linux in general but know that if the system throws that many errors and all needed packages plus dependencies are installed, it is rarely the user's fault.

One more thing I almost forgot: I also downloaded the stable release from github and compared the files with Meld. They are identical.

**Comment by GammaC0de** [comment]
package manager mean pip?

I sugget you download the latest pyload from https://github.com/pyload/pyload/archive/stable.zip.

**Comment by MannvonStand** [comment]
No, I mean it as it is written in the README of the [stable branch](https://github.com/pyload/pyload/blob/stable/README):

> Note: If you installed pyload via package-manager...

I also downloaded the latest pyLoad from exactly that archive and the pyLoadCore files are identical, hence I get the same errors.

**Comment by GammaC0de** [comment]
I don't know the pyLoad package from the AUR repositories, it's not official.

There are two official ways to install pyLoad:
1. download it form https://github.com/pyload/pyload/archive/stable.zip (recommended).
2. The method described in #2000

**Comment by MannvonStand** [comment]
Like I said before I compared the two files from the AUR and from the github stable and they are identical using Meld.

Nevertheless I did as you mentioned and downloaded it from the https://github.com/pyload/pyload/archive/stable.zip and followed the method described it #2000. Outcome: **same errors**.

And if the package from the ArchLinux AUR is not official why do you have it on https://github.com/pyload/pyload/wiki/Download ?

**Comment by GammaC0de** [comment]
I was not aware of https://github.com/pyload/pyload/wiki/Download, I know https://github.com/pyload/pyload/releases.

Try using
`python <full_path_of_pyloadcore>/pyLoadCore.py`

**Comment by MannvonStand** [comment]
Nope, gives me the same error. Perhaps it is distro specific then.

Will try it on Ubuntu this weekend as the rest of my week is very busy and post an update once I tested.

**Comment by GammaC0de** [comment]
One more thing, try running with `python <full_path_of_pyloadcore>/pyLoadCore.py -d` so we can see the traceback.

**Comment by GammaC0de** [comment]
No response, closing.
