### ISSUE TITLE
external_script package_extracted destination param

### ISSUE THREAD

**Issue by luzik** [pyload/pyload#3044]
Please add extraction folder param to exterl_script->package_extracted. There is dl_folder - quite unusable, but extraction folder is nice param to have, and it is archive independent

**Comment by GammaC0de** [comment]
> There is dl_folder

Where exactly?

As far as I can see, package_extracted does send the extracted folder so please further explain what is "quite unusable"..

**Comment by luzik** [comment]
https://github.com/pyload/pyload-plugins/blob/stable/pyload/plugins/hooks/ExternalScripts.py :255
def package_extracted

Running external script with dl_folder after package seems to be only usable for deleting those archives, but this can be done using ExctarcArchive delete param.
What seems to be usable is an extraction folder (as script param), so from this external script I can do something with those extracted files (for example move those files somewhere)

**Comment by GammaC0de** [comment]
There is `archive_extracted` script with those arguments..

`package_extracted` is called after all archives in a package were extracted..

**Comment by luzik** [comment]
Yes, exacly ..but I would like to run this script with such information after whole package extracted. I know that getting all information - like from `package_extracted` is an issue, but adding simple extract destination folder shouldn't be such.

**Comment by GammaC0de** [comment]
> What seems to be usable is an extraction folder (as script param), so from this external script I can do something with those extracted files (for example move those files somewhere)

Why not doing this from `archive_extracted`?

**Comment by luzik** [comment]
For example, if my package contains 6 pack CD in 6 rar files, and I want to move those files as a whole. I know that this is something where I can always use static paths or just make use of archive_extracted and skip calls till last of archive, but my suggestion does not brake any thing, just extend functionality.

**Comment by GammaC0de** [comment]
each archive can be extracted to a different folder..

**Comment by GammaC0de** [comment]
No response, closing.
