### ISSUE TITLE
pid not readable (yet?) after start: No such file or directory

### ISSUE THREAD

**Issue by xenius** [pyload/pyload#3046]
I have a problem with the service running when i reboot my server...
I can't get it to work. It doesn't create the pidfile... If i manually create the dir and the pid and chown my user i can start the service but its gone after a reboot... Anyone a solution?

 pyload@ragnar.service - pyLoad
   Loaded: loaded (/etc/systemd/system/pyload@.service; enabled; vendor preset: enabled)
   Active: failed (Result: resources) since Sam 2017-12-09 16:59:36 CET; 5s ago
  Process: 4835 ExecStart=/usr/bin/python /home/ragnar/.pyload/pyLoadCore.py --config=/home/ragnar/.pyload --pidfile=/var/run/pyload/pid --daemon (code=exited, status=0/S

Dez 09 16:59:35 Lagertha systemd[1]: Starting pyLoad...
Dez 09 16:59:36 Lagertha python[4835]: Daemon PID 4863
Dez 09 16:59:36 Lagertha systemd[1]: pyload@ragnar.service: PID file /var/run/pyload/pid not readable (yet?) after start: No such file or directory
Dez 09 16:59:36 Lagertha systemd[1]: pyload@ragnar.service: Daemon never wrote its PID file. Failing.
Dez 09 16:59:36 Lagertha systemd[1]: Failed to start pyLoad.
Dez 09 16:59:36 Lagertha systemd[1]: pyload@ragnar.service: Unit entered failed state.
Dez 09 16:59:36 Lagertha systemd[1]: pyload@ragnar.service: Failed with result 'resources'.

[Unit]
Description=pyLoad
After=network.target
 
[Service]
Type=forking
KillMode=process
User=%I
PIDFile=/var/run/pyload/pid
ExecStart=/usr/bin/python /home/ragnar/.pyload/pyLoadCore.py --config=/home/ragnar/.pyload --pidfile=/var/run/pyload/pid --daemon
ExecStop=-/bin/kill -HUP
WorkingDirectory=/home/%I/
 
[Install]
WantedBy=multi-user.target

**Comment by GammaC0de** [comment]
Try removing --daemon

Also, what is the output of `sudo journalctl -u pyload`?

**Comment by xenius** [comment]
pyload@ragnar.service - pyLoad
   Loaded: loaded (/etc/systemd/system/pyload@.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sam 2017-12-09 17:43:29 CET; 7s ago
  Process: 8560 ExecStart=/usr/bin/python /home/ragnar/.pyload/pyLoadCore.py --config=/home/ragnar/.pyload --pidfile=/var/run/pyload/pid (code=exited, status=1/FAILURE)

Dez 09 17:43:29 Lagertha python[8560]:     pyload_core.start()
Dez 09 17:43:29 Lagertha python[8560]:   File "/home/ragnar/.pyload/pyLoadCore.py", line 355, in start
Dez 09 17:43:29 Lagertha python[8560]:     self.writePidFile()
Dez 09 17:43:29 Lagertha python[8560]:   File "/home/ragnar/.pyload/pyLoadCore.py", line 198, in writePidFile
Dez 09 17:43:29 Lagertha python[8560]:     f = open(self.pidfile, "wb")
Dez 09 17:43:29 Lagertha python[8560]: IOError: [Errno 2] No such file or directory: '/var/run/pyload/pid'
Dez 09 17:43:29 Lagertha systemd[1]: pyload@ragnar.service: Control process exited, code=exited status=1
Dez 09 17:43:29 Lagertha systemd[1]: Failed to start pyLoad.
Dez 09 17:43:29 Lagertha systemd[1]: pyload@ragnar.service: Unit entered failed state.
Dez 09 17:43:29 Lagertha systemd[1]: pyload@ragnar.service: Failed with result 'exit-code'.

journalctl -u pyload
-- No entries --

**Comment by GammaC0de** [comment]
What if you remove the `PIDFile=` line?

**Comment by xenius** [comment]
pyload@rangar.service - pyLoad
   Loaded: loaded (/etc/systemd/system/pyload@.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sam 2017-12-09 18:10:14 CET; 10s ago
  Process: 3362 ExecStart=/usr/bin/python /home/ragnar/.pyload/pyLoadCore.py --config=/home/ragnar/.pyload --pidfile=/var/run/pyload/pid (code=exited, status=217/USER)

Dez 09 18:10:14 Lagertha systemd[1]: Starting pyLoad...
Dez 09 18:10:14 Lagertha systemd[1]: pyload@rangar.service: Control process exited, code=exited status=217
Dez 09 18:10:14 Lagertha systemd[1]: Failed to start pyLoad.
Dez 09 18:10:14 Lagertha systemd[1]: pyload@rangar.service: Unit entered failed state.
Dez 09 18:10:14 Lagertha systemd[1]: pyload@rangar.service: Failed with result 'exit-code'.

**Comment by xenius** [comment]
if i change User=tomyusername

● pyload@rangar.service - pyLoad
   Loaded: loaded (/etc/systemd/system/pyload@.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sam 2017-12-09 18:53:34 CET; 2s ago
  Process: 10691 ExecStart=/usr/bin/python /home/ragnar/.pyload/pyLoadCore.py --config=/home/ragnar/.pyload --pidfile=/var/run/pyload/pid (code=exited, status=1/FAILURE)

Dez 09 18:53:34 Lagertha python[10691]:     pyload_core.start()
Dez 09 18:53:34 Lagertha python[10691]:   File "/home/ragnar/.pyload/pyLoadCore.py", line 355, in start
Dez 09 18:53:34 Lagertha python[10691]:     self.writePidFile()
Dez 09 18:53:34 Lagertha python[10691]:   File "/home/ragnar/.pyload/pyLoadCore.py", line 198, in writePidFile
Dez 09 18:53:34 Lagertha python[10691]:     f = open(self.pidfile, "wb")
Dez 09 18:53:34 Lagertha python[10691]: IOError: [Errno 2] No such file or directory: '/var/run/pyload/pid'
Dez 09 18:53:34 Lagertha systemd[1]: pyload@rangar.service: Control process exited, code=exited status=1
Dez 09 18:53:34 Lagertha systemd[1]: Failed to start pyLoad.
Dez 09 18:53:34 Lagertha systemd[1]: pyload@rangar.service: Unit entered failed state.
Dez 09 18:53:34 Lagertha systemd[1]: pyload@rangar.service: Failed with result 'exit-code'.

**Comment by GammaC0de** [comment]
What OS are you using?

**Comment by xenius** [comment]
I have found a solution:

`[Unit]
Description=pyLoad
After=network.target

[Service]
Type=forking
KillMode=process
User=ragnar
PIDFile=/home/ragnar/pyload/pid
ExecStart=/usr/bin/python /home/ragnar/.pyload/pyLoadCore.py --config=/home/ragnar/.pyload --pidfile=/home/ragnar/pyload/pid --daemon
ExecStop=-/bin/kill -HUP
WorkingDirectory=/home/ragnar/

[Install]
WantedBy=multi-user.target
`
I've put the pidfile into the userdir, atleast this is working atm.

**Comment by GammaC0de** [comment]
OK, seem like a permission issue (ragnar user probably does not have write pers to /var/run).

Closing then. 👍

**Comment by laykechen** [comment]
I have the same problem while i config my teamspeak server, I fixed it by “chown -R teamspeak:teamspeak teamspeak3-server_linux_amd64”,  WTF!!
