### ISSUE TITLE
SimplydebridCom

### ISSUE THREAD

**Issue by KristofVr** [pyload/pyload#3047]
When I try to connect to SimplydebridCom I get following error message:

09.12.2017 17:55:19 WARNING   ACCOUNT SimplydebridCom: Error loading hoster list for user `emp*******` | descriptor 'strip' requires a 'str' object but received a 'unicode'
09.12.2017 17:55:19 ERROR     ACCOUNT SimplydebridCom: Failed to load hoster list for user `emp*******`, retry in 5 minutes

Is this a known issue or does anyone has a quick fix?

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.
