### ISSUE TITLE
Add the possibility to deactivate to plugin updater or create a stable branch of the plugins

### ISSUE THREAD

**Issue by RincewindsHat** [pyload/pyload#3050]
It would be really nice, if there would be a nice way to prevent pyload from making itself useless by downloading broken plugins and replacing the working ones.

**Comment by GammaC0de** [comment]
I really don't understand what you are trying to say.
The whole point of the plugin update process is to fix issues in the plugins by downloading and updated version.

Which  broken plugins are you talking about?
If you have any specific issue please specify it, I would gladly help with that.

**Comment by Burnout5151** [comment]
I just updated and my Webinterface broke. Maybe he has the same problem?
`TemplateNotFound: default/home.html
`

**Comment by GammaC0de** [comment]
@RincewindsHat see https://github.com/pyload/pyload/issues/3043

**Comment by Burnout5151** [comment]
@GammaC0de : Thank you, I wasn't aware of that. :-)

**Comment by GammaC0de** [comment]
No response, closing.
