### ISSUE TITLE
FshareVN Error loading info

### ISSUE THREAD

**Issue by bigdargon** [pyload/pyload#3051]
Plugins FshareVN can't loading info. Can you fix it?
`
1480 | 20.12.2017 09:59:06 | INFO | ACCOUNT FshareVn: Grabbing account info for user `myh*******`...
-- | -- | -- | --
1481 | 20.12.2017 09:59:08 | WARNING | ACCOUNT FshareVn: Error loading info for user `myh*******` \| time data  u'15-05-2019 23:59:59' does not match format '%d-%m-%Y %H:%M:%S'
`

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.
