### ISSUE TITLE
Help updating pyload on D-Link NAS

### ISSUE THREAD

**Issue by hbbernardo** [pyload/pyload#3056]
Hi Pyload.

I have a D-link DNS 320L NAS. I was able to install a third party addon containing Pyload.

But the thing is. It is too old apparently. There are lots os plugins missing. Especially, in my case MegaCoNz

I have tried to manually put the new UpdateManager.Py into the hooks folder. 

But the only thing I got was this message error in the logs.

Error importing UpdateManager: No module named Addon
ERROR | Error importing ExtractArchive: No module named AbstractExtractor

Please, can anyone help me?

Thanks

**Comment by GammaC0de** [comment]
Try this:
https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/830cb0161b416a5328e32516067608cd2cfdd031/UpdateManager.py

**Comment by hbbernardo** [comment]
Thanks for replying.

I will replace the UpdateManager.py that I have placed in my NAS with this one.

I will let you know what happened

**Comment by hbbernardo** [comment]
Sorry for the delayed response.

Pyload took a while to update all plugins. 

This message appeared after the update was done:


608 | 25.12.2017 22:49:09 | INFO | Downloadtime: True
-- | -- | -- | --
```
609 | 25.12.2017 22:49:09 | INFO | Starting ThriftBackend: 0.0.0.0:7227
610 | 25.12.2017 22:49:15 | INFO | Starting threaded webserver: 0.0.0.0:8000
611 | 25.12.2017 22:49:15 | INFO | Free space: 162.48 GiB
612 | 25.12.2017 22:49:16 | INFO | Activating Accounts...
613 | 25.12.2017 22:49:16 | INFO | Activating Plugins...
614 | 25.12.2017 22:49:43 | INFO | ADDON UpdateManager: pyLoad is up to date!
615 | 25.12.2017 22:49:44 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/BayfilesCom.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/BayfilesCom.py'
616 | 25.12.2017 22:49:44 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/BitshareCom.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/BitshareCom.py'
617 | 25.12.2017 22:49:44 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/DdlstorageCom.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/DdlstorageCom.py'
618 | 25.12.2017 22:49:44 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/HotfileCom.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/HotfileCom.py'
619 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/NetloadIn.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/NetloadIn.py'
620 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/RapidshareCom.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/RapidshareCom.py'
621 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/RyushareCom.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/RyushareCom.py'
622 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/StahnuTo.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/StahnuTo.py'
623 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/UploadingCom.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/UploadingCom.py'
624 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/WarserverCz.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/accounts/WarserverCz.py'
625 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/crypter/DontKnowMe.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/crypter/DontKnowMe.py'
626 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/crypter/OneKhDe.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/crypter/OneKhDe.py'
627 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hooks/ClickAndLoad.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hooks/ClickAndLoad.py'
628 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hooks/IRCInterface.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hooks/IRCInterface.py'
629 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hooks/XFileSharingPro.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hooks/XFileSharingPro.py'
630 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hooks/XMPPInterface.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hooks/XMPPInterface.py'
631 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hoster/NowDownloadEu.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hoster/NowDownloadEu.py'
632 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hoster/RapidshareCom.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hoster/RapidshareCom.py'
633 | 25.12.2017 22:49:45 | WARNING | ADDON UpdateManager: Error removing `/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hoster/XFileSharingPro.py` \| [Errno 13] Permission denied: '/mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins/hoster/XFileSharingPro.py'
634 | 25.12.2017 22:49:46 | INFO | ADDON UpdateManager: All plugins are up to date!
```

What should I do?

**Comment by GammaC0de** [comment]
You do not have write permissions to /mnt/HD/HD_a2/Nas_Prog/pyLoad/module/plugins...

**Comment by hbbernardo** [comment]
I have found another error.

When I tried to add my mega credentials to pyload this error message appeared in the logs:


ERROR | ACCOUNT MegaCoNz: Could not login user `*******` \| [Errno 13] Permission denied: '/dev/urandom'
-- | --

**Comment by GammaC0de** [comment]
What is the output of: `ls -la /dev/urandom`?

**Comment by hbbernardo** [comment]
-bash-4.3# ls -la /dev/urandom
crw-rw----    1 root     root        1,   9 Dec 31  1999 /dev/urandom

I have noticed that pyload is being run by 'nobody'.

![image](https://user-images.githubusercontent.com/24485236/34346989-65b5d92e-e9dc-11e7-8af4-529a0113954c.png)

**Comment by GammaC0de** [comment]
try `sudo chmod 666  /dev/urandom`

**Comment by hbbernardo** [comment]
Sorry for the delayed response. A timezone between us was to blame.

It worked. All is set, apparently.

`26.12.2017 12:02:02 INFO      restarting pyLoad
26.12.2017 12:02:02 INFO      shutting down...
26.12.2017 12:02:02 INFO      ADDON ClickNLoad: Shutting down proxy...
26.12.2017 12:02:03 INFO      Starting pyLoad 0.4.9
26.12.2017 12:02:03 INFO      Using home directory: /mnt/HD/HD_a2/Nas_Prog/pyLoa                                                                                        d/config
26.12.2017 12:02:13 INFO      Activated plugins: BypassCaptcha, Checksum, ClickN                                                                                        Load, EventMapper, ExternalScripts, ExtractArchive, ImageTyperz, LinkdecrypterCo                                                                                        mHook, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
26.12.2017 12:02:13 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandb                                                                                        y, AntiVirus, Captcha9Kw, CaptchaBrotherhood, CloudFlareDdos, DeathByCaptcha, De                                                                                        leteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, JustPremium, Li                                                                                        nkFilter, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed,                                                                                         SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
26.12.2017 12:02:13 INFO      Downloadtime: True
26.12.2017 12:02:13 INFO      Starting ThriftBackend: 0.0.0.0:7227
26.12.2017 12:02:18 INFO      Free space: 155.24 GiB
26.12.2017 12:02:18 INFO      Starting threaded webserver: 0.0.0.0:8000
26.12.2017 12:02:19 INFO      Activating Accounts...
26.12.2017 12:02:47 INFO      ACCOUNT MegaCoNz: Adding user `*******`...
26.12.2017 12:02:47 INFO      ACCOUNT MegaCoNz: Login user `*******`...
26.12.2017 12:02:48 WARNING   ACCOUNT MegaCoNz: Skipped login user `*******`                                                                                         | Already signed in
26.12.2017 12:02:48 INFO      ACCOUNT MegaCoNz: Grabbing account info for user `                                                                                        *******`...
26.12.2017 12:02:49 INFO      Activating Plugins...
26.12.2017 12:02:51 INFO      ADDON UpdateManager: pyLoad is up to date!
26.12.2017 12:02:53 INFO      ADDON UpdateManager: All plugins are up to date!
26.12.2017 12:02:53 INFO      ADDON XFileSharing: Auto-discover new hosters
26.12.2017 12:02:54 INFO      ADDON XFileSharing: Auto-discover new crypters
26.12.2017 12:02:54 INFO      pyLoad is up and running
26.12.2017 12:02:56 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666`

**Comment by hbbernardo** [comment]
It is all set.

I have successfully added a file from Mega. Downloaded and decrypted.

26.12.2017 12:15:57 INFO      Added package Magazine containing 1 links
26.12.2017 12:15:58 INFO      Download starts: https://mega.nz/XXXXXXXXXXXXXXXXXXXXXX
26.12.2017 12:15:58 WARNING   HOSTER MegaCoNz[40]: Plugin may be unstable
26.12.2017 12:15:58 INFO      ACCOUNT MegaCoNz: Grabbing account info for user `*******`...
26.12.2017 12:15:58 INFO      HOSTER MegaCoNz[40]: Grabbing link info...
26.12.2017 12:15:58 INFO      HOSTER MegaCoNz[40]: Link name: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
26.12.2017 12:15:58 INFO      HOSTER MegaCoNz[40]: Link size: N/D
26.12.2017 12:15:58 INFO      HOSTER MegaCoNz[40]: Link status: starting
26.12.2017 12:15:58 INFO      HOSTER MegaCoNz[40]: Processing url: https://mega.nz/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
26.12.2017 12:16:56 INFO      HOSTER MegaCoNz[40]: File saved
26.12.2017 12:20:19 INFO      HOSTER MegaCoNz[40]: File decrypted
26.12.2017 12:20:19 INFO      HOSTER MegaCoNz[40]: File integrity of "Magazine.pdf" verified by CBC-MAC checksum ((3496197966L, 1472427684))
26.12.2017 12:20:19 INFO      HOSTER MegaCoNz[40]: Checking download...
26.12.2017 12:20:20 INFO      HOSTER MegaCoNz[40]: File is OK
26.12.2017 12:20:20 INFO      Download finished: Magazine
26.12.2017 12:20:20 INFO      Package finished: Magazine
26.12.2017 12:20:20 INFO      ADDON ExtractArchive: Check package: Magazine
26.12.2017 12:20:20 INFO      ADDON ExtractArchive: No files found to extract

Thank you so much for helping me out bringing some new life to my old NAS.

Regards

**Comment by GammaC0de** [comment]
👍
