### ISSUE TITLE
No favicon in Web interface with reverse proxy

### ISSUE THREAD

**Issue by youlJunior** [pyload/pyload#3057]
Hello,

When using a reverse proxy changing context root, favicon does'nt work.
Because no favicon is specified in HTML, brower search for it in web root, without context root.

Example : 
- pyload is accessed with https://192.168.0.x/pyload/
- browser search for https://192.168.0.x/favicon.ico

I modified pyload-stable/module/web/templates/classic/base.html with adding inside ```<head>``` : 
```<link rel="icon" href="/favicon.ico" />```

**Comment by GammaC0de** [comment]
I think you should set `Path Prefix` settings in the general/web interface config.

**Comment by youlJunior** [comment]
Path prefix is already set, but this is not relevant.

If there is no favicon set in HTML, browser always try to get icon from root, without path.
