### ISSUE TITLE
Error on first start, after configuring everything OK

### ISSUE THREAD

**Issue by joseluislucas** [pyload/pyload#3058]
First time I did "sudo pyLoadCore" I had to configure and setup, it all went well and the configuration was successful, so I wanted to restart pyLoadCore.

I do "sudo pyLoadCore" and those errors appear:

> Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 392, in start
    self.pluginManager = PluginManager(self)
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 50, in __init__
    self.createIndex()
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 73, in createIndex
    self.plugins["hooks"] = self.hookPlugins = self.parse("hooks")
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 163, in parse
    config = literal_eval(config[0].strip().replace("\n", "").replace("\r", ""))
  File "/usr/share/pyload/module/lib/SafeEval.py", line 44, in const_eval
    c = test_expr(expr, _const_codes)
  File "/usr/share/pyload/module/lib/SafeEval.py", line 33, in test_expr
    raise ValueError, "%s is not a valid expression" % expr
ValueError: (<span class="pl-s"><span class="pl-pds">&quot;</span>mh_mode<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>all;listed;unlisted<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Filter hosters to use<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>all<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L14" class="blob-num js-line-number" data-line-number="14"></td>        <td id="LC14" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>mh_list<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Hoster list (comma separated)<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span><span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L15" class="blob-num js-line-number" data-line-number="15"></td>        <td id="LC15" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>mh_interval<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>int<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Reload interval in hours<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">12</span>) is not a valid expression

> 

I have installed pyLoad from the deb package, version 0.4.9, as it says [here](https://github.com/pyload/pyload/issues/2000)

**Comment by GammaC0de** [comment]
What  python version are you using?
You should use v2.7

**Comment by zaikar** [comment]
I have used also "sudo python2.7 pyLoadCore.py" and the output is exactly the same...

**Comment by GammaC0de** [comment]
What Hardware are you using, What OS?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by UserX404** [comment]
same Problem on first run
running on Qnap TS-x53 (x64)
Python 2.7.15

`[/share/MD0_DATA/.qpkg/Entware/etc/pyload] # ./pyLoadCore.py
19.01.2019 22:57:18 INFO      starte pyLoad 0.4.9
19.01.2019 22:57:18 INFO      Benutze Home-Verzeichnis: /share/MD0_DATA/.qpkg/Entware/var/.pyload
19.01.2019 22:57:18 ERROR     Invalid config in RapidshareCom: ['server', 'Cogent;Deutsche Telekom;Level(3);Level(3) #2;GlobalCrossing;Level(3) #3;Teleglobe;GlobalCrossing #2;TeliaSonera #2;Teleglobe #2;TeliaSonera #3;TeliaSonera', 'Preferred Server', 'None']
Traceback (most recent call last):
  File "./pyLoadCore.py", line 666, in <module>
    main()
  File "./pyLoadCore.py", line 657, in main
    pyload_core.start()
  File "./pyLoadCore.py", line 391, in start
    self.pluginManager = PluginManager(self)
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/plugins/PluginManager.py", line 50, in __init__
    self.createIndex()
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/plugins/PluginManager.py", line 91, in createIndex
    self.hookPlugins, config = self.parse("hooks")
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/plugins/PluginManager.py", line 203, in parse
    config = literal_eval(config[0].strip().replace("\n", "").replace("\r", ""))
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/lib/SafeEval.py", line 44, in const_eval
    c = test_expr(expr, _const_codes)
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/lib/SafeEval.py", line 33, in test_expr
    raise ValueError, "%s is not a valid expression" % expr
ValueError: [(<span class="pl-s"><span class="pl-pds">&quot;</span>activated<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Activated<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">True</span>),</td>      </tr>      <tr>        <td id="L22" class="blob-num js-line-number" data-line-number="22"></td>        <td id="LC22" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>checkinterval<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>int<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Check interval in hours<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">6</span>),</td>      </tr>      <tr>        <td id="L23" class="blob-num js-line-number" data-line-number="23"></td>        <td id="LC23" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>autorestart<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Auto-restart pyLoad when required<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">True</span>),</td>      </tr>      <tr>        <td id="L24" class="blob-num js-line-number" data-line-number="24"></td>        <td id="LC24" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>checkonstart<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Check for updates on startup<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">True</span>),</td>      </tr>      <tr>        <td id="L25" class="blob-num js-line-number" data-line-number="25"></td>        <td id="LC25" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>checkperiod<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Check for updates periodically<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">True</span>),</td>      </tr>      <tr>        <td id="L26" class="blob-num js-line-number" data-line-number="26"></td>        <td id="LC26" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>reloadplugins<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Monitor plugin code changes in debug mode<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">True</span>),</td>      </tr>      <tr>        <td id="L27" class="blob-num js-line-number" data-line-number="27"></td>        <td id="LC27" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>nodebugupdate<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Don&#39;t update plugins in debug mode<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">False</span>)] is not a valid expression`

I manualy removed Rapishare files in account and hoster. The remaining "...not a valid expression" message is the same.

**Comment by UserX404** [comment]
`[/share/MD0_DATA/.qpkg/Entware/etc/pyload] # cat /share/MD0_DATA/.qpkg/Entware/var/.pyload/pyload.conf
version: 1

remote - "Remote":
        bool nolocalauth : "No authentication on local connections" = True
        bool activated : "Activated" = True
        int port : "Port" = 7227
        ip listenaddr : "Adress" = 0.0.0.0

log - "Log":
        int log_size : "Size in kb" = 100
        folder log_folder : "Folder" = Logs
        bool file_log : "File Log" = True
        int log_count : "Count" = 5
        bool log_rotate : "Log Rotate" = True

permission - "Permissions":
        str group : "Groupname" = users
        bool change_dl : "Change Group and User of Downloads" = False
        bool change_file : "Change file mode of downloads" = False
        str user : "Username" = user
        str file : "Filemode for Downloads" = 0644
        bool change_group : "Change group of running process" = False
        str folder : "Folder Permission mode" = 0755
        bool change_user : "Change user of running process" = False

general - "General":
        en;de;fr;it;es;nl;sv;ru;pl;cs;sr;pt_BR language : "Language" = de
        folder download_folder : "Download Folder" = /share/Download/Pyload/
        bool checksum : "Use Checksum" = False
        bool folder_per_package : "Create folder for each package" = True
        bool debug_mode : "Debug Mode" = False
        int min_free_space : "Min Free Space (MB)" = 200
        int renice : "CPU Priority" = 0

ssl - "SSL":
        file cert : "SSL Certificate" = ssl.crt
        bool activated : "Activated" = True
        file key : "SSL Key" = ssl.key

webinterface - "Webinterface":
        str template : "Template" = default
        bool activated : "Activated" = True
        str prefix : "Path Prefix" =
        builtin;threaded;fastcgi;lightweight server : "Server" = threaded
        ip host : "IP" = 0.0.0.0
        bool https : "Use HTTPS" = False
        int port : "Port" = 58001

proxy - "Proxy":
        str username : "Username" = None
        bool proxy : "Use Proxy" = False
        str address : "Address" = "localhost"
        password password : "Password" = None
        http;socks4;socks5 type : "Protocol" = http
        int port : "Port" = 7070

reconnect - "Reconnect":
        time endTime : "End" = 0:00
        bool activated : "Use Reconnect" = False
        str method : "Method" = None
        time startTime : "Start" = 0:00

download - "Download":
        int max_downloads : "Max Parallel Downloads" = 3
        bool limit_speed : "Limit Download Speed" = False
        str interface : "Download interface to bind (ip or Name)" = None
        bool skip_existing : "Skip already existing files" = False
        int max_speed : "Max Download Speed in kb/s" = -1
        bool ipv6 : "Allow IPv6" = False
        int chunks : "Max connections for one download" = 3

downloadTime - "Download Time":
        time start : "Start" = 0:00
        time end : "End" = 0:00
`

**Comment by GammaC0de** [comment]
Can you delete /share/MD0_DATA/.qpkg/Entware/var/.pyload/plugin.conf` and retry running?

**Comment by UserX404** [comment]
it seems to be the same

`[/share/MD0_DATA/.qpkg/Entware/etc/pyload] # ./pyLoadCore.py > log
Traceback (most recent call last):
  File "./pyLoadCore.py", line 666, in <module>
    main()
  File "./pyLoadCore.py", line 657, in main
    pyload_core.start()
  File "./pyLoadCore.py", line 391, in start
    self.pluginManager = PluginManager(self)
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/plugins/PluginManager.py", line 50, in __init__
    self.createIndex()
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/plugins/PluginManager.py", line 91, in createIndex
    self.hookPlugins, config = self.parse("hooks")
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/plugins/PluginManager.py", line 203, in parse
    config = literal_eval(config[0].strip().replace("\n", "").replace("\r", ""))
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/lib/SafeEval.py", line 44, in const_eval
    c = test_expr(expr, _const_codes)
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/lib/SafeEval.py", line 33, in test_expr
    raise ValueError, "%s is not a valid expression" % expr
ValueError: [(<span class="pl-s"><span class="pl-pds">&quot;</span>activated<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Activated<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">True</span>),</td>      </tr>      <tr>        <td id="L22" class="blob-num js-line-number" data-line-number="22"></td>        <td id="LC22" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>checkinterval<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>int<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Check interval in hours<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">6</span>),</td>      </tr>      <tr>        <td id="L23" class="blob-num js-line-number" data-line-number="23"></td>        <td id="LC23" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>autorestart<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Auto-restart pyLoad when required<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">True</span>),</td>      </tr>      <tr>        <td id="L24" class="blob-num js-line-number" data-line-number="24"></td>        <td id="LC24" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>checkonstart<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Check for updates on startup<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">True</span>),</td>      </tr>      <tr>        <td id="L25" class="blob-num js-line-number" data-line-number="25"></td>        <td id="LC25" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>checkperiod<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Check for updates periodically<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">True</span>),</td>      </tr>      <tr>        <td id="L26" class="blob-num js-line-number" data-line-number="26"></td>        <td id="LC26" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>reloadplugins<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Monitor plugin code changes in debug mode<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">True</span>),</td>      </tr>      <tr>        <td id="L27" class="blob-num js-line-number" data-line-number="27"></td>        <td id="LC27" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>nodebugupdate<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Don&#39;t update plugins in debug mode<span class="pl-pds">&quot;</span></span>, <span class="pl-c1">False</span>)] is not a valid expression`

**Comment by GammaC0de** [comment]
Can you tell me please how have you installed pyload?

**Comment by UserX404** [comment]
downloaded sourcecode.zip 
https://github.com/pyload/pyload/archive/v0.4.9.zip
and extracted to
/share/MD0_DATA/.qpkg/Entware/etc/pyload]

installed all dependencies via opkg (Entware)

`ca-bundle - 20180409-3
ca-certificates - 20180409-3
entware-opt - 227000-3
entware-release - 1.0-2
entware-upgrade - 1.0-1
file - 5.35-1
findutils - 4.6.0-1
giflib - 5.1.4-1
grep - 3.1-1
js - 1.6.20070208-2
lcms - 2.9-1
libbz2 - 1.0.6-4
libc - 2.27-8
libcurl - 7.62.0-1
libdb47 - 4.7.25.4.NC-5
libexpat - 2.2.6-1
libffi - 3.2.1-3
libfreetype - 2.9.1-1
libgcc - 7.3.0-8
libgdbm - 1.11-1
libgmp - 6.1.2-1
libjpeg - 9c-1
libjs - 1.6.20070208-2
libleptonica - 1.76.0-1
libmagic - 5.35-1
libncurses - 6.1-1
libncursesw - 6.1-1
libopenssl - 1.0.2p-1a
libpcre - 8.42-1
libpcre2 - 10.32-1
libpng - 1.6.35-1
libpthread - 2.27-8
libreadline - 7.0-1
librt - 2.27-8
libsqlite3 - 3250300-1
libssp - 7.3.0-8
libstdcpp - 7.3.0-8
libtiff - 4.0.10-1
libtirpc - 1.1.4-1
libuv - 1.23.2-1
libxml2 - 2.9.8-3
locales - 2.27-8
nano - 3.2-1
node - v8.12.0-1
opkg - 2011-04-08-9c97d5ec-17c
pillow - 5.3.0-1
python - 2.7.15-2
python-asn1crypto - 0.24.0-1
python-base - 2.7.15-2
python-cffi - 1.11.5-1
python-codecs - 2.7.15-2
python-compiler - 2.7.15-2
python-crypto - 2.6.1-3
python-cryptography - 2.4.2-1
python-ctypes - 2.7.15-2
python-curl - 7.43.0.2-1
python-db - 2.7.15-2
python-decimal - 2.7.15-2
python-distutils - 2.7.15-2
python-email - 2.7.15-2
python-enum34 - 1.1.6-3
python-gdbm - 2.7.15-2
python-idna - 2.7-1
python-ipaddress - 1.0.22-1
python-light - 2.7.15-2
python-logging - 2.7.15-2
python-multiprocessing - 2.7.15-2
python-ncurses - 2.7.15-2
python-openssl - 2.7.15-2
python-pip-conf - 0.1-1
python-ply - 3.11-1
python-pycparser - 2.19-1
python-pydoc - 2.7.15-2
python-pyopenssl - 18.0.0-1
python-setuptools - 39.0.1-1
python-six - 1.11.0-2
python-sqlite3 - 2.7.15-2
python-unittest - 2.7.15-2
python-xml - 2.7.15-2
sqlite3-cli - 3250300-1
terminfo - 6.1-1
tesseract - 4.0.0-1
unrar - 5.6.8-1
unzip - 6.0-6
wget - 1.20-1a
zlib - 1.2.11-2
zoneinfo-asia - 2018g-1
zoneinfo-europe - 2018g-1
`

**Comment by GammaC0de** [comment]
Download the latest sources from here: https://github.com/pyload/pyload/archive/stable.zip

**Comment by GammaC0de** [comment]
:tada:
