### ISSUE TITLE
ZippyshareCom not working

### ISSUE THREAD

**Issue by oltodosel** [pyload/pyload#3062]
Zippyshare doesn't work any more. Log says download was successful, but file contains html page with 404 error.

> 290 | 31.12.2017 15:45:18 | WARNING | HOSTER ZippyshareCom[8292]: Plugin may be unstable
> -- | -- | -- | --
> 291 | 31.12.2017 15:45:18 | INFO | HOSTER ZippyshareCom[8292]: Grabbing link info...
> 292 | 31.12.2017 15:45:19 | INFO | HOSTER ZippyshareCom[8292]: Link name: 5retemsunimsulp.02.part13.rar
> 293 | 31.12.2017 15:45:19 | INFO | HOSTER ZippyshareCom[8292]: Link size: 150.00 MiB (157286400 bytes)
> 294 | 31.12.2017 15:45:19 | INFO | HOSTER ZippyshareCom[8292]: Link status: online
> 295 | 31.12.2017 15:45:19 | INFO | HOSTER ZippyshareCom[8292]: Processing url: http://www25.zippyshare.com/v/tt2WZimS/file.html
> 296 | 31.12.2017 15:45:19 | INFO | HOSTER ZippyshareCom[8292]: Looking for direct download link...
> 297 | 31.12.2017 15:45:19 | INFO | HOSTER ZippyshareCom[8292]: Direct download link not found
> 298 | 31.12.2017 15:45:19 | INFO | HOSTER ZippyshareCom[8292]: Checking for link errors...
> 299 | 31.12.2017 15:45:19 | INFO | HOSTER ZippyshareCom[8292]: No errors found
> 300 | 31.12.2017 15:45:19 | INFO | HOSTER ZippyshareCom[8292]: Processing as free download...
> 301 | 31.12.2017 15:45:19 | WARNING | CAPTCHA ZippyshareCom[8292]: ReCaptcha \| Key pattern not found
> 302 | 31.12.2017 15:45:19 | INFO | HOSTER ZippyshareCom[8292]: Downloading file...
> 303 | 31.12.2017 15:45:20 | INFO | HOSTER ZippyshareCom[8292]: File saved
> 304 | 31.12.2017 15:45:20 | INFO | HOSTER ZippyshareCom[8292]: Checking download...
> 305 | 31.12.2017 15:45:20 | INFO | HOSTER ZippyshareCom[8292]: File is OK
> 306 | 31.12.2017 15:45:20 | INFO | HOSTER ZippyshareCom[8292]: Checking file (with built-in rules)...
> 307 | 31.12.2017 15:45:20 | INFO | HOSTER ZippyshareCom[8292]: Checking file (with custom rules)...
> 308 | 31.12.2017 15:45:20 | INFO | HOSTER ZippyshareCom[8292]: Checking for link errors...
> 309 | 31.12.2017 15:45:20 | INFO | HOSTER ZippyshareCom[8292]: No errors found
> 310 | 31.12.2017 15:45:20 | INFO | HOSTER ZippyshareCom[8292]: No errors found
> 311 | 31.12.2017 15:45:20 | INFO | Download finished: 5retemsunimsulp.02.part13.rar

**Comment by GammaC0de** [comment]
This worked fine for me, try restarting the downlad.

**Comment by oltodosel** [comment]
It happens with every zippyshare link, even if I add one separately without crypter. Also tried restarting payload.

**Comment by GammaC0de** [comment]
Is this a new installation?

**Comment by oltodosel** [comment]
No. Worked fine for some time.

**Comment by GammaC0de** [comment]
What plugin version are you using?

**Comment by oltodosel** [comment]
Where can I find it?

**Comment by GammaC0de** [comment]
Enable debug mode, start a download and look in the log.

**Comment by oltodosel** [comment]
Plugin version: 0.94

**Comment by GammaC0de** [comment]
v0.94 is the latest.

Please post the log with debug mode enabled.

**Comment by oltodosel** [comment]
215 | 31.12.2017 18:03:27 | INFO | Download starts: 5retemsunimsulp.02.part13.rar (2)
-- | -- | -- | --
216 | 31.12.2017 18:03:27 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
217 | 31.12.2017 18:03:27 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
218 | 31.12.2017 18:03:27 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
219 | 31.12.2017 18:03:27 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
220 | 31.12.2017 18:03:27 | DEBUG | HOSTER ZippyshareCom[8363]: Plugin version: 0.94
221 | 31.12.2017 18:03:27 | DEBUG | HOSTER ZippyshareCom[8363]: Plugin status: testing
222 | 31.12.2017 18:03:27 | WARNING | HOSTER ZippyshareCom[8363]: Plugin may be unstable
223 | 31.12.2017 18:03:27 | INFO | HOSTER ZippyshareCom[8363]: Grabbing link info...
224 | 31.12.2017 18:03:27 | DEBUG | HOSTER ZippyshareCom[8363]: Link info: {'status': 2, 'hash': {}, 'name': u'5retemsunimsulp.02.part13.rar', 'url': u'http://www25.zippyshare.com/v/tt2WZimS/file.html', 'pattern': {'HOST': u'www25.zippyshare.com', 'U': u'MB', 'S': u'150', 'KEY': u'tt2WZimS', 'N': u'5retemsunimsulp.02.part13.rar'}, 'size': 157286400}
225 | 31.12.2017 18:03:27 | DEBUG | HOSTER ZippyshareCom[8363]: Previous link info: {}
226 | 31.12.2017 18:03:27 | INFO | HOSTER ZippyshareCom[8363]: Link name: 5retemsunimsulp.02.part13.rar
227 | 31.12.2017 18:03:27 | INFO | HOSTER ZippyshareCom[8363]: Link size: 150.00 MiB (157286400 bytes)
228 | 31.12.2017 18:03:27 | INFO | HOSTER ZippyshareCom[8363]: Link status: online
229 | 31.12.2017 18:03:27 | INFO | HOSTER ZippyshareCom[8363]: Processing url: http://www25.zippyshare.com/v/tt2WZimS/file.html
230 | 31.12.2017 18:03:27 | INFO | HOSTER ZippyshareCom[8363]: Looking for direct download link...
231 | 31.12.2017 18:03:27 | DEBUG | HOSTER ZippyshareCom[8363]: LOAD URL http://www25.zippyshare.com/v/tt2WZimS/file.html \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
232 | 31.12.2017 18:03:27 | INFO | HOSTER ZippyshareCom[8363]: Direct download link not found
233 | 31.12.2017 18:03:27 | DEBUG | HOSTER ZippyshareCom[8363]: LOAD URL http://www25.zippyshare.com/v/tt2WZimS/file.html \| redirect=True \| cookies=[('zippyshare.com', 'ziplocale', 'en')] \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
234 | 31.12.2017 18:03:27 | INFO | HOSTER ZippyshareCom[8363]: Checking for link errors...
235 | 31.12.2017 18:03:27 | INFO | HOSTER ZippyshareCom[8363]: No errors found
236 | 31.12.2017 18:03:27 | INFO | HOSTER ZippyshareCom[8363]: Processing as free download...
237 | 31.12.2017 18:03:27 | WARNING | CAPTCHA ZippyshareCom[8363]: ReCaptcha \| Key pattern not found
238 | 31.12.2017 18:03:27 | INFO | HOSTER ZippyshareCom[8363]: Downloading file...
239 | 31.12.2017 18:03:27 | DEBUG | HOSTER ZippyshareCom[8363]: DOWNLOAD URL http://www25.zippyshare.com/Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
240 | ? | ? | /pd/tt2WZimS/15262/5retemsunimsulp.02.part13.rar \| fixurl=True \| resume=None \| get={} \| cookies=True \| disposition=True \| chunks=None \| post={} \| ref=True
241 | 31.12.2017 18:03:28 | INFO | HOSTER ZippyshareCom[8363]: File saved
242 | 31.12.2017 18:03:28 | INFO | HOSTER ZippyshareCom[8363]: Checking download...
243 | 31.12.2017 18:03:28 | INFO | HOSTER ZippyshareCom[8363]: File is OK
244 | 31.12.2017 18:03:28 | INFO | HOSTER ZippyshareCom[8363]: Checking file (with built-in rules)...
245 | 31.12.2017 18:03:28 | INFO | HOSTER ZippyshareCom[8363]: Checking file (with custom rules)...
246 | 31.12.2017 18:03:28 | INFO | HOSTER ZippyshareCom[8363]: Checking for link errors...
247 | 31.12.2017 18:03:28 | INFO | HOSTER ZippyshareCom[8363]: No errors found
248 | 31.12.2017 18:03:28 | INFO | HOSTER ZippyshareCom[8363]: No errors found
249 | 31.12.2017 18:03:28 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
250 | 31.12.2017 18:03:28 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
251 | 31.12.2017 18:03:28 | INFO | Download finished: 5retemsunimsulp.02.part13.rar (2) (2)
252 | 31.12.2017 18:03:28 | DEBUG | ADDON ExternalScripts: No script found under folder `download_finished`
253 | 31.12.2017 18:03:28 | INFO | Package finished: zzz
254 | 31.12.2017 18:03:28 | DEBUG | ADDON ExternalScripts: No script found under folder `package_finished`
255 | 31.12.2017 18:03:28 | DEBUG | ADDON ExtractArchive: Use for extensions: .7z\|.bz2\|.bzip2\|.gz\|.gzip\|.lha\|.lzh\|.lzma\|.rar\|.tar\|.taz\|.tbz\|.tbz2\|.tgz\|.xar\|.xz\|.z\|.zip
256 | 31.12.2017 18:03:28 | INFO | ADDON ExtractArchive: Check package: zzz
257 | 31.12.2017 18:03:28 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
258 | 31.12.2017 18:03:28 | INFO | ADDON ExtractArchive: No files found to extract
259 | 31.12.2017 18:03:28 | DEBUG | All downloads processed
260 | 31.12.2017 18:03:28 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_finished`
261 | 31.12.2017 18:03:28 | DEBUG | All downloads finished

**Comment by GammaC0de** [comment]
OK, can you check  the file `5retemsunimsulp.02.part13.rar (2) (2)`?

**Comment by oltodosel** [comment]
Still the same html file with 404.

**Comment by GammaC0de** [comment]
can you post the file?

**Comment by oltodosel** [comment]
`<html><head><title>Apache Tomcat/7.0.32 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /Picked%20up%20_JAVA_OPTIONS:%20-Dawt.useSystemAAFontSettings=on%20-Dswing.aatext=true%20-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel%20-Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel%20%0A/d/tt2WZimS/30448/5retemsunimsulp.02.part13.rar</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/Picked%20up%20_JAVA_OPTIONS:%20-Dawt.useSystemAAFontSettings=on%20-Dswing.aatext=true%20-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel%20-Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel%20%0A/d/tt2WZimS/30448/5retemsunimsulp.02.part13.rar</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.32</h3></body></html>`

**Comment by oltodosel** [comment]
My bad. After looking closer at html I see that the problem was because of my Java options at .bashrc
