### ISSUE TITLE
Problem with installation (raspbian Jessie or Raspian stretch)

### ISSUE THREAD

**Issue by jbo82** [pyload/pyload#3065]
Hi guys,

Since this morning I try to install Pyload on my raspberry but I can't. One precision : I tried with raspbian Jessie an Rapsbian Strectch. I think that my problem comes from Jinja2. I post the  system chek.

----------------------
## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: OK

py-imaging: OK
tesseract: OK

PyQt4: missing

Your installed jinja2 version 2.7.3 seems too old.
You can safely continue but if the webinterface is not working,
please upgrade or deinstall it, pyLoad includes a sufficient jinja2 libary.

jinja2: missing
beaker: OK
JS engine: missing

System check finished, hit enter to see your status report.

## Status ##

Features available: container decrypting, ssl connection, automatic captcha decryption, Webinterface

Featues missing: 

Gui not available
The Graphical User Interface.

no JavaScript engine found
You will need this for some Click'N'Load links. Install Spidermonkey, ossp-js, pyv8 or rhino
You can abort the setup now and fix some dependicies if you want.

----------------

As you can see Jinja2 is missing. I have this problem with the two versions of rapsbian.

When I make the command "pip list" I have got : 

-----------------------
argparse (1.2.1)
blinker (1.3)
chardet (2.3.0)
colorama (0.3.2)
Flask (0.10.1)
gpiozero (1.4.0)
html5lib (0.999)
itsdangerous (0.24)
Jinja2 (2.7.3)
lxkeymap (0.1)
MarkupSafe (0.23)
mcpi (0.1.1)
ndg-httpsclient (0.3.2)
numpy (1.8.2)
picamera (1.13)
picraft (1.0)
pifacecommon (4.2.1)
pifacedigitalio (3.1.0)
pigpio (1.35)
Pillow (2.6.1)
pip (1.5.6)
pyasn1 (0.1.7)
pycrypto (2.6.1)
pycurl (7.19.5)
pygame (1.9.2a0)
pygobject (3.14.0)
pyinotify (0.9.4)
pyOpenSSL (0.13.1)
pyserial (2.6)
python-apt (0.9.3.12)
requests (2.4.3)
RPi.GPIO (0.6.3)
RTIMULib (7.2.1)
sense-emu (1.0)
sense-hat (2.2.0)
setuptools (5.5.1)
six (1.8.0)
smbus (1.1)
spidev (3.0)
twython (3.1.2)
urllib3 (1.9.1)
Werkzeug (0.9.6)
wheel (0.24.0)
wsgiref (0.1.2)
---------------------------------------

That is confirmed that Jinja2 is installed. I updated Jinja2. I was in version jinja2 2.8 and after 2.10. The problem is always here.

If someone could help me.

Thanks.

**Comment by GammaC0de** [comment]
See https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi)

**Comment by jbo82** [comment]
I allready tried. In fact, I followed that instructions step by step

**Comment by GammaC0de** [comment]
I suggest you "pip uninstall Jinja2" because pyload is bundled with an older version of it, and the newer version is not backward compatible.

also:
> I try to install Pyload on my raspberry but I can't

You did not said what symptoms do you have..

**Comment by jbo82** [comment]
I allready tried to uninstall Jinja2 with this comand line. I had an exception : 

 -------------------------
Not uninstalling Jinja2 at /usr/lib/python2.7/dist-packages, owned by OS
----------------------------

The symptom is that in the system check I have : 

------------
Gui not available
The Graphical User Interface.
-------------

and when I tried to acces at the web interface with my browser, I could not

**Comment by GammaC0de** [comment]
>Gui not available

This is normal.
GUI is for using pyload as a windows app which is not what you want.

try  running `pyLoadCore.py -s`, what do you get?

**Comment by GammaC0de** [comment]
Any news on this?

**Comment by jbo82** [comment]
Hi,

I tried and the result is  

---------------------------------
 
sudo -u pyload python pyLoadCore.py -s
Choose your Language / Wähle deine Sprache ([en], de, fr, it, es, nl, sv, ru, pl, cs, sr, pt_BR): 

Welcome to the pyLoad Configuration Assistent.
It will check your system and make a basic setup in order to run pyLoad.

The value in brackets [] always is the default value,
in case you don't want to change it or you are unsure what to choose, just hit enter.
Don't forget: You can always rerun this assistent with --setup or -s parameter, when you start pyLoadCore.
If you have any problems with this assistent hit STRG-C,
to abort and don't let him start with pyLoadCore automatically anymore.

When you are ready for system check, hit enter.

## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: OK

py-imaging: OK
tesseract: OK

PyQt4: missing

Your installed jinja2 version 2.7.3 seems too old.
You can safely continue but if the webinterface is not working,
please upgrade or deinstall it, pyLoad includes a sufficient jinja2 libary.

jinja2: missing
beaker: OK
JS engine: missing

System check finished, hit enter to see your status report.

no JavaScript engine found
You will need this for some Click'N'Load links. Install Spidermonkey, ossp-js, pyv8 or rhino
You can abort the setup now and fix some dependicies if you want.

---------------------------------

It's good for you, you think ?

**Comment by GammaC0de** [comment]
All except jinja and JS.

- For jinja2 please try `sudo pip uninstall` (notice the sudo command).
- For JS:
```
sudo apt-get install libmozjs-24-bin
cd /usr/bin
ln -s js24 js
```

**Comment by GammaC0de** [comment]
No response, closing.
