### ISSUE TITLE
get ERR_EMPTY_RESPONSE from Chrome or other when i try to connect to pylooad

### ISSUE THREAD

**Issue by Rascarcasimor** [pyload/pyload#3066]
Hi 
since several days i can't connect anymore to pyload on my POCORN A-410
browsers tell me 192.168.0.38:8000 didn't send any data ERR_EMPTY_RESPONSE 
i tried to reinstall pyload but nothing to do
any suggestion
Thanks
David

**Comment by GammaC0de** [comment]
So if I understand correctly, you have reinstalled pyload, 
How did you reinstalled?

**Comment by GammaC0de** [comment]
opkg means with the package from entware-ng?

**Comment by Rascarcasimor** [comment]
Don t know where can I find this info?Download opkg through the csi installer from the media player popcorn A 410


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: GammaC0de <notifications@github.com> Data: 18/01/18  15:11  (GMT+01:00) A: pyload/pyload <pyload@noreply.github.com> Cc: Rascarcasimor <david.spam.75@gmail.com>, Author <author@noreply.github.com> Oggetto: Re: [pyload/pyload] get ERR_EMPTY_RESPONSE from Chrome or other when i try to connect to pylooad (#3066) 
opkg means with the package from entware-ng?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pyload/pyload","title":"pyload/pyload","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pyload/pyload"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GammaC0de in #3066: opkg means with the package from entware-ng?"}],"action":{"name":"View Issue","url":"https://github.com/pyload/pyload/issues/3066#issuecomment-358657780"}}}

**Comment by GammaC0de** [comment]
first you used csi installer to install opkg and then you used opkg to install pyload?

**Comment by Rascarcasimor** [comment]
Exactly and everything was running perfectly since few daysAll browser can t connect to port 8000 


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: GammaC0de <notifications@github.com> Data: 18/01/18  15:54  (GMT+01:00) A: pyload/pyload <pyload@noreply.github.com> Cc: Rascarcasimor <david.spam.75@gmail.com>, Author <author@noreply.github.com> Oggetto: Re: [pyload/pyload] get ERR_EMPTY_RESPONSE from Chrome or other when i try to connect to pylooad (#3066) 
first you used csi installer to install opkg and then you used opkg to install pyload?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pyload/pyload","title":"pyload/pyload","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pyload/pyload"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GammaC0de in #3066: first you used csi installer to install opkg and then you used opkg to install pyload?"}],"action":{"name":"View Issue","url":"https://github.com/pyload/pyload/issues/3066#issuecomment-358670375"}}}

**Comment by GammaC0de** [comment]
what is the output of: 
`find / -name "pyload.conf"`

and:
`find / -name "pyLoadCore.py"`
?

**Comment by GammaC0de** [comment]
Any news on this?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by Rascarcasimor** [comment]
Hello Sorry i was abroad for professionnal reason with no connection 
here is the output for pyload.conf
version: 1 

remote - "Remote":
	bool nolocalauth : "No authentication on local connections" = True
	bool activated : "Activated" = True
	int port : "Port" = 7227
	ip listenaddr : "Adress" = 0.0.0.0

log - "Log":
	int log_size : "Size in kb" = 100
	folder log_folder : "Folder" = Logs
	bool file_log : "File Log" = True
	int log_count : "Count" = 5
	bool log_rotate : "Log Rotate" = True

permission - "Permissions":
	str group : "Groupname" = users
	bool change_dl : "Change Group and User of Downloads" = False
	bool change_file : "Change file mode of downloads" = False
	str user : "Username" = user
	str file : "Filemode for Downloads" = 0644
	bool change_group : "Change group of running process" = False
	str folder : "Folder Permission mode" = 0755
	bool change_user : "Change user of running process" = False

general - "General":
	en;de;fr;it;es;nl;sv;ru;pl;cs;sr;pt_BR language : "Language" = en
	folder download_folder : "Download Folder" = /share/Download
	bool checksum : "Use Checksum" = False
	bool folder_per_package : "Create folder for each package" = True
	bool debug_mode : "Debug Mode" = False
	int min_free_space : "Min Free Space (MB)" = 200
	int renice : "CPU Priority" = 0

ssl - "SSL":
	file cert : "SSL Certificate" = ssl.crt
	bool activated : "Activated" = False
	file key : "SSL Key" = ssl.key

webinterface - "Webinterface":
	str template : "Template" = default
	bool activated : "Activated" = True
	str prefix : "Path Prefix" = 
	builtin;threaded;fastcgi;lightweight server : "Server" = builtin
	ip host : "IP" = 0.0.0.0
	bool https : "Use HTTPS" = False
	int port : "Port" = 8000

proxy - "Proxy":
	str username : "Username" = None
	bool proxy : "Use Proxy" = False
	str address : "Address" = "localhost"
	password password : "Password" = None
	http;socks4;socks5 type : "Protocol" = http
	int port : "Port" = 7070

reconnect - "Reconnect":
	time endTime : "End" = 0:00
	bool activated : "Use Reconnect" = False
	str method : "Method" = None
	time startTime : "Start" = 0:00

download - "Download":
	int max_downloads : "Max Parallel Downloads" = 3
	bool limit_speed : "Limit Download Speed" = False
	str interface : "Download interface to bind (ip or Name)" = None
	bool skip_existing : "Skip already existing files" = False
	int max_speed : "Max Download Speed in kb/s" = -1
	bool ipv6 : "Allow IPv6" = False
	int chunks : "Max connections for one download" = 3

downloadTime - "Download Time":
	time start : "Start" = 0:00
	time end : "End" = 0:00


and pyloadcore.py can't be find (????!!!!)

**Comment by GammaC0de** [comment]
Try changing `default` to `classic`:
```
webinterface - "Webinterface":
str template : "Template" = default
```

**Comment by Rascarcasimor** [comment]
Done !
nothing successful but
Since last week now I have ERR_CONNECTION REFUSED instead of ERR_EMPTY_RESPONSE (!!!!??) is there a subtility ?

**Comment by Rascarcasimor** [comment]
It seems my pyload install is not good anymore 
I try to reinstall it via opkg but I miss files like pyloadcore
Think my problem is coming from my media player PCH A410

**Comment by GammaC0de** [comment]
So you want to close this issue?

**Comment by Rascarcasimor** [comment]
Yes think so
Thanks mate 
David

**Comment by GammaC0de** [comment]
👍
