### ISSUE TITLE
improve package with multible hoster

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#3067]
Hello.
First of all, I don't know what topic i have to seach for. So sorry if i'm opening a duplicate.

If i'm starting a package (multipart) consisting the same filenames (e.g.: ***.part1.rar) from differnt hoster (call them A and B)  the package is starting to download the same file from hoster A and B.
Is there a possibility to get rid of loading the same file again? The 'file-exists-check' only recognizes completed files (***.part1.rar) but not if there are already existing chunkfiles (***.part1.rar.chunks or ***.part1.rar.chunks0) in package path.

Only for completion: I'm running those packages as free-user and would minimize unnecesary waiting time.
Thanks!

**Comment by GammaC0de** [comment]
I think you are referring to same issue as https://github.com/pyload/pyload/issues/3033.
See https://github.com/pyload/pyload/issues/3033#issuecomment-349533885 and please tell me if that helps.

Also, I would be glad if you can send me such a DLC file (preferably with not many  multi-part files).

**Comment by GammaC0de** [comment]
Any news about this?

**Comment by UserX404** [comment]
Yes! After testing the other Hoster.py for 1 day I can report the bug seems to be fixed.
No more double-downloads.
Thanks!
