### ISSUE TITLE
PremiumizeMe deactivating

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#3070]
Hello!
Had a PremiumizeMe account in the past but isn't loger active.
I deleted my account at 'accounts', restarted pyload, but it still tries to load per PremiumizeMe.

**plugin.conf:**
### PremiumizeMe - "PremiumizeMe":
        str mh_list : "Hoster list (comma separated)" =
        all;listed;unlisted mh_mode : "Filter hosters to use" = listed
        int mh_interval : "Reload interval in hours" = 60
### OboomCom - "OboomCom":
        bool activated : "Activated" = True

i'm wondering about lines 1794, 3012 and 2986 in log.
OboomCom is loaded and how can i get rid of the default option `use_premium` not found, use default `True`?
Is there a possibility to deactivate premium anywhere?

I have this problem with OBoom only. Oher hosters ar not affected.

1794 | 22.01.2018 18:34:51 | DEBUG | Redirected import module.plugins.hoster.OboomCom -> userplugins.hoster.OboomCom
-- | -- | -- | --

...

77 | 22.01.2018 18:36:54 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: S0KXSMdoV4E (pid:1901)
-- | -- | -- | --
2978 | 22.01.2018 18:36:54 | INFO | ADDON UnSkipOnFail: No duplicates found
2979 | 22.01.2018 18:36:56 | INFO | Download starts: SlQRgGJZWyM
2980 | 22.01.2018 18:36:56 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
-- | -- | -- | --
2981 | 22.01.2018 18:36:56 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
2982 | 22.01.2018 18:36:56 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0  (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
2983 | 22.01.2018 18:36:56 | DEBUG | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Plugin version: 0.31
2984 | 22.01.2018 18:36:56 | DEBUG | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Plugin status: testing
2985 | 22.01.2018 18:36:56 | WARNING | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Plugin may be unstable
2986 | 22.01.2018 18:36:56 | DEBUG | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Config option `use_premium` not found, use default `True`
2987 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Grabbing link info...
2988 | 22.01.2018 18:36:56 | DEBUG | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Link info: {'status': 7,  'hash': {}, 'name': 'SlQRgGJZWyM', 'url':  u'https://openload.co/f/SlQRgGJZWyM', 'pattern': {}, 'size': 0}
2989 | 22.01.2018 18:36:56 | DEBUG | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Previous link info: {}
2990 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Link name: SlQRgGJZWyM
2991 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Link size: N/D
2992 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Link status: starte
2993 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Processing url: https://openload.co/f/SlQRgGJZWyM
2994 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Looking for direct download link...
2995 | 22.01.2018 18:36:56 | DEBUG | HOSTER PremiumizeMe[19133]: PremiumizeMe \| LOAD URL  https://openload.co/f/SlQRgGJZWyM \| redirect=True \| cookies=True \|  get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \|  just_header=True
2996 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Direct download link not found
2997 | 22.01.2018 18:36:56 | DEBUG | HOSTER PremiumizeMe[19133]: PremiumizeMe \| LOAD URL  https://openload.co/f/SlQRgGJZWyM \| redirect=True \| cookies=True \|  get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \|  just_header=False
2998 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Checking for link errors...
2999 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| No errors found
3000 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Grabbing link info...
3001 | 22.01.2018 18:36:56 | DEBUG | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Link info: {'status': 7,  'hash': {}, 'name': 'SlQRgGJZWyM', 'url':  u'https://openload.co/f/SlQRgGJZWyM', 'pattern': {}, 'size': 0}
3002 | 22.01.2018 18:36:56 | DEBUG | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Previous link info:  {'status': 7, 'hash': {}, 'name': 'SlQRgGJZWyM', 'url':  u'https://openload.co/f/SlQRgGJZWyM', 'pattern': {}, 'size': 0}
3003 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Link name: SlQRgGJZWyM
3004 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Link size: N/D
3005 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Link status: starte
3006 | 22.01.2018 18:36:56 | INFO | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Processing as free download...
3007 | 22.01.2018 18:36:56 | WARNING | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Free download failed \| MultiHoster download failed
3008 | 22.01.2018 18:36:56 | DEBUG | HOSTER PremiumizeMe[19133]: PremiumizeMe \| Config option `revert_failed` not found, use default `True`
3009 | 22.01.2018 18:36:56 | WARNING | Download failed: SlQRgGJZWyM \| MultiHoster download failed
3010 | 22.01.2018 18:36:56 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: SlQRgGJZWyM (pid:1901)
3011 | 22.01.2018 18:36:56 | INFO | ADDON UnSkipOnFail: No duplicates found
3012 | 22.01.2018 18:38:32 | DEBUG | Plugin OboomCom not found
3013 | 22.01.2018 18:38:32 | DEBUG | Available plugins : {'LinkdecrypterComHook': {'user': True, 'name':  'LinkdecrypterComHook', 'v': 1.1100000000000001}, 'XMPP': {'user': True,  'name': 'XMPP', 'v': 0.17999999999999999}, 'PushOver': {'user': True,  'name': 'PushOver', 'v': 0.070000000000000007}, 'LinkFilter': {'user':  True, 'name': 'LinkFilter', 'v': 0.16}, 'AntiVirus': {'user': True,  'name': 'AntiVirus', 'v': 0.20999999999999999}, 'UpdateManager':  {'module': , 'user': True, 'name': 'UpdateManager', 'v': 1.2}, 'MergeFiles': {'module': ,  'user': True, 'name': 'MergeFiles', 'v': 0.22}, 'ImageTyperz': {'user':  True, 'name': 'ImageTyperz', 'v': 0.14000000000000001},  'DeleteFinished': {'user': True, 'name': 'DeleteFinished', 'v':  1.1899999999999999}, 'DeathByCaptcha': {'user': True, 'name':  'DeathByCaptcha', 'v': 0.14999999999999999}, 'RestartFailed': {'user':  True, 'name': 'RestartFailed', 'v': 1.6499999999999999}, 'EventMapper':  {'module': ,  'user': True, 'name': 'EventMapper', 'v': 0.02}, 'BypassCaptcha':  {'user': True, 'name': 'BypassCaptcha', 'v': 0.13}, 'ExternalScripts':  {'user': True, 'name': 'ExternalScripts', 'v': 0.72999999999999998},  'Captcha9Kw': {'module': ,  'user': True, 'name': 'Captcha9Kw', 'v': 0.38}, 'AntiStandby': {'user':  True, 'name': 'AntiStandby', 'v': 0.17999999999999999},  'WindowsPhoneNotify': {'user': True, 'name': 'WindowsPhoneNotify', 'v':  0.17999999999999999}, 'UnSkipOnFail': {'module': ,  'user': True, 'name': 'UnSkipOnFail', 'v': 0.14000000000000001},  'DownloadScheduler': {'user': True, 'name': 'DownloadScheduler', 'v':  0.29999999999999999}, 'HotFolder': {'user': True, 'name': 'HotFolder',  'v': 0.23999999999999999}, 'Checksum': {'module': , 'user': True, 'name': 'Checksum', 'v': 0.34000000000000002}, 'ExtractArchive': {'module': ,  'user': True, 'name': 'ExtractArchive', 'v': 1.6599999999999999},  'LogMarker': {'user': True, 'name': 'LogMarker', 'v':  0.080000000000000002}, 'TransmissionRPC': {'user': True, 'name':  'TransmissionRPC', 'v': 0.19}, 'AndroidPhoneNotify': {'user': True,  'name': 'AndroidPhoneNotify', 'v': 0.16}, 'CloudFlareDdos': {'user':  True, 'name': 'CloudFlareDdos', 'v': 0.13}, 'IRC': {'user': True,  'name': 'IRC', 'v': 0.25}, 'JustPremium': {'user': True, 'name':  'JustPremium', 'v': 0.27000000000000002}, 'MultiHome': {'user': True,  'name': 'MultiHome', 'v': 0.20999999999999999}, 'XFileSharing':  {'module': ,  'user': True, 'name': 'XFileSharing', 'v': 0.56000000000000005},  'CaptchaBrotherhood': {'user': True, 'name': 'CaptchaBrotherhood', 'v':  0.14999999999999999}, 'ExpertDecoders': {'user': True, 'name':  'ExpertDecoders', 'v': 0.11}, 'ClickNLoad': {'module': ,  'user': True, 'name': 'ClickNLoad', 'v': 0.60999999999999999},  'PushBullet': {'user': True, 'name': 'PushBullet', 'v':  0.050000000000000003}, 'UserAgentSwitcher': {'module': ,  'user': True, 'name': 'UserAgentSwitcher', 'v': 0.16},  'DiscordNotifier': {'user': True, 'name': 'DiscordNotifier', 'v':  0.10000000000000001}, 'SkipRev': {'user': True, 'name': 'SkipRev', 'v':  0.38}}

**Comment by GammaC0de** [comment]
Stop pyload and then edit accounts.conf removing PremiumizeMe  info,.
Also I think you have to remove the OboomCom links and then re-add them.

**Comment by UserX404** [comment]
thx for support
issue can be closed

**Comment by GammaC0de** [comment]
👍
