### ISSUE TITLE
Download failed: UptoBox

### ISSUE THREAD

**Issue by regpa** [pyload/pyload#3071]
Hello
download via browser is working fine 
with pyload, i get repeatedly this log and the download stops at start
would you have some idea on how to fix this ?

note: all actual readable startings are replace by "blabla" in this posted log 

```
DEBUG	ACCOUNT UptoboxCom: LOAD URL http://uptobox.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
DEBUG	ACCOUNT UptoboxCom: VALID UNTIL PATTERN not found
DEBUG	ACCOUNT UptoboxCom: TRAFFIC LEFT PATTERN not found
DEBUG	ACCOUNT UptoboxCom: LEECH TRAFFIC PATTERN not found
DEBUG	ACCOUNT UptoboxCom: Account info for user `???*******`: {'login': {'timestamp': 1516659002.724557, 'password': '???*******????', 'valid': True}, 'data': {'premium': False, 'plugin': , 'leechtraffic': None, 'trafficleft': None, 'maxtraffic': None, 'validuntil': None, 'login': 'erd*******', 'type': 'UptoboxCom', 'options': {'limitdl': '0'}}}
INFO	HOSTER UptoboxCom[1]: Grabbing link info...
DEBUG	HOSTER UptoboxCom[1]: Link info: {'status': 2, 'hash': {}, 'name': u'blabla', 'url': u'http:/blabla', 'pattern': {'S': u'2.2', 'U': u'GB', 'N': u'blabla'}, 'error': u'28 minutes, 43 seconds', 'size': 2362232012L}
DEBUG	HOSTER UptoboxCom[1]: Previous link info: {'status': 2, 'hash': {}, 'name': u'blabla', 'error': u'28 minutes, 43 seconds', 'url': u'blabla', 'pattern': {'S': u'2.2', 'U': u'GB', 'N': u'blabla'}, 'size': 2362232012L}
INFO	HOSTER UptoboxCom[1]: Link name: blabla
INFO	HOSTER UptoboxCom[1]: Link size: 2.20 GiB (2362232012 bytes)
INFO	HOSTER UptoboxCom[1]: Link status: online
INFO	HOSTER UptoboxCom[1]: Processing url: blabla
DEBUG	HOSTER UptoboxCom[1]: LOAD URL http://blabla | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
INFO	HOSTER UptoboxCom[1]: Checking for link errors...
INFO	HOSTER UptoboxCom[1]: No errors found
INFO	HOSTER UptoboxCom[1]: Processing as free download...
DEBUG	HOSTER UptoboxCom[1]: Getting download link #1...
INFO	HOSTER UptoboxCom[1]: Checking for link errors...
INFO	HOSTER UptoboxCom[1]: No errors found
DEBUG	HOSTER UptoboxCom[1]: {u'rand': u'blabla', u'file_size_real': u'2414468877', u'method_premium': '', u'down_direct': u'1', u'referer': '', u'fname': u'blabla', u'method_free': '', u'id': u'f9n523mcw8xn', u'op': u'download2'}
WARNING	CAPTCHA UptoboxCom[1]: ReCaptcha | Key pattern not found
DEBUG	CAPTCHA UptoboxCom[1]: SolveMedia | Key pattern not found
DEBUG	HOSTER UptoboxCom[1]: LOAD URL http://blabla | redirect=False | cookies=True | get={} | req=None | decode=True | multipart=False | post={u'rand': u'wjaecfa6mlkyft6wfufcy76evochqrwjlqmftxq', u'file_size_real': u'2414468877', u'down_direct': u'1', u'referer': u'http://blabla', u'fname': u'blabla', u'method_free': 'Free Download', u'id': u'f9n523mcw8xn', u'op': u'download2'} | ref=True | just_header=False
INFO	HOSTER UptoboxCom[1]: Downloading file...
DEBUG	HOSTER UptoboxCom[1]: DOWNLOAD URL http://www60.blabla | fixurl=True | resume=None | get={} | cookies=True | disposition=True | chunks=None | post={} | ref=True
WARNING	HOSTER UptoboxCom[1]: Free download failed | downloading
DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
WARNING	Download failed: blabla | downloading
INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: blabla (pid:1)
INFO	ADDON UnSkipOnFail: No duplicates found
DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
DEBUG	All downloads `processed
```

**Comment by GammaC0de** [comment]
I see that you have a premium account, right?

So:
Account information is needed for testing, please set to a temporary password and then send sample URL and account user and password to nitzo2001 at yahoo dot com.

**Comment by regpa** [comment]
Thanks for your immediate response @GammaC0de, I have also tested after having deleted my account (so the download waiting time increased up to 1h30) and ... the result and the log are unfortunately unchanged, so I believe that the root cause isn't that much linked to the account credentials.
To your view, there is something I could to better narrow down the issue cause ?

I don't want to bother you too much, I you see nothing I will will for a total re-install

**Comment by GammaC0de** [comment]
There seems to be two problems:
1. The account plugin is not working - for that I will need account info.
2. The hoster plugin in not working also, - for that I will need a sample URL.

So, if you don't want to fix the account plugin, at least send a sample URL..

**Comment by GammaC0de** [comment]
I tested the link you have sent and it works fine for me,
I suggest you stop pyload and then start it with `-d` command line switch (`pyLoadCore.py -d`), retry the download and then post the (debug) log here.

**Comment by GammaC0de** [comment]
Any update?

**Comment by Asmolet** [comment]
I have the same pb...
I start Pyload with the command `pyLoadCore.py -d` : 

`21.02.2018 22:52:22 INFO      Debug Report written to debug_UptoboxCom_21-02-2018_22-52-16.zip
21.02.2018 22:52:22 INFO      UnSkipOnFail: Looking for skipped duplicates of: https://uptobox.com/bd7n36of0343 (pid:1373)
21.02.2018 22:52:26 INFO      UnSkipOnFail: No duplicates found
21.02.2018 22:52:29 INFO      Download starts: bis1llybw8b2
21.02.2018 22:52:30 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:52:30 DEBUG     UptoboxCom: Previous file info: {}
21.02.2018 22:52:57 DEBUG     pycurl exception 28: SSL connection timeout
21.02.2018 22:52:57 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
21.02.2018 22:53:20 DEBUG     pycurl exception 28: SSL connection timeout
21.02.2018 22:53:21 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
21.02.2018 22:53:22 DEBUG     pycurl exception 28: SSL connection timeout
21.02.2018 22:53:22 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
21.02.2018 22:53:23 DEBUG     pycurl exception 28: SSL connection timeout
21.02.2018 22:53:23 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
21.02.2018 22:53:33 DEBUG     pycurl exception 28: SSL connection timeout
21.02.2018 22:53:33 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
21.02.2018 22:53:35 DEBUG     pycurl exception 28: SSL connection timeout
21.02.2018 22:53:35 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
21.02.2018 22:53:36 DEBUG     pycurl exception 28: SSL connection timeout
21.02.2018 22:53:36 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
21.02.2018 22:53:37 DEBUG     pycurl exception 28: SSL connection timeout
21.02.2018 22:53:37 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
21.02.2018 22:53:37 DEBUG     pycurl exception 28: SSL connection timeout
21.02.2018 22:53:38 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
21.02.2018 22:53:38 DEBUG     pycurl exception 28: SSL connection timeout
21.02.2018 22:53:38 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
21.02.2018 22:53:58 INFO      Download starts: https://uptobox.com/mjbmicu4rvuk
21.02.2018 22:53:58 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:53:58 DEBUG     UptoboxCom: Previous file info: {}
21.02.2018 22:54:09 DEBUG     UptoboxCom: Current file info: {'status': 3, 'url': u'https://uptobox.com/mjbmicu4rvuk', 'name': u'mjbmicu4rvuk', 'size': 0}
21.02.2018 22:54:09 DEBUG     UptoboxCom: File name: mjbmicu4rvuk | File size: Unknown
21.02.2018 22:54:09 DEBUG     UptoboxCom: File status: queued
21.02.2018 22:54:15 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:54:15 DEBUG     UptoboxCom: Previous file info: {'status': 3, 'url': u'https://uptobox.com/mjbmicu4rvuk', 'name': u'mjbmicu4rvuk', 'size': 0}
21.02.2018 22:54:15 DEBUG     UptoboxCom: Current file info: {'status': 3, 'name': u'mjbmicu4rvuk', 'url': u'https://uptobox.com/mjbmicu4rvuk', 'size': 0}
21.02.2018 22:54:15 DEBUG     UptoboxCom: File name: mjbmicu4rvuk | File size: Unknown
21.02.2018 22:54:15 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:54:15 DEBUG     UptoboxCom: Previous file info: {'status': 3, 'name': u'mjbmicu4rvuk', 'url': u'https://uptobox.com/mjbmicu4rvuk', 'size': 0}
21.02.2018 22:54:15 DEBUG     UptoboxCom: Current file info: {'status': 3, 'name': u'mjbmicu4rvuk', 'url': u'https://uptobox.com/mjbmicu4rvuk', 'size': 0}
21.02.2018 22:54:16 DEBUG     UptoboxCom: File name: mjbmicu4rvuk | File size: Unknown
21.02.2018 22:54:16 DEBUG     UptoboxCom: File status: queued
21.02.2018 22:54:16 DEBUG     UptoboxCom: Handled as free download
21.02.2018 22:54:16 DEBUG     UptoboxCom: Getting download link: #1
21.02.2018 22:54:16 WARNING   Download failed: mjbmicu4rvuk | Parse error: TEXTAREA F1 not found | Plugin may be out of date
21.02.2018 22:54:16 INFO      UnSkipOnFail: Looking for skipped duplicates of: mjbmicu4rvuk (pid:1373)
21.02.2018 22:54:16 INFO      UnSkipOnFail: No duplicates found
21.02.2018 22:54:21 INFO      Download starts: https://uptobox.com/qo45jb3de7td
21.02.2018 22:54:21 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:54:21 DEBUG     UptoboxCom: Previous file info: {}
21.02.2018 22:54:23 INFO      Download starts: https://uptobox.com/pleoqxuhc61p
21.02.2018 22:54:23 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:54:23 DEBUG     UptoboxCom: Previous file info: {}
21.02.2018 22:54:24 INFO      Download starts: https://uptobox.com/ra535kw7btdm
21.02.2018 22:54:24 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:54:24 DEBUG     UptoboxCom: Previous file info: {}
21.02.2018 22:54:33 INFO      Download starts: doc42ol2pme5
21.02.2018 22:54:33 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:54:34 DEBUG     UptoboxCom: Previous file info: {}
21.02.2018 22:54:36 INFO      Download starts: https://uptobox.com/wlefiupfs51s
21.02.2018 22:54:36 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:54:36 DEBUG     UptoboxCom: Previous file info: {}
21.02.2018 22:54:37 INFO      Download starts: 3vppkdwm6kxq
21.02.2018 22:54:37 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:54:37 DEBUG     UptoboxCom: Previous file info: {}
21.02.2018 22:54:37 INFO      Download starts: es3o9od20oir
21.02.2018 22:54:38 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:54:38 INFO      Download starts: fcgzep8sd4m3
21.02.2018 22:54:38 DEBUG     UptoboxCom: Previous file info: {}
21.02.2018 22:54:38 DEBUG     UptoboxCom: Update file info...
21.02.2018 22:54:38 DEBUG     UptoboxCom: Previous file info: {}
21.02.2018 22:54:39 DEBUG     pycurl exception 35: gnutls_handshake() failed: A TLS packet with unexpected length was received.
21.02.2018 22:54:39 INFO      Download starts: bis1llybw8b2
21.02.2018 22:54:39 ERROR     pycurl error 35: gnutls_handshake() failed: A TLS packet with unexpected length was received.
21.02.2018 22:54:39 DEBUG     UptoboxCom: Update file info...
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/usr/share/pyload/module/plugins/Plugin.py", line 237, in preprocessing
    return self.process(self.pyfile)
  File "/home/pi/.pyload/userplugins/internal/SimpleHoster.py", line 460, in process
    self.checkInfo()
  File "/home/pi/.pyload/userplugins/internal/SimpleHoster.py", line 606, in checkInfo
    self.checkNameSize()
  File "/home/pi/.pyload/userplugins/internal/SimpleHoster.py", line 581, in checkNameSize
    self.info.update(self.getInfo(self.pyfile.url, self.html))
  File "/home/pi/.pyload/userplugins/internal/SimpleHoster.py", line 352, in getInfo
    elif info['status'] is 3 and not fileUrl(None, url):
  File "/home/pi/.pyload/userplugins/internal/SimpleHoster.py", line 160, in fileUrl
    res = req.load(url, cookies=True, just_header=True, decode=True)
21.02.2018 22:54:39 DEBUG     UptoboxCom: Previous file info: {}
  File "/usr/share/pyload/module/network/HTTPRequest.py", line 195, in load
    self.c.perform()
error: (35, 'gnutls_handshake() failed: A TLS packet with unexpected length was received.')
21.02.2018 22:54:46 INFO      Debug Report written to debug_UptoboxCom_21-02-2018_22-54-39.zip
21.02.2018 22:54:47 INFO      UnSkipOnFail: Looking for skipped duplicates of: https://uptobox.com/qo45jb3de7td (pid:1373)
21.02.2018 22:54:51 INFO      UnSkipOnFail: No duplicates found
21.02.2018 22:55:04 DEBUG     pycurl exception 28: SSL connection timeout
21.02.2018 22:55:05 WARNING   Couldn't connect to host or connection reset, waiting 1 minute and retry.
...`

**Comment by GammaC0de** [comment]
@Asmolet Your plugin is not up to date, you should use plugin version 0.33.

**Comment by Asmolet** [comment]
Thanks. How can i update my plugin ?

**Comment by GammaC0de** [comment]
Please read  #2994

**Comment by Asmolet** [comment]
Yes i download and replace updatemanager.py but i have this message : 

>26.02.2018 20:13:49 | INFO | Démarrage pyLoad 0.4.9
26.02.2018 20:13:49 | INFO | Utilisation du dossier principal : /home/pi/.pyload
**26.02.2018 20:14:40 | ERROR | Erreur d'importation UpdateManager : invalid syntax (UpdateManager.py, line 30)**
26.02.2018 20:14:40 | INFO | Plugins activés: BypassCaptcha, Captcha9Kw, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, RestartFailed, UnSkipOnFail, XFileSharingPro
26.02.2018 20:14:40 | INFO | Plugins désactivés: AlldebridCom, AndroidPhoneNotify, CaptchaBrotherhood, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, FastixRu, FreeWayMe, HotFolder, IRCInterface, JustPremium, LinkdecrypterCom, LinksnappyCom, MegaDebridEu, MergeFiles, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumTo, PremiumizeMe, PutdriveCom, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, SmoozedCom, UnrestrictLi, WindowsPhoneNotify, XMPPInterface, ZeveraCom
26.02.2018 20:14:40 | INFO | Temps de téléchargement : True

**Comment by GammaC0de** [comment]
You should download https://raw.githubusercontent.com/pyload/pyload/353c6692afdec4b6108555725cb5db46d02ed816/module/plugins/hooks/UpdateManager.py into `/home/pi/.pyload/userplugins/hooks` directory, the one that you have now is damaged

**Comment by Asmolet** [comment]
Thanks but i still have a problem...

> 

27.02.2018 20:13:53 | INFO | Utilisation du dossier principal : /home/pi/.pyload
27.02.2018 20:14:16 | ERROR | **Erreur d'importation UpdateManager : No module named Addon**
27.02.2018 20:14:16 | INFO | Plugins activés: BypassCaptcha, Captcha9Kw, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, RestartFailed, UnSkipOnFail, XFileSharingPro
27.02.2018 20:14:16 | INFO | Plugins désactivés: AlldebridCom, AndroidPhoneNotify, CaptchaBrotherhood, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, FastixRu, FreeWayMe, HotFolder, IRCInterface, JustPremium, LinkdecrypterCom, LinksnappyCom, MegaDebridEu, MergeFiles, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumTo, PremiumizeMe, PutdriveCom, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, SmoozedCom, UnrestrictLi, WindowsPhoneNotify, XMPPInterface, ZeveraCom
27.02.2018 20:14:16 | INFO | Temps de téléchargement : True
27.02.2018 20:14:16 | INFO | Démarre ThriftBackend: 0.0.0.0:7227
27.02.2018 20:14:29 | INFO | Free space: 24.66 GiB
27.02.2018 20:14:29 | WARNING | SSL certificates not found.
27.02.2018 20:14:29 | INFO | Starting builtin webserver: 
27.02.2018 20:14:30 | INFO | Activating Accounts...
27.02.2018 20:14:30 | INFO | Activating Plugins...
27.02.2018 20:14:30 | INFO | ExtractArchive: No SevenZip installed
27.02.2018 20:14:31 | INFO | ExtractArchive: Activated UnRar 4.10\|UnZip (python 2.7.3)
27.02.2018 20:14:31 | INFO | XFileSharingPro: Handling any hoster I can!
27.02.2018 20:14:31 | INFO | ClickAndLoad: Proxy listening on 127.0.0.1:9666
27.02.2018 20:14:31 | INFO | XFileSharingPro: Handling any crypter I can!
27.02.2018 20:14:31 | INFO | pyLoad is up and running
27.02.2018 20:15:54 | INFO | Added package Ferdinand containing 3 links
27.02.2018 20:15:56 | INFO | Download starts: https://uptobox.com/txvdtbummfn5
27.02.2018 20:15:58 | INFO | Download starts: https://uptobox.com/vwp0yevn8ggh
27.02.2018 20:16:00 | INFO | Download starts: https://uptobox.com/i6sfwgk19xqv
27.02.2018 20:16:16 | WARNING | Info Fetching for UptoboxCom failed \| (35, 'gnutls_handshake() failed: A TLS packet with unexpected length was received.')
27.02.2018 20:16:21 | ERROR | pycurl error 35: gnutls_handshake() failed: A TLS packet with unexpected length was received.
27.02.2018 20:16:21 | INFO | UnSkipOnFail: Looking for skipped duplicates of: https://uptobox.com/txvdtbummfn5 (pid:1373)
27.02.2018 20:16:22 | INFO | UnSkipOnFail: No duplicates found
27.02.2018 20:16:23 | ERROR | pycurl error 35: gnutls_handshake() failed: A TLS packet with unexpected length was received.
27.02.2018 20:16:23 | INFO | UnSkipOnFail: Looking for skipped duplicates of: https://uptobox.com/vwp0yevn8ggh (pid:1373)
27.02.2018 20:16:23 | INFO | UnSkipOnFail: No duplicates found
27.02.2018 20:16:24 | ERROR | pycurl error 35: gnutls_handshake() failed: A TLS packet with unexpected length was received.
27.02.2018 20:16:24 | INFO | UnSkipOnFail: Looking for skipped duplicates of: https://uptobox.com/i6sfwgk19xqv (pid:1373)
27.02.2018 20:16:24 | INFO | UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
@Asmolet Two things:
First, disable XFileSharingPro plugin.
Second, it seems that now you have an issue with outdated pycurl which have a bug with SSL.
Please update pycurl.

**Comment by Asmolet** [comment]
XFileSharingPro is disabled.
I tried to update pycurl but there is no update...
I tried to uninstall/install pyload using this commands : 

> sudo apt-get remove pyload
sudo apt-get update
sudo apt-get install python-support python-crypto python-pycurl tesseract-ocr tesseract-ocr-eng python-imaging -y
wget --no-check-certificate https://github.com/pyload/pyload/releases/download/v0.4.9/pyload-cli_0.4.9_all.deb
sudo dpkg -i pyload*
rm pyload*.deb
sudo apt-get install python-pip python-dev -y
sudo pip install pyopenssl
sudo apt-get install rhino -y
pyLoadCore -s

But the problem is still here...

**Comment by GammaC0de** [comment]
@Asmolet See #3072

**Comment by Asmolet** [comment]
Yes i apllied the modification with pycurl and openssl, but the problem persists...

Can you tell me the instructions to cleanly uninstall all the files of pyload ?

**Comment by Asmolet** [comment]
The gnutls error is solved.
Now i have this problem : 

> 01.03.2018 12:43:08 INFO      Démarrage pyLoad 0.4.9
01.03.2018 12:43:08 INFO      Utilisation du dossier principal : /home/pi/.pyload
01.03.2018 12:43:08 DEBUG     Remote activated: True
01.03.2018 12:43:30 DEBUG     created index of plugins
01.03.2018 12:43:30 DEBUG     Redirected import module.plugins.hooks.RestartFailed -> userplugins.hooks.RestartFailed
01.03.2018 12:43:30 DEBUG     Redirected import module.plugins.hooks.BypassCaptcha -> userplugins.hooks.BypassCaptcha
01.03.2018 12:43:30 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder download_preparing not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder download_finished not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder all_downloads_finished not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder all_downloads_processed not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder before_reconnect not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder after_reconnect not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder package_finished not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder package_extracted not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder archive_extracted not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder all_archives_extracted not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder all_archives_processed not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder unrar_finished not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder all_dls_finished not created
01.03.2018 12:43:30 DEBUG     ExternalScripts: Script folder all_dls_processed not created
01.03.2018 12:43:30 DEBUG     Redirected import module.plugins.hooks.Captcha9Kw -> userplugins.hooks.Captcha9Kw
01.03.2018 12:43:30 DEBUG     Redirected import module.plugins.hooks.Checksum -> userplugins.hooks.Checksum
01.03.2018 12:43:30 DEBUG     Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
01.03.2018 12:43:30 DEBUG     Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
01.03.2018 12:43:30 DEBUG     Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
01.03.2018 12:43:31 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
**01.03.2018 12:43:31 ERROR     Erreur d'importation UpdateManager : No module named Addon
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/home/pi/.pyload/userplugins/hooks/UpdateManager.py", line 11, in <module>
    from ..internal.Addon import Addon
ImportError: No module named Addon**
01.03.2018 12:43:31 DEBUG     Redirected import module.plugins.hooks.ImageTyperz -> userplugins.hooks.ImageTyperz
01.03.2018 12:43:31 DEBUG     Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
01.03.2018 12:43:31 DEBUG     Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
01.03.2018 12:43:31 INFO      Plugins activés: BypassCaptcha, Captcha9Kw, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, ImageTyperz, RestartFailed, UnSkipOnFail
01.03.2018 12:43:31 INFO      Plugins désactivés: AlldebridCom, AndroidPhoneNotify, CaptchaBrotherhood, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, FastixRu, FreeWayMe, HotFolder, IRCInterface, JustPremium, LinkdecrypterCom, LinksnappyCom, MegaDebridEu, MergeFiles, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumTo, PremiumizeMe, PutdriveCom, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, SmoozedCom, UnrestrictLi, WindowsPhoneNotify, XFileSharingPro, XMPPInterface, ZeveraCom
01.03.2018 12:43:31 INFO      Temps de téléchargement : True
01.03.2018 12:43:32 INFO      Démarre ThriftBackend: 0.0.0.0:7227
01.03.2018 12:43:32 INFO      Espace libre : 24.66 GiB
01.03.2018 12:43:35 INFO      Activation des comptes ...
01.03.2018 12:43:35 INFO      Activation des Extensions...
01.03.2018 12:43:35 DEBUG     RestartFailed: Invalid interval value, kept current
01.03.2018 12:43:47 DEBUG     Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
01.03.2018 12:43:47 WARNING   SSL certificates not found.
01.03.2018 12:43:47 INFO      Starting builtin webserver: 192.168.0.3:8000
01.03.2018 12:43:47 DEBUG     Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
01.03.2018 12:43:48 INFO      ExtractArchive: No SevenZip installed
01.03.2018 12:43:48 DEBUG     Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
01.03.2018 12:43:48 INFO      ExtractArchive: Activated UnRar 4.10|UnZip (python 2.7.3)
01.03.2018 12:43:48 INFO      pyLoad is up and running
01.03.2018 12:43:48 INFO      ClickAndLoad: Proxy listening on 127.0.0.1:9666
01.03.2018 12:43:50 DEBUG     RestartFailed: Restart failed downloads
01.03.2018 12:43:52 DEBUG     Redirected import module.plugins.hoster.UptoboxCom -> userplugins.hoster.UptoboxCom
01.03.2018 12:43:52 DEBUG     Redirected import module.plugins.internal.XFSHoster -> userplugins.internal.XFSHoster
01.03.2018 12:43:52 DEBUG     Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
01.03.2018 12:43:52 DEBUG     Redirected import module.plugins.accounts.UptoboxCom -> userplugins.accounts.UptoboxCom
01.03.2018 12:43:52 DEBUG     Redirected import module.plugins.internal.XFSAccount -> userplugins.internal.XFSAccount
01.03.2018 12:43:52 INFO      Download starts: 8ne21ml6ctvs
01.03.2018 12:43:52 DEBUG     UptoboxCom: Update file info...
01.03.2018 12:43:52 DEBUG     UptoboxCom: Previous file info: {}
01.03.2018 12:43:54 DEBUG     UptoboxCom: Current file info: {'status': 3, 'url': u'https://uptobox.com/8ne21ml6ctvs', 'name': u'8ne21ml6ctvs', 'size': 0}
01.03.2018 12:43:54 DEBUG     UptoboxCom: File name: 8ne21ml6ctvs | File size: Unknown
01.03.2018 12:43:54 DEBUG     UptoboxCom: File status: queued
01.03.2018 12:43:54 DEBUG     UptoboxCom: Update file info...
01.03.2018 12:43:54 DEBUG     UptoboxCom: Previous file info: {'status': 3, 'url': u'https://uptobox.com/8ne21ml6ctvs', 'name': u'8ne21ml6ctvs', 'size': 0}
01.03.2018 12:43:54 DEBUG     UptoboxCom: Current file info: {'status': 3, 'name': u'8ne21ml6ctvs', 'url': u'https://uptobox.com/8ne21ml6ctvs', 'size': 0}
01.03.2018 12:43:54 DEBUG     UptoboxCom: File name: 8ne21ml6ctvs | File size: Unknown
01.03.2018 12:43:54 DEBUG     UptoboxCom: Update file info...

**Comment by Asmolet** [comment]
I tried to update PluginManager.py with the last version but doesn't work...

**Comment by regpa** [comment]
I back on the thread, I followed it silently as my spots would have been quite the same, the issue is quite resistant. I will try a total uninstall before a new fresh install. Is there an updated procedure bullet-proof that new comer to pyload could follow ?
many @GammaC0de for all you hints !

**Comment by GammaC0de** [comment]
@regpa See #2000
