### ISSUE TITLE
nginx reverse proxy

### ISSUE THREAD

**Issue by kugan49** [pyload/pyload#3073]
I saw some person who have set pyload and nginx to address website via http://servername/pyload/

How can I do this ?

**Comment by GammaC0de** [comment]
Does is have to be nginx  or apache is acceptable too?

**Comment by kugan49** [comment]
I already use nginx (I'm on raspberry Pi) so I can't use anything else. Any ideas ?

**Comment by GammaC0de** [comment]
Ok, so how about this setup?
```
location  /pyload {
  rewrite /pyload(.*) /$1  break;
  proxy_pass         http://localhost:8000;
  proxy_redirect     off;
  proxy_set_header   Host $host;
}
```

**Comment by kugan49** [comment]
when I go on http://myservername/pyload
It redirect to http://myservername/login

**Comment by kugan49** [comment]
I put "/pyload" in path prefix

**Comment by GammaC0de** [comment]
What if you go to http://myservername/pyload/login ?

**Comment by kugan49** [comment]
GOt this

Error 404: Not Found
Sorry, the requested URL 'http://osmc/login' caused an error:

Not found: '//login'

**Comment by GammaC0de** [comment]
Try this:
```
location  /pyload {
  rewrite /pyload(.*) $1  break;
  proxy_pass         http://localhost:8000;
  proxy_redirect     off;
  proxy_set_header   Host $host;
}
```

**Comment by kugan49** [comment]
http://myservername/ redirects to http://myservername/login
and  
http://myservername/pyload/login works but with no css

**Comment by GammaC0de** [comment]
This?
```
location  /pyload {
  proxy_pass         http://localhost:8000;
  proxy_redirect     off;
  proxy_set_header   Host $host;
}
```

**Comment by kugan49** [comment]
This is the same result,

I saw this [https://github.com/pyload/pyload/issues/2631](https://github.com/pyload/pyload/issues/2631) 
But nginx put me an error on the last config (location /pyload/ {
    proxy_pass http://localhost:8000/;
    proxy_set_header Accept-Encoding "";
    sub_filter_types text/css text/xml text/javascript;
    sub_filter '/media/' '/pyload/media/';
    sub_filter '/json/' '/pyload/json/';
    sub_filter '/api/' '/pyload/api/';
    sub_filter '<a href="/' '<a href="/pyload/';
    sub_filter_once off;
}) =

nginx: [emerg] "sub_filter" directive is duplicate in /etc/nginx/sites-available/locat.conf:45

**Comment by kugan49** [comment]
Is there a way to work with uwsgi in socket mode ? (I've already installed it on my raspberry)

**Comment by GammaC0de** [comment]
> Is there a way to work with uwsgi in socket mode 

I don't understand..

**Comment by GammaC0de** [comment]
What version of nginx  are you using?

**Comment by kugan49** [comment]
socket mode can be done like this with flask applications :+1: [https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-uwsgi-and-nginx-on-ubuntu-14-04#set-up-a-flask-application](url)
Is there a way to do like this with pyload ?



My nginx version :


`nginx version: nginx/1.6.2                                                                                                                                                                                         
TLS SNI support enabled                                                                                                                                                                                            
configure arguments: --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt=-Wl,-z,relro --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --
http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-p
ath=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-
path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_s
sl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gzip_static_module --wit
h-http_image_filter_module --with-http_spdy_module --with-http_sub_module --with-http_xslt_module --with-mail --with-mail_ssl_module --add-module=/build/nginx-51Ms7m/nginx-1.6.2/debian/modules/nginx-auth-pam --a
dd-module=/build/nginx-51Ms7m/nginx-1.6.2/debian/modules/nginx-dav-ext-module --add-module=/build/nginx-51Ms7m/nginx-1.6.2/debian/modules/nginx-echo --add-module=/build/nginx-51Ms7m/nginx-1.6.2/debian/modules/ng
inx-upstream-fair --add-module=/build/nginx-51Ms7m/nginx-1.6.2/debian/modules/ngx_http_substitutions_filter_module                                                                                                 
`

**Comment by OzzieIsaacs** [comment]
The path prefix is not working in pyload (from webinterface.py):
```if` PREFIX:
    env.filters["url"] = lambda x: x
else:
    env.filters["url"] = lambda x: PREFIX + x if x.startswith("/") else x
```
So if there is a prefix set, is ignored, and if prefix is not set than nothing is added.
Furthermore in the templated the url filters are not included. There are two more lines in the code which have to be exchanged (therfore the redirect to /login instead of .../login). 
If you are willing to merge this, I can create a pull request. Than the proxyconfig from @GammaC0de should work.

**Comment by kugan49** [comment]
In fact it would be so nice to have this, because while I can't have this I stop use pyload.
Tell me how

**Comment by GammaC0de** [comment]
I intent to setup nginx on a VM and see what is going on..
Busy days..

@OzzieIsaacs I'm interested to see your PR, is this tested on Apache also?

**Comment by OzzieIsaacs** [comment]
to be honest its only tested on apache now, i have to test it on nginx. hopefully this evening

**Comment by OzzieIsaacs** [comment]
I created the pull request. Its only done for pyplex and not for the classic UI yet, because of the minified js files and the huge amout of css url links, which cause trouble. 
I'll update also my pyload Next-theme repro to take advance of the PR.

**Comment by GammaC0de** [comment]
Thanks @OzzieIsaacs.
@kugan49 Can you test that it works?

**Comment by kugan49** [comment]
@GammaC0de , @OzzieIsaacs   It works nice thank youu !!!!!!!!

**Comment by JoergBerlin** [comment]
Hi,

so I copied the changed files to my raspberry and tried to gain access via nginx reverse proxy with this configuration:

gateway:

        location ^~ /pyload {
                proxy_pass http://127.0.0.1:84;
                proxy_redirect off;
        }

config-file:

server {
        listen 127.0.0.1:84;
        server_name 127.0.0.1;

location  /pyload {
  proxy_pass         http://localhost:8000;
  proxy_redirect     off;
  proxy_set_header   Host $host;
}

I get this error:

2018/03/30 16:12:14 [error] 1373#1373: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET /pyload HTTP/1.0", upstream: "http://127.0.0.1:8000/pyload", host: "127.0.0.1:84"

Does anybody know how to solve the problem?

Thanks

Joerg

**Comment by GammaC0de** [comment]
Please open a new issue, you will have more chance to get an answer..
