### ISSUE TITLE
Announcing: pyplex enhanced version webinterface- now officialy included

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#3075]
Hi all!

### Let me Introduce to you the most complete and stable webinterface up until today!

Based on PyPlex (Thanks @xunil75) but with:
- countless bug-fixes...
- countless changes...
- countless enhancements...

I will specify the major ones:
- The theme name was renamed to 'pyplex' (lower letters).
- Desktop notifications!
- Plugin config tab now has a dynamic plugin name search!!
- Add package dialolg is now resizible and dragable.
- Queue/Collector: the order of the files and packages can be set by dragging them to the desired position.
- Filechooser / Pathchooser are now inside a dialog and not on a separate browser window.
- Floating "scroll to top" button.
- Password edit boxes has a reveal password button (except in the configuration tab).
- The info tab now shows pyload's tweeter feed.

Final words:
I thought of it a lot and I will be honest with you:
I am not comfortable with the idea of putting a donate button inside the WebUI (it's on the info tab) and once I even added it but removed it shortly after.
Time went on and on and this mini-project was far from finished .
So I thought, considering the enormous sheer amount of work this mini-project took (there is probably no place I did not touched/changed) and considering the amount of work I put in pyLoad in particular, I finally decided to do add a donate button,

Please use it to show your appreciation :heart:

**Comment by Web-Eye** [comment]
How do I get this webinterface?
It does not come along with the UpdateManager (ver. 1.20) 
Have I to update the files manually?

**Comment by GammaC0de** [comment]
Sorry, I will explain:
Since it's not a plugin, UpdateManager cannot update it.
Best way to update (plus you get huge number of bug-fixes) is to do is:
* Go to `http://<IP_OF_PYLOAD>/info`
* Write down the value of `Installation Folder`
* Stop pyload
* Download https://github.com/pyload/pyload/archive/stable.zip
* Extract everything under  `<stable.zip>/pyload-stable/module` to `<Installation Folder>/module`.
* Now you have two options:
 1.  * Run `python pyLoadCore.py -s`, answer all the questions and choose `pyplex` as a webinterface.
     * Start pyLoad.

  2. * Start pyload.
      * Go to pyLoads's general settings -> webinterface and change the template to `pyplex`.
      * Restart pyLoad.

**Comment by Web-Eye** [comment]
Thanks,
I will give it a try....

**Comment by OzzieIsaacs** [comment]
First of all, I want to thank you that you are integrated this in the stable branch of pyload, this UI is looking much more modern than the old one, and gives the opportunity to use pyload on mobile devices.

You introduced some new (untranslated) strings with this change. I added this strings and the missing strings (at least for the german version) in a PR to update the (german) translation file.

**Comment by OzzieIsaacs** [comment]
Hello @GammaC0de,
if seen you only merged the js and html files, but not the language file (Django.mo), was this intentionally?

**Comment by GammaC0de** [comment]
Sorry, missed that..

**Comment by Web-Eye** [comment]
Hey @GammaC0de,
installed successful, but only worked, when run first time with the start wizzard.
Looks nice, so thanks for that...
One question: Is (will be) there amore brighter version?
WebEye

**Comment by GammaC0de** [comment]
I do intend to make a brighter version (I actually like more the bright version, but I already started to work on this because I did not think it would take so long and it was too late to stop).

You can also use the Next theme, merged with the chnges by me, from @OzzieIsaacs if you like .

**Comment by Web-Eye** [comment]
thanks,
but I think, I like your theme much more!
Maybe, we got a brighter version, some day...

**Comment by Keltere** [comment]
Will be pyplex the next main template? Maybe with pyload 5.0?

**Comment by GammaC0de** [comment]
@Keltere I don't know, @vuolter is responsible for this, but at least now pyload's setup wizard (`pyLoadCore -s`) hase the option to choose web the webtemplate to use.

**Comment by MaluNoPeleke** [comment]
Thanks a lot @GammaC0de !
For a bright version you mean [this one](https://github.com/OzzieIsaacs/pyload-NextTheme), don't you?

**Comment by xunil75** [comment]
@GammaCode @MaluNoPeleke check my PyWhite version on my account. I will release it soon. @GammaCode contact me for details, i need to explain you something

**Comment by GammaC0de** [comment]
I will not be able to do so until the end of the week. 

 
 
  Marco Fernandes<notifications@github.com> wrote:   
@gammacode @MaluNoPeleke check my PyWhite version on my account. I will release it soon. @gammacode contact me for details, i need to explain you something

**Comment by pyblub** [comment]
@xunil75 @MaluNoPeleke Do any of your templates support mobile devices well? I really like the new designs, but a special design/template for mobile devices would be great. The current design is rather difficult to use on a smartphone.

**Comment by MiuiSwitzerland** [comment]
@pyblub the best way it to download the app. Im on IOS and there is an app for pyload on the AppStore.

**Comment by GammaC0de** [comment]
@xunil75 We can chat on Gitter if you like

**Comment by SweetthD3ViL** [comment]
Thank you - it looks great a works great. 
2 small issues:
1) The pyLoad logo (top left) which is clickable does not do anything and would be great to lead back home
2) When adding a new link to download - The name box become white when selected, however, the link box remains grey, and the font colour is also grey - so when pasting a link or links they aren't visible.

**Comment by GammaC0de** [comment]
> When adding a new link to download - The name box become white when selected, however, the link box remains grey, and the font colour is also grey - so when pasting a link or links they aren't visible.

Can you post a screenshot?

**Comment by SweetthD3ViL** [comment]
Sure thing - see below. 

The first one show the link box with text highlighted - text box grey with text in grey.
<a href="http://tinypic.com?ref=2nlcn68" target="_blank"><img src="http://i66.tinypic.com/2nlcn68.png" border="0" alt="Image and video hosting by TinyPic"></a>
The second image show the text box not selected - as you can see the text is not visible, you can see text to be there as it is underline for spealing mistake. 
<a href="http://tinypic.com?ref=t7ek2c" target="_blank"><img src="http://i68.tinypic.com/t7ek2c.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by GammaC0de** [comment]
@SweetthD3ViL I could not reproduce this (see below)
What is your configuration? I used chrome on windows 10.
![capture1](https://user-images.githubusercontent.com/11036551/39868646-332ddb68-5463-11e8-85c4-b064d178b295.PNG)
![capture2](https://user-images.githubusercontent.com/11036551/39868654-39c67a02-5463-11e8-8504-0b953cef39d7.PNG)

**Comment by SweetthD3ViL** [comment]
Thank you for looking into it. I have the issue on two different machine.
Computer running Archlinux with Chromium
Chromebook with Chrome

How about the pyLoad logo on the top left not leading back to the home page?

**Comment by GammaC0de** [comment]
These instructions https://github.com/pyload/pyload/issues/3075#issuecomment-360980457?

**Comment by SweetthD3ViL** [comment]
Yes correct.

**Comment by GammaC0de** [comment]
Wll, I don't have arch Archlinux nor Chromium, can you try this on a normal Chrome or Firefox?

**Comment by GammaC0de** [comment]
Please send user and password to nitzo2001 at yahoo dot com.

**Comment by SweetthD3ViL** [comment]
Right, So was creating the user for you, changed the permission and was testing the user. Now the link box is behaving like normal (white when selected) with that new user in an incognito tab. So I tried clearing the chrome cache, but with my normal user, it still does the same?!

**Comment by GammaC0de** [comment]
@Web-Eye Yes, I am aware of this issue and I tried to solve this with these commits: 
https://github.com/pyload/pyload/commit/29e23d127413c3b94468bcdbe418f1d028f32b60 https://github.com/pyload/pyload/commit/7e64480b93f1bd0ae5f8625756bc51a12f70b049

Try to update to the latest stable branch and please inform me if this issue is resolved.

**Comment by Web-Eye** [comment]
@GammaC0de,
thanks, I will give it a try and give feedback....

**Comment by GammaC0de** [comment]
@Web-Eye Do you have a conclusion?

**Comment by Web-Eye** [comment]
Hey @GammaC0de,
sorry for late feedback, actual I wanted to test till weekend!
So far no issues anymore, seems to be resolved...
Thanks WebEye

**Comment by Web-Eye** [comment]
@GammaC0de,
no issues anymore. Well done!
Thanks for Support,
WebEye

**Comment by GammaC0de** [comment]
For the reference: https://github.com/pyload/pyload/issues/3264
