### ISSUE TITLE
FshareVN has updated the new interface

### ISSUE THREAD

**Issue by bigdargon** [pyload/pyload#3082]
Hello,
FshareVN has updated the new interface, so the current FshareVN plugin is no longer working. Can you update it?
Thank you!

**Comment by bigdargon** [comment]
@GammaC0de I sent the account information to nitzo2001 at yahoo dot com

**Comment by GammaC0de** [comment]
URL with password please

**Comment by bigdargon** [comment]
Link with password www.fshare.vn/file/7JT662H2I3LH
password : 123456
Thanks!
