### ISSUE TITLE
HearthisAt not working anymore

### ISSUE THREAD

**Issue by sraedler** [pyload/pyload#3084]
Hi,

Hearthis.At is not working anymore.

[Testlink](https://hearthis.at/mashup/#tracks)

**Comment by GammaC0de** [comment]
https://hearthis.at/mashup/mashup-germany-when-ba-jingle-takes-over/ works fine, the link you gave is for a playlist, not a single track..

**Comment by sraedler** [comment]
Is Playlist support planed?

**Comment by GammaC0de** [comment]
The problem is how to distinguish between a playlist URL and track URL?

**Comment by sraedler** [comment]
A single track has that intTrackId tag.

On a site with multiple tracks you have to call https://hearthis.at/user_ajax_more.php as POST-Request.
The Payload hast to be user, min and max. 
Min and Max has to be a value with range 10.

So multiple call that post with min 0, max 10, min 10, max 20, ... until the response is empty
The User is written after intInternalId


if the playlist is a Category, the URL includes /categories/.
the url here is https://hearthis.at/category_ajax_more.php
payload again min and max and the linkpart after /categories/

there are more playlist types, but if you could setup the stuff above, I could try to add the rest

**Comment by GammaC0de** [comment]
I mean the problem is for example:
https://hearthis.at/mashup/#tracks is a playlist
and https://hearthis.at/mashup/mashup-germany-when-ba-jingle-takes-over/ is a track

pyLoad has to know from the URL what kind of URL is it so it can handle is correctly.

How do you know when a URL is a track and when it is a playlist?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by sraedler** [comment]
Sorry!

That's what i ment.

In it's a single track, than in the html content is that inttrackid otherwise not.

So a html get is required to decide

**Comment by GammaC0de** [comment]
@sraedler Imlementation is not a problem (in fact hearit is one of the easiest), the issued it that pyLoad has to know  **from the URL** what type of URL it is.

I heave and idea how to handle it:
Treat _every_ hearit URL as a playlist and if it is not a playlist add a tag to the URL to flag it as a song.
This means that for a single URL it would have to process it twice,
Would you like that?

**Comment by sraedler** [comment]
@GammaC0de now I get the point!

That's a good idea.

It would be cool if you could do that!

Just a question. Am I right, if a playlist has 100 tracks than only the first URL call has to be twice and all the downloads only need one call, because the URL just match with the track plugin.

**Comment by GammaC0de** [comment]
Yes.

**Comment by sraedler** [comment]
Great!

**Comment by sraedler** [comment]
thx!!!

I would love to try that, but unfortunately I'm not able to use pyload anymore since #3085 

The problem is, that I'm not able to compile pycurl and pycrypto for synology NAS...

Sorry for that...

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/45e086d29f6e40e13747a197c270eb98d83bd4bf
