### ISSUE TITLE
Some python 3 syntax problems

### ISSUE THREAD

**Issue by Keltere** [pyload/pyload#3089]
Hi, i've tried to install pyload on archlinux because the package on aur is not updated and i like the new theme.
I've copied pyload in /opt/pyload/ when i start to run it with `python /opt/pyload/pyLoadCore.py` it gave me this error

```
File "/opt/pyload/pyLoadCore.py", line 99
    print "pyLoad", CURRENT_VERSION
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "pyLoad", CURRENT_VERSION)?

```

I've fixed it also in line 139 `print pid` to `print (pid)`

But then at line 142 i get this error

```
File "/opt/pyload/pyLoadCore.py", line 142
    print "false"
                ^
TabError: inconsistent use of tabs and spaces in indentation

```

Sorry to bother but i'm not use to python, i hate the tabs/space indentation. Could you please give me a help?

EDIT also 156, 159, 168 is missing parentheses

**Comment by pyblub** [comment]
run it with `python2 /opt/pyload/pyLoadCore.py` or change the first line in `/opt/pyload/pyLoadCore.py` to `#!/usr/bin/env python2` and just run the file directly.

pyload (stable) does not support python 3. There are more differences than the parentheses of the print statement. It is not an easy task to port it to python 3

**Comment by Keltere** [comment]
Thanks, i just wanted some boost on performance.
I read "You need at least Python 2.7" so i was thinking that is compatible with python 3.0
Sorry for creating this meaningless issue.

**Comment by pyblub** [comment]
pyload is fairly leightweight. Some unnecessary pooling though. The main bottleneck, I assume, will always be your internet connection and the speed of the website you download from.

Did you notice any performance problems?

The only thing I ever noticed, was extracting archives was slow (also due to the hardware I used), but extracting is mainly done by external programs (7zip, unrar). Some python modules are even just wrappers for C code, which is fast.

**Comment by Keltere** [comment]
No no, just with old theme, the new one it's amazing. I like to get the best performance and to have always the last version of everything. That's also why i choose arch as my distro. Sometimes that cause problems...

**Comment by GammaC0de** [comment]
@Keltere The master branch is the development branch of the next version of pyLoad.
It is not complete yet, pre-alpha version.
In this version python 3 would be supported.
