### ISSUE TITLE
Pyload plugin error importing

### ISSUE THREAD

**Issue by dawcio73** [pyload/pyload#3091]
I do not know when it happened
[code]
INFO Using home directory: /share/MD0_DATA/.qpkg/pyload/data
702 05.02.2018 13:25:31 ERROR Error importing EventMapper: No module named json
703 05.02.2018 13:25:31 ERROR Error importing ExternalScripts: No module named json
704 05.02.2018 13:25:31 ERROR Error importing ClickNLoad: No module named json
705 05.02.2018 13:25:31 ERROR Error importing ExtractArchive: No module named json
706 05.02.2018 13:25:31 ERROR Error importing UnSkipOnFail: No module named json
707 05.02.2018 13:25:32 ERROR Error importing XFileSharing: No module named json
708 05.02.2018 13:25:32 ERROR Error importing UpdateManager: No module named json
709 05.02.2018 13:25:32 ERROR Error importing UserAgentSwitcher: No module named json
[/code]

**Comment by GammaC0de** [comment]
What python version  are you running?

**Comment by dawcio73** [comment]
python 2.5.6

**Comment by dawcio73** [comment]
Traceback (most recent call last):
File "/share/MD0_DATA/.qpkg/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/share/MD0_DATA/.qpkg/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/share/MD0_DATA/.qpkg/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/share/MD0_DATA/.qpkg/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/share/MD0_DATA/.qpkg/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/share/MD0_DATA/.qpkg/pyload/module/utils.py", line 165, in new
return func(*args)
File "/share/MD0_DATA/.qpkg/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/share/MD0_DATA/.qpkg/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

  loading

**Comment by GammaC0de** [comment]
are you able to upgrade to python 2.7?

**Comment by dawcio73** [comment]
Yes. But I do not know how to remove 2.5.6

**Comment by GammaC0de** [comment]
You don't have to, they can co-exist, just run python 2.7 directly, e.g. /usr/bin/python2.7

How do you install python 2.7?

**Comment by dawcio73** [comment]
QNAP qpkg

**Comment by GammaC0de** [comment]
you install python 2.7 with QNAP qpkg? isn't there a way to remove python 2.5?

If no, just try installing 2.7

**Comment by dawcio73** [comment]
I installed but how to run it? what command

**Comment by GammaC0de** [comment]
Whare is pyLoadCore.py located?

**Comment by dawcio73** [comment]
/share/MD0_DATA/.qpkg/pyload

**Comment by GammaC0de** [comment]
Run `<full-path-of-python-2.7.bin> /share/MD0_DATA/.qpkg/pyload/pyLoadCore.py -s`

Also, did you see https://www.qnapclub.eu/en/qpkg/189?

**Comment by GammaC0de** [comment]
Or this http://www.positiv-it.fr/QNAP/APP/QPyload_170116_x86_64.zip?

**Comment by dawcio73** [comment]
I have QNAP TS-212p does not support 64bit

**Comment by GammaC0de** [comment]
OK, then http://www.positiv-it.fr/QNAP/APP/QPyload_170116_x86.zip?

**Comment by dawcio73** [comment]
I will check. Give me a moment

**Comment by GammaC0de** [comment]
If not there are (for arm CPU)
http://www.positiv-it.fr/QNAP/APP/QPyload_170116_arm-x41.zip
http://www.positiv-it.fr/QNAP/APP/QPyload_160116_arm-x31.zip

**Comment by dawcio73** [comment]
I see the lights of the tunnel :-) give me a moment

**Comment by dawcio73** [comment]
nothing works. It must be arm_x19

**Comment by GammaC0de** [comment]
OK, then run `<full-path-of-python-2.7.bin> /share/MD0_DATA/.qpkg/pyload/pyLoadCore.py -s`

**Comment by dawcio73** [comment]
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/pyload/pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/share/MD0_DATA/.qpkg/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/share/MD0_DATA/.qpkg/pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/share/MD0_DATA/.qpkg/pyload/module/network/HTTPRequest.py", line 20, in <module>
    import pycurl
ImportError: No module named pycurl

**Comment by GammaC0de** [comment]
Where does pyload.conf resides?

**Comment by dawcio73** [comment]
./data/

**Comment by GammaC0de** [comment]
replace ./data/userplugins/internal/misc.py with https://github.com/pyload/pyload/raw/73a02ef618c043e03b79619014323a72d40133a2/module/plugins/internal/misc.py and see if it helps

**Comment by dawcio73** [comment]
I found it here:
/share/MD0_DATA/.qpkg/pyload/data/userplugins/internal
I swapped. he ordered a restart. without result. But this file is also in other locations?

**Comment by dawcio73** [comment]
/share/MD0_DATA/.qpkg/CloudBackupSync/python/lib/python2.7/compiler/misc.py
/share/MD0_DATA/.qpkg/CloudDrive/python/lib/python2.7/compiler/misc.py
/share/MD0_DATA/.qpkg/CloudDriveSync/python/lib/python2.7/compiler/misc.py
/share/MD0_DATA/.qpkg/HybridBackup/python/lib/python2.7/compiler/misc.py
/share/MD0_DATA/.qpkg/Optware/lib/python2.5/compiler/misc.py
/share/MD0_DATA/.qpkg/Optware/lib/python2.5/site-packages/django/contrib/gis/geos/prototypes/misc.py
/share/MD0_DATA/.qpkg/Python/lib/python2.7/compiler/misc.py
/share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/misc.py
/share/MD0_DATA/.qpkg/pyload/opt/lib/python2.5/compiler/misc.py
/share/MD0_DATA/.qpkg/pyload/opt/lib/python2.5/site-packages/django/contrib/gis/geos/prototypes/misc.py

**Comment by pyblub** [comment]
The message states `No module named pycurl`
have you tried installing the package? `pip install pycurl` or `<full-path-of-python-2.7.bin> -m pip install pycurl`

also `HTTPRequest.py", line 20` when looking at the current file: https://github.com/pyload/pyload/blob/stable/module/network/HTTPRequest.py `import pycurl` is done in line 21. Do you have the newest version?

**Comment by GammaC0de** [comment]
Replace this one: /share/MD0_DATA/.qpkg/pyload/data/userplugins/internal/misc.py

**Comment by dawcio73** [comment]
I changed it there
replace HTTPRequest.py. We'll see what happens

**Comment by dawcio73** [comment]
How to install it?
 pip install pycurl or <full-path-of-python-2.7.bin> -m pip install pycurl

**Comment by GammaC0de** [comment]
Have to go. Speak to you tomorrow. 
<notifications@github.com> wrote:   
How to install it?
pip install pycurl or <full-path-of-python-2.7.bin> -m pip install pycurl

**Comment by dawcio73** [comment]
thanks for the help. see you tomorrow

**Comment by adamantike** [comment]
@dawcio73 can you run these commands and past the output here?

```
which python

python --version

pip --version

/share/MD0_DATA/.qpkg/pyload/module/lib

<full-path-of-python-2.7.bin> --version

pip freeze

<full-path-of-python-2.7.bin> -m pip freeze
```

**Comment by dawcio73** [comment]
python 2.7
other commands not found

**Comment by adamantike** [comment]
Please paste the exact output you got for each command. Otherwise, it's too difficult to find out what's happening

**Comment by dawcio73** [comment]
optware out
I installed entware-nd and pyload and everything works. Topic is closed

**Comment by GammaC0de** [comment]
👍
