### ISSUE TITLE
Windows fresh installation

### ISSUE THREAD

**Issue by france996** [pyload/pyload#3092]
Hello,

first of all i'm not a developer or a software expert so i've tried everything but i don't know how to do a fresh installation of pyload in windows.
I've seen the #2000 but it is for linux; could you please explain in details how can i install pyload?
Thank you so much.

**Comment by GammaC0de** [comment]
Windows package is here: https://github.com/pyload/pyload/releases/download/v0.4.9/pyload_0.4.9_win.zip.
Follow the instruction in #2000 .

**Comment by france996** [comment]
Hello @GammaC0de ,

i've found the problem; i was unzipping the stable version in the root folder of the pyload release (the one in which there is the executable) and not in the correct one (dist).
Now it's working, thank you so much.
