### ISSUE TITLE
Missing some fixes in "Fix path prefix for pyplex/classic UI"

### ISSUE THREAD

**Issue by youlJunior** [pyload/pyload#3094]
There is some missing fixes for path prefix in classic template : 

- all url like "/api/xxx" in media/js/classic/package_ui.js
- /json/abort_link/ in templates/classic/home.html

**Comment by youlJunior** [comment]
@GammaC0de I found one more missing path prefix fix in package_ui.js 😃 

imgs[0].set("src","/media/classic/img/status_queue.png")
should be
imgs[0].set("src","{{'/media/classic/img/status_queue.png'|url }}")

**Comment by GammaC0de** [comment]
:+1: Done
