### ISSUE TITLE
[MegaCoNz] Asian characters in file name are truncated

### ISSUE THREAD

**Issue by frosty5689** [pyload/pyload#3096]
Hi,

I am using the latest version of pyLoad and noticed if I use MegaCoNz plugin to download a folder of files, the files with asian characters in the file name will be truncated. When the file is downloading, all the asian characters are striped out and missing in the webinterface as well. The asian characters eventually become available in the webinterface after download completes, but the file name on disk is still missing them.

Here's an example MegaCoNz folder I was trying to download

https://mega.nz/#F!WN9zmKoZ!1KiTzhk7l2FFNXB_l_ORQw

**Comment by GammaC0de** [comment]
pyLoad has severe unicode issues,
Unfortunately, it would probably require to rewrite many parts of pyLoad to fix that..
