### ISSUE TITLE
relink.to Plugin may be out of date

### ISSUE THREAD

**Issue by oltodosel** [pyload/pyload#3097]
http://relink.to/view.php?id=0c474c48ac2df5b932b9fcffb7f8b9

749 | 10.02.2018 01:06:31 | INFO | CRYPTER RelinkUs[4451]: Waiting 4 seconds...
750 | 10.02.2018 01:06:37 | INFO | CRYPTER RelinkUs[4451]: Waiting 4 seconds...
751 | 10.02.2018 01:06:43 | INFO | CRYPTER RelinkUs[4451]: Waiting 4 seconds...
752 | 10.02.2018 01:06:49 | ERROR | Decrypting failed: 0c474c48ac2df5b932b9fcffb7f8b9 \| Decrypt error: No link grabbed \| Plugin may be out of date

**Comment by GammaC0de** [comment]
@oltodosel 
Please provide debug log.

**Comment by oltodosel** [comment]
Started working again.
