### ISSUE TITLE
No permission set after extraction with 7-zip.

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#3099]
Hello. i have found a small bug after extraction with 7zip-rar in debian.
If i use 7-zip in pyload for extraction, the folder permission is set to 0700 instead of the permission that i set in pyload. The Problem is, i have no access to the extracted folder via samba. i have access to the content/folder if i change the permission via putty /winscp. This error is not with unrar, only with 7zip.
I see also no error in extraction and all archives extracted fine.
I use 7zip 16.02 for testing. 
It's extracted fine but did not set the correct folder permission.

**Comment by GammaC0de** [comment]
can you change https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExtractArchive.py#L273 from:
```python
            if not exists(extract_folder):
                os.makedirs(extract_folder)

                if subfolder:
                    self.set_permissions(extract_folder)
```

To:
```python
            if not exists(extract_folder):
                os.makedirs(extract_folder)

            self.set_permissions(extract_folder)
```

and test if it helps?

**Comment by Mister-XY** [comment]
Nothing changes :-(

**Comment by GammaC0de** [comment]
@Mister-XY Maybe this is the problem https://github.com/pyload/pyload/issues/3219#issuecomment-413458658?

**Comment by Mister-XY** [comment]
No, i have this all enabled. The permissions from files are correct butnot from the folders.

**Comment by GammaC0de** [comment]
OK, you did not say that earlier.
Now it makes sense.

**Comment by Mister-XY** [comment]
> OK, you did not say that earlier.
Now it makes sense.

> It's extracted fine but did not set the correct folder permission.

**Comment by Mister-XY** [comment]
Very nice, it's look very fine.
