### ISSUE TITLE
Missing function in pyplex (change priority)

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#3100]
Hello, i missing a small function in pyplex theme. In classic theme, i can move the archives in queue/collector from top to bottom or from bottom to top. So I can set which archive has a higher priority. In pyplex i can't do that.

**Comment by GammaC0de** [comment]
This feature does exist,
You should drag the progress bars.

**Comment by Mister-XY** [comment]
Ah ok, i must drag the progress bar. 
closed
