### ISSUE TITLE
uptobox issue with TEXTAREA F1 

### ISSUE THREAD

**Issue by zephura** [pyload/pyload#3103]
Hi,
I have an issue with uptobox

here is an extract of the log:

Index|Date|Type|Data|
-- | -- | -- | --
12 | 14.02.2018 19:48:21 | INFO | Download starts: oyk9w6vqc87l
13 | 14.02.2018 19:48:21 | WARNING | HOSTER UptoboxCom[1542]: Plugin may be unstable
14 | 14.02.2018 19:48:21 | INFO | HOSTER UptoboxCom[1542]: Grabbing link info...
15 | 14.02.2018 19:48:21 | INFO | HOSTER UptoboxCom[1542]: Link name: oyk9w6vqc87l
16 | 14.02.2018 19:48:21 | INFO | HOSTER UptoboxCom[1542]: Link size: N/D
17 | 14.02.2018 19:48:21 | INFO | HOSTER UptoboxCom[1542]: Link status: demarrage
18 | 14.02.2018 19:48:21 | INFO | HOSTER UptoboxCom[1542]: Processing url:  the url is http :// uptobox dot com/oyk9w6vqc87l (replace dot com by .com)
19 | 14.02.2018 19:48:22 | INFO | HOSTER UptoboxCom[1542]: Checking for link errors...
20 | 14.02.2018 19:48:22 | INFO | HOSTER UptoboxCom[1542]: No errors found
21 | 14.02.2018 19:48:22 | INFO | HOSTER UptoboxCom[1542]: Grabbing link info...
22 | 14.02.2018 19:48:22 | INFO | HOSTER UptoboxCom[1542]: Link name: oyk9w6vqc87l
23 | 14.02.2018 19:48:22 | INFO | HOSTER UptoboxCom[1542]: Link size: N/D
24 | 14.02.2018 19:48:22 | INFO | HOSTER UptoboxCom[1542]: Link status: demarrage
25 | 14.02.2018 19:48:22 | INFO | HOSTER UptoboxCom[1542]: Processing as free download...
26 | 14.02.2018 19:48:22 | INFO | HOSTER UptoboxCom[1542]: Checking for link errors...
27 | 14.02.2018 19:48:22 | INFO | HOSTER UptoboxCom[1542]: No errors found
28 | 14.02.2018 19:48:22 | INFO | HOSTER UptoboxCom[1542]: Waiting 1 seconds...
29 | 14.02.2018 19:48:24 | INFO | Download restarted: oyk9w6vqc87l \| TEXTAREA F1 not found

**Comment by youlJunior** [comment]
It seems that uptobox changed their html : 
- link pattern is now "xxxxx/dl/xxxx" instead of "xxxx/d/xxxx"
- other patterns may need to be changed like INFO_PATTERN, NAME_PATTERN, SIZE_PATTERN...

BUT : It happens to me few days ago, and Uptobox changed back their html few hours after.
Maybe they are testing a new html, so the plugin needs to be compatible with the two htmls....

**Comment by youlJunior** [comment]
@GammaC0de you can change the Uptobox plugin like that : 

```python
INFO_PATTERN = r'**(?:**"para_title">**|<h1>)**(?P<N>.+) \((?P<S>[\d.,]+) (?P<U>[\w^_]+)\)'
LINK_PATTERN = r'"(https?://(?:obwp\d+\.uptobox\.com|\w+\.uptobox\.com/d**l?**)/.*?)"'
```

**Comment by GammaC0de** [comment]
Thanks 👍
