### ISSUE TITLE
UPTOBOX Technical changes from 15/02/2018

### ISSUE THREAD

**Issue by maaax78** [pyload/pyload#3104]
Hi,
I received support ticket today from uptobox team regarding technical changes in their website, making downloads not possible from this host now with version 0.20 of host.
![upto_150218](https://user-images.githubusercontent.com/36514885/36272407-c0b7cf9e-1281-11e8-93f1-27aad8050575.JPG)
Think this will need update
Thank you 
Best regards,

**Comment by maaax78** [comment]
Hello, sorry if i did not clearly explain the issue : 

- I am using Synology Download Station to manage my downloads
- this application is using Pyload's plugin to manage public hosts authentication
- Pyload's plug-in version for uptobox.com host is 0.20

As explained, since yesterday, downloads from uptobox are not working because Uptobox did technical changes to their website (this is basically what is said from their technical support in French in the attached screenshot).

Hence my request to update this host and if I am not at the right place then let me apologize. 

Hope this is clear now

**Comment by soulierseb** [comment]
Hello same issue i've got  this error message from today in pyload 
TEXTAREA F1 not found 0.00 BUptoboxCom

it seems that uptobox change something on their servers

can you please fix it thanks a lot

**Comment by GammaC0de** [comment]
The current version of the hoster plugin is 0.32 and the account plugin is 0.21.
So obliviously your plugins are not up-to-date. .

**Comment by youlJunior** [comment]
@GammaC0de I think this is linked to the changes I found in #3103

**Comment by soulierseb** [comment]
thanks a lot for the answer the issue is fixed

**Comment by GammaC0de** [comment]
👍 
@maaax78 Does it fixes the issue for you too?

**Comment by maaax78** [comment]
Hi,
As of today the Synology application I am running has no update, which may be necessary to update your plug-in to the latest version in the app (still 0.20 on my side). 

Anyway another workaround was provided by the community until Synology officially update their package (custom .host file to reflect changes in uptobox website). 

Many thanks for your answers and help provided!

**Comment by GammaC0de** [comment]
@maaax78 Did you read https://github.com/pyload/pyload/issues/2994?

**Comment by maaax78** [comment]
Yes and thanks for informing but this has to be done in the Synology package by itself which cannot be done on my side.
Thank you again

**Comment by GammaC0de** [comment]
If you have access to the filesystem, you can do it yourself rather than wait..

**Comment by zephura** [comment]
linked to the issue 3104 (but this ticket is still opened)
I still have the same problem with TEXTAREA F1 not found.

btw : I have the last version of the plugin "0.32" and pyload has been restarted and recompilation forced.

If I can help in something

**Comment by youlJunior** [comment]
@zephura can you give me the Uptobox link you are trying to download ?

**Comment by MacFred13** [comment]
hi all,
I still have this problem with my pyload on a qnap. 
I've just change the version of pyload to a pyload-stable / it seems to be the last version of the 02/15 of 2018. 
When I try to download a link from uptobox I obtain a message : 

1004 | 18.02.2018 18:06:30 | INFO | HOSTER UptoboxCom[179]: Processing url: https://uptobox.com/vw0q1duwura1
-- | -- | -- | --
1005 | 18.02.2018 18:06:30 | INFO | HOSTER UptoboxCom[179]: Checking for link errors...
1006 | 18.02.2018 18:06:30 | INFO | HOSTER UptoboxCom[179]: No errors found
1007 | 18.02.2018 18:06:30 | INFO | HOSTER UptoboxCom[179]: Processing as free download...
1008 | 18.02.2018 18:06:30 | INFO | HOSTER UptoboxCom[179]: Checking for link errors...
1009 | 18.02.2018 18:06:30 | INFO | HOSTER UptoboxCom[179]: No errors found
1010 | 18.02.2018 18:06:30 | INFO | HOSTER UptoboxCom[179]: Waiting 1 seconds...
1011 | 18.02.2018 18:06:30 | INFO | Download restarted: KNO1080.part05.rar \| TEXTAREA F1 not found
1012 | 18.02.2018 18:06:30 | INFO | Download starts: KNO1080.part05.rar
1013 | 18.02.2018 18:06:30 | WARNING | HOSTER UptoboxCom[178]: Plugin may be unstable
1014 | 18.02.2018 18:06:30 | INFO | HOSTER UptoboxCom[178]: Grabbing link info...

I've the same issue with all download I tried.
So, if you want more information ...

**Comment by GammaC0de** [comment]
Please enable debug mode and then resend the log.

**Comment by MacFred13** [comment]
ok, see below the log with debug mode : 

18.02.2018 19:00:59 INFO      Download restarted: KNO1080.part04.rar | TEXTAREA F1 not found
18.02.2018 19:00:59 INFO      HOSTER UptoboxCom[178]: Checking for link errors...
18.02.2018 19:00:59 INFO      HOSTER UptoboxCom[178]: No errors found
18.02.2018 19:00:59 INFO      HOSTER UptoboxCom[178]: Processing as free download...
18.02.2018 19:00:59 INFO      Download starts: KNO1080.part04.rar
18.02.2018 19:00:59 DEBUG     HOSTER UptoboxCom[178]: Getting download link #1...
18.02.2018 19:00:59 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
18.02.2018 19:00:59 INFO      HOSTER UptoboxCom[178]: Checking for link errors...
18.02.2018 19:00:59 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
18.02.2018 19:00:59 INFO      HOSTER UptoboxCom[178]: No errors found
18.02.2018 19:00:59 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
18.02.2018 19:00:59 DEBUG     HOSTER UptoboxCom[178]: WAIT set to timestamp 1518976861.676593 | Previous waitUntil: 0.000000
18.02.2018 19:00:59 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
18.02.2018 19:00:59 INFO      HOSTER UptoboxCom[178]: Waiting 1 seconds...
18.02.2018 19:00:59 DEBUG     HOSTER UptoboxCom[177]: Plugin version: 0.32
18.02.2018 19:00:59 DEBUG     HOSTER UptoboxCom[177]: Plugin status: testing
18.02.2018 19:00:59 WARNING   HOSTER UptoboxCom[177]: Plugin may be unstable
18.02.2018 19:00:59 INFO      HOSTER UptoboxCom[177]: Grabbing link info...
18.02.2018 19:00:59 DEBUG     HOSTER UptoboxCom[177]: Link info: {'status': 2, 'hash': {}, 'name': u'KNO1080.part04.rar', 'url': u'https://uptobox.com/t24ccvjfx9ta', 'pattern': {'S': u'950.00', 'U': u'MB', 'N': u'KNO1080.part04.rar'}, 'size': 996147200}
18.02.2018 19:00:59 DEBUG     HOSTER UptoboxCom[177]: Previous link info: {'status': 2, 'hash': {}, 'name': u'KNO1080.part04.rar', 'url': u'https://uptobox.com/t24ccvjfx9ta', 'pattern': {'S': u'950.00', 'U': u'MB', 'N': u'KNO1080.part04.rar'}, 'size': 996147200}
18.02.2018 19:00:59 INFO      HOSTER UptoboxCom[177]: Link name: KNO1080.part04.rar
18.02.2018 19:00:59 INFO      HOSTER UptoboxCom[177]: Link size: 950.00 MiB (996147200 bytes)
18.02.2018 19:00:59 INFO      HOSTER UptoboxCom[177]: Link status: en ligne
18.02.2018 19:00:59 INFO      HOSTER UptoboxCom[177]: Processing url: https://uptobox.com/t24ccvjfx9ta
18.02.2018 19:00:59 DEBUG     HOSTER UptoboxCom[177]: LOAD URL https://uptobox.com/t24ccvjfx9ta | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
18.02.2018 19:00:59 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`

**Comment by MacFred13** [comment]
I complete my post with the rest of the log 
18.02.2018 19:01:19 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
18.02.2018 19:01:19 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: KNO1080.part09.rar (pid:102)
18.02.2018 19:01:19 INFO      ADDON UnSkipOnFail: No duplicates found
18.02.2018 19:01:20 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
18.02.2018 19:01:20 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
18.02.2018 19:01:20 DEBUG     ADDON ExternalScripts: No script found under folder `package_failed`
18.02.2018 19:01:20 INFO      Download restarted: KNO1080.part10.rar | TEXTAREA F1 not found
18.02.2018 19:01:20 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
18.02.2018 19:01:20 DEBUG     All downloads processed
18.02.2018 19:01:20 INFO      Download starts: KNO1080.part10.rar
18.02.2018 19:01:20 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
18.02.2018 19:01:20 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
18.02.2018 19:01:20 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
18.02.2018 19:01:20 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
18.02.2018 19:01:20 DEBUG     HOSTER UptoboxCom[183]: Plugin version: 0.32
18.02.2018 19:01:20 DEBUG     HOSTER UptoboxCom[183]: Plugin status: testing
18.02.2018 19:01:20 WARNING   HOSTER UptoboxCom[183]: Plugin may be unstable
18.02.2018 19:01:20 INFO      HOSTER UptoboxCom[183]: Grabbing link info...
18.02.2018 19:01:20 DEBUG     HOSTER UptoboxCom[183]: Link info: {'status': 2, 'hash': {}, 'name': u'KNO1080.part10.rar', 'url': u'https://uptobox.com/q709yp79hmcg', 'pattern': {'S': u'394.25', 'U': u'MB', 'N': u'KNO1080.part10.rar'}, 'size': 413401088}
18.02.2018 19:01:20 DEBUG     HOSTER UptoboxCom[183]: Previous link info: {'status': 2, 'hash': {}, 'name': u'KNO1080.part10.rar', 'url': u'https://uptobox.com/q709yp79hmcg', 'pattern': {'S': u'394.25', 'U': u'MB', 'N': u'KNO1080.part10.rar'}, 'size': 413401088}
18.02.2018 19:01:20 INFO      HOSTER UptoboxCom[183]: Link name: KNO1080.part10.rar
18.02.2018 19:01:20 INFO      HOSTER UptoboxCom[183]: Link size: 394.25 MiB (413401088 bytes)
18.02.2018 19:01:20 INFO      HOSTER UptoboxCom[183]: Link status: en ligne
18.02.2018 19:01:20 INFO      HOSTER UptoboxCom[183]: Processing url: https://uptobox.com/q709yp79hmcg
18.02.2018 19:01:20 DEBUG     HOSTER UptoboxCom[183]: LOAD URL https://uptobox.com/q709yp79hmcg | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
18.02.2018 19:01:21 INFO      HOSTER UptoboxCom[183]: Checking for link errors...
18.02.2018 19:01:21 INFO      HOSTER UptoboxCom[183]: No errors found
18.02.2018 19:01:21 INFO      HOSTER UptoboxCom[183]: Processing as free download...
18.02.2018 19:01:21 DEBUG     HOSTER UptoboxCom[183]: Getting download link #1...
18.02.2018 19:01:21 INFO      HOSTER UptoboxCom[183]: Checking for link errors...
18.02.2018 19:01:21 INFO      HOSTER UptoboxCom[183]: No errors found
18.02.2018 19:01:21 WARNING   HOSTER UptoboxCom[183]: Free download failed | TEXTAREA F1 not found
18.02.2018 19:01:21 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
18.02.2018 19:01:21 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
18.02.2018 19:01:21 DEBUG     ADDON ExternalScripts: No script found under folder `package_failed`
18.02.2018 19:01:21 WARNING   Download failed: KNO1080.part10.rar | TEXTAREA F1 not found
18.02.2018 19:01:21 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
18.02.2018 19:01:21 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: KNO1080.part10.rar (pid:102)
18.02.2018 19:01:21 INFO      ADDON UnSkipOnFail: No duplicates found
18.02.2018 19:01:21 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
18.02.2018 19:01:21 DEBUG     All downloads processed

**Comment by MacFred13** [comment]
Hi, thx a lot GammaC0de, it seems to works now 👍 with your last commit.
