### ISSUE TITLE
PremiumizeMe problem with UploadedTo downloads

### ISSUE THREAD

**Issue by tommaek** [pyload/pyload#3105]
Hi,
I just installed pyload on my Netgear R7800 router, but I cant get my premiumize.me account working.

What I did:
- Added PremiumizeMe account, Status is "valid" and Premium "yes".
- Premiumize.me account plugin: Hosters to use: "all"
- Linkdecrypter.com plugin: Activated: "off"

Logfile Output:
57	20.12.2017 01:00:48	INFO	Download starts: xyz.rar
58	20.12.2017 01:00:48	WARNING	HOSTER UploadedTo[23]: Plugin may be unstable
59	20.12.2017 01:00:48	INFO	HOSTER UploadedTo[23]: Grabbing link info...
60	20.12.2017 01:00:48	INFO	HOSTER UploadedTo[23]: Link name: xyz.rar
61	20.12.2017 01:00:48	INFO	HOSTER UploadedTo[23]: Link size: 1023.00 MiB (1072693248 bytes)
62	20.12.2017 01:00:48	INFO	HOSTER UploadedTo[23]: Link status: online
63	20.12.2017 01:00:48	INFO	HOSTER UploadedTo[23]: Processing url: http://uploaded.net/file/xyz
64	20.12.2017 01:00:48	INFO	HOSTER UploadedTo[23]: Looking for direct download link...
65	20.12.2017 01:00:48	INFO	HOSTER UploadedTo[23]: Direct download link not found
66	20.12.2017 01:00:48	INFO	HOSTER UploadedTo[23]: Checking for link errors...
67	20.12.2017 01:00:48	INFO	HOSTER UploadedTo[23]: No errors found
68	20.12.2017 01:00:48	INFO	HOSTER UploadedTo[23]: Processing as free download...
69	20.12.2017 01:00:48	WARNING	CAPTCHA UploadedTo[23]: ReCaptcha | Secure Token pattern not found
70	20.12.2017 01:00:48	WARNING	Download failed: xyz.rar | ReCaptcha challenge pattern not found
71	20.12.2017 01:00:48	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: xyz.rar (pid:13)
72	20.12.2017 01:00:48	INFO	ADDON UnSkipOnFail: No duplicates found

When I delete the UploadedTo.py hoster plugin the logfile says:
34	16.02.2018 08:00:48	WARNING	Plugin UploadedTo not found.
35	16.02.2018 08:00:48	CRITICAL	None

It seems that pyload does not "know" to use the premiumizeMe account for the uploaded downloads.
Did I anything wrong or is there a problem with the premiumizeMe plugin?

**Comment by GammaC0de** [comment]
How exactly di you installed pyload?

**Comment by tommaek** [comment]
I followed this instruction:
https://www.hqt.ro/pyload-download-manager-through-entware/

I know only a few basics of linux so I dont know how to install the missing packages at the end of the report or if the are related to my problem.

This is the status report of the config assistent:
root@R7800:/tmp/mnt/sda1/entware/share/pyload$ python pyLoadCore.py -s
Choose your Language / Wähle deine Sprache ([en], de, fr, it, es, nl, sv, ru, pl, cs, sr, pt_BR):

Welcome to the pyLoad Configuration Assistent.
It will check your system and make a basic setup in order to run pyLoad.

The value in brackets [] always is the default value,
in case you don't want to change it or you are unsure what to choose, just hit enter.
Don't forget: You can always rerun this assistent with --setup or -s parameter, when you start pyLoadCore.
If you have any problems with this assistent hit STRG-C,
to abort and don't let him start with pyLoadCore automatically anymore.

When you are ready for system check, hit enter.

## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: OK

py-imaging: OK
tesseract: OK

PyQt4: missing

jinja2: OK
beaker: OK
JS engine: missing

System check finished, hit enter to see your status report.

## Status ##

Features available: container decrypting, ssl connection, automatic captcha decryption, Webinterface

Featues missing:

Gui not available
The Graphical User Interface.

no JavaScript engine found
You will need this for some Click'N'Load links. Install Spidermonkey, ossp-js, pyv8 or rhino
You can abort the setup now and fix some dependicies if you want.
Continue with setup? ([y]/n):

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by tommaek** [comment]
I dont know about other hosts because normally I dont use them. Uploaded is the most important one.
I will send you the account.
In pyload you have to insert the Customer ID and the PIN, which you find in the account settings of premiumizeMe. It will not work with email and account password.

Thank you for your support.

**Comment by GammaC0de** [comment]
I have tested it and it worked fine for me with Uploaded.
I sujjest you reinstall pyLoad.

**Comment by tommaek** [comment]
Very strange, it was a clean install from the scratch.
I will install it again, but I have less time atm, so it can take some days.

The missing packages are not the problem? no JavaScript engine found
You will need this for some Click'N'Load links. Install Spidermonkey, ossp-js, pyv8 or rhino

**Comment by GammaC0de** [comment]
For PremiumizeMe javascript is not needded.

Try restarting pyload, maybe it would solve the issue.

**Comment by tommaek** [comment]
I did that a couple of times, it didn't help. Maybe I try it on my Linux PC with open suse when I have some free time.

**Comment by GammaC0de** [comment]
Starting pyload from the console with the `-d` commandline switch may help to pinpoint the cause of this.

**Comment by tommaek** [comment]
Is there anything useful in this output?

310 | 17.02.2018 17:54:45 | INFO | shutting down...
-- | -- | -- | --
311 | 17.02.2018 17:54:45 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_stop`
312 | 17.02.2018 17:54:45 | DEBUG | Deleting old pidfile pyload.pid
313 | 17.02.2018 17:54:45 | INFO | killed pyLoad from Terminal
314 | 17.02.2018 17:55:05 | INFO | Starting pyLoad 0.4.9
315 | 17.02.2018 17:55:05 | INFO | Using home directory: /tmp/mnt/sda1/entware/var/pyload
316 | 17.02.2018 17:55:05 | DEBUG | Remote activated: True
317 | 17.02.2018 17:55:07 | DEBUG | created index of plugins
318 | 17.02.2018 17:55:08 | INFO | Activated plugins: EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher
319 | 17.02.2018 17:55:08 | INFO | Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, ClickNLoad, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
320 | 17.02.2018 17:55:08 | INFO | Downloadtime: True
321 | 17.02.2018 17:55:08 | INFO | Using SSL ThriftBackend
322 | 17.02.2018 17:55:08 | INFO | Starting ThriftBackend: 0.0.0.0:7227
323 | 17.02.2018 17:55:09 | INFO | Free space: 177.13 GiB
324 | 17.02.2018 17:55:09 | INFO | Starting builtin webserver: 0.0.0.0:8000
325 | 17.02.2018 17:55:09 | INFO | Activating Accounts...
326 | 17.02.2018 17:55:10 | INFO | ACCOUNT PremiumizeMe: Adding user `123456789`...
327 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: Reached login timeout for user `123456789`
328 | 17.02.2018 17:55:10 | INFO | ACCOUNT PremiumizeMe: Login user `123456789`...
329 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php \| redirect=True \| cookies=True \| get={'params[pass]': '**********', 'params[login]': '123456789', 'method': 'accountstatus'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
330 | 17.02.2018 17:55:10 | INFO | ACCOUNT PremiumizeMe: Grabbing account info for user `123456789`...
331 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php \| redirect=True \| cookies=True \| get={'params[pass]': '**********', 'params[login]': '123456789', 'method': 'accountstatus'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
332 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: {u'status': 200, u'result': {u'trafficleft_gigabytes': 930.57457681093001, u'trafficleft_bytes': 999196843473L, u'expires': 1533467154, u'fairuse_left': 0.93057457681093003, u'extuid': u'123456789', u'type': u'premium', u'account_name': u'123456789'}, u'statusmessage': u'OK'}
333 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: Account info for user `123456789`: {'login': {'timestamp': 1518890110.0322549, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 975778167L, 'maxtraffic': None, 'validuntil': 1533467154.0, 'login': '123456789', 'type': 'PremiumizeMe', 'options': {'limitdl': ['0']}}}
334 | 17.02.2018 17:55:10 | INFO | ACCOUNT PremiumizeMe: Grabbing account info for user `123456789`...
335 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php \| redirect=True \| cookies=True \| get={'params[pass]': '**********', 'params[login]': '123456789', 'method': 'accountstatus'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
336 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: {u'status': 200, u'result': {u'trafficleft_gigabytes': 930.57457681093001, u'trafficleft_bytes': 999196843473L, u'expires': 1533467154, u'fairuse_left': 0.93057457681093003, u'extuid': u'123456789', u'type': u'premium', u'account_name': u'123456789'}, u'statusmessage': u'OK'}
337 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: Account info for user `123456789`: {'login': {'timestamp': 1518890110.0322549, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 975778167L, 'maxtraffic': None, 'validuntil': 1533467154.0, 'login': '123456789', 'type': 'PremiumizeMe', 'options': {'limitdl': ['0']}}}
338 | 17.02.2018 17:55:10 | INFO | Activating Plugins...
339 | 17.02.2018 17:55:10 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_start`
340 | 17.02.2018 17:55:10 | DEBUG | ADDON ExtractArchive: Found UnRar 5.50 \| Found UnZip 2.7.14 \| Found UnTar 2.7.14
341 | 17.02.2018 17:55:10 | DEBUG | ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com \| redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
342 | 17.02.2018 17:55:10 | INFO | pyLoad is up and running
343 | 17.02.2018 17:55:10 | WARNING | ADDON UpdateManager: Unable to connect to the server to retrieve updates
344 | 17.02.2018 17:55:24 | INFO | Download starts: xyz.rar
345 | 17.02.2018 17:55:24 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
346 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: Plugin version: 1.05
347 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: Plugin status: testing
348 | 17.02.2018 17:55:24 | WARNING | HOSTER UploadedTo[37]: Plugin may be unstable
349 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Grabbing link info...
350 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: Link info: {'status': 2, 'hash': {}, 'name': 'xyz.rar', 'url': u'http://uploaded.net/file/xyz', 'pattern': {'ID': u'xyz'}, 'size': 5521422}
351 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: Previous link info: {}
352 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Link name: xyz.rar
353 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Link size: 5.27 MiB (5521422 bytes)
354 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Link status: online
355 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Processing url: http://uploaded.net/file/xyz
356 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Looking for direct download link...
357 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: LOAD URL http://uploaded.net/file/xyz \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
358 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Direct download link not found
359 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: LOAD URL http://uploaded.net/file/xyz \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
360 | 17.02.2018 17:55:25 | INFO | HOSTER UploadedTo[37]: Checking for link errors...
361 | 17.02.2018 17:55:25 | INFO | HOSTER UploadedTo[37]: No errors found
362 | 17.02.2018 17:55:25 | INFO | HOSTER UploadedTo[37]: Processing as free download...
363 | 17.02.2018 17:55:25 | DEBUG | HOSTER UploadedTo[37]: LOAD URL http://uploaded.net/language/en \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
364 | 17.02.2018 17:55:25 | DEBUG | HOSTER UploadedTo[37]: LOAD URL http://uploaded.net/js/download.js \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
365 | 17.02.2018 17:55:25 | DEBUG | CAPTCHA UploadedTo[37]: ReCaptcha \| Key: 6Le1WUIUAAAAAG0gEh0atRevv3TT-WP4HW8FLMoe
366 | 17.02.2018 17:55:25 | WARNING | CAPTCHA UploadedTo[37]: ReCaptcha \| Secure Token pattern not found
367 | 17.02.2018 17:55:25 | DEBUG | HOSTER UploadedTo[37]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6Le1WUIUAAAAAG0gEh0atRevv3TT-WP4HW8FLMoe \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=http://uploaded.net/file/xyz \| just_header=False
368 | 17.02.2018 17:55:25 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
369 | 17.02.2018 17:55:25 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
370 | 17.02.2018 17:55:25 | WARNING | Download failed: xyz.rar \| ReCaptcha challenge pattern not found
371 | 17.02.2018 17:55:25 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: xyz.rar (pid:15)
372 | 17.02.2018 17:55:25 | INFO | ADDON UnSkipOnFail: No duplicates found
373 | 17.02.2018 17:55:25 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
374 | 17.02.2018 17:55:25 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
375 | 17.02.2018 17:55:25 | DEBUG | All downloads processed

**Comment by tommaek** [comment]
Is there anything useful in this output?


```
310 | 17.02.2018 17:54:45 | INFO | shutting down...
-- | -- | -- | --
311 | 17.02.2018 17:54:45 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_stop`
312 | 17.02.2018 17:54:45 | DEBUG | Deleting old pidfile pyload.pid
313 | 17.02.2018 17:54:45 | INFO | killed pyLoad from Terminal
314 | 17.02.2018 17:55:05 | INFO | Starting pyLoad 0.4.9
315 | 17.02.2018 17:55:05 | INFO | Using home directory: /tmp/mnt/sda1/entware/var/pyload
316 | 17.02.2018 17:55:05 | DEBUG | Remote activated: True
317 | 17.02.2018 17:55:07 | DEBUG | created index of plugins
318 | 17.02.2018 17:55:08 | INFO | Activated plugins: EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher
319 | 17.02.2018 17:55:08 | INFO | Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, ClickNLoad, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
320 | 17.02.2018 17:55:08 | INFO | Downloadtime: True
321 | 17.02.2018 17:55:08 | INFO | Using SSL ThriftBackend
322 | 17.02.2018 17:55:08 | INFO | Starting ThriftBackend: 0.0.0.0:7227
323 | 17.02.2018 17:55:09 | INFO | Free space: 177.13 GiB
324 | 17.02.2018 17:55:09 | INFO | Starting builtin webserver: 0.0.0.0:8000
325 | 17.02.2018 17:55:09 | INFO | Activating Accounts...
326 | 17.02.2018 17:55:10 | INFO | ACCOUNT PremiumizeMe: Adding user `123456789`...
327 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: Reached login timeout for user `123456789`
328 | 17.02.2018 17:55:10 | INFO | ACCOUNT PremiumizeMe: Login user `123456789`...
329 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php \| redirect=True \| cookies=True \| get={'params[pass]': '**********', 'params[login]': '123456789', 'method': 'accountstatus'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
330 | 17.02.2018 17:55:10 | INFO | ACCOUNT PremiumizeMe: Grabbing account info for user `123456789`...
331 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php \| redirect=True \| cookies=True \| get={'params[pass]': '**********', 'params[login]': '123456789', 'method': 'accountstatus'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
332 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: {u'status': 200, u'result': {u'trafficleft_gigabytes': 930.57457681093001, u'trafficleft_bytes': 999196843473L, u'expires': 1533467154, u'fairuse_left': 0.93057457681093003, u'extuid': u'123456789', u'type': u'premium', u'account_name': u'123456789'}, u'statusmessage': u'OK'}
333 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: Account info for user `123456789`: {'login': {'timestamp': 1518890110.0322549, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 975778167L, 'maxtraffic': None, 'validuntil': 1533467154.0, 'login': '123456789', 'type': 'PremiumizeMe', 'options': {'limitdl': ['0']}}}
334 | 17.02.2018 17:55:10 | INFO | ACCOUNT PremiumizeMe: Grabbing account info for user `123456789`...
335 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: LOAD URL http://api.premiumize.me/pm-api/v1.php \| redirect=True \| cookies=True \| get={'params[pass]': '**********', 'params[login]': '123456789', 'method': 'accountstatus'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
336 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: {u'status': 200, u'result': {u'trafficleft_gigabytes': 930.57457681093001, u'trafficleft_bytes': 999196843473L, u'expires': 1533467154, u'fairuse_left': 0.93057457681093003, u'extuid': u'123456789', u'type': u'premium', u'account_name': u'123456789'}, u'statusmessage': u'OK'}
337 | 17.02.2018 17:55:10 | DEBUG | ACCOUNT PremiumizeMe: Account info for user `123456789`: {'login': {'timestamp': 1518890110.0322549, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 975778167L, 'maxtraffic': None, 'validuntil': 1533467154.0, 'login': '123456789', 'type': 'PremiumizeMe', 'options': {'limitdl': ['0']}}}
338 | 17.02.2018 17:55:10 | INFO | Activating Plugins...
339 | 17.02.2018 17:55:10 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_start`
340 | 17.02.2018 17:55:10 | DEBUG | ADDON ExtractArchive: Found UnRar 5.50 \| Found UnZip 2.7.14 \| Found UnTar 2.7.14
341 | 17.02.2018 17:55:10 | DEBUG | ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com \| redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
342 | 17.02.2018 17:55:10 | INFO | pyLoad is up and running
343 | 17.02.2018 17:55:10 | WARNING | ADDON UpdateManager: Unable to connect to the server to retrieve updates
344 | 17.02.2018 17:55:24 | INFO | Download starts: xyz.rar
345 | 17.02.2018 17:55:24 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
346 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: Plugin version: 1.05
347 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: Plugin status: testing
348 | 17.02.2018 17:55:24 | WARNING | HOSTER UploadedTo[37]: Plugin may be unstable
349 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Grabbing link info...
350 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: Link info: {'status': 2, 'hash': {}, 'name': 'xyz.rar', 'url': u'http://uploaded.net/file/xyz', 'pattern': {'ID': u'xyz'}, 'size': 5521422}
351 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: Previous link info: {}
352 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Link name: xyz.rar
353 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Link size: 5.27 MiB (5521422 bytes)
354 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Link status: online
355 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Processing url: http://uploaded.net/file/xyz
356 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Looking for direct download link...
357 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: LOAD URL http://uploaded.net/file/xyz \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
358 | 17.02.2018 17:55:24 | INFO | HOSTER UploadedTo[37]: Direct download link not found
359 | 17.02.2018 17:55:24 | DEBUG | HOSTER UploadedTo[37]: LOAD URL http://uploaded.net/file/xyz \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
360 | 17.02.2018 17:55:25 | INFO | HOSTER UploadedTo[37]: Checking for link errors...
361 | 17.02.2018 17:55:25 | INFO | HOSTER UploadedTo[37]: No errors found
362 | 17.02.2018 17:55:25 | INFO | HOSTER UploadedTo[37]: Processing as free download...
363 | 17.02.2018 17:55:25 | DEBUG | HOSTER UploadedTo[37]: LOAD URL http://uploaded.net/language/en \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
364 | 17.02.2018 17:55:25 | DEBUG | HOSTER UploadedTo[37]: LOAD URL http://uploaded.net/js/download.js \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
365 | 17.02.2018 17:55:25 | DEBUG | CAPTCHA UploadedTo[37]: ReCaptcha \| Key: 6Le1WUIUAAAAAG0gEh0atRevv3TT-WP4HW8FLMoe
366 | 17.02.2018 17:55:25 | WARNING | CAPTCHA UploadedTo[37]: ReCaptcha \| Secure Token pattern not found
367 | 17.02.2018 17:55:25 | DEBUG | HOSTER UploadedTo[37]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6Le1WUIUAAAAAG0gEh0atRevv3TT-WP4HW8FLMoe \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=http://uploaded.net/file/xyz \| just_header=False
368 | 17.02.2018 17:55:25 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
369 | 17.02.2018 17:55:25 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
370 | 17.02.2018 17:55:25 | WARNING | Download failed: xyz.rar \| ReCaptcha challenge pattern not found
371 | 17.02.2018 17:55:25 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: xyz.rar (pid:15)
372 | 17.02.2018 17:55:25 | INFO | ADDON UnSkipOnFail: No duplicates found
373 | 17.02.2018 17:55:25 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
374 | 17.02.2018 17:55:25 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
375 | 17.02.2018 17:55:25 | DEBUG | All downloads processed
```

**Comment by GammaC0de** [comment]
Yes,
Your pyload is not up-to-date because you have not applied https://github.com/pyload/pyload/issues/2994.

**Comment by tommaek** [comment]
Thank you so much, now it works!

**Comment by GammaC0de** [comment]
Great. 👍
