### ISSUE TITLE
pyload not starting

### ISSUE THREAD

**Issue by koenigmidas** [pyload/pyload#3110]
hi gamma - hi people.

i was wondering why i cant reach pyload over webbrowser.
restarting raspi did not help

so i checked ssh with: sudo systemctl status pyload

pi@raspberrypi:~ $ sudo systemctl status pyload
● pyload.service - Python Downloader
   Loaded: loaded (/etc/systemd/system/pyload.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-02-19 20:51:10 CET; 11min ago
  Process: 317 ExecStart=/usr/bin/python /opt/pyload/pyLoadCore.py (code=exited, status=1/FAILURE)
 Main PID: 317 (code=exited, status=1/FAILURE)

Feb 19 20:51:10 raspberrypi python[317]:   File "/opt/pyload/pyLoadCore.py", line 664, in main
Feb 19 20:51:10 raspberrypi python[317]:     pyload_core.start()
Feb 19 20:51:10 raspberrypi python[317]:   File "/opt/pyload/pyLoadCore.py", line 410, in start
Feb 19 20:51:10 raspberrypi python[317]:     spaceLeft = freeSpace(self.config["general"]["download_folder"])
Feb 19 20:51:10 raspberrypi python[317]:   File "/opt/pyload/module/utils.py", line 112, in freeSpace
Feb 19 20:51:10 raspberrypi python[317]:     s = statvfs(folder)
Feb 19 20:51:10 raspberrypi python[317]: OSError: [Errno 2] No such file or directory: ''
Feb 19 20:51:10 raspberrypi systemd[1]: pyload.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 20:51:10 raspberrypi systemd[1]: pyload.service: Unit entered failed state.
Feb 19 20:51:10 raspberrypi systemd[1]: pyload.service: Failed with result 'exit-code'.

based on the fact that i am not a rasp/pyload pro - it would be great to get pyload working again please.

So please shoot and tell me how to fix it 

thank you in advance.

**Comment by GammaC0de** [comment]
It seems that your download folder does not exists..

**Comment by GammaC0de** [comment]
python /opt/pyload/pyLoadCore.py -s

**Comment by koenigmidas** [comment]
seems to work. thank you very much

**Comment by GammaC0de** [comment]
:+1:
