### ISSUE TITLE
Issue with Uptobox TEXTAREA F1 not found

### ISSUE THREAD

**Issue by sousouille** [pyload/pyload#3111]
Hi,

Issue with plugin Uptobox. May be only with premium account ?

Same issue for many files.

See the log below :
```
INFO	Download starts: j4mrdu895wmf
DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
DEBUG	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
DEBUG	ADDON UserAgentSwitcher: Setting maximum redirections to 10
DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
DEBUG	HOSTER XFileSharing[298]: UptoboxCom | Plugin version: 0.65
DEBUG	HOSTER XFileSharing[298]: UptoboxCom | Plugin status: testing
WARNING	HOSTER XFileSharing[298]: UptoboxCom | Plugin may be unstable
INFO	ACCOUNT UptoboxCom: Grabbing account info for user `**********`...
DEBUG	ACCOUNT UptoboxCom: LOAD URL http://uptobox.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
DEBUG	ACCOUNT UptoboxCom: Expire date: ********
DEBUG	ACCOUNT UptoboxCom: Valid until: 1531864800.0
DEBUG	ACCOUNT UptoboxCom: TRAFFIC LEFT PATTERN not found
DEBUG	ACCOUNT UptoboxCom: LEECH TRAFFIC PATTERN not found
DEBUG	ACCOUNT UptoboxCom: Account info for user `**********`: {'login': {'timestamp': 1519167226.090078, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1531864800.0, 'login': '*******', 'type': 'UptoboxCom', 'options': {'limitdl': ['0']}}}
INFO	HOSTER XFileSharing[298]: UptoboxCom | Grabbing link info...
DEBUG	HOSTER XFileSharing[298]: UptoboxCom | Link info: {'status': 7, 'hash': {}, 'name': 'j4mrdu895wmf', 'url': u'http://uptobox.com/j4mrdu895wmf', 'pattern': {}, 'size': 0}
DEBUG	HOSTER XFileSharing[298]: UptoboxCom | Previous link info: {}
INFO	HOSTER XFileSharing[298]: UptoboxCom | Link name: j4mrdu895wmf
INFO	HOSTER XFileSharing[298]: UptoboxCom | Link size: N/D
INFO	HOSTER XFileSharing[298]: UptoboxCom | Link status: demarrage
INFO	HOSTER XFileSharing[298]: UptoboxCom | Processing url: http://uptobox.com/j4mrdu895wmf
INFO	HOSTER XFileSharing[298]: UptoboxCom | Looking for direct download link...
DEBUG	HOSTER XFileSharing[298]: UptoboxCom | LOAD URL http://uptobox.com/j4mrdu895wmf | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
INFO	HOSTER XFileSharing[298]: UptoboxCom | Direct download link not found
DEBUG	HOSTER XFileSharing[298]: UptoboxCom | LOAD URL http://uptobox.com/j4mrdu895wmf | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
INFO	HOSTER XFileSharing[298]: UptoboxCom | Checking for link errors...
INFO	HOSTER XFileSharing[298]: UptoboxCom | No errors found
INFO	HOSTER XFileSharing[298]: UptoboxCom | Grabbing link info...
DEBUG	HOSTER XFileSharing[298]: UptoboxCom | Link info: {'status': 7, 'hash': {}, 'name': 'j4mrdu895wmf', 'url': u'http://uptobox.com/j4mrdu895wmf', 'pattern': {}, 'size': 0}
DEBUG	HOSTER XFileSharing[298]: UptoboxCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'j4mrdu895wmf', 'url': u'http://uptobox.com/j4mrdu895wmf', 'pattern': {}, 'size': 0}
INFO	HOSTER XFileSharing[298]: UptoboxCom | Link name: j4mrdu895wmf
INFO	HOSTER XFileSharing[298]: UptoboxCom | Link size: N/D
INFO	HOSTER XFileSharing[298]: UptoboxCom | Link status: demarrage
INFO	HOSTER XFileSharing[298]: UptoboxCom | Processing as premium download...
DEBUG	HOSTER XFileSharing[298]: UptoboxCom | Getting download link #1...
INFO	HOSTER XFileSharing[298]: UptoboxCom | Checking for link errors...
INFO	HOSTER XFileSharing[298]: UptoboxCom | No errors found
DEBUG	HOSTER XFileSharing[298]: UptoboxCom | WAIT set to timestamp 1519167259.463536 | Previous waitUntil: 0.000000
DEBUG	HOSTER XFileSharing[298]: UptoboxCom | RECONNECT not required | Previous wantReconnect: False
INFO	HOSTER XFileSharing[298]: UptoboxCom | Waiting 1 seconds...
DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
DEBUG	ADDON ExternalScripts: No script found under folder `package_failed`
INFO	Download restarted: j4mrdu895wmf | TEXTAREA F1 not found
DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
DEBUG	All downloads processed
```

**Comment by sousouille** [comment]
file conf error

**Comment by Hems45** [comment]
Can you explain Sousouille? because I have the same error even after clean install :/

**Comment by Chunam** [comment]
I had the same error, then pull the latest commits and it works now. (uptoboxCom.py changed recently)

**Comment by Hems45** [comment]
Got the last version of uptoboxcom (0.33 right?) same error :/

`549	21.02.2018 22:58:55	INFO	ACCOUNT UptoboxCom: Grabbing account info for user `Hems*******`...
550	21.02.2018 22:58:55	DEBUG	ACCOUNT UptoboxCom: LOAD URL http://uptobox.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
551	21.02.2018 22:58:55	DEBUG	ACCOUNT UptoboxCom: Expire date: 28 August 2018
552	21.02.2018 22:58:55	DEBUG	ACCOUNT UptoboxCom: Valid until: 1535407200.0
553	21.02.2018 22:58:55	DEBUG	ACCOUNT UptoboxCom: TRAFFIC LEFT PATTERN not found
554	21.02.2018 22:58:55	DEBUG	ACCOUNT UptoboxCom: LEECH TRAFFIC PATTERN not found
555	21.02.2018 22:58:55	DEBUG	ACCOUNT UptoboxCom: Account info for user `Hems*******`: {'login': {'timestamp': 1519250317.301521, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1535407200.0, 'login': 'Hems*******', 'type': 'UptoboxCom', 'options': {'limitdl': ['0']}}}
556	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Grabbing link info...
557	21.02.2018 22:58:55	DEBUG	HOSTER XFileSharing[2]: UptoboxCom | Link info: {'status': 7, 'hash': {}, 'name': 'dlz2mw0ra2c6', 'url': u'http://uptobox.com/dlz2mw0ra2c6', 'pattern': {}, 'size': 0}
558	21.02.2018 22:58:55	DEBUG	HOSTER XFileSharing[2]: UptoboxCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'dlz2mw0ra2c6', 'url': u'http://uptobox.com/dlz2mw0ra2c6', 'pattern': {}, 'size': 0}
559	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Link name: dlz2mw0ra2c6
560	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Link size: N/D
561	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Link status: demarrage
562	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Processing url: http://uptobox.com/dlz2mw0ra2c6
563	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Looking for direct download link...
564	21.02.2018 22:58:55	DEBUG	HOSTER XFileSharing[2]: UptoboxCom | LOAD URL http://uptobox.com/dlz2mw0ra2c6 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
565	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Direct download link not found
566	21.02.2018 22:58:55	DEBUG	HOSTER XFileSharing[2]: UptoboxCom | LOAD URL http://uptobox.com/dlz2mw0ra2c6 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
567	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Checking for link errors...
568	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | No errors found
569	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Grabbing link info...
570	21.02.2018 22:58:55	DEBUG	HOSTER XFileSharing[2]: UptoboxCom | Link info: {'status': 7, 'hash': {}, 'name': 'dlz2mw0ra2c6', 'url': u'http://uptobox.com/dlz2mw0ra2c6', 'pattern': {}, 'size': 0}
571	21.02.2018 22:58:55	DEBUG	HOSTER XFileSharing[2]: UptoboxCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'dlz2mw0ra2c6', 'url': u'http://uptobox.com/dlz2mw0ra2c6', 'pattern': {}, 'size': 0}
572	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Link name: dlz2mw0ra2c6
573	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Link size: N/D
574	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Link status: demarrage
575	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Processing as premium download...
576	21.02.2018 22:58:55	DEBUG	HOSTER XFileSharing[2]: UptoboxCom | Getting download link #1...
577	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | Checking for link errors...
578	21.02.2018 22:58:55	INFO	HOSTER XFileSharing[2]: UptoboxCom | No errors found
579	21.02.2018 22:58:55	WARNING	HOSTER XFileSharing[2]: UptoboxCom | Premium download failed | TEXTAREA F1 not found
580	21.02.2018 22:58:55	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
581	21.02.2018 22:58:55	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
582	21.02.2018 22:58:55	INFO	Download restarted: dlz2mw0ra2c6 | Fallback to free processing
583	21.02.2018 22:58:55	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
584	21.02.2018 22:58:55	DEBUG	All downloads processed `

>

**Comment by sousouille** [comment]
On my Synology, i just reinstall and redownload plugin directory.

**Comment by zephura** [comment]
Hi,

Is that a cat 'n mouse game???
It doesn't work anymore....

I've try to disable XFileSharing without success 😨

**Comment by GammaC0de** [comment]
Disable XFilesharing plugin


Hems45<notifications@github.com> wrote:   
Got the last version of uptoboxcom (0.33 right?) same error :/

549 21.02.2018 22:58:55 INFO ACCOUNT UptoboxCom: Grabbing account info for userHems*******... 550 21.02.2018 22:58:55 DEBUG ACCOUNT UptoboxCom: LOAD URL http://uptobox.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False 551 21.02.2018 22:58:55 DEBUG ACCOUNT UptoboxCom: Expire date: 28 August 2018 552 21.02.2018 22:58:55 DEBUG ACCOUNT UptoboxCom: Valid until: 1535407200.0 553 21.02.2018 22:58:55 DEBUG ACCOUNT UptoboxCom: TRAFFIC LEFT PATTERN not found 554 21.02.2018 22:58:55 DEBUG ACCOUNT UptoboxCom: LEECH TRAFFIC PATTERN not found 555 21.02.2018 22:58:55 DEBUG ACCOUNT UptoboxCom: Account info for userHems*******: {'login': {'timestamp': 1519250317.301521, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1535407200.0, 'login': 'Hems*******', 'type': 'UptoboxCom', 'options': {'limitdl': ['0']}}} 556 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Grabbing link info... 557 21.02.2018 22:58:55 DEBUG HOSTER XFileSharing[2]: UptoboxCom | Link info: {'status': 7, 'hash': {}, 'name': 'dlz2mw0ra2c6', 'url': u'http://uptobox.com/dlz2mw0ra2c6', 'pattern': {}, 'size': 0} 558 21.02.2018 22:58:55 DEBUG HOSTER XFileSharing[2]: UptoboxCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'dlz2mw0ra2c6', 'url': u'http://uptobox.com/dlz2mw0ra2c6', 'pattern': {}, 'size': 0} 559 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Link name: dlz2mw0ra2c6 560 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Link size: N/D 561 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Link status: demarrage 562 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Processing url: http://uptobox.com/dlz2mw0ra2c6 563 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Looking for direct download link... 564 21.02.2018 22:58:55 DEBUG HOSTER XFileSharing[2]: UptoboxCom | LOAD URL http://uptobox.com/dlz2mw0ra2c6 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True 565 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Direct download link not found 566 21.02.2018 22:58:55 DEBUG HOSTER XFileSharing[2]: UptoboxCom | LOAD URL http://uptobox.com/dlz2mw0ra2c6 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False 567 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Checking for link errors... 568 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | No errors found 569 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Grabbing link info... 570 21.02.2018 22:58:55 DEBUG HOSTER XFileSharing[2]: UptoboxCom | Link info: {'status': 7, 'hash': {}, 'name': 'dlz2mw0ra2c6', 'url': u'http://uptobox.com/dlz2mw0ra2c6', 'pattern': {}, 'size': 0} 571 21.02.2018 22:58:55 DEBUG HOSTER XFileSharing[2]: UptoboxCom | Previous link info: {'status': 7, 'hash': {}, 'name': 'dlz2mw0ra2c6', 'url': u'http://uptobox.com/dlz2mw0ra2c6', 'pattern': {}, 'size': 0} 572 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Link name: dlz2mw0ra2c6 573 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Link size: N/D 574 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Link status: demarrage 575 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Processing as premium download... 576 21.02.2018 22:58:55 DEBUG HOSTER XFileSharing[2]: UptoboxCom | Getting download link #1... 577 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | Checking for link errors... 578 21.02.2018 22:58:55 INFO HOSTER XFileSharing[2]: UptoboxCom | No errors found 579 21.02.2018 22:58:55 WARNING HOSTER XFileSharing[2]: UptoboxCom | Premium download failed | TEXTAREA F1 not found 580 21.02.2018 22:58:55 DEBUG ADDON ExternalScripts: No script found under folderdownload_processed581 21.02.2018 22:58:55 DEBUG ADDON ExternalScripts: No script found under folderpackage_processed582 21.02.2018 22:58:55 INFO Download restarted: dlz2mw0ra2c6 | Fallback to free processing 583 21.02.2018 22:58:55 DEBUG ADDON ExternalScripts: No script found under folderall_downloads_processed584 21.02.2018 22:58:55 DEBUG All downloads processed

**Comment by zephura** [comment]
Configuration > Plugins > XfileSharing > Activated : FALSE
Here the extract from plugin.conf
XFileSharing - "XFileSharing":
        bool activated : "Activated" = False

here is the extract from the log:

908 | 24.02.2018 18:34:06 | CRITICAL | 'NoneType' object has no attribute 'group'
-- | -- | -- | --



I can activate debugging if needed

**Comment by GammaC0de** [comment]
@zephura After you have disabled XfileSharing plugin, you must remove the links and then re-add them.

Also, please do not send just one line of the log, this is not helpful.

**Comment by zephura** [comment]
Hi,
Thank you I didn't know I add to re-add the links, I'll keep that in mind.

For the log, I've extracted the only interesting part : nothing before (except all is fine) and nothing after.
You can judge by yourself 😄 

887 | 24.02.2018 17:20:32 | INFO | Démarre ThriftBackend: 0.0.0.0:7227
-- | -- | -- | --
888 | 24.02.2018 17:20:33 | INFO | Starting builtin webserver: 0.0.0.0:8000
889 | 24.02.2018 17:20:33 | INFO | Free space: 311.91 GiB
890 | 24.02.2018 17:20:33 | INFO | Activating Accounts...
891 | 24.02.2018 17:20:33 | INFO | Activating Plugins...
892 | 24.02.2018 17:20:33 | INFO | pyLoad is up and running
893 | 24.02.2018 17:20:34 | INFO | ADDON UpdateManager: pyLoad is up to date!
894 | 24.02.2018 17:20:35 | INFO | ADDON UpdateManager: All plugins are up to date!
895 | 24.02.2018 17:20:39 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
896 | 24.02.2018 17:20:55 | CRITICAL | 'NoneType' object has no attribute 'group'
897 | 24.02.2018 17:20:57 | CRITICAL | 'NoneType' object has no attribute 'group'
898 | 24.02.2018 17:20:59 | CRITICAL | 'NoneType' object has no attribute 'group'
899 | 24.02.2018 17:21:01 | CRITICAL | 'NoneType' object has no attribute 'group'
900 | 24.02.2018 17:21:03 | CRITICAL | 'NoneType' object has no attribute 'group'
901 | 24.02.2018 17:21:05 | CRITICAL | 'NoneType' object has no attribute 'group'
902 | 24.02.2018 17:21:07 | CRITICAL | 'NoneType' object has no attribute 'group'
903 | 24.02.2018 17:21:09 | CRITICAL | 'NoneType' object has no attribute 'group'
904 | 24.02.2018 17:21:11 | CRITICAL | 'NoneType' object has no attribute 'group'
905 | 24.02.2018 17:21:13 | CRITICAL | 'NoneType' object has no attribute 'group'
906 | 24.02.2018 17:21:15 | CRITICAL | 'NoneType' object has no attribute 'group'
907 | 24.02.2018 17:21:17 | CRITICAL | 'NoneType' object has no attribute 'group'
908 | 24.02.2018 18:34:06 | CRITICAL | 'NoneType' object has no attribute 'group'
909 | 24.02.2018 18:38:16 | INFO | shutting down...
910 | 24.02.2018 18:38:16 | INFO | ADDON ClickNLoad: Shutting down proxy...
911 | 24.02.2018 18:38:16 | INFO | Received Quit signal

**Comment by GammaC0de** [comment]
Can you start pyload with the command `python pyLoadCore -d` and display the output?
