### ISSUE TITLE
Entware-ng: js not recognized

### ISSUE THREAD

**Issue by alex9434** [pyload/pyload#3113]
I have installed pyload on Entware-NG (asus router). Both available enines (duktape and JS) are not recognized by pyload. The system test gives the follwoing output:

JS engine: missing

The js engine is definitively availabel, eg. 

#js
((o) Duktape 2.2.0 (v2.2.0)
duk>

**Comment by GammaC0de** [comment]
What is the output of `systemCheck.py`?

**Comment by GammaC0de** [comment]
No response, closing.
