### ISSUE TITLE
Turbobit premium doesn't work.

### ISSUE THREAD

**Issue by 012345678987654321** [pyload/pyload#3114]
Hi!

The premium plugin doesn't work anymore. I get:

ACCOUNT TurbobitNet: Could not login user `...` | Bad server response: 503 Service Unavailable

The UpdateManager also doesn't work correctly. It tells me a (after a manual update, cause the old update servers are down):

ADDON UpdateManager: ***  New pyLoad 0.4.9 available  ***
ADDON UpdateManager: ***  Get it here: https://github.com/pyload/pyload/releases  ***

I am using pyload on a QNAP installed by Entware-ng (opkg).

**Comment by GammaC0de** [comment]
Please read #2000 .

**Comment by 012345678987654321** [comment]
Done.

25.02.2018 02:36:45 ERROR     ACCOUNT TurbobitNet: Could not login user `dr_*******` | Bad server response: 503 Service Unavailable
25.02.2018 02:36:45 INFO      Activating Plugins...
25.02.2018 02:36:46 INFO      ADDON UpdateManager: pyLoad is up to date!
25.02.2018 02:36:49 INFO      ADDON UpdateManager: Removed blacklisted plugin: ACCOUNTS FreeWayMe
25.02.2018 02:36:50 INFO      ADDON UpdateManager: All plugins are up to date!
25.02.2018 02:36:53 INFO      ADDON XFileSharing: Auto-discover new hosters
25.02.2018 02:36:54 INFO      ADDON XFileSharing: Auto-discover new crypters
25.02.2018 02:36:54 INFO      pyLoad is up and running

So turbobit is still not working.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

Also, please send sample URL, thanks.

**Comment by GammaC0de** [comment]
No response, closing.
