### ISSUE TITLE
UsersCloudCom plugin error

### ISSUE THREAD

**Issue by davycamps** [pyload/pyload#3115]
Downloading from userscloud.com gives me this error under the package in Queue:
failed 'UserscloudCom' object has no attribute 'pyload' 0.00 B UserscloudCom

**Comment by GammaC0de** [comment]
Sample URL please.

**Comment by GammaC0de** [comment]
Sorry but this file is offline...

**Comment by GammaC0de** [comment]
I'm sorry but this works fine for me.
Please stop pyload and then start it with the command `python pyLoadCore.py -d`, start a download and the post the log from the console here.

**Comment by davycamps** [comment]
Here we go:

[~] pyLoadCore -d
01.03.2018 06:18:27 INFO      Starting pyLoad 0.4.9
01.03.2018 06:18:27 INFO      Using home directory: /USERNAME/.pyload
01.03.2018 06:18:27 DEBUG     Deleting old pidfile pyload.pid
01.03.2018 06:18:27 DEBUG     Remote activated: False
01.03.2018 06:18:27 DEBUG     created index of plugins
01.03.2018 06:18:28 INFO      ExtractArchive: Activated UnRar UnZip
01.03.2018 06:18:28 INFO      Activated plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
01.03.2018 06:18:28 INFO      Deactivate plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
01.03.2018 06:18:28 INFO      Downloadtime: True
01.03.2018 06:18:28 INFO      Free space: 3.26 TiB
01.03.2018 06:18:28 INFO      Activating Accounts...
01.03.2018 06:18:28 INFO      Activating Plugins...
01.03.2018 06:18:28 INFO      pyLoad is up and running
01.03.2018 06:18:28 INFO      Starting builtin webserver: 0.0.0.0:8877
01.03.2018 06:18:31 INFO      ***  New pyLoad Version <html><head><title>Loading...</title></head><body><script type='text/javascript'>window.location.replace('http://get.pyload.org/check/0.4.9/?js=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqcyI6MX0.fADWc9hUOlh58R9UzufQBROmie3I7c7vE835oE6YmU4&uuid=5d53adbe-1d18-11e8-aa51-3434d201752e');</script></body></html> available  ***
01.03.2018 06:18:31 INFO      ***  Get it here: http://pyload.org/download  ***
01.03.2018 06:18:31 INFO      No plugin updates available
01.03.2018 06:19:44 INFO      Added package Testing UsersCloud containing 1 links
01.03.2018 06:19:46 INFO      Download starts: https://userscloud.com/p7kco7brloo1
01.03.2018 06:19:46 WARNING   Download failed: https://userscloud.com/p7kco7brloo1 | 'UserscloudCom' object has no attribute 'pyload'
Traceback (most recent call last):
  File "/USERNAME/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/USERNAME/share/pyload/module/plugins/Plugin.py", line 233, in preprocessing
    self.setup()
  File "/USERNAME/share/pyload/module/plugins/hoster/UserscloudCom.py", line 71, in setup
    options=self.pyload.requestFactory.getOptions(),
AttributeError: 'UserscloudCom' object has no attribute 'pyload'
01.03.2018 06:19:46 DEBUG     Error creating zip file: [Errno 2] No such file or directory: 'tmp/UserscloudCom'
01.03.2018 06:19:46 INFO      Debug Report written to debug_UserscloudCom_01-03-2018_06-19-46.txt
01.03.2018 06:19:46 DEBUG     All downloads processed

**Comment by GammaC0de** [comment]
@davycamps OK, that explains it: your pyload version is not up-to-date, please read #2994

**Comment by davycamps** [comment]
Ah, got it. It's weird I didn't get the latest, I followed the Feral instructions which seemed to download the latest from GitHub: https://www.feralhosting.com/wiki/software/pyload

I'll update now, thanks!

**Comment by GammaC0de** [comment]
👍 Please report of any progress.

**Comment by GammaC0de** [comment]
@davycamps I don't think the instruction in https://www.feralhosting.com/wiki/software/pyload are correct.
Please read #2000 for fresh installation.

**Comment by davycamps** [comment]
@GammaC0de even though it reports "pyLoad 0.4.9" when it's running?

**Comment by GammaC0de** [comment]
Yes.

**Comment by GammaC0de** [comment]
any update?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by davycamps** [comment]
Sorry for now following up. I did manage to get a clean install done on Feral and all is working now as expected. Thanks! I do notice that it will try to download but says waiting before counting down from 50 seconds and keeps repeating this. But I assume this is just an issue with UsersCloud.com.

**Comment by davycamps** [comment]
It eventually failed with "failed TEXTAREA F1 not found"
