### ISSUE TITLE
UpToBox doesn't resolve name

### ISSUE THREAD

**Issue by cmiscloni** [pyload/pyload#3118]
Since latest release, Uptobox seems to not resolve name of downloads

<img width="687" alt="capture d ecran 2018-02-27 a 16 46 54" src="https://user-images.githubusercontent.com/4446733/36738462-d8541486-1bdd-11e8-8abd-913607fe47e0.png">

Thanks

**Comment by GammaC0de** [comment]
The plugin was updated today (https://github.com/pyload/pyload/commit/00300855ff760220850e031eedd5c00e44f84893), please insure you are using the latest plugin (v0.34) and report if it works.

**Comment by cmiscloni** [comment]
Yes still exist with latest version 0.34.
I tried to delete .pyload folder and make a new configuration but it's the same problem

**Comment by GammaC0de** [comment]
@cmiscloni I'm sorry but this works fine for me.
Can you please enable debug mode and then start a download.
I it fails, there will be a HTML file in `<pyload-home-dir>/tmp/UptoboxCom`, zip it and attach it here.

**Comment by cmiscloni** [comment]
I tried to reinstall pyload completely but now, Uptobox account is not detected as Premium too

See below debug file:
[load_line242.dump.html.zip](https://github.com/pyload/pyload/files/1772705/load_line242.dump.html.zip)

Thanks

**Comment by GammaC0de** [comment]
@cmiscloni 
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

Also, please disable geofiltering on the account, thanks.

**Comment by GammaC0de** [comment]
Plugin updated.

**Comment by skillfr** [comment]
Thank you for your work but Uptobox files seems to be unsolved

![image](https://user-images.githubusercontent.com/12272393/37111510-22d58644-2240-11e8-95d5-56a8df876d5c.png)

**Comment by GammaC0de** [comment]
Yes it is, please disable XFileSharing plugin.

**Comment by skillfr** [comment]
Thank you very much it's work ;D
