### ISSUE TITLE
FilerNet: ReCaptcha free downloads not working

### ISSUE THREAD

**Issue by funta23** [pyload/pyload#3120]
Seems[ Filer.net switched to ReCaptcha](http://filer.net/changelog) and plugin is not working anymore since some days.
Can anyone help please? 
Already updated to latest version using new [Updatemanager.py ](https://raw.githubusercontent.com/pyload/pyload/353c6692afdec4b6108555725cb5db46d02ed816/module/plugins/hooks/UpdateManager.py)

Sample URL: http://filer.net/folder/ai3b00umflydtexn

```
01.03.2018 22:05:18 INFO      ADDON UpdateManager: pyLoad is up to date!
01.03.2018 22:05:19 INFO      ADDON XFileSharing: Auto-discover new crypters
01.03.2018 22:05:19 INFO      pyLoad is up and running
01.03.2018 22:05:20 INFO      ADDON UpdateManager: All plugins are up to date!
01.03.2018 22:05:21 INFO      Download starts: abcdefghijklmnop.part10.rar
01.03.2018 22:05:21 WARNING   HOSTER FilerNet[2570]: Plugin may be unstable
01.03.2018 22:05:21 INFO      HOSTER FilerNet[2570]: Grabbing link info...
01.03.2018 22:05:22 INFO      HOSTER FilerNet[2570]: Link name: abcdefghijklmnop.part10.rar
01.03.2018 22:05:22 INFO      HOSTER FilerNet[2570]: Link size: 200.00 MiB (209715300 bytes)
01.03.2018 22:05:22 INFO      HOSTER FilerNet[2570]: Link status: online
01.03.2018 22:05:22 INFO      HOSTER FilerNet[2570]: Processing url: http://filer.net/get/abcdefghijk
01.03.2018 22:05:22 INFO      HOSTER FilerNet[2570]: Looking for direct download link...
01.03.2018 22:05:22 INFO      HOSTER FilerNet[2570]: Direct download link not found
01.03.2018 22:05:22 INFO      HOSTER FilerNet[2570]: Checking for link errors...
01.03.2018 22:05:22 INFO      HOSTER FilerNet[2570]: Waiting 1 minutes...
01.03.2018 22:06:24 INFO      HOSTER FilerNet[2570]: No errors found
01.03.2018 22:06:24 INFO      HOSTER FilerNet[2570]: Processing as free download...
01.03.2018 22:06:25 WARNING   CAPTCHA FilerNet[2570]: ReCaptcha | Secure Token pattern not found
01.03.2018 22:06:25 WARNING   HOSTER FilerNet[2570]: Free download failed | ReCaptcha challenge pattern not found
01.03.2018 22:06:25 WARNING   Download failed: abcdefghijklmnop.part10.rar | ReCaptcha challenge pattern not found

```

**Comment by funta23** [comment]
See http://filer.net/changelog

**Comment by pyblub** [comment]
Yes, it's the same problem as with shareonline and uploaded.

Current progress can be checked here: https://github.com/pyload/pyload/issues/3074

**Comment by Michi-F** [comment]
Solved in my latest commits & ready for testing:
https://github.com/pyload/pyload/issues/3074#issuecomment-370865920

**Comment by funta23** [comment]
Pulled your _all branch and manual FilerNet captcha solving works fine with the tampermonkey script. But 9kw doe not work.
Btw: For ShareOnline it's the other way round: Tampermonkey script isn't loading (altough seems to have correct match url defined) but 9kw works here.

**Comment by pyblub** [comment]
@funta23 ShareOnline should work with Tampermonkey. Are you using https with pyload? Try allowing "mixed active content", see https://kb.iu.edu/d/bdny and https://github.com/pyload/pyload/issues/3074#issuecomment-371108161

**Comment by GammaC0de** [comment]
Closing, refer to #3074 .
