### ISSUE TITLE
Pyload windows version - can't connect to update server

### ISSUE THREAD

**Issue by kveiro** [pyload/pyload#3124]
Hi,
My Pyload no longer connects to the update server. I have actual UpdateManager.py v1.20.
It happened recently, apparently after the github replaced ssl certificate ( I could no longer open a link to the github in the old browser too)

In debug mode I do not see anything informative, only message:

DEBUG     ADDON UpdateManager: LOAD URL https://github.com/p
yload/updates/raw/master/plugins.txt | redirect=True | cookies=True | get={'v':
'0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_
header=False
WARNING   ADDON UpdateManager: Unable to connect to the serv
er to retrieve updates

How to overcome this?
I have win7 x32 and pyload worked fine.

P.S. I can open a link to the list of plugins at least in firefox 34.

**Comment by GammaC0de** [comment]
Open a command prompt and then start pyload with `-d` command line switch and paste the output here.

**Comment by kveiro** [comment]
I executed pyloadcore -d but nothing has changed in log.  ( see above ) I turned off debug mode in web-interface and restarted again with -d. Now it run w/o debug mode.
I'm not sure that pyloadcore understands this option at all.

**Comment by GammaC0de** [comment]
Search for the file `pyLoadCore.py` and then execute `python pyLoadCore.py -d`.

**Comment by Velociraptor85** [comment]
@kveiro did you manage to get the debug log? you might still be using the wrong/old update module thats why we need more data

**Comment by kveiro** [comment]
@GammaC0de "python pyLoadCore.py -d" To do this, I need to install the entire package of python separately. I do not know what launches  .py modules in windows version of pyload, just found \dist\python27.dll
Ok, now it does not matter, the error is found !
In UpdateManager.py i have replaced SERVER_URL to

https://raw.githubusercontent.com/pyload/updates/blablabla

The redirection probably does not work.

@Velociraptor85 Thank you for participating, the problem is solved

**Comment by GammaC0de** [comment]
Solved so closing.

**Comment by m0n4** [comment]
Thank you kveiro !
I can finally update with thi url :
[](https://raw.githubusercontent.com/pyload/updates/master/plugins.txt)

and thanks GammaC0de and all of you guys !
