### ISSUE TITLE
FshareVN captures not the full link in the directory

### ISSUE THREAD

**Issue by bigdargon** [pyload/pyload#3128]
Link in the directory has 55 links, but when added to the pyload only 20 links. Can you fix it? Thank you!
Link https://www.fshare.vn/folder/RZBCIAM1XDRI

**Comment by GammaC0de** [comment]
Give me a link with less than 20 files please, and if possible another with more than 60 files.

**Comment by bigdargon** [comment]
Link <20 files: https://www.fshare.vn/folder/RW11UWPKHC33
Link >60 files: https://www.fshare.vn/folder/97VKWLXPEOV2
