### ISSUE TITLE
Update manager folowing issue #2994

### ISSUE THREAD

**Issue by Petal0u** [pyload/pyload#3129]
Hi all,

here is my first post on pyload issues because i still can't fix my issue.

following issue  #2994 i replaced UpdateManager.py

Now i still have an issue and i tried this fix #2995

here is my debug file 

```
11.03.2018 14:38:52 DEBUG     Deleting old pidfile pyload.pid                                         
11.03.2018 14:38:52 DEBUG     Remote activated: False                                                 
11.03.2018 14:38:56 DEBUG     created index of plugins                                                
11.03.2018 14:38:56 ERROR     Erreur d'importation LinkdecrypterComHook : No module named MultiHook   
Traceback (most recent call last):                                                                    
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                   
    plugins[name]["name"])                                                                            
  File "/usr/share/pyload/module/plugins/hooks/LinkdecrypterComHook.py", line 5, in <module>          
    from module.plugins.internal.MultiHook import MultiHook                                           
ImportError: No module named MultiHook                                                                
11.03.2018 14:38:56 ERROR     Erreur d'importation UpdateManager : No module named misc               
Traceback (most recent call last):                                                                    
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                   
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 12, in <module>                                                                                         
    from ..internal.misc import Expose, encode, exists, fsjoin, threaded                                                                                                       
ImportError: No module named misc                                                                                                                                              
11.03.2018 14:38:56 DEBUG     HOOK ExternalScripts: Deprecated method `event_list`, use `event_map` in                                                                         
stead                                                                                                                                                                          
11.03.2018 14:38:56 ERROR     Erreur d'importation Captcha9Kw : No module named Hook                                                                                           
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/Captcha9Kw.py", line 11, in <module>                                                                                            
    from module.plugins.internal.Hook import Hook, threaded                                                                                                                    
ImportError: No module named Hook                                                                                                                                              
11.03.2018 14:38:56 ERROR     Erreur d'importation PyLoadiOSPush : No module named Hook                                                                                        
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/PyLoadiOSPush.py", line 1, in <module>                                                                                          
    from module.plugins.Hook import Hook, Expose                                                                                                                               
ImportError: No module named Hook                                                                                                                                              
11.03.2018 14:38:56 INFO      Plugins activés: AntiStandby, ExternalScripts, ExtractArchive, UnSkipOnF                                                                         
ail, UserAgentSwitcher                                                                                                                                                         
11.03.2018 14:38:56 INFO      Plugins désactivés: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captch                                                                         
aBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder,                                                                          
IRCInterface, ImageTyperz, JustPremium, MergeFiles, MultiHome, RestartFailed, SkipRev, WindowsPhoneNot                                                                         
ify, XMPPInterface                                                                                                                                                             
11.03.2018 14:38:56 INFO      Temps de téléchargement : True                                                                                                                   
11.03.2018 14:38:57 WARNING   SSL certificates not found.                                                   
```

**Comment by GammaC0de** [comment]
Replcace `/usr/share/pyload/module/plugins/hooks/UpdateManager.py` with https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/830cb0161b416a5328e32516067608cd2cfdd031/UpdateManager.py

**Comment by Petal0u** [comment]
Thank you for your answer.

here are my results

`root@cubietruck:/usr/share/pyload/module/plugins/hooks# cp UpdateManager.py UpdateManager.py.old      
root@cubietruck:/usr/share/pyload/module/plugins/hooks# rm UpdateManager.py                           
root@cubietruck:/usr/share/pyload# python pyLoadCore.py -q                                            
waiting for pyLoad to quit    
pyLoad successfully stopped                                                                           
root@cubietruck:/usr/share/pyload# cd /usr/share/pyload/module/plugins/hooks/    
root@cubietruck:/usr/share/pyload/module/plugins/hooks# wget https://gist.github.com/GammaC0de/a77279b
6588c11aed9c9/raw/830cb0161b416a5328e32516067608cd2cfdd031/UpdateManager.py                           
--2018-03-11 21:32:44--  https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/830cb0161b416a5328
e32516067608cd2cfdd031/UpdateManager.py                                                               
Resolving gist.github.com (gist.github.com)... 192.30.253.118, 192.30.253.119                         
Connecting to gist.github.com (gist.github.com)|192.30.253.118|:443... connected.                     
HTTP request sent, awaiting response... 301 Moved Permanently                                         
Location: https://gist.githubusercontent.com/GammaC0de/a77279b6588c11aed9c9/raw/830cb0161b416a5328e325
16067608cd2cfdd031/UpdateManager.py [following]                                                       
--2018-03-11 21:32:44--  https://gist.githubusercontent.com/GammaC0de/a77279b6588c11aed9c9/raw/830cb01
61b416a5328e32516067608cd2cfdd031/UpdateManager.py                                                    
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 151.101.12.133                   
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|151.101.12.133|:443... connected
.                                                                                                     
HTTP request sent, awaiting response... 200 OK                                                        
Length: 7490 (7.3K) [text/plain]                                                                      
Saving to: ‘UpdateManager.py’                                                                         
                                                                                                      
UpdateManager.py          100%[=====================================>]   7.31K  --.-KB/s   in 0.06s   
                                                                                                      
2018-03-11 21:32:45 (113 KB/s) - ‘UpdateManager.py’ saved [7490/7490]     
`
Seems not working :-(

`root@cubietruck:/usr/share/pyload# python pyLoadCore.py                                               
11.03.2018 21:37:33 INFO      Démarrage pyLoad 0.4.9                                                  
11.03.2018 21:37:33 INFO      Utilisation du dossier principal : /root/.pyload                        
11.03.2018 21:37:33 DEBUG     Remote activated: False                                                 
11.03.2018 21:37:36 DEBUG     created index of plugins                                                
11.03.2018 21:37:36 ERROR     Erreur d'importation LinkdecrypterComHook : No module named MultiHook   
Traceback (most recent call last):                                                                    
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                   
    plugins[name]["name"])                                                                            
  File "/usr/share/pyload/module/plugins/hooks/LinkdecrypterComHook.py", line 5, in <module>          
    from module.plugins.internal.MultiHook import MultiHook                                           
ImportError: No module named MultiHook                                                                
11.03.2018 21:37:36 ERROR     Erreur d'importation UpdateManager : No module named Hook               
Traceback (most recent call last):                                                                    
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                   
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 11, in <module>                                                                                         
    from module.plugins.Hook import threaded, Expose, Hook                                                                                                                     
ImportError: No module named Hook                                                                                                                                              
11.03.2018 21:37:36 DEBUG     HOOK ExternalScripts: Deprecated method `event_list`, use `event_map` in                                                                         
stead                                                                                                                                                                          
11.03.2018 21:37:36 ERROR     Erreur d'importation Captcha9Kw : No module named Hook                                                                                           
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/Captcha9Kw.py", line 11, in <module>                                                                                            
    from module.plugins.internal.Hook import Hook, threaded                                                                                                                    
ImportError: No module named Hook                                                                                                                                              
11.03.2018 21:37:36 ERROR     Erreur d'importation PyLoadiOSPush : No module named Hook                                                                                        
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/PyLoadiOSPush.py", line 1, in <module>                                                                                          
    from module.plugins.Hook import Hook, Expose                                                                                                                               
ImportError: No module named Hook                                                                                                                                              
11.03.2018 21:37:36 INFO      Plugins activés: AntiStandby, ExternalScripts, ExtractArchive, UnSkipOnF                                                                         
ail, UserAgentSwitcher                                                                             
11.03.2018 21:37:36 INFO      Plugins désactivés: AndroidPhoneNotify, AntiVirus, BypassCaptcha, Captch                                                                         
aBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder,                                                                          
IRCInterface, ImageTyperz, JustPremium, MergeFiles, MultiHome, RestartFailed, SkipRev, WindowsPhoneNot                                                                         
ify, XMPPInterface                                                                                                                                                             
11.03.2018 21:37:36 INFO      Temps de téléchargement : True                                                                                                                   
11.03.2018 21:37:37 WARNING   SSL certificates not found.                                                                                                                      
11.03.2018 21:37:37 INFO      Free space: 328.68 GiB                                                                                                                           
11.03.2018 21:37:37 INFO      Starting threaded webserver: 0.0.0.0:8000                                                                                                        
11.03.2018 21:37:37 INFO      Activating Accounts...                                                                                                                           
11.03.2018 21:37:37 INFO      Activating Plugins...                                                                                                                            
11.03.2018 21:37:37 WARNING   HOOK AntiStandby: Unable to change system power state | [Errno 2] No such file or directory                                                                                                                                                            
xset:  unable to open display ""                                                                                                                                               
11.03.2018 21:37:37 DEBUG     HOOK ExtractArchive: Found UnRar 5.21 | Found UnZip 2.7.9                                                                                        
11.03.2018 21:37:38 INFO      pyLoad is up and running                                                                                                                         

`

**Comment by GammaC0de** [comment]
Start pyload with the command `python pyLoadCore.py -d`

**Comment by Petal0u** [comment]
Hi GammaC0de, thanks for your help.

here is the result for python pyLoadCore.py -d 

root@cubietruck:~# cd /usr/share/pyload/                                                                                                                                       
root@cubietruck:/usr/share/pyload# ls                                                                                                                                          
icons  LICENSE  locale  module  pavement.py  pyLoadCli.py  pyLoadCore.py  README  scripts  setup.cfg  systemCheck.py  testlinks.txt  tests                                     
root@cubietruck:/usr/share/pyload# python pyLoadCore.py -q                                                                                                                     
waiting for pyLoad to quit                                                                                                                                                     
pyLoad successfully stopped                                                                                                                                                    
root@cubietruck:/usr/share/pyload# python pyLoadCore.py -d                                                                                                                     
12.03.2018 20:14:27 INFO      Démarrage pyLoad 0.4.9                                                                                                                           
12.03.2018 20:14:27 INFO      Utilisation du dossier principal : /root/.pyload                                                                                                 
12.03.2018 20:14:27 DEBUG     Remote activated: False                                                                                                                          
12.03.2018 20:14:28 DEBUG     created index of plugins                                                                                                                         
12.03.2018 20:14:28 ERROR     Erreur d'importation LinkdecrypterComHook : No module named MultiHook                                                                            
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/LinkdecrypterComHook.py", line 5, in <module>                                                                                   
    from module.plugins.internal.MultiHook import MultiHook                                                                                                                    
ImportError: No module named MultiHook                                                                                                                                         
12.03.2018 20:14:28 ERROR     Erreur d'importation UpdateManager : No module named Hook                                                                                        
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 11, in <module>                                                                                         
    from module.plugins.Hook import threaded, Expose, Hook                                                                                                                     
ImportError: No module named Hook                                                                                                                                              
12.03.2018 20:14:28 DEBUG     HOOK ExternalScripts: Deprecated method `event_list`, use `event_map` instead                                                                    
12.03.2018 20:14:28 ERROR     Erreur d'importation Captcha9Kw : No module named Hook                                                                                           
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/Captcha9Kw.py", line 11, in <module>                                                                                            
    from module.plugins.internal.Hook import Hook, threaded                                                                                                                    
ImportError: No module named Hook                                                                                                                                              
12.03.2018 20:14:28 ERROR     Erreur d'importation PyLoadiOSPush : No module named Hook                                                                                        
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/PyLoadiOSPush.py", line 1, in <module>                                                                                          
    from module.plugins.Hook import Hook, Expose                                                                                                                               
ImportError: No module named Hook                                                                                                                                              
12.03.2018 20:14:28 INFO      Plugins activés: AntiStandby, ExternalScripts, ExtractArchive, UnSkipOnFail, UserAgentSwitcher                                                   
12.03.2018 20:14:28 INFO      Plugins désactivés: AndroidPhoneNotify, AntiVirus, BypassCaptcha, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler
, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, MergeFiles, MultiHome, RestartFailed, SkipRev, WindowsPhoneNotify, XMPPInterface                          
12.03.2018 20:14:28 INFO      Temps de téléchargement : True                                                                                                                   
12.03.2018 20:14:28 INFO      Espace libre : 328.68 GiB                                                                                                                        
12.03.2018 20:14:28 INFO      Activation des comptes ...                                                                                                                       
12.03.2018 20:14:28 INFO      Activation des Extensions...                                                                                                                     
12.03.2018 20:14:29 WARNING   SSL certificates not found.                                                                                                                      
12.03.2018 20:14:29 INFO      Starting threaded webserver: 0.0.0.0:8000                                                                                                        
12.03.2018 20:14:29 WARNING   HOOK AntiStandby: Unable to change system power state | [Errno 2] No such file or directory                                                      
xset:  unable to open display ""                                                                                                                                               
12.03.2018 20:14:29 DEBUG     HOOK ExtractArchive: Found UnRar 5.21 | Found UnZip 2.7.9                                                                                        
12.03.2018 20:14:29 INFO      pyLoad is up and running

**Comment by GammaC0de** [comment]
Delete the forlder `/root/.pyload/userplugins` and run`python pyLoadCore.py -d` again.

**Comment by Petal0u** [comment]
```
root@cubietruck:~/.pyload#cd /root/.pyload/                                                                                                                     
root@cubietruck :~/.pyload# rm -r userplugins/                                                                                                               
root@cubietruck:~/.pyload# cd /usr/share/pyload/                                                                                                                               
root@cubietruck:/usr/share/pyload# python pyLoadCore.py -d                                                                                                                     
12.03.2018 22:58:31 INFO      Démarrage pyLoad 0.4.9                                                                                                                           
12.03.2018 22:58:31 INFO      Utilisation du dossier principal : /root/.pyload                                                                                                 
12.03.2018 22:58:31 DEBUG     Deleting old pidfile pyload.pid                                                                                                                  
12.03.2018 22:58:31 DEBUG     Remote activated: False                                                                                                                          
12.03.2018 22:58:35 DEBUG     created index of plugins                                                                                                                         
12.03.2018 22:58:35 ERROR     Erreur d'importation LinkdecrypterComHook : No module named MultiHook                                                                            
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/LinkdecrypterComHook.py", line 5, in <module>                                                                                   
    from module.plugins.internal.MultiHook import MultiHook                                                                                                                    
ImportError: No module named MultiHook                                                                                                                                         
12.03.2018 22:58:35 ERROR     Erreur d'importation UpdateManager : No module named Hook                                                                                        
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 11, in <module>                                                                                         
    from module.plugins.Hook import threaded, Expose, Hook                                                                                                                     
ImportError: No module named Hook                                                                                                                                              
12.03.2018 22:58:35 DEBUG     HOOK ExternalScripts: Deprecated method `event_list`, use `event_map` instead                                                                    
12.03.2018 22:58:35 ERROR     Erreur d'importation Captcha9Kw : No module named Hook                                                                                           
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/Captcha9Kw.py", line 11, in <module>                                                                                            
    from module.plugins.internal.Hook import Hook, threaded                                                                                                                    
ImportError: No module named Hook                                                                                                                                              
12.03.2018 22:58:35 ERROR     Erreur d'importation PyLoadiOSPush : No module named Hook                                                                                        
Traceback (most recent call last):                                                                                                                                             
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule                                                                                            
    plugins[name]["name"])                                                                                                                                                     
  File "/usr/share/pyload/module/plugins/hooks/PyLoadiOSPush.py", line 1, in <module>                                                                                          
    from module.plugins.Hook import Hook, Expose                                                                                                                               
ImportError: No module named Hook                                   
12.03.2018 22:58:35 INFO      Plugins activés: AntiStandby, ExternalScripts, ExtractArchive, UnSkipOnFail, UserAgentSwitcher                                                   
12.03.2018 22:58:35 INFO      Plugins désactivés: AndroidPhoneNotify, AntiVirus, BypassCaptcha, CaptchaBrotherhood, Checksum, DeathByCaptcha, DeleteFinished, DownloadScheduler
, ExpertDecoders, HotFolder, IRCInterface, ImageTyperz, JustPremium, MergeFiles, MultiHome, RestartFailed, SkipRev, WindowsPhoneNotify, XMPPInterface                          
12.03.2018 22:58:35 INFO      Temps de téléchargement : True                                                                                                                   
12.03.2018 22:58:35 WARNING   SSL certificates not found.                                                                                                                      
12.03.2018 22:58:35 INFO      Free space: 328.68 GiB                                                                                                                           
12.03.2018 22:58:35 INFO      Starting threaded webserver: 0.0.0.0:8000                                                                                                        
12.03.2018 22:58:35 INFO      Activating Accounts...                                                                                                                           
12.03.2018 22:58:35 INFO      Activating Plugins...                                                                                                                            
12.03.2018 22:58:35 WARNING   HOOK AntiStandby: Unable to change system power state | [Errno 2] No such file or directory                                                      
xset:  unable to open display ""                                                                                                                                               
12.03.2018 22:58:36 DEBUG     HOOK ExtractArchive: Found UnRar 5.21 | Found UnZip 2.7.9                                                                                        
12.03.2018 22:58:36 INFO      pyLoad is up and running         
```

**Comment by GammaC0de** [comment]
How exactly did you installed pyload?

**Comment by Petal0u** [comment]
that's a long time i installed pyload (4 years ago) on a cubietruck. 

I think i followed raspberry method because cubietruck is an arm computer with [debian Jessie.](https://www.armbian.com/cubietruck/)

**Comment by GammaC0de** [comment]
I recommend you uninstall and then reinstall.

**Comment by Petal0u** [comment]
Thanks @GammaC0de 
How do i uninstall ? Do i simply remove folders ?
Do i reinstall using raspberry way ?

**Comment by GammaC0de** [comment]
I think you should do `sudo apt remove pyload'

**Comment by Petal0u** [comment]
done and then ?

**Comment by Velociraptor85** [comment]
hi @Petal0u try that setup https://github.com/pyload/pyload/issues/2000
