### ISSUE TITLE
issues with k2s and filejoker

### ISSUE THREAD

**Issue by digimon04** [pyload/pyload#3131]
Recently, I have re-installed pyload in my router through Entware-ng. After that, I found I can no longer download any file on k2s and filejoker. For k2s, I have also tried to replace the HTTPRequest.py as per instructed here: https://github.com/pyload/pyload/issues/2940. However, the issue remains. Below are the logs.

k2s (failedParse error: Unique-ID pattern not found | Plugin may be out of date 0.00 BKeep2ShareCc)
(tested url: http://k2s.cc/file/4809615e6855b):

> 13.03.2018 19:23:53 | INFO | Download starts: 4809615e6855b
> 598 | 13.03.2018 19:23:53 | WARNING | HOSTER Keep2ShareCc[13]: Plugin may be unstable
> 599 | 13.03.2018 19:23:53 | INFO | HOSTER Keep2ShareCc[13]: Grabbing link info...
> 600 | 13.03.2018 19:23:55 | INFO | HOSTER Keep2ShareCc[13]: Link name: 4809615e6855b
> 601 | 13.03.2018 19:23:55 | INFO | HOSTER Keep2ShareCc[13]: Link size: N/D
> 602 | 13.03.2018 19:23:55 | INFO | HOSTER Keep2ShareCc[13]: Link status: starting
> 603 | 13.03.2018 19:23:55 | INFO | HOSTER Keep2ShareCc[13]: Processing url: http://k2s.cc/file/4809615e6855b
> 604 | 13.03.2018 19:23:57 | INFO | HOSTER Keep2ShareCc[13]: Grabbing link info...
> 605 | 13.03.2018 19:23:57 | INFO | HOSTER Keep2ShareCc[13]: Link name: 4809615e6855b
> 606 | 13.03.2018 19:23:57 | INFO | HOSTER Keep2ShareCc[13]: Link size: N/D
> 607 | 13.03.2018 19:23:57 | INFO | HOSTER Keep2ShareCc[13]: Link status: starting
> 608 | 13.03.2018 19:23:57 | INFO | HOSTER Keep2ShareCc[13]: Processing as free download...
> 609 | 13.03.2018 19:23:59 | WARNING | Download failed: 4809615e6855b \| Parse error: Unique-ID pattern not found \| Plugin may be out of date
> 610 | 13.03.2018 19:23:59 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: 4809615e6855b (pid:5)
> 611 | 13.03.2018 19:23:59 | INFO | ADDON UnSkipOnFail: No duplicates found

filejoker (failedReCaptcha challenge pattern not found 237.90 MiBFilejokerNet)
(tested url: https://filejoker.net/fx34sp1xl1ar):

> 612 | 13.03.2018 19:24:06 | INFO | Download starts: ZEOD-53_02.mp4
> 613 | 13.03.2018 19:24:06 | WARNING | HOSTER FilejokerNet[14]: Plugin may be unstable
> 614 | 13.03.2018 19:24:06 | INFO | HOSTER FilejokerNet[14]: Grabbing link info...
> 615 | 13.03.2018 19:24:07 | INFO | HOSTER FilejokerNet[14]: Link name: ZEOD-53_02.mp4
> 616 | 13.03.2018 19:24:07 | INFO | HOSTER FilejokerNet[14]: Link size: 237.90 MiB (249456230 bytes)
> 617 | 13.03.2018 19:24:07 | INFO | HOSTER FilejokerNet[14]: Link status: online
> 618 | 13.03.2018 19:24:07 | INFO | HOSTER FilejokerNet[14]: Processing url: https://filejoker.net/fx34sp1xl1ar
> 619 | 13.03.2018 19:24:08 | INFO | HOSTER FilejokerNet[14]: Checking for link errors...
> 620 | 13.03.2018 19:24:08 | INFO | HOSTER FilejokerNet[14]: No errors found
> 621 | 13.03.2018 19:24:08 | INFO | HOSTER FilejokerNet[14]: Processing as free download...
> 622 | 13.03.2018 19:24:08 | INFO | HOSTER FilejokerNet[14]: Checking for link errors...
> 623 | 13.03.2018 19:24:08 | INFO | HOSTER FilejokerNet[14]: No errors found
> 624 | 13.03.2018 19:24:09 | WARNING | CAPTCHA FilejokerNet[14]: ReCaptcha \| Key pattern not found
> 625 | 13.03.2018 19:24:09 | INFO | HOSTER FilejokerNet[14]: Checking for link errors...
> 626 | 13.03.2018 19:24:09 | INFO | HOSTER FilejokerNet[14]: No errors found
> 627 | 13.03.2018 19:24:09 | WARNING | CAPTCHA FilejokerNet[14]: ReCaptcha \| Secure Token pattern not found
> 628 | 13.03.2018 19:24:09 | WARNING | Download failed: ZEOD-53_02.mp4 \| ReCaptcha challenge pattern not found
> 629 | 13.03.2018 19:24:09 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: ZEOD-53_02.mp4 (pid:6)
> 630 | 13.03.2018 19:24:09 | INFO | ADDON UnSkipOnFail: No duplicates found

It seems pyload can't find the file size from k2s while it can correctly capture the file size in filejoker but none of them can be downloaded. Any help is appreciated. Thanks.

**Comment by pyblub** [comment]
Both hosters have switched to ReCaptcha v2. Same problem as here: https://github.com/pyload/pyload/issues/3074
A solution under construction.

**Comment by GammaC0de** [comment]
k2s  uses recaptcha *sometimes*, so it might help if you retry the download.
