### ISSUE TITLE
new problem uptobox

### ISSUE THREAD

**Issue by fugitif** [pyload/pyload#3132]
Hello
I have a new problem with Qpyload.  I have this probleme 1 day ago.
the first DL Is ok but nexts downloads it s OK with bad file name 

desinstallé et reinstallé voici le 1 er package
56	13.03.2018 15:18:27	INFO	Download starts: https://uptobox.com/qqa4dd82m94k
57	13.03.2018 15:18:27	WARNING	HOSTER UptoboxCom[1]: Plugin may be unstable
58	13.03.2018 15:18:27	INFO	HOSTER UptoboxCom[1]: Grabbing link info...
59	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Link name: calcul EFFECTIF vierge modele22.xlsm
60	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Link size: 73.51 KiB (75274 bytes)
61	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Link status: en ligne
62	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Processing url: https://uptobox.com/qqa4dd82m94k
63	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Looking for direct download link...
64	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Direct download link not found
65	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Checking for link errors...
66	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: No errors found
67	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Processing as free download...
68	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Downloading file...
69	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: File saved
70	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Checking download...
71	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: File is OK
72	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Checking file (with built-in rules)...
73	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Checking file (with custom rules)...
74	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: Checking for link errors...
75	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: No errors found
76	13.03.2018 15:18:28	INFO	HOSTER UptoboxCom[1]: No errors found
77	13.03.2018 15:18:28	INFO	Download finished: calcul EFFECTIF vierge modele22.xlsm
78	13.03.2018 15:18:28	INFO	Package finished: test1
79	13.03.2018 15:18:28	INFO	ADDON ExtractArchive: Check package: test1

It s ok

second DL

195	13.03.2018 15:24:04	INFO	Download starts: qqa4dd82m94k
196	13.03.2018 15:24:04	WARNING	HOSTER XFileSharing[2]: UptoboxCom | Plugin may be unstable
197	13.03.2018 15:24:04	INFO	ACCOUNT UptoboxCom: Grabbing account info for user `vin*******`...
198	13.03.2018 15:24:04	INFO	HOSTER XFileSharing[2]: UptoboxCom | Grabbing link info...
199	13.03.2018 15:24:04	INFO	HOSTER XFileSharing[2]: UptoboxCom | Link name: qqa4dd82m94k
200	13.03.2018 15:24:04	INFO	HOSTER XFileSharing[2]: UptoboxCom | Link size: N/D
201	13.03.2018 15:24:04	INFO	HOSTER XFileSharing[2]: UptoboxCom | Link status: demarrage
202	13.03.2018 15:24:04	INFO	HOSTER XFileSharing[2]: UptoboxCom | Processing url: https://uptobox.com/qqa4dd82m94k
203	13.03.2018 15:24:04	INFO	HOSTER XFileSharing[2]: UptoboxCom | Looking for direct download link...
204	13.03.2018 15:24:04	INFO	HOSTER XFileSharing[2]: UptoboxCom | Direct download link detected
205	13.03.2018 15:24:04	INFO	HOSTER XFileSharing[2]: UptoboxCom | Downloading file...
206	13.03.2018 15:24:05	INFO	HOSTER XFileSharing[2]: UptoboxCom | File saved
207	13.03.2018 15:24:05	INFO	HOSTER XFileSharing[2]: UptoboxCom | Checking download...
208	13.03.2018 15:24:05	INFO	HOSTER XFileSharing[2]: UptoboxCom | File is OK
209	13.03.2018 15:24:05	INFO	HOSTER XFileSharing[2]: UptoboxCom | Checking file (with built-in rules)...
210	13.03.2018 15:24:05	INFO	HOSTER XFileSharing[2]: UptoboxCom | Checking file (with custom rules)...
211	13.03.2018 15:24:05	INFO	HOSTER XFileSharing[2]: UptoboxCom | Checking for link errors...
212	13.03.2018 15:24:05	INFO	HOSTER XFileSharing[2]: UptoboxCom | No errors found
213	13.03.2018 15:24:05	INFO	HOSTER XFileSharing[2]: UptoboxCom | No errors found
214	13.03.2018 15:24:05	INFO	Download finished: qqa4dd82m94k
215	13.03.2018 15:24:05	INFO	Package finished: test 2
216	13.03.2018 15:24:05	INFO	ADDON ExtractArchive: Check package: test 2

It s KO..

**Comment by GammaC0de** [comment]
Disable XFileSharing plugin

**Comment by fugitif** [comment]
It s ok  tank you

**Comment by fugitif** [comment]
Thank you*

**Comment by GammaC0de** [comment]
:+1:
