### ISSUE TITLE
Updating reCAPTCHA V2 API & Webinterface

### ISSUE THREAD

**Issue by morefreedom** [pyload/pyload#3134]
Hi,

i'm running pyload v0.4.9 on a raspberry pi. All worked fine.
I manually replace UpdateManager.py from https://github.com/pyload/pyload/issues/2994 to get Updates furthermore.
Log-Entry says: 
```
ADDON UpdateManager: pyLoad is up to date!
ADDON UpdateManager: All plugins are up to date!
```
To update the hoster plugins share-online.biz, uploaded.net and filer.net to the new reCAPTCHA V2 API i replaced files by this ones: https://github.com/pyload/pyload/pull/3126
To fix Webinterface i replaced files from here: https://github.com/pyload/pyload/pull/3125

I use the default theme, so i had to:

change module/Api.py
change module/CaptchaManager.py
new module/plugins/captcha/ReCaptcha.py
new module/plugins/captcha/ReCaptchaV2_userscript.js
new module/plugins/internal/Captcha.py
change module/web/json_app.py
change module/web/media/js/base.js from module/web/media/js/classic/base.js
new module/web/media/js/recaptcha-v2-interactive.js from module/web/media/js/classic/recaptcha-v2-interactive.js
new module/web/media/default/css/styles.css from module/web/media/pyplex/css/styles.css
change module/web/templates/default/base.html from module/web/templates/classic/base.html
change module/web/templates/default/captcha.html from module/web/templates/classic/captcha.html

After restart i got:

> Critical  error while processing request:

Where is the Log-File stored?

**Comment by pyblub** [comment]
https://github.com/pyload/pyload/pull/3126 are just the changes for the hosters. You need the changes for pyload to work with ReCaptcha v2. The easiest way is to clone/checkout https://github.com/Michi-F/pyload/tree/recaptcha_v2_all this contains both. You will also need tampermonkey and the userscript from: https://github.com/Michi-F/pyload/blob/recaptcha_v2_all/module/plugins/captcha/ReCaptchaV2_userscript.js

**Comment by morefreedom** [comment]
Ok, i installed everything new. Classic theme seems to work now.
In chrome (with Tampermonkey) i don't see any captchas:
![image](https://user-images.githubusercontent.com/37485529/37566350-28e84b68-2ab8-11e8-85cd-6594d2b14e5f.png)
Script is in /opt/pyload/module/plugins/captcha
![image](https://user-images.githubusercontent.com/37485529/37566393-db84f712-2ab8-11e8-9aef-c888387fb63a.png)
With activated https it doesn't work:
![image](https://user-images.githubusercontent.com/37485529/37566468-bac85d10-2ab9-11e8-88ea-879b1aabe06d.png)



Thanks for help.

**Comment by pyblub** [comment]
You need to add the userscript to tampermonkey.

Also, if you use pyload with https (as you should), you need to deactivate protection against mixed active content: https://kb.iu.edu/d/bdny (this is a problem, because some hosters do not use https.)

**Comment by morefreedom** [comment]
Got it. Now it works perfect.
@pyblub Thanks a lot.
