### ISSUE TITLE
Pyload Updated and stopped working on my QNAP

### ISSUE THREAD

**Issue by Maverick237** [pyload/pyload#3135]
Hello,

I updated my Pyload to to 180305 version.
Unfortunately i cannot download anything ... it asks for captcha every time.

Any idea how to resolve it?

**Comment by GammaC0de** [comment]
Hi,
Sorry for late delay.
Did you managed to solve this?

**Comment by Maverick237** [comment]
Hi,

No, i didn't . Please let me know how to resolve it.

**Comment by GammaC0de** [comment]
Try this:
https://qnapclub.eu/fr/qpkg/model/download/462832/QPyload_180305_x86_64.qpkg

**Comment by Maverick237** [comment]
Now files set to download ... change status for "starting" and after a few seconds it changes for "finished". However nothing is downloaded.

**Comment by GammaC0de** [comment]
Go to pyLoad's configuration  and see what is the download folder.

Also, the log can help if you turn on debug mode.

**Comment by Maverick237** [comment]
Is it ok if i wrote in the "download folder"?
/share/CACHEDEV1_DATA/Download/pyload

**Comment by Maverick237** [comment]
The result is the same. "Starting" and after a few seconds "Finished".

**Comment by GammaC0de** [comment]
OK, so enable debug mode, retry and post the log.

**Comment by Maverick237** [comment]
`

82 | 24.03.2018 20:06:34 | DEBUG | HOSTER RapideoPl[2]: RapideoPl \| LOAD URL http://catshare.net/xwwpgxcV06nwWSzw/The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
-- | -- | -- | --
83 | 24.03.2018 20:06:34 | INFO | HOSTER RapideoPl[2]: RapideoPl \| Checking for link errors...
84 | 24.03.2018 20:06:34 | INFO | HOSTER RapideoPl[2]: RapideoPl \| No errors found
85 | 24.03.2018 20:06:34 | INFO | HOSTER RapideoPl[2]: RapideoPl \| Grabbing link info...
86 | 24.03.2018 20:06:34 | DEBUG | HOSTER RapideoPl[2]: RapideoPl \| Link info: {'status': 7, 'hash': {}, 'name': 'The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar', 'url': u'http://catshare.net/xwwpgxcV06nwWSzw/The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar', 'pattern': {}, 'size': 0}
87 | 24.03.2018 20:06:34 | DEBUG | HOSTER RapideoPl[2]: RapideoPl \| Previous link info: {'status': 7, 'hash': {}, 'name': 'The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar', 'url': u'http://catshare.net/xwwpgxcV06nwWSzw/The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar', 'pattern': {}, 'size': 0}
88 | 24.03.2018 20:06:34 | INFO | HOSTER RapideoPl[2]: RapideoPl \| Link name: The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar
89 | 24.03.2018 20:06:34 | INFO | HOSTER RapideoPl[2]: RapideoPl \| Link size: N/D
90 | 24.03.2018 20:06:34 | INFO | HOSTER RapideoPl[2]: RapideoPl \| Link status: rozpoczynam
91 | 24.03.2018 20:06:34 | INFO | HOSTER RapideoPl[2]: RapideoPl \| Processing as free download...
92 | 24.03.2018 20:06:34 | DEBUG | HOSTER RapideoPl[2]: RapideoPl \| {'username': 'Mav*******', 'loc': 1, 'url': u'http://catshare.net/xwwpgxcV06nwWSzw/The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar', 'site': 'newrd', 'output': 'json', 'password': '07cf5fa11ba874efb6279ecf09e45dfe', 'check': 2}
93 | 24.03.2018 20:06:34 | DEBUG | HOSTER RapideoPl[2]: RapideoPl \| LOAD URL http://enc.rapideo.pl \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={'username': 'Mav*******', 'loc': 1, 'url': u'http://catshare.net/xwwpgxcV06nwWSzw/The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar', 'site': 'newrd', 'output': 'json', 'password': '07cf5fa11ba874efb6279ecf09e45dfe', 'check': 2} \| ref=True \| just_header=False
94 | 24.03.2018 20:06:37 | DEBUG | HOSTER RapideoPl[2]: RapideoPl \| {u'uniquequeue': None, u'cookies': None, u'uniquesession': None, u'url': u'http://catshare.net/xwwpgxcV06nwWSzw/The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar', u'happyadd': u'1', u'directlink': None, u'hosting': u'catshare', u'filename': u'The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar', u'filesize': u'3274912563', u'uniquehash': None, u'chargeuser': 3274912563, u'additional_params2': None, u'sdownload': u'0'}
95 | 24.03.2018 20:06:37 | DEBUG | HOSTER RapideoPl[2]: RapideoPl \| {'username': 'Mav*******', 'output': 'json', 'password': '07cf5fa11ba874efb6279ecf09e45dfe', 'url': u'http://catshare.net/xwwpgxcV06nwWSzw/The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar', 'site': 'newrd'}
96 | 24.03.2018 20:06:37 | DEBUG | HOSTER RapideoPl[2]: RapideoPl \| LOAD URL http://enc.rapideo.pl \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={'username': 'Mav*******', 'output': 'json', 'password': '07cf5fa11ba874efb6279ecf09e45dfe', 'url': u'http://catshare.net/xwwpgxcV06nwWSzw/The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar', 'site': 'newrd'} \| ref=True \| just_header=False
97 | 24.03.2018 20:06:38 | INFO | HOSTER RapideoPl[2]: RapideoPl \| Downloading file...
98 | 24.03.2018 20:06:38 | DEBUG | HOSTER RapideoPl[2]: RapideoPl \| DOWNLOAD URL http://rcdn.rapideo.pl/?ENCbXxzeHEgO2hueG9zfHB4IFB8a3hvdH52Ly47bXxubmpyb3kgLSp%2Beyh7fCwsf3wlKil4e38rLyokeH57LSR4KSh5e3g7dHN7ciA7aG9xIHVpaW0nMjJ%2BfGludXxveDNzeGkyZWpqbXplfkstK3NqSk5najJJdXgzVXRpcHxzbjNfcnlkemh8b3kzLy0sKjNQSFFJdDMsLSUtbTNfcWhPfGQzZS8rKTBWdFZSM218b2kvM298bzt%2BdXh%2BdiA7aW9kdHN6IDtveHt4b3hvIDtudGl4IHN4am95O3FyfnxxIDtudXxveCA7dHNueG9pIDtxfHN6IDttcWh6dHMgO254fG9%2BdSA7b3JoaXggO254bm50cnMgO3V8bW1kfHl5IDtpeHBtIDt1fG51IDtyaGltaGkgd25ycztsaHhoeCA7b3hsaHhuaUJ0bSA7bm5xcnMgLTtubnFye3sgO3p4aWlvfHt7dH4gO3Vybml8fn50eSA7fG10eG9vIDtuaXxvaXlxIDtqfGl%2BdSA7b3hsdG0gO294eXRveG9vIDtvcmhpeHJ7eyA7eXRveH5pcXRzdnJ7eyA7f3RzeXRtIDtveHl0b3h%2BaWlyIDttb3JlZCA7eXNucnt7IDtxcn58cW54b2t4byA7c3J0c254b2kgO25wbn5yeXggO3x5eXt0cXhzfHB4IDt5dG58f3F4fnx%2BdXggO3xoeXRyIDtrdHl4ciA7cHkoICklfisvKC14fysvfHsleX4lJCp4Ky57eX4rK3kqf3l%2F \| fixurl=True \| resume=None \| get={} \| cookies=True \| disposition=True \| chunks=None \| post={} \| ref=True
99 | 24.03.2018 20:06:38 | INFO | HOSTER RapideoPl[2]: RapideoPl \| File saved
100 | 24.03.2018 20:06:38 | INFO | HOSTER RapideoPl[2]: RapideoPl \| Checking download...
101 | 24.03.2018 20:06:38 | INFO | HOSTER RapideoPl[2]: RapideoPl \| File is OK
102 | 24.03.2018 20:06:38 | INFO | HOSTER RapideoPl[2]: RapideoPl \| Checking file (with built-in rules)...
103 | 24.03.2018 20:06:38 | INFO | HOSTER RapideoPl[2]: RapideoPl \| Checking file (with custom rules)...
104 | 24.03.2018 20:06:38 | INFO | HOSTER RapideoPl[2]: RapideoPl \| Checking for link errors...
105 | 24.03.2018 20:06:38 | INFO | HOSTER RapideoPl[2]: RapideoPl \| No errors found
106 | 24.03.2018 20:06:38 | INFO | HOSTER RapideoPl[2]: RapideoPl \| No errors found
107 | 24.03.2018 20:06:38 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
108 | 24.03.2018 20:06:38 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
109 | 24.03.2018 20:06:38 | INFO | Download finished: The.Hitmans.Bodyguard.2017.MULTi.1080p.BluRay.x264-KiKO.part2.rar
110 | 24.03.2018 20:06:38 | DEBUG | ADDON ExternalScripts: No script found under folder `download_finished`
111 | 24.03.2018 20:06:38 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
112 | 24.03.2018 20:06:38 | DEBUG | All downloads processed
113 | 24.03.2018 20:06:38 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_finished`
114 | 24.03.2018 20:06:38 | DEBUG | All downloads finished

`

**Comment by GammaC0de** [comment]
Is there any file inside /share/CACHEDEV1_DATA/Download/pyload?

I tried to download the URL in line 98 of the log and it works (with a browser though).

**Comment by Maverick237** [comment]
I have all downloaded files under this path.
There are folders and a few files.
I know that the url (line 98) works, but i don't know it cannot be downloaded through pyload.

**Comment by GammaC0de** [comment]
Thefile of the URL in line 98 should be around 3GB

**Comment by Maverick237** [comment]
Yes, that is right.

**Comment by GammaC0de** [comment]
so it is working fine, no?

**Comment by GammaC0de** [comment]
> However nothing is downloaded.

Why do you said so if the is a file insde `/share/CACHEDEV1_DATA/Download/pyload`?

**Comment by Maverick237** [comment]
I downloaded the file and i got it the file with 22 Kb of size instead of 3 GB

**Comment by GammaC0de** [comment]
What is the content of the file?

**Comment by Maverick237** [comment]
it is a video.

**Comment by GammaC0de** [comment]
No, I meant what is the content of the  22 Kb file?

**Comment by Maverick237** [comment]
the file (22 kb) looks like mkv file ... only the size is not correct.

**Comment by GammaC0de** [comment]
Whay OS are you running? 
Linux?
Type `cat <downloaded_file.mkv>`

**Comment by Maverick237** [comment]
I don't know. I use QNAP Software, pyload add through App Center and that is all.

**Comment by Maverick237** [comment]
> Type cat <downloaded_file.mkv>

What do you mean?

**Comment by GammaC0de** [comment]
If you open the file with notepad, what do you see?

**Comment by Maverick237** [comment]
i see this in the file:

> 70=lacking parameters

**Comment by GammaC0de** [comment]
If you try to download a normal file like https://qnapclub.eu/fr/qpkg/model/download/462832/QPyload_180305_x86_64.qpkg , does it work OK?

**Comment by Maverick237** [comment]
yes, it works.

**Comment by GammaC0de** [comment]
So it seems like a problem with RapideoPl plugin.

Account information is needed for testing, please set to a temporary password and then send account user and password and the URL you had tried to download to nitzo2001 at yahoo dot com.

**Comment by Maverick237** [comment]
ok one moment

**Comment by Maverick237** [comment]
email sent, please check it.

**Comment by GammaC0de** [comment]
Got it.

**Comment by Maverick237** [comment]
OK. Do you want to test it now or we have to continue tomorrow?

**Comment by GammaC0de** [comment]
I will test and update you if any progress.

**Comment by Maverick237** [comment]
ok fine

**Comment by GammaC0de** [comment]
Is this a premium account?

**Comment by Maverick237** [comment]
yes it is

**Comment by Maverick237** [comment]
did you fix that?

**Comment by GammaC0de** [comment]
Yes

**Comment by Maverick237** [comment]
do i have to install the pyload again?

**Comment by GammaC0de** [comment]
No, just restart it and it should update the plugin.

**Comment by Maverick237** [comment]
restarted ... still the same problem.

**Comment by GammaC0de** [comment]
According to the log, what plugin version do you use?

**Comment by Maverick237** [comment]
Plugin version: 0.12
--

**Comment by GammaC0de** [comment]
You should be using 0.13.
See #2994

**Comment by Maverick237** [comment]
ok i will update this tomorrow.

**Comment by Maverick237** [comment]
Now all works perfecty, thank you.

**Comment by GammaC0de** [comment]
👍
