### ISSUE TITLE
MegaCoNz don't find

### ISSUE THREAD

**Issue by asdrubale1970** [pyload/pyload#3136]
hello I can not enter user and password of mega.nz
what should I do
thank you

**Comment by asdrubale1970** [comment]
i have not filed mega
![mega](https://user-images.githubusercontent.com/37486959/38379677-bd336ec2-3901-11e8-9699-a28e49cbd673.png)

**Comment by GammaC0de** [comment]
Please read https://github.com/pyload/pyload/issues/2994 and #2000

**Comment by GammaC0de** [comment]
Any update?

**Comment by asdrubale1970** [comment]
perfect 
i have make new install and replace updatemanager.py

thank you very muc

**Comment by GammaC0de** [comment]
:+1:
