### ISSUE TITLE
UptoboxCom : download failed (TEXTAREA F1 not found)

### ISSUE THREAD

**Issue by moacmoa** [pyload/pyload#3140]
Fresh install (git clone), fresh init.
When I try to download from uptobox : 
```
26.03.2018 16:04:10 INFO      Download starts: s9an865b99fi
26.03.2018 16:04:10 WARNING   HOSTER XFileSharing[1]: UptoboxCom | Plugin may be unstable
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Grabbing link info...
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Link name: s9an865b99fi
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Link size: N/D
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Link status: demarrage
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Processing url: http://uptobox.com/s9an865b99fi
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Checking for link errors...
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | No errors found
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Grabbing link info...
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Link name: s9an865b99fi
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Link size: N/D
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Link status: demarrage
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Processing as free download...
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | Checking for link errors...
26.03.2018 16:04:10 INFO      HOSTER XFileSharing[1]: UptoboxCom | No errors found
26.03.2018 16:04:10 WARNING   HOSTER XFileSharing[1]: UptoboxCom | Free download failed | TEXTAREA F1 not found
26.03.2018 16:04:10 WARNING   Download failed: s9an865b99fi | TEXTAREA F1 not found
```
This problem seems to be fixed (https://github.com/pyload/pyload/issues/3103 ), but it still failed on my config.

**Comment by GammaC0de** [comment]
Disable XFileSharing plugin.

**Comment by moacmoa** [comment]
It works !
Thanks a lot :+1:

**Comment by GammaC0de** [comment]
👍

**Comment by xilmen** [comment]
Hello, for me if i disable XFileSharing plugin i have this: 

`Traceback (most recent call last):
  File "/opt/pyload/module/ThreadManager.py", line 276, in assignJob
29.08.2018 19:11:20 CRITICAL  'NoneType' object has no attribute 'group'
    job.initPlugin()
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/PyFile.py", line 103, in initPlugin
    self.plugin = self.pluginclass(self)
  File "/opt/pyload/pyload-config/userplugins/internal/Base.py", line 99, in __init__
    self.init()
  File "/opt/pyload/pyload-config/userplugins/hoster/XFileSharing.py", line 39, in init
    self.pyfile.url).group("DOMAIN").lower()
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by STarfield42** [comment]
Hello,
I have the same problem as Xilmen with a fresh install of pyload on a raspbian stretch lite.
With XFileSharing plugin enabled, it does not work
With XFileSharing  plugin disabled, I get the  'NoneType' object has no attribute 'group' too.

@xilmen : have you created a new issue ?

thanks.

**Comment by GammaC0de** [comment]
@STarfield42  Please open a new issue with sample URL, thanks.
