### ISSUE TITLE
downloads from rapidgator are html files

### ISSUE THREAD

**Issue by digimon04** [pyload/pyload#3141]
I tried several times to download from rapidgator but each time Pyload downloads html file from rapidgator. I don't see any prompt form captcha. I have checked rapidgator that they didn't use the new recaptcha. Please help. Thanks.

The logs are:

> 382 | 28.03.2018 16:45:57 | INFO | Added package test3 containing 1 links
> -- | -- | -- | --
> 383 | 28.03.2018 16:45:57 | INFO | Download starts: https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html
> 384 | 28.03.2018 16:45:57 | WARNING | HOSTER BasePlugin[17]: Plugin may be unstable
> 385 | 28.03.2018 16:45:57 | INFO | HOSTER BasePlugin[17]: Grabbing link info...
> 386 | 28.03.2018 16:45:57 | INFO | HOSTER BasePlugin[17]: Link name: 14366_rare-jav.info.rar.html
> 387 | 28.03.2018 16:45:57 | INFO | HOSTER BasePlugin[17]: Link size: N/D
> 388 | 28.03.2018 16:45:57 | INFO | HOSTER BasePlugin[17]: Link status: starting
> 389 | 28.03.2018 16:45:57 | INFO | HOSTER BasePlugin[17]: Processing url: https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html
> 390 | 28.03.2018 16:46:00 | INFO | HOSTER BasePlugin[17]: File saved
> 391 | 28.03.2018 16:46:00 | WARNING | HOSTER BasePlugin[17]: Check result: Html file \| Waiting 1 minute and retry
> 392 | 28.03.2018 16:46:00 | INFO | HOSTER BasePlugin[17]: Waiting 1 minutes...
> 393 | 28.03.2018 16:47:02 | INFO | Download restarted: 14366_rare-jav.info.rar.html \| Html file
>

**Comment by GammaC0de** [comment]
Your download is handled by the default `BasePlugin` plugin bit it should have been handled by the `RapidgatorNet` plugin.

This may indicate of a corrupt installation.
Is this a new installation?

**Comment by digimon04** [comment]
No. I will try to fresh install Pyload after the holidays and tried to download again. I will report then. Thanks.

**Comment by GammaC0de** [comment]
Hi,
Any update?

**Comment by digimon04** [comment]
No, not yet, I might be able to do a clean install in the coming weekend.

**Comment by digimon04** [comment]
Today , I have removed Pyload and re-installed it. Sadly, the result is the same. All I have done right after installation is editing some files to make use of Pillow and replacing updatemanger.py to allow the update of hosters. Below are the logs.


> 03.04.2018 10:41:43 | INFO | Starting pyLoad 0.4.9
> 03.04.2018 10:41:43 | INFO | Using home directory: /tmp/mnt/sda1/entware/var/pyload
> 03.04.2018 10:41:47 | ERROR | Error importing UpdateManager: No module named Hook
> 03.04.2018 10:41:48 | INFO | Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UserAgentSwitcher, XFileSharing
> 03.04.2018 10:41:48 | INFO | Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
> 03.04.2018 10:41:48 | INFO | Downloadtime: True
> 03.04.2018 10:41:48 | INFO | Using SSL ThriftBackend
> 03.04.2018 10:41:48 | INFO | Starting ThriftBackend: 0.0.0.0:7227
> 03.04.2018 10:41:51 | INFO | Free space: 3.08 GiB
> 03.04.2018 10:41:51 | INFO | Starting builtin webserver: 0.0.0.0:8000
> 03.04.2018 10:41:51 | INFO | Activating Accounts...
> 03.04.2018 10:41:51 | INFO | Activating Plugins...
> 03.04.2018 10:41:53 | INFO | ADDON XFileSharing: Auto-discover new hosters
> 03.04.2018 10:41:54 | INFO | ADDON XFileSharing: Auto-discover new crypters
> 03.04.2018 10:41:54 | INFO | pyLoad is up and running
> 03.04.2018 10:41:58 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
> 03.04.2018 17:31:18 | INFO | Added package test containing 1 links
> 03.04.2018 17:31:20 | INFO | Download starts: https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html
> 03.04.2018 17:31:20 | WARNING | HOSTER BasePlugin[1]: Plugin may be unstable
> 03.04.2018 17:31:20 | INFO | HOSTER BasePlugin[1]: Grabbing link info...
> 03.04.2018 17:31:20 | INFO | HOSTER BasePlugin[1]: Link name: 14366_rare-jav.info.rar.html
> 03.04.2018 17:31:20 | INFO | HOSTER BasePlugin[1]: Link size: N/D
> 03.04.2018 17:31:20 | INFO | HOSTER BasePlugin[1]: Link status: starting
> 03.04.2018 17:31:20 | INFO | HOSTER BasePlugin[1]: Processing url: https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html
> 03.04.2018 17:31:23 | INFO | HOSTER BasePlugin[1]: File saved
> 03.04.2018 17:31:23 | WARNING | HOSTER BasePlugin[1]: Check result: Html file \| Waiting 1 minute and retry
> 03.04.2018 17:31:23 | INFO | HOSTER BasePlugin[1]: Waiting 1 minutes...
> 03.04.2018 17:32:25 | INFO | Download restarted: 14366_rare-jav.info.rar.html \| Html file
>

**Comment by GammaC0de** [comment]
How exactly did you installed pyload?

**Comment by digimon04** [comment]
I have tried again today. This time, I didn't do any editing related to Pillow nor replace the updatemanager.py. Pyload still uses baseplugin in download from rapidgator. The logs are:


> 04.04.2018 19:15:14 | INFO | Starting pyLoad 0.4.9
> 04.04.2018 19:15:14 | INFO | Using home directory: /tmp/mnt/sda1/entware/var/pyload
> 04.04.2018 19:15:23 | INFO | Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
> 04.04.2018 19:15:23 | INFO | Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
> 04.04.2018 19:15:23 | INFO | Downloadtime: True
> 04.04.2018 19:15:23 | INFO | Using SSL ThriftBackend
> 04.04.2018 19:15:23 | INFO | Starting ThriftBackend: 0.0.0.0:7227
> 04.04.2018 19:15:29 | INFO | Free space: 3.07 GiB
> 04.04.2018 19:15:29 | INFO | Starting builtin webserver: 0.0.0.0:8000
> 04.04.2018 19:15:29 | INFO | Activating Accounts...
> 04.04.2018 19:15:29 | INFO | Activating Plugins...
> 04.04.2018 19:15:29 | WARNING | ADDON UpdateManager: Unable to connect to the server to retrieve updates
> 04.04.2018 19:15:32 | INFO | ADDON XFileSharing: Auto-discover new hosters
> 04.04.2018 19:15:33 | INFO | ADDON XFileSharing: Auto-discover new crypters
> 04.04.2018 19:15:33 | INFO | pyLoad is up and running
> 04.04.2018 19:15:35 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
> 04.04.2018 19:22:22 | INFO | Added package test containing 1 links
> 04.04.2018 19:22:23 | INFO | Download starts: https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html
> 04.04.2018 19:22:23 | WARNING | HOSTER BasePlugin[1]: Plugin may be unstable
> 04.04.2018 19:22:23 | INFO | HOSTER BasePlugin[1]: Grabbing link info...
> 04.04.2018 19:22:23 | INFO | HOSTER BasePlugin[1]: Link name: 14366_rare-jav.info.rar.html
> 04.04.2018 19:22:23 | INFO | HOSTER BasePlugin[1]: Link size: N/D
> 04.04.2018 19:22:23 | INFO | HOSTER BasePlugin[1]: Link status: starting
> 04.04.2018 19:22:23 | INFO | HOSTER BasePlugin[1]: Processing url: https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html
> 04.04.2018 19:22:28 | INFO | HOSTER BasePlugin[1]: File saved
> 04.04.2018 19:22:28 | WARNING | HOSTER BasePlugin[1]: Check result: Html file \| Waiting 1 minute and retry
> 04.04.2018 19:22:28 | INFO | HOSTER BasePlugin[1]: Waiting 1 minutes...

The pyload is installed to the Entware-enabled Asus router. I first remove the Pyload by:

`opkg remove pyload`

Restart the router and then install again by

`opkg install pyload`

`cd /opt/share/pyload`

`python pyLoadCore.py -s`

**Comment by GammaC0de** [comment]
start pyload with `python pyLoadCore.py -d`, retry the download and post the log (all of it please, from the start of pyload) again

**Comment by digimon04** [comment]
Here is the log:

> admin@RT-AC68U-6258:/tmp/mnt/sda1/entware/share/pyload# python pyLoadCore.py -d
> 06.04.2018 09:41:44 INFO      Starting pyLoad 0.4.9
> 06.04.2018 09:41:44 INFO      Using home directory: /tmp/mnt/sda1/entware/var/pyload
> 06.04.2018 09:41:44 DEBUG     Remote activated: True
> 06.04.2018 09:41:48 DEBUG     created index of plugins
> 06.04.2018 09:41:48 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
> 06.04.2018 09:41:48 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
> 06.04.2018 09:41:48 INFO      Downloadtime: True
> 06.04.2018 09:41:48 INFO      Using SSL ThriftBackend
> 06.04.2018 09:41:48 INFO      Starting ThriftBackend: 0.0.0.0:7227
> 06.04.2018 09:41:52 INFO      Free space: 3.06 GiB
> 06.04.2018 09:41:52 INFO      Starting builtin webserver: 0.0.0.0:8000
> 06.04.2018 09:41:52 INFO      Activating Accounts...
> 06.04.2018 09:41:52 INFO      Activating Plugins...
> 06.04.2018 09:41:52 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
> 06.04.2018 09:41:52 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_start`
> 06.04.2018 09:41:52 WARNING   ADDON UpdateManager: Unable to connect to the server to retrieve updates
> 06.04.2018 09:41:53 DEBUG     ADDON ExtractArchive: Found UnZip 2.7.14 | Found UnTar 2.7.14
> 06.04.2018 09:41:55 INFO      ADDON XFileSharing: Auto-discover new hosters
> 06.04.2018 09:41:55 DEBUG     ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|cramit\.in|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uploadrocket\.net|uptobox\.com|vidplay\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
> 06.04.2018 09:41:55 INFO      ADDON XFileSharing: Auto-discover new crypters
> 06.04.2018 09:41:55 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
> 06.04.2018 09:41:55 INFO      pyLoad is up and running
> 06.04.2018 09:41:57 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
> 06.04.2018 09:42:27 DEBUG     ADDON ExternalScripts: No script found under folder `package_deleted`
> 06.04.2018 09:43:24 INFO      Added package test2 containing 1 links
> 06.04.2018 09:43:26 INFO      Download starts: https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html
> 06.04.2018 09:43:26 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
> 06.04.2018 09:43:26 DEBUG     HOSTER BasePlugin[6]: Plugin version: 0.51
> 06.04.2018 09:43:26 DEBUG     HOSTER BasePlugin[6]: Plugin status: testing
> 06.04.2018 09:43:26 WARNING   HOSTER BasePlugin[6]: Plugin may be unstable
> 06.04.2018 09:43:26 DEBUG     HOSTER BasePlugin[6]: Config option `use_premium` not found, use default `True`
> 06.04.2018 09:43:26 INFO      HOSTER BasePlugin[6]: Grabbing link info...
> 06.04.2018 09:43:26 DEBUG     HOSTER BasePlugin[6]: Link info: {'status': 7, 'hash': {}, 'name': '14366_rare-jav.info.rar.html', 'url': u'https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html', 'pattern': {}, 'size': 0}
> 06.04.2018 09:43:26 DEBUG     HOSTER BasePlugin[6]: Previous link info: {}
> 06.04.2018 09:43:26 INFO      HOSTER BasePlugin[6]: Link name: 14366_rare-jav.info.rar.html
> 06.04.2018 09:43:26 INFO      HOSTER BasePlugin[6]: Link size: N/D
> 06.04.2018 09:43:26 INFO      HOSTER BasePlugin[6]: Link status: starting
> 06.04.2018 09:43:26 INFO      HOSTER BasePlugin[6]: Processing url: https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html
> 06.04.2018 09:43:26 DEBUG     HOSTER BasePlugin[6]: DOWNLOAD URL https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
> 06.04.2018 09:43:28 INFO      HOSTER BasePlugin[6]: File saved
> 06.04.2018 09:43:28 WARNING   HOSTER BasePlugin[6]: Check result: Html file | Waiting 1 minute and retry
> 06.04.2018 09:43:28 DEBUG     HOSTER BasePlugin[6]: WAIT set to timestamp 1523007869.988709 | Previous waitUntil: 0.000000
> 06.04.2018 09:43:28 DEBUG     HOSTER BasePlugin[6]: RECONNECT not required | Previous wantReconnect: False
> 06.04.2018 09:43:28 INFO      HOSTER BasePlugin[6]: Waiting 1 minutes...
> 06.04.2018 09:44:31 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
> 06.04.2018 09:44:31 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
> 06.04.2018 09:44:31 INFO      Download restarted: 14366_rare-jav.info.rar.html | Html file
> 06.04.2018 09:44:32 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
> 06.04.2018 09:44:32 DEBUG     All downloads processed
> 06.04.2018 09:44:32 INFO      Download starts: 14366_rare-jav.info.rar.html
> 06.04.2018 09:44:32 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
> 06.04.2018 09:44:32 DEBUG     HOSTER BasePlugin[6]: Plugin version: 0.51
> 06.04.2018 09:44:32 DEBUG     HOSTER BasePlugin[6]: Plugin status: testing
> 06.04.2018 09:44:32 WARNING   HOSTER BasePlugin[6]: Plugin may be unstable
> 06.04.2018 09:44:32 DEBUG     HOSTER BasePlugin[6]: Config option `use_premium` not found, use default `True`
> 06.04.2018 09:44:32 INFO      HOSTER BasePlugin[6]: Grabbing link info...
> 06.04.2018 09:44:32 DEBUG     HOSTER BasePlugin[6]: Link info: {'status': 7, 'hash': {}, 'name': '14366_rare-jav.info.rar.html', 'url': u'https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html', 'pattern': {}, 'size': 0}
> 06.04.2018 09:44:32 DEBUG     HOSTER BasePlugin[6]: Previous link info: {'status': 7, 'hash': {}, 'name': '14366_rare-jav.info.rar.html', 'url': u'https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html', 'pattern': {}, 'size': 0}
> 06.04.2018 09:44:32 INFO      HOSTER BasePlugin[6]: Link name: 14366_rare-jav.info.rar.html
> 06.04.2018 09:44:32 INFO      HOSTER BasePlugin[6]: Link size: N/D
> 06.04.2018 09:44:32 INFO      HOSTER BasePlugin[6]: Link status: starting
> 06.04.2018 09:44:32 INFO      HOSTER BasePlugin[6]: Processing url: https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html
> 06.04.2018 09:44:32 DEBUG     HOSTER BasePlugin[6]: DOWNLOAD URL https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
> 06.04.2018 09:44:34 INFO      HOSTER BasePlugin[6]: File saved
> 06.04.2018 09:44:34 WARNING   HOSTER BasePlugin[6]: Check result: Html file | Waiting 1 minute and retry
> 06.04.2018 09:44:34 DEBUG     HOSTER BasePlugin[6]: WAIT set to timestamp 1523007935.693171 | Previous waitUntil: 1523007869.988709
> 06.04.2018 09:44:34 DEBUG     HOSTER BasePlugin[6]: RECONNECT not required | Previous wantReconnect: False
> 06.04.2018 09:44:34 INFO      HOSTER BasePlugin[6]: Waiting 1 minutes...
> 06.04.2018 09:45:36 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
> 06.04.2018 09:45:36 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
> 06.04.2018 09:45:36 INFO      Download restarted: 14366_rare-jav.info.rar.html (2) | Html file
> 06.04.2018 09:45:38 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
> 06.04.2018 09:45:38 DEBUG     All downloads processed
> 06.04.2018 09:45:38 INFO      Download starts: 14366_rare-jav.info.rar.html (2)
> 06.04.2018 09:45:38 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
> 06.04.2018 09:45:38 DEBUG     HOSTER BasePlugin[6]: Plugin version: 0.51
> 06.04.2018 09:45:38 DEBUG     HOSTER BasePlugin[6]: Plugin status: testing
> 06.04.2018 09:45:38 WARNING   HOSTER BasePlugin[6]: Plugin may be unstable
> 06.04.2018 09:45:38 DEBUG     HOSTER BasePlugin[6]: Config option `use_premium` not found, use default `True`
> 06.04.2018 09:45:38 INFO      HOSTER BasePlugin[6]: Grabbing link info...
> 06.04.2018 09:45:38 DEBUG     HOSTER BasePlugin[6]: Link info: {'status': 7, 'hash': {}, 'name': '14366_rare-jav.info.rar.html', 'url': u'https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html', 'pattern': {}, 'size': 0}
> 06.04.2018 09:45:38 DEBUG     HOSTER BasePlugin[6]: Previous link info: {'status': 7, 'hash': {}, 'name': '14366_rare-jav.info.rar.html', 'url': u'https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html', 'pattern': {}, 'size': 0}
> 06.04.2018 09:45:38 INFO      HOSTER BasePlugin[6]: Link name: 14366_rare-jav.info.rar.html
> 06.04.2018 09:45:38 INFO      HOSTER BasePlugin[6]: Link size: N/D
> 06.04.2018 09:45:38 INFO      HOSTER BasePlugin[6]: Link status: starting
> 06.04.2018 09:45:38 INFO      HOSTER BasePlugin[6]: Processing url: https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html
> 06.04.2018 09:45:38 DEBUG     HOSTER BasePlugin[6]: DOWNLOAD URL https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
> 06.04.2018 09:45:40 INFO      HOSTER BasePlugin[6]: File saved
> 06.04.2018 09:45:40 WARNING   HOSTER BasePlugin[6]: Check result: Html file | Waiting 1 minute and retry
> 06.04.2018 09:45:40 DEBUG     HOSTER BasePlugin[6]: WAIT set to timestamp 1523008001.410135 | Previous waitUntil: 1523007935.693171
> 06.04.2018 09:45:40 DEBUG     HOSTER BasePlugin[6]: RECONNECT not required | Previous wantReconnect: False
> 06.04.2018 09:45:40 INFO      HOSTER BasePlugin[6]: Waiting 1 minutes...
> 06.04.2018 09:46:42 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
> 06.04.2018 09:46:42 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
> 06.04.2018 09:46:42 INFO      Download restarted: 14366_rare-jav.info.rar.html (2) (2) | Html file
> 06.04.2018 09:46:43 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
> 06.04.2018 09:46:43 DEBUG     All downloads processed
> 06.04.2018 09:46:43 INFO      Download starts: 14366_rare-jav.info.rar.html (2) (2)
> 06.04.2018 09:46:43 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
> 06.04.2018 09:46:43 DEBUG     HOSTER BasePlugin[6]: Plugin version: 0.51
> 06.04.2018 09:46:43 DEBUG     HOSTER BasePlugin[6]: Plugin status: testing
> 06.04.2018 09:46:43 WARNING   HOSTER BasePlugin[6]: Plugin may be unstable
> 06.04.2018 09:46:43 DEBUG     HOSTER BasePlugin[6]: Config option `use_premium` not found, use default `True`
> 06.04.2018 09:46:43 INFO      HOSTER BasePlugin[6]: Grabbing link info...
> 06.04.2018 09:46:43 DEBUG     HOSTER BasePlugin[6]: Link info: {'status': 7, 'hash': {}, 'name': '14366_rare-jav.info.rar.html', 'url': u'https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html', 'pattern': {}, 'size': 0}
> 06.04.2018 09:46:43 DEBUG     HOSTER BasePlugin[6]: Previous link info: {'status': 7, 'hash': {}, 'name': '14366_rare-jav.info.rar.html', 'url': u'https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html', 'pattern': {}, 'size': 0}
> 06.04.2018 09:46:43 INFO      HOSTER BasePlugin[6]: Link name: 14366_rare-jav.info.rar.html
> 06.04.2018 09:46:43 INFO      HOSTER BasePlugin[6]: Link size: N/D
> 06.04.2018 09:46:43 INFO      HOSTER BasePlugin[6]: Link status: starting
> 06.04.2018 09:46:43 INFO      HOSTER BasePlugin[6]: Processing url: https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html
> 06.04.2018 09:46:43 DEBUG     HOSTER BasePlugin[6]: DOWNLOAD URL https://rapidgator.net/file/02ae0b239b8dda7f86c79664516faa8a/14366_rare-jav.info.rar.html | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=False
> 06.04.2018 09:46:45 INFO      HOSTER BasePlugin[6]: File saved
> 06.04.2018 09:46:45 WARNING   HOSTER BasePlugin[6]: Check result: Html file | Waiting 1 minute and retry
> 06.04.2018 09:46:45 DEBUG     HOSTER BasePlugin[6]: Config option `fallback` not found, use default `True`
> 06.04.2018 09:46:45 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
> 06.04.2018 09:46:45 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
> 06.04.2018 09:46:45 WARNING   Download failed: 14366_rare-jav.info.rar.html (2) (2) | Html file
> 06.04.2018 09:46:45 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: 14366_rare-jav.info.rar.html (2) (2) (pid:4)
> 06.04.2018 09:46:45 INFO      ADDON UnSkipOnFail: No duplicates found
> 06.04.2018 09:46:45 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
> 06.04.2018 09:46:45 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
> 06.04.2018 09:46:45 DEBUG     All downloads processed

**Comment by GammaC0de** [comment]
```
06.04.2018 09:41:52 DEBUG ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
```
Your plugins are out of date, 
please read https://github.com/pyload/pyload/issues/2994.

**Comment by digimon04** [comment]
In the latest attempt as mentioned above, I didn't do any editing in relation to updatemanager.py so the plugins are outdated. I have read #2994 but I didn't find UpdateManager.py in `var/pyload/userplugins/hooks`. There is only one file named `__init__.py` consisted of 0kb. Instead, I have followed #2995 and #3129, replacing `share/pyload/module/plugins/hooks/UpdateManager.py` with https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/830cb0161b416a5328e32516067608cd2cfdd031/UpdateManager.py

But this produces the same result as my first clean install's above.

**Comment by GammaC0de** [comment]
- Go to `http://<IP_OF_PYLOAD>/info` and see the valuse of `Installation Folder` and `Config Folder`
- on a SSH prompt do:
`cd <Config Folder>`
`rm -rf userplugins`
`cd <Installation Folder>/module/plugins/hooks`
`cat UpdateManager.py  | grep __version__`
`rm -f UpdateManager.py`
`wget --no-check-certificate "https://gist.github.com/GammaC0de/a77279b6588c11aed9c9/raw/830cb0161b416a5328e32516067608cd2cfdd031/UpdateManager.py"`

**Comment by digimon04** [comment]
Thanks. I  will try that when I am home.

**Comment by GammaC0de** [comment]
- cd  /tmp/mnt/sda1/entware/var/pyload
- rm -rf userplugins
- cd /tmp/mnt/sda1/entware/share/pyload/
- download https://github.com/pyload/pyload/archive/stable.zip
- extract and overwrite all the files in `stable.zip/pyload-stable` to `/tmp/mnt/sda1/entware/share/pyload/`

**Comment by digimon04** [comment]
Work like a charm. Thank you very much.

**Comment by GammaC0de** [comment]
👍
