### ISSUE TITLE
Extract Archive failed error code 2

### ISSUE THREAD

**Issue by GottHeit** [pyload/pyload#3142]
hey there,

i am running pyload with zyxel nas540 and extract archive has not been working for a while now (i guess the package they provide - seems to been 03/2017 - has some plugins not working in that version, as a fresh install does not fix it). 

but recently i have updated the updatemanager.py manually and now all plugins are up to date, but extract archive still does not extract. i always get an error code 2 (before updating behaviour was different when switching trash/delete, with one setting files were deleted without extracting, now just nothing happens).

tried to change download/extrac-location/folder, but no change. tried to find some older posts here, but did not find any fix...
copied new files from the stable over installation and restarted, did not change anything... 

only difference now after updating is that every download is sorted into a subfolder (cannot change this by setting) as name resolution of filecrypt.cc dlc did not work and now i have to go to every single folder to extract manually, before i could extract em in one bunch... that was somehow easier ^^ 

would appreciate any help! thanks!

> 

  | 30.03.2018 11:46:44 | INFO | ADDON ExtractArchive:  xxx.part1.rar \| Extract to:  /i-data/a578d198/nfs/filme/filecrypt.cc/
-- | -- | -- | --
853 | 30.03.2018 11:46:44 | ERROR | ADDON ExtractArchive: xxx.part1.rar \| Archive error \| Process return code: 2
854 | 30.03.2018 11:46:44 | ERROR | ADDON ExtractArchive: xxx.part1.rar \| Extract failed

**Comment by GammaC0de** [comment]
Please enable debug mode, retry and post the debug log here.

**Comment by GottHeit** [comment]
30.03.2018 15:33:21 DEBUG     ADDON ExternalScripts: No script found under folder `download_finished`
30.03.2018 15:33:24 INFO      HOSTER ShareonlineBiz[28]: File saved
30.03.2018 15:33:24 INFO      HOSTER ShareonlineBiz[28]: Checking download...
30.03.2018 15:33:24 INFO      HOSTER ShareonlineBiz[28]: File is OK
30.03.2018 15:33:24 INFO      HOSTER ShareonlineBiz[28]: Checking file (with built-in rules)...
30.03.2018 15:33:24 INFO      HOSTER ShareonlineBiz[28]: Checking file (with custom rules)...
30.03.2018 15:33:25 INFO      HOSTER ShareonlineBiz[28]: No errors found
30.03.2018 15:33:25 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
30.03.2018 15:33:25 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
30.03.2018 15:33:25 INFO      Download finished: xxx.part2.rar
30.03.2018 15:33:25 DEBUG     ADDON ExternalScripts: No script found under folder `download_finished`
30.03.2018 15:33:25 INFO      Package finished: xxx - filecrypt.cc
30.03.2018 15:33:25 DEBUG     ADDON ExternalScripts: No script found under folder `package_finished`
30.03.2018 15:33:25 DEBUG     ADDON ExtractArchive: Use for extensions: .7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
30.03.2018 15:33:25 INFO      ADDON ExtractArchive: Check package: xxx - filecrypt.cc
30.03.2018 15:33:25 DEBUG     ADDON ExtractArchive: Targets for SevenZip: [(27, '/i-data/a578d198/nfs/filme/filecrypt.cc/xxx.part1.rar', '/i-data/a578d198/nfs/filme/filecrypt.cc/')]
30.03.2018 15:33:25 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
30.03.2018 15:33:25 INFO      ADDON ExtractArchive: xxx.part1.rar | Extract to: /i-data/a578d198/nfs/filme/filecrypt.cc/
30.03.2018 15:33:25 DEBUG     All downloads processed
30.03.2018 15:33:25 DEBUG     ADDON ExtractArchive: Password: None provided
30.03.2018 15:33:25 DEBUG     EXTRACTOR SevenZip: EXECUTE 7z l -y -xr!*.nfo -xr!*.DS_Store -xr!index.dat -xr!thumb.db -p- -slt /i-data/a578d198/nfs/filme/filecrypt.cc/xxx.part1.rar
30.03.2018 15:33:25 DEBUG     ADDON ExtractArchive: Extracting using password: None
30.03.2018 15:33:25 DEBUG     EXTRACTOR SevenZip: EXECUTE 7z e -y -xr!*.nfo -xr!*.DS_Store -xr!index.dat -xr!thumb.db -p- -o/i-data/a578d198/nfs/filme/filecrypt.cc/ /i-data/a578d198/nfs/filme/filecrypt.cc/xxx.part1.rar
30.03.2018 15:33:25 ERROR     ADDON ExtractArchive: xxx.part1.rar | Archive error | Process return code: 2
30.03.2018 15:33:25 DEBUG     ADDON ExternalScripts: No script found under folder `archive_extract_failed`
30.03.2018 15:33:25 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_finished`
30.03.2018 15:33:25 DEBUG     All downloads finished
30.03.2018 15:33:25 ERROR     ADDON ExtractArchive: xxx.part1.rar | Extract failed
30.03.2018 15:33:25 DEBUG     ADDON ExternalScripts: No script found under folder `package_extract_failed`

**Comment by GottHeit** [comment]
3 parts, no password, extracting with 7zip manually works without any problems...

**Comment by GammaC0de** [comment]
The error comes from 7zip itself.
Execute the command ` 7z e -y -xr!.nfo -xr!.DS_Store -xr!index.dat -xr!thumb.db -p- -o/i-data/a578d198/nfs/filme/filecrypt.cc/ /i-data/a578d198/nfs/filme/filecrypt.cc/xxx.part1.rar` and see if you can spot something.

**Comment by GottHeit** [comment]
![2018-03-30 1](https://user-images.githubusercontent.com/17480327/38140485-34539356-3434-11e8-9e94-5fc2f645c982.png)

**Comment by GammaC0de** [comment]
I would try to change the download directory to a local directory and see if makes any difference

**Comment by GottHeit** [comment]
the download location is one of the inside hard disks of the nas... did serveral installations in the morning with delivered built als well with updated plugins... have two storages places, tried both of them, tried the original location in the admin share. no change. only thing which worked out different is that files got deleted with the build in-version when setting is trash or delete (one of them, not shure which one), but also files did not get extracted and i received an error code 2

**Comment by GammaC0de** [comment]
Can you try:
`7z e -y -xr!.nfo -xr!.DS_Store -xr!index.dat -xr!thumb.db -p- -o'/i-data/a578d198/nfs/filme/filecrypt.cc/' '/i-data/a578d198/nfs/filme/filecrypt.cc/xxx.part1.rar'`?

**Comment by GottHeit** [comment]
i tried, did not make any change, still "not found"

**Comment by GottHeit** [comment]
/i-data/fdfd98ea/.PKG/pyLoad/bin$ 7z e -y -xr!*.nfo -xr!*.DS_Store -xr!index.dat -xr!thumb.db -p- -o /i-data/sysvol/nfs/Video/ /i-data/sysvol/nfs/Video/xxx.part1.rar
-sh: 7z: not found
/i-data/fdfd98ea/.PKG/pyLoad/bin$ 7z e -y -xr!*.nfo -xr!*.DS_Store -xr!index.dat -xr!thumb.db -p- -o /i-data/fdfd98ea/nfs/Video/ /i-data/fdfd98ea/nfs/Video/xxx.part1.rar
-sh: 7z: not found
/i-data/fdfd98ea/.PKG/pyLoad/bin$ 7z e -y -xr!*.nfo -xr!*.DS_Store -xr!index.dat -xr!thumb.db -p- -o /i-data/fdfd98ea/admin/download/pyload-download/ /i-data/fdfd98ea/admin/download/pyload-download/xxx.part1.rar
-sh: 7z: not found
/i-data/fdfd98ea/.PKG/pyLoad/bin$ 7z e -y -xr!.nfo -xr!.DS_Store -xr!index.dat -xr!thumb.db -p- -o'/i-data/a578d198/nfs/filme/filecrypt.cc/' '/i-data/a578d198/nfs/filme/filecrypt.cc/xxx.part1.rar'
-sh: 7z: not found

**Comment by Mister-XY** [comment]
Hello, a info for you. You can download unrar for your Nas.
At first, you must install MetaRepository  http://www.zyxelforum.de/viewtopic.php?f=304&t=6863
if you have done this, you can install Randomtools http://www.zyxelforum.de/viewtopic.php?f=302&t=7502.
After you have install the random tools, you must restart pyload again and you extractor extract with unrar instead the old 7zip (i hope)

**Comment by GottHeit** [comment]
Thanks a lot, did not know about MetaRepository and Randomtools! (will give debian or omv a try by time)

Unrar "works" as it extracts the packages, but cannot delete them, as it throws out an error:


31.03.2018 11:42:54 | DEBUG | EXTRACTOR UnRar: EXECUTE unrar l -o- -or -x*.nfo -x*.DS_Store  -xindex.dat -xthumb.db -y -p- -v  /i-data/a578d198/nfs/filme/filecrypt.cc/xxx/xxx.part1.rar
-- | -- | --
455 | 31.03.2018 11:42:54 | DEBUG | ADDON ExtractArchive: Extracting using password: None
456 | 31.03.2018 11:42:54 | DEBUG | EXTRACTOR UnRar: EXECUTE unrar x -o- -or -x*.nfo -x*.DS_Store  -xindex.dat -xthumb.db -y -p-  /i-data/a578d198/nfs/filme/filecrypt.cc/xxx/xxx.part1.rar  /i-data/a578d198/nfs/filme/
457 | 31.03.2018 11:43:05 | DEBUG | EXTRACTOR UnRar: Config option `ignore_warnings` not found, use default `False`
**458 | 31.03.2018 11:43:05 | ERROR | ADDON ExtractArchive:  xxx.part1.rar \| Archive error \|  /i-data/fdfd98ea/.PKG/RandomTools/bin/unrar-5.4.5.bin:  /lib/libstdc++.so.6: no version information available (required by  /i-data/fdfd98ea/.PKG/RandomTools/bin/unrar-5.4.5.bin)
459 | ? | ? | /i-data/fdfd98ea/.PKG/RandomTools/bin/unrar-5.4.5.bin:  /lib/libstdc++.so.6: no version information available (required by  /i-data/fdfd98ea/.PKG/RandomTools/bin/unrar-5.4.5.bin)
460 | ? | ? | /i-data/fdfd98ea/.PKG/RandomTools/bin/unrar-5.4.5.bin:  /lib/libstdc++.so.6: no version information available (required by  /i-data/fdfd98ea/.PKG/RandomTools/bin/unrar-5.4.5.bin)**
461 | 31.03.2018 11:43:05 | DEBUG | ADDON ExternalScripts: No script found under folder `archive_extract_failed`
462 | 31.03.2018 11:43:05 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_finished`
463 | 31.03.2018 11:43:05 | DEBUG | All downloads finished
464 | 31.03.2018 11:43:05 | ERROR | ADDON ExtractArchive: xxx.part1.rar \| Extract failed
465 | 31.03.2018 11:43:05 | DEBUG | ADDON ExtractArchive: Targets for SevenZip: [(4,  '/i-data/a578d198/nfs/filme/filecrypt.cc/xxx/xxx.part1.rar',  '/i-data/a578d198/nfs/filme/')]
466 | 31.03.2018 11:43:05 | INFO | ADDON ExtractArchive: xxx.part1.rar \| Extract to: /i-data/a578d198/nfs/filme/
467 | 31.03.2018 11:43:05 | DEBUG | ADDON ExtractArchive: Password: None provided
468 | 31.03.2018 11:43:05 | DEBUG | EXTRACTOR SevenZip: EXECUTE 7z l -xr!*.nfo -xr!*.DS_Store  -xr!index.dat -xr!thumb.db -p- -slt  /i-data/a578d198/nfs/filme/filecrypt.cc/xxx/xxx.part1.rar
469 | 31.03.2018 11:43:05 | DEBUG | ADDON ExtractArchive: Extracting using password: None
470 | 31.03.2018 11:43:05 | DEBUG | EXTRACTOR SevenZip: EXECUTE 7z x -xr!*.nfo -xr!*.DS_Store  -xr!index.dat -xr!thumb.db -p- -o/i-data/a578d198/nfs/filme/  /i-data/a578d198/nfs/filme/filecrypt.cc/xxx/xxx.part1.rar
471 | 31.03.2018 11:43:05 | ERROR | ADDON ExtractArchive: xxx.part1.rar \| Archive error \| Process return code: 2
472 | 31.03.2018 11:43:05 | DEBUG | ADDON ExternalScripts: No script found under folder `archive_extract_failed`
473 | 31.03.2018 11:43:05 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_finished`
474 | 31.03.2018 11:43:05 | DEBUG | All downloads finished
475 | 31.03.2018 11:43:05 | ERROR | ADDON ExtractArchive: xxx.part1.rar \| Extract failed
476 | 31.03.2018 11:43:05 | DEBUG | ADDON ExternalScripts: No script found under folder `package_extract_failed`

**Comment by Mister-XY** [comment]
Ah ok, this is an old error. Now we have two solution. We make a small wrapper or you install also entware-ng via you app list and uninstall random tools. if you have install entware-ng, you must login via ssh and install unrar. i think it was opkg update and opkg install unrar. Via entware-ng you have also the "newest" unrar version. You can also install othe package looks like here 
http://pkg.entware.net/binaries/armv7/Packages.html

**Comment by GottHeit** [comment]
Ah okay, cool!
I just tried entware-ng, but seems not to work on my nas... opkg command does not work, i get an "not found" ^^ tried to install it another time, but still "not found" 
So how about the small wrapper :)

**Comment by Mister-XY** [comment]
have you install entware-ng at first and then open the ssh.

**Comment by GottHeit** [comment]
figured it out... even if i am in the correct folder and i am trying to start opkg it doesn´t work, but if i am starting it with full path in command it worked... like this:

> /i-data/fdfd98ea/.PKG/Entware-ng/opt/bin/opkg list-installed

**Comment by Mister-XY** [comment]
ore did you have also an folder called /opt ?

**Comment by GottHeit** [comment]
yes, there is one in the root directory, pointing to /i-data/fdfd98ea/.PKG/Entware-ng/opt/

also i can start 7z when using full path for command: /i-data/fdfd98ea/.PKG/pyLoad/bin/7z

**Comment by Mister-XY** [comment]
what happen if you type unrar?
i hope you have uninstall random tools

**Comment by GottHeit** [comment]
great, that works! wow!
files got extracted and rars got deleted (only send2trash does not work, but as long as extraction works i can live with that, i guess...)
so, wasthat the problem... that 7z was not been able to be found? 
and do you have any idea why my system is acting like that? (as i was able to run the random tools unrar just by "unrar" command...)
and thanks a lot for your help and patience!

**Comment by Mister-XY** [comment]
I think, the problem is that 7z can't extract rar archive. is need the 7zip rar support. With ubuntu or debian, i must also install p7zip-rar to extract rar archives. I think that's also need here.
If you have time and fun, you can make a Entware-ng stick. In my active zyxel time, i have also use the entware -ng stick and have installed pyload via entware-ng (opkg). I don't have use any zyxel package, because that was to old. 
http://www.zyxelforum.de/viewtopic.php?f=311&t=10148
here to install pyload
https://github.com/Entware/Entware-ng/wiki/Using-Pyload

**Comment by GottHeit** [comment]
Ah, i understand. Thanks for explaining! 

And great note, the old packages have always upset me, too... will definately give it a try when i have some spare time :)

**Comment by GammaC0de** [comment]
@Mister-XY Thanks for your help :+1: 

@GottHeit Cant we close this issue?

**Comment by GottHeit** [comment]
@Mister-XY "and don't use send2trash, take delete files instate of send2trash" okay, i will do so, thanks again! 
@GammaC0de yes, please close it
