### ISSUE TITLE
[OneFichier] Number of parallel downloads

### ISSUE THREAD

**Issue by youlJunior** [pyload/pyload#3144]
When I queue multiple OneFichier links, pyload only download 5 links in parallel.

"Max Parallel Downloads" is set to 50 in config, and with UpToBox links I can download more than 5 links in parallel, so I don't see where this limit is set...

I'm premium on OneFichier and UpToBox.

**Comment by youlJunior** [comment]
There were two parameters in accounts.conf for OneFichier account: 
@limitdl 5
@limitDL 5
But this was not seen in WebUI in Accounts tab...

So I removed and added again my OneFichier account.
Now there is only "@limitdl 0" in accounts.conf, and I can download more than 5 files in parrallel !

@GammaC0de @vuolter, can you check why limitdl account paramter is not shown in WebUI ?

**Comment by GammaC0de** [comment]
![capture](https://user-images.githubusercontent.com/11036551/38175664-d833245e-35e8-11e8-8a6c-2a9b6aefe1ae.PNG)

**Comment by youlJunior** [comment]
@GammaC0de, whatever is set in accounts.conf, this edit box stay empty

**Comment by GammaC0de** [comment]
OK, I will check.

**Comment by youlJunior** [comment]
Thank you @GammaC0de, so fast as usual ;)

**Comment by GammaC0de** [comment]
Updated..
