### ISSUE TITLE
Access pyload using nginx reverse proxy - 502 Bad Gateway

### ISSUE THREAD

**Issue by JoergBerlin** [pyload/pyload#3147]
Hi,

according to issue ["nginx reverse proxy   #3073"](https://github.com/pyload/pyload/issues/3073) I tried to access pyload using nginx reverse proxy https://mydomain/pyload/

So I copied the files to my raspberry (/usr/share/pyload/) and tried to gain access via nginx reverse proxy with this configuration:

nginx gateway file (/etc/nginx/conf.d/mydomain.conf):

```
        location ^~ /pyload {
                proxy_pass http://127.0.0.1:84;
                proxy_redirect off;
        }
```

nginx virtual host config-file (/etc/nginx/conf.d/mydomain_pyload.conf:

```
server {
        listen 127.0.0.1:84;
        server_name 127.0.0.1;

location  /pyload {
  proxy_pass         http://127.0.0.1:1234;
  proxy_redirect     off;
  proxy_set_header   Host $host;
  access_log /var/log/nginx/pyload.access.log
  error_log /var/log/nginx/pyload.error.log
}
}
```

I get the error 502 Bad Gateway.

In the error_log (/var/log/nginx/pyload.error.log) I find this entry:

2018/03/30 16:12:14 [error] 1373#1373: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET /pyload HTTP/1.0", upstream: "http://127.0.0.1:8000/pyload", host: "127.0.0.1:84"

If I try to open pyload manually (w3m on the raspberry or Chrome from another client in the lan) by using the url http://192.168.178.225:1234 (it is the fix ip of the raspberry in the lan), It works.

Does anybody know how to solve the problem?

Thanks

Joerg
** Beginner **

**Comment by GammaC0de** [comment]
I don't have nginx so I'm not sure that this actually works but try:
```
    location /pyload {
        proxy_set_header Host $host;
        proxy_pass https://localhost:8000/pyload;
        proxy_redirect default;
    }
```

**Comment by JoergBerlin** [comment]
I tried but it doesn´t work :-(

**Comment by GammaC0de** [comment]
Have you set the pathprefix settings in pyload's configuration?

**Comment by JoergBerlin** [comment]
I did:
sudo nano /usr/share/pyload/module/config/default.conf

section "webinterface - "Webinterface":

str prefix: "Path Prefix" = /pyload

Same error:  502 Bad Gateway.

**Comment by GammaC0de** [comment]
Maybe @OzzieIsaacs can help you because I know he have successfully using nginx..

**Comment by GammaC0de** [comment]
@OzzieIsaacs Thanks anyway.

**Comment by youlJunior** [comment]
FYI, I use nginx as reverse proxy, and all is working.
This is my config : 

> location /pyload {
                auth_basic              'pyLoad';
                proxy_pass              http://127.0.0.1:8000/pyload;
                proxy_redirect          default;
        }
And I have "Path Prefix" set to "/pyload".

Before the commit on 27th January (#3077), I had to make some ugly config in Nginx, but now it's working smooth.

**Comment by JoergBerlin** [comment]
It is dryving my crazy...

nano /etc/nginx/conf.d/myserver.eu.conf 

```
        location /pyload {
                auth_basic 'pyLoad';
                proxy_pass http://127.0.0.1:1234/pyload;
                proxy_redirect default;
                access_log /var/log/nginx/pyload.access.log;
                error_log /var/log/nginx/pyload.error.log;
        }
```

/usr/share/pyload/module/config/default.conf

```
webinterface - "Webinterface":
        bool activated : "Activated" = True
        builtin;threaded;fastcgi;lightweight server : "Server" = threaded
        bool https : "Use HTTPS" = False
        ip host : "IP" = 127.0.0.1
        int port : "Port" = 1234
        str template : "Template" = pyplex
        str prefix : "Path Prefix" = /pyload
```

Tests directly on the raspberry:

w3m http://127.0.0.1/pyload --> 502 Bad Gateway
w3m http://192.168.178.230/pyload --> 502 Bad Gateway
w3m http://127.0.0.1:1234 --> w3m: Can't load http://127.0.0.1:1234.
w3m http://192.168.178.230:1234 --> works

From another client in the local network with google chrome:

https://myserver.eu/pyload --> 502 Bad Gateway

This is the error code from /var/log/nginx/pyload.error.log 

2018/04/08 13:22:48 [error] 28038#28038: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 37.120.23.174, server: myserver.eu, request: "GET /pyload HTTP/2.0", upstream: "http://127.0.0.1:1234/pyload", host: "jmr.ddnss.eu"


HELP! :-(

**Comment by youlJunior** [comment]
@JoergBerlin 
Make sure you have latest pyload files.
Because without nginx you should access to pyload with "http://192.168.178.230:1234/pyload", not "http://192.168.178.230:1234"

BTW, the error "connection refused" in your nginx logs is not related to path.
It means that nginx can't connect to 127.0.0.1 on port 1234.
Can you make sure that pyload really listen on 127.0.0.1 by using netstat command ?

**Comment by JoergBerlin** [comment]
w3m http://192.168.178.230:1234/pyload

```
Error 404: Not Found
Sorry, the requested URL 'http://192.168.178.230:1234/pyload' caused an error:
Not found: 'pyload'
```

netstat -taupen | grep 1234

Proto Recv-Q Send-Q Local Address           Foreign Address         State       Benutzer   Inode      PID/Program name  
tcp        0      0 192.168.178.230:1234    0.0.0.0:*               LISTEN      999        2303149    28589/python

**Comment by youlJunior** [comment]
So, what I think : 
- pyload is only listening on 192.168.178.230, so use this ip in your nginx conf for proxy_pass
- config file is not default.conf
   in the /usr/share/pyload/module/config/configdir file, there is the folder where you real config is located
   in this folder you will find pyload.conf

**Comment by JoergBerlin** [comment]
I dont have /usr/share/pyload/module/config/configdir 

I looked for pyload.conf

```
root@raspberrypi:/# find -name pyload.conf
./var/www/pyload/pyload.conf
./root/.pyload/pyload.conf
./home/pyload/.pyload/pyload.conf
./home/joerg/.pyload/pyload.conf
```
To check the details:

```
root@raspberrypi:/# ls -l ./var/www/pyload/pyload.conf
-rw------- 1 www-data www-data 2504 Mär 28 23:56 ./var/www/pyload/pyload.conf
root@raspberrypi:/# ls -l ./home/pyload/.pyload/pyload.conf
-rw------- 1 pyload pyload 2501 Apr  8 14:17 ./home/pyload/.pyload/pyload.conf
root@raspberrypi:/# ls -l ./home/joerg/.pyload/pyload.conf
-rw------- 1 joerg joerg 2477 Mär 29 15:18 ./home/joerg/.pyload/pyload.conf
```

So I think, ./home/pyload/.pyload/pyload.conf will be the conf-file, which is used (timestamp):

nano ./home/pyload/.pyload/pyload.conf

```
webinterface - "Webinterface":
        bool activated : "Activated" = True
        ip host : "IP" = 192.168.178.230
        bool https : "Use HTTPS" = False
        int port : "Port" = 1234
        str prefix : "Path Prefix" =
        builtin;threaded;fastcgi;lightweight server : "Server" = threaded
        str template : "Template" = pyplex
```

**Comment by youlJunior** [comment]
OK, the pyload.conf used will be the one in the home of the user which is running pyload : 
/home/[user running pyload]/.pyload/pyload.conf

If you have access to pyload web interface (http://192.168.178.230:1234) you can change ip host and Path Prefix directly in gui without knowing where the conf file is located

**Comment by JoergBerlin** [comment]
I did check the setting in the web interface. Everything correct

http://192.168.178.230:1234/ works

but why not https://mywebserver:1234 or https://mywebserver/pyload?

I just want to get access to pyload via https://mywebserver/pyload

**Comment by youlJunior** [comment]
You have to : 
- Change Path Prefix to /pyload (via Web Interface or via conf file)
- Restart pyload
- Verify you can access http://192.168.178.230:1234/pyload
- Change proxy_pass in nginx conf to "proxy_pass http://192.168.178.230:1234/pyload;"
- Restart Nginx
- Access https://mywebserver/pyload (assuming mywebserver is where Nginx listen)

**Comment by JoergBerlin** [comment]
Ok, one step forward is done. THANK YOU!!!

I can reach pyload with http://192.168.178.230:1234/pyload

But there are two problems:

1. Graphics and design not shown

2. Links are not correct: For example, click to "Administration" goes to https://192.168.178.210/admin/ and not https://192.168.178.210/pyload/admin/ (manually entered, works)

**Comment by youlJunior** [comment]
Good !
So now the problem you have point out that you don't have latest pyload files.
Did you download STABLE branch from https://github.com/pyload/pyload ?

**Comment by OzzieIsaacs** [comment]
Please make sure to have all the files in the web folder updated. Normally the jinia cache can cause this problem. In the userconfig folder there should be a folder named jinija_cache or similar. Please delete the content of that folder (not the folder itself), and restart pyload

**Comment by youlJunior** [comment]
git clone https://github.com/pyload/pyload.git -> it gets master branch, not stable one !you don't have to use git, just download https://github.com/pyload/pyload/archive/stable.zip and unzip

**Comment by OzzieIsaacs** [comment]
stable branch has no setup.py, you cloned the master branch, please try the stable branch

**Comment by JoergBerlin** [comment]
So I did:

```
wget https://github.com/pyload/pyload/archive/stable.zip
unzip stable.zip
mv pyload-stable /usr/share/
mv /usr/share/pyload-stable pyload-stable
```

then I did (

1. Change Path Prefix to /pyload (via Web Interface or via conf file)
2. Restart pyload
3. Verify you can access http://192.168.178.230:1234/pyload
4. Change proxy_pass in nginx conf to "proxy_pass http://192.168.178.230:1234/pyload;"
5. Restart Nginx
6. Access https://mywebserver/pyload (assuming mywebserver is where Nginx listen)

Result:

http://192.168.178.230:1234 --> works

https://mywebserver/pyload
-->
Graphics and design not shown. Links are not correct: For example, click to "Administration" goes to https://192.168.178.230/admin/ and not https://192.168.178.230/pyload/admin/ (manually entered, works)

**Comment by youlJunior** [comment]
How did you launch pyload ?

**Comment by GammaC0de** [comment]
You could do
`git clone -b stable https://github.com/pyload/pyload.git`
to get the stable branch.

**Comment by JoergBerlin** [comment]
ok, I tried but It doesn´t work. Thanks to all here but I give up with this situation. I think, apache is more documented and for my case, the performance difference between nginx and apache doesn´t count.  I try to set up a new raspy with apache and will try again to install monitorix. So again, thx to all. I close this thread ...

**Comment by Shadouw** [comment]
On my system the path prefix doesn't properly work.
I can access pyload via http://nginx-host/pyload.
But when I hover over the Queue button it links to http://nginx-host/queue instead of http://nginx-host/pyload/queue (which works as well.
I've tried the builtin and the threaded web server.

**Comment by GammaC0de** [comment]
@Shadouw Are you using the latest `stable` branch?

**Comment by Shadouw** [comment]
> 
> 
> @Shadouw Are you using the latest `stable` branch?

Yes, I just pulled from branch stable and tested again. I tested without nginx:
When I open https://myraspberry:8000/pyload/queue it opens the pyload queue (as expected).
When I hover over the queue button, the link shows: https://myraspberry:8000/queue

**Comment by GammaC0de** [comment]
Which web template are you using, `classic` or `pyplex`?

**Comment by youlJunior** [comment]
@Shadouw I'm using the stable branch and no problem with Nginx RP.
Normally, when Payload serve the JS files, it adds pathPrefix to all links, so they appear good.
If you have links problem with latest stable, either you don't have set the path prefix, or your Nginx conf is not correct.
Can you share your Nginx conf ?

**Comment by GammaC0de** [comment]
> either you don't have set the path prefix

Just to add for this, `path prefix` is a config option in pyLoad's configuration

**Comment by Shadouw** [comment]
I've set the `path prefix` before but I used `classic` (I never changed default templates since I had some issues in the past after upgrading pyload). Retesting with `pyplex` works: now the `path prefix` gets added to the links and it works with my nginx configuration. 
@youlJunior my config is rather simple:
```
        location /pyload {
                return 302 /pyload/;
        }

        location /pyload/ {
                proxy_pass http://localhost:8000/pyload/;
        }
```

**Comment by youlJunior** [comment]
@Shadouw great to hear that it works.
All templates works equally, both classic and pyplex have been updated ti support path prefix with #3077.
Here I use classic.

**Comment by OzzieIsaacs** [comment]
I yesterday check the code for classic and pyplex, the correct code is applied in both cases. I remember my problems from the time I applied the fix:

>     - Delete jinjia cache (while pyload is stopped)
>     - delete website cache of your browser
>     (99% of all issues with the pathprefix are caused by mixed/cached templates and scripts)

**Comment by sNiXx** [comment]
I can confirm that deleting the contents of "jinja_cache" solved the problem of wrong links being generated - my pyload instance is now reachable via "myserver.com/pyload". I set the path prefix to "/pyload" and have the following config:
```
location /pyload {
   proxy_pass http://localhost:8000;
   proxy_redirect off;
   proxy_set_header Host $host;
}
```
