### ISSUE TITLE
zippyshare.com stopped working.

### ISSUE THREAD

**Issue by oltodosel** [pyload/pyload#3149]
pyload uses BasePlugin and gets html file.
zippyshare plugin version is 0.94 
./tmp/UpdateManager/load_line242.dump.html:hoster|ZippyshareCom.py|353c669|0.94

60 | 08.04.2018 04:32:39 | INFO | restarting pyLoad
-- | -- | -- | --
61 | 08.04.2018 04:32:39 | INFO | shutting down...
62 | 08.04.2018 04:32:39 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_restart`
63 | 08.04.2018 04:32:39 | INFO | ADDON ClickNLoad: Shutting down proxy...
64 | 08.04.2018 04:32:39 | DEBUG | ADDON ClickNLoad: Server exited successfully
65 | 08.04.2018 04:32:39 | DEBUG | Deleting old pidfile pyload.pid
66 | 08.04.2018 04:32:40 | INFO | Starting pyLoad 0.4.9
67 | 08.04.2018 04:32:40 | INFO | Using home directory: /home/lom/.pyload
68 | 08.04.2018 04:32:40 | DEBUG | Remote activated: True
69 | 08.04.2018 04:32:40 | DEBUG | created index of plugins
70 | 08.04.2018 04:32:40 | INFO | Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
71 | 08.04.2018 04:32:40 | INFO | Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
72 | 08.04.2018 04:32:40 | INFO | Downloadtime: True
73 | 08.04.2018 04:32:40 | INFO | Starting ThriftBackend: 0.0.0.0:7227
74 | 08.04.2018 04:32:41 | INFO | Starting builtin webserver: 0.0.0.0:9177
75 | 08.04.2018 04:32:41 | INFO | Free space: 84.61 GiB
76 | 08.04.2018 04:32:41 | INFO | Activating Accounts...
77 | 08.04.2018 04:32:41 | INFO | Activating Plugins...
78 | 08.04.2018 04:32:41 | DEBUG | ADDON UpdateManager: LOAD URL https://github.com/pyload/updates/raw/master/plugins.txt \| redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
79 | 08.04.2018 04:32:41 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_start`
80 | 08.04.2018 04:32:41 | DEBUG | ADDON ExtractArchive: Found UnRar 5.60 \| Found SevenZip 16.02 \| Found UnZip 2.7.14 \| Found UnTar 2.7.14
81 | 08.04.2018 04:32:41 | INFO | ADDON XFileSharing: Auto-discover new hosters
82 | 08.04.2018 04:32:41 | DEBUG | ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com\|clicknupload\.org\|cramit\.in\|easybytez\.com\|exashare\.com\|filejoker\.net\|fileom\.com\|filerio\.com\|fistfast\.net\|hugefiles\.net\|junocloud\.me\|movreel\.com\|nosupload\.com\|novafile\.com\|rapidfileshare\.net\|rarefile\.net\|safesharing\.eu\|secureupload\.eu\|streamcloud\.eu\|tusfiles\.net\|uploadrocket\.net\|vidplay\.net))(?P(?:[\d.]+\|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W\|$)
83 | 08.04.2018 04:32:41 | DEBUG | Redirected import module.plugins.crypter.FilecryptCc -> userplugins.crypter.FilecryptCc
84 | 08.04.2018 04:32:41 | DEBUG | Redirected import userplugins.captcha.ReCaptcha -> module.plugins.captcha.ReCaptcha
85 | 08.04.2018 04:32:41 | DEBUG | Redirected import userplugins.captcha.SolveMedia -> module.plugins.captcha.SolveMedia
86 | 08.04.2018 04:32:41 | DEBUG | Redirected import userplugins.internal.Crypter -> module.plugins.internal.Crypter
87 | 08.04.2018 04:32:41 | INFO | ADDON XFileSharing: Auto-discover new crypters
88 | 08.04.2018 04:32:41 | DEBUG | ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com\|tusfiles\.net))(?P(?:[\d.]+\|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user\|folder)s?/\w+
89 | 08.04.2018 04:32:41 | INFO | pyLoad is up and running
90 | 08.04.2018 04:32:42 | INFO | ADDON UpdateManager: pyLoad is up to date!
91 | 08.04.2018 04:32:42 | DEBUG | ADDON UpdateManager: LOAD URL https://github.com/pyload/updates/raw/master/plugins.txt \| redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
92 | 08.04.2018 04:32:42 | DEBUG | ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'FreeWayMe'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
93 | 08.04.2018 04:32:42 | INFO | ADDON UpdateManager: All plugins are up to date!
94 | 08.04.2018 04:32:47 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
95 | 08.04.2018 04:33:01 | INFO | Download starts: file.html
96 | 08.04.2018 04:33:01 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
97 | 08.04.2018 04:33:01 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
98 | 08.04.2018 04:33:01 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
99 | 08.04.2018 04:33:01 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
100 | 08.04.2018 04:33:01 | DEBUG | HOSTER BasePlugin[662]: Plugin version: 0.52
101 | 08.04.2018 04:33:01 | DEBUG | HOSTER BasePlugin[662]: Plugin status: testing
102 | 08.04.2018 04:33:01 | WARNING | HOSTER BasePlugin[662]: Plugin may be unstable
103 | 08.04.2018 04:33:01 | DEBUG | HOSTER BasePlugin[662]: Config option `use_premium` not found, use default `True`
104 | 08.04.2018 04:33:01 | INFO | HOSTER BasePlugin[662]: Grabbing link info...
105 | 08.04.2018 04:33:01 | DEBUG | HOSTER BasePlugin[662]: Link info: {'status': 7, 'hash': {}, 'name': 'file.html', 'url': u'https://www59.zippyshare.com/v/lXRYmwGe/file.html', 'pattern': {}, 'size': 0}
106 | 08.04.2018 04:33:01 | DEBUG | HOSTER BasePlugin[662]: Previous link info: {}
107 | 08.04.2018 04:33:01 | INFO | HOSTER BasePlugin[662]: Link name: file.html
108 | 08.04.2018 04:33:01 | INFO | HOSTER BasePlugin[662]: Link size: N/D
109 | 08.04.2018 04:33:01 | INFO | HOSTER BasePlugin[662]: Link status: starting
110 | 08.04.2018 04:33:01 | INFO | HOSTER BasePlugin[662]: Processing url: https://www59.zippyshare.com/v/lXRYmwGe/file.html
111 | 08.04.2018 04:33:01 | DEBUG | HOSTER BasePlugin[662]: DOWNLOAD URL https://www59.zippyshare.com/v/lXRYmwGe/file.html \| fixurl=True \| resume=None \| get={} \| cookies=True \| disposition=True \| chunks=None \| post={} \| ref=False
112 | 08.04.2018 04:33:02 | INFO | HOSTER BasePlugin[662]: File saved
113 | 08.04.2018 04:33:02 | INFO | HOSTER BasePlugin[662]: Checking download...
114 | 08.04.2018 04:33:02 | INFO | HOSTER BasePlugin[662]: File is OK
115 | 08.04.2018 04:33:02 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
116 | 08.04.2018 04:33:02 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
117 | 08.04.2018 04:33:02 | INFO | Download finished: file.html
118 | 08.04.2018 04:33:02 | DEBUG | ADDON ExternalScripts: No script found under folder `download_finished`
119 | 08.04.2018 04:33:02 | INFO | Package finished: https://www59.zippyshare.com/v/lXRYmwGe/file.html
120 | 08.04.2018 04:33:02 | DEBUG | ADDON ExternalScripts: No script found under folder `package_finished`
121 | 08.04.2018 04:33:02 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
122 | 08.04.2018 04:33:02 | DEBUG | All downloads processed
123 | 08.04.2018 04:33:02 | DEBUG | ADDON ExtractArchive: Use for extensions: .7z\|.bz2\|.bzip2\|.gz\|.gzip\|.lha\|.lzh\|.lzma\|.rar\|.tar\|.taz\|.tbz\|.tbz2\|.tgz\|.xar\|.xz\|.z\|.zip
124 | 08.04.2018 04:33:02 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_finished`
125 | 08.04.2018 04:33:02 | DEBUG | All downloads finished
126 | 08.04.2018 04:33:02 | INFO | ADDON ExtractArchive: Check package: https://www59.zippyshare.com/v/lXRYmwGe/file.html
127 | 08.04.2018 04:33:02 | INFO | ADDON ExtractArchive: No files found to extract
128 | 08.04.2018 04:33:02 | DEBUG | ADDON ExternalScripts: No script found under folder `all_archives_extracted`
129 | 08.04.2018 04:33:02 | DEBUG | ADDON ExternalScripts: No script found under folder `all_archives_processed`

**Comment by Binomico** [comment]
Liegt imho am Plugin  \module\plugins\hoster\**ZippyshareCom.py**

`__pattern__ = r'http://(?P<HOST>www\d{0,3}\.zippyshare\.com)/(?:[vd]/|view\.jsp.*key=)(?P<KEY>[\w^_]+)'`

http --> https?

So läufts bei mir jedenfalls wieder! 

Laut deren Blog - http://blog.zippyshare.com/ - haben die Admins am 03. April auf https / ssl umgestellt.

Cheers!

**Comment by Binomico** [comment]
In doubt do a clean install of pyload - with a "clean" (pyload) config path (backup in case of sensitive data).

**Comment by led13714** [comment]
reinstalling solved the problem. Thx.

**Comment by hulyahulya** [comment]
problem again started zipsare not working

**Comment by oltodosel** [comment]
I don't have problems with zippyshare.
Just checked on https://www.filecrypt.cc/Container/E4B6B31F2D.html
