### ISSUE TITLE
[Uptobox] Issue with download free & premium

### ISSUE THREAD

**Issue by sousouille** [pyload/pyload#3150]
Hi all,

Issue with Uptobox download.

My plugin version :
- hoster : 0.34
- accounts : 0.23

**Log without free account :** 
33 | 13.04.2018 22:21:39 | INFO | Download starts: x.x.x.x.x.x.x.x264.XX3-x.x-x1.x.part1.rar
34 | 13.04.2018 22:21:39 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
35 | 13.04.2018 22:21:39 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
36 | 13.04.2018 22:21:39 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
37 | 13.04.2018 22:21:39 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
38 | 13.04.2018 22:21:39 | DEBUG | HOSTER UptoboxCom[22]: Plugin version: 0.34
39 | 13.04.2018 22:21:39 | DEBUG | HOSTER UptoboxCom[22]: Plugin status: testing
40 | 13.04.2018 22:21:39 | WARNING | HOSTER UptoboxCom[22]: Plugin may be unstable
41 | 13.04.2018 22:21:39 | INFO | HOSTER UptoboxCom[22]: Grabbing link info...
42 | 13.04.2018 22:21:41 | DEBUG | HOSTER UptoboxCom[22]: Link info: {'status': 2, 'hash': {}, 'name': u'x.x.x.x.x.x.x.x264.XX3-x.x-x1.x.part1.rar', 'url': u'http://uptobox.com/o9z58ejvc992', 'pattern': {'S': u'1.00', 'U': u'GB', 'N': u'x.x.x.x.x.x.x.x264.XX3-x.x-x1.x.part1.rar'}, 'size': 1073741824}
43 | 13.04.2018 22:21:41 | DEBUG | HOSTER UptoboxCom[22]: Previous link info: {}
44 | 13.04.2018 22:21:41 | INFO | HOSTER UptoboxCom[22]: Link name: x.x.x.x.x.x.x.x264.XX3-x.x-x1.x.part1.rar
45 | 13.04.2018 22:21:41 | INFO | HOSTER UptoboxCom[22]: Link size: 1.00 GiB (1073741824 bytes)
46 | 13.04.2018 22:21:41 | INFO | HOSTER UptoboxCom[22]: Link status: en ligne
47 | 13.04.2018 22:21:41 | INFO | HOSTER UptoboxCom[22]: Processing url: http://uptobox.com/o9z58ejvc992
48 | 13.04.2018 22:21:41 | INFO | HOSTER UptoboxCom[22]: Looking for direct download link...
49 | 13.04.2018 22:21:41 | DEBUG | HOSTER UptoboxCom[22]: LOAD URL http://uptobox.com/o9z58ejvc992 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
50 | 13.04.2018 22:21:41 | INFO | HOSTER UptoboxCom[22]: Direct download link not found
51 | 13.04.2018 22:21:41 | DEBUG | HOSTER UptoboxCom[22]: LOAD URL http://uptobox.com/o9z58ejvc992 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
52 | 13.04.2018 22:21:41 | INFO | HOSTER UptoboxCom[22]: Checking for link errors...
53 | 13.04.2018 22:21:41 | INFO | HOSTER UptoboxCom[22]: No errors found
54 | 13.04.2018 22:21:41 | INFO | HOSTER UptoboxCom[22]: Processing as free download...
55 | 13.04.2018 22:21:41 | INFO | HOSTER UptoboxCom[22]: Downloading file...
56 | 13.04.2018 22:21:41 | DEBUG | HOSTER UptoboxCom[22]: DOWNLOAD URL http://www51.uptobox.com/dl/3INpDVRFkswr4bkNdPDiC2RvxWoNoeN2zNmVWOzvgkcvKh88s32frq0uMA5DVWtSmJSqUHUsnCrQfrXiHxa78L-4l_mFSxUj1TQLhHC_ixdVsDofVATM0JqHRuZBKz2KfDAKmDh7Mo_ykSkxUzFEoA/x.x.x.x.x.x.x.x264.XX3-x.x-x1.x.part1.rar \| fixurl=True \| resume=None \| get={} \| cookies=True \| disposition=True \| chunks=None \| post={} \| ref=True
57 | 13.04.2018 22:21:41 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
58 | 13.04.2018 22:21:41 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
59 | 13.04.2018 22:21:41 | WARNING | Download failed: x.x.x.x.x.x.x.x264.XX3-x.x-x1.x.part1.rar \| 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
60 | 13.04.2018 22:21:42 | INFO | Debug Report written to debug_UptoboxCom_13-04-2018_22-21-41.zip
61 | 13.04.2018 22:21:42 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
62 | 13.04.2018 22:21:42 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: x.x.x.x.x.x.x.x264.XX3-x.x-x1.x.part1.rar (pid:7)
63 | 13.04.2018 22:21:42 | INFO | ADDON UnSkipOnFail: No duplicates found
64 | 13.04.2018 22:21:42 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
65 | 13.04.2018 22:21:42 | DEBUG | All downloads processed

**Log with premium account :** 
87	13.04.2018 22:28:32	DEBUG	ACCOUNT UptoboxCom: LOAD URL https://uptobox.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
88	13.04.2018 22:28:32	DEBUG	ACCOUNT UptoboxCom: Expire date: 18 July 2018
89	13.04.2018 22:28:32	DEBUG	ACCOUNT UptoboxCom: Valid until: 1531864800.0
90	13.04.2018 22:28:32	DEBUG	ACCOUNT UptoboxCom: TRAFFIC LEFT PATTERN not found
91	13.04.2018 22:28:32	DEBUG	ACCOUNT UptoboxCom: LEECH TRAFFIC PATTERN not found
92	13.04.2018 22:28:32	DEBUG	ACCOUNT UptoboxCom: Account info for user `xxx*******`: {'login': {'timestamp': 1523651297.851931, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1531864800.0, 'login': 'xxx*******', 'type': 'UptoboxCom', 'options': {'limitdl': '0'}}}
93	13.04.2018 22:28:32	INFO	HOSTER UptoboxCom[22]: Grabbing link info...
94	13.04.2018 22:28:32	DEBUG	HOSTER UptoboxCom[22]: Link info: {'status': 2, 'hash': {}, 'name': u'xxx.XXX.1111.part1.rar', 'url': u'http://uptobox.com/o9z58ejvc992', 'pattern': {'S': u'1.00', 'U': u'GB', 'N': u'xxx.XXX.1111.part1.rar'}, 'size': 1073741824}
95	13.04.2018 22:28:32	DEBUG	HOSTER UptoboxCom[22]: Previous link info: {}
96	13.04.2018 22:28:32	INFO	HOSTER UptoboxCom[22]: Link name: xxx.XXX.1111.part1.rar
97	13.04.2018 22:28:32	INFO	HOSTER UptoboxCom[22]: Link size: 1.00 GiB (1073741824 bytes)
98	13.04.2018 22:28:32	INFO	HOSTER UptoboxCom[22]: Link status: en ligne
99	13.04.2018 22:28:32	INFO	HOSTER UptoboxCom[22]: Processing url: http://uptobox.com/o9z58ejvc992
100	13.04.2018 22:28:32	INFO	HOSTER UptoboxCom[22]: Looking for direct download link...
101	13.04.2018 22:28:32	DEBUG	HOSTER UptoboxCom[22]: LOAD URL http://uptobox.com/o9z58ejvc992 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
102	13.04.2018 22:28:33	INFO	HOSTER UptoboxCom[22]: Direct download link not found
103	13.04.2018 22:28:33	DEBUG	HOSTER UptoboxCom[22]: LOAD URL http://uptobox.com/o9z58ejvc992 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
104	13.04.2018 22:28:33	INFO	HOSTER UptoboxCom[22]: Checking for link errors...
105	13.04.2018 22:28:33	INFO	HOSTER UptoboxCom[22]: No errors found
106	13.04.2018 22:28:33	INFO	HOSTER UptoboxCom[22]: Processing as premium download...
107	13.04.2018 22:28:33	INFO	HOSTER UptoboxCom[22]: Downloading file...
108	13.04.2018 22:28:33	DEBUG	HOSTER UptoboxCom[22]: DOWNLOAD URL http://www51.uptobox.com/dl/2f1FzY-o3WqV6Ix4XEfgzjNJsd4X3EsjLCuDPudniHF8Jf1kKaHKhRqKN7mBI9ZVV-LdKaCN8UuKchLG8rFFrDbCzSzfa6tRORnPnSifW3C_a5_QzSVzrxqVrljHAFwZX2HJH_jxdHLuMitdr8n_EQ/xxx.XXX.1111.part1.rar | fixurl=True | resume=None | get={} | cookies=True | disposition=True | chunks=None | post={} | ref=True
109	13.04.2018 22:28:33	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
110	13.04.2018 22:28:33	DEBUG	ADDON ExternalScripts: No script found under folder `package_processed`
111	13.04.2018 22:28:33	WARNING	Download failed: xxx.XXX.1111.part1.rar | 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
112	13.04.2018 22:28:33	INFO	Debug Report written to debug_UptoboxCom_13-04-2018_22-28-33.zip
113	13.04.2018 22:28:33	DEBUG	ADDON ExternalScripts: No script found under folder `download_failed`
114	13.04.2018 22:28:33	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: xxx.XXX.1111.part1.rar (pid:7)
115	13.04.2018 22:28:33	INFO	ADDON UnSkipOnFail: No duplicates found
116	13.04.2018 22:28:33	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
117	13.04.2018 22:28:33	DEBUG	All downloads processed

Can you explain me how to debug and fix this issue plz ?

Thx in advance.

BR

**Comment by GammaC0de** [comment]
`ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)`

Pyload has issues with non english (unicode) file names but the link in the log (http://uptobox.com/o9z58ejvc992) has normal english file name so I don't know how this had happened..

**Comment by sousouille** [comment]
solve by reinstall
thx
