### ISSUE TITLE
ExternalScripts:  'ascii' codec can't decode byte issue

### ISSUE THREAD

**Issue by m0n4** [pyload/pyload#3151]
Hello

I've an issue with a selfmade ExternalScripts, I'm sure it'll be obvious to you, but I can't do it alone.

14.04.2018 19:38:50 INFO      Package finished: mypackage
14.04.2018 19:38:50 INFO      ADDON ExtractArchive: Check package: mypackage
14.04.2018 19:38:50 INFO      ADDON ExternalScripts: Executing scripts in folder `all_downloads_processed`...
14.04.2018 19:38:50 INFO      ADDON ExtractArchive: No files found to extract
14.04.2018 19:38:50 WARNING   Error calling event handler allDownloadsProcessed: <bound method ExternalScripts.all_downloads_processed of <Hook ExternalScripts>>, (), 'ascii' codec can't decode byte 0x92 in position 16: ordinal not in range(128)

the python script (functional) to run under windows 
```
# coding: utf-8
import os, shutil
import unicodedata
path = r'C:/Users/TV/Downloads/PyLoad/'
moveto = r'//FREEBOX_SERVER/Disque dur/Vidéos/Pyload/'
files = os.listdir(path)
files.sort()
for f in files:
    src = path+f
    dst = moveto+f
    shutil.move(src,dst)
```

thanks in advance

**Comment by GammaC0de** [comment]
Just a hunch, try changing these lines:
files = os.listdir(path.encode('utd-8'))
shutil.move(src.encode('utd-8'), dst.encode('utd-8'))

**Comment by m0n4** [comment]
Thanks GammaC0de
If doesn't work :
`'ascii' codec can't decode byte 0x92 in position 16: ordinal not in range(128)`
Could pyload run a batch script ?

**Comment by GammaC0de** [comment]
If you are going to use a batch script then you do not need the python script..

Also, try to download with a pure ASCII (English) file name.

**Comment by m0n4** [comment]
Thank you again GammaC0de !
if it could help someone:

ECHO off
TIMEOUT /NOBREAK /T 30
robocopy /MOVE /s C:\Users\user\Downloads\PyLoad\ "\\FREEBOX_SERVER\Disque dur\**Vid‚os**\Pyload" 
MKDIR C:\Users\TV\Downloads\PyLoad\
