### ISSUE TITLE
Installation instruction outdated ?!

### ISSUE THREAD

**Issue by fmigeot-lf** [pyload/pyload#3152]
I tried to reinstalled pyload by reading the readme, but
- the pip install seems to be broken
- there is no `setup.py` in the source code

did I miss something ? or is the README outdated ?

**Comment by GammaC0de** [comment]
See #2000

**Comment by nmss** [comment]
I've had the same problem recently, and the issue you link is nice

Do you want a PR that will remove the pip info? Or is it staying for some reason?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by nmss** [comment]
Thanks, that's clearer now
