### ISSUE TITLE
Modify the destination option

### ISSUE THREAD

**Issue by miguelconde91** [pyload/pyload#3157]
Hello people, I need that my users when they add a new file to download this go directly to the collector and that does not give you the possibility of marking to go to the queue, then, I will be the one who passes it to the queue to be downloaded automatically. Something like this
![downloads - pyload interface web - mozilla firefox](https://user-images.githubusercontent.com/19227457/39258875-0488ad1a-4883-11e8-94f7-5dafbf02d9f8.jpg)

**Comment by GammaC0de** [comment]
I think There is a solution for you: 
Create a new user with just "add" permissions (have not tested it..)

![capture](https://user-images.githubusercontent.com/11036551/39309983-e6badef8-4971-11e8-8bb9-13e2e0abb5b1.PNG)

**Comment by GammaC0de** [comment]
Edit window.html then restart pyload so the changes takes effect.

**Comment by miguelconde91** [comment]
Thanks, it´s work for me. Now my pyLoad looks and work like I need it.
