### ISSUE TITLE
Nitroflare

### ISSUE THREAD

**Issue by smschumacher** [pyload/pyload#3159]
Hello,

I just bought a Nitroflare Premium Account. I added it to the account list using the account nr. shown on the website, but it just shows status = invalid and premium = none. After this I closed pyload and did a git pull during which Nitroflare was being updated. I removed the old account and added it again but it is still shown as being invalid. Is the plugin currently broken? How do I fix this? I am currently on stable and my Linux version is Debian Stretch 9.4.

Yours sincerely
Stefan

**Comment by smschumacher** [comment]
PS: I am currently on "stable".

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Well!?

**Comment by smschumacher** [comment]
Then you probably need my email, which is : s.schumacher@netcologne.de.

Yours sincerely
Stefan

2018-05-01 21:23 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
Did you see my answer?

**Comment by smschumacher** [comment]
I did, I am going to give it a try this evening.
Thank you very much for your effort.

Yours,
Stefan

2018-05-04 11:27 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
I used the email and password.

**Comment by GammaC0de** [comment]
Can we close this?

**Comment by smschumacher** [comment]
I think so. Thanks again for your effort.

2018-05-07 22:05 GMT+02:00 GammaC0de <notifications@github.com>:

**Comment by GammaC0de** [comment]
:+1:
