### ISSUE TITLE
'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by Maltrack** [pyload/pyload#3161]
Hello,

I can’t download of any hoster
Can you help me ?
Sorry my english is not very good

Thank

Bonjour,

Pourriez-vous m'aider je n'arrive a télécharger sous aucun hébergeur.
Voici le bug report.
Cordialement

[misc.py.txt](https://github.com/pyload/pyload/files/1958189/misc.py.txt)

[debug_Report.txt](https://github.com/pyload/pyload/files/1958188/debug_Report.txt)

**Comment by Maltrack** [comment]
This is the url https://uptobox.com/dherrydiurz9

I try many url for this download and try other download but still not working

**Comment by GammaC0de** [comment]
Works fine for me, please provide debug log.

**Comment by Maltrack** [comment]
Sorry for my silence, can yon think a complete reinstall should delete my bug ?

**Comment by GammaC0de** [comment]
Probably,
How exactly did you installec pyload?

**Comment by Maltrack** [comment]
This is my path : 	/storage/mon_disque/telechargements

I install with .deb file with command dpkg and i paste the plugin folder since the zip archive

**Comment by GammaC0de** [comment]
OK so start pyload with the command `pyLoadCore.py -d`, retry the download and then post the log here.

**Comment by Maltrack** [comment]
This is the log file

https://www.catupload.com/download/2ba4e11edb2885a4fadf0a83116d359f.html

**Comment by GammaC0de** [comment]
```
08.05.2018 08:33:39 WARNING   HOSTER UptoboxCom[6]: 1 hours 59 minutes 58 seconds
08.05.2018 08:33:39 DEBUG     HOSTER UptoboxCom[6]: WAIT set to timestamp 1525768418.239589|Previous waitUntil: 0.000000
08.05.2018 08:33:39 INFO      HOSTER UptoboxCom[6]: Waiting 1 hours, 59 minutes, 58 seconds...
08.05.2018 08:33:42 INFO      shutting down...
08.05.2018 08:33:43 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
```
You have aborted the download before it even started..
Please repeat this procedure and don't abort until the download actually starts...

**Comment by Maltrack** [comment]
Sorry i don’t why the first link was not write this is another log

https://www.catupload.com/download/344cf120d9fa7d62a945f0ed356d3873.html

**Comment by GammaC0de** [comment]
Do you have write permission to the download folder?

**Comment by Maltrack** [comment]
It’s mean download in progress

**Comment by Maltrack** [comment]
No change always same error

I try to reinstall pyload and the ascci error was disapeared but this is the new error :
-HOSTER XFileSharing[1]: UptoboxCom | Waiting 1 seconds...
655	14.05.2018 18:16:14	INFO	Download restarted: bsbp7z48w9xk | TEXTAREA F1 not found

**Comment by GammaC0de** [comment]
> 	14.05.2018 18:16:14 INFO Download restarted: bsbp7z48w9xk | TEXTAREA F1 not found

Disable `XFileSharing` plugin please.

**Comment by Maltrack** [comment]
Hello thanks for your help

When I disabled the plugin i got this : CRITICAL	'NoneType' object has no attribute 'group'

**Comment by GammaC0de** [comment]
Any update?

**Comment by Maltrack** [comment]
sorry for my silence

i got this

31.05.2018 13:59:08 CRITICAL  'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/share/pyload/module/ThreadManager.py", line 276, in assignJob
    job.initPlugin()
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/PyFile.py", line 103, in initPlugin
    self.plugin = self.pluginclass(self)
  File "/home/pi/.pyload/userplugins/internal/Base.py", line 99, in __init__
    self.init()
  File "/home/pi/.pyload/userplugins/hoster/XFileSharing.py", line 39, in init
    self.pyfile.url).group("DOMAIN").lower()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Maltrack** [comment]
I empty the waiting list et put a new file for download and i got his error the first error

.05.2018 14:11:32 WARNING   Download failed: Black.Panther.2018.MULTi.TRUEFRENCH.1080p.HDLight.x264.AC3-EXTREME.mkv | 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/home/pi/.pyload/userplugins/internal/Base.py", line 294, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/pi/.pyload/userplugins/internal/Hoster.py", line 124, in _process
    e)
  File "/home/pi/.pyload/userplugins/internal/Plugin.py", line 93, in log_warning
    self._log("warning", self.__type__, self.__name__, args)
  File "/home/pi/.pyload/userplugins/internal/Base.py", line 103, in _log
    msg = u" | ".join(decode(a).strip() for a in messages if a)
  File "/home/pi/.pyload/userplugins/internal/Base.py", line 103, in <genexpr>
    msg = u" | ".join(decode(a).strip() for a in messages if a)
  File "/home/pi/.pyload/userplugins/internal/misc.py", line 390, in decode
    res = unicode(value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

**Comment by tonurics** [comment]
Might be related:
I had the same error while trying to use the "Ä" character in the path and queue name, once I replaced it with a Latinate "A" everything worked as expected. In this case 0xc3 = "Ă", maybe that will help you figure out where it's being used...

I would guess there's a decode('ascii') somewhere in the python code. My suggestion would be to replace 'ascii' with 'utf-8', but that might break things on older systems that use; such as those writing to FAT filesystems.

**Comment by Maltrack** [comment]
I think my problem is not a character but the space in start of the filename who is add by pyload.  I try to download whith chrome and there is no space at the start of the filename.

I cant find where is the line who add this space

**Comment by Maltrack** [comment]
i try many and many issues but still the same error.

Someone have an idea ?

**Comment by h4wkmoon** [comment]
Issue appears each time I try to give pyload a dlc file containing non ascii characters in the package name (not the dlc file name).

**Comment by GammaC0de** [comment]
This is a known issue, I'm afraid there no solution for it until new version of pyload comes.

**Comment by tomtom602** [comment]
I now have the same issue.
I had pyload working well for a long time and since last week I have this issue.
When putting pyload in debug, I can see the string that cause problem "téléchargement en cours"
which means "downloading" in french.
pyload is running in french and my system local is fr_FR
when I put pyload in english, the problem disapear but the download fail, because of my local, I think :
pyload can't find the direct download link.
I cant change my local, other programs running on the same machine dont have any problem with it.
does the string come from pyload somewhere ? I can't find it in the code here.

**Comment by Frozen-byte** [comment]
had same issue removing umlauts from destination-Folder worked for me.
Queue -> Edit Package -> Folder
