### ISSUE TITLE
PyLoad Theme PyWhite

### ISSUE THREAD

**Issue by xunil75** [pyload/pyload#3162]
Hi guys, I need three beta testers for my new PyLoad theme called PyWhite. Please apply on the comments and I will pick someone randomly. Here's a sneak peak:

# Screencast:
![hi50qxvrc8](https://user-images.githubusercontent.com/32961904/39432109-ea4ea58a-4c92-11e8-9a37-42fe1ee526cd.gif)

**Comment by miguelconde91** [comment]
I want to test it

**Comment by SweetthD3ViL** [comment]
Would also help

**Comment by ochbob** [comment]
Any news about a public release ?

love it :)

**Comment by GammaC0de** [comment]
Since this thread is inactive for so long and no code have been released until now, I'm forced to close this.
