### ISSUE TITLE
Youtube playlist problem

### ISSUE THREAD

**Issue by TerkiKerel** [pyload/pyload#3163]
Hi,

This list can not be downloaded with pyload:
https://www.youtube.com/playlist?list=PLg-jS7VWuFqcLEKIWQFcgeqjQXDgXpyld

%95 of files are failed. I don't know why. I start the failed ones by one but they failed again.
![screenshot](https://user-images.githubusercontent.com/30633816/39487321-75fef900-4d87-11e8-8209-2dd57ca8419f.png)

Can you please help me about it.

Thank you

**Comment by GammaC0de** [comment]
Successfully downloaded 104 of 109 files, the reset were offline..

What plugin version are you using?

**Comment by GammaC0de** [comment]
Any update on this?

**Comment by TerkiKerel** [comment]
In which directory is the updateManager.py file? I could not find it on my $HOME/.pyLoad/ directory

**Comment by GammaC0de** [comment]
you can go to `http://<IP_OF_PYLOAD>/info`, there you can see "Config Folder".
UpdateManager.py should be inside `<Config Folder>/userplugins/hooks`

**Comment by TerkiKerel** [comment]
@GammaC0de I check that directory. There is only "__init__.py" file inside my <Config Folder>/userplugins/hooks directory. the "__init__.py" file is empty.

If I don't have UpdateManager, how/why my pyLoad types on startup:
`Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing`

**Comment by GammaC0de** [comment]
Well!?

**Comment by GammaC0de** [comment]
No response, closing.
