### ISSUE TITLE
pyload and zippyshare are not working

### ISSUE THREAD

**Issue by koenigmidas** [pyload/pyload#3164]
Hi,

i am using pyload on a raspberry based on follwing infrastrucuture:

Python: | 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
OS: | posix linux2 Linux raspberrypi 4.14.34+ #1110 Mon Apr 16 14:51:42 BST 2018 armv6l
pyLoad Version: | 0.4.9

I have following problems, once I have uploaded a dlc file or a single zippy link:

https://pastebin.com/SYsHyxNi

thanks so far for ypu ncie code and work.

greets
km

**Comment by GammaC0de** [comment]
Is this a new installation?

**Comment by koenigmidas** [comment]
Unfortunately not :(

**Comment by GammaC0de** [comment]
If you had a working installation, please read https://github.com/pyload/pyload/issues/2994 and after that, delete and then retry to download the URL.

**Comment by koenigmidas** [comment]
where do I find the userplugins dir, once i have followed your rasp install instruction.

**Comment by GammaC0de** [comment]
You can go to `http://<IP_OF_PYLOAD>/info`, there you can see "Config Folder".
UpdateManager.py should be inside `<Config Folder>/userplugins/hooks`

**Comment by koenigmidas** [comment]
hey gamma,

my config folder is displayed as: /home/pyload/.pyload

but i cant find any hooks dir there or in /home/pyload.


can yoi pls give me a hint how to proceed?

**Comment by koenigmidas** [comment]
Hey gamma, thnks for your fast reply.

pi@raspberrypi:/home/pyload $ ls -l
total 0

there is no content :(

once  i am looking for a userplugins dir i only get:
pi@raspberrypi:~ $ find -name userplugins
pi@raspberrypi:~ $ find userplugins
find: ‘userplugins’: No such file or directory


what I am doing wrong?

**Comment by GammaC0de** [comment]
find / -type d -name userplugins

**Comment by koenigmidas** [comment]
Ok,

need to add sudo to the find cmd in order to get a result.



pi@raspberrypi:~ $ sudo find / -type d -name userplugins
/home/pyload/.pyload/userplugins

after that:


pi@raspberrypi:~ $ cd /home/pyload/.pyload/userplugins/
-bash: cd: /home/pyload/.pyload/userplugins/: Permission denied



any clue how to proceed in order to solve this issue?

thanks so far. keep it up!

**Comment by GammaC0de** [comment]
```
su
cd /home/pyload/.pyload/userplugins/hooks
rm -f UpdateManager.py
wget --no-check-certificate https://github.com/pyload/pyload/raw/353c6692afdec4b6108555725cb5db46d02ed816/module/plugins/hooks/UpdateManager.py

**Comment by koenigmidas** [comment]
hey gamma,

thanks so far for your help.
it seems to work.


thank you very much :)
