### ISSUE TITLE
Api login with http

### ISSUE THREAD

**Issue by Seiikatsu** [pyload/pyload#3165]
Hello,
i am using pyLoad since yesterday (btw. you guys did great work already keep it up!). I have a php (laravel) backend and currently trying to login into the api of pyLoad.
My question now is, in the documentation i can see that all requests should be via http post and json formatted.

My Url is this: http://192.168.1.10:8000/api/login/

My Content-Type header is "application/json" and i'll give it as body this:
`{ "username":"seikatsu", "password":"dev"}`

The response from pyLoad is always false.
(I can login via the webinterface without any problems).

BUT if i change the Content-Type of the request to "application/x-www-form-urlencoded" and as body this:
`username=seikatsu&password=dev`

I'll get the first time a String with the session id.

Currently i don't understand why x-www-form-urlencoded works without any problems but json not. Im sure my json is correct formatted, aswell tried with something like `{ "username":"\"seikatsu\"", "password":"\"dev\""}`, but here aswell only false.

Im useing the current stable branch, last pulled yesterday.

What am i doing wrong? I read already some issues but i didnt found a solution for this problem

**Comment by GammaC0de** [comment]
I think that if you've got a session id, it worked OK and then you can proceed

**Comment by Seiikatsu** [comment]
Maybe for now it works yes, but i dont understand why it does not work with JSON. I mean its an HTTP Json Api or not? Do you see any mistakes that i did with the JSON request?

**Comment by GammaC0de** [comment]
As far I can tell, JSON is not supported for API.

**Comment by Seiikatsu** [comment]
JSON is not supported?
Why is a section for it at the wiki? https://github.com/pyload/pyload/wiki/How-to-access-the-API#example

**Comment by GammaC0de** [comment]
> To pass arguments you have two choices. Either use positional arguments, eg http://pyload-core/api/getFileData/1, where 1 is the FileID, or use keyword arguments supplied via GET or POST http://pyload-core/api/getFileData?fid=1. You can find the argument names in the Api documentation.

Argument passing is done by passing a JSON string נut rather using HTTP POST.
The format of each parameter uses JSON escape rules to determine the argument type:
> It is important that all arguments are in JSON format. So http://pyload-core/api/getFileData/1 is valid because 1 represents an integer in json format. On the other hand if the method is expecting strings, this would be correct: http://pyload-core/api/getUserData/"username"/"password".

**Comment by Seiikatsu** [comment]
Well then i unterstand this wrong, but i tried both ways aswell. For example i did:
`http://192.168.1.10:8000/api/login/"seikatsu"/"dev"`
The response was:

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error 403: Forbidden</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error 403: Forbidden</h1>
            <p>Sorry, the requested URL <tt>&#039;http://192.168.1.10:8000/api/login/%22seikatsu%22/%22dev%22&#039;</tt>
               caused an error:</p>
            <pre>&quot;Forbidden&quot;</pre>
        </body>
    </html>
> 
(Same result if i use %22 instead of each ")

And if i use parameters like:
`http://192.168.1.10:8000/api/login?username="seikatsu"&password="dev"`
The response is just "false" but my data is correct & i can login with them. Tried aswell with %22 and without ". All of them return false.

**Comment by GammaC0de** [comment]
For login you must use HTTP POST method.

**Comment by Seiikatsu** [comment]
I know & i'm usung http post. If i use http get, i get Method not allowed.

**Comment by GammaC0de** [comment]
Yes, that's the way it is implemented..

**Comment by GammaC0de** [comment]
login:
`curl "http://127.0.0.1:7000/api/login" -g -H "Host: 127.0.0.1:7000" -H "Content-Type: application/x-www-form-urlencoded" --data "username=user&password=pass"`

Works.

`curl "http://127.0.0.1:7000/api/login" -g -H "Host: 127.0.0.1:7000" -H "Content-Type: application/json" --data '{"username":"user", "password":"pass"}'`

Unsupported does not work.

Now that you have a session ID, you call the desired API:
`curl "http://127.0.0.1:7000/api/statusDownloads" -g -H "Host: 127.0.0.1:7000" -H "Content-Type: application/x-www-form-urlencoded" --data "session=ec987ba8b06d1e18a3dc69567903a4f9"`

**Comment by Seiikatsu** [comment]
Well then thanks, it works like you said. My opinion was, "json encoded" means i NEED to set the content-type to "application/json" and that it is just a lucky try that "application/x-www-form-urlencoded" works. I did not understand that.
