### ISSUE TITLE
Please change the link on "Get pyload" on pyload.net

### ISSUE THREAD

**Issue by chr0max** [pyload/pyload#3170]
As a noob I often runned into this: I simply used the "Get pyload" link on pyload.net getting to here: https://github.com/pyload/pyload/releases

This ancient version works, throws some errors, but works. But then some plugins won´t work and update and the help section leads to the spammy pyload.net. So please shut this release-site down or write in 72pt "Get the actual stable version here" or something.

Thanks,
for a cleaner internet! 
◕‿◕

**Comment by GammaC0de** [comment]
Please read #2000 .
Will update the web site soon.

**Comment by GammaC0de** [comment]
Packages updated to work with the current update server.
