### ISSUE TITLE
Pyload extract archive cant import

### ISSUE THREAD

**Issue by Evil-uncelz** [pyload/pyload#3171]
Hey there, i installed all new on my NAS 325 v 2 and first wont work anything on it, after some time its updated with some tricks. Now i had the Issue that doesnt extract anymore. What was the first point for an new Pyload.  Does anyone had an fix for it? I couldnt find it here. Thanks anyway. 

See 213

LOG: 

316 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UserscloudCom -> userplugins.hoster.UserscloudCom
-- | -- | -- | --
315 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.SolidfilesCom -> userplugins.hoster.SolidfilesCom
314 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.NitrobitNet -> userplugins.hoster.NitrobitNet
313 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.CloudzillaTo -> userplugins.hoster.CloudzillaTo
312 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.SpeedfileCz -> userplugins.hoster.SpeedfileCz
311 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.KatfileCom -> userplugins.hoster.KatfileCom
310 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UnibytesCom -> userplugins.hoster.UnibytesCom
309 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.SharebeesCom -> userplugins.hoster.SharebeesCom
308 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.FreakshareCom -> userplugins.hoster.FreakshareCom
307 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.HotfileCom -> userplugins.hoster.HotfileCom
306 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.RapidfileshareNet -> userplugins.hoster.RapidfileshareNet
305 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.DateiTo -> userplugins.hoster.DateiTo
304 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.TenluaVn -> userplugins.hoster.TenluaVn
303 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.TurbobitNet -> userplugins.hoster.TurbobitNet
302 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.MegaDebridEu -> userplugins.hoster.MegaDebridEu
301 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.GigapetaCom -> userplugins.hoster.GigapetaCom
300 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.SmuleCom -> userplugins.hoster.SmuleCom
299 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.YoutubeCom -> userplugins.hoster.YoutubeCom
298 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.FiledropperCom -> userplugins.hoster.FiledropperCom
297 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UloziskoSk -> userplugins.hoster.UloziskoSk
296 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.NosuploadCom -> userplugins.hoster.NosuploadCom
295 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.FastshareCz -> userplugins.hoster.FastshareCz
294 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.ShareFilesCo -> userplugins.hoster.ShareFilesCo
293 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.FileStoreTo -> userplugins.hoster.FileStoreTo
292 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.WarserverCz -> userplugins.hoster.WarserverCz
291 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.SpeedLoadOrg -> userplugins.hoster.SpeedLoadOrg
290 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.NowVideoSx -> userplugins.hoster.NowVideoSx
289 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.YibaishiwuCom -> userplugins.hoster.YibaishiwuCom
288 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.SharingmatrixCom -> userplugins.hoster.SharingmatrixCom
287 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.FilesonicCom -> userplugins.hoster.FilesonicCom
286 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.EpicShareNet -> userplugins.hoster.EpicShareNet
285 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.FilejokerNet -> userplugins.hoster.FilejokerNet
284 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.NowDownloadSx -> userplugins.hoster.NowDownloadSx
283 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.ZeveraCom -> userplugins.hoster.ZeveraCom
282 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.LeechThreeHundreedSixtyCom -> userplugins.hoster.LeechThreeHundreedSixtyCom
281 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.NitroflareCom -> userplugins.hoster.NitroflareCom
280 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UploadrocketNet -> userplugins.hoster.UploadrocketNet
279 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.WrzucTo -> userplugins.hoster.WrzucTo
278 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UpleaCom -> userplugins.hoster.UpleaCom
277 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.EgoFilesCom -> userplugins.hoster.EgoFilesCom
276 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.XHamsterCom -> userplugins.hoster.XHamsterCom
275 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.PornhostCom -> userplugins.hoster.PornhostCom
274 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.AlldebridCom -> userplugins.hoster.AlldebridCom
273 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.HighWayMe -> userplugins.hoster.HighWayMe
272 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.LetitbitNet -> userplugins.hoster.LetitbitNet
271 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.DodanePl -> userplugins.hoster.DodanePl
270 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.Ftp -> userplugins.hoster.Ftp
269 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UploadingCom -> userplugins.hoster.UploadingCom
268 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.NoPremiumPl -> userplugins.hoster.NoPremiumPl
267 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.PutdriveCom -> userplugins.hoster.PutdriveCom
266 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.MegaCoNz -> userplugins.hoster.MegaCoNz
265 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.GooIm -> userplugins.hoster.GooIm
264 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UploadkingCom -> userplugins.hoster.UploadkingCom
263 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.PornovkaCz -> userplugins.hoster.PornovkaCz
262 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.FilepupNet -> userplugins.hoster.FilepupNet
261 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.XFileSharing -> userplugins.hoster.XFileSharing
260 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UploadedTo -> userplugins.hoster.UploadedTo
259 | 17.05.2018 23:35:41 | DEBUG | ADDON UpdateManager: LOAD URL  https://github.com/pyload/updates/raw/master/plugins.txt \| redirect=True  \| decode=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \|  just_header=False \| post={} \| ref=True \| multipart=False
258 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UploadgigCom -> userplugins.hoster.UploadgigCom
257 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UlozTo -> userplugins.hoster.UlozTo
256 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.RgHostNet -> userplugins.hoster.RgHostNet
255 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.RapideoPl -> userplugins.hoster.RapideoPl
254 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.ZahikiNet -> userplugins.hoster.ZahikiNet
253 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.HearthisAt -> userplugins.hoster.HearthisAt
252 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UploadhereCom -> userplugins.hoster.UploadhereCom
251 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.DailymotionCom -> userplugins.hoster.DailymotionCom
250 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.RockfileEu -> userplugins.hoster.RockfileEu
249 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.SmoozedCom -> userplugins.hoster.SmoozedCom
248 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.CzshareCom -> userplugins.hoster.CzshareCom
247 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.UptoboxCom -> userplugins.hoster.UptoboxCom
246 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.PromptfileCom -> userplugins.hoster.PromptfileCom
245 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.TwojlimitPl -> userplugins.hoster.TwojlimitPl
244 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.PremiumizeMe -> userplugins.hoster.PremiumizeMe
243 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.HundredEightyUploadCom -> userplugins.hoster.HundredEightyUploadCom
242 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.YoupornCom -> userplugins.hoster.YoupornCom
241 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.MyfastfileCom -> userplugins.hoster.MyfastfileCom
240 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.FlyFilesNet -> userplugins.hoster.FlyFilesNet
239 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.FilecloudIo -> userplugins.hoster.FilecloudIo
238 | 17.05.2018 23:35:42 | DEBUG | Redirected import module.plugins.hoster.BoltsharingCom -> userplugins.hoster.BoltsharingCom
237 | 17.05.2018 23:35:41 | DEBUG | Redirected import module.plugins.hoster.ZippyshareCom -> userplugins.hoster.ZippyshareCom
236 | 17.05.2018 23:35:41 | DEBUG | Redirected import module.plugins.hoster.LolabitsEs -> userplugins.hoster.LolabitsEs
235 | 17.05.2018 23:35:41 | DEBUG | Redirected import module.plugins.hoster.LoadTo -> userplugins.hoster.LoadTo
234 | 17.05.2018 23:35:41 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_start`
233 | 17.05.2018 23:35:41 | INFO | Activating Plugins...
232 | 17.05.2018 23:35:41 | DEBUG | ACCOUNT UploadedTo: Account info for user `721*******`: {'login':  {'timestamp': 1526592940.5938201, 'password': '**********', 'valid':  True}, 'data': {'premium': True, 'plugin': ,  'trafficleft': 605332439L, 'maxtraffic': None, 'validuntil': None,  'login': '721*******', 'type': 'UploadedTo', 'options': {'limitDL':  ['0']}}}
231 | 17.05.2018 23:35:40 | DEBUG | ACCOUNT UploadedTo: Size: 577,29 \| Unit: gb
230 | 17.05.2018 23:35:40 | DEBUG | ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me \| redirect=True \|  decode=True \| cookies=True \| get={} \| req=None \| just_header=False \|  post={} \| ref=True \| multipart=False
229 | 17.05.2018 23:35:40 | INFO | ACCOUNT UploadedTo: Grabbing account info for user `721*******`...
228 | 17.05.2018 23:35:40 | DEBUG | ACCOUNT UploadedTo: LOAD URL http://uploaded.net/io/login \|  redirect=True \| decode=True \| cookies=True \| get={} \| req=None \|  just_header=False \| post={'id': '721*******', 'pw': '**********'} \|  ref=True \| multipart=False
227 | 17.05.2018 23:35:40 | DEBUG | ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me \| redirect=True \|  decode=True \| cookies=True \| get={} \| req=None \| just_header=False \|  post={} \| ref=True \| multipart=False
226 | 17.05.2018 23:35:40 | INFO | ACCOUNT UploadedTo: Login user `721*******`...
225 | 17.05.2018 23:35:40 | DEBUG | ACCOUNT UploadedTo: Reached login timeout for user `721*******`
224 | 17.05.2018 23:35:40 | INFO | ACCOUNT UploadedTo: Adding user `721*******`...
223 | 17.05.2018 23:35:40 | DEBUG | Redirected import module.plugins.accounts.UploadedTo -> userplugins.accounts.UploadedTo
222 | 17.05.2018 23:35:40 | INFO | Activating Accounts...
221 | 17.05.2018 23:35:39 | INFO | Freier Speicher: 380.85 GiBGB
220 | 17.05.2018 23:35:40 | INFO | Starting threaded webserver: 0.0.0.0:7272
219 | 17.05.2018 23:35:38 | INFO | Starte ThriftBackend: 0.0.0.0:7227
218 | 17.05.2018 23:35:38 | INFO | Downloadzeit: True
217 | 17.05.2018 23:35:38 | INFO | Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus,  BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos,  DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler,  ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter,  LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet,  PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify,  XMPP
216 | 17.05.2018 23:35:38 | INFO | Aktivierte Plugins: ClickNLoad, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
-- | -- | -- | --
215 | 17.05.2018 23:35:38 | DEBUG | Redirected import module.plugins.hooks.UserAgentSwitcher -> userplugins.hooks.UserAgentSwitcher
214 | 17.05.2018 23:35:38 | DEBUG | Redirected import module.plugins.hooks.XFileSharing -> userplugins.hooks.XFileSharing
## **213 | 17.05.2018 23:35:38 | ERROR | Fehler beim importieren von ExtractArchive: 'return' outside function (Extractor.py, line 175)**
212 | 17.05.2018 23:35:38 | DEBUG | Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
211 | 17.05.2018 23:35:38 | DEBUG | Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
210 | 17.05.2018 23:35:38 | DEBUG | Redirected import module.plugins.hooks.ClickNLoad -> userplugins.hooks.ClickNLoad
209 | 17.05.2018 23:35:38 | DEBUG | Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
208 | 17.05.2018 23:35:38 | DEBUG | Redirected import module.plugins.hooks.EventMapper -> userplugins.hooks.EventMapper
207 | 17.05.2018 23:35:38 | DEBUG | Redirected import module.plugins.internal.misc -> userplugins.internal.misc
206 | 17.05.2018 23:35:38 | DEBUG | Redirected import module.plugins.internal.Addon -> userplugins.internal.Addon
205 | 17.05.2018 23:35:38 | DEBUG | created index of plugins
204 | 17.05.2018 23:35:30 | DEBUG | Remote activated: True
203 | 17.05.2018 23:35:30 | INFO | Benutze Home-Verzeichnis: /i-data/e4fc7a33/admin/zy-pkgs/pyLoad/etc/pyload
202 | 17.05.2018 23:35:30 | INFO | starte pyLoad 0.4.9
201 | 17.05.2018 23:35:28 | DEBUG | Deleting old pidfile pyload.pid
200 | 17.05.2018 23:35:28 | DEBUG | ADDON ClickNLoad: Server exited successfully
199 | 17.05.2018 23:35:28 | INFO | ADDON ClickNLoad: Shutting down proxy...

**Comment by GammaC0de** [comment]
I suggest you:
- search for a `userplugins` directory and delete it.
- read #2000

**Comment by Evil-uncelz** [comment]
I did it like u said. it was already the Stable branch. I might forget to write tht i switched the old with the new version. I just didnt delete the _userplugins_ directory. Now i  did this it just moved the problem to an other one :(  The Updatemanager doesent seems to find. Fliecryptcc cant read either. Extract Archive cant find any files to extract now.

704 | 18.05.2018 09:27:47 | INFO | ExtractArchive: No files found to extract
-- | -- | -- | --
703 | 18.05.2018 09:27:47 | DEBUG | All downloads finished
702 | 18.05.2018 09:27:47 | DEBUG | All downloads processed
701 | 18.05.2018 09:27:47 | INFO | ExtractArchive: Check package: ******
700 | 18.05.2018 09:27:47 | ERROR | ExtractArchive: [Errno 2] No such file or directory: 'passwords.txt'
699 | 18.05.2018 09:27:47 | DEBUG | ExtractArchive: Use for extensions: 7z\|.bz2\|.bzip2\|.gz\|.gzip\|.lha\|.lzh\|.lzma\|.rar\|.tar\|.taz\|.tbz\|.tbz2\|.tgz\|.xar\|.xz\|.z\|.zip
698 | 18.05.2018 09:27:47 | INFO | Package finished: Red.Sparrow.2018.German.DTS.DL.1080p.BluRay.x265-UNFIrED
697 | 18.05.2018 09:27:47 | INFO | Download finished: ******.rar
696 | 18.05.2018 09:26:16 | DEBUG | Content-Disposition: R*****.rar
695 | 18.05.2018 09:26:16 | INFO | UploadedTo: Direct download link detected
694 | 18.05.2018 09:26:16 | DEBUG | UploadedTo: Redirect #1 to: http://am4-r1f10-stor03.uploaded.net/dl/2c8c1b3c-935e-4837-8eac-8871173a12a3
693 | 18.05.2018 09:26:16 | DEBUG | UploadedTo: Redirect #0 to: http://uploaded.net/file/**
692 | 18.05.2018 09:26:16 | DEBUG | UploadedTo: Looking for direct download link...
691 | 18.05.2018 09:26:16 | DEBUG | UploadedTo: File status: online
690 | 18.05.2018 09:26:16 | DEBUG | UploadedTo: File name: R**********.rar \| File size: 309450484 byte
689 | 18.05.2018 09:26:16 | DEBUG | UploadedTo: Current file info: {'status': 2, 'url':  u'http://uploaded.net/file/*', 'size': 309450484.0, 'name':  *************************************', 'pattern': {'ID':  u'25muh0st'}}
688 | 18.05.2018 09:26:16 | DEBUG | UploadedTo: Previous file info: {}
687 | 18.05.2018 09:26:16 | DEBUG | UploadedTo: Update file info...
686 | 18.05.2018 09:26:16 | INFO | Download starts: ****************************.rar
685 | 18.05.2018 09:20:08 | INFO | pyLoad is up and running
684 | 18.05.2018 09:20:08 | INFO | ExtractArchive: Activated UnRar 4.00\|SevenZip 9.20\|UnZip (python 2.6.2)
683 | 18.05.2018 09:20:08 | INFO | Activating Plugins...
682 | 18.05.2018 09:20:08 | DEBUG | UploadedTo: Account Info: {'premium': True, 'validuntil': None, 'trafficleft': 605028352.0}
681 | 18.05.2018 09:20:08 | DEBUG | UploadedTo: Get Account Info for 7215334
680 | 18.05.2018 09:20:08 | INFO | Activating Accounts...
679 | 18.05.2018 09:20:06 | INFO | Freier Speicher: 380.56 GiBGB
678 | 18.05.2018 09:20:07 | INFO | Starting threaded webserver: 0.0.0.0:7272
677 | 18.05.2018 09:20:06 | INFO | Starte ThriftBackend: 0.0.0.0:7227
676 | 18.05.2018 09:20:06 | INFO | Downloadzeit: True
675 | 18.05.2018 09:20:06 | INFO | Deaktivierte Plugins: AndroidPhoneNotify, BypassCaptcha,  Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha,  DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder,  ImageTyperz, JustPremium, MergeFiles, MultiHome, RestartFailed, SkipRev,  WindowsPhoneNotify
674 | 18.05.2018 09:20:06 | INFO | Aktivierte Plugins: ExternalScripts, ExtractArchive, UnSkipOnFail
673 | 18.05.2018 09:20:06 | ERROR | Fehler beim importieren von UpdateManager: No module named Addon
672 | 18.05.2018 09:20:06 | DEBUG | created index of plugins
671 | 18.05.2018 09:20:04 | DEBUG | Remote activated: True
670 | 18.05.2018 09:20:04 | INFO | Benutze Home-Verzeichnis: /i-data/e4fc7a33/admin/zy-pkgs/pyLoad/etc/pyload
669 | 18.05.2018 09:20:04 | INFO | starte pyLoad 0.4.9
668 | 18.05.2018 09:11:43 | INFO | pyLoad quits
667 | 18.05.2018 09:11:43 | DEBUG | Deleting old pidfile pyload.pid
666 | 18.05.2018 09:11:43 | INFO | shutting down...
665 | 18.05.2018 09:02:49 | DEBUG | FilecryptCc: Error decrypting weblinks: 'NoneType' object has no attribute 'group'
664 | 18.05.2018 09:02:48 | INFO | FilecryptCc: Found 0 mirrors
663 | 18.05.2018 09:02:48 | INFO | FilecryptCc: No captcha found
662 | 18.05.2018 09:02:48 | DEBUG | ReCaptcha: Key not found
661 | 18.05.2018 09:02:48 | INFO | Decrypting starts: 1A7E38F647.html?mirror=1
660 | 18.05.2018 09:02:42 | INFO | pyLoad is up and running
659 | 18.05.2018 09:02:42 | INFO | ExtractArchive: Activated UnRar 4.00\|SevenZip 9.20\|UnZip (python 2.6.2)
658 | 18.05.2018 09:02:41 | INFO | Activating Plugins...
657 | 18.05.2018 09:02:41 | DEBUG | UploadedTo: Account Info: {'premium': True, 'validuntil': None, 'trafficleft': 605028352.0}
656 | 18.05.2018 09:02:41 | DEBUG | UploadedTo: Get Account Info for 7215334
655 | 18.05.2018 09:02:40 | INFO | Aktiviere Accounts...
654 | 18.05.2018 09:02:41 | INFO | Starting threaded webserver: 0.0.0.0:7272
653 | 18.05.2018 09:02:40 | INFO | Freier Speicher: 380.56 GiBGB
652 | 18.05.2018 09:02:40 | INFO | Starte ThriftBackend: 0.0.0.0:7227
651 | 18.05.2018 09:02:40 | INFO | Downloadzeit: True
650 | 18.05.2018 09:02:40 | INFO | Deaktivierte Plugins: AndroidPhoneNotify, BypassCaptcha,  Captcha9Kw, CaptchaBrotherhood, Checksum, DeathByCaptcha,  DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder,  ImageTyperz, JustPremium, MergeFiles, MultiHome, RestartFailed, SkipRev,  WindowsPhoneNotify
649 | 18.05.2018 09:02:40 | INFO | Aktivierte Plugins: ExternalScripts, ExtractArchive, UnSkipOnFail
648 | 18.05.2018 09:02:40 | ERROR | Fehler beim importieren von UpdateManager: No module named Addon
647 | 18.05.2018 09:02:40 | DEBUG | created index of plugins
646 | 18.05.2018 09:02:37 | DEBUG | Remote activated: True
645 | 18.05.2018 09:02:37 | INFO | Benutze Home-Verzeichnis: /i-data/e4fc7a33/admin/zy-pkgs/pyLoad/etc/pyload
644 | 18.05.2018 09:02:37 | INFO | starte pyLoad 0.4.9
643 | 18.05.2018 09:02:36 | DEBUG | Deleting old pidfile pyload.pid
642 | 18.05.2018 09:02:36 | DEBUG | ADDON ClickNLoad: Server exited successfully
641 | 18.05.2018 09:02:36 | INFO | ADDON ClickNLoad: Shutting down proxy...
640 | 18.05.2018 09:02:36 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_restart`
639 | 18.05.2018 09:02:36 | INFO | shutting down...
638 | 18.05.2018 09:02:36 | INFO | restarting pyLoad

**Comment by GammaC0de** [comment]
`673 | 18.05.2018 09:20:06 | ERROR | Fehler beim importieren von UpdateManager: No module named Addon`

Your installation is still not OK.

Uninstall pyload and delete `userplugins` directory, and download the [stable branch](https://github.com/pyload/pyload/archive/stable.zip).

**Comment by GammaC0de** [comment]
No response, closing.
