### ISSUE TITLE
Rapidgator.net - Login handshake has failed

### ISSUE THREAD

**Issue by SylvesterAT** [pyload/pyload#3178]
Hey,

for a few days, pyload is not able to login to my rapidgator.net account anymore.

I can see in the log, the following error:

240 | 02.06.2018 20:44:44 | INFO | ACCOUNT RapidgatorNet: Adding user `win*******`...
-- | -- | -- | --
241 | 02.06.2018 20:44:44 | INFO | ACCOUNT RapidgatorNet: Login user `win*******`...
242 | 02.06.2018 20:44:44 | ERROR | ACCOUNT RapidgatorNet: (35, 'Unknown SSL protocol error in connection to rapidgator.net:443 ')
243 | 02.06.2018 20:44:44 | ERROR | ACCOUNT RapidgatorNet: Could not login user `win*******` \| Login handshake has failed

What can I do to fix this issue?

**Comment by GammaC0de** [comment]
What OS are you running?

**Comment by SylvesterAT** [comment]
Windows, other accounts are working.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
I have tested it on windows 7 and it worked fine.

my pyload installation uses "PycURL/7.19.5.3 libcurl/7.45.0 WinSSL zlib/1.2.8".

**Comment by SylvesterAT** [comment]
It is running on a Windows Home Server 2011. I just tried to reinstall pyload but it did not solve the problem. My uploaded.to account works.

**Comment by GammaC0de** [comment]
What PycURL version are you using?

**Comment by SylvesterAT** [comment]
mhm how can I see the PycURL version? In the System Check it only says OK.

**Comment by GammaC0de** [comment]
```
C:\> python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
>>> pycurl.version
'PycURL/7.19.5.3 libcurl/7.45.0 WinSSL zlib/1.2.8'
>>> 
```

**Comment by SylvesterAT** [comment]
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (
AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
>>> pycurl.version
'PycURL/7.19.5.3 libcurl/7.45.0 WinSSL zlib/1.2.8'

Actually, it is the same as you have.

**Comment by GammaC0de** [comment]
How did you installed pyload?

**Comment by GammaC0de** [comment]
No response, closing.
