### ISSUE TITLE
pyload and zippyshare links are not working again

### ISSUE THREAD

**Issue by koenigmidas** [pyload/pyload#3180]
hi there,

i had a similiar issue last time (#3164).

currently i am running a raspberry with:
Linux raspberrypi 4.14.34+

based on your github description pyload installation.

and once i am adding zippyshare sources for download i get the following:

https://pastebin.com/FeNk9tnT

I am not sure if I did anything wrong because I have not changed any setting on the raspi or in pyload.

Perhaps its only a small thing which you can tell me quickly to fix it.

thanks so far and have a nice sunday!

**Comment by koenigmidas** [comment]
Hi gamma,
what does that mean?

is this issue still open and will be fixed or is there already a fix available? thx for your short feedback

greetz

**Comment by GammaC0de** [comment]
It had been fixed, update your plugin to v0.97.

**Comment by koenigmidas** [comment]
thank mate - i am helpless without your comments :)


is there a tutorial available? where i can see how to update and where to get the plugin?

**Comment by GammaC0de** [comment]
If you have the UpdateManager plugin functioning correctly, the update should have been automatic.

Restart pyload and see if it works now.

**Comment by koenigmidas** [comment]
well i should habe the latest updatemanager.py - i reapted all you said from #3164 to be 100% sure

but after whole reboot of the raspberry zippyshare downloads still not working.

i uploaded an dlc  file with zippy links. upload worked and i can see different links but no download.



620 | 03.06.2018 22:26:22 | INFO | HOSTER BasePlugin[71]: Grabbing link info...
-- | -- | -- | --
619 | 03.06.2018 22:26:21 | WARNING | HOSTER BasePlugin[71]: Plugin may be unstable
618 | 03.06.2018 22:26:21 | INFO | Download starts: https://www86.zippyshare.com/v/XXXXX/file.html
617 | 03.06.2018 22:26:20 | INFO | Download skipped: file.html due to File exists
616 | 03.06.2018 22:26:20 | INFO | HOSTER BasePlugin[70]: Link status: starte
615 | 03.06.2018 22:26:20 | INFO | HOSTER BasePlugin[70]: Link size: N/D
614 | 03.06.2018 22:26:20 | INFO | HOSTER BasePlugin[70]: Link name: file.html
613 | 03.06.2018 22:26:19 | INFO | HOSTER BasePlugin[70]: Grabbing link info...
612 | 03.06.2018 22:26:19 | WARNING | HOSTER BasePlugin[70]: Plugin may be unstable



and so on :(

**Comment by GammaC0de** [comment]
Correct URL is https://github.com/pyload/pyload-plugins/raw/stable/pyload/plugins/hoster/ZippyshareCom.py.

Replace  the file and then delete the package and readd it again.

**Comment by koenigmidas** [comment]
did it - also tested a new dlc file - but does not work.


1012 | 03.06.2018 22:36:58 | INFO | HOSTER BasePlugin[172]: Link status: starte
-- | -- | -- | --
1011 | 03.06.2018 22:36:58 | INFO | HOSTER BasePlugin[172]: Link size: N/D
1010 | 03.06.2018 22:36:58 | INFO | HOSTER BasePlugin[172]: Link name: file.html
1009 | 03.06.2018 22:36:58 | INFO | HOSTER BasePlugin[172]: Grabbing link info...
1008 | 03.06.2018 22:36:58 | WARNING | HOSTER BasePlugin[172]: Plugin may be unstable
1007 | 03.06.2018 22:36:58 | INFO | Download starts: https://www68.zippyshare.com/v/XXX/file.html
1006 | 03.06.2018 22:36:56 | INFO | Download skipped: file.html due to File exists
1005 | 03.06.2018 22:36:56 | INFO | HOSTER BasePlugin[171]: Link status: starte
1004 | 03.06.2018 22:36:56 | INFO | HOSTER BasePlugin[171]: Link size: N/D
1003 | 03.06.2018 22:36:56 | INFO | HOSTER BasePlugin[171]: Link name: file.html
1002 | 03.06.2018 22:36:56 | INFO | HOSTER BasePlugin[171]: Grabbing link info...
1001 | 03.06.2018 22:36:56 | WARNING | HOSTER BasePlugin[171]: Plugin may be unstable
1000 | 03.06.2018 22:36:55 | INFO | Download starts: https://www27.zippyshare.com/v/XXX/file.html
999 | 03.06.2018 22:36:54 | INFO | Download skipped: file.html due to File exists

**Comment by koenigmidas** [comment]
ok - first of all - thanks for you very fast replies!



So what can I do? do you need more informations from me - if yes wha di you need and where can i get it for you?

**Comment by GammaC0de** [comment]
Did you restart pyload? replacing the file is not enough, you have to restart to take effect and also re-add the package after that.

**Comment by koenigmidas** [comment]
i did restart pyload and restart the whole raspberry as well.


1031 | 03.06.2018 23:02:21 | INFO | pyLoad is up and running
-- | -- | -- | --
1030 | 03.06.2018 23:02:21 | INFO | ADDON XFileSharing: Auto-discover new crypters
1029 | 03.06.2018 23:02:20 | INFO | ADDON XFileSharing: Auto-discover new hosters
1028 | 03.06.2018 23:02:18 | INFO | Starting builtin webserver: 0.0.0.0:8000
1027 | 03.06.2018 23:02:10 | INFO | Aktiviere Plugins...
1026 | 03.06.2018 23:02:10 | INFO | Aktiviere Accounts...
1025 | 03.06.2018 23:02:10 | INFO | Freier Speicher: 52.03 GiBGB
1024 | 03.06.2018 23:02:10 | INFO | Downloadzeit: True
1023 | 03.06.2018 23:02:10 | INFO | Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
1022 | 03.06.2018 23:02:10 | INFO | Aktivierte Plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
1021 | 03.06.2018 23:02:05 | INFO | Benutze Home-Verzeichnis: /home/pyload/.pyload
1020 | 03.06.2018 23:02:05 | INFO | starte pyLoad 0.4.9
1019 | 03.06.2018 23:01:59 | INFO | ADDON ClickNLoad: Shutting down proxy...
1018 | 03.06.2018 23:01:59 | INFO | shutting down...
1017 | 03.06.2018 23:01:59 | INFO | restarting pyLoad




added the file again and got the error:
 

1096 | 03.06.2018 23:03:22 | INFO | HOSTER BasePlugin[8]: Link status: starte
-- | -- | -- | --
1095 | 03.06.2018 23:03:22 | INFO | HOSTER BasePlugin[8]: Link size: N/D
1094 | 03.06.2018 23:03:22 | INFO | HOSTER BasePlugin[8]: Link name: file.html
1093 | 03.06.2018 23:03:22 | INFO | HOSTER BasePlugin[8]: Grabbing link info...
1092 | 03.06.2018 23:03:22 | WARNING | HOSTER BasePlugin[8]: Plugin may be unstable
1091 | 03.06.2018 23:03:22 | INFO | Download starts: https://www68.zippyshare.com/v/XXX/file.html



I am sad :(

**Comment by GammaC0de** [comment]
Delete ZippyshareCom.py and then restart pyload, wait one minute and see if there is a new ZippyshareCom.py downloaded.

**Comment by koenigmidas** [comment]
Ok. 
now we got a little success.
i rm it and after restart there is a new .py file in the dir.


BUT


1179 | 03.06.2018 23:11:47 | INFO | HOSTER BasePlugin[16]: Link status: starte
-- | -- | -- | --
1178 | 03.06.2018 23:11:47 | INFO | HOSTER BasePlugin[16]: Link size: N/D
1177 | 03.06.2018 23:11:47 | INFO | HOSTER BasePlugin[16]: Link name: file.html
1176 | 03.06.2018 23:11:47 | INFO | HOSTER BasePlugin[16]: Grabbing link info...
1175 | 03.06.2018 23:11:47 | WARNING | HOSTER BasePlugin[16]: Plugin may be unstable
1174 | 03.06.2018 23:11:47 | INFO | Download starts: https://www68.zippyshare.com/v/XXX/file.html

**Comment by GammaC0de** [comment]
OK, plugin updated again to support https urls, restart pyload and readd the file.

**Comment by GammaC0de** [comment]
I added support https urls,.
