### ISSUE TITLE
Hoster 1fichier does not work

### ISSUE THREAD

**Issue by Qubits01** [pyload/pyload#3182]
Edit: Can be closed. I found out that they (obviously recently) banned my subnet :/

I get a 403 error.

06.06.2018 13:15:40 INFO      ACCOUNT OneFichierCom: Grabbing account info for user `XXX*******`...
06.06.2018 13:15:41 INFO      HOSTER OneFichierCom[1019]: Grabbing link info...
06.06.2018 13:15:42 INFO      HOSTER OneFichierCom[1019]: Link name: XXXX.rar
06.06.2018 13:15:42 INFO      HOSTER OneFichierCom[1019]: Link size: 40.43 MiB (42393927 bytes)
06.06.2018 13:15:42 INFO      HOSTER OneFichierCom[1019]: Link status: online
06.06.2018 13:15:42 INFO      HOSTER OneFichierCom[1019]: Processing url: https://1fichier.com/?k97o8igxxx
06.06.2018 13:15:42 INFO      HOSTER OneFichierCom[1019]: Looking for direct download link...
06.06.2018 13:15:42 WARNING   Download failed: XXXX.rar | Bad server response: 403 Forbidden

**Comment by GammaC0de** [comment]
:+1:
