### ISSUE TITLE
Zippyshare download still not working on the latest version

### ISSUE THREAD

**Issue by elbasan** [pyload/pyload#3184]
![image](https://user-images.githubusercontent.com/12799363/41197773-1b34ca12-6c69-11e8-9a01-b18d05e343bd.png)

Full log:
https://pastebin.com/raw/kcqGKNFF

**Comment by GammaC0de** [comment]
> 10.06.2018 02:10:01 INFO      ADDON UpdateManager: New version of plugin: HOSTER ZippyshareCom (v0.96 -> v0.98)

Please restart pyload and try again.

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by elbasan** [comment]
That Worked, sorry!
