### ISSUE TITLE
[hoster] 1fichier - malfuctionning - naming the file

### ISSUE THREAD

**Issue by zephura** [pyload/pyload#3188]
Hi, since the update of 1fichier a couple of day ago, the plugins did not rename the file.

no need to provide a log extract, but here it is at the bottom for the example
http://1fichier.com/?49bn3h8no0
the downloaded file was "?49bn3h8no0"

more interesting, here is the extract of the 1fichier source code
`				<td class="titre normal" style="width:180px">Filename :</td>`
`				<td class="normal">Lucifer.S03E26.FiNAL.FRENCH.HDTV.XviD-ZT.1ww.Zone-Telechargement1.com.avi</td>`

so I guess (I try to understand how regexp are working ) in the plugin, it will be translated into
`NAME_PATTERN = r'>Filename :</td>\s*<td.*>(?P<N>.+?)<'`

_not tried because, last time I did something like this, I messed everything up :'(_

208 | 19.06.2018 20:50:04 | INFO | HOSTER OneFichierCom[1863]: No errors found
-- | -- | -- | --
209 | 19.06.2018 20:50:04 | INFO | HOSTER OneFichierCom[1863]: Grabbing link info...
210 | 19.06.2018 20:50:05 | INFO | HOSTER OneFichierCom[1863]: Link name: ?49bn3h8no0
211 | 19.06.2018 20:50:05 | INFO | HOSTER OneFichierCom[1863]: Link size: 350.38 MiB (367400058 bytes)
212 | 19.06.2018 20:50:05 | INFO | HOSTER OneFichierCom[1863]: Link status: en ligne
213 | 19.06.2018 20:50:05 | INFO | HOSTER OneFichierCom[1863]: Processing as free download...
214 | 19.06.2018 20:50:05 | INFO | HOSTER OneFichierCom[1863]: Checking for link errors...
215 | 19.06.2018 20:50:05 | INFO | HOSTER OneFichierCom[1863]: No errors found
216 | 19.06.2018 20:50:05 | INFO | HOSTER OneFichierCom[1863]: Downloading file...
217 | 19.06.2018 21:02:02 | INFO | HOSTER OneFichierCom[1863]: File saved
218 | 19.06.2018 21:02:02 | INFO | HOSTER OneFichierCom[1863]: Checking download...
219 | 19.06.2018 21:02:02 | INFO | HOSTER OneFichierCom[1863]: File is OK
220 | 19.06.2018 21:02:02 | INFO | HOSTER OneFichierCom[1863]: Checking file (with built-in rules)...
221 | 19.06.2018 21:02:03 | INFO | HOSTER OneFichierCom[1863]: Checking file (with custom rules)...
222 | 19.06.2018 21:02:03 | INFO | HOSTER OneFichierCom[1863]: Checking for link errors...
223 | 19.06.2018 21:02:03 | INFO | HOSTER OneFichierCom[1863]: No errors found
224 | 19.06.2018 21:02:03 | INFO | HOSTER OneFichierCom[1863]: No errors found
225 | 19.06.2018 21:02:03 | INFO | Download finished: ?49bn3h8no0

**Comment by GammaC0de** [comment]
:+1:
