### ISSUE TITLE
Open source solution for CnL with (non root) ANDROID device to NAS (WIFI)?

### ISSUE THREAD

**Issue by Binomico** [pyload/pyload#3189]
Hi there!

I'm looking for an open source solution to download via click'n'load on my Huawei P10 (non root) to my NAS (just in the local network / wifi).

I've found a commercial app ('FWD' at the marketplace) which forwards the local port (9666) to the NAS adress and port. But the app is as wrote bevore commercial (ads and i dont know about the operation itselve) and i prefer open source or at least ad-free!

Anybody a guess / solution? Maybe with a ssh app? ... could netcat be a solution? I'm not that expert in android things, maybe u r ❓ 

Thanks in advance! ... and have fun watching football 🤙

**Comment by GammaC0de** [comment]
Try this: https://github.com/pyload/android-app/files/1195457/org.pyload.android.client_18.zip

**Comment by Binomico** [comment]
Thanks!

Is there any kind of tutorial or out there? I don't get a connection to pyload with port 7227. If I choose 8000, the interface port the connection gets lost, for sure .... to check if there is any communication!

I've also set a virtual server at the router (port forwarding).

And herewith the click n load could be done?

Cheers
