### ISSUE TITLE
PyLoad in Quickbox - Service Unavailable

### ISSUE THREAD

**Issue by Samaf** [pyload/pyload#3190]
Hi,
I installed PyLoad with Quickbox.
When I run PyLoad PyLoad, i have this message:

`Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.`

What is this error message ?
Thx for this response :)

Cordialy,

**Comment by GammaC0de** [comment]
Are you able to browse to http://localhost:8000/pyload from the Quickbox server?

**Comment by Samaf** [comment]
This link don't run.
For access this PyLoad, i use this link: https://localhost/pyload/login

**Comment by GammaC0de** [comment]
What does `service pyload status` says?

**Comment by Samaf** [comment]
`pyload.service
Loaded: not-found (Reason: No such file or directory)
Active: inactive (dead)`

For install PyLoad, i use this webinterface.
https://image.noelshack.com/fichiers/2018/25/7/1529792151-pyload.png

**Comment by GammaC0de** [comment]
Does this helps? https://plaza.quickbox.io/t/pyload-not-loading/965

**Comment by GammaC0de** [comment]
No response, closing.
