### ISSUE TITLE
Omit Package name and just download the links?

### ISSUE THREAD

**Issue by oimaasi** [pyload/pyload#3191]
It seems impossible to run `pyLoadCli add http://myurl` and let it just download the link I want. It will give me the following error message
```
Please use this syntax: add <Package name> <link> <link2> ...
```
But I don't want to specify the package name each time since I am running it in a automated script. I also have `bool folder_per_package : "Create folder for each package" = False`

Why is the package name absolutely neccessary? Is there any workaround? 

Moreover, could I just give a dummy package name?

**Comment by GammaC0de** [comment]
You can give any package name you like.

package is used to group several links together, for example:
package "ubuntu" contains 3 urls to dvd1.iso dvd2.iso and dvd3.iso.
