### ISSUE TITLE
How to use pyLoadCli add in a pipe

### ISSUE THREAD

**Issue by oimaasi** [pyload/pyload#3192]
Can pyLoadCli take links from STDIN?

```
cat mylinks.txt | pyLoadCli package_name 
or
cat mylinks.txt | pyLoadCli package_name -
```
I tried both but neither worked.

My use case is that I need to run a series of command line tools to extract the links for download. It would be nice to just add pyLoadCli to the pipe.

**Comment by GammaC0de** [comment]
`cat mylinks.txt | xargs -d\n pyLoadCli package_name `

**Comment by oimaasi** [comment]
Thanks.
```
cat mylinks.txt | xargs -d "\n" pyLoadCli add package_name
```
works for me.
