### ISSUE TITLE
pypi link gone

### ISSUE THREAD

**Issue by ahmedtds** [pyload/pyload#3193]
404

**Comment by GammaC0de** [comment]
There is nothin I can do about it beside delete it from README.md

**Comment by ahmedtds** [comment]
Why was it deleted? Is there no other easy way to install it?

**Comment by GammaC0de** [comment]
I do not have access to it and It had never worked anyway. 

You can download it from here: https://github.com/pyload/pyload/releases

**Comment by ahmedtds** [comment]
But last release is from 5 years ago in that page?

**Comment by GammaC0de** [comment]
You have two options:
- Use https://github.com/pyload/pyload/releases (it will update the plugins to current).
- Download and extract https://github.com/pyload/pyload/archive/master.zip to the installation folder (you get the plugin updates + many bug fixes).

**Comment by ahmedtds** [comment]
I see but why not make a new release at least once or twice a year?

**Comment by GammaC0de** [comment]
pyLoad self updates its plugins. 
A new release is only necessary when pyLoad's core changes.

A new version is planned soon.
