### ISSUE TITLE
No captcha shown although 'captcha-interactive.zip' was installed

### ISSUE THREAD

**Issue by faezzi** [pyload/pyload#3197]
When trying to download a file from shareonline, I do not see captchas to solve. Loading with 9kw-plugin is possible though.
![pyload_no_captcha](https://user-images.githubusercontent.com/38786074/42270914-4b043094-7f82-11e8-97aa-32e81edc09f7.png)

What I did (to my running pyload-installation):
stopped pyload
deleted folder 'userplugins'
installed tampermonkey (4.7.5788)
and TamperMonkey script (https://github.com/GammaC0de/pyload/raw/captcha-interactive/module/web/media/js/captcha-interactive.user.js)

restarted pyload, but issue persists.

This is the log:
`` 04.07.2018 12:00:09 INFO      starte pyLoad 0.4.9
04.07.2018 12:00:09 INFO      Benutze Home-Verzeichnis: /home/toni/.pyload
04.07.2018 12:00:09 DEBUG     Remote activated: True
04.07.2018 12:00:10 DEBUG     created index of plugins
04.07.2018 12:00:11 INFO      Aktivierte Plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
04.07.2018 12:00:11 INFO      Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
04.07.2018 12:00:11 INFO      Downloadzeit: True
04.07.2018 12:00:11 INFO      Starte ThriftBackend: 0.0.0.0:7227
04.07.2018 12:00:11 INFO      Freier Speicher: 290.81 GiBGB
04.07.2018 12:00:11 INFO      Aktiviere Accounts...
04.07.2018 12:00:11 INFO      Aktiviere Plugins...
04.07.2018 12:00:13 INFO      Starting builtin webserver: 0.0.0.0:8000
04.07.2018 12:00:13 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_start`
04.07.2018 12:00:13 DEBUG     ADDON ExtractArchive: Found UnRar 5.21 | Found SevenZip 9.20 | Found UnZip 2.7.9 | Found UnTar 2.7.9
04.07.2018 12:00:13 INFO      ADDON XFileSharing: Auto-discover new hosters
04.07.2018 12:00:13 DEBUG     ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|clicknupload\.org|cramit\.in|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|fistfast\.net|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uploadrocket\.net|vidplay\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
04.07.2018 12:00:14 INFO      ADDON XFileSharing: Auto-discover new crypters
04.07.2018 12:00:14 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
04.07.2018 12:00:14 INFO      pyLoad is up and running
04.07.2018 12:00:14 DEBUG     ADDON UpdateManager: LOAD URL https://github.com/pyload/updates/raw/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:15 INFO      ADDON UpdateManager: pyLoad is up to date!
04.07.2018 12:00:15 DEBUG     ADDON UpdateManager: LOAD URL https://github.com/pyload/updates/raw/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:15 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'FreeWayMe'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
04.07.2018 12:00:15 INFO      ADDON UpdateManager: New version of plugin: ACCOUNT RealdebridCom (v0.56 -> v0.57)
04.07.2018 12:00:15 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/e72e080/module/plugins/accounts/RealdebridCom.py | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x7effa54fae20> | decode=False | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:15 INFO      ADDON UpdateManager: New version of plugin: CAPTCHA UlozTo (v0.04 -> v0.05)
04.07.2018 12:00:15 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/e21a338/module/plugins/captcha/UlozTo.py | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x7effa54fae20> | decode=False | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:16 INFO      ADDON UpdateManager: New version of plugin: HOSTER DailymotionCom (v0.28 -> v0.30)
04.07.2018 12:00:16 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/0e65b66/module/plugins/hoster/DailymotionCom.py | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x7effa54fae20> | decode=False | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:16 INFO      ADDON UpdateManager: New plugin: HOSTER FiregetCom (v0.01)
04.07.2018 12:00:16 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/3bec6f9/module/plugins/hoster/FiregetCom.py | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x7effa54fae20> | decode=False | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:16 INFO      ADDON UpdateManager: New version of plugin: HOSTER OneFichierCom (v1.12 -> v1.13)
04.07.2018 12:00:16 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/5037cd0/module/plugins/hoster/OneFichierCom.py | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x7effa54fae20> | decode=False | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:16 INFO      ADDON UpdateManager: New version of plugin: HOSTER RapidgatorNet (v0.51 -> v0.52)
04.07.2018 12:00:16 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/3e38243/module/plugins/hoster/RapidgatorNet.py | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x7effa54fae20> | decode=False | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:16 INFO      ADDON UpdateManager: New version of plugin: HOSTER RealdebridCom (v0.76 -> v0.77)
04.07.2018 12:00:16 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/e72e080/module/plugins/hoster/RealdebridCom.py | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x7effa54fae20> | decode=False | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:16 INFO      ADDON UpdateManager: New version of plugin: HOSTER ShareplaceCom (v0.18 -> v0.19)
04.07.2018 12:00:16 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/d6a3c6f/module/plugins/hoster/ShareplaceCom.py | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x7effa54fae20> | decode=False | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:17 INFO      ADDON UpdateManager: New version of plugin: HOSTER UlozTo (v1.39 -> v1.40)
04.07.2018 12:00:17 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/5bc0b0c/module/plugins/hoster/UlozTo.py | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x7effa54fae20> | decode=False | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:17 INFO      ADDON UpdateManager: New version of plugin: HOSTER ZippyshareCom (v0.96 -> v0.98)
04.07.2018 12:00:17 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/pyload/0876b38/module/plugins/hoster/ZippyshareCom.py | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0x7effa54fae20> | decode=False | multipart=False | post={} | ref=True | just_header=False
04.07.2018 12:00:17 INFO      ADDON UpdateManager: *** Plugins updated ***
04.07.2018 12:00:17 DEBUG     Request reload of plugins: [(u'accounts', u'RealdebridCom'), (u'captcha', u'UlozTo'), (u'hoster', u'DailymotionCom'), (u'hoster', u'FiregetCom'), (u'hoster', u'OneFichierCom'), (u'hoster', u'RapidgatorNet'), (u'hoster', u'RealdebridCom'), (u'hoster', u'ShareplaceCom'), (u'hoster', u'UlozTo'), (u'hoster', u'ZippyshareCom')]
04.07.2018 12:00:17 DEBUG     Reloading DailymotionCom
04.07.2018 12:00:17 DEBUG     Reloading OneFichierCom
04.07.2018 12:00:17 DEBUG     Reloading RapidgatorNet
04.07.2018 12:00:17 DEBUG     Reloading RealdebridCom
04.07.2018 12:00:17 DEBUG     Reloading ShareplaceCom
04.07.2018 12:00:17 DEBUG     Reloading UlozTo
04.07.2018 12:00:17 DEBUG     Reloading ZippyshareCom
04.07.2018 12:00:20 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
04.07.2018 12:00:34 INFO      Download starts: grm-0603.rar
04.07.2018 12:00:34 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
04.07.2018 12:00:34 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
04.07.2018 12:00:34 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
04.07.2018 12:00:34 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
04.07.2018 12:00:34 DEBUG     HOSTER ShareonlineBiz[1]: Plugin version: 0.67
04.07.2018 12:00:34 DEBUG     HOSTER ShareonlineBiz[1]: Plugin status: testing
04.07.2018 12:00:34 WARNING   HOSTER ShareonlineBiz[1]: Plugin may be unstable
04.07.2018 12:00:34 INFO      HOSTER ShareonlineBiz[1]: Grabbing link info...
04.07.2018 12:00:34 DEBUG     HOSTER ShareonlineBiz[1]: Link info: {'status': 2, 'hash': {}, 'name': 'grm-0603.rar', 'url': u'http://www.share-online.biz/dl/IBIDYF4PG3A', 'pattern': {'ID': u'IBIDYF4PG3A'}, 'size': 390001660, 'md5': '6be377e139393d6ac8726955e4b55cd4', 'fileid': 'IBIDYF4PG3A'}
04.07.2018 12:00:34 DEBUG     HOSTER ShareonlineBiz[1]: Previous link info: {}
04.07.2018 12:00:34 INFO      HOSTER ShareonlineBiz[1]: Link name: grm-0603.rar
04.07.2018 12:00:34 INFO      HOSTER ShareonlineBiz[1]: Link size: 371.93 MiB (390001660 bytes)
04.07.2018 12:00:34 INFO      HOSTER ShareonlineBiz[1]: Link status: online
04.07.2018 12:00:34 INFO      HOSTER ShareonlineBiz[1]: Processing url: http://www.share-online.biz/dl/IBIDYF4PG3A
04.07.2018 12:00:34 INFO      HOSTER ShareonlineBiz[1]: Looking for direct download link...
04.07.2018 12:00:34 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.share-online.biz/dl/IBIDYF4PG3A | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
04.07.2018 12:00:34 INFO      HOSTER ShareonlineBiz[1]: Direct download link not found
04.07.2018 12:00:34 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.share-online.biz/dl/IBIDYF4PG3A | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
04.07.2018 12:00:34 INFO      HOSTER ShareonlineBiz[1]: Processing as free download...
04.07.2018 12:00:34 DEBUG     HOSTER ShareonlineBiz[1]: WAIT set to timestamp 1530698438.443301 | Previous waitUntil: 0.000000
04.07.2018 12:00:34 DEBUG     HOSTER ShareonlineBiz[1]: RECONNECT not required | Previous wantReconnect: False
04.07.2018 12:00:34 INFO      HOSTER ShareonlineBiz[1]: Waiting 3 seconds...
04.07.2018 12:00:38 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.share-online.biz/dl/IBIDYF4PG3A/free/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'dl_free': '1', 'choice': 'free'} | ref=True | just_header=False
04.07.2018 12:00:38 DEBUG     CAPTCHA ShareonlineBiz[1]: ReCaptcha | Key: 6LdnPkIUAAAAABqC_ITR9-LTJKSdyR_Etj1Sf-Xi
04.07.2018 12:00:38 DEBUG     CAPTCHA ShareonlineBiz[1]: ReCaptcha | Detected reCAPTCHA v2
04.07.2018 12:00:38 WARNING   CAPTCHA ShareonlineBiz[1]: ReCaptcha | Secure Token pattern not found
04.07.2018 12:00:38 DEBUG     HOSTER ShareonlineBiz[1]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6LdnPkIUAAAAABqC_ITR9-LTJKSdyR_Etj1Sf-Xi | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=http://www.share-online.biz/dl/IBIDYF4PG3A | just_header=False
04.07.2018 12:00:38 WARNING   CAPTCHA ShareonlineBiz[1]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
04.07.2018 12:00:38 DEBUG     CAPTCHA ShareonlineBiz[1]: ReCaptcha | Challenge reCAPTCHA v2 interactive
``

If you need further information, plese let me know.

edit: My installtion is running on debian jessie.

**Comment by GammaC0de** [comment]
What OS/ Hardware are you running?

**Comment by faezzi** [comment]
It' s debian jessie on a PC with AMD 64bit cpu.

**Comment by GammaC0de** [comment]
what is the output of http://192.168.2.140:8000/info ?

**Comment by shoopdawoop** [comment]
Not meaning to interrupt but I am also no longer seeing captcha images with UploadedTo links.
I believe the only change on my system was an update to libsoup-gnome2.4-1 and libsoup2.4-1.

```
Python:2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]
OS:posix linux2 Linux bananapi 3.4.90 #2 SMP PREEMPT Tue Aug 5 14:11:40 CST 2014 armv7l
pyLoad version:0.4.9
```

**Comment by GammaC0de** [comment]
@shoopdawoop Have you read https://github.com/pyload/pyload/issues/3074?

**Comment by shoopdawoop** [comment]
Just saw it, guess I'll have to wait patiently... thanks!

**Comment by faezzi** [comment]
@GammaC0de 
it says:
`
Python:
    2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
Betriebssystem:
    posix linux2 Linux Ronja 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64
pyLoad Version:
    0.4.9
Installationsordner:
    /usr/share/pyload
Konfigurationsordner:
    /home/toni/.pyload
Downloadordner:
    /home/toni/Downloads/pyLoad
Freier Speicherplatz:
    290.80 GiB
Sprache:
    de
Webinterface Port:
    8000
Remote Interface Port:
    7227 `

**Comment by GammaC0de** [comment]
OK, so now check that `/usr/share/pyload/module/web/templates/pyplex/captcha.html` is the same as https://github.com/pyload/pyload/raw/stable/module/web/templates/pyplex/captcha.html
and  `/usr/share/pyload/module/web//media/js/pyplex/base.js` is the same as https://github.com/pyload/pyload/raw/stable/module/web/media/js/pyplex/base.js

**Comment by faezzi** [comment]
Well. A quick diff showed, they were not identical. Although I am pretty sure, I have overwritten everything in there. pyLoadCore.py for example is the same.

But even after overwriting captcha. html and base.js with those you mentioned, after deleting userplugins and deleting cache. The issue persists. :/

**Comment by GammaC0de** [comment]
These two were just samples to check, you have to verify that `/usr/share/pyload/module/*` is the same.
Also, delete the userplugins directory and then restart pyload after that.

**Comment by faezzi** [comment]
OK, I just redownloaded https://github.com/GammaC0de/pyload/archive/captcha-interactive.zip and have overwritten /usr/share/pyload/ with it. 

https://github.com/GammaC0de/pyload/raw/captcha-interactive/module/web/media/js/pyplex/base.js is _still_ different from /usr/share/pyload/module/web/media/js/pyplex/base.js

What am I doing wrong?

**Comment by GammaC0de** [comment]
This is probably because different EOL conversion.

Have you tested it now?

**Comment by faezzi** [comment]
```
drwxr-xr-x  2 root root  4096 Jul 11 11:02 docs
drwxr-xr-x  2 root root  4096 Jul 11 11:02 icons
-rw-r--r--  1 root root 32422 Jun 28 01:08 LICENSE
drwxr-xr-x 17 root root  4096 Jul 11 11:02 locale
drwxr-xr-x 12 root root  4096 Jul 11 11:02 module
drwxr-xr-x 12 root root  4096 Jul 11 09:11 module_neu
-rw-r--r--  1 root root  9106 Jun 28 01:08 pavement.py
-rwxr-xr-x  1 root root 19879 Jun 28 01:08 pyLoadCli.py
-rwxr-xr-x  1 root root 22964 Jun 28 01:08 pyLoadCore.py
-rwxr-xr-x  1 root root 28650 Jun 28 01:08 pyLoadGui.py
-rw-r--r--  1 root root  2545 Jun 28 01:08 README
drwxr-xr-x  2 root root  4096 Jul 11 11:02 scripts
-rw-r--r--  1 root root   117 Jun 28 01:08 setup.cfg
-rw-r--r--  1 root root  3878 Jun 28 01:08 systemCheck.py
-rw-r--r--  1 root root  1005 Jun 28 01:08 testlinks.txt
drwxr-xr-x  2 root root  4096 Jul 11 11:02 tests

```

But what I found is that I have two 'pypley' folders. I think PyPlex is the correct one and the other I made when trying to activate PyPlex, without knowing I had to install it.

```
toni@Ronja:/usr/share/pyload/module/web/media/js$ ls -la | grep lex
drwxr-xr-x 2 root root  4096 Jul 11 11:02 pyplex
drwxr-xr-x 2 root root  4096 Jun  6 09:14 PyPlex

```

But a diff here also shows no match. And it' s not just EOL:

```
---
> }
> 
19,20c58,59
<     b = $("#add_links").value();
<     g = new RegExp("(ht|f)tp(s?)://[a-zA-Z0-9-./?=_&%#]+[<| |\"|'|\r|\n|\t]{1}", "g");
---
>     b = $("#add_links").val();
>     g = new RegExp("(?:ht|f)tp(?:s?)://[a-zA-Z0-9-./?=_&%#:]+(?:[<| |\\\"|'|\\r|\\n|\\t]{1}|$)", "gi");
23c62
<         return;
---

```

**Comment by GammaC0de** [comment]
pyplex is the right one.
Delete PyPlex and switch to pyplex  and it should solve your problem.

**Comment by faezzi** [comment]
Well... At least, something is different now.

Currently I only have SSH access to the linux machine, can' t use the firefox there as the windows machine I' m on now does not allow to use X forwarding. I started pyload, switched to 'pyplex' and restarted pyload.

Now pyload told me to install tampermonkey and the script (didn' t have it here). Installed tampermonkey, imported the script and restarted firefox. But all I get now is:


```
The captcha may take a few seconds to load.

Note: to solve this interactive captchas
Please install the Tampermonkey add-on in your browser and add the pyload userscript.
```

Is uBlock Origin still needed? Just now as I am writing here II get a popup from pyload that there is a new captcha to solve, but still the message from above. :(

**Comment by GammaC0de** [comment]
See if you can see anything related on the web console (firefox's web developer menu) or the network tool

**Comment by GammaC0de** [comment]
I would have also delete everything under `/usr/share/pyload/` and `/home/toni/.pyload` and reinstall captcha-interactive.

**Comment by GammaC0de** [comment]
Any update on this?

**Comment by faezzi** [comment]
Yes, indeed there is :)

Today I have physical access to the machine and I just tested a minute ago. When using the correct pyplex I do get captchas to solve. I did not have to reinstall.

Captcha is shown and can be solved. Download is running.

Thank you for your patience and your great support! Go have a beer on me, you deserve it :)

**Comment by GammaC0de** [comment]
Thanks mate 🤗
