### ISSUE TITLE
fork #2 failed: 12 (Cannot allocate memory)

### ISSUE THREAD

**Issue by diman82** [pyload/pyload#3199]
When running on Entware (Asus rt-ac86u  -  armv8): 
pyload --daemon --configdir=/opt/var/pyload

I get the following error message:
fork #2 failed: 12 (Cannot allocate memory)

How to debug this issue?

**Comment by GammaC0de** [comment]
This is an Entware issue, not pyLoad issue.
Please ask them for help (https://github.com/Entware/Entware/issues), thanks.
