### ISSUE TITLE
little help please

### ISSUE THREAD

**Issue by 99filllip** [pyload/pyload#3200]
hi
i just downloaded and installed pyload (.deb file)
first i dont quite understand there were only few plugins (websites), so i downloaded them from pyload-plugins..
anyway, when i want to download s.th. from say soundcloud, i add the link, but all it does is downloading the site but no media...
what do i do wrong?

peace

**Comment by GammaC0de** [comment]
From where have you downloaded the .deb file?

Pyload should automatically update its plugins, no download is necessary.

**Comment by 99filllip** [comment]
from the github pyload download page.
i know the first time i ran the setup it updated a lot of plugins ... you know, from what i saw running throu the terminal, but when i checked /module/plugins/hoster it was only like a handful of sites.

anyway, in the meantime i also cloned the pyload code set it up and tried to run a debugger with pycharm (i'm new to programming, python, pycharm.., if someone can provide some guidance, that would be much appreciated..;))
i'm pretty sure the soundcloud plugin (i downloaded from the pyload-plugin ) is not working as it should.
but if i'm wrong pls let me know and how to fix.

peace

**Comment by 99filllip** [comment]
https://github.com/pyload/pyload/releases

that's where i got the deb pkg from..

**Comment by GammaC0de** [comment]
I have tested a soundcloud URL and it worked fine for me.

Please enable DEBUG mode, retry the download and then post the here.

**Comment by GammaC0de** [comment]
There are no tracks there.. https://soundcloud.com/beans-on-toast-official/tracks

**Comment by 99filllip** [comment]
sure there is... at least audio media to fetch..

**Comment by 99filllip** [comment]
not sayin a song u have to have. but there is media that pyload is supposed to recognize, fetch and provide, or am i wrong?

**Comment by 99filllip** [comment]
it is also just an example, it did not work with other links either

**Comment by 99filllip** [comment]
youtube,vimeo worked though

**Comment by GammaC0de** [comment]
>not sayin a song u have to have. but there is media that pyload is supposed to recognize, fetch and provide, or am i wrong?

I don't                                                                                                                                                                                                                                                                                                                                                                                                                                             understand what you are trying to say, there are no tracks, see attached screenshot:
![capture](https://user-images.githubusercontent.com/11036551/42598413-c4cb772e-8564-11e8-87fc-3d6de7a4343c.PNG)

**Comment by 99filllip** [comment]
![selection_001](https://user-images.githubusercontent.com/40335702/42598723-af38dba8-8565-11e8-9d45-99cfd2bb616d.png)

u see the url and the play button

**Comment by 99filllip** [comment]
do u have plugins running?

**Comment by GammaC0de** [comment]
I guess this URL is blocked from my region because I cannot see any tracks.

This is the URL I successfully tested: https://soundcloud.com/dj-jinx-paul/old-school-reggae-for-lovers

**Comment by 99filllip** [comment]
ok, i try your link now...

**Comment by 99filllip** [comment]
![selection_002](https://user-images.githubusercontent.com/40335702/42599127-f648239a-8566-11e8-9ee0-d5fa25fb83e7.png)
![selection_003](https://user-images.githubusercontent.com/40335702/42599133-f9f0ac10-8566-11e8-8008-1b55fddc7324.png)

**Comment by 99filllip** [comment]
looks like it worked ;)

**Comment by GammaC0de** [comment]
:+1: Closing.
