### ISSUE TITLE
Real debrid premium account / plugin fails

### ISSUE THREAD

**Issue by audren49** [pyload/pyload#3201]
`

19 | 12.07.2018 17:16:11 | INFO | ACCOUNT RealdebridCom: Adding user `aud*******`...
-- | -- | -- | --
20 | 12.07.2018 17:16:11 | INFO | ACCOUNT RealdebridCom: Login user `aud*******`...
21 | 12.07.2018 17:16:12 | ERROR | ACCOUNT RealdebridCom: Could not login user `aud*******` \| No api-token been found in response.
22 | 12.07.2018 17:16:14 | ERROR | ACCOUNT RealdebridCom: Could not load hoster list - invalid account, retry in 5 minutes
23 | 12.07.2018 17:17:06 | INFO | ACCOUNT RealdebridCom: Updating account info for user `aud*******`...
24 | 12.07.2018 17:17:06 | INFO | ACCOUNT RealdebridCom: Relogin user `aud*******`...
25 | 12.07.2018 17:17:07 | ERROR | ACCOUNT RealdebridCom: Could not login user `aud*******` \| No api-token been found in response.
26 | 12.07.2018 17:17:07 | INFO | ACCOUNT RealdebridCom: Updating account info for user `aud*******`...
27 | 12.07.2018 17:17:07 | INFO | ACCOUNT RealdebridCom: Relogin user `aud*******`...
28 | 12.07.2018 17:17:07 | ERROR | ACCOUNT RealdebridCom: Could not login user `aud*******` \| No api-token been found in response.
29 | 12.07.2018 17:17:10 | ERROR | ACCOUNT RealdebridCom: Could not load hoster list - invalid account, retry in 5 minutes

`

Hi, using either the token or the password on the current stable branch.
Cannot use real debrid account anymore.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by audren49** [comment]
Hi @GammaC0de thanks for the fix.

The account is now properly added. However, the download fails due to this error :

`

21 | 17.07.2018 14:12:33 | INFO | Added package Ready player one containing 1 links
-- | -- | -- | --
22 | 17.07.2018 14:12:34 | INFO | Download starts: https://1fichier.com/?6zjg7eq7dhlpm39v93zm
23 | 17.07.2018 14:12:34 | WARNING | HOSTER RealdebridCom[1]: RealdebridCom \| Plugin may be unstable
24 | 17.07.2018 14:12:34 | INFO | ACCOUNT RealdebridCom: Grabbing account info for user `aud*******`...
25 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Grabbing link info...
26 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link name: ?6zjg7eq7dhlpm39v93zm
27 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link size: N/D
28 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link status: starting
29 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Processing url: https://1fichier.com/?6zjg7eq7dhlpm39v93zm
30 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Looking for direct download link...
31 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Direct download link not found
32 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Checking for link errors...
33 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| No errors found
34 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Grabbing link info...
35 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link name: ?6zjg7eq7dhlpm39v93zm
36 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link size: N/D
37 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link status: starting
38 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Processing as premium download...
39 | 17.07.2018 14:12:35 | WARNING | Download failed: ?6zjg7eq7dhlpm39v93zm \| 'auth_token'
40 | 17.07.2018 14:12:35 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: ?6zjg7eq7dhlpm39v93zm (pid:1)
41 | 17.07.2018 14:12:35 | INFO | ADDON UnSkipOnFail: No duplicates found

`

This is the error :

WARNING | Download failed: ?6zjg7eq7dhlpm39v93zm \| **'auth_token'**
-- | --
