### ISSUE TITLE
[Account] ShareonlineBiz: Could not login | INVALID USER DATA

### ISSUE THREAD

**Issue by Arno-Nymous** [pyload/pyload#3203]
For two days now I'm getting the following error whenever adding or updating my Shareonline.biz account:

    13.07.2018 15:35:23 INFO      ACCOUNT ShareonlineBiz: Adding user `557*******`...
    13.07.2018 15:35:23 DEBUG     ACCOUNT ShareonlineBiz: Reached login timeout for user `557*******`
    13.07.2018 15:35:23 INFO      ACCOUNT ShareonlineBiz: Login user `557*******`...
    13.07.2018 15:35:23 DEBUG     ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': '557*******', 'password': '**********'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
    13.07.2018 15:35:23 ERROR     ACCOUNT ShareonlineBiz: Could not login user `557*******` | INVALID USER DATA

My account worked just perfectly before in pyload and I can login into my account just fine. So it's not a problem with the credentials. Several password changes in order to eliminate problems here didn't help. The account is listed as **_invalid_** in the interface. What's going on here? Any ideas?

I get this error on my Windows 7 machine (Python 2.7.15) as well as on my Linux running Debian 9 (Python 2.7.13). I can provide further info on request.

**Comment by Arno-Nymous** [comment]
It must have to do with the plugin. When I do the same request from my browser by typing it straight into the address bar I get back the correct account data. Whereas when pyload performs the same reuest with ma provided credentials, it fails. Typos are impossible in this case since I always copy the values from my password manager.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by Arno-Nymous** [comment]
I'm very sorry @GammaC0de but I won't take part in account sharing or such breach of security. There must be a another way to debug that. All I can tell you is the above error and that I can both log into my account via the shareonline.biz site and request my account data py pasting the exact get request from pyload into my browser address bar :confused:

**Comment by GammaC0de** [comment]
I am sorry, without an account I cannot test anything.
I have no choice but close this, If you manage to solve this by yourself you can issue a PR.  :confused:
