### ISSUE TITLE
captcha-interactive.zip , YouTube links not downloading

### ISSUE THREAD

**Issue by shoopdawoop** [pyload/pyload#3204]
I replaced my old install with <https://github.com/GammaC0de/pyload/archive/captcha-interactive.zip> as described in #3074 and now it won't grab videos from YouTube.

Is this a known issue?

The log shows this:

```
14.07.2018 10:11:08 INFO      Added package  containing 1 links
14.07.2018 10:11:10 INFO      Download starts: https://www.youtube.com/watch?v=okFxhVeW150
14.07.2018 10:11:10 WARNING   HOSTER YoutubeCom[1633] Plugin may be unstable
14.07.2018 10:11:10 INFO      HOSTER YoutubeCom[1633] Grabbing link info...
14.07.2018 10:11:10 INFO      HOSTER YoutubeCom[1633] Link name: watch?v=okFxhVeW150
14.07.2018 10:11:10 INFO      HOSTER YoutubeCom[1633] Link size: N/D
14.07.2018 10:11:10 INFO      HOSTER YoutubeCom[1633] Link status: starting
14.07.2018 10:11:10 INFO      HOSTER YoutubeCom[1633] Processing url: https://www.youtube.com/watch?v=okFxhVeW150
14.07.2018 10:11:11 ERROR     <<< UNCAUGHT EXCEPTION >>>
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/hoster/YoutubeCom.py", line 39, in write
    raise Exception("Loaded Url exceeded limit")
Exception: Loaded Url exceeded limit
14.07.2018 10:11:11 ERROR     pycurl error 23: Failed writing body (0 != 11338)
14.07.2018 10:11:11 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: watch?v=okFxhVeW150 (pid:565)
14.07.2018 10:11:11 INFO      ADDON UnSkipOnFail: No duplicates found
```

**Comment by adielp89** [comment]
the same thing happens to me, the only difference is that I have not replaced anything, as I downloaded it from the repository I was downloading the YouTube videos well and now they do not download me and I get the same error as you

`

538 | 14.07.2018 10:46:03 | INFO | Download starts: watch?v=8-3Xe7RMg3w
-- | -- | -- | --
539 | 14.07.2018 10:46:03 | WARNING | HOSTER YoutubeCom[115]: Plugin may be unstable
540 | 14.07.2018 10:46:03 | INFO | HOSTER YoutubeCom[115]: Grabbing link info...
541 | 14.07.2018 10:46:03 | INFO | HOSTER YoutubeCom[115]: Link name: watch?v=8-3Xe7RMg3w
542 | 14.07.2018 10:46:03 | INFO | HOSTER YoutubeCom[115]: Link size: N/D
543 | 14.07.2018 10:46:03 | INFO | HOSTER YoutubeCom[115]: Link status: comenzando
544 | 14.07.2018 10:46:03 | INFO | HOSTER YoutubeCom[115]: Processing url: https://www.youtube.com/watch?v=8-3Xe7RMg3w
545 | 14.07.2018 10:46:04 | ERROR | <<< UNCAUGHT EXCEPTION >>>
546 | ? | ? | Traceback (most recent call last):
547 | ? | ? | File "/root/.pyload/userplugins/hoster/YoutubeCom.py", line 39, in write
548 | ? | ? | raise Exception("Loaded Url exceeded limit")
549 | ? | ? | Exception: Loaded Url exceeded limit
550 | 14.07.2018 10:46:04 | ERROR | pycurl error 23: Failed writing body (0 != 15690)
551 | 14.07.2018 10:46:04 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: watch?v=8-3Xe7RMg3w (pid:22)
552 | 14.07.2018 10:46:04 | INFO | ADDON UnSkipOnFail: No duplicates found

`

**Comment by shoopdawoop** [comment]
Thanks for the quick fix. But I still get the same error after the update (I deleted /userplugins/*):

`INFO      ADDON UpdateManager: New version of plugin: HOSTER YoutubeCom (v0.67 -> v0.68)`

```
ERROR     <<< UNCAUGHT EXCEPTION >>>
Traceback (most recent call last):
  File "/usr/share/pyload/module/plugins/hoster/YoutubeCom.py", line 39, in write
    raise Exception("Loaded Url exceeded limit")
Exception: Loaded Url exceeded limit

```

So I manually set the limit even higher and now it works for me.

`    def __init__(self, cookies=None, options=None, limit=20000000):`

**Comment by GammaC0de** [comment]
25000000 is too much for low RAM systems like NASs.

Can you give the URL that was still failing?

**Comment by shoopdawoop** [comment]
It must have been this one: <https://youtube.com/watch?v=1tJZAc-A4kU>
