### ISSUE TITLE
No JS Engine despite having Node when downloading from ZippyShare

### ISSUE THREAD

**Issue by IshanArya** [pyload/pyload#3206]
I'm trying to run PyLoad on a linux server. However, whenever I try to download from Zippyshare, I get a "No JS Engine" found error. I already ran the JSEngine.py eval statement manually in the terminal and the result 42 returns.

Here is the error:
`16.07.2018 03:57:28 WARNING   CAPTCHA ZippyshareCom[31]: ReCaptcha | Key pattern not found
16.07.2018 03:57:28 WARNING   Download failed: file.part01.rar | No JS Engine`

Any idea why this may be? I read that I should try changing the PyLoad init file, but I can't find the init file anywhere.

**Comment by GammaC0de** [comment]
I don't think that Node is supported, what is the output of `systemCheck.py`?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by IshanArya** [comment]
Hi, sorry. Here's the output:

```
#####   System Information   #####

('Platform:', 'linux2')
('Operating System:', 'posix')
('Python:', '2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]\n')
('pycurl:', 'PycURL/7.43.0.2 libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3')
('py-crypto:', '2.6.1')
('OpenSSL:', '16.2.0')
('image library:', 'missing')
('pyqt:', 'missing')
('JS engine', 'missing')


#####   System Status   #####

##  pyLoadCore  ##
The system check has detected some errors:

Please install py-imaging/pil/pillow to use Hoster, which uses captchas.
Please install tesseract to use Hoster, which uses captchas.

##  pyLoadGui  ##
The system check has detected some errors:

GUI won't work without pyqt4 !!

##  Webinterface  ##
No Problems detected, Webinterface should work fine.

Possible improvements for webinterface:

Install Flup to use FastCGI or optional webservers.
Press Enter to Exit.
```

**Comment by GammaC0de** [comment]
Whay linux distribution are you using?

**Comment by GammaC0de** [comment]
Is `js` is in the PATH of pyLoad's daemon? (PATH is not the same for daemons and the user shell, you should modify pyLoad's init scrpit to add the additional path)

**Comment by IshanArya** [comment]
No, I don't think so. Where can I find the init script?

**Comment by GammaC0de** [comment]
First do `which js` to see the path of `js`.

I think you sould edit a file called `pyload.service` which I think should be inside `/etc/systemd/system`

**Comment by IshanArya** [comment]
There wasn't any `pyload.service` file, but I found `pyload.desktop` which had a Path option. After setting the Path to the folder with `node` the program still responded with the same error (`No JS Engine installed`).

Just to clarify, am I supposed to point the path to the folder with node or to the binary itself. Meaning `usr/bin` vs `usr/bin/node` ?

**Comment by GammaC0de** [comment]
1. What is the output of `which js` command?
2. How exactly do you start pyload? via the desktop shortcut?

**Comment by IshanArya** [comment]
Hi, sorry.

1. `which js` does not give an output. However, according to the JSEngine.py file, node should be a suitable alternative.
2. I start pyload with the command: `screen -dmS pyLoad pyLoadCore`. This is running on a headless machine, so I have to start it with the terminal.

**Comment by GammaC0de** [comment]
>1. `which js` does not give an output.

So how excatly pyload can run it if it is not in the PATH!?

> However, according to the JSEngine.py file, node should be a suitable alternative.

Where do you see that!?

**Comment by IshanArya** [comment]
I was looking at this: https://github.com/swayf/pyLoad/blob/master/module/common/JsEngine.py

But I'm guessing this is outdated now. My bad. So which jsengine should I use for a headless server?

**Comment by GammaC0de** [comment]
https://github.com/swayf/pyLoad/blob/master/module/common/JsEngine.py seems to have node support but the official one does not.
Try replacing JsEngine.py with https://github.com/swayf/pyLoad/raw/master/module/common/JsEngine.py and see what happens (of course you have to restart pyload after replacing the file)

**Comment by IshanArya** [comment]
No, I don't think the official pyload has a JSEngine.py at all.

**Comment by GammaC0de** [comment]
> No, I don't think the official pyload has a JSEngine.py at all.

Yes it does: https://github.com/pyload/pyload/blob/stable/module/common/JsEngine.py

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/79a9cac126883586f022db06344b1e8e3f5ac380

**Comment by IshanArya** [comment]
Oh wow. Thanks!
