### ISSUE TITLE
[Question] Permission denied to download a file to a network share

### ISSUE THREAD

**Issue by Youkier** [pyload/pyload#3207]
Hi,

I have installed Pyload and I am trying to download to a drive on my local network.

Downloads are working as long as I download on the machine pyload is running on.
But I have got an error "Free download failed | IOError 13" as soon as I try downloading on the drive on my network.

There should be no access issues, rights are open : drwxrwxrwx   8 4242 4242    0 juil. 16 23:16 freebox

Any idea of the issue ?

Thanks for your help,

**Comment by GammaC0de** [comment]
Is this share on a windows or linux machine?
SAMBA share or NFS?

**Comment by Youkier** [comment]
Hi,

thanks for your answer

My device with pyload is a raspberry on raspbian
The share device is my internet modem (freebox mini 4K). It is running on freebox OS and is sharing using DLNA. Some FTP set up is also possible.

Thanks for your help,

**Comment by GammaC0de** [comment]
How exactly do you use DLNA for file sharing!? 
Are you able to copy a file to the DLNA  share from the raspbian box?

**Comment by Youkier** [comment]
Sorry I made a mistake (I'm quite new on raspbian) : I am using FTP
And yes I am able to copy a file from my raspbian box to my FTP share

Here is a copy of the mount : 
//mafreebox.freebox.fr/Freebox on /media/freebox type cifs (rw,relatime,vers=1.0,cache=strict,username=freebox,domain=,uid=0,noforceuid,gid=0,noforcegid,addr=xxx.yy.zz.www,soft,unix,posixpaths,serverino,mapposix,acl,rsize=61440,wsize=65536,echo_interval=60,actimeo=1,_netdev)

**Comment by GammaC0de** [comment]
What user is used to run pyLoad?
Can you display pyLoad's init script?

**Comment by GammaC0de** [comment]
OK, so this proves that this a permissions issue.
I would check also the network share permissions, not just the directory permissions

**Comment by Youkier** [comment]
That s it I changed the user of the network share and it is working.
Thanks for your help !

By the way it takes quite a lot of time (5 minutes) once a download it done, to have the file ready (time to aggregate the chunks I guess). It was for a file of about 700MB.
Is it normal ? Is there some set up to speed it ?

thanks

**Comment by GammaC0de** [comment]
Considering this is a network drive, it is probably much slower then a local drive.

Solved so closing.
