### ISSUE TITLE
Real debrid download fails for premium

### ISSUE THREAD

**Issue by audren49** [pyload/pyload#3209]
After having setup a premium account, when trying to download a package, the auth seems to bug. I guess it is also due to the token. Just like in issue #3201 

`
21 | 17.07.2018 14:12:33 | INFO | Added package Ready player one containing 1 links
-- | -- | -- | --
22 | 17.07.2018 14:12:34 | INFO | Download starts: https://1fichier.com/?6zjg7eq7dhlpm39v93zm
23 | 17.07.2018 14:12:34 | WARNING | HOSTER RealdebridCom[1]: RealdebridCom \| Plugin may be unstable
24 | 17.07.2018 14:12:34 | INFO | ACCOUNT RealdebridCom: Grabbing account info for user aud*******...
25 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Grabbing link info...
26 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link name: ?6zjg7eq7dhlpm39v93zm
27 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link size: N/D
28 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link status: starting
29 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Processing url: https://1fichier.com/?6zjg7eq7dhlpm39v93zm
30 | 17.07.2018 14:12:34 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Looking for direct download link...
31 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Direct download link not found
32 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Checking for link errors...
33 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| No errors found
34 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Grabbing link info...
35 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link name: ?6zjg7eq7dhlpm39v93zm
36 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link size: N/D
37 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link status: starting
38 | 17.07.2018 14:12:35 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Processing as premium download...
39 | 17.07.2018 14:12:35 | WARNING | Download failed: ?6zjg7eq7dhlpm39v93zm \| 'auth_token'
40 | 17.07.2018 14:12:35 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: ?6zjg7eq7dhlpm39v93zm (pid:1)
41 | 17.07.2018 14:12:35 | INFO | ADDON UnSkipOnFail: No duplicates found

`

Error is WARNING | Download failed: ?6zjg7eq7dhlpm39v93zm \| 'auth_token'

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by audren49** [comment]
Just tested.
Everything works correctly as far as I can see.

Good job, and thank you

**Comment by GammaC0de** [comment]
@Hetoft Password for Real-debrid should be the API token - get it from: https://real-debrid.com/apitoken

**Comment by Hetoft** [comment]
@GammaC0de Thanks for the fast reply. 

Yes, that is how it USED to be. That (apparently?) got changed a month or two ago. Found out when it wasn't able to log me in anymore. So now I'm using my password - which worked perfectly fine until now. 

If I'm using the API token as password, pyLoad can't log me in and displays "Status: Not valid" and "Premium: no". So apparently this behaviour (going from API token to normal password) happened a while ago.

**Comment by GammaC0de** [comment]
DO NOT use your password.
When using user and password you'll some times get a Captcha request , that's why the old method was brought back.

**Comment by audren49** [comment]
Hi,

It was fixed for me. It now works like a charm.


Le ven. 27 juil. 2018 à 12:14, GammaC0de <notifications@github.com> a
écrit :

**Comment by audren49** [comment]
And I confirm that with a premium account you need to use the token as the
password.

Le ven. 27 juil. 2018 à 12:34, Audren de Valbray <a.devalbray@gmail.com> a
écrit :

**Comment by Hetoft** [comment]
@audren49 Thanks for confirming.

@GammaC0de My bad - didn't quite understand that you went back to the old method. Perhaps I should've read the thread properly before I commented... :) Anyway, manually updated to the current RealDebrid files (in Hosters and Accounts), and everything is working nice and smoothly now. Thank you so much for developing and maintaining this great application!

**Comment by audren49** [comment]
Hi,

plugin seems to be broken again.
I've updated to latest stable branch.
Premium account is being accepted correctly : status = valid, premium = yes. Date valid until is also the right one.

But download fails: 

Here is some log:
`19.02.2019 18:22:49 INFO      Added package XXXXXXXXXX containing 1 links
19.02.2019 18:22:49 INFO      Download starts: hXXXXXXXXXXX3
19.02.2019 18:22:49 WARNING   HOSTER RealdebridCom[1]: RealdebridCom | Plugin may be unstable
19.02.2019 18:22:49 INFO      ACCOUNT RealdebridCom: Grabbing account info for user `aud*******`...
19.02.2019 18:22:50 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Grabbing link info...
19.02.2019 18:22:50 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link name: ?y4XXXXXX2123
19.02.2019 18:22:50 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link size: N/D
19.02.2019 18:22:50 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link status: starting
19.02.2019 18:22:50 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Processing url: https://1fXXXXXXXXXXX
19.02.2019 18:22:50 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Looking for direct download link...
19.02.2019 18:22:51 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Direct download link not found
19.02.2019 18:22:51 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Checking for link errors...
19.02.2019 18:22:51 INFO      HOSTER RealdebridCom[1]: RealdebridCom | No errors found
19.02.2019 18:22:51 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Grabbing link info...
19.02.2019 18:22:51 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link name: ?y4byXXXXXXXX3
19.02.2019 18:22:51 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link size: N/D
19.02.2019 18:22:51 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link status: starting
19.02.2019 18:22:51 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Processing as premium download...
19.02.2019 18:22:51 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Downloading file...
19.02.2019 18:22:51 WARNING   HOSTER RealdebridCom[1]: RealdebridCom | Premium download failed | downloading
19.02.2019 18:22:52 INFO      Download restarted: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXACOOL.WwW.mkv | Revert to original hoster plugin
19.02.2019 18:22:52 INFO      Download starts: XXXXXXXXXXXXXXXXXXXXXXXX
19.02.2019 18:22:52 WARNING   HOSTER OneFichierCom[1]: Plugin may be unstable
19.02.2019 18:22:52 INFO      HOSTER OneFichierCom[1]: Grabbing link info...
19.02.2019 18:22:53 INFO      HOSTER OneFichierCom[1]: Link name: ?y4byfx94xxaw9avnwx1c&af=22123
19.02.2019 18:22:53 INFO      HOSTER OneFichierCom[1]: Link size: 2.71 GiB (2906419928 bytes)
19.02.2019 18:22:53 INFO      HOSTER OneFichierCom[1]: Link status: starting
`

Thanks

**Comment by GammaC0de** [comment]
Could you check again please?
Maybe it was a momentary issue with RealdebridCom?

**Comment by audren49** [comment]
Unfortunately it is still not working. :(

**Comment by GammaC0de** [comment]
OK, so please open a new issue.

**Comment by audren49** [comment]
Hi,

It was my bad entirely, hard drive has in read only for some reason.
False alarm, sorry about that.

Thank you
