### ISSUE TITLE
SSL certificate check fails in pyLoad Android app | What's the correct format?

### ISSUE THREAD

**Issue by Arno-Nymous** [pyload/pyload#3210]
Are there certain points I have to consider when enabling SSL on the thrift backend to make it work correctly with my snake-oil certificate? I have a full PKI set up for my network where I have one root CA, multiple intermediate CAs and lastly several derived server and client certificates. I have deployed my root certificate to my devices and created a private/public key pair and certificate for pyLoad.

Now, when I deliver the pyLoad server certificate solely to my clients it's not trusted since it's missing the intermediate link between it and the root cert. When I chain all the certs together into one big certificate chain (e.g. like I would do for Apache), the Android client either complains that it couldn't verify the certificate (when it's listed first in the chain) or there's no certificate recognized at all (when it's listed last in the chain).

Can anyone tell me whether it's possible to provide pyLoad a full certificate chain for verification and if so which format does it have to have?

**Comment by Velociraptor85** [comment]
Hej arno I dont have experience with SSL&pyload but maybe you try checking out closed tickets in regards to that "SSL" topic ... 

1. also I am not sure how well maintained the android app is and would like to know If you tested it on a PC?
2. alternativly I thought maybe you could create a apache reverse proxy as far as I remember there are people doing just that
3. also I guess you tested pem file/text with "priv"/"pub"+"intermpub"+"capub", If i read that correctly

**Comment by Arno-Nymous** [comment]
@Velociraptor85 Thanks for your reply. For the time being I just disabled the verification of certificates. I know I could as well use some wrapper service like stunnel which I utilize for other applications that don't support TLS at all but I thought it would be much cleaner if I could just use the features the app already includes. Well, for now it works but I'll see if i can work it out.

**Comment by GammaC0de** [comment]
Fixed.
