### ISSUE TITLE
With threaded webserver ClickNLoad puts packages always to Collector

### ISSUE THREAD

**Issue by oltodosel** [pyload/pyload#3211]
Despite the setting being set to add to Queue, it ignores it and adds packages to Collector

**Comment by GammaC0de** [comment]
How have you installed pyload?
are you using the latest stable branch?
On what OS pyload runs?

**Comment by oltodosel** [comment]
Installed via AUR https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pyload

Python: | 2.7.15 (default, Jun 27 2018, 13:05:28) [GCC 8.1.1 20180531]
OS: | posix linux2 Linux lom 4.17.8-1-ARCH #1 SMP PREEMPT Wed Jul 18 09:56:24 UTC 2018 x86_64
pyLoad version: | 0.4.9

**Comment by GammaC0de** [comment]
This version seems to be very old.
Please grab https://github.com/pyload/pyload/archive/stable.zip and copy to `${pkgdir}/opt/pyload` overwriting the old files

**Comment by oltodosel** [comment]
Sorry, I was mistaken.
I actually have the stable branch installed - https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pyload-git, which takes https://github.com/pyload/pyload.git#branch=stable

**Comment by oltodosel** [comment]
It seem to have started working.
