### ISSUE TITLE
Python Web Interface on macOS Safari Can't Add Downloads

### ISSUE THREAD

**Issue by marianadangelo** [pyload/pyload#3212]
Hi, apologies if this issue has already come up, I tried searching the issues, but didn't spot anything. I'm pretty new to submitting issues so let me know if there's any other useful information I can cobble together.

I just set up a pyload install on my raspberry pi with the pyplex web interface template and I noticed that the web interface does not appear to (fully) work on desktop Safari. While the downloads can be browsed and configuration settings changed (e.g., adding accounts), downloads cannot be added. 

Reproduce: 
(1) open WebUI in Safari on desktop
(2) try to add any link
(3) check logs - no messages related to the added link appear and the link is not added

Conclusion that it was a problem with desktop safari drawn from:
(1) download links could be added via CLI
(2) download links could be added using Firefox 
(3) download links could be added using Safari on iOS

Safari: Version 11.1.2 (13605.3.8)
Operating System: macOS High Sierra 10.13.6 (17G65)

**Comment by GammaC0de** [comment]
How did you installed pyload? you should grab the latest stable branch..

**Comment by marianadangelo** [comment]
I’m on latest stable
