### ISSUE TITLE
dl protect domain change

### ISSUE THREAD

**Issue by Floflobel** [pyload/pyload#3213]
Hi,

The plugin dl-protect not working. I think it's because of the domain name that has to change ?

**Comment by GammaC0de** [comment]
Sample URL please

**Comment by Floflobel** [comment]
https://www.dl-protect1.com/41535349060065065544953483548570613648460650x0z524756360k0x595858520f

**Comment by GammaC0de** [comment]
@Floflobel Do you have a password protected URL?

**Comment by Floflobel** [comment]
@GammaC0de no, just the captcha on the website
