### ISSUE TITLE
reCaptcha not working with captcha9KW and Filer.net

### ISSUE THREAD

**Issue by Taraman17** [pyload/pyload#3214]
When I try to get captchas solved automatically with 9KW for Filer.net Downloads, the Download does not process.

The Log shows:
DEBUG CAPTCHA FilerNet[133]: ReCaptcha | Key: 6LdB1kcUAAAAAAVPepnD-6TEd4BXKzS7L4FZFkpO
DEBUG CAPTCHA FilerNet[133]: ReCaptcha | Detected reCAPTCHA v2
WARNING CAPTCHA FilerNet[133]: ReCaptcha | Secure Token pattern not found
DEBUG HOSTER FilerNet[133]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6LdB1kcUAAAAAAVPepnD-6TEd4BXKzS7L4FZFkpO | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=https://filer.net/get/vfwtn9xxri0dot8q | just_header=False
WARNING HOSTER FilerNet[133]: Free download failed | reCAPTCHA challenge message not found

Thereafter, I get this message on every download, even if I am connected to solve manually.
When I pause till the next day, I can download again - manually.

Are there any more Infos I can post to help?

**Comment by Taraman17** [comment]
OK, I found the first error - my APIkey somehow was stored wrong - I'm so a noob not to check that before...
Now I get the following output:
INFO      HOSTER FilerNet[86]: Processing as free download...
DEBUG     HOSTER FilerNet[86]: LOAD URL https://filer.net/get/ceb0dbkbzzwsm8ub | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'token': u'b928e4b579657c1b2277869d7764dd3db039faf0e65c2507440535a54f0f318a'} | ref=True | just_header=False
DEBUG     CAPTCHA FilerNet[86]: ReCaptcha | Key: 6LdB1kcUAAAAAAVPepnD-6TEd4BXKzS7L4FZFkpO
DEBUG     CAPTCHA FilerNet[86]: ReCaptcha | Detected reCAPTCHA v2
WARNING   CAPTCHA FilerNet[86]: ReCaptcha | Secure Token pattern not found
DEBUG     HOSTER FilerNet[86]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6LdB1kcUAAAAAAVPepnD-6TEd4BXKzS7L4FZFkpO | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=https://filer.net/get/ceb0dbkbzzwsm8ub | just_header=False
DEBUG     HOSTER FilerNet[86]: LOAD URL http://www.google.com/recaptcha/api2/payload?c=03AEMEkEn_m6EIr_6RHvYI5rkEwG9GVV-UGjNVJnqpz6T2KtFvXhul8rJZ5DX5fa9E4AD3YMKkQ1KTbLa-tBXEL9e3SWtp6tq6R2jMVRzWd_MsHbsPqsJ6WI_hizeSFVIhB5l-I8P2-KqqrDgBBrPXhGQZWtqP8RGZdoyVd_9rO0i6PgrLwhRVcmCSMjj82ybh62TiPaqTEqnrwzaO2dcNPRN7UTNkebtzi6FKRvCybmMpc4jyJkszS9lBp2kQq_z3p_WOI7qSvAAS5Qx7mrK4P8lJcokp-SarzSmAwU4wwKtzOo5EOhBMUtLTRmp1he_l_GVqhvVyGxwzLri7xtxaY_ngbaLzxGP56A&k=6LdB1kcUAAAAAAVPepnD-6TEd4BXKzS7L4FZFkpO | redirect=True | cookies=True | get={} | req=None | decode=False | multipart=False | post={} | ref=http://www.google.com/recaptcha/api/fallback?k=6LdB1kcUAAAAAAVPepnD-6TEd4BXKzS7L4FZFkpO | just_header=False
DEBUG     ADDON Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | redirect=True | cookies=True | get={'action': 'usercaptchaguthaben', 'source': 'pyload', 'apikey': u'XXXX', 'pyload': '1'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
INFO      ADDON Captcha9Kw: 1169 credits left
DEBUG     ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
DEBUG     ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
DEBUG     ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
DEBUG     ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
DEBUG     ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
WARNING   CAPTCHA FilerNet[86]: ReCaptcha | No Client connected for captcha decrypting
WARNING   HOSTER FilerNet[86]: Free download failed | No Client connected for captcha decrypting

**Comment by GammaC0de** [comment]
Sometimes the ReCaptcha solving takes very long (google keeps bugging with new pictures).
So it seems to timeout, it can be because:
No client on the 9kw site was available to solve the captcha.
There was a timeout while the user was solving the captcha (9kw timeout)
Captcha 9kw gave out while waiting for an answer..


Your log does not include timestamp, how much time passed since the first `LOAD URL http://www.9kw.eu/grafik/servercheck.txt` line until `No Client connected for captcha decrypting` ?

**Comment by Taraman17** [comment]
Sorry, left these out so the lines get shorter.
It always takes exactly 50 secs.

**Comment by 3mb3dw0rk5** [comment]
I also have the problem that after 50 seconds the 9kw captcha solving is somehow canceled.
Here my log:

`

579 | 05.08.2018 19:02:55 | INFO | Download starts: coincidence-split-1080p (1).mkv.part01.rar
-- | -- | -- | --
580 | 05.08.2018 19:02:55 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
581 | 05.08.2018 19:02:55 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
582 | 05.08.2018 19:02:55 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
583 | 05.08.2018 19:02:55 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
584 | 05.08.2018 19:02:55 | DEBUG | HOSTER ShareonlineBiz[4]: Plugin version: 0.67
585 | 05.08.2018 19:02:55 | DEBUG | HOSTER ShareonlineBiz[4]: Plugin status: testing
586 | 05.08.2018 19:02:55 | WARNING | HOSTER ShareonlineBiz[4]: Plugin may be unstable
587 | 05.08.2018 19:02:55 | INFO | HOSTER ShareonlineBiz[4]: Grabbing link info...
588 | 05.08.2018 19:02:55 | DEBUG | HOSTER ShareonlineBiz[4]: Link info: {'status': 2, 'hash': {}, 'name': 'coincidence-split-1080p.mkv.part01.rar', 'url': u'http://www.share-online.biz/dl/F1AMJUPO9Y', 'pattern': {'ID': u'F1AMJUPO9Y'}, 'size': 1049624000, 'md5': '27c5e896aa26d4f88db67761edbf2728', 'fileid': 'F1AMJUPO9Y'}
589 | 05.08.2018 19:02:55 | DEBUG | HOSTER ShareonlineBiz[4]: Previous link info: {'status': 2, 'hash': {}, 'name': 'coincidence-split-1080p.mkv.part01.rar', 'url': u'http://www.share-online.biz/dl/F1AMJUPO9Y', 'pattern': {'ID': u'F1AMJUPO9Y'}, 'fileid': 'F1AMJUPO9Y', 'md5': '27c5e896aa26d4f88db67761edbf2728', 'size': 1049624000}
590 | 05.08.2018 19:02:55 | INFO | HOSTER ShareonlineBiz[4]: Link name: coincidence-split-1080p.mkv.part01.rar
591 | 05.08.2018 19:02:55 | INFO | HOSTER ShareonlineBiz[4]: Link size: 1001.00 MiB (1049624000 bytes)
592 | 05.08.2018 19:02:55 | INFO | HOSTER ShareonlineBiz[4]: Link status: online
593 | 05.08.2018 19:02:55 | INFO | HOSTER ShareonlineBiz[4]: Processing url: http://www.share-online.biz/dl/F1AMJUPO9Y
594 | 05.08.2018 19:02:55 | INFO | HOSTER ShareonlineBiz[4]: Looking for direct download link...
595 | 05.08.2018 19:02:55 | DEBUG | HOSTER ShareonlineBiz[4]: LOAD URL http://www.share-online.biz/dl/F1AMJUPO9Y \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
596 | 05.08.2018 19:02:55 | INFO | HOSTER ShareonlineBiz[4]: Direct download link not found
597 | 05.08.2018 19:02:55 | DEBUG | HOSTER ShareonlineBiz[4]: LOAD URL http://www.share-online.biz/dl/F1AMJUPO9Y \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
598 | 05.08.2018 19:02:55 | INFO | HOSTER ShareonlineBiz[4]: Processing as free download...
599 | 05.08.2018 19:02:55 | DEBUG | HOSTER ShareonlineBiz[4]: WAIT set to timestamp 1533495779.955072 \| Previous waitUntil: 1533495775.266358
600 | 05.08.2018 19:02:55 | INFO | HOSTER ShareonlineBiz[4]: Waiting 3 seconds...
601 | 05.08.2018 19:02:59 | DEBUG | HOSTER ShareonlineBiz[4]: LOAD URL http://www.share-online.biz/dl/F1AMJUPO9Y/free/ \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={'dl_free': '1', 'choice': 'free'} \| ref=True \| just_header=False
602 | 05.08.2018 19:03:00 | DEBUG | CAPTCHA ShareonlineBiz[4]: ReCaptcha \| Key: 6LdnPkIUAAAAABqC_ITR9-LTJKSdyR_Etj1Sf-Xi
603 | 05.08.2018 19:03:00 | DEBUG | CAPTCHA ShareonlineBiz[4]: ReCaptcha \| Detected reCAPTCHA v2
604 | 05.08.2018 19:03:00 | WARNING | CAPTCHA ShareonlineBiz[4]: ReCaptcha \| Secure Token pattern not found
605 | 05.08.2018 19:03:00 | DEBUG | HOSTER ShareonlineBiz[4]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6LdnPkIUAAAAABqC_ITR9-LTJKSdyR_Etj1Sf-Xi \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=http://www.share-online.biz/dl/F1AMJUPO9Y \| just_header=False
606 | 05.08.2018 19:03:00 | WARNING | CAPTCHA ShareonlineBiz[4]: ReCaptcha \| reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
607 | 05.08.2018 19:03:00 | DEBUG | CAPTCHA ShareonlineBiz[4]: ReCaptcha \| Challenge reCAPTCHA v2 interactive
608 | 05.08.2018 19:03:00 | DEBUG | ADDON Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi \| redirect=True \| cookies=True \| get={'action': 'usercaptchaguthaben', 'source': 'pyload', 'apikey': u'3SPT3X9J2PRCMGA68G', 'pyload': '1'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
609 | 05.08.2018 19:03:00 | INFO | ADDON Captcha9Kw: 40341 credits left
610 | 05.08.2018 19:03:00 | DEBUG | ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
611 | 05.08.2018 19:03:10 | DEBUG | ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
612 | 05.08.2018 19:03:20 | DEBUG | ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
613 | 05.08.2018 19:03:31 | DEBUG | ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
614 | 05.08.2018 19:03:41 | DEBUG | ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
615 | 05.08.2018 19:03:51 | WARNING | CAPTCHA ShareonlineBiz[4]: ReCaptcha \| No Client connected for captcha decrypting
616 | 05.08.2018 19:03:51 | WARNING | HOSTER ShareonlineBiz[4]: Free download failed \| No Client connected for captcha decrypting
617 | 05.08.2018 19:03:51 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
618 | 05.08.2018 19:03:51 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
619 | 05.08.2018 19:03:51 | DEBUG | ADDON ExternalScripts: No script found under folder `package_failed`
620 | 05.08.2018 19:03:51 | WARNING | Download failed: coincidence-split-1080p (1).mkv.part01.rar \| No Client connected for captcha decrypting
621 | 05.08.2018 19:03:51 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: coincidence-split-1080p (1).mkv.part01.rar (pid:3)
622 | 05.08.2018 19:03:51 | INFO | ADDON UnSkipOnFail: No duplicates found
623 | 05.08.2018 19:03:51 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
624 | 05.08.2018 19:03:51 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
625 | 05.08.2018 19:03:51 | DEBUG | All downloads processed

`

**Comment by GammaC0de** [comment]
It seems like the 9kw server is overloaded.
Increase the `Max. Queue` parameter
