### ISSUE TITLE
Can not downlad anything - CRITICAL : NoneType' object has no attribute 'BasePlugin'

### ISSUE THREAD

**Issue by jasek5** [pyload/pyload#3217]
Hello.
I am unable to download any file .
It always shows error NoneType' object has no attribute 'BasePlugin'
Could you please tell what i did wrong ?

If you need additional information please tell me .
thank you.

**log -->**

12.08.2018 14:09:53 INFO      Starting pyLoad 0.4.9
12.08.2018 14:09:53 INFO      Using home directory: /home/pi/.pyload
12.08.2018 14:09:55 ERROR     Error importing EventMapper: No module named Addon
12.08.2018 14:09:55 ERROR     Error importing ExternalScripts: No module named Addon
12.08.2018 14:09:55 ERROR     Error importing ClickNLoad: No module named Addon
12.08.2018 14:09:55 ERROR     Error importing ExtractArchive: No module named Addon
12.08.2018 14:09:55 ERROR     Error importing UnSkipOnFail: No module named Addon
12.08.2018 14:09:55 ERROR     Error importing XFileSharing: No module named Addon
12.08.2018 14:09:55 ERROR     Error importing UpdateManager: No module named Addon
12.08.2018 14:09:55 ERROR     Error importing UserAgentSwitcher: No module named Addon
12.08.2018 14:09:55 INFO      Activated plugins: CaptchaTrader, ClickAndLoad
12.08.2018 14:09:55 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, Ca$
12.08.2018 14:09:55 INFO      Downloadtime: True
12.08.2018 14:09:56 INFO      Starting builtin webserver: 0.0.0.0:8000
12.08.2018 14:09:56 INFO      Free space: 458.53 GiB
12.08.2018 14:09:56 INFO      Activating Accounts...
12.08.2018 14:09:56 INFO      Activating Plugins...
12.08.2018 14:09:56 INFO      pyLoad is up and running
12.08.2018 14:10:52 ERROR     Error importing BasePlugin: No module named Hoster
12.08.2018 14:10:52 INFO      Added package google containing 1 links
12.08.2018 14:10:52 ERROR     Error importing BasePlugin: No module named Hoster
12.08.2018 14:10:52 CRITICAL  'NoneType' object has no attribute 'BasePlugin'
12.08.2018 14:11:21 ERROR     Error importing BasePlugin: No module named Hoster
12.08.2018 14:11:21 INFO      Added package ig containing 1 links
12.08.2018 14:11:22 ERROR     Error importing BasePlugin: No module named Hoster
12.08.2018 14:11:22 INFO      Added package ig containing 1 links
12.08.2018 14:11:53 INFO      shutting down...

**Comment by Velociraptor85** [comment]
* How did you setup your pyload? Did you follow this setup guide by @GammaC0de ? https://github.com/pyload/pyload/wiki/Installation
* Also are you sure that the permissions are set correctly?

for me this seems like a setup/update problem

**Comment by GammaC0de** [comment]
@jasek5 The link seems to be back again https://gist.githubusercontent.com/GammaC0de/a77279b6588c11aed9c9/raw/830cb0161b416a5328e32516067608cd2cfdd031/UpdateManager.py

It seems like there was a temporary issue on github.

Use the instructions in https://github.com/pyload/pyload/wiki/Installation

**Comment by jasek5** [comment]
thank you now it works.
:)
