### ISSUE TITLE
Permissions after extracting

### ISSUE THREAD

**Issue by Nutellaeis** [pyload/pyload#3219]
Is it possible to define the permissions an extracted file should have? I want it to be 660 but pyload always seems to make in 644. Even turning of permission settings completely would be fine. I use ACL and have a default mask set but pyload seems to ignore that

**Comment by Velociraptor85** [comment]
So for me the set permissions are correctly set it should be changeable in
Settings -> General -> Permissions

**Comment by Nutellaeis** [comment]
Settings -> General -> Permissions only seems to set permissions for downloaded files. My problem are the permissions on extracted files. They still default to 644.

**Comment by GammaC0de** [comment]
@Nutellaeis Are you using 7-zip?

**Comment by Nutellaeis** [comment]
The setup is as following:

- Ubuntu Server 18.04
- Pyload running in a docker container (https://hub.docker.com/r/writl/pyload/) as an unprivileged user.
- All "Change group of..." options are disabled.
- The container only contains "unrar" and no 7zip

**Comment by GammaC0de** [comment]
`Change file mode of downloads` should be enabled.

**Comment by Nutellaeis** [comment]
That works. And on the way I learned that unrar really always seems to set its own permissions and ignores default masks. Fascinating....   Thanks a lot!

**Comment by GammaC0de** [comment]
👍

**Comment by Mister-XY** [comment]
Ah cool, it's run.
