### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Imparium** [pyload/pyload#3222]
Hello. 
I am installing pyLoad on my Raspberry Pi following [this](https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi)) tutorial.
However, when I get to the part: `sudo -u pyload python pyLoadCore.py`, I get `Segmentation fault`. Yes, I just get that and the process die.
What may be happening? Thank you so much.

**Comment by GammaC0de** [comment]
Probably a permissions issue.
You have to enable write access to the directory where pyLoadCore.py resides.

**Comment by GammaC0de** [comment]
No response, closing.
