### ISSUE TITLE
[Feature Request] RealdebridCom Torrent Support

### ISSUE THREAD

**Issue by CodingMask** [pyload/pyload#3223]
Requesting the following enhancement to the RealdebridCom multihoster plugin
- Ability to send torrent files or magnet links to RealdebridCom

Secondary request:
- Hook similar to HotFolder to use as a RealdebridCom Blackhole, which would periodically search for torrent files or magnet link files in a prescribed folder, then send them to RealdebridCom
- Hook would then periodically check status of the downloads at RealdebridCom and then add them to the download queue if ready

See [here](https://github.com/Corey-Evans/real-debrid-blackhole) for a similar project

I feebly attempted to create a hook to get this to work, but thus far have been unable to understand how to correctly call the multihoster plugin RealdebridCom from a hook to get the correct api_token and make the additional api_response calls.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by CodingMask** [comment]
Thanks for the quick response.  If you're going to go to the trouble of coding this, I can just purchase you an account.  Would 30 days suffice?

**Comment by GammaC0de** [comment]
I think so, you know, real life comes first..

**Comment by CodingMask** [comment]
OK, sent you a note.  Thanks

**Comment by GammaC0de** [comment]
You will submit a URL to a torrent file or magnet, 
Is that OK?

**Comment by CodingMask** [comment]
Ideally, either an URL or POST a local torrent/magnet file to the service.  I think the API allows for either:
https://api.real-debrid.com/

The goal would be to use the hook similar to HotFolder, as a blackhole folder for other programs like Sonarr or Sickbeard

**Comment by GammaC0de** [comment]
Done,  please check.

Now you can add a magnet/torrent URL or upload a torrent file.

You use the same HotFolder plugin to submit magnet/torrent via a hot folder

**Comment by GammaC0de** [comment]
Well, does it work?

**Comment by GammaC0de** [comment]
@CodingMask Have you tried it?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by CodingMask** [comment]
Apologies for the delayed response (I was out of country).  I tried the new version / plugin.  The response in the debug log when activating the plugin in settings is:
```
DEBUG | Plugin RealdebridComTorrent not found
```

Clearly the addon is present though.  Is there some additional setup required?

**Comment by GammaC0de** [comment]
>Is there some additional setup required

No,
The only configuration option for this plugin is if you want to keep torrents on the server.

Please stop pyload and the start it from the console with the command `pyLoadCore.py -d` and the try to download a torrent.
After that, please post the log from the console (all of it please).

**Comment by CodingMask** [comment]
OK, I finally got it to work.   For documentation, I did have to setup the hotfolder plugin before I activated the realdebridtorrent addon.  For whatever reason, it would give the same error if hotfolder was activated after realdebridtorrent.  Works like a charm!

**Comment by dansleboby** [comment]
It will be nice to add a file mask, exemple I only want the file with X extensions

**Comment by GammaC0de** [comment]
@dansleboby Do you example torrent?

**Comment by dansleboby** [comment]
@GammaC0de any torrent will work

**Comment by ChzeRub** [comment]
You should also check for cached files in a torrent by calling /torrents/instantAvailability/hash . 
I "hacked" something together so that only the cached files are selected for download (if there are any cached files).

RealdebridComTorrent.py

` #: Select all the files for downloading
        file_ids = ",".join([str(_f['id']) for _f in torrent_info['files']])
        hash =  torrent_info['hash']

        file_info = self.api_response("/torrents/instantAvailability/" + hash,
                                         get={'auth_token': self.api_token})
        
        if 'error' in file_info:
            self.fail("%s (code: %s)" % (file_info["error"], file_info.get("error_code", -1)))

        if file_info[hash] != []:
            file_ids =  ",".join([str(_f) for _f in file_info[hash]['rd'][0]])

        self.api_response("/torrents/selectFiles/" + torrent_id,
                          get={'auth_token': self.api_token},
                          post={'files': file_ids})

        return torrent_id
`

**Comment by ChzeRub** [comment]
You should also check for cached files in a torrent by calling /torrents/instantAvailability/hash . 
I "hacked" something together so that only the cached files are selected for download (if there are any).

RealdebridComTorrent.py

```
        #: Select all the files for downloading
        file_ids = ",".join([str(_f['id']) for _f in torrent_info['files']])
        hash =  torrent_info['hash']

        file_info = self.api_response("/torrents/instantAvailability/" + hash,
                                         get={'auth_token': self.api_token})
        
        if 'error' in file_info:
            self.fail("%s (code: %s)" % (file_info["error"], file_info.get("error_code", -1)))
        
        #: Select cached files for downloading
         if file_info[hash]['rd'] != []:
                file_ids =  ",".join([str(_f) for _f in file_info[hash]['rd'][0]])

        self.api_response("/torrents/selectFiles/" + torrent_id,
                          get={'auth_token': self.api_token},
                          post={'files': file_ids})

        return torrent_id
```

**Comment by GammaC0de** [comment]
@ChzeRub From my experience , 
If a torrent is instantly available , it will be finished instantly, so the is no benefit with calling `/torrents/instantAvailability`,
correct me if I'm wrong.

**Comment by GammaC0de** [comment]
@dansleboby Added file masking to RealdebridComTorrent https://github.com/pyload/pyload/commit/a4a5204ca467a6e9b6f31023e901bae01bdd0f56

@ChzeRub I have read more about `/torrents/instantAvailability` and according to the documentation is states that to get instant downloading, you have to select **all** the file ids to you receive from `/torrents/instantAvailability`  and now with file masking, this is out of the question.
