### ISSUE TITLE
FilerNet "argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by Taraman17** [pyload/pyload#3225]
FilerNet free downloads regularly fail with the above message.

Logfile Shows:
`06.09.2018 16:41:18 DEBUG     HOSTER FilerNet[107]: Plugin version: 0.27
06.09.2018 16:41:18 DEBUG     HOSTER FilerNet[107]: Plugin status: testing
06.09.2018 16:41:18 WARNING   HOSTER FilerNet[107]: Plugin may be unstable
06.09.2018 16:41:18 INFO      HOSTER FilerNet[107]: Grabbing link info...
06.09.2018 16:41:18 DEBUG     HOSTER FilerNet[107]: Link info: {'status': 7, 'hash': {}, 'name': 'sy5fpeqmtdffh4lm', 'url': u'https://filer.net/get/sy5fpeqmtdffh4lm', 'pattern': {}, 'size': 0}
06.09.2018 16:41:18 DEBUG     HOSTER FilerNet[107]: Previous link info: {}
06.09.2018 16:41:18 INFO      HOSTER FilerNet[107]: Link name: sy5fpeqmtdffh4lm
06.09.2018 16:41:18 INFO      HOSTER FilerNet[107]: Link size: 500.00 MiB (524288000 bytes)
06.09.2018 16:41:18 INFO      HOSTER FilerNet[107]: Link status: starte
06.09.2018 16:41:18 INFO      HOSTER FilerNet[107]: Processing url: https://filer.net/get/sy5fpeqmtdffh4lm
06.09.2018 16:41:18 INFO      HOSTER FilerNet[107]: Looking for direct download link...
06.09.2018 16:41:18 DEBUG     HOSTER FilerNet[107]: LOAD URL https://filer.net/get/sy5fpeqmtdffh4lm | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
06.09.2018 16:41:19 INFO      HOSTER FilerNet[107]: Direct download link not found
06.09.2018 16:41:19 DEBUG     HOSTER FilerNet[107]: LOAD URL https://filer.net/get/sy5fpeqmtdffh4lm | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
06.09.2018 16:41:19 INFO      HOSTER FilerNet[107]: Checking for link errors...
06.09.2018 16:41:19 DEBUG     HOSTER FilerNet[107]: WAIT set to timestamp 1536248477.506296 | Previous waitUntil: 0.000000
06.09.2018 16:41:19 INFO      HOSTER FilerNet[107]: Waiting 59 minutes, 57 seconds...
06.09.2018 17:41:18 INFO      HOSTER FilerNet[107]: No errors found
06.09.2018 17:41:18 INFO      HOSTER FilerNet[107]: Grabbing link info...
06.09.2018 17:41:18 DEBUG     HOSTER FilerNet[107]: Link info: {'status': 7, 'hash': {}, 'name': 'sy5fpeqmtdffh4lm', 'url': u'https://filer.net/get/sy5fpeqmtdffh4lm', 'pattern': {}, 'size': 0}
06.09.2018 17:41:18 DEBUG     HOSTER FilerNet[107]: Previous link info: {'status': 7, 'hash': {}, 'name': 'sy5fpeqmtdffh4lm', 'url': u'https://filer.net/get/sy5fpeqmtdffh4lm', 'pattern': {}, 'size': 0}
06.09.2018 17:41:18 INFO      HOSTER FilerNet[107]: Link name: sy5fpeqmtdffh4lm
06.09.2018 17:41:18 INFO      HOSTER FilerNet[107]: Link size: 500.00 MiB (524288000 bytes)
06.09.2018 17:41:18 INFO      HOSTER FilerNet[107]: Link status: starte
06.09.2018 17:41:18 INFO      HOSTER FilerNet[107]: Processing as free download...
06.09.2018 17:41:18 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
06.09.2018 17:41:18 WARNING   Download failed: sy5fpeqmtdffh4lm | argument of type 'NoneType' is not iterable
06.09.2018 17:41:18 INFO      Debug Report written to debug_FilerNet_06-09-2018_17-41-18.zip
06.09.2018 17:41:18 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed``

Debug Report attached.
[debug_FilerNet_31-07-2018_12-34-56.zip](https://github.com/pyload/pyload/files/2357768/debug_FilerNet_31-07-2018_12-34-56.zip)

**Comment by Taraman17** [comment]
And looking at the download-patterns, it seems that every second download fails.

**Comment by GammaC0de** [comment]
Yes, what you have said seems to confirm my suspicion that does not detect properly when it have to wait before starting a new download.

How much time passes until another successful download?

**Comment by Taraman17** [comment]
I have to look at this in detail.
Since it is always the second download it must be between 1x "standard wait time" + a second and 2x "standard wait time"

**Comment by GammaC0de** [comment]
@Taraman17 Please confirm this is fixed.

**Comment by Taraman17** [comment]
Yes, works fine.

THX a lot!

**Comment by GammaC0de** [comment]
:+1:
