### ISSUE TITLE
RapidgatorNet problems

### ISSUE THREAD

**Issue by zn4jp3** [pyload/pyload#3226]
Hi! First of all im new to this so be gentle =)
Im having problems with my rapidgator account in pyload, when i add my account it says "Status Valid" and "Premium Yes" Then after a litle while it says that its not valid anymore and when i check the log it says "
WARNING | HOSTER RapidgatorNet[258]: Plugin may be unstable" Im runing pyload on my Nas Asustor AS3202T. Is there a way to update the Rapidgator plugin?

**Comment by zn4jp3** [comment]
And another thing, might not be pyload related but the dl speed is realy slow, i had uploaded account before and got realy high speed

**Comment by bradau** [comment]
This too is a problem for myself! 

Initially, the adding of a premium account is fine with. As described above "Status Valid = Yes" and "Premium = Yes" 

After trying to commence a download it falls back to "Premium = No" however the status remains Valid. I am running this on a Linux VPS and have replicated the behaviour on my own environment using Ubuntu 18.04  and the latest codebase.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
By the way, "HOSTER xxxx]: Plugin may be unstable" is a standard message for all hosters, it just says that the plugin **MAY** be unstable.

**Comment by zn4jp3** [comment]
Account info to what?

**Comment by bradau** [comment]
I have issues with both k2c.cc and rapidgator . One thing I will mention before I provide account details, is that my login (e-mail address) is using a newer TLD domain which is ".club" 

Could it be that the auth process / handshake fails when using a newer TLD domain name as a login?

**Comment by GammaC0de** [comment]
pyLoad does not care what you put in the user login.

**Comment by GammaC0de** [comment]
@zn4jp3 for RapidgatorNet .

**Comment by GammaC0de** [comment]
No response, closing.
