### ISSUE TITLE
linksnappy : 403 forbidden

### ISSUE THREAD

**Issue by diman82** [pyload/pyload#3227]
I get 403 forbidden http error when I try to download using Linksnappy plugin (Premium account has been successfully added). 
What could be the problem?

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user , password and sample URL to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Well?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by diman82** [comment]
Sorry for the delay.
U: 36321303
P: Testpassword1!

Sample url: http://dlserv29.linksnappy.com/files/7iZ9Q36yr4qyvLWn74/SutS810aagnPrnr00pMNELDP1H24Tb2GB.rar

**Comment by GammaC0de** [comment]
For security concerns, you should not post passwords here,
My instructions were to send by mail.

**Comment by diman82** [comment]
@GammaC0de Sorry about that, but it's a temp password anyway, and I'm the only one who has access to email (2-factor authentication).

**Comment by diman82** [comment]
No banned IP, as I successfully download from my PC (same AP), the problem is faced on an embedded device - Entware firmware.
Maybe the reason is an old Pyload version (that is distributed through opkg)?

**Comment by GammaC0de** [comment]
You'd better pull the latest `stable` branch:
Go to `http://<PYLOAD_IP>/info` and see write down the `Installation Folder` and `Config Folder`.
Stop pyLoad and then overwrite everything with the download and after you are done, I recommend you to switch to the `pyplex` web interface.

**Comment by diman82** [comment]
Thanks for the recommendation.
How do I switch to pyplex web interface?

**Comment by GammaC0de** [comment]
Do you know how to run the configuration wizard (`pyLoadCore.pt -s`)?

**Comment by diman82** [comment]
Yes, I got the idea.
If possible, please leave the issue open for several days until I download latest and reconfigure.

**Comment by GammaC0de** [comment]
After you overwrite the `Installation Folder` with the download, run `pyLoadCore.py -s` ant it will ask you what webinterface you like.

**Comment by GammaC0de** [comment]
Hello, any news?

**Comment by diman82** [comment]
@GammaC0de Sorry, short on time. I'll have a look in the upcoming days.

**Comment by GammaC0de** [comment]
???

**Comment by GammaC0de** [comment]
When you have time please report, meanwhile this is closed.

**Comment by diman82** [comment]
@GammaC0de fetched latest stable version, overwrite *.py files, seems to be working now (slow download, but working..).
BTW - what is the benefit of switching to _pyplex_ web interface? And will it work well, as the builtin web-server? And if I run a config above the current setup, will it preserve all the settings, and change **only** the web-server?

**Comment by Velociraptor85** [comment]
@diman82 I am running pyplex with threaded server config and it works good the configured settings should not change since its just the visualization

**Comment by diman82** [comment]
@GammaC0de Who is in charge of dev of this plugin? Who can I ask regd. chunked downloads? Because it downloads at speed of 50kb/s, in average..

**Comment by GammaC0de** [comment]
> Who is in charge of dev of this plugin
Basically I am in charge

Please set back the temporary password and I will have a look.
