### ISSUE TITLE
BasePlugin didn't work properly - Download finished with error

### ISSUE THREAD

**Issue by diegoweb** [pyload/pyload#3228]
Hey!

I have tried to download a Google Drive link and everything works fine.
But when I try to download via Direct Link (so, pyLoad uses BasePlugin), I get an error and the file is not downloaded as it should be (it goes to 100%, but then it fails):

![image](https://user-images.githubusercontent.com/12632119/45458443-12ceec80-b6ca-11e8-9dfb-6608d136fda9.png)

This is the log with debug on:
`

1 | 12.09.2018 23:24:19 | INFO | restarting pyLoad
-- | -- | -- | --
2 | 12.09.2018 23:24:19 | INFO | shutting down...
3 | 12.09.2018 23:24:19 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_restart`
4 | 12.09.2018 23:24:19 | DEBUG | Deleting old pidfile pyload.pid
5 | 12.09.2018 23:24:21 | INFO | Starting pyLoad 0.4.9
6 | 12.09.2018 23:24:21 | INFO | Using home directory: /opt/pyload/pyload-config
7 | 12.09.2018 23:24:21 | DEBUG | Remote activated: False
8 | 12.09.2018 23:24:22 | DEBUG | created index of plugins
9 | 12.09.2018 23:24:22 | INFO | Activated plugins: Captcha9Kw, EventMapper, ExternalScripts, UpdateManager, UserAgentSwitcher, XFileSharing
10 | 12.09.2018 23:24:22 | INFO | Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, CaptchaBrotherhood, Checksum, ClickNLoad, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, UnSkipOnFail, WindowsPhoneNotify, XMPP
11 | 12.09.2018 23:24:22 | INFO | Downloadtime: True
12 | 12.09.2018 23:24:22 | INFO | Starting builtin webserver: 0.0.0.0:8000
13 | 12.09.2018 23:24:22 | INFO | Free space: 53.75 GiB
14 | 12.09.2018 23:24:22 | INFO | Activating Accounts...
15 | 12.09.2018 23:24:22 | INFO | Activating Plugins...
16 | 12.09.2018 23:24:22 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_start`
17 | 12.09.2018 23:24:23 | INFO | ADDON XFileSharing: Auto-discover new hosters
18 | 12.09.2018 23:24:23 | DEBUG | ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com\|clicknupload\.org\|cramit\.in\|easybytez\.com\|exashare\.com\|filejoker\.net\|fileom\.com\|filerio\.com\|fistfast\.net\|hugefiles\.net\|junocloud\.me\|movreel\.com\|nosupload\.com\|novafile\.com\|rapidfileshare\.net\|rarefile\.net\|safesharing\.eu\|secureupload\.eu\|streamcloud\.eu\|tusfiles\.net\|uploadrocket\.net\|vidplay\.net))(?P(?:[\d.]+\|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W\|$)
19 | 12.09.2018 23:24:23 | INFO | ADDON XFileSharing: Auto-discover new crypters
20 | 12.09.2018 23:24:23 | DEBUG | ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com\|tusfiles\.net))(?P(?:[\d.]+\|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user\|folder)s?/\w+
21 | 12.09.2018 23:24:23 | DEBUG | ADDON UpdateManager: LOAD URL https://github.com/pyload/updates/raw/master/plugins.txt \| redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
22 | 12.09.2018 23:24:23 | INFO | pyLoad is up and running
23 | 12.09.2018 23:24:26 | INFO | ADDON UpdateManager: pyLoad is up to date!
24 | 12.09.2018 23:24:26 | DEBUG | ADDON UpdateManager: LOAD URL https://github.com/pyload/updates/raw/master/plugins.txt \| redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
25 | 12.09.2018 23:24:26 | DEBUG | ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'FreeWayMe'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
26 | 12.09.2018 23:24:26 | INFO | ADDON UpdateManager: All plugins are up to date!
27 | 12.09.2018 23:24:29 | INFO | Download starts: 100MB.zip
28 | 12.09.2018 23:24:29 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
29 | 12.09.2018 23:24:29 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
30 | 12.09.2018 23:24:29 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
31 | 12.09.2018 23:24:29 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
32 | 12.09.2018 23:24:29 | DEBUG | HOSTER BasePlugin[1]: Plugin version: 0.52
33 | 12.09.2018 23:24:29 | DEBUG | HOSTER BasePlugin[1]: Plugin status: testing
34 | 12.09.2018 23:24:29 | WARNING | HOSTER BasePlugin[1]: Plugin may be unstable
35 | 12.09.2018 23:24:29 | DEBUG | HOSTER BasePlugin[1]: Config option `use_premium` not found, use default `True`
36 | 12.09.2018 23:24:29 | INFO | HOSTER BasePlugin[1]: Grabbing link info...
37 | 12.09.2018 23:24:29 | DEBUG | HOSTER BasePlugin[1]: Link info: {'status': 7, 'hash': {}, 'name': '100MB.zip', 'url': u'http://speedtest.tele2.net/100MB.zip', 'pattern': {}, 'size': 0}
38 | 12.09.2018 23:24:29 | DEBUG | HOSTER BasePlugin[1]: Previous link info: {}
39 | 12.09.2018 23:24:29 | INFO | HOSTER BasePlugin[1]: Link name: 100MB.zip
40 | 12.09.2018 23:24:29 | INFO | HOSTER BasePlugin[1]: Link size: 100.00 MiB (104857600 bytes)
41 | 12.09.2018 23:24:29 | INFO | HOSTER BasePlugin[1]: Link status: starting
42 | 12.09.2018 23:24:29 | INFO | HOSTER BasePlugin[1]: Processing url: http://speedtest.tele2.net/100MB.zip
43 | 12.09.2018 23:24:29 | DEBUG | HOSTER BasePlugin[1]: DOWNLOAD URL http://speedtest.tele2.net/100MB.zip \| fixurl=True \| resume=None \| get={} \| cookies=True \| disposition=True \| chunks=None \| post={} \| ref=False
44 | 12.09.2018 23:24:29 | DEBUG | Chunked with range 13107201-26214402
45 | 12.09.2018 23:24:29 | DEBUG | Chunked with range 26214402-39321603
46 | 12.09.2018 23:24:29 | DEBUG | Chunked with range 39321603-52428804
47 | 12.09.2018 23:24:29 | DEBUG | Chunked with range 52428804-65536005
48 | 12.09.2018 23:24:29 | DEBUG | Chunked with range 65536005-78643206
49 | 12.09.2018 23:24:29 | DEBUG | Chunked with range 78643206-91750407
50 | 12.09.2018 23:24:29 | DEBUG | Chunked with range 91750407-
51 | 12.09.2018 23:25:42 | INFO | HOSTER BasePlugin[1]: File saved
52 | 12.09.2018 23:25:42 | INFO | HOSTER BasePlugin[1]: Checking download...
53 | 12.09.2018 23:25:43 | INFO | HOSTER BasePlugin[1]: Path deleted: /opt/pyload/Downloads/Speedtest/100MB.zip
54 | 12.09.2018 23:25:43 | WARNING | HOSTER BasePlugin[1]: Free download failed \| Parse error: Empty file \| Plugin may be out of date
55 | 12.09.2018 23:25:43 | DEBUG | HOSTER BasePlugin[1]: Config option `fallback` not found, use default `True`
56 | 12.09.2018 23:25:43 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
57 | 12.09.2018 23:25:43 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
58 | 12.09.2018 23:25:43 | WARNING | Download failed: 100MB.zip \| Parse error: Empty file \| Plugin may be out of date
59 | 12.09.2018 23:25:43 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
60 | 12.09.2018 23:25:43 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
61 | 12.09.2018 23:25:43 | DEBUG | All downloads processed

`

This is my pyLoad info:

> Python:2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
OS:posix linux2 Linux 73173a342663 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7lpyLoad version:0.4.9
Installation Folder:/opt/pyload
Config Folder:/opt/pyload/pyload-config
Download Folder:/opt/pyload/Downloads
Free Space:53.75 GiB
Language:en
Webinterface Theme:PyPlex by Marco Fernandes improved by Dogan Bagci and GammaC0de
Webinterface Port:8000
Remote Interface Port:7227

By the way, I'm running pyLoad over Docker (RPi3) this time. But I had this exact same problem when I was running with OSMC OS (non-docker).

**Comment by GammaC0de** [comment]
This server is very unstable, it fails to finish the download even with Firefox.
