### ISSUE TITLE
Captcha not loading - UploadedTo Plugin

### ISSUE THREAD

**Issue by diegoweb** [pyload/pyload#3229]
I haven't tested with other file hosting yet, but with UploadedTo I'm having issues to see the recaptcha. By the way, 9kw.eu is configured with my API key and enabled. I don't know which 9kw.eu plugin I should turn on, so I just switched both to enable.

![image](https://user-images.githubusercontent.com/12632119/45458902-4b6fc580-b6cc-11e8-9369-4b1717bd0623.png)

My log:
`

1 | 12.09.2018 20:37:04 | INFO | restarting pyLoad
-- | -- | -- | --
2 | 12.09.2018 20:37:04 | INFO | shutting down...
3 | 12.09.2018 20:37:04 | INFO | ADDON ClickNLoad: Shutting down proxy...
4 | 12.09.2018 20:37:06 | INFO | Starting pyLoad 0.4.9
5 | 12.09.2018 20:37:06 | INFO | Using home directory: /opt/pyload/pyload-config
6 | 12.09.2018 20:37:07 | INFO | Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
7 | 12.09.2018 20:37:07 | INFO | Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
8 | 12.09.2018 20:37:07 | INFO | Downloadtime: True
9 | 12.09.2018 20:37:07 | INFO | Starting ThriftBackend: 0.0.0.0:7227
10 | 12.09.2018 20:37:08 | INFO | Starting builtin webserver: 0.0.0.0:8000
11 | 12.09.2018 20:37:08 | INFO | Free space: 53.75 GiB
12 | 12.09.2018 20:37:08 | INFO | Activating Accounts...
13 | 12.09.2018 20:37:08 | INFO | Activating Plugins...
14 | 12.09.2018 20:37:08 | INFO | ADDON XFileSharing: Auto-discover new hosters
15 | 12.09.2018 20:37:08 | INFO | ADDON XFileSharing: Auto-discover new crypters
16 | 12.09.2018 20:37:08 | INFO | pyLoad is up and running
17 | 12.09.2018 20:37:11 | INFO | ADDON UpdateManager: pyLoad is up to date!
18 | 12.09.2018 20:37:11 | INFO | ADDON UpdateManager: All plugins are up to date!
19 | 12.09.2018 20:37:14 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
20 | 12.09.2018 20:41:14 | INFO | Added package Avatar containing 1 links
21 | 12.09.2018 20:41:14 | INFO | Decrypting starts: http://uploaded.net/f/q4ym6n
22 | 12.09.2018 20:41:14 | WARNING | CRYPTER UploadedToFolder[1]: Plugin may be unstable
23 | 12.09.2018 20:41:14 | INFO | CRYPTER UploadedToFolder[1]: Grabbing link info...
24 | 12.09.2018 20:41:15 | INFO | CRYPTER UploadedToFolder[1]: Link name: AVT21
25 | 12.09.2018 20:41:15 | INFO | CRYPTER UploadedToFolder[1]: Link size: N/D
26 | 12.09.2018 20:41:15 | INFO | CRYPTER UploadedToFolder[1]: Link status: online
27 | 12.09.2018 20:41:15 | INFO | CRYPTER UploadedToFolder[1]: Processing url: http://uploaded.net/f/q4ym6n
28 | 12.09.2018 20:41:15 | INFO | CRYPTER UploadedToFolder[1]: Looking for direct link...
29 | 12.09.2018 20:41:16 | INFO | CRYPTER UploadedToFolder[1]: Direct link not found
30 | 12.09.2018 20:41:16 | INFO | CRYPTER UploadedToFolder[1]: Checking for link errors...
31 | 12.09.2018 20:41:16 | INFO | CRYPTER UploadedToFolder[1]: No errors found
32 | 12.09.2018 20:41:16 | INFO | CRYPTER UploadedToFolder[1]: Decrypting as free link...
33 | 12.09.2018 20:41:16 | INFO | CRYPTER UploadedToFolder[1]: Create package: AVT21 \| 12 links
34 | 12.09.2018 20:41:16 | INFO | Added package AVT21 containing 12 links
35 | 12.09.2018 20:41:16 | INFO | CRYPTER UploadedToFolder[1]: Save package `AVT21` to folder: AVT21
36 | 12.09.2018 20:41:16 | INFO | Download starts: http://uploaded.net/file/hk5xcp62/from/q4ym6n
37 | 12.09.2018 20:41:16 | WARNING | HOSTER UploadedTo[2]: Plugin may be unstable
38 | 12.09.2018 20:41:16 | INFO | HOSTER UploadedTo[2]: Grabbing link info...
39 | 12.09.2018 20:41:17 | INFO | HOSTER UploadedTo[2]: Link name: AVT21D.part01.rar
40 | 12.09.2018 20:41:17 | INFO | HOSTER UploadedTo[2]: Link size: 4.88 GiB (5242880000 bytes)
41 | 12.09.2018 20:41:17 | INFO | HOSTER UploadedTo[2]: Link status: online
42 | 12.09.2018 20:41:17 | INFO | HOSTER UploadedTo[2]: Processing url: http://uploaded.net/file/hk5xcp62/from/q4ym6n
43 | 12.09.2018 20:41:17 | INFO | HOSTER UploadedTo[2]: Looking for direct download link...
44 | 12.09.2018 20:41:18 | INFO | HOSTER UploadedTo[2]: Direct download link not found
45 | 12.09.2018 20:41:18 | INFO | HOSTER UploadedTo[2]: Checking for link errors...
46 | 12.09.2018 20:41:18 | INFO | HOSTER UploadedTo[2]: No errors found
47 | 12.09.2018 20:41:18 | INFO | HOSTER UploadedTo[2]: Processing as free download...
48 | 12.09.2018 20:41:19 | WARNING | CAPTCHA UploadedTo[2]: ReCaptcha \| Could not properly detect ReCaptcha version, defaulting to v1
49 | 12.09.2018 20:41:20 | INFO | CAPTCHA UploadedTo[2]: ReCaptcha \| Using OCR to decrypt captcha...
50 | 12.09.2018 20:41:20 | WARNING | CAPTCHA UploadedTo[2]: ReCaptcha \| No OCR result

`

**Comment by GammaC0de** [comment]
@diegoweb See https://github.com/pyload/pyload/issues/3074#issuecomment-390926441

**Comment by diegoweb** [comment]
@GammaC0de since you're from pyLoad team, can you make this changes directly into the pyLoad repo? So I would just build my docker image again in order to download the new changes.

By the way, why isn't this change already in the pyLoad Stable branch?
Since your #3074 comment is from May 22.

Thank you!

**Comment by GammaC0de** [comment]
@diegoweb This is to be released as v0.4.10
