### ISSUE TITLE
DLC corrupted

### ISSUE THREAD

**Issue by Keridos** [pyload/pyload#3230]
filecrypt.cc and JDownloader 2 created DLC are not being able to be imported on pyload 0.4.9 with up to date plugins.
Probably need to switch to a different decryption service? http://dcrypt.it/ maybe?

**Comment by GammaC0de** [comment]
DLC from https://filecrypt.cc/Container/E00CA3BBCE.html tested and works fine for me..

**Comment by Keridos** [comment]
Hm, maybe my docker image still runs older plugins?

**Comment by GammaC0de** [comment]
I don't know,
docker images can be out of sync..

**Comment by Keridos** [comment]
Well it is the latest release version. Though "latest" means 2013

**Comment by GammaC0de** [comment]
I don't know, 
The docker package was built by 3rd party, it is not maintained by us..

You  must be in sync with the latest "stable" git branch.

"latest" is 4 month ago (see  https://hub.docker.com/r/writl/pyload/builds/), it should work with DLC.
`docker pull writl/pyload:latest`
