### ISSUE TITLE
1fichier.com TLS handshake

### ISSUE THREAD

**Issue by t09** [pyload/pyload#3231]
Hi,

I got premium account and download ist not woking for me.
Log:
`

336 | 13.09.2018 17:55:02 | DEBUG | pycurl exception 35: gnutls_handshake() failed: A TLS packet with unexpected length was received.
-- | -- | -- | --
337 | 13.09.2018 17:55:02 | ERROR | pycurl error 35: gnutls_handshake() failed: A TLS packet with unexpected length was received.
338 | 13.09.2018 17:55:02 | INFO | Debug Report written to debug_OneFichierCom_13-09-2018_17-55-02.zip

`
Debug log:
[debug_OneFichierCom_13-09-2018_17-55-08.zip](https://github.com/pyload/pyload/files/2380107/debug_OneFichierCom_13-09-2018_17-55-08.zip)

Thanks a lot

**Comment by GammaC0de** [comment]
@t09 What OS are you using?

**Comment by t09** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by lukastribus** [comment]
As per your trace, `1fichier.com` seems to work fine, but `a-12.1fichier.com` (I assume the actual download server) does not.

And in fact [a-12.1fichier.com requires ECDHE ciphers](https://www.ssllabs.com/ssltest/analyze.html?d=a%2d12.1fichier.com), while [1fichier.com does not](https://www.ssllabs.com/ssltest/analyze.html?d=1fichier.com).

But in Ubuntu 14.04 the dependancy chain is `python-pycurl` -> `libcurl3-gnutls` -> `libgnutls26`, which lacks ECDHE, supported only in `libgnutls268`.

In Ubuntu 14.04, this is as easily reproduced as:
```
$ sudo apt-get install python-pycurl
$ python

import pycurl

c = pycurl.Curl()
c.setopt(c.URL, 'https://a-12.1fichier.com/')
c.perform()
c.close()
```

which returns:
```
>>> c.perform()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pycurl.error: (35, 'gnutls_handshake() failed: A TLS packet with unexpected length was received.')

```


Either you ask 1fichier to enable non-ECDHE ciphers on their download servers (just like they already do on their main site), or you upgrade your Ubuntu installation. Any supported Ubuntu release that is newer than 14.04 will do just fine. Ubuntu 14.04 will be end-of-support in a few months and the packages in the repositories are just too old at this point, not even SNI is supported with this python-pycurl/gnutls26 combination.

**Comment by t09** [comment]
OK thanks got it :+1:

**Comment by GammaC0de** [comment]
Also red here: https://wfuzz.readthedocs.io/en/latest/user/installation.html#pycurl-ssl-bug
