### ISSUE TITLE
Where can I change the default queue setting on start?

### ISSUE THREAD

**Issue by chr0max** [pyload/pyload#3233]
Hi,

sorry if this is the wrong forum for my question. But I´m searching the setting to change the default behaviour when starting pyload. It´s always starting and thats fine, but for now I want it paused.

Thanks for any information.

**Comment by GammaC0de** [comment]
You can try using the `DownloadScheduler` plugin or write your own hook plugin that calls `self.pyload.api.pauseServer()` at startup.

**Comment by Velociraptor85** [comment]
@chr0max I am not sure what exectly you want do you think that you could explain it with some other words? do you mean that the downloads are starting if you start pyload or that pyload start when you start your box?

**Comment by GammaC0de** [comment]
> I just want that I start the pyloadCore.py, it starts till its ready and does nothing, till I hit the start button manually

And why would you want something like that?

You could add the URLs to the "collector" instead to the queue and when you are ready move them to the queue.

**Comment by chr0max** [comment]
Because I have a tight connection and don´t want always go into the webui/app and manually stop it everytime the raspberry is restarted.

So the solution is: Manually move downloads always between queue and collector.

**Comment by GammaC0de** [comment]
:+1: Closing.
