### ISSUE TITLE
/info not protected by authentication

### ISSUE THREAD

**Issue by DaPutzy** [pyload/pyload#3235]
All urls are protected by authentication, but `/info` is not. There are some internal settings visible that IMHO should not be visible to unauthenticated users!

EDIT: version 0.4.9 btw.

**Comment by GammaC0de** [comment]
Fixed `/info`, thanks for reporting.
>There are some internal settings visible that IMHO should not be visible to unauthenticated users!

You mean inside `/info`, correct?

**Comment by DaPutzy** [comment]
yes 👍

**Comment by DaPutzy** [comment]
Can confirm. I have built a new docker image and `/info` is no longer unprotected, thanks 👍

**Comment by GammaC0de** [comment]
:+1:
