### ISSUE TITLE
UlozTo plugin not working

### ISSUE THREAD

**Issue by urys** [pyload/pyload#3237]
premium account - download only web page source
withou premium - repeatledly wants to enter captcha

this issue started after August 15th

I'am using *stable
root@pyload_buster:~/pyload# git branch
  master
* stable

root@pyload_buster:~/pyload# git pull
Already up to date.

[pyload_free_ulozto.txt](https://github.com/pyload/pyload/files/2425562/pyload_free_ulozto.txt)
[pyload_premium_ulozto.txt](https://github.com/pyload/pyload/files/2425563/pyload_premium_ulozto.txt)

[downloadedwithpremium.zip](https://github.com/pyload/pyload/files/2425569/downloadedwithpremium.zip)

**Comment by GammaC0de** [comment]
Tested with free download and it worked fine.

If you want me to test with premium account, account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by urys** [comment]
Account info sent. Thanks

**Comment by urys** [comment]
thanks, now works well
