### ISSUE TITLE
Add new web-ui to stable branch?

### ISSUE THREAD

**Issue by fooness** [pyload/pyload#3240]
Are there any plans on adding the new web-ui which can be seen on pyload.net to the stable branch?

**Comment by GammaC0de** [comment]
@fooness We have a dark web-ui thait it is already in the stable branch, it is called `pyplex`.
There is a plan to make a bright web-ui.
You have also https://github.com/OzzieIsaacs/pyload-NextTheme which looks similar to what you asked.

**Comment by fooness** [comment]
Thank you, @GammaC0de. I’ve read about `pyplex` and `next` in issues from 2017 so I thought there’s maybe some news … is `next` as advanced and stable as the `classic` theme that comes with 0.4.9 (or the stable branch)?

`There is a plan to make a bright web-ui.`

Very looking forward to this. And I think I’m not the only one.

**Comment by GammaC0de** [comment]
> I’ve read about pyplex and next in issues from 2017

What do you mean, what issues?

**Comment by fooness** [comment]
> What do you mean, what issues?

Pardon, that was maybe a bit confusing … I wanted to say, I was reading through some `Issues` from the `pyload` repository ([#2710](https://github.com/pyload/pyload/issues/2710), [#2989](https://github.com/pyload/pyload/issues/2989), and [#2997](https://github.com/pyload/pyload/issues/2997)) but they all seem a rather dated.

> The most complete and maintained is `pyplex` which is included in the `stable` branch.

I’ve tried `pyplex` and I agree, it looks very advanced. I just wish there would be a bright/neutral color scheme like the `0.4.9` classic theme or like that screenshot shown on `pyload.net` shown below …

<img width="1665" alt="sample" src="https://user-images.githubusercontent.com/11408027/46592630-f9507300-cac4-11e8-9e8a-09ab4d223de9.png">

… That just looks perfect to me.

**Comment by fooness** [comment]
Thank you, @GammaC0de, for explaining how things went!

> The bright version is just a matter of spare time and priorities, although I believe it just a matter of changing colors so I estimate it would not take long to port.

You’re probably right, so maybe at some point someone finds the time and motivation to do this.

**Comment by xunil75** [comment]
Hi everyone, I'm creating a lighter version of the Theme. This is a preview for now:

![image](https://user-images.githubusercontent.com/32961904/47223579-e473b980-d3b9-11e8-9049-85cf2a326e74.png)

**Comment by GammaC0de** [comment]
@fooness Enjoy: https://github.com/pyload/pyload/commit/1731ccd7aa4250c8b1b17252a0b28b78bb9628f7
