### ISSUE TITLE
restarting pyload failed

### ISSUE THREAD

**Issue by Web-Eye** [pyload/pyload#3247]
Hello maybe more a qestion than a issue:

I recently changed my pyload startup method to systed service on Ubuntu 18.1 LTS with following script:

```
[Unit]
Description=pyload Service
After=network.target

[Service]
Type=forking
User=root
#PIDFile=/run/pyload.pid
PIDFile=/home/pyload/.pyload/pyload.pid
ExecStart=/usr/bin/pyLoadCore --configdir=/home/pyload/.pyload/ --pidfile=/home/pyload/.pyload/pyload.pid --daemon
#ExecStart=/usr/bin/pyLoadCore --configdir=/home/pyload/.pyload/
#ExecStart=/usr/bin/python /opt/pyload/pyLoadCore.py

[Install]
WantedBy=multi-user.target
```
All works fine, except pyload can't restart itself, or manually via the webinterface, there aren't any futher logs, just "shutting down..." nothing more

The only way to restart is in the linux bash with 
`sudo service pyload restart`

Anybody an idea, ho to got this to work? I's a little bit bothering, because an autmatic restart through update process failed...

Thanks,
WebEye

**Comment by GammaC0de** [comment]
Try:
`ExecStop=/usr/bin/pyLoadCore --configdir=/home/pyload/.pyload/ --pidfile=/home/pyload/.pyload/pyload.pid --quit`

**Comment by Web-Eye** [comment]
sadly, with this pyload would not start

```
#systemctl status pyload.service
● pyload.service - pyload Service
   Loaded: loaded (/etc/systemd/system/pyload.service; enabled; vendor preset: enabled)
   Active: failed (Result: protocol) since Sun 2018-10-21 16:20:23 CEST; 2min 9s ago
  Process: 26319 ExecStart=/usr/bin/pyLoadCore --configdir=/home/pyload/.pyload/ --pidfile=/home/pyload/.pyload/pyload.pid --quit (code=exited, status=0/SUCCESS)
 Main PID: 20581 (code=killed, signal=TERM)

Okt 21 16:20:21 FSNAS01 systemd[1]: Starting pyload Service...
Okt 21 16:20:23 FSNAS01 pyLoadCore[26319]: No pyLoad running.
Okt 21 16:20:23 FSNAS01 systemd[1]: pyload.service: Can't open PID file /home/pyload/.pyload/pyload.pid (yet?) after start: No such file or directory
Okt 21 16:20:23 FSNAS01 systemd[1]: pyload.service: Failed with result 'protocol'.
Okt 21 16:20:23 FSNAS01 systemd[1]: Failed to start pyload Service.
```

The "can't open PID.." line is normal

**Comment by Velociraptor85** [comment]
@Web-Eye the option `--quit ` will quit the running core so its not the thing you should put in Exec**Start**

also you are starting the service as root but do you let pyload change the user? Check settings under General>Permissions>Username

**Comment by GammaC0de** [comment]
I was saying to add a `ExecStop` (notice the stop...) line.
also, maybe removing the `--daemon` on the `ExecStart` line might help.

**Comment by youlJunior** [comment]
Here is me pyload service, on Debian Jessie : 

```
[Unit]
Description=Python Downloader
After=network.target

[Service]
User=pyload
Group=pyload
Type=simple
ExecStart=/usr/bin/python /opt/pyload/pyLoadCore.py

[Install]
WantedBy=multi-user.target
```

**Comment by Web-Eye** [comment]
@GammaC0de 
You're right, i missed that ``ExecStop``, but didn't work eather, with removing ``--daemon`` it works, but the bash is busy till i kill pyload

@Velociraptor85 
I checked the permissions, helps nothing; thanks for idea

@youlJunior 
I played a little bit with you script, now it works with these lines:
```
[Service]
User=root
Type=simple
ExecStart=/usr/bin/pyLoadCore --configdir=/home/pyload/.pyload/
```

Thank all of you,
WebEye
