### ISSUE TITLE
Turbobit premium not works

### ISSUE THREAD

**Issue by xxbongoxx** [pyload/pyload#3251]
i become the following errror messages  pyload is up to date

`when in loggin to turbobit i must make a capcher

152 | 24.10.2018 06:22:40 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
-- | -- | -- | --
153 | 24.10.2018 06:25:57 | INFO | shutting down...
154 | 24.10.2018 06:25:57 | INFO | ADDON ClickNLoad: Shutting down proxy...
155 | 24.10.2018 06:25:57 | INFO | pyLoad quits
156 | 24.10.2018 06:26:46 | INFO | Starting pyLoad 0.4.9
157 | 24.10.2018 06:26:46 | INFO | Using home directory: /home/hitman/.pyload
158 | 24.10.2018 06:26:46 | DEBUG | Remote activated: True
159 | 24.10.2018 06:26:46 | DEBUG | created index of plugins
160 | 24.10.2018 06:26:46 | INFO | Activated plugins: ClickNLoad, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
161 | 24.10.2018 06:26:46 | INFO | Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus,  BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos,  DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler,  ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz,  JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles,  MultiHome, PushBullet, PushOver, RestartFailed, SkipRev,  TransmissionRPC, WindowsPhoneNotify, XMPP
162 | 24.10.2018 06:26:46 | INFO | Downloadtime: True
163 | 24.10.2018 06:26:46 | INFO | Starting ThriftBackend: 0.0.0.0:7227
164 | 24.10.2018 06:26:46 | INFO | Starting builtin webserver: 127.0.0.1:8011
165 | 24.10.2018 06:26:46 | INFO | Free space: 5.41 TiB
166 | 24.10.2018 06:26:46 | INFO | Activating Accounts...
167 | 24.10.2018 06:26:46 | INFO | ACCOUNT TurbobitNet: Adding user `xxj*******`...
168 | 24.10.2018 06:26:46 | DEBUG | ACCOUNT TurbobitNet: Reached login timeout for user `xxj*******`
169 | 24.10.2018 06:26:46 | INFO | ACCOUNT TurbobitNet: Login user `xxj*******`...
170 | 24.10.2018 06:26:46 | DEBUG | ACCOUNT TurbobitNet: LOAD URL http://turbobit.net/login \|  redirect=True \| cookies=True \| get={} \| req=None \| decode=True \|  multipart=False \| post={} \| ref=True \| just_header=False
171 | 24.10.2018 06:26:47 | DEBUG | ACCOUNT TurbobitNet: LOAD URL http://turbobit.net/user/login \|  redirect=True \| cookies=True \| get={} \| req=None \| decode=True \|  multipart=False \| post={u'user[submit]': 'Sign in',  u'user[captcha_subtype]': '', u'user[pass]': '**********',  u'user[login]': 'xxj*******', u'user[captcha_type]': '',  u'user[memory]': ''} \| ref=True \| just_header=False
172 | 24.10.2018 06:26:47 | ERROR | ACCOUNT TurbobitNet: Could not login user `xxj*******` \| Bad server response: 503 Service Unavailable
173 | 24.10.2018 06:26:47 | INFO | Activating Plugins...
174 | 24.10.2018 06:26:47 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_start`
175 | 24.10.2018 06:26:47 | INFO | ADDON XFileSharing: Auto-discover new hosters
176 | 24.10.2018 06:26:47 | DEBUG | ADDON XFileSharing: Pattern for hosters:  (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com\|clicknupload\.org\|cramit\.in\|easybytez\.com\|exashare\.com\|filejoker\.net\|fileom\.com\|filerio\.com\|fistfast\.net\|hugefiles\.net\|junocloud\.me\|movreel\.com\|nosupload\.com\|novafile\.com\|rapidfileshare\.net\|rarefile\.net\|safesharing\.eu\|secureupload\.eu\|streamcloud\.eu\|suprafiles\.me\|tusfiles\.net\|uploadrocket\.net\|vidplay\.net))(?P(?:[\d.]+\|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W\|$)
177 | 24.10.2018 06:26:47 | INFO | ADDON XFileSharing: Auto-discover new crypters
178 | 24.10.2018 06:26:47 | DEBUG | ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com\|tusfiles\.net))(?P(?:[\d.]+\|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user\|folder)s?/\w+
179 | 24.10.2018 06:26:47 | DEBUG | ADDON UpdateManager: LOAD URL  https://raw.githubusercontent.com/pyload/updates/master/plugins.txt \|  redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \|  decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
180 | 24.10.2018 06:26:47 | INFO | pyLoad is up and running
181 | 24.10.2018 06:26:47 | INFO | ADDON UpdateManager: pyLoad is up to date!
182 | 24.10.2018 06:26:47 | DEBUG | ADDON UpdateManager: LOAD URL  https://raw.githubusercontent.com/pyload/updates/master/plugins.txt \|  redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \|  decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
183 | 24.10.2018 06:26:47 | DEBUG | ADDON UpdateManager: Requested deletion of plugins: [(u'accounts',  u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts',  u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts',  u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts',  u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts',  u'FreeWayMe'), (u'accounts', u'HotfileCom'), (u'accounts',  u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts',  u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts',  u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts',  u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts',  u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts',  u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts',  u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts',  u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts',  u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts',  u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha',  u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'),  (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container',  u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter',  u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter',  u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter',  u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter',  u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter',  u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter',  u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'),  (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'),  (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks',  u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks',  u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks',  u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks',  u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks',  u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'),  (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks',  u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks',  u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks',  u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks',  u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks',  u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks',  u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks',  u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks',  u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks',  u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks',  u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks',  u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'),  (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks',  u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks',  u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks',  u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks',  u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks',  u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks',  u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'),  (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'),  (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'),  (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks',  u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks',  u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks',  u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks',  u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster',  u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster',  u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster',  u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'),  (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster',  u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster',  u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster',  u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster',  u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster',  u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster',  u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster',  u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal',  u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'),  (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal',  u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal',  u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal',  u'XFSPHoster'), (u'internal', u'utils')]
184 | 24.10.2018 06:26:47 | INFO | ADDON UpdateManager: All plugins are up to date!
185 | 24.10.2018 06:26:53 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666

`

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Will close if no response..

**Comment by xxbongoxx** [comment]
i send the information

**Comment by GammaC0de** [comment]
👍

**Comment by GammaC0de** [comment]
Now works.
I have disabled `Use a captcha to protect my account` option on TurboBit's account setting because logging in with captcha is unsupported by pyload.
