### ISSUE TITLE
Shareonline is not working

### ISSUE THREAD

**Issue by m125** [pyload/pyload#3252]
Hey I use pyload only on Shareonline.
It's not working and here is the log
I think it's grabbing the wrong address

> 
127 | 24.10.2018 09:28:06 | INFO | pyLoad is up and running
-- | -- | -- | --
128 | 24.10.2018 09:28:06 | INFO | ADDON UpdateManager: pyLoad is up to date!
129 | 24.10.2018 09:28:06 | INFO | ADDON UpdateManager: All plugins are up to date!
130 | 24.10.2018 09:28:12 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
131 | 24.10.2018 09:48:08 | INFO | Download starts: *.part01.rar
132 | 24.10.2018 09:48:08 | WARNING | HOSTER ShareonlineBiz[1]: Plugin may be unstable
133 | 24.10.2018 09:48:08 | INFO | ACCOUNT ShareonlineBiz: Grabbing account info for user `*******`...
134 | 24.10.2018 09:48:08 | INFO | HOSTER ShareonlineBiz[1]: Grabbing link info...
135 | 24.10.2018 09:48:08 | INFO | HOSTER ShareonlineBiz[1]: Link name: *.part01.rar
136 | 24.10.2018 09:48:08 | INFO | HOSTER ShareonlineBiz[1]: Link size: 250.20 MiB (262353715 bytes)
137 | 24.10.2018 09:48:08 | INFO | HOSTER ShareonlineBiz[1]: Link status: online
138 | 24.10.2018 09:48:08 | INFO | HOSTER ShareonlineBiz[1]: Processing url: http://www.share-online.biz/dl/*
139 | 24.10.2018 09:48:08 | INFO | HOSTER ShareonlineBiz[1]: Looking for direct download link...
140 | 24.10.2018 09:48:08 | INFO | HOSTER ShareonlineBiz[1]: Direct download link not found
141 | 24.10.2018 09:48:08 | INFO | ACCOUNT ShareonlineBiz: Grabbing account info for user `*******`...
142 | 24.10.2018 09:48:08 | INFO | HOSTER ShareonlineBiz[1]: Filesize: 256204 KiB \| Traffic left for user `*******`: 104801536 KiB
143 | 24.10.2018 09:48:08 | INFO | HOSTER ShareonlineBiz[1]: Processing as premium download...
144 | 24.10.2018 09:48:08 | INFO | ACCOUNT ShareonlineBiz: Grabbing account info for user `*******`...
145 | 24.10.2018 09:48:08 | INFO | HOSTER ShareonlineBiz[1]: Downloading file...
146 | 24.10.2018 09:48:08 | WARNING | HOSTER ShareonlineBiz[1]: Premium download failed \| downloade
147 | 24.10.2018 09:48:08 | INFO | Download restarted: *.part01.rar \| Fallback to free processing
148 | 24.10.2018 09:48:08 | INFO | Download starts: *.part01.rar
149 | 24.10.2018 09:48:08 | WARNING | HOSTER ShareonlineBiz[1]: Plugin may be unstable
150 | 24.10.2018 09:48:08 | INFO | HOSTER ShareonlineBiz[1]: Grabbing link info...
151 | 24.10.2018 09:48:09 | INFO | HOSTER ShareonlineBiz[1]: Link name: *.part01.rar
152 | 24.10.2018 09:48:09 | INFO | HOSTER ShareonlineBiz[1]: Link size: 250.20 MiB (262353715 bytes)
153 | 24.10.2018 09:48:09 | INFO | HOSTER ShareonlineBiz[1]: Link status: online
154 | 24.10.2018 09:48:09 | INFO | HOSTER ShareonlineBiz[1]: Processing url: http://www.share-online.biz/dl/*
155 | 24.10.2018 09:48:09 | INFO | HOSTER ShareonlineBiz[1]: Looking for direct download link...
156 | 24.10.2018 09:48:10 | INFO | HOSTER ShareonlineBiz[1]: Direct download link not found
157 | 24.10.2018 09:48:10 | INFO | HOSTER ShareonlineBiz[1]: Processing as free download...
158 | 24.10.2018 09:48:10 | INFO | HOSTER ShareonlineBiz[1]: Waiting 3 seconds...
159 | 24.10.2018 09:48:14 | WARNING | CAPTCHA ShareonlineBiz[1]: ReCaptcha \| Secure Token pattern not found
160 | 24.10.2018 09:48:14 | WARNING | Download failed: *.part01.rar \| Bad server response: 400 Bad Request
161 | 24.10.2018 09:48:14 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: *.part01.rar (pid:1)
162 | 24.10.2018 09:48:14 | INFO | ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by Mister-XY** [comment]
Hm, no problem here with shareonline and premium.

**Comment by m125** [comment]
Ok Sry for this I made a dump error.
Always run pyload as root. Now it's working

**Comment by GammaC0de** [comment]
:+1:
