### ISSUE TITLE
error: can't start new thread

### ISSUE THREAD

**Issue by diman82** [pyload/pyload#3253]
pyload crashes right after run with an UNCAUGHT EXCEPTION:

```
05.05.2018 08:05:28 INFO      Starting pyLoad 0.4.9
05.05.2018 08:05:28 INFO      Using home directory: /tmp/mnt/entware/entware/var/pyload
05.05.2018 08:05:35 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
05.05.2018 08:05:35 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
05.05.2018 08:05:35 INFO      Downloadtime: True
05.05.2018 08:05:35 INFO      Using SSL ThriftBackend
05.05.2018 08:05:35 INFO      Starting ThriftBackend: 0.0.0.0:7227
05.05.2018 08:05:38 INFO      Free space: 1.80 TiB
05.05.2018 08:05:38 INFO      Starting builtin webserver: 0.0.0.0:8000
05.05.2018 08:05:38 INFO      Activating Accounts...
05.05.2018 08:05:38 INFO      ACCOUNT UploadedTo: Adding user `111*******`...
05.05.2018 08:05:38 INFO      ACCOUNT UploadedTo: Login user `111*******`...
05.05.2018 08:05:38 ERROR     ACCOUNT UploadedTo: 
05.05.2018 08:05:38 ERROR     ACCOUNT UploadedTo: Could not login user `111*******` | 
05.05.2018 08:05:39 INFO      ACCOUNT LinksnappyCom: Adding user `363*******`...
05.05.2018 08:05:39 INFO      ACCOUNT LinksnappyCom: Login user `363*******`...
05.05.2018 08:05:39 ERROR     ACCOUNT LinksnappyCom: Could not login user `363*******` | (6, "Couldn't resolve host 'linksnappy.com'")
05.05.2018 08:05:39 INFO      Activating Plugins...
05.05.2018 08:05:39 ERROR     Error executing hooks: can't start new thread
05.05.2018 08:05:39 INFO      pyLoad is up and running
05.05.2018 08:05:41 ERROR     <<< UNCAUGHT EXCEPTION >>>
Traceback (most recent call last):
  File "/opt/bin/pyload", line 685, in <module>
    main()
  File "/opt/bin/pyload", line 672, in main
    deamon()
  File "/opt/bin/pyload", line 664, in deamon
    pyload_core.start()
  File "/opt/bin/pyload", line 487, in start
    self.scheduler.work()
  File "/tmp/mnt/entware/entware/share/pyload/module/Scheduler.py", line 85, in work
    j.start()
  File "/tmp/mnt/entware/entware/share/pyload/module/Scheduler.py", line 109, in start
    start_new_thread(self.run, ())
error: can't start new thread
```

What is the problem?
I'm forking from most updated stable branch..

**Comment by GammaC0de** [comment]
> "Couldn't resolve host 'linksnappy.com'

You have DNS / internet issues

**Comment by diman82** [comment]
@GammaC0de No, the problem is that pyload exits right away!
P.S Dunno DNS issues, as linksnappy.com works fine from my PC (same network)

**Comment by GammaC0de** [comment]
try pinging linksnappy.com from the NAS, you will get an error..

**Comment by diman82** [comment]
> try pinging linksnappy.com from the NAS, you will get an error..

diman82@RT-AC86U:/tmp/home/root# **ping linksnappy.com**
PING linksnappy.com (104.23.131.80): 56 data bytes
64 bytes from 104.23.131.80: seq=0 ttl=56 time=66.243 ms
64 bytes from 104.23.131.80: seq=1 ttl=56 time=66.934 ms
64 bytes from 104.23.131.80: seq=2 ttl=56 time=65.974 ms
64 bytes from 104.23.131.80: seq=3 ttl=56 time=66.175 ms
64 bytes from 104.23.131.80: seq=4 ttl=56 time=66.705 ms
^C
--- linksnappy.com ping statistics ---
5 packets transmitted, 5 packets received, **0% packet loss**
round-trip min/avg/max = 65.974/66.406/66.934 ms

**Comment by diman82** [comment]
@GammaC0de 
`26.10.2018 15:52:10 INFO      Starting pyLoad 0.4.9
26.10.2018 15:52:10 INFO      Using home directory: /tmp/mnt/entware/entware/var/pyload
26.10.2018 15:52:17 ERROR     <<< UNCAUGHT EXCEPTION >>>
Traceback (most recent call last):
  File "/opt/bin/pyload", line 685, in <module>
    main()
  File "/opt/bin/pyload", line 672, in main
    deamon()
  File "/opt/bin/pyload", line 664, in deamon
    pyload_core.start()
  File "/opt/bin/pyload", line 407, in start
    self.threadManager = ThreadManager(self)
  File "/tmp/mnt/entware/entware/share/pyload/module/ThreadManager.py", line 72, in __init__
    self.createThread()
  File "/tmp/mnt/entware/entware/share/pyload/module/ThreadManager.py", line 78, in createThread
    thread = PluginThread.DownloadThread(self)
  File "/tmp/mnt/entware/entware/share/pyload/module/PluginThread.py", line 161, in __init__
    self.start()
  File "/opt/lib/python2.7/threading.py", line 736, in start
**error: can't start new thread**`

**Comment by GammaC0de** [comment]
Have you changed something on your system before this started to happen?

**Comment by diman82** [comment]
> Have you changed something on your system before this started to happen?
Nope. Just updated to latest firmware (Asus Merlin)

**Comment by diman82** [comment]
@GammaC0de Eventually if was an "out of memory" problem on the router (swap partition wasn't mounted).
All working fine now.
