### ISSUE TITLE
OneFichierCom premium account not detected

### ISSUE THREAD

**Issue by baubi** [pyload/pyload#3254]
Hello, 
I subscribed a premium account on Onefichier.com today but it's not valid on my pyload.

"ERROR | ACCOUNT OneFichierCom: Could not login user `bob*******` \| (35, 'error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version')"

What is my problem ?
Thanks a lot
Bob

**Comment by baubi** [comment]
Thank you but it doesn't work :(
i have got a good version pycurl but i haven't got openSSL version !! 
I look for tomorrow

**Comment by GammaC0de** [comment]
>i have got a good version pycurl but i haven't got openSSL version !!

If you don't have pycurl openSSL version, it is not good..

**Comment by baubi** [comment]
hi
I think it's ok now but my account identification doesn't work.
In log, i have : 

04.11.2018 03:27:10	INFO	ACCOUNT OneFichierCom: Updating account info for user `bobgrang@gmail.com`...
109	04.11.2018 03:27:10	INFO	ACCOUNT OneFichierCom: Relogin user `None`...
110	04.11.2018 03:27:10	ERROR	ACCOUNT OneFichierCom: Could not login user `None` | 'login'

It's strange..
Have you got a idea ?
Thanks a lot.

**Comment by baubi** [comment]
No, 
I just do it. and it's the same problem


114	04.11.2018 03:41:46	ERROR	ACCOUNT OneFichierCom: Could not login user `Bob*******` | (35, 'error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version')

However,
This is my ipkg list installed :
 
[/] # ipkg list-installed
ipkg: unknown sub-command list-installed
ipkg version 0.99.163
usage: ipkg [options...] sub-command [arguments...]
where sub-command is one 
[/] #                    ipkg list_installed
bzip2 - 1.0.6-1 - Very high-quality data compression program
freetype - 2.3.6-1 - Free truetype library
libcurl - 7.24.0-1 - Curl is a command line tool for transferring files with URL syntax, supporting FTP, FTPS, HTTP, HTTPS, GOPHER, TELNET, DICT, FI
libdb - 4.2.52-3 - Berkeley DB Libraries
libgmp - 4.3.2-1 - GNU Multiple Precision Arithmetic Library.
libidn - 1.25-1 - GNU Libidn is an implementation of the Stringprep, Punycode and IDNA specifications defined by the IETF Internationalized Domai
libjpeg - 6b-3 - collection of jpeg tools
libpng - 1.2.44-1 - Portable Network Graphics Libraries
libstdc++ - 6.0.3-6 - Standard C++ library, needed for dynamically linked C++ programs
libtiff - 3.9.5-1 - Tag Image File Format Libraries
nano - 2.2.6-1 - A pico like editor
ncurses - 5.7-3 - NCurses libraries
ncursesw - 5.7-2 - NCurses libraries with wide char support
openssl - 0.9.8v-2 - Openssl provides the ssl implementation in libraries libcrypto and libssl, and is needed by many other applications and librari
ossp-js - 1.6.20070208-1 - a stand-alone distribution of the JavaScript (JS) programming language reference implementation from Mozilla.
py25-crypto - 2.1.0-2 - Python Cryptography Toolkit.
py25-curl - 7.19.0-1 - PycURL is a Python interface to libcurl.
py25-django - 1.1.2-1 - A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
py25-openssl - 0.10-1 - Python wrapper around a small subset of the OpenSSL library.
py25-pil - 1.1.7-1 - The Python Imaging Library (PIL) adds image processing capabilities to your Python interpreter.
python - 2.5-1 - This is a package that sets up the default python.
python25 - 2.5.6-2 - Python is an interpreted, interactive, object-oriented programming language.
readline - 6.1-2 - The GNU Readline library provides a set of functions for use by applications that allow users to edit command lines as they are
sqlite - 3.8.1-1 - SQLite is a small C library that implements a self-contained, embeddable, zero-configuration SQL database engine.
tesseract-ocr - 2.03-3 - An OCR Engine
tesseract-ocr-lang-eng - 2.03-3 - An OCR Engine, eng language files
unrar - 5.0.12-1 - unrar is an application that can decompress files and archives created using the RAR compression scheme
unzip - 6.0-2 - A (de)compression library for the ZIP format
wget-ssl - 1.12-2 - A network utility to retrieve files from the Web
zlib - 1.2.5-1 - zlib is a library implementing the 'deflate' compression system.
Successfully terminated.
[/] #

**Comment by GammaC0de** [comment]
@baubi 
What is the output of:
```
python
import pycurl
pycurl.version
```

?

**Comment by baubi** [comment]
Thanks for your come back, 


[~] # python
Python 2.5.6 (r256:88840, Feb 16 2012, 05:11:54) 
[GCC 3.4.3 (release) (CodeSourcery ARM Q1B 2005)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
>>> pycurl.version
'libcurl/7.24.0 OpenSSL/0.9.8v zlib/1.2.5'
>>>

**Comment by GammaC0de** [comment]
Why are you using python 2.5?

**Comment by baubi** [comment]
Because I dead 

Note: You need at least Python 2.5 or at most Python 2.7 to run pyLoad and its required software dependencies.

**Comment by baubi** [comment]
But i can try with Python 2.6
I don't know if librarys are out of date with my nas version !

**Comment by GammaC0de** [comment]
Can you use [Optware-ng](https://github.com/Optware/Optware-ng)?

**Comment by baubi** [comment]
I think no.
I have a qnap 109 pro 2 and  i don't use the QTS 4.2 firmware. ☹

**Comment by GammaC0de** [comment]
What is the output of `which ipkg`?

Dou you have optware/entware installed?

**Comment by baubi** [comment]
I finally broke my ipkg with Opware-ng because now i can't run ipkg :
[/] # ipkg update
-sh: /opt/bin/ipkg: cannot execute binary file

i try to repair but it's not easy

**Comment by baubi** [comment]
i have Optware_0.99.163_arm-x09

**Comment by GammaC0de** [comment]
Which version of Opware-ng  have you tried to install?

>  i don't use the QTS 4.2 firmware

Why not?

**Comment by baubi** [comment]
> I finally broke my ipkg with Opware-ng because now i can't run ipkg :
> [/] # ipkg update
> -sh: /opt/bin/ipkg: cannot execute binary file
> 
> i try to repair but it's not easy

ok, it's work ! :) 

> Why not?
because my Qnap is a 109 pro2 and his firmware is out of date (qts : 3.3.2 ! )

**Comment by baubi** [comment]
About ssl, 
i haven't got libcurl4-openssl-dev : 

[/] # ipkg list | grep ssl
alac-decoder - 0.1.0-2 - A decoder for the apple lossless file format
flac - 1.2.1-1 - FLAC is a free lossless audio codec.  This package contains the codec libraries and the command-line tools flac and metaflac.
openssl - 0.9.8v-2 - Openssl provides the ssl implementation in libraries libcrypto and libssl, and is needed by many other applications and librari
openssl-dev - 0.9.8v-2 - openssl native development files
perl-crypt-openssl-random - 0.03-1 - Crypt-OpenSSL-Random - Routines for accessing the OpenSSL pseudo-random number generator
perl-crypt-openssl-rsa - 0.24-1 - Crypt-OpenSSL-RSA - RSA encoding and decoding, using the openSSL libraries
perl-crypt-ssleay - 0.55-1 - OpenSSL glue that provides LWP https support.
perl-io-socket-ssl - 0.999-1 - IO-Socket-SSL - Nearly transparent SSL encapsulation for IO::Socket::INET
perl-net-ssleay - 1.30-1 - Net_SSLeay - Perl extension for using OpenSSL
py25-openssl - 0.10-1 - Python wrapper around a small subset of the OpenSSL library.
py26-openssl - 0.10-1 - Python wrapper around a small subset of the OpenSSL library.
sslwrap - 206-1 - sslwrap is a simple Unix service that sits over any simple TCP service such as POP3, IMAP, SMTP, and encrypts all of the data o
ucl - 1.03-1 - UCL is a portable lossless data compression library written in ANSI C.
wavpack - 4.50.1-1 - WavPack is a completely open audio compression format providing lossless, high-quality lossy, and a unique hybrid compression m
wget-ssl - 1.12-2 - A network utility to retrieve files from the Web

I'm lost

**Comment by baubi** [comment]
In Log of pyload, when i add a account, i read : 


08.11.2018 00:38:52 INFO      pyLoad is up and running
08.11.2018 00:38:58 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
08.11.2018 00:39:24 INFO      ACCOUNT OneFichierCom: Adding user `bob*******`...
08.11.2018 00:39:24 DEBUG     ACCOUNT OneFichierCom: Reached login timeout for user `bob*******`
08.11.2018 00:39:24 INFO      ACCOUNT OneFichierCom: Login user `bob*******`...
08.11.2018 00:39:24 DEBUG     ACCOUNT OneFichierCom: LOAD URL https://1fichier.com/login.pl?lg=en | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={'purge': 'off', 'mail': 'bob*******', 'valider': 'Send', 'It': 'on', 'pass': '**********'} | ref=https://1fichier.com/login.pl?lg=en | multipart=False
08.11.2018 00:39:24 ERROR     ACCOUNT OneFichierCom: Could not login user `bob*******` | (35, 'error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version')

is it normal ?
why have got "**" instead my mail adress ?  
is there a track ?

**Comment by GammaC0de** [comment]
Yes, this is intentional. 
About the ssl issue, you have to update the pycurl to include a more modern open ssl.    
In Log of pyload, when i add a account, i read :

08.11.2018 00:38:52 INFO pyLoad is up and running
08.11.2018 00:38:58 INFO ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
08.11.2018 00:39:24 INFO ACCOUNT OneFichierCom: Adding user bob*******...
08.11.2018 00:39:24 DEBUG ACCOUNT OneFichierCom: Reached login timeout for user bob*******
08.11.2018 00:39:24 INFO ACCOUNT OneFichierCom: Login user bob*******...
08.11.2018 00:39:24 DEBUG ACCOUNT OneFichierCom: LOAD URL https://1fichier.com/login.pl?lg=en | redirect=True | decode=True | cookies=True | get={} | req=None | just_header=False | post={'purge': 'off', 'mail': 'bob*******', 'valider': 'Send', 'It': 'on', 'pass': '**********'} | ref=https://1fichier.com/login.pl?lg=en | multipart=False
08.11.2018 00:39:24 ERROR ACCOUNT OneFichierCom: Could not login user bob******* | (35, 'error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version')

is it normal ?
why have got "**" instead my mail adress ?
is there a track ?

**Comment by baubi** [comment]
what should be the version of pycurl ? and openSSL ?

**Comment by GammaC0de** [comment]
This is from my system:
```
python
>>> import pycurl
>>> pycurl.version
'PycURL/7.43.0.2 libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.11 c-ares/1.14.0 WinIDN libssh2/1.8.0 nghttp2/1.32.0'
>>>
```

Where from did you get Optware_0.99.163_arm-x09?

**Comment by GammaC0de** [comment]
> Optware 0.99.163_ arm is extension of my nas for use package and library linux.

Where to download it from? I want to check..

**Comment by baubi** [comment]
[http://pool.qnapclub.pl/projects/packages/optware/Optware_0.99.163_arm-x09.zip](url)

from : http://pool.qnapclub.pl/projects/packages/optware/

**Comment by GammaC0de** [comment]
What is the output of `uname -a`?

**Comment by GammaC0de** [comment]
So which flavor of optware-ng have you tried?

I recommend you to try:
```
wget -O - http://ipkg.nslu2-linux.org/optware-ng/bootstrap/buildroot-armv5eabi-ng-legacy-bootstrap.sh | sh
```

**Comment by baubi** [comment]
Yes, 
I have try: ARMv5 EABI legacy (built with 2.6.22 kernel headers, use for devices that run old kernels.
But i don't know if it's ok with my kernel version! (2.6.12.6-arm1)

I have got after install : segmentation fault.
Why ?

**Comment by baubi** [comment]
But how to do from ipk?

**Comment by GammaC0de** [comment]
`ipkg install ./somepackage.ipk`

**Comment by baubi** [comment]
[/] # python
Python 2.5.6 (r256:88840, Feb 16 2012, 05:11:54)
[GCC 3.4.3 (release) (CodeSourcery ARM Q1B 2005)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libssl.so.0.9.8: cannot open shared object file: No such file or directory
>>>

**Comment by GammaC0de** [comment]
More packages (install the 25 flavors in your case):
[py-curl.zip](https://github.com/pyload/pyload/files/2574367/py-curl.zip)

**Comment by baubi** [comment]
Ok but it's strange, i can't run python or python27 : 
[/] # python
-sh: python: command not found
[/] # python27
-sh: python27: command not found
[/] #

while the package are installed : 

[/] # ipkg list_installed
bzip2 - 1.0.6-1 - Very high-quality data compression program
freetype - 2.3.6-1 - Free truetype library
libcurl - 7.40.0-1 -
libdb - 4.2.52-3 - Berkeley DB Libraries
libgmp - 4.3.2-1 - GNU Multiple Precision Arithmetic Library.
libjpeg - 6b-3 - collection of jpeg tools
libpng - 1.2.44-1 - Portable Network Graphics Libraries
libstdc++ - 6.0.3-6 - Standard C++ library, needed for dynamically linked C++ programs
libtiff - 3.9.5-1 - Tag Image File Format Libraries
nano - 2.2.6-1 - A pico like editor
ncurses - 5.7-3 - NCurses libraries
ncursesw - 5.7-2 - NCurses libraries with wide char support
openssl - 1.0.1a-2 -
ossp-js - 1.6.20070208-1 - a stand-alone distribution of the JavaScript (JS) programming language reference implementation from Mozilla.
py25-crypto - 2.1.0-2 - Python Cryptography Toolkit.
py25-curl - 7.19.0-1 - PycURL is a Python interface to libcurl.
py25-django - 1.1.2-1 - A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
py25-openssl - 0.10-1 - Python wrapper around a small subset of the OpenSSL library.
py25-pil - 1.1.7-1 - The Python Imaging Library (PIL) adds image processing capabilities to your Python interpreter.
py27-crypto - 2.1.0-2 -
py27-curl - 7.19.0-2 -
py27-mercurial - 1.9-1 - A fast, lightweight Source Control Management system designed for efficient handling of very large distributed projects.
py27-openssl - 0.10-2 -
py27-pil - 1.1.7-1 -
py27-redis - 2.7.2-1 - The Python interface to the Redis key-value store
py27-setuptools - 0.6c11-2 - Tool to build and distribute Python packages, enhancement to distutils.
python25 - 2.5.6-2 - Python is an interpreted, interactive, object-oriented programming language.
python27 - 2.7.3-1 - Python is an interpreted, interactive, object-oriented programming language.
readline - 6.1-2 - The GNU Readline library provides a set of functions for use by applications that allow users to edit command lines as they are
screen - 4.0.3-2 - A screen manager that supports multiple logins on single terminal
sqlite - 3.8.1-1 - SQLite is a small C library that implements a self-contained, embeddable, zero-configuration SQL database engine.
termcap - 1.3.1-2 - Terminal emulation library
tesseract-ocr - 2.03-3 - An OCR Engine
tesseract-ocr-lang-eng - 2.03-3 - An OCR Engine, eng language files
zlib - 1.2.5-1 - zlib is a library implementing the 'deflate' compression system.
Successfully terminated.

**Comment by GammaC0de** [comment]
`/opt/bin/python2.7`

**Comment by baubi** [comment]
If i install python again, i recognise python 2.5 
and impossible to start python27 but python25

 ipkg install python
Installing python (2.5-1) to root...
Downloading http://ipkg.nslu2-linux.org/feeds/optware/cs05q1armel/cross/unstable/python_2.5-1_arm.ipk
Configuring python
Successfully terminated.
[/] # python
Python 2.5.6 (r256:88840, Feb 16 2012, 05:11:54)
[GCC 3.4.3 (release) (CodeSourcery ARM Q1B 2005)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libcurl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named libcurl
>>> import pycurl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libssl.so.0.9.8: cannot open shared object file: No such file or directory
>>>
[/] # python27
-sh: python27: command not found
[/] # python


or 


[/] # ipkg install python
Installing python (2.5-1) to root...
Downloading http://ipkg.nslu2-linux.org/feeds/optware/cs05q1armel/cross/unstable/python_2.5-1_arm.ipk
Configuring python
Successfully terminated.
[/] # python
Python 2.5.6 (r256:88840, Feb 16 2012, 05:11:54)
[GCC 3.4.3 (release) (CodeSourcery ARM Q1B 2005)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libcurl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named libcurl
>>> import pycurl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libssl.so.0.9.8: cannot open shared object file: No such file or directory
>>>
[/] # python27
-sh: python27: command not found
[/] # python
[/] # ipkg remove python
Removing package python from root...
Successfully terminated.
[/] # cd /share/HDA_DATA/.qpkg/
[/share/HDA_DATA/.qpkg] # cd python27/
[/share/HDA_DATA/.qpkg/python27] # ls
py27-crypto_2.1.0-2_arm.ipk  py27-openssl_0.10-2_arm.ipk  python27_2.7.3-1_arm.ipk
py27-curl_7.19.0-2_arm.ipk   py27-pil_1.1.7-1_arm.ipk
[/share/HDA_DATA/.qpkg/python27] # ipkg install python27_2.7.3-1_arm.ipk
Installing python27 (2.7.3-1) to root...
Nothing to be done
Successfully terminated.
Collected errors:
Package python27 md5sum mismatch. Either the ipkg or the package index are corrupt. Try 'ipkg update'.
[/share/HDA_DATA/.qpkg/python27] # python
-sh: python: command not found
[/share/HDA_DATA/.qpkg/python27] #

**Comment by GammaC0de** [comment]
you start it with `/opt/bin/python2.7` (notice the dot in 2.7)

**Comment by baubi** [comment]
Yeah ! it's ok : 
[/opt] # python2.7
Python 2.7.3 (default, Apr 12 2012, 12:17:48)
[GCC 3.4.3 (release) (CodeSourcery ARM Q1B 2005)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
>>> pycurl.version
'libcurl/7.40.0 OpenSSL/1.0.1a zlib/1.2.5'

But about installing python, have you got : python27 md5sum because : 
[/opt] # ipkg install /opt/python27/python27_2.7.3-1_arm.ipk
Installing python27 (2.7.3-1) to root...
Nothing to be done
Successfully terminated.
Collected errors:
Package python27 md5sum mismatch. Either the ipkg or the package index are corru           pt. Try 'ipkg update'.

Where have you find the packages ? :)

**Comment by GammaC0de** [comment]
Is seems that python27 is already installed so ignore those messages.

Now type:
```
/opt/bin/python2.7
import pycurl
pycurl.version
```
And post the output here.


Now how exactly do you starts pyload?

**Comment by baubi** [comment]
ok ok 

> Is seems that python27 is already installed so ignore those messages.
>Now type:
>/opt/bin/python2.7
>import pycurl
>pycurl.version

 python2.7
Python 2.7.3 (default, Apr 12 2012, 12:17:48)
[GCC 3.4.3 (release) (CodeSourcery ARM Q1B 2005)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
import pycurl
 pycurl.version
'libcurl/7.40.0 OpenSSL/1.0.1a zlib/1.2.5'

and

> Now how exactly do you starts pyload?

 python2.7 /opt/pyload-stable/pyload-stable/pyLoadCore.py
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/opt/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/opt/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha1
Traceback (most recent call last):
  File "/opt/pyload-stable/pyload-stable/pyLoadCore.py", line 54, in <module>
    from module.database import DatabaseBackend, FileHandler
  File "/share/HDA_DATA/.qpkg/Optware/pyload-stable/pyload-stable/module/database/__init__.py", line 5, in <module>
    from UserDatabase import UserMethods
  File "/share/HDA_DATA/.qpkg/Optware/pyload-stable/pyload-stable/module/database/UserDatabase.py", line 19, in <module>
    from hashlib import sha1
ImportError: cannot import name sha1

**Comment by GammaC0de** [comment]
does pyload works now with python 2.5?

**Comment by baubi** [comment]
no : 
 python2.5 /opt/pyload-stable/pyload-stable/pyLoadCore.py
Traceback (most recent call last):
  File "/opt/pyload-stable/pyload-stable/pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/share/HDA_DATA/.qpkg/Optware/pyload-stable/pyload-stable/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/share/HDA_DATA/.qpkg/Optware/pyload-stable/pyload-stable/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/share/HDA_DATA/.qpkg/Optware/pyload-stable/pyload-stable/module/network/HTTPRequest.py", line 21, in <module>
    import pycurl
ImportError: libssl.so.0.9.8: cannot open shared object file: No such file or directory

**Comment by GammaC0de** [comment]
What is the output of:
```
ls -l /opt/lib/libssl.*
```

And:
```
python2.7 
import hashlib
dir(hashlib)
```
?

**Comment by baubi** [comment]
ls -l /opt/lib/libssl.*
lrwxrwxrwx    1 admin    administ       15 Nov 13 01:54 /opt/lib/libssl.so -> libssl.so.1.0.0
lrwxrwxrwx    1 admin    administ       15 Nov 13 01:54 /opt/lib/libssl.so.0 -> libssl.so.1.0.0
-rw-r--r--    1 admin    administ   319788 Nov 11 19:49 /opt/lib/libssl.so.1.0.0

and  

python2.7
Python 2.7.3 (default, Apr 12 2012, 12:17:48)
[GCC 3.4.3 (release) (CodeSourcery ARM Q1B 2005)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import haslib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named haslib
>>> import hashlib
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/opt/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/opt/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha1


dir(hashlib)
['__all__', '__builtins__', '__doc__', '__file__', '__get_builtin_constructor', '__name__', '__package__', 'algorithms', 'logging', 'new', 'sha224', 'sha256', 'sha384', 'sha512']

**Comment by GammaC0de** [comment]
Install this:
[openssl_1.0.1a-2_arm.zip](https://github.com/pyload/pyload/files/2578219/openssl_1.0.1a-2_arm.zip)

**Comment by baubi** [comment]
ok : 
 ipkg install cd /opt/openssl_1.0.1a-2_arm/openssl_1.0.1a-2_arm.ipk
Installing openssl (1.0.1a-2) to root...
Configuring openssl
Successfully terminated.
Collected errors:
Cannot find package cd.
Check the spelling or perhaps run 'ipkg update'


but pyload doesn't start : 
 python2.7 /opt/pyload-stable/pyload-stable/pyLoadCore.py
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/opt/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/opt/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha1
Traceback (most recent call last):
  File "/opt/pyload-stable/pyload-stable/pyLoadCore.py", line 54, in <module>
    from module.database import DatabaseBackend, FileHandler
  File "/share/HDA_DATA/.qpkg/Optware/pyload-stable/pyload-stable/module/database/__init__.py", line 5, in <module>
    from UserDatabase import UserMethods
  File "/share/HDA_DATA/.qpkg/Optware/pyload-stable/pyload-stable/module/database/UserDatabase.py", line 19, in <module>
    from hashlib import sha1
ImportError: cannot import name sha1

**Comment by GammaC0de** [comment]
Install this:
[openssl_1.0.1a-3_arm.zip](https://github.com/pyload/pyload/files/2578281/openssl_1.0.1a-3_arm.zip)

**Comment by baubi** [comment]
ipkg install cd /opt/openssl_1.0.1a-2_arm/openssl_1.0.1a-3_arm.ipk
Upgrading openssl on root from 1.0.1a-2 to 1.0.1a-3...
Configuring openssl
Successfully terminated.
Collected errors:
Cannot find package cd.
Check the spelling or perhaps run 'ipkg update'
[~] # python2.7 /opt/pyload-stable/pyload-stable/pyLoadCore.py
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/opt/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/opt/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha1
Traceback (most recent call last):
  File "/opt/pyload-stable/pyload-stable/pyLoadCore.py", line 54, in <module>
    from module.database import DatabaseBackend, FileHandler
  File "/share/HDA_DATA/.qpkg/Optware/pyload-stable/pyload-stable/module/database/__init__.py", line 5, in <module>
    from UserDatabase import UserMethods
  File "/share/HDA_DATA/.qpkg/Optware/pyload-stable/pyload-stable/module/database/UserDatabase.py", line 19, in <module>
    from hashlib import sha1
ImportError: cannot import name sha1

**Comment by GammaC0de** [comment]
Output of:
```
 python2.7
 import _hashlib
 dir(_hashlib)
```
?

**Comment by baubi** [comment]
[K[~] # 
[~] # python2.7
Python 2.7.3 (default, Apr 12 2012, 12:17:48) 
[GCC 3.4.3 (release) (CodeSourcery ARM Q1B 2005)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import _hashlib
Traceback (most recent call last):
  File "", line 1, in 
ImportError: libssl.so.0.9.8: cannot open shared object file: No such file or directory

>>> dir(_hashlib)
Traceback (most recent call last):
  File "", line 1, in 
NameError: name '_hashlib' is not defined
>>>

**Comment by GammaC0de** [comment]
Install this:
[python27_2.7.3-2_arm.zip](https://github.com/pyload/pyload/files/2581184/python27_2.7.3-2_arm.zip)

**Comment by baubi** [comment]
WHAAAAA !!! :+1: 
Respect !! 
Thanks a lot ! 

![image](https://user-images.githubusercontent.com/10334596/48498684-06d0e980-e837-11e8-9f00-ecc337ff8e97.png)

**Comment by GammaC0de** [comment]
Great :+1: :+1: :+1: 

Now I recommend you to switch to the `pyplex` web interface.
