### ISSUE TITLE
Zevera broken - new api

### ISSUE THREAD

**Issue by McBeats** [pyload/pyload#3257]
Zevera have a new api: https://www.zevera.com/api
Pyload appears to use the old address etc as now it requires an api key rather than username/password.

Thanks

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by McBeats** [comment]
Sent the api key for my account

**Comment by GammaC0de** [comment]
what is client_id?
Is it global for pyload or personal unique for each user?

**Comment by McBeats** [comment]
global for pyload I presume.
JDownloader updated to support it if that helps: https://github.com/mirror/jdownloader/blob/master/src/jd/plugins/hoster/ZeveraCom.java

**Comment by McBeats** [comment]
You create a client_id at: https://www.zevera.com/registerclient

**Comment by GammaC0de** [comment]
Well, JDownloader uses "306575304".
From my tests, no matter what I put in client_id it works..

 https://www.zevera.com/registerclient requires a user which I don't have..
You can try to register one for pyLoad and send it..

**Comment by McBeats** [comment]
I dont think you will need a paid account for client id registration hopefully.

![image](https://user-images.githubusercontent.com/44104938/47621271-3ff62380-daed-11e8-8c0c-00476076bcae.png)

That is the registration page.

**Comment by GammaC0de** [comment]
There are 3 option to go from here:
1. Use "306575304" as JDownloader does - not a proper thing to do..
2. Use "pyLoad" as client_id - works but the may block this in the future
3. You register a client_id for pyLoad - you do have paid account, right?

**Comment by McBeats** [comment]
Yeah it is paid but any free non paid account can create a client id, it doenst have to be paid to register an app.
If you want I will generate a key though, just thought you guys may want those types of notices etc.
