### ISSUE TITLE
Youtube Playlist 

### ISSUE THREAD

**Issue by nhhuayt** [pyload/pyload#3258]
failedParse error: Empty file | Plugin may be out of date 0.00 BYoutubeCom

I meet that problem when download playlist from youtube.
13/41 videos error and I can't get 1080p of downloaded videos
UpdateManager.py is version 1.21
Youtube Plugin is version 0.68

Please check that link https://www.youtube.com/playlist?list=PLzio09PZm6Tshl1pasGyFwWrm-JPWmjm2
Thank you :D

**Comment by GammaC0de** [comment]
😕 
> 13/41 videos error

What error exactly?? please explain so one can understand..

>  I can't get 1080p of downloaded videos

So you do succeed to download?

**Comment by nhhuayt** [comment]
1. Yes, I do success download 28/41 videos in playlist
![screenshot-2018-10-29 queue - pyload webinterface](https://user-images.githubusercontent.com/17810302/47635349-3caf7600-db87-11e8-87d1-3c3a6c5469dc.png)

2. I choose 1080p but video is only 720p even the source is 1080p
![screenshot-2018-10-29 config - pyload webinterface](https://user-images.githubusercontent.com/17810302/47635407-7a140380-db87-11e8-90ea-3c9dcdd8c79a.png)

**Comment by nhhuayt** [comment]
You could try this link https://www.youtube.com/watch?v=kOqWcSF-p5Q&index=21&list=PLzio09PZm6Tshl1pasGyFwWrm-JPWmjm2
1080p is max but only 720p downloaded

**Comment by GammaC0de** [comment]
Do you have ffmpeg installed? it is required

**Comment by nhhuayt** [comment]
I think I do
![screenshot from 2018-10-29 14-36-39](https://user-images.githubusercontent.com/17810302/47635583-176f3780-db88-11e8-9fa0-89d13fdbadc9.png)

**Comment by GammaC0de** [comment]
Please enable DEBUG mode and then provide log of downloading https://www.youtube.com/watch?v=kOqWcSF-p5Q&index=21&list=PLzio09PZm6Tshl1pasGyFwWrm-JPWmjm2

**Comment by nhhuayt** [comment]
Can you tell me how to enable DEBUG mode ? Run pyload on terminal ?

**Comment by nhhuayt** [comment]
455 | 29.10.2018 14:50:55 | INFO | Added package 14a containing 1 links
-- | -- | -- | --
456 | 29.10.2018 14:50:56 | INFO | Download starts: https://www.youtube.com/watch?v=kOqWcSF-p5Q&index=21&list=PLzio09PZm6Tshl1pasGyFwWrm-JPWmjm2
457 | 29.10.2018 14:50:56 | WARNING | HOSTER YoutubeCom[87]: Plugin may be unstable
458 | 29.10.2018 14:50:56 | INFO | HOSTER YoutubeCom[87]: Grabbing link info...
459 | 29.10.2018 14:50:56 | INFO | HOSTER YoutubeCom[87]: Link name: watch?v=kOqWcSF-p5Q&index=21&list=PLzio09PZm6Tshl1pasGyFwWrm-JPWmjm2
460 | 29.10.2018 14:50:56 | INFO | HOSTER YoutubeCom[87]: Link size: N/D
461 | 29.10.2018 14:50:56 | INFO | HOSTER YoutubeCom[87]: Link status: starting
462 | 29.10.2018 14:50:56 | INFO | HOSTER YoutubeCom[87]: Processing url:  https://www.youtube.com/watch?v=kOqWcSF-p5Q&index=21&list=PLzio09PZm6Tshl1pasGyFwWrm-JPWmjm2
463 | 29.10.2018 14:51:22 | INFO | HOSTER YoutubeCom[87]: File saved
464 | 29.10.2018 14:51:22 | INFO | HOSTER YoutubeCom[87]: Checking download...
465 | 29.10.2018 14:51:22 | INFO | HOSTER YoutubeCom[87]: File is OK
466 | 29.10.2018 14:51:22 | INFO | Download finished: 14a access control infrastructure.mp4
467 | 29.10.2018 14:51:22 | INFO | Package finished: 14a
468 | 29.10.2018 14:51:22 | INFO | ADDON ExtractArchive: Check package: 14a
469 | 29.10.2018 14:51:22 | INFO | ADDON ExtractArchive: No files found to extract

**Comment by GammaC0de** [comment]
This is not debug log, you have to enable DEBUG mode first (it is in pyload's configuration)

**Comment by nhhuayt** [comment]
![screenshot from 2018-10-29 15-01-42](https://user-images.githubusercontent.com/17810302/47636622-91ed8680-db8b-11e8-938b-8d8786f65927.png)

**Comment by GammaC0de** [comment]
Yes, you may need to restart pyload to take effect.

**Comment by nhhuayt** [comment]
657 | 29.10.2018 15:32:51 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
-- | -- | -- | --
658 | 29.10.2018 15:32:51 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0  (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
659 | 29.10.2018 15:32:51 | DEBUG | HOSTER YoutubeCom[90]: Plugin version: 0.68
660 | 29.10.2018 15:32:51 | DEBUG | HOSTER YoutubeCom[90]: Plugin status: testing
661 | 29.10.2018 15:32:51 | WARNING | HOSTER YoutubeCom[90]: Plugin may be unstable
662 | 29.10.2018 15:32:51 | DEBUG | HOSTER YoutubeCom[90]: Config option `use_premium` not found, use default `True`
663 | 29.10.2018 15:32:51 | INFO | HOSTER YoutubeCom[90]: Grabbing link info...
664 | 29.10.2018 15:32:51 | DEBUG | HOSTER YoutubeCom[90]: Link info: {'status': 7, 'hash': {}, 'name':  'watch?v=kOqWcSF-p5Q&index=21&list=PLzio09PZm6Tshl1pasGyFwWrm-JPWmjm2',  'url':  u'https://www.youtube.com/watch?v=kOqWcSF-p5Q&index=21&list=PLzio09PZm6Tshl1pasGyFwWrm-JPWmjm2',  'pattern': {}, 'size': 0}
665 | 29.10.2018 15:32:51 | DEBUG | HOSTER YoutubeCom[90]: Previous link info: {}
666 | 29.10.2018 15:32:51 | INFO | HOSTER YoutubeCom[90]: Link name: watch?v=kOqWcSF-p5Q&index=21&list=PLzio09PZm6Tshl1pasGyFwWrm-JPWmjm2
667 | 29.10.2018 15:32:51 | INFO | HOSTER YoutubeCom[90]: Link size: N/D
668 | 29.10.2018 15:32:51 | INFO | HOSTER YoutubeCom[90]: Link status: starting
669 | 29.10.2018 15:32:51 | INFO | HOSTER YoutubeCom[90]: Processing url:  https://www.youtube.com/watch?v=kOqWcSF-p5Q&index=21&list=PLzio09PZm6Tshl1pasGyFwWrm-JPWmjm2
670 | 29.10.2018 15:32:51 | DEBUG | HOSTER YoutubeCom[90]: LOAD URL  https://www.youtube.com/watch?v=kOqWcSF-p5Q&index=21&list=PLzio09PZm6Tshl1pasGyFwWrm-JPWmjm2  \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \|  multipart=False \| post={} \| ref=True \| just_header=False
671 | 29.10.2018 15:32:52 | DEBUG | HOSTER YoutubeCom[90]: AVAILABLE STREAMS: [22, 43, 18, 36, 17]
672 | 29.10.2018 15:32:52 | DEBUG | HOSTER YoutubeCom[90]: DESIRED VIDEO STREAM: ITAG:37 (.mp4 1920x1080 Q:9 3D:False) NOT found, allowed
673 | 29.10.2018 15:32:52 | DEBUG | HOSTER YoutubeCom[90]: Choosing nearest stream: [(18, True, 7), (22, True, 1)]
674 | 29.10.2018 15:32:52 | DEBUG | HOSTER YoutubeCom[90]: CHOSEN VIDEO STREAM: ITAG:22 (.mp4 1280x720 Q:8 3D:False)
675 | 29.10.2018 15:32:52 | DEBUG | HOSTER YoutubeCom[90]: DOWNLOAD URL  https://r2---sn-8pxuuxa-nbok.googlevideo.com/videoplayback?sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ei=s8XWW4TlLtmGgQPq0qSgCQ&key=yt6&source=youtube&ratebypass=yes&mv=m&dur=1794.252&lmt=1520372485908883&itag=22&ms=au%2Conr&mm=31%2C26&mn=sn-8pxuuxa-nbok%2Csn-i3b7knl6&initcwndbps=1052500&ipbits=0&expire=1540823571&c=WEB&id=o-AGZsO9sOBfVrJdpfaV-m7ddJ7uKqKryPMzYZihZ0S0aw&ip=115.79.192.156&mt=1540801899&requiressl=yes&mime=video%2Fmp4&signature=D2D5FF46A6FB4F8486992A126CFBFAC9610BF0DC.E3384F3E39ECA76352A1BDFB5060C2C7D5C5E96C&pl=21&fvip=5  \| fixurl=True \| resume=None \| get={} \| cookies=True \| disposition=False  \| chunks=None \| post={} \| ref=True
676 | 29.10.2018 15:33:18 | INFO | HOSTER YoutubeCom[90]: File saved
677 | 29.10.2018 15:33:18 | DEBUG | HOSTER YoutubeCom[90]: AVAILABLE SUBTITLES: [u'en']
678 | 29.10.2018 15:33:18 | INFO | HOSTER YoutubeCom[90]: Checking download...
679 | 29.10.2018 15:33:18 | INFO | HOSTER YoutubeCom[90]: File is OK
680 | 29.10.2018 15:33:18 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
681 | 29.10.2018 15:33:18 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
682 | 29.10.2018 15:33:18 | INFO | Download finished: 14a access control infrastructure.mp4
683 | 29.10.2018 15:33:18 | DEBUG | ADDON ExternalScripts: No script found under folder `download_finished`
684 | 29.10.2018 15:33:18 | INFO | Package finished: 14a
685 | 29.10.2018 15:33:18 | DEBUG | ADDON ExternalScripts: No script found under folder `package_finished`
686 | 29.10.2018 15:33:18 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
687 | 29.10.2018 15:33:18 | DEBUG | ADDON ExtractArchive: Use for extensions:  .7z\|.bz2\|.bzip2\|.gz\|.gzip\|.lha\|.lzh\|.lzma\|.rar\|.tar\|.taz\|.tbz\|.tbz2\|.tgz\|.xar\|.xz\|.z\|.zip
688 | 29.10.2018 15:33:18 | DEBUG | All downloads processed
689 | 29.10.2018 15:33:18 | INFO | ADDON ExtractArchive: Check package: 14a
690 | 29.10.2018 15:33:18 | INFO | ADDON ExtractArchive: No files found to extract

**Comment by nhhuayt** [comment]
671 | 29.10.2018 15:32:52 | DEBUG | HOSTER YoutubeCom[90]: AVAILABLE STREAMS: [22, 43, 18, 36, 17]
-- | -- | -- | --


I see AVAILABLE STREAMS is not enough. Maybe youtube change something?

**Comment by GammaC0de** [comment]
>Maybe youtube change something?

Seems like it.

**Comment by GammaC0de** [comment]
I'm afraid there is no easy solution for this because the file is spitted to many little files

**Comment by eSephiroth** [comment]
When I set the Quality Setting to 1080p , pyload download the video and audio desperately.  There are two file, one is xxx.video.mp4, the other is xxx.audio.webm.  Can they merge to one file?

**Comment by GammaC0de** [comment]
@eSephiroth Yes, you need to have `ffmpeg` installed and available in your PATH

**Comment by eSephiroth** [comment]
I use omv + docker. And I install ffmpeg in root command line. Is that something with the docker?

**Comment by GammaC0de** [comment]
@eSephiroth Since this is not related to the original issue,
Can you please open a new issue for this?

Thanks.

**Comment by MPW1412** [comment]
Pyload is for one click hosters. There is youtube-dl for video platforms. It can download videos from a lot of platforms, not only from the name giving one.
