### ISSUE TITLE
RapidgatorNet - ReCaptcha challenge pattern not found

### ISSUE THREAD

**Issue by NorfolkXX** [pyload/pyload#3260]
WARNING | CAPTCHA RapidgatorNet[259]: ReCaptcha \| Secure Token pattern not found
WARNING | HOSTER RapidgatorNet[259]: Free download failed \| ReCaptcha challenge pattern not found

Since a few days, maybe starting around Oct. 25th 2018, I get those messages at rapidgator-downloads. I usually use captcha-solving-services like expertdecoders or 9kw, but here it seems as if its already triggered by the rapidgator-plugin?

When opening the same rapidgator-link in a browser like chrome, I recieve the "i'm not a robot"-captcha and can initiate the download afterwards. 

Is there a solution for pyload? Is this problem coming from the rapidgator-plugin or the captcha-type? 
I tried reading the recaptcha v2 thread to understand more about this type of captcha but honestly didnt understand much of it. especially not if there would be a solution and if yes, how to implement it on an ubuntu headless server.

**Comment by GammaC0de** [comment]
Do you use the [stable branch](https://github.com/pyload/pyload) or the interactive [captcha branch](https://github.com/GammaC0de/pyload)?

**Comment by NorfolkXX** [comment]
I use the stable branche, didnt realize there's a fork. Will check that one too later today...

**Comment by GammaC0de** [comment]
It is not a fork, it will be merged to stable as a new version in the future.

**Comment by GammaC0de** [comment]
Also, please remember to delete the `userplugins` directory.
Please update if you succeed.

**Comment by NorfolkXX** [comment]
I installed the interactive captcha branch from scratch, only reused my config-files, used the classic theme and got stuck, though i'm not sure how it should look like. 

After starting the free download at rapidgator and waiting the usual 45 seconds, pyload logs this:

`231 02.11.2018 17:54:53 WARNING CAPTCHA RapidgatorNet[268]: ReCaptcha | Secure Token pattern not found
232 02.11.2018 17:54:53 WARNING CAPTCHA RapidgatorNet[268]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive`

Also, pyload shows the "captcha waiting"-tag, I click for manual captcha solving, but when clicking on it, only the following message appears, but no captcha is loaded:

`Captcha reading
***
The captcha may take a few seconds to load.
***
Note: to solve this interactive captchas
Please install the Tampermonkey add-on in your browser and add the pyload userscript.`

It stays this way and after 5 minutes, a timeout hits:
`WARNING | CAPTCHA RapidgatorNet[268]: ReCaptcha \| Invalid captcha \| No captcha result obtained in appropriate timing (300s)
-- | --`

First, I did it without tampermonkey and userscript, so I took the links in this message and installed both, but nothing changed. I tried the download 3-4 times, but always got stuck at the message above. Btw, tampermonkey shows me that the script was run (only) one time, not sure if that is correct. I would have expectet it to be run each time I get a captcha message.

Also, aside solving the captcha myself in client, I'd rather more have a services like 9kw or expertdecoders solving it like I did before with the old captchas, but it seems like this also not working. Again, I'm aware that this is a develepement-branch, so I have no idea what should work and what is just not implemented yet :)

Sidenote: 
I use "classic"-theme. Other themes dont work on my system. Dont know why and never cared after I found out that the "classic" works some years ago.

**Comment by GammaC0de** [comment]
Fist of all, have you deleted the userplugins directory?

For manual solving you have to user tapmermonkey and [this](https://github.com/GammaC0de/pyload/raw/captcha-interactive/module/web/media/js/captcha-interactive.user.js) userscript.

9kw have tested to work, mabe you have wrong plugin version becsause not deleting userplugins directory?

expertdecoders most probably don't work, if you want to add support I will need you to send user and password by email..

> I use "classic"-theme. Other themes don't work on my system

Why not?

**Comment by NorfolkXX** [comment]
To the "no captcha displayed/solved" as described above:
Yes, I deleted everything, including both directory-trees, the complete installation-directory as well as the complete config-directory with the userplugins. Then I installed a freshly downloaded "interactive captcha branch". 
From the old installation, I only kept the config-files (accounts.conf, plugin.conf, pyload.conf) and the files.db and used them in the new installation for the interactive captcha branch.

About 9kw:
There are two plugins for 9kw. 
1) At github for pyload, both branches (the regular stable and the interactive captcha) include a plugin "Captcha9kw.py" in version 0.38. 
2) At the 9kw.eu-website another plugin called "Captcha_9kw.py" (including that underline) in version 0.42. Check https://www.9kw.eu/software_pyload.html 

Which one of those 9kw-plugins is to be used? 
I think I tried both of them but will check again tomorrow.

Also, I understand from your reply that pyload + 9kw should be able to solve interactive captchas without me interacting at a webbrowser? This would be the prefered solution anyway for me. 
I only tried the webbrowser + tampermonkey + userscript-approache since the automatich captcha solving with 9kw and Expertdecoders didnt work before. 
BTW: I used expertdecoders before, but if 9kw works, I'm fine with 9kw too.

About the themes: I just switched to pyplex, with server "threaded" and https "off". It is working now. 
(Years ago I had issues with the other themes/servermodes only "default"&"threaded" was working. So when I had issues with the web interface today, I thought it's the same error from years ago, but actually it was just the config still pointing to a "default"-theme and not the new "classic" or "pyplex". Now this was easy to change and both - classic + pyplex - are now working for me)

**Comment by GammaC0de** [comment]
> Which one of those 9kw-plugins is to be used?

[This one](https://github.com/GammaC0de/pyload/raw/captcha-interactive/module/plugins/hooks/Captcha9Kw.py)

> 9kw should be able to solve interactive captchas without me interacting at a webbrowser

Yes, please review the setting and make sure ""Solve ReCaptcha Interactive (cost 30 credits)"" is enabled.

> Now this was easy to change and both - classic + pyplex - are now working for me

Great.

**Comment by NorfolkXX** [comment]
I started again with a fresh install from the "interactive captcha branch", configured only the captcha9kw v0.38 as by your advice. 

Now pyload correctly gets the 9kw-credits and also sends the captcha to 9kw. The result comes back about 100 seconds later, sometimes more. This is also shown when I check at the 9kw-website with correct ticket numbers and correct response times.

After that captcha response, I immediately get "Invalid Captcha" - check the log below.

Is this some timeout? After all, 100 seconds and more is quite long for a captcha check. 
Or is it some other issue? How should the log look like when an interactive captcha is accepted and the download can proceed? 

> 03.11.2018 13:29:29 WARNING   CAPTCHA RapidgatorNet[268]: ReCaptcha | Secure Token pattern not found
> 03.11.2018 13:29:29 WARNING   CAPTCHA RapidgatorNet[268]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive 
> 03.11.2018 13:29:29 INFO      ADDON Captcha9Kw: 94 credits left
> 03.11.2018 13:31:10 INFO      ADDON Captcha9Kw: Captcha result for ticket 114273202: 03AM(...)
> 03.11.2018 13:31:10 INFO      CAPTCHA RapidgatorNet[268]: ReCaptcha | Captcha result: 03AM(...)
> 03.11.2018 13:31:11 WARNING   CAPTCHA RapidgatorNet[268]: ReCaptcha | Invalid captcha | 03AM(...)
> 03.11.2018 13:31:11 INFO      HOSTER RapidgatorNet[268]: Waiting 1 seconds...

**Comment by h4de5** [comment]
captcha display did not work proberly with tempermonkey script on pyload with ssl in firefox.
noticed the following error in the console:
```
Load denied by X-Frame-Options:  ... does not permit cross-origin framing.
```

added this firefox addon and its working again:
https://addons.mozilla.org/en-US/firefox/addon/ignore-x-frame-options-header/

**Comment by GammaC0de** [comment]
@h4de5 Thanks, great find! :grinning:

**Comment by igel-kun** [comment]
just stumbled upon this myself, the addon mentioned by @h4de5 helped - it may be worth mentioning in the alt-text of the captcha box...

**Comment by GammaC0de** [comment]
Looks like there is a chrome extension too: https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe
