### ISSUE TITLE
No filesize/filename information when adding a DLC to queue

### ISSUE THREAD

**Issue by magicxs1** [pyload/pyload#3262]
I'm using several premium accounts. After adding a new dlc you can see the new folder with the name of the package in the collector. If you open the link on the webinterface of pyload you can see all the links with e.g. the share-online url as the file name. Even after waiting a long time or restarting/re-adding the dlc, pyload is not resolving the right file/folder names. uploaded.to links same

After starting the download, pyload is resolving the right filename for the files currently downloading. It's not a big problem because you can still download the files but looks not nice.

```
267	03.11.2018 11:25:39	INFO	Added package add_file containing 1 links
268	03.11.2018 11:25:40	INFO	Decrypting starts: /Daten/ftp/pyload-download/tmp_0207fb697d9ad8e4a9bd5c421b8543a4b07de613.dlc
269	03.11.2018 11:25:40	WARNING	CONTAINER DLC[4396]: Plugin may be unstable
270	03.11.2018 11:25:40	INFO	CONTAINER DLC[4396]: Grabbing link info...
271	03.11.2018 11:25:40	INFO	CONTAINER DLC[4396]: Link name: tmp_0207fb697d9ad8e4a9bd5c421b8543a4b07de613.dlc
272	03.11.2018 11:25:40	INFO	CONTAINER DLC[4396]: Link size: N/D
273	03.11.2018 11:25:40	INFO	CONTAINER DLC[4396]: Link status: starte
274	03.11.2018 11:25:40	INFO	CONTAINER DLC[4396]: Processing url: /Daten/ftp/pyload-download/tmp_0207fb697d9ad8e4a9bd5c421b8543a4b07de613.dlc
275	03.11.2018 11:25:40	INFO	CONTAINER DLC[4396]: Path deleted: /Daten/ftp/pyload-download/tmp_0207fb697d9ad8e4a9bd5c421b8543a4b07de613.dlc
276	03.11.2018 11:25:40	INFO	CONTAINER DLC[4396]: Create package: WinRAR 5.61 | 1 links
277	03.11.2018 11:25:40	INFO	Added package WinRAR 5.61 containing 1 links
278	03.11.2018 11:25:40	INFO	CONTAINER DLC[4396]: Save package `WinRAR 5.61` to folder: WinRAR 5.61

```
adding dlc:
<a><img src="https://image.ibb.co/fNBcXf/Unbenannt.png" alt="before" border="0"></a>

starting download:
<a><img src="https://image.ibb.co/hX7Rsf/Unbenannt2.png" alt="after" border="0"></a>

**Comment by GammaC0de** [comment]
Sorry, known issue, no solution for this.
