### ISSUE TITLE
Error with extracting with multiple split archives

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#3263]
Hello, I have an error while unpacking multiple split archives.
And although he loads down the files 1.part01.rar.001, 1.part01.rar.002, 1.part01.rar.003,
1.part02.rar.001, 1.part02.rar.002, 1.part02.rar.003.
The next step after the download should be the following, he would have to put these archives together as follows 

> 1.part01.rar.001, 1.part01.rar.002, 1.part01.rar.003 to 1.part01.rar

> 1.part02.rar.001, 1.part02.rar.002, 1.part02.rar.003 to 1.part02.rar

But he tries to unpack the archives as they are. This does not work. I tested it with unrar and 7zip.

**Comment by GammaC0de** [comment]
OK,

After downloading all the 67 files I can say this is a case of a bad packager doing a NO NO BOO BOO:
He first compressed the package with rar 1GB parts and the splitting each part with `hjsplit` into 3 parts (hence the 001, 002 and 003 extensions).

Why not just compress the package with rar 350MB?

**Comment by mkreisl** [comment]
@GammaC0d
> Why not just compress the package with rar 350MB?

The idea behind this is to be compatible with other OCH's
Shareonline, Rapidgator, Oboom allows 1GB parts, but Zippyshare only 512M. That's why one 1GB part is divided into 3 sub-parts.

**Comment by Mister-XY** [comment]
@GammaC0de i dont why to split into 350 mb package. I can say, that jdownloader handle this correct.

**Comment by Mister-XY** [comment]
Is there a solution for this problem?

**Comment by GammaC0de** [comment]
@Mister-XY 
I am not sure but you may have been already familiar with the `MergeFiles` plugin which is used to merge hjsplit files.

The issue is what happens if you enable both  `ExtractArchive` and `MergeFiles` plugins? which one will be run first?

Currently there is no mechanism to control the order of the hook plugins runs..

**Comment by Mister-XY** [comment]
at first, its run extractarchive.

**Comment by Mister-XY** [comment]
edit: I have deactivated extractarchive and only activated mergefiles. But after the package is finished, nothing is happend

**Comment by GammaC0de** [comment]
@Mister-XY Apparently, 7-zip can handle split files also,
Fix is on the way.

**Comment by Mister-XY** [comment]
nice to here that

**Comment by GammaC0de** [comment]
Hi,
Please test.

**Comment by GammaC0de** [comment]
Please note that you must add the "001" extension to the "Extract archives ending with extension" config option.

**Comment by Mister-XY** [comment]
I will test it.

**Comment by Mister-XY** [comment]
I think it's solve the issue. Nut i have make a small mistake, i let mergefiles on. 
if mergefiles on and the new extracarchive, merge files will merge the files and delete the old and extracarchive will search the files to merge and make a 0 byte file. 
But i think without mergefiles it's run fine.

**Comment by GammaC0de** [comment]
Yes, not ExtractArchive has its own [HjSplit](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/HjSplit.py) extractor plugin,
You should not enable the MergeFiles plugin if you use ExtractArchive (and also added the '001' file extension in the config) :grin:

**Comment by GammaC0de** [comment]
> But with the new extractarchive, merge file is obsolet 

Basically you are right,
I decided to not delete it in case one would want to use just MergreFiles plugin and leave the ExtractArchive off.

**Comment by Mister-XY** [comment]
My problem with mergefile swas that, that mergefiles did not merge any files. Today its merge files but i don't know why.

**Comment by GammaC0de** [comment]
Just me be clear,
I don't need to enable the MergreFiles plugin if you have enabled the ExtractArchive plugin.

So the rule is: enable just one of them, not both.

**Comment by Mister-XY** [comment]
I have to that, after i see, that mergefiles and extractarchive merge both the files.

**Comment by GammaC0de** [comment]
> edit: did mergefiles use a tool to merge?

No, it is a pure python.

The algorithm is: just copy each part to the output file.

**Comment by Mister-XY** [comment]
Ok, very nice work from you. That make pyload better.

**Comment by Mister-XY** [comment]
But i found a small new error with special signs. if the archive has a special signs looks like ( or ), extractarchive can not extracht the archive.

**Comment by GammaC0de** [comment]
> if the archive has a special signs looks like ( or ), extractarchive can not extracht the archive.

Can you explain? I could not really understand what you meant..

Is there any exception happening?

**Comment by Mister-XY** [comment]
I have send you a pm.

**Comment by GammaC0de** [comment]
Testing.

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/711015850e7af810f753f3df5c9b85afa8cea472

**Comment by Mister-XY** [comment]
solve also the problem. verny nice, top work.

**Comment by hjholtz** [comment]
With these changes, the list of extracted files does not get detected correctly, which  in turn prevents both permission update and recursive unpack.

`05.02.2019 06:10:04 | DEBUG | ADDON ExtractArchive: Extracted files: []`

It seems, `_RE_FILES_V5` does not correctly parse the format provided by the "v" command. I've tried  unrar 5.30 and 5.61 as well as rar 5.40 and 5.50, all of which produce the same format, which does not fit the regex.

**Comment by GammaC0de** [comment]
@hjholtz Sample URL please.
Also, from your words I can deduce that you are using unrar and not 7zip, right?

**Comment by hjholtz** [comment]
@GammaC0de  yes, unrar

the behavior can be reproduced e.g. with these two files:

http://www.ankeziger.net/home/files/lorem_outer.part1.rar
http://www.ankeziger.net/home/files/lorem_outer.part2.rar

they contain another set of multipart rar files, which in turn contain a bunch of "lorem ipsum" style nonsense text files.

**Comment by GammaC0de** [comment]
Testing

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/61ceab78f28a42ae8d01016f7e9c63c14f6e554e

**Comment by hjholtz** [comment]
Seems to work fine. Thanks for the quick fix!

I noticed you didn't include "<->" in the new regex (and then remembered my example file set does not contain a file spanning more than 2 volumes, so you wouldn't see that in the "unrar v" output for the "middle" part). That is fine however. The file name will be found anyway, both in the volume containing its beginning (with -->) and the one with its end (with <--).
