### ISSUE TITLE
Linkifier.com plugin - SSL Troubles

### ISSUE THREAD

**Issue by pirate42** [pyload/pyload#3265]
Hello,

According to Linkifier support:

"Pyload has some issue with our API due to older SSL protocol. Can you please contact their support and let them know?"

Here is the log of Pyload:

_INFO | ACCOUNT LinkifierCom: Login user `toto*******`..._

_ERROR | ACCOUNT LinkifierCom: Could not login user `toto*******` \| (35, 'gnutls_handshake() failed: A TLS packet with unexpected length was received.')_

_ERROR | ACCOUNT LinkifierCom: Could not load hoster list - invalid account, retry in 5 minutes_

Thanks for your help ;)

**Comment by GammaC0de** [comment]
@pirate42 Actually this is not a pyload issue but rather a pycurl issue that pyload uses.
Please read https://github.com/pyload/pyload/issues/3250

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by pirate42** [comment]
Hello and sorry for my late reply.... You are right, it's a pycurl issue and [#3250](https://github.com/pyload/pyload/issues/3250) fix it. Thanks for your help ;)

**Comment by GammaC0de** [comment]
Great :+1:
