### ISSUE TITLE
[ShareonlineBiz] - Bad server response: 400 Bad Request

### ISSUE THREAD

**Issue by SMHRambo** [pyload/pyload#3266]
Hi, after a long time, i using pyload again.
The last usage was around mid this year.
But now i can't download any file from ShareonlineBiz.
The log:

1063 | 09.11.2018 23:58:08 | INFO | starte pyLoad 0.4.9
1064 | 09.11.2018 23:58:08 | INFO | Benutze Home-Verzeichnis: /etc/pyload
1065 | 09.11.2018 23:58:09 | INFO | Aktivierte Plugins: ClickNLoad, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
1066 | 09.11.2018 23:58:09 | INFO | Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
1067 | 09.11.2018 23:58:09 | INFO | Downloadzeit: True
1068 | 09.11.2018 23:58:09 | INFO | Starte ThriftBackend: 0.0.0.0:7227
1069 | 09.11.2018 23:58:09 | INFO | Freier Speicher: 227.67 GiBGB
1070 | 09.11.2018 23:58:09 | INFO | Aktiviere Accounts...
1071 | 09.11.2018 23:58:09 | INFO | Activating Plugins...
1072 | 09.11.2018 23:58:09 | INFO | Starting builtin webserver: 0.0.0.0:8000
1073 | 09.11.2018 23:58:10 | INFO | ADDON XFileSharing: Auto-discover new hosters
1074 | 09.11.2018 23:58:10 | INFO | ADDON UpdateManager: pyLoad is up to date!
1075 | 09.11.2018 23:58:10 | INFO | ADDON XFileSharing: Auto-discover new crypters
1076 | 09.11.2018 23:58:10 | INFO | pyLoad is up and running
1077 | 09.11.2018 23:58:10 | INFO | ADDON UpdateManager: All plugins are up to date!
1078 | 09.11.2018 23:58:16 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
1079 | 09.11.2018 23:58:32 | INFO | Download starts: S8VKOXHP5C
1080 | 09.11.2018 23:58:32 | WARNING | HOSTER ShareonlineBiz[1]: Plugin may be unstable
1081 | 09.11.2018 23:58:32 | INFO | HOSTER ShareonlineBiz[1]: Grabbing link info...
1082 | 09.11.2018 23:58:32 | INFO | HOSTER ShareonlineBiz[1]: Link name: Neues Textdokument.txt
1083 | 09.11.2018 23:58:32 | INFO | HOSTER ShareonlineBiz[1]: Link size: 133.00 B (133 bytes)
1084 | 09.11.2018 23:58:32 | INFO | HOSTER ShareonlineBiz[1]: Link status: online
1085 | 09.11.2018 23:58:32 | INFO | HOSTER ShareonlineBiz[1]: Processing url: http://www.share-online.biz/dl/S8VKOXHP5C
1086 | 09.11.2018 23:58:32 | INFO | HOSTER ShareonlineBiz[1]: Looking for direct download link...
1087 | 09.11.2018 23:58:33 | INFO | HOSTER ShareonlineBiz[1]: Direct download link not found
1088 | 09.11.2018 23:58:33 | INFO | HOSTER ShareonlineBiz[1]: Processing as free download...
1089 | 09.11.2018 23:58:33 | INFO | HOSTER ShareonlineBiz[1]: Waiting 3 seconds...
1090 | 09.11.2018 23:58:37 | WARNING | CAPTCHA ShareonlineBiz[1]: ReCaptcha \| Secure Token pattern not found
1091 | 09.11.2018 23:58:37 | WARNING | Download failed: Neues Textdokument.txt \| Bad server response: 400 Bad Request
1092 | 09.11.2018 23:58:37 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: Neues Textdokument.txt (pid:1)
1093 | 09.11.2018 23:58:37 | INFO | ADDON UnSkipOnFail: No duplicates found

i also made a "fresh" install and run pyload as root, with no success.

**Comment by GammaC0de** [comment]
> i also made a "fresh" install and run pyload as root, with no success.

You should get the `stable` branch from [here](https://github.com/GammaC0de/pyload),
install TamperMonkey on your browser and
also install [this](https://github.com/GammaC0de/pyload/raw/captcha-interactive/module/web/media/js/captcha-interactive.user.js) TamperMonkey  userscript.

You may also activate the `Captcha9k` captcha plugin if you have an account.

**Comment by SMHRambo** [comment]
Sorry for the long response time.
Cool, it's working.
But i have to use Captcha9k, to solve my own captcha.
Is there any way to do it in the web interface from pyload?

**Comment by GammaC0de** [comment]
You should also be able to solve captchas from  the web interface  also.

When you try to solve a captcha what exactly happens?

**Comment by SMHRambo** [comment]
I get the message that a new Captcha is available.
I click on the captcha button.
And tha i get a info box with the following text.

Captchas lesen

The captcha may take a few seconds to load.
Note: to solve this interactive captchas
Please install the Tampermonkey add-on in your browser and add the pyload userscript.

And than i wait for more than a minute with no change. 

I installed tampermonky on edge, chrome and firefox and also installed the script.
pyLoad Script for Interactive Captcha by Michi-F, GammaC0de v0.17

tampermonky is active, the script is enabled and it shows a "1" on the symbol.

the log:
INFO | HOSTER ShareonlineBiz[6]: Looking for direct download link...
INFO | HOSTER ShareonlineBiz[6]: Direct download link not found
INFO | HOSTER ShareonlineBiz[6]: Processing as free download...
INFO | HOSTER ShareonlineBiz[6]: Waiting 3 seconds...
WARNING | CAPTCHA ShareonlineBiz[6]: ReCaptcha \| Secure Token pattern not found
WARNING | CAPTCHA ShareonlineBiz[6]: ReCaptcha \| reCAPTCHA noscript is blocked, trying reCAPTCHA interactive

**Comment by GammaC0de** [comment]
> WARNING | CAPTCHA ShareonlineBiz[6]: ReCaptcha | Secure Token pattern not found
WARNING | CAPTCHA ShareonlineBiz[6]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive

Those are normal messages.

Maybe you should delete the `userplugins` directory and then restart pyload..

**Comment by SMHRambo** [comment]
Problem solved.
There was a scriptblock in all three browsers.
