### ISSUE TITLE
Announcing: new webinterface called `modern` now included

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#3274]
Hi all,

By popular demand I have created a new "bright" version of `pyplex` webinterface called `modern`.

The `modern` webinterface  is now the default webinterface  instead of `classic`.

Final note:
please donate to show you appreciation.

Screenshot:
![capture](https://user-images.githubusercontent.com/11036551/48711902-18d6d180-ec15-11e8-96c3-e757844947ea.PNG)

**Comment by Floflobel** [comment]
hello,
I ma very interesting but it's not working. I have update to latest commit and the default theme is "classic". 
I tried to reboot and clear my browser cache

**Comment by GammaC0de** [comment]
@Floflobel You have to go to pyload's config page -> webinterface -> Template
Change it from` classic` to `modern`, save and restart pyLoad
