### ISSUE TITLE
CloudFlareDdos exception

### ISSUE THREAD

**Issue by RaGeXGotYoded** [pyload/pyload#3278]
Pyload is installed on a machine on which I do not have access to it's config, but this error for the "CloudFlareDdos" plugin comes up. From what I see it has something to do with the time length that it needs to wait for. I could try contacting them if needed.

`ADDON CloudFlareDdos: invalid literal for int() with base 10: 'js: "<command>#1(eval)", line 1: uncaught JavaScript runtime exception: TypeError: Cannot read property "length" from undefined\n\tat <command>#1(eval):1'`

**Comment by GammaC0de** [comment]
What URL did you tried to download?

**Comment by RaGeXGotYoded** [comment]
I've tried accessing a MultiUp.org mirror, and MultiUp.org uses cloudflare apparently.

**Comment by GammaC0de** [comment]
Fixed.
