### ISSUE TITLE
How to update pyLoad on Raspberry?

### ISSUE THREAD

**Issue by renegade2k** [pyload/pyload#3279]
Sorry for the maybe pretty much noob question, but how to i update pyLoad to the newest version on a raspberry?
All the tutorials and questions i found were about a fresh install or installing issues, but i cannot find anything about updates.
Are they installed automaticly?
Or do i need to do kinda "fresh install" every time, when a newer version is released?

**Comment by Velociraptor85** [comment]
yes usually the addons are installed on its own by change of the version of that plugin here in the git but maybe you still have an old version and the update addons is not at the current version an than you might need to update that manually or you just install it fresh ... but you could probably verify that in your log if you see a line like xxxx updated

**Comment by GammaC0de** [comment]
Well, If you installed pyLoad correctly then pyLoad should be able to update the plugins by itself.

Plugin updates fixes issues with hoster plugins, it does not deal with with bugs within pyLoad's core.
For that you will have to do full update from the github repo from time to time.
This is not mandatory but sometimes necessary if there is a serious bug within the core that prevents normal functionality.

**Comment by renegade2k** [comment]
My current "problem" is, that when i try to download from share-online portal it tells me, there is no matched pattern for capcha and the download is stopped.
As far as i google-d it, people tell to update the plugins. So i thought i had to do it manually just like installing raspbian updates ...

**Comment by GammaC0de** [comment]
Well,  share-online (free download) uses ReCaptcha v2 which was not supported up until now.

What you have to do it download the latest stable branch, unpack it to the same location where  pyload is installed, overwriting the files.

After that you have to install TamperMonkey on your browser and also pyLoad's TamperMonkey  script.

**Comment by GammaC0de** [comment]
Did you managed to update pyLoad?

**Comment by GammaC0de** [comment]
No response, closing.
