### ISSUE TITLE
ERROR	ACCOUNT AlldebridCom

### ISSUE THREAD

**Issue by Cseb87** [pyload/pyload#3280]
Hello,
An error has appeared in recent days with AllDebrid.
Can you watch to correct it
thank you

here is the log :

INFO | ACCOUNT AlldebridCom: Adding user `*******`...
INFO | ACCOUNT AlldebridCom: Login user `*******`...
ERROR | ACCOUNT AlldebridCom: Could not login user `*******` \| (35, 'gnutls_handshake() failed: A TLS fatal alert has been received.')
ERROR | ACCOUNT AlldebridCom: Could not load hoster list - invalid account, retry in 5 minutes

**Comment by GammaC0de** [comment]
Please read #3250

**Comment by Cseb87** [comment]
good evening @GammaC0de 
Thank you for your quick reply
but i use pyload on a NAS asustor and i have not touched anything to the installation of pyload for several months, i only have UpdateManager that is enabled.
So that's why I'm wondering why AllDebrid suddenly does not work and this error appears today

**Comment by GammaC0de** [comment]
> So that's why I'm wondering why AllDebrid suddenly does not work and this error appears today

Because AllDebrid  have changed their SSL certificate algorithm and your pycurl version cannot handle this.

**Comment by GammaC0de** [comment]
> I read #3250 and I have not been able to solve my problem
can you help me

How did you installed pyLoad and pycurl specifically?
What python version are you using?

**Comment by Cseb87** [comment]
Do you know how to update pycurl on an ASUSTOR NAS?
I have tried pip install pycurl but I have this error .ConfigurationError: Could not run curl-conf
ig: [Errno 2] No such file or directory

Pyload and python are available in ASUSTOR's app store

![image](https://user-images.githubusercontent.com/16488213/49249443-6b399e80-f41c-11e8-8130-49e0c8b44f78.png)

**Comment by Cseb87** [comment]
I can provide you with the pyload install file (.apk)
you may know how pyload works on ASUSTOR
And how pyload and pycurl are managed
I found in the install this "pycurl-7.19.0.egg-info"
If you can watch this would be cool
But I can not join the .apk file and too big for here
Can I send it to you in another way?

**Comment by GammaC0de** [comment]
> I can provide you with the pyload install file (.apk)

Is there a URL for downloading it?

**Comment by Cseb87** [comment]
here is the link asustor
https://www.asustor.com/en/app_central/app_detail?id=359&type=6&model=

**Comment by Cseb87** [comment]
On your advice @GammaC0de 
I contacted him, we will see if I have a return !
I'll let you know if I have an answer

**Comment by GammaC0de** [comment]
> Can we contact in private ?

https://gitter.im/GammaC0de

**Comment by Cseb87** [comment]
Thank you @GammaC0de 
I contacted you
