### ISSUE TITLE
issue with subyshare

### ISSUE THREAD

**Issue by digimon04** [pyload/pyload#3281]
Recently, I have encountered issues with Subyshare. The error logs are;

`875	30.11.2018 10:51:24	WARNING	HOSTER XFileSharing[10]: SubyshareCom | Plugin may be unstable
876	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | Grabbing link info...
877	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | Link name: GHKQ-71_03.mp4
878	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | Link size: N/D
879	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | Link status: online
880	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | Processing url: http://subyshare.com/wf2mwifvlehu/GHKQ-71_03.mp4.html
881	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | Checking for link errors...
882	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | No errors found
883	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | Processing as free download...
884	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | Checking for link errors...
885	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | No errors found
886	30.11.2018 10:51:24	WARNING	CAPTCHA XFileSharing[10]: SubyshareCom | ReCaptcha | Key pattern not found
887	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | Checking for link errors...
888	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[10]: SubyshareCom | No errors found
889	30.11.2018 10:51:24	WARNING	CAPTCHA XFileSharing[10]: SubyshareCom | ReCaptcha | Key pattern not found
890	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[9]: SubyshareCom | Checking for link errors...
891	30.11.2018 10:51:24	INFO	HOSTER XFileSharing[9]: SubyshareCom | No errors found

892	30.11.2018 10:51:24	WARNING	CAPTCHA XFileSharing[9]: SubyshareCom | ReCaptcha | Key pattern not found
893	30.11.2018 10:51:25	INFO	HOSTER XFileSharing[8]: SubyshareCom | Checking for link errors...
894	30.11.2018 10:51:25	INFO	HOSTER XFileSharing[8]: SubyshareCom | No errors found
895	30.11.2018 10:51:25	WARNING	CAPTCHA XFileSharing[8]: SubyshareCom | ReCaptcha | Key pattern not found
896	30.11.2018 10:51:26	INFO	HOSTER XFileSharing[10]: SubyshareCom | Checking for link errors...
897	30.11.2018 10:51:26	INFO	HOSTER XFileSharing[10]: SubyshareCom | No errors found
898	30.11.2018 10:51:26	WARNING	CAPTCHA XFileSharing[10]: SubyshareCom | ReCaptcha | Key pattern not found
899	30.11.2018 10:51:26	INFO	HOSTER XFileSharing[9]: SubyshareCom | Checking for link errors...
900	30.11.2018 10:51:26	INFO	HOSTER XFileSharing[9]: SubyshareCom | No errors found
901	30.11.2018 10:51:27	WARNING	CAPTCHA XFileSharing[9]: SubyshareCom | ReCaptcha | Key pattern not found
902	30.11.2018 10:51:27	INFO	HOSTER XFileSharing[8]: SubyshareCom | Checking for link errors...
903	30.11.2018 10:51:27	INFO	HOSTER XFileSharing[8]: SubyshareCom | No errors found
904	30.11.2018 10:51:27	WARNING	CAPTCHA XFileSharing[8]: SubyshareCom | ReCaptcha | Key pattern not found
905	30.11.2018 10:51:28	INFO	HOSTER XFileSharing[10]: SubyshareCom | Checking for link errors...
906	30.11.2018 10:51:28	INFO	HOSTER XFileSharing[10]: SubyshareCom | No errors found
907	30.11.2018 10:51:29	WARNING	CAPTCHA XFileSharing[10]: SubyshareCom | ReCaptcha | Key pattern not found
908	30.11.2018 10:51:29	INFO	HOSTER XFileSharing[9]: SubyshareCom | Checking for link errors...
909	30.11.2018 10:51:29	INFO	HOSTER XFileSharing[9]: SubyshareCom | No errors found
910	30.11.2018 10:51:29	WARNING	CAPTCHA XFileSharing[9]: SubyshareCom | ReCaptcha | Key pattern not found
911	30.11.2018 10:51:29	WARNING	HOSTER XFileSharing[8]: SubyshareCom | Free download failed | Parse error: Too many OPs | Plugin may be out of date`

The error shown on queue page is:

`failedParse error: Too many OPs | Plugin may be out of date 0.00 BXFileSharing`

I have triggered an update to ensure all plugins are up-to-date

`834	30.11.2018 10:49:33	INFO	ADDON XFileSharing: Auto-discover new hosters
835	30.11.2018 10:49:34	INFO	ADDON XFileSharing: Auto-discover new crypters
836	30.11.2018 10:49:34	INFO	pyLoad is up and running
837	30.11.2018 10:49:34	INFO	ADDON UpdateManager: All plugins are up to date!`

I have visited the url to ensure they have't introduced interactive recaptcha yet. Any help is appreciated.

test download link: http://subyshare.com/wf2mwifvlehu/GHKQ-71_03.mp4.html

**Comment by GammaC0de** [comment]
Did you succeed to download from subyshare in the past?

**Comment by GammaC0de** [comment]
Hi,
Sorry for the delay.
Is this still relevant?

**Comment by digimon04** [comment]
> Hi,
> Sorry for the delay.
> Is this still relevant?

I have updated pyload installation to the latest stable branch but the issue still persists.
