### ISSUE TITLE
Error FilecryptCC - newTask() takes exactly 5 arguments (4 given)

### ISSUE THREAD

**Issue by j4m** [pyload/pyload#3282]
ERROR | Decrypting failed: 148549F19F.html \| newTask() takes exactly 5 arguments (4 given)

Examplelink: https://filecrypt.cc/Container/148549F19F.html

**Comment by GammaC0de** [comment]
You have to update to the latest `stable` branch.

**Comment by j4m** [comment]
Thanks, it works now.
