### ISSUE TITLE
FileJoker Plugin, Parse error: Too many OPs

### ISSUE THREAD

**Issue by MaxPower88** [pyload/pyload#3286]
After updating the FileJoker plugin for the fix for #3284 there seem to be other issues. Some kind of parse error.

> 428 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: Processing url: https://filejoker.net/6be8ebth5x6w
> -- | -- | -- | --
> 429 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: LOAD URL https://filejoker.net/6be8ebth5x6w \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
> 430 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: Checking for link errors...
> 431 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: No errors found
> 432 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: Processing as free download...
> 433 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: Getting download link #1...
> 434 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: Checking for link errors...
> 435 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: No errors found
> 436 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: {u'usr_login': u'6122479499', u'referer': '', u'fname': u'Hiroko Moriguchi - Mou hitotsu no Mirai ~starry spirit…11.28].rar', u'method_free': u'1', u'id': u'6be8ebth5x6w', u'op': u'download1'}
> 437 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: LOAD URL https://filejoker.net/6be8ebth5x6w \| redirect=False \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={u'usr_login': u'6122479499', u'referer': u'https://filejoker.net/6be8ebth5x6w', u'fname': u'Hiroko Moriguchi - Mou hitotsu no Mirai ~starry spirit…11.28].rar', u'method_free': 'Free Download', u'id': u'6be8ebth5x6w', u'op': u'download1'} \| ref=True \| just_header=False
> 438 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: Getting download link #2...
> 439 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: Checking for link errors...
> 440 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: No errors found
> 441 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: {u'cc': '', u'pm_id': '', u'amount': '', u'aff_file': '', u'type': '', u'email': '', u'op': u'payments'}
> 442 | 02.12.2018 03:04:39 | WARNING | CAPTCHA FilejokerNet[1880]: ReCaptcha \| Key pattern not found
> 443 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: LOAD URL https://filejoker.net/6be8ebth5x6w \| redirect=False \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={u'cc': '', u'pm_id': '', u'amount': '', u'aff_file': '', 'method_free': 'Free Download', u'type': '', u'email': '', u'op': u'payments'} \| ref=True \| just_header=False
> 444 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: Getting download link #3...
> 445 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: Checking for link errors...
> 446 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: No errors found
> 447 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: {u'cc': '', u'pm_id': '', u'amount': '', u'aff_file': '', u'type': '', u'email': '', u'op': u'payments'}
> 448 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: LOAD URL https://filejoker.net/6be8ebth5x6w \| redirect=False \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={u'cc': '', u'pm_id': '', u'amount': '', u'aff_file': '', 'method_free': 'Free Download', u'type': '', u'email': '', u'op': u'payments'} \| ref=True \| just_header=False
> 449 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: Getting download link #4...
> 450 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: Checking for link errors...
> 451 | 02.12.2018 03:04:39 | INFO | HOSTER FilejokerNet[1880]: No errors found
> 452 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: {u'cc': '', u'pm_id': '', u'amount': '', u'aff_file': '', u'type': '', u'email': '', u'op': u'payments'}
> 453 | 02.12.2018 03:04:39 | DEBUG | HOSTER FilejokerNet[1880]: LOAD URL https://filejoker.net/6be8ebth5x6w \| redirect=False \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={u'cc': '', u'pm_id': '', u'amount': '', u'aff_file': '', 'method_free': 'Free Download', u'type': '', u'email': '', u'op': u'payments'} \| ref=True \| just_header=False
> 454 | 02.12.2018 03:04:40 | DEBUG | HOSTER FilejokerNet[1880]: Getting download link #5...
> 455 | 02.12.2018 03:04:40 | INFO | HOSTER FilejokerNet[1880]: Checking for link errors...
> 456 | 02.12.2018 03:04:40 | INFO | HOSTER FilejokerNet[1880]: No errors found
> 457 | 02.12.2018 03:04:40 | DEBUG | HOSTER FilejokerNet[1880]: {u'cc': '', u'pm_id': '', u'amount': '', u'aff_file': '', u'type': '', u'email': '', u'op': u'payments'}
> 458 | 02.12.2018 03:04:40 | DEBUG | HOSTER FilejokerNet[1880]: LOAD URL https://filejoker.net/6be8ebth5x6w \| redirect=False \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={u'cc': '', u'pm_id': '', u'amount': '', u'aff_file': '', 'method_free': 'Free Download', u'type': '', u'email': '', u'op': u'payments'} \| ref=True \| just_header=False
> 459 | 02.12.2018 03:04:40 | WARNING | HOSTER FilejokerNet[1880]: Free download failed \| Parse error: Too many OPs \| Plugin may be out of date

**Comment by GammaC0de** [comment]
Try again now: https://github.com/pyload/pyload/commit/623406e8edcdb358febb50b639cff7e03d9f6d07

**Comment by GammaC0de** [comment]
I have successfully downloaded https://filejoker.net/6be8ebth5x6w,

Did you get captcha prompt? maybe you have this issue https://github.com/pyload/pyload/issues/3285?

**Comment by GammaC0de** [comment]
OK, it seems that they are putting random delay messages, plugin updeted again https://github.com/pyload/pyload/commit/67ab933b9bc1cc9b079db37d94b1f5a324a67292

**Comment by MaxPower88** [comment]
I tried too often, now I have to wait 2 hours to see if it is working, but the behaviour looks more promising already. Regarding #3285 my tampermonkey script is up to date.

**Comment by GammaC0de** [comment]
> I tried too often, now I have to wait 2 hours to see if it is working

You only get average of one download per two hours..

**Comment by MaxPower88** [comment]
> You only get average of one download per two hours..
Well, it must have counted some of my (failed) attempts as a download then. But I didn't even get to the waiting prompt before, it just failed.

**Comment by MaxPower88** [comment]
Works now with your last fix, thanks again!
