### ISSUE TITLE
error:1407742E:SSL (onefichier normal)

### ISSUE THREAD

**Issue by emilic14** [pyload/pyload#3287]
Hi,

I am having constant SSL issues when trying to download through onefichier
This is what I get ->
```
02.12.2018 21:04:17 INFO      Download starts: https://1fichier.com/?blablabla
02.12.2018 21:04:17 DEBUG     ADDON UserAgentSwitcher: Setting connection timeou
t to 60 seconds
02.12.2018 21:04:17 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirecti
ons to 10
02.12.2018 21:04:17 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent str
ing `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
02.12.2018 21:04:17 DEBUG     HOSTER OneFichierCom[5]: Plugin version: 1.14
02.12.2018 21:04:17 DEBUG     HOSTER OneFichierCom[5]: Plugin status: testing
02.12.2018 21:04:17 WARNING   HOSTER OneFichierCom[5]: Plugin may be unstable
02.12.2018 21:04:17 INFO      HOSTER OneFichierCom[5]: Grabbing link info...
Traceback (most recent call last):
  File "threading.pyc", line 503, in __bootstrap
  File "threading.pyc", line 530, in __bootstrap_inner
  File "C:\pyload\dist\.\module\PluginThread.py", line 187, in run
  File "C:\pyload\dist\.\module\plugins\internal\Base.py", line 294, in preproce
ssing
  File "C:\pyload\dist\.\module\plugins\internal\Hoster.py", line 105, in _proce
ss
  File "C:\pyload\dist\.\module\plugins\internal\Base.py", line 166, in _setup
  File "C:\pyload\dist\.\module\plugins\internal\Base.py", line 226, in grab_inf
o
  File "C:\pyload\dist\.\module\plugins\hoster\OneFichierCom.py", line 62, in ge
t_info
  File "C:\pyload\dist\.\module\network\RequestFactory.py", line 131, in getURL
  File "C:\pyload\dist\.\module\network\RequestFactory.py", line 72, in getURL
  File "C:\pyload\dist\.\module\network\HTTPRequest.py", line 216, in load
error: (35, 'error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert prot
ocol version')
02.12.2018 21:04:17 DEBUG     HOSTER OneFichierCom[5]: Link info: {'status': 8,
'error': ''}
02.12.2018 21:04:17 DEBUG     HOSTER OneFichierCom[5]: Previous link info: {}
02.12.2018 21:04:17 INFO      HOSTER OneFichierCom[5]: Link name: https://1fichi
er.com/?ywvn25s51p
02.12.2018 21:04:17 INFO      HOSTER OneFichierCom[5]: Link size: N/D
02.12.2018 21:04:17 INFO      HOSTER OneFichierCom[5]: Link status: failed
02.12.2018 21:04:17 WARNING   Download failed: https://1fichier.com/?blablabla
| failed
02.12.2018 21:04:17 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates
 of: https://1fichier.com/?ywvn25s51p (pid:5)
02.12.2018 21:04:17 INFO      ADDON UnSkipOnFail: No duplicates found
```
Not sure what is the problem, but I am currently focusing on the SSL...

>  File "C:\pyload\dist\.\module\network\HTTPRequest.py", line 216, in load
> error: (35, 'error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert prot
> ocol version')

And well regarding my system:
Windows Server 2012 R2
With Python 2.7.15
With pycurl running OpenSSL
```
>>> import pycurl
>>> pycurl.version
'PycURL/7.43.0.2 libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.11 c-ares/1.14.0 WinIDN
libssh2/1.8.0 nghttp2/1.32.0'
```

And well I am lost, I think my settings are up to date... Dont understand why I am having the SSL error, unless the plugin is not working?

(and yes, I updated pyload to the latest stable version today).
Does anybody have any suggestions of what can be going wrong? 
Thanks!

**Comment by emilic14** [comment]
I am using Windows Server 2012 R2

and I've followed 3250
I am using OpenSSL, and latest version of Python.

```
>>> import pycurl
>>> pycurl.version
'PycURL/7.43.0.2 libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.11 c-ares/1.14.0 WinIDN
libssh2/1.8.0 nghttp2/1.32.0'
```

**Comment by GammaC0de** [comment]
`'PycURL/7.43.0.2 libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.11 c-ares/1.14.0 WinIDN
libssh2/1.8.0 nghttp2/1.32.0'`

This is exactly the same pycurl I have (windows 7).

Can you check your internet settings?

![untitled](https://user-images.githubusercontent.com/11036551/49346793-35a4e780-f6a0-11e8-962a-da6ed5ab343d.png)

**Comment by GammaC0de** [comment]
Would you like to send me your account details (change to a temporary password first) so I can test it on windows 7?

**Comment by emilic14** [comment]
Actually I don't have a 1fichier account ^^
I am trying to use the free download without an account, and I get that error.

**Comment by GammaC0de** [comment]
Ah, OK.

Can you test on another windows say windows 7?

**Comment by emilic14** [comment]
Tested, with Windows 7 64bits.
Same issue...  Can someone confirm that with other systems (linux) it works without any problems?

**Comment by emilic14** [comment]
Hi, thanks for testing.
I tested the link you sent and I am having the same issue...
But at least I now think the issue is on my windows 7 and not with pyload...

Could you let me know what you have in your windows registry : 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols

I have no other ideas of what could be wrong... so trying several stuff related to TLS / pycurl setup in windows.

**Comment by GammaC0de** [comment]
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders]
"SecurityProviders"="credssp.dll"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SaslProfiles]
"GSSAPI"="Kerberos"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL]
"EventLogging"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\CipherSuites]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client]
"DisabledByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest]
"Debuglevel"=dword:00000000
"Negotiate"=dword:00000000
"UTF8HTTP"=dword:00000001
"UTF8SASL"=dword:00000001
"DigestEncryptionAlgorithms"="3des,rc4"

```

**Comment by GammaC0de** [comment]
Maybe uninstall pycurl and then reinstall

**Comment by emilic14** [comment]
Done that several times... even by setting SET PYCURL_SSL_LIBRARY=openssl

And even tried using easy-install...
but still same error.

**Comment by GammaC0de** [comment]
OK,
Is your windows update up-to-date?

**Comment by emilic14** [comment]
yes it is, and all the patches for TLS installed and re-installed... ^^

**Comment by GammaC0de** [comment]
Do you have some kind of firewall or anti-virus installed?

**Comment by emilic14** [comment]
no anti-virus, but windows firewall
and I have accepted traffic incoming from Pyload (python is not an option).

**Comment by GammaC0de** [comment]
Maybe a central/corporate firewall ?

Try disabling windows firewall just for the test..

**Comment by GammaC0de** [comment]
Is this a new pyload installation?

**Comment by emilic14** [comment]
Ish...
I already had it and it was working until like 1 month ago that it stopped
working.
I saw ur post of having to reset pyload and so I did.
Fresh install (windows and latest stable version).

**Comment by emilic14** [comment]
Easy:
Dowloaded the latest version for Windows zip. Extracted it.
The I downloaded the latest stable version from the git.
In the dist folder of the windows extracted version I extracted the content
of the stable version downloaded.
And then just used the pyload core exec.
Easy cheesy.
O and we'll I had already installed python, and pip the needed
dependencies.

**Comment by GammaC0de** [comment]
This is probably the cause of this error.

- Delete your pyload installation.
- Install python 64bits and pycurl.
- Download the latest stable version from the git.
- Put [js.exe](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/osspack32/js.exe) in pyload's directory.
- Start pyload with the command `python pyLodeCore.py`.

**Comment by emilic14** [comment]
Ok, I will give it a try.
What is the JS.EXE file?

**Comment by GammaC0de** [comment]
> What is the JS.EXE file

JavaScript engine: used for several hosters, ClickNLoad, CloudFlare support.

**Comment by emilic14** [comment]
Ok well you are right! (impressive)
The good news is that following a fresh installation and running it through python (not the exe) works.
Although it does point out that I am now missing some items : 

```
## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: missing
py-OpenSSL: OK

py-imaging: missing
tesseract: missing

PyQt4: missing

jinja2: OK
beaker: OK
JS engine: missing
```

And when I added the JS.exe file, and run again the setup, It still states JS engine missing.
Not sure if there is another step I must do to enable the hosters usage?
(or install javaScript in another method?)

**Comment by GammaC0de** [comment]
pycrypto  is availible through `pip install pycrypto`.
Put js.exe somewhere in your PATH.

All the rest are optional.

**Comment by emilic14** [comment]
Great! thanks

So just for pycrypto a windows user will need Microsoft Visual C++ 9
but I am sure users will figure out things.
Well thanks a lot for the support. we can close this now.
Plus you now have a good referral to how to install pyload in Windows! :)
THANKS!

**Comment by GammaC0de** [comment]
Great :+1:
