### ISSUE TITLE
Log page redirecting to spam site

### ISSUE THREAD

**Issue by artdog123** [pyload/pyload#3288]
Whenever I replace the contents of the modules directory with the contents from the current stable, I am redirected to a spam site about 5 secs after accessing the logs page. I have no idea how to figure out which file is causing this but it shouldn't be in a stable version. 

I am on a macbook pro running Mojave. I have tried several browsers. All the same.

**Comment by GammaC0de** [comment]
Hi,
Do you still have this issue?

**Comment by artdog123** [comment]
Hi. Seems to have stopped.
