### ISSUE TITLE
 omv docker Quality Setting bug

### ISSUE THREAD

**Issue by eSephiroth** [pyload/pyload#3291]
I use omv + docker + pyload
When I set the Quality Setting to 1080p , pyload download the video and audio desperately. There are two file, one is xxx.video.mp4, the other is xxx.audio.webm. Can they merge to one file?
And I install ffmpeg in root command line. Is that something with the docker?

Python: | 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
-- | --
OS: | posix linux2 Linux  4.18.0-0.bpo.1-amd64 #1 SMP Debian 4.18.6-1~bpo9+1 (2018-09-13) x86_64
pyLoad version: | 0.4.9
Installation Folder: | /opt/pyload
Config Folder: | /opt/pyload/pyload-config
Download Folder: | /opt/pyload/Downloads
Free Space: | 5.46 TiB
Language: | en
Webinterface Port: | 8187
Remote Interface Port: | 7227

**Comment by eSephiroth** [comment]
I don't think so. I am trying. I guess I have to learn how to make a docker image.

**Comment by GammaC0de** [comment]
Are you using this: https://hub.docker.com/r/writl/pyload/ ?

**Comment by GammaC0de** [comment]
No response, closing.
