### ISSUE TITLE
QUESTION - AddPackage API example with password

### ISSUE THREAD

**Issue by m0n4** [pyload/pyload#3292]
Hi 

is it possible to create a new packet with a password parameter?
in #2828 GammaC0de provides:

```
http://IP:PORT/api/addPackage?name="test"&links=["https://github.com/foo"]
http://IP:PORT/api/addPackage?name=%22test%22&links=%5B%22https%3A%2F%2Fgithub.com%2Ffoo%22%5D
```
Which works perfectly.
I've tried different things but I can't insert a password.

`&password=%22mypass%22`

does the API allow for this case?

Regards

**Comment by GammaC0de** [comment]
@m0n4 Only with the latest stable branch and only with POST method.

POST arguments:
name="packagename"
links=["URL"]
u=username
p=password

**Comment by m0n4** [comment]
thank you.

is this password for the package or connecting to the API ?

**Comment by GammaC0de** [comment]
Oh, you mean password for archive extraction?

**Comment by m0n4** [comment]
yes :-)

**Comment by GammaC0de** [comment]
So you are using the session cookie, right?

**Comment by m0n4** [comment]
i use 
```
	GM.xmlHttpRequest({
	  method: "POST",
	  url: "http://192.168.xx.yy:8000/api/login",
	  data: "username=***&password=***",
	  headers: {
		"Content-Type": "application/x-www-form-urlencoded",
	  },
	  onload: function(res) {
		  AddPackage();
	  }
	});
```

**Comment by GammaC0de** [comment]
OK?

**Comment by m0n4** [comment]
GREAT ! :thumbsup:
thank you

**Comment by GammaC0de** [comment]
:+1:
