### ISSUE TITLE
Strange URL rewrite being macOS Apache reverse proxy

### ISSUE THREAD

**Issue by jamieshaw** [pyload/pyload#3294]
I'm having issues running Pyload behing macOS Server's apache config as a reverse proxy; strangely, it's taking the `%{HTTP_HOST}` and comma-separating itself with itself, dropping the protocol.

For example:
`https://something.domain/pyload` is becoming `something.domain%2C%20something.domain/pyload`

Out of the other 15 or so reverse proxies that I've set up; this is the second occurrence I've seen with this issue. All others work, and still work, fine. It's just Pyload and Bazarr that seem to exhibit this issue regardless of domain name; `something.domain`, `something.local` and `localhost` all create this issue.

I've stripped the config files back to basics to see if anything is introducing the bug, so they're effectively just `ProxyPass` and `ProxyPassReverse` directives, but the issue persists.

As both Pyload and Bazarr are python apps, I'm wondering if there is a shared webserver between the two that is introducing the issue? Google isn't giving me much help, and I never did get to the root of the issue with Bazarr, either.

Any thoughts?

**Comment by GammaC0de** [comment]
Are you using the latest stable branch?

**Comment by GammaC0de** [comment]
Have you set pathprefix config option inside pyload?

Can you post the apache logs?

**Comment by jamieshaw** [comment]
Path prefix is configured as `/pyload`.

Have checked the logs; nothing useful unfortunately, doesn't appear to be flagging any errors. Something is rewriting the URL (successfully) to `something.domain, something.domain` at which the browser does not proceed to resolve the new URL.

**Comment by jamieshaw** [comment]
It’s a domain I use both internally and externally.

Externally resolves through CloudFlare.
Internally resolves through local DNS server.

Both endpoints are the same machine and same virtual host on Apache.

**Comment by GammaC0de** [comment]
😕 I don't understand,
What exactly is your configuration?
How does CloudFlare is involved here?

I cannot resolve `something.domain`...

**Comment by jamieshaw** [comment]
Apologies, I misread your comment, I thought you said "`something.domain` is internal" – that's what I get for attempting to read comments at the gym without my glasses.

No, it's not literal. I'm just using as an example. As mentioned in the original comment the rewrite is occurring as:
`https://something.domain/pyload` is becoming `something.domain%2C%20something.domain/pyload`.

Sorry for the confusion – but to clarify I'm using Cloudflare as a dynamic DNS for external connections; both internally and externally, they're hitting the same machine and both receiving the same comma-delimited rewrite as above.

**Comment by GammaC0de** [comment]
Can you post your apache configuration?

**Comment by jamieshaw** [comment]
Sorry for the delay on this – the config is a bit of a mess, which could potentially be contributing but not entirely sure where to begin debugging.

The apache server on macOS is a bit of a clusterf…

Essentially, there are two Apache servers, one in front of the other proxying internal services and the second being customisable by the sysadmin – the second one is the one that I'm using to reverse proxy various services on my server.

I've just had a dig around the inspector and notice that CherryPy is providing a 303 redirect on load, but not sure why it's pulling the domain name twice which makes me think it could be an internal issue, but not sure why I'm a special snowflake in this case.

**In my testing, I can see the following trace:**
-- Upgrade to HTTPS
`http://something.domain/pyload` returns 302 redirect to `https://something.domain/pyload`
-- Add trailing backslash if missing from URL
`https://something.domain/pyload` returns 302 redirect to `https://something.domain/pyload/`
-- Internal CherryPy redirect
`https://something.domain/pyload/` returns 303 redirect to `https://something.domain, something.domain/pyload/login`

It looks as though it's taking the HOST request header and delimiting it for some reason?

**Comment by GammaC0de** [comment]
I suggest that first you'd disable HTTP and then watch the HTTP headers sent from each proxy using wireshark.

That way you can pinpoint the misbehaving proxy..

**Comment by jamieshaw** [comment]
Had another crack at it but still none the wiser; seems my setup is a special snowflake for whatever reason.
Seeing as I'm seeing this with other CherryPy-based projects elsewhere, I've just fudged it so that the reverse proxy rewrites the location header if it contains `(%2C|\,)(%20|\ )`.

At least it's working now. Thanks for all the help anway.
