### ISSUE TITLE
1fichier delay for DL-URL

### ISSUE THREAD

**Issue by zephura** [pyload/pyload#3299]
Hi,
It looks like 1fichier has been severly been updated...now  with a 2 steps process and eventually a public password

1st step: the link-page
this link-page has a 60 sec delay before accessing the DL-link-page (unavailable if a DL is pending, or finished _recently_)
2nd step: the DL-link-page
it looks like the provided link is a link **for single use**
link example (without password) : https://1fichier.com/?nbdzq5c1cm7nfws1phrj

Another new feature is now some links have **password** : it means password to be able to access to the DL-link-page.
link example (for password) : https://1fichier.com/?rwx6ok5jrkd29586e00l
password : annuaire-telechargement.com

**Comment by GammaC0de** [comment]
I have successfully tested and downloaded the second link (with the password) with no issues..

**Comment by GammaC0de** [comment]
Can you give more example URLs because I don't have any issues
Tried to download the first URL a view times:
It downloads the URL and then I restart the download which causes a wait and then the download works.

**Comment by zephura** [comment]
Hi,
My bad, I tried and re-tried, it works fine with every link **without** password.

for link protected by password, it writes : 
 - link not available
 - plugin out of date

**Comment by GammaC0de** [comment]
Did you fill the password on the add URL dialog?

**Comment by zephura** [comment]
What is happening is when i add the password and the URL dialog, 
I get a single use link which is available for some delay.

If I collect some of them, let say only 2 links; the delay between 2 downloads make expire the second link.

**Comment by zephura** [comment]
here is extract from the log:
the download is performed by the baseplugin, not the 1fichier plugin, which confirm that I filled the password on the URL dialog


389 | 31.12.2018 09:29:05 | INFO | Download starts: https://a-1.1fichier.com/c107020015
-- | -- | -- | --
390 | 31.12.2018 09:29:05 | WARNING | HOSTER BasePlugin[2834]: Plugin may be unstable
391 | 31.12.2018 09:29:05 | INFO | HOSTER BasePlugin[2834]: Grabbing link info...
392 | 31.12.2018 09:29:05 | INFO | HOSTER BasePlugin[2834]: Link name: c107020015
-- | -- | -- | --
393 | 31.12.2018 09:29:05 | INFO | HOSTER BasePlugin[2834]: Link size: N/D
394 | 31.12.2018 09:29:05 | INFO | HOSTER BasePlugin[2834]: Link status: demarrage
395 | 31.12.2018 09:29:05 | INFO | HOSTER BasePlugin[2834]: Processing url: https://a-1.1fichier.com/c107020015

**Comment by GammaC0de** [comment]
https://a-1.1fichier.com/c107020015 is not a valid 1fichier URL, that's why it is handled by BasePlugin.

Can you give me more password protected URLs to test?

**Comment by zephura** [comment]
- Always same password : annuaire-telechargement.com

- but here other example links:
https://1fichier.com/?g8a1qa3yidp0h9bzrjfq
https://1fichier.com/?68q4okg5qdxqn8ibg2io
https://1fichier.com/?9bz8k3xt4dmr3mqm29bb

**Comment by GammaC0de** [comment]
@zephura I tried those links and the one before and all links were successfully downloaded.

What hardware are you using?

**Comment by GammaC0de** [comment]
Cannot reproduce and no response so closing.
