### ISSUE TITLE
BIG Issues since "major update"

### ISSUE THREAD

**Issue by Bx15k0** [pyload/pyload#3300]
Hi,
i have installed pyload on my QNAP NAS and until 2 weeks ago everything worked fine, then i had the fantastic idea to manually update pyload with the newest stable (like i do every few months). After the update, share-online and uploaded.net won´t work anymore.

The failure is: (log-extract)
ERROR	Error importing ShareonlineBiz: invalid syntax (ReCaptcha.py, line 414)
CRITICAL	'NoneType' object has no attribute 'ShareonlineBiz'
or
CRITICAL	'NoneType' object has no attribute 'UploadedTo'
ERROR	Error importing UploadedTo: invalid syntax (ReCaptcha.py, line 414)

I have premium accounts and i don´t know why the "ReCaptcha"-thing is imported... But i do only understand a LITTLE LITTLE programming language and i don´t know what´s happening...
Maybe the failure is on my site? I hope you can help.

And:
I installed everything new, resetting all settings and tried so much things - at the moment i don´t know any way further

(i hope you understand me, i´m not a native english-speaker)

**Comment by vuolter** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by vuolter** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/pyload/pyload/issues/974 (ExtractArchive error since Update), https://github.com/pyload/pyload/issues/1590 (Uploaded/Premiumize/CustomPlugin issues since latest update), https://github.com/pyload/pyload/issues/1118 (rapidgator issue), https://github.com/pyload/pyload/issues/2939 (alldebrid issue), and https://github.com/pyload/pyload/issues/2267 (1fichier issues).

**Comment by GammaC0de** [comment]
Hello,
How did you installed pyload in the first place?

How exactly do  manually update pyload with the newest stable?

What QNAP  model is it?

**Comment by iceman64128** [comment]
All, got the same problem as Bx15k0. I got a premium account and I am not able to interpret the following code:
(TIA for your help)
`30.12.2018 10:49:22 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
-- | -- | --
1135 | 30.12.2018 10:49:22 | ERROR | Error importing ShareonlineBiz: invalid syntax (ReCaptcha.py, line 414)
1134 | 30.12.2018 10:49:20 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
1133 | 30.12.2018 10:49:20 | ERROR | Error importing ShareonlineBiz: invalid syntax (ReCaptcha.py, line 414)
1132 | 30.12.2018 10:48:58 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
1131 | 30.12.2018 10:48:54 | INFO | ADDON UpdateManager: All plugins are up to date!
1130 | 30.12.2018 10:48:54 | INFO | ADDON UpdateManager: Removed blacklisted plugin: INTERNAL AbstractExtractor
1129 | 30.12.2018 10:48:54 | INFO | ADDON UpdateManager: pyLoad is up to date!
1128 | 30.12.2018 10:48:54 | INFO | pyLoad is up and running
1127 | 30.12.2018 10:48:54 | INFO | ADDON XFileSharing: Auto-discover new crypters
1126 | 30.12.2018 10:48:54 | ERROR | Error importing MultiUpOrg: invalid syntax (ReCaptcha.py, line 414)
1125 | 30.12.2018 10:48:53 | ERROR | Error importing FilecryptCc: invalid syntax (CoinHive.py, line 96)
1124 | 30.12.2018 10:48:53 | INFO | ADDON XFileSharing: Auto-discover new hosters
1123 | 30.12.2018 10:48:53 | ERROR | Error importing HugefilesNet: invalid syntax (ReCaptcha.py, line 414)
1122 | 30.12.2018 10:48:53 | ERROR | Error importing ExtabitCom: invalid syntax (ReCaptcha.py, line 414)
1121 | 30.12.2018 10:48:53 | ERROR | Error importing FilejungleCom: invalid syntax (ReCaptcha.py, line 414)
1120 | 30.12.2018 10:48:53 | ERROR | Error importing YoutubeCom: invalid syntax (YoutubeCom.py, line 569)
1119 | 30.12.2018 10:48:53 | ERROR | Error importing FistfastNet: invalid syntax (ReCaptcha.py, line 414)
1118 | 30.12.2018 10:48:53 | ERROR | Error importing FileserveCom: invalid syntax (ReCaptcha.py, line 414)
1117 | 30.12.2018 10:48:53 | ERROR | Error importing UgouploadNet: invalid syntax (ReCaptcha.py, line 414)
1116 | 30.12.2018 10:48:53 | ERROR | Error importing NovafileCom: invalid syntax (ReCaptcha.py, line 414)
1115 | 30.12.2018 10:48:53 | ERROR | Error importing FilepostCom: invalid syntax (ReCaptcha.py, line 414)
1114 | 30.12.2018 10:48:53 | ERROR | Error importing SafesharingEu: invalid syntax (ReCaptcha.py, line 414)
1113 | 30.12.2018 10:48:53 | ERROR | Error importing StreamcloudEu: invalid syntax (ReCaptcha.py, line 414)
1112 | 30.12.2018 10:48:53 | ERROR | Error importing OboomCom: invalid syntax (ReCaptcha.py, line 414)
1111 | 30.12.2018 10:48:53 | ERROR | Error importing FiregetCom: invalid syntax (ReCaptcha.py, line 414)
1110 | 30.12.2018 10:48:53 | ERROR | Error importing SuprafilesMe: invalid syntax (ReCaptcha.py, line 414)
1109 | 30.12.2018 10:48:53 | ERROR | Error importing NosuploadCom: invalid syntax (ReCaptcha.py, line 414)
1108 | 30.12.2018 10:48:53 | ERROR | Error importing FilecloudIo: invalid syntax (ReCaptcha.py, line 414)
1107 | 30.12.2018 10:48:53 | ERROR | Error importing ZippyshareCom: invalid syntax (ReCaptcha.py, line 414)
1106 | 30.12.2018 10:48:53 | ERROR | Error importing RarefileNet: invalid syntax (ReCaptcha.py, line 414)
1105 | 30.12.2018 10:48:53 | ERROR | Error importing FilerNet: invalid syntax (ReCaptcha.py, line 414)
1104 | 30.12.2018 10:48:53 | ERROR | Error importing LuckyShareNet: invalid syntax (ReCaptcha.py, line 414)
1103 | 30.12.2018 10:48:53 | ERROR | Error importing MovReelCom: invalid syntax (ReCaptcha.py, line 414)
1102 | 30.12.2018 10:48:53 | ERROR | Error importing UploadrocketNet: invalid syntax (ReCaptcha.py, line 414)
1101 | 30.12.2018 10:48:53 | ERROR | Error importing RapiduNet: invalid syntax (ReCaptcha.py, line 414)
1100 | 30.12.2018 10:48:53 | ERROR | Error importing MediafireCom: invalid syntax (ReCaptcha.py, line 414)
1099 | 30.12.2018 10:48:53 | ERROR | Error importing FilerioCom: invalid syntax (ReCaptcha.py, line 414)
1098 | 30.12.2018 10:48:53 | ERROR | Error importing FreakshareCom: invalid syntax (ReCaptcha.py, line 414)
1097 | 30.12.2018 10:48:53 | ERROR | Error importing DateiTo: invalid syntax (ReCaptcha.py, line 414)
1096 | 30.12.2018 10:48:53 | ERROR | Error importing TurbobitNet: invalid syntax (ReCaptcha.py, line 414)
1095 | 30.12.2018 10:48:53 | ERROR | Error importing JunocloudMe: invalid syntax (ReCaptcha.py, line 414)
1094 | 30.12.2018 10:48:53 | ERROR | Error importing RapidgatorNet: invalid syntax (ReCaptcha.py, line 414)
1093 | 30.12.2018 10:48:53 | ERROR | Error importing DatafileCom: invalid syntax (ReCaptcha.py, line 414)
1092 | 30.12.2018 10:48:53 | ERROR | Error importing ShareonlineBiz: invalid syntax (ReCaptcha.py, line 414)
1091 | 30.12.2018 10:48:53 | ERROR | Error importing CatShareNet: invalid syntax (ReCaptcha.py, line 414)
1090 | 30.12.2018 10:48:53 | ERROR | Error importing UpstoreNet: invalid syntax (ReCaptcha.py, line 414)
1089 | 30.12.2018 10:48:53 | ERROR | Error importing FilejokerNet: invalid syntax (ReCaptcha.py, line 414)
1088 | 30.12.2018 10:48:53 | ERROR | Error importing SecureUploadEu: invalid syntax (ReCaptcha.py, line 414)
1087 | 30.12.2018 10:48:53 | ERROR | Error importing TusfilesNet: invalid syntax (ReCaptcha.py, line 414)
1086 | 30.12.2018 10:48:53 | ERROR | Error importing CramitIn: invalid syntax (ReCaptcha.py, line 414)
1085 | 30.12.2018 10:48:53 | ERROR | Error importing RapidfileshareNet: invalid syntax (ReCaptcha.py, line 414)
1084 | 30.12.2018 10:48:53 | ERROR | Error importing CrockoCom: invalid syntax (ReCaptcha.py, line 414)
1083 | 30.12.2018 10:48:53 | ERROR | Error importing RealdebridComTorrent: invalid syntax (RealdebridComTorrent.py, line 71)
1082 | 30.12.2018 10:48:53 | ERROR | Error importing ClicknuploadCom: invalid syntax (ReCaptcha.py, line 414)
1081 | 30.12.2018 10:48:53 | ERROR | Error importing FileomCom: invalid syntax (ReCaptcha.py, line 414)
1080 | 30.12.2018 10:48:53 | ERROR | Error importing UploadgigCom: invalid syntax (ReCaptcha.py, line 414)
1079 | 30.12.2018 10:48:53 | ERROR | Error importing XFileSharing: invalid syntax (ReCaptcha.py, line 414)
1078 | 30.12.2018 10:48:53 | ERROR | Error importing UploadedTo: invalid syntax (ReCaptcha.py, line 414)
1077 | 30.12.2018 10:48:53 | ERROR | Error importing BigfileTo: invalid syntax (ReCaptcha.py, line 414)
1076 | 30.12.2018 10:48:53 | ERROR | Error importing EasybytezCom: invalid syntax (ReCaptcha.py, line 414)
1075 | 30.12.2018 10:48:53 | ERROR | Error importing RockfileEu: invalid syntax (ReCaptcha.py, line 414)
1074 | 30.12.2018 10:48:53 | ERROR | Error importing HundredEightyUploadCom: invalid syntax (ReCaptcha.py, line 414)
1073 | 30.12.2018 10:48:53 | ERROR | Error importing ExashareCom: invalid syntax (ReCaptcha.py, line 414)
1072 | 30.12.2018 10:48:53 | ERROR | Error importing VidPlayNet: invalid syntax (ReCaptcha.py, line 414)
1071 | 30.12.2018 10:48:53 | INFO | Activating Plugins...`

**Comment by iceman64128** [comment]
Okay. I got a TS-459 Pro with QTS4.2.6 2018/10/26. 

I updated pyload according to your instructions. #3283

**Comment by GammaC0de** [comment]
OK,
And how did you installed pyload in the first place?

How do you start pyload?

**Comment by iceman64128** [comment]
Frankly speaking - it is a long time ago, I installed pyload. So I can not remember. It all worked well until end October. Pyload starts as a service, once the NAS is started.

**Comment by iceman64128** [comment]
Install folder is: /share/MD0_DATA/.qpkg/pyload

unfortunately behavior has not changed - log looks as I posted above.

**Comment by GammaC0de** [comment]
What is the output of `ls -la /share/MD0_DATA/.qpkg/pyload`?

**Comment by Bx15k0** [comment]
First: Sorry for my late answer
Second: Ok, i hope we will find a solution also for iceman

> How did you installed pyload in the first place?
First (long time ago) i installed pyload with the official QNAP way with the "QNAP Store" but i think i reinstalled it also a long time ago with the way "install manually" (download at first an qpkg, and then install it  with the AppCenter "install manually")
i have reinstalled it in the last weeks i think 10 times or more this way.

> How exactly do manually update pyload with the newest stable?
ftp-connection, download the stable package on my desktop, copy the content from the zip to the installation-folder (/share/MD0_DATA/.qpkg/pyload) or copy the zip and unzip the content to the installation-folder overwriting the old files.

> What QNAP model is it?
TS-212 (armv5)

(reinstallation of ReCaptcha.py did not change anything)

OUTPUT ls -la:
`drwxr-xr-x   10 admin    administ      4096 Dec 28 23:44 ./
drwxrwxrwx   12 admin    administ      4096 Dec 29 01:10 ../
-rw-r--r--    1 admin    administ       422 Dec 16 17:01 .gitattributes
-rw-r--r--    1 admin    administ      3037 Dec 16 17:01 .gitignore
-rwxr--r--    1 admin    administ       149 Dec 14  2011 .hg_archival.txt*
-rwxr--r--    1 admin    administ       411 Dec 19  2011 .hgignore*
-rwxr--r--    1 admin    administ       808 Dec 19  2011 .hgtags*
-rwxr--r--    1 admin    administ      2611 Mar  7  2011 .qpkg_icon.gif*
-rwxr--r--    1 admin    administ      3531 Mar  7  2011 .qpkg_icon_80.gif*
-rwxr--r--    1 admin    administ      2985 Mar  7  2011 .qpkg_icon_gray.gif*
-rwxr--r--    1 admin    administ      1019 Dec 19  2011 .uninstall.sh*
-rwxr--r--    1 admin    administ     32422 Dec 14  2011 LICENSE*
-rw-r--r--    1 admin    administ     32422 Dec 16 17:01 LICENSE.MD
-rwxr--r--    1 admin    administ      2541 Dec 14  2011 README*
-rw-r--r--    1 admin    administ      5531 Dec 16 17:01 README.MD
drwxr-xr-x    6 admin    administ      4096 Dec 29 00:36 data/
drwxr-xr-x    2 admin    administ      4096 Dec 16 17:01 docs/
drwxr-xr-x    2 admin    administ      4096 Dec 28 23:44 icons/
drwxr-xr-x   17 admin    administ      4096 Dec 28 23:44 locale/
drwxr-xr-x   12 admin    administ      4096 Dec 28 23:45 module/
drwxr-xr-x    9 admin    administ      4096 Dec 19  2011 opt/
-rw-r--r--    1 admin    administ      9106 Dec 16 17:01 pavement.py
-rw-r--r--    1 admin    administ     19879 Dec 16 17:01 pyLoadCli.py
-rw-r--r--    1 admin    administ     22964 Dec 16 17:01 pyLoadCore.py
-rw-r--r--    1 admin    administ     28650 Dec 16 17:01 pyLoadGui.py
-rw-rw-rw-    1 admin    administ   2206946 Dec 28 23:06 pyload-stable.zip
-rwxr-xr-x    1 admin    administ      2342 Dec 19  2011 pyload.sh*
drwxr-xr-x   10 admin    administ      4096 Dec 28 23:44 scripts/
-rw-r--r--    1 admin    administ       117 Dec 16 17:01 setup.cfg
-rw-r--r--    1 admin    administ      3884 Dec 16 17:01 systemCheck.py
-rw-r--r--    1 admin    administ      1005 Dec 16 17:01 testlinks.txt
drwxr-xr-x    2 admin    administ      4096 Dec 28 23:44 tests/`

**Comment by GammaC0de** [comment]
>ftp-connection, download the stable package on my desktop, copy the content from the zip to the installation-folder

Why not use wget to download it directly from the NAS?

what is the output of `cat ls -la /share/MD0_DATA/.qpkg/pyload/pyload.sh`?

**Comment by Bx15k0** [comment]
wget: because i'm not so familiar with linux, but i try to learn such things. 

OUTPUT:
cat /share/MD0_DATA/.qpkg/pyload/pyload.sh
#!/bin/sh

RETVAL=0
QPKG_NAME="pyLoad"
PUBLIC_SHARE=`/sbin/getcfg SHARE_DEF defPublic -d Public -f /etc/config/def_share.info`
DOWNLOAD_SHARE=`/sbin/getcfg SHARE_DEF defDownload -d Qdownload -f /etc/config/def_share.info`

_exit()
{
    /bin/echo -e "Error: $*"
    /bin/echo
    exit 1
}

# Determine BASE installation location according to smb.conf
BASE=
publicdir=`/sbin/getcfg $PUBLIC_SHARE path -f /etc/config/smb.conf`
if [ ! -z $publicdir ] && [ -d $publicdir ];then
	publicdirp1=`/bin/echo $publicdir | /bin/cut -d "/" -f 2`
	publicdirp2=`/bin/echo $publicdir | /bin/cut -d "/" -f 3`
	publicdirp3=`/bin/echo $publicdir | /bin/cut -d "/" -f 4`
	if [ ! -z $publicdirp1 ] && [ ! -z $publicdirp2 ] && [ ! -z $publicdirp3 ]; then
		[ -d "/${publicdirp1}/${publicdirp2}/${PUBLIC_SHARE}" ] && BASE="/${publicdirp1}/${publicdirp2}"
	fi
fi

# Determine BASE installation location by checking where the Public folder is.
if [ -z $BASE ]; then
	for datadirtest in /share/HDA_DATA /share/HDB_DATA /share/HDC_DATA /share/HDD_DATA /share/MD0_DATA; do
		[ -d $datadirtest/$PUBLIC_SHARE ] && BASE="/${publicdirp1}/${publicdirp2}"
	done
fi
if [ -z $BASE ] ; then
	echo "The Public share not found."
	_exit 1
fi
QPKG_DIR=${BASE}/.qpkg/pyload

/bin/echo $PATH | /bin/grep "/root/.pyload" 1>>/dev/null 2>>/dev/null
[ $? -ne 0 ] && export PATH=$PATH:/root/.pyload/opt/bin

/bin/echo $LD_LIBRARY_PATH | /bin/grep "/root/.pyload" 1>>/dev/null 2>>/dev/null
[ $? -ne 0 ] && export LD_LIBRARY_PATH=/root/.pyload/opt/lib:$LD_LIBRARY_PATH

[ -f "/usr/lib/locale/locale-archive" ] || /usr/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
LANGVAR=`/usr/bin/locale | grep LANG | cut -f 2 -d "="`
[ "x${LANGVAR}" != x ] || export LANG=en_US.UTF-8

case "$1" in
	start)
		[ -d /root/.pyload ] || /bin/ln -sf $QPKG_DIR /root/.pyload

		[ -d ${BASE}/${DOWNLOAD_SHARE}/pyload ] || /bin/mkdir -p ${BASE}/${DOWNLOAD_SHARE}/pyload
		[ -d ${QPKG_DIR}/data/Downloads ] || /bin/ln -sf ${BASE}/${DOWNLOAD_SHARE}/pyload ${QPKG_DIR}/data/Downloads

	  /bin/echo "Starting pyLoad"	  
	  ${QPKG_DIR}/opt/bin/python2.5 ${QPKG_DIR}/pyLoadCore.py --daemon  
	;;
	stop)
		/bin/echo "Stopping pyLoad"
		${QPKG_DIR}/opt/bin/python2.5 ${QPKG_DIR}/pyLoadCore.py --quit
		/bin/sleep 1
	;;
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

**Comment by GammaC0de** [comment]
OK,

I think I know the reason for this:
You are running pyload with python v2.5 (**OLD!**).

We can fix this issue with ReCaptcha.py but more issues can come in the future and because v2.5 is very old, so it is not recommended.

Other solution would be to install optware-ng (https://www.qnapclub.eu/en/qpkg/550)

**Comment by Bx15k0** [comment]
ok, i understand.
does it work with entware-ng also? i'm running this on my nas.
yes, the way with the "user-installation" is the way i will try.
for the first idea:
maybe you can run a check which version of python is running and so the way you "use" ReCaptcha.py" will decided on this output? so maybe for the users which do install pyload "my way" will not fail with this issue.

**Comment by GammaC0de** [comment]
> does it work with entware-ng also?

Yes

>maybe you can run a check which version of python is running and so the way you "use" ReCaptcha.py" will decided on this output? so maybe for the users which do install pyload "my way" will not fail with this issue.

Replace ReCaptcha.py with https://github.com/pyload/pyload/raw/stable/module/plugins/captcha/ReCaptcha.py  and it should now work.


As for pyload entware installation do
```
opkg update
opkg install python python-pip python-crypto python-curl python-openssl pillow tesseract js unrar
```

**Comment by Bx15k0** [comment]
Thank you,
i just tested your solution with the ReCaptcha.py and you are right, it works. 

But i will also make a clean install of pyload with entware.
But not today :-)

Thank you and happy new year 2019

**Comment by GammaC0de** [comment]
Happy new year :gift:
