### ISSUE TITLE
Low download speed with Pyload since major changes

### ISSUE THREAD

**Issue by 3x3cut0r** [pyload/pyload#3302]
Same issue like #2870 a good year ago ...
Low download speed since few weeks (major changes) on my DS918+ with pyload running in a Docker Container (writl/pyload:latest). 2MB/s on DS918+ ... 5-6MB/s (50Mbit/s connection) on MacBookPro ... with all File Hosters! (uploaded/share-online/keep2share tested)
Don't know if its a plugin or major issue.
Any suggestions?

PS: is it possible to reopen closed issues like #2870 ?

**Comment by GammaC0de** [comment]
@3x3cut0r It would be helpfull if you can test is on a regullar pyload installation without docker.

**Comment by 3x3cut0r** [comment]
Yes, its even on a nativ/regular installation without docker on my Synology and on my macbook in a virtualbox on ubuntu 16.04 and 18.04!

**Comment by GammaC0de** [comment]
> Yes, its even on a nativ/regular installation without docker

How exactly have you installed ןא?
 
What about installing using Entware?
https://github.com/Entware/Entware/wiki/Install-on-Synology-NAS

**Comment by GammaC0de** [comment]
> Yes, its even on a nativ/regular installation without docker

How exactly have you installed it?
 
What about installing using Entware?
https://github.com/Entware/Entware/wiki/Install-on-Synology-NAS

**Comment by 3x3cut0r** [comment]
Why should i try another "entware" installation?
I just installed the requirements (python stuff) and cloned and started it from github repo.
followed the setup and its done.
on my synology i installed it with a spk. 
on all installations i download not with full speed.
so i think it is not a installation issue ...

**Comment by GammaC0de** [comment]
> I just installed the requirements (python stuff)

OK, so how exactly have you done that?

**Comment by 3x3cut0r** [comment]
Same wise like in the dockerfile from writl/pyload:
`apt-get update && apt-get install -y python \
locales \
python-setuptools \
python-requests \
python-pycurl \
python-crypto \
python-imaging \ # <- on Ubuntu 18.04 python-pil
python-pyxmpp \
python-jinja2 \
python-thrift \
python-feedparser \
python-beautifulsoup \
python-pip \
tesseract-ocr \
python-beaker \
unrar \
curl \
gocr \
python-django \
git \
rhino \
gosu

git clone https://github.com/pyload/pyload.git /opt/pyload \
&& cd /opt/pyload

python pyLoadCore -s # <- done setup assistent
python pyLoadCore # <- after setup`

**Comment by GammaC0de** [comment]
I don't know what are all of those packages, pyload needs only  these packages:
python-pycurl
python-crypto
python-imaging
unrar
rhino
tesseract-ocr

**Comment by 3x3cut0r** [comment]
What ever ... why are you still believing this is an installation problem?
i think it has something to do with the major changes and/or the ul.to/so.com plugins!
a friend of mine has the exact same problem on a different DS, with different internet connection.

**Comment by GammaC0de** [comment]
>why are you still believing this is an installation problem

pyload uses pycurl for downloading, I cannot do anything to speed up downloading.

>a friend of mine has the exact same problem on a different DS

So you prove that this issue is specific to synology, maybe the native python or one of the python packages have a bug?

Please try installing using Entware, you have nothing to lose, the worst case you delete the /opt directory.

Another thing I would like you to try is to install pyload on a regular computer (preferably with Linux OS) and test what speed do you get.

**Comment by 3x3cut0r** [comment]
I installed it with Entware on my synology. the download speed is even worse ... around 1mb/s instead of 5-6mb/s
i only have a macbookpro so i cant / wont install ubuntu nativ on that. but as i said i installed it on a ubuntu virtual machine. the download speed there is also low.
i installed it now on so many different systems and OSes that it cannot be a synology specific bug.
you say pyload uses pycurl for downloading. maybe there is a bug?
i found some similar threads with low download speed in other software on google related to pycurl.

what can i do now? there is no similar software like pyload out there exept of jdownloader2 which is crap using it over a webfrontent.

**Comment by GammaC0de** [comment]
What speed do you get with this url?
http://releases.ubuntu.com/18.04.1/ubuntu-18.04.1-desktop-amd64.iso


This is what I get:

![capture](https://user-images.githubusercontent.com/11036551/50851037-4d991680-1384-11e9-9a09-1bd8c28980fa.PNG)

**Comment by 3x3cut0r** [comment]
for some reason i get an error O_o
failed 'getpwnam(): name not found: admin' 0.00 B BasePlugin

**Comment by GammaC0de** [comment]
Closing since the root of this issue is not pyload, sorry.
