### ISSUE TITLE
No Capcha displayed with SSL enabled

### ISSUE THREAD

**Issue by klauswitt** [pyload/pyload#3305]
Hello,

with SSL enabled, no capcha will be shown in the popup.
only:
`The captcha may take a few seconds to load.

Note: to solve this interactive captchas
Please install the Tampermonkey add-on in your browser and add the pyload userscript.`

With SSL disabled everything works fine.

The configuration ist the same, except SSL on/off

With apache reverse proxy it shows the same behavior:
pyload (without ssl) -> apache http -> working
pyload (without ssl) -> apache https -> not working

installed version from: https://github.com/pyload/pyload/issues/3283
server: threaded

can this issue be related to Tampermonkey or pyload?

regards
Klaus

**Comment by GammaC0de** [comment]
This is a browser limitation with [mixed active content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default). When you use https for pyload and the hoster only uses http, the browser (e.g. firefox) blocks this request. You might have to stop blocking mixed content: https://kb.iu.edu/d/bdny

**Comment by GammaC0de** [comment]
@klauswitt Which browser are you using?

**Comment by klauswitt** [comment]
> @klauswitt Which browser are you using?

I'm using Firefox.

"stop blocking mixed content" is working for me
But if you will find a better solution, i would prefer it

**Comment by GammaC0de** [comment]
>"stop blocking mixed content" is working for me

:+1: 

>But if you will find a better solution, i would prefer it

In a second thought, the only solution that _might_ work is a special webextention, but that seems to not going to happen in the near future.
