### ISSUE TITLE
[Plugin Request] InCloudDrive

### ISSUE THREAD

**Issue by 3fey3ugf** [pyload/pyload#3306]
Could you please add support for InCloudDrive premium accounts.
```
https://www.inclouddrive.com/file/nARc9MhEvBSOOsheyhzACg/20190104-epl-review-eng-720p.mkv
```

**Comment by GammaC0de** [comment]
I'm sorry but I tried a couple of time and I really cannot download anything from inclouddrive.com even with a regular web browser like Firefox or Internet explorer :disappointed:

**Comment by 3fey3ugf** [comment]
@GammaC0de I'm using JDownloader 2 and it downloaded just fine.

Here is link to inclouddrive plugin for JDownloader:
https://github.com/mirror/jdownloader/blob/master/src/jd/plugins/hoster/InCloudDriveCom.java

**Comment by GammaC0de** [comment]
I'm sorry but for me even JDownloader fails to download - it gives "server error 401" error message.
