### ISSUE TITLE
Premiumize.me is outdated

### ISSUE THREAD

**Issue by nshtg** [pyload/pyload#3308]
Premiumize.me plugin is very oudated. Api used was legacy and support was dropped 01.12.2018.

Support for downloading from their cloud would be very nice, right now those just fallback to baseplugins which fails.

New api https://app.swaggerhub.com/apis-docs/premiumize.me/api/1.3

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

>Support for downloading from their cloud would be very nice, right now those just fallback to baseplugins which fails.

Can you please explain to a non Premiumize.me user what that means?

**Comment by GammaC0de** [comment]
@nshtg Any update?

**Comment by GammaC0de** [comment]
Will close if no response

**Comment by nshtg** [comment]
I can't share you my account, I'm sorry. Premiumize Cloud is a service where they offer to download e.g. torrents to their servers and you can download them from their later on.

**Comment by GammaC0de** [comment]
> I can't share you my account, I'm sorry.

Too bad :(
Since I don't have an account,I have no other option than close this. :(

Maybe another person would be willing to give the information in the future.
Until then, Premiumize is broken.
