### ISSUE TITLE
[RapidgatorNet] pycurl error 35: Unknown SSL protocol

### ISSUE THREAD

**Issue by FremdWelt** [pyload/pyload#3309]
Hi,
when trying to download from rapidgator the download fails with the following error message:

>12.01.2019 07:46:47 WARNING   HOSTER RapidgatorNet[416]: Plugin may be unstable
>12.01.2019 07:46:47 INFO      HOSTER RapidgatorNet[416]: Grabbing link info...
>12.01.2019 07:46:47 INFO      HOSTER RapidgatorNet[416]: Link name: cea8f5e23d24258ed14f7293c4e9391e
>12.01.2019 07:46:47 INFO      HOSTER RapidgatorNet[416]: Link size: N/D
>12.01.2019 07:46:47 INFO      HOSTER RapidgatorNet[416]: Link status: starte
>12.01.2019 07:46:47 INFO      HOSTER RapidgatorNet[416]: Processing url: https://rapidgator.net/file/cea8f5e23d24258ed14f7293c4e9391e
>12.01.2019 07:46:47 INFO      HOSTER RapidgatorNet[416]: Looking for direct download link...
>12.01.2019 07:46:47 ERROR     pycurl error 35: Unknown SSL protocol error in connection to rapidgator.net:443
>12.01.2019 07:46:47 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: cea8f5e23d24258ed14f7293c4e9391e (pid:10)
>12.01.2019 07:46:47 INFO      ADDON UnSkipOnFail: No duplicates found'

pycurl.version gives me this:
>'PycURL/7.43.1 libcurl/7.58.0 OpenSSL/1.0.2n zlib/1.2.11 c-ares/1.14.0 libssh2/1.8.0'

OS is Win10, Python version 3.7.
Thank you very much for your time and support!

**Comment by GammaC0de** [comment]
No issues for me.
You have to use python 2.7 with pyload, not 3.7.

**Comment by FremdWelt** [comment]
Ah, I was afraid that would be the issue. Thank you!

**Comment by FremdWelt** [comment]
I recently switched to Python 2.7 to get rid of the issues but unfortunately they persist. I also have the same issue with several other hosters, for example ddl.to. Please let me know which info you need.

**Comment by GammaC0de** [comment]
Can you please try disabling IPv6 on your windows machine and see if that helps?

**Comment by FremdWelt** [comment]
Okay, I tried that and still got the same error. Here's what I did in detail:
deactivated ipv6 in the control menu and restarted. Tried again with rapidgator and ddl.to, no change. Activated ipv6 support in my router and then in the control menu and restarted. Tried again with ddl.to and got the same error.
Thank you for your patience!

**Comment by FremdWelt** [comment]
Okay, after looking through the issues of other users this solved my problems for now: https://github.com/pyload/pyload/issues/3287#issuecomment-444321889
