### ISSUE TITLE
share-online.biz: log download server errors

### ISSUE THREAD

**Issue by lukastribus** [pyload/pyload#3310]
Hello!

a share-online.biz download server may refuse the download for multiple reasons. It does that by responding with a `301 Moved Permanently`, pointing to a location with the original download URL and appending specific error links:

* `/failure/ip` --> [multiple IPs are downloading](http://www.share-online.biz/dl/04KWKALPIZ0R/failure/ip)
* `/failure/expired` --> [download ticket expired](http://www.share-online.biz/dl/04KWKALPIZ0R/failure/expired)
* `/failure/precheck` --> [some checks failed (most likely client bug)](http://www.share-online.biz/dl/04KWKALPIZ0R/failure/precheck)

The HTTP transaction looks like this:
```
GET /dl?u=ABLABLABLAID&q=v4 HTTP/1.1
Host: dlw380-1.share-online.biz
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
Accept-Encoding: gzip, deflate
Referer: https://api.share-online.biz/account.php?...somedata
Cookie: <somecookies>
Accept: */*
Accept-Language: en-US,en
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Connection: keep-alive
Keep-Alive: 300

HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Sun, 13 Jan 2019 21:41:33 GMT
Transfer-Encoding: chunked
Connection: close
X-SO-Verify: <somerandomdata>
Location: http://www.share-online.biz/dl/04KWKALPIZ0R/failure/ip
```

If such a response occurs, pyload reverts to free user mode (ignoring the `Fallback to free download if premium fails` plugin setting).

Also, there is no indication in the log about that error.

Debug log of a successful download:
```
14.01.2019 00:32:53 INFO      HOSTER ShareonlineBiz[7243]: Downloading file...
14.01.2019 00:32:53 DEBUG     HOSTER ShareonlineBiz[7243]: DOWNLOAD URL http://dlw380-1.share-online.biz/dl?u=SOMESECRETID&q=v4 | fixurl=True | resume=None | get={} | cookies=True | disposition=True | chunks=None | post={} | ref=True
14.01.2019 00:32:53 DEBUG     Content-Disposition: ubuntu-18.04.1-desktop-amd64.iso
```

Debug log of a failed download reverting to free user mode:
```
14.01.2019 00:07:34 INFO      HOSTER ShareonlineBiz[7243]: Downloading file...
14.01.2019 00:07:34 DEBUG     HOSTER ShareonlineBiz[7243]: DOWNLOAD URL http://dlw380-1.share-online.biz/dl?u=<SOMESECRETID>&q=v4 | fixurl=True | resume=None | get={} | cookies=True | disposition=True | chunks=None | post={} | ref=True
14.01.2019 00:07:35 INFO      HOSTER ShareonlineBiz[7243]: File saved
14.01.2019 00:07:35 INFO      HOSTER ShareonlineBiz[7243]: Checking download...
14.01.2019 00:07:35 INFO      HOSTER ShareonlineBiz[7243]: File is OK
14.01.2019 00:07:35 DEBUG     HOSTER ShareonlineBiz[7243]: WAIT set to timestamp 1547421156.233153 | Previous waitUntil: 0.000000
14.01.2019 00:07:35 INFO      HOSTER ShareonlineBiz[7243]: Waiting 5 minutes...
```

There is no indication of an error, not even in debug mode.

Ideally we would:
* respect the `Fallback to free download if premium fails` plugin setting
* parse specific share-online.biz errors and report it in the log (multiple IPs downloading, download ticket expired, unkown precheck error, unknown error)

The latter I imagine is non-trivial, as it happens only at download stage, so it isn't handled in a shareonline specific code path.

However I would like for pyload to at least emit an clear error message (visible in standard logging) that the download server rejected the request. Maybe it could detect the 30X response headers or the `text/html` Content-Type in the subsequent request and emit a generic premium download failure statement in the log. Whatever triggers the free user download mode should also trigger a error message in the log.

Example DL:
`http://www.share-online.biz/dl/04KWKALPIZ0R`

Download from multiple IPs to trigger the `/failure/ip` redirect.

**Comment by GammaC0de** [comment]
@lukastribus You wrote a lot of things and it is unclear what the issues are..
I would appreciate if you summarize the issues in a small list, thanks.

**Comment by lukastribus** [comment]
I realize it's a large wall of text...

When the download server rejects a premium download I see the following issues:
* falls back to free mode, despite share-online plugin setting `Fallback to free download if premium fails` is disabled
* does not log the fact that the premium download failed

Expected behavior would be to only fall back to free user mode if that is allowed by plugin settings and actually log the fact that the premium download failed (which is an error). Even better would be to log the reason of the failure (based on the HTTP redirect destination).

hope this helps

**Comment by GammaC0de** [comment]
>When the download server rejects a premium download

Why would it reject a premium download?

> Expected behavior would be to only fall back to free user mode if that is allowed by plugin settings and actually log the fact that the premium download failed

This is exactly what is supposed to happen :confused:

**Comment by lukastribus** [comment]
In the specific example the download server refuses the download, because the account is already used on another IP, therefor it [redirects to an error site](http://www.share-online.biz/dl/04KWKALPIZ0R/failure/ip). pyload silently falls back to free-user mode without any indication of an error.

The entire point of this issue is to make at least a generic download error visible (in the log) and respect the `Fallback to free download if premium fails` setting.

**Comment by GammaC0de** [comment]
> In the specific example the download server refuses the download, because the account is already used on another IP

So there are more than one user that uses the same account?

I need an account to test, can you change your account password to a temporary password and sent it by mail to nitzo2001 at yahoo dot com?

**Comment by lukastribus** [comment]
Well 2 different source IP's, by mistake: I had another download running while trying to download with pyload from a different internet connection. I eventually understood the problem, and figured out that the pyload silently falls back to free mode. After you reproduce it, do go back to the first post of this issue as it contains some details about the server behavior.

I actually already tried sending your the credentials, but I can see that yahoo rejected the mail. You should have them now (or in a few minutes), please ping me back if you still did not get them. thanks.

**Comment by GammaC0de** [comment]
OK, I got the credentials.

**Comment by GammaC0de** [comment]
Hi, Can you please test?

**Comment by lukastribus** [comment]
Confirmed, HTML output is detected now:

```
INFO	HOSTER ShareonlineBiz[7243]: Processing as premium download...
INFO	HOSTER ShareonlineBiz[7243]: Checking download...
INFO	HOSTER ShareonlineBiz[7243]: File is OK
INFO	HOSTER ShareonlineBiz[7243]: Checking file (with built-in rules)...
WARNING	HOSTER ShareonlineBiz[7243]: Check result: Html file | Waiting 1 minute and retry
INFO	HOSTER ShareonlineBiz[7243]: Waiting 1 minutes... 
```


I imagine there is no way to actually detect the IP error, suggesting that in the error log message? This is actual a duplicate of #899

**Comment by GammaC0de** [comment]
@lukastribus Can you add the line
```
        self.log_warning("lastEffectiveURL=%s" % self.lastEffectiveURL)
```
before this: line https://github.com/pyload/pyload/blob/b556d06dd039393f4c02da6b9a8a3ac84eef2a32/module/plugins/hoster/ShareonlineBiz.py#L102
and then post the log when occurs?

**Comment by lukastribus** [comment]
I got `'ShareonlineBiz' object has no attribute 'lastEffectiveURL' ` so I used `self.req.lastEffectiveURL` instead:

```
WARNING | HOSTER ShareonlineBiz[7243]:  lastEffectiveURL=https://api.share-online.biz/account.php?username=638*******&lid=04KWKALPIZ0R&password=**********&act=download
```

**Comment by GammaC0de** [comment]
Hello,
Here is a HTTPS only ShareonlineBiz plugin.
[ShareonlineBiz.zip](https://github.com/pyload/pyload/files/2829907/ShareonlineBiz.zip)

**Comment by iceman64128** [comment]
688  | 09.02.2019 12:09:09 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
-- | -- | -- | --
687 | 09.02.2019 12:09:09 | ERROR | Error importing ShareonlineBiz: invalid syntax (ShareonlineBiz.py, line 102)
686 | 09.02.2019 12:09:07 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
685 | 09.02.2019 12:09:07 | ERROR | Error importing ShareonlineBiz: invalid syntax (ShareonlineBiz.py, line 102)
684 | 09.02.2019 12:09:05 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
683 | 09.02.2019 12:09:05 | ERROR | Error importing ShareonlineBiz: invalid syntax (ShareonlineBiz.py, line 102)
682 | 09.02.2019 12:09:03 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
681 | 09.02.2019 12:09:03 | ERROR | Error importing ShareonlineBiz: invalid syntax (ShareonlineBiz.py, line 102)
680 | 09.02.2019 12:09:01 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
679 | 09.02.2019 12:09:01 | ERROR | Error importing ShareonlineBiz: invalid syntax (ShareonlineBiz.py, line 102)
678 | 09.02.2019 12:08:59 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'

Could this issue come from the plugin bug?

**Comment by GammaC0de** [comment]
@iceman64128 Is this a new installation?
Please open a new issue, thanks.

**Comment by lukastribus** [comment]
Pushing this up, so that stale[bot] does not close the issue. "feedback wanted" label is wrong.

**Comment by GammaC0de** [comment]
@lukastribus Can you change line 112 from:
```
m = re.search(r'/failure/(.*?)/', self.req.lastEffectiveURL)
```
to:
```
m = re.search(r'/failure/(.*?)/', self.req.lastEffectiveURL) or re.search(r'/failure/(.*?)/', self.data)
```

and then test?

**Comment by lukastribus** [comment]
Nice!

Instead of a generic:
```
INFO	HOSTER ShareonlineBiz[7243]: Processing as premium download...
INFO	HOSTER ShareonlineBiz[7243]: Downloading file...
INFO	HOSTER ShareonlineBiz[7243]: File saved
INFO	HOSTER ShareonlineBiz[7243]: Checking download...
INFO	HOSTER ShareonlineBiz[7243]: File is OK
INFO	HOSTER ShareonlineBiz[7243]: Checking file (with built-in rules)...
WARNING	HOSTER ShareonlineBiz[7243]: Check result: Html file | Waiting 1 minute and retry
INFO	HOSTER ShareonlineBiz[7243]: Waiting 1 minutes... 
```

I'm showing:
```
HOSTER ShareonlineBiz[7243]: Processing as premium download...
HOSTER ShareonlineBiz[7243]: Downloading file...
HOSTER ShareonlineBiz[7243]: File saved
HOSTER ShareonlineBiz[7243]: Checking download...
HOSTER ShareonlineBiz[7243]: File is OK
HOSTER ShareonlineBiz[7243]: ip< | The usage of different IPs is not possible!
HOSTER ShareonlineBiz[7243]: Waiting 1 minutes... 
```

Which is exactly what I need to know in the log to understand the issue!

**Comment by GammaC0de** [comment]
So this solve this issue then?

**Comment by lukastribus** [comment]
Yes, I confirm the issue is fixed with this, with the latest regex the log is:

```
HOSTER ShareonlineBiz[7243]: Downloading file...
HOSTER ShareonlineBiz[7243]: File saved
HOSTER ShareonlineBiz[7243]: Checking download...
HOSTER ShareonlineBiz[7243]: File is OK
HOSTER ShareonlineBiz[7243]: ip | The usage of different IPs is not possible!
HOSTER ShareonlineBiz[7243]: Waiting 1 hours...
```

**Comment by lukastribus** [comment]
Thanks for this!
