### ISSUE TITLE
addPackage API function seems broken

### ISSUE THREAD

**Issue by Igglybuff** [pyload/pyload#3311]
Hi,

I'm trying to use the pyLoad API to send a URL to pyLoad for it to download.

```
session = self.connect()
info(self.silence, 'Sending URL to pyLoad...')
package_name = self.l.rsplit('/')

headers = {
    'Content-Type': 'application/json',
}

params = (
    ('name', package_name[-1]),
    ('links', self.l),
)

session.post(self.url + '/api/addPackage', headers=headers, params=params)
```

`self.l` is a working URL to a file. The `/api/addPackage` API endpoint returns raw HTML asking me to fill in a captcha. When I try to add the same URL from the web interface, I am not asked to fill in a captcha. This happens even for YouTube links. I've tried adding additional headers in case I'm missing something there, but that didn't help.

Why does an API endpoint require filling in a captcha? Am I doing something wrong? `/api/getQueue` works fine :thinking: 

Thanks :)

EDIT: Some more info from my pyLoad logs

When attempting to name the package for the YouTube link to `watch?v=VP1uTgikarU` I see this:

```
Traceback (most recent call last):
  File "/opt/pyload/module/web/api_app.py", line 62, in call_api
    return callApi(func, *args, **kwargs)
  File "/opt/pyload/module/web/api_app.py", line 74, in callApi
    **dict([(x, literal_eval(y)) for x, y in kwargs.iteritems()]))
  File "/opt/pyload/module/lib/SafeEval.py", line 44, in const_eval
    c = test_expr(expr, _const_codes)
  File "/opt/pyload/module/lib/SafeEval.py", line 33, in test_expr
    raise ValueError, "%s is not a valid expression" % expr
ValueError: watch?v=VP1uTgikarU is not a valid expression
```
Changing the package name to `test` resulted in this error:
```
Traceback (most recent call last):
  File "/opt/pyload/module/web/api_app.py", line 62, in call_api
    return callApi(func, *args, **kwargs)
  File "/opt/pyload/module/web/api_app.py", line 74, in callApi
    **dict([(x, literal_eval(y)) for x, y in kwargs.iteritems()]))
  File "/opt/pyload/module/lib/SafeEval.py", line 44, in const_eval
    c = test_expr(expr, _const_codes)
  File "/opt/pyload/module/lib/SafeEval.py", line 39, in test_expr
    raise ValueError, "opcode %s not allowed" % dis.opname[code]
ValueError: opcode LOAD_NAME not allowed
```

**Comment by GammaC0de** [comment]
http://IP:PORT/api/addPackage?name="test"&links=["https://github.com/foo"]

**Comment by Igglybuff** [comment]
Thanks, I managed to get it to work by adding the square brackets. It might be good to include your example above in the [API wiki page](https://github.com/pyload/pyload/wiki/module.Api.Api), and similar examples for all of the API functions documented there. Perhaps with `curl` command examples :slightly_smiling_face:
