### ISSUE TITLE
Unable to reorder the items of download queue

### ISSUE THREAD

**Issue by MrcRel** [pyload/pyload#3314]
If I use the "pyplex" or "modern" web interface and try to reorder the items of download queue I get the "failed" error message (I tried every web server available in the configuration menu), instead if I use the "classic" web interface I can reorder the items of the download queue.

OS: Ubuntu 18.04 
JavaScript engine: libmozjs-52

**Comment by GammaC0de** [comment]
Yes I know,
I'm currently investigating this.
