### ISSUE TITLE
HOSTER EasybytezCom[968]: Plugin may be unstable

### ISSUE THREAD

**Issue by SunYangLeo** [pyload/pyload#3317]
Hello, I'm a new user from Italy.
I started to download with Pyload to my Nas Asustor but since yesterday I received this error LOG 
when I try to download with my premium easybytez account:

975 | 25.01.2019 10:11:07 | INFO | Added package Dark crimes containing 52 links
-- | -- | -- | --
976 | 25.01.2019 10:11:08 | INFO | Download starts: http://www.easybytez.com/azwqbvptdrof
977 | 25.01.2019 10:11:08 | WARNING | HOSTER EasybytezCom[965]: Plugin may be unstable
978 | 25.01.2019 10:11:08 | WARNING | Download failed: http://www.easybytez.com/azwqbvptdrof \| 'NoneType' object has no attribute 'get_info'
979 | 25.01.2019 10:11:08 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: http://www.easybytez.com/azwqbvptdrof (pid:22)
980 | 25.01.2019 10:11:08 | INFO | ADDON UnSkipOnFail: No duplicates found
981 | 25.01.2019 10:11:10 | INFO | Download starts: http://www.easybytez.com/6yuoif3r6x4u
982 | 25.01.2019 10:11:10 | WARNING | HOSTER EasybytezCom[966]: Plugin may be unstable
983 | 25.01.2019 10:11:10 | WARNING | Download failed: http://www.easybytez.com/6yuoif3r6x4u \| 'NoneType' object has no attribute 'get_info'
984 | 25.01.2019 10:11:10 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: http://www.easybytez.com/6yuoif3r6x4u (pid:22)
985 | 25.01.2019 10:11:10 | INFO | ADDON UnSkipOnFail: No duplicates found
986 | 25.01.2019 10:11:12 | INFO | Download starts: http://www.easybytez.com/otuc9wavl2gd
987 | 25.01.2019 10:11:12 | WARNING | HOSTER EasybytezCom[967]: Plugin may be unstable
988 | 25.01.2019 10:11:12 | WARNING | Download failed: http://www.easybytez.com/otuc9wavl2gd \| 'NoneType' object has no attribute 'get_info'
989 | 25.01.2019 10:11:12 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: http://www.easybytez.com/otuc9wavl2gd (pid:22)
990 | 25.01.2019 10:11:12 | INFO | ADDON UnSkipOnFail: No duplicates found
991 | 25.01.2019 10:11:14 | INFO | Download starts: http://www.easybytez.com/ft33dheakjs1
992 | 25.01.2019 10:11:14 | WARNING | HOSTER EasybytezCom[968]: Plugin may be unstable
993 | 25.01.2019 10:11:14 | WARNING | Download failed: http://www.easybytez.com/ft33dheakjs1 \| 'NoneType' object has no attribute 'get_info'
994 | 25.01.2019 10:11:14 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: http://www.easybytez.com/ft33dheakjs1 (pid:22)
995 | 25.01.2019 10:11:14 | INFO | ADDON UnSkipOnFail: No duplicates found

I tried to download with JD2 the same files and everything works.

Thanks for all your help!!

SYL

**Comment by GammaC0de** [comment]
Is this a new installation?

**Comment by GammaC0de** [comment]
No response, EasybytezCom works fine for me.
Closing.
