### ISSUE TITLE
Convert https into http links?

### ISSUE THREAD

**Issue by mkrsn** [pyload/pyload#3319]
Hi all,
after adding a new package full of HTTPS-Links, pyload is using HTTP instead (tcpdump confirmes this).

I'm wondering why pyload seems to convert HTTPS into HTTP links. Is this as designed?

Greetings
mkrsn

**Comment by GammaC0de** [comment]
@mkrsn This is probably because some old plugin.

What URLs have you used? 
Are the from the same hoster? which one?

**Comment by mkrsn** [comment]
I'm using the stable-branch - last pull yesterday. While starting, pyload reports that all plugins are up to date.

> 30.01.2019 18:59:33 INFO      ADDON UpdateManager: pyLoad is up to date!
> 30.01.2019 18:59:33 INFO      ADDON UpdateManager: All plugins are up to date!

This is happening with every share-online Link. Following an example for http://www.share-online.biz/dl/68E8S5MP4L

debug-Log: https://pastebin.com/raw/qJqt0uV9

**Comment by GammaC0de** [comment]
Ok, you are correct.
The plugin uses this pattern for URL matching:
```
 __pattern__ = r'https?://(?:www\.)?(share-online\.biz|egoshare\.com)/(download\.php\?id=|dl/)(?P<ID>\w+)'
```
and replaces it with:
```
URL_REPLACEMENTS = [(__pattern__ + ".*", "http://www.share-online.biz/dl/\g<ID>")]
```

So the byproduct of replacing the complex URL pattern is the conversion of  HTTPS into HTTP.

**Comment by mkrsn** [comment]
hmm... it's up to you. If you think this is not necessary i'll fix it for my own.

Generally speaking, the most User are doing "Backups" of stuff with pyload. Keeping this in mind, everything should be encrypted to keep unwanted eyes away...

And generally it is a good idea of encrypt the whole traffic - why not? it's free of Charge :)

**Comment by GammaC0de** [comment]
OK, I will do the change for ShareonlineBiz.
But changing all the plugins and then testing that they are not broken - this is too much hassle, pyload has more important bugs that needs fixing.

**Comment by GammaC0de** [comment]
> ShareOnline offers a http and https link and advertise the http as the fast download link...

So in other words, what you say is that HTTP is faster then HTTPS?

**Comment by mkrsn** [comment]
Good Morning,

it's what ShareOnline advertised. But this is bullshit.

**Comment by GammaC0de** [comment]
Hello,
Here is a HTTPS only ShareonlineBiz plugin.
[ShareonlineBiz.zip](https://github.com/pyload/pyload/files/2829930/ShareonlineBiz.zip)

**Comment by mkrsn** [comment]
Thanks. Unfortunately the download is still using HTTP

> 04.02.2019 23:04:32 DEBUG     HOSTER ShareonlineBiz[104]: LOAD URL https://api.share-online.biz/account.php | redirect=True | cookies=True | get={'username': '**********', 'lid': '3X********', 'password': '**********', 'act': 'download'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
> 04.02.2019 23:04:32 DEBUG     HOSTER ShareonlineBiz[104]: STATUS: online
> URL: http://dlw259-2.share-online.biz/dl?u=<snipp>&q=v4
> ID: 3X*******
> NAME: ****************.part060.rar
> SIZE: 268435457
> MD5: 02c3****************
> 04.02.2019 23:04:32 INFO      HOSTER ShareonlineBiz[104]: Downloading file...
> 04.02.2019 23:04:32 DEBUG     HOSTER ShareonlineBiz[104]: DOWNLOAD URL http://dlw259-2.share-online.biz/dl?u=<snipp>&q=v4 | fixurl=True | resume=None | get={} | cookies=True | disposition=True | chunks=None | post={} | ref=True

**Comment by GammaC0de** [comment]
Try this:
[ShareonlineBiz.zip](https://github.com/pyload/pyload/files/2830022/ShareonlineBiz.zip)

**Comment by mkrsn** [comment]
This now works - tcpdump confirmes: no HTTP at all

> 04.02.2019 23:24:29 DEBUG     HOSTER ShareonlineBiz[109]: LOAD URL https://api.share-online.biz/account.php | redirect=True | cookies=True | get={'username': '**********', 'lid': 'C8597DUOSHE', 'password': '**********', 'act': 'download'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
> 04.02.2019 23:24:29 DEBUG     HOSTER ShareonlineBiz[109]: STATUS: online
> URL: http://dlw354-1.share-online.biz/dl?u=********************4&q=v4
> ID: ********************
> NAME: ********************.part065.rar
> SIZE: 268435457
> MD5: ********************
> 04.02.2019 23:24:29 INFO      HOSTER ShareonlineBiz[109]: Downloading file...
> 04.02.2019 23:24:29 DEBUG     HOSTER ShareonlineBiz[109]: DOWNLOAD URL https://dlw354-1.share-online.biz/dl?u=********************&q=v4 | fixurl=True | resume=None | get={} | cookies=True | disposition=True | chunks=None | post={} | ref=True

The only issue is that the Debug-output is now wrong - see URL above. But main-target accomplished :) Thanks!

**Comment by GammaC0de** [comment]
> The only issue is that the Debug-output is now wrong - see URL above 

This is just what the request to https://api.share-online.biz/account.php returns, just ignore it.
