### ISSUE TITLE
688  | 09.02.2019 12:09:09 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'

### ISSUE THREAD

**Issue by iceman64128** [pyload/pyload#3323]
688  | 09.02.2019 12:09:09 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
-- | -- | -- | --
687 | 09.02.2019 12:09:09 | ERROR | Error importing ShareonlineBiz: invalid syntax (ShareonlineBiz.py, line 102)
686 | 09.02.2019 12:09:07 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
685 | 09.02.2019 12:09:07 | ERROR | Error importing ShareonlineBiz: invalid syntax (ShareonlineBiz.py, line 102)
684 | 09.02.2019 12:09:05 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
683 | 09.02.2019 12:09:05 | ERROR | Error importing ShareonlineBiz: invalid syntax (ShareonlineBiz.py, line 102)
682 | 09.02.2019 12:09:03 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
681 | 09.02.2019 12:09:03 | ERROR | Error importing ShareonlineBiz: invalid syntax (ShareonlineBiz.py, line 102)
680 | 09.02.2019 12:09:01 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'
679 | 09.02.2019 12:09:01 | ERROR | Error importing ShareonlineBiz: invalid syntax (ShareonlineBiz.py, line 102)
678 | 09.02.2019 12:08:59 | CRITICAL | 'NoneType' object has no attribute 'ShareonlineBiz'

Could this issue come from the plugin bug?

_Originally posted by @iceman64128 in https://github.com/pyload/pyload/issues/3310#issuecomment-462035484_

**Comment by iceman64128** [comment]
No new install

**Comment by GammaC0de** [comment]
Which python version are you using? (go to `http://<PYLOAD_IP>/info` and see)

**Comment by GammaC0de** [comment]
I recommend you to upgrade from python 2.5 to python 2.7

**Comment by iceman64128** [comment]
Python 2.7.3 is installed, but pyload still seems to use 2.5.5.... how do I change that?

Thanks

**Comment by GammaC0de** [comment]
What hardware are you using?
How exactly do you start pyload?

**Comment by iceman64128** [comment]
HW is a QNAP - TS 459. I think it starts as a service.

**Comment by GammaC0de** [comment]
The issue is that QNAP's qpyload package is not and official pyload package and is bundled with python 2.5.

**Comment by iceman64128** [comment]
.... and there is no work around?

**Comment by GammaC0de** [comment]
The package maintainer is Stéphane Guérithault (https://fr-fr.facebook.com/stephane.guerithault), you could try your luck and contact him.

Another way could be install pyload using Entware https://github.com/Entware/Entware/wiki/Install-on-QNAP-NAS
