### ISSUE TITLE
9kw.eu interactive captcha solving behaving strange

### ISSUE THREAD

**Issue by NorfolkXX** [pyload/pyload#3324]
Hello,

I use 9kw.eu to solve interactive captcha and also the stable branche installed january 26th, 2019.

Worked like a charm until around early january 2019, so I downloaded and installed a new stable version on january 26th 2019, but this didnt help eighter. Unfortunately, I cannot pinpoint it, but my impression is that only about 1 out of 100 captchas get sent to 9kw to be solved. It usually looks that way: pyload fetches the credits from 9kw and displays the correct credit-value, but after that it seems like pyload is waiting ages but there's no solving. at the same time, I cannot track the captcha at 9kw. If i check the 9kw history pages regarding submitted captchas, it tells me as if I have submitted about 1-2 captchas evere few days, while in reality, my pyload tries to get about 20-30 captchas solved each day.

I tried checking logs, debug, settings, but until now, i have not found any hint on whats going on. 

Any idea? Or also: does it work for you or anyone else?

**Comment by GammaC0de** [comment]
@NorfolkXX if you go to http://www.9kw.eu/grafik/servercheck.txt you will see that the queue sis something above 100.
So what that means that there are more then 100 users waiting for answer, which means 9kw has some server issues...
