### ISSUE TITLE
7-Zip cannot find the code that works with archives

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#3325]
Hello, need your support please

Extracting fails
in userplugins ExtractArchive.py version -> 1.68
passwords are given by password file

```
12.02.2019 21:42:59	DEBUG	ADDON ExternalScripts: No script found under folder `package_extract_failed`
12.02.2019 21:42:59	ERROR	ADDON ExtractArchive: xxx.part1.rar | Extract failed
12.02.2019 21:42:59	DEBUG	ADDON ExternalScripts: No script found under folder `archive_extract_failed`
? 	?	7-Zip cannot find the code that works with archives.
12.02.2019 21:42:59	ERROR	ADDON ExtractArchive: xxx.part1.rar | Archive error | ERROR:
12.02.2019 21:42:59	DEBUG	EXTRACTOR SevenZip: EXECUTE 7z x -bso0 -bsp1 -aoa -xr!*.nfo -xr!*.DS_Store -xr!index.dat -xr!thumb.db -p- -o/share/Multimedia/Serien/_downloaded/ /share/Download/Pyload/truedetectiveDLHD3 - serienjunkies.org/4sj-true-detective-s03e05-720p.part1.rar
12.02.2019 21:42:59	DEBUG	ADDON ExtractArchive: Extracting using password: None
12.02.2019 21:42:59	DEBUG	EXTRACTOR SevenZip: EXECUTE 7z l -bso0 -bsp1 -aoa -xr!*.nfo -xr!*.DS_Store -xr!index.dat -xr!thumb.db -p- -slt /share/Download/Pyload/truedetectiveDLHD3 - serienjunkies.org/4sj-true-detective-s03e05-720p.part1.rar
12.02.2019 21:42:59	DEBUG	ADDON ExtractArchive: Password: None provided
12.02.2019 21:42:59	INFO	ADDON ExtractArchive: xxx.rar | Extract to: /share/_downloaded/
12.02.2019 21:42:59	DEBUG	ADDON ExtractArchive: Targets for SevenZip: [(1030, '/share/yyy - xxx.part1.rar', '/share/yyy/')]
12.02.2019 21:42:59	ERROR	ADDON ExtractArchive: xxx.part1.rar | Extract failed
12.02.2019 21:42:58	DEBUG	ADDON ExternalScripts: No script found under folder `archive_extract_failed`
12.02.2019 21:42:58	ERROR	ADDON ExtractArchive: 4sj-true-detective-s03e05-720p.part1.rar | No password found
```

**Comment by GammaC0de** [comment]
URL and password please

**Comment by UserX404** [comment]
did you get the links?
answered directly via email. No clue if it work that way.

**Comment by GammaC0de** [comment]
Sorry I got no email from you.

My address is  nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
OK, email received.

**Comment by Mister-XY** [comment]
Have you also installed the p7zip-rar bin to extract rar archive?

**Comment by UserX404** [comment]
not to my knowledge
shouldn't it be handled by unrar?

1736 | 13.02.2019 05:50:26 | DEBUG | ADDON ExtractArchive: Found HjSplit 0.01 \| Found UnRar 5.61 \| Found SevenZip 16.02 \| Found UnZip 2.7.15 \| Found UnTar 2.7.15
-- | -- | -- | --

by the way.... other multipackage archives (partX.rar) were handled correctly but several are are skipped by this error.

another misbehaviour i'm not sure about...
If a package has been finished and a previous package in queue is still uncomplete, it looks like the finished one isn't triggered to extract.

**Comment by GammaC0de** [comment]
Sorry for late respose but downloading but free download a 1GB file from sare-online takes 5+ hours...

`ExtractArchive` sucessfully unpacked the password protected file using unrar v5.61:
```
16.02.2019 19:24:02 DEBUG     ADDON ExtractArchive: Found HjSplit 0.01 | Found UnRar 5.61 | Found SevenZip 18.05 | Found UnZip 2.7.12 | Found UnTar 2.7.12
.
.
.
16.02.2019 19:41:38 INFO      Package finished: 3325
16.02.2019 19:41:38 DEBUG     ADDON ExternalScripts: No script found under folder `package_finished`
16.02.2019 19:41:38 DEBUG     ADDON ExtractArchive: Use for extensions: .001|.7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
16.02.2019 19:41:38 INFO      ADDON ExtractArchive: Check package: 3325
16.02.2019 19:41:39 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
16.02.2019 19:41:39 DEBUG     All downloads processed
16.02.2019 19:41:39 DEBUG     ADDON ExtractArchive: Targets for UnRar: [(2170, 'Downloads\\3325\\4sj-true-detective-s03e05-720p.part1.rar', 'Downloads\\3325\\')]
16.02.2019 19:41:39 INFO      ADDON ExtractArchive: 4sj-true-detective-s03e05-720p.part1.rar | Extract to: Downloads\3325\
16.02.2019 19:41:39 DEBUG     ADDON ExtractArchive: Password: serienjunkies.org
16.02.2019 19:41:39 DEBUG     EXTRACTOR UnRar: EXECUTE C:\pyload-stable\UnRAR.exe l -o- -or -x*.DS_Store -xindex.dat -xthumb.db -y -pserienjunkies.org -kb -v Downloads\3325\4sj-true-detective-s03e05-720p.part1.rar
16.02.2019 19:41:39 DEBUG     ADDON ExtractArchive: Extracting using password: serienjunkies.org
16.02.2019 19:41:39 DEBUG     EXTRACTOR UnRar: EXECUTE C:\pyload-stable\UnRAR.exe x -o- -or -x*.DS_Store -xindex.dat -xthumb.db -y -pserienjunkies.org -kb Downloads\3325\4sj-true-detective-s03e05-720p.part1.rar Downloads\3325\
16.02.2019 19:41:45 DEBUG     EXTRACTOR UnRar: EXECUTE C:\pyload-stable\UnRAR.exe v -o- -or -x*.DS_Store -xindex.dat -xthumb.db -y -pserienjunkies.org -kb -v Downloads\3325\4sj-true-detective-s03e05-720p.part1.rar
16.02.2019 19:41:45 DEBUG     ADDON ExtractArchive: Would delete: Downloads\3325\4sj-true-detective-s03e05-720p.part1.rar, Downloads\3325\4sj-true-detective-s03e05-720p.part2.rar
16.02.2019 19:41:45 INFO      ADDON ExtractArchive: Deleting 2 files
16.02.2019 19:41:48 INFO      ADDON ExtractArchive: 4sj-true-detective-s03e05-720p.part1.rar | Extracting finished
16.02.2019 19:41:48 DEBUG     ADDON ExtractArchive: Extracted files: ['Downloads\\3325\\4sj-true-detective-s03e05-720p.mkv']
16.02.2019 19:41:48 DEBUG     ADDON ExternalScripts: No script found under folder `archive_extracted`
16.02.2019 19:41:48 DEBUG     ADDON ExternalScripts: No script found under folder `package_extracted`
```

**Comment by GammaC0de** [comment]
> passwords are given by password file

Have you tried to check if it makes any difference if you put the password in the "password" field of the "add package" dialog?

**Comment by UserX404** [comment]
can be closed.
After re-download extracting worked as expected.
No idea what's going wrong at the first time :-/

**Comment by UserX404** [comment]
happened again

i noted password.txt get an empty line inserted at first line.
when i manually remove empty line (every line a password, correct?) empty line again gets inserted after package restart and extraction attempt.
When manually insert password to package and restart them, the archive get extracted.

474 | 17.02.2019 13:52:33 | INFO | Download skipped: 4sj-elementary-s06e14-720p.part2.rar due to File exists
-- | -- | -- | --
475 | 17.02.2019 13:52:33 | INFO | Package finished: 4sj-elementary-s06e14-720p
476 | 17.02.2019 13:52:33 | DEBUG | ADDON ExternalScripts: No script found under folder `package_finished`
477 | 17.02.2019 13:52:33 | DEBUG | ADDON ExtractArchive: Use for extensions:  .7z\|.bz2\|.bzip2\|.gz\|.gzip\|.lha\|.lzh\|.lzma\|.rar\|.tar\|.taz\|.tbz\|.tbz2\|.tgz\|.xar\|.xz\|.z\|.zip
478 | 17.02.2019 13:52:33 | INFO | ADDON ExtractArchive: Check package: 4sj-elementary-s06e14-720p
479 | 17.02.2019 13:52:33 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
480 | 17.02.2019 13:52:33 | DEBUG | All downloads processed
481 | 17.02.2019 13:52:33 | DEBUG | ADDON ExtractArchive: Targets for UnRar: [(1156,  '/share/Download/Pyload/4sj-elementary-s06e14-720p/4sj-elementary-s06e14-720p.part1.rar',  '/share/Multimedia/Serien/_downloaded/')]
482 | 17.02.2019 13:52:33 | INFO | ADDON ExtractArchive: 4sj-elementary-s06e14-720p.part1.rar \| Extract to: /share/Multimedia/Serien/_downloaded/
483 | 17.02.2019 13:52:33 | DEBUG | ADDON ExtractArchive: Password: None provided
484 | 17.02.2019 13:52:33 | DEBUG | EXTRACTOR UnRar: EXECUTE unrar l -o+ -x*.nfo -x*.DS_Store  -xindex.dat -xthumb.db -y -p- -v  /share/Download/Pyload/4sj-elementary-s06e14-720p/4sj-elementary-s06e14-720p.part1.rar
485 | 17.02.2019 13:52:33 | DEBUG | ADDON ExtractArchive: Extracting using password: None
486 | 17.02.2019 13:52:33 | DEBUG | EXTRACTOR UnRar: EXECUTE unrar x -o+ -x*.nfo -x*.DS_Store  -xindex.dat -xthumb.db -y -p-  /share/Download/Pyload/4sj-elementary-s06e14-720p/4sj-elementary-s06e14-720p.part1.rar  /share/Multimedia/Serien/_downloaded/
487 | 17.02.2019 13:52:50 | ERROR | ADDON ExtractArchive: 4sj-elementary-s06e14-720p.part1.rar \| No password found
488 | 17.02.2019 13:52:50 | DEBUG | ADDON ExternalScripts: No script found under folder `archive_extract_failed`
489 | 17.02.2019 13:52:50 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_finished`
490 | 17.02.2019 13:52:50 | DEBUG | All downloads finished
491 | 17.02.2019 13:52:50 | ERROR | ADDON ExtractArchive: 4sj-elementary-s06e14-720p.part1.rar \| Extract failed
492 | 17.02.2019 13:52:50 | DEBUG | ADDON ExtractArchive: Targets for SevenZip: [(1156,  '/share/Download/Pyload/4sj-elementary-s06e14-720p/4sj-elementary-s06e14-720p.part1.rar',  '/share/Multimedia/Serien/_downloaded/')]
493 | 17.02.2019 13:52:50 | INFO | ADDON ExtractArchive: 4sj-elementary-s06e14-720p.part1.rar \| Extract to: /share/Multimedia/Serien/_downloaded/
494 | 17.02.2019 13:52:50 | DEBUG | ADDON ExtractArchive: Password: None provided
495 | 17.02.2019 13:52:50 | DEBUG | EXTRACTOR SevenZip: EXECUTE 7z l -bso0 -bsp1 -aoa -xr!*.nfo  -xr!*.DS_Store -xr!index.dat -xr!thumb.db -p- -slt  /share/Download/Pyload/4sj-elementary-s06e14-720p/4sj-elementary-s06e14-720p.part1.rar
496 | 17.02.2019 13:52:50 | DEBUG | ADDON ExtractArchive: Extracting using password: None
497 | 17.02.2019 13:52:50 | DEBUG | EXTRACTOR SevenZip: EXECUTE 7z x -bso0 -bsp1 -aoa -xr!*.nfo  -xr!*.DS_Store -xr!index.dat -xr!thumb.db -p-  -o/share/Multimedia/Serien/_downloaded/  /share/Download/Pyload/4sj-elementary-s06e14-720p/4sj-elementary-s06e14-720p.part1.rar
498 | 17.02.2019 13:52:50 | ERROR | ADDON ExtractArchive: 4sj-elementary-s06e14-720p.part1.rar \| Archive error \| ERROR:
499 | ? | ? | 7-Zip cannot find the code that works with archives.
500 | 17.02.2019 13:52:50 | DEBUG | ADDON ExternalScripts: No script found under folder `archive_extract_failed`
501 | 17.02.2019 13:52:50 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_finished`
502 | 17.02.2019 13:52:50 | DEBUG | All downloads finished
503 | 17.02.2019 13:52:50 | ERROR | ADDON ExtractArchive: 4sj-elementary-s06e14-720p.part1.rar \| Extract failed
504 | 17.02.2019 13:52:50 | DEBUG | ADDON ExternalScripts: No script found under folder `package_extract_failed`
505 | 17.02.2019 13:52:50 | DEBUG | ADDON ExternalScripts: No script found under folder `all_archives_processed`

**Comment by UserX404** [comment]
sent you some furter files

**Comment by GammaC0de** [comment]
@UserX404 This issue happens only if you don't put a password in the add URL dialog and expect that the password would be in the `passwords.txt` file.

When those conditions are met, pyLoad iterates all the passwords in the `passwords.txt` file but fails to verify if the password is correct (it always picks the first one and fails)
Now I can't decide best way how to find the correct password from the `passwords.txt` file, more details tomorrow.

B.T.W,
Does your 7zip program is functional? try extracting some files from the commandline (see https://serverfault.com/questions/581377/7zip-command-line-cannot-find-code-that-works-with-archives)

**Comment by UserX404** [comment]
@GammaC0de Yes, those conditions are my regular usecase.
Packages password are not set and should be picked from passwords.txt

If i extracting via commandline, using unrar no errors are thrown.
Other packages also get extracted automatically and successfully (with those empty line in password file)

I never have used sevenzip on my system before. It seems to me it is not installed, but the package should be handled by unrar. Do you agree?

**Comment by GammaC0de** [comment]
> I never have used sevenzip on my system before. It seems to me it is not installed,

From the logsin https://github.com/pyload/pyload/issues/3325#issuecomment-463059026, it seems like you do have sevenzip installed:
```
1736 	13.02.2019 05:50:26 	DEBUG 	ADDON ExtractArchive: Found HjSplit 0.01 | Found UnRar 5.61 | Found SevenZip 16.02 | Found UnZip 2.7.15 | Found UnTar 2.7.15
```
But 7zip seems to be broken, the message `cannot find code that works with archives` comes from 7zip (see https://serverfault.com/questions/581377/7zip-command-line-cannot-find-code-that-works-with-archives)
This is why I wanted you to try to unpack the package using 7zip...

>but the package should be handled by unrar. Do you agree?

pyLoad will try to use all suitable unpackers available on the system. 
If one fails, it will try the next one.
pyload tries to use unrar before trying 7zip..
