### ISSUE TITLE
Nginx Reverse Proxy and Port change

### ISSUE THREAD

**Issue by gdomod** [pyload/pyload#3326]
i start pyload in a docker container with default port and local access
in next step i want to represent the pyload to nginx with reverse proxy and diferent port

`location /pyload {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://localhost:8000/pyload;

        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        access_log /var/log/nginx/pyload.access.log;
        error_log /var/log/nginx/pyload.error.log;

    }`

i change the url prefix to /pyload
 `webinterface - "Webinterface":
        bool activated : "Activated" = True
        ip host : "IP" = 0.0.0.0
        bool https : "Use HTTPS" = False
        int port : "Port" = 8000
        str prefix : "Path Prefix" = /pyload
        builtin;threaded;fastcgi;lightweight server : "Server" = builtin
        pyplex;classic;modern template : "Template" = pyplex`

but i get a redirection from 
https://domain:**nginx_port**/pyload to

**http://domain/pyload/login**
they cut away the custom **nginx_port**

**Comment by GammaC0de** [comment]
@gdomod I think that if you change pyload's webinterface port use nginx_port then it should work..

**Comment by gdomod** [comment]
Not possible because the Port is allready in use.

Am Mi., 13. Feb. 2019, 19:49 hat GammaC0de <notifications@github.com>
geschrieben:
