### ISSUE TITLE
Slashes missing when moving packages

### ISSUE THREAD

**Issue by m125** [pyload/pyload#3332]
Like in the tile that's the problem.
Slashes missing when moving package from collector to queue.
I'm useing modern and pyplex.

**Comment by GammaC0de** [comment]
Can you please explain what do you mean?

**Comment by m125** [comment]
Ok sure.
I have links in the linkcollector and specify a target folder. 

> stuff/things

and if I transfer them to the queue the slash is missing in the folder path like

> stuffthings

I can make some pictures if I can't explain it enough.

**Comment by GammaC0de** [comment]
>  and specify a target folder

Where exactly do you specify a target folder?

**Comment by m125** [comment]
That's the target folder:
> Bilder/Holland

**Comment by GammaC0de** [comment]
I asked Where do you specify (where do you enter) the target folder, not where is the target folder...

**Comment by GammaC0de** [comment]
Well?

**Comment by shoopdawoop** [comment]
I just gave it a try as I think I've had this issue before, so I created a new Package and entered `TEST/LALA` in the Name field, added it to Collector, then moved it to the Queue and the link downloaded alright but got put into a folder named `TEST_LALA`. That's perfectly fine I guess, but being able to use subfolders here would sure be a nice to have feature.

**Comment by m125** [comment]
> I just gave it a try as I think I've had this issue before, so I created a new Package and entered TEST/LALA in the Name field, added it to Collector, then moved it to the Queue and the link downloaded alright but got put into a folder named TEST_LALA. That's perfectly fine I guess, but being able to use subfolders here would sure be a nice to have feature.

That's my problem

> I asked where do you specify (where do you enter) the target folder, not where is the target folder... Please do.

I specify the target folder in the settings on and in the collector

![Bildschirmfoto 2019-03-10 um 12 37 35](https://user-images.githubusercontent.com/27641994/54084488-7ceee400-4331-11e9-9512-37e00bdbdb9c.png)
![Bildschirmfoto 2019-03-10 um 12 38 08](https://user-images.githubusercontent.com/27641994/54084489-7ceee400-4331-11e9-8578-83bcbbb0bd69.png)

**Comment by GammaC0de** [comment]
>so I created a new Package and entered TEST/LALA in the Name field

It was not designed to be used that way..
As the dialog states, it is the package **Name**, not folder.

But if you really must, you can change this line https://github.com/pyload/pyload/blob/stable/module/Api.py#L324 although I cannot guarantee the results...

**Comment by karl34** [comment]
Ive also encountered this problem and found this quick fix:
Delete the save_path call at https://github.com/pyload/pyload/blob/stable/module/PyPackage.py#L42

BUT BEWARE: This solution might be insecure since every path can be entered for saving downloads, im far too lazy to produce or look for a fitting path sanitizing function.

**Comment by GammaC0de** [comment]
I think this thread has run its course, closing.
