### ISSUE TITLE
Easybytez plugin problem

### ISSUE THREAD

**Issue by asdrubale1970** [pyload/pyload#3333]
hi
i have this error

Premium decrypted link found | Plugin may be out of date

help me please
thanks

**Comment by asdrubale1970** [comment]
7 | 03.03.2019 11:22:26 | INFO | Decrypting starts: http://www.easybytez.com/users/xxx/xxx/1xx
-- | -- | -- | --
8 | 03.03.2019 11:22:26 | DEBUG | CRYPTER EasybytezComFolder[1]: Plugin version: 0.17
9 | 03.03.2019 11:22:26 | DEBUG | CRYPTER EasybytezComFolder[1]: Plugin status: testing
10 | 03.03.2019 11:22:26 | WARNING | CRYPTER EasybytezComFolder[1]: Plugin may be unstable
11 | 03.03.2019 11:22:26 | INFO | CRYPTER EasybytezComFolder[1]: Grabbing link info...
12 | 03.03.2019 11:22:26 | DEBUG | CRYPTER EasybytezComFolder[1]: Link info: {'status': 2, 'hash': {}, 'name': 'xx', 'url': u'http://www.easybytez.com/xxx/xxx/xxx/xx?&per_page=10000', 'pattern': {'N': u'xxx'}, 'size': 0}
13 | 03.03.2019 11:22:26 | DEBUG | CRYPTER EasybytezComFolder[1]: Previous link info: {}
14 | 03.03.2019 11:22:26 | INFO | CRYPTER EasybytezComFolder[1]: Link name: xxxx
15 | 03.03.2019 11:22:26 | INFO | CRYPTER EasybytezComFolder[1]: Link size: N/D
16 | 03.03.2019 11:22:26 | INFO | CRYPTER EasybytezComFolder[1]: Link status: online
17 | 03.03.2019 11:22:26 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
18 | 03.03.2019 11:22:26 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
19 | 03.03.2019 11:22:26 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
20 | 03.03.2019 11:22:26 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
21 | 03.03.2019 11:22:26 | INFO | CRYPTER EasybytezComFolder[1]: Processing url: http://www.easybytez.com/xxx/xxx/xx/xxx
22 | 03.03.2019 11:22:26 | ERROR | Decrypting failed: xxx\| Required account not found

**Comment by asdrubale1970** [comment]
sorry link is corrupted
other link works

**Comment by GammaC0de** [comment]
So all is OK!?
