### ISSUE TITLE
UpdateManager: Unable to connect to the server to retrieve updates 

### ISSUE THREAD

**Issue by geronimoronin** [pyload/pyload#3334]
DEBUG | ADDON UpdateManager: LOAD URL  http://updatemanager-spyload.rhcloud.com \| redirect=True \| cookies=True \|  get={'v': '0.4.9'} \| req=None \| decode=True \| multipart=False \| post={}  \| ref=True \| just_header=False
-- | --
917 | 05.03.2019 09:47:58 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_start`
918 | 05.03.2019 09:47:58 | WARNING | ADDON UpdateManager: Unable to connect to the server to retrieve updates

**Comment by OzzieIsaacs** [comment]
#3283

**Comment by GammaC0de** [comment]
What he said ...  :point_up:

Closing..
