### ISSUE TITLE
Wondering about features

### ISSUE THREAD

**Issue by D4R4** [pyload/pyload#3339]
Hello,
I was wondering if pyLoad supports these two features:
1. For the API addPackage function to accept a large list of URLs as a remote txt file or any other type of input.
2. For the Downloader to create a recursive pathing and perfect directory layout for a file list input to maintain. Like:
https://test.com/d1/d2/d3.bin
saved to ./Downloads/d1/d2/d3.bin

**Comment by GammaC0de** [comment]
1. you can upload a .txt file containing a list of URLs
2. Pyload is not designed to be used that way.
It uses the concept of packages: it creates a subfolder under the download folder and  all the URLs of that package are downloaded to this folder.
