### ISSUE TITLE
FileJoker login not working

### ISSUE THREAD

**Issue by abowen319** [pyload/pyload#3340]
Hi guys,

i want to add my filejoker premium account to pyload but it seems that it's not working.

`

76 | 14.03.2019 15:59:40 | INFO | ACCOUNT FilejokerNet: Adding user `x-k*******`...
-- | -- | -- | --
77 | 14.03.2019 15:59:40 | DEBUG | ACCOUNT FilejokerNet: Reached login timeout for user `x-k*******`
78 | 14.03.2019 15:59:40 | INFO | ACCOUNT FilejokerNet: Login user `x-k*******`...
79 | 14.03.2019 15:59:40 | DEBUG | ACCOUNT FilejokerNet: LOAD URL http://www.filejoker.net/login.html \|  redirect=True \| cookies=True \| get={} \| req=None \| decode=True \|  multipart=False \| post={} \| ref=True \| just_header=False
80 | 14.03.2019 15:59:40 | DEBUG | ACCOUNT FilejokerNet: LOAD URL http:///login \| redirect=True \|  cookies=True \| get={} \| req=None \| decode=True \| multipart=False \|  post={u'redirect': '', u'rand': '', 'login': 'x-k*******', u'password':  '**********', u'email': '', u'op': u'login'} \| ref=True \|  just_header=False
81 | 14.03.2019 15:59:40 | ERROR | ACCOUNT FilejokerNet: Could not login user `x-k*******` \| (6, 'Could not resolve host: login')

`

I tried to login with mail adress and customer id but both times it failed.

I can provide account informations.

best regards

**Comment by GammaC0de** [comment]
> 6, 'Could not resolve host: login

It seems that you have DNS / internet issues...

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by mjimeneznet** [comment]
I have the same problem, I've tested it 3 computers in 2 different networks.

My pyload is running in a docker inside a QNAP.

**Comment by GammaC0de** [comment]
@mjimeneznet 
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by mjimeneznet** [comment]
> @mjimeneznet
> Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

Credentials sent.

**Comment by GammaC0de** [comment]
Fixed with https://github.com/pyload/pyload/commit/00974c8c8e691d22c8c62aeff7f3baf8ec2b197e

Sorry it took so long but better late than never :no_mouth:
