### ISSUE TITLE
[Question] API: Get package ID by name

### ISSUE THREAD

**Issue by D4R4** [pyload/pyload#3343]
I have an app which feeds AddPackage calls to pyLoad via the API already, It specifies a name + an array of URLs to be downloaded,
I want to check for an existing package with the same "name" attribute and delete it if it already exists via the API. I believe I have to use the DeletePackage method if it exists which only responds to PIDs or Package IDs.
How can I query the pyLoad API to check if a package with an existing name already exists or not and how to delete it only by knowing the name?

**Comment by GammaC0de** [comment]
Package names are not unique, you can have multiple packages with the same name...

Use `getQueue()` API to get the queued packages ids and names.
