### ISSUE TITLE
Premium.to not recognized

### ISSUE THREAD

**Issue by 157760** [pyload/pyload#3344]
It seems that Premium.to wont get recognized.
Account added with status premium (and traffic left) adding link of supported hoster (Uptobox) the wrong plugin gets selected

`

1085 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Link status: starting
-- | -- | -- | --
1086 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Processing url: https://uptobox.com/XXX
1087 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Checking for link errors...
1088 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| No errors found
1089 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Grabbing link info...
1090 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Link name: XXX
1091 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Link size: N/D
1092 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Link status: starting
1093 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Processing as free download...
1094 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Checking for link errors...
1095 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| No errors found
1096 | 22.03.2019 17:29:48 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Waiting 1 seconds...
1097 | 22.03.2019 17:29:50 | INFO | Download restarted: lrxf6m9g1m8j \| TEXTAREA F1 not found
1098 | 22.03.2019 17:29:51 | INFO | Download starts: XXX
1099 | 22.03.2019 17:29:51 | WARNING | HOSTER XFileSharing[4]: UptoboxCom \| Plugin may be unstable
1100 | 22.03.2019 17:29:51 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Grabbing link info...
1101 | 22.03.2019 17:29:51 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Link name: XXX
1102 | 22.03.2019 17:29:51 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Link size: N/D
1103 | 22.03.2019 17:29:51 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Link status: starting
1104 | 22.03.2019 17:29:51 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Processing url: https://uptobox.com/XXX
1105 | 22.03.2019 17:29:52 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Checking for link errors...
1106 | 22.03.2019 17:29:52 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| No errors found
1107 | 22.03.2019 17:29:52 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Grabbing link info...
1108 | 22.03.2019 17:29:52 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Link name: xxx
1109 | 22.03.2019 17:29:52 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Link size: N/D
1110 | 22.03.2019 17:29:52 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Link status: starting
1111 | 22.03.2019 17:29:52 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Processing as free download...
1112 | 22.03.2019 17:29:52 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| Checking for link errors...
1113 | 22.03.2019 17:29:52 | INFO | HOSTER XFileSharing[4]: UptoboxCom \| No errors found
1114 | 22.03.2019 17:29:52 | WARNING | HOSTER XFileSharing[4]: UptoboxCom \| Free download failed \| Max retries reached
1115 | 22.03.2019 17:29:52 | WARNING | Download failed: XXX \| Max retries reached
1116 | 22.03.2019 17:29:52 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: lrxf6m9g1m8j (pid:4)
1117 | 22.03.2019 17:29:52 | INFO | ADDON UnSkipOnFail: No duplicates found
1118 | 22.03.2019 17:35:33 | CRITICAL | 'NoneType' object has no attribute 'group'

`

disable the XFileSharing leads to "failed'NoneType' object has no attribute 'group' 0.00 BXFileSharing" in Queue

**Comment by GammaC0de** [comment]
Please disable XFileSharing plugin and then remove and re-add the download package

**Comment by 157760** [comment]
Hello GammaC0de

Still not loading premium.to. Disabled xFileSharing and Uptobox and did process stop/Start.

23.03.2019 13:12:30	INFO	ACCOUNT PremiumTo: Adding user `157*******`...
17	23.03.2019 13:12:30	INFO	ACCOUNT PremiumTo: Login user `157*******`...
18	23.03.2019 13:12:30	INFO	ACCOUNT PremiumTo: Grabbing account info for user `157*******`...
19	23.03.2019 13:12:31	INFO	Activating Plugins...
20	23.03.2019 13:12:31	INFO	pyLoad is up and running
21	23.03.2019 13:12:31	INFO	ADDON UpdateManager: pyLoad is up to date!
22	23.03.2019 13:12:32	INFO	ADDON UpdateManager: All plugins are up to date!
23	23.03.2019 13:12:33	INFO	ACCOUNT PremiumTo: Hosters not overwritten: onefichier.com
24	23.03.2019 13:12:37	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
25	23.03.2019 13:21:49	INFO	Added package Test pto containing 1 links
26	23.03.2019 13:21:49	INFO	Download starts: https://uptobox.com/XXX
27	23.03.2019 13:21:49	WARNING	HOSTER UptoboxCom[6]: Plugin may be unstable
28	23.03.2019 13:21:49	INFO	HOSTER UptoboxCom[6]: Grabbing link info...
29	23.03.2019 13:21:50	INFO	HOSTER UptoboxCom[6]: Link somefile.mkv
30	23.03.2019 13:21:50	INFO	HOSTER UptoboxCom[6]: Link size: 611.64 MiB (641351024 bytes)
31	23.03.2019 13:21:50	INFO	HOSTER UptoboxCom[6]: Link status: online
32	23.03.2019 13:21:50	INFO	HOSTER UptoboxCom[6]: Processing url: https://uptobox.com/XXX
33	23.03.2019 13:21:50	INFO	HOSTER UptoboxCom[6]: Looking for direct download link...
34	23.03.2019 13:21:50	INFO	HOSTER UptoboxCom[6]: Direct download link not found
35	23.03.2019 13:21:51	INFO	HOSTER UptoboxCom[6]: Checking for link errors...
36	23.03.2019 13:21:51	INFO	HOSTER UptoboxCom[6]: Waiting 30 seconds...
37	23.03.2019 13:22:23	INFO	HOSTER UptoboxCom[6]: No errors found
38	23.03.2019 13:22:23	INFO	HOSTER UptoboxCom[6]: Processing as free download...
39	23.03.2019 13:22:23	INFO	HOSTER UptoboxCom[6]: Downloading file...

**Comment by GammaC0de** [comment]
Too bad that all the important parts are missing from your log :(
* The URL
* Have you logged in to PremiumTo successfully?

If you do not want to share this publically, you can the info to nitzo2001 at yahoo dot com.
Also, for testing it would be very helpful if  you also send the PremiumTo  account information:
 please set to a temporary password and then send account user and password to my email.

**Comment by 157760** [comment]
Login is successful. I see the Traffic left in the Account Tab.
Happens with all links that are ment to run my Premium.to. 

Check Mail for Login.

**Comment by GammaC0de** [comment]
I'm sorry but UptoboxCom seems to be unsupported:

You can see the supported hosters if you go to http://api.premium.to/api/hosters.php?username=<USERNAME>&password=<PASSWORD>

I even tried to download https://uptobox.com/ihqo5gq0h5fv from the "download" menu on the web site without success :(

**Comment by 157760** [comment]
Just checked on premium.to. No Premium Account available. Tried with oboom. Worked.
So i guess no pyload Problem.

Should have checked better.
Sorry for bothering you and thanks for showing me.

**Comment by GammaC0de** [comment]
:+1:
