### ISSUE TITLE
uptobox "Login handshake has failed"

### ISSUE THREAD

**Issue by SuissoNaBisso9** [pyload/pyload#3345]
Hi
I tried to connect my Uptobox premium account with both username and email but none of them is working !
See the log below

Thanks

369	23.03.2019 11:43:29	INFO	ADDON UpdateManager: All plugins are up to date!
370	23.03.2019 11:43:35	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
371	23.03.2019 11:44:07	INFO	ACCOUNT UptoboxCom: Updating account info for user `Sui*******`...
372	23.03.2019 11:44:07	INFO	ACCOUNT UptoboxCom: Relogin user `Sui*******`...
373	23.03.2019 11:44:07	ERROR	ACCOUNT UptoboxCom: Could not login user `Sui*******` | Login handshake has failed
374	23.03.2019 11:44:07	INFO	ACCOUNT UptoboxCom: Updating account info for user `Sui*******`...
375	23.03.2019 11:44:07	INFO	ACCOUNT UptoboxCom: Relogin user `Sui*******`...
376	23.03.2019 11:44:07	ERROR	ACCOUNT UptoboxCom: Could not login user `Sui*******` | Login handshake has failed
377	23.03.2019 11:44:13	INFO	ACCOUNT UptoboxCom: Updating account info for user `Sui*******`...
378	23.03.2019 11:44:13	INFO	ACCOUNT UptoboxCom: Relogin user `Sui*******`...
379	23.03.2019 11:44:13	ERROR	ACCOUNT UptoboxCom: Could not login user `Sui*******` | Login handshake has failed
380	23.03.2019 11:44:13	INFO	ACCOUNT UptoboxCom: Removing user `Sui*******`...
381	23.03.2019 11:44:40	INFO	ACCOUNT UptoboxCom: Adding user `tho*******`...
382	23.03.2019 11:44:40	INFO	ACCOUNT UptoboxCom: Login user `tho*******`...
383	23.03.2019 11:44:40	ERROR	ACCOUNT UptoboxCom: Could not login user `tho*******` | Login handshake has failed
384	23.03.2019 11:44:50	INFO	ACCOUNT UptoboxCom: Updating account info for user `tho*******`...
385	23.03.2019 11:44:50	INFO	ACCOUNT UptoboxCom: Relogin user `tho*******`...
386	23.03.2019 11:44:51	ERROR	ACCOUNT UptoboxCom: Could not login user `tho*******` | Login handshake has failed
387	23.03.2019 11:44:51	INFO	ACCOUNT UptoboxCom: Updating account info for user `tho*******`...
388	23.03.2019 11:44:51	INFO	ACCOUNT UptoboxCom: Relogin user `tho*******`...
389	23.03.2019 11:44:51	ERROR	ACCOUNT UptoboxCom: Could not login user `tho*******` | Login handshake has failed
390	23.03.2019 11:47:48	INFO	ACCOUNT UptoboxCom: Updating account info for user `tho*******`...
391	23.03.2019 11:47:48	INFO	ACCOUNT UptoboxCom: Relogin user `tho*******`...
392	23.03.2019 11:47:49	ERROR	ACCOUNT UptoboxCom: Could not login user `tho*******` | Login handshake has failed
393	23.03.2019 11:47:49	INFO	ACCOUNT UptoboxCom: Updating account info for user `tho*******`...
394	23.03.2019 11:47:49	INFO	ACCOUNT UptoboxCom: Relogin user `tho*******`...
395	23.03.2019 11:47:49	ERROR	ACCOUNT UptoboxCom: Could not login user `tho*******` | Login handshake has failed
396	23.03.2019 11:48:41	INFO	ACCOUNT UptoboxCom: Updating account info for user `tho*******`...
397	23.03.2019 11:48:41	INFO	ACCOUNT UptoboxCom: Relogin user `tho*******`...
398	23.03.2019 11:48:42	ERROR	ACCOUNT UptoboxCom: Could not login user `tho*******` | Login handshake has failed
399	23.03.2019 11:48:42	INFO	ACCOUNT UptoboxCom: Removing user `tho*******`...
400	23.03.2019 11:48:59	INFO	ACCOUNT UptoboxCom: Adding user `Sui*******`...
401	23.03.2019 11:48:59	INFO	ACCOUNT UptoboxCom: Login user `Sui*******`...
402	23.03.2019 11:49:00	ERROR	ACCOUNT UptoboxCom: Could not login user `Sui*******` | Login handshake has failed

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by SuissoNaBisso9** [comment]
login info sent

**Comment by GammaC0de** [comment]
Hi,
The account  seems to work fine for me..

is this a new installation?

**Comment by SuissoNaBisso9** [comment]
ok don't know why but it's now working fine ! but have another issue, the file dowloaded is being renamed with random name et file extension is removed, any solution for that ?

**Comment by GammaC0de** [comment]
Please restore the temporary password so I can check if there is anything that can be done..

**Comment by SuissoNaBisso9** [comment]
ok done, same password as you had

**Comment by GammaC0de** [comment]
I have disabled the direct downloads feature on the uptobox  web site and now it works fine.

**Comment by SuissoNaBisso9** [comment]
ok cool thanks for your help !

**Comment by GammaC0de** [comment]
:+1:

**Comment by Haldir31** [comment]
Hello,

I try to configure Pyload with UptoboxCom premium account but i get the same error described above. I try to disable the direct download but i still have in the log, the following error:

33 | 05.08.2019 23:26:17 | ERROR | ACCOUNT UptoboxCom: Could not login user `hal*******` \| Login handshake has failed
-- | -- | -- | --
34 | 05.08.2019 23:28:16 | ERROR | ADDON ClickNLoad: [Errno 98] Address already in use

I have the same account set in Download Station for Synology and able to download as Premium without issue.

Thanks

**Comment by GammaC0de** [comment]
@Haldir31 Please open a new issue, thanks.
