### ISSUE TITLE
Unable to connect to my server from Android app

### ISSUE THREAD

**Issue by SuissoNaBisso9** [pyload/pyload#3346]
Hi

Just tried to connect my Android app with remote server.
Well added IP address, correct port, username and password but I have an error message "connection timed out, check your server settings"

What should I do ?

**Comment by GammaC0de** [comment]
The Android App uses different port from the WebUI, usually  port 7227

You can check for the line `Starting ThriftBackend:` on the log file to verify.

**Comment by GammaC0de** [comment]
No response, closing.
