### ISSUE TITLE
Upyobox plugin failing 'NoneType' object has no attribute 'get_info'

### ISSUE THREAD

**Issue by JeanMars** [pyload/pyload#3347]
Hi,

just to report that current UptoboxCom hoster fails:

2973 | 24.03.2019 22:40:50 | WARNING | Download failed: https://uptobox.com/8cf2j7ikvhrb \| 'NoneType' object has no attribute 'get_info'
-- | -- | -- | --
2974 | 24.03.2019 22:40:50 | INFO | Debug Report written to debug_UptoboxCom_24-03-2019_22-40-50.zip
2975 | 24.03.2019 22:40:50 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: https://uptobox.com/8cf2j7ikvhrb (pid:244)
 
Something should be wrong with expected data vs data returned by uptobox.

**Comment by GammaC0de** [comment]
It seems that your pyload installation is broken,
Is this a new installation?

**Comment by JeanMars** [comment]
No, it's a pretty old one and 1fichier is working well

**Comment by GammaC0de** [comment]
Please read https://github.com/pyload/pyload/issues/3283

**Comment by JeanMars** [comment]
Works fine now, many thanks !

**Comment by GammaC0de** [comment]
:+1:
