### ISSUE TITLE
How to change Download Folder in Qnap

### ISSUE THREAD

**Issue by totofroto** [pyload/pyload#3348]
i cant change to hard disk in qnap, as you can see down
Python: | 2.7.14 (default, Jan 10 2018, 14:55:03) [GCC 6.3.0]
-- | --
OS: | posix linux2 Linux Libya 3.4.6 #1 Wed Jan 2 10:32:43 CST 2019 armv5tel
pyLoad version: | 0.4.9
Installation Folder: | /share/HDA_DATA/.qpkg/Entware-ng/share/pyload
Config Folder: | /share/HDA_DATA/.qpkg/Entware-ng/var/pyload
Download Folder: | /mnt/sda1/downloads
Free Space: | 15.46 MiB
Language: | en
Webinterface Port: | 8000
Remote Interface Port: | 7227

**Comment by totofroto** [comment]
i am suffering... please help me

**Comment by GammaC0de** [comment]
On the WebUI choose config -> general -> Download Folder

**Comment by totofroto** [comment]
Thanks for reply
The HDD is not showing up
Config..general.. here you see only what in qnap folders..my HDD still  unseen

**Comment by GammaC0de** [comment]
Just enter the path manually, do not try to browse

**Comment by totofroto** [comment]
I did but still in qnap memory

**Comment by GammaC0de** [comment]
> I did but still in qnap memory

Sorry, I do not understand what do you mean.

Maybe  this is a permissions issue..

**Comment by totofroto** [comment]
Can you write the correct path for me please

**Comment by GammaC0de** [comment]
Sorry, I do not own a Qnap

**Comment by totofroto** [comment]
How to deal with permission issue

**Comment by totofroto** [comment]
pyLoad - Webinterface

An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/share/HDA_DATA/.qpkg/Entware-ng/share/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/share/HDA_DATA/.qpkg/Entware-ng/share/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/share/HDA_DATA/.qpkg/Entware-ng/share/pyload/module/web/pyload_app.py", line 528, in info
"freespace": formatSize(PYLOAD.freeSpace()),
File "/share/HDA_DATA/.qpkg/Entware-ng/share/pyload/module/Api.py", line 238, in freeSpace
return freeSpace(self.core.config["general"]["download_folder"])
File "/share/HDA_DATA/.qpkg/Entware-ng/share/pyload/module/utils.py", line 112, in freeSpace
s = statvfs(folder)
OSError: [Errno 2] No such file or directory: '\t/share/HDA_DATA/.qpkg/pyload/data/Downloads

**Comment by GammaC0de** [comment]
Why `\t/share/HDA_DATA/.qpkg/pyload/data/Downloads`?
It probably should be `/share/HDA_DATA/.qpkg/pyload/data/Downloads`

**Comment by totofroto** [comment]
System
Python:	2.7.14 (default, Jan 10 2018, 14:55:03) [GCC 6.3.0]
OS:	posix linux2 Linux Libya 3.4.6 #1 Wed Jan 2 10:32:43 CST 2019 armv5tel
pyLoad version:	0.4.9
Installation Folder:	/share/HDA_DATA/.qpkg/Entware-ng/share/pyload
Config Folder:	/share/HDA_DATA/.qpkg/Entware-ng/var/pyload
Download Folder:	/share/HDA_DATA/.qpkg/pyload/data/Downloads
Free Space:	2.60 TiB
Language:	en
Webinterface Port:	8000
Remote Interface Port:	7227

**Comment by totofroto** [comment]
Perfect....you saved my life
Thanks alot

**Comment by GammaC0de** [comment]
:+1:
 :hugs:
