### ISSUE TITLE
No JS Engine

### ISSUE THREAD

**Issue by 157760** [pyload/pyload#3351]
Hi, i cant get pyload to find the JS engine.

I installed js2py by using pip. No success. So i unistalled. Now i installed entware and tried with js and duktape package. No success either. I unistalled and took js package instead. Pyload keeps unable to find js. Always rebooted after a change

System says:
[root@DNS-320]# which js
/opt/bin/js

[root@DNS-320]# echo $PATH
/bin:/sbin:/usr/bin:/usr/sbin:/opt/bin:/opt/sbin:/ffp/bin:/ffp/sbin

so i dont understand why pyload wont find js engine.

Entering js directly works fine.

js> help()
JavaScript-C 1.6 pre-release 1 2006-04-04 (OSSP js 1.6.20070208)

**Comment by GammaC0de** [comment]
Please follow the instrunctions in https://github.com/pyload/pyload/issues/3283 and then retry.

**Comment by 157760** [comment]
Did the Job. Thought i read everything related to this issue. Seems like i missed the working solution. Thanks.

**Comment by GammaC0de** [comment]
:+1:
