### ISSUE TITLE
Wrong scheme in login redirection

### ISSUE THREAD

**Issue by yannouchou** [pyload/pyload#3352]
Pyload redirects to `/login` using the correct host name (even when behind a proxy), but the wrong scheme.
It always uses http even when the proxy is https.
So when I visit **https**://mydomain.com/pyload unauthenticated, Pyload sends a HTTP 303 redirect to **http**://mydomain.com/pyload/login
My server supports both http and https on the same domain so when using Pyload standalone it "works" (if you consider serving a _login_ page in clear http to be 'working'... but luckily my proxy then redirects again to https), but this is an issue when I'm using Pyload embedded in an iFrame (inside Organizr), since the iFrame security context prevents loading of any unsecure resources (my proxy doesn't even get a chance to redirect since the resource is not even called and cannot return an http 301 redirect to the https equivalent). So I end up on a blank page...

This happens even when setting some of the usual proxy headers:
```
X-Scheme               https
X-Forwarded-Ssl     on
X-Forwarded-Proto  https
```

Strange since somehow it seems it respects the `X-Forwarded-For` header to determine the original hostname (?)...

**Comment by GammaC0de** [comment]
I really could not follow what you are saying..
If you use HTTPS proxy then you probably have to configure pyload to use SSL too..

**Comment by yannouchou** [comment]
The flow is:
```
Browser --https://mydomain.com/pyload--> Proxy --http://localhost/pyload--> pyload
```

This allows me to manage TLS settings, authentication (with SSO with Google/Facebook etc), certificate provisioning for my domain etc only once at the proxy level.

Pyload handles properly all the URL link building using the proper scheme and domain, so all links and resources correctly point to https://mydomain.com/pyload/... as a base URL, except for the login redirection, which correctly uses the request's original domain (mydomain.com) even though Pyload receives it as localhost, but not the original scheme (always uses http even when the original call is made to https).

I guess I could try using https from proxy to pyload as well, but that's really just a workaround for what is really a bug. In any case since the proxy would call pyload on localhost, the domain wouldn't match the certificate so I'd have to disable certificate validation, meaning it wouldn't really be secure anyway.

Here's the HTTP trace to illustrate what's wrong. You can see that the original call is http**s** but the 303 redirection to `/login` is plain http.

![image](https://user-images.githubusercontent.com/1210752/55203784-3b01e100-51ff-11e9-8e54-30f39aa991ad.png)

The following redirect switches back to https, but this one is issued by my proxy. This flow works standalone but not in a secure iframe since the plain http call will be blocked by the browser.

**Comment by ohaucke** [comment]
You should configure your proxy to rewrite the location header, this isn't a pyload issue.
"proxy_redirect http://imediacenter.org https://imediacenter.org;"

**Comment by yannouchou** [comment]
Indeed a **workaround** would be the rewrite the downstream Location header, but Pyload sending a 301 redirect to a different scheme than the original query is still undeniably a bug and presumably easily fixable - Pyload already uses the correct domain so we're halfway there, presumably by honoring the `X-Forwarded-For` request header.

I've thought about this but this workaround is not possible for me right now since I'm using Caddy, which doesn't support downstream header rewriting - at least until [this PR](https://github.com/mholt/caddy/pull/2144) is released.

**Comment by GammaC0de** [comment]
pyLoad simply redierts to `/login` ([pyload_app.py#L248](https://github.com/pyload/pyload/blob/stable/module/web/pyload_app.py#L248)).
 
It is you that is sending a request to `http://<pyload_ip>/` and gets redirected to `/login`.
pyLoad cannot know that it is behind a proxy..

You can simply verify that if you monitor the requests on the pyload box with `tcpdump`.

**Comment by yannouchou** [comment]
Hmm, OK, I'm not very familiar with python web frameworks, so I'm not very sure what is going on here.
The code indeed seems to indicate a relative redirection, but my observation is that pyload returns an absolute URL in the `Location` header of the HTTP redirect. Here is a call made directly to the pyload HTTP entrypoint:

```
YannBook:mediacenter yann$ curl -v http://127.0.0.1:52497/pyload
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 52497 (#0)
> GET /pyload HTTP/1.1
> Host: 127.0.0.1:52497
> User-Agent: curl/7.54.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 303 See Other
< Date: Fri, 29 Mar 2019 14:14:21 GMT
< Server: WSGIServer/0.1 Python/2.7.6
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< Location: http://127.0.0.1:52497/pyload/login
< 
* Closing connection 0
```

You can see that this is not coming from my proxy since the `Server` response header is `WSGIServer/0.1 Python/2.7.6`.

Even clearer, the same call with a `Host` request header (and not the `X-Forwarded-For` header as I mistakenly mentioned earlier, since that one is to convey the original client IP, not the original host) also redirects to an absolute URL, but this time using the provided Host value as domain name:

```
YannBook:mediacenter yann$ curl -v http://127.0.0.1:52497/pyload -H "Host: mydomain.com"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 52497 (#0)
> GET /pyload HTTP/1.1
> Host: mydomain.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 303 See Other
< Date: Fri, 29 Mar 2019 14:15:18 GMT
< Server: WSGIServer/0.1 Python/2.7.6
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< Location: http://mydomain.com/pyload/login
< 
* Closing connection 0
```

So to conclude, the redirection URL is absolute and entirely controlled by Pyload or at least the web framework it uses, which properly honors the `Host` request header to construct the redirect URL, but not `X-Forwarded-Proto`.
I'm using the builtin server, not sure if this would affect this behavior.

If this is handled at the web framework level I can understand you may not be willing to spend too much time fixing this, if even possible, since I understand this may not affect too many users - and most of them may indeed have an acceptable workaround through rewriting of the `Location` header.

I can probably live with it, especially if #2814 (disabling authentication) ever gets implemented. I can see there was an old PR implementing it (together with LDAP authentication) in #1966... Any chance this can be considered?

**Comment by GammaC0de** [comment]
OK,
This issue comes from the external `bottle` framework.

To fix change [bottle.py#L1805](https://github.com/pyload/pyload/blob/stable/module/lib/bottle.py#L1805) to: `location = url`

**Comment by GammaC0de** [comment]
No response, closing.
