### ISSUE TITLE
[RealdebridTorrent] Multiple links handling

### ISSUE THREAD

**Issue by user4me** [pyload/pyload#3353]
Hi,

It seems that real-debrid can respond multiple links for an only one magnet/torrent file. Pyload seems to only download the first one. It shoulds downlaod all of them i guess.

Example of the JSON returned by the real-debrid API : 

`{"error":0,"total":"1","current_page":1,"last_page":1,"list":[{"id":"123456789","status":"2","server":"3","name":"ABCD","progress":100,"seeders":0,"speed":0,"txt":"","time":"1553330681","date":"23\/03\/2019 09:44:41","links":["https:\/\/real-debrid.com\/d\/AAAAA","https:\/\/real-debrid.com\/d\/BBBBB","https:\/\/real-debrid.com\/d\/CCCCC","https:\/\/real-debrid.com\/d\/DDDD"]}]}`

**Comment by GammaC0de** [comment]
>It seems that real-debrid can respond multiple links for an only one magnet/torrent file

Can you please explain what that means?

>Pyload seems to only download the first one

As far as I remember, pyload download all the file as one big zip file, no?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by user4me** [comment]
Hi, 

Sorry for the delay, I was not able to answer since,

When you submit a torrent containing multiple files, real-debrid may answer as many links as files in the torrent. And it's not managed by the RealdebridTorrent plugin.

Explanations : When Realdebrid receives a torrent it's able to recognize files inside the torrent or the torrent itself to avoid re-download/re-upload torrent again its side. 

Example : If two people downloaded two different files from a same torrent, two links would be generated by RD. If a person asks for thoses two files, RD has cached it so it would answer those two links to avoid re-download and re-upload.

I hope it clearer now

**Comment by GammaC0de** [comment]
I understand The fact that a torrents are being cached by real-debrid and it makes sense.
I would be disappointed if had not.

As for as I know, every torrent generates only one download link, one cannot download just one file from a torrent.

Am I missing something?

**Comment by user4me** [comment]
Yes, the point is that real-debrid can in some cases generates multiple links for one torrent.

I gave you the JSON I get from the real-debrid API for " /torrents/info/{id}" :

> {"error":0,"total":"1","current_page":1,"last_page":1,"list":[{"id":"123456789","status":"2","server":"3","name":"ABCD","progress":100,"seeders":0,"speed":0,"txt":"","time":"1553330681","date":"23\/03\/2019 09:44:41","**links**":["https:\/\/real-debrid.com\/d\/AAAAA","https:\/\/real-debrid.com\/d\/BBBBB","https:\/\/real-debrid.com\/d\/CCCCC","https:\/\/real-debrid.com\/d\/DDDD"]}]}

As you can notice the property inside the response is "links" and it's an array, not a simple string. In my case I had multiple links...

**Comment by GammaC0de** [comment]
If you want me to test this, account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
@user4me  The documentation specify that you can uses "all" as a parameter to `/torrents/selectFiles/{id}`   to select all the files but in reality it does not :(

**Comment by user4me** [comment]
Hi, 

Let's dive into code into the function `wait_for_server_dl` returns `torrent_info["links"][0]`. It has to be `torrent_info["links"]` to manage the multiple links that real debrid returns ;) ! Then we can iterate on it into `def process(self, pyfile)` and trigger `self.download_torrent(torrent_url)` as much as there is links for this torrent ;) !

**Comment by user4me** [comment]
#3403 I did the fix here, it should be tested, anyway i hope you'll understand by seeing the code

**Comment by GammaC0de** [comment]
Please provide a torrent URL for test

**Comment by user4me** [comment]
It should happen with that one : "magnet:?xt=urn:btih:66315ae24e949bd69c6315c8b2ae5a703542ba7e&dn=When.They.See.Us.S01.MULTi.720p.NF.WEB-DL.DD5.1.x264-ARK01"

**Comment by GammaC0de** [comment]
Fixed https://github.com/pyload/pyload/commit/4891a724f66b40ab4c306e2e686284b8b68b9450
