### ISSUE TITLE
Does Click'N'Load working on WebUI

### ISSUE THREAD

**Issue by ProTechEx** [pyload/pyload#3357]
Does Click'N'Load working on pyload WebUI ?

**Comment by GammaC0de** [comment]
Hello,
What do you mean? 
Cany you explain please?

**Comment by oltodosel** [comment]
For a few weeks I also had the plugin stop working (chromium). I stopped using it after finding plugin `HotFolder` more convenient.

**Comment by GammaC0de** [comment]
Closing.
