### ISSUE TITLE
Restart Webinterface seperately on crash

### ISSUE THREAD

**Issue by AlexOnFOSS** [pyload/pyload#3358]
Is it possible to implement a way to restart the webinterface automatically or manually?

Sometimes the webinterface crashes and I would like to be able to restart it in those cases without the need to restart the whole process (pyLoadCore.py).

**Comment by GammaC0de** [comment]
>Sometimes the webinterface crashes

You need so supply some debug info like Exception info..

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by AlexOnFOSS** [comment]
Sorry for my late response. 
I didn't want to find a fix for these rare webinterface crashes, I just wanted to know if i can restart the webinterface without restarting the whole pyload program.

**Comment by GammaC0de** [comment]
just close the browser tab and then open a new one.

**Comment by AlexOnFOSS** [comment]
this wouldn't help. As said, the webinterface / webserver crashed. Downloads were still active and running. But the webserver / webinterface crashed and there was nothing anymore listening on port 8000. Thats why i thought it would be nice to just relaunch the webinterface / webserver without having to restart whole pyload and aborting the active downloads.

**Comment by GammaC0de** [comment]
@AlexOnFOSS What OS are you using?
How can you tell that the webserver  has crashed? Is there an exception that occurs?

Try  running the setup wizard  (`pyLoadCore.py -s`) and switch the server backend, possibilities are "builtin", "threaded", "fastcgi" and "lightweight"

**Comment by AlexOnFOSS** [comment]
I am using:

Distributor ID:	Debian
Description:	Debian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch

4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux 

I realized that the webserver crashed because:

- i was not able to contact the ip:8000 website,

- using netstat - tulpen showed no entry for port 8000 anymore

- bmon showed downloadactivity

- ps -fe showed me that pyload was still running

- when bmon showed no more downloadactivity i found the finished downloaded files in the download directory. 

When i had that issue i was using Threaded as webserver with ssl support. 
Since a few weeks now i am using Builtin without ssl and did not experience the same error anymore.


Is there a way to restart the webinterface manually to be able to monitor pyload using the webbrowser in case something similar happens again in the future?

**Comment by GammaC0de** [comment]
> Is there a way to restart the webinterface manually

Sorry but no.

You could though run pyload with `pyLoadCore.py -d` to see if there is any exception occurs.
