### ISSUE TITLE
RealDebrid - "filter hoster list" - How to use for excluding hosts?

### ISSUE THREAD

**Issue by NorfolkXX** [pyload/pyload#3359]
Hello!

I cannot exclude a filehoster from the realdebrid.com-plugin - is there an example how it should work?

The multihoster-plugin works great for supported filehosters like rapidgator, but keep2share.cc is not supported and therefore I need to exclude it from realdebrid.com, or would recieve the error message "WARNING | Download failed: FILENAME \Bad server response: 503 Service Unavailable"

In the RealDebridCom-Plugin, I tried the following settings:
1) Hoster list (comma separated): Keep2ShareCC,k2scc,keep2share.cc,k2s.cc => also tried only one word like "keep2sharecc", "keep2share.cc", "k2scc", "k2s.cc" 
2) Filter hosters to use: listed / unlisted => I tried both versions, not knowing which is the correct one.

But whatever I tried at this settings, pyload always sent the k2s link to realdebrid and ofc this always resulted an error. Could you give an example what or how the settings should work? Or maybe it is a bug after all?

BTW: I have been using pyload for ages now, thank you for this great piece and the continuing support!

**Comment by GammaC0de** [comment]
"Hosters to use" should set to `unlisted`
"Hoster list (comma separated)" should include "Keep2ShareCc" (Which is the class name for the plugin and is case sensitive)

**Comment by NorfolkXX** [comment]
Unfortunately, there seems to be a bug after all - It is not working, but I also found something new during testing:

With your settings above ("Hoster list: Keep2ShareCc" + "unlisted"), I used a NitroflareCom-Link, just to verify if other filehosters are still working. Nitroflare is supported by RealDebrid and the download worked perfectly as premium download. 

Afterwards I changed "Hoster list: NitroflareCom,Keep2ShareCc" and used another NitroflareCom-Link again. Now it failed, with the log file showing the following:

`
11.04.2019 08:57:31 | INFO | HOSTER RealdebridCom[26]: RealdebridCom \| Processing as premium download...
-- | -- | --
201 | 11.04.2019 08:57:32 | INFO | HOSTER RealdebridCom[26]: RealdebridCom \| Downloading file...
202 | 11.04.2019 08:57:56 | WARNING | Download failed: FILENAME.XXX \| Bad server response: 503 Service Unavailable
`

Of course I tested Keep2ShareCc too, but always got the "Bad server response: 503". I would assume something broken at the RealDebit-plugin? 

Also as a sidenote: I could not find an option to disable RealDebit-plugin, I always have to remove and add the account data again to disable it. Did i just miss it?

Ty again :)

**Comment by GammaC0de** [comment]
This really sound weird, why would RealdebridCom report that is supports NitroflareCom and Keep2ShareCc if it does not?

If you want me to test this, please set your RealdebridCom  account to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by NorfolkXX** [comment]
As a sidenote, I have already noticed that some infos from RealDebrid are outdated and not accurate, after all I would think it it to be a rather cheap multihosting-service. 

For the RealDebrid-plugin, I think the option to exclude/include certain hosts should cause pyload not to use RealDebrid for those links at all, but directly access the respective filehoster instead - no matter if that excluded host would be supported by RealDebrid or not. 

pls check email.

**Comment by GammaC0de** [comment]
Before you buy an account, have you read https://github.com/pyload/pyload/issues/3283?

**Comment by NorfolkXX** [comment]
Yes, but #3283 didnt help. Sent account data to your inbox.
