### ISSUE TITLE
libcrypto.so.1.0.0 problem

### ISSUE THREAD

**Issue by cerealconyogurt** [pyload/pyload#3360]
I cannot run pyload anymore. Seems to me that pyload is using a old library dependencies for openssl. But not sure what happened since pyload was working few weeks ago. Any advice?

This is the message error:

  File "pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/tmp/mnt/NAS2/entware/share/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/tmp/mnt/NAS2/entware/share/pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/tmp/mnt/NAS2/entware/share/pyload/module/network/HTTPRequest.py", line 20, in <module>
    import pycurl
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by GammaC0de** [comment]
This seems like an entware issue, try updating/reinstalling pycurl

**Comment by cerealconyogurt** [comment]
Hi, I will try tomorrow. Now I am on the fly... thanks for the advice. I will let you know the outcome

**Comment by GammaC0de** [comment]
Hello,
Any update on this?

**Comment by cerealconyogurt** [comment]
Hi, I was trying to reinstall/upgrade pycurl last night but there is not package with that name in the repo. The repo that Entware is using is: http://bin.entware.net/armv7sf-k2.6/

So no sure what should be next step. I was searching any clue in google but no good so far... :-(

**Comment by GammaC0de** [comment]
Try issuing `opkg update && opkg upgrade`

**Comment by cerealconyogurt** [comment]
I will try that during the weekend...

**Comment by UserX404** [comment]
after updating Entware i ran into the same problem
[~] # /opt/etc/pyload/pyLoadCore.py --debug
Traceback (most recent call last):
  File "/opt/etc/pyload/pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/share/MD0_DATA/.qpkg/Entware/etc/pyload/module/network/HTTPRequest.py", line 21, in <module>
    import pycurl
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

seems it could be fixed after forced reinstall of pycurl
opkg install --force-reinstall python-curl

**Comment by GammaC0de** [comment]
>seems it could be fixed after forced reinstall of pycurl
opkg install --force-reinstall python-curl

Great :+1: , @cerealconyogurt can you confirm?

**Comment by cerealconyogurt** [comment]
> > seems it could be fixed after forced reinstall of pycurl
> > opkg install --force-reinstall python-curl
> 
> Great 👍 , @cerealconyogurt can you confirm?

The UserX404's advice worked!. Thanks both of you. I can recall that I had the same problem after updating Entware

**Comment by GammaC0de** [comment]
Great :grinning: 

Thanks @UserX404 .

Closing.
