### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by D4R4** [pyload/pyload#3361]
Hello,

I have around 30k Queue objects each with 1~200 links inside.
The current query from the CLI takes around 120 second to complete:
python pyLoadCli.py -u admin --pw='!@#' queue >> log.txt
Are there any recommendations on how to increase this speed?

**Comment by GammaC0de** [comment]
30,000 * 100(avrage) links = 3,000,000

What did you expect?

Leave alone the odd question why are you downloading 3M links..

**Comment by D4R4** [comment]
Sadly that's the current need for my current project.

**Comment by GammaC0de** [comment]
Sorry but I cannot do anything, closing.
