### ISSUE TITLE
keep2share broken

### ISSUE THREAD

**Issue by kveke** [pyload/pyload#3364]
Hi,
something has changed at k2s hoster, it pass captcha, wait time, but can't download file.
Thank in advance !

17.04.2019 19:24:17 INFO      Download starts: Sticky_Password_5.0.5.239.rar
17.04.2019 19:24:17 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
17.04.2019 19:24:17 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
17.04.2019 19:24:17 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
17.04.2019 19:24:17 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
17.04.2019 19:24:17 DEBUG     HOSTER Keep2ShareCc[19]: Plugin version: 0.43
17.04.2019 19:24:17 DEBUG     HOSTER Keep2ShareCc[19]: Plugin status: testing
17.04.2019 19:24:17 WARNING   HOSTER Keep2ShareCc[19]: Plugin may be unstable
17.04.2019 19:24:17 INFO      HOSTER Keep2ShareCc[19]: Grabbing link info...
17.04.2019 19:24:18 DEBUG     HOSTER Keep2ShareCc[19]: Link info: {'status': 2, 'hash': {}, 'name': u'Sticky_Password_5.0.5.239.rar', 'url': u'https://k2s.cc/file/10fae5648ecb2', 'pattern': {'ID': u'10fae5648ecb2'}, 'access': u'public', 'size': 11525752, 'md5': u'1826df6ef0eec9cafe32c7b5a9e55ec4'}
17.04.2019 19:24:18 DEBUG     HOSTER Keep2ShareCc[19]: Previous link info: {}
17.04.2019 19:24:18 INFO      HOSTER Keep2ShareCc[19]: Link name: Sticky_Password_5.0.5.239.rar
17.04.2019 19:24:18 INFO      HOSTER Keep2ShareCc[19]: Link size: 10.99 MiB (11525752 bytes)
17.04.2019 19:24:18 INFO      HOSTER Keep2ShareCc[19]: Link status: -
17.04.2019 19:24:18 INFO      HOSTER Keep2ShareCc[19]: Processing url: https://k2s.cc/file/10fae5648ecb2
17.04.2019 19:24:18 INFO      HOSTER Keep2ShareCc[19]: Looking for direct download link...
17.04.2019 19:24:18 DEBUG     HOSTER Keep2ShareCc[19]: LOAD URL https://k2s.cc/file/10fae5648ecb2 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
17.04.2019 19:24:20 INFO      HOSTER Keep2ShareCc[19]: Direct download link not found
17.04.2019 19:24:20 DEBUG     HOSTER Keep2ShareCc[19]: LOAD URL https://k2s.cc/file/10fae5648ecb2 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
17.04.2019 19:24:20 INFO      HOSTER Keep2ShareCc[19]: Checking for link errors...
17.04.2019 19:24:20 INFO      HOSTER Keep2ShareCc[19]: No errors found
17.04.2019 19:24:20 INFO      HOSTER Keep2ShareCc[19]: Processing as free download...
17.04.2019 19:24:23 DEBUG     CAPTCHA Keep2ShareCc[19]: Captcha | LOAD URL https://keep2share.cc/api/v2/captcha.html?id=1a1ab6a0b0283 | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0xffff8c6c79a8> | decode=False | multipart=False | post={} | ref=False | just_header=False
17.04.2019 19:24:24 INFO      CAPTCHA Keep2ShareCc[19]: Captcha | Using OCR to decrypt captcha...
17.04.2019 19:24:24 WARNING   CAPTCHA Keep2ShareCc[19]: Captcha | No OCR result
17.04.2019 19:24:34 INFO      CAPTCHA Keep2ShareCc[19]: Captcha | Captcha result: `sfsf`
17.04.2019 19:24:36 WARNING   CAPTCHA Keep2ShareCc[19]: Captcha | Invalid captcha | sfsf
17.04.2019 19:24:37 DEBUG     CAPTCHA Keep2ShareCc[19]: Captcha | LOAD URL https://keep2share.cc/api/v2/captcha.html?id=0800fb93cfee8 | redirect=True | cookies=True | get={} | req=<module.network.Browser.Browser object at 0xffff8c6c79a8> | decode=False | multipart=False | post={} | ref=False | just_header=False
17.04.2019 19:24:37 INFO      CAPTCHA Keep2ShareCc[19]: Captcha | Using OCR to decrypt captcha...
17.04.2019 19:24:37 WARNING   CAPTCHA Keep2ShareCc[19]: Captcha | No OCR result
17.04.2019 19:24:58 INFO      CAPTCHA Keep2ShareCc[19]: Captcha | Captcha result: `removos`
17.04.2019 19:25:00 INFO      CAPTCHA Keep2ShareCc[19]: Captcha | Correct captcha | removos
17.04.2019 19:25:00 DEBUG     HOSTER Keep2ShareCc[19]: WAIT set to timestamp 1555521931.070431 | Previous waitUntil: 0.000000
17.04.2019 19:25:00 DEBUG     HOSTER Keep2ShareCc[19]: RECONNECT not required | Previous wantReconnect: False
17.04.2019 19:25:00 INFO      HOSTER Keep2ShareCc[19]: Waiting 30 seconds...
17.04.2019 19:25:33 INFO      HOSTER Keep2ShareCc[19]: Downloading file...
17.04.2019 19:25:33 DEBUG     HOSTER Keep2ShareCc[19]: DOWNLOAD URL https://slow-151.keep2share.cc/2be4d54cccff7/65ef85186ffa0/76c898dfd8091?temp_url_sig=43c728120b8416cb71ad3dd06f6b5ce0e3555b4813fa2d1d2c2ec58569011675f040a86a1b37e6dea7398bb0a69dc68b2540592ac3d38e7068be173f019d404f&temp_url_expires=1555608332&id=c87c14bad4c14&ip=any&node_id=151&countable=1&project=moneyplatform&uf=10fae5648ecb2&tags=legacy-api%252Cdownload%252Ck2s&name=Sticky_Password_5.0.5.239.rar | fixurl=True | resume=None | get={} | cookies=True | disposition=False | chunks=None | post={} | ref=True
17.04.2019 19:25:34 DEBUG     Chunk 1 failed: Bad server response: 401 Unauthorized
17.04.2019 19:25:34 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
17.04.2019 19:25:34 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
17.04.2019 19:25:34 WARNING   Download failed: Sticky_Password_5.0.5.239.rar | Bad server response: 401 Unauthorized

**Comment by kveke** [comment]
I seem to have found why the file is not downloaded. The direct link has changed in content and has become a bit longer. You can download, for example wget, downloaded normally. I do not know which module Pyload is engaged in downloading a direct link, I can try from the terminal.


I hope it helps.
Sorry for poor english.

Here is a debug file.
[debug_Keep2ShareCc_20-04-2019_22-33-04.zip](https://github.com/pyload/pyload/files/3103557/debug_Keep2ShareCc_20-04-2019_22-33-04.zip)

**Comment by GammaC0de** [comment]
Thanks for the hint, it really helped.

**Comment by UserX404** [comment]
First test seems not to work.
Still 401 Unauthorized

**Comment by GammaC0de** [comment]
@UserX404 Restart pyload so it will update the plugins.

**Comment by UserX404** [comment]
Had to restart it twice but now it's working.
Thx
