### ISSUE TITLE
Keep2Share PROTOCOL_ERROR (err 1)

### ISSUE THREAD

**Issue by rubenelshof** [pyload/pyload#3365]
Hello,

I am getting the following error when trying to download afile from keep2share:

17.04.2019 18:39:33 INFO      Download starts: http://k2s.cc/file/
17.04.2019 18:39:33 WARNING   HOSTER Keep2ShareCc[38]: Plugin may be unstable
17.04.2019 18:39:33 INFO      HOSTER Keep2ShareCc[38]: Grabbing link info...
17.04.2019 18:39:34 INFO      HOSTER Keep2ShareCc[38]: Link name: F0EOUFT.zip
17.04.2019 18:39:34 INFO      HOSTER Keep2ShareCc[38]: Link size: 131.92 MiB (138333222 bytes)
17.04.2019 18:39:34 INFO      HOSTER Keep2ShareCc[38]: Link status: online
17.04.2019 18:39:34 INFO      HOSTER Keep2ShareCc[38]: Processing url: http://k2s.cc/file/
17.04.2019 18:39:34 INFO      HOSTER Keep2ShareCc[38]: Looking for direct download link...
17.04.2019 18:39:34 INFO      HOSTER Keep2ShareCc[38]: Direct download link not found
17.04.2019 18:39:34 INFO      HOSTER Keep2ShareCc[38]: Checking for link errors...
17.04.2019 18:39:34 INFO      HOSTER Keep2ShareCc[38]: No errors found
17.04.2019 18:39:34 INFO      HOSTER Keep2ShareCc[38]: Processing as free download...
17.04.2019 18:39:34 ERROR     pycurl error 92: HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

I am using pyload in a docker container.
I have installed the required packages and added rhino and pyopenssl.
Is this an error with pyload or am i missing a package?

**Comment by GammaC0de** [comment]
This seems to be a pycurl issue..

What pycurl version are you using?
What docker container are you using?

**Comment by rubenelshof** [comment]
I am using pycurl version 7.43.0.2,
I have created my own image. Here is my dockerfile

# pyload
# Using python alpine
FROM python:2-alpine
    
# Add git, openssh and install pip and needed packages
RUN apk add --no-cache \
	bash \
    su-exec \
    git && \
    apk add --no-cache --virtual=build-deps \
    	gcc \
    	curl-dev \
    	musl-dev \
    	libffi-dev && \
    pip --no-cache-dir install --upgrade setuptools pip && \
    pip --no-cache-dir install --upgrade \
    	thrift \
    	beaker \
    	jinja2 \
    	pycurl \
	rhino \
	pycrypto \
    	pyopenssl && \
    git clone --depth 1 https://github.com/pyload/pyload.git -b stable /opt/pyload && \
    echo "/opt/pyload/pyload-config" > /opt/pyload/module/config/configdir && \
    apk del --no-cache --purge build-deps && \
    rm -rf /tmp/* /var/cache/apk/* /var/tmp/* /opt/pyload/.git

# Set the locale
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV PYCURL_SSL_LIBRARY='openssl'

ADD pyload-config/ /tmp/pyload-config
ADD run.sh /run.sh
RUN chmod +x /run.sh

EXPOSE 8000
VOLUME /opt/pyload/pyload-config
VOLUME /opt/pyload/Downloads

CMD ["/run.sh"]

**Comment by GammaC0de** [comment]
You have to disable HTTP/2 in pycurl 
https://github.com/curl/curl/issues/3206

**Comment by rubenelshof** [comment]
Am I correct than that I would have to compile pycurl from source and remove the USE_NGHTTP2 compile flag?

**Comment by GammaC0de** [comment]
just add `c.setopt(pycurl.HTTP_VERSION, pycurl.CURL_HTTP_VERSION_1_1)` line here: [HTTPRequest.py#L102](https://github.com/pyload/pyload/blob/stable/module/network/HTTPRequest.py#L102)

**Comment by rubenelshof** [comment]
That worked. Thank you for your help and maintenance of the project.
Have a good weekend.

**Comment by dakonga** [comment]
Same issue for me. Since alpine 3.9 pyload stuck on pycurl. Is there any solution without modifing pyload source code? Maybe curl config etc?
