### ISSUE TITLE
Important Alldebrid API update before 01/05/2019

### ISSUE THREAD

**Issue by Alldebrid** [pyload/pyload#3366]
Hello,

We are the Alldebrid staff. We are contacting you today about an update regarding our API.
We are planning to shutdown the login by username/password on our API the 01 May 2019.

Please, use our PIN system : https://docs.alldebrid.com/#pin-auth

Here is how it works :

1/ retrieve on https://api.alldebrid.com/pin/get a pin code and show to your user the "user_url", clickable would be better
=> https://docs.alldebrid.com/#get-pin

2/ Check the pin status via "check_url" and wait to receive the token as soon the user enter it on alldebrid.
=> https://docs.alldebrid.com/#check-the-pin-status

These changes are mandatory to upgrade the security of our users accounts.

Let us know if you need more information or any help.

Thank you.

**Comment by GammaC0de** [comment]
@Alldebrid I need a premium account for tesing..

**Comment by Alldebrid** [comment]
Sent by email.

**Comment by GammaC0de** [comment]
Does the auth token have an expiration period or is it permanent?

I did not received any email, my address is nitzo2001 at yahoo dot com.

**Comment by Alldebrid** [comment]
Should be in your inbox now.

The auth token is permanent (until the user password is updated obviously).

**Comment by GammaC0de** [comment]
pyLoad is a headless software, it does not support user interaction while logging-in.

Is it possible to retrieve a token via some web page so the user will not have to go trough the hassle of the pinning process?

**Comment by GammaC0de** [comment]
[GetAlldebridToken.zip](https://github.com/pyload/pyload/files/3100399/GetAlldebridToken.zip)

**Comment by GammaC0de** [comment]
[GetAlldebridToken.zip](https://github.com/pyload/pyload/files/3100409/GetAlldebridToken.zip)

**Comment by LiloBzH** [comment]
It's ok with script

Thank you !

**Comment by daveyy** [comment]
how to use this script ?

**Comment by GammaC0de** [comment]
@daveyy you run it using python.
All the necessary instructions is there.

**Comment by daveyy** [comment]
I don't know how to do it on Qnap :(

**Comment by GammaC0de** [comment]
You don't do it on Qnap, you do it on your PC and then you go to pyload's Alldebrid plugin configuration and enter the apikey there.

**Comment by daveyy** [comment]
I already have the "API Token" but I don't know where to enter it in the plugin configuration

**Comment by GammaC0de** [comment]
> I already have the "API Token" but I don't know where to enter it in the plugin configuration

Go to pyload's configuration -> accounts -> press the plus button to add account -> and:
Enter your alldebrid.com username as user , "API Token" as password and account type set to "AlldebridCom".

That's it.
