### ISSUE TITLE
9kw in pyload tells me not enough credit even though there is a lot

### ISSUE THREAD

**Issue by ptrsl** [pyload/pyload#3369]
Hello,
I installed pyload and 9kw exactly the way it is described on the 9kw website, also I use their plug in and not the standard one that comes with pyload. Unfurtunately pyload keeps telling me, I hadn't enough credit.
My log tells me this:

102 | 23.04.2019 14:05:17 | ERROR | ADDON Captcha9Kw: Your captcha 9kw.eu account has not enough credits
-- | -- | -- | --
101 | 23.04.2019 14:05:17 | ERROR | ADDON Captcha9Kw: 0003 Keinen aktiven API Key gefunden. / Active API key not found

Does anyone know this?
Thank you in advance!

**Comment by GammaC0de** [comment]
> I use their plug in and not the standard one that comes with pyload.

Do not do that.

**Comment by ptrsl** [comment]
ok sir i won't do it again. i did because i didn't get it to run with the standard tool either, captcha9kw did not even show up in my log :-/ is there any noob proof guide on how to use it and how the api must be configured?

**Comment by GammaC0de** [comment]
First of all, please read https://github.com/pyload/pyload/issues/3283
Next you go to the captcha9k config settings and add your API key.

**Comment by ptrsl** [comment]
thank you, problem solved, all is working well. thank you very much for your great job!!

**Comment by GammaC0de** [comment]
Great :+1:
