### ISSUE TITLE
Receiving not valid when logging into real-debrid

### ISSUE THREAD

**Issue by bobsage123** [pyload/pyload#3372]
Hello. When I try to login to real-debrid in pyload I receive a not valid status. I have tried using my username as well as email for RD with the same result.

**Comment by GammaC0de** [comment]
Password for Real-debrid should be the API token.
Get it from: https://real-debrid.com/apitoken

**Comment by bobsage123** [comment]
Thank you that worked. Please resolve.

**Comment by GammaC0de** [comment]
:+1:
