### ISSUE TITLE
[Request][Hoster] MegaUp.net

### ISSUE THREAD

**Issue by zapp-brannigan** [pyload/pyload#3373]
Hey there,

would be nice if someone could make plugin for megaup.net.
Sample: https://megaup.net/2Ma3y/testfile.bin

The site looks quite simple (load it, grab the link, wait 5 seconds and download; it works even without JS). I tried to make a plugin but i failed (it downloads just the html-page; maybe cookie-related?).

**Comment by GammaC0de** [comment]
Whoah!
I haven't seen you here for ages!

Welcome back! :grin:

**Comment by GammaC0de** [comment]
You're welcome :)
