### ISSUE TITLE
search flags for patterns

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#3374]
Currently, most of the generic code (`SimpleHoster.py` etc) does not use regex flags (such as `re.IGNORECASE`) and so some of the patterns become rather ridiculous (see <https://github.com/pyload/pyload/blob/00974c8c8e691d22c8c62aeff7f3baf8ec2b197e/module/plugins/internal/SimpleHoster.py#L117>). In my fork, I'm using a dict `SEARCH_FLAGS` assigning flags to pattern names (`{"OFFLINE_PATTERN": re.IGNORECASE}`) which I think might be a nice way to allow easier plugin development (so far, if you want your pattern matched with `re.IGNORECASE` you'll have to either write a weird pattern or rewrite some `handle_free()`. Downside, however, is that all the searches in `internal/*.py` have to change slightly. Do you think it's still worth it? Would you welcome a pull request in this regard?

**Comment by GammaC0de** [comment]
Nice idea and indeed  this is required but I have an idea for better implementation.
So, working on it..

**Comment by igel-kun** [comment]
cool, thanks for picking this up; looking forward to seeing it :)

**Comment by GammaC0de** [comment]
Now you can use for example:
```
OFFLINE_PATTERN = r'file not found' , re.S |  re.I
```
i.e.
OFFLINE_PATTERN  = pattern [, flags]


Please test and tell me what you think.

**Comment by igel-kun** [comment]
very clean and effective, good work man :)

**Comment by igel-kun** [comment]
hmm, I see that `SimpleHoster` often contains lines like this:
```
if cls.OFFLINE_PATTERN and search_pattern(cls.OFFLINE_PATTERN, html) is not None:
```
It might be more neat to move the first test into `search_pattern` itself. This way, we get better error handling in `search_pattern` and we make `SimpleHoster` more readable :)
