### ISSUE TITLE
Keep2Share captcha for account login

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#3376]
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [x] Bug report
- [ ] Question
- [ ] Other

### Summary:

It seems that Keep2Share sometimes wants a captcha for login requests

### How to reproduce:

`curl -L --data '{"username":"***", "password":"***"}' 'https://k2s.cc/api/v2/login'`
`{"message":"Please verify your request via re captcha challenge","status":"error","code":406,"errorCode":33}{"message":"Invalid reCaptcha response","status":"error","code":406,"errorCode":31}`

This leads to a `fail_login()` at https://github.com/pyload/pyload/blob/1212a684f94856181ad227ff5da140045a95ea8f/module/plugins/accounts/Keep2ShareCc.py#L56 while it should cause a captcha request

**Comment by GammaC0de** [comment]
Please try this and confirm
[Keep2ShareCc.zip](https://github.com/pyload/pyload/files/3143981/Keep2ShareCc.zip)

**Comment by igel-kun** [comment]
```
04.05.2019 12:01:08 INFO      ACCOUNT Keep2ShareCc: Adding user `*******`...
04.05.2019 12:01:08 DEBUG     ACCOUNT Keep2ShareCc: Reached login timeout for user `*******`
04.05.2019 12:01:08 INFO      ACCOUNT Keep2ShareCc: Login user `*******`...
04.05.2019 12:01:12 DEBUG     CAPTCHA Keep2ShareCc: Captcha | LOAD URL https://keep2share.cc/api/v2/captcha.html?id=6402f82e78728 | redirect=True | cookies=True | redir_post=True | req=<module.network.Browser.Browser object at 0xb189cca8> | decode=False | just_header=False | get={} | post={} | ref=False | multipart=False
04.05.2019 12:01:15 INFO      CAPTCHA Keep2ShareCc: Captcha | Using OCR to decrypt captcha...
04.05.2019 12:01:15 WARNING   CAPTCHA Keep2ShareCc: Captcha | No OCR result
04.05.2019 12:01:24 INFO      CAPTCHA Keep2ShareCc: Captcha | Captcha result: `posote`
04.05.2019 12:01:27 ERROR     ACCOUNT Keep2ShareCc: Could not login user `*******` | Extra data: line 1 column 108 - line 1 column 191 (char 108 - 191)
Traceback (most recent call last):
  File "./pyLoadCore.py", line 685, in <module>
    main()
  File "./pyLoadCore.py", line 676, in main
    pyload_core.start()
  File "./pyLoadCore.py", line 445, in start
    self.accountManager.getAccountInfos()
  File "/home/cache/pyload_newfork/module/utils.py", line 169, in new
    return func(*args)
  File "/home/cache/pyload_newfork/module/plugins/AccountManager.py", line 180, in getAccountInfos
    data[p.__name__] = p.getAllAccounts(force)
  File "/home/cache/pyload_newfork/module/plugins/internal/misc.py", line 234, in new
    return fn(*args, **kwargs)
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 279, in getAllAccounts
    self.init_accounts()  # @TODO: Recheck in 0.4.10
  File "/home/cache/pyload_newfork/module/plugins/internal/misc.py", line 234, in new
    return fn(*args, **kwargs)
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 267, in init_accounts
    self.add(user, info['password'], info['options'])
  File "/home/cache/pyload_newfork/module/plugins/internal/misc.py", line 234, in new
    return fn(*args, **kwargs)
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 313, in add
    result = u['plugin'].choose(user)
  File "/home/cache/pyload_newfork/module/plugins/internal/misc.py", line 234, in new
    return fn(*args, **kwargs)
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 431, in choose
    self.relogin()
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 177, in relogin
    return self.login()
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 118, in login
    self.info['data'])
  File "/home/cache/pyload_newfork/module/plugins/accounts/Keep2ShareCc.py", line 79, in signin
    json_data = json.loads(e.content)
  File "/home/cache/pyload_newfork/module/lib/simplejson/__init__.py", line 413, in loads
    return _default_decoder.decode(s)
  File "/home/cache/pyload_newfork/module/lib/simplejson/decoder.py", line 405, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
JSONDecodeError: Extra data: line 1 column 108 - line 1 column 191 (char 108 - 191)
```

**Comment by GammaC0de** [comment]
Can you put this in line 76:
```
                            self.log_debug("Error 406:", e.content)
```

**Comment by igel-kun** [comment]
hmm, maybe I'm bad at doing captchas... but json_loads seems to be bad at parsing two hashes ^^
```
04.05.2019 13:23:03 INFO      CAPTCHA Keep2ShareCc: Captcha | Using OCR to decrypt captcha...
04.05.2019 13:23:03 WARNING   CAPTCHA Keep2ShareCc: Captcha | No OCR result
04.05.2019 13:23:14 INFO      CAPTCHA Keep2ShareCc: Captcha | Captcha result: `lsacso`
04.05.2019 13:23:16 DEBUG     ACCOUNT Keep2ShareCc: Error 406: | {"message":"Please verify your request via re captcha challenge","status":"error","code":406,"errorCode":33}{"message":"Invalid reCaptcha response","status":"error","code":406,"errorCode":31}
04.05.2019 13:23:16 ERROR     ACCOUNT Keep2ShareCc: Could not login user `*******` | Extra data: line 1 column 108 - line 1 column 191 (char 108 - 191)
```

**Comment by igel-kun** [comment]
may I suggest
```
for m in re.finditer('{.*?}', e.content):
  json_data = json.loads(m.group(0))
  ...
```

**Comment by GammaC0de** [comment]
`{"message":"Please verify your request via re captcha challenge","status":"error","code":406,"errorCode":33}{"message":"Invalid reCaptcha response","status":"error","code":406,"errorCode":31}` is not a valid JSON string :(

`{"message":"Please verify your request via re captcha challenge","status":"error","code":406,"errorCode":33}` is valid and also `{"message":"Invalid reCaptcha response","status":"error","code":406,"errorCode":31}` is valid
Why would the send two json string???  :angry:

**Comment by igel-kun** [comment]
*shakes fist*
(but when you look at my initial post, that's when they do, even for a manual request)

**Comment by GammaC0de** [comment]
OK, updating the code, please wait.

**Comment by igel-kun** [comment]
I'm trying
```
                    except BadHeader, e:
                        self.log_debug("Error 406:", e.content)
                        if e.code == 406:
                            if 31 in (json.loads(i.group(0)).get('errorCode',0) for i in re.finditer('{.*?}', e.content)):
                                #: ERROR_CAPTCHA_INVALID
                                self.captcha.invalid()
                                continue
```
in the meantime :)

**Comment by GammaC0de** [comment]
33 is ERROR_RE_CAPTCHA_REQUIRED, maybe that means reCaptcha!?

**Comment by igel-kun** [comment]
ooooh, you might be right, cause I'm just getting the same 406 over and over, even if I'm sure my captchas are rcorrect

**Comment by igel-kun** [comment]
yes, `curl`-based testing confirmed that it works with re-captcha challenges/responses...

**Comment by GammaC0de** [comment]
Can you post the curl test?

**Comment by igel-kun** [comment]
```
% curl -L --data '' 'https://k2s.cc/api/v2/RequestReCaptcha'
{"status":"success","code":200,"challenge":"82fea2fe2add5","captcha_url":"https:\/\/k2s.cc\/api\/v2\/reCaptcha.html?id=82fea2fe2add5"}
% curl -L --data '{"username":"***", "password":"***", "re_captcha_challenge":"82fea2fe2add5", "re_captcha_response":"03AOLTBLSGkZ49-An9PLl5H6vFtPJpYyfJRFvt_Bz2XBMdKIs1KX6ly1usf_E0ViLXDdgtsK5dyfLCRUzX390knNHaOT7RyhcK6A0DlhuMKnhVxs31oujphk-pGqJM_NyWIHWwpanlYkJTyPecLE9cOPqrzCOLBFzfdubhI-ZwJ0Z7YfU-eNdflhLsRXZadSD4JbaCyVNBbk5tzbPCQsCbd8lw49uWHVTxN6GLsFKGqEl0JoSAeaOSjFpQ5AhiJ5yK5qEkPSGGopSgw3f7gHIyw3ZoB8gwKXR0rz1UmpQLYMIlhfhIBfuzVLFi8emxSgkpcXjK7tvHbe_stW9GpCI2Q-EU1Jm4nKWavw"}' 'https://k2s.cc/api/v2/login'
{"message":"Invalid login or password","status":"error","code":406,"errorCode":70}
```

**Comment by GammaC0de** [comment]
oooh so captcha_url is used to distinguish the captcha type...

**Comment by igel-kun** [comment]
no, it's `re_captcha_challenge` and `re_captcha_response` instead of `captcha_challenge` and `captcha_response` I think

**Comment by igel-kun** [comment]
(by the way, I cannot Administration -> Restart Pyload while the account plugin is active it seems)

**Comment by GammaC0de** [comment]
captcha_url = `https://k2s.cc/api/v2/reCaptcha.html?id=82fea2fe2add5`
notice **reCaptcha.html**

**Comment by igel-kun** [comment]
okay, didn't get what exactly you meant before :)

**Comment by GammaC0de** [comment]
Try this:
[Keep2ShareCc.zip](https://github.com/pyload/pyload/files/3144480/Keep2ShareCc.zip)

**Comment by GammaC0de** [comment]
Sorry, wrong file :(
Try this one:
[Keep2ShareCc.zip](https://github.com/pyload/pyload/files/3144658/Keep2ShareCc.zip)

**Comment by igel-kun** [comment]
I'm in the process of testing... first thing: not all Keep2share accounts are premium, I replaced the
`'premium': True` by ` 'premium': True if json_data['account_expires'] else False`

**Comment by GammaC0de** [comment]
OK, but does the captcha fix works now? 

 
 
   igel-kun<notifications@github.com> wrote:   
I'm in the process of testing... first thing: not all Keep2share accounts are premium, I replaced the
'premium': True by  'premium': True if json_data['account_expires'] else False

**Comment by igel-kun** [comment]
hmm, without having run the code yet, I have two other remarks:
1. I don't you handling the invalid JSON that is returned by the `login` command if no or a wrong captcha is submitted along with it
2. the way I read your code, it sends a `login` request and if it gets a 406 code it does
`if "reCaptcha" in json_data['captcha_url']` but the response to the `login` request does not have a "captcha_url" field (see initial post)

**Comment by GammaC0de** [comment]
> hmm, without having run the code yet, I have a few other remarks
> I don't see you handling the invalid JSON that is returned by the login command if no or a wrong captcha is submitted along with it

I was hoping (since I cannot test is without an account) that if you provide the correct captcha type that k2s expect, it would return a normal json response,
So please test the code.

> the pyfile object you're getting is only used in the "#normal captcha" case, right? 

No, it is used for any captcha type.

**Comment by igel-kun** [comment]
> > hmm, without having run the code yet, I have a few other remarks
> > I don't see you handling the invalid JSON that is returned by the login command if no or a wrong captcha is submitted along with it
> 
> I was hoping (since I cannot test is without an account) that if you provide the correct captcha type that k2s expect, it would return a normal json response,
> So please test the code.
hmm, can't test right now it seems, I'm getting instant-success from k2s when calling `login`... I'll try again later.

However, I don't see your call to `login` provide any captcha whatsoever, and that's the one returning the malformed json (see curl in the initial post), so right or wrong captcha type, this call will eventually crash `json.loads()` answer with the malformed json (unless I am misunderstanding something fundamental).

> > the pyfile object you're getting is only used in the "#normal captcha" case, right? 
> No, it is used for any captcha type.
okay, my python is certainly vastly inferior to yours, so I'm wondering, how is it used in the `if "reCaptcha" in json_data['captcha_url']:` block if the word "pyfile" does not even occur in there (and it's a local variable)?

**Comment by GammaC0de** [comment]
As I said, this code is untested so I guess it probably should have been `self.pyfile = ...`

```
 % sha1sum Keep2ShareCc.py
ea8949260de967763cab77145b15676987947cea  Keep2ShareCc.py
```
Correct

**Comment by igel-kun** [comment]
I fixed the problem but am now getting
```
  File "/home/cache/pyload_newfork/module/plugins/accounts/Keep2ShareCc.py", line 80, in signin
    re_captcha_response, _ = self.captcha.challenge(self.RECAPTCHA_KEY)
  File "/home/cache/pyload_newfork/module/plugins/captcha/ReCaptcha.py", line 159, in challenge
    version=self.detect_version(data=data),
  File "/home/cache/pyload_newfork/module/plugins/captcha/ReCaptcha.py", line 133, in detect_version
    data = data or self.retrieve_data()
  File "/home/cache/pyload_newfork/module/plugins/internal/CaptchaService.py", line 27, in retrieve_data
    return self.pyfile.plugin.data or self.pyfile.plugin.last_html or ""
AttributeError: 'Keep2ShareCc' object has no attribute 'data'
```
It seems `ReCaptcha.py` assumes that all plugins using it will have a `data` field. I'll just put the json string there...

**Comment by GammaC0de** [comment]
Try adding `version=2js` parameter at line 80

 
 
  igel-kun<notifications@github.com> wrote:   
I fixed the problem but am now getting
  File "/home/cache/pyload_newfork/module/plugins/accounts/Keep2ShareCc.py", line 80, in signin
    re_captcha_response, _ = self.captcha.challenge(self.RECAPTCHA_KEY)
  File "/home/cache/pyload_newfork/module/plugins/captcha/ReCaptcha.py", line 159, in challenge
    version=self.detect_version(data=data),
  File "/home/cache/pyload_newfork/module/plugins/captcha/ReCaptcha.py", line 133, in detect_version
    data = data or self.retrieve_data()
  File "/home/cache/pyload_newfork/module/plugins/internal/CaptchaService.py", line 27, in retrieve_data
    return self.pyfile.plugin.data or self.pyfile.plugin.last_html or ""
AttributeError: 'Keep2ShareCc' object has no attribute 'data'

It seems ReCaptcha.py assumes that all plugins using it will have a data field. I'll just put the json string there...

**Comment by igel-kun** [comment]
This file works for me (tested using proxies)
[Keep2ShareCc.py.gz](https://github.com/pyload/pyload/files/3158123/Keep2ShareCc.py.gz)

**Comment by igel-kun** [comment]
> Try adding `version=2js` parameter at line 80
no, the problem was that we didn't `self.load()` the `captcha_url` given by the API :) I just did `self.data = self.load(json_data['captcha_url'])` and it went through.

**Comment by GammaC0de** [comment]
Can you please test this version?
[Keep2ShareCc.py.gz](https://github.com/pyload/pyload/files/3159456/Keep2ShareCc.py.gz)

**Comment by igel-kun** [comment]
I see you removed the `self.data = self.load(json_data['captcha_url'])`, so how will `ReCaptcha()` know the captcha challenge it is supposed to solve?

**Comment by GammaC0de** [comment]
the captcha_url points to a html with call to recaptcha with the recaptcha token. So what I do is call the recaptcha myself and send the result and the challenge 

 
igel-kun<notifications@github.com> wrote:   
I see you removed the self.data = self.load(json_data['captcha_url']), so how will ReCaptcha() know the captcha challenge it is supposed to solve?

**Comment by GammaC0de** [comment]
captcha_url allways points the same HTML no matter what.
ReCaptcha returns the response which Keep2Share can verify its correctness using its private API key.
After Keep2Share verifies correct captcha, this captcha  is associated with the current download session using the re_captcha_challenge

**Comment by igel-kun** [comment]
Oh, I see, only the sitekey is required and it's always the same - surprising... they'd have to link the captcha to my IP-address internally. Anyways, I'm in the process of testing again... :)

**Comment by igel-kun** [comment]
By the way, I noticed when switching proxies that pyload tries to authenticate with the auth_token obtained from a different IP address, resulting in a 403 BadHeader. Maybe we want to treat this case while we're at it or should I open a separate issue?

**Comment by GammaC0de** [comment]
```
{"message":"Authorization session was expired","status":"error","code":403,"errorCode":11}
```

On what line this exception occours?

**Comment by igel-kun** [comment]
This happens if my IP changes after a successful login and pyload tries to `grab_info` using the old `auth_token`:
```
11.05.2019 10:40:48 INFO      ACCOUNT Keep2ShareCc: Grabbing account info for user `*******`...
11.05.2019 10:40:52 WARNING   ACCOUNT Keep2ShareCc: Error loading info for user `*******` | Bad server response: 403 Forbidden
```

**Comment by GammaC0de** [comment]
We will deal with this later,
Have you tested the plugin?

**Comment by igel-kun** [comment]
```
11.05.2019 14:55:01 DEBUG     ACCOUNT Keep2ShareCc: Reached login timeout for user `*******`
11.05.2019 14:55:01 INFO      ACCOUNT Keep2ShareCc: Login user `*******`...
11.05.2019 14:55:08 ERROR     ACCOUNT Keep2ShareCc: Could not login user `*******` | 'Keep2ShareCc' object has no attribute 'data'
Traceback (most recent call last):
  File "./pyLoadCore.py", line 685, in <module>
    main()
  File "./pyLoadCore.py", line 676, in main
    pyload_core.start()
  File "./pyLoadCore.py", line 445, in start
    self.accountManager.getAccountInfos()
  File "/home/cache/pyload_newfork/module/utils.py", line 169, in new
    return func(*args)
  File "/home/cache/pyload_newfork/module/plugins/AccountManager.py", line 180, in getAccountInfos
    data[p.__name__] = p.getAllAccounts(force)
  File "/home/cache/pyload_newfork/module/plugins/internal/misc.py", line 229, in new
    return fn(*args, **kwargs)
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 277, in getAllAccounts
    self.init_accounts()  # @TODO: Recheck in 0.4.10
  File "/home/cache/pyload_newfork/module/plugins/internal/misc.py", line 229, in new
    return fn(*args, **kwargs)
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 265, in init_accounts
    self.add(user, info['password'], info['options'])
  File "/home/cache/pyload_newfork/module/plugins/internal/misc.py", line 229, in new
    return fn(*args, **kwargs)
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 311, in add
    result = u['plugin'].choose(user)
  File "/home/cache/pyload_newfork/module/plugins/internal/misc.py", line 229, in new
    return fn(*args, **kwargs)
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 431, in choose
    self.relogin()
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 177, in relogin
    return self.login()
  File "/home/cache/pyload_newfork/module/plugins/internal/Account.py", line 118, in login
    self.info['data'])
  File "/home/cache/pyload_newfork/module/plugins/accounts/Keep2ShareCc.py", line 78, in signin
    re_captcha_response, _ = self.captcha.challenge(self.RECAPTCHA_KEY, version="2js")
  File "/home/cache/pyload_newfork/module/plugins/captcha/ReCaptcha.py", line 146, in challenge
    secure_token = secure_token or self.detect_secure_token(data) if version in (2,'2js') else None
  File "/home/cache/pyload_newfork/module/plugins/captcha/ReCaptcha.py", line 120, in detect_secure_token
    html = data or self.retrieve_data()
  File "/home/cache/pyload_newfork/module/plugins/internal/CaptchaService.py", line 27, in retrieve_data
    return self.pyfile.plugin.data or self.pyfile.plugin.last_html or ""
AttributeError: 'Keep2ShareCc' object has no attribute 'data'
```

**Comment by GammaC0de** [comment]
ReCaptcha plugin has been updated.

Please test this plugin:
[Keep2ShareCc.py.gz](https://github.com/pyload/pyload/files/3169213/Keep2ShareCc.py.gz)

**Comment by igel-kun** [comment]
seems to work now with ReCaptcha 0.42, cheers!

**Comment by GammaC0de** [comment]
> want me to open a new issue for the 403 error or can we do it here?

The fix for 403 is to issue a re-login but:
* I don't think that pyload would support relogin while in the middle of a download
* This is an issue only if you are using the reconnect feature (other account plugins *may* be effected)

So I need to see a full trace log to think if this is possible..

**Comment by igel-kun** [comment]
it's the account plugin itself that catches a 403, when issuing `grab_info` _before_ the download starts (it's not "in the middle of a download"). 
> ```
> 11.05.2019 10:40:48 INFO      ACCOUNT Keep2ShareCc: Grabbing account info for user `*******`...
> 11.05.2019 10:40:52 WARNING   ACCOUNT Keep2ShareCc: Error loading info for user `*******` | Bad server response: 403 Forbidden
> ```

I'll see if I can get a trace...

**Comment by GammaC0de** [comment]
Please provide full debug log, thanks.
