### ISSUE TITLE
FilboomMe hoster plugin out of date

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#3377]
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [x] Bug report
- [ ] Question
- [ ] Other

### Summary:

seems that the guys over at fileboom.me changed their website, which is now basically a whole mess of javascript. However, I think I read somewhere (and the guys developing JDownloader use this I think) that fileboom basically follows the Keep2share API, so this may be a great opportunity to just inherit from Keep2shareCC, change the API URL and be done with it :)

**Comment by GammaC0de** [comment]
Thanks for the hint 👍

**Comment by GammaC0de** [comment]
Duplicate of #3153
