### ISSUE TITLE
Can't download anything 

### ISSUE THREAD

**Issue by razerman17** [pyload/pyload#3380]
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [X ] Bug report
- [ ] Question
- [ ] Other

### Summary:

Hello, 

I just install pyload on a fresh Debian 9 VM (on Proxmox) after done configuration with my alldebrid account (I follow Gammac0de conf for this part), I try to download but nothing start (try with uptobox a 1fichier) there's an error show up.... Here's my log file

913 | 10.05.2019 14:11:50 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
-- | -- | -- | --
914 | 10.05.2019 14:15:35 | INFO | Added package Mydownload containing 1 links
915 | 10.05.2019 14:15:36 | INFO | Download starts: https://uptobox.com/XXX
916 | 10.05.2019 14:15:36 | WARNING | HOSTER AlldebridCom[8]: AlldebridCom \| Plugin may be unstable
917 | 10.05.2019 14:15:36 | INFO | ACCOUNT AlldebridCom: Grabbing account info for user `sam*******`...
918 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Grabbing link info...
919 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Link name: XXX
920 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Link size: N/D
921 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Link status: starting
922 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Processing url: https://uptobox.com/XXX
923 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Looking for direct download link...
924 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Direct download link not found
925 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Checking for link errors...
926 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| No errors found
927 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Grabbing link info...
928 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Link name: **XXX**
929 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Link size: N/D
930 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Link status: starting
931 | 10.05.2019 14:15:36 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Processing as premium download...
932 | 10.05.2019 14:15:37 | INFO | HOSTER AlldebridCom[8]: AlldebridCom \| Downloading file...
933 | 10.05.2019 14:15:37 | ERROR | HOSTER AlldebridCom[8]: AlldebridCom
934 | 10.05.2019 14:15:37 | WARNING | HOSTER AlldebridCom[8]: AlldebridCom \| Premium download failed \| IOError 13
935 | 10.05.2019 14:15:37 | INFO | Download restarted: Mydownload.mkv \| Revert to original hoster plugin
936 | 10.05.2019 14:15:37 | INFO | Download starts: Mydownload.mkv
937 | 10.05.2019 14:15:37 | WARNING | HOSTER UptoboxCom[8]: Plugin may be unstable
938 | 10.05.2019 14:15:37 | INFO | HOSTER UptoboxCom[8]: Grabbing link info...
939 | 10.05.2019 14:15:37 | INFO | HOSTER UptoboxCom[8]: Link name: Mydownload.mkv
940 | 10.05.2019 14:15:37 | INFO | HOSTER UptoboxCom[8]: Link size: 2.05 GiB (2201170739 bytes)
941 | 10.05.2019 14:15:37 | INFO | HOSTER UptoboxCom[8]: Link status: online
942 | 10.05.2019 14:15:37 | INFO | HOSTER UptoboxCom[8]: Processing url: https://uptobox.com/XXX
943 | 10.05.2019 14:15:37 | INFO | HOSTER UptoboxCom[8]: Looking for direct download link...
944 | 10.05.2019 14:15:37 | INFO | HOSTER UptoboxCom[8]: Direct download link not found
945 | 10.05.2019 14:15:37 | INFO | HOSTER UptoboxCom[8]: Checking for link errors...
946 | 10.05.2019 14:15:37 | INFO | HOSTER UptoboxCom[8]: Waiting 30 seconds...

Can you help me please ?

**Comment by GammaC0de** [comment]
How did you install pyLoad?

**Comment by razerman17** [comment]
Here's the step I follow :
wget http://download.pyload.org/pyload-v0.4.9-all
dpkg -i pyload-v0.4.9-all
and use ./pyLoadCorre.py script to do the config with default settings (I do it first in french but there's was another problem that I solved by change to english).
But after I tried to configure alldebrid and downloaded the one I found on pyload/module and saw there were a problem with the conection so I download the complete plugins folder from github with last modified file and replace the original one from /usr/share/pyload/module/plugins
and downloaded the GetAlldebridToken.py to do the generation of the token that I put as password.
I also tried to desactivate some plugins like XFileSharing  as I saw on other post but no effect....

**Comment by GammaC0de** [comment]
This is NOT how to install pyload.

This is how:
- Download and install https://github.com/pyload/pyload/releases/download/v0.4.9/pyload_0.4.9_all.deb and use ./pyLoadCorre.py script to do the config with default settings.
- Start pyLoad
- Follow the instructions in https://github.com/pyload/pyload/issues/3283

**Comment by razerman17** [comment]
Perfect all works ! Thank You :)

**Comment by GammaC0de** [comment]
:+1:  Now I recommend you to go to pyLoad's configuration and switch to the "modern" web-ui.
