### ISSUE TITLE
AlldebridCom problem

### ISSUE THREAD

**Issue by tson0n0** [pyload/pyload#3382]
- [ ] Plugin request
- [ ] Feature request
- [ ] Bug report
- [X] Question
- [ ] Other

Hello, I have a problem with the "alldebrid" hoster. The account is good (with the new API) Status : Valid
But when I try to download something from alldebrid (link example : https://zvq490.alld.ovh/dl/someID/The.**********.mkv ), the hoster is kwnew as "BasePlugin" And the file size is 1,5kb.
Did I miss something ?

Thank you

![alld](https://user-images.githubusercontent.com/3876472/57532314-ae892900-733b-11e9-9f98-30ab9be51228.png)

Here the logs : 

Added package sky containing 1 links
--
520 | 10.05.2019 16:58:16 | INFO | Download starts: https://tld15b.alld.ovh/dl/SOMEID/DOWNLOADEDFILE.AVI
521 | 10.05.2019 16:58:16 | WARNING | HOSTER BasePlugin[14]: Plugin may be unstable
522 | 10.05.2019 16:58:16 | INFO | HOSTER BasePlugin[14]: Grabbing link info...
523 | 10.05.2019 16:58:16 | INFO | HOSTER BasePlugin[14]: Link name: DOWNLOADEDFILE.AVI
524 | 10.05.2019 16:58:16 | INFO | HOSTER BasePlugin[14]: Link size: N/D
525 | 10.05.2019 16:58:16 | INFO | HOSTER BasePlugin[14]: Link status: starting
526 | 10.05.2019 16:58:16 | INFO | HOSTER BasePlugin[14]: Processing url: https://tld15b.alld.ovh/dl/SOMEID/DOWNLOADEDFILE.AVI
527 | 10.05.2019 16:58:17 | INFO | HOSTER BasePlugin[14]: File saved
528 | 10.05.2019 16:58:17 | WARNING | HOSTER BasePlugin[14]: Check result: Html file \| Waiting 1 minute and retry
529 | 10.05.2019 16:58:17 | INFO | HOSTER BasePlugin[14]: Waiting 1 minutes...
530 | 10.05.2019 16:59:19 | INFO | Download restarted: DOWNLOADEDFILE.AVI \| Html file
531 | 10.05.2019 16:59:19 | INFO | Download starts: DOWNLOADEDFILE.AVI

**Comment by GammaC0de** [comment]
BasePlugin is the default plugin when no other plugins match the URL.
pyLoad uses alldebrid API to query the supported URLs.
So what is probably happens is that alldebrid  does not support https://tld15b.alld.ovh/dl/SOMEID/DOWNLOADEDFILE.AVI

**Comment by tson0n0** [comment]
But this link is a debrided link with alldebrid. This link works with the Synology plugin.I Can send the complete link if needed

**Comment by GammaC0de** [comment]
What is the original link?

**Comment by tson0n0** [comment]
This link for exemple : https://tld15b.alld.ovh/dl/1k0zwvwb84b/1809ProX64AvrFr.part11.rar

**Comment by Alldebrid** [comment]
I don't thing this has anything to do with Pyload indeed. The HTML file you got is an download error page, not sure what error you trigguered specifically.

Best way to use Alldebrid with your Syno is to use our Synology .host file available here https://alldebrid.com/extensions/?platform=nas#syno . This way you can add hoster links directly, and Synology will handle the unlocking and downloading stuff itself.

**Comment by tson0n0** [comment]
Thank you for your answer, but I prefer user pyload with my server .
It
This is a part of the html error page : 

	<script type="text/javascript">$(document).ready(function() {  $.msgbox("Server not allowed (SERVER_IP).", {type: "info"}, function(result) {window.location = "http://www.alldebrid.com"});  });</script>
</body>
</html>




I really wish I could use pyload with the AllDebrid plugin.
Is it possible that something is missing in the plug in?

**Comment by GammaC0de** [comment]
@tson0n0 You are using pyload and alldebrid totally the wrong way:
* First you add the account
* After that you add the locked URL into pyload (for example http://ul.to/some_file), and it would unlock the URL for you and then download it.

By the way, I can download https://tld15b.alld.ovh/dl/1k0zwvwb84b/1809ProX64AvrFr.part11.rar with no problem, tried on two different computers.

**Comment by tson0n0** [comment]
Okay I see ...
I thought the problem came from the plugin because we could see that it used the plugin of the host (ul.to for example) and not the one of Alldebrid, but it is Alldebrid who failed the connection (I have the impression)
Here are the logs: 

840 | 14.05.2019 09:48:03 | INFO | Added package test containing 1 links
-- | -- | -- | --
841 | 14.05.2019 09:48:04 | INFO | Download starts: http://ul.to/0dca3qps
842 | 14.05.2019 09:48:04 | WARNING | HOSTER AlldebridCom[21]: AlldebridCom \| Plugin may be unstable
843 | 14.05.2019 09:48:04 | INFO | ACCOUNT AlldebridCom: Grabbing account info for user `tso*******`...
844 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Grabbing link info...
845 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link name: 0dca3qps
846 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link size: N/D
847 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link status: starting
848 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Processing url: http://ul.to/0dca3qps
849 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Looking for direct download link...
850 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Direct download link not found
851 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Checking for link errors...
852 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| No errors found
853 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Grabbing link info...
854 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link name: 0dca3qps
855 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link size: N/D
856 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link status: starting
857 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Processing as premium download...
858 | 14.05.2019 09:48:05 | WARNING | HOSTER AlldebridCom[21]: AlldebridCom \| ipnotallowed
859 | 14.05.2019 09:48:05 | WARNING | HOSTER AlldebridCom[21]: AlldebridCom \| Premium download failed \| temp. offline
860 | 14.05.2019 09:48:05 | INFO | Download restarted: 0dca3qps \| Fallback to free processing
861 | 14.05.2019 09:48:05 | INFO | Download starts: 0dca3qps
862 | 14.05.2019 09:48:05 | WARNING | HOSTER AlldebridCom[21]: AlldebridCom \| Plugin may be unstable
863 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Grabbing link info...
864 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link name: 0dca3qps
865 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link size: N/D
866 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link status: starting
867 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Processing url: http://ul.to/0dca3qps
868 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Looking for direct download link...
869 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Direct download link not found
870 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Checking for link errors...
871 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| No errors found
872 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Grabbing link info...
873 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link name: 0dca3qps
874 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link size: N/D
875 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Link status: starting
876 | 14.05.2019 09:48:05 | INFO | HOSTER AlldebridCom[21]: AlldebridCom \| Processing as free download...
877 | 14.05.2019 09:48:05 | WARNING | HOSTER AlldebridCom[21]: AlldebridCom \| Free download failed \| MultiHoster download failed
878 | 14.05.2019 09:48:05 | INFO | Download restarted: 0dca3qps \| Revert to original hoster plugin
879 | 14.05.2019 09:48:06 | INFO | Download starts: 0dca3qps
880 | 14.05.2019 09:48:06 | WARNING | HOSTER UploadedTo[21]: Plugin may be unstable
881 | 14.05.2019 09:48:06 | INFO | HOSTER UploadedTo[21]: Grabbing link info...
882 | 14.05.2019 09:48:06 | INFO | HOSTER UploadedTo[21]: Link name: Edmond.2018.FRENCH.720p.HDLight.x264.AC3-EXTREME.mkv
883 | 14.05.2019 09:48:06 | INFO | HOSTER UploadedTo[21]: Link size: 1.64 GiB (1755685166 bytes)
884 | 14.05.2019 09:48:06 | INFO | HOSTER UploadedTo[21]: Link status: online
885 | 14.05.2019 09:48:06 | INFO | HOSTER UploadedTo[21]: Processing url: http://ul.to/0dca3qps
886 | 14.05.2019 09:48:06 | INFO | HOSTER UploadedTo[21]: Looking for direct download link...
887 | 14.05.2019 09:48:06 | INFO | HOSTER UploadedTo[21]: Direct download link not found
888 | 14.05.2019 09:48:06 | INFO | HOSTER UploadedTo[21]: Checking for link errors...
889 | 14.05.2019 09:48:06 | INFO | HOSTER UploadedTo[21]: Waiting 30 seconds...

**Comment by GammaC0de** [comment]
"ipnotallowed" errors means that somehow @Alldebrid banned your IP..

**Comment by tson0n0** [comment]
Thanks for the help ! 
And Great Works guys ! :)
