### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by rubenelshof** [pyload/pyload#3387]
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [x] Bug report
- [ ] Question
- [ ] Other

### Summary:

After restarting pyload (asked because plugins were updated) I am getting the following error with every plugin I try to use: 'NoneType' object is not iterable
I have used Keep2Share and Rapidgator.
Error log

558 | 14.05.2019 21:24:25 | INFO | Download starts: ofj150617.2.rar
-- | -- | -- | --
559 | 14.05.2019 21:24:25 | WARNING | HOSTER Keep2ShareCc[51495]: Plugin may be unstable
560 | 14.05.2019 21:24:25 | INFO | HOSTER Keep2ShareCc[51495]: Grabbing link info...
561 | 14.05.2019 21:24:25 | INFO | HOSTER Keep2ShareCc[51495]: Link name: ofj150617.2.rar
562 | 14.05.2019 21:24:25 | INFO | HOSTER Keep2ShareCc[51495]: Link size: 68.75 MiB (72094271 bytes)
563 | 14.05.2019 21:24:25 | INFO | HOSTER Keep2ShareCc[51495]: Link status: online
564 | 14.05.2019 21:24:25 | INFO | HOSTER Keep2ShareCc[51495]: Processing url: 
565 | 14.05.2019 21:24:25 | INFO | HOSTER Keep2ShareCc[51495]: Looking for direct download link...
566 | 14.05.2019 21:24:25 | INFO | HOSTER Keep2ShareCc[51495]: Direct download link not found
567 | 14.05.2019 21:24:25 | INFO | HOSTER Keep2ShareCc[51495]: Checking for link errors...
568 | 14.05.2019 21:24:25 | WARNING | Download failed: ofj150617.2.rar \| 'NoneType' object is not iterable
569 | 14.05.2019 21:24:25 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: ofj150617.2.rar (pid:364)
570 | 14.05.2019 21:24:25 | INFO | ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
Please enable debug mode and then retry and send the log with debug information.

**Comment by rubenelshof** [comment]
Please see below:

715 | 14.05.2019 22:50:25 | INFO | Download starts: contraste.zip
-- | -- | -- | --
716 | 14.05.2019 22:50:25 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
717 | 14.05.2019 22:50:25 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
718 | 14.05.2019 22:50:25 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
719 | 14.05.2019 22:50:25 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0  (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
720 | 14.05.2019 22:50:25 | DEBUG | HOSTER Keep2ShareCc[51505]: Plugin version: 0.44
721 | 14.05.2019 22:50:25 | DEBUG | HOSTER Keep2ShareCc[51505]: Plugin status: testing
722 | 14.05.2019 22:50:25 | WARNING | HOSTER Keep2ShareCc[51505]: Plugin may be unstable
723 | 14.05.2019 22:50:25 | INFO | HOSTER Keep2ShareCc[51505]: Grabbing link info...
724 | 14.05.2019 22:50:26 | DEBUG | HOSTER Keep2ShareCc[51505]: Link info: {'status': 2, 'hash': {},  'name': u'contraste.zip', 'url': u'https://k2s.cc/file/8fedab1515f88',  'pattern': {'ID': u'8fedab1515f88'}, 'access': u'public', 'size':  583036828, 'md5': u'1f960baf8308f5975fbfcd0c0e5801d9'}
725 | 14.05.2019 22:50:26 | DEBUG | HOSTER Keep2ShareCc[51505]: Previous link info: {}
726 | 14.05.2019 22:50:26 | INFO | HOSTER Keep2ShareCc[51505]: Link name: contraste.zip
727 | 14.05.2019 22:50:26 | INFO | HOSTER Keep2ShareCc[51505]: Link size: 556.03 MiB (583036828 bytes)
728 | 14.05.2019 22:50:26 | INFO | HOSTER Keep2ShareCc[51505]: Link status: online
729 | 14.05.2019 22:50:26 | INFO | HOSTER Keep2ShareCc[51505]: Processing url: https://k2s.cc/file/8fedab1515f88
730 | 14.05.2019 22:50:26 | INFO | HOSTER Keep2ShareCc[51505]: Looking for direct download link...
731 | 14.05.2019 22:50:26 | DEBUG | HOSTER Keep2ShareCc[51505]: LOAD URL  https://k2s.cc/file/8fedab1515f88 \| redirect=True \| cookies=True \|  get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \|  just_header=True
732 | 14.05.2019 22:50:26 | INFO | HOSTER Keep2ShareCc[51505]: Direct download link not found
733 | 14.05.2019 22:50:26 | DEBUG | HOSTER Keep2ShareCc[51505]: LOAD URL  https://k2s.cc/file/8fedab1515f88 \| redirect=True \| cookies=True \|  get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \|  just_header=False
734 | 14.05.2019 22:50:26 | INFO | HOSTER Keep2ShareCc[51505]: Checking for link errors...
735 | 14.05.2019 22:50:26 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
736 | 14.05.2019 22:50:26 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
737 | 14.05.2019 22:50:26 | DEBUG | ADDON ExternalScripts: No script found under folder `package_failed`
738 | 14.05.2019 22:50:26 | WARNING | Download failed: contraste.zip \| 'NoneType' object is not iterable
739 | 14.05.2019 22:50:26 | INFO | Debug Report written to debug_Keep2ShareCc_14-05-2019_22-50-26.zip
740 | 14.05.2019 22:50:26 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: contraste.zip (pid:365)
741 | 14.05.2019 22:50:26 | INFO | ADDON UnSkipOnFail: No duplicates found
742 | 14.05.2019 22:50:26 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
743 | 14.05.2019 22:50:26 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`

**Comment by LiloBzH** [comment]
same thing for me.
With every servers (uptobox uploaded etc ...)

Download failed: 9fplxxxxxxxxxx \| 'NoneType' object is not iterable

**Comment by LiloBzH** [comment]
@Web-Eye IF you have this old version, can you do a zip with ?

Thank's

**Comment by LiloBzH** [comment]
hum

    __name__ = "SimpleCrypter"
    __type__ = "crypter"
    __version__ = "0.93"
    __status__ = "testing"


0.95 ?!

**Comment by Web-Eye** [comment]
That's strange!

see https://github.com/pyload/pyload/commit/1865a1415d2d3517305f4fb26efade39a2350c28

[pyload_3387_workaround.zip](https://github.com/pyload/pyload/files/3182652/pyload_3387_workaround.zip)

remeber also to delete the pyc files, restart pyload and add files/packages again!

**Comment by LiloBzH** [comment]
hum ... plugins never update in my rasp .. i have lost plugin !! 

i dont understand why tss

**Comment by Kenifornication** [comment]
> [pyload_3387_workaround.zip](https://github.com/pyload/pyload/files/3182652/pyload_3387_workaround.zip)

Thank you very much, @Web-Eye :)

**Comment by LiloBzH** [comment]
@Web-Eye GG thank you ;)
