### ISSUE TITLE
Premium.to: NoneType' object is not iterable

### ISSUE THREAD

**Issue by elgreco29** [pyload/pyload#3388]
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [x] Bug report
- [ ] Question
- [ ] Other

### Summary:

Hi, here are the log if i tried to download a file from premium.to. Resetting pyload doesn't helps. If i create a remote link at premium.to, the download with the base plugin works.

### Debug log:

WARNING | HOSTER PremiumTo[9]: PremiumTo \| Plugin may be unstable
-- | --
65 | 15.05.2019 06:35:48 | INFO | ACCOUNT PremiumTo: Grabbing account info for user `
66 | 15.05.2019 06:35:48 | INFO | HOSTER PremiumTo[9]: PremiumTo \| Grabbing link info...
67 | 15.05.2019 06:35:48 | INFO | HOSTER PremiumTo[9]: PremiumTo \| Link name xxx.zip
68 | 15.05.2019 06:35:48 | INFO | HOSTER PremiumTo[9]: PremiumTo \| Link size: N/D
69 | 15.05.2019 06:35:48 | INFO | HOSTER PremiumTo[9]: PremiumTo \| Link status: starte
70 | 15.05.2019 06:35:48 | INFO | HOSTER PremiumTo[9]: PremiumTo \| Processing url: http://xxx.zip
71 | 15.05.2019 06:35:48 | INFO | HOSTER PremiumTo[9]: PremiumTo \| Looking for direct download link...
72 | 15.05.2019 06:35:48 | INFO | HOSTER PremiumTo[9]: PremiumTo \| Direct download link not found
73 | 15.05.2019 06:35:48 | INFO | HOSTER PremiumTo[9]: PremiumTo \| Checking for link errors...
74 | 15.05.2019 06:35:48 | WARNING | Download failed: xxx.zip \| 'NoneType' object is not iterable
75 | 15.05.2019 06:35:48 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of xxx.zip

!--- WRITE HERE - REQUIRED IF BUG REPORT -->

**Comment by Web-Eye** [comment]
Qick workaround: https://github.com/pyload/pyload/issues/3387#issuecomment-492645499
