### ISSUE TITLE
Update download queue entry with file name

### ISSUE THREAD

**Issue by Nippey** [pyload/pyload#3390]
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [x] Bug report
- [x] Question
- [ ] Other

### Summary:

Hi, 
I noticed that at least with shareonline, the name of the queue entry is always the URL.
This is inconventient, if I try to match real files with queue entries.

`{"status": 3, "format_size": "0.00 B", "name": "http://www.share-online.biz/dl/##########", "plugin": "ShareonlineBiz", "url": "http://www.share-online.biz/dl/##########", "packageID": 91, "fid": 1287, "error": "", "statusmsg": "eingereiht", "icon": "status_queue.png", "order": 0, "size": 0},`

But, the source code of ShareonlineBiz.py contains the function `api_info`, which is able to retrieve the File Name.
I expected that at latest when the DL is started, the name will be upgraded.

### How to reproduce:

Enqueue a DL link; it will only be called by its URL, even after starting a download.

### Expected behavior:

This is more a question:
__Shouldn't it update the entry name to the file name?__
__When should this happen? While adding or at start of download?__
__If the current behaviour is unintended; can I help to change it?__

My Idea: 
`If link.name == link.url Then link.name = filename`

Or is "name" informal and another entry "filename" should be added to the database?
`link.filename = filename`

### Debug log:

pyLoad knows the name...

`3740 | 15.05.2019 08:55:00 | INFO | HOSTER ShareonlineBiz[1268]: Grabbing link info...`
`3741 | 15.05.2019 08:55:00 | INFO | HOSTER ShareonlineBiz[1268]: Link name: xxxxxxxxxxxxxxx.part1.rar`

**Comment by GammaC0de** [comment]
Fixed.

**Comment by Nippey** [comment]
Cool, this changed something!
For unstarted downloads, the entry changed from:
http://www.share-online.biz/dl/##########
to:
http://www.share-online.biz/dl/########## **/######.zip**

But as soon as the download starts, the new name gets again replaced by:
http://www.share-online.biz/dl/##########

So, for the downloads, that are done (where I need their name) it isn't there..

Do you mind to take another look?

BR
Nippey

**Comment by GammaC0de** [comment]
@Nippey Do you have an example URL?

**Comment by Nippey** [comment]
Hi, 
I was digging a bit deeper.
Actually, it wasn't an issue with the Hoster itself, but the template.
It was just not clear to me yet, sorry.

I know, updates to the template will not go though the update manager, but maybe it still helps you.

BR
Nippey

**Comment by GammaC0de** [comment]
This is a PR for the master branch, not the stable. Are you sure this is really what you want? 

 
 
   Nippey<notifications@github.com> wrote:   
Hi,
I was digging a bit deeper.
Actually, it wasn't an issue with the Hoster itself, but the template.
It was just not clear to me yet, sorry.

I know, updates to the template will not go though the update manager, but maybe it still helps you.

BR
Nippey

**Comment by Nippey** [comment]
Sorry, fetched the wrong branch to update selected files from my pyload installation.
Everything is fine!!
