### ISSUE TITLE
NoneType object is not iterable UptoboxCom

### ISSUE THREAD

**Issue by sheryus** [pyload/pyload#3391]
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [x] Bug report
- [ ] Question
- [ ] Other

### Summary:

Hi, when i start a download i have this : échoué'NoneType' object is not iterable  UptoboxCom   [Supprimer lien]    [Relancer le lien] 

### How to reproduce:

Start a new download

**Comment by Web-Eye** [comment]
Qick workaround: https://github.com/pyload/pyload/issues/3387#issuecomment-492645499
