### ISSUE TITLE
error Uptobox plugin

### ISSUE THREAD

**Issue by foxan54** [pyload/pyload#3392]
Hello i'm sorry for my bad english
i have a ubuntu 18.04 with the [swizzin script](https://github.com/liaralabs/swizzin/blob/master/scripts/install/pyload.sh) so the install of pyload is `/home/user/.pyload`
i can download with 1fichier but i have some problem with uptobox
i have try 

`pyload stop`
`rm -rf <Config Folder>/userplugins`
`cd <Installation Folder>`
`wget https://github.com/pyload/pyload/archive/stable.zip`
`unzip ./stable.zip`
`cp -rf pyload-stable/* .`
`rm -rf ./pyload-stable`
`rm -f ./stable.zip`
`pyload start`

but it does not work
My logs errors
[log.txt](https://github.com/pyload/pyload/files/3184640/log.txt)

**Comment by GammaC0de** [comment]
Please disable `XFileSharing` plugin.

Also, I can see that you have a premium account for `UptoboxCom`, am I right?
If so, the account plugin for `UptoboxCom` might need updating, so:

Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by foxan54** [comment]
thank you for your reply
i disable xfilesharing plugin and it worked I can download with uptobox
I haven't a premium account.

Thx you again :)
