### ISSUE TITLE
Uptobox login url changed

### ISSUE THREAD

**Issue by adrienyhuel** [pyload/pyload#3395]
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [x] Bug report
- [ ] Question
- [ ] Other

### Summary:

Uptobox login url changed, so pyload can't login to premium account.

### Debug log:

28.05.2019 22:55:25 INFO      ACCOUNT UptoboxCom: Adding user `you*******`...
28.05.2019 22:55:25 DEBUG     ACCOUNT UptoboxCom: Reached login timeout for user `you*******`
28.05.2019 22:55:25 INFO      ACCOUNT UptoboxCom: Login user `you*******`...
28.05.2019 22:55:25 DEBUG     ACCOUNT UptoboxCom: LOAD URL https://uptobox.com/login.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
28.05.2019 22:55:26 DEBUG     ACCOUNT UptoboxCom: LOAD URL https://uptobox.com/ | redirect=True | cookies=True | get={'referer': 'homepage', 'op': 'login'} | req=None | decode=True | multipart=False | post={'login': 'you*******', 'password': '**********'} | ref=True | just_header=False
28.05.2019 22:55:26 ERROR     ACCOUNT UptoboxCom: Could not login user `you*******` | Login handshake has failed

### References:

Uptobox login url is no longer https://uptobox.com/?op=login&referer=homepage.
And logout url is no longer https://uptobox.com/?op=logout.
Now it is "https://uptobox.com/login?referer=homepage" and "https://uptobox.com/logout"

So you need to add in accounts/UptoboxCom.py : 
```
LOGIN_URL = "https://uptobox.com/login"
LOGIN_SKIP_PATTERN = "https://uptobox.com/logout"
```

And modify : 
```python
html = self.load(self.PLUGIN_URL,
                         get={'op': "login",'referer': "homepage"},
                         post={'login': user,
                               'password': password},
                         cookies=self.COOKIES)
```
to : 
```python
html = self.load(self.LOGIN_URL,
                         get={'referer': "homepage"},
                         post={'login': user,
                               'password': password},
                         cookies=self.COOKIES)
```

**Comment by yan059** [comment]
Thanks a lot

**Comment by Herbs851** [comment]
It works fine, thanks a lot :D !!!
