### ISSUE TITLE
Download menu is not working 

### ISSUE THREAD

**Issue by cerealconyogurt** [pyload/pyload#3397]
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [X] Bug report
- [ ] Question
- [ ] Other

### Summary:

Hi, when I tried to access to the Download menu in the web interface I've got a error message

### References:

An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/tmp/mnt/NAS2/entware/share/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/tmp/mnt/NAS2/entware/share/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/tmp/mnt/NAS2/entware/share/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/tmp/mnt/NAS2/entware/share/pyload/module/web/pyload_app.py", line 307, in downloads
elif isfile(join(root, item)):
File "/opt/lib/python2.7/genericpath.py", line 37, in isfile
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 39: ordinal not in range(128)

**Comment by GammaC0de** [comment]
What OS are you using?

**Comment by cerealconyogurt** [comment]
Hi, I am using Asus with Merlin firmware. 

OS:posix linux2 Linux AC68U 2.6.36.4brcmarm #1 SMP PREEMPT Wed Apr 3 18:37:21 EDT 2019 armv7l

pyLoad version:0.4.9

**Comment by GammaC0de** [comment]
What is the output of the `locale` command?

**Comment by cerealconyogurt** [comment]
Should I run pyLoadCore.py -local?

**Comment by GammaC0de** [comment]
No, just `locale` from the ssh console

**Comment by cerealconyogurt** [comment]
Ok! I will do that as soon as return to my home today. Thanks for your promptly reply.

**Comment by cerealconyogurt** [comment]
Hi, ssh console did not reply anything from `locale` since local does not exit... 

`-sh: locale: not found`

I run `env` and this is the output:

`SHLVL=1
TERMINFO=/opt/share/terminfo
HOME=/root
SSH_TTY=/dev/pts/0
PS1=\u@\h:\w\$
LOGNAME=
TEMP=/opt/tmp
TERM=xterm
PATH=/opt/bin:/opt/sbin:/bin:/usr/bin:/sbin:/usr/sbin:/home/xxxxxxxx:/mmc/sbin:/mmc/bin:/mmc/usr/sbin:/mmc/usr/bin:/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin
LANG=en_US.UTF-8
TMP=/opt/tmp
SHELL=/bin/sh
LC_ALL=en_US.UTF-8
PWD=/tmp/home/root`

So not sure if this help. I am asking how can get run `locale` in my Asuswrt-Merlin environment...
