### ISSUE TITLE
[Suggestion] Official docker

### ISSUE THREAD

**Issue by Ansem93** [pyload/pyload#3398]
HI,
I wandered if it would be possible to have an official docker repository.
I know that there are many forks, but I think that an official one would be the best thing

**Comment by GammaC0de** [comment]
There is https://github.com/obi12341/docker-pyload which you can call semi-official

**Comment by Ansem93** [comment]
Thanks! out of curiosity: how is possible that the size is 800Mb?!

**Comment by GammaC0de** [comment]
> out of curiosity: how is possible that the size is 800Mb?!

I really don't have a clue,
From https://hub.docker.com/r/writl/pyload/tags, `latest` is 352MB.
You can ask by opening an issue at https://github.com/obi12341/docker-pyload/issues.

Closing..
