### ISSUE TITLE
pyLoad doesn't show captcha with Tampermonkey

### ISSUE THREAD

**Issue by MaluNoPeleke** [pyload/pyload#3400]
I have updated pyLoad to the latest stable version as described in https://github.com/pyload/pyload/issues/3283 and I have installed Tampermonkey and the Interactive Captcha script on my Chrome 75 Windows Browser but every time a captcha should be solved with this the popup keeps telling me that it could a while to load but nothing happens.
With an enabled 9kw plugin it works.
What could be the problem?

**Comment by GammaC0de** [comment]
See https://github.com/pyload/pyload/issues/3264

**Comment by MaluNoPeleke** [comment]
Thanks but that seems to be a little bit risky.

**Comment by GammaC0de** [comment]
> that seems to be a little bit risky

Why is that?

What this addon does is to allow loading an iframe even when the site's policy don't allow it.

By default, most sites do allow loading iframes..

**Comment by MaluNoPeleke** [comment]
Quote from the addon description:

"Should be used only temporarily and only for developement, testing, or troubleshooting purposes because it disables important browser security mechanisms."

**Comment by GammaC0de** [comment]
The addon can be configured to be used only on specific web sites of your choice.

This is the only way to solve this issue.

Closing then.
