### ISSUE TITLE
Request to add Fileboom.me and ExtMatrix.com filehost plugins

### ISSUE THREAD

**Issue by WYLinD** [pyload/pyload#3406]
### Type of ticket:

- [x] Plugin request
- [x] Feature request
- [ ] Bug report
- [ ] Question
- [ ] Other

### Summary:

I would like to request for the file hosting sites Fileboom.me and Extmatrix.com to be added in the filehost plugin in pyload if possible. 

Thank you very much

**Comment by GammaC0de** [comment]
Fileboom.me is already supported

**Comment by GammaC0de** [comment]
Sample URL for extmatrix.com please.

**Comment by WYLinD** [comment]
Thanks for the information on the support of Fileboom.me though I cannot seem to find it on the filehost listing on the Download Station application on my Synology NAS DSM. Their support team asked me to send in a request to add filehost plug-ins here.

As the sample URL for ExtMatrix.com, please see below:
https://www.extmatrix.com/files/TVOFZQ5G/JUY-886-1080p.mp4.html

Thank you very much for considering my request for filehost plug-in additions.

**Comment by GammaC0de** [comment]
DownloadStation is made by Synology,
pyLoad is another download application independent of DownloadStation.

https://www.extmatrix.com/files/TVOFZQ5G/JUY-886-1080p.mp4.html requires a premium account for downloading,

Do you have a premium extmatrix account?
Do you have another URL that does not require a premium account?

**Comment by WYLinD** [comment]
Hi,

Please use the following login info for your coding purposes:
weiyenlin@gmail.com : eR$05!a@nkVi

Thanks

**Comment by WYLinD** [comment]
> Fileboom.me is already supported

I checked with Synology (as they use the pyload file host plug-ins as part of their Download Station), according to them, the current Pyload Fileboom.me filehost plug-in does not support download tasks that require user account verification. 

Hence is it okay if I add the request for Fileboom.me filehost plug-in to support download tasks with user account verification? You can use the following login credentials for testing:
weiyenlin@gmail.com : fJ0nhA1R&$&E

THank you very much!

**Comment by GammaC0de** [comment]
OK :+1: ,

Next time, please do not post here sensitive data like your user and password.
The procedure is that you change your password to a temporary password and send it by email.

**Comment by WYLinD** [comment]
Noted on the procedure. 

Thank you very much in advance!

**Comment by GammaC0de** [comment]
Added Extmatrix plugin https://github.com/pyload/pyload/commit/542f5cec6157b5c5814888d0978d97096d3c4ae8

**Comment by WYLinD** [comment]
Thank You very much!
