### ISSUE TITLE
Webinterface not accessible, CLI works fine

### ISSUE THREAD

**Issue by Ikosihenagon** [pyload/pyload#3409]
### Describe the problem

After installing pyLoad and starting it for the first time, the configuration menu is skipped and pyLoad starts directly. The configuration can nevertheless be done with pyLoad -s. After configuration only CLI is working. When I try to login to the webinterface, I get the following error in my browser (firefox): "Critical error while processing request: /login". The Terminal shows me this: `<h1>Critical error while processing request: /login</h1> 23.06.2019 08:48:08 ERROR     ADDON ClickNLoad: [Errno 98] Address already in use
23.06.2019 08:52:08 ERROR     ADDON ClickNLoad: [Errno 98] Address already in use`.

The Debug report (attached) gives me the error "template not found". The solution in "WebUI not loading [#3043"]" (https://github.com/pyload/pyload/issues/3043) does not solve the problem. Reinstalling does also not solve the problem. System is Debian Stretch.

Thank you very much for helping.

### Debug log

Critical error while processing request: /login
Error:

TemplateNotFound()

Traceback:

Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 820, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/usr/share/pyload/module/lib/bottle.py", line 773, in _cast
    out = self.error_handler.get(out.status, repr)(out)
  File "/usr/share/pyload/module/web/pyload_app.py", line 83, in error500
    error.traceback.replace("\n", "
") if error.traceback else "No Traceback"])
  File "/usr/share/pyload/module/web/pyload_app.py", line 72, in base
    return render_to_response('base.html', {'messages': messages}, [pre_processor])
  File "/usr/share/pyload/module/web/utils.py", line 29, in render_to_response
    t = env.get_template(TEMPLATE + "/" + name)
  File "/usr/share/pyload/module/lib/jinja2/environment.py", line 716, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/share/pyload/module/lib/jinja2/environment.py", line 690, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/share/pyload/module/lib/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/share/pyload/module/lib/jinja2/loaders.py", line 339, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: classic/base.html

**Comment by GammaC0de** [comment]
Hi,
It seems that your installation is missing some files.

How exactly have you installed pyLoad?

**Comment by Ikosihenagon** [comment]
Hi,

I've installed as described in the [Step-by-Step Installation (Linux)](https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(Linux)) guide and downloaded the pyload_0.4.9_all.deb package. Before I've also checked the pyLoad page at [debianfoum.de](https://wiki.debianforum.de/PyLoad) and installed all packages which are listed there or rather checked that they are already installed in the current version. 

Is there any possibility to check what is missing?

Thanks

**Comment by GammaC0de** [comment]
Donload the latest stable branch (https://github.com/pyload/pyload/archive/stable.zip), extract it to /usr/share/pyload, overwriting the old files.

**Comment by Ikosihenagon** [comment]
Thank you very much! Overwriting the files solved the problem. 

Is there anything missing in the file mentioned in the installation guide? Just to eventually inform the right person to check if the link should be updated.

**Comment by GammaC0de** [comment]
>Thank you very much! Overwriting the files solved the problem.

Great :+1: 

>Is there anything missing in the file mentioned in the installation guide? Just to eventually inform the right person to check if the link should be updated.

Sorry, I could not understand your question..

**Comment by Evil-uncelz** [comment]
Abbrechen
GammaC0de <notifications@github.com> schrieb am Sa., 29. Juni 2019, 21:35:

**Comment by Ikosihenagon** [comment]
I just thought that there is something missing in the pyload_0.4.9_all.deb on the download page mentioned in the installation guide I've used. Since your link lead me to the latest stable release, there is obviously a difference between the one you linked to and the pyload_0.4.9_all.deb.
