### ISSUE TITLE
Share-online fall back in free modus

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#3410]
### Describe the problem
I have a problem with share-online. If i want to download files, share online fall at start very often in free modus and want to solve captchas. But i'm a premium user. This error comes with every start in pyload.

### Debug log

4848	25.06.2019 20:03:56	INFO	Download skipped: xxx.rar due to File exists
4847	25.06.2019 20:03:56	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
4846	25.06.2019 20:03:56	INFO	HOSTER ShareonlineBiz[4192]: Link status: online
4845	25.06.2019 20:03:56	INFO	HOSTER ShareonlineBiz[4192]: Link size: 149.00 MiB (156237924 bytes)
4844	25.06.2019 20:03:56	INFO	HOSTER ShareonlineBiz[4192]: Link name: xxx.rar
4843	25.06.2019 20:03:56	DEBUG	HOSTER ShareonlineBiz[4192]: Previous link info: {'status': 2, 'hash': {}, 'name': 'xxx.rar', 'url': u'xxx', 'pattern': {'ID': u'xxx'}, 'fileid': 'xxx', 'md5': '4010149656e9c1f858fad93d0f491d15', 'size': 156237924}
4842	25.06.2019 20:03:56	DEBUG	HOSTER ShareonlineBiz[4192]: Link info: {'status': 2, 'hash': {}, 'name': 'xxx.rar', 'url': u'xxx', 'pattern': {'ID': u'xxx'}, 'size': 156237924, 'md5': '4010149656e9c1f858fad93d0f491d15', 'fileid': 'xxx'}
4841	25.06.2019 20:03:56	INFO	HOSTER ShareonlineBiz[4192]: Grabbing link info...
4840	25.06.2019 20:03:56	DEBUG	ACCOUNT ShareonlineBiz: Account info for user `xxx`: {'login': {'timestamp': 1561485651.831434, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 104857600.0, 'maxtraffic': None, 'validuntil': 1617902849.0, 'login': 'xxx', 'type': 'ShareonlineBiz', 'options': {'limitDL': ['0']}}}
4839	25.06.2019 20:03:56	DEBUG	ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': 'xxx', 'password': '**********'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
4838	25.06.2019 20:03:56	INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `xxx`...
4837	25.06.2019 20:03:56	WARNING	HOSTER ShareonlineBiz[4192]: Plugin may be unstable
4836	25.06.2019 20:03:56	DEBUG	HOSTER ShareonlineBiz[4192]: Plugin status: testing
4835	25.06.2019 20:03:56	DEBUG	HOSTER ShareonlineBiz[4192]: Plugin version: 0.71
4834	25.06.2019 20:03:56	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
4833	25.06.2019 20:03:56	DEBUG	ADDON UserAgentSwitcher: Setting maximum redirections to 10
4832	25.06.2019 20:03:56	DEBUG	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
4831	25.06.2019 20:03:56	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
4830	25.06.2019 20:03:56	INFO	Download starts: xxx.rar
4829	25.06.2019 20:03:56	INFO	Download restarted: xxx.rar | precheck
4828	25.06.2019 20:03:56	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
4827	25.06.2019 20:02:54	INFO	HOSTER ShareonlineBiz[4192]: Waiting 1 minutes...
4826	25.06.2019 20:02:54	DEBUG	HOSTER ShareonlineBiz[4192]: WAIT set to timestamp 1561485835.066236 | Previous waitUntil: 0.000000
4825	25.06.2019 20:02:54	ERROR	HOSTER ShareonlineBiz[4192]: precheck | Es ist ein unbekannter Fehler aufgetreten!
4824	25.06.2019 20:02:54	INFO	HOSTER ShareonlineBiz[4192]: File is OK
4823	25.06.2019 20:02:54	INFO	HOSTER ShareonlineBiz[4192]: Checking download...
4822	25.06.2019 20:02:54	INFO	HOSTER ShareonlineBiz[4192]: File saved
4821	25.06.2019 20:02:48	DEBUG	CAPTCHA ShareonlineBiz[4193]: ReCaptcha | Challenge reCAPTCHA v2 interactive
4820	25.06.2019 20:02:48	WARNING	CAPTCHA ShareonlineBiz[4193]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
4819	25.06.2019 20:02:47	DEBUG	HOSTER ShareonlineBiz[4193]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6LdnPkIUAAAAABqC_ITR9-LTJKSdyR_Etj1Sf-Xi | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=xxx | just_header=False
4818	25.06.2019 20:02:47	WARNING	CAPTCHA ShareonlineBiz[4193]: ReCaptcha | Secure Token pattern not found
4817	25.06.2019 20:02:47	DEBUG	CAPTCHA ShareonlineBiz[4193]: ReCaptcha | Detected reCAPTCHA v2
4816	25.06.2019 20:02:47	WARNING	CAPTCHA ShareonlineBiz[4193]: ReCaptcha | Secure Token pattern not found
4815	25.06.2019 20:02:47	DEBUG	CAPTCHA ShareonlineBiz[4193]: ReCaptcha | Key: 6LdnPkIUAAAAABqC_ITR9-LTJKSdyR_Etj1Sf-Xi
4814	25.06.2019 20:02:47	DEBUG	HOSTER ShareonlineBiz[4193]: LOAD URL xxx/free/ | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'dl_free': '1', 'choice': 'free'} | ref=True | just_header=False
4813	25.06.2019 20:02:43	INFO	HOSTER ShareonlineBiz[4193]: Waiting 3 seconds...
4812	25.06.2019 20:02:43	DEBUG	HOSTER ShareonlineBiz[4193]: WAIT set to timestamp 1561485767.846971 | Previous waitUntil: 0.000000
4811	25.06.2019 20:02:43	INFO	HOSTER ShareonlineBiz[4193]: Processing as free download...
4810	25.06.2019 20:02:43	DEBUG	HOSTER ShareonlineBiz[4193]: LOAD URL xxx | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
4809	25.06.2019 20:02:43	INFO	HOSTER ShareonlineBiz[4193]: Direct download link not found
4808	25.06.2019 20:02:43	DEBUG	HOSTER ShareonlineBiz[4193]: LOAD URL xxx | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
4807	25.06.2019 20:02:43	INFO	HOSTER ShareonlineBiz[4193]: Looking for direct download link...
4806	25.06.2019 20:02:43	INFO	HOSTER ShareonlineBiz[4193]: Processing url: xxx
4805	25.06.2019 20:02:43	INFO	HOSTER ShareonlineBiz[4193]: Link status: online
4804	25.06.2019 20:02:43	INFO	HOSTER ShareonlineBiz[4193]: Link size: 149.00 MiB (156237924 bytes)
4803	25.06.2019 20:02:43	INFO	HOSTER ShareonlineBiz[4193]: Link name: xxx.rar
4802	25.06.2019 20:02:43	DEBUG	HOSTER ShareonlineBiz[4193]: Previous link info: {'status': 2, 'hash': {}, 'name': 'xxx.rar', 'url': u'xxx', 'pattern': {'ID': u'xxx'}, 'fileid': 'xxx', 'md5': 'a68fa6f44e703f785fe1566b836b4042', 'size': 156237924}
4801	25.06.2019 20:02:43	DEBUG	HOSTER ShareonlineBiz[4193]: Link info: {'status': 2, 'hash': {}, 'name': 'xxx.rar', 'url': u'xxx', 'pattern': {'ID': u'xxx'}, 'size': 156237924, 'md5': 'a68fa6f44e703f785fe1566b836b4042', 'fileid': 'xxx'}
4800	25.06.2019 20:02:43	INFO	HOSTER ShareonlineBiz[4193]: Grabbing link info...
4799	25.06.2019 20:02:43	WARNING	HOSTER ShareonlineBiz[4193]: Plugin may be unstable
4798	25.06.2019 20:02:43	DEBUG	HOSTER ShareonlineBiz[4193]: Plugin status: testing
4797	25.06.2019 20:02:43	DEBUG	HOSTER ShareonlineBiz[4193]: Plugin version: 0.71
4796	25.06.2019 20:02:43	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
4795	25.06.2019 20:02:43	DEBUG	ADDON UserAgentSwitcher: Setting maximum redirections to 10
4794	25.06.2019 20:02:43	DEBUG	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
4793	25.06.2019 20:02:43	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
4792	25.06.2019 20:02:43	INFO	Download starts: xxx.rar
4791	25.06.2019 20:02:43	INFO	Download restarted: xxx.rar | Fallback to free processing
4790	25.06.2019 20:02:43	DEBUG	ADDON ExternalScripts: No script found under folder `download_processed`
4789	25.06.2019 20:02:43	WARNING	HOSTER ShareonlineBiz[4193]: Premium download failed | downloade
4788	25.06.2019 20:02:35	DEBUG	HOSTER ShareonlineBiz[4193]: DOWNLOAD URL http://dlw451-1.share-online.biz/dl?u=C6442BE9C0242BEDF04929E4C0472AEF953E22BEF044798C9D412B90943E46EDE8482396EB4903DD97342CED902A4EA9&q=v4 | fixurl=True | resume=None | get={} | cookies=True | disposition=True | chunks=None | post={} | ref=True
4787	25.06.2019 20:02:35	INFO	HOSTER ShareonlineBiz[4193]: Downloading file...
4786	? 	?	MD5: a68fa6f44e703f785fe1566b836b4042
4785	? 	?	SIZE: 156237924
4784	? 	?	NAME: xxx.rar
4783	? 	?	ID: xxx
4782	? 	?	URL: http://dlw451-1.share-online.biz/dl?u=C6442BE9C0242BEDF04929E4C0472AEF953E22BEF044798C9D412B90943E46EDE8482396EB4903DD97342CED902A4EA9&q=v4
4781	25.06.2019 20:02:35	DEBUG	HOSTER ShareonlineBiz[4193]: STATUS: online
4780	25.06.2019 20:02:35	DEBUG	HOSTER ShareonlineBiz[4193]: LOAD URL https://api.share-online.biz/account.php | redirect=True | cookies=True | get={'username': 'xxx', 'lid': 'xxx', 'password': '**********', 'act': 'download'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
4779	25.06.2019 20:02:35	INFO	HOSTER ShareonlineBiz[4193]: Processing as premium download...
4778	25.06.2019 20:02:35	INFO	HOSTER ShareonlineBiz[4193]: Filesize: 152576 KiB | Traffic left for user `xxx`: 104857600 KiB
4777	25.06.2019 20:02:35	DEBUG	ACCOUNT ShareonlineBiz: Account info for user `xxx`: {'login': {'timestamp': 1561485651.831434, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 104857600.0, 'maxtraffic': None, 'validuntil': 1617902849.0, 'login': 'xxx', 'type': 'ShareonlineBiz', 'options': {'limitDL': ['0']}}}
4776	25.06.2019 20:02:35	DEBUG	ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': 'xxx', 'password': '**********'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
4775	25.06.2019 20:02:35	INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `xxx`...
4774	25.06.2019 20:02:35	DEBUG	HOSTER ShareonlineBiz[4193]: LOAD URL xxx | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
4773	25.06.2019 20:02:35	INFO	HOSTER ShareonlineBiz[4193]: Direct download link not found
4772	25.06.2019 20:02:35	DEBUG	HOSTER ShareonlineBiz[4193]: LOAD URL xxx | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
4771	25.06.2019 20:02:35	INFO	HOSTER ShareonlineBiz[4193]: Looking for direct download link...
4770	25.06.2019 20:02:35	INFO	HOSTER ShareonlineBiz[4193]: Processing url: xxx
4769	25.06.2019 20:02:35	INFO	HOSTER ShareonlineBiz[4193]: Link status: online
4768	25.06.2019 20:02:35	INFO	HOSTER ShareonlineBiz[4193]: Link size: 149.00 MiB (156237924 bytes)
4767	25.06.2019 20:02:35	INFO	HOSTER ShareonlineBiz[4193]: Link name: xxx.rar
4766	25.06.2019 20:02:35	DEBUG	HOSTER ShareonlineBiz[4193]: Previous link info: {}
4765	25.06.2019 20:02:35	DEBUG	HOSTER ShareonlineBiz[4193]: Link info: {'status': 2, 'hash': {}, 'name': 'xxx.rar', 'url': u'xxx', 'pattern': {'ID': u'xxx'}, 'size': 156237924, 'md5': 'a68fa6f44e703f785fe1566b836b4042', 'fileid': 'xxx'}
4764	25.06.2019 20:02:35	INFO	HOSTER ShareonlineBiz[4193]: Grabbing link info...
4763	25.06.2019 20:02:35	DEBUG	ACCOUNT ShareonlineBiz: Account info for user `xxx`: {'login': {'timestamp': 1561485651.831434, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': 104857600.0, 'maxtraffic': None, 'validuntil': 1617902849.0, 'login': 'xxx', 'type': 'ShareonlineBiz', 'options': {'limitDL': ['0']}}}
4762	25.06.2019 20:02:35	DEBUG	ACCOUNT ShareonlineBiz: LOAD URL https://api.share-online.biz/cgi-bin | redirect=True | cookies=True | get={'q': 'userdetails', 'aux': 'traffic', 'username': 'xxx', 'password': '**********'} | req=None | decode=False | multipart=False | post={} | ref=True | just_header=False
4761	25.06.2019 20:02:35	INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `xxx`...
4760	25.06.2019 20:02:35	WARNING	HOSTER ShareonlineBiz[4193]: Plugin may be unstable
4759	25.06.2019 20:02:35	DEBUG	HOSTER ShareonlineBiz[4193]: Plugin status: testing
4758	25.06.2019 20:02:35	DEBUG	HOSTER ShareonlineBiz[4193]: Plugin version: 0.71
4757	25.06.2019 20:02:35	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
4756	25.06.2019 20:02:35	DEBUG	ADDON UserAgentSwitcher: Setting maximum redirections to 10
4755	25.06.2019 20:02:35	DEBUG	ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
4754	25.06.2019 20:02:35	DEBUG	ADDON ExternalScripts: No script found under folder `download_preparing`
4753	25.06.2019 20:02:35	INFO	Download starts: xxx
4752	25.06.2019 20:02:33	DEBUG	HOSTER ShareonlineBiz[4192]: DOWNLOAD URL http://dlw373-2.share-online.biz/dl?u=C5445CE9C0232BEDF24929E4C0472AEF953E22BEF044228C9D412BEB94496CEDF6362CCBF243159A9C274DED92733FF8&q=v4 | fixurl=True | resume=None | get={} | cookies=True | disposition=True | chunks=None | post={} | ref=True
4751	25.06.2019 20:02:33	INFO	HOSTER ShareonlineBiz[4192]: Downloading file...

**Comment by Gerold68** [comment]
Same issue here for some weeks. In my case it is always the 2. file of a new started queue which falls back in free mode. The next files are downloaded in premium mode again.

**Comment by Mister-XY** [comment]
Also the same.

**Comment by GammaC0de** [comment]
Does this happen with plugin v0.70 also??

**Comment by Mister-XY** [comment]
Yes, this happens also with the 0.70 Version.

**Comment by Gerold68** [comment]
I have used 0.65 for a long time without issues.

**Comment by Gerold68** [comment]
How can i void that the updater replaces 0.65 with 0.70?

**Comment by Mister-XY** [comment]
Sorry Mate, i see, that i have version 0.71

**Comment by Mister-XY** [comment]
I have sent you the account data, please test it.

**Comment by GammaC0de** [comment]
Plugin updated, please test.

**Comment by Gerold68** [comment]
So, i have restarted pyload. The plugins are up to date. In the plugin source i see version 0.72.
I started a queue and the second file failed with a message 

INFO | HOSTER ShareonlineBiz[2]: Looking for direct download link...
-- | --
340 | 09.07.2019 19:07:30 | INFO | HOSTER ShareonlineBiz[2]: Direct download link not found
341 | 09.07.2019 19:07:30 | INFO | HOSTER ShareonlineBiz[2]: Processing as free download...
342 | 09.07.2019 19:07:30 | INFO | HOSTER ShareonlineBiz[2]: Waiting 3 seconds...
343 | 09.07.2019 19:07:34 | WARNING | CAPTCHA ShareonlineBiz[2]: ReCaptcha \| Secure Token pattern not found
344 | 09.07.2019 19:07:34 | WARNING | CAPTCHA ShareonlineBiz[2]: ReCaptcha \| Secure Token pattern not found
345 | 09.07.2019 19:07:34 | WARNING | CAPTCHA ShareonlineBiz[2]: ReCaptcha \| reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
346 | 09.07.2019 19:07:34 | WARNING | Download failed: Escape.Room.2019.part01.rev \| newTask() takes exactly 5 arguments (4 given)

I have aborted the downloads and reset and restarted the queue. Then all files went well incl. the second file.

Is it possible to avoid the update off this plugin. Like i wrote, version 0.65 work without any problem.

Tnx for digging into it.

G68

**Comment by GammaC0de** [comment]
Version 0.65 is from 2017, are you sure it works OK?

@Mister-XY Can you confirm it is not fixed?

**Comment by CrazyDornie** [comment]
For me 0.72 is not working...

213 | 12.07.2019 19:32:48 | INFO | HOSTER ShareonlineBiz[2157]: Processing as free download...
212 | 12.07.2019 19:32:48 | INFO | HOSTER ShareonlineBiz[2157]: Direct download link not found
211 | 12.07.2019 19:32:48 | INFO | HOSTER ShareonlineBiz[2157]: Looking for direct download link...

**Comment by Gerold68** [comment]
I have tried 0.66 again but behaviour is like 0.72. Plugin falls back in free mode but only for the 2. file of a fresh started queue. Something has changed on the hosters side.

**Comment by CrazyDornie** [comment]
I have to withdraw my statement. Account was locked on hoster site. For me everything works fine now.

**Comment by GammaC0de** [comment]
>I have tried 0.66 again but behaviour is like 0.72.

This is what I suspect, share-online probably changed something on their side..

@Gerold68 Can you provide a debug log?

**Comment by daill** [comment]
I had the same problem two days ago. Interestingly the same dlc file works now properly. Maybe it was just a temporary problem?

**Comment by Gerold68** [comment]
Today it works like before, the strange behvior is gone. Seems it was just a temperary Share Online Issue.

**Comment by Mister-XY** [comment]
I will test it also.

**Comment by igno2k** [comment]
I have exactly the same problem. Premium account is unlocked and fully functional. Any ideas?

**Comment by Niach** [comment]
Same problem here, asks for captcha every time
