### ISSUE TITLE
autologin option ignored and removed upon start

### ISSUE THREAD

**Issue by lorenzschmid** [pyload/pyload#3413]
### Describe the problem
It seems like the autologin functionality is not working: When adding the `autologin` option to the `webinterface` section of the configuration file, the option is removed upon restart by pyload. Thus, it is never applied and the autologin functionality not working.

```python
webinterface - "Webinterface":
	...
	bool autologin : "Skip login if single user" = True
```

### Expected behavior
- Setting the configuration file as given by the example above
- Browse to the pyload instance and access without login (considering that there is only one user existing)

### Actual behavior
- Setting the configuration file as given by the example above
- Browse to the pyload instance and be presented with a login screen (i.e. no autologin)
- Upon verifying the settings in the configuration file discovering that the previous `autlogin` parameter is missing:

```python
webinterface - "Webinterface":
	...
```

### To reproduce
- Set the `autlogin` option as described in the example above

### Debug log
```
01.07.2019 12:30:10 INFO      Starting pyLoad 0.4.9
01.07.2019 12:30:10 INFO      Using home directory: /config
01.07.2019 12:30:16 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
01.07.2019 12:30:16 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
01.07.2019 12:30:16 INFO      Downloadtime: True
01.07.2019 12:30:18 INFO      Starting builtin webserver: 0.0.0.0:8000
01.07.2019 12:30:18 INFO      Free space: XXX
01.07.2019 12:30:18 INFO      Activating Accounts...
01.07.2019 12:30:18 INFO      Activating Plugins...
01.07.2019 12:30:19 INFO      ADDON XFileSharing: Auto-discover new hosters
01.07.2019 12:30:19 INFO      ADDON UpdateManager: pyLoad is up to date!
01.07.2019 12:30:19 INFO      ADDON XFileSharing: Auto-discover new crypters
01.07.2019 12:30:19 INFO      pyLoad is up and running
01.07.2019 12:30:19 INFO      ADDON UpdateManager: All plugins are up to date!
01.07.2019 12:30:25 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
```

**Comment by HVR88** [comment]
As of April 2024, setting AUTOLOGIN to TRUE causes the web interface to fail - no web browser will connect.

**Comment by GammaC0de** [comment]
> As of April 2024, setting AUTOLOGIN to TRUE causes the web interface to fail - no web browser will connect.

I have tested this with and without docker and it worked fine.
I you still having problems, please proved debug logs.

**Comment by HVR88** [comment]
Problem went away with an update and is now working correctly. I created an issue for the specific problem, which I'll be closing.
