### ISSUE TITLE
HOSTER FilejokerNet[26]: Free download failed | Parse error: Too many OPs

### ISSUE THREAD

**Issue by ryester27** [pyload/pyload#3414]
### Describe the problem

Free Filejoker downloads sometimes fail due to a "Parse error: Too many OPs" error

### Expected behavior

Download should start immediately after solving the captcha

### Actual behavior

Error is thrown, and the file is skipped over. Happens about 50% of the time when captcha solving is automated using the 9kw plugin

### To reproduce

1) Add a bunch of Filejoker links to the queue
2) profit

### Debug log

[log1.txt](https://github.com/pyload/pyload/files/3350095/log1.txt)

### Additional references

As mentioned before, I'm also using the 9kw plugin. Dunno if that complicates things

**Comment by GammaC0de** [comment]
Please disable XFileSharing plugin.

**Comment by ryester27** [comment]
> Please disable XFileSharing plugin.

Just deactivated that "XFileSharing dummy hoster plugin for hook" plugin. I'll let you know how it was once this queue clears up in a few days

**Comment by ryester27** [comment]
Good Morning. Woke up to 2 more more Parse errors, and that was with the XFileSharing plugin deactivated. New log attached

[new_log.txt](https://github.com/pyload/pyload/files/3354936/new_log.txt)

**Comment by GammaC0de** [comment]
I do not see any parse errors on the log...

**Comment by ryester27** [comment]
> I do not see any parse errors on the log...

They're the lines marked as number 122, 124, 259, and 261

**Comment by GammaC0de** [comment]
Plugin updated (v0.07), please test.

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by ryester27** [comment]
Sorry. I didn't forget about this. I just don't have anything to download right now. I'll make sure to let you know once I do

**Comment by ryester27** [comment]
Good morning. I was able to get 2 separate Filejoker download to start one after another, so that's a good sign. Still haven't done a download with multiple parts, but I will keep you updated when I do

**Comment by ryester27** [comment]
Just had 6 consecutive Filejoker links start without issue. Marking this as resolved and closed
