### ISSUE TITLE
How can I delete all queue list from command

### ISSUE THREAD

**Issue by cerealconyogurt** [pyload/pyload#3416]
### Your question

How I can delete the whole queue list from command? I mess up pyLoad when I was trying to download from FTP server couple of files. For some reason I have in queue several files and the queue webinterface is useless

**Comment by GammaC0de** [comment]
* Browse to `http://<PYLOAD_IP>/info` and write down the value of `Config Folder`.
* Stop pyLoad.
* Delete the file `files.db` which resides on the  `Config Folder`.
* Start pyLoad`s configuration again (pyLoadCore.py -s).
* Start pyLoad.

**Comment by cerealconyogurt** [comment]
This fixed the problem. Thanks!

**Comment by defencedog** [comment]
Its not a elegant method ...I mean i delete `files.db` & have to go through setting up user / psw from scratch...
