### ISSUE TITLE
Fshare.vn plugin cannot login

### ISSUE THREAD

**Issue by bigdargon** [pyload/pyload#3417]
### Describe the problem

When I restart the device, the plugin cannot login
```
470	07.07.2019 20:25:30	INFO	ACCOUNT FshareVn: Adding user `myh*******`...
471	07.07.2019 20:25:30	INFO	ACCOUNT FshareVn: Login user `myh*******`...
472	07.07.2019 20:25:33	ERROR	ACCOUNT FshareVn: Could not login user `myh*******` | Login handshake has failed
```
When I add a new download link, I receive an error
```
586	07.07.2019 22:57:37	INFO	ACCOUNT FshareVn: Relogin user `None`...
587	07.07.2019 22:57:37	ERROR	ACCOUNT FshareVn: Could not login user `None` | 'login'
588	07.07.2019 22:57:37	WARNING	Download failed: https://www.fshare.vn/file/LCMSTJXRR9RR | 'login' 
```
Link test: https://www.fshare.vn/file/LCMSTJXRR9RR
I sent a premium account to email `nitzo2001 at yahoo dot com`

I found fshare has a direct download feature, if  the vip account when downloading the link will automatically download. Can Pyload download and capture the filename directly?

**Comment by GammaC0de** [comment]
![Capture](https://user-images.githubusercontent.com/11036551/60828897-5005ed00-a1bc-11e9-98b9-1d04ed0c7d8e.PNG)


Whats is this?

**Comment by bigdargon** [comment]
Sorry! This is like 2-step authentication, I turned it off.  You can try logging in again! Thanks

**Comment by GammaC0de** [comment]
After disabling 2-step authentication, plugin works fine...

**Comment by bigdargon** [comment]
the plugin still cannot login :( 

```
751 10.07.2019 06:15:58	INFO	ACCOUNT FshareVn: Updating account info for user `myh*******`...
752	10.07.2019 06:15:58	INFO	ACCOUNT FshareVn: Relogin user `myh*******`...
753	10.07.2019 06:16:01	INFO	ACCOUNT FshareVn: Updating account info for user `myh*******`...
754	10.07.2019 06:16:01	INFO	ACCOUNT FshareVn: Relogin user `myh*******`...
755	10.07.2019 06:16:03	ERROR	ACCOUNT FshareVn: Could not login user `myh*******` | Login handshake has failed
```

**Comment by GammaC0de** [comment]
Hello,
Why do I get this message when logging in to the web site?

![Capture](https://user-images.githubusercontent.com/11036551/61134500-68318100-a4c8-11e9-9123-c4f52e9dc26a.PNG)

**Comment by bigdargon** [comment]
fshare security upgrade, recording the number of ip account login.  If I see the above message, I must log in and delete the logged-in sessions.  I deleted the login session, you can try again!  I noticed pyload started downloading and will log back into the account, so the number of login ip increased!

**Comment by GammaC0de** [comment]
OK, so no login with pyload is fine.

**Comment by bigdargon** [comment]
It’s working! Thanks you!
```
823 13.07.2019 22:36:14	INFO	ACCOUNT FshareVn: Adding user `myh*******`...
824	13.07.2019 22:36:14	INFO	ACCOUNT FshareVn: Login user `myh*******`...
825	13.07.2019 22:36:14	WARNING	ACCOUNT FshareVn: Skipped login user `myh*******` | Already signed in
826	13.07.2019 22:36:14	INFO	ACCOUNT FshareVn: Grabbing account info for user `myh*******`...
```
