### ISSUE TITLE
Uploadgig Plugin "Bad server response: 403 Forbidden"

### ISSUE THREAD

**Issue by chodid** [pyload/pyload#3424]
Hello!

I stumpeled upon a problem when downloading uploadgig files...
Adding the uploadgig account works fine, just when trying to download something - this is the error message that gets shown "Bad server response: 403 Forbidden".

The corresponding log entries are:
```
313 | 05.08.2019 20:48:30 | INFO | Download starts: **************
-- | -- | -- | --
314 | 05.08.2019 20:48:30 | WARNING | HOSTER UploadgigCom[1]: Plugin may be unstable
315 | 05.08.2019 20:48:30 | INFO | ACCOUNT UploadgigCom: Relogin user `**********`...
316 | 05.08.2019 20:48:30 | INFO | ACCOUNT UploadgigCom: Grabbing account info for user `***********`...
317 | 05.08.2019 20:48:30 | INFO | HOSTER UploadgigCom[1]: Grabbing link info...
318 | 05.08.2019 20:48:30 | INFO | HOSTER UploadgigCom[1]: Link name: ********
319 | 05.08.2019 20:48:30 | INFO | HOSTER UploadgigCom[1]: Link size: 13.60 MiB
320 | 05.08.2019 20:48:30 | INFO | HOSTER UploadgigCom[1]: Link status: online
321 | 05.08.2019 20:48:30 | INFO | HOSTER UploadgigCom[1]: Processing url: https://uploadgig.com/file/download/*****
322 | 05.08.2019 20:48:30 | INFO | HOSTER UploadgigCom[1]: Looking for direct download link...
323 | 05.08.2019 20:48:31 | WARNING | Download failed: ******** \| Bad server response: 403 Forbidden
324 | 05.08.2019 20:48:31 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: ********* (pid:1)
325 | 05.08.2019 20:48:31 | INFO | ADDON UnSkipOnFail: No duplicates found
```

The error occurs regardless of file type - this one was a file I uploaded myself. Downloading via the website worked perfectly fine.
If needed I can provide account details for testing, no problem.

Thanks in advance!

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by chodid** [comment]
Any news?

**Comment by GammaC0de** [comment]
> Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

Have you sent the account information?

**Comment by chodid** [comment]
On August 6th, yes. Email went out to nitzo2001 at yahoo dot com

**Comment by GammaC0de** [comment]
Oops, it went into spam :(

**Comment by GammaC0de** [comment]
Can you provide debug log?
For me it works fine..

**Comment by chodid** [comment]
I haven't tried it in a while - now the error message seems to have changed :/

`
955 | 02.09.2019 15:05:01 | INFO | ADDON UpdateManager: pyLoad is up to date!
-- | -- | -- | --
956 | 02.09.2019 15:05:01 | INFO | ADDON UpdateManager: All plugins are up to date!
957 | 02.09.2019 15:45:15 | INFO | Added package a containing 1 links
958 | 02.09.2019 15:45:16 | INFO | Download starts: https://uploadgig.com/file/download/***************
959 | 02.09.2019 15:45:16 | WARNING | HOSTER UploadgigCom[48]: Plugin may be unstable
960 | 02.09.2019 15:45:16 | WARNING | Download failed:  ***************  \| 'NoneType' object has no attribute 'get_info'
961 | 02.09.2019 15:45:16 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of:  https://uploadgig.com/file/download/********************  (pid:11)
962 | 02.09.2019 15:45:16 | INFO | ADDON UnSkipOnFail: No duplicates found
963 | 02.09.2019 15:46:36 | INFO | Download starts: https://uploadgig.com/file/download/*************
964 | 02.09.2019 15:46:36 | WARNING | HOSTER UploadgigCom[48]: Plugin may be unstable
965 | 02.09.2019 15:46:36 | WARNING | Download failed:  https://uploadgig.com/file/download/***********  \| 'NoneType' object has no attribute 'get_info'
966 | 02.09.2019 15:46:36 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of:  https://uploadgig.com/file/download/***************************  (pid:11)
967 | 02.09.2019 15:46:36 | INFO | ADDON UnSkipOnFail: No duplicates found
`

**Comment by GammaC0de** [comment]
It seems like your pyload installation is broken, please refresh your pyload installation using the instructions in https://github.com/pyload/pyload/issues/3283.
