### ISSUE TITLE
UptoboxCom - Account Not valid error

### ISSUE THREAD

**Issue by Haldir31** [pyload/pyload#3425]
Hello,

I try to configure Pyload with UptoboxCom premium account but i get the same error described above. I try to disable the direct download but i still have in the log, the following error:

33 | 05.08.2019 23:26:17 | ERROR | ACCOUNT UptoboxCom: Could not login user `hal*******` \| Login handshake has failed
-- | -- | -- | --
34 | 05.08.2019 23:28:16 | ERROR | ADDON ClickNLoad: [Errno 98] Address already in use

I have the same account set in Download Station for Synology and able to download as Premium without issue.

Thanks

**Comment by GammaC0de** [comment]
So it does work with pyload on Synology?

Is this a new installation on the second machine?

**Comment by Haldir31** [comment]
I use Synology Download station with the uptobox premium module. 

On a new hosted server, pyload is already installed and i would like to use too with my premium account.

The pyload version installed is 0.4.9

**Comment by GammaC0de** [comment]
>On a new hosted server, pyload is already installed

Who have installed it and how?

**Comment by Haldir31** [comment]
I have my server at bytesized-hosting.com who provide a one-click installation for multiple tool including Pyload. I just set the password to access to the web interface but installation is fully managed by the provider.

**Comment by GammaC0de** [comment]
Do you have enough permissions to do the instructions in #3283?

**Comment by Haldir31** [comment]
Thanks, it worked perfectly
