### ISSUE TITLE
Is the UpdateManager Plugin still functioning?

### ISSUE THREAD

**Issue by Exormeter** [pyload/pyload#3429]
### Your question

Hi, I was just wondering if the UpdateManager is still working. For example, the current version for the shareOnline plugin is 0.72, but according the the URL (https://raw.githubusercontent.com/pyload/updates/master/plugins.txt)
in the UpdateManager Plugin it is 0.48.

I was using an older shareOnline plugin 0.65 because the UpdateManager never reported an update.

**Comment by GammaC0de** [comment]
Yes,
I suggest you follow the instructions in https://github.com/pyload/pyload/issues/3283 to refresh your installation.

**Comment by Exormeter** [comment]
Updated pyload to the newest version and had a second look at the plugins.txt that is retrieved by the UpdateManager. I overlook that **Accounts** for ShareOnline is 0.47 and that the **Hoster** is infact 0.72, which matches with the version in the stable branch.
