### ISSUE TITLE
ShareOnlineBiz

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#3433]
### Describe the problem

ShareonlineBiz always break download due to Oberationtoo slow Exception.
Running as free user it happend on 1GB files randomly.

### Debug log

...

4389 | 24.08.2019 10:33:42 | DEBUG | Chunk 1 failed: (28, 'Operation too slow. Less than 5 bytes/sec transferred the last 120 seconds')
-- | -- | -- | --
4390 | 24.08.2019 10:33:42 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
4391 | 24.08.2019 10:33:42 | DEBUG | pycurl exception 28: Operation too slow. Less than 5 bytes/sec transferred the last 120 seconds
4392 | 24.08.2019 10:33:42 | WARNING | Couldn't connect to host or connection reset, waiting 1 minute and retry.
4393 | 24.08.2019 10:34:43 | INFO | Download starts: 4sj-tmln-720p-s03e02.part1.rar
4394 | 24.08.2019 10:34:43 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
-- | -- | -- | --
4395 | 24.08.2019 10:34:43 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
4396 | 24.08.2019 10:34:43 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
4397 | 24.08.2019 10:34:43 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0  (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
4398 | 24.08.2019 10:34:43 | DEBUG | HOSTER ShareonlineBiz[7603]: Plugin version: 0.72
4399 | 24.08.2019 10:34:43 | DEBUG | HOSTER ShareonlineBiz[7603]: Plugin status: testing
4400 | 24.08.2019 10:34:43 | WARNING | HOSTER ShareonlineBiz[7603]: Plugin may be unstable
4401 | 24.08.2019 10:34:43 | INFO | HOSTER ShareonlineBiz[7603]: Grabbing link info...
4402 | 24.08.2019 10:34:43 | DEBUG | HOSTER ShareonlineBiz[7603]: Link info: {'status': 2, 'hash': {},  'name': '4sj-tmln-720p-s03e02.part1.rar', 'url':  u'http://www.share-online.biz/dl/CARO9PWPMWA', 'pattern': {'ID':  u'CARO9PWPMWA'}, 'md5': '49f2473ead5911cdec9d32c67005e44a', 'size':  1073741824}
4403 | 24.08.2019 10:34:43 | DEBUG | HOSTER ShareonlineBiz[7603]: Previous link info: {'status': 2,  'hash': {}, 'name': '4sj-tmln-720p-s03e02.part1.rar', 'url':  u'http://www.share-online.biz/dl/CARO9PWPMWA', 'pattern': {'ID':  u'CARO9PWPMWA'}, 'size': 1073741824, 'md5':  '49f2473ead5911cdec9d32c67005e44a'}
4404 | 24.08.2019 10:34:43 | INFO | HOSTER ShareonlineBiz[7603]: Link name: 4sj-tmln-720p-s03e02.part1.rar
4405 | 24.08.2019 10:34:43 | INFO | HOSTER ShareonlineBiz[7603]: Link size: 1.00 GiB (1073741824 bytes)
4406 | 24.08.2019 10:34:43 | INFO | HOSTER ShareonlineBiz[7603]: Link status: online
4407 | 24.08.2019 10:34:43 | INFO | HOSTER ShareonlineBiz[7603]: Processing url: http://www.share-online.biz/dl/CARO9PWPMWA
4408 | 24.08.2019 10:34:43 | INFO | HOSTER ShareonlineBiz[7603]: Looking for direct download link...
4409 | 24.08.2019 10:34:43 | DEBUG | HOSTER ShareonlineBiz[7603]: LOAD URL  http://www.share-online.biz/dl/CARO9PWPMWA \| redirect=True \|  cookies=True \| get={} \| req=None \| decode=True \| multipart=False \|  post={} \| ref=True \| just_header=True
4410 | 24.08.2019 10:34:43 | INFO | HOSTER ShareonlineBiz[7603]: Direct download link not found
4411 | 24.08.2019 10:34:43 | DEBUG | HOSTER ShareonlineBiz[7603]: LOAD URL  http://www.share-online.biz/dl/CARO9PWPMWA \| redirect=True \|  cookies=True \| get={} \| req=None \| decode=True \| multipart=False \|  post={} \| ref=False \| just_header=False
4412 | 24.08.2019 10:34:43 | INFO | HOSTER ShareonlineBiz[7603]: Processing as free download...
4413 | 24.08.2019 10:34:43 | DEBUG | HOSTER ShareonlineBiz[7603]: WAIT set to timestamp 1566635687.395425 \| Previous waitUntil: 1566635682.703433
4414 | 24.08.2019 10:34:43 | INFO | HOSTER ShareonlineBiz[7603]: Waiting 3 seconds...
4415 | 24.08.2019 10:34:47 | DEBUG | HOSTER ShareonlineBiz[7603]: LOAD URL  http://www.share-online.biz/dl/CARO9PWPMWA/free/ \| redirect=True \|  cookies=True \| get={} \| req=None \| decode=True \| multipart=False \|  post={'dl_free': '1', 'choice': 'free'} \| ref=True \| just_header=False
4416 | 24.08.2019 10:34:47 | DEBUG | CAPTCHA ShareonlineBiz[7603]: ReCaptcha \| Key: 6LdnPkIUAAAAABqC_ITR9-LTJKSdyR_Etj1Sf-Xi
4417 | 24.08.2019 10:34:47 | WARNING | CAPTCHA ShareonlineBiz[7603]: ReCaptcha \| Secure Token pattern not found
4418 | 24.08.2019 10:34:47 | DEBUG | CAPTCHA ShareonlineBiz[7603]: ReCaptcha \| Detected reCAPTCHA v2
4419 | 24.08.2019 10:34:47 | WARNING | CAPTCHA ShareonlineBiz[7603]: ReCaptcha \| Secure Token pattern not found
4420 | 24.08.2019 10:34:47 | DEBUG | HOSTER ShareonlineBiz[7603]: LOAD URL  http://www.google.com/recaptcha/api/fallback?k=6LdnPkIUAAAAABqC_ITR9-LTJKSdyR_Etj1Sf-Xi  \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \|  multipart=False \| post={} \|  ref=http://www.share-online.biz/dl/CARO9PWPMWA \| just_header=False
4421 | 24.08.2019 10:34:47 | WARNING | CAPTCHA ShareonlineBiz[7603]: ReCaptcha \| reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
4422 | 24.08.2019 10:34:47 | DEBUG | CAPTCHA ShareonlineBiz[7603]: ReCaptcha \| Challenge reCAPTCHA v2 interactive
4423 | 24.08.2019 10:34:47 | DEBUG | ADDON Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi \|  redirect=True \| cookies=True \| get={'action': 'usercaptchaguthaben',  'source': 'pyload', 'apikey': u'***', 'pyload': '1'} \|  req=None \| decode=True \| multipart=False \| post={} \| ref=True \|  just_header=False
4424 | 24.08.2019 10:34:47 | INFO | ADDON Captcha9Kw: 5283 credits left
4425 | 24.08.2019 10:34:47 | DEBUG | ADDON Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt \|  redirect=True \| cookies=True \| get={} \| req=None \| decode=True \|  multipart=False \| post={} \| ref=True \| just_header=False
4426 | 24.08.2019 10:34:47 | DEBUG | ADDON Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi \|  redirect=True \| cookies=True \| get={} \| req=None \| decode=True \|  multipart=False \| post={'securetoken': '', 'base64': 0, 'prio': 0,  'min_len': 2, 'data-sitekey':  u'6LdnPkIUAAAAABqC_ITR9-LTJKSdyR_Etj1Sf-Xi', 'numeric': 0, 'max_len':  50, 'pageurl': u'http://www.share-online.biz/', 'phrase': 0, 'mouse': 0,  'oldsource': 'ShareonlineBiz', 'apikey': u'***',  'captchapermin': 3, 'case-sensitive': 0, 'confirm': False, 'maxtimeout':  900, 'captchaperhour': 15, 'selfsolve': True, 'source': 'pyload',  'action': 'usercaptchaupload', 'pyload': 1, 'math': 0, 'interactive': 1}  \| ref=True \| just_header=False
4427 | 24.08.2019 10:34:48 | DEBUG | ADDON Captcha9Kw: NewCaptchaID ticket: 125575422
4428 | 24.08.2019 10:34:48 | DEBUG | ADDON Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi \|  redirect=True \| cookies=True \| get={'info': '1', 'apikey':  u'***', 'source': 'pyload', 'action':  'usercaptchacorrectdata', 'id': u'125575422', 'pyload': '1'} \| req=None \|  decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
-- | -- | -- | --
....
4488 | 24.08.2019 10:40:02 | DEBUG | ADDON Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi \|  redirect=True \| cookies=True \| get={'info': '1', 'apikey':  u'***', 'source': 'pyload', 'action':  'usercaptchacorrectdata', 'id': u'125575422', 'pyload': '1'} \| req=None \|  decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
-- | -- | -- | --
4489 | 24.08.2019 10:40:02 | INFO | ADDON Captcha9Kw: Captcha result for ticket 125575422:  03AOLTBLT7XCCaOziP1Q6lXSSs2mEnIGVNbBKwNfaPANv_cNoK4AMN1FbO9T0Dnmz_M74kYVw2Yoye7lrQbJINAhUVULo92wnK-HCjAM_c4vbN-TVsGsjgAAyGidCvO3zPEC-j4OwymINiyNW82oFjysHNQBFnedopZLQuj_e9MM_ryfrF60oG62VJ2oHXXpnWQT-Dqg-Fv6-hT7295o4Sdz3d_eCFpIkv-xrAmejwyaXvDdOLc9-wMIGZuHX3m1btO1MYPBucvMbi2we0fMdF1zJQK5Ls1F6THqPF_DjdkpSvoLSDCQx0J9D1aeC3brCNbFZZB98cISa_LZvb5ulS2GzbM-lgbbnOMlN76nmLyD5jPwameT3ISYFigEYODTG6tcLHNjscByGO2m445Xd1yT5IpW79fJu3jg
4490 | 24.08.2019 10:40:03 | INFO | CAPTCHA ShareonlineBiz[7603]: ReCaptcha \| Captcha result:  `03AOLTBLT7XCCaOziP1Q6lXSSs2mEnIGVNbBKwNfaPANv_cNoK4AMN1FbO9T0Dnmz_M74kYVw2Yoye7lrQbJINAhUVULo92wnK-HCjAM_c4vbN-TVsGsjgAAyGidCvO3zPEC-j4OwymINiyNW82oFjysHNQBFnedopZLQuj_e9MM_ryfrF60oG62VJ2oHXXpnWQT-Dqg-Fv6-hT7295o4Sdz3d_eCFpIkv-xrAmejwyaXvDdOLc9-wMIGZuHX3m1btO1MYPBucvMbi2we0fMdF1zJQK5Ls1F6THqPF_DjdkpSvoLSDCQx0J9D1aeC3brCNbFZZB98cISa_LZvb5ulS2GzbM-lgbbnOMlN76nmLyD5jPwameT3ISYFigEYODTG6tcLHNjscByGO2m445Xd1yT5IpW79fJu3jg`
4491 | 24.08.2019 10:40:03 | DEBUG | HOSTER ShareonlineBiz[7603]: WAIT set to timestamp 1566636034.257635 \| Previous waitUntil: 1566635687.395425
4492 | 24.08.2019 10:40:03 | DEBUG | HOSTER ShareonlineBiz[7603]: LOAD URL  http://www.share-online.biz/dl/CARO9PWPMWA/free/captcha/1566636003258 \|  redirect=True \| cookies=True \| get={} \| req=None \| decode=True \|  multipart=False \| post={'recaptcha_challenge_field':  u'03AOLTBLT7XCCaOziP1Q6lXSSs2mEnIGVNbBKwNfaPANv_cNoK4AMN1FbO9T0Dnmz_M74kYVw2Yoye7lrQbJINAhUVULo92wnK-HCjAM_c4vbN-TVsGsjgAAyGidCvO3zPEC-j4OwymINiyNW82oFjysHNQBFnedopZLQuj_e9MM_ryfrF60oG62VJ2oHXXpnWQT-Dqg-Fv6-hT7295o4Sdz3d_eCFpIkv-xrAmejwyaXvDdOLc9-wMIGZuHX3m1btO1MYPBucvMbi2we0fMdF1zJQK5Ls1F6THqPF_DjdkpSvoLSDCQx0J9D1aeC3brCNbFZZB98cISa_LZvb5ulS2GzbM-lgbbnOMlN76nmLyD5jPwameT3ISYFigEYODTG6tcLHNjscByGO2m445Xd1yT5IpW79fJu3jg',  'recaptcha_response_field':  u'03AOLTBLT7XCCaOziP1Q6lXSSs2mEnIGVNbBKwNfaPANv_cNoK4AMN1FbO9T0Dnmz_M74kYVw2Yoye7lrQbJINAhUVULo92wnK-HCjAM_c4vbN-TVsGsjgAAyGidCvO3zPEC-j4OwymINiyNW82oFjysHNQBFnedopZLQuj_e9MM_ryfrF60oG62VJ2oHXXpnWQT-Dqg-Fv6-hT7295o4Sdz3d_eCFpIkv-xrAmejwyaXvDdOLc9-wMIGZuHX3m1btO1MYPBucvMbi2we0fMdF1zJQK5Ls1F6THqPF_DjdkpSvoLSDCQx0J9D1aeC3brCNbFZZB98cISa_LZvb5ulS2GzbM-lgbbnOMlN76nmLyD5jPwameT3ISYFigEYODTG6tcLHNjscByGO2m445Xd1yT5IpW79fJu3jg',  'dl_free': '1'} \| ref=True \| just_header=False
4493 | 24.08.2019 10:40:03 | INFO | CAPTCHA ShareonlineBiz[7603]: ReCaptcha \| Correct captcha \|  03AOLTBLT7XCCaOziP1Q6lXSSs2mEnIGVNbBKwNfaPANv_cNoK4AMN1FbO9T0Dnmz_M74kYVw2Yoye7lrQbJINAhUVULo92wnK-HCjAM_c4vbN-TVsGsjgAAyGidCvO3zPEC-j4OwymINiyNW82oFjysHNQBFnedopZLQuj_e9MM_ryfrF60oG62VJ2oHXXpnWQT-Dqg-Fv6-hT7295o4Sdz3d_eCFpIkv-xrAmejwyaXvDdOLc9-wMIGZuHX3m1btO1MYPBucvMbi2we0fMdF1zJQK5Ls1F6THqPF_DjdkpSvoLSDCQx0J9D1aeC3brCNbFZZB98cISa_LZvb5ulS2GzbM-lgbbnOMlN76nmLyD5jPwameT3ISYFigEYODTG6tcLHNjscByGO2m445Xd1yT5IpW79fJu3jg
4494 | 24.08.2019 10:40:03 | DEBUG | ADDON Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi \|  redirect=True \| cookies=True \| get={'apikey': u'***',  'id': u'125575422', 'source': 'pyload', 'action':  'usercaptchacorrectback', 'api_key': u'***', 'correct':  '1', 'pyload': '1'} \| req=None \| decode=True \| multipart=False \|  post={} \| ref=True \| just_header=False
4495 | 24.08.2019 10:40:03 | DEBUG | ADDON Captcha9Kw: Request correct: OK

4496 | 24.08.2019 10:40:03 | INFO | HOSTER ShareonlineBiz[7603]: Waiting 30 seconds...
-- | -- | -- | --
4497 | 24.08.2019 10:40:35 | INFO | HOSTER ShareonlineBiz[7603]: Downloading file...
4498 | 24.08.2019 10:40:35 | DEBUG | HOSTER ShareonlineBiz[7603]: DOWNLOAD URL  http://dlw409-1.share-online.biz/fl?fr=C64458E9C0302AEAF6412B93C51722BF93217DB9F3462E8CC041569C94268BEDE5BB2C5C3B488F829D26D6EDCEA49BE3DB447F333B47C5EC94A82BEC656E8E349417E499096B0BECD3B32CCC8BF05C6394952E9F931445A1CF0308EC71CF7CE111982E05D9F58CE6946554C12026AE77&q=v4  \| fixurl=True \| resume=None \| get={} \| cookies=True \| disposition=True \|  chunks=None \| post={} \| ref=True
4499 | 24.08.2019 10:40:35 | DEBUG | Content-Disposition: 4sj-tmln-720p-s03e02.part1.rar
4500 | 24.08.2019 11:02:59 | DEBUG | ADDON ClickNLoad: Connection from 185.176.27.126:45901
4501 | 24.08.2019 11:02:59 | DEBUG | ADDON ClickNLoad: Connection from 185.176.27.126:46506
4502 | 24.08.2019 11:02:59 | DEBUG | ADDON ClickNLoad: Connection from 185.176.27.126:47806
4503 | 24.08.2019 11:36:46 | DEBUG | Chunk 1 failed: (28, 'Operation too slow. Less than 5 bytes/sec transferred the last 120 seconds')
4504 | 24.08.2019 11:36:46 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
4505 | 24.08.2019 11:36:46 | DEBUG | pycurl exception 28: Operation too slow. Less than 5 bytes/sec transferred the last 120 seconds
4506 | 24.08.2019 11:36:46 | WARNING | Couldn't connect to host or connection reset, waiting 1 minute and retry.

### Screenshots

not neccessary

**Comment by GammaC0de** [comment]
`Operation too slow. Less than 5 bytes/sec transferred the last 120 seconds` is a pycurl error, there is nothing that can be done from pyload's side..

Either you have internet issues or possibly share-online does.. 

P.S.
Your post was edited to remove your 9kw API key, 
To prevent someone else use your key, I suggest you delete this key and create a new key..
