### ISSUE TITLE
failed: newTask() takes exactly 5 arguments (4 given)

### ISSUE THREAD

**Issue by fragme2** [pyload/pyload#3434]
Hi folks,
I'm getting this error message in the pyload Webinterface Queue: failed newTask() takes exactly 5 arguments (4 given).
The error is already mentioned here: https://github.com/pyload/pyload/issues/3282
But: FileCryptCC seems to be up to date. I'm getting these Infos from pyload after starting:
26.08.2019 12:34:35 INFO      ADDON UpdateManager: pyLoad is up to date!
26.08.2019 12:34:35 INFO      ADDON UpdateManager: All plugins are up to date!
Can I manually update FileCrypt? Maybe it's another Addon, where can I get more Information? The Logfile provides no further information.
thx
fragme

**Comment by GammaC0de** [comment]
Please follow the instructions in https://github.com/pyload/pyload/issues/3283 and then retry.
