### ISSUE TITLE
Easybytes plugin "uncaught exception"

### ISSUE THREAD

**Issue by kirner** [pyload/pyload#3441]
Hello,  seems easybytes plugin cannot process this file:
http://www.easybytez.com/3ptnth6tlt46

Please check it.
Thx

### Debug log

413 | 08.09.2019 12:03:35 | WARNING | HOSTER EasybytezCom[1127]: Plugin may be unstable
-- | -- | -- | --
414 | 08.09.2019 12:03:35 | INFO | ACCOUNT EasybytezCom: Grabbing account info for user `kir*******`...
415 | 08.09.2019 12:03:35 | DEBUG | ACCOUNT EasybytezCom: LOAD URL http://www.easybytez.com/ \| redirect=True \| cookies=True \| get={'op': 'my_account'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
416 | 08.09.2019 12:03:36 | DEBUG | ACCOUNT EasybytezCom: Expire date: 23 September 2019
417 | 08.09.2019 12:03:36 | DEBUG | ACCOUNT EasybytezCom: Valid until: 1569189600.0
418 | 08.09.2019 12:03:36 | DEBUG | ACCOUNT EasybytezCom: TRAFFIC LEFT PATTERN not found
419 | 08.09.2019 12:03:36 | DEBUG | ACCOUNT EasybytezCom: LEECH TRAFFIC PATTERN not found
420 | 08.09.2019 12:03:36 | DEBUG | ACCOUNT EasybytezCom: Account info for user `kir*******`: {'login': {'timestamp': 1567936992.726799, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1569189600.0, 'login': 'kir*******', 'type': 'EasybytezCom', 'options': {'limitdl': ['0']}}}
421 | 08.09.2019 12:03:36 | INFO | HOSTER EasybytezCom[1127]: Grabbing link info...
422 | 08.09.2019 12:03:36 | DEBUG | HOSTER EasybytezCom[1127]: Link info: {'status': 2, 'hash': {}, 'name': '4.1.R151n6.12.Fu7ur0.e.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar', 'url': u'http://www.easybytez.com/3ptnth6tlt46', 'pattern': {'S': u'255.0', 'U': u'MB', 'N': u'4.1.R151n6.12.Fu7ur0.\xe8.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar'}, 'size': 267386880}
423 | 08.09.2019 12:03:36 | DEBUG | HOSTER EasybytezCom[1127]: Previous link info: {}
424 | 08.09.2019 12:03:36 | INFO | HOSTER EasybytezCom[1127]: Link name: 4.1.R151n6.12.Fu7ur0.e.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar
425 | 08.09.2019 12:03:36 | INFO | HOSTER EasybytezCom[1127]: Link size: 255.00 MiB (267386880 bytes)
426 | 08.09.2019 12:03:36 | INFO | HOSTER EasybytezCom[1127]: Link status: online
427 | 08.09.2019 12:03:36 | INFO | HOSTER EasybytezCom[1127]: Processing url: http://www.easybytez.com/3ptnth6tlt46
428 | 08.09.2019 12:03:36 | INFO | HOSTER EasybytezCom[1127]: Looking for direct download link...
429 | 08.09.2019 12:03:36 | DEBUG | HOSTER EasybytezCom[1127]: LOAD URL http://www.easybytez.com/3ptnth6tlt46 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
430 | 08.09.2019 12:03:38 | DEBUG | HOSTER EasybytezCom[1127]: Redirect #1 to: http://str25.ezbytez.com/files/8/kpmp5clipleoxg/4.1.R151n6.12.Fu7ur0.e.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar
431 | 08.09.2019 12:03:38 | DEBUG | HOSTER EasybytezCom[1127]: LOAD URL http://str25.ezbytez.com/files/8/kpmp5clipleoxg/4.1.R151n6.12.Fu7ur0.e.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
432 | 08.09.2019 12:03:38 | INFO | HOSTER EasybytezCom[1127]: Direct download link not found
433 | 08.09.2019 12:03:38 | DEBUG | HOSTER EasybytezCom[1127]: LOAD URL http://www.easybytez.com/3ptnth6tlt46 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
434 | 08.09.2019 12:03:39 | ERROR | <<< UNCAUGHT EXCEPTION >>>
435 | ? | ? | Traceback (most recent call last):
436 | ? | ? | File "/opt/pyload/module/network/HTTPRequest.py", line 306, in write
437 | ? | ? | raise Exception("Loaded Url exceeded limit")
438 | ? | ? | Exception: Loaded Url exceeded limit
439 | 08.09.2019 12:03:39 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
440 | 08.09.2019 12:03:39 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
441 | 08.09.2019 12:03:39 | DEBUG | pycurl exception 23: Failed writing body (0 != 16384)
442 | 08.09.2019 12:03:39 | ERROR | pycurl error 23: Failed writing body (0 != 16384)
443 | 08.09.2019 12:03:39 | INFO | Debug Report written to debug_EasybytezCom_08-09-2019_12-03-39.zip
444 | 08.09.2019 12:03:39 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
445 | 08.09.2019 12:03:39 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: 4.1.R151n6.12.Fu7ur0.e.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar (pid:50)
446 | 08.09.2019 12:03:39 | INFO | ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
http://www.easybytez.com/3ptnth6tlt46 is down..

**Comment by kirner** [comment]
Thx ,
The file is down now, but i have a copy of it, so you can check the bug
http://www.easybytez.com/ipp1ek9edhud

**Comment by GammaC0de** [comment]
http://www.easybytez.com/ipp1ek9edhud works fine for me, 
do have  the same issue with it?

**Comment by kirner** [comment]
yes same problem, uncaught exception, raise Exception("Loaded Url exceeded limit")
but if you tell me you have no problem, i think this could be a library problem, pyload is running on  pi - Raspbian GNU/Linux 8.0 (jessie)
could be python release too: Python 2.7.9
ok thx in advance.

###DEBUG##########################
17 | 10.09.2019 07:13:45 | INFO | ACCOUNT EasybytezCom: No errors found
-- | -- | -- | --
18 | 10.09.2019 07:13:45 | INFO | ACCOUNT EasybytezCom: Grabbing account info for user `kir*******`...
19 | 10.09.2019 07:13:45 | DEBUG | ACCOUNT EasybytezCom: LOAD URL http://www.easybytez.com/ \| redirect=True \| cookies=True \| get={'op': 'my_account'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
20 | 10.09.2019 07:13:45 | DEBUG | ACCOUNT EasybytezCom: Expire date: 23 September 2019
21 | 10.09.2019 07:13:45 | DEBUG | ACCOUNT EasybytezCom: Valid until: 1569189600.0
22 | 10.09.2019 07:13:45 | DEBUG | ACCOUNT EasybytezCom: TRAFFIC LEFT PATTERN not found
23 | 10.09.2019 07:13:45 | DEBUG | ACCOUNT EasybytezCom: LEECH TRAFFIC PATTERN not found
24 | 10.09.2019 07:13:45 | DEBUG | ACCOUNT EasybytezCom: Account info for user `kir*******`: {'login': {'timestamp': 1568092424.470757, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'leechtraffic': None, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1569189600.0, 'login': 'kir*******', 'type': 'EasybytezCom', 'options': {'limitdl': ['0']}}}
25 | 10.09.2019 07:13:45 | INFO | HOSTER EasybytezCom[1130]: Grabbing link info...
26 | 10.09.2019 07:13:45 | DEBUG | HOSTER EasybytezCom[1130]: Link info: {'status': 2, 'hash': {}, 'name': '4.1.R151n6.12.Fu7ur0.e.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar', 'url': u'http://www.easybytez.com/ipp1ek9edhud', 'pattern': {'S': u'255.0', 'U': u'MB', 'N': u'4.1.R151n6.12.Fu7ur0.\xe8.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar'}, 'size': 267386880}
27 | 10.09.2019 07:13:45 | DEBUG | HOSTER EasybytezCom[1130]: Previous link info: {}
28 | 10.09.2019 07:13:45 | INFO | HOSTER EasybytezCom[1130]: Link name: 4.1.R151n6.12.Fu7ur0.e.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar
29 | 10.09.2019 07:13:45 | INFO | HOSTER EasybytezCom[1130]: Link size: 255.00 MiB (267386880 bytes)
30 | 10.09.2019 07:13:45 | INFO | HOSTER EasybytezCom[1130]: Link status: online
31 | 10.09.2019 07:13:45 | INFO | HOSTER EasybytezCom[1130]: Processing url: http://www.easybytez.com/ipp1ek9edhud
32 | 10.09.2019 07:13:45 | INFO | HOSTER EasybytezCom[1130]: Looking for direct download link...
33 | 10.09.2019 07:13:45 | DEBUG | HOSTER EasybytezCom[1130]: LOAD URL http://www.easybytez.com/ipp1ek9edhud \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
34 | 10.09.2019 07:13:45 | DEBUG | HOSTER EasybytezCom[1130]: Redirect #1 to: http://wrk134.easybytez.com/files/0/dltym00cvogb6b/4.1.R151n6.12.Fu7ur0.e.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar
35 | 10.09.2019 07:13:45 | DEBUG | HOSTER EasybytezCom[1130]: LOAD URL http://wrk134.easybytez.com/files/0/dltym00cvogb6b/4.1.R151n6.12.Fu7ur0.e.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
36 | 10.09.2019 07:13:46 | INFO | HOSTER EasybytezCom[1130]: Direct download link not found
37 | 10.09.2019 07:13:46 | DEBUG | HOSTER EasybytezCom[1130]: LOAD URL http://www.easybytez.com/ipp1ek9edhud \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
38 | 10.09.2019 07:13:46 | ERROR | <<< UNCAUGHT EXCEPTION >>>
39 | ? | ? | Traceback (most recent call last):
40 | ? | ? | File "/opt/pyload/module/network/HTTPRequest.py", line 306, in write
41 | ? | ? | raise Exception("Loaded Url exceeded limit")
42 | ? | ? | Exception: Loaded Url exceeded limit
43 | 10.09.2019 07:13:46 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
44 | 10.09.2019 07:13:46 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
45 | 10.09.2019 07:13:46 | DEBUG | pycurl exception 23: Failed writing body (0 != 16384)
46 | 10.09.2019 07:13:46 | ERROR | pycurl error 23: Failed writing body (0 != 16384)
47 | 10.09.2019 07:13:46 | INFO | Debug Report written to debug_EasybytezCom_10-09-2019_07-13-46.zip
48 | 10.09.2019 07:13:46 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
49 | 10.09.2019 07:13:46 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: 4.1.R151n6.12.Fu7ur0.e.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar (pid:53)
50 | 10.09.2019 07:13:46 | INFO | ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
Go to `http://<PYLOAD_IP>/info` and write down the value of `Config Folder`.
Go to `Config Folder`, there should be a `response.dump` file there, please post this file here.

**Comment by kirner** [comment]
here it is
[response.zip](https://github.com/pyload/pyload/files/3599226/response.zip)

**Comment by GammaC0de** [comment]
Can you disable direct downloads on easybytez.com's account settings and then recheck?

**Comment by kirner** [comment]
Seems i have not this option in easybytezcom plugin settings.

**Comment by kirner** [comment]
done!

**Comment by GammaC0de** [comment]
Disabled direct downloads in the account settings and now the plugin works:
![Capture](https://user-images.githubusercontent.com/11036551/64866215-ad4a6e80-d643-11e9-8e1d-edfd36652012.PNG)

**Comment by kirner** [comment]
So, sorry for later response, Thx for explaining me ho to disable direct download, anyway issue has not solved. Now the file has been downloaded, but just 1k size.
I attach debug, but no sense, no errors inside.

Excuse me, have you considered this issue is only with this file? usually with others files i have no problems. 

#DEBUG#############


79 | 15.09.2019 07:53:07 | INFO | HOSTER EasybytezCom[1335]: Downloading file...
-- | -- | -- | --
80 | 15.09.2019 07:53:07 | DEBUG | HOSTER EasybytezCom[1335]: DOWNLOAD URL http://str25.ezbytez.com/files/5/5u21eln8kd8e7c/4.1.R151n6.12.Fu7ur0.e.4d3550.2018.FU22.HD.VU.10809.D75-HD.M4+4C3.174.3N6.5U8.2F1.part01.rar \| fixurl=True \| resume=None \| get={} \| cookies=True \| disposition=True \| chunks=None \| post={} \| ref=True
81 | 15.09.2019 07:53:08 | INFO | HOSTER EasybytezCom[1335]: File saved
82 | 15.09.2019 07:53:08 | INFO | HOSTER EasybytezCom[1335]: Checking download...
83 | 15.09.2019 07:53:08 | INFO | HOSTER EasybytezCom[1335]: File is OK
84 | 15.09.2019 07:53:08 | INFO | HOSTER EasybytezCom[1335]: Checking file (with built-in rules)...
85 | 15.09.2019 07:53:08 | INFO | HOSTER EasybytezCom[1335]: Checking file (with custom rules)...
86 | 15.09.2019 07:53:08 | INFO | HOSTER EasybytezCom[1335]: Checking for link errors...
87 | 15.09.2019 07:53:08 | INFO | HOSTER EasybytezCom[1335]: No errors found
88 | 15.09.2019 07:53:08 | INFO | HOSTER EasybytezCom[1335]: No errors found

**Comment by GammaC0de** [comment]
> Excuse me, have you considered this issue is only with this file? usually with others files i have no problems.

Indeed this happens only with some files.
I know why it happens but the fix is not so trivial,
I will update if any progress.

**Comment by GammaC0de** [comment]
OK, plugins were updated, can you test the above URL again?

**Comment by kirner** [comment]
Thx m8, finally now is fixed.
