### ISSUE TITLE
PyLoad's frontend asset links fail to conform to set Path Prefix

### ISSUE THREAD

**Issue by rare-energy** [pyload/pyload#3445]
### Describe the problem
I put PyLoad behind Traefik, with a `PathPrefix` of `/example/pyload`. I set the Path Prefix in PyLoad's backend to `/example/pyload`.

Visiting `/example/pyload` in a browser successfully redirects to `/example/pyload/login`, where the login process can be completed, again successfully.

However, frontend layout assets fail to fetch and render. A cursory glance of the network logs show requests that *do not* conform to the Path Prefix set on PyLoad's backend.

### Debug log
Here's Firefox's console output when visiting the login page:
```
Loading failed for the <script> with source “https://host/media/js/modern/jquery-3.2.1.min.js”. login:295:1
The resource from “https://host/media/js/modern/jquery-ui-1.12.1.min.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
login
Loading failed for the <script> with source “https://host/media/js/modern/jquery-ui-1.12.1.min.js”. login:296:1
The resource from “https://host/media/js/modern/jquery.peekabar.min.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
login
Loading failed for the <script> with source “https://host/media/js/modern/jquery.peekabar.min.js”. login:297:1
The resource from “https://host/media/js/modern/bootstrap.min.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
login
Loading failed for the <script> with source “https://host/media/js/modern/bootstrap.min.js”. login:298:1
The resource from “https://host/media/js/modern/base.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
login
Loading failed for the <script> with source “https://host/media/js/modern/base.js”.
```

If we look at the last unloaded resource, visiting the following URL successfully loads it: `https://host/example/pyload/media/js/modern/base.js`.

PyLoad's frontend resource URIs should conform to the Path Prefix set by the user.

**Comment by GammaC0de** [comment]
>`The resource from “https://host/media/js/modern/jquery-ui-1.12.1.min.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff)`

Please post Firefox's network logs,
Is seems that Traefik messes/blocks MIME types
