### ISSUE TITLE
Help - how to restrict / throttle pyload 

### ISSUE THREAD

**Issue by koenigmidas** [pyload/pyload#3447]
hi folks,

i am using pyload on a raspberry and everything is working fine.

but when leeching files and using ExtractArchive my raspi is only hard reachable. which mean i cant use the raspi in parallel for other services.

I recognized several options to throttle the pyload service.

first i can set a kind of prio in the extract script via webinterface.
Currently there is 0 = process prio.
What would you suggest? which number should i enter?

The next point is I want to limit the download speed to 100 mbit. (i am on a 400mbit connection)
So which value should i enter on:  Max Download Speed in kb/s . ?

Are there any other options to tell pyload to use (for e.g.) only 30% of the raspberry power?

Thanks so far for your help
bye

EDIT: currently i got a Load of 10.* when leeching with pyload (not extracting only downloading)...

**Comment by Gurkengewuerz** [comment]
Hey @koenigmidas 

i cant say much to the process topic but what is you idle load?

To the download throtteling:
If you want to throttle the max download Speed you should theoretically enter "100000" kb/s. 
Keep in mind you are using a raspberry pi. On Pi 4 it uses a shared usb controller that can maybe use more than 100 MBit/s. Older versions cant use more than 100 MBit/s on the Ethernet Controller due to hardware restrictions.


Greetings from Germany!

**Comment by koenigmidas** [comment]
> Hey @koenigmidas
> 
> i cant say much to the process topic but what is you idle load?
> 
> To the download throtteling:
> If you want to throttle the max download Speed you should theoretically enter "100000" kb/s.
> Keep in mind you are using a raspberry pi. On Pi 4 it uses a shared usb controller that can maybe use more than 100 MBit/s. Older versions cant use more than 100 MBit/s on the Ethernet Controller due to hardware restrictions.
> 
> Greetings from Germany!

Hey Niklas.


avarage load is 0.25 - Besides pyload I'am only using pihole on this raspberry4 (1gig)

And once downloading the load increases to over 10 and my dns server is not really reachable "well" 
therefore i want to lower the priority of pyload, so that the pihole is working permanently.

Thanks for the hint regarding the speed. i have throttled it to 100000.

So how to proceed.

Greetings from Germany to Germany ;)

**Comment by Gurkengewuerz** [comment]
I'm sorry, I am not really into the core code of pyload. I can't say much about it.
So maybe wait for the devs @vuolter or @GammaC0de and maybe attach a bit more debug information like a screenshot of htop or something :)

**Comment by koenigmidas** [comment]
currently I am extracting a larger directory with pyload @ extractarchive with a Load of approx. 5.0
Which is okay for my.

AFAIK i get loads of over 10 only when downloading files.

**Comment by GammaC0de** [comment]
Maybe try to play with "Process priority" setting in ExtractArchive's settings.

**Comment by koenigmidas** [comment]
> Maybe try to play with "Process priority" setting in ExtractArchive's settings.

Hey Gamma,

thanks for your reply.
which value @ ExtractArchive (Process priority) would you suggest?

and what about my point...
heavy load during downloading...

**Comment by GammaC0de** [comment]
pyLoad uses the linux [`renice` ](http://man7.org/linux/man-pages/man1/renice.1.html) command to set the priority.
https://www.computerhope.com/unix/renice.htm

**Comment by koenigmidas** [comment]
Ok, will check it.

and what value are you gonna suggest for the extractarchive prio. currently I got a Load of 5.0 when "unrar" is active.

**Comment by GammaC0de** [comment]
It just a matter of trial and error..

**Comment by koenigmidas** [comment]
ok, i will use 20 for extractarchive and general - priority. I adjusted the value via webinterface. saved it and now doing a raspi reboot and will test it.

**Comment by koenigmidas** [comment]
So now testing.

currently downloading.
Load is over 10!

CPU and Mem of pyload are under 10% (checked with htop)
no other services are over the perentage of pyload
screenshot attached. any help?
btw speed limit wont work, currently downloading with over 20mb/s

[https://abload.de/img/loadvajbm.jpeg](url)

**Comment by GammaC0de** [comment]
What is wrong with 8.4% CPU usage?

**Comment by koenigmidas** [comment]
The Load of over 10, 10sec After this Screenshot. 

With That Load, pihole is not working smoothly. 

So cpu and mem seems Not Bad, but what is causing this load which let the raspI laggy as fuck.

**Comment by GammaC0de** [comment]
How exactly have you installed pyload?

**Comment by koenigmidas** [comment]
I took your tut

**Comment by GammaC0de** [comment]
Which one?
Have you looked in https://github.com/pyload/pyload/issues/3283?

**Comment by koenigmidas** [comment]
I took this one:
https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi)



Let me update it like #3283 and i will See its better. Will reply tomorrow. 

Honestly, do really think this will help?

How Can i check / be sure that the Update was succeasfull?

**Comment by GammaC0de** [comment]
>Honestly, do really think this will help?

I'm not sure but it worth trying..

Also there is a `CPU Priority` settings in pyLoad's general setting that adjust the priority of pyLoad's process.

**Comment by koenigmidas** [comment]
> > Honestly, do really think this will help?
> 
> I'm not sure but it worth trying..
> 
> Also there is a `CPU Priority` settings in pyLoad's general setting that adjust the priority of pyLoad's process.


Ok, will try the update later on this day and report asap.

I have already adjustet the priority to 20 via webinterface 
@ extractArchive & in the pyload general settings.

without any success. See my htop LOAD above.

Will keep on reporting this evening.

**Comment by koenigmidas** [comment]
Hey @GammaC0de , did the update like mentioned in #3283 

Load increases again like befor and the download speed limit set to: 100000 kb/s is not working.
Currently leeching für over 25mib/s 

any help?

**Comment by GammaC0de** [comment]
What happens if you give pyload a negative nicness value?

**Comment by GammaC0de** [comment]
No response, closing.
