### ISSUE TITLE
Parse error: No file downloaded | Plugin may be out of date (Uptobox)

### ISSUE THREAD

**Issue by lbr38** [pyload/pyload#3448]
Hi,

I've got the following error on every uptobox link : 

`échoué Parse error: No file downloaded | Plugin may be out of date UptoboxCom `

`01.10.2019 16:22:10	WARNING	HOSTER UptoboxCom[54]: Free download failed | Parse error: No file downloaded | Plugin may be out of date`

I always have to restart the download to make it work then it fails again on the next uptobox link in the queue. Then I restart, it downloads, then it fails again on the next link, etc...

I've got the last stable version of pyload and a free uptobox account.

Thank you for your help

**Comment by GammaC0de** [comment]
No response, closing.
