### ISSUE TITLE
Captchas - Chrome Mobile

### ISSUE THREAD

**Issue by dontobi** [pyload/pyload#3454]
I would like to use pyload mainly via smartphone. however, no captchas are displayed to me. is there already a workaround for this?

**Comment by GammaC0de** [comment]
Your only option is to create an account on [9kw.eu](https://www.9kw.eu/) and then enable pyload's 9kw plugin to solve captchas.

You will also need to earn captcha credits on 9kw.eu.
You do that either with [9kw client](https://www.9kw.eu/software_9kwclient.html) on a PC or with [CaptchaToGo](https://play.google.com/store/apps/details?id=captchatogov2.de.pixelvalley.captchatogov2) app on android.
