### ISSUE TITLE
m3u8 playlist support

### ISSUE THREAD

**Issue by jjit** [pyload/pyload#3456]
m3u8 playlist like this :
https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
right now I'm useing ffmpeg
like this : ffmpeg -i "m3u8 url" -c copy "file name"
but if it's a big file and I'm runing ffmpeg in background on my server
it's not very easy to check download progress
so I hope pyLoad can add m3u8 download support

**Comment by GammaC0de** [comment]
Sorry, this is out of the scope of pyload, closing.
