### ISSUE TITLE
[PremiumTo] File name?

### ISSUE THREAD

**Issue by keqas** [pyload/pyload#3457]
Hi all,
when downloading files from uploaded.net the downloaded files are not named correctly.
That means when downloading something like uploaded.net/file/abcdefg1 the name of the downloaded file is just abcdefg1. 
Any suggestions?

Thanks for your support!

**Comment by GammaC0de** [comment]
For me it works fine,
Is this a new pyload installation?
Can you provide sample URL?

**Comment by keqas** [comment]
Yes, it's a new pyload installation (Docker, Synology DSM 6.2).

When adding this link to pyload the downloaded file is named sa4lggv1: http://uploaded.net/file/sa4lggv1/

By manually adding the file name to the link the downloaded file is named accordingly and auto extraction works fine.
http://uploaded.net/file/sa4lggv1/Kodi%20v18%204%20Leia.rar

**Comment by GammaC0de** [comment]
Again, this URL works fine form also,

From where did you get the docker image?
![Untitled](https://user-images.githubusercontent.com/11036551/67626227-26e39800-f851-11e9-9c0b-999d81d17616.png)

**Comment by keqas** [comment]
https://hub.docker.com/r/writl/pyload/

But I reused the config files of a previous pyload installation.

**Comment by GammaC0de** [comment]
I suggest you refresh your pyload plugins uring the instructions in https://github.com/pyload/pyload/issues/3283, maybe it would help

**Comment by keqas** [comment]
I should have mentioned that I use a Premium.to account. 
When activating the PremiumTo plugin the Uploaded.to link is downloading in premium mode, though,  the filename is "wrong".
When deactivating the PremiumTo plugin the Uploaded.to link is downloading in free mode and the filename ist correct.

**Comment by GammaC0de** [comment]
Ok then,
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by keqas** [comment]
I checked again:
activating/deactivating the PremiumTo plugin doesn't make any difference. 
Just add/remove the PremiumTo user account to reproduce the described behavior.
I will send you the account information.

**Comment by GammaC0de** [comment]
There is a bug that pyload does not properly parse the `content-disposition` header.

The fix is not trivial, will keep you updated on any progress.

**Comment by GammaC0de** [comment]
@keqas See https://github.com/pyload/pyload/issues/3487
