### ISSUE TITLE
Mediafire only download one link at time

### ISSUE THREAD

**Issue by Ansem93** [pyload/pyload#3462]
#2600 # Describe the problem
I added a list of 22 links to mediafire. After that I used the filter urls to be sure they were correctly written.
After that, Pyload seems to only be able to find one link at time, if I try to restart the package it will find a new link and download it.

### Debug log
9.10.2019 23:32:20 INFO      Download starts: .....
29.10.2019 23:32:20 WARNING   HOSTER MediafireCom[106]: Plugin may be unstable
29.10.2019 23:32:20 INFO      HOSTER MediafireCom[106]: Grabbing link info...
29.10.2019 23:32:20 INFO      HOSTER MediafireCom[106]: Link name: file
29.10.2019 23:32:20 INFO      HOSTER MediafireCom[106]: Link size: 49.19 MiB (51582649 bytes)
29.10.2019 23:32:20 INFO      HOSTER MediafireCom[106]: Link status: online
29.10.2019 23:32:20 INFO      HOSTER MediafireCom[106]: Processing url: http://www.mediafire.com/file/...../....../file
29.10.2019 23:32:20 INFO      HOSTER MediafireCom[106]: Looking for direct download link...
29.10.2019 23:32:21 INFO      HOSTER MediafireCom[106]: Direct download link not found
29.10.2019 23:32:21 INFO      HOSTER MediafireCom[106]: Checking for link errors...
29.10.2019 23:32:21 INFO      HOSTER MediafireCom[106]: No errors found
29.10.2019 23:32:21 INFO      HOSTER MediafireCom[106]: Processing as free download...
29.10.2019 23:32:21 WARNING   CAPTCHA MediafireCom[106]: ReCaptcha | Key pattern not found
29.10.2019 23:32:21 INFO      HOSTER MediafireCom[106]: Downloading file...
29.10.2019 23:32:22 INFO      Download starts: file
29.10.2019 23:32:22 WARNING   HOSTER MediafireCom[107]: Plugin may be unstable
29.10.2019 23:32:22 INFO      HOSTER MediafireCom[107]: Grabbing link info...
29.10.2019 23:32:22 INFO      HOSTER MediafireCom[107]: Link name: file
29.10.2019 23:32:22 INFO      HOSTER MediafireCom[107]: Link size: N/D
29.10.2019 23:32:22 INFO      HOSTER MediafireCom[107]: Link status: online
29.10.2019 23:32:22 INFO      Download skipped: file due to MediafireCom
29.10.2019 23:32:24 INFO      Download starts: file
29.10.2019 23:32:24 WARNING   HOSTER MediafireCom[108]: Plugin may be unstable
29.10.2019 23:32:24 INFO      HOSTER MediafireCom[108]: Grabbing link info...
29.10.2019 23:32:24 INFO      HOSTER MediafireCom[108]: Link name: file
29.10.2019 23:32:24 INFO      HOSTER MediafireCom[108]: Link size: N/D
29.10.2019 23:32:24 INFO      HOSTER MediafireCom[108]: Link status: online
29.10.2019 23:32:24 INFO      Download skipped: file due to MediafireCom
29.10.2019 23:32:26 INFO      Download starts: file
29.10.2019 23:32:26 WARNING   HOSTER MediafireCom[109]: Plugin may be unstable
29.10.2019 23:32:26 INFO      HOSTER MediafireCom[109]: Grabbing link info...
29.10.2019 23:32:26 INFO      HOSTER MediafireCom[109]: Link name: file
29.10.2019 23:32:26 INFO      HOSTER MediafireCom[109]: Link size: N/D
29.10.2019 23:32:26 INFO      HOSTER MediafireCom[109]: Link status: online
29.10.2019 23:32:26 INFO      Download skipped: file due to MediafireCom
29.10.2019 23:32:28 INFO      Download starts: file
29.10.2019 23:32:28 WARNING   HOSTER MediafireCom[110]: Plugin may be unstable
29.10.2019 23:32:28 INFO      HOSTER MediafireCom[110]: Grabbing link info...
29.10.2019 23:32:28 INFO      HOSTER MediafireCom[110]: Link name: file
29.10.2019 23:32:28 INFO      HOSTER MediafireCom[110]: Link size: N/D
29.10.2019 23:32:28 INFO      HOSTER MediafireCom[110]: Link status: online
29.10.2019 23:32:28 INFO      Download skipped: file due to MediafireCom
29.10.2019 23:32:30 INFO      Download starts: file
29.10.2019 23:32:30 WARNING   HOSTER MediafireCom[111]: Plugin may be unstable
29.10.2019 23:32:30 INFO      HOSTER MediafireCom[111]: Grabbing link info...
29.10.2019 23:32:30 INFO      HOSTER MediafireCom[111]: Link name: file
29.10.2019 23:32:30 INFO      HOSTER MediafireCom[111]: Link size: N/D
29.10.2019 23:32:30 INFO      HOSTER MediafireCom[111]: Link status: online
29.10.2019 23:32:30 INFO      Download skipped: file due to MediafireCom
29.10.2019 23:32:32 INFO      Download starts: [Keitaro84] Tenjou Tenge Vol. 07.rar
29.10.2019 23:32:32 WARNING   HOSTER MediafireCom[112]: Plugin may be unstable
29.10.2019 23:32:32 INFO      HOSTER MediafireCom[112]: Grabbing link info...
29.10.2019 23:32:33 INFO      HOSTER MediafireCom[112]: Link name: file
29.10.2019 23:32:33 INFO      HOSTER MediafireCom[112]: Link size: 96.78 MiB (101479131 bytes)
29.10.2019 23:32:33 INFO      HOSTER MediafireCom[112]: Link status: online
29.10.2019 23:32:33 INFO      Download skipped: file due to MediafireCom
29.10.2019 23:32:34 INFO      Download starts: file
29.10.2019 23:32:34 WARNING   HOSTER MediafireCom[113]: Plugin may be unstable
29.10.2019 23:32:34 INFO      HOSTER MediafireCom[113]: Grabbing link info...
29.10.2019 23:32:34 INFO      HOSTER MediafireCom[113]: Link name: file
29.10.2019 23:32:34 INFO      HOSTER MediafireCom[113]: Link size: N/D
29.10.2019 23:32:34 INFO      HOSTER MediafireCom[113]: Link status: online
29.10.2019 23:32:34 INFO      Download skipped: file due to MediafireCom
29.10.2019 23:32:36 INFO      Download starts: file
29.10.2019 23:32:36 WARNING   HOSTER MediafireCom[114]: Plugin may be unstable
29.10.2019 23:32:36 INFO      HOSTER MediafireCom[114]: Grabbing link info...
29.10.2019 23:32:36 INFO      HOSTER MediafireCom[114]: Link name: file
29.10.2019 23:32:36 INFO      HOSTER MediafireCom[114]: Link size: N/D
29.10.2019 23:32:36 INFO      HOSTER MediafireCom[114]: Link status: online
29.10.2019 23:32:36 INFO      Download skipped: file due to MediafireCom
29.10.2019 23:32:38 INFO      Download starts: file
29.10.2019 23:32:38 WARNING   HOSTER MediafireCom[115]: Plugin may be unstable
29.10.2019 23:32:38 INFO      HOSTER MediafireCom[115]: Grabbing link info...
29.10.2019 23:32:38 INFO      HOSTER MediafireCom[115]: Link name: file
29.10.2019 23:32:38 INFO      HOSTER MediafireCom[115]: Link size: N/D
29.10.2019 23:32:38 INFO      HOSTER MediafireCom[115]: Link status: online
29.10.2019 23:32:38 INFO      Download skipped: file due to MediafireCom
29.10.2019 23:32:40 INFO      Download starts: file
29.10.2019 23:32:40 WARNING   HOSTER MediafireCom[116]: Plugin may be unstable
29.10.2019 23:32:40 INFO      HOSTER MediafireCom[116]: Grabbing link info...

**Comment by Ansem93** [comment]
p.s. i deleted the link, but if you need some example I can send it to you :)

**Comment by GammaC0de** [comment]
Your log says "Download skipped" which means that the download file already exists on your download folder.

I have successfully downloaded a package with 5 URLs in it...
