### ISSUE TITLE
Encoding issue in RealdebridTorrent

### ISSUE THREAD

**Issue by hrldd** [pyload/pyload#3466]
### Describe the problem

I am trying to use the RealdebridTorrent plugin.
Downloading a torrent fails when the torrent file contains non-ASCII characters.
In my case, I upload a `torrent.torrent` file which contains the '°' character
I can send you the `torrent.torrent` file privately for debugging purposes.

### Debug log

```
04.11.2019 14:10:37 ERROR     Decrypting failed: tmp_torrent.torrent | 'ascii' codec can't decode byte 0xc2 in position 6: ordinal not in range(128)
```

**Comment by GammaC0de** [comment]
pyload has a known for long time bug when filename contains non-ASCII characters.
Please send the torrent to nitzo2001 at yahoo dot com.
Chanses to fix are low.

**Comment by haroldmrt** [comment]
I sent it, thanks for the quick answer

**Comment by GammaC0de** [comment]
@haroldmrt See #3487
