### ISSUE TITLE
TurbobitNet don't start - 'could not convert string to float'

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#3468]
### Describe the problem

Running as free user download won't start due too 'could not convert string to float'
[Filelink](https://turbobit.net/jq6q5kbiaz12.html)
But other Links have no problems (e.g. [SampleLink](https://turbobit.net/zndkd7pomc4b.html))

### Debug log

```

630 | 04.11.2019 19:39:16 | INFO | CAPTCHA TurbobitNet[233]: ReCaptcha \| Captcha result:  `03AOLTBLQa8ECSQxWhrG1iFSU3_Vd0kJowWeMErZuP-O3JwGfCk3rx4QH9VKvwQzccPnL3WKMQzZHnD8x4EkNGQiseS8HPC7ovyEgiQenW-PPJVsPoyS6ANK9fEg3GAjnBXfBVwZ3JhNCmRYEOS-aD4CoDKMJg-379AI9Mm-EN4EXCE8TSzK33P5yXLzeRoV92pko0pUr06eJwaEWnY_aG37gqAVc54F8fKFyIGEW0fW4grT7NvnBAXmlnLnHBZmMj2Zh0vdnXUliw1K27L0a2F_CMQ_wyWNN2jyWJX3PLGLdVuUA3R6I6cMciJhyQ9oB5ViPcV8dRGTNou3MVrCK640C8LJ0eZ9FwA5BOPINvLORQv1CMl4DGQb3fJqWwNQtdIqobn8_1qel4EKW0nSmjX35T6mhA3bPYDV8fTip7FFoofeUriWIC8mNuPp4CaLtyMOf_NJ88xQuAjgW2j9UOwk8j4cZ-dZI6UaVgtPwaJOWhVLYJy9kSlUXUu2jejUtCZLjlRa-fZABL`
-- | -- | -- | --
631 | 04.11.2019 19:39:16 | DEBUG | HOSTER TurbobitNet[233]: LOAD URL  https://turbobit.net/download/free/jq6q5kbiaz12 \| redirect=True \|  cookies=True \| get={} \| req=None \| decode=True \| multipart=False \|  post={u'captcha_type': u'recaptcha2', 'g-recaptcha-response':  '03AOLTBLQa8ECSQxWhrG1iFSU3_Vd0kJowWeMErZuP-O3JwGfCk3rx4QH9VKvwQzccPnL3WKMQzZHnD8x4EkNGQiseS8HPC7ovyEgiQenW-PPJVsPoyS6ANK9fEg3GAjnBXfBVwZ3JhNCmRYEOS-aD4CoDKMJg-379AI9Mm-EN4EXCE8TSzK33P5yXLzeRoV92pko0pUr06eJwaEWnY_aG37gqAVc54F8fKFyIGEW0fW4grT7NvnBAXmlnLnHBZmMj2Zh0vdnXUliw1K27L0a2F_CMQ_wyWNN2jyWJX3PLGLdVuUA3R6I6cMciJhyQ9oB5ViPcV8dRGTNou3MVrCK640C8LJ0eZ9FwA5BOPINvLORQv1CMl4DGQb3fJqWwNQtdIqobn8_1qel4EKW0nSmjX35T6mhA3bPYDV8fTip7FFoofeUriWIC8mNuPp4CaLtyMOf_NJ88xQuAjgW2j9UOwk8j4cZ-dZI6UaVgtPwaJOWhVLYJy9kSlUXUu2jejUtCZLjlRa-fZABL',  u'captcha_subtype': ''} \| ref=True \| just_header=False
632 | 04.11.2019 19:39:17 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
633 | 04.11.2019 19:39:17 | WARNING | Download failed: SPT72O.S14E20.part2.rar \| could not convert string to float: out of memory
634 | 04.11.2019 19:39:17 | INFO | Debug Report written to debug_TurbobitNet_04-11-2019_19-39-17.zip
635 | 04.11.2019 19:39:17 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
636 | 04.11.2019 19:39:17 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: SPT72O.S14E20.part2.rar (pid:35)
637 | 04.11.2019 19:39:17 | INFO | ADDON UnSkipOnFail: No duplicates found


```
[debug_TurbobitNet_04-11-2019_19-39-17.zip](https://github.com/pyload/pyload/files/3805566/debug_TurbobitNet_04-11-2019_19-39-17.zip)

**Comment by GammaC0de** [comment]
For me it works OK,
Does it happens to you every time with the above URL?

Also, `could not convert string to float: out of memory`,
Why out of memory?

**Comment by UserX404** [comment]
No. After some time an retries it workes.
I have no glue why it happens. Is there any memory limitation for the threated webserver?

**Comment by GammaC0de** [comment]
Can you please add this line:
```
        self.log_debug('wait_time="%s" eval="%s"' % (wait_time, m.groups(1)))
```
 after [TurbobitNet.py#L59](https://github.com/pyload/pyload/blob/a93e89c78758734f37f6974c2dec1cff3c4d92a7/module/plugins/hoster/TurbobitNet.py#L59), restart pyload and when the plugin fails, post the log here?

**Comment by UserX404** [comment]
Wanna check them in the next days.

**Comment by UserX404** [comment]
It's really curious.
After adding your log-line i get no JS-Engine error.
Removed them and back to  'could not convert string to float' fault.
I restarted in between.

Appended log to zip -> [debug_TurbobitNet.zip](https://github.com/pyload/pyload/files/3821000/debug_TurbobitNet_07-11-2019_18-30-28.zip)

**Comment by GammaC0de** [comment]
I really have no clue, maybe it is really a memory issue.

What type of JS engine do you use?

**Comment by UserX404** [comment]
I placed the line after 'wait_time = self.js.eval(m.group(1))'
Now i placed it for this line and it leads to:
Download failed: SPT72O.S14E20.part2.rar | local variable 'wait_time' referenced before assignment

**Comment by GammaC0de** [comment]
It should be:
```
        wait_time = self.js.eval(m.group(1))
        self.log_debug('wait_time="%s" eval="%s"' % (wait_time, m.groups(1)))
        self.wait(wait_time)
```

**Comment by UserX404** [comment]
> 
> What type of JS engine do you use?
>

[/opt/share/pyload] # js
js> help()
JavaScript-C 1.6 pre-release 1 2006-04-04 (OSSP js 1.6.20070208)

**Comment by GammaC0de** [comment]
Maybe try uninstall it and install `duktape` instead

**Comment by UserX404** [comment]
i already checked that the line was correct placed before.
output of m.group(1) is `eval="60 - 15 + 15"` but im not sure if js is working correctly.
So I tested with pyLoadCore.py -s
Output:
```
## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: OK

py-imaging: OK
tesseract: OK

PyQt4: fehlt

jinja2: OK
beaker: OK
JS engine: OK
```

It looks ok to me. How can I check self.js is initialized correctly?
On console:
```
[/opt/var/pyload/userplugins/hoster] # js
js> eval(60 - 15 + 15)
60
```

**Comment by GammaC0de** [comment]
Can you try with `duktape` instead of OSSP js?

**Comment by UserX404** [comment]
Removed js and installed duktape and now it seems to work.
Maybe the dependency list at the install notes should be updated.

Thanks for support!

**Comment by GammaC0de** [comment]
:+1:
