### ISSUE TITLE
problem easybytez.com

### ISSUE THREAD

**Issue by alby1979** [pyload/pyload#3470]
155 | 09.11.2019 09:32:03 | DEBUG | ACCOUNT EasybytezCom: Reached login timeout for user `zob*******`
-- | -- | -- | --
156 | 09.11.2019 09:32:03 | INFO | ACCOUNT EasybytezCom: Login user `zob*******`...
157 | 09.11.2019 09:32:03 | DEBUG | ACCOUNT EasybytezCom: LOAD URL https://www.easybytez.com/login.html \| redirect=True \| decode=True \| cookies=True \| get={} \| req=None \| just_header=False \| post={} \| ref=True \| multipart=False
158 | 09.11.2019 09:32:03 | ERROR | ACCOUNT EasybytezCom: Could not login user `zob*******` \| (7, "couldn't connect to host")

thanks

**Comment by alby1979** [comment]
change address 

https://www.easybytez.com/login2.html

how change address link ?

thanks

**Comment by matrog** [comment]
looks like the right address is http://www.easybytez.com/login2.html, even if you try to change there are problems recognizing the Premium Status

**Comment by alby1979** [comment]
Hi
How can change link?
Thankyou

Il sab 9 nov 2019, 11:26 matrog <notifications@github.com> ha scritto:

**Comment by matrog** [comment]
to try I changed inside XFSAccount.py but then other things are broken and this goes beyond my knowledge

**Comment by alby1979** [comment]
unfortunately in that file there is no easybytez link

**Comment by alby1979** [comment]
@matrog
yuppiii thanks!!!

XFSAccount.py

change this

if not self.PLUGIN_URL:
            self.PLUGIN_URL = "http://www.%s/" % self.PLUGIN_DOMAIN

        if not self.LOGIN_URL:
            self.LOGIN_URL = urlparse.urljoin(self.PLUGIN_URL, "login2.html")

**Comment by matrog** [comment]
yeah, works fine now!
