### ISSUE TITLE
Plugin List list

### ISSUE THREAD

**Issue by bachph** [pyload/pyload#3478]
### Your question

The popup with all the plugins is not showing all plugins. I can't see ZippyshareCom Plugin. How can I deactivate plugins?

**Comment by GammaC0de** [comment]
>The popup with all the plugins is not showing all plugins

Which popup exactly?
Please explain your question.

**Comment by bachph** [comment]
Sorry, try to explain it more precise.

The Popup is in the Web UI at "Einstellungen > Zusatzprogramme > Menu" so I guess in english it is "Settings > Additional Programs > Menu".

Where you can edit all the settings of hosters and plugins. The list is so way to long to show all plugins. At least Chrome does not show them all so that I cant see e.g. ZippyshareCom settings.

**Comment by GammaC0de** [comment]
Can you post a screenshot?

**Comment by bachph** [comment]
Of course, check these images: https://imgur.com/a/lx4DUyN

**Comment by GammaC0de** [comment]
Please follow the instructions in https://github.com/pyload/pyload/issues/3283 and then switch the the `modern` web-ui interface.
You will have a search input box there.

**Comment by bachph** [comment]
I did exactly that a couple days ago to get the UpdateManager running. My main problem is that I cant get ZippyshareCom from downloading anything after I add links via DLC-Container.

I repeated your steps and the UI is the same. How should the `modern` web-ui interface look like?

**Comment by GammaC0de** [comment]
You **strongly** advised to switch to `modern` Web-UI, 
Basically the UI you  are using is obsolete.

**Comment by bachph** [comment]
You might have an tutorial? How exactly do I switch?
