### ISSUE TITLE
how to download more files in site

### ISSUE THREAD

**Issue by sodd** [pyload/pyload#3483]
### Your question

Hi, I have a little problem to find a way to download multiple files from one hoster and set their name from page (url for single file doesn't contain real name).

Problem is I don't know how to make a package of links with their correct names

thx for any advice @GammaC0de 

#### Page
https://dvojka.rozhlas.cz/george-agathonikiadis-na-morave-nekvetou-olivy-8115745

#### single link
https://dvojka.rozhlas.cz/sites/default/files/audios/e49c978657ba299162cbd45a32cb3277.mp3?uuid=5de40308f38df

#### real name
1. díl: George Agathonikiadis: Na Moravě nekvetou olivy

**Comment by GammaC0de** [comment]
RegEX to find Json data with name:
`<script>dataLayer = (.+?);</script>`

Get name from json:
`json_data[0]['entityLabel']`

RegEX to find Json data with the download link:
`jQuery\.extend\(Drupal.settings, (.+?)\);`

Download URLs:
`json_data['cro_soundmanager']['playtime'].keys()`

**Comment by sodd** [comment]
thx again, but i didn't said it clearly coz i have already name and download url but i don't know where to put them :( something like  

``` python
self.addpackage(PACKAGE_NAME, [(filename1, directdownloadurl1), (filename2, directdownloadurl2), (filename3, directdownloadurl3)])
```

And i am little confuse if i have to use Crypter or just a Hoster

**Comment by GammaC0de** [comment]
Crypter takes a URL and creates a package that includes a list of URLs to download and a package name (filenames are not included)

Then the hoster takes each URL within a package, parses the filename and the download URL and then download it.

**Comment by sodd** [comment]
sry for the delay,
how can i use information from Crypter (specially real filename) in Hoster plugin?

**Comment by GammaC0de** [comment]
> sry for the delay,
how can i use information from Crypter (specially real filename) in Hoster plugin?

I really don't understand your question and what is your need for it

**Comment by sodd** [comment]
well i have site with list of links with hashed names like 2xnsgdghs.mp3 and I wish to make a hoster to download all files from that site.

and I wish to set correct name for that mp3 file instead the hash one.

and thx again for your answers and patience with me :)

**Comment by GammaC0de** [comment]
So the crypter is for a specific web site, right?

Where do you get the real filenames from?

**Comment by sodd** [comment]
> So the crypter is for a specific web site, right?

right

> Where do you get the real filenames from?

the example URL from the first topic has expired so here is the new one.
https://dvojka.rozhlas.cz/vaclav-erben-poklad-byzantskeho-kupce-8147869

i wrote simple Crypter where is set 
```
    __pattern__ = r'https?://dvojka\.rozhlas\.cz/([^/]+)$'

```
and
```
decrypt()
   self.realfilenames = [('realfilename1.mp3', 'http://dvojka.rozhlas.cz/nested/download/audio/urlforfilename1', 'packagename'),
                                     ('realfilename2.mp3', 'http://dvojka.rozhlas.cz/nested/download/audio/urlforfilename2', packagename'),
                                     ('realfilename3.mp3', 'http://dvojka.rozhlas.cz/nested/download/audio/urlforfilename3, 'packagename')]
   self.links = ['urlforfilename1','urlforfilename2','urlforfilename3']
```

for Hoster i wrote
```
   __pattern__ = r'https?://dvojka\.rozhlas\.cz/nested/download/audio/[^/]+.mp3?\d+$'
```

and now i don't know how to set for correct self.pyfile.name

maybe I'm doing something completely wrong but I don't now what :(

**Comment by GammaC0de** [comment]
You could encode the information inside the URL and then send the encoded URL to the hoster.

See example how I have done this in [CloudMailRuFolder.py](https://github.com/pyload/pyload/blob/stable/module/plugins/crypter/CloudMailRuFolder.py) and [CloudMailRu.py](https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/CloudMailRu.py)

**Comment by sodd** [comment]
great, ill use this workaround, thx
