### ISSUE TITLE
ExternalScripts : Script is not executable

### ISSUE THREAD

**Issue by user4me** [pyload/pyload#3484]
Hi,

I'm not able to make ExternalScripts execute my custom sh scripts, i'm always getting a 
> WARNING | ADDON ExternalScripts: Script `move-to-finished.sh` is not executable

This script is present in my configuration dir : `scripts/all_download_finished`.

I set all permissions on script dir `chmod -R 777` and a chown -R  with the user running my pyload instance and it still doesn't work. Does someone faces the same issue ?

Thanks

**Comment by GammaC0de** [comment]
What OS are you using?

**Comment by user4me** [comment]
I was dockering Pyload, and it seems that scripts accessibles through mounted volume are not executable (Docker limitations)

So the workaround is to build the docker directly with embedded configuration.

Two ideas could make it easier : 
- Separate scripts directory from configuration directory 
- Make scripts directory configurable through UI

Anyway this issue can be closed, my bad ;) ! Hope it would be useful for some other docker users.

**Comment by GammaC0de** [comment]
> Make scripts directory configurable through UI

Isn't that a security risk?
