### ISSUE TITLE
Adding links to running pyLoad daemon

### ISSUE THREAD

**Issue by bachph** [pyload/pyload#3485]
Hi folks!

Is there a way to add e.g. a Filer.net folder/container to a running pyLoad daemon?

best regards,
bachph

**Comment by GammaC0de** [comment]
I really don't understand your question, please explain.

**Comment by bachph** [comment]
Sorry for the late response. 

I meant if there is a possibilty to add e.g. a dlc container to pyLoad via command line instead of using the web interface?

**Comment by GammaC0de** [comment]
You can use the `HotFolder` plugin
