### ISSUE TITLE
Error in build Payload 

### ISSUE THREAD

**Issue by OpenVu** [pyload/pyload#3490]
Hello  i Build enigma2 For dreambox From Openvision Source and When I compyle Payload i Get Error in do_compile in payload

### Additional references

ERROR: pyload-0.4.9-r0 do_compile: Execution of '/home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/temp/run.do_compile.30428' failed with exit code 127:
/home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/temp/run.do_compile.30428: line 99: python: command not found
WARNING: /home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/temp/run.do_compile.30428:1 exit 127 from 'python -m compileall /home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/pyload'

ERROR: Logfile of failure stored in: /home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/temp/log.do_compile.30428
Log data follows:
| DEBUG: Executing shell function do_compile
| /home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/temp/run.do_compile.30428: line 99: python: command not found
| WARNING: /home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/temp/run.do_compile.30428:1 exit 127 from 'python -m compileall /home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/pyload'
| ERROR: Execution of '/home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/temp/run.do_compile.30428' failed with exit code 127:
| /home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/temp/run.do_compile.30428: line 99: python: command not found
| WARNING: /home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/temp/run.do_compile.30428:1 exit 127 from 'python -m compileall /home/linux/dm800se/openvision-development-platform/build/tmp/work/mips32el-oe-linux/pyload/0.4.9-r0/pyload'
|
ERROR: Task (/home/linux/dm800se/openvision-development-platform/meta-openvision/recipes-connectivity/pyload/pyload.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 7804 tasks of which 7494 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/linux/dm800se/openvision-development-platform/meta-openvision/recipes-connectivity/pyload/pyload.bb:do_compile
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

SUMMARY = "pyLoad is a fast, lightweight and full featured download manager for many One-Click-Hoster"
LICENSE = "GPLv3"
LIC_FILES_CHKSUM = "file://LICENSE;md5=d4333f07cbfa8fe036e90820f556b2ad"
HOMEPAGE = "http://pyload.org/"
RDEPENDS_${PN} = "\
  python-compression \
  python-db \
  python-email \
  python-html \
  python-imaging \
  python-numbers \
  python-pprint \
  python-pycrypto \
  python-pycurl \
  python-sqlite3 \
  python-subprocess \
  python-terminal \
  python-unixadmin \
  python-xmlrpc \
"
RRECOMMENDS_${PN} = "unrar"

PV = "0.4.9"

inherit update-rc.d

SRC_URI = "http://source.mynonpublic.com/pyload-src-v${PV}.zip \
  file://pyload.init \
  file://pyload.tar.gz.defaults"
SRC_URI[md5sum] = "28876150af22999b6f539c8579d3b415"
SRC_URI[sha256sum] = "f937631d376216bc830d6ffcd5b4ecb1806afd4012a184849da1a333a7ba0016"

S = "${WORKDIR}/pyload"

FILES_${PN} = "/usr/pyload/* /etc/*"

INITSCRIPT_NAME = "${PN}"
INITSCRIPT_PARAMS = "defaults 60 "

do_compile() {
    python -m compileall ${S}
}

do_install() {
    install -d ${D}/etc/init.d
    install -d ${D}/usr/pyload

    cp -r ${S}/icons ${D}/usr/pyload
    cp -r ${S}/locale ${D}/usr/pyload
    cp -r ${S}/module ${D}/usr/pyload
    cp -r ${S}/scripts ${D}/usr/pyload
    install -m 755 ${S}/pyLoadCli.py ${D}/usr/pyload
    install -m 755 ${S}/pyLoadCore.py ${D}/usr/pyload
    install -m 755 ${S}/systemCheck.py ${D}/usr/pyload
    cp ${WORKDIR}/pyload.tar.gz.defaults ${D}/usr/pyload/pyload-defaults.tar.gz
    
    install -m 0755 ${WORKDIR}/pyload.init ${D}/etc/init.d/pyload
}

**Comment by GammaC0de** [comment]
@OpenVu 
I am not familiar with this platform but I can see that the source of your installation is a **VERY** old version of pyload.

Basically to run pyload you have to have a running python 2.7 installation with some python modules installed.

If you have python 2.7 installed and running I can guide you.
