### ISSUE TITLE
I not can start Pyload

### ISSUE THREAD

**Issue by juankaxxi** [pyload/pyload#3491]
i have this error:

root@OpenWrt:/mnt/Disk1/Pyload# python ./pyLoadCore.py
13.12.2019 12:49:54 INFO      Starting pyLoad 0.4.9
13.12.2019 12:49:54 INFO      Using home directory: /mnt/Disk1/Pyload/.pyload
13.12.2019 12:50:01 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
13.12.2019 12:50:01 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
13.12.2019 12:50:01 INFO      Downloadtime: True
13.12.2019 12:50:01 ERROR     <<< UNCAUGHT EXCEPTION >>>
Traceback (most recent call last):
  File "./pyLoadCore.py", line 686, in <module>
    main()
  File "./pyLoadCore.py", line 677, in main
    pyload_core.start()
  File "./pyLoadCore.py", line 418, in start
    self.remoteManager.startBackends()
  File "/mnt/Disk1/Pyload/module/remote/RemoteManager.py", line 76, in startBackends
    klass = getattr(__import__("module.remote.%s" % b, globals(), locals(), [b], -1), b)
AttributeError: 'module' object has no attribute 'ThriftBackend'

whats happens?

**Comment by GammaC0de** [comment]
How exactly did you installed pyload?

**Comment by juankaxxi** [comment]
I had Pyload installed on a Xiaomi 3G router, which worked perfectly. Now it has stopped working and I saw this post and reinstalled it again but it gives me that error.

**Comment by juankaxxi** [comment]
https://github.com/pyload/pyload/issues/3487

I Reinstalled from here

**Comment by GammaC0de** [comment]
>I had Pyload installed on a Xiaomi 3G router

How did you installed it in the first place?

>Now it has stopped working

Have you updated python core modules (not plugins) before it stopped working?
What happens if you reinstall the normal `stable` version again? does it work?

Can you successfully run this python code:
```
from OpenSSL import SSL
SSL.Connection
```

**Comment by juankaxxi** [comment]
I install it like this:

install these modules:
python-curl python-crypto python-sqlite3 python-openssl pyopenssl openssl-util python-expat unzip unrar screen wget python-pyopenssl python python-pip python-crypto python-curl python-openssl pillow tesseract js

Then I set up Pyload

And then i receive this mensage:
root@OpenWrt:/mnt/Disk1/Pyload# python ./pyLoadCore.py
13.12.2019 12:49:54 INFO Starting pyLoad 0.4.9
13.12.2019 12:49:54 INFO Using home directory: /mnt/Disk1/Pyload/.pyload
13.12.2019 12:50:01 INFO Activated plugins: ClickNLoad, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
13.12.2019 12:50:01 INFO Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
13.12.2019 12:50:01 INFO Downloadtime: True
13.12.2019 12:50:01 ERROR <<< UNCAUGHT EXCEPTION >>>
Traceback (most recent call last):
File "./pyLoadCore.py", line 686, in
main()
File "./pyLoadCore.py", line 677, in main
pyload_core.start()
File "./pyLoadCore.py", line 418, in start
self.remoteManager.startBackends()
File "/mnt/Disk1/Pyload/module/remote/RemoteManager.py", line 76, in startBackends
klass = getattr(import("module.remote.%s" % b, globals(), locals(), [b], -1), b)
AttributeError: 'module' object has no attribute 'ThriftBackend'


"from OpenSSL import SSL
SSL.Connection"
The latter I don't know how to do it

**Comment by GammaC0de** [comment]
From putty shell do:

python2
from OpenSSL import SSL
SSL.Connection

**Comment by juankaxxi** [comment]
i get  this error:

root@OpenWrt:~# python2
Python 2.7.17 (default, Dec 10 2019, 08:54:20)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenSSL import SSLfrom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
ImportError: Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: EC_GROUP_get_curve_GF2m: symbol not found
>>> SSL.Connection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'SSL' is not defined
>>> SSL.Connection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'SSL' is not defined
>>>

**Comment by GammaC0de** [comment]
@juankaxxi Are you using OpenWrt on your Xiaomi 3G router?

**Comment by juankaxxi** [comment]
yes, the version is:

openwrt-18.06.5-ramips-mt7621-mir3g-squashfs-sysupgrade

Pyload Version is:

Pyload unicode-fix

**Comment by GammaC0de** [comment]
Try updating to the latest version, it may help

**Comment by juankaxxi** [comment]
it´s is the last version

**Comment by juankaxxi** [comment]
No solution???

**Comment by juankaxxi** [comment]
I have installed other versions that I had of Pyload and they all give the same error.

Have you updated any Python module that is the cause of the problem?

I could install version 0.5?

If the answer is yes, can you give me the direct download address?

thaks

**Comment by GammaC0de** [comment]
just let me understand:
You had pyload working on openwrt-18.06.5-ramips-mt7621-mir3g-squashfs-sysupgrade and then suddenly it stopped working?
Or If so, have you updated pyload modules  and then it stopped working?

pyload 0.5 is not ready yet, sorry.

**Comment by juankaxxi** [comment]
yes, I have written a line for the openwrt modules to automatically update every 2 weeks.

Surely some module that has been updated is the one that is giving fault, but I have no idea.

I have installed other versions of openwrt and pyload and always the same fault.

**Comment by juankaxxi** [comment]
The problem is solved. The problem was that in the name of the folder, I had an uppercase letter that I did not write in the configuration, example:

i put it:  "/mnt/Disk1/PyLoad/.pyload"

and the folder was called "Pyload"

**Comment by GammaC0de** [comment]
Oh 🎉 

That's good news 👍
