### ISSUE TITLE
Can't recognize YouTube Chinese video tiles

### ISSUE THREAD

**Issue by dg9999cn** [pyload/pyload#3492]
### Describe the problem

Can't recognize YouTube Chinese video tiles
I guess it's decode error in Chinese titles
 1 _______.mp4
finished  7.48 MiB YoutubeCom 
It replace Chinese with underline.

### Debug log

```

```

### Additional references

Python:2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]OS:posix linux2 Linux dellomv 4.19.0-0.bpo.4-amd64 #1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27) x86_64pyLoad version:0.4.9Installation Folder:/opt/pyloadConfig Folder:/opt/pyload/pyload-configDownload Folder:/opt/pyload/DownloadsFree Space:1.89 TiBLanguage:enWebinterface Theme:modern by GammaC0de based on work of Marco Fernandes and Dogan BagciWebinterface Port:8187Remote Interface Port:7227

**Comment by GammaC0de** [comment]
See https://github.com/pyload/pyload/issues/3487

**Comment by dg9999cn** [comment]
https://www.youtube.com/watch?v=Oj92o6QN1kY&list=PLr3TS7r_zdDu701sMVyd4Q7KHS6z7iIl2&index=24&t=0s

**Comment by GammaC0de** [comment]
Have you tried #3487?

**Comment by dg9999cn** [comment]
Don't know how to do it in docker. My docker run in openmediavault 4.
At step 7, I need the pyload docker container running to exec bash and replace the file in pyload-python2-unicode-fix.zip. 
1. download pyload-python2-unicode-fix.zip in folder Downloads
2. unzip pyload-python2-unicode-fix.zip
3. docker exec -it pyload bash                                                     
4. cd /opt/pyload/
5. cd Dowloads/pyload-python2-unicode-fix
6. cp * /opt/pyload/
7. rm -f /opt/pyload/pyload-config/userplugin/ 
(without stop pyload docker container, for I can't "docker exec -it pyload bash" if I stop the container)
8. exit
9. docker stop pyload
10. docker start pyload

this is what I got after restart pyload docker container.
Choose your Language / Wähle deine Sprache ([en], de, fr, it, es, nl, sv, ru, pl, cs, sr, pt_BR): Setup failed
Traceback (most recent call last):
  File "/opt/pyload/pyLoadCore.py", line 284, in start
    res = s.start()
  File "/opt/pyload/module/setup.py", line 40, in start
    lang = self.ask(u"Choose your Language / Wähle deine Sprache", "en", langs)
  File "/opt/pyload/module/setup.py", line 485, in ask
    input = raw_input(qst + " %s: " % info)
EOFError: EOF when reading a line
This is your first start, running configuration assistent now.

**Comment by dg9999cn** [comment]
The new version works perfect now.
