### ISSUE TITLE
AllDebrid Plugin does not work

### ISSUE THREAD

**Issue by kaiffeetasse** [pyload/pyload#3499]
### Describe the problem

I want to download from ddl.to which is supported by AllDebrid. I already added my account with the security token provided by AllDebrid and activated the AllDebrid plugin. Pyload still uses the DdlTo plugin resulting in a captcha request.

### Debug log

```
339 | 01.01.2020 17:21:39 | INFO | Added package abc123 containing 1 links
-- | -- | -- | --
340 | 01.01.2020 17:21:40 | INFO | Download starts: https://ddl.to/abc123
341 | 01.01.2020 17:21:40 | WARNING | HOSTER DdlTo[308]: Plugin may be unstable
342 | 01.01.2020 17:21:40 | INFO | HOSTER DdlTo[308]: Grabbing link info...
343 | 01.01.2020 17:21:40 | INFO | HOSTER DdlTo[308]: Link name: abc123.rar
344 | 01.01.2020 17:21:40 | INFO | HOSTER DdlTo[308]: Link size: 103.83 MiB (108873646 bytes)
345 | 01.01.2020 17:21:40 | INFO | HOSTER DdlTo[308]: Link status: online
346 | 01.01.2020 17:21:40 | INFO | HOSTER DdlTo[308]: Processing url: https://ddl.to/abc123
347 | 01.01.2020 17:21:40 | INFO | HOSTER DdlTo[308]: Checking for link errors...
348 | 01.01.2020 17:21:40 | INFO | HOSTER DdlTo[308]: No errors found
349 | 01.01.2020 17:21:40 | INFO | HOSTER DdlTo[308]: Processing as free download...
350 | 01.01.2020 17:21:40 | INFO | HOSTER DdlTo[308]: Checking for link errors...
351 | 01.01.2020 17:21:40 | INFO | HOSTER DdlTo[308]: No errors found
352 | 01.01.2020 17:21:40 | WARNING | CAPTCHA DdlTo[308]: ReCaptcha \| Secure Token pattern not found
353 | 01.01.2020 17:21:40 | WARNING | CAPTCHA DdlTo[308]: ReCaptcha \| Secure Token pattern not found
```

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
From the documentation (https://docs.alldebrid.com/#user-hosts) 
`status - Is the host currently (< 5 min) working on Alldebrid.`

After issuing an API query (`https://api.alldebrid.com/user/hosts?token=<YOUR_API_TOKEN>&agent=pyLoad&version=0.4.9`)
Alldebrid falsely send false `status` for ddl.to , even tough they actually DO support it :flushed: 

Can you please contact alldebrid's support and ask why they return `status` false for ddl.to even tough they DO support it?
Should we ignore the value of `status`?

**Comment by kaiffeetasse** [comment]
When you take look at the response from the user-hosts API, they actually list ddl.to under redirectors -> generic -> regexp

I think as a workaround it would be okay to ignore the `status` field.

**Comment by GammaC0de** [comment]
Added "Treat all hosters as available" configuration option (disabled by default).

**Comment by kaiffeetasse** [comment]
It's still asking for a captcha.

what if you just use the generic hoster list?
this should work:

`hosters = data["redirectors"]["generic"]["regexp"]
hosters = hosters.replace("((", "").replace(")/folders?/[^'\"<>;]+)", "")
return [x.strip() for x in hosters.split("|") if x]`

**Comment by GammaC0de** [comment]
> disabled by default

You have to enable `Treat all hosters as available` configuration option to make it work.

**Comment by kaiffeetasse** [comment]
I enabled it, it still asks for a captcha.

**Comment by GammaC0de** [comment]
I had tested it and it worked,
Please update your installation using the instructions in #3283 and then try again.

**Comment by kaiffeetasse** [comment]
Thanks, my pyload installation wasn't up to date! Now it works.

That workaround treats all urls the same,
what do you think about the fix I suggested?

**Comment by GammaC0de** [comment]
>That workaround treats all urls the same,
what do you think about the fix I suggested?

What do you mean by that?

**Comment by kaiffeetasse** [comment]
```
hosters = json_data["redirectors"]["generic"]["regexp"]
hosters = hosters.replace("((", "").replace(")/folders?/[^'\"<>;]+)", "")
return [x.strip() for x in hosters.split("|") if x]
```

This would fix the problem since it uses the hosters provided in the generic hoster list

**Comment by GammaC0de** [comment]
The result is the same, aint it? 
I prefer to give the user the choice to decide if to ignore the `status` field or not.

**Comment by kaiffeetasse** [comment]
As I understand, the plugin would now take any link, even if AllDebrid doesn't support it, doesn't it?
I don't think this is a correct function of that plugin...
What if you merge your code with mine? Then the user would still have the choice and the plugin would work correctly again.

**Comment by GammaC0de** [comment]
`Treat all hosters as available` means "treat all hosters that  AllDebrid reports in the API query as available", that's it.
