### ISSUE TITLE
RapiduNet qnap 4.4.1 issue file offline

### ISSUE THREAD

**Issue by shuvarec** [pyload/pyload#3502]
HOSTER RapiduNet[2]: Plugin may be unstable
![Screen Shot 2020-01-07 at 11 29 54 PM](https://user-images.githubusercontent.com/40018386/71958662-ad97e800-31a5-11ea-8315-4b03d618a06b.png)

Qnap updated to 4.4.1

**Comment by GammaC0de** [comment]
This works fine for me,
Please update your installation using the instructions in #3283 and then try again.

**Comment by shuvarec** [comment]
working perfect . Thanks .
