### ISSUE TITLE
ExtractArchive doesn't extract after download

### ISSUE THREAD

**Issue by Hamm3rhart** [pyload/pyload#3504]
### Describe the problem

Hello,
i just installed pyload on my rasspberry pi and it works just fine. But whenever a download is finished the ExtractArchive ADDON doesn't started extracting, because it says "that there are no files to extract". On my Ubuntu server everything works fine so i don't know the problem here. The filelocation (Download Folder and Extraction Folder) is on a mounted NTFS drive.

rasspberry pi verison: uname -a
`Linux SVPi-hole 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux`
### Debug log

```
09.01.2020 18:30:21 INFO      Download finished: <File.part2.rar>
09.01.2020 18:30:21 INFO      Package finished: <Name>
09.01.2020 18:30:21 INFO      ADDON ExtractArchive: Check package: <Package1>
09.01.2020 18:30:21 INFO      ADDON ExtractArchive: Check package: <Package1>
09.01.2020 18:30:22 INFO      ADDON ExtractArchive: No files found to extract
09.01.2020 18:30:22 INFO      ADDON ExtractArchive: No files found to extract
```
Thats the only related log that i have got so far. With debug mode enabled,
### Additional references

If i you need more information, please ask me.

**Comment by Hamm3rhart** [comment]
Fixed. Needed to install Unrar so that pyload could see? extract? them. I don't know. But now it works.

btw. it was a bit tricky to install unrar but if you so dumb as i am you can do it pretty well

**Comment by GammaC0de** [comment]
👍

**Comment by ingjcgonzalez** [comment]
Hi! @GammaC0de I got a particular situation with ExtractArchive. Let me put you on context:
I use pyload on a PC with CentOS just in CLI. So, to automatize the start of pyload, a few year ago I found a bash script to do it. I did some personalizations on that script, I share you a lil bit down.

Well, I added like a service using
`chkconfig --add pyloadd`

And run it like this `service pyloadd start`

So, I realize that ExtractArchive wasn't working. I though that may be I didn't have `rar` and `unrar` installed, but both were installed. Any way, I run pyload on debug mode and surprise! ExtractArchive it's working. I run it againg like a service but not working again (log doesn't show nothing, just `ADDON ExtractArchive: No files found to extract`. But in debug mode works fine).

I quit pyload and run it with full command path `python pyLoadCore.py --daemon` and ExtractArchive it's working. So, I guess that the problem it's with the script. What can a I do to fix it? This is the bash script:
`
#!/bin/bash
#
# pyLoad daemon
#
# chkconfig: 345 99 01
# description: pyLoad daemon 
# processname: pyload
# Source function library.
. /etc/init.d/functions
# Declare variables
NAME=pyload
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON="python /etc/pyload/pyLoadCore.py --daemon"
DAEMON_OPTS="--debug"
STATUS="python /etc/pyload/pyLoadCore.py --status"
VERSION="python /etc/pyload/pyLoadCore.py -v"
#UPDATE_SRC="https://bitbucket.org/spoob/pyload/get/tip.zip"
UPDATE_SRC="https://github.com/pyload/pyload/archive/stable.zip"
LOG="/etc/pyload/.pyload/Logs/log.txt" #your path to the Logfile here!
CLEAR="python /etc/pyload/pyLoadCore.py --clear"
USER="python /etc/pyload/pyLoadCore.py -u"
SETUP="python /etc/pyload/pyLoadCore.py -s"
CONFIGDIR="python /etc/pyload/pyLoadCore.py --configdir"
CHANGEDIR="python /etc/pyload/pyLoadCore.py --changedir"
QUIT="python /etc/pyload/pyLoadCore.py -q"
##########################################################################
# COMMANDS START
##########################################################################
start()
{
     if [ `$STATUS` != false ]; then
          echo "`$VERSION`: actualmente en ejecucion"
     else
          echo "`$VERSION`: iniciando"
          echo "`$VERSION`:" `$DAEMON`
          sleep 2
               if [ `$STATUS` != false ]; then
                   echo "`$VERSION`: inicio exitoso"
               else
                  `$DAEMON`
               fi
     fi
}
##########################################################################
stop()
{
    if [ `$STATUS` != false ]; then
          echo "`$VERSION`: cerrando proceso"
          kill `$STATUS`; sleep 2
          echo "`$VERSION`: proceso terminado con exito"
    else
          echo "`$VERSION`: actualmente terminado"
    fi
}
##########################################################################
update()
{
   if [ `$STATUS` != false ]; then
        quit; sleep 5;
else
echo "intentando actualizar `$VERSION`"
   fi
    cd /tmp
        wget --no-check-certificate -q $UPDATE_SRC
              if [ $? -eq 0 ] ; then
                 echo "UPDATE: version dev cargada con exito"
              else
                update
              fi
              unzip -o /tmp/stable.zip; rm -f /tmp/stable.zip
              if [ $? -eq 0 ] ; then
                 echo "UPDATE: archivo descomprimido y eliminado"; sleep 2
              else
                 update
              fi
                 rsync -ru /tmp/pyload-stable/ /etc/pyload/
              if [ $? -eq 0 ] ; then
                  echo "UPDATE: `$VERSION` actualizado con exito"
              else
                  update
              fi
                  rm -rf /tmp/pyload-stable/
                  echo "`date '+%d.%m.%Y %T'` INFO      Update complete" >>$LOG
              start
}
##########################################################################
debug()
{
    if [ `$STATUS` != false ]; then
        echo "`$VERSION`: actualmente en ejecucion... reiniciando"
        quit
        sleep 5
        debug
    else
        echo "`$VERSION`: iniciando en modo de depuracion + mostrar en pantalla salida"
        echo "`$VERSION`:" `$DAEMON $DAEMON_OPTS`
        sleep 2
        if [ `$STATUS` != false ]; then
               echo "`$VERSION`: modo de depuracion iniciado con exito"
               echo ""
               echo "***** ctrl + c para detener y regresar *****"
               echo ""
               tail -f $LOG
        else
               `$DAEMON $DAEMON_OPTS`
        fi
    fi
}
##########################################################################
info()
{
     if [ `$STATUS` != false ]; then
          echo "`$VERSION`: el ID del proceso es `$STATUS`"
          echo ""
echo '####################################################################'
echo ' OPCIONES'
echo ' start      = iniciar pyLoad (default)'
echo ' stop       = detener pyLoad forzado'
echo ' restart    = reiniciar pyLoad'
echo ' update     = actualiza los archivos del programa'
echo ' debug      = habilita el modo de depuracion + output'
echo ' info       = muestra el PID y estado de pyLoad'
echo ' show       = muestra el archivo Log mientras se ejecuta'
echo ' clear      = elimina todos los paquetes/enlaces'
echo ' user       = administra los usuario'
echo ' setup      = ejecuta el asistente de instalacion'
echo ' changegdir = cambia el directorio config'
echo ' configdir  = ejecuta con el <dir> como directorio confi'
echo ' quit       = cierra pyLoad de forma segura'
echo '####################################################################'

     else
           echo "`$VERSION`: el proceso no esta en ejecucion, nada por hacer"
     fi
}
##########################################################################
show()
{
     start
     while [ `$STATUS` != false ]; do
        echo ""
        echo "***** ctrl + c para detener y regresar *****"
        echo ""
        tail -f $LOG
     done
}
##########################################################################
clear()
{
   if [ `$STATUS` != false ]; then
        quit; sleep 5;
else
echo "Eliminando los paquetes/enlaces de la cola"
fi
$CLEAR
}
##########################################################################
user()
{
   if [ `$STATUS` != false ]; then
        quit; sleep 5;
else
echo "Administrando usuarios"
fi
$USER
}
##########################################################################
setup()
{
   if [ `$STATUS` != false ]; then
        quit; sleep 5;
else
echo "Ejecutando asistente de configuracion"
fi
$SETUP
}
##########################################################################
configdir()
{
   if [ `$STATUS` != false ]; then
        quit; sleep 5;
else
echo "Usando el directorio seleccionado"
fi
$CONFIGDIR
}
##########################################################################
changedir()
{
   if [ `$STATUS` != false ]; then
        quit; sleep 5;
else
echo "Cambiando el directorio config permanentemente"
fi
$CHANGEDIR
}
##########################################################################
quit()
{
    if [ `$STATUS` != false ]; then
          echo "`$VERSION`: saliendo"
          $QUIT ; sleep 2
          echo "`$VERSION`: se ha salido con exito"
    else
          echo "`$VERSION`: actualmente terminado"
    fi
}
##########################################################################
case "$1" in
      start)
              start
              ;;
      stop)
              stop
              ;;
      restart)
              quit
              sleep 2
              start
              ;;
      update)
              update
              ;;
      debug)
              debug
              ;;
      info)
              info
              ;;
      show)
              show
              ;;
      clear)
              clear
              ;;
      user)
              user
              ;;
      setup)
              setup
              ;;
      changedir)
              changedir
              ;;
      configdir)
              configdir
              ;;
      quit)
              quit
              ;;
      *)
              echo "Usage: $NAME (start|stop|quit|restart|update|debug|info|show|clear|user|setup|configdir|changedir)" >&2
              exit 1
              ;;
esac

exit 0
`

**Comment by GammaC0de** [comment]
@ingjcgonzalez Obviously this is a PATH issue.
I think you should change:
```
PATH=/sbin:/bin:/usr/sbin:/usr/bin
```
to:
```
export PATH=/sbin:/bin:/usr/sbin:/usr/bin
```

**Comment by ingjcgonzalez** [comment]
Thanks, I'll check today, so I can give you a feedback about this. Thanks again, you rocks!

**Comment by ingjcgonzalez** [comment]
@GammaC0de nothing my friend, it doesn't works yet. Still show me the log `no file found to extract`

**Comment by GammaC0de** [comment]
Where unrar and 7z are located?

**Comment by ingjcgonzalez** [comment]
I use `unrar`, it's located on `/usr/local/bin/`

**Comment by GammaC0de** [comment]
> PATH=/sbin:/bin:/usr/sbin:/usr/bin

OK,
So it seems that the value of PATH is wrong, is should be
```
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
```

Also, for best result, 7z is recommended.

**Comment by ingjcgonzalez** [comment]
@GammaC0de you're a crack! it's working now. I'll try with 7z. Thanks!
