### ISSUE TITLE
Uptobox.com Host - premium account login fails

### ISSUE THREAD

**Issue by Parlendir** [pyload/pyload#3506]
### Describe the problem

Hi, 
I got pyload 0.4.9 running on a Qnap Nas.
Hi, 
I have a problem with taking into account a premium uptobox account: this one is not recognized by the plugin: the plugin displays that the account is "valid" in the status field, but marks it as "not premium".
Is this issue known ? I hope it is not linked this the qnap ssl certificate :/

### Debug log

1016 | 22.01.2020 22:20:58 | INFO | ACCOUNT UptoboxCom: Adding user `Par*******`...
-- | -- | --
1017 | 22.01.2020 22:20:58 | INFO | ACCOUNT UptoboxCom: Relogin user `Par*******`...
1018 | 22.01.2020 22:20:58 | INFO | ACCOUNT UptoboxCom: Grabbing account info for user `Par*******`...
1019 | 22.01.2020 22:20:58 | WARNING | ACCOUNT UptoboxCom: Error loading info for user `Par*******` \| (51,  "SSL: certificate subject name 'QNAP NAS' does not match target host  name 'www.uptobox.com'")

### Screenshots

In settings / accounts : 

Plugin | Nom | Mot de passe | Statut | Premium | Valide jusqu'au | Trafic restant | Temps | Maximum en Parallèle | Supprimer ?
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
UptoboxCom | Parlendir |   | valide | non | non disponible | non disponible |   |   |

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by Parlendir** [comment]
Credits sent.

**Comment by GammaC0de** [comment]
:+1:

**Comment by GammaC0de** [comment]
Works fine for me,
Please update your pyload installation using the instructions in https://github.com/pyload/pyload/issues/3283 and then retry

**Comment by Parlendir** [comment]
Thnak you for the review. I'll do the mentionned procedure tonight.
So far, before any reinstall, the complete debug log : 

Line|timestamp|grav|mess
-- | -- | -- | -- | 
1064 | 24.01.2020 07:21:07 | INFO | ACCOUNT UptoboxCom: Adding user `Par*******`...
1065 | 24.01.2020 07:21:07 | DEBUG | ACCOUNT UptoboxCom: Reached login timeout for user `Par*******`
1066 | 24.01.2020 07:21:07 | INFO | ACCOUNT UptoboxCom: Relogin user `Par*******`...
1067 | 24.01.2020 07:21:07 | DEBUG | ACCOUNT UptoboxCom: LOAD URL https://uptobox.com/login \|  redirect=True \| cookies=True \| get={} \| req=None \| decode=True \|  multipart=False \| post={} \| ref=True \| just_header=False
1068 | 24.01.2020 07:21:07 | DEBUG | ACCOUNT UptoboxCom: LOAD URL https://uptobox.com/login \|  redirect=True \| cookies=True \| get={'referer': 'homepage'} \| req=None \|  decode=True \| multipart=False \| post={'login': 'Par*******', 'password':  '**********'} \| ref=True \| just_header=False
1069 | 24.01.2020 07:21:07 | INFO | ACCOUNT UptoboxCom: Grabbing account info for user `Par*******`...
1070 | 24.01.2020 07:21:07 | DEBUG | ACCOUNT UptoboxCom: LOAD URL http://www.uptobox.com/ \| redirect=True  \| cookies=True \| get={'op': 'my_account'} \| req=None \| decode=True \|  multipart=False \| post={} \| ref=True \| just_header=False
1071 | 24.01.2020 07:21:07 | WARNING | ACCOUNT UptoboxCom: Error loading info for user `Par*******` \| (51,  "SSL: certificate subject name 'QNAP NAS' does not match target host  name 'www.uptobox.com'")
1072 | 24.01.2020 07:21:07 | DEBUG | ACCOUNT UptoboxCom: Account info for user `Par*******`: {'login':  {'timestamp': 1579846867.270341, 'password': '**********', 'valid':  True}, 'data': {'premium': None, 'plugin': ,  'trafficleft': None, 'maxtraffic': None, 'validuntil': None, 'login':  'Par*******', 'type': 'UptoboxCom', 'options': {'limitDL': ['0']}}}

**Comment by Parlendir** [comment]
I've followed the pointed procedure. All clear now, it's working like a charm again ! Thank you very much ! :D 
Bug solved and closed !
