### ISSUE TITLE
unknown file after download it to PC

### ISSUE THREAD

**Issue by ruimgp** [pyload/pyload#3507]

**Comment by ruimgp** [comment]
Unknown file after download. Only capital letters (D286PF~V) not the original name.

It is a movie but can't open it to watch.

pyload version: linuxserver/pyload

Can you help me?
![pyloadfile](https://user-images.githubusercontent.com/57061652/73118589-09a48f80-3f4e-11ea-830d-93de7ab104d7.jpg)

**Comment by GammaC0de** [comment]
URL please.

**Comment by GammaC0de** [comment]
No response, closing.
