### ISSUE TITLE
DebridItaliaCom: Login handshake has failed

### ISSUE THREAD

**Issue by MikeD23** [pyload/pyload#3509]
Hi,
login to my DebridItalia account seems not to work anymore. Could not find any answer in the similar tickets. Does it need to be fixed in code or is the problem somewhere else?
I can send you account credentials if I need to.
`
03.02.2020 22:58:14 | INFO | ACCOUNT DebridItaliaCom: Adding user `Mik*******`...
-- | -- | -- | --
03.02.2020 22:58:14 | INFO | ACCOUNT DebridItaliaCom: Login user `Mik*******`...
03.02.2020 22:58:14 | ERROR | ACCOUNT DebridItaliaCom: Could not login user `Mik*******` \| Login handshake has failed
03.02.2020 22:58:15 | ERROR | ACCOUNT DebridItaliaCom: Could not load hoster list - invalid account, retry in 5 minutes
`

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by MikeD23** [comment]
Credentials sent

**Comment by GammaC0de** [comment]
Works fine for me,
Please refresh your pyLoad installation using the instruction in #3283 and then retry.

**Comment by MikeD23** [comment]
Tried without changing anything except new temp credentials and it works. Maybe there is some problems with special characters.

**Comment by GammaC0de** [comment]
:+1:
