### ISSUE TITLE
[alfafile.net] Plugin request

### ISSUE THREAD

**Issue by axzxc1236** [pyload/pyload#3516]
### Describe the plugin

I hope pyload can support downloading from alfafile.net.

### Sample resources

As far as I can tell there are two kinds of links

http://alfafile.net/file/8Xohj/example.txt

http://alfafile.net/file/8Xohj/     (shortened version)

**Comment by GammaC0de** [comment]
Sorry for so late, busy times...

**Comment by axzxc1236** [comment]
Don't say sorry, I'm thrilled that the plugin is here, and it works!
