### ISSUE TITLE
Pyload installation

### ISSUE THREAD

**Issue by muniv11111** [pyload/pyload#3518]
### Your question

Hello,

I am new to pyload, and try using pyload on seedbox server: seedhost.eu
But I see only few hosters: 

https://pasteboard.co/IVwiDmz.png
https://pasteboard.co/IVwlPCL.png

I dont have root access on this server.
How could I upgrade or add modules? 

Support on seedhost tell me to this: 
" Hi,

how can I update pyload? Only few hosters are available in web interface under config/accounts against current version, see https://github.com/pyload/pyload/wiki/Supported-Hoster.

Best regards.

Hi,

You have the latest version installed. If you are missing any module, you need to install it yourself.

Best Regards, "

**Comment by GammaC0de** [comment]
Update your pyload installation using the instructions in https://github.com/pyload/pyload/issues/3283
