### ISSUE TITLE
zippyshare.com - wrong filenames

### ISSUE THREAD

**Issue by oltodosel** [pyload/pyload#3519]
Filenames of all files show up like this:
`Math[e36.h8a(+15)];}},{'key':e36.h8a(409\|0),'value':function Q57(n57){return Math[e36.w8a(90)](this[e36.h8a(550-0)]-this[e36.w8a(498)](n57))>J87;}},{'key':e36.h8a(+75),'value':function C57(){var G57,S57;e36.U36(2);G57=e36.r36(0,0);S57=+0`

Example link: https://www43.zippyshare.com/v/Cl7tr7kX/file.html

**Comment by ktw77** [comment]
can confirm this is happening consistently, even with manual link adding or by use of dlcs

**Comment by maikyyy** [comment]
Mass loader protection?

Use following settings and it workds like a charm

Max Parallel Downloads: 1
Max connections for one download: 8

kind regards

**Comment by GammaC0de** [comment]
@maikyyy The download was successful and only the file name was incorrect ?

**Comment by maikyyy** [comment]
Downloading more than one file at the same time results in incorrect file names.

Max Parallel Downloads: 1 (important)
Max connections for one download: 4 or 5 or 6 or 8 (works)

Loading 1 file at the same time with multiple chunks works.

kind regards

**Comment by oltodosel** [comment]
With the link I provided in the first post it's still gives wrong name even if I set to download only this one link.

**Comment by maikyyy** [comment]
worksforme

`
 test
1 / 1
490.00 MiB / 490.00 MiB
Ordner: test
Passwort:

    YiY14534620200220080619.part04.rar
    Fertig  490.00 MiB ZippyshareCom    
`

My setup

`
System

Python:
    2.7.17 (default, Nov 7 2019, 10:07:09) [GCC 7.4.0]
Betriebssystem:
    posix linux2 Linux ********* 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64
pyLoad Version:
    0.4.20
Webinterface Theme:
    pyplex by GammaC0de based on work of Marco Fernandes and Dogan Bagci
`

kind regards

**Comment by GammaC0de** [comment]
@oltodosel Can you provide debug logs?

**Comment by oltodosel** [comment]
https://0x0.st/iZMb.txt

**Comment by GammaC0de** [comment]
Anyone of you guys know some python or how to edit .py files?

**Comment by oltodosel** [comment]
Yes?

**Comment by GammaC0de** [comment]
Can you enable debug mode and then put these lines as the first lines of `hoster/ZippyshareCom.py`'s `handle_free()` function?

```
        self.dump_html()
        return 
```

Then you retry the download (please create a new package, don't retry existing one)
You will have a .dump.html file inside `<PYLOAD_WORKDIR>\tmp\ZippyshareCom` directory.
Please send this file.

**Comment by oltodosel** [comment]
https://0x0.st/iZMp.html

**Comment by GammaC0de** [comment]
@oltodosel Beside the wrong file name, are you able to download successfully?

**Comment by oltodosel** [comment]
Yes.

**Comment by maikyyy** [comment]
**Edit file**
/usr/share/pyload/module/plugins/hoster/ZippyshareCom.py

`    def handle_free(self, pyfile):`
`        self.captcha = ReCaptcha(pyfile)`
`        captcha_key = self.captcha.detect_key()`
...

`    def handle_free(self, pyfile):`
`        self.dump_html()`
`        return`
...
`        self.captcha = ReCaptcha(pyfile)`
...

right?

**Log**
https://pastebin.com/R6QKayYV

**Comment by GammaC0de** [comment]
> @oltodosel Beside the wrong file name, are you able to download successfully?
> > Yes.

Does the file name is correct on the disk but not in the package info?


Fix is on the way,
If you do not want to wait, you can upgrade to pyload v0.4.20 (the file name it updated from the `Content-Disposion` HTTP header)

**Comment by maikyyy** [comment]
**0.4.20 without *.py edit**

https://pastebin.com/2TnWerXx

**Comment by oltodosel** [comment]
@GammaC0de Both filenames are the same jumble.

**Comment by m-ango** [comment]
Can confirm. When downloading multiple files in parallel the names are all messed up. Downloading does not work then sometimes. 
It gives me a unkown location error, I think its because the name is messed up. But some files are working.
