### ISSUE TITLE
Updating pyload to v4.9.20

### ISSUE THREAD

**Issue by morefreedom** [pyload/pyload#3524]
Whats the best was to update pyload to v4.9.20 whithout loosing any settings?
Can anyone please give some detailed instructions.

**Comment by GammaC0de** [comment]
>Whats the best was to update pyload to v4.9.20 whithout loosing any settings?
Can anyone please give some detailed instructions.

https://github.com/pyload/pyload/issues/3283

**Comment by GammaC0de** [comment]
Where is your working v0.5 fork?
