### ISSUE TITLE
websharecz cannot use premium account, real-debrid cannot login

### ISSUE THREAD

**Issue by muniv11111** [pyload/pyload#3525]
Hi,

after new installation and upgrade to 0.4.20, I get some errors:

22.02.2020 13:34:05 INFO      Starting pyLoad 0.4.20
22.02.2020 13:34:05 INFO      Using home directory: C:\Users\muniv\pyload
22.02.2020 13:34:06 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
22.02.2020 13:34:06 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
22.02.2020 13:34:06 INFO      Downloadtime: True
22.02.2020 13:34:06 INFO      Server set to threaded, due to known performance problems on windows.
22.02.2020 13:34:06 INFO      Free space: 402.72 GiB
22.02.2020 13:34:07 INFO      Starting threaded webserver: 0.0.0.0:8000
22.02.2020 13:34:07 INFO      Activating Accounts...
22.02.2020 13:34:07 INFO      ACCOUNT WebshareCz: Adding user `m_u*******`...
22.02.2020 13:34:07 INFO      ACCOUNT WebshareCz: Login user `m_u*******`...
22.02.2020 13:34:07 ERROR     ACCOUNT WebshareCz: Could not login user `m_u*******` | 'NoneType' object has no attribute 'group'
22.02.2020 13:34:07 INFO      Activating Plugins...
22.02.2020 13:34:08 INFO      ADDON UpdateManager: pyLoad is up to date!
22.02.2020 13:34:09 INFO      ADDON XFileSharing: Auto-discover new hosters
22.02.2020 13:34:09 INFO      ADDON XFileSharing: Auto-discover new crypters
22.02.2020 13:34:09 INFO      pyLoad is up and running
22.02.2020 13:34:09 INFO      ADDON UpdateManager: All plugins are up to date!
22.02.2020 13:34:15 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
22.02.2020 13:34:38 INFO      shutting down...
22.02.2020 13:34:38 INFO      ADDON ClickNLoad: Shutting down proxy...
22.02.2020 13:34:38 INFO      killed pyLoad from Terminal

c:\Users\muniv\.windows-build-tools\python27>python "c:\Users\muniv\Downloads\pyload\pyLoadCore.py"
22.02.2020 13:34:40 INFO      Starting pyLoad 0.4.20
22.02.2020 13:34:40 INFO      Using home directory: C:\Users\muniv\pyload
22.02.2020 13:34:41 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
22.02.2020 13:34:41 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
22.02.2020 13:34:41 INFO      Downloadtime: True
22.02.2020 13:34:41 INFO      Free space: 402.72 GiB
22.02.2020 13:34:41 INFO      Activating Accounts...
22.02.2020 13:34:42 INFO      Server set to threaded, due to known performance problems on windows.
22.02.2020 13:34:42 INFO      ACCOUNT WebshareCz: Adding user `m_u*******`...
22.02.2020 13:34:42 INFO      ACCOUNT WebshareCz: Login user `m_u*******`...
22.02.2020 13:34:42 INFO      Starting threaded webserver: 0.0.0.0:8000
22.02.2020 13:34:42 ERROR     ACCOUNT WebshareCz: Could not login user `m_u*******` | 'NoneType' object has no attribute 'group'
22.02.2020 13:34:42 INFO      Activating Plugins...
22.02.2020 13:34:42 INFO      ADDON UpdateManager: pyLoad is up to date!
22.02.2020 13:34:43 INFO      ADDON XFileSharing: Auto-discover new hosters
22.02.2020 13:34:43 INFO      ADDON XFileSharing: Auto-discover new crypters
22.02.2020 13:34:43 INFO      pyLoad is up and running
22.02.2020 13:34:43 INFO      ADDON UpdateManager: All plugins are up to date!
22.02.2020 13:34:49 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
22.02.2020 13:38:14 INFO      ACCOUNT WebshareCz: Updating account info for user `m_u*******`...
22.02.2020 13:38:14 INFO      ACCOUNT WebshareCz: Relogin user `m_u*******`...
22.02.2020 13:38:14 ERROR     ACCOUNT WebshareCz: Could not login user `m_u*******` | 'NoneType' object has no attribute 'group'
22.02.2020 13:38:14 INFO      ACCOUNT WebshareCz: Updating account info for user `m_u*******`...
22.02.2020 13:38:14 INFO      ACCOUNT WebshareCz: Relogin user `m_u*******`...
22.02.2020 13:38:14 ERROR     ACCOUNT WebshareCz: Could not login user `m_u*******` | 'NoneType' object has no attribute 'group'
22.02.2020 13:50:05 INFO      ACCOUNT RealdebridCom: Adding user `mun*******`...
22.02.2020 13:50:05 INFO      ACCOUNT RealdebridCom: Login user `mun*******`...
22.02.2020 13:50:05 ERROR     ACCOUNT RealdebridCom: Could not login user `mun*******` | Login handshake has failed
22.02.2020 13:50:08 ERROR     ACCOUNT RealdebridCom: Could not load hoster list - invalid account, retry in 5 minutes
22.02.2020 13:51:23 INFO      ACCOUNT UlozTo: Adding user `m_u*******`...
22.02.2020 13:51:23 INFO      ACCOUNT UlozTo: Login user `m_u*******`...
22.02.2020 13:51:26 INFO      ACCOUNT UlozTo: Grabbing account info for user `m_u*******`...
22.02.2020 13:53:11 INFO      Added package fsd containing 1 links
22.02.2020 13:53:12 INFO      Download starts: https://uloz.to/file/eW4r8ELE/sax-teminator-root-krabator-live-29-9-1989-avi
22.02.2020 13:53:12 WARNING   HOSTER UlozTo[1]: Plugin may be unstable
22.02.2020 13:53:12 INFO      ACCOUNT UlozTo: Grabbing account info for user `m_u*******`...
22.02.2020 13:53:12 INFO      HOSTER UlozTo[1]: Grabbing link info...
22.02.2020 13:53:12 INFO      HOSTER UlozTo[1]: Link name: sax,teminator,root,krabator_live_29.9.1989.avi
22.02.2020 13:53:12 INFO      HOSTER UlozTo[1]: Link size: N/D
22.02.2020 13:53:12 INFO      HOSTER UlozTo[1]: Link status: online
22.02.2020 13:53:12 INFO      HOSTER UlozTo[1]: Processing url: https://uloz.to/file/eW4r8ELE/sax-teminator-root-krabator-live-29-9-1989-avi
22.02.2020 13:53:12 INFO      HOSTER UlozTo[1]: Looking for direct download link...
22.02.2020 13:53:13 INFO      HOSTER UlozTo[1]: Direct download link not found
22.02.2020 13:53:13 INFO      HOSTER UlozTo[1]: Checking for link errors...
22.02.2020 13:53:13 INFO      HOSTER UlozTo[1]: No errors found
22.02.2020 13:53:13 INFO      HOSTER UlozTo[1]: Processing as free download...
22.02.2020 13:53:13 INFO      CAPTCHA UlozTo[1]: Captcha | Using OCR to decrypt captcha...
22.02.2020 13:53:13 WARNING   CAPTCHA UlozTo[1]: Captcha | No OCR result
22.02.2020 13:54:34 INFO      CAPTCHA UlozTo[1]: Captcha | Captcha result: `gKHG`
22.02.2020 13:54:34 INFO      CAPTCHA UlozTo[1]: Captcha | Path deleted: C:\Users\muniv\pyload\tmp\captcha_image_UlozTo_99365.jpg
Exception in thread Thread-58:
Traceback (most recent call last):
  File "c:\Users\muniv\.windows-build-tools\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\Users\muniv\Downloads\pyload\module\PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\hooks\ClickNLoad.py", line 85, in forward
    forward(source, destination)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\misc.py", line 940, in forward
    destination.sendall(bufdata)
  File "c:\Users\muniv\.windows-build-tools\python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10053] Software v hostitelskÚm poŔÝtaŔi ukonŔil vytvo°enÚ p°ipojen

22.02.2020 13:55:08 ERROR     ACCOUNT RealdebridCom: Could not load hoster list - invalid account, retry in 5 minutes
22.02.2020 13:56:01 INFO      CAPTCHA UlozTo[1]: Captcha | Correct captcha | gKHG
22.02.2020 13:56:01 INFO      Download aborted: sax,teminator,root,krabator_live_29.9.1989.avi
22.02.2020 13:56:56 INFO      Added package vcxvxc containing 1 links
22.02.2020 13:56:58 INFO      Download starts: https://webshare.cz/#/file/3N55dt4h56/terminator-temny-osud-mkv
22.02.2020 13:56:58 WARNING   HOSTER WebshareCz[2]: Plugin may be unstable
22.02.2020 13:56:58 INFO      HOSTER WebshareCz[2]: Grabbing link info...
22.02.2020 13:56:58 INFO      HOSTER WebshareCz[2]: Link name: Termin├ítor Temn├Ż osud.mkv
22.02.2020 13:56:58 INFO      HOSTER WebshareCz[2]: Link size: 1.66 GiB (1781393744 bytes)
22.02.2020 13:56:58 INFO      HOSTER WebshareCz[2]: Link status: online
22.02.2020 13:56:58 INFO      HOSTER WebshareCz[2]: Processing url: https://webshare.cz/#/file/3N55dt4h56/terminator-temny-osud-mkv
22.02.2020 13:56:58 INFO      HOSTER WebshareCz[2]: Looking for direct download link...
22.02.2020 13:56:58 INFO      HOSTER WebshareCz[2]: Direct download link not found
22.02.2020 13:56:58 INFO      HOSTER WebshareCz[2]: Checking for link errors...
22.02.2020 13:56:58 INFO      HOSTER WebshareCz[2]: No errors found
22.02.2020 13:56:58 INFO      HOSTER WebshareCz[2]: Processing as free download...
22.02.2020 13:56:58 INFO      HOSTER WebshareCz[2]: Downloading file...
22.02.2020 13:56:59 ERROR     Download chunks failed, fallback to single connection | Bad server response: 416 Requested Range Not Satisfiable
22.02.2020 13:58:16 INFO      ACCOUNT WebshareCz: Updating account info for user `m_univ`...
22.02.2020 13:58:16 INFO      ACCOUNT WebshareCz: Login user `None`...
22.02.2020 13:58:16 ERROR     ACCOUNT WebshareCz: Could not login user `None` | 'login'
Traceback (most recent call last):
  File "c:\Users\muniv\Downloads\pyload\module\lib\bottle.py", line 733, in _handle
    return route.call(**args)
  File "c:\Users\muniv\Downloads\pyload\module\lib\bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "c:\Users\muniv\Downloads\pyload\module\web\utils.py", line 112, in _view
    return func(*args, **kwargs)
  File "c:\Users\muniv\Downloads\pyload\module\web\json_app.py", line 298, in update_accounts
    PYLOAD.updateAccount(plugin, user, options={"limitDL": [value]})
  File "c:\Users\muniv\Downloads\pyload\module\Api.py", line 895, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "c:\Users\muniv\Downloads\pyload\module\utils.py", line 169, in new
    return func(*args)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\AccountManager.py", line 153, in updateAccount
    updated = p.updateAccounts(user, password, options)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\misc.py", line 228, in new
    return fn(*args, **kwargs)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\Account.py", line 333, in updateAccounts
    u['plugin'].relogin()
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\Account.py", line 177, in relogin
    return self.login()
KeyError: 'login'
An error occured while processing the request.
Traceback (most recent call last):
  File "c:\Users\muniv\Downloads\pyload\module\lib\bottle.py", line 733, in _handle
    return route.call(**args)
  File "c:\Users\muniv\Downloads\pyload\module\lib\bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "c:\Users\muniv\Downloads\pyload\module\web\utils.py", line 112, in _view
    return func(*args, **kwargs)
  File "c:\Users\muniv\Downloads\pyload\module\web\json_app.py", line 298, in update_accounts
    PYLOAD.updateAccount(plugin, user, options={"limitDL": [value]})
  File "c:\Users\muniv\Downloads\pyload\module\Api.py", line 895, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "c:\Users\muniv\Downloads\pyload\module\utils.py", line 169, in new
    return func(*args)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\AccountManager.py", line 153, in updateAccount
    updated = p.updateAccounts(user, password, options)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\misc.py", line 228, in new
    return fn(*args, **kwargs)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\Account.py", line 333, in updateAccounts
    u['plugin'].relogin()
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\Account.py", line 177, in relogin
    return self.login()
KeyError: 'login'

22.02.2020 13:59:36 INFO      ACCOUNT WebshareCz: Updating account info for user `m_univ`...
22.02.2020 13:59:36 INFO      ACCOUNT WebshareCz: Relogin user `None`...
22.02.2020 13:59:36 ERROR     ACCOUNT WebshareCz: Could not login user `None` | 'login'
Traceback (most recent call last):
  File "c:\Users\muniv\Downloads\pyload\module\lib\bottle.py", line 733, in _handle
    return route.call(**args)
  File "c:\Users\muniv\Downloads\pyload\module\lib\bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "c:\Users\muniv\Downloads\pyload\module\web\utils.py", line 112, in _view
    return func(*args, **kwargs)
  File "c:\Users\muniv\Downloads\pyload\module\web\json_app.py", line 298, in update_accounts
    PYLOAD.updateAccount(plugin, user, options={"limitDL": [value]})
  File "c:\Users\muniv\Downloads\pyload\module\Api.py", line 895, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "c:\Users\muniv\Downloads\pyload\module\utils.py", line 169, in new
    return func(*args)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\AccountManager.py", line 153, in updateAccount
    updated = p.updateAccounts(user, password, options)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\misc.py", line 228, in new
    return fn(*args, **kwargs)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\Account.py", line 333, in updateAccounts
    u['plugin'].relogin()
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\Account.py", line 177, in relogin
    return self.login()
KeyError: 'login'
An error occured while processing the request.
Traceback (most recent call last):
  File "c:\Users\muniv\Downloads\pyload\module\lib\bottle.py", line 733, in _handle
    return route.call(**args)
  File "c:\Users\muniv\Downloads\pyload\module\lib\bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "c:\Users\muniv\Downloads\pyload\module\web\utils.py", line 112, in _view
    return func(*args, **kwargs)
  File "c:\Users\muniv\Downloads\pyload\module\web\json_app.py", line 298, in update_accounts
    PYLOAD.updateAccount(plugin, user, options={"limitDL": [value]})
  File "c:\Users\muniv\Downloads\pyload\module\Api.py", line 895, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "c:\Users\muniv\Downloads\pyload\module\utils.py", line 169, in new
    return func(*args)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\AccountManager.py", line 153, in updateAccount
    updated = p.updateAccounts(user, password, options)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\misc.py", line 228, in new
    return fn(*args, **kwargs)
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\Account.py", line 333, in updateAccounts
    u['plugin'].relogin()
  File "c:\Users\muniv\Downloads\pyload\module\plugins\internal\Account.py", line 177, in relogin
    return self.login()
KeyError: 'login'

22.02.2020 14:00:08 ERROR     ACCOUNT RealdebridCom: Could not load hoster list - invalid account, deactivating
22.02.2020 14:00:08 INFO      ACCOUNT RealdebridCom: Reverting back to default hosters

**Comment by Mister-XY** [comment]
Have you use the apitoken instead of password in real debrid? You can find the apitoken here
https://real-debrid.com/apitoken

**Comment by muniv11111** [comment]
> Have you use the apitoken instead of password in real debrid? You can find the apitoken here
> https://real-debrid.com/apitoken

yes, I did...

**Comment by GammaC0de** [comment]
WebshareCz is not supported by real-debrid  (see `https://api.real-debrid.com/rest/1.0/hosts/status?auth_token=<API_TOKEN>`)

Do you have premium account for WebshareCz?

**Comment by muniv11111** [comment]
> WebshareCz is not supported by real-debrid (see `https://api.real-debrid.com/rest/1.0/hosts/status?auth_token=<API_TOKEN>`)
> 
> Do you have premium account for WebshareCz?

Yes I have,

websharecz premiun account, see: https://pasteboard.co/IW0B7fp.png

For real debrid I have no premium. I tried to this time webshare, real-debrid, and ulozto.. Only on last site login works in pyload.

This accoun for webshare is valid on these domains, if you could update plugin -

https://en.webshare.cz/#/

https://webshare.cz/#/

https://beta.wsfiles.com/

https://beta.webshare.cz/#/

Webshare is popular in our country also with this great movie and TV shows kodi plugin:

https://github.com/bbaronSVK/plugin.video.stream-cinema

Maybe you can look how this plugin works, I am not python coder... :-)


Today pyload start with this log, if you see something there... 

I could PM 

23.02.2020 13:00:05 INFO      Starting pyLoad 0.4.20
23.02.2020 13:00:05 INFO      Using home directory: C:\Users\muniv\pyload
23.02.2020 13:00:13 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
23.02.2020 13:00:13 INFO      Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
23.02.2020 13:00:13 INFO      Downloadtime: True
23.02.2020 13:00:15 INFO      Server set to threaded, due to known performance problems on windows.
23.02.2020 13:00:15 INFO      Free space: 401.53 GiB
23.02.2020 13:00:15 INFO      Starting threaded webserver: 0.0.0.0:8000
23.02.2020 13:00:15 INFO      Activating Accounts...
23.02.2020 13:00:15 INFO      ACCOUNT UlozTo: Adding user `m_u*******`...
23.02.2020 13:00:15 INFO      ACCOUNT UlozTo: Login user `m_u*******`...
23.02.2020 13:00:20 INFO      ACCOUNT UlozTo: Grabbing account info for user `m_u*******`...
23.02.2020 13:00:20 INFO      ACCOUNT WebshareCz: Adding user `m_u*******`...
23.02.2020 13:00:20 INFO      ACCOUNT WebshareCz: Login user `m_u*******`...
23.02.2020 13:00:20 ERROR     ACCOUNT WebshareCz: Could not login user `m_u*******` | 'NoneType' object has no attribute 'group'
23.02.2020 13:00:20 INFO      ACCOUNT RealdebridCom: Adding user `mun*******`...
23.02.2020 13:00:20 INFO      ACCOUNT RealdebridCom: Login user `mun*******`...
23.02.2020 13:00:21 ERROR     ACCOUNT RealdebridCom: Could not login user `mun*******` | Login handshake has failed
23.02.2020 13:00:21 INFO      Activating Plugins...
23.02.2020 13:00:21 INFO      ADDON UpdateManager: pyLoad is up to date!
23.02.2020 13:00:22 INFO      ADDON XFileSharing: Auto-discover new hosters
23.02.2020 13:00:22 INFO      ADDON XFileSharing: Auto-discover new crypters
23.02.2020 13:00:22 INFO      pyLoad is up and running
23.02.2020 13:00:22 INFO      ADDON UpdateManager: New version of plugin: CRYPTER CriptTo (v0.02 -> v0.03)
23.02.2020 13:00:23 INFO      ADDON UpdateManager: *** Plugins updated ***
23.02.2020 13:00:23 ERROR     ACCOUNT RealdebridCom: Could not load hoster list - invalid account, retry in 5 minutes
23.02.2020 13:00:24 ERROR     ACCOUNT RealdebridCom: Could not load hoster list - invalid account, retry in 5 minutes
23.02.2020 13:00:28 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
23.02.2020 13:05:24 ERROR     ACCOUNT RealdebridCom: Could not load hoster list - invalid account, deactivating
23.02.2020 13:05:24 INFO      ACCOUNT RealdebridCom: Reverting back to default hosters

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set your WebshareCz password  to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by muniv11111** [comment]
Account info sent. Thanks
