### ISSUE TITLE
error: getgrnam() name not found smbusr after clean install

### ISSUE THREAD

**Issue by MrQuestionnaire** [pyload/pyload#3526]
I've setted up my banana pi with Armbian_19.11.3_Bananapi_bionic_current_5.3.9
After main configuration (name, ipadress, timezone,console etc.) I tried to set up pyload
first of all I installed depenencies as named by C0demaster:

apt-get install python-pycurl
apt install python-pip
pip install setuptools
pip install wheel

to avoid compitibilty issues I installed:

python -m pip install --upgrade pycrypto, tesseract, nodejs, ffmpeg , rhino

without any problems

But trying to install rhino ended up with errors. I found out that depenencies for rhino are missing, so installed them in my OS:

apt install python-dev libjpeg-dev zlib1g-dev

After this a

python -m pip install --upgrade rhino

succeeded.

On this point I thought everything should be in place, so I did:

cd /opt
git clone https://github.com/pyload/pyload.git
cd pyload
git checkout stable
python ./pyLoadCore.py -s

So, the output wasn't that, what I expected. JS (rhino) and tesseract where missing.
--------
Verfügbare Funktionen: Container decrypting, Webinterface

Fehlende Funktionen:

** no SSL available **
Wird gebraucht falls du eine SSL Verbindung zu Core oder Webinterface einstellen willst.
Falls du nur lokal zugreifen willst, ist SSL überflüssig.

** no Captcha OCR Recognition available **
Wird für einige Hoster als Freeuser benötigt.

** Gui not available **
Die Grafische Benutzer Oberfläche.

** no JavaScript engine found **
Du benötigst das für einige Click'n'Load links. Installiere Spidermonkey, ossp-js, pyv8 oder rhino
--------
I stopped the pylaod configuration and checked on console:

pip list

Output:
-------
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package         Version
--------------- --------
dnspython       1.15.0
ffmpeg          1.4
nodejs          0.1.1
optional-django 0.1.0
Pillow          6.2.2
pip             20.0.2
pycrypto        2.6.1
pycurl          7.43.0.1
Rhino           0.0.5
setuptools      44.0.0
tesseract       0.1.3
wheel           0.34.2
---------

I decided to install rhino and tesseract-ocr in the OS:

apt install rhino tesseract-ocr

Now again:

python ./pyLoadCore.py -s

Output:
-------
## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: fehlt

py-imaging: OK
tesseract: OK

PyQt4: fehlt

jinja2: OK
beaker: OK
JS engine: OK

System-Check beendet, drücke Enter um deinen Status Bericht zu sehen.

## Status ##

Verfügbare Funktionen: Container decrypting, Automatisches Captcha einlesen, Webinterface, erweitertes Click'N'Load

Fehlende Funktionen:

** no SSL available **
Wird gebraucht falls du eine SSL Verbindung zu Core oder Webinterface einstellen willst.
Falls du nur lokal zugreifen willst, ist SSL überflüssig.

** Gui not available **
Die Grafische Benutzer Oberfläche.
---------

That's what I wanted.
After starting pyload

python ./pyLoadCore.py --daemon

connecting via browser from a client pc. Downloading starts but ends up with an error I never seen before:

getgrnam() name not found smbusr

Tested on hosters: zippyshare(native), Rapidgator & uploaded.to via debriditalia pluging = same error

So I think I made a big mistake installing a wrong package somewhere OR there is a bug in support of python2.7 somewhere.

**Comment by GammaC0de** [comment]
Is this a new installation or you had pyload already installed in the past?

**Comment by GammaC0de** [comment]
Try running pyload without daemon and see if it works

`python ./pyLoadCore.py -d`

**Comment by MrQuestionnaire** [comment]
Issue was caused by my mistake. Of course I installed the complete OS and pyload new (on SDCard), but to be honnest, I used the old configuartion directory with was placed on HDD, without deleting its old content. 
GammaC0des comments helped me to find where I did the mistake.
Sorry for the disturbance. 
Issue closed
