### ISSUE TITLE
RealDebrid - Bad server response: 503 Service Unavailable

### ISSUE THREAD

**Issue by c0cee** [pyload/pyload#3528]
### Describe the problem

I did a fresh installation of pyLoad. Added my RealDebrid account which shows valid and premium is activated.
Im trying to download from Oboom, which is in the Hoster List of RealDebrid, but unfortunately I always get the error "Bad server response: 503 Service Unavailabl". 
Also I activated the CloudflareDDoS plugin.

Maybe someone can help me.

### Debug log

23.02.2020 09:22:57 INFO      starte pyLoad 0.4.20
23.02.2020 09:22:57 INFO      Benutze Home-Verzeichnis: /media/1f4d/cocee/.pyload
23.02.2020 09:22:57 DEBUG     Remote activated: False
23.02.2020 09:22:58 DEBUG     created index of plugins
23.02.2020 09:22:58 INFO      Aktivierte Plugins: ClickNLoad, CloudFlareDdos, EventMapper, ExternalScripts, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
23.02.2020 09:22:58 INFO      Deaktivierte Plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
23.02.2020 09:22:58 INFO      Downloadzeit: True
23.02.2020 09:22:58 INFO      Starting builtin webserver: 0.0.0.0:23083
23.02.2020 09:22:58 INFO      Free space: 3.41 TiB
23.02.2020 09:22:58 INFO      Activating Accounts...
23.02.2020 09:22:58 INFO      ACCOUNT RealdebridCom: Adding user `LWM*******`...
23.02.2020 09:22:58 DEBUG     ACCOUNT RealdebridCom: Reached login timeout for user `LWM*******`
23.02.2020 09:22:58 INFO      ACCOUNT RealdebridCom: Login user `LWM*******`...
23.02.2020 09:22:58 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/user | redirect=True | cookies=True | get={'auth_token': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
23.02.2020 09:22:58 INFO      ACCOUNT RealdebridCom: Grabbing account info for user `LWM*******`...
23.02.2020 09:22:58 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/user | redirect=True | cookies=True | get={'auth_token': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
23.02.2020 09:22:58 DEBUG     ACCOUNT RealdebridCom: Account info for user `LWM*******`: {'login': {'timestamp': 1582449778.578645, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account RealdebridCom>, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1590074984.694418, 'login': 'LWM*******', 'type': 'RealdebridCom', 'options': {'limitDL': ['0']}}}
23.02.2020 09:22:58 INFO      Activating Plugins...
23.02.2020 09:22:58 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_start`
23.02.2020 09:22:58 DEBUG     ADDON CloudFlareDdos: Overriding get_url()
23.02.2020 09:22:58 INFO      ADDON XFileSharing: Auto-discover new hosters
23.02.2020 09:22:58 DEBUG     ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|clicknupload\.org|cramit\.in|ddl\.to|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|fistfast\.net|hugefiles\.net|junocloud\.me|katfile\.com|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|suprafiles\.me|tusfiles\.net|uploadrocket\.net|vidplay\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
23.02.2020 09:22:58 DEBUG     Redirected import module.plugins.crypter.CriptTo -> userplugins.crypter.CriptTo
23.02.2020 09:22:58 DEBUG     Redirected import userplugins.captcha.ReCaptcha -> module.plugins.captcha.ReCaptcha
23.02.2020 09:22:58 DEBUG     Redirected import userplugins.captcha.SolveMedia -> module.plugins.captcha.SolveMedia
23.02.2020 09:22:58 DEBUG     Redirected import userplugins.container.DLC -> module.plugins.container.DLC
23.02.2020 09:22:58 DEBUG     Redirected import userplugins.internal.misc -> module.plugins.internal.misc
23.02.2020 09:22:58 DEBUG     Redirected import userplugins.internal.SimpleCrypter -> module.plugins.internal.SimpleCrypter
23.02.2020 09:22:58 INFO      ADDON XFileSharing: Auto-discover new crypters
23.02.2020 09:22:58 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
23.02.2020 09:22:58 INFO      pyLoad is up and running
23.02.2020 09:22:58 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/updates/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.20'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
23.02.2020 09:22:58 INFO      ADDON UpdateManager: pyLoad is up to date!
23.02.2020 09:22:58 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/updates/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.20'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
23.02.2020 09:22:58 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'FreeWayMe'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'ShareonlineBiz'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'ShareonlineBiz'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaBrotherhood'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'Libgen'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'RealdebridComTorrent'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
23.02.2020 09:22:58 INFO      ADDON UpdateManager: All plugins are up to date!
23.02.2020 09:23:00 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/hosts/status | redirect=True | cookies=True | get={'auth_token': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
23.02.2020 09:23:00 DEBUG     ACCOUNT RealdebridCom: Hoster list for user `LWM*******`: [u'clicknupload.me', u'dailymotion.com', u'datafilehost.com', u'ddl.to', u'depositfiles.com', u'filefactory.com', u'filerio.com', u'flashx.tv', u'fourshared.com', u'free.fr', u'gigapeta.com', u'google.com', u'hitfile.net', u'hulkshare.com', u'inclouddrive.com', u'isra.cloud', u'mediafire.com', u'mega.co.nz', u'mixdrop.co', u'oboom.com', u'onefichier.com', u'rapidgator.net', u'redtube.com', u'rutube.ru', u'scribd.com', u'sendspace.com', u'sky.fm', u'solidfiles.com', u'soundcloud.com', u'turbobit.net', u'tusfiles.com', u'ulozto.net', u'unibytes.com', u'uploaded.to', u'userscloud.com', u'vidlox.tv', u'vidoza.net', u'vimeo.com', u'wupfile.com', u'youporn.com', u'youtube.com', u'zippyshare.com']
23.02.2020 09:23:00 DEBUG     ACCOUNT RealdebridCom: Overwritten hosters: DailymotionCom, DdlTo, DepositfilesCom, FilefactoryCom, FilerioCom, FourSharedCom, GigapetaCom, HitfileNet, MediafireCom, MegaCoNz, OboomCom, OneFichierCom, RapidgatorNet, RedtubeCom, SendspaceCom, SolidfilesCom, SoundcloudCom, TurbobitNet, UnibytesCom, UploadedTo, UserscloudCom, VimeoCom, YoupornCom, YoutubeCom, ZippyshareCom
23.02.2020 09:23:00 DEBUG     ACCOUNT RealdebridCom: New hosters: clicknupload.me, datafilehost.com, flashx.tv, free.fr, google.com, hulkshare.com, inclouddrive.com, isra.cloud, mixdrop.co, rutube.ru, scribd.com, sky.fm, tusfiles.com, ulozto.net, vidlox.tv, vidoza.net, wupfile.com
23.02.2020 09:23:00 DEBUG     ACCOUNT RealdebridCom: Pattern: https?://((?:www\.|s\d+\.)?real-debrid\.com/dl?/|[\w^_]\.rdb\.so/d/)[\w^_]+|.*(?P<DOMAIN>clicknupload\.me|datafilehost\.com|flashx\.tv|free\.fr|google\.com|hulkshare\.com|inclouddrive\.com|isra\.cloud|mixdrop\.co|rutube\.ru|scribd\.com|sky\.fm|tusfiles\.com|ulozto\.net|vidlox\.tv|vidoza\.net|wupfile\.com).*
23.02.2020 09:23:04 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
23.02.2020 09:23:17 INFO      Added package Test containing 1 links
23.02.2020 09:23:26 INFO      Download starts: https://www.oboom.com/M5OTDYD4
23.02.2020 09:23:26 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
23.02.2020 09:23:26 DEBUG     ADDON CloudFlareDdos: Overriding _preload() for <HOSTER RealdebridCom[1]>
23.02.2020 09:23:26 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
23.02.2020 09:23:26 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
23.02.2020 09:23:26 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
23.02.2020 09:23:26 DEBUG     HOSTER RealdebridCom[1]: RealdebridCom | Plugin version: 0.79
23.02.2020 09:23:26 DEBUG     HOSTER RealdebridCom[1]: RealdebridCom | Plugin status: testing
23.02.2020 09:23:26 WARNING   HOSTER RealdebridCom[1]: RealdebridCom | Plugin may be unstable
23.02.2020 09:23:26 INFO      ACCOUNT RealdebridCom: Grabbing account info for user `LWM*******`...
23.02.2020 09:23:26 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/user | redirect=True | cookies=True | get={'auth_token': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
23.02.2020 09:23:27 DEBUG     ACCOUNT RealdebridCom: Account info for user `LWM*******`: {'login': {'timestamp': 1582449778.578645, 'password': '**********', 'valid': True}, 'data': {'hosters': [u'clicknupload.me', u'dailymotion.com', u'datafilehost.com', u'ddl.to', u'depositfiles.com', u'filefactory.com', u'filerio.com', u'flashx.tv', u'fourshared.com', u'free.fr', u'gigapeta.com', u'google.com', u'hitfile.net', u'hulkshare.com', u'inclouddrive.com', u'isra.cloud', u'mediafire.com', u'mega.co.nz', u'mixdrop.co', u'oboom.com', u'onefichier.com', u'rapidgator.net', u'redtube.com', u'rutube.ru', u'scribd.com', u'sendspace.com', u'sky.fm', u'solidfiles.com', u'soundcloud.com', u'turbobit.net', u'tusfiles.com', u'ulozto.net', u'unibytes.com', u'uploaded.to', u'userscloud.com', u'vidlox.tv', u'vidoza.net', u'vimeo.com', u'wupfile.com', u'youporn.com', u'youtube.com', u'zippyshare.com'], 'premium': True, 'plugin': <Account RealdebridCom>, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1590074984.018129, 'login': 'LWM*******', 'type': 'RealdebridCom', 'options': {'limitDL': ['0']}}}
23.02.2020 09:23:27 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Grabbing link info...
23.02.2020 09:23:27 DEBUG     ADDON CloudFlareDdos: Calling get_url() of <HOSTER RealdebridCom[1]>
23.02.2020 09:23:27 DEBUG     HOSTER RealdebridCom[1]: RealdebridCom | LOAD URL https://www.oboom.com/M5OTDYD4 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
23.02.2020 09:23:30 DEBUG     ADDON CloudFlareDdos: get_url() returned successfully
23.02.2020 09:23:30 DEBUG     HOSTER RealdebridCom[1]: RealdebridCom | Link info: {'status': 7, 'hash': {}, 'name': u'M5OTDYD4', 'url': u'https://www.oboom.com/M5OTDYD4', 'pattern': {}, 'size': 0}
23.02.2020 09:23:30 DEBUG     HOSTER RealdebridCom[1]: RealdebridCom | Previous link info: {}
23.02.2020 09:23:30 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link name: M5OTDYD4
23.02.2020 09:23:30 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link size: N/D
23.02.2020 09:23:30 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link status: starte
23.02.2020 09:23:30 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Processing url: https://www.oboom.com/M5OTDYD4
23.02.2020 09:23:30 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Looking for direct download link...
23.02.2020 09:23:30 DEBUG     HOSTER RealdebridCom[1]: RealdebridCom | LOAD URL https://www.oboom.com/M5OTDYD4 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
23.02.2020 09:23:31 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Direct download link not found
23.02.2020 09:23:31 DEBUG     ADDON CloudFlareDdos: Calling _preload() of <HOSTER RealdebridCom[1]>
23.02.2020 09:23:31 DEBUG     HOSTER RealdebridCom[1]: RealdebridCom | LOAD URL https://www.oboom.com/M5OTDYD4 | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
23.02.2020 09:23:31 DEBUG     ADDON CloudFlareDdos: _preload() returned successfully
23.02.2020 09:23:31 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Checking for link errors...
23.02.2020 09:23:31 INFO      HOSTER RealdebridCom[1]: RealdebridCom | No errors found
23.02.2020 09:23:31 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Grabbing link info...
23.02.2020 09:23:31 DEBUG     HOSTER RealdebridCom[1]: RealdebridCom | Link info: {'status': 7, 'hash': {}, 'name': u'M5OTDYD4', 'url': u'https://www.oboom.com/M5OTDYD4', 'pattern': {}, 'size': 0}
23.02.2020 09:23:31 DEBUG     HOSTER RealdebridCom[1]: RealdebridCom | Previous link info: {'status': 7, 'hash': {}, 'name': u'M5OTDYD4', 'url': u'https://www.oboom.com/M5OTDYD4', 'pattern': {}, 'size': 0}
23.02.2020 09:23:31 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link name: M5OTDYD4
23.02.2020 09:23:31 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link size: N/D
23.02.2020 09:23:31 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Link status: starte
23.02.2020 09:23:31 INFO      HOSTER RealdebridCom[1]: RealdebridCom | Processing as premium download...
23.02.2020 09:23:31 DEBUG     HOSTER RealdebridCom[1]: RealdebridCom | LOAD URL https://api.real-debrid.com/rest/1.0/unrestrict/link | redirect=True | cookies=True | get={'auth_token': '**********'} | req=None | decode=True | multipart=False | post={'password': '', 'link': u'https://www.oboom.com/M5OTDYD4'} | ref=True | just_header=False
23.02.2020 09:23:31 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
23.02.2020 09:23:31 DEBUG     ADDON CloudFlareDdos: Unoverriding _preload() for <HOSTER RealdebridCom[1]>
23.02.2020 09:23:31 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
23.02.2020 09:23:31 WARNING   Download failed: M5OTDYD4 | Bad server response: 503 Service Unavailable
Traceback (most recent call last):
  File "/media/1f4d/cocee/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/media/1f4d/cocee/share/pyload/module/plugins/internal/Base.py", line 294, in preprocessing
    return self._process(*args, **kwargs)
  File "/media/1f4d/cocee/share/pyload/module/plugins/internal/MultiHoster.py", line 64, in _process
    SimpleHoster._process(self, thread)
  File "/media/1f4d/cocee/share/pyload/module/plugins/internal/Hoster.py", line 118, in _process
    self.process(self.pyfile)
  File "/media/1f4d/cocee/share/pyload/module/plugins/internal/SimpleHoster.py", line 278, in process
    self.handle_premium(pyfile)
  File "/media/1f4d/cocee/share/pyload/module/plugins/hoster/RealdebridCom.py", line 46, in handle_premium
    args(link=pyfile.url, password=self.get_password()))
  File "/media/1f4d/cocee/share/pyload/module/plugins/hoster/RealdebridCom.py", line 33, in api_response
    json_data = self.load(self.API_URL + namespace, get=get, post=post)
  File "/media/1f4d/cocee/share/pyload/module/plugins/internal/Base.py", line 493, in load
    return Plugin.load(self, *args, **kwargs)
  File "/media/1f4d/cocee/share/pyload/module/plugins/internal/Plugin.py", line 215, in load
    decode is True)  # @TODO: Fix network multipart in 0.4.10
  File "/media/1f4d/cocee/share/pyload/module/network/Browser.py", line 98, in load
    return self.http.load(*args, **kwargs)
  File "/media/1f4d/cocee/share/pyload/module/network/HTTPRequest.py", line 232, in load
    self.code = self.verifyHeader()
  File "/media/1f4d/cocee/share/pyload/module/network/HTTPRequest.py", line 248, in verifyHeader
    raise BadHeader(code, self.header, self.getResponse())
BadHeader: Bad server response: 503 Service Unavailable
23.02.2020 09:23:31 INFO      Debug Report written to debug_OboomCom_23-02-2020_09-23-31.zip
23.02.2020 09:23:31 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
23.02.2020 09:23:31 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: M5OTDYD4 (pid:1)
23.02.2020 09:23:31 INFO      ADDON UnSkipOnFail: No duplicates found
23.02.2020 09:23:31 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
23.02.2020 09:23:31 DEBUG     All downloads processed
^C23.02.2020 09:25:26 INFO      shutting down...
23.02.2020 09:25:26 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_stop`
23.02.2020 09:25:26 INFO      ADDON ClickNLoad: Shutting down proxy...
23.02.2020 09:25:26 DEBUG     ADDON ClickNLoad: Server exited successfully
23.02.2020 09:25:26 DEBUG     ADDON CloudFlareDdos: Unoverriding get_url()
23.02.2020 09:25:26 DEBUG     Deleting old pidfile pyload.pid
23.02.2020 09:25:26 INFO      killed pyLoad from Terminal

**Comment by GammaC0de** [comment]
Does this happen only with Oboom?

**Comment by c0cee** [comment]
No, tested it also with RapidgatorNet a few hours ago.

**Comment by GammaC0de** [comment]
Maybe your IP is banned, are you using proxy?

**Comment by c0cee** [comment]
I use a seedbox. Maybe they blocked the Ip of it.

**Comment by GammaC0de** [comment]
Seems like it.

You could try updating pyload using the instructions in https://github.com/pyload/pyload/issues/3283, maybe it would help.

Also you can try it on your computer so you will be sure.

**Comment by c0cee** [comment]
I tried to update it. Still not working.
Think its because of the blocked Ip.

Nevertheless many thanks!

**Comment by GammaC0de** [comment]
:+1:
