### ISSUE TITLE
DDL.TO - Bad Server Response: 400 Bad Request

### ISSUE THREAD

**Issue by PiperNigrum** [pyload/pyload#3535]
Hi,

pyload is not able to download files from ddl.to.
I've updated pyload to the latest version 0.4.20.
The connection will established through a proxy.

I've tested the same URL with jDownloader which uses the same proxy server. 
There are no errors and I'm able to download the file.

Are there any problems with the plugin?

Thanks for any help :-)

27.02.2020 19:12:56 | INFO | Download starts: ict10ger1080hdc.part01.rar
-- | -- | --
27.02.2020 19:12:56 | WARNING | HOSTER DdlTo[53]: Plugin may be unstable
27.02.2020 19:12:56 | INFO | HOSTER DdlTo[53]: Grabbing link info...
27.02.2020 19:12:59 | INFO | HOSTER DdlTo[53]: Link name: ict10ger1080hdc.part01.rar
27.02.2020 19:12:59 | INFO | HOSTER DdlTo[53]: Link size: 950.00 MiB (996147200 bytes)
27.02.2020 19:12:59 | INFO | HOSTER DdlTo[53]: Link status: online
27.02.2020 19:12:59 | INFO | HOSTER DdlTo[53]: Processing url: https://ddl.to/0pjwy0sxkyi5
27.02.2020 19:13:01 | INFO | HOSTER DdlTo[53]: Checking for link errors...
27.02.2020 19:13:01 | INFO | HOSTER DdlTo[53]: No errors found
27.02.2020 19:13:01 | INFO | HOSTER DdlTo[53]: Processing as free download...
27.02.2020 19:13:01 | INFO | HOSTER DdlTo[53]: Checking for link errors...
27.02.2020 19:13:01 | INFO | HOSTER DdlTo[53]: No errors found
27.02.2020 19:13:01 | WARNING | CAPTCHA DdlTo[53]: ReCaptcha \| Secure Token pattern not found
27.02.2020 19:13:01 | WARNING | CAPTCHA DdlTo[53]: ReCaptcha \| Secure Token pattern not found
27.02.2020 19:13:02 | WARNING | Download failed: ict10ger1080hdc.part01.rar \| Bad server response: 400 Bad Request

**Comment by treysis** [comment]
No problem here on my end. What are you using to solve captchas?

**Comment by PiperNigrum** [comment]
I'm using the tampermonkey add-on to solve any capture.
I've temporarily deactivated the proxy and tried it again.
It works. 
Thats why I've tried the same URL with jDownloader an the same proxy.
As I described above there are no errors.
So I don't believe that the proxy would be the problem.

**Comment by treysis** [comment]
Oh, yes, I overlooked the proxy part.

**Comment by PiperNigrum** [comment]
yes, but i do not think that the used proxy might be the problem.
I've tried some other things e. g. open the URL at a browser using the proxy.
No problem :/

Only at pyload I get this error message.
Also by trying an URL from other hoster like uploaded.to

Maybe a general problem with the usage of proxies?

**Comment by PiperNigrum** [comment]
Is it possible that someone of the experts can take a look on my Problem?
btw....
I‘m not able to change the Label or something else.

Thanks :)

**Comment by treysis** [comment]
What kind of proxy is it? Is it maybe using "https" instead of "http"?

**Comment by GammaC0de** [comment]
You are using non standard setup and so it cannot be tested..

Can you share your proxy information?
If so, please send to nitzo2001 at yahoo dot com.

**Comment by PiperNigrum** [comment]
@treysis 
I‘m using a private proxy called privoxy on a raspberry pi 2 Model b.
privoxy will be used for both http and https connections through tor network. 
Pyload and Proxy are in the same network and connected using the local IP.

it works very well. but as described above it doesn‘t work with pyload.


@GammaC0de 
what du you mean by non standard setup?
I'm not sure if it helpfull for you but I've send you the configuration file of my proxy server.
Subject is PiperNigrum: Proxy

Thanks to both of you! :)

Greetings
PiperNigrum

**Comment by PiperNigrum** [comment]
Hello,

I hope everyone's okay?

Anything new on this problem yet?  It's really annoying not being able to download files.

**Comment by GammaC0de** [comment]
> I hope everyone's okay?

I hope so too..

> Anything new on this problem yet?

Sorry, not yet.
These crazy days and new pyLoad version produces lots of bug reports and feature requests.
I hope I can check this soon.

**Comment by Tockra** [comment]
Just for your interest: ddl.to is now ddownload.com

**Comment by mezzo86** [comment]
Anything new here? I have the same setup (pyload + 9kw) behind a VPN. As soon as the VPN is turned on, the captcha solving fails. Without the VPN everything works just fine.

Would appreciate an update. Thanks

**Comment by GammaC0de** [comment]
@PiperNigrum Can you please enable debug mode and send new logs?

**Comment by GammaC0de** [comment]
Fixed,  finally.
