### ISSUE TITLE
BasePlugin fails on zero-filled files (minor issue)

### ISSUE THREAD

**Issue by treysis** [pyload/pyload#3536]
### Describe the problem

When downloading a file that consists only of zeros, BasePlugin thinks something went wrong in the download and deletes the file.

E.g. https://speed.hetzner.de/100MB.bin

I consider this a minor issue, as empty files will be a rare case. However, I believe this could lead to a situation where pyLoad constantly tries to redownload the file, trying to get a proper version? Or if downloading a series of partition images, maybe one partition image could be zero-filled and thus also fail to download.

### Debug log

```
19:48:21 INFO      HOSTER BasePlugin[1424]: File saved
19:48:21 INFO      HOSTER BasePlugin[1424]: Checking download...
19:48:22 INFO      HOSTER BasePlugin[1424]: Path deleted: D:\pyload\data\Downloads\hetzner-1gb\1GB.bin
19:48:22 WARNING   HOSTER BasePlugin[1424]: Free download failed | Parse error: Empty file | Plugin may be out of date
19:48:22 DEBUG     HOSTER BasePlugin[1424]: Config option `fallback` not found, use default `True`
```

**Comment by GammaC0de** [comment]
This is by design.

**Comment by treysis** [comment]
I understand that this is by design, but there could be situations where this causes an unintentional error. At least it should be configurable not to delete zero-filled files.
