### ISSUE TITLE
Can't log out on Feb 29th

### ISSUE THREAD

**Issue by treysis** [pyload/pyload#3538]
### Describe the problem

Logging out from the webinterface on February 29th doesn't work. It shows "An Error occured, please enable debug mode to get more details. HTTP Response 500" and the user stays logged in.

### Debug log

```
Traceback (most recent call last):
File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/usr/share/pyload/module/web/pyload_app.py", line 235, in logout
s.delete()
File "/usr/share/pyload/module/lib/beaker/session.py", line 594, in delete
self._session().delete()
File "/usr/share/pyload/module/lib/beaker/session.py", line 196, in delete
self._delete_cookie()
File "/usr/share/pyload/module/lib/beaker/session.py", line 186, in _delete_cookie
expires = datetime.today().replace(year=2003)
ValueError: day is out of range for month
```

### Additional references

As it turns out, 2003 isn't a leap year. So February in 2003 doesn't have 29 days, thus "day is out of range for month". Simplest solution seems to be to replace `expires = datetime.today().replace(year=2003)` with `expires = datetime.today().replace(year=2004)` in line 186 `pyload/module/lib/beaker/session.py`, since 2004 was a leap year. I tried this and it works.

Of course, this bug will only occur today and every next 4 years for one day 😉

EDIT: More elegant solution is probably to use a relative date. E.g. the following line fixes it as well, even if you would reset your system clock to <=2004:
`expires = datetime.today() - timedelta(days=1)`

**Comment by akfedux** [comment]
> 
> ### Describe the problem
> 
> Logging out from the webinterface on February 29th doesn't work. It shows "An Error occured, please enable debug mode to get more details. HTTP Response 500" and the user stays logged in.
> ### Debug log
> 
> ```
> Traceback (most recent call last):
> File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
> return route.call(**args)
> File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
> rv = callback(*a, **ka)
> File "/usr/share/pyload/module/web/pyload_app.py", line 235, in logout
> s.delete()
> File "/usr/share/pyload/module/lib/beaker/session.py", line 594, in delete
> self._session().delete()
> File "/usr/share/pyload/module/lib/beaker/session.py", line 196, in delete
> self._delete_cookie()
> File "/usr/share/pyload/module/lib/beaker/session.py", line 186, in _delete_cookie
> expires = datetime.today().replace(year=2003)
> ValueError: day is out of range for month
> ```
> 
> ### Additional references
> 
> As it turns out, 2003 isn't a leap year. So February in 2003 doesn't have 29 days, thus "day is out of range for month". Simplest solution seems to be to replace `expires = datetime.today().replace(year=2003)` with `expires = datetime.today().replace(year=2004)` in line 186 `pyload/module/lib/beaker/session.py`, since 2004 was a leap year. I tried this and it works.
> 
> Of course, this bug will only occur today and every next 4 years for one day 😉
> 
> EDIT: More elegant solution is probably to use a relative date. E.g. the following line fixes it as well, even if you would reset your system clock to <=2004:
> `expires = datetime.today() - timedelta(days=1)`

Which version of the python do you have?
I can log out without this patch today.
I use this version: Python: 2.7.3

**Comment by treysis** [comment]
@akfedux I am using Python 2.7.17. Maybe your pyload updated automatically to include the new patch? Is your server and client both on date Feb 29?

**Comment by akfedux** [comment]
There has not been an update yet.
serwer: Sat Feb 29 15:16:29 CET 2020
client: Sat Feb 29 15:15:29 CET 2020

**Comment by treysis** [comment]
No idea then. At least with the latest Python 2.7.17 it's a bug.

**Comment by GammaC0de** [comment]
@akfedux
 You have to manually  update your pyLoad installation using the instruction in #3283,
UpdateManager cannot update the pyLoad's core where this bug resides.
