### ISSUE TITLE
TurbobitNet ->C'n'L -> BasePlugin

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#3539]
### Describe the problem

Running on the last 0.4.20 with TurbobitNet version 0.35, Tubobit.net links were handled with/as BasePlugin when links were added via ClickNload.
Adding the links to JD, export them as DLC and import in Plyoad leads to correctly handled and recognized packages.

### Debug log

The log don't show anything interresting corresponding this issue.
Only C'n'L connection and adding the package afterwards.

FileCryptContainer:  https://filecrypt.cc/Container/C898158066.html?mirror=0

**Comment by GammaC0de** [comment]
This file it offline,
Updated offline detection.

**Comment by UserX404** [comment]
No, it isn't offline. I forgot CryperPW: serienjunkies.org

**Comment by GammaC0de** [comment]
https://filecrypt.cc/Container/C898158066.html?mirror=0 == 404

**Comment by Mister-XY** [comment]
Have you dactivated xfilesharing? If i have it enabled, turobinit files where catched via xfilesharingfiles instead of turbobit

**Comment by UserX404** [comment]
For me the link still is reachable. Maybe your provider is blocking the dns request.

Give it a try with alternative DNS:176.103.130.130 or
176.103.130.131
(don't forget to clear Browser/Dns cache)

XFileShareing is deactivated.

**Comment by GammaC0de** [comment]
>Give it a try with alternative DNS:176.103.130.130 or
176.103.130.131

Not working either:
![Capture](https://user-images.githubusercontent.com/11036551/75611200-16a23900-5b21-11ea-8998-810eb7d394bc.PNG)

Do you have another URL?

**Comment by UserX404** [comment]
I tried with 3 different links but those worked without problems.
I encountered this problems more than once the past days but am not able to send you an other link at the moment.
Issue could be closed and i will append if i run into this in future.

**Comment by GammaC0de** [comment]
:+1:

**Comment by UserX404** [comment]
@GammaC0de 
Today i encoungered same bahavior with turbobit
https://filecrypt.cc/Container/E7EF814D47.html?mirror=1

**Comment by UserX404** [comment]
Thank you!
Tested and satisfied. :grin:
