### ISSUE TITLE
Downloading of larger files from web interface crashes pyLoad due to out of memory

### ISSUE THREAD

**Issue by treysis** [pyload/pyload#3541]
### Describe the problem

When going to the Downloads-tab in the web interface with the web browser to retrieve larger files that finished downloading, pyLoad is trying gzip the file (as is requested in the headers with "Accept-Encoding" by default from most web browsers, e.g. Chrome/Opera/Edge, same if you force gzip-compression with wget). If files are big enough, they will cause pyLoad or at the least the gzipping to crash due to being out of memory. It doesn't crash and download fine if you force the browser not to use gzip-compression.

Problem exists both when running builtin or threaded web server. On Linux, the whole pyLoad crashes, no error message displayed. When running pyLoad on Windows, browser shows the debug log.

### Debug log

Error in web interface (nothing appearing in console log):
```
Traceback (most recent call last):
  File "D:\pyload-0420\pyload\dist\module\lib\wsgiserver\__init__.py", line 1174, in communicate
  File "D:\pyload-0420\pyload\dist\module\lib\wsgiserver\__init__.py", line 544, in respond
  File "D:\pyload-0420\pyload\dist\module\lib\wsgiserver\__init__.py", line 556, in _respond
  File "D:\pyload-0420\pyload\dist\.\module\web\middlewares.py", line 55, in __call__
  File "D:\pyload-0420\pyload\dist\.\module\web\middlewares.py", line 121, in finish_response
  File "gzip.pyc", line 240, in write
MemoryError: out of memory
```

### Additional references

PyLoad 0.4.20. Python 2.7.17, both Linux (Ubuntu) and Windows are affected.

**Comment by GammaC0de** [comment]
Hi, Do you have sample URL that produces this error?

**Comment by treysis** [comment]
Any file that is big enough, e.g. https://ftp.fau.de/ubuntu-releases/eoan/ubuntu-19.10-desktop-amd64.iso (download it with pyLoad, then try to download it from pyLoad's webif).

I have already figured out that the problem is the middleware. If requested by the browser, it tries to gzip the file completely in memory before handing it to the actual webserver (cherrypy). It actually does that for any file, including html. But big files means it will eat up memory on the host until it crashes. The solution is probably to just eliminate the middleware (it's arguable whether pyLoad is really needing it to save bandwidth, maybe in heavy multi-user environments?). Alternatively, use a newer middleware (the one shipped with pyLoad seems to be from 2004) that is prepared to handle large files (unfortunately, I haven't found any lightweight middleware. Not saying there isn't one!).

**Comment by GammaC0de** [comment]
Well, Having 32GB ram, I have no issues to download https://ftp.fau.de/ubuntu-releases/eoan/ubuntu-19.10-desktop-amd64.iso  :muscle:  :sweat_smile:

What happens if you change [middlewares.py#L95](https://github.com/pyload/pyload/blob/stable/module/web/middlewares.py#L95)
From:
````python
            and 'zip' not in ct and cl > 200:
````
To:
```python
            and 'zip' not in ct and 10485760 > cl > 200:
```
Does it make any difference?

**Comment by treysis** [comment]
Nope, it doesn't. It's still funneled through the middleware. Actually, it seems like the problem is not gzip itself, but the way the middleware does buffering. It uses StringIO, even for binary files, no matter whether they'll be compressed or not. There's only one test in the initialization of the GZipMiddleWare-routine inside the middleware, that if the browser doesn't request gzip-encoding, then it will not invole this routine. This is why it breaks even with non-compressible files as long as the browser requests gzip-encoding:

```
        if 'gzip' not in environ.get('HTTP_ACCEPT_ENCODING', ''):
            # nothing for us to do, so this middleware will
            # be a no-op:
            return self.application(environ, start_response)
```

No idea how this "start_response" works. I can't find a definition or declaration. Hm. And I only find usages of it inside middlewares.py.

**Comment by GammaC0de** [comment]
here is `start_response`: https://github.com/pyload/pyload/blob/stable/module/web/middlewares.py#L84

Actually my proposed solution does eliminate the gzip compression (watch the `content-encoding` HTTP header)
Have you tried my proposed solution? do you have logs?

**Comment by treysis** [comment]
`gzip_start_response` and `start_response` are different. `gzip_start_response` will funnel through gzip routine, causing the OOM error. Your proposed solution (I tested it, no difference in error) does eliminate compression, but doesn't eliminate the routine. The routine with `StringIO` as buffer is the problem, not the compression itself.

A workaround I found was to disable GZip compression completely by commenting out `web = GZipMiddleWare(web)` in `webinterface.py:127`.

Log (line numbers may differ slightly cause I added some additional `print` statements here and there):
```
MemoryError('out of memory',)
Traceback (most recent call last):
  File "D:\pyload-0420\pyload\dist\module\lib\wsgiserver\__init__.py", line 1408, in communicate req.respond()
  File "D:\pyload-0420\pyload\dist\module\lib\wsgiserver\__init__.py", line 862, in respond self.server.gateway(self).respond()
  File "D:\pyload-0420\pyload\dist\module\lib\wsgiserver\__init__.py", line 2335, in respond response = self.req.server.wsgi_app(self.env, self.start_response)
  File "D:\pyload-0420\pyload\dist\module\web\middlewares.py", line 55, in __call__ response.finish_response(app_iter)
  File "D:\pyload-0420\pyload\dist\module\web\middlewares.py", line 128, in finish_response output.write(s)
MemoryError: out of memory
```

PS: What also struck me is that files from /downloads/ are served as `text/html`. While that in itself doesn't seem to cause any problems regarding the OOM error, it would probably be cleaner if they were served as `application/binary`.

**Comment by treysis** [comment]
Since I can't find a small working middleware to resolve this issue, I disabled the whole GZip functionality. It's referenced (among other improvements) in this pull request:
https://github.com/pyload/pyload/pull/3619
