### ISSUE TITLE
'Add Package'-Dialog contains old values in input fields

### ISSUE THREAD

**Issue by GaryBlooper** [pyload/pyload#3545]
The dialog showing after clicking the 'Add Package'-Button sometimes contains the values from the former submit. I can't actually say when exactly this happens, but it does from time and time.<p>
In the last release version the input fields where always cleared on dialog opening.

**Comment by fluffyxyz** [comment]
Has something to do with this commit
https://github.com/pyload/pyload/commit/48b499ff4b1677a922578b8fff08cf80fe4fddb6

**Comment by GammaC0de** [comment]
Fixed.
