### ISSUE TITLE
Update pyLoad (IPKG) - My Book Live NAS

### ISSUE THREAD

**Issue by AlphaC0de** [pyload/pyload#3547]
### Update pyLoad (IPKG) - My Book Live NAS

I installed _pyLoad 0.4.9_ on my My Book Live NAS two years ago; now I see a new version is released
How can I update it through SSH Terminal?

### Additional references

I uses Real-Debrid too, is there something I need to update here? The device (pyLoad and Real-Debrid plugin) was not updated from late 2017.

**Comment by GammaC0de** [comment]
>How can I update it through SSH Terminal?

Simply download the ipk file from `https://github.com/pyload/pyload/releases/download/0.4.20/pyload_0.4.20_noarch.ipk` with `wget` and then install it using the command `ipkg install pyload_0.4.20_noarch.ipk`

> I uses Real-Debrid too, is there something I need to update here? The device (pyLoad and Real-Debrid plugin) was not updated from late 2017. 

Why not update!?
pyLoad now supports torrent download via Real-debrid.

**Comment by AlphaC0de** [comment]
> Simply download the ipk file from

Ok, but if I do ipkg install I'll delete previous configuration? I uses a lot of automated scripts and I've a log download history I want to preserve

> Why not update!?
NAS was off for two years but now I need to add it again

**Comment by GammaC0de** [comment]
* Go to `HTTP://<PYLOAD_IP>/info` and backup the folder labeled `Config Folder`.
* Stop pyLoad
* Uninstall version 0..4.9
* Install pyLoad version 0.4.20 and run the setup wizard (make sure you point to the previous `config folder`)
* got to pyLoad's WebUI and see if all your data is there

**Comment by AlphaC0de** [comment]
This was how I installed the package

```
wget --no-check-certificate https://github.com/pyload/pyload/releases/download/v0.4.9/pyload_0.4.9_any.ipk -O ./pyload-v0.4.9-noarch.ipk
ipkg install --nodeps ./pyload-v0.4.9-noarch.ipk
rm -f ./pyload-v0.4.9-noarch.ipk
ln -s /opt/share/pyload/pyLoadCore.py /opt/bin/pyLoadCore
```

How can I uninstall it? And what do you think if I do a clean temporary installation in another folder so that I'm safe?

**Comment by GammaC0de** [comment]
you uninstall using `ipkg remove pyload`

>  what do you think if I do a clean temporary installation in another folder so that I'm safe?

How would you do that?
Don't install two versions at the same time..
Just follow my instructions and I would work.

**Comment by AlphaC0de** [comment]
Tried now even with no check certificate but it says SSL error
```
wget --no-check-certificate https://github.com/pyload/pyload/releases/download/0.4.20/pyload_0.4.20_noarch.ipk -O ./pyload_0.4.20_noarch.ipk
--2020-03-10 20:40:16--  https://github.com/pyload/pyload/releases/download/0.4.20/pyload_0.4.20_noarch.ipk
Resolving github.com... 140.82.118.3
Connecting to github.com|140.82.118.3|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
```

**Comment by GammaC0de** [comment]
Are you using optware of optware-ng?

do `ipkg install  wget-ssl`

**Comment by AlphaC0de** [comment]
If I remember correctly optware-ng; here my setup code

```
# Optware Install
# Optware Install - Initial Setup
cat <<"EOM" >./setup-mybooklive.sh
#!/bin/sh
feed=http://ipkg.nslu2-linux.org/optware-ng/buildroot-ppc-603e
ipk_name=$(wget -qO- $feed/Packages | awk '/^Filename: ipkg-static/ {print $2}')
wget -O /tmp/$ipk_name $feed/$ipk_name
tar -C /tmp -xvzf /tmp/$ipk_name ./data.tar.gz
tar -C / -xzvf /tmp/data.tar.gz
rm -f /tmp/$ipk_name /tmp/data.tar.gz
echo "src/gz optware-ng $feed" > /opt/etc/ipkg.conf
echo "dest /opt/ /" >> /opt/etc/ipkg.conf

PATH=$PATH:/opt/bin:/opt/sbin

echo "Bootstraping done"

echo "Installing glibc-locale package to generate needed /opt/lib/locale/locale-archive"
echo "================================================================================="

/opt/bin/ipkg update
/opt/bin/ipkg install glibc-locale

echo "================================================================================="
echo "Removing glibc-locale package to save space: this doesn't remove generated /opt/lib/locale/locale-archive"

/opt/bin/ipkg remove glibc-locale
EOM

sh setup-mybooklive.sh
rm -f ./setup-mybooklive.sh

export PATH=$PATH:/opt/bin:/opt/sbin

grep -q "/opt/bin" /root/.bashrc || echo "export PATH=$PATH:/opt/bin:/opt/sbin" >> /root/.bashrc
grep -q "/opt/bin" /etc/profile || echo "export PATH=$PATH:/opt/bin:/opt/sbin" >> /etc/profile

grep -q "LC_ALL=en_US.UTF-8" /root/.bashrc || echo "export LC_ALL=en_US.UTF-8" >> /root/.bashrc
grep -q "LC_ALL=en_US.UTF-8" /etc/profile || echo "export LC_ALL=en_US.UTF-8" >> /etc/profile
# End of Optware Install - Initial Setup


# Optware Install - Optware Setup
if [ ! -f /etc/init.d/optware.sh ]; then
cat <<"EOM" >/etc/init.d/optware.sh
#!/bin/sh

start() {
if [ -d /opt/etc/init.d ]; then
  echo "Launching Optware initialization scripts"
  for f in /opt/etc/init.d/S* ; do
    [ -x $f ] && $f start
  done
else
  echo "error: /opt/etc/ini.d directory not found" >&2
  exit 1
fi
}

stop() {
if [ -d /opt/etc/init.d ]; then
  echo "Launching Optware termination scripts"
  for f in /opt/etc/init.d/K* ; do
    [ -x $f ] && $f stop
  done
else
  echo "error: /opt/etc/ini.d directory not found" >&2
  exit 1
fi
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    cleanup)
    ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
EOM
chmod +x /etc/init.d/optware.sh
mkdir -p /opt/etc/init.d
mkdir -p /opt/var/run
update-rc.d optware.sh defaults 90 01
fi
# End of Optware Install - Optware Setup
# End of Optware Install
```

Now I try

**Comment by GammaC0de** [comment]
Try `/opt/bin/wget https://github.com/pyload/pyload/releases/download/0.4.20/pyload_0.4.20_noarch.ipk -O ./pyload_0.4.20_noarch.ipk` instead.

**Comment by AlphaC0de** [comment]
Works perfectly! And I installed and configured all, it seems to be all OK; now it will take a bit of time to check if all works (custom plugins, scripts, ...) but I am confident :wink:
Really thank you!
