### ISSUE TITLE
please include auto captions and auto translate captions.

### ISSUE THREAD

**Issue by dg9999cn** [pyload/pyload#3552]
### Describe the feature

I love what you did in pyload. 
Please include auto captions and auto translate captions download in you next version, it is extremely useful to learn foreign language.
Website like this provide auto captions and auto translate captions.
https://www.findyoutube.net/

**Comment by GammaC0de** [comment]
What are auto captions and auto translate captions?

**Comment by dg9999cn** [comment]
There are some video do not have subtitles, but Google can generate English
subtitle for some video automatically. And translate it into different
language.
