### ISSUE TITLE
Add Package to Queue: Package name changes (Filer.net)

### ISSUE THREAD

**Issue by bachph** [pyload/pyload#3553]
When adding a package in pyload (Hoster Filer.net) I enter a package name and the link of the Filer.net Folder. When the package is "found" and "started" the package name changes.

Is there a way to force pyload to use my entered package name?

**Comment by bachph** [comment]
Maybe this is solved with 0.4.20. But how do I update from 0.4.9 to 0.4.20? See my question [here](https://github.com/pyload/pyload/issues/3283#issuecomment-599190095).

**Comment by GammaC0de** [comment]
Are you downloading from a Filer.net folder?

> But how do I update from 0.4.9 to 0.4.20?

What hardware/OS are you using?

**Comment by bachph** [comment]
> Are you downloading from a Filer.net folder?
Yes.

> But how do I update from 0.4.9 to 0.4.20?
I followed your steps from [#3283](https://github.com/pyload/pyload/issues/3283) but it didn't work.

> What hardware/OS are you using?
It's a remote machine, so I don't know the hardware. It's a gentoo linux machine.

> How did you installed pyLoad in the first place?
wget -O pyload.zip https://github.com/pyload/pyload/archive/stable.zip
unzip pyload.zip; mv pyload-stable/ pyload/
Then used the configuration wizard.

**Comment by GammaC0de** [comment]
> >    But how do I update from 0.4.9 to 0.4.20?

>I followed your steps from #3283 but it didn't work.

Why not?

When pyLoad downloads a folder, it creates a new package with all the URLs in that folder and the name of the package is taken from the folder web page...

**Comment by bachph** [comment]
> Why not?

Unfortunately I don't know. The version is still 0.4.9 and the log still outputs that a newer version is available.

> 15.03.2020 10:11:22 INFO      ADDON UpdateManager: ***  New pyLoad 0.4.20 available  ***
> 15.03.2020 10:11:22 INFO      ADDON UpdateManager: ***  Get it here: https://github.com/pyload/pyload/releases  ***

> When pyLoad downloads a folder, it creates a new package with all the URLs in that folder and the name of the package is taken from the folder web page...
I understand that. But is there no option for overwriting that with the name I enter in the "Add Package" Dialog? If you add e.g. 100 packages - all of them have cryptic folder names - you can't distingish anymore what you added in the first place..

**Comment by GammaC0de** [comment]
> Unfortunately I don't know. The version is still 0.4.9 and the log still outputs that a newer version is available.

    15.03.2020 10:11:22 INFO ADDON UpdateManager: *** New pyLoad 0.4.20 available ***
    15.03.2020 10:11:22 INFO ADDON UpdateManager: *** Get it here: https://github.com/pyload/pyload/releases ***


This is from 3 days ago,
Stop pyload, delete the log files ,start it again and check the logs.

**Comment by bachph** [comment]
> I understand that. But is there no option for overwriting that with the name I enter in the "Add Package" Dialog? If you add e.g. 100 packages - all of them have cryptic folder names - you can't distingish anymore what you added in the first place..

Okay, the update seems to work now. I don't know, maybe I missed the copy step before? Strange.
But could you include an option where you control that the package names is used from what you insert in the the Add Package dialog instead of the web page folder name?
