### ISSUE TITLE
PB 

### ISSUE THREAD

**Issue by Jluc33** [pyload/pyload#3558]
### Describe the problem
 Hello,

since the installation of the Pyload version 0.4.20 I can no longer download from "https://uptobox.com/".

Can you help me ?

### Debug log

WARNING | HOSTER   XFileSharing[5]: UptoboxCom \| Free download failed \| Max retries reached
WARNING | Download failed:   grhxypcksm9j \| Max retries reached

**Comment by GammaC0de** [comment]
Please disable ` XFileSharing` plugin.

**Comment by GammaC0de** [comment]
No response, closing.
