### ISSUE TITLE
Filter Folders

### ISSUE THREAD

**Issue by StefftheEmperor2** [pyload/pyload#3559]
Some providers update their crypted folders from time to time. I use Flexget to observe these changes. But then, the whole package is added again. I think pyload has some sort of duplicate check. But when I cleanup my download folder and move the files to an appropriate destination, the whole package would be downloaded again. It would be great if there was some sort of filter, when adding packages, because flexget would know what to search for. Another solution is to track the downloaded files despite of they were moved/deleted and filter them if they are added again.

**Comment by GammaC0de** [comment]
This is out of the scope of pyload,

You can write your own hook plugin and listen to `links_added` event.
If you already downloaded the URL (saved when you get `package_finished` event), you empty the 'links` argument (which is an array of URLs) .
pyLoad will discard packages with 0 links.

see [TransmissionRPC.py](https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/TransmissionRPC.py) for an example hook plugin that handles `links_added` event.

**Comment by StefftheEmperor2** [comment]
Works .. thx for the advice.
