### ISSUE TITLE
LinkifierCom Hoster not work

### ISSUE THREAD

**Issue by justroot1337** [pyload/pyload#3565]
Hi,

i get the following error when i add my premium account:
WARNING	ACCOUNT LinkifierCom: Error loading info for user `jus*******` | invalid literal for int() with base 10: 'UnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUnlimitedUn' 

Please Help.
Thanks a lot.

just.RooT

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by justroot1337** [comment]
sent.
