### ISSUE TITLE
Problem with rapidgator plugin

### ISSUE THREAD

**Issue by ironbiff** [pyload/pyload#3566]
Hey pyload Team,

using pyload quite a long time now with uploaded Account. Works like a charm
Added rapidgator Account. I tried 
-> Everytime I get

`WARNING | Download failed: xxxxx.part1.rar | Bad server response: 503 Service Unavailable`

for each download. 

Maybe I am just dump, but I did not manage to fix it. Maybe its a bug, but no one else in the internet is complaining about this.

Setup:
Synology NAS
Docker
linuxserver/pyload
pyload: 0.4.20

tested also
linuxserver/pyload and writl/pyload on docker for mac so I assume it is at least not related to a special docker image.

Is there somebody who can help me out of it.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by ironbiff** [comment]
thank you.
mail is on its way

**Comment by GammaC0de** [comment]
I have tested you account (once) and it worked.

503 is sometimes generated by CloudFlare's DDoS protection page, maybe this is the issue here.

Please provide more detailed log (DEBUG log!!)

Also, if you enable debug mode, there should be some html files inside `<PYLOAD_HOME_DIR>/tmp/RapidgatorNet` directory, maybe it can shed some light on what's happening..

**Comment by GammaC0de** [comment]
What happens if you add 
```
DIRECT_LINK = False
```
to [RapidgatorNet.py#L36](https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/RapidgatorNet.py#L36)?

**Comment by ironbiff** [comment]
Added DIRECT_LINK in ../hoster/Rapidgator.py

no changes!

log:

05.04.2020 15:16:17 | INFO | Download starts: Mr.Robot.S04E01.GERMAN.DL.1080.p.WEB.H.264-FENDT.part1.rar
-- | -- | --
215 | 05.04.2020 15:16:17 | WARNING | HOSTER RapidgatorNet[1]: Plugin may be unstable
216 | 05.04.2020 15:16:17 | INFO | ACCOUNT RapidgatorNet: Grabbing account info for user `rap*******`...
217 | 05.04.2020 15:16:17 | INFO | HOSTER RapidgatorNet[1]: Grabbing link info...
218 | 05.04.2020 15:16:18 | INFO | HOSTER RapidgatorNet[1]: Link name: Mr.Robot.S04E01.GERMAN.DL.1080.p.WEB.H.264-FENDT.part1.rar
219 | 05.04.2020 15:16:18 | INFO | HOSTER RapidgatorNet[1]: Link size: 1.00 GiB (1073741824 bytes)
220 | 05.04.2020 15:16:18 | INFO | HOSTER RapidgatorNet[1]: Link status: online
221 | 05.04.2020 15:16:18 | INFO | HOSTER RapidgatorNet[1]: Processing url: https://rapidgator.net/file/2bcbeb6f9e7616438f7570bb0e8fd698
222 | 05.04.2020 15:16:18 | WARNING | Download failed: Mr.Robot.S04E01.GERMAN.DL.1080.p.WEB.H.264-FENDT.part1.rar \| Bad server response: 503 Service Unavailable

**Comment by GammaC0de** [comment]
Can you try changing your IP address?

**Comment by ironbiff** [comment]
reconnected router -> got new different IP
sadly, same Problem

I also tried re-adding the poster Account which results in this. A reboot of pyload fixes the issue. 
<img width="823" alt="Bildschirmfoto 2020-04-05 um 20 13 15" src="https://user-images.githubusercontent.com/16765857/78506463-ee3dd800-7779-11ea-97d1-bc7f71f70b10.png">
!

I do not understand why it should work for you and not for me.

**Comment by GammaC0de** [comment]
What happens if you login to rapigator.net from the web browser?

Do you get any special messages?

**Comment by ironbiff** [comment]
Nothing special. I also tested rapidgator with jdownloader some weeks ago and this works fine. 
same System, same IP, same rapidgator account

**Comment by 4gql** [comment]
I just wanted to note, that I am having the exact same problem. I can download directly on the rapidgator website but not with pyload, haven't tried JDownloader.

**Comment by GammaC0de** [comment]
@4gql  Please provide debug log while logging in,
If that would not net lead to positive results, I might need to access you pyload machine.

**Comment by 4gql** [comment]
I do not know how to provide a debug log. What do I need to do in order to get the debug log?

**Comment by GammaC0de** [comment]
@ironbiff 
Can you try without docker? maybe on your pc..

@4gql 
First you have to enable debug mode:
Settings -> General -> Debug Mode: on

Then restart pyload and add the rapigator account.

Copy the log from the "logs" tab.

**Comment by 4gql** [comment]
Debuglog: https://pastebin.com/kCbNqxQe

I wanted to note that at least for me JDownloader is also not working correctly. On first boot it manages to start the download of a single file but with mutiple files or multiple chunks or when it should start the next file as well as on pause/resume it fails and goes into a one minute wait loop. In the settings tap under "Account Manager" it shows that the status of the account is "[404] Session expired - waiting before opening next session". When the wait of one minute is over the account becomes green and active for the fraction of a second and the goes in the above stated error state again.

**Comment by GammaC0de** [comment]
@4gql I see that you have successfully logged in, can you download?

**Comment by 4gql** [comment]
No I cannot. Maybe this helps, also from the debuglog: https://pastebin.com/m3y0JZqs

**Comment by GammaC0de** [comment]
To try to solve it , can I have access to your pyload?

**Comment by 4gql** [comment]
Sure how do you want to connect? Directly to Pyload somehow or via Teamviewer or something alike?

**Comment by GammaC0de** [comment]
Anydesk would be great
send your Anydesk ID to nitzo2001 at yahoo dot com.

**Comment by 4gql** [comment]
Send you the ID.

**Comment by GammaC0de** [comment]
It works now.

One issue I noted,
You should enable write permissions to /opt/pyload/modules/plugins to the user that runs pyload..

**Comment by GammaC0de** [comment]
OK, this is crazy 

Same url: `https://rapidgator.net/file/ba210bb2ed8adc9d72207c26bbdabe6c/avzal.BeatSkillz.Bollywood.Maharaja.v2.0.MacOSX.part1.rar.html`

With my browser:
Free download is ok
Premium download gives 503 😠 :

Also when trying their example php API library (http://rapidgator.net/library/rapidgator_php_client.zip) download is failing

![Capture](https://user-images.githubusercontent.com/11036551/79052378-cef1ef80-7c3e-11ea-9305-129b6e901376.PNG)

**Comment by 4gql** [comment]
You think it is fixable or is their API just to messed up?

**Comment by GammaC0de** [comment]
@4gql  @ironbiff  I think the root of this issue is the "Check IP during authorization"  in Rapidgator settings:
Either disable it or add your pyload's public IP to the whitelist.

I can now premium download successfully after whitelisting my IP. 

I might update the plugins to use API v2 though.

@4gql Please test and confirm.

**Comment by 4gql** [comment]
I deactivated the IP check and can confirm that I can download via Pyload now without issues.

@GammaC0de: Thank you a lot for your effort.

**Comment by GammaC0de** [comment]
👍

**Comment by ironbiff** [comment]
@4gql you had IP check activated before? Are we talking about this check?

<img width="772" alt="Bildschirmfoto 2020-04-13 um 11 45 34" src="https://user-images.githubusercontent.com/16765857/79111549-036bc580-7d7d-11ea-98bd-14e2edf3ddc7.png">

Sorry for getting back to this. I even activated and deactivated IP check again (before it was already deactivated) but I got the same error again.

**Comment by GammaC0de** [comment]
Try whitelisting your IP, maybe that would help

**Comment by ironbiff** [comment]
already tested this -> does not work
installed pyload on a windows machine but unfortunately got the same errors.

**Comment by GammaC0de** [comment]
> installed pyload on a windows machine but unfortunately got the same errors.

Can you give me access with Anydesk?

**Comment by ironbiff** [comment]
just for the record and all the guys with the same problem. A mail to rapidgator fixed the problem. The IP Range of my ISP was blocked on their side. I just wrote a mail to the support team that I got these errors and they instantly answered with something like "your account is open now...."

@GammaC0de thank you very much for your terrific support.

**Comment by GammaC0de** [comment]
👏clap
