### ISSUE TITLE
Realdebrid whitelist/blacklist did not run

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#3567]
### Describe the problem

Hello, if I want to exclude an account from realdebrid, then I enter it at Hoster list. In this case, I want YouTube to be excluded.
So I enter YoutubeCom and set filter hosters to use: unlisted.
Nevertheless, he loads things via Realdebrid instead of directly via youtube.

### Debug log

```

```

**Comment by GammaC0de** [comment]
Apparently the definition is a bit misleading,
This should be `youtube.com`, not `YoutubeCom`.

**Comment by Mister-XY** [comment]
Thanks, closed
