### ISSUE TITLE
WARNING   HOSTER BasePlugin[3]: Free download failed | IOError 36

### ISSUE THREAD

**Issue by xerosanyam** [pyload/pyload#3568]
### Describe the problem

Unable to download anything, getting err `WARNING   HOSTER BasePlugin[3]: Free download failed | IOError 36`

### Debug log

```

```

### Screenshots

![image](https://user-images.githubusercontent.com/3167278/78371673-e51c0200-75e5-11ea-96c3-7e768be1d595.png)

### Additional references

using Ansible-nas default configuration to run this.

**Comment by GammaC0de** [comment]
URL????

IOError 36 is "File name too long"

**Comment by GammaC0de** [comment]
No response, closing.
