### ISSUE TITLE
Remove special characters in Youtube titles

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#3569]
### Describe the plugin

Is it possible to remove special characters in youtube titles?
E.g. the following, because Windows cannot display them in the name: \ /: *? "<> |

**Comment by GammaC0de** [comment]
Special characters should have been removed,.
Or am I missing something?

**Comment by Mister-XY** [comment]
I don't find this. I also have special charakters.
Here is a example.
https://www.youtube.com/watch?v=9B76VV4cdEY

**Comment by GammaC0de** [comment]
What OS are you using?

**Comment by Mister-XY** [comment]
To Download, i'm using Debian 10 and to look into folder, i'm using windows 10.
