### ISSUE TITLE
Real-Debrid - Failed to login

### ISSUE THREAD

**Issue by AlphaC0de** [pyload/pyload#3570]
### Describe the problem

Are there some changes to Real-Debris plugin? A month ago all was working, using _LoginID_ and _APIToken_ but now it seems not to work anymore

### Debug log

```
You have to use GetRealdebridToken.py to authorize pyLoad: https://github.com/pyload/pyload/files/4406037/GetRealdebridToken.zip
```

**Comment by GammaC0de** [comment]
> Are there some changes to Real-Debris plugin

Yes

You have to authorize pyLoad using https://github.com/pyload/pyload/files/4406037/GetRealdebridToken.zip

**Comment by AlphaC0de** [comment]
I've to run this from SSH or what?

**Comment by GammaC0de** [comment]
No need

**Comment by AlphaC0de** [comment]
I'm sorry I'm not understanding; I have to put that .py file in the Plugin folder or to select something? I don't see any option.

**Comment by GammaC0de** [comment]
You have to run `GetRealdebridToken.py` to get username and password.

**Comment by AlphaC0de** [comment]
Something wrong?

```
MyBookLive:~# cd /root
MyBookLive:~# bash GetRealdebridToken.py
GetRealdebridToken.py: line 3: $'\r': command not found
from: can't read /var/mail/__future__
GetRealdebridToken.py: line 5: $'\r': command not found
GetRealdebridToken.py: line 6: import: command not found
GetRealdebridToken.py: line 7: import: command not found
GetRealdebridToken.py: line 8: import: command not found
GetRealdebridToken.py: line 9: $'\r': command not found
GetRealdebridToken.py: line 12: $'\r': command not found
GetRealdebridToken.py: line 25: syntax error near unexpected token `('
GetRealdebridToken.py: line 25: `def fetch_url(url, referer=None, user_agent=USE'_AGENT, headers={}, post={}, size=None):
MyBookLive:~# 
```

**Comment by GammaC0de** [comment]
use `python GetRealdebridToken.py`

**Comment by AlphaC0de** [comment]
```
MyBookLive:~# python /root/GetRealdebridToken.py
  File "/root/GetRealdebridToken.py", line 42
    except URLError as e:
                     ^
SyntaxError: invalid syntax
MyBookLive:~#
```

**Comment by GammaC0de** [comment]
Use python 2.7 and up, you can run it from your PC too.

**Comment by AlphaC0de** [comment]
I try now; the output I'll get it's one-time or I can save it and re-use if I'll do a new installation?

**Comment by GammaC0de** [comment]
I guess you can save it but i don't recommend it.

**Comment by GammaC0de** [comment]
Each user and password is intended to be used on a single device,
I hope this clarify things.

**Comment by AlphaC0de** [comment]
Yes same device I'm the only user; I was only thinking if it was possible to automate a future restore without login anymore

**Comment by GammaC0de** [comment]
I guess that's fine.

**Comment by AlphaC0de** [comment]
Now login seems to work but there's some issue as It runs as free download; I'll check later and If no issue I close here

**Comment by AlphaC0de** [comment]
All OK, works perfectly; thank you @GammaC0de

**Comment by githubby11** [comment]
> > Are there some changes to Real-Debris plugin
> 
> Yes
> 
> You have to authorize pyLoad using https://github.com/pyload/pyload/files/4406037/GetRealdebridToken.zip

How would this work for Synology NAS using Docker?
