### ISSUE TITLE
MegaCoNz - not recognise new url patterns 

### ISSUE THREAD

**Issue by felixmosh** [pyload/pyload#3571]
### Describe the problem

Looks like mega.nz changed the url structure, therefore, pyload not recognize the hoster any more -> fallbacks to BasePlugin.

I think that this pattern is not matching anymore.
```
__pattern__ = r'(https?://(?:www\.)?mega(\.co)?\.nz/|mega:|chrome:.+?)#(?P<TYPE>N|)!(?P<ID>[\w^_]+)!(?P<KEY>[\w\-,=]+)(?:###n=(?P<OWNER>[\w^_]+))?'
```
Example of url:
https://mega.nz/file/FioDkD4b#Gji67x6-BxL12Fg8Dvm9cYYApezEI_qOkcA61G30W4

The url is missing (`c`) at the end.

**Comment by cbackas** [comment]
I thought I was going crazy over the last couple of days - couldn't find anyone else talking about this issue and can't download all these things

**Comment by felixmosh** [comment]
@GammaC0de thank you for the quick fix 🙏🏼but i think that it is not working properly 
I've got this update 
![image](https://user-images.githubusercontent.com/9304194/78654458-31f52680-78cd-11ea-8674-12a36c8f3b46.png)
It fails on ```failed 'ID' 0.00 B MegaCoNzFolder```
```
WARNING	CRYPTER MegaCoNzFolder[7]: Plugin may be unstable
954	07.04.2020 12:40:26	INFO	CRYPTER MegaCoNzFolder[7]: Grabbing link info...
955	07.04.2020 12:40:26	INFO	CRYPTER MegaCoNzFolder[7]: Link name: hMhDmAaS
956	07.04.2020 12:40:26	INFO	CRYPTER MegaCoNzFolder[7]: Link size: N/D
957	07.04.2020 12:40:26	INFO	CRYPTER MegaCoNzFolder[7]: Link status: starting
958	07.04.2020 12:40:26	INFO	CRYPTER MegaCoNzFolder[7]: Processing url: https://mega.nz/folder/hMhDmAaS#4nBkyaNdeS46ZmEqAU2nGQ/file/0Q4gDSDL
959	07.04.2020 12:40:26	ERROR	Decrypting failed: hMhDmAaS | 'ID'
```

**Comment by felixmosh** [comment]
Apparently I needed to restart pyload, then it started to work, so thank you 🙏

**Comment by cbackas** [comment]
I'm still having a lot of trouble with the new link structure. I'm using the Linuxserver/Pyload docker container. I've restarted and updated many times in the last few days and I'm still getting 

> 12.04.2020 07:01:49 ERROR Decrypting failed: RlwzDQBR | Decrypt error: No link grabbed | Plugin may be out of date

The UpdateManager in the startup logs insists all plugins are up to date every time I've restarted. Starting to get a pile of veritably active megalinks that I can't download. 

When I try to add the links it tries to use the XFileSharing plugin and fails, if I disable the XFileSharing plugins it gives tries to use the Mega plugins and fails. 

Is there something else I need to do to get this working again?

**Comment by GammaC0de** [comment]
Sample URL please

**Comment by cbackas** [comment]
I just made a new folder with a random cat video (content I can share on github) 

https://mega.nz/folder/xpVCmCZa#5ss5tEjoR9PVIZiw4r-Dwg

Behaves the same as the other megalinks I come across

**Comment by GammaC0de** [comment]
Works fine for me, plugins version 0.22 and 0.55

**Comment by cbackas** [comment]
Where can I check what the plugin versions I have are?

**Comment by GammaC0de** [comment]
If you enable debug mode, you'll see it in the logs while downloading.

**Comment by cbackas** [comment]
https://hastebin.com/sitilebeva.py

I just went and disabled XFileSharing/Folder plugins and it got out of the way and the mega link worked!
