### ISSUE TITLE
[XDCC] join custom IRC channel

### ISSUE THREAD

**Issue by temsof** [pyload/pyload#3573]
### Describe the feature

Allow defining custom IRC channels to join on connect.

### Is this related to a problem?

Some IRC channels have the requirement to join an additional channel. If not joined, the download will be canceled after a short time.

### Describe alternatives you've considered

--

### Additional references

--

**Comment by GammaC0de** [comment]
Example please

**Comment by temsof** [comment]
join server + channel = irc://irc.abjects.net:6667/moviegods
start any download
you get whisper: 
`<BotReign> You must /join #mg-chat to download. Your download will be canceled now.`
