### ISSUE TITLE
Add option for intermediate certificate chain

### ISSUE THREAD

**Issue by h4de5** [pyload/pyload#3578]
### Add option to provide an intermediate certificate

when starting the threaded webserver with an certificate, browsers like chrome or firefox may connect successfully when using a fullchain cerficiate. Other lclients like curl or openssl, which are used heavingly in automations, do not accept this certificate due to the missing certificate chain.

a proposed change is to add `certificate_chain` parameter to https://github.com/pyload/pyload/blob/master/src/pyload/webui/webserver_thread.py#L50

Test your installation:

`openssl s_client -connect your.domain.com:8001`

    Certificate chain
     0 s:CN = your.domain.com
       i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3

but should be:

    Certificate chain
     0 s:CN = your.domain.com
       i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
     1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
       i:O = Digital Signature Trust Co., CN = DST Root CA X3

### Additional references

duplicates that were closed but not fixed:
https://github.com/pyload/pyload/issues/3210
https://github.com/pyload/pyload/issues/2386
https://github.com/pyload/pyload/issues/1809
ssl adapter reference:
https://docs.cherrypy.org/projects/cheroot/en/latest/pkg/cheroot.ssl.builtin.html

**Comment by GammaC0de** [comment]
Are you talking about pyLoad v0.4.20 or v0.5?

**Comment by h4de5** [comment]
It is in current master - so v0.4.20?

**Comment by GammaC0de** [comment]
master => 0.5
stable => v0.4.20

**Comment by h4de5** [comment]
mmh. I am sorry - my bad - I am pulling the docker installation from `linuxserver/pyload:latest` 
 - so I thought I was on the latest version. The info page says indeed v0.4.20

So its for the current stable.

**Comment by h4de5** [comment]
in that case the path to the threaded webserver is wrong:

https://github.com/pyload/pyload/blob/9f479e872841e72374a40ae21881b0bc888afb6a/module/web/webinterface.py#L150

and the reference for the `certificate_chain`: https://cherrypydocrework.readthedocs.io/pkg/cherrypy.wsgiserver.html

**Comment by GammaC0de** [comment]
`CherryPy `on v0.4.20 is very old, no support for `certificate_chain`.
Updating `CherryPy `may not be an option for v0.4.20..

I have to look what can be done, but I'm quite busy A.T.M.

**Comment by treysis** [comment]
I updated CherryPy to 8.9.1 and it's working fine. I also tried Cheroot 5.11.0 (latest with Python 2.6 support) and it just needs some minor changes on the import statements (obviously, CherryPyWSGIServer needs to be updated). Can't complain, but will cause non-breaking error messages with self-signed certificates (that's due to SSL lib afaik).

**Comment by GammaC0de** [comment]
@treysis Can you please document here the changes that you have made to make it work (and maybe provide a patch file) ?

**Comment by treysis** [comment]
@GammaC0de Hi, I already described the necessary changes here:
https://github.com/pyload/pyload/issues/3543#issuecomment-594294390
That is for CherryPy 8.9.1 (last version before it was renamed to Cheroot). For Cheroot 5.11.0 we also need to change the import. I have that on my other computer and will look it up at the weekend.

**Comment by treysis** [comment]
I wouldn't wait for 0.5.x to implement this, as this isn't a big change. If you don't want to include it in the current release, maybe make a new 0.4.21 or something like this. I think it definitely should go into the current branch and not be delayed till 0.5.x, even though most people probably run it in docker behind some reverse proxy.

**Comment by treysis** [comment]
I finally got around to implementing the upgrade to cheroot/5.11.0 (latest version that supports Python 2.x), which also fixes SSL and dualstack, and I added a dualstack option to the webinterface configuration. See my PR: https://github.com/pyload/pyload/pull/3619

**Comment by GammaC0de** [comment]
@h4de5 https://github.com/pyload/pyload/commit/63f0f9269bd5d37dddda811d630353a83338ed7a Added support for intermediate certificate chain, can you please test and confirm working?

**Comment by h4de5** [comment]
@GammaC0de : I can confirm that in the latest docker release (0b68255490a5) the intermediate certificate is delivered correctly. no more ssl handshake errors using curl.

it seems the update also fixed the original certificate output, because if I choose a fullchain certificate in the normal ssl field (leaving the intermediate empty) - no more errors are triggered now.

thanks for the fast response and the backport!


still having trouble with the API integration - but this seems to be another problem.
linking https://github.com/home-assistant/core/issues/10678
