### ISSUE TITLE
Web Interface Not Showing

### ISSUE THREAD

**Issue by vertigo888** [pyload/pyload#3580]
Hi,

Service has started but web interface is not showing - any ideas?

**Comment by GammaC0de** [comment]
Is this a new installation?
How exactly did you installed it?

**Comment by vertigo888** [comment]
Fresh install and via entware, which i also installed clean. Are there any logs I can provide or check?

**Comment by GammaC0de** [comment]
Have you run the configuration wizard from the console?

**Comment by GammaC0de** [comment]
No response, closing.
