### ISSUE TITLE
Is it possible to set a referer url for a specific url or a whole package?

### ISSUE THREAD

**Issue by crash5** [pyload/pyload#3581]
### Your question

Is it possible to set a referer url for a specific url or a whole package? (There is some page who enables downloads with a specific referer only like vimeo)

**Comment by GammaC0de** [comment]
You'll have to write a plugin for that.

**Comment by crash5** [comment]
Which plugin type can change the add url dialog? Or I need a whole new hoster plugin and change the referer in the config section after every url?

**Comment by GammaC0de** [comment]
@crash5 Are we speaking on a specific hoster that you are downloading from or the URLs are just plain HTTPlinks?

**Comment by crash5** [comment]
It's some kind of vimeo videos. Embedded in paid sites and only can be viewed if the referer match the including site address.

**Comment by StefftheEmperor2** [comment]
So you should add the paid site and a pyload plugin should crawl the Vimeo video from there and set the referrer accordingly

**Comment by GammaC0de** [comment]
I cannot tell,
Is this a vimeo video or vimeo is just an example?

**Comment by crash5** [comment]
This is a vimeo video, embedded in a site. I can copy the video url from the page source but if I simply try to open it in a new tab it says i can't view it because of some privacy settings. But if I spoof the referer address it works.

**Comment by GammaC0de** [comment]
Without more details I cannot help you further,
If you would like, please send the URLs and supposed referrer to nitzo2001 at yahoo dot com.

**Comment by crash5** [comment]
Ok, thank you.
