### ISSUE TITLE
passive mode with xdcc plugin?

### ISSUE THREAD

**Issue by galitus** [pyload/pyload#3583]
Is it possible to use XDCC with passive DCC?

I think the question is already describing the problem and the question.
Some transfer is being done using the passive mode which needs to be configured.
The external ip and ports on the client side has to be set to the external ip and external available ports, so that the other person can send files through this mode.

I tested the normal transfer mode and it is working fine but passive mode is not working.

Is there a way to achieve this?

thanks in advance

**Comment by GammaC0de** [comment]
> but passive mode is not working

Where I can test passive mode?

**Comment by GammaC0de** [comment]
@galitus Do you have an example for XDCC bot that needs  passive mode?

**Comment by galitus** [comment]
I wrote you a mail and you can set up a bot on your own very fast with

https://github.com/dinoex/iroffer-dinoex

the important part in the config is passive_dcc.

the error message of the plugin is:
getsockaddrarg: port must be 0-65535.

**Comment by GammaC0de** [comment]
XDCC plugin now has passive DCC support  (https://github.com/pyload/pyload/commit/c4e13955ada3b9df8d1e62ee8bd0d217c9956ba9).
Better now than never :)
