### ISSUE TITLE
[XDCC] add waiting time while in queue

### ISSUE THREAD

**Issue by temsof** [pyload/pyload#3584]
### Describe the feature

~~Add max_wait option to plugin settings.~~
Edit: Add an option to wait for the pack after requesting it. Maybe a detection if you are in a queue.

### Is this related to a problem?

Sometimes all slots of a bot are full and you have to wait in a queue. At the moment, the plugin 

- requests for the pack
- wait 90 secs
- disconnects from server 
- waits 1min
- starts from the beginning

example log:
```
14.04.2020 19:34:31 INFO      HOSTER XDCC[11]: Requesting pack #1
14.04.2020 19:36:01 INFO      HOSTER XDCC[11]: Diconnecting from <Server>
14.04.2020 19:36:01 DEBUG     HOSTER XDCC[11]: Disconnected
14.04.2020 19:36:01 ERROR     HOSTER XDCC[11]: XDCC Bot did not answer
14.04.2020 19:36:01 DEBUG     HOSTER XDCC[11]: WAIT set to timestamp 1586893022.387776 | Previous waitUntil: 1586892859.656410
14.04.2020 19:36:01 DEBUG     HOSTER XDCC[11]: Config option `max_wait` not found, use default `10`
14.04.2020 19:36:01 INFO      HOSTER XDCC[11]: Waiting 1 minutes...
```

**Comment by GammaC0de** [comment]
Very nice but you did not explain what max_wait option would do....

**Comment by temsof** [comment]
I was thinking, the `max_wait` option would add a default waiting time after requesting a pack. But it looks like I was wrong with this ;)

I've a piece of log from an older session, where the bot messaged a status update every ~10 mins. But I'm not sure, if this is the default for all servers.

snippet:
```
# Requesting Pack 251
06.04.2020 19:09:46 DEBUG     HOSTER XDCC[5]: PrivMsg: <BOT> ** All Slots Full, Added you to the idle queue for pack 251 ("REQUESTED-ITEM") in position 11. To Remove yourself at a later time type "/MSG BOT XDCC REMOVE".
06.04.2020 19:21:06 DEBUG     HOSTER XDCC[5]: PrivMsg: <BOT> Queued 0h5m for "REQUESTED-ITEM", in position 49 of 50. 46h24m or less remaining. (at 19:09)
06.04.2020 19:29:29 DEBUG     HOSTER XDCC[5]: PrivMsg: <BOT> Queued 0h5m for "REQUESTED-ITEM", in position 48 of 50. 23h54m or less remaining. (at 19:19)
06.04.2020 19:38:00 DEBUG     HOSTER XDCC[5]: PrivMsg: <BOT> Queued 0h15m for "REQUESTED-ITEM", in position 45 of 49. 22h41m or less remaining. (at 19:29)
```

**Comment by GammaC0de** [comment]
Can you send me the IRC host, channel and bot for pack 251?
If you don't want to post here, you can send via email (nitzo2001 at yahoo dot com).

**Comment by GammaC0de** [comment]
So what you are asking is to add an option to set the time period between retries of pack request from the XDCC bot?

**Comment by temsof** [comment]
I would like to have a longer wait time between requesting a pack and disconnecting from the server.
At the moment it waits only for 90 secs after the pack request, then disconnects, waits another 1 min and starts the next try.

It looks like the IRC bots are using iroffer -> https://github.com/dinoex/iroffer-dinoex - maybe something like this would work:

- Request Pack
- Wait 10 min for response from bot, containing text from here: https://github.com/dinoex/iroffer-dinoex/blob/master/src/dinoex_queue.c#L297
- if added to queue, wait 15 min for the download to start
- if bot response with a message like - https://github.com/dinoex/iroffer-dinoex/blob/master/src/dinoex_misc.c#L315 -> wait another 15 min

**Comment by GammaC0de** [comment]
Hi,
I could not find a busy bot :(
Can you test this file http://0x0.st/i12B.py (rename to XDCC.py) and tell if it works as expected?

**Comment by temsof** [comment]
found a busy bot using the new version and sent you the logs.
what exactly does the new `retry_wait` do?

**Comment by GammaC0de** [comment]
OK, reshuffle,
Please try this one:
[XDCC.zip](https://github.com/pyload/pyload/files/4513068/XDCC.zip)

If you have more busy bots, please send.

**Comment by GammaC0de** [comment]
Hi, any news about this?

**Comment by temsof** [comment]
nope, no luck atm.

**Comment by GammaC0de** [comment]
By "no luck" you mean you could not find a busy bot yet? 

 
 
   temsof<notifications@github.com> wrote:   


nope, no luck atm.

**Comment by temsof** [comment]
just found a busy bot with queue. have done some tests and sent you the logs.
for me it looks like the addon detects the `RE_QUEUED` responses from the bot, but not `RE_QUEUE_STAT`.

The setting `Time to wait before failing if queued` seems to work.

**Comment by temsof** [comment]
> for me it looks like the addon detects the `RE_QUEUED` responses from the bot, but not `RE_QUEUE_STAT`.

I thought that `RE_QUEUED_STAT` would output any INFO msg to the logs like `RE_QUEUED` does, but just noticed it's not coded like this. So ignore my "not working" for `RE_QUEUED_STAT` :)

**Comment by GammaC0de** [comment]
You should increase `Time to wait before failing if queued`,
lests  say 300

**Comment by temsof** [comment]
yeah sure, normaly i would go for something like 900 sec. had it set to a lower value to see, what happens if the time is reached.

**Comment by GammaC0de** [comment]
So what is your conclusion, does it work fine?

**Comment by temsof** [comment]
For me it looks great and i saw no errors.
The only question i have is, should something happen if the `XDCC Bot response timeout` time is reached? In some examples i had it to 5 seconds and nothing happened if the bot didn't responded in time.

**Comment by GammaC0de** [comment]
> In some examples i had it to 5 seconds and nothing happened if the bot didn't responded in time

There is a hard minimum of 60 seconds

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/fc897ee3dc9e8dd4a6377af8f2b39b63e5a7c024 added queue position logging

**Comment by temsof** [comment]
did some testings yesterday, working great with the new query queue feature.
no bugs found so far, nice work 👍

**Comment by GammaC0de** [comment]
Also added queue waiting time https://github.com/pyload/pyload/commit/04d4225f7257b40125117f407b4e17c33ac66e8a

Issue resolved, closing.
