### ISSUE TITLE
Plugin PremiumTo not working

### ISSUE THREAD

**Issue by garrit-schroeder** [pyload/pyload#3588]
Premium To has changed their api.

The new details can be found here:
https://premium.to/API.html

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by the-rene** [comment]
Works for me with the current stable branch, it uses the new API already

**Comment by s3ppo** [comment]
the download is working but the filenames are wrong (something like 93df34292 without extension).. still have to rename all files and put it in correct sorting ( *.r01 *.r02 .... )

**Comment by GammaC0de** [comment]
@s3ppo  Try refresh your pyLoad installation using the instruction in #3283 and then retry.

**Comment by s3ppo** [comment]
@GammaC0de thanks for your answer, is there also a howto when using a docker? (its from linuxserver and up-to-date)

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

Also please provide problematic sample URLs
