### ISSUE TITLE
Ddl.to is now ddownload.com

### ISSUE THREAD

**Issue by monkeynightlife** [pyload/pyload#3590]
### Describe the problem

The URL of the hoster changed.

**Comment by Vinnpinn** [comment]
@GammaC0de if you still need my account, I haven't changed the password yet and you can use it if you need to.

**Comment by monkeynightlife** [comment]
Still not working:


1395 | ? | ? | File "/home/server/pyload_stable/module/plugins/hoster/XFileSharing.py", line 38, in init
-- | -- | -- | --
1396 | ? | ? | self.pyfile.url).group("DOMAIN").lower()
1397 | ? | ? | AttributeError: 'NoneType' object has no attribute 'group'

**Comment by monkeynightlife** [comment]
Thanks
