### ISSUE TITLE
can't download youtube.

### ISSUE THREAD

**Issue by dg9999cn** [pyload/pyload#3593]
### Describe the problem

can't download the video
https://www.youtube.com/watch?v=xYZZsoVzZ-k
https://www.youtube.com/watch?v=OtCMu4jdSRI

19.04.2020 04:17:18 | INFO | HOSTER YoutubeCom[104]: Processing url: https://www.youtube.com/watch?v=RZM02tHKg_8
-- | -- | --
354 | 19.04.2020 04:17:20 | WARNING | HOSTER YoutubeCom[104]: Free download failed \| Cannot identify player ID https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js
355 | 19.04.2020 04:17:20 | WARNING | Download failed: watch \| Cannot identify player ID https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js
356 | 19.04.2020 04:17:20 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: watch (pid:2)
357 | 19.04.2020 04:17:20 | INFO | ADDON UnSkipOnFail: Queue found duplicate: watch (pid:2)
358 | 19.04.2020 04:17:37 | INFO | HOSTER YoutubeCom[109]: File saved
359 | 19.04.2020 04:17:38 | WARNING | HOSTER YoutubeCom[109]: ffmpeg error
360 | 19.04.2020 04:17:38 | INFO | HOSTER YoutubeCom[109]: Checking download...
361 | 19.04.2020 04:17:38 | INFO | HOSTER YoutubeCom[109]: Path deleted: /downloads/Y1.8 dance bible action songs/Always w Lyrics.video.mp4
362 | 19.04.2020 04:17:38 | WARNING | HOSTER YoutubeCom[109]: Free download failed \| Parse error: Empty file \| Plugin may be out of date
363 | 19.04.2020 04:17:38 | WARNING | Download failed: Always w Lyrics.video.mp4 \| Parse error: Empty file \| Plugin may be out of date
364 | 19.04.2020 04:17:38 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: Always w Lyrics.video.mp4 (pid:2)
365 | 19.04.2020 04:17:38 | INFO | ADDON UnSkipOnFail: No duplicates found

### Debug log

```

```

**Comment by GammaC0de** [comment]
Downloading https://www.youtube.com/watch?v=RZM02tHKg_8 now works.

As for https://www.youtube.com/watch?v=OtCMu4jdSRI, I do not know why this happens, I hope the problem is just with this URL and not other.
We'll see.
