### ISSUE TITLE
Random MegaCoNz links within a folder get skipped

### ISSUE THREAD

**Issue by cbackas** [pyload/pyload#3594]
### Describe the problem
When I add a mega folder to the download queue, it will randomly mark certain files as "skipped" and I'll have to re-queue  them (sometimes multiple times) to get them to actually download. This happens with just about every folder I add for a month+.... So either I've got something really messed up or everyone else is too lazy to report this? (like i have been for the last weeks)

### Debug log
Debug off logs: https://i.imgur.com/AMCDKNa.png
Debug on logs: https://i.imgur.com/RsmaN2V.png
I hope I included enough logs, let me know if I need to go find more
(Different folder links at different times)

### Screenshots
Screenshot of queue during issue: https://i.imgur.com/z3XHJLw.png

It doesn't stop me from downloading files, as I can still get them if I'm persistent enough with the re-queue, but I do wish I didn't need to babysit every folder so much

**Comment by GammaC0de** [comment]
This is because you have enable "skip existing" download and pyload does not know the file name before starting to download..

**Comment by cbackas** [comment]
So i guess the skip existing feature doesn't really work

**Comment by adir6** [comment]
Hi, I am having the same issue even though, "Skip already existing files" feature is disabled.

**Comment by GammaC0de** [comment]
@adir6 Please provide a debug log showing your issue.
