### ISSUE TITLE
FileStoreTo Plugin unstable

### ISSUE THREAD

**Issue by mcmikele** [pyload/pyload#3598]
Hi all,

I installed today the pyload 4.9 qpkg on my QNAP NAS. 

Its not possible to download for example from the hoster Filestore. I got the error below. It is enough to install just the pyload qpkg or do I need also to install python?

PS: The plugins are up to date. I copied them from the stable version!

Error Message:
failed httpDownload() got an unexpected keyword argument 'size' 0.00 B FileStoreTo

### Debug log
589 | 22.04.2020 15:51:54 | INFO | Download starts: http://filestore.to/?d=8JNX8FDLEC
-- | -- | -- | --
590 | 22.04.2020 15:51:54 | WARNING | HOSTER FileStoreTo[4]: Plugin may be unstable
591 | 22.04.2020 15:51:54 | INFO | HOSTER FileStoreTo[4]: Grabbing link info...
592 | 22.04.2020 15:51:55 | INFO | HOSTER FileStoreTo[4]: Link name: Out.Of.Play.-.Der.Weg.zurueck.2020.PsO.part1.rar
593 | 22.04.2020 15:51:55 | INFO | HOSTER FileStoreTo[4]: Link size: 499.00 MiB (523239424 bytes)
594 | 22.04.2020 15:51:55 | INFO | HOSTER FileStoreTo[4]: Link status: online
595 | 22.04.2020 15:51:55 | INFO | HOSTER FileStoreTo[4]: Processing url: http://filestore.to/?d=8JNX8FDLEC
596 | 22.04.2020 15:51:55 | INFO | HOSTER FileStoreTo[4]: Looking for direct download link...
597 | 22.04.2020 15:51:55 | INFO | HOSTER FileStoreTo[4]: Direct download link not found
598 | 22.04.2020 15:51:55 | INFO | HOSTER FileStoreTo[4]: Checking for link errors...
599 | 22.04.2020 15:51:55 | INFO | HOSTER FileStoreTo[4]: No errors found
600 | 22.04.2020 15:51:55 | INFO | HOSTER FileStoreTo[4]: Processing as free download...
601 | 22.04.2020 15:51:55 | INFO | HOSTER FileStoreTo[4]: Checking for link errors...
602 | 22.04.2020 15:51:55 | INFO | HOSTER FileStoreTo[4]: Waiting 10 seconds...
603 | 22.04.2020 15:52:07 | INFO | HOSTER FileStoreTo[4]: No errors found
604 | 22.04.2020 15:52:07 | INFO | HOSTER FileStoreTo[4]: Checking for link errors...
605 | 22.04.2020 15:52:07 | INFO | HOSTER FileStoreTo[4]: No errors found
606 | 22.04.2020 15:52:07 | INFO | HOSTER FileStoreTo[4]: Downloading file...
607 | 22.04.2020 15:52:07 | WARNING | Download failed: Out.Of.Play.-.Der.Weg.zurueck.2020.PsO.part1.rar \| httpDownload() got an unexpected keyword argument 'size'

Nice regards

**Comment by GammaC0de** [comment]
Works fine for me, please update you pyload installtion using the instructions in https://github.com/pyload/pyload/issues/3283 and then retry.

**Comment by mcmikele** [comment]
Thank you for the tip. It worked :)

**Comment by GammaC0de** [comment]
👍
