### ISSUE TITLE
Add multiple files via api or links

### ISSUE THREAD

**Issue by Miosame** [pyload/pyload#3600]
Is there a way to add multiple `.torrent` files / "containers" to the queue? looking at the API it only ever mentions `links` and trying to add links with a `file://` path leads to `Illegal URL`.

**Comment by GammaC0de** [comment]
Just use the `HotFolder ` plugin.
Every torrent file you put in the hot folder would be put in the queue.

**Comment by Miosame** [comment]
Thanks! I'll test it out and close it, if it works.

**Comment by Miosame** [comment]
@GammaC0de it does not seem to pick them up after three times the interval, is there logs I could check for that specific plugin?

**Comment by GammaC0de** [comment]
Just "Added %s from HotFolder" message in the standard log

**Comment by Miosame** [comment]
@GammaC0de yep it was the read only flag, it was trying to delete them and was crashing - now one final question, is there a way to group those torrents into packages instead of having them download with thousands of different names? e.g. put them in a subfolder and it'll pick that up?

**Comment by GammaC0de** [comment]
Why would you want several torrents in the same folder?

**Comment by Miosame** [comment]
@GammaC0de for grouping them by package instead of filename

**Comment by GammaC0de** [comment]
torrents are containers, each software/movie/whatever is distributed with one torrent file.
What you are asking does not make sense to me.

**Comment by Miosame** [comment]
@GammaC0de maybe I don't realize how this is usually done? but I was thinking of grouping torrents into packages, just like with OCHs, so it would download into a folder named `series-name` instead of e.g. `filename.mkv`.

**Comment by GammaC0de** [comment]
The package name is taken from the toorent file, just try it and see

**Comment by Miosame** [comment]
@GammaC0de I know that's my issue, I wanted torrent files to be grouped into the same series name, instead of by filename, is that possible with hotfolder? by e.g. doing `series-name/torrentfile01.torrent` etc.

**Comment by GammaC0de** [comment]
Maybe you can use the 'package_finished` external script to move the directory

**Comment by Miosame** [comment]
@GammaC0de that would be near impossible, since the varying format of the filenames - do I understand that hotfolder can't handle putting files into packages by anything else than their filename?

**Comment by h4de5** [comment]
have a look at filebot's amc script - https://www.filebot.net/forums/viewtopic.php?t=215 it is "the" benchmark for renaming files.
