### ISSUE TITLE
Alldebrid is not working.

### ISSUE THREAD

**Issue by Merlincool** [pyload/pyload#3602]
This is the first time I am using this pyload on my vps which is headless unbuntu 18. I have installed pyload using AtoMic Toolkit script.

When ever I try to push in my uptobox link I don't see something going through alldebrid plugin rather it's going through uptobox free plugin.

`

1 | 24.04.2020 17:35:49 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
-- | -- | -- | --
2 | 24.04.2020 17:35:49 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
3 | 24.04.2020 17:35:49 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
4 | 24.04.2020 17:35:49 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
5 | 24.04.2020 17:35:49 | DEBUG | HOSTER UptoboxCom[3]: Plugin version: 0.36
6 | 24.04.2020 17:35:49 | DEBUG | HOSTER UptoboxCom[3]: Plugin status: testing
7 | 24.04.2020 17:35:49 | WARNING | HOSTER UptoboxCom[3]: Plugin may be unstable
8 | 24.04.2020 17:35:49 | INFO | HOSTER UptoboxCom[3]: Grabbing link info...
9 | 24.04.2020 17:35:49 | DEBUG | HOSTER UptoboxCom[3]: Link info: {'status': 2, 'hash': {}, 'name': u'Venom (2018) 1080p BluRay x264 Dual Audio [Hindi DD5.1 - English DD5.1] - ESUBS ~ Ranvijay.mkv', 'url': u'https://uptobox.com/u0ynogvc00r4', 'pattern': {'S': u'4.80', 'U': u'GB', 'N': u'Venom (2018) 1080p BluRay x264 Dual Audio [Hindi DD5.1 - English DD5.1] - ESUBS ~ Ranvijay.mkv'}, 'size': 5153960755}
10 | 24.04.2020 17:35:49 | DEBUG | HOSTER UptoboxCom[3]: Previous link info: {}
11 | 24.04.2020 17:35:49 | INFO | HOSTER UptoboxCom[3]: Link name: Venom (2018) 1080p BluRay x264 Dual Audio [Hindi DD5.1 - English DD5.1] - ESUBS ~ Ranvijay.mkv
12 | 24.04.2020 17:35:49 | INFO | HOSTER UptoboxCom[3]: Link size: 4.80 GiB (5153960755 bytes)
13 | 24.04.2020 17:35:49 | INFO | HOSTER UptoboxCom[3]: Link status: online
14 | 24.04.2020 17:35:49 | INFO | HOSTER UptoboxCom[3]: Processing url: https://uptobox.com/u0ynogvc00r4
15 | 24.04.2020 17:35:49 | INFO | HOSTER UptoboxCom[3]: Looking for direct download link...
16 | 24.04.2020 17:35:49 | DEBUG | HOSTER UptoboxCom[3]: LOAD URL https://uptobox.com/u0ynogvc00r4 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
17 | 24.04.2020 17:35:49 | INFO | HOSTER UptoboxCom[3]: Direct download link not found
18 | 24.04.2020 17:35:49 | DEBUG | HOSTER UptoboxCom[3]: LOAD URL https://uptobox.com/u0ynogvc00r4 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
19 | 24.04.2020 17:35:49 | INFO | HOSTER UptoboxCom[3]: Checking for link errors...
20 | 24.04.2020 17:35:49 | INFO | HOSTER UptoboxCom[3]: No errors found
21 | 24.04.2020 17:35:49 | INFO | HOSTER UptoboxCom[3]: Processing as free download...
22 | 24.04.2020 17:35:49 | DEBUG | HOSTER UptoboxCom[3]: LOAD URL https://uptobox.com/u0ynogvc00r4 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={'waitingToken': u"' type=", 'submit': 'Free Download'} \| ref=True \| just_header=False
23 | 24.04.2020 17:35:49 | INFO | HOSTER UptoboxCom[3]: Checking download...
24 | 24.04.2020 17:35:49 | WARNING | HOSTER UptoboxCom[3]: Free download failed \| Parse error: No file downloaded \| Plugin may be out of date
25 | 24.04.2020 17:35:49 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
26 | 24.04.2020 17:35:49 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
27 | 24.04.2020 17:35:49 | WARNING | Download failed: Venom (2018) 1080p BluRay x264 Dual Audio [Hindi DD5.1 - English DD5.1] - ESUBS ~ Ranvijay.mkv \| Parse error: No file downloaded \| Plugin may be out of date
28 | 24.04.2020 17:35:49 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
29 | 24.04.2020 17:35:49 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: Venom (2018) 1080p BluRay x264 Dual Audio [Hindi DD5.1 - English DD5.1] - ESUBS ~ Ranvijay.mkv (pid:3)
30 | 24.04.2020 17:35:49 | INFO | ADDON UnSkipOnFail: No duplicates found
31 | 24.04.2020 17:35:49 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
32 | 24.04.2020 17:35:49 | DEBUG | All downloads processed

`

Also what is Queue and Collector? And which one is better for quick download without waiting time.

https://i.postimg.cc/90snnJ0z/ad.png

**Comment by GammaC0de** [comment]
>  have installed pyload using AtoMic Toolkit script

From the image I can see you ave installed a very old version of pyload,

Please upgrade your installation using the instructions in https://github.com/pyload/pyload/issues/3283

**Comment by Merlincool** [comment]
> > have installed pyload using AtoMic Toolkit script
> 
> From the image I can see you ave installed a very old version of pyload,
> 
> Please upgrade your installation using the instructions in #3283

`

273 | 25.04.2020 06:27:13 | WARNING | HOSTER AlldebridCom[2]: AlldebridCom \| Premium download failed \| temp. offline
-- | -- | -- | --
274 | 25.04.2020 06:27:13 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
275 | 25.04.2020 06:27:13 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
276 | 25.04.2020 06:27:13 | INFO | Download restarted: af3436c2fa600c54d6fa08067f907473 \| Fallback to free processing
277 | 25.04.2020 06:27:13 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
278 | 25.04.2020 06:27:13 | DEBUG | All downloads processed
279 | 25.04.2020 06:27:13 | INFO | Download starts: af3436c2fa600c54d6fa08067f907473
280 | 25.04.2020 06:27:13 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
281 | 25.04.2020 06:27:13 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
282 | 25.04.2020 06:27:13 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
283 | 25.04.2020 06:27:13 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
284 | 25.04.2020 06:27:13 | DEBUG | HOSTER AlldebridCom[2]: AlldebridCom \| Plugin version: 0.60
285 | 25.04.2020 06:27:13 | DEBUG | HOSTER AlldebridCom[2]: AlldebridCom \| Plugin status: testing
286 | 25.04.2020 06:27:13 | WARNING | HOSTER AlldebridCom[2]: AlldebridCom \| Plugin may be unstable
287 | 25.04.2020 06:27:13 | INFO | HOSTER AlldebridCom[2]: AlldebridCom \| Grabbing link info...
288 | 25.04.2020 06:27:13 | DEBUG | HOSTER AlldebridCom[2]: AlldebridCom \| Link info: {'status': 7, 'hash': {}, 'name': u'af3436c2fa600c54d6fa08067f907473', 'url': u'https://rapidgator.net/file/af3436c2fa600c54d6fa08067f907473', 'pattern': {}, 'size': 0}
289 | 25.04.2020 06:27:13 | DEBUG | HOSTER AlldebridCom[2]: AlldebridCom \| Previous link info: {'status': 7, 'hash': {}, 'name': u'af3436c2fa600c54d6fa08067f907473', 'url': u'https://rapidgator.net/file/af3436c2fa600c54d6fa08067f907473', 'pattern': {}, 'size': 0}
290 | 25.04.2020 06:27:13 | INFO | HOSTER AlldebridCom[2]: AlldebridCom \| Link name: af3436c2fa600c54d6fa08067f907473
291 | 25.04.2020 06:27:13 | INFO | HOSTER AlldebridCom[2]: AlldebridCom \| Link size: N/D
292 | 25.04.2020 06:27:13 | INFO | HOSTER AlldebridCom[2]: AlldebridCom \| Link status: starting
293 | 25.04.2020 06:27:13 | INFO | HOSTER AlldebridCom[2]: AlldebridCom \| Processing url: https://rapidgator.net/file/af3436c2fa600c54d6fa08067f907473
294 | 25.04.2020 06:27:13 | INFO | HOSTER AlldebridCom[2]: AlldebridCom \| Checking for link errors...
295 | 25.04.2020 06:27:13 | WARNING | HOSTER AlldebridCom[2]: AlldebridCom \| No data to check
296 | 25.04.2020 06:27:13 | INFO | HOSTER AlldebridCom[2]: AlldebridCom \| Grabbing link info...
297 | 25.04.2020 06:27:13 | DEBUG | HOSTER AlldebridCom[2]: AlldebridCom \| Link info: {'status': 7, 'hash': {}, 'name': u'af3436c2fa600c54d6fa08067f907473', 'url': u'https://rapidgator.net/file/af3436c2fa600c54d6fa08067f907473', 'pattern': {}, 'size': 0}
298 | 25.04.2020 06:27:13 | DEBUG | HOSTER AlldebridCom[2]: AlldebridCom \| Previous link info: {'status': 7, 'hash': {}, 'name': u'af3436c2fa600c54d6fa08067f907473', 'url': u'https://rapidgator.net/file/af3436c2fa600c54d6fa08067f907473', 'pattern': {}, 'size': 0}
299 | 25.04.2020 06:27:13 | INFO | HOSTER AlldebridCom[2]: AlldebridCom \| Link name: af3436c2fa600c54d6fa08067f907473
300 | 25.04.2020 06:27:13 | INFO | HOSTER AlldebridCom[2]: AlldebridCom \| Link size: N/D
301 | 25.04.2020 06:27:13 | INFO | HOSTER AlldebridCom[2]: AlldebridCom \| Link status: starting
302 | 25.04.2020 06:27:13 | INFO | HOSTER AlldebridCom[2]: AlldebridCom \| Processing as free download...
303 | 25.04.2020 06:27:13 | WARNING | HOSTER AlldebridCom[2]: AlldebridCom \| Free download failed \| MultiHoster download failed
304 | 25.04.2020 06:27:13 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
305 | 25.04.2020 06:27:13 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
306 | 25.04.2020 06:27:13 | INFO | Download restarted: af3436c2fa600c54d6fa08067f907473 \| Revert to original hoster plugin
307 | 25.04.2020 06:27:13 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
308 | 25.04.2020 06:27:13 | DEBUG | All downloads processed
309 | 25.04.2020 06:27:13 | INFO | Download starts: af3436c2fa600c54d6fa08067f907473
310 | 25.04.2020 06:27:13 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
311 | 25.04.2020 06:27:13 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
312 | 25.04.2020 06:27:13 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
313 | 25.04.2020 06:27:13 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
314 | 25.04.2020 06:27:13 | DEBUG | HOSTER RapidgatorNet[2]: Plugin version: 0.55
315 | 25.04.2020 06:27:13 | DEBUG | HOSTER RapidgatorNet[2]: Plugin status: testing
316 | 25.04.2020 06:27:13 | WARNING | HOSTER RapidgatorNet[2]: Plugin may be unstable
317 | 25.04.2020 06:27:13 | INFO | HOSTER RapidgatorNet[2]: Grabbing link info...
318 | 25.04.2020 06:27:14 | DEBUG | HOSTER RapidgatorNet[2]: Link info: {'status': 2, 'hash': {u'MD5': u'9a93b12ae764a27a7aaf16dbe52f08a2'}, 'name': u'kbhtcfezdqy.part01.rar', 'url': u'https://rapidgator.net/file/af3436c2fa600c54d6fa08067f907473', 'pattern': {'S': u'999.99', 'U': u'MB', 'D': u'9a93b12ae764a27a7aaf16dbe52f08a2', 'H': u'MD5', 'ID': u'af3436c2fa600c54d6fa08067f907473', 'N': u'kbhtcfezdqy.part01.rar'}, 'size': 1048565514}
319 | 25.04.2020 06:27:14 | DEBUG | HOSTER RapidgatorNet[2]: Previous link info: {}
320 | 25.04.2020 06:27:14 | INFO | HOSTER RapidgatorNet[2]: Link name: kbhtcfezdqy.part01.rar
321 | 25.04.2020 06:27:14 | INFO | HOSTER RapidgatorNet[2]: Link size: 999.99 MiB (1048565514 bytes)
322 | 25.04.2020 06:27:14 | INFO | HOSTER RapidgatorNet[2]: Link status: online
323 | 25.04.2020 06:27:14 | INFO | HOSTER RapidgatorNet[2]: Processing url: https://rapidgator.net/file/af3436c2fa600c54d6fa08067f907473
324 | 25.04.2020 06:27:14 | INFO | HOSTER RapidgatorNet[2]: Looking for direct download link...
325 | 25.04.2020 06:27:14 | DEBUG | HOSTER RapidgatorNet[2]: LOAD URL https://rapidgator.net/file/af3436c2fa600c54d6fa08067f907473 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
326 | 25.04.2020 06:27:14 | INFO | HOSTER RapidgatorNet[2]: Direct download link not found
327 | 25.04.2020 06:27:14 | DEBUG | HOSTER RapidgatorNet[2]: LOAD URL https://rapidgator.net/file/af3436c2fa600c54d6fa08067f907473 \| redirect=True \| cookies=[('rapidgator.net', 'lang', 'en')] \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
328 | 25.04.2020 06:27:14 | INFO | HOSTER RapidgatorNet[2]: Checking for link errors...
329 | 25.04.2020 06:27:14 | WARNING | HOSTER RapidgatorNet[2]: Free download failed \| File can be downloaded by premium users only
330 | 25.04.2020 06:27:14 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
331 | 25.04.2020 06:27:14 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
332 | 25.04.2020 06:27:14 | WARNING | Download failed: kbhtcfezdqy.part01.rar \| File can be downloaded by premium users only
333 | 25.04.2020 06:27:14 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
334 | 25.04.2020 06:27:14 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: kbhtcfezdqy.part01.rar (pid:2)
335 | 25.04.2020 06:27:14 | INFO | ADDON UnSkipOnFail: No duplicates found
336 | 25.04.2020 06:27:14 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
337 | 25.04.2020 06:27:14 | DEBUG | All downloads processed

`

I have sucesssfully added stable version also myalldebrid has been added and it shows premium status

**Comment by GammaC0de** [comment]
> It seems My vps is banned, apart from rasing ticket to alldebrid support team,is there any alternative?

No, you have to talk to them.

Closing.
