### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by Merlincool** [pyload/pyload#3603]
### Your question

Do not understand where to start using vpn and how to configure and what all things to do like initialisation etc. I am sorry but did not have any idea what all to do.

It is not tha simple like explained in previous tickets, I have open vpn config how to enter in pyload configuration? Also there is no prompt for entering configuration details.

**Comment by GammaC0de** [comment]
pyLoad does not support OpenVPN, you will have to do is on the OS level.
It supports using HTTP/Socks4/Socks5 proxy though.
