### ISSUE TITLE
YouTube download / age verification

### ISSUE THREAD

**Issue by 7k0l4n5k1** [pyload/pyload#3604]
### YouTube download / age verification

hello,
i use pyload 4.20 and it works very well. but last time i got an issue during download a YouTube video. there is an age verification. i didnt find a solution to store my YouTube account in section administration or plugins. how can i fix it?
thank you very much

### Additional references

26.04.2020 14:06:52 | INFO | Download starts: watch
-- | -- | --
601 | 26.04.2020 14:06:52 | WARNING | HOSTER YoutubeCom[142]: Plugin may be unstable
602 | 26.04.2020 14:06:52 | INFO | HOSTER YoutubeCom[142]: Grabbing link info...
603 | 26.04.2020 14:06:52 | INFO | HOSTER YoutubeCom[142]: Link name: watch
604 | 26.04.2020 14:06:52 | INFO | HOSTER YoutubeCom[142]: Link size: N/D
605 | 26.04.2020 14:06:52 | INFO | HOSTER YoutubeCom[142]: Link status: starte
606 | 26.04.2020 14:06:52 | INFO | HOSTER YoutubeCom[142]: Processing url: https://www.youtube.com/watch?v=f4x_1oonQUA
607 | 26.04.2020 14:06:53 | ERROR | HOSTER YoutubeCom[142]: "reason":"Sign in to confirm your age
608 | 26.04.2020 14:06:53 | WARNING | HOSTER YoutubeCom[142]: Free download failed \| offline
609 | 26.04.2020 14:06:53 | WARNING | Download is offline: watch

**Comment by GammaC0de** [comment]
Adding login support is not planed support just few file downloads, 

You can try using https://github.com/ytdl-org/youtube-dl
