### ISSUE TITLE
Uptobox login failed

### ISSUE THREAD

**Issue by Merlincool** [pyload/pyload#3609]
### Your question

I used this post https://github.com/pyload/pyload/issues/3602 and as recommended I had update my pyload.

I logged in as USER:PASS but did not work,so I read following article.

I am taking this into consideration and trying 
https://www.nas-forum.com/forum/topic/44084-r%C3%A9solufichier-host-uptobox-host-file-uptobox/

I used user:pass - tokenn:token_key_copied_from_account.

Nothing worked.

So how to login in my account. Sorry this is my first time dealing with pyload.

**Comment by GammaC0de** [comment]
User = your  Alldebrid user
Pass = token generated with https://github.com/pyload/pyload/files/4489732/GetAlldebridTokenV4.zip

**Comment by Merlincool** [comment]
> User = your Alldebrid user
> Pass = token generated with https://github.com/pyload/pyload/files/4489732/GetAlldebridTokenV4.zip

This I have already done, I was asking about UPTOBOX login, I have premium account for same

**Comment by GammaC0de** [comment]
If I recall right, Alldebrid has already support for UPTOBOX, no?
If so, why do you also need a UPTOBOX account?

> I logged in as USER:PASS but did not work

Please enable debug mode, retry logging in and downloading and then post the logs here.

if you like, you can set your account to a temporary password and then send account user and password to nitzo2001 at yahoo dot com so I can check here.

**Comment by Merlincool** [comment]
As I told you earlier, alldebrid bans dedicated IP and vps. How on earth some one can use vps? Is that even possible to use? And if then tell me how. I tried like I have said https://github.com/pyload/pyload/issues/3602. But shows me ip ban/rejected.

Is there a way to use it on a vps? Just let me know the directions.

If this works well then I don't have to use uptobox account anyways, I can use alldebrid whole day.

**Comment by GammaC0de** [comment]
I understand you ar upset, but how can you tell you are banned? form pyLoad's log?
(You did not post any logs here so I cannot tel)

If you are an alldebrid paying customer, alldebrid should not care whether you use your account from a vps or from the moon, I suggest you contact their support (remember to include the vps's IP) and ask them to unban your IP.

**Comment by GammaC0de** [comment]
No response, closing.
