### ISSUE TITLE
Plugin PremiumizeMe not found

### ISSUE THREAD

**Issue by jbman11** [pyload/pyload#3610]
In my logs I am seeing this about the plugin not found

138 | 29.04.2020 18:11:57 | DEBUG | Plugin PremiumizeMe not found
-- | -- | -- | --
139 | 29.04.2020 18:11:57 | DEBUG | Available plugins : {'LinkdecrypterComHook': {'user': False, 'name': 'LinkdecrypterComHook', 'v': 1.11}, 'AppriseNotify': {'user': False, 'name': 'AppriseNotify', 'v': 0.01}, 'XMPP': {'user': False, 'name': 'XMPP', 'v': 0.22}, 'PushOver': {'user': False, 'name': 'PushOver', 'v': 0.07}, 'LinkFilter': {'user': False, 'name': 'LinkFilter', 'v': 0.16}, 'AntiVirus': {'user': False, 'name': 'AntiVirus', 'v': 0.22}, 'UpdateManager': {'user': False, 'name': 'UpdateManager', 'v': 1.21}, 'MergeFiles': {'user': False, 'name': 'MergeFiles', 'v': 0.24}, 'ImageTyperz': {'user': False, 'name': 'ImageTyperz', 'v': 0.15}, 'DeleteFinished': {'user': False, 'name': 'DeleteFinished', 'v': 1.19}, 'DeathByCaptcha': {'user': False, 'name': 'DeathByCaptcha', 'v': 0.17}, 'RestartFailed': {'user': False, 'name': 'RestartFailed', 'v': 1.65}, 'EventMapper': {'module': , 'user': False, 'name': 'EventMapper', 'v': 0.02}, 'BypassCaptcha': {'user': False, 'name': 'BypassCaptcha', 'v': 0.14}, 'ExternalScripts': {'module': , 'user': False, 'name': 'ExternalScripts', 'v': 0.75}, 'Captcha9Kw': {'user': False, 'name': 'Captcha9Kw', 'v': 0.4}, 'AntiStandby': {'user': False, 'name': 'AntiStandby', 'v': 0.18}, 'ClickNLoad': {'user': False, 'name': 'ClickNLoad', 'v': 0.61}, 'UnSkipOnFail': {'module': , 'user': False, 'name': 'UnSkipOnFail', 'v': 0.14}, 'DownloadScheduler': {'user': False, 'name': 'DownloadScheduler', 'v': 0.3}, 'HotFolder': {'user': False, 'name': 'HotFolder', 'v': 0.26}, 'Checksum': {'user': False, 'name': 'Checksum', 'v': 0.35}, 'ExtractArchive': {'user': False, 'name': 'ExtractArchive', 'v': 1.69}, 'LogMarker': {'user': False, 'name': 'LogMarker', 'v': 0.08}, 'TransmissionRPC': {'user': False, 'name': 'TransmissionRPC', 'v': 0.19}, 'AndroidPhoneNotify': {'user': False, 'name': 'AndroidPhoneNotify', 'v': 0.16}, 'CloudFlareDdos': {'user': False, 'name': 'CloudFlareDdos', 'v': 0.16}, 'IRC': {'user': False, 'name': 'IRC', 'v': 0.28}, 'JustPremium': {'user': False, 'name': 'JustPremium', 'v': 0.27}, 'MultiHome': {'user': False, 'name': 'MultiHome', 'v': 0.21}, 'XFileSharing': {'user': False, 'name': 'XFileSharing', 'v': 0.56}, 'ExpertDecoders': {'user': False, 'name': 'ExpertDecoders', 'v': 0.14}, 'WindowsPhoneNotify': {'user': False, 'name': 'WindowsPhoneNotify', 'v': 0.18}, 'PushBullet': {'user': False, 'name': 'PushBullet', 'v': 0.05}, 'UserAgentSwitcher': {'user': False, 'name': 'UserAgentSwitcher', 'v': 0.18}, 'DiscordNotifier': {'user': False, 'name': 'DiscordNotifier', 'v': 0.1}, 'SkipRev': {'user': False, 'name': 'SkipRev', 'v': 0.38}}

Under accounts my premium account is showing ok and valid

If I take a look in the hoster folder I can see the Premiumizeme.py file there version 0.33

I just blew everything away for a new install just in case with the same error

Thanks in advance

**Comment by jbman11** [comment]
Something else I have noticed


264 | 29.04.2020 18:53:15 | DEBUG | HOSTER BasePlugin[369]: Plugin version: 0.52
-- | -- | -- | --
265 | 29.04.2020 18:53:15 | DEBUG | HOSTER BasePlugin[369]: Plugin status: testing
266 | 29.04.2020 18:53:15 | WARNING | HOSTER BasePlugin[369]: Plugin may be unstable
267 | 29.04.2020 18:53:15 | DEBUG | HOSTER BasePlugin[369]: Config option `use_premium` not found, use default `True`
268 | 29.04.2020 18:53:15 | INFO | HOSTER BasePlugin[369]: Grabbing link info...

**Comment by jbman11** [comment]
I also noticed this in my logs

347 | 29.04.2020 19:44:33 | DEBUG | HOSTER BasePlugin[371]: Plugin version: 0.52
348 | 29.04.2020 19:44:33 | DEBUG | HOSTER BasePlugin[371]: Plugin status: testing
349 | 29.04.2020 19:44:33 | WARNING | HOSTER BasePlugin[371]: Plugin may be unstable
350 | 29.04.2020 19:44:33 | DEBUG | HOSTER BasePlugin[371]: Config option `use_premium` not found, use default `True`
351 | 29.04.2020 19:44:33 | INFO | HOSTER BasePlugin[371]: Grabbing link info...

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Is this a new installation?

Please provide all the relevant log, not just one line..

**Comment by jbman11** [comment]
> nitzo2001 at yahoo dot com.

Sent as requested.

Thank you

**Comment by jbman11** [comment]
> Is this a new installation?
> 
> Please provide all the relevant log, not just one line..

Old install nothing new. I did try a new install as well with the same issues.

**Comment by GammaC0de** [comment]
Please send username and password, not just userid and token

**Comment by GammaC0de** [comment]
Also, what URL you were trying to download?

**Comment by jbman11** [comment]
> Also, what URL you were trying to download?

If I go into the config and pick premiumize make any change to the config and press save I see the initial error about the plugin not found. 

At this stage ignore about what I said about the download as it appears that there were some issues with the premium service a few days ago which might have been an issue. 

My concern at the moment is the error I see in the logs about the plugin is not found. If this isn’t an issue no problem please feel free to close the ticket.

**Comment by GammaC0de** [comment]
> Old install nothing new. I did try a new install as well with the same issues.

>If I go into the config and pick premiumize make any change to the config and press save I see the initial error about the plugin not found.


Then try to update your  pyLoad installation using the instruction in #3283 and then retry.

**Comment by jbman11** [comment]
Tried that method and also a git clone with the same issue. 

Is there a place that lists all those plugins? The log that shows 

DEBUG | Available plugins

With premiumize missing so I wanted to check if my list is missing it.

**Comment by GammaC0de** [comment]
All plugins are here: https://github.com/pyload/pyload/tree/stable/module/plugins

**Comment by jbman11** [comment]
Ok so I can see them in the folder locally which is the same as on git.  Is there a reference list that pyload calls or does it read that folder and create the list from there?

**Comment by jbman11** [comment]
More testing, more confusing. Links are downloading ok with no issues, however it still says that the plugin is not found.

It’s working so I am going to close this ticket as there isn’t an issue with the downloading as such just the error noted in the logs.

Cheers


73 | 01.05.2020 18:16:48 | INFO | Download starts: https://clicknupload.co/
-- | -- | -- | --
74 | 01.05.2020 18:16:48 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
75 | 01.05.2020 18:16:48 | DEBUG | HOSTER PremiumizeMe[377]: PremiumizeMe \| Plugin version: 0.33
76 | 01.05.2020 18:16:48 | DEBUG | HOSTER PremiumizeMe[377]: PremiumizeMe \| Plugin status: testing
77 | 01.05.2020 18:16:48 | WARNING | HOSTER PremiumizeMe[377]: PremiumizeMe \| Plugin may be unstable
78 | 01.05.2020 18:16:48 | INFO | ACCOUNT PremiumizeMe: Grabbing account info for user `763*******`...
79 | 01.05.2020 18:16:48 | DEBUG | ACCOUNT PremiumizeMe: LOAD URL https://www.premiumize.me/api/account/info \| redirect=True \| cookies=True \| get={'apikey': '**********'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
