### ISSUE TITLE
ddl.to - Link processed as a html file

### ISSUE THREAD

**Issue by BlubBlubBlu** [pyload/pyload#3612]
### Describe the problem

If i load with a URL from ddownload its all working ok.
If i load with a URL from ddl.to the Plugin load only a small hmtl file, and save it with the Name from the Archiv xxxx.rar. :-(

if I manually change the url of every single file from dddl.to to ddownload.com then it works.
There's a bug somewhere

Thanks for help, and sorry for my bad english :)

### Debug log

29.04.2020 17:23:27 INFO      Download starts: https://ddl.to/xxxxx
29.04.2020 17:23:27 WARNING   HOSTER XFileSharing[808]: DdlTo | Plugin may be unstable
29.04.2020 17:23:27 INFO      ACCOUNT DdlTo: Grabbing account info for user `xxxxxxx`...
29.04.2020 17:23:27 INFO      HOSTER XFileSharing[808]: DdlTo | Grabbing link info...
29.04.2020 17:23:27 INFO      HOSTER XFileSharing[808]: DdlTo | Link name: xxxxx.rar
29.04.2020 17:23:27 INFO      HOSTER XFileSharing[808]: DdlTo | Link size: N/D
29.04.2020 17:23:27 INFO      HOSTER XFileSharing[808]: DdlTo | Link status: online
29.04.2020 17:23:27 INFO      HOSTER XFileSharing[808]: DdlTo | Processing url: https://ddl.to/xxxxxxxxx
29.04.2020 17:23:27 INFO      HOSTER XFileSharing[808]: DdlTo | Looking for direct download link...
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | Direct download link not found
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | Checking for link errors...
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | No errors found
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | Processing as premium download...
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | Checking for link errors...
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | No errors found
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | Downloading file...
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | File saved
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | Checking download...
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | File is OK
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | Checking file (with built-in rules)...
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | Checking file (with custom rules)...
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | Checking for link errors...
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | No errors found
29.04.2020 17:23:28 INFO      HOSTER XFileSharing[808]: DdlTo | No errors found
29.04.2020 17:23:28 INFO      Download finished: xxxxxxx.rar
29.04.2020 17:23:28 INFO      Package finished: ST2 

```

```

**Comment by GammaC0de** [comment]
Please disable XFileSharing plugin and re-add the URL

**Comment by BlubBlubBlu** [comment]
if i disabled the XFileSharing plugin it works
thank you very, very much!

**Comment by GammaC0de** [comment]
👍
