### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by Gatewayy** [pyload/pyload#3613]
### Describe the problem

The readme does not contain the correct default login info.

From https://github.com/pyload/pyload/blob/master/README.md:

Web Interface

Open your web browser and visit the url http://localhost:8001 to have access to the pyLoad's web interface.

    Default username: pyload.
    Default password: pyload.

the correct information is admin / password.

### Debug log

```
N/A
```

### Screenshots

N/A

### Additional references

N/A

**Comment by GammaC0de** [comment]
@Gatewayy Thanks for notifying,
Fixed the default config file because 8000 is the correct value.
