### ISSUE TITLE
how works plugins "AndroidPhoneNotify"

### ISSUE THREAD

**Issue by juankaxxi** [pyload/pyload#3617]
Hello, I would like to know how the "Androidphonenotify" plugin works, since the website www.notifymyandroid.com does not work.

Thank you!!!

**Comment by GammaC0de** [comment]
As you said, unfortunately www.notifymyandroid.com has shut down it's services.
We have removed `AndroidPhoneNotify `from the plugin list, thanks for reporting.

You can use one of the other notification services instead: `PushBullet`, `PushOver` or AppriseNotify`.

With `AppriseNotify`, you can even configure multiple notification detonations and it supports many notification services.

**Comment by juankaxxi** [comment]
Ok, thanks!!!!
