### ISSUE TITLE
DDL.to - ddownload.com Plugin

### ISSUE THREAD

**Issue by Praevision** [pyload/pyload#3618]
### Describe the problem

I'm trying to use ddownload.com (premium), former ddl.to, for download. The account can be added, the remaining traffic is also shown properly. But the downloaded files are only 12KB no matter what files I want to download. Propably the change from ddl.to to ddownload.com corrupted the plugin?

### Debug log

```
02.05.2020 13:54:07 | INFO | HOSTER XFileSharing[50]: DdlTo \| Grabbing link info...
-- | -- | --
197 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| Link name: XXX.part01.rar
198 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| Link size: N/D
199 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| Link status: online
200 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| Processing url: https://ddl.to/XXX
201 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| Looking for direct download link...
202 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| Direct download link not found
203 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| Checking for link errors...
204 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| No errors found
205 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| Processing as premium download...
206 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| Checking for link errors...
207 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| No errors found
208 | 02.05.2020 13:54:08 | INFO | HOSTER XFileSharing[50]: DdlTo \| Downloading file...

02.05.2020 13:54:09 | INFO | HOSTER XFileSharing[50]: DdlTo \| File saved
-- | -- | --
210 | 02.05.2020 13:54:09 | INFO | HOSTER XFileSharing[50]: DdlTo \| Checking download...
211 | 02.05.2020 13:54:09 | INFO | HOSTER XFileSharing[50]: DdlTo \| File is OK
212 | 02.05.2020 13:54:09 | INFO | HOSTER XFileSharing[50]: DdlTo \| Checking file (with built-in rules)...
213 | 02.05.2020 13:54:09 | INFO | HOSTER XFileSharing[50]: DdlTo \| Checking file (with custom rules)...
214 | 02.05.2020 13:54:09 | INFO | HOSTER XFileSharing[50]: DdlTo \| Checking for link errors...
215 | 02.05.2020 13:54:09 | INFO | HOSTER XFileSharing[50]: DdlTo \| No errors found
216 | 02.05.2020 13:54:09 | INFO | HOSTER XFileSharing[50]: DdlTo \| No errors found
217 | 02.05.2020 13:54:09 | INFO | Download finished: XXX.part01.rar


```

**Comment by GammaC0de** [comment]
Please disable XFileSharing plugin and then retry.

**Comment by Praevision** [comment]
that did the trick, thank you!

**Comment by kabelclown** [comment]
Unfortunately this did not resolve the same issue for me:

<pre>
623 | 14.05.2020 15:25:16 | CRITICAL | 'NoneType' object has no attribute 'group'
-- | -- | -- | --
624 | ? | ? | Traceback (most recent call last):
625 | ? | ? | File "/app/pyload/module/ThreadManager.py", line 269, in assignJob
626 | ? | ? | job.initPlugin()
627 | ? | ? | File "/app/pyload/module/utils.py", line 169, in new
628 | ? | ? | return func(*args)
629 | ? | ? | File "/app/pyload/module/PyFile.py", line 103, in initPlugin
630 | ? | ? | self.plugin = self.pluginclass(self)
631 | ? | ? | File "/app/pyload/module/plugins/internal/Base.py", line 99, in __init__
632 | ? | ? | self.init()
633 | ? | ? | File "/app/pyload/module/plugins/hoster/XFileSharing.py", line 38, in init
634 | ? | ? | self.pyfile.url).group("DOMAIN").lower()
635 | ? | ? | AttributeError: 'NoneType' object has no attribute 'group'
636 | 14.05.2020 15:25:18 | CRITICAL | 'NoneType' object has no attribute 'group'
637 | ? | ? | Traceback (most recent call last):
638 | ? | ? | File "/app/pyload/module/ThreadManager.py", line 269, in assignJob
639 | ? | ? | job.initPlugin()
640 | ? | ? | File "/app/pyload/module/utils.py", line 169, in new
641 | ? | ? | return func(*args)
642 | ? | ? | File "/app/pyload/module/PyFile.py", line 103, in initPlugin
643 | ? | ? | self.plugin = self.pluginclass(self)
644 | ? | ? | File "/app/pyload/module/plugins/internal/Base.py", line 99, in __init__
645 | ? | ? | self.init()
646 | ? | ? | File "/app/pyload/module/plugins/hoster/XFileSharing.py", line 38, in init
647 | ? | ? | self.pyfile.url).group("DOMAIN").lower()
648 | ? | ? | AttributeError: 'NoneType' object has no attribute 'group'
</pre>

Im running the linuxserver.io pyload docker image, is that maybe a permission problem I need to open as issue over there?
