### ISSUE TITLE
Call to API statusServer results in HTTP 500 error

### ISSUE THREAD

**Issue by h4de5** [pyload/pyload#3622]
### Describe the problem

API calls to latest (stable) docker image results in an HTTP 500 Status error. 

I am using docker images from the hub: https://hub.docker.com/r/linuxserver/pyload/tags

the last working image: 

> linuxserver/pyload:9ea07eef-ls20 _ buildtime: 2:01pm

afterwards (including the latest one) the example code below no longer works:

> linuxserver/pyload:344086b9-ls20 _ buildtime: 4:58pm

unfortunately I cannot narrow it down exactly but it looks like the commit https://github.com/pyload/pyload/commit/2e9272ab8112157814310e0e517bf3bf3e4cae01 for fixing #3578 is responsible for this.

### Debug log

The docker logs show the follow error message:

```
/app/pyload/module/web/api_app.py:65: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  return HTTPError(500, json.dumps({"error": e.message, "traceback": format_exc()}))
Traceback (most recent call last):
  File "/app/pyload/module/web/api_app.py", line 62, in call_api
    return callApi(func, *args, **kwargs)
  File "/app/pyload/module/web/api_app.py", line 74, in callApi
    **dict([(x, literal_eval(y)) for x, y in kwargs.iteritems()]))
  File "/app/pyload/module/lib/SafeEval.py", line 44, in const_eval
    c = test_expr(expr, _const_codes)
  File "/app/pyload/module/lib/SafeEval.py", line 33, in test_expr
    raise ValueError, "%s is not a valid expression" % expr
ValueError:  is not a valid expression
```

### Additional references

Exampe script:

```python 
"""testing pyload api."""
import requests
from requests.packages.urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

username = "admin"
password = "****"
url = "https://****:8001/api/"
payload = {"username": username, "password": password}
login = requests.post(
    "{}{}".format(url, "login"), data=payload, timeout=5, verify=False)
print(login.cookies)

payload = {"method": "speed"}
response = requests.post(
    "{}{}".format(url, "statusServer"),
    json=payload,
    cookies=login.cookies,
    timeout=5,
    verify=False
)
print(response)
response.raise_for_status()
print(response.json())

```

**Comment by h4de5** [comment]
results of the script:
```
$ python3 pyload-test.py
<RequestsCookieJar[<Cookie beaker.session.id=42e9****161a for ****/>]>
{'speed': 0, 'total': 5, 'active': 0, 'pause': False, 'queue': 3, 'reconnect': True, 'download': True}
```
and:
```
$ python3 pyload-test.py
<RequestsCookieJar[<Cookie beaker.session.id=bc82****6486 for ****/>]>
<Response [500]>
Traceback (most recent call last):
  File "pyload-test.py", line 24, in <module>
    response.raise_for_status()
  File "****/python3.5/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://****:8001/api/statusServer
```

**Comment by GammaC0de** [comment]
What happens if you chage `"error": e.message` to `"error": e.args[0]`?

Does this issue exists when turning SSL off also?

**Comment by h4de5** [comment]
changed line 113 in api_app.py to:

```python
return HTTPError(500, json.dumps({"error": e.args[0], "traceback": format_exc()}))
```

and the example script to:
```python
print(response)
# response.raise_for_status()
print(response.text)
```

and now I get the html source of the pyload page ?!

yes - some problem without ssl enabled.

**Comment by treysis** [comment]
I get a similar error if I roll back the changes. Weirdly, just visiting `serverStatus` works. But asking for `"method": "speed"` causes the error.
Maybe it has got to do with fixing some of the unicode errors?

**Comment by treysis** [comment]
What is `payload = {"method": "speed"}` supposed to mean or do? If I leave that line out, the script runs just fine.

**Comment by GammaC0de** [comment]
`statusServer()` does not accept arguments: https://github.com/pyload/pyload/blob/stable/module/Api.py#L220

**Comment by treysis** [comment]
That's what I thought. So I presume first and second script are different. Cause I get the same error if I run the listed script against the older pyLoad.

**Comment by h4de5** [comment]
Mmh. I based the script on the pyload integration of home-assistant: 
https://github.com/home-assistant/core/blob/e7b9cecec9e3a2d2e2562dd7a454fef41f8dfa84/homeassistant/components/pyload/sensor.py#L149

At least that parameter is there since a while already. Also that integration worked with the previous docker build.

But i'll have a look without it and make a PR into home-assistant if it works.

**Comment by GammaC0de** [comment]
Some info you have to know about the API:
* data is sent as `application/x-www-form-urlencoded` and received as `application/json` (weird but that's the way it is)
* Parameters are formatted as: ` {"arg1": "py_expr1", ...}`
`arg1` is obviously the name of the parameter .
`py_expr1` is python expression that can be evaluated to a value, this result world be `arg1`'s value.
For example ` {"arg1": "1+1"}` would send an argument named `arg1` withe the value of 2.
If you want to send a string as a value that would be ` {"arg1": "'singe quoted string'"}`

Example for call with parameters:
```
"""testing pyload api."""
import requests
from requests.packages.urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

username = "admin"
password = "****"
url = "https://****:8001/api/"
payload = {"username": username, "password": password}
login = requests.post(
    "{}{}".format(url, "login"),
    headers={'Content-Type':"application/x-www-form-urlencoded"},
    data=payload,
    timeout=5,
    verify=False)
print(login.cookies)

payload = {"offset": 20}
response = requests.post(
    "{}{}".format(url, "getLog"),
    data=payload,
    cookies=login.cookies,
    timeout=5,
    verify=False,
    headers={'Content-Type':"application/x-www-form-urlencoded"}
)
print(response)
response.raise_for_status()
print(response.json())
```

**Comment by h4de5** [comment]
tested it without the parameters/payload - works as expected. Issue can be closed.
I'll go forward and create a PR on home-assistant.

one more question: is the API handling and the parameters related to the webserver selection (builtin, threaded, fastcgi or lightweight)? Cause I have only tested threaded so far.

thanks again for the explaination!

**Comment by GammaC0de** [comment]
One comment:
the speed that is returned by pyLoad is in bytes/s, so I think (not sure how home-assistant) this should be DATA_RATE_BYTES_PER_SECOND,  no?

**Comment by h4de5** [comment]
it devides it by `/ 2 ** 20` to convert it to MB/s - so it fits:
> "speed": 51163.321888841696
![image](https://user-images.githubusercontent.com/6115324/81128443-88439c80-8f41-11ea-9821-e6d449e73728.png)

**Comment by GammaC0de** [comment]
👍
