### ISSUE TITLE
Apprise notifications bug?

### ISSUE THREAD

**Issue by juankaxxi** [pyload/pyload#3625]
Hi, I have tested the plugin "Apprise Notification" and yop I think it needs a code review.

From the openwrt command line it works.

I do not understand programming but I think that the lines of the file "AppriseNotify.py" are wrong according to the web.

**On "AppriseNotify.py":**
      import apprise
        apprise_obj = apprise.Apprise()
        apprise_config = apprise.AppriseConfig()
        for c in key:
            apprise_config.add(c)
        apprise_obj.add(apprise_config)
        apprise_obj.notify(title=self.config.get("title"),
                           body="%s: %s" % (event, msg) if msg else event)

**On WEB:**
import apprise
apobj = apprise.Apprise()
apobj.add('json://localhost/tagA/', tag="TagA")
# Add 2 tags by string; the comma and/or space auto delimit
# our entries (spaces and comma's are ignored):
apobj.add('json://localhost/tagAB/', tag="TagA, TagB")
# Add 2 tags using a list; this works with tuples and sets too!
apobj.add('json://localhost/tagCD/', tag=["TagC", "TagD"])

WEB:
https://github.com/caronc/apprise/wiki/Development_API

Thanks

**Comment by GammaC0de** [comment]
Sorry but I could not understand what you are trying to say..

**Comment by juankaxxi** [comment]
![IMG_20200505_172424](https://user-images.githubusercontent.com/45994412/81083826-57d61100-8ef5-11ea-85e0-f36ff192acf9.jpg)

**Comment by juankaxxi** [comment]
Its no the same command line

**Comment by GammaC0de** [comment]
You have to specify configuration file(s) (see https://github.com/caronc/apprise/wiki/config_yaml and
https://github.com/caronc/apprise/wiki/config_text) for the plugin to work with.
![Capture](https://user-images.githubusercontent.com/11036551/81105962-73eda880-8f1d-11ea-9b07-261ffe71f1ad.PNG)

**Comment by juankaxxi** [comment]
Thanks to a friend I already have the solution for notifications to telegram:

1.- You have to create a file in the root folder of pyload, for example "apprise.conf" and inside you paste the telegram line "tgram: /// 123456789: abcdefg_hijklmnop / 12315544 /"

2.- You go config -> plugins -> Apprise Notify and in the box "Configuration (s) path / URL (comma separated):" you must put the full path of the file previously created.

3.- The service is already working, you will receive telegram messages !!!.

I leave the configuration page to create the telegram line in case anyone is interested.

https://github.com/caronc/apprise/wiki/Notify_telegram


Regards.

**Comment by GammaC0de** [comment]
👍
