### ISSUE TITLE
DDL.to premium does not download automatically

### ISSUE THREAD

**Issue by godfuture** [pyload/pyload#3631]
### Describe the problem
Downloading with DDL.to premium does not work anymore. Accounts page shows "invalid" for DDL premium account state. When adding links to pyload, I am asked to enter captcha, even I am using premium.

### Debug log
I have updated the docker container and done a restart to update plugins.

1034 | 09.05.2020 02:26:23 | INFO | starte pyLoad 0.4.20
-- | -- | -- | --
1035 | 09.05.2020 02:26:23 | INFO | Benutze Home-Verzeichnis: /config
1036 | 09.05.2020 02:26:23 | INFO | Aktivierte Plugins: ClickNLoad, EventMapper, ExternalScripts,  ExtractArchive, HotFolder, UnSkipOnFail, UpdateManager,  UserAgentSwitcher, XFileSharing
1037 | 09.05.2020 02:26:23 | INFO | Deaktivierte Plugins: AntiStandby, AntiVirus, AppriseNotify,  BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha,  DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, IRC,  ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker,  MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev,  TransmissionRPC, WindowsPhoneNotify, XMPP
1038 | 09.05.2020 02:26:23 | INFO | Downloadzeit: True
1039 | 09.05.2020 02:26:23 | INFO | Starte ThriftBackend: 0.0.0.0:7227
1040 | 09.05.2020 02:26:23 | INFO | Freier Speicher: 673.69 GiBGB
1041 | 09.05.2020 02:26:23 | INFO | Aktiviere Accounts...
1042 | 09.05.2020 02:26:24 | INFO | Starting threaded webserver: :::8000
1043 | 09.05.2020 02:26:24 | INFO | ACCOUNT DdlTo: Adding user `c*******`...
1044 | 09.05.2020 02:26:24 | INFO | ACCOUNT DdlTo: Login user `c*******`...
1045 | 09.05.2020 02:26:28 | ERROR | ACCOUNT DdlTo: Could not login user `c*******` \| Bad server response: 503 Service Unavailable

**Comment by godfuture** [comment]
Cloudflare seems to be the difference here. Will it be possible to make it cloudflare compatible?

**Comment by GammaC0de** [comment]
> Cloudflare seems to be the difference here. 

You are right about that.

> Will it be possible to make it cloudflare compatible?

It's not so simple, it may require major changes to pyLoad.
I will do my best.

**Comment by godfuture** [comment]
On pyload start and when committing account info in settings page, I get timeout during connection to ddl. Is this plugin supposed to work? No pressure here, but just trying to manage my expectation, because it worked for quite a time.

ERROR | ACCOUNT DdlTo: Could not login user `xxx*******` \| (28, 'Connection timed out after 30000 milliseconds')
-- | --

Has the server url changed such that the plugin is simply outdated? Or is it the google captcha that breaks things? I noticed there is no need of captcha when being logged in at ddl for download via browser. Therefore I guess ddl will work again once login succeeded...

**Comment by godfuture** [comment]
Connection timeout occured due to proxy. Without proxy I get:

651 | 04.08.2020 01:28:47 | ERROR | ACCOUNT DdlTo: Could not login user `xxx*******` \| Bad server response: 500 Internal Server Error
-- | -- | -- | --

**Comment by GammaC0de** [comment]
@godfuture  Why pay 50eur to DdlTo for 6 month if you can buy a real-debrid account for 16eur and get many more hosters and a stable service?

**Comment by godfuture** [comment]
> 
> 
> @godfuture Why pay 50eur to DdlTo for 6 month if you can buy a real-debrid account for 16eur and get many more hosters and a stable service?

This means you can recommand this service? I do not know it.

**Comment by GammaC0de** [comment]
> This means you can recommand this service? I do not know it.

I can safely recommend [real-debrid](https://real-debrid.com/premium),
It is a well known multi-hoster that pyload has support for it.
You get many more hosters besides `DdlTo` plus you also get torrent downloading with pyload via real-debrid (so your IP is not exposed when downloading torrents).

**Comment by GammaC0de** [comment]
05.08.2020 20:41:37 DEBUG     ACCOUNT RealdebridCom: Hoster list for user `ZYF*******`: [u'alfafile.net', u'anzfile.net', u'bayfiles.com', u'clicknupload.me', u'clipwatching.com', u'dailymotion.com', u'ddownload.com', u'depositfiles.com', u'dropapk.to', u'filefactory.com', u'filerio.com', u'fourshared.com', u'free.fr', u'gigapeta.com', u'google.com', u'hitfile.net', u'hulkshare.com', u'inclouddrive.com', u'isra.cloud', u'mediafire.com', u'mega.co.nz', u'mixdrop.co', u'nitroflare.com', u'oboom.com', u'onefichier.com', u'rapidgator.net', u'redtube.com', u'scribd.com', u'sendspace.com', u'sky.fm', u'solidfiles.com', u'soundcloud.com', u'turbobit.net', u'tusfiles.com', u'ulozto.net', u'unibytes.com', u'uploaded.to', u'uptobox.com', u'userscloud.com', u'usersdrive.com', u'vidlox.tv', u'vidoza.net', u'vimeo.com', u'wipfiles.net', u'wupfile.com', u'youporn.com', u'youtube.com', u'zippyshare.com']

**Comment by godfuture** [comment]
> You get many more hosters besides `DdlTo` plus you also get torrent downloading with pyload via real-debrid (so your IP is not exposed when downloading torrents).

I dont understand the nature of this service and I could not find any information about it. How is realDebrid connected to all those hosters? I would be using split tunnel to the hoster. Would I have to add a tunnel for every single domain or am I connecting only realdebrid hosts? In the last case one tunnel in policy based routing would be enough.

Is this kind of service explained somewhere more in detail?

**Comment by GammaC0de** [comment]
This is called a multi-hoster, AKA debrid:
You pay to them and you get premium access to all the above hosters
The debrid company have business agreements with all those hoster companies so you can download as premium.

So in short: you pay once an get many.

>Would I have to add a tunnel for every single domain or am I connecting only realdebrid hosts

Can you explain? what is a tunnel ?

**Comment by godfuture** [comment]
> So in short: you pay once an get many.

Right. I was just thinking how it is possible to pay less for multiple hosters than paying one. It sounded a bit like scam. But I am always open for new! As I care about privacy, my request was bit more of technical nature like do I build up connections only to debrid or to servers of every single hoster. Which leads to your next question...
> Can you explain? what is a tunnel ?

I am using VPN to several servers depending on the target. Its called policy based routing or in VPN terms split tunnel, as only certain networks are being routed through VPN. The average VPN user is routing the default gateway through one VPN. This is not the case for me. I use different VPNs for different targets. Therefore maintaining the VPN routed networks is harder if there more direct connections to several hosters than building up a connection to debrid acting like a proxy to those other hosters. Thats all.

It looked to me like I only have to login into debrid and all hosters are accessable?! Or can I use my debrid account to login into other hosters website as well?

Sorry for being detailed like hell. Hope my questions are okay.

**Comment by GammaC0de** [comment]
>  do I build up connections only to debrid or to servers of every single hoster

All traffic goes to the realdebrid servers, see an example download session log:
```
06.08.2020 01:52:05 INFO      Added package 3631 containing 1 links
06.08.2020 01:52:06 INFO      Download starts: https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
06.08.2020 01:52:06 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
06.08.2020 01:52:06 DEBUG     ADDON CloudFlareDdos: Overriding _preload() for <HOSTER RealdebridCom[10089]>
06.08.2020 01:52:06 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
06.08.2020 01:52:06 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
06.08.2020 01:52:06 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0`
06.08.2020 01:52:06 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | Plugin version: 0.81
06.08.2020 01:52:06 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | Plugin status: testing
06.08.2020 01:52:06 WARNING   HOSTER RealdebridCom[10089]: RealdebridCom | Plugin may be unstable
06.08.2020 01:52:06 INFO      ACCOUNT RealdebridCom: Grabbing account info for user `ZYF*******`...
06.08.2020 01:52:06 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/user | redirect=True | cookies=True | get={'auth_token': u'XXX'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
06.08.2020 01:52:06 DEBUG     ACCOUNT RealdebridCom: Account info for user `ZYF*******`: {'login': {'timestamp': 1596667888.517, 'password': '**********', 'valid': True}, 'data': {'hosters': [u'alfafile.net', u'anzfile.net', u'bayfiles.com', u'clicknupload.me', u'clipwatching.com', u'dailymotion.com', u'ddownload.com', u'depositfiles.com', u'dropapk.to', u'filefactory.com', u'filerio.com', u'fourshared.com', u'free.fr', u'gigapeta.com', u'google.com', u'hitfile.net', u'hulkshare.com', u'inclouddrive.com', u'isra.cloud', u'mediafire.com', u'mega.co.nz', u'mixdrop.co', u'nitroflare.com', u'oboom.com', u'onefichier.com', u'rapidgator.net', u'redtube.com', u'scribd.com', u'sendspace.com', u'sky.fm', u'solidfiles.com', u'soundcloud.com', u'turbobit.net', u'tusfiles.com', u'ulozto.net', u'unibytes.com', u'uploaded.to', u'uptobox.com', u'userscloud.com', u'usersdrive.com', u'vidlox.tv', u'vidoza.net', u'vimeo.com', u'wipfiles.net', u'wupfile.com', u'youporn.com', u'youtube.com', u'zippyshare.com'], 'premium': True, 'trafficleft': -1, 'plugin': <Account RealdebridCom>, 'maxtraffic': None, 'api_token': u'XXX', 'validuntil': 1614471797.826, 'login': 'ZYF*******', 'type': 'RealdebridCom', 'options': {'limitDL': ['0']}}}
06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Grabbing link info...
06.08.2020 01:52:06 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | Link info: {'status': 7, 'hash': {}, 'name': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'url': u'https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'pattern': {}, 'size': 0}
06.08.2020 01:52:06 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | Previous link info: {}
06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Link name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Link size: N/D
06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Link status: starting
06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Processing url: https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
06.08.2020 01:52:06 DEBUG     ADDON CloudFlareDdos: Calling _preload() of <HOSTER RealdebridCom[10089]>
06.08.2020 01:52:06 DEBUG     ADDON CloudFlareDdos: _preload() returned successfully
06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Checking for link errors...
06.08.2020 01:52:06 WARNING   HOSTER RealdebridCom[10089]: RealdebridCom | No data to check
06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Grabbing link info...
06.08.2020 01:52:06 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | Link info: {'status': 7, 'hash': {}, 'name': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'url': u'https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'pattern': {}, 'size': 0}
06.08.2020 01:52:06 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | Previous link info: {'status': 7, 'hash': {}, 'name': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'url': u'https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'pattern': {}, 'size': 0}
06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Link name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Link size: N/D
06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Link status: starting
06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Processing as premium download...
06.08.2020 01:52:06 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | LOAD URL https://api.real-debrid.com/rest/1.0/unrestrict/link | redirect=True | cookies=True | get={'auth_token': u'XXX'} | req=None | decode=True | multipart=False | post={'password': '', 'link': u'https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'} | ref=True | just_header=False
06.08.2020 01:52:07 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | Returned Data: {u'mimeType': u'application/zip', u'streamable': 0, u'host_icon': u'https://fcdn.real-debrid.com/0802/images/hosters/rapidgator.png', u'filename': u'XXXXXXXXX.zip', u'crc': 1, u'host': u'rapidgator.net', u'link': u'https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'filesize': 208666624, u'chunks': 8, u'download': u'https://42.download.real-debrid.com/d/GQQG3IHJNIILG/XXXXXXXXX.zip', u'id': u'GQQG3IHJNIILG'}
06.08.2020 01:52:07 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Downloading file...
06.08.2020 01:52:07 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | DOWNLOAD URL https://42.download.real-debrid.com/d/GQQG3IHJNIILG/XXXXXXXXX.zip | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
06.08.2020 01:52:08 DEBUG     Content-Disposition: XXXXXXXXX.zip
06.08.2020 01:52:08 DEBUG     Chunked with range 69556715-139113430
06.08.2020 01:52:08 DEBUG     Chunked with range 139113430-
 ```

> It looked to me like I only have to login into debrid and all hosters are accessable?!

Yes, they are accessible via realdebrid's web site:
You put a link there and get a realdebrid download link in exchange.

> Or can I use my debrid account to login into other hosters website as well?

No.

**Comment by GammaC0de** [comment]
Oops, DdlTo seems not supported by realdebrid.
But no worries, there is https://alldebrid.com/offer/ which offers many more hosters then realdebrid and also DdlTo is supported.

Here is a DdlTo  download session with alldebrid:
```
06.08.2020 02:16:38 INFO      Download starts: https://ddownload.com/xxxxxxxxxxxx
06.08.2020 02:16:38 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
06.08.2020 02:16:38 DEBUG     ADDON CloudFlareDdos: Overriding _preload() for <HOSTER AlldebridCom[10090]>
06.08.2020 02:16:38 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
06.08.2020 02:16:38 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
06.08.2020 02:16:38 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0`
06.08.2020 02:16:38 DEBUG     HOSTER AlldebridCom[10090]: AlldebridCom | Plugin version: 0.61
06.08.2020 02:16:38 DEBUG     HOSTER AlldebridCom[10090]: AlldebridCom | Plugin status: testing
06.08.2020 02:16:38 WARNING   HOSTER AlldebridCom[10090]: AlldebridCom | Plugin may be unstable
06.08.2020 02:16:38 INFO      ACCOUNT AlldebridCom: Grabbing account info for user `Jin*******`...
06.08.2020 02:16:38 DEBUG     ACCOUNT AlldebridCom: LOAD URL https://api.alldebrid.com/v4/user | redirect=True | cookies=True | get={'apikey': '**********', 'version': '0.4.20', 'agent': 'pyLoad'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
06.08.2020 02:16:38 DEBUG     ACCOUNT AlldebridCom: Account info for user `Jin*******`: {'login': {'timestamp': 1596669381.547, 'password': '**********', 'valid': True}, 'data': {'hosters': [u'alterupload.com', u'anzfile.net', u'backin.net', u'baidu.com', u'bayfiles.com', u'bdupload.asia', u'brupload.net', u'btafile.com', u'cjoint.net', u'clicknupload.co', u'clipwatching.com', u'cloudvideo.tv', u'cosmobox.org', u'ddl.to', u'desfichiers.com', u'dfichiers.com', u'dl4free.com', u'douploads.com', u'dropapk.to', u'earn4files.com', u'example.com', u'example.net', u'exload.com', u'feurl.com', u'file-upload.com', u'file.al', u'file4safe.com', u'filefactory.com', u'filerio.com', u'filerio.in', u'filespace.com', u'fileupload.pw', u'fireget.com', u'flashbit.cc', u'florenfile.com', u'fourshared.com', u'free.fr', u'fshare.vn', u'giga-down.com', u'gigapeta.com', u'goloady.com', u'google.com', u'gounlimited.to', u'hitfile.net', u'hotlink.cc', u'inclouddrive.com', u'indishare.me', u'isra.cloud', u'katfile.com', u'letsupload.co', u'letsupload.to', u'load.to', u'mediafire.com', u'mega.co.nz', u'mega.nz', u'megadl.fr', u'mesfichiers.org', u'mexa.sh', u'mexashare.com', u'mixdrop.co', u'nelion.me', u'onefichier.com', u'piecejointe.net', u'pjointe.com', u'playvidto.com', u'prefiles.com', u'rapidgator.net', u'rapidrar.com', u'rapidu.net', u'rarefile.net', u'rockfile.co', u'scribd.com', u'sendit.cloud', u'sendspace.com', u'simfileshare.net', u'takefile.link', u'tenvoi.com', u'turbo.to', u'turbobit.cc', u'turbobit.cloud', u'turbobit.net', u'ubiqfile.com', u'upload.ac', u'uploadbox.io', u'uploadcloud.pro', u'uploaded.to', u'uploaded.to', u'uploadev.com', u'uploadev.org', u'uploadrar.com', u'uppit.com', u'uptobox.com', u'uptostream.com', u'userscloud.com', u'usersdrive.com', u'vev.io', u'videobin.co', u'vidlox.me', u'vidoza.net', u'vidoza.org', u'vidto-do.com', u'vidtodo.com', u'vshare.eu', u'wayupload.com', u'wdupload.com', u'wipfiles.net', u'world-files.com', u'worldbytez.com', u'wushare.com', u'xubster.com', u'zippyshare.com'], 'premium': True, 'plugin': <Account AlldebridCom>, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1681062754, 'login': 'Jin*******', 'type': 'AlldebridCom', 'options': {'limitDL': ['0']}}}
06.08.2020 02:16:38 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Grabbing link info...
06.08.2020 02:16:38 DEBUG     HOSTER AlldebridCom[10090]: AlldebridCom | Link info: {'status': 7, 'hash': {}, 'name': u'xxxxxxxxxxxx', 'url': u'https://ddownload.com/xxxxxxxxxxxx', 'pattern': {}, 'size': 0}
06.08.2020 02:16:38 DEBUG     HOSTER AlldebridCom[10090]: AlldebridCom | Previous link info: {}
06.08.2020 02:16:38 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Link name: xxxxxxxxxxxx
06.08.2020 02:16:38 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Link size: 1.07 GiB (1153433600 bytes)
06.08.2020 02:16:38 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Link status: starting
06.08.2020 02:16:38 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Processing url: https://ddownload.com/xxxxxxxxxxxx
06.08.2020 02:16:38 DEBUG     ADDON CloudFlareDdos: Calling _preload() of <HOSTER AlldebridCom[10090]>
06.08.2020 02:16:38 DEBUG     ADDON CloudFlareDdos: _preload() returned successfully
06.08.2020 02:16:38 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Checking for link errors...
06.08.2020 02:16:38 WARNING   HOSTER AlldebridCom[10090]: AlldebridCom | No data to check
06.08.2020 02:16:38 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Grabbing link info...
06.08.2020 02:16:38 DEBUG     HOSTER AlldebridCom[10090]: AlldebridCom | Link info: {'status': 7, 'hash': {}, 'name': u'xxxxxxxxxxxx', 'url': u'https://ddownload.com/xxxxxxxxxxxx', 'pattern': {}, 'size': 0}
06.08.2020 02:16:38 DEBUG     HOSTER AlldebridCom[10090]: AlldebridCom | Previous link info: {'status': 7, 'hash': {}, 'name': u'xxxxxxxxxxxx', 'url': u'https://ddownload.com/xxxxxxxxxxxx', 'pattern': {}, 'size': 0}
06.08.2020 02:16:38 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Link name: xxxxxxxxxxxx
06.08.2020 02:16:38 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Link size: 1.07 GiB (1153433600 bytes)
06.08.2020 02:16:38 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Link status: starting
06.08.2020 02:16:38 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Processing as premium download...
06.08.2020 02:16:38 DEBUG     HOSTER AlldebridCom[10090]: AlldebridCom | LOAD URL https://api.alldebrid.com/v4/link/unlock | redirect=True | cookies=True | get={'apikey': '**********', 'link': u'https://ddownload.com/xxxxxxxxxxxx', 'version': '0.4.20', 'agent': 'pyLoad'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
06.08.2020 02:16:39 INFO      HOSTER AlldebridCom[10090]: AlldebridCom | Downloading file...
06.08.2020 02:16:39 DEBUG     HOSTER AlldebridCom[10090]: AlldebridCom | DOWNLOAD URL https://m6auib.alldebridro.ovh:449/dl/1vcicho6378/XXXXXX.part1.rar | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
06.08.2020 02:16:40 DEBUG     Chunked with range 384477867-768955734
06.08.2020 02:16:40 DEBUG     Chunked with range 768955734-
 ```

**Comment by godfuture** [comment]
> All traffic goes to the realdebrid servers, see an example download session log:
> ```
> 06.08.2020 01:52:06 INFO      Download starts: https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 06.08.2020 01:52:06 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | Link info: {'status': 7, 'hash': {}, 'name': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'url': u'https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'pattern': {}, 'size': 0}
> 06.08.2020 01:52:06 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Processing url: https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 06.08.2020 01:52:06 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | Link info: {'status': 7, 'hash': {}, 'name': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'url': u'https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'pattern': {}, 'size': 0}
> 06.08.2020 01:52:06 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | Previous link info: {'status': 7, 'hash': {}, 'name': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'url': u'https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'pattern': {}, 'size': 0}
> 06.08.2020 01:52:06 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | LOAD URL https://api.real-debrid.com/rest/1.0/unrestrict/link | redirect=True | cookies=True | get={'auth_token': u'XXX'} | req=None | decode=True | multipart=False | post={'password': '', 'link': u'https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'} | ref=True | just_header=False```

If I got you correctly, even after these lines rapidgator.net would have never seen my ip? Not a single request sent there, right? As this is a crucial part, I try to be very clear.

Later it looks like data is downloaded anyway from fcdn.real-debrid.com. So it seems only auth header is redirected to websites to initiate sessions. Again, this underlines that only realdebrid sees my ip, right?:
> ```06.08.2020 01:52:07 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | Returned Data: {u'mimeType': u'application/zip', u'streamable': 0, u'host_icon': u'https://fcdn.real-debrid.com/0802/images/hosters/rapidgator.png', u'filename': u'XXXXXXXXX.zip', u'crc': 1, u'host': u'rapidgator.net', u'link': u'https://rapidgator.net/file/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'filesize': 208666624, u'chunks': 8, u'download': u'https://42.download.real-debrid.com/d/GQQG3IHJNIILG/XXXXXXXXX.zip', u'id': u'GQQG3IHJNIILG'}
> 06.08.2020 01:52:07 INFO      HOSTER RealdebridCom[10089]: RealdebridCom | Downloading file...
> 06.08.2020 01:52:07 DEBUG     HOSTER RealdebridCom[10089]: RealdebridCom | DOWNLOAD URL https://42.download.real-debrid.com/d/GQQG3IHJNIILG/XXXXXXXXX.zip | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True```

**Comment by GammaC0de** [comment]
>If I got you correctly, even after these lines rapidgator.net would have never seen my ip? Not a single request sent there, right?

No, 
only `LOAD URL` and `DOWNLOAD URL`  log lines are HTTP requests.

> This underlines that only realdebrid sees my ip, right?

Right.

**Comment by godfuture** [comment]
Thanks a lot for you help here. Can I use promo codes to credit you on one of the hosters? 

Alldebrid.com does not allow VPN usage for registration. This sounds very suspicious to me. They claim that VPN is not required, because all traffic is behind their servers. Thats good, but still alldebrid.com sees my IP address. I really do not know why they would be interested to see my real IP address on registration...

**Comment by djessich** [comment]
I have the same problem with ddl. After some time it stops downloading automatically, a manual restart helps. However, what I could find out is that the problem persists only if Plugins were updated with UpdateManager, the initial version with 0.4.20 works as expected (at least for me).
@GammaC0de Is there any possibility to have this fixed soon a new Plugin or Pyload version released including the fix?

**Comment by djessich** [comment]
@GammaC0de Is there any possibility to have this fixed soon and a new Plugin or Pyload version released including the fix?

**Comment by GammaC0de** [comment]
@djessich Can you provide debug logs?
