### ISSUE TITLE
HOSTER Katfile does not work

### ISSUE THREAD

**Issue by juankaxxi** [pyload/pyload#3633]
KATFILE does not work, I put here the error that gives pyload:

2567 | 12.05.2020 08:37:59 | INFO | HOSTER KatfileCom[108]: No errors found
-- | -- | -- | --
2566 | 12.05.2020 08:37:58 | INFO | HOSTER KatfileCom[108]: Checking for link errors...
2565 | 12.05.2020 08:37:58 | DEBUG | HOSTER KatfileCom[108]: Getting download link #1...
2564 | 12.05.2020 08:37:58 | INFO | HOSTER KatfileCom[108]: Processing as free download...
2563 | 12.05.2020 08:37:58 | INFO | HOSTER KatfileCom[108]: Link status: starting
2562 | 12.05.2020 08:37:58 | INFO | HOSTER KatfileCom[108]: Link size: N/D
2561 | 12.05.2020 08:37:58 | INFO | HOSTER KatfileCom[108]: Link name: 3x02_-_Los_tres_deseos.mkv.html
2560 | 12.05.2020 08:37:58 | DEBUG | HOSTER KatfileCom[108]: Previous link info: {'status': 7, 'hash': {}, 'name': u'3x02_-_Los_tres_deseos.mkv.html', 'url': u'http://katfile.com/5to0glyznq2z/3x02_-_Los_tres_deseos.mkv.html', 'pattern': {}, 'size': 0}
2559 | 12.05.2020 08:37:58 | DEBUG | HOSTER KatfileCom[108]: Link info: {'status': 7, 'hash': {}, 'name': u'3x02_-_Los_tres_deseos.mkv.html', 'url': u'http://katfile.com/5to0glyznq2z/3x02_-_Los_tres_deseos.mkv.html', 'pattern': {}, 'size': 0}
2558 | 12.05.2020 08:37:58 | INFO | HOSTER KatfileCom[108]: Grabbing link info...
2557 | 12.05.2020 08:37:58 | INFO | HOSTER KatfileCom[108]: No errors found
2556 | 12.05.2020 08:37:58 | INFO | HOSTER KatfileCom[108]: Checking for link errors...
2555 | 12.05.2020 08:37:57 | DEBUG | HOSTER KatfileCom[108]: LOAD URL http://katfile.com/5to0glyznq2z/3x02_-_Los_tres_deseos.mkv.html \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
2554 | 12.05.2020 08:37:57 | INFO | HOSTER KatfileCom[108]: Processing url: http://katfile.com/5to0glyznq2z/3x02_-_Los_tres_deseos.mkv.html
2553 | 12.05.2020 08:37:57 | INFO | HOSTER KatfileCom[108]: Link status: starting
2552 | 12.05.2020 08:37:57 | INFO | HOSTER KatfileCom[108]: Link size: N/D
2551 | 12.05.2020 08:37:57 | INFO | HOSTER KatfileCom[108]: Link name: 3x02_-_Los_tres_deseos.mkv.html
2550 | 12.05.2020 08:37:57 | DEBUG | HOSTER KatfileCom[108]: Previous link info: {'status': 7, 'hash': {}, 'name': u'3x02_-_Los_tres_deseos.mkv.html', 'url': u'http://katfile.com/5to0glyznq2z/3x02_-_Los_tres_deseos.mkv.html', 'pattern': {}, 'size': 0}
2549 | 12.05.2020 08:37:57 | DEBUG | HOSTER KatfileCom[108]: Link info: {'status': 7, 'hash': {}, 'name': u'3x02_-_Los_tres_deseos.mkv.html', 'url': u'http://katfile.com/5to0glyznq2z/3x02_-_Los_tres_deseos.mkv.html', 'pattern': {}, 'size': 0}
2548 | 12.05.2020 08:37:56 | INFO | HOSTER KatfileCom[108]: Grabbing link info...
2547 | 12.05.2020 08:37:56 | WARNING | HOSTER KatfileCom[108]: Plugin may be unstable
2546 | 12.05.2020 08:37:56 | DEBUG | HOSTER KatfileCom[108]: Plugin status: testing
2545 | 12.05.2020 08:37:56 | DEBUG | HOSTER KatfileCom[108]: Plugin version: 0.02

Gracias!!!

**Comment by GammaC0de** [comment]
This file is offline, now properly detected.
