### ISSUE TITLE
api 500

### ISSUE THREAD

**Issue by Joker404-code** [pyload/pyload#3634]
Hello
i have problem with api the login phase work with no problem and i got the session id but when i test checkurl or any other method not work , i got error 500 :
`$cookie = '/tmp/pyload.txt';

$login = json_decode(curlPost('http://127.0.0.1:8000/api/login','POST',array('username' => 'hemiad','password' => '1236987'),null,null,$cookie),true);`

$checklink = curlPost('http://127.0.0.1:8000/api/checkURLs','POST',array('urls' => 'https://1fichier.com/?mfyfhoarotevqis57sqi','session' => $login),null,null,$cookie,true);
die(print_r($checklink));`

![scren](https://image.prntscr.com/image/_9qmnAvKScGxm9cVG6gn2w.png)

Debug mode is ON
![scren](https://image.prntscr.com/image/9cKysgSUSHOEQvZAvGelBA.png)

Thank you
Best regards

**Comment by GammaC0de** [comment]
What language is this? PHP?

See [here ](https://github.com/pyload/pyload/issues/3622#issuecomment-623192663)for example of API usage.

**Comment by Joker404-code** [comment]
Yes Language PHP.
I have test the code in https://github.com/pyload/pyload/issues/3622#issuecomment-623192663
`import requests
from requests.packages.urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

username = "hemiad"
password = "1236987"
url = "http://127.0.0.1:8000/api/"
payload = {"username": username, "password": password}
login = requests.post(
    "{}{}".format(url, "login"),
    headers={'Content-Type':"application/x-www-form-urlencoded"},
    data=payload,
    timeout=5,
    verify=False)
print(login.cookies)

payload = {"offset": 20}
response = requests.post(
    "{}{}".format(url, "getUserData"),
    data=payload,
    cookies=login.cookies,
    timeout=5,
    verify=False,
    headers={'Content-Type':"application/x-www-form-urlencoded"}
)
print(response)
response.raise_for_status()
print(response.json())
`
And change method to getUserData.

Reponse : 
`<RequestsCookieJar[<Cookie beaker.session.id=f26d60092131b401950ae74d44a14bbe for 127.0.0.1/>]>
<Response [500]>
Traceback (most recent call last):
  File "pyload.py", line 28, in <module>
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8000/api/getUserData`

**Comment by GammaC0de** [comment]
What are you trying to achieve exactly?
