### ISSUE TITLE
Pyload in namespace

### ISSUE THREAD

**Issue by Merlincool** [pyload/pyload#3638]
### Your question

I have seen this article and tried to run pyload under namespace so I don't have to use vpn for entire server, I could also sucessfully start pyload in namespace.

But I can't connect to webgui?

Also "python ~/.pyload/pyLoadCli.py" says

Could not establish connection with 127.0.0.1 and port 7227.

**Comment by diman82** [comment]
Duplicate of #1085

**Comment by JpegXguy** [comment]
Btw this is because you have to tunnel the pyload port from the namespace to outside the namespace. (e.g. with socat)
