### ISSUE TITLE
Youtube Plugin download failed

### ISSUE THREAD

**Issue by pivster86** [pyload/pyload#3639]
WARNING	HOSTER YoutubeCom[60]: Plugin may be unstable
INFO	HOSTER YoutubeCom[60]: Grabbing link info...
INFO	HOSTER YoutubeCom[60]: Link name: watch
INFO	HOSTER YoutubeCom[60]: Link size: N/D
INFO	HOSTER YoutubeCom[60]: Link status: starte
INFO	HOSTER YoutubeCom[60]: Processing url: https://youtube.com/watch?v=***************
WARNING	HOSTER YoutubeCom[60]: Free download failed | No available video stream meets your preferences
WARNING | Download failed: watch \| No available video stream meets your preferences
-- | --

Any ideas? Some seconds before i downloaded other Video, w/o any problems.. PyLoad has last version...

**Comment by GammaC0de** [comment]
URL please

**Comment by pivster86** [comment]
Hi,

i tryed it just once more, and i can download it... I changed nothing, i think there was some problem on youtube maybe?

Issue can be closed... thx for fast response!

**Comment by theissue** [comment]
Hi, i'm currently having the same issue:


97 | 26.08.2020 04:34:57 | INFO | Download starts: https://www.youtube.com/watch?v=IqoB5qCCWKo
-- | -- | -- | --
798 | 26.08.2020 04:34:57 | WARNING | HOSTER YoutubeCom[8]: Plugin may be unstable
799 | 26.08.2020 04:34:57 | INFO | HOSTER YoutubeCom[8]: Grabbing link info...
800 | 26.08.2020 04:34:57 | INFO | HOSTER YoutubeCom[8]: Link name: watch
801 | 26.08.2020 04:34:57 | INFO | HOSTER YoutubeCom[8]: Link size: N/D
802 | 26.08.2020 04:34:57 | INFO | HOSTER YoutubeCom[8]: Link status: starting
803 | 26.08.2020 04:34:57 | INFO | HOSTER YoutubeCom[8]: Processing url: https://www.youtube.com/watch?v=IqoB5qCCWKo
**804 | 26.08.2020 04:34:58 | WARNING | HOSTER YoutubeCom[8]: Free download failed \| No available video stream meets your preferences
805 | 26.08.2020 04:34:58 | WARNING | Download failed: watch \| No available video stream meets your preferences**
806 | 26.08.2020 04:34:58 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: watch (pid:8)
807 | 26.08.2020 04:34:58 | INFO | ADDON UnSkipOnFail: No duplicates found

Also, i'm having this:


19 | 26.08.2020 04:44:13 | INFO | Added package watch containing 1 links
-- | -- | -- | --
820 | 26.08.2020 04:44:14 | INFO | Download starts: https://www.youtube.com/watch?v=UZ4yaV9uepA
821 | 26.08.2020 04:44:14 | WARNING | HOSTER YoutubeCom[10]: Plugin may be unstable
822 | 26.08.2020 04:44:14 | INFO | HOSTER YoutubeCom[10]: Grabbing link info...
823 | 26.08.2020 04:44:14 | INFO | HOSTER YoutubeCom[10]: Link name: watch
824 | 26.08.2020 04:44:14 | INFO | HOSTER YoutubeCom[10]: Link size: N/D
825 | 26.08.2020 04:44:14 | INFO | HOSTER YoutubeCom[10]: Link status: starting
826 | 26.08.2020 04:44:14 | INFO | HOSTER YoutubeCom[10]: Processing url: https://www.youtube.com/watch?v=UZ4yaV9uepA
**827 | 26.08.2020 04:44:14 | WARNING | Download failed: watch \| Unterminated string starting at: line 1 column 1119 (char 1119)**
828 | 26.08.2020 04:44:14 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: watch (pid:10)
829 | 26.08.2020 04:44:14 | INFO | ADDON UnSkipOnFail: No duplicates found


Any ideas? Thanks!

**Comment by gerroon** [comment]
I have this with terminated strings issue as well with Pyload 0.5.0 (pyload-ng , python 3.9.7) using Docker version.
