### ISSUE TITLE
Pornhub account missing

### ISSUE THREAD

**Issue by mlazzarotto** [pyload/pyload#3640]
### Your question

Hello everyone, I can't find Pornhub in the list of available account on pyLoad (Config --> Accounts --> + button).
I'm using pyLoad 0.4.20 on a Docker container.

**Comment by GammaC0de** [comment]
Currently there is no support for a Pornhub account, is there any benefit of having/using a Pornhub account (in terms of download)?

**Comment by mlazzarotto** [comment]
Yes, the benefit of using a premium account is downloading premium videos that are not otherwise available.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

Also, please send a sample URL that is available as premium only.

**Comment by mlazzarotto** [comment]
> Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.
> 
> Also, please send a sample URL that is available as premium only.

Done
