### ISSUE TITLE
Greek language

### ISSUE THREAD

**Issue by ChriZathens** [pyload/pyload#3644]
### Your question

Hello guys. In webui there are a few languages to choose from, but there are also a lot missing
Can you add more language options?

**Comment by GammaC0de** [comment]
1. Go to https://crowdin.com/project/pyload/el#/pyLoad0.4.10 and verify that the translation if OK.
2. Correct any mistake you find in the translation.
3. Post here when finished.

**Comment by ChriZathens** [comment]
Done...
(Had proofread and added to the translation myself, years ago...I checked again, approved and corrected some, but it can only be "perfected" after it is used)

**Comment by GammaC0de** [comment]
Extract this [el.zip](https://github.com/pyload/pyload/files/4667438/el.zip) to the root of the installation , restart pyload, switch language, restart again.
Then confirm it work so I can include it in the repo

**Comment by ChriZathens** [comment]
Ok, done that and seems to be working just fine
I see some improvements that need to be made, I suppose you will be notified when the strings are updated. In any case I will also post here just fyi.

**Comment by ChriZathens** [comment]
I looked through the gui and thought that some strings were not translated. However just checked in crowdin and they are. Could it be that you packed a previous version of the translated strings or anything like that in the zip you posted above?

**Comment by ChriZathens** [comment]
OK submitted a pull request that fixes the above #3646

**Comment by GammaC0de** [comment]
@ChriZathens I want to create a new translation template file,
This will take some days until I finish some other stuff.

**Comment by GammaC0de** [comment]
@ChriZathens I have updated the translation template.

Unfortunately, I do not have access to the croudwin pyload site 😢  so wou will have to use [poedit](https://poedit.net/download) and the [new translation template](https://github.com/pyload/pyload/raw/stable/locale/django.pot) to generate an updated Greek .po file.

When finished, please post the .po file hre and I will commit the translation.

**Comment by ChriZathens** [comment]
OK, I have translated the strings
Here you go:
[el_GR.zip](https://github.com/pyload/pyload/files/4716835/el_GR.zip)

I copied the mo file on my installation, too, and seems to be OK. I will check it better when I have some more time and "fine tune" it if necessary. 
There are quite a few more stuff that appear untranslated in the web interface - I suppose they are the rest of the *.mo files, correct? So, when you can, provide the pot for those files, too, and I will translate those also.

**Comment by GammaC0de** [comment]
> There are quite a few more stuff that appear untranslated in the web interface - I suppose they are the rest of the *.mo files, correct?
Django.pot holds the translations for the web interface. So all of the web interface should have been translated (but maybe I miss some so I need your feedback). 
The other templates names are self explinatory 
 
 
  , ChriZathens<notifications@github.com> wrote:   


OK, I have translated the strings
Here you go:
el_GR.zip

I copied the mo file on my installation, too, and seems to be OK. I will check it better when I have some more time and "fine tune" it if necessary.
There are quite a few more stuff that appear untranslated in the web interface - I suppose they are the rest of the *.mo files, correct? So, when you can, provide the pot for those files, too, and I will translate those also.

**Comment by ChriZathens** [comment]
Ok I see.. I thought the webui was perhaps pulling strings from other portions of the code..
There are a lot of untranslated stuff.
I am attaching a zip with screenshots of the "Config" section. (The png named config is the main menu - the other are the settings  -each png named after the relevant setting.)
[Config.zip](https://github.com/pyload/pyload/files/4717010/Config.zip)

**Comment by GammaC0de** [comment]
Apparently these are dynamically generated.

I will see what can be done.

**Comment by GammaC0de** [comment]
OK, I have updated the template again, You'll probably will also need to apply https://github.com/pyload/pyload/commit/0aa43a93bd791bf62fe068cc669b6bfdc9024ff5 to your installation.

**Comment by ChriZathens** [comment]
Well I don't use the git version but looking at the specific commit, it should be no problem
Is there an ability to edit the already translated file and add only the new strings? I re-downloaded the template but I will need to translate all of it again. (Copy-paste but still). If it can't be done, no problem, though, I will just copy-paste

**Comment by ChriZathens** [comment]
OK, attaching the updated translation
[el_GR.zip](https://github.com/pyload/pyload/files/4729432/el_GR.zip)
I actually applied the commit (by manually editing the files - I should consider switching to git) and all seems good
Now there are a few  untranslated stuff in hoster and crypter files but I doubt you want to deal with all those
I also added 3 pull requests, #3664 , #3665 and #3666 which correct an untranslated string. Also attaching another translation here, which also includes this missing string.
[el_GR1.zip](https://github.com/pyload/pyload/files/4729659/el_GR1.zip)

**Comment by GammaC0de** [comment]
Thanks for notifying me about the untranslated string but,
You had two duplicate PRs (3664 and 3665 are the same - classic theme) and pyplex is missing.
So if you don't mind I have changed it my self.

**Comment by ChriZathens** [comment]
Heh,  sorry, messed it up...

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/1c9abd63d65769945d04a9da737f2e4bcecf4c70
