### ISSUE TITLE
New Torrent plugin with Alldebrid or Realdebrid

### ISSUE THREAD

**Issue by TuXbOy06** [pyload/pyload#3645]
Hi,
Since the new TORRENT plugin was released I am having a strange behaviour with Pyload...

I chose AlldebridComTorrent plugin in Plugins > TORRENT > Associate Torrents / Magnets with plugin

![image](https://user-images.githubusercontent.com/13116073/82645151-b77d2d80-9c12-11ea-8feb-8539d351e4e2.png)

Pyload does not seems to take in consideration my choice is there a way to force this plugin? 

I tried with a test account of Realdebrid and having the same issue
Here the logs

91 | 22.05.2020 09:48:33 | INFO | Starting builtin webserver: 0.0.0.0:8000
-- | -- | -- | --
92 | 22.05.2020 09:48:33 | INFO | Free space: 4.68 TiB
93 | 22.05.2020 09:48:33 | INFO | Activating Accounts...
94 | 22.05.2020 09:48:33 | INFO | Activating Plugins...
95 | 22.05.2020 09:48:33 | WARNING | ADDON TORRENT: torrents / magnets are not associated with any plugin
96 | 22.05.2020 09:48:33 | INFO | ADDON XFileSharing: Auto-discover new hosters
97 | 22.05.2020 09:48:33 | INFO | ADDON XFileSharing: Auto-discover new crypters
98 | 22.05.2020 09:48:33 | INFO | pyLoad is up and running
99 | 22.05.2020 09:48:33 | INFO | ADDON UpdateManager: pyLoad is up to date!
100 | 22.05.2020 09:48:33 | INFO | ADDON UpdateManager: All plugins are up to date!
101 | 22.05.2020 09:48:39 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
102 | 22.05.2020 09:50:55 | WARNING | Error calling event handler configChanged: >, ('TORRENT', 'torrent_plugin', u'c:AlldebridComTorrent', 'plugin'), 'TORRENT'
103 | 22.05.2020 09:52:00 | INFO | ACCOUNT AlldebridCom: Adding user `kes*******`...
104 | 22.05.2020 09:52:00 | INFO | ACCOUNT AlldebridCom: Login user `kes*******`...
105 | 22.05.2020 09:52:00 | INFO | ACCOUNT AlldebridCom: Grabbing account info for user `kes*******`...
106 | 22.05.2020 09:52:56 | INFO | Added package ncis_la containing 1 links
107 | 22.05.2020 09:52:57 | INFO | Decrypting starts: magnet:?xt=urn:btih:76MPABIQ2QILY7LNV42S4ZXHXXSHQZPN&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://open.stealth.si:80/announce&tr=http://tracker3.itzmx.com:8080/announce&tr=udp://explodie.org:6969/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.si:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://9.rarbg.me:2710/announce&tr=udp://9.rarbg.to:2740/announce&tr=udp://9.rarbg.com:2770/announce&tr=http://servandroidkino.ru/announce&tr=http://1337.abcvg.info/announce&tr=http://tracker.bittor.pw:1337/announce&tr=http://open.acgnxtracker.com/announce&tr=http://share.camoe.cn:8080/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.cyberia.is:6969/announce&tr=udp://151.80.120.114:2710/announce&tr=http://tracker2.itzmx.com:6961/announce&tr=udp://tracker.yoshi210.com:6969/announce&tr=http://tracker.yoshi210.com:6969/announce&tr=http://torrentsmd.com:8080/announce&tr=udp://zephir.monocul.us:6969/announce&tr=udp://denis.stalker.upeer.me:6969/announce&tr=http://tracker.bt4g.com:2095/announce&tr=http://tracker.torrentyorg.pl/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://opentor.org:2710/announce
108 | 22.05.2020 09:52:57 | WARNING | CONTAINER TORRENT[1]: Plugin may be unstable
109 | 22.05.2020 09:52:57 | INFO | CONTAINER TORRENT[1]: Grabbing link info...
110 | 22.05.2020 09:52:57 | INFO | CONTAINER TORRENT[1]: Link name: urnbtih76MPABIQ2QILY7LNV42S4ZXHXXSHQZPN
111 | 22.05.2020 09:52:57 | INFO | CONTAINER TORRENT[1]: Link size: N/D
112 | 22.05.2020 09:52:57 | INFO | CONTAINER TORRENT[1]: Link status: starting
113 | 22.05.2020 09:52:57 | INFO | CONTAINER TORRENT[1]: Processing url: magnet:?xt=urn:btih:76MPABIQ2QILY7LNV42S4ZXHXXSHQZPN&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://open.stealth.si:80/announce&tr=http://tracker3.itzmx.com:8080/announce&tr=udp://explodie.org:6969/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.si:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://9.rarbg.me:2710/announce&tr=udp://9.rarbg.to:2740/announce&tr=udp://9.rarbg.com:2770/announce&tr=http://servandroidkino.ru/announce&tr=http://1337.abcvg.info/announce&tr=http://tracker.bittor.pw:1337/announce&tr=http://open.acgnxtracker.com/announce&tr=http://share.camoe.cn:8080/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.cyberia.is:6969/announce&tr=udp://151.80.120.114:2710/announce&tr=http://tracker2.itzmx.com:6961/announce&tr=udp://tracker.yoshi210.com:6969/announce&tr=http://tracker.yoshi210.com:6969/announce&tr=http://torrentsmd.com:8080/announce&tr=udp://zephir.monocul.us:6969/announce&tr=udp://denis.stalker.upeer.me:6969/announce&tr=http://tracker.bt4g.com:2095/announce&tr=http://tracker.torrentyorg.pl/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://opentor.org:2710/announce
114 | 22.05.2020 09:52:57 | ERROR | CONTAINER TORRENT[1]: No plugin is associated with torrents / magnets \| Please go to plugin settings -> TORRENT and select your preferred plugin
115 | 22.05.2020 09:52:57 | ERROR | Decrypting failed: urnbtih76MPABIQ2QILY7LNV42S4ZXHXXSHQZPN \| No plugin is associated with torrents / magnets
116 | 22.05.2020 09:53:11 | INFO | Decrypting starts: urnbtih76MPABIQ2QILY7LNV42S4ZXHXXSHQZPN
117 | 22.05.2020 09:53:11 | WARNING | CONTAINER TORRENT[1]: Plugin may be unstable
118 | 22.05.2020 09:53:11 | INFO | CONTAINER TORRENT[1]: Grabbing link info...
119 | 22.05.2020 09:53:11 | INFO | CONTAINER TORRENT[1]: Link name: urnbtih76MPABIQ2QILY7LNV42S4ZXHXXSHQZPN
120 | 22.05.2020 09:53:11 | INFO | CONTAINER TORRENT[1]: Link size: N/D
121 | 22.05.2020 09:53:11 | INFO | CONTAINER TORRENT[1]: Link status: starting
122 | 22.05.2020 09:53:11 | INFO | CONTAINER TORRENT[1]: Processing url: magnet:?xt=urn:btih:76MPABIQ2QILY7LNV42S4ZXHXXSHQZPN&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://open.stealth.si:80/announce&tr=http://tracker3.itzmx.com:8080/announce&tr=udp://explodie.org:6969/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.si:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://9.rarbg.me:2710/announce&tr=udp://9.rarbg.to:2740/announce&tr=udp://9.rarbg.com:2770/announce&tr=http://servandroidkino.ru/announce&tr=http://1337.abcvg.info/announce&tr=http://tracker.bittor.pw:1337/announce&tr=http://open.acgnxtracker.com/announce&tr=http://share.camoe.cn:8080/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.cyberia.is:6969/announce&tr=udp://151.80.120.114:2710/announce&tr=http://tracker2.itzmx.com:6961/announce&tr=udp://tracker.yoshi210.com:6969/announce&tr=http://tracker.yoshi210.com:6969/announce&tr=http://torrentsmd.com:8080/announce&tr=udp://zephir.monocul.us:6969/announce&tr=udp://denis.stalker.upeer.me:6969/announce&tr=http://tracker.bt4g.com:2095/announce&tr=http://tracker.torrentyorg.pl/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://opentor.org:2710/announce
123 | 22.05.2020 09:53:11 | ERROR | CONTAINER TORRENT[1]: No plugin is associated with torrents / magnets \| Please go to plugin settings -> TORRENT and select your preferred plugin
124 | 22.05.2020 09:53:11 | ERROR | Decrypting failed: urnbtih76MPABIQ2QILY7LNV42S4ZXHXXSHQZPN \| No plugin is associated with torrents / magnets

**Comment by GammaC0de** [comment]
1. Enable DEBUG mode.
2. Refresh your pyLoad installation using the instruction in #3283,
3. Delete the package,
5. Configure the TORRENT plugin,
6. Restart pyload and verify that the TORRENT remains consistent
7. Retry with a new package.

P.S. are you using docker?

**Comment by TuXbOy06** [comment]
Yep I am using docker and was using before...
Still not working here the new logs


375 | 22.05.2020 10:29:58 | ERROR | Decrypting failed: urnbtih76MPABIQ2QILY7LNV42S4ZXHXXSHQZPN \| No plugin is associated with torrents / magnets
-- | -- | -- | --
376 | 22.05.2020 10:30:55 | INFO | Added package test containing 1 links
377 | 22.05.2020 10:30:56 | INFO | Decrypting starts: magnet:?xt=urn:btih:AOMEENYF4X3GPQN2IEA3DI3CQOAR5EVV&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://open.stealth.si:80/announce&tr=http://tracker3.itzmx.com:8080/announce&tr=udp://explodie.org:6969/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.si:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://9.rarbg.me:2710/announce&tr=udp://9.rarbg.to:2740/announce&tr=udp://9.rarbg.com:2770/announce&tr=http://servandroidkino.ru/announce&tr=http://1337.abcvg.info/announce&tr=http://tracker.bittor.pw:1337/announce&tr=http://open.acgnxtracker.com/announce&tr=http://share.camoe.cn:8080/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.cyberia.is:6969/announce&tr=udp://151.80.120.114:2710/announce&tr=http://tracker2.itzmx.com:6961/announce&tr=udp://tracker.yoshi210.com:6969/announce&tr=http://tracker.yoshi210.com:6969/announce&tr=http://torrentsmd.com:8080/announce&tr=udp://zephir.monocul.us:6969/announce&tr=udp://denis.stalker.upeer.me:6969/announce&tr=http://tracker.bt4g.com:2095/announce&tr=http://tracker.torrentyorg.pl/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://opentor.org:2710/announce
378 | 22.05.2020 10:30:56 | DEBUG | CONTAINER TORRENT[2]: Plugin version: 0.04
379 | 22.05.2020 10:30:56 | DEBUG | CONTAINER TORRENT[2]: Plugin status: testing
380 | 22.05.2020 10:30:56 | WARNING | CONTAINER TORRENT[2]: Plugin may be unstable
381 | 22.05.2020 10:30:56 | INFO | CONTAINER TORRENT[2]: Grabbing link info...
382 | 22.05.2020 10:30:56 | DEBUG | CONTAINER TORRENT[2]: Link info: {'status': 7, 'hash': {}, 'name': u'urnbtihAOMEENYF4X3GPQN2IEA3DI3CQOAR5EVV', 'url': u'magnet:?xt=urn:btih:AOMEENYF4X3GPQN2IEA3DI3CQOAR5EVV&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://open.stealth.si:80/announce&tr=http://tracker3.itzmx.com:8080/announce&tr=udp://explodie.org:6969/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.si:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://9.rarbg.me:2710/announce&tr=udp://9.rarbg.to:2740/announce&tr=udp://9.rarbg.com:2770/announce&tr=http://servandroidkino.ru/announce&tr=http://1337.abcvg.info/announce&tr=http://tracker.bittor.pw:1337/announce&tr=http://open.acgnxtracker.com/announce&tr=http://share.camoe.cn:8080/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.cyberia.is:6969/announce&tr=udp://151.80.120.114:2710/announce&tr=http://tracker2.itzmx.com:6961/announce&tr=udp://tracker.yoshi210.com:6969/announce&tr=http://tracker.yoshi210.com:6969/announce&tr=http://torrentsmd.com:8080/announce&tr=udp://zephir.monocul.us:6969/announce&tr=udp://denis.stalker.upeer.me:6969/announce&tr=http://tracker.bt4g.com:2095/announce&tr=http://tracker.torrentyorg.pl/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://opentor.org:2710/announce', 'pattern': {}, 'size': 0}
383 | 22.05.2020 10:30:56 | DEBUG | CONTAINER TORRENT[2]: Previous link info: {}
384 | 22.05.2020 10:30:56 | INFO | CONTAINER TORRENT[2]: Link name: urnbtihAOMEENYF4X3GPQN2IEA3DI3CQOAR5EVV
385 | 22.05.2020 10:30:56 | INFO | CONTAINER TORRENT[2]: Link size: N/D
386 | 22.05.2020 10:30:56 | INFO | CONTAINER TORRENT[2]: Link status: starting
387 | 22.05.2020 10:30:56 | INFO | CONTAINER TORRENT[2]: Processing url: magnet:?xt=urn:btih:AOMEENYF4X3GPQN2IEA3DI3CQOAR5EVV&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://open.stealth.si:80/announce&tr=http://tracker3.itzmx.com:8080/announce&tr=udp://explodie.org:6969/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.si:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://9.rarbg.me:2710/announce&tr=udp://9.rarbg.to:2740/announce&tr=udp://9.rarbg.com:2770/announce&tr=http://servandroidkino.ru/announce&tr=http://1337.abcvg.info/announce&tr=http://tracker.bittor.pw:1337/announce&tr=http://open.acgnxtracker.com/announce&tr=http://share.camoe.cn:8080/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.cyberia.is:6969/announce&tr=udp://151.80.120.114:2710/announce&tr=http://tracker2.itzmx.com:6961/announce&tr=udp://tracker.yoshi210.com:6969/announce&tr=http://tracker.yoshi210.com:6969/announce&tr=http://torrentsmd.com:8080/announce&tr=udp://zephir.monocul.us:6969/announce&tr=udp://denis.stalker.upeer.me:6969/announce&tr=http://tracker.bt4g.com:2095/announce&tr=http://tracker.torrentyorg.pl/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://opentor.org:2710/announce
388 | 22.05.2020 10:30:56 | ERROR | CONTAINER TORRENT[2]: No plugin is associated with torrents / magnets \| Please go to plugin settings -> TORRENT and select your preferred plugin
389 | ? | ? | Traceback (most recent call last):
390 | ? | ? | File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
391 | ? | ? | self.__bootstrap_inner()
392 | ? | ? | File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
393 | ? | ? | self.run()
394 | ? | ? | File "/opt/pyload/module/PluginThread.py", line 363, in run
395 | ? | ? | self.active.plugin.preprocessing(self)
396 | ? | ? | File "/opt/pyload/pyload-config/userplugins/internal/Base.py", line 291, in preprocessing
397 | ? | ? | return self._process(*args, **kwargs)
398 | ? | ? | File "/opt/pyload/pyload-config/userplugins/internal/Base.py", line 281, in _process
399 | ? | ? | self.process(self.pyfile)
400 | ? | ? | File "/opt/pyload/pyload-config/userplugins/container/TORRENT.py", line 32, in process
401 | ? | ? | _("Please go to plugin settings -> TORRENT and select your preferred plugin"))
402 | ? | ? |  
403 | 22.05.2020 10:30:56 | ERROR | Decrypting failed: urnbtihAOMEENYF4X3GPQN2IEA3DI3CQOAR5EVV \| No plugin is associated with torrents / magnets

**Comment by GammaC0de** [comment]
Which docker build are you using?
 can you build up-to-date image?

**Comment by TuXbOy06** [comment]
I tried 2 different images ( writl/pyload and linuxserver/pyload) but no worries i'll build my own and I'll let you know

**Comment by GammaC0de** [comment]
Does the config folder writeable?

**Comment by TuXbOy06** [comment]
yep 777 acl ;-)

**Comment by TuXbOy06** [comment]
Ok seems to be working properly with the new docker image thanks for your help
