### ISSUE TITLE
RealDebrid Plugin MegaCoNz No module named Crypto.Cipher.AES

### ISSUE THREAD

**Issue by tacosuzy** [pyload/pyload#3647]
### Debug log

```

```

**Comment by tacosuzy** [comment]
Is my bug reported ok, It doesn't show my information. I may not have followed or understood fully the pre inserted info.

**Comment by GammaC0de** [comment]
You have to install pycrypto

**Comment by tacosuzy** [comment]
Ok I installed pycrypto it put itself in .cache/pip/wheels/b6/e6/c8/"longnumberlettername" I didn't put the number letter Idk if that is unsafe info. Would I need to move this somewhere or should it not matter where it went? I restarted pyload after I got the dependency installed but I am still getting the error "failed Parse error: free decrypted link not found | Plugin may be out of date 0.00 B XFileSharingFolder". This is with a Mega folder url.

**Comment by GammaC0de** [comment]
Please disable XFileSharing plugin

**Comment by tacosuzy** [comment]
Ok I have different error with Mega, it states ip not allowed code 22. It did this with uploaded too with realdebrid plugin. Should I create another thread and close this one?

**Comment by GammaC0de** [comment]
Please enable debug mode, retry and then post the logs here.

**Comment by tacosuzy** [comment]
WARNING	Download failed: mega | ip_not_allowed (code: 22)
1008	23.05.2020 02:56:01	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: mega (pid:19)
1009	23.05.2020 02:56:01	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by tacosuzy** [comment]
That didn't look like the above here is it separately for mega folder


483 | 23.05.2020 03:08:04 | INFO | HOSTER RealdebridCom[23]: RealdebridCom \| Checking for link errors...
-- | -- | -- | --
484 | 23.05.2020 03:08:04 | WARNING | HOSTER RealdebridCom[23]: RealdebridCom \| No data to check
485 | 23.05.2020 03:08:04 | INFO | HOSTER RealdebridCom[23]: RealdebridCom \| Grabbing link info...
486 | 23.05.2020 03:08:04 | DEBUG | HOSTER RealdebridCom[23]: RealdebridCom \| Link info: {'status': 7, 'hash': {}, 'name': u'mega', 'url': u'', 'pattern': {}, 'size': 0}
487 | 23.05.2020 03:08:04 | DEBUG | HOSTER RealdebridCom[23]: RealdebridCom \| Previous link info: {'status': 7, 'hash': {}, 'name': u'mega', 'url': u'', 'pattern': {}, 'size': 0}
488 | 23.05.2020 03:08:04 | INFO | HOSTER RealdebridCom[23]: RealdebridCom \| Link name: mega
489 | 23.05.2020 03:08:04 | INFO | HOSTER RealdebridCom[23]: RealdebridCom \| Link size: N/D
490 | 23.05.2020 03:08:04 | INFO | HOSTER RealdebridCom[23]: RealdebridCom \| Link status: starting
491 | 23.05.2020 03:08:04 | INFO | HOSTER RealdebridCom[23]: RealdebridCom \| Processing as premium download...
492 | 23.05.2020 03:08:04 | DEBUG | HOSTER RealdebridCom[23]: RealdebridCom \| LOAD URL https://api.real-debrid.com/rest/1.0/unrestrict/link \| redirect=True \| cookies=True \| get={'auth_token': u'RSUERWD3645JAMWMBLN23VWE6WZIBVEIZXYMGLKE3ATZHFSH2DAA'} \| req=None \| decode=True \| multipart=False \| post={'password': '', 'link': u''} \| ref=True \| just_header=False
493 | 23.05.2020 03:08:04 | DEBUG | HOSTER RealdebridCom[23]: RealdebridCom \| Returned Data: {u'error_code': 22, u'error': u'ip_not_allowed_'}
494 | 23.05.2020 03:08:04 | WARNING | HOSTER RealdebridCom[23]: RealdebridCom \| Premium download failed \| ip_not_allowed_ (code: 22)
495 | 23.05.2020 03:08:04 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
496 | 23.05.2020 03:08:04 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
497 | 23.05.2020 03:08:04 | DEBUG | ADDON ExternalScripts: No script found under folder `package_failed`
498 | 23.05.2020 03:08:04 | WARNING | Download failed: mega \| ip_not_allowed_ (code: 22)
499 | 23.05.2020 03:08:04 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
500 | 23.05.2020 03:08:04 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: mega (pid:3)
501 | 23.05.2020 03:08:04 | INFO | ADDON UnSkipOnFail: No duplicates found
502 | 23.05.2020 03:08:04 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
503 | 23.05.2020 03:08:04 | DEBUG | All downloads processed

**Comment by tacosuzy** [comment]
This is with a non encrypted mega link


530 | 23.05.2020 03:13:18 | INFO | HOSTER RealdebridCom[24]: RealdebridCom \| Link status: starting
-- | -- | -- | --
531 | 23.05.2020 03:13:18 | INFO | HOSTER RealdebridCom[24]: RealdebridCom \| Processing as premium download...
532 | 23.05.2020 03:13:18 | DEBUG | HOSTER RealdebridCom[24]: RealdebridCom \| LOAD URL https://api.real-debrid.com/rest/1.0/unrestrict/link \| redirect=True \| cookies=True \| get={'auth_token': u''} \| req=None \| decode=True \| multipart=False \| post={'password': '', 'link': u''} \| ref=True \| just_header=False
533 | 23.05.2020 03:13:18 | DEBUG | HOSTER RealdebridCom[24]: RealdebridCom \| Returned Data: {u'error_code': 22, u'error': u'ip_not_allowed_'}
534 | 23.05.2020 03:13:18 | WARNING | HOSTER RealdebridCom[24]: RealdebridCom \| Premium download failed \| ip_not_allowed_ (code: 22)
535 | 23.05.2020 03:13:18 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
536 | 23.05.2020 03:13:18 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
537 | 23.05.2020 03:13:18 | WARNING | Download failed: wcEwHIZD \| ip_not_allowed_ (code: 22)
538 | 23.05.2020 03:13:18 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
539 | 23.05.2020 03:13:18 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: wcEwHIZD (pid:4)
540 | 23.05.2020 03:13:18 | INFO | ADDON UnSkipOnFail: No duplicates found
541 | 23.05.2020 03:13:18 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
542 | 23.05.2020 03:13:18 | DEBUG | All downloads processed

**Comment by tacosuzy** [comment]
I had to remove some things that wasn't hidden hopefully enough info is there to resolve.

**Comment by GammaC0de** [comment]
It seems that your IP is blacklisted, please contact real-debrid.com

**Comment by tacosuzy** [comment]
I am using pyload on a seedbx. Is this common or should I still contact them?

**Comment by GammaC0de** [comment]
I think you have nothing to lose, maximum the will say we are not allowing seed boxes

**Comment by tacosuzy** [comment]
I found this when searching their support.

If you want to download with or through a dedicated server (RDP, personal VPN, private proxy, and so on), you have to use your "Remote Traffic".

The Remote traffic available on our website also allows you to use our links on the hosters that accept the Remote Upload.
The hosters will be able to download and directly save the file on their servers without using your own connection.

I currently have 0 remote traffic plus it is pricey even for 1TB. I may just be better off getting a mega premium. Is there a place where plugin status is listed before I go that route to make sure the plugin is working?

**Comment by GammaC0de** [comment]
You can also try other debrid services.
Mega plugin works fine.

**Comment by tacosuzy** [comment]
Which ones do you know work with least issues and most limits? I'm ahead of you lol I've got alldebrid and premiumize pages up looking at prices.

**Comment by GammaC0de** [comment]
There is also debrid-link.fr, debriditalia.com, get24.org, Leech360.com, Linkifier.com, Premium.to

There are more

**Comment by tacosuzy** [comment]
Do you know if premiumize plugin works?

**Comment by GammaC0de** [comment]
premiumize plugin should work

**Comment by tacosuzy** [comment]
I've sent them a message and to some of the other ones to see if any of them are allowed.

**Comment by tacosuzy** [comment]
Would I need to disable the Megaconz MegaconzFolder plugins since I would be using real-debrid for it?

**Comment by GammaC0de** [comment]
> Would I need to disable the Megaconz MegaconzFolder plugins since I would be using real-debrid for it?

No
