### ISSUE TITLE
Mega.nz links won't download

### ISSUE THREAD

**Issue by mutantmarine** [pyload/pyload#3649]
### Describe the problem

I'm adding mega.nz links but none of them are downloading.

Here is an example link: https://mega.nz/file/KRdEgS4D#lniei0hVNbmOLa5u0dXJ6S9vhy3LBUFIAAAAAAAAAAA

It doesn't recognize that it is a mega link and just tries to download it as BasePlugin, then fails.

I've been puttnig the full link (Link and Key) in the link area. Should I be putting the link in the link area without the key? Then for the password, paste the key?

I've also already disabled XFileSharing/Folder plugins but that didn't help.

Any suggestions?

### Debug log

```

```

**Comment by GammaC0de** [comment]
Works fine for me (although this URL is offline), your pyload installation is probable out of date,
Please refresh your pyLoad installation using the instruction in #3283 and then retry.
