### ISSUE TITLE
File too large on download 

### ISSUE THREAD

**Issue by jiyari** [pyload/pyload#3650]
### Your question
Hello 
Im using pyload on osmc linux system, while downloading large file more than 10 GB , its gives error ( IOError: [Errno 27] File too large) 
I tried to use to external drives and same result , I noticed that files larger than 12 GB have this issue , 
So what could be the cause ? 
Thanks

**Comment by GammaC0de** [comment]
Are you using FAT32 filesystem?

**Comment by jiyari** [comment]
Im not sure , FAT32 cant accept more than 4GB is it ? 
My flash is NTFS formatted , my external drive the same

**Comment by GammaC0de** [comment]
Please enable debug mode, retry downloading and post the log here.

**Comment by jiyari** [comment]
Ok thanks I will as soon

**Comment by GammaC0de** [comment]
Just copy/paste and surround the text with code marks (\`\`\`)

**Comment by jiyari** [comment]
589 | 22.05.2020 01:37:17 | INFO | Download aborted: Mr.Bean.Brilliant.Boxset.D.R.E.1990-1995.MULTi.PAL.DVDR-STM.rar
-- | -- | -- | --
590 | 22.05.2020 01:51:14 | ERROR | <<< UNCAUGHT EXCEPTION >>>
591 | ? | ? | Traceback (most recent call last):
592 | ? | ? | File "/usr/share/pyload/module/network/HTTPChunk.py", line 236, in writeBody
593 | ? | ? | self.fp.write(buf)
594 | ? | ? | IOError: [Errno 27] File too large
595 | 22.05.2020 01:51:17 | ERROR | <<< UNCAUGHT EXCEPTION >>>
596 | ? | ? | Traceback (most recent call last):
597 | ? | ? | File "/usr/share/pyload/module/network/HTTPChunk.py", line 236, in writeBody
598 | ? | ? | self.fp.write(buf)
599 | ? | ? | IOError: [Errno 27] File too large
600 | 22.05.2020 01:51:18 | ERROR | <<< UNCAUGHT EXCEPTION >>>
601 | ? | ? | Traceback (most recent call last):
602 | ? | ? | File "/usr/share/pyload/module/network/HTTPChunk.py", line 236, in writeBody
603 | ? | ? | self.fp.write(buf)
604 | ? | ? | IOError: [Errno 27] File too large
605 | 22.05.2020 01:51:22 | ERROR | HOSTER RealdebridCom[1]: RealdebridCom


606 | 22.05.2020 01:51:22 | WARNING | HOSTER RealdebridCom[1]: RealdebridCom \| Premium download failed \| IOError 22
-- | -- | -- | --
607 | 22.05.2020 01:51:22 | WARNING | Download failed: Top.Gun.1986.2160p.UHD.BluRay.X265-IAMABLE.mkv \| IOError 22
608 | 22.05.2020 01:51:22 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: Top.Gun.1986.2160p.UHD.BluRay.X265-IAMABLE.mkv (pid:1)
609 | 22.05.2020 01:51:22 | INFO | ADDON UnSkipOnFail: No duplicates found
610 | 22.05.2020 01:56:49 | INFO | Download starts: Top.Gun.1986.2160p.UHD.BluRay.X265-IAMABLE.mkv
611 | 22.05.2020 01:56:49 | WARNING | HOSTER RealdebridCom[1]: RealdebridCom \| Plugin may be unstable
612 | 22.05.2020 01:56:49 | INFO | ACCOUNT RealdebridCom: Grabbing account info for user `T4R*******`...
613 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Grabbing link info...
614 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link name: DZPO2UOGTSJMK
615 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link size: 30.04 GiB (32252891428 bytes)
616 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link status: starting
617 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Processing url: https://real-debrid.com/d/DZPO2UOGTSJMK
618 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Looking for direct download link...
619 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Direct download link not found
620 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Checking for link errors...
621 | 22.05.2020 01:56:50 | WARNING | HOSTER RealdebridCom[1]: RealdebridCom \| No data to check
622 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Grabbing link info...
623 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link name: DZPO2UOGTSJMK
624 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link size: 30.04 GiB (32252891428 bytes)
625 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link status: starting
626 | 22.05.2020 01:56:50 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Processing as premium download...
627 | 22.05.2020 01:56:51 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Downloading file...
628 | 22.05.2020 01:56:52 | ERROR | <<< UNCAUGHT EXCEPTION >>>
629 | ? | ? | Traceback (most recent call last):
630 | ? | ? | File "/usr/share/pyload/module/network/HTTPChunk.py", line 236, in writeBody
631 | ? | ? | self.fp.write(buf)
632 | ? | ? | IOError: [Errno 27] File too large
633 | 22.05.2020 01:56:52 | ERROR | <<< UNCAUGHT EXCEPTION >>>
634 | ? | ? | Traceback (most recent call last):
635 | ? | ? | File "/usr/share/pyload/module/network/HTTPChunk.py", line 236, in writeBody
636 | ? | ? | self.fp.write(buf)
637 | ? | ? | IOError: [Errno 27] File too large
638 | 22.05.2020 01:56:52 | ERROR | <<< UNCAUGHT EXCEPTION >>>
639 | ? | ? | Traceback (most recent call last):
640 | ? | ? | File "/usr/share/pyload/module/network/HTTPChunk.py", line 236, in writeBody
641 | ? | ? | self.fp.write(buf)
642 | ? | ? | IOError: [Errno 27] File too large
643 | 22.05.2020 01:56:52 | ERROR | HOSTER RealdebridCom[1]: RealdebridCom
644 | 22.05.2020 01:56:52 | WARNING | HOSTER RealdebridCom[1]: RealdebridCom \| Premium download failed \| IOError 22
645 | 22.05.2020 01:56:52 | WARNING | Download failed: Top.Gun.1986.2160p.UHD.BluRay.X265-IAMABLE.mkv \| IOError 22
646 | 22.05.2020 01:56:52 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: Top.Gun.1986.2160p.UHD.BluRay.X265-IAMABLE.mkv (pid:1)
647 | 22.05.2020 01:56:52 | INFO | ADDON UnSkipOnFail: No duplicates found
648 | 22.05.2020 01:57:09 | INFO | Download starts: Top.Gun.1986.2160p.UHD.BluRay.X265-IAMABLE.mkv
649 | 22.05.2020 01:57:09 | WARNING | HOSTER RealdebridCom[1]: RealdebridCom \| Plugin may be unstable
650 | 22.05.2020 01:57:09 | INFO | ACCOUNT RealdebridCom: Grabbing account info for user `T4R*******`...
651 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Grabbing link info...
652 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link name: DZPO2UOGTSJMK
653 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link size: 30.04 GiB (32252891428 bytes)
654 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link status: starting
655 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Processing url: https://real-debrid.com/d/DZPO2UOGTSJMK
656 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Looking for direct download link...
657 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Direct download link not found
658 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Checking for link errors...
659 | 22.05.2020 01:57:10 | WARNING | HOSTER RealdebridCom[1]: RealdebridCom \| No data to check
660 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Grabbing link info...
661 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link name: DZPO2UOGTSJMK
662 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link size: 30.04 GiB (32252891428 bytes)
663 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link status: starting
664 | 22.05.2020 01:57:10 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Processing as premium download...
665 | 22.05.2020 01:57:11 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Downloading file...
666 | 22.05.2020 01:57:11 | ERROR | <<< UNCAUGHT EXCEPTION >>>
667 | ? | ? | Traceback (most recent call last):
668 | ? | ? | File "/usr/share/pyload/module/network/HTTPChunk.py", line 236, in writeBody
669 | ? | ? | self.fp.write(buf)
670 | ? | ? | IOError: [Errno 27] File too large
671 | 22.05.2020 01:57:12 | ERROR | <<< UNCAUGHT EXCEPTION >>>
672 | ? | ? | Traceback (most recent call last):
673 | ? | ? | File "/usr/share/pyload/module/network/HTTPChunk.py", line 236, in writeBody
674 | ? | ? | self.fp.write(buf)
675 | ? | ? | IOError: [Errno 27] File too large
676 | 22.05.2020 01:57:12 | ERROR | <<< UNCAUGHT EXCEPTION >>>
677 | ? | ? | Traceback (most recent call last):
678 | ? | ? | File "/usr/share/pyload/module/network/HTTPChunk.py", line 236, in writeBody
679 | ? | ? | self.fp.write(buf)
680 | ? | ? | IOError: [Errno 27] File too large
681 | 22.05.2020 01:57:12 | ERROR | HOSTER RealdebridCom[1]: RealdebridCom
682 | 22.05.2020 01:57:12 | WARNING | HOSTER RealdebridCom[1]: RealdebridCom \| Premium download failed \| IOError 22
683 | 22.05.2020 01:57:12 | WARNING | Download failed: Top.Gun.1986.2160p.UHD.BluRay.X265-IAMABLE.mkv \| IOError 22
684 | 22.05.2020 01:57:12 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: Top.Gun.1986.2160p.UHD.BluRay.X265-IAMABLE.mkv (pid:1)
685 | 22.05.2020 01:57:12 | INFO | ADDON UnSkipOnFail: No duplicates found
686 | 22.05.2020 01:57:25 | INFO | Download starts: Top.Gun.1986.2160p.UHD.BluRay.X265-IAMABLE.mkv
687 | 22.05.2020 01:57:25 | WARNING | HOSTER RealdebridCom[1]: RealdebridCom \| Plugin may be unstable
688 | 22.05.2020 01:57:25 | INFO | ACCOUNT RealdebridCom: Grabbing account info for user `T4R*******`...
689 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Grabbing link info...
690 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link name: DZPO2UOGTSJMK
691 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link size: 30.04 GiB (32252891428 bytes)
692 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link status: starting
693 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Processing url: https://real-debrid.com/d/DZPO2UOGTSJMK
694 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Looking for direct download link...
695 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Direct download link not found
696 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Checking for link errors...
697 | 22.05.2020 01:57:26 | WARNING | HOSTER RealdebridCom[1]: RealdebridCom \| No data to check
698 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Grabbing link info...
699 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link name: DZPO2UOGTSJMK
700 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link size: 30.04 GiB (32252891428 bytes)
701 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Link status: starting
702 | 22.05.2020 01:57:26 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Processing as premium download...
703 | 22.05.2020 01:57:27 | INFO | HOSTER RealdebridCom[1]: RealdebridCom \| Downloading file...
704 | 22.05.2020 01:57:28 | ERROR | <<< UNCAUGHT EXCEPTION >>>
705 | ? | ? | Traceback (most recent call last):

**Comment by jiyari** [comment]
I have found the log of the last download I hope it be will informative

**Comment by GammaC0de** [comment]
Well, this confirm that the issue comes from the OS or Python, not from pyload.

Can you format the external drive to ext4 and try?

**Comment by jiyari** [comment]
Yes I will try to format my flash drive , should I use my osmc to format it ? If yes how? Or by pc ? I have a macbook
OS you mean the format system?

**Comment by GammaC0de** [comment]
For best results, better use a linux system.

See https://discourse.osmc.tv/t/formating-external-drive-to-ext4/78109 but make sure you format the correct drive...

**Comment by jiyari** [comment]
I couldn’t format it it says the following 
/dev/sdb is apparently in use by the system; will not make a filesystem here!

**Comment by GammaC0de** [comment]
You probably should use /dev/sdb1

**Comment by jiyari** [comment]
I just asked remove safely through kodi , then formatted successfully 
Thanks, now I will try to download a large file and will get back to you for results later

**Comment by jiyari** [comment]
Just a question, why sometimes when I reboot osmc , then I cant find pyload , I have to run restart command by ssh ?

**Comment by GammaC0de** [comment]
This is a osmc  issue, not pyload.

**Comment by jiyari** [comment]
Ok thanks , 
I just want to know why while downloading I cant get full speed as I have 300 Mbits internet speed , but I cant get more than 70 Mbits

**Comment by jiyari** [comment]
I want to confirm that formatting mu hard was worked, thanks for your help
