### ISSUE TITLE
Tired of failures

### ISSUE THREAD

**Issue by Merlincool** [pyload/pyload#3653]
### Your question

I have been using this pyload and it works 2 - 3 days and suddenly collapses

I request OP can you come up with permanent solution for this.

https://i.imgur.com/8GanoOm.png

I gave up!!!!!!!!!!!!!!!

### Additional references

I am running vpn.

I was running same set up and it worked for 3-4 days and unfortunately webui stopped so I stopped pyload and vpn and restarted both of them and now it don't work.

I am running latest update build of pyload. The stable build.

**Comment by GammaC0de** [comment]
Run `python pyLoadCore.py -s` and change the  webinterface server to `threaded`, not lightweight as it is now.

**Comment by Merlincool** [comment]
> Run `python pyLoadCore.py -s` and change the webinterface server to `threaded`, not lightweight as it is now.

Ok, what is the difference and I had selected lightweight all the time since I am using.

Thank you for pointing out, why exactly I am suppose to go for threaded

**Comment by GammaC0de** [comment]
Those are different brands of web servers, it should not matter to you which to use as long as it works.
Most use threaded.

**Comment by treysis** [comment]
If you really want to use "lightweight", you could also try setting `dualstack` to `False` in `pyload.conf`. But like that you can't access the webinterface via IPv6.

**Comment by Merlincool** [comment]
Ok thanks guys. I have reconfigured as threaded and it's working now.
