### ISSUE TITLE
tb7.pl multi-hoster

### ISSUE THREAD

**Issue by NitroFuN** [pyload/pyload#3654]
### Describe the plugin

If this possible to create an plugin for polish multihoster site tb7.pl? I asked for API but they doesn't have any API.

### Sample resources

I can share my account if needed

### Additional references

Here are list of hostings supported by that site https://tb7.pl/jdhostingi.txt

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by NitroFuN** [comment]
Done :)

**Comment by NitroFuN** [comment]
I forgot to mention that they have a plugin for Firefox and Chrome which copy links to their website. Maybe will be useful
https://addons.mozilla.org/pl/firefox/addon/wtyczka-tb7-pl/

**Comment by GammaC0de** [comment]
This multihoster is not so stable:

For example it reports it supports rapogator.net but fails to resolve a URL with "Nieaktywne linki" message 😕

**Comment by NitroFuN** [comment]
Thanks for plugin :)

Working fine with rapidu.net links :)

**Comment by the4anoni** [comment]
> This multihoster is not so stable:
> 
> For example it reports it supports rapogator.net but fails to resolve a URL with "Nieaktywne linki" message 😕

Link works in browser?

**Comment by GammaC0de** [comment]
> Link works in browser?

I really don't remember, it was one year ago and I do not have an account now..
