### ISSUE TITLE
[DebridlinkFr] refresh token not retrieved

### ISSUE THREAD

**Issue by hex2a** [pyload/pyload#3655]
### Describe the problem
after creating the "pyLoad" oauth app (with "Device" as grant_type and 1 day `access_token` expire time), the new `GetDebridlinkToken.py` script does not return `refresh_token`

**script output:**

```
Waiting for authorization... 892 {u'access_token': [REMOVED]', u'token_type': u'Bearer', u'expires_in': [REMOVED]}
Traceback (most recent call last):
  File "GetDebridlinkToken.py", line 91, in <module>
    main()
  File "GetDebridlinkToken.py", line 86, in main
    refresh_token = api_data['refresh_token']
KeyError: 'refresh_token'
```

**Comment by GammaC0de** [comment]
Doeas this happen to you every time?

**Comment by hex2a** [comment]
yes (I tried it a few times)

**Comment by GammaC0de** [comment]
This is weird, it works fine with my account.

If you want me to check, i will need access to your account.
Please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by Tockra** [comment]
I sent you an email too. I hope it is okay. Its because of an other problem. But I don't want to make a post here cause the corresponding .dlc contains some links of copy right protected stuff...

**Comment by foxan54** [comment]
i have the same problem but my account isn't premium. I want to try to connect them before I go premium.

**Comment by GammaC0de** [comment]
@foxan54 As far as I know, free user is not supported

Please provide logs of your issue.

**Comment by foxan54** [comment]
`Waiting for authorization... 876 {u'access_token': [I have remove token]', u'token_type': u'Bearer', u'expires_in': 86400}
Traceback (most recent call last):
  File "GetDebridlinkToken.py", line 91, in <module>
    main()
  File "GetDebridlinkToken.py", line 86, in main
    refresh_token = api_data['refresh_token']
KeyError: 'refresh_token'
`
Maybe it's because i'm free user, i will contact debridlink to see if it works with a vps

**Comment by hex2a** [comment]
@foxan54 it does not work if a different IP address is used to confirm the request (via the browser)

**Comment by foxan54** [comment]
hex2a Oh thanks i tried why my VPN (same ip) it worked :)

**Comment by GammaC0de** [comment]
> it does not work if a different IP address is used to confirm the request (via the browser)

This concludes this issue as resolved, closing.
