### ISSUE TITLE
pyload webinterface 

### ISSUE THREAD

**Issue by addic7ed2** [pyload/pyload#3656]
Hi guys i have installed pyload on my raspberry pi 3B+ and after configuring it when opening webinterface in browser is soo so slow both on chrome and firefox .
any help please

**Comment by GammaC0de** [comment]
What type of web server have you chose? you'd best choose `threaded`.

run `/usr/bin/python /opt/pyload/pyLoadCore.py -s` and verify.

**Comment by jbman11** [comment]
I have noticed the same thing recently. I did a full wipe and install again a few weeks ago and it’s now slow as described. I have to use the built in otherwise I get a blank web page with threaded.

**Comment by jbman11** [comment]
Threaded log

31.05.2020 11:52:59 INFO      Starting pyLoad 0.4.20
31.05.2020 11:52:59 INFO      Using home directory: /home/osmc/.pyload
31.05.2020 11:52:59 DEBUG     Remote activated: False
31.05.2020 11:53:01 DEBUG     created index of plugins
31.05.2020 11:53:01 INFO      ADDON ExternalScripts: Activated scripts in folder `download_finished`: run.sh
31.05.2020 11:53:01 INFO      Activated plugins: EventMapper, ExternalScripts, UnSkipOnFail
31.05.2020 11:53:01 INFO      Deactivate plugins: AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checks$
31.05.2020 11:53:01 INFO      Downloadtime: True
31.05.2020 11:53:03 INFO      Starting threaded webserver: 0.0.0.0:8000
31.05.2020 11:53:03 INFO      Free space: 152.10 GiB

**Comment by jbman11** [comment]
Built in log

31.05.2020 11:56:21 INFO      Starting pyLoad 0.4.20
31.05.2020 11:56:21 INFO      Using home directory: /home/osmc/.pyload
31.05.2020 11:56:21 DEBUG     Deleting old pidfile pyload.pid
31.05.2020 11:56:21 DEBUG     Remote activated: False
31.05.2020 11:56:22 DEBUG     created index of plugins
31.05.2020 11:56:22 INFO      ADDON ExternalScripts: Activated scripts in folder `download_finished`: run.sh
31.05.2020 11:56:22 INFO      Activated plugins: EventMapper, ExternalScripts, UnSkipOnFail
31.05.2020 11:56:22 INFO      Deactivate plugins: AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checks$
31.05.2020 11:56:22 INFO      Downloadtime: True
31.05.2020 11:56:23 INFO      Starting builtin webserver: 0.0.0.0:8000
31.05.2020 11:56:23 INFO      Free space: 152.10 GiB

**Comment by jbman11** [comment]
Would love to help to get this fixed

**Comment by vuolter** [comment]
did you tried on the new pyload version, i mean pyLoad Next?

**Comment by jbman11** [comment]
No, I will take a look at that. Thank you
