### ISSUE TITLE
Zippyshare

### ISSUE THREAD

**Issue by maikyyy** [pyload/pyload#3657]
### Describe the problem

Zippyshare Plugin broken, maybe name pattern changed. file.html and size are ok, but file can't be downloaded.

https://www114.zippyshare.com/v/QXULENKV/file.html

https://www114.zippyshare.com/d/QXULENKV/27090/GodWoaIsHrtoFid209GRANDL18pBlRyx6NVERU.part01.rar

### Debug log

373 | 29.05.2020 18:57:01 | DEBUG | HOSTER ZippyshareCom[13]: Plugin version: 0.99
-- | -- | -- | --
374 | 29.05.2020 18:57:01 | DEBUG | HOSTER ZippyshareCom[13]: Plugin status: testing
375 | 29.05.2020 18:57:01 | WARNING | HOSTER ZippyshareCom[13]: Plugin may be unstable
376 | 29.05.2020 18:57:01 | INFO | HOSTER ZippyshareCom[13]: Grabbing link info...
377 | 29.05.2020 18:57:01 | DEBUG | HOSTER ZippyshareCom[13]: Link info: {'status': 2, 'hash': {},  'name': u'GodWoaIsHrtoFid209GRANDL18pBlRyx6NVERU.part01.rar', 'url':  u'http://www114.zippyshare.com/v/QXULENKV/file.html', 'pattern':  {'HOST': u'www114.zippyshare.com', 'U': u'MB', 'S': u'496.86', 'KEY':  u'QXULENKV', 'N': u'GodWoaIsHrtoFid209GRANDL18pBlRyx6NVERU.part01.rar'},  'size': 520995471}
378 | 29.05.2020 18:57:01 | DEBUG | HOSTER ZippyshareCom[13]: Previous link info: {}
379 | 29.05.2020 18:57:01 | INFO | HOSTER ZippyshareCom[13]: Link name: GodWoaIsHrtoFid209GRANDL18pBlRyx6NVERU.part01.rar
380 | 29.05.2020 18:57:01 | INFO | HOSTER ZippyshareCom[13]: Link size: 496.86 MiB (520995471 bytes)
381 | 29.05.2020 18:57:01 | INFO | HOSTER ZippyshareCom[13]: Link status: online
382 | 29.05.2020 18:57:01 | INFO | HOSTER ZippyshareCom[13]: Processing url: http://www114.zippyshare.com/v/QXULENKV/file.html
383 | 29.05.2020 18:57:01 | INFO | HOSTER ZippyshareCom[13]: Looking for direct download link...
384 | 29.05.2020 18:57:01 | DEBUG | HOSTER ZippyshareCom[13]: LOAD URL  http://www114.zippyshare.com/v/QXULENKV/file.html \| redirect=True \|  cookies=True \| get={} \| req=None \| decode=True \| multipart=False \|  post={} \| ref=True \| just_header=True
385 | 29.05.2020 18:57:01 | DEBUG | HOSTER ZippyshareCom[13]: Redirect #1 to: https://www114.zippyshare.com/v/QXULENKV/file.html
386 | 29.05.2020 18:57:01 | DEBUG | HOSTER ZippyshareCom[13]: LOAD URL  https://www114.zippyshare.com/v/QXULENKV/file.html \| redirect=True \|  cookies=True \| get={} \| req=None \| decode=True \| multipart=False \|  post={} \| ref=True \| just_header=True
387 | 29.05.2020 18:57:01 | INFO | HOSTER ZippyshareCom[13]: Direct download link not found
388 | 29.05.2020 18:57:01 | DEBUG | HOSTER ZippyshareCom[13]: LOAD URL  http://www114.zippyshare.com/v/QXULENKV/file.html \| redirect=True \|  cookies=[('zippyshare.com', 'ziplocale', 'en')] \| get={} \| req=None \|  decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
389 | 29.05.2020 18:57:02 | INFO | HOSTER ZippyshareCom[13]: Checking for link errors...
390 | 29.05.2020 18:57:02 | INFO | HOSTER ZippyshareCom[13]: No errors found
391 | 29.05.2020 18:57:02 | INFO | HOSTER ZippyshareCom[13]: Processing as free download...
392 | 29.05.2020 18:57:02 | WARNING | CAPTCHA ZippyshareCom[13]: ReCaptcha \| Key pattern not found
393 | 29.05.2020 18:57:02 | INFO | HOSTER ZippyshareCom[13]: Downloading file...
394 | 29.05.2020 18:57:02 | DEBUG | HOSTER ZippyshareCom[13]: DOWNLOAD URL  http://www114.zippyshare.com/d/QXULENKV/46392/GodWoaIsHrtoFid209GRANDL18pBlRyx6NVERU.part01.rar  \| cookies=True \| resume=None \| get={} \| disposition=True \| chunks=None \|  post={} \| ref=True
395 | 29.05.2020 18:57:02 | WARNING | HOSTER ZippyshareCom[13]: Free download failed \| downloade
396 | 29.05.2020 18:57:02 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
397 | 29.05.2020 18:57:02 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
398 | 29.05.2020 18:57:02 | DEBUG | ADDON ExternalScripts: No script found under folder `package_failed`
399 | 29.05.2020 18:57:02 | WARNING | Download failed: GodWoaIsHrtoFid209GRANDL18pBlRyx6NVERU.part01.rar \| downloade
400 | 29.05.2020 18:57:02 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
401 | 29.05.2020 18:57:02 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: GodWoaIsHrtoFid209GRANDL18pBlRyx6NVERU.part01.rar (pid:4)
402 | 29.05.2020 18:57:02 | INFO | ADDON UnSkipOnFail: No duplicates found

```

```

**Comment by GammaC0de** [comment]
Works fine for me, maybe you have reached some kind of download limit?

**Comment by maikyyy** [comment]
hmmm here is something wrong, even adding dlc is not working anymore.


573 | 29.05.2020 20:24:39 | INFO | Added package add_file containing 0 links
-- | -- | -- | --


dont know what happens

**Comment by GammaC0de** [comment]
Maybe this is issue with DLC, try adding zippyshare link directly and see what happens.

**Comment by maikyyy** [comment]
tested, same as above. can it have to do something with libcurl?

**Comment by GammaC0de** [comment]
Try refresh your pyLoad installation using the instruction in #3283.

**Comment by maikyyy** [comment]
yes, i have installed the latest 0.4.20 and it is already updated to latest stable from github. running fine since last year, but tonight something went wrong. i think i reinstall pyload.

**Comment by maikyyy** [comment]
The problem is solved. Looks like I had a problem with libcurl. After reinstallation everything works as it should.

Brother, send me your Paypal. I want to buy you a coffee.

**Comment by GammaC0de** [comment]
> Brother, send me your Paypal. I want to buy you a coffee.

See my Github profile 😉

**Comment by GammaC0de** [comment]
Thanks for donation mate 😃
