### ISSUE TITLE
Is there a way to automatically collect copied urls?

### ISSUE THREAD

**Issue by parasiteoflife** [pyload/pyload#3668]
I'm new to pyload after using JDownloader for a long time and I was wondering if pyload has a feature like JD to automatically collect the copied urls so we can later choose what to add to the download queue.

**Comment by GammaC0de** [comment]
You can add the links to the `collector` instead of the `queue`.

**Comment by parasiteoflife** [comment]
> You can add the links to the `collector` instead of the `queue`.

Yes, thanks for your help. That's what I was talking of, maybe I phrased it wrong. I want pyload to automatically grab the link in the clipboard and collect them. Right now when I copy some links they aren't detected automatically by pyload.

**Comment by GammaC0de** [comment]
> Right now when I copy some links they aren't detected automatically by pyload

pyLoad is a web application and so, it cannot detect when you copy something to the clipboard.

Nevertheless, You can paste the links to pyload if you press "filter urls" button of the "add package" dialog (it is located right to the "links" title)

**Comment by parasiteoflife** [comment]
Got it. Thank you! Would be nice if it could be added.
