### ISSUE TITLE
MegaNz.py error ordinal not in range(128)

### ISSUE THREAD

**Issue by LeoKesler** [pyload/pyload#367]
Hi, sorry for my bad english.

There are a issue with meganz.py and files with foreign characters ( I guess).

By example, I am trying to download a file called 
(HyuugaDownloads)-_-SSDK_-_008 - Músculos incríveis! O segredo do sensei.mp4

(I can share the link, if you this is needed.)

But this file dont get decrypted.  The log shows this error:

Download failed: (HyuugaDownloads)-_-SSDK_-_008 - Músculos incríveis! O segredo do sensei.mp4.crypted | 'ascii' codec can't encode character u'\xfa' in position 69: ordinal not in range(128)

I can provide links and other files with the same problem.

Thanks and excuse me my bad english and if this the wrong place.

**Comment by vuolter** [comment]
Works for me, are you sure you are using the latest version?

**Comment by morgriv** [comment]
Yes, I'm using v0.23. The hoster/MegaCoNz.py has version == "0.23".
Only 2nd file out of the five succeeded. Unsurprisingly, it is the only one without any accented characters in the file name. See this log for details: http://pastebin.com/EFfXaRdH

**Comment by vuolter** [comment]
Please enable debug mode (webui -> config -> general -> debug mode) and re-post the log. :)

**Comment by morgriv** [comment]
Here you go: http://pastebin.com/W9wxcnDU

**Comment by vuolter** [comment]
Still working for me. Are you under windows or linux?

**Comment by morgriv** [comment]
I'm running it on Synology DSM 5.1, basically a Linux distro. It's using Python 2.7.9.
Here's the debug_Report.txt: http://pastebin.com/wFTFMr1y
And the api_response_line88.dump.html: http://pastebin.com/YtqKT04K

**Comment by morgriv** [comment]
Sweet. It works perfectly now. Thanks a lot for the support @vuolter :-)

**Comment by Roburetto** [comment]
This issue seems to be back.

"failed'ascii' codec can't encode character u'\xf3' in position 4: ordinal not in range(128) 90.36 MiBMegaCoNz"

LOG here: http://pastebin.com/jmNq1075

Debug Report attached.

[debug_MegaCoNz_07-09-2016_11-39-36.zip](https://github.com/pyload/pyload/files/458894/debug_MegaCoNz_07-09-2016_11-39-36.zip)
