### ISSUE TITLE
Alldebrid download failure

### ISSUE THREAD

**Issue by abdullah0ahmed** [pyload/pyload#3678]
hello, 
I did connect a premium alldebrid account to my pyload that is in a server. 
when I paste a link (ex. https://uptobox.com/00qnf944ykyd), it takes uptobox.com as hoster and not using my alldebrid premium account. 
I turned the uptobox hoster OFF, and still cannot download with my plugin.

not only that, suppose that I don't want to use the plugin, and i have a direct download link from alldebrid. when I add it to download it, it doesn't work at all. and when I put it in some other downloader it works!

so these are the two issues I am facing.. 

Thank you

**Comment by GammaC0de** [comment]
Is this a new pyload installation?
How exactly have you installed it?

**Comment by abdullah0ahmed** [comment]
This is version: 0.4.20

I didn't install it myself. It came as service with a seedbox.

**Comment by GammaC0de** [comment]
Try refreshing your installation using the instructions in #3283
