### ISSUE TITLE
Problems while parsing links (clickandload, dlc) containing UTF-8 letters

### ISSUE THREAD

**Issue by Tockra** [pyload/pyload#3679]
Some dlcs / ClickAndLoad from filecrypt doesn't work (rapidgator).
Jdownloader can work with them. 

I think the problem is caused by "ä, ö, ü and ß " in the filenames.

If you need a example, I can send you one per private message.

### Debug log
```bash
 Database Error @ addLinks (...)
{} You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
pyload_1  | 30.06.2020 19:04:57 INFO      Added package Name - filecrypt.cc containing 24 links
```

**Comment by GammaC0de** [comment]
> If you need a example

Please send example

**Comment by Tockra** [comment]
> > If you need a example
> 
> Please send example

I already sent one to your email address. Because I can't reproduce the problem I sent a link to you where I noticed the problem. But I don't want to send this link in public...

**Comment by Tockra** [comment]
Ah okay sorry I'm seeing you sent me a answere:
https://github.com/pyload/pyload/issues/3283

But I'm using a docker image of pyload. So I'll get a fresh installation everytime when I build the image. /opt/pyload/pyload-config is the once directory which won't updated. So I removed the userplugins folder. But nothing changed after rebuilding the docker image.

Here some errors:
```bash
 Database Error @ addLinks (...)
{} You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
pyload_1  | 30.06.2020 19:04:57 INFO      Added package Name - filecrypt.cc containing 24 links

```

**Comment by GammaC0de** [comment]
> I already sent one to your email address (some days ago)

I tested the link you have sent and it worked fine...

Please send more examples.

**Comment by Tockra** [comment]
I can't grow them. I just have a second example. But if that works maybe you need to set your browser language to german to ensure click and load causes the same issue

**Comment by GammaC0de** [comment]
So the issue is with ClickAndLoad, not DLC?

**Comment by Tockra** [comment]
Both

**Comment by GammaC0de** [comment]
What OS are you using?
Are you able to download URLs containing filenames with UTF-8 letters?  (not ClickAndLoad/DLC)

**Comment by Tockra** [comment]
I can solute that problem by copying the links to jdownloader and then creating my own dlc. This dlc will be parsed by pyload.

I'm using pyload in a docker image (linux debian or ubuntu)

**Comment by GammaC0de** [comment]
> I'm using pyload in a docker image

Where from have you got this image?

**Comment by Tockra** [comment]
I don't know. I can look for it this evening.
But the Dockerfile just installs the necessary dependencies and clones the master branch of pyload.

**Comment by GammaC0de** [comment]
These are the images known to me, I suggest you try them:
https://hub.docker.com/r/writl/pyload/
https://hub.docker.com/r/linuxserver/pyload

**Comment by Tockra** [comment]
I'm using writl/pyload

**Comment by Tockra** [comment]
What do you think?

**Comment by GammaC0de** [comment]
Can you try it without docker?

I need more examples.

**Comment by Tockra** [comment]
Sent you multiple links. Some doesn't work. Some just contains a 2-4 links (instead of 16 or more). 
Maybe I can install pyload on my laptop but my server don't has a python installation.

**Comment by Tockra** [comment]
Could you reproduce the problems?

**Comment by Tockra** [comment]
Okay I will try to debug that on my own. But I need your help for my setup. I didn't work with python for a long while. And that has a reason...

Should I use a Docker image to debug? 
What is the workflow? Is setup.py important? 
Are there debug flaggs in your application?

**Comment by Tockra** [comment]
Okay found it out. 

I can give you the program part which causes the error. It is module/database/FileDatabase.py line 625.

Error:
```python
Traceback (most recent call last):
  File "/Users/timtannert/Documents/pyload/module/database/DatabaseBackend.py", line 96, in processJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/Users/timtannert/Documents/pyload/module/database/FileDatabase.py", line 625, in addLinks
    self.c.executemany('INSERT INTO links(url, name, plugin, package, linkorder) VALUES(?,?,?,?,?)', links)
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

```
Please don't let me fix it. I hate python. Really it is the worst I know...

**Comment by GammaC0de** [comment]
Sorry for not responding, I've been busy with a new project I'm building.

Checking..

**Comment by Tockra** [comment]
No problem. This is not your job and you don't get money for it...
Hopefuly your next project is in a better language ^^

**Comment by GammaC0de** [comment]
Here you go, fixed.

> Hopefuly your next project is in a better language ^^

Well, it's in Javascript which I consider yuck, I'd rather Python any day.

**Comment by Tockra** [comment]
Thank you ;)
