### ISSUE TITLE
DDownload: Capcha displayed incorrectly

### ISSUE THREAD

**Issue by alex9434** [pyload/pyload#3681]
### Describe the problem

The capcha for DDownload is displayed incorrectly using Tampermonkey and pylaod script: The capcha window is not resized to the full size making it impossible to solve the capcha (see screenshot). Same problem with Chrome and Firefox on Windows and Linux. Other OCHs (e.g. uploaded.to) resize the window correctly with the same setup.

### Debug log

```
Logfile does not show errors
```

### Screenshots

![Screenshot from 2020-07-07 17-01-17](https://user-images.githubusercontent.com/8560446/86755536-4c79a000-c074-11ea-85d2-ecd2d6a0146c.png)

### Additional references

pyLoad 4.4.20 with Python 2.7.18 on Openwrt 19.07.3

**Comment by GammaC0de** [comment]
does this happen every time you open a captcha?

**Comment by alex9434** [comment]
It happens every time with DDownload. It does not happen at all with other OCHs (e.g. Uploaded.to)

**Comment by GammaC0de** [comment]
Well, it does not happen to me.

So if you want me to test this,
 I need that you give me access to a test machine with pyLoad and Firefox.

Please install anydesk and then send the anydesk ID and password to nitzo2001 at yahoo dot com.

**Comment by alex9434** [comment]
Sure, I have set-up a test system and send you the information by email. Please give me an update if you have identified the issue.

**Comment by GammaC0de** [comment]
> I have set-up a test system

Is this a VM?
Can you upload it somewhere?

**Comment by alex9434** [comment]
No, it is not a VM. However, it is a fresh install of pyload and Firefox ESR with Tampermonkey on Debian 10. So it should be very straightforward to replicate. As I said, this issue is only with DDownload not other OCHs.

**Comment by alex9434** [comment]
Hi @GammaC0de , have you been able to observe the issue? Do you still need access to the environment?

**Comment by tanrak** [comment]
I have the same problem.
See also https://github.com/pyload/pyload/issues/3607

**Comment by alex9434** [comment]
Hi @tanrak @dirdi and @GammaC0de, I agree this issue is a duplicate of #3607.

**Comment by GammaC0de** [comment]
OK, I now have a VM with Debian 10 with this issue in effect,
Will keep you updated.

**Comment by alex9434** [comment]
Thank you very much, appreciated!

**Comment by alex9434** [comment]
Hi @GammaC0de , I just found out that the https://douploads.net/ plugin has exactly the same issue that I have described above.

**Comment by GammaC0de** [comment]
@alex9434 https://douploads.net/ is not supported by pyload (pyload has yet no plugin for it)

**Comment by tanrak** [comment]
Any news about the #3681 and #3607 ?

**Comment by GammaC0de** [comment]
This is really annoying but to catch, 
Once it was not working and suddenly it started working

**Comment by tanrak** [comment]
That's exactly how it is. I know, i's a first world problem but realy pesky. By the way.  Thanks for your great commitment to pyload.

**Comment by alex9434** [comment]
Hi GammaC0de, any update on this? Still not resolved on my instance. I have the same issue with the hoster UploadgigCom. Do you have any tipps on what I can do to solve the issue?

**Comment by tanrak** [comment]
In the last three months, I did not experience the problem again. Maybe we can close this issue? @alex9434 Do you still experience this problem?

**Comment by alex9434** [comment]
Hi @tanrak , apologies for the late reply. I still have the problem on Chrome and Firefox on Linux. I do not have the problem on Firefox on Windows 10. So it seems to be connected to the OS of the browser.
