### ISSUE TITLE
AttributeError, TypeError and ValueError when starting the program

### ISSUE THREAD

**Issue by AlphaJack** [pyload/pyload#3683]
### Describe the problem
I can't start the program because I get these error on startup (log file attached below).
I'm using the latest version of `pyload-nightly` available in the AUR, which follows [this installation process](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pyload-nightly). I created a system user with home in /var/lib/pyload to run it as a daemon. 

The [stable version](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pyload-git) is able to start without any problem via `sudo -u pyload /usr/bin/pyLoadCore`

### Debug log
Launched with `sudo -u pyload /usr/bin/pyload`, but I get the same result running `pyload` with my user
[pyload-stderr.log](https://github.com/pyload/pyload/files/4909457/pyload-stderr.log)

**Comment by vuolter** [comment]
It should work now.
