### ISSUE TITLE
pyload not found

### ISSUE THREAD

**Issue by zzzzzzli** [pyload/pyload#3685]
### Your question

Why the command `pyload` not found? I installed it successfully using the command `sudo pip3 install pyload-ng[all]` without error. Thankyou.

**Comment by GammaC0de** [comment]
For installing pyload you need python 2.7 and one of the releases that suits you OS: https://github.com/pyload/pyload/releases/tag/0.4.20

**Comment by zzzzzzli** [comment]
Okey, thank you very much.

**Comment by GammaC0de** [comment]
👍
