### ISSUE TITLE
Real Debrid links uses BasePlugin to download instead

### ISSUE THREAD

**Issue by Fa1salH** [pyload/pyload#3686]
### Describe the problem

I installed pyload using docker and I added my real debrid account and everything seems to be set up correctly but when I add a real debrid link I get an error failed Bad server response: 503 Service Unavailable  BasePlugin
and If I'm not mistaken pyload uses baseplugin to download and that's why. I tried to disable BasePlugin but I keep getting the same error

### Debug log

```

594 | 14.07.2020 13:23:13 | INFO | ADDON UnSkipOnFail: No duplicates found
595 | 14.07.2020 13:23:31 | INFO | Added package 321 containing 1 links
596 | 14.07.2020 13:23:31 | INFO | Download starts: https://33.download.real-debrid.com/d/abc.mkv
597 | 14.07.2020 13:23:31 | WARNING | HOSTER BasePlugin[133]: Plugin may be unstable
598 | 14.07.2020 13:23:31 | INFO | HOSTER BasePlugin[133]: Grabbing link info...
599 | 14.07.2020 13:23:31 | INFO | HOSTER BasePlugin[133]: Link name: AAA.mkv
600 | 14.07.2020 13:23:31 | INFO | HOSTER BasePlugin[133]: Link size: N/D
601 | 14.07.2020 13:23:31 | INFO | HOSTER BasePlugin[133]: Link status: starting
602 | 14.07.2020 13:23:31 | INFO | HOSTER BasePlugin[133]: Processing url: https://33.download.real-debrid.com/d/abc.mkv
603 | 14.07.2020 13:23:31 | WARNING | Download failed: abc.mkv \| Bad server response: 503 Service Unavailable



```

**Comment by GammaC0de** [comment]
From where have you got the real debrid link?

**Comment by Fa1salH** [comment]
> From where have you got the real debrid link?

I don't get that question. I copied it it was a mega link and I used RD to convert it

**Comment by GammaC0de** [comment]
You should have put the mega link into pyload...

**Comment by Fa1salH** [comment]
when I do that I get:
`failed Parse error: Free decrypted link not found | Plugin may be out of date  XFileSharingFolder`

**Comment by GammaC0de** [comment]
Please disable `XFileSharing ` plugin

**Comment by Fa1salH** [comment]
after doing that it uses MegaCoNz plugin and returns `ip_not_allowed`
I tried disabling it but it kept using it

**Comment by GammaC0de** [comment]
Please enable debug mode and then delete the package, retry the URL and then post the log here.

**Comment by Fa1salH** [comment]
Using google drive links it worked fine and used RD plugin, now my issue is with RD themself since my server's IP is blocked
