### ISSUE TITLE
pycurl

### ISSUE THREAD

**Issue by Schlunze** [pyload/pyload#3689]
Hello,

it looks like there is an issue with pycurl in archlinux.
Log says "pycurl error 23: Failure writing output to destination"
the package is up to date:
python2-pycurl-7.43.0.5-1
python-pycurl-7.43.0.5-1

Do you have any advice?
Greetings

**Comment by NaVeZZe** [comment]
Hi,

i have the same issue from around mid june, i'm using a raspberry pi 3 with archlinux arm.
if i look in the download folder at the end of the process i find 2 files, filename.ext.chunk0 and filename.ext.chunks i usually delete the second one and rename the first.
tested for the moment with mkv and mp4 files and they work

**Comment by Schlunze** [comment]
you realize it's vacation time since june here :)

Cheers

**Comment by matrog** [comment]
I'm having same issue on Synology

`

469 | 10.08.2020 09:40:18 | ERROR | pycurl error 23: Failure writing output to destination
-- | -- | -- | --
468 | 10.08.2020 09:40:18 | DEBUG | pycurl exception 23: Failure writing output to destination
467 | 10.08.2020 09:40:18 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
466 | 10.08.2020 09:40:18 | DEBUG | Chunk 1 failed: (23, 'Failure writing output to destination')
465 | 10.08.2020 09:40:17 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
464 | 10.08.2020 09:40:17 | INFO | ADDON UnSkipOnFail: No duplicates found
463 | 10.08.2020 09:40:17 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: xxxxxxx.pdf (pid:2)
462 | 10.08.2020 09:40:17 | INFO | Debug Report written to debug_EasybytezCom_10-08-2020_09-40-17.zip
461 | 10.08.2020 09:40:17 | ERROR | pycurl error 23: Failure writing output to destination
460 | 10.08.2020 09:40:17 | DEBUG | pycurl exception 23: Failure writing output to destination
459 | 10.08.2020 09:40:17 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
458 | 10.08.2020 09:40:17 | DEBUG | Chunk 1 failed: (23, 'Failure writing output to destination')
457 | 10.08.2020 09:40:17 | DEBUG | Invalid curl handle -> closed
456 | 10.08.2020 09:40:17 | DEBUG | Invalid curl handle -> closed
455 | 10.08.2020 09:40:17 | DEBUG | Resume File from 4552377

`
it seems to point to a permission issue but some files are written and some not

**Comment by GammaC0de** [comment]
Maybe this can help you:
https://stackoverflow.com/questions/19606447/pycurl-and-io-stringio-pycurl-error-23-failed-writing-body

Also, make sure you are using python 2.7

**Comment by matrog** [comment]
the version is ok

```
/volume1/\@appstore/pyload/env/bin/python --version
Python 2.7.18
```

unfortunately i'm not a python expert so that link didn't help me. Would be interesting to know if it depends on the hoster, i'm having issues with easybytez

**Comment by matrog** [comment]
solved doing rollback on python package...it works with this Python 2.7.14

**Comment by nyyu** [comment]
This return 0 make the write error : https://github.com/pyload/pyload/blob/b5518176585bd843d95023e26bb0795818ba2afe/module/network/HTTPChunk.py#L257

**Comment by GammaC0de** [comment]
The cause of this issue is [this PR](https://github.com/curl/curl/pull/5596) causing [HTTPDownload.py#L229](https://github.com/pyload/pyload/blob/stable/module/network/HTTPDownload.py#L229 ) not ignore this exception.

I will try to issue a PR there.
