### ISSUE TITLE
rapidgatornet captcha do not load

### ISSUE THREAD

**Issue by punkelchen** [pyload/pyload#3691]
### Describe the problem

The Captcha form Rapidgatornet don't load.

### Debug log

```
on firefox consol shows the error
"X-Frame-Options"-Direktive "SAMEORIGIN"
```

### Additional references

[Mozialla Link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)

**Comment by GammaC0de** [comment]
Please install https://addons.mozilla.org/firefox/addon/ignore-x-frame-options-header/

**Comment by punkelchen** [comment]
thanks that helps

**Comment by GammaC0de** [comment]
👍
