### ISSUE TITLE
Unable to download from filecrypt.cc referrer.

### ISSUE THREAD

**Issue by 4gql** [pyload/pyload#3694]
### Describe the problem

In the following text I redacted some concrete links with the letter x. For concrete examples please let me know where I can send you an non-public email. Filecrypt.cc provides a DLC as well as links to files hosted on Turbobit.net! The downloaded DLC file starts up the XFileSharing Plugin that does fail with:
```
550 | 25.07.2020 23:01:35 | WARNING | HOSTER XFileSharing[244]: TurbTo \| Plugin may be unstable
551 | 25.07.2020 23:01:35 | INFO | HOSTER XFileSharing[244]: TurbTo \| Grabbing link info...
552 | 25.07.2020 23:01:36 | INFO | HOSTER XFileSharing[244]: TurbTo \| Link name: xxxxxx.html
553 | 25.07.2020 23:01:36 | INFO | HOSTER XFileSharing[244]: TurbTo \| Link size: N/D
554 | 25.07.2020 23:01:36 | INFO | HOSTER XFileSharing[244]: TurbTo \| Link status: starting
555 | 25.07.2020 23:01:36 | INFO | HOSTER XFileSharing[244]: TurbTo \| Processing url: https://turb.to/xxxxxx.html
556 | 25.07.2020 23:01:37 | INFO | HOSTER XFileSharing[244]: TurbTo \| Checking for link errors...
557 | 25.07.2020 23:01:37 | INFO | HOSTER XFileSharing[244]: TurbTo \| No errors found
558 | 25.07.2020 23:01:37 | INFO | HOSTER XFileSharing[244]: TurbTo \| Grabbing link info...
559 | 25.07.2020 23:01:37 | INFO | HOSTER XFileSharing[244]: TurbTo \| Link name: xxxxxx.html
560 | 25.07.2020 23:01:37 | INFO | HOSTER XFileSharing[244]: TurbTo \| Link size: N/D
561 | 25.07.2020 23:01:37 | INFO | HOSTER XFileSharing[244]: TurbTo \| Link status: starting
562 | 25.07.2020 23:01:37 | INFO | HOSTER XFileSharing[244]: TurbTo \| Processing as free download...
563 | 25.07.2020 23:01:37 | INFO | HOSTER XFileSharing[244]: TurbTo \| Checking for link errors...
564 | 25.07.2020 23:01:37 | INFO | HOSTER XFileSharing[244]: TurbTo \| No errors found
565 | 25.07.2020 23:01:37 | WARNING | HOSTER XFileSharing[244]: TurbTo \| Free download failed \| Max retries reached
566 | 25.07.2020 23:01:37 | WARNING | Download failed: xxxxxx.html \| Max retries reached
567 | 25.07.2020 23:01:37 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: xxxxxx.html (pid:29)
568 | 25.07.2020 23:01:37 | INFO | ADDON UnSkipOnFail: No duplicates found
```
When I try to open the links directly they have a URL like this:
https://filecrypt.cc/Link/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.html while the content displayed is a original Turbobit download site. When I enter this long URL into pyload it downloads the site html code instead of the file.

**Comment by GammaC0de** [comment]
Please disable XFileSharing plugin

**Comment by 4gql** [comment]
I set XFileSharing Plugin "Activated:" to "off".
Now I get:

582	27.07.2020 21:31:30	INFO	Starting pyLoad 0.4.20
583	27.07.2020 21:31:30	INFO	Using home directory: /config
584	27.07.2020 21:31:30	INFO	Activated plugins: ClickNLoad, EventMapper, ExternalScripts, TORRENT, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
585	27.07.2020 21:31:30	INFO	Deactivate plugins: AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
586	27.07.2020 21:31:30	INFO	Downloadtime: True
587	27.07.2020 21:31:30	INFO	Starting ThriftBackend: 0.0.0.0:7227
588	27.07.2020 21:31:30	INFO	Starting builtin webserver: :::8000
589	27.07.2020 21:31:30	INFO	Free space: 1.55 TiB
590	27.07.2020 21:31:30	INFO	Activating Accounts...
591	27.07.2020 21:31:30	INFO	ACCOUNT RapidgatorNet: Adding user `taz*******`...
592	27.07.2020 21:31:30	INFO	ACCOUNT RapidgatorNet: Login user `taz*******`...
593	27.07.2020 21:31:30	INFO	ACCOUNT RapidgatorNet: Grabbing account info for user `taz*******`...
594	27.07.2020 21:31:30	INFO	ACCOUNT TurbobitNet: Adding user `taz*******`...
595	27.07.2020 21:31:30	INFO	ACCOUNT TurbobitNet: Login user `taz*******`...
596	27.07.2020 21:31:31	INFO	ACCOUNT TurbobitNet: Grabbing account info for user `taz*******`...
597	27.07.2020 21:31:31	INFO	Activating Plugins...
598	27.07.2020 21:31:31	WARNING	ADDON TORRENT: torrents / magnets are not associated with any plugin
599	27.07.2020 21:31:31	INFO	ADDON XFileSharing: Auto-discover new hosters
600	27.07.2020 21:31:31	INFO	ADDON XFileSharing: Auto-discover new crypters
601	27.07.2020 21:31:31	INFO	pyLoad is up and running
602	27.07.2020 21:31:31	INFO	ADDON UpdateManager: pyLoad is up to date!
603	27.07.2020 21:31:31	INFO	ADDON UpdateManager: All plugins are up to date!
604	27.07.2020 21:31:37	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
605	27.07.2020 21:32:57	INFO	Added package add_file containing 1 links
606	27.07.2020 21:32:59	INFO	Decrypting starts: /downloads/tmp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.dlc
607	27.07.2020 21:32:59	WARNING	CONTAINER DLC[246]: Plugin may be unstable
608	27.07.2020 21:32:59	INFO	CONTAINER DLC[246]: Grabbing link info...
609	27.07.2020 21:32:59	INFO	CONTAINER DLC[246]: Link name: tmp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.dlc
610	27.07.2020 21:32:59	INFO	CONTAINER DLC[246]: Link size: N/D
611	27.07.2020 21:32:59	INFO	CONTAINER DLC[246]: Link status: starting
612	27.07.2020 21:32:59	INFO	CONTAINER DLC[246]: Processing url: /downloads/tmp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.dlc
613	27.07.2020 21:32:59	INFO	CONTAINER DLC[246]: Path deleted: /downloads/tmp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.dlc
614	27.07.2020 21:32:59	INFO	CONTAINER DLC[246]: Create package: xxxxx | 1 links
615	27.07.2020 21:32:59	INFO	Added package xxxxx containing 1 links
616	27.07.2020 21:32:59	INFO	CONTAINER DLC[246]: Save package `xxxxx` to folder: xxxxx
617	27.07.2020 21:33:01	INFO	Download starts: https://turb.cc/xxxxxxxxxxxx.html
618	27.07.2020 21:33:01	WARNING	HOSTER BasePlugin[247]: Plugin may be unstable
619	27.07.2020 21:33:01	INFO	HOSTER BasePlugin[247]: Grabbing link info...
620	27.07.2020 21:33:01	INFO	HOSTER BasePlugin[247]: Link name: xxxxxxxxxxxx.html
621	27.07.2020 21:33:01	INFO	HOSTER BasePlugin[247]: Link size: N/D
622	27.07.2020 21:33:01	INFO	HOSTER BasePlugin[247]: Link status: starting
623	27.07.2020 21:33:01	INFO	HOSTER BasePlugin[247]: Processing url: https://turb.cc/xxxxxxxxxxxx.html
624	27.07.2020 21:33:02	INFO	HOSTER BasePlugin[247]: File saved
625	27.07.2020 21:33:02	WARNING	HOSTER BasePlugin[247]: Check result: Html file | Waiting 1 minute and retry
626	27.07.2020 21:33:02	INFO	HOSTER BasePlugin[247]: Waiting 1 minutes...
627	27.07.2020 21:34:05	INFO	Download restarted: xxxxxxxxxxxx.html | Html file
628	27.07.2020 21:34:05	INFO	Download starts: xxxxxxxxxxxx.html
629	27.07.2020 21:34:05	WARNING	HOSTER BasePlugin[247]: Plugin may be unstable
630	27.07.2020 21:34:05	INFO	HOSTER BasePlugin[247]: Grabbing link info...
631	27.07.2020 21:34:05	INFO	HOSTER BasePlugin[247]: Link name: xxxxxxxxxxxx.html
632	27.07.2020 21:34:05	INFO	HOSTER BasePlugin[247]: Link size: 185.00 B (185 bytes)
633	27.07.2020 21:34:05	INFO	HOSTER BasePlugin[247]: Link status: starting
634	27.07.2020 21:34:05	INFO	HOSTER BasePlugin[247]: Processing url: https://turb.cc/xxxxxxxxxxxx.html
635	27.07.2020 21:34:06	INFO	HOSTER BasePlugin[247]: File saved
636	27.07.2020 21:34:06	WARNING	HOSTER BasePlugin[247]: Check result: Html file | Waiting 1 minute and retry
637	27.07.2020 21:34:06	INFO	HOSTER BasePlugin[247]: Waiting 1 minutes...

**Comment by GammaC0de** [comment]
Plugin updated, please recheck.
