### ISSUE TITLE
Torrent plugin manager is Broken, torrent is unusable

### ISSUE THREAD

**Issue by yonix06** [pyload/pyload#3696]
ALL TORRENT PLUGIN FAIL
### Describe the problem

All Torrent plugin are broken.

TORRENT plugin cant hold a config setting, and ALWAYS RESET, no matter what i do, i even edited the file plugin conf manully, it goes back every time.

Im loosing it, seriously.

### Debug log

```
Yes, done, but no more info, beside this:

27.07.2020 23:11:11 | INFO | ADDON TORRENT: Using DebridlinkFrTorrent to handle torrents / magnets


27.07.2020 23:12:17 | ERROR | CONTAINER TORRENT[2]: No plugin is associated with torrents / magnets \| Please go to plugin settings -> TORRENT and select your preferred plugin
--
229 | ? | ? | Traceback (most recent call last):
230 | ? | ? | File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
231 | ? | ? | self.__bootstrap_inner()
232 | ? | ? | File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
233 | ? | ? | self.run()
234 | ? | ? | File "/app/pyload/module/PluginThread.py", line 363, in run
235 | ? | ? | self.active.plugin.preprocessing(self)
236 | ? | ? | File "/app/pyload/module/plugins/internal/Base.py", line 291, in preprocessing
237 | ? | ? | return self._process(*args, **kwargs)
238 | ? | ? | File "/app/pyload/module/plugins/internal/Base.py", line 281, in _process
239 | ? | ? | self.process(self.pyfile)
240 | ? | ? | File "/app/pyload/module/plugins/container/TORRENT.py", line 32, in process
241 | ? | ? | _("Please go to plugin settings -> TORRENT and select your preferred plugin"))





```

### Screenshots

no need.

**Comment by GammaC0de** [comment]
TORRENT was just updated,

As a result,
you have to reconfigure the plugin and the delete and then readd all the torrents URLs.

**Comment by yonix06** [comment]
Hello,

first of all: Thanks for your fast answer.

Second, i did that 2 times already before opening a ticket, i did delete everything and started over on a new config.

So i did that twice, results are the same, the config is unloading everytime.

For information: im using the "c:DebridlinkFrTorrent", i reconfigured the account with the script provided and the account setting seems to hold fine, but the torrent plugin config is ereasing everytime.

So i do this in this order precisely:
I change the TORRENT plugin config, then hit save.
i check the log and it says torrent are handled by C:debridlinkFrTorrent, so all seems fine.
I relaunch the torrent file previoulsy added (maybe i should delete entierly the torrent file and add it again ?)
And it fails, saying no torrent plug in is configured.
