### ISSUE TITLE
RealDebrid not working / Failed to load hoster list

### ISSUE THREAD

**Issue by asdproton** [pyload/pyload#3697]
### Describe the problem
When I put Rapidgator or Uploaded Links into pyload it was my expectation that the realdebrid plugin (I have a premium account) would pick those up, request the direct links and start downloading (if possible via Real Debrid direct links). However this often (if not always) fails.

What I find in the logis

ACCOUNT RealdebridCom: Failed to load hoster list for user ...

I have several premium accounts on top of RD (e.g. smoozed) and put in Uploaded.To links. I was surprised to see that pyload used the smoozed premium. I configured the RD plugin to use listed hosts only and set the filter to "RapidgatorNet,UploadedTo,AlfafileNet,DailymotionCom,TurbobitNet"

And on smoozed I did a similar thing with a list NOT including UploadedTo. Still pyload chose Smoozed instead of Rapidgator.

If I go to the RD website, put the links there and convert them to RD links and enter those links into pyload the BasePlugin is being used and the download works like a charm.

Here is an example of an Uploaded DLC:

```
30.07.2020 12:27:18 | WARNING | HOSTER UploadedTo[165]: Plugin may be unstable
-- | -- | --
1003 | 30.07.2020 12:27:18 | INFO | HOSTER UploadedTo[165]: Grabbing link info...
1004 | 30.07.2020 12:27:18 | ERROR | ACCOUNT RealdebridCom: Failed to load hoster list for user `**********`, retry in 5 minutes
1005 | 30.07.2020 12:27:18 | INFO | HOSTER UploadedTo[165]: Link name: *******.rar
1006 | 30.07.2020 12:27:18 | INFO | HOSTER UploadedTo[165]: Link size: 450.00 MiB (471859203 bytes)
1007 | 30.07.2020 12:27:18 | INFO | HOSTER UploadedTo[165]: Link status: online
1008 | 30.07.2020 12:27:18 | INFO | HOSTER UploadedTo[165]: Processing url: http://uploaded.net/file/*****
1009 | 30.07.2020 12:27:18 | INFO | HOSTER UploadedTo[165]: Looking for direct download link...
1010 | 30.07.2020 12:27:18 | INFO | HOSTER UploadedTo[165]: Direct download link not found
1011 | 30.07.2020 12:27:18 | INFO | HOSTER UploadedTo[165]: Checking for link errors...
1012 | 30.07.2020 12:27:18 | INFO | HOSTER UploadedTo[165]: Waiting 30 seconds...

1014 | 30.07.2020 12:27:50 | INFO | HOSTER UploadedTo[165]: No errors found
-- | -- | -- | --
1015 | 30.07.2020 12:27:50 | INFO | HOSTER UploadedTo[165]: Processing as free download...


```

So the RD plugin does not kick in.

**Comment by GammaC0de** [comment]
Works fine for me,
maybe your IP is banned?

**Comment by asdproton** [comment]
When I manually log into RD from the same IP all is fine and I can convert links etc. Would "Failed to load Hoster list for user ..." explain the other error though? If it cannot get a Hoster list it probably does not know what Hosters it should support so that e.g. an UploadedTo DLC would be transferred to the uploaded plugin instead of the RD plugin. So far correct?

Then the "only" open issue would be why it cannot get the host list. Authentication worked flawlessly.... Any idea of how to debug this? I have 2FA on.

**Comment by GammaC0de** [comment]
Your log lacks the most important part - the login attempt..

"Failed to load Hoster list for user ..."  may be as a result of a login failure.

Also,
Please enable DEBUG mode inside pyload's configuration.

**Comment by asdproton** [comment]
`
10.08.2020 11:59:46 | DEBUG | ACCOUNT RealdebridCom: Account info for user `XXX*******`: {'login': {'timestamp': 1597060785.848956, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'api_token': XXX', 'validuntil': 1603980660.186677, 'login': 'XXX*******', 'type': 'RealdebridCom', 'options': {'limitDL': ['0']}}}
26 | 10.08.2020 11:59:46 | INFO | Activating Plugins...
27 | 10.08.2020 11:59:46 | WARNING | ADDON TORRENT: torrents / magnets are not associated with any plugin
28 | 10.08.2020 11:59:46 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_start`
29 | 10.08.2020 11:59:46 | DEBUG | ADDON ExtractArchive: Found HjSplit 0.02 \| Found UnRar 5.50 \| Found UnZip 2.7.17 \| Found UnTar 2.7.17
30 | 10.08.2020 11:59:46 | DEBUG | Redirected import module.plugins.hoster.OneFichierCom -> userplugins.hoster.OneFichierCom
31 | 10.08.2020 11:59:46 | DEBUG | Redirected import userplugins.internal.SimpleHoster -> module.plugins.internal.SimpleHoster
32 | 10.08.2020 11:59:46 | DEBUG | Redirected import module.plugins.hoster.TurbobitNet -> userplugins.hoster.TurbobitNet
33 | 10.08.2020 11:59:46 | DEBUG | Redirected import userplugins.captcha.ReCaptcha -> module.plugins.captcha.ReCaptcha
34 | 10.08.2020 11:59:46 | INFO | ADDON XFileSharing: Auto-discover new hosters
35 | 10.08.2020 11:59:46 | DEBUG | ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com\|clicknupload\.org\|cramit\.in\|ddownload\.com\|easybytez\.com\|exashare\.com\|filejoker\.net\|fileom\.com\|filerio\.com\|fistfast\.net\|hugefiles\.net\|junocloud\.me\|katfile\.com\|movreel\.com\|nosupload\.com\|novafile\.com\|rapidfileshare\.net\|rarefile\.net\|safesharing\.eu\|secureupload\.eu\|streamcloud\.eu\|suprafiles\.me\|tusfiles\.net\|uploadrocket\.net\|vidplay\.net))(?P(?:[\d.]+\|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W\|$)
36 | 10.08.2020 11:59:47 | DEBUG | Redirected import module.plugins.crypter.MultiUpOrg -> userplugins.crypter.MultiUpOrg
37 | 10.08.2020 11:59:47 | DEBUG | Redirected import userplugins.internal.SimpleCrypter -> module.plugins.internal.SimpleCrypter
38 | 10.08.2020 11:59:47 | INFO | ADDON XFileSharing: Auto-discover new crypters
39 | 10.08.2020 11:59:47 | DEBUG | ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com\|tusfiles\.net))(?P(?:[\d.]+\|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user\|folder)s?/\w+
40 | 10.08.2020 11:59:47 | DEBUG | ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/updates/master/plugins.txt \| redirect=True \| cookies=True \| get={'v': '0.4.20'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
41 | 10.08.2020 11:59:47 | INFO | pyLoad is up and running
42 | 10.08.2020 11:59:47 | INFO | ADDON UpdateManager: pyLoad is up to date!
43 | 10.08.2020 11:59:47 | DEBUG | ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/updates/master/plugins.txt \| redirect=True \| cookies=True \| get={'v': '0.4.20'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
44 | 10.08.2020 11:59:47 | DEBUG | ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'FreeWayMe'), (u'accounts', u'GetTwentyFourOrg'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'ShareonlineBiz'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'ShareonlineBiz'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'TORRENT'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'AndroidPhoneNotify'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaBrotherhood'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'GetTwentyFourOrg'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'Libgen'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'RealdebridComTorrent'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
45 | 10.08.2020 11:59:47 | INFO | ADDON UpdateManager: All plugins are up to date!
46 | 10.08.2020 11:59:49 | DEBUG | ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/hosts/status \| redirect=True \| cookies=True \| get={'auth_token': XXX’} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
47 | 10.08.2020 11:59:49 | DEBUG | ACCOUNT RealdebridCom: Hoster list for user `XXX*******`: [u'alfafile.net', u'anzfile.net', u'bayfiles.com', u'clicknupload.me', u'clipwatching.com', u'dailymotion.com', u'ddownload.com', u'depositfiles.com', u'dropapk.to', u'filefactory.com', u'filerio.com', u'fourshared.com', u'free.fr', u'gigapeta.com', u'google.com', u'hitfile.net', u'hulkshare.com', u'inclouddrive.com', u'isra.cloud', u'mediafire.com', u'mega.co.nz', u'mixdrop.co', u'nitroflare.com', u'oboom.com', u'onefichier.com', u'rapidgator.net', u'redtube.com', u'scribd.com', u'sendspace.com', u'sky.fm', u'solidfiles.com', u'soundcloud.com', u'turbobit.net', u'tusfiles.com', u'ulozto.net', u'unibytes.com', u'uploaded.to', u'uptobox.com', u'userscloud.com', u'usersdrive.com', u'vidlox.tv', u'vidoza.net', u'vimeo.com', u'wipfiles.net', u'wupfile.com', u'youporn.com', u'youtube.com', u'zippyshare.com']
48 | 10.08.2020 11:59:49 | ERROR | ACCOUNT RealdebridCom: Failed to load hoster list for user `XXX*******`, retry in 5 minutes
49 | ? | ? | Traceback (most recent call last):
50 | ? | ? | File "/opt/pyload/module/Scheduler.py", line 101, in run
51 | ? | ? | ret = self.call(*self.args, **self.kwargs)
52 | ? | ? | File "/opt/pyload/module/plugins/internal/misc.py", line 179, in _task
53 | ? | ? | self.task()
54 | ? | ? | File "/opt/pyload/module/plugins/internal/MultiAccount.py", line 86, in periodical_task
55 | ? | ? | self.reactivate(refresh=True)
56 | ? | ? | File "/opt/pyload/module/plugins/internal/MultiAccount.py", line 320, in reactivate
57 | ? | ? | self.log_error(_("Failed to load hoster list for user `%s`, retry in 5 minutes") % self.user)
58 | ? | ?
`

With debugging on. I obfuscated the API token as you can see. The credentials seem to be correct as the account is listed as valid and online and download of RG material works like a charm.

**Comment by masch242** [comment]
/home/martin/pyload/pyLoadCore.py --debug
04.10.2020 17:36:37 INFO      starte pyLoad 0.4.20
04.10.2020 17:36:37 INFO      Benutze Home-Verzeichnis: /home/martin/.pyload
04.10.2020 17:36:37 DEBUG     Remote activated: True
04.10.2020 17:36:37 DEBUG     created index of plugins
04.10.2020 17:36:37 INFO      Aktivierte Plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, LinkdecrypterComHook, MergeFiles, TORRENT, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
04.10.2020 17:36:37 INFO      Deaktivierte Plugins: AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
04.10.2020 17:36:37 INFO      Downloadzeit: True
04.10.2020 17:36:37 INFO      Starte ThriftBackend: 0.0.0.0:7227
04.10.2020 17:36:38 INFO      Starting builtin webserver: :::8000
04.10.2020 17:36:38 INFO      Free space: 332.87 GiB
04.10.2020 17:36:38 INFO      Activating Accounts...
04.10.2020 17:36:38 INFO      ACCOUNT RealdebridCom: Adding user `D72*******`...
04.10.2020 17:36:38 DEBUG     ACCOUNT RealdebridCom: Reached login timeout for user `D72*******`
04.10.2020 17:36:38 INFO      ACCOUNT RealdebridCom: Login user `D72*******`...
04.10.2020 17:36:38 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/oauth/v2/token | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={'client_secret': 'XXXXXXXXXXXXXXXXXXXXXXXXX', 'code': '**********', 'client_id': 'XXXXXXXXXXXXXXXXXXXXXXXX', 'grant_type': 'http://oauth.net/grant_type/device/1.0'} | ref=True | just_header=False
04.10.2020 17:36:38 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/user | redirect=True | cookies=True | get={'auth_token': u'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
04.10.2020 17:36:38 INFO      ACCOUNT RealdebridCom: Grabbing account info for user `D72*******`...
04.10.2020 17:36:38 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/user | redirect=True | cookies=True | get={'auth_token': u'XXXXXXXXXXXXXXXXXXXXXXXXXX'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
04.10.2020 17:36:38 DEBUG     ACCOUNT RealdebridCom: Account info for user `D72*******`: {'login': {'timestamp': 1601825798.24083, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account RealdebridCom>, 'trafficleft': -1, 'maxtraffic': None, 'api_token': u'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'validuntil': 1609442133.738552, 'login': 'D72*******', 'type': 'RealdebridCom', 'options': {'limitDL': ['0']}}}
04.10.2020 17:36:38 INFO      Activating Plugins...
04.10.2020 17:36:38 WARNING   ADDON TORRENT: torrents / magnets are not associated with any plugin
04.10.2020 17:36:38 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_start`
04.10.2020 17:36:38 DEBUG     ADDON ExtractArchive: Found HjSplit 0.02 | Found UnRar 5.30 | Found UnZip 2.7.12 | Found UnTar 2.7.12
04.10.2020 17:36:38 INFO      ADDON XFileSharing: Auto-discover new hosters
04.10.2020 17:36:38 DEBUG     ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|clicknupload\.org|cramit\.in|ddownload\.com|easybytez\.com|exashare\.com|file\.al|filejoker\.net|fileom\.com|filerio\.com|fistfast\.net|hugefiles\.net|junocloud\.me|katfile\.com|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|suprafiles\.me|tusfiles\.net|uploadrocket\.net|vidplay\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
04.10.2020 17:36:39 INFO      ADDON XFileSharing: Auto-discover new crypters
04.10.2020 17:36:39 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
04.10.2020 17:36:39 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/updates/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.20'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
04.10.2020 17:36:39 INFO      pyLoad is up and running
04.10.2020 17:36:39 INFO      ADDON UpdateManager: pyLoad is up to date!
04.10.2020 17:36:39 DEBUG     ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/updates/master/plugins.txt | redirect=True | cookies=True | get={'v': '0.4.20'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
04.10.2020 17:36:39 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'FreeWayMe'), (u'accounts', u'GetTwentyFourOrg'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'ShareonlineBiz'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'ShareonlineBiz'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'TORRENT'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'AndroidPhoneNotify'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaBrotherhood'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'GetTwentyFourOrg'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'Libgen'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'RealdebridComTorrent'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
04.10.2020 17:36:39 INFO      ADDON UpdateManager: All plugins are up to date!
04.10.2020 17:36:41 DEBUG     ACCOUNT RealdebridCom: LOAD URL https://api.real-debrid.com/rest/1.0/hosts/status | redirect=True | cookies=True | get={'auth_token': u'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
04.10.2020 17:36:41 DEBUG     ACCOUNT RealdebridCom: Hoster list for user `D72*******`: [u'alfafile.net', u'anzfile.net', u'bayfiles.com', u'clicknupload.me', u'clipwatching.com', u'dailymotion.com', u'ddownload.com', u'depositfiles.com', u'dropapk.to', u'filefactory.com', u'filerio.com', u'fourshared.com', u'free.fr', u'gigapeta.com', u'google.com', u'hitfile.net', u'hulkshare.com', u'inclouddrive.com', u'isra.cloud', u'mediafire.com', u'mega.co.nz', u'mixdrop.co', u'nitroflare.com', u'oboom.com', u'onefichier.com', u'rapidgator.net', u'redtube.com', u'scribd.com', u'sendspace.com', u'sky.fm', u'solidfiles.com', u'soundcloud.com', u'turbobit.net', u'tusfiles.com', u'ulozto.net', u'unibytes.com', u'uploaded.to', u'uptobox.com', u'userscloud.com', u'usersdrive.com', u'vidlox.tv', u'vidoza.net', u'vimeo.com', u'wipfiles.net', u'wupfile.com', u'youporn.com', u'youtube.com', u'zippyshare.com']
04.10.2020 17:36:41 ERROR     ACCOUNT RealdebridCom: Failed to load hoster list for user `D72*******`, retry in 5 minutes
Traceback (most recent call last):
  File "/home/martin/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/home/martin/pyload/module/plugins/internal/misc.py", line 179, in _task
    self.task()
  File "/home/martin/pyload/module/plugins/internal/MultiAccount.py", line 86, in periodical_task
    self.reactivate(refresh=True)
  File "/home/martin/pyload/module/plugins/internal/MultiAccount.py", line 320, in reactivate
    self.log_error(_("Failed to load hoster list for user `%s`, retry in 5 minutes") % self.user)

04.10.2020 17:36:45 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666

**Comment by GammaC0de** [comment]
Try refreshing your pyLoad installation using the instruction in #3283 and then retry.
