### ISSUE TITLE
Deepbrid 

### ISSUE THREAD

**Issue by jaylfc** [pyload/pyload#3698]
Hi,

I have made the switch to deepbrid after trying many others and was disappointed when I came to add it to pyload, any possibility you could add it?

Thanks in advance and keep up the awesome work!

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by jaylfc** [comment]
Sent it to you :)

**Comment by GammaC0de** [comment]
@jaylfc Email not received...

**Comment by jaylfc** [comment]
Sorry! Should be there now!

**Comment by GammaC0de** [comment]
Password not working..

**Comment by jaylfc** [comment]
Strange, it Kuantan's have saved, I've just reset it to the one I sent. Sorry!

**Comment by jaylfc** [comment]
Any luck?

**Comment by GammaC0de** [comment]
I'm sorry but this is a poorly designed multihoster:
- API is poorly designed, for example querying the list of supported domains returns the hoster name without its TLD..
- You cannot login via API, you have to do it via HTTP
- The login page is protected with CloudFlare DDoS protection wheren you have to fill a Captcha which is unsupported currently :(

**Comment by jaylfc** [comment]
No probs, thanks for trying!

**Comment by milahu** [comment]
seems to work with jdownloader: [DeepbridCom.java](https://sourceforge.net/p/jdownloader-svn-mirror-milahu/code/HEAD/tree/trunk/src/jd/plugins/hoster/DeepbridCom.java)

```java
            if (account.getType() == AccountType.PREMIUM) {
                /* Use API in premium mode */
                postPage(br, API_BASE + "?page=api&app=jdownloader&action=generateLink", "pass=&link=" + Encoding.urlEncode(link.getPluginPatternMatcher()));
            } else {
                /* Use website for free account downloads */
                postPage(br, API_BASE + "?page=api&action=generateLink", "pass=&link=" + Encoding.urlEncode(link.getPluginPatternMatcher()));
            }
            final Map<String, Object> resp = this.handleErrorsAPI(br, account, link);
            dllink = (String) resp.get("link");
```
