### ISSUE TITLE
DNS resolution through SOCKS5 proxy

### ISSUE THREAD

**Issue by andreasgerstmayr** [pyload/pyload#37]
Even if I enable a SOCKS 5 proxy, DNS resolution is done locally:
`pycurl error 6: Couldn't resolve host name`

I've looked into the source and found out that libcurl has a special PROXYTYPE to resolve hostnames through the proxy called SOCKS5_HOSTNAME.

Unfortunately pycurl hasn't defined this constant, but we can pass this constant (integer) directly to setopt:
`self.c.setopt(pycurl.PROXYTYPE, 7)`
in line https://github.com/pyload/pyload/blob/master/module/network/HTTPRequest.py#L111

I guess everyone wants to to DNS through proxy, so we can just replace this line - otherwise we can define a new proxy type in the interfaces.

**Comment by clst** [comment]
I just ran into this.
It's an easy fix. Just change module\network\HTTPRequest.py
```
127:                 self.c.setopt(pycurl.PROXYTYPE, pycurl.PROXYTYPE_SOCKS5)
```
to
```
127:                 self.c.setopt(pycurl.PROXYTYPE, pycurl.PROXYTYPE_SOCKS5_HOSTNAME)
```

**Comment by GammaC0de** [comment]
@clst  Wow, you get the most ancient issue bringer award 🌷
