### ISSUE TITLE
Error downloading Google Drive

### ISSUE THREAD

**Issue by Biozxx** [pyload/pyload#3705]
### Describe the problem

I am having a problem downloading any google drive links, I have premiurize premium and realdebrid premium and it fails also.

Other links I can download fine.

### Debug log

229 | 27.08.2020 02:45:22 | INFO | ADDON UpdateManager: pyLoad is up to date!
-- | -- | -- | --
230 | 27.08.2020 02:45:22 | INFO | ADDON UpdateManager: All plugins are up to date!
231 | 27.08.2020 05:45:23 | INFO | ADDON UpdateManager: pyLoad is up to date!
232 | 27.08.2020 05:45:23 | INFO | ADDON UpdateManager: All plugins are up to date!
233 | 27.08.2020 07:46:51 | INFO | ACCOUNT PremiumizeMe: Relogin user `374*******`...
234 | 27.08.2020 07:50:16 | INFO | Added package sd containing 1 links
235 | 27.08.2020 07:50:17 | INFO | Download starts: https://drive.google.com/uc?id=1uJLNriohOc2CW7ozqM5a9Lh0kU-s4n_C&export=download
236 | 27.08.2020 07:50:17 | WARNING | HOSTER GoogledriveCom[7]: Plugin may be unstable
237 | 27.08.2020 07:50:17 | INFO | HOSTER GoogledriveCom[7]: Grabbing link info...
238 | 27.08.2020 07:50:17 | INFO | HOSTER GoogledriveCom[7]: Link name: uc
239 | 27.08.2020 07:50:17 | INFO | HOSTER GoogledriveCom[7]: Link size: N/D
240 | 27.08.2020 07:50:17 | INFO | HOSTER GoogledriveCom[7]: Link status: starting
241 | 27.08.2020 07:50:17 | INFO | HOSTER GoogledriveCom[7]: Processing url: https://drive.google.com/uc?id=1uJLNriohOc2CW7ozqM5a9Lh0kU-s4n_C&export=download
242 | 27.08.2020 07:50:17 | WARNING | HOSTER GoogledriveCom[7]: Free download failed \| offline
243 | 27.08.2020 07:50:17 | WARNING | Download is offline: uc
244 | 27.08.2020 08:00:06 | INFO | Added package test containing 2 links
245 | 27.08.2020 08:00:06 | INFO | Download starts: https://drive.google.com/uc?id=1aLDg7iBK7fCjgTI-cke-y9CtNHVJO6v2&export=download
246 | 27.08.2020 08:00:06 | WARNING | HOSTER GoogledriveCom[8]: Plugin may be unstable
247 | 27.08.2020 08:00:06 | INFO | HOSTER GoogledriveCom[8]: Grabbing link info...
248 | 27.08.2020 08:00:06 | INFO | HOSTER GoogledriveCom[8]: Link name: uc
249 | 27.08.2020 08:00:06 | INFO | HOSTER GoogledriveCom[8]: Link size: N/D
250 | 27.08.2020 08:00:06 | INFO | HOSTER GoogledriveCom[8]: Link status: starting
251 | 27.08.2020 08:00:06 | INFO | HOSTER GoogledriveCom[8]: Processing url: https://drive.google.com/uc?id=1aLDg7iBK7fCjgTI-cke-y9CtNHVJO6v2&export=download
252 | 27.08.2020 08:00:06 | WARNING | HOSTER GoogledriveCom[8]: Free download failed \| offline
253 | 27.08.2020 08:00:06 | WARNING | Download is offline: uc
254 | 27.08.2020 08:00:08 | INFO | Download starts: https://drive.google.com/uc?id=1SULKOFAbg6kCvzwNdGvctdU0SaGpGS7l&export=download
255 | 27.08.2020 08:00:08 | WARNING | HOSTER GoogledriveCom[9]: Plugin may be unstable
256 | 27.08.2020 08:00:08 | INFO | HOSTER GoogledriveCom[9]: Grabbing link info...
257 | 27.08.2020 08:00:08 | INFO | HOSTER GoogledriveCom[9]: Link name: uc
258 | 27.08.2020 08:00:08 | INFO | HOSTER GoogledriveCom[9]: Link size: N/D
259 | 27.08.2020 08:00:08 | INFO | HOSTER GoogledriveCom[9]: Link status: starting
260 | 27.08.2020 08:00:08 | INFO | HOSTER GoogledriveCom[9]: Processing url: https://drive.google.com/uc?id=1SULKOFAbg6kCvzwNdGvctdU0SaGpGS7l&export=download
261 | 27.08.2020 08:00:08 | WARNING | HOSTER GoogledriveCom[9]: Free download failed \| offline
262 | 27.08.2020 08:00:08 | WARNING | Download is offline: uc

```

```

**Comment by iki789** [comment]
I am still having this issue https://drive.google.com/u/0/uc?export=download

**Comment by koroki** [comment]
Here other with the same problem.

**Comment by dinjojo** [comment]
Me too

**Comment by GammaC0de** [comment]
@dinjojo Please open a new issue and provide a sample URL.
