### ISSUE TITLE
User privileges using Web

### ISSUE THREAD

**Issue by Matssa56** [pyload/pyload#3719]
Hi, I'm using the latest docker image available on a Rpi4 with Kali on it.
I successfully installed and can access pyload and it works fine.
However is there a possibility to do some user management? I mean add users with less permissions on the app than the admin account (to avoid them checking the logs or even changing some core setttings)?

I managed to create a user using pyLoadCore.py -u but it has the same permissions as the admin.

Thanks a bunch!

**Comment by GammaC0de** [comment]
After you have created a new user using` pyLoadCore.py -u`, go to `http://<PYLOAD_IP>/admin/` and assign desired privileges to that user

**Comment by Matssa56** [comment]
Go,

Thanks for the fast reply. When going to that webpage, I can't eem to be able the change the privileges. Indeed I only have a list of the different privileges and I can't seem to remove any (there isn't any button or whatsoever). Maybe the theme doesn't work probably :S I'll take a screenshot later today

**Comment by Matssa56** [comment]
Hi again,

Please find below the users page, I can't seem to be able to change anything :S

![image](https://user-images.githubusercontent.com/16662808/92640503-abaa9980-f2dd-11ea-886d-9c07812f78da.png)

**Comment by Matssa56** [comment]
Nvm just saw that on my android phone the list where i could select the permissions. Thanks! :)
