### ISSUE TITLE
[Main] News not loading in pyplex Theme

### ISSUE THREAD

**Issue by OzzieIsaacs** [pyload/pyload#3727]
### Description
After starting pyLoad in the pyPlex theme (main branch), go to page info. On the top of the page the loading bar in the News section appears, but no news are loaded.

### Debug log
Nothing in the debug log

### Additional references
Tested on Linux Mint with latest commit from main branch

### Screenshots

![grafik](https://user-images.githubusercontent.com/6438895/93015572-dd13b580-f5ba-11ea-932d-2dbc98c32e61.png)

**Comment by GammaC0de** [comment]
👍
