### ISSUE TITLE
Create a paid Debrid service with PyLoad

### ISSUE THREAD

**Issue by themago** [pyload/pyload#3730]
### Question

Is it possible to use Pyload to create a paid debrid service like alldebrid, realdebrid, linksnappy, etc?

**Comment by GammaC0de** [comment]
Yes, 
alldebrid, realdebrid and linksnappy are all supported including Torrent support.

**Comment by themago** [comment]
hi, that's not what I meant, sorry if I wasn't clear, I didn't mean using
pyload to download from those websites, I meant created a debrid service
using pyload's functionality, so create a front end website that various
users can signup for and download from using pyload on your own server

**Comment by GammaC0de** [comment]
No,
pyload only supports downloading functionality.

You can add an existing account to pyLoad using the updateAccount() API function.
