### ISSUE TITLE
[Main] Migrate Modern theme to pyload NG?

### ISSUE THREAD

**Issue by OzzieIsaacs** [pyload/pyload#3743]
### Feature description
Currently the "modern theme" is missing for pyload NG, would it wake sense to port this theme also to pyload NG.
(I'm willing to do it, if it will get merged, but I won't do it and you decide afterwards that you don't want it)

### Problem description
Modern theme is missing

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/0c625f6ca6eda9c47669780c265b961f3defca36
