### ISSUE TITLE
File.Al support

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#3758]
### Description

FileAl (http://file.al) seems to be an `XFSHoster`-type hoster. I have a [plugin in my fork](https://github.com/igel-kun/pyload/blob/stable/module/plugins/hoster/FileAl.py) that used to work until recently, but they switched to RecaptchaV2 and the current interactive captcha implementation seems to have trouble with it (interactive window comes up in the web-interface, but the captcha doesn't load). Maybe you have a better shot at writing the plugin or figuring out what's up...

### Sample resources

sample link: https://file.al/hcfxima0o9mo/VA_-_Hit_Music_2016_Vol_2_MP3~320Kbps.part2.rar.html

disclaimer: I have nothing to do with this link, I just found it googling for file.al samples.

**Comment by GammaC0de** [comment]
Plugin still works, 
you have to install [Ignore X-Frame-Options](https://addons.mozilla.org/en-US/firefox/addon/ignore-x-frame-options-header) plugin to make captcha work.

**Comment by igel-kun** [comment]
awesome, thanks for the quick support. I'll drop a pull request for the plugin then :] *cheers*
