### ISSUE TITLE
how do I configure pyload for external access

### ISSUE THREAD

**Issue by Draalz** [pyload/pyload#3762]
### Question

how do I configure pyload for external access

### Additional references
Sorry for my bad english

My host for different servers works with debian bullseye. After a dist-upgrade apt removed python2.7 and pyload. So I search for a alternate installing methode. With pip it was then successful. pyload runs, but I have no access to the webinterface. Which settings do I have to make to be able to access pyload externally.

This is my pyload.cfg
`download - "Download":
        int chunks : "Max connections for one download" = 3
        time end_time : "End" = 0:00
        ip interface : "Download interface to bind (IP Address)" = 192.168.137.2
        bool ipv6 : "Allow IPv6" = False
        bool limit_speed : "Limit Download Speed" = False
        int max_downloads : "Max Parallel Downloads" = 3
        int max_speed : "Max Download Speed in KiB/s" = -1
        bool skip_existing : "Skip already existing files" = False
        time start_time : "Start" = 0:00

general - "General":
        debug;trace;stack debug_level : "Debug Level" = trace
        bool debug_mode : "Debug Mode" = True
        bool folder_per_package : "Create folder for each package" = True
        en; language : "Language" = en
        int min_free_space : "Min Free Space in MiB" = 1024
        folder storage_folder : "Download Folder" = /home/christian/Downloads/pyLoad

log - "Log":
        bool console : "Print log to console" = True
        bool console_color : "Colorize console" = False
        bool filelog : "Save log to file" = True
        int filelog_entries : "Max log files" = 10
        folder filelog_folder : "File folder" =
        bool filelog_rotate : "Log rotate" = True
        int filelog_size : "Max file size (in KiB)" = 100
        bool syslog : "Sent log to syslog" = False
        folder syslog_folder : "Syslog local folder" =
        ip syslog_host : "Syslog remote IP Address" = localhost
        local;remote syslog_location : "Syslog location" = local
        int syslog_port : "Syslog remote Port" = 514

permission - "Permissions":
        bool change_dl : "Change Group and User of Downloads" = False
        bool change_file : "Change file mode of downloads" = False
        bool change_group : "Change group of running process" = False
        bool change_user : "Change user of running process" = False
        str file : "Filemode for Downloads" = 0644
        str folder : "Folder Permission mode" = 0755
        str group : "Groupname" = users
        str user : "Username" = christian

proxy - "Proxy":
        bool enabled : "Activated" = False
        ip host : "IP Address" = 192.168.137.2
        password password : "Password" =
        int port : "Port" = 7070
        http;socks4;socks5 type : "Protocol" = http
        str username : "Username" = christian

reconnect - "Reconnection":
        bool enabled : "Activated" = False
        time end_time : "End" = 0:00
        str script : "Script" =
        time start_time : "Start" = 0:00

webui - "Web Interface":
        bool autologin : "Skip login if single user" = True
        bool develop : "Development mode" = True
        bool enabled : "Activated" = True
        ip host : "IP Address" = 192.168.137.2
        int port : "Port" = 8001
        str prefix : "Path Prefix" =
        file ssl_certchain : "CA's intermediate certificate bundle (optional)" =
        file ssl_certfile : "SSL Certificate" = ssl.crt
        file ssl_keyfile : "SSL Key" = ssl.key
        Default;PyPlex theme : "Theme" = PyPlex
        bool use_ssl : "Use HTTPS" = False`

**Comment by GammaC0de** [comment]
You have installed pyload v0.5 which is not ready for use yet.
Currently the stable version of pyload (v0.4.20) still uses python2.7.

See https://github.com/pyload/pyload/releases//0.4.20/

If you need hel with installation, please tell.
