### ISSUE TITLE
Plugin DebridlinkfrTorrent, decrypting failed when download torrent, any clue on what is wrong ?

### ISSUE THREAD

**Issue by yonix06** [pyload/pyload#3765]
Hello
### Description

I have a décrypter error when I'm using the debridlinkfr plugin to download torrent file

### Debug log

Debug mode enabled
```
02.10.2020 07:59:46	INFO	Decrypting starts: tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
627	02.10.2020 07:59:46	WARNING	CRYPTER DebridlinkFrTorrent[510]: Plugin may be unstable
628	02.10.2020 07:59:46	INFO	CRYPTER DebridlinkFrTorrent[510]: Grabbing link info...
629	02.10.2020 07:59:46	INFO	CRYPTER DebridlinkFrTorrent[510]: Link name: tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
630	02.10.2020 07:59:46	INFO	CRYPTER DebridlinkFrTorrent[510]: Link size: N/D
631	02.10.2020 07:59:46	INFO	CRYPTER DebridlinkFrTorrent[510]: Link status: starting
632	02.10.2020 07:59:46	INFO	CRYPTER DebridlinkFrTorrent[510]: Processing url: file://tmp/tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
633	02.10.2020 07:59:47	ERROR	Decrypting failed: tmp_The.100.S07E16.The.Last.War.1080p.10bit.
```

### Additional references

Just want to say thanks for the software again

**Comment by GammaC0de** [comment]
Please enable debug mode, retry and the post the logs.

**Comment by yonix06** [comment]
Sorry, i thought it was on, i have clicked on the save button 100 times in a row this time.

> 

02.10.2020 16:53:01 | ERROR | Decrypting failed: tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent \| 'torrentId'
-- | -- | --
689 | 02.10.2020 16:53:01 | INFO | CRYPTER DebridlinkFrTorrent[510]: Processing url: file://tmp/tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
688 | 02.10.2020 16:53:01 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link status: starting
687 | 02.10.2020 16:53:01 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link size: N/D
686 | 02.10.2020 16:53:01 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link name: tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
685 | 02.10.2020 16:53:01 | INFO | CRYPTER DebridlinkFrTorrent[510]: Grabbing link info...
684 | 02.10.2020 16:53:01 | WARNING | CRYPTER DebridlinkFrTorrent[510]: Plugin may be unstable
683 | 02.10.2020 16:53:01 | INFO | Decrypting starts: tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
682 | 02.10.2020 16:52:59 | ERROR | Decrypting failed: tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent \| 'torrentId'
681 | 02.10.2020 16:52:57 | INFO | CRYPTER DebridlinkFrTorrent[510]: Processing url: file://tmp/tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
680 | 02.10.2020 16:52:57 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link status: starting
679 | 02.10.2020 16:52:57 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link size: N/D
678 | 02.10.2020 16:52:57 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link name: tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
677 | 02.10.2020 16:52:57 | INFO | CRYPTER DebridlinkFrTorrent[510]: Grabbing link info...
676 | 02.10.2020 16:52:57 | WARNING | CRYPTER DebridlinkFrTorrent[510]: Plugin may be unstable
675 | 02.10.2020 16:52:57 | INFO | Decrypting starts: file://tmp/tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
674 | 02.10.2020 16:52:57 | ERROR | Decrypting failed: file://tmp/tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent \| No JSON object could be decoded: line 1 column 0 (char 0)
673 | ? | ? | Abort
672 | ? | ? | raise Abort()
671 | ? | ? | File "/app/pyload/module/network/HTTPRequest.py", line 340, in write
670 | ? | ? | Traceback (most recent call last):
669 | 02.10.2020 16:52:57 | ERROR | <<< UNCAUGHT EXCEPTION >>>
668 | 02.10.2020 16:52:53 | INFO | CRYPTER DebridlinkFrTorrent[510]: Processing url: file://tmp/tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
667 | 02.10.2020 16:52:53 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link status: starting
666 | 02.10.2020 16:52:53 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link size: N/D
665 | 02.10.2020 16:52:53 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link name: tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
664 | 02.10.2020 16:52:53 | INFO | CRYPTER DebridlinkFrTorrent[510]: Grabbing link info...
663 | 02.10.2020 16:52:53 | WARNING | CRYPTER DebridlinkFrTorrent[510]: Plugin may be unstable
662 | 02.10.2020 16:52:53 | INFO | Decrypting starts: tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
661 | 02.10.2020 16:52:18 | ERROR | Decrypting failed: tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent \| 'torrentId'
660 | 02.10.2020 16:52:17 | INFO | CRYPTER DebridlinkFrTorrent[510]: Processing url: file://tmp/tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent
659 | 02.10.2020 16:52:17 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link status: starting
658 | 02.10.2020 16:52:17 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link size: N/D
657 | 02.10.2020 16:52:17 | INFO | CRYPTER DebridlinkFrTorrent[510]: Link name: tmp_The.100.S07E16.The.Last.War.1080p.10bit.WEBRip.6CH.x265.HEVC.mkv.torrent

**Comment by GammaC0de** [comment]
Please send the torrent URL to nitzo2001 at yahoo dot com.

**Comment by lTimeLordl** [comment]
@GammaC0de `torrentId` field was never documented on the API and was only used as backward compatibility with api V1.

Replacing the `torrentId` by `id` should fix this issue. https://github.com/pyload/pyload/blob/stable/module/plugins/crypter/DebridlinkFrTorrent.py#L124

**Comment by GammaC0de** [comment]
Fixed. 

@lTimeLordl Thanks for pinpointing this 👍

**Comment by yonix06** [comment]
Thanks again for the reactivity !! 
Regards,
Yo'
