### ISSUE TITLE
9kw captcha service - nothing happens

### ISSUE THREAD

**Issue by razzia23** [pyload/pyload#3766]
Hello,
I´ve installed the .deb file (version 0.4.2) on debian buster, entered the 9kw captcha api key, but there is no change - have to confirm manually. Also wondering why there are two services available. 

Captcha9Kw and Captcha_9kw

```
`04.10.2020 12:25:28 WARNING   CAPTCHA DdlTo[5]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
04.10.2020 12:25:28 DEBUG     CAPTCHA DdlTo[5]: ReCaptcha | Challenge reCAPTCHA v2 interactive`
```

**Comment by GammaC0de** [comment]
First of all, there should be only one plugin (`Captcha9Kw`)
2. Try refreshing your pyLoad installation using the instruction in #3283 and then retry.
3. Have you enabled the plugin?

**Comment by razzia23** [comment]
Plugin loaded and enabled:
`04.10.2020 21:53:13 DEBUG     Plugin loaded: Captcha9Kw`

04.10.2020 21:54:16 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
04.10.2020 21:54:16 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
04.10.2020 21:54:16 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
04.10.2020 21:54:16 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
04.10.2020 21:54:16 DEBUG     HOSTER DdlTo[1]: Plugin version: 0.07
04.10.2020 21:54:16 DEBUG     HOSTER DdlTo[1]: Plugin status: testing
04.10.2020 21:54:16 WARNING   HOSTER DdlTo[1]: Plugin may be unstable
04.10.2020 21:54:16 INFO      HOSTER DdlTo[1]: Grabbing link info...
04.10.2020 21:54:17 DEBUG     HOSTER DdlTo[1]: Link info: {'status': 2, 'hash': {}, 'name': u'MS', 'url': u'https://xxxx', 'pattern': {'S': u'100.00', 'U': u'MB', 'ID': xxxxk', 'N': u'xxx1.rar'}, 'size': 10434353}
04.10.2020 21:54:17 DEBUG     HOSTER DdlTo[1]: Previous link info: {}
04.10.2020 21:58:25 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
04.10.2020 21:58:25 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
04.10.2020 21:58:25 INFO      Download aborted: MS
04.10.2020 21:58:25 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
04.10.2020 21:58:25 DEBUG     All downloads processed
04.10.2020 21:58:25 WARNING   ADDON TORRENT: torrents / magnets are not associated with any plugin
04.10.2020 21:58:25 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_stop`
04.10.2020 21:58:25 INFO      ADDON ClickNLoad: Shutting down proxy...
04.10.2020 21:58:25 DEBUG     ADDON ClickNLoad: Server exited successfully
04.10.2020 21:58:25 DEBUG     Deleting old pidfile pyload.pid
04.10.2020 21:58:25 INFO      killed pyLoad from Terminal

**Comment by GammaC0de** [comment]
Also verify that `Don't use if client is connected` settings is disabled

**Comment by razzia23** [comment]
perfect! Thank you very much - you saved my day :)) that was the solution!
