### ISSUE TITLE
Some captchas are not loading in Vivaldi (based on Chromium)

### ISSUE THREAD

**Issue by coldspark29** [pyload/pyload#3773]
### Description

When a new captcha is ready a green bar is shown saying it is ready, but when I click on new captchas ready, they are not loading. I installed Tampermoneky and the pyload module.

### Debug log

The log gives me this and then nothing happens
```
127 | 16.10.2020 19:54:24 | WARNING | CAPTCHA UploadedTo[1]: ReCaptcha \| reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
126 | 16.10.2020 19:54:24 | WARNING | CAPTCHA UploadedTo[1]: ReCaptcha \| Secure Token pattern not found
125 | 16.10.2020 19:54:24 | WARNING | CAPTCHA UploadedTo[1]: ReCaptcha \| Secure Token pattern not found
```

**Comment by coldspark29** [comment]
Just found out that it works on Firefox. Haven't tried Chromium. Maybe this is a Tampermonkey Chromium issue?

**Comment by GammaC0de** [comment]
Some hosters also require [ignore-x-frame-options-header](https://addons.mozilla.org/en-US/firefox/addon/ignore-x-frame-options-header/) plugin.

Can't help you with Vivaldi, sorry.
