### ISSUE TITLE
Captchas are not visible in iOS Client

### ISSUE THREAD

**Issue by coldspark29** [pyload/pyload#3776]
### Description

I get a notification inside the app (the red C), but then no captcha is shown. I already had a captcha with text and one where you have to choose the cars or chimneys etc. They work in the browser, but not iOS.

**Comment by coldspark29** [comment]
Guess the iOS Client isn't developed by you guys?

**Comment by GammaC0de** [comment]
iOS app is not official and is not supported here.
Ask for support from the app developer.

**Comment by coldspark29** [comment]
Unfortunately all his support links lead to nowhere after 10 redirections. What a rip off xD
