### ISSUE TITLE
pyload-ng support

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#3826]
Because Entware removed python2 support i ran into issues after updating packages. So i decided to move towards pyload-ng. But now i have no idea how to get further and hope anyone (@vuolter) could help me out with those issues.
It seems to me there are problems detecting Cryptodome but it's installed.

> 

> 
[my pyload.log](https://github.com/pyload/pyload/files/5471410/pyload.log)

[installed python modules](https://github.com/pyload/pyload/files/5471412/modules.txt)

**Comment by GammaC0de** [comment]
First of all, your pyCryptodome installation seems to be corrupt.

Not all of the plugins were migrated to pyload-ng yet.
Those that use the pycrypto library are planned to move to the cryptography library, pyCryptodome is not a requirement

**Comment by xprofiler** [comment]
To solve this I had to install pycryptodomex (see [https://pycryptodome.readthedocs.io/en/latest/src/installation.html](https://pycryptodome.readthedocs.io/en/latest/src/installation.html))
`pip3 install pycryptodomex`

**Comment by UserX404** [comment]
@xprofiler 
Finally found some time and motivation to set up Pyload-ng again and ran into some other issues before i come back again into this one.
Thanks for your solution. Pyload-ng is finally starting without exceptions.
