### ISSUE TITLE
How do I delete ALL collector Items at once? 

### ISSUE THREAD

**Issue by Bava1980** [pyload/pyload#3830]
### Question

How do I delete ALL collector Items at once? 

### Additional references
I dont know how but a filefactory CNL was copied about 1000 times (using Firefox Private Window). Now I dont want to delete every single item. Probably there is a file where all informations are stored and just needs to be deleted? 

Using Pyplex
Python:
    2.6.2 (r262:71600, Nov 24 2014, 22:01:21) [GCC 4.3.2]
Betriebssystem:
    posix linux2 Linux MileniumFalcon 2.6.31.8 #2 Wed Jun 21 16:44:13 CST 2017 armv5tel
pyLoad Version:
    0.4.20

**Comment by GammaC0de** [comment]
* Go to `http://<pyload_ip>/info` and write down the value of `Config Folder`
* Stop pyLoad
* Go to `Config Folder` directory and delete files.db
* Start pyLoad
