### ISSUE TITLE
Pyload configuration rendered differently among multiple restarts

### ISSUE THREAD

**Issue by djessich** [pyload/pyload#3841]
### Description

Pyload 0.4.20 renders the following part of configuration during first start:
```
classic;pyplex;modern template : "Template" = modern
```

After multiple restarts, Pyload 0.4.20 rerenders the above line to the following:

```
classic;modern;pyplex template : "Template" = modern
```

I think the line will be rerendered only, after some Plugins have been updated to a specific version. The Plugin causing this behavior or the concrete version of it is currently not known.

### Debug log

I tried to find some useful information in debug log, why this behaviour changed. However, there is no hint in the logs, referencing this issue.

### Additional references

None.

### Additional Information

Maybe it would be a good idea, to avoid rendering the config over and over again during Pyload start. Is there any requirement of a specific order in config file? Can this behavior somehow skipped?

**Comment by GammaC0de** [comment]
Why is this so important to you?

**Comment by djessich** [comment]
@GammaC0de This issue is preventing me from rendering the Pyload configuration by using an automated and template-based approach. As I have totally reimplemented the [Pyload Chef cookbook](https://github.com/djessich/cookbook-pyload) in the past weeks (I am the author), which automates the installation and configuration of Pyload, I was able to find this bug during testing. It seems to me, that after Pyload was successfully installed, configured and updated (by the update manager), the config file content is not rendered the same as with a fresh installation of 0.4.20.

**Comment by GammaC0de** [comment]
This is probably because of this: https://github.com/pyload/pyload/blob/stable/module/web/webinterface.py#L68

It tries to dynamically create a list of existing templates...

**Comment by djessich** [comment]
Is there any progress on this with latest Pyload version?

**Comment by GammaC0de** [comment]
@djessich Cant you make chef recognize multiple cases (something like a script maybe)?
The intention is that pyload would recognize the WebUI templates installed and fill this config settings dynamically...
