### ISSUE TITLE
UploadedTo interactive captcha problem

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#3844]
### Description

I'm not seeing captchas for UploadedTo (should be interactive captchas).
I do see (interactive) captchas for all other hosters I've tested.
I'm using the webUI interface, connecting with firefox (newest version, windows and linux tested, have Tampermonkey+pyload script and the Ignore-X-Frame-Option addon).
In the log, it appears that the captcha key for the site is detected correctly.

I am wondering whether his "secure token" might have anything to do with it, but I really have no clue about the whole interactive-captcha process, so I'm just guessing wildly here...

### Debug log

```
3063 | 15.11.2020 14:12:22 | DEBUG | CAPTCHA UploadedTo[53545]: ReCaptcha \| Key: 6Le1WUIUAAAAAG0gEh0atRevv3TT-WP4HW8FLMoe
-- | -- | -- | --
3064 | 15.11.2020 14:12:22 | WARNING | CAPTCHA UploadedTo[53545]: ReCaptcha \| Secure Token pattern not found
3065 | 15.11.2020 14:12:22 | DEBUG | CAPTCHA UploadedTo[53545]: ReCaptcha \| Detected reCAPTCHA v2
3066 | 15.11.2020 14:12:22 | WARNING | CAPTCHA UploadedTo[53545]: ReCaptcha \| Secure Token pattern not found
```

**Comment by GammaC0de** [comment]
For me it is working fine even with x-frame-options plugin disabled.

Try to see if there is some useful error message in Firefox's web console (Ctrl-Shift-k)

**Comment by igel-kun** [comment]
good call, I'm seeing an error there:
```Blocked loading mixed active content “http://uploaded.net/[...]”```
It might have to do with the fact that firefox doesn't like the SSL certificate provided on the webUI (although I did explicitly told it not to worry about certificate errors of the site...). I'll investigate a bit more.

**Comment by igel-kun** [comment]
Okay, so this is a duplicate of #3305 which has been closed, so I guess, this should be closed as well, unless you disagree and want to take a second look at the problem...
