### ISSUE TITLE
Premiumize.me account is not recognized properly

### ISSUE THREAD

**Issue by dima0git** [pyload/pyload#3845]
### Description

The premiumize.me plugin is setup correctly, active and loaded in pyLoad (see line 2 - 4 of attached log).
But it is not used when downloading from this service. The BasePlugin is used instead and fails downloading.

Used pyLoad version: 0.4.20
OS: posix linux2 Linux ubuntu 5.4.0-54-generic
Python: 2.7.18

### Debug log

1	25.11.2020 22:36:48	INFO	Activating Accounts...
2	25.11.2020 22:36:48	INFO	ACCOUNT PremiumizeMe: Adding user `**********`...
3	25.11.2020 22:36:48	INFO	ACCOUNT PremiumizeMe: Login user `**********`...
4	25.11.2020 22:36:50	INFO	ACCOUNT PremiumizeMe: Grabbing account info for user `**********`...
5	25.11.2020 22:36:51	INFO	Activating Plugins...
6	25.11.2020 22:36:51	INFO	pyLoad is up and running
7	25.11.2020 22:36:52	INFO	ADDON UpdateManager: pyLoad is up to date!
8	25.11.2020 22:36:53	INFO	ADDON UpdateManager: All plugins are up to date!
9	25.11.2020 22:36:57	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
10	25.11.2020 22:37:50	INFO	Added package test containing 1 links
11	25.11.2020 22:37:51	INFO	Download starts: https://www.premiumize.me/file?id=abcdefghijklmnopqrst
12	25.11.2020 22:37:51	WARNING	HOSTER BasePlugin[238]: Plugin may be unstable
13	25.11.2020 22:37:51	INFO	HOSTER BasePlugin[238]: Grabbing link info...
14	25.11.2020 22:37:51	INFO	HOSTER BasePlugin[238]: Link name: file
15	25.11.2020 22:37:51	INFO	HOSTER BasePlugin[238]: Link size: N/D
16	25.11.2020 22:37:51	INFO	HOSTER BasePlugin[238]: Link status: starte
17	25.11.2020 22:37:51	INFO	HOSTER BasePlugin[238]: Processing url: https://www.premiumize.me/file?id=abcdefghijklmnopqrst
18	25.11.2020 22:37:52	WARNING	Download failed: file | Bad server response: 500 Internal Server Error
19	25.11.2020 22:37:52	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: file (pid:32)
20	25.11.2020 22:37:52	INFO	ADDON UnSkipOnFail: No duplicates found 

```
Remark: Link is masked.
```

**Comment by GammaC0de** [comment]
Are you sure the url is supported by Premiumize.me?
I cannot tell since you did not posted it..

**Comment by dima0git** [comment]
The URL in the log does not work.
Here is a real URL with a dummy 100MB dummy file:
https://www.premiumize.me/file?id=x22DZBbSIiPX9PI8czrUhA

But to use it, you need to be logged in.
I can provide you the credentials, which are required for the plug-in in pyLoad.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Well?!

**Comment by dima0git** [comment]
Will provide you in a couple of days. Maybe already tomorrow...

**Comment by dima0git** [comment]
Could you confirm, that you received the account data.

Please tell us, if there is a progress.

Thanks a lot!

**Comment by GammaC0de** [comment]
Yes, account received 👍

**Comment by GammaC0de** [comment]
Can you provide another URL?
I get "File not found" error..

**Comment by dima0git** [comment]
There is a file in "MyFiles". I generated it with the command `truncate -s 100M dummy.txt`.
You can upload any other files for testing.

You can copy a direct URL to a file which starts with `https://www.premiumize.me/...`
Or you can generate a cloud download URL, but this link is depending on the IP address, from which the link was created.


![screenshot](https://user-images.githubusercontent.com/75067403/100932630-72ed1b80-34ec-11eb-9e38-8734207e2eed.png)


pyLoad is not working with the direct links, while jDownloader interprets the URL correctly and derives the corresponding files from the URL.

**Comment by dima0git** [comment]
Great!
It seems to work :) Thanks.

Does pyLoad update the plug-ins automatically?
I wanted to copy the new PremiumizeMe.py (v 0.34) to my pyLoad installation, but it is already there after a restart of pyLoad.

I guess you don't need the testing account any more, right?

**Comment by GammaC0de** [comment]
> Does pyLoad update the plug-ins automatically?

Yes

> I guess you don't need the testing account any more, right?

Correct.
