### ISSUE TITLE
failed Player config pattern not found 0.00 B YoutubeCom    

### ISSUE THREAD

**Issue by dg9999cn** [pyload/pyload#3847]
### Description

https://www.youtube.com/watch?v=uxLaBHZFtbU
failed Player config pattern not found 0.00 B YoutubeCom    
95% of the downloads don't work today.

### Debug log
145 | 28.11.2020 03:18:58 | INFO | HOSTER YoutubeCom[4]: Processing url: https://www.youtube.com/watch?v=uxLaBHZFtbU
-- | -- | -- | --
146 | 28.11.2020 03:18:59 | WARNING | HOSTER YoutubeCom[4]: Free download failed \| Player config pattern not found
147 | 28.11.2020 03:18:59 | WARNING | Download failed: watch \| Player config pattern not found
148 | 28.11.2020 03:18:59 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: watch (pid:4)
149 | 28.11.2020 03:18:59 | INFO | ADDON UnSkipOnFail: No duplicates found

System:
Python:2.7.18 (default, May 3 2020, 20:31:45) [GCC 9.2.0]OS:posix linux2 Linux f8eac205609f 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64pyLoad version:0.4.20Installation Folder:/app/pyloadConfig Folder:/configDownload Folder:/downloadsFree Space:4.17 TiBLanguage:enWebinterface Theme:modern by GammaC0de based on work of Marco Fernandes and Dogan Bagci

**Comment by GammaC0de** [comment]
It works fine for me..

**Comment by CanadianEngineer** [comment]
I'm getting the same error message here as well. However, I spun it up in a docker container: https://hub.docker.com/r/linuxserver/pyload

**Comment by Nebucatnetzer** [comment]
I'm seeing this as well with the Docker container.

**Comment by GammaC0de** [comment]
Please provide sample html file for a failed URL so I can test

**Comment by Nebucatnetzer** [comment]
This one failed for me:
https://www.youtube.com/watch?v=yLbG_TkmMb4

**Comment by boblegal31** [comment]
Thanks
