### ISSUE TITLE
Install pyLoad ipkg without prompting visual configuration

### ISSUE THREAD

**Issue by AlphaC0de** [pyload/pyload#3857]
### Question

How can I bypass visual configuration of pyLoad while installing from _ipkg_?
I use an automate script to create necessary files like _pyLoad.conf, files.db, plugins.conf and accounts.conf._
But using this
```
/opt/bin/wget https://github.com/pyload/pyload/releases/download/0.4.20/pyload_0.4.20_noarch.ipk -O ./pyload_0.4.20_noarch.ipk
ipkg install --nodeps ./pyload_0.4.20_noarch.ipk
```
it displays me the configuration prompt; what command to bypass and do a silent installation without interruptions?

**Comment by GammaC0de** [comment]
This is not possible with the current release, try this one: [pyload_0.4.20_noarch.zip](https://github.com/pyload/pyload/files/5685386/pyload_0.4.20_noarch.zip)

**Comment by AlphaC0de** [comment]
Can this standalone versione be updated normally like the default one? I mean, no differences in future support (plugins, etc.)

**Comment by GammaC0de** [comment]
Can you confirm it works?

> Can this standalone versione be updated normally like the default one?

I don't understand your question

**Comment by AlphaC0de** [comment]
> Can you confirm it works?
> 
It says this

```
opt/etc/init.d/pyload stop
mv /opt/etc/pyload /opt/etc/pyloadBAKOLD
ipkg remove pyload
/opt/bin/wget https://github.com/pyload/pyload/files/5685386/pyload_0.4.20_noarch.zip -O /root/pyload_0.4.20_noarch.zip
unzip /root/pyload_0.4.20_noarch.zip -d /root
rm -f /root/pyload_0.4.20_noarch.zip
ipkg install --nodeps /root/pyload_0.4.20_noarch.ipk
Collected errors:
 * deb_extract: /root/pyload_0.4.20_noarch.ipk: invalid magic
 * pkg_init_from_file: Failed to extract control file from /root/pyload_0.4.20_noarch.ipk.
```
> > Can this standalone versione be updated normally like the default one?
> 
> I don't understand your question

I don't know I understood correctly, but isn't this ipk a modded one so that I can bypass configuration? The question is, this modded version will be able to receive future updates normally?

**Comment by GammaC0de** [comment]
OK, here is a working version: [pyload_0.4.20_noarch.zip](https://github.com/pyload/pyload/files/5685581/pyload_0.4.20_noarch.zip)

> The question is, this modded version will be able to receive future updates normally?

This exactly the same package with the configuration script excluded.

**Comment by AlphaC0de** [comment]
OK, tried this:
```
/opt/bin/wget https://github.com/pyload/pyload/files/5685581/pyload_0.4.20_noarch.zip -O /root/pyload_0.4.20_noarch.zip
unzip /root/pyload_0.4.20_noarch.zip -d /root
rm -f /root/pyload_0.4.20_noarch.zip
ipkg install --nodeps /root/pyload_0.4.20_noarch.ipk
Installing pyload (0.4.20) on /opt/.
Configuring pyload.
rm -f ./pyload_0.4.20_noarch.ipk
ln -s /opt/share/pyload/pyLoadCore.py /opt/bin/pyLoadCore
sleep 10
/opt/etc/init.d/pyload stop
mv /opt/etc/pyload /opt/etc/pyloadBAKNEW
mv /opt/etc/pyloadBAKOLD /opt/etc/pyload
```
The issue is that pyLoad seems to work (log says this) but it not uses accounts.conf (for my logins) and the download history (Library)

**Comment by GammaC0de** [comment]
please verify that you are putting those file in the correct folder:

```
14.12.2020 22:59:40 INFO      Starting pyLoad 0.4.20
14.12.2020 22:59:40 INFO      Using home directory: /opt/pyload/somedirectory/etc
```

**Comment by AlphaC0de** [comment]
Tried to reinstall all: the issue was that _pyLoad_ necessary needed a full second reboot, don't know why; only datas missing are download history.
What are the exact files I need to restore that (and, is there a program that can open and mount a _roots.img_ file without using a VM withy Linux distro)?

**Comment by GammaC0de** [comment]
Download history is stored in `files.db` located at pyload's home directory.

**Comment by AlphaC0de** [comment]
Now it works perfectly; all issues solved, thank you
