### ISSUE TITLE
PyLoad start failed on RPI3b

### ISSUE THREAD

**Issue by Matszwe02** [pyload/pyload#3859]
Hi. I can't start pylaod service on my RPI with raspbian operating system. When I install it, it works for some time, then it breaks and nothing helps (reconfiguring, reinstalling), I have to reinstall the entire raspbian.
### Debug log

Here's the log:
```

pi@raspberrypi:~ $ sudo service pyload restart
Job for pyload.service failed because the control process exited with error code.
See "systemctl status pyload.service" and "journalctl -xe" for details.


pi@raspberrypi:~ $ journalctl -xe
Dec 13 15:29:18 raspberrypi pyload[1335]: Starting pyload download manager daemon: pyload f
Dec 13 15:29:18 raspberrypi systemd[1]: pyload.service: Control process exited, code=exited
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit pyload.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Dec 13 15:29:18 raspberrypi systemd[1]: pyload.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit pyload.service has entered the 'failed' state with result 'exit-code'.
Dec 13 15:29:18 raspberrypi systemd[1]: Failed to start LSB: Starts pyload daemon.
-- Subject: A start job for unit pyload.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit pyload.service has finished with a failure.
--
-- The job identifier is 933 and the job result is failed.

```

**Comment by GammaC0de** [comment]
Start pyload as a normal process with the command `pyLoadCore -d` and see if it works this way.

**Comment by kushwavez** [comment]
Same thing happened for me too on RPi4. 

I really overcomlicated the whole thing, wasted hours... It was really simple. Permissions. I learned now that the frickin permissions is a problem all the time on Linux.

Make sure that your config file is inside a folder that pyLoad can use without root priviliges.

After that, run the setup again and change the config dir. (first with sudo, second with normal priv)
`/usr/bin/pyLoadCore -s`

I also unfortunately wasted hours figuring out how can I install pyLoad, all the guides are outdated, pip/pip3 method doesn't work at all. Then I just installed the .deb with `dpkg -i` and it worked after `sudo apt --fix-broken install`... omg... well, good afternoon

**Comment by Matszwe02** [comment]
> Same thing happened for me too on RPi4. 
> 
> I really overcomplicated the whole thing, wasted hours... It was really simple. Permissions. I learned now that the frickin permissions is a problem all the time on Linux.
> 
> Make sure that your config file is inside a folder that pyLoad can use without root priviliges.
> 
> After that, run the setup again and change the config dir. (first with sudo, second with normal priv)
> `/usr/bin/pyLoadCore -s`
> 
> I also unfortunately wasted hours figuring out how can I install pyLoad, all the guides are outdated, pip/pip3 method doesn't work at all. Then I just installed the .deb with `dpkg -i` and it worked after `sudo apt --fix-broken install`... omg... well, good afternoon

Thanks for your help! When I'll have some time, I'll try it and check if it was it causing the issue.

**Comment by kushwavez** [comment]
oh also forgot to mention that I'm using pyLoad 0.4.20, not pyLoad-ng because that doesn't work at all.
