### ISSUE TITLE
problems entering webinterface after a while

### ISSUE THREAD

**Issue by koenigmidas** [pyload/pyload#3863]
hi gamma!

me again, sorry to bother you.

i have installed the deb file you mentioned and my dl's are running and working!

but after a while, i cant enter my webinterface anymore but i can see by "htop" that pyload is running.
I need to reboot and then i can enter again.

i installed it like you have mentioned and the path is now:
/usr/share/pyload

to have it started after reboot i did the following:

- sudo crontab -e
- and added this: @reboot pyLoadCore --daemon

What did i wrong :( ?

Thanks in advance
greetings

**Comment by GammaC0de** [comment]
Please make sure the user that runs pyload have write permission to /usr/share/pyload.

Also, please enable debug mode in pyload so we can look at to log to see if there is an issue.
