### ISSUE TITLE
how install new version on zyxel 310s ?

### ISSUE THREAD

**Issue by alby1979** [pyload/pyload#3868]
hello
where i find a file for zyxel 310s?

thank you

**Comment by GammaC0de** [comment]
which new version do you mean? 0.4.20 or 0.5(which is beta)?

**Comment by alby1979** [comment]
I had a problem with 0.4.9.

it was enough to uninstall and reinstall it and now it works

I keep 0.4.9

thanks

**Comment by GammaC0de** [comment]
> I keep 0.4.9
thanks

0.4.9 is obsolete but suit yourself.
