### ISSUE TITLE
ExtractArchive - Don't extract the following folder?

### ISSUE THREAD

**Issue by uysct** [pyload/pyload#3872]
This setting **Don't extract the following files: *.jpg,*.nfo,*.url,*.DS_Store,index.dat,thumb.db**  does not extract the specified files after a successful download.
Is it possible that certain folders contained in the archive (for example a folder "Sample") are not unzipped?

How can I define that a complete folder with its content isn't touched while extraction? In my specific example I want to exclude the folder sample with all its content. Thanks

**Comment by rootsradics** [comment]
I'm not sure, but I think there's a minor issue with extractors plugin. To fix this one, I had to install 7zip, and add the '*.zip' extension to be handled by 7zip. This way, that works!
The other solution is to add a few lines to the UnZip plugin (extractall part, members have to be passed to the functionà, because AFAIK this one does not handle exclusion (files or directories). 
If I have time, I will try to fix and propose this fix to the pyload team.

**Comment by GammaC0de** [comment]
I can confirm that 7zip plugin should work by assing the folder name to the exclusion list (`Sample` in your example).

**Comment by uysct** [comment]
> The other solution is to add a few lines to the UnZip plugin (extractall part, members have to be passed to the function, because AFAIK this one does not handle exclusion (files or directories).
> If I have time, I will try to fix and propose it to the pyload team.

This is a really great idea! Personally, I like the second solution better, because the included "ExtractArchive" plugin works great for me. Unfortunately, the desired function is missing. The developers will have to decide which of the two suggestions is correct. If you can write code that works, it would be fantastic! Many Thanks

**Comment by uysct** [comment]
> I can confirm that 7zip plugin should work by assing the folder name to the exclusion list (`Sample` in your example).

As a developer, you will surely find the most sensible solution, I hope your time will allow it! Many Thanks

**Comment by GammaC0de** [comment]
> As a developer, you will surely find the most sensible solution, I hope your time will allow it! Many Thanks

It should work fine without any updates if you use 7zip with pyload instead of unrar/unzip.

**Comment by uysct** [comment]
Thank you for your feedback. Unfortunately, I am unable to do this because I simply don't know how to do it. I use pyload in a Docker (writl / pyload) in which this function (unrar / unzip) is already integrated. Is there an easy way to install 7zip?

**Comment by GammaC0de** [comment]
Please enable debug mode and then restart pyload.
You should see a line says something like:
```
 DEBUG     ADDON ExtractArchive: Found HjSplit 0.02 | Found UnRar 5.61 | Found SevenZip 18.05 | Found UnZip 2.7.18 | Found UnTar 2.7.18
```

If you do not see SevenZip, then it is not used.

What you have to do is either:
- build the docker file yourself, replacing unrar with p7zip https://github.com/obi12341/docker-pyload/blob/master/Dockerfile#L21
- ask the author to do that by crating an issue in https://github.com/obi12341/docker-pyload/issues

**Comment by uysct** [comment]
Ok, thanks for your help!

**Comment by GammaC0de** [comment]
:+1:

**Comment by uysct** [comment]
> > I can confirm that 7zip plugin should work by assing the folder name to the exclusion list (`Sample` in your example).

The Docker developer has now successfully integrated 7zip. And files in the list are still reliably not extracted. What exactly do I have to add to the list so that the example folder "Sample" is not extracted?

*.jpg,*.nfo,*.url,*.txt,*.DS_Store,index.dat,thumb.db,**\Sample\** ?

**Comment by GammaC0de** [comment]
Should be just "Sample":
.jpg,.nfo,.url,.txt,*.DS_Store,index.dat,thumb.db,Sample

**Comment by uysct** [comment]
Thanks alot! It works great!
