### ISSUE TITLE
[Easybytez] - No longer supported?

### ISSUE THREAD

**Issue by samad909** [pyload/pyload#3877]
Is Easybytez no longer supported? It is not listed inside the plugins in the latest pyLoad version.

**Comment by GammaC0de** [comment]
Is Easybytez still active?

http://www.easybytez.com/ leads to 403

**Comment by samad909** [comment]
Weird, it is up for me - https://prnt.sc/whbvtq

**Comment by Princeofthebow** [comment]
I came here for this very same reason as well. Moreover, do you know if a premium account was required or a free registered could do the job? 

Anyway, it is up for me. @GammaC0de may the issue be DNS?

**Comment by GammaC0de** [comment]
Plugin restored.
