### ISSUE TITLE
ClickNLoad urls are separated by spaces instead of new line.

### ISSUE THREAD

**Issue by 0x4d4d** [pyload/pyload#3880]
### Description

When I use ClickNLoad on Serialjunkies, it adds a package with only one link to download, with all links separated by a space. When the download begins, the download fails because of an invalid link.

Note: I have configured ssh port forwarding which redirects the request to my pyload instance.

I have analyzed the code a bit and found a location where the problem can be fixed.

```
module/web/cnl_app.py
40: - urls = [x.decode('latin1').strip() for x in request.POST['urls'].split("\n") if x.decode('latin1').strip()]
40: + urls = [x.decode('latin1').strip() for x in re.split("\n|\s", request.POST['urls']) if x.decode('latin1').strip()]
```

### Debug log

```

```

### Screenshots

![grafik](https://user-images.githubusercontent.com/20473294/104035159-190a0080-51d2-11eb-8278-550aae427e29.png)

**Comment by UserX404** [comment]
Reported this issue to SJ devs several time. It seems to me they don't want to support the cnl spec.
