### ISSUE TITLE
Filecrypt no decrpytion

### ISSUE THREAD

**Issue by Princeofthebow** [pyload/pyload#3882]
### Description

Hello I'm a total newbie here and I have tried to download via pyload(stable) the contents of filecrypt container(no *.dlc file). This has some how not succeded and I see a python trace log that may be suggestion I made some mistake with the installation, which may well be. 

Can anybody point me out in tthe right direction?

Thanks in advance.

### Debug log

```
08.01.2021 18:13:42 DEBUG     CRYPTER FilecryptCc[8]: LOAD URL http://filecrypt.cc/Link/RnKhek6LasplVCHRWebGravbXicN5nOdff_PeAlwfD8WU2FH_CF0BdLtRwuwDnNGpxWcTb84WrDB7GVdbvVl9_NJCSV92yIeJRK1kEiVBcAI-seTnOag8gL6441tAtkK.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.01.2021 18:13:42 DEBUG     CRYPTER FilecryptCc[8]: LOAD URL http://filecrypt.cc/Link/RnKhek6LasplVCHRWebGravbXicN5nOdff_PeAlwfD8WU2FH_CF0BdLtRwuwDnNGpxWcTb84WrDB7GVdbvVl9_NJCSV92yIeJRK1kEiVBcAI-seTnOag8gL6441tAtkK.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.01.2021 18:13:43 DEBUG     CRYPTER FilecryptCc[8]: LOAD URL http://filecrypt.cc/Link/RnKhek6LasplVCHRWebGravbXicN5nOdff_PeAlwfD8WU2FH_CF0BdLtRwuwDnNGpxWcTb84WrDB7GVdbvVl9_NJCSV92yIeJRK1kEiVBcAI-seTnOag8gL6441tAtkK.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.01.2021 18:13:43 DEBUG     CRYPTER FilecryptCc[8]: LOAD URL http://filecrypt.cc/Link/RnKhek6LasplVCHRWebGravbXicN5nOdff_PeAlwfD8WU2FH_CF0BdLtRwuwDnNGpxWcTb84WrDB7GVdbvVl9_NJCSV92yIeJRK1kEiVBcAI-seTnOag8gL6441tAtkK.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
08.01.2021 18:13:43 DEBUG     CRYPTER FilecryptCc[8]: LOAD URL http://filecrypt.cc/Link/RnKhek6LasplVCHRWebGravbXicN5nOdff_PeAlwfD8WU2FH_CF0BdLtRwuwDnNGpxWcTb84WrDB7GVdbvVl9_NJCSV92yIeJRK1kEiVBcAI-seTnOag8gL6441tAtkK.html | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False

08.01.2021 18:13:43 ERROR     CRYPTER FilecryptCc[8]: Weblink could not be found
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/jpk/Desktop/pyload-0.4.20/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/home/jpk/.pyload/userplugins/internal/Base.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/jpk/.pyload/userplugins/internal/Base.py", line 281, in _process
    self.process(self.pyfile)
  File "/home/jpk/Desktop/pyload-0.4.20/module/plugins/internal/Crypter.py", line 32, in process
    self.decrypt(pyfile)
  File "/home/jpk/.pyload/userplugins/crypter/FilecryptCc.py", line 112, in decrypt
    handle()
  File "/home/jpk/.pyload/userplugins/crypter/FilecryptCc.py", line 284, in handle_weblinks
    self.log_error(_("Weblink could not be found"))

```

I can of course provide the link if needed.

**Comment by GammaC0de** [comment]
What is the URL (http://filecrypt.cc/Link/RnKhek6LasplVCHRWebGravbXicN5nOdff_PeAlwfD8WU2FH_CF0BdLtRwuwDnNGpxWcTb84WrDB7GVdbvVl9_NJCSV92yIeJRK1kEiVBcAI-seTnOag8gL6441tAtkK.html)?
Where did you get it from?
It is not a valid filecrypt URL...

**Comment by Princeofthebow** [comment]
It has expired as the Filecrypt contained is updated daily. The Filecrypt I used is [here](https://www.filecrypt.cc/Container/73886A714A.html).

**Comment by GammaC0de** [comment]
This URL does not work with a a browser either..

**Comment by Princeofthebow** [comment]
I'm puzzled. It i[s working on my side](https://imgur.com/a/tJHtcrJ).

**Comment by GammaC0de** [comment]
I can open it also but it fails if you press "download" on a file...

**Comment by Princeofthebow** [comment]
Is suspect this may be becasue for seom reason (as in #3877 ) you were unable for some to open easybytez. 
Substantially after clikking download (on the [filecrypt page](https://www.filecrypt.cc/Container/73886A714A.html)) you are redirected to a easybytez page to download the file. See [this](https://imgur.com/a/KPMnnde) for instance

**Comment by GammaC0de** [comment]
I cannot get this URL to work with my browser, do you have another one to test?

**Comment by Princeofthebow** [comment]
[This](https://filecrypt.cc/Container/ED8105E695.html), however this has a dlc downloadable file so it may be different.

**Comment by Princeofthebow** [comment]
@GammaC0de show I give a try to your commits? How can I update the plugin to do so?

**Comment by GammaC0de** [comment]
@Princeofthebow pyload should auto update the plugin.

I also successfully tested it with the above URL , you can test further.

**Comment by Princeofthebow** [comment]
Excellent, and thanks. This was a superb job!

**Comment by GammaC0de** [comment]
👍

**Comment by Princeofthebow** [comment]
Hello sorry to write back here again but I have few questions.

- From the link I provided I have manually extracted - trough copy and paste- the filecrypt download link (which will in turn leads to easybytez). However when I pass this single file link to pyload it tries to use the base plugin and hence fails to find that its actaully a easybytez link and it does not download the desired file. For example from [this](https://www.filecrypt.cc/Container/73886A714A.html) page I extract [this](http://www.filecrypt.cc/Link/blJWmnQ1_wtjrns44pnHSCd5eUsCkj4DN-Ln9mAn8rWanI-SmF-NLiFHvgMGz6BbKrR3dtDJ7seToSLqBydFhf3odhetNV0MWEqjDwlkdr-hJuaFhCroQY9QNFq54I7l.html) link which does not work. How can I somehow feed pyload a singl link and get to download correctly the file?

- Is there a way to specify via the api to pyload to use a specific plug in for a given link?

Thanks in advance once again!

**Comment by GammaC0de** [comment]
> Is there a way to specify via the api to pyload to use a specific plug in for a given link?

No,
pyload uses the first plugin that:  the URL matches the regular expression defined in that plugin (`__pattern__` variable).
If no match found, it uses the base plugin.

Unfortunately, Filecrypt will refuse to resolve the extracted [link ](http://www.filecrypt.cc/Link/blJWmnQ1_wtjrns44pnHSCd5eUsCkj4DN-Ln9mAn8rWanI-SmF-NLiFHvgMGz6BbKrR3dtDJ7seToSLqBydFhf3odhetNV0MWEqjDwlkdr-hJuaFhCroQY9QNFq54I7l.html)if you don't load first the container URL and cookies are saved.
So the plugin cannot be updated to use extracted links.

**Comment by Princeofthebow** [comment]
ah ha! 
Thank you I did not know all this was happening under the hood with Filecrypt. 
Does that imply that in pyload code you actually get a session opening the container and from there gather all the links in the container and decrypt them by opening them one by one and gathering the final file? Or do you somehow decrypt them?

Moreover, once you have the list of decrypted links is it accessible via api?

**Comment by GammaC0de** [comment]
pyload tries to simulate a browser.
it gets the html from the web page, saves received cookies and then parses the html for links

**Comment by Princeofthebow** [comment]
Grazie! Thank you very much for your explanation now everything is much clearer!
