### ISSUE TITLE
click'n'load via ssh tunnel stopped working …

### ISSUE THREAD

**Issue by fooness** [pyload/pyload#3883]
Hello everyone. Unfortunately, click'n'load _suddenly_ stopped working for me.

> Links could not be transferred
> Please try again and make sure JDownloader is running. Download here

```
Loading failed for the <script> with source “http://localhost:9666/jdcheck.js?cb=40437148926”.   jdownloader-cnl:1:1
GET http://localhost:9666/jdcheck.js?cb=40437148926                                              [HTTP/1.0 403 Forbidden 18ms]
```

`pyload` is running on my raspberry pi.

```
$ python pyLoadCore.py
09.01.2021 15:20:41 INFO      Starting pyLoad 0.4.20
[…]
09.01.2021 15:20:42 INFO      Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, TORRENT, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
[…]
09.01.2021 15:20:51 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
```

My computer is forwarding click'n'load to my raspberry pi.

`ssh -N -L 9666:localhost:9666 user@pi`

I checked everything and searched through the issues here and asked some search engines, but I did not find anything that might help me. What I did stumble upon, though, is the following weird issue:

When navigating to `127.0.0.1:9666/flash`, I can see the word `JDownloader` (and nothing more) … when navigating to `localhost:9666/flash`, then I get `Error: 403 Forbidden` … could this be the source of the problem, maybe? And if yes, how could I debug or fix this?

```
$ curl http://localhost:9666/flash/
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 403 Forbidden</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 403 Forbidden</h1>
            <p>Sorry, the requested URL <tt>&#039;http://localhost:9666/flash&#039;</tt>
               caused an error:</p>
            <pre>Forbidden</pre>
        </body>
    </html>

$ curl http://127.0.0.1:9666/flash/
JDownloader
```

Here’s my `/etc/hosts` file, I’m on macOS 10.14.6 …

```
127.0.0.1        localhost
255.255.255.255  broadcasthost
::1              localhost
```

Tested in Firefox 84.0.2 and Chromium 89.0.4 …

**Comment by GammaC0de** [comment]
run:
`sudo tcpdump -vvvv -i lo port 9666`

And see what's going on

**Comment by fooness** [comment]
Pardon, I have no experience with tcpdump … I ran the command on both machines, on macOS I had to change `-i lo` to `-i lo0` and I hope this change was a correct assumptions. After I started `tcpdump`, I ran the click'n'load tab again until the fail message appears, then I stopped the dump.

Not sure if you see anything relevant in the dump?

[macbook.txt](https://github.com/pyload/pyload/files/5791400/macbook.txt)
[raspberry-pi.txt](https://github.com/pyload/pyload/files/5791401/raspberry-pi.txt)

**Comment by GammaC0de** [comment]
The capture has to be done on the remote machine (pi)

You will have to capture the packets to a file on the pi with tcpdump and then open the created file with wireshark on your mac to see what is going on.

See https://www.wireshark.org/docs/wsug_html_chunked/AppToolstcpdump.html

**Comment by fooness** [comment]
I have, unfortunately, no idea what to look for here. There is, though, also a message stating the `403 Forbidden` error which I mentioned previously in regards of navigating to `localhost:9666/flash/` in my browser.

<img width="1392" alt="Screenshot 2021-01-09 at 19 02 15" src="https://user-images.githubusercontent.com/11408027/104105281-568f8c00-52ad-11eb-8e73-03345aabbfec.png">

**Comment by GammaC0de** [comment]
Can you send the dump file?

**Comment by fooness** [comment]
Oh, sorry, I forgot to attach it. Please find below, that’s the file I imported to Wireshark in the screenshot above.

[raspberry-pi.txt](https://github.com/pyload/pyload/files/5791683/raspberry-pi.txt)

**Comment by GammaC0de** [comment]
I suspect the issue is because  you are are using IPv6.
Try changing [cnl_app.py#L20](https://github.com/pyload/pyload/blob/stable/module/web/cnl_app.py#L20) from:
```python
if request.environ.get('REMOTE_ADDR', "0") in ('127.0.0.1', 'localhost') \
```
to:
```python
if request.environ.get('REMOTE_ADDR', "0") in ('127.0.0.1', '::1', 'localhost') \
```

And then restart pyload,
hHopefully it would solve this.

**Comment by fooness** [comment]
> I suspect the issue is because you are are using IPv6.

Am I? Hm, maybe something was automatically changed when dist-upgrading raspbian to buster. IPv4 is definitely configured and working.

> Try changing cnl_app.py#L20 from:

Changed that line, restarted pyload, unfortunately the problem still persists.

Is it possible that the problem is not the pi/pyload, but something on my macbook?

**Comment by GammaC0de** [comment]
Maybe this [cnl_app.py#L21](https://github.com/pyload/pyload/blob/stable/module/web/cnl_app.py#L21) should be changed too:
```
        or request.environ.get('HTTP_HOST','0') in ('127.0.0.1:9666', '[::1]:9666'):
```

P.S.
I'm not sure about `[::1]:9666` since I have never used IPv6.

**Comment by fooness** [comment]
Still no success. I managed to find some other website with click'n'load links and on that other website it worked.

I’m going to try to contact the admin/support/whatever of the first website, maybe the problem is not pyload or macOS but something on the website itself?

Will update once I know more. Thank you so much for all your help so for. 🙌

**Comment by fooness** [comment]
@GammaC0de Alright, indeed it is a problem with `pyload`, and indeed the problem exists in the file `module/web/cnl_app.py` and the two lines `#20, #21` you pointed out before; I had to add `localhost:9666` to the second line, see below:

```
        if request.environ.get('REMOTE_ADDR', "0") in ('127.0.0.1', '::1', 'localhost') \
        or request.environ.get('HTTP_HOST','0') in ('127.0.0.1:9666', '[::1]:9666', 'localhost:9666'):
```

**Comment by GammaC0de** [comment]
What happens  if you change it to:
```
     if request.environ.get('REMOTE_ADDR', "0") in ('127.0.0.1', '::ffff:127.0.0.1', '::1', 'localhost') \
        or request.environ.get('HTTP_HOST','0') in ('127.0.0.1:9666', '[::1]:9666'):
```

(notice I removed localhost from HTTP_HOST since it can be forged)

**Comment by fooness** [comment]
> ```
>      if request.environ.get('REMOTE_ADDR', "0") in ('127.0.0.1', '::ffff:127.0.0.1', '::1', 'localhost') \
>         or request.environ.get('HTTP_HOST','0') in ('127.0.0.1:9666', '[::1]:9666'):
> ```

This way it works, too.

**Comment by GammaC0de** [comment]
👍 
See https://stackoverflow.com/questions/49793630/is-ffff127-0-0-1-localhost
