### ISSUE TITLE
ExtractArchive not extracting archives

### ISSUE THREAD

**Issue by TheHellSite** [pyload/pyload#3888]
### Description
As the title says. The plugin is not extracting my downloaded packages. Never.
It doesn't matter if the archives are password protected or not.

```
Python: 2.7.18 (default, Sep 5 2020, 11:17:26) [GCC 10.2.0]
OS: posix linux2 Linux DLVM-ARCHLINUX 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64
pyLoad version: 0.4.20
Installation Folder: /opt/pyload
Config Folder: /home/archie/.config/pyload
Download Folder: /mnt/nas/downloads
Free Space: 7.77 TiB
Language: en
Webinterface Theme: modern by GammaC0de based on work of Marco Fernandes and Dogan Bagci
Webinterface Port: 8000
Remote Interface Port: 7227
```

### Debug log
I don't have any log for this as there is no error in the logs.

### Screenshot of my settings.
https://imgur.com/a/MJ1FGwC

**Comment by GammaC0de** [comment]
Please enable debug mode, restart pyload and then:
download a file to be extracted and then provide the log from the moment pyload start until download is finished without extraction.

**Comment by TheHellSite** [comment]
Find attached my log. As I already said, there is no reason for the plugin to not extract the files.
I downloaded two archives, both without password.
1# a splitted 100 MB .7z-file (10 MB parts)
2# a single 100 MB .7z-file

[log.txt](https://github.com/pyload/pyload/files/5809587/log.txt)

**Comment by GammaC0de** [comment]
> 13.01.2021 15:57:20 DEBUG     ADDON ExtractArchive: Found HjSplit 0.02 | Found UnZip 2.7.18 | Found UnTar 2.7.18

You do not have neither 7zip nor unrar installed on your system.
pleas install 7zip.

**Comment by TheHellSite** [comment]
Okay I understand. My bad!
Does pyload also support "unar" or "lsar"? I would like to only use opensource packages.
https://archlinux.org/packages/community/x86_64/unarchiver/

**Comment by GammaC0de** [comment]
Probably https://archlinux.org/packages/extra/x86_64/p7zip/

Pyload does not supports any archivers other then unrar and 7zip.
If you insist using 3rd party archiver, you'll have to write a plugin for it yourself.

**Comment by TheHellSite** [comment]
Okay, then I will simple use the supported packages. Thank you for the support!
