### ISSUE TITLE
Add Krakenfiles.com to the list

### ISSUE THREAD

**Issue by H4Z4RD-H42** [pyload/pyload#3889]
### Description

It's possible to add krakenfiles.com to the available website?

### Sample resources

https://krakenfiles.com

**Comment by vuolter** [comment]
A sample resource should preferably be an url pointing to a content (eg. file) hosted by the service, not just the homepage, thx.

**Comment by bulubebek** [comment]
sorry for resurrecting necro issue. seems hoster plugin for Krakenfiles is not working here.

`08.05.2022 12:44:24 INFO      Added package SEP containing 1 links
08.05.2022 12:44:24 INFO      Download starts: https://krakenfiles.com/view/eDkkKbjGd0/file.html
08.05.2022 12:44:24 WARNING   HOSTER KrakenfilesCom[35]: Plugin may be unstable
08.05.2022 12:44:24 INFO      HOSTER KrakenfilesCom[35]: Processing url: https://krakenfiles.com/view/eDkkKbjGd0/file.html
08.05.2022 12:44:24 INFO      HOSTER KrakenfilesCom[35]: Looking for direct download link...
08.05.2022 12:44:25 INFO      HOSTER KrakenfilesCom[35]: Direct download link not found
08.05.2022 12:44:25 INFO      HOSTER KrakenfilesCom[35]: Checking for link errors...
08.05.2022 12:44:25 INFO      HOSTER KrakenfilesCom[35]: No errors found
08.05.2022 12:44:25 INFO      HOSTER KrakenfilesCom[35]: Grabbing link info...
08.05.2022 12:44:25 INFO      HOSTER KrakenfilesCom[35]: Link name: file.html
08.05.2022 12:44:25 INFO      HOSTER KrakenfilesCom[35]: Link size: N/D
08.05.2022 12:44:25 INFO      HOSTER KrakenfilesCom[35]: Link status: starting
08.05.2022 12:44:25 INFO      HOSTER KrakenfilesCom[35]: Processing as free download...
08.05.2022 12:44:25 WARNING   HOSTER KrakenfilesCom[35]: Free download failed | hash pattern not found
08.05.2022 12:44:25 WARNING   Download failed: file.html | hash pattern not found
08.05.2022 12:44:25 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: file.html (pid:22)
08.05.2022 12:44:25 INFO      ADDON UnSkipOnFail: No duplicates found`

Thank you.

**Comment by GammaC0de** [comment]
Next time please open a new issue, thanks.

**Comment by bulubebek** [comment]
> Next time please open a new issue, thanks.

roger that, thank you for the fix. I can confirm plugin for KrakenFiles work as expected now.
