### ISSUE TITLE
DDOWNLOAD.COM (Ddl.to) dont recognize Premium Account

### ISSUE THREAD

**Issue by BitBlockv6** [pyload/pyload#3890]
DDOWNLOAD.COM ( Ddl.to ) 
dont recognize Premium Account

**Comment by uysct** [comment]
There are no problems here ...

**Comment by lmoesch** [comment]
Maybe it's this issue #3618

**Comment by inDane** [comment]
there isnt a Ddl.to account-option in the "Type" drop-down menu for me. Installed just now via "pip install --pre pyload-ng[all]"

![pyload](https://user-images.githubusercontent.com/5693407/106391837-897df900-63ef-11eb-96a5-97edfe6151af.jpg)

**Comment by GammaC0de** [comment]
@inDane You should use pyload stable (v0.4.20) not the beta v0.5.
Get it from here: https://github.com/pyload/pyload/releases/tag/0.4.20

**Comment by inDane** [comment]
> 
> 
> @inDane You should use pyload stable (v0.4.20) not the beta v0.5.
> Get it from here: https://github.com/pyload/pyload/releases/tag/0.4.20

whoops, thanks. Im looking into it...

**Comment by inDane** [comment]
yup, works just fine!

**Comment by Tao87-04** [comment]
i have same Problem. i use pyload 0.4.2, but pyload dont recognize my premium acc :(

Log say this
`ACCOUNT DdownloadCom: Could not login user `Cre*******` | (7, 'Failed to connect to www.ddownload.com port 80: Connection refused')`

**Comment by GammaC0de** [comment]
@Tao87-04 According to the log, It seems that your IP is banned or you have some type of connection issue.

**Comment by Tao87-04** [comment]
sounds logical, I'm looking for the error in my network. pihole may be crazy
