### ISSUE TITLE
Confusing unit for max download speed

### ISSUE THREAD

**Issue by 0x4c47** [pyload/pyload#3894]
### Description

The unit given in the description for the "Max Download Speed" (Config -> Download) is "kb/s" which should translate to kilo**bit** per second. I wanted to limit speed to ~4,5 megabyte per second so I set this value to 36000.
But it still downloaded with speeds way above 4,5 MB/s.

I set it to 4500 and it did download at roughly 4,5 megabyte per second after that.

So I guess that this value is not kilo**bit** per second (k**b**/s) as it's stated in the description but actually kilo**byte** per second which would be k**B**/s. This should be fixed in the description text.

Maybe even write it out so it's clear what the unit is. Megabyte per second (MB/s) as a float might also be more useful and coherent for most users today.

(Please ignore my ignorance towards the MiB vs MB difference here.^^)

**Comment by GammaC0de** [comment]
> "kb/s" which should translate to kilobit per second

Then it would have said kbit/s,
kb/s is kilo**byte**/s...

I notice one cosmetic issue:
While this settings uses KB/s, the WebUI shows the speed in KiB/s.
See https://en.wikipedia.org/wiki/Byte#Multiple-byte_units for the difference.

**Comment by 0x4c47** [comment]
> kb/s is kilo**byte**/s...

According to [this article](https://en.m.wikipedia.org/wiki/Data-rate_units) kb/s is kilobit/s and kB/s is kilobyte/s.

**Comment by GammaC0de** [comment]
OK, you are right.
I will update the description
