### ISSUE TITLE
Uploadgig log in failure

### ISSUE THREAD

**Issue by artdog123** [pyload/pyload#3895]
### Description
I am running pyLoad 0.4.20 on my raspberry pi 4 using an Uploadgig premium account. It has been fine since the install but yesterday I began to get an error in the logs:
ERROR | ACCOUNT UploadgigCom: Could not login user `art*******` \| Login handshake has failed

In addition, the account shows plugin: none, name: none and cannot be deleted. 

I have contacted Uploadgig but I doubt they will assist. 
-- | --

### Debug log

```

```

### Additional references
Debug log:

274 | ? | ? | File "/app/pyload/module/plugins/internal/Account.py", line 275, in getAllAccounts
-- | -- | -- | --
275 | ? | ? | self.init_accounts()  # @TODO: Recheck in 0.4.10
276 | ? | ? | File "/app/pyload/module/plugins/internal/misc.py", line 228, in new
277 | ? | ? | return fn(*args, **kwargs)
278 | ? | ? | File "/app/pyload/module/plugins/internal/Account.py", line 263, in init_accounts
279 | ? | ? | self.add(user, info['password'], info['options'])
280 | ? | ? | File "/app/pyload/module/plugins/internal/misc.py", line 228, in new
281 | ? | ? | return fn(*args, **kwargs)
282 | ? | ? | File "/app/pyload/module/plugins/internal/Account.py", line 310, in add
283 | ? | ? | u['plugin'].get_info()
284 | ? | ? | File "/app/pyload/module/plugins/internal/Account.py", line 196, in get_info
285 | ? | ? | if self.relogin():
286 | ? | ? | File "/app/pyload/module/plugins/internal/Account.py", line 173, in relogin
287 | ? | ? | return self.login()
288 | ? | ? | File "/app/pyload/module/plugins/internal/Account.py", line 114, in login
289 | ? | ? | self.info['data'])
290 | ? | ? | File "/app/pyload/module/plugins/accounts/UploadgigCom.py", line 66, in signin
291 | ? | ? | self.fail_login()
292 | ? | ? | File "/app/pyload/module/plugins/internal/Account.py", line 441, in fail_login
293 | ? | ? | return self.fail(msg)
294 | ? | ? | File "/app/pyload/module/plugins/internal/Plugin.py", line 191, in fail
295 | ? | ? | raise Fail(decode(msg))  # @TODO: Remove `decode` in 0.4.10
296 | ? | ? | Fail: Login handshake has failed
297 | ? | ? |  
298 | 06.02.2021 10:50:20 | INFO | Activating Plugins...
299 | 06.02.2021 10:50:20 | WARNING | ADDON TORRENT: torrents / magnets are not associated with any plugin
300 | 06.02.2021 10:50:20 | DEBUG | ADDON ExternalScripts: No script found under folder `pyload_start`
301 | 06.02.2021 10:50:20 | DEBUG | ADDON UpdateManager: LOAD URL  https://raw.githubusercontent.com/pyload/updates/master/plugins.txt \|  redirect=True \| cookies=True \| get={'v': '0.4.20'} \| req=None \|  decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
302 | 06.02.2021 10:50:20 | INFO | pyLoad is up and running
303 | 06.02.2021 10:50:20 | INFO | ADDON UpdateManager: pyLoad is up to date!
304 | 06.02.2021 10:50:20 | DEBUG | ADDON UpdateManager: LOAD URL  https://raw.githubusercontent.com/pyload/updates/master/plugins.txt \|  redirect=True \| cookies=True \| get={'v': '0.4.20'} \| req=None \|  decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
305 | 06.02.2021 10:50:20 | DEBUG | ADDON UpdateManager: Requested deletion of plugins: [(u'accounts',  u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts',  u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts',  u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts',  u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts',  u'FreeWayMe'), (u'accounts', u'GetTwentyFourOrg'), (u'accounts',  u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts',  u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts',  u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts',  u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts',  u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts',  u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts',  u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts',  u'ShareonlineBiz'), (u'accounts', u'StahnuTo'), (u'accounts',  u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts',  u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts',  u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha',  u'GigasizeCom'), (u'captcha', u'LinksaveIn'), (u'captcha',  u'NetloadIn'), (u'captcha', u'OCR'), (u'captcha', u'ShareonlineBiz'),  (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container',  u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'),  (u'crypter', u'BitshareComFolder'), (u'crypter', u'C1NeonCom'),  (u'crypter', u'C1neonCom'), (u'crypter', u'CryptItCom'), (u'crypter',  u'DailymotionBatch'), (u'crypter', u'DdlstorageComFolder'), (u'crypter',  u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter',  u'DuckCryptInfo'), (u'crypter', u'DuploadOrgFolder'), (u'crypter',  u'FilebeerInfoFolder'), (u'crypter', u'FilesonicComFolder'),  (u'crypter', u'FiredriveComFolder'), (u'crypter', u'Go4Up'),  (u'crypter', u'HotfileComFolder'), (u'crypter', u'HotfileFolderCom'),  (u'crypter', u'ILoadTo'), (u'crypter', u'ImgurComAlbum'), (u'crypter',  u'JunocloudMeFolder'), (u'crypter', u'LetitbitNetFolder'), (u'crypter',  u'LinkCryptWs'), (u'crypter', u'LinkSaveIn'), (u'crypter', u'LofCc'),  (u'crypter', u'MBLinkInfo'), (u'crypter', u'MegauploadComFolder'),  (u'crypter', u'Movie2KTo'), (u'crypter', u'Movie2kTo'), (u'crypter',  u'MultiuploadCom'), (u'crypter', u'NCryptIn'), (u'crypter',  u'NetfolderIn'), (u'crypter', u'OneKhDe'), (u'crypter',  u'OronComFolder'), (u'crypter', u'RSLayerCom'), (u'crypter',  u'RapidfileshareNetFolder'), (u'crypter', u'RelinkUs'), (u'crypter',  u'SecuredIn'), (u'crypter', u'ShareLinksBiz'), (u'crypter',  u'ShareRapidComFolder'), (u'crypter', u'SharingmatrixComFolder'),  (u'crypter', u'SpeedLoadOrgFolder'), (u'crypter', u'StealthTo'),  (u'crypter', u'TORRENT'), (u'crypter', u'TrailerzoneInfo'), (u'crypter',  u'UploadableChFolder'), (u'crypter', u'WiiReloadedOrg'), (u'crypter',  u'WuploadComFolder'), (u'crypter', u'XFileSharingProFolder'),  (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks',  u'AlldebridComHook'), (u'hooks', u'AndroidPhoneNotify'), (u'hooks',  u'Captcha9kw'), (u'hooks', u'CaptchaBrotherhood'), (u'hooks',  u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks',  u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks',  u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks',  u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'),  (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks',  u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks',  u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks',  u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks',  u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks',  u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks',  u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks',  u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks',  u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks',  u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks',  u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks',  u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks',  u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'),  (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks',  u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks',  u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'),  (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks',  u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks',  u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'),  (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'),  (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'),  (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks',  u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks',  u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks',  u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks',  u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster',  u'BayfilesCom'), (u'hoster', u'BillionuploadsCom'), (u'hoster',  u'BitshareCom'), (u'hoster', u'BoltsharingCom'), (u'hoster',  u'CloudzerNet'), (u'hoster', u'CyberlockerCh'), (u'hoster',  u'DdlstorageCom'), (u'hoster', u'DodanePl'), (u'hoster', u'DuploadOrg'),  (u'hoster', u'EgoFilesCom'), (u'hoster', u'EnteruploadCom'),  (u'hoster', u'EpicShareNet'), (u'hoster', u'File4safeCom'), (u'hoster',  u'FileApeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster',  u'FilebeerInfo'), (u'hoster', u'FileshareInUa'), (u'hoster',  u'FilesonicCom'), (u'hoster', u'FilezyNet'), (u'hoster',  u'FiredriveCom'), (u'hoster', u'FreeWayMe'), (u'hoster',  u'FreevideoCz'), (u'hoster', u'GetTwentyFourOrg'), (u'hoster',  u'HellspyCz'), (u'hoster', u'HotfileCom'), (u'hoster', u'IFileWs'),  (u'hoster', u'IcyFilesCom'), (u'hoster', u'IfileIt'), (u'hoster',  u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster',  u'KickloadCom'), (u'hoster', u'LemUploadsCom'), (u'hoster',  u'LetitbitNet'), (u'hoster', u'Libgen'), (u'hoster', u'LolabitsEs'),  (u'hoster', u'LomafileCom'), (u'hoster', u'MegaDebrid'), (u'hoster',  u'MegaFilesSe'), (u'hoster', u'MegaNz'), (u'hoster', u'MegareleaseOrg'),  (u'hoster', u'MegauploadCom'), (u'hoster', u'MegavideoCom'),  (u'hoster', u'MultiDebridCom'), (u'hoster', u'MyvideoDe'), (u'hoster',  u'NahrajCz'), (u'hoster', u'NetloadIn'), (u'hoster', u'NowDownloadEu'),  (u'hoster', u'NowDownloadSx'), (u'hoster', u'NowVideoAt'), (u'hoster',  u'OronCom'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'),  (u'hoster', u'PandaplaNet'), (u'hoster', u'PotloadCom'), (u'hoster',  u'Premium4Me'), (u'hoster', u'PrzeklejPl'), (u'hoster',  u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster',  u'RealdebridComTorrent'), (u'hoster', u'ReloadCc'), (u'hoster',  u'RyushareCom'), (u'hoster', u'SendmywayCom'), (u'hoster',  u'Share4webCom'), (u'hoster', u'Share76Com'), (u'hoster',  u'ShareFilesCo'), (u'hoster', u'ShareRapidCom'), (u'hoster',  u'SharebeesCom'), (u'hoster', u'ShareonlineBiz'), (u'hoster',  u'SharingmatrixCom'), (u'hoster', u'ShragleCom'), (u'hoster',  u'SockshareCom'), (u'hoster', u'Solidfiles'), (u'hoster',  u'SpeedLoadOrg'), (u'hoster', u'SpeedfileCz'), (u'hoster', u'StahnuTo'),  (u'hoster', u'StorageTo'), (u'hoster', u'TurbouploadCom'), (u'hoster',  u'UnrestrictLi'), (u'hoster', u'UploadStationCom'), (u'hoster',  u'UploadableCh'), (u'hoster', u'UploadboxCom'), (u'hoster',  u'UploadhereCom'), (u'hoster', u'UploadingCom'), (u'hoster',  u'UploadkingCom'), (u'hoster', u'Vipleech4UCom'), (u'hoster',  u'Vipleech4uCom'), (u'hoster', u'WarserverCz'), (u'hoster',  u'WuploadCom'), (u'hoster', u'X7To'), (u'hoster', u'XFileSharingPro'),  (u'hoster', u'ZShareNet'), (u'hoster', u'ZahikiNet'), (u'internal',  u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal',  u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'),  (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'),  (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'),  (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'),  (u'internal', u'utils')]
306 | 06.02.2021 10:50:20 | INFO | ADDON UpdateManager: All plugins are up to date!
307 | 06.02.2021 10:50:26 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
They have added a recaptcha to the login form..
