### ISSUE TITLE
 Login handshake has failed

### ISSUE THREAD

**Issue by tomcdj71** [pyload/pyload#3896]
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [x] Bug report
- [ ] Question
- [ ] Other

### Summary:

Can't login to uptobox.
### Actual behavior:

I have two accounts, both two are new and premium for a month. I can send credentials for tests.
Using pyLoad 0.4.20 on Ubuntu 20.4 server and Windows.
Both uses standard config with only the uptobox account.
Also tested with adding devices to my uptobox account from the uptobox api (with`curl https://uptobox.com/api/streaming`).
### Debug log:

09.02.2021 15:24:40 | INFO | ACCOUNT UptoboxCom: Adding user `tho*******`...
09.02.2021 15:24:40 | DEBUG | ACCOUNT UptoboxCom: Reached login timeout for user `tho*******`
09.02.2021 15:24:40 | INFO | ACCOUNT UptoboxCom: Login user `tho*******`...
09.02.2021 15:24:40 | DEBUG | ACCOUNT UptoboxCom: LOAD URL https://uptobox.com/login \| redirect=True \|  cookies=True \| get={} \| req=None \| decode=True \| multipart=False \|  post={} \| ref=True \| just_header=False
09.02.2021 15:24:40 | DEBUG | ACCOUNT UptoboxCom: LOAD URL https://uptobox.com/login \| redirect=True \|  cookies=True \| get={'referer': 'homepage'} \| req=None \| decode=True \|  multipart=False \| post={'login': 'tho*******', 'password': '**********'}  \| ref=True \| just_header=False
09.02.2021 15:24:40 | ERROR | ACCOUNT UptoboxCom: Could not login user `tho*******` \| Login handshake has failed

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by tomcdj71** [comment]
Credentials sent.
Thanks in advance
