### ISSUE TITLE
Slow Download Speed

### ISSUE THREAD

**Issue by SweetthD3ViL** [pyload/pyload#3904]
Hello,

Long time user of PyLoad (both on a NAS running ARM-Archlinux, and a desktop running Archlinux)

I have an home broadband running at about 65 MiB/s on average (soon to be updated to FTTP at 300 MiB/s!!) 

Anyway, I am looking into the download speed of the NAS averaging at 2.5 MiB/s. Now I know that the download speed will vary greatly from the source and the usage of other users on my network. However, I can easily get to 8.5 MiB/s downloading using PyLoad on my PC. 

Both files where downloading from uptobox within 5mins (and I never get above 2.8 MiB/s from the NAS)

My hard drive is a WD Red WD Red Plus 2TB 3.5" SATA NAS Hard Drive - WD20EFRX (CMR) 

Running a speed/write test onto this hard drive will give me the following: 

Write test:
sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 17.9825 s, 59.7 MB/s

Read test:
dd if=tempfile of=/dev/null bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 11.0121 s, 97.5 MB/s

Giving those test, I should be able to Download at about three time the speed? 

Is there a test of log I can look at that would be able to point me to the right direction?

Thank you for your time.

**Comment by GammaC0de** [comment]
This also  depends on your NAS's hardware strength: CPU, memory and network card speed (100/1000)
