### ISSUE TITLE
KeyError in PluginManager on ddl.to plugin

### ISSUE THREAD

**Issue by myxor** [pyload/pyload#3905]
### Description

Downloads from ddl.to not possible even though the plugin is enabled and was working a few days ago.

### Debug log

40 | 28.02.2021 10:22:26 | WARNING | Plugin DdlTo not found.
41 | 28.02.2021 10:22:26 | CRITICAL | None
42 | ? | ? | Traceback (most recent call last):
43 | ? | ? | File "/app/pyload/module/ThreadManager.py", line 269, in assignJob
44 | ? | ? | job.initPlugin()
45 | ? | ? | File "/app/pyload/module/utils.py", line 169, in new
46 | ? | ? | return func(*args)
47 | ? | ? | File "/app/pyload/module/PyFile.py", line 101, in initPlugin
48 | ? | ? | self.pluginmodule = self.m.core.pluginManager.getPlugin(self.pluginname)
49 | ? | ? | File "/app/pyload/module/plugins/PluginManager.py", line 279, in getPlugin
50 | ? | ? | return self.loadModule(type, name)
51 | ? | ? | File "/app/pyload/module/plugins/PluginManager.py", line 296, in loadModule
52 | ? | ? | plugins = self.plugins[type]
53 | ? | ? | KeyError: None
54 | 28.02.2021 10:22:28 | WARNING | Plugin DdlTo not found.
55 | 28.02.2021 10:22:28 | CRITICAL | None
56 | ? | ? | Traceback (most recent call last):
57 | ? | ? | File "/app/pyload/module/ThreadManager.py", line 269, in assignJob
58 | ? | ? | job.initPlugin()
59 | ? | ? | File "/app/pyload/module/utils.py", line 169, in new
60 | ? | ? | return func(*args)
61 | ? | ? | File "/app/pyload/module/PyFile.py", line 101, in initPlugin
62 | ? | ? | self.pluginmodule = self.m.core.pluginManager.getPlugin(self.pluginname)
63 | ? | ? | File "/app/pyload/module/plugins/PluginManager.py", line 279, in getPlugin
64 | ? | ? | return self.loadModule(type, name)
65 | ? | ? | File "/app/pyload/module/plugins/PluginManager.py", line 296, in loadModule
66 | ? | ? | plugins = self.plugins[type]
67 | ? | ? | KeyError: None

**Comment by GammaC0de** [comment]
DdlTo was renamed to DdownloadCom.
Please Remo e the DdlTo Account and then add DdownloadCom account inatead

**Comment by myxor** [comment]
Well, i am not using any account for DdlTo. 
Although i do have downloads in the queue which seem to not find the DdlTo plugin. Do i have to readd all these downloads?

**Comment by GammaC0de** [comment]
I'm afraid so. 
 
  Marco H<notifications@github.com> wrote:   


Do i have to readd all these downloads?

**Comment by uysct** [comment]
My DdlTo account was apparently automatically removed by PyLoad after the update. 
After adding my access data to the DdownloadCom account, I get: 

`ERROR Bad or missing plugin: ACCOUNT DdlTo`

I even get this message when I manually deactivate the old DdlTo account plugin in the plugin tab.

**Comment by GammaC0de** [comment]
Try to stop pyload and then manually edit accounts.conf removing the old account.

**Comment by uysct** [comment]
That's working! Thanks again for the quick support ...

**Comment by uysct** [comment]
Happy too early. After editing, no download works anymore ... 

397	28.02.2021 15:00:45	WARNING	Plugin DdlTo not found.
398	28.02.2021 15:00:45	CRITICAL	None
399	?	?	Traceback (most recent call last):
400	?	?	File "/opt/pyload/module/ThreadManager.py", line 269, in assignJob
401	?	?	job.initPlugin()
402	?	?	File "/opt/pyload/module/utils.py", line 169, in new
403	?	?	return func(*args)
404	?	?	File "/opt/pyload/module/PyFile.py", line 101, in initPlugin
405	?	?	self.pluginmodule = self.m.core.pluginManager.getPlugin(self.pluginname)
406	?	?	File "/opt/pyload/module/plugins/PluginManager.py", line 279, in getPlugin
407	?	?	return self.loadModule(type, name)
408	?	?	File "/opt/pyload/module/plugins/PluginManager.py", line 296, in loadModule
409	?	?	plugins = self.plugins[type]
410	?	?	KeyError: None
411	28.02.2021 15:00:47	WARNING	Plugin DdlTo not found.
412	28.02.2021 15:00:47	CRITICAL	None
413	?	?	Traceback (most recent call last):
414	?	?	File "/opt/pyload/module/ThreadManager.py", line 269, in assignJob
415	?	?	job.initPlugin()
416	?	?	File "/opt/pyload/module/utils.py", line 169, in new
417	?	?	return func(*args)
418	?	?	File "/opt/pyload/module/PyFile.py", line 101, in initPlugin
419	?	?	self.pluginmodule = self.m.core.pluginManager.getPlugin(self.pluginname)
420	?	?	File "/opt/pyload/module/plugins/PluginManager.py", line 279, in getPlugin
421	?	?	return self.loadModule(type, name)
422	?	?	File "/opt/pyload/module/plugins/PluginManager.py", line 296, in loadModule
423	?	?	plugins = self.plugins[type]
424	?	?	KeyError: None

**Comment by GammaC0de** [comment]
@uysct Have you solved your issue?

**Comment by uysct** [comment]
Yes everything works now. Thank you for your excellent support. 
In between I had these error messages in the log and file download was not possible. But now everything is working again, no idea why these messages came up in the log. 

397	28.02.2021 15:00:45	WARNING	Plugin DdlTo not found.
398	28.02.2021 15:00:45	CRITICAL	None
399	?	?	Traceback (most recent call last):
400	?	?	File "/opt/pyload/module/ThreadManager.py", line 269, in assignJob
401	?	?	job.initPlugin()
402	?	?	File "/opt/pyload/module/utils.py", line 169, in new
403	?	?	return func(*args)
404	?	?	File "/opt/pyload/module/PyFile.py", line 101, in initPlugin
405	?	?	self.pluginmodule = self.m.core.pluginManager.getPlugin(self.pluginname)
406	?	?	File "/opt/pyload/module/plugins/PluginManager.py", line 279, in getPlugin
407	?	?	return self.loadModule(type, name)
408	?	?	File "/opt/pyload/module/plugins/PluginManager.py", line 296, in loadModule
409	?	?	plugins = self.plugins[type]
410	?	?	KeyError: None
411	28.02.2021 15:00:47	WARNING	Plugin DdlTo not found.
412	28.02.2021 15:00:47	CRITICAL	None
413	?	?	Traceback (most recent call last):
414	?	?	File "/opt/pyload/module/ThreadManager.py", line 269, in assignJob
415	?	?	job.initPlugin()
416	?	?	File "/opt/pyload/module/utils.py", line 169, in new
417	?	?	return func(*args)
418	?	?	File "/opt/pyload/module/PyFile.py", line 101, in initPlugin
419	?	?	self.pluginmodule = self.m.core.pluginManager.getPlugin(self.pluginname)
420	?	?	File "/opt/pyload/module/plugins/PluginManager.py", line 279, in getPlugin
421	?	?	return self.loadModule(type, name)
422	?	?	File "/opt/pyload/module/plugins/PluginManager.py", line 296, in loadModule
423	?	?	plugins = self.plugins[type]
424	?	?	KeyError: None

**Comment by SmartC2016** [comment]
Hey. I had the same error and the proposed solution worked for me as well. Thanks a lot for the support!

**Comment by GammaC0de** [comment]
@uysct 
>397 28.02.2021 15:00:45 WARNING Plugin DdlTo not found.

This probably because some URLs you had previously added that used the not non existing `DdlTo `plugin.

Closing :+1:
