### ISSUE TITLE
Cannot download a rar content

### ISSUE THREAD

**Issue by Whisper40** [pyload/pyload#3910]
### Description

Today i'm trying your tool, permissions are ok, so i'm trying to download content.rar here : 
https://dev-files.blender.org/file/download/fbesofb22svautbktglp/PHID-FILE-onmshh3l6jhqdeq3ctdz/sample.rar

But it doesn't work
### Logs 
```
15.03.2021 11:25:38 INFO      HOSTER BasePlugin[4]: Link size: N/D
15.03.2021 11:25:38 INFO      HOSTER BasePlugin[4]: Link status: starting
15.03.2021 11:25:38 INFO      HOSTER BasePlugin[4]: Processing url: https://dev-files.blender.org/file/download/fbesofb22svautbktglp/PHID-FILE-onmshh3l6jhqdeq3ctdz/sample.rar
15.03.2021 11:25:39 WARNING   Download failed: sample.rar | Downloaded content was smaller than expected. Try to reduce download connections.
15.03.2021 11:25:39 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: sample.rar (pid:4)
15.03.2021 11:25:39 INFO      ADDON UnSkipOnFail: No duplicates found
```

**Comment by OzzieIsaacs** [comment]
I can reproduce the problem also with the development branch. It can be avoided by setting `Max connections per download` to  to `1`:
![grafik](https://user-images.githubusercontent.com/6438895/111174650-e56b9e00-85a7-11eb-8b22-719757fecff6.png)

The file is indeed smaller as the chunk sizes imply:

![grafik](https://user-images.githubusercontent.com/6438895/111175499-c3bee680-85a8-11eb-9e11-52056f0abd8b.png)
I did a binary compare of the rar file and the content of the file they are having no difference to a downloaded version via a normal browser (firefox in my case). The browser is downloading the file without any problems

**Comment by Whisper40** [comment]
Ok good :) That's good to report true bugs ;) 
That was my first test with the app

**Comment by GammaC0de** [comment]
The server advertised it supports chunked download while it does not,
no way to predict that.
