### ISSUE TITLE
Autosuspend setup

### ISSUE THREAD

**Issue by SweetthD3ViL** [pyload/pyload#3918]
Hello there,

I just setup a new home server running Archlinux, as it is a home server it will not be needed all the time. 

Currently, trying to setup router to wake the server up on oncoming traffic to the server through wol.

Anyhow, the Dev from autosuspend is asking if pyload had an HTTP-api (see below)

In any case, you can also extend autosuspend with custom checks using Python classes or you can use the ExternalCommand check to execute a custom script that then determines whether something like PyLoad is currently downloading anything. If PyLoad has an HTTP-API, that could also be checked with things like the JsonPath check.

Thank you

**Comment by GammaC0de** [comment]
You call `http://<PYLOAD_IP>/json/status` which returns `json` and check the value of the `active `variable

**Comment by SweetthD3ViL** [comment]
Apologies, I have been quite busy lately but should have thank you for your reply that worked perfectly!

Many thanks for your work and time, greatly appreciated.

**Comment by GammaC0de** [comment]
👍
