### ISSUE TITLE
Plugin Fshare error

### ISSUE THREAD

**Issue by thiennguyenqn** [pyload/pyload#3920]
### Description

Plugin Fshare error! I logged in with fshare vip account but the plugin reported an error. Screenshot below . Thank you <3
Can you update new API: https://www.fshare.vn/api-doc
https://github.com/pyload/pyload/blob/main/src/pyload/plugins/accounts/FshareVn.py

### Debug log

1037 | ? | ? | PYLOAD.updateAccount(type, login, password)
-- | -- | -- | --
1038 | ? | ? | File "/root/pyload/module/Api.py", line 895, in updateAccount
1039 | ? | ? | self.core.accountManager.updateAccount(plugin, account, password, options)
1040 | ? | ? | File "/root/pyload/module/utils.py", line 169, in new
1041 | ? | ? | return func(*args)
1042 | ? | ? | File "/root/pyload/module/plugins/AccountManager.py", line 153, in updateAccount
1043 | ? | ? | updated = p.updateAccounts(user, password, options)
1044 | ? | ? | File "/root/pyload/module/plugins/internal/misc.py", line 228, in new
1045 | ? | ? | return fn(*args, **kwargs)
1046 | ? | ? | File "/root/pyload/module/plugins/internal/Account.py", line 332, in updateAccounts
1047 | ? | ? | self.add(user, password, options)
1048 | ? | ? | File "/root/pyload/module/plugins/internal/misc.py", line 228, in new
1049 | ? | ? | return fn(*args, **kwargs)
1050 | ? | ? | File "/root/pyload/module/plugins/internal/Account.py", line 309, in add
1051 | ? | ? | result = u['plugin'].choose(user)
1052 | ? | ? | File "/root/pyload/module/plugins/internal/misc.py", line 228, in new
1053 | ? | ? | return fn(*args, **kwargs)
1054 | ? | ? | File "/root/pyload/module/plugins/internal/Account.py", line 426, in choose
1055 | ? | ? | self.relogin()
1056 | ? | ? | File "/root/pyload/module/plugins/internal/Account.py", line 173, in relogin
1057 | ? | ? | return self.login()
1058 | ? | ? | File "/root/pyload/module/plugins/internal/Account.py", line 114, in login
1059 | ? | ? | self.info['data'])
1060 | ? | ? | File "/root/pyload/module/plugins/accounts/FshareVn.py", line 87, in signin
1061 | ? | ? | self.fail_login()
1062 | ? | ? | File "/root/pyload/module/plugins/internal/Account.py", line 441, in fail_login
1063 | ? | ? | return self.fail(msg)
1064 | ? | ? | File "/root/pyload/module/plugins/internal/Plugin.py", line 191, in fail
1065 | ? | ? | raise Fail(decode(msg)) # @TODO: Remove `decode` in 0.4.10
1066 | ? | ? | Fail: Login handshake has failed

```

```

### Screenshots

![image](https://user-images.githubusercontent.com/44944761/112865408-f0afe500-90e2-11eb-8e10-22acac4ac43a.png)

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by thiennguyenqn** [comment]
> Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

I sent it to your mail. Thanks.
