### ISSUE TITLE
Downloads hang in "starting"

### ISSUE THREAD

**Issue by asdproton** [pyload/pyload#3922]
I very often see the following: I upload a DLC, things seem to go nicely. When I come back a while later, downloads have stopped but not all files are downloaded. The Queue shows them in "starting". When I retry they go into queued and download just fine. If I tag too many the first ones get downloaded, the rest goes into starting again.

Happens with all sorts of downloaders (RealDebrid, DDownload).

**Comment by GammaC0de** [comment]
1. pyLoad 0.5 is beta and not released yet.
2.  have you updated your installation to the latest develop branch?
3. if so, please provide debug log
4. since 0.5 is beta, not all of the plugins were migrated yet so this can cause this issue.

**Comment by asdproton** [comment]
> * pyLoad 0.5 is beta and not released yet.

I am aware. It is not so much meant as a complaint but more a bug report. Trying to help.

> * have you updated your installation to the latest develop branch?

I would not dare creating a bug without doing that first. :-) I have!

> * if so, please provide debug log

Will try to get the important parts out of the log... Not as easy as one might think.

> * since 0.5 is beta, not all of the plugins were migrated yet so this can cause this issue.

ACK.

**Comment by GammaC0de** [comment]
> It is not so much meant as a complaint but more a bug report. Trying to help.

 👍 Contribution is always welcome, we need it.

> Will try to get the important parts out of the log... Not as easy as one might think.

Please do so.

**Comment by RemiRigal** [comment]
I observe the same behavior with the Uptobox plugin on PyLoad v0.4.20 (linuxserver.io docker image with tag `latest`).

Nothing in the debug logs seems relevant to the issue apart from having this line for every download:
```
WARNING	HOSTER UptoboxCom[108]: Plugin may be unstable
```

If the download has been in the queue for less than ~30 minutes it usually starts successfully when the current downloads stop. If it has been queued for a longer period it hangs in the `starting` state indefinitely. The download restarts correctly when clicking on `Restart Link` however.

**Comment by foorschtbar** [comment]
Same problem here with FileStore Plugin (the only is tested). Downloads are limited to two files parallel. The first files from the queue are moves to status `downloading` and download work. After the first downloads finished a few hours later, next files from queue moved to status `starting` and stuck there until i click restart.

Latest Pyload Docker Version (0.4.20).

**Comment by djto** [comment]
At the tab `Config > Accounts` I did set `Max Parallel` for the stucking plugin smaller, than the setting `Maximum parallel downloads` in the tab `Config > General > Download`. I am still testing, but right now looks like solving the issue for me.

**Comment by GammaC0de** [comment]
@djto 
Can you describe how to reproduce this issue?
Can you provide debug logs?

**Comment by bsmithio** [comment]
> At the tab `Config > Accounts` I did set `Max Parallel` for the stucking plugin smaller, than the setting `Maximum parallel downloads` in the tab `Config > General > Download`. I am still testing, but right now looks like solving the issue for me.

Thanks for this, this solved the problem. I set Max Parallel on Settings -> Accounts to 2. I then set Max parallel downloads setting at Settings -> General -> Download to 2 as well. Downloads don't hang on starting anymore.

**Comment by GammaC0de** [comment]
If you want me to test this issue I need to know how to reproduce it.

**Comment by bsmithio** [comment]
It happens for me if I add new packages to the queue. For example, say I have 1 package that is downloading. I then add another package. pyLoad will then start downloading links from the new package. Previous links that were in the original package that were queued then become stuck in a "starting" state and can only be started by clicking the restart button next to them or the package. If I keep adding new packages the process repeats. This is done with UpToBox links and an AllDebrid premium account. I'm using pyload 0.5.0. The solution above seems to work, no idea why, though.

**Comment by foorschtbar** [comment]
Not all download plugins had the option to set `Max Parallel`.

@GammaC0de does the description of @bsmithio  help you or should i put everything together for u to reproduce it?

**Comment by wisukind** [comment]
Hello,

Same problem with plugin OneFichier. And workaround from @djto also works for me to solve the issue. I am using premium account. 
@GammaC0de , if you want to test using a premium account you can use mine. I havn't changed the password since we last discussed on a different issue.

Thanks

**Comment by guidocioni** [comment]
Unfortunately this happens to me also with the DefaultPlugin, and I'm not doing anything special...just downloading file from a server (so plain https links without captcha, premium accounts or other things...). 

It seems this happens because the packages in the queue stay there quite a long time, but I cannot remember seeing this issue before if I'm being honest. 

The log doesn't show anything special.

**Comment by wisukind** [comment]
To me this problem arrived when migrating to the latest stable branch, as explained in #3283
With previous stable release, I never had this issue.

Note also that the workaround from @djto only partially fix the problem. From time to time, some downloads still get stucked in starting phase.

**Comment by guidocioni** [comment]
I'll try updating later, just realized I still am on `pyload-ng 0.5.0b2.dev9`

**Comment by GammaC0de** [comment]
Guys, please confirm fixed (currently only pyload-ng)

**Comment by GammaC0de** [comment]
@foorschtbar @guidocioni @bsmithio @djto please confirm fixed

**Comment by guidocioni** [comment]
> @foorschtbar @guidocioni @bsmithio @djto please confirm fixed

hey, I don't have some links to reproduce the issue right now. I'll let you know ASAP

**Comment by foorschtbar** [comment]
> hey, I don't have some links to reproduce the issue right now. I'll let you know ASAP

Same here

**Comment by foorschtbar** [comment]
Mhmm, i now switched from pyload to pyload-ng (lscr.io/linuxserver/pyload-ng:arm32v7-latest). Info shows 0.5.0, i see the same problems:

![grafik](https://user-images.githubusercontent.com/10727275/159679196-ff817e53-d124-4ff3-a3aa-76f92494092e.png)

**Comment by GammaC0de** [comment]
@foorschtbar you should use http://lscr.io/linuxserver/pyload-ng:arm32v7-develop

**Comment by GammaC0de** [comment]
Any news about this?

**Comment by GammaC0de** [comment]
Send links to nitzo2001 at yahoo dot com, thanks.

Has anyone else have issues?

**Comment by foorschtbar** [comment]
Last downloads had no problems. let me check it for a few more days.

**Comment by GammaC0de** [comment]
So, is the a definitive answer?

**Comment by foorschtbar** [comment]
No, it doesn't work. i send u an mail yesterday.

**Comment by GammaC0de** [comment]
Hi,
I'm afraid I get "Leider sind aktuell keine freien Downloadslots für Freeuser verfügbar", so I cannot download.Do you have another set of URLs with another hoster?
Also, How do you add the URLs to pyload, ClickNLoad? or DLC? or manually add the package?
Regards

    On Wednesday, April 6, 2022, 11:10:53 AM GMT+3, Fab!an ***@***.***> wrote:  
 
 


No, it doesn't work. i send u an mail yesterday.
