### ISSUE TITLE
How to use API python script to return client.statusDownloads

### ISSUE THREAD

**Issue by SweetthD3ViL** [pyload/pyload#3926]
Hello all,

Wanted to use the python script from the wiki to get the client.statusDownloads in order for autosuspend (a project that monitor the activity of my server to suspend it if not in use) to suspend the server. 

However, my python knowledge are none existent. If I could get some pointers that would be great. 

Does it need to run as it's own .py file or does it need to be added to another file? 

For information, I run archlinux and pyload is installed using AUR pyload-git. 

Thank you for your time and I am looking forward to your replies.

**Comment by GammaC0de** [comment]
Which wiki page are you referring to?

**Comment by SweetthD3ViL** [comment]
Hi, thank you for your reply.

https://github.com/pyload/pyload/wiki/How-to-access-the-API

With this python code.
```

from module.remote.thriftbackend.ThriftClient import ThriftClient, WrongLogin

try:
    client = ThriftClient(host="127.0.0.1", port=7227, user="User", password="yourpw")
except:
    print "Login was wrong"
    exit()

print "Server version:", client.getServerVersion()
print client.statusDownloads()
q = client.getQueue()
for p in q:
  data = client.getPackageData(p.pid)
  print "Package Name: ", data.name
```

**Comment by SweetthD3ViL** [comment]
Hi,

In order to update the question, I wrote a bash script returning the serverstatus .active json to use with autosuspend

Below for references:

```
 #!/bin/bash

SessionID=$(curl -s "http://127.0.0.1:8000/api/login" -g -H "Host: 127.0.0.1:8000" -H "Content-Type: application/x-www-form-urlencoded" --data "username=MYUSER&password=MYPASSWORD" | jq -r)

SessionStatus=$(curl -s  "http://127.0.0.1:8000/api/statusServer" -g -H "Host: 127.0.0.1:8000" -H "Content-Type: application/x-www-form-urlencoded" --data "session=$SessionID" | jq -r '.active')

if [ $SessionStatus -eq 1 ]
then
        echo 0
else
        echo 1
fi

```

Thank you for your help and work on this project!

**Comment by GammaC0de** [comment]
```bash
#!/bin/bash

SessionID=$(curl -s "http://127.0.0.1:8000/api/login" -g -H "Host: 127.0.0.1:8000" -H "Content-Type: application/x-www-form-urlencoded" --data "username=MYUSER&password=MYPASSWORD" | jq -r)

ActiveDownloads=$(curl -s  "http://127.0.0.1:8000/api/statusServer" -g -H "Host: 127.0.0.1:8000" -H "Content-Type: application/x-www-form-urlencoded" --data "session=$SessionID" | jq -r '.active')

if [ $ActiveDownloads -gt 0 ]
then
        echo 0
else
        echo 1
fi
```

This works fine (notice ActiveDownloads  can be any number grater than 0)

SO what you are asking is how to write this in python!?

**Comment by SweetthD3ViL** [comment]
Hi,

Thank you for you reply. No I don't need to write it in python. I used the above script to access json serverstatus and just posted there for reference if anyone needs it. 

So the JSON .active argument from serverStatus could return anything greater than 0 is interesting. From test it's either 0 or 1 (active or not active)

**Comment by GammaC0de** [comment]
OK, closing then.
