### ISSUE TITLE
ExternalScripts: when there is a "sleep" in download_preparing script, the files are downloading twice in MEGA

### ISSUE THREAD

**Issue by koroki** [pyload/pyload#3933]
### Description

I prepare an script to connect with a VPN when some download is prepared. I used a bash script with a while and sleep that finished when the vpn conection is correct.
All is working properly but when the download is finished, it restart again with "download_preparing" script.

### Debug log

```

```

**Comment by GammaC0de** [comment]
@koroki Please test.
