### ISSUE TITLE
GetRealdebridtoken.py not working anymore?

### ISSUE THREAD

**Issue by CelloDE** [pyload/pyload#3936]
I'm having trouble adding my Real-Debrid to pyload. I was able to get the username and password in the past with GetRealdebridtoken.py, but now it's not working anymore. After entering the code in real-debrid.com/device to authorize the request cmd.exe just closes without giving me the username & password.

**Comment by GammaC0de** [comment]
Works fine for me.
This is what I used: https://github.com/pyload/pyload/files/4406037/GetRealdebridToken.zip

**Comment by CelloDE** [comment]
I tried it again and apparently its working, but the username and password are only shown for a fraction of a second before the window closes.

**Comment by GammaC0de** [comment]
You should run GetRealdebridtoken.py from within an open cmd.exe window
