### ISSUE TITLE
Rapidu.net doesn't work since few days

### ISSUE THREAD

**Issue by QBANIN** [pyload/pyload#3937]
Hi. Rapidu.net plugin doesn't work anymore. All added links becomes offline immediately.

**Comment by GammaC0de** [comment]
sample URL please.

**Comment by QBANIN** [comment]
> sample URL please.

https://rapidu.net/421008745968104/Within-Temptation-Resist-2019-FLAC.rar

**Comment by GammaC0de** [comment]
>> sample URL please.

> https://rapidu.net/421008745968104/Within-Temptation-Resist-2019-FLAC.rar

"We are sorry but this file has probably been deleted from our servers"

**Comment by QBANIN** [comment]
> > > sample URL please.
> 
> > https://rapidu.net/421008745968104/Within-Temptation-Resist-2019-FLAC.rar
> 
> "We are sorry but this file has probably been deleted from our servers"

Nope. I just downded it with JDownloader.

**Comment by GammaC0de** [comment]
![image](https://user-images.githubusercontent.com/11036551/115970984-a2a9c800-a54e-11eb-9e13-bb1553f75c33.png)

**Comment by QBANIN** [comment]
I have premium account that works in pyLoad as premium but the state is not recognized properly 
![pyload](https://user-images.githubusercontent.com/487657/115971028-80ac4780-a546-11eb-9d3f-72d4d11ad3f2.png)

**Comment by GammaC0de** [comment]
> have premium account that works in pyLoad as premium but the state is not recognized properly

OK, but first I need a a URL that works, please verify that it loads in your browser.

**Comment by QBANIN** [comment]
> > have premium account that works in pyLoad as premium but the state is not recognized properly
> 
> OK, but first I need a a URL that works, please verify that it loads in your browser.

Check this one  https://rapidu.net/721008431507903/Star.Trek-The.Original.Series..S01E29.PL.BluRay.720p.x264-LTN-darkw.pl.mkv

**Comment by GammaC0de** [comment]
:confused: This is weird, does it works for you in your browser?!
I get the same result :(
May be there is some kind of geo-location restriction?

**Comment by QBANIN** [comment]
> 😕 This is weird, does it works for you in your browser?!
> I get the same result :(
> May be there is some kind of geo-location restriction?

Yes, it does work in my browser (and JDownloader), but it doesn't work from my pyLoad instance. Both share the same WAN IP address.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by QBANIN** [comment]
> nitzo2001

Check your email.

**Comment by GammaC0de** [comment]
Plugin updated, please test.

**Comment by QBANIN** [comment]
> Plugin updated, please test.

Downloaded new plugin but the problem still remains. Every download link is recognized as offline.

**Comment by GammaC0de** [comment]
Please change the password back

**Comment by QBANIN** [comment]
> Please change the password back

Done.

**Comment by GammaC0de** [comment]
For me, the above link works

Please provide debug log.

**Comment by QBANIN** [comment]
> For me, the above link works
> 
> Please provide debug log.

`25.04.2021 23:02:13 INFO      ADDON UpdateManager: pyLoad is up to date!
25.04.2021 23:02:13 INFO      ADDON UpdateManager: All plugins are up to date!
25.04.2021 23:02:19 INFO      Download starts: 9810097853
25.04.2021 23:02:19 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
25.04.2021 23:02:19 WARNING   HOSTER RapiduNet[2]: Plugin may be unstable
25.04.2021 23:02:19 INFO      ACCOUNT RapiduNet: Grabbing account info for user `qba*******`...
25.04.2021 23:02:19 INFO      HOSTER RapiduNet[2]: Grabbing link info...
25.04.2021 23:02:19 INFO      HOSTER RapiduNet[2]: Link name: Seven.Psychopaths.2012.MULTi.1080p.BluRay.x264.DTS.AC3-DENDA.part1.rar
25.04.2021 23:02:19 INFO      HOSTER RapiduNet[2]: Link size: 2.00 GiB (2147483648 bytes)
25.04.2021 23:02:19 INFO      HOSTER RapiduNet[2]: Link status: online
25.04.2021 23:02:19 INFO      HOSTER RapiduNet[2]: Processing url: https://rapidu.net/981009785352147/Seven.Psychopaths.2012.MULTi.1080p.BluRay.x264.DTS.AC3-DENDA.part1.rar
25.04.2021 23:02:19 INFO      HOSTER RapiduNet[2]: Looking for direct download link...
25.04.2021 23:02:19 INFO      HOSTER RapiduNet[2]: Direct download link not found
25.04.2021 23:02:19 INFO      HOSTER RapiduNet[2]: Checking for link errors...
25.04.2021 23:02:19 INFO      HOSTER RapiduNet[2]: No errors found
25.04.2021 23:02:19 INFO      HOSTER RapiduNet[2]: Processing as premium download...
25.04.2021 23:02:20 INFO      HOSTER RapiduNet[2]: Downloading file...
25.04.2021 23:02:20 ERROR     HOSTER RapiduNet[2]:
25.04.2021 23:02:20 WARNING   HOSTER RapiduNet[2]: Premium download failed | IOError 13
25.04.2021 23:02:20 WARNING   Download failed: Seven.Psychopaths.2012.MULTi.1080p.BluRay.x264.DTS.AC3-DENDA.part1.rar | IOError 13
25.04.2021 23:02:20 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: Seven.Psychopaths.2012.MULTi.1080p.BluRay.x264.DTS.AC3-DENDA.part1.rar (pid:2)
25.04.2021 23:02:20 INFO      ADDON UnSkipOnFail: No duplicates found`

**Comment by GammaC0de** [comment]
IOError 13 is Permission denied..
Please check your download folder permissions

**Comment by QBANIN** [comment]
> IOError 13 is Permission denied..
> Please check your download folder permissions

It is fine. Just after this I added different set of DL links and they work fine.

**Comment by QBANIN** [comment]
You were right, problem solved. Thank you.
