### ISSUE TITLE
Error 404 in Files Tab

### ISSUE THREAD

**Issue by aronjanosch** [pyload/pyload#3954]
### Description

When selecting a downloaded file under the Files Tab an Error 404 is thrown. Tested this under Mac and Linux(RPi).
### Debug log

```
[2021-05-06 23:56:02]  DEBUG         pyload.webui  Error 404 - Requested URL: http://localhost:8000/files/get/HC/asd.audio.webm
127.0.0.1 - - [06/May/2021 23:56:02] "GET /files/get/HC/asd.audio.webm HTTP/1.1" 404 -
```

### Screenshots

![image](https://user-images.githubusercontent.com/20959518/117371155-b1d23380-aec7-11eb-8e6c-813d41c6ca5c.png)

**Comment by GammaC0de** [comment]
Thanks.
