### ISSUE TITLE
[XDCC] ARNING	Download failed: irc | 'int' object has no attribute 'strip'

### ISSUE THREAD

**Issue by tupertinois** [pyload/pyload#3956]
### Description
Hello,

I've recently updated pyload from 0.49 to 0.4.20

The XDCC plugin is not worjing as it used to be

When I use the following link
xdcc://servername:port/#channel/notname/#package number

(example: xdcc://irc.rizon.net:6667/#subsplease/CR-HOLLAND\|NEW/#15398)

I get the following warning in the log

WARNING | HOSTER XDCC[7517]: Plugin may be unstable

INFO | HOSTER XDCC[7517]: Grabbing link info...
INFO | HOSTER XDCC[7517]: Link name: irc
INFO | HOSTER XDCC[7517]: Link size: N/D
INFO | HOSTER XDCC[7517]: Link status: démarrage
INFO | HOSTER XDCC[7517]: Processing url: xdcc://irc.rizon.net:6667/#subsplease/CR-HOLLAND\|NEW/#15398
WARNING | Download failed: irc \| 'int' object has no attribute 'strip'
INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: irc (pid:836)
INFO | ADDON UnSkipOnFail: No duplicates found

And tht download does not run

Do you have any tips ? or info about this issue ?

Thanks in advance

**Comment by GammaC0de** [comment]
- Stop pyLoad
- Go to `http://<PYLOAD_IP>/info` and write down the value of `Config Folder`.
- Go to `<Config Folder>` and delete the `userplugins` folder
- Start pyLoad

If that does not help then:
- Enable debug mode
- Try a XDCC download
- Post the debug log here

**Comment by tupertinois** [comment]
It works again!

Thanks a lot for your quick answer
