### ISSUE TITLE
User Permissions not working

### ISSUE THREAD

**Issue by aronjanosch** [pyload/pyload#3957]
### Description

When creating a new Account, that is not an admin, you cannot access anything. 
Setting permissions doesn't change the outcome. 
I've selected all permissions, and I still only get the "Forbidden" Page.

If you enable admin you can access the webgui normally.

### Debug log

```

```

### Screenshots

![Screenshot_2021-05-10_17-36-01](https://user-images.githubusercontent.com/20959518/117685569-58635080-b1b6-11eb-9f95-cbe2fe5d62fc.png)
![Screenshot_2021-05-10_17-36-54](https://user-images.githubusercontent.com/20959518/117685586-5a2d1400-b1b6-11eb-9a71-cb58dae434c4.png)

**Comment by dausruddin** [comment]
Hi. Will there be a new release with this fix soon?
