### ISSUE TITLE
Nitroflare uses a new TLD

### ISSUE THREAD

**Issue by JoshuaParker001** [pyload/pyload#3959]
So Nitroflare uses the new TLD nitro.download instead of nitroflare.com
Can you please change the plugin?

**Comment by GammaC0de** [comment]
Sample URL please

**Comment by vuolter** [comment]
Looking on discord I found this: https://nitroflare.com/view/91B3AD7786D91D6/Totally_Free_Will_By_Mark_Chandaue.pdf

**Comment by JoshuaParker001** [comment]
Here is a sample URL:
https://nitro.download/view/1D9B292F73F58A1/mother.earth.news.june.july.2021.pdf

**Comment by GammaC0de** [comment]
> Here is a sample URL:
https://nitro.download/view/1D9B292F73F58A1/mother.earth.news.june.july.2021.pdf

This file is available with Premium only.

**Comment by JoshuaParker001** [comment]
Oh sorry didnt see that.
Try this:
https://nitro.download/view/1160519A6E6F4C4/test.pdf

**Comment by GammaC0de** [comment]
fixed.
