### ISSUE TITLE
activate discussions for the repositories

### ISSUE THREAD

**Issue by bozzfozz** [pyload/pyload#3962]
hey, why don't you activate discussions for the repositories, it's better to give help or suggest new features instead of creating issues for each time

**Comment by vuolter** [comment]
Maybe it's not a bad idea after all, @GammaC0de what do you think about this?

**Comment by GammaC0de** [comment]
I'm not familiar with github discussions, is it something like gitter?

**Comment by vuolter** [comment]
Not so, it's a "relatively" new feature github added some time ago, a really nice example is https://github.com/vercel/next.js/discussions

Maybe we could use this to avoid all the "question" issues here.

**Comment by GammaC0de** [comment]
Discussions are now active.
