### ISSUE TITLE
Linksnappy.com doesnt show progress for files?

### ISSUE THREAD

**Issue by kjboa** [pyload/pyload#3964]
Hi, i was thinking about migrating from jdownloader to pyload mainly because its open source and has a beautiful web interface.
I have one question though: Whenever i download files via my linksnappy premium it says the file has 0b and thus no progress is shown although the file is clearly being downloaded. Is this a software limitation or is there a workaround?

**Comment by GammaC0de** [comment]
Which pyLoad version are we talking about? (you can check if you browse to http://ip:8000/info)

**Comment by kjboa** [comment]
I'm very sorry i didn't check all the options before writing this issue. I just had to go to home and the progress was visible. Man i feel dumb. Thanks for the quick answer though.
