### ISSUE TITLE
File hoster filefox.cc

### ISSUE THREAD

**Issue by jimmybrigs** [pyload/pyload#3965]
Hello,

First thanks for pyload; its an amazing little program. 

So I have been having issues with filefox.cc; the links used to work with the baseplugin until they switched to hcaptcha. In all my brilliance I thought it would be easy enough to just copy the old filejoker plugin and modify that to fit but that didn't work, and then I tried following the guide in the wiki but being that I know nothing about python that didn't work either. 

Would it be possible to get a hoster plugin for filefox.cc? The download links generally look like "https://filefox.cc/<random string>", where random string is would be a unique string for the file consisting of alphanumeric characters of varying lengths.

**Comment by vuolter** [comment]
You're welcome 😄 
We need a sample url (to a download), to start looking at this.
If you can, please provide us with one. Thanks.

**Comment by jimmybrigs** [comment]
Sorry I just saw that you responded! I shot you an email (hopefully thats ok - the gmail in your profile) with a link. Hopefully it doesn't end up in your spam. Let me know if you need anything else, I'll pay more attention to my github notifications haha. Thank you for looking into this!
