### ISSUE TITLE
Having issue downloading torrent magnet links

### ISSUE THREAD

**Issue by anandisrocking007** [pyload/pyload#3967]
### Description

Hello sir i am using raspberry pi zero installed with Raspberry OS Lite i am having trouble downloading torrent in pyload i tried to use a magnet link and the following error message cam out in the log
I hope you can help we solve this issue and also how can i download from .torrent file.

### Debug log

27.05.2021 07:18:19 | INFO | Added package test tor containing 1 links
-- | -- | --
154 | 27.05.2021 07:18:20 | INFO | Decrypting starts: magnet:?xt=urn:btih:D251669A585A4AB3147ED40FAF65E7CF674F7755&amp;dn=Justice+League%3A+Crisis+on+Two+Earths+%282010%29+%5B720p%5D+%5BYTS.MX%5D&amp;tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&amp;tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337&amp;tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337
155 | 27.05.2021 07:18:20 | WARNING | CONTAINER TORRENT[2]: Plugin may be unstable
156 | 27.05.2021 07:18:20 | INFO | CONTAINER TORRENT[2]: Grabbing link info...
157 | 27.05.2021 07:18:20 | INFO | CONTAINER TORRENT[2]: Link name: urnbtihD251669A585A4AB3147ED40FAF65E7CF674F7755
158 | 27.05.2021 07:18:20 | INFO | CONTAINER TORRENT[2]: Link size: N/D
159 | 27.05.2021 07:18:20 | INFO | CONTAINER TORRENT[2]: Link status: starting
160 | 27.05.2021 07:18:20 | INFO | CONTAINER TORRENT[2]: Processing url: magnet:?xt=urn:btih:D251669A585A4AB3147ED40FAF65E7CF674F7755&amp;dn=Justice+League%3A+Crisis+on+Two+Earths+%282010%29+%5B720p%5D+%5BYTS.MX%5D&amp;tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&amp;tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337&amp;tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337
161 | 27.05.2021 07:18:20 | ERROR | CONTAINER TORRENT[2]: No plugin is associated with torrents / magnets \| Please go to plugin settings -&gt; TORRENT and select your preferred plugin
162 | 27.05.2021 07:18:20 | ERROR | Decrypting failed: urnbtihD251669A585A4AB3147ED40FAF65E7CF674F7755 \| No plugin is associated with torrents / magnets

**Comment by GammaC0de** [comment]
First of all, please refresh your pyLoad installation using the instruction in #3283.
Then you have to go to settings -> plugins -> TORRENT and select the plugin to use for torrents.
Then retry.

To use .torrent file, you select the file to "upload a container" of the "add package" dialog.
