### ISSUE TITLE
Permissions settings better explanation?

### ISSUE THREAD

**Issue by zax-ftw** [pyload/pyload#3968]
1. **Groupname** - obvious
2. **Change Group and User of Downloads** - toggles 'Username' and 'Groupname' settings, sets owner of downloaded files AND folders
3. **Change file mode of downloads** - toggles just the 5th setting or also 7th?
4. **Username** - obvious
5. **Filemode for Downloads** - sets filemode just for downloaded files or also folders (packages)?
6. **Change group of running process** - no idea
7. **Folder Permission mode** - which folder, the main 'pyLoad' one or subfolders (packages)?
8. **Change user of running process** - no idea

**Comment by GammaC0de** [comment]
if 2 is true:
- chown  `<value_of_4>`:`<value_of_1>` package_folder
- chown  `<value_of_4>`:`<value_of_1>` downloaded_file

if 3 is true:
- chmod `<value_of_7>` package_folder
- chmod `<value_of_5>` downloaded_file

if 6 is true:
- setgid `<value_of_1>`

if 8 is true:
- setuid `<value_of_4>`

If you can phrase it better, I'm open for suggestions..

**Comment by zax-ftw** [comment]
> If you can phrase it better, I'm open for suggestions...

```
1. Change ownership of downloads: [on/off]
2. User [...]
3. Group [...]
4. Change permissions of downloads: [on/off]
5. Files [...]
6. Folders [...]
7. Change group of running process: [on/off]
8. Change user of running process: [on/off]
```
Perhaps something like this would be clearer?

**Comment by GammaC0de** [comment]
Done
