### ISSUE TITLE
unsupported locale setting via xfs_account.py

### ISSUE THREAD

**Issue by fooness** [pyload/pyload#3973]
### Description
I am running `pyload-ng` on Raspberry Pi OS, installed via: https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi) … After adding an account for DdownloadCom, I was not able to log in due to locales issues, it seems?

### Debug log
```
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  INFO                pyload  ACCOUNT DdownloadCom: Adding user `**********`...
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  DEBUG               pyload  ACCOUNT DdownloadCom: Reached login timeout for user `*******`
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  INFO                pyload  ACCOUNT DdownloadCom: Login user `*******`...
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  DEBUG               pyload  ACCOUNT DdownloadCom: LOAD URL http://www.ddownload.com/login.html | get={} | post={} | ref=True | cookies=True | just_he
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  DEBUG               pyload  ACCOUNT DdownloadCom: LOAD URL https://ddownload.com/ | get={} | post={'op': 'login', 'token': 'XXXXXXXXXXXXXXXXXXXXXXXXX
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  INFO                pyload  ACCOUNT DdownloadCom: Checking for link errors...
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  INFO                pyload  ACCOUNT DdownloadCom: No errors found
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  INFO                pyload  ACCOUNT DdownloadCom: Grabbing account info for user `*******`...
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  DEBUG               pyload  ACCOUNT DdownloadCom: LOAD URL http://www.ddownload.com/ | get={'op': 'my_account'} | post={} | ref=True | cookies=True |
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  DEBUG               pyload  ACCOUNT DdownloadCom: Expire date: XX XXX XXXX
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  ERROR               pyload  ACCOUNT DdownloadCom: unsupported locale setting
Jun 12 15:07:54 raspberry pyload[1410]: Traceback (most recent call last):
Jun 12 15:07:54 raspberry pyload[1410]:   File "/usr/local/lib/python3.7/dist-packages/pyload/plugins/base/xfs_account.py", line 101, in grab_info
Jun 12 15:07:54 raspberry pyload[1410]:     locale.setlocale(locale.LC_TIME, "en_US")
Jun 12 15:07:54 raspberry pyload[1410]:   File "/usr/lib/python3.7/locale.py", line 604, in setlocale
Jun 12 15:07:54 raspberry pyload[1410]:     return _setlocale(category, locale)
Jun 12 15:07:54 raspberry pyload[1410]: locale.Error: unsupported locale setting
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  DEBUG               pyload  ACCOUNT DdownloadCom: Size: XXXXX | Unit: MB
Jun 12 15:07:54 raspberry pyload[1410]: [2021-06-12 15:07:54]  DEBUG               pyload  ACCOUNT DdownloadCom: LEECH TRAFFIC PATTERN not found
```

### Additional references
This line seems to be the problem(?) …

https://github.com/pyload/pyload/blob/develop/src/pyload/plugins/base/xfs_account.py#L101

When changing `en_US` to `en_US.UTF-8` here, then it worked for me.

Maybe it should, by default, be changed to something like `C` to circumvent such errors?

**Comment by GammaC0de** [comment]
Do you have a en_US listed in locale -a? If not you must [install](https://ubuntuforums.org/showthread.php?t=196414) it.

**Comment by fooness** [comment]
> Do you have a en_US listed in locale -a? If not you must [install](https://ubuntuforums.org/showthread.php?t=196414) it.

No, I don’t. Why is it hardcoded to be `en_US`? I don’t think that **everyone** has that locale installed by default.

```
$ locale -e
C
C.UTF-8
POSIX
en_US.utf8
```

**Comment by GammaC0de** [comment]
OK, I have changed it  to `en_US.utf8`.
Please confirm it works.

https://github.com/pyload/pyload/blob/develop/src/pyload/plugins/base/xfs_account.py#L101 was 
added to fix #3973 because time.strptime() uses the current locale to parse time.

**Comment by fooness** [comment]
> OK, I have changed it to `en_US.UTF-8`.
> Please confirm it works.

Thank you very much. **Confirming this works for me.** ✔️

PS, just in case this will become necessary: I fear, though, that maybe might break things and introduce similar issues for other users without the `en_US.UTF-8` locale? **I might be wrong**, but I think to have read that `C` and `POSIX` are enabled by default on very most systems.

**Comment by GammaC0de** [comment]
> but I think to have read that C and POSIX are enabled by default on very most systems.

I'm really not a locale expert, I do know that we need English time parsing with time.strptime().
