### ISSUE TITLE
Anti-captcha support

### ISSUE THREAD

**Issue by Mte90** [pyload/pyload#3989]
### Description
I am using https://anti-captcha.com/ service in other tools but this service doesn't integrate it
I see that this tool integrates with other service for captcha resolving, it is possible to add this one?

**Comment by GammaC0de** [comment]
It may be possible but I would need an API key for testing.
Please  API key to nitzo2001 at yahoo dot com.

**Comment by Mte90** [comment]
Key sent :-)

**Comment by GammaC0de** [comment]
OK,
The plugin seems to be finished, but:
I need a favor from you:
In order to register pyLoad  at the anti-captcha.com's App Center, they ask me to send 1$.
I tried to buy 1$ credit but I could not succeed: via PayPal the minimum is 10$ :(
I also tried buying a coupon without success either :(

Can you please an email with a 1$ coupon code for anti-captcha.com so I can register  pyLoad?
I would really appreciate that.

**Comment by Mte90** [comment]
Strange that require to register an app. I am using with that https://github.com/packt-cli/Packt-Publishing-Free-Learning that just require to me the key and doesn't have the app registered.
I cannot generate a coupon but I can open a ticket for the app to not use the coupon. I guess that will be free in the portal so I don't understand why they asks to pay for it.

**Comment by GammaC0de** [comment]
OK, I successfully submitted pyLoad for review, 
Now the status is "under review", 
I'll update when I get an answer.

**Comment by GammaC0de** [comment]
App approved.

**Comment by Mte90** [comment]
Thanks! there are any plans for a new release or in the meantime I can install with pip using the latest commits?

**Comment by GammaC0de** [comment]
See https://github.com/pyload/pyload/discussions/3986#discussioncomment-874799.

**Comment by Mte90** [comment]
Thanks I checked and I am using the debian package so I have to see the difference with pip package.

**Comment by Mte90** [comment]
I got:
```
1129 | 2021-07-01 15:14:41 | DEBUG | pyload | ANTICAPTCHA TurbobitNet[1]: ReCaptcha \| 73ffc805-d031-4a4a-90af-f9481e72d996 \| Wrong key format, this probably because it is not a reCAPTCHA key
-- | -- | -- | -- | --
1130 | 2021-07-01 15:14:41 | WARNING | pyload | ANTICAPTCHA TurbobitNet[1]: ReCaptcha \| Key pattern not found
```

**Comment by GammaC0de** [comment]
Those are normal messages.

**Comment by Mte90** [comment]
I see tonight tried again and worked.
