### ISSUE TITLE
Rapidgator.net over AlldebridCom - Downloaded content was smaller than expected

### ISSUE THREAD

**Issue by godfuture** [pyload/pyload#3995]
### Description

<html><body>

Download with rapidgator.net over AlldebridCom starts, but stops after certain time. When restarting the failed download, progress continues where ended, but finally getting many crc in archive extract. Currently downloading with max 3 connections, but this issue also happens with only one connection at a time.

Edit: this happened also to ddl.

</body>
</html>

### Debug log

```
328 | 25.07.2021 02:10:36 | INFO | HOSTER AlldebridCom[842]: AlldebridCom \| Downloading file...
-- | -- | -- | --
329 | 25.07.2021 02:11:37 | WARNING | Download failed: SLMT09f11.part4.rar \| Downloaded content was smaller than expected. Try to reduce download connections.
330 | 25.07.2021 02:11:37 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: SLMT09f11.part4.rar (pid:147)
331 | 25.07.2021 02:11:37 | INFO | ADDON UnSkipOnFail: No duplicates found
```

**Comment by godfuture** [comment]
I think this is a problem of AlldebridCom. Closing this issue.

**Comment by GammaC0de** [comment]
> I think this is a problem of AlldebridCom

How did you find that?

**Comment by SweetthD3ViL** [comment]
Hello, 

I am having the same issue, have you found a solution?

**Comment by godfuture** [comment]
I have tried to download the package with alldebrid downloader and even there the package did not finish downloaded over their link and by browser. So I guess I need to get in contact with them. This is at least my conclusion.

**Comment by GammaC0de** [comment]
@godfuture  Thanks for confirming.
What I have found is that the server responses with "Rate Limit"

**Comment by SweetthD3ViL** [comment]
Right, thank you for your responses.

I had the issue this morning with two packages again. However, everytime it happens I used alldebrid website to generate a link then use wget to download the file from my server without any issues.

I shall try to use payload to download the alldebrid generated link next time and report.

**Comment by GammaC0de** [comment]
Maybe @Alldebrid can shed some light on this..

**Comment by GammaC0de** [comment]
OK, fixed 🎉
