### ISSUE TITLE
webshare.cz VIP not working

### ISSUE THREAD

**Issue by xDereCx** [pyload/pyload#3996]
webshare vip not working, under settings -> accounts still showing not valid. using latest ng develop branch
log : https://pastebin.com/aHtqPjD5

if you need VIP account for testing email me

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by Sparh4wk** [comment]
seems like this is still not fixed?

**Comment by GammaC0de** [comment]
@Sparh4wk It was working in the past, if not please open a new issue.
