### ISSUE TITLE
Cant add account for MEGA.NZ (the account has 2FA enabled)

### ISSUE THREAD

**Issue by h1ghju1ce** [pyload/pyload#4007]
### Description

---------------------------------------------
Python Version:3.8.5 [GCC 4.9.2]
OS Platform:  posix linux Linux QNAP 4.14.24-qnap
pyLoad  Version:0.5.0
---------------------------------------------

Trying to add an account for MEGA.NZ, but when trying to add it, it gives a red ERROR banner
my account has 2FA enabled (6 digit code generated by an app on my phone)
I assume thats the issue

(the QNAP install was done via a QPKG from: https://qnapclub.eu/en/qpkg/1132 

### Debug log

2021-08-20 15:39:47	ERROR	pyload	Error importing MegaCoNz: No module named 'Cryptodome'
440	?	?	?	Traceback (most recent call last):
441	?	?	?	  File "/share/CACHEDEV1_DATA/.qpkg/PyloadNG/pyload/core/managers/plugin_manager.py", line 345, in load_module
442	?	?	?	    module = __import__(
443	?	?	?	  File "/share/CACHEDEV1_DATA/.qpkg/PyloadNG/pyload/plugins/accounts/MegaCoNz.py", line 3, in <module>
444	?	?	?	    import Cryptodome.PublicKey.RSA
445	?	?	?	ModuleNotFoundError: No module named 'Cryptodome'
446	2021-08-20 15:39:47	DEBUG	pyload.webui	'NoneType' object has no attribute 'update_accounts'
447	?	?	?	Traceback (most recent call last):
448	?	?	?	  File "/share/CACHEDEV1_DATA/.qpkg/PyloadNG/flask/app.py", line 1950, in full_dispatch_request
449	?	?	?	    rv = self.dispatch_request()
450	?	?	?	  File "/share/CACHEDEV1_DATA/.qpkg/PyloadNG/flask/app.py", line 1936, in dispatch_request
451	?	?	?	    return self.view_functions[rule.endpoint](**req.view_args)
452	?	?	?	  File "/share/CACHEDEV1_DATA/.qpkg/PyloadNG/pyload/webui/app/helpers.py", line 182, in wrapper
453	?	?	?	    response = func(*args, **kwargs)
454	?	?	?	  File "/share/CACHEDEV1_DATA/.qpkg/PyloadNG/pyload/webui/app/blueprints/json_blueprint.py", line 289, in add_account
455	?	?	?	    api.update_account(type, login, password)
456	?	?	?	  File "/share/CACHEDEV1_DATA/.qpkg/PyloadNG/pyload/core/api/__init__.py", line 80, in wrapper
457	?	?	?	    return func(self, *args, **kwargs)
458	?	?	?	  File "/share/CACHEDEV1_DATA/.qpkg/PyloadNG/pyload/core/api/__init__.py", line 1187, in update_account
459	?	?	?	    self.pyload.account_manager.update_account(plugin, account, password, options)
460	?	?	?	  File "/share/CACHEDEV1_DATA/.qpkg/PyloadNG/pyload/core/utils/struct/lock.py", line 22, in wrapped
461	?	?	?	    return func(self, *args, **kwargs)
462	?	?	?	  File "/share/CACHEDEV1_DATA/.qpkg/PyloadNG/pyload/core/managers/account_manager.py", line 169, in update_account
463	?	?	?	    updated = p.update_accounts(user, password, options)
464	?	?	?	AttributeError: 'NoneType' object has no attribute 'update_accounts'

### Screenshots

I dont know if the not found module "Cryptodome" is a red herring , or the key to getting  it working
I could install it with "pip install pycryptodome" if needed

**Comment by OzzieIsaacs** [comment]
Pychrotodome is no red herring, you Need it. then we see what else isn‘t working

**Comment by h1ghju1ce** [comment]
add the module via pip , but error message still appeared

I think its todo with how the apps are sandboxed, I've contacted the author of the package

will update once I get that module working

**Comment by GammaC0de** [comment]
1. 2FA is not supported.
2. The QPKG seems to be outdated (Cryptodome is not imported anymore by MegaCoNz)

**Comment by h1ghju1ce** [comment]
I tried updating the files from this GIT ontop of the ones in the QPKG install folder, but then it just complained that it was missing cookiejar (damm it)

I tried adding that, but it just seem to brake the app , and wouldnt start the server

so I havent been able to test the suggestion above I'm afraid

I contacted the maintainer of the QPKG , and he said he'll look at updating it with the latest files soon
I'll just have to wait I think

**Comment by GammaC0de** [comment]
> I'll just have to wait I think

Or you can try going the Entware path.
