### ISSUE TITLE
Pyload Fails To Download Multiple Files In One Package From Rapidgator

### ISSUE THREAD

**Issue by ajayvarghese2000** [pyload/pyload#4008]
### Description

When trying to download a zip-file that is split into multiple links with a .001 ... 00X extension. Pyload only downloads the first file and then errors out the subsequent links in that package. However, when trying to download the links individually, pyload has no problem. Even when trying to restart the package after the firs one is complete it still errors out and does not start.

Only tested with Rapidgator and Youtube, youtube seems to work fine with multiple files however I assume the people is something to do with the files having the same name until the extension and not the plugins/hosters fault 

### Debug log

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyload/core/threads/download_thread.py", line 56, in run
    pyfile.plugin.preprocessing(self)
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/hoster.py", line 300, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/downloader.py", line 104, in _process
    self.process(self.pyfile)
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/simple_downloader.py", line 311, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/downloader.py", line 316, in download
    self.check_duplicates()
  File "/usr/local/lib/python3.9/dist-packages/pyload/plugins/base/downloader.py", line 535, in check_duplicates
    dl_n = int(m.group(2) or "0")
AttributeError: 'NoneType' object has no attribute 'group'
```

### Screenshots

![image](https://user-images.githubusercontent.com/58085441/130262739-da540e11-a2f2-4e4b-9996-4970bc13e5a5.png)

The All 3 test is all 3 of the zip files together in one package, and as you can see it had no problem downloading the first one but, then failed the other two.

However, if the other two links are added individually, they download fine as seen in the "Rapidgator 2 Part" and "Rapidgator 3rd Part" folders.

Please let me know if you need any other info.

Thank You!

**Comment by GammaC0de** [comment]
Sample URL(s) please.

**Comment by ajayvarghese2000** [comment]
> Sample URL(s) please.

"https://rapidgator.net/file/9314c1d332bafff253bc0b5b6d9e4cc2/#cf4a0579b979226b40387e35a6cccaaa41686328.7z.001"
"https://rapidgator.net/file/ea43dd96eda8ec4bcc7f7a3d6c8bbd9f/#cf4a0579b979226b40387e35a6cccaaa41686328.7z.002"
"https://rapidgator.net/file/6bd37ec12ed34e5060b2131124d9747d/#cf4a0579b979226b40387e35a6cccaaa41686328.7z.003"

Try these?

**Comment by GammaC0de** [comment]
@ajayvarghese2000 Can you check now with https://github.com/pyload/pyload/commit/4bceb59d981d8f03883fd2ea0c028e19882ed130 included?

**Comment by ajayvarghese2000** [comment]
> @ajayvarghese2000 Can you check now with [4bceb59](https://github.com/pyload/pyload/commit/4bceb59d981d8f03883fd2ea0c028e19882ed130) included?

Yeah that seems to have fixed it, just tested it with a number of different package links and It all seems to be in working order.
