### ISSUE TITLE
Scope of "plugin policy" on pyload.net

### ISSUE THREAD

**Issue by seaofmars** [pyload/pyload#4011]
### Question
Hi. I see PyLoad's official website[0] (I presume) has a "plugin policy". What exactly does this policy apply to? Is it that I'm not allowed to write plugins for certain services at all, am I not allowed to host them on official instances, something else?

### Additional References
[0] https://pyload.net/

**Comment by vuolter** [comment]
Policies applies only for plugins hosted here and released within pyLoad as official plugins.
Ofc, you can use any plugin in respect of its license.
