### ISSUE TITLE
Unabel to run pyLoad on Debian stable

### ISSUE THREAD

**Issue by dirdi** [pyload/pyload#4012]
### Question

With the release of bullseye, it is no longer possible to run pyLoad on Debian stable: pyLoad 0.4.20 (stable) requires python-pycurl, which is no longer part of the distribution and pyLoad 0.5 (NG) has not reached a usable state, yet.

Are there other options to run pyLoad on Debian bullseye?
Maybe it would be possible to ship pycurl together with pyLoad, like jinja2?

**Comment by GammaC0de** [comment]
Two options:
1. Install pyload-ng:
```
sudo apt install python3-pycurl
pip install --upgrade git+https://github.com/pyload/pyload.git@develop
pyload
```

2. Manually install pyload-stable:
```
apt install python2 python2-dev libcurl4-gnutls-dev gnutls-dev
wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
python2 ./get-pip.py
rm -f ./get-pip.py
pip2 install pycurl pycrypto pyopenssl pillow
cd /opt
wget https://github.com/pyload/pyload/archive/refs/heads/stable.zip
unzip ./stable.zip
rm -f ./stable.zip
cd /opt/pyload-stable/
python2 ./pyLoadCore.py --configdir=/opt/pyload-stable/config
```

**Comment by dirdi** [comment]
@GammaC0de: Thanks, for your fast response! The first option worked for me, indeed. Previously, I tried to install pyload-ng following the [official guide](https://github.com/pyload/pyload/tree/develop), but this approach resulted in Segmentation faults, every time I tried to start a download.

**Comment by Kentin9** [comment]
hello @Earl0fPudding, 
Can you share more details ? i still have error exiting pip2 command.
i checked and i have the latest version of build-essential package/

pi@raspberrypi:/home $ sudo apt-get install build-essential
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
