### ISSUE TITLE
Account valid for 11 weeks but pyload says its valid until tomorrow

### ISSUE THREAD

**Issue by smschumacher** [pyload/pyload#4014]
Hi,

I am using Pyload-NG installed via PIP on a fresh installation of Debian 11, so I have version 0.50.0 I already have downloaded multiple files with my uploaded premium account. I just added another batch of links and now it it demanding that I solve captchas. My account -  I deleted and recreated it multiple times - is saying that it is only valid until today in the web interface - but according to uploaded.net it is valid until for another 11 weeks. The log is already 1,2 MB in size so please tell me what keywords I should be grepping for. 

Yours
Stefan

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by smschumacher** [comment]
I am sorry, It seems I am actually on Pyload-Next while Pyload with python 2.7 is Pyload-Stable. Of course I am not using that on Debian 11 anymore as it does not have all the requirements to run the old pyload anymore.

**Comment by smschumacher** [comment]
Is this a valid request? Could a member of the dev team comment on this?

**Comment by GammaC0de** [comment]
Go to `httpL//<pyload_ip>/info` and see which version of pyload and python you are running.

**Comment by smschumacher** [comment]
Why is this closed? Wouldn't sending you the logs be enough? You must understand that I am cautious to giving out my account. ?
Storage
Download Folder:/mnt/btrfs-raid/Downloads/Incoming/Available Space:8.47 TiB
System
Python Version:3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]OS Platform:posix linux Linux mars 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64
pyLoad
Version:0.5.0Installation Folder:/usr/local/lib/python3.9/dist-packages/pyloadConfig Folder:/root/.pyloadLanguage:en
WebUI
Port:8000Theme:pyplex (by GammaC0de based on work of Marco Fernandes and Dogan Bagci)

**Comment by GammaC0de** [comment]
> Why is this closed?

YOU closed it...


Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by smschumacher** [comment]
Hi
Username:9121329
Password:  uf9vnm

Thank you for your efforts.
Stefan



Am Di., 7. Sept. 2021 um 20:52 Uhr schrieb GammaC0de <
***@***.***>:

**Comment by GammaC0de** [comment]
DO NOT post sensitive information here...

**Comment by GammaC0de** [comment]
fixed.

**Comment by smschumacher** [comment]
Thank you. Which pip command will I have to issue to get the fixed version?

**Comment by GammaC0de** [comment]
> Which pip command will I have to issue to get the fixed version?

`pip install --upgrade git+https://github.com/pyload/pyload.git@develop`
