### ISSUE TITLE
[Plugin request] Hotlink.cc

### ISSUE THREAD

**Issue by Mte90** [pyload/pyload#4031]
### Description
As turbobit there is hotlink.cc that has a timeout before trying again.
The difference is to get the link there is no captcha, just a button to press, page reload with the link.
Also the timeout before download again with free plan is 24hours.

I don't know if it is the case to share link to that service here as often are copyrighted stuff.

**Comment by GammaC0de** [comment]
Sample URL please.

**Comment by Mte90** [comment]
A sample URL https://hotlink.cc/XMF7Q6K4D4S0/NightOfTheCreeps.zip.html

**Comment by Mte90** [comment]
Thanks!
I was worried that as there wasn't any reply the ticket was closed without the support, but anyway thanks!

**Comment by alpe12** [comment]
@GammaC0de Has this been added to pyload-ng? I use the docker image lscr.io/linuxserver/pyload:ng and there is no hotlink.cc support there.

**Comment by GammaC0de** [comment]
> @GammaC0de Has this been added to pyload-ng? I use the docker image lscr.io/linuxserver/pyload:ng and there is no hotlink.cc support there.


It's in the `develop` branch.
