### ISSUE TITLE
ExtractArchive: no files found to extract

### ISSUE THREAD

**Issue by lollysan** [pyload/pyload#4032]
### Description

Hi, I have an issue with the ExtractArchive plugin and multi part RAR archives. The plugin does not automatically extract the archive when the download is finished. The logs report that the plugin is checking the folder where the parts are, but it is not finding anything to extract. Thank you for your help!

### System Info

Platform: Raspberry Pi 3
OS: Raspbian Buster 
pyload-ng: 0.5.0 main

**Comment by GammaC0de** [comment]
Sample URL and debug logs please.

**Comment by lollysan** [comment]
Sorry, what do you mean with Sample URL?

Here is my log, line 1939 is checking the folder where the part1, part2, .... part15.rar files are: 

1919 | 2021-11-02 17:47:16 | INFO | pyload | Download finished: *******.part14.rar
1920 | 2021-11-02 17:47:16 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_finished`
1921 | 2021-11-02 17:48:09 | DEBUG | pyload | Chunk 1 download finished
1922 | 2021-11-02 17:48:09 | DEBUG | pyload | Chunk 3 download finished
1923 | 2021-11-02 17:48:09 | DEBUG | pyload | Chunk 2 download finished
1924 | 2021-11-02 17:48:30 | INFO | pyload | DOWNLOADER EasybytezCom[53]: File saved
1925 | 2021-11-02 17:48:30 | INFO | pyload | DOWNLOADER EasybytezCom[53]: Checking download...
1926 | 2021-11-02 17:48:30 | INFO | pyload | DOWNLOADER EasybytezCom[53]: File is OK
1927 | 2021-11-02 17:48:30 | INFO | pyload | DOWNLOADER EasybytezCom[53]: Checking file (with built-in rules)...
1928 | 2021-11-02 17:48:31 | INFO | pyload | DOWNLOADER EasybytezCom[53]: Checking file (with custom rules)...
1929 | 2021-11-02 17:48:31 | INFO | pyload | DOWNLOADER EasybytezCom[53]: Checking for link errors...
1930 | 2021-11-02 17:48:31 | INFO | pyload | DOWNLOADER EasybytezCom[53]: No errors found
1931 | 2021-11-02 17:48:31 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_processed`
1932 | 2021-11-02 17:48:31 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `package_processed`
1933 | 2021-11-02 17:48:31 | INFO | pyload | Download finished: *******.part15.rar
1934 | 2021-11-02 17:48:31 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_finished`
1935 | 2021-11-02 17:48:31 | INFO | pyload | Package finished: **********
1936 | 2021-11-02 17:48:31 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `package_finished`
1937 | 2021-11-02 17:48:31 | DEBUG | pyload | ADDON ExtractArchive: Use for extensions: .001\|.7z\|.bz2\|.bzip2\|.gz\|.gzip\|.lha\|.lzh\|.lzma\|.rar\|.tar\|.taz\|.tbz\|.tbz2\|.tgz\|.xar\|.xz\|.z\|.zip
1938 | 2021-11-02 17:48:31 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
1939 | 2021-11-02 17:48:31 | INFO | pyload | ADDON ExtractArchive: Check package: *********
1940 | 2021-11-02 17:48:31 | DEBUG | pyload | All downloads processed
1941 | 2021-11-02 17:48:31 | INFO | pyload | ADDON ExtractArchive: No files found to extract
1942 | 2021-11-02 17:48:31 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `all_downloads_finished`
1943 | 2021-11-02 17:48:31 | DEBUG | pyload | All downloads finished
1944 | 2021-11-02 17:48:31 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `all_archives_extracted`
1945 | 2021-11-02 17:48:31 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `all_archives_processed`

**Comment by GammaC0de** [comment]
> Sorry, what do you mean with Sample URL?

A URL(s) that failed to extract.

**Comment by lollysan** [comment]
Somehow I managed to fix it, it seems that the issue was tied to that specific archive. I downloaded other archives and the extraction worked correctly. Thank you anyway for your help.
