### ISSUE TITLE
Is pyload portable (usb-stick)?

### ISSUE THREAD

**Issue by DoS007** [pyload/pyload#4033]
### Question

Is pyload portable? It doesn't write files outsite of its directory, does it (only downloads as exception)?

**Comment by GammaC0de** [comment]
Which OS are you using?
If the answer is windows, I guess you can use https://github.com/pyload/pyload/releases/download/v0.4.20/pyload_0.4.20_win.zip

**Comment by DoS007** [comment]
@GammaC0de yes, it's windows. So the setup and the so installed program won't use %appdata%, the registry or anything other outside its directory e.g. for configuration (except the download folder)?

**Comment by GammaC0de** [comment]
Yes, everything (by default the download folder also) resides in in the `data` subdirectory.

**Comment by DoS007** [comment]
@GammaC0de Thank you :).
