### ISSUE TITLE
FshareVN login issue. "Bad server response: 403 Forbidden"

### ISSUE THREAD

**Issue by hieppo** [pyload/pyload#4036]
### Description

Issue with login in to FshareVM premium account. "Bad server response: 403 Forbidden", Could not login user 'jac*****' | Login handshare has failed.

### Debug log

```
[log.txt](https://github.com/pyload/pyload/files/7513454/log.txt)
```

### Additional references

<!-- WRITE HERE - OPTIONAL --

>

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.
