### ISSUE TITLE
rapidu.net not working

### ISSUE THREAD

**Issue by skwaruch** [pyload/pyload#4043]
### Description
I'm not able to download any file from rapidu.net. I get the information "global name 'challenge' is not defined"
was working on 2021-11-24 
did not work 2021-12-04

Maybe the new plugin broke something:
30.11.2021 04:10:54	INFO	ADDON UpdateManager: New version of plugin: HOSTER RapiduNet (v0.17 -> v0.18)

### Debug log

06.12.2021 18:04:09	WARNING	ADDON TORRENT: torrents / magnets are not associated with any plugin
474	06.12.2021 18:04:09	INFO	ADDON ClickNLoad: Shutting down proxy...
475	06.12.2021 18:04:13	INFO	Starting pyLoad 0.4.20
476	06.12.2021 18:04:13	INFO	Using home directory: /mnt/sda2/pyload/.pyload
477	06.12.2021 18:04:22	INFO	Activated plugins: ClickNLoad, EventMapper, ExternalScripts, TORRENT, UnSkipOnFail, UpdateManager, UserAgentSwitcher
478	06.12.2021 18:04:22	INFO	Deactivate plugins: AntiCaptcha, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
479	06.12.2021 18:04:22	INFO	Downloadtime: True
480	06.12.2021 18:04:22	INFO	Free space: 28.66 GiB
481	06.12.2021 18:04:24	INFO	Activating Accounts...
482	06.12.2021 18:04:24	INFO	Activating Plugins...
483	06.12.2021 18:04:29	INFO	Starting builtin webserver: :::8000
484	06.12.2021 18:04:29	WARNING	ADDON TORRENT: torrents / magnets are not associated with any plugin
485	06.12.2021 18:04:29	INFO	pyLoad is up and running
486	06.12.2021 18:04:29	INFO	ADDON UpdateManager: pyLoad is up to date!
487	06.12.2021 18:04:31	INFO	ADDON UpdateManager: All plugins are up to date!
488	06.12.2021 18:04:35	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
489	06.12.2021 18:41:09	INFO	Download starts: xxx.xxx
490	06.12.2021 18:41:09	WARNING	HOSTER RapiduNet[192]: Plugin may be unstable
491	06.12.2021 18:41:09	INFO	HOSTER RapiduNet[192]: Grabbing link info...
492	06.12.2021 18:41:09	INFO	HOSTER RapiduNet[192]: Link name: xxx.xxx
493	06.12.2021 18:41:09	INFO	HOSTER RapiduNet[192]: Link size: 8.72 GiB (9364401509 bytes)
494	06.12.2021 18:41:09	INFO	HOSTER RapiduNet[192]: Link status: online
495	06.12.2021 18:41:09	INFO	HOSTER RapiduNet[192]: Processing url: https://rapidu.net/xxx
496	06.12.2021 18:41:09	INFO	HOSTER RapiduNet[192]: Looking for direct download link...
497	06.12.2021 18:41:10	INFO	HOSTER RapiduNet[192]: Direct download link not found
498	06.12.2021 18:41:10	INFO	HOSTER RapiduNet[192]: Checking for link errors...
499	06.12.2021 18:41:10	INFO	HOSTER RapiduNet[192]: No errors found
500	06.12.2021 18:41:10	INFO	HOSTER RapiduNet[192]: Processing as free download...
501	06.12.2021 18:41:10	WARNING	CAPTCHA RapiduNet[192]: ReCaptcha | Secure Token pattern not found
502	06.12.2021 18:41:10	WARNING	CAPTCHA RapiduNet[192]: ReCaptcha | Could not properly detect reCAPTCHA version, defaulting to v2
503	06.12.2021 18:41:10	WARNING	CAPTCHA RapiduNet[192]: ReCaptcha | Secure Token pattern not found
504	06.12.2021 18:41:11	WARNING	CAPTCHA RapiduNet[192]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
505	06.12.2021 18:44:10	INFO	CAPTCHA RapiduNet[192]: ReCaptcha | Captcha result: `03AGdBq26DFbV-l43g05sKQ6hfbrhby2NSOZv2JIen1nTWd3L8Kf7aD0EA7DWTxcitpr2kSN63pYZJw6cJ1o4HuLbEqoGsbVq7vJaS982YZI3VSpiD-dWk0SBYp9EeOtDg0feMQiDVghWKsye7zVcbSpMzF42W2-019jm1ycTNWfaZQWD0PImTCWqhNjwgfnDA1HBUbL2DJKLxernY2jyGilyOnA3doIy_8Bmr4xJDy4md2kHFrCvkA8TXNDXHKzWbumlDcoeM_F9wfBKEPslh7SsKRZmaF1tgIk813heCEyWZaBijxdwPMNmC48VyDiQqMkXc0ZcrGtDci2Mn35Ynm7v43TIBCGNOMhZN3bJ5sHKsbSO2JQ7vaRj9mI1SC_HAyFC8VOnkO76NlaznudZWymMzIPRKCXN_ZtVsQxBf4-b6b68Dkn5lmmVEdmtudo5XvzzoY9h1_xk-`
506	06.12.2021 18:44:10	WARNING	HOSTER RapiduNet[192]: Invalid wait time interval
507	06.12.2021 18:44:10	WARNING	Download failed: xxx.xxx | global name 'challenge' is not defined
508	06.12.2021 18:44:10	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: xxx.xxx (pid:34)
509	06.12.2021 18:44:10	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
Sample URL please

**Comment by skwaruch** [comment]
https://rapidu.net/081278835970367/

**Comment by GammaC0de** [comment]
I get 404 (:

**Comment by skwaruch** [comment]
URL is OK

**Comment by GammaC0de** [comment]
For me is does not work :(
maybe it has some geolocation restrictions :(
![image](https://user-images.githubusercontent.com/11036551/144933660-daced5ff-8d5d-4186-8604-00b0b923fe8f.png)

**Comment by GammaC0de** [comment]
You can try to [produce a HAR fie](https://www.medianova.com/en-blog/a-step-by-step-guide-to-generating-a-har-file/)  while downloading the URL..
Then post the file somewhere
