### ISSUE TITLE
RarefileNet

### ISSUE THREAD

**Issue by JustinS-B** [pyload/pyload#4050]
### Description
RarefileNet plugin is ignoring my valid premium account and falling back to free download. I can use my premium account to download in my browser, so I know that it is working & not a Rarefile issue.

### Debug log
18.12.2021 17:14:38	INFO	Added package Live containing 1 links
18.12.2021 17:14:38	INFO	Download starts: http://www.rarefile.net/snipped_url_Live.zip
18.12.2021 17:14:38	WARNING	HOSTER RarefileNet[2303]: Plugin may be unstable
18.12.2021 17:14:39	INFO	ACCOUNT RarefileNet: Grabbing account info for user `pal*******`...
18.12.2021 17:14:39	INFO	HOSTER RarefileNet[2302]: Processing url: http://www.rarefile.net/snipped_url_Live.zip
18.12.2021 17:14:39	INFO	HOSTER RarefileNet[2302]: Looking for direct download link...
18.12.2021 17:14:40	INFO	HOSTER RarefileNet[2302]: Direct download link detected
18.12.2021 17:14:40	INFO	HOSTER RarefileNet[2302]: Downloading file...
18.12.2021 17:14:40	ERROR	HOSTER RarefileNet[2302]:
18.12.2021 17:14:40	WARNING	HOSTER RarefileNet[2302]: Premium download failed | IOError 2
18.12.2021 17:14:40	INFO	Download restarted: http://www.rarefile.net/snipped_url_Live.zip | Fallback to free processing
18.12.2021 17:14:41	INFO	Download starts: http://www.rarefile.net/snipped_url_Live.zip

### Additional references
@vuolter fixed this last time it broke in issue #717. Like last time, I can give my premium account details to whoever needs them to fix this.

**Comment by GammaC0de** [comment]
Please send account info to nitzo2001 at yahoo dot com
 
  ***@***.***> wrote:   


Assigned #4050 to @GammaC0de.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JustinS-B** [comment]
@GammaC0de I sent the account details over to you. Thanks.

**Comment by GammaC0de** [comment]
👍

**Comment by GammaC0de** [comment]
apparently, this is duplicate of https://github.com/pyload/pyload/issues/4045 which is now should be fixed, can you check again?

**Comment by JustinS-B** [comment]
All fixed & working as normal again. Thank you.
