### ISSUE TITLE
Prevent the banner from hiding the main menu

### ISSUE THREAD

**Issue by foorschtbar** [pyload/pyload#4052]
### Feature description

Change the behavior of the "Sucess, Failed, Captch Request, [...]" banner so that it no longer hides the menu when it is displayed. 

Am I the only person who is bothered by this or do I just not know how to change it?

### Additional references

![banner](https://user-images.githubusercontent.com/10727275/146761399-cbd0c66e-fb5d-42d3-8752-edb2a6e52e1b.gif)

**Comment by shoopdawoop** [comment]
I would very much appreciate this as well.

I tried editing the base.css to have the banner pop up at the bottom but that did not work too well either.

**Comment by GammaC0de** [comment]
Soon.

**Comment by foorschtbar** [comment]
Great. Thank u!
