### ISSUE TITLE
FSHARE Outdated plugin

### ISSUE THREAD

**Issue by huythanh5595** [pyload/pyload#4057]
FSHARE Outdated plugin
### Description
FSHARE Outdated plugin

FSHARE Outdated plugin

### Debug log
798	25.12.2021 11:23:40	WARNING	Download failed: Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv | 'login'
799	25.12.2021 11:23:40	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv (pid:12)
800	25.12.2021 11:23:40	INFO	ADDON UnSkipOnFail: No duplicates found
801	25.12.2021 11:26:11	INFO	Added package test containing 1 links
802	25.12.2021 11:26:12	INFO	Download starts: https://download031.fshare.vn/dl/ffPdf4JsCkUjp40PilKXMsviTRPYBJAIQbzB6tRoy4LI8UBOSc7B4l3Jgu5Hs-NwYhpq0sVaWmi3-wu+/Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv
803	25.12.2021 11:26:12	WARNING	HOSTER BasePlugin[13]: Plugin may be unstable
804	25.12.2021 11:26:12	INFO	HOSTER BasePlugin[13]: Grabbing link info...
805	25.12.2021 11:26:12	INFO	HOSTER BasePlugin[13]: Link name: Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv
806	25.12.2021 11:26:12	INFO	HOSTER BasePlugin[13]: Link size: N/D
807	25.12.2021 11:26:12	INFO	HOSTER BasePlugin[13]: Link status: starting
808	25.12.2021 11:26:12	INFO	HOSTER BasePlugin[13]: Processing url: https://download031.fshare.vn/dl/ffPdf4JsCkUjp40PilKXMsviTRPYBJAIQbzB6tRoy4LI8UBOSc7B4l3Jgu5Hs-NwYhpq0sVaWmi3-wu+/Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv
809	25.12.2021 11:26:13	WARNING	Download failed: Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv | Bad server response: 500 Internal Server Error
810	25.12.2021 11:26:13	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv (pid:13)
811	25.12.2021 11:26:13	INFO	ADDON UnSkipOnFail: No duplicates found
812	25.12.2021 11:26:25	INFO	Added package 123 containing 1 links
813	25.12.2021 11:26:26	INFO	Download starts: https://download031.fshare.vn/dl/ffPdf4JsCkUjp40PilKXMsviTRPYBJAIQbzB6tRoy4LI8UBOSc7B4l3Jgu5Hs-NwYhpq0sVaWmi3-wu+/Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv
814	25.12.2021 11:26:26	WARNING	HOSTER BasePlugin[14]: Plugin may be unstable
815	25.12.2021 11:26:26	INFO	HOSTER BasePlugin[14]: Grabbing link info...
816	25.12.2021 11:26:26	INFO	HOSTER BasePlugin[14]: Link name: Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv
817	25.12.2021 11:26:26	INFO	HOSTER BasePlugin[14]: Link size: N/D
818	25.12.2021 11:26:26	INFO	HOSTER BasePlugin[14]: Link status: starting
819	25.12.2021 11:26:26	INFO	HOSTER BasePlugin[14]: Processing url: https://download031.fshare.vn/dl/ffPdf4JsCkUjp40PilKXMsviTRPYBJAIQbzB6tRoy4LI8UBOSc7B4l3Jgu5Hs-NwYhpq0sVaWmi3-wu+/Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv
820	25.12.2021 11:26:27	WARNING	Download failed: Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv | Bad server response: 500 Internal Server Error
821	25.12.2021 11:26:27	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Iron.Man.2008.Open.Matte.1080p.BluRay.DTS.x264-BLUEBIRD.mkv (pid:14)
822	25.12.2021 11:26:27	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
1. Refresh your pyLoad installation using the instruction in #3283.
2.  Enable debug mode
3. Retry the download and provide a debug log from the start of the download until if fails. 
4. Provide sample URL

**Comment by huythanh5595** [comment]
I did it but still got the error, please help me

link: https://www.fshare.vn/file/ZWAH8E1QC8U9

866	25.12.2021 17:22:06	INFO	Starting pyLoad 0.4.20
867	25.12.2021 17:22:06	INFO	Using home directory: /root/.pyload
868	25.12.2021 17:22:08	INFO	Activated plugins: ClickNLoad, EventMapper, ExternalScripts, TORRENT, UnSkipOnFail, UpdateManager, UserAgentSwitcher
869	25.12.2021 17:22:08	INFO	Deactivate plugins: AntiCaptcha, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
870	25.12.2021 17:22:08	INFO	Downloadtime: True
871	25.12.2021 17:22:08	INFO	Starting ThriftBackend: 0.0.0.0:7227
872	25.12.2021 17:22:10	WARNING	SSL certificates not found.
873	25.12.2021 17:22:10	INFO	Starting builtin webserver: 192.168.1.196:8888
874	25.12.2021 17:22:10	INFO	Free space: 2.45 TiB
875	25.12.2021 17:22:10	INFO	Activating Accounts...
876	25.12.2021 17:22:10	INFO	ACCOUNT FshareVn: Adding user `psb*******`...
877	25.12.2021 17:22:10	INFO	ACCOUNT FshareVn: Login user `psb*******`...
878	25.12.2021 17:22:10	ERROR	ACCOUNT FshareVn: Login failed, error code 403
879	25.12.2021 17:22:10	ERROR	ACCOUNT FshareVn: Could not login user `psb*******` | Login handshake has failed
880	25.12.2021 17:22:10	INFO	Activating Plugins...
881	25.12.2021 17:22:10	WARNING	ADDON TORRENT: torrents / magnets are not associated with any plugin
882	25.12.2021 17:22:10	INFO	pyLoad is up and running
883	25.12.2021 17:22:11	INFO	ADDON UpdateManager: pyLoad is up to date!
884	25.12.2021 17:22:11	INFO	ADDON UpdateManager: Removed blacklisted plugin: ACCOUNTS GetTwentyFourOrg
885	25.12.2021 17:22:11	INFO	ADDON UpdateManager: Removed blacklisted plugin: HOSTER GetTwentyFourOrg
886	25.12.2021 17:22:11	INFO	ADDON UpdateManager: All plugins are up to date!
887	25.12.2021 17:22:16	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
888	25.12.2021 17:22:43	INFO	ACCOUNT FshareVn: Removing user `psb*******`...
889	25.12.2021 17:23:12	INFO	ACCOUNT FshareVn: Adding user `psb*******`...
890	25.12.2021 17:23:12	INFO	ACCOUNT FshareVn: Relogin user `psb*******`...
891	25.12.2021 17:23:12	ERROR	ACCOUNT FshareVn: Login failed, error code 403
892	25.12.2021 17:23:12	ERROR	ACCOUNT FshareVn: Could not login user `psb*******` | Login handshake has failed
893	25.12.2021 17:24:05	INFO	Added package 123 containing 1 links
894	25.12.2021 17:24:06	INFO	Download starts: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640427805
895	25.12.2021 17:24:06	WARNING	HOSTER FshareVn[15]: Plugin may be unstable
896	25.12.2021 17:24:06	WARNING	Download failed: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640427805 | 'NoneType' object has no attribute 'get_info'
897	25.12.2021 17:24:06	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640427805 (pid:15)
898	25.12.2021 17:24:06	INFO	ADDON UnSkipOnFail: No duplicates found
899	25.12.2021 17:24:36	INFO	Added package test containing 1 links
900	25.12.2021 17:24:37	INFO	Download starts: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640427805
901	25.12.2021 17:24:37	WARNING	HOSTER FshareVn[16]: Plugin may be unstable
902	25.12.2021 17:24:37	WARNING	Download failed: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640427805 | 'NoneType' object has no attribute 'get_info'
903	25.12.2021 17:24:37	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640427805 (pid:16)
904	25.12.2021 17:24:37	INFO	ADDON UnSkipOnFail: No duplicates found
905	25.12.2021 17:25:43	INFO	Added package test containing 1 links
906	25.12.2021 17:25:43	INFO	Download starts: https://www.fshare.vn/file/ZWAH8E1QC8U9
907	25.12.2021 17:25:43	WARNING	HOSTER FshareVn[17]: Plugin may be unstable
908	25.12.2021 17:25:43	WARNING	Download failed: https://www.fshare.vn/file/ZWAH8E1QC8U9 | 'NoneType' object has no attribute 'get_info'
909	25.12.2021 17:25:43	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: https://www.fshare.vn/file/ZWAH8E1QC8U9 (pid:17)
910	25.12.2021 17:25:43	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by huythanh5595** [comment]
I sent it, please help me

**Comment by GammaC0de** [comment]
plugin updated, please test.

**Comment by huythanh5595** [comment]
Thank you for your support, I have updated the plugin. when i entered fshare account in pyload it recognized me as premium account.

but it still can't download the file with fshare, I have attached the image when pyload loads
![fshare pyload](https://user-images.githubusercontent.com/70749465/147395301-e5ab9b7d-ec9f-4b6b-83ff-6372aefd3770.png)

log:
943	26.12.2021 06:03:06	INFO	ADDON UpdateManager: Removed blacklisted plugin: HOSTER GetTwentyFourOrg
944	26.12.2021 06:03:06	INFO	ADDON UpdateManager: All plugins are up to date!
945	26.12.2021 06:03:11	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
946	26.12.2021 06:05:04	INFO	Added package test containing 1 links
947	26.12.2021 06:05:05	INFO	Download starts: https://www.fshare.vn/file/ZWAH8E1QC8U9
948	26.12.2021 06:05:05	WARNING	HOSTER FshareVn[5]: Plugin may be unstable
949	26.12.2021 06:05:05	INFO	ACCOUNT FshareVn: Grabbing account info for user `psb*******`...
950	26.12.2021 06:05:05	INFO	HOSTER FshareVn[5]: Processing url: https://www.fshare.vn/file/ZWAH8E1QC8U9
951	26.12.2021 06:05:05	INFO	HOSTER FshareVn[5]: Looking for direct download link...
952	26.12.2021 06:05:06	INFO	HOSTER FshareVn[5]: Direct download link not found
953	26.12.2021 06:05:08	INFO	HOSTER FshareVn[5]: Checking for link errors...
954	26.12.2021 06:05:08	INFO	HOSTER FshareVn[5]: No errors found
955	26.12.2021 06:05:08	INFO	HOSTER FshareVn[5]: Grabbing link info...
956	26.12.2021 06:05:08	WARNING	Download failed: ZWAH8E1QC8U9 | 'Browser' object has no attribute 'c'
957	26.12.2021 06:05:08	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: ZWAH8E1QC8U9 (pid:5)
958	26.12.2021 06:05:08	INFO	ADDON UnSkipOnFail: No duplicates found
959	26.12.2021 06:06:27	INFO	Added package test containing 1 links
960	26.12.2021 06:06:27	INFO	Download starts: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640473572
961	26.12.2021 06:06:27	WARNING	HOSTER FshareVn[6]: Plugin may be unstable
962	26.12.2021 06:06:27	INFO	ACCOUNT FshareVn: Grabbing account info for user `psb*******`...
963	26.12.2021 06:06:27	INFO	HOSTER FshareVn[6]: Processing url: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640473572
964	26.12.2021 06:06:27	INFO	HOSTER FshareVn[6]: Looking for direct download link...
965	26.12.2021 06:06:28	INFO	HOSTER FshareVn[6]: Direct download link not found
966	26.12.2021 06:06:39	INFO	HOSTER FshareVn[6]: Checking for link errors...
967	26.12.2021 06:06:39	INFO	HOSTER FshareVn[6]: No errors found
968	26.12.2021 06:06:39	INFO	HOSTER FshareVn[6]: Grabbing link info...
969	26.12.2021 06:06:39	WARNING	Download failed: ZWAH8E1QC8U9 | 'Browser' object has no attribute 'c'
970	26.12.2021 06:06:39	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: ZWAH8E1QC8U9 (pid:6)
971	26.12.2021 06:06:39	INFO	ADDON UnSkipOnFail: No duplicates found
972	26.12.2021 06:07:38	INFO	Added package test containing 1 links
973	26.12.2021 06:07:39	INFO	Download starts: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640473572
974	26.12.2021 06:07:39	WARNING	HOSTER FshareVn[7]: Plugin may be unstable
975	26.12.2021 06:07:39	INFO	ACCOUNT FshareVn: Grabbing account info for user `psb*******`...
976	26.12.2021 06:07:40	INFO	HOSTER FshareVn[7]: Processing url: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640473572
977	26.12.2021 06:07:40	INFO	HOSTER FshareVn[7]: Looking for direct download link...
978	26.12.2021 06:07:40	INFO	HOSTER FshareVn[7]: Direct download link not found
979	26.12.2021 06:07:41	INFO	HOSTER FshareVn[7]: Checking for link errors...
980	26.12.2021 06:07:41	INFO	HOSTER FshareVn[7]: No errors found
981	26.12.2021 06:07:41	INFO	HOSTER FshareVn[7]: Grabbing link info...
982	26.12.2021 06:07:41	WARNING	Download failed: ZWAH8E1QC8U9 | 'Browser' object has no attribute 'c'
983	26.12.2021 06:07:41	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: ZWAH8E1QC8U9 (pid:7)
984	26.12.2021 06:07:41	INFO	ADDON UnSkipOnFail: No duplicates found
985	26.12.2021 06:08:13	INFO	Added package 123 containing 1 links
986	26.12.2021 06:08:14	INFO	Download starts: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640473572
987	26.12.2021 06:08:14	WARNING	HOSTER FshareVn[8]: Plugin may be unstable
988	26.12.2021 06:08:14	INFO	ACCOUNT FshareVn: Grabbing account info for user `psb*******`...
989	26.12.2021 06:08:14	INFO	HOSTER FshareVn[8]: Processing url: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640473572
990	26.12.2021 06:08:14	INFO	HOSTER FshareVn[8]: Looking for direct download link...
991	26.12.2021 06:08:15	INFO	HOSTER FshareVn[8]: Direct download link not found
992	26.12.2021 06:08:15	INFO	HOSTER FshareVn[8]: Checking for link errors...
993	26.12.2021 06:08:15	INFO	HOSTER FshareVn[8]: No errors found
994	26.12.2021 06:08:15	INFO	HOSTER FshareVn[8]: Grabbing link info...
995	26.12.2021 06:08:15	WARNING	Download failed: ZWAH8E1QC8U9 | 'Browser' object has no attribute 'c'
996	26.12.2021 06:08:15	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: ZWAH8E1QC8U9 (pid:8)
997	26.12.2021 06:08:15	INFO	ADDON UnSkipOnFail: No duplicates found
998	26.12.2021 06:08:38	INFO	Added package 123 containing 1 links
999	26.12.2021 06:08:40	INFO	Download starts: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640473572
1000	26.12.2021 06:08:40	WARNING	HOSTER FshareVn[9]: Plugin may be unstable
1001	26.12.2021 06:08:40	INFO	ACCOUNT FshareVn: Grabbing account info for user `psb*******`...
1002	26.12.2021 06:08:40	INFO	HOSTER FshareVn[9]: Processing url: https://www.fshare.vn/file/ZWAH8E1QC8U9?token=1640473572
1003	26.12.2021 06:08:40	INFO	HOSTER FshareVn[9]: Looking for direct download link...
1004	26.12.2021 06:08:44	INFO	HOSTER FshareVn[9]: Direct download link not found
1005	26.12.2021 06:08:44	INFO	HOSTER FshareVn[9]: Checking for link errors...
1006	26.12.2021 06:08:44	INFO	HOSTER FshareVn[9]: No errors found
1007	26.12.2021 06:08:44	INFO	HOSTER FshareVn[9]: Grabbing link info...
1008	26.12.2021 06:08:44	WARNING	Download failed: ZWAH8E1QC8U9 | 'Browser' object has no attribute 'c'
1009	26.12.2021 06:08:44	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: ZWAH8E1QC8U9 (pid:9)
1010	26.12.2021 06:08:44	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
Please enable debug mode and then retry

**Comment by GammaC0de** [comment]
OK, plugin updated again, please retest.

**Comment by huythanh5595** [comment]
it worked, thank you very much

**Comment by GammaC0de** [comment]
👍
