### ISSUE TITLE
Plugin Extractarchieve: Extraction failed

### ISSUE THREAD

**Issue by elgreco29** [pyload/pyload#4060]
Hi,

with my stable pyload as a docker on my QNAP-NAS i can't extract downloaded files. Any Ideas? Here is the log:

28.12.2021 09:49:42 | INFO | ADDON ExtractArchive: Check package: test429
-- | -- | --
498 | 28.12.2021 09:49:42 | INFO | ADDON ExtractArchive: V21-12-27.rar \| Extract to: /opt/pyload/Downloads/test429/
499 | 28.12.2021 09:49:42 | ERROR | ADDON ExtractArchive: V21-12-27.rar \| Archive error \| Command Line Error:
500 | ? | ? | Too short switch
501 | ? | ? | r!
502 | 28.12.2021 09:49:42 | ERROR | ADDON ExtractArchive: V21-12-27.rar \| Extract failed

Greetings from Germany

**Comment by GammaC0de** [comment]
Please enable debug mode and then post the log again

**Comment by elgreco29** [comment]
28.12.2021 21:06:55 | DEBUG | ADDON ExtractArchive: Targets for SevenZip: [(54, u'/opt/pyload/Downloads/test432/891.rar', u'/opt/pyload/Downloads/test432/')]
-- | -- | --
832 | 28.12.2021 21:06:55 | INFO | ADDON ExtractArchive: 891.rar \| Extract to: /opt/pyload/Downloads/test432/
833 | 28.12.2021 21:06:55 | DEBUG | ADDON ExtractArchive: Password: None provided
834 | 28.12.2021 21:06:55 | DEBUG | EXTRACTOR SevenZip: EXECUTE 7z l -bso0 -bsp1 -aoa -xr! -p- -slt /opt/pyload/Downloads/test432/891.rar
835 | 28.12.2021 21:06:55 | DEBUG | ADDON ExtractArchive: Extracting using password: None
836 | 28.12.2021 21:06:55 | DEBUG | EXTRACTOR SevenZip: EXECUTE 7z x -bso0 -bsp1 -aoa -xr! -p- -o/opt/pyload/Downloads/test432/ /opt/pyload/Downloads/test432/891.rar
837 | 28.12.2021 21:06:55 | ERROR | ADDON ExtractArchive: 891.rar \| Archive error \| Command Line Error:
838 | ? | ? | Too short switch
839 | ? | ? | r!
840 | ? | ? | Traceback (most recent call last):
841 | ? | ? | File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
842 | ? | ? | self.__bootstrap_inner()
843 | ? | ? | File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
844 | ? | ? | self.run()
845 | ? | ? | File "/opt/pyload/module/PluginThread.py", line 458, in run
846 | ? | ? | self.f(*self.args, **self.kwargs)
847 | ? | ? | File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 177, in extract_queued
848 | ? | ? | if self.extract(packages, thread): # @NOTE: check only if all gone fine, no failed reporting for now
-- | -- | -- | --
849 | ? | ? | File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 326, in extract
850 | ? | ? | new_files = self._extract(pyfile, archive, pypack.password)
851 | ? | ? | File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 462, in _extract
852 | ? | ? | archive.extract(password)
853 | ? | ? | File "/opt/pyload/module/plugins/internal/SevenZip.py", line 119, in extract
854 | ? | ? | raise ArchiveError(err)
855 | ? | ? | ArchiveError: Command Line Error:
856 | ? | ? | Too short switch
857 | ? | ? | r!
858 | ? | ? |  
859 | 28.12.2021 21:06:55 | DEBUG | ADDON ExternalScripts: No script found under folder `archive_extract_failed`
860 | 28.12.2021 21:06:55 | ERROR | ADDON ExtractArchive: 891.rar \| Extract failed
? | ? | Traceback (most recent call last):
-- | -- | --
862 | ? | ? | File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
863 | ? | ? | self.__bootstrap_inner()
864 | ? | ? | File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
865 | ? | ? | self.run()
866 | ? | ? | File "/opt/pyload/module/PluginThread.py", line 458, in run
867 | ? | ? | self.f(*self.args, **self.kwargs)
868 | ? | ? | File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 177, in extract_queued
869 | ? | ? | if self.extract(packages, thread): # @NOTE: check only if all gone fine, no failed reporting for now
870 | ? | ? | File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 326, in extract
871 | ? | ? | new_files = self._extract(pyfile, archive, pypack.password)
872 | ? | ? | File "/opt/pyload/module/plugins/hooks/ExtractArchive.py", line 530, in _extract
873 | ? | ? | raise Exception(_("Extract failed"))
874 | ? | ? | Exception: Extract failed

**Comment by GammaC0de** [comment]
What happens if you run
```
7z x -bso0 -bsp1 -aoa -xr! -p- -o/opt/pyload/Downloads/test432/ /opt/pyload/Downloads/test432/891.rar
```

Also, what is the version of 7z you have?

**Comment by elgreco29** [comment]
There is no 7-Zip on may NAS. This happend after i reinstalled pyload in my docker enviroment. Until a few days ago the previous docker with pyload worked fine for me for years.

**Comment by GammaC0de** [comment]
> There is no 7-Zip on my NAS

So 7-Zip resides inside the docker image.
Which docker image do you use? 

> Also, what is the version of 7z you have?

You can see it in the log if you restart pyload.

**Comment by elgreco29** [comment]
This is my log after i restart pyload

<html>
<body>
<div id="head-panel" style="background: url(&quot;/media/classic/img/head_bg1.png&quot;) left bottom repeat-x rgb(82, 82, 82); color: rgb(0, 0, 0); font-family: sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div id="head-search-and-login" style="float: right; margin: 0px 1em 0px 0px; background-color: rgb(34, 34, 34); padding: 7px 7px 5px 5px; color: white; white-space: nowrap; border-bottom-left-radius: 6px; border-bottom-right-radius: 6px;"><img src="http://192.168.1.21:8001/media/classic/img/head-login.png" alt="User:" style="border: none; vertical-align: middle; margin: 2px;"><span style="padding-right: 2px;">pyload</span><span> </span><ul id="user-actions" style="padding: 5px; margin: 0px; display: inline; color: black; background-color: rgb(236, 236, 236); list-style-type: none; border-radius: 3px;"><li style="margin: 5px; display: inline;"><a href="http://192.168.1.21:8001/logout" class="action logout" rel="nofollow" style="color: black; text-decoration: none; background: url(&quot;/media/classic/img/user-actions-logout.png&quot;) 0px 1px no-repeat transparent; display: inline; margin: 0px 3px; padding: 2px 0px 2px 18px;">Abmelden</a></li><span> </span><li style="margin: 5px; display: inline;"><a href="http://192.168.1.21:8001/admin" class="action profile" rel="nofollow" style="color: black; text-decoration: none; background: url(&quot;/media/classic/img/user-actions-profile.png&quot;) 0px 1px no-repeat transparent; display: inline; margin: 0px 3px; padding: 2px 0px 2px 18px;">Administrieren</a></li><span> </span><li style="margin: 5px; display: inline;"><a href="http://192.168.1.21:8001/info" class="action info" rel="nofollow" style="color: black; text-decoration: none; background: url(&quot;/media/classic/img/user-info.png&quot;) 0px 1px no-repeat transparent; display: inline; margin: 0px 3px; padding: 2px 0px 2px 18px;">Info</a></li></ul></div><a href="http://192.168.1.21:8001/" style="color: rgb(52, 101, 164); text-decoration: none;"><img id="head-logo" src="http://192.168.1.21:8001/media/classic/img/pyload-logo-edited3.5-new-font-small.png" alt="pyLoad" style="border: none; float: left; margin: 5px 0px -15px 5px; padding: 0px; overflow: visible;"></a><div id="head-menu" style="width: 1680px; float: left; margin: 0px; padding: 0.8em 0px 0px; background: url(&quot;/media/classic/img/tabs-border-bottom.png&quot;) 0px 100% repeat-x transparent;"><ul style="list-style: none; margin: 0px 1em 0px 2em;"><li style="margin: 0px 0px 4px 0.3em; float: left; font-size: 14px;"><a href="http://192.168.1.21:8001/" title="" style="color: rgb(85, 85, 85); text-decoration: none; float: left; padding: 3px 7px; border-width: 2px 2px 0px; border-style: solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) transparent; border-image: initial; border-radius: 5px; background: url(&quot;/media/classic/img/tab-background.png&quot;) 0px 100% repeat-x rgb(234, 234, 234);"><img src="http://192.168.1.21:8001/media/classic/img/head-menu-home.png" alt="" style="border: none; height: 22px; width: 22px; vertical-align: middle;"><span> </span>Start</a></li><li style="margin: 0px 0px 4px 0.3em; float: left; font-size: 14px;"><a href="http://192.168.1.21:8001/queue/" title="" style="color: rgb(85, 85, 85); text-decoration: none; float: left; padding: 3px 7px; border-width: 2px 2px 0px; border-style: solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) transparent; border-image: initial; border-radius: 5px; background: url(&quot;/media/classic/img/tab-background.png&quot;) 0px 100% repeat-x rgb(234, 234, 234);"><img src="http://192.168.1.21:8001/media/classic/img/head-menu-queue.png" alt="" style="border: none; height: 22px; width: 22px; vertical-align: middle;"><span> </span>Warteschlange</a></li><li style="margin: 0px 0px 4px 0.3em; float: left; font-size: 14px;"><a href="http://192.168.1.21:8001/collector/" title="" style="color: rgb(85, 85, 85); text-decoration: none; float: left; padding: 3px 7px; border-width: 2px 2px 0px; border-style: solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) transparent; border-image: initial; border-radius: 5px; background: url(&quot;/media/classic/img/tab-background.png&quot;) 0px 100% repeat-x rgb(234, 234, 234);"><img src="http://192.168.1.21:8001/media/classic/img/head-menu-collector.png" alt="" style="border: none; height: 22px; width: 22px; vertical-align: middle;"><span> </span>Linksammler</a></li><li style="margin: 0px 0px 4px 0.3em; float: left; font-size: 14px;"><a href="http://192.168.1.21:8001/downloads/" title="" style="color: rgb(85, 85, 85); text-decoration: none; float: left; padding: 3px 7px; border-width: 2px 2px 0px; border-style: solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) transparent; border-image: initial; border-radius: 5px; background: url(&quot;/media/classic/img/tab-background.png&quot;) 0px 100% repeat-x rgb(234, 234, 234);"><img src="http://192.168.1.21:8001/media/classic/img/head-menu-development.png" alt="" style="border: none; height: 22px; width: 22px; vertical-align: middle;"><span> </span>Downloads</a></li><li class="right selected" style="margin: 0px 0px 0px 0.3em; float: left; font-size: 14px;"><a href="http://192.168.1.21:8001/logs/" class="action index" accesskey="x" rel="nofollow" style="color: rgb(53, 102, 165); text-decoration: none; background: url(&quot;/media/classic/img/tab-background.png&quot;) 0px 100% repeat-x rgb(234, 234, 234); float: left; padding: 3px 7px 7px; border-width: 2px 2px 0px; border-style: solid solid none; border-color: rgb(204, 204, 204) rgb(204, 204, 204) transparent; border-image: initial; border-radius: 5px 5px 0px 0px;"><img src="http://192.168.1.21:8001/media/classic/img/head-menu-index.png" alt="" style="border: none; height: 22px; width: 22px; vertical-align: middle;">Log</a></li><li class="right" style="margin: 0px 0px 4px 0.3em; float: left; font-size: 14px;"><a href="http://192.168.1.21:8001/settings/" class="action index" accesskey="x" rel="nofollow" style="color: rgb(85, 85, 85); text-decoration: none; background: url(&quot;/media/classic/img/tab-background.png&quot;) 0px 100% repeat-x rgb(234, 234, 234); float: left; padding: 3px 7px; border-width: 2px 2px 0px; border-style: solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) transparent; border-image: initial; border-radius: 5px;"><img src="http://192.168.1.21:8001/media/classic/img/head-menu-config.png" alt="" style="border: none; height: 22px; width: 22px; vertical-align: middle;">Einstellungen</a></li></ul></div><div style="clear: both;"></div></div><ul id="page-actions2" style="float: left; margin: 10px 10px 0px; padding: 6px; color: rgb(0, 0, 0); background-color: rgb(236, 236, 236); list-style-type: none; border-radius: 5px; font-family: sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li id="action_play" style="margin: 5px; display: inline;"><a href="http://192.168.1.21:8001/logs/#" class="action play" accesskey="o" rel="nofollow" style="color: black; text-decoration: none; background: url(&quot;/media/classic/img/control_play.png&quot;) 0px 1px no-repeat transparent; display: inline; margin: 0px 3px; padding: 2px 0px 2px 18px;">Starten</a></li><span> </span><li id="action_stop" style="margin: 5px; display: inline;"><a href="http://192.168.1.21:8001/logs/#" class="action stop" accesskey="o" rel="nofollow" style="color: black; text-decoration: none; background: url(&quot;/media/classic/img/control_stop.png&quot;) 0px 1px no-repeat transparent; display: inline; margin: 0px 3px; padding: 2px 0px 2px 18px;">Stoppen</a></li><span> </span><li id="action_cancel" style="margin: 5px; display: inline;"><a href="http://192.168.1.21:8001/logs/#" class="action cancel" accesskey="o" rel="nofollow" style="color: black; text-decoration: none; background: url(&quot;/media/classic/img/control_cancel.png&quot;) 0px 1px no-repeat transparent; display: inline; margin: 0px 3px; padding: 2px 0px 2px 18px;">Abbrechen</a></li><span> </span><li id="action_add" style="margin: 5px; display: inline;"><a href="http://192.168.1.21:8001/logs/#" class="action add" accesskey="o" rel="nofollow" style="color: black; text-decoration: none; background: url(&quot;/media/classic/img/control_add.png&quot;) 0px 1px no-repeat transparent; display: inline; margin: 0px 3px; padding: 2px 0px 2px 18px;">Hinzufügen</a></li></ul><ul id="page-actions" style="float: right; margin: 10px 10px 0px; padding: 6px; color: rgb(0, 0, 0); background-color: rgb(236, 236, 236); list-style-type: none; white-space: nowrap; border-radius: 5px; font-family: sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="margin: 5px; display: inline;"><span class="time" style="padding: 2px 0px 2px 18px; margin: 0px 3px; background: url(&quot;/media/classic/img/status_None.png&quot;) 0px 1px no-repeat transparent;">Download:</span><a id="time" style="color: black; text-decoration: none; display: inline; margin: 0px 3px; padding: 2px 0.1cm 2px 0cm; background-color: rgb(143, 252, 37);"><span> </span>an</a></li><span> </span><li style="margin: 5px; display: inline;"><span class="reconnect" style="padding: 2px 0px 2px 18px; margin: 0px 3px; background: url(&quot;/media/classic/img/reconnect.png&quot;) 0px 1px no-repeat transparent;">Reconnect:</span><a id="reconnect" style="color: black; text-decoration: none; display: inline; margin: 0px 3px; padding: 2px 0.1cm 2px 0cm; background-color: rgb(143, 252, 37);"><span> </span>an</a></li><span> </span><li style="margin: 5px; display: inline;"><a class="action backlink" style="color: black; text-decoration: none; background: url(&quot;/media/classic/img/page-tools-backlinks.png&quot;) 0px 1px no-repeat transparent; display: inline; margin: 0px 3px; padding: 2px 0px 2px 18px;">Geschwindigkeit:<span> </span><b id="speed">0 B/s</b></a></li><span> </span><li style="margin: 5px; display: inline;"><a class="action cog" style="color: black; text-decoration: none; background: url(&quot;/media/classic/img/cog.png&quot;) 0px 1px no-repeat transparent; display: inline; margin: 0px 3px; padding: 2px 0px 2px 18px;">Aktiv:<span> </span><b id="aktiv" title="Active">0</b><span> </span>/<span> </span><b id="aktiv_from" title="Queued">1</b><span> </span>/<span> </span><b id="aktiv_total" title="Total">54</b></a></li><span> </span><li style="margin: 5px; display: inline;"><a href="http://192.168.1.21:8001/logs/" class="action revisions" accesskey="o" rel="nofollow" style="color: black; text-decoration: none; background: url(&quot;/media/classic/img/page-tools-revisions.png&quot;) 0px 1px no-repeat transparent; display: inline; margin: 0px 3px; padding: 2px 0px 2px 18px;">Aktualisieren</a></li></ul><br style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div id="body-wrapper" class="dokuwiki" style="height: 664.297px; padding: 40px 40px 10px; font-size: 15.24px; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div id="content" lang="en" dir="ltr" style="height: 664.297px; margin-top: -20px; padding: 0px; font-size: 14px; color: black; line-height: 1.5em;"><h1 style="background: none 0px 0px repeat scroll transparent; border-bottom: 1px solid rgb(170, 170, 170); color: black; font-weight: normal; margin: 0px 0px 0.1em; padding: 0.5em 0px 0px; font-size: 26.32px; line-height: 1.2em;">Log</h1><br><div class="level1" style="clear: both;"></div><div id="load-indicator" style="opacity: 0; float: right; margin-top: -10px;"><img src="http://192.168.1.21:8001/media/classic/img/ajax-loader.gif" alt="" style="border: none; padding-right: 5px;"><span> </span>lade</div><div style="clear: both;"></div><div class="logpaginator" style="float: left; padding-top: 5px;"><a href="http://192.168.1.21:8001/logs/1" style="color: rgb(52, 101, 164); text-decoration: none; padding: 0px 8px;">&lt;&lt; Starten</a><span> </span><a href="http://192.168.1.21:8001/logs/1" style="color: rgb(52, 101, 164); text-decoration: none; padding: 0px 8px;">&lt; zurück</a><span> </span><a href="http://192.168.1.21:8001/logs/1" style="color: rgb(52, 101, 164); text-decoration: none; padding: 0px 8px;">weiter &gt;</a><span> </span><a href="http://192.168.1.21:8001/logs/" style="color: rgb(52, 101, 164); text-decoration: none; padding: 0px 8px;">Ende &gt;&gt;</a></div><div class="logperpage" style="float: right; padding-bottom: 8px;"><form id="logform1" action="http://192.168.1.21:8001/logs/" method="POST" style="margin: 0px; padding: 0px; border: none; display: inline; background: transparent;"><label for="reversed">Reversed:</label><span> </span><input type="checkbox" name="reversed" onchange="this.form.submit();"> <span> </span><label for="perpage">Lines per page:</label><span> </span><select name="perpage" onchange="this.form.submit();"><span> </span> <span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><option value="0" selected="selected" style="border: 0px none rgb(255, 255, 255);">all</option><span> </span> <span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><option value="20" style="border: 0px none rgb(255, 255, 255);">20</option><span> </span> <span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><option value="34" style="border: 0px none rgb(255, 255, 255);">34</option><span> </span> <span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><option value="40" style="border: 0px none rgb(255, 255, 255);">40</option><span> </span> <span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><option value="100" style="border: 0px none rgb(255, 255, 255);">100</option><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span></select></form></div><div class="logwarn" style="text-align: center; color: red;"></div><div style="clear: both;"></div><div class="logdiv" style="height: 580.859px; width: 1583px; overflow: auto; border: 2px solid rgb(204, 204, 204); outline: rgb(102, 102, 102) solid 1px; background-color: rgb(255, 255, 238); margin-right: auto; margin-left: auto;">

1 | 03.01.2022 10:23:56 | INFO | ACCOUNT Keep2ShareCc: Grabbing account info for user `elg*******`...
-- | -- | -- | --
2 | 03.01.2022 10:23:56 | INFO | ACCOUNT PremiumTo: Adding user `GUY*******`...
3 | 03.01.2022 10:23:56 | INFO | ACCOUNT PremiumTo: Login user `GUY*******`...
4 | 03.01.2022 10:23:56 | INFO | ACCOUNT PremiumTo: Grabbing account info for user `GUY*******`...
5 | 03.01.2022 10:23:56 | INFO | Activating Plugins...
6 | 03.01.2022 10:23:56 | WARNING | ADDON TORRENT: torrents / magnets are not associated with any plugin
7 | 03.01.2022 10:23:56 | INFO | pyLoad is up and running
8 | 03.01.2022 10:23:56 | INFO | ADDON UpdateManager: pyLoad is up to date!
9 | 03.01.2022 10:23:56 | INFO | ADDON UpdateManager: All plugins are up to date!
10 | 03.01.2022 10:24:02 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
11 | 03.01.2022 10:24:02 | ERROR | ADDON ClickNLoad: [Errno 98] Address already in use
12 | 03.01.2022 10:24:24 | INFO | starte pyLoad 0.4.20
13 | 03.01.2022 10:24:24 | INFO | Benutze Home-Verzeichnis: /opt/pyload/pyload-config
14 | 03.01.2022 10:24:24 | INFO | Aktivierte Plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, TORRENT, UnSkipOnFail, UpdateManager, UserAgentSwitcher
15 | 03.01.2022 10:24:24 | INFO | Deaktivierte Plugins: AntiCaptcha, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
16 | 03.01.2022 10:24:24 | INFO | Downloadzeit: True
17 | 03.01.2022 10:24:24 | INFO | Starte ThriftBackend: 0.0.0.0:7227
18 | 03.01.2022 10:24:24 | INFO | Starting builtin webserver: :::8001
19 | 03.01.2022 10:24:24 | INFO | Free space: 1.13 TiB
20 | 03.01.2022 10:24:24 | INFO | Activating Accounts...
21 | 03.01.2022 10:24:24 | INFO | ACCOUNT Keep2ShareCc: Adding user `elg*******`...
22 | 03.01.2022 10:24:24 | INFO | ACCOUNT Keep2ShareCc: Login user `elg*******`...
23 | 03.01.2022 10:24:25 | INFO | ACCOUNT Keep2ShareCc: Grabbing account info for user `elg*******`...
24 | 03.01.2022 10:24:25 | INFO | ACCOUNT PremiumTo: Adding user `GUY*******`...
25 | 03.01.2022 10:24:25 | INFO | ACCOUNT PremiumTo: Login user `GUY*******`...
26 | 03.01.2022 10:24:25 | INFO | ACCOUNT PremiumTo: Grabbing account info for user `GUY*******`...
27 | 03.01.2022 10:24:25 | INFO | Activating Plugins...
28 | 03.01.2022 10:24:25 | WARNING | ADDON TORRENT: torrents / magnets are not associated with any plugin
29 | 03.01.2022 10:24:25 | INFO | pyLoad is up and running
30 | 03.01.2022 10:24:25 | INFO | ADDON UpdateManager: pyLoad is up to date!
31 | 03.01.2022 10:24:25 | INFO | ADDON UpdateManager: All plugins are up to date!
32 | 03.01.2022 10:24:31 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
33 | 03.01.2022 10:24:31 | ERROR | ADDON ClickNLoad: [Errno 98] Address already in use
34 | 03.01.2022 10:28:31 | ERROR | ADDON ClickNLoad: [Errno 98] Address already in use
35 | 03.01.2022 10:29:41 | INFO | restarting pyLoad
36 | 03.01.2022 10:29:41 | INFO | shutting down...
37 | 03.01.2022 10:29:41 | WARNING | ADDON TORRENT: torrents / magnets are not associated with any plugin
38 | 03.01.2022 10:29:41 | INFO | ADDON ClickNLoad: Shutting down proxy...

</div><div class="logform" style="display: table; margin: 0px auto; padding-top: 5px;"><form id="logform2" action="http://192.168.1.21:8001/logs/" method="POST" style="margin: 0px; padding: 0px; border: none; display: inline; background: transparent;"><label for="from">Springe zu Zeitpunkt:</label><input type="text" name="from" size="15" value="03.01.2022 10:23:56"><span> </span><input type="submit" value="ok"></form></div><div style="clear: both; height: 10px;"> </div><hr style="border: none; height: 1px; color: rgb(192, 192, 192); background-color: rgb(192, 192, 192); margin: 0.2em 0px; clear: both;"><div id="foot" style="font-style: normal; color: rgb(136, 136, 136); text-align: center;">© 2008-2018 pyLoad Team<span> </span><a href="http://192.168.1.21:8001/logs/#top" class="action top" accesskey="x" style="color: rgb(170, 170, 255); text-decoration: none;"><span>Nach oben</span></a></div></div></div>
</body>
</html>

**Comment by GammaC0de** [comment]
Please surround the log inside a code block(https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by GammaC0de** [comment]
> © 2008-2018 pyLoad Team Nach oben

Your pyload is 4 years old.

You said you're using docker so I recommend using https://github.com/linuxserver/docker-pyload
