### ISSUE TITLE
Alldebrid 'PyFile' object has no attribute 'set_status'

### ISSUE THREAD

**Issue by ManlyJack** [pyload/pyload#4061]
### Description
Pyload no longer gets the Decoded URL through alldebrid

### Debug log
INFO	Added package ************ containing 1 links
INFO	Download starts: https://uptobox.com/************
WARNING	HOSTER AlldebridCom[9]: AlldebridCom | Plugin may be unstable
INFO	ACCOUNT AlldebridCom: Grabbing account info for user `D*********`...
INFO	HOSTER AlldebridCom[9]: AlldebridCom | Processing url: https://uptobox.com/************
INFO	HOSTER AlldebridCom[9]: AlldebridCom | Checking for link errors...
WARNING	HOSTER AlldebridCom[9]: AlldebridCom | No data to check
INFO	HOSTER AlldebridCom[9]: AlldebridCom | Grabbing link info...
INFO	HOSTER AlldebridCom[9]: AlldebridCom | Link name: ************
INFO	HOSTER AlldebridCom[9]: AlldebridCom | Link size: N/D
INFO	HOSTER AlldebridCom[9]: AlldebridCom | Link status: starting
WARNING	Download failed: *********** | 'PyFile' object has no attribute 'set_status'
INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: *********** (pid:7)
INFO	ADDON UnSkipOnFail: No duplicates found 

### Additional references
Has happened on two installs of pyload just out of the blue, I believe same versions as were previously working fine.

**Comment by andree182** [comment]
ulozto the same, probably https://github.com/pyload/pyload/commit/ce198d2501e6b36591fee3e8f51cc5989cf0013f ...

**Comment by Timothee64** [comment]
got the same error with ddl... 

INFO	HOSTER DdownloadCom[84]: Looking for direct download link...
INFO	HOSTER DdownloadCom[84]: Direct download link not found
INFO	HOSTER DdownloadCom[84]: Checking for link errors...
INFO	HOSTER DdownloadCom[84]: No errors found
INFO	HOSTER DdownloadCom[84]: Grabbing link info...
INFO	HOSTER DdownloadCom[84]: Link size: X.XX GiB (XXXXXXXXXXX bytes)
INFO	HOSTER DdownloadCom[84]: Link status: online
WARNING	Download failed: ************* | 'PyFile' object has no attribute 'set_status'

**Comment by zephura** [comment]
> ulozto the same, probably [ce198d2](https://github.com/pyload/pyload/commit/ce198d2501e6b36591fee3e8f51cc5989cf0013f) ...

andree182 is right, I've commented the specified line, and it worked again... (waiting the official patch ;) )

**Comment by ManlyJack** [comment]
I couldn't find the specific line in the AlldebridCom.py file, any hints? Or I'll just wait it out

**Comment by Kenifornication** [comment]
> I couldn't find the specific line in the AlldebridCom.py file, any hints? Or I'll just wait it out

The line is in the file `SimpleHoster.py` found in `userplugins/internal`

Can confirm that commenting the line fixes the issue

**Comment by ManlyJack** [comment]
> The line is in the file `SimpleHoster.py` found in `userplugins/internal`

Opened the file, and it's already in there, yet still have the same issue

**Comment by GammaC0de** [comment]
Change `set_status` to `setStatus` and it old work fine.

Fix will be made today.
(This is what happens when.you maintain two different pyload version 🤦🏻‍♂️)

**Comment by ManlyJack** [comment]
> Fix will be made today.

Thanks! This is version 4.20 on the linuxserver docker template.

**Comment by ManlyJack** [comment]
> Change `set_status` to `setStatus` and it old work fine.

Confirmed to work, had to increment the version inside .py file by .01 in order for it to be used instead of the one inside the docker.
