### ISSUE TITLE
GoogledriveCom not show speed download

### ISSUE THREAD

**Issue by huythanh5595** [pyload/pyload#4062]
hello support team

help me. GoogledriveCom not show speed download

link: https://drive.google.com/drive/folders/13YzNGLcdFbRhXV7QzOCRaEsmhfmcZppj?usp=sharing

![2](https://user-images.githubusercontent.com/70749465/148147268-393182a2-4011-4f7d-be06-3aae4cce7571.png)
![1](https://user-images.githubusercontent.com/70749465/148147272-e6710c9d-2560-49a7-a5f9-13a292ba0858.png)

**Comment by GammaC0de** [comment]
Works fine for me,
Please refresh your pyLoad installation using the instruction in #3283 and then retry.

**Comment by GammaC0de** [comment]
No response, closing.
