### ISSUE TITLE
pyLoad for iOs: Connection failed

### ISSUE THREAD

**Issue by julien-jan** [pyload/pyload#4065]
Hello, I've been using pyload for a while now and I also have the iOs application. But recently, the app stopped reaching my server.
![image](https://user-images.githubusercontent.com/66908338/148627032-6fa70c15-917a-4f9b-aa25-0edf7c300798.png)
I haven't changed anything in my settings and I can perfectly use pyload with the web GUI.
If thats a bug from the application I hope it will be fixed because I paid for this app.
As my pyload server works normally, I don't really know what other information I can give.
Thanks

**Comment by micwoj92** [comment]
You should report it to "pyload for ios" developers, I don't even know if that application is official.

**Comment by julien-jan** [comment]
> You should report it to "pyload for ios" developers, I don't even know if that application is official.

There is a "Support" button which leads me to pyload.net so I thought it was.
![image](https://user-images.githubusercontent.com/66908338/148627684-d4747e0e-d509-4e4a-bad7-f238b5c3128f.png)

**Comment by GammaC0de** [comment]
pyLoad has no iOS app.

**Comment by qwrty-ftw** [comment]
@julien-jan do you switch from 0.4.20 to 0.5 ?
If yes, I guess that's why it's not working anymore.
