### ISSUE TITLE
ISP force reconnect evry 24 hours lead to "failed (28, 'Opertion to slow. Less than 5bytes/sec transferred the last 120 seconds')

### ISSUE THREAD

**Issue by StefanRu1** [pyload/pyload#4069]
### Question

Hi, 
I have a long download running from Rapigator.
My ISP does a force reconnect every 24 hours where i also get a new IP.
The junk which is downloaded when the reconnect occurs always aborts with the message:
failed (28, 'Opertion to slow. Less than 5bytes/sec transferred the last 120 seconds')

The force reconnect is not taking 120 seconds, but it seems that the download can not be restored after reconnect and fails after 120 seconds.

Is there a way to resume the download after force reconnect from ISP?

Thanks for the great Software,
Stefan

**Comment by GammaC0de** [comment]
If your ISP cuts the (TCP) connection, there is no way to restore it and the download would fail.
Just like if you had chrome download while  a force reconnect happens, am I right?

I would try to increase `Max timeout for link connection in seconds` settings if the `UserAgentSwitcher` plugin but i doubt it would help.

**Comment by StefanRu1** [comment]
Hi, 
thanks!
Yes in germany a lot of ISPs do a force disconnect every 24 hours. This means a complete disconnect.
The force reconnect takes between 10 and 30 seconds, with the new connection you also get a new IP.
Download Managers are able to resume a download after force disconnect.
But I understand with this hosters it is not possible.

I changed the setting und will check if it helps to wait longer.
I will also check if force reconnect is still executed every 24hours by the ISP.
So I will disable the setting to do it between 3 and 4 o'Clock in the night which is set in my router.
Let's see.

Thanks for your help!

**Comment by GammaC0de** [comment]
Good luck 👍 .

**Comment by StefanRu1** [comment]
Just to document what has worked for me:
So ISPs in Germany still do a force reconnect every 24 hours.
This reconnects destroys any running download.

My solution was to enable reconnect feature in pyload.
Since pyload then reconnects when necessary and this is mostly more often than 24h, it is no problem anymore, but you have to live with reconnecting throughout the day.

For me, this is fine and works perfectly.

Thanks and best regards,
Stefan
