### ISSUE TITLE
About Disabled, please upgrade, check out api.real-debrid.com

### ISSUE THREAD

**Issue by speedecho** [pyload/pyload#4071]
### Description

The RealdebridCom API has been officially updated and the current API address is no longer available.

https://real-debrid.com/ajax/login.php?user=%s&pass=%s

### Debug log

```
github.com/pyload/pyload/files/4406037/GetRealdebridToken.zip
13.01.2022 14:09:47 ERROR     ACCOUNT RealdebridCom: Could not login user `pau*******` | Login handshake has failed
13.01.2022 14:09:50 ERROR     ACCOUNT RealdebridCom: Could not load hoster list - invalid account, deactivating
13.01.2022 14:09:50 INFO      ACCOUNT RealdebridCom: Reverting back to default hosters
```

**Comment by GammaC0de** [comment]
This works fine for me,
Is this a new installation?
Please refresh your pyLoad installation using the instruction in #3283 and then retry.

**Comment by GammaC0de** [comment]
Any news?

**Comment by GammaC0de** [comment]
No response, closing.
