### ISSUE TITLE
Plugin for WeTransfer

### ISSUE THREAD

**Issue by SMAW** [pyload/pyload#4072]
### Description

A plugin for downloading from WeTransfer would be great. Link to the website https://wetransfer.com/

### Sample resources

https://wetransfer.com/downloads/91b9c27868c1b0cfc6134beae33927db20220113133610/dc460f52ae5d3320df2a288785c86f8320220113133747/65f89b (Valid for only 7 days)

### Additional references

Currently when putting the link into pyload, it downloads the webpage.

**Comment by prime-optimal** [comment]
I know this is old, but just wanted to say thanks 🙏
