### ISSUE TITLE
Can't download from gdrive

### ISSUE THREAD

**Issue by yousefgunz** [pyload/pyload#4073]
I'm trying to download a folder from gdrive but I get "WARNING	Download is offline"

 I can download the files without pyload so I know the files are fine.
Also if I try to download from gdrive with the file link I get:

782	13.01.2022 22:25:22	ERROR	<<< UNCAUGHT EXCEPTION >>>
783	?	?	Traceback (most recent call last):
784	?	?	File "/media/sdo1/sephgunz/share/pyload/module/network/HTTPRequest.py", line 306, in write
785	?	?	raise Exception("Loaded Url exceeded limit")
786	?	?	Exception: Loaded Url exceeded limit
787	13.01.2022 22:25:22	ERROR	pycurl error 23: Failed writing body (0 != 3613)
788	13.01.2022 22:25:22	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: 1K3u8RqzWmGnpJhM_rn2KgaVTseTP7_02 (pid:5)
789	13.01.2022 22:25:22	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
Please refresh your pyLoad installation using the instruction in #3283 and then retry.

**Comment by yousefgunz** [comment]
I'm still getting the errors

**Comment by GammaC0de** [comment]
1. Please provide a sample  URL.
2. Please enable debug mode within pyload's configuration, retry the download and then post the log from the beginning of the download until it fails.

**Comment by GammaC0de** [comment]
No response, closing.
