### ISSUE TITLE
Difference between pyload-ng and pyload

### ISSUE THREAD

**Issue by LazyGeniusMan** [pyload/pyload#4078]
### Question

Hi, I want to try pyload, but I dont even fully understand what's the difference between pyload-ng and pyload. I tried to look for the difference in readme and wiki but the only information that I got is pyload-ng is rewrite of pyload using python 3 instead of python 2? is that correct?

Is there any features differences ? peformance differences ? etc ?

What's pros and cons of using pyload-ng instead of pyload and vice versa?

**Comment by GammaC0de** [comment]
> I got is pyload-ng is rewrite of pyload using python 3 instead of python 2? is that correct?

Exactly

> Is there any features differences ? peformance differences ? etc ? 

Not really.

**Comment by LazyGeniusMan** [comment]
> Exactly

does pyload development outside of plugins stopped since now there is pyload-ng? or there will be 2 project even after pyload-ng have stable release?

**Comment by GammaC0de** [comment]
The plan is to move on someday but currently they are both actively in development. 
***@***.***> wrote:   



Exactly


does pyload development outside of plugins stopped since now there is pyload-ng? or there will be 2 project even after pyload-ng have stable release?
