### ISSUE TITLE
Do you have a donation link?

### ISSUE THREAD

**Issue by aptalca** [pyload/pyload#4080]
Do you guys have a donation link?

I'm with linuxserver.io and we are making some changes to the pyLoad images we publish.

Since the old stable pyLoad is py2, which has been EOL for some time, we decided to deprecate that image (the alpine 3.11 baseimage we use for that just went EOL). The `pyLoad Next` images we are publishing at the `ng` tag will be moved to a new repo: https://github.com/linuxserver/docker-pyload-ng because I don't believe there is an upgrade path from old stable to ng. We didn't want to break old stable users' setups by force upgrading them to ng.

While we're at it, we'd like to add your donation link (if you have one) to the container logs as well as the Github Sponsors button in our repo.

Also, one more question, does pyLoad ng make use of the system unrar binary? Because alpine 3.15 dropped their unrar package due to license issues (they now consider it non-free) so we resorted to compiling unrar from source. But I'm not sure if it's required by pyLoad ng.

Thanks.

PS. The new repo will push the pypi packages at the `latest` tag and git commits from your develop branch at the `develop` tag.

**Comment by GammaC0de** [comment]
> While we're at it, we'd like to add your donation link (if you have one) to the container logs as well as the Github Sponsors button in our repo.

Thanks, my paypal: `https://PayPal.Me/nitzo2001/0usd`

> Also, one more question, does pyLoad ng make use of the system unrar binary? Because alpine 3.15 dropped their unrar package due to license issues (they now consider it non-free) so we resorted to compiling unrar from source. But I'm not sure if it's required by pyLoad ng.

pyLoad detects which unpackers are installed on the system, it can work with unrar and 7zip.
In fact, pyLoad works better with 7zip than unrar.

**Comment by aptalca** [comment]
ah, great to know. Thanks

**Comment by GammaC0de** [comment]
Closing 👍
