### ISSUE TITLE
ExtractArchive.py does not call `archive.list` with the correct password

### ISSUE THREAD

**Issue by dkales** [pyload/pyload#4083]
### Description

In `ExtractArchive.py` `archive.list()` gets called without a password,
https://github.com/pyload/pyload/blob/0b7b6eec6eb35cb755f16a77646e4c6775d49dc5/src/pyload/plugins/addons/ExtractArchive.py#L516

which raises an exception in 
https://github.com/pyload/pyload/blob/0b7b6eec6eb35cb755f16a77646e4c6775d49dc5/src/pyload/plugins/extractors/SevenZip.py#L189

since the output of 7z for this operation is
```
Listing archive: archive.part01.rar


ERROR: archive.part01.rar : Can not open encrypted archive. Wrong password?
```

Based on my quick testing, passing the correct password with `archive.list(password)` (and potentially updating the password variable with the discovered password from the password list before that) instead has the desired effect and lets the post-extraction process continue as normal and delete files and change permissions as intended.

### Debug log

Note the call to `7z l` using an empty password.
```
20171 | 2022-01-30 12:53:30 | DEBUG | pyload | ADDON ExtractArchive: Extracting using password: password
-- | -- | -- | -- | --
20172 | 2022-01-30 12:53:30 | DEBUG | pyload | EXTRACTOR SevenZip: EXECUTE 7z x -scsUTF-8 -sccUTF-8 -bso0 -bsp1 -aos -xr!*.nfo -xr!*.DS_Store -xr!index.dat -xr!thumb.db -ppassword -o/downloads/ /downloads/archive.part01.rar
20173 | 2022-01-30 12:54:14 | DEBUG | pyload | EXTRACTOR SevenZip: EXECUTE 7z l -scsUTF-8 -sccUTF-8 -bso0 -bsp1 -aos -xr!*.nfo -xr!*.DS_Store -xr!index.dat -xr!thumb.db -p- /downloads/archive.part01.rar
20174 | 2022-01-30 12:54:14 | ERROR | pyload | ADDON ExtractArchive: archive.part01.rar \| Archive error \| Cannot open file
20175 | ? | ? | ? | Traceback (most recent call last):
20176 | ? | ? | ? | File "/usr/lib/python3.9/site-packages/pyload/plugins/addons/ExtractArchive.py", line 516, in _extract
20177 | ? | ? | ? | extracted_files = archive.files or archive.list()
20178 | ? | ? | ? | File "/usr/lib/python3.9/site-packages/pyload/plugins/extractors/SevenZip.py", line 190, in list
20179 | ? | ? | ? | raise ArchiveError(self._("Cannot open file"))
```

# Other Info
I'm using the new [linuxserver/pyload-ng](https://github.com/linuxserver/docker-pyload-ng/) docker container, which is currently at version `0.5.0b2.dev11`.

**Comment by GammaC0de** [comment]
Sample URLs please

**Comment by dkales** [comment]
Here are some sample rar's, password=password:
```
test.rar
https://www36.zippyshare.com/v/LRSAwK5d/file.html
test2.rar
https://www36.zippyshare.com/v/DZTXs5kZ/file.html
```

test.rar uses header encryption as well as content encryption, while test2.rar only uses content encryption.
This means test.rar fails to list without the correct password, while test2.rar does list without the correct password.
