### ISSUE TITLE
Invalid syntax- I'm too stupid for this!!!

### ISSUE THREAD

**Issue by 2talll** [pyload/pyload#4085]
### Question

So I'm having all sorts of trouble getting this to work, and I'm about to give up. I've downloaded the windows version, python and ran the exe files for each. And that's about as far as I can get! I tried the "first start" and keep getting invalid syntax when putting the suggested file into Run, both in Python and the nurmal windows Run. I went into the DIST folder and tried to load the LOADGUI.exe filed but I get an error saying the GUI is not stable yet and I should use the webinterface. I have no idea where the webinterface is!!! After I close that error i either get another error saying it cant connect to host or the client opens but says "Not Responding" forever. Guess I'm stuck downloading dumb Filejoker files with my internet browser.

**Comment by GammaC0de** [comment]
* Just run `pyLoadCore.exe` (not the one inside the dist directory), it will run the first time configuration setup.
* When finished the configuration setup,  run `pyLoadCore.exe`  again and leave it running.
* Browse to `http://<IP_OF_PYLOAD>:8000`

**Comment by 2talll** [comment]
I copied and pasted pyLoadCore.exe into the RUN box and it says it can't find the file. Even though I can see it pyload folder from the download.

Also, how do I find the IP of Pyload?
I really hate stupid Filejoker for maker me try to figure out all this stuff when I'm totally happy with my other download manager.

**Comment by GammaC0de** [comment]
> I copied and pasted pyLoadCore.exe into the RUN box and it says it can't find the file. Even though I can see it pyload folder from the download.

You have to unpack all the files from the zip not just pyLoadCore.exe and then run pyLoadCore.exe

>Also, how do I find the IP of Pyload?

if pyLoadCore.exe and the browser are on the same machine you can do http://127.0.0.1:8000/

>I really hate stupid Filejoker for maker me try to figure out all this stuff when I'm totally happy with my other download manager.

May I ask what is your other download manager, it does not support Filejoker ?

**Comment by 2talll** [comment]
I did unpack everything, run still says it cant find it.
I Quit! I finally get the webinterface to load and it won't take my username and password!!!!!
JDownloader... Filejoker changed the captchas they use and they aren't compatible.
Can you suggest an EASY download manager that will work with Filejoker because obviously I give up with this.

**Comment by GammaC0de** [comment]
> I Quit! I finally get the webinterface to load and it won't take my username and password!!!!!

run setup.exe and choose "user managment"

**Comment by 2talll** [comment]
OK, got that finally. Now I go to add a URL to download and it says failed global name image is not defined

**Comment by GammaC0de** [comment]
Checking..

**Comment by GammaC0de** [comment]
Unpack [this ](https://github.com/pyload/pyload/files/7973942/PIL.zip) file into the `dist` folder overwriting existing files then stop and start pyload and retry.

**Comment by 2talll** [comment]
Now I get this error: failed 'NoneType' object has no attribute 'XFileSharing' 0.00 B XFileSharing    

Could you just suggest another download manager that can work with Filejoker that isn"t so complicated?

**Comment by 2talll** [comment]
I did that and now it says "failed nonetype object has no attirbute "filejokernet"

**Comment by GammaC0de** [comment]
Here is a [working version](https://www81.zippyshare.com/v/CqLrS9wz/file.html)

**Comment by 2talll** [comment]
That seems to work! Thank you!!

Is there a way for the copied URL to automatically go into pyload without copying and pasting, like with other download managers

**Comment by GammaC0de** [comment]
Great! 👍 

> Is there a way for the copied URL to automatically go into pyload without copying and pasting, like with other download managers

Pyload uses the client-server approach where the client run on your browser.
The browser imposes security restriction like not being able to post anything.
This is why clipboard monitoring is not possible with pyload 😔

Alternatively pyload supports clicknload or https://github.com/RemiRigal/Yape

**Comment by 2talll** [comment]
Thanks. Looks like I’m still stuck using the web browser or searching for a new download manager. This isn’t much faster download speed wise and the wait time is longer. JDownloader is capable of downloading a few files before the wait time, web browser wait time is 3-4 hours between larger files but this has a 5-6 hour wait when I only downloaded a 23kb file.
