### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by SweetthD3ViL** [pyload/pyload#4087]
Hello all,

Long time user of pyLoad, so thank you for the work, time and effort! I run pyLoad on my home server, mainly use for media with Plex & Jellyfin (for the music), the server is not up all the time and is mainly on in the evening to use Plex. However, when collect links to download it is mainly during the day. 

Is there a plugin that will collects links from an online place such as an email account, or google drive docs or something similar? 
So the idea, is that I can add those links whenever during the day, and when the server get started in the evening it will check if there is any links to download? 

I hope that makes sense? 

Also, is there any news with the issues from Alldebrid links failing? (https://github.com/pyload/pyload/issues/3995)

**Comment by GammaC0de** [comment]
Maybe you Can use the HotFolder plugin.

If that not suitable for you, you can write your own pyload plugin that upon startup or periodically   checks the online place and the uses the `add_package` API to add links

I will take a look at #3995 again.

**Comment by SweetthD3ViL** [comment]
Right,

Thank you for your prompt reply. That's excellent!

Surely I could use that plugin to watch a local file, that could update from a Google drive doc using a script running on start up?

**Comment by GammaC0de** [comment]
The HotFolder plugin reads text file that you put on the hot folder and creates packages from them.
It is up to you to put content on the folder.

**Comment by GammaC0de** [comment]
Closing.
