### ISSUE TITLE
pyload 0.5 on Dietpi webui issue

### ISSUE THREAD

**Issue by gl86** [pyload/pyload#4091]
### Question

Hi i have installed pyload on a Dietpi with Python 3 installed.  Pyload can be started but webui is not accessable.  What do i wrongM
thanks

**Comment by GammaC0de** [comment]
- How exactly did you installed pyload?

- Run `python3 -m pyload` and post the output here.

**Comment by GammaC0de** [comment]
Have you succeeded to install?

**Comment by GammaC0de** [comment]
No response, closing.
