### ISSUE TITLE
UlozTo plugin: "failed a bytes-like object is required, not 'str'" error when assembling downloaded chunks

### ISSUE THREAD

**Issue by tkafka** [pyload/pyload#4093]
### Description
After downloading a large file (8 GB) from UlozTo with a premium account, a message `failed a bytes-like object is required, not 'str'` appears under each file in Queue tab.

The chunks eventually got assembled into a final file, so that seems OK.

A file name of downloaded file was unusual - `Something - eng /1080p, DTS 5.1/ favic@.mkv` and seems to have confused pyLoad into saving it as `favic@.mkv` instead (which creates a problem when multiple downloaded files end with `/ favic@.mkv`). 

### Debug log
I don't have one, I am using `lscr.io/linuxserver/pyload-ng:latest` docker.

```

```

### Screenshots
Here is how it looks like.
<img width="532" alt="Screenshot 2022-02-10 at 20 40 52" src="https://user-images.githubusercontent.com/876717/153484253-bcb09793-7d4f-40fa-9868-844ddec845b4.png">

**Comment by GammaC0de** [comment]
1. Please provide the URLs.
2. Please try `lscr.io/linuxserver/pyload-ng:develop`

**Comment by GammaC0de** [comment]
Can you provide URLs?

**Comment by maxer456** [comment]
Hello, I've recently encountered the same issue. Link to an example file:
https://ulozto.net/file/tatq5iCIlsPe/dna-test-jpg#!ZGIyMQR2ZwqwAwH4MJRkAJLmZwp2ZzIDp2k1Z2ykYay0MmAxAj==
Generated debug archive: [debug_UlozTo_2022-02-20_11-24-42.zip](https://github.com/pyload/pyload/files/8103946/debug_UlozTo_2022-02-20_11-24-42.zip)

I'm currently using the `latest` tagged image from `lscr.io/linuxserver/pyload-ng`. I may try the `develop` tag later but looking through the code that's mentioned in the trace
```
2022-02-20 11:24:42 | WARNING | pyload | Download failed: DNA TEST.jpg \| a bytes-like object is required, not 'str'
-- | -- | -- | --
169 | ? | ? | ? | Traceback (most recent call last):
170 | ? | ? | ? | File "/usr/lib/python3.9/site-packages/pyload/core/threads/download_thread.py", line 56, in run
171 | ? | ? | ? | pyfile.plugin.preprocessing(self)
172 | ? | ? | ? | File "/usr/lib/python3.9/site-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
173 | ? | ? | ? | return self._process(*args, **kwargs)
174 | ? | ? | ? | File "/usr/lib/python3.9/site-packages/pyload/plugins/base/downloader.py", line 106, in _process
175 | ? | ? | ? | self._check_download()
176 | ? | ? | ? | File "/usr/lib/python3.9/site-packages/pyload/plugins/base/simple_downloader.py", line 290, in _check_download
177 | ? | ? | ? | self.check_download()
178 | ? | ? | ? | File "/usr/lib/python3.9/site-packages/pyload/plugins/downloaders/UlozTo.py", line 247, in check_download
179 | ? | ? | ? | check = self.scan_download(
180 | ? | ? | ? | File "/usr/lib/python3.9/site-packages/pyload/plugins/base/downloader.py", line 368, in scan_download
181 | ? | ? | ? | if rule in content:
182 | ? | ? | ? | TypeError: a bytes-like object is required, not 'str'
```

the UlozTo plugin uses [scan_download](https://github.com/pyload/pyload/blob/c23da07ba14fdc3b8d2e4c6f717f4837840aba24/src/pyload/plugins/base/downloader.py#L347) function which checks for
```python
...
        with open(dl_file, mode="rb") as fp:
            content = fp.read(read_size)
...
        for name, rule in rules.items():
            if isinstance(rule, str):
                if rule in content:
                    return name
...
```
but `content` is always loaded as bytes and `rule` is checked to be a string.
