### ISSUE TITLE
Create subfolder for package not in archive

### ISSUE THREAD

**Issue by Vandaahl** [pyload/pyload#4099]
I have setup the ExtractArchive plugin to create a subfolder for each package. Can the same be done for files not in an archive?

For example, let's say a file is downloaded to /downloads/nameofpackage/goodmovie.mkv. It was not in an archive. Can it automatically be placed in /downloads/nameofpackage/goodmovie/goodmovie.mkv?

**Comment by GammaC0de** [comment]
You can use the `ExternalScripts` plugin and write a script that does whatever you want on a `download_finished` event.

**Comment by Vandaahl** [comment]
> You can use the `ExternalScripts` plugin and write a script that does whatever you want on a `download_finished` event.

Yes I tried that. I wrote a bash script that moves the package folder to a folder named after the download file. However, if a package has 2 files, this creates 2 separate folders, but I want them both in the same folder.

**Comment by GammaC0de** [comment]
So use `package_finished` event instead.

**Comment by Vandaahl** [comment]
That was my conclusion as well ;) However, so far it does not work. Here's my test script:

```
#!/bin/sh
# Path of the extracted package, e.g. "/downloads/Movie name"
olddir=$3 
# Extract the path of the download folder from the olddir by removing the last segment"
destdir=$(echo ${olddir%/*})
# Search the download folder for certain filetypes and store the first result (head -1) in a variable
filename=$(find . -maxdepth 1 -type f -iname '*.mkv' -or -iname '*.mp4' | head -1)
echo "$filename" > "$olddir/filename.txt"
```

So I'm trying to find a file with a certain extension that was downloaded and save it to a text file to confirm the script is working up to that point. However the generated text file is empty so the 'find' command does not seem to find any files. If I run the find command manually it does echo a filename so I'm not sure why this does not work.

**Comment by Vandaahl** [comment]
Forgot to cd into the download dir before doing the 'find' command, whoops. Here's a working script placed in package_finished dir:

```
#!/bin/sh
# Path of the extracted package, e.g. "/downloads/Night flier"
olddir=$3
# Extract the path of the download folder from the olddir by removing the last segment
destdir=$(echo ${olddir%/*})
cd "$olddir"
# Search the download folder for certain filetypes and store the first result (head -1) in a variable
filename=$(find . -maxdepth 1 -type f -iname '*.mkv' -or -iname '*.mp4' | head -1)
if ! [ -z "$filename" ]; then
    newdirname=$(echo "${filename%.*}")
    mv "$olddir" "$destdir/$newdirname"
fi
```
