### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by styxxx** [pyload/pyload#4103]
### Description
pyLoad fails to start with error message "ImportError: cannot import name 'soft_unicode' from 'markupsafe'". 

### Reason
`soft_unicode` was removed from markupsafe. See: https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

> Remove soft_unicode, which was previously deprecated. Use soft_str instead. [#261](https://github.com/pallets/markupsafe/pull/261)

### Solution
Use `soft_str` in code.

### Workaround for users
Installing markupsafe 2.0.1 until the bug is fixed: ` python -m pip install markupsafe==2.0.1`

**Comment by GammaC0de** [comment]
- Please specify what OS are you using.
- Please post the trace log

**Comment by aptalca** [comment]
Likely upstream issue:
https://github.com/pallets/markupsafe/issues/284

Related downstream issue:
https://github.com/linuxserver/docker-pyload-ng/issues/10

**Comment by GammaC0de** [comment]
This is why we [upgraded Flask to v2.0](https://github.com/pyload/pyload/commit/8a4352eaa91cc153f6ee2a77cd608ed318b89367) which uses Jinja2-3.0.3 and MarkupSafe-2.1.0.
Also I have [updated Flask-Themes2 to v1.0](https://github.com/pyload/pyload/commit/eec646fccd5a2227fee47f53bf9a276fb665380f), please tell me if is solves the issue.

**Comment by aptalca** [comment]
I believe our ci just pushed a new build with the latest commit to develop. I'll ask the users to test that and report.

Thanks

**Comment by aptalca** [comment]
@GammaC0de it looks like our `develop` tag which builds the latest commit from your develop branch works fine: https://github.com/linuxserver/docker-pyload-ng/issues/10#issuecomment-1053717289

When you merge that to master and push to pypi, our `latest` tag should be fixed as well.

Thanks

**Comment by GammaC0de** [comment]
Done.
