### ISSUE TITLE
Nitroflare Account doesnt work

### ISSUE THREAD

**Issue by smschumacher** [pyload/pyload#4108]
Hi,

I just bought a Nitroflare account in order to use it with pyload-ng. Be advised that I used Nitroflare in combination with pyload in the past and it always worked. Now I only get this. (The last line, meaning no information about the validity of my account at all) Please tell me where to send my account data so someone from development can check out the problem.

None | None |   | not valid | no | not available | not available |  

Thanks in Advance
Stefan

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by smschumacher** [comment]
Sent it again just a minute ago.

**Comment by GammaC0de** [comment]
Got it.

**Comment by GammaC0de** [comment]
Issue resolved,
Username for the account should be your email.

Please test.

**Comment by smschumacher** [comment]
Thank you for your help. With my email as username - and not the user id -
the account is recognized. Why Nitroflare assigns a user id at all when
your email is used for logging in I do not entirely understand.

Yours sincerely
Stefan

Am Sa., 12. März 2022 um 23:09 Uhr schrieb GammaC0de <
***@***.***>:

**Comment by GammaC0de** [comment]
👍

**Comment by smschumacher** [comment]
Great. By the way, I just updated to the latest development version and the
problem still persists, so I guess Nitroflare changed something in their
web interface.
I also couldn't delete the defect account anymore, had to do it manually
from settings/accounts.cfg. The username and password were in the
Nitroflare section which
is more than which is shown by the web interface

Bye for now
Stefan

Am Fr., 11. März 2022 um 22:58 Uhr schrieb GammaC0de <
***@***.***>:
