### ISSUE TITLE
FileStoreTo Plugin unstable?

### ISSUE THREAD

**Issue by timma82** [pyload/pyload#4113]
Hi everyone,

I habe since this week problems with the FileStoreTo plugin. All downloads are failing from that hoster. Is there actually a issue? 

WARNING | HOSTER FileStoreTo[64]: Plugin may be unstable
WARNING | HOSTER FileStoreTo[65]: Free download failed \| DID pattern not found

I tried it with pyLoad version 0.4.20 and 0.5.0. I didnt do any changes on my settings for the last months 

Best regards
timma82

**Comment by GammaC0de** [comment]
Sample URL please.

**Comment by timma82** [comment]
I just tried to download the file directly with my browser.
The response of the website: "There are no download slots available for free users".

The warning message "Free download failed" means then there are no download slots available?

http://filestore.to/?d=7BJ7UJYJRO

**Comment by GammaC0de** [comment]
It means that the file cannot be downloaded without a premium user

**Comment by MaluNoPeleke** [comment]
Does the Restart Failed Plugin detect this as failed and restart those downloads in these cases?

**Comment by GammaC0de** [comment]
@MaluNoPeleke I cannot download even with a browser.
When I tried to upload a file and then download it I get "File not ready yet" 😕

**Comment by MaluNoPeleke** [comment]
Yes, I have the same problem but I mean: does the "Restart Failed" plugin detect these cases as fails and restarts them?

**Comment by GammaC0de** [comment]
The indeed fail but you cannot download even with your browser so this is pointless.

**Comment by MaluNoPeleke** [comment]
I thought that a free download slot might become available later and therefore it should be tried again and again (which manually just worked with one file)

**Comment by GammaC0de** [comment]
I haven't downloaded anything  yet and I got the same message 😕

**Comment by GammaC0de** [comment]
I cannot download even a file I uploaded, maybe a temporary issue with FileStore.to

**Comment by timma82** [comment]
Today I was able to download 2-3 files from FileStoreTo (as a free user) with pyload. 

So I think it would be a great enhancement (like mentioned from @MaluNoPeleke) for the FileStoreTo plugin if it could start the downloads after a random time if the download "failed" to check if there are available slots for free users to start the download again.

This problem exists already since 7 days, so I dont think its just a temporally issue from FileStoreTo.

**Comment by timma82** [comment]
> Yes, I have the same problem but I mean: does the "Restart Failed" plugin detect these cases as fails and restarts them?

Yes it does.

**Comment by GammaC0de** [comment]
I cannot download anything, even with my browser.
I cannot download even my own uploaded file.

> Its seems like the jdownloader community is facing the same problem
https://board.jdownloader.org/showthread.php?t=89521

I cannot read German,
Is there any solution there?

Meanwhile I treat this as temp. offline.

**Comment by timma82** [comment]
@GammaC0de 
FileStoreTo is working again like before. Guess it was really just temporarly like you said.

I have one question about the change you did. If it is treated as temp. offline will it be restarted by the RestartFailed plugin?

**Comment by GammaC0de** [comment]
> If it is treated as temp. offline will it be restarted by the RestartFailed plugin?

Yes.

Closing this issue.

**Comment by MaluNoPeleke** [comment]
The problem still exists:
![image](https://user-images.githubusercontent.com/1446541/164792598-8475166c-5dbc-4681-b318-3c3bf7ac576d.png)
![image](https://user-images.githubusercontent.com/1446541/164792627-98d34a12-4b34-49ea-a6a3-ed384720c10e.png)
Any workaround available`?

**Comment by GammaC0de** [comment]
Are you able to download with a plain browser?

**Comment by MaluNoPeleke** [comment]
20 Seconds should be fine I guess

**Comment by GammaC0de** [comment]
added retry on no free slot (delay and attempts are added as plugin parameters because I  don't want to hammer the server)
