### ISSUE TITLE
FastShareCz plugin won't use premium account

### ISSUE THREAD

**Issue by Tessarai** [pyload/pyload#4117]
### Description

Even though I have Premium account on Fastshare, Pyload insists that it is not premium and don't want to use it. If I try to force it with direct downloads, Pyload won't find them in the links and start using free mode. If I force it with only Premium, it will still ignore premium and start with free instead. I had those problems with Stable version 0.4.20 so I migrated to Next hoping it will be fixed.
I don't have any credit on the premium account, only unlimited download, but I think it worked with credit some long time ago on Stable, not sure now ...
I have no problem lending Premium account for testing if it will help with this :)

### Debug log

During startup - log in of the accounts
<html>
<body>

8511 | 2022-03-25 20:43:57 | INFO | pyload | ACCOUNT FastshareCz: Adding user `vcg*******`...
-- | -- | -- | -- | --
8512 | 2022-03-25 20:43:57 | DEBUG | pyload | ACCOUNT FastshareCz: Reached login timeout for user `vcg****`
8513 | 2022-03-25 20:43:57 | INFO | pyload | ACCOUNT FastshareCz: Login user `vcg****`...
8514 | 2022-03-25 20:43:57 | DEBUG | pyload | ACCOUNT FastshareCz: LOAD URL https://www.fastshare.cz/login \| get={} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
8515 | 2022-03-25 20:43:57 | DEBUG | pyload | ACCOUNT FastshareCz: LOAD URL https://www.fastshare.cz/sql.php \| get={} \| post={'login': 'vcg****', 'heslo': '**********'} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
8516 | 2022-03-25 20:43:57 | INFO | pyload | ACCOUNT FastshareCz: Grabbing account info for user `vcg****`...
8517 | 2022-03-25 20:43:57 | DEBUG | pyload | ACCOUNT FastshareCz: LOAD URL https://www.fastshare.cz/user \| get={} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
8518 | 2022-03-25 20:43:57 | DEBUG | pyload | ACCOUNT FastshareCz: Account info for user `vcg****`: {'login': {'password': '**********', 'timestamp': 1648237437.4960058, 'valid': True}, 'data': {'login': 'vcg****', 'maxtraffic': None, 'options': {'limit_dl': ['0']}, 'plugin': <Account FastshareCz>, 'premium': False, 'trafficleft': None, 'type': 'FastshareCz', 'validuntil': -1}}
8519 | 2022-03-25 20:43:57 | INFO | pyload | Activating plugins...

</body>
</html>

Download
<html>
<body>

8531 | 2022-03-25 20:49:20 | INFO | pyload | Added package Windows containing 1 links
-- | -- | -- | -- | --
8532 | 2022-03-25 20:49:20 | INFO | pyload | Download starts: https://fastshare.cz/19601547/en-us-windows-10-enterprise-ltsc-2021-x86-dvd-9f4aa95f.iso
8533 | 2022-03-25 20:49:20 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_preparing`
8534 | 2022-03-25 20:49:20 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
8535 | 2022-03-25 20:49:20 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting maximum redirections to 10
8536 | 2022-03-25 20:49:20 | DEBUG | pyload | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
8537 | 2022-03-25 20:49:20 | DEBUG | pyload | DOWNLOADER FastshareCz[67]: Plugin version: 0.45
8538 | 2022-03-25 20:49:20 | DEBUG | pyload | DOWNLOADER FastshareCz[67]: Plugin status: testing
8539 | 2022-03-25 20:49:20 | WARNING | pyload | DOWNLOADER FastshareCz[67]: Plugin may be unstable
8540 | 2022-03-25 20:49:20 | INFO | pyload | ACCOUNT FastshareCz: Grabbing account info for user `vcg****`...
8541 | 2022-03-25 20:49:20 | DEBUG | pyload | ACCOUNT FastshareCz: LOAD URL https://www.fastshare.cz/user \| get={} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
8542 | 2022-03-25 20:49:20 | DEBUG | pyload | ACCOUNT FastshareCz: Account info for user `vcg****`: {'login': {'password': '**********', 'timestamp': 1648237437.4960058, 'valid': True}, 'data': {'login': 'vcg****', 'maxtraffic': None, 'options': {'limit_dl': ['0']}, 'plugin': <Account FastshareCz>, 'premium': False, 'trafficleft': None, 'type': 'FastshareCz', 'validuntil': -1}}
8543 | 2022-03-25 20:49:20 | INFO | pyload | DOWNLOADER FastshareCz[67]: Processing url: https://fastshare.cz/19601547/en-us-windows-10-enterprise-ltsc-2021-x86-dvd-9f4aa95f.iso
8544 | 2022-03-25 20:49:20 | INFO | pyload | DOWNLOADER FastshareCz[67]: Looking for direct download link...
8545 | 2022-03-25 20:49:20 | DEBUG | pyload | DOWNLOADER FastshareCz[67]: LOAD URL https://fastshare.cz/19601547/en-us-windows-10-enterprise-ltsc-2021-x86-dvd-9f4aa95f.iso \| get={} \| post={} \| ref=True \| cookies=True \| just_header=True \| decode=True \| multipart=False \| redirect=True \| req=None
8546 | 2022-03-25 20:49:20 | INFO | pyload | DOWNLOADER FastshareCz[67]: Direct download link not found
8547 | 2022-03-25 20:49:20 | DEBUG | pyload | DOWNLOADER FastshareCz[67]: LOAD URL https://fastshare.cz/19601547/en-us-windows-10-enterprise-ltsc-2021-x86-dvd-9f4aa95f.iso \| get={} \| post={} \| ref=False \| cookies=[('fastshare.cz', 'lang', 'en')] \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
8548 | 2022-03-25 20:49:43 | INFO | pyload | DOWNLOADER FastshareCz[67]: Grabbing link info...
8549 | 2022-03-25 20:49:43 | DEBUG | pyload | DOWNLOADER FastshareCz[67]: Link info: {'name': 'en-us-windows-10-enterprise-ltsc-2021-x86-dvd-9f4aa95f.iso', 'hash': {}, 'pattern': {}, 'size': 0, 'status': 2, 'url': 'https://fastshare.cz/19601547/en-us-windows-10-enterprise-ltsc-2021-x86-dvd-9f4aa95f.iso'}
8550 | 2022-03-25 20:49:43 | DEBUG | pyload | DOWNLOADER FastshareCz[67]: Previous link info: {}
8551 | 2022-03-25 20:49:43 | INFO | pyload | DOWNLOADER FastshareCz[67]: Link name: en-us-windows-10-enterprise-ltsc-2021-x86-dvd-9f4aa95f.iso
8552 | 2022-03-25 20:49:43 | INFO | pyload | DOWNLOADER FastshareCz[67]: Link size: N/D
8553 | 2022-03-25 20:49:43 | INFO | pyload | DOWNLOADER FastshareCz[67]: Link status: online
8554 | 2022-03-25 20:49:43 | INFO | pyload | DOWNLOADER FastshareCz[67]: Processing as free download...
8555 | 2022-03-25 20:49:43 | INFO | pyload | DOWNLOADER FastshareCz[67]: Downloading file...
8556 | 2022-03-25 20:49:43 | DEBUG | pyload | DOWNLOADER FastshareCz[67]: DOWNLOAD URL https://fastshare.cz/free/?lang=en&u=19601547&r=aHR0cHM6Ly9mYXN0c2hhcmUuY3ovMTk2MDE1NDcvZW4tdXMtd2luZG93cy0xMC1lbnRlcnByaXNlLWx0c2MtMjAyMS14ODYtZHZkLTlmNGFhOTVmLmlzbw== \| get={} \| post={} \| ref=True \| cookies=True \| disposition=True \| resume=None \| chunks=None
8557 | 2022-03-25 20:49:44 | DEBUG | pyload | Content-Disposition: en-us_windows_10_enterprise_ltsc_2021_x86_dvd_9f4aa95f.iso

</body>
</html>

### Additional references

Python -  Version:3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
OS Platform - posix linux Linux home-pyload 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64
Version - 0.5.0
Installation Folder - /usr/local/lib/python3.8/dist-packages/pyload
Config Folder - /home/pyload-files/ConfigurationLanguage:en

### Screenshots

Logged account - others are fine, only Fastshare is acting up ...
![accounts](https://user-images.githubusercontent.com/102386237/160193491-6f5ad817-8578-4c39-b24e-c2f1708e85e3.jpg)

Account screen on Fastshare (only unlimited download, no credit)
![fastshare](https://user-images.githubusercontent.com/102386237/160193696-3ff38a74-6f06-4045-afce-7d19b507ed26.jpg)

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by Tessarai** [comment]
Done, you should have it in your Inbox
