### ISSUE TITLE
Feature request - PushOver settings

### ISSUE THREAD

**Issue by flexyboooy** [pyload/pyload#4118]
I noticed a minor issue:

I have setup the PushOver plugin to let me know when there are CAPTCHA requests waiting and I would like to receive notifications for these events exclusively. But I also get "All Downloads Processed" messages.

The way I understand it, the all_downloads_processed event triggers notifier.py and thus a message gets sent via pushover as well, but there is no setting available in the the PushOver.py plugin for this type of event.

Would adding a

``` ("all_downloads_processed", "bool", "Notify all dowloads processed", False),```

to the PushOver.py plugins config segment be enough to allow suppressing these messages, or would it require additional work?

**Comment by GammaC0de** [comment]
According to [notifier.py#L105](https://github.com/pyload/pyload/blob/main/src/pyload/plugins/base/notifier.py#L105), you should always get "All downloads processed" notification.

**Comment by flexyboooy** [comment]
Ah, thanks.

So the def for all_downloads_processed would have to be changed to how it is for i.e. download_failed.

Any chance that is ever going to happen? I say more config options -> good.

**Comment by GammaC0de** [comment]
Are you are asking for config options to enable/disable`all_downloads_processed` and `all_downloads_finished` notifications?

I could not really understand:
> So the def for all_downloads_processed would have to be changed to how it is for i.e. download_failed.

**Comment by flexyboooy** [comment]
I guess so, if that is what is needed to be able to get the same options for the pushover plugin.

If I read the code right (I don't really speak Python), [notifier.py#L105](https://github.com/pyload/pyload/blob/main/src/pyload/plugins/base/notifier.py#L105) does not implement the option, but e.g. [notifier.py#L81](https://github.com/pyload/pyload/blob/main/src/pyload/plugins/base/notifier.py#L81) does. Should be a simple change in notifier.py as well as in the pushover plugin, right?

**Comment by flexyboooy** [comment]
Alternatively, a `scripts/captcha_task` directory to put scripts in would be quite useful as well (and would solve at least my specific problem well enough).

**Comment by flexyboooy** [comment]
Thank you! :)
