### ISSUE TITLE
addPackage - All files are in queue, not even download

### ISSUE THREAD

**Issue by SuatNguyen** [pyload/pyload#4119]
### Question

The following code is used on my terminal

curl -c cookie.txt -d "username=xxx&password=yyy" http://localhost:8000/api/login/

curl -b cookie.txt "http://localhost:8000/api/addPackage?name=%22test1%22&links=%22https://www.fshare.vn/file/8JS2LMYSQ43S%22"

The file is ended up in queue, not even download. I have tested various hosts, same issue.

If I add the link manually on pyload UI, it works. The file will be downloaded. But if I use command line, all files will be in queue, not even download.

So, why does it not download?

**Comment by GammaC0de** [comment]
This is how it should be done:
```
curl -c cookie.txt -d "username=xxx&password=yyy" http://localhost:8000/api/login
curl -b cookie.txt "http://localhost:8000/api/addPackage?name=%5B%22https://www.fshare.vn/file/8JS2LMYSQ43S%22"%5D"
```
Please notice the %5B %5D inside the request.

Also, please make sure you are using the latest stable branch or the latest develop branch in case you are using pyload-ng.

**Comment by SuatNguyen** [comment]
Thanks so much. It works. %5B %5D were missing.

`curl -b cookie.txt "http://localhost:8000/api/addPackage?name=%22test1%22&links=%5B%22https://www.fshare.vn/file/8JS2LMYSQ43S%22%5D"`
