### ISSUE TITLE
Connection to debriders

### ISSUE THREAD

**Issue by SnowTechnical** [pyload/pyload#4121]
Hello all,
I can't connect my alldebrid or realdebrid account on pyload. I tried with my logins, my tokens or apikeys but impossible to connect.
Do you also have this problem?

Thank for help

**Comment by thomasbonsirven** [comment]
Hello,

I have the same problem, i want to login with my account, but the status is Invalid.
If i use the same login/password in alldebrid.com ( redirect in alldebrid.fr), is work.

Why ?

**Comment by GammaC0de** [comment]
@thomasbonsirven You should use [GetAlldebridTokenV4.py](https://github.com/pyload/pyload/files/4489732/GetAlldebridTokenV4.zip) to generate apikey.

Username for AlldebridCom should be your alldebrid.com username and password is apikey .
