### ISSUE TITLE
When signing in to my RealDebrid account on PyLoad I get "Status: Not Valid; Premium: no"

### ISSUE THREAD

**Issue by githubby11** [pyload/pyload#4133]
### Question

I have this issue on Docker for Synology NAS. I do have premium RealDebrid and I tried adding my Real Debrid Token API in the password section but it doesn't accept that. What could I be possibly doing wrong? I am using pyload-ng

**Comment by OptimusGREEN** [comment]
see [here](https://github.com/pyload/pyload/issues/3570)

**Comment by githubby11** [comment]
> see [here](https://github.com/pyload/pyload/issues/3570)

You have to authorize pyLoad using https://github.com/pyload/pyload/files/4406037/GetRealdebridToken.zip

How would I do that on Synology NAS with Docker?

**Comment by OptimusGREEN** [comment]
You can turn it on any device, it just prints the username and token to enter in pyload

**Comment by githubby11** [comment]
> You can turn it on any device, it just prints the username and token to enter in pyload

Thanks for the help so far. I understand what you mean now. I get this error when running it in Terminal in MacOS with this command: python3 GetRealdebridToken.py

<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Comment by githubby11** [comment]
> You can turn it on any device, it just prints the username and token to enter in pyload

I added my token and it's in RealDebrid and everything looks great so far except I still get that I don't have premium. Anything else I can try?

**Comment by gabotronix** [comment]
I had this issue too, but I am using a Docker image from linuxserver.io ([pyload-ng](https://fleet.linuxserver.io/image?name=linuxserver/pyload-ng)). The pyload-ng container from LinuxServer uses Alpine Linux and doesn't have the python binary installed. My workaround was to rebuild pyload-ng with python and GetRealdebridToken.py via Dockerfile and [docker-compose](https://github.com/docker/compose).

I am not familiar with the Synology ecosystem, but the steps below worked on my DIY NAS (OpenMediaVault 6, Debian 11 "bullseye"). Once the device/token has been added to RealDebrid, the credentials seem to persist across container rebuilds/recreates/restarts.

_Note: The steps below assumes that `docker-compose` is already installed and that the username logged in to SSH is `myuser` with UID of 1000 and GID of 1000._
```bash
myuser@NAS:~id
uid=1000(myuser) gid=1000(myuser) groups=1000(myuser)
```

**Sample Steps:**
1. Create the pyload-ng folder, install unzip if not yet installed, download GetRealdebridToken.zip. From this point on, the working directory will be `/home/myuser/pyload-ng`:
```bash
mkdir /home/myuser/pyload-ng
cd /home/myuser/pyload-ng
wget https://github.com/pyload/pyload/files/4406037/GetRealdebridToken.zip
apt update
apt install -y unzip
unzip GetRealdebridToken.zip
rm -f GetRealdebridToken.zip
```
2. Create the Dockerfile:
`nano Dockerfile`
```Dockerfile
FROM linuxserver/pyload-ng:latest

RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python

COPY GetRealdebridToken.py /home/GetRealdebridToken.py
```
3. Create the docker-compose file:
```bash
mkdir {config,downloads}
nano docker-compose.yml
```
```YAML
version: '3.6'
services:
    pyload:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: pyload-ng
      restart: unless-stopped
      ports:
          - 8000:8000
          - 9666:9666 #optional Click'n'Load port
      environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/New_York
      volumes:
          - /home/myuser/pyload/config:/config
          - /home/myuser/pyload/downloads:/downloads
```
4. Run docker-compose:
```bash
docker-compose up -d --force-recreate --build pyload
```
5. Check if pyload-ng is running:
```bash
docker-compose ps
NAME                COMMAND             SERVICE             STATUS              PORTS
pyload-ng           "/init"             pyload              running             0.0.0.0:9666->9666/tcp, :::9666->9666/tcp, 0.0.0.0:8000->8000/tcp, :::8000->8000/tcp
```
6. Run GetRealdebridToken.py
`docker exec -it pyload-ng python /home/GetRealdebridToken.py`
```
Please login to your real-debrid account, then go to https://real-debrid.com/device
and enter the code ABCDEF1G to authorize the request.

Waiting for authorization... 888

Your username for RealDebridCom: 1ABCDEFG2HIJK/x01xxx2x345xxx67x8x9012xx3x45x6789012345
Your Password for RealdebridCom: ABCD1EF2GHIJKLMNO3PQRSTUVWXYZABCDEFGHIJKLMN4OPQRS5TU
``` 
7. Enter provided `RealDebridCom` username and Password in pyload-ng web panel > Settings > Accounts.
