### ISSUE TITLE
Slow to combine chunks file?

### ISSUE THREAD

**Issue by SweetthD3ViL** [pyload/pyload#4135]
Hello all,

It seems to take longer than usual once the files have been downloaded to combine the chunks files together?

I changed pyload to download 3 files at once (I got FTTP 500) but it can take up to 5/10 minutes to combined the 3 files together and then start to download the next files.

My server isn't slow, it's an intel I5 with 4G of ram.

Any idea?

**Comment by GammaC0de** [comment]
For me it few takes seconds.

What OS are you using?
Maybe its a permissions issue?

Try with simple HTTP URL like https://releases.ubuntu.com/22.04/ubuntu-22.04-desktop-amd64.iso

**Comment by SweetthD3ViL** [comment]
Thank you for your reply.

I am using Archlinux, can't be permission - pyLoad start with my user and the folder is own by my user.

I changed the setting from 3 parallel download per link to 1 and it is much faster (seconds)

**Comment by GammaC0de** [comment]
What hardware do you use?

Maybe try to play with the [buffer size](https://github.com/pyload/pyload/blob/develop/src/pyload/core/network/http/http_download.py#L97).

**Comment by SweetthD3ViL** [comment]
I have a home build PC with SSD for the os, and two harddrive for the files and 8gb of ram (not 4 as previously stated) with an I5 Intel 

But now that I have changed the "max connection for one download" to 1 instead of 3 it is almost instant. 

Sorry it wasn't the max parallel download that I changed.

**Comment by GammaC0de** [comment]
Using one connection per download can limit the maximum download speed of that file.

You can still try to play the [buffer size](https://github.com/pyload/pyload/blob/develop/src/pyload/core/network/http/http_download.py#L97).

Closing.

**Comment by SweetthD3ViL** [comment]
sorry to revive an old topic. 

I am still having the issue, do I have to amend the buffer size directly on the config file? And if so, would it not be revert an update?

**Comment by fr3d02** [comment]
Hi, i've same problems. Very long combine files... How i can modify cache or no combine and directly download files ?

**Comment by GammaC0de** [comment]
@SweetthD3ViL @fr3d02 
> sorry to revive an old topic.

I am still having the issue, do I have to amend the buffer size directly on the config file? And if so, would it not be revert an update?

Sorry for (very) late response, you have to edit [http_download.py](https://github.com/pyload/pyload/blob/develop/src/pyload/core/network/http/http_download.py#L97) directly.
Play with the `buffer_size` value, restart pyload , make a download and  see what is the best value for `buffer_size`.

**Comment by fr3d02** [comment]
> @SweetthD3ViL @fr3d02
> 
> > sorry to revive an old topic.
> 
> I am still having the issue, do I have to amend the buffer size directly on the config file? And if so, would it not be revert an update?
> 
> Sorry for (very) late response, you have to edit [http_download.py](https://github.com/pyload/pyload/blob/develop/src/pyload/core/network/http/http_download.py#L97) directly. Play with the `buffer_size` value, restart pyload , make a download and see what is the best value for `buffer_size`.

Thanks for reply.
I want to test but i've some questions : 
How i can modify this value : 

buffer_size = 32 << 10

the result is on o, kb, mb, gb ? 
i can modify like this : buffer_size = 8000 if is in mb ?

Thx for reply,

**Comment by GammaC0de** [comment]
buffer_size is in bytes.
32 << 10 means 32*2^10 = 32768bytes = 32kb

>i can modify like this : buffer_size = 8000 if is in mb

No, it is 8000bytes.

**Comment by SweetthD3ViL** [comment]
Thank you for the reply,

I have tried "64 << 10" and it works, whether it is faster I don't know. What would be the defining factor that would indicate the best buffer size? CPU and ram? I have a intel I5 with 4gb of ram so should I got for a larger one?

**Comment by GammaC0de** [comment]
>I have tried "64 << 10" and it works, whether it is faster I don't know. What would be the defining factor that would indicate the best buffer size? CPU and ram? I have a intel I5 with 4gb of ram so should I got for a larger one?

You can measure the time it takes by calling time.time() in lines 90 and 111 of http_download.py and then log the delta value.
You have do some trial and error to know the best value.
