### ISSUE TITLE
Pause Dowloads and Reconnect button not working

### ISSUE THREAD

**Issue by BobSilent** [pyload/pyload#4136]
### Description
![image](https://user-images.githubusercontent.com/13506173/166327581-447c9b38-c79c-41c2-a4c0-2882199660ed.png)

Clicking the Buttons has no effect.
Pausing and unpausing can only be done via API

### Expected
clicking the button will toggle the Functionality

**This issue is on stable and 0.5 (pyLoad next)**

**Comment by GammaC0de** [comment]
Pausing and unpausing is done by using these buttons: 
![image](https://user-images.githubusercontent.com/11036551/166574167-2466a8e7-4f50-4058-b73f-47c9d9fb58aa.png)

**Comment by BobSilent** [comment]
Okay, maybe i used the wrong wording. 
In the past i could enable/disable overall downloading.

E.g. if i clicked the buttons above, pyload toggled from On to Off, active downloads finished, and then no new downloads stated.
![image](https://user-images.githubusercontent.com/13506173/166327581-447c9b38-c79c-41c2-a4c0-2882199660ed.png)

today, i still can click the "buttons" but nothing happens, so there are butttons (the cursors changes) but a click does nothing.

**Comment by GammaC0de** [comment]
You want to press the pause button to pause the queue.
The stop button stops active downloads.

**Comment by BobSilent** [comment]
Okay, let me check again
Maybe I was to quick here.

**Comment by BobSilent** [comment]
@GammaC0de sorry for this one, you are right, the pause button does what i want...

But toggle Reconnect is not possible on Home?

Maybe i just was confused, as the mouse cursor changes to a button click cursor when hovering over Download and Reconnect

**Comment by GammaC0de** [comment]
> But toggle Reconnect is not possible on Home?

Currently no, it is available in the settings menu.
Is it necessary? why would you want to constantly enable and disable reconnect?

**Comment by BobSilent** [comment]
I am a fan of lean work, so I currently would not request or wish this feature, as it seems that i am the only one requesting 😉

but just to give you a use case - my use case:

> currently i have an ISP where a reconnect gives me the same IP again (in 98% of reconnects) - so a reconnect is useless for me.
> But as a reconnect was usable, it was enabled by default. I only disabled it during the times I wanted a stable internet connection, e.g for work, streaming or any other thing.
> So i manually disabled it when needed.

Many thanks anyway for the really really great work you are doing here!
