### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by milahu** [pyload/pyload#4143]
error

```
  File "pyload/__init__.py", line 15, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

fixed by adding `setuptools` to dependencies

**Comment by GammaC0de** [comment]
Correct me if I'm wrong but its already there [setup.cfg#L81](https://github.com/pyload/pyload/blob/main/setup.cfg#L81)

**Comment by milahu** [comment]
aah, sorry, then it's a downstream issue with nix / nixpkgs

usually, when dependencies are missing, nix-build throws an error

here, when `setuptools` is missing, build is passing, but i get the runtime error `No module named pkg_resources`
