### ISSUE TITLE
show vpn error

### ISSUE THREAD

**Issue by milahu** [pyload/pyload#4148]
nitroflare says

> To continue this download please purchase premium or turn off your VPN.

pyload log says

```
WARNING             pyload  ANTICAPTCHA NitroflareCom[1]: ReCaptcha | Key pattern not found
```

ideally, pyload would show the vpn error

**Comment by milahu** [comment]
yes. filehosters dont like vpn : /

**Comment by GammaC0de** [comment]
If you are using a VPN and the remote site can detect it, this is not an issue with pyLoad.

**Comment by milahu** [comment]
> this is not an issue with pyLoad

problem is, pyload is printing the wrong error message (captcha error)

nevermind

**Comment by GammaC0de** [comment]
> problem is, pyload is printing the wrong error message (captcha error)
>nevermind

I understand your point, 
The plugin could be updated but I don't have VPN and you did not provide logs or sufficient information what should be changed with the plugin in order to handle this case..

**Comment by milahu** [comment]
> you did not provide logs or sufficient information what should be changed with the plugin in order to handle this case

fixed by adding this to

`plugins/downloaders/NitroflareCom.py`

```py
class NitroflareCom(SimpleDownloader):

    # ...

    def check_errors(self, data=None):
        super().check_errors(data=data)
        if data == 'To continue this download please <a href="/payment">purchase premium</a> or turn off your VPN.':
            self.fail(self._("File hoster does not support VPN"))
```

**Comment by GammaC0de** [comment]
Have you tested this code? can you confirm it works?

P.S. you should compare against `self.data `

**Comment by milahu** [comment]
yes, its working

generic solution:

```py
# plugins/base/simple_downloader.py

    def check_errors(self, data=None):
        data = data or self.data
        self.log_info(self._(f"Checking for link errors... data={repr(data)}"))
```

... so the error is in the logs
