### ISSUE TITLE
Can't download alldebrid

### ISSUE THREAD

**Issue by KyoshiroFR** [pyload/pyload#4150]
Hi, i can't download any file with alldebrid account
i already conf the token in my account but all my files weigh 2 ko
![2022-05-14_01h06_39](https://user-images.githubusercontent.com/104206709/168424981-c8096911-7e80-4241-97d4-44b04e67ff2e.png)
![2022-05-14_01h10_36](https://user-images.githubusercontent.com/104206709/168424982-2370b9bd-2ed4-468f-b403-17938cd3a860.png)
![2022-05-14_01h11_05](https://user-images.githubusercontent.com/104206709/168424983-95b37836-0544-4fee-b6c6-ed448e25dcb3.png)

thanks

**Comment by GammaC0de** [comment]
> but all my files weigh 2 ko

And what is the content of the files?

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by GammaC0de** [comment]
You should use the original URL (not the alldebrid URL) with pyload
