### ISSUE TITLE
Archive.org login

### ISSUE THREAD

**Issue by SMAW** [pyload/pyload#4151]
### Description

A Plugin for https://archive.org so that large/high bandwith files can be downloaded (this requires a log in)
### Sample resources

for example : https://archive.org/details/no-intro_romsets

**Comment by sgmihai** [comment]
Can you please show how to actually use this to download the files in the example folder ?
I tried added individual links to .zip files. I get : pyload.core.network.http.exceptions.BadHeader: Bad server response: 403 Forbidden
And adding a folder link like https://archive.org/download/no-intro_romsets I get:
Download failed: no-intro_romsets | Free download not implemented

archive.org user appears as valid in user list.
pyload-ng 0.5.0b3.dev26-1

**Comment by GammaC0de** [comment]
@sgmihai 
You have to add a Archive.org account to pyload before trying to download:
Settings->Accounts->Add->Archive.org

If you have issues, please provide sample URLs and debug logs.
