### ISSUE TITLE
anonfiles and bayfiles

### ISSUE THREAD

**Issue by akogwapo14** [pyload/pyload#4154]
hi nothing works anon files and bayfiles

<div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: flex; justify-content: space-between;"><div id="load-indicator2" class="load-indicator" style="box-sizing: border-box; opacity: 0; margin-top: 5px;"><img src="http://tarvos.whatbox.ca:19979/_themes/modern/img/ajax-loader.gif" alt="" style="box-sizing: border-box; border: 0px; vertical-align: middle; padding-right: 5px;"></div></div><div class="clear" style="box-sizing: border-box; clear: both; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><div class="logpaginator" style="box-sizing: border-box; float: left; padding-top: 5px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="http://tarvos.whatbox.ca:19979/logs/1" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none; padding: 0px 8px;"><span class="glyphicon glyphicon-fast-backward" style="box-sizing: border-box; position: relative; top: 1px; display: inline-block; font-family: &quot;Glyphicons Halflings&quot;; font-style: normal; font-weight: 400; line-height: 1; -webkit-font-smoothing: antialiased;"></span></a><span> </span><a href="http://tarvos.whatbox.ca:19979/logs/4542" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none; padding: 0px 8px;"><span class="glyphicon glyphicon-step-backward" style="box-sizing: border-box; position: relative; top: 1px; display: inline-block; font-family: &quot;Glyphicons Halflings&quot;; font-style: normal; font-weight: 400; line-height: 1; -webkit-font-smoothing: antialiased;"></span></a><span> </span><a href="http://tarvos.whatbox.ca:19979/logs/4576" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none; padding: 0px 8px;"><span class="glyphicon glyphicon-step-forward" style="box-sizing: border-box; position: relative; top: 1px; display: inline-block; font-family: &quot;Glyphicons Halflings&quot;; font-style: normal; font-weight: 400; line-height: 1; -webkit-font-smoothing: antialiased;"></span></a><span> </span><a href="http://tarvos.whatbox.ca:19979/logs" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none; padding: 0px 8px;"><span class="glyphicon glyphicon-fast-forward" style="box-sizing: border-box; position: relative; top: 1px; display: inline-block; font-family: &quot;Glyphicons Halflings&quot;; font-style: normal; font-weight: 400; line-height: 1; -webkit-font-smoothing: antialiased;"></span></a></div><div class="logperpage" style="box-sizing: border-box; float: right; padding-bottom: 8px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><form id="logform1" action="http://tarvos.whatbox.ca:19979/logs" method="POST" style="box-sizing: border-box;"><label for="reversed" style="box-sizing: border-box; display: inline-block; max-width: 100%; margin-bottom: 5px; font-weight: 700;">Reversed:</label><span> </span><input type="checkbox" name="reversed" id="reversed" onchange="this.form.submit();" style="box-sizing: border-box; margin: 4px 0px 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: normal; font-family: inherit; color: inherit; padding: 0px;"> <span> </span><label for="perpage" style="box-sizing: border-box; display: inline-block; max-width: 100%; margin-bottom: 5px; font-weight: 700;">Lines per page:</label> <span> </span><select name="perpage" id="perpage" onchange="this.form.submit();" style="box-sizing: border-box; margin: 0px 0px 5px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 14px; line-height: 1.42857; font-family: inherit; color: inherit; text-transform: none; display: inline; width: auto; height: auto; padding: 0px; border: 0px; border-top-left-radius: 4px; border-bottom-left-radius: 4px;"><span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><option value="0" style="box-sizing: border-box;">all</option><span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><option value="20" style="box-sizing: border-box;">20</option><span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><option value="34" selected="selected" style="box-sizing: border-box;">34</option><span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><option value="40" style="box-sizing: border-box;">40</option><span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><option value="100" style="box-sizing: border-box;">100</option><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span><span> </span> <span> </span></select></form></div><div class="logwarn" style="box-sizing: border-box; text-align: center; color: red; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; clear: both;"></div><div class="logdiv" style="box-sizing: border-box; width: 388.065px; height: 46vh; overflow: auto; border: 1px solid rgb(205, 205, 205); outline: rgb(205, 205, 205) solid 1px; background-color: rgb(240, 240, 240); margin-right: auto; margin-left: auto; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

4576 | ? | ? | ? | Traceback (most recent call last):
-- | -- | -- | -- | --
4577 | ? | ? | ? | File "/home/akogwapo14/.local/lib/python3.9/site-packages/pyload/plugins/addons/ClickNLoad.py", line 171, in _server
4578 | ? | ? | ? | dock_socket.bind((self.cnl_ip, self.cnl_port))
4579 | ? | ? | ? | OSError: [Errno 98] Address already in use
4580 | 2022-05-22 23:43:15 | INFO | pyload | Added package gago containing 1 links
4581 | 2022-05-22 23:43:15 | CRITICAL | pyload | module 'pyload.plugins.downloaders.BayFilesCom' has no attribute 'BayFilesCom'
4582 | ? | ? | ? | Traceback (most recent call last):
4583 | ? | ? | ? | File "/home/akogwapo14/.local/lib/python3.9/site-packages/pyload/core/managers/thread_manager.py", line 317, in assign_job
4584 | ? | ? | ? | job.init_plugin()
4585 | ? | ? | ? | File "/home/akogwapo14/.local/lib/python3.9/site-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
4586 | ? | ? | ? | return func(self, *args, **kwargs)
4587 | ? | ? | ? | File "/home/akogwapo14/.local/lib/python3.9/site-packages/pyload/core/datatypes/pyfile.py", line 88, in init_plugin
4588 | ? | ? | ? | self.pluginclass = getattr(
4589 | ? | ? | ? | AttributeError: module 'pyload.plugins.downloaders.BayFilesCom' has no attribute 'BayFilesCom'
4590 | 2022-05-22 23:43:37 | INFO | pyload | Added package sjsj containing 1 links
4591 | 2022-05-22 23:43:37 | CRITICAL | pyload | module 'pyload.plugins.downloaders.BayFilesCom' has no attribute 'BayFilesCom'
4592 | ? | ? | ? | Traceback (most recent call last):
4593 | ? | ? | ? | File "/home/akogwapo14/.local/lib/python3.9/site-packages/pyload/core/managers/thread_manager.py", line 317, in assign_job
4594 | ? | ? | ? | job.init_plugin()
4595 | ? | ? | ? | File "/home/akogwapo14/.local/lib/python3.9/site-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
4596 | ? | ? | ? | return func(self, *args, **kwargs)
4597 | ? | ? | ? | File "/home/akogwapo14/.local/lib/python3.9/site-packages/pyload/core/datatypes/pyfile.py", line 88, in init_plugin
4598 | ? | ? | ? | self.pluginclass = getattr(
4599 | ? | ? | ? | AttributeError: module 'pyload.plugins.downloaders.BayFilesCom' has no attribute 'BayFilesCom'
4600 | 2022-05-22 23:44:35 | INFO | pyload | Added package zkzkzkksosososo containing 1 links
4601 | 2022-05-22 23:44:36 | CRITICAL | pyload | module 'pyload.plugins.downloaders.BayFilesCom' has no attribute 'BayFilesCom'
4602 | ? | ? | ? | Traceback (most recent call last):
4603 | ? | ? | ? | File "/home/akogwapo14/.local/lib/python3.9/site-packages/pyload/core/managers/thread_manager.py", line 317, in assign_job
4604 | ? | ? | ? | job.init_plugin()
4605 | ? | ? | ? | File "/home/akogwapo14/.local/lib/python3.9/site-packages/pyload/core/utils/struct/lock.py", line 22, in wrapped
4606 | ? | ? | ? | return func(self, *args, **kwargs)
4607 | ? | ? | ? | File "/home/akogwapo14/.local/lib/python3.9/site-packages/pyload/core/datatypes/pyfile.py", line 88, in init_plugin
4608 | ? | ? | ? | self.pluginclass = getattr(
4609 | ? | ? | ? | AttributeError: module 'pyload.plugins.downloaders.BayFilesCom' has no attribute 'BayFilesCom'

</div>

**Comment by GammaC0de** [comment]
Works fine here, is this a new installation?

**Comment by akogwapo14** [comment]
> 

yes new install

**Comment by GammaC0de** [comment]
How exactly did you installed pyload?

**Comment by akogwapo14** [comment]
> 

i follow this, this is my service https://whatbox.ca/wiki/pyLoad

**Comment by akogwapo14** [comment]
anonfile is work now only bayfiles its not but its work when i put the direct url of download thanks

**Comment by GammaC0de** [comment]
What OS and python version are you using?

**Comment by GammaC0de** [comment]
No response, closing.
