### ISSUE TITLE
support for gofile.io

### ISSUE THREAD

**Issue by ddonindia** [pyload/pyload#4158]
### Description

Add support for gofile.io. Its one of best free file host service around.

### Sample resources

https://gofile.io/d/VQ7GlG

**Comment by ddonindia** [comment]
Thanks its working :)

**Comment by RAGIL316** [comment]
plugin does not work anymore @GammaC0de

**Comment by GammaC0de** [comment]
Please open a new issue and provide a sample URL.

**Comment by Doktor-X** [comment]
Not working
Bad server response: 401 Unauthorized

https://gofile.io/d/52be6f61-f12f-42b3-bc6f-90fe21a4f2a8

**Comment by GammaC0de** [comment]
@Doktor-X 
If you try this URL on your browser you get:
![image](https://github.com/pyload/pyload/assets/11036551/364bac97-b47c-47d3-b7b8-b6c7a9f778e7)

Plugin updated to handle this situation.

**Comment by Doktor-X** [comment]
Now it works its no longer private
https://gofile.io/d/RVPqS1
