### ISSUE TITLE
TCP: request_sock_TCP: Possible SYN flooding on port X. Sending cookies. Check SNMP counters. (Web UI port)

### ISSUE THREAD

**Issue by FZXizzbKv7jg** [pyload/pyload#4173]
### Description

dmesg shows this message

`TCP: request_sock_TCP: Possible SYN flooding on port X. Sending cookies. Check SNMP counters. `

for the web ui port.

Changing parameters in sysctl has no effects.
It must be hardcoded in pyload (TCP Listen Backlog?). Got this error with another python based program (deluge).
It doesn't cause any real problems in pyload. Anyway, it may be better to avoid this.

### Debug log

```

```

### Additional references

Please see https://access.redhat.com/solutions/30453

**Comment by GammaC0de** [comment]
> `TCP: request_sock_TCP: Possible SYN flooding on port X. Sending cookies. Check SNMP counters. `

Where exactly do you see this error?

**Comment by FZXizzbKv7jg** [comment]
Output of

`sudo dmesg `

Kernel ring buffer. I'm on Manjaro Linux.

**Comment by GammaC0de** [comment]
Do you know how to make a PR to fix this?

**Comment by FZXizzbKv7jg** [comment]
Hi again.

We might clarify this quickly? I'm sorry for late reply.

My suggestion to you would be to implement an option in web interface for socket backlog size (see qBittorrent has that option).
And further, increase default value to 30.

At least, the default value must be increased to 30 (default is 5 as far as I can remember).



```
# /usr/lib/python3.10/site-packages/pyload/webui/webserver_thread.py
# request_queue_size

    def _run_produc(self):
        bind_path = "/"
        bind_addr = (self.host, self.port)
        wsgi_app = wsgi.PathInfoDispatcher({bind_path: self.app})
        self.server = wsgi.Server(bind_addr, wsgi_app, request_queue_size=512)
```

I'll leave it up to you to decide. Thank you!

**Comment by GammaC0de** [comment]
👍
