### ISSUE TITLE
Depositfiles Captcha Not Loading

### ISSUE THREAD

**Issue by defencedog** [pyload/pyload#4174]
Rapidgator Working But Depositfile not working?

![Screenshot_2](https://user-images.githubusercontent.com/831749/179635393-6b5fa823-1614-4352-8add-5c5d5e46c7d2.png)

**Comment by GammaC0de** [comment]
Try installing https://addons.mozilla.org/en-US/firefox/addon/ignore-x-frame-options-header and see if it helps.

**Comment by defencedog** [comment]
I am using Edge (chromium based)

**Comment by defencedog** [comment]
I have installed this for my Edge: https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe

But no ...its isnt correcting issue

**Comment by GammaC0de** [comment]
Sample URL please

**Comment by defencedog** [comment]
Try this: https://depositfiles.com/files/7w3fxndfy

**Comment by GammaC0de** [comment]
[This plugin](https://microsoftedge.microsoft.com/addons/detail/cors-unblock/hkjklmhkbkdhlgnnfbbcihcajofmjgbh) or [this chrome plugin](https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe) solves this issue.

If you ask me I prefer the chrome plugin.

**Comment by defencedog** [comment]
@GammaC0de Using either plugin my problem isnt resolved?

**Comment by GammaC0de** [comment]
Switch to chrome or use the Captcha9Kw plugin.
