### ISSUE TITLE
DebridlinkFrTorrent

### ISSUE THREAD

**Issue by Cseb87** [pyload/pyload#4178]
Hi,
for a few days I have this error with DebridlinkFrTorrent :
Decrypting failed: .......... | (6, 'Could not resolve host: up1.debrid.link')

I specify that the direct download with DebridlinkFr works normally

Thanks

**Comment by GammaC0de** [comment]
This is not an issue with pyload,
It seems that you have some kind of DNS issues (maybe you are using a VPN?)
Your system cannot resolve the host up1.debrid.link.

**Comment by Cseb87** [comment]
> This is not an issue with pyload, It seems that you have some kind of DNS issues (maybe you are using a VPN?) Your system cannot resolve the host up1.debrid.link.

I use cloudflare DNS
I wonder if the address https://up1.debrid.link/seedbox is still valid

https://debrid-link.fr/api_doc/v2/introduction

**Comment by GammaC0de** [comment]
OK,
I can see some issues with the plugin .

I have sent a support query to DebridlinkFr, will update when I get an answer.
