### ISSUE TITLE
Plugin DebridLinkFR GetDebridlinkToken.py

### ISSUE THREAD

**Issue by flyxen-jpg** [pyload/pyload#4188]
### Question
I've tried to connect my DebridLinkFr Account with the pyload Plugin.
Then I found following line in the log:

ACCOUNT DebridlinkFr: You have to use GetDebridlinkToken.py to authorize pyLoad: https://github.com/pyload/pyload/files/4679112/GetDebridlinkToken.zip

So I downloaded the file and let it run.
But every time when I'm running the script this error message pops up:

Traceback (most recent call last):
  File "Main.py", line 91, in <module>
    main()
  File "Main.py", line 49, in main
    client_id = raw_input("then go to the app's details and paste the value of 'client_id' here: ")
EOFError: EOF when reading a line

I'm new to this, so maybe this error occurs because of a mistake from my side.
But I'm not sure and don't know how to deal with this.

**Comment by GammaC0de** [comment]
Open terminal (console) app on your computer and run the file there, do not run it on your NAS.

**Comment by flyxen-jpg** [comment]
That's exactly what I've already tried on my Macbook
![Screenshot](https://user-images.githubusercontent.com/75328690/184875643-4199bc3c-29b6-44eb-89f9-b90b54b9a7e0.png)

**Comment by GammaC0de** [comment]
rename `raw_input` to `input`.

**Comment by flyxen-jpg** [comment]
Thanks after changing to input I can already enter the Client ID. But when I do that, I get the following error messages:

![Bildschirmfoto 2022-08-16 um 21 18 30](https://user-images.githubusercontent.com/75328690/184964484-c691448a-4662-4d64-8d2e-f0f3adc2a4ac.png)

As far as I can see, I've set up everything correctly with DebridLinkFr:
![Bildschirmfoto 2022-08-16 um 21 20 04](https://user-images.githubusercontent.com/75328690/184964636-b0ee3ad7-d10b-4e26-b7f7-660f25863aab.png)

**Comment by GammaC0de** [comment]
Try this: https://pastebin.pl/view/e0797d91

**Comment by flyxen-jpg** [comment]
That's working :)
Thank you so much!!
