### ISSUE TITLE
FilecryptCc: Activating "Handle Mirror Pages" leads to multiple packages

### ISSUE THREAD

**Issue by JayFoxRox** [pyload/pyload#4194]
When adding an URL to filecrypt.cc, with "Handle Mirror Pages" enabled, the decryption will lead to new packages being created for each mirror. I don't think this is intentional?

Problems:

- All packages will share the same name.
- This is bad for using the pyload API (as the package you added via API is no longer the package you want to track).
- Makes it impossible to order / prioritize packages by mirror, because priority is per-package.
- Multiple progress bars (one per package) in the Web-UI for what should be a single package.

**Comment by GammaC0de** [comment]
Do you have an example URL with mirrors in it?

**Comment by GammaC0de** [comment]
No response, closing.
