### ISSUE TITLE
Docker build fails building cryptography wheel

### ISSUE THREAD

**Issue by rrittwag** [pyload/pyload#4204]
### Description

Building the main branch via `docker build -t my-pyload:latest .` fails with "Failed building wheel for cryptography".
Reason: the build demands a newer Rust version.

### Debug log

```
  error: Rust 1.47.0 does not match extension requirement >=1.48.0
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
```
[complete log](https://pastebin.com/LL3KrSWS)

**Comment by raycheung** [comment]
After #4205, the Docker image built but it said pyload module not found on start. Is it just me please?

**Comment by rrittwag** [comment]
I get the same error "pyload module not found". But I'm not experienced enough in Python and did not have the time to analyse it.

**Comment by raycheung** [comment]
> 

It's the Docker image built having this issue.

**Comment by GammaC0de** [comment]
> It's the Docker image built having this issue.

I have successfully built and run the Docker image on Ubuntu 18.04

**Comment by raycheung** [comment]
> > It's the Docker image built having this issue.
> 
> I have successfully built and run the Docker image on Ubuntu 18.04

Thanks. Yes, I found it is something about building with Alpine 3.14, reverting back to 3.13 is better. Will take a look later.
