### ISSUE TITLE
Zippy occasionally has issues with files.

### ISSUE THREAD

**Issue by CaptainCoward** [pyload/pyload#4217]
Sometimes the zippy plugin will have Issues with some parts. Printing the error 32 in the debug console, saying the File can't be accessed since it is used by another process (which it isn't). If i then try to "redownload" i'll get a bad request. Downloading the same file via Browser will work just fine.

I'd love to provide additional info, but i closed pyload by accident. So this is the only information i have at this point. Though the debug console didn'T print anything else related to the issue anyways.

**Comment by GammaC0de** [comment]
Please enable debug  mode and then provide debug log.

**Comment by GammaC0de** [comment]
No response, closing.
