### ISSUE TITLE
Pyload failed to start since update

### ISSUE THREAD

**Issue by SweetthD3ViL** [pyload/pyload#4218]
Hello,

Running pyload-ng installed via pip on Archlinux. Following a system update pyload failed to start. I have tried to update via pip --upgrade but that did not help neither. 

see terminal output:

`$ sudo systemctl status pyload
x pyload.service - Downloadtool for One-Click-Hoster written in python.
     Loaded: loaded (/etc/systemd/system/pyload.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Thu 2022-11-10 17:57:00 GMT; 3s ago
   Duration: 570ms
    Process: 813 ExecStart=python3 -m pyload (code=exited, status=1/FAILURE)
   Main PID: 813 (code=exited, status=1/FAILURE)
        CPU: 458ms

Nov 10 17:57:00 pbertol.duckdns.org python3[813]:     from .network import request_factory
Nov 10 17:57:00 pbertol.duckdns.org python3[813]:   File "/home/sweetth/.local/lib/python3.10/site-packages/pyload/core/network/request_factory.py", line 6, in <module>
Nov 10 17:57:00 pbertol.duckdns.org python3[813]:     from .browser import Browser
Nov 10 17:57:00 pbertol.duckdns.org python3[813]:   File "/home/sweetth/.local/lib/python3.10/site-packages/pyload/core/network/browser.py", line 7, in <module>
Nov 10 17:57:00 pbertol.duckdns.org python3[813]:     from .http.http_download import HTTPDownload
Nov 10 17:57:00 pbertol.duckdns.org python3[813]:   File "/home/sweetth/.local/lib/python3.10/site-packages/pyload/core/network/http/http_download.py", line 7, in <module>
Nov 10 17:57:00 pbertol.duckdns.org python3[813]:     import pycurl
Nov 10 17:57:00 pbertol.duckdns.org python3[813]: ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
Nov 10 17:57:00 pbertol.duckdns.org systemd[1]: pyload.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 17:57:00 pbertol.duckdns.org systemd[1]: pyload.service: Failed with result 'exit-code'.
`

**Comment by GammaC0de** [comment]
Try updating/reinstalling pycurl

**Comment by GammaC0de** [comment]
it looks like archlinux switched to openssl 3 and pycurl was linked with openssl 1.1

>Is the pycurl version used by pyload installed using pip the same as the system one?

I think the system one should be more compatible with the OS (obviously).

**Comment by SweetthD3ViL** [comment]
thank you for your prompt replies. 

So what's my options then?

**Comment by GammaC0de** [comment]
maybe update packages libcurl, libcurl-dev,  openssl, openssl-dev

**Comment by SweetthD3ViL** [comment]
my all system is actually up to date.

**Comment by GammaC0de** [comment]
Try:
```
# python 3
>>> import pycurl
>>> pycurl.version

```

**Comment by SweetthD3ViL** [comment]
Thank you for the prompt replies and assistance, you are a star.

See below result:

```
$ python3
Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
>>> pycurl.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pycurl' is not defined
>>> 
```

**Comment by GammaC0de** [comment]
Your issue is incompatibilities between libcurl/openssl/pycurl 

What version of Archlinux are you running?

maybe try removing system pycurl and install via pip.

**Comment by SweetthD3ViL** [comment]
Brilliant!!!  

That works!

Thank you so much!!
