### ISSUE TITLE
Add DebridPlanet

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#4224]
### Discussed in https://github.com/pyload/pyload/discussions/4223

<div type='discussions-op-text'>

<sup>Originally posted by **ioannis101** November 23, 2022</sup>
Hello,

Can you please add the plugin for debridplanet (multyhosting downloader https://debridplanet.com/)?

Thank you.</div>

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by ioannis101** [comment]
Thank you for your quick response. Mail sended.
