### ISSUE TITLE
'utf8' codec can't decode byte invalid continuation byte 

### ISSUE THREAD

**Issue by xilmen** [pyload/pyload#4230]
Hello, 

I used latest version of pyload (with docker https://hub.docker.com/r/linuxserver/pyload). All addon are updated. 

### Description
Not all torrent names ("éà.torrent" for example) work, in my example the  0xe9 -> é. I have space on my name. 

### Debug log
```
38	10.12.2022 23:08:45	INFO	CONTAINER TORRENT[66]: Grabbing link info...
37	10.12.2022 23:08:45	WARNING	CONTAINER TORRENT[66]: Plugin may be unstable
36	10.12.2022 23:08:45	DEBUG	CONTAINER TORRENT[66]: Plugin status: testing
35	10.12.2022 23:08:45	DEBUG	CONTAINER TORRENT[66]: Plugin version: 0.05
34	10.12.2022 23:08:45	INFO	Decrypting starts: /torrent/finished/<String_with_all_utf8_char>.torrent
33	10.12.2022 23:08:43	INFO	Debug Report written to debug_TORRENT_10-12-2022_23-08-43.zip
32	? 	?	UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 19: invalid continuation byte
31	? 	?	return codecs.utf_8_decode(input, errors, True)
30	? 	?	File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
29	? 	?	url = url.encode("latin1").decode("utf8") #: bugfix urllib
28	? 	?	File "/config/userplugins/internal/misc.py", line 528, in fixurl
27	? 	?	url = fixurl(url, unquote=True)
26	? 	?	File "/app/pyload/module/plugins/internal/Base.py", line 43, in get_info
25	? 	?	new_info = self.get_info(replace_patterns(self.pyfile.url, self.URL_REPLACEMENTS), self.data)
24	? 	?	File "/app/pyload/module/plugins/internal/Base.py", line 222, in grab_info
23	? 	?	self.grab_info()
22	? 	?	File "/app/pyload/module/plugins/internal/Base.py", line 165, in _setup
21	? 	?	self._setup()
20	? 	?	File "/app/pyload/module/plugins/internal/Base.py", line 266, in _process
19	? 	?	return self._process(*args, **kwargs)
18	? 	?	File "/app/pyload/module/plugins/internal/Base.py", line 290, in preprocessing
17	? 	?	self.active.plugin.preprocessing("self")
16	? 	?	File "/app/pyload/module/PluginThread.py", line 363, in run
15	? 	?	Traceback (most recent call last):
14	10.12.2022 23:08:43	ERROR	Decrypting failed: /torrent/finished/<String_with_all_utf8_char>.torrent | 'utf8' codec can't decode byte 0xe9 in position 19: invalid continuation byte 
```

**Comment by GammaC0de** [comment]
You'd better use https://hub.docker.com/r/linuxserver/pyload-ng instead

**Comment by xilmen** [comment]
This works much better. Thx !

**Comment by qwrty-ftw** [comment]
Any workarrouund to get this work ? @GammaC0de 
I dont want to use docker image right now :(

**Comment by GammaC0de** [comment]
Use https://hub.docker.com/r/linuxserver/pyload-ng

**Comment by GammaC0de** [comment]
@qwrty-ftw Please provide sample problematic URL

**Comment by qwrty-ftw** [comment]
@GammaC0de 

Here two examples:

`Decrypting failed: /mnt/volume1/telechargements/WatchFolderPyload/finished/Arrête moi si tu peux (2002) MULTi 1080p BluRay mHD AC3 x264-SANTACRUZ (Catch Me If You Can).torrent | 'utf8' codec can't decode byte 0xea in position 59: invalid continuation byte`

`Decrypting failed: /mnt/volume1/telechargements/WatchFolderPyload/finished/Shrek the Halls (2007) MULTi [1080p] BluRay x264-PopHD.mkv (Joyeux Noël Shrek !).torrent | 'utf8' codec can't decode byte 0xeb in position 125: invalid continuation byte`

**Comment by GammaC0de** [comment]
@qwrty-ftw
1. What I asked for is the URLs that  you downloaded `Shrek the Halls (2007) MULTi [1080p] BluRay x264-PopHD.mkv (Joyeux Noël Shrek !).torrent` and `Arrête moi si tu peux (2002) MULTi 1080p BluRay mHD AC3 x264-SANTACRUZ (Catch Me If You Can).torrent`  from.
2. Please enable debug mode, retry the donload and post the logs.
3. why not use pyload-ng (v0.5) instead of v0.4.20?

**Comment by qwrty-ftw** [comment]
.torrent came from YGG.
They are download from Radarr which download the .torrent from my YGG indexer.
I use Blackhole download client in Radarr.
Radarr and the Blackhole download client store the . torrent in the watch folder scan by Pyload and RealdebridComTorrent download it.

Hope it's clear ˆˆ

Ok, i will do that for the log.

I like the way I can run the 0.4.20 (whith his own user, and all files in a single folder)
Docker is root only, I dont like that and I dont want to use it right now.
I check the Pip install for the pyload-ng instead, but I dont like the way are managed config files (in hiden folder) and i think I cannot run it as a specific system user with nologin for example ?

**Comment by GammaC0de** [comment]
>but I dont like the way are managed config files (in hidden folder) and i think I cannot run it as a specific system user with nologin for example ?

pyload-ng  has `--storagedir`, `--userdir` and `--tempdir` command-line arguments.
also pyload-ng run as daemon with `--daemon` command-line switch.

**Comment by qwrty-ftw** [comment]
I will check that, thank you :)

Btw, the debug trace:

`

331 | 05.02.2023 22:15:56 | INFO | Decrypting starts: /mnt/volume1/telechargements/WatchFolderPyload/finished/ArrÃªte moi si tu peux (2002) MULTI AC3 1080p mHD x264-SANTACRUZ.mkv.torrent
-- | -- | -- | --
332 | 05.02.2023 22:15:56 | DEBUG | CONTAINER TORRENT[1982]: Plugin version: 0.05
333 | 05.02.2023 22:15:56 | DEBUG | CONTAINER TORRENT[1982]: Plugin status: testing
334 | 05.02.2023 22:15:56 | WARNING | CONTAINER TORRENT[1982]: Plugin may be unstable
335 | 05.02.2023 22:15:56 | INFO | CONTAINER TORRENT[1982]: Grabbing link info...
336 | 05.02.2023 22:15:56 | ERROR | Decrypting failed: /mnt/volume1/telechargements/WatchFolderPyload/finished/ArrÃªte moi si tu peux (2002) MULTI AC3 1080p mHD x264-SANTACRUZ.mkv.torrent \| 'latin-1' codec can't encode character u'\u0303' in position 60: ordinal not in range(256)
337 | ? | ? | Traceback (most recent call last):
338 | ? | ? | File "/opt/pyload/module/PluginThread.py", line 363, in run
339 | ? | ? | self.active.plugin.preprocessing(self)
340 | ? | ? | File "/opt/pyload/userplugins/internal/Base.py", line 290, in preprocessing
341 | ? | ? | return self._process(*args, **kwargs)
342 | ? | ? | File "/opt/pyload/userplugins/internal/Base.py", line 266, in _process
343 | ? | ? | self._setup()
344 | ? | ? | File "/opt/pyload/userplugins/internal/Base.py", line 165, in _setup
345 | ? | ? | self.grab_info()
346 | ? | ? | File "/opt/pyload/userplugins/internal/Base.py", line 222, in grab_info
347 | ? | ? | new_info = self.get_info(replace_patterns(self.pyfile.url, self.URL_REPLACEMENTS), self.data)
348 | ? | ? | File "/opt/pyload/userplugins/internal/Base.py", line 43, in get_info
349 | ? | ? | url = fixurl(url, unquote=True)
350 | ? | ? | File "/opt/pyload/userplugins/internal/misc.py", line 528, in fixurl
351 | ? | ? | url = url.encode("latin1").decode("utf8") #: bugfix urllib
352 | ? | ? | UnicodeEncodeError: 'latin-1' codec can't encode character u'\u0303' in position 60: ordinal not in range(256)
353 | 05.02.2023 22:15:56 | INFO | Debug Report written to debug_TORRENT_05-02-2023_22-15-56.zip

`
