### ISSUE TITLE
GetRealdebridtoken available ?

### ISSUE THREAD

**Issue by sk1llup** [pyload/pyload#4231]
Hello,

i want to know if GetRealdebridtoken.py is available ?
i enter my login/password on pyload config for uptobox and realdebrid but i got "not valid"

![image](https://user-images.githubusercontent.com/41892224/207400295-e7764af5-c824-450d-b20f-042014d4dbf7.png)

if anyone can explain to me thanks

**Comment by GammaC0de** [comment]
GetRealdebridToken is here: [GetRealdebridToken](https://github.com/pyload/pyload/files/4406037/GetRealdebridToken.zip)

As for UptoboxCom, account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by sk1llup** [comment]
thanks for realdebrid

where i set username & password please ?

pi@raspberrypi:~ $ python GetRealdebridToken.py

Please login to your real-debrid account, then go to https://real-debrid.com/device
and enter the code XXXXXXX to authorize the request.

Waiting for authorization... 880

Your username for RealDebridCom: xxxx
Your Password for RealdebridCom: xxxx

**Comment by GammaC0de** [comment]
> Your username for RealDebridCom: xxxx
Your Password for RealdebridCom: xxxx

Put this in pyload`s RealdebridCom account config.

**Comment by sk1llup** [comment]
i see on accounts.conf

RealdebridCom:

        xxxx:xxxx
        @limitDL 0

but on settings url, not valid

![image](https://user-images.githubusercontent.com/41892224/207429365-b4415427-b73a-4c18-b03d-b170630a1e21.png)

**Comment by GammaC0de** [comment]
Please look in the logs if there is more info.

**Comment by sk1llup** [comment]
<html>
<body>


1052 | 13.12.2022 19:48:46 | ERROR | ACCOUNT RealdebridCom: Password for Real-debrid should be the API token - get it from: https://real-debrid.com/apitoken
-- | -- | -- | --
1053 | 13.12.2022 19:48:46 | ERROR | ACCOUNT RealdebridCom: Could not login user `HBR*******` \| Login handshake has failed


</body>
</html>

**Comment by sk1llup** [comment]
<html>
<body>


15 | 13.12.2022 20:05:36 | INFO | Starting pyLoad 0.4.9
-- | -- | -- | --
16 | 13.12.2022 20:05:36 | INFO | Using home directory: /opt/pyload/pyload-config
17 | 13.12.2022 20:05:37 | INFO | Activated plugins: ClickNLoad, EventMapper, ExternalScripts, RestartFailed, UnSkipOnFail, UpdateManager, UserAgentSwitcher
18 | 13.12.2022 20:05:37 | INFO | Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, SkipRev, TransmissionRPC, WindowsPhoneNotify, XFileSharing, XMPP
19 | 13.12.2022 20:05:37 | INFO | Downloadtime: True
20 | 13.12.2022 20:05:38 | INFO | Free space: 235.24 GiB
21 | 13.12.2022 20:05:38 | INFO | Activating Accounts...
22 | 13.12.2022 20:05:38 | INFO | Starting builtin webserver: 0.0.0.0:8000
23 | 13.12.2022 20:05:38 | INFO | ACCOUNT RealdebridCom: Adding user `HBR*******`...
24 | 13.12.2022 20:05:38 | INFO | ACCOUNT RealdebridCom: Login user `HBR*******`...
25 | 13.12.2022 20:05:38 | ERROR | ACCOUNT RealdebridCom: Password for Real-debrid should be the API token - get it from: https://real-debrid.com/apitoken
26 | 13.12.2022 20:05:38 | ERROR | ACCOUNT RealdebridCom: Could not login user `HBR*******` \| Login handshake has failed
27 | 13.12.2022 20:05:38 | INFO | Activating Plugins...
28 | 13.12.2022 20:05:38 | INFO | pyLoad is up and running
29 | 13.12.2022 20:05:39 | INFO | ADDON UpdateManager: *** New pyLoad 0.4.20 available ***
30 | 13.12.2022 20:05:39 | INFO | ADDON UpdateManager: *** Get it here: https://github.com/pyload/pyload/releases ***
31 | 13.12.2022 20:05:40 | INFO | ADDON RestartFailed: Restarting all failed downloads...
32 | 13.12.2022 20:05:40 | ERROR | ACCOUNT RealdebridCom: Could not load hoster list - invalid account, retry in 5 minutes
33 | 13.12.2022 20:05:44 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666


</body>
</html>

**Comment by sk1llup** [comment]
need to do something here : ACCOUNT RealdebridCom: Could not load hoster list - invalid account, retry in 5 minutes ?

**Comment by sk1llup** [comment]
don't know if its the username but i got a / on it :  HBRXXXXXXXX**/**b0cbxxxxxxxxxxxxxxxxxxxxx

**Comment by GammaC0de** [comment]
> don't know if its the username but i got a / on it

This is normal


> Starting pyLoad 0.4.9

Your pyload version is  **OLD**

Please update to at least version 0.4.20 or if you have python3, better use v0.5

**Comment by sk1llup** [comment]
Its possible to upgrade it from 0.4.9 to 0.4.20 without totally reinstall ?

**Comment by GammaC0de** [comment]
Please follow installation the instruction in #3283

**Comment by sk1llup** [comment]
ok thanks i will test

**Comment by sk1llup** [comment]
i'm on a raspberry and pyload is on docker container
maybe you know Docker Pull Command / docker container with the last pyload version ?

**Comment by GammaC0de** [comment]
For docker use https://github.com/linuxserver/docker-pyload-ng
