### ISSUE TITLE
Security Reports

### ISSUE THREAD

**Issue by bAuh0lz** [pyload/pyload#4239]
### Description

Could you please check these security reports?
I think they are harmful issues.

- https://www.huntr.dev/bounties/867509d2-be5f-42e4-bcc7-59c23de581e5/
- https://www.huntr.dev/bounties/4311d8d7-682c-4f2a-b92c-3f9f1a36255a/

**Comment by GammaC0de** [comment]
Hello,
They will be addressed, I need more time

**Comment by bAuh0lz** [comment]
Hi,
Sure, I just wanted to know if the reports were left.
Thanks.
