### ISSUE TITLE
pyload parse_url call from flexget fails

### ISSUE THREAD

**Issue by StefftheEmperor2** [pyload/pyload#4240]
### Description

Hi,
the flexget pyload plugin does an api call /parse_urls to pyload if configured as an output.

the request body looks something like:
{'html': '"bla https://foo.bar"', 'url': ''}

then pyload responds with a 500

### Debug log

```
invalid syntax (<unknown>, line 0)","traceback":"Traceback (most recent call last):\\n  File \\"/pyload/webui/app/blueprints/api_blueprint.py\\", line 55, in rpc
response = call_api(func, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File \\"/pyload/webui/app/blueprints/api_blueprint.py\\", line 71, in call_api
**{x: literal_eval(y) for x, y in kwargs.items()},
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File \\"/pyload/webui/app/blueprints/api_blueprint.py\\", line 71, in <dictcomp>
**{x: literal_eval(y) for x, y in kwargs.items()},
^^^^^^^^^^^^^^^
File \\"/usr/lib/python3.11/ast.py\\", line 64, in literal_eval
node_or_string = parse(node_or_string.lstrip(\\" \\\\t\\"), mode=\'eval\')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File \\"/usr/lib/python3.11/ast.py\\", line 50, in parse
return compile(source, filename, mode, flags,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File \\"<unknown>\\", line 0

SyntaxError: invalid syntax
```

Not sure wheather the problem is flexget sending an empty string as url or ast which cant parse empty strings or pyload, which does not catch those.

Kind regards,
StE

**Comment by StefftheEmperor2** [comment]
Tried a hack to filter empty strings, but other strings fail as well. what the heck is this code even good for. calling some sort of eval on input parameters .. isn't that dangerous?

**Comment by GammaC0de** [comment]
Was it working on python version older than 3.11?

**Comment by StefftheEmperor2** [comment]
same for 3.10 .. sadly i do not have any other versions installed locally

**Comment by GammaC0de** [comment]
> what the heck is this code even good for. calling some sort of eval on input parameters .. isn't that dangerous?

It is used for parsing the input parameters,
See https://docs.python.org/3/library/ast.html#ast.literal_eval

I am not familiar with flexget, how do you use it?

**Comment by StefftheEmperor2** [comment]
> I am not familiar with flexget, how do you use it?

The short version:
I'm gathering links from rss feeds and passing them to pyload .. 

The long version: .. its complicated :-)

**Comment by GammaC0de** [comment]
>the request body looks something like:
{'html': '"bla https://foo.bar/"', 'url': ''}

API does not accept json input.

Arguments are either query parameters and/or form fields, so the flexget plugin is defect:
* `curl -H "Content-type: multipart/form-data" -F html="blah  https://foo.bar/" -X POST "http://localhost:8000/api/parse_urls"`

* `curl "http://localhost:8000/api/parse_urls?html=%22blah+https://foo.bar/%22"`

**Comment by StefftheEmperor2** [comment]
> Arguments are either query parameters and/or form fields, so the flexget plugin is defect

Actually, my post was the export of the dict, flexget builds as form-data

**Comment by GammaC0de** [comment]
You can try the examples I posted above and see that they work.

So put a breakpoint in [api_blueprint.py#L22](https://github.com/pyload/pyload/blob/main/src/pyload/webui/app/blueprints/api_blueprint.py#L22) and see what Flexget is doing wrong.

**Comment by StefftheEmperor2** [comment]
![Bildschirmfoto vom 2023-02-05 02-36-17](https://user-images.githubusercontent.com/55734627/216797183-6728015a-346b-43d1-8aed-a4ea1c3493cd.png)
![Bildschirmfoto vom 2023-02-05 02-40-03](https://user-images.githubusercontent.com/55734627/216797232-bc05244c-f4c9-4f20-a922-0a8c4d7d49b1.png)

the get via get worked, but the curl post ended up in the exact same exception .. the difference in the post is, that its not extra quited, ie `curl -H "Content-type: multipart/form-data" -F html="'blah  https://foo.bar/'" -X POST "http://localhost:8000/api/parse_urls"`
