### ISSUE TITLE
[pyload-ng] systemd service ? and few questions

### ISSUE THREAD

**Issue by qwrty-ftw** [pyload/pyload#4251]
Hello,

I'm running 0.4.20 right now, which work really great, I start to play with pyload-ng (installed with pip) beacause of this issue #4230

I have made a systemd service, which seems to work:

```
[Unit]
Description=pyload-ng
After=network.target

[Service]
User=pyload
Group=pyload
Type=simple
ExecStart=/usr/local/bin/pyload --storagedir /mnt/volume1/telechargement --userdir /opt/pyload-ng --tempdir /opt/pyload-ng --pidfile /opt/pyload-ng/pyload-ng.pid
[Install]
WantedBy=multi-user.target
```

Can your confirm that's the way we should run pyload-ng as a service ? Maybe the type is wrong (forking ?)

0.5 consume a way more ressource - **CPU time** -  than 0.4.20

1h30 uptime and already 30s on 0.5 vs 2h30 and just 2.563s for the 0.4.20 version:
```
Active: active (running) since Mon 2023-02-06 11:35:13 CET; **1h 29min ago**
   Main PID: 230048 (pyload)
      Tasks: 23 (limit: 76876)
     Memory: 54.0M
        **CPU: 30.287s**
     CGroup: /system.slice/pyload-ng.service
             └─230048 /usr/bin/python3 /usr/local/bin/pyload --storagedir /mnt/volume1/telechargement --userdir /opt/pyload-ng --tempdir /opt/pyload-ng --pidfile /opt/pyload-ng/pyload-ng.pid
```

```
Active: active (running) since Mon 2023-02-06 10:37:22 CET; **2h 27min ago**
   Main PID: 164447 (python2.7)
      Tasks: 13 (limit: 76876)
     Memory: 43.7M
        **CPU: 2.563s**
     CGroup: /system.slice/pyload.service
             └─164447 /usr/bin/python2.7 /opt/pyload/pyLoadCore.py
```

I also notice a few more process running on 0.5 vs 0.4.20

```
pstree pyload
pyload───22*[{pyload}]
python2.7───12*[{python2.7}]
```

Another question: 
0.4.20 auto update modules, does 0.5 do the same or we should upgrade with pip ?

Thank you for your feedback :)

**Comment by GammaC0de** [comment]
> Maybe the type is wrong (forking ?)

No, it seems OK as you are not forking with the `--daemon` switch.
> 0.4.20 auto update modules, does 0.5 do the same or we should upgrade with pip ?

currently v0.5 does not support updates via `UpdateManager`,
So run:
`pip install --upgrade https://github.com/pyload/pyload/archive/refs/heads/main.zip`
or
`pip install --upgrade https://github.com/pyload/pyload/archive/refs/heads/develop.zip`
now and then.
