### ISSUE TITLE
 No module named 'pyload.core.config' when installing pip install pyload-ng

### ISSUE THREAD

**Issue by StefanRu1** [pyload/pyload#4252]
### Description
I have a new installed Raspberry Pi4 on bullseye.
I tried to install "pip install pyload-ng"
When trying to start pyload I get:
 No module named 'filetype'

After installing filetype with "pip install filetype" and try gain to start pyload I get:
 No module named 'pyload.core.config'

I had this problem long time ago on my raspberry pi3. I solved it somehow.
But now I have no idea anymore what to do.

I found some references here but they seem to be outdated.
eg.: https://github.com/pyload/pyload/issues/3540
and: https://github.com/pyload/pyload/issues/3428#issuecomment-522275713

On my PI3 i have 0.5.0 running but do not remember how i got it working.
I also checked on the PI3 and it is using python3.9.

Should be possible on PI4 too. 

Can you help me solve the issue?

Thanks,
Stefan

**Comment by GammaC0de** [comment]
What python version are you running?

Install via `pip3 install --pre pyload-ng[all`

Please post the logs from the installation.

**Comment by StefanRu1** [comment]
Hi and thanks for your help,

I have the same python on my PI4 as on the PI3.
python -V
Python 3.9.2

I have done "pip3 install --pre pyload-ng[all]" with the mentioned error.

The log of the execution of "pip3 install --pre pyload-ng[all]" is  attached as pip_pyload.log

[pip_pyload.log](https://github.com/pyload/pyload/files/10667769/pip_pyload.log)

Error shown when executing pyload after pip:
` pyload
ModuleNotFoundError: No module named 'filetype'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyload/core/utils/fs.py", line 18, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyload", line 5, in <module>
    from pyload.script import main
  File "/usr/local/lib/python3.9/dist-packages/pyload/script.py", line 9, in <module>
    from .core import Core
  File "/usr/local/lib/python3.9/dist-packages/pyload/core/__init__.py", line 22, in <module>
    from .utils import format, fs
  File "/usr/local/lib/python3.9/dist-packages/pyload/core/utils/format.py", line 9, in <module>
    from .fs import fullpath
  File "/usr/local/lib/python3.9/dist-packages/pyload/core/utils/fs.py", line 21, in <module>
    from filetype import guess_mime
ModuleNotFoundError: No module named 'filetype'
`

When doing "pip install filetype" to solve this and executing "pyload" again I get:
`root@raspberrypi:~# pyload
ModuleNotFoundError: No module named 'pyload.core.config'
Traceback (most recent call last):
  File "/usr/local/bin/pyload", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/pyload/script.py", line 124, in main
    run(core_args, args.daemon)
  File "/usr/local/lib/python3.9/dist-packages/pyload/script.py", line 108, in run
    pyload_core = Core(*core_args)
  File "/usr/local/lib/python3.9/dist-packages/pyload/core/__init__.py", line 91, in __init__
    self._init_config(userdir, cachedir, storagedir, debug)
  File "/usr/local/lib/python3.9/dist-packages/pyload/core/__init__.py", line 107, in _init_config
    from .config.parser import ConfigParser
ModuleNotFoundError: No module named 'pyload.core.config'
`

Thanks and best regards,
Stefan

**Comment by StefanRu1** [comment]
Ok, i found it out.

The error in the log:
[Errno 2] No such file or directory: 'curl-config'
when installing pycurl-7.45.2 made me wonder.

So I searched for solutions and found:
sudo apt install libcurl4-openssl-dev libssl-dev

This helped to build pycurl-7.45.2 without problem.

But pyload still did not work after "pip3 install --pre pyload-ng[all]"

So I did a:
pip uninstall -y -r <(pip freeze)

And installed again.

Afterwards pyload started :-)

Is it possible to mention this somewhere?
The error is occurring on a fresh raspberry setup, so I think more people have this problem.

Thanks!

**Comment by GammaC0de** [comment]
>And installed again.
>
>Afterwards pyload started :-)

Great ;)

>Is it possible to mention this somewhere?
The error is occurring on a fresh raspberry setup, so I think more people have this problem.

If you like, you are welcome to post here a new installation guide to replace the very old one in https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi)

Meantime I close this issue as resolved.

**Comment by StefanRu1** [comment]
Hi, yes i would update the wiki page.
Can you give me access rights? 
Or should I write it and send you?

Thanks,
Stefan

**Comment by GammaC0de** [comment]
Yes, please write and send here or by email if you prefer.

**Comment by StefanRu1** [comment]
Hi,

 

so i have written a first Version which should work.

If there should be problems i am willing to investigate.

 

Here is the Wiki:


Step by Step Installation (RaspberryPi)

Installing pyLoad-ng on a Raspberry Pi with Raspbian Bullseye

In the following, I assume that you are running a Raspberry Pi with a recent version of Raspbian. At the point of writing this means you are running some version of Debian Bullseye.

We will install the pyload-ng using pip.

First, we are going to create a system user for running pyload.
sudo adduser --system pyload

Next we are installing some dependencies for pyLoad-ng. 
sudo apt install libcurl4-openssl-dev libssl-dev

Now we install pyload
sudo pip install --pre pyload-ng[all]

For more information about this command see: https://pypi.org/project/pyload-ng/

Pyload will be installed in: /usr/local/bin/pyload

Test pyload with calling pyload as user pyload.
runuser -u pyload --command pyload 

Pyload will start on localhost:8000.

You can access the web UI from your local raspberry browser only since it is bound to localhost.

In the web UI use user pyload and password pyload to do the configuration.

If you are running headless and need to access the web UI from another host in your local network edit the file:
/home/pyload/.pyload/settings/pyload.cfg

In this file under the section webui - "Web Interface": you will find:
ip host : "IP address" = localhost

change this to:
ip host : "IP address" = <your local ip>

Then start 
runuser -u pyload --command pyload

You should be able to access the web UI now from any host on your local network with this <your local ip>:8000.

After the first start config files will be created in: /home/pyload/.pyload/settings

If you want to start pyload at every reboot you can create a systemd service file for that. Just create a new file
sudo nano /lib/systemd/system/pyload.service
and dump the following code in there.

[Unit]

Description=Python Downloader

After=network-online.target nss-lookup.target local-fs.target remote-fs.target 

 

[Service]

User=pyload

ExecStart=/usr/local/bin/pyload

 

[Install]

WantedBy=multi-user.target

 

Now we need to activate this rule with systemd.
sudo systemctl enable pyload.service

You can test the service by calling 

sudo systemctl start pyload

 

And verify the start with

sudo systemctl status pyload

 

After a reboot, this should automatically be executed, and you can see the status of the service with

sudo systemctl status pyload

 



Best regards,

Stefan

 

Gesendet: Dienstag, 07. Februar 2023 um 19:00 Uhr
Von: "GammaC0de" ***@***.***>
An: "pyload/pyload" ***@***.***>
Cc: "StefanRu1" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pyload/pyload] No module named 'pyload.core.config' when installing pip install pyload-ng (Issue #4252)


 

Yes, please write and send here or by email if you prefer.

**Comment by StefanRu1** [comment]
Ah i want to add:
Updates can be done by executing:
sudo pip install --pre pyload-ng[all] -U

**Comment by StefanRu1** [comment]
And another error i found "runuser -u pyload --command pyload" 
must be runuser -u pyload -- pyload

**Comment by GammaC0de** [comment]
Ok, thanks, page updated. 👍

**Comment by StefanRu1** [comment]
You are welcome. 
I there should be questions or problems with the raspberry install wiki you can inform me and i will try to help.

Best regards,
Stefan
