### ISSUE TITLE
pyload does not start after updating from 4.9 to 4.20

### ISSUE THREAD

**Issue by geronimoronin** [pyload/pyload#4254]
### Description
pyload does not start after updating from 4.9 to 4.20
update was carried out according to these instructions
https://github.com/pyload/pyload/issues/3520

System DDWRT --> Entware-ng
everything worked last week and 4.9 works too, but 4.20 doesn't

### Debug log
08.02.2023 12:59:30 INFO      starte pyLoad 0.4.20
08.02.2023 12:59:30 INFO      Benutze Home-Verzeichnis: /opt/var/pyload
08.02.2023 12:59:32 INFO      Aktivierte Plugins: ClickNLoad, EventMapper, Exter                                                                                                                                               nalScripts, ExtractArchive, MergeFiles, TORRENT, UnSkipOnFail, UpdateManager, Us                                                                                                                                               erAgentSwitcher, XFileSharing
08.02.2023 12:59:32 INFO      Deaktivierte Plugins: AntiCaptcha, AntiStandby, An                                                                                                                                               tiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, Dea                                                                                                                                               thByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders,                                                                                                                                                HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LogMarker, MultiHome, Pus                                                                                                                                               hBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify,                                                                                                                                                XMPP
08.02.2023 12:59:32 INFO      Downloadzeit: True
08.02.2023 12:59:32 INFO      Starte ThriftBackend: 0.0.0.0:7227
08.02.2023 12:59:34 INFO      Starting builtin webserver: :::8000
08.02.2023 12:59:34 INFO      Free space: 3.49 GiB
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/share/pyload/module/web/ServerThread.py", line 78, in run
    self.start_builtin()
  File "/opt/share/pyload/module/web/ServerThread.py", line 85, in start_builtin
    webinterface.run_simple(host=self.host, port=self.port)
  File "/opt/share/pyload/module/web/webinterface.py", line 139, in run_simple
    run(app=web, host=host, port=port, quiet=True)
  File "/opt/share/pyload/module/lib/bottle.py", line 3137, in run
    server.run(app)
  File "/opt/share/pyload/module/lib/bottle.py", line 2789, in run
    srv = make_server(self.host, self.port, app, server_cls, handler_cls)
  File "/opt/lib/python2.7/wsgiref/simple_server.py", line 151, in make_server
  File "/opt/lib/python2.7/SocketServer.py", line 414, in __init__
  File "/opt/lib/python2.7/socket.py", line 191, in __init__
error: [Errno 97] Address family not supported by protocol

08.02.2023 12:59:34 INFO      Activating Accounts...
08.02.2023 12:59:34 INFO      Activating Plugins...
08.02.2023 12:59:34 WARNING   ADDON TORRENT: torrents / magnets are not associat                                                                                                                                               ed with any plugin
08.02.2023 12:59:34 INFO      ADDON UpdateManager: pyLoad is up to date!
08.02.2023 12:59:36 INFO      ADDON XFileSharing: Auto-discover new hosters
08.02.2023 12:59:36 INFO      ADDON XFileSharing: Auto-discover new crypters
08.02.2023 12:59:36 INFO      pyLoad is up and running
08.02.2023 12:59:37 INFO      ADDON UpdateManager: All plugins are up to date!
08.02.2023 12:59:42 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666

```

```

**Comment by GammaC0de** [comment]
@geronimoronin Does your system support IPv6?
Another thing, try changing pyload's web server type to `threaded`.

**Comment by geronimoronin** [comment]
Thanks, activiting IPv6 in the ddwrt, and switching to threaded, it works again. Just changing to threaded didnt work. This has brought me almost to despair the last few days.
Big thanks to GammaC0de

**Comment by GammaC0de** [comment]
👍
