### ISSUE TITLE
Files skipped when downloading from Zippyshare with Linksnappy

### ISSUE THREAD

**Issue by AlexR2106** [pyload/pyload#4257]
Hey!
When downloading from Zippyshare via a Linksnappy Premium Account many of the files are marked as skipped and have to be restarted. Restarting all at once, leads to the same issue, except for 1 or 2 files, which start as expected.
When restarting the skipped files one after another it works perfectly fine.
Seems, that there is a little issue when too many files are started at the same time.

Thanks
Alex
`<html><body>

0468 | 2023-02-19 01:41:03 | INFO | pyload | ACCOUNT LinksnappyCom: Grabbing account info for user `352****`...
-- | -- | -- | -- | --
20469 | 2023-02-19 01:41:03 | DEBUG | pyload | ACCOUNT LinksnappyCom: LOAD URL https://linksnappy.com/api/USERDETAILS \| get={'username': '352****', 'password': '**********'} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
20470 | 2023-02-19 01:41:03 | WARNING | pyload | DOWNLOADER LinksnappyCom[126]: LinksnappyCom \| Could not determine traffic usage for host www92.zippyshare.com
20471 | 2023-02-19 01:41:03 | INFO | pyload | DOWNLOADER LinksnappyCom[126]: LinksnappyCom \| Processing as premium download...
20472 | 2023-02-19 01:41:03 | DEBUG | pyload | DOWNLOADER LinksnappyCom[126]: LinksnappyCom \| LOAD URL https://linksnappy.com/api/linkgen \| get={'genLinks': '{"link": "http://www92.zippyshare.com/v/5QfaBl91/file.html"}'} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
20473 | 2023-02-19 01:41:03 | DEBUG | pyload | ACCOUNT LinksnappyCom: Account info for user `352****`: {'login': {'password': '**********', 'timestamp': 1676767231.7839377, 'valid': True}, 'data': {'login': '352****', 'maxtraffic': None, 'options': {'limit_dl': ['0']}, 'plugin': <Account LinksnappyCom>, 'premium': True, 'trafficleft': -1, 'type': 'LinksnappyCom', 'validuntil': 1684521712.0, 'hosters': ['alfafile.net', 'clicknupload.link', 'dailymotion.com', 'daofile.com', 'ddownload.com', 'dropapk.to', 'easybytez.com', 'file.al', 'filefactory.com', 'filefox.cc', 'filenext.com', 'filer.net', 'filespace.com', 'flashbit.cc', 'gigapeta.com', 'heroupload.com', 'hitfile.net', 'hotlink.cc', 'isra.cloud', 'katfile.com', 'keep2share.cc', 'mediafire.com', 'mega.co.nz', 'onefichier.com', 'prefiles.com', 'rapidgator.net', 'salefiles.com', 'solidfiles.com', 'soundcloud.com', 'tezfiles.com', 'turbobit.net', 'twoshared.com', 'ubiqfile.com', 'ultramegabit.com', 'uptobox.com', 'wdupload.com', 'zippyshare.com']}}
20474 | 2023-02-19 01:41:03 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_processed`
20475 | 2023-02-19 01:41:03 | INFO | pyload | Download skipped: file.html due to ZippyshareCom
20476 | 2023-02-19 01:41:04 | INFO | pyload | Download starts: file.html
20477 | 2023-02-19 01:41:04 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_preparing`
20478 | 2023-02-19 01:41:04 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
20479 | 2023-02-19 01:41:04 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting maximum redirections to 10
20480 | 2023-02-19 01:41:04 | DEBUG | pyload | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
20481 | 2023-02-19 01:41:04 | DEBUG | pyload | DOWNLOADER LinksnappyCom[128]: LinksnappyCom \| Plugin version: 0.20
20482 | 2023-02-19 01:41:04 | DEBUG | pyload | DOWNLOADER LinksnappyCom[128]: LinksnappyCom \| Plugin status: testing
20483 | 2023-02-19 01:41:04 | WARNING | pyload | DOWNLOADER LinksnappyCom[128]: LinksnappyCom \| Plugin may be unstable
20484 | 2023-02-19 01:41:04 | INFO | pyload | ACCOUNT LinksnappyCom: Grabbing account info for user `352****`...
20485 | 2023-02-19 01:41:04 | DEBUG | pyload | ACCOUNT LinksnappyCom: LOAD URL https://linksnappy.com/api/USERDETAILS \| get={'username': '352****', 'password': '**********'} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
20486 | 2023-02-19 01:41:04 | DEBUG | pyload | ACCOUNT LinksnappyCom: Account info for user `352****`: {'login': {'password': '**********', 'timestamp': 1676767231.7839377, 'valid': True}, 'data': {'login': '352****', 'maxtraffic': None, 'options': {'limit_dl': ['0']}, 'plugin': <Account LinksnappyCom>, 'premium': True, 'trafficleft': -1, 'type': 'LinksnappyCom', 'validuntil': 1684521712.0, 'hosters': ['alfafile.net', 'clicknupload.link', 'dailymotion.com', 'daofile.com', 'ddownload.com', 'dropapk.to', 'easybytez.com', 'file.al', 'filefactory.com', 'filefox.cc', 'filenext.com', 'filer.net', 'filespace.com', 'flashbit.cc', 'gigapeta.com', 'heroupload.com', 'hitfile.net', 'hotlink.cc', 'isra.cloud', 'katfile.com', 'keep2share.cc', 'mediafire.com', 'mega.co.nz', 'onefichier.com', 'prefiles.com', 'rapidgator.net', 'salefiles.com', 'solidfiles.com', 'soundcloud.com', 'tezfiles.com', 'turbobit.net', 'twoshared.com', 'ubiqfile.com', 'ultramegabit.com', 'uptobox.com', 'wdupload.com', 'zippyshare.com']}}
20487 | 2023-02-19 01:41:04 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_processed`
20488 | 2023-02-19 01:41:04 | INFO | pyload | Download skipped: file.html due to ZippyshareCom
20489 | 2023-02-19 01:41:04 | INFO | pyload | DOWNLOADER LinksnappyCom[126]: LinksnappyCom \| Downloading file...
20490 | 2023-02-19 01:41:04 | DEBUG | pyload | DOWNLOADER LinksnappyCom[126]: LinksnappyCom \| DOWNLOAD URL http://dlserv15.linksnappy.com/files/FGWZwztYzg7dstSkiNz/604f0589-5c34-436e-8615-21134a31c923.part01.rar \| get={} \| post={} \| ref=True \| cookies=True \| disposition=True \| resume=None \| chunks=None
20491 | 2023-02-19 01:41:05 | INFO | pyload | Download starts: file.html
20492 | 2023-02-19 01:41:05 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_preparing`
20493 | 2023-02-19 01:41:05 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
20494 | 2023-02-19 01:41:05 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting maximum redirections to 10
20495 | 2023-02-19 01:41:05 | DEBUG | pyload | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
20496 | 2023-02-19 01:41:05 | DEBUG | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Plugin version: 0.20
20497 | 2023-02-19 01:41:05 | DEBUG | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Plugin status: testing
20498 | 2023-02-19 01:41:05 | WARNING | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Plugin may be unstable
20499 | 2023-02-19 01:41:05 | INFO | pyload | ACCOUNT LinksnappyCom: Grabbing account info for user `352****`...
20500 | 2023-02-19 01:41:05 | DEBUG | pyload | ACCOUNT LinksnappyCom: LOAD URL https://linksnappy.com/api/USERDETAILS \| get={'username': '352****', 'password': '**********'} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
20501 | 2023-02-19 01:41:05 | DEBUG | pyload | ACCOUNT LinksnappyCom: Account info for user `352****`: {'login': {'password': '**********', 'timestamp': 1676767231.7839377, 'valid': True}, 'data': {'login': '352****', 'maxtraffic': None, 'options': {'limit_dl': ['0']}, 'plugin': <Account LinksnappyCom>, 'premium': True, 'trafficleft': -1, 'type': 'LinksnappyCom', 'validuntil': 1684521712.0, 'hosters': ['alfafile.net', 'clicknupload.link', 'dailymotion.com', 'daofile.com', 'ddownload.com', 'dropapk.to', 'easybytez.com', 'file.al', 'filefactory.com', 'filefox.cc', 'filenext.com', 'filer.net', 'filespace.com', 'flashbit.cc', 'gigapeta.com', 'heroupload.com', 'hitfile.net', 'hotlink.cc', 'isra.cloud', 'katfile.com', 'keep2share.cc', 'mediafire.com', 'mega.co.nz', 'onefichier.com', 'prefiles.com', 'rapidgator.net', 'salefiles.com', 'solidfiles.com', 'soundcloud.com', 'tezfiles.com', 'turbobit.net', 'twoshared.com', 'ubiqfile.com', 'ultramegabit.com', 'uptobox.com', 'wdupload.com', 'zippyshare.com']}}
20502 | 2023-02-19 01:41:05 | INFO | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Processing url: https://www7.zippyshare.com/v/GqzXfzCt/file.html
20503 | 2023-02-19 01:41:05 | INFO | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Checking for link errors...
20504 | 2023-02-19 01:41:05 | WARNING | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| No data to check
20505 | 2023-02-19 01:41:05 | INFO | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Grabbing link info...
20506 | 2023-02-19 01:41:05 | DEBUG | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Link info: {'name': 'file.html', 'hash': {}, 'pattern': {}, 'size': 0, 'status': 7, 'url': 'http://www7.zippyshare.com/v/GqzXfzCt/file.html'}
20507 | 2023-02-19 01:41:05 | DEBUG | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Previous link info: {}
20508 | 2023-02-19 01:41:05 | INFO | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Link name: file.html
20509 | 2023-02-19 01:41:05 | INFO | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Link size: N/D
20510 | 2023-02-19 01:41:05 | INFO | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Link status: starting
20511 | 2023-02-19 01:41:05 | DEBUG | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| LOAD URL https://linksnappy.com/api/FILEHOSTS \| get={} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
20512 | 2023-02-19 01:41:05 | WARNING | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Could not determine traffic usage for host www7.zippyshare.com
20513 | 2023-02-19 01:41:05 | INFO | pyload | DOWNLOADER LinksnappyCom[129]: LinksnappyCom \| Processing as premium download...
 

</body>
</html>`

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
No response, closing.
