### ISSUE TITLE
Uptobox download don't start 

### ISSUE THREAD

**Issue by nbrgt** [pyload/pyload#4258]
Hi, 

When I try to download a Uptobox link, the download doesn't start... I can see the link in "queued" 
I have a Premium account and I think it's a bug from the plugin...

Somebody can help me ? 

Thx

**Comment by GammaC0de** [comment]
Is this a new installation?
What pyload version are you using?
Does it work on other sites?
Please provide debug logs.

**Comment by nbrgt** [comment]
No, but I reinstall it, I use seedbox.fr
The version is 0.4.20
I try with 1fichier link and it doesn't work too...

240 | 21.02.2023 12:47:00 | INFO | ACCOUNT UptoboxCom: Adding user `nic*******`...
-- | -- | -- | --
241 | 21.02.2023 12:47:00 | INFO | ACCOUNT UptoboxCom: Login user `nic*******`...
242 | 21.02.2023 12:47:01 | INFO | ACCOUNT UptoboxCom: Grabbing account info for user `nic*******`...
243 | 21.02.2023 12:48:32 | INFO | Added package movies containing 1 links
244 | 21.02.2023 12:48:50 | INFO | Added package test containing 1 links

**Comment by GammaC0de** [comment]
1. Please refresh your pyLoad installation using the instruction in #3283.
2. After that, please enable debug mode, retry and then post the logs.

**Comment by nbrgt** [comment]
I reinstall with my seedbox (can't install it manualy) and 2 first link work and download but the other links does'nt work... 

<div class="logdiv">

21.02.2023 23:02:03 | INFO | Download starts: https://uptobox.com/8ggi1eh5n72g
-- | -- | --
150 | 21.02.2023 23:02:03 | WARNING | HOSTER UptoboxCom[2]: Plugin may be unstable
151 | 21.02.2023 23:02:03 | INFO | ACCOUNT UptoboxCom: Grabbing account info for user `nic*******`...
152 | 21.02.2023 23:02:03 | INFO | HOSTER UptoboxCom[2]: Processing url: https://uptobox.com/8ggi1eh5n72g
153 | 21.02.2023 23:02:03 | INFO | HOSTER UptoboxCom[2]: Looking for direct download link...
154 | 21.02.2023 23:02:03 | INFO | HOSTER UptoboxCom[2]: Direct download link not found
155 | 21.02.2023 23:02:03 | INFO | HOSTER UptoboxCom[2]: Checking for link errors...
156 | 21.02.2023 23:02:03 | INFO | HOSTER UptoboxCom[2]: No errors found
157 | 21.02.2023 23:02:03 | INFO | HOSTER UptoboxCom[2]: Grabbing link info...
158 | 21.02.2023 23:02:03 | INFO | HOSTER UptoboxCom[2]: Link name:  Sharper.2023.MULTi.VFi.2160p.10bit.4KLight.DV.HDR10Plus.WEBRip.DDP.5.1.Atmos.x265-SAKADOX-Wawacity.hair.mkv
159 | 21.02.2023 23:02:03 | INFO | HOSTER UptoboxCom[2]: Link size: 3.82 GiB (4101693767 bytes)
160 | 21.02.2023 23:02:03 | INFO | HOSTER UptoboxCom[2]: Link status: en ligne
161 | 21.02.2023 23:02:03 | INFO | HOSTER UptoboxCom[2]: Processing as premium download...
162 | 21.02.2023 23:02:03 | INFO | HOSTER UptoboxCom[2]: Downloading file...
163 | 21.02.2023 23:02:24 | INFO | HOSTER UptoboxCom[1]: File saved
164 | 21.02.2023 23:02:24 | INFO | HOSTER UptoboxCom[1]: Checking download...
165 | 21.02.2023 23:02:24 | INFO | HOSTER UptoboxCom[1]: File is OK
166 | 21.02.2023 23:02:24 | INFO | HOSTER UptoboxCom[1]: Checking file (with built-in rules)...
167 | 21.02.2023 23:02:24 | INFO | HOSTER UptoboxCom[1]: Checking file (with custom rules)...
168 | 21.02.2023 23:02:24 | INFO | HOSTER UptoboxCom[1]: Checking for link errors...
169 | 21.02.2023 23:02:24 | INFO | HOSTER UptoboxCom[1]: No errors found
170 | 21.02.2023 23:02:24 | INFO | HOSTER UptoboxCom[1]: No errors found
171 | 21.02.2023 23:02:24 | INFO | Download finished: Bullet.Train.2022.MULTi.2160p.10bit.4KLight.HDR.WEBRip.EAC3.5.1.x265-Wawacity.red.mkv
172 | 21.02.2023 23:02:24 | INFO | Package finished: movies
173 | 21.02.2023 23:03:15 | INFO | Added package movies containing 1 links
174 | 21.02.2023 23:03:17 | INFO | Download starts: https://uptobox.com/g5ik22xvufp9
175 | 21.02.2023 23:03:17 | WARNING | HOSTER UptoboxCom[3]: Plugin may be unstable
176 | 21.02.2023 23:03:17 | INFO | ACCOUNT UptoboxCom: Grabbing account info for user `nic*******`...
177 | 21.02.2023 23:03:17 | INFO | HOSTER UptoboxCom[3]: Processing url: https://uptobox.com/g5ik22xvufp9
178 | 21.02.2023 23:03:17 | INFO | HOSTER UptoboxCom[3]: Looking for direct download link...
179 | 21.02.2023 23:03:17 | INFO | HOSTER UptoboxCom[3]: Direct download link not found
180 | 21.02.2023 23:03:17 | INFO | HOSTER UptoboxCom[3]: Checking for link errors...
181 | 21.02.2023 23:03:17 | WARNING | HOSTER UptoboxCom[3]: 1 hours 58 minutes 46 seconds
182 | 21.02.2023 23:03:17 | INFO | HOSTER UptoboxCom[3]: Waiting 1 hours, 58 minutes, 46 seconds...


</div>
<div class="logform">
  </div>

**Comment by nbrgt** [comment]
I reinstall with my seedbox (can't install it manualy) and 2 first link work and download but the other links does'nt work...
21.02.2023 23:02:03	INFO	HOSTER UptoboxCom[2]: Link size: 3.82 GiB (4101693767 bytes)
160	21.02.2023 23:02:03	INFO	HOSTER UptoboxCom[2]: Link status: en ligne
161	21.02.2023 23:02:03	INFO	HOSTER UptoboxCom[2]: Processing as premium download...
162	21.02.2023 23:02:03	INFO	HOSTER UptoboxCom[2]: Downloading file...
163	21.02.2023 23:02:24	INFO	HOSTER UptoboxCom[1]: File saved
164	21.02.2023 23:02:24	INFO	HOSTER UptoboxCom[1]: Checking download...
165	21.02.2023 23:02:24	INFO	HOSTER UptoboxCom[1]: File is OK
166	21.02.2023 23:02:24	INFO	HOSTER UptoboxCom[1]: Checking file (with built-in rules)...
167	21.02.2023 23:02:24	INFO	HOSTER UptoboxCom[1]: Checking file (with custom rules)...
168	21.02.2023 23:02:24	INFO	HOSTER UptoboxCom[1]: Checking for link errors...
169	21.02.2023 23:02:24	INFO	HOSTER UptoboxCom[1]: No errors found
170	21.02.2023 23:02:24	INFO	HOSTER UptoboxCom[1]: No errors found
171	21.02.2023 23:02:24	INFO	Download finished: Bullet.Train.2022.MULTi.2160p.10bit.4KLight.HDR.WEBRip.EAC3.5.1.x265-Wawacity.red.mkv
172	21.02.2023 23:02:24	INFO	Package finished: movies
173	21.02.2023 23:03:15	INFO	Added package movies containing 1 links
174	21.02.2023 23:03:17	INFO	Download starts: https://uptobox.com/g5ik22xvufp9
175	21.02.2023 23:03:17	WARNING	HOSTER UptoboxCom[3]: Plugin may be unstable
176	21.02.2023 23:03:17	INFO	ACCOUNT UptoboxCom: Grabbing account info for user `nic*******`...
177	21.02.2023 23:03:17	INFO	HOSTER UptoboxCom[3]: Processing url: https://uptobox.com/g5ik22xvufp9
178	21.02.2023 23:03:17	INFO	HOSTER UptoboxCom[3]: Looking for direct download link...
179	21.02.2023 23:03:17	INFO	HOSTER UptoboxCom[3]: Direct download link not found
180	21.02.2023 23:03:17	INFO	HOSTER UptoboxCom[3]: Checking for link errors...
181	21.02.2023 23:03:17	WARNING	HOSTER UptoboxCom[3]: 1 hours 58 minutes 46 seconds
182	21.02.2023 23:03:17	INFO	HOSTER UptoboxCom[3]: Waiting 1 hours, 58 minutes, 46 seconds...
183	21.02.2023 23:06:03	INFO	HOSTER UptoboxCom[2]: File saved
184	21.02.2023 23:06:03	INFO	HOSTER UptoboxCom[2]: Checking download...
185	21.02.2023 23:06:03	INFO	HOSTER UptoboxCom[2]: File is OK
186	21.02.2023 23:06:03	INFO	HOSTER UptoboxCom[2]: Checking file (with built-in rules)...
187	21.02.2023 23:06:03	INFO	HOSTER UptoboxCom[2]: Checking file (with custom rules)...
188	21.02.2023 23:06:03	INFO	HOSTER UptoboxCom[2]: Checking for link errors...
189	21.02.2023 23:06:03	INFO	HOSTER UptoboxCom[2]: No errors found
190	21.02.2023 23:06:03	INFO	HOSTER UptoboxCom[2]: No errors found
191	21.02.2023 23:06:03	INFO	Download finished: Sharper.2023.MULTi.VFi.2160p.10bit.4KLight.DV.HDR10Plus.WEBRip.DDP.5.1.Atmos.x265-SAKADOX-Wawacity.hair.mkv
192	21.02.2023 23:06:03	INFO	Package finished: movies

**Comment by GammaC0de** [comment]
You have to enable debug mode:
Go to settings -> General -> Debug mode

**Comment by nbrgt** [comment]
I did it
I think that the problem is plugin, I have a premium account on Uptobox but Pyload don't recognize it

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by nbrgt** [comment]
Uptobox account or Pyload account ?

**Comment by GammaC0de** [comment]
Uptobox of course.

**Comment by GammaC0de** [comment]
Info received. 👍🏻

**Comment by GammaC0de** [comment]
Please disable geo-location restrictions..

**Comment by nbrgt** [comment]
It's done

**Comment by GammaC0de** [comment]
It works fine for me.

Are you using pyload v0.4.20 or 0.5?

**Comment by nbrgt** [comment]
I use pyload 0.4.20 with a seedbox so I have not choice to use this version..

**Comment by GammaC0de** [comment]
I guess the seedbox installation is buggy, maybe its an old version.

Maybe you can ask them to follow the instructions in https://github.com/pyload/pyload/issues/3283.

Closing.
