### ISSUE TITLE
Newbie need help

### ISSUE THREAD

**Issue by Jagsi1981** [pyload/pyload#4264]
### Cannot edit the file /home/pyload/.pyload/settings/pyload.cfg - to get access from my network

I am pretty sure there is an easy answer but after 2 hours of trying and googeling I need your help - I cannot access the file which I have to change - I always get "Permission denied" 
If I type sudo in front of it "command not found" 

I think the installation was successfully because when I look the status it says it is running but I cannot access the Web Gui 

Thank you very much for your help

**Comment by jd1** [comment]
Which command do you try to run? Can you share the complete steps you tried?

**Comment by Jagsi1981** [comment]
Actually finally a friend of mine did it and it works now - the next problem I have now is that I want to add a network folder from my NAS and I don't know how to do it - is there maybe a plug-in or something?

**Comment by GammaC0de** [comment]
You have to mount the network folder so it it accessible to the OS and then you can access it from any program on that machine.

**Comment by Jagsi1981** [comment]
Can you support me how to do this?

**Comment by jd1** [comment]
I'm sorry, but this doesn't belong here. If you need help for Linux (I guess you are using Linux - unfortunately you haven't provided any information about your system), ask your friend, in a forum, on stackoverflow or even in a [discussion]( https://github.com/pyload/pyload/discussions), but this isn't a pyload issue.
Here is one last helpful link: https://www.google.com/search?q=mount+samba+share+linux
