### ISSUE TITLE
Plugin for FileBit.net

### ISSUE THREAD

**Issue by michnixweiss** [pyload/pyload#4266]
### Description
Can someone write a plugin for FileBit.net

### Sample resources
https://filebit.net/f/BeZO21c?i=?i=filebit01112022#AY8mW7CUFiBH13XcJ1jhjVpW59nm--q1L9Nt8067OVpQ

**Comment by michnixweiss** [comment]
Is this project still maintained (by
@vuolter and @GammaC0de) ?

**Comment by GammaC0de** [comment]
Correct.

I'm a little bit busy recently (have to deal with some life issues so github issues come later) so everything is a little bit slower here

**Comment by michnixweiss** [comment]
No problem, but can you give me a timetable? More or less...
