### ISSUE TITLE
REPODIR

### ISSUE THREAD

**Issue by p6002** [pyload/pyload#4267]
Whats that mean?
`Replace <REPODIR> with the location on the host machine where you have checked out the pyload repository.
`
I dont check nothing, what I need to check?

`---
version: '2'
services:
  pyload:
    image: pyload
    build: <REPODIR>
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - <USERDIR>:/config
      - <STORAGEDIR>:/downloads
    ports:
      - 8000:8000 # Webinterface
      - 9666:9666 # Click 'N' Load
    restart: unless-stopped`

**Comment by p6002** [comment]
Ok solution here:
https://hub.docker.com/r/linuxserver/pyload-ng

**Comment by GammaC0de** [comment]
👍
