### ISSUE TITLE
MAC OS and 'Enter' key in SolveMedia captcha issue

### ISSUE THREAD

**Issue by GreenSnakeLinux** [pyload/pyload#4272]
### Description

On MAC OS (Mac air book M1) I cannot do 'enter' after put the text in the text field of SolveMedia captcha
(I can do 'Escape' key but only if the text field is focus)
It work on Windows, so I suppect a issue in the gui script that do not recognize the 'enter' key of MAC OS

### Additional references

RapidGator link to reproduce:
https://rapidgator.net/file/0b9d618431ea9fbc0ad7df388cc84421

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/38be12874b121405de85e7ab68fab6a8e8a87a89 fixes the hidden button, you have to use the `develop` branch to to get the fix before it gets to the `main` branch.

**Comment by GammaC0de** [comment]
@GreenSnakeLinux Tis fix is now in the `main` branch also.
