### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by MasterOfBytes** [pyload/pyload#4273]
### Description

Hello,
i recently upgraded pyLoad to Version 0.5.0b3.dev53 and now i'm getting an error on every download:

> SSL certificate problem: unable to get local issuer certificate

### Debug log

```
TRACEBACK:
 Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/pyload/core/threads/download_thread.py", line 56, in run
    pyfile.plugin.preprocessing(self)
  File "/home/pi/.local/lib/python3.10/site-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
    return self._process(*args, **kwargs)
  File "/home/pi/.local/lib/python3.10/site-packages/pyload/plugins/base/downloader.py", line 103, in _process
    self.process(self.pyfile)
  File "/home/pi/.local/lib/python3.10/site-packages/pyload/plugins/base/simple_downloader.py", line 286, in process
    self.download(self.link, disposition=self.DISPOSITION)
  File "/home/pi/.local/lib/python3.10/site-packages/pyload/plugins/base/downloader.py", line 332, in download
    newname = self._download(
  File "/home/pi/.local/lib/python3.10/site-packages/pyload/plugins/base/downloader.py", line 238, in _download
    newname = self.req.http_download(
  File "/home/pi/.local/lib/python3.10/site-packages/pyload/core/network/browser.py", line 116, in http_download
    name = self.dl.download(chunks, resume)
  File "/home/pi/.local/lib/python3.10/site-packages/pyload/core/network/http/http_download.py", line 132, in download
    self._download(chunks, resume)
  File "/home/pi/.local/lib/python3.10/site-packages/pyload/core/network/http/http_download.py", line 276, in _download
    raise ex or Exception
pycurl.error: (60, 'SSL certificate problem: unable to get local issuer certificate')
```

[debug_DdownloadCom_2023-03-24_12-36-21.zip](https://github.com/pyload/pyload/files/11061592/debug_DdownloadCom_2023-03-24_12-36-21.zip)

### Additional references

pip3 list and Python Version:

```
pi@raspberrypi:~ $ pip3 list
Package               Version
--------------------- -------------
aiodns                3.0.0
Babel                 2.12.1
beautifulsoup4        4.12.0
bitmath               1.3.3.1
Brotli                1.0.9
cachelib              0.10.2
certifi               2022.12.7
cffi                  1.15.1
cheroot               8.6.0
click                 8.1.3
colorlog              6.7.0
cryptography          40.0.0
filetype              1.2.0
Flask                 2.2.3
Flask-Babel           1.0.0
Flask-Caching         1.11.1
Flask-Compress        1.13
Flask-Session         0.4.0
Flask-Themes2         1.0.0
itsdangerous          2.1.2
jaraco.functools      3.6.0
Jinja2                3.0.3
Js2Py                 0.74
MarkupSafe            2.1.2
more-itertools        9.1.0
Pillow                9.4.0
pip                   23.0.1
pyasn1                0.5.0rc2
pyasn1-modules        0.3.0rc1
pycares               4.3.0
pycparser             2.21
pycurl                7.45.2
pyjsparser            2.7.1
pyload-ng             0.5.0b3.dev53
pyOpenSSL             23.1.0
pytz                  2022.7.1
pytz-deprecation-shim 0.1.0.post0
semver                2.13.0
Send2Trash            1.8.1b0
setuptools            65.5.0
six                   1.16.0
slixmpp               1.8.3
soupsieve             2.4
tzdata                2022.7
tzlocal               4.4b1
Werkzeug              2.2.3
pi@raspberrypi:~ $ python3 --version
Python 3.10.10
```

System Info from pyLoad

```
Python Version:3.10.10 (main, Mar 24 2023, 10:53:08) [GCC 8.3.0]
OS Platform:posix linux Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l
```

**Comment by GammaC0de** [comment]
This is either pycurl error or a server error.

The only thing that can be done from pLoad's side is to disable `Verify SSL certificates` settings (it's in the general section)

**Comment by GammaC0de** [comment]
I forgot to mention that disabling `Verify SSL certificates`  of-course reduces security.
One this to to try before disabling `Verify SSL certificates` is to update the `certifi` package to the latest version.

**Comment by MasterOfBytes** [comment]
As you can see in the pip3 list posted
```
certifi               2022.12.7
pycurl                7.45.2
```
certifi ( and pyCurl ) is the latest version, as i found this hint allready.

Disabling SSL Verification is working now. Thanks so far.

**Comment by godfuture** [comment]
In my case the ddownload.com root, intermediate and server cert were fine.

Is this an issue of certificate chain or simply a bug in cert verification?

**Comment by GammaC0de** [comment]
> Is this an issue of certificate chain or simply a bug in cert verification?

I absolutely have no idea what causes this since all the certificate verification process is done inside pycurl and I have no control of it.

So the only thing that can be done is disable SSL Verification in pyLoad's configuration.

**Comment by fumazu** [comment]
For the record, this appears to be a server-side issue with the cdn*.rapidshare.to links handed out by ddownload.

https://whatsmychaincert.com/?cdn61.rapidshare.to

also:
```bash
$ openssl s_client -showcerts -connect cdn61.rapidshare.to:443
CONNECTED(00000003)
depth=0 CN = *.rapidshare.to
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = *.rapidshare.to
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = *.rapidshare.to
verify return:1
```

**Comment by GammaC0de** [comment]
@fumazu Thanks for the explanation.

**Comment by dr3st** [comment]
As temporary workarround you can download the CA certs (via browser for example) and add them to certifi's cert-store.
I downloaded the ca certs and added them to /usr/lib/python3.10/site-packages/certifi/cacert.pem

This worked after a pyload restart. Not the best, but atm the easiest way.

You better check the correct CA-certs, but this is what I've done in detail:

`
docker exec -ti pyload bash
cat >> /usr/lib/python3.10/site-packages/certifi/cacert.pem <<EOF
-----BEGIN CERTIFICATE-----
MIIGOTCCBSGgAwIBAgIMVNHkysT8DTKpECEIMA0GCSqGSIb3DQEBCwUAMEwxCzAJ
BgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMSIwIAYDVQQDExlB
bHBoYVNTTCBDQSAtIFNIQTI1NiAtIEc0MB4XDTIzMDExOTE1MjUxMVoXDTI0MDIy
MDE1MjUxMFowFDESMBAGA1UEAwwJKi51Y2RuLnRvMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEA1xcIm2cBuDPJ6RggIigejfm0n2C/Xf1hy3hMkAhkoUtV
RcTGxgPLX15tJ8miUgZ/2qpVS5KIZmYdtNb+BFOyz5edlEJAXz3m3Fdj2ZPRsPy6
inmlP8NWIvYZYc30JCFhU/eK175wSTNvlln6j8/xe0xsvil7QoZy1UB9LNrgJH5C
9FMJa6uJdOEojJes+TMGAsfViZdQsGK1/VzUe7d01V1S7XmIP1nYBaOsO2YIKWTP
DZtF4D/AQdt7DSLcxCHr4OYleCoAil/hO8zx89d0b8l8Ln+CPIZ/L4Ap8Wxjvctj
teFkwkwbrPUd1XIU3oQ8SMEeoh7giKpB7WGiKaZInQIDAQABo4IDUTCCA00wDgYD
VR0PAQH/BAQDAgWgMIGTBggrBgEFBQcBAQSBhjCBgzBGBggrBgEFBQcwAoY6aHR0
cDovL3NlY3VyZS5nbG9iYWxzaWduLmNvbS9jYWNlcnQvYWxwaGFzc2xjYXNoYTI1
Nmc0LmNydDA5BggrBgEFBQcwAYYtaHR0cDovL29jc3AuZ2xvYmFsc2lnbi5jb20v
YWxwaGFzc2xjYXNoYTI1Nmc0MFcGA1UdIARQME4wCAYGZ4EMAQIBMEIGCisGAQQB
oDIKAQMwNDAyBggrBgEFBQcCARYmaHR0cHM6Ly93d3cuZ2xvYmFsc2lnbi5jb20v
cmVwb3NpdG9yeS8wCQYDVR0TBAIwADBBBgNVHR8EOjA4MDagNKAyhjBodHRwOi8v
Y3JsLmdsb2JhbHNpZ24uY29tL2FscGhhc3NsY2FzaGEyNTZnNC5jcmwwHQYDVR0R
BBYwFIIJKi51Y2RuLnRvggd1Y2RuLnRvMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
BgEFBQcDAjAfBgNVHSMEGDAWgBRPy6yowu+r3YNva7/OmD1cWCV2FTAdBgNVHQ4E
FgQULB7lGZylt/9CGqlejInsLQG86L8wggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoB
aAB2AEiw42vapkc0D+VqAvqdMOscUgHLVt0sgdm7v6s52IRzAAABhcqiURwAAAQD
AEcwRQIgFY2juJ5m36+rQOOIRHT9HK3hyjjYoiXfcnwBb9vpwGQCIQDl+JpkWLU1
9qVkJ6sq9//S5ieGE0r4euuHFykBOYI/nQB2AHb/iD8KtvuVUcJhzPWHujS0pM27
KdxoQgqf5mdMWjp0AAABhcqiUUsAAAQDAEcwRQIgSEBFb6LxyBloKp7Hq9E5vz4Z
SLT+YFP+x0Eheld7nIkCIQCSonq31ocbGdajw+BUvvVyEB5eWpMaX9A4LTGvNY8K
HAB2ANq2v2s/tbYin5vCu1xr6HCRcWy7UYSFNL2kPTBI1/urAAABhcqiUTgAAAQD
AEcwRQIhAIJ+phIL1JISaBxVggkxhU/OVWmEIsuXJEiKGMEevNeFAiBA3xTmaP6D
BfIrw40zqJVWgoU+vofRzfxphc0hOglK2jANBgkqhkiG9w0BAQsFAAOCAQEAOQ60
Bjh0E/qY2Q6BQaRTZu440OTI68Ys1uNPxBWZx0omPd8GAG+azZqpDvPubmxpGJdQ
9jOTEDN0h44kKuThxafQEtFolZ46cfhYM5BaA6FSBnSiLcBcp9XKd8JDQyPEbTP/
3wpXQKLzgAFRabmBvCPa8706P1ongMUGbZ5OboFzVMJaCTU0HR9u8XGNPqs7cHva
gwlfkFxt3/7QeufaZWYhbs3IlPckj1kAzTwhZDyUHB3Ij2qBqwKGwz258yrCOJgh
RRG8Rz4a8UdwarDayphTuGYrNnwarMlSISd41dQtQprUgCMfk4ZQZh+oaXF0Goqa
xj9CVxcQT2kZuWU0hg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEijCCA3KgAwIBAgIQfU1CqStDHX5kU+fBmo1YdzANBgkqhkiG9w0BAQsFADBX
MQswCQYDVQQGEwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEQMA4GA1UE
CxMHUm9vdCBDQTEbMBkGA1UEAxMSR2xvYmFsU2lnbiBSb290IENBMB4XDTIyMTAx
MjAzNDk0M1oXDTI3MTAxMjAwMDAwMFowTDELMAkGA1UEBhMCQkUxGTAXBgNVBAoT
EEdsb2JhbFNpZ24gbnYtc2ExIjAgBgNVBAMTGUFscGhhU1NMIENBIC0gU0hBMjU2
IC0gRzQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCtJCmVZhWIPzOH
A3jP1QwkuDFT8/+DImyZlSt85UpZwq7G0Sqd+n8gLlHIZypQkad5VkT7OLU+MI78
lC7LVwxpU19ExlaWL67ANyWG8XHx3AJFQoZhuDbvUeNzRQyQs6XS5wN6uDlF0Bf1
AtCUQWrGGLGYwyC1xTrzgrFKpESsIXMqklUGTsh8i7DKZhRUVfgrPLJUkbbLUrLY
42+KRCiwfSvBloC5PgDYnj3oMZ1aTe3Wfk3l1I4D3RKaJ4PU1qHXhHJOge2bjGIG
l6MsaBN+BB2sr6EnxX0xnMIbew2oIfOFoLqs47vh/GH4JN0qql2WBHfDPVDm3b+G
QxY6N/LXAgMBAAGjggFbMIIBVzAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYE
FE/LrKjC76vdg29rv86YPVxYJXYVMB8GA1UdIwQYMBaAFGB7ZhpFDZfKiVAvfQTN
NKj//P1LMHoGCCsGAQUFBwEBBG4wbDAtBggrBgEFBQcwAYYhaHR0cDovL29jc3Au
Z2xvYmFsc2lnbi5jb20vcm9vdHIxMDsGCCsGAQUFBzAChi9odHRwOi8vc2VjdXJl
Lmdsb2JhbHNpZ24uY29tL2NhY2VydC9yb290LXIxLmNydDAzBgNVHR8ELDAqMCig
JqAkhiJodHRwOi8vY3JsLmdsb2JhbHNpZ24uY29tL3Jvb3QuY3JsMCEGA1UdIAQa
MBgwCAYGZ4EMAQIBMAwGCisGAQQBoDIKAQMwDQYJKoZIhvcNAQELBQADggEBABol
9nNkiECpWQenQ7oVP1FhvRX/LWTdzXpdMmp/SELnEJhoOe+366E0dt8tWGg+ezAc
DPeGYPmp83nAVLeDpji7Nqu8ldB8+G/B6U9GB8i2DDIAqSsFEvcMbWb5gZ2/DmRN
cifGi9FKAuFu2wyft4s4DHwzL2CJ2zjMlUOM3RaE1cxuOs+Om6MCD9G7vnkAtSiC
/OOfHO902f4yI2a48K+gKaAf3lISFXjd32pwQ21LpM3ueIGydaJ+1/z8nv+C7SUT
5bHoz7cYU27LUvh1n2WSNnC6/QwFSoP6gNKa4POO/oO13xjhrLRHJ/04cKMbRALt
JWQkPacJ8SJVhB2R7BI=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDdTCCAl2gAwIBAgILBAAAAAABFUtaw5QwDQYJKoZIhvcNAQEFBQAwVzELMAkG
A1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNVBAsTB1Jv
b3QgQ0ExGzAZBgNVBAMTEkdsb2JhbFNpZ24gUm9vdCBDQTAeFw05ODA5MDExMjAw
MDBaFw0yODAxMjgxMjAwMDBaMFcxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9i
YWxTaWduIG52LXNhMRAwDgYDVQQLEwdSb290IENBMRswGQYDVQQDExJHbG9iYWxT
aWduIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDaDuaZ
jc6j40+Kfvvxi4Mla+pIH/EqsLmVEQS98GPR4mdmzxzdzxtIK+6NiY6arymAZavp
xy0Sy6scTHAHoT0KMM0VjU/43dSMUBUc71DuxC73/OlS8pF94G3VNTCOXkNz8kHp
1Wrjsok6Vjk4bwY8iGlbKk3Fp1S4bInMm/k8yuX9ifUSPJJ4ltbcdG6TRGHRjcdG
snUOhugZitVtbNV4FpWi6cgKOOvyJBNPc1STE4U6G7weNLWLBYy5d4ux2x8gkasJ
U26Qzns3dLlwR5EiUWMWea6xrkEmCMgZK9FGqkjWZCrXgzT/LCrBbBlDSgeF59N8
9iFo7+ryUp9/k5DPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8E
BTADAQH/MB0GA1UdDgQWBBRge2YaRQ2XyolQL30EzTSo//z9SzANBgkqhkiG9w0B
AQUFAAOCAQEA1nPnfE920I2/7LqivjTFKDK1fPxsnCwrvQmeU79rXqoRSLblCKOz
yj1hTdNGCbM+w6DjY1Ub8rrvrTnhQ7k4o+YviiY776BQVvnGCv04zcQLcFGUl5gE
38NflNUVyRRBnMRddWQVDf9VMOyGj/8N7yy5Y0b2qvzfvGn9LhJIZJrglfCm7ymP
AbEVtQwdpf5pLGkkeB6zpxxxYu7KyJesF12KwvhHhm4qxFYxldBniYUr+WymXUad
DKqC5JlR3XC321Y9YeRq4VzW9v493kHMB65jUr9TU/Qr6cf9tveCX4XSQRjbgbME
HMUfpIBvFSDJ3gyICh3WZlXi/EjJKSZp4A==
-----END CERTIFICATE-----
EOF

exit
docker restart pyload
`

**Comment by GammaC0de** [comment]
@ddownloadcom can you check this?

**Comment by duderinio247** [comment]
https://github.com/pyload/pyload/issues/4292#issuecomment-1553167376

**Comment by duderinio247** [comment]
It does not work for me! Decryption of DLC files fails. What am I doing wrong? I just attached the described certificate to the cacert.pem in the directory /usr/lib/python3.10/site-packages/certifi/. That was correct, wasn't it?

I use docker-pyload-ng on an Asustor NAS.

**Comment by fooness** [comment]
_Wanted to share my experience as reference for others …_

The [proposed workaround](https://github.com/pyload/pyload/issues/4273#issuecomment-1539164273) did not work for me in the time frame of the last two months; I’m not running PyLoad via Docker, but via the regular Raspberry Pi / `pip` installation and update method. Downloading/Saving the certificate file in the corresponding location does not solve the problem, unfortunately.
