### ISSUE TITLE
pyload.webui  'JSONProvider' object has no attribute 'JSONEncoder'

### ISSUE THREAD

**Issue by qwrty-ftw** [pyload/pyload#4289]
Hello,

since couple days, i just notice an issue with the webui.
I tried reset default admin account, but still the same issue.

When I try to add a new package I get an error "Failed"
Same issue when I tried to delevep some package I add before.
Same issue when I tried to add a new users.

I activated debug mode:

> avril 28 17:38:09 linology python3[2201953]: [2023-04-28 17:38:09]  DEBUG         pyload.webui  'JSONProvider' object has no attribute 'JSONEncoder'
> avril 28 17:38:09 linology python3[2201953]: Traceback (most recent call last):
> avril 28 17:38:09 linology python3[2201953]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
> avril 28 17:38:09 linology python3[2201953]:     rv = self.dispatch_request()
> avril 28 17:38:09 linology python3[2201953]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
> avril 28 17:38:09 linology python3[2201953]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
> avril 28 17:38:09 linology python3[2201953]:   File "/usr/local/lib/python3.9/dist-packages/pyload/webui/app/helpers.py", line 199, in wrapper
> avril 28 17:38:09 linology python3[2201953]:     response = func(*args, **kwargs)
> avril 28 17:38:09 linology python3[2201953]:   File "/usr/local/lib/python3.9/dist-packages/pyload/webui/app/blueprints/json_blueprint.py", line 22, in status
> avril 28 17:38:09 linology python3[2201953]:     return jsonify(data)
> avril 28 17:38:09 linology python3[2201953]:   File "/usr/local/lib/python3.9/dist-packages/flask/json/__init__.py", line 170, in jsonify
> avril 28 17:38:09 linology python3[2201953]:     return current_app.json.response(*args, **kwargs)
> avril 28 17:38:09 linology python3[2201953]:   File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 104, in response
> avril 28 17:38:09 linology python3[2201953]:     return self._app.response_class(self.dumps(obj), mimetype="application/json")
> avril 28 17:38:09 linology python3[2201953]:   File "/usr/local/lib/python3.9/dist-packages/pyload/webui/app/helpers.py", line 28, in dumps
> avril 28 17:38:09 linology python3[2201953]:     return json.dumps(obj, **kwargs, cls=self.JSONEncoder)
> avril 28 17:38:09 linology python3[2201953]: AttributeError: 'JSONProvider' object has no attribute 'JSONEncoder'

Is this a new bug with recent commit related to flask ?

edit:

I upgrade pyload-ng every 2 days like this:

> echo 'Upgrading pyload-ng...'
> echo 'Stopping pyload-ng service'
> /usr/sbin/service pyload-ng stop
> echo 'Uninstall with pip to ensure latest is installed'
> /usr/local/bin/pip uninstall --yes --root-user-action=ignore pyload-ng
> echo 'Downloading latest pyload-ng dev with pip...'
> /usr/local/bin/pip install --root-user-action=ignore https://github.com/pyload/pyload/archive/refs/heads/develop.zip
> echo 'pyload-ng restarting...'
> /usr/sbin/service pyload-ng start

Thanks :)

**Comment by GammaC0de** [comment]
Thanks for reporting, you are right 👍🏻.
Fix for it very soon (today).

**Comment by DannenmannA** [comment]
Hi, same issue. Thank you for reporting and fixing 😃

**Comment by GammaC0de** [comment]
Please confirm working.

**Comment by qwrty-ftw** [comment]
Yes, it's fixed :)

Thank you
