### ISSUE TITLE
DdownloadCom - Bad server response: 403 Forbidden

### ISSUE THREAD

**Issue by uysct** [pyload/pyload#4292]
### Description

Recently I can no longer download from ddownload.com. All download parts abort with this error message. However, the files are available and can be downloaded via Browser. The account is in order and has sufficient download volume.

### Debug log

```

DEBUG | ACCOUNT DdownloadCom: Valid until: 1685052000.0
DEBUG | ACCOUNT DdownloadCom: Size: 184755 | Unit: MB
DEBUG | ACCOUNT DdownloadCom: LEECH TRAFFIC PATTERN not found
INFO | HOSTER DdownloadCom[525]: Processing url: https://ddownload.com/xxxxx/xxxxx.Remux.part27.rar
INFO | HOSTER DdownloadCom[525]: Looking for direct download link...
WARNING | Download failed: xxxxx.Remux.part27.rar | Bad server response: 403 Forbidden
? | ? | Traceback (most recent call last):
505 | ? | ? | File "/opt/pyload/module/PluginThread.py", line 189, in run
506 | ? | ? | pyfile.plugin.preprocessing(self)
507 | ? | ? | File "/opt/pyload/module/plugins/internal/Base.py", line 290, in preprocessing
508 | ? | ? | return self._process(*args, **kwargs)
509 | ? | ? | File "/opt/pyload/module/plugins/internal/Hoster.py", line 118, in _process
510 | ? | ? | self.process(self.pyfile)
511 | ? | ? | File "/opt/pyload/module/plugins/internal/SimpleHoster.py", line 257, in process
512 | ? | ? | self.handle_direct(pyfile)
513 | ? | ? | File "/opt/pyload/module/plugins/internal/SimpleHoster.py", line 439, in handle_direct
514 | ? | ? | link = self.isresource(pyfile.url)
515 | ? | ? | File "/opt/pyload/module/plugins/internal/Hoster.py", line 174, in isresource
516 | ? | ? | header = self.load(url, just_header=True)
517 | ? | ? | File "/opt/pyload/module/plugins/internal/Base.py", line 484, in load
518 | ? | ? | return Plugin.load(self, *args, **kwargs)
519 | ? | ? | File "/opt/pyload/module/plugins/internal/Plugin.py", line 248, in load
520 | ? | ? | decode is True)
521 | ? | ? | File "/opt/pyload/module/network/Browser.py", line 98, in load
522 | ? | ? | return self.http.load(*args, **kwargs)
523 | ? | ? | File "/opt/pyload/module/network/HTTPRequest.py", line 270, in load
524 | ? | ? | self.code = self.verifyHeader()
525 | ? | ? | File "/opt/pyload/module/network/HTTPRequest.py", line 286, in verifyHeader
526 | ? | ? | raise BadHeader(code, self.header, self.getResponse())
527 | ? | ? | BadHeader: Bad server response: 403 Forbidden
```

### Additional references

Download via LAN, no VPN.

### Screenshots

![IMG_0751](https://github.com/pyload/pyload/assets/30735558/a68772d5-1bd5-4136-81f6-eba660d9d22f)

**Comment by advorsky73** [comment]
same here :(

**Comment by advorsky73** [comment]
@GammaC0de  you can use my 2 ddownload accounts for testing, i havent changed the pw yet ;)

**Comment by uysct** [comment]
Thank you for the confirmation!

**Comment by advorsky73** [comment]
its kind of random.... restarting pyload a few times or switching from stable to develop sometimes makes it work again for a short while... strange...

**Comment by advorsky73** [comment]
Its getting even more strange.... pyLoad starts those 403 marked downloads again on its own after a while and then the mostly work... lol wtf?

**Comment by uysct** [comment]
The downloads are not restarted for me, the complete download breaks off after the 403 error...

**Comment by advorsky73** [comment]
Its gotten worse.... Now not even the account can be loaded correctly anymore....


22390 | 2023-05-10 21:03:39 | INFO | pyload | ACCOUNT DdownloadCom: Login user `ale****`...
22391 | 2023-05-10 21:03:39 | DEBUG | pyload | ACCOUNT DdownloadCom: LOAD URL http://www.ddownload.com/login.html \| get={} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
22392 | 2023-05-10 21:03:40 | DEBUG | pyload | ACCOUNT DdownloadCom: LOAD URL https://ddownload.com/ \| get={} \| post={'op': 'login', 'token': '290ffdbaaa51ec690a863f844707e93e', 'rand': '', 'redirect': 'http://www.ddownload.com/login.html', 'login': 'ale****', 'password': '**********'} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
22393 | 2023-05-10 21:03:41 | ERROR | pyload | ACCOUNT DdownloadCom: Could not login user `ale****` \| Bad server response: 403 Forbidden
22394 | 2023-05-10 21:03:41 | INFO | pyload | ACCOUNT DdownloadCom: Adding user `ale*******`...
22395 | 2023-05-10 21:03:41 | DEBUG | pyload | ACCOUNT DdownloadCom: Reached login timeout for user `ale****`
22396 | 2023-05-10 21:03:41 | INFO | pyload | ACCOUNT DdownloadCom: Login user `ale****`...
22397 | 2023-05-10 21:03:41 | DEBUG | pyload | ACCOUNT DdownloadCom: LOAD URL http://www.ddownload.com/login.html \| get={} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
22398 | 2023-05-10 21:03:42 | DEBUG | pyload | ACCOUNT DdownloadCom: LOAD URL https://ddownload.com/ \| get={} \| post={'op': 'login', 'token': '290ffdbaaa51ec690a863f844707e93e', 'rand': '', 'redirect': 'http://www.ddownload.com/login.html', 'login': 'ale****', 'password': '**********'} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
22399 | 2023-05-10 21:03:42 | ERROR | pyload | ACCOUNT DdownloadCom: Could not login user `ale****` \| Bad server response: 403 Forbidden

**Comment by GammaC0de** [comment]
checking..

**Comment by uysct** [comment]
Exactly the same here. Let's wait and see what happens, there's nothing else left at the moment anyway...

![ IMG_0753](https://github.com/pyload/pyload/assets/30735558/deaf57bb-021d-42e4-bb1e-205dc37897d0)

**Comment by GammaC0de** [comment]
It's damn CloudFlare DDos protection..

**Comment by ddownloadcom** [comment]
Someone from the pyLoad Devs should contact us.

We moved from Cloudflare to ddos-guard.net which is more aggressive with scrapping.
We can no longer work with Cloudflare anymore.

We find a way to implement it for pyLoad.

One of the devs can contact us over information (at) unlimited-network.hk

**Comment by jasondaigo** [comment]
sidenote: dont change ip too often for troubleshooting. you will get banned and have to contact support :-)

**Comment by advorsky73** [comment]
i have a fixed ip... not an issue, but thanks for the hint...

**Comment by advorsky73** [comment]
not yet. DDownload asked to be contacted by a developer 🤷

**Comment by advorsky73** [comment]
if i understood the ddownload support correctly its about the user agent (string) they are supporting in their ddos system...

**Comment by ddownloadcom** [comment]
We still waiting for contact.

Or where can we contact Devs?

**Comment by uysct** [comment]
@GammaC0de

**Comment by advorsky73** [comment]
You can contact one of the main developers directly under ***@***.***
He responded in the thread on GitHub once already complaining about the cloud flare ddos ;)

Br
Alexander Dvorsky

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GammaC0de** [comment]
@ddownloadcom Mail sent.

**Comment by ddownloadcom** [comment]
Solution found, soon pyLoad working again.

**Comment by GammaC0de** [comment]
> Solution found, soon pyLoad working again.

So the fix will come from side?

**Comment by d30r** [comment]
Seems to work now. :)
Can anyone confirm aswell?

**Comment by fragkp** [comment]
> Seems to work now. :) Can anyone confirm aswell?

Not for me (using pyload via Docker from linuxserver/pyload:ng)

**Comment by uysct** [comment]
No change so far...

`ERROR | ACCOUNT DdownloadCom: Could not login user `Bob*******` | Bad server response: 403 Forbidden`

**Comment by geronimoronin** [comment]
> Solution found, soon pyLoad working again.

you have solved nothing 👎

**Comment by jasondaigo** [comment]
Relax. they are working on it.

**Comment by uysct** [comment]
It doesn't work here either... 🙁

**Comment by ddownloadcom** [comment]
We answered to Email, but did not got any answer yet from pyLoad Dev.

**Comment by uysct** [comment]
@GammaC0de

**Comment by GammaC0de** [comment]
OK then, I will do it soon, probably today.

**Comment by advorsky73** [comment]
There was no change in code yet, so you probably just got lucky as the ddos prevent system of ddownload doesnt see you as thread any more ;)

**Comment by uysct** [comment]
Finally. Seems correct now, try a download...

**Comment by uysct** [comment]
Account login works again, downloads not yet...


![IMG_0766](https://github.com/pyload/pyload/assets/30735558/1501487b-76c6-486a-a562-c3b3973056c6)

`WARNING | Download failed: xxxxxx.part37.rar | Bad server response: 403`

**Comment by advorsky73** [comment]
login works now, but similar but not the same as usycts picture: Status: VALID, Premium:  NO (even there are 2 premium accounts in there...) 
Download does not work.

**Comment by advorsky73** [comment]
and login gives 403 again 🤣

**Comment by ddownloadcom** [comment]
If there was a update, let us know aswell.

**Comment by GammaC0de** [comment]
> If there was a update, let us know aswell.

Sure.

**Comment by GammaC0de** [comment]
Current stat: basically it works more or less, there could be some issues with download (not sure).

This should have been a quick fix but the design of pyload makes it hard to do what should have been simple thing.
Add this to the lack of time..

So today I will release an intermediate version so at least you all can start working.

**Comment by advorsky73** [comment]
Applied https://github.com/linuxserver/docker-pyload-ng/pkgs/container/pyload-ng/versions?filters%5Bversion_type%5D=tagged with tag develop.
Works like a charm with 2 ddownload accounts  so far (testing for 10 minutes now 🥇) 
👍

**Comment by fragkp** [comment]
> Applied https://github.com/linuxserver/docker-pyload-ng/pkgs/container/pyload-ng/versions?filters%5Bversion_type%5D=tagged with tag develop. Works like a charm with 2 ddownload accounts so far (testing for 10 minutes now 🥇) 👍

I get "SSL certificate problem: unable to get local issuer certificate" on your image "linuxserver/pyload-ng:develop". Any ideas?

**Comment by GammaC0de** [comment]
@fragkp  this is duplicate 
of #4273

**Comment by fragkp** [comment]
Works for me now! Thanks

**Comment by duderinio247** [comment]
It does not work for me! Decryption of DLC files fails. What am I doing wrong? I just attached the described certificate to the cacert.pem in the directory /usr/lib/python3.10/site-packages/certifi/. That was correct, wasn't it?

I use docker-pyload-ng on an Asustor NAS.

**Comment by duderinio247** [comment]
It does not work for me! Decryption of DLC files fails. What am I doing wrong? I just attached the described certificate to the cacert.pem in the directory /usr/lib/python3.10/site-packages/certifi/. That was correct, wasn't it?

I use docker-pyload-ng on an Asustor NAS.

**Comment by GammaC0de** [comment]
Does anyone having this issue https://github.com/pyload/pyload/discussions/4297?

**Comment by uysct** [comment]
**It works again!**

Many thanks to @GammaC0de and @ddownloadcom !

**Comment by LordSandwurm** [comment]
> Does anyone having this issue #4297?

I have it bevore i copied the fix https://github.com/pyload/pyload/commit/9e8ada9dadd661a4634fd14630c64315c3c26208 into my Files. I am installed pyload over pip, the fix wasn´t available there so i copied it from hand. Without the fix the parsing of the information from the acount didnt work.

**Comment by GammaC0de** [comment]
@LordSandwurm @sspuck You are probably using the main branch, please retry now.

**Comment by sspuck** [comment]
> @LordSandwurm @sspuck You are probably using the main branch, please retry now.

After running "pip install --pre --upgrade pyload-ng" again, it now works.
Thank You.

**Comment by Pootch** [comment]
I use pyload docker and it is not possible to ad an account (ddownload, rapigator, etc..) It always ran into a timeout.

```
626	2023-11-10 10:59:16	INFO	pyload	ACCOUNT DdownloadCom: Updating account info for user `poo****`...
627	2023-11-10 10:59:16	INFO	pyload	ACCOUNT DdownloadCom: Relogin user `poo****`...
628	2023-11-10 10:59:16	DEBUG	pyload	ACCOUNT DdownloadCom: LOAD URL http://ddownload.com/login.html | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
629	2023-11-10 10:59:46	ERROR	pyload	ACCOUNT DdownloadCom: Could not login user `poo****` | (28, 'Failed to connect to ddownload.com port 80 after 30002 ms: Timeout was reached')
630	?	?	?	Traceback (most recent call last):
631	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/account.py", line 138, in login
632	?	?	?	    self.signin(self.user, self.info["login"]["password"], self.info["data"])
633	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/xfs_account.py", line 188, in signin
634	?	?	?	    self.data = self.load(self.LOGIN_URL, cookies=self.COOKIES)
635	?	?	?	                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
636	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/plugin.py", line 217, in load
637	?	?	?	    html = req.load(
638	?	?	?	           ^^^^^^^^^
639	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/browser.py", line 127, in load
640	?	?	?	    return self.http.load(*args, **kwargs)
641	?	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
642	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/http/http_request.py", line 311, in load
643	?	?	?	    self.c.perform()
644	?	?	?	pycurl.error: (28, 'Failed to connect to ddownload.com port 80 after 30002 ms: Timeout was reached')
```

**Comment by GammaC0de** [comment]
It seems that you are having connection issues,
Maybe your IP is banned on maybe you are using VPN?

**Comment by Pootch** [comment]
Hi. Thanks for your answer. 
No my IP is not banned. It works with pyload or jdownloader for Windows to connect to those accounts.
I did not use a vpn.
I will check my connections, maybe there is an firewall issue with the docker container.

**Comment by itsNik** [comment]
> I use pyload docker and it is not possible to ad an account (ddownload, rapigator, etc..) It always ran into a timeout.
> 
> ```
> 626	2023-11-10 10:59:16	INFO	pyload	ACCOUNT DdownloadCom: Updating account info for user `poo****`...
> 627	2023-11-10 10:59:16	INFO	pyload	ACCOUNT DdownloadCom: Relogin user `poo****`...
> 628	2023-11-10 10:59:16	DEBUG	pyload	ACCOUNT DdownloadCom: LOAD URL http://ddownload.com/login.html | get={} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
> 629	2023-11-10 10:59:46	ERROR	pyload	ACCOUNT DdownloadCom: Could not login user `poo****` | (28, 'Failed to connect to ddownload.com port 80 after 30002 ms: Timeout was reached')
> 630	?	?	?	Traceback (most recent call last):
> 631	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/account.py", line 138, in login
> 632	?	?	?	    self.signin(self.user, self.info["login"]["password"], self.info["data"])
> 633	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/xfs_account.py", line 188, in signin
> 634	?	?	?	    self.data = self.load(self.LOGIN_URL, cookies=self.COOKIES)
> 635	?	?	?	                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 636	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/plugin.py", line 217, in load
> 637	?	?	?	    html = req.load(
> 638	?	?	?	           ^^^^^^^^^
> 639	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/browser.py", line 127, in load
> 640	?	?	?	    return self.http.load(*args, **kwargs)
> 641	?	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 642	?	?	?	  File "/lsiopy/lib/python3.11/site-packages/pyload/core/network/http/http_request.py", line 311, in load
> 643	?	?	?	    self.c.perform()
> 644	?	?	?	pycurl.error: (28, 'Failed to connect to ddownload.com port 80 after 30002 ms: Timeout was reached')
> ```

I have the exact same problem. Seems like using the plugin got my ip banned. Even access to ddownload via browser is now blocked from my ip which worked before. 
@ddownloadcom maybe you can clear things up for us, thanks!

**Comment by the-unknown** [comment]
> Hi. Thanks for your answer. No my IP is not banned. It works with pyload or jdownloader for Windows to connect to those accounts. I did not use a vpn. I will check my connections, maybe there is an firewall issue with the docker container.

any news on this? I am having the same issue with pyload-ng in docker

**Comment by Pootch** [comment]
I added the docker subnet for payload to my firewall rule set and it worked.
