### ISSUE TITLE
Script to extract json status

### ISSUE THREAD

**Issue by SweetthD3ViL** [pyload/pyload#4311]
I used the following script in conjunction with autosuspend - autosuspend will run checks on the server to check on given activity and will either leave the server running if an activity is running; i.e. pyLoad is downloading or a video is being watch on Plex. 

So the script will extract the status of .active from /api/statusserver.

It works well up until 2/3 weeks and now the second curl command is complaining about not being authorised. 

`#!/bin/bash

set -e
set -x

SessionID=$(curl -s "http://192.168.1.90:8000/api/login" -g -H "Host: 192.168.1.90:8000" -H "Content-Type: application/x-www-form-urlencoded" --data "username=user&password=password" | jq -r)

SessionStatus=$(curl -s  "http://192.168.1.90:8000/api/statusServer" -g -H "Host: 192.168.1.90" -H "Content-Type: application/x-www-form-urlencoded" --data "session=$SessionID" | jq -r '.active')

if [ $SessionStatus -eq 1 ]
then
  exit 0
else
  exit 1
fi`

`$ sh autosuspend_script/pyload_autosuspend.s
h
++ curl -s http://192.168.1.90:8000/api/login -g -H 'Host: 192.
168.1.90:8000' -H 'Content-Type: application/x-www-form-urlenco
ded' --data 'username=*****&password=****'
+ SessionID='{"_permanent": true, "authenticated": true, "id":
1, "name": "pyload", "role": 0, "perms": 0, "template": "defaul
t", "_flashes": [["message", "Logged in successfully"]]}'
++ curl -s http://192.168.1.90:8000/api/statusServer -g -H 'Hos
t: 192.168.1.90:8000' -H 'Content-Type: application/x-www-form-
urlencoded' --data 'session={"_permanent": true, "authenticated
": true, "id": 1, "name": "pyload", "role": 0, "perms": 0, "tem
plate": "default", "_flashes": [["message", "Logged in successf
ully"]]}'
+ SessionStatus='{"error": "Unauthorized"}'
+ '[' '{"error":' '"Unauthorized"}' -eq 1 ']'
autosuspend_script/pyload_autosuspend.sh: line 10: [: too many
arguments
+ exit 1 `

Has anything change on the login side that would explained why the script stop working? And what would be the best option to get to the desired result?

**Comment by GammaC0de** [comment]
```
curl -c cookie.txt -d "username=xxx&password=yyy" http://localhost:8000/api/login
curl -b cookie.txt "http://localhost:8000/api/statusServer"
```

**Comment by SweetthD3ViL** [comment]
Sorry for the late reply, that works many thanks!

**Comment by GammaC0de** [comment]
👍
