### ISSUE TITLE
Cant download torrent (or magnet)

### ISSUE THREAD

**Issue by 9acca9** [pyload/pyload#4316]
First time using Pyload.

I go to Settings/Plugin/TORRENT

There i just see this:

`Associate torrents / magnets with plugin:`

I have to associate with a plugin to download a torrent or magnet??
If yes, i try all there, and... i need to have a user from those service? i dont pay any of those service. I have to pay a service to download a torrent or magnet link? (i dont understand).
Thanks.

**Comment by GammaC0de** [comment]
pyload does not support downloading torrents out of the box (it was not designed to do so).
It can use those premium services to do the download.
