### ISSUE TITLE
Cannot retrieve session id via HTTP API

### ISSUE THREAD

**Issue by francesco-plt** [pyload/pyload#4317]
From the API documentation we read:
> First you need to authenticate, if you using this within the webinterface and the user is logged the API is also accessible, since they share the same cookie/session.

> However, if you are building a external client and want to authenticate manually you have to send your credentials username and password as POST parameter to http://pyload-core/api/login.

> The result will be your session id. If you are using cookies, it will be set and you can use the API now. In case you dont’t have cookies enabled you can pass the session id as session POST parameter so pyLoad can authenticate you.

If I try to login into pyload via HTTP API using `curl`, for example:

```bash
$ curl "http://127.0.0.1:8000/api/login" -g -H "Host: 127.0.0.1:8000" -H "Content-Type: application/x-www-form-urlencoded" --data "username=pyload&password=pyload"
```
I get the following response:
```json
{"_permanent": true, "authenticated": true, "id": 1, "name": "pyload", "role": 0, "perms": 0, "template": "default", "_flashes": [["message", "Logged in successfully"]]}
```
But I am not able to perform any other action since I cannot find a way to actually receive the session id in the response. 

I tried to avoid the issue by using a `Session` object from the python library requests, which successfully retrieves a session id from the cookies in the server response, but if I include such identifier as a POST parameter in subsequent requests I get error 401 from pyload.

Moreover, if I keep using the session object to interact with APIs I get another error, this time a Internal Server Error (error code 500), with a response containing HTML code even if I am interacting with API endpoints (e.g. `http://127.0.0.1:8000/api/addPackage`).

As a result I am unable to interact with pyload using its APIs.

**Comment by GammaC0de** [comment]
```
curl -c cookie.txt -d "username=xxx&password=yyy" http://localhost:8000/api/login
curl -b cookie.txt "http://localhost:8000/api/statusServer"
```
