### ISSUE TITLE
[UptoboxCom] Premium account info and validity date 

### ISSUE THREAD

**Issue by Elrickp31** [pyload/pyload#4318]
Hi, 
Premium account info and validity date are not detected for Uptobox plug-in

That can be see in "config" tab, the login to uptobox work but the account information are not grabbed from uptobox.com  

Herebelow, the log:

15 | 19.06.2023 19:53:11 | INFO | ACCOUNT UptoboxCom: Adding user `Elr*******`...
-- | -- | -- | --
16 | 19.06.2023 19:53:11 | DEBUG | ACCOUNT UptoboxCom: Reached login timeout for user `Elr*******`
17 | 19.06.2023 19:53:11 | INFO | ACCOUNT UptoboxCom: Login user `Elr*******`...
18 | 19.06.2023 19:53:11 | DEBUG | ACCOUNT UptoboxCom: LOAD URL https://uptobox.eu/login \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
19 | 19.06.2023 19:53:11 | INFO | Starting threaded webserver: :::8000
20 | 19.06.2023 19:53:13 | DEBUG | ACCOUNT UptoboxCom: LOAD URL https://uptobox.eu/login \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={'login': 'Elr*******', 'password': '**********'} \| ref=https://uptobox.eu/login \| just_header=False
21 | 19.06.2023 19:53:13 | INFO | ACCOUNT UptoboxCom: Grabbing account info for user `Elr*******`...
22 | 19.06.2023 19:53:13 | DEBUG | ACCOUNT UptoboxCom: LOAD URL http://www.uptobox.eu/ \| redirect=True \| cookies=True \| get={'op': 'my_account'} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
23 | 19.06.2023 19:53:14 | WARNING | ACCOUNT UptoboxCom: Error loading info for user `Elr*******` \| (6, 'Could not resolve: uptobox.com (Domain name not found)')
24 | 19.06.2023 19:53:14 | DEBUG | ACCOUNT UptoboxCom: Account info for user `Elr*******`: {'login': {'timestamp': 1687197191.965, 'password': '**********', 'stats': [1, 0], 'valid': True}, 'data': {'validuntil': None, 'plugin': , 'trafficleft': None, 'maxtraffic': None, 'premium': None, 'login': 'Elr*******', 'type': 'UptoboxCom', 'options': {'limitDL': ['0']}}}

So, I have developed a solution that I will  submit.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Please disable goeip restrictions
