### ISSUE TITLE
Installation on Debian 12 "Bookworm"

### ISSUE THREAD

**Issue by psycho-dad** [pyload/pyload#4319]
### Question

I get this message:

pip3 install pyload-ng
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

Any Ideas what happend?

**Comment by GammaC0de** [comment]
https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-everytime-i-use-pip3

**Comment by fooness** [comment]
As I ran into the same issue, I’ll document _my subjective_ installation procedure here; maybe someone wants to update the [installation steps in the wiki](https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi))? I’m not sure this is the “best” approach, but it’s close to what the wiki already suggests.

These snippets are **in addition** to the installation steps laid out in the wiki; you still need to install dependencies first, maybe create a system user account for pyload, and create/start/enable your systemd service files accordingly …

- `apt install python3-venv`
- create python virtual environment, e.g. `python3 -m venv ~/.local`
- `source ~/.local/bin/activate`
- `pip3 install --pre pyload-ng[all]` (as in the wiki, but without `sudo`)
- change the command in systemd service file, like:
```
ExecStart=/bin/sh -c "/home/<username>/.local/bin/python /home/<username>/.local/bin/pyload"
```
