### ISSUE TITLE
UptoboxCom - Login and Downloads

### ISSUE THREAD

**Issue by githuber1998** [pyload/pyload#4320]
### Description

I can't login on the UptoboxCom plugin and can't download...

### Debug log

pycurl error 6: Could not resolve host: uptobox.eu 

```

```

**Comment by GammaC0de** [comment]
It was working yesterday now its not.
Maybe a DNS issue, maybe this address was banned?

uptobox.com and uptobox.fr still works, which site is better?

**Comment by githuber1998** [comment]
uptobox.com work on PyLoad Yesterday, so I think it's better

**Comment by GammaC0de** [comment]
Now uptobox.eu works again so closing this.
If there is still an issue please inform here.

**Comment by githuber1998** [comment]
Download does'nt start ... There are still in queued 😔

**Comment by githuber1998** [comment]
> Download does'nt start ... There are still in queued 😔

Same problem with 1fichier.com ...
