### ISSUE TITLE
Challenge reCAPTCHA v2 interactive on MAC OS with Chrome/Edge 

### ISSUE THREAD

**Issue by GreenSnakeLinux** [pyload/pyload#4321]
### Description
I've got the following issue with Challenge reCAPTCHA v2 interactive
on Chrome (also on Edge) on MAC OS
Tampermonkey is installed and working on other captcha method

Here is the message when I click on Captcha waiting button:
The captcha may take a few seconds to load.
Note: to solve this interactive captcha
Please install the Tampermonkey add-on in your browser and add the pyload userscript.

but nothing happen

### Debug log
2428	2023-06-27 23:07:24	DEBUG	pyload	DOWNLOADER FilericeCom[18]: Plugin version: 0.01
2429	2023-06-27 23:07:24	DEBUG	pyload	DOWNLOADER FilericeCom[18]: Plugin status: testing
2430	2023-06-27 23:07:24	WARNING	pyload	DOWNLOADER FilericeCom[18]: Plugin may be unstable
2431	2023-06-27 23:07:24	INFO	pyload	DOWNLOADER FilericeCom[18]: Processing url: https://filerice.com/su7g47a2b8q7
2432	2023-06-27 23:07:24	DEBUG	pyload	DOWNLOADER FilericeCom[18]: LOAD URL https://filerice.com/su7g47a2b8q7 | get={} | post={} | ref=False | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
2433	2023-06-27 23:07:25	INFO	pyload	DOWNLOADER FilericeCom[18]: Checking for link errors...
2434	2023-06-27 23:07:25	INFO	pyload	DOWNLOADER FilericeCom[18]: No errors found
2435	2023-06-27 23:07:25	INFO	pyload	DOWNLOADER FilericeCom[18]: Grabbing link info...
2436	2023-06-27 23:07:25	DEBUG	pyload	DOWNLOADER FilericeCom[18]: Link info: {'name': 'Law.and.Order.Organized.Crime.S03E01.FRENCH.HDTV.x264-Wawacity.boo.mp4', 'hash': {}, 'pattern': {'ID': 'su7g47a2b8q7', 'N': 'Law.and.Order.Organized.Crime.S03E01.FRENCH.HDTV.x264-Wawacity.boo.mp4', 'S': '333.7', 'U': 'MB'}, 'size': 349909811, 'status': 2, 'url': 'https://filerice.com/su7g47a2b8q7'}
2437	2023-06-27 23:07:25	DEBUG	pyload	DOWNLOADER FilericeCom[18]: Previous link info: {}
2438	2023-06-27 23:07:25	INFO	pyload	DOWNLOADER FilericeCom[18]: Link name: Law.and.Order.Organized.Crime.S03E01.FRENCH.HDTV.x264-Wawacity.boo.mp4
2439	2023-06-27 23:07:25	INFO	pyload	DOWNLOADER FilericeCom[18]: Link size: 333.70 MiB (349909811 bytes)
2440	2023-06-27 23:07:25	INFO	pyload	DOWNLOADER FilericeCom[18]: Link status: online
2441	2023-06-27 23:07:25	INFO	pyload	DOWNLOADER FilericeCom[18]: Processing as free download...
2442	2023-06-27 23:07:25	DEBUG	pyload	DOWNLOADER FilericeCom[18]: Getting download link #1...
2443	2023-06-27 23:07:25	INFO	pyload	DOWNLOADER FilericeCom[18]: Checking for link errors...
2444	2023-06-27 23:07:25	INFO	pyload	DOWNLOADER FilericeCom[18]: No errors found
2445	2023-06-27 23:07:25	DEBUG	pyload	DOWNLOADER FilericeCom[18]: {'op': 'download1', 'usr_login': '', 'id': 'su7g47a2b8q7', 'fname': 'Law.and.Order.Organized.Crime.S03E01.FRENCH.HDTV.x264-Wawacity.boo.mp4', 'referer': '', 'method_premium': 'Download at high speed'}
2446	2023-06-27 23:07:25	WARNING	pyload	ANTICAPTCHA FilericeCom[18]: ReCaptcha | Key pattern not found
2447	2023-06-27 23:07:25	WARNING	pyload	ANTICAPTCHA FilericeCom[18]: HCaptcha | Key pattern not found
2448	2023-06-27 23:07:25	DEBUG	pyload	ANTICAPTCHA FilericeCom[18]: SolveMedia | Key pattern not found
2449	2023-06-27 23:07:25	DEBUG	pyload	DOWNLOADER FilericeCom[18]: LOAD URL https://filerice.com/su7g47a2b8q7 | get={} | post={'op': 'download1', 'usr_login': '', 'id': 'su7g47a2b8q7', 'fname': 'Law.and.Order.Organized.Crime.S03E01.FRENCH.HDTV.x264-Wawacity.boo.mp4', 'referer': 'https://filerice.com/su7g47a2b8q7', 'method_free': 'Free Download'} | ref=https://filerice.com/su7g47a2b8q7 | cookies=True | just_header=False | decode=True | multipart=False | redirect=False | req=None
2450	2023-06-27 23:07:27	DEBUG	pyload	DOWNLOADER FilericeCom[18]: Getting download link #2...
2451	2023-06-27 23:07:27	INFO	pyload	DOWNLOADER FilericeCom[18]: Checking for link errors...
2452	2023-06-27 23:07:27	INFO	pyload	DOWNLOADER FilericeCom[18]: No errors found
2453	2023-06-27 23:07:27	DEBUG	pyload	DOWNLOADER FilericeCom[18]: {'op': 'download2', 'id': 'su7g47a2b8q7', 'rand': 'zexoa4322xajc2ydwtepgltbdpcjenrifim2ukf6va', 'referer': 'https://filerice.com/su7g47a2b8q7', 'method_free': 'Free Download', 'method_premium': '', 'adblock_detected': ''}
2454	2023-06-27 23:07:27	DEBUG	pyload	DOWNLOADER FilericeCom[18]: WAIT set to timestamp 1687900063.605879 | Previous wait_until: 0
2455	2023-06-27 23:07:27	DEBUG	pyload	ANTICAPTCHA FilericeCom[18]: ReCaptcha | Key: 6Ld9jdYmAAAAAISEkxcput1vI6q8QsvSeR_S3KNU
2456	2023-06-27 23:07:27	WARNING	pyload	ANTICAPTCHA FilericeCom[18]: ReCaptcha | Secure Token pattern not found
2457	2023-06-27 23:07:27	DEBUG	pyload	ANTICAPTCHA FilericeCom[18]: ReCaptcha | Detected reCAPTCHA v2
2458	2023-06-27 23:07:27	WARNING	pyload	ANTICAPTCHA FilericeCom[18]: ReCaptcha | Secure Token pattern not found
2459	2023-06-27 23:07:27	DEBUG	pyload	DOWNLOADER FilericeCom[18]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=6Ld9jdYmAAAAAISEkxcput1vI6q8QsvSeR_S3KNU | get={} | post={} | ref=https://filerice.com/su7g47a2b8q7 | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
2460	2023-06-27 23:07:27	WARNING	pyload	ANTICAPTCHA FilericeCom[18]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
2461	2023-06-27 23:07:27	DEBUG	pyload	ANTICAPTCHA FilericeCom[18]: ReCaptcha | Challenge reCAPTCHA v2 interactive

### Additional references
URL:
https://filerice.com/su7g47a2b8q7

**Comment by GammaC0de** [comment]
Try installing one of these:
https://chrome.google.com/webstore/search/x-frame-options

**Comment by GreenSnakeLinux** [comment]
thanks it's working with this extension: Ignore X-Frame headers

**Comment by GammaC0de** [comment]
👍
