### ISSUE TITLE
pyload upload file in chunk format

### ISSUE THREAD

**Issue by Dikko3506** [pyload/pyload#4325]
![image](https://github.com/pyload/pyload/assets/43563193/e62c28a5-7a4c-4063-8220-019aa9c4abd1)

i am using my google drive with rclone 

with pyload but after done its upload files in .chunk format anyone can help me                                                                                                                                                    

//Log 

01.07.2023 21:29:36 | INFO | ADDON TORRENT: Using RealdebridComTorrent to handle torrents / magnets
01.07.2023 21:29:36 | INFO | pyLoad is up and running
01.07.2023 21:29:36 | INFO | ADDON UpdateManager: pyLoad is up to date!
01.07.2023 21:29:36 | INFO | ADDON UpdateManager: All plugins are up to date!
01.07.2023 21:29:42 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
01.07.2023 21:30:11 | INFO | Added package asw containing 1 links
01.07.2023 21:30:12 | INFO | Decrypting starts: magnet:?xt=xxxxxx
01.07.2023 21:30:12 | WARNING | CRYPTER RealdebridComTorrent[15]: Plugin may be unstable
01.07.2023 21:30:12 | INFO | CRYPTER RealdebridComTorrent[15]: Grabbing link info...
01.07.2023 21:30:12 | INFO | CRYPTER RealdebridComTorrent[15]: Link name: urnbtih21d5c9d4982f50d86d399910cdc41ca9e0868879
 01.07.2023 21:30:12 | INFO | CRYPTER RealdebridComTorrent[15]: Link size: N/D
01.07.2023 21:30:12 | INFO | CRYPTER RealdebridComTorrent[15]: Link status: starting
01.07.2023 21:30:12 | INFO | CRYPTER RealdebridComTorrent[15]: Processing url: magnet:?xt=urn:btih:21d5c9d4982f50d86d399910cdc41ca9e0868879&dn=Manowar%20-
01.07.2023 21:31:10 | INFO | CRYPTER RealdebridComTorrent[15]: Create package: asw \| 1 links
 01.07.2023 21:31:10 | INFO | Added package asw containing 1 links
01.07.2023 21:31:10 | INFO | CRYPTER RealdebridComTorrent[15]: Save package `asw` to folder: asw
 01.07.2023 21:31:10 | INFO | Download starts: https://real-debrid.com/d/SC3B4AAU3DLZI
01.07.2023 21:31:10 | WARNING | HOSTER RealdebridCom[16]: RealdebridCom \| Plugin may be unstable
 01.07.2023 21:31:10 | INFO | ACCOUNT RealdebridCom: Grabbing account info for user `M3O*******`...
01.07.2023 21:31:11 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Processing url: https://real-debrid.com/d/SC3B4AAU3DLZI
01.07.2023 21:31:11 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Looking for direct download link...
 01.07.2023 21:31:11 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Direct download link not found
01.07.2023 21:31:11 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Checking for link errors...
01.07.2023 21:31:11 | WARNING | HOSTER RealdebridCom[16]: RealdebridCom \| No data to check
 01.07.2023 21:31:11 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Grabbing link info...
 01.07.2023 21:31:11 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Link name: SC3B4AAU3DLZI
01.07.2023 21:31:11 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Link size: N/D
 01.07.2023 21:31:11 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Link status: starting
01.07.2023 21:31:11 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Processing as premium download...
 01.07.2023 21:31:11 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Downloading file...
 01.07.2023 21:31:32 | ERROR | HOSTER RealdebridCom[16]: RealdebridCom
01.07.2023 21:31:32 | ERROR | <<< UNCAUGHT EXCEPTION >>>
 ? | ? | IOError: [Errno 1] Operation not permitted
 01.07.2023 21:31:32 | WARNING | Download failed: Manowar - Fighting The World (1987) [MIVAGO].rar \| error return without exception set
 01.07.2023 21:31:32 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: Manowar - Fighting The World (1987) [MIVAGO].rar (pid:16)
 01.07.2023 21:31:32 | INFO | ADDON UnSkipOnFail: No duplicates found

**Comment by GammaC0de** [comment]
> IOError: [Errno 1] Operation not permitted

You have some access issues in your download folder, please enable debug logs, restart pyLoad, retry the download and post the logs.

**Comment by Dikko3506** [comment]
02.07.2023 08:29:09 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Processing url: https://real-debrid.com/d/SC3B4AAU3DLZI
-- | -- | --
19 | 02.07.2023 08:29:09 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Looking for direct download link...
20 | 02.07.2023 08:29:09 | DEBUG | HOSTER RealdebridCom[16]: RealdebridCom \| LOAD URL https://real-debrid.com/d/SC3B4AAU3DLZI \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
21 | 02.07.2023 08:29:09 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Direct download link not found
22 | 02.07.2023 08:29:09 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Checking for link errors...
23 | 02.07.2023 08:29:09 | WARNING | HOSTER RealdebridCom[16]: RealdebridCom \| No data to check
24 | 02.07.2023 08:29:09 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Grabbing link info...
25 | 02.07.2023 08:29:09 | DEBUG | HOSTER RealdebridCom[16]: RealdebridCom \| Link info: {'status': 7, 'hash': {}, 'name': u'SC3B4AAU3DLZI', 'url': u'https://real-debrid.com/d/SC3B4AAU3DLZI', 'pattern': {}, 'size': 0}
26 | 02.07.2023 08:29:09 | DEBUG | HOSTER RealdebridCom[16]: RealdebridCom \| Previous link info: {}
27 | 02.07.2023 08:29:09 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Link name: SC3B4AAU3DLZI
28 | 02.07.2023 08:29:09 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Link size: 81.42 MiB (85379316 bytes)
29 | 02.07.2023 08:29:09 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Link status: starting
30 | 02.07.2023 08:29:09 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Processing as premium download...
31 | 02.07.2023 08:29:09 | DEBUG | HOSTER RealdebridCom[16]: RealdebridCom \| LOAD URL https://api.real-debrid.com/rest/1.0/unrestrict/link \| redirect=True \| cookies=True \| get={'auth_token': u'7PEPKXSDIAINM36AUIZUQA3YN7QHUTUYU33ORF7NA2CKJ2TNV4BA'} \| req=None \| decode=True \| multipart=False \| post={'password': '', 'link': u'https://real-debrid.com/d/SC3B4AAU3DLZI'} \| ref=True \| just_header=False
32 | 02.07.2023 08:29:09 | DEBUG | HOSTER RealdebridCom[16]: RealdebridCom \| Returned Data: {u'mimeType': u'application/x-rar-compressed', u'streamable': 0, u'host_icon': u'https://fcdn.real-debrid.com/0820/images/hosters/realdebrid.png', u'filename': u'Manowar - Fighting The World (1987) [MIVAGO].rar', u'crc': 1, u'host': u'real-debrid.com', u'link': u'https://real-debrid.com/d/SC3B4AAU3DLZI', u'filesize': 85379316, u'chunks': 32, u'download': u'https://22.download.real-debrid.com/d/DGYBKMWP3GDRI/Manowar%20-%20Fighting%20The%20World%20%281987%29%20%5BMIVAGO%5D.rar', u'id': u'DGYBKMWP3GDRI'}
33 | 02.07.2023 08:29:09 | INFO | HOSTER RealdebridCom[16]: RealdebridCom \| Downloading file...
34 | 02.07.2023 08:29:09 | DEBUG | HOSTER RealdebridCom[16]: RealdebridCom \| DOWNLOAD URL https://22.download.real-debrid.com/d/DGYBKMWP3GDRI/Manowar%20-%20Fighting%20The%20World%20%281987%29%20%5BMIVAGO%5D.rar \| cookies=True \| resume=None \| get={} \| disposition=True \| chunks=None \| post={} \| ref=True
35 | 02.07.2023 08:29:11 | DEBUG | Chunked with range 28459773-56919546
36 | 02.07.2023 08:29:11 | DEBUG | Chunked with range 56919546-
37 | 02.07.2023 08:29:30 | ERROR | HOSTER RealdebridCom[16]: RealdebridCom
38 | ? | ? | Traceback (most recent call last):
39 | ? | ? | File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
40 | ? | ? | self.__bootstrap_inner()
41 | ? | ? | File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
42 | ? | ? | self.run()
43 | ? | ? | File "/usr/share/pyload/module/PluginThread.py", line 187, in run
44 | ? | ? | pyfile.plugin.preprocessing(self)
45 | ? | ? | File "/root/.pyload/userplugins/internal/Base.py", line 290, in preprocessing
46 | ? | ? | return self._process(*args, **kwargs)
47 | ? | ? | File "/root/.pyload/userplugins/internal/MultiHoster.py", line 71, in _process
48 | ? | ? | SimpleHoster._process(self, thread)
49 | ? | ? | File "/root/.pyload/userplugins/internal/Hoster.py", line 118, in _process
50 | ? | ? | self.process(self.pyfile)
51 | ? | ? | File "/root/.pyload/userplugins/internal/SimpleHoster.py", line 285, in process
52 | ? | ? | self.download(self.link, disposition=self.DISPOSITION)
53 | ? | ? | File "/root/.pyload/userplugins/internal/Hoster.py", line 308, in download
54 | ? | ? | disposition, resume, chunks)
55 | ? | ? | File "/root/.pyload/userplugins/internal/Hoster.py", line 237, in _download
56 | ? | ? | status_notify=self._on_notification, disposition=disposition)
57 | ? | ? | File "/usr/share/pyload/module/network/Browser.py", line 89, in httpDownload
58 | ? | ? | name = self.dl.download(chunks, resume)
59 | ? | ? | File "/usr/share/pyload/module/network/HTTPDownload.py", line 130, in download
60 | ? | ? | self._download(chunks, resume)
61 | ? | ? | File "/usr/share/pyload/module/network/HTTPDownload.py", line 298, in _download
62 | ? | ? | self._copyChunks()
63 | ? | ? | File "/usr/share/pyload/module/network/HTTPDownload.py", line 107, in _copyChunks
  ? | ? | fo.write(data)
? | IOError: [Errno 29] Illegal seek
 ? | ? |  
|02.07.2023 08:29:30 | ERROR | <<< UNCAUGHT EXCEPTION >>>
? | ? | IOError: [Errno 1] Operation not permitted
 02.07.2023 08:29:30 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
 02.07.2023 08:29:30 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
02.07.2023 08:29:30 | WARNING | Download failed: Manowar - Fighting The World (1987) [MIVAGO].rar \| error return without exception set
02.07.2023 08:29:30 | INFO | Debug Report written to debug_RealdebridCom_02-07-2023_08-29-30.zip
02.07.2023 08:29:30 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: Manowar - Fighting The World (1987) [MIVAGO].rar (pid:16)
 02.07.2023 08:29:30 | INFO | ADDON UnSkipOnFail: No duplicates found
 02.07.2023 08:29:30 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
 02.07.2023 08:29:30 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
 02.07.2023 08:29:30 | DEBUG | All downloads processed

**Comment by GammaC0de** [comment]
> IOError: [Errno 29] Illegal seek 	

Are you trying to download to the google drive?!

**Comment by Dikko3506** [comment]
Yes i attach my google drive with rclone and system i use is ubuntu 
all data directly store to google drive 
can you please fix my issue its will be very helpful

**Comment by GammaC0de** [comment]
This configuration is not supported.

What **may** work is to move the downloaded files to Google drive after the download is complete.
