### ISSUE TITLE
What is the package feature?

### ISSUE THREAD

**Issue by npodbielski** [pyload/pyload#4334]
### Question

I tried to use packages few times but it does not work. Files stays in 'queued' state forever. Nothing is being downloaded. There is no logs. It seems like it does nothing at all.

So what is the expected behavior? What should happen and why? What I was expecting is to have ability to set multiple links for multiple files like in Jdownloader:

 | File 1 | Link 1 to hoster 1 | 
 | File 1 | Link 2 to hoster 2 | 
 | File 1 | Link 3 to hoster 3 | 
 | File 1 | Link 4 to hoster 4 | 
 | File 2 | Link 5 to hoster 1 | 
 | File 2 | Link 6 to hoster 2 | 
 | File 2 | Link 7 to hoster 3 | 
 | File 2 | Link 8 to hoster 4 | 

And it automatically downloads i.e. Link 1 and Link 6 for File 1 and File 2 respectively.  It omits Link 5 because there is only 1 connection per hoster allowed. When File 1 downloads fails it tries to download Link 3 because Hoster 2 is blocked by Link 6.

There is nothing really in docs about this.

**Comment by mihawk90** [comment]
The Package tab is just meant for you to organise your packages before you start the download, i.e. remove links that you don't need, change package names and paths, set passwords.

If you're coming from JDownloader it's essentially the equivalent to the LinkGrabber.

At least... that's my understanding.

I don't think there is a way to combine multiple packages into one - if there is it's very well hidden. It doesn't matter for multi-host downloads though. Under Settings > Downloads there is "Skip already existing files", enable that if it's not already and it will skip files that already exist so it doesn't download them from multiple hosters. It should also skip files with a *.chunk0 file (i.e. have already been started), but I haven't tested this.

**Comment by npodbielski** [comment]
Ah thanks. I will try that out ;)

Closing.
