### ISSUE TITLE
allow users to override extractor code

### ISSUE THREAD

**Issue by milahu** [pyload/pyload#4338]
make it easier to patch the more "dynamic" parts of pyload

for example, try to import extractor code from `$HOME/.config/pyload/pyload`
or if there is no such file, then fall back to the default code

### Problem description

patching of extractor code requires a full update of pyload

### keywords

plugins, hoster handlers, domain handlers

**Comment by GammaC0de** [comment]
> for example, try to import extractor code from $HOME/.config/pyload/pyload
or if there is no such file, then fall back to the default code

pyLoad already have this feature (https://github.com/pyload/pyload/commit/0e53f8688c491500431e15d610fa3fca49433477), it will try load plugins from `$HOME/.config/pyload/plugins` first.

**Comment by GammaC0de** [comment]
There was a  bug and now it is fixed
