### ISSUE TITLE
Uptobox Hoster V0.40 : Parse error: Premium download link not found

### ISSUE THREAD

**Issue by yaya059** [pyload/pyload#4341]
### Description
Hi All ,since the update of the hoster uptobox the 30th of July in V0.40 , the premium links are not reachable.
Pyload Version : 0.4.20

### Debug log
logs : 

209 | 31.07.2023 09:48:33 | DEBUG | HOSTER UptoboxCom[9]: Plugin version: 0.40
-- | -- | -- | --
210 | 31.07.2023 09:48:33 | DEBUG | HOSTER UptoboxCom[9]: Plugin status: testing
211 | 31.07.2023 09:48:33 | WARNING | HOSTER UptoboxCom[9]: Plugin may be unstable
212 | 31.07.2023 09:48:33 | INFO | ACCOUNT UptoboxCom: Grabbing account info for user `xxx*******`...
213 | 31.07.2023 09:48:33 | DEBUG | ACCOUNT UptoboxCom: LOAD URL https://uptobox.eu/my_account \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
214 | 31.07.2023 09:48:33 | DEBUG | ACCOUNT UptoboxCom: Account info for user `xxx*******`: {'login': {'timestamp': 1690788527.143359, 'password': '**********', 'stats': [1, 1690788537.724993], 'valid': True}, 'data': {'validuntil': 1714241040.0, 'plugin': , 'trafficleft': -1, 'maxtraffic': None, 'premium': True, 'login': 'xxx*******', 'type': 'UptoboxCom', 'options': {'limitDL': ['0']}}}
215 | 31.07.2023 09:48:33 | DEBUG | ACCOUNT UptoboxCom: Using account xxx*******
216 | 31.07.2023 09:48:33 | INFO | HOSTER UptoboxCom[9]: Processing url: https://uptobox.com/yslduvtxm9l3
217 | 31.07.2023 09:48:33 | DEBUG | HOSTER UptoboxCom[9]: LOAD URL https://uptobox.link/yslduvtxm9l3 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
218 | 31.07.2023 09:48:33 | INFO | HOSTER UptoboxCom[9]: Checking for link errors...
219 | 31.07.2023 09:48:33 | DEBUG | HOSTER UptoboxCom[9]: WAIT set to timestamp 1690789774.741529 \| Previous waitUntil: 0.000000
220 | 31.07.2023 09:48:33 | INFO | HOSTER UptoboxCom[9]: Waiting 1 minutes...
221 | 31.07.2023 09:49:35 | INFO | HOSTER UptoboxCom[9]: No errors found
222 | 31.07.2023 09:49:35 | INFO | HOSTER UptoboxCom[9]: Grabbing link info...
223 | 31.07.2023 09:49:35 | DEBUG | HOSTER UptoboxCom[9]: Link info: {'status': 2, 'hash': {}, 'name': u'Sons.Of.Summer.2023.French.Hdrip.X264.Wawacity.Homes.mp4', 'url': u'https://uptobox.link/yslduvtxm9l3', 'pattern': {'S': u'1014.14', 'U': u'MB', 'ID': u'yslduvtxm9l3', 'N': u'Sons.Of.Summer.2023.French.Hdrip.X264.Wawacity.Homes.mp4'}, 'size': 1063402864}
224 | 31.07.2023 09:49:35 | DEBUG | HOSTER UptoboxCom[9]: Previous link info: {}
225 | 31.07.2023 09:49:35 | INFO | HOSTER UptoboxCom[9]: Link name: Sons.Of.Summer.2023.French.Hdrip.X264.Wawacity.Homes.mp4
226 | 31.07.2023 09:49:35 | INFO | HOSTER UptoboxCom[9]: Link size: 1014.14 MiB (1063402864 bytes)
227 | 31.07.2023 09:49:35 | INFO | HOSTER UptoboxCom[9]: Link status: en ligne
228 | 31.07.2023 09:49:35 | INFO | HOSTER UptoboxCom[9]: Processing as premium download...
229 | 31.07.2023 09:49:35 | WARNING | HOSTER UptoboxCom[9]: Premium download failed \| Parse error: Premium download link not found \| Plugin may be out of date
230 | 31.07.2023 09:49:35 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
231 | 31.07.2023 09:49:35 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
232 | 31.07.2023 09:49:35 | WARNING | Download failed: Sons.Of.Summer.2023.French.Hdrip.X264.Wawacity.Homes.mp4 \| Parse error: Premium download link not found \| Plugin may be out of date
233 | 31.07.2023 09:49:35 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
234 | 31.07.2023 09:49:35 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: Sons.Of.Summer.2023.French.Hdrip.X264.Wawacity.Homes.mp4 (pid:9)
235 | 31.07.2023 09:49:35 | INFO | ADDON UnSkipOnFail: No duplicates found
236 | 31.07.2023 09:49:35 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
237 | 31.07.2023 09:49:35 | DEBUG | All downloads processed

here the ouput of the hoster in v 0.40 :

import re

from ..internal.SimpleHoster import SimpleHoster

class UptoboxCom(SimpleHoster):
    __name__ = "UptoboxCom"
    __type__ = "hoster"
    __version__ = "0.40"
    __status__ = "testing"

    __pattern__ = r'https?://(?:www\.)?(uptobox|uptostream)\.(?:com|eu|link)/(?P<ID>\w{12})'
    __config__ = [("activated", "bool", "Activated", True),
                  ("use_premium", "bool", "Use premium account if available", True),
                  ("fallback", "bool",
                   "Fallback to free download if premium fails", True),
                  ("chk_filesize", "bool", "Check file size", True),
                  ("max_wait", "int", "Reconnect if waiting time is greater than minutes", 10)]

    __description__ = """Uptobox.com hoster plugin"""
    __license__ = "GPLv3"
    __authors__ = [("Walter Purcaro", "vuolter@gmail.com"),
                   ("GammaC0de", "nitzo2001[AT]yahoo[DOT]com")]

    PLUGIN_DOMAIN = "uptobox.link"

    INFO_PATTERN = r"""(?:"para_title">|<h1(?: .*)?>)(?P<N>.+) \((?P<S>[\d.,]+) (?P<U>[\w^_]+)\)"""
    OFFLINE_PATTERN = r"""(File not found|Access Denied|404 Not Found)"""
    TEMP_OFFLINE_PATTERN = r""">Service Unavailable"""
    WAIT_PATTERN = r"""data-remaining-time=["'](\d+)["']"""

    LINK_PATTERN = r"""['"](https?://(?:obwp\d+\.uptobox\.(?:com|eu|link)|\w+\.uptobox\.(?:com|eu|link)/dl?)/.+?)['"]"""
    DIRECT_LINK = False

    DL_LIMIT_PATTERN = r"""or you can wait (.+) to launch a new download"""
    URL_REPLACEMENTS = [(__pattern__ + ".*", r"https://uptobox.link/\g<ID>")]

    def setup(self):
        self.multiDL = self.premium
        self.chunk_limit = 1
        self.resume_download = True

    def handle_free(self, pyfile):
        m = re.search(r"""<input name=["']waitingToken["'] value=["'](.+?)["']""", self.data)
        if m is not None:
            self.data = self.load(pyfile.url,
                                  post={'waitingToken': m.group(1),
                                        'submit': "Free Download"})

        m = re.search(self.LINK_PATTERN, self.data)
        if m is not None:
            self.link = m.group(1)

```



Thanks in advance , the premium link are ok with DL in the browser so it's not a DNS issue

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by yaya059** [comment]
account credential has been transferred thanks in advance

**Comment by GammaC0de** [comment]
Fixed.

**Comment by yaya059** [comment]
Thanks a lot
