### ISSUE TITLE
pyload-ng 0.5.0 api access from 0.4.9

### ISSUE THREAD

**Issue by HPP8140** [pyload/pyload#4353]
### Question
So I am looking into upgrading from Debian Jessie Pyload 0.4.9 Python 2.7 to Debian Bookworm, which has removed support for Python 2.7. 
I installed pyload-ng for Python 3 and am wondering is there or will there be a replacement for the .4.9 CLI API?

python pyLoadCli.py -l
http://localhost:8000/api/generateAndAddPackages?links=

Thanks

**Comment by GammaC0de** [comment]
CLI is no more but you can use curl to access API:
```
curl -c cookie.txt -d "username=xxx&password=yyy" http://localhost:8000/api/login
curl -b cookie.txt "http://localhost:8000/api/addPackage?name=%5B%22https://www.somesite.com/file/sample.zip%22%5D"
```

**Comment by HPP8140** [comment]
Thanks. Can you provide an example of adding multiple links?

**Comment by HPP8140** [comment]
Oh looks like all the .4.9 api functions are in this legacy init
https://github.com/pyload/pyload/blob/main/src/pyload/core/api/__init__.py

**Comment by HPP8140** [comment]
> CLI is no more but you can use curl to access API:
> 
> ```
> curl -c cookie.txt -d "username=xxx&password=yyy" http://localhost:8000/api/login
> curl -b cookie.txt "http://localhost:8000/api/addPackage?name=%5B%22https://www.somesite.com/file/sample.zip%22%5D"
> ```

Help...the example asks for captcha?

 <label>Text
                        <span class="small">Input the text on the captcha.</span>
                        </label>

**Comment by GammaC0de** [comment]
> Help...the example asks for captcha?

What do you mean? it should not ask for any captcha

**Comment by HPP8140** [comment]
> > Help...the example asks for captcha?
> 
> What do you mean? it should not ask for any captcha

Sorry, I must have been running it on the old .4.9. I got the error below, but figured out the correct format.

**Error:**
`{"error": "Api.add_package() missing 1 required positional argument: 'links'", "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/dist-packages/pyload/webui/app/blueprints/api_blueprint.py\", line 58, in rpc\n    response = call_api(func, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/dist-packages/pyload/webui/app/blueprints/api_blueprint.py\", line 72, in call_api\n    result = getattr(api, func)(\n             ^^^^^^^^^^^^^^^^^^^\nTypeError: Api.add_package() missing 1 required positional argument: 'links'\n"}`



**Good:**
`curl -b cookie.txt "http://192.168.1.40:8000/api/addPackage?name=%22nametest%22&links=%5B%22https://www.somesite.com/file/sample.zip%22,%22https://www.somesite.com/file/sample.zip%22%5D"`

Thanks

**Comment by GammaC0de** [comment]
👍
