### ISSUE TITLE
Need help to reset password in docker

### ISSUE THREAD

**Issue by hiiragizawakun** [pyload/pyload#4359]
### Question

I accidentally deleted my pyload login credential.

I need a way to reset my password. I've installed pyload via docker.

I saw https://github.com/obi12341/docker-pyload/issues/15 but I am unable to find pyLoadCore.py within my docker container.

### Additional references

Version:
root@4b3c5fc674c2:/# pyload --version
pyLoad 0.5.0

**Comment by GammaC0de** [comment]
You'd better use https://github.com/linuxserver/docker-pyload-ng

**Comment by hiiragizawakun** [comment]
Looking at my docker compose, I think I’m already using it…

version: '2'
services:
  pyload:
    image: linuxserver/pyload-ng
    container_name: pyload2
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/usb/pyload2/config:/config
      - /mnt/usb/pyload2/downloads:/downloads
    ports:
      - 8000:8000 # Webinterface
      - 9666:9666 # Click 'N' Load
    restart: unless-stopped

**Comment by hiiragizawakun** [comment]
And going into docker terminal and triggering pyload -r does not work… it doesn’t seem to revert to default password

**Comment by GammaC0de** [comment]
Use  `pyload -r` to reset password to default

**Comment by GammaC0de** [comment]
If you dont mind loosing all the packages the look for `pyload.db` in `/mnt/usb/pyload2/config:/config` and rename/delete it.

**Comment by hiiragizawakun** [comment]
> Use `pyload -r` to reset password to default

This doesn't work... :(

I did get this in terminal - not sure if this is correct?

pi@raspberrypi:~ $ docker exec -it 4b3c5fc674c2 bash
root@4b3c5fc674c2:/# pyload -r
pyLoad already running with pid 113

**Comment by GammaC0de** [comment]
This is as far as my docker knowledge goes.
I suggest you ask for help in https://github.com/linuxserver/docker-pyload-ng

**Comment by hiiragizawakun** [comment]
Note that this resolved on it's own without mr doing anything for some reason.

**Comment by hiiragizawakun** [comment]
Closed without any resolution - I created another instance of pyload instead.
