### ISSUE TITLE
pyLoad Hoster now Downloader

### ISSUE THREAD

**Issue by HPP8140** [pyload/pyload#4362]
### Question

So for pylaod 0.4.9, I wrote new plugins using the Hoster....now called Downloader in pyLoad-ng. Can you provide a brief overview of the difference between SimpleDownloader and BaseDownloader below? 

**pylaod 0.4.9**
from module.plugins.Hoster import Hoster
class YoutubeCom(Hoster):

**pyload-ng**
from ..base.downloader import BaseDownloader
class YoutubeCom(BaseDownloader):

from ..base.simple_downloader import SimpleDownloader
class VimeoCom(SimpleDownloader):

**Comment by GammaC0de** [comment]
`BaseDownloader` is the bare downloader plugin, the main function is `process()`, it its up to you (the plugin coder) to do all the necessary tasks for getting an active download.

`SimpleDownloader` on the other hand is somewhat more advanced downloader plugin, it uses regex patterns to detect info (like `WAIT_PATTERN`, `NAME_PATTERN`, `SIZE_PATTERN`, `LINK_PATTERN`, etc..), it also tries to detect if the URL is a direct download and if so downloads the URL.
if it is not a direct download then it loads the URL page HTML into `self.data`.
The main function for `SimpleDownloader` are `handle_free()` and `handle_premium()`.
Once you found the correct download link, you can put it in `self.link` or call `self.download(link)`.
