### ISSUE TITLE
flask-2.3 module 'flask.json' has no attribute 'JSONEncoder'

### ISSUE THREAD

**Issue by sven76** [pyload/pyload#4364]
### Description

flask-2.3.0 doesn't provide JSONDecoder anymore. (see link below)

JSONDecoder is available via python3-builtin json package.

Updated pyload via pip install --upgrade git+https://github.com/pyload/pyload.git@develop

Pyload-0.5.0 didn't start. I've changed 

webui/app/helpers.py:12:class JSONEncoder(flask.json.JSONEncoder):

to builtin json module

import json
class JSONEncoder(json.JSONEncoder):

Pyload starts, but it's not possible to expand a container via web interface. Also starting the download of a container isn't working.

### Debug log

Aug 30 09:39:47 kobold pyload[3687]:   File "/usr/local/bin/pyload", line 8, in <module>
Aug 30 09:39:47 kobold pyload[3687]:     sys.exit(main())
Aug 30 09:39:47 kobold pyload[3687]:   File "/var/lib/pyload/.local/lib/python3.9/site-packages/pyload/__main__.py", line 292, in main
Aug 30 09:39:47 kobold pyload[3687]:     run(core_args, args.daemon, args.pidfile)
Aug 30 09:39:47 kobold pyload[3687]:   File "/var/lib/pyload/.local/lib/python3.9/site-packages/pyload/__main__.py", line 235, in run
Aug 30 09:39:47 kobold pyload[3687]:     pyload_core = Core(*core_args)
Aug 30 09:39:47 kobold pyload[3687]:   File "/var/lib/pyload/.local/lib/python3.9/site-packages/pyload/core/__init__.py", line 105, in __init__
Aug 30 09:39:47 kobold pyload[3687]:     self._init_webserver()
Aug 30 09:39:47 kobold pyload[3687]:   File "/var/lib/pyload/.local/lib/python3.9/site-packages/pyload/core/__init__.py", line 168, in _init_webserver
Aug 30 09:39:47 kobold pyload[3687]:     from pyload.webui.webserver_thread import WebServerThread
Aug 30 09:39:47 kobold pyload[3687]:   File "/var/lib/pyload/.local/lib/python3.9/site-packages/pyload/webui/webserver_thread.py", line 9, in <module>
Aug 30 09:39:47 kobold pyload[3687]:     from .app import App
Aug 30 09:39:47 kobold pyload[3687]:   File "/var/lib/pyload/.local/lib/python3.9/site-packages/pyload/webui/app/__init__.py", line 17, in <module>
Aug 30 09:39:47 kobold pyload[3687]:     from .blueprints import BLUEPRINTS
Aug 30 09:39:47 kobold pyload[3687]:   File "/var/lib/pyload/.local/lib/python3.9/site-packages/pyload/webui/app/blueprints/__init__.py", line 11, in <module>
Aug 30 09:39:47 kobold pyload[3687]:     from .app_blueprint import bp as app_bp
Aug 30 09:39:47 kobold pyload[3687]:   File "/var/lib/pyload/.local/lib/python3.9/site-packages/pyload/webui/app/blueprints/app_blueprint.py", line 17, in <module>
Aug 30 09:39:47 kobold pyload[3687]:     from ..helpers import (
Aug 30 09:39:47 kobold pyload[3687]:   File "/var/lib/pyload/.local/lib/python3.9/site-packages/pyload/webui/app/helpers.py", line 12, in <module>
Aug 30 09:39:47 kobold pyload[3687]:     class JSONEncoder(flask.json.JSONEncoder):
Aug 30 09:39:47 kobold pyload[3687]: AttributeError: module 'flask.json' has no attribute 'JSONEncoder'

### Additional references

https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0

**Comment by GammaC0de** [comment]
```
Aug 30 09:39:47 kobold pyload[3687]: File "/var/lib/pyload/.local/lib/python3.9/site-packages/pyload/webui/app/helpers.py", line 12, in
Aug 30 09:39:47 kobold pyload[3687]: class JSONEncoder(flask.json.JSONEncoder):
Aug 30 09:39:47 kobold pyload[3687]: AttributeError: module 'flask.json' has no attribute 'JSONEncoder'
```
Your installation is not up-to-date, see [helpers.py#L12](https://github.com/pyload/pyload/blob/ff7f3a86e1ab3f59b65c8a319c66f2eb397f8851/src/pyload/webui/app/helpers.py#L12) for example:
```
class JSONEncoder(json.JSONEncoder):
```
