### ISSUE TITLE
Fikper

### ISSUE THREAD

**Issue by artdog123** [pyload/pyload#4374]
Currently only anonymous downloads are supported.
If you want to add support for premium downloads, 
account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

_Originally posted by @GammaC0de in https://github.com/pyload/pyload/issues/4271#issuecomment-1501054886_

**Comment by artdog123** [comment]
Hi GammaCOde. I recently signed up so I'm happy to help with this. I'd love to have a premium plugin for Fikper

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by artdog123** [comment]
Sent

**Comment by artdog123** [comment]
How can I obtain the plugin?

**Comment by GammaC0de** [comment]
Use your API key for password

**Comment by artdog123** [comment]
Right. DOH! Thanks for the help. Working now but you already knew that. :D
