### ISSUE TITLE
Plugin AlldebridCom KO due to URL change 

### ISSUE THREAD

**Issue by Jqh63** [pyload/pyload#4375]
### Description
Pattern to match alldebrid links is KO due to update on service.
Source code to update locate into src/pyload/plugins/downloaders/AlldebridCom.py
KO pattern : `"https?://(?:\w+\.)?(?:alldebrid\.com|debrid\.it)/dl/[\w^_]+"`
but /dl/ have been change to /f/

### Debug log

Exemple:
link https://alldebrid.com/f/BLJJNF065h6ZLWOir0tlXrZNQqa8ZtioN0f5WUcgocE
goes directly to DefaultPlugin

FYI remove log due to API key leak

**Comment by jckytf** [comment]
@GammaC0de can we merge this into the main bench too? so people who use linuxserver/pyload-ng:latest can get this fix?

**Comment by GammaC0de** [comment]
all changes from `develop` have now pushed into `main`.
