### ISSUE TITLE
Api session login and add package

### ISSUE THREAD

**Issue by OndrejIT** [pyload/pyload#4388]
Previously (pyload stable), when calling the login api, it returned the session ID directly as the response, I then passed this response to the addPackage plugin as the session in the POST.
Unfortunately this doesn't work in the new pyload. When I login via api I only get the session ID in cookies, and even this ID I can't then send to addPackage as I could before.

I needed this because I wrote a browser plugin (grasemonkey Js script) that sent the current open page to pyload.

Would it be possible to revert this behavior?

**Comment by GammaC0de** [comment]
Please provide code snippet / logs of what you are trying to do.

You can also use basic auth with api, see [pyload_bookmarklet.js#L261](https://github.com/pyload/pyload-bookmarklet/blob/master/pyload_bookmarklet.js#L261)

Also https://github.com/RemiRigal/Yape

**Comment by OndrejIT** [comment]
https://github.com/RemiRigal/Yape working great.,
