### ISSUE TITLE
server certificate verification failed

### ISSUE THREAD

**Issue by geronimoronin** [pyload/pyload#4390]
Hi I cannot download any files from ddownload.com because of  server certificate verification failed. 
download  from ypoutube works without any problems.

System :  uname -a
Linux odroidc2 6.1.50-current-meson64 #2 SMP PREEMPT Wed Aug 30 14:11:13 UTC 202 

pyLoad: Version:  0.5.0

LOG
<html><body>

(60, 'server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none')
--
526 | ? | ? | ? | Traceback (most recent call last):
527 | ? | ? | ? | File "/home/ronin/.local/lib/python3.11/site-packages/pyload/core/threads/download_thread.py", line 56, in run
528 | ? | ? | ? | pyfile.plugin.preprocessing(self)
529 | ? | ? | ? | File "/home/ronin/.local/lib/python3.11/site-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
530 | ? | ? | ? | return self._process(*args, **kwargs)
531 | ? | ? | ? | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
532 | ? | ? | ? | File "/home/ronin/.local/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 103, in _process
533 | ? | ? | ? | self.process(self.pyfile)
534 | ? | ? | ? | File "/home/ronin/.local/lib/python3.11/site-packages/pyload/plugins/base/simple_downloader.py", line 286, in process
535 | ? | ? | ? | self.download(self.link, disposition=self.DISPOSITION)
536 | ? | ? | ? | File "/home/ronin/.local/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 330, in download
537 | ? | ? | ? | newname = self._download(
538 | ? | ? | ? | ^^^^^^^^^^^^^^^
539 | ? | ? | ? | File "/home/ronin/.local/lib/python3.11/site-packages/pyload/plugins/base/downloader.py", line 238, in _download
540 | ? | ? | ? | newname = self.req.http_download(
541 | ? | ? | ? | ^^^^^^^^^^^^^^^^^^^^^^^
542 | ? | ? | ? | File "/home/ronin/.local/lib/python3.11/site-packages/pyload/core/network/browser.py", line 116, in http_download
543 | ? | ? | ? | name = self.dl.download(chunks, resume)
544 | ? | ? | ? | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
545 | ? | ? | ? | File "/home/ronin/.local/lib/python3.11/site-packages/pyload/core/network/http/http_download.py", line 132, in download
546 | ? | ? | ? | self._download(chunks, resume)
547 | ? | ? | ? | File "/home/ronin/.local/lib/python3.11/site-packages/pyload/core/network/http/http_download.py", line 275, in _download
548 | ? | ? | ? | raise ex or Exception
549 | ? | ? | ? | pycurl.error: (60, 'server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none')

</body>
</html>

 sudo apt-get install --reinstall ca-certificates   couldn't solve the problem either

**Comment by geronimoronin** [comment]
Problem solved , Verify SSL certificates: was activated in general Settings

**Comment by mihawk90** [comment]
> Problem solved , Verify SSL certificates: was activated in general Settings

Disabling SSL verification is a super bad idea.

#4383
#4273
