### ISSUE TITLE
Pyload can't access account 

### ISSUE THREAD

**Issue by Milimeter1991** [pyload/pyload#4413]
### Question

Hi sorry I'm new to GitHub so I hope I do it right:

I have a problem with pyload running in a Docker container. I used the default Docker Compose. When I try to log in with my premium account, I get the error message:

vbnet
Copy code
ACCOUNT RapidgatorNet: Login user `the*******`...
66	28.12.2023 20:42:46	ERROR	ACCOUNT RapidgatorNet: (6, 'Could not resolve host: rapidgator.net')
67	28.12.2023 20:42:46	ERROR	ACCOUNT RapidgatorNet: Could not login user `the*******` | Login handshake has failed

It worked after installation but suddenly stopped working. I also use pihole in another container; could that be related? The host is accessible via the browser, and login credentials are correct.

Best regards, milimeter

**Comment by GammaC0de** [comment]
You have DNS issues.

**Comment by marc-cenon** [comment]
Hi,
I have the same issue running in k8s. It was working fine for a long time. Update to the lasted version didn't fix it.
No DNS issues on my side....
Any updates ?

**Comment by GammaC0de** [comment]
`(6, 'Could not resolve host:... ` is a pycurl error which means pycurl failed to resolve the host name into IP address, hence DNS issues
