### ISSUE TITLE
pyLoad installation fails  on TrueNAS Scale 22.12.4.2

### ISSUE THREAD

**Issue by shiftZZnet** [pyload/pyload#4417]
### Description

Dear all,

first: happy new year to the community!

I have a TrueNAS Scale installation (TrueNAS-SCALE-22.12.4.2) running and was using pyLoad chart for about half a year now without problems, it's a great tool. The process then stopped working reliably about 1 week ago without any change of the underlying architecture. There was no update to the NAS.

I then tried to restart pyLoad, no success. I rebooted the NAS, no success. I finally uninstalled pyLoad and re-installing it again and it fails the installation, see debug log with the errors. I tried it several times and in the end I did not configure anything during the installation process. I took all default values.

I tried the following versions which are offered, but none of them works:
```
- 12.0.0
- 12.0.1
- 12.1.0
- 12.1.3
```

### Debug log

```
Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 427, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 465, in __run_body
    rv = await self.method(*([self] + args))
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1247, in nf
    res = await f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1379, in nf
    return await func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 486, in do_create
    await self.middleware.call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1368, in call
    return await self._call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1328, in _call
    return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1231, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/helm.py", line 44, in helm_action
    raise CallError(f'Failed to {tn_action} chart release: {stderr.decode()}')
middlewared.service_exception.CallError: [EFAULT] Failed to install chart release: Error: INSTALLATION FAILED: template: pyload/templates/common.yaml:1:3: executing "pyload/templates/common.yaml" at <include "tc.v1.common.loader.all" .>: error calling include: template: pyload/charts/common/templates/loader/_all.tpl:6:6: executing "tc.v1.common.loader.all" at <include "tc.v1.common.loader.apply" .>: error calling include: template: pyload/charts/common/templates/loader/_apply.tpl:47:6: executing "tc.v1.common.loader.apply" at <include "tc.v1.common.spawner.pvc" .>: error calling include: template: pyload/charts/common/templates/spawner/_pvc.tpl:25:10: executing "tc.v1.common.spawner.pvc" at <include "tc.v1.common.lib.persistence.validation" (dict "rootCtx" $ "objectData" $objectData)>: error calling include: template: pyload/charts/common/templates/lib/storage/_validation.tpl:18:43: executing "tc.v1.common.lib.persistence.validation" at <$objectData.static.mode>: nil pointer evaluating interface {}.mode
```

### Additional references

I would really like any feedback because I'm quite unsure why the installation fails. Any ideas are highly appreciated! 
Thanks in advance,
Joachim.

**Comment by shiftZZnet** [comment]
Oh my dear, I was just realizing that I wasn't able anymore to install *any* app on my NAS. That means that most probably it's not a bug of pyload. Moreover it seems that something has changed inside TrueNAS installation which leads to the error.

We can close here, sorry for raising the issue.

**Comment by GammaC0de** [comment]
yes, you have issue with `middlewared`, whatever it is..

**Comment by mihawk90** [comment]
Are you launching the container manually via "Launch Docker Container" or are you using the TrueCharts repo version?

Because I've been having issues updating my TrueCharts apps for roughly the same time as well, and I'm thinking it's an issue with the TrueCharts repo since there was no Scale update.

My pyload container is launched manually and it still works, so try that I guess.

**Comment by shiftZZnet** [comment]
@GammaC0de : Yes, that is true. And I kind of fixed it now.

@mihawk90: There was an update to TrueNAS scale, I found it accidentally when looking for the NULL pointer exception. I found the following thread on reddit:

https://www.reddit.com/r/truecharts/comments/18oqxlb/issues_installing_traefik_truenas_scale/?rdt=61466

I then upgraded my TruerNAS 22.12 installation to 23.10. That was only possible by changing the train. 

![Screenshot 2024-01-03 at 13 17 05](https://github.com/pyload/pyload/assets/106601931/8d499057-8f31-41f7-9204-1c9d9d443832)

Afterwards every app was installable again, especially the `pyLoad` app in the latest version:

![Screenshot 2024-01-03 at 13 18 20](https://github.com/pyload/pyload/assets/106601931/b63687f7-f2f1-4518-87f9-c484df55677a)

These are the catalogs I'm installing my truechart apps from:

![Screenshot 2024-01-03 at 13 19 42](https://github.com/pyload/pyload/assets/106601931/c5404613-f415-421a-9977-b385ddcfcbc3)

Greetings!

**Comment by mihawk90** [comment]
> There was an update to TrueNAS scale

Sorry, might have been poorly worded. There was no update to the 22.12 (Bluefin) branch. The last one was in October or so. 
The update you're referring to is the 23.10 (Cobia) branch and is a major version upgrade. Depending on the usecase an upgrade isn't always advisable, and both are still supported.

According to the [TrueCharts Support policy](https://truecharts.org/manual/SUPPORT/) they also still support 22.12 just as iX does, so technically it should be working. I haven't had much motivation to look into it or ask on the discord though.
