### ISSUE TITLE
Worldbytez.com plugin not working

### ISSUE THREAD

**Issue by aleZZ2001** [pyload/pyload#4418]
### Description
Worldbytez.com plugin not working, account added, premium not detected and download a link file instead of file

### Debug log

<html>
<body>

39 | 2024-01-02 17:34:55 | INFO | pyload | Added package Prova containing 1 links
-- | -- | -- | -- | --
40 | 2024-01-02 17:34:55 | INFO | pyload | Download starts: 3cpfb3o4qpas
41 | 2024-01-02 17:34:55 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_preparing`
42 | 2024-01-02 17:34:55 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
43 | 2024-01-02 17:34:55 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting maximum redirections to 10
44 | 2024-01-02 17:34:55 | DEBUG | pyload | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`
45 | 2024-01-02 17:34:55 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1]: Plugin version: 0.52
46 | 2024-01-02 17:34:55 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1]: Plugin status: testing
47 | 2024-01-02 17:34:55 | WARNING | pyload | DOWNLOADER DefaultPlugin[1]: Plugin may be unstable
48 | 2024-01-02 17:34:55 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1]: Config option `use_premium` not found, use default `True`
49 | 2024-01-02 17:34:55 | INFO | pyload | DOWNLOADER DefaultPlugin[1]: Grabbing link info...
50 | 2024-01-02 17:34:55 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1]: Link info: {'name': '3cpfb3o4qpas', 'hash': {}, 'pattern': {}, 'size': 0, 'status': 7, 'url': 'https://worldbytez.com/3cpfb3o4qpas'}
51 | 2024-01-02 17:34:55 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1]: Previous link info: {}
52 | 2024-01-02 17:34:55 | INFO | pyload | DOWNLOADER DefaultPlugin[1]: Link name: 3cpfb3o4qpas
53 | 2024-01-02 17:34:55 | INFO | pyload | DOWNLOADER DefaultPlugin[1]: Link size: N/D
54 | 2024-01-02 17:34:55 | INFO | pyload | DOWNLOADER DefaultPlugin[1]: Link status: starting
55 | 2024-01-02 17:34:55 | INFO | pyload | DOWNLOADER DefaultPlugin[1]: Processing url: https://worldbytez.com/3cpfb3o4qpas
56 | 2024-01-02 17:34:55 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1]: DOWNLOAD URL https://worldbytez.com/3cpfb3o4qpas \| get={} \| post={} \| ref=False \| cookies=True \| disposition=True \| resume=None \| chunks=None
57 | 2024-01-02 17:34:56 | DEBUG | pyload | Chunk 1 download finished
58 | 2024-01-02 17:34:56 | INFO | pyload | DOWNLOADER DefaultPlugin[1]: File saved
59 | 2024-01-02 17:34:56 | INFO | pyload | DOWNLOADER DefaultPlugin[1]: Checking download...
60 | 2024-01-02 17:34:56 | INFO | pyload | DOWNLOADER DefaultPlugin[1]: File is OK
61 | 2024-01-02 17:34:56 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_processed`
62 | 2024-01-02 17:34:56 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `package_processed`
63 | 2024-01-02 17:34:56 | INFO | pyload | Download finished: 3cpfb3o4qpas
64 | 2024-01-02 17:34:56 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_finished`
65 | 2024-01-02 17:34:56 | INFO | pyload | Package finished: Prova
66 | 2024-01-02 17:34:56 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `package_finished`
67 | 2024-01-02 17:34:56 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
68 | 2024-01-02 17:34:56 | DEBUG | pyload | All downloads processed
69 | 2024-01-02 17:34:56 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `all_downloads_finished`
70 | 2024-01-02 17:34:56 | DEBUG | pyload | All downloads finished

</body>
</html>

**Comment by GammaC0de** [comment]
pyLoad currently does not support Worldbytez.com

**Comment by aleZZ2001** [comment]
Can you make this work ASAP? I have about 15k people in a forum Which could use it to replace jd2

**Comment by GammaC0de** [comment]
> You can download files up to 50 Mb only for free account.

Is this a premium download?

**Comment by aleZZ2001** [comment]
Yes, i can send my account for testing purpose

**Comment by GammaC0de** [comment]
Please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by aleZZ2001** [comment]
Sended

**Comment by GammaC0de** [comment]
URL is offline, please provide a new sample URL.

**Comment by aleZZ2001** [comment]
https://worldbytez.com/3i97gfbul8pm

**Comment by aleZZ2001** [comment]
I have another question/request. is there an option for autoname the packages? like JD2

**Comment by aleZZ2001** [comment]
On JD2 when you paste the link it auto-extracts the package name without me having to give it to it

![image](https://github.com/pyload/pyload/assets/36056536/b9cad449-6a3d-4238-97f3-03cb8c072e0b)

**Comment by aleZZ2001** [comment]
Can I send you a video to try to explain what I mean?

**Comment by GammaC0de** [comment]
Ok

**Comment by aleZZ2001** [comment]
[video demo.zip](https://github.com/pyload/pyload/files/13938025/video.demo.zip)

**Comment by GammaC0de** [comment]
#4427 I'll see what can be done, no promises.
