### ISSUE TITLE
MEGA File Size limit

### ISSUE THREAD

**Issue by guidocioni** [pyload/pyload#4426]
### Question
I'm using MEGA with a private account, BUT without a subscription, which means I can only download a certain file size (5 GB I believe ) before incurring into an individual file size limit.

Once I hit this limit, I then have to wait about 6hrs for the download to start again. This works in the browser on my computer, but in pyload the download always fails with  `Free download failed | Parse error: Empty file | Plugin may be out of date.`

Shouldn't pyload at least try to download the chunk that it can, then wait and download the remaining part even with the free quota?
The waiting mechanism works really well fo individual files that are under the size limit.

**Comment by clst** [comment]
I think it can be done. megabasterd (also on github) seems to do it like that.

**Comment by guidocioni** [comment]
> I think it can be done. megabasterd (also on github) seems to do it like that.

So  it is not yet implemented in pyload?

**Comment by GammaC0de** [comment]
> I'm using MEGA with a private account, BUT without a subscription

So what you're saying is that you are using a free account?

> Shouldn't pyload at least try to download the chunk that it can, then wait and download the remaining part even with the free quota?

Theoretically yes but MEGA does not support traditional HTTP resume but uses proprietary alternative which pyload does support (yet?) 

> The waiting mechanism works really well fo individual files that are under the size limit.

Please explain..

**Comment by guidocioni** [comment]
> > I'm using MEGA with a private account, BUT without a subscription
> 
> So what you're saying is that you are using a free account?


Yes, Sorry.
> 
> > Shouldn't pyload at least try to download the chunk that it can, then wait and download the remaining part even with the free quota?
> 
> Theoretically yes but MEGA does not support traditional HTTP resume but uses proprietary alternative which pyload does support (yet?)
> 

Ah ok that explains it then, I get it.

> > The waiting mechanism works really well fo individual files that are under the size limit.
> 
> Please explain..

Doesn't matter. Now I understand the problem.. of course for an individual file that is smaller than the limit it doesn't really matter. I was talking about the wait mechanism that kicks of once you hit the transfer limits after downloading many files.
