### ISSUE TITLE
[Wiki] Wrong config file path and format

### ISSUE THREAD

**Issue by hkcomori** [pyload/pyload#4433]
### Question

[Wiki](/pyload/pyload/wiki/Configuration) said:

> pyLoad has two configurations, core.xml is for the pyLoad Core, plugin.xml for all the plugins. These are located in module/config/.

But in fact:

- `~/.pyload/settings/pyload.cfg` for the pyLoad Core
- `~/.pyload/settings/plugins.cfg` for all the plugins
- `~/.pyload/settings/account.cfg` for hoster accounts?

All files seem to be in a non-XML format (Original format?).

My knowledge is limited (just started using this), so sorry if I am wrong.

**Comment by GammaC0de** [comment]
The wiki is incorrect, I will update it today.

**Comment by GammaC0de** [comment]
updated
