### ISSUE TITLE
pyload error 'latin-1' codec can't encode character u'\u015a' in position 87: ordinal not in range(256)

### ISSUE THREAD

**Issue by GeekeR2** [pyload/pyload#4448]
Hello. I use pylad version 0.4.20 and I have a problem because I don't want to download files from links with Polish characters, this error is displayed 'latin-1' codec can't encode character u'\u015a' in position 87: ordinal not in range(256). In the network interface, I have UTF-8 set in the plug-ins txt, but it does not help. please help.

**Comment by GeekeR2** [comment]
I will also add that I download from https://www.rapideo.net/

**Comment by GammaC0de** [comment]
1. enable debug mode and provide logs
2. You'd better use pyload 0.5 with python 3 which uses Unicode strings natively.

**Comment by GeekeR2** [comment]
but in pyload 5.0 there is no Remote and I really need it

**Comment by GeekeR2** [comment]
but there is no remote in pyload 5.0 and I really need it

**Comment by GeekeR2** [comment]
I use it on qnap in Container Station and I don't know how to enable debugging mode and log sharing, if you tell me, I will do it

**Comment by GammaC0de** [comment]
On the WebUI go to Config -> General -> set "Debug mode:" to on.
Restart pyload and do a faulty download.
On the top of the WebUI  there is a Logs tab.

**Comment by GeekeR2** [comment]
something like this occurred to me
<html>
<body>

163 | 15.04.2024 00:04:53 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
-- | -- | -- | --
164 | 15.04.2024 00:04:53 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
165 | 15.04.2024 00:04:53 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
166 | 15.04.2024 00:04:53 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
167 | 15.04.2024 00:04:53 | DEBUG | HOSTER BasePlugin[5]: Plugin version: 0.52
168 | 15.04.2024 00:04:53 | DEBUG | HOSTER BasePlugin[5]: Plugin status: testing
169 | 15.04.2024 00:04:53 | WARNING | HOSTER BasePlugin[5]: Plugin may be unstable
170 | 15.04.2024 00:04:53 | DEBUG | HOSTER BasePlugin[5]: Config option `use_premium` not found, use default `True`
171 | 15.04.2024 00:04:53 | INFO | HOSTER BasePlugin[5]: Grabbing link info...
172 | 15.04.2024 00:04:53 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
173 | 15.04.2024 00:04:53 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
174 | 15.04.2024 00:04:53 | WARNING | Download failed: https://standard.rapideo.pl/59259777/37163a47af8c114066ffd734297955a8969d4560/Pierwsze_Święta_Misia_Yogi.1980.PL.DVDRip.XviD.AC3-0W0C.mp4 \| 'latin-1' codec can't encode character u'\u015a' in position 87: ordinal not in range(256)
175 | ? | ? | Traceback (most recent call last):
176 | ? | ? | File "/app/pyload/module/PluginThread.py", line 189, in run
177 | ? | ? | pyfile.plugin.preprocessing(self)
178 | ? | ? | File "/config/userplugins/internal/Base.py", line 290, in preprocessing
179 | ? | ? | return self._process(*args, **kwargs)
180 | ? | ? | File "/config/userplugins/internal/Hoster.py", line 107, in _process
181 | ? | ? | self._setup()
182 | ? | ? | File "/config/userplugins/internal/Base.py", line 165, in _setup
183 | ? | ? | self.grab_info()
184 | ? | ? | File "/config/userplugins/internal/Base.py", line 222, in grab_info
185 | ? | ? | new_info = self.get_info(replace_patterns(self.pyfile.url, self.URL_REPLACEMENTS), self.data)
186 | ? | ? | File "/config/userplugins/internal/Base.py", line 43, in get_info
187 | ? | ? | url = fixurl(url, unquote=True)
188 | ? | ? | File "/config/userplugins/internal/misc.py", line 531, in fixurl
189 | ? | ? | url = url.encode("latin1").decode("utf8") #: bugfix urllib
190 | ? | ? | UnicodeEncodeError: 'latin-1' codec can't encode character u'\u015a' in position 87: ordinal not in range(256)
191 | 15.04.2024 00:04:53 | INFO | Debug Report written to debug_BasePlugin_15-04-2024_00-04-53.zip
192 | 15.04.2024 00:04:53 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
193 | 15.04.2024 00:04:53 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: https://standard.rapideo.pl/59259777/37163a47af8c114066ffd734297955a8969d4560/Pierwsze_Święta_Misia_Yogi.1980.PL.DVDRip.XviD.AC3-0W0C.mp4 (pid:5)
194 | 15.04.2024 00:04:53 | INFO | ADDON UnSkipOnFail: No duplicates found
195 | 15.04.2024 00:04:53 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
196 | 15.04.2024 00:04:53 | DEBUG | All downloads processed


</body>
</html>

**Comment by GeekeR2** [comment]
<html>
<body>

163 | 15.04.2024 00:04:53 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
-- | -- | -- | --
164 | 15.04.2024 00:04:53 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
165 | 15.04.2024 00:04:53 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
166 | 15.04.2024 00:04:53 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
167 | 15.04.2024 00:04:53 | DEBUG | HOSTER BasePlugin[5]: Plugin version: 0.52
168 | 15.04.2024 00:04:53 | DEBUG | HOSTER BasePlugin[5]: Plugin status: testing
169 | 15.04.2024 00:04:53 | WARNING | HOSTER BasePlugin[5]: Plugin may be unstable
170 | 15.04.2024 00:04:53 | DEBUG | HOSTER BasePlugin[5]: Config option `use_premium` not found, use default `True`
171 | 15.04.2024 00:04:53 | INFO | HOSTER BasePlugin[5]: Grabbing link info...
172 | 15.04.2024 00:04:53 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
173 | 15.04.2024 00:04:53 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
174 | 15.04.2024 00:04:53 | WARNING | Download failed: https://standard.rapideo.pl/59259777/37163a47af8c114066ffd734297955a8969d4560/Pierwsze_Święta_Misia_Yogi.1980.PL.DVDRip.XviD.AC3-0W0C.mp4 \| 'latin-1' codec can't encode character u'\u015a' in position 87: ordinal not in range(256)
175 | ? | ? | Traceback (most recent call last):
176 | ? | ? | File "/app/pyload/module/PluginThread.py", line 189, in run
177 | ? | ? | pyfile.plugin.preprocessing(self)
178 | ? | ? | File "/config/userplugins/internal/Base.py", line 290, in preprocessing
179 | ? | ? | return self._process(*args, **kwargs)
180 | ? | ? | File "/config/userplugins/internal/Hoster.py", line 107, in _process
181 | ? | ? | self._setup()
182 | ? | ? | File "/config/userplugins/internal/Base.py", line 165, in _setup
183 | ? | ? | self.grab_info()
184 | ? | ? | File "/config/userplugins/internal/Base.py", line 222, in grab_info
185 | ? | ? | new_info = self.get_info(replace_patterns(self.pyfile.url, self.URL_REPLACEMENTS), self.data)
186 | ? | ? | File "/config/userplugins/internal/Base.py", line 43, in get_info
187 | ? | ? | url = fixurl(url, unquote=True)
188 | ? | ? | File "/config/userplugins/internal/misc.py", line 531, in fixurl
189 | ? | ? | url = url.encode("latin1").decode("utf8") #: bugfix urllib
190 | ? | ? | UnicodeEncodeError: 'latin-1' codec can't encode character u'\u015a' in position 87: ordinal not in range(256)
191 | 15.04.2024 00:04:53 | INFO | Debug Report written to debug_BasePlugin_15-04-2024_00-04-53.zip
192 | 15.04.2024 00:04:53 | DEBUG | ADDON ExternalScripts: No script found under folder `download_failed`
193 | 15.04.2024 00:04:53 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: https://standard.rapideo.pl/59259777/37163a47af8c114066ffd734297955a8969d4560/Pierwsze_Święta_Misia_Yogi.1980.PL.DVDRip.XviD.AC3-0W0C.mp4 (pid:5)
194 | 15.04.2024 00:04:53 | INFO | ADDON UnSkipOnFail: No duplicates found
195 | 15.04.2024 00:04:53 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
196 | 15.04.2024 00:04:53 | DEBUG | All downloads processed


</body>
</html>

**Comment by GeekeR2** [comment]
![1](https://github.com/pyload/pyload/assets/37579439/2bfcfd23-9658-4c3f-a198-7de5adc0c118)
![2](https://github.com/pyload/pyload/assets/37579439/ad8ddf7b-6648-403f-a8f3-aaa795ab1d29)

**Comment by GammaC0de** [comment]
plugin updated, restart pyload and rtry

**Comment by GeekeR2** [comment]
I don't know what you did but it works, thank you very much.

**Comment by GeekeR2** [comment]
And just out of curiosity, is it possible to have a remote in pyload 0.5

**Comment by GammaC0de** [comment]
> And just out of curiosity, is it possible to have a remote in pyload 0.5

I need time to do it.
See #4414

**Comment by GeekeR2** [comment]
Okey thank you good luck.
