### ISSUE TITLE
ddownload failes | 'NoneType' object has no attribute 'choose'

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#4449]
### Description

loading a package with c'n'l into pyload and want to start that package.
there is no captcha request and it failes imedeately.
Other hoster workes without issues.
Seems to there was a change at hoster side within the last weeks.

### Debug log

```
404 | 2024-04-19 14:30:29 | DEBUG | pyload | DOWNLOADER DdownloadCom[20977]: Plugin version: 0.11
405 | 2024-04-19 14:30:29 | DEBUG | pyload | DOWNLOADER DdownloadCom[20977]: Plugin status: testing
406 | 2024-04-19 14:30:29 | WARNING | pyload | DOWNLOADER DdownloadCom[20977]: Plugin may be unstable
407 | 2024-04-19 14:30:29 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_processed`
408 | 2024-04-19 14:30:29 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `package_processed`
409 | 2024-04-19 14:30:29 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `package_failed`
410 | 2024-04-19 14:30:29 | WARNING | pyload | Download failed: Star.Trek.Discovery.S05E04.GERMAN.DL.720.p.WEB.h.264-SAUERKRAUT.part2.rar \| 'NoneType' object has no attribute 'choose'
411 | 2024-04-19 14:30:29 | INFO | pyload | Debug Report written to /share/CACHEDEV1_DATA/.qpkg/Entware/tmp/pyload/debug_DdownloadCom_2024-04-19_14-30-29.zip
412 | 2024-04-19 14:30:29 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_failed`
413 | 2024-04-19 14:30:29 | INFO | pyload | ADDON UnSkipOnFail: Looking for skipped duplicates of: Star.Trek.Discovery.S05E04.GERMAN.DL.720.p.WEB.h.264-SAUERKRAUT.part2.rar (pid:1742)
414 | 2024-04-19 14:30:29 | INFO | pyload | ADDON UnSkipOnFail: No duplicates found
```

### Additional references

[Sample Link](https://ddownload.com/odbzg1c2ucd1/Star.Trek.Discovery.S05E04.GERMAN.DL.720.p.WEB.h.264-SAUERKRAUT.part1.rar)

**Comment by GammaC0de** [comment]
Is this a premium or free download?
It seem that you have some issue with the ddownload account.
This works fine for me (free download)

**Comment by UserX404** [comment]
It is a free download.
I have account credentials set but they has been expired.
Checking my accounts show my fist entry as None but i remember i as Ddownload in the past.
![PSX_20240420_103145](https://github.com/pyload/pyload/assets/14954521/c7e9a894-b3cc-4c76-875b-440a2f9ea6d1)

I dissabled 'Use premium account if available' for ddownload plugin and it's working again.
It's not possible todelet the entry with checking the delete-checkbox and apply afterwards.

**Comment by GammaC0de** [comment]
Just stop pyload and then remove the orphan account from `accounts.cfg`
