### ISSUE TITLE
Suggestion: optional CSS filters to improve visibility of certain captcha images

### ISSUE THREAD

**Issue by denilsonsa** [pyload/pyload#4457]
Some captcha images have a very low contrast rate and are hard to read by humans, specially humans with poor eyesight or on displays with poor color accuracy.

For instance, take a look at this image:

![Raw captcha image, with poor contrast](https://github.com/pyload/pyload/assets/121676/fc49e18e-5a87-4008-9a6f-3ac625ef6a0f)

The light colors for the letters against the white background makes them very hard to read. Thankfully, with a simple CSS rule like this:

```css
#cap_textual_img:hover {
    filter: brightness(51%) contrast(6400%) grayscale(100%);
}
```

That same image gets rendered as:

![Captcha image with the CSS filter applied, the letters are now black on top of a white background](https://github.com/pyload/pyload/assets/121676/73d87eda-d022-4f22-98e7-31108dec2adf)

### Implementation

We could have this effect applied as mouse-over (but then it wouldn't work for mobile devices or touch devices). We could have a little toggle to switch the effect on and off. Maybe two tabs, one with the effect and one without the effect.

We could have a central repository of effects per captcha provider. Or the user could also provide its own effect in the settings page. Maybe we could have a collection of different effects, and let them be picked on a per-captcha basis (just like those filters on the social media photo apps).

**Comment by denilsonsa** [comment]
@GammaC0de Thanks for implementing it so quickly!

Someone may want to review if some captcha systems have a dark/grey background, which would be unreadable with these filters. Sure, this can be done and improved in the future.

**Comment by GammaC0de** [comment]
If someone has issues with this I guess he will open an issue.
Of-course you don't have to hover the image if it shows improperly, so this would be a minor issue
