### ISSUE TITLE
Worldbytez plugin not detecting premium anymore

### ISSUE THREAD

**Issue by aleZZ2001** [pyload/pyload#4458]
Worldbytez plugin not detecting premium anymore, just this

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Have you sent the info?

**Comment by aleZZ2001** [comment]
> Have you sent the info?

email sended

**Comment by aleZZ2001** [comment]
https://worldbytez.com/1nvpxwcxzv33

link for try
