### ISSUE TITLE
Where's the "Development section" mentioned in the main page?

### ISSUE THREAD

**Issue by ky0utarou** [pyload/pyload#4459]
### Question

The [main page](https://pyload.net) mentions there's a well documented "Development section" for programming interface. But it doesn't seem to exist. Where's it?

**Comment by ky0utarou** [comment]
presumably this one https://github.com/pyload/pyload/wiki/How-to-access-the-API ?

**Comment by ky0utarou** [comment]
seems things aren't really "well documented". quite hard to interact with in a programatic way. 
for people interested in doing programatic downloading, consider using aria2: [dockerized backend](https://github.com/P3TERX/Aria2-Pro-Docker) and [python library](https://github.com/pawamoy/aria2p) operating it

**Comment by ky0utarou** [comment]
shouldn't have closed it. reopen to allow people see this

**Comment by GammaC0de** [comment]
Page updated,
Please note that the documentation may not be up to date, this is because lack of resources:
There are are many bugs/features to do before.

If you have any question regarding API you are welcome to ask here.
