### ISSUE TITLE
Add API key support to PixelDrainCom

### ISSUE THREAD

**Issue by heyhippari** [pyload/pyload#4473]
### Feature description

Pixel Drain allows to bypass some limitations on speed with the use of an API key. It'd be great to add support for this in order to allow users to use their account when downloading.

### Problem description

Downloads slow down after a set amount of data for the day. The API keys allow you to download more without a speed limit.

### Additional references

Pixel Drain API documentation: https://pixeldrain.com/api

**Comment by GammaC0de** [comment]
1. from reading https://pixeldrain.com/api you can see:
>
>Authentication
>
>The methods for uploading and retrieving files **don’t** require an API key.
>The methods for creating and retrieving lists also **don’t** require an API key. 
>All methods which delete or modify a resource **do** require an API key.

So are you saying that if you provide API  key to `/file/` method, it would be faster?
Please send API key to nitzo2001 at yahoo dot com.

**Comment by heyhippari** [comment]
> So are you saying that if you provide API key to /file/ method, it would be faster?

Indeed, as you can see on the [Subscription](https://pixeldrain.com/#pro) page, you get limited after 5GB per day on the free tier. You still get 1MiB/s, so it doesn't cut you off, but it's not ideal.

Relevant part of the page linked above:
![image](https://github.com/pyload/pyload/assets/19396809/c8d26ca0-b760-4383-bc82-e1e50d8ed58c)

---

I'll send you a key.
