### ISSUE TITLE
add hoster: freedl.ink = frdl.to

### ISSUE THREAD

**Issue by milahu** [pyload/pyload#4479]
https://freedl.ink/

download links look like `https://frdl.to/123456789012/somefile.txt.html`

jdownloader plugin [FreedlInk.java](https://github.com/mycodedoesnotcompile2/jdownloader_mirror/blob/main/svn_trunk/src/jd/plugins/hoster/FreedlInk.java)

but its rarely used, and seems broken, so near-zero priority

**Comment by GammaC0de** [comment]
I could fine a https://frdl.to/ URL and the plugin works.
Please provide a https://freedl.ink/ URL, I could not find one.
Also I cannot upload a file (wtf!?)

**Comment by milahu** [comment]
yepp, that hoster seems broken

closing
