### ISSUE TITLE
fireload.com host site support

### ISSUE THREAD

**Issue by Bluey26** [pyload/pyload#4482]
### Feature description

I was wondering if https://www.fireload.com/ could be added to the supported sites.

They have a wait time(usually 5 seconds) and allow several downloads at the same time.

I can provide an example URL if needed.

There seems to be fireload support in Jdownloader, i think it works, by what other users say.

### Additional references

[JdPlugin](https://github.com/mycodedoesnotcompile2/jdownloader_mirror/blob/main/svn_trunk/src/jd/plugins/hoster/FireloadCom.java)

**Comment by GammaC0de** [comment]
this web site is unstable
