### ISSUE TITLE
Extmatrix -  Parse error: No file downloaded | Plugin may be out of date 

### ISSUE THREAD

**Issue by victorhooi** [pyload/pyload#4485]
I can verify that Extmatrix logins are working again (https://github.com/pyload/pyload/issues/4481).

However, if you try to download any files - it seems to get some kind of parse error now?

The error message in pyload (seen in the Queue screen, and also in the logs is):

```
Parse error: No file downloaded | Plugin may be out of date 
```

**Comment by GammaC0de** [comment]
Well, sample URLs are needed..

**Comment by victorhooi** [comment]
I think any Extmatrix link should work (to reproduce the issue).

How about this one?

https://www.extmatrix.com/get/1YNLYG9Q/1718469472/VTMN-002.1080p.mp4/

**Comment by GammaC0de** [comment]
\have you changed the account password?

**Comment by victorhooi** [comment]
Ah I figured that file was downloadable by both free/premium.

No worries, I've changed my password back to the temporary one I sent you - can you try again?
