### ISSUE TITLE
ClickNLoad: SSL error: module 'ssl' has no attribute 'wrap_socket'

### ISSUE THREAD

**Issue by 646EIN** [pyload/pyload#4496]
### Description

I have installed a docker container from [https://github.com/linuxserver/docker-pyload-ng](https://github.com/linuxserver/docker-pyload-ng) which seem to use python3.12. When I try to use ClickNLoad I get an error and no links are transmitted to pyload. It seems like ssl.wrap_socket() was removed https://docs.python.org/3/whatsnew/3.12.html#ssl.

### Debug log

pyload-ng  | [2024-07-20 15:17:57]  DEBUG               pyload  ADDON ClickNLoad: Connection from 172.18.0.1:49680
pyload-ng  | [2024-07-20 15:17:57]  ERROR               pyload  ADDON ClickNLoad: SSL error: module 'ssl' has no attribute 'wrap_socket'
pyload-ng  | Traceback (most recent call last):
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/pyload/plugins/addons/ClickNLoad.py", line 189, in _server
pyload-ng  |     backend_socket = ssl.wrap_socket(backend_socket)
pyload-ng  |                      ^^^^^^^^^^^^^^^
pyload-ng  | AttributeError: module 'ssl' has no attribute 'wrap_socket'

**Comment by GammaC0de** [comment]
@646EIN Please test and report if it work now

**Comment by 646EIN** [comment]
Hi, thx for the response.
I have rebuild the docker image with pyload from develop branch and started it on my rpi5 with libreelec12.
Pyload seems to start correctly but when I try to connect my ClickNLoad port 9666 from my desktop pc to my rpi5 there is an error:

pyload-ng  | [2024-07-31 15:31:34]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `pyload_start`
pyload-ng  | [2024-07-31 15:31:34]  DEBUG               pyload  ADDON ExtractArchive: Found HjSplit 0.02 | Found UnRar 7.00 | Found SevenZip 23.01 | Found UnZip 3.12.3 | Found UnTar 3.12.3
pyload-ng  | [2024-07-31 15:31:34]  INFO          pyload.webui  Starting webserver: https://0.0.0.0:8000
pyload-ng  | [2024-07-31 15:31:34]  DEBUG               pyload  *** pyLoad is up and running ***
pyload-ng  | Connection to localhost (127.0.0.1) 8000 port [tcp/*] succeeded!
pyload-ng  | [ls.io-init] done.
pyload-ng  | [2024-07-31 15:31:39]  DEBUG               pyload  ADDON ClickNLoad: Backend found on https://127.0.0.1:8000
pyload-ng  | [2024-07-31 15:31:39]  INFO                pyload  ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
pyload-ng  | [2024-07-31 15:32:07]  DEBUG               pyload  ADDON ClickNLoad: Connection from 172.18.0.1:48844
pyload-ng  | [2024-07-31 15:32:07]  ERROR               pyload  ADDON ClickNLoad: SSL error: check_hostname requires server_hostname
pyload-ng  | Traceback (most recent call last):
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/pyload/plugins/addons/ClickNLoad.py", line 190, in _server
pyload-ng  |     backend_socket = context.wrap_socket(backend_socket)
pyload-ng  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 455, in wrap_socket
pyload-ng  |     return self.sslsocket_class._create(
pyload-ng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 970, in _create
pyload-ng  |     raise ValueError("check_hostname requires server_hostname")
pyload-ng  | ValueError: check_hostname requires server_hostname
pyload-ng  | [2024-07-31 15:32:07]  DEBUG               pyload  ADDON ClickNLoad: Connection from 172.18.0.1:48860
pyload-ng  | [2024-07-31 15:32:07]  ERROR               pyload  ADDON ClickNLoad: SSL error: check_hostname requires server_hostname
pyload-ng  | Traceback (most recent call last):
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/pyload/plugins/addons/ClickNLoad.py", line 190, in _server
pyload-ng  |     backend_socket = context.wrap_socket(backend_socket)
pyload-ng  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 455, in wrap_socket
pyload-ng  |     return self.sslsocket_class._create(
pyload-ng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 970, in _create
pyload-ng  |     raise ValueError("check_hostname requires server_hostname")
pyload-ng  | ValueError: check_hostname requires server_hostname



Here is how I connect my ports from desktop pc to rpi5:
`ssh -L9666:localhost:9666 root@libreelec` 
This usually works.
I also get an error message in the ssh shell:
channel 3: open failed: connect failed: Connection refused

**Comment by GammaC0de** [comment]
Please check now

**Comment by 646EIN** [comment]
My settings from pyload.cfg are:
webui - "Web Interface": ->  bool use_ssl : "Use HTTPS" = True

Port forwarding via `ssh -L9666:localhost:9666 root@libreelec` seems to works now, but when I try to add a package via ClickNLoad this error occurs:

```
pyload-ng  | [2024-07-31 20:00:00]  DEBUG               pyload  ADDON ClickNLoad: Connection from 172.18.0.1:58150
pyload-ng  | [2024-07-31 20:00:00]  ERROR               pyload  ADDON ClickNLoad: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)
pyload-ng  | Traceback (most recent call last):
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/pyload/plugins/addons/ClickNLoad.py", line 197, in _server
pyload-ng  |     backend_socket.connect(self.web_addr)
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1353, in connect
pyload-ng  |     self._real_connect(addr, False)
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1344, in _real_connect
pyload-ng  |     self.do_handshake()
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1320, in do_handshake
pyload-ng  |     self._sslobj.do_handshake()
pyload-ng  | ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)
```


When I change my settings to:
webui - "Web Interface": ->  bool use_ssl : "Use HTTPS" = False

Port forwarding & adding a package via ClickNLoad are working, but I can't login to the webinterface anymore. I can reach the login page via http, but when I enter the correct user+pw I get redirected to the same login page. I tried to login several times and even the logs are saying `User 'pyload' successfully logged in` :

```
pyload-ng  | [2024-07-31 20:05:13]  DEBUG               pyload  ADDON ClickNLoad: Backend found on http://127.0.0.1:8000
pyload-ng  | [2024-07-31 20:05:13]  INFO                pyload  ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
pyload-ng  | [2024-07-31 20:05:28]  INFO                pyload  User 'pyload' successfully logged in
pyload-ng  | [2024-07-31 20:05:36]  INFO                pyload  User 'pyload' successfully logged in
pyload-ng  | [2024-07-31 20:05:55]  DEBUG               pyload  ADDON ClickNLoad: Connection from 172.18.0.1:58796
pyload-ng  | [2024-07-31 20:05:56]  DEBUG               pyload  ADDON ClickNLoad: Connection from 172.18.0.1:58810
pyload-ng  | [2024-07-31 20:05:56]  INFO                pyload  Added package ************ - filecrypt.cc containing 6 links
pyload-ng  | [2024-07-31 20:07:14]  INFO                pyload  User 'pyload' successfully logged in
pyload-ng  | [2024-07-31 20:07:30]  INFO                pyload  User 'pyload' successfully logged in
pyload-ng  | [2024-07-31 20:08:55]  INFO                pyload  User 'pyload' successfully logged in
```
I even tried to restart Firefox and reloading the page but no luck...

**Comment by GammaC0de** [comment]
Try now

**Comment by 646EIN** [comment]
Seems like nothing changed. Still getting the error when I use the tls website and try to add a package:
```
pyload-ng  | [2024-07-31 21:15:11]  ERROR               pyload  ADDON ClickNLoad: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)
pyload-ng  | Traceback (most recent call last):
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/pyload/plugins/addons/ClickNLoad.py", line 198, in _server
pyload-ng  |     backend_socket.connect(self.web_addr)
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1353, in connect
pyload-ng  |     self._real_connect(addr, False)
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1344, in _real_connect
pyload-ng  |     self.do_handshake()
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1320, in do_handshake
pyload-ng  |     self._sslobj.do_handshake()
pyload-ng  | ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)
```

And when i use no tls ClickNLoad works but I can't login (as before).

I have also verified your change in pyload/plugins/addons/ClickNLoad.py from [7906bf4](https://github.com/pyload/pyload/commit/7906bf49c88debd7194c05a287d0da2d50e255e7)

**Comment by GammaC0de** [comment]
maybe now

**Comment by 646EIN** [comment]
Now I'm getting this error with tls on:
```
pyload-ng  | [2024-07-31 22:48:50]  DEBUG               pyload  ADDON ClickNLoad: Connection from 172.18.0.1:50440
pyload-ng  | [2024-07-31 22:48:50]  ERROR               pyload  ADDON ClickNLoad: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:806)
pyload-ng  | Traceback (most recent call last):
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/pyload/plugins/addons/ClickNLoad.py", line 199, in _server
pyload-ng  |     backend_socket.connect(self.web_addr)
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1353, in connect
pyload-ng  |     self._real_connect(addr, False)
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1331, in _real_connect
pyload-ng  |     self._sslobj = self.context._wrap_socket(
pyload-ng  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  | ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:806)
```

With tls off it seems to stuck when I try to add a package via ClickNload. No more log entries than this:
```
pyload-ng  | [2024-07-31 22:54:04]  DEBUG               pyload  ADDON ClickNLoad: Backend found on http://127.0.0.1:8000
pyload-ng  | [2024-07-31 22:54:04]  INFO                pyload  ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
pyload-ng  | [2024-07-31 22:54:17]  DEBUG               pyload  ADDON ClickNLoad: Connection from 172.18.0.1:33940
```
And my ClickNLoad browser popup shows neither red nor green

**Comment by GammaC0de** [comment]
Change CLIENT_AUTH to SERVER_AUTH

**Comment by GammaC0de** [comment]
please test

**Comment by 646EIN** [comment]
With activated tls:
Everything seems to work, but I found this error in the log:
```
pyload-ng  | [2024-08-05 19:10:26]  DEBUG               pyload  ADDON ClickNLoad: Backend found on https://127.0.0.1:8000
pyload-ng  | [2024-08-05 19:10:26]  INFO                pyload  ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
pyload-ng  | [2024-08-05 19:10:41]  ERROR         pyload.webui  Error in HTTPServer.serve
pyload-ng  | Traceback (most recent call last):
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/cheroot/server.py", line 1823, in serve
pyload-ng  |     self._connections.run(self.expiration_interval)
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/cheroot/connections.py", line 203, in run
pyload-ng  |     self._run(expiration_interval)
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/cheroot/connections.py", line 246, in _run
pyload-ng  |     new_conn = self._from_server_socket(self.server.socket)
pyload-ng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/cheroot/connections.py", line 300, in _from_server_socket
pyload-ng  |     s, ssl_env = self.server.ssl_adapter.wrap(s)
pyload-ng  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/cheroot/ssl/builtin.py", line 277, in wrap
pyload-ng  |     s = self.context.wrap_socket(
pyload-ng  |         ^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 455, in wrap_socket
pyload-ng  |     return self.sslsocket_class._create(
pyload-ng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1042, in _create
pyload-ng  |     self.do_handshake()
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1320, in do_handshake
pyload-ng  |     self._sslobj.do_handshake()
pyload-ng  | ssl.SSLError: [SSL] record layer failure (_ssl.c:1000)

```
With deactivated tls:
I still can't login to the webinterface.

**Comment by GammaC0de** [comment]
This is an issue with cheroot package, it probably should be updated.

**Comment by 646EIN** [comment]
With the new cheroot package there is an error about "bad" certs:

```
pyload-ng  | [2024-08-06 08:40:43]  DEBUG               pyload  ADDON ClickNLoad: Connection from 172.18.0.1:53920
pyload-ng  | [2024-08-06 08:40:53]  DEBUG               pyload  ADDON ClickNLoad: Connection from 172.18.0.1:56708
pyload-ng  | [2024-08-06 08:40:54]  INFO                pyload  Added package ****** containing 24 links
pyload-ng  | [2024-08-06 08:41:12]  ERROR         pyload.webui  Error in HTTPServer.serve
pyload-ng  | Traceback (most recent call last):
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/cheroot/server.py", line 1823, in serve
pyload-ng  |     self._connections.run(self.expiration_interval)
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/cheroot/connections.py", line 203, in run
pyload-ng  |     self._run(expiration_interval)
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/cheroot/connections.py", line 246, in _run
pyload-ng  |     new_conn = self._from_server_socket(self.server.socket)
pyload-ng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/cheroot/connections.py", line 300, in _from_server_socket
pyload-ng  |     s, ssl_env = self.server.ssl_adapter.wrap(s)
pyload-ng  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/lsiopy/lib/python3.12/site-packages/cheroot/ssl/builtin.py", line 277, in wrap
pyload-ng  |     s = self.context.wrap_socket(
pyload-ng  |         ^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 455, in wrap_socket
pyload-ng  |     return self.sslsocket_class._create(
pyload-ng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1042, in _create
pyload-ng  |     self.do_handshake()
pyload-ng  |   File "/usr/lib/python3.12/ssl.py", line 1320, in do_handshake
pyload-ng  |     self._sslobj.do_handshake()
pyload-ng  | ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] ssl/tls alert bad certificate (_ssl.c:1000)
pyload-ng  | [2024-08-06 08:41:26]  INFO                pyload  User 'pyload' successfully logged in
pyload-ng  | [2024-08-06 08:41:34]  INFO                pyload  Download starts: 04i65z761gti

```

But anyway everything seems to work with tls on

**Comment by GammaC0de** [comment]
Well, apperantly cheroot does not support python 3.12 yet...

**Comment by 646EIN** [comment]
Is there anything else I can do about the login problem with deactivated tls? I haven't found a proper way to start pyload with pdb inside of the container. Otherwise it's fine for me to close this issue.

**Comment by GammaC0de** [comment]
>Is there anything else I can do about the login problem with deactivated tls?

Probably open an issue on https://github.com/linuxserver/docker-pyload-ng/issues asking to use python3.11
or asking to support  python3.12 on https://github.com/cherrypy/cheroot/issues.

**Comment by 646EIN** [comment]
They already reverted the docker container to python 3.11. So everything should work again.

For the sake of completeness I found another error while using python 3.12:
```
17447	2024-08-08 21:00:03	WARNING	pyload	Download failed: VA - ***.zip | (56, 'OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0')
17448	? 	?	?	Traceback (most recent call last):
17449	? 	?	?	  File "/lsiopy/lib/python3.12/site-packages/pyload/core/threads/download_thread.py", line 55, in run
17450	? 	?	?	    pyfile.plugin.preprocessing(self)
17451	? 	?	?	  File "/lsiopy/lib/python3.12/site-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
17452	? 	?	?	    return self._process(*args, **kwargs)
17453	? 	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17454	? 	?	?	  File "/lsiopy/lib/python3.12/site-packages/pyload/plugins/base/downloader.py", line 103, in _process
17455	? 	?	?	    self.process(self.pyfile)
17456	? 	?	?	  File "/lsiopy/lib/python3.12/site-packages/pyload/plugins/base/simple_downloader.py", line 286, in process
17457	? 	?	?	    self.download(self.link, disposition=self.DISPOSITION)
17458	? 	?	?	  File "/lsiopy/lib/python3.12/site-packages/pyload/plugins/base/downloader.py", line 335, in download
17459	? 	?	?	    newname = self._download(
17460	? 	?	?	              ^^^^^^^^^^^^^^^
17461	? 	?	?	  File "/lsiopy/lib/python3.12/site-packages/pyload/plugins/base/downloader.py", line 240, in _download
17462	? 	?	?	    newname = self.req.http_download(
17463	? 	?	?	              ^^^^^^^^^^^^^^^^^^^^^^^
17464	? 	?	?	  File "/lsiopy/lib/python3.12/site-packages/pyload/core/network/browser.py", line 116, in http_download
17465	? 	?	?	    name = self.dl.download(chunks, resume)
17466	? 	?	?	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17467	? 	?	?	  File "/lsiopy/lib/python3.12/site-packages/pyload/core/network/http/http_download.py", line 134, in download
17468	? 	?	?	    self._download(chunks, resume)
17469	? 	?	?	  File "/lsiopy/lib/python3.12/site-packages/pyload/core/network/http/http_download.py", line 280, in _download
17470	? 	?	?	    raise ex or Exception
17471	? 	?	?	pycurl.error: (56, 'OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0')
17472	2024-08-08 21:00:03	INFO	pyload	Debug Report written to /tmp/pyLoad/debug_TurbobitNet_2024-08-08_21-00-03.zip
```
Seems like it needs a little bit of time till python 3.12 will work...
