### ISSUE TITLE
FastShareCz Cannot login to account or start downloading

### ISSUE THREAD

**Issue by Tessarai** [pyload/pyload#4500]
### Description

When I check my account info for Fastshare it shows not valid and no premium even though that's not true. If I try to delete the account and add it again, it will show up as None/None in the account list.
Even when I try to use Free mode, it will not download anything - it will use DefaultPlugin.
Fastshare changed their URLs to fastshare.cloud a while ago, so maybe that's the issue ?

### Debug log

Account changes and logins
<html><body>

11985 | 2024-08-12 10:03:22 | INFO | pyload | ACCOUNT FastshareCz: Adding user `vcg*******`...
-- | -- | -- | -- | --
11986 | 2024-08-12 10:03:22 | DEBUG | pyload | ACCOUNT FastshareCz: Reached login timeout for user `vcg****`
11987 | 2024-08-12 10:03:22 | INFO | pyload | ACCOUNT FastshareCz: Login user `vcg****`...
11988 | 2024-08-12 10:03:22 | DEBUG | pyload | ACCOUNT FastshareCz: LOAD URL https://www.fastshare.cz/user \| get={} \| post={} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
11989 | 2024-08-12 10:03:22 | DEBUG | pyload | ACCOUNT FastshareCz: LOAD URL https://www.fastshare.cz/sql.php \| get={} \| post={'login': 'vcg****', 'heslo': '**********'} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
11990 | 2024-08-12 10:03:22 | ERROR | pyload | ACCOUNT FastshareCz: Could not login user `vcg****` \| Login handshake has failed

</body>
</html>

File download
<html><body>

12023 | 2024-08-12 10:10:49 | INFO | pyload | Added package test containing 1 links
-- | -- | -- | -- | --
12024 | 2024-08-12 10:10:49 | INFO | pyload | Download starts: 19d9160535b5f51a80197ead67e210c494d67ca05495b7fbee49e43e4a35ecd1886ddb2934104257c554fc14df4c3038a3559cfdaddcdb5959d76724b1cedc6703db7dd1
12025 | 2024-08-12 10:10:49 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
12026 | 2024-08-12 10:10:49 | DEBUG | pyload | ADDON UserAgentSwitcher: Setting maximum redirections to 10
12027 | 2024-08-12 10:10:49 | DEBUG | pyload | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0`
12028 | 2024-08-12 10:10:49 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_preparing`
12029 | 2024-08-12 10:10:49 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1266]: Plugin version: 0.52
12030 | 2024-08-12 10:10:49 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1266]: Plugin status: testing
12031 | 2024-08-12 10:10:49 | WARNING | pyload | DOWNLOADER DefaultPlugin[1266]: Plugin may be unstable
12032 | 2024-08-12 10:10:49 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1266]: Config option `use_premium` not found, use default `True`
12033 | 2024-08-12 10:10:49 | INFO | pyload | DOWNLOADER DefaultPlugin[1266]: Grabbing link info...
12034 | 2024-08-12 10:10:49 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1266]: Link info: {'name': '19d9160535b5f51a80197ead67e210c494d67ca05495b7fbee49e43e4a35ecd1886ddb2934104257c554fc14df4c3038a3559cfdaddcdb5959d76724b1cedc6703db7dd1', 'hash': {}, 'pattern': {}, 'size': 0, 'status': 7, 'url': 'https://fastshare.cloud/19d9160535b5f51a80197ead67e210c494d67ca05495b7fbee49e43e4a35ecd1886ddb2934104257c554fc14df4c3038a3559cfdaddcdb5959d76724b1cedc6703db7dd1'}
12035 | 2024-08-12 10:10:49 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1266]: Previous link info: {}
12036 | 2024-08-12 10:10:49 | INFO | pyload | DOWNLOADER DefaultPlugin[1266]: Link name: 19d9160535b5f51a80197ead67e210c494d67ca05495b7fbee49e43e4a35ecd1886ddb2934104257c554fc14df4c3038a3559cfdaddcdb5959d76724b1cedc6703db7dd1
12037 | 2024-08-12 10:10:49 | INFO | pyload | DOWNLOADER DefaultPlugin[1266]: Link size: N/D
12038 | 2024-08-12 10:10:49 | INFO | pyload | DOWNLOADER DefaultPlugin[1266]: Link status: starting
12039 | 2024-08-12 10:10:49 | INFO | pyload | DOWNLOADER DefaultPlugin[1266]: Processing url: https://fastshare.cloud/19d9160535b5f51a80197ead67e210c494d67ca05495b7fbee49e43e4a35ecd1886ddb2934104257c554fc14df4c3038a3559cfdaddcdb5959d76724b1cedc6703db7dd1
12040 | 2024-08-12 10:10:49 | DEBUG | pyload | DOWNLOADER DefaultPlugin[1266]: DOWNLOAD URL https://fastshare.cloud/19d9160535b5f51a80197ead67e210c494d67ca05495b7fbee49e43e4a35ecd1886ddb2934104257c554fc14df4c3038a3559cfdaddcdb5959d76724b1cedc6703db7dd1 \| get={} \| post={} \| ref=False \| cookies=True \| disposition=True \| resume=None \| chunks=None
12041 | 2024-08-12 10:10:49 | DEBUG | pyload | Chunk 1 download finished
12042 | 2024-08-12 10:10:49 | INFO | pyload | DOWNLOADER DefaultPlugin[1266]: File saved
12043 | 2024-08-12 10:10:49 | INFO | pyload | DOWNLOADER DefaultPlugin[1266]: Checking download...
12044 | 2024-08-12 10:10:49 | INFO | pyload | DOWNLOADER DefaultPlugin[1266]: File is OK
12045 | 2024-08-12 10:10:49 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_processed`
12046 | 2024-08-12 10:10:49 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `package_processed`
12047 | 2024-08-12 10:10:49 | INFO | pyload | Download finished: 19d9160535b5f51a80197ead67e210c494d67ca05495b7fbee49e43e4a35ecd1886ddb2934104257c554fc14df4c3038a3559cfdaddcdb5959d76724b1cedc6703db7dd1
12048 | 2024-08-12 10:10:49 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `download_finished`
12049 | 2024-08-12 10:10:49 | INFO | pyload | Package finished: test
12050 | 2024-08-12 10:10:49 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `package_finished`
12051 | 2024-08-12 10:10:49 | DEBUG | pyload | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
12052 | 2024-08-12 10:10:49 | DEBUG | pyload | All downloads processed

</body>
</html>

### Additional references

System
Python Version: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
OS Platform: posix linux Linux tessa-pyload 5.15.0-118-generic #128-Ubuntu SMP Fri Jul 5 09:28:59 UTC 2024 x86_64

pyLoad
Version: 0.5.0b3.dev85 (upgraded through pip using upgrade-strategy eager)
Installation Folder: /usr/local/lib/python3.10/dist-packages/pyload
Config Folder: /home/pyload-files/Configuration
Language: en 

### Screenshots

![Snímek obrazovky 2024-08-12 100347](https://github.com/user-attachments/assets/8873df52-46fd-4206-ad49-0c17a3ef231e)

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by Tessarai** [comment]
Done, you should have it in your mailbox :)
