### ISSUE TITLE
WebshareCz VIP not working

### ISSUE THREAD

**Issue by skyhawk90** [pyload/pyload#4502]
### Description

VIP login for webshare.cz is not working.  it looks like they changed API:
https://webshare.cz/apidoc/#/login

### Debug log

<html>
<body>

ACCOUNT WebshareCz: Adding user `sky*******`...
--
20968 | 2024-08-19 18:41:53 | DEBUG | pyload | ACCOUNT WebshareCz: Reached login timeout for user `sky****`
20969 | 2024-08-19 18:41:53 | INFO | pyload | ACCOUNT WebshareCz: Login user `sky****`...
20970 | 2024-08-19 18:41:53 | DEBUG | pyload | ACCOUNT WebshareCz: LOAD URL https://webshare.cz/api/salt/ \| get={} \| post={'username_or_email': 'sky****'} \| ref=True \| cookies=True \| just_header=False \| decode=True \| multipart=False \| redirect=True \| req=None
20971 | 2024-08-19 18:41:53 | ERROR | pyload | ACCOUNT WebshareCz: Could not login user `sky****` \| name 'passlib' is not defined
20972 | ? | ? | ? | Traceback (most recent call last):
20973 | ? | ? | ? | File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/base/account.py", line 138, in login
20974 | ? | ? | ? | self.signin(self.user, self.info["login"]["password"], self.info["data"])
20975 | ? | ? | ? | File "/lsiopy/lib/python3.11/site-packages/pyload/plugins/accounts/WebshareCz.py", line 63, in signin
20976 | ? | ? | ? | password = hashlib.sha1(passlib.hash.md5_crypt.encrypt(password, salt=salt).encode()).hexdigest()
20977 | ? | ? | ? | ^^^^^^^
20978 | ? | ? | ? | NameError: name 'passlib' is not defined

</body>
</html>

```

```

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by skyhawk90** [comment]
Account should be in the mail . Thanks.
