### ISSUE TITLE
Can't connect the web interface

### ISSUE THREAD

**Issue by Rebislori** [pyload/pyload#4503]
Hi everyone, I'm sorry to brother you with such a noob question, but i tried to install pyload into a Debian lxc under proxmox: everything seems fine, but i can't connect to the webui with a generic ERR_CONNECTION_RESET

I tried with a script for an Arch lxc found on the internet (reported as working) since i thought i screwed something up during the installation, with same result. 

I'm not sure what information can be useful to sort it out (logs? Lxc configiration?): just tell me and I'll provider them. 

Thanks in advanced for your time.

**Comment by NorfolkXX** [comment]
I had access problems myself yesterday and learned that the default config limits web interface access to localhost.

Change
< ip host : "IP address" = localhost >
to
< ip host : "IP address" = 0.0.0.0 >
in the pyload.cfg

**Comment by Rebislori** [comment]
Thanks, that did the trick!!
