### ISSUE TITLE
pyLoad suddenly downloading very slowly - around 5x slower than via browser?

### ISSUE THREAD

**Issue by victorhooi** [pyload/pyload#4505]
### Description
I have pyLoad running in a Docker container on a Linux ARM64 host.

Previously, pyLoad seemed to be downloading at roughly 10-12 MB/s - which was a good speed, and in line with my internet connection. This was from ExtMatrix links (I have ExtMatrix premium).

However, recently, it seems to be downloading at roughly 1.5-2 MB/s.

Downloading manually via the browser downloads at the normal speed (i.e. close to 10 MB/s).

I did check my settings - and as far as I can tell, the download speed isn't restricted:

![CleanShot 2024-08-31 at 21 22 41@2x](https://github.com/user-attachments/assets/74ad4654-7a2d-4958-9c8e-61901abc4385)

Is there any way to find out why pyLoad is suddenly downloading so slowly?

### Debug log

```

```

**Comment by victorhooi** [comment]
Ok - for some reason, this is specific to ExtMatrix only...

As in, downloading from other hosts will download at the normal speed - however, for some reason, ExtMatrix seems to be artificially capped (when using pyload) at around 500 Kb/s

![CleanShot 2024-10-06 at 21 35 19@2x](https://github.com/user-attachments/assets/5e8c3a22-47b5-480a-bea1-4d94b02a4067)

When I try to download the same ExtMatrix via the browser - it downloads at the normal speed (5-10 Mb/s)

Does anybody have any why this difference might be?

**Comment by GammaC0de** [comment]
Maybe try disabling http/2 (uncomment line 119 in http_request.py)
