### ISSUE TITLE
pyload v0.5 - how to update plugins? minor issues?

### ISSUE THREAD

**Issue by NorfolkXX** [pyload/pyload#4508]
I ran pyload v0.4.20 for ages, but with the loss of python2 after upgrading ubuntu 24.04, i had to switch to pyload v0.5.0. I used "pip install --pre pyload-ng[all]" to install it into /home/username/.local/bin

1) After seeing issue https://github.com/pyload/pyload/issues/4506 resolved in https://github.com/pyload/pyload/commit/e8e315e2e5148b49ab9de768e4642aba522a34ea, I noted my pyload does not download this update. 
How do I get that updated plugin installed automatically? Am I using the wrong branch? Also, it seems like my pyload v0.5.0 is advertising me the release v0.4.20 as new version all the time in the top corner but I understand v0.5.0 would be the way to go nowadays at python3? Or do I miss smth?

Logfile:
[2024-09-04 03:52:53]  DEBUG               pyload  ADDON UpdateManager: LOAD URL https://raw.githubusercontent.com/pyload/updates/master/plugins.txt | get={'v': '0.5.0'} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
[2024-09-04 03:52:53]  INFO                pyload  ADDON UpdateManager: ***  New pyLoad 0.4.20 available  ***
[2024-09-04 03:52:53]  INFO                pyload  ADDON UpdateManager: ***  Get it here: https://github.com/pyload/pyload/releases  ***

2) I run 2 instances of pyload with different settings and I took care to seperate them by having different directories, ports etc.
While accessing only the same installation several times even in multible browser tabs at the same time, I stay logged in and all is fine, but as soon as I switch to the other installation on a different port, I need to login again on both instances. They also cannot be used in browser tabs the same time, as each action will cause a logoff, hence it would not be useable this way.

Do I missunderstand something? 

I was under the impression, v0.5.0 is the "new stable", at least for python 3.

**Comment by GammaC0de** [comment]
In v0.5 UpdateManager is not functional (yet?) so you would have to do `pip install --upgrade https://github.com/pyload/pyload/archive/refs/heads/develop.zip` one in a while.

**Comment by UserX404** [comment]
@GammaC0de 
Thx again for reminder ;-)

**Comment by NorfolkXX** [comment]
Thanks, it did work (ofc)
