### ISSUE TITLE
ExtMatrix plugin no longer working - failed 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by victorhooi** [pyload/pyload#4510]
### Description
When trying to download ExtMatrix links, these all now seem to fail with the error messsage:

```
failed 'NoneType' object has no attribute 'close'
```

### Debug log

```

18953 | 2024-09-06 11:23:05 | WARNING | pyload | Download failed: somefile.html \| 'NoneType' object has no attribute 'close'
-- | -- | -- | -- | --
18954 | 2024-09-06 11:23:05 | INFO | pyload | ADDON UnSkipOnFail: Looking for skipped duplicates of: MIDV-461-1080p.mp4.html (pid:98)
18955 | 2024-09-06 11:23:05 | INFO | pyload | ADDON UnSkipOnFail: No duplicates found


```

**Comment by GammaC0de** [comment]
Sample URL and account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by victorhooi** [comment]
I've sent you an email =) - password is set to the same temporary one as before!

**Comment by GammaC0de** [comment]
I have tried and it works fine for me.
So, maybe its the URL you're trying to download, please send sample problematic URL.
Also, please enable debug mode, restart pyLoad and then retry the download and resend the log here.
