### ISSUE TITLE
Add editable endpoint for AntiCaptcha

### ISSUE THREAD

**Issue by JReming85** [pyload/pyload#4516]
### Description
There are many 3rd party captcha providers that emulate anti-captcha's API.  Would love to have the ability to "change" the endpoint to use those services.

I myself have xevil, and have manually edited the endpoint in the py file, but I am also using the docker version so it would be overwritten on the next pull.

Would love the ability to just define an endpoint if we want to use 3rd party options.

**Comment by GammaC0de** [comment]
Can you give some examples for such changes?

**Comment by GammaC0de** [comment]
Can you give some examples for such changes? otherwise I will have to close this..

**Comment by JReming85** [comment]
Appologies for the delay.

I am talking about the http/://myowndot.com instead of api.anticapcha.com

Currently out at an event now but i can get you some example services that emulate it. 

I personally use XEvil, but CapMonster and GSA breaker also can emulate their API
