### ISSUE TITLE
Filename is determined incorrectly if there is ";" in the filename

### ISSUE THREAD

**Issue by simp16** [pyload/pyload#4524]
### Description
When I am downloading a file in pyload with ";" (%3B encoded) symbol in the download url, I get incorrectly determined filename. For instance, when I am downloading from a url like this:

- https://..../MSG.NYC%3B.Brights.Lights.In.Blues.City.zip

The name in pyload is determined like this:

- MSG.NYC

instead of:

- MSG.NYC;.Brights.Lights.In.Blues.City.zip

### Debug log

```

```

### Additional references

I am using pyload in pyload-ng docker container version linuxserver/pyload-ng:0.5.0

### Screenshots

![image](https://github.com/user-attachments/assets/c0d28ebf-87ce-44f5-bbb6-deb9cffc49a9)

**Comment by GammaC0de** [comment]
URL and OS type please

**Comment by simp16** [comment]
The example URL is https://42-4.download.real-debrid.com/d/ETZKZBEMTLTKK/test%3B123.rar and the OS is synology DSM 7 but it is running in docker as mentioned. When I add the file to pyload I get "test" instead of "test;123.rar"

![image](https://github.com/user-attachments/assets/fc0a5aae-a5ef-406f-a6b7-c53e93c231d8)
