### ISSUE TITLE
PyLoad API uploadContainer/upload_container correct data format

### ISSUE THREAD

**Issue by janbieck** [pyload/pyload#4532]
### Question

I try to upload a dlc file to the API of PyLoad using the requests library.
After starting PyLoad via the terminal, I am using a persistent session to connect to PyLoad and try to use the uploadContainer endpoint. Below is my code:

```
from requests import Session

session = Session()
session.post(url="http://localhost:8000/api/login",
                    data={"username": "pyload",
                               "password": "pyload"})

dlc_file = open("test.dlc", "rb")
dlc_file_content = dlc_file.read()


res = session.post(url="http://localhost:8000/api/uploadContainer",
                             data={"filename": "test.dlc",
                                        "data": dlc_file_content})
```

The response content is the following:

`
{'error': 'malformed node or string on line 1: <ast.Attribute object at 0x0000025763DF62C0>', 
'traceback': 'Traceback (most recent call last):\n  File "C:\\Users\\my_user\\anaconda3\\envs\\my_project\\lib\\site-packages\\pyload\\webui\\app\\blueprints\\api_blueprint.py", line 71, in rpc\n    response = call_api(func, *args, **kwargs)\n  File "C:\\Users\\my_user\\anaconda3\\envs\\my_project\\lib\\site-packages\\pyload\\webui\\app\\blueprints\\api_blueprint.py", line 95, in call_api\n    **{x: literal_eval(y) for x, y in kwargs.items()},\n  File "C:\\Users\\my_user\\anaconda3\\envs\\my_project\\lib\\site-packages\\pyload\\webui\\app\\blueprints\\api_blueprint.py", line 95, in <dictcomp>\n    **{x: literal_eval(y) for x, y in kwargs.items()},\n  File "C:\\Users\\my_user\\anaconda3\\envs\\my_project\\lib\\ast.py", line 110, in literal_eval\n    return _convert(node_or_string)\n  File "C:\\Users\\my_user\\anaconda3\\envs\\my_project\\lib\\ast.py", line 109, in _convert\n    return _convert_signed_num(node)\n  File "C:\\Users\\my_user\\anaconda3\\envs\\my_project\\lib\\ast.py", line 83, in _convert_signed_num\n    return _convert_num(node)\n  File "C:\\Users\\my_user\\anaconda3\\envs\\my_project\\lib\\ast.py", line 74, in _convert_num\n    _raise_malformed_node(node)\n  File "C:\\Users\\my_user\\anaconda3\\envs\\my_project\\lib\\ast.py", line 71, in _raise_malformed_node\n    raise ValueError(msg + f\': {node!r}\')\nValueError: malformed node or string on line 1: <ast.Attribute object at 0x0000025763DF62C0>\n'}
`

Can someone tell me how to correctly format the data of the dlc file before sending it to the uploadContainer API of PyLoad?
It would be very helpful to see a working example.

**Comment by GammaC0de** [comment]
```python
from requests import Session

session = Session()
session.post(
    url="http://localhost:8000/api/login",
    data={
        "username": "pyload",
        "password": "pyload"
    }
)

dlc_file = open("test.dlc", "r")
dlc_file_content = dlc_file.read()


res = session.post(
    url="http://localhost:8000/api/uploadContainer",
    data={
        'filename': '"test.dlc"',
        'data': f'b"{dlc_file_content}"'
    }
)
```
