### ISSUE TITLE
pipx install failed with error failed building wheel for msgspec

### ISSUE THREAD

**Issue by serious96** [pyload/pyload#4534]
[deck@bazzite ~]$ pipx install --pip-args=--pre pyload-ng[all]
Fatal error from pip prevented installation. Full pip output in file:
    /home/deck/.local/state/pipx/log/cmd_2024-12-24_18.02.17_pip_errors.log

pip failed to build package:
    msgspec

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    msgspec/_core.c:500:13: error: implicit declaration of function ‘_PyUnicode_EQ’; did you mean ‘PyUnicode_New’? [-Wimplicit-function-declaration]
    msgspec/_core.c:4452:12: error: implicit declaration of function ‘_PySet_NextEntry’ [-Wimplicit-function-declaration]
    msgspec/_core.c:11254:15: error: too few arguments to function ‘_PyLong_AsByteArray’
    error: command '/usr/bin/gcc' failed with exit code 1
    ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (msgspec)

Error installing pyload-ng from spec 'pyload-ng[all]'.
[deck@bazzite ~]$ 

here is from the error log:

Building wheels for collected packages: msgspec
  Building wheel for msgspec (pyproject.toml): started
  Building wheel for msgspec (pyproject.toml): finished with status 'error'
Failed to build msgspec

PIP STDERR
----------
  error: subprocess-exited-with-error
  
  × Building wheel for msgspec (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/__init__.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/_json_schema.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/_utils.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/_version.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/inspect.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/json.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/msgpack.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/structs.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/toml.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/yaml.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/__init__.pyi -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/json.pyi -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/msgpack.pyi -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/structs.pyi -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/py.typed -> build/lib.linux-x86_64-cpython-313/msgspec
      UPDATING build/lib.linux-x86_64-cpython-313/msgspec/_version.py
      set build/lib.linux-x86_64-cpython-313/msgspec/_version.py to '0.18.6'
      running build_ext
      building 'msgspec._core' extension
      creating build/temp.linux-x86_64-cpython-313/msgspec
      gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -fPIC -I/home/deck/.local/share/pipx/venvs/pyload-ng/include -I/usr/include/python3.13 -c msgspec/_core.c -o build/temp.linux-x86_64-cpython-313/msgspec/_core.o
      msgspec/_core.c: In function ‘find_keyword’:
      msgspec/_core.c:500:13: error: implicit declaration of function ‘_PyUnicode_EQ’; did you mean ‘PyUnicode_New’? [-Wimplicit-function-declaration]
        500 |         if (_PyUnicode_EQ(kwname, key)) {
            |             ^~~~~~~~~~~~~
            |             PyUnicode_New
      msgspec/_core.c: In function ‘typenode_collect_convert_structs’:
      msgspec/_core.c:4452:12: error: implicit declaration of function ‘_PySet_NextEntry’ [-Wimplicit-function-declaration]
       4452 |     while (_PySet_NextEntry(state->structs_set, &set_pos, &set_item, &set_hash)) {
            |            ^~~~~~~~~~~~~~~~
      msgspec/_core.c: In function ‘ms_uuid_to_16_bytes’:
      msgspec/_core.c:11254:15: error: too few arguments to function ‘_PyLong_AsByteArray’
      11254 |     int out = _PyLong_AsByteArray((PyLongObject *)int128, buf, 16, 0, 0);
            |               ^~~~~~~~~~~~~~~~~~~
      In file included from /usr/include/python3.13/longobject.h:107,
                       from /usr/include/python3.13/Python.h:81,
                       from msgspec/_core.c:9:
      /usr/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for msgspec
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (msgspec)

**Comment by GammaC0de** [comment]
1. This has nothing to do with pyLoad (this is and issue msgspec and python 3.13 - see https://github.com/jcrist/msgspec/issues/698)
2. python 3.13 is not tested with pyLoad yet, there may be more issues..
