### ISSUE TITLE
Setup procedure

### ISSUE THREAD

**Issue by cimnine** [pyload/pyload#48]
While trying to set up a fresh version of PyLoad (from current `master`), `pyload.py` crashes.

Here's the full trace of running `python pyload.py -s --changedir --configdir /etc/pyload/`.

    Choose your Language / Wähle deine Sprache ([en], de, fr, it, es, nl, sv, ru, pl, cs, sr, pt_BR): 
    
    Would you like to configure pyLoad via Webinterface?
    You need a Browser and a connection to this PC for it.
    Url would be: http://hostname:8000/
    Start initial webinterface for configuration? ([y]/n): n
    Welcome to the pyLoad Configuration Assistent.
    It will check your system and make a basic setup in order to run pyLoad.
    
    The value in brackets [] always is the default value,
    in case you don't want to change it or you are unsure what to choose, just hit enter.
    Don't forget: You can always rerun this assistent with --setup or -s parameter, when you start pyLoadCore.
    If you have any problems with this assistent hit STRG-C,
    to abort and don't let him start with pyLoadCore automatically anymore.
    
    When you are ready for system check, hit enter.
    
    Traceback (most recent call last):
      File "pyload.py", line 664, in <module>
        main()
      File "pyload.py", line 653, in main
        pyload_core = Core()
      File "pyload.py", line 132, in __init__
        s.start()
      File "/opt/pyload/module/Setup.py", line 79, in start
        self.start_cli()
      File "/opt/pyload/module/Setup.py", line 102, in start_cli
        if len(avail) < 5:
    NameError: global name 'avail' is not defined

**Comment by vuolter** [comment]
Fixed in 0.4.10 .
No Setup procedure in 0.5.0 .
