### ISSUE TITLE
Mega.co.nz Folder Decrypter

### ISSUE THREAD

**Issue by ItachiSan** [pyload/pyload#481]
As title, would it be possible to implement a mega.co.nz folder decrypter?
I sincerly am not an expert in this field of programming, if I'll be able, I'll write it to you...
But as for now, can someone do it? Thanks! :)

**Comment by comerpapas** [comment]
@Pieter-F @vuolter @gonzalosr @miracle2k @ItachiSan hi fellows, any help on how to reverse the decrypt (get  the folder id of the file)...Is it posible to make a code for that :+1:  ???
i need to download the files directly from the folder
Thanks!

**Comment by GammaC0de** [comment]
@comerpapas Sample URL please.

**Comment by vuolter** [comment]
@GammaC0de mega:///#F!vcty1BLI!FhP2NETG1P7A7Y5bdMhm1g

**Comment by comerpapas** [comment]
@GammaC0de folder url from @vuolter :
https://mega.co.nz/#F!vcty1BLI!FhP2NETG1P7A7Y5bdMhm1g

First file from that folder decrypted with megadownloader:
http://mega.co.nz/#N!WJ8CURKR!W1nF3mh5d0TV75-hdB3r3eoRGSUcJ-
9FJ_C_P25xxzc=###n=vcty1BLI@vuolter 

I want to do the inverse of that..

Here the program.exe that i use to get url from the files in the folder: Megadownloader
https://mega.nz/#!5EYj1TBJ!Wv4E07NlSHP8-r1lD7FcaGJ361wWgL3ppeL4y3Bds_0
