### ISSUE TITLE
Log auth events to logfile

### ISSUE THREAD

**Issue by alesnav** [pyload/pyload#500]
Hello,

I've looked for a method to use fail2ban with a filter for pyload. This way, when someone fails login more than X times, his IP will be banned.

My problem is that pyload does not log those events of web module (login, logout, auth failed,...). This will be a very little improvement, but I think it is neccesary.

As I am not familiar with pyload code, I don't know where would be the best location to do this. I see that it will be possible to do it in many ways...

¿Would it be possible to add this enhacement?

Thanks!

**Comment by qwrty-ftw** [comment]
Hello, 

any news about this ?
