### ISSUE TITLE
Datoid.cz

### ISSUE THREAD

**Issue by dvbmanCZ** [pyload/pyload#665]
[hoster] Datoid.cz
Hello my pyLoad friends, thanx for making this program and your Support, at once :-D

Can you make hoster for Datoid.cz - mainly for premium ?

Thanx, DvB.

**Comment by Billysk** [comment]
http://datoid.cz/McPNxG/stvanec-2014-cz-dabing-avi-tatarlopata-avi

**Comment by Billysk** [comment]
Can you make hoster for Datoid.cz - mainly for premium ?
Still not work?
Thanx, DvB.

**Comment by Buritos81** [comment]
Adding me to the request for Datoid.cz.
Please. Thanx.

**Comment by GammaC0de** [comment]
Sample URL please

**Comment by Buritos81** [comment]
https://datoid.cz/4z1pHY/pata-vlna-2016-cz-titulky-avi

**Comment by GammaC0de** [comment]
What is this??

![datoid cz_-_2016-05-16_22 18 51](https://cloud.githubusercontent.com/assets/11036551/15301004/367baa64-1bb4-11e6-8734-9161672e46b2.png)

**Comment by Buritos81** [comment]
This is login for registered user.

**Comment by GammaC0de** [comment]
This is what I get when going to https://datoid.cz/4z1pHY/pata-vlna-2016-cz-titulky-avi.
Where is free user?!

**Comment by Buritos81** [comment]
Here  is sreenshots ,  where click  to download free user https://goo.gl/photos/Bbx5AMXZ7k2CdcBz9

**Comment by GammaC0de** [comment]
I dont have this, i get the only the login page

Maybe it is locked to CZ users only?

**Comment by Buritos81** [comment]
And when you enter petr-b1@seznam.cz 987654321

**Comment by GammaC0de** [comment]
ok, now it works.
Is this premium only hoster?

**Comment by Buritos81** [comment]
I think not. It should go without registration, as sreenshots.

**Comment by GammaC0de** [comment]
It first asks for login and the it shows the page as your screenshot..

**Comment by GammaC0de** [comment]
**Všechny free sloty jsou obsazeny**

Another URL please.

**Comment by Buritos81** [comment]
Free users are limited number of slots for downloading.

**Comment by GammaC0de** [comment]
@Buritos81 How limited? one download per hour? per day? or maybe other limit?
I was not downloading other files and tried to download my own upload so I'm sure its not expired..

Please explain

**Comment by Buritos81** [comment]
There is only this:
Premium account, you can download full with all the advantages.
1) Unlimited download speed
2) Unlimited number of simultaneous downloads
3) Establishing a broken downloads
4) Support for download Clients

**Comment by GammaC0de** [comment]
But what about free users?

Now I cannot download anything as a free user..

**Comment by GammaC0de** [comment]
Free download not verified.
