### ISSUE TITLE
[MultiHoster] superload.cz

### ISSUE THREAD

**Issue by sergix-zz** [pyload/pyload#672]
Hello,

I would like to ask you, if you can take a look on multihoster server superload.cz Its a great service which deserves its own plugin:)
url: http://www.superload.cz
sample link: http://www.superload.cz/dl/ezA4rVIH-rozpal-to-sefe-03-avi
Tell me pls, if you need something else to test

Thx a lot!

**Comment by GammaC0de** [comment]
Very old thread, If someone really want support for this multi-hoster and have an account to provide, please open a new issue.

Closing.
