### ISSUE TITLE
pyload stops downloading after one file via xdcc

### ISSUE THREAD

**Issue by nathschwarz** [pyload/pyload#675]
XDCC stops downloading files after one is completed - pyload still responds, I'm still able to add and delete packages (with exception of the package in which the last xdcc-file is), yadda yadda yadda, but it doesn't download any other one. Neither previously nor afterwards added files. However it finishes other running downloads and the xdcc-file was downloaded correctly (marked as finished in Queue-tab and works properly). Not downloaded files are still marked as queue.

```
06.07.2014 05:29:54 INFO      Added package SAO containing 1 links
06.07.2014 05:29:56 INFO      Download starts: xdcc://irc.rizon.net/#HorribleSubs/CR-ARUTHA|NL-720p/4059
06.07.2014 05:29:59 DEBUG     Xdcc: XDCC: Sending CTCP VERSION.
06.07.2014 05:30:02 INFO      Xdcc: XDCC: Downloading "[HorribleSubs] Sword Art Online - 01 [720p].mkv" from 95.211.186.210:54330
06.07.2014 05:31:58 INFO      Added package SAO containing 25 links
06.07.2014 05:34:13 DEBUG     Xdcc: Xdcc: Download of /media/odroid/Mijierna/Download/SAO/"[HorribleSubs] Sword Art Online - 01 [720p].mkv" finished.
06.07.2014 05:34:13 INFO      Download finished: "[HorribleSubs] Sword Art Online - 01 [720p].mkv"
06.07.2014 05:34:13 INFO      Package finished: SAO
```

At first I thought that the procedure of the xdcc-download hasn't ended completely and that something is still pending, but the package itself is finished so... no idea.
To continue downloading a restart of pyload is needed.

Edit: Almost forgot a test link:
xdcc://irc.rizon.net/#HorribleSubs/CR-ARUTHA|NL-720p/4061

**Comment by Ceder001** [comment]
I have the same problem. 
When the download ends, the ThreadManager tries to assign a new job but it gets stuck at `self.plugin = self.pluginclass(self)` of initPlugin function in PyFile.py.
In my case, pluginclass variable is set to `set([<class 'userplugins.hoster.Xdcc.Xdcc'>])`

**Comment by Kagenoshin** [comment]
I'm trying to figure out the problem without any success :(
But I keep searching...

**Comment by GammaC0de** [comment]
The cause of this problem is described in https://github.com/pyload/pyload/issues/2583.
PR #2615 fixes this.

**Comment by ingjcgonzalez** [comment]
Hello, how do I do the configuration of th xdcc plugin? And how add the package to download?
Thax

**Comment by GammaC0de** [comment]
@ingjcgonzalez xdcc support has some issues and bugs, PR #2615 fixes those issues so you have to apply #2615 manually.

Configuration is done via configuration->plugins->xdcc

You would add a package like any other packages but the URL would be xdcc://SERVER:PORT/#CHANNEL/BOT_NAME/#PACK_NUM

**Comment by ingjcgonzalez** [comment]
@GammaC0de

**Comment by GammaC0de** [comment]
Yes?

**Comment by ingjcgonzalez** [comment]
@GammaC0de I wrote in the post above. Sorry but I did't finish to write and did the post

**Comment by GammaC0de** [comment]
@ingjcgonzalez I'm afraid that XDCC.py was overwritten by `UpdateManager`.
You should restore XDCC.py to the one from #2615 and also edit the version from "0.42" to "0.43" so it will not be overwritten again.

I did this and it worked with the above URL.

**Comment by ingjcgonzalez** [comment]
I did it, edit the line version to "0.43". Still the same. I fix the plugins according to #300. Should I edit RequestFactory.py file according to #2583 ?

**Comment by GammaC0de** [comment]
Get the files from here https://gist.github.com/GammaC0de/e26c0465608090873e9fb641bc26fcce/archive/884c925636dbd72c099fcaed2a0de21347a49ceb.zip (don't forget to change the version)

**Comment by ingjcgonzalez** [comment]
@GammaC0de u'r a damn genious! Now thanx to u, I've my Mega account and XDCC to download!
