### ISSUE TITLE
NowDownload Plugin

### ISSUE THREAD

**Issue by ghost** [pyload/pyload#707]
Plugin is out of Date.
Example Link:
http://www.nowdownload.sx/dl/b9rop8f1bgjgz
Could you fix it?

**Comment by ilteoood** [comment]
What about this issue?
The problem is still here!

**Comment by Velociraptor85** [comment]
This domain does not work anymore

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/d75e598dcc73ab9cff28e1020d2f515266bb0ff7
