### ISSUE TITLE
high cpu load, thread loop

### ISSUE THREAD

**Issue by twoDarkMessiah** [pyload/pyload#724]
I several times noticed, that pyLoad has a very high cpu load in Idle mode. 
This occurs only after some time.

pyLoad Version:
pyload-win-v0.4.9

Hardware:
CPU: I7 4770k 8x3,64 GHz

![pyload](https://cloud.githubusercontent.com/assets/5120677/4111322/d3830a32-3204-11e4-9d5d-260f758907f8.jpg)

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/354ecbc78898efb4a31a7272e5ea1f5e00a53327
