### ISSUE TITLE
[Hoster] Turbobit.net still doesn't work after update

### ISSUE THREAD

**Issue by geminiarek** [pyload/pyload#764]
it still doesn't work for me 

29.09.2014 12:23:56 WARNING TurbobitNet: Could not login with account ************_**@.__| Wrong Password 
29.09.2014 12:23:56 DEBUG TurbobitNet: Get Account Info for *_**********_**@._\* 
29.09.2014 12:23:56 DEBUG TurbobitNet: Account Info: {'validuntil': -1, 'premium': False, 'trafficleft': -1}

few minutes later

29.09.2014 12:54:05 WARNING TurbobitNet: Could not login with account ************_**@._\* | (56, 'Recv failure: Connection reset by peer') 
29.09.2014 12:54:05 DEBUG TurbobitNet: Get Account Info for ************_**@._\* 
29.09.2014 12:54:06 DEBUG TurbobitNet: Account Info: {'validuntil': -1, 'premium': False, 'trafficleft': -1}

On their website account working without any problems.

What can I do ?

**Comment by palla89** [comment]
any news on this?

**Comment by vuolter** [comment]
@palla89 No progress
@mike321 I'm unable to remove it from http://pyload.org/hoster

**Comment by Velociraptor85** [comment]
uses also recaptcha for free download tested it with random file I uploaded ... does not work @GammaC0de could you take a peak ... will probrably work very similarly like shareonline
I took a peak and first one hast to href to /download/free/hash in the td class "no-border download button" or a id "nopay-btn" followed by the google recaptcha iframe ... but I guess you will work that out on your own :)
