### ISSUE TITLE
YouTube https issues -convert to http (especially for Playlists)

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#779]
Hey. Please add support for https or at least add an converter from https to http ..
Because pyLoad has this brilliant function, that YouTube-Playlists are working - which is a very rare feature out there. But it's just not working, because of the https problem. Because even if i change the https to http in the playlist url, pyload automatically takes the https link for every video. Which makes it totally useless.

**Comment by vuolter** [comment]
1) See: http://askubuntu.com/questions/186847/error-gnutls-handshake-falied-when-connecting-to-https-servers
2) Debug log please.

**Comment by GammaC0de** [comment]
Works, closing.
