### ISSUE TITLE
Google Drive support

### ISSUE THREAD

**Issue by vuolter** [pyload/pyload#792]

**Comment by timofonic** [comment]
Some relevant links for reference:

https://pypi.python.org/pypi/PyDrive
https://github.com/googledrive/PyDrive
https://github.com/goranpejovic/drive-uploader  
https://github.com/google/google-api-python-client  
https://github.com/google/gdata-python-client
https://github.com/google/oauth2client  
https://pypi.python.org/pypi/googleDriveAccess
https://github.com/HatsuneMiku/googleDriveAccess
https://github.com/pinoyyid/ngDrive
https://github.com/pffy/googledrive-reference/
https://github.com/hnakamur/gae-oauth2client-spreadsheet
https://github.com/yumaokao/gdrv
https://github.com/rohitdureja/Terminal-Drive


https://developers.google.com/drive/v2/reference/
https://developers.google.com/api-client-library/python/
https://developers.google.com/google-apps/spreadsheets/?hl=ja

Syncers

Python
https://github.com/hschauhan/gosync


Java
https://github.com/stepank/jdbox 
https://github.com/murzic4/GoogleDrive

Other
https://github.com/astrada/google-drive-ocamlfuse (Ocaml)


Some apps

https://github.com/mkaminsky11/codeyourcloud
https://github.com/the-horn/Horn
