### ISSUE TITLE
Inconsistent Download Location with FlexGet

### ISSUE THREAD

**Issue by sasese** [pyload/pyload#808]
Given [this config.yml](http://pastebin.com/3Af4kQZr), pyLoad will alternately download files to their specified folders (for example: X:\Intended\Folder) or to a number of different folders in pyLoads default download folder (for example D:\default pyload download folder\Package Name, or D:\default pyload download folder\XIntendedFolder). When the package is inspected in pyLoad's webui, it shows the correct folder, and if the packages is restarted, it will download to the correct folder.
The occurrence of this issue is unpredictable: the same config.yml run back to back several times results in different outcomes.

Unfortunately neither FlexGet's trace log nor pyLoad's debug logs indicate the or any related problem, but as pyLoad does record the intended download folder correctly it would seem that the error is in pyLoad.

Semantically the folder location seems correct, as far as FlexGet goes. A number of variations have been tried, including forward slashing the path, without avail.

The most curious part of the entire problem is its intermittent nature: sometimes the download folder is correct, sometimes it is not. Sometimes, correct and incorrect folders appear in packages added in the same task, and even in the same package. Any of the three download locations defined in the config.yml, linked to above, may produce the error.

pyLoad 0.49
Windows (7, 32bit, Ultimate)

**Comment by snickers2k** [comment]
Hey. Oh boy, it's been a long time. I absolutely had no free time in the past months, so i'm really sorry.
But i'm still struggling with this issue.

Has your fix already been merged ? And if the crypter.py is still the problem, and you haven't any experience with it, maybe @vuolter can take a look?

thanks guys

**Comment by vuolter** [comment]
My 0.4.10 is currently broken: first I need to fix it, update plugins to lastest in stable, then I can examine that pr. It's a long story...

**Comment by snickers2k** [comment]
i really don't want to bother.. but maybe any news on this?^^
