### ISSUE TITLE
Thriftbackend does not bind randomly

### ISSUE THREAD

**Issue by pscheit** [pyload/pyload#815]
Hi there,

thank you so much for pyload. I really like the thrift api and It's working really well.
One thing that I noticed it, that sometimes the thrift backend gets not bound. I does not respond to any requests I made (cannot read/write from socket).
When I "turn it on and off again" ;) its often bound correctly.

my config is like this:

```
version: 1 

remote - "Remote":
    bool nolocalauth : "No authentication on local connections" = False
    bool activated : "Activated" = True
    int port : "Port" = 7227
    ip listenaddr : "Adress" = 127.0.0.1
```

any ideas? Do you need a log?
I'm running the latest version pyload on windows 7 professional 32 bit

**Comment by pscheit** [comment]
i'm 100% sure that this happens if the update manager is restarting pyload

**Comment by vuolter** [comment]
@pscheit Key info! I will investigate about it.
