### ISSUE TITLE
pyLoad does not respect folder- and packagename for crypted-links (given by API)

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#829]
Hey.
I use Flexget to add links via pyload-API.
And first everything works great: The (customized-)folder and packagename is taken by pyload.
But then, pyload decrypts the package - and create a new package with the "original" packagename and folder. And doesn't take the customized folder/packagename to the newly created package.
Which makes it impossible to handle these files automatically (filebot for example), after a successful download..

**Comment by mbosner** [comment]
I tested the serienjunkies.org issue today with 8d1231901b3ccccdc2d3d2593c0baf4ff7be4220 and i get this:
02.01.2015 18:21:16 ERROR     Error importing SerienjunkiesOrg: No module named SerienjunkiesOrg
02.01.2015 18:21:16 CRITICAL  'NoneType' object has no attribute 'SerienjunkiesOrg'
Traceback (most recent call last):
  File "/data/media/bin/pyload-versions/stable/module/ThreadManager.py", line 276, in assignJob
    job.initPlugin()
  File "/data/media/bin/pyload-versions/stable/module/utils.py", line 165, in new
    return func(*args)
  File "/data/media/bin/pyload-versions/stable/module/PyFile.py", line 102, in initPlugin
    self.pluginclass = getattr(self.pluginmodule, self.m.core.pluginManager.getPluginName(self.pluginname))
AttributeError: 'NoneType' object has no attribute 'SerienjunkiesOrg'

"zip" version does work but has other issues.

**Comment by seppi91** [comment]
Do I have to manually merge this into my local files or is it merged in the stable branch? Can't see any changes on the crypter.py file at "stable","master"  or "1.0.0" branch.

**Comment by vuolter** [comment]
@seppi91 See: https://github.com/vuolter/pyload

**Comment by Leonderi** [comment]
Is there any chance to get this to work?

i'm also trying to add a package with flexget. The used Crypter is Filecryptcc, which seems to pick the DLC. The DLC plugin seems to generate a new package with an new name.

I really would like, if the package name given by flexget would stay.

**Comment by j4m** [comment]
@GammaC0de do you see any chance to fix this behaviour?

**Comment by GammaC0de** [comment]
@j4m Have you tried https://github.com/pyload/pyload/pull/866?
