### ISSUE TITLE
DlFreeFr.py update

### ISSUE THREAD

**Issue by FeverRay** [pyload/pyload#847]
Hi,

Any help appreciated to update this plugin 

sample link :
http://dl.free.fr/b2ANA3gPp

Log :
1151	04.11.2014 12:37:24	INFO	Download starts: 
1152	04.11.2014 12:37:25	WARNING	Download failed:  | Invalid AdYouLike challenge
1153	04.11.2014 12:37:25	INFO	UnSkipOnFail: look for skipped duplicates

**Comment by lazlev** [comment]
The plugin should work again with the latest commits.
