### ISSUE TITLE
FileCrypt.cc

### ISSUE THREAD

**Issue by vuolter** [pyload/pyload#872]
Forum: http://forum.pyload.org/viewtopic.php?f=13&t=3750

**Comment by Ghoststage** [comment]
Is it maybe possible to fix the script ? Unfortunately, there is no more. Error message is no captchas found :(
----------------/''''''''''''''''''\---------------
Ist es vieleicht möglich das Script zu fixen? Es geht leider nicht mehr Fehler meldung lautet No Captchas found :(

http://filecrypt.cc/Container/797745D650.html
![filecryptcc](https://cloud.githubusercontent.com/assets/10416328/5628496/3dc53b48-95a8-11e4-91e4-49eca4192f4e.PNG)

**Comment by zapp-brannigan** [comment]
@Ghoststage
See https://github.com/pyload/pyload/issues/976
I don't know how to deal with that type of captcha :(

**Comment by Ghoststage** [comment]
:(( Ok Thx

2015-01-06 14:25 GMT+01:00 zapp-brannigan <notifications@github.com>:
