### ISSUE TITLE
Fshare.vn doesn't work no more

### ISSUE THREAD

**Issue by sobny** [pyload/pyload#932]
fshare.vn just updated to new version so plugin not working. Can you solve the problem? Please contact me if you need premium account to fix problem.

Best Regards

**Comment by sobny** [comment]
Hi @vuolter, is there any good news of this issue?

**Comment by vuolter** [comment]
I rewrote the account plugin a week ago, but was not working well and currently I'm busy with dlc, extractor and updatemanage. I'm sorry for waiting you so much time, I'll recheck it soon as possible. :(

**Comment by sobny** [comment]
So is there any chance to make fshare.vn plugins? @vuolter
