### ISSUE TITLE
UpdateManager can't restart pyload

### ISSUE THREAD

**Issue by vuolter** [pyload/pyload#935]
Forum: http://forum.pyload.org/viewtopic.php?f=12&t=3791

**Comment by Killer1337** [comment]
Another thing I noticed is that I can't change the option "Don't check for updates in debug mode:" in the Update Manager. If I set it to "off", it will be on again after a restart of pyload. And having had pyload running in debug mode for the past weeks didn't bring any updates.

**Comment by vuolter** [comment]
Oookay: https://github.com/pyload/pyload/issues/1001
