### ISSUE TITLE
no premium at share-online.biz

### ISSUE THREAD

**Issue by R3alflash** [pyload/pyload#973]
Hello. 

I get the same failure since few days.

1080	24.12.2014 21:29:51	DEBUG	ShareonlineBiz: Account Info: {'premium': False, 'validuntil': -1, 'trafficleft': -1} 

i have reinstall it and i have update the hoster and account file from here, but nothing resolved it.

Can u help me?

**Comment by R3alflash** [comment]
any news?

**Comment by vuolter** [comment]
Working on...

**Comment by R3alflash** [comment]
great new Info! I have try your latest account fix and it Works :+1:
