### ISSUE TITLE
FilecryptCc.py "no captcha found"

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#976]
25.12.2014 10:49:21 INFO      Decrypting starts: http://filecrypt.cc/Container/CD088C4FE9.html
25.12.2014 10:49:21 DEBUG     FilecryptCc: No captcha found

**Comment by zapp-brannigan** [comment]
@vuolter 
Do you have any clue how to solve this captchas?
https://cloud.githubusercontent.com/assets/10416328/5628496/3dc53b48-95a8-11e4-91e4-49eca4192f4e.PNG

Jdownloader2 is able to handle it. I've looked into JD-code but i don't understand it :S

**Comment by Ghoststage** [comment]
Ok THX :((

2015-01-06 14:27 GMT+01:00 zapp-brannigan <notifications@github.com>:

**Comment by Gutz-Pilz** [comment]
http://stackoverflow.com/questions/8380972/recaptcha-in-django-without-forms
http://stackoverflow.com/questions/1440239/how-to-use-python-plugin-recaptcha-client-for-validation
^^maybe this helps??

**Comment by Ghoststage** [comment]
Unfortunately, I do not understand :(

Leider verstehe ich das nicht :(

**Comment by zapp-brannigan** [comment]
Some "good" news:
Today i've inspected JDownloader2 code again and looked at the http requests which are made by JD. I've borrowed some code for our plugin, but unfortunately it still doesn't work.
But as of today JD2's support for recaptchaV2 is also broken ;)

**Comment by vuolter** [comment]
50% done, see recaptcha in captchaservice. ;)

**Comment by zapp-brannigan** [comment]
@vuolter 
I have a working recaptchaV2 solution. How is the progress on your side? Shall i open a PR for Captchaservice.py or are you almost done?

**Comment by vuolter** [comment]
Mi side is out-of-order! XD
Your PR will be welcome. ;)

**Comment by Ghoststage** [comment]
VERY BIG THX
