### ISSUE TITLE
Error with premium.to

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#979]
I hav an error to download with premium.to.
By every Download, i get the error with tra not definied
i have uploaded this error in the forum
http://forum.pyload.org/viewtopic.php?f=10&t=3842

**Comment by dascripta** [comment]
Thx for your hint, but unfortunately i am using payload via a NAS System, so i got no possibilities to control the used Version.

i am looking forward for the Fix.

**Comment by Mister-XY** [comment]
I'm using also via nas.

**Comment by vuolter** [comment]
Working on...

**Comment by Mister-XY** [comment]
ok

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/e0cba81ae8d59ee24e1cd1f1cf1697c5e61118ce

**Comment by Mister-XY** [comment]
The error is not away, is the same. no file were downloaded, only the html code. And now, the file name ist not the rar file instead before.now is it 29qvalta instead of i.love.pyload.rar
597	02.01.2015 04:12:17	DEBUG	ExternalScripts: Executing | /e-data/df880230-cd6e-44c8-a5d6-f12cea45e9dc/ffproot/ffp/opt/pyLoad/etc/pyload/scripts/package_finished/package_finished.sh | scripts/package_finished/package_finished.sh x /i-data/md0/Download/x 10
596	02.01.2015 04:12:17	INFO	Package finished: x
595	02.01.2015 04:12:17	INFO	Download finished: 29qvalta
594	02.01.2015 04:12:17	DEBUG	Download Check triggered
593	02.01.2015 04:12:17	DEBUG	Download Check triggered
592	02.01.2015 04:12:16	DEBUG	PremiumTo: File name: 29qvalta | File size: Unknown
591	02.01.2015 04:12:16	DEBUG	PremiumTo: File info (AFTER): {'status': 3, 'url': u'http://ul.to/29qvalta', 'name': u'29qvalta', 'size': 0}
590	02.01.2015 04:12:16	DEBUG	PremiumTo: File info (BEFORE): {}
589	02.01.2015 04:12:16	INFO	PremiumTo: Direct download link detected
588	02.01.2015 04:12:16	DEBUG	PremiumTo: Looking for direct download link...
587	02.01.2015 04:12:16	INFO	Download starts: 29qvalta
586	02.01.2015 04:11:54	DEBUG	PremiumTo: Regexp: https?://(?:www\.)?premium\.to/.+|.*(depfile\.com|dizzcloud\.com|filemonkey\.in|nitroflare\.com).*
585	02.01.2015 04:11:54	DEBUG	PremiumTo: New hosters: depfile.com, dizzcloud.com, filemonkey.in, nitroflare.com
584	02.01.2015 04:11:54	DEBUG	PremiumTo: Overwritten hosters: BitshareCom, ExtabitCom, FileParadoxIn, FilefactoryCom, FilepostCom, FilerNet, FiredriveCom, FourSharedCom, FreakshareCom, Keep2shareCC, LetitbitNet, NetloadIn, OboomCom, OneFichierCom, RapidgatorNet, RapidshareCom, SecureUploadEu, ShareonlineBiz, TurbobitNet, UploadableCh, UploadedTo, UptoboxCom
583	02.01.2015 04:11:53	DEBUG	Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
582	02.01.2015 04:11:53	DEBUG	Redirected import module.plugins.internal.MultiHoster -> userplugins.internal.MultiHoster
581	02.01.2015 04:11:53	DEBUG	Redirected import module.plugins.hoster.PremiumTo -> userplugins.hoster.PremiumTo
580	02.01.2015 04:11:53	INFO	PremiumTo: Reloading supported hoster list
579	02.01.2015 04:11:51	INFO	pyLoad is up and running
578	02.01.2015 04:11:51	DEBUG	XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?([\w.^_]+(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:user|folder)s?/\w+
577	02.01.2015 04:11:51	INFO	XFileSharingPro: Handling any crypter I can!
576	02.01.2015 04:11:51	DEBUG	XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?([\w.^_]+(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
575	02.01.2015 04:11:51	INFO	XFileSharingPro: Handling any hoster I can!
574	02.01.2015 04:11:51	INFO	Activating Plugins...
573	02.01.2015 04:11:51	DEBUG	PremiumTo: Account Info: {'validuntil': -1, 'premium': True, 'trafficleft': 558002904.13476562}
572	02.01.2015 04:11:51	DEBUG	PremiumTo: Get Account Info for Mister XY
571	02.01.2015 04:11:51	DEBUG	Redirected import module.plugins.accounts.PremiumTo -> userplugins.accounts.PremiumTo
570	02.01.2015 04:11:51	INFO	Activating Accounts...
569	02.01.2015 04:11:51	INFO	Free space: 1.07 TiB
568	02.01.2015 04:11:51	INFO	Starting threaded webserver: 0.0.0.0:7272
567	02.01.2015 04:11:50	INFO	Starte ThriftBackend: 0.0.0.0:7227
566	02.01.2015 04:11:50	INFO	Downloadzeit: True
565	02.01.2015 04:11:50	INFO	Deaktivierte Plugins: AlldebridCom, BypassCaptcha, Captcha9kw, CaptchaBrotherhood, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, ExpertDecoders, ExtractArchive, FastixRu, FreeWayMe, HotFolder, IRCInterface, ImageTyperz, LinkdecrypterCom, LinksnappyCom, MegaDebridEu, MergeFiles, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumizeMe, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartFailed, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, UnrestrictLi, WindowsPhoneToastNotify, XMPPInterface, ZeveraCom
564	02.01.2015 04:11:50	INFO	Aktivierte Plugins: Checksum, ClickAndLoad, ExternalScripts, PremiumTo, UnSkipOnFail, UpdateManager, XFileSharingPro
563	02.01.2015 04:11:50	DEBUG	Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
562	02.01.2015 04:11:50	DEBUG	Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
561	02.01.2015 04:11:50	DEBUG	Redirected import module.plugins.internal.MultiHook -> userplugins.internal.MultiHook
560	02.01.2015 04:11:50	DEBUG	Redirected import module.plugins.hooks.PremiumTo -> userplugins.hooks.PremiumTo
559	02.01.2015 04:11:50	DEBUG	Redirected import module.plugins.hooks.Checksum -> userplugins.hooks.Checksum
558	02.01.2015 04:11:50	DEBUG	Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
557	02.01.2015 04:11:50	DEBUG	Redirected import module.plugins.hooks.ClickAndLoad -> userplugins.hooks.ClickAndLoad
556	02.01.2015 04:11:50	INFO	ExternalScripts: Installed scripts for | package_finished | package_finished.sh
555	02.01.2015 04:11:50	DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
554	02.01.2015 04:11:50	DEBUG	created index of plugins
553	02.01.2015 04:11:47	DEBUG	Remote activated: True

**Comment by vuolter** [comment]
@Mister-XY Please, recheck it now.

**Comment by Mister-XY** [comment]
It's look like good. I can now download with the new premium.to script.

**Comment by dascripta** [comment]
love u guys... great work!
