### ISSUE TITLE
[PremiumizeMe] Sometimes not working

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#984]
28.12.2014 11:43:57 ERROR     PremiumizeMe: 
28.12.2014 11:43:57 ERROR     PremiumizeMe: No hoster loaded

guessing that the issue is since:
https://github.com/pyload/pyload/commit/b72be64cc16660e3ba877d97dbc0e717bb030666#diff-5cb8b7e5d9fcdfa73d07da5793a9e2e3

**Comment by tseroo** [comment]
At least it is partly working now, but the main issue is, that lots of hosters are missing! As you can see from the logs, e.g. uploaded.to is not available. Direct download of uploaded.to links via web browser are working with full speed though!

606	01.01.2015 12:08:36	DEBUG	PremiumizeMe: Regexp: .*(asfile\.com|depfile\.com|mixturecloud\.com|movshare\.net|purevid\.com|shareflare\.net|uploadto\.us|videoweed\.es|vip-file\.com).*
605	01.01.2015 12:08:36	DEBUG	PremiumizeMe: New hosters: asfile.com, depfile.com, mixturecloud.com, movshare.net, purevid.com, shareflare.net, uploadto.us, videoweed.es, vip-file.com
604	01.01.2015 12:08:36	DEBUG	PremiumizeMe: Overwritten hosters: BitshareCom, DepositfilesCom, FilepostCom, FilerNet, FilerioCom, FourSharedCom, LetitbitNet, NetloadIn, NowVideoSx, OneFichierCom, RapidgatorNet, StreamcloudEu, TurbobitNet, UploadableCh, UploadedTo, UptoboxCom

**Comment by vuolter** [comment]
604 01.01.2015 12:08:36 DEBUG PremiumizeMe: Overwritten hosters: BitshareCom, DepositfilesCom, FilepostCom, FilerNet, FilerioCom, FourSharedCom, LetitbitNet, NetloadIn, NowVideoSx, OneFichierCom, RapidgatorNet, StreamcloudEu, TurbobitNet, UploadableCh, __UploadedTo__, UptoboxCom

**Comment by kasperj** [comment]
Everything is working. At least for me it does ;)

**Comment by vuolter** [comment]
So all working... can I smoothly close this issue report now?

**Comment by tseroo** [comment]
@vuolter 

Of course you're right ... overwritten means it was already there before!! 
Problem was that it did not use PremiumizeMe for downloading. Only after disabling/enabling it, it was working again as expected.

So working again :-)

**Comment by snickers2k** [comment]
Does it really work for you guys ?!
I did activate the new PremiumizeMe-Plugin .. 
But i still have the problem, that it's sometimes working - and sometimes not. Without any error.

**Comment by kasperj** [comment]
Which hosters do you use, 90% I use uploaded, and its working

**Comment by snickers2k** [comment]
yeah, me2 .. :( But it's only working sporadically ..

**Comment by vuolter** [comment]
@snickers2k Without a detailed log I'm not able to fix it. :(

**Comment by snickers2k** [comment]
like kasperj .. about 80-90% UploadedTo. 
and sometimes Rapidgator and Share-Online. But lately Premiumize has problems with these hosters.

**Comment by vuolter** [comment]
Without any error?!
In the package view (webui) every link has a status (online, queue, failed, etc.) and when fails reports a status message. No status messages at all?

**Comment by snickers2k** [comment]
no.. no error. normally it worked after restarting pyload, back a few weeks ago.
but now, sporadically its just not working at all, even after restart.
only message is:

INFO	PremiumizeMe: Reloading supported hoster list

**Comment by vuolter** [comment]
Retry now.

**Comment by Gutz-Pilz** [comment]
I can copy that. 
Worked sporadically before wirhout errors.
Now nothing...

Von meinem iPhone gesendet

**Comment by vuolter** [comment]
@Gutz-Pilz Works now or it's broken? :P

**Comment by Gutz-Pilz** [comment]
not working - full broken:/

**Comment by Gutz-Pilz** [comment]
i'll test it 2night

**Comment by snickers2k** [comment]
looks good! i think this finally fixed it.
thank you very much voulter!

**Comment by snickers2k** [comment]
oh boy... today, the problems went back :(

**Comment by Firefly1337** [comment]
Maybe this has nothing to do with pyload.
See PremiumizeMe's Hoster List:

"Download might not work for all our users. Please stand by for further information. "

That would also explain why downloads are working for some of you.

**Comment by snickers2k** [comment]
Hey.
Okay, i know premiumize.me sucks right now. But i think this is more a pyload issue. 
With premiumize-chrome-plugin , uploadable and rapidgator works most of the time. But with pyload, it doesn't. It just starts as free-user. Not a single sign of premium-usage with pyload :(

**Comment by vikwin** [comment]
I can copy that. It always happen for me when downloading from oboom.com. As a workaround, I run this command in the download directory to "resort" the files for extraction:

for f in ./*; do nr="$(unrar l "$f" | grep volume | awk '{ print $6 }')"; if [ "$nr" != ""  ]; then mv "$f" "file.part$nr.rar"; fi; done
