### ISSUE TITLE
ExtractArchive doesn't extract my file (Tells it's empty)

### ISSUE THREAD

**Issue by stefan1495** [pyload/pyload#988]
Hello, i'm not sure if it's an issue or my fault but i didn't find any solution anywhere else.. pyLoad keeps telling me that the File is empty when ExtractArchive.py is trying to extract the file.. It's not empty as i can extract it on my local machine but not on my Synology Diskstation. Here's the logoutput

http://pastebin.com/MdH17uFe

Testarchive: http://speedtest.dal01.softlayer.com/downloads/test.zip

Hope this will be fixed soon :)

**Comment by stefan1495** [comment]
It seems to work with rar but not with ZIP :o

**Comment by michiil** [comment]
Can confirm. Zip files wont work rar fipes work fine

**Comment by vuolter** [comment]
I know that some rar patterns still don't work...

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/8848a359a43316fb346b728d1d79d7b72d27e5a0
Please reopen if not fixed.
