### ISSUE TITLE
Plugin Shareonlinebiz 0.45 premium doesn´t work

### ISSUE THREAD

**Issue by x2ht1** [pyload/pyload#991]
The plugin can not login. I do not get premium status.There are this error message in the log.
" ShareonlineBiz: Could not login with account | 'NoneType' object has no attribute 'load' "

**Comment by Ghoststage** [comment]
ja das selbe hier auch.

**Comment by vuolter** [comment]
Try deleting userplugins directory + accounts.conf file (in config folder), then restart pyload.

**Comment by Ghoststage** [comment]
Habe ich schon gemacht. Habe auch mein NAS neu Formatiert und alles neu gemacht selbe fehler wenn ich pyload beim ersten start NICHT updaten lasse gehtes ohne probleme aber dan gehen andere sachen nicht sobald ich das Update Aktiviere ist es zu ende

**Comment by GammaC0de** [comment]
Working now.
