### ISSUE TITLE
DLC upload is broken

### ISSUE THREAD

**Issue by mbosner** [pyload/pyload#998]
Tested with 3639af423fab5d905e9222f0125aeea2dcf58118 https://github.com/pyload/pyload/commit/3639af423fab5d905e9222f0125aeea2dcf58118

Error:

02.01.2015 01:56:39 ERROR     Error importing DLC: NULL object in marshal data for tuple
02.01.2015 01:56:39 CRITICAL  'NoneType' object has no attribute 'DLC'
Traceback (most recent call last):
  File "/data/media/bin/pyload-versions/stable/module/ThreadManager.py", line 276, in assignJob
    job.initPlugin()
  File "/data/media/bin/pyload-versions/stable/module/utils.py", line 165, in new
    return func(*args)
  File "/data/media/bin/pyload-versions/stable/module/PyFile.py", line 102, in initPlugin
    self.pluginclass = getattr(self.pluginmodule, self.m.core.pluginManager.getPluginName(self.pluginname))

After replacing "module/plugins/container" with the one from the zip version uploading dlc is working again.

**Comment by vuolter** [comment]
What zip version?

**Comment by mbosner** [comment]
http://get.pyload.org/get/src/

**Comment by vuolter** [comment]
Thanks: https://github.com/pyload/pyload/commit/1e5187cb3802c972a451c875e57ff72c41c14b6e

**Comment by mbosner** [comment]
Thank you!
